### ISSUE TITLE
Username & password arguments don't seem to login user and download fails.

### ISSUE THREAD

**Issue by eremiya** [rg3/youtube-dl#10008]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.07.05*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.07.05**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl --verbose --output '~/Downloads/lynda.com/Developer/%(title)s.%(ext)s' https://www.lynda.com/Perl-tutorials/Perl-5-Essential-Training-Revision/447321-2.html --username USERNAME --password PASSWORD
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'--output', u'~/Downloads/lynda.com/Developer/%(title)s.%(ext)s', u'https://www.lynda.com/Perl-tutorials/Perl-5-Essential-Training-Revision/447321-2.html', u'--username', u'PRIVATE', u'--password', u'PRIVATE']
[debug] Encodings: locale US-ASCII, fs utf-8, out US-ASCII, pref US-ASCII
[debug] youtube-dl version 2016.07.05
[debug] Python version 2.7.10 - Darwin-15.5.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[lynda:course] Downloading signin page
[lynda:course] Submitting email
[lynda:course] Submitting password
[lynda:course] 447321: Downloading course JSON
WARNING: 85 videos are only available for members (or paid members) and will not be downloaded. Use --username and --password options to provide lynda.com account credentials.
[download] Downloading playlist: Perl 5 Essential Training
[lynda:course] playlist Perl 5 Essential Training: Collected 7 video ids (downloading 7 of them)
[download] Downloading video 1 of 7
[lynda] Downloading signin page
[lynda] 484118: Downloading video JSON
[lynda] 484118: Checking 1-540 video format URL
[lynda] 484118: Checking 1-720 video format URL
[lynda] 484118: Checking 1-360 video format URL
[lynda] 484118: Checking 0-540 video format URL
[lynda] 484118: Checking 0-720 video format URL
[lynda] 484118: Checking 0-360 video format URL
[lynda] 484118: Checking 2-540 video format URL
[lynda] 484118: Checking 2-720 video format URL
[lynda] 484118: Checking 2-360 video format URL
ERROR: unable to open for writing: [Errno 21] Is a directory: '~/Downloads/lynda.com/Developer/'
jeremie-Desktop:
jeremie-Desktop:youtube-dl --verbose --output ~/Downloads/lynda.com/Developer/%(title)s.%(ext)s --cookies cookies.txt https://www.lynda.com/Perl-tutorials/Perl-5-Essential-Training-Revision/447321-2.html --username jeremie@cubytz.com --password manu3lla --user-agent "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36"
-bash: syntax error near unexpected token `('
jeremie-Desktop:youtube-dl --verbose --output ~/Downloads/lynda.com/Developer/%(title)s.%(ext)s --cookies cookies.txt https://www.lynda.com/Perl-tutorials/Perl-5-Essential-Training-Revision/447321-2.html --username jeremie@cubytz.com --password manu3lla --user-agent "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36"
jeremie-Desktop:youtube-dl --verbose --output '~/Downloads/lynda.com/Developer/%(title)s.%(ext)s' --cookies cookies.txt https://www.lynda.com/Perl-tutorials/Perl-5-Essential-Training-Revision/447321-2.html --username jeremie@cubytz.com --password manu3lla --user-agent "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'--output', u'~/Downloads/lynda.com/Developer/%(title)s.%(ext)s', u'--cookies', u'cookies.txt', u'https://www.lynda.com/Perl-tutorials/Perl-5-Essential-Training-Revision/447321-2.html', u'--username', u'PRIVATE', u'--password', u'PRIVATE', u'--user-agent', u'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36']
[debug] Encodings: locale US-ASCII, fs utf-8, out US-ASCII, pref US-ASCII
[debug] youtube-dl version 2016.07.03.1
[debug] Python version 2.7.10 - Darwin-15.5.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[lynda:course] Downloading signin page
[lynda:course] 447321: Downloading course JSON
WARNING: 85 videos are only available for members (or paid members) and will not be downloaded. Use --username and --password options to provide lynda.com account credentials.
[download] Downloading playlist: Perl 5 Essential Training
[lynda:course] playlist Perl 5 Essential Training: Collected 7 video ids (downloading 7 of them)
[download] Downloading video 1 of 7
[lynda] Downloading signin page
[lynda] 484118: Downloading video JSON
[lynda] 484118: Checking 1-540 video format URL
[lynda] 484118: Checking 1-720 video format URL
[lynda] 484118: Checking 1-360 video format URL
[lynda] 484118: Checking 0-540 video format URL
[lynda] 484118: Checking 0-720 video format URL
[lynda] 484118: Checking 0-360 video format URL
[lynda] 484118: Checking 2-540 video format URL
[lynda] 484118: Checking 2-720 video format URL
[lynda] 484118: Checking 2-360 video format URL
[debug] Invoking downloader on u'http://files2.lynda.com/secure/courses/447321/VBR_MP4h264_main_HD720/447321_00_01_WX30_welcome.mp4?c3.ri=3770488891909531538&hashval=1467706709_fad5ba316235ddef63fb298089189dea'
[download] Destination: ~/Downloads/lynda.com/Developer/Welcome.mp4
[download] 100% of 3.03MiB in 00:00
[download] Downloading video 2 of 7
[lynda] 484119: Downloading video JSON
[lynda] 484119: Checking 1-540 video format URL
[lynda] 484119: Checking 1-720 video format URL
[lynda] 484119: Checking 1-360 video format URL
[lynda] 484119: Checking 0-540 video format URL
[lynda] 484119: Checking 0-720 video format URL
[lynda] 484119: Checking 0-360 video format URL
[lynda] 484119: Checking 2-540 video format URL
[lynda] 484119: Checking 2-720 video format URL
[lynda] 484119: Checking 2-360 video format URL
[debug] Invoking downloader on u'http://files2.lynda.com/secure/courses/447321/VBR_MP4h264_main_HD720/447321_00_02_XR15_exfiles.mp4?c3.ri=3770207350291988353&hashval=1467706758_0147c994b6a03f0c6a009ca7e61789cc'
[download] Destination: ~/Downloads/lynda.com/Developer/Exercise files.mp4
[download] 100% of 3.06MiB in 00:00
[download] Downloading video 3 of 7
[lynda] 484121: Downloading video JSON
[lynda] 484121: Checking 1-540 video format URL
[lynda] 484121: Checking 1-720 video format URL
[lynda] 484121: Checking 1-360 video format URL
[lynda] 484121: Checking 0-540 video format URL
[lynda] 484121: Checking 0-720 video format URL
[lynda] 484121: Checking 0-360 video format URL
[lynda] 484121: Checking 2-540 video format URL
[lynda] 484121: Checking 2-720 video format URL
[lynda] 484121: Checking 2-360 video format URL
[debug] Invoking downloader on u'http://files2.lynda.com/secure/courses/447321/VBR_MP4h264_main_HD720/447321_01_01_XR15_instmac.mp4?c3.ri=3770207350291988715&hashval=1467706810_0f5fb4be953d9e2b3f303bb28d332dd8'
[download] Destination: ~/Downloads/lynda.com/Developer/Installing Komodo for Mac OS X.mp4
[download] 100% of 18.14MiB in 00:05
[download] Downloading video 4 of 7
[lynda] 484125: Downloading video JSON
[lynda] 484125: Checking 1-540 video format URL
[lynda] 484125: Checking 1-720 video format URL
[lynda] 484125: Checking 1-360 video format URL
[lynda] 484125: Checking 0-540 video format URL
[lynda] 484125: Checking 0-720 video format URL
[lynda] 484125: Checking 0-360 video format URL
[lynda] 484125: Checking 2-540 video format URL
[lynda] 484125: Checking 2-720 video format URL
[lynda] 484125: Checking 2-360 video format URL
[debug] Invoking downloader on u'http://files2.lynda.com/secure/courses/447321/VBR_MP4h264_main_HD720/447321_02_01_XR15_quickstart.mp4?c3.ri=3770207350291989161&hashval=1467706864_c06e526ecc3e5e8c429911de7559f17c'
[download] Destination: ~/Downloads/lynda.com/Developer/About the quick start.mp4
[download] 100% of 896.60KiB in 00:00
[download] Downloading video 5 of 7
[lynda] 484132: Downloading video JSON
[lynda] 484132: Checking 1-540 video format URL
[lynda] 484132: Checking 1-720 video format URL
[lynda] 484132: Checking 1-360 video format URL
[lynda] 484132: Checking 0-540 video format URL
[lynda] 484132: Checking 0-720 video format URL
[lynda] 484132: Checking 0-360 video format URL
[lynda] 484132: Checking 2-540 video format URL
[lynda] 484132: Checking 2-720 video format URL
[lynda] 484132: Checking 2-360 video format URL
[debug] Invoking downloader on u'http://files2.lynda.com/secure/courses/447321/VBR_MP4h264_main_HD720/447321_03_01_XR15_anatomy.mp4?c3.ri=3770488891909533767&hashval=1467706917_3c9767d2770f39ee486be33c9c5319fd'
[download] Destination: ~/Downloads/lynda.com/Developer/Anatomy of a Perl script.mp4
[download] 100% of 14.86MiB in 00:04
[download] Downloading video 6 of 7
[lynda] 484138: Downloading video JSON
[lynda] 484138: Checking 1-540 video format URL
[lynda] 484138: Checking 1-720 video format URL
[lynda] 484138: Checking 1-360 video format URL
[lynda] 484138: Checking 0-540 video format URL
[lynda] 484138: Checking 0-720 video format URL
[lynda] 484138: Checking 0-360 video format URL
[lynda] 484138: Checking 2-540 video format URL
[lynda] 484138: Checking 2-720 video format URL
[lynda] 484138: Checking 2-360 video format URL
[debug] Invoking downloader on u'http://files2.lynda.com/secure/courses/447321/VBR_MP4h264_main_HD720/447321_04_01_XR15_values.mp4?c3.ri=3770488891909534523&hashval=1467706976_f8ac6d7036a106006641cff95966c554'
[download] Destination: ~/Downloads/lynda.com/Developer/Understanding values and variables.mp4
[download] 100% of 5.20MiB in 00:01
[download] Downloading video 7 of 7
[lynda] 484147: Downloading video JSON
[lynda] 484147: Checking 1-540 video format URL
[lynda] 484147: Checking 1-720 video format URL
[lynda] 484147: Checking 1-360 video format URL
[lynda] 484147: Checking 0-540 video format URL
[lynda] 484147: Checking 0-720 video format URL
[lynda] 484147: Checking 0-360 video format URL
[lynda] 484147: Checking 2-540 video format URL
[lynda] 484147: Checking 2-720 video format URL
[lynda] 484147: Checking 2-360 video format URL
[debug] Invoking downloader on u'http://files2.lynda.com/secure/courses/447321/VBR_MP4h264_main_HD720/447321_05_01_XR15_if.mp4?c3.ri=3770488891909535087&hashval=1467707028_a68a7eebf99617c6a80c1ff7f1243a1a'
[download] Destination: ~/Downloads/lynda.com/Developer/The if statement.mp4
[download] 100% of 8.32MiB in 00:03
[download] Finished downloading playlist: Perl 5 Essential Training
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

---

### Description of your *issue*, suggested solution and other information
I am trying to download a course on Lynda.com and follow all the tutorials I found on the subject but I can't make it work. I use OS X El Capitan and the latest version of youtude-dl.
```
youtube-dl --version
2016.07.05
```
I installed it using the curl command on the readme page. When I run the command, I have the output above. It only downloads the free videos, as if I am not logged in.
I verified my credentials, and they work on a browser.
I also tried using the cookies argument, but no luck there too. It gives me the same output as above.
I tried to download a single video using the link, but I get error below :

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'--output', u'/~/Downloads/lynda.com/Developer/%(title)s.%(ext)s', u'https://www.lynda.com/Perl-tutorials/Installing-Perl-Komodo-Windows/447321/484122-4.html?', u'--username', u'PRIVATE', u'--password', u'PRIVATE']
[debug] Encodings: locale US-ASCII, fs utf-8, out US-ASCII, pref US-ASCII
[debug] youtube-dl version 2016.07.05
[debug] Python version 2.7.10 - Darwin-15.5.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[lynda] Downloading signin page
[lynda] Submitting email
[lynda] Submitting password
[lynda] 484122: Downloading video JSON
ERROR: lynda returned error: Video not found
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 681, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 343, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/lynda.py", line 124, in _real_extract
    'lynda returned error: %s' % video['Message'], expected=True)
ExtractorError: lynda returned error: Video not found
```
Which makes me think that the sign in doesn't work properly and redirect to the login page, but that is just MHO.

Am I missing something?
Thank you so much for your help!

**Comment by dstftw** [comment]
Can you watch https://www.lynda.com/Perl-tutorials/Installing-Perl-Komodo-Windows/447321/484122-4.html in browser?
Post the output of `youtube-dl -v --dump-pages -u login -p password https://www.lynda.com/Perl-tutorials/Installing-Perl-Komodo-Windows/447321/484122-4.html`.

**Comment by eremiya** [comment]
Hello,
Thank you for your reply. I am truly sorry but I found that there was a problem with my account.
This is resolved and it works great!

Thank you and sorry again.

**Comment by cyberjoshan** [comment]
hey 
i am getting

ERROR: lynda returned error: Session has expired

while trying 
youtube-dl -v --dump-pages -u login -p password https://www.lynda.com/Perl-tutorials/Installing-Perl-Komodo-Windows/447321/484122-4.html.

on version 2016.10.12

can anyone help me ?
