### ISSUE TITLE
NineCNineMedia: ERROR: multiple stacks;

### ISSUE THREAD

**Issue by RingoTheDog** [rg3/youtube-dl#10016]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.07.05*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.07.05**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
youtube-dl.py -v "http://www.ctv.ca/video/player?vid=902194"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.ctv.ca/video/player?vid=902194']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.07.05
[debug] Python version 3.5.1 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-71727-g46778ab, rtmpdump 2.4
[debug] Proxy map: {}
[NineCNineMedia] 902194: Downloading JSON metadata
[NineCNineMedia] 902194: Downloading JSON metadata
ERROR: multiple stacks; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to
ag and include its complete output.
Traceback (most recent call last):
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 681, in extract_info
    ie_result = ie.extract(url)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\common.py", line 343, in extract
    return self._real_extract(url)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\ninecninemedia.py", line 30, in _real_extract
    raise ExtractorError('multiple stacks')
youtube_dl.utils.ExtractorError: multiple stacks; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl
e-dl with the --verbose flag and include its complete output.


...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://www.ctv.ca/video/player?vid=902194
- Single video: http://www.ctv.ca/Conan/video.aspx?vid=899961
- Playlist: http://www.ctvnews.ca/sci-tech/jupiter-meet-juno-nasa-s-ultimately-doomed-solar-powered-spacecraft-1.2973225

---

### Description of your *issue*, suggested solution and other information

BTW.....other URLS that also use 9c9 include:
http://www.tsn.ca/video/fiba-turkey-69-canada-77~904611
http://www.bnn.ca/Video/player.aspx?vid=904811
http://www.cp24.com/video#903450

**Comment by RingoTheDog** [comment]
Not sure if it will help anyone...but vpnbook has a free VPN in Canada available:
http://www.vpnbook.com/
