### ISSUE TITLE
youtube.com Signature extraction failed

### ISSUE THREAD

**Issue by Ta7ady** [rg3/youtube-dl#10020]
# youtube-dl https://www.youtube.com/watch?v=HKcvbi6sNEU -v
[debug] System config: [u'--prefer-free-formats']
[debug] User config: []
[debug] Command-line args: [u'https://www.youtube.com/watch?v=HKcvbi6sNEU', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.06.03
[debug] Python version 2.7.5 - Linux-3.10.0-327.22.2.el7.x86_64-x86_64-with-centos-7.2.1511-Core
[debug] exe versions: ffmpeg 2.6.8, ffprobe 2.6.8
[debug] Proxy map: {}
[youtube] HKcvbi6sNEU: Downloading webpage
[youtube] HKcvbi6sNEU: Downloading video info webpage
[youtube] HKcvbi6sNEU: Extracting video information
[youtube] {43} signature length 40.45, html5 player en_US-vflAbrXV8
[youtube] HKcvbi6sNEU: Downloading player https://s.ytimg.com/yts/jsbin/player-en_US-vflAbrXV8/base.js
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 995, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 910, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 973, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/lib/python2.7/site-packages/youtube_dl/jsinterp.py", line 241, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
ExtractorError: Could not find JS function u'wr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Could not find JS function u'wr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 995, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 910, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 973, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/lib/python2.7/site-packages/youtube_dl/jsinterp.py", line 241, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
ExtractorError: Could not find JS function u'wr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 676, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 341, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 1568, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 1005, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 995, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 910, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 973, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/lib/python2.7/site-packages/youtube_dl/jsinterp.py", line 241, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
ExtractorError: Could not find JS function u'wr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Could not find JS function u'wr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by phihag** [comment]
You are using an outdated version of youtube-dl. Refer to [our FAQ](https://yt-dl.org/update) on how to update.
