### ISSUE TITLE
Can play with MPV, can't download

### ISSUE THREAD

**Issue by horusra** [rg3/youtube-dl#10037]
Trying to download: http://www.c-span.org/video/?c4609395/special-access-programs-involved
getting error:
ssl.CertificateError: hostname 'data.c-spanvideo.org.s3.amazonaws.com' doesn't match either of '*.s3.amazonaws.com', 's3.amazonaws.com'

Using the same link on MPV + Youtube-dl does open the player and actually plays the video though.

```
C:\Program Files\MPV>youtube-dl.exe --output "I:\Youtube\%(title)s.%(ext)s" --cookies "C:\Program Files\MPV\cookies.txt" --no-playlist --all-subs -f=bestvideo+bestaudio/best --verbose http://www.c-span.org/video/?c4609395/special-access-programs-involved
[debug] System config: []
[debug] User config: ['--output', 'I:\\Lynda\\%(playlist)s\\%(playlist)s_%(playlist_index)s_%(title)s.%(ext)s', '--cookies', 'C:\\Program Files\\MPV\\cookies.txt', '--no-mtime']
[debug] Command-line args: ['--output', 'I:\\Youtube\\%(title)s.%(ext)s', '--cookies', 'C:\\Program Files\\MPV\\cookies.txt', '--no-playlist', '--all-subs', '-f=bestvideo+bestaudio/best', '--verbose', 'http://www.c-span.org/video/?c4609395/special-access-programs-involved']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.07.07
[debug] Python version 3.4.4 - Windows-10-10.0.10240
[debug] exe versions: none
[debug] Proxy map: {}
[CSpan] c4609395: Downloading webpage
[CSpan] 4609395: Downloading JSON metadata
[CSpan] 4609395: Downloading XML
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp1_rvenhi\build\youtube_dl\__init__.py", line 422, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp1_rvenhi\build\youtube_dl\__init__.py", line 412, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp1_rvenhi\build\youtube_dl\YoutubeDL.py", line 1745, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp1_rvenhi\build\youtube_dl\YoutubeDL.py", line 692, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp1_rvenhi\build\youtube_dl\YoutubeDL.py", line 738, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp1_rvenhi\build\youtube_dl\YoutubeDL.py", line 1391, in process_video_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp1_rvenhi\build\youtube_dl\YoutubeDL.py", line 1556, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp1_rvenhi\build\youtube_dl\extractor\common.py", line 503, in _download_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp1_rvenhi\build\youtube_dl\extractor\common.py", line 410, in _download_webpage_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp1_rvenhi\build\youtube_dl\extractor\common.py", line 390, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp1_rvenhi\build\youtube_dl\YoutubeDL.py", line 1955, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp1_rvenhi\build\youtube_dl\utils.py", line 1002, in https_open
  File "C:\Python\Python34\lib\urllib\request.py", line 1183, in do_open
  File "C:\Python\Python34\lib\http\client.py", line 1137, in request
  File "C:\Python\Python34\lib\http\client.py", line 1182, in _send_request
  File "C:\Python\Python34\lib\http\client.py", line 1133, in endheaders
  File "C:\Python\Python34\lib\http\client.py", line 963, in _send_output
  File "C:\Python\Python34\lib\http\client.py", line 898, in send
  File "C:\Python\Python34\lib\http\client.py", line 1287, in connect
  File "C:\Python\Python34\lib\ssl.py", line 362, in wrap_socket
  File "C:\Python\Python34\lib\ssl.py", line 580, in __init__
  File "C:\Python\Python34\lib\ssl.py", line 815, in do_handshake
  File "C:\Python\Python34\lib\ssl.py", line 282, in match_hostname
ssl.CertificateError: hostname 'data.c-spanvideo.org.s3.amazonaws.com' doesn't match either of '*.s3.amazonaws.com', 's3.amazonaws.com'
```

**Comment by horusra** [comment]
--no-check certificate doesn't work either

```
C:\Program Files\MPV>youtube-dl.exe --output "I:\Youtube\%(title)s.%(ext)s" --cookies "C:\Program Files\MPV\cookies.txt" --no-playlist --all-subs -f=bestvideo+bestaudio/best --verbose --no-check certificate http://www.c-span.org/video/?c4609395/special-access-programs-involved
[debug] System config: []
[debug] User config: ['--output', 'I:\\Lynda\\%(playlist)s\\%(playlist)s_%(playlist_index)s_%(title)s.%(ext)s', '--cookies', 'C:\\Program Files\\MPV\\cookies.txt', '--no-mtime']
[debug] Command-line args: ['--output', 'I:\\Youtube\\%(title)s.%(ext)s', '--cookies', 'C:\\Program Files\\MPV\\cookies.txt', '--no-playlist', '--all-subs', '-f=bestvideo+bestaudio/best', '--verbose', '--no-check', 'certificate', 'http://www.c-span.org/video/?c4609395/special-access-programs-involved']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.07.07
[debug] Python version 3.4.4 - Windows-10-10.0.10240
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] certificate: Downloading webpage
[youtube] certificate: Downloading video info webpage
ERROR: certificate: YouTube said: This video does not exist.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp1_rvenhi\build\youtube_dl\YoutubeDL.py", line 681, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp1_rvenhi\build\youtube_dl\extractor\common.py", line 343, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp1_rvenhi\build\youtube_dl\extractor\youtube.py", line 1317, in _real_extract
youtube_dl.utils.ExtractorError: certificate: YouTube said: This video does not exist.
```

**Comment by yan12125** [comment]
It's ```--no-check-certificate```. See https://github.com/rg3/youtube-dl/issues/7309#issuecomment-204692846 for a detailed discussion.
