### ISSUE TITLE
YouTube download fails

### ISSUE THREAD

**Issue by royale1223** [rg3/youtube-dl#1004]
```
$ youtube-dl -u $usn -p $pwd http://www.youtube.com/watch?v=xD27z1EmLaM
[youtube] Setting language
[youtube] Logging in
[youtube] Confirming age
[youtube] xD27z1EmLaM: Downloading video webpage
[youtube] xD27z1EmLaM: Downloading video info webpage
[youtube] xD27z1EmLaM: Extracting video information
ERROR: no known formats available for video; please report this issue on GitHub.
binoy@binoy-pc:~$ youtube-dl -u $usn -p $pwd http://www.youtube.com/watch?v=xD27z1EmLaM -v[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-u', '$usn', '-p', '$pwd', 'http://www.youtube.com/watch?v=xD27z1EmLaM', '-v']
[debug] youtube-dl version 2013.06.21
[debug] Python version 2.7.4 - Linux-3.8.0-26-generic-i686-with-Ubuntu-13.04-raring
[debug] Proxy map: {}
[youtube] Setting language
[youtube] Logging in
[youtube] Confirming age
[youtube] xD27z1EmLaM: Downloading video webpage
[youtube] xD27z1EmLaM: Downloading video info webpage
[youtube] xD27z1EmLaM: Extracting video information
ERROR: no known formats available for video; please report this issue on GitHub.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/FileDownloader.py", line 465, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/InfoExtractors.py", line 99, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/InfoExtractors.py", line 747, in _real_extract
    raise ExtractorError(u'no known formats available for video')
ExtractorError: no known formats available for video; please report this issue on GitHub.
```

**Comment by dstftw** [comment]
This video has been removed by the user. Feel free to open a new issue if can reproduce with another video.
