### ISSUE TITLE
iqiyi couldnt download some vedio

### ISSUE THREAD

**Issue by weigeloveu** [rg3/youtube-dl#10068]
Microsoft Windows [版本 10.0.10586](c) 2015 Microsoft Corporation。保留所有权利。

C:\Users\wei>youtube-dl -v http://www.iqiyi.com/v_19rrl18u40.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.iqiyi.com/v_19rrl18u40.html']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2016.07.11
[debug] Python version 3.5.2 - Windows-10-10.0.10586-SP0
[debug] exe versions: ffmpeg N-80955-g5939878, ffprobe N-80955-g5939878
[debug] Proxy map: {}
[iqiyi] temp_id: download video page
[iqiyi] 093aae408729001c3c3d5cc3d0f14789: Downloading JSON metadata
[debug] Invoking downloader on 'http://cache.m.iqiyi.com/dc/dt/text/18753d83x20fe0ad5x777a6171/20160326/eb/70/ab531dd4a5547d0cbddb86d14cdec6e5.m3u8?qd_sc=4cefedbea7ffcf258841cc9968868134&t_sign=-0-76f90cbd92f94a2e925d83e8ccd22cb7-463644700_04022000001000000000_18'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 598
[download] Destination: ：1860年代：太平天国与南北战争（上）-093aae408729001c3c3d5cc3d0f14789.mp4
[download]   0.2% of ~2.79GiB at  1.37MiB/s ETA 35:59      ERROR: unable to download video data: <urlopen error [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。>
Traceback (most recent call last):
  File "c:\users\wei\appdata\local\programs\python\python35-32\lib\urllib\request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "c:\users\wei\appdata\local\programs\python\python35-32\lib\http\client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "c:\users\wei\appdata\local\programs\python\python35-32\lib\http\client.py", line 1151, in _send_request
    self.endheaders(body)
  File "c:\users\wei\appdata\local\programs\python\python35-32\lib\http\client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "c:\users\wei\appdata\local\programs\python\python35-32\lib\http\client.py", line 934, in _send_output
    self.send(msg)
  File "c:\users\wei\appdata\local\programs\python\python35-32\lib\http\client.py", line 877, in send
    self.connect()
  File "c:\users\wei\appdata\local\programs\python\python35-32\lib\http\client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "c:\users\wei\appdata\local\programs\python\python35-32\lib\socket.py", line 711, in create_connection
    raise err
  File "c:\users\wei\appdata\local\programs\python\python35-32\lib\socket.py", line 702, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\wei\appdata\local\programs\python\python35-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 1653, in process_info
    success = dl(filename, info_dict)
  File "c:\users\wei\appdata\local\programs\python\python35-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 1595, in dl
    return fd.download(name, info)
  File "c:\users\wei\appdata\local\programs\python\python35-32\lib\site-packages\youtube_dl\downloader\common.py", line 350, in download
    return self.real_download(filename, info_dict)
  File "c:\users\wei\appdata\local\programs\python\python35-32\lib\site-packages\youtube_dl\downloader\hls.py", line 98, in real_download
    success = ctx['dl'].download(frag_filename, {'url': frag_url})
  File "c:\users\wei\appdata\local\programs\python\python35-32\lib\site-packages\youtube_dl\downloader\common.py", line 350, in download
    return self.real_download(filename, info_dict)
  File "c:\users\wei\appdata\local\programs\python\python35-32\lib\site-packages\youtube_dl\downloader\http.py", line 58, in real_download
    data = self.ydl.urlopen(request)
  File "c:\users\wei\appdata\local\programs\python\python35-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 1955, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "c:\users\wei\appdata\local\programs\python\python35-32\lib\urllib\request.py", line 472, in open
    response = meth(req, response)
  File "c:\users\wei\appdata\local\programs\python\python35-32\lib\urllib\request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\users\wei\appdata\local\programs\python\python35-32\lib\urllib\request.py", line 504, in error
    result = self._call_chain(_args)
  File "c:\users\wei\appdata\local\programs\python\python35-32\lib\urllib\request.py", line 444, in _call_chain
    result = func(_args)
  File "c:\users\wei\appdata\local\programs\python\python35-32\lib\urllib\request.py", line 696, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "c:\users\wei\appdata\local\programs\python\python35-32\lib\urllib\request.py", line 466, in open
    response = self._open(req, data)
  File "c:\users\wei\appdata\local\programs\python\python35-32\lib\urllib\request.py", line 484, in _open
    '_open', req)
  File "c:\users\wei\appdata\local\programs\python\python35-32\lib\urllib\request.py", line 444, in _call_chain
    result = func(*args)
  File "c:\users\wei\appdata\local\programs\python\python35-32\lib\site-packages\youtube_dl\utils.py", line 838, in http_open
    req)
  File "c:\users\wei\appdata\local\programs\python\python35-32\lib\urllib\request.py", line 1256, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。>

**Comment by yan12125** [comment]
Apparently there are bugs in Github... This issue does not show up in my notifications until just now.

10060 indicates that your connection is unstable. Try more times and you can get the full video.
