### ISSUE TITLE
Link not working?

### ISSUE THREAD

**Issue by blackrum** [rg3/youtube-dl#10073]
C:\Users>youtube-dl http://www.vier.be/dewereldvan/videos/de-wereld-van-bellewaerde-s2-aflevering-4/988890 -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://www.vier.be/dewereldvan/videos/de-wereld-van-bellewaerde-s2-aflevering-4/988890', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.07.11
[debug] Python version 3.4.4 - Windows-10-10.0.10586
[debug] exe versions: ffmpeg N-78313-g6632802
[debug] Proxy map: {}
[vier] de-wereld-van-bellewaerde-s2-aflevering-4: Downloading webpage
ERROR: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpaqp3kvn1\build\youtube_dl\YoutubeDL.py", line 681, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpaqp3kvn1\build\youtube_dl\extractor\common.py", line 347, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpaqp3kvn1\build\youtube_dl\extractor\vier.py", line 43, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpaqp3kvn1\build\youtube_dl\extractor\common.py", line 650, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Thanks in advance for helping out

**Comment by blackrum** [comment]
Sorry I'm a noob, but Is an account needed? It used to work a few months ago without account.

**Comment by dstftw** [comment]
It does not play in browser. Instead it asks to register an account.

**Comment by blackrum** [comment]
Well, this was not the case before. Is there any way around to get them?

**Comment by seghers** [comment]
+1

**Comment by midas02** [comment]
Duplicate of  #7168

**Comment by yan12125** [comment]
@midas02 Thanks.
