### ISSUE TITLE
Site request: Dish anywhere / sling player

### ISSUE THREAD

**Issue by keybounce** [rg3/youtube-dl#10085]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.07.13*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2016.07.13**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
keybounceMBP:Keybounce michael$ youtube-dl -v "http://www.dishanywhere.com/shows/marvels_ultimate_spiderman_vs_the_sinister
_6_p136571346?tab=dvr"
[debug] System config: []
[debug] User config: [u'-o', u'%(title)s.%(ext)s', u'-f', u'\nbest[ext=mp4][height>431][height<=719]/\nbestvideo[ext=mp4][height=480]+bestaudio[ext=m4a]/\nbest[ext=mp4][height>340][height<=431]/\nbestvideo[ext=mp4][height>360][height<=576]+bestaudio/\nbest[height>340][height<=576]/\nbestvideo[height>360][height<=576]+bestaudio/\nbestvideo[height=360]+bestaudio/\nbest[ext=mp4][height>=280][height<=360]/\nbest[height<=576]/\nworst', u'--write-sub', u'--embed-subs', u'--recode-video', u'mp4', u'--mark-watched']
[debug] Command-line args: [u'-v', u'http://www.dishanywhere.com/shows/marvels_ultimate_spiderman_vs_the_sinister_6_p136571346?tab=dvr']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.07.13
[debug] Python version 2.7.5 - Darwin-13.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.1.1, ffprobe 3.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] marvels_ultimate_spiderman_vs_the_sinister_6_p136571346?tab=dvr: Requesting header
WARNING: Falling back on generic information extractor.
[generic] marvels_ultimate_spiderman_vs_the_sinister_6_p136571346?tab=dvr: Downloading webpage
[generic] marvels_ultimate_spiderman_vs_the_sinister_6_p136571346?tab=dvr: Extracting information
ERROR: Unsupported URL: http://www.dishanywhere.com/shows/marvels_ultimate_spiderman_vs_the_sinister_6_p136571346?tab=dvr
Traceback (most recent call last):
  File "/Users/michael/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1565, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/Users/michael/bin/youtube-dl/youtube_dl/compat.py", line 2525, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/Users/michael/bin/youtube-dl/youtube_dl/compat.py", line 2514, in _XML
    parser.feed(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 40, column 724
Traceback (most recent call last):
  File "/Users/michael/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 681, in extract_info
    ie_result = ie.extract(url)
  File "/Users/michael/bin/youtube-dl/youtube_dl/extractor/common.py", line 347, in extract
    return self._real_extract(url)
  File "/Users/michael/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2282, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.dishanywhere.com/shows/marvels_ultimate_spiderman_vs_the_sinister_6_p136571346?tab=dvr

```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):

Typical playlist (all recorded episodes of a series): 
http://www.dishanywhere.com/shows/the_late_show_with_stephen_colbert_p136124004?tab=dvr

http://www.dishanywhere.com/shows/marvels_ultimate_spiderman_vs_the_sinister_6_p136571346?tab=dvr

All on-demand episodes of a show
http://www.dishanywhere.com/shows/marvels_ultimate_spiderman_vs_the_sinister_6_p136571346?tab=ondemand

Typical specific episodes:
On demand: http://www.dishanywhere.com/shows/marvels_ultimate_spiderman_vs_the_sinister_6_p136571346/episodes/4758048/2112288/

Normal recordings:
http://www.dishanywhere.com/sling/8008/16789505

NB: This site requires a login, obviously. Less obviously: recordings will either wind up redirecting to local network (if you can talk directly to the recorder) or passing through dish's server (if you are not at home -- firewalls prevent direct contact with the receiver).

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* required an account credentials please provide them or explain how one can obtain them.

**Comment by keybounce** [comment]
If you need to use my tv provider information to do this, let me know. (Is that what the tag means?)
