### ISSUE TITLE
Did not download audio, only video (dash format)

### ISSUE THREAD

**Issue by keybounce** [rg3/youtube-dl#10083]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.07.13*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2016.07.13**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

I got a video without audio; not sure why.

```
keybounceMBP:OtherCM4 michael$ youtube-dl -v https://www.youtube.com/watch?v=x0RvjXXFeck
[debug] System config: []
[debug] User config: [u'-o', u'%(title)s.%(ext)s', u'-f', u'\nbest[ext=mp4][height>431][height<=719]/\nbestvideo[ext=mp4][height=480]+bestaudio[ext=m4a]/\nbest[ext=mp4][height>340][height<=431]/\nbestvideo[ext=mp4][height>360][height<=576]+bestaudio/\nbest[height>340][height<=576]/\nbestvideo[height>360][height<=576]+bestaudio/\nbestvideo[height=360]+bestaudio/\nbest[ext=mp4][height>=280][height<=360]/\nbest[height<=576]/\nworst', u'--write-sub', u'--embed-subs', u'--recode-video', u'mp4', u'--mark-watched']
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=x0RvjXXFeck']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.07.13
[debug] Python version 2.7.5 - Darwin-13.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.0.2, ffprobe 3.0.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] x0RvjXXFeck: Downloading webpage
[youtube] x0RvjXXFeck: Downloading video info webpage
[youtube] x0RvjXXFeck: Extracting video information
WARNING: video doesn't have subtitles
[youtube] x0RvjXXFeck: Downloading MPD manifest
[youtube] x0RvjXXFeck: Downloading MPD manifest
[debug] Invoking downloader on u'https://r6---sn-a5meknee.googlevideo.com/videoplayback/id/c7446f8d75c579c9/itag/135/source/yt_otf/requiressl/yes/initcwndbps/430000/pl/21/nh/IgpwcjAxLmxheDE2KgkxMjcuMC4wLjE/mn/sn-a5meknee/mm/31/ms/au/mv/m/ratebypass/yes/mime/video%2Fmp4/otfp/1/otf/1/lmt/1465968767332073/key/dg_yt0/mt/1468462601/signature/576BFF6BA424965A3211CB2BE907DD43D27D5AF8.5CE0AC5B1DF1B9B45CA0ED1CA1DDAA5FF71020D6/upn/ObSsecJ6LH4/sver/3/fexp/9407157,9413138,9416126,9416891,9419451,9422596,9424134,9428398,9429856,9431012,9433096,9433380,9433946,9435526,9435876,9435922,9436635,9437066,9437078,9437552,9437742,9438663,9438731,9439601,9439652,9440364,9440376/ip/108.192.89.65/ipbits/0/expire/1468484485/sparams/ip,ipbits,expire,id,itag,source,requiressl,initcwndbps,pl,nh,mn,mm,ms,mv,ratebypass,mime,otfp,otf,lmt/'
[dashsegments] Total fragments: 1093
[download] Destination: Deconstructing Captive Minecraft IV - Winter Realm [Minecraft 1.10] (HD 1080p 60fps).mp4
[download]  93.0% of ~611.20MiB at 630.17KiB/s ETA 01:52[download] Got server HTTP error. Retrying fragment Seg1016 (attempt 1 of 10)...
[download] Got server HTTP error. Retrying fragment Seg1016 (attempt 2 of 10)...
[download] Got server HTTP error. Retrying fragment Seg1016 (attempt 3 of 10)...
[download] Got server HTTP error. Retrying fragment Seg1016 (attempt 4 of 10)...
[download] Got server HTTP error. Retrying fragment Seg1016 (attempt 5 of 10)...
[download] Got server HTTP error. Retrying fragment Seg1016 (attempt 6 of 10)...
[download] Got server HTTP error. Retrying fragment Seg1016 (attempt 7 of 10)...
[download] 100% of 573.40MiB in 25:45
  fmpeg] Not converting video file Deconstructing Captive Minecraft IV - Winter Realm [Minecraft 1.10] (HD 1080p 60fps).mp4 - already is in target format mp4
[ffmpeg] There aren't any subtitles to embed
keybounceMBP:OtherCM4 michael$
```

The first video format fails (there is a 720p file, but I'm excluding that).
The second format line is bestvideo[ext=mp4][height=480]+bestaudio[ext=m4a] -- and there is a 480 dash video and audio.

But what I get is video only.

```
keybounceMBP:OtherCM4 michael$ youtube-dl -F https://www.youtube.com/watch?v=x0RvjXXFeck
[youtube] x0RvjXXFeck: Downloading webpage
[youtube] x0RvjXXFeck: Downloading video info webpage
[youtube] x0RvjXXFeck: Extracting video information
WARNING: video doesn't have subtitles
[youtube] x0RvjXXFeck: Downloading MPD manifest
[youtube] x0RvjXXFeck: Downloading MPD manifest
[info] Available formats for x0RvjXXFeck:
format code  extension  resolution note
140          m4a        audio only DASH audio  149k , m4a_dash container, mp4a.40.2@128k (44100Hz)
160          mp4        256x144    DASH video  108k , avc1.4d400b, 30fps, video only
133          mp4        426x240    DASH video  242k , avc1.4d400c, 30fps, video only
134          mp4        640x360    DASH video  647k , avc1.4d401e, 30fps, video only
135          mp4        854x480    DASH video 1155k , avc1.4d4014, 30fps, video only
298          mp4        1280x720   DASH video 3568k , avc1.4d4020, 60fps, video only
299          mp4        1920x1080  DASH video 7867k , avc1.64002a, 60fps, video only
17           3gp        176x144    small , mp4v.20.3,  mp4a.40.2@ 24k
36           3gp        320x180    small , mp4v.20.3,  mp4a.40.2
43           webm       640x360    medium , vp8.0,  vorbis@128k
18           mp4        640x360    medium , avc1.42001E,  mp4a.40.2@ 96k
22           mp4        1280x720   hd720 , avc1.64001F,  mp4a.40.2@192k (best)
```

I expected to get video 135 and audio 140.

**Comment by keybounce** [comment]
Turns out this is happening to a lot of videos (I am trying to download my youtube channel).

Some are downloading just fine (audio and video). Many are only getting video.

Here's another sample.

```
keybounceMBP:Keybounce michael$ youtube-dl -v AjWZe7h7Clg
[debug] System config: []
[debug] User config: [u'-o', u'%(title)s.%(ext)s', u'-f', u'\nbest[ext=mp4][height>431][height<=719]/\nbestvideo[ext=mp4][height=480]+bestaudio[ext=m4a]/\nbest[ext=mp4][height>340][height<=431]/\nbestvideo[ext=mp4][height>360][height<=576]+bestaudio/\nbest[height>340][height<=576]/\nbestvideo[height>360][height<=576]+bestaudio/\nbestvideo[height=360]+bestaudio/\nbest[ext=mp4][height>=280][height<=360]/\nbest[height<=576]/\nworst', u'--write-sub', u'--embed-subs', u'--recode-video', u'mp4', u'--mark-watched']
[debug] Command-line args: [u'-v', u'AjWZe7h7Clg']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.07.13
[debug] Python version 2.7.5 - Darwin-13.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.1.1, ffprobe 3.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] AjWZe7h7Clg: Downloading webpage
[youtube] AjWZe7h7Clg: Downloading video info webpage
[youtube] AjWZe7h7Clg: Extracting video information
[youtube] AjWZe7h7Clg: Downloading MPD manifest
[info] Writing video subtitles to: KmOcd Magic Farm Performance Tuning 001 - What's behind me (Keybounce's Minecraft Overkill).en.vtt
[debug] Invoking downloader on u'https://r11---sn-a5m7lnez.googlevideo.com/videoplayback?id=0235997bb87b0a58&itag=135&source=youtube&requiressl=yes&pl=21&nh=IgpwcjAyLmxheDE2KgkxMjcuMC4wLjE&mn=sn-a5m7lnez&mv=m&initcwndbps=420000&ms=au&mm=31&ratebypass=yes&mime=video/mp4&gir=yes&clen=263559223&lmt=1387343721799493&dur=2327.467&sver=3&fexp=9405978,9416126,9416891,9422596,9428398,9431012,9433096,9433223,9433651,9433851,9433946,9435058,9435526,9435876,9436051,9437066,9437553,9437663,9437742,9438663,9438900,9439013,9439186,9439652,9439889,9439979,9440333,9440374,9440550,9440642,9440839&signature=837E13E488801D6A2A40C4C012D0801B22F97BA0.6A08DCAB200D7DC42CC64B2DB5F91BF52B6FB545&upn=31_lOXuTCj4&key=dg_yt0&mt=1468476936&ip=108.192.89.65&ipbits=0&expire=1468498790&sparams=ip,ipbits,expire,id,itag,source,requiressl,pl,nh,mn,mv,initcwndbps,ms,mm,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: KmOcd Magic Farm Performance Tuning 001 - What's behind me (Keybounce's Minecraft Overkill).mp4
[download] 100% of 251.35MiB in 10:49
[ffmpeg] Not converting video file KmOcd Magic Farm Performance Tuning 001 - What's behind me (Keybounce's Minecraft Overkill).mp4 - already is in target format mp4
[ffmpeg] Embedding subtitles in 'KmOcd Magic Farm Performance Tuning 001 - What's behind me (Keybounce's Minecraft Overkill).mp4'
[debug] ffmpeg command line: ffmpeg -y -i 'file:KmOcd Magic Farm Performance Tuning 001 - What'"'"'s behind me (Keybounce'"'"'s Minecraft Overkill).mp4' -i 'file:KmOcd Magic Farm Performance Tuning 001 - What'"'"'s behind me (Keybounce'"'"'s Minecraft Overkill).en.vtt' -map 0:v -c:v copy -map 0:a -c:a copy -map -0:s -c:s mov_text -map 1:0 -metadata:s:s:0 language=eng 'file:KmOcd Magic Farm Performance Tuning 001 - What'"'"'s behind me (Keybounce'"'"'s Minecraft Overkill).temp.mp4'
ERROR: To ignore this, add a trailing '?' to the map.
Traceback (most recent call last):
  File "/Users/michael/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1791, in post_process
    files_to_delete, info = pp.run(info)
  File "/Users/michael/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 384, in run
    self.run_ffmpeg_multiple_files(input_files, temp_filename, opts)
  File "/Users/michael/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 168, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
FFmpegPostProcessorError

keybounceMBP:Keybounce michael$
```

NB: Even though I specified best video + best audio (the all-in-one for that video is a 360p, so it gets skipped), it downloaded as video only (silent).

**Comment by dstftw** [comment]
Caused by https://github.com/rg3/youtube-dl/blob/master/youtube_dl/YoutubeDL.py#L1088-L1090. `formats` at that time is already filtered out so this does not really check whether extractor has only video-only or audio-only formats.

**Comment by keybounce** [comment]
Thank you ... but in fairness, looking at that comment and the lines around it, I really don't understand what the code is doing.

(Might help if I knew the language. I am guessing at what the flow structure is doing. The data structures, however ...

Also, what language says "THEN statement IF condition ELSE statement"?)
