### ISSUE TITLE
ffmpeg is failing on a caption file.

### ISSUE THREAD

**Issue by keybounce** [rg3/youtube-dl#10081]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.07.13*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2016.07.13**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
[debug] System config: []
[debug] User config: [u'-o', u'%(title)s.%(ext)s', u'-f', u'\nbest[ext=mp4][height>431][height<=1576]/\nbestvideo[ext=mp4][height=480]+bestaudio[ext=m4a]/\nbest[ext=mp4][height>340][height<=431]/\nbestvideo[ext=mp4][height>360][height<=576]+bestaudio/\nbest[height>340][height<=576]/\nbestvideo[height>360][height<=576]+bestaudio/\nbestvideo[height=360]+bestaudio/\nbest[ext=mp4][height>=280][height<=360]/\nbest[height<=576]/\nworst', u'--write-sub', u'--embed-subs', u'--recode-video', u'mp4', u'--mark-watched']
[debug] Command-line args: [u'-v', u'AjWZe7h7Clg']
[debug] Encodings: locale UTF-8, fs utf-8, out None, pref UTF-8
[debug] youtube-dl version 2016.07.13
[debug] Python version 2.7.5 - Darwin-13.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.0.2, ffprobe 3.0.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] AjWZe7h7Clg: Downloading webpage
[youtube] AjWZe7h7Clg: Downloading video info webpage
[youtube] AjWZe7h7Clg: Extracting video information
[youtube] AjWZe7h7Clg: Downloading MPD manifest
[info] Writing video subtitles to: KmOcd Magic Farm Performance Tuning 001 - What's behind me (Keybounce's Minecraft Overkill).en.vtt
[debug] Invoking downloader on u'https://r11---sn-a5m7lnez.googlevideo.com/videoplayback?id=0235997bb87b0a58&itag=135&source=youtube&requiressl=yes&initcwndbps=455000&mn=sn-a5m7lnez&mm=31&nh=IgpwcjA0LmxheDE2KgkxMjcuMC4wLjE&pl=21&ms=au&mv=m&ratebypass=yes&mime=video/mp4&gir=yes&clen=263559223&lmt=1387343721799493&dur=2327.467&key=dg_yt0&upn=AL7Qf1JcF3w&signature=1AB2CE46D29D8E89FCF1C0BDECDE436190B8BF29.0C97E8582379D4D4CAD1969827E03661D0D5201D&fexp=9405976,9410705,9416126,9416891,9419451,9422596,9428398,9429932,9431012,9433096,9433223,9433946,9434904,9434904,9435241,9435526,9435876,9436027,9437066,9437552,9437742,9438392,9438663,9438870,9439363,9439652,9439684,9440162,9440184,9440376,9441087&sver=3&mt=1468448993&ip=108.192.89.65&ipbits=0&expire=1468470968&sparams=ip,ipbits,expire,id,itag,source,requiressl,initcwndbps,mn,mm,nh,pl,ms,mv,ratebypass,mime,gir,clen,lmt,dur'
[download] KmOcd Magic Farm Performance Tuning 001 - What's behind me (Keybounce's Minecraft Overkill).mp4 has already been downloaded

[download] 100% of 251.09MiB
[ffmpeg] Not converting video file KmOcd Magic Farm Performance Tuning 001 - What's behind me (Keybounce's Minecraft Overkill).mp4 - already is in target format mp4
[ffmpeg] Embedding subtitles in 'KmOcd Magic Farm Performance Tuning 001 - What's behind me (Keybounce's Minecraft Overkill).mp4'
[debug] ffmpeg command line: ffmpeg -y -i 'file:KmOcd Magic Farm Performance Tuning 001 - What'"'"'s behind me (Keybounce'"'"'s Minecraft Overkill).mp4' -i 'file:KmOcd Magic Farm Performance Tuning 001 - What'"'"'s behind me (Keybounce'"'"'s Minecraft Overkill).en.vtt' -map 0:v -c:v copy -map 0:a -c:a copy -map -0:s -c:s mov_text -map 1:0 -metadata:s:s:0 language=eng 'file:KmOcd Magic Farm Performance Tuning 001 - What'"'"'s behind me (Keybounce'"'"'s Minecraft Overkill).temp.mp4'
ERROR: To ignore this, add a trailing '?' to the map.
Traceback (most recent call last):
  File "/Users/michael/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1791, in post_process
    files_to_delete, info = pp.run(info)
  File "/Users/michael/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 384, in run
    self.run_ffmpeg_multiple_files(input_files, temp_filename, opts)
  File "/Users/michael/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 168, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
FFmpegPostProcessorError


```

I have no idea why ffmpeg does not like this.

**Comment by keybounce** [comment]
Odd.

I just updated ffmpeg, in case that was the problem. Same thing.

```
keybounceMBP:Keybounce michael$ youtube-dl -v AjWZe7h7Clg
[debug] System config: []
[debug] User config: [u'-o', u'%(title)s.%(ext)s', u'-f', u'\nbest[ext=mp4][height>431][height<=719]/\nbestvideo[ext=mp4][height=480]+bestaudio[ext=m4a]/\nbest[ext=mp4][height>340][height<=431]/\nbestvideo[ext=mp4][height>360][height<=576]+bestaudio/\nbest[height>340][height<=576]/\nbestvideo[height>360][height<=576]+bestaudio/\nbestvideo[height=360]+bestaudio/\nbest[ext=mp4][height>=280][height<=360]/\nbest[height<=576]/\nworst', u'--write-sub', u'--embed-subs', u'--recode-video', u'mp4', u'--mark-watched']
[debug] Command-line args: [u'-v', u'AjWZe7h7Clg']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.07.13
[debug] Python version 2.7.5 - Darwin-13.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.1.1, ffprobe 3.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] AjWZe7h7Clg: Downloading webpage
[youtube] AjWZe7h7Clg: Downloading video info webpage
[youtube] AjWZe7h7Clg: Extracting video information
[youtube] AjWZe7h7Clg: Downloading MPD manifest
[info] Writing video subtitles to: KmOcd Magic Farm Performance Tuning 001 - What's behind me (Keybounce's Minecraft Overkill).en.vtt
[debug] Invoking downloader on u'https://r11---sn-a5m7lnez.googlevideo.com/videoplayback?id=0235997bb87b0a58&itag=135&source=youtube&requiressl=yes&pl=21&nh=IgpwcjAyLmxheDE2KgkxMjcuMC4wLjE&mn=sn-a5m7lnez&mv=m&initcwndbps=420000&ms=au&mm=31&ratebypass=yes&mime=video/mp4&gir=yes&clen=263559223&lmt=1387343721799493&dur=2327.467&sver=3&fexp=9405978,9416126,9416891,9422596,9428398,9431012,9433096,9433223,9433651,9433851,9433946,9435058,9435526,9435876,9436051,9437066,9437553,9437663,9437742,9438663,9438900,9439013,9439186,9439652,9439889,9439979,9440333,9440374,9440550,9440642,9440839&signature=837E13E488801D6A2A40C4C012D0801B22F97BA0.6A08DCAB200D7DC42CC64B2DB5F91BF52B6FB545&upn=31_lOXuTCj4&key=dg_yt0&mt=1468476936&ip=108.192.89.65&ipbits=0&expire=1468498790&sparams=ip,ipbits,expire,id,itag,source,requiressl,pl,nh,mn,mv,initcwndbps,ms,mm,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: KmOcd Magic Farm Performance Tuning 001 - What's behind me (Keybounce's Minecraft Overkill).mp4
[download] 100% of 251.35MiB in 10:49
[ffmpeg] Not converting video file KmOcd Magic Farm Performance Tuning 001 - What's behind me (Keybounce's Minecraft Overkill).mp4 - already is in target format mp4
[ffmpeg] Embedding subtitles in 'KmOcd Magic Farm Performance Tuning 001 - What's behind me (Keybounce's Minecraft Overkill).mp4'
[debug] ffmpeg command line: ffmpeg -y -i 'file:KmOcd Magic Farm Performance Tuning 001 - What'"'"'s behind me (Keybounce'"'"'s Minecraft Overkill).mp4' -i 'file:KmOcd Magic Farm Performance Tuning 001 - What'"'"'s behind me (Keybounce'"'"'s Minecraft Overkill).en.vtt' -map 0:v -c:v copy -map 0:a -c:a copy -map -0:s -c:s mov_text -map 1:0 -metadata:s:s:0 language=eng 'file:KmOcd Magic Farm Performance Tuning 001 - What'"'"'s behind me (Keybounce'"'"'s Minecraft Overkill).temp.mp4'
ERROR: To ignore this, add a trailing '?' to the map.
Traceback (most recent call last):
  File "/Users/michael/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1791, in post_process
    files_to_delete, info = pp.run(info)
  File "/Users/michael/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 384, in run
    self.run_ffmpeg_multiple_files(input_files, temp_filename, opts)
  File "/Users/michael/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 168, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
FFmpegPostProcessorError

keybounceMBP:Keybounce michael$
```

**Comment by dstftw** [comment]
Caused by #9288.

**Comment by dstftw** [comment]
```
PS C:\dev\youtube-dl\master> ffmpeg -y -i "file:KmOcd Magic Farm Performance Tuning 001 - What's behind me (Keybounce's Minecraft Overkill)-AjWZe7h7Clg-135.mp4" -i "file:KmOcd Magic Farm Performance Tuning 001 - Wh
at's behind me (Keybounce's Minecraft Overkill)-AjWZe7h7Clg-135.en.vtt" -map 0:v -c:v copy -map 0:a -c:a copy -map -0:s -c:s mov_text -map 1:0 -metadata:s:s:0 language=eng "file:KmOcd Magic Farm Performance Tuning
001 - What's behind me (Keybounce's Minecraft Overkill)-AjWZe7h7Clg-135.temp.mp4"
ffmpeg version 3.0 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 5.3.0 (GCC)
  configuration: --enable-gpl --enable-version3 --disable-w32threads --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libdcadec --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-decklink --enable-zlib
  libavutil      55. 17.103 / 55. 17.103
  libavcodec     57. 24.102 / 57. 24.102
  libavformat    57. 25.100 / 57. 25.100
  libavdevice    57.  0.101 / 57.  0.101
  libavfilter     6. 31.100 /  6. 31.100
  libswscale      4.  0.100 /  4.  0.100
  libswresample   2.  0.101 /  2.  0.101
  libpostproc    54.  0.100 / 54.  0.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'file:KmOcd Magic Farm Performance Tuning 001 - What's behind me (Keybounce's Minecraft Overkill)-AjWZe7h7Clg-135.mp4':
  Metadata:
    major_brand     : dash
    minor_version   : 0
    compatible_brands: iso6avc1mp41
    creation_time   : 2013-12-17 05:15:20
  Duration: 00:38:47.47, start: 0.033333, bitrate: 905 kb/s
    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 854x480, 1 kb/s, 30 fps, 30 tbr, 90k tbn, 60 tbc (default)
    Metadata:
      creation_time   : 2013-12-17 05:15:20
      handler_name    : VideoHandler
Input #1, webvtt, from 'file:KmOcd Magic Farm Performance Tuning 001 - What's behind me (Keybounce's Minecraft Overkill)-AjWZe7h7Clg-135.en.vtt':
  Duration: N/A, bitrate: N/A
    Stream #1:0: Subtitle: webvtt
Stream map '0:a' matches no streams.
To ignore this, add a trailing '?' to the map.
```

**Comment by yan12125** [comment]
Sorry it's my fault. I didn't check video-only or audio-only files before making changes. I've reverted the change and embedding should work as usual in most cases in the next version.
