### ISSUE TITLE
[Facebook] Not downloading ended live videos (public)

### ISSUE THREAD

**Issue by vxbinaca** [rg3/youtube-dl#10104]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.07.16**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)

```youtube-dl -v https://www.facebook.com/groups/leanposting/permalink/524549411085736/```

```
[debug] System config: []
[debug] User config: ['--download-archive', '~/.ytdlarchive', '--retries', '100', '--no-overwrites', '--call-home', '--continue', '--write-info-json', '--write-description', '--write-thumbnail', '--write-annotations', '--all-subs', '--write-sub', '--add-metadata', '-f', 'bestvideo+bestaudio/best', '--merge-output-format', 'mkv', '--prefer-ffmpeg', '--embed-thumbnail']
[debug] Command-line args: ['-v', 'https://www.facebook.com/groups/leanposting/permalink/524549411085736/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.07.16
[debug] Python version 3.5.1+ - Linux-4.4.0-31-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 2.8.6-1ubuntu2, avprobe 2.8.6-1ubuntu2, ffmpeg 2.8.6-1ubuntu2, ffprobe 2.8.6-1ubuntu2, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Public IP address: 173.14.86.178
[facebook] 524549411085736: Downloading webpage
[facebook] 524549411085736: Downloading webpage
ERROR: The video is not available, Facebook said: "The link you followed may have expired, or the page may only be visible to an audience you&#039;re not in."
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/YoutubeDL.py", line 682, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/common.py", line 347, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/facebook.py", line 338, in _real_extract
    video_id, fatal_if_no_video=True)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/facebook.py", line 264, in _extract_from_url
    expected=True)
youtube_dl.utils.ExtractorError: The video is not available, Facebook said: "The link you followed may have expired, or the page may only be visible to an audience you&#039;re not in."
```

**Comment by vxbinaca** [comment]
Nevermind.
