### ISSUE TITLE
[VideoMega.TV] Download link 403 Forbidden.

### ISSUE THREAD

**Issue by MaeJhem** [rg3/youtube-dl#10107]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.07.16**

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

The problem that, when you run this command.
`youtube-dl -g http://videomega.tv/?ref=G64G3RFB0000BFR3G46G`
You'll be able to get the direct link of the file/video. but the problem that when you open the link to your browser/HTML5 video player. You'll get the message 403 Forbidden.

**Comment by dstftw** [comment]
**Post the full output of youtube-dl when run with `-v`**, i.e. **add** `-v` flag to **your command line**, copy the **whole** output and post it in the issue body wrapped in \`\`\` for better formatting. It should look similar to this:
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2015.12.06
[debug] Git HEAD: 135392e
[debug] Python version 2.6.6 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
```
**Do not post screenshots of verbose log only plain text is acceptable.**

The output (including the first lines) contains important debugging information. Issues without the full output are often not reproducible and therefore do not get solved in short order, if ever.

**Comment by MaeJhem** [comment]
Here's the ourput.
```
youtube-dl -v http://videomega.tv/?ref=G64G3RFB0000BFR3G46G
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://videomega.tv/?ref=G64G3RFB0000BFR3G46G']
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
[debug] youtube-dl version 2016.07.16
[debug] Python version 2.6.6 - Linux-2.6.32-042stab113.21-x86_64-with-centos-6.8-Final
[debug] exe versions: none
[debug] Proxy map: {}
[VideoMega] G64G3RFB0000BFR3G46G: Downloading webpage
[debug] Invoking downloader on u'http://ack.cdn.vizplay.org/v/b5ef57919b73200c744121a8e358b69f.mp4?st=GeVLfNsXHwTO_VE0Mk95PA&hash=lP_d2XbYtNaUKmNjiMl3Mg'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1683, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1625, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 350, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 58, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1985, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib64/python2.6/urllib2.py", line 397, in open
    response = meth(req, response)
  File "/usr/lib64/python2.6/urllib2.py", line 510, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.6/urllib2.py", line 435, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.6/urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.6/urllib2.py", line 518, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden
```
