### ISSUE TITLE
Unable to download with a Dish provider, cookie file, and a supported site.

### ISSUE THREAD

**Issue by keybounce** [rg3/youtube-dl#10111]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.07.17*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2016.07.17**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ x] Bug report (encountered problems with youtube-dl)
- [x ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

I am having trouble watching TV shows that need logging in with Dish. A search showed a similar issue at https://github.com/rg3/youtube-dl/issues/9786

Basically: Attempting to isolate the needed cookies by making a new firefox profile, and going to my sites found that I was already logged in through Dish, without having to enter account name/password; this implies that abobe flash is handling the login.

```
keybounceMBP:TV michael$ youtube-dl -v -F --cookies ~/Dish-cookies.txt http://www.adultswim.com/videos/naruto-
shippuden/guardian-of-the-iron-wall/
[debug] System config: []
[debug] User config: [u'-o', u'%(title)s.%(ext)s', u'-f', u'\nbest[ext=mp4][height>431][height<=576]/\nbestvideo[ext=mp4][height=480]+bestaudio[ext=m4a]/\nbest[ext=mp4][height>340][height<=431]/\nbestvideo[ext=mp4][height>360][height<=576]+bestaudio/\nbest[height>340][height<=576]/\nbestvideo[height>360][height<=576]+bestaudio/\nbestvideo[height=360]+bestaudio/\nbest[ext=mp4][height>=280][height<=360]/\nbest[height<=576]/\nworst', u'--write-sub', u'--embed-subs', u'--recode-video', u'mp4', u'--mark-watched']
[debug] Command-line args: [u'-v', u'-F', u'--cookies', u'/Users/michael/Dish-cookies.txt', u'http://www.adultswim.com/videos/naruto-shippuden/guardian-of-the-iron-wall/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.07.17
[debug] Python version 2.7.5 - Darwin-13.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.1.1, ffprobe 3.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[AdultSwim] guardian-of-the-iron-wall: Downloading webpage
ERROR: This video is only available via cable service provider subscription that is not currently supported. You may want to use --cookies.
Traceback (most recent call last):
  File "/Users/michael/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 682, in extract_info
    ie_result = ie.extract(url)
  File "/Users/michael/bin/youtube-dl/youtube_dl/extractor/common.py", line 347, in extract
    return self._real_extract(url)
  File "/Users/michael/bin/youtube-dl/youtube_dl/extractor/adultswim.py", line 148, in _real_extract
    expected=True)
ExtractorError: This video is only available via cable service provider subscription that is not currently supported. You may want to use --cookies.
```

Note that I have a cookie file specified. I can visit adult swim or disney XD, and watch shows, without having to provider any more details. Yet it's not working here.

My question: Is this because I have Dish as my provider, or is it because something is not being exported in my cookies? NB: I have self-destructing cookies installed, just to keep from accumulating tons of advertising cookies (each visit serves a new ad).

Cookies kept: adobe.com, adultswim.com, cartoonnetwork.com, fwmrm.com, go.com, turner.com.

**Comment by keybounce** [comment]
How can I provide you with an account/password?

**Comment by gkoelln** [comment]
I've tried to add the Dish MSO in the adobepass.py file and I get the following:
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--ap-mso', 'Dish', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', 'http://www.fox.com/watch/770377795715/7833489408', '--write-sub', '--convert-subs', 'srt', '-f', 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]', '-o', 'C:\\Users\\Greg\\Videos\\%(series)s\\%(season_number)sx%(episode_number)s %(title)s.%(ext)s', '-v', '--get-filename']
[debug] Encodings: locale cp1252, fs utf-8, out cp1252, pref cp1252
[debug] youtube-dl version 2017.01.10
[debug] Python version 3.6.0 - Windows-10-10.0.14393-SP0
[debug] exe versions: ffmpeg 3.2.2, ffprobe 3.2.2, rtmpdump 2.3
[debug] Proxy map: {}
ERROR: Unable to extract post url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Python36\lib\youtube-dl\youtube_dl\YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "C:\Python36\lib\youtube-dl\youtube_dl\extractor\common.py", line 359, in extract
    return self._real_extract(url)
  File "C:\Python36\lib\youtube-dl\youtube_dl\extractor\fox.py", line 48, in _real_extract
    query['auth'] = self._extract_mvpd_auth(url, video_id, 'fbc-fox', resource)
  File "C:\Python36\lib\youtube-dl\youtube_dl\extractor\adobepass.py", line 1441, in _extract_mvpd_auth
    mso_info.get('password_field', 'password'): password,
  File "C:\Python36\lib\youtube-dl\youtube_dl\extractor\adobepass.py", line 1347, in post_form
    post_url = self._html_search_regex(r'<form[^>]+action=(["\'])(?P<url>.+?)\1', form_page, 'post url', group='url')
  File "C:\Python36\lib\youtube-dl\youtube_dl\extractor\common.py", line 671, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "C:\Python36\lib\youtube-dl\youtube_dl\extractor\common.py", line 662, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract post url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
