### ISSUE TITLE
Error text when cancelled CTRL+C in initialization moment

### ISSUE THREAD

**Issue by iDolmatov** [rg3/youtube-dl#10135]
Windows 10.0.10586 + Youtube-dl 2016.07.17
By keywords and such did not find instructions.
Bug report

Start command:
"C:\Program Files (x86)\youtube-dl\youtube-dl.exe"  --user-agent "Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36" --external-downloader "C:\Program Files (x86)\youtube-dl\aria2c.exe"  --external-downloader-args -c  --embed-subs --add-metadata --write-sub  --xattrs   --console-title  --youtube-skip-dash-manifest --no-check-certificate   -c --ignore-config -i   -o "D:\music\Новые 2\%(resolution)s\%(uploader_id)s\%(title)s.%(ext)s" --referer https://www.youtube.com/feed/subscriptions --merge-output-format MKV

Press CTRL+C few seconds later

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpd3npnjq3\build\youtube_dl\extractor\__init__.py", line 4, in <module>
ImportError: No module named 'youtube_dl.extractor.lazy_extractors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "__main__.py", line 16, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python\Python34\lib\site-packages\zipextimporter.py", line 86, in load_module
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpd3npnjq3\build\youtube_dl\__init__.py", line 42, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python\Python34\lib\site-packages\zipextimporter.py", line 86, in load_module
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpd3npnjq3\build\youtube_dl\extractor\__init__.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python\Python34\lib\site-packages\zipextimporter.py", line 86, in load_module
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpd3npnjq3\build\youtube_dl\extractor\extractors.py", line 192, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python\Python34\lib\site-packages\zipextimporter.py", line 86, in load_module
  File "<frozen importlib._bootstrap>", line 1223, in _fix_up_module
KeyboardInterrupt

C:\Users\Администратор>"C:\Program Files (x86)\youtube-dl\youtube-dl.exe"  --user-agent "Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36" --external-downloader "C:\Program Files (x86)\youtube-dl\aria2c.exe"  --external-downloader-args -c  --embed-subs --add-metadata --write-sub  --xattrs   --console-title  --youtube-skip-dash-manifest --no-check-certificate   -c --ignore-config -i   -o "D:\music\Новые 2\%(resolution)s\%(uploader_id)s\%(title)s.%(ext)s" --referer https://www.youtube.com/feed/subscriptions --merge-output-format MKV
WARNING: Long argument string detected. Use -- to separate parameters and URLs, like this:
youtube-dl --user-agent 'Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36' --external-downloader 'C:\Program Files (x86)\youtube-dl\aria2c.exe' --external-downloader-args -c --embed-subs --add-metadata --xattrs --console-title --youtube-skip-dash-manifest --no-check-certificate -c --ignore-config -i -o 'D:\music\Новые 2\%(resolution)s\%(uploader_id)s\%(title)s.%(ext)s' --referer https://www.youtube.com/feed/subscriptions --merge-output-format MKV -- --write-sub

Usage: youtube-dl.exe [OPTIONS] URL [URL...]

youtube-dl.exe: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options.

C:\Users\Администратор>"C:\Program Files (x86)\youtube-dl\youtube-dl.exe"  --user-agent "Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36" --external-downloader "C:\Program Files (x86)\youtube-dl\aria2c.exe"  --external-downloader-args -c  --embed-subs --add-metadata --write-sub  --xattrs   --console-title  --youtube-skip-dash-manifest --no-check-certificate   -c --ignore-config -i   -o "D:\music\Новые 2\%(resolution)s\%(uploader_id)s\%(title)s.%(ext)s" --referer https://www.youtube.com/feed/subscriptions --merge-output-format MKV
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpd3npnjq3\build\youtube_dl\extractor\__init__.py", line 4, in <module>
ImportError: No module named 'youtube_dl.extractor.lazy_extractors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "__main__.py", line 16, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python\Python34\lib\site-packages\zipextimporter.py", line 86, in load_module
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpd3npnjq3\build\youtube_dl\__init__.py", line 42, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python\Python34\lib\site-packages\zipextimporter.py", line 86, in load_module
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpd3npnjq3\build\youtube_dl\extractor\__init__.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python\Python34\lib\site-packages\zipextimporter.py", line 86, in load_module
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpd3npnjq3\build\youtube_dl\extractor\extractors.py", line 47, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python\Python34\lib\site-packages\zipextimporter.py", line 86, in load_module
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpd3npnjq3\build\youtube_dl\extractor\ard.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python\Python34\lib\site-packages\zipextimporter.py", line 86, in load_module
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpd3npnjq3\build\youtube_dl\extractor\generic.py", line 33, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2222, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 2164, in _find_spec
  File "<frozen importlib._bootstrap>", line 1940, in find_spec
  File "<frozen importlib._bootstrap>", line 1916, in _get_spec
  File "<frozen importlib._bootstrap>", line 1897, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 863, in spec_from_loader
  File "<frozen importlib._bootstrap>", line 915, in spec_from_file_location
KeyboardInterrupt

C:\Users\Администратор>"C:\Program Files (x86)\youtube-dl\youtube-dl.exe"  --user-agent "Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36" --external-downloader "C:\Program Files (x86)\youtube-dl\aria2c.exe"  --external-downloader-args -c  --embed-subs --add-metadata --write-sub  --xattrs   --console-title  --youtube-skip-dash-manifest --no-check-certificate   -c --ignore-config -i   -o "D:\music\Новые 2\%(resolution)s\%(uploader_id)s\%(title)s.%(ext)s" --referer https://www.youtube.com/feed/subscriptions --merge-output-format MKV
WARNING: Long argument string detected. Use -- to separate parameters and URLs, like this:
youtube-dl --user-agent 'Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36' --external-downloader 'C:\Program Files (x86)\youtube-dl\aria2c.exe' --external-downloader-args -c --embed-subs --add-metadata --xattrs --console-title --youtube-skip-dash-manifest --no-check-certificate -c --ignore-config -i -o 'D:\music\Новые 2\%(resolution)s\%(uploader_id)s\%(title)s.%(ext)s' --referer https://www.youtube.com/feed/subscriptions --merge-output-format MKV -- --write-sub

Usage: youtube-dl.exe [OPTIONS] URL [URL...]

youtube-dl.exe: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options.

C:\Users\Администратор>"C:\Program Files (x86)\youtube-dl\youtube-dl.exe"  --user-agent "Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36" --external-downloader "C:\Program Files (x86)\youtube-dl\aria2c.exe"  --external-downloader-args -c  --embed-subs --add-metadata --write-sub  --xattrs   --console-title  --youtube-skip-dash-manifest --no-check-certificate   -c --ignore-config -i   -o "D:\music\Новые 2\%(resolution)s\%(uploader_id)s\%(title)s.%(ext)s" --referer https://www.youtube.com/feed/subscriptions --merge-output-format MKV

C:\Users\Администратор>"C:\Program Files (x86)\youtube-dl\youtube-dl.exe"  --user-agent "Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36" --external-downloader "C:\Program Files (x86)\youtube-dl\aria2c.exe"  --external-downloader-args -c  --embed-subs --add-metadata --write-sub  --xattrs   --console-title  --youtube-skip-dash-manifest --no-check-certificate   -c --ignore-config -i   -o "D:\music\Новые 2\%(resolution)s\%(uploader_id)s\%(title)s.%(ext)s" --referer https://www.youtube.com/feed/subscriptions --merge-output-format MKV
Traceback (most recent call last):
  File "__main__.py", line 16, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python\Python34\lib\site-packages\zipextimporter.py", line 86, in load_module
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpd3npnjq3\build\youtube_dl\__init__.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python\Python34\lib\site-packages\zipextimporter.py", line 86, in load_module
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpd3npnjq3\build\youtube_dl\options.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python\Python34\lib\site-packages\zipextimporter.py", line 86, in load_module
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpd3npnjq3\build\youtube_dl\downloader\__init__.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python\Python34\lib\site-packages\zipextimporter.py", line 86, in load_module
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpd3npnjq3\build\youtube_dl\downloader\common.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python\Python34\lib\site-packages\zipextimporter.py", line 86, in load_module
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpd3npnjq3\build\youtube_dl\compat.py", line 2332, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python\Python34\lib\site-packages\zipextimporter.py", line 86, in load_module
  File "C:\Python\Python34\lib\http\server.py", line 663, in <module>
  File "C:\Python\Python34\lib\http\server.py", line 869, in SimpleHTTPRequestHandler
  File "C:\Python\Python34\lib\mimetypes.py", line 349, in init
  File "C:\Python\Python34\lib\mimetypes.py", line 256, in read_windows_registry
KeyboardInterrupt

If run and wait text normal

Usage: youtube-dl.exe [OPTIONS] URL [URL...]

youtube-dl.exe: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options.

Perhaps it is not even a bug. But it would be desirable without displaying the text. Or get an explanation of the situation.

**Comment by dstftw** [comment]
That is expected behavior. You'll always get a stack trace with `KeyboardInterrupt` if interrupted before flow reaches `main`.
