### ISSUE TITLE
Bad username or password...

### ISSUE THREAD

**Issue by MatrixView** [rg3/youtube-dl#10140]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.07.17**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Bug report (encountered problems with youtube-dl)
---
```
d:\>youtube-dl -u username@pages.plusgoogle.com -p password :ytsubs -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-u', 'PRIVATE', '-p', 'PRIVATE', ':ytsubs', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.07.17
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-67388-g37425fc, ffprobe N-67388-g37425fc, rtmpdump 2.4-47-gc26c541
[debug] Proxy map: {}
[youtube:subscriptions] Downloading login page
[youtube:subscriptions] Logging in
WARNING: unable to log in: bad username or password
[youtube:subscriptions] Youtube Subscriptions: Downloading webpage
[download] Downloading playlist: Youtube Subscriptions
[youtube:subscriptions] playlist Youtube Subscriptions: Collected 0 video ids (downloading 0 of them)
[download] Finished downloading playlist: Youtube Subscriptions```

---

Unfortunately I'm unable to use youtube-dl with my credentials since late last night (GMT).
I can login on youtube.com on different browsers just fine with the same credentials.
My credentials have NOT changed recently. I do NOT have 2-factor authentication on.

I don't know if others can still login with youtube-dl. What could be the problem?

**Comment by radoslawg** [comment]
+1 - same issue since today. 24 hours ago it worked alright.

**Comment by nazar2sfive** [comment]
same issue here... multiple times since yesterday.

```
android@android:~$ youtube-dl -f 43 -u nazar2sfive@gmail.com -p ********** https://www.youtube.com/watch?v=c6oWQ8p0FuI -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-f', u'43', u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'https://www.youtube.com/watch?v=c6oWQ8p0FuI', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.08.17
[debug] Python version 2.7.12 - Linux-4.4.0-34-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.6-1ubuntu2, ffprobe 2.8.6-1ubuntu2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] Downloading login page
[youtube] Logging in
WARNING: unable to log in: bad username or password
[youtube] c6oWQ8p0FuI: Downloading webpage
[youtube] c6oWQ8p0FuI: Downloading embed webpage
[youtube] c6oWQ8p0FuI: Refetching age-gated info webpage
ERROR: c6oWQ8p0FuI: YouTube said: Please sign in to view this video.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 691, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 347, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 1321, in _real_extract
    expected=True, video_id=video_id)
ExtractorError: c6oWQ8p0FuI: YouTube said: Please sign in to view this video.
```

**Comment by jleaders** [comment]
I also am seeing "Bad Username or Password" when, as far as I can tell from multiple attempts, it is the correct username/pass combo.

**Comment by PaulCyberEngel** [comment]
I'm having the same problem.  I have verified I can login with the username & password I put on the command line.

**Comment by sakanaproductions** [comment]
I'm also having the same issue

**Comment by AlexEdimensionz** [comment]
Still an issue. 

**$ youtube-dl -u "user@emaildomain.com" --format mp4 https://www.youtube.com/watch? v=VIDEOCODE**
> Type account password and press [Return]: 
> [youtube] Downloading login page
> [youtube] Logging in
> WARNING: unable to log in: bad username or password
> [youtube] xY9TWQrF8AQ: Downloading webpage
> [youtube] xY9TWQrF8AQ: Downloading embed webpage
> [youtube] xY9TWQrF8AQ: Refetching age-gated info webpage
> ERROR: xY9TWQrF8AQ: YouTube said: This video is private.

**Comment by yan12125** [comment]
@AlexEdimensionz Did you use 2FA or App passwords? If so see #5053

**Comment by AlexEdimensionz** [comment]
I don't have 2FA on my account. Just used gmail login/password

**Comment by yan12125** [comment]
As my account is working, I can only put random guesses. Do you have non-ASCII characters in your username or password? And please paste the output of
```
youtube-dl -v -u "user@emaildomain.com" --format mp4 https://www.youtube.com/watch?v=VIDEOCODE
```

**Comment by astaluego** [comment]
It's works only when I put double quotes : 
`youtube-dl -u "email@domain.com" https://youtube.com/watch?v=VIDEOCODE`

**Comment by vkchan** [comment]
I'm getting the same error when I try to download a private youtube video that I have subscribed to. I am certain that my username and password are correct. Here are my error messages. Any suggestion?

```
ubuntu:~$ youtube-dl -f bestvideo+bestaudio -ciw -o "/videos/%(title)s.%(ext)s" -u USERNAME@gmail.com" -p "PASSWORD" --ffmpeg-location /usr/bin https://www.youtube.com/watch?v=VIDEOCODE --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-f', u'bestvideo+bestaudio', u'-ciw', u'-o', u'/videos/%(title)s.%(ext)s', u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'--ffmpeg-location', u'/usr/bin', u'https://www.youtube.com/watch?v=VIDEOCODE', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.03.22
[debug] Python version 2.7.12 - Linux-4.4.0-66-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] Downloading login page
[youtube] Logging in
[youtube] lesiYZMTczk: Downloading webpage
[youtube] lesiYZMTczk: Downloading video info webpage
ERROR: lesiYZMTczk: YouTube said: This video is private.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 761, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 428, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 1392, in _real_extract
    expected=True, video_id=video_id)
ExtractorError: lesiYZMTczk: YouTube said: This video is private.

```

**Comment by vkchan** [comment]
I'm still getting this problem with the latest version (2017.03.22). see [#12520](https://github.com/rg3/youtube-dl/issues/12520)

**Comment by Shigeto1** [comment]
Any idea when or if this will be addressed? Using double quotes doesn't help.
