### ISSUE TITLE
ValueError: no closing quotation

### ISSUE THREAD

**Issue by Poilaucul** [rg3/youtube-dl#10145]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.07.22*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2016.07.22**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

```
C:\Program Files\MPV>youtube-dl.exe --version
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpra3yzk2s\build\youtube_dl\__init__.py", line 422, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpra3yzk2s\build\youtube_dl\__init__.py", line 56, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpra3yzk2s\build\youtube_dl\options.py", line 823, in parseOpts
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpra3yzk2s\build\youtube_dl\options.py", line 59, in _readUserConf
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpra3yzk2s\build\youtube_dl\options.py", line 33, in _readOptions
  File "C:\Python\Python34\lib\shlex.py", line 276, in split
  File "C:\Python\Python34\lib\shlex.py", line 266, in __next__
  File "C:\Python\Python34\lib\shlex.py", line 93, in get_token
  File "C:\Python\Python34\lib\shlex.py", line 169, in read_token
ValueError: No closing quotation



C:\Program Files\MPV>youtube-dl.exe -v "https://www.youtube.com/watch?v=2vDEyKa4Zeo"
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpra3yzk2s\build\youtube_dl\__init__.py", line 422, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpra3yzk2s\build\youtube_dl\__init__.py", line 56, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpra3yzk2s\build\youtube_dl\options.py", line 823, in parseOpts
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpra3yzk2s\build\youtube_dl\options.py", line 59, in _readUserConf
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpra3yzk2s\build\youtube_dl\options.py", line 33, in _readOptions
  File "C:\Python\Python34\lib\shlex.py", line 276, in split
  File "C:\Python\Python34\lib\shlex.py", line 266, in __next__
  File "C:\Python\Python34\lib\shlex.py", line 93, in get_token
  File "C:\Python\Python34\lib\shlex.py", line 169, in read_token
ValueError: No closing quotation

C:\Program Files\MPV>
```

**Comment by dstftw** [comment]
Post the output of your config file.

**Comment by Poilaucul** [comment]
```
-u xxxxxxxxxx@xxxx -p xxxxxxxxxxx
--cache-dir "F://Temporaire//YouTube"
--format "bestvideo+bestaudio"
--ffmpeg-location "C://Program Files//FFmpeg//bin//ffmpeg.exe"
--mark-watched

## En cas de téléchargement d'une playlist

-o '"F://Temporaire//MPV//%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s"

#-o "F://Temporaire//MPV//%(title)s.%(ext)s"
```

**Comment by dstftw** [comment]
>-o '"F://Temporaire//MPV//%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s"
>No closing quotation

`'` quote is not closed.
