### ISSUE TITLE
Support SeeSo Downloads

### ISSUE THREAD

**Issue by OverlordQ** [rg3/youtube-dl#10163]
### Make sure you are using the _latest_ version: run `youtube-dl --version` and ensure your version is _2016.07.24_. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ X] I've **verified** and **I assure** that I'm running youtube-dl **2016.07.24**
### Before submitting an _issue_ make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
### What is the purpose of your _issue_?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your _issue_

---
### If the purpose of this _issue_ is a _bug report_, _site support request_ or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
$ youtube-dl -v https://www.seeso.com/home\?vid\=720439363694
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://www.seeso.com/home?vid=720439363694']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.07.24
[debug] Python version 2.7.12 - Linux-4.5.0-2-amd64-x86_64-with-debian-stretch-sid
[debug] exe versions: ffmpeg 3.1.1-2, ffprobe 3.1.1-2
[debug] Proxy map: {}
[generic] home?vid=720439363694: Requesting header
WARNING: Falling back on generic information extractor.
[generic] home?vid=720439363694: Downloading webpage
[generic] home?vid=720439363694: Extracting information
ERROR: Unsupported URL: https://www.seeso.com/home?vid=720439363694
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl-2016.7.24-py2.7.egg/youtube_dl/extractor/generic.py", line 1597, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl-2016.7.24-py2.7.egg/youtube_dl/compat.py", line 2525, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl-2016.7.24-py2.7.egg/youtube_dl/compat.py", line 2514, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: syntax error: line 1, column 0
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl-2016.7.24-py2.7.egg/youtube_dl/YoutubeDL.py", line 682, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl-2016.7.24-py2.7.egg/youtube_dl/extractor/common.py", line 347, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl-2016.7.24-py2.7.egg/youtube_dl/extractor/generic.py", line 2326, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.seeso.com/home?vid=720439363694
```

---
### If the purpose of this _issue_ is a _site support request_ please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.seeso.com/home?vid=720439363694

---
### Description of your _issue_, suggested solution and other information

Support SeeSo downloads. Uses Akamai/ThePlatform backend, but generic extractor doesn't work.

**Comment by OverlordQ** [comment]
Seems like putting the VID parameter into:
``https://feed.theplatform.com/f/NZILfC/nbcott-prod-all-media?byAvailabilityState=available&byId=<vid>&form=cjson``

Spits back some JSON info:

```

{"$xmlns":{"nbc-chaos":"http://xml.theplatform.com/media/data/nbcu-chaos"},"startIndex":1,"itemsPerPage":100,"entryCount":1,"title":"All Media Feed","entries":[{"id":"http://data.media.theplatform.com/media/data/Media/639351875955","guid":"2998316","title":"Inside Joke","author":"","description":"Former foes Victoria and Baxter bond over an inside joke at Chelsea's expense. Their sudden friendship drives Andrew crazy with jealousy. Meanwhile Amir's mysterious new client shows up guns blazing... literally, and Chelsea has to sell a house to a heartbroken man.","added":1457440364000,"availableDate":1457413200000,"expirationDate":1546318800000,"categories":[{"name":"Series","scheme":"","label":""},{"name":"Series/Original","scheme":"","label":""},{"name":"Series/Original/US","scheme":"","label":""},{"name":"Series/Original/US/Sitcom","scheme":"","label":""},{"name":"Series/Original/US/Sitcom/Bajillion Dollar Propertie$","scheme":"","label":""}],"copyright":"","copyrightUrl":"","credits":[{"role":"director","scheme":"","value":"Alex FernieAlex Fernie"},{"role":"producer","scheme":"","value":"Scott Aukerman"},{"role":"producer","scheme":"","value":"Thomas Lennon"},{"role":"producer","scheme":"","value":"R. Ben Garant"},{"role":"producer","scheme":"","value":"David Jargowsky"},{"role":"producer","scheme":"","value":"Kulap Vilaysack"},{"role":"producer","scheme":"","value":"Jason Korstad"},{"role":"producer","scheme":"","value":"Brad Morris"},{"role":"actor","scheme":"","value":"Paul F Tompkins"},{"role":"actor","scheme":"","value":"Dan Ahdoot"},{"role":"actor","scheme":"","value":"Mandell Maughan"},{"role":"actor","scheme":"","value":"Ryan Gaul"},{"role":"actor","scheme":"","value":"Drew Tarver"},{"role":"actor","scheme":"","value":"Tim Baltz"},{"role":"actor","scheme":"","value":"Tawny Newsome"}],"keywords":"Bajillion Dollar Propertie$","ratings":[{"scheme":"urn:v-chip","rating":"tv-ma","subRatings":["d","l"]}],"countries":[],"excludeCountries":true,"text":"","content":[{"audioChannels":2,"audioSampleRate":0,"bitrate":204800,"checksums":{},"contentType":"video","duration":1409.000,"expression":"full","fileSize":55272125,"frameRate":0.0,"format":"MPEG4","height":234,"isDefault":false,"language":"en","sourceTime":0.000,"url":"https://link.theplatform.com/s/NZILfC/media/ANDDDYtIr4T6?feed=All%20Media%20Feed","width":416},{"audioChannels":2,"audioSampleRate":0,"bitrate":1887232,"checksums":{},"contentType":"video","duration":1409.000,"expression":"full","fileSize":342468586,"frameRate":0.0,"format":"MPEG4","height":540,"isDefault":false,"language":"en","sourceTime":0.000,"url":"https://link.theplatform.com/s/NZILfC/media/ANDDDYtIr4T6?feed=All%20Media%20Feed","width":960},{"audioChannels":2,"audioSampleRate":0,"bitrate":409600,"checksums":{},"contentType":"video","duration":1409.000,"expression":"full","fileSize":90062675,"frameRate":0.0,"format":"MPEG4","height":234,"isDefault":false,"language":"en","sourceTime":0.000,"url":"https://link.theplatform.com/s/NZILfC/media/ANDDDYtIr4T6?feed=All%20Media%20Feed","width":416},{"audioChannels":2,"audioSampleRate":0,"bitrate":1228800,"checksums":{},"contentType":"video","duration":1409.000,"expression":"full","fileSize":230024172,"frameRate":0.0,"format":"MPEG4","height":540,"isDefault":false,"language":"en","sourceTime":0.000,"url":"https://link.theplatform.com/s/NZILfC/media/ANDDDYtIr4T6?feed=All%20Media%20Feed","width":960},{"audioChannels":2,"audioSampleRate":0,"bitrate":4194304,"checksums":{},"contentType":"video","duration":1409.000,"expression":"full","fileSize":736589731,"frameRate":0.0,"format":"MPEG4","height":1080,"isDefault":true,"language":"en","sourceTime":0.000,"url":"https://link.theplatform.com/s/NZILfC/media/ANDDDYtIr4T6?feed=All%20Media%20Feed","width":1920},{"audioChannels":2,"audioSampleRate":0,"bitrate":2621440,"checksums":{},"contentType":"video","duration":1409.000,"expression":"full","fileSize":467982786,"frameRate":0.0,"format":"MPEG4","height":720,"isDefault":false,"language":"en","sourceTime":0.000,"url":"https://link.theplatform.com/s/NZILfC/media/ANDDDYtIr4T6?feed=All%20Media%20Feed","width":1280},{"audioChannels":2,"audioSampleRate":0,"bitrate":716800,"checksums":{},"contentType":"video","duration":1409.000,"expression":"full","fileSize":142516103,"frameRate":0.0,"format":"MPEG4","height":360,"isDefault":false,"language":"en","sourceTime":0.000,"url":"https://link.theplatform.com/s/NZILfC/media/ANDDDYtIr4T6?feed=All%20Media%20Feed","width":640}],"thumbnails":[{"audioChannels":0,"audioSampleRate":0,"bitrate":0,"checksums":{},"contentType":"image","duration":0.000,"expression":"full","fileSize":204257,"frameRate":0.0,"format":"JPEG","height":1080,"isDefault":true,"language":"","sourceTime":0.000,"url":"https://chaosic.akamaized.net/NBCOTT_-_Production/454/475/160308_2998316_Inside_Joke.jpg","width":1920}],"adminTags":[],"categoryIds":["http://data.media.theplatform.com/media/data/Category/536592451699","http://data.media.theplatform.com/media/data/Category/538917955567","http://data.media.theplatform.com/media/data/Category/543920195982","http://data.media.theplatform.com/media/data/Category/546602051612","http://data.media.theplatform.com/media/data/Category/639697987556"],"pubDate":1458792000000,"defaultThumbnailUrl":"https://chaosic.akamaized.net/NBCOTT_-_Production/454/475/160308_2998316_Inside_Joke.jpg","provider":"Chaos","programId":"http://data.entertainment.tv.theplatform.com/entertainment/data/Program/guid/2670495309/bajillion-dollar-propertie_1_3_inside-joke","seriesId":"http://data.entertainment.tv.theplatform.com/entertainment/data/Program/guid/2670495309/bajillion-dollar-propertie","publicUrl":"https://link.theplatform.com/s/NZILfC/media/ANDDDYtIr4T6","nbc-chaos$advertisingGenre":"Comedy","nbc-chaos$director":"Alex FernieAlex Fernie","nbc-chaos$episodeNumber":3,"nbc-chaos$freeContent":false,"nbc-chaos$fullEpisode":true,"nbc-chaos$originalAirdate":1458792000000,"nbc-chaos$programmingType":"Full Episode","nbc-chaos$seasonNumber":1,"nbc-chaos$shortDescription":"Victoria and Baxter bond over an inside joke and a jealous Andrew has no idea how to handle it, Amir's new client has a dangerous secret, and Chelsea deals with a sad divorcee.","nbc-chaos$shortTitle":"Inside Joke","nbc-chaos$show":"Bajillion Dollar Propertie$","nbc-chaos$subscriptionPackage":["comedy.basic"]}]}
```

**Comment by sa7mon** [comment]
Anything we can do to help get this feature? I'd love to have it.

**Comment by sa7mon** [comment]
If a dev needs an account, I can provide one to test with.

**Here's what I've found so far that may be able to help:**

On the episode page _i.e.: https://www.seeso.com/view/episode/757391939917_, if you open Chrome Dev Tools and watch the Network tab, you can filter ".m3u" files. 
Once you see "index_0_av.m3u8", right-click and hit "Open link in new tab". This will download the .m3u8 file. Once you have this, you can use VLC ( or ffmpeg, I'm assuming) to "convert" the playlist to a raw file. This will give you an MPEG-TS file with audio, video, and subtitles.

@yan12125 Is there any sort of similar functionality already built into youtube-dl?

**Comment by yan12125** [comment]
> Is there any sort of similar functionality already built into youtube-dl?

Yeah, there's a function:
```
self._extract_m3u8_formats
```
