### ISSUE TITLE
BUG: Download from 'vivo.sx' no longer works (since a couple of weeks)

### ISSUE THREAD

**Issue by runkharr** [rg3/youtube-dl#10170]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.07.26.2*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2016.07.26.2**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### This is a BUG-report.

Downloads from the site 'vivo.sx' no longer work (for me?). The protocol output follows:

```
$ ./youtube-dl --verbose http://vivo.sx/bfb7f37eff
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://vivo.sx/bfb7f37eff']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.07.26.2
[debug] Python version 2.7.12 - Linux-4.6.0-1-amd64-x86_64-with-debian-stretch-sid
[debug] exe versions: avconv 11.3-6, avprobe 3.1.1-2, ffmpeg 3.1.1-2, ffprobe 3.1.1-2, rtmpdump 2.4
[debug] Proxy map: {}
[Shared] bfb7f37eff: Downloading webpage
[Shared] bfb7f37eff: Downloading video page
ERROR: Unable to extract video URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 682, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 347, in extract
    return self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/shared.py", line 55, in _real_extract
    r'data-url="([^"]+)"', video_page, 'video URL')
  File "./youtube-dl/youtube_dl/extractor/common.py", line 659, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 650, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
<end of log>
```

When i perform each step manually (using 'wget'), the "download" still works, meaning: When issuing a POST-request with the form-data from the just downloaded web-page, i get the "downlad" page, which no longer contains the hidden form, but the URL of the video.

The problem is independent of the video-id, that is regardless of which video i'm trying to download from 'vivo.sx', 'youtube-dl' fails with the same error message as displayed in the protocol.

I have no solution for this problem. All what i can see is that the POST-request obviously fails, because 'youtube-dl' downloads the same webpage (with the same hidden form). I tried different methods - from "waiting" like in the 'streamcloud' extractor module to "removing" the stored cookie to multiple reloads (with and without delays), but nothing works ...

---

**Comment by runkharr** [comment]
OK, thanks!
