### ISSUE TITLE
Unable to download abc7chicago.com's videos.

### ISSUE THREAD

**Issue by antdude** [rg3/youtube-dl#10176]
For an example:
$ youtube-dl -v http://abc7chicago.com/video/embed/?pid=1436951
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://abc7chicago.com/video/embed/?pid=1436951']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.07.26.2
[debug] Python version 3.4.2 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.5
[debug] exe versions: ffmpeg 3.0.2-4, ffprobe 3.0.2-4, rtmpdump 2.4
[debug] Proxy map: {}
[generic] ?pid=1436951: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ?pid=1436951: Downloading webpage
[generic] ?pid=1436951: Extracting information
ERROR: Unsupported URL: http://abc7chicago.com/video/embed/?pid=1436951
Traceback (most recent call last):
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 682, in extract_info
    ie_result = ie.extract(url)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/common.py", line 347, in extract
    return self._real_extract(url)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2329, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: http://abc7chicago.com/video/embed/?pid=1436951

Thank you in advance. :)

**Comment by SeanPM5** [comment]
Although I am not a developer and can't fix, I have a workaround for this site that might help for the time being.

View page source and look for upylnk.com URL ending in .m3u8, for example:
`			<meta itemprop="contentURL" content="http://content.uplynk.com/ext/aac37e2c66614e699fb189ab391084ff/072116-wcl-blue-man-group-vdi_web.m3u8?ad._v=2&ad=wls_video&ad.preroll=&ad.fill_slate=1&ad.ametr=1">`

Then run command like this to download:
`youtube-dl http://content.uplynk.com/ext/aac37e2c66614e699fb189ab391084ff/072116-wcl-blue-man-group-vdi_web.m3u8 --hls-prefer-native`
