### ISSUE TITLE
Unknown cause of bug...?

### ISSUE THREAD

**Issue by babadoctor** [rg3/youtube-dl#10197]
A:\>youtube-dl https://www.youtube.com/watch?v=AGZiLMGdCE0 -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=AGZiLMGdCE0', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.06.12
[debug] Python version 3.4.4 - Windows-10-10.0.10586
[debug] exe versions: ffmpeg N-77953-gcc83177, ffprobe N-77953-gcc83177
[debug] Proxy map: {}
[youtube] AGZiLMGdCE0: Downloading webpage
[youtube] AGZiLMGdCE0: Downloading video info webpage
[youtube] AGZiLMGdCE0: Extracting video information
[youtube] {43} signature length 42.43, html5 player en_US-vfld7sVQ3
[youtube] AGZiLMGdCE0: Downloading player https://s.ytimg.com/yts/jsbin/player-en_US-vfld7sVQ3/base.js
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpg7f6m7dy\build\youtube_dl\extractor\youtube.py", line 997, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpg7f6m7dy\build\youtube_dl\extractor\youtube.py", line 912, in _extract_signature_function
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpg7f6m7dy\build\youtube_dl\extractor\youtube.py", line 975, in _parse_sig_js
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpg7f6m7dy\build\youtube_dl\jsinterp.py", line 241, in extract_function
youtube_dl.utils.ExtractorError: Could not find JS function 'Qy'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Could not find JS function 'Qy'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpg7f6m7dy\build\youtube_dl\extractor\youtube.py", line 997, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpg7f6m7dy\build\youtube_dl\extractor\youtube.py", line 912, in _extract_signature_function
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpg7f6m7dy\build\youtube_dl\extractor\youtube.py", line 975, in _parse_sig_js
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpg7f6m7dy\build\youtube_dl\jsinterp.py", line 241, in extract_function
youtube_dl.utils.ExtractorError: Could not find JS function 'Qy'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpg7f6m7dy\build\youtube_dl\extractor\youtube.py", line 997, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpg7f6m7dy\build\youtube_dl\extractor\youtube.py", line 912, in _extract_signature_function
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpg7f6m7dy\build\youtube_dl\extractor\youtube.py", line 975, in _parse_sig_js
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpg7f6m7dy\build\youtube_dl\jsinterp.py", line 241, in extract_function
youtube_dl.utils.ExtractorError: Could not find JS function 'Qy'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpg7f6m7dy\build\youtube_dl\YoutubeDL.py", line 676, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpg7f6m7dy\build\youtube_dl\extractor\common.py", line 342, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpg7f6m7dy\build\youtube_dl\extractor\youtube.py", line 1570, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpg7f6m7dy\build\youtube_dl\extractor\youtube.py", line 1007, in _decrypt_signature
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpg7f6m7dy\build\youtube_dl\extractor\youtube.py", line 997, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpg7f6m7dy\build\youtube_dl\extractor\youtube.py", line 912, in _extract_signature_function
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpg7f6m7dy\build\youtube_dl\extractor\youtube.py", line 975, in _parse_sig_js
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpg7f6m7dy\build\youtube_dl\jsinterp.py", line 241, in extract_function
youtube_dl.utils.ExtractorError: Could not find JS function 'Qy'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Could not find JS function 'Qy'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

I ran youtube-dl -U before trying this.
Ran cmd in administrator and without administrator. same problem.
OS: Windows 10

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.
