### ISSUE TITLE
Handle multiple node objects in JSON-LD (was: Generic Extractor: AttributeError: 'list' object has no attribute 'get')

### ISSUE THREAD

**Issue by canavan** [rg3/youtube-dl#10203]
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2016.07.30**
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
---

youtube-dl --verbose https://rumble.com/v31a0x-19-people-who-should-stay-away-from-power-tools.html                   
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://rumble.com/v31a0x-19-people-who-should-stay-away-from-power-tools.html']
[debug] Encodings: locale ISO8859-1, fs ISO8859-1, out ISO8859-1, pref ISO8859-1
[debug] youtube-dl version 2016.07.30
[debug] Python version 2.7.12 - IRIX64-6.5-IP35-mips-n32bit-ELF
[debug] exe versions: ffmpeg UNKNOWN, ffprobe UNKNOWN, rtmpdump 2.2b
[debug] Proxy map: {}
[generic] v31a0x-19-people-who-should-stay-away-from-power-tools: Requesting header
WARNING: Falling back on generic information extractor.
[generic] v31a0x-19-people-who-should-stay-away-from-power-tools: Downloading webpage
[generic] v31a0x-19-people-who-should-stay-away-from-power-tools: Extracting information
Traceback (most recent call last):
  File "/usr/nekoware/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/nekoware/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/nekoware/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/nekoware/bin/youtube-dl/youtube_dl/__init__.py", line 422, in main
  File "/usr/nekoware/bin/youtube-dl/youtube_dl/__init__.py", line 412, in _real_main
  File "/usr/nekoware/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1775, in download
  File "/usr/nekoware/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 682, in extract_info
  File "/usr/nekoware/bin/youtube-dl/youtube_dl/extractor/common.py", line 347, in extract
  File "/usr/nekoware/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2236, in _real_extract
  File "/usr/nekoware/bin/youtube-dl/youtube_dl/extractor/common.py", line 818, in _search_json_ld
  File "/usr/nekoware/bin/youtube-dl/youtube_dl/extractor/common.py", line 826, in _json_ld
AttributeError: 'list' object has no attribute 'get'

**Comment by yan12125** [comment]
An example of multiple node objects in JSON-LD: https://www.w3.org/TR/json-ld/#named-graphs Such objects should be handled.
