### ISSUE TITLE
*.cbslocal.com "time data does not match format"

### ISSUE THREAD

**Issue by incorpusyehtee** [rg3/youtube-dl#10213]
- [x] Bug report (encountered problems with youtube-dl)

Windows:
```
$ youtube-dl -v --ignore-config http://pittsburgh.cbslocal.com/2016/08/01/new-state-tax-has-some-smokers-considering-quitting/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', '--ignore-config', 'http://pittsburgh.cbslocal.com/2016/08/01/new-state-tax-has-some-smokers-cons
idering-quitting/']
[debug] Encodings: locale cp1252, fs mbcs, out cp65001, pref cp1252
[debug] youtube-dl version 2016.08.01
[debug] Python version 3.4.4 - Windows-8.1-6.3.9600
[debug] exe versions: ffmpeg N-62824-g5b39376, ffprobe N-62824-g5b39376, rtmpdump 2.4
[debug] Proxy map: {}
[CBSLocal] new-state-tax-has-some-smokers-considering-quitting: Downloading webpage
[CBSLocal] 3440613: Fetching server time
[CBSLocal] 3440613: Downloading JSON metadata
[CBSLocal] 3440613: Downloading SMIL file
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpnq4x675r\build\youtube_dl\__init__.py", line 422, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpnq4x675r\build\youtube_dl\__init__.py", line 412, in _real_mai
n
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpnq4x675r\build\youtube_dl\YoutubeDL.py", line 1775, in downloa
d
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpnq4x675r\build\youtube_dl\YoutubeDL.py", line 682, in extract_
info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpnq4x675r\build\youtube_dl\extractor\common.py", line 347, in e
xtract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpnq4x675r\build\youtube_dl\extractor\cbslocal.py", line 77, in
_real_extract
  File "C:\Python\Python34\lib\_strptime.py", line 507, in _strptime_datetime
  File "C:\Python\Python34\lib\_strptime.py", line 344, in _strptime
ValueError: time data 'August 1, 2016 9:47 PM' does not match format '%b %d, %Y %I:%M %p'
```

Ubuntu
```
$ youtube-dl -v --ignore-config http://pittsburgh.cbslocal.com/2016/08/01/new-state-tax-has-some-smokers-considering-quitting/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'--ignore-config', u'http://pittsburgh.cbslocal.com/2016/08/01/new-state-tax-has-some-smokers-considering-quitting/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.08.01
[debug] Python version 2.7.6 - Linux-3.19.0-33-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: ffmpeg N-75470-g4ed5a73, ffprobe N-75470-g4ed5a73
[debug] Proxy map: {}
[CBSLocal] new-state-tax-has-some-smokers-considering-quitting: Downloading webpage
[CBSLocal] 3440613: Fetching server time
[CBSLocal] 3440613: Downloading JSON metadata
[CBSLocal] 3440613: Downloading SMIL file
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 422, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 412, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1775, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 682, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 347, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/cbslocal.py", line 77, in _real_extract
  File "/usr/lib/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data 'August 1, 2016 9:47 PM' does not match format '%b %d, %Y %I:%M %p'
```

**Comment by incorpusyehtee** [comment]
For anyone who needs *.CBSlocal.com rips in the mean time: 

You can find the m3u file the player uses. It isn't encrypted or anything. It contains m3u's pointing to all the various quality levels of the video.

**Comment by yan12125** [comment]
Thanks for the report, most CBSLocal Los Angeles should work again in the next version.
