### ISSUE TITLE
*Disregard* Youtube 403 Forbidden error

### ISSUE THREAD

**Issue by jesuspi6127** [rg3/youtube-dl#10212]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.08.01*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2016.08.01**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
youtube-dl -v -f 18 https://www.youtube.com/watch?v=UwCsJvmwAGw
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-c', u'-o', u'%(title)s - %(uploader)s.%(ext)s', u'-v', u'-f', u'18', u'https://www.youtube.com/watch?v=UwCsJvmwAGw']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.08.01
[debug] Python version 2.7.12 - Linux-3.16.7-35-desktop-x86_64-with-SuSE-13.2-x86_64
[debug] exe versions: ffmpeg 3.0.2, ffprobe 3.0.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] UwCsJvmwAGw: Downloading webpage
[youtube] UwCsJvmwAGw: Downloading video info webpage
[youtube] UwCsJvmwAGw: Extracting video information
[youtube] UwCsJvmwAGw: Downloading MPD manifest
[debug] Invoking downloader on u'https://r1---sn-ja5gvjv-cvbs.googlevideo.com/videoplayback?mn=sn-ja5gvjv-cvbs&mm=31&ipbits=0&requiressl=yes&signature=D4FBFFC5F6805C44CC29FFD53F6C5BFC60438939.1E5D52025C25BEC8AA4675B8BBF684E1B2D33C8F&expire=1470175245&sver=3&mv=m&mt=1470152945&ms=au&ei=rcOgV4D2Js7a-gW8sYrIDg&lmt=1470090121899914&dur=796.142&ip=200.118.99.17&key=yt6&itag=18&id=o-AOuiT2mM1yP54FQEjMvY0ELPV1UCam4RotDgEemWecaX&sparams=dur%2Cei%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&mime=video%2Fmp4&upn=U2V14nJNGek&fexp=9406000%2C9410705%2C9416891%2C9419451%2C9422555%2C9422596%2C9427833%2C9428398%2C9431012%2C9433092%2C9433096%2C9433223%2C9433851%2C9433946%2C9435526%2C9435876%2C9437066%2C9437553%2C9438327%2C9438480%2C9438495%2C9438662%2C9438955%2C9439652%2C9440141%2C9440389%2C9440831%2C9440880%2C9441085%2C9441414%2C9441471%2C9441560%2C9441774%2C9442254%2C9442424%2C9443425&pl=22&source=youtube&ratebypass=yes&initcwndbps=626250'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1683, in process_info
    success = dl(filename, info_dict)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1625, in dl
    return fd.download(name, info)
  File "/usr/bin/youtube-dl/youtube_dl/downloader/common.py", line 350, in download
    return self.real_download(filename, info_dict)
  File "/usr/bin/youtube-dl/youtube_dl/downloader/http.py", line 58, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1985, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 467, in error
    result = self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 654, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden


...
<end of log>
```

---

### Description of your *issue*, suggested solution and other information

Youtube seems to have implemented some back end changes and now YTDL no longer works. It would seem not exclusive to YTDL as I have other programs that can download from youtube (gPodder, JDownloader 2 and the Chrome add-on Youtube Plus) and they are all broken at this point.

**Comment by jesuspi6127** [comment]
Youtube seems to have solved the problem, please disregard this report
