### ISSUE TITLE
[adultswim] Add support for trailers

### ISSUE THREAD

**Issue by mattl** [rg3/youtube-dl#10235]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.08.01*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.08.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
Seems like they've changed something again.

$ youtube-dl --verbose http://www.adultswim.com/videos/decker/inside-decker-a-new-hero/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.adultswim.com/videos/decker/inside-decker-a-new-hero/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.08.01
[debug] Python version 2.7.6 - Linux-3.16.0-57-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: ffmpeg N-77455-g4707497, ffprobe N-77455-g4707497, rtmpdump 2.4
[debug] Proxy map: {}
[AdultSwim] inside-decker-a-new-hero: Downloading webpage
ERROR: Unable to find video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 682, in extract_info
ie_result = ie.extract(url)
File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 347, in extract
return self._real_extract(url)
File "/usr/local/bin/youtube-dl/youtube_dl/extractor/adultswim.py", line 137, in _real_extract
raise ExtractorError('Unable to find video info')
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

---

### Description of your *issue*, suggested solution and other information

Can't download videos from adultswim.com -- I tried a couple different URLs, but http://www.adultswim.com/videos/decker/inside-decker-a-new-hero/ is the only I'm trying to archive.

**Comment by mattl** [comment]
@dstftw I don't believe it is a trailer, it should be a bonus show 10-15 minutes in length about the series, Decker.
