### ISSUE TITLE
Problem with TLC.com

### ISSUE THREAD

**Issue by theennev** [rg3/youtube-dl#10245]
I'm using the latest version (2016.08.06) and just got this in verbose mode : 
```
youtube-dl --verbose 'https://www.discoverygo.com/love-at-first-kiss/kiss-first-ask-questions-later/'    
[debug] System config: []                                                                                                        
[debug] User config: []                                                                                                          
[debug] Command-line args: [u'--verbose', u'https://www.discoverygo.com/love-at-first-kiss/kiss-first-ask-questions-later/']     
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8                                                                 
[debug] youtube-dl version 2016.08.06                                                                                            
[debug] Python version 2.7.10 - Darwin-15.6.0-x86_64-i386-64bit                                                                  
[debug] exe versions: ffmpeg 3.0.2-tessus                                                                                        
[debug] Proxy map: {}                                                                                                            
[generic] kiss-first-ask-questions-later: Requesting header                                                                      
WARNING: Falling back on generic information extractor.                                                                          
[generic] kiss-first-ask-questions-later: Downloading webpage                                                                    
[generic] kiss-first-ask-questions-later: Extracting information                                                                 
ERROR: kiss-first-ask-questions-later: Failed to parse JSON  (caused by ValueError('Extra data: line 32 column 5 - line 33 column
 5 (char 1379 - 1385)',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  
youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.                    
Traceback (most recent call last):                                                                                               
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 549, in _parse_json                                      
    return json.loads(json_string)                                                                                               
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads             
    return _default_decoder.decode(s)                                                                                            
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 369, in decode             
    raise ValueError(errmsg("Extra data", s, end, len(s)))                                                                       
ValueError: Extra data: line 32 column 5 - line 33 column 5 (char 1379 - 1385)                                                   
Traceback (most recent call last):                                                                                               
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 682, in extract_info                                            
    ie_result = ie.extract(url)                                                                                                  
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 347, in extract                                          
    return self._real_extract(url)                                                                                               
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2244, in _real_extract                                  
    webpage, video_id, default=None, expected_type='VideoObject')                                                                
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 823, in _search_json_ld                                  
    expected_type=expected_type)                                                                                                 
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 827, in _json_ld                                         
    json_ld = self._parse_json(json_ld, video_id, fatal=fatal)                                                                   
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 553, in _parse_json                                      
    raise ExtractorError(errmsg, cause=ve)                                                                                       
ExtractorError: kiss-first-ask-questions-later: Failed to parse JSON  (caused by ValueError('Extra data: line 32 column 5 - line 
33 column 5 (char 1379 - 1385)',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest versio
n; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. 
```

**Comment by theennev** [comment]
Awesome, tested it and it work .
