### ISSUE TITLE
[adultswim] ValueError: unknown url type

### ISSUE THREAD

**Issue by zoocey** [rg3/youtube-dl#10252]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.08.07*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.08.07**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS]() sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
youtube-dl.py -f best --write-sub --convert-subtitles srt -v http://www.adultswim.com/videos/million-dollar-extreme-presents-world-peace/your-vibe-attracts-your-tribe/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-f', u'best', u'--write-sub', u'--convert-subtitle
s', u'srt', u'-v', u'http://www.adultswim.com/videos/million-dollar-extreme-pres
ents-world-peace/your-vibe-attracts-your-tribe/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.08.07
[debug] Python version 2.7.11 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-80953-gd4c8e93, ffprobe N-80953-gd4c8e93
[debug] Proxy map: {}
[AdultSwim] your-vibe-attracts-your-tribe: Downloading webpage
[AdultSwim] Million Dollar Extreme Presents: World Peace - Your Vibe Attracts Yo
ur Tribe: Downloading segment information
[AdultSwim] Million Dollar Extreme Presents: World Peace - Your Vibe Attracts Yo
ur Tribe: Downloading m3u8 information
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\you\youtube-dl.py\__main__.py", line 19, in <module>
  File "C:\you\youtube-dl.py\youtube_dl\__init__.py", line 422, in main
  File "C:\you\youtube-dl.py\youtube_dl\__init__.py", line 412, in _real_main
  File "C:\you\youtube-dl.py\youtube_dl\YoutubeDL.py", line 1775, in download
  File "C:\you\youtube-dl.py\youtube_dl\YoutubeDL.py", line 682, in extract_info

  File "C:\you\youtube-dl.py\youtube_dl\extractor\common.py", line 347, in extra
ct
  File "C:\you\youtube-dl.py\youtube_dl\extractor\adultswim.py", line 211, in _r
eal_extract
  File "C:\you\youtube-dl.py\youtube_dl\extractor\common.py", line 1164, in _ext
ract_m3u8_formats
  File "C:\you\youtube-dl.py\youtube_dl\extractor\common.py", line 414, in _down
load_webpage_handle
  File "C:\you\youtube-dl.py\youtube_dl\extractor\common.py", line 394, in _requ
est_webpage
  File "C:\you\youtube-dl.py\youtube_dl\YoutubeDL.py", line 1985, in urlopen
  File "C:\Python27\lib\urllib2.py", line 423, in open
    protocol = req.get_type()
  File "C:\Python27\lib\urllib2.py", line 285, in get_type
    raise ValueError, "unknown url type: %s" % self.__original
ValueError: unknown url type: /secure/tve/2016-08/ASOE1008021600067583_HLS/ASOE1
008021600067583_iphone_vod.m3u8
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://www.adultswim.com/videos/million-dollar-extreme-presents-world-peace/your-vibe-attracts-your-tribe/

---

### Description of your *issue*, suggested solution and other information
As above, unable to even try to start the download. A simple -F causes the issue too. Also doesn't work with Python version 3.5.2.

**Comment by zoocey** [comment]
Working fine now. Unsure if due to a change by AS or due to updating to 2016.08.10, Closing issue.
