### ISSUE TITLE
Can't download from globoplay.globo.com

### ISSUE THREAD

**Issue by llagerlof** [rg3/youtube-dl#10262]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.08.07*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.08.07**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
C:\Apps\youtube-dl>youtube-dl.exe --version
2016.08.07

C:\Apps\youtube-dl>youtube-dl.exe -v https://globoplay.globo.com/v/5217401/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'https://globoplay.globo.com/v/5217401/']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.08.07
[debug] Python version 3.4.4 - Windows-8.1-6.3.9600
[debug] exe versions: ffmpeg N-34549-g13b7781, ffprobe N-79000-g66edd86
[debug] Proxy map: {}
[Globo] 5217401: Downloading JSON metadata
[Globo] 5217401: Downloading security hash for 5217401_90_720_wmsm
[Globo] 5217401_90_720_wmsm: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[Globo] 5217401: Downloading security hash for 5217401_360_720_wmsm
[Globo] 5217401_360_720_wmsm: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[Globo] 5217401: Downloading security hash for 5217401_360_360_wmsm
[Globo] 5217401_360_360_wmsm: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type
  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpj2cm3udp\build\youtube_dl\YoutubeDL.py", line 682, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpj2cm3udp\build\youtube_dl\extractor\common.py", line 347, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpj2cm3udp\build\youtube_dl\extractor\globo.py", line 382, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpj2cm3udp\build\youtube_dl\extractor\common.py", line 898, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

C:\Apps\youtube-dl>

<end of log>
```

### Description of your *issue*, suggested solution and other information

Can't download from globoplay.globo.com. I can see this video (https://globoplay.globo.com/v/5217401/) without problems in the browser.

**Comment by dstftw** [comment]
Works fine here:
```
PS C:\Dev\youtube-dl\master> py -2.7 .\youtube_dl\__main__.py https://globoplay.globo.com/v/5217401/  --proxy 'socks5://
201.71.166.241:29668' -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'https://globoplay.globo.com/v/5217401/', u'--proxy', u'socks5://201.71.166.241:29668', u'-v']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.08.07
[debug] Git HEAD: 082395d
[debug] Python version 2.7.12 - Windows-10-10.0.10240
[debug] exe versions: ffmpeg N-81192-g04da20e, ffprobe N-81192-g04da20e, rtmpdump 2.4
[debug] Proxy map: {u'http': u'socks5://201.71.166.241:29668', u'https': u'socks5://201.71.166.241:29668'}
[Globo] 5217401: Downloading JSON metadata
[Globo] 5217401: Downloading security hash for 5217401_90_720_wmsm
[Globo] 5217401_90_720_wmsm: Downloading m3u8 information
WARNING: Failed to download m3u8 information: <urlopen error [Errno 10054] An existing connection was forcibly closed by the remote host>
[Globo] 5217401: Downloading security hash for 5217401_360_720_wmsm
[Globo] 5217401_360_720_wmsm: Downloading m3u8 information
[Globo] 5217401: Downloading security hash for 5217401_360_360_wmsm
[Globo] 5217401_360_360_wmsm: Downloading m3u8 information
[debug] Invoking downloader on u'https://vodstreaming02.video.globo.com/r360_720/v2/f0/3b/0c/5217401_0c306aa799d7a796ecd337a117e7ed3bcc132625/5217401-manifest.wmsm/manifest/web720.mp4.m3u8'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 1550
[download] Destination: Cerimnia de abertura dos Jogos Olmpicos Rio 2016, na ntegra-5217401.mp4
[download]   0.0% of ~4.91GiB at 20.98KiB/s ETA 85:43:46
ERROR: Interrupted by user
```

**Comment by janemaydaily** [comment]
I use Allavsoft to download from Globo, YouTube, Vimeo, Linkedin etc
Here is the easy guide http://www.allavsoft.com/how-to/download-globo-videos.html
