### ISSUE TITLE
Site request: Anime Planet

### ISSUE THREAD

**Issue by keybounce** [rg3/youtube-dl#10305]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.08.12*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2016.08.12**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
keybounceMBP:Finite-Fluids michael$ youtube-dl -v http://www.anime-planet.com/anime/rosario-to-vampire
[debug] System config: []
[debug] User config: [u'-o', u'%(title)s.%(ext)s', u'-f', u'\nbest[ext=mp4][height>431][height<=480]/\nbestvideo[ext=mp4][height=480]+bestaudio[ext=m4a]/\nbest[ext=mp4][height>340][height<=431]/\nbestvideo[ext=mp4][height>360][height<=576]+bestaudio/\nbest[height>340][height<=576]/\nbestvideo[height>360][height<=576]+bestaudio/\nbestvideo[height=360]+bestaudio/\nbest[ext=mp4][height>=280][height<=360]/\nbest[height<=576]/\nworst', u'--write-sub', u'--write-auto-sub', u'--sub-lang', u'en,enUS', u'--sub-format', u'srt/ass/best', u'--embed-subs', u'--recode-video', u'mp4', u'--mark-watched']
[debug] Command-line args: [u'-v', u'http://www.anime-planet.com/anime/rosario-to-vampire']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.08.12
[debug] Python version 2.7.5 - Darwin-13.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.1.1, ffprobe 3.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] rosario-to-vampire: Requesting header
WARNING: Falling back on generic information extractor.
[generic] rosario-to-vampire: Downloading webpage
[generic] rosario-to-vampire: Extracting information
ERROR: Unsupported URL: http://www.anime-planet.com/anime/rosario-to-vampire
Traceback (most recent call last):
  File "/Users/michael/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1610, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/Users/michael/bin/youtube-dl/youtube_dl/compat.py", line 2525, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/Users/michael/bin/youtube-dl/youtube_dl/compat.py", line 2514, in _XML
    parser.feed(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: syntax error: line 1, column 1
Traceback (most recent call last):
  File "/Users/michael/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 691, in extract_info
    ie_result = ie.extract(url)
  File "/Users/michael/bin/youtube-dl/youtube_dl/extractor/common.py", line 347, in extract
    return self._real_extract(url)
  File "/Users/michael/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2344, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.anime-planet.com/anime/rosario-to-vampire

```

Typical playlist: http://www.anime-planet.com/anime/rosario-to-vampire

Typical episode: http://www.anime-planet.com/anime/rosario-to-vampire/videos/172162

NB: Site claims to be legal viewing with various partners.

**Comment by yan12125** [comment]
> Site claims to be legal viewing with various partners.

Could you give some claims?

**Comment by keybounce** [comment]
On the front page.

http://www.anime-planet.com/anime/watch-online/ says, "Watch thousands of dubbed and subbed anime episodes on Anime-Planet. Legal and industry-supported due to partnerships with Crunchyroll, Hulu, and more!"

Beyond that, I have no idea how to investigate legality.

However, just as a quickie: Going to Attack on Titan, http://www.anime-planet.com/anime/attack-on-titan/videos, it says,

" legal and free, due to our partnerships with the industry.
Provided by Hulu"

Hulu has switched from free streaming from itself, to paid subscription for direct viewing, with ad-supported partners that don't take subscriptions. Cite: https://tech.slashdot.org/story/16/08/08/1546245/hulu-ends-free-streaming-service-moves-free-stuff-to-yahoo-view -- it seems that yahoo is not the only hulu partner for free with ads.

**Comment by yan12125** [comment]
OK. Let's trust it!

**Comment by yan12125** [comment]
Seems it requires login? On my browser http://www.anime-planet.com/anime/rosario-to-vampire/videos/172162 always jumps to http://www.anime-planet.com/anime/rosario-to-vampire.

**Comment by keybounce** [comment]
That's unexpected.

Accounts are free over there, but I did not know that I had to be logged in to view videos. Ok, another cookie for the youtube-dl jar.

**Comment by keybounce** [comment]
Nope! I just went there without logging in, and was able to watch. Had to re-enter my birthdate because it's a mature audience video.

**Comment by yan12125** [comment]
Maybe it depends on geolocation? Where are you?

**Comment by keybounce** [comment]
Didn't think of that. United states (california).

On 2016-08-13, at 11:29 AM, Yen Chi Hsuan <notifications@github.com> wrote:

> Maybe it depends on geolocation? Where are you?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

---
Entertaining minecraft videos
http://YouTube.com/keybounce

**Comment by yan12125** [comment]
Thanks the video popups with a US proxy.

**Comment by keybounce** [comment]
Bump
Still not working :-).

Is someone willing to help a person with no prior python experience tackle this as their first python project, or is it too much to try as a first thing?

**Comment by orbea** [comment]
I would appreciate seeing this work too, but unfortunately have no python knowledge...
