### ISSUE TITLE
[24video] Unable to extract OpenGraph title

### ISSUE THREAD

**Issue by stepshal** [rg3/youtube-dl#10317]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.08.12**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

```
$ youtube-dl -v 'http://www.24video.net/video/view/1044982'
[debug] System config: []
[debug] User config: ['-4', '-f', 'best', '--prefer-free-formats', '--no-cache-dir', '--no-mtime', '--youtube-skip-dash-manifest']
[debug] Command-line args: ['-v', 'http://www.24video.net/video/view/1044982']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.08.12
[debug] Python version 3.6.0a3 - Linux-4.7.0-rc7-686-i686-with-debian-stretch-sid
[debug] exe versions: ffmpeg 3.1.2, ffprobe 3.1.2, rtmpdump 2.4
[debug] Proxy map: {}
[24video] 1044982: Downloading webpage
ERROR: Unable to extract OpenGraph title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/YoutubeDL.py", line 691, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/common.py", line 347, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/twentyfourvideo.py", line 48, in _real_extract
    title = self._og_search_title(webpage)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/common.py", line 749, in _og_search_title
    return self._og_search_property('title', html, **kargs)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/common.py", line 737, in _og_search_property
    escaped = self._search_regex(og_regexes, html, name, flags=re.DOTALL, **kargs)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/common.py", line 650, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract OpenGraph title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```
http://www.24video.net/video/view/1044982

**Comment by dstftw** [comment]
```
PS C:\Dev\youtube-dl\master> py -3.5 .\youtube_dl\__main__.py http://www.24video.net/video/view/1044982 -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://www.24video.net/video/view/1044982', '-v']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.08.12
[debug] Git HEAD: 990d533
[debug] Python version 3.5.2 - Windows-10-10.0.10240-SP0
[debug] exe versions: ffmpeg 3.0, ffprobe 3.0, rtmpdump 2.4
[debug] Proxy map: {}
[24video] 1044982: Downloading webpage
WARNING: unable to extract comment count; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[24video] 1044982: Downloading init XML
[24video] 1044982: Downloading video XML
[debug] Invoking downloader on 'http://dlp-2.24video.xxx:8080/2723265f1bab14f947eaf2dee5d8a204/1044/1044982/erotika_kamennogo_veka.mp4'
[download] Resuming download at byte 523264
[download] Destination: Эротика каменного века-1044982.mp4
[download]  22.1% of 2.82MiB at 329.95KiB/s ETA 00:06
ERROR: Interrupted by user
```

**Comment by stepshal** [comment]
@dstftw try with python 3.6.

**Comment by yan12125** [comment]
```
$ youtube-dl python3.6 -v "http://www.24video.net/video/view/1044982" 
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.24video.net/video/view/1044982']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.08.12
[debug] Git HEAD: f0d3669
[debug] Python version 3.6.0a3+ - Linux-4.6.5-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 3.1.2, ffprobe 3.1.2, rtmpdump 2.4
[debug] Proxy map: {}
[24video] 1044982: Downloading webpage
WARNING: unable to extract comment count; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[24video] 1044982: Downloading init XML
[24video] 1044982: Downloading video XML
[debug] Invoking downloader on 'http://dlp-2.24video.xxx:8080/dd154863e1483c776ed38a977a22a42d/1044/1044982/erotika_kamennogo_veka.mp4'
[download] Destination: Эротика каменного века-1044982.mp4
[download] 100% of 2.82MiB in 00:05
```

**Comment by dstftw** [comment]
Post the output of `youtube-dl --dump-pages 'http://www.24video.net/video/view/1044982'`.

**Comment by stepshal** [comment]
```py
$ youtube-dl --dump-pages 'http://www.24video.net/video/view/1044982'
[24video] 1044982: Downloading webpage
[24video] Dumping request to http://www.24video.net/video/view/1044982
PCFET0NUWVBFIGh0bWw+CjxodG1sIGxhbmc9ImVuIj4KPGhlYWQ+CiAgICA8IS0tIMKr0JTQvtGB0YLRg9C/INC30LDQv9GA0LXRidGR0L3CuyAtLT4KICAgIDxtZXRhIGNoYXJzZXQ9IlVURi04Ij4KICAgIDxtZXRhIG5hbWU9InZpZXdwb3J0IiBjb250ZW50PSJ3aWR0aD1kZXZpY2Utd2lkdGgsIGluaXRpYWwtc2NhbGU9MSI+CiAgICA8bGluayByZWw9InN0eWxlc2hlZXQiIGhyZWY9Ii4vc3RhdGljL3dhcm5pbmcvY3NzL2ZvbnRzLmNzcyI+CiAgICA8bGluayByZWw9InN0eWxlc2hlZXQiIGhyZWY9Ii4vc3RhdGljL3dhcm5pbmcvY3NzL21haW4uY3NzIj4KICAgIDxsaW5rIHJlbD0ic2hvcnRjdXQgaWNvbiIgaHJlZj0iLi9zdGF0aWMvd2FybmluZy9mYXZpY29uLmljbyI+CiAgICA8IS0tW2lmIGx0ZSBJRSA5XT4KICAgICAgICA8c2NyaXB0IHNyYz0iaHR0cDovL2h0bWw1c2hpdi1wcmludHNoaXYuZ29vZ2xlY29kZS5jb20vc3ZuL3RydW5rL2h0bWw1c2hpdi1wcmludHNoaXYuanMiPjwvc2NyaXB0PgogICAgPCFbZW5kaWZdLS0+CiAgICA8dGl0bGU+0JTQvtGB0YLRg9C/INC+0LPRgNCw0L3QuNGH0LXQvTwvdGl0bGU+CiAgICA8IS0tIFlhbmRleC5NZXRyaWthIGNvdW50ZXIgLS0+IDxzY3JpcHQgdHlwZT0idGV4dC9qYXZhc2NyaXB0Ij4gKGZ1bmN0aW9uIChkLCB3LCBjKSB7ICh3W2NdID0gd1tjXSB8fCBbXSkucHVzaChmdW5jdGlvbigpIHsgdHJ5IHsgdy55YUNvdW50ZXIzNjg1NzI3NSA9IG5ldyBZYS5NZXRyaWthKHsgaWQ6MzY4NTcyNzUsIGNsaWNrbWFwOnRydWUsIHRyYWNrTGlua3M6dHJ1ZSwgYWNjdXJhdGVUcmFja0JvdW5jZTp0cnVlLCB3ZWJ2aXNvcjp0cnVlLCB0cmFja0hhc2g6dHJ1ZSwgdXQ6Im5vaW5kZXgiIH0pOyB9IGNhdGNoKGUpIHsgfSB9KTsgdmFyIG4gPSBkLmdldEVsZW1lbnRzQnlUYWdOYW1lKCJzY3JpcHQiKVswXSwgcyA9IGQuY3JlYXRlRWxlbWVudCgic2NyaXB0IiksIGYgPSBmdW5jdGlvbiAoKSB7IG4ucGFyZW50Tm9kZS5pbnNlcnRCZWZvcmUocywgbik7IH07IHMudHlwZSA9ICJ0ZXh0L2phdmFzY3JpcHQiOyBzLmFzeW5jID0gdHJ1ZTsgcy5zcmMgPSAiaHR0cHM6Ly9tYy55YW5kZXgucnUvbWV0cmlrYS93YXRjaC5qcyI7IGlmICh3Lm9wZXJhID09ICJbb2JqZWN0IE9wZXJhXSIpIHsgZC5hZGRFdmVudExpc3RlbmVyKCJET01Db250ZW50TG9hZGVkIiwgZiwgZmFsc2UpOyB9IGVsc2UgeyBmKCk7IH0gfSkoZG9jdW1lbnQsIHdpbmRvdywgInlhbmRleF9tZXRyaWthX2NhbGxiYWNrcyIpOyA8L3NjcmlwdD4gPG5vc2NyaXB0PjxkaXY+PGltZyBzcmM9Imh0dHBzOi8vbWMueWFuZGV4LnJ1L3dhdGNoLzM2ODU3Mjc1P3V0PW5vaW5kZXgiIHN0eWxlPSJwb3NpdGlvbjphYnNvbHV0ZTsgbGVmdDotOTk5OXB4OyIgYWx0PSIiIC8+PC9kaXY+PC9ub3NjcmlwdD4gPCEtLSAvWWFuZGV4Lk1ldHJpa2EgY291bnRlciAtLT4KPC9oZWFkPgo8Ym9keT4KCiAgICA8ZGl2IGNsYXNzPSJoZWFkZXIiPgogICAgICAgIDxkaXYgY2xhc3M9ImNvbnRhaW5lciI+CiAgICAgICAgICAgIDxhIGhyZWY9Imh0dHBzOi8vd3d3LnJ0LnJ1IiB0YXJnZXQ9Il9ibGFuayI+CiAgICAgICAgICAgICAgICA8aW1nIHNyYz0iLi9zdGF0aWMvd2FybmluZy9pbWcvcnRsb2dvLnN2ZyIgYWx0PSIiPgogICAgICAgICAgICA8L2E+CiAgICAgICAgPC9kaXY+CiAgICA8L2Rpdj4KICAgIDxkaXYgY2xhc3M9ImRyb3Bkb3duIj4KICAgICAgICA8ZGl2IGNsYXNzPSJjb250YWluZXIiPgogICAgICAgICAgICA8ZGl2IGNsYXNzPSJ3cmFwcGVyIj4KICAgICAgICAgICAgICAgIDxoMT7QlNC+0YHRgtGD0L8g0L7Qs9GA0LDQvdC40YfQtdC9PC9oMT4KICAgICAgICAgICAgICAgIDxwPtCU0L7RgdGC0YPQvyDQuiDQt9Cw0L/RgNCw0YjQuNCy0LDQtdC80L7QvNGDINGA0LXRgdGD0YDRgdGDINC+0LPRgNCw0L3QuNGH0LXQvSDQv9C+INGA0LXRiNC10L3QuNGOINGB0YPQtNCwINC40LvQuCDQv9C+INC40L3Ri9C8INC+0YHQvdC+0LLQsNC90LjRj9C8LDxicj4D0YPRgdGC0LDQvdC+0LLQu9C10L3QvdGL0Lwg0LfQsNC60L7QvdC+0LTQsNGC0LXQu9GM0YHRgtCy0L7QvCDQoNC+0YHRgdC40LnRgdC60L7QuSDQpNC10LTQtdGA0LDRhtC40Lg8L3A+CiAgICAgICAgICAgICAgICA8YSBocmVmPSIjIiBjbGFzcz0iZHJvcGRvd24tdG9nZ2xlIj7QktC+0LfQvNC+0LbQvdGL0LUg0L/RgNC40YfQuNC90Ysg0L7Qs9GA0LDQvdC40YfQtdC90LjRjyDQtNC+0YHRgtGD0L/QsDwvYT4KICAgICAgICAgICAgICAgIDxvbCBjbGFzcz0iZHJvcGRvd24tbWVudSI+CiAgICAgICAgICAgICAgICAgICAgPGxpPtCU0L7RgdGC0YPQvyDQvtCz0YDQsNC90LjRh9C10L0g0L/QviDRgNC10YjQtdC90LjRjiDRgdGD0LTQsCDQuNC70Lgg0L/QviDQuNC90YvQvCDQvtGB0L3QvtCy0LDQvdC40Y/QvCwg0YPRgdGC0LDQvdC+0LLQu9C10L3QvdGL0Lwg0LfQsNC60L7QvdC+0LTQsNGC0LXQu9GM0YHRgtCy0L7QvCDQoNC+0YHRgdC40LnRgdC60L7QuSDQpNC10LTQtdGA0LDRhtC40LguPC9saT4KICAgICAgICAgICAgICAgICAgICA8bGk+0KPQutCw0LfQsNGC0LXQu9GMINGB0YLRgNCw0L3QuNGG0Ysg0LggKNC40LvQuCkg0LTQvtC80LXQvdC90L7QtSDQuNC80Y8g0YHQsNC50YLQsCwg0YHQtdGC0LXQstC+0Lkg0LDQtNGA0LXRgSDQstC60LvRjtGH0LXQvdGLINCyIDxhIGhyZWY9Imh0dHA6Ly9lYWlzLnJrbi5nb3YucnUvIiB0YXJnZXQ9Il9ibGFuayI+0JXQtNC40L3Ri9C5INCg0LXQtdGB0YLRgDwvYT4g0LTQvtC80LXQvdC90YvRhSDQuNC80LXQvSwg0YPQutCw0LfQsNGC0LXQu9C10Lkg0YHRgtGA0LDQvdC40YYg0YHQsNC50YLQvtCyINGB0LXRgtC4IMKr0JjQvdGC0LXRgNC90LXRgsK7INC4INGB0LXRgtC10LLRi9GFINCw0LTRgNC10YHQvtCyLCDQv9C+0LfQstC+0LvRj9GO0YnQuNGFINC40LTQtdC90YLQuNGE0LjRhtC40YDQvtCy0LDRgtGMINGB0LDQudGC0Ysg0LIg0YHQtdGC0LggwqvQmNC90YLQtdGA0L3QtdGCwrssINGB0L7QtNC10YDQttCw0YnQuNC1INC40L3RhNC+0YDQvNCw0YbQuNGOLCDRgNCw0YHQv9GA0L7RgdGC0YDQsNC90LXQvdC40LUg0LrQvtGC0L7RgNC+0Lkg0LIg0KDQvtGB0YHQuNC50YHQutC+0Lkg0KTQtdC00LXRgNCw0YbQuNC4INC30LDQv9GA0LXRidC10L3Qvi48YnI+CiAgICAgICAgICAgICAgICAgICAgICAgINCf0YDQvtCy0LXRgNC40YLRjCDQvdCw0LvQuNGH0LjQtSDQtNC+0LzQtdC90L3QvtCz0L4g0LjQvNC10L3QuCDQuCAo0LjQu9C4KSDRg9C60LDQt9Cw0YLQtdC70Y8g0YHRgtGA0LDQvdC40YbRiyDRgdCw0LnRgtCwLCDRgdC10YLQtdCy0L7Qs9C+INCw0LTRgNC10YHQsCDQsiDQldC00LjQvdC+0Lwg0YDQtdC10YHRgtGA0LUg0LzQvtC20L3QviDQsiDRgNCw0LfQtNC10LvQtTxicj7Cq9Cf0YDQvtGB0LzQvtGC0YAg0YDQtdC10YHRgtGA0LDCuyDQvdCwINGB0LDQudGC0LUKICAgICAgICAgICAgICAgICAgICAgICAgPGEgaHJlZj0iaHR0cDovL2VhaXMucmtuLmdvdi5ydS8iIHRhcmdldD0iX2JsYW5rIj5odHRwOi8vZWFpcy5ya24uZ292LnJ1LzwvYT48L2xpPgogICAgICAgICAgICAgICAgICAgIDxsaT7Qo9C60LDQt9Cw0YLQtdC70Ywg0YHRgtGA0LDQvdC40YbRiyDQuCAo0LjQu9C4KSDQtNC+0LzQtdC90L3QvtC1INC40LzRjywg0YHQtdGC0LXQstC+0Lkg0LDQtNGA0LXRgSDQstC60LvRjtGH0LXQvdGLINCyIDxhIGhyZWY9Imh0dHA6Ly9uYXAucmtuLmdvdi5ydS8iIHRhcmdldD0iX2JsYW5rIj7QoNC10LXRgdGC0YA8L2E+INC00L7QvNC10L3QvdGL0YUg0LjQvNC10L0sINGD0LrQsNC30LDRgtC10LvQtdC5INGB0YLRgNCw0L3QuNGGINGB0LDQudGC0L7QsiDQsiDRgdC10YLQuCDCq9CY0L3RgtC10YDQvdC10YLCuyDQuCDRgdC10YLQtdCy0YvRhSDQsNC00YDQtdGB0L7Qsiwg0L/QvtC30LLQvtC70Y/RjtGJ0LjRhSDQuNC00LXQvdGC0LjRhNC40YbQuNGA0L7QstCw0YLRjCDRgdCw0LnRgtGLINCyINGB0LXRgtC4IMKr0JjQvdGC0LXRgNC90LXRgsK7LCDRgdC+0LTQtdGA0LbQsNGJ0LjQtSDQuNC90YTQvtGA0LzQsNGG0LjRjiwg0YDQsNGB0L/RgNC+0YHRgtGA0LDQvdGP0LXQvNGD0Y4g0YEg0L3QsNGA0YPRiNC10L3QuNC10Lwg0LjRgdC60LvRjtGH0LjRgtC10LvRjNC90YvRhSDQv9GA0LDQsi48YnI+CiAgICAgICAgICAgICAgICAgICAgICAgINCf0YDQvtCy0LXRgNC40YLRjCDQvdCw0LvQuNGH0LjQtSDQtNC+0LzQtdC90L3QvtCz0L4g0LjQvNC10L3QuCDQuCAo0LjQu9C4KSDRg9C60LDQt9Cw0YLQtdC70Y8g0YHRgtGA0LDQvdC40YbRiyDRgdCw0LnRgtCwLCDRgdC10YLQtdCy0L7Qs9C+INCw0LTRgNC10YHQsCDQsiDQoNC10LXRgdGC0YDQtSDQvNC+0LbQvdC+INCyINGA0LDQt9C00LXQu9C1PGJyPsKr0J/RgNC+0YHQvNC+0YLRgCDRgNC10LXRgdGC0YDQsMK7INC90LAg0YHQsNC50YLQtQogICAgICAgICAgICAgICAgICAgICAgICA8YSBocmVmPSJodHRwOi8vbmFwLnJrbi5nb3YucnUvcmVlc3RyLyIgdGFyZ2V0PSJfYmxhbmsiPmh0dHA6Ly9uYXAucmtuLmdvdi5ydS9yZWVzdHIvPC9hPjwvbGk+CiAgICAgICAgICAgICAgICAgICAgPGxpPtCj0LrQsNC30LDRgtC10LvRjCDRgdGC0YDQsNC90LjRhtGLINC4ICjQuNC70LgpINC00L7QvNC10L3QvdC+0LUg0LjQvNGPLCDRgdC10YLQtdCy0L7QuSDQsNC00YDQtdGBINCy0LrQu9GO0YfQtdC90Ysg0LIgPGEgaHJlZj0iaHR0cDovLzM5OC1mei5ya24uZ292LnJ1LyIgdGFyZ2V0PSJfYmxhbmsiPtCg0LXQtdGB0YLRgDwvYT4g0LTQvtC80LXQvdC90YvRhSDQuNC80LXQvSwg0YPQutCw0LfQsNGC0LXQu9C10Lkg0YHRgtGA0LDQvdC40YYg0YHQsNC50YLQvtCyINCyINGB0LXRgtC4IMKr0JjQvdGC0LXRgNC90LXRgsK7INC4INGB0LXRgtC10LLRi9GFINCw0LTRgNC10YHQvtCyLCDQv9C+0LfQstC+0LvRj9GO0YnQuNGFINC40LTQtdC90YLQuNGE0LjRhtC40YDQvtCy0LDRgtGMINGB0LDQudGC0Ysg0LIg0YHQtdGC0LggwqvQmNC90YLQtdGA0L3QtdGCwrssINGB0L7QtNC10YDQttCw0YnQuNC1INC/0YDQuNC30YvQstGLINC6INC80LDRgdGB0L7QstGL0Lwg0LHQtdGB0L/QvtGA0Y/QtNC60LDQvCwg0L7RgdGD0YnQtdGB0YLQstC70LXQvdC40Y4g0Y3QutGB0YLRgNC10LzQuNGB0YLRgdC60L7QuSDQtNC10Y/RgtC10LvRjNC90L7RgdGC0LgsINGD0YfQsNGB0YLQuNGOINCyINC80LDRgdGB0L7QstGL0YUgKNC/0YPQsdC70LjRh9C90YvRhSkg0LzQtdGA0L7Qv9GA0LjRj9GC0LjRj9GFLCDQv9GA0L7QstC+0LTQuNC80YvRhSDRgSDQvdCw0YDRg9GI0LXQvdC40LXQvCDRg9GB0YLQsNC90L7QstC70LXQvdC90L7Qs9C+INC/0L7RgNGP0LTQutCwLjxicj4KICAgICAgICAgICAgICAgICAgICAgICAg0J/RgNC+0LLQtdGA0LjRgtGMINC90LDQu9C40YfQuNC1INC00L7QvNC10L3QvdC+0LPQviDQuNC80LXQvdC4INC4ICjQuNC70LgpINGD0LrQsNC30LDRgtC10LvRjyDRgdGC0YDQsNC90LjRhtGLINGB0LDQudGC0LAsINGB0LXRgtC10LLQvtCz0L4g0LDQtNGA0LXRgdCwINCyINCg0LXQtdGB0YLRgNC1INC80L7QttC90L4g0LIg0YDQsNC30LTQtdC70LU8YnI+wqvQn9GA0L7RgdC80L7RgtGAINGA0LXQtdGB0YLRgNCwwrsg0L3QsCDRgdCw0LnRgtC1CiAgICAgICAgICAgICAgICAgICAgICAgIDxhIGhyZWY9Imh0dHA6Ly8zOTgtZnoucmtuLmdvdi5ydS8iIHRhcmdldD0iX2JsYW5rIj5odHRwOi8vMzk4LWZ6LnJrbi5nb3YucnUvPC9hPjwvbGk+CiAgICAgICAgICAgICAgICAgICAgPGxpPtCj0LrQsNC30LDRgtC10LvRjCDRgdGC0YDQsNC90LjRhtGLINC4ICjQuNC70LgpINC00L7QvNC10L3QvdC+0LUg0LjQvNGPINCy0LrQu9GO0YfQtdC90Ysg0LIgPGEgaHJlZj0iaHR0cDovLzk3LWZ6LnJrbi5nb3YucnUvIiB0YXJnZXQ9Il9ibGFuayI+0KDQtdC10YHRgtGAPC9hPiDQvtGA0LPQsNC90LjQt9Cw0YLQvtGA0L7QsiDRgNCw0YHQv9GA0L7RgdGC0YDQsNC90LXQvdC40Y8g0LjQvdGE0L7RgNC80LDRhtC40Lgg0LIg0YHQtdGC0LggwqvQmNC90YLQtdGA0L3QtdGCwrsg0Lgg0YHQsNC50YLQvtCyICjQuNC70LgpINGB0YLRgNCw0L3QuNGGINGB0LDQudGC0L7QsiDQsiDRgdC10YLQuCDCq9CY0L3RgtC10YDQvdC10YLCuywg0L3QsCDQutC+0YLQvtGA0YvRhSDRgNCw0LfQvNC10YnQsNC10YLRgdGPINC+0LHRidC10LTQvtGB0YLRg9C/0L3QsNGPINC40L3RhNC+0YDQvNCw0YbQuNGPINC4INC00L7RgdGC0YPQvyDQuiDQutC+0YLQvtGA0YvQvCDQsiDRgtC10YfQtdC90LjQtSDRgdGD0YLQvtC6INGB0L7RgdGC0LDQstC70Y/QtdGCINCx0L7Qu9C10LUg0YLRgNC10YUg0YLRi9GB0Y/RhyDQv9C+0LvRjNC30L7QstCw0YLQtdC70LXQuSDRgdC10YLQuCDCq9CY0L3RgtC10YDQvdC10YLCuy48YnI+CiAgICAgICAgICAgICAgICAgICAgICAgINCf0YDQvtCy0LXRgNC40YLRjCDQvdCw0LvQuNGH0LjQtSDQtNC+0LzQtdC90L3QvtCz0L4g0LjQvNC10L3QuCDQuCAo0LjQu9C4KSDRg9C60LDQt9Cw0YLQtdC70Y8g0YHRgtGA0LDQvdC40YbRiyDRgdCw0LnRgtCwINCyINCg0LXQtdGB0YLRgNC1INC80L7QttC90L4g0LIg0YDQsNC30LTQtdC70LUgwqvQn9GA0L7RgdC80L7RgtGAINGA0LXQtdGB0YLRgNCwwrsg0L3QsDxicj7RgdCw0LnRgtC1CiAgICAgICAgICAgICAgICAgICAgICAgIDxhIGhyZWY9Imh0dHA6Ly85Ny1mei5ya24uZ292LnJ1LyIgdGFyZ2V0PSJfYmxhbmsiPmh0dHA6Ly85Ny1mei5ya24uZ292LnJ1LzwvYT48L2xpPgogICAgICAgICAgICAgICAgPC9vbD4KICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgPC9kaXY+CiAgICA8L2Rpdj4KICAgIDxpZnJhbWUgaWQ9ImdhbWVzLXJ0IiBzcmM9Imh0dHBzOi8vZ2FtZXMucnQucnUvYmFubmVkLWZyYW1lIiBmcmFtZWJvcmRlcj0iMCIgd2lkdGg9IjEwMCUiIGhlaWdodD0iNzAwIiBzY3JvbGxpbmc9Im5vIj48L2lmcmFtZT4KICAgIDxzY3JpcHQgdHlwZT0idGV4dC9qYXZhc2NyaXB0Ij4KICAgICAgICB2YXIgZXZlbnRNZXRob2QgPSB3aW5kb3cuYWRkRXZlbnRMaXN0ZW5lciA/ICJhZGRFdmVudExpc3RlbmVyIiA6ICJhdHRhY2hFdmVudCI7CiAgICAgICAgdmFyIGV2ZW50ZXIgPSB3aW5kb3dbZXZlbnRNZXRob2RdOwogICAgICAgIHZhciBtZXNzYWdlRXZlbnQgPSBldmVudE1ldGhvZCA9PSAiYXR0YWNoRXZlbnQiID8gIm9ubWVzc2FnZSIgOiAibWVzc2FnZSI7CgogICAgICAgIGV2ZW50ZXIobWVzc2FnZUV2ZW50LCBmdW5jdGlvbihlKSB7CiAgICAgICAgICAgIGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdnYW1lcy1ydCcpLnN0eWxlLmhlaWdodCA9IGUuZGF0YSArICdweCc7CiAgICAgICAgfSwgZmFsc2UpOwogICAgPC9zY3JpcHQ+CiAgICA8c2NyaXB0PgogICAgICAgIGlmICh0eXBlb2YoVXNlckFnZW50SW5mbykgIT0gJ3VuZGVmaW5lZCcgJiYgIXdpbmRvdy5hZGRFdmVudExpc3RlbmVyKXsKICAgICAgICAgICAgVXNlckFnZW50SW5mby5zdHJCcm93c2VyID0gMTsKICAgICAgICB9CiAgICA8L3NjcmlwdD4KICAgIDxzY3JpcHQgdHlwZT0idGV4dC9qYXZhc2NyaXB0IiBzcmM9Ii4vc3RhdGljL3dhcm5pbmcvanMvanF1ZXJ5Lm1pbi5qcyI+PC9zY3JpcHQ+CiAgICA8c2NyaXB0IHR5cGU9InRleHQvamF2YXNjcmlwdCIgc3JjPSIuL3N0YXRpYy93YXJuaW5nL2pzL21haW4uanMiPjwvc2NyaXB0Pgo8L2JvZHk+CjwvaHRtbD4=
ERROR: Unable to extract OpenGraph title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by dstftw** [comment]
You are blocked according to Роскомнадзор's registry of banned sites.
```
Доступ ограничен

Доступ к запрашиваемому ресурсу ограничен по решению суда или по иным основаниям,
установленным законодательством Российской Федерации

Возможные причины ограничения доступа
Доступ ограничен по решению суда или по иным основаниям, установленным законодательством Российской Федерации.
Указатель страницы и (или) доменное имя сайта, сетевой адрес включены в Единый Реестр доменных имен, указателей страниц сайтов сети «Интернет» и сетевых адресов, позволяющих идентифицировать сайты в сети «Интернет», содержащие информацию, распространение которой в Российской Федерации запрещено.
Проверить наличие доменного имени и (или) указателя страницы сайта, сетевого адреса в Едином реестре можно в разделе
«Просмотр реестра» на сайте http://eais.rkn.gov.ru/
Указатель страницы и (или) доменное имя, сетевой адрес включены в Реестр доменных имен, указателей страниц сайтов в сети «Интернет» и сетевых адресов, позволяющих идентифицировать сайты в сети «Интернет», содержащие информацию, распространяемую с нарушением исключительных прав.
Проверить наличие доменного имени и (или) указателя страницы сайта, сетевого адреса в Реестре можно в разделе
«Просмотр реестра» на сайте http://nap.rkn.gov.ru/reestr/
Указатель страницы и (или) доменное имя, сетевой адрес включены в Реестр доменных имен, указателей страниц сайтов в сети «Интернет» и сетевых адресов, позволяющих идентифицировать сайты в сети «Интернет», содержащие призывы к массовым беспорядкам, осуществлению экстремистской деятельности, участию в массовых (публичных) мероприятиях, проводимых с нарушением установленного порядка.
Проверить наличие доменного имени и (или) указателя страницы сайта, сетевого адреса в Реестре можно в разделе
«Просмотр реестра» на сайте http://398-fz.rkn.gov.ru/
Указатель страницы и (или) доменное имя включены в Реестр организаторов распространения информации в сети «Интернет» и сайтов (или) страниц сайтов в сети «Интернет», на которых размещается общедоступная информация и доступ к которым в течение суток составляет более трех тысяч пользователей сети «Интернет».
Проверить наличие доменного имени и (или) указателя страницы сайта в Реестре можно в разделе «Просмотр реестра» на
сайте http://97-fz.rkn.gov.ru/
```

**Comment by stepshal** [comment]
@dstftw Oh, i see. Okey then.
