### ISSUE TITLE
[8tracks]  Unable to extract trax information

### ISSUE THREAD

**Issue by stepshal** [rg3/youtube-dl#10334]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.08.12**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

```
$ y -v 'http://8tracks.com/ytdl/youtube-dl-test-tracks-a'
[debug] System config: []
[debug] User config: ['-4', '-f', 'best', '--prefer-free-formats', '--no-cache-dir', '--no-mtime', '--youtube-skip-dash-manifest']
[debug] Command-line args: ['-v', 'http://8tracks.com/ytdl/youtube-dl-test-tracks-a']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.08.12
[debug] Python version 3.5.2+ - Linux-4.7.0-rc7-686-i686-with-debian-stretch-sid
[debug] exe versions: ffmpeg 3.1.2, ffprobe 3.1.2, rtmpdump 2.4
[debug] Proxy map: {}
[8tracks] youtube-dl-test-tracks-a: Downloading webpage
ERROR: Unable to extract trax information; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/YoutubeDL.py", line 691, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/common.py", line 347, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/eighttracks.py", line 111, in _real_extract
    r"(?s)PAGE\.mix\s*=\s*({.+?});\n", webpage, 'trax information'),
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/common.py", line 650, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract trax information; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
http://8tracks.com/ytdl/youtube-dl-test-tracks-a

**Comment by yan12125** [comment]
It says:

> Oops! It looks like the mix you are trying to listen to is not currently available. In the meantime, check out these playlists.

Do you have other examples?

**Comment by stepshal** [comment]
@yan12125 http://8tracks.com/wildernessqueen/the-battle-begins#smart_id=all:safe
Download is not going:
```
[8tracks] the-battle-begins: Downloading webpage
[8tracks] the-battle-begins: Downloading song information 1/16
[8tracks] the-battle-begins: Downloading song information 2/16
[8tracks] the-battle-begins: Downloading song information 3/16
[8tracks] the-battle-begins: Downloading song information 4/16
[8tracks] the-battle-begins: Downloading song information 5/16
[8tracks] the-battle-begins: Downloading song information 6/16
[8tracks] the-battle-begins: Waiting for 255.3125 seconds
```

**Comment by yan12125** [comment]
It's a countermeasure against throttling detection of 8tracks.com. See #2310 for discussion.

I'll try to update the test, while #7350 should be resolved first.

**Comment by ackspam** [comment]
youtube-dl not working with 8tracks again, it was ok earlier in June, I suspect 8tracks changed something.

# youtube-dl -U
youtube-dl is up-to-date (2017.06.18)

# youtube-dl --verbose "https://8tracks.com/saturnsgold/im-pulse"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://8tracks.com/saturnsgold/im-pulse']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.06.18
[debug] Python version 2.7.9 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.8
[debug] exe versions: avconv 11.9-6, avprobe 11.9-6, rtmpdump 2.4
[debug] Proxy map: {}
[8tracks] im-pulse: Downloading webpage
ERROR: Unable to extract trax information; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 762, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/eighttracks.py", line 111, in _real_extract
    r"(?s)PAGE\.mix\s*=\s*({.+?});\n", webpage, 'trax information'),
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 782, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract trax information; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by ackspam** [comment]
8tracks is working again in version 2017.06.25!
