### ISSUE TITLE
[radiobremen] 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by stepshal** [rg3/youtube-dl#10337]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.08.12**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

```
$ y -v 'http://www.radiobremen.de/mediathek/index.html?id=114720'
[debug] System config: []
[debug] User config: ['-4', '-f', 'best', '--prefer-free-formats', '--no-cache-dir', '--no-mtime', '--youtube-skip-dash-manifest']
[debug] Command-line args: ['-v', 'http://www.radiobremen.de/mediathek/index.html?id=114720']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.08.12
[debug] Python version 3.5.2+ - Linux-4.7.0-rc7-686-i686-with-debian-stretch-sid
[debug] exe versions: ffmpeg 3.1.2, ffprobe 3.1.2, rtmpdump 2.4
[debug] Proxy map: {}
[radiobremen] 114720: Downloading metadata
[radiobremen] 114720: Downloading video information
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl", line 9, in <module>
    load_entry_point('youtube-dl==2016.8.12', 'console_scripts', 'youtube-dl')()
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/__init__.py", line 433, in main
    _real_main(argv)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/__init__.py", line 423, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/YoutubeDL.py", line 1786, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/YoutubeDL.py", line 691, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/common.py", line 347, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/radiobremen.py", line 49, in _real_extract
    (video_id, video_id, mobj.group("secret"), mobj.group('width')))
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by yan12125** [comment]
There's a strange message from my side:
```
Dieser Beitrag liegt im eingestellten Format leider nicht vor.
Wählen Sie ggf. über "Einstellungen" ein alternatives Format.
Wir empfehlen "H.264 Breitband" für Videos.
```
Can you watch this video?

**Comment by stepshal** [comment]
@yan12125 No.

**Comment by stepshal** [comment]
@yan12125 This url works: http://www.radiobremen.de/mediathek/index.html?id=141876

**Comment by yan12125** [comment]
Thanks, the test case is updated.
