### ISSUE TITLE
UnicodeEncodeError in Windows (was: Some error)

### ISSUE THREAD

**Issue by mevsme** [rg3/youtube-dl#1033]
```cmd
c:\Download>py youtube-dl --no-check-certificate -t "http://www.youtube.com/watch?v=qFzlD1q9I2U"
[youtube] Setting language
[youtube] qFzlD1q9I2U: Downloading video webpage
[youtube] qFzlD1q9I2U: Downloading video info webpage
[youtube] qFzlD1q9I2U: Extracting video information
[youtube] qFzlD1q9I2U: Encrypted signatures detected.
Traceback (most recent call last):
  File "D:\Program Files (x86)\Python33\lib\runpy.py", line 160, in _run_module_as_main    "__main__", fname, loader, pkg_name)
  File "D:\Program Files (x86)\Python33\lib\runpy.py", line 73, in _run_code    exec(code, run_globals)
  File "youtube-dl\__main__.py", line 18, in <module>
  File "youtube-dl\youtube_dl\__init__.py", line 634, in main
  File "youtube-dl\youtube_dl\__init__.py", line 618, in _real_main
  File "youtube-dl\youtube_dl\YoutubeDL.py", line 575, in download
  File "youtube-dl\youtube_dl\YoutubeDL.py", line 327, in extract_info
  File "youtube-dl\youtube_dl\YoutubeDL.py", line 410, in process_ie_result
  File "youtube-dl\youtube_dl\YoutubeDL.py", line 410, in <listcomp>
  File "youtube-dl\youtube_dl\YoutubeDL.py", line 357, in process_ie_result
  File "youtube-dl\youtube_dl\YoutubeDL.py", line 550, in process_info
  File "youtube-dl\youtube_dl\FileDownloader.py", line 470, in _do_download
  File "youtube-dl\youtube_dl\FileDownloader.py", line 198, in report_destination
  File "youtube-dl\youtube_dl\FileDownloader.py", line 117, in to_screen
  File "youtube-dl\youtube_dl\YoutubeDL.py", line 136, in to_screen
  File "D:\Program Files (x86)\Python33\lib\encodings\cp866.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\xf3' in position 33: character maps to <undefined>
```

**Comment by dstftw** [comment]
Works with latest version. Closing.
