### ISSUE TITLE
aenetworks error

### ISSUE THREAD

**Issue by StevenDTX** [rg3/youtube-dl#10345]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.08.13*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2016.08.13**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [X] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
E:\>youtube-dl "http://www.aetv.com/shows/wahlburgers/season-6/episode-1" --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://www.aetv.com/shows/wahlburgers/season-6/episode-1', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.08.13
[debug] Python version 3.4.4 - Windows-10-10.0.10586
[debug] exe versions: ffmpeg N-72383-g7206b94, ffprobe N-72383-g7206b94, rtmpdump 2.4
[debug] Proxy map: {}
[aenetworks] wahlburgers/season-6/episode-1: Downloading webpage
[aenetworks] 719428163744: Downloading JSON metadata
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpz_7f3hc1\build\youtube_dl\__init__.py", line 433, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpz_7f3hc1\build\youtube_dl\__init__.py", line 423, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpz_7f3hc1\build\youtube_dl\YoutubeDL.py", line 1786, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpz_7f3hc1\build\youtube_dl\YoutubeDL.py", line 691, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpz_7f3hc1\build\youtube_dl\extractor\common.py", line 347, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpz_7f3hc1\build\youtube_dl\extractor\aenetworks.py", line 114, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpz_7f3hc1\build\youtube_dl\extractor\theplatform.py", line 227, in _extract_mvpd_auth
  File "C:\Python\Python34\lib\netrc.py", line 32, in __init__
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\steven\\.netrc'

...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://www.aetv.com/shows/wahlburgers/season-6/episode-1

---

### Description of your *issue*, suggested solution and other information

Always get this error on any aenetworks video:
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpz_7f3hc1\build\youtube_dl\__init__.py", line 433, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpz_7f3hc1\build\youtube_dl\__init__.py", line 423, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpz_7f3hc1\build\youtube_dl\YoutubeDL.py", line 1786, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpz_7f3hc1\build\youtube_dl\YoutubeDL.py", line 691, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpz_7f3hc1\build\youtube_dl\extractor\common.py", line 347, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpz_7f3hc1\build\youtube_dl\extractor\aenetworks.py", line 114, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpz_7f3hc1\build\youtube_dl\extractor\theplatform.py", line 227, in _extract_mvpd_auth
  File "C:\Python\Python34\lib\netrc.py", line 32, in __init__
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\steven\\.netrc'

Yes, these videos require a login. I use DirecTV. The videos play fine in IE. I have tried using a cookies.txt file, unsuccessfully.

I have tried creating a .netrc file, but that does not seem to matter either.

Any suggestions, or is this an extractor issue?

Thanks.

**Comment by yan12125** [comment]
Did you put the ```.netrc``` file at ```C:\Users\steven\.netrc```?

**Comment by StevenDTX** [comment]
I have tried several .netrc variations, and nothing seems to work.

**Comment by yan12125** [comment]
Well, currently only DTV is supported.

/cc @remitamine, who knows more about Adobe Pass.

**Comment by remitamine** [comment]
the error said that youtube-dl couldn't find the netrc file, the error is not related AdobePass, i think with this kind of error any extractor that needs auth won't work.

**Comment by StevenDTX** [comment]
I just created a new .netrc file, with DirecTV credentials.

.netrc file:
```
machine aenetworks login <USERNAME> password <PASSWORD>
machine common login <USERNAME> password <PASSWORD>
machine theplatform login <USERNAME> password <PASSWORD>
```

This is what I get now:
```
E:\>youtube-dl "http://www.aetv.com/shows/wahlburgers/season-6/episode-1" --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://www.aetv.com/shows/wahlburgers/season-6/episode-1', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.08.13
[debug] Python version 3.4.4 - Windows-10-10.0.10586
[debug] exe versions: ffmpeg N-72383-g7206b94, ffprobe N-72383-g7206b94, rtmpdump 2.4
[debug] Proxy map: {}
[aenetworks] wahlburgers/season-6/episode-1: Downloading webpage
[aenetworks] 719428163744: Downloading JSON metadata
[aenetworks] 719428163744: Downloading SMIL data
ERROR: This release requires that we validate your access but we received an error while performing the check.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpz_7f3hc1\build\youtube_dl\YoutubeDL.py", line 691, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpz_7f3hc1\build\youtube_dl\extractor\common.py", line 347, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpz_7f3hc1\build\youtube_dl\extractor\aenetworks.py", line 118, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpz_7f3hc1\build\youtube_dl\extractor\theplatform.py", line 43, in _extract_theplatform_smil
youtube_dl.utils.ExtractorError: This release requires that we validate your access but we received an error while performing the check.
```

**Comment by remitamine** [comment]
you don't have to add an entry for every site, just add this:
```
machine DTV login <email> password <password>
```
and it will work with extractor that support Adobe Pass auth.

**Comment by StevenDTX** [comment]
Thank you!!  Thank you!!  Thank you!!
