### ISSUE TITLE
Thumbnail embedding support for webm files

### ISSUE THREAD

**Issue by VitCN** [rg3/youtube-dl#10360]
### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

Thumbnail embedding support for webm files. WebM seems to be very similar to mkv, so it should be able to be supported the same way once mkv embedding is fixed (#10359).

**Comment by kunal394** [comment]
@VitCN  mp3 thumbnail is not working for me. Can anyone confirm if that is an issue or should I show my python code I am using to download mp3 files using the youtube_dl python module!!

**Comment by yan12125** [comment]
@kunal394 Maybe your problem is the same as #5957.

**Comment by kunal394** [comment]
@yan12125 for me the thumbnail just doesn't shows. I am going to share my code, so please suggest if I need to make any changes or if I have done something wrong.

```
#!/usr/bin/env python

from __future__ import unicode_literals
import youtube_dl, sys, argparse

common_settings = {
        'continue': True,
        'embedthumbnail': True,
        'fixup': 'detect_or_warn',  # Automatically correct known faults of the file.
        'ignoreerrors' : True,
        'outtmpl': '%(title)s.%(ext)s',     # name the file the title of the video
        #'proxy': 'http:proxy.iiit.ac.in:8080' #proxy
        'verbose': True
        }

#correct flac: something is wrong!!!!
flac = {
        'extractaudio' : True,      # only keep the audio
        'format': 'bestaudio/best', # choice of quality
        'noplaylist' : True,        # only download single song, not playlist
        'postprocessors': [{
            'key': 'FFmpegExtractAudio',
            'preferredcodec': 'flac'
            }]
    }

mp3 = {
        #'audioformat' : "mp3",      # convert to mp3 
        'extractaudio' : True,      # only keep the audio
        'format': 'bestaudio/best', # choice of quality
        'noplaylist' : True,        # only download single song, not playlist
        'postprocessors': [{
            'key': 'FFmpegExtractAudio',
            'preferredcodec': 'mp3',
            'preferredquality': '320',
            }]
    }

mp3_playlist = {
        #'audioformat' : "mp3",      # convert to mp3 
        'extractaudio' : True,      # only keep the audio
        'format': 'bestaudio/best', # choice of quality
        'noplaylist' : False,        # only download single song, not playlist
        'postprocessors': [{
            'key': 'FFmpegExtractAudio',
            'preferredcodec': 'mp3',
            'preferredquality': '320',
            }]
    }

mp4 = {
        #'extractaudio' : True,      # only keep the audio
        'format': 'bestvideo+bestaudio/bestvideo[ext=mp4]+bestaudio/bestvideo[ext=mkv]+bestaudio/best', # choice of quality
        'noplaylist' : True,        # only download single song, not playlist
        'videoformat' : "mp4"      # convert to mp4
    }

mp4_playlist = {
        'format': 'bestvideo+bestaudio/bestvideo[ext=mp4]+bestaudio/bestvideo[ext=mkv]+bestaudio/best', # choice of quality
        'noplaylist' : False,        # only download single song, not playlist
        'videoformat' : "mp4"      # convert to mp4 
    }

def download(args):
    options = {}
    if args['type'].endswith('p'):
        try:
            options.update({'playliststart': int(args['play_start'])})
        except:
            pass
        try:
            options.update({'playlistend': int(args['play_end'])})
        except:
            pass
    if args['type'] == 'flac':
        options.update(flac)
    elif args['type'] == 'mp3':
        options.update(mp3)
    elif args['type'] == 'mp3p':
        options.update(mp3_playlist)
    elif args['type'] == 'mp4':
        options.update(mp4)
    elif args['type'] == 'mp4p':
        options.update(mp4_playlist)

    options.update(common_settings)
    ydl = youtube_dl.YoutubeDL(options)
    r = ydl.extract_info(args['url'])

if __name__ == "__main__":
    arg_names = ['command', 'type', 'url', 'play_start', 'play_end']
    args = dict(zip(arg_names, sys.argv))
    download(args)

```

**Comment by dstftw** [comment]
@kunal394 you did not add a `EmbedThumbnail` postprocessor for thumbnail embedding.

**Comment by kunal394** [comment]
@dstftw I have no idea about its syntax. Can you please explain it!!

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl/blob/master/youtube_dl/__init__.py#L262

**Comment by kunal394** [comment]
@dstftw I am missing something again!! But I don't know what!!!!

Code:
```
#!/usr/bin/env python

from __future__ import unicode_literals
import youtube_dl, sys, argparse

common_settings = {
        'continue': True,
        'embedthumbnail': True,
        'fixup': 'detect_or_warn',  # Automatically correct known faults of the file.
        'ignoreerrors' : True,
        'outtmpl': '%(title)s.%(ext)s',     # name the file the title of the video
        #'proxy': 'http:proxy.iiit.ac.in:8080' #proxy
        'verbose': True
        }

def contruct_flac():
    #TODO:debug flac!! something's wrong!!!!
    flac = {
        'extractaudio' : True,      # only keep the audio
        'format': 'bestaudio/best', # choice of quality
        'noplaylist' : True,        # only download single song, not playlist
        }
    postprocessors = [{
        'key': 'FFmpegExtractAudio',
        'preferredcodec': 'flac'
        }]
    return flac, postprocessors

def contruct_mp3():
    mp3 = {
        #'audioformat' : "mp3",      # convert to mp3 
        'extractaudio' : True,      # only keep the audio
        'format': 'bestaudio/best', # choice of quality
        'noplaylist' : True,        # only download single song, not playlist
        }
    postprocessors = [{
        'key': 'FFmpegExtractAudio',
        'preferredcodec': 'mp3',
        'preferredquality': '320',
        }]
    return mp3, postprocessors

def contruct_mp3_playlist():
    mp3_playlist = {
        #'audioformat' : "mp3",      # convert to mp3 
        'extractaudio' : True,      # only keep the audio
        'format': 'bestaudio/best', # choice of quality
        'noplaylist' : False,        # only download single song, not playlist
        }
    postprocessors = [{
        'key': 'FFmpegExtractAudio',
        'preferredcodec': 'mp3',
        'preferredquality': '320',
        }]
    return mp3_playlist, postprocessors

def contruct_mp4():
    mp4 = {
        #'extractaudio' : True,      # only keep the audio
        'format': 'bestvideo+bestaudio/bestvideo[ext=mp4]+bestaudio/bestvideo[ext=mkv]+bestaudio/best', # choice of quality
        'noplaylist' : True,        # only download single song, not playlist
        'videoformat' : "mp4"      # convert to mp4
        }
    return mp4

def contruct_mp4_playlist():
    mp4_playlist = {
        'format': 'bestvideo+bestaudio/bestvideo[ext=mp4]+bestaudio/bestvideo[ext=mkv]+bestaudio/best', # choice of quality
        'noplaylist' : False,        # only download single song, not playlist
        'videoformat' : "mp4"      # convert to mp4 
        }
    return mp4_playlist

def download(args):
    global common_settings
    postprocessors = []

    if args['type'] == 'flac':
        options, p = contruct_flac()
    elif args['type'] == 'mp3':
        options, p = contruct_mp3()
    elif args['type'] == 'mp3p':
        options, p = contruct_mp3_playlist()
    elif args['type'] == 'mp4':
        options = contruct_mp4()
        p = []
    elif args['type'] == 'mp4p':
        options = contruct_mp4_playlist()
        p = []

    postprocessors.extend(p)
    postprocessors.append({
            'key': 'EmbedThumbnail',
            'already_have_thumbnail': False
            })
    options.update({'postprocessors' : postprocessors})

    if args['type'].endswith('p'):
        try:
            options.update({'playliststart': int(args['play_start'])})
        except:
            pass
        try:
            options.update({'playlistend': int(args['play_end'])})
        except:
            pass

    options.update(common_settings)


    print options
    ydl = youtube_dl.YoutubeDL(options)
    r = ydl.extract_info(args['url'])

if __name__ == "__main__":
    arg_names = ['command', 'type', 'url', 'play_start', 'play_end']
    args = dict(zip(arg_names, sys.argv))
    download(args)

```

Output:

```
$ ytd mp3 'https://www.youtube.com/watch?v=NeP6V_Ajego'
{u'ignoreerrors': True, u'verbose': True, u'format': u'bestaudio/best', u'embedthumbnail': True, u'continue': True, u'outtmpl': u'%(title)s.%(ext)s', u'postprocessors': [{u'preferredcodec': u'mp3', u'preferredquality': u'320', u'key': u'FFmpegExtractAudio'}, {u'already_have_thumbnail': False, u'key': u'EmbedThumbnail'}], u'noplaylist': True, u'extractaudio': True, u'fixup': u'detect_or_warn'}
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.08.22
[debug] Python version 2.7.12 - Linux-4.4.0-34-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 2.8.6-1ubuntu2, avprobe 2.8.6-1ubuntu2, ffmpeg 2.8.6-1ubuntu2, ffprobe 2.8.6-1ubuntu2
[debug] Proxy map: {'ftp': 'ftp://proxy.iiit.ac.in:8080/', 'all': 'socks://proxy.iiit.ac.in:8080/', 'http': 'http://proxy.iiit.ac.in:8080/', 'https': 'https://proxy.iiit.ac.in:8080/', 'no': 'localhost, 127.0.0.1, iiit.ac.in, .iiit.ac.in, iiit.net, .iiit.net, 172.16.0.0/12, 192.168.0.0/16, 10.0.0.0/8', 'socks': 'socks://proxy.iiit.ac.in:8080/'}
[youtube] NeP6V_Ajego: Downloading webpage
[youtube] NeP6V_Ajego: Downloading video info webpage
[youtube] NeP6V_Ajego: Extracting video information
[youtube] NeP6V_Ajego: Downloading MPD manifest
WARNING: "id" field is not a string - forcing string conversion
[debug] Invoking downloader on u'https://r2---sn-o3o-itql.googlevideo.com/videoplayback?id=35e3fa57f0237a0a&itag=140&source=youtube&requiressl=yes&mm=31&mn=sn-o3o-itql&pl=24&pcm2cms=yes&initcwndbps=8958750&mv=m&ms=au&ratebypass=yes&mime=audio/mp4&gir=yes&clen=35308664&lmt=1419402147440575&dur=2199.346&key=dg_yt0&signature=42E605EE6C6FB791147C4FB57696E8896BFB925C.723AD629A328EA04973F4240708DF3B9F3906E0D&mt=1471970459&upn=i-LjBBPWdwM&sver=3&fexp=9405975,9419451,9422596,9423554,9428398,9431012,9432564,9433096,9433221,9433946,9435526,9436048,9436834,9437981,9438327,9438662,9439365,9439580,9440029,9442424,9442426,9442658,9442688,9443045,9443741,9444229,9444895,9445060,9445775&ip=14.139.82.6&ipbits=0&expire=1471992435&sparams=ip,ipbits,expire,id,itag,source,requiressl,mm,mn,pl,pcm2cms,initcwndbps,mv,ms,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: The Fun of It - 1970 - Meditation [Full Album].m4a
[download] 100% of 33.67MiB in 00:45
[ffmpeg] Correcting container in "The Fun of It - 1970 - Meditation [Full Album].m4a"
[debug] ffmpeg command line: avconv -y -i 'file:The Fun of It - 1970 - Meditation [Full Album].m4a' -c copy -f mp4 'file:The Fun of It - 1970 - Meditation [Full Album].temp.m4a'
[debug] avconv command line: avprobe -show_streams 'file:The Fun of It - 1970 - Meditation [Full Album].m4a'
[ffmpeg] Destination: The Fun of It - 1970 - Meditation [Full Album].mp3
[debug] ffmpeg command line: avconv -y -i 'file:The Fun of It - 1970 - Meditation [Full Album].m4a' -vn -acodec libmp3lame -b:a 320k 'file:The Fun of It - 1970 - Meditation [Full Album].mp3'
Deleting original file The Fun of It - 1970 - Meditation [Full Album].m4a (pass -k to keep)
ERROR: u'filename'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 702, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 748, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1430, in process_video_result
    self.process_info(new_info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1768, in process_info
    self.post_process(filename, info_dict)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1832, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/postprocessor/embedthumbnail.py", line 36, in run
    thumbnail_filename = info['thumbnails'][-1]['filename']
KeyError: u'filename'

```

I don't know whether to set already_have_thumbnail as True or False, so I checked with both and both of them give the same error.

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl/issues/10185#issuecomment-236192440

**Comment by kunal394** [comment]
@dstftw thanks a lot for the help. I just need to clarify a couple of more things:

1. Suppose I have a downloaded a file using the python script I shared above. Now if I download the same song, should the script say that the file already exists or should it simply re-download the song i.e. I am asking what is the default behavior of youtube-dl in such a case? Because right now it re-downloads the song even if it has already been downloaded. So, is this feature simply not there or am I again missing something?

2. When I download a song, the cover art shows in the vlc but not in the file browser of ubuntu. Do you have any idea why is it so?

**Comment by dstftw** [comment]
Open a new issue.
