### ISSUE TITLE
KeyError: 'assetId' on litv.tv

### ISSUE THREAD

**Issue by casinero** [rg3/youtube-dl#10385]
youtube-dl.exe --no-playlist -v -J -i  https://www.litv.tv/vod/drama/content.do?brc_id=&id=VOD00044840
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--no-playlist', '-v', '-J', '-i', 'https://www.litv.tv/vod/drama/content.do?brc_id=&id=VOD00044840']
[debug] Encodings: locale cp950, fs mbcs, out cp950, pref cp950
[debug] youtube-dl version 2016.08.19
[debug] Python version 3.4.4 - Windows-10-10.0.10586
[debug] exe versions: ffmpeg N-70348-g9564375, ffprobe N-70348-g9564375
[debug] Proxy map: {}
ERROR: An extractor error has occurred. (caused by KeyError('assetId',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpppfzkhrf\build\youtube_dl\extractor\common.py", line 347, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpppfzkhrf\build\youtube_dl\extractor\litv.py", line 100, in _real_extract
KeyError: 'assetId'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpppfzkhrf\build\youtube_dl\extractor\common.py", line 347, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpppfzkhrf\build\youtube_dl\extractor\litv.py", line 100, in _real_extract
KeyError: 'assetId'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpppfzkhrf\build\youtube_dl\YoutubeDL.py", line 691, in extract_info
null
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpppfzkhrf\build\youtube_dl\extractor\common.py", line 353, in extract
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('assetId',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by yan12125** [comment]
Thanks for the report. "promo" videos on LiTV will be supported in the next version.
