### ISSUE TITLE
Site support request [stopgame.ru]

### ISSUE THREAD

**Issue by YogSottot** [rg3/youtube-dl#10395]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.08.19**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Site support request (request for adding support for a new site)

```
>youtube-dl -vF http://stopgame.ru/gamemovie/show/390
[debug] System config: []
[debug] User config: [u'--sub-lang', u'ru,en']
[debug] Command-line args: [u'-vF', u'http://stopgame.ru/gamemovie/show/390']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.08.19
[debug] Python version 2.7.10 - Linux-4.1.30-gentoo-nvidia-x86_64-Intel-R-_Core-TM-2_Duo_CPU_E8400_@_3.00GHz-with-gentoo-2.2
[debug] exe versions: ffmpeg 3.1.2, ffprobe 3.1.2
[debug] Proxy map: {}
[generic] 390: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 390: Downloading webpage
[generic] 390: Extracting information
ERROR: Unsupported URL: http://stopgame.ru/gamemovie/show/390
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/generic.py", line 1633, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/lib64/python2.7/site-packages/youtube_dl/compat.py", line 2525, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/lib64/python2.7/site-packages/youtube_dl/compat.py", line 2514, in _XML
    parser.feed(text)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: duplicate attribute: line 2, column 37
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 691, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/common.py", line 347, in extract
    return self._real_extract(url)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/generic.py", line 2377, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://stopgame.ru/gamemovie/show/390
```
- Single video: http://stopgame.ru/gamemovie/show/390
- Single video: http://stopgame.ru/machinima/show/536
- Playlist: http://stopgame.ru/gamemovie/genre/vghs
- Playlist: http://stopgame.ru/machinima/genre/red_vs_blue

**Comment by sufuf3** [comment]
Hi, may I try to send a PR of this issue?

It still can't download the video of this website via version 2017.07.09.
```
$ youtube_dl/__main__.py -vF http://stopgame.ru/gamemovie/show/390
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-vF', u'http://stopgame.ru/gamemovie/show/390']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.07.09
[debug] Git HEAD: 2583c0b54
[debug] Python version 2.7.10 - Darwin-16.6.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[generic] 390: Requesting header
[redirect] Following redirect to https://stopgame.ru/gamemovie/show/390
[generic] 390: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 390: Downloading webpage
[generic] 390: Extracting information
ERROR: Unsupported URL: https://stopgame.ru/gamemovie/show/390
Traceback (most recent call last):
  File "/Users/sufuf3/Documents/youtube-dl/youtube_dl/extractor/generic.py", line 2043, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/Users/sufuf3/Documents/youtube-dl/youtube_dl/compat.py", line 2539, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/Users/sufuf3/Documents/youtube-dl/youtube_dl/compat.py", line 2528, in _XML
    parser.feed(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: duplicate attribute: line 2, column 37
Traceback (most recent call last):
  File "/Users/sufuf3/Documents/youtube-dl/youtube_dl/YoutubeDL.py", line 775, in extract_info
    ie_result = ie.extract(url)
  File "/Users/sufuf3/Documents/youtube-dl/youtube_dl/extractor/common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "/Users/sufuf3/Documents/youtube-dl/youtube_dl/extractor/generic.py", line 2893, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://stopgame.ru/gamemovie/show/390
```
I'll follow the `Adding support for a new site` of [CONTRIBUTING](https://github.com/rg3/youtube-dl/blob/master/CONTRIBUTING.md) to send a PR.

Thank you. 😃

**Comment by yan12125** [comment]
Go ahead :)
