### ISSUE TITLE
[YouTube] Unable to log in: bad username or password

### ISSUE THREAD

**Issue by elundmark** [rg3/youtube-dl#10392]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.08.19*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.08.19**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)

Failed to login and download my Watch Later list. Using netrc, which I haven't edited, worked fine  couple of days ago, but never once since. Works fine without `--netrc`.

```
[download https://www.youtube.com/playlist?list=WL]
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--no-mtime', u'--ignore-errors', u'--rate-limit=1000K', u'--netrc', u'--mark-watched', u'--verbose', u'https://www.youtube.com/playlist?list=WL']
[debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8
[debug] youtube-dl version 2016.08.19
[debug] Python version 2.7.12 - Linux-4.4.0-34-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.6-1ubuntu2, ffprobe 2.8.6-1ubuntu2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:watchlater] Downloading login page
[youtube:watchlater] Logging in
WARNING: unable to log in: bad username or password
[youtube:watchlater] WL: Downloading webpage
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 691, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 347, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 2333, in _real_extract
    return self._extract_playlist('WL')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1922, in _extract_playlist
    page, 'title')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 659, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 650, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by nazar2sfive** [comment]
same problem here

```
android@android:~$ youtube-dl -f 43 -u nazar2sfive@gmail.com -p thisisfake https://www.youtube.com/watch?v=c6oWQ8p0FuI -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-f', u'43', u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'https://www.youtube.com/watch?v=c6oWQ8p0FuI', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.08.17
[debug] Python version 2.7.12 - Linux-4.4.0-34-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.6-1ubuntu2, ffprobe 2.8.6-1ubuntu2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] Downloading login page
[youtube] Logging in
WARNING: unable to log in: bad username or password
[youtube] c6oWQ8p0FuI: Downloading webpage
[youtube] c6oWQ8p0FuI: Downloading embed webpage
[youtube] c6oWQ8p0FuI: Refetching age-gated info webpage
ERROR: c6oWQ8p0FuI: YouTube said: Please sign in to view this video.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 691, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 347, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 1321, in _real_extract
    expected=True, video_id=video_id)
ExtractorError: c6oWQ8p0FuI: YouTube said: Please sign in to view this video.
```

**Comment by nazar2sfive** [comment]
even after update

```
youtube-dl -f 43 -u nazar2sfive@gmail.com -p thisisanotherfake https://www.youtube.com/watch?v=c6oWQ8p0FuI -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-f', u'43', u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'https://www.youtube.com/watch?v=c6oWQ8p0FuI', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.08.19
[debug] Python version 2.7.12 - Linux-4.4.0-34-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.6-1ubuntu2, ffprobe 2.8.6-1ubuntu2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] Downloading login page
[youtube] Logging in
WARNING: unable to log in: bad username or password
[youtube] c6oWQ8p0FuI: Downloading webpage
[youtube] c6oWQ8p0FuI: Downloading embed webpage
[youtube] c6oWQ8p0FuI: Refetching age-gated info webpage
ERROR: c6oWQ8p0FuI: YouTube said: Please sign in to view this video.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 691, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 347, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 1321, in _real_extract
    expected=True, video_id=video_id)
ExtractorError: c6oWQ8p0FuI: YouTube said: Please sign in to view this video.

```

**Comment by dstftw** [comment]
Post the output with `--dump-pages`.

**Comment by elundmark** [comment]
`sudo youtube-dl -U && youtube-dl -u fake@email.com -p fakepass -v --dump-pages https://www.youtube.com/playlist?list=WL &> ~/yt.log`

Output was too big so I attached it.

[yt.txt](https://github.com/rg3/youtube-dl/files/428724/yt.txt)

**Comment by Shamus03** [comment]
Same issue here, verified that username and password are correct in .netrc and two factor authentication is off.

[log.txt](https://github.com/rg3/youtube-dl/files/428883/log.txt)

**Comment by MatrixView** [comment]
Same here since yesterday evening GMT 23:00, before this time everything worked fine. Upgraded to latest version (22-08-2016), to no avail. :-(
Perhaps YT's login page changed?
------------------------
youtube-dl -u %username% -p %password% -v --dump-pages :ytsubs > YTlog.txt
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-u', 'PRIVATE', '-p', 'PRIVATE', '-v', '--dump-pages', ':ytsubs']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2016.08.22
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-67388-g37425fc, ffprobe N-67388-g37425fc, rtmpdump 2.4-47-gc26c541
[debug] Proxy map: {}
WARNING: unable to log in: bad username or password
-------------------------
[YTlog.txt](https://github.com/rg3/youtube-dl/files/431796/YTlog.txt)

**Comment by radoslawg** [comment]
I will also chime in with "same issue here' type of message. :)

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-vvv', '--no-check-certificate', '--playlist-end', '299', '-u', 'PRIVATE', '-p', 'PRIVATE', '-o', '%(upload_date)s#%(playlist_index)s#%(title)s#%(uploader)s.%(ext)s', '--no-mtime', '--restrict-filenames', '-f', '137+bestaudio/298+bestaudio/22/136+bestaudio/135+bestaudio/134+bestaudio/133+bestaudio', '--write-sub', '--sub-lang', 'pl,en', '--merge-output-format', 'mkv', '--dateafter', '20160822', '--datebefore', '20160822', '--playlist-reverse', '-i', ':ytsubs']
[debug] Encodings: locale cp1250, fs mbcs, out cp852, pref cp1250
[debug] youtube-dl version 2016.08.22
[debug] Python version 3.4.4 - Windows-10-10.0.10586
[debug] exe versions: ffmpeg N-79260-g0c94906, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:subscriptions] Downloading login page
[youtube:subscriptions] Logging in
WARNING: unable to log in: bad username or password
[youtube:subscriptions] Youtube Subscriptions: Downloading webpage
[download] Downloading playlist: Youtube Subscriptions
[youtube:subscriptions] playlist Youtube Subscriptions: Collected 0 video ids (downloading 0 of them)
[download] Finished downloading playlist: Youtube Subscriptions
```
[dump.txt](https://github.com/rg3/youtube-dl/files/432246/dump.txt)
