### ISSUE TITLE
Twitch VODs which require login/subscription don't work (again)

### ISSUE THREAD

**Issue by TheRyuu** [rg3/youtube-dl#10397]
Twitch VODs which require a subscription appear to be broken again.  This worked up until failry recently although I haven't used it in quite some time.  I believe it broke sometime within the past month or two.  The only other issue I found for this was something from last year[1] but it's worked correctly since then so I'm not sure that's related.

I first noticed this bug while trying to watch a twitch vod in mpv.  Live streams appear to still work correctly (since they do not require a login) as do vods from accounts which do not require a subscription.

When I try and use youtube-dl directly:
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '--username=PRIVATE', '--password=PRIVATE', 'https://www.twitch.tv/day9tv/v/84517558']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.08.19
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: none
[debug] Proxy map: {}
[twitch:vod] Downloading login page
[twitch:vod] Logging in as PRIVATE
[twitch:vod] 84517558: Downloading vod info JSON
[twitch:vod] 84517558: Downloading vod access token
[twitch:vod] 84517558: Downloading m3u8 information
ERROR: Failed to download m3u8 information: HTTP Error 403: ERROR (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpppfzkhrf\build\youtube_dl\extractor\common.py", line 394, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpppfzkhrf\build\youtube_dl\YoutubeDL.py", line 1996, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
```

As I said this was working up until fairly recently so I'm not sure if the previous issue I linked to is related or not.

[1] https://github.com/rg3/youtube-dl/issues/6628

**Comment by dstftw** [comment]
Does it work with 2016.08.22?

**Comment by TheRyuu** [comment]
I'll give it a shot as soon as the server stops being broken and failing to respond.

**Comment by TheRyuu** [comment]
Yea that fixed it, seems to work now.

**Comment by Mxywes** [comment]
It seems to be the same issue again:
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-J', '--format', 'High', '--ignore-config', '-u', 'PRIVATE', '-p', 'PRIVATE', '--verbose', '--all-subs', 'http://www.twitch.tv/zerator/v/115838658']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.01.29
[debug] Python version 3.4.4 - Windows-10-10.0.10586
[debug] exe versions: ffmpeg N-82324-g872b358, ffprobe N-82324-g872b358, rtmpdump 2.3
[debug] Proxy map: {}
ERROR: Unable to login. Twitch said: Please complete the CAPTCHA correctly.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\common.py", line 416, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\YoutubeDL.py", line 2001, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
urllib.error.HTTPError: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\twitch.py", line 96, in _login
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\common.py", line 561, in _download_json
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\common.py", line 529, in _download_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\common.py", line 436, in _download_webpage_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\common.py", line 425, in _request_webpage
youtube_dl.utils.ExtractorError: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\common.py", line 416, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\YoutubeDL.py", line 2001, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
urllib.error.HTTPError: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\twitch.py", line 96, in _login
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\common.py", line 561, in _download_json
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\common.py", line 529, in _download_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\common.py", line 436, in _download_webpage_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\common.py", line 425, in _request_webpage
youtube_dl.utils.ExtractorError: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\YoutubeDL.py", line 694, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\common.py", line 368, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\common.py", line 362, in initialize
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\twitch.py", line 56, in _real_initialize
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\twitch.py", line 101, in _login
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\twitch.py", line 65, in fail
youtube_dl.utils.ExtractorError: Unable to login. Twitch said: Please complete the CAPTCHA correctly.
```
I have the latest version. I can provide IDs if you want to try because you need premium for this VOD.

**Comment by dstftw** [comment]
That's not an issue. You have to do what error message asks you to do and pass cookies to youtube-dl.
