### ISSUE TITLE
Unable to extract title, youtube-dl version 2016.08.22

### ISSUE THREAD

**Issue by RoboTehnik** [rg3/youtube-dl#10413]
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-f', 'mp4', '--verbose', '--batch-file', 'youtube-dl.lst']
[debug] Batch file urls: ['https://www.youtube.com/watch?v=7BjTh-PhL4c&list=WL&index=1']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.08.22
[debug] Python version 3.4.4 - Windows-XP-5.1.2600-SP3
[debug] exe versions: none
[debug] Proxy map: {}
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6u7yql_3\build\youtube_dl\YoutubeDL.py", line 691, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6u7yql_3\build\youtube_dl\extractor\common.py", line 347, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6u7yql_3\build\youtube_dl\extractor\youtube.py", line 2333, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6u7yql_3\build\youtube_dl\extractor\youtube.py", line 1922, in _extract_playlist
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6u7yql_3\build\youtube_dl\extractor\common.py", line 659, in _html_search_regex
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6u7yql_3\build\youtube_dl\extractor\common.py", line 650, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
https://www.youtube.com/watch?v=7BjTh-PhL4c&list=WL&index=1 is either a playlist (watchlater) or a video (7BjTh-PhL4c). By default such cases are handled as a playlist thus you must provide account credentials with `-u/-p` or .netrc `-n` for watchlater playlist. For downloading 7BjTh-PhL4c video with this URL `--no-playlist` must be passed.

**Comment by RoboTehnik** [comment]
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '-f', 'mp4', '--username', 'PRIVATE', '--password', 'PRIVATE', 'http://www.youtube.com/playlist?list=WL']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.08.22
[debug] Python version 3.4.4 - Windows-XP-5.1.2600-SP3
[debug] exe versions: none
[debug] Proxy map: {}
WARNING: unable to log in: bad username or password
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6u7yql_3\build\youtube_dl\YoutubeDL.py", line 691, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6u7yql_3\build\youtube_dl\extractor\common.py", line 347, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6u7yql_3\build\youtube_dl\extractor\youtube.py", line 2333, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6u7yql_3\build\youtube_dl\extractor\youtube.py", line 1922, in _extract_playlist
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6u7yql_3\build\youtube_dl\extractor\common.py", line 659, in _html_search_regex
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6u7yql_3\build\youtube_dl\extractor\common.py", line 650, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by yan12125** [comment]
You need to put URLs in double quotes. See https://github.com/rg3/youtube-dl/blob/master/README.md#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command

**Comment by benklaasen** [comment]
I got this error while using `2016.08.24.1` by inadvertently adding an extra character to the playlist identifier. Read the arguments to youtube-dl again carefully.
