### ISSUE TITLE
Site request: abc.go.com

### ISSUE THREAD

**Issue by StevenDTX** [rg3/youtube-dl#10439]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.08.24.1*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.08.24.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [X] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```

E:\>youtube-dl --verbose "http://abc.go.com/shows/modern-family/episode-guide/season-07/16-the-coverup"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://abc.go.com/shows/modern-family/episode-guide/season-07/16-the-coverup']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.08.24
[debug] Python version 3.4.4 - Windows-10-10.0.10586
[debug] exe versions: ffmpeg N-72383-g7206b94, ffprobe N-72383-g7206b94, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 16-the-coverup: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 16-the-coverup: Downloading webpage
[generic] 16-the-coverup: Extracting information
ERROR: Unsupported URL: http://abc.go.com/shows/modern-family/episode-guide/season-07/16-the-coverup
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp3vpw27pc\build\youtube_dl\YoutubeDL.py", line 691, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp3vpw27pc\build\youtube_dl\extractor\common.py", line 347, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp3vpw27pc\build\youtube_dl\extractor\generic.py", line 2377, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: http://abc.go.com/shows/modern-family/episode-guide/season-07/16-the-coverup


E:\>youtube-dl --verbose "http://abc.go.com/shows/modern-family/episode-guide/season-07/16-the-coverup" --cookies e:\cookies-ABC.txt
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://abc.go.com/shows/modern-family/episode-guide/season-07/16-the-coverup', '--cookies', 'e:\\cookies-ABC.txt']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.08.24
[debug] Python version 3.4.4 - Windows-10-10.0.10586
[debug] exe versions: ffmpeg N-72383-g7206b94, ffprobe N-72383-g7206b94, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 16-the-coverup: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 16-the-coverup: Downloading webpage
[generic] 16-the-coverup: Extracting information
ERROR: Unsupported URL: http://abc.go.com/shows/modern-family/episode-guide/season-07/16-the-coverup
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp3vpw27pc\build\youtube_dl\YoutubeDL.py", line 691, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp3vpw27pc\build\youtube_dl\extractor\common.py", line 347, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp3vpw27pc\build\youtube_dl\extractor\generic.py", line 2377, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: http://abc.go.com/shows/modern-family/episode-guide/season-07/16-the-coverup


E:\>youtube-dl --verbose "http://abc.go.com/shows/modern-family/episode-guide/season-07/16-the-coverup" --netrc
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://abc.go.com/shows/modern-family/episode-guide/season-07/16-the-coverup', '--netrc']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.08.24
[debug] Python version 3.4.4 - Windows-10-10.0.10586
[debug] exe versions: ffmpeg N-72383-g7206b94, ffprobe N-72383-g7206b94, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 16-the-coverup: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 16-the-coverup: Downloading webpage
[generic] 16-the-coverup: Extracting information
ERROR: Unsupported URL: http://abc.go.com/shows/modern-family/episode-guide/season-07/16-the-coverup
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp3vpw27pc\build\youtube_dl\YoutubeDL.py", line 691, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp3vpw27pc\build\youtube_dl\extractor\common.py", line 347, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp3vpw27pc\build\youtube_dl\extractor\generic.py", line 2377, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: http://abc.go.com/shows/modern-family/episode-guide/season-07/16-the-coverup


E:\>youtube-dl "http://content-ause3.uplynk.com/cadf06a2ebe8468c8e2a2cd825310531/j.m3u8?exp=1472138180&ct=a&oid=d874124ecca24c88a3c9575e78686acf&eid=10060007&iph=913aea843f9e429756bbab8b2a72fa7715a19966d23164bd3de49b0f74e94eb1&rays=jihgfedcb&euid=54B504BD-73FE-4241-BFDC-6A686417D955_013_0_001_lf&cdn=ec&stgcfg=datg&pp2ip=0&sig=e03c51431fb1f9c9f36626e50b1d326e8a9964bcdb3686f922101cecc26a1c19&ad.cping=1&pbs=0af75beb1c4545af9f820c16138c61b1"
[generic] j.m3u8?exp=1472138180&ct=a&oid=d874124ecca24c88a3c9575e78686acf&eid=10060007&iph=913aea843f9e429756bbab8b2a72fa7715a19966d23164bd3de49b0f74e94eb1&rays=jihgfedcb&euid=54B504BD-73FE-4241-BFDC-6A686417D955_013_0_001_lf&cdn=ec&stgcfg=datg&pp2ip=0&sig=e03c51431fb1f9c9f36626e50b1d326e8a9964bcdb3686f922101cecc26a1c19&ad: Requesting header
[generic] j.m3u8?exp=1472138180&ct=a&oid=d874124ecca24c88a3c9575e78686acf&eid=10060007&iph=913aea843f9e429756bbab8b2a72fa7715a19966d23164bd3de49b0f74e94eb1&rays=jihgfedcb&euid=54B504BD-73FE-4241-BFDC-6A686417D955_013_0_001_lf&cdn=ec&stgcfg=datg&pp2ip=0&sig=e03c51431fb1f9c9f36626e50b1d326e8a9964bcdb3686f922101cecc26a1c19&ad: Downloading m3u8 information
[download] Destination: j-j.m3u8exp=1472138180&ct=a&oid=d874124ecca24c88a3c9575e78686acf&eid=10060007&iph=913aea843f9e429756bbab8b2a72fa7715a19966d23164bd3de49b0f74e94eb1&rays=jihgfedcb&euid=54B504BD-73FE-4241-BFDC-6A686417D955_013_0_001_lf&cdn=ec&stgcfg=datg&pp2ip=0&sig=e03c51431fb1f9c9f36626e50b1d326e8a9964bcdb3686f922101cecc26a1c19&ad.mp4
ffmpeg version N-72383-g7206b94 Copyright (c) 2000-2015 the FFmpeg developers
  built with gcc 4.9.2 (GCC)
  configuration: --enable-gpl --enable-version3 --disable-w32threads --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libdcadec --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmfx --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-aacenc --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-lzma --enable-decklink --enable-zlib
  libavutil      54. 26.100 / 54. 26.100
  libavcodec     56. 41.100 / 56. 41.100
  libavformat    56. 33.101 / 56. 33.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 16.101 /  5. 16.101
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  1.100 /  1.  1.100
  libpostproc    53.  3.100 / 53.  3.100
[https @ 0000000005215a60] HTTP error 404 Not Found
Unable to open key file https://content-ause3.uplynk.com/check2?b=cadf06a2ebe8468c8e2a2cd825310531&v=cadf06a2ebe8468c8e2a2cd825310531&r=j&pbs=0af75beb1c4545af9f820c16138c61b1
[hls,applehttp @ 00000000051a72a0] Error when loading first segment 'http://x-disney-datg-stgec.uplynk.com/ncal/slices/cad/d874124ecca24c88a3c9575e78686acf/cadf06a2ebe8468c8e2a2cd825310531/J00000000.ts?pbs=0af75beb1c4545af9f820c16138c61b1&euid=54B504BD-73FE-4241-BFDC-6A686417D955_013_0_001_lf&si=0'
http://content-ause3.uplynk.com/cadf06a2ebe8468c8e2a2cd825310531/j.m3u8?exp=1472138180&ct=a&oid=d874124ecca24c88a3c9575e78686acf&eid=10060007&iph=913aea843f9e429756bbab8b2a72fa7715a19966d23164bd3de49b0f74e94eb1&rays=jihgfedcb&euid=54B504BD-73FE-4241-BFDC-6A686417D955_013_0_001_lf&cdn=ec&stgcfg=datg&pp2ip=0&sig=e03c51431fb1f9c9f36626e50b1d326e8a9964bcdb3686f922101cecc26a1c19&ad.cping=1&pbs=0af75beb1c4545af9f820c16138c61b1: Invalid data found when processing input


ERROR: ffmpeg exited with code 1

E:\>youtube-dl "http://content-ause3.uplynk.com/cadf06a2ebe8468c8e2a2cd825310531/j.m3u8?exp=1472138180&ct=a&oid=d874124ecca24c88a3c9575e78686acf&eid=10060007&iph=913aea843f9e429756bbab8b2a72fa7715a19966d23164bd3de49b0f74e94eb1&rays=jihgfedcb&euid=54B504BD-73FE-4241-BFDC-6A686417D955_013_0_001_lf&cdn=ec&stgcfg=datg&pp2ip=0&sig=e03c51431fb1f9c9f36626e50b1d326e8a9964bcdb3686f922101cecc26a1c19&ad.cping=1&pbs=0af75beb1c4545af9f820c16138c61b1" --cookies e:\cookies-ABC.txt
[generic] j.m3u8?exp=1472138180&ct=a&oid=d874124ecca24c88a3c9575e78686acf&eid=10060007&iph=913aea843f9e429756bbab8b2a72fa7715a19966d23164bd3de49b0f74e94eb1&rays=jihgfedcb&euid=54B504BD-73FE-4241-BFDC-6A686417D955_013_0_001_lf&cdn=ec&stgcfg=datg&pp2ip=0&sig=e03c51431fb1f9c9f36626e50b1d326e8a9964bcdb3686f922101cecc26a1c19&ad: Requesting header
[generic] j.m3u8?exp=1472138180&ct=a&oid=d874124ecca24c88a3c9575e78686acf&eid=10060007&iph=913aea843f9e429756bbab8b2a72fa7715a19966d23164bd3de49b0f74e94eb1&rays=jihgfedcb&euid=54B504BD-73FE-4241-BFDC-6A686417D955_013_0_001_lf&cdn=ec&stgcfg=datg&pp2ip=0&sig=e03c51431fb1f9c9f36626e50b1d326e8a9964bcdb3686f922101cecc26a1c19&ad: Downloading m3u8 information
[download] Destination: j-j.m3u8exp=1472138180&ct=a&oid=d874124ecca24c88a3c9575e78686acf&eid=10060007&iph=913aea843f9e429756bbab8b2a72fa7715a19966d23164bd3de49b0f74e94eb1&rays=jihgfedcb&euid=54B504BD-73FE-4241-BFDC-6A686417D955_013_0_001_lf&cdn=ec&stgcfg=datg&pp2ip=0&sig=e03c51431fb1f9c9f36626e50b1d326e8a9964bcdb3686f922101cecc26a1c19&ad.mp4
ffmpeg version N-72383-g7206b94 Copyright (c) 2000-2015 the FFmpeg developers
  built with gcc 4.9.2 (GCC)
  configuration: --enable-gpl --enable-version3 --disable-w32threads --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libdcadec --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmfx --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-aacenc --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-lzma --enable-decklink --enable-zlib
  libavutil      54. 26.100 / 54. 26.100
  libavcodec     56. 41.100 / 56. 41.100
  libavformat    56. 33.101 / 56. 33.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 16.101 /  5. 16.101
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  1.100 /  1.  1.100
  libpostproc    53.  3.100 / 53.  3.100
[https @ 00000000051c5a60] HTTP error 404 Not Found
Unable to open key file https://content-ause3.uplynk.com/check2?b=cadf06a2ebe8468c8e2a2cd825310531&v=cadf06a2ebe8468c8e2a2cd825310531&r=j&pbs=0af75beb1c4545af9f820c16138c61b1
[hls,applehttp @ 00000000051572a0] Error when loading first segment 'http://x-disney-datg-stgec.uplynk.com/ncal/slices/cad/d874124ecca24c88a3c9575e78686acf/cadf06a2ebe8468c8e2a2cd825310531/J00000000.ts?pbs=0af75beb1c4545af9f820c16138c61b1&euid=54B504BD-73FE-4241-BFDC-6A686417D955_013_0_001_lf&si=0'
http://content-ause3.uplynk.com/cadf06a2ebe8468c8e2a2cd825310531/j.m3u8?exp=1472138180&ct=a&oid=d874124ecca24c88a3c9575e78686acf&eid=10060007&iph=913aea843f9e429756bbab8b2a72fa7715a19966d23164bd3de49b0f74e94eb1&rays=jihgfedcb&euid=54B504BD-73FE-4241-BFDC-6A686417D955_013_0_001_lf&cdn=ec&stgcfg=datg&pp2ip=0&sig=e03c51431fb1f9c9f36626e50b1d326e8a9964bcdb3686f922101cecc26a1c19&ad.cping=1&pbs=0af75beb1c4545af9f820c16138c61b1: Invalid data found when processing input


ERROR: ffmpeg exited with code 1

E:\>youtube-dl "http://content-ause3.uplynk.com/cadf06a2ebe8468c8e2a2cd825310531/j.m3u8?exp=1472138180&ct=a&oid=d874124ecca24c88a3c9575e78686acf&eid=10060007&iph=913aea843f9e429756bbab8b2a72fa7715a19966d23164bd3de49b0f74e94eb1&rays=jihgfedcb&euid=54B504BD-73FE-4241-BFDC-6A686417D955_013_0_001_lf&cdn=ec&stgcfg=datg&pp2ip=0&sig=e03c51431fb1f9c9f36626e50b1d326e8a9964bcdb3686f922101cecc26a1c19&ad.cping=1&pbs=0af75beb1c4545af9f820c16138c61b1" --netrc
[generic] j.m3u8?exp=1472138180&ct=a&oid=d874124ecca24c88a3c9575e78686acf&eid=10060007&iph=913aea843f9e429756bbab8b2a72fa7715a19966d23164bd3de49b0f74e94eb1&rays=jihgfedcb&euid=54B504BD-73FE-4241-BFDC-6A686417D955_013_0_001_lf&cdn=ec&stgcfg=datg&pp2ip=0&sig=e03c51431fb1f9c9f36626e50b1d326e8a9964bcdb3686f922101cecc26a1c19&ad: Requesting header
[generic] j.m3u8?exp=1472138180&ct=a&oid=d874124ecca24c88a3c9575e78686acf&eid=10060007&iph=913aea843f9e429756bbab8b2a72fa7715a19966d23164bd3de49b0f74e94eb1&rays=jihgfedcb&euid=54B504BD-73FE-4241-BFDC-6A686417D955_013_0_001_lf&cdn=ec&stgcfg=datg&pp2ip=0&sig=e03c51431fb1f9c9f36626e50b1d326e8a9964bcdb3686f922101cecc26a1c19&ad: Downloading m3u8 information
[download] Destination: j-j.m3u8exp=1472138180&ct=a&oid=d874124ecca24c88a3c9575e78686acf&eid=10060007&iph=913aea843f9e429756bbab8b2a72fa7715a19966d23164bd3de49b0f74e94eb1&rays=jihgfedcb&euid=54B504BD-73FE-4241-BFDC-6A686417D955_013_0_001_lf&cdn=ec&stgcfg=datg&pp2ip=0&sig=e03c51431fb1f9c9f36626e50b1d326e8a9964bcdb3686f922101cecc26a1c19&ad.mp4
ffmpeg version N-72383-g7206b94 Copyright (c) 2000-2015 the FFmpeg developers
  built with gcc 4.9.2 (GCC)
  configuration: --enable-gpl --enable-version3 --disable-w32threads --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libdcadec --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmfx --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-aacenc --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-lzma --enable-decklink --enable-zlib
  libavutil      54. 26.100 / 54. 26.100
  libavcodec     56. 41.100 / 56. 41.100
  libavformat    56. 33.101 / 56. 33.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 16.101 /  5. 16.101
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  1.100 /  1.  1.100
  libpostproc    53.  3.100 / 53.  3.100
[https @ 00000000052c5a60] HTTP error 404 Not Found
Unable to open key file https://content-ause3.uplynk.com/check2?b=cadf06a2ebe8468c8e2a2cd825310531&v=cadf06a2ebe8468c8e2a2cd825310531&r=j&pbs=0af75beb1c4545af9f820c16138c61b1
[hls,applehttp @ 00000000052572a0] Error when loading first segment 'http://x-disney-datg-stgec.uplynk.com/ncal/slices/cad/d874124ecca24c88a3c9575e78686acf/cadf06a2ebe8468c8e2a2cd825310531/J00000000.ts?pbs=0af75beb1c4545af9f820c16138c61b1&euid=54B504BD-73FE-4241-BFDC-6A686417D955_013_0_001_lf&si=0'
http://content-ause3.uplynk.com/cadf06a2ebe8468c8e2a2cd825310531/j.m3u8?exp=1472138180&ct=a&oid=d874124ecca24c88a3c9575e78686acf&eid=10060007&iph=913aea843f9e429756bbab8b2a72fa7715a19966d23164bd3de49b0f74e94eb1&rays=jihgfedcb&euid=54B504BD-73FE-4241-BFDC-6A686417D955_013_0_001_lf&cdn=ec&stgcfg=datg&pp2ip=0&sig=e03c51431fb1f9c9f36626e50b1d326e8a9964bcdb3686f922101cecc26a1c19&ad.cping=1&pbs=0af75beb1c4545af9f820c16138c61b1: Invalid data found when processing input


ERROR: ffmpeg exited with code 1

E:\>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://abc.go.com/shows/modern-family/episode-guide/season-07/16-the-coverup

---

### Description of your *issue*, suggested solution and other information

I have a DirecTV login. I have tried using both --netrc and --cookies, both with no success.  I tried a m3u8 URL that I captured with URL Snooper, and I received a key file error.

Using adownloader, I get a list of m3u8 URLs, but again, get a key error.  This, specifically, is the URL I'm interested in: http://content-ause1.uplynk.com/cadf06a2ebe8468c8e2a2cd825310531/k.m3u8. Its the 1080p playlist.

Thanks.

**Comment by StevenDTX** [comment]
Bump!

**Comment by remitamine** [comment]
the problem with the go websites is that for full episodes it requires an auth token, and trying to obtain the auth token i get this message from the API while using multiple public US VPN services:
> You appear to be outside the United States or its territories. Due to international rights agreements, we only offer this video to viewers located within the United States and its territories.

**Comment by StevenDTX** [comment]
Thanks, @remitamine.  Is there something more I can do to help?  Do more testing? Provide a temporary Teamviewer session?

I would love to work on an extractor myself, but I just do not have the coding abilities.

**Comment by remitamine** [comment]
if post the output of this command(requires curl):
```
curl --data 'brand=008&device=001&video_id=VDKA0_o5ho9vtb&video_type=lf' https://api.entitlement.watchabc.go.com/vp2/ws-secure/entitlement/2020/authorize.json
```

**Comment by StevenDTX** [comment]
```
E:\>c:\support\curl\bin\curl.exe --data "brand=008&device=001&video_id=VDKA0_o5ho9vtb&video_type=lf" https://api.entitlement.watchabc.go.com/vp2/ws-secure/entitlement/2020/authorize.json
{"date":1473855376901,"uplynkData":{"sessionKey":"exp=1473855676&ct=a&oid=21885d134fa441488df8e1d7acee8c66&eid=10056474&iph=d6f86aa9c907b9fd9e516da8fededd6f334288018690a5fb7968b452b27fa498&rays=jihgfedcb&euid=5036212C-86FE-4971-84D8-AA33997378DE_000_0_001_lf_04-06-00_NA&cdn=ec&stgcfg=datg&pp2ip=0&sig=d937e44252db58a8aa5c32d6a3df6f4c8bbe6e296c72165dfe58499a4682ff69"},"entitlementData":{"build":"12232","device":"001","brand":"008","ipaddress":"10.236.229.105","xff":"173.71.xxx.xxx"}}

```

**Comment by remitamine** [comment]
so it's working for you, i will try make a change to add support for free episodes as first step.

**Comment by StevenDTX** [comment]
Thank you.  Here is a full episode that is available with no sign in required.

http://abc.go.com/shows/speechless/episode-guide/season-01/1-series-premiere-p-i-pilot

**Comment by remitamine** [comment]
when a new version released, try to check if it's working.

**Comment by StevenDTX** [comment]
Thanks! I will try it out.

**Comment by StevenDTX** [comment]
Thanks a lot, @remitamine!  It works for both the free and login-required videos.

**Comment by StevenDTX** [comment]
@krind24 

I just now saw your note.  I never got it to work.  I tried several methods.  I did open a new issue.

https://github.com/rg3/youtube-dl/issues/10831
