### ISSUE TITLE
ParseError: mismatched tag with generic downloader on insider.foxnews

### ISSUE THREAD

**Issue by neopunisher** [rg3/youtube-dl#10445]
### Due diligence 

- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.08.24.1**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)

### Verbose Output
```
carter@carterdesk:~$ youtube-dl http://insider.foxnews.com/2016/08/25/univ-wisconsin-student-group-pushing-silence-certain-words
[generic] univ-wisconsin-student-group-pushing-silence-certain-words: Requesting header
WARNING: Falling back on generic information extractor.
[generic] univ-wisconsin-student-group-pushing-silence-certain-words: Downloading webpage
[generic] univ-wisconsin-student-group-pushing-silence-certain-words: Extracting information
ERROR: Unsupported URL: http://insider.foxnews.com/2016/08/25/univ-wisconsin-student-group-pushing-silence-certain-words
carter@carterdesk:~$ youtube-dl  --verbose http://insider.foxnews.com/2016/08/25/univ-wisconsin-student-group-pushing-silence-certain-words
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://insider.foxnews.com/2016/08/25/univ-wisconsin-student-group-pushing-silence-certain-words']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.08.24.1
[debug] Python version 2.7.6 - Linux-3.19.0-66-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.18-6, avprobe 9.18-6, rtmpdump 2.4
[debug] Proxy map: {}
[generic] univ-wisconsin-student-group-pushing-silence-certain-words: Requesting header
WARNING: Falling back on generic information extractor.
[generic] univ-wisconsin-student-group-pushing-silence-certain-words: Downloading webpage
[generic] univ-wisconsin-student-group-pushing-silence-certain-words: Extracting information
ERROR: Unsupported URL: http://insider.foxnews.com/2016/08/25/univ-wisconsin-student-group-pushing-silence-certain-words
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1633, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2525, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2514, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: mismatched tag: line 115, column 2
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 691, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 347, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2377, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://insider.foxnews.com/2016/08/25/univ-wisconsin-student-group-pushing-silence-certain-words
```
### Description of your *issue*, suggested solution and other information

```
url: http://insider.foxnews.com/2016/08/25/univ-wisconsin-student-group-pushing-silence-certain-words
domain: insider.foxnews.com
```

Im not sure if foxnews is supposed to use a specific downloader but in the tests i see the ```video.foxnews.com``` domain but my url is from ```insider.foxnews.com``` and defaults to the generic downloader. Looks like some parse error with malformed html ```ParseError: mismatched tag: line 115, column 2``` I bet some closing tag is missing in their html

**Comment by yan12125** [comment]
insider.foxnews.com was not supported. I've added it and it will be available in the next version.
