### ISSUE TITLE
Failing with "ValueError: insecure string pickle"

### ISSUE THREAD

**Issue by kamalsomani** [rg3/youtube-dl#10440]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.08.24.1*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ *] I've **verified** and **I assure** that I'm running youtube-dl **2016.08.24.1**

### Before submitting an *issue* make sure you have:
- [* ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [* ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ *] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v https://www.youtube.com/playlist?list=PLillGF-RfqbbZnAJlEzttBrbkAO27U_hd
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/playlist?list=PLillGF-RfqbbZnAJlEzttBrbkAO27U_hd']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.08.24.1
[debug] Python version 2.7.10 - Darwin-15.6.0-x86_64-i386-64bit
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "../youtube-dl/youtube-dl_20160821/__main__.py", line 19, in <module>
  File "../youtube-dl/youtube-dl_20160821/youtube_dl/__init__.py", line 433, in main
  File "../youtube-dl/youtube-dl_20160821/youtube_dl/__init__.py", line 400, in _real_main
  File "../youtube-dl/youtube-dl_20160821/youtube_dl/YoutubeDL.py", line 367, in __init__
  File "../youtube-dl/youtube-dl_20160821/youtube_dl/YoutubeDL.py", line 2037, in print_debug_header
  File "../youtube-dl/youtube-dl_20160821/youtube_dl/postprocessor/ffmpeg.py", line 64, in get_versions
  File "../youtube-dl/youtube-dl_20160821/youtube_dl/postprocessor/ffmpeg.py", line 48, in __init__
  File "../youtube-dl/youtube-dl_20160821/youtube_dl/postprocessor/ffmpeg.py", line 105, in _determine_executables
  File "../youtube-dl/youtube-dl_20160821/youtube_dl/postprocessor/ffmpeg.py", line 105, in <genexpr>
  File "../youtube-dl/youtube-dl_20160821/youtube_dl/utils.py", line 1789, in get_exe_version
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1334, in _execute_child
    child_exception = pickle.loads(data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 1382, in loads
    return Unpickler(file).load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 966, in load_string
    raise ValueError, "insecure string pickle"
ValueError: insecure string pickle

```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* required an account credentials please provide them or explain how one can obtain them.

**Comment by dstftw** [comment]
Update python to 2.7.12.

**Comment by kamalsomani** [comment]
I am not sure, what changed everything was working fine till yesterday evening..
I also tried  v2016.08.22 , but that too failing today.

any guess, why the older version also not working ?
