### ISSUE TITLE
[youtube] Unable to use an app password to login

### ISSUE THREAD

**Issue by Starsam80** [rg3/youtube-dl#10484]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.08.28**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Bug report (encountered problems with youtube-dl)
- [x] Feature request (request for a new functionality)

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['https://www.youtube.com/playlist?list=WL', '--verbose', '--username', 'PRIVATE', '--password', 'PRIVATE']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.08.28
[debug] Git HEAD: b8079a4
[debug] Python version 3.5.2 - Linux-4.7.2-1-ARCH-x86_64-with-arch-Arch-Linux
[debug] exe versions: ffmpeg 3.1.2, ffprobe 3.1.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:watchlater] Downloading login page
[youtube:watchlater] Logging in
ERROR: Unable to login: The email and password you entered don't match.
Traceback (most recent call last):
  File "/home/starsam80/.local/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 691, in extract_info
    ie_result = ie.extract(url)
  File "/home/starsam80/.local/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 346, in extract
    self.initialize()
  File "/home/starsam80/.local/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 340, in initialize
    self._real_initialize()
  File "/home/starsam80/.local/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1847, in _real_initialize
    self._login()
  File "/home/starsam80/.local/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 113, in _login
    raise ExtractorError('Unable to login: %s' % error_msg, expected=True)
youtube_dl.utils.ExtractorError: Unable to login: The email and password you entered don't match.
```

I am unable to use an app password with youtube-dl. App passwords allow programs to use an account without requiring their actual password or a 2 factor auth code, but it seems this doesn't work with youtube-dl. You can see/create an app password here: https://security.google.com/settings/security/apppasswords

**Comment by Starsam80** [comment]
Whoops, I guess my search for "app password" didn't pick up "app passwd", so this is a duplicate. Sorry.
