### ISSUE TITLE
Site Support: eonline.com

### ISSUE THREAD

**Issue by StevenDTX** [rg3/youtube-dl#10528]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.08.31*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2016.08.31**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [X] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
E:\>youtube-dl --verbose --netrc "http://www.eonline.com/now/famously-single/full-episode/do-you-trust-me/717540931533"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '--netrc', 'http://www.eonline.com/now/famously-single/full-episode/do-you-trust-me/717540931533']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.08.31
[debug] Python version 3.4.4 - Windows-10-10.0.10586
[debug] exe versions: ffmpeg N-72383-g7206b94, ffprobe N-72383-g7206b94, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 717540931533: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 717540931533: Downloading webpage
[generic] 717540931533: Extracting information
ERROR: Unsupported URL: http://www.eonline.com/now/famously-single/full-episode/do-you-trust-me/717540931533
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6cf1z6ka\build\youtube_dl\YoutubeDL.py", line 691, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6cf1z6ka\build\youtube_dl\extractor\common.py", line 347, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6cf1z6ka\build\youtube_dl\extractor\generic.py", line 2388, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.eonline.com/now/famously-single/full-episode/do-you-trust-me/717540931533
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://www.eonline.com/now/famously-single/full-episode/do-you-trust-me/717540931533

---

### Description of your *issue*, suggested solution and other information

This should be similar to BravoTV.

**Comment by StevenDTX** [comment]
Duplicate of #6198
