### ISSUE TITLE
[tf1] / LCI.fr: Site support request or extending [tf1]

### ISSUE THREAD

**Issue by fenollp** [rg3/youtube-dl#10573]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.09.04.1*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.09.04.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

###  the purpose of this *issue* is a *site support request*

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
youtube-dl -v 'http://www.lci.fr/economie/la-france-de-demain-une-social-valley-1208898.html'
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.lci.fr/economie/la-france-de-demain-une-social-valley-1208898.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.09.04.1
[debug] Python version 2.7.12 - Linux-4.4.0-36-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 2.8.6-1ubuntu2, avprobe 2.8.6-1ubuntu2, ffmpeg 2.8.6-1ubuntu2, ffprobe 2.8.6-1ubuntu2, rtmpdump 2.4
[debug] Proxy map: {}
[generic] la-france-de-demain-une-social-valley-1208898: Requesting header
WARNING: Falling back on generic information extractor.
[generic] la-france-de-demain-une-social-valley-1208898: Downloading webpage
[generic] la-france-de-demain-une-social-valley-1208898: Extracting information
[debug] Invoking downloader on u'/economie/la-france-de-demain-une-social-valley-1208898.html'
Traceback (most recent call last):
  File "/usr/bin/youtube-dl", line 6, in <module>
    youtube_dl.main()
  File "/usr/lib/python2.7/dist-packages/youtube_dl/__init__.py", line 434, in main
    _real_main(argv)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/__init__.py", line 424, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1788, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 702, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 748, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1432, in process_video_result
    self.process_info(new_info)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1696, in process_info
    success = dl(filename, info_dict)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1638, in dl
    return fd.download(name, info)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/downloader/common.py", line 354, in download
    return self.real_download(filename, info_dict)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/downloader/http.py", line 58, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1998, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 421, in open
    protocol = req.get_type()
  File "/usr/lib/python2.7/urllib2.py", line 283, in get_type
    raise ValueError, "unknown url type: %s" % self.__original
ValueError: unknown url type: /economie/la-france-de-demain-une-social-valley-1208898.html
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://www.lci.fr/economie/la-france-de-demain-une-social-valley-1208898.html
- Single video: http://www.lci.fr/emissions/la-meteo-du-6-septembre-2016-2001724.html

---

### Description of your *issue*, suggested solution and other information

I was creating this issue for site support of LCI.fr but it appears [tf1] has a sub TLD for LCI and should be handled. However download fails (with an ugly error).

**Comment by fenollp** [comment]
Actually I got an error while muxing:

```
youtube-dl -v 'http://www.lci.fr/economie/la-france-de-demain-une-social-valley-1208898.html'
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.lci.fr/economie/la-france-de-demain-une-social-valley-1208898.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.09.08
[debug] Python version 2.7.12 - Darwin-15.6.0-x86_64-i386-64bit
[debug] exe versions: avconv 11.4, avprobe 11.4, ffmpeg 3.1.3, ffprobe 3.1.3, rtmpdump 2.4
[debug] Proxy map: {}
[LCI] 1208898: Downloading webpage
[wat.tv] 12617669: Downloading JSON metadata
[wat.tv] 12617669: Downloading JSON metadata
[wat.tv] 12617669: Downloading m3u8 information
[wat.tv] 12617669: Downloading f4m manifest
[wat.tv] 12617669: Extracting http url
[wat.tv] 12617669: Checking http-280 URL
[wat.tv] 12617669: Checking http-493 URL
[wat.tv] 12617669: Checking http-705 URL
[wat.tv] 12617669: Checking http-1341 URL
[wat.tv] 12617669: Checking http-1977 URL
[wat.tv] 12617669: Checking http-2719 URL
[wat.tv] 12617669: Downloading MPD manifest
[debug] Invoking downloader on u'http://das.q1.tf1.fr/2/USP-0x0/76/69/12617669/ssm/12617669.ism/dash/'
[download] La France de demain - une 'Social Valley' -12617669.fdash-video=2500592.mp4 has already been downloaded
[download] 100% of 254.81MiB
[debug] Invoking downloader on u'http://ios.q1.tf1.fr/2/USP-0x0/76/69/12617669/ssm/12617669.ism/12617669-audio=64000.m3u8?vk=MTI2MTc2NjkubTN1OA==&st=OmWG5W-FYnw8_bCKbak4yA&e=1473622354&t=1473611554&'
[download] La France de demain - une 'Social Valley' -12617669.fhls-68.mp4 has already been downloaded
[download] 100% of 7.38MiB
[ffmpeg] Merging formats into "La France de demain - une 'Social Valley' -12617669.mp4"
[debug] ffmpeg command line: avconv -y -i 'file:La France de demain - une '"'"'Social Valley'"'"' -12617669.fdash-video=2500592.mp4' -i 'file:La France de demain - une '"'"'Social Valley'"'"' -12617669.fhls-68.mp4' -c copy -map 0:v:0 -map 1:a:0 'file:La France de demain - une '"'"'Social Valley'"'"' -12617669.temp.mp4'
ERROR: av_interleaved_write_frame(): Invalid argument
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1834, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 445, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 168, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
FFmpegPostProcessorError
```
