### ISSUE TITLE
[Daylimotion] ERROR: requested format not available

### ISSUE THREAD

**Issue by Poilaucul** [rg3/youtube-dl#10575]
### What is the purpose of your *issue*?
- [X ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

```
C:\Users\_A.T.Omix_>Updated youtube-dl to version 2016.09.04.1.
youtube-dl --version
2016.09.04.1

C:\Users\_A.T.Omix_>youtube-dl -v http://www.dailymotion.com/video/x4n2hqy_l-exploration-d-une-maison-abandonnee-en-pleine-montagne-tourne-mal_fun
[debug] System config: []
[debug] User config: ['-u', 'PRIVATE', '-p', 'PRIVATE', '--cache-dir', 'F://Temporaire//YouTube', '--format', 'bestvideo+bestaudio', '--ffmpeg-location', 'C://Program Files//FFmpeg//bin//ffmpeg.exe', '--mark-watched', '--external-downloader', 'aria2c.exe', '--external-downloader-args', '-x10', '-o', 'F://Temporaire//MPV//%(title)s.%(ext)s']
[debug] Command-line args: ['-v', 'http://www.dailymotion.com/video/x4n2hqy_l-exploration-d-une-maison-abandonnee-en-pleine-montagne-tourne-mal_fun']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.09.04.1
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-80999-gf41e37b, ffprobe N-80999-gf41e37b
[debug] Proxy map: {}
[dailymotion] x4n2hqy: Downloading webpage
[dailymotion] x4n2hqy: Downloading m3u8 information
ERROR: requested format not available
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptom439wb\build\youtube_dl\YoutubeDL.py", line 702, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptom439wb\build\youtube_dl\YoutubeDL.py", line 748, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptom439wb\build\youtube_dl\YoutubeDL.py", line 1424, in process_video_result
youtube_dl.utils.ExtractorError: requested format not available


C:\Users\_A.T.Omix_>youtube-dl -v http://www.dailymotion.com/video/x4s3muc_huawei-nova-prise-en-main-video_tech
[debug] System config: []
[debug] User config: ['-u', 'PRIVATE', '-p', 'PRIVATE', '--cache-dir', 'F://Temporaire//YouTube', '--format', 'bestvideo+bestaudio', '--ffmpeg-location', 'C://Program Files//FFmpeg//bin//ffmpeg.exe', '--mark-watched', '--external-downloader', 'aria2c.exe', '--external-downloader-args', '-x10', '-o', 'F://Temporaire//MPV//%(title)s.%(ext)s']
[debug] Command-line args: ['-v', 'http://www.dailymotion.com/video/x4s3muc_huawei-nova-prise-en-main-video_tech']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.09.04.1
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-80999-gf41e37b, ffprobe N-80999-gf41e37b
[debug] Proxy map: {}
[dailymotion] x4s3muc: Downloading webpage
[dailymotion] x4s3muc: Downloading m3u8 information
ERROR: requested format not available
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptom439wb\build\youtube_dl\YoutubeDL.py", line 702, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptom439wb\build\youtube_dl\YoutubeDL.py", line 748, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptom439wb\build\youtube_dl\YoutubeDL.py", line 1424, in process_video_result
youtube_dl.utils.ExtractorError: requested format not available
```

---

Hello, this happens whenever I try to download something from daylimotion.

**Comment by dstftw** [comment]
There are no video-only or audio-only formats for this video you are requesting.

**Comment by Poilaucul** [comment]
It's it possible to have a site specific configuration then?
