### ISSUE TITLE
videomore.ru

### ISSUE THREAD

**Issue by alex-s-m** [rg3/youtube-dl#10592]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.09.04.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
>youtube-dl.exe -v http://videomore.ru/dva_ottsa_i_dva_syna/3_sezon/20_seriya
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://videomore.ru/dva_ottsa_i_dva_syna/3_sezon/20_seriya']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.09.04.1
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-81550-g443c9fa
[debug] Proxy map: {}
[videomore:video] 20_seriya: Downloading webpage
[videomore] 473722: Downloading video XML
[videomore] 473722: Downloading f4m manifest
[videomore] 473722: Downloading video JSON
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptom439wb\build\youtube_dl\extractor\common.py", line 394, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptom439wb\build\youtube_dl\YoutubeDL.py", line 1998, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default

```
http://videomore.ru/dva_ottsa_i_dva_syna/3_sezon/20_seriya

**Comment by alex-s-m** [comment]
`
>youtube-dl.exe -v http://videomore.ru/dva_ottsa_i_dva_syna/3_sezon/20_seriya
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://videomore.ru/dva_ottsa_i_dva_syna/3_sezon/20_seriya']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.11.27
[debug] Python version 3.4.4 - Windows-10-10.0.14971
[debug] exe versions: none
[debug] Proxy map: {}
[videomore:video] 20_seriya: Downloading webpage
[videomore] 473722: Downloading video XML
[videomore] 473722: Downloading f4m manifest
[debug] Invoking downloader on 'http://videomore.ru/video/file/7bcfa9b11c249a586639b97c7cf6692a/1480403345/497860.f4m'
[f4m] Downloading f4m manifest
[f4m] Total fragments: 364
[download] Destination: Два отца и два сына 3 сезон 20 серия-473722.flv
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi2nj3req\build\youtube_dl\YoutubeDL.py", line 1699, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi2nj3req\build\youtube_dl\YoutubeDL.py", line 1641, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi2nj3req\build\youtube_dl\downloader\common.py", line 353, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi2nj3req\build\youtube_dl\downloader\f4m.py", line 393, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi2nj3req\build\youtube_dl\downloader\common.py", line 353, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi2nj3req\build\youtube_dl\downloader\http.py", line 61, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi2nj3req\build\youtube_dl\YoutubeDL.py", line 2001, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden`
