### ISSUE TITLE
[één] Extractor isn't working anymore -> player changed to same as Canvas

### ISSUE THREAD

**Issue by MichaelDeBoey** [rg3/youtube-dl#10605]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.09.08**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Site support request (request for adding support for a new site)

---

```
$ youtube-dl -v https://www.een.be/sorry-voor-alles/herbekijk-sorry-voor-alles
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://www.een.be/sorry-voor-alles/herbekijk-sorry-voor-alles']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.07.05
[debug] Python version 2.7.10 - Darwin-15.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.1.1, ffprobe 3.1.1
[debug] Proxy map: {}
[generic] herbekijk-sorry-voor-alles: Requesting header
WARNING: Falling back on generic information extractor.
[generic] herbekijk-sorry-voor-alles: Downloading webpage
[generic] herbekijk-sorry-voor-alles: Extracting information
ERROR: Unsupported URL: https://www.een.be/sorry-voor-alles/herbekijk-sorry-voor-alles
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1530, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2524, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2513, in _XML
    parser.feed(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 5, column 372
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 681, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 343, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2237, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.een.be/sorry-voor-alles/herbekijk-sorry-voor-alles
```

---

- Single video: https://www.een.be/sorry-voor-alles/herbekijk-sorry-voor-alles

---

### Description of your *issue*, suggested solution and other information

The één-website is completely changed and now provides full episodes.
But the videos on the site aren't downloadable anymore.

I think it's because the één-site now also uses the VRT Player, like they do on the Canvas-site.
So this problem is the same as #7079 and we just need to change the [Canvas-extractor](https://github.com/rg3/youtube-dl/blob/2cab48704ced0d703f2b6de8575dc06e83207462/youtube_dl/extractor/canvas.py) a bit I think.

Maybe a rename would be a good idea, but we already have a [VRT-extractor](https://github.com/rg3/youtube-dl/blob/2cab48704ced0d703f2b6de8575dc06e83207462/youtube_dl/extractor/vrt.py) for other VRT-related sites

Edit: Just found out that there's already a support-request for another VRT-site that uses the same VRT-player: #10343

Edit 2: After having a closer look all the VRT-related sites ([één](http://één.be), [Canvas](http://canvas.be), [Ketnet](http://ketnet.be), [deredactie](http://deredactie.be), ...) use the new VRT Player 2.11.2

**Comment by MichaelDeBoey** [comment]
Thanks for adding it so quickly @dstftw! 😃 

#10343 is the same one as this issue, so I guess you could add that as well?
And you could also add the entire [VRT-extractor](https://github.com/rg3/youtube-dl/blob/2cab48704ced0d703f2b6de8575dc06e83207462/youtube_dl/extractor/vrt.py) I think, since it's using the same player?
