### ISSUE TITLE
ERROR: unable to download video - UnavailableVideoError: [Errno 7] Argument list too long

### ISSUE THREAD

**Issue by znerol2** [rg3/youtube-dl#10603]
I've verified and I assure that I'm running youtube-dl 2016.09.04.1
 At least skimmed through README and most notably FAQ and BUGS sections
 Searched the bugtracker for similar issues including closed ones
What is the purpose of your issue?

 Bug report (encountered problems with youtube-dl)

 Question
 Other

command:

youtube-dl http://www.le.com/ptv/vplay/26463586.html -v

output:

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://www.le.com/ptv/vplay/26463586.html', u'-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.04.06
[debug] Python version 2.7.10 - Darwin-15.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.1.3, ffprobe 3.1.3
[debug] Proxy map: {}
[Le] 26463586: Downloading webpage
[Le] 26463586: Downloading playJson data
[Le] 26463586: Download JSON metadata for format 350
[Le] 26463586: Downloading m3u8 information for format 350
[Le] 26463586: Download JSON metadata for format 1000
[Le] 26463586: Downloading m3u8 information for format 1000
[debug] Invoking downloader on u'data:application/vnd.apple.mpegurl;base64,I0VYVE0zVQ0KI0VYVC1YLVZFUlNJT046Mw0KI0VYVC1YLU1FRElBLVNFUVVFTkNFOjANCiNFWFQtWC1BTExPVy1DQUNIRTpZRVMNCiNFWFQtWC1UQVJHRVREVVJBVElPTjoyMA0KI0VYVC1MRVRWLU0zVTgtVFlQRTpWT0QNCiNFWFQtTEVUVi1NM1U4LVZFUjp2ZXJfMDBfMjINCiNFWFQtTEVUVi1QUk9HUkFNLURFU0NJUFRJT04NCiNFWFQtTEVUVi1QUk9HUkFNLUlEOjQ1OTllZWE4YTI1ODk2ZDNjMDI3MjczNzBkMmMyNGI0MDAwDQojRVhULUxFVFYtUElDLVdJRFRIOjEyODANCiNFWFQtTEVUVi1QSUMtSEVJR0hUOjcyMA0KI0VYVC1MRVRWLVRPVEFML
--------------------------------------------------
...cut out about 1000 more lines like this...
--------------------------------------------------
pZD0mbGVkaXRjaWQ9JmxlZGl0Y2lwPSZsZWRpdGZsPSZsZWRpdGFmbD0NCiNFWFQtWC1FTkRMSVNUDQo=' -c copy -f mp4 -bsf:a aac_adtstoasc 'file:ChinaGT成都站实况全程-26463586.mp4.part'
ERROR: unable to download video
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1725, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 680, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 725, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1371, in process_video_result
    self.process_info(new_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1638, in process_info
    raise UnavailableVideoError(err)
UnavailableVideoError: [Errno 7] Argument list too long

**Comment by znerol2** [comment]
updated to latest version, problem solved
