### ISSUE TITLE
[Funimation] Unable to extract players data

### ISSUE THREAD

**Issue by MartinWeingaertner** [rg3/youtube-dl#10629]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.09.11.1*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.09.11.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
C:\Users\Martin\Desktop\test>youtube-dl.exe "http://www.funimation.com/shows/seiyus-life/videos/official/recording" -u user -p password -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://www.funimation.com/shows/seiyus-life/videos/official/recording', '-u', 'PRIVATE', '-p', 'PRIVATE', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.09.11.1
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-81338-g6612d04, ffprobe N-81338-g6612d04, rtmpdump 2.4
[debug] Proxy map: {}
[Funimation] Logging in as user
[Funimation] recording: Downloading webpage
ERROR: Unable to extract players data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpj47q005f\build\youtube_dl\YoutubeDL.py", line 691, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpj47q005f\build\youtube_dl\extractor\common.py", line 347, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpj47q005f\build\youtube_dl\extractor\funimation.py", line 157, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpj47q005f\build\youtube_dl\extractor\common.py", line 650, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract players data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

### Description of your *issue*, suggested solution and other information

Seems to be a recent issue, last time I downloaded something about 8 days ago everything still worked.
Other sites (I tried Crunchyroll) do not seem to be affected.

**Comment by yan12125** [comment]
Funimation blocks automatic downloaders now. Could you try ```--cookies```?

**Comment by MartinWeingaertner** [comment]
With the --cookies option the message changes to the one below, like in [#10639](https://github.com/rg3/youtube-dl/issues/10639).
```
C:\Users\Martin\Desktop\test>youtube-dl.exe "http://www.funimation.com/shows/seiyus-life/videos/official/recording" -u user -p password --cookies cookies.txt -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://www.funimation.com/shows/seiyus-life/videos/official/recording', '-u', 'PRIVATE', '-p', 'PRIVATE', '--cookies', 'cookies.txt', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.09.11.1
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-81338-g6612d04, ffprobe N-81338-g6612d04, rtmpdump 2.4
[debug] Proxy map: {}
[Funimation] Logging in as user
ERROR: Unable to log in; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpj47q005f\build\youtube_dl\YoutubeDL.py", line 691, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpj47q005f\build\youtube_dl\extractor\common.py", line 346, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpj47q005f\build\youtube_dl\extractor\common.py", line 340, in initialize
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpj47q005f\build\youtube_dl\extractor\funimation.py", line 113, in _real_initialize
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpj47q005f\build\youtube_dl\extractor\funimation.py", line 110, in _login
youtube_dl.utils.ExtractorError: Unable to log in; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by yan12125** [comment]
How about use ```--cookies``` and remove ```--username``` and ```--password```?

**Comment by MartinWeingaertner** [comment]
That seems to lead back to square one:
```
C:\Users\Martin\Desktop\test>youtube-dl.exe "http://www.funimation.com/shows/seiyus-life/videos/official/recording" --cookies cookies.txt -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://www.funimation.com/shows/seiyus-life/videos/official/recording', '--cookies', 'cookies.txt', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.09.11.1
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-81338-g6612d04, ffprobe N-81338-g6612d04, rtmpdump 2.4
[debug] Proxy map: {}
[Funimation] recording: Downloading webpage
ERROR: Unable to extract players data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpj47q005f\build\youtube_dl\YoutubeDL.py", line 691, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpj47q005f\build\youtube_dl\extractor\common.py", line 347, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpj47q005f\build\youtube_dl\extractor\funimation.py", line 157, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpj47q005f\build\youtube_dl\extractor\common.py", line 650, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract players data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by Parent5446** [comment]
You need to have `--cookies` in order to use Funimation now due to recent changes with their site.

As noted, the login error you get when using `--cookies` is a separate bug that I've documented in #10639, and should hopefully have a PR ready for today.

@MartinWeingaertner if possible, could you try checking out or applying my patch (https://github.com/Parent5446/youtube-dl/commit/833f233a780e6e4c08b9b21be03733e65d3f5425) and see if it resolves the issue you're facing?

**Comment by MartinWeingaertner** [comment]
@Parent5446 I've somehow managed to clone the repo and test your patch. I can confirm that it is working and that these two issues are indeed one and the same. Thank you for your work and I hope this patch is soon included in a new release.

**Comment by Parent5446** [comment]
@MartinWeingaertner if things are working again, feel free to close this.

**Comment by MartinWeingaertner** [comment]
Closing this for the moment.
