### ISSUE TITLE
[funimation] Unable to log in

### ISSUE THREAD

**Issue by Parent5446** [rg3/youtube-dl#10639]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.09.11.1*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.09.11.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

_Note: this error can be reproduced on both the latest release and Git HEAD. The log output is identical for both._

```
$ python -m youtube_dl --verbose http://www.funimation.com/shows/love-live-sunshine/videos/official/aye-aye-my-friend\?watch\=sub
[debug] System config: []
[debug] User config: [u'--netrc', u'--cookies', u'/home/parent5446/.cache/youtube-dl-cookies
.txt', u'--prefer-free-formats']                                                           
[debug] Command-line args: [u'--verbose', u'http://www.funimation.com/shows/love-live-sunshi
ne/videos/official/aye-aye-my-friend?watch=sub']                                           
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.09.11.1
[debug] Git HEAD: 8414c2d
[debug] Python version 2.7.12+ - Linux-4.6.0-1-amd64-x86_64-with-debian-stretch-sid
[debug] exe versions: ffmpeg 3.1.2-1, ffprobe 3.1.2-1, rtmpdump 2.4
[debug] Proxy map: {}
[Funimation] Logging in as tylerromeo@gmail.com
ERROR: Unable to log in; please report this issue on https://yt-dl.org/bug . Make sure you a
re using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to cal
l youtube-dl with the --verbose flag and include its complete output.                      
Traceback (most recent call last):
  File "youtube_dl/YoutubeDL.py", line 692, in extract_info
    ie_result = ie.extract(url)
  File "youtube_dl/extractor/common.py", line 346, in extract
    self.initialize()
  File "youtube_dl/extractor/common.py", line 340, in initialize
    self._real_initialize()
  File "youtube_dl/extractor/funimation.py", line 113, in _real_initialize
    self._login()
  File "youtube_dl/extractor/funimation.py", line 110, in _login
    raise ExtractorError('Unable to log in')
ExtractorError: Unable to log in; please report this issue on https://yt-dl.org/bug . Make s
ure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be su
re to call youtube-dl with the --verbose flag and include its complete output.
```

---

### Description of your *issue*, suggested solution and other information

Funimation is having login issues. It may be related to changes in their site. Trying to investigate now, but no guarantees.

**Comment by Parent5446** [comment]
It seems the issue is because Funimation has started requiring session cookies before it will render the login page. This can be reproduced by trying to open the _LOGIN_URL in an incognito browser, and noticing that it redirects you to the home page, but then entering the same URL again without clearing the cookies will render the login page as expected.

I've tested, and simply adding an initial request before attempting to log in seems to resolve the issue. PR incoming shortly.

**Comment by Parent5446** [comment]
I have the PR ready, but can't send it until tomorrow when I get approval from work. (Forgot to bring my corp laptop home with me.) If somebody beats me to the punch so be it.

**Comment by Parent5446** [comment]
I can no longer reproduce this locally, nor can others as mentioned in #10651, so it must have been a regression on Funimation's end.
