### ISSUE TITLE
Can't download from streamin.to

### ISSUE THREAD

**Issue by whitesiroi** [rg3/youtube-dl#10646]
```
$ youtube-dl -v "http://streamin.to/embed-lgri82v8szvp-852x460.html"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://streamin.to/embed-lgri82v8szvp-852x460.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.09.11.1
[debug] Python version 2.7.10 - Darwin-15.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.8, ffprobe 2.8
[debug] Proxy map: {}
[XFileShare] lgri82v8szvp: Downloading webpage
[XFileShare] lgri82v8szvp: Waiting for 5 seconds
[XFileShare] lgri82v8szvp: Downloading video page
ERROR: Unable to extract OpenGraph title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 691, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 347, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/xfileshare.py", line 132, in _real_extract
    webpage, 'title', default=None) or self._og_search_title(webpage)).strip()
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 759, in _og_search_title
    return self._og_search_property('title', html, **kargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 747, in _og_search_property
    escaped = self._search_regex(og_regexes, html, name, flags=re.DOTALL, **kargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 650, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract OpenGraph title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

```
$ youtube-dl --version
2016.09.11.1
```

**Comment by Belderak** [comment]
Is it not worth to make one extractor per provider? Here we just have to regex the url jwplayer 

![image](https://cloud.githubusercontent.com/assets/7056621/18611647/69f9574a-7d40-11e6-86a2-957fbbb59354.png)

**Comment by dstftw** [comment]
It's already there if you bother to check the log.

**Comment by Belderak** [comment]
Sorry, I would say 'per site'

class XFileShareIE(InfoExtractor):
    _SITES = (
        ('daclips.in', 'DaClips'),
        ('filehoot.com', 'FileHoot'),
        ('gorillavid.in', 'GorillaVid'),
        ('movpod.in', 'MovPod'),
        ('powerwatch.pw', 'PowerWatch'),
        ('rapidvideo.ws', 'Rapidvideo.ws'),
        ('thevideobee.to', 'TheVideoBee'),
        ('vidto.me', 'Vidto'),
        ('streamin.to', 'Streamin.To'),
        ('xvidstage.com', 'XVIDSTAGE'),
    )
One for vidto.me, one for streamin etc...

**Comment by dstftw** [comment]
That's pointless. There is no matter where to add regexes.
