### ISSUE TITLE
Can't download from bilibili.com

### ISSUE THREAD

**Issue by whitesiroi** [rg3/youtube-dl#10647]
```
$ youtube-dl -v "http://www.bilibili.com/video/av1816340/"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.bilibili.com/video/av1816340/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.09.11.1
[debug] Python version 2.7.10 - Darwin-15.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.8, ffprobe 2.8
[debug] Proxy map: {}
[BiliBili] 1816340: Downloading webpage
[BiliBili] 1816340: Downloading video info page
ERROR: An extractor error has occurred. (caused by KeyError(u'backup_url',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 347, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/bilibili.py", line 127, in _real_extract
    for backup_url in durl['backup_url']:
KeyError: u'backup_url'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 691, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 353, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
ExtractorError: An extractor error has occurred. (caused by KeyError(u'backup_url',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

```
$ youtube-dl --version
2016.09.11.1
```

**Comment by yan12125** [comment]
Looks like a copyrighted product of Fox Broadcasting Company according to Wikipedia: https://en.wikipedia.org/wiki/Lie_to_Me. Do you have other examples?

**Comment by yan12125** [comment]
Or, if BiliBili has bought legal redistribution permissions from copyright holders, could you paste some materials for that? Either English or Chinese is fine.

**Comment by whitesiroi** [comment]
> Or, if BiliBili has bought legal redistribution permissions from copyright holders, could you paste some materials for that?

no:)

**Comment by yan12125** [comment]
Never mind. I still fix the problem as other legal videos may be affected by the same bug as well.
