### ISSUE TITLE
urlopen error [WinError 10060] at "Downloading MPD manifest" stage

### ISSUE THREAD

**Issue by Praesidian** [rg3/youtube-dl#10761]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.09.24*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.09.24**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -f bestaudio https://www.youtube.com/watch?v=hqXpaTu8UrM
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', '-f', 'bestaudio', 'https://www.youtube.com/watch?v=hqXpaTu8UrM']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2016.09.24
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] hqXpaTu8UrM: Downloading webpage
[youtube] hqXpaTu8UrM: Downloading video info webpage
[youtube] hqXpaTu8UrM: Extracting video information
[youtube] hqXpaTu8UrM: Downloading MPD manifest
[debug] Invoking downloader on 'https://r8---sn-j5caxoxu-hh0s.googlevideo.com/videoplayback?id=86a5e9693bbc52b3&itag=140&source=youtube&requiressl=yes&pcm2cms=yes&mv=m&ms=au&initcwndbps=2342500&mn=sn-j5caxoxu-hh0s&mm=31&pl=20&ratebypass=yes&mime=audio/mp4&gir=yes&clen=3987045&lmt=1401161642629756&dur=248.313&key=dg_yt0&mt=1474859081&upn=AxlPwg2lpD0&signature=1166C6D317E3466C02FB9DFFC9EA9F880678340C.81CF84B91C7C038FC66EABCD66808884B1E96534&ip=47.16.82.215&ipbits=0&expire=1474881013&sparams=ip,ipbits,expire,id,itag,source,requiressl,pcm2cms,mv,ms,initcwndbps,mn,mm,pl,ratebypass,mime,gir,clen,lmt,dur'
ERROR: unable to download video data: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
Traceback (most recent call last):
  File "C:\Python\Python34\lib\urllib\request.py", line 1183, in do_open
  File "C:\Python\Python34\lib\http\client.py", line 1137, in request
  File "C:\Python\Python34\lib\http\client.py", line 1182, in _send_request
  File "C:\Python\Python34\lib\http\client.py", line 1133, in endheaders
  File "C:\Python\Python34\lib\http\client.py", line 963, in _send_output
  File "C:\Python\Python34\lib\http\client.py", line 898, in send
  File "C:\Python\Python34\lib\http\client.py", line 1279, in connect
  File "C:\Python\Python34\lib\http\client.py", line 871, in connect
  File "C:\Python\Python34\lib\socket.py", line 516, in create_connection
  File "C:\Python\Python34\lib\socket.py", line 507, in create_connection
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc7h_sle1\build\youtube_dl\YoutubeDL.py", line 1699, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc7h_sle1\build\youtube_dl\YoutubeDL.py", line 1641, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc7h_sle1\build\youtube_dl\downloader\common.py", line 354, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc7h_sle1\build\youtube_dl\downloader\http.py", line 58, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc7h_sle1\build\youtube_dl\YoutubeDL.py", line 2001, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc7h_sle1\build\youtube_dl\utils.py", line 1011, in https_open
  File "C:\Python\Python34\lib\urllib\request.py", line 1185, in do_open
urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond> 

...
<end of log>
```

---

### Description of your *issue*, suggested solution and other information

Failed target videos: 
https://www.youtube.com/watch?v=hqXpaTu8UrM
https://www.youtube.com/watch?v=YtaJNbW4ET4

Working target video:
https://www.youtube.com/watch?v=bOrVzmd9j1s

youtube-dl gives a connection error whenever it reaches the Downloading MPD Manifest stage.  I can access all videos themselves fine, and when I ask for available formats, it connects fine and works as intended.  I have tried using the youtu.be url as well as the full url, and using http instead of https, but it still gives the same error.  I have also tried it using a different video (provided above), and it worked perfectly.  When I ask for available formats, it connects fine and gives me the format choices for all three videos.

Error log provided above is for attempt on https://www.youtube.com/watch?v=hqXpaTu8UrM

Any help or advice would be appreciated.  Thank you.

**Comment by yan12125** [comment]
Could you paste logs for successful videos as well?

By the way, this may be an issue with antivirus services. Please also try to download videos again with antivirus services disabled.

**Comment by Praesidian** [comment]
The full verbose log for the successful video:

$youtube-dl -v -f bestaudio https://www.youtube.com/watch?v=bOrVzmd9j1s 
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', '-f', 'bestaudio', 'https://www.youtube.com/watch?v=bOrVzmd9j1s']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2016.09.24
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] bOrVzmd9j1s: Downloading webpage
[youtube] bOrVzmd9j1s: Downloading video info webpage
[youtube] bOrVzmd9j1s: Extracting video information
[youtube] bOrVzmd9j1s: Downloading MPD manifest
[debug] Invoking downloader on 'https://r4---sn-j5caxoxu-hh0l.googlevideo.com/videoplayback?id=6cead5ce677d8f5b&itag=251&source=youtube&requiressl=yes&ms=au&mv=m&initcwndbps=2523750&mn=sn-j5caxoxu-hh0l&mm=31&pcm2cms=yes&pl=20&ratebypass=yes&mime=audio/webm&gir=yes&clen=4346852&lmt=1453455546970464&dur=229.341&signature=145AB4A9421CB3900F52612A01DBB170FBE03634.1F5109DFE168A3D689579901859BA3DBB5AC223B&mt=1474901871&upn=lnWxNFoKwxM&key=dg_yt0&ip=47.16.82.215&ipbits=0&expire=1474924014&sparams=ip,ipbits,expire,id,itag,source,requiressl,ms,mv,initcwndbps,mn,mm,pcm2cms,pl,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: Awr-i-guhn-bOrVzmd9j1s.webm

[download]   0.0% of 4.15MiB at 64.28KiB/s ETA 01:06
[download]   0.1% of 4.15MiB at 192.83KiB/s ETA 00:21
[download]   0.2% of 4.15MiB at 435.92KiB/s ETA 00:09
[download]   0.4% of 4.15MiB at 934.12KiB/s ETA 00:04
[download]   0.7% of 4.15MiB at 984.97KiB/s ETA 00:04
[download]   1.5% of 4.15MiB at  1.58MiB/s ETA 00:02 
[download]   3.0% of 4.15MiB at  2.05MiB/s ETA 00:01 
[download]   6.0% of 4.15MiB at  1.03MiB/s ETA 00:03 
[download]  12.0% of 4.15MiB at  1.60MiB/s ETA 00:02 
[download]  24.1% of 4.15MiB at  1.88MiB/s ETA 00:01 
[download]  48.2% of 4.15MiB at  2.38MiB/s ETA 00:00 
[download]  96.5% of 4.15MiB at  2.56MiB/s ETA 00:00 
[download] 100.0% of 4.15MiB at  2.60MiB/s ETA 00:00 
[download] 100% of 4.15MiB in 00:01

I tried it again on the failed videos after disabling my antivirus, but the same exact problem happened, including pretty much the same -v output.

**Comment by Cinerar** [comment]
i'm expiriencing same issue on some of fresh uploaded videos.  It will download part of the video, than stop with error.  If you start it over again it will download next part and stop again.  It will be hard to reproduce as if someone already downloaded video by that link, youtube-dl will download it without a problem.
