### ISSUE TITLE
bilibili - RegexNotFoundError

### ISSUE THREAD

**Issue by MewX** [rg3/youtube-dl#10763]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.09.24*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.09.24**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

#### Linux

```
$ ./youtube-dl --verbose http://www.bilibili.com/video/av1230156/index_2.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.bilibili.com/video/av1230156/index_2.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.09.24
[debug] Python version 2.7.5 - Linux-3.10.0-327.22.2.el7.x86_64-x86_64-with-redhat-7.2-Maipo
[debug] exe versions: ffmpeg 3.1.3, ffprobe 3.1.3
[debug] Proxy map: {}
[BiliBili] 1230156: Downloading webpage
ERROR: Unable to extract player parameters; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 355, in extract
    return self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/bilibili.py", line 48, in _real_extract
    webpage, 'player parameters'))['cid'][0]
  File "./youtube-dl/youtube_dl/extractor/common.py", line 658, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract player parameters; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

#### Windows

```
C:\>youtube-dl.exe -v http://www.bilibili.com/video/av1230156
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.bilibili.com/video/av1230156']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2016.09.24
[debug] Python version 3.4.4 - Windows-8.1-6.3.9600
[debug] exe versions: none
[debug] Proxy map: {}
[BiliBili] 1230156: Downloading webpage
ERROR: Unable to extract player parameters; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U
 to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc7h_sle1\build\youtube_dl\YoutubeDL.py", line 694, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc7h_sle1\build\youtube_dl\extractor\common.py", line 355, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc7h_sle1\build\youtube_dl\extractor\bilibili.py", line 48, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc7h_sle1\build\youtube_dl\extractor\common.py", line 658, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract player parameters; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest
 version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by yan12125** [comment]
Seems it requires login? It says:
```
视频不见了唷，你可以尝试登录
```

**Comment by MewX** [comment]
Oh, right! Thank you, I tried 2 browsers, but I didn't notice that it's logged in.

**Comment by yan12125** [comment]
FYI: there's a plan to support authentication for bilibili at #6661. No real progress, though.
