### ISSUE TITLE
site support request for watch.hgtv.com

### ISSUE THREAD

**Issue by Transcodes** [rg3/youtube-dl#10765]
### Make sure you are using the _latest_ version: run `youtube-dl --version` and ensure your version is _2016.09.24_. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.09.24**
### Before submitting an _issue_ make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
### What is the purpose of your _issue_?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other
### If the purpose of this _issue_ is a _bug report_, _site support request_ or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
removed personal info $
$  youtube-dl  -v --ap-mso <TV provider name> --ap-username <email> --ap-password <pass> http://watch.hgtv.com/player.HFORF.html#0247376
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--ap-mso', '$TV', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', 'http://watch.hgtv.com/player.HFORF.html#0247376']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.02.07
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-83034-gf48b6b8, ffprobe N-83034-gf48b6b8
[debug] Proxy map: {}
[generic] player.HFORF: Requesting header
WARNING: Falling back on generic information extractor.
[generic] player.HFORF: Downloading webpage
[generic] player.HFORF: Extracting information
ERROR: Unsupported URL: http://watch.hgtv.com/player.HFORF.html#0247376
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpfjt892j_\build\youtube_dl\YoutubeDL.py", line 696, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpfjt892j_\build\youtube_dl\extractor\common.py", line 369, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpfjt892j_\build\youtube_dl\extractor\generic.py", line 2589, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: http://watch.hgtv.com/player.HFORF.html#0247376

<end of log>
```

---
### If the purpose of this _issue_ is a _site support request_ please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video that does not need account credentials :  

http://watch.hgtv.com/player.HFORF.html#0257479
- Single video: http://watch.hgtv.com/player.HFORF.html#0257767
  needs TV Provider login.
- Playlist: http://watch.hgtv.com/player.HFORF.html
  ## http://watch.hgtv.com/home.html
### Description of your _issue_, suggested solution and other information

Show : Flip or Flop and others
videos may be region restricted to Canada
may be similar to www.hgtv.com
All videos need TV Login info..It would be great if someone can provide if needed

**Comment by StevenDTX** [comment]
This really should include all of Scripps sites (DIY, FOOD, Cooking, GAC, Travel) since the players on all of them are the same.

**Comment by bshaw** [comment]
+1

**Comment by StevenDTX** [comment]
Thanks @remitamine.  This works great for hgtv.com. Should it work for other Scripps networks?  

This is what I get on a Food Network show:

```
C:\support\Python36\lib\youtube-dl-master>c:\support\Python36\python.exe -m youtube-dl --download-archive D:\scripts\Auto-TV-Download\archive.txt --restrict-filenames --continue --no-check-certificate --verbose --ap-mso DTV --ap-username <username> --ap-password <password> -o "D:\scripts\Auto-TV-Download\TEMP\The.Pioneer.Woman.2017.02.04.Merc.Story.mp4" "http://watch.hgtv.com/player.HFXUP.html#0255934"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--download-archive', 'D:\\scripts\\Auto-TV-Download\\archive.txt', '--restrict-filenames', '--continue', '--no-check-certificate', '--verbose', '--ap-mso', 'DTV', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '-o', 'D:\\scripts\\Auto-TV-Download\\TEMP\\The.Pioneer.Woman.2017.02.04.Merc.Story.mp4', 'http://watch.hgtv.com/player.HFXUP.html#0255934']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2017.02.07
[debug] Python version 3.6.0b1 - Windows-10-10.0.14393-SP0
[debug] exe versions: ffmpeg N-82966-g6993bb4, ffprobe N-72383-g7206b94, rtmpdump 2.4
[debug] Proxy map: {}
[scrippsnetworks:watch] 0255934: Downloading webpage
ERROR: An extractor error has occurred. (caused by StopIteration()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\support\Python36\lib\youtube-dl-master\youtube_dl\extractor\common.py", line 369, in extract
    return self._real_extract(url)
  File "C:\support\Python36\lib\youtube-dl-master\youtube_dl\extractor\scrippsnetworks.py", line 36, in _real_extract
    video_data = next(v for v in channel['videos'] if v.get('nlvid') == video_id)
StopIteration
Traceback (most recent call last):
  File "C:\support\Python36\lib\youtube-dl-master\youtube_dl\extractor\common.py", line 369, in extract
    return self._real_extract(url)
  File "C:\support\Python36\lib\youtube-dl-master\youtube_dl\extractor\scrippsnetworks.py", line 36, in _real_extract
    video_data = next(v for v in channel['videos'] if v.get('nlvid') == video_id)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\support\Python36\lib\youtube-dl-master\youtube_dl\YoutubeDL.py", line 696, in extract_info
    ie_result = ie.extract(url)
  File "C:\support\Python36\lib\youtube-dl-master\youtube_dl\extractor\common.py", line 375, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by StopIteration()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
