### ISSUE TITLE
Couldn't download video from lesports.com, again

### ISSUE THREAD

**Issue by Kimi-Arthur** [rg3/youtube-dl#10794]
Hi,

Similar to bug #9750.

I tried `youtube-dl -v http://www.lesports.com/match/1023203003.html`, which is original url. Output:

> [debug] System config: []
> [debug] User config: []
> [debug] Command-line args: ['-v', 'http://www.lesports.com/match/1023203003.html']
> [debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
> [debug] youtube-dl version 2016.09.27
> [debug] Python version 3.5.0 - Windows-post2012Server-6.3.9600
> [debug] exe versions: none
> [debug] Proxy map: {}
> [generic] 1023203003: Requesting header
> WARNING: Falling back on generic information extractor.
> [generic] 1023203003: Downloading webpage
> [generic] 1023203003: Extracting information
> ERROR: Unsupported URL: http://www.lesports.com/match/1023203003.html
> Traceback (most recent call last):
>   File "c:\program files\python 3.5\lib\site-packages\youtube_dl\YoutubeDL.py", line 694, in extract_info
>     ie_result = ie.extract(url)
>   File "c:\program files\python 3.5\lib\site-packages\youtube_dl\extractor\common.py", line 355, in extract
>     return self._real_extract(url)
>   File "c:\program files\python 3.5\lib\site-packages\youtube_dl\extractor\generic.py", line 2424, in _real_extract
>     raise UnsupportedError(url)
> youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.lesports.com/match/1023203003.html

I then tried to use `youtube-dl -v http://sports.le.com/match/1023203003.html`, which is similar to the pattern in #9750. Output is similar to #9750,

> [debug] System config: []
> [debug] User config: []
> [debug] Command-line args: ['-v', 'http://sports.le.com/match/1023203003.html']
> [debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
> [debug] youtube-dl version 2016.09.27
> [debug] Python version 3.5.0 - Windows-post2012Server-6.3.9600
> [debug] exe versions: none
> [debug] Proxy map: {}
> [LePlaylist] 1023203003: Downloading webpage
> [download] Downloading playlist: 拜仁慕尼黑,罗斯托夫,拜仁慕尼黑VS罗斯托夫,欧洲冠军联赛,足球
> [LePlaylist] playlist 拜仁慕尼黑,罗斯托夫,拜仁慕尼黑VS罗斯托夫,欧洲冠军联赛,足球: Collected 0 video ids (downloading 0 of them)
> [download] Finished downloading playlist: 拜仁慕尼黑,罗斯托夫,拜仁慕尼黑VS罗斯托夫,欧洲冠军联赛,足球

**Comment by yan12125** [comment]
Could you try the latest un-released version: https://github.com/rg3/youtube-dl/archive/master.zip (extract it and run ```python youtube_dl/__main__.py```)

**Comment by Kimi-Arthur** [comment]
Sadly, neither link works. Here is the verbose log. (the `--version` shows 2016.09.27, not sure whether that's right)

> F:\Downloads\Chrome\youtube-dl-master>python youtube_dl/__main__.py -v http://www.lesports.com/match/1023203003.htm
> [debug] System config: []
> [debug] User config: []
> [debug] Command-line args: ['-v', 'http://www.lesports.com/match/1023203003.htm']
> [debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
> [debug] youtube-dl version 2016.09.27
> [debug] Python version 3.5.0 - Windows-post2012Server-6.3.9600
> [debug] exe versions: none
> [debug] Proxy map: {}
> [generic] 1023203003: Requesting header
> WARNING: Falling back on generic information extractor.
> [generic] 1023203003: Downloading webpage
> [generic] 1023203003: Extracting information
> ERROR: Unsupported URL: http://www.lesports.com/match/1023203003.htm
> Traceback (most recent call last):
>   File "F:\Downloads\Chrome\youtube-dl-master\youtube_dl\YoutubeDL.py", line 694, in extract_info
>     ie_result = ie.extract(url)
>   File "F:\Downloads\Chrome\youtube-dl-master\youtube_dl\extractor\common.py", line 355, in extract
>     return self._real_extract(url)
>   File "F:\Downloads\Chrome\youtube-dl-master\youtube_dl\extractor\generic.py", line 2424, in _real_extract
>     raise UnsupportedError(url)
> youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.lesports.com/match/1023203003.htm
> 
> 
> F:\Downloads\Chrome\youtube-dl-master>python youtube_dl/__main__.py -v http://sports.le.com/match/1023203003.html
> [debug] System config: []
> [debug] User config: []
> [debug] Command-line args: ['-v', 'http://sports.le.com/match/1023203003.html']
> [debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
> [debug] youtube-dl version 2016.09.27
> [debug] Python version 3.5.0 - Windows-post2012Server-6.3.9600
> [debug] exe versions: none
> [debug] Proxy map: {}
> [Le] 1023203003: Downloading webpage
> [Le] 1023203003: Downloading html5 playJson data
> ERROR: Generic error. flag = 0
> Traceback (most recent call last):
>   File "F:\Downloads\Chrome\youtube-dl-master\youtube_dl\YoutubeDL.py", line 694, in extract_info
>     ie_result = ie.extract(url)
>   File "F:\Downloads\Chrome\youtube-dl-master\youtube_dl\extractor\common.py", line 355, in extract
>     return self._real_extract(url)
>   File "F:\Downloads\Chrome\youtube-dl-master\youtube_dl\extractor\leeco.py", line 150, in _real_extract
>     self._check_errors(play_json_h5)
>   File "F:\Downloads\Chrome\youtube-dl-master\youtube_dl\extractor\leeco.py", line 132, in _check_errors
>     raise ExtractorError(msg, expected=True)
> youtube_dl.utils.ExtractorError: Generic error. flag = 0

**Comment by yan12125** [comment]
Alright the bug is not easy.
