### ISSUE TITLE
Some Facebook plugin URLs are unsupported

### ISSUE THREAD

**Issue by wanchihh** [rg3/youtube-dl#10795]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.09.27*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.09.27**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
> youtube-dl.exe "https://www.facebook.com/v2.3/plugins/video.php?allowfullscreen=true&app_id=&channel=http%3A%2F%2Fstaticxx.facebook.com%2Fconnect%2Fx
d_arbiter%2Fr%2FP5DLcu0KGJB.js%3Fversion%3D42%23cb%3Df1d45e6da%26domain%3Dwww.mycarforum.com%26origin%3Dhttp%253A%252F%252Fwww.mycarforum.com%252Ff1e33442e4%26r
elation%3Dparent.parent&container_width=883&href=http%3A%2F%2Fwww.mycarforum.com%2FTheStraitsTimes%2Fvideos%2F10153797435237115%2F%3Ftype%3D3&locale=en_US&sdk=j
oey" -v                                                                                                                                                         
[debug] System config: []                                                                                                                                       
[debug] User config: []                                                                                                                                         
[debug] Command-line args: ['https://www.facebook.com/v2.3/plugins/video.php?allowfullscreen=true&app_id=&channel=http%3A%2F%2Fstaticxx.facebook.com%2Fconnect%2
Fxd_arbiter%2Fr%2FP5DLcu0KGJB.js%3Fversion%3D42%23cb%3Df1d45e6da%26domain%3Dwww.mycarforum.com%26origin%3Dhttp%253A%252F%252Fwww.mycarforum.com%252Ff1e33442e4%2
6relation%3Dparent.parent&container_width=883&href=http%3A%2F%2Fwww.mycarforum.com%2FTheStraitsTimes%2Fvideos%2F10153797435237115%2F%3Ftype%3D3&locale=en_US&sdk
=joey', '-v']                                                                                                                                                   
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252                                                                                               
[debug] youtube-dl version 2016.09.27                                                                                                                           
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1                                                                                                           
[debug] exe versions: ffmpeg N-74113-gcdb0225, ffprobe N-74113-gcdb0225                                                                                         
[debug] Proxy map: {}                                                                                                                                           
[generic] video.php?allowfullscreen=true&app_id=&channel=http://staticxx.facebook.com/connect/xd_arbiter/r/P5DLcu0KGJB.js?version=42#cb=f1d45e6da&domain=www.myc
arforum.com&origin=http%3A%2F%2Fwww.mycarforum.com%2Ff1e33442e4&relation=parent.parent&container_width=883&href=http://www.mycarforum: Requesting header        
WARNING: Falling back on generic information extractor.                                                                                                         
[generic] video.php?allowfullscreen=true&app_id=&channel=http://staticxx.facebook.com/connect/xd_arbiter/r/P5DLcu0KGJB.js?version=42#cb=f1d45e6da&domain=www.myc
arforum.com&origin=http%3A%2F%2Fwww.mycarforum.com%2Ff1e33442e4&relation=parent.parent&container_width=883&href=http://www.mycarforum: Downloading webpage      
[generic] video.php?allowfullscreen=true&app_id=&channel=http://staticxx.facebook.com/connect/xd_arbiter/r/P5DLcu0KGJB.js?version=42#cb=f1d45e6da&domain=www.myc
arforum.com&origin=http%3A%2F%2Fwww.mycarforum.com%2Ff1e33442e4&relation=parent.parent&container_width=883&href=http://www.mycarforum: Extracting information   
ERROR: Unsupported URL: https://www.facebook.com/v2.3/plugins/video.php?allowfullscreen=true&app_id=&channel=http%3A%2F%2Fstaticxx.facebook.com%2Fconnect%2Fxd_a
rbiter%2Fr%2FP5DLcu0KGJB.js%3Fversion%3D42%23cb%3Df1d45e6da%26domain%3Dwww.mycarforum.com%26origin%3Dhttp%253A%252F%252Fwww.mycarforum.com%252Ff1e33442e4%26rela
tion%3Dparent.parent&container_width=883&href=http%3A%2F%2Fwww.mycarforum.com%2FTheStraitsTimes%2Fvideos%2F10153797435237115%2F%3Ftype%3D3&locale=en_US&sdk=joey
                                                                                                                                                                
Traceback (most recent call last):                                                                                                                              
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpaa64pv68\build\youtube_dl\YoutubeDL.py", line 694, in extract_info                         
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpaa64pv68\build\youtube_dl\extractor\common.py", line 355, in extract                       
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpaa64pv68\build\youtube_dl\extractor\generic.py", line 2424, in _real_extract               
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.facebook.com/v2.3/plugins/video.php?allowfullscreen=true&app_id=&channel=http%3A%2F%2Fstaticxx.f
acebook.com%2Fconnect%2Fxd_arbiter%2Fr%2FP5DLcu0KGJB.js%3Fversion%3D42%23cb%3Df1d45e6da%26domain%3Dwww.mycarforum.com%26origin%3Dhttp%253A%252F%252Fwww.mycarfor
um.com%252Ff1e33442e4%26relation%3Dparent.parent&container_width=883&href=http%3A%2F%2Fwww.mycarforum.com%2FTheStraitsTimes%2Fvideos%2F10153797435237115%2F%3Fty
pe%3D3&locale=en_US&sdk=joey                                                                                                                                    
...
<end of log>
```

---

### Description of your *issue*, suggested solution and other information

Hi,

When I tried downloading videos from the Facebook urls beginning with **"https://www.facebook.com/v2.3/plugins/video.php"**, the Unsupported URL error is returned.

Eg.:
- https://www.facebook.com/v2.3/plugins/video.php?allowfullscreen=true&app_id=&channel=http%3A%2F%2Fstaticxx.facebook.com%2Fconnect%2Fxd_arbiter%2Fr%2FP5DLcu0KGJB.js%3Fversion%3D42%23cb%3Df1d45e6da%26domain%3Dwww.mycarforum.com%26origin%3Dhttp%253A%252F%252Fwww.mycarforum.com%252Ff1e33442e4%26relation%3Dparent.parent&container_width=883&href=http%3A%2F%2Fwww.mycarforum.com%2FTheStraitsTimes%2Fvideos%2F10153797435237115%2F%3Ftype%3D3&locale=en_US&sdk=joey
- https://www.facebook.com/v2.3/plugins/video.php?allowfullscreen=true&app_id=&channel=http%3A%2F%2Fstaticxx.facebook.com%2Fconnect%2Fxd_arbiter%2Fr%2FP5DLcu0KGJB.js%3Fversion%3D42%23cb%3Df61fb0db%26domain%3Dwww.mycarforum.com%26origin%3Dhttp%253A%252F%252Fwww.mycarforum.com%252Ff77f158a4%26relation%3Dparent.parent&container_width=861&href=http%3A%2F%2Fwww.mycarforum.com%2FBehChiaLor%2Fvideos%2F1779898258932927%2F%3Ftype%3D3&locale=en_US&sdk=joey
- https://www.facebook.com/v2.3/plugins/video.php?allowfullscreen=true&app_id=&channel=http%3A%2F%2Fstaticxx.facebook.com%2Fconnect%2Fxd_arbiter%2Fr%2FP5DLcu0KGJB.js%3Fversion%3D42%23cb%3Df1dbf9be7%26domain%3Dwww.mycarforum.com%26origin%3Dhttp%253A%252F%252Fwww.mycarforum.com%252Ff77f158a4%26relation%3Dparent.parent&container_width=883&href=http%3A%2F%2Fwww.mycarforum.com%2FBehChiaLor%2Fvideos%2F1779959948926758%2F%3Ftype%3D3&locale=en_US&sdk=joey

Note the youtube-dl is able to download videos from Facebook urls beginning with
**"https://www.facebook.com/plugins/video.php"**

Thanks.

**Comment by ole-tange** [comment]
This also does not work:
https://www.facebook.com/groups/ateistiskselskab/permalink/10154930137678856/

It thinks you need to log in - which is clearly not true.

**Comment by yan12125** [comment]
@ole-tange That's a different bug. Could you open a new issue?

**Comment by mcepl** [comment]
Is this the same as mine problem?

```
fun~$ youtube-dl --verbose 'https://www.facebook.com/reel/1463302304499951'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.facebook.com/reel/1463302304499951']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.11.3 (CPython) - Linux-6.3.9-1-default-x86_64-with-glibc2.37
[debug] exe versions: ffmpeg 6.0, ffprobe 6.0
[debug] Proxy map: {}
[generic] 1463302304499951: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 1463302304499951: Downloading webpage
[generic] 1463302304499951: Extracting information
[generic] 1463302304499951: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 1463302304499951: Downloading webpage
[generic] 1463302304499951: Extracting information
[redirect] Following redirect to https://www.facebook.com/plugins/video.php?height=1920&width=1080&href=%2F100013522218132%2Fvideos%2Fmassive-us-aircraft-carrier-in-waters-of-split-croatia-with-70-planes-that-can-r%2F1463302304499951%2F&_fb_noscript=1
[generic] video: Requesting header
WARNING: Falling back on generic information extractor.
[generic] video: Downloading webpage
[generic] video: Extracting information
ERROR: Unsupported URL: https://www.facebook.com/plugins/video.php?height=1920&width=1080&href=%2F100013522218132%2Fvideos%2Fmassive-us-aircraft-carrier-in-waters-of-split-croatia-with-70-planes-that-can-r%2F1463302304499951%2F&_fb_noscript=1
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3489, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.facebook.com/plugins/video.php?height=1920&width=1080&href=%2F100013522218132%2Fvideos%2Fmassive-us-aircraft-carrier-in-waters-of-split-croatia-with-70-planes-that-can-r%2F1463302304499951%2F&_fb_noscript=1

fun~$ 
```

**Comment by mcepl** [comment]
@dirkf Thank you, that really makes youtube-dl working for me again! Passed it [to the openSUSE package](https://build.opensuse.org/request/show/1096011).
