### ISSUE TITLE
[generic] struct.error at http://www.americancrisis.us/video.php

### ISSUE THREAD

**Issue by thpublic** [rg3/youtube-dl#10804]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.09.27*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X ] I've **verified** and **I assure** that I'm running youtube-dl **2016.09.27**

### Before submitting an *issue* make sure you have:
- [X ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
./youtube-dl -F -v http://www.americancrisis.us/video.php
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-F', u'-v', u'http://www.americancrisis.us/video.php']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.09.27
[debug] Python version 2.7.6 - Linux-3.19.0-32-generic-i686-with-LinuxMint-17.3-rosa
[debug] exe versions: avconv 9.18-6, avprobe 9.18-6
[debug] Proxy map: {}
[generic] video: Requesting header
WARNING: Falling back on generic information extractor.
[generic] video: Downloading webpage
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "./youtube-dl/__main__.py", line 19, in <module>
  File "./youtube-dl/youtube_dl/__init__.py", line 449, in main
  File "./youtube-dl/youtube_dl/__init__.py", line 439, in _real_main
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 1791, in download
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 694, in extract_info
  File "./youtube-dl/youtube_dl/extractor/common.py", line 355, in extract
  File "./youtube-dl/youtube_dl/extractor/generic.py", line 1621, in _real_extract
  File "./youtube-dl/youtube_dl/extractor/common.py", line 402, in _request_webpage
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 2001, in urlopen
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "./youtube-dl/youtube_dl/utils.py", line 909, in http_response
  File "/usr/lib/python2.7/gzip.py", line 254, in read
    self._read(readsize)
  File "/usr/lib/python2.7/gzip.py", line 296, in _read
    self._read_gzip_header()
  File "/usr/lib/python2.7/gzip.py", line 195, in _read_gzip_header
    self.mtime = read32(self.fileobj)
  File "/usr/lib/python2.7/gzip.py", line 25, in read32
    return struct.unpack("<I", input.read(4))[0]
struct.error: unpack requires a string argument of length 4


```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://www.americancrisis.us/video.php

---

### Description of your *issue*, suggested solution and other information

Two resolutions at website.  Expected file listing (-F) with [generic] mode to determine which resolution to retrieve, got traceback error.

**Comment by yan12125** [comment]
Can't reproduce. Could you try again? Maybe they have fixed their server.

**Comment by Animis09** [comment]
Same issue here.

youtube-dl -v http://www.playhd.video/video/667/jithan-2
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.playhd.video/video/667/jithan-2']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.10.07
[debug] Proxy map: {}
[generic] jithan-2: Requesting header
WARNING: Falling back on generic information extractor.
[generic] jithan-2: Downloading webpage
[generic] jithan-2: Extracting information
[download] Downloading playlist: None
[generic] playlist None: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[debug] Invoking downloader on u'http://www.playhd.video/media/videos/iphone/667.mp4'
Traceback (most recent call last):
File "/usr/lib/python2.7/runpy.py", line 162, in run_module_as_main
"__main_", fname, loader, pkg_name)
File "/usr/lib/python2.7/runpy.py", line 72, in run_code
exec code in run_globals
File "/usr/local/bin/youtube-dl/__main_.py", line 19, in 
File "/usr/local/bin/youtube-dl/youtube_dl/init.py", line 445, in main
File "/usr/local/bin/youtube-dl/youtube_dl/init.py", line 435, in _real_main
File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1791, in download
File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 705, in extract_info
File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 866, in process_ie_result
File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 751, in process_ie_result
File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1435, in process_video_result
File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1699, in process_info
File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1641, in dl
File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 354, in download
File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 61, in real_download
File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2001, in urlopen
File "/usr/lib/python2.7/urllib2.py", line 407, in open
response = meth(req, response)
File "/usr/lib/python2.7/urllib2.py", line 520, in http_response
'http', request, response, code, msg, hdrs)
File "/usr/lib/python2.7/urllib2.py", line 439, in error
result = self._call_chain(args)
File "/usr/lib/python2.7/urllib2.py", line 379, in _call_chain
result = func(args)
File "/usr/lib/python2.7/urllib2.py", line 626, in http_error_302
return self.parent.open(new, timeout=req.timeout)
File "/usr/lib/python2.7/urllib2.py", line 407, in open
response = meth(req, response)
File "/usr/lib/python2.7/urllib2.py", line 520, in http_response
'http', request, response, code, msg, hdrs)
File "/usr/lib/python2.7/urllib2.py", line 439, in error
result = self._call_chain(args)
File "/usr/lib/python2.7/urllib2.py", line 379, in _call_chain
result = func(args)
File "/usr/lib/python2.7/urllib2.py", line 626, in http_error_302
return self.parent.open(new, timeout=req.timeout)
File "/usr/lib/python2.7/urllib2.py", line 407, in open
response = meth(req, response)
File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 925, in http_response
File "/usr/lib/python2.7/gzip.py", line 249, in read
self._read(readsize)
File "/usr/lib/python2.7/gzip.py", line 320, in _read
self._read_eof()
File "/usr/lib/python2.7/gzip.py", line 339, in _read_eof
isize = read32(self.fileobj) # may exceed 2GB
File "/usr/lib/python2.7/gzip.py", line 25, in read32
return struct.unpack("<I", input.read(4))[0]
struct.error: unpack requires a string argument of length 4
