### ISSUE TITLE
FootyRoom not working

### ISSUE THREAD

**Issue by tnmannen** [rg3/youtube-dl#10810]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.09.27*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.09.27**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
---

```
youtube-dl http://footyroom.com/matches/79927508/roma-vs-astra-giurgiu/review -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://footyroom.com/matches/79927508/roma-vs-astra-giurgiu/review', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.09.27
[debug] Python version 2.7.12 - Linux-4.4.0-38-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.6-1ubuntu2, ffprobe 2.8.6-1ubuntu2, rtmpdump 2.4
[debug] Proxy map: {}
[FootyRoom] matches: Downloading webpage
[download] Downloading playlist: VIDEO Roma 4 - 0 Astra Giurgiu
[FootyRoom] playlist VIDEO Roma 4 - 0 Astra Giurgiu: Collected 0 video ids (downloading 0 of them)
[download] Finished downloading playlist: VIDEO Roma 4 - 0 Astra Giurgiu
```
---
Nothing is downloaded..

**Comment by yan12125** [comment]
On that page:
```
We could not find anything for this match. Please accept our apology. If you are a producer of original content and would like to have it featured here or have a suggestion where to find some, please write to us.
```
I guess the video was removed in the last 10 days?

**Comment by tnmannen** [comment]
Seems to be so..
Did new try with other video from their page http://footyroom.com/matches/79922154/hull-city-vs-chelsea/review and got another error:

```
youtube-dl http://footyroom.com/matches/79922154/hull-city-vs-chelsea/review -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://footyroom.com/matches/79922154/hull-city-vs-chelsea/review', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.10.07
[debug] Python version 2.7.12 - Linux-4.4.0-38-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.6-1ubuntu2, ffprobe 2.8.6-1ubuntu2, rtmpdump 2.4
[debug] Proxy map: {}
[FootyRoom] matches: Downloading webpage
ERROR: Unable to extract video selector; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 356, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/footyroom.py", line 33, in _real_extract
    r'VideoSelector\.load\((\[.+?\])\);', webpage, 'video selector'),
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 659, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video selector; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

My point here being that the extractor seems to be broken..

**Comment by yan12125** [comment]
Thanks for the feedback! This site will be fixed in the next version.
