### ISSUE TITLE
[ComedyCentral] Unable to extract mgid

### ISSUE THREAD

**Issue by mcepl** [rg3/youtube-dl#10821]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.09.27**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Bug report (encountered problems with youtube-dl)
---
```
matej@mitmanek: ~$ youtube-dl --verbose 'http://www.cc.com/episodes/18dju4/the-colbert-report-june-30--2011---timothy-garton-ash-season-7-ep-07086'[debug] System config: [u'--prefer-free-formats']
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.cc.com/episodes/18dju4/the-colbert-report-june-30--2011---timothy-garton-ash-season-7-ep-07086']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.09.27
[debug] Python version 2.7.5 - Linux-3.10.0-509.el7.x86_64-x86_64-with-redhat-7.3-Maipo
[debug] exe versions: ffmpeg 3.1.3-static, ffprobe 2.6.8, rtmpdump 2.4
[debug] Proxy map: {}
[ComedyCentral] the-colbert-report-june-30--2011---timothy-garton-ash-season-7-ep-07086: Downloading webpage
ERROR: Unable to extract mgid; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/mtv.py", line 208, in _extract_mgid
    og_url = self._og_search_video_url(webpage)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 776, in _og_search_video_url
    return self._html_search_regex(regexes, html, name, **kargs)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 667, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 658, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 355, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/mtv.py", line 230, in _real_extract
    mgid = self._extract_mgid(webpage)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/mtv.py", line 224, in _extract_mgid
    r'embed/(mgid:.+?)["\'&?/]', sm4_embed, 'mgid')
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 658, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract mgid; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

matej@mitmanek: ~$
```

**Comment by dstftw** [comment]
There is no video on this page.
