### ISSUE TITLE
thisoldhouse.com has changed their video urls

### ISSUE THREAD

**Issue by jcollie** [rg3/youtube-dl#10837]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.10.02*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2016.10.02**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ ~/.local/bin/youtube-dl https://www.thisoldhouse.com/watch/episode-101
[generic] episode-101: Requesting header
WARNING: Falling back on generic information extractor.
[generic] episode-101: Downloading webpage
[generic] episode-101: Extracting information
ERROR: Unsupported URL: https://www.thisoldhouse.com/watch/episode-101
[jeff@home02 ~]$ ~/.local/bin/youtube-dl -v https://www.thisoldhouse.com/watch/episode-101
[debug] System config: [u'--prefer-free-formats']
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://www.thisoldhouse.com/watch/episode-101']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.10.02
[debug] Python version 2.7.12 - Linux-4.8.0-0.rc8.git0.1.fc25.x86_64-x86_64-with-fedora-25-Twenty_Five
[debug] exe versions: ffmpeg 3.1.3, ffprobe 3.1.3
[debug] Proxy map: {}
[generic] episode-101: Requesting header
WARNING: Falling back on generic information extractor.
[generic] episode-101: Downloading webpage
[generic] episode-101: Extracting information
ERROR: Unsupported URL: https://www.thisoldhouse.com/watch/episode-101
Traceback (most recent call last):
  File "/home/jeff/.local/lib/python2.7/site-packages/youtube_dl/extractor/generic.py", line 1649, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/home/jeff/.local/lib/python2.7/site-packages/youtube_dl/compat.py", line 2525, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/home/jeff/.local/lib/python2.7/site-packages/youtube_dl/compat.py", line 2514, in _XML
    parser.feed(text)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 14, column 375
Traceback (most recent call last):
  File "/home/jeff/.local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/home/jeff/.local/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 355, in extract
    return self._real_extract(url)
  File "/home/jeff/.local/lib/python2.7/site-packages/youtube_dl/extractor/generic.py", line 2432, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.thisoldhouse.com/watch/episode-101

```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.thisoldhouse.com/watch/arlington-arts-crafts-arts-and-crafts-class-begins
- Single video: https://www.thisoldhouse.com/watch/episode-101
---

### Description of your *issue*, suggested solution and other information

thisoldhouse.com has revamped their website so videos are access via different URLs now.

**Comment by jcollie** [comment]
Thanks!
