### ISSUE TITLE
Unable to download WACC's Vimeo videos.

### ISSUE THREAD

**Issue by antdude** [rg3/youtube-dl#10834]
Example from http://wacc.tv:

$ youtube-dl -v "https://player.vimeo.com/video/185229261?title=0&byline=0&portrait=0&autoplay=1"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'https://player.vimeo.com/video/185229261?title=0&byline=0&portrait=0&autoplay=1']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.10.02
[debug] Python version 3.4.2 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.6
[debug] exe versions: ffmpeg 3.1.3-1, ffprobe 3.1.3-1, rtmpdump 2.4
[debug] Proxy map: {}
[vimeo] 185229261: Downloading webpage
ERROR: Cannot download embed-only video without embedding URL. Please call youtube-dl with the URL of the page that embeds this video.
Traceback (most recent call last):
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/common.py", line 402, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2001, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 461, in open
    response = meth(req, response)
  File "/usr/lib/python3.4/urllib/request.py", line 571, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.4/urllib/request.py", line 499, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 433, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 579, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/vimeo.py", line 412, in _real_extract
    webpage = self._download_webpage(request, video_id)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/common.py", line 515, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/common.py", line 422, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/common.py", line 411, in _request_webpage
    raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
youtube_dl.utils.ExtractorError: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/common.py", line 402, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2001, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 461, in open
    response = meth(req, response)
  File "/usr/lib/python3.4/urllib/request.py", line 571, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.4/urllib/request.py", line 499, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 433, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 579, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/vimeo.py", line 412, in _real_extract
    webpage = self._download_webpage(request, video_id)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/common.py", line 515, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/common.py", line 422, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/common.py", line 411, in _request_webpage
    raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
youtube_dl.utils.ExtractorError: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/common.py", line 355, in extract
    return self._real_extract(url)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/vimeo.py", line 421, in _real_extract
    expected=True)
youtube_dl.utils.ExtractorError: Cannot download embed-only video without embedding URL. Please call youtube-dl with the URL of the page that embeds this video.

Thank you in advance. :)

**Comment by dstftw** [comment]
`--referer http://wacc.aspireonemedia.com/`.

**Comment by antdude** [comment]
Thanks dstftw! Dang, all these video sites are getting strict!
