### ISSUE TITLE
Broken arte links

### ISSUE THREAD

**Issue by sieben** [rg3/youtube-dl#10863]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.10.02*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.10.02**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

```
$ youtube-dl -v -t "http://www.arte.tv/guide/fr/038373-000-A/la-langue-cachee-d-amazonie?country=FR"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'-t', u'http://www.arte.tv/guide/fr/038373-000-A/la-langue-cachee-d-amazonie?country=FR']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.10.02
[debug] Python version 2.7.12 - Linux-4.4.0-38-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.6-1ubuntu2, ffprobe 2.8.6-1ubuntu2
[debug] Proxy map: {}
[arte.tv:+7] la-langue-cachee-d-amazonie: Downloading webpage
[arte.tv:+7] la-langue-cachee-d-amazonie: Downloading JSON metadata
Traceback (most recent call last):
  File "/home/sieben/.local/bin/youtube-dl", line 11, in <module>
    sys.exit(main())
  File "/home/sieben/.local/lib/python2.7/site-packages/youtube_dl/__init__.py", line 445, in main
    _real_main(argv)
  File "/home/sieben/.local/lib/python2.7/site-packages/youtube_dl/__init__.py", line 435, in _real_main
    retcode = ydl.download(all_urls)
  File "/home/sieben/.local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 1791, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/home/sieben/.local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/home/sieben/.local/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 355, in extract
    return self._real_extract(url)
  File "/home/sieben/.local/lib/python2.7/site-packages/youtube_dl/extractor/arte.py", line 200, in _real_extract
    return self._extract_from_webpage(webpage, video_id, lang)
  File "/home/sieben/.local/lib/python2.7/site-packages/youtube_dl/extractor/arte.py", line 243, in _extract_from_webpage
    return self._extract_from_json_url(json_url, video_id, lang, title=title)
  File "/home/sieben/.local/lib/python2.7/site-packages/youtube_dl/extractor/arte.py", line 110, in _extract_from_json_url
    for format_id, format_dict in player_info['VSR'].items():
AttributeError: 'list' object has no attribute 'items'
```

**Comment by dstftw** [comment]
There is no video on this page.
