### ISSUE TITLE
BBC no JSON object could be decoded

### ISSUE THREAD

**Issue by surgeio** [rg3/youtube-dl#10873]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.10.07**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```

[steve@ando BBC]$ python2.7 ~/youtube-dl/youtube-dl --verbose --proxy="46.101.19.214:80" http://www.bbc.co.uk/iplayer/episode/b07ypgc4
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'--proxy=46.101.19.214:80', u'http://www.bbc.co.uk/iplayer/episode/b07ypgc4']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.10.07
[debug] Python version 2.7.2 - Linux-2.6.18-407.el5-i686-with-redhat-5.11-Final
[debug] exe versions: avconv 11.7, avprobe 11.7, ffmpeg 0.6.5, ffprobe 0.6.5
[debug] Proxy map: {u'http': u'46.101.19.214:80', u'https': u'46.101.19.214:80'}
[bbc.co.uk] b07ypgc4: Downloading video page
[bbc.co.uk] b07ypgc4: Downloading playlist JSON
ERROR: b07ypgc4: Failed to parse JSON  (caused by ValueError('No JSON object could be decoded',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/steve/youtube-dl/youtube-dl/youtube_dl/extractor/common.py", line 558, in _parse_json
    return json.loads(json_string)
  File "/usr/local/lib/python2.7/json/__init__.py", line 326, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Traceback (most recent call last):
  File "/home/steve/youtube-dl/youtube-dl/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/home/steve/youtube-dl/youtube-dl/youtube_dl/extractor/common.py", line 356, in extract
    return self._real_extract(url)
  File "/home/steve/youtube-dl/youtube-dl/youtube_dl/extractor/bbc.py", line 501, in _real_extract
    programme_id, title, description, duration, formats, subtitles = self._download_playlist(group_id)
  File "/home/steve/youtube-dl/youtube-dl/youtube_dl/extractor/bbc.py", line 390, in _download_playlist
    playlist_id, 'Downloading playlist JSON')
  File "/home/steve/youtube-dl/youtube-dl/youtube_dl/extractor/common.py", line 552, in _download_json
    json_string, video_id, transform_source=transform_source, fatal=fatal)
  File "/home/steve/youtube-dl/youtube-dl/youtube_dl/extractor/common.py", line 562, in _parse_json
    raise ExtractorError(errmsg, cause=ve)
ExtractorError: b07ypgc4: Failed to parse JSON  (caused by ValueError('No JSON object could be decoded',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


```

---

### Description of your *issue*, suggested solution and other information

Downloading from BBC iplayer URLs seems to have stopped working some time in the last month or two. Downloading *was* working a month or two ago (I don't remember the exact date) but now gives a JSON error "No JSON object could be decoded".

**Comment by surgeio** [comment]
I forgot to mention -- I've tried using different proxies, and get the same error.

**Comment by remitamine** [comment]
it a problem in the proxy not youtube-dl:
```
youtube-dl http://www.bbc.co.uk/iplayer/episode/b07ypgc4
[bbc.co.uk] b07ypgc4: Downloading video page
[bbc.co.uk] b07ypcf1: Downloading media selection XML
[bbc.co.uk] b07ypcf1: Downloading m3u8 information
[bbc.co.uk] b07ypcf1: Downloading MPD manifest
[bbc.co.uk] b07ypcf1: Downloading m3u8 information
[bbc.co.uk] b07ypcf1: Downloading MPD manifest
[bbc.co.uk] b07ypcf1: Downloading m3u8 information
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 88
[download] Destination: Danger Mouse, 39. The Cute Shall Inherit the Earth-b07ypcf1.mp4
[download]   0.1% of ~423.63MiB at 165.94KiB/s ETA 58:12
```
the proxy you're using return a phpinfo webpage instead of the video webpage.
