### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by AndMunich** [rg3/youtube-dl#10889]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.10.07*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ ] I've **verified** and **I assure** that I'm running youtube-dl **2016.10.07**

### Before submitting an *issue* make sure you have:
- [ ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.10.07
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

**Comment by yan12125** [comment]
"Connection reset by peer" does not provide much information. Please include the output of
```
youtube-dl -v <your video URL>
```

**Comment by AndMunich** [comment]
Hello, here comes the "-v" text:

"andrew@PhileasFogg:~$ sudo youtube-dl -U
[sudo] password for andrew: 
Updating to version 2016.10.07 ...
Updated youtube-dl. Restart youtube-dl to use the new version.
andrew@PhileasFogg:~$ sudo youtube-dl --verbose "https://www.youtube.com/watch?feature=player_embedded&v=Kr1p7tDfEIA"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://www.youtube.com/watch?feature=player_embedded&v=Kr1p7tDfEIA']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.10.07
[debug] Python version 2.7.12 - Linux-4.4.0-38-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 2.8.6-1ubuntu2, avprobe 2.8.6-1ubuntu2, ffmpeg 2.8.6-1ubuntu2, ffprobe 2.8.6-1ubuntu2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] Kr1p7tDfEIA: Downloading webpage
[youtube] Kr1p7tDfEIA: Downloading video info webpage
[youtube] Kr1p7tDfEIA: Extracting video information
[youtube] Kr1p7tDfEIA: Downloading MPD manifest
[youtube] Kr1p7tDfEIA: Downloading MPD manifest
[debug] Invoking downloader on u'https://r2---sn-i5onxoxu-4g5e.googlevideo.com/videoplayback/id/2abd69eed0df1080/itag/137/source/youtube/requiressl/yes/initcwndbps/787500/mm/31/mn/sn-i5onxoxu-4g5e/pl/21/ms/au/mv/m/ratebypass/yes/mime/video%2Fmp4/otfp/1/gir/yes/clen/1213908464/lmt/1475943420704604/dur/2300.320/signature/6A8A14B972C89B4FE13CE45CE2DC65A1E860F835.60873C8DF302F57B6F67DBD240EDDF2285129EDE/mt/1475960804/upn/MEA1pfsHX8k/key/dg_yt0/ip/89.204.135.1/ipbits/0/expire/1475982852/sparams/ip,ipbits,expire,id,itag,source,requiressl,initcwndbps,mm,mn,pl,ms,mv,ratebypass,mime,otfp,gir,clen,lmt,dur/'
[dashsegments] Total fragments: 451
[download] Destination: Viehschauen Schangnau 2016 am 4. + 6. Oktober-Kr1p7tDfEIA.f137.mp4
[download]  59.2% of ~1.12GiB at 688.68KiB/s ETA 15:32ERROR: unable to download video data: <urlopen error [Errno 104] Connection reset by peer>
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1693, in process_info
    partial_success = dl(fname, new_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1641, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 354, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/dash.py", line 73, in real_download
    if not process_segment(segment, ctx['tmpfilename'], i):
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/dash.py", line 46, in process_segment
    success = ctx['dl'].download(target_filename, {'url': segment_url})
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 354, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 61, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2001, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 467, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 654, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 467, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 654, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1034, in https_open
    req, **kwargs)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 104] Connection reset by peer>

andrew@PhileasFogg:~$ 

Now 269 parts of that video file are left here (1.3 GB). Can I bind those in one mp4-file? Or do I just have to delete them all?

Thanks, Andreas

**Comment by yan12125** [comment]
> Can I bind those in one mp4-file? 

FYI: Those *.part files are already copied to ```Viehschauen Schangnau 2016 am 4. + 6. Oktober-Kr1p7tDfEIA.f137.mp4.part```

**Comment by AndMunich** [comment]
Sorry, no, they are not. Shall I send a list with their sizes?

**Comment by yan12125** [comment]
Hmm there's a bug if they are not in the ```.part``` file.

You can also ```cat``` all files to get the combined mp4. Note that the order should be correct (Frag0, Frag1, Frag2, ...)

**Comment by AndMunich** [comment]
Oh, yes, they are! Sorry!

**Comment by AndMunich** [comment]
So, I just remove '.part' from that file, then I'm done, ya?

**Comment by yan12125** [comment]
Yes you got it.

**Comment by AndMunich** [comment]
Why was it interrupted? Any explanation available?

**Comment by AndMunich** [comment]
Youtube-Police?

**Comment by AndMunich** [comment]
Or my dear provider?

**Comment by yan12125** [comment]
Most likely a network issue. Either on YouTube side or your side. If YouTube want to ban you, they response 429 instead.

**Comment by AndMunich** [comment]
Okay, thanks so much, Yan!

**Comment by yan12125** [comment]
My download is finished. Could you try again?

**Comment by AndMunich** [comment]
I know about the reason of the 'resetting': My connection is a mobile one by O2, a German side of the Spanish Telefonica, and they cut off the internet connection from time to time. I am having often that problem. Torrent software can handle such 'interruptions', youtube-dl probably can not. I'll look first in that part, I already have and then decide, if I start a download again. Thank you so much!

**Comment by AndMunich** [comment]
I have seen enough: None of the cows are mine, my part has no sound, that's a pity. It must be one of the newest high resolutions, because it is slow motion only here. thanks again!

**Comment by yan12125** [comment]
The whole process is interrupted when downloading bestvideo. You'll need to download bestaudio and merge them.

**Comment by AndMunich** [comment]
---------------------------------------------------------------------
Ab-Sender:
Andreas H. Mardersteig
Kiem-Pauli-Weg 9
80686  Muenchen
Telefon: 0179/9581299
Telefax: 089/99964236
E-Mail: andreastec11@andmunich.net
---------------------------------------------------------------------





Ok, thanks, I'll dive into that, when I get play-time! Danke!


Am Sun, 09 Oct 2016 09:38:46 -0700 erhielt ich von
notifications@github.com das Folgende zum Thema: Re:
[rg3/youtube-dl] Connection reset by peer (#10889)

On Sun, 09 Oct 2016 09:38:46 -0700, notifications@github.com had
sent me the following on the subject: Re: [rg3/youtube-dl]
Connection reset by peer (#10889)


>>: The whole process is interrupted when downloading bestvideo.
>>: You'll need to download bestaudio and merge them.
>>: 
>>: -- 
>>: You are receiving this because you authored the thread.
>>: Reply to this email directly or view it on GitHub:
>>: https://github.com/rg3/youtube-dl/issues/10889#issuecomment-252496987

"--" 
If we have no problems at all, we tend to create some ...
---------------------------------------------------------------------

**Comment by mpenkov** [comment]
This seems to work flawlessly on 2018.03.14, so I think this issue may be closed now.
