### ISSUE TITLE
ERROR: Signature extraction failed

### ISSUE THREAD

**Issue by runlevelsix** [rg3/youtube-dl#10902]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.10.07**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)

### verbose output
```
$ youtube-dl -v -f 'bestvideo[height<=720]+bestaudio/best[height<=720]' https://www.youtube.com/playlist?list=PLgCM33LYxWKNntNq7vjpSFtuSU5rHZBJG
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'-f', u'bestvideo[height<=720]+bestaudio/best[height<=720]', u'https://www.youtube.com/playlist?list=PLgCM33LYxWKNntNq7vjpSFtuSU5rHZBJG']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.10.07
[debug] Python version 2.7.12 - Darwin-15.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.1.3, ffprobe 3.1.3, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:playlist] PLgCM33LYxWKNntNq7vjpSFtuSU5rHZBJG: Downloading webpage
[download] Downloading playlist: UtahJS 2016
[youtube:playlist] playlist UtahJS 2016: Downloading 34 videos
[download] Downloading video 1 of 34
[youtube] OnkYnm-WiVo: Downloading webpage
[youtube] OnkYnm-WiVo: Downloading video info webpage
[youtube] OnkYnm-WiVo: Extracting video information
[youtube] OnkYnm-WiVo: Downloading MPD manifest
[download] Visual Studio Code The last editor you'll ever need - Wade Anderson-OnkYnm-WiVo.mp4 has already been downloaded and merged
[download] Downloading video 2 of 34
[youtube] MdOhEalZ-0Q: Downloading webpage
[youtube] MdOhEalZ-0Q: Downloading video info webpage
[youtube] MdOhEalZ-0Q: Extracting video information
[youtube] MdOhEalZ-0Q: Downloading MPD manifest
[youtube] MdOhEalZ-0Q: Downloading MPD manifest
[download] Utah JS Giveaways & Closing Remarks-MdOhEalZ-0Q.mp4 has already been downloaded and merged
[download] Downloading video 3 of 34
[youtube] MYYUVTxtA8Q: Downloading webpage
[youtube] MYYUVTxtA8Q: Downloading video info webpage
[youtube] MYYUVTxtA8Q: Extracting video information
[youtube] MYYUVTxtA8Q: Downloading MPD manifest
[download] Angular 2 Material Design and Angular CLI - Hans Larsen-MYYUVTxtA8Q.mp4 has already been downloaded and merged
[download] Downloading video 4 of 34
[youtube] L2Ke1wf7xqk: Downloading webpage
[youtube] L2Ke1wf7xqk: Downloading video info webpage
[youtube] L2Ke1wf7xqk: Extracting video information
[youtube] {22} signature length 42.43, html5 player en_US-vflQcYs5w
[youtube] L2Ke1wf7xqk: Downloading player https://s.ytimg.com/yts/jsbin/player-en_US-vflQcYs5w/base.js
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1005, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 919, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 516, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 423, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 412, in _request_webpage
    raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
ExtractorError: Download of https://s.ytimg.com/yts/jsbin/player-en_US-vflQcYs5w/base.js failed: ('The read operation timed out',) (caused by SSLError('The read operation timed out',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Download of https://s.ytimg.com/yts/jsbin/player-en_US-vflQcYs5w/base.js failed: ('The read operation timed out',) (caused by SSLError('The read operation timed out',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1005, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 919, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 516, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 423, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 412, in _request_webpage
    raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
ExtractorError: Download of https://s.ytimg.com/yts/jsbin/player-en_US-vflQcYs5w/base.js failed: ('The read operation timed out',) (caused by SSLError('The read operation timed out',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 356, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1584, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1015, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1005, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 919, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 516, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 423, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 412, in _request_webpage
    raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
ExtractorError: Download of https://s.ytimg.com/yts/jsbin/player-en_US-vflQcYs5w/base.js failed: ('The read operation timed out',) (caused by SSLError('The read operation timed out',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Download of https://s.ytimg.com/yts/jsbin/player-en_US-vflQcYs5w/base.js failed: ('The read operation timed out',) (caused by SSLError('The read operation timed out',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```
---

### Description of your *issue*, suggested solution and other information

Using the latest version of youtube-dl, I get the above errors (highlighted below):

* Signature extraction failed (because of ...)
* ExtractorError: Download of https://s.ytimg.com/yts/jsbin/player-en_US-vflQcYs5w/base.js failed: ('The read operation timed out',) (caused by SSLError('The read operation timed out',))

**Comment by yan12125** [comment]
> The read operation timed out

Most likely it's a network issue. Could you try again later?

**Comment by runlevelsix** [comment]
I've tried on two different days (12 hours apart or so) with the same errors. The file `base.js` appears to be downloadable via the browser - can it be copied into a youtube-dl cache directory?

**Comment by runlevelsix** [comment]
Ok, weird, I just tried again and it's working.
