### ISSUE TITLE
Download problem using youtube-dl at www.svtplay.se

### ISSUE THREAD

**Issue by peterkry** [rg3/youtube-dl#10940]
Possible youtube-dl bug or svtplay database problem
Problems retrieving videos (files) from svtplay (www.svtplay.se). After contacting the site and downloading initial info it only retrieves a couple of MB (should be around GB) for the following videos Millenium part 5 and 6 as well as 56orna part 2, 3, etc. Then the merge process fails.
Output from youtube-dl with --verbose, namely

> [debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.svtplay.se/video/2279502/millennium']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.10.16
[debug] Python version 2.7.12 - Linux-3.16.7-42-desktop-x86_64-with-SuSE-13.2-x86_64
[debug] exe versions: ffmpeg 3.0.2, ffprobe 3.0.2
[debug] Proxy map: {}
[SVTPlay] 2279502: Downloading webpage
[SVTPlay] 1122946-006A: Downloading JSON metadata
[SVTPlay] 1122946-006A: Downloading m3u8 information
[SVTPlay] 1122946-006A: Downloading m3u8 information
[SVTPlay] 1122946-006A: Downloading MPD manifest
[SVTPlay] 1122946-006A: Downloading f4m manifest
[debug] Invoking downloader on u'http://svtplay3r-f.akamaihd.net/d/se/open/delivery/20161007/1122946-006A/dash-live/PG-1122946-006A-MILLENNIUMTVSERI-02-1a894f3d-e7aa-336d-472e-56993a27cd04-live.mpd?alt=http://switcher.cdn.svt.se/./'
[dashsegments] Total fragments: 896
[download] Destination: Avsnitt 6-1122946-006A.fdashhbbtv-PG-1122946-006A-MILLENNIUMTVSERI-02_2796_1.mp4
[download] 100% of 2.66MiB in 00:06
[debug] Invoking downloader on u'http://svtplay3r-f.akamaihd.net/d/se/open/delivery/20161007/1122946-006A/dash-live/PG-1122946-006A-MILLENNIUMTVSERI-02-1a894f3d-e7aa-336d-472e-56993a27cd04-live.mpd?alt=http://switcher.cdn.svt.se/./'
[dashsegments] Total fragments: 894
[download] Destination: Avsnitt 6-1122946-006A.fdashhbbtv-PG-1122946-006A-MILLENNIUMTVSERI-02_988_2.m4a
[download] 100% of 2.65MiB in 00:07
[ffmpeg] Merging formats into "Avsnitt 6-1122946-006A.mp4"
[debug] ffmpeg command line: ffmpeg -y -i 'file:Avsnitt 6-1122946-006A.fdashhbbtv-PG-1122946-006A-MILLENNIUMTVSERI-02_2796_1.mp4' -i 'file:Avsnitt 6-1122946-006A.fdashhbbtv-PG-1122946-006A-MILLENNIUMTVSERI-02_988_2.m4a' -c copy -map 0:v:0 -map 1:a:0 'file:Avsnitt 6-1122946-006A.temp.mp4'
ERROR: file:Avsnitt 6-1122946-006A.fdashhbbtv-PG-1122946-006A-MILLENNIUMTVSERI-02_2796_1.mp4: Invalid data found when processing input
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1837, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 444, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/usr/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 192, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
FFmpegPostProcessorError

>

**Comment by b9AcE** [comment]
I have recently gotten problems with downloading news videos from svt.se (same organization and platform as svtplay.se) and they are definitely not geo-restricted.
What has seemed to work is removing the "--format best" that I normally have in my config-file and manually identifying the URL to the .mpd-file I want in the source code (both steps needed for success, it seems).
As I remember it, it used to just work until maybe a month ago.
An example: http://www.svt.se/nyheter/lokalt/stockholm/kraftig-brand-i-asylboende-i-sodra-stockholm

**Comment by yan12125** [comment]
http://www.svt.se/nyheter/lokalt/stockholm/kraftig-brand-i-asylboende-i-sodra-stockholm is geo-restricted, too.
```
Programmet kan bara ses i Sverige
```

**Comment by norden1** [comment]
I leave in Sweden and I cant download from svtplay no more its have worked perfect earlier. The downloade file are just approx. 1.7 mb.

**Comment by 0880** [comment]
>http://www.svt.se/nyheter/lokalt/stockholm/kraftig-brand-i-asylboende-i-sodra-stockholm

There are two videos. The second one is accessible even outside of Sweden.

DASH manifest file:

```
http://svtklipp6a-vh.akamaihd.net/d/world/open/delivery/20161016/R-2016-1016-SAGASYLBRAND/dash-live/R-2016-1016-SAGASYLBRAND-cc602291-6385-336d-c6f6-e553bc7180bb-live.mpd?alt=http://switcher.cdn.svt.se/R-2016-1016-SAGASYLBRAND.mpd
```
```
<MPD mediaPresentationDuration="PT22.806S" minBufferTime="PT2.00S" profiles="urn:hbbtv:dash:profile:isoff-live:2012,urn:mpeg:dash:profile:isoff-live:2011" type="static" xmlns="urn:mpeg:dash:schema:mpd:2011" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:mpeg:DASH:schema:MPD:2011 DASH-MPD.xsd">
  <BaseURL>./</BaseURL>
  <Period>
    <AdaptationSet contentType="video" mimeType="video/mp4" par="16:9" subsegmentAlignment="true" subsegmentStartsWithSAP="1">
      <SegmentTemplate initialization="$RepresentationID$/$RepresentationID$_00000.m4v" media="$RepresentationID$/$RepresentationID$_$Number%05d$.m4v" startNumber="1" timescale="25000">
        <SegmentTimeline>
          <S d="150000" t="0" />
          <S d="150000" r="1" />
          <S d="120000" />
        </SegmentTimeline>
      </SegmentTemplate>
      <Representation bandwidth="150665" codecs="avc1.42c015" frameRate="25" height="288" id="R-2016-1016-SAGASYLBRAND_240_1" sar="1:1" scanType="progressive" width="512" />
      <Representation bandwidth="944745" codecs="avc1.4d401e" frameRate="25" height="432" id="R-2016-1016-SAGASYLBRAND_988_1" sar="1:1" scanType="progressive" width="768" />
      <Representation bandwidth="1678202" codecs="avc1.4d401f" frameRate="25" height="576" id="R-2016-1016-SAGASYLBRAND_1680_1" sar="1:1" scanType="progressive" width="1024" />
      <Representation bandwidth="558340" codecs="avc1.42c015" frameRate="25" height="288" id="R-2016-1016-SAGASYLBRAND_636_1" sar="1:1" scanType="progressive" width="512" />
      <Representation bandwidth="261760" codecs="avc1.42c015" frameRate="25" height="288" id="R-2016-1016-SAGASYLBRAND_348_1" sar="1:1" scanType="progressive" width="512" />
      <Representation bandwidth="371768" codecs="avc1.42c015" frameRate="25" height="288" id="R-2016-1016-SAGASYLBRAND_456_1" sar="1:1" scanType="progressive" width="512" />
      <Representation bandwidth="2845469" codecs="avc1.64001f" frameRate="25" height="720" id="R-2016-1016-SAGASYLBRAND_2796_1" sar="1:1" scanType="progressive" width="1280" />
    </AdaptationSet>
    <AdaptationSet contentType="audio" mimeType="audio/mp4" subsegmentAlignment="true" subsegmentStartsWithSAP="1">
      <Accessibility schemeIdUri="urn:tva:metadata:cs:AudioPurposeCS:2007" value="6" />
      <Role schemeIdUri="urn:mpeg:dash:role:2011" value="main" />
      <SegmentTemplate initialization="$RepresentationID$/$RepresentationID$_00000.m4a" media="$RepresentationID$/$RepresentationID$_$Number%05d$.m4a" startNumber="1" timescale="48000">
        <SegmentTimeline>
          <S d="287744" t="0" />
          <S d="288768" r="1" />
          <S d="229376" />
        </SegmentTimeline>
      </SegmentTemplate>
      <Representation audioSamplingRate="48000" bandwidth="97305" codecs="mp4a.40.5" id="R-2016-1016-SAGASYLBRAND_636_2">
        <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2" />
      </Representation>
    </AdaptationSet>
  </Period>
</MPD>
```
```
youtube-dl --no-warnings "http://svtklipp6a-vh.akamaihd.net/d/world/open/delivery/20161016/R-2016-1016-SAGASYLBRAND/dash-live/R-2016-1016-SAGASYLBRAND-cc602291-6385-336d-c6f6-e553bc7180bb-live.mpd?alt=http://switcher.cdn.svt.se/R-2016-1016-SAGASYLBRAND.mpd"
[generic] R-2016-1016-SAGASYLBRAND: Requesting header
[generic] R-2016-1016-SAGASYLBRAND: Downloading webpage
[generic] R-2016-1016-SAGASYLBRAND: Extracting information
[dashsegments] Total fragments: 5
[download] Destination: R-2016-1016-SAGASYLBRAND-cc602291-6385-336d-c6f6-e553bc7180bb-live-R-2016-1016-SAGASYLBRAND.fR-2016-1016-SAGASYLBRAND-R-2016-1016-SAGASYLBRAND_2796_1.mp4
[download] 100% of 14.74KiB in 00:01
[dashsegments] Total fragments: 5
[download] Destination: R-2016-1016-SAGASYLBRAND-cc602291-6385-336d-c6f6-e553bc7180bb-live-R-2016-1016-SAGASYLBRAND.fR-2016-1016-SAGASYLBRAND-R-2016-1016-SAGASYLBRAND_636_2.m4a
[download] 100% of 14.74KiB in 00:01
[ffmpeg] Merging formats into "R-2016-1016-SAGASYLBRAND-cc602291-6385-336d-c6f6-e553bc7180bb-live-R-2016-1016-SAGASYLBRAND.mp4"
ERROR: file:R-2016-1016-SAGASYLBRAND-cc602291-6385-336d-c6f6-e553bc7180bb-live-R-2016-1016-SAGASYLBRAND.fR-2016-1016-SAGASYLBRAND-R-2016-1016-SAGASYLBRAND_2796_1.mp4: Invalid data found when processing input
```

Other examples:

http://www.svt.se/nyheter/lokalt/stockholm/den-ar-som-en-giljotin
http://www.svt.se/nyheter/lokalt/stockholm/350-id-kapningar-varje-dag

**Comment by yan12125** [comment]
Yeah that's a different bug reported at #10909

**Comment by norden1** [comment]
Its noy possible to download from this link either. What happens earlier it works fine to download from svtplay with Youtube dl but now it dosent work anymore. Please can someone fix that?
http://www.svtplay.se/video/10696487/veckans-brott/veckans-brott-sasong-13-avsnitt-1

**Comment by norden1** [comment]
Its still not working to download some files from svtplay
http://www.svtplay.se/video/10640214/om-ett-hjarta/om-ett-hjarta-sasong-1-avsnitt-1
