### ISSUE TITLE
ERROR: lynda returned error: Session has expired (with cookies)

### ISSUE THREAD

**Issue by AbsoluteZero273** [rg3/youtube-dl#10957]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.10.16*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.10.16**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl --cookies lyndacookie1.txt https://www.lynda.com/Python-tutorials/Distinguishing-mutable-immutable-objects/62226/70945-4.html?autoplay=true -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--cookies', u'lyndacookie1.txt', u'https://www.lynda.com/Python-tutorials/Distinguishing-mutable-immutable-objects/62226/70945-4.html?autoplay=true', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.10.16
[debug] Python version 2.7.12 - Linux-4.4.0-24-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 2.8.6-1ubuntu2, avprobe 2.8.6-1ubuntu2, ffmpeg 2.8.6-1ubuntu2, ffprobe 2.8.6-1ubuntu2, rtmpdump 2.4
[debug] Proxy map: {}
[lynda] 70945: Downloading video JSON
ERROR: lynda returned error: Session has expired
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 356, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/lynda.py", line 176, in _real_extract
    'lynda returned error: %s' % video['Message'], expected=True)
ExtractorError: lynda returned error: Session has expired
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

---

### Description of your *issue*, suggested solution and other information

I am using an organization login, and hence the cookies. I extracted cookies using Cookie Exporter 1.5.1-signed and added # Netscape HTTP Cookie File on top of file. I also replaced all `\r\n` with `\n` with a hex editor. I first tried downloading all of course but it only downloads free ones. Then I tried with an individual locked video, I am getting this error. And, yes I can play the video fine on the browser. Is it a bug or a problem in my command?

**Comment by dstftw** [comment]
Organization login is not supported. If it does not work with cookies there is not way to go.

**Comment by julioblas01** [comment]
This is also my problem, help with organization cookies.
