### ISSUE TITLE
CDA Error

### ISSUE THREAD

**Issue by tzji** [rg3/youtube-dl#10962]
```
$ youtube-dl -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.10.16
[debug] Python version 2.7.12 - Linux-4.4.0-43-generic-x86_64-with-LinuxMint-18-sarah
[debug] exe versions: ffmpeg 2.8.8-0ubuntu0.16.04.1, ffprobe 2.8.8-0ubuntu0.16.04.1
[debug] Proxy map: {}
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options.

$ youtube-dl http://www.cda.pl/video/........
[CDA] 955530d5: Downloading webpage
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 445, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 435, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1791, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 694, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 356, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/cda.py", line 82, in _real_extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/cda.py", line 59, in extract_format
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 3023, in decode_packed_codes
AttributeError: 'NoneType' object has no attribute 'groups'
```

**Comment by dstftw** [comment]
Duplicate of #10929.
