### ISSUE TITLE
[AdultSwim] No video formats found

### ISSUE THREAD

**Issue by stepshal** [rg3/youtube-dl#10977]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.10.19**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

```
[AdultSwim] dio-the-invader: Downloading webpage
[AdultSwim] YnqkxbrVRquUxiyo6Sr_Rw-0: Downloading XML
[AdultSwim] YnqkxbrVRquUxiyo6Sr_Rw-0: Downloading f4m manifest
WARNING: Unable to download f4m manifest: HTTP Error 403: Forbidden
[AdultSwim] YnqkxbrVRquUxiyo6Sr_Rw-0: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[AdultSwim] YnqkxbrVRquUxiyo6Sr_Rw-0: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/common.py", line 356, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/adultswim.py", line 187, in _real_extract
    'tokenizer_src': 'http://www.adultswim.com/astv/mvpd/processors/services/token_ipadAdobe.do',
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/turner.py", line 137, in _extract_cvp_info
    self._sort_formats(formats)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/common.py", line 923, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
http://www.adultswim.com/videos/jojos-bizarre-adventure/dio-the-invader/

**Comment by yan12125** [comment]
Can you watch this video in browsers?

**Comment by stepshal** [comment]
@yan12125 try to watch without adblock.

**Comment by yan12125** [comment]
Can you talk to "someone"? I can't play it on Firefox. Flash 23 beta installed. All blockers already disabled.

**Comment by remitamine** [comment]
the video is geo restricted, it works using a US IP:
```
youtube-dl http://www.adultswim.com/videos/jojos-bizarre-adventure/dio-the-invader/
[AdultSwim] dio-the-invader: Downloading webpage
[AdultSwim] YnqkxbrVRquUxiyo6Sr_Rw-0: Downloading XML
[AdultSwim] YnqkxbrVRquUxiyo6Sr_Rw-0: Downloading f4m manifest
[AdultSwim] YnqkxbrVRquUxiyo6Sr_Rw-0: Downloading f4m manifest
[AdultSwim] YnqkxbrVRquUxiyo6Sr_Rw-0: Downloading f4m manifest
WARNING: Unable to download f4m manifest: HTTP Error 404: Not Found
[AdultSwim] YnqkxbrVRquUxiyo6Sr_Rw-0: Downloading f4m manifest
WARNING: Unable to download f4m manifest: HTTP Error 404: Not Found
[AdultSwim] YnqkxbrVRquUxiyo6Sr_Rw-0: Downloading f4m manifest
WARNING: Unable to download f4m manifest: HTTP Error 404: Not Found
[AdultSwim] YnqkxbrVRquUxiyo6Sr_Rw-0: Downloading f4m manifest
WARNING: Unable to download f4m manifest: HTTP Error 404: Not Found
[AdultSwim] YnqkxbrVRquUxiyo6Sr_Rw-0: Downloading m3u8 information
[AdultSwim] YnqkxbrVRquUxiyo6Sr_Rw-0: Downloading m3u8 information
[download] Downloading playlist: JoJo's Bizarre Adventure - Dio the Invader
[AdultSwim] playlist JoJo's Bizarre Adventure - Dio the Invader: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[info] Writing video subtitles to: JoJo's Bizarre Adventure - Dio the Invader-YnqkxbrVRquUxiyo6Sr_Rw-0.en.vtt
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 128
[download] Destination: JoJo's Bizarre Adventure - Dio the Invader-YnqkxbrVRquUxiyo6Sr_Rw-0.mp4
[download]   0.1% of ~1.21GiB at 191.59KiB/s ETA 02:17:44
```
