### ISSUE TITLE
version - 2016.10.21 - URLError: <urlopen error unknown url type: {"urls">

### ISSUE THREAD

**Issue by DcsPeterDickten** [rg3/youtube-dl#10984]
## Please follow the guide below

- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.10.21**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)

---

the parameters are:
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'--min-filesize', u'50k', u'--autonumber-size', u'3', u'--username', u'PRIVATE', u'--password', u'PRIVATE', u'--sleep-interval', u'181', u'-o', u'./angular-2-getting-started-update/%(autonumber)s-%(title)s.%(ext)s', u'https://app.pluralsight.com/library/courses/angular-2-getting-started-update']
[debug] Encodings: locale UTF-8, fs utf-8, out None, pref UTF-8
[debug] youtube-dl version 2016.10.21
[debug] Python version 2.7.10 - Darwin-16.0.0-x86_64-i386-64bit
[debug] exe versions: avconv 11.4, avprobe 11.4, ffmpeg 3.1.4, ffprobe 3.1.4
[debug] Proxy map: {}

---

### the full verbose output as follows:

Running the latest version of youtube-dl with plural sight gives me this error:

ERROR: unable to download video data: <urlopen error unknown url type: {"urls">
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1699, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1641, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 353, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 61, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2001, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 454, in _open
    'unknown_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1265, in unknown_open
    raise URLError('unknown url type: %s' % type)
URLError: <urlopen error unknown url type: {"urls">
---

the url is 
https://app.pluralsight.com/library/courses/angular-2-getting-started-update

---

**Comment by SliceTap** [comment]
yes can confirm, i get the same error unknown urls
