### ISSUE TITLE
ValueError on litv.tv

### ISSUE THREAD

**Issue by casinero** [rg3/youtube-dl#11006]
youtube-dl.exe --no-playlist -v -J -i  https://www.litv.tv/vod/movie/content.do?id=VOD00039305
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--no-playlist', '-v', '-J', '-i', 'https://www.litv.tv/vod/movie/content.do?id=VOD00039305']
[debug] Encodings: locale cp950, fs mbcs, out cp950, pref cp950
[debug] youtube-dl version 2016.10.21.1
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-70348-g9564375, ffprobe N-70348-g9564375
[debug] Proxy map: {}
ERROR: VOD00039305: Failed to parse JSON  (caused by ValueError('Expecting value: line 1 column 1 (char 0)',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmphn9u2rzv\build\youtube_dl\extractor\common.py", line 558, in _parse_json
  File "C:\Python\Python34\lib\json\__init__.py", line 318, in loads
  File "C:\Python\Python34\lib\json\decoder.py", line 343, in decode
  File "C:\Python\Python34\lib\json\decoder.py", line 361, in raw_decode
ValueError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmphn9u2rzv\build\youtube_dl\extractor\common.py", line 558, in _parse_json
  File "C:\Python\Python34\lib\json\__init__.py", line 318, in loads
  File "C:\Python\Python34\lib\json\decoder.py", line 343, in decode
  File "C:\Python\Python34\lib\json\decoder.py", line 361, in raw_decode
ValueError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
null
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmphn9u2rzv\build\youtube_dl\YoutubeDL.py", line 694, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmphn9u2rzv\build\youtube_dl\extractor\common.py", line 356, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmphn9u2rzv\build\youtube_dl\extractor\litv.py", line 89, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmphn9u2rzv\build\youtube_dl\extractor\common.py", line 562, in _parse_json
youtube_dl.utils.ExtractorError: VOD00039305: Failed to parse JSON  (caused by ValueError('Expecting value: line 1 column 1 (char 0)',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by yan12125** [comment]
I guess this video requires payment?

**Comment by casinero** [comment]
Sorry, I didn't realize that.
I'll close this issue.

**Comment by yan12125** [comment]
Well, it's possible to support non-free videos, usually with ```--cookies``` or ```--username``` and ```--password```. I'm just asking for confirmation.
