### ISSUE TITLE
[ARD:mediathek] ERROR: Video: Failed to parse JSON

### ISSUE THREAD

**Issue by devurandom** [rg3/youtube-dl#11018]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.10.21.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)

```
youtube-dl --verbose http://www.ardmediathek.de/tv/Reportage-Dokumentation/Inside-Nordkorea/Das-Erste/Video                                                                                                                                           [43/45]
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.ardmediathek.de/tv/Reportage-Dokumentation/Inside-Nordkorea/Das-Erste/Video']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.10.21.1
[debug] Python version 3.5.2 - Linux-4.8.4-1-ARCH-x86_64-with-arch-Arch-Linux
[debug] exe versions: ffmpeg 3.1.4, ffprobe 3.1.4, rtmpdump 2.4
[debug] Proxy map: {}
[ARD:mediathek] Video: Downloading webpage
[ARD:mediathek] Video: Downloading media JSON
ERROR: Video: Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to cal
l youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 558, in _parse_json
    return json.loads(json_string)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 558, in _parse_json
    return json.loads(json_string)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 356, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/ard.py", line 228, in _real_extract
    'http://www.ardmediathek.de/play/media/%s' % video_id, webpage, video_id)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/ard.py", line 81, in _extract_media_info
    media_info_url, video_id, 'Downloading media JSON')
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 552, in _download_json
    json_string, video_id, transform_source=transform_source, fatal=fatal)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 562, in _parse_json
    raise ExtractorError(errmsg, cause=ve)
youtube_dl.utils.ExtractorError: Video: Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how
 to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by devurandom** [comment]
The URL was wrong. It should have been `http://www.ardmediathek.de/tv/Reportage-Dokumentation/Inside-Nordkorea/Das-Erste/Video?bcastId=799280&documentId=38416322`

Opening the URL mentioned above in a webbrowser redirects to `http://www.ardmediathek.de/-/stoerung`. Maybe this could be detected by the handler?

**Comment by hquadrat** [comment]
I can confirm this issue, also appears with correct urls.

e.g. http://www.ardmediathek.de/tv/Der-Montags-Check/Der-Geld-Check-2-Wo-Kommunen-hinlange/Das-Erste/Video?bcastId=22834010&documentId=38514196

**Comment by devurandom** [comment]
@hquadrat I cannot reproduce this problem here. Maybe you forgot to quote the URL?

**Comment by hquadrat** [comment]
@devurandom /me is looking ashamed to the ground. Err, yes, forgot. Sorry for that.
