### ISSUE TITLE
ESPN: "Unable to extract pcode"

### ISSUE THREAD

**Issue by hub2git** [rg3/youtube-dl#11041]
## Please follow the guide below
---
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2016.10.26**
### Before submitting an _issue_ make sure you have:
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
## \- [X] Bug report (encountered problems with youtube-dl)

```
youtube-dl --verbose http://www.espn.com/video/clip?id=17833410
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.espn.com/video/clip?id=17833410']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.10.26
[debug] Python version 2.7.12 - Linux-4.4.0-36-generic-x86_64-with-LinuxMint-18-sarah
[debug] exe versions: avconv 2.8.8-0ubuntu0.16.04.1, avprobe 2.8.8-0ubuntu0.16.04.1, ffmpeg 2.8.8-0ubuntu0.16.04.1, ffprobe 2.8.8-0ubuntu0.16.04.1
[debug] Proxy map: {}
[ESPN] clip?id=17833410: Downloading webpage
[ESPN] 17833410: Downloading webpage
ERROR: Unable to extract pcode; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 356, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/espn.py", line 72, in _real_extract
    r'["\']pcode=([^"\']+)["\']', player, 'pcode')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 659, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract pcode; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

...
<end of log>
```
---

**Comment by snipem** [comment]
Same for the test video in the extractor:

```
youtube-dl "http://espn.go.com/video/clip?id=10365079" --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://espn.go.com/video/clip?id=10365079', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2016.11.02
[debug] Python version 3.5.0 - Linux-4.2.3-1-ARCH-i686-with-arch
[debug] exe versions: ffmpeg 3.0.2, ffprobe 3.0.2, rtmpdump 2.4
[debug] Proxy map: {}
[ESPN] clip?id=10365079: Downloading webpage
ERROR: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 357, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/espn.py", line 62, in _real_extract
    webpage, 'video id', group='id')
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 660, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
