### ISSUE TITLE
site-support in youtube-dl for ozee.com site- streaming video only in flash though. 

### ISSUE THREAD

**Issue by shirishag75** [rg3/youtube-dl#11058]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.10.26**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Site support request (request for adding support for a new site)

---
I would like to have support for ozee.com . 
---

This is what i get when I try/tried using youtube-dl -

```
[$] youtube-dl --verbose -F "http://www.ozee.com/shows/little-lord/video/little-lord-episode-23-october-28-2016-full-episode.html"  [3:13:25]
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'-F', u'http://www.ozee.com/shows/little-lord/video/little-lord-episode-23-october-28-2016-full-episode.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.10.26
[debug] Python version 2.7.12+ - Linux-4.7.0-1-amd64-x86_64-with-debian-stretch-sid
[debug] exe versions: ffmpeg 3.1.4-1, ffprobe 3.1.4-1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] little-lord-episode-23-october-28-2016-full-episode: Requesting header
WARNING: Falling back on generic information extractor.
[generic] little-lord-episode-23-october-28-2016-full-episode: Downloading webpage
[generic] little-lord-episode-23-october-28-2016-full-episode: Extracting information
ERROR: Unsupported URL: http://www.ozee.com/shows/little-lord/video/little-lord-episode-23-october-28-2016-full-episode.html
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1634, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2525, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2514, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 76, column 24
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 356, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2417, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.ozee.com/shows/little-lord/video/little-lord-episode-23-october-28-2016-full-episode.html
```

**Comment by Abhinav1217** [comment]
Their servers have been changed a bit now. This is the current error message from their site when I tried to download an episode for me.
```
 youtube-dl "http://www.ozee.com/shows/bhabi-ji-ghar-par-hai/video/bhabi-ji-ghar-par-hain-episode-663-september-12-2017-full-episode.html"
[generic] bhabi-ji-ghar-par-hain-episode-663-september-12-2017-full-episode: Requesting header
WARNING: Falling back on generic information extractor.
[generic] bhabi-ji-ghar-par-hain-episode-663-september-12-2017-full-episode: Downloading webpage
[generic] bhabi-ji-ghar-par-hain-episode-663-september-12-2017-full-episode: Extracting information
[generic] bhabi-ji-ghar-par-hain-episode-663-september-12-2017-full-episode: Downloading m3u8 information
[hlsnative] Downloading m3u8 manifest
ERROR: unable to download video data: HTTP Error 301: The HTTP server returned a redirect error that would lead to an infinite loop.
The last 30x error message was:
Moved Permanently
```
I used the URL http://www.ozee.com/shows/bhabi-ji-ghar-par-hai/video/bhabi-ji-ghar-par-hain-episode-663-september-12-2017-full-episode.html 

This is URL of one of the video fragment captured by firefox extension `Download them all`.
```
http://zeeapp4-vh.akamaihd.net/i/ozee.com/draco/shows/and_tv/Bhabiji_Ghar_Par_Hai/September/12092017/Bhabiji_Ghar_Par_Hai_Episode_663_Ozee.smil/index_884736_av.m3u8?e=5dc6dd309b401889&hdneaq=exp=1505393562~acl=/*~hmac=7f891311798dbca0ec7b4da80212be5b69e91bf1ec58b03df87eee4602fa6855
```

Looks like they have some kind of hmac auth in their m3u8 stream.
