### ISSUE TITLE
[Dalymotion] ERROR: hostname 'proxy-099.dc3.dailymotion.com' doesn't match either of

### ISSUE THREAD

**Issue by Lapinator** [rg3/youtube-dl#11059]
youtube-dl --version 
2016.10.26

youtube-dl http://www.dailymotion.com/video/x3lnp8j_chroma-s01-01-troll2_shortfilms
[dailymotion] x3lnp8j: Downloading webpage
[dailymotion] x3lnp8j: Downloading m3u8 information
[dailymotion] x3lnp8j: Downloading m3u8 information
[dailymotion] x3lnp8j: Downloading m3u8 information
[dailymotion] x3lnp8j: Downloading m3u8 information
[dailymotion] x3lnp8j: Downloading m3u8 information
[dailymotion] x3lnp8j: Downloading m3u8 information
[dailymotion] x3lnp8j: Downloading m3u8 information
ERROR: hostname 'proxy-099.dc3.dailymotion.com' doesn't match either of 'proxy-001.dc3.dailymotion.com', 'proxy-002.dc3.dailymotion.com', 'proxy-003.dc3.dailymotion.com', 'proxy-004.dc3.dailymotion.com', 'proxy-005.dc3.dailymotion.com', 'proxy-006.dc3.dailymotion.com', 'proxy-007.dc3.dailymotion.com', 'proxy-008.dc3.dailymotion.com', 'proxy-009.dc3.dailymotion.com', 'proxy-010.dc3.dailymotion.com', 'proxy-011.dc3.dailymotion.com', 'proxy-012.dc3.dailymotion.com', 'proxy-013.dc3.dailymotion.com', 'proxy-014.dc3.dailymotion.com', 'proxy-015.dc3.dailymotion.com', 'proxy-016.dc3.dailymotion.com', 'proxy-017.dc3.dailymotion.com', 'proxy-018.dc3.dailymotion.com', 'proxy-019.dc3.dailymotion.com', 'proxy-020.dc3.dailymotion.com', 'proxy-021.dc3.dailymotion.com', 'proxy-022.dc3.dailymotion.com', 'proxy-023.dc3.dailymotion.com', 'proxy-024.dc3.dailymotion.com', 'proxy-025.dc3.dailymotion.com', 'proxy-026.dc3.dailymotion.com', 'proxy-027.dc3.dailymotion.com', 'proxy-028.dc3.dailymotion.com', 'proxy-029.dc3.dailymotion.com', 'proxy-030.dc3.dailymotion.com', 'proxy-031.dc3.dailymotion.com', 'proxy-032.dc3.dailymotion.com', 'proxy-033.dc3.dailymotion.com', 'proxy-034.dc3.dailymotion.com', 'proxy-035.dc3.dailymotion.com', 'proxy-036.dc3.dailymotion.com', 'proxy-037.dc3.dailymotion.com', 'proxy-038.dc3.dailymotion.com', 'proxy-039.dc3.dailymotion.com', 'proxy-040.dc3.dailymotion.com', 'proxy-041.dc3.dailymotion.com', 'proxy-042.dc3.dailymotion.com', 'proxy-043.dc3.dailymotion.com', 'proxy-044.dc3.dailymotion.com', 'proxy-045.dc3.dailymotion.com', 'proxy-046.dc3.dailymotion.com', 'proxy-047.dc3.dailymotion.com', 'proxy-048.dc3.dailymotion.com', 'proxy-049.dc3.dailymotion.com', 'proxy-050.dc3.dailymotion.com', 'proxy-051.dc3.dailymotion.com', 'proxy-052.dc3.dailymotion.com', 'proxy-053.dc3.dailymotion.com', 'proxy-054.dc3.dailymotion.com', 'proxy-055.dc3.dailymotion.com', 'proxy-056.dc3.dailymotion.com', 'proxy-057.dc3.dailymotion.com', 'proxy-058.dc3.dailymotion.com', 'proxy-059.dc3.dailymotion.com', 'proxy-060.dc3.dailymotion.com', 'proxy-061.dc3.dailymotion.com', 'proxy-062.dc3.dailymotion.com', 'proxy-063.dc3.dailymotion.com', 'proxy-064.dc3.dailymotion.com', 'proxy-065.dc3.dailymotion.com', 'proxy-066.dc3.dailymotion.com', 'proxy-067.dc3.dailymotion.com', 'proxy-068.dc3.dailymotion.com', 'proxy-069.dc3.dailymotion.com', 'proxy-070.dc3.dailymotion.com', 'proxy-071.dc3.dailymotion.com', 'proxy-072.dc3.dailymotion.com', 'proxy-073.dc3.dailymotion.com', 'proxy-074.dc3.dailymotion.com', 'proxy-075.dc3.dailymotion.com', 'proxy-076.dc3.dailymotion.com', 'proxy-077.dc3.dailymotion.com', 'proxy-078.dc3.dailymotion.com', 'proxy-079.dc3.dailymotion.com', 'proxy-080.dc3.dailymotion.com', 'proxy-081.dc3.dailymotion.com', 'proxy-082.dc3.dailymotion.com', 'proxy-083.dc3.dailymotion.com', 'proxy-084.dc3.dailymotion.com', 'upload-01.dc3.dailymotion.com', 'upload-07.dc3.dailymotion.com', 'upload-10.dc3.dailymotion.com', 'upload-11.dc3.dailymotion.com', 'upload-12.dc3.dailymotion.com'

**Comment by yan12125** [comment]
This video works for me. Could you paste the output of this command:
```
youtube-dl -v http://www.dailymotion.com/video/x3lnp8j_chroma-s01-01-troll2_shortfilms
```

**Comment by dstftw** [comment]
```
PS C:\dev\youtube-dl\master> py -3.5 .\youtube_dl\__main__.py http://www.dailymotion.com/video/x3lnp8j_chroma-s01-01-tro
ll2_shortfilms -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://www.dailymotion.com/video/x3lnp8j_chroma-s01-01-troll2_shortfilms', '-v']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.10.26
[debug] Git HEAD: f351756
[debug] Python version 3.5.2 - Windows-10-10.0.10240-SP0
[debug] exe versions: ffmpeg N-81192-g04da20e, ffprobe N-81192-g04da20e, rtmpdump 2.4
[debug] Proxy map: {}
[dailymotion] x3lnp8j: Downloading webpage
[dailymotion] x3lnp8j: Downloading m3u8 information
[dailymotion] x3lnp8j: Downloading m3u8 information
[dailymotion] x3lnp8j: Downloading m3u8 information
[dailymotion] x3lnp8j: Downloading m3u8 information
[dailymotion] x3lnp8j: Downloading m3u8 information
[dailymotion] x3lnp8j: Downloading m3u8 information
[dailymotion] x3lnp8j: Downloading m3u8 information
[debug] Invoking downloader on 'https://www.dailymotion.com/cdn/H264-1920x1080/video/x3lnp8j.mp4?auth=1477926419-2562-7usxsa9o-9ff3fe5a96d1440cb8b8ed6c50888295'
[download] Resuming download at byte 1047552
Traceback (most recent call last):
  File ".\youtube_dl\__main__.py", line 19, in <module>
    youtube_dl.main()
  File "C:\dev\youtube-dl\master\youtube_dl\__init__.py", line 445, in main
    _real_main(argv)
  File "C:\dev\youtube-dl\master\youtube_dl\__init__.py", line 435, in _real_main
    retcode = ydl.download(all_urls)
  File "C:\dev\youtube-dl\master\youtube_dl\YoutubeDL.py", line 1791, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "C:\dev\youtube-dl\master\youtube_dl\YoutubeDL.py", line 705, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\dev\youtube-dl\master\youtube_dl\YoutubeDL.py", line 751, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "C:\dev\youtube-dl\master\youtube_dl\YoutubeDL.py", line 1435, in process_video_result
    self.process_info(new_info)
  File "C:\dev\youtube-dl\master\youtube_dl\YoutubeDL.py", line 1699, in process_info
    success = dl(filename, info_dict)
  File "C:\dev\youtube-dl\master\youtube_dl\YoutubeDL.py", line 1641, in dl
    return fd.download(name, info)
  File "C:\dev\youtube-dl\master\youtube_dl\downloader\common.py", line 353, in download
    return self.real_download(filename, info_dict)
  File "C:\dev\youtube-dl\master\youtube_dl\downloader\http.py", line 61, in real_download
    data = self.ydl.urlopen(request)
  File "C:\dev\youtube-dl\master\youtube_dl\YoutubeDL.py", line 2001, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "C:\Python\Python35\lib\urllib\request.py", line 472, in open
    response = meth(req, response)
  File "C:\Python\Python35\lib\urllib\request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python\Python35\lib\urllib\request.py", line 504, in error
    result = self._call_chain(*args)
  File "C:\Python\Python35\lib\urllib\request.py", line 444, in _call_chain
    result = func(*args)
  File "C:\Python\Python35\lib\urllib\request.py", line 696, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "C:\Python\Python35\lib\urllib\request.py", line 466, in open
    response = self._open(req, data)
  File "C:\Python\Python35\lib\urllib\request.py", line 484, in _open
    '_open', req)
  File "C:\Python\Python35\lib\urllib\request.py", line 444, in _call_chain
    result = func(*args)
  File "C:\dev\youtube-dl\master\youtube_dl\utils.py", line 1036, in https_open
    req, **kwargs)
  File "C:\Python\Python35\lib\urllib\request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "C:\Python\Python35\lib\http\client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "C:\Python\Python35\lib\http\client.py", line 1151, in _send_request
    self.endheaders(body)
  File "C:\Python\Python35\lib\http\client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "C:\Python\Python35\lib\http\client.py", line 934, in _send_output
    self.send(msg)
  File "C:\Python\Python35\lib\http\client.py", line 877, in send
    self.connect()
  File "C:\Python\Python35\lib\http\client.py", line 1260, in connect
    server_hostname=server_hostname)
  File "C:\Python\Python35\lib\ssl.py", line 377, in wrap_socket
    _context=self)
  File "C:\Python\Python35\lib\ssl.py", line 752, in __init__
    self.do_handshake()
  File "C:\Python\Python35\lib\ssl.py", line 988, in do_handshake
    self._sslobj.do_handshake()
  File "C:\Python\Python35\lib\ssl.py", line 638, in do_handshake
    match_hostname(self.getpeercert(), self.server_hostname)
  File "C:\Python\Python35\lib\ssl.py", line 297, in match_hostname
    % (hostname, ', '.join(map(repr, dnsnames))))
ssl.CertificateError: hostname 'proxy-099.dc3.dailymotion.com' doesn't match either of 'proxy-001.dc3.dailymotion.com', 'proxy-002.dc3.dailymotion.com', 'proxy-003.dc3.dailymotion.com', 'proxy-004.dc3.dailymotion.com', 'proxy-005.dc3.dailymotion.com', 'proxy-006.dc3.dailymotion.com', 'proxy-007.dc3.dailymotion.com', 'proxy-008.dc3.dailymotion.com', 'proxy-009.dc3.dailymotion.com', 'proxy-010.dc3.dailymotion.com', 'proxy-011.dc3.dailymotion.com', 'proxy-012.dc3.dailymotion.com', 'proxy-013.dc3.dailymotion.com', 'proxy-014.dc3.dailymotion.com', 'proxy-015.dc3.dailymotion.com', 'proxy-016.dc3.dailymotion.com', 'proxy-017.dc3.dailymotion.com', 'proxy-018.dc3.dailymotion.com', 'proxy-019.dc3.dailymotion.com', 'proxy-020.dc3.dailymotion.com', 'proxy-021.dc3.dailymotion.com', 'proxy-022.dc3.dailymotion.com', 'proxy-023.dc3.dailymotion.com', 'proxy-024.dc3.dailymotion.com', 'proxy-025.dc3.dailymotion.com', 'proxy-026.dc3.dailymotion.com', 'proxy-027.dc3.dailymotion.com', 'proxy-028.dc3.dailymotion.com', 'proxy-029.dc3.dailymotion.com', 'proxy-030.dc3.dailymotion.com', 'proxy-031.dc3.dailymotion.com', 'proxy-032.dc3.dailymotion.com', 'proxy-033.dc3.dailymotion.com', 'proxy-034.dc3.dailymotion.com', 'proxy-035.dc3.dailymotion.com', 'proxy-036.dc3.dailymotion.com', 'proxy-037.dc3.dailymotion.com', 'proxy-038.dc3.dailymotion.com', 'proxy-039.dc3.dailymotion.com', 'proxy-040.dc3.dailymotion.com', 'proxy-041.dc3.dailymotion.com', 'proxy-042.dc3.dailymotion.com', 'proxy-043.dc3.dailymotion.com', 'proxy-044.dc3.dailymotion.com', 'proxy-045.dc3.dailymotion.com', 'proxy-046.dc3.dailymotion.com', 'proxy-047.dc3.dailymotion.com', 'proxy-048.dc3.dailymotion.com', 'proxy-049.dc3.dailymotion.com', 'proxy-050.dc3.dailymotion.com', 'proxy-051.dc3.dailymotion.com', 'proxy-052.dc3.dailymotion.com', 'proxy-053.dc3.dailymotion.com', 'proxy-054.dc3.dailymotion.com', 'proxy-055.dc3.dailymotion.com', 'proxy-056.dc3.dailymotion.com', 'proxy-057.dc3.dailymotion.com', 'proxy-058.dc3.dailymotion.com', 'proxy-059.dc3.dailymotion.com', 'proxy-060.dc3.dailymotion.com', 'proxy-061.dc3.dailymotion.com', 'proxy-062.dc3.dailymotion.com', 'proxy-063.dc3.dailymotion.com', 'proxy-064.dc3.dailymotion.com', 'proxy-065.dc3.dailymotion.com', 'proxy-066.dc3.dailymotion.com', 'proxy-067.dc3.dailymotion.com', 'proxy-068.dc3.dailymotion.com', 'proxy-069.dc3.dailymotion.com', 'proxy-070.dc3.dailymotion.com', 'proxy-071.dc3.dailymotion.com', 'proxy-072.dc3.dailymotion.com', 'proxy-073.dc3.dailymotion.com', 'proxy-074.dc3.dailymotion.com', 'proxy-075.dc3.dailymotion.com', 'proxy-076.dc3.dailymotion.com', 'proxy-077.dc3.dailymotion.com', 'proxy-078.dc3.dailymotion.com', 'proxy-079.dc3.dailymotion.com', 'proxy-080.dc3.dailymotion.com', 'proxy-081.dc3.dailymotion.com', 'proxy-082.dc3.dailymotion.com', 'proxy-083.dc3.dailymotion.com', 'proxy-084.dc3.dailymotion.com', 'upload-01.dc3.dailymotion.com', 'upload-07.dc3.dailymotion.com', 'upload-10.dc3.dailymotion.com', 'upload-11.dc3.dailymotion.com', 'upload-12.dc3.dailymotion.com'
```
Certificate served for download URL https://www.dailymotion.com/cdn/H264-1920x1080/video/x3lnp8j.mp4?auth=1477926482-2562-nc6748mp-e2523682ec037046fcc840167fbdfa12 (redirects to https://proxy-099.dc3.dailymotion.com/video/952/677/217776259_mp4_h264_aac_fhd.mp4?auth=1477757906-6658-fmme24k2-25162c9cee96cd7cc3c37d474ff515cd#cell=core) is not valid since it does not list `hostname proxy-099.dc3.dailymotion.com` as allowed.

You can contact dailymotion and ask them to fix their certificates or use `--no-check-certificate` if you don't care about certificates at all.
