### ISSUE TITLE
Some bandcamp links do not work with youtube-dl.

### ISSUE THREAD

**Issue by orbea** [rg3/youtube-dl#11067]
### Make sure you are using the _latest_ version: run `youtube-dl --version` and ensure your version is _2016.10.26_. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.10.26**
### Before submitting an _issue_ make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
### What is the purpose of your _issue_?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
### If the purpose of this _issue_ is a _bug report_, _site support request_ or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
$ youtube-dl --verbose https://erasenegatedelete.bandcamp.com/album/of-rust-and-rotten-things
[debug] System config: []
[debug] User config: ['--prefer-free-formats', '--format', 'webm/ogg/best']
[debug] Command-line args: ['--verbose', 'https://erasenegatedelete.bandcamp.com/album/of-rust-and-rotten-things']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.10.26
[debug] Python version 3.5.2 - Linux-4.8.4-x86_64-AMD_FX-tm-6350_Six-Core_Processor-with-slackware-14.2
[debug] exe versions: ffmpeg 3.1.5, ffprobe 3.1.5, rtmpdump 2.4
[debug] Proxy map: {}
[Bandcamp:album] of-rust-and-rotten-things: Downloading webpage
[download] Downloading playlist: Of Rust And Rotten Things
[Bandcamp:album] playlist Of Rust And Rotten Things: Collected 11 video ids (downloading 11 of them)
[download] Downloading video 1 of 11
[Bandcamp] invocation-of-the-centipede-king: Downloading webpage
[Bandcamp] 1572278198: Downloading free downloads page
ERROR: Unable to extract items; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib64/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib64/python3.5/site-packages/youtube_dl/extractor/common.py", line 356, in extract
    return self._real_extract(url)
  File "/usr/lib64/python3.5/site-packages/youtube_dl/extractor/bandcamp.py", line 87, in _real_extract
    r'(?sm)items: (.*?),$', download_webpage, 'items'), video_id)
  File "/usr/lib64/python3.5/site-packages/youtube_dl/extractor/common.py", line 659, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract items; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
...
<end of log>
```
### Description of your _issue_, suggested solution and other information

Some bandcamp links do not seem to work with youtube-dl.

Examples:

https://erasenegatedelete.bandcamp.com/album/of-rust-and-rotten-things
https://thebastards330.bandcamp.com/album/being-human

**Comment by pricejn2** [comment]
I'm seeing the same behavior:

```
youtube-dl http://grindlinetheband.bandcamp.com/track/lifes-a-bitch --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://grindlinetheband.bandcamp.com/track/lifes-a-bitch', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.11.04
[debug] Python version 3.4.2 - Linux-3.14.32-xxxx-grs-ipv6-64-x86_64-with-Debian-8
[debug] exe versions: ffmpeg 2.8.8, ffprobe 2.8.8, rtmpdump 2.4
[debug] Proxy map: {}
[Bandcamp] lifes-a-bitch: Downloading webpage
[Bandcamp] 2814239023: Downloading free downloads page
ERROR: Unable to extract items; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.4/dist-packages/youtube_dl/extractor/common.py", line 357, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python3.4/dist-packages/youtube_dl/extractor/bandcamp.py", line 87, in _real_extract
    r'(?sm)items: (.*?),$', download_webpage, 'items'), video_id)
  File "/usr/local/lib/python3.4/dist-packages/youtube_dl/extractor/common.py", line 660, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract items; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by orbea** [comment]
`youtube-dl-2016.11.08.1-x86_64-1_SBo`

Another one.
https://roborg.bandcamp.com/album/fsociety
```
$ youtube-dl --verbose https://roborg.bandcamp.com/album/fsociety
[debug] System config: []
[debug] User config: ['--prefer-free-formats', '--format', 'webm/ogg/best']
[debug] Command-line args: ['--verbose', 'https://roborg.bandcamp.com/album/fsociety']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.11.08.1
[debug] Python version 3.5.2 - Linux-4.8.4-x86_64-AMD_FX-tm-6350_Six-Core_Processor-with-slackware-14.2
[debug] exe versions: ffmpeg 3.1.5, ffprobe 3.1.5, rtmpdump 2.4
[debug] Proxy map: {}
[Bandcamp:album] fsociety: Downloading webpage
[download] Downloading playlist: fsociety
[Bandcamp:album] playlist fsociety: Collected 5 video ids (downloading 5 of them)
[download] Downloading video 1 of 5
[Bandcamp] count-zero: Downloading webpage
[Bandcamp] 2940104791: Downloading free downloads page
ERROR: Unable to extract items; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib64/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib64/python3.5/site-packages/youtube_dl/extractor/common.py", line 357, in extract
    return self._real_extract(url)
  File "/usr/lib64/python3.5/site-packages/youtube_dl/extractor/bandcamp.py", line 87, in _real_extract
    r'(?sm)items: (.*?),$', download_webpage, 'items'), video_id)
  File "/usr/lib64/python3.5/site-packages/youtube_dl/extractor/common.py", line 660, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract items; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by Gwend4l** [comment]
I encounter the same issue using version 2016.10.25:

~~~~~
$ youtube-dl --verbose https://ddrkirbyisq.bandcamp.com/album/celestial-melodies
[debug] System config: ['--prefer-free-formats']
[debug] User config: []
[debug] Command-line args: ['--verbose', 'https://ddrkirbyisq.bandcamp.com/album/celestial-melodies']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.10.25
[debug] Python version 3.5.2 - Linux-4.8.6-300.fc25.x86_64-x86_64-with-fedora-25-Twenty_Five
[debug] exe versions: ffmpeg 3.1.5, ffprobe 3.1.5, rtmpdump 2.4
[debug] Proxy map: {}
[Bandcamp:album] celestial-melodies: Downloading webpage
[download] Downloading playlist: Celestial Melodies
[Bandcamp:album] playlist Celestial Melodies: Collected 23 video ids (downloading 23 of them)
[download] Downloading video 1 of 23
[Bandcamp] lullaby-of-flame-lullaby-of-deserted-hell: Downloading webpage
[Bandcamp] 1209265345: Downloading free downloads page
ERROR: Unable to extract items; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 693, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 356, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/bandcamp.py", line 87, in _real_extract
    r'(?sm)items: (.*?),$', download_webpage, 'items'), video_id)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 659, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract items; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
~~~~~

**Comment by orbea** [comment]
`youtube-dl-2016.11.14.1-x86_64-1_SBo`

Another one...
```
~$ youtube-dl --verbose https://gosutomall.bandcamp.com/
[debug] System config: []
[debug] User config: ['--prefer-free-formats', '--format', 'webm/ogg/best']
[debug] Command-line args: ['--verbose', 'https://gosutomall.bandcamp.com/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.11.14.1
[debug] Python version 3.5.2 - Linux-4.8.7-x86_64-AMD_FX-tm-6350_Six-Core_Processor-with-slackware-14.2
[debug] exe versions: ffmpeg 3.2, ffprobe 3.2, rtmpdump 2.4
[debug] Proxy map: {}
[Bandcamp:album] gosutomall: Downloading webpage
[download] Downloading playlist: BetaPlus 製品恋
[Bandcamp:album] playlist BetaPlus 製品恋: Collected 8 video ids (downloading 8 of them)
[download] Downloading video 1 of 8
[Bandcamp] -: Downloading webpage
[Bandcamp] 2760467925: Downloading free downloads page
ERROR: Unable to extract items; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib64/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib64/python3.5/site-packages/youtube_dl/extractor/common.py", line 357, in extract
    return self._real_extract(url)
  File "/usr/lib64/python3.5/site-packages/youtube_dl/extractor/bandcamp.py", line 87, in _real_extract
    r'(?sm)items: (.*?),$', download_webpage, 'items'), video_id)
  File "/usr/lib64/python3.5/site-packages/youtube_dl/extractor/common.py", line 660, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract items; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by orbea** [comment]
`youtube-dl-2016.11.18-x86_64-1_SBo`

....
```
$ youtube-dl --verbose  https://powercut.bandcamp.com/album/honolulu-mixtape
[debug] System config: []
[debug] User config: ['--prefer-free-formats', '--format', 'webm/ogg/best']
[debug] Command-line args: ['--verbose', 'https://powercut.bandcamp.com/album/honolulu-mixtape']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.11.18
[debug] Python version 3.5.2 - Linux-4.8.8-x86_64-AMD_FX-tm-6350_Six-Core_Processor-with-slackware-14.2
[debug] exe versions: ffmpeg 3.2, ffprobe 3.2, rtmpdump 2.4
[debug] Proxy map: {}
[Bandcamp:album] honolulu-mixtape: Downloading webpage
[download] Downloading playlist: Honolulu mixtape
[Bandcamp:album] playlist Honolulu mixtape: Collected 5 video ids (downloading 5 of them)
[download] Downloading video 1 of 5
[Bandcamp] friendly-zombie: Downloading webpage
[Bandcamp] 3641043230: Downloading free downloads page
ERROR: Unable to extract items; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib64/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib64/python3.5/site-packages/youtube_dl/extractor/common.py", line 357, in extract
    return self._real_extract(url)
  File "/usr/lib64/python3.5/site-packages/youtube_dl/extractor/bandcamp.py", line 87, in _real_extract
    r'(?sm)items: (.*?),$', download_webpage, 'items'), video_id)
  File "/usr/lib64/python3.5/site-packages/youtube_dl/extractor/common.py", line 660, in _search_regex
```
