### ISSUE TITLE
[ustream] No video formats found

### ISSUE THREAD

**Issue by stepshal** [rg3/youtube-dl#11072]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.10.26**
### Before submitting an _issue_ make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
### What is the purpose of your _issue_?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

```
$ y -v http://www.ustream.tv/channel/iss-hdev-payload
[debug] System config: []
[debug] User config: ['-4', '-f', 'best', '--prefer-free-formats', '--no-cache-dir', '--no-mtime', '--youtube-skip-dash-manifest']
[debug] Command-line args: ['-v', 'http://www.ustream.tv/channel/iss-hdev-payload']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.10.26
[debug] Python version 3.5.2+ - Linux-4.8.0-trunk-686-i686-with-debian-stretch-sid
[debug] exe versions: ffmpeg 3.2, ffprobe 3.2, rtmpdump 2.4
[debug] Proxy map: {}
[ustream:channel] iss-hdev-payload: Downloading webpage
[ustream:channel] iss-hdev-payload: Downloading video information (next: 1)
[ustream:channel] iss-hdev-payload: Downloading video information (next: 13)
[ustream:channel] iss-hdev-payload: Downloading video information (next: 25)
[ustream:channel] iss-hdev-payload: Downloading video information (next: 37)
[ustream:channel] iss-hdev-payload: Downloading video information (next: 49)
[ustream:channel] iss-hdev-payload: Downloading video information (next: 61)
[ustream:channel] iss-hdev-payload: Downloading video information (next: 73)
[ustream:channel] iss-hdev-payload: Downloading video information (next: 85)
[ustream:channel] iss-hdev-payload: Downloading video information (next: 97)
[ustream:channel] iss-hdev-payload: Downloading video information (next: 109)
[ustream:channel] iss-hdev-payload: Downloading video information (next: 121)
[ustream:channel] iss-hdev-payload: Downloading video information (next: 133)
[ustream:channel] iss-hdev-payload: Downloading video information (next: 145)
[ustream:channel] iss-hdev-payload: Downloading video information (next: 157)
[ustream:channel] iss-hdev-payload: Downloading video information (next: 169)
[ustream:channel] iss-hdev-payload: Downloading video information (next: 181)
[ustream:channel] iss-hdev-payload: Downloading video information (next: 193)
[ustream:channel] iss-hdev-payload: Downloading video information (next: 205)
[ustream:channel] iss-hdev-payload: Downloading video information (next: 217)
[ustream:channel] iss-hdev-payload: Downloading video information (next: 229)
[ustream:channel] iss-hdev-payload: Downloading video information (next: 241)
[ustream:channel] iss-hdev-payload: Downloading video information (next: 253)
[download] Downloading playlist: 17074538
[ustream:channel] playlist 17074538: Collected 261 video ids (downloading 261 of them)
[download] Downloading video 1 of 261
[ustream] 92527698: Downloading JSON metadata
[ustream] 92527698: Downloading connection info
[ustream] 92527698: Downloading stream info
[ustream] 92527698: Downloading connection info (try 2)
[ustream] 92527698: Downloading stream info (try 2)
[ustream] 92527698: Downloading connection info (try 3)
[ustream] 92527698: Downloading stream info (try 3)
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/common.py", line 356, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/ustream.py", line 210, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/common.py", line 923, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

 http://www.ustream.tv/channel/iss-hdev-payload

**Comment by yan12125** [comment]
Seems ustream refuses to return video URLs if I tried the same link too many times. I guess it's some attack protection. Please wait for some time and try again.

Closing as the problematic video (92527698) is working for me and most likely it's a client-side issue rather than a youtube-dl one.
```
$ youtube-dl -v http://www.ustream.tv/recorded/92527698 
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.ustream.tv/recorded/92527698']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.11.08.1
[debug] Git HEAD: 3eaaa8a
[debug] Python version 3.5.2 - Linux-4.8.4-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 3.2, ffprobe 3.2
[debug] Proxy map: {}
[ustream] 92527698: Downloading JSON metadata
[ustream] 92527698: Downloading connection info
[ustream] 92527698: Downloading stream info
[ustream] 92527698: Downloading connection info (try 2)
[ustream] 92527698: Downloading stream info (try 2)
[ustream] 92527698: Downloading connection info (try 3)
[ustream] 92527698: Downloading stream info (try 3)
[ustream] 92527698: Downloading m3u8 information
[debug] Invoking downloader on 'http://c742ee30-lp-omega.ums.ustream.tv/playlist/recorded/92527698/1/playlist.m3u8?token=10423561_1478873140001&cdn=uhs_akamai&appType=11&appVersion=2&sgn=b5763fa0977e8e472e9309bab42516d8835df60e'
[download] Destination: ISS HD Earth Viewing Experiment-92527698.mp4
[debug] ffmpeg command line: ffmpeg -y -headers 'Accept-Language: en-us,en;q=0.5
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/47.0 (Chrome)
Accept-Encoding: gzip, deflate
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
' -i 'http://c742ee30-lp-omega.ums.ustream.tv/playlist/recorded/92527698/1/playlist.m3u8?token=10423561_1478873140001&cdn=uhs_akamai&appType=11&appVersion=2&sgn=b5763fa0977e8e472e9309bab42516d8835df60e' -c copy -f mp4 -bsf:a aac_adtstoasc 'file:ISS HD Earth Viewing Experiment-92527698.mp4.part'
ffmpeg version 3.2 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 6.2.1 (GCC) 20160830
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-avisynth --enable-avresample --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libass --enable-libbluray --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-netcdf --enable-shared --enable-version3 --enable-x11grab
  libavutil      55. 34.100 / 55. 34.100
  libavcodec     57. 64.100 / 57. 64.100
  libavformat    57. 56.100 / 57. 56.100
  libavdevice    57.  1.100 / 57.  1.100
  libavfilter     6. 65.100 /  6. 65.100
  libavresample   3.  1.  0 /  3.  1.  0
  libswscale      4.  2.100 /  4.  2.100
  libswresample   2.  3.100 /  2.  3.100
  libpostproc    54.  1.100 / 54.  1.100
Input #0, hls,applehttp, from 'http://c742ee30-lp-omega.ums.ustream.tv/playlist/recorded/92527698/1/playlist.m3u8?token=10423561_1478873140001&cdn=uhs_akamai&appType=11&appVersion=2&sgn=b5763fa0977e8e472e9309bab42516d8835df60e':
  Duration: 02:59:54.00, start: 0.000000, bitrate: 0 kb/s
  Program 0 
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709), 1280x720 [SAR 1:1 DAR 16:9], 60 tbr, 90k tbn, 120 tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
Output #0, mp4, to 'file:ISS HD Earth Viewing Experiment-92527698.mp4.part':
  Metadata:
    encoder         : Lavf57.56.100
    Stream #0:0: Video: h264 (High) ([33][0][0][0] / 0x0021), yuv420p(tv, bt709), 1280x720 [SAR 1:1 DAR 16:9], q=2-31, 60 tbr, 90k tbn, 90k tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) ([64][0][0][0] / 0x0040), 48000 Hz, stereo
    Metadata:
      variant_bitrate : 0
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
^Cframe= 1446 fps=184 q=-1.0 Lsize=    4964kB time=00:00:24.08 bitrate=1688.4kbits/s speed=3.06x    
video:4578kB audio:374kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.242983%
Exiting normally, received signal 2.

ERROR: Interrupted by user
```
