### ISSUE TITLE
on RTS: "mp4-1201k video format URL is invalid, skipping"

### ISSUE THREAD

**Issue by Fil** [rg3/youtube-dl#11089]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.11.02**

- [x] Bug report (encountered problems with youtube-dl)

```
youtube-dl --verbose "http://www.rts.ch/docs/lundi/8030686-le-doc-du-lundi.html"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.rts.ch/docs/lundi/8030686-le-doc-du-lundi.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.11.02
[debug] Python version 2.7.12 - Darwin-16.1.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.1.3, ffprobe 3.1.3, rtmpdump 2.4
[debug] Proxy map: {}
[RTS] le-doc-du-lundi: Downloading JSON metadata
[RTS] le-doc-du-lundi: Downloading webpage
[download] Downloading playlist: Le doc du lundi
[RTS] playlist Le doc du lundi: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[RTS] 8131886: Downloading JSON metadata
[RTS] 8131886: Downloading JSON metadata
[RTS] 8131886: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[RTS] 8131886: Downloading hds token
[RTS] 8131886: Downloading f4m manifest
WARNING: Unable to download f4m manifest: HTTP Error 403: Forbidden
[RTS] 8131886: Checking mp4-1201k video format URL
[RTS] 8131886: mp4-1201k video format URL is invalid, skipping
[RTS] 8131886: Checking mp4-301k video format URL
[RTS] 8131886: mp4-301k video format URL is invalid, skipping
[RTS] 8131886: Checking mp4-101k video format URL
[RTS] 8131886: mp4-101k video format URL is invalid, skipping
[RTS] 8131886: Checking mp4-701k video format URL
[RTS] 8131886: mp4-701k video format URL is invalid, skipping
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 357, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/rts.py", line 216, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 924, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by Fil** [comment]
The problem is not about geo-restriction.

**Comment by yan12125** [comment]
The label "geo-restricted" indicates that a developer needs a proxy to check this issue. The real cause is unknown yet
