### ISSUE TITLE
Vodlocker extractor just failed

### ISSUE THREAD

**Issue by treaki** [rg3/youtube-dl#11106]
hi,

it lookes like vodlocker just changed there interface, dowloading content as worked the one moment and the other moment it stopt working, See an abstract of the hardcopy of the terminal i have used:
```
$ youtube-dl http://vodlocker.com/fseyq8rioqjc
[Vodlocker] fseyq8rioqjc: Downloading webpage
[Vodlocker] fseyq8rioqjc: Waiting for 3 seconds
[Vodlocker] fseyq8rioqjc: Downloading video page
[download] Destination: Star Trek Enterprise Sez 1 ep05 ebk-fseyq8rioqjc.mp4
[download] 100% of 93.22MiB in 05:15
$ youtube-dl http://vodlocker.com/fseyq8rioqjc
[Vodlocker] fseyq8rioqjc: Downloading webpage
ERROR: Unable to extract embed url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest ver
sion; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
$ youtube-dl http://watchseries.cr/external/342484
[generic] 342484: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 342484: Downloading webpage
[generic] 342484: Extracting information
ERROR: Unsupported URL: http://watchseries.cr/external/342484
$ youtube-dl http://vodlocker.com/1vn59m0oomdb
[Vodlocker] 1vn59m0oomdb: Downloading webpage
[Vodlocker] 1vn59m0oomdb: Waiting for 3 seconds
[Vodlocker] 1vn59m0oomdb: Downloading video page
ERROR: Unable to extract embed url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest ver
sion; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
$ youtube-dl -U
Updating to version 2016.11.02 ...
Updated youtube-dl. Restart youtube-dl to use the new version.
$ youtube-dl http://vodlocker.com/1vn59m0oomdb
[Vodlocker] 1vn59m0oomdb: Downloading webpage
ERROR: Unable to extract embed url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest ver
sion; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
$ youtube-dl http://vodlocker.com/1vn59m0oomdb --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://vodlocker.com/1vn59m0oomdb', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.11.02
[debug] Python version 2.7.9 - Linux-4.2.0-0.bpo.1-amd64-x86_64-with-debian-8.6
[debug] exe versions: ffmpeg 2.8.8, ffprobe 2.8.8, rtmpdump 2.4
[debug] Proxy map: {}
[Vodlocker] 1vn59m0oomdb: Downloading webpage
ERROR: Unable to extract embed url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest ver
sion; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/treaki/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/home/treaki/bin/youtube-dl/youtube_dl/extractor/common.py", line 357, in extract
    return self._real_extract(url)
  File "/home/treaki/bin/youtube-dl/youtube_dl/extractor/vodlocker.py", line 56, in _real_extract
    webpage, 'embed url', group='url')
  File "/home/treaki/bin/youtube-dl/youtube_dl/extractor/common.py", line 660, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract embed url; please report this issue on https://yt-dl.org/bug . Make sure you are using t
he latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete
 output.

$
```

regards

**Comment by treaki** [comment]
or maybe the file was just deleted, but it lookes from the perspective of the output of the youtube-dl software like a tecnical error, so please capture this message ```The file was removed by administrator``` and show it to the terminal user to aviod confusion if it is that in case as i atitipaded
