### ISSUE TITLE
[Toutv] Falling back on generic information extractor. Premium content Ici Explora

### ISSUE THREAD

**Issue by MonsieurClavet** [rg3/youtube-dl#11121]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.11.04*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2016.11.04**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
youtube-dl -v -u MY_AWESOME_USERNAME -p MY_AWESOME_PASSWORD -f "(mp4,webm)bestvideo[height<=2160]+bestaudio/best[height<=2160]" -o Output.mp4 http://ici.tou.tv/hackers 
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'-f', u'(mp4,webm)bestvideo[height<=2160]+bestaudio/best[height<=2160]', u'-o', u'Output.mp4', u'http://ici.tou.tv/hackers']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.11.04
[debug] Python version 2.7.12+ - Linux-4.7.0-1-amd64-x86_64-with-Kali-kali-rolling-kali-rolling
[debug] exe versions: ffmpeg 3.2, ffprobe N-74640-g4f86084, rtmpdump 2.4
[debug] Proxy map: {}
[generic] hackers: Requesting header
WARNING: Falling back on generic information extractor.
[generic] hackers: Downloading webpage
[generic] hackers: Extracting information
[redirect] Following redirect to http://ici.tou.tv/non-supportes.html
[generic] non-supportes: Requesting header
WARNING: Falling back on generic information extractor.
[generic] non-supportes: Downloading webpage
[generic] non-supportes: Extracting information
ERROR: Unsupported URL: http://ici.tou.tv/non-supportes.html
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1634, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2525, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2514, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: mismatched tag: line 13, column 2
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 357, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2421, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://ici.tou.tv/non-supportes.html
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

---

### Description of your *issue*, suggested solution and other information

I used the same command for a while and it always worked properly with premium/non-premium content.  
Tou.tv have a section within their premium content called Ici Explora and some tv-shows doesnt seems to download accordingly
I noticed that it's mainly the show without any "SxxExx" in the url.  
For instance, The following url will download properly (http://ici.tou.tv/planete-techno/S03E06) where this url (http://ici.tou.tv/hackers) will return error pasted in the log.

[Work] http://ici.tou.tv/planete-techno/S03E06
[Dont Work] http://ici.tou.tv/hackers
Both are Premium content under Ici-Explora

I have an account if necessary for you to reproduce the issue.

**Comment by MonsieurClavet** [comment]
thx for the quick resolution, cant wait to try it!
