### ISSUE TITLE
Only one URL from this domain is giving Errno 104

### ISSUE THREAD

**Issue by webunraveling** [rg3/youtube-dl#11136]
---
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.11.04**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other
---

```
$ youtube-dl --verbose -g http://video.lptv.org/video/2365880559/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'-g', u'http://video.lptv.org/video/2365880559/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.11.04
[debug] Python version 2.7.9 - Linux-3.16.0-4-586-i686-with-debian-8.6
[debug] exe versions: avconv 11.8-6, avprobe 11.8-6, rtmpdump 2.4
[debug] Proxy map: {}
WARNING: Unable to download webpage: [Errno 104] Connection reset by peer
WARNING: Unable to download webpage: [Errno 104] Connection reset by peer
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 357, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/pbs.py", line 529, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 924, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

### Description & Other Information

This output is reproduced every time for this specific URL. All other URLs at this domain have worked flawlessly. I was running an outdated version of `youtube-dl` when I first received the above output. After upgrading (using `youtube-dl -U`) I am still receiving the same output. Below is some other output to provide a little more detail about the OS version.

    $ uname -a
    Linux hostName 3.16.0-4-586 #1 Debian 3.16.36-1+deb8u1 (2016-09-03) i686 GNU/Linux

**Comment by dstftw** [comment]
Works fine for me. Can you watch it in browser in the first place from this host?

**Comment by dstftw** [comment]
Post the output of `youtube-dl --verbose --dump-pages http://video.lptv.org/video/2365880559/`.

**Comment by webunraveling** [comment]
The video works just fine in the browser for me. Well now, I was able to get the URL using `youtube-dl -g` but it returned `WARNING: Unable to download webpage: [Errno 104] Connection reset by peer` before returning the video URL. After that when I attempt to get the thumbnail, it is failing again (output below). Also, below that is the output you requested. I use youtube-dl often at this site and it has never happened before but maybe the host server doesn't like me accessing the same page in a short time span. But I'm still able to watch the video just after receiving that error. So I'm still not sure.

```
$ youtube-dl -v --get-thumbnail http://video.lptv.org/video/2365880559/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'--get-thumbnail', u'http://video.lptv.org/video/2365880559/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.11.04
[debug] Python version 2.7.9 - Linux-3.16.0-4-586-i686-with-debian-8.6
[debug] exe versions: avconv 11.8-6, avprobe 11.8-6, rtmpdump 2.4
[debug] Proxy map: {}
WARNING: Unable to download webpage: [Errno 104] Connection reset by peer
WARNING: Unable to download webpage: [Errno 104] Connection reset by peer
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 357, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/pbs.py", line 529, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 924, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
### Output you requested
```
$ youtube-dl --verbose --dump-pages http://video.lptv.org/video/2365880559/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'--dump-pages', u'http://video.lptv.org/video/2365880559/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.11.04
[debug] Python version 2.7.9 - Linux-3.16.0-4-586-i686-with-debian-8.6
[debug] exe versions: avconv 11.8-6, avprobe 11.8-6, rtmpdump 2.4
[debug] Proxy map: {}
[pbs] 2365880559: Downloading widget/partnerplayer page
WARNING: Unable to download webpage: [Errno 104] Connection reset by peer
[pbs] 2365880559: Downloading portalplayer page
WARNING: Unable to download webpage: [Errno 104] Connection reset by peer
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 357, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/pbs.py", line 529, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 924, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by dstftw** [comment]
This looks like intermittent connectivity issue between you and http://player.pbs.org/. In any case it works fine for me from multiple locations.
