### ISSUE TITLE
Mashable support

### ISSUE THREAD

**Issue by tnmannen** [rg3/youtube-dl#11147]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.11.08.1*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.11.08.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Site support request (request for adding support for a new site)
---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
youtube-dl -v http://mashable.com/2016/11/03/portable-projector-monitor-smartphone/#V23YOtG9ykqi
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://mashable.com/2016/11/03/portable-projector-monitor-smartphone/#V23YOtG9ykqi']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.11.08.1
[debug] Python version 2.7.12 - Linux-4.4.0-45-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.8-0ubuntu0.16.04.1, ffprobe 2.8.8-0ubuntu0.16.04.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] #V23YOtG9ykqi: Requesting header
WARNING: Falling back on generic information extractor.
[generic] #V23YOtG9ykqi: Downloading webpage
[generic] #V23YOtG9ykqi: Extracting information
ERROR: Unsupported URL: http://mashable.com/2016/11/03/portable-projector-monitor-smartphone/#V23YOtG9ykqi
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 1636, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/compat.py", line 2525, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/compat.py", line 2514, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 18, column 96
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 357, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 2433, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://mashable.com/2016/11/03/portable-projector-monitor-smartphone/#V23YOtG9ykqi
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://mashable.com/2016/05/10/amazon-smart-home-universe/?utm_cid=mash-prod-nav-sub-st
- Single video: http://mashable.com/2016/11/03/portable-projector-monitor-smartphone/#V23YOtG9ykqi
---

**Comment by yan12125** [comment]
To developers: seems they use Brightcove before (#1697) while now they turned to JWPlatform.
