### ISSUE TITLE
Unable to download orlandosentinel.com's embedded Flash brightcove videos.

### ISSUE THREAD

**Issue by antdude** [rg3/youtube-dl#11155]
Example:

$ youtube-dl -v http://www.orlandosentinel.com/features/kayla-obrien/91839398-132.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.orlandosentinel.com/features/kayla-obrien/91839398-132.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.11.08.1
[debug] Python version 3.4.2 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.6
[debug] exe versions: ffmpeg 3.1.4-1, ffprobe 3.1.4-1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 91839398-132: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 91839398-132: Downloading webpage
[generic] 91839398-132: Extracting information
ERROR: Unsupported URL: http://www.orlandosentinel.com/features/kayla-obrien/91839398-132.html
Traceback (most recent call last):
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/common.py", line 357, in extract
    return self._real_extract(url)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2433, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.orlandosentinel.com/features/kayla-obrien/91839398-132.html

Thank you in advance. :)

**Comment by yan12125** [comment]
It uses a custom Brightcove player, so a dedicated extractor is necessary.
