### ISSUE TITLE
HTTP error on a viewable multifeed Youtube video

### ISSUE THREAD

**Issue by v1kn** [rg3/youtube-dl#11168]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.11.08.1*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.11.08.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

I experienced the following issue when trying to download a video (link in the output below) from Youtube. The video is viewable on the website.

**OS**: xubuntu 16.04
**Python**: using virtualenv, python3-pip, all pip packages installed locally under $HOME

```
youtube-dl -v https://www.youtube.com/watch?v=jvGDaLqkpTg                                                                                                                                               [1/8976]
[debug] System config: []
[debug] User config: ['-R', '5', '-v', '-w', '-c', '-f', 'best', '-o', '~/Videos/%(title)s.%(ext)s']
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=jvGDaLqkpTg']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.11.08.1
[debug] Python version 3.5.1+ - Linux-4.4.0-45-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.8-0ubuntu0.16.04.1, ffprobe 2.8.8-0ubuntu0.16.04.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] jvGDaLqkpTg: Downloading webpage
[youtube] jvGDaLqkpTg: Downloading video info webpage
[youtube] Downloading multifeed video (jvGDaLqkpTg, 3AKt1R1aDnw, RtAMM00gpVc, 6N2fdlP3C5U) - add --no-playlist to just download video jvGDaLqkpTg
[download] Downloading playlist: Tom Clancy Free Weekend Rainbow Whatever
[youtube] playlist Tom Clancy Free Weekend Rainbow Whatever: Collected 4 video ids (downloading 4 of them)
[download] Downloading video 1 of 4
[youtube] jvGDaLqkpTg: Downloading webpage
[youtube] jvGDaLqkpTg: Downloading video info webpage
[youtube] jvGDaLqkpTg: Extracting video information
[youtube] jvGDaLqkpTg: Downloading MPD manifest
[debug] Invoking downloader on 'https://redirector.googlevideo.com/videoplayback?requiressl=yes&ip=89.228.161.79&mime=video%2Fmp4&ipbits=0&ratebypass=yes&signature=240E5A83071B2581523841FD27AE32584C46B03F.31D21A93
45EEB2EF0A143BCCFBE215208FE1DFAE&sparams=ei%2Cgcr%2Cid%2Cip%2Cipbits%2Citag%2Cmime%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&id=jvGDaLqkpTg.1&ei=qromWIPzBIOLd57kkJAO&upn=v3ptTqXZE1c&gcr=pl&itag=18&expire=1
478954762&source=youtube&key=yt6'
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/home/user/.local/pyvenv/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 1699, in process_info
    success = dl(filename, info_dict)
  File "/home/user/.local/pyvenv/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 1641, in dl
    return fd.download(name, info)
  File "/home/user/.local/pyvenv/lib/python3.5/site-packages/youtube_dl/downloader/common.py", line 353, in download
    return self.real_download(filename, info_dict)
  File "/home/user/.local/pyvenv/lib/python3.5/site-packages/youtube_dl/downloader/http.py", line 61, in real_download
    data = self.ydl.urlopen(request)
  File "/home/user/.local/pyvenv/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 2001, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 504, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 696, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by yan12125** [comment]
The URL ```https://redirector.googlevideo.com/...``` is suspicious. In general YouTube does not return such URLs. Do all other videos work? And could you paste the result of the following command?
```
nslookup www.youtube.com
```

**Comment by v1kn** [comment]
New development: the video now works.
Nor could I reproduce the issue on my openSUSE box.

perhaps network hiccups?

i will close the issue

**Comment by yan12125** [comment]
172.217.16.174 are Google IPs. There were reports that some ISPs intercept YouTube traffic and causing problems in downloading. Anyway, this case looks like a temporary YouTube server-side issue.

**Comment by v1kn** [comment]
good to know, thanks
