### ISSUE TITLE
SITE REQUEST (fix): lenta.ru (eagleplatform)

### ISSUE THREAD

**Issue by nmr50** [rg3/youtube-dl#11160]
Hello dear authors!
I've met another video on previously added site lenta.ru that y-dl won't load, for unclear reason.
The log is here:
C:>youtube-dl.exe -F -v https://lenta.ru/news/2016/11/10/fsb_vizitka/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-F', '-v', 'https://lenta.ru/news/2016/11/10/fsb_vizitka/']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.11.08.1
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-82314-g863ebe6, ffprobe N-82314-g863ebe6
[debug] Proxy map: {}
[generic] fsb_vizitka: Requesting header
WARNING: Falling back on generic information extractor.
[generic] fsb_vizitka: Downloading webpage
[generic] fsb_vizitka: Extracting information
[EaglePlatform] 600380: Downloading JSON metadata
[EaglePlatform] 600380: Downloading m3u8 JSON
[EaglePlatform] 600380: Downloading m3u8 information
[EaglePlatform] 600380: Downloading mp4 JSON
ERROR: undefined method `application_alias_by_secure_link_type' for nil:NilClass
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpee_sdt7t\build\youtube_dl\extractor\common.py", line 404, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpee_sdt7t\build\youtube_dl\YoutubeDL.py", line 2001, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
urllib.error.HTTPError: HTTP Error 500: Internal Server Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpee_sdt7t\build\youtube_dl\extractor\eagleplatform.py", line 82, in _download_json
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpee_sdt7t\build\youtube_dl\extractor\common.py", line 549, in _download_json
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpee_sdt7t\build\youtube_dl\extractor\common.py", line 517, in _download_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpee_sdt7t\build\youtube_dl\extractor\common.py", line 424, in _download_webpage_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpee_sdt7t\build\youtube_dl\extractor\common.py", line 413, in _request_webpage
youtube_dl.utils.ExtractorError: Unable to download JSON metadata: HTTP Error 500: Internal Server Error (caused by HTTP Error()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpee_sdt7t\build\youtube_dl\extractor\common.py", line 404, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpee_sdt7t\build\youtube_dl\YoutubeDL.py", line 2001, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
urllib.error.HTTPError: HTTP Error 500: Internal Server Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpee_sdt7t\build\youtube_dl\extractor\eagleplatform.py", line 82, in _download_json
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpee_sdt7t\build\youtube_dl\extractor\common.py", line 549, in _download_json
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpee_sdt7t\build\youtube_dl\extractor\common.py", line 517, in _download_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpee_sdt7t\build\youtube_dl\extractor\common.py", line 424, in _download_webpage_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpee_sdt7t\build\youtube_dl\extractor\common.py", line 413, in _request_webpage
youtube_dl.utils.ExtractorError: Unable to download JSON metadata: HTTP Error 500: Internal Server Error (caused by HTTP Error()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpee_sdt7t\build\youtube_dl\YoutubeDL.py", line 694, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpee_sdt7t\build\youtube_dl\extractor\common.py", line 357, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpee_sdt7t\build\youtube_dl\extractor\eagleplatform.py", line 127, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpee_sdt7t\build\youtube_dl\extractor\eagleplatform.py", line 91, in _get_video_url
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpee_sdt7t\build\youtube_dl\extractor\eagleplatform.py", line 86, in _download_json
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpee_sdt7t\build\youtube_dl\extractor\eagleplatform.py", line 78, in _handle_error
youtube_dl.utils.ExtractorError: undefined method `application_alias_by_secure_link_type' for nil:NilClass

Please fix it when you'll have a time - thanks in advance!
-t

**Comment by nmr50** [comment]
Works perfect, many thankks !!! +1:)
