### ISSUE TITLE
you-dl error

### ISSUE THREAD

**Issue by Faf6791** [rg3/youtube-dl#11167]
V[youtube] aUsrrrpKsqo: Downloading js player en_US-vflgFv_Kx
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 905, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 820, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 883, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/jsinterp.py", line 241, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
ExtractorError: Could not find JS function u'tn';

**Comment by yan12125** [comment]
Most likely you're using an out-dated version of youtube-dl. Please check [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and make sure you're using version 2016.11.08.1. If you're using apt-get, uninstall it first as apt-get usually ships with very old version.
