### ISSUE TITLE
vimeo video embedded in iframe on wix site

### ISSUE THREAD

**Issue by nlevitt** [rg3/youtube-dl#11196]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.11.14.1*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.11.14.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v http://www.blackandwhiteandsex.com/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.blackandwhiteandsex.com/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.11.14.1
[debug] Git HEAD: 6b4dfa2819
[debug] Python version 3.5.2 - Darwin-15.6.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[generic] www.blackandwhiteandsex: Requesting header
WARNING: Falling back on generic information extractor.
[generic] www.blackandwhiteandsex: Downloading webpage
[generic] www.blackandwhiteandsex: Extracting information
ERROR: Unsupported URL: http://www.blackandwhiteandsex.com/
Traceback (most recent call last):
  File "/Users/nlevitt/workspace/youtube-dl/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/Users/nlevitt/workspace/youtube-dl/youtube_dl/extractor/common.py", line 357, in extract
    return self._real_extract(url)
  File "/Users/nlevitt/workspace/youtube-dl/youtube_dl/extractor/generic.py", line 2433, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.blackandwhiteandsex.com/
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):

Just one url:
http://www.blackandwhiteandsex.com/
Single plage site with more than one tab with embedded vimeo videos.
---

### Description of your *issue*, suggested solution and other information

http://www.blackandwhiteandsex.com/
is a single-page wix.com site with vimeo videos embedded in iframes, under the "trailer" table and "the angies" tab. The iframe is inserted by some javascript. The videos are specified in json files like this:
https://static.wixstatic.com/sites/dbdeea_51ac6c3b06f8f100f3ba997173abde97_166.json.z?v=3
```
"videoId":"183444182","videoType":"VIMEO"
```

I don't know for sure if this is a generic wix.com thing but I suspect it is. I am curious if you guys will deem this feasible for youtube-dl to support.

**Comment by jtagcat** [comment]
https://maailmakool.ee/v/0e4e3d works in a similar way:
```
<script type="text/javascript">

	jQuery(document).ready(function() {
		var video_target = 'https://maailmakool.ee/?download_file=16572&order=wc_order_AY21DpMoz3a9Y&email=tiia%40akg.vil.ee&key=0cad466f2e85701a945cf80f43b2f085';
		jQuery.ajax({
			url: video_target,
			success: function(result) {
				if (typeof(result.video_redirect) != 'undefined') {
					window.location.href = result.video_redirect;
				} else {
					jQuery('iframe#video_iframe').attr('src', 'https://player.vimeo.com/video/' + result.video_id + '?texttrack=et');
				}
			}, complete: function(result) {
				if (typeof(result.responseJSON) != 'undefined' && result.responseJSON) {
					if (typeof(result.responseJSON.code) != 'undefined' && result.responseJSON.code == 'wp_die') {
						jQuery('#video_iframe').remove();
						jQuery('#video_title').replaceWith(result.responseJSON.message);
					}
				} else {
					window.location.href = mk_embedder.root;
				}
			}, dataType: 'json'
		});
	});

	</script>
	<iframe id="video_iframe" width="1080" height="608" frameborder="0" allow="fullscreen" allowfullscreen></iframe>
```

The solution to this, and possibly future problems with other extractors would be to allow rendering JS with a CLI flag.
