### ISSUE TITLE
Vbox7.com download failure

### ISSUE THREAD

**Issue by BigWax** [rg3/youtube-dl#11222]
### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

D:\Youtube\ffmpeg\bin>youtube-dl.exe -v https://www.vbox7.com/play:7ce86348
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'https://www.vbox7.com/play:7ce86348']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.11.18
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-82324-g872b358, ffprobe N-82324-g872b358, rtmpdump 2.4
[debug] Proxy map: {}
[Vbox7] 7ce86348: Downloading webpage
WARNING: unable to extract thumbnail URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[Vbox7] 7ce86348: Downloading info webpage
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptx6jnsy6\build\youtube_dl\__init__.py", line 444, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptx6jnsy6\build\youtube_dl\__init__.py", line 434, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptx6jnsy6\build\youtube_dl\YoutubeDL.py", line 1791, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptx6jnsy6\build\youtube_dl\YoutubeDL.py", line 694, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptx6jnsy6\build\youtube_dl\extractor\common.py", line 357, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptx6jnsy6\build\youtube_dl\extractor\vbox7.py", line 64, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptx6jnsy6\build\youtube_dl\extractor\vbox7.py", line 64, in <lambda>
IndexError: list index out of range

---

### Description of your *issue*, suggested solution and other information

Issue appears when I try to download any video with the 2016.11.18 build under Windows 10

**Comment by dstftw** [comment]
>Собственикът на този клип го е отбелязал като личен. В момента само той/тя могат да гледат този клип.
