### ISSUE TITLE
People.com PEN Site Request

### ISSUE THREAD

**Issue by remlap** [rg3/youtube-dl#11245]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.11.18*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.11.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

Would love to be able to download video from http://people.com/pen-shows/

**Comment by dstftw** [comment]
Post [an example URL](https://github.com/rg3/youtube-dl/blob/master/README.md#is-the-description-of-the-issue-itself-sufficient).

**Comment by remlap** [comment]
http://people.com/pen/00000156-7b90-d970-ad76-7bd0a6cf0000/

**Comment by RuneMagle** [comment]
When do you add it?

´´´
C:\Users\rumag\Desktop\youtube-dl>youtube-dl.exe -f best --all-subs http://people.com/pen/00000158-44d0-d1a1-a758-4cd852110000/0000015b-206a-d9b9-a3ff-f26f3a4e0000 -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'best', '--all-subs', 'http://people.com/pen/00000158-44d0-d1a1-a758-4cd852110000/0000015b-206a-d9b9-a3ff-f26f3a4e0000', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.03.26
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-82833-gedb4f5d, ffprobe N-82833-gedb4f5d, rtmpdump 2.3
[debug] Proxy map: {}
[generic] 0000015b-206a-d9b9-a3ff-f26f3a4e0000: Requesting header
[redirect] Following redirect to http://people.com/pen/00000158-44d0-d1a1-a758-4cd852110000/0000015b-206a-d9b9-a3ff-f26f3a4e0000/
[generic] 0000015b-206a-d9b9-a3ff-f26f3a4e0000: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 0000015b-206a-d9b9-a3ff-f26f3a4e0000: Downloading webpage
[generic] 0000015b-206a-d9b9-a3ff-f26f3a4e0000: Extracting information
ERROR: Unsupported URL: http://people.com/pen/00000158-44d0-d1a1-a758-4cd852110000/0000015b-206a-d9b9-a3ff-f26f3a4e0000/
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpje2_cfdl\build\youtube_dl\YoutubeDL.py", line 761, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpje2_cfdl\build\youtube_dl\extractor\common.py", line 428, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpje2_cfdl\build\youtube_dl\extractor\generic.py", line 2667, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: http://people.com/pen/00000158-44d0-d1a1-a758-4cd852110000/0000015b-206a-d9b9-a3ff-f26f3a4e0000/
´´´
