### ISSUE TITLE
nature.com support

### ISSUE THREAD

**Issue by tnmannen** [rg3/youtube-dl#11278]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.11.22*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.11.22**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Site support request (request for adding support for a new site)
---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://www.nature.com/nature/videoarchive/tickling-rats/index.html', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.11.22
[debug] Python version 2.7.12 - Linux-4.4.0-47-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.8-0ubuntu0.16.04.1, ffprobe 2.8.8-0ubuntu0.16.04.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] index: Requesting header
WARNING: Falling back on generic information extractor.
[generic] index: Downloading webpage
[generic] index: Extracting information
ERROR: Unsupported URL: http://www.nature.com/nature/videoarchive/tickling-rats/index.html
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 1636, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/compat.py", line 2526, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/compat.py", line 2515, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: undefined entity &nbsp;: line 329, column 64
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 357, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 2443, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.nature.com/nature/videoarchive/tickling-rats/index.html
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://www.nature.com/nature/videoarchive/tickling-rats/index.html
---

**Comment by yan12125** [comment]
To developers: YouTube Flash embed

**Comment by goggle** [comment]
Seems to work now:
```
$ youtube-dl "http://www.nature.com/nature/videoarchive/tickling-rats/index.html" -F
[generic] index: Requesting header
[redirect] Following redirect to http://www.nature.com/nature/videoarchive/tickling-rats/index.html?foxtrotcallback=true
[generic] index: Requesting header
WARNING: Falling back on generic information extractor.
[generic] index: Downloading webpage
[generic] index: Extracting information
[download] Downloading playlist: What makes rats ticklish? : Nature
[generic] playlist What makes rats ticklish? : Nature: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[youtube] K9YzB57OQuw: Downloading webpage
[youtube] K9YzB57OQuw: Downloading video info webpage
[youtube] K9YzB57OQuw: Extracting video information
[youtube] K9YzB57OQuw: Downloading MPD manifest
[info] Available formats for K9YzB57OQuw:
format code  extension  resolution note
139          m4a        audio only DASH audio   48k , m4a_dash container, mp4a.40.5@ 48k (22050Hz), 458.37KiB
249          webm       audio only DASH audio   54k , opus @ 50k, 503.13KiB
250          webm       audio only DASH audio   75k , opus @ 70k, 684.12KiB
171          webm       audio only DASH audio  121k , vorbis@128k, 1.06MiB
140          m4a        audio only DASH audio  128k , m4a_dash container, mp4a.40.2@128k (44100Hz), 1.19MiB
251          webm       audio only DASH audio  145k , opus @160k, 1.30MiB
278          webm       256x144    144p  108k , webm container, vp9, 30fps, video only, 851.56KiB
160          mp4        256x144    DASH video  115k , avc1.4d400c, 30fps, video only, 1.02MiB
133          mp4        426x240    DASH video  253k , avc1.4d4015, 30fps, video only, 2.24MiB
242          webm       426x240    240p  259k , vp9, 30fps, video only, 1.65MiB
243          webm       640x360    360p  464k , vp9, 30fps, video only, 3.04MiB
134          mp4        640x360    DASH video  633k , avc1.4d401e, 30fps, video only, 3.27MiB
244          webm       854x480    480p  867k , vp9, 30fps, video only, 5.29MiB
135          mp4        854x480    DASH video 1160k , avc1.4d401f, 30fps, video only, 6.23MiB
247          webm       1280x720   720p 1723k , vp9, 30fps, video only, 10.35MiB
136          mp4        1280x720   DASH video 2320k , avc1.4d401f, 30fps, video only, 11.84MiB
248          webm       1920x1080  1080p 3007k , vp9, 30fps, video only, 18.49MiB
137          mp4        1920x1080  DASH video 4337k , avc1.640028, 30fps, video only, 21.48MiB
17           3gp        176x144    small , mp4v.20.3, mp4a.40.2@ 24k
36           3gp        320x180    small , mp4v.20.3, mp4a.40.2
43           webm       640x360    medium , vp8.0, vorbis@128k
18           mp4        640x360    medium , avc1.42001E, mp4a.40.2@ 96k
22           mp4        1280x720   hd720 , avc1.64001F, mp4a.40.2@192k (best)
[download] Finished downloading playlist: What makes rats ticklish? : Nature
```
I think this issue can be closed.

**Comment by Hrxn** [comment]
That's an YouTube embed. If all videos on nature.com are that way, then yes, fine.

**Comment by goggle** [comment]
Right, here I could find one, that does not work:
http://www.nature.com/nature/videoarchive/memory/index.html
