### ISSUE TITLE
Reuters failed

### ISSUE THREAD

**Issue by xubuntu4iran** [rg3/youtube-dl#11279]
C:\Users\***\Desktop>youtube-dl -v http://www.reuters.com/article/us-usa-trump
-britain-farage-vacancy-idUSKBN13H0HC
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.reuters.com/article/us-usa-trump-b
ritain-farage-vacancy-idUSKBN13H0HC']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2016.11.18
[debug] Python version 3.4.4 - Windows-8.1-6.3.9600
[debug] exe versions: none
[debug] Proxy map: {}
WARNING: Falling back on generic information extractor.
ERROR: Unsupported URL: http://www.reuters.com/article/us-usa-trump-britain-fara
ge-vacancy-idUSKBN13H0HC
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptx6jnsy6\bu
ild\youtube_dl\YoutubeDL.py", line 694, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptx6jnsy6\bu
ild\youtube_dl\extractor\common.py", line 357, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptx6jnsy6\bu
ild\youtube_dl\extractor\generic.py", line 2433, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.reuters.com/artic
le/us-usa-trump-britain-farage-vacancy-idUSKBN13H0HC

**Comment by tikul** [comment]
The format of your URL is incorrect. The direct link to that specific video would be [http://www.reuters.com/video/2016/11/22/uk-to-trump-no-vacancy-for-farage-as-amb?videoId=370528300](http://www.reuters.com/video/2016/11/22/uk-to-trump-no-vacancy-for-farage-as-amb?videoId=370528300). It should have '/video' in the URL and end with a videoId=xxxxxxxxx.

**Comment by yan12125** [comment]
As the webpage contians video, this request is valid. By the way, #6209 may help

**Comment by rjvim** [comment]
![screen shot 2017-04-10 at 11 55 29 am](https://cloud.githubusercontent.com/assets/23579455/24848517/b02f077e-1de4-11e7-9f45-d78c8df02aed.png)

This is failing: youtube-dl --verbose http://www.reuters.com/video/2017/04/06/avatars-help-scientists-find-best-female\?videoId\=371439210

Please help.

**Comment by ennisa-ire** [comment]
Same here, any updates.. I am using version 
ae@ae-Unknow:~/workspace/media/vids/news/reuters$ youtube-dl --version
2017.01.14
ae@ae-Unknow:~/workspace/media/vids/news/reuters$ 


The error is
ae@ae-Unknow:~/workspace/media/vids/news/reuters$ youtube-dl -v http://www.reuters.com/video/2016/05/17/jk-rowling-says-trump-has-a-right-to-be?videoId=368538205
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'http://www.reuters.com/video/2016/05/17/jk-rowling-says-trump-has-a-right-to-be?videoId=368538205']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.01.14
[debug] Python version 2.7.12 - Linux-4.4.0-79-generic-i686-athlon-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1, rtmpdump 2.4
[debug] Proxy map: {}
[Reuters] 368538205: Downloading webpage
ERROR: Unable to extract video data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 359, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/reuters.py", line 32, in _real_extract
    webpage, 'video data'))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 662, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

ae@ae-Unknow:~/workspace/media/vids/news/reuters$

**Comment by ennisa-ire** [comment]
Just updated to latest and greatest version, still same problem.


ae@ae-Unknow:~/workspace/media/vids/news/reuters$ youtube-dl --version
2017.06.12
ae@ae-Unknow:~/workspace/media/vids/news/reuters$ youtube-dl -v http://www.reuters.com/video/2016/05/17/jk-rowling-says-trump-has-a-right-to-be?videoId=368538205
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'http://www.reuters.com/video/2016/05/17/jk-rowling-says-trump-has-a-right-to-be?videoId=368538205']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.06.12
[debug] Python version 2.7.12 - Linux-4.4.0-79-generic-i686-athlon-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1, rtmpdump 2.4
[debug] Proxy map: {}
[Reuters] 368538205: Downloading webpage
ERROR: Unable to extract video data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 762, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/reuters.py", line 32, in _real_extract
    webpage, 'video data'))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 782, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

ae@ae-Unknow:~/workspace/media/vids/news/reuters$

**Comment by wilx** [comment]
I was trying to d/l this from Reuters and it failed: http://www.reuters.tv/v/k5V/2016/11/02/documents-show-isis-rules-on-beards-concubines
