### ISSUE TITLE
Unable to download http://aplus.com/'s videos.

### ISSUE THREAD

**Issue by antdude** [rg3/youtube-dl#11286]
Example:
$ youtube-dl http://aplus.com/a/interview-blue-man-group-co-founder-phil-stanton
[generic] interview-blue-man-group-co-founder-phil-stanton: Requesting header
WARNING: Falling back on generic information extractor.
[generic] interview-blue-man-group-co-founder-phil-stanton: Downloading webpage
[generic] interview-blue-man-group-co-founder-phil-stanton: Extracting information
ERROR: Unsupported URL: http://aplus.com/a/interview-blue-man-group-co-founder-phil-stanton
(SopelPython3)ant@ANTian:~/Downloads/bmg$ youtube-dl -v http://aplus.com/a/interview-blue-man-group-co-founder-phil-stanton
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://aplus.com/a/interview-blue-man-group-co-founder-phil-stanton']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.11.22
[debug] Python version 3.4.2 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.6
[debug] exe versions: ffmpeg 3.2-2, ffprobe 3.2-2, rtmpdump 2.4
[debug] Proxy map: {}
[generic] interview-blue-man-group-co-founder-phil-stanton: Requesting header
WARNING: Falling back on generic information extractor.
[generic] interview-blue-man-group-co-founder-phil-stanton: Downloading webpage
[generic] interview-blue-man-group-co-founder-phil-stanton: Extracting information
ERROR: Unsupported URL: http://aplus.com/a/interview-blue-man-group-co-founder-phil-stanton
Traceback (most recent call last):
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/common.py", line 357, in extract
    return self._real_extract(url)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2443, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: http://aplus.com/a/interview-blue-man-group-co-founder-phil-stanton

Thank you in advance. :)

**Comment by yan12125** [comment]
To developers: today.com (NBCNews) embed in <iframe>
