### ISSUE TITLE
Site Request: ITProTV 

### ISSUE THREAD

**Issue by Dedsec1** [rg3/youtube-dl#11304]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.11.22*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ ] I've **verified** and **I assure** that I'm running youtube-dl **2016.11.22**

### Before submitting an *issue* make sure you have:
- [ ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
youtube-dl -v https://itpro.tv/course-library/vmware-certified-professional-6-vcp6dcv/upgrading-vsphere-6-2/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'https://itpro.tv/course-library/vmware-certified-professional-6-vcp6dcv/upgrading-vsphere-6-2/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.11.22
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: none
[debug] Proxy map: {}
[generic] upgrading-vsphere-6-2: Requesting header
WARNING: Falling back on generic information extractor.
[generic] upgrading-vsphere-6-2: Downloading webpage
[generic] upgrading-vsphere-6-2: Extracting information
ERROR: Unsupported URL: https://itpro.tv/course-library/vmware-certified-professional-6-vcp6dcv/upgrading-vsphere-6-2/
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0yt5fyka\build\youtube_dl\YoutubeDL.py", line 694, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0yt5fyka\build\youtube_dl\extractor\common.py", line 357, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0yt5fyka\build\youtube_dl\extractor\generic.py", line 2443, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://itpro.tv/course-library/vmware-certified-professional-6-vcp6dcv/upgrading-vsphere-6-2/
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video:  https://player.vimeo.com/video/100816669?api=1&player_id=vimeoplayer
- Single video: https://player.vimeo.com/video/100816670?api=1&player_id=vimeoplayer

---

### Description of your *issue*, suggested solution and other information

site request for itpro.tv, 

i would like to request support for itpro.tv since i would like to have an cli based support for downloading videos from the site when i dont have good internet speeds or i would like to archive the videos to an remote server.  currently itpro.tv needs an paid account to download videos, you can signup for an trial account using the code TWIT30 when signing up.  they currently use two sources for video urls jw player and vimeo. the jw player links expire after 24 hours while the Vimeo links do not. 

you can download an Vimeo video using the following youtube-dl command,  youtube-dl -v "https://player.vimeo.com/video/170683353?api=1&player_id=vimeoplayer" --referer "https://itpro.tv/" 

or  youtube-dl -v "https://player.vimeo.com/video/170683353?api=1&player_id=vimeoplayer" --referer "https://itpro.tv/" --external-downloader aria2c --external-downloader-args='--max-connection-per-server=16 --split=20'

ITProTV provides the connection for self-study users and the real world experience that career IT people need to be successful. Because our shows are available Live everyday our content portfolio stays fresh and current. We are always covering the latest information of each topic geared toward I.T. candidates who desire to validate their skills/knowledge through vendor certification exams.

Thanks 

Dedsec1

**Comment by endeavorfrazer** [comment]
You may also try this method http://www.allavsoft.com/how-to/download-itprotv-courses.html

**Comment by beenfill** [comment]
You can use Allavsoft to download all online courses from the entire ITProTV course library into MP4, AVI, MOV, WMV, MP3, WAV, AAC, etc  and find it at
http://www.allavsoft.com/how-to/download-itprotv-courses.html
