### ISSUE TITLE
Site Request: Video reviews of Amazon.com products

### ISSUE THREAD

**Issue by hub2git** [rg3/youtube-dl#11300]
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2016.11.22**
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Site support request (request for adding support for a new site)

```
youtube-dl -v https://www.amazon.com/review/R2FXL7PRZNKELM/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://www.amazon.com/review/R2FXL7PRZNKELM/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.11.22
[debug] Python version 2.7.12 - Linux-4.4.0-47-generic-x86_64-with-LinuxMint-18-sarah
[debug] exe versions: avconv 2.8.8-0ubuntu0.16.04.1, avprobe 2.8.8-0ubuntu0.16.04.1, ffmpeg 2.8.8-0ubuntu0.16.04.1, ffprobe 2.8.8-0ubuntu0.16.04.1
[debug] Proxy map: {}
[generic] R2FXL7PRZNKELM: Requesting header
WARNING: Could not send HEAD request to https://www.amazon.com/review/R2FXL7PRZNKELM/: HTTP Error 405: MethodNotAllowed
[generic] R2FXL7PRZNKELM: Downloading webpage
WARNING: Falling back on generic information extractor.
[generic] R2FXL7PRZNKELM: Extracting information
ERROR: Unsupported URL: https://www.amazon.com/review/R2FXL7PRZNKELM/
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1636, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2526, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2515, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 14, column 37
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 357, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2443, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.amazon.com/review/R2FXL7PRZNKELM/

```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.amazon.com/review/R2FXL7PRZNKELM/

---

### Description of your *issue*, suggested solution and other information
I'd like to download videos of Amazon product reviews. :+1: :tada: :v: :video_camera:

**Comment by chocmake** [comment]
Sorry for the ping to the related users but if anyone is aware of how these can be downloaded, whether it be some separate script/etc it would be appreciated. Searched both DDG and Github but couldn't find relevant results.
