### ISSUE TITLE
Can't fetch video from ardmediathek.de: youtube-dl crashes

### ISSUE THREAD

**Issue by heis2201** [rg3/youtube-dl#11313]
- [x] I'm not running 2016.11.27 but whatever my distribution currently offers, which is  **2016.10.25**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:
```
$ youtube-dl --verbose  http://www.ardmediathek.de/tv/Filme-im-Ersten/Banklady/Das-Erste/Video?bcastId=1933898&documentId=39100244
[1] 8165
[debug] System config: ['--prefer-free-formats']
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.ardmediathek.de/tv/Filme-im-Ersten/Banklady/Das-Erste/Video?bcastId=1933898']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.10.25
[debug] Python version 3.5.2 - Linux-4.8.8-200.fc24.x86_64-x86_64-with-fedora-24-Twenty_Four
[debug] exe versions: ffmpeg 3.1.5, ffprobe 3.1.5
[debug] Proxy map: {}
[ARD:mediathek] Video: Downloading webpage
[ARD:mediathek] Video: Downloading media JSON
ERROR: Video: Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 558, in _parse_json
    return json.loads(json_string)
  File "/usr/lib64/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 558, in _parse_json
    return json.loads(json_string)
  File "/usr/lib64/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 693, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 356, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/ard.py", line 228, in _real_extract
    'http://www.ardmediathek.de/play/media/%s' % video_id, webpage, video_id)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/ard.py", line 81, in _extract_media_info
    media_info_url, video_id, 'Downloading media JSON')
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 552, in _download_json
    json_string, video_id, transform_source=transform_source, fatal=fatal)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 562, in _parse_json
    raise ExtractorError(errmsg, cause=ve)
youtube_dl.utils.ExtractorError: Video: Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by dstftw** [comment]
You have to either put the URL into quotes or manually escape all the special shell characters. Read [FAQ entry](https://github.com/rg3/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command) for details.

**Comment by heis2201** [comment]
Ha, Thanks. 

Even though reading through the FAQs, I didn't catch this one. Putting the URL in double quotes solves the problem. Thanks again!
