### ISSUE TITLE
Site Support Request for Esquire TV Network web site

### ISSUE THREAD

**Issue by jdunn0** [rg3/youtube-dl#11334]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.12.01*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.12.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v http://tv.esquire.com/now/team-ninja-warrior/full-episode/college-madness-pt-1-of-5/815232067537
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://tv.esquire.com/now/team-ninja-warrior/full-episode/college-madness-pt-1-of-5/815232067537']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.11.18
[debug] Python version 2.7.12 - Linux-4.4.21-gentoo-x86_64-Intel-R-_Core-TM-_i7-6700K_CPU_@_4.00GHz-with-gentoo-2.2
[debug] exe versions: ffmpeg 2.8.6, ffprobe 2.8.6, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 815232067537: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 815232067537: Downloading webpage
[generic] 815232067537: Extracting information
ERROR: Unsupported URL: http://tv.esquire.com/now/team-ninja-warrior/full-episode/college-madness-pt-1-of-5/815232067537
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/generic.py", line 1636, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/lib64/python2.7/site-packages/youtube_dl/compat.py", line 2526, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/lib64/python2.7/site-packages/youtube_dl/compat.py", line 2515, in _XML
    parser.feed(text)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 8, column 339
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/common.py", line 357, in extract
    return self._real_extract(url)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/generic.py", line 2433, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://tv.esquire.com/now/team-ninja-warrior/full-episode/college-madness-pt-1-of-5/815232067537
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Episode (Free to Watch): http://tv.esquire.com/now/team-ninja-warrior/full-episode/college-madness-pt-1-of-5/815232067537
- Episode (Requires TV Provider Authentication): http://tv.esquire.com/now/team-ninja-warrior/full-episode/college-madness-pt-2-of-5/819488835643

---

### Description of your *issue*, suggested solution and other information
I would like support for tv.esquire.com videos.
Some of the videos require TV Provider Authentication and some don't require it.

**Comment by jdunn0** [comment]
I recently figured out that I when I posted my last two bugs, I was using version 2016.11.18 instead of the current version 2016.12.01 so for this bug I ran youtube-dl again and updated the log above the new one.
Though it appears no difference was made as the error message is still the same.

Also, I found that when playing a video on Esquire TV, if you right click on the flash player, the menu shows "ThePlatform SDK" so I would guess Esquire TV is using ThePlatform which youtube-dl already supports for NBC, AMC, BBCAmericia and others so that may help when adding support for Esquire TV.

**Comment by jdunn0** [comment]
I decided to look at the file `extractor/theplatform.py` to see how the extractor for 'ThePlatform' works and see if it can be made to work with Esquire TV.
It seems that for supported URLs, it looks in HTML Code for an SMIL file that has the actual file URLs to download in it.
I looked at the source code in Google Chrome and found this line (easy to find by searching for 'theplatform'):
`<div data-tve-page-authz-player="pdk-player" data-src="//player.theplatform.com/p/HNK2IC/esquire_vod_noauth/embed/select/1sdIjHCVjypZ" data-release-url="//link.theplatform.com/s/HNK2IC/1sdIjHCVjypZ?mbr=true" data-id="pdk-player" data-mbr="true" data-fw-site-section="esquire_tveverywhere_vod_hub"></div>`
It appears the 'data-release-url' attribute contains the url of the SMIL file as the first line of the file is `<smil xmlns="http://www.w3.org/2005/SMIL21/Language">` and there are elements with a URL, bitrate, height and width specificed.
I saved the HTML code and the SMIL file and put them in this zip file [Esquire_Video.zip](https://github.com/rg3/youtube-dl/files/643608/Esquire_Video.zip).
I don't know enough about programming in python to make an extractor with this information myself but maybe this information can help someone who does and I can help test that extractor.

**Comment by jdunn0** [comment]
Hey, is there anything I can do to help move this issue forward (without writing the extractor myself as I'm not familiar enough with python to do that)?
I would really like to be able to download Team Ninja Warrior as Esquire doesn't provide an Android or Roku app and my cable provider doesn't provide Esquire TV in HD so using the web site is the only way to get HD or close to HD episodes of the show.

**Comment by citbr** [comment]
Just in case it might motivate the creators of youtube-dl a little, it appears that the format and platform for full episodes is virtually identical to that of E! Online, which I see has also been requested (https://github.com/rg3/youtube-dl/issues/6198).  So if you could create a working extractor for Esquire it would probably take all of two minutes after copying it to make it also work for E!, since the two sites appear to be virtual clones, at least in the way videos are presented.  You'd be adding two services for the effort of one! :)
