### ISSUE TITLE
Site support request: StuffYouShouldKnow.com podcasts

### ISSUE THREAD

**Issue by sfgasdfsafggfgg** [rg3/youtube-dl#11336]
---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.12.01*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.12.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other
---
#### Single audio:
```
$ youtube-dl -v "http://www.stuffyoushouldknow.com/podcasts/banned-kids-advertising.htm"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.stuffyoushouldknow.com/podcasts/banned-kids-advertising.htm']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.12.01
[debug] Python version 3.5.2 - Linux-4.8.10-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 3.2.1, ffprobe 3.2.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] banned-kids-advertising: Requesting header
WARNING: Falling back on generic information extractor.
[generic] banned-kids-advertising: Downloading webpage
[generic] banned-kids-advertising: Extracting information
ERROR: Unsupported URL: http://www.stuffyoushouldknow.com/podcasts/banned-kids-advertising.htm
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 357, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/generic.py", line 2433, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.stuffyoushouldknow.com/podcasts/banned-kids-advertising.htm
<end of log>
```
#### Playlist:
```
$ youtube-dl -v "http://www.stuffyoushouldknow.com/tags/animals.htm"                                                                            
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.stuffyoushouldknow.com/tags/animals.htm']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.12.01
[debug] Python version 3.5.2 - Linux-4.8.10-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 3.2.1, ffprobe 3.2.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] animals: Requesting header
WARNING: Falling back on generic information extractor.
[generic] animals: Downloading webpage
[generic] animals: Extracting information
ERROR: Unsupported URL: http://www.stuffyoushouldknow.com/tags/animals.htm
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 357, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/generic.py", line 2433, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.stuffyoushouldknow.com/tags/animals.htm
```
---

### Example URLs:
- Single audio: http://www.stuffyoushouldknow.com/podcasts/banned-kids-advertising.htm
- Playlist: http://www.stuffyoushouldknow.com/tags/animals.htm

---

**Comment by yan12125** [comment]
Uses JPlayer
