### ISSUE TITLE
[BUG] AttributeError: 'NoneType' rtbf.be broken?

### ISSUE THREAD

**Issue by Animis09** [rg3/youtube-dl#11344]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.12.01*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.12.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
---

```
youtube-dl -v http://www.rtbf.be/auvio/detail_04-documentaires-de-la-bbc-bebes-pandas?id=2158373
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.rtbf.be/auvio/detail_04-documentaires-de-la-bbc-bebes-pandas?id=2158373']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.12.01
[debug] Python version 2.7.3 - Linux-3.14.32-xxxx-grs-ipv6-64-x86_64-with-Debian-7
[debug] exe versions: ffmpeg 2.2.2, ffprobe 2.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[RTBF] 2158373: Downloading JSON metadata
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 444, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 434, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1791, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 694, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 357, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/rtbf.py", line 66, in _real_extract
AttributeError: 'NoneType' object has no attribute 'get'
```

---

Thank you for your help.

**Comment by dstftw** [comment]
>Erreur 404
Cette page est introuvable
