### ISSUE TITLE
Site support request for 9jumpin.com.au

### ISSUE THREAD

**Issue by rominatrix** [rg3/youtube-dl#11379]
While trying to download a video, using the latest version of youtube-dl, it says that the url is unsopported. So this is a site support request for the website 9jumpin.com.au

This is a url example:  http://www.9jumpin.com.au/show/today/today-takeaway/2016/december/is-benedict-cumberbatch-headed-for-australia/

From what I was able to make out this website uses brightcove which has in the past usually worked with youtube-dl. I was unable to obtain the direct brightcove url to the video though but usually youtube-dl obtains it iself.

[x] I've **verified** and **I assure** that I'm running youtube-dl **2016.12.01**

```
D:\ytdl>youtube-dl.exe -v http://www.9jumpin.com.au/show/today/today-tak
eaway/2016/december/is-benedict-cumberbatch-headed-for-australia/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.9jumpin.com.au/show/today/today-ta
keaway/2016/december/is-benedict-cumberbatch-headed-for-australia/']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.12.01
[debug] Python version 3.4.4 - Windows-7-6.1.7600-SP0
[debug] exe versions: ffmpeg N-73696-g8250943, ffprobe N-73696-g8250943, rtmpdum
p 2.4
[debug] Proxy map: {}
[generic] is-benedict-cumberbatch-headed-for-australia: Requesting header
WARNING: Falling back on generic information extractor.
[generic] is-benedict-cumberbatch-headed-for-australia: Downloading webpage
[generic] is-benedict-cumberbatch-headed-for-australia: Extracting information
ERROR: Unsupported URL: http://www.9jumpin.com.au/show/today/today-takeaway/2016
/december/is-benedict-cumberbatch-headed-for-australia/
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6j6yd3lp\build\youtube_dl\YoutubeDL.py", line 694, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6j6yd3lp\build\youtube_dl\extractor\common.py", line 357, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6j6yd3lp\build\youtube_dl\extractor\generic.py", line 2433, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.9jumpin.com.au/show/today/today-takeaway/2016/december/is-benedict-cumberbatch-headed-for-austral
ia/
<end of log>
```

**Comment by rominatrix** [comment]
I don't know if this is useful or not but I managed to obtain download links with the following url (for this case), considering that the video_id i obtained from a brightcove url in the requests (videoPlayer=5235492073001), and the token also from one one the requests but I can't remember right now in which but the parameter was token nonetheless. The command i just tried a few and got it to work.
This link provided me with a json message with several links to different mp4 files. 

`http://api.brightcove.com/services/library?media_delivery=http&video_id=5235492073001&command=find_video_by_id&token=Vb3fqavTKFDDZbnnGGtbhKxam7uHduOnob-2MJlpHmUnzSMWbDe5bg..`

Hope this helps.
