### ISSUE TITLE
Downloading from southpark.cc.com fails.

### ISSUE THREAD

**Issue by timlenertz** [rg3/youtube-dl#11405]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.12.09*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.12.09**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
sh-3.2$ youtube-dl -v http://southpark.cc.com/full-episodes/s20e10-the-end-of-serialization-as-we-know-it#source=06bb4aa7-9917-4b6a-ae93-5ed7be79556a:879fd28e-c96b-4f9d-a437-e05c1bcf80aa&position=10
[1] 13081
sh-3.2$ [debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://southpark.cc.com/full-episodes/s20e10-the-end-of-serialization-as-we-know-it#source=06bb4aa7-9917-4b6a-ae93-5ed7be79556a:879fd28e-c96b-4f9d-a437-e05c1bcf80aa']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.12.09
[debug] Python version 2.7.12 - Darwin-16.1.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.8.4, ffprobe 2.8.4, rtmpdump 2.4
[debug] Proxy map: {}
[southpark.cc.com] s20e10-the-end-of-serialization-as-we-know-it: Downloading webpage
[southpark.cc.com] 2c762ec7-8b59-4628-bd23-416a3dd6136d: Downloading info
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 444, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 434, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1791, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 694, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 357, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/mtv.py", line 232, in _real_extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/mtv.py", line 191, in _get_videos_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/mtv.py", line 196, in _get_videos_info_from_url
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 540, in _download_xml
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2526, in compat_etree_fromstring
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2515, in _XML
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: mismatched tag: line 128, column 196

[1]+  Done(1)                 youtube-dl -v http://southpark.cc.com/full-episodes/s20e10-the-end-of-serialization-as-we-know-it#source=06bb4aa7-9917-4b6a-ae93-5ed7be79556a:879fd28e-c96b-4f9d-a437-e05c1bcf80aa
sh-3.2$ 
```

---

### Description of your *issue*, suggested solution and other information

Downloading from southpark.cc.com fails. Using OS X 10.12.1, with Python 2.7.12.

**Comment by dstftw** [comment]
You have to either put the URL into quotes or manually escape all the special shell characters. Read [FAQ entry](https://github.com/rg3/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command) for details.
