### ISSUE TITLE
youtubedl requesting source url of embeded video but isnt able to extract video url out of it

### ISSUE THREAD

**Issue by treakiandroid** [rg3/youtube-dl#11440]
youtubedl requesting source url of embeded video but isnt able to extract video url out of it

the following output should explain everything:

```
user@host:/tmp$ youtube-dl -v 'https://player.vimeo.com/video/190073274?autoplay=1&color=95c11e'
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://player.vimeo.com/video/190073274?autoplay=1&color=95c11e']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.11.02
[debug] Python version 2.7.9 - Linux-4.2.0-0.bpo.1-amd64-x86_64-with-debian-8.6
[debug] exe versions: ffmpeg 2.8.8, ffprobe 2.8.8, rtmpdump 2.4
[debug] Proxy map: {}
[vimeo] 190073274: Downloading webpage
ERROR: Cannot download embed-only video without embedding URL. Please call youtube-dl with the URL of the page that embeds this video.
Traceback (most recent call last):
  File "/home/treaki/bin/youtube-dl/youtube_dl/extractor/vimeo.py", line 433, in _real_extract
    webpage, urlh = self._download_webpage_handle(request, video_id)
  File "/home/treaki/bin/youtube-dl/youtube_dl/extractor/common.py", line 424, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "/home/treaki/bin/youtube-dl/youtube_dl/extractor/common.py", line 413, in _request_webpage
    raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
ExtractorError: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/treaki/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/home/treaki/bin/youtube-dl/youtube_dl/extractor/common.py", line 357, in extract
    return self._real_extract(url)
  File "/home/treaki/bin/youtube-dl/youtube_dl/extractor/vimeo.py", line 447, in _real_extract
    expected=True)
ExtractorError: Cannot download embed-only video without embedding URL. Please call youtube-dl with the URL of the page that embeds this video.

user@host:/tmp$ youtube-dl -v http://knockknockhq.com/project/calvin-harris-my-way
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://knockknockhq.com/project/calvin-harris-my-way']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.11.02
[debug] Python version 2.7.9 - Linux-4.2.0-0.bpo.1-amd64-x86_64-with-debian-8.6
[debug] exe versions: ffmpeg 2.8.8, ffprobe 2.8.8, rtmpdump 2.4
[debug] Proxy map: {}
[generic] calvin-harris-my-way: Requesting header
WARNING: Falling back on generic information extractor.
[generic] calvin-harris-my-way: Downloading webpage
[generic] calvin-harris-my-way: Extracting information
ERROR: Unsupported URL: http://knockknockhq.com/project/calvin-harris-my-way
Traceback (most recent call last):
  File "/home/treaki/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1634, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/home/treaki/bin/youtube-dl/youtube_dl/compat.py", line 2525, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/home/treaki/bin/youtube-dl/youtube_dl/compat.py", line 2514, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 23, column 16
Traceback (most recent call last):
  File "/home/treaki/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/home/treaki/bin/youtube-dl/youtube_dl/extractor/common.py", line 357, in extract
    return self._real_extract(url)
  File "/home/treaki/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2417, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://knockknockhq.com/project/calvin-harris-my-way

user@host:/tmp$ wget http://knockknockhq.com/project/calvin-harris-my-way
--2016-12-14 09:51:19--  http://knockknockhq.com/project/calvin-harris-my-way
Auflösen des Hostnamen »knockknockhq.com (knockknockhq.com)«... 212.110.164.166
Verbindungsaufbau zu knockknockhq.com (knockknockhq.com)|212.110.164.166|:80... verbunden.
HTTP-Anforderung gesendet, warte auf Antwort... 200 OK
Länge: nicht spezifiziert [text/html]
In »»calvin-harris-my-way«« speichern.

calvin-harris-my-wa     [ <=>                  ]  15,13K  --.-KB/s   in 0,1s   

2016-12-14 09:51:20 (108 KB/s) - »calvin-harris-my-way« gespeichert [15490]

user@host:/tmp$ cat calvin-harris-my-way | grep vimeo
		<script src="https://f.vimeocdn.com/js/froogaloop2.min.js"></script>
							<div class="js-vimeo btn btn--work slider__btn"  data-vimeo="https://vimeo.com/190073274">
user@host:/tmp$ #so where is the problem??
```

**Comment by treakiandroid** [comment]
maybe you could add an option to input the source url of the embedded iframe using an cli parameter, than you would be able to send the needed refer url to vimeo and don't have to extract the embedded video yourself. thanks in advance

**Comment by yan12125** [comment]
> maybe you could add an option to input the source url of the embedded iframe using an cli parameter

Yep there's an option ```--referer```
```
youtube-dl --referer "http://knockknockhq.com/project/calvin-harris-my-way" "https://player.vimeo.com/video/190073274?autoplay=1&color=95c11e"
```
