### ISSUE TITLE
Disney XD -- Unable to downloaded protected videos even with login cookies.

### ISSUE THREAD

**Issue by keybounce** [rg3/youtube-dl#11468]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.12.15*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2016.12.15**

### Before submitting an *issue* make sure you have:
- x[ ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x ] Site support request (request for adding support for a new site)
- [x ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

```
keybounceMBP:Rebels michael$ youtube-dl -v --cookie ~/Dish-cookies.txt 'http://watchdisneyxd.go.com/star-wars-
rebels/video/vdka3428924/03/03-the-antilles-extraction#playlist=PL553400298'
[debug] System config: []
[debug] User config: [u'-o', u'%(title)s.%(ext)s', u'-f', u'\nbest[ext=mp4][height>431][height<=480]/\nbest[ext=mp4][height>431][height<=576]/\nbestvideo[ext=mp4][height=480]+bestaudio[ext=m4a]/\nbest[ext=mp4][height>340][height<=431]/\nbestvideo[ext=mp4][height>360][height<=576]+bestaudio/\nbest[height>340][height<=576]/\nbestvideo[height>360][height<=576]+bestaudio/\nbestvideo[height=360]+bestaudio/\nbest[ext=mp4][height>=280][height<=360]/\nbest[height<=576]/\nworst', u'--write-sub', u'--write-auto-sub', u'--sub-lang', u'en,enUS', u'--sub-format', u'srt/ass/best', u'--embed-subs', u'--recode-video', u'mp4', u'--mark-watched']
[debug] Command-line args: [u'-v', u'--cookie', u'/Users/michael/Dish-cookies.txt', u'http://watchdisneyxd.go.com/star-wars-rebels/video/vdka3428924/03/03-the-antilles-extraction#playlist=PL553400298']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.12.15
[debug] Python version 2.7.5 - Darwin-13.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.2, ffprobe 3.2, rtmpdump 2.4
[debug] Proxy map: {}
[Go] 3428924: Downloading JSON metadata
[Go] 3428924: Downloading JSON metadata
ERROR: Go said: 1007:Unable to retrieve required files for playback. Please try again in a few minutes.
Traceback (most recent call last):
  File "/Users/michael/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/Users/michael/bin/youtube-dl/youtube_dl/extractor/common.py", line 357, in extract
    return self._real_extract(url)
  File "/Users/michael/bin/youtube-dl/youtube_dl/extractor/go.py", line 74, in _real_extract
    raise ExtractorError('%s said: %s' % (self.IE_NAME, error_message), expected=True)
ExtractorError: Go said: 1007:Unable to retrieve required files for playback. Please try again in a few minutes.

keybounceMBP:Rebels michael$ 
```

The first two episodes -- not protected -- downloaded just fine.
The cookie file used was generated by logging into the site through dish.

So, this is a login-related issue. I am providing the login cookies. Still not working. Help please.

(Search oddity: A search for 'disneyxd' returns no hits??? Clearly my searching was a failure.)

**Comment by keybounce** [comment]
Ok, so searching for "Disney XD" with a space turns up several hits for disney and references to XD. Real sadface: I authored most of them :-)

Good news: The unprotected ones now download (a few months ago, those did not).
Bad news: Is there any way to use adobe flash cookies with youtube-dl?

**Comment by RuneMagle** [comment]
This happens to me also! O_O

```
C:\Users\rumag\Desktop\youtube-dl>youtube-dl.exe -f best --embed-subs --all-subs --convert-subs srt --username LikeImgonnaShowU --password NoneOfYourBusiness --ap-username somethingPrivate --ap-password ifUreadThisLol --ap-mso DTV --no-check-certificate http://watchdisneychannel.go.com/girl-meets-world/video/vdka3613338/03/19-world-meets-girl -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'best', '--embed-subs', '--all-subs', '--convert-subs', 'srt', '--username', 'PRIVATE', '--password', 'PRIVATE', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '--ap-mso', 'DTV', '--no-check-certificate', 'http://watchdisneychannel.go.com/girl-meets-world/video/vdka3613338/03/19-world-meets-girl', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.01.05
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-82889-g54931fd
[debug] Proxy map: {}
[Go] 3613338: Downloading JSON metadata
[Go] 3613338: Downloading JSON metadata
ERROR: Go said: 1007:Unable to retrieve required files for playback. Please try again in a few minutes.
```

**Comment by RuneMagle** [comment]
WHY IS NOBODY FIXING IT?! I'M FREAKN' OUT!
