### ISSUE TITLE
youtube-dl http://groovemp3.com/track/120593577

### ISSUE THREAD

**Issue by asansli** [rg3/youtube-dl#11487]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.12.18*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.12.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
da@xps15z:~$ youtube-dl -v http://groovemp3.com/track/120593577
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://groovemp3.com/track/120593577']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.12.18
[debug] Python version 2.7.12 - Linux-4.4.0-53-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 2.8.10-0ubuntu0.16.04.1, avprobe 2.8.10-0ubuntu0.16.04.1, ffmpeg 2.8.10-0ubuntu0.16.04.1, ffprobe 2.8.10-0ubuntu0.16.04.1
[debug] Proxy map: {}
[generic] 120593577: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 120593577: Downloading webpage
[generic] 120593577: Extracting information
ERROR: Unsupported URL: http://groovemp3.com/track/120593577
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1626, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2526, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2515, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: mismatched tag: line 44, column 6
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 357, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2433, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://groovemp3.com/track/120593577

da@xps15z:~$ 
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://groovemp3.com/track/120593577
---

### Description of your *issue*, suggested solution and other information

Would you add http://groovemp3.com to supported sites? Thanks.

**Comment by yan12125** [comment]
Apparently http://groovemp3.com/track/120593577 is gone. Do you have new examples?

**Comment by asansli** [comment]
http://groovemp3.com/track/18413551

**Comment by yan12125** [comment]
In Firefox this URL redirects to http://groovemp3.com/album/The+Weeknd/Starboy. Is it expected?

Apparently this website is just a wrapper of YouTube videos. For example the first song in http://groovemp3.com/album/The+Weeknd/Starboy is actually https://www.youtube.com/watch?v=34Na4j8AVgA

**Comment by asansli** [comment]
I did not checked if the urls were linked to YouTube.

Album is correct. Choosed one of popular.
