### ISSUE TITLE
Mac OS X El Capitan pip install OSError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by matrixko** [rg3/youtube-dl#11509]
Hi,
Sorry to bother you but I can't manage to install your program (it looks awesome by the way, I would love to have it !) 
I tried to use the command `pip install youtube-dl` but I get the following 

```
MacBook-Pro-de-lukitsa:~ lukitsa$ pip install youtube-dl
Collecting youtube-dl
  Using cached youtube_dl-2016.12.22-py2.py3-none-any.whl
Installing collected packages: youtube-dl
Exception:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip/wheel.py", line 377, in move_wheel_files
    clobber(source, dest, False, fixer=fixer, filter=filter)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
**OSError: [Errno 13] Permission denied: '/Library/Frameworks/Python.framework/Versions/2.7/share/doc/youtube_dl'**
```

Is there anyone who can help me with this ? By the way I am on Mac OS X 10.11.6 El Capitan and unfortunately I can't use any other installation way like Homebrew because of my work. They use program and didn't allow you to change any main architecture of your mac (unless you don't want support anymore.. sorry)
Many thanks in advance for your help

**Comment by dstftw** [comment]
Read [FAQ](https://github.com/rg3/youtube-dl#installation) and copy paste pip command from there.

**Comment by matrixko** [comment]
Thank you for your reply but that's what I did. They say that you have to use `sudo` but I can't use this command. Is there any other way ?

**Comment by yan12125** [comment]
```pip install youtube-dl --user``` and add ```$HOME/Library/Python/2.7/bin``` to ```$PATH```

**Comment by matrixko** [comment]
Thanks for helping @yan12125 but I don't have the folder `/Library/Python/2.7/bin`, I only have `/Library/Python/2.7` and in there, there is only a `site-packages` folder.. Sorry I really am a beginner in programming and stuff

**Comment by yan12125** [comment]
```$HOME/Library/Python/2.7/bin```, not ```/Library/Python/2.7/bin```. You can also use ```~/Library/Python/2.7/bin```

**Comment by matrixko** [comment]
Okay thanks but where do I add `$HOME/Library/Python/2.7/bin` to `path` ? I'm really sorry I know you just gave me the answer but I can't figure out exactly what I have to write in the terminal.

**Comment by yan12125** [comment]
Like this:
```
export PATH="$HOME/Library/Python/2.7/bin:$PATH"
```
