### ISSUE TITLE
[facebook] RegexNotFoundError: Unable to extract server js data

### ISSUE THREAD

**Issue by radiocane** [rg3/youtube-dl#11514]
### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)

```
bruno@jeeg:~/src/youtube-dl/bin$ ./youtube-dl --verbose https://www.facebook.com/video.php?v=10153746866670196
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://www.facebook.com/video.php?v=10153746866670196']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.22
[debug] Python version 2.7.11+ - Linux-4.4.0-22-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.6-1ubuntu2, ffprobe 2.8.6-1ubuntu2, rtmpdump 2.4
[debug] Proxy map: {}
[facebook] 10153746866670196: Downloading webpage
ERROR: Unable to extract server js data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 666, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 316, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/facebook.py", line 188, in _real_extract
    r'handleServerJS\(({.+})\);', webpage, 'server js data'), video_id)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 611, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract server js data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

### Description of your *issue*, suggested solution and other information
I can see the video in Firefox (Ubuntu) with the given URL without login. youtube-dl does not download it.

**Comment by yan12125** [comment]
> [debug] youtube-dl version 2016.02.22

It's too old. Please upgrade to the latest version (2016.12.22), which is working:
```
$ youtube-dl -v "https://www.facebook.com/video.php?v=10153746866670196" 
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'https://www.facebook.com/video.php?v=10153746866670196']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.12.22
[debug] Git HEAD: 19f37ce4b
[debug] Python version 3.5.2 - Linux-4.8.13-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 3.2.2, ffprobe 3.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[facebook] 10153746866670196: Downloading webpage
[debug] Invoking downloader on 'https://video-tpe1-1.xx.fbcdn.net/v/t42.1790-2/12433540_423938111136426_1680795630_n.mp4?efg=eyJ2ZW5jb2RlX3RhZyI6InN2ZV9zZCJ9&oh=e3c0c278c4fc33904260a270b55e98fc&oe=585D3C05'
[download] Destination: E  CHE VIGILIA SIA!!!!Buon Natale dai Pellagra !!!!Pellagra domina anche a...-10153746866670196.mp4
[download] 100% of 3.03MiB in 00:01
```

**Comment by radiocane** [comment]
I'm so sorry for this useless issue: I didn't doublecheck the --verbose output and I didn't realize that running the "bin/youtube-dl" script loaded the system outdated version instead of the updated one I had just cloned.
Thanks for the great software :)
