### ISSUE TITLE
DiscoveryGO.com - Can no longer download videos

### ISSUE THREAD

**Issue by Mr-Jake** [rg3/youtube-dl#11522]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.12.22*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.12.22**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```

C:\>youtube-dl\youtube-dl.exe "https://www.discoverygo.com/alaska-the-last-frontier/homesteading-for-the-holidays/" -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['https://www.discoverygo.com/alaska-the-last-frontier/homesteading-for-the-holidays/', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.12.22
[debug] Python version 3.4.4 - Windows-XP-5.1.2600-SP3
[debug] exe versions: ffmpeg n3.1.2, ffprobe n3.1.2, rtmpdump 2.4
[debug] Proxy map: {}
[DiscoveryGo] homesteading-for-the-holidays: Downloading webpage
ERROR: homesteading-for-the-holidays: Failed to parse JSON  (caused by ValueError("Expecting ',' delimiter: line 1 column 24418 (char 24417)",)); please report
this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose
flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptqqgo4yk\build\youtube_dl\extractor\common.py", line 560, in _parse_json
  File "C:\Python\Python34\lib\json\__init__.py", line 318, in loads
  File "C:\Python\Python34\lib\json\decoder.py", line 343, in decode
  File "C:\Python\Python34\lib\json\decoder.py", line 359, in raw_decode
ValueError: Expecting ',' delimiter: line 1 column 24418 (char 24417)
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptqqgo4yk\build\youtube_dl\extractor\common.py", line 560, in _parse_json
  File "C:\Python\Python34\lib\json\__init__.py", line 318, in loads
  File "C:\Python\Python34\lib\json\decoder.py", line 343, in decode
  File "C:\Python\Python34\lib\json\decoder.py", line 359, in raw_decode
ValueError: Expecting ',' delimiter: line 1 column 24418 (char 24417)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptqqgo4yk\build\youtube_dl\YoutubeDL.py", line 694, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptqqgo4yk\build\youtube_dl\extractor\common.py", line 358, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptqqgo4yk\build\youtube_dl\extractor\discoverygo.py", line 53, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptqqgo4yk\build\youtube_dl\extractor\common.py", line 564, in _parse_json
youtube_dl.utils.ExtractorError: homesteading-for-the-holidays: Failed to parse JSON  (caused by ValueError("Expecting ',' delimiter: line 1 column 24418 (char24417)",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

C:\>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):

https://www.discoverygo.com/alaska-the-last-frontier/homesteading-for-the-holidays/

---

### Description of your *issue*, suggested solution and other information

youtube-dl  can  no longer download videos from discoverygo.com (animalplanetgo.com, sciencechannelgo.com, etc). I have posted the error log above. While most videos require a cable company login, I have posted a free video link that does not require a login. The last time youtube-dl was able to download from  discoverygo.com was early December 2016.

**Comment by StevenDTX** [comment]
Actually, it hasnt worked since early November.  This is a duplicate of https://github.com/rg3/youtube-dl/issues/11219

**Comment by Mr-Jake** [comment]
Thanks @StevenDTX

Did that "hack" work for you? I tried it without success. But I think I put it in the wrong line of common.py. It says line 559, but common.py was edited since then and I don't know what release that was intended for.

Would you know under what line I would insert the "hack"?

Line 559 is in this function of common.py:
```
    def _parse_json(self, json_string, video_id, transform_source=None, fatal=True):
        if transform_source:
            json_string = transform_source(json_string)
        try:
            return json.loads(json_string)
        except ValueError as ve:
            errmsg = '%s: Failed to parse JSON ' % video_id
            if fatal:
                raise ExtractorError(errmsg, cause=ve)
            else:
                self.report_warning(errmsg + str(ve))
```


Code by KyleBS:
```
for i in xrange(json_string.count('"&lt;?xml version="1.0" encoding="UTF-8"?> <VAST')):
        start = json_string.find('"&lt;?xml version="1.0" encoding="UTF-8"?> <VAST')
        end = json_string.find('VAST> "') + len('VAST> "')
        json_string = json_string[:start] + json_string[end:]

```

**Comment by KyleBS** [comment]
Updated the original comment to use 'git diff' -- should have the commit id I am on and a bit of context.

**Comment by breffasst** [comment]
Thanks @KyleBS 

I applied your diff and it works perfectly now.

**Comment by Mr-Jake** [comment]
Thanks @KyleBS for updating. The diff was easy to apply and DiscoveryGO now works with cookies.
