### ISSUE TITLE
Cannot download video from youku

### ISSUE THREAD

**Issue by jzjsuper** [rg3/youtube-dl#11543]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.12.22*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.12.22**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v http://v.youku.com/v_show/id_XMTM5NDM5ODYwOA==.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://v.youku.com/v_show/id_XMTM5NDM5ODYwOA==.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.12.22
[debug] Python version 2.7.13 - Darwin-15.6.0-x86_64-i386-64bit
[debug] exe versions: avconv 11.4, avprobe 11.4, ffmpeg 3.2.2, ffprobe 3.2.2
[debug] Proxy map: {}
[youku] XMTM5NDM5ODYwOA: Downloading JSON metadata
ERROR: XMTM5NDM5ODYwOA: Failed to parse JSON  (caused by ValueError('No JSON object could be decoded',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 560, in _parse_json
    return json.loads(json_string)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 358, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youku.py", line 234, in _real_extract
    data = retrieve_data(basic_data_url, 'Downloading JSON metadata')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youku.py", line 223, in retrieve_data
    raw_data = self._download_json(req_url, video_id, note=note, headers=headers)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 554, in _download_json
    json_string, video_id, transform_source=transform_source, fatal=fatal)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 564, in _parse_json
    raise ExtractorError(errmsg, cause=ve)
ExtractorError: XMTM5NDM5ODYwOA: Failed to parse JSON  (caused by ValueError('No JSON object could be decoded',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

---

### Description of your *issue*, suggested solution and other information

Cannot download video from youku

**Comment by yan12125** [comment]
Works for me:
```
$ youtube-dl -v "http://v.youku.com/v_show/id_XMTM5NDM5ODYwOA==.html" 
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://v.youku.com/v_show/id_XMTM5NDM5ODYwOA==.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.12.22
[debug] Git HEAD: b63005f5a
[debug] Python version 3.5.2 - Linux-4.8.13-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 3.2.2, ffprobe 3.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[youku] XMTM5NDM5ODYwOA: Downloading JSON metadata
[download] Downloading playlist: 万万没想到 第三季 04 大锤闪婚结婚照曝光 娇妻为哈佛高材生
[youku] playlist 万万没想到 第三季 04 大锤闪婚结婚照曝光 娇妻为哈佛高材生: Collected 3 video ids (downloading 3 of them)
[download] Downloading video 1 of 3
[debug] Invoking downloader on 'http://k.youku.com/player/getFlvPath/sid/948284539371812e5286a_00/st/flv/fileid/030001030056547612BD8D06257BB623E378D1-3B75-5D21-7DA3-72A08F676DE6?hd=1&ypp=0&token=4144&ep=eyacGEGJU80J5iTegD8bMingfHFeXP4J9h%2BFgNJhALshTu27njjQxe%2FERotCEPscdVB0Funy3tPgYjQVYfMxrm0Q2jqqOPrnioHg5apRtZAIEB8xdLmislSaQjT1&oip=2356157543&ctype=12&myp=0&ev=1&K=29e3f3b45d4bfd30282bfeee'
[download] Destination: 万万没想到 第三季 04 大锤闪婚结婚照曝光 娇妻为哈佛高材生-XMTM5NDM5ODYwOA_part1.flv
[download]  17.9% of 32.08MiB at 404.31KiB/s ETA 01:06^CException ignored in: <_io.FileIO name='万万没想到 第三季 04 大锤闪婚结婚照曝光 娇妻为哈佛高材生-XMTM5NDM5ODYwOA_part1.flv.part' mode='wb' closefd=True>
ResourceWarning: unclosed file <_io.BufferedWriter name='万万没想到 第三季 04 大锤闪婚结婚照曝光 娇妻为哈佛高材生-XMTM5NDM5ODYwOA_part1.flv.part'>

ERROR: Interrupted by user
```

Could you paste the output of:
```
curl -v "http://play.youku.com/play/get.json?vid=XMTM5NDM5ODYwOA&ct=12"
```

**Comment by jzjsuper** [comment]
It works after I changed my DNS server.
