### ISSUE TITLE
Crunchyroll login

### ISSUE THREAD

**Issue by kaduuchiha** [rg3/youtube-dl#11552]
youtube-dl -u xxxx -p xxx --verbose "http://www.crunchyroll.com/brave-witches" --write-sub --sub-lang ptBR --playlist-start 1 -skip-download
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-u', 'PRIVATE', '-p', 'PRIVATE', '--verbose', 'http://www.crunchyroll.com/brave-witches', '--write-sub', '--sub-lang', 'ptBR', '--playlist-start', '1', '-skip-download']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.12.22
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-82794-g3ab1311, ffprobe N-82794-g3ab1311, rtmpdump 2.3
[debug] Proxy map: {}
[crunchyroll:playlist] Downloading login page
[crunchyroll:playlist] Logging in
ERROR: Unable to login: Captcha inválido. Tente novamente.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptqqgo4yk\build\youtube_dl\YoutubeDL.py", line 694, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptqqgo4yk\build\youtube_dl\extractor\common.py", line 357, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptqqgo4yk\build\youtube_dl\extractor\common.py", line 351, in initialize
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptqqgo4yk\build\youtube_dl\extractor\crunchyroll.py", line 91, in _real_initialize
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptqqgo4yk\build\youtube_dl\extractor\crunchyroll.py", line 86, in _login
youtube_dl.utils.ExtractorError: Unable to login: Captcha inválido. Tente novamente.

**Comment by dstftw** [comment]
Go to www.crunchyroll.com, solve captcha, then [export cookies and pass to youtube-dl](https://github.com/rg3/youtube-dl#how-do-i-pass-cookies-to-youtube-dl).
