### ISSUE TITLE
Can't download from youtube

### ISSUE THREAD

**Issue by mosheDO** [rg3/youtube-dl#11610]
---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.01.05*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.01.05**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
```
C:\Apps>youtube-dl.exe -v https://www.youtube.com/watch?v=6ACl8s_tBzE
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=6ACl8s_tBzE']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.01.05
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] 6ACl8s_tBzE: Downloading webpage
[youtube] 6ACl8s_tBzE: Downloading video info webpage
[youtube] 6ACl8s_tBzE: Extracting video information
WARNING: unable to extract uploader nickname
[youtube] 6ACl8s_tBzE: Downloading embed webpage
[youtube] {22} signature length 42.41, html5 player en_US-vfla6wgHS
[youtube] 6ACl8s_tBzE: Downloading player https://s.ytimg.com/yts/jsbin/player-en_US-vfla6wgHS/base.js
[youtube] {43} signature length 42.41, html5 player en_US-vfla6wgHS
[youtube] {18} signature length 42.41, html5 player en_US-vfla6wgHS
[youtube] {36} signature length 42.41, html5 player en_US-vfla6wgHS
[youtube] {17} signature length 42.41, html5 player en_US-vfla6wgHS
[youtube] {137} signature length 42.41, html5 player en_US-vfla6wgHS
[youtube] {248} signature length 42.41, html5 player en_US-vfla6wgHS
[youtube] {136} signature length 42.41, html5 player en_US-vfla6wgHS
[youtube] {247} signature length 42.41, html5 player en_US-vfla6wgHS
[youtube] {135} signature length 42.41, html5 player en_US-vfla6wgHS
[youtube] {244} signature length 42.41, html5 player en_US-vfla6wgHS
[youtube] {134} signature length 42.41, html5 player en_US-vfla6wgHS
[youtube] {243} signature length 42.41, html5 player en_US-vfla6wgHS
[youtube] {133} signature length 42.41, html5 player en_US-vfla6wgHS
[youtube] {242} signature length 42.41, html5 player en_US-vfla6wgHS
[youtube] {160} signature length 42.41, html5 player en_US-vfla6wgHS
[youtube] {278} signature length 42.41, html5 player en_US-vfla6wgHS
[youtube] {140} signature length 42.41, html5 player en_US-vfla6wgHS
[youtube] {171} signature length 42.41, html5 player en_US-vfla6wgHS
[youtube] {249} signature length 42.41, html5 player en_US-vfla6wgHS
[youtube] {250} signature length 42.41, html5 player en_US-vfla6wgHS
[youtube] {251} signature length 42.41, html5 player en_US-vfla6wgHS
[debug] Invoking downloader on 'https://r4---sn-gphvo-ua8e.googlevideo.com/videoplayback?initcwndbps=22512500&requiressl=yes&key=yt6&mime=video%2Fmp4&mv=m&ratebypass=yes&ip=95.86.122.78&ms=au&sparams=dur%2Cgcr%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&gcr=il&mt=1483610497&id=o-AO5vgzBZyeYcd2AcPWJysqXKIG1bRBpMQNnsvv0pGWon&mn=sn-gphvo-ua8e&mm=31&upn=5Din8vDzbHo&source=youtube&pl=21&itag=22&lmt=1479243066176825&dur=255.071&ipbits=0&expire=1483632323&signature=8D0A3D1936B36AE129CEED21AB38DC8C03D9C84FA.C54CD7447A9522299B71F279C05AB71B9CE8A87C4'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp023qj2d_\build\youtube_dl\YoutubeDL.py", line 1699, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp023qj2d_\build\youtube_dl\YoutubeDL.py", line 1641, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp023qj2d_\build\youtube_dl\downloader\common.py", line 353, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp023qj2d_\build\youtube_dl\downloader\http.py", line 61, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp023qj2d_\build\youtube_dl\YoutubeDL.py", line 2001, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden
...
<end of log>
```

---

### Description of your *issue*, suggested solution and other information

When i try to download it dosn't work like

https://www.youtube.com/watch?v=6ACl8s_tBzE

I'm using the program on windows.

**Comment by Tony-il-Capo** [comment]
It works for me. Like shizeeg said, your IP at that time probably reached request limit, 'HTTP Error 403: Forbidden'

**Comment by mosheDO** [comment]
Its working fine again.
thanks
