### ISSUE TITLE
Signature extraction failed: Traceback (most recent call last)

### ISSUE THREAD

**Issue by linglung** [rg3/youtube-dl#11663]
The title says about this issue.
Before creating this issue, i already search and read some issues related to mine, such as:  #7413 ,  #10019 , #3255 , #4603 and similar issue in other places by Google search. Most of them said it's caused by out of date version of youtube-dl. 

What i've done is like below:
- uninstall and remove everything any previous youtube-dl on my machine
- reinstall latest version through  `pip install --upgrade youtube-dl` 
- Uninstall through `pip`, replace using latest build exe for windows 

Same result. None of them are worked.
```
pip install --upgrade youtube-dl
Collecting youtube-dl
  Using cached youtube_dl-2017.1.8-py2.py3-none-any.whl
Installing collected packages: youtube-dl
Successfully installed youtube-dl-2017.1.8
```
```
$ youtube-dl --version
2017.01.08
$ python --version
Python 3.6.0
```
```$ youtube-dl https://www.youtube.com/watch?v=yKNxeF4KMsY -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=yKNxeF4KMsY', '-v']
[debug] Encodings: locale cp1252, fs utf-8, out cp1252, pref cp1252
[debug] youtube-dl version 2017.01.08
[debug] Python version 3.6.0 - Windows-10-10.0.14393-SP0
[debug] exe versions: ffmpeg 2.8.4, ffprobe N-82966-g6993bb4
[debug] Proxy map: {}
[youtube] yKNxeF4KMsY: Downloading webpage
[youtube] yKNxeF4KMsY: Downloading video info webpage
[youtube] yKNxeF4KMsY: Extracting video information
[youtube] {43} signature length 44.40, html5 player en_US-vflsagga9
[youtube] yKNxeF4KMsY: Downloading player https://s.ytimg.com/yts/jsbin/player-en_US-vflsagga9/base.js
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "c:\users\google\appdata\local\programs\python\python36-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1005, in _decrypt_signature
    video_id, player_url, s
  File "c:\users\google\appdata\local\programs\python\python36-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 932, in _extract_signature_function
    cache_res = res(test_string)
  File "c:\users\google\appdata\local\programs\python\python36-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 984, in <lambda>
    return lambda s: initial_function([s])
  File "c:\users\google\appdata\local\programs\python\python36-32\lib\site-packages\youtube_dl\jsinterp.py", line 254, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "c:\users\google\appdata\local\programs\python\python36-32\lib\site-packages\youtube_dl\jsinterp.py", line 55, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "c:\users\google\appdata\local\programs\python\python36-32\lib\site-packages\youtube_dl\jsinterp.py", line 174, in interpret_expression
    return obj[member](argvals)
KeyError: 'qC'
 (caused by KeyError('qC',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\users\google\appdata\local\programs\python\python36-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1005, in _decrypt_signature
    video_id, player_url, s
  File "c:\users\google\appdata\local\programs\python\python36-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 932, in _extract_signature_function
    cache_res = res(test_string)
  File "c:\users\google\appdata\local\programs\python\python36-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 984, in <lambda>
    return lambda s: initial_function([s])
  File "c:\users\google\appdata\local\programs\python\python36-32\lib\site-packages\youtube_dl\jsinterp.py", line 254, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "c:\users\google\appdata\local\programs\python\python36-32\lib\site-packages\youtube_dl\jsinterp.py", line 55, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "c:\users\google\appdata\local\programs\python\python36-32\lib\site-packages\youtube_dl\jsinterp.py", line 174, in interpret_expression
    return obj[member](argvals)
KeyError: 'qC'
Traceback (most recent call last):
  File "c:\users\google\appdata\local\programs\python\python36-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1005, in _decrypt_signature
    video_id, player_url, s
  File "c:\users\google\appdata\local\programs\python\python36-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 932, in _extract_signature_function
    cache_res = res(test_string)
  File "c:\users\google\appdata\local\programs\python\python36-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 984, in <lambda>
    return lambda s: initial_function([s])
  File "c:\users\google\appdata\local\programs\python\python36-32\lib\site-packages\youtube_dl\jsinterp.py", line 254, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "c:\users\google\appdata\local\programs\python\python36-32\lib\site-packages\youtube_dl\jsinterp.py", line 55, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "c:\users\google\appdata\local\programs\python\python36-32\lib\site-packages\youtube_dl\jsinterp.py", line 174, in interpret_expression
    return obj[member](argvals)
KeyError: 'qC'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\google\appdata\local\programs\python\python36-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "c:\users\google\appdata\local\programs\python\python36-32\lib\site-packages\youtube_dl\extractor\common.py", line 359, in extract
    return self._real_extract(url)
  File "c:\users\google\appdata\local\programs\python\python36-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1584, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "c:\users\google\appdata\local\programs\python\python36-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1015, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "c:\users\google\appdata\local\programs\python\python36-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1005, in _decrypt_signature
    video_id, player_url, s
  File "c:\users\google\appdata\local\programs\python\python36-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 932, in _extract_signature_function
    cache_res = res(test_string)
  File "c:\users\google\appdata\local\programs\python\python36-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 984, in <lambda>
    return lambda s: initial_function([s])
  File "c:\users\google\appdata\local\programs\python\python36-32\lib\site-packages\youtube_dl\jsinterp.py", line 254, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "c:\users\google\appdata\local\programs\python\python36-32\lib\site-packages\youtube_dl\jsinterp.py", line 55, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "c:\users\google\appdata\local\programs\python\python36-32\lib\site-packages\youtube_dl\jsinterp.py", line 174, in interpret_expression
    return obj[member](argvals)
KeyError: 'qC'
 (caused by KeyError('qC',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

**Comment by lolaristocrat** [comment]
also having this issue :(

**Comment by KitoHD** [comment]
I'm having this issue too.

**Comment by linglung** [comment]
Seem like youtube updated the layout, caused by something like this `html5 player en_US-vflsagga9`.  :cry:

**Comment by yan12125** [comment]
Can anyone run ```youtube-dl --write-pages yKNxeF4KMsY``` and upload all *.dump files?

**Comment by yan12125** [comment]
OK I got this bug, too

**Comment by linglung** [comment]
@yan12125  Still need to upload *.dump files or not? as i can't attach zip file here?

**Comment by anovicecodemonkey** [comment]
@yan12125 Here's the *.dump files: https://www.sendspace.com/filegroup/JhlFwck9rTaglBTPq6nYRS88mETW2kvb

**Comment by Doinkle** [comment]
Would just like to make it known that I am having this same issue.

**Comment by trongnguyentcec** [comment]
I've got the same issue.

**Comment by nmarley** [comment]
"I'm having the same issue" and "+1" comments are just creating noise at this point. It's a known issue, there will be a fix soon. Please consider this before posting here.

**Comment by yan12125** [comment]
Here's an ad-hoc fix:
```Diff
diff --git a/youtube_dl/extractor/youtube.py b/youtube_dl/extractor/youtube.py
index 335568a10..573c90ded 100644
--- a/youtube_dl/extractor/youtube.py
+++ b/youtube_dl/extractor/youtube.py
@@ -1266,6 +1266,7 @@ class YoutubeIE(YoutubeBaseInfoExtractor):
             video_info = None
             # Try looking directly into the video webpage
             ytplayer_config = self._get_ytplayer_config(video_id, video_webpage)
+            player_url = ytplayer_config.get('url')
             if ytplayer_config:
                 args = ytplayer_config['args']
                 if args.get('url_encoded_fmt_stream_map'):
@@ -1552,7 +1553,8 @@ class YoutubeIE(YoutubeBaseInfoExtractor):
                         jsplayer_url_json = self._search_regex(
                             ASSETS_RE, embed_webpage, 'JS player URL')
 
-                    player_url = json.loads(jsplayer_url_json)
+                    if player_url is None:
+                        player_url = json.loads(jsplayer_url_json)
                     if player_url is None:
                         player_url_json = self._search_regex(
                             r'ytplayer\.config.*?"url"\s*:\s*("[^"]+")',
```
Please upload dump files if this does not work for you.

**Comment by Mochlate** [comment]
Yup, me too.

**Comment by Kagami** [comment]
@yan12125 works for me for a simple test. Thanks.

**Comment by Kagami** [comment]
@yan12125 fails with trace for removed videos. E.g.:

```
$ youtube-dl -F atcXRlPT12o               
[youtube] atcXRlPT12o: Downloading webpage
Traceback (most recent call last):
  File "/usr/lib64/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/kagami/.local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/home/kagami/.local/bin/youtube-dl/youtube_dl/__init__.py", line 444, in main
  File "/home/kagami/.local/bin/youtube-dl/youtube_dl/__init__.py", line 434, in _real_main
  File "/home/kagami/.local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1791, in download
  File "/home/kagami/.local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 694, in extract_info
  File "/home/kagami/.local/bin/youtube-dl/youtube_dl/extractor/common.py", line 359, in extract
  File "/home/kagami/.local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1275, in _real_extract
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by yan12125** [comment]
@Kagami Hurry brings bad codes :-)

**Comment by dstftw** [comment]
Yet another hack:
```
Index: youtube_dl/jsinterp.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- youtube_dl/jsinterp.py	(date 1483978139000)
+++ youtube_dl/jsinterp.py	(revision )
@@ -213,7 +213,7 @@
     def extract_object(self, objname):
         obj = {}
         obj_m = re.search(
-            (r'(?:var\s+)?%s\s*=\s*\{' % re.escape(objname)) +
+            (r'(?<!this\.)%s\s*=\s*\{' % re.escape(objname)) +
             r'\s*(?P<fields>([a-zA-Z$0-9]+\s*:\s*function\(.*?\)\s*\{.*?\}(?:,\s*)?)*)' +
             r'\}\s*;',
             self.code)

```

**Comment by sta749** [comment]
Same problem here:

leto:~% youtube-dl https://www.youtube.com/watch?v=lteL18wd15Y
[youtube] lteL18wd15Y: Downloading webpage
[youtube] lteL18wd15Y: Downloading video info webpage
[youtube] lteL18wd15Y: Extracting video information
[youtube] lteL18wd15Y: Downloading js player en_US-vflsagga9
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/local/home/tet/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1005, in _decrypt_signature
    video_id, player_url, s
  File "/local/home/tet/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 932, in _extract_signature_function
    cache_res = res(test_string)
  File "/local/home/tet/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 984, in <lambda>
    return lambda s: initial_function([s])
  File "/local/home/tet/bin/youtube-dl/youtube_dl/jsinterp.py", line 254, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "/local/home/tet/bin/youtube-dl/youtube_dl/jsinterp.py", line 55, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/local/home/tet/bin/youtube-dl/youtube_dl/jsinterp.py", line 174, in interpret_expression
    return obj[member](argvals)
KeyError: u'qC'
 (caused by KeyError(u'qC',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
leto:~% youtube-dl --version
2017.01.08
leto:~% python --version
Python 2.7.12

**Comment by gsfordham** [comment]
```
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "A:\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1005, in _decrypt_signature
    video_id, player_url, s
  File "A:\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 932, in _extract_signature_function
    cache_res = res(test_string)
  File "A:\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 984, in <lambda>
    return lambda s: initial_function([s])
  File "A:\Python35-32\lib\site-packages\youtube_dl\jsinterp.py", line 254, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "A:\Python35-32\lib\site-packages\youtube_dl\jsinterp.py", line 55, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "A:\Python35-32\lib\site-packages\youtube_dl\jsinterp.py", line 174, in interpret_expression
    return obj[member](argvals)
KeyError: 'qC'
 (caused by KeyError('qC',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
I'm getting something like this, too...
Weird thing is, only some videos.
I tried:
```
[GSF@kawaiiOS.kyaa]# pip install youtube-dl update
Requirement already satisfied: youtube-dl in a:\python35-32\lib\site-packages
Collecting update
  Downloading update-0.4.4.tar.gz
Installing collected packages: update
  Running setup.py install for update ... done
Successfully installed update-0.4.4
```
Still some videos won't work.

**Comment by yan12125** [comment]
@dstftw Mind applying your patch to master? Although that's dirty, it's better than going back to the old Flash way.

**Comment by dstftw** [comment]
Done and released.

**Comment by yan12125** [comment]
Thanks!

**Comment by crazeyheadshots** [comment]
Hey can someone do a step by step on how to fix this please?

**Comment by yan12125** [comment]
@crazedpsyc The fix is included in 2017.01.10; see https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl

**Comment by KitoHD** [comment]
how do i open the script panel thing, sorry im new to this. how do i fix this?

**Comment by yan12125** [comment]
@KitoHD How did you install youtube-dl?

**Comment by sonaldynho** [comment]
The openload is fix?????

**Comment by sonaldynho** [comment]
Is the openload fix???

**Comment by crazeyheadshots** [comment]
basically go to the ur error message and go to the directory where it says the error is then find the file called jsinterp.py. This is where i found the file: https://gyazo.com/3e4a6a2402ac561bd79444df275ed6d5
Remove the line that says:(r'(?:var\s+)?%s\s*=\s*\{' % re.escape(objname)) +
Replace with:(r'(?<!this\.)%s\s*=\s*\{' % re.escape(objname)) +

**Comment by crazeyheadshots** [comment]
No problem guys

**Comment by crazeyheadshots** [comment]
Btw open the file with notepad ++ or wordpad etc to edit it.

**Comment by dstftw** [comment]
This issue is already fixed. Read [this FAQ entry](https://yt-dl.org/update) if you have troubles updating.
