### ISSUE TITLE
bug as of 1/10/2017

### ISSUE THREAD

**Issue by thesokrin** [rg3/youtube-dl#11670]
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 1005, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 932, in _extract_signature_function
    cache_res = res(test_string)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 984, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/lib64/python2.7/site-packages/youtube_dl/jsinterp.py", line 254, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/jsinterp.py", line 55, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/jsinterp.py", line 174, in interpret_expression
    return obj[member](argvals)
KeyError: u'qC'
 (caused by KeyError(u'qC',));

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [this FAQ entry](https://yt-dl.org/update) if you have troubles updating.
