### ISSUE TITLE
ExtractorError: Cannot find player ID

### ISSUE THREAD

**Issue by scottstensland** [rg3/youtube-dl#11688]
Bug report

youtube-dl --verbose   http://www.nature.com/nmeth/journal/v9/n7/fig_tab/nmeth.2062_SV1.html

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'http://www.nature.com/nmeth/journal/v9/n7/fig_tab/nmeth.2062_SV1.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.01.10
[debug] Python version 2.7.12 - Linux-4.4.0-57-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg N-79477-g3a72760, ffprobe N-79477-g3a72760, rtmpdump 2.4
[debug] Proxy map: {}
[generic] nmeth.2062_SV1: Requesting header
WARNING: Falling back on generic information extractor.
[generic] nmeth.2062_SV1: Downloading webpage
[generic] nmeth.2062_SV1: Extracting information
ERROR: Cannot find player ID; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1685, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2526, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2515, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: syntax error: line 2, column 3
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 359, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1759, in _real_extract
    bc_urls = BrightcoveLegacyIE._extract_brightcove_urls(webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/brightcove.py", line 255, in _extract_brightcove_urls
    return list(filter(None, [cls._build_brighcove_url(m) for m in matches]))
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/brightcove.py", line 184, in _build_brighcove_url
    raise ExtractorError('Cannot find player ID')
ExtractorError: Cannot find player ID; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by yan12125** [comment]
Thanks for the report. This will be fixed in the next version.
