### ISSUE TITLE
[fplive.net] down

### ISSUE THREAD

**Issue by RuneMagle** [rg3/youtube-dl#11694]
---
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.01.10**
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
```
C:\Users\rumag\Desktop\youtube-dl>youtube-dl.exe -f best --embed-subs --all-subs --convert-subs srt --username NoneofUrBusiness --password july1987 --ap-username sup --ap-password july1987 --ap-mso DTV --no-check-certificate "nick.com/videos/clip/the-thundermans-402-full-episode.html" -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'best', '--embed-subs', '--all-subs', '--convert-subs', 'srt', '--username', 'PRIVATE', '--password', 'PRIVATE', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '--ap-mso', 'DTV', '--no-check-certificate', 'nick.com/videos/clip/the-thundermans-402-full-episode.html', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.01.08
[debug] Python version 3.4.4 - Windows-10-10.0.10586
[debug] exe versions: ffmpeg N-82966-g6993bb4
[debug] Proxy map: {}
WARNING: The url doesn't specify the protocol, trying with http
[nick.com] the-thundermans-402-full-episode.html: Downloading webpage
[nick.com] c3d21540-b607-11e6-bfd4-0026b9414f30: Downloading info
[nick.com] 296a81a1-9306-4b18-8ff6-e93d89e64f7a: Extracting information
[nick.com] 296a81a1-9306-4b18-8ff6-e93d89e64f7a: Downloading video urls
[nick.com] e6635c56-48dd-4f1d-b7d1-744f0ef458e7: Extracting information
[nick.com] e6635c56-48dd-4f1d-b7d1-744f0ef458e7: Downloading video urls
[nick.com] 0368e230-4252-4110-8e41-c65ff7497040: Extracting information
[nick.com] 0368e230-4252-4110-8e41-c65ff7497040: Downloading video urls
[nick.com] dbd52286-d74b-4292-9576-186409ca183c: Extracting information
[nick.com] dbd52286-d74b-4292-9576-186409ca183c: Downloading video urls
[download] Downloading playlist: The Thundermans: "Smells Like Team Spirit"
[nick.com] playlist The Thundermans: "Smells Like Team Spirit": Collected 4 video ids (downloading 4 of them)
[download] Downloading video 1 of 4
[info] Writing video subtitles to: The Thundermans - 'Smells Like Team Spirit' S1-296a81a1-9306-4b18-8ff6-e93d89e64f7a.en.vtt
[debug] Invoking downloader on 'http://viacommtvstrmfs.fplive.net/gsp.alias/mediabus/kids.com/2016/12/21/04/50/30/cbda52af52aa4a6fac2df1f7a840b32d/1497974/uDCJVLrQA2_HDTHN402A1_1497974_6918242_1920x1080_5128.mp4'
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9qq9vblw\build\youtube_dl\YoutubeDL.py", line 1699, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9qq9vblw\build\youtube_dl\YoutubeDL.py", line 1641, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9qq9vblw\build\youtube_dl\downloader\common.py", line 353, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9qq9vblw\build\youtube_dl\downloader\http.py", line 61, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9qq9vblw\build\youtube_dl\YoutubeDL.py", line 2001, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found
...
<end of log>
```
---
- Single video: nick.com/videos/clip/the-thundermans-402-full-episode.html
- Single video: http://beta.nick.com/videos/clip/the-thundermans-402-full-episode.html

---
fplive.net seems to be down
MTV ,Nick and many others rely on viacommtvstrmfs.fplive.net

Comedy Central already switched to m3u8,akamaihd from fplive

**Comment by dstftw** [comment]
This is already fixed.

**Comment by RuneMagle** [comment]
No, it's not fixed. When I do it on my PC, it's still not working.

```
C:\Users\BARN\Desktop\youtube-dl>youtube-dl.exe -f best http://www.nick.com/videos/clip/the-thundermans-402-full-episode.html -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'best', 'http://www.nick.com/videos/clip/the-thundermans-402-full-episode.html', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.01.10
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-83034-gf48b6b8
[debug] Proxy map: {}
[nick.com] the-thundermans-402-full-episode.html: Downloading webpage
[nick.com] c3d21540-b607-11e6-bfd4-0026b9414f30: Downloading info
[nick.com] 296a81a1-9306-4b18-8ff6-e93d89e64f7a: Extracting information
[nick.com] 296a81a1-9306-4b18-8ff6-e93d89e64f7a: Downloading video urls
[nick.com] e6635c56-48dd-4f1d-b7d1-744f0ef458e7: Extracting information
[nick.com] e6635c56-48dd-4f1d-b7d1-744f0ef458e7: Downloading video urls
[nick.com] 0368e230-4252-4110-8e41-c65ff7497040: Extracting information
[nick.com] 0368e230-4252-4110-8e41-c65ff7497040: Downloading video urls
[nick.com] dbd52286-d74b-4292-9576-186409ca183c: Extracting information
[nick.com] dbd52286-d74b-4292-9576-186409ca183c: Downloading video urls
[download] Downloading playlist: The Thundermans: "Smells Like Team Spirit"
[nick.com] playlist The Thundermans: "Smells Like Team Spirit": Collected 4 video ids (downloading 4 of them)
[download] Downloading video 1 of 4
[debug] Invoking downloader on 'http://viacommtvstrmfs.fplive.net/gsp.alias/mediabus/kids.com/2016/12/21/04/50/30/cbda52af52aa4a6fac2df1f7a840b32d/1497974/uDCJVLrQA2_HDTHN402A1_1497974_6918242_1920x1080_5128.mp4'
ERROR: unable to download video data: ''
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpu7wtweqp\build\youtube_dl\YoutubeDL.py", line 1699, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpu7wtweqp\build\youtube_dl\YoutubeDL.py", line 1641, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpu7wtweqp\build\youtube_dl\downloader\common.py", line 353, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpu7wtweqp\build\youtube_dl\downloader\http.py", line 61, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpu7wtweqp\build\youtube_dl\YoutubeDL.py", line 2001, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpu7wtweqp\build\youtube_dl\utils.py", line 877, in http_open
  File "C:\Python\Python34\lib\urllib\request.py", line 1186, in do_open
  File "C:\Python\Python34\lib\http\client.py", line 1227, in getresponse
  File "C:\Python\Python34\lib\http\client.py", line 386, in begin
  File "C:\Python\Python34\lib\http\client.py", line 356, in _read_status
http.client.BadStatusLine: ''
```

**Comment by dstftw** [comment]
It's not yet released.
