### ISSUE TITLE
Error downloading Colbert Report Clips from ComedyCentral website

### ISSUE THREAD

**Issue by lukaskollmer** [rg3/youtube-dl#11695]
*(Yes I'm running the latest version (2017.01.10) and I read the issue instructions)*

I can't download Colbert Report clips from the comedycentral website anymore. (Watching the clip on [the website](http://www.cc.com/video-clips/p0x4yp/the-colbert-report-on-topic---stephen-s-epic-sign-off) works fine).

I believe this issue is related to #11600. However, #11600 seems to be related to downloading full episodes (which works fine for me). I just want the clips.

Example output:
```
youtube-dl -v http://www.cc.com/video-clips/p0x4yp/the-colbert-report-on-topic---stephen-s-epic-sign-off
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'http://www.cc.com/video-clips/p0x4yp/the-colbert-report-on-topic---stephen-s-epic-sign-off']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.01.10
[debug] Python version 2.7.10 - Darwin-16.3.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.0.2, ffprobe 3.0.2
[debug] Proxy map: {}
[ComedyCentral] the-colbert-report-on-topic---stephen-s-epic-sign-off: Downloading webpage
[ComedyCentral] b7ce39cc-e119-4412-a362-06ff9c2256aa: Downloading info
[ComedyCentral] b7ce39cc-e119-4412-a362-06ff9c2256aa: Extracting information
[ComedyCentral] b7ce39cc-e119-4412-a362-06ff9c2256aa: Downloading video urls
[download] Downloading playlist: On Topic - Stephen's Epic Sign Off
[ComedyCentral] playlist On Topic - Stephen's Epic Sign Off: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[debug] Invoking downloader on u'http://viacommtvstrmfs.fplive.net/gsp.comedystor/com/colbert/mashups/colbert_farewell/cr_ultimatesignoff_1280x720_3500_h32.mp4'
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1699, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1641, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 353, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 61, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2001, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found
```

**Comment by RuneMagle** [comment]
Because it's using fplive aswell #11694

**Comment by dstftw** [comment]
This is already fixed.
