### ISSUE TITLE
ERROR: Incomplete YouTube ID

### ISSUE THREAD

**Issue by linglung** [rg3/youtube-dl#11707]
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
Error downloading video with prefix dash sign of video ID. 
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=-vH2eZAM30', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2017.01.10
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-82966-g6993bb4, ffprobe N-82966-g6993bb4
[debug] Proxy map: {}
ERROR: Incomplete YouTube ID -vH2eZAM30. URL https://www.youtube.com/watch?v=-vH2eZAM30 looks truncated.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpu7wtweqp\build\youtube_dl\YoutubeDL.py", line 694, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpu7wtweqp\build\youtube_dl\extractor\common.py", line 359, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpu7wtweqp\build\youtube_dl\extractor\youtube.py", line 2523, in _real_extract
youtube_dl.utils.ExtractorError: Incomplete YouTube ID -vH2eZAM30. URL https://www.youtube.com/watch?v=-vH2eZAM30 looks truncated.
```

**Comment by dstftw** [comment]
https://www.youtube.com/watch?v=-vH2eZAM30 is not a valid YouTube URL.

**Comment by linglung** [comment]
Oh my bad, apologize for my mistake. After check it again, it's wrong video id. I didn't recognize even though i paste URL and retry many times. It's missing one last character. The correct URL is `https://www.youtube.com/watch?v=-vH2eZAM30s`. 
**closed** 
Thank you @dstftw
