### ISSUE TITLE
Signature extraction failed

### ISSUE THREAD

**Issue by reynoldpj** [rg3/youtube-dl#11754]
Hi,

I am getting the error message "Signature extraction failed" message intermittently while trying to download videos using youtube-dl. I am running youtube-dl on mac OS X 10.11.6 using latest version 2016.05.16 and python 2.7. 

Pasting below the verbose message from cmdline, 

> 

$ youtube-dl --verbose -o "sol.flv" "https://www.youtube.com/watch?v=9h30Bx4Klxg"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'-o', u'SelenaGomez_SameOldLove.flv', u'https://www.youtube.com/watch?v=9h30Bx4Klxg']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.05.16
[debug] Python version 2.7.12 - Darwin-15.6.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] 9h30Bx4Klxg: Downloading webpage
[youtube] 9h30Bx4Klxg: Downloading video info webpage
[youtube] 9h30Bx4Klxg: Extracting video information
[youtube] {22} signature length 41.42, html5 player en_US-vflR62D9G
[youtube] {43} signature length 41.42, html5 player en_US-vflR62D9G
[youtube] {18} signature length 41.42, html5 player en_US-vflR62D9G
[youtube] {36} signature length 41.42, html5 player en_US-vflR62D9G
[youtube] {17} signature length 41.42, html5 player en_US-vflR62D9G
[youtube] {137} signature length 39.42, html5 player en_US-vflR62D9G
[youtube] 9h30Bx4Klxg: Downloading player https://s.ytimg.com/yts/jsbin/player-en_US-vflR62D9G/base.js
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 995, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 910, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/local/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 973, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/local/lib/python2.7/site-packages/youtube_dl/jsinterp.py", line 241, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
ExtractorError: Could not find JS function u'Gi'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Could not find JS function u'Gi'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 995, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 910, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/local/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 973, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/local/lib/python2.7/site-packages/youtube_dl/jsinterp.py", line 241, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
ExtractorError: Could not find JS function u'Gi'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 676, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 341, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 1568, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/usr/local/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 1005, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 995, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 910, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/local/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 973, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/local/lib/python2.7/site-packages/youtube_dl/jsinterp.py", line 241, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
ExtractorError: Could not find JS function u'Gi'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Could not find JS function u'Gi'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by linglung** [comment]
You are using an outdated version of youtube-dl. Just [update ](https://github.com/rg3/youtube-dl/commit/c1c2fe2045911c310fd5d2eda7bbb53ad581d250)it and everything will be OK. 😄
