### ISSUE TITLE
[tvland] AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by StevenDTX** [rg3/youtube-dl#11752]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.01.16*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.01.16**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---
```
E:\>youtube-dl.exe --restrict-filenames --continue --no-check-certificate --verbose -o Younger.S03E06-%(playlist_index)s.mp4 "http://www.tvland.com/full-episodes/a97wwe/younger-me-myself-and-o-season-3-ep-306"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--restrict-filenames', '--continue', '--no-check-certificate', '--verbose', '-o', 'Younger.S03E06-%(playlist_index)s.mp4', 'http://www.tvland.com/full-episodes/a97wwe/younger-me-myself-and-o-season-3-ep-306']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.01.16
[debug] Python version 3.4.4 - Windows-10-10.0.10586
[debug] exe versions: ffmpeg N-82966-g6993bb4, ffprobe N-72383-g7206b94, rtmpdump 2.4
[debug] Proxy map: {}
[tvland.com] younger-me-myself-and-o-season-3-ep-306: Downloading webpage
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpuqqhlvi_\build\youtube_dl\__init__.py", line 444, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpuqqhlvi_\build\youtube_dl\__init__.py", line 434, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpuqqhlvi_\build\youtube_dl\YoutubeDL.py", line 1791, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpuqqhlvi_\build\youtube_dl\YoutubeDL.py", line 694, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpuqqhlvi_\build\youtube_dl\extractor\common.py", line 359, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpuqqhlvi_\build\youtube_dl\extractor\mtv.py", line 264, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpuqqhlvi_\build\youtube_dl\extractor\mtv.py", line 195, in _get_videos_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpuqqhlvi_\build\youtube_dl\extractor\mtv.py", line 38, in _id_from_uri
AttributeError: 'NoneType' object has no attribute 'split'

```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://www.tvland.com/full-episodes/a97wwe/younger-me-myself-and-o-season-3-ep-306
- Single video: http://www.tvland.com/full-episodes/ro3ytv/the-jim-gaffigan-show-the-list-season-2-ep-204

---

### Description of your *issue*, suggested solution and other information

TVLAND was working just fine until recently. I'm guessing that it may have something to do with the recent MTV extractor changes.

Thanks.

**Comment by dstftw** [comment]
This video is only available with TV provider.

**Comment by StevenDTX** [comment]
Sorry about that. Here is a free episode that gets the same error.

http://www.tvland.com/full-episodes/rj3wir/lopez-slave-for-a-day-season-1-ep-101

```
E:\>youtube-dl http://www.tvland.com/full-episodes/rj3wir/lopez-slave-for-a-day-season-1-ep-101 --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['http://www.tvland.com/full-episodes/rj3wir/lopez-slave-for-a-day-season-1-ep-101', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.01.16
[debug] Python version 3.4.4 - Windows-10-10.0.10586
[debug] exe versions: ffmpeg N-82966-g6993bb4, ffprobe N-72383-g7206b94, rtmpdump 2.4
[debug] Proxy map: {}
[tvland.com] lopez-slave-for-a-day-season-1-ep-101: Downloading webpage
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpuqqhlvi_\build\youtube_dl\__init__.py", line 444, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpuqqhlvi_\build\youtube_dl\__init__.py", line 434, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpuqqhlvi_\build\youtube_dl\YoutubeDL.py", line 1791, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpuqqhlvi_\build\youtube_dl\YoutubeDL.py", line 694, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpuqqhlvi_\build\youtube_dl\extractor\common.py", line 359, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpuqqhlvi_\build\youtube_dl\extractor\mtv.py", line 264, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpuqqhlvi_\build\youtube_dl\extractor\mtv.py", line 195, in _get_videos_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpuqqhlvi_\build\youtube_dl\extractor\mtv.py", line 38, in _id_from_uri
AttributeError: 'NoneType' object has no attribute 'split'
```
