### ISSUE TITLE
cracked.com movies are not supported

### ISSUE THREAD

**Issue by marafa** [rg3/youtube-dl#11775]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.01.10*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ ] I've **verified** and **I assure** that I'm running youtube-dl **2017.01.10**

### Before submitting an *issue* make sure you have:
- [ ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
youtube-dl -v http://www.crackle.com/7-seconds
[debug] System config: ['--prefer-free-formats']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://www.crackle.com/7-seconds']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.01.10
[debug] Python version 3.5.2 - Linux-4.9.3-200.fc25.x86_64-x86_64-with-fedora-25-Twenty_Five
[debug] exe versions: ffmpeg 3.1.6, ffprobe 3.1.6
[debug] Proxy map: {}
[generic] 7-seconds: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 7-seconds: Downloading webpage
[generic] 7-seconds: Extracting information
ERROR: Unsupported URL: http://www.crackle.com/7-seconds
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 693, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 359, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/generic.py", line 2507, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.crackle.com/7-seconds
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://www.crackle.com/7-seconds

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

youtube-dl already supports the TV section of crackle.com. However, it does not support the movies section

**Comment by yan12125** [comment]
I got blank screens from http://www.crackle.com/7-seconds in both Firefox and Chrome. Is it geo-restricted?

**Comment by marafa** [comment]
I believe so . Yes

**Comment by yan12125** [comment]
Which country? I got a proxy from United States and it doesn't work.

**Comment by marafa** [comment]
United States is the country

**Comment by yan12125** [comment]
Now I got 404 with various US proxies. Is the video still alive?

**Comment by marafa** [comment]
Yes it is. It's not due to be switched out till the end of the month

**Comment by zoocey** [comment]
My other report was closed #10419. I am not in the US but crackle is available in my region (with a limited selection). If it is available in your region any video on the crackle page should reproduce the issue. I can also watch American videos using a paid VPN with no issue. 

As a work around if you have a way to sniff traffic when playing a video, e.g.  an adblocker (ublock origin) or experience with your browsers developer tools. Filter for json. For your video you should see a url like ..Service.svc/details/media/2492959/US?format=json 

Append that number to your url http://www.crackle.com/7-seconds/2492959 and it will work with youtube-dl.

**Comment by ajp69** [comment]
Should download if you use the correct link  

http://www.crackle.com/7-seconds/2492959

Shows a 1080p video at 5052k and aac audio at 128kbps

**Comment by marafa** [comment]
can someone attach a copy of the crackle.com/7-seconds page? it might help

**Comment by oxguy3** [comment]
It's very easy to get the correct URL for a movie without having to do any fancy traffic sniffing. Just scroll down to where it says "NOW PLAYING" and click on the movie poster. You'll then be taken to the URL with the number in it. Here's a screenshot; I've circled the link you should click:
<img width="1634" src="https://cloud.githubusercontent.com/assets/796881/22389069/cc561242-e4b1-11e6-9e18-cd1f3654d82f.png">

**Comment by oxguy3** [comment]
By the way youtube-dl developers, here's how you can add support for the number-less URLs: For all URLs of the format "http://www.crackle.com/SOME-SLUG", make a query to `https://web-api-us.crackle.com/Service.svc/details/channel/SOME-SLUG/US?format=json` (side note: you'll have to change the country code from "US" to whatever country the user's IP address is in). Then, get the attribute "ID" of the object "FeaturedMedia" from that JSON response, and append that to the URL.

If that endpoint returns an empty response, that means the URL was invalid and you should throw an "unsupported URL" error message. If the endpoint returns a valid JSON response, but the "FeaturedMedia" key doesn't exist, that probably means the URL was a TV show rather than a movie,  and you should throw an "unsupported URL" error message.

Here are examples of each of these cases:
* A movie that can be supported: https://web-api-us.crackle.com/Service.svc/details/channel/7-seconds/US?format=json
* A bad URL that returns an empty response: https://web-api-us.crackle.com/Service.svc/details/channel/asdf/US?format=json
* A TV show, which has no "FeaturedMedia" and can't be supported: https://web-api-us.crackle.com/Service.svc/details/channel/all-in-the-family/US?format=json

**Comment by yan12125** [comment]
Does crackle support countries other than United Stated? https://web-api-us.crackle.com/Service.svc/details/channel/7-seconds/US?format=json returns valid results yet https://web-api-us.crackle.com/Service.svc/details/channel/7-seconds/TW?format=json gives HTTP 401. If only US is possible I'd like to hardcode it - detecting users' geolocation is quite difficult.

**Comment by oxguy3** [comment]
It definitely works in Canada, Australia, and Puerto Rico, but the
selection of movies/shows is different (looks like 7 Seconds happens to be
US-only). Here's the endpoint to retrieve the list of all movies:
https://web-api-us.crackle.com/Service.svc/browse/movies/full/all/alpha-
asc/US/20/1?format=json

If you plug CA or AU or PR in place of US in that URL, you still get
results. I'm not sure if it works anywhere besides US+CA+AU+PR -- no other
country code has gotten me any results (I've tried UK, GB, ES, MX, TW, JA,
DE, FR...).

*Hayden Schiff*
*schiff.io <http://schiff.io>*

**Comment by 89z** [comment]
Issue should be closed, URL is dead
