### ISSUE TITLE
Cannot work on Iwara

### ISSUE THREAD

**Issue by Uron0238** [rg3/youtube-dl#11781]
youtube-dl.exe http://ecchi.iwara.tv/videos/mwweqhblyds8k181n -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['http://ecchi.iwara.tv/videos/mwweqhblyds8k181n', '-v']
[debug] Encodings: locale cp932, fs mbcs, out cp932, pref cp932
[debug] youtube-dl version 2017.01.18
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: none
[debug] Proxy map: {}
[Iwara] mwweqhblyds8k181n: Downloading webpage
ERROR: Unable to extract iframe URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkdk_72bb\build\youtube_dl\YoutubeDL.py", line 694, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkdk_72bb\build\youtube_dl\extractor\common.py", line 359, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkdk_72bb\build\youtube_dl\extractor\iwara.py", line 60, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkdk_72bb\build\youtube_dl\extractor\common.py", line 671, in _html_search_regex
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkdk_72bb\build\youtube_dl\extractor\common.py", line 662, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract iframe URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

----------------------------------------------------------------------------
It stopped working on iwara.
It was working on January 4th.
It seems that the specification change of the site was around 11th.
I would like it to work if possible.
Please.
This sentence is machine translation.

**Comment by ogekve** [comment]
iwara.tv (Iwara) is listed @ https://github.com/rg3/youtube-dl/blob/master/docs/supportedsites.md
youtube-dl worked in 2016 to download from http://www.iwara.tv but in 2017 in early January the videos began reporting this error:

$ youtube-dl http://www.iwara.tv/videos/jkrq0cj9jie1elyl
[debug] System config: []
[debug] User config: [u'--no-overwrites', u'--continue', u'--verbose', u'-f', u'best']
[debug] Custom config: []
[debug] Command-line args: [u'http://www.iwara.tv/videos/jkrq0cj9jie1elyl']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.01.25
[debug] Python version 2.7.9 - Linux-3.16.0-4-686-pae-i686-with-debian-8.7
[debug] exe versions: avconv 11.8-6, avprobe 11.8-6
[debug] Proxy map: {}
[Iwara] jkrq0cj9jie1elyl: Downloading webpage
ERROR: Unable to extract iframe URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 359, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/iwara.py", line 60, in _real_extract
    webpage, 'iframe URL', group='url')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 671, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 662, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract iframe URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

$ youtube-dl --version
2017.01.25

If someone could re-add compatibility for extracting from this website that would be greatly appreciated.

**Comment by yan12125** [comment]
Thanks for the reports. Iwara support will be fixed in the next version.
