### ISSUE TITLE
Youtube downloading blocked

### ISSUE THREAD

**Issue by dollabi11z** [rg3/youtube-dl#11803]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.01.18*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.01.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2017.01.18
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

Youtube-DL no longer downloads youtube videos its been blocked or something ive tried from 5 different servers

debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=ARgCjfOs7BA']

[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.01.18
[debug] Python version 3.4.4 - Windows-2012ServerR2-6.3.9600
[debug] exe versions: ffmpeg N-82871-ga5cf600, ffprobe N-82871-ga5cf600
[debug] Proxy map: {}
[youtube] ARgCjfOs7BA: Downloading webpage
[youtube] ARgCjfOs7BA: Downloading video info webpage
[youtube] ARgCjfOs7BA: Extracting video information
[youtube] ARgCjfOs7BA: Downloading MPD manifest
[youtube] ARgCjfOs7BA: Downloading MPD manifest
[debug] Invoking downloader on 'https://r7---sn-bvvbax-hjpe.googlevideo.com/vide
oplayback/id/0118028df3acec10/itag/134/source/youtube/requiressl/yes/nh/EAo/pl/2
1/mm/31/mn/sn-bvvbax-hjpe/gcr/us/ms/au/mv/u/ratebypass/yes/mime/video%2Fmp4/otfp
/1/gir/yes/clen/146564816/lmt/1484996410785763/dur/2694.040/signature/191B29E062
81BD9D73EF58173BA2FCB288296C0A.4781C56F7B3E3A5B32CE0B8083FD1C220C533581/upn/zh5I
eNXbcuA/key/dg_yt0/mt/1485035928/ip/204.12.234.34/ipbits/0/expire/1485057628/spa
rams/ip,ipbits,expire,id,itag,source,requiressl,nh,pl,mm,mn,gcr,ms,mv,ratebypass
,mime,otfp,gir,clen,lmt,dur/'
[dashsegments] Total fragments: 527
[download] Destination: CBBUK   s19e18 (Day 17 - Live Eviction - Part 1)-ARgCjfO
s7BA.f134.mp4

And just times out

**Comment by renalid** [comment]
Hello,

I reproduce the same issue with different video, on different servers.
Youtube-DL no longer downloads youtube videos its been blocked and timeout.

> youtube-dl -v http://www.youtube.com/watch?v=ib-ymINhMDE -f m4a
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=ib-ymINhMDE', u'-f', u'm4a']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.01.25
[debug] Python version 2.7.12 - Darwin-15.6.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] ib-ymINhMDE: Downloading webpage
[youtube] ib-ymINhMDE: Downloading video info webpage
[youtube] ib-ymINhMDE: Extracting video information
[youtube] ib-ymINhMDE: Downloading MPD manifest
[youtube] ib-ymINhMDE: Downloading MPD manifest
[debug] Invoking downloader on u'https://r1---sn-25ge7nls.googlevideo.com/videoplayback/id/89bfb29883613031/itag/140/source/youtube/requiressl/yes/mv/u/ms/au/pl/23/nh/IgpwcjAxLnBhcjAxKgkxMjcuMC4wLjE/mn/sn-25ge7nls/mm/31/ratebypass/yes/mime/audio%2Fmp4/otfp/1/gir/yes/clen/41680985/lmt/1485336445262658/dur/2622.391/mt/1485418708/key/dg_yt0/upn/nsik_DqCUe4/signature/9389208D22BF26BB89374B27F7AADF0C00FDED13.0C60922727C6496974FC19E71CF74B0F9362D488/ip/195.244.20.72/ipbits/0/expire/1485440410/sparams/ip,ipbits,expire,id,itag,source,requiressl,mv,ms,pl,nh,mn,mm,ratebypass,mime,otfp,gir,clen,lmt,dur/'
[dashsegments] Total fragments: 526
[download] Destination: 'Business Models for Startups' by Younès Rharbaoui, Deal-Flow Manager @TheFamily-ib-ymINhMDE.m4a
[download]   1.5% of ~34.95MiB at Unknown speed ETA Unknown ETAERROR: unable to download video data: <urlopen error [Errno 65] No route to host>
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1699, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1641, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 353, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/dash.py", line 73, in real_download
    if not process_segment(segment, ctx['tmpfilename'], i):
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/dash.py", line 46, in process_segment
    success = ctx['dl'].download(target_filename, {'url': segment_url})
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 353, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 61, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2001, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1048, in https_open
    req, **kwargs)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 65] No route to 

> host>

**Comment by dollabi11z** [comment]
Yes almost like they are blocking IP’s and A LOT of them instantly

 

 

Hello,

I reproduce the same issue with different video, on different servers.
Youtube-DL no longer downloads youtube videos its been blocked and timeout.

youtube-dl -v http://www.youtube.com/watch?v=ib-ymINhMDE -f m4a
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=ib-ymINhMDE', u'-f', u'm4a']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.01.25
[debug] Python version 2.7.12 - Darwin-15.6.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] ib-ymINhMDE: Downloading webpage
[youtube] ib-ymINhMDE: Downloading video info webpage
[youtube] ib-ymINhMDE: Extracting video information
[youtube] ib-ymINhMDE: Downloading MPD manifest
[youtube] ib-ymINhMDE: Downloading MPD manifest
[debug] Invoking downloader on u'https://r1---sn-25ge7nls.googlevideo.com/videoplayback/id/89bfb29883613031/itag/140/source/youtube/requiressl/yes/mv/u/ms/au/pl/23/nh/IgpwcjAxLnBhcjAxKgkxMjcuMC4wLjE/mn/sn-25ge7nls/mm/31/ratebypass/yes/mime/audio%2Fmp4/otfp/1/gir/yes/clen/41680985/lmt/1485336445262658/dur/2622.391/mt/1485418708/key/dg_yt0/upn/nsik_DqCUe4/signature/9389208D22BF26BB89374B27F7AADF0C00FDED13.0C60922727C6496974FC19E71CF74B0F9362D488/ip/195.244.20.72/ipbits/0/expire/1485440410/sparams/ip,ipbits,expire,id,itag,source,requiressl,mv,ms,pl,nh,mn,mm,ratebypass,mime,otfp,gir,clen,lmt,dur/'
[dashsegments] Total fragments: 526
[download] Destination: 'Business Models for Startups' by Younès Rharbaoui, Deal-Flow Manager @TheFamily-ib-ymINhMDE.m4a
[download] 1.5% of ~34.95MiB at Unknown speed ETA Unknown ETAERROR: unable to download video data: <urlopen error [Errno 65] No route to host>
Traceback (most recent call last):
File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1699, in process_info
success = dl(filename, info_dict)
File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1641, in dl
return fd.download(name, info)
File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 353, in download
return self.real_download(filename, info_dict)
File "/usr/local/bin/youtube-dl/youtube_dl/downloader/dash.py", line 73, in real_download
if not process_segment(segment, ctx['tmpfilename'], i):
File "/usr/local/bin/youtube-dl/youtube_dl/downloader/dash.py", line 46, in process_segment
success = ctx['dl'].download(target_filename, {'url': segment_url})
File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 353, in download
return self.real_download(filename, info_dict)
File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 61, in real_download
data = self.ydl.urlopen(request)
File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2001, in urlopen
return self._opener.open(req, timeout=self._socket_timeout)
File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 429, in open
response = self._open(req, data)
File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 447, in _open
'_open', req)
File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
result = func(*args)
File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1048, in https_open
req, **kwargs)
File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1198, in do_open
raise URLError(err)
URLError: <urlopen error [Errno 65] No route to

host>

**Comment by ThomasChr** [comment]
No problem here with your URL "http://www.youtube.com/watch?v=ib-ymINhMDE"

**Comment by vxbinaca** [comment]
I'm getting this error:

```
 vxbinaca@melitene  ~/.tubeup/downloads  youtube-dl --verbose q3xMr9-BwPc                       1 ↵  26 ⚙  655  02:43:29 
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'q3xMr9-BwPc']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.12.09
[debug] Python version 3.4.5 - Linux-3.10.0-514.2.2.el7.x86_64-x86_64-with-centos-7.3.1611-Core
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] q3xMr9-BwPc: Downloading webpage
[youtube] q3xMr9-BwPc: Downloading video info webpage
[youtube] q3xMr9-BwPc: Extracting video information
[youtube] {22} signature length 42.43, html5 player en_US-vflkk7pUE
[youtube] q3xMr9-BwPc: Downloading player /yts/jsbin/player-en_US-vflkk7pUE/base.js
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/home/vxbinaca/.local/lib/python3.4/site-packages/youtube_dl/extractor/youtube.py", line 1005, in _decrypt_signature
    video_id, player_url, s
  File "/home/vxbinaca/.local/lib/python3.4/site-packages/youtube_dl/extractor/youtube.py", line 919, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "/home/vxbinaca/.local/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 517, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "/home/vxbinaca/.local/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 424, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "/home/vxbinaca/.local/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 404, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/home/vxbinaca/.local/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 2000, in urlopen
    req = sanitized_Request(req)
  File "/home/vxbinaca/.local/lib/python3.4/site-packages/youtube_dl/utils.py", line 513, in sanitized_Request
    return compat_urllib_request.Request(sanitize_url(url), *args, **kwargs)
  File "/usr/lib64/python3.4/urllib/request.py", line 267, in __init__
    self.full_url = url
  File "/usr/lib64/python3.4/urllib/request.py", line 293, in full_url
    self._parse()
  File "/usr/lib64/python3.4/urllib/request.py", line 322, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/yts/jsbin/player-en_US-vflkk7pUE/base.js'
 (caused by ValueError("unknown url type: '/yts/jsbin/player-en_US-vflkk7pUE/base.js'",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/vxbinaca/.local/lib/python3.4/site-packages/youtube_dl/extractor/youtube.py", line 1005, in _decrypt_signature
    video_id, player_url, s
  File "/home/vxbinaca/.local/lib/python3.4/site-packages/youtube_dl/extractor/youtube.py", line 919, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "/home/vxbinaca/.local/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 517, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "/home/vxbinaca/.local/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 424, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "/home/vxbinaca/.local/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 404, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/home/vxbinaca/.local/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 2000, in urlopen
    req = sanitized_Request(req)
  File "/home/vxbinaca/.local/lib/python3.4/site-packages/youtube_dl/utils.py", line 513, in sanitized_Request
    return compat_urllib_request.Request(sanitize_url(url), *args, **kwargs)
  File "/usr/lib64/python3.4/urllib/request.py", line 267, in __init__
    self.full_url = url
  File "/usr/lib64/python3.4/urllib/request.py", line 293, in full_url
    self._parse()
  File "/usr/lib64/python3.4/urllib/request.py", line 322, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/yts/jsbin/player-en_US-vflkk7pUE/base.js'
Traceback (most recent call last):
  File "/home/vxbinaca/.local/lib/python3.4/site-packages/youtube_dl/extractor/youtube.py", line 1005, in _decrypt_signature
    video_id, player_url, s
  File "/home/vxbinaca/.local/lib/python3.4/site-packages/youtube_dl/extractor/youtube.py", line 919, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "/home/vxbinaca/.local/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 517, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "/home/vxbinaca/.local/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 424, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "/home/vxbinaca/.local/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 404, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/home/vxbinaca/.local/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 2000, in urlopen
    req = sanitized_Request(req)
  File "/home/vxbinaca/.local/lib/python3.4/site-packages/youtube_dl/utils.py", line 513, in sanitized_Request
    return compat_urllib_request.Request(sanitize_url(url), *args, **kwargs)
  File "/usr/lib64/python3.4/urllib/request.py", line 267, in __init__
    self.full_url = url
  File "/usr/lib64/python3.4/urllib/request.py", line 293, in full_url
    self._parse()
  File "/usr/lib64/python3.4/urllib/request.py", line 322, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/yts/jsbin/player-en_US-vflkk7pUE/base.js'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vxbinaca/.local/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/home/vxbinaca/.local/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 357, in extract
    return self._real_extract(url)
  File "/home/vxbinaca/.local/lib/python3.4/site-packages/youtube_dl/extractor/youtube.py", line 1584, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/home/vxbinaca/.local/lib/python3.4/site-packages/youtube_dl/extractor/youtube.py", line 1015, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/home/vxbinaca/.local/lib/python3.4/site-packages/youtube_dl/extractor/youtube.py", line 1005, in _decrypt_signature
    video_id, player_url, s
  File "/home/vxbinaca/.local/lib/python3.4/site-packages/youtube_dl/extractor/youtube.py", line 919, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "/home/vxbinaca/.local/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 517, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "/home/vxbinaca/.local/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 424, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "/home/vxbinaca/.local/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 404, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/home/vxbinaca/.local/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 2000, in urlopen
    req = sanitized_Request(req)
  File "/home/vxbinaca/.local/lib/python3.4/site-packages/youtube_dl/utils.py", line 513, in sanitized_Request
    return compat_urllib_request.Request(sanitize_url(url), *args, **kwargs)
  File "/usr/lib64/python3.4/urllib/request.py", line 267, in __init__
    self.full_url = url
  File "/usr/lib64/python3.4/urllib/request.py", line 293, in full_url
    self._parse()
  File "/usr/lib64/python3.4/urllib/request.py", line 322, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/yts/jsbin/player-en_US-vflkk7pUE/base.js'
 (caused by ValueError("unknown url type: '/yts/jsbin/player-en_US-vflkk7pUE/base.js'",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

**Comment by yan12125** [comment]
@vxbinaca You're using an out-dated version
```
[debug] youtube-dl version 2016.12.09
```
There's an important update in 2017.01.31

**Comment by vitorgalvao** [comment]
Since there are no more reports of this since @yan12125 mentioned the new version, I’d say this can be closed.

**Comment by yan12125** [comment]
@vitorgalvao: The issue vxbinaca gets is a different one. Let's ask @dollabi11z and @renalid whether there are more hanging issues or not. I remember that there are quite a few hanging issues for DASH formats, and many of them proved to be temporary issues. Here I'd like to get confirmation.

**Comment by renalid** [comment]
Hello,
This issue was temporary. I don't reproduce.
Regards,
