### ISSUE TITLE
youtube-dl and konserthusetplay.se

### ISSUE THREAD

**Issue by Moi3679** [rg3/youtube-dl#11823]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.01.24*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.01.24**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

youtube-dl.exe --verbose http://konserthusetplay.se/?m=QYBEuAhagByaRY3UkH7ShQ
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'http://konserthusetplay.se/?m=QYBEuAhagByaRY3UkH7ShQ']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.01.24
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-81774-g64545dd, ffprobe N-81774-g64545dd
[debug] Proxy map: {}
[KonserthusetPlay] QYBEuAhagByaRY3UkH7ShQ: Downloading webpage
[KonserthusetPlay] QYBEuAhagByaRY3UkH7ShQ: Downloading JSON metadata
ERROR: An extractor error has occurred. (caused by StopIteration()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp13s41y6_\build\youtube_dl\extractor\common.py", line 359, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp13s41y6_\build\youtube_dl\extractor\konserthusetplay.py", line 45, in _real_extract
StopIteration
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp13s41y6_\build\youtube_dl\extractor\common.py", line 359, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp13s41y6_\build\youtube_dl\extractor\konserthusetplay.py", line 45, in _real_extract
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp13s41y6_\build\youtube_dl\YoutubeDL.py", line 694, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp13s41y6_\build\youtube_dl\extractor\common.py", line 365, in extract
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by StopIteration()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

---

Hello,
I try to download the video http://konserthusetplay.se/?m=QYBEuAhagByaRY3UkH7ShQ, ideally with English subtitles, but it does not work. Normally the site http://konserthusetplay.se/ is supported.
Thanks in advance.

**Comment by Moi3679** [comment]
Thank you very much.
