### ISSUE TITLE
[video.disney.dk] Unable to download video data

### ISSUE THREAD

**Issue by RuneMagle** [rg3/youtube-dl#11857]
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.01.28**
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

```
C:\Users\rumag\Desktop\youtube-dl>youtube-dl.exe -f best --all-subs http://video.disney.dk/afspil/afsnit-29-53fc63e907a77efc0d92846d -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'best', '--all-subs', 'http://video.disney.dk/afspil/afsnit-29-53fc63e907a77efc0d92846d', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.01.28
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-82833-gedb4f5d, ffprobe N-82833-gedb4f5d, rtmpdump 2.3
[debug] Proxy map: {}
[Disney] 53fc63e907a77efc0d92846d: Downloading webpage
[debug] Invoking downloader on 'http://disintlmedia-a.akamaihd.net/emea/kaltura/content/r71v1/entry/data/616/930/1_hhucokuo_1_fx5g3c9x_2.webm'
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpa1jocv52\build\youtube_dl\YoutubeDL.py", line 1699, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpa1jocv52\build\youtube_dl\YoutubeDL.py", line 1641, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpa1jocv52\build\youtube_dl\downloader\common.py", line 353, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpa1jocv52\build\youtube_dl\downloader\http.py", line 61, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpa1jocv52\build\youtube_dl\YoutubeDL.py", line 2001, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found
...
<end of log>
```
---
- Single video: http://video.disney.dk/afspil/afsnit-29-53fc63e907a77efc0d92846d
- Single video: http://video.disney.dk/afspil/the-lodge/josh-sladrer-er-sean-forelsket-i-skye-540ca9346bfde8f81e4ae991
- Single video: http://video.disney.dk/afspil/star-wars-rebels/afsnit-29-del-1-52e13fa3b522154ee2fc54ef
---

I noticed you added the site I requested, which I am very happy for, but I am not able to download the videos. And I am sure that it runs perfectly in my browser.

**Comment by yan12125** [comment]
Both http://video.disney.dk/afspil/star-wars-rebels/afsnit-29-del-1-52e13fa3b522154ee2fc54ef and http://video.disney.dk/afspil/afsnit-29-53fc63e907a77efc0d92846d says:

> Videoen er ikke tilgængelig

For http://video.disney.dk/afspil/the-lodge/josh-sladrer-er-sean-forelsket-i-skye-540ca9346bfde8f81e4ae991, downloading is fine:
```
$ youtube-dl -v "http://video.disney.dk/afspil/the-lodge/josh-sladrer-er-sean-forelsket-i-skye-540ca9346bfde8f81e4ae991"       
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://video.disney.dk/afspil/the-lodge/josh-sladrer-er-sean-forelsket-i-skye-540ca9346bfde8f81e4ae991']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.02.10
[debug] Git HEAD: e01bfc19c
[debug] Python version 3.6.0 - Linux-4.9.6-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 3.2.2, ffprobe 3.2.2
[debug] Proxy map: {}
[Disney] 540ca9346bfde8f81e4ae991: Downloading webpage
[debug] Invoking downloader on 'http://kaltura.akamaized.net/s/p/1068292/sp/106829200/serveFlavor/entryId/1_gi352lpk/v/1/flavorId/1_ot16sg07/fileName/The_Lodge___Josh_sladrer:_Er_Sean_forelsket_i_Skye__(HD_720_-_WEB_(H264_2500)).mp4/forceproxy/true/name/a.mp4?__hdnea__=st=1478782035~exp=1478803635~acl=/s/p/1068292/sp/106829200/serveFlavor/entryId/1_gi352lpk/v/1/flavorId/1_ot16sg07/fileName/The_Lodge___Josh_sladrer:_Er_Sean_forelsket_i_Skye__(HD_720_-_WEB_(H264_2500)).mp4/forceproxy/true/name/a.mp4*~hmac=d3b165b9cc4cc027b351cb7389591d0de628eea30980602938173ef09d3757bb'
[download] Destination: The Lodge _ Josh sladrer - Er Sean forelsket i Skye-540ca9346bfde8f81e4ae991.mp4
[download]  10.4% of 19.19MiB at 1006.93KiB/s ETA 00:17^CException ignored in: <_io.FileIO name='The Lodge _ Josh sladrer - Er Sean forelsket i Skye-540ca9346bfde8f81e4ae991.mp4.part' mode='wb' closefd=True>
ResourceWarning: unclosed file <_io.BufferedWriter name='The Lodge _ Josh sladrer - Er Sean forelsket i Skye-540ca9346bfde8f81e4ae991.mp4.part'>

ERROR: Interrupted by user
```
Please paste error messages if things are still broken.

**Comment by RuneMagle** [comment]
Oh, it seems to work now. 

Thanks!
