### ISSUE TITLE
Downloading from YouTube fails with 'Rimon' ISP

### ISSUE THREAD

**Issue by ZvikaZ** [rg3/youtube-dl#11877]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.01.29*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.01.29**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
>youtube-dl -v --proxy "" --no-check-certificate https://w
ww.youtube.com/watch?v=SACeGmvxE1A
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--proxy', u'', u'--no-check-certificate', u
'https://www.youtube.com/watch?v=SACeGmvxE1A']
[debug] Encodings: locale cp1255, fs mbcs, out cp862, pref cp1255
[debug] youtube-dl version 2017.01.29
[debug] Python version 2.7.9 - Windows-8-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] SACeGmvxE1A: Downloading webpage
[youtube] SACeGmvxE1A: Downloading video info webpage
[youtube] SACeGmvxE1A: Extracting video information
WARNING: unable to extract uploader nickname
[youtube] SACeGmvxE1A: Downloading embed webpage
[youtube] {22} signature length 44.40, html5 player en_US-vflQBHHdn
[youtube] SACeGmvxE1A: Downloading player https://s.ytimg.com/yts/jsbin/player-e
n_US-vflQBHHdn/base.js
[youtube] {43} signature length 44.40, html5 player en_US-vflQBHHdn
[youtube] {18} signature length 44.40, html5 player en_US-vflQBHHdn
[youtube] {36} signature length 44.40, html5 player en_US-vflQBHHdn
[youtube] {17} signature length 44.40, html5 player en_US-vflQBHHdn
[youtube] {137} signature length 44.40, html5 player en_US-vflQBHHdn
[youtube] {248} signature length 44.40, html5 player en_US-vflQBHHdn
[youtube] {136} signature length 44.40, html5 player en_US-vflQBHHdn
[youtube] {247} signature length 44.40, html5 player en_US-vflQBHHdn
[youtube] {135} signature length 44.40, html5 player en_US-vflQBHHdn
[youtube] {244} signature length 44.40, html5 player en_US-vflQBHHdn
[youtube] {134} signature length 44.40, html5 player en_US-vflQBHHdn
[youtube] {243} signature length 44.40, html5 player en_US-vflQBHHdn
[youtube] {133} signature length 44.40, html5 player en_US-vflQBHHdn
[youtube] {242} signature length 44.40, html5 player en_US-vflQBHHdn
[youtube] {160} signature length 44.40, html5 player en_US-vflQBHHdn
[youtube] {278} signature length 44.40, html5 player en_US-vflQBHHdn
[youtube] {140} signature length 44.40, html5 player en_US-vflQBHHdn
[youtube] {171} signature length 44.40, html5 player en_US-vflQBHHdn
[youtube] {249} signature length 44.40, html5 player en_US-vflQBHHdn
[youtube] {250} signature length 44.40, html5 player en_US-vflQBHHdn
[youtube] {251} signature length 44.40, html5 player en_US-vflQBHHdn
[debug] Invoking downloader on u'https://r3---sn-gphvo-ua8e.googlevideo.com/vide
oplayback?ms=au&mv=m&initcwndbps=21143750&source=youtube&sparams=dur%2Cid%2Cinit
cwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%
2Crequiressl%2Csource%2Cupn%2Cexpire&pl=24&dur=2646.563&mm=31&itag=22&mn=sn-gphv
o-ua8e&upn=8D1mRMidNmA&key=yt6&ipbits=0&mt=1485728424&expire=1485750133&id=o-AL-
8bcA5XMeISC6dZnFffjgAhbIZmleOMiEd7CtsjRvD&mime=video%2Fmp4&ratebypass=yes&requir
essl=yes&lmt=1472431379029221&ip=213.151.47.128&signature=5E61E6A46DA1636CFFAD5E
B5B5931605FE955934395.DFB731158B868A8DD4FD67DB61457FD8C0805E'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 1699, in pr
ocess_info
    success = dl(filename, info_dict)
  File "C:\Python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 1641, in dl

    return fd.download(name, info)
  File "C:\Python27\lib\site-packages\youtube_dl\downloader\common.py", line 353
, in download
    return self.real_download(filename, info_dict)
  File "C:\Python27\lib\site-packages\youtube_dl\downloader\http.py", line 61, i
---


### Description of your *issue*, suggested solution and other information

Hi.
My ISP (Israeli "Rimon") does content filtering and manipulates the HTTP(S) data.
It doesn't allow to watch some YouTube videos.
There are other YouTube videos, that I *can* watch (from Chrome, or other browser), but fail to download through `youtube-dl`.
When I connect to my work VPN (and therefore 'bypass' the ISP), I'm able to download these videos with `youtube-dl`.
(note: when connecting from work, I have to use proxy, which is configured with environment variables; when connecting from Rimon I have to disable that proxy)

Attaching 2 detailed log files, with HTTP traffic.
[work.traffic.txt](https://github.com/rg3/youtube-dl/files/737894/work.traffic.txt)
[rimon.traffic.txt](https://github.com/rg3/youtube-dl/files/737895/rimon.traffic.txt)

It's interesting to diff them.
There are some interesting differences that I don't understand...

Thanks!

**Comment by dstftw** [comment]
So, can you watch https://www.youtube.com/watch?v=SACeGmvxE1A from Rimon in browser without any kind of anonymizing software/plugin enabled?

**Comment by ZvikaZ** [comment]
Yes.

**Comment by dstftw** [comment]
What if you select different format with `-f`?

**Comment by ZvikaZ** [comment]
Seems similar.

```
C:\Users\zharamax\temp>youtube-dl -f worstaudio -v --proxy "" --no-check-certifi
cate https://www.youtube.com/watch?v=SACeGmvxE1A
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-f', u'worstaudio', u'-v', u'--proxy', u'', u'--no
-check-certificate', u'https://www.youtube.com/watch?v=SACeGmvxE1A']
[debug] Encodings: locale cp1255, fs mbcs, out cp862, pref cp1255
[debug] youtube-dl version 2017.01.29
[debug] Python version 2.7.9 - Windows-8-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] SACeGmvxE1A: Downloading webpage
[youtube] SACeGmvxE1A: Downloading video info webpage
[youtube] SACeGmvxE1A: Extracting video information
WARNING: unable to extract uploader nickname
[youtube] SACeGmvxE1A: Downloading embed webpage
[youtube] {22} signature length 40.40, html5 player en_US-vflQBHHdn
[youtube] {43} signature length 40.40, html5 player en_US-vflQBHHdn
[youtube] {18} signature length 40.40, html5 player en_US-vflQBHHdn
[youtube] {36} signature length 40.40, html5 player en_US-vflQBHHdn
[youtube] {17} signature length 40.40, html5 player en_US-vflQBHHdn
[youtube] {137} signature length 40.40, html5 player en_US-vflQBHHdn
[youtube] {248} signature length 40.40, html5 player en_US-vflQBHHdn
[youtube] {136} signature length 40.40, html5 player en_US-vflQBHHdn
[youtube] {247} signature length 40.40, html5 player en_US-vflQBHHdn
[youtube] {135} signature length 40.40, html5 player en_US-vflQBHHdn
[youtube] {244} signature length 40.40, html5 player en_US-vflQBHHdn
[youtube] {134} signature length 40.40, html5 player en_US-vflQBHHdn
[youtube] {243} signature length 40.40, html5 player en_US-vflQBHHdn
[youtube] {133} signature length 40.40, html5 player en_US-vflQBHHdn
[youtube] {242} signature length 40.40, html5 player en_US-vflQBHHdn
[youtube] {160} signature length 40.40, html5 player en_US-vflQBHHdn
[youtube] {278} signature length 40.40, html5 player en_US-vflQBHHdn
[youtube] {140} signature length 40.40, html5 player en_US-vflQBHHdn
[youtube] {171} signature length 40.40, html5 player en_US-vflQBHHdn
[youtube] {249} signature length 40.40, html5 player en_US-vflQBHHdn
[youtube] {250} signature length 40.40, html5 player en_US-vflQBHHdn
[youtube] {251} signature length 40.40, html5 player en_US-vflQBHHdn
[debug] Invoking downloader on u'https://r3---sn-gphvo-ua8e.googlevideo.com/vide
oplayback?clen=16982884&gir=yes&source=youtube&mime=audio%2Fwebm&key=yt6&initcwn
dbps=18818750&itag=249&lmt=1453189853584740&ipbits=0&expire=1485814165&sparams=c
len%2Cdur%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2
Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&mm=31&pl=24&mn=sn-gphvo-ua8e&
id=o-AEIHmZJ6UHWDddYIXIDt1Wyq3CZ3mAFBbW69ecgOc-Af&dur=2646.521&requiressl=yes&mt
=1485792326&mv=m&ms=au&ip=213.151.47.128&upn=XxdlQcWYju0&signature=B5B5CDC64B113
B154324B31EAC955E4ED55D8B2.C602AA7ABA6E0A1E5BC442AB0AFEA3AA27BE2B&ratebypass=yes
'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 1699, in pr
ocess_info
    success = dl(filename, info_dict)
  File "C:\Python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 1641, in dl

    return fd.download(name, info)
  File "C:\Python27\lib\site-packages\youtube_dl\downloader\common.py", line 353
, in download
    return self.real_download(filename, info_dict)
  File "C:\Python27\lib\site-packages\youtube_dl\downloader\http.py", line 61, i
n real_download
    data = self.ydl.urlopen(request)
  File "C:\Python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 2001, in ur
lopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "C:\Python27\lib\urllib2.py", line 437, in open
    response = meth(req, response)
  File "C:\Python27\lib\urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python27\lib\urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "C:\Python27\lib\urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden
```

**Comment by yan12125** [comment]
What's the result of ```nslookup r3---sn-gphvo-ua8e.googlevideo.com``` from within Rimon ISP?

**Comment by ZvikaZ** [comment]
>nslookup r3---sn-gphvo-ua8e.googlevideo.com
Server:  router.asus.com
Address:  192.168.1.1

Non-authoritative answer:
Name:    r3---sn-gphvo-ua8e.googlevideo.com.ger.corp.intel.com
Address:  213.151.33.115

**Comment by yan12125** [comment]
```
$ whois 213.151.33.115 | grep Rimon
descr:          Internet Rimon infrastructre
descr:          Internet Rimon LTD
```
Apparently the connection is hijacked.

**Comment by yan12125** [comment]
You'll need to check DNS settings on router.asus.com(192.168.1.1) or ask your ISP stop hijacking YouTube connections. That's out of the scope of youtube-dl so closing.
