### ISSUE TITLE
ERROR: Signature extraction failed

### ISSUE THREAD

**Issue by karm4ma** [rg3/youtube-dl#11898]
Hey there, yesterday it was working fine. Got this error in the morning.

ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\youtube_dl\extractor\youtube.py", line 1057, in _decrypt_signature
    video_id, player_url, s
  File "C:\Python27\lib\site-packages\youtube_dl\extractor\youtube.py", line 971, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "C:\Python27\lib\site-packages\youtube_dl\extractor\common.py", line 519, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "C:\Python27\lib\site-packages\youtube_dl\extractor\common.py", line 426, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "C:\Python27\lib\site-packages\youtube_dl\extractor\common.py", line 406, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "C:\Python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 2001, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "C:\Python27\lib\urllib2.py", line 421, in open
    protocol = req.get_type()
  File "C:\Python27\lib\urllib2.py", line 283, in get_type
    raise ValueError, "unknown url type: %s" % self.__original
ValueError: unknown url type: /yts/jsbin/player-en_US-vflV3n15C/base.js
 (caused by ValueError(u'unknown url type: /yts/jsbin/player-en_US-vflV3n15C/base.js',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Please fix this issue asap.

**Comment by karm4ma** [comment]
URL that caused the error: https://www.youtube.com/watch?v=91ZI3IrojMU

**Comment by karm4ma** [comment]
It is working for some URLs. It fails most of the time.

**Comment by njuki** [comment]
I'm having the same issue.

**Comment by Repulser** [comment]
Same

**Comment by Repulser** [comment]
Looks like something about the endpoint changing to https?

**Comment by karm4ma** [comment]
Nope, tried http over https..no luck so far.

**Comment by Khang-NT** [comment]
https://github.com/rg3/youtube-dl/pull/11892
Try it:
`pip install --upgrade git+git://github.com/Khang-NT/youtube-dl@master#egg=youtube-dl`

**Comment by njuki** [comment]
@Khang-NT that works. Thanks man!

**Comment by karm4ma** [comment]
Worked like Charm. Thanks.

**Comment by theriddleywalker** [comment]
Thank you @Khang-NT!
