### ISSUE TITLE
ERROR: Signature extraction failed

### ISSUE THREAD

**Issue by dadyalexey** [rg3/youtube-dl#11895]
youtube-dl --verbose https://www.youtube.com/watch?v=7nDKFPWbJMU -o - | mpv --no-video -
Playing: -
[file] Reading from stdin...
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.youtube.com/watch?v=7nDKFPWbJMU', u'-o', u'-']
[debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8
[debug] youtube-dl version 2017.01.29
[debug] Python version 2.7.12 - Linux-4.4.0-36-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.10-0ubuntu0.16.04.1, ffprobe 2.8.10-0ubuntu0.16.04.1
[debug] Proxy map: {}
[cache] Cache is not responding - slow/stuck network connection?
[youtube] 7nDKFPWbJMU: Downloading webpage
[youtube] 7nDKFPWbJMU: Downloading video info webpage
[youtube] 7nDKFPWbJMU: Extracting video information
WARNING: unable to extract uploader nickname
[youtube] {43} signature length 42.43, html5 player en_US-vflV3n15C
[youtube] 7nDKFPWbJMU: Downloading player /yts/jsbin/player-en_US-vflV3n15C/base.js
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1057, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 971, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 529, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 436, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 416, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2001, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 421, in open
    protocol = req.get_type()
  File "/usr/lib/python2.7/urllib2.py", line 283, in get_type
    raise ValueError, "unknown url type: %s" % self.__original
ValueError: unknown url type: /yts/jsbin/player-en_US-vflV3n15C/base.js
 (caused by ValueError(u'unknown url type: /yts/jsbin/player-en_US-vflV3n15C/base.js',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1057, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 971, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 529, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 436, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 416, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2001, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 421, in open
    protocol = req.get_type()
  File "/usr/lib/python2.7/urllib2.py", line 283, in get_type
    raise ValueError, "unknown url type: %s" % self.__original
ValueError: unknown url type: /yts/jsbin/player-en_US-vflV3n15C/base.js
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 369, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1646, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1067, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1057, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 971, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 529, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 436, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 416, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2001, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 421, in open
    protocol = req.get_type()
  File "/usr/lib/python2.7/urllib2.py", line 283, in get_type
    raise ValueError, "unknown url type: %s" % self.__original
ValueError: unknown url type: /yts/jsbin/player-en_US-vflV3n15C/base.js
 (caused by ValueError(u'unknown url type: /yts/jsbin/player-en_US-vflV3n15C/base.js',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Failed to recognize file format.

Exiting... (Errors when loading file)

**Comment by RooTooZ** [comment]
Pull Request https://github.com/rg3/youtube-dl/pull/11892

**Comment by nachanon** [comment]
I have got a similar error today, with [a different URL](https://www.youtube.com/watch?v=lhtHxPI3cxM)...

Command line:

	youtube-dl --list-formats --verbose https://www.youtube.com/watch?v=lhtHxPI3cxM

Youtube-DL output:

	[debug] System config: []
	[debug] User config: []
	[debug] Custom config: []
	[debug] Command-line args: ['--list-formats', '--verbose', 'https://www.youtube.com/watch?v=lhtHxPI3cxM']
	[debug] Encodings: locale cp874, fs mbcs, out cp874, pref cp874
	[debug] youtube-dl version 2017.01.29
	[debug] Python version 3.4.4 - Windows-XP-5.1.2600-SP3
	[debug] exe versions: none
	[debug] Proxy map: {}
	[youtube] lhtHxPI3cxM: Downloading webpage
	[youtube] lhtHxPI3cxM: Downloading video info webpage
	[youtube] lhtHxPI3cxM: Extracting video information
	[youtube] {43} signature length 42.43, html5 player en_US-vflV3n15C
	[youtube] lhtHxPI3cxM: Downloading player /yts/jsbin/player-en_US-vflV3n15C/base.js
	ERROR: Signature extraction failed: Traceback (most recent call last):
	  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\youtube.py", line 1057, in _decrypt_signature
	  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\youtube.py", line 971, in _extract_signature_function
	  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\common.py", line 529, in _download_webpage
	  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\common.py", line 436, in _download_webpage_handle
	  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\common.py", line 416, in _request_webpage
	  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\YoutubeDL.py", line 2000, in urlopen
	  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\utils.py", line 525, in sanitized_Request
	  File "C:\Python\Python34\lib\urllib\request.py", line 267, in __init__
	  File "C:\Python\Python34\lib\urllib\request.py", line 293, in full_url
	  File "C:\Python\Python34\lib\urllib\request.py", line 322, in _parse
	ValueError: unknown url type: '/yts/jsbin/player-en_US-vflV3n15C/base.js'
	 (caused by ValueError("unknown url type: '/yts/jsbin/player-en_US-vflV3n15C/base.js'",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
	Traceback (most recent call last):
	  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\youtube.py", line 1057, in _decrypt_signature
	  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\youtube.py", line 971, in _extract_signature_function
	  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\common.py", line 529, in _download_webpage
	  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\common.py", line 436, in _download_webpage_handle
	  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\common.py", line 416, in _request_webpage
	  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\YoutubeDL.py", line 2000, in urlopen
	  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\utils.py", line 525, in sanitized_Request
	  File "C:\Python\Python34\lib\urllib\request.py", line 267, in __init__
	  File "C:\Python\Python34\lib\urllib\request.py", line 293, in full_url
	  File "C:\Python\Python34\lib\urllib\request.py", line 322, in _parse
	ValueError: unknown url type: '/yts/jsbin/player-en_US-vflV3n15C/base.js'
	Traceback (most recent call last):
	  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\youtube.py", line 1057, in _decrypt_signature
	  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\youtube.py", line 971, in _extract_signature_function
	  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\common.py", line 529, in _download_webpage
	  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\common.py", line 436, in _download_webpage_handle
	  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\common.py", line 416, in _request_webpage
	  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\YoutubeDL.py", line 2000, in urlopen
	  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\utils.py", line 525, in sanitized_Request
	  File "C:\Python\Python34\lib\urllib\request.py", line 267, in __init__
	  File "C:\Python\Python34\lib\urllib\request.py", line 293, in full_url
	  File "C:\Python\Python34\lib\urllib\request.py", line 322, in _parse
	ValueError: unknown url type: '/yts/jsbin/player-en_US-vflV3n15C/base.js'
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\YoutubeDL.py", line 694, in extract_info
	  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\common.py", line 369, in extract
	  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\youtube.py", line 1646, in _real_extract
	  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\youtube.py", line 1067, in _decrypt_signature
	youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
	  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\youtube.py", line 1057, in _decrypt_signature
	  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\youtube.py", line 971, in _extract_signature_function
	  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\common.py", line 529, in _download_webpage
	  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\common.py", line 436, in _download_webpage_handle
	  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\common.py", line 416, in _request_webpage
	  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\YoutubeDL.py", line 2000, in urlopen
	  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\utils.py", line 525, in sanitized_Request
	  File "C:\Python\Python34\lib\urllib\request.py", line 267, in __init__
	  File "C:\Python\Python34\lib\urllib\request.py", line 293, in full_url
	  File "C:\Python\Python34\lib\urllib\request.py", line 322, in _parse
	ValueError: unknown url type: '/yts/jsbin/player-en_US-vflV3n15C/base.js'
	 (caused by ValueError("unknown url type: '/yts/jsbin/player-en_US-vflV3n15C/base.js'",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Note: YouTube-DL terminated with exit code 1.

I will wait to see if next release fixes this issue once the pull request is accepted.

Youtube-DL: 2017.01.29 (EXE release)
System: Microsoft Windows XP Professional SP3
