### ISSUE TITLE
Signature extraction failed

### ISSUE THREAD

**Issue by parsasaei** [rg3/youtube-dl#11897]
Hi.I'm using the **latest version** of youtube-dl zipped version [:2017.01.29](https://yt-dl.org/downloads/2017.01.29/youtube-dl)
and **exe version** returns this error too.
What is this issue?And how can I solve this issue?

ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6cf1z6ka\bu
ild\youtube_dl\extractor\youtube.py", line 987, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6cf1z6ka\bu
ild\youtube_dl\extractor\youtube.py", line 901, in _extract_signature_function
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6cf1z6ka\bu
ild\youtube_dl\extractor\common.py", line 507, in _download_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6cf1z6ka\bu
ild\youtube_dl\extractor\common.py", line 414, in _download_webpage_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6cf1z6ka\bu
ild\youtube_dl\extractor\common.py", line 394, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6cf1z6ka\bu
ild\youtube_dl\YoutubeDL.py", line 1997, in urlopen
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6cf1z6ka\bu
ild\youtube_dl\utils.py", line 501, in sanitized_Request
  File "C:\Python\Python34\lib\urllib\request.py", line 267, in __init__
  File "C:\Python\Python34\lib\urllib\request.py", line 293, in full_url
  File "C:\Python\Python34\lib\urllib\request.py", line 322, in _parse
ValueError: unknown url type: '/yts/jsbin/player-en_US-vflV3n15C/base.js'
 (caused by ValueError("unknown url type: '/yts/jsbin/player-en_US-vflV3n15C/bas
e.js'",)); please report this issue on https://yt-dl.org/bug . Make sure you are
 using the latest version; type  youtube-dl -U  to update. Be sure to call youtu
be-dl with the --verbose flag and include its complete output.

**Comment by palmtree5** [comment]
#11892
