### ISSUE TITLE
Strange behavior on some youtube video (not protected, as it seems)

### ISSUE THREAD

**Issue by nmr50** [rg3/youtube-dl#11911]
Hello dear coders! I've been about to get some nice video, and what I met:
C:>youtube-dl.exe -v -F https://youtu.be/dihoTVuqjNc
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://youtu.be/dihoTVuqjNc']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2017.01.29
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 3.2.2, ffprobe 3.2.2
[debug] Proxy map: {}
[youtube] dihoTVuqjNc: Downloading webpage
[youtube] dihoTVuqjNc: Downloading video info webpage
[youtube] dihoTVuqjNc: Extracting video information
[youtube] {43} signature length 42.43, html5 player en_US-vflV3n15C
[youtube] dihoTVuqjNc: Downloading player /yts/jsbin/player-en_US-vflV3n15C/base.js
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\youtube.py", line 1057, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\youtube.py", line 971, in _extract_signature_function
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\common.py", line 529, in _download_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\common.py", line 436, in _download_webpage_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\common.py", line 416, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\YoutubeDL.py", line 2000, in urlopen
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\utils.py", line 525, in sanitized_Request
  File "C:\Python\Python34\lib\urllib\request.py", line 267, in __init__
  File "C:\Python\Python34\lib\urllib\request.py", line 293, in full_url
  File "C:\Python\Python34\lib\urllib\request.py", line 322, in _parse
ValueError: unknown url type: '/yts/jsbin/player-en_US-vflV3n15C/base.js'
 (caused by ValueError("unknown url type: '/yts/jsbin/player-en_US-vflV3n15C/base.js'",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\youtube.py", line 1057, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\youtube.py", line 971, in _extract_signature_function
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\common.py", line 529, in _download_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\common.py", line 436, in _download_webpage_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\common.py", line 416, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\YoutubeDL.py", line 2000, in urlopen
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\utils.py", line 525, in sanitized_Request
  File "C:\Python\Python34\lib\urllib\request.py", line 267, in __init__
  File "C:\Python\Python34\lib\urllib\request.py", line 293, in full_url
  File "C:\Python\Python34\lib\urllib\request.py", line 322, in _parse
ValueError: unknown url type: '/yts/jsbin/player-en_US-vflV3n15C/base.js'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\youtube.py", line 1057, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\youtube.py", line 971, in _extract_signature_function
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\common.py", line 529, in _download_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\common.py", line 436, in _download_webpage_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\common.py", line 416, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\YoutubeDL.py", line 2000, in urlopen
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\utils.py", line 525, in sanitized_Request
  File "C:\Python\Python34\lib\urllib\request.py", line 267, in __init__
  File "C:\Python\Python34\lib\urllib\request.py", line 293, in full_url
  File "C:\Python\Python34\lib\urllib\request.py", line 322, in _parse
ValueError: unknown url type: '/yts/jsbin/player-en_US-vflV3n15C/base.js'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\YoutubeDL.py", line 694,in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\common.py", line 369, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\youtube.py", line 1646, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\youtube.py", line 1067, in _decrypt_signature
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\youtube.py", line 1057, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\youtube.py", line 971, in _extract_signature_function
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\common.py", line 529, in _download_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\common.py", line 436, in _download_webpage_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\extractor\common.py", line 416, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\YoutubeDL.py", line 2000, in urlopen
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw2prp8oz\build\youtube_dl\utils.py", line 525, in sanitized_Request
  File "C:\Python\Python34\lib\urllib\request.py", line 267, in __init__
  File "C:\Python\Python34\lib\urllib\request.py", line 293, in full_url
  File "C:\Python\Python34\lib\urllib\request.py", line 322, in _parse
ValueError: unknown url type: '/yts/jsbin/player-en_US-vflV3n15C/base.js'
 (caused by ValueError("unknown url type: '/yts/jsbin/player-en_US-vflV3n15C/base.js'",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
-- Please fix this stuff as soon as possible. Thanks in advance !:)

**Comment by jaydenkieran** [comment]
Duplicate of #11890

**Comment by nmr50** [comment]
Closed because issue https://github.com/rg3/youtube-dl/issues/11890 is still active
