### ISSUE TITLE
[youtube] TL* playlist format not recognized by youtube-dl

### ISSUE THREAD

**Issue by mateon1** [rg3/youtube-dl#11945]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.02.01*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
>youtube-dl -vs TLGGrESM50VT6acwMjAyMjAxNw
[debug] System config: []
[debug] User config: ['-o', 'D:/V/%(extractor)s/%(uploader)s/%(title)s/%(format)s.%(ext)s', '-f', 'bestvideo+bestaudio,best']
[debug] Custom config: []
[debug] Command-line args: ['-vs', 'TLGGrESM50VT6acwMjAyMjAxNw']
[debug] Encodings: locale cp1250, fs mbcs, out cp852, pref cp1250
[debug] youtube-dl version 2017.02.01
[debug] Python version 3.4.4 - Windows-10-10.0.14965
[debug] exe versions: ffmpeg 2.8.4, ffprobe 3.0.1
[debug] Proxy map: {}
ERROR: 'TLGGrESM50VT6acwMjAyMjAxNw' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:TLGGrESM50VT6acwMjAyMjAxNw" ) to search YouTube
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4a0k6hcr\build\youtube_dl\YoutubeDL.py", line 694, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4a0k6hcr\build\youtube_dl\extractor\common.py", line 369, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4a0k6hcr\build\youtube_dl\extractor\generic.py", line 1601, in _real_extract
youtube_dl.utils.ExtractorError: 'TLGGrESM50VT6acwMjAyMjAxNw' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:TLGGrESM50VT6acwMjAyMjAxNw" ) to search YouTube
```

---

### Description of your *issue*, suggested solution and other information

When trying to download a playlist like `TLGGrESM50VT6acwMjAyMjAxNw` using just the ID, it's not recognized as a Youtube playlist ID, similar to how `PL...`, `LL...` and `FL...` playlists are handled (automatically recognized as the `[youtube:playlist]` plugin).
`youtube-dl youtube.com/playlist?list=TLGGrESM50VT6acwMjAyMjAxNw` works, however.

It seems that `TL` is used for batch uploads of videos in subscriber notifications.

**Comment by mateon1** [comment]
Relevant source:
https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/youtube.py#L1860,L1866
