### ISSUE TITLE
"unknown url type" exception on youtube song

### ISSUE THREAD

**Issue by xczheng** [rg3/youtube-dl#11950]
$ youtube-dl  -v  https://www.youtube.com/watch?v=7F37r50VUTQ
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=7F37r50VUTQ']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.01.29
[debug] Python version 3.6.0 - Linux-3.2.61-grsec-modsign-x86_64-with-debian-wheezy-sid
[debug] exe versions: avconv 0.8.17-4, avprobe 0.8.17-4, ffmpeg 3.2.2-static, ffprobe 3.2.2-static
[debug] Proxy map: {}
[youtube] 7F37r50VUTQ: Downloading webpage
[youtube] 7F37r50VUTQ: Downloading video info webpage
[youtube] 7F37r50VUTQ: Extracting video information
[youtube] {22} signature length 42.43, html5 player en_US-vflp0EuAP
[youtube] 7F37r50VUTQ: Downloading player /yts/jsbin/player-en_US-vflp0EuAP/base.js
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/home/user/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1057, in _decrypt_signature
    video_id, player_url, s
  File "/home/user/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 971, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "/home/user/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 529, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "/home/user/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 436, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "/home/user/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 416, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/home/user/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 2000, in urlopen
    req = sanitized_Request(req)
  File "/home/user/lib/python3.6/site-packages/youtube_dl/utils.py", line 525, in sanitized_Request
    return compat_urllib_request.Request(sanitize_url(url), *args, **kwargs)
  File "/home/user/lib/python3.6/urllib/request.py", line 329, in __init__
    self.full_url = url
  File "/home/user/lib/python3.6/urllib/request.py", line 355, in full_url
    self._parse()
  File "/home/user/lib/python3.6/urllib/request.py", line 384, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/yts/jsbin/player-en_US-vflp0EuAP/base.js'
 (caused by ValueError("unknown url type: '/yts/jsbin/player-en_US-vflp0EuAP/base.js'",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/user/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1057, in _decrypt_signature
    video_id, player_url, s
  File "/home/user/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 971, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "/home/user/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 529, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "/home/user/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 436, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "/home/user/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 416, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/home/user/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 2000, in urlopen
    req = sanitized_Request(req)
  File "/home/user/lib/python3.6/site-packages/youtube_dl/utils.py", line 525, in sanitized_Request
    return compat_urllib_request.Request(sanitize_url(url), *args, **kwargs)
  File "/home/user/lib/python3.6/urllib/request.py", line 329, in __init__
    self.full_url = url
  File "/home/user/lib/python3.6/urllib/request.py", line 355, in full_url
    self._parse()
  File "/home/user/lib/python3.6/urllib/request.py", line 384, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/yts/jsbin/player-en_US-vflp0EuAP/base.js'
Traceback (most recent call last):
  File "/home/user/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1057, in _decrypt_signature
    video_id, player_url, s
  File "/home/user/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 971, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "/home/user/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 529, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "/home/user/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 436, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "/home/user/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 416, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/home/user/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 2000, in urlopen
    req = sanitized_Request(req)
  File "/home/user/lib/python3.6/site-packages/youtube_dl/utils.py", line 525, in sanitized_Request
    return compat_urllib_request.Request(sanitize_url(url), *args, **kwargs)
  File "/home/user/lib/python3.6/urllib/request.py", line 329, in __init__
    self.full_url = url
  File "/home/user/lib/python3.6/urllib/request.py", line 355, in full_url
    self._parse()
  File "/home/user/lib/python3.6/urllib/request.py", line 384, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/yts/jsbin/player-en_US-vflp0EuAP/base.js'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/home/user/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 369, in extract
    return self._real_extract(url)
  File "/home/user/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1646, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/home/user/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1067, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/home/user/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1057, in _decrypt_signature
    video_id, player_url, s
  File "/home/user/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 971, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "/home/user/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 529, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "/home/user/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 436, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "/home/user/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 416, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/home/user/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 2000, in urlopen
    req = sanitized_Request(req)
  File "/home/user/lib/python3.6/site-packages/youtube_dl/utils.py", line 525, in sanitized_Request
    return compat_urllib_request.Request(sanitize_url(url), *args, **kwargs)
  File "/home/user/lib/python3.6/urllib/request.py", line 329, in __init__
    self.full_url = url
  File "/home/user/lib/python3.6/urllib/request.py", line 355, in full_url
    self._parse()
  File "/home/user/lib/python3.6/urllib/request.py", line 384, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/yts/jsbin/player-en_US-vflp0EuAP/base.js'
 (caused by ValueError("unknown url type: '/yts/jsbin/player-en_US-vflp0EuAP/base.js'",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [this FAQ entry](https://yt-dl.org/update) if you have troubles updating.
