### ISSUE TITLE
[twitch] player.twitch.tv 'channel' parameter support

### ISSUE THREAD

**Issue by hummitus** [rg3/youtube-dl#11971]
---
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.02.01*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.01**

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other
---
```
$ youtube-dl -vg https://player.twitch.tv/?channel=lotsofs
[debug] System config: []
[debug] User config: ['--no-mtime']
[debug] Custom config: []
[debug] Command-line args: ['-vg', 'https://player.twitch.tv/?channel=lotsofs']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.02.01
[debug] Python version 3.6.0 - Linux-4.9.6-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 3.2.2, ffprobe 3.2.2, rtmpdump 2.4
[debug] Proxy map: {}
WARNING: Falling back on generic information extractor.
ERROR: Unsupported URL: https://player.twitch.tv/?channel=lotsofs
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 369, in extract
    return self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2551, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://player.twitch.tv/?channel=lotsofs
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Any at the moment live twitch.tv channel: ```player.twitch.tv/?channel=streamer-username```

---

### Description of your *issue*, suggested solution and other information

Issue: https://github.com/rg3/youtube-dl/commit/9a0f999585e392f04541e4f6d5c8d26cf18d31a8 only added support for the VOD parameter ```player.twitch.tv/?video=vXYZ```
Solution: implement functionality to support the 'channel' parameter

**Comment by hummitus** [comment]
Cheers :thumbsup:
