### ISSUE TITLE
please support wired.com 

### ISSUE THREAD

**Issue by shirishag75** [rg3/youtube-dl#11998]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.02.04.1*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.04.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Site support request (request for adding support for a new site)

```
[$] youtube-dl -vF "https://www.wired.com/2017/02/airbus-kinda-serious-swappable-plane-interiors-cafes-spas/"                      
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-vF', u'https://www.wired.com/2017/02/airbus-kinda-serious-swappable-plane-interiors-cafes-spas/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.02.04.1
[debug] Python version 2.7.13 - Linux-4.9.0-1-amd64-x86_64-with-debian-9.0
[debug] exe versions: ffmpeg 3.2.2-2, ffprobe 3.2.2-2, rtmpdump 2.4
[debug] Proxy map: {}
[generic] airbus-kinda-serious-swappable-plane-interiors-cafes-spas: Requesting header
WARNING: Falling back on generic information extractor.
[generic] airbus-kinda-serious-swappable-plane-interiors-cafes-spas: Downloading webpage
[generic] airbus-kinda-serious-swappable-plane-interiors-cafes-spas: Extracting information
ERROR: Unsupported URL: https://www.wired.com/2017/02/airbus-kinda-serious-swappable-plane-interiors-cafes-spas/
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1711, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2526, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2515, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 6, column 16
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 696, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 369, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2551, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.wired.com/2017/02/airbus-kinda-serious-swappable-plane-interiors-cafes-spas/
```

Hopefully this can be fixed.

**Comment by Hrxn** [comment]
This still doesn't work with latest youtube-dl.


```
PS E:\> youtube-dl -U
youtube-dl is up-to-date (2017.07.02)
PS E:\> youtube-dl -v --ignore-config "https://www.wired.com/story/f-35-fighter-jet-paris-air-show-flight-video/"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--ignore-config', 'https://www.wired.com/story/f-35-fighter-jet-paris-air-show-flight-video/']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.07.02
[debug] Python version 3.4.4 - Windows-10-10.0.15063
[debug] exe versions: ffmpeg N-86691-gc885356, ffprobe N-86691-gc885356
[debug] Proxy map: {}
[generic] f-35-fighter-jet-paris-air-show-flight-video: Requesting header
WARNING: Falling back on generic information extractor.
[generic] f-35-fighter-jet-paris-air-show-flight-video: Downloading webpage
[generic] f-35-fighter-jet-paris-air-show-flight-video: Extracting information
ERROR: Unsupported URL: https://www.wired.com/story/f-35-fighter-jet-paris-air-show-flight-video/
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcnuqbtg0\build\youtube_dl\YoutubeDL.py", line 762, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcnuqbtg0\build\youtube_dl\extractor\common.py", line 433, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcnuqbtg0\build\youtube_dl\extractor\generic.py", line 2824, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.wired.com/story/f-35-fighter-jet-paris-air-show-flight-video/

PS E:\>
```

I'd think that Wired is not really a niche site.
From `supportedsites.md`
> CondeNast: Condé Nast media group: Allure, Architectural Digest, Ars Technica, Bon Appétit, Brides, Condé Nast, Condé Nast Traveler, Details, Epicurious, GQ, Glamour, Golf Digest, SELF, Teen Vogue, The New Yorker, Vanity Fair, Vogue, W Magazine, WIRED

Other Conde Nast sites tested by me not working right now:
Vanity Fair (`vanityfair.com` & `video.vanityfair.com`)
Vogue (`video.vogue.com`)
GQ (`video.gq.com`)

Errors: `youtube_dl.utils.RegexNotFoundError: Unable to extract video id;`

Note: Some of these sites (but not all, and there are some exceptions apparently) display videos hosted on _The Scene_, a video platform also owned by Conde Nast and supported by youtube-dl.
If you follow through and use the link with `thescene.com`, it still seems to work.

**Comment by Hrxn** [comment]
Ping @dstftw @yan12125 

In the meantime, maybe update [supportedsites.md](https://github.com/rg3/youtube-dl/blob/master/docs/supportedsites.md) to reflect that Wired is not supported right now, for the sake of consistency?

**Comment by Hrxn** [comment]
https://github.com/rg3/youtube-dl/releases/tag/2017.09.15

> - [condenast] Fix extraction (#14196, #14207)

**Comment by yan12125** [comment]
Thanks for calling back. However, support for wired.com is still broken.

> maybe update supportedsites.md to reflect that Wired is not supported right now

There's a _WORKING mark, which applies to the whole extractor. In other words, if ```_WORKING = False``` is added to condenast.py, all related websites will be marked as broken. A fine-grained _WORKING mark is necessary for that.
