### ISSUE TITLE
[Openload] Unable To Download Video From This Openload Website

### ISSUE THREAD

**Issue by boxstore** [rg3/youtube-dl#12001]
Unable To Download Video From This Openload Website

**Comment by pitsi** [comment]
I would say I have that too, but I downgraded to v2017.02.04 and the problem happens there too, so I guess it is some change on the openload site.

I use youtube-dl via mpv, which plays video streams without downloading first and it did work properly yesterday. In case you are looking for a log to help, here

http://paste.debian.net/913133/

The pastebin link expires in 3 days and I use the youtube-dl binary from your page stored and run from my ~/bin file because my distro's version is 2 months old.

**Comment by sudovijay** [comment]
Here try this fix! #12002

**Comment by pitsi** [comment]
How do I apply a patch to an already executable file?

```
$ file bin/youtube-dl 
bin/youtube-dl: a /usr/bin/env python script executable (binary data)
```

**Comment by dautushenka** [comment]
> Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.6/dist-packages/youtube_dl/__init__.py", line 452, in main
    _real_main(argv)
  File "/usr/local/lib/python2.6/dist-packages/youtube_dl/__init__.py", line 442, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/local/lib/python2.6/dist-packages/youtube_dl/YoutubeDL.py", line 1796, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/local/lib/python2.6/dist-packages/youtube_dl/YoutubeDL.py", line 696, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.6/dist-packages/youtube_dl/extractor/common.py", line 369, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python2.6/dist-packages/youtube_dl/extractor/openload.py", line 85, in _real_extract
    first_three_chars - fifth_char * int(float(ol_id[num + 3:][:2])))
ValueError: unichr() arg not in range(0x110000) (wide Python build)
~# python --version
Python 2.6.6

Didn't try fix from PR yet.

**Comment by yan12125** [comment]
Please move to #10408 for further discussion.
