### ISSUE TITLE
problem with openload

### ISSUE THREAD

**Issue by treakiandroid** [rg3/youtube-dl#12017]
```
$ youtube-dl --verbose https://openload.co/f/NQm6o5iEhlk/stars-no.game.no.life.ova1.480p.mkv https://openload.co/f/UquthgpRQ-E/stars-no.game.no.life.ova2.480p.mkv https://openload.co/f/kX7d0RUuPrA/stars-no.game.no.life.ova3.480p.mkv https://openload.co/f/2RLXFu3f0as/stars-no.game.no.life.ova4.480p.mkv https://openload.co/f/L-pN7wl2m1M/stars-no.game.no.life.ova5.480p.mkv https://openload.co/f/ciXK6b7n_5I/stars-no.game.no.life.ova6.480p.mkv
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://openload.co/f/NQm6o5iEhlk/stars-no.game.no.life.ova1.480p.mkv', u'https://openload.co/f/UquthgpRQ-E/stars-no.game.no.life.ova2.480p.mkv', u'https://openload.co/f/kX7d0RUuPrA/stars-no.game.no.life.ova3.480p.mkv', u'https://openload.co/f/2RLXFu3f0as/stars-no.game.no.life.ova4.480p.mkv', u'https://openload.co/f/L-pN7wl2m1M/stars-no.game.no.life.ova5.480p.mkv', u'https://openload.co/f/ciXK6b7n_5I/stars-no.game.no.life.ova6.480p.mkv']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.02.07
[debug] Python version 2.7.9 - Linux-4.2.0-0.bpo.1-amd64-x86_64-with-debian-8.6
[debug] exe versions: ffmpeg 2.8.9, ffprobe 2.8.9, rtmpdump 2.4
[debug] Proxy map: {}
[Openload] NQm6o5iEhlk: Downloading webpage
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/treaki/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/home/treaki/bin/youtube-dl/youtube_dl/__init__.py", line 452, in main
  File "/home/treaki/bin/youtube-dl/youtube_dl/__init__.py", line 442, in _real_main
  File "/home/treaki/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1796, in download
  File "/home/treaki/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 696, in extract_info
  File "/home/treaki/bin/youtube-dl/youtube_dl/extractor/common.py", line 369, in extract
  File "/home/treaki/bin/youtube-dl/youtube_dl/extractor/openload.py", line 85, in _real_extract
ValueError: unichr() arg not in range(0x110000) (wide Python build)
```

**Comment by yan12125** [comment]
This is fixed in #14225, which will be included in the next version. Thanks to @Tithen-Firion!
