### ISSUE TITLE
Support toukoucity.to

### ISSUE THREAD

**Issue by ogekve** [rg3/youtube-dl#12010]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.07**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Site support request (request for adding support for a new site)

---
Support toukoucity.to

Support for http://toukoucity.to should be pretty easy, as the video is always called "video.mp4" in the page's source. Example below.

$ youtube-dl --version
2017.02.07
$ youtube-dl http://toukoucity.to/video/VpvpP3ghin/
[debug] System config: []
[debug] User config: [u'--no-overwrites', u'--continue', u'--verbose', u'-f', u'best']
[debug] Custom config: []
[debug] Command-line args: [u'http://toukoucity.to/video/VpvpP3ghin/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.02.07
[debug] Python version 2.7.9 - Linux-3.16.0-4-686-pae-i686-with-debian-8.7
[debug] exe versions: avconv 11.8-6, avprobe 11.8-6
[debug] Proxy map: {}
[generic] VpvpP3ghin: Requesting header
[redirect] Following redirect to http://toukoucity.to/
[generic] toukoucity: Requesting header
WARNING: Falling back on generic information extractor.
[generic] toukoucity: Downloading webpage
[generic] toukoucity: Extracting information
ERROR: Unsupported URL: http://toukoucity.to/
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1741, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2526, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2515, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 4, column 451
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 696, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 369, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2589, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://toukoucity.to/
<end of log>

additional info:
Source of page and the video.mp4 link. Which is easy to download, but youtube-dl would make it even easier.
-From URL: "view-source:http://toukoucity.to/video/VpvpP3ghin/"
so.addVariable('file','http://107.182.234.250/p1/VpvpP3ghin/video.mp4');
-
So
wget http://107.182.234.250/p1/VpvpP3ghin/video.mp4 -O toukoucity-VpvpP3ghin.mp4
works now.
Note that the IP number and sub-dir "P1" are subject to change depending on the URL.

I don't think the site has alternative formats, so http://toukoucity.to/video/FFFFFFFFFF/ seems to be the only URL format.

**Comment by Wandang** [comment]
https://github.com/rg3/youtube-dl/pull/3536/commits

This was done before but never integrated/pulled into the project (AFAIK) and therefore I assume this provider is not allowed?
