### ISSUE TITLE
uplynk/Viceland: Connection reset when downloading with hlsnative

### ISSUE THREAD

**Issue by voltagex** [rg3/youtube-dl#12043]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.02.07*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.07**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
voltagex@gentoo ~ $ youtube-dl -v -4 -f "best[height=720]" --all-subs https://www.viceland.com/en_us/video/monday-february-6-2017/5895150563b11c126b7df089
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-4', '-f', 'best[height=720]', '--all-subs', 'https://www.viceland.com/en_us/video/monday-february-6-2017/5895150563b11c126b7df089']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.02.07
[debug] Python version 3.4.5 - Linux-4.9.6-gentoo-r1-x86_64-Intel-R-_Core-TM-_i7-6800K_CPU_@_3.40GHz-with-gentoo-2.3
[debug] exe versions: ffmpeg 2.8.10, ffprobe 2.8.10
[debug] Proxy map: {}
[Viceland] 5895150563b11c126b7df089: Downloading webpage
[Viceland] 5895150563b11c126b7df089: Downloading JSON metadata
[uplynk:preplay] b9dc2b5e74d341a3bddee2be1b17ee36: Downloading JSON metadata
[uplynk:preplay] b9dc2b5e74d341a3bddee2be1b17ee36: Downloading m3u8 information
[uplynk:preplay] b9dc2b5e74d341a3bddee2be1b17ee36: Downloading JSON metadata
[info] Writing video subtitles to: Monday, February 6, 2017-5895150563b11c126b7df089.en.vtt
[debug] Invoking downloader on 'http://content-ausw1.uplynk.com/b9dc2b5e74d341a3bddee2be1b17ee36/g.m3u8'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 334
[download] Destination: Monday, February 6, 2017-5895150563b11c126b7df089.mp4
[download]   0.2% of ~35.63MiB at  6.75MiB/s ETA 14:14ERROR: unable to download video data: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1704, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1646, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 353, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/hls.py", line 121, in real_download
    'http_headers': info_dict.get('http_headers'),
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 353, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 165, in real_download
    data_block = data.read(block_size if not is_test else min(block_size, data_len - byte_counter))
  File "/usr/lib64/python3.4/http/client.py", line 537, in read
    return super(HTTPResponse, self).read(amt)
  File "/usr/lib64/python3.4/http/client.py", line 576, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib64/python3.4/socket.py", line 378, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer

...
<end of log>
```

---

### Description of your *issue*, suggested solution and other information
This site is geoblocked, but I don't believe it's a connection issue - something else is going on. I can't use ffmpeg as the grabber due to https://github.com/rg3/youtube-dl/issues/11496

**Comment by remitamine** [comment]
```
python __main__.py https://www.viceland.com/en_us/video/monday-february-6-2017/5895150563b11c126b7df089
[Viceland] 5895150563b11c126b7df089: Downloading webpage
[Viceland] 5895150563b11c126b7df089: Retrieving Media Token
[Viceland] 5895150563b11c126b7df089: Downloading JSON metadata
[uplynk:preplay] b9dc2b5e74d341a3bddee2be1b17ee36: Downloading JSON metadata
[uplynk:preplay] b9dc2b5e74d341a3bddee2be1b17ee36: Downloading m3u8 information
[uplynk:preplay] b9dc2b5e74d341a3bddee2be1b17ee36: Downloading JSON metadata
WARNING: ar subtitles not available for 5895150563b11c126b7df089
[info] Writing video subtitles to: Monday, February 6, 2017-5895150563b11c126b7df089.en.vtt
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 334
[download] Destination: Monday, February 6, 2017-5895150563b11c126b7df089.mp4
[download]  12.0% of ~414.19MiB at 129.46KiB/s ETA 55:10
```
