### ISSUE TITLE
Can't download videos from YouTube: TypeError: XML() got an unexpected keyword argument 'parser'

### ISSUE THREAD

**Issue by pschloss** [rg3/youtube-dl#12076]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.02.10*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.10**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

```
youtube-dl  -v "https://www.youtube.com/watch?v=o7LByfB_LYo"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=o7LByfB_LYo']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.02.10
[debug] Python version 3.1.3 - Darwin-15.6.0-x86_64-i386-32bit
[debug] exe versions: ffmpeg SVN-r26402, ffprobe SVN-r26402
[debug] Proxy map: {}
[youtube] o7LByfB_LYo: Downloading webpage
[youtube] o7LByfB_LYo: Downloading video info webpage
[youtube] o7LByfB_LYo: Extracting video information
[youtube] o7LByfB_LYo: Downloading MPD manifest
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.1/lib/python3.1/runpy.py", line 128, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Library/Frameworks/Python.framework/Versions/3.1/lib/python3.1/runpy.py", line 34, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 452, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 442, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1796, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 696, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 369, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1739, in _real_extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1570, in _extract_mpd_formats
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2497, in compat_etree_fromstring
TypeError: XML() got an unexpected keyword argument 'parser'
```

---

### Description of your *issue*, suggested solution and other information

I am getting an error downloading this and other YouTube videos (e.g. https://www.youtube.com/watch?v=r8_A8nrRAfA)

**Comment by dstftw** [comment]
youtube-dl does not support python 3.1.

**Comment by pschloss** [comment]
thanks. so now what do i do?

**Comment by dstftw** [comment]
Update python, huh?

**Comment by pschloss** [comment]
to...
