### ISSUE TITLE
[site-support-request] thehill.com

### ISSUE THREAD

**Issue by johnhawkinson** [rg3/youtube-dl#12103]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.11**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Site support request (request for adding support for a new site)
---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

thehill.com (news site for Washington, DC -- i.e. "capital hill") seems to use a lot of different embedded players on different article pages, and youtube-dl is hit-or-miss with them.

The one I got stuck on today is
http://thehill.com/homenews/senate/319143-franken-says-he-would-have-told-trump-calling-warren-pocahontas-was-racist
which seems to use Akamai AMP via something called inform-news, although I'm not really sure.
I wasn't able to find any similar extractors, though obviously there is some support for Akamai AMP, so maybe I am just looking in the wrong place.

---
```
$ youtube-dl -v 'http://thehill.com/homenews/senate/319143-franken-says-he-would-have-told-trump-calling-warren-pocahontas-was-racist'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'http://thehill.com/homenews/senate/319143-franken-says-he-would-have-told-trump-calling-warren-pocahontas-was-racist']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.02.11
[debug] Python version 2.7.10 - Darwin-14.5.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.1.5, ffprobe 3.1.5, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 319143-franken-says-he-would-have-told-trump-calling-warren-pocahontas-was-racist: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 319143-franken-says-he-would-have-told-trump-calling-warren-pocahontas-was-racist: Downloading webpage
[generic] 319143-franken-says-he-would-have-told-trump-calling-warren-pocahontas-was-racist: Extracting information
ERROR: Unsupported URL: http://thehill.com/homenews/senate/319143-franken-says-he-would-have-told-trump-calling-warren-pocahontas-was-racist
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1741, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2526, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2515, in _XML
    parser.feed(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 342, column 21
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 696, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 369, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2589, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://thehill.com/homenews/senate/319143-franken-says-he-would-have-told-trump-calling-warren-pocahontas-was-racist
```
---

The HTML seems to have this form for the video:
```
<div class="inform-embed"
data-config-id="1"
data-type="VideoPlayer/Single"
data-tracking-group="91690"
data-playlist-id="13434"
data-video-id="31974114"
data-site-section="thehill2300_nws_pol_sec">
</div>
```

although after JS runs on the page the DOM has:

```
<div id="inform-player-container-1" style="width:100%;height:100%;" data-amp.version="AMP Premier - NDN v1.53.x.0004" class="akamai-flash akamai-player akamai-desktop akamai-vod akamai-medium-video akamai-ad-mode akamai-paused">
<div class="akamai-video akamai-layer">
<object type="application/x-shockwave-flash" id="flashObject1486927047763" name="flashObject1486927047763" data="http://launch.newsinc.com/167/js/lib/amp.premier/AkamaiPremierPlayer.swf" style="visibility: visible;" class="akamai-media-element" height="100%" width="100%">
...
```

**Comment by johnhawkinson** [comment]
Here's another `inform-embed` video on a different site: http://observer.com/2017/02/donald-trump-administration-mike-flynn-russian-embassy/
