### ISSUE TITLE
Download song on Deezer

### ISSUE THREAD

**Issue by Rudloff** [rg3/youtube-dl#1211]
It would be nice to be able to download songs on Deezer (e.g. http://www.deezer.com/fr/track/2422929).

**Comment by dinamic** [comment]
I think this is working now. You have to dump your cookies properly, otherwise you will get only the 30 second version.

Please, consider closing the issue.

**Comment by Rudloff** [comment]
The extractor does not seem to be triggered:
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'https://www.deezer.com/track/2422929', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.01
[debug] Python version 2.7.6 - Linux-3.13.0-77-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.18-6, avprobe 9.18-6, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 2422929: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 2422929: Downloading webpage
[generic] 2422929: Extracting information
ERROR: Unsupported URL: https://www.deezer.com/track/2422929
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 1289, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/compat.py", line 248, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=etree.TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/compat.py", line 237, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: undefined entity: line 5, column 27
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 666, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 313, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 1919, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.deezer.com/track/2422929
```

**Comment by dinamic** [comment]
It works only for playlists currently. You can create a playlist with the song you would like to download.

**Comment by Rudloff** [comment]
Strangely, it now downloads a random JS file:
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'https://www.deezer.com/track/2422929', u'--get-url', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.04.06
[debug] Python version 2.7.9 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.4
[debug] exe versions: avconv 11.6-6, avprobe 11.6-6, rtmpdump 2.4
[debug] Proxy map: {}
WARNING: Falling back on generic information extractor.
https://cdns-files.dzcdn.net/cache/js/profile-14b9280e2c5f8c84b940f74ea16be676.js
```

**Comment by Rudloff** [comment]
The URL does not work anymore.

**Comment by dinamic** [comment]
@Rudloff, I was unable to respond on time.

I just updated to the last version of youtube-dl and downloading does not work still.

Here's some output:

```
# youtube-dl http://www.deezer.com/track/96213206

[generic] 96213206: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 96213206: Downloading webpage
[generic] 96213206: Extracting information
[generic] player?html5player=1&autoplay=1&playlist=0&width=504&height=504&format=square&type=tracks&id=96213206: Requesting header
WARNING: Falling back on generic information extractor.
[generic] player?html5player=1&autoplay=1&playlist=0&width=504&height=504&format=square&type=tracks&id=96213206: Downloading webpage
[generic] player?html5player=1&autoplay=1&playlist=0&width=504&height=504&format=square&type=tracks&id=96213206: Extracting information
ERROR: Unsupported URL: https://www.deezer.com/plugins/player?html5player=1&autoplay=1&playlist=0&width=504&height=504&format=square&type=tracks&id=96213206
```

**Comment by dinamic** [comment]
@Rudloff, should this issue remain closed, I shall open a new one to have this feature supported.

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/10049

https://github.com/ytdl-org/youtube-dl/issues/1211
https://github.com/ytdl-org/youtube-dl/issues/16412
https://github.com/ytdl-org/youtube-dl/issues/24211
https://github.com/ytdl-org/youtube-dl/pull/22074
