### ISSUE TITLE
[nick.com] ERROR: nick.com returned error: not_found

### ISSUE THREAD

**Issue by RuneMagle** [rg3/youtube-dl#12113]
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.11**
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other
---
```
C:\Users\Desktop\youtube-dl>youtube-dl.exe -f best --all-subs http://www.nick.com/henry-danger/videos/nickelodeon-s-not-so-valentine-s-special-full-episode/ -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'best', '--all-subs', 'http://www.nick.com/henry-danger/videos/nickelodeon-s-not-so-valentine-s-special-full-episode/', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.02.11
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-82833-gedb4f5d, ffprobe N-82833-gedb4f5d, rtmpdump 2.3
[debug] Proxy map: {}
[nick.com] nickelodeon-s-not-so-valentine-s-special-full-episode: Downloading webpage
[nick.com] 5694bfcc-de12-11e6-bfd4-0026b9414f30: Downloading info
[nick.com] e7979cae-2f3b-49c2-b93f-fb3254cf4f22: Extracting information
[nick.com] e7979cae-2f3b-49c2-b93f-fb3254cf4f22: Downloading video urls
[nick.com] e7979cae-2f3b-49c2-b93f-fb3254cf4f22: Downloading m3u8 information
[nick.com] 73eeb452-f8a7-4979-b24e-0a1fbc1cf045: Extracting information
[nick.com] 73eeb452-f8a7-4979-b24e-0a1fbc1cf045: Downloading video urls
[nick.com] 73eeb452-f8a7-4979-b24e-0a1fbc1cf045: Downloading m3u8 information
[nick.com] b0f71472-aa9d-4b13-88e7-66c160631a12: Extracting information
[nick.com] b0f71472-aa9d-4b13-88e7-66c160631a12: Downloading video urls
[nick.com] b0f71472-aa9d-4b13-88e7-66c160631a12: Downloading m3u8 information
[nick.com] 0f72e4e9-2f62-494b-9f3b-8b937c0085fb: Extracting information
[nick.com] 0f72e4e9-2f62-494b-9f3b-8b937c0085fb: Downloading video urls
[nick.com] 0f72e4e9-2f62-494b-9f3b-8b937c0085fb: Downloading m3u8 information
[nick.com] a5f8ff80-3c0b-4971-aa47-807c28b38e2b: Extracting information
[nick.com] a5f8ff80-3c0b-4971-aa47-807c28b38e2b: Downloading video urls
[nick.com] a5f8ff80-3c0b-4971-aa47-807c28b38e2b: Downloading m3u8 information
[nick.com] bfe38083-124a-4f0f-a749-3b6d65d917bb: Extracting information
[nick.com] bfe38083-124a-4f0f-a749-3b6d65d917bb: Downloading video urls
ERROR: nick.com returned error: not_found -
      Sorry, this video is not found or no longer available due to date or rights restrictions.

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9b6x_5wr\build\youtube_dl\YoutubeDL.py", line 696, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9b6x_5wr\build\youtube_dl\extractor\common.py", line 369, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9b6x_5wr\build\youtube_dl\extractor\mtv.py", line 264, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9b6x_5wr\build\youtube_dl\extractor\mtv.py", line 198, in _get_videos_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9b6x_5wr\build\youtube_dl\extractor\mtv.py", line 209, in _get_videos_info_from_url
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9b6x_5wr\build\youtube_dl\extractor\mtv.py", line 209, in <listcomp>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9b6x_5wr\build\youtube_dl\extractor\mtv.py", line 145, in _get_video_info
youtube_dl.utils.ExtractorError: nick.com returned error: not_found -
      Sorry, this video is not found or no longer available due to date or rights restrictions.
...
<end of log>
```

---
- Single video: http://www.nick.com/henry-danger/videos/nickelodeon-s-not-so-valentine-s-special-full-episode/

---

### Description of my issue

Hi, I cannot download the new Nickelodeon Special. I don't know why, but I can download everything else just fine. I really want this special, can somebody fix this?

**Comment by RuneMagle** [comment]
NOTE: The video works fine on the website. I also just grabbed this link myself, it's the one youtube-dl usually gets `https://cp479184-vh.akamaihd.net/i/mtvnorigin/gsp.alias/mediabus/kids.com/2017/02/09/11/46/14/b1cae3b21a524c9780cabf90ab30cac8/1568730/vPn88BzH4k_HDNSZ689A1_1568730_7147669_,384x216_278,512x288_498,640x360_1028,768x432_1528,960x540_2128,1280x720_3128,1920x1080_5128,.mp4.csmil/index_6_av.m3u8?null=0&id=AgCt0ETdrc0JTvR8oVjJLFZ9ylLDl4aU2CJJLmq4R+o6Y78DJhCbAiw6cbuHDL59O222b9HCL%2f%2fo+Q%3d%3d&hdntl=exp=1487064692~acl=%2fi%2fmtvnorigin%2fgsp.alias%2fmediabus%2fkids.com%2f2017%2f02%2f09%2f11%2f46%2f14%2fb1cae3b21a524c9780cabf90ab30cac8%2f1568730%2fvPn88BzH4k_HDNSZ689A1_1568730_7147669_,384x216_278,512x288_498,640x360_1028,768x432_1528,960x540_2128,1280x720_3128,1920x1080_5128,.mp4.csmil%2f*~data=hdntl~hmac=ceb18a455298f005fc39f8d6303b0380b792adfd920787b94161203a0d64ecd5`

When I tried that in youtube-dl, it said something else:
`youtube-dl.exe -f best https://cp479184-vh.akamaihd.net/i/mtvnorigin/gsp.alias/mediabus/kids.com/2017/02/09/11/46/14/b1cae3b21a524c9780cabf90ab30cac8/1568730/vPn88BzH4k_HDNSZ689A1_1568730_7147669_,384x216_278,512x288_498,640x360_1028,768x432_1528,960x540_2128,1280x720_3128,1920x1080_5128,.mp4.csmil/index_6_av.m3u8?null=0&id=AgCt0ETdrc0JTvR8oVjJLFZ9ylLDl4aU2CJJLmq4R+o6Y78DJhCbAiw6cbuHDL59O222b9HCL%2f%2fo+Q%3d%3d&hdntl=exp=1487064692~acl=%2fi%2fmtvnorigin%2fgsp.alias%2fmediabus%2fkids.com%2f2017%2f02%2f09%2f11%2f46%2f14%2fb1cae3b21a524c9780cabf90ab30cac8%2f1568730%2fvPn88BzH4k_HDNSZ689A1_1568730_7147669_,384x216_278,512x288_498,640x360_1028,768x432_1528,960x540_2128,1280x720_3128,1920x1080_5128,.mp4.csmil%2f*~data=hdntl~hmac=ceb18a455298f005fc39f8d6303b0380b792adfd920787b94161203a0d64ecd5 -v
[generic] index_6_av: Requesting header
WARNING: Could not send HEAD request to https://cp479184-vh.akamaihd.net/i/mtvnorigin/gsp.alias/mediabus/kids.com/2017/02/09/11/46/14/b1cae3b21a524c9780cabf90ab30cac8/1568730/vPn88BzH4k_HDNSZ689A1_1568730_7147669_,384x216_278,512x288_498,640x360_1028,768x432_1528,960x540_2128,1280x720_3128,1920x1080_5128,.mp4.csmil/index_6_av.m3u8?null=0: HTTP Error 405: Method Not Allowed
[generic] index_6_av: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
'id' is not recognized as an internal or external command,
operable program or batch file.
'hdntl' is not recognized as an internal or external command,
operable program or batch file.`

**Comment by RuneMagle** [comment]
Seems like it's working now. Must have been Nick doing something.

`C:\Users\rumag\Desktop\youtube-dl>youtube-dl.exe -f best --all-subs http://www.nick.com/the-thundermans/videos/the-thundermans-411-clip/ -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'best', '--all-subs', 'http://www.nick.com/the-thundermans/videos/the-thundermans-411-clip/', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.02.14
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-82833-gedb4f5d, ffprobe N-82833-gedb4f5d, rtmpdump 2.3
[debug] Proxy map: {}
[nick.com] the-thundermans-411-clip: Downloading webpage
[nick.com] b9781956-189c-4c00-b85b-6989385f3dac: Downloading info
[nick.com] b9781956-189c-4c00-b85b-6989385f3dac: Extracting information
[nick.com] b9781956-189c-4c00-b85b-6989385f3dac: Downloading video urls
[nick.com] b9781956-189c-4c00-b85b-6989385f3dac: Downloading m3u8 information
[download] Downloading playlist: The Thundermans: "Back to Evil"
[nick.com] playlist The Thundermans: "Back to Evil": Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[info] Writing video subtitles to: The Thundermans - 'Back to Evil'-b9781956-189c-4c00-b85b-6989385f3dac.en.vtt
[debug] Invoking downloader on 'https://cp479184-vh.akamaihd.net/i/mtvnorigin/gsp.alias/mediabus/kids.com/2017/02/13/10/53/05/b5f6d68e8f344b069308c05d97bff957/1568192/F1WixYjuTW_7142688_1568192_20170213105305392_,384x216_278,512x288_498,640x360_1028,768x432_1528,960x540_2128,1280x720_3128,1920x1080_5128,.mp4.csmil/index_6_av.m3u8?null=0&id=AgAFZzggUEdSjRvjolh1l3cRSLZ59PWicS1p%2fHmHPgp8Cr1HNz2QDtCu0V%2fYuzhNG1YB6ZuK2IxbmA%3d%3d&hdntl=exp=1487156379~acl=%2fi%2fmtvnorigin%2fgsp.alias%2fmediabus%2fkids.com%2f2017%2f02%2f13%2f10%2f53%2f05%2fb5f6d68e8f344b069308c05d97bff957%2f1568192%2fF1WixYjuTW_7142688_1568192_20170213105305392_,384x216_278,512x288_498,640x360_1028,768x432_1528,960x540_2128,1280x720_3128,1920x1080_5128,.mp4.csmil%2f*~data=hdntl~hmac=7a293777db8a57e9791a5bfe339192bc9530d09ef7ca7e11296f8eeff14f656e'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 11
[download] Destination: The Thundermans - 'Back to Evil'-b9781956-189c-4c00-b85b-6989385f3dac.mp4
[download] 100% of 36.47MiB in 00:13
[debug] ffmpeg command line: ffprobe -show_streams 'file:The Thundermans - '"'"'Back to Evil'"'"'-b9781956-189c-4c00-b85b-6989385f3dac.mp4'
[ffmpeg] Fixing malformated aac bitstream in "The Thundermans - 'Back to Evil'-b9781956-189c-4c00-b85b-6989385f3dac.mp4"
[debug] ffmpeg command line: ffmpeg -y -i 'file:The Thundermans - '"'"'Back to Evil'"'"'-b9781956-189c-4c00-b85b-6989385f3dac.mp4' -c copy -f mp4 -bsf:a aac_adtstoasc 'file:The Thundermans - '"'"'Back to Evil'"'"'-b9781956-189c-4c00-b85b-6989385f3dac.temp.mp4'
[download] Finished downloading playlist: The Thundermans: "Back to Evil"

C:\Users\rumag\Desktop\youtube-dl>youtube-dl.exe -f best http://www.nick.com/mash-ups/videos/nickelodeon-s-not-so-valentine-s-special-full-episode/ -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'best', 'http://www.nick.com/mash-ups/videos/nickelodeon-s-not-so-valentine-s-special-full-episode/', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.02.14
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-82833-gedb4f5d, ffprobe N-82833-gedb4f5d, rtmpdump 2.3
[debug] Proxy map: {}
[nick.com] nickelodeon-s-not-so-valentine-s-special-full-episode: Downloading webpage
[nick.com] 5694bfcc-de12-11e6-bfd4-0026b9414f30: Downloading info
[nick.com] e7979cae-2f3b-49c2-b93f-fb3254cf4f22: Extracting information
[nick.com] e7979cae-2f3b-49c2-b93f-fb3254cf4f22: Downloading video urls
[nick.com] e7979cae-2f3b-49c2-b93f-fb3254cf4f22: Downloading m3u8 information
[nick.com] 73eeb452-f8a7-4979-b24e-0a1fbc1cf045: Extracting information
[nick.com] 73eeb452-f8a7-4979-b24e-0a1fbc1cf045: Downloading video urls
[nick.com] 73eeb452-f8a7-4979-b24e-0a1fbc1cf045: Downloading m3u8 information
[nick.com] b0f71472-aa9d-4b13-88e7-66c160631a12: Extracting information
[nick.com] b0f71472-aa9d-4b13-88e7-66c160631a12: Downloading video urls
[nick.com] b0f71472-aa9d-4b13-88e7-66c160631a12: Downloading m3u8 information
[nick.com] 0f72e4e9-2f62-494b-9f3b-8b937c0085fb: Extracting information
[nick.com] 0f72e4e9-2f62-494b-9f3b-8b937c0085fb: Downloading video urls
[nick.com] 0f72e4e9-2f62-494b-9f3b-8b937c0085fb: Downloading m3u8 information
[nick.com] a5f8ff80-3c0b-4971-aa47-807c28b38e2b: Extracting information
[nick.com] a5f8ff80-3c0b-4971-aa47-807c28b38e2b: Downloading video urls
[nick.com] a5f8ff80-3c0b-4971-aa47-807c28b38e2b: Downloading m3u8 information
[nick.com] bfe38083-124a-4f0f-a749-3b6d65d917bb: Extracting information
[nick.com] bfe38083-124a-4f0f-a749-3b6d65d917bb: Downloading video urls
[nick.com] bfe38083-124a-4f0f-a749-3b6d65d917bb: Downloading m3u8 information
[download] Downloading playlist: Nickelodeon’s Not So Valentine’s Special : "Nickelodeon’s Not So Valentine’s Special "
[nick.com] playlist Nickelodeon’s Not So Valentine’s Special : "Nickelodeon’s Not So Valentine’s Special ": Collected 6 video ids (downloading 6 of them)
[download] Downloading video 1 of 6
[debug] Invoking downloader on 'https://cp479184-vh.akamaihd.net/i/mtvnorigin/gsp.alias/mediabus/kids.com/2017/02/09/11/46/14/b1cae3b21a524c9780cabf90ab30cac8/1568730/vPn88BzH4k_HDNSZ689A1_1568730_7147669_,384x216_278,512x288_498,640x360_1028,768x432_1528,960x540_2128,1280x720_3128,1920x1080_5128,.mp4.csmil/index_6_av.m3u8?null=0&id=AgAFZzggUEdSjaHlolj6o6Dxm73+Hab3z7C%2fn3MdjZFOdNmv7e5kNgGSHT9CR2h3KJQHJo076iviAA%3d%3d&hdntl=exp=1487157025~acl=%2fi%2fmtvnorigin%2fgsp.alias%2fmediabus%2fkids.com%2f2017%2f02%2f09%2f11%2f46%2f14%2fb1cae3b21a524c9780cabf90ab30cac8%2f1568730%2fvPn88BzH4k_HDNSZ689A1_1568730_7147669_,384x216_278,512x288_498,640x360_1028,768x432_1528,960x540_2128,1280x720_3128,1920x1080_5128,.mp4.csmil%2f*~data=hdntl~hmac=01b9a26f9fe19776534f9b7ac8bc72dd1beeb5384a7154e69d9952e8667a4dd9'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 139
[download] Destination: Nickelodeon's Not So Valentine's Special  - 'Nickelodeon's Not So Valentine's Special ' S1-e7979cae-2f3b-49c2-b93f-fb3254cf4f22.mp4
[download] 100% of 513.69MiB in 01:46`
