### ISSUE TITLE
youtube_dl.utils.ExtractorError: Cannot identify player '/yts/jsbin/player-en_US-vfl8LqiZp/base.js'; please report this issue on https://yt-dl.org/bug

### ISSUE THREAD

**Issue by valuial** [rg3/youtube-dl#12136]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.02.14*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.14**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
~ $ youtube-dl --verbose -F http://www.youtube.com/watch?v=-0VHxAA4PXw
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '-F', 'http://www.youtube.com/watch?v=-0VHxAA4PXw']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.07.07
[debug] Python version 3.4.5 - Linux-4.9.2-gentoo-aoi-nvidia-x86_64-Intel-R-_Core-TM-_i5-2310_CPU_@_2.90GHz-with-gentoo-2.3
[debug] exe versions: ffmpeg 2.8.10, ffprobe 2.8.10, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] -0VHxAA4PXw: Downloading webpage
[youtube] -0VHxAA4PXw: Downloading video info webpage
[youtube] -0VHxAA4PXw: Extracting video information
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {22} signature length 42.40, html5 player None
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/home/vee/.bin/youtube-dl/youtube_dl/extractor/youtube.py", line 676, in _decrypt_signature
    video_id, player_url, s
  File "/home/vee/.bin/youtube-dl/youtube_dl/extractor/youtube.py", line 568, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
youtube_dl.utils.ExtractorError: Cannot identify player '/yts/jsbin/player-en_US-vfl8LqiZp/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Cannot identify player '/yts/jsbin/player-en_US-vfl8LqiZp/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/vee/.bin/youtube-dl/youtube_dl/extractor/youtube.py", line 676, in _decrypt_signature
    video_id, player_url, s
  File "/home/vee/.bin/youtube-dl/youtube_dl/extractor/youtube.py", line 568, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
youtube_dl.utils.ExtractorError: Cannot identify player '/yts/jsbin/player-en_US-vfl8LqiZp/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/vee/.bin/youtube-dl/youtube_dl/extractor/youtube.py", line 676, in _decrypt_signature
    video_id, player_url, s
  File "/home/vee/.bin/youtube-dl/youtube_dl/extractor/youtube.py", line 568, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
youtube_dl.utils.ExtractorError: Cannot identify player '/yts/jsbin/player-en_US-vfl8LqiZp/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vee/.bin/youtube-dl/youtube_dl/YoutubeDL.py", line 654, in extract_info
    ie_result = ie.extract(url)
  File "/home/vee/.bin/youtube-dl/youtube_dl/extractor/common.py", line 273, in extract
    return self._real_extract(url)
  File "/home/vee/.bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1149, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/home/vee/.bin/youtube-dl/youtube_dl/extractor/youtube.py", line 686, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/home/vee/.bin/youtube-dl/youtube_dl/extractor/youtube.py", line 676, in _decrypt_signature
    video_id, player_url, s
  File "/home/vee/.bin/youtube-dl/youtube_dl/extractor/youtube.py", line 568, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
youtube_dl.utils.ExtractorError: Cannot identify player '/yts/jsbin/player-en_US-vfl8LqiZp/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Cannot identify player '/yts/jsbin/player-en_US-vfl8LqiZp/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

---

---

### Description of your *issue*, suggested solution and other information

Just trying to download from youtube (in the example using -F to get the list of codecs first) but youtube seems to have a new/unknown player that youtube-dl does not recognize. Posting this issue, because youtube-dl asked me to.

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [this FAQ entry](https://yt-dl.org/update) if you have troubles updating.
