### ISSUE TITLE
Don't work YouTube/Pornhub

### ISSUE THREAD

**Issue by rhazor** [rg3/youtube-dl#12135]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.14**
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Bug report (encountered problems with youtube-dl)

```
$ youtube-dl --version
2017.02.14
```

```
$ youtube-dl https://www.youtube.com/watch?v=6aPzjhXAUR8
[youtube] 6aPzjhXAUR8: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)> (caused by URLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)'),))
```

```
$ youtube-dl http://www.pornhub.com/view_video.php?viewkey=ph56b4268d3cfd6
[PornHub] ph56b4268d3cfd6: Downloading webpage
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpqajgst4a\build\youtube_dl\__init__.py", line 452, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpqajgst4a\build\youtube_dl\__init__.py", line 442, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpqajgst4a\build\youtube_dl\YoutubeDL.py", line 1796, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpqajgst4a\build\youtube_dl\YoutubeDL.py", line 707, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpqajgst4a\build\youtube_dl\YoutubeDL.py", line 753, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpqajgst4a\build\youtube_dl\YoutubeDL.py", line 1377, in process_video_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpqajgst4a\build\youtube_dl\YoutubeDL.py", line 1232, in _calc_headers
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpqajgst4a\build\youtube_dl\YoutubeDL.py", line 1239, in _calc_cookies
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpqajgst4a\build\youtube_dl\utils.py", line 537, in sanitized_Request
  File "C:\Python\Python34\lib\urllib\request.py", line 267, in __init__
  File "C:\Python\Python34\lib\urllib\request.py", line 293, in full_url
  File "C:\Python\Python34\lib\urllib\request.py", line 322, in _parse
ValueError: unknown url type: '/*b7d613353d72035229ff946bee9*/cce09a14d4a6d/*d1fd28691994e*/e280c0b24188374fbf27/*a6c6752011bcad12dcd1f8*/ce6a786af/*d78f210f635d92*/a5f879e3e5/*cdea67f*/fcd6/*fcd6*/d78f210f635d92/*b0471227e7c2da6ddcbbec9f*/d69b51ff0e1aae6c601a32ecf0d/*ce6a786af*/d6cb9540695b028d9b7dc97c4298e219/*fcd6*/c1ac/*af96*/b0471227e7c2da6ddcbbec9f/*d1fd28691994e*/ee9115/*fcd6*/af96/*a5f879e3e5*/cdea67f/*af96*/ed5293da835a3f9db9b68e5c0f0d/*cdea67f*/d1fd28691994e/*a6c6752011bcad12dcd1f8*/e61c5/*bc6*/bc6/*e268c81e0da2d07cc8e85847*/e6b27/*e6b27*/f4dc0a4c16cfc627/*a5f879e3e5*/b7d613353d72035229ff946bee9/*b7d613353d72035229ff946bee9*/e268c81e0da2d07cc8e85847/*e61c5*/d709757b39fc31a3/*f4dc0a4c16cfc627*/a6c6752011bcad12dcd1f8'
```

Win10 x64 Python 2.7.12 (64-bit)

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl/issues/11573#issuecomment-269896421

**Comment by rhazor** [comment]
What about second error.

**Comment by dstftw** [comment]
Duplicate.
