### ISSUE TITLE
facebook video: Cannot parse data; 

### ISSUE THREAD

**Issue by sant527** [rg3/youtube-dl#12132]
```
 % youtube-dl -v -F "https://www.facebook.com/BBCWalesNews/videos/1269641106435307/"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', '-F', 'https://www.facebook.com/BBCWalesNews/videos/1269641106435307/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.12.22
[debug] Python version 3.5.1 - Linux-4.6.2-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 3.0.2, ffprobe 3.0.2, rtmpdump 2.4
[debug] Proxy map: {}
[facebook] 1269641106435307: Downloading webpage
[facebook] 1269641106435307: Downloading webpage
ERROR: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 358, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/facebook.py", line 343, in _real_extract
    video_id, fatal_if_no_video=True)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/facebook.py", line 266, in _extract_from_url
    raise ExtractorError('Cannot parse data')
youtube_dl.utils.ExtractorError: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
