### ISSUE TITLE
https://youtu.be/KQ5W0qoQhJA

### ISSUE THREAD

**Issue by mishop** [rg3/youtube-dl#12147]
youtube-dl -F https://youtu.be/KQ5W0qoQhJA
[youtube] KQ5W0qoQhJA: Downloading webpage
[youtube] KQ5W0qoQhJA: Downloading video info webpage
[youtube] KQ5W0qoQhJA: Extracting video information
[youtube] KQ5W0qoQhJA: Downloading js player en_US-vfl8LqiZp
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1005, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 919, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 517, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 424, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 404, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 2000, in urlopen
    req = sanitized_Request(req)
  File "/usr/lib/python3/dist-packages/youtube_dl/utils.py", line 513, in sanitized_Request
    return compat_urllib_request.Request(sanitize_url(url), *args, **kwargs)
  File "/usr/lib/python3.5/urllib/request.py", line 269, in __init__
    self.full_url = url
  File "/usr/lib/python3.5/urllib/request.py", line 295, in full_url
    self._parse()
  File "/usr/lib/python3.5/urllib/request.py", line 324, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/yts/jsbin/player-en_US-vfl8LqiZp/base.js'
 (caused by ValueError("unknown url type: '/yts/jsbin/player-en_US-vfl8LqiZp/base.js'",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
zsh: exit 1     youtube-dl -F https://youtu.be/KQ5W0qoQhJA

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [this FAQ entry](https://yt-dl.org/update) if you have troubles updating.
