### ISSUE TITLE
[watchdisneychannel.go.com] ERROR: Unable to extract post url

### ISSUE THREAD

**Issue by RuneMagle** [rg3/youtube-dl#12165]
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.16**
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
```
C:\Users\rumag\Desktop\youtube-dl>youtube-dl.exe -f best --all-subs --username something@gmail.com --password july1987 --ap-username something@gmail.com --ap-password july1987 --ap-mso DTV http://watchdisneychannel.go.com/liv-and-maddie/video/vdka3684875/04/11-tiny-housearooney -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'best', '--all-subs', '--username', 'PRIVATE', '--password', 'PRIVATE', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '--ap-mso', 'DTV', 'http://watchdisneychannel.go.com/liv-and-maddie/video/vdka3684875/04/11-tiny-housearooney', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.02.16
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-82833-gedb4f5d, ffprobe N-82833-gedb4f5d, rtmpdump 2.3
[debug] Proxy map: {}
[Go] 3678263: Downloading JSON metadata
[Go] 3678263: Downloading Provider Redirect Page
[Go] 3678263: Downloading Provider Login Page
[Go] 3678263: Logging in
ERROR: Unable to extract post url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpnd0pf5s_\build\youtube_dl\YoutubeDL.py", line 696, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpnd0pf5s_\build\youtube_dl\extractor\common.py", line 369, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpnd0pf5s_\build\youtube_dl\extractor\go.py", line 93, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpnd0pf5s_\build\youtube_dl\extractor\adobepass.py", line 1418, in _extract_mvpd_auth
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpnd0pf5s_\build\youtube_dl\extractor\adobepass.py", line 1322, in post_form
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpnd0pf5s_\build\youtube_dl\extractor\common.py", line 681, in _html_search_regex
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpnd0pf5s_\build\youtube_dl\extractor\common.py", line 672, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract post url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://watchdisneychannel.go.com/liv-and-maddie/video/vdka3684875/04/11-tiny-housearooney

### Description of my issue:

This worked like a week ago, and now I can't get the videos down. Please fix this! :)

**Comment by StevenDTX** [comment]
Works just fine for me with DTV credentials.  Try using the command line I used.


```
E:\>youtube-dl.exe --restrict-filenames --continue --no-check-certificate --verbose --ap-mso DTV --ap-username <username> --ap-password <password> -o Disney.Test.mp4 "http://watchdisneychannel.go.com/liv-and-maddie/video/vdka3684875/04/11-tiny-housearooney"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--restrict-filenames', '--continue', '--no-check-certificate', '--verbose', '--ap-mso', 'DTV', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '-o', 'Disney.Test.mp4', 'http://watchdisneychannel.go.com/liv-and-maddie/video/vdka3684875/04/11-tiny-housearooney']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.02.16
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-82966-g6993bb4, ffprobe N-72383-g7206b94, rtmpdump 2.4
[debug] Proxy map: {}
[Go] 3684875: Downloading JSON metadata
[Go] 3684875: Downloading Provider Redirect Page
[Go] 3684875: Downloading Provider Login Page
[Go] 3684875: Logging in
[Go] 3684875: Confirming Login
[Go] 3684875: Retrieving Session
[Go] 3684875: Retrieving Authorization Token
[Go] 3684875: Retrieving Media Token
[Go] 3684875: Downloading JSON metadata
[Go] 3684875: Downloading m3u8 information
[debug] Invoking downloader on 'http://content-auso1.uplynk.com/0ba2561afda148b686f1b0388c5a1086/j.m3u8?exp=1487351942&ct=a&oid=21885d134fa441488df8e1d7acee8c66&eid=10085787&iph=d6f86aa9c907b9fd9e516da8fededd6f334288018690a5fb7968b452b27fa498&rays=jihgfedcb&euid=AC2DC00C-075D-4A2D-A67F-B5E38F8C650E_000_1_001_lf_03-06-00_NA&cdn=ec&stgcfg=datg&pp2ip=0&sig=ff66127e9656741fb28c28f1ef0b85e0b677fd0b18eee0b9c41af2b1b9e94886&pbs=5c7ae63ed3eb4540ac3fd74f24c9c874'
[download] Destination: Disney.Test.mp4
[debug] ffmpeg command line: ffmpeg -y -headers 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/47.0 (Chrome)
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Encoding: gzip, deflate
Accept-Language: en-us,en;q=0.5
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
' -i 'http://content-auso1.uplynk.com/0ba2561afda148b686f1b0388c5a1086/j.m3u8?exp=1487351942&ct=a&oid=21885d134fa441488df8e1d7acee8c66&eid=10085787&iph=d6f86aa9c907b9fd9e516da8fededd6f334288018690a5fb7968b452b27fa498&rays=jihgfedcb&euid=AC2DC00C-075D-4A2D-A67F-B5E38F8C650E_000_1_001_lf_03-06-00_NA&cdn=ec&stgcfg=datg&pp2ip=0&sig=ff66127e9656741fb28c28f1ef0b85e0b677fd0b18eee0b9c41af2b1b9e94886&pbs=5c7ae63ed3eb4540ac3fd74f24c9c874' -c copy -f mp4 -bsf:a aac_adtstoasc file:Disney.Test.mp4.part
ffmpeg version N-82966-g6993bb4 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 5.4.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-dxva2 --enable-libmfx --enable-nvenc --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-decklink --enable-zlib
  libavutil      55. 43.100 / 55. 43.100
  libavcodec     57. 70.100 / 57. 70.100
  libavformat    57. 61.100 / 57. 61.100
  libavdevice    57.  2.100 / 57.  2.100
  libavfilter     6. 68.100 /  6. 68.100
  libswscale      4.  3.101 /  4.  3.101
  libswresample   2.  4.100 /  2.  4.100
  libpostproc    54.  2.100 / 54.  2.100
[aac @ 00000000028194e0] element type mismatch 1 != 0
Input #0, hls,applehttp, from 'http://content-auso1.uplynk.com/0ba2561afda148b686f1b0388c5a1086/j.m3u8?exp=1487351942&ct=a&oid=21885d134fa441488df8e1d7acee8c66&eid=10085787&iph=d6f86aa9c907b9fd9e516da8fededd6f334288018690a5fb7968b452b27fa498&rays=jihgfedcb&euid=AC2DC00C-075D-4A2D-A67F-B5E38F8C650E_000_1_001_lf_03-06-00_NA&cdn=ec&stgcfg=datg&pp2ip=0&sig=ff66127e9656741fb28c28f1ef0b85e0b677fd0b18eee0b9c41af2b1b9e94886&pbs=5c7ae63ed3eb4540ac3fd74f24c9c874':
  Duration: 00:23:17.91, start: 0.000000, bitrate: 0 kb/s
  Program 0
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Audio: aac (HE-AAC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p, 1280x720, 23.98 tbr, 90k tbn, 48 tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:2: Data: timed_id3 (ID3  / 0x20334449)
    Metadata:
      variant_bitrate : 0
Output #0, mp4, to 'file:Disney.Test.mp4.part':
  Metadata:
    encoder         : Lavf57.61.100
    Stream #0:0: Video: h264 (High) ([33][0][0][0] / 0x0021), yuv420p, 1280x720, q=2-31, 23.98 tbr, 90k tbn, 90k tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (HE-AAC) ([64][0][0][0] / 0x0040), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
Stream mapping:
  Stream #0:1 -> #0:0 (copy)
  Stream #0:0 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame= 1341 fps=139 q=-1.0 Lsize=   23606kB time=00:00:56.10 bitrate=3446.6kbits/s speed= 5.8x
video:22726kB audio:870kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.041056%
Exiting normally, received signal 2.

ERROR: Interrupted by user

```

**Comment by RuneMagle** [comment]
Thank you. Works now!
