### ISSUE TITLE
problem in openload download

### ISSUE THREAD

**Issue by mdoulabi** [rg3/youtube-dl#12167]
i change openload.py and make youtube-dl but this erorr :
youtube-dl -v https://openload.co/embed/j4TxUXWqVZc/xcite-king.james
Traceback (most recent call last):
File "/usr/lib64/python2.6/runpy.py", line 122, in _run_module_as_main
"main", fname, loader, pkg_name)
File "/usr/lib64/python2.6/runpy.py", line 34, in _run_code
exec code in run_globals
File "/usr/local/bin/youtube-dl/main.py", line 16, in
File "/usr/local/bin/youtube-dl/youtube_dl/init.py", line 43, in
File "/usr/local/bin/youtube-dl/youtube_dl/extractor/init.py", line 9, in
File "/usr/local/bin/youtube-dl/youtube_dl/extractor/extractors.py", line 54, in
File "/usr/local/bin/youtube-dl/youtube_dl/extractor/ard.py", line 7, in
File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 85, in
File "/usr/local/bin/youtube-dl/youtube_dl/extractor/openload.py", line 107
SyntaxError: 'return' outside function

why?

**Comment by dstftw** [comment]
Offtopic.
