### ISSUE TITLE
[MDR] Mediathek Audio not working

### ISSUE THREAD

**Issue by a-l-e-k** [rg3/youtube-dl#12169]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.17**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Bug report (encountered problems with youtube-dl)

- Single audio: http://www.mdr.de/kultur/videos-und-audios/audio-radio/operation-mindfuck-robert-wilson100.html
- Playlist: http://www.mdr.de/kultur/videos-und-audios/index.html

**description**
After recent changes on their site the download from MDR Radio is no longer working.

**log**
```
youtube-dl.exe -v http://www.mdr.de/kultur/videos-und-audios/audio-radio/operation-mindfuck-robert-wilson100.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://www.mdr.de/kultur/videos-und-audios/audio-radio/operation-mindfuck-robert-wilson100.html']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.02.17
[debug] Python version 3.4.4 - Windows-XP-5.1.2600-SP3
[debug] exe versions: ffmpeg N-67100-g6dc99fd, ffprobe N-67100-g6dc99fd, rtmpdump 2.4
[debug] Proxy map: {}
[generic] operation-mindfuck-robert-wilson100: Requesting header
WARNING: Falling back on generic information extractor.
[generic] operation-mindfuck-robert-wilson100: Downloading webpage
[generic] operation-mindfuck-robert-wilson100: Extracting information
ERROR: Unsupported URL: http://www.mdr.de/kultur/videos-und-audios/audio-radio/operation-mindfuck-robert-wilson100.html
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpqajgst4a\build\youtube_dl\YoutubeDL.py", line 696, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpqajgst4a\build\youtube_dl\extractor\common.py", line 369, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpqajgst4a\build\youtube_dl\extractor\generic.py", line 2579, in _real_extractyoutube_dl.utils.UnsupportedError: Unsupported URL: http://www.mdr.de/kultur/videos-und-audios/audio-radio/operation-mindfuck-robert-wilson100.html
<end of log>
```

**Comment by yan12125** [comment]
http://www.mdr.de/kultur/videos-und-audios/audio-radio/operation-mindfuck-robert-wilson100.html will be fixed in the next version. Playlists are not supported yet, though.
