### ISSUE TITLE
Add support for tune.pk

### ISSUE THREAD

**Issue by PannenkoekenNL** [rg3/youtube-dl#12197]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.17**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Site support request (request for adding support for a new site)

### Description of your *issue*, suggested solution and other information
Trying to download this video https://tune.pk/video/3188265/kaiketsu-incredible-zorori-episode-1-dragging-away-the-dragon-english-dub-1-of-2 results in this:

Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0y1qi6u7\build\youtube_dl\__init__.py", line 452, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0y1qi6u7\build\youtube_dl\__init__.py", line 442, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0y1qi6u7\build\youtube_dl\YoutubeDL.py", line 1796, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0y1qi6u7\build\youtube_dl\YoutubeDL.py", line 696, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0y1qi6u7\build\youtube_dl\extractor\common.py", line 370, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0y1qi6u7\build\youtube_dl\extractor\generic.py", line 2512, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0y1qi6u7\build\youtube_dl\extractor\common.py", line 2110, in _parse_jwplayer_data
TypeError: 'str' object does not support item assignment

**Comment by best-job** [comment]
Is there new in this issue ?!!
