### ISSUE TITLE
Unable to download from parliamentlive.tv

### ISSUE THREAD

**Issue by sitymarz** [rg3/youtube-dl#12206]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.02.17*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.17**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

...
C:\temp\youtubedl>youtube-dl -v http://www.parliamentlive.tv/Event/Index/4d2056a8-be31-4553-9ca8-ef32580b26a7
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://www.parliamentlive.tv/Event/Index/4d2056a8-be31-4553-9ca8-ef32580b26a7']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.02.17
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-71883-geb9fb50, ffprobe N-71883-geb9fb50
[debug] Proxy map: {}
[parliamentlive.tv] 4d2056a8-be31-4553-9ca8-ef32580b26a7: Downloading webpage
[parliamentlive.tv] 4d2056a8-be31-4553-9ca8-ef32580b26a7: Downloading JSON metadata
[Kaltura] 1_4zmq0hod: Downloading video info JSON
[Kaltura] 1_4zmq0hod: Downloading m3u8 information
[debug] Invoking downloader on 'http://cdnapi.kaltura.com/p/1756741/sp/175674100/playManifest/entryId/1_4zmq0hod/format/url/protocol/http/flavorId/1_ij44klfg'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0y1qi6u7\build\youtube_dl\YoutubeDL.py", line 1704, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0y1qi6u7\build\youtube_dl\YoutubeDL.py", line 1646, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0y1qi6u7\build\youtube_dl\downloader\common.py", line 353, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0y1qi6u7\build\youtube_dl\downloader\http.py", line 61, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0y1qi6u7\build\youtube_dl\YoutubeDL.py", line 2006, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 502, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 685, in http_error_302
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

http://www.parliamentlive.tv/Event/Index/4d2056a8-be31-4553-9ca8-ef32580b26a7

Unable to process link and receive an Error 403 error.

**Comment by goggle** [comment]
This seems to be a server-side issue.
You can use
´´´youtube-dl http://www.parliamentlive.tv/Event/Index/4d2056a8-be31-4553-9ca8-ef32580b26a7 -f hls-1169´´´
do download the mentioned video.

**Comment by yan12125** [comment]
@goggle is right. This is a server-side issue. mp4-1200 corresponds to the "High" quality on the webpage, and it's not available in browsers, either. On the other hand, mp4-250, which maps to "Low", downloads fine.

A more elegant approach is discussed in #3721. Before that's implemented you'll need to try available formats one by one.
