### ISSUE TITLE
Please add support for animation.filmarchives.jp

### ISSUE THREAD

**Issue by GeorgeHamp** [rg3/youtube-dl#12237]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.02.22*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.22**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
youtube-dl.exe -v http://animation.filmarchives.jp/works/play/5432
[debug] System config: []
[debug] User config: ['-o', '%(title)s.%(ext)s', '--autonumber-size', '3', '--all-subs', '-r', '1M']
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://animation.filmarchives.jp/works/play/5432']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.02.22
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-71883-geb9fb50, ffprobe N-71883-geb9fb50, rtmpdump 2.3
[debug] Proxy map: {}
[generic] 5432: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 5432: Downloading webpage
[generic] 5432: Extracting information
ERROR: Unsupported URL: http://animation.filmarchives.jp/works/play/5432
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkf42q19b\build\youtube_dl\YoutubeDL.py", line 704, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkf42q19b\build\youtube_dl\extractor\common.py", line 427, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkf42q19b\build\youtube_dl\extractor\generic.py", line 2604, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: http://animation.filmarchives.jp/works/play/5432
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://animation.filmarchives.jp/works/play/5432
- Single video: http://animation.filmarchives.jp/works/playen/5432

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

**Comment by gurugurumaguru** [comment]
Sorry about double posting! I searched "film archive" and nothing came up. I done goofed and should have searched "filmarchives".
