### ISSUE TITLE
[noco.tv] Login problem

### ISSUE THREAD

**Issue by ianuxfr** [rg3/youtube-dl#12246]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.02.24*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.24**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

There seems to be a probleme with noco.tv login (API change?). I can download a freely available video without being logged, but when I log in there is an error (and so I can't download paid SVOD).

Without login:
```
$ youtube-dl -v https://noco.tv/emission/39664/nolife/le-point-sur-nolife/20-fevrier-2017
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://noco.tv/emission/39664/nolife/le-point-sur-nolife/20-fevrier-2017']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.02.24
[debug] Python version 2.7.12 - Linux-3.10.102-armv7l-with-glibc2.4
[debug] exe versions: ffmpeg 2.7.1
[debug] Proxy map: {}
[Noco] 39664: Downloading webpage
[Noco] 39664: Downloading video JSON
[Noco] 39664: Downloading show JSON
[Noco] 39664: Downloading user options JSON
[Noco] 39664: Downloading qualities JSON
[Noco] 39664: Downloading audio-fr_sub-none_TV video JSON
[Noco] 39664: Downloading audio-fr_sub-none_HQ video JSON
[Noco] 39664: Downloading audio-fr_sub-none_HD_720 video JSON
[Noco] 39664: Downloading audio-fr_sub-none_LQ video JSON
[debug] Invoking downloader on u'http://video.noco.tv/nol/0/d/PN_S17s08_notime08.mp4?st=R5-r4F5N2Se_ACAHxLfQXA&e=1487956387&u=0&d=0&videoname='
[download] Destination: Le point sur Nolife - 20 février 2017-39664.mp4
```
With login:
```
$ youtube-dl -u *** -p *** -v https://noco.tv/emission/39664/nolife/le-point-sur-nolife/20-fevrier-2017
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'-v', u'https://noco.tv/emission/39664/nolife/le-point-sur-nolife/20-fevrier-2017']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.02.24
[debug] Python version 2.7.12 - Linux-3.10.102-armv7l-with-glibc2.4
[debug] exe versions: ffmpeg 2.7.1
[debug] Proxy map: {}
[Noco] Logging in as ***
ERROR: None: Failed to parse JSON  (caused by ValueError('No JSON object could be decoded',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 660, in _parse_json
    return json.loads(json_string)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 761, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 426, in extract
    self.initialize()
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 384, in initialize
    self._real_initialize()
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/noco.py", line 65, in _real_initialize
    self._login()
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/noco.py", line 81, in _login
    login = self._download_json(request, None, 'Logging in as %s' % username)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 654, in _download_json
    json_string, video_id, transform_source=transform_source, fatal=fatal)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 664, in _parse_json
    raise ExtractorError(errmsg, cause=ve)
ExtractorError: None: Failed to parse JSON  (caused by ValueError('No JSON object could be decoded',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by dsferruzza** [comment]
I have the same issue.

Using the `--write-pages` flag, I got a `None_http_-_noco.tv_do.php.dump` file that contains:
```
APPEL INVALIDE
```
