### ISSUE TITLE
(YouTube) Error: Signature Extraction Failed 

### ISSUE THREAD

**Issue by fuzzewuzze** [rg3/youtube-dl#12244]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.02.24*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X ] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.24**

### Before submitting an *issue* make sure you have:
- [X ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
[debug] Encodings: locale cp1252, fs mbcs, out UTF-8, pref cp1252
[debug] youtube-dl version 2016.12.01
[debug] Python version 3.5.1 - Windows-10-10.0.14393-SP0
[debug] exe versions: ffmpeg N-83585-ga5c1c7a, ffprobe N-83585-ga5c1c7a
[debug] Proxy map: {}
[youtube] wPBbMbKSZrQ: Downloading webpage
[youtube] wPBbMbKSZrQ: Downloading video info webpage
[youtube] wPBbMbKSZrQ: Extracting video information
[youtube] {22} signature length 40.44, html5 player en_US-vflqOi6vK
[youtube] {43} signature length 40.44, html5 player en_US-vflqOi6vK
[youtube] {18} signature length 40.44, html5 player en_US-vflqOi6vK
[youtube] {36} signature length 40.44, html5 player en_US-vflqOi6vK
[youtube] {17} signature length 40.44, html5 player en_US-vflqOi6vK
[youtube] {137} signature length 40.44, html5 player en_US-vflqOi6vK
[youtube] {248} signature length 40.44, html5 player en_US-vflqOi6vK
[youtube] {136} signature length 40.44, html5 player en_US-vflqOi6vK
[youtube] {247} signature length 40.44, html5 player en_US-vflqOi6vK
[youtube] {135} signature length 40.44, html5 player en_US-vflqOi6vK
[youtube] {244} signature length 40.44, html5 player en_US-vflqOi6vK
[youtube] {134} signature length 40.44, html5 player en_US-vflqOi6vK
[youtube] {243} signature length 40.44, html5 player en_US-vflqOi6vK
[youtube] {133} signature length 40.44, html5 player en_US-vflqOi6vK
[youtube] {242} signature length 40.44, html5 player en_US-vflqOi6vK
[youtube] {160} signature length 40.44, html5 player en_US-vflqOi6vK
[youtube] {278} signature length 40.44, html5 player en_US-vflqOi6vK
[youtube] {140} signature length 40.44, html5 player en_US-vflqOi6vK
[youtube] {171} signature length 40.44, html5 player en_US-vflqOi6vK
[youtube] {249} signature length 40.44, html5 player en_US-vflqOi6vK
[youtube] {250} signature length 40.44, html5 player en_US-vflqOi6vK
[youtube] {251} signature length 38.44, html5 player en_US-vflqOi6vK
[youtube] wPBbMbKSZrQ: Downloading player /yts/jsbin/player-en_US-vflqOi6vK/base.js
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1005, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 919, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\common.py", line 517, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\common.py", line 424, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\common.py", line 404, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 2000, in urlopen
    req = sanitized_Request(req)
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\utils.py", line 513, in sanitized_Request
    return compat_urllib_request.Request(sanitize_url(url), *args, **kwargs)
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 268, in __init__
    self.full_url = url
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 294, in full_url
    self._parse()
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 323, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/yts/jsbin/player-en_US-vflqOi6vK/base.js'
 (caused by ValueError("unknown url type: '/yts/jsbin/player-en_US-vflqOi6vK/base.js'",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1005, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 919, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\common.py", line 517, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\common.py", line 424, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\common.py", line 404, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 2000, in urlopen
    req = sanitized_Request(req)
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\utils.py", line 513, in sanitized_Request
    return compat_urllib_request.Request(sanitize_url(url), *args, **kwargs)
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 268, in __init__
    self.full_url = url
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 294, in full_url
    self._parse()
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 323, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/yts/jsbin/player-en_US-vflqOi6vK/base.js'
Traceback (most recent call last):
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1005, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 919, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\common.py", line 517, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\common.py", line 424, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\common.py", line 404, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 2000, in urlopen
    req = sanitized_Request(req)
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\utils.py", line 513, in sanitized_Request
    return compat_urllib_request.Request(sanitize_url(url), *args, **kwargs)
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 268, in __init__
    self.full_url = url
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 294, in full_url
    self._parse()
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 323, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/yts/jsbin/player-en_US-vflqOi6vK/base.js'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\common.py", line 357, in extract
    return self._real_extract(url)
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1584, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1015, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1005, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 919, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\common.py", line 517, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\common.py", line 424, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\common.py", line 404, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 2000, in urlopen
    req = sanitized_Request(req)
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\utils.py", line 513, in sanitized_Request
    return compat_urllib_request.Request(sanitize_url(url), *args, **kwargs)
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 268, in __init__
    self.full_url = url
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 294, in full_url
    self._parse()
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 323, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/yts/jsbin/player-en_US-vflqOi6vK/base.js'
 (caused by ValueError("unknown url type: '/yts/jsbin/player-en_US-vflqOi6vK/base.js'",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1005, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 919, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\common.py", line 517, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\common.py", line 424, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\common.py", line 404, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 2000, in urlopen
    req = sanitized_Request(req)
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\utils.py", line 513, in sanitized_Request
    return compat_urllib_request.Request(sanitize_url(url), *args, **kwargs)
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 268, in __init__
    self.full_url = url
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 294, in full_url
    self._parse()
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 323, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/yts/jsbin/player-en_US-vflqOi6vK/base.js'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\common.py", line 357, in extract
    return self._real_extract(url)
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1584, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1015, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1005, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 919, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\common.py", line 517, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\common.py", line 424, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\common.py", line 404, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 2000, in urlopen
    req = sanitized_Request(req)
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\utils.py", line 513, in sanitized_Request
    return compat_urllib_request.Request(sanitize_url(url), *args, **kwargs)
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 268, in __init__
    self.full_url = url
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 294, in full_url
    self._parse()
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 323, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/yts/jsbin/player-en_US-vflqOi6vK/base.js'
 (caused by ValueError("unknown url type: '/yts/jsbin/player-en_US-vflqOi6vK/base.js'",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:/Source/MusicTriviaBot/main.py", line 54, in on_message
    info = ydl.extract_info('https://www.youtube.com/watch?v=wPBbMbKSZrQ',download=True)
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 709, in extract_info
    self.report_error(compat_str(e), e.format_traceback())
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 568, in report_error
    self.trouble(error_message, tb)
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 538, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1005, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 919, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\common.py", line 517, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\common.py", line 424, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\common.py", line 404, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 2000, in urlopen
    req = sanitized_Request(req)
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\utils.py", line 513, in sanitized_Request
    return compat_urllib_request.Request(sanitize_url(url), *args, **kwargs)
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 268, in __init__
    self.full_url = url
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 294, in full_url
    self._parse()
  File "C:\Users\Fuzze\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 323, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/yts/jsbin/player-en_US-vflqOi6vK/base.js'
 (caused by ValueError("unknown url type: '/yts/jsbin/player-en_US-vflqOi6vK/base.js'",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

---

### Description of your *issue*, suggested solution and other information

My code is the following 

opts = {
            'format': 'webm[abr>0]/bestaudio/best',
            'prefer_ffmpeg': True,
            'simulate': True,
            'verbose': True
        }
        ydl = youtube_dl.YoutubeDL(opts)
        info = ydl.extract_info('https://www.youtube.com/watch?v=wPBbMbKSZrQ',download=False)

The error occurs about 50% of the time on the extract_info call
For ease of reading i also made Pastebins of two output logs one working and one failing

Here is the same exact code run and it works
http://pastebin.com/fsRxMdGX

And here is the code ran several more times until it failed
http://pastebin.com/fR8PyNM4

It appears  somehow that one of the signature lengths is shorter than the others when it breaks?   Not sure if its Youtube giving you bad data or what?

**Comment by jaimeMF** [comment]
You are using an outdated version, [you have to update youtube-dl](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl).
