### ISSUE TITLE
openload not working

### ISSUE THREAD

**Issue by sigujoseph** [rg3/youtube-dl#12247]
:\Users\user\Downloads\youtube-dl-2017.02.24\youtube-dl>py youtube_dl --verbose https://openload.co/f/wFQxhy5bSdk/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://openload.co/f/wFQxhy5bSdk/']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2017.02.14
[debug] Python version 3.6.0 - Windows-10-10.0.10586-SP0
[debug] exe versions: ffmpeg N-82889-g54931fd, ffprobe N-82889-g54931fd
[debug] Proxy map: {}
[Openload] wFQxhy5bSdk: Downloading webpage
ERROR: Unable to extract openload ID; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-packages\youtube_dl-2017.2.14-py3.6.egg\youtube_dl\YoutubeDL.py", line 696, in extract_info
    ie_result = ie.extract(url)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-packages\youtube_dl-2017.2.14-py3.6.egg\youtube_dl\extractor\common.py", line 369, in extract
    return self._real_extract(url)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-packages\youtube_dl-2017.2.14-py3.6.egg\youtube_dl\extractor\openload.py", line 76, in _real_extract
    webpage, 'openload ID')
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-packages\youtube_dl-2017.2.14-py3.6.egg\youtube_dl\extractor\common.py", line 672, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract openload ID; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

C:\Users\user\Downloads\youtube-dl-2017.02.24\youtube-dl>

**Comment by sigujoseph** [comment]
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--verbose', 'https://openload.co/f/wFQxhy5bSdk/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.02.24
[debug] Python version 3.4.4 - Windows-10-10.0.10586
[debug] exe versions: ffmpeg N-82889-g54931fd, ffprobe N-82889-g54931fd
[debug] Proxy map: {}
[Openload] wFQxhy5bSdk: Downloading webpage
ERROR: Unable to extract openload ID; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpok6oidjm\build\youtube_dl\YoutubeDL.py", line 761, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpok6oidjm\build\youtube_dl\extractor\common.py", line 427, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpok6oidjm\build\youtube_dl\extractor\openload.py", line 76, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpok6oidjm\build\youtube_dl\extractor\common.py", line 759, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract openload ID; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by yan12125** [comment]
That will be fixed in the next version.
