### ISSUE TITLE
MSNBC Livestream errors

### ISSUE THREAD

**Issue by LikeLakers2** [rg3/youtube-dl#12287]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.02.24.1*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.24.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
C:\Users\Michelle\Videos>youtube-dl --verbose -- http://www.msnbc.com/live-online/watch/live-streaming-will-resume-shortly-871842883738
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--', 'http://www.msnbc.com/live-online/watch/live-streaming-will-resume-shortly-871842883738']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.02.24.1
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-79000-g66edd86, ffprobe N-79000-g66edd86
[debug] Proxy map: {}
[NBCNews] 871842883738: Downloading webpage
[ThePlatformFeed] n_shift_livesho_170207: Downloading JSON metadata
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpl89hv5ts\build\youtube_dl\__init__.py", line 457, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpl89hv5ts\build\youtube_dl\__init__.py", line 447, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpl89hv5ts\build\youtube_dl\YoutubeDL.py", line 1883, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpl89hv5ts\build\youtube_dl\YoutubeDL.py", line 772, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpl89hv5ts\build\youtube_dl\YoutubeDL.py", line 838, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpl89hv5ts\build\youtube_dl\YoutubeDL.py", line 761, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpl89hv5ts\build\youtube_dl\extractor\common.py", line 427, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpl89hv5ts\build\youtube_dl\extractor\theplatform.py", line 378, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpl89hv5ts\build\youtube_dl\extractor\theplatform.py", line 313, in _extract_feed_info
IndexError: list index out of range
```

```
C:\Users\Michelle\Videos>youtube-dl --verbose -- http://www.msnbc.com/msnbc-live
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--', 'http://www.msnbc.com/msnbc-live']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.02.24.1
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-79000-g66edd86, ffprobe N-79000-g66edd86
[debug] Proxy map: {}
[NBCNews] live: Downloading webpage
ERROR: An extractor error has occurred. (caused by KeyError('meta',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpl89hv5ts\build\youtube_dl\extractor\common.py", line 427, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpl89hv5ts\build\youtube_dl\extractor\nbc.py", line 371, in _real_extract
KeyError: 'meta'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpl89hv5ts\build\youtube_dl\extractor\common.py", line 427, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpl89hv5ts\build\youtube_dl\extractor\nbc.py", line 371, in _real_extract
KeyError: 'meta'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpl89hv5ts\build\youtube_dl\YoutubeDL.py", line 761, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpl89hv5ts\build\youtube_dl\extractor\common.py", line 440, in extract
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('meta',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

---

### Description of your *issue*, suggested solution and other information

These were found whilst seeing if youtube-dl would work with MSNBC's live stream of their own content. I know normally youtube-dl does not spit out a trace when a URL is not found, though it seems the MSNNews extractor caught it and attempted to download it as a pre-recorded video (not a stream), hence the first error above. Both of the URLs that I try above should lead to the same page (the second URL lead to the first URL in a web browser).

I am fairly certain, regardless of whether this is an extractor catching a URL it can't actually handle or not, the errors should not have been thrown, however. If it is indeed an extractor catching a URL it cannot handle, I would recommend having it error out in a more proper way, instead of throwing a trace.

**Comment by lwpVIM** [comment]
I have a similar IndexError crash, also on MSNBC.  I am trying to download a video, under linux.
lwp@william:/media/lwp/HermesNowVideo/Madhat.066$   youtube-dl    --print-traffic -v http://player.theplatform.com/p/7wvmTC/MSNBCEmbeddedOffSite?guid=n_maddow_dempty_150806
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--print-traffic', u'-v', u'http://player.theplatform.com/p/7wvmTC/MSNBCEmbeddedOffSite?guid=n_maddow_dempty_150806']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.03.07
[debug] Python version 2.7.9 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.7
[debug] exe versions: ffmpeg 3.2.4-1, ffprobe 3.2.4-1, rtmpdump 2.4
[debug] Proxy map: {}
[ThePlatform] MSNBCEmbeddedOffSite: Downloading webpage
send: u'GET /p/7wvmTC/MSNBCEmbeddedOffSite?guid=n_maddow_dempty_150806 HTTP/1.1\r\nHost: player.theplatform.com\r\nAccept-Language: en-us,en;q=0.5\r\nAccept-Encoding: gzip, deflate\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nUser-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/47.0 (Chrome)\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nConnection: close\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Wed, 08 Mar 2017 13:20:24 GMT
header: Access-Control-Allow-Origin: *
header: Content-Type: text/html;charset=UTF-8
header: P3P: CP="CUR CUS NOI STA NAV PSAi OUR OTRo IND"
header: Cache-Control: no-cache
header: X-Cache: HIT from player.theplatform.com:80
header: Connection: close
header: Server: Jetty(8.1.8.v20121106)
[ThePlatform] MSNBCEmbeddedOffSite: Downloading feed script
send: u'GET /cd771b0aa897f931a306d7ab6af0d448836b5fd1/satelliteLib-b4a012ca1ff96bd960a7a5db112455f1ce62a52e.js HTTP/1.1\r\nHost: assets.adobedtm.com\r\nAccept-Language: en-us,en;q=0.5\r\nAccept-Encoding: gzip, deflate\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nUser-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/47.0 (Chrome)\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nConnection: close\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Server: Apache
header: ETag: "f2c02145a691c6a34a7d4940a0931468:1487725736"
header: Last-Modified: Wed, 22 Feb 2017 01:08:56 GMT
header: Accept-Ranges: bytes
header: Content-Type: application/x-javascript
header: Vary: Accept-Encoding
header: Content-Encoding: gzip
header: Timing-Allow-Origin: *
header: Content-Length: 61092
header: Timing-Allow-Origin: *
header: Date: Wed, 08 Mar 2017 13:20:24 GMT
header: Connection: close
header: Timing-Allow-Origin: *
[ThePlatform] MSNBCEmbeddedOffSite: Downloading feed script
send: u'GET /i/videoassets/msnbc/dev/embed/offsite/js/c_offsite-160223a.js HTTP/1.1\r\nHost: media2.s-nbcnews.com\r\nAccept-Language: en-us,en;q=0.5\r\nAccept-Encoding: gzip, deflate\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nUser-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/47.0 (Chrome)\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nConnection: close\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Content-Type: application/x-javascript
header: Last-Modified: Tue, 23 Feb 2016 17:19:36 GMT
header: Accept-Ranges: bytes
header: ETag: "044635e5e6ed11:0"
header: Server: Microsoft-IIS/7.5
header: X-Powered-By: ASP.NET
header: Access-Control-Allow-Origin: *
header: Vary: Accept-Encoding
header: Content-Encoding: gzip
header: Date: Wed, 08 Mar 2017 13:20:24 GMT
header: Transfer-Encoding:  chunked
header: Connection: close
header: Connection: Transfer-Encoding
[ThePlatformFeed] n_maddow_dempty_150806: Downloading JSON metadata
send: u'GET /f/7wvmTC/msnbc_video-p-test?form=json&byGuid=n_maddow_dempty_150806 HTTP/1.1\r\nAccept-Language: en-us,en;q=0.5\r\nAccept-Encoding: gzip, deflate\r\nConnection: close\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nUser-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/47.0 (Chrome)\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nHost: feed.theplatform.com\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Wed, 08 Mar 2017 13:20:24 GMT
header: X-Cache: MISS from feed.theplatform.com
header: Expires: Wed, 08 Mar 2017 13:25:24 GMT
header: Last-Modified: Wed, 08 Mar 2017 13:20:24 GMT
header: Content-Type: text/plain;charset=UTF-8
header: Access-Control-Allow-Origin: *
header: Connection: close
header: Server: Jetty(8.1.16.2)
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 459, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 449, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1883, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 772, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 833, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 761, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 427, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/theplatform.py", line 378, in _real_extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/theplatform.py", line 313, in _extract_feed_info
IndexError: list index out of range
lwp@william:/media/lwp/HermesNowVideo/Madhat.066$
