### ISSUE TITLE
[mylifetime.com] ERROR: No video formats found

### ISSUE THREAD

**Issue by RuneMagle** [rg3/youtube-dl#12309]
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.28**
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
```
C:\Users\Desktop\youtube-dl>youtube-dl.exe -f best --all-subs http://www.mylifetime.com/shows/the-pop-game/season-1/episode-2/the-pop-game-episode-2-preview -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'best', '--all-subs', 'http://www.mylifetime.com/shows/the-pop-game/season-1/episode-2/the-pop-game-episode-2-preview', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.02.28
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-82833-gedb4f5d, ffprobe N-82833-gedb4f5d, rtmpdump 2.3
[debug] Proxy map: {}
[aenetworks] the-pop-game/season-1/episode-2: Downloading webpage
[aenetworks] 882592323590: Downloading JSON metadata
WARNING: unable to extract JSON-LD; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[aenetworks] 882592323590: Downloading SMIL data
[aenetworks] 882592323590: Checking video URL
[aenetworks] 882592323590: video URL is invalid, skipping
[aenetworks] 882592323590: Checking video URL
[aenetworks] 882592323590: video URL is invalid, skipping
[aenetworks] 882592323590: Checking video URL
[aenetworks] 882592323590: video URL is invalid, skipping
[aenetworks] 882592323590: Checking video URL
[aenetworks] 882592323590: video URL is invalid, skipping
[aenetworks] 882592323590: Checking video URL
[aenetworks] 882592323590: video URL is invalid, skipping
[aenetworks] 882592323590: Checking video URL
[aenetworks] 882592323590: video URL is invalid, skipping
[aenetworks] 882592323590: Checking video URL
[aenetworks] 882592323590: video URL is invalid, skipping
[aenetworks] 882592323590: Checking video URL
[aenetworks] 882592323590: video URL is invalid, skipping
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp_o63hpm_\build\youtube_dl\YoutubeDL.py", line 761, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp_o63hpm_\build\youtube_dl\extractor\common.py", line 427, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp_o63hpm_\build\youtube_dl\extractor\aenetworks.py", line 126, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp_o63hpm_\build\youtube_dl\extractor\common.py", line 1023, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video (clip): http://www.mylifetime.com/shows/the-pop-game/season-1/episode-2/the-pop-game-episode-2-preview
- Single video(full episode):  http://www.mylifetime.com/shows/the-pop-game/season-1/episode-1

---

It doesn't work :(

**Comment by goggle** [comment]
I think this was a server side issue they had yesterday. Seems to work again:
```
$ youtube-dl --all-subs "http://www.mylifetime.com/shows/the-pop-game/season-1/episode-2/the-pop-game-episode-2-preview"
[aenetworks] the-pop-game/season-1/episode-2: Downloading webpage
[aenetworks] 882592323590: Downloading JSON metadata
WARNING: unable to extract JSON-LD; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[aenetworks] 882592323590: Downloading SMIL data
[aenetworks] 882592323590: Checking video URL
[aenetworks] 882592323590: Checking video URL
[aenetworks] 882592323590: Checking video URL
[aenetworks] 882592323590: Checking video URL
[aenetworks] 882592323590: Checking video URL
[aenetworks] 882592323590: Checking video URL
[aenetworks] 882592323590: Checking video URL
[aenetworks] 882592323590: Checking video URL
[download] Destination: The Pop Game Episode 2 Preview-882592323590.mp4
[download] 100% of 9.35MiB in 00:02
$ youtube-dl --all-subs "http://www.mylifetime.com/shows/the-pop-game/season-1/episode-1"
[aenetworks] the-pop-game/season-1/episode-1: Downloading webpage
[aenetworks] 879852611915: Downloading JSON metadata
[aenetworks] 879852611915: Downloading SMIL data
[aenetworks] 879852611915: Checking video URL
[aenetworks] 879852611915: Checking video URL
[aenetworks] 879852611915: Checking video URL
[aenetworks] 879852611915: Checking video URL
[aenetworks] 879852611915: Checking video URL
[aenetworks] 879852611915: Checking video URL
[aenetworks] 879852611915: Checking video URL
[aenetworks] 879852611915: Checking video URL
[info] Writing video subtitles to: Got What It Takes-879852611915.en.dfxp
[download] Destination: Got What It Takes-879852611915.mp4
[download]   2.3% of 797.60MiB at 714.72KiB/s ETA 18:36
```

**Comment by RuneMagle** [comment]
Yep, seems to be working now ;)
