### ISSUE TITLE
ERROR: Signature extraction failed

### ISSUE THREAD

**Issue by uzielweb** [rg3/youtube-dl#12319]
Here is my paste of this error:

 youtube-dl https://www.youtube.com/watch?v=LaTbXphLhFk
[youtube] LaTbXphLhFk: Downloading webpage
[youtube] LaTbXphLhFk: Downloading video info webpage
[youtube] LaTbXphLhFk: Extracting video information
[youtube] LaTbXphLhFk: Downloading js player en_US-vflVlxFvV
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 1001, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 915, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 503, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 410, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 390, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1950, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 421, in open
    protocol = req.get_type()
  File "/usr/lib/python2.7/urllib2.py", line 283, in get_type
    raise ValueError, "unknown url type: %s" % self.__original
ValueError: unknown url type: /yts/jsbin/player-en_US-vflVlxFvV/base.js
 (caused by ValueError(u'unknown url type: /yts/jsbin/player-en_US-vflVlxFvV/base.js',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [this FAQ entry](https://yt-dl.org/update) if you have troubles updating.
