### ISSUE TITLE
[Facebook] video parsing is not working

### ISSUE THREAD

**Issue by souravndp** [rg3/youtube-dl#12323]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.02.28**

### I have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### purpose of my *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### full verbose output as follows:
```
C:\Users\Sourav\Desktop> youtube-dl -s --verbose "https://www.facebook.com/buzzfeedtasty/videos/1841707432748564/?__mref=message_bubble" 
[debug] System config: [] 
[debug] User config: []  
[debug] Custom config: []
[debug] Command-line args: ['-s', '--verbose', 'https://www.facebook.com/buzzfeedtasty/videos/1841707432748564/?__mref=message_bubble']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.02.28 
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: none 
[debug] Proxy map: {}  
[facebook] 1841707432748564: Downloading webpage 
[facebook] 1841707432748564: Downloading webpage 
ERROR: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. 
Traceback (most recent call last): 
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp_o63hpm_\build\youtube_dl\YoutubeDL.py", line 761, in extract_info
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp_o63hpm_\build\youtube_dl\extractor\common.py", line 427, in extract
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp_o63hpm_\build\youtube_dl\extractor\facebook.py", line 408, in _real_extract
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp_o63hpm_\build\youtube_dl\extractor\facebook.py", line 325, in _extract_from_url  
youtube_dl.utils.ExtractorError: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

---

### Description of the *issue*:

Download worked even 2 days ago. But today it is not working. Youtube download is working. I am from India (In case facebook's page structure is different in different country)

**Comment by pkirk** [comment]
Same problem here, adding my verbose output so you can see the traceback:

```
MacBook-Pro-di-Paolo:~ paolo$ youtube-dl --verbose https://www.facebook.com/GIGadgets.Fans/videos/1322618441150775/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.facebook.com/GIGadgets.Fans/videos/1322618441150775/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.02.28
[debug] Python version 2.7.10 - Darwin-16.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg N-79129-gb3dc51d-tessus, ffprobe N-79800-g7b7c338-tessus
[debug] Proxy map: {}
[facebook] 1322618441150775: Downloading webpage
[facebook] 1322618441150775: Downloading webpage
ERROR: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 761, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 427, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/facebook.py", line 408, in _real_extract
    video_id, fatal_if_no_video=True)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/facebook.py", line 325, in _extract_from_url
    raise ExtractorError('Cannot parse data')
ExtractorError: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by sant527** [comment]
Same problem here:

```
% youtube-dl -v -s -F "https://www.facebook.com/nba/videos/10154919342108463/"                             :(
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-s', '-F', 'https://www.facebook.com/nba/videos/10154919342108463/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.02.24
[debug] Python version 3.5.1 - Linux-4.6.2-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 3.0.2, ffprobe 3.0.2, rtmpdump 2.4
[debug] Proxy map: {}
[facebook] 10154919342108463: Downloading webpage
[facebook] 10154919342108463: Downloading webpage
ERROR: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 761, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 427, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/facebook.py", line 408, in _real_extract
    video_id, fatal_if_no_video=True)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/facebook.py", line 325, in _extract_from_url
    raise ExtractorError('Cannot parse data')
youtube_dl.utils.ExtractorError: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

Also tried with username and password:

```
% youtube-dl -v -s -F --username "something@gmail.com" --password "something" "https://www.facebook.com/nba/videos/10154919342108463/"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-s', '-F', '--username', 'PRIVATE', '--password', 'PRIVATE', 'https://www.facebook.com/nba/videos/10154919342108463/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.02.24
[debug] Python version 3.5.1 - Linux-4.6.2-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 3.0.2, ffprobe 3.0.2, rtmpdump 2.4
[debug] Proxy map: {}
[facebook] Downloading login page
[facebook] Logging in
[facebook] 10154919342108463: Downloading webpage
[facebook] 10154919342108463: Downloading webpage
ERROR: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 761, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 427, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/facebook.py", line 408, in _real_extract
    video_id, fatal_if_no_video=True)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/facebook.py", line 325, in _extract_from_url
    raise ExtractorError('Cannot parse data')
youtube_dl.utils.ExtractorError: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

**Comment by yan12125** [comment]
Will be fixed in the next version. Thanks for those reports!
