### ISSUE TITLE
error downloading Facebook video

### ISSUE THREAD

**Issue by drxero** [rg3/youtube-dl#12330]
Unable to download a video from Facebook. I verified in a  browser the video was working, and did not require the user to be signed in. Here's the URL I'm trying to get:

https://www.facebook.com/thecalvinwayman/videos/1117031128379911/

Here's the output:

```
:~$ youtube-dl --verbose "https://www.facebook.com/thecalvinwayman/videos/1117031128379911/"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.facebook.com/thecalvinwayman/videos/1117031128379911/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.02.28
[debug] Python version 2.7.12 - Linux-4.4.0-59-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.10-0ubuntu0.16.04.1, ffprobe 2.8.10-0ubuntu0.16.04.1
[debug] Proxy map: {}
[facebook] 1117031128379911: Downloading webpage
[facebook] 1117031128379911: Downloading webpage
ERROR: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 761, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 427, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/facebook.py", line 408, in _real_extract
    video_id, fatal_if_no_video=True)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/facebook.py", line 325, in _extract_from_url
    raise ExtractorError('Cannot parse data')
ExtractorError: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by drxero** [comment]
Which is it a duplicate of, please?
