### ISSUE TITLE
[go] Fake IP not working (Go said: 6007:Unable to retrieve required files)

### ISSUE THREAD

**Issue by RuneMagle** [rg3/youtube-dl#12355]
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.03.02**
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
```
C:\Users\Desktop\youtube-dl>youtube-dl.exe -f best --all-subs --username PRIVATE --password july1987 --ap-username PRIVATE --ap-password july1987 --ap-mso DTV --continue --no-check-certificate http://watchdisneychannel.go.com/descendants-wicked-world/video/vdka3698796/02/01-jewelbilee -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'best', '--all-subs', '--username', 'PRIVATE', '--password', 'PRIVATE', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '--ap-mso', 'DTV', '--continue', '--no-check-certificate', 'http://watchdisneychannel.go.com/descendants-wicked-world/video/vdka3698796/02/01-jewelbilee', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.03.02
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-82833-gedb4f5d, ffprobe N-82833-gedb4f5d, rtmpdump 2.3
[debug] Proxy map: {}
[Go] 3698796: Downloading JSON metadata
[Go] 3698796: Retrieving Media Token
[Go] 3698796: Downloading Provider Redirect Page
[Go] 3698796: Downloading Provider Login Page
[Go] 3698796: Logging in
[Go] 3698796: Confirming Login
[Go] 3698796: Retrieving Session
[Go] 3698796: Retrieving Authorization Token
[Go] 3698796: Retrieving Media Token
[Go] 3698796: Downloading JSON metadata
WARNING: [Go] Video is geo restricted. Retrying extraction with fake IP 3.116.93.222 (US) as X-Forwarded-For.
[Go] 3698796: Downloading JSON metadata
[Go] 3698796: Retrieving Media Token
[Go] 3698796: Downloading Provider Redirect Page
[Go] 3698796: Downloading Provider Login Page
[Go] 3698796: Logging in
[Go] 3698796: Confirming Login
[Go] 3698796: Retrieving Session
[Go] 3698796: Retrieving Authorization Token
[Go] 3698796: Downloading JSON metadata
ERROR: Go said: 6007:Unable to retrieve required files for playback. Please try again in a few minutes.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpbcda0ng_\build\youtube_dl\YoutubeDL.py", line 761, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpbcda0ng_\build\youtube_dl\extractor\common.py", line 427, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpbcda0ng_\build\youtube_dl\extractor\go.py", line 110, in _real_extract
youtube_dl.utils.ExtractorError: Go said: 6007:Unable to retrieve required files for playback. Please try again in a few minutes.
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://watchdisneychannel.go.com/descendants-wicked-world/video/vdka3698796/02/01-jewelbilee
- Single video: http://watchdisneychannel.go.com/liv-and-maddie/video/vdka3712878/04/13-sing-it-livearooney
- Single video: http://abc.go.com/shows/oscars/episode-guide/season-89/4-the-oscars-2017

---

### Description of your my issue.

Fake IP not working. I can provide my TV credentials if needed.

**Comment by dstftw** [comment]
Does it work with `--no-geo-bypass`?

**Comment by RuneMagle** [comment]
No. I'm not in US.

`C:\Users\Desktop\youtube-dl>youtube-dl.exe -f best --all-subs --username ag316805@gmail.com --password july1987 --ap-username ag316805@gmail.com --ap-password july1987 --ap-mso DTV --continue --no-check-certificate --no-geo-bypass http://watchdisneychannel.go.com/descendants-wicked-world/video/vdka3698796/02/01-jewelbilee -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'best', '--all-subs', '--username', 'PRIVATE', '--password', 'PRIVATE', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '--ap-mso', 'DTV', '--continue', '--no-check-certificate', '--no-geo-bypass', 'http://watchdisneychannel.go.com/descendants-wicked-world/video/vdka3698796/02/01-jewelbilee', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.03.02
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-82833-gedb4f5d, ffprobe N-82833-gedb4f5d, rtmpdump 2.3
[debug] Proxy map: {}
[Go] 3698796: Downloading JSON metadata
[Go] 3698796: Retrieving Media Token
[Go] 3698796: Downloading Provider Redirect Page
[Go] 3698796: Downloading Provider Login Page
[Go] 3698796: Logging in
[Go] 3698796: Confirming Login
[Go] 3698796: Retrieving Session
[Go] 3698796: Retrieving Authorization Token
[Go] 3698796: Retrieving Media Token
[Go] 3698796: Downloading JSON metadata
ERROR: 1002:You appear to be outside the United States or its territories. Due to international rights agreements, we only offer this video to viewers located within the United States and its territories.
This video is available in United States.
You might want to use a VPN or a proxy server (with --proxy) to workaround.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpbcda0ng_\build\youtube_dl\YoutubeDL.py", line 761, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpbcda0ng_\build\youtube_dl\extractor\common.py", line 427, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpbcda0ng_\build\youtube_dl\extractor\go.py", line 108, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpbcda0ng_\build\youtube_dl\extractor\common.py", line 701, in raise_geo_restricted
youtube_dl.utils.GeoRestrictedError: 1002:You appear to be outside the United States or its territories. Due to international rights agreements, we only offer this video to viewers located within the United States and its territories.`

**Comment by dstftw** [comment]
It's not supposed to work in all cases. It will only work if all checkpoints that verify geo location honor X-Forwarded-For header.

**Comment by RuneMagle** [comment]
What do you mean? It never works!

**Comment by RuneMagle** [comment]
Only with the free ones.

**Comment by yan12125** [comment]
In 8e1409fd805b3b5e3731da66a2101494643a06ea, @remitamine wrote:

> use geo bypass only for free videos

Seems the bypass works for free videos only? By default X-Forward-For is always used in face of ```GeoRestrictedError```. If we know it won't work, how about explicitly disabling it to prevent further confusions? (I didn't test it as I don't have an account)
```Diff
diff --git a/youtube_dl/extractor/go.py b/youtube_dl/extractor/go.py
index 4c9be47b4..30c666e67 100644
--- a/youtube_dl/extractor/go.py
+++ b/youtube_dl/extractor/go.py
@@ -101,6 +101,9 @@ class GoIE(AdobePassIE):
                         'token_type': 'ap',
                         'adobe_requestor_id': requestor_id,
                     })
+                    # Explicitly disables X-Forward-For bypassing as it works
+                    # for free videos only and may bring confusions (#12355)
+                    self._GEO_BYPASS = False
                 else:
                     self._initialize_geo_bypass(['US'])
                 entitlement = self._download_json(

```

**Comment by RuneMagle** [comment]
If you don't have an account, you can find a stolen one here: http://freebie-nation.org/

**Comment by yan12125** [comment]
@RuneMagle I deleted your last comment as we don't want to spread illegal stuffs.

**Comment by RuneMagle** [comment]
Well, I wouldn't say it's illegal, just a...workaround...

**Comment by StevenDTX** [comment]
Works just fine in the US, even without a login.

```

E:\>youtube-dl.exe --verbose http://watchdisneychannel.go.com/descendants-wicked-world/video/vdka3698796/02/01-jewelbilee
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'http://watchdisneychannel.go.com/descendants-wicked-world/video/vdka3698796/02/01-jewelbilee']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.03.02
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-82966-g6993bb4, ffprobe N-72383-g7206b94, rtmpdump 2.4
[debug] Proxy map: {}
[Go] 3698796: Downloading JSON metadata
[Go] 3698796: Retrieving Authorization Token
[Go] 3698796: Retrieving Media Token
[Go] 3698796: Downloading JSON metadata
[Go] 3698796: Downloading m3u8 information
[debug] Invoking downloader on 'http://content-auso3.uplynk.com/1ab51bd7495d49478b26770b4c22032b/j.m3u8?exp=1488651346&ct=a&oid=21885d134fa441488df8e1d7acee8c66&eid=10085953&iph=d6f86aa9c907b9fd9e516da8fededd6f334288018690a5fb7968b452b27fa498&rays=jihgfedcb&euid=D6BD9435-8213-41BB-ACB6-9EA70A917473_000_1_001_lf_03-06-00_NA&cdn=ec&stgcfg=datg&pp2ip=0&sig=92e029ddcf236ac6301275b7f16d92185f5cc614fcea2d53c03583be9614ecaa&pbs=614233d7d4654542af68ca583208a7e0'
[download] Destination: S2 E1 - Jewel-bilee-3698796.mp4
[debug] ffmpeg command line: ffmpeg -y -headers 'Accept-Encoding: gzip, deflate
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/47.0 (Chrome)
Accept-Language: en-us,en;q=0.5
' -i 'http://content-auso3.uplynk.com/1ab51bd7495d49478b26770b4c22032b/j.m3u8?exp=1488651346&ct=a&oid=21885d134fa441488df8e1d7acee8c66&eid=10085953&iph=d6f86aa9c907b9fd9e516da8fededd6f334288018690a5fb7968b452b27fa498&rays=jihgfedcb&euid=D6BD9435-8213-41BB-ACB6-9EA70A917473_000_1_001_lf_03-06-00_NA&cdn=ec&stgcfg=datg&pp2ip=0&sig=92e029ddcf236ac6301275b7f16d92185f5cc614fcea2d53c03583be9614ecaa&pbs=614233d7d4654542af68ca583208a7e0' -c copy -f mp4 -bsf:a aac_adtstoasc 'file:S2 E1 - Jewel-bilee-3698796.mp4.part'
ffmpeg version N-82966-g6993bb4 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 5.4.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-dxva2 --enable-libmfx --enable-nvenc --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-decklink --enable-zlib
  libavutil      55. 43.100 / 55. 43.100
  libavcodec     57. 70.100 / 57. 70.100
  libavformat    57. 61.100 / 57. 61.100
  libavdevice    57.  2.100 / 57.  2.100
  libavfilter     6. 68.100 /  6. 68.100
  libswscale      4.  3.101 /  4.  3.101
  libswresample   2.  4.100 /  2.  4.100
  libpostproc    54.  2.100 / 54.  2.100
[aac @ 0000000002822c40] element type mismatch 1 != 0
Input #0, hls,applehttp, from 'http://content-auso3.uplynk.com/1ab51bd7495d49478b26770b4c22032b/j.m3u8?exp=1488651346&ct=a&oid=21885d134fa441488df8e1d7acee8c66&eid=10085953&iph=d6f86aa9c907b9fd9e516da8fededd6f334288018690a5fb7968b452b27fa498&rays=jihgfedcb&euid=D6BD9435-8213-41BB-ACB6-9EA70A917473_000_1_001_lf_03-06-00_NA&cdn=ec&stgcfg=datg&pp2ip=0&sig=92e029ddcf236ac6301275b7f16d92185f5cc614fcea2d53c03583be9614ecaa&pbs=614233d7d4654542af68ca583208a7e0':
  Duration: 00:35:54.45, start: 0.000000, bitrate: 0 kb/s
  Program 0
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Audio: aac (HE-AAC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p, 1280x720, 23.98 tbr, 90k tbn, 48 tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:2: Data: timed_id3 (ID3  / 0x20334449)
    Metadata:
      variant_bitrate : 0
Output #0, mp4, to 'file:S2 E1 - Jewel-bilee-3698796.mp4.part':
  Metadata:
    encoder         : Lavf57.61.100
    Stream #0:0: Video: h264 (High) ([33][0][0][0] / 0x0021), yuv420p, 1280x720, q=2-31, 23.98 tbr, 90k tbn, 90k tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (HE-AAC) ([64][0][0][0] / 0x0040), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
Stream mapping:
  Stream #0:1 -> #0:0 (copy)
  Stream #0:0 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame= 1118 fps=365 q=-1.0 Lsize=   19826kB time=00:00:46.84 bitrate=3466.9kbits/s speed=15.3x
video:19093kB audio:725kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.041663%
Exiting normally, received signal 2.

ERROR: Interrupted by user

```

**Comment by RuneMagle** [comment]
Yeah, I know. It works fine with me too, but I can only get it to work with very slow VPN. But it don't work with no VPN, because I'm in DK. I don't know how you get it without login though, because it's locked, and it doesn't work here.
```
C:\Users\rumag\Desktop\youtube-dl>youtube-dl.exe --verbose http://watchdisneychannel.go.com/descendants-wicked-world/video/vdka3698796/02/01-jewelbilee
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'http://watchdisneychannel.go.com/descendants-wicked-world/video/vdka3698796/02/01-jewelbilee']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.03.02
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-82833-gedb4f5d, ffprobe N-82833-gedb4f5d, rtmpdump 2.3
[debug] Proxy map: {}
[Go] 3698796: Downloading JSON metadata
[Go] 3698796: Retrieving Media Token
ERROR: This video is only available for users of participating TV providers. Use --ap-mso to specify Adobe Pass Multiple-system operator Identifier and --ap-username and --ap-password or --netrc to provide account credentials.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpbcda0ng_\build\youtube_dl\YoutubeDL.py", line 761, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpbcda0ng_\build\youtube_dl\extractor\common.py", line 427, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpbcda0ng_\build\youtube_dl\extractor\go.py", line 92, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpbcda0ng_\build\youtube_dl\extractor\adobepass.py", line 1366, in _extract_mvpd_auth
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpbcda0ng_\build\youtube_dl\extractor\adobepass.py", line 1346, in raise_mvpd_required
youtube_dl.utils.ExtractorError: This video is only available for users of participating TV providers. Use --ap-mso to specify Adobe Pass Multiple-system operator Identifier and --ap-username and --ap-password or --netrc to provide account credentials.
```
