### ISSUE TITLE
Not downloading

### ISSUE THREAD

**Issue by jackzulaa** [rg3/youtube-dl#12409]
D:\moses>youtube-dl https://www.youtube.com/watch?v=XtpPSugtX8A&index=1&list=RDXtpPSugtX8A
[youtube] XtpPSugtX8A: Downloading webpage
[youtube] XtpPSugtX8A: Downloading video info webpage
[youtube] XtpPSugtX8A: Extracting video information
WARNING: unable to extract uploader nickname
[youtube] XtpPSugtX8A: Downloading js player en_US-vflOnuOF-
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\youtube_dl\extractor\youtube.py", line 1011, in _decrypt_signature
    video_id, player_url, s
  File "C:\Python27\lib\site-packages\youtube_dl\extractor\youtube.py", line 925, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "C:\Python27\lib\site-packages\youtube_dl\extractor\common.py", line 519, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "C:\Python27\lib\site-packages\youtube_dl\extractor\common.py", line 426, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "C:\Python27\lib\site-packages\youtube_dl\extractor\common.py", line 406, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "C:\Python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 2001, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "C:\Python27\lib\urllib2.py", line 423, in open
    protocol = req.get_type()
  File "C:\Python27\lib\urllib2.py", line 285, in get_type
    raise ValueError, "unknown url type: %s" % self.__original
ValueError: unknown url type: /yts/jsbin/player-en_US-vflOnuOF-/base.js
 (caused by ValueError(u'unknown url type: /yts/jsbin/player-en_US-vflOnuOF-/base.js',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  h
'index' is not recognized as an internal or external command,
operable program or batch file.
'list' is not recognized as an internal or external command,
operable program or batch file.

D:\moses>youtube-dl https://www.youtube.com/watch?v=XtpPSugtX8A
[youtube] XtpPSugtX8A: Downloading webpage
[youtube] XtpPSugtX8A: Downloading video info webpage
[youtube] XtpPSugtX8A: Extracting video information
[youtube] XtpPSugtX8A: Downloading js player en_US-vflOnuOF-
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\youtube_dl\extractor\youtube.py", line 1011, in _decrypt_signature
    video_id, player_url, s
  File "C:\Python27\lib\site-packages\youtube_dl\extractor\youtube.py", line 925, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "C:\Python27\lib\site-packages\youtube_dl\extractor\common.py", line 519, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "C:\Python27\lib\site-packages\youtube_dl\extractor\common.py", line 426, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "C:\Python27\lib\site-packages\youtube_dl\extractor\common.py", line 406, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "C:\Python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 2001, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "C:\Python27\lib\urllib2.py", line 423, in open
    protocol = req.get_type()
  File "C:\Python27\lib\urllib2.py", line 285, in get_type
    raise ValueError, "unknown url type: %s" % self.__original
ValueError: unknown url type: /yts/jsbin/player-en_US-vflOnuOF-/base.js
 (caused by ValueError(u'unknown url type: /yts/jsbin/player-en_US-vflOnuOF-/base.js',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  h

D:\moses>
D:\moses>
D:\moses>
D:\moses>clear

D:\moses>youtube-dl https://www.youtube.com/watch?v=XWqFFlwC_yI&list=RDXtpPSugtX8A
[youtube] XWqFFlwC_yI: Downloading webpage
[youtube] XWqFFlwC_yI: Downloading video info webpage
[youtube] XWqFFlwC_yI: Extracting video information
[youtube] XWqFFlwC_yI: Downloading js player en_US-vflOnuOF-
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\youtube_dl\extractor\youtube.py", line 1011, in _decrypt_signature
    video_id, player_url, s
  File "C:\Python27\lib\site-packages\youtube_dl\extractor\youtube.py", line 925, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "C:\Python27\lib\site-packages\youtube_dl\extractor\common.py", line 519, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "C:\Python27\lib\site-packages\youtube_dl\extractor\common.py", line 426, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "C:\Python27\lib\site-packages\youtube_dl\extractor\common.py", line 406, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "C:\Python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 2001, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "C:\Python27\lib\urllib2.py", line 423, in open
    protocol = req.get_type()
  File "C:\Python27\lib\urllib2.py", line 285, in get_type
    raise ValueError, "unknown url type: %s" % self.__original
ValueError: unknown url type: /yts/jsbin/player-en_US-vflOnuOF-/base.js
 (caused by ValueError(u'unknown url type: /yts/jsbin/player-en_US-vflOnuOF-/base.js',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  h
'list' is not recognized as an internal or external command,
operable program or batch file.

D:\moses>youtube-dl https://www.youtube.com/watch?v=XWqFFlwC_yI&list=RDXtpPSugtX8A&index=2
[youtube] XWqFFlwC_yI: Downloading webpage
[youtube] XWqFFlwC_yI: Downloading video info webpage
[youtube] XWqFFlwC_yI: Extracting video information
[youtube] XWqFFlwC_yI: Downloading js player en_US-vflOnuOF-
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\youtube_dl\extractor\youtube.py", line 1011, in _decrypt_signature
    video_id, player_url, s
  File "C:\Python27\lib\site-packages\youtube_dl\extractor\youtube.py", line 925, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "C:\Python27\lib\site-packages\youtube_dl\extractor\common.py", line 519, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "C:\Python27\lib\site-packages\youtube_dl\extractor\common.py", line 426, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "C:\Python27\lib\site-packages\youtube_dl\extractor\common.py", line 406, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "C:\Python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 2001, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "C:\Python27\lib\urllib2.py", line 423, in open
    protocol = req.get_type()
  File "C:\Python27\lib\urllib2.py", line 285, in get_type
    raise ValueError, "unknown url type: %s" % self.__original
ValueError: unknown url type: /yts/jsbin/player-en_US-vflOnuOF-/base.js
 (caused by ValueError(u'unknown url type: /yts/jsbin/player-en_US-vflOnuOF-/base.js',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  h
'list' is not recognized as an internal or external command,
operable program or batch file.
'index' is not recognized as an internal or external command,
operable program or batch file.

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [this FAQ entry](https://yt-dl.org/update) if you have troubles updating.
