### ISSUE TITLE
suffolk.edu/sjc support broke on Feb.16

### ISSUE THREAD

**Issue by johnhawkinson** [rg3/youtube-dl#12410]
…even though there's a test for it! Not quite sure I understand, although the test is marked `'skip_download': True` so that might be related, except the failure is pre-download and I don't fully understand.

I left https://github.com/rg3/youtube-dl/commit/a4a554a79354981fcab55de8eaab7b95a40bbb48#commitcomment-21221835 which was probably not useful and I should have just filed an issue.

Support for this was added in response to #11993 on Feb. 6, but it was broken ten days later in a4a554a79354981fcab55de8eaab7b95a40bbb48:

```
pb3:youtube-dl jhawk$ git checkout b898f0a173fa040ddf95dbd97650cec07a8f19f5
Previous HEAD position was a50862b73... [downloader/external] Add missing import and PEP8
HEAD is now at b898f0a17... [elpais] Fix typo and improve extraction (closes #12139)
pb3:youtube-dl jhawk$ python test/test_download.py TestDownload.test_Generic_61
[generic] sjc: Requesting header
[generic] sjc: Downloading webpage
[generic] sjc: Extracting information
[info] Writing video description metadata as JSON to: sjclive.info.json
.
----------------------------------------------------------------------
Ran 1 test in 0.810s

OK
pb3:youtube-dl jhawk$ git checkout a4a554a79354981fcab55de8eaab7b95a40bbb48
Previous HEAD position was b898f0a17... [elpais] Fix typo and improve extraction (closes #12139)
HEAD is now at a4a554a79... [generic] Try parsing JWPlayer embedded videos (closes #12030)
pb3:youtube-dl jhawk$ python test/test_download.py TestDownload.test_Generic_61
[generic] sjc: Requesting header
[generic] sjc: Downloading webpage
[generic] sjc: Extracting information
ERROR: An extractor error has occurred. (caused by KeyError(u'title',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/Users/jhawk/src/youtube-dl/youtube_dl/extractor/common.py", line 370, in extract
    return self._real_extract(url)
  File "/Users/jhawk/src/youtube-dl/youtube_dl/extractor/generic.py", line 2507, in _real_extract
    return self._parse_jwplayer_data(jwplayer_data, video_id)
  File "/Users/jhawk/src/youtube-dl/youtube_dl/extractor/common.py", line 2181, in _parse_jwplayer_data
    'title': video_data['title'] if require_title else video_data.get('title'),
KeyError: u'title'
Traceback (most recent call last):
  File "/Users/jhawk/src/youtube-dl/youtube_dl/YoutubeDL.py", line 696, in extract_info
    ie_result = ie.extract(url)
  File "/Users/jhawk/src/youtube-dl/youtube_dl/extractor/common.py", line 376, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
ExtractorError: An extractor error has occurred. (caused by KeyError(u'title',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

E
======================================================================
ERROR: test_Generic_61 (__main__.TestDownload)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_download.py", line 142, in test_template
    force_generic_extractor=params.get('force_generic_extractor', False))
  File "/Users/jhawk/src/youtube-dl/youtube_dl/YoutubeDL.py", line 711, in extract_info
    self.report_error(compat_str(e), e.format_traceback())
  File "/Users/jhawk/src/youtube-dl/youtube_dl/YoutubeDL.py", line 570, in report_error
    self.trouble(error_message, tb)
  File "/Users/jhawk/src/youtube-dl/youtube_dl/YoutubeDL.py", line 540, in trouble
    raise DownloadError(message, exc_info)
DownloadError: ERROR: An extractor error has occurred. (caused by KeyError(u'title',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

----------------------------------------------------------------------
Ran 1 test in 0.781s

FAILED (errors=1)
```

and it remains broken now. Of course the actual test is now `test_Generic_62`. Here's the -v output if we really need that:

```
pb3:youtube-dl jhawk$ python -m youtube_dl -v http://suffolk.edu/sjc/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'http://suffolk.edu/sjc/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.03.07
[debug] Git HEAD: 76bee08fe
[debug] Python version 2.7.10 - Darwin-14.5.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg git-2017-02-28-7f62368, ffprobe git-2017-02-28-7f62368, rtmpdump 2.4
[debug] Proxy map: {}
[generic] sjc: Requesting header
WARNING: Falling back on generic information extractor.
[generic] sjc: Downloading webpage
[generic] sjc: Extracting information
ERROR: An extractor error has occurred. (caused by KeyError(u'title',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dl/extractor/common.py", line 427, in extract
    ie_result = self._real_extract(url)
  File "youtube_dl/extractor/generic.py", line 2553, in _real_extract
    return self._parse_jwplayer_data(jwplayer_data, video_id)
  File "youtube_dl/extractor/common.py", line 2221, in _parse_jwplayer_data
    'title': video_data['title'] if require_title else video_data.get('title'),
KeyError: u'title'
Traceback (most recent call last):
  File "youtube_dl/YoutubeDL.py", line 761, in extract_info
    ie_result = ie.extract(url)
  File "youtube_dl/extractor/common.py", line 440, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
ExtractorError: An extractor error has occurred. (caused by KeyError(u'title',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by yan12125** [comment]
Thanks for this report. Sorry I haven't had time to refine jwplayer support in generic.py. I should have been pass ```require_title=False``` to ```_parse_jwplayer_data```.

Related: #12307
