### ISSUE TITLE
kaltura playlist: invalid URL

### ISSUE THREAD

**Issue by sg0001** [rg3/youtube-dl#12427]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.03.10**

```
~$ youtube-dl --version
2017.03.10
```

### I have

- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
    - 5081 and #6137 were fixes in past versions, I think
    - #12041 indicates a non-url format for single Kaltura videos; I tried this with the playlist ID and got an extractor error (also below)

### purpose of issue
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### verbose output

```
~$ youtube-dl -v "https://cdnapisec.kaltura.com/html5/html5lib/v2.41/mwEmbedFrame.php/p/1770401/uiconf_id/34290512?wid=_1770401&iframeembed=true&playerId=kaltura_player_1484154962&flashvars%5BstreamerType%5D=auto&flashvars%5BplaylistAPI.kpl0Id%5D=0_pmra4snw"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://cdnapisec.kaltura.com/html5/html5lib/v2.41/mwEmbedFrame.php/p/1770401/uiconf_id/34290512?wid=_1770401&iframeembed=true&playerId=kaltura_player_1484154962&flashvars%5BstreamerType%5D=auto&flashvars%5BplaylistAPI.kpl0Id%5D=0_pmra4snw']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.03.10
[debug] Python version 2.7.13 - Darwin-14.5.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.2, ffprobe 3.2, rtmpdump 2.4
[debug] Proxy map: {}
ERROR: Invalid URL
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 761, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 427, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/kaltura.py", line 248, in _real_extract
    raise ExtractorError('Invalid URL', expected=True)
ExtractorError: Invalid URL
```

Trying the format from #12041 (see above) with parameters taken from URL: 
```
~$ youtube-dl -v kaltura:1770401:0_pmra4snw
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'kaltura:1770401:0_pmra4snw']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.03.10
[debug] Python version 2.7.13 - Darwin-14.5.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.2, ffprobe 3.2, rtmpdump 2.4
[debug] Proxy map: {}
[Kaltura] 0_pmra4snw: Downloading video info JSON
ERROR: An extractor error has occurred. (caused by KeyError(u'dataUrl',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 427, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/kaltura.py", line 266, in _real_extract
    data_url = info['dataUrl']
KeyError: u'dataUrl'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 761, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 440, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
ExtractorError: An extractor error has occurred. (caused by KeyError(u'dataUrl',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

---

I tried archiving a playlist from a kaltera embed URL, but am running into problems. The page I'm trying to download from is behind a login redirect which wasn't working with a passed username/pass, so I tried downloading from the playlist embed URL. (I am not sure about the copyright of the example I have on hand but kaltera is already listed as a supported site so I figured I'd submit a report.)

Not sure if kaltera updated or if there's just a different URL the utility needs. I've been poking around the embed source but haven't found a different URL to try yet. (I also tried the alternate `kaltera:` format mentioned in another issue and what I think are the creator and playlist IDs from the URL, but it also gave me a bug and said to report.)

Thanks!

**Comment by sg0001** [comment]
I was able to find the IDs by rooting around the source of the page, so I think this might just be a hole in the kaltura extractor.

Solved my issue, thanks though! Will leave this here in case someone figures out a fix.

**Comment by maxst33l** [comment]
> I was able to find the IDs by rooting around the source of the page, so I think this might just be a hole in the kaltura extractor.
> 
> Solved my issue, thanks though! Will leave this here in case someone figures out a fix.

@sg0001 How did you find the ID? were you able to figure out how to download a video from kaltura?  please help :) thanks!

**Comment by JonasOlson** [comment]
@sg0001
> I tried archiving a playlist from kaltura but it's not working... also tried the non-URL `kaltura:` format with with the IDs in the URL, but it gave me an extractor error and said to report.

How does one use such a format?

**Comment by JonasOlson** [comment]
If it's of any help:

As seen [here](https://tpprop.com/PROPWIZARD/php/frameworks/kaltura-mwEmbed-ffdcd55/docs/index.php?path=Playlists/playlistApi), with a partner ID and a playlist ID, one can form a playlist URL like this: [`http://www.kaltura.com/index.php/partnerservices2/executeplaylist?playlist_id=1_e387kavu&partner_id=243342&subp_id=24334200&format=8&ks={ks}`](http://www.kaltura.com/index.php/partnerservices2/executeplaylist?playlist_id=1_e387kavu&partner_id=243342&subp_id=24334200&format=8&ks={ks}) I don't know what `subp_id` and `ks` are, but they don't seem to matter. The `format` parameter can be varied to get the playlist in a few different formats.

**Comment by remitamine** [comment]
> @sg0001
> 
> > I tried archiving a playlist from kaltura but it's not working... also tried the non-URL `kaltura:` format with with the IDs in the URL, but it gave me an extractor error and said to report.
> 
> How does one use such a format?

`kaltura:[partner_id]:[entry_id]`, as an example to download the first video in the playlist that you did post you can use:
`youtube-dl kaltura:243342:0_swup5zao`
