### ISSUE TITLE
[tbs.co.jp] ExtractorError: Empty playlist

### ISSUE THREAD

**Issue by shaofreak** [rg3/youtube-dl#12426]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.03.10**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)

Hi,
I can watch the video with firefox.
Don't know if it's really a bug or a site support request: is TBS japan included ?

```
$ youtube-dl -v -f best  "http://www.tbs.co.jp/seriku/movie/player.html?bctid=15atm0082_020"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-f', u'best', u'-v', u'http://www.tbs.co.jp/seriku/movie/player.html?bctid=15atm0082_020']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.03.10
[debug] Python version 2.7.9 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.7
[debug] exe versions: avconv 11.8-6, avprobe 11.8-6, rtmpdump 2.4
[debug] Proxy map: {}
[generic] player: Requesting header
WARNING: Falling back on generic information extractor.
[generic] player: Downloading webpage
[generic] player: Extracting information
[generic] Brightcove video detected.
[download] Downloading playlist: 競技動画｜TBSテレビ：世界陸上北京
[generic] playlist 競技動画｜TBSテレビ：世界陸上北京: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[brightcove:legacy] AQ~~,AAAABl_qIFk~,1zrlVCWCJHPiZuBbgHyJP7aD-Sqnohj-: Downloading playlist information
ERROR: Empty playlist; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 761, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 427, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/brightcove.py", line 290, in _real_extract
    return self._get_playlist_info(player_key[0])
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/brightcove.py", line 333, in _get_playlist_info
    raise ExtractorError('Empty playlist')
ExtractorError: Empty playlist; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

**Comment by yan12125** [comment]
http://www.tbs.co.jp/seriku/movie/player.html?bctid=15atm0082_020 is gone, and other videos on tbs.co.jp are now on YouTube, which can be downloaded. For example:
```
[1]$ youtube-dl -vF "http://www.tbs.co.jp/gomen_aishiteru/"
[debug] System config: []
[debug] User config: ['-v', '--add-metadata', '--xattrs', '-o', '~/tmp/%(title)s-%(id)s.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: ['-vF', 'http://www.tbs.co.jp/gomen_aishiteru/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.07.15
[debug] Git HEAD: d20b1c672
[debug] Python version 3.6.2 - Linux-4.11.9-1-ARCH-x86_64-with-arch-Arch-Linux
[debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2
[debug] Proxy map: {}
[generic] gomen_aishiteru: Requesting header
WARNING: Falling back on generic information extractor.
[generic] gomen_aishiteru: Downloading webpage
[generic] gomen_aishiteru: Extracting information
[download] Downloading playlist: 日曜劇場『ごめん､愛してる』
[generic] playlist 日曜劇場『ごめん､愛してる』: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[youtube] M4vAd_i6_ko: Downloading webpage
[youtube] M4vAd_i6_ko: Downloading video info webpage
[youtube] M4vAd_i6_ko: Extracting video information
[youtube] M4vAd_i6_ko: Downloading MPD manifest
[info] Available formats for M4vAd_i6_ko:
format code  extension  resolution note
249          webm       audio only DASH audio   47k , opus @ 50k, 169.84KiB
139          m4a        audio only DASH audio   48k , m4a_dash container, mp4a.40.5@ 48k (22050Hz), 187.61KiB
250          webm       audio only DASH audio   61k , opus @ 70k, 217.59KiB
171          webm       audio only DASH audio  101k , vorbis@128k, 365.04KiB
251          webm       audio only DASH audio  117k , opus @160k, 415.50KiB
140          m4a        audio only DASH audio  127k , m4a_dash container, mp4a.40.2@128k (44100Hz), 498.42KiB
278          webm       256x144    144p  103k , webm container, vp9, 30fps, video only, 388.92KiB
160          mp4        256x144    DASH video  115k , avc1.4d400c, 30fps, video only, 419.07KiB
242          webm       426x240    240p  232k , vp9, 30fps, video only, 843.26KiB
133          mp4        426x240    DASH video  247k , avc1.4d4015, 30fps, video only, 893.74KiB
243          webm       640x360    360p  417k , vp9, 30fps, video only, 1.44MiB
134          mp4        640x360    DASH video  593k , avc1.4d401e, 30fps, video only, 1.52MiB
244          webm       854x480    480p  760k , vp9, 30fps, video only, 2.35MiB
135          mp4        854x480    DASH video 1159k , avc1.4d401f, 30fps, video only, 2.93MiB
247          webm       1280x720   720p 1505k , vp9, 30fps, video only, 4.46MiB
136          mp4        1280x720   DASH video 2171k , avc1.4d401f, 30fps, video only, 5.62MiB
248          webm       1920x1080  1080p 2540k , vp9, 30fps, video only, 7.91MiB
137          mp4        1920x1080  DASH video 4264k , avc1.640028, 30fps, video only, 11.88MiB
17           3gp        176x144    small , mp4v.20.3, mp4a.40.2@ 24k
36           3gp        320x180    small , mp4v.20.3, mp4a.40.2
43           webm       640x360    medium , vp8.0, vorbis@128k
18           mp4        640x360    medium , avc1.42001E, mp4a.40.2@ 96k
22           mp4        1280x720   hd720 , avc1.64001F, mp4a.40.2@192k (best)
[download] Finished downloading playlist: 日曜劇場『ごめん､愛してる』
```
Feel free to open a new issue if another video is broken.
