### ISSUE TITLE
[DirecTV.com] TV on Demand

### ISSUE THREAD

**Issue by RuneMagle** [rg3/youtube-dl#12432]
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.03.10**
- [ ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [X] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
```
C:\Users\Desktop\youtube-dl>youtube-dl.exe -f best --all-subs https://www.directv.com/tv/Nickelodeon-s-2017-Kids-Choice-Awards-aEtWZkNzcjZlSWJybGQydnpFVzZCdz09 -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'best', '--all-subs', 'https://www.directv.com/tv/Nickelodeon-s-2017-Kids-Choice-Awards-aEtWZkNzcjZlSWJybGQydnpFVzZCdz09', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.03.10
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-83034-gf48b6b8, ffprobe N-83096-g6596b34
[debug] Proxy map: {}
[generic] Nickelodeon-s-2017-Kids-Choice-Awards-aEtWZkNzcjZlSWJybGQydnpFVzZCdz09: Requesting header
WARNING: Could not send HEAD request to https://www.directv.com/tv/Nickelodeon-s-2017-Kids-Choice-Awards-aEtWZkNzcjZlSWJybGQydnpFVzZCdz09: HTTP Error 503: Service Unavailable
[generic] Nickelodeon-s-2017-Kids-Choice-Awards-aEtWZkNzcjZlSWJybGQydnpFVzZCdz09: Downloading webpage
WARNING: Falling back on generic information extractor.
[generic] Nickelodeon-s-2017-Kids-Choice-Awards-aEtWZkNzcjZlSWJybGQydnpFVzZCdz09: Extracting information
ERROR: Unsupported URL: https://www.directv.com/tv/Nickelodeon-s-2017-Kids-Choice-Awards-aEtWZkNzcjZlSWJybGQydnpFVzZCdz09
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpj3l3ckzu\build\youtube_dl\YoutubeDL.py", line 761, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpj3l3ckzu\build\youtube_dl\extractor\common.py", line 427, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpj3l3ckzu\build\youtube_dl\extractor\generic.py", line 2648, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.directv.com/tv/Nickelodeon-s-2017-Kids-Choice-Awards-aEtWZkNzcjZlSWJybGQydnpFVzZCdz09
...
<end of log>
```

---
- Single video: https://www.directv.com/tv/Nickelodeon-s-2017-Kids-Choice-Awards-aEtWZkNzcjZlSWJybGQydnpFVzZCdz09
- Single video: https://www.directv.com/movies/Tangled-Before-Ever-After-Wm5nMTFuNzlyK3k4blJLK3dQMDJ5dz09

---

I don't know if you can add, but would be cool though :)

**Comment by jschwalbe** [comment]
+1

**Comment by RuneMagle** [comment]
remitamine: Where should I send the info?

**Comment by remitamine** [comment]
remitamine[at]gmail[dot]com

**Comment by RuneMagle** [comment]
Account info sent! :)

**Comment by remitamine** [comment]
it asks to install DIRECTV Player which appear to be Windows/Mac only https://support.directv.com/troubleshooting/3679 so i can't help with this(i'm using Arch Linux), as they require to install this software it most likely that they are using a DRM system to protect their videos.

**Comment by RuneMagle** [comment]
I'm not so sure. Don't you have a Virtual Machine or something?

**Comment by jschwalbe** [comment]
![image](https://cloud.githubusercontent.com/assets/8005921/25067137/520af3e2-2208-11e7-8169-014032d27384.png)
I agree it's probably DRMd but maybe someone who knows more about it can try.

**Comment by remitamine** [comment]
tried to use a VM from https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/ before but the system freeze because of low resources.

**Comment by RuneMagle** [comment]
VM's from Microsoft is some bs. Download the full version of Windows from a torrent site or something. Maybe that'll work.

**Comment by remitamine** [comment]
i looked for an official and legal way to try it, the Windows 7 ISO images posted before online are not available anymore, and also i tried to run some of the programs in wine and it didn't work, so i stopped looking for a way to run windows programs in linux(and i don't really need it for most of the things that i work on).

**Comment by jschwalbe** [comment]
You could try sniffing the connection being made from a mobile device, just a thought.

**Comment by jiangjiangflies** [comment]
Hope you can support directv or go.cnn.com with directv provider

**Comment by RuneMagle** [comment]
Sniffing the connection from a mobile device, isn't gonna help youtube-dl.

**Comment by 89z** [comment]
Issue should be closed, unless account can be provided
