### ISSUE TITLE
3player error msg "Unsupported url" for various videos downloadable a few days ago

### ISSUE THREAD

**Issue by wubfud** [rg3/youtube-dl#12450]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.03.10*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.03.10**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

[C:\Documents and Settings\adult\Local Settings\Temp\6\wget-1.16]youtube-dl --ve
rbose http://www.tv3.ie/3player/show/1131/121878/0/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'http://www.tv3.ie/3player/show/1131/12
1878/0/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.03.10
[debug] Python version 3.4.4 - Windows-XP-5.1.2600-SP3
[debug] exe versions: none
[debug] Proxy map: {}
[generic] 0: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 0: Downloading webpage
[generic] 0: Extracting information
ERROR: Unsupported URL: http://www.tv3.ie/3player/show/1131/121878/0/
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpj3l3ckzu\bu
ild\youtube_dl\YoutubeDL.py", line 761, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpj3l3ckzu\bu
ild\youtube_dl\extractor\common.py", line 427, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpj3l3ckzu\bu
ild\youtube_dl\extractor\generic.py", line 2648, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.tv3.ie/3player/sh
ow/1131/121878/0/

[C:\Documents and Settings\adult\Local Settings\Temp\6\wget-1.16]

### Description of your *issue*, suggested solution and other information

Hi
Last week I was able to download some videos from the 3player online catchup service for Ireland's tv3 free-to-air channel, but yesterday every link I tried (including some that worked perfectly last week) came back with the "unsupported url" error msg. The same error occurs now with the previously-successful versions of youtube-dl too so maybe in the last day or two tv3 / 3player have changed something to block it.

Thanks in advance for your help :)

**Comment by wubfud** [comment]
@yan12125 thanks for looking at the issue but I live in Ireland so geo-restricted location was not a problem because I was able to download these video files last week. Just tried today's version and getting the same errmsg :(

**Comment by yan12125** [comment]
FYI: the label indicates that a developer needs a working proxy to debug the problem. I don't know the actual issue here as I have no time to find a good (fast and stable) Ireland proxy.

**Comment by StephenCarroll1982** [comment]
stevie@stevie-Standard-PC-Q35-ICH9-2009:~$ youtube-dl --verbose http://www.tv3.ie/3player/show/712/123633/0/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'http://www.tv3.ie/3player/show/712/123633/0/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.04.09
[debug] Python version 2.7.12 - Linux-4.4.0-71-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 0: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 0: Downloading webpage
[generic] 0: Extracting information
ERROR: Unsupported URL: http://www.tv3.ie/3player/show/712/123633/0/
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1820, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2526, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2515, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: syntax error: line 1, column 0
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 761, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 429, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2682, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.tv3.ie/3player/show/712/123633/0/

**Comment by neilwatest** [comment]
Just to add this is still an issue. Also not all videos on the TV3 website are geo-restricted. 

This is one you can use for testing

http://www.tv3.ie/news_sub_page.php?video_id=126598&locID=1.2.883

Thanks!

**Comment by perrywynkles** [comment]
I think they changed from ts to lots of mp4 segments. I downloaded some mp4s but they would not play and I read there is encryption. I am still able to download videos from about 6 weeks ago. Newer ones give
Could not send HEAD request to http://player.ooyala.com/player/ipad/BqO
WR0YzE650YBh4R46D5sXV44I2zwCp__2200.m3u8: HTTP Error 404: Not Found
[generic] BqOWR0YzE650YBh4R46D5sXV44I2zwCp__2200: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPErro
r
I am in Ireland so not geo restricted. Find it starange you guy had this in May, worked for me till about 6 weeks ago

Hope someone can find a solution. Impossible to watch online or screen record due to ads. Thanks

**Comment by yan12125** [comment]
Not sure. Someone in Ireland may know it better as this website appears to block visitors outside Ireland.

**Comment by perrywynkles** [comment]
I am in Ireland. Is there any info i can give to help, for example the source code from the page?  . I think cyberghost vpn can give  an Irish IP

**Comment by perrywynkles** [comment]
"Most likely an IP is necessary on implementing a new extractor"what does implementing a new extractor mean"?. is there any thing i can do to assist it doing that? Where can i learn about it?

**Comment by yan12125** [comment]
FYI: basic starting tips can be found at https://github.com/rg3/youtube-dl#adding-support-for-a-new-site

**Comment by perrywynkles** [comment]
did anyone fix this for tv3 ireland? perrywynkles@yahoo.com

**Comment by perrywynkles** [comment]
Any update on this?

**Comment by 89z** [comment]
Issue should be closed, URL is dead
