### ISSUE TITLE
Error: Signature Extraction Failed

### ISSUE THREAD

**Issue by AbhirojPanwar** [rg3/youtube-dl#12458]
Hi, 

I am getting the following error using youtube-dl to download a mp3 file from youtube. Any assistance would be helpful. :) 

Output of terminal after executing this command :- `youtube-dl -x --audio-format mp3 URL`

```
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 894, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 808, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 465, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 372, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 352, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1904, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 423, in open
    protocol = req.get_type()
  File "/usr/lib/python2.7/urllib2.py", line 285, in get_type
    raise ValueError, "unknown url type: %s" % self.__original
ValueError: unknown url type: /yts/jsbin/player-en_US-vflsP-F5F/base.js
 (caused by ValueError(u'unknown url type: /yts/jsbin/player-en_US-vflsP-F5F/base.js',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [this FAQ entry](https://yt-dl.org/update) if you have troubles updating.
