### ISSUE TITLE
ON linux when trying to run youtube-dl following error is produced

### ISSUE THREAD

**Issue by sniggy93** [rg3/youtube-dl#12454]
test@test-ThinkCentre-M72e:/etc/apache2/conf-available$ youtube-dl -v https://www.youtube.com/watch?v=o87JLvkWJm8
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=o87JLvkWJm8']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.03.15
[debug] Python version 2.7.6 - Linux-3.13.0-24-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.20-6, avprobe 9.20-6, ffmpeg 9.20-6, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] o87JLvkWJm8: Downloading webpage
[youtube] o87JLvkWJm8: Downloading video info webpage
[youtube] o87JLvkWJm8: Extracting video information
[youtube] o87JLvkWJm8: Downloading MPD manifest
WARNING: Your copy of avconv is outdated and unable to properly mux separate video and audio files, youtube-dl will download single file media. Update avconv to version 10-0 or newer to fix this.
[debug] Invoking downloader on u'https://r12---sn-h557sn7y.googlevideo.com/videoplayback?sparams=dur%2Cei%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&ipbits=0&ratebypass=yes&requiressl=yes&mt=1489556122&initcwndbps=1022500&signature=828421118B48E45B47C5DE68EF076024A8C14DC6.E3455BA41F7DEA6FF7E1DE120E3A78FA6C456B69&upn=G0--SPZTlOc&mime=video%2Fmp4&itag=22&ei=GdPIWNWqIseHoAPGvI3QDA&pl=24&expire=1489577849&mm=31&mn=sn-h557sn7y&id=o-AINiXqMx-jaPes62bEZ37FcFOpRl0kmtxYrVAzYUFl5w&dur=75.488&source=youtube&mv=m&ms=au&ip=59.160.207.94&key=yt6&lmt=1472317934244708'
ERROR: unable to download video data: <urlopen error [Errno 1] _ssl.c:510: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1791, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1733, in dl
    return fd.download(name, info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/common.py", line 356, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/http.py", line 61, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 2093, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/utils.py", line 1083, in https_open
    req, **kwargs)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 1] _ssl.c:510: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol>

**Comment by dstftw** [comment]
Update python.
