### ISSUE TITLE
Error when attempting to download AMC video with no ratings

### ISSUE THREAD

**Issue by tremby** [rg3/youtube-dl#12453]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.03.15**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)

---

```
$ youtube-dl -v "http://www.amc.com/shows/fear-the-walking-dead/video-extras/fear-the-walking-dead-passage-parts-1-8"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://www.amc.com/shows/fear-the-walking-dead/video-extras/fear-the-walking-dead-passage-parts-1-8']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.03.15
[debug] Python version 3.5.2 - Linux-4.4.0-62-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.10-0ubuntu0.16.04.1, ffprobe 2.8.10-0ubuntu0.16.04.1
[debug] Proxy map: {}
[AMCNetworks] fear-the-walking-dead-passage-parts-1-8: Downloading webpage
[AMCNetworks] fear-the-walking-dead-passage-parts-1-8: Downloading JSON metadata
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/__init__.py", line 464, in main
    _real_main(argv)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/__init__.py", line 454, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/YoutubeDL.py", line 1883, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/YoutubeDL.py", line 761, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/common.py", line 427, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/amcnetworks.py", line 71, in _real_extract
    rating = theplatform_metadata['ratings'][0]['rating']
IndexError: list index out of range
```

### Description of your *issue*, suggested solution and other information

It looks like the AMC downloader is expecting ratings to exist, but there might not be any.

**Comment by elasca** [comment]
Which ratings?

**Comment by tremby** [comment]
See in the stack trace. Second-from-last line, where it shows the line of code which is failing:

```python
rating = theplatform_metadata['ratings'][0]['rating']
```

**Comment by elasca** [comment]
i don't know how to correct that, any idea?

**Comment by Hrxn** [comment]
No new version released yet. If you have a working Python installation, you can run from source.

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/13742
