### ISSUE TITLE
ERROR: Unable to extract video url [Pornhub.com] 

### ISSUE THREAD

**Issue by surcouf9** [rg3/youtube-dl#12470]
---
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.03.16**
---
**ISSUE:** youtube-dl won't download videos or playlists from pornhub.com.
```
<begin log>
...
$ youtube-dl -v http://www.pornhub.com/view_video.php?viewkey=1874321084
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'http://www.pornhub.com/view_video.php?viewkey=1874321084']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.03.16
[debug] Python version 2.7.12 - Linux-4.4.0-53-generic-x86_64-with-LinuxMint-18.1-serena
[debug] exe versions: none
[debug] Proxy map: {}
[PornHub] 1874321084: Downloading webpage
[PornHub] 1874321084: Downloading webpage
ERROR: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 761, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 427, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/pornhub.py", line 134, in _real_extract
    'video url', group='url')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 759, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video url
...
<end of log>
```

**Comment by Modryz** [comment]
+1

**Comment by Omega9** [comment]
+1

**Comment by szunyi** [comment]
+1

**Comment by throaway123123** [comment]
Old regexp is: `r'<video[^>]+\bsrc=(["\'])(?P<url>(?:https?:)?//.+?)\1',`

New HTML, e.g., is:

```
        <div class="videoContainer" data-segment="1">
                <video id="html5Player" class="playerhtml5 wide"  poster="" width="100%" preload="metadata" autoplay></video>
...
<script type="text/javascript">
        var rae149003ra58rae149003ra58="&e=149003";var ra1522mp4ra35ra1522mp4ra35="1522.mp" + "4?";var raphncdncra55raphncdncra55=".phncdn.c";var ra4562hc3ra86ra4562hc3ra86="4562&h=c3";var ra490027362ra35ra490027362ra35="490027362";var rahttpbvra40rahttpbvra40="http://bv";var ra1400s1ra87ra1400s1ra87="=1400&s" + "=1";var ra18bra20ra18bra20="18b";var ra8a4fee2fbra67ra8a4fee2fbra67="8a4fee2" + "fb";var rars107rira98rars107rira98="rs=107&ri";var raipa5015ra69raipa5015ra69="ipa=50." + "15";var ra72378152ra69ra72378152ra69="7/23781" + "52";var ra2vl480ra36ra2vl480ra36="2/vl_480_";var ra47b3fa3d5ra19ra47b3fa3d5ra19="47b3fa3" + "d5";var raomvideosra31raomvideosra31="om/videos";var rabc2bd5e20ra31rabc2bd5e20ra31="bc2bd" + "5e20";var ra682k2378ra93ra682k2378ra93="682k_2378";var ra911647ra49ra911647ra49="9.116.47&";var ra2014022ra49ra2014022ra49="/201402/2";var mediastring=/* + ra1400s1ra87ra1400s1ra87 + */rahttpbvra40rahttpbvra40 + /* + ra4562hc3ra86ra4562hc3ra86 + */raphncdncra55raphncdncra55 + /* + rabc2bd5e20ra31rabc2bd5e20ra31 + */raomvideosra31raomvideosra31 + /* + rae149003ra58rae149003ra58 + */ra2014022ra49ra2014022ra49 + /* + ra47b3fa3d5ra19ra47b3fa3d5ra19 + */ra72378152ra69ra72378152ra69 + /* + ra2014022ra49ra2014022ra49 + */ra2vl480ra36ra2vl480ra36 + /* + rabc2bd5e20ra31rabc2bd5e20ra31 + */ra682k2378ra93ra682k2378ra93 + /* + ra1522mp4ra35ra1522mp4ra35 + */ra1522mp4ra35ra1522mp4ra35 + /* + rae149003ra58rae149003ra58 + */raipa5015ra69raipa5015ra69 + /* + raipa5015ra69raipa5015ra69 + */ra911647ra49ra911647ra49 + /* + ra18bra20ra18bra20 + */rars107rira98rars107rira98 + /* + ra2vl480ra36ra2vl480ra36 + */ra1400s1ra87ra1400s1ra87 + /* + ra8a4fee2fbra67ra8a4fee2fbra67 + */ra490027362ra35ra490027362ra35 + /* + ra682k2378ra93ra682k2378ra93 + */rae149003ra58rae149003ra58 + /* + ra911647ra49ra911647ra49 + */ra4562hc3ra86ra4562hc3ra86 + /* + raomvideosra31raomvideosra31 + */ra47b3fa3d5ra19ra47b3fa3d5ra19 + /* + ra47b3fa3d5ra19ra47b3fa3d5ra19 + */ra8a4fee2fbra67ra8a4fee2fbra67 + /* + ra72378152ra69ra72378152ra69 + */rabc2bd5e20ra31rabc2bd5e20ra31 + /* + ra1522mp4ra35ra1522mp4ra35 + */ra18bra20ra18bra20;</script>
```

The URL can be decoded pretty easily but requires parsing javascript.

**Comment by snpwr** [comment]
I created a fix too. Seems you were faster @throawayagain123.

**Comment by throawayagain123** [comment]
:grin:

**Comment by Hrxn** [comment]
BTW, is Pornhub still 720p max, or has anyone found a way for more?

**Comment by szunyi** [comment]
Higher resolution is only for valid subscription user as I know.

**Comment by surcouf9** [comment]
THX for the qyuick fix. Now. How do I apply it?

Surcouf. Newbie with experience.

**Comment by twlz0ne** [comment]
@surcouf9

```sh
$ cd /path/to/youtube-dl--git
$ git pull && git checkout -b pornhub-issue-12470
$ curl -o youtube_dl/extractor/pornhub.py https://raw.githubusercontent.com/snpwr/youtube-dl/07e5efbcb24235a70a28a4eedb88dc1e69656a38/youtube_dl/extractor/pornhub.py
$ python ./setup.py install
$ youtube-dl <url>
```

**Comment by szunyi** [comment]
where will be in the next uptime?

youtube-dl -U
youtube-dl is up-to-date (2017.03.20)

**Comment by throawayagain123** [comment]
@szunyi No fix has been applied to master repository yet.  Once that happens it may make it into an update.

**Comment by zepimp** [comment]
How can I apply this patch to youtube-dl?
p.s. I'm totally new to github. I'm currently using the exe file for youtube-dl.
