### ISSUE TITLE
[aljazeera.net] Support

### ISSUE THREAD

**Issue by 3fey3ugf** [rg3/youtube-dl#12480]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.03.16*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.03.16**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v http://www.aljazeera.net/programs/withoutbounds/2004/6/4/%d9%85%d8%b3%d8%aa%d9%82%d8%a8%d9%84-%d8%a7%d9%84%d9%82%d9%8a%d8%a7%d8%af%d8%a9-%d8%a7%d9%84%d9%81%d9%84%d8%b3%d8%b7%d9%8a%d9%86%d9%8a%d8%a9-%d9%81%d9%8a-%d8%b8%d9%84-%d8%a7%d9%84%d9%85%d8%b7%d8%a7%d9%84%d8%a8-%d8%a8%d8%aa%d8%ba%d9%8a%d9%8a%d8%b1%d9%87%d8%a7
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'http://www.aljazeera.net/programs/withoutbounds/2004/6/4/%d9%85%d8%b3%d8%aa%d9%82%d8%a8%d9%84-%d8%a7%d9%84%d9%82%d9%8a%d8%a7%d8%af%d8%a9-%d8%a7%d9%84%d9%81%d9%84%d8%b3%d8%b7%d9%8a%d9%86%d9%8a%d8%a9-%d9%81%d9%8a-%d8%b8%d9%84-%d8%a7%d9%84%d9%85%d8%b7%d8%a7%d9%84%d8%a8-%d8%a8%d8%aa%d8%ba%d9%8a%d9%8a%d8%b1%d9%87%d8%a7']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.03.16
[debug] Python version 2.7.12 - Linux-4.4.0-45-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: none
[debug] Proxy map: {}
[generic] مستقبل-القيادة-الفلسطينية-في-ظل-المطالب-بتغييرها: Requesting header
WARNING: Falling back on generic information extractor.
[generic] مستقبل-القيادة-الفلسطينية-في-ظل-المطالب-بتغييرها: Downloading webpage
[generic] مستقبل-القيادة-الفلسطينية-في-ظل-المطالب-بتغييرها: Extracting information
ERROR: Unsupported URL: http://www.aljazeera.net/programs/withoutbounds/2004/6/4/%d9%85%d8%b3%d8%aa%d9%82%d8%a8%d9%84-%d8%a7%d9%84%d9%82%d9%8a%d8%a7%d8%af%d8%a9-%d8%a7%d9%84%d9%81%d9%84%d8%b3%d8%b7%d9%8a%d9%86%d9%8a%d8%a9-%d9%81%d9%8a-%d8%b8%d9%84-%d8%a7%d9%84%d9%85%d8%b7%d8%a7%d9%84%d8%a8-%d8%a8%d8%aa%d8%ba%d9%8a%d9%8a%d8%b1%d9%87%d8%a7
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1779, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2526, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2515, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 39, column 98
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 761, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 427, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2649, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.aljazeera.net/programs/withoutbounds/2004/6/4/%d9%85%d8%b3%d8%aa%d9%82%d8%a8%d9%84-%d8%a7%d9%84%d9%82%d9%8a%d8%a7%d8%af%d8%a9-%d8%a7%d9%84%d9%81%d9%84%d8%b3%d8%b7%d9%8a%d9%86%d9%8a%d8%a9-%d9%81%d9%8a-%d8%b8%d9%84-%d8%a7%d9%84%d9%85%d8%b7%d8%a7%d9%84%d8%a8-%d8%a8%d8%aa%d8%ba%d9%8a%d9%8a%d8%b1%d9%87%d8%a7

...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://www.aljazeera.net/programs/withoutbounds/2004/6/4/%d9%85%d8%b3%d8%aa%d9%82%d8%a8%d9%84-%d8%a7%d9%84%d9%82%d9%8a%d8%a7%d8%af%d8%a9-%d8%a7%d9%84%d9%81%d9%84%d8%b3%d8%b7%d9%8a%d9%86%d9%8a%d8%a9-%d9%81%d9%8a-%d8%b8%d9%84-%d8%a7%d9%84%d9%85%d8%b7%d8%a7%d9%84%d8%a8-%d8%a8%d8%aa%d8%ba%d9%8a%d9%8a%d8%b1%d9%87%d8%a7

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information
They use Brightcove.

**Comment by johnhawkinson** [comment]
This is fixed by PR #12178:

```
pb3:youtube-dl jhawk$ git status|head -1
On branch brightcove-12005
pb3:youtube-dl jhawk$ python -m youtube_dl -vs --write-pages 'http://www.aljazeera.net/programs/withoutbounds/2004/6/4/%d9%85%d8%b3%d8%aa%d9%82%d8%a8%d9%84-%d8%a7%d9%84%d9%82%d9%8a%d8%a7%d8%af%d8%a9-%d8%a7%d9%84%d9%81%d9%84%d8%b3%d8%b7%d9%8a%d9%86%d9%8a%d8%a9-%d9%81%d9%8a-%d8%b8%d9%84-%d8%a7%d9%84%d9%85%d8%b7%d8%a7%d9%84%d8%a8-%d8%a8%d8%aa%d8%ba%d9%8a%d9%8a%d8%b1%d9%87%d8%a7'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-vs', u'--write-pages', u'http://www.aljazeera.net/programs/withoutbounds/2004/6/4/%d9%85%d8%b3%d8%aa%d9%82%d8%a8%d9%84-%d8%a7%d9%84%d9%82%d9%8a%d8%a7%d8%af%d8%a9-%d8%a7%d9%84%d9%81%d9%84%d8%b3%d8%b7%d9%8a%d9%86%d9%8a%d8%a9-%d9%81%d9%8a-%d8%b8%d9%84-%d8%a7%d9%84%d9%85%d8%b7%d8%a7%d9%84%d8%a8-%d8%a8%d8%aa%d8%ba%d9%8a%d9%8a%d8%b1%d9%87%d8%a7']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.03.07
[debug] Git HEAD: 34da9a4df
[debug] Python version 2.7.10 - Darwin-14.5.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg git-2017-02-28-7f62368, ffprobe git-2017-02-28-7f62368, rtmpdump 2.4
[debug] Proxy map: {}
[generic] مستقبل-القيادة-الفلسطينية-في-ظل-المطالب-بتغييرها: Requesting header
WARNING: Falling back on generic information extractor.
[generic] مستقبل-القيادة-الفلسطينية-في-ظل-المطالب-بتغييرها: Downloading webpage
[generic] Saving request to __-_-_-_-_http_-_www.aljazeera.net_programs_withoutbounds_2004_6_4_%d9%85%d8%b3%d8%aa%d9%82%d8%a8%d9%84-%d8%a7%d9%84%d9%82%d9%8a%d8%a7%d8%af%d8%a9-%d8%a7%d9%84%d9%81%_5bed9b6a372c8f803c7dedb7d24fb221.dump
[generic] مستقبل-القيادة-الفلسطينية-في-ظل-المطالب-بتغييرها: Extracting information
[generic] Brightcove (new) video detected.
[download] Downloading playlist: مستقبل القيادة الفلسطينية في ظل المطالب بتغييرها
[generic] playlist مستقبل القيادة الفلسطينية في ظل المطالب بتغييرها: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[brightcove:new] 1313238276001: Downloading webpage
[brightcove:new] Saving request to 1313238276001_http_-_players.brightcove.net_665001584001_BJeiBqmye_default_index.min.js.dump
[brightcove:new] 1313238276001: Downloading JSON metadata
[brightcove:new] Saving request to 1313238276001_https_-_edge.api.brightcove.com_playback_v1_accounts_665001584001_videos_1313238276001.dump
[download] Finished downloading playlist: مستقبل القيادة الفلسطينية في ظل المطالب بتغييرها
```
