### ISSUE TITLE
[brightcove] Can't download a video from un.org

### ISSUE THREAD

**Issue by xlfjn** [rg3/youtube-dl#12482]
Hello,
I want to download a video clip using youtube-dl from www.un.org/chinese/News/story.asp?NewsID=27724
However, it didn't work:
```
$ youtube-dl -v http://www.un.org/chinese/News/story.asp?NewsID=27724
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://www.un.org/chinese/News/story.asp?NewsID=27724']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.03.16
[debug] Python version 3.6.0 - Linux-4.10.3-1-ARCH-i686-with-arch
[debug] exe versions: ffmpeg 3.2.4, ffprobe 3.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[generic] story: Requesting header
WARNING: Falling back on generic information extractor.
[generic] story: Downloading webpage
[generic] story: Extracting information
ERROR: Unsupported URL: http://www.un.org/chinese/News/story.asp?NewsID=27724
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 761, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 427, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/generic.py", line 2628, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.un.org/chinese/News/story.asp?NewsID=27724
```
Then, I tried the link to the embedded Brightcove player. It didn't work either.
```
$ youtube-dl -v http://link.brightcove.com/services/player/bcpid1722935254001/?bctid=5360463607001
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://link.brightcove.com/services/player/bcpid1722935254001/?bctid=5360463607001']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.03.16
[debug] Python version 3.6.0 - Linux-4.10.3-1-ARCH-i686-with-arch
[debug] exe versions: ffmpeg 3.2.4, ffprobe 3.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[brightcove:legacy] 5360463607001: Downloading webpage
ERROR: brightcove said: A valid ID was not sent for this player.
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 761, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 427, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/brightcove.py", line 281, in _real_extract
    videoPlayer[0], query, referer=referer)
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/brightcove.py", line 304, in _get_video_info
    'brightcove said: %s' % error_msg, expected=True)
youtube_dl.utils.ExtractorError: brightcove said: A valid ID was not sent for this player.
```

**Comment by 3fey3ugf** [comment]
> https://github.com/rg3/youtube-dl/issues/12480#issuecomment-287552973

**Comment by johnhawkinson** [comment]
> https://github.com/rg3/youtube-dl/issues/12480#issuecomment-287552973

Err, no, this is not same as 12480, which is fixed in 12178 (not yet merged).
If you had a different question, not sure what it was.

**Comment by yan12125** [comment]
Thanks for the report and sorry for the delay. Such Brightcove videos will be supported in the next version.
