### ISSUE TITLE
EOFError: Compressed file ended before the end-of-stream marker was reached

### ISSUE THREAD

**Issue by V1de0Lovr** [rg3/youtube-dl#12483]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.03.16**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ x] Bug report (encountered problems with youtube-dl)

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:
```
youtube-dl https://www.youtube.com/watch?v=f44XUFUhAMc -v
[debug] System config: []
[debug] User config: ['--ffmpeg-location', 'C:\\Program Files\\FFmpeg\\ffmpeg.exe']
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=f44XUFUhAMc', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.03.16
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg 3.2.4, ffprobe 3.2.4
[debug] Proxy map: {}
[youtube] f44XUFUhAMc: Downloading webpage
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpvd2cwzkd\build\youtube_dl\__init__.py", line 464, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpvd2cwzkd\build\youtube_dl\__init__.py", line 454, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpvd2cwzkd\build\youtube_dl\YoutubeDL.py", line 1883, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpvd2cwzkd\build\youtube_dl\YoutubeDL.py", line 761, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpvd2cwzkd\build\youtube_dl\extractor\common.py", line 427, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpvd2cwzkd\build\youtube_dl\extractor\youtube.py", line 1291, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpvd2cwzkd\build\youtube_dl\extractor\common.py", line 618, in _download_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpvd2cwzkd\build\youtube_dl\extractor\common.py", line 525, in _download_webpage_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpvd2cwzkd\build\youtube_dl\extractor\common.py", line 496, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpvd2cwzkd\build\youtube_dl\YoutubeDL.py", line 2093, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpvd2cwzkd\build\youtube_dl\utils.py", line 974, in http_response
  File "C:\Python\Python34\lib\gzip.py", line 360, in read
  File "C:\Python\Python34\lib\gzip.py", line 449, in _read
  File "C:\Python\Python34\lib\gzip.py", line 482, in _read_eof
  File "C:\Python\Python34\lib\gzip.py", line 286, in _read_exact
EOFError: Compressed file ended before the end-of-stream marker was reached
...
<end of log>
```

### Description of your *issue*, suggested solution and other information

youtube-dl used to work great on this computer but always errors out now. I tried several older versions but the problem seems to be something with my computer. It works fine on another computer in my house. Googling solutions for this python error indicates that a partially downloaded file should be deleted, but I can't find such a file. I have emptied my temp folders but this does not help. Downloading the same video from Youtube works find on my other computer, and 4K Video Downloader works fine on this computer where youtube-dl does not.

**Comment by dstftw** [comment]
1. Does it work with other sites?
2. Try disabling/adding exclusion to windows defender.
3. Post the output with `--print-traffic`.

**Comment by V1de0Lovr** [comment]
1. Yes, it does work with teamcoco.com, which appears to use ffmpeg for downloading.
2. Bitdefender is the firewall. I added a rule for youtube-dl and later disabled it, but neither worked.
3. I can't see any difference with -print-traffic so I presume its not getting any download at all.
4. I tried a command prompt instead of PowerShell and got it to download from Youtube once, but the audio would not play despite there being audio in the file. After changing to a different drive, it no longer downloads anything in a command prompt either.

PS E:\Encode> youtube-dl https://www.youtube.com/watch?v=f44XUFUhAMc -v --print-traffic
[debug] System config: []
[debug] User config: ['--ffmpeg-location', 'C:\\Program Files\\FFmpeg\\ffmpeg.exe']
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=f44XUFUhAMc', '-v', '--print-traffic']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.03.16
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg 3.2.4, ffprobe 3.2.4
[debug] Proxy map: {}
[youtube] f44XUFUhAMc: Downloading webpage
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpvd2cwzkd\build\youtube_dl\__init__.py", line 464, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpvd2cwzkd\build\youtube_dl\__init__.py", line 454, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpvd2cwzkd\build\youtube_dl\YoutubeDL.py", line 1883, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpvd2cwzkd\build\youtube_dl\YoutubeDL.py", line 761, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpvd2cwzkd\build\youtube_dl\extractor\common.py", line 427, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpvd2cwzkd\build\youtube_dl\extractor\youtube.py", line 1291, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpvd2cwzkd\build\youtube_dl\extractor\common.py", line 618, in _download_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpvd2cwzkd\build\youtube_dl\extractor\common.py", line 525, in _download_webpage_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpvd2cwzkd\build\youtube_dl\extractor\common.py", line 496, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpvd2cwzkd\build\youtube_dl\YoutubeDL.py", line 2093, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpvd2cwzkd\build\youtube_dl\utils.py", line 974, in http_response
  File "C:\Python\Python34\lib\gzip.py", line 360, in read
  File "C:\Python\Python34\lib\gzip.py", line 449, in _read
  File "C:\Python\Python34\lib\gzip.py", line 482, in _read_eof
  File "C:\Python\Python34\lib\gzip.py", line 286, in _read_exact
EOFError: Compressed file ended before the end-of-stream marker was reached

**Comment by joeyh** [comment]
I can reproduce this every time, over an Exede Satellite internet connection. There is a transparent proxy, which causes this problem with http urls. Does not affect https urls. I have not seen it cause problems with other programs, only youtube-dl.

**Comment by ElonSatoshi** [comment]
Another Exede user here, from 2018. They must've started doing some shit again. I turned on my VPN, it seems to have fixed the issue. Avoid Exede, maybe someday I'll convince my mom to try Centurylink.
