### ISSUE TITLE
"unknown url type" Error on YouTube Video

### ISSUE THREAD

**Issue by ChaseyLain** [rg3/youtube-dl#12492]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.03.16**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Bug report (encountered problems with youtube-dl)
---
```
D:\Downloads\ffmpeg>youtube-dl.exe --verbose https://www.youtube.com/watch?v=ud_jVgBurJg
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=ud_jVgBurJg']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.07.13
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-80906-gd5edb6c
[debug] Proxy map: {}
[youtube] ud_jVgBurJg: Downloading webpage
[youtube] ud_jVgBurJg: Downloading video info webpage
[youtube] ud_jVgBurJg: Extracting video information
[youtube] {43} signature length 46.40, html5 player en_US-vflk2jRfn
[youtube] ud_jVgBurJg: Downloading player /yts/jsbin/player-en_US-vflk2jRfn/base.js
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc5h2pb0m\build\youtube_dl\extractor\youtube.py", line 1006, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc5h2pb0m\build\youtube_dl\extractor\youtube.py", line 920, in _extract_signature_function
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc5h2pb0m\build\youtube_dl\extractor\common.py", line 507, in _download_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc5h2pb0m\build\youtube_dl\extractor\common.py", line 414, in _download_webpage_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc5h2pb0m\build\youtube_dl\extractor\common.py", line 394, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc5h2pb0m\build\youtube_dl\YoutubeDL.py", line 1954, in urlopen
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc5h2pb0m\build\youtube_dl\utils.py", line 499, in sanitized_Request
  File "C:\Python\Python34\lib\urllib\request.py", line 267, in __init__
  File "C:\Python\Python34\lib\urllib\request.py", line 293, in full_url
  File "C:\Python\Python34\lib\urllib\request.py", line 322, in _parse
ValueError: unknown url type: '/yts/jsbin/player-en_US-vflk2jRfn/base.js'
 (caused by ValueError("unknown url type: '/yts/jsbin/player-en_US-vflk2jRfn/base.js'",)); please report this issue on https://yt-dl.org/bug . Make sure you are
 using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc5h2pb0m\build\youtube_dl\extractor\youtube.py", line 1006, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc5h2pb0m\build\youtube_dl\extractor\youtube.py", line 920, in _extract_signature_function
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc5h2pb0m\build\youtube_dl\extractor\common.py", line 507, in _download_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc5h2pb0m\build\youtube_dl\extractor\common.py", line 414, in _download_webpage_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc5h2pb0m\build\youtube_dl\extractor\common.py", line 394, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc5h2pb0m\build\youtube_dl\YoutubeDL.py", line 1954, in urlopen
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc5h2pb0m\build\youtube_dl\utils.py", line 499, in sanitized_Request
  File "C:\Python\Python34\lib\urllib\request.py", line 267, in __init__
  File "C:\Python\Python34\lib\urllib\request.py", line 293, in full_url
  File "C:\Python\Python34\lib\urllib\request.py", line 322, in _parse
ValueError: unknown url type: '/yts/jsbin/player-en_US-vflk2jRfn/base.js'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc5h2pb0m\build\youtube_dl\extractor\youtube.py", line 1006, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc5h2pb0m\build\youtube_dl\extractor\youtube.py", line 920, in _extract_signature_function
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc5h2pb0m\build\youtube_dl\extractor\common.py", line 507, in _download_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc5h2pb0m\build\youtube_dl\extractor\common.py", line 414, in _download_webpage_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc5h2pb0m\build\youtube_dl\extractor\common.py", line 394, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc5h2pb0m\build\youtube_dl\YoutubeDL.py", line 1954, in urlopen
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc5h2pb0m\build\youtube_dl\utils.py", line 499, in sanitized_Request
  File "C:\Python\Python34\lib\urllib\request.py", line 267, in __init__
  File "C:\Python\Python34\lib\urllib\request.py", line 293, in full_url
  File "C:\Python\Python34\lib\urllib\request.py", line 322, in _parse
ValueError: unknown url type: '/yts/jsbin/player-en_US-vflk2jRfn/base.js'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc5h2pb0m\build\youtube_dl\YoutubeDL.py", line 681, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc5h2pb0m\build\youtube_dl\extractor\common.py", line 347, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc5h2pb0m\build\youtube_dl\extractor\youtube.py", line 1579, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc5h2pb0m\build\youtube_dl\extractor\youtube.py", line 1016, in _decrypt_signature
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc5h2pb0m\build\youtube_dl\extractor\youtube.py", line 1006, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc5h2pb0m\build\youtube_dl\extractor\youtube.py", line 920, in _extract_signature_function
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc5h2pb0m\build\youtube_dl\extractor\common.py", line 507, in _download_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc5h2pb0m\build\youtube_dl\extractor\common.py", line 414, in _download_webpage_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc5h2pb0m\build\youtube_dl\extractor\common.py", line 394, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc5h2pb0m\build\youtube_dl\YoutubeDL.py", line 1954, in urlopen
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc5h2pb0m\build\youtube_dl\utils.py", line 499, in sanitized_Request
  File "C:\Python\Python34\lib\urllib\request.py", line 267, in __init__
  File "C:\Python\Python34\lib\urllib\request.py", line 293, in full_url
  File "C:\Python\Python34\lib\urllib\request.py", line 322, in _parse
ValueError: unknown url type: '/yts/jsbin/player-en_US-vflk2jRfn/base.js'
 (caused by ValueError("unknown url type: '/yts/jsbin/player-en_US-vflk2jRfn/base.js'",)); please report this issue on https://yt-dl.org/bug . Make sure you are
 using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
Did not find a similar bug report. Sorry if one is already there, Not familiar with GitHub. Keep up great the great work!

**Comment by ChaseyLain** [comment]
sorry, i got fooled by the update process not working somehow :(
