### ISSUE TITLE
Hallmark Channel

### ISSUE THREAD

**Issue by tv21** [rg3/youtube-dl#12527]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.03.22*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.03.22**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
~$ youtube-dl http://www.hallmarkchanneleverywhere.com/Series/Episode/Words+from+the+Heart -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'http://www.hallmarkchanneleverywhere.com/Series/Episode/Words+from+the+Heart', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.03.22
[debug] Python version 2.7.9 - Linux-3.16.0-4-686-pae-i686-with-debian-8.7
[debug] exe versions: avprobe 11.8-6, ffmpeg N-83692-gb8a7dcbde2-static, ffprobe N-83692-gb8a7dcbde2-static, rtmpdump 2.4
[debug] Proxy map: {}
[generic] Words+from+the+Heart: Requesting header
WARNING: Falling back on generic information extractor.
[generic] Words+from+the+Heart: Downloading webpage
[generic] Words+from+the+Heart: Extracting information
ERROR: Unsupported URL: http://www.hallmarkchanneleverywhere.com/Series/Episode/Words+from+the+Heart
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1790, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2526, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2515, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 20, column 31
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 761, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 428, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2653, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.hallmarkchanneleverywhere.com/Series/Episode/Words+from+the+Heart
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://www.hallmarkchanneleverywhere.com/Series/Episode/Words+from+the+Heart
- Single video: http://www.hallmarkchanneleverywhere.com/Series/Episode/5132
- Single video: http://www.hallmarkchanneleverywhere.com/Movies/Details/All%2527s%2bFair%2bin%2bLove%2band%2bAdvertising#

---

### Description of your *issue*, suggested solution and other information

Please add support for The Hallmark Channel (http://www.hallmarkchannel.com/)

**Comment by yan12125** [comment]
All links are dead.

> Sorry, an error occurred while processing your request.

Any new examples?

**Comment by tv21** [comment]
This link is good until May 22:  http://www.hallmarkchanneleverywhere.com/Series/Episode/Heart+of+a+Secret

**Comment by tindivall** [comment]
@tv21  Evidently I am destined to follow in your footsteps. I am also looking for hallmark ability. Did you ever figure anything out on this?

**Comment by ToniWonKanobi** [comment]
> @tv21 Evidently I am destined to follow in your footsteps. I am also looking for hallmark ability. Did you ever figure anything out on this?

I am honestly surprised another human out there was looking for the ability to use youtube-dl with the Hallmark Channel. My wife will forever love me if this is possible.

**Comment by ToniWonKanobi** [comment]
Yeahhh 😢 

```
Anthonys-MacBook:~ Anthony$ youtube-dl http://www.hallmarkchanneleverywhere.com/#/movies/A+Very+Happy+Yule+Log
[generic] A+Very+Happy+Yule+Log: Requesting header
WARNING: Falling back on generic information extractor.
[generic] A+Very+Happy+Yule+Log: Downloading webpage
[generic] A+Very+Happy+Yule+Log: Extracting information
NOT TEACHABLE
ERROR: Unsupported URL: http://www.hallmarkchanneleverywhere.com/#/movies/A+Very+Happy+Yule+Log
Anthonys-MacBook:~ Anthony$ 
```

**Comment by ProgrammerAKL** [comment]
- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2019.11.05**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones


## Example URLs



- Single video: http://www.hallmarkchanneleverywhere.com/#/Home+%26+Family/8044
- Playlist: http://www.hallmarkchanneleverywhere.com/#/Home+%26+Family/all


## Description

m3u8 paths should be relatively straightforward to find
