### ISSUE TITLE
Unable to download Private YouTube video with correct username/password

### ISSUE THREAD

**Issue by vkchan** [rg3/youtube-dl#12520]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.03.22*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.03.22**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

I'm getting an error when I try to download a private youtube video that I have subscribed to. I am certain that my username and password are correct. I have reviewed the previous closed issue and added double quote around the email address/username but it still doesn't work.

Here are my error messages. Any suggestion?

```
ubuntu:~$ youtube-dl -f bestvideo+bestaudio -ciw -o "/videos/%(title)s.%(ext)s" -u "USERNAME@gmail.com" -p "PASSWORD" --ffmpeg-location /usr/bin https://www.youtube.com/watch?v=VIDEOCODE --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-f', u'bestvideo+bestaudio', u'-ciw', u'-o', u'/videos/%(title)s.%(ext)s', u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'--ffmpeg-location', u'/usr/bin', u'https://www.youtube.com/watch?v=VIDEOCODE', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.03.22
[debug] Python version 2.7.12 - Linux-4.4.0-66-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] Downloading login page
[youtube] Logging in
[youtube] VIDEOCODE: Downloading webpage
[youtube] VIDEOCODE: Downloading video info webpage
ERROR: lesiYZMTczk: YouTube said: This video is private.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 761, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 428, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 1392, in _real_extract
    expected=True, video_id=video_id)
ExtractorError: VIDEOCODE: YouTube said: This video is private.

```
---

**Comment by vkchan** [comment]
Solved. Not a youtube-dl issue. It turns out it was because my gmail is linked to more than one youtube accounts, and the youtube account that was entitled was not the default one. When I set it to be the default  account, youtube-dl works perfectly. Thanks.
