### ISSUE TITLE
Unsupported 

### ISSUE THREAD

**Issue by rajucomp** [rg3/youtube-dl#12529]
I am getting unsupported url for the following site.

**Comment by rajucomp** [comment]
youtube-dl -v --prefer-ffmpeg https://india.viu.com/en/media/1126286865
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--prefer-ffmpeg', u'https://india.viu.com/en/media/1126286865']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.03.20
[debug] Python version 2.7.12 - Linux-4.4.0-66-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 2.8.11-0ubuntu0.16.04.1, avprobe 2.8.11-0ubuntu0.16.04.1, ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1, rtmpdump 2.4
[debug] Proxy map: {'ftp': 'http://edcguest:edcguest@localhost:8080/" ', 'http': 'http://edcguest:edcguest@localhost:8080/', 'https': 'http://edcguest:edcguest@localhost:8080/" ', 'no': 'localhost,127.0.0.1,localaddress,.localdomain.com" '}
[generic] 1126286865: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 1126286865: Downloading webpage
[generic] 1126286865: Extracting information
ERROR: Unsupported URL: https://india.viu.com/en/media/1126286865
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 1779, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/compat.py", line 2526, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/compat.py", line 2515, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 4, column 4
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 761, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 428, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 2642, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://india.viu.com/en/media/1126286865
