### ISSUE TITLE
Error downloading from au.tv.yahoo.com

### ISSUE THREAD

**Issue by Splinterverse** [rg3/youtube-dl#12540]
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.03.24**
- [X ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X ] Bug report (encountered problems with youtube-dl)

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
C:\youtube-dl-master>youtube-dl --verbose --proxy "" "https://au.tv.yahoo.com/pl
us7/home-and-away-the-early-years/-/watch/34706441/home-and-away-the-early-years
-mon-20-mar/" --force-generic-extractor
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--proxy', '', 'https://au.tv.yahoo.com
/plus7/home-and-away-the-early-years/-/watch/34706441/home-and-away-the-early-ye
ars-mon-20-mar/', '--force-generic-extractor']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.03.24
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-69233-g1f13348, ffprobe N-80234-g49b0246, rtmpdum
p 2.5
[debug] Proxy map: {}
[generic] home-and-away-the-early-years-mon-20-mar: Requesting header
WARNING: Forcing on generic information extractor.
[generic] home-and-away-the-early-years-mon-20-mar: Downloading webpage
[generic] home-and-away-the-early-years-mon-20-mar: Extracting information
[download] Downloading playlist: Home and Away The Early Years: Mon 20 Mar - wat
ch now
[generic] playlist Home and Away The Early Years: Mon 20 Mar - watch now: Collec
ted 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[brightcove:new] 5364757841001: Downloading webpage
[brightcove:new] 5364757841001: Downloading JSON metadata
ERROR: Access to this resource is forbidden by access policy.
You might want to use a VPN or a proxy server (with --proxy) to workaround.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp7c11i4w7\bu
ild\youtube_dl\extractor\common.py", line 497, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp7c11i4w7\bu
ild\youtube_dl\YoutubeDL.py", line 2094, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_defau
lt
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp7c11i4w7\bu
ild\youtube_dl\extractor\brightcove.py", line 551, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp7c11i4w7\bu
ild\youtube_dl\extractor\common.py", line 651, in _download_json
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp7c11i4w7\bu
ild\youtube_dl\extractor\common.py", line 619, in _download_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp7c11i4w7\bu
ild\youtube_dl\extractor\common.py", line 526, in _download_webpage_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp7c11i4w7\bu
ild\youtube_dl\extractor\common.py", line 506, in _request_webpage
youtube_dl.utils.ExtractorError: Unable to download JSON metadata: HTTP Error 40
3: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.
org/bug . Make sure you are using the latest version; type  youtube-dl -U  to up
date. Be sure to call youtube-dl with the --verbose flag and include its complet
e output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp7c11i4w7\bu
ild\youtube_dl\extractor\common.py", line 497, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp7c11i4w7\bu
ild\youtube_dl\YoutubeDL.py", line 2094, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_defau
lt
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp7c11i4w7\bu
ild\youtube_dl\extractor\brightcove.py", line 551, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp7c11i4w7\bu
ild\youtube_dl\extractor\common.py", line 651, in _download_json
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp7c11i4w7\bu
ild\youtube_dl\extractor\common.py", line 619, in _download_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp7c11i4w7\bu
ild\youtube_dl\extractor\common.py", line 526, in _download_webpage_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp7c11i4w7\bu
ild\youtube_dl\extractor\common.py", line 506, in _request_webpage
youtube_dl.utils.ExtractorError: Unable to download JSON metadata: HTTP Error 40
3: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.
org/bug . Make sure you are using the latest version; type  youtube-dl -U  to up
date. Be sure to call youtube-dl with the --verbose flag and include its complet
e output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp7c11i4w7\bu
ild\youtube_dl\YoutubeDL.py", line 761, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp7c11i4w7\bu
ild\youtube_dl\extractor\common.py", line 428, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp7c11i4w7\bu
ild\youtube_dl\extractor\brightcove.py", line 558, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp7c11i4w7\bu
ild\youtube_dl\extractor\common.py", line 702, in raise_geo_restricted
youtube_dl.utils.GeoRestrictedError: Access to this resource is forbidden by acc
ess policy.


---

### Description of your *issue*, suggested solution and other information

I am a new user to this software. I just downloaded the Windows .EXE today. The only thing I'm unsure of is the proxy. I used --proxy assuming that would populate the proxy information for australia. Is there something else I need to do to get the proxy going? (I switched to youtube-dl today because the program I normally use to download these is not working; I'm guessing yahoo changed something since last week). The --force-generic-extractor was used based on another thread I saw on here.

**Comment by Splinterverse** [comment]
Any help?

**Comment by remitamine** [comment]
this video is geo-restricted to australia, as error said you have to provide an australian proxy or us a vpn to be able to download the video.
```
youtube-dl https://au.tv.yahoo.com/plus7/home-and-away-the-early-years/-/watch/34706441/home-and-away-the-early-years-mon-20-mar/
[Yahoo] home-and-away-the-early-years-mon: Downloading webpage
[brightcove:new] 5364757841001: Downloading webpage
[brightcove:new] 5364757841001: Downloading JSON metadata
[brightcove:new] 5364757841001: Downloading m3u8 information
[brightcove:new] 5364757841001: Downloading MPD manifest
[brightcove:new] 5364757841001: Downloading MPD manifest
[brightcove:new] 5364757841001: Downloading MPD manifest
[brightcove:new] 5364757841001: Downloading MPD manifest
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 135
[download] Destination: Home and Away The Early Years - Mon 20 Mar-5364757841001.mp4
[download]   1.1% of ~357.52MiB at 356.89KiB/s ETA 24:03
```
