### ISSUE TITLE
possible bug

### ISSUE THREAD

**Issue by pb-colsen** [rg3/youtube-dl#12567]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.03.26*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.03.26**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/Users/colsen/anaconda/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 987, in _decrypt_signature
    video_id, player_url, s
  File "/Users/colsen/anaconda/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 901, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "/Users/colsen/anaconda/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 507, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "/Users/colsen/anaconda/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 414, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "/Users/colsen/anaconda/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 394, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/Users/colsen/anaconda/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 1997, in urlopen
    req = sanitized_Request(req)
  File "/Users/colsen/anaconda/lib/python3.5/site-packages/youtube_dl/utils.py", line 501, in sanitized_Request
    return compat_urllib_request.Request(sanitize_url(url), *args, **kwargs)
  File "/Users/colsen/anaconda/lib/python3.5/urllib/request.py", line 269, in __init__
    self.full_url = url
  File "/Users/colsen/anaconda/lib/python3.5/urllib/request.py", line 295, in full_url
    self._parse()
  File "/Users/colsen/anaconda/lib/python3.5/urllib/request.py", line 324, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/yts/jsbin/player-en_US-vflEzRdnB/base.js'
 (caused by ValueError("unknown url type: '/yts/jsbin/player-en_US-vflEzRdnB/base.js'",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/Users/colsen/anaconda/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 987, in _decrypt_signature
    video_id, player_url, s
  File "/Users/colsen/anaconda/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 901, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "/Users/colsen/anaconda/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 507, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "/Users/colsen/anaconda/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 414, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "/Users/colsen/anaconda/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 394, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/Users/colsen/anaconda/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 1997, in urlopen
    req = sanitized_Request(req)
  File "/Users/colsen/anaconda/lib/python3.5/site-packages/youtube_dl/utils.py", line 501, in sanitized_Request
    return compat_urllib_request.Request(sanitize_url(url), *args, **kwargs)
  File "/Users/colsen/anaconda/lib/python3.5/urllib/request.py", line 269, in __init__
    self.full_url = url
  File "/Users/colsen/anaconda/lib/python3.5/urllib/request.py", line 295, in full_url
    self._parse()
  File "/Users/colsen/anaconda/lib/python3.5/urllib/request.py", line 324, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/yts/jsbin/player-en_US-vflEzRdnB/base.js'
Traceback (most recent call last):
  File "/Users/colsen/anaconda/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 987, in _decrypt_signature
    video_id, player_url, s
  File "/Users/colsen/anaconda/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 901, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "/Users/colsen/anaconda/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 507, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "/Users/colsen/anaconda/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 414, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "/Users/colsen/anaconda/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 394, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/Users/colsen/anaconda/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 1997, in urlopen
    req = sanitized_Request(req)
  File "/Users/colsen/anaconda/lib/python3.5/site-packages/youtube_dl/utils.py", line 501, in sanitized_Request
    return compat_urllib_request.Request(sanitize_url(url), *args, **kwargs)
  File "/Users/colsen/anaconda/lib/python3.5/urllib/request.py", line 269, in __init__
    self.full_url = url
  File "/Users/colsen/anaconda/lib/python3.5/urllib/request.py", line 295, in full_url
    self._parse()
  File "/Users/colsen/anaconda/lib/python3.5/urllib/request.py", line 324, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/yts/jsbin/player-en_US-vflEzRdnB/base.js'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/colsen/anaconda/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 691, in extract_info
    ie_result = ie.extract(url)
  File "/Users/colsen/anaconda/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 347, in extract
    return self._real_extract(url)
  File "/Users/colsen/anaconda/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1560, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/Users/colsen/anaconda/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 997, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/Users/colsen/anaconda/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 987, in _decrypt_signature
    video_id, player_url, s
  File "/Users/colsen/anaconda/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 901, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "/Users/colsen/anaconda/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 507, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "/Users/colsen/anaconda/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 414, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "/Users/colsen/anaconda/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 394, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/Users/colsen/anaconda/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 1997, in urlopen
    req = sanitized_Request(req)
  File "/Users/colsen/anaconda/lib/python3.5/site-packages/youtube_dl/utils.py", line 501, in sanitized_Request
    return compat_urllib_request.Request(sanitize_url(url), *args, **kwargs)
  File "/Users/colsen/anaconda/lib/python3.5/urllib/request.py", line 269, in __init__
    self.full_url = url
  File "/Users/colsen/anaconda/lib/python3.5/urllib/request.py", line 295, in full_url
    self._parse()
  File "/Users/colsen/anaconda/lib/python3.5/urllib/request.py", line 324, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/yts/jsbin/player-en_US-vflEzRdnB/base.js'
 (caused by ValueError("unknown url type: '/yts/jsbin/player-en_US-vflEzRdnB/base.js'",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [this FAQ entry](https://yt-dl.org/update) if you have troubles updating.
