### ISSUE TITLE
[cloudy] unable to download video data: HTTP Error 403

### ISSUE THREAD

**Issue by best-job** [rg3/youtube-dl#12606]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.03.26**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) 
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v http://www.cloudy.ec/v/1b2368a59f8ff
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://www.cloudy.ec/v/1b2368a59f8ff']
[debug] Encodings: locale cp1256, fs mbcs, out cp720, pref cp1256
[debug] youtube-dl version 2017.03.26
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: none
[debug] Proxy map: {}
[Cloudy] 1b2368a59f8ff: Downloading webpage
[Cloudy] 1b2368a59f8ff: Downloading webpage
[debug] Invoking downloader on 'http://185.176.193.243/dl/bbb45536315c6d2115e8a27bc8a5107b/58dd7ce8/oo7152ba147c1bef7ac25bb871aaa5c6fa.mp4'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpje2_cfdl\build\youtube_dl\YoutubeDL.py", line 1791, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpje2_cfdl\build\youtube_dl\YoutubeDL.py", line 1733, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpje2_cfdl\build\youtube_dl\downloader\common.py", line 356, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpje2_cfdl\build\youtube_dl\downloader\http.py", line 61, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpje2_cfdl\build\youtube_dl\YoutubeDL.py", line 2094, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden
<end of log>
```

---
- Single video: http://www.cloudy.ec/v/1b2368a59f8ff
---

**Comment by dstftw** [comment]
```
PS C:\dev\youtube-dl\master> py -3.6 .\youtube_dl\__main__.py http://www.cloudy.ec/v/1b2368a59f8ff
[Cloudy] 1b2368a59f8ff: Downloading webpage
[Cloudy] 1b2368a59f8ff: Downloading webpage
[download] Resuming download at byte 717824
[download] Destination: RebelThiefWhoStolethePeopleE14As2tv.comHD-1b2368a59f8ff.mp4
[download]   0.2% of 388.12MiB at 145.18KiB/s ETA 45:32
ERROR: Interrupted by user
```

**Comment by best-job** [comment]
Some videos do not work
Ex :
http://www.cloudy.ec/v/f0ecde94c057a
http://www.cloudy.ec/v/791f4dad90ffb

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://www.cloudy.ec/v/791f4dad90ffb']
[debug] Encodings: locale cp1256, fs mbcs, out cp720, pref cp1256
[debug] youtube-dl version 2017.04.02
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: none
[debug] Proxy map: {}
[Cloudy] 791f4dad90ffb: Downloading webpage
[Cloudy] 791f4dad90ffb: Downloading webpage
[debug] Invoking downloader on 'http://185.176.193.151/dl/f7257b132fac03b598190691a9b5b4a4/58e222bb/ff757c77b1827cf0375ddb45b83f020951.mp4'
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpol0xsjvy\build\youtube_dl\YoutubeDL.py", line 1797, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpol0xsjvy\build\youtube_dl\YoutubeDL.py", line 1739, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpol0xsjvy\build\youtube_dl\downloader\common.py", line 356, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpol0xsjvy\build\youtube_dl\downloader\http.py", line 61, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpol0xsjvy\build\youtube_dl\YoutubeDL.py", line 2100, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found
