### ISSUE TITLE
packtpub site support

### ISSUE THREAD

**Issue by jaan143** [rg3/youtube-dl#12610]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.03.26*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2017.03.26**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

can you please add this website to download video courses which they allow to watch online
packtpub.com

course link
https://www.packtpub.com/mapt/video/web-development/9781787122215

**Comment by jaan143** [comment]
is it working with this file ?
i put these two changes in my folder but i am getting this error
PS C:\Users\vicky\downloads> youtube-dl --verbose -o '~/downloads/%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s' h
ttps://www.packtpub.com/mapt/video/web-development/9781787122215 --username 123@gmail.com --password 123
Traceback (most recent call last):
  File "c:\users\vicky\appdata\local\programs\python\python35\lib\site-packages\youtube_dl\extractor\__init__.py", line
4, in <module>
    from .lazy_extractors import *
ImportError: No module named 'youtube_dl.extractor.lazy_extractors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\vicky\appdata\local\programs\python\python35\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\vicky\appdata\local\programs\python\python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\vicky\AppData\Local\Programs\Python\Python35\Scripts\youtube-dl.exe\__main__.py", line 5, in <module>
  File "c:\users\vicky\appdata\local\programs\python\python35\lib\site-packages\youtube_dl\__init__.py", line 43, in <mo
dule>
    from .extractor import gen_extractors, list_extractors
  File "c:\users\vicky\appdata\local\programs\python\python35\lib\site-packages\youtube_dl\extractor\__init__.py", line
9, in <module>
    from .extractors import *
  File "c:\users\vicky\appdata\local\programs\python\python35\lib\site-packages\youtube_dl\extractor\extractors.py", lin
e 731
    +from .packtpub import (
        ^
SyntaxError: invalid syntax
PS C:\Users\vicky\downloads>
