### ISSUE TITLE
[iqiyi] couldn't download iqiyi vip video 

### ISSUE THREAD

**Issue by liuxu623** [rg3/youtube-dl#12648]
```
$ youtube-dl -U
youtube-dl is up-to-date (2017.04.03)
```
```
$ youtube-dl -F --verbose -u xxx -p xxx http://www.iqiyi.com/v_19rrb3rfno.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-F', u'--verbose', u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'http://www.iqiyi.com/v_19rrb3rfno.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.04.03
[debug] Python version 2.7.13 - Darwin-16.5.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.2.4, ffprobe 3.2.4
[debug] Proxy map: {}
[iqiyi] Get token for logging
[iqiyi] Validate credentials
[iqiyi] temp_id: download video page
[iqiyi] 8525819c09a2265c08c623e60081bfea: Downloading JSON metadata
ERROR: Unable to load data. Error code: A00011; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 761, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 429, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/iqiyi.py", line 357, in _real_extract
    raise ExtractorError('Unable to load data. Error code: ' + raw_data['code'])
ExtractorError: Unable to load data. Error code: A00011; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by yan12125** [comment]
iQiyi's VIP support is broken. Check #9839 for more details.
