### ISSUE TITLE
[MAJOR] Cannot download ANY YouTube DASH video format : ERROR: unable to download video data: <urlopen error [Errno 101] Network is unreachable>

### ISSUE THREAD

**Issue by sebma** [rg3/youtube-dl#12667]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.04.03*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.04.03**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2017.04.03
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

---

Hi,

It seems youtube-dl cannot download ANY YouTube DASH video format : 
```
$ youtube-dl -i -v -f 160,134,135,133,136 http://www.youtube.com/watch?v=FXsRDxcxmTA
[debug] System config: []
[debug] User config: [u'--prefer-ffmpeg', u'--no-warnings', u'--restrict-filenames', u'-o', u'%(title)s__%(format_id)s__%(id)s.%(ext)s', u'--format', u'mp4/webm/best', u'--write-auto-sub']
[debug] Custom config: []
[debug] Command-line args: [u'-i', u'-v', u'-f', u'160,134,135,133,136', u'http://www.youtube.com/watch?v=FXsRDxcxmTA']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.04.03
[debug] Python version 2.7.6 - Linux-4.4.0-67-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.20-6, avprobe 9.20-6, ffmpeg 3.2.4-2, ffprobe 3.2.4-2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] FXsRDxcxmTA: Downloading webpage
[youtube] FXsRDxcxmTA: Downloading video info webpage
[youtube] FXsRDxcxmTA: Extracting video information
[youtube] FXsRDxcxmTA: Looking for automatic captions
[youtube] FXsRDxcxmTA: Downloading MPD manifest
[info] FXsRDxcxmTA: downloading video in 5 formats
[debug] Invoking downloader on u'https://r15---sn-4gxx-25gel.googlevideo.com/videoplayback/id/157b110f17319930/itag/160/source/youtube/requiressl/yes/nh/EAE/initcwndbps/978750/pcm2cms/yes/mn/sn-4gxx-25gel/mm/31/pl/12/mv/m/ms/au/ratebypass/yes/mime/video%2Fmp4/otfp/1/gir/yes/clen/17589307/lmt/1485506709666071/dur/5437.197/upn/Kn6Yq2VMAtg/mt/1491481649/key/dg_yt0/signature/339FEC195534B790B25960611AABEC024F67DDDA.21A7EA77648D67CE2DCDAF8374510E6FA88BEE38/ip/78.243.8.240/ipbits/0/expire/1491503360/sparams/ip,ipbits,expire,id,itag,source,requiressl,nh,initcwndbps,pcm2cms,mn,mm,pl,mv,ms,ratebypass,mime,otfp,gir,clen,lmt,dur/'
[dashsegments] Total fragments: 1020
[download] Destination: A_Touch_of_His_Presence_2_Joseph_Prince_Songs__160__FXsRDxcxmTA.mp4
[download]   6.3% of ~19.21MiB at 959.68KiB/s ETA 01:42ERROR: unable to download video data: <urlopen error [Errno 101] Network is unreachable>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1797, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1739, in dl
    return fd.download(name, info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/common.py", line 356, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/dash.py", line 76, in real_download
    if not process_segment(segment, ctx['tmpfilename'], i):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/dash.py", line 48, in process_segment
    'http_headers': info_dict.get('http_headers'),
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/common.py", line 356, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/http.py", line 61, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 2100, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/utils.py", line 1089, in https_open
    req, **kwargs)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 101] Network is unreachable>

[debug] Invoking downloader on u'https://r15---sn-4gxx-25gel.googlevideo.com/videoplayback/id/157b110f17319930/itag/134/source/youtube/requiressl/yes/nh/EAE/initcwndbps/978750/pcm2cms/yes/mn/sn-4gxx-25gel/mm/31/pl/12/mv/m/ms/au/ratebypass/yes/mime/video%2Fmp4/otfp/1/gir/yes/clen/24332106/lmt/1485506710195769/dur/5437.197/upn/Kn6Yq2VMAtg/mt/1491481649/key/dg_yt0/signature/82E82485438E721C6572D1B11191003EDD0CBA83.5169681F726E6D630AD991EABDC342A91413FEF3/ip/78.243.8.240/ipbits/0/expire/1491503360/sparams/ip,ipbits,expire,id,itag,source,requiressl,nh,initcwndbps,pcm2cms,mn,mm,pl,mv,ms,ratebypass,mime,otfp,gir,clen,lmt,dur/'
[dashsegments] Total fragments: 1020
[download] Destination: A_Touch_of_His_Presence_2_Joseph_Prince_Songs__134__FXsRDxcxmTA.mp4
[download]  14.0% of ~26.95MiB at 904.76KiB/s ETA 00:08ERROR: unable to download video data: <urlopen error [Errno 101] Network is unreachable>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1797, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1739, in dl
    return fd.download(name, info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/common.py", line 356, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/dash.py", line 76, in real_download
    if not process_segment(segment, ctx['tmpfilename'], i):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/dash.py", line 48, in process_segment
    'http_headers': info_dict.get('http_headers'),
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/common.py", line 356, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/http.py", line 61, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 2100, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/utils.py", line 1089, in https_open
    req, **kwargs)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 101] Network is unreachable>

[debug] Invoking downloader on u'https://r15---sn-4gxx-25gel.googlevideo.com/videoplayback/id/157b110f17319930/itag/135/source/youtube/requiressl/yes/nh/EAE/initcwndbps/978750/pcm2cms/yes/mn/sn-4gxx-25gel/mm/31/pl/12/mv/m/ms/au/ratebypass/yes/mime/video%2Fmp4/otfp/1/gir/yes/clen/30923863/lmt/1485506709854540/dur/5437.197/upn/Kn6Yq2VMAtg/mt/1491481649/key/dg_yt0/signature/25021BADBE622D6C94DE714DB3F90A82434F694A.44CA6F003FEDD4E4AF8A8CDBDC83FA1C0737AB38/ip/78.243.8.240/ipbits/0/expire/1491503360/sparams/ip,ipbits,expire,id,itag,source,requiressl,nh,initcwndbps,pcm2cms,mn,mm,pl,mv,ms,ratebypass,mime,otfp,gir,clen,lmt,dur/'
[dashsegments] Total fragments: 1020
[download] Destination: A_Touch_of_His_Presence_2_Joseph_Prince_Songs__135__FXsRDxcxmTA.mp4
[download]   9.8% of ~34.44MiB at 189.58KiB/s ETA 00:41ERROR: unable to download video data: <urlopen error [Errno 101] Network is unreachable>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1797, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1739, in dl
    return fd.download(name, info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/common.py", line 356, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/dash.py", line 76, in real_download
    if not process_segment(segment, ctx['tmpfilename'], i):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/dash.py", line 48, in process_segment
    'http_headers': info_dict.get('http_headers'),
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/common.py", line 356, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/http.py", line 61, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 2100, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/utils.py", line 1089, in https_open
    req, **kwargs)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 101] Network is unreachable>

[debug] Invoking downloader on u'https://r15---sn-4gxx-25gel.googlevideo.com/videoplayback/id/157b110f17319930/itag/133/source/youtube/requiressl/yes/nh/EAE/initcwndbps/978750/pcm2cms/yes/mn/sn-4gxx-25gel/mm/31/pl/12/mv/m/ms/au/ratebypass/yes/mime/video%2Fmp4/otfp/1/gir/yes/clen/29731111/lmt/1485506709795848/dur/5437.197/upn/Kn6Yq2VMAtg/mt/1491481649/key/dg_yt0/signature/8A531E8262FE259E78F8882F9D544EFF8E7EF23A.1946E365839AF4B211DD7CBD4D086A14237F29FD/ip/78.243.8.240/ipbits/0/expire/1491503360/sparams/ip,ipbits,expire,id,itag,source,requiressl,nh,initcwndbps,pcm2cms,mn,mm,pl,mv,ms,ratebypass,mime,otfp,gir,clen,lmt,dur/'
[dashsegments] Total fragments: 1020
[download] Destination: A_Touch_of_His_Presence_2_Joseph_Prince_Songs__133__FXsRDxcxmTA.mp4
[download]   4.8% of ~33.38MiB at 975.27KiB/s ETA 01:48ERROR: unable to download video data: <urlopen error [Errno 101] Network is unreachable>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1797, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1739, in dl
    return fd.download(name, info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/common.py", line 356, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/dash.py", line 76, in real_download
    if not process_segment(segment, ctx['tmpfilename'], i):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/dash.py", line 48, in process_segment
    'http_headers': info_dict.get('http_headers'),
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/common.py", line 356, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/http.py", line 61, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 2100, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/utils.py", line 1089, in https_open
    req, **kwargs)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 101] Network is unreachable>

[debug] Invoking downloader on u'https://r15---sn-4gxx-25gel.googlevideo.com/videoplayback/id/157b110f17319930/itag/136/source/youtube/requiressl/yes/nh/EAE/initcwndbps/978750/pcm2cms/yes/mn/sn-4gxx-25gel/mm/31/pl/12/mv/m/ms/au/ratebypass/yes/mime/video%2Fmp4/otfp/1/gir/yes/clen/48678228/lmt/1485506709860438/dur/5437.197/upn/Kn6Yq2VMAtg/mt/1491481649/key/dg_yt0/signature/16737A821C7479BB24736EE5F739F27AB896AC.1A0381549FB82600E4B0A8C0D21BAE8DE1DC3F26/ip/78.243.8.240/ipbits/0/expire/1491503360/sparams/ip,ipbits,expire,id,itag,source,requiressl,nh,initcwndbps,pcm2cms,mn,mm,pl,mv,ms,ratebypass,mime,otfp,gir,clen,lmt,dur/'
[dashsegments] Total fragments: 1020
[download] Destination: A_Touch_of_His_Presence_2_Joseph_Prince_Songs__136__FXsRDxcxmTA.mp4
[download]  12.5% of ~55.07MiB at 706.42KiB/s ETA 00:19ERROR: unable to download video data: <urlopen error [Errno 101] Network is unreachable>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1797, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1739, in dl
    return fd.download(name, info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/common.py", line 356, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/dash.py", line 76, in real_download
    if not process_segment(segment, ctx['tmpfilename'], i):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/dash.py", line 48, in process_segment
    'http_headers': info_dict.get('http_headers'),
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/common.py", line 356, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/http.py", line 61, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 2100, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/utils.py", line 1089, in https_open
    req, **kwargs)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 101] Network is unreachable>

$ echo $?
1
```

**Comment by dstftw** [comment]
Fix your network connection.

**Comment by sebma** [comment]
I can download NON DASH format without any problem, please double check : 
```
$ youtube-dl -i -v -f 18 http://www.youtube.com/watch?v=FXsRDxcxmTA
[debug] System config: []
[debug] User config: [u'--prefer-ffmpeg', u'--no-warnings', u'--restrict-filenames', u'-o', u'%(title)s__%(format_id)s__%(id)s.%(ext)s', u'--format', u'mp4/webm/best', u'--write-auto-sub']
[debug] Custom config: []
[debug] Command-line args: [u'-i', u'-v', u'-f', u'18', u'http://www.youtube.com/watch?v=FXsRDxcxmTA']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.04.03
[debug] Python version 2.7.6 - Linux-4.4.0-67-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.20-6, avprobe 9.20-6, ffmpeg 3.2.4-2, ffprobe 3.2.4-2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] FXsRDxcxmTA: Downloading webpage
[youtube] FXsRDxcxmTA: Downloading video info webpage
[youtube] FXsRDxcxmTA: Extracting video information
[youtube] FXsRDxcxmTA: Looking for automatic captions
[youtube] FXsRDxcxmTA: Downloading MPD manifest
[debug] Invoking downloader on u'https://r15---sn-4gxx-25ge7.googlevideo.com/videoplayback?mt=1491492688&mv=m&pl=12&id=o-AA6RKgFXijl-lkoXRFfcbLGNflRaPQLLa0LkhPEokDrF&ei=yV_mWInDBcGYcoeCipgO&ms=au&ip=78.243.8.240&gir=yes&ratebypass=yes&source=youtube&mm=31&mn=sn-4gxx-25ge7&upn=MSgTgCypwZs&itag=18&mime=video%2Fmp4&pcm2cms=yes&dur=5437.323&signature=4386D458CD6A5E6ACD6517C761815D17393F1CFF.A2FF08FA115F9203EC763DBD45708E76743D5660&ipbits=0&nh=EAE&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpcm2cms%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&lmt=1485507369279902&clen=124726239&requiressl=yes&key=yt6&initcwndbps=922500&expire=1491514409'
[download] Destination: A_Touch_of_His_Presence_2_Joseph_Prince_Songs__18__FXsRDxcxmTA.mp4
[download] 100% of 118.95MiB in 01:20
$ echo $?
0

```

**Comment by dstftw** [comment]
I can download DASH fine. Fix your network.
