### ISSUE TITLE
Can't download video on Facebook

### ISSUE THREAD

**Issue by Rudloff** [rg3/youtube-dl#1269]
```
pierre@Rudloff:~/Bureau/youtube-dl$ ./youtube-dl https://www.facebook.com/photo.php?v=1726498360960
[facebook] 1726498360960: Downloading webpage
ERROR: Cannot parse data; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
pierre@Rudloff:~/Bureau/youtube-dl$ ./youtube-dl https://www.facebook.com/photo.php?v=1726498360960 -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['https://www.facebook.com/photo.php?v=1726498360960', '-v']
[debug] youtube-dl version 2013.08.17
[debug] Python version 2.7.3 - Linux-3.2.0-4-amd64-x86_64-with-debian-7.1
[debug] Proxy map: {}
[facebook] 1726498360960: Downloading webpage
ERROR: Cannot parse data; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 312, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 96, in extract
    return self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/facebook.py", line 96, in _real_extract
    raise ExtractorError(u'Cannot parse data')
ExtractorError: Cannot parse data; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
```

**Comment by mcepl** [comment]
```
matej@mitmanek: youtube-dl (epel7 %)$ youtube-dl --verbose \
    -u mcepl -p veryverysecret \
    'https://www.facebook.com/video.php?v=10203524731698317&set=vb.1215049765&type=2&theater'
[debug] System config: ['--prefer-free-formats']
[debug] User config: []
[debug] Command-line args: ['--verbose', '-u', u'PRIVATE', '-p', u'PRIVATE', 'https://www.facebook.com/video.php?v=10203524731698317&set=vb.1215049765&type=2&theater']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.01.25
[debug] Python version 2.7.5 - Linux-3.10.0-123.9.3.el7.x86_64-x86_64-with-redhat-7.1-Maipo
[debug] exe versions: ffmpeg 2.3.4, ffprobe 2.3.4, rtmpdump 2.4
[debug] Proxy map: {}
[facebook] Downloading login page
[facebook] Logging in
WARNING: unable to log in: bad username/password, or exceded login rate limit (~3/min). Check credentials or wait.
[facebook] 10203524731698317: Downloading webpage
ERROR: The video is not available, Facebook said: "The page you requested cannot be displayed right now. It may be temporarily unavailable, the link you clicked on may have expired, or you may not have permission to view this page."
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 613, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 266, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/facebook.py", line 122, in _real_extract
    expected=True)
ExtractorError: The video is not available, Facebook said: "The page you requested cannot be displayed right now. It may be temporarily unavailable, the link you clicked on may have expired, or you may not have permission to view this page."

matej@mitmanek: youtube-dl (epel7 %)$
```
I don't think this is a private video, is it?

**Comment by brightghost** [comment]
Is this still broken? I'm seeing all the same behaviors described here.

**Comment by Rudloff** [comment]
This seems to be fixed now.

**Comment by mcepl** [comment]
@Rudloff no, it isn't. I can still reproduce https://github.com/rg3/youtube-dl/issues/1269#issuecomment-71850429 with 2017.02.16

**Comment by Rudloff** [comment]
Well, I can download the video from the original comment with 2017.03.22, so yours is probably a different issue.

**Comment by mcepl** [comment]
Right, confirming, this has been fixed in 2017.03.22

**Comment by klavixs** [comment]
using 2017.03.22
updated using sudo youtube-dl -U
failed for https://www.facebook.com/pg/ReformedThugLife/videos/?ref=page_internal

youtube-dl -f best 'http://www.facebook.com/ReformedThugLife/videos/'

```

[generic] videos: Requesting header
[redirect] Following redirect to https://www.facebook.com/ReformedThugLife/videos/
[generic] videos: Requesting header
WARNING: Falling back on generic information extractor.
[generic] videos: Downloading webpage
[generic] videos: Extracting information
[redirect] Following redirect to https://www.facebook.com/ReformedThugLife/videos/?_fb_noscript=1
[generic] ?_fb_noscript=1: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ?_fb_noscript=1: Downloading webpage
[generic] ?_fb_noscript=1: Extracting information
ERROR: Unsupported URL: https://www.facebook.com/ReformedThugLife/videos/?_fb_noscript=1

```

**Comment by Ads20000** [comment]
This doesn't work if you have certain special characters in your password

**Comment by sophanarin** [comment]
You can Download Facebook Video here
http://www.kh-song.com/download-facebook-video-online.html
