### ISSUE TITLE
--proxy not working

### ISSUE THREAD

**Issue by RuneMagle** [rg3/youtube-dl#12739]
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.04.14**
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [X] Question
- [ ] Other

---
```
C:\Users\youtube-dl>youtube-dl.exe -f best --all-subs --username lol --password ololll --ap-username lol --ap-password lol --ap-mso DTV --continue --no-check-certificate --proxy 107.17.92.18:8080 http://watchdisneyjunior.go.com/mickey-and-the-roadster-racers/video/vdka3788100/01/12-the-impossible-race-the-happiest-helpers-cruise#playlist=PL551978168 -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'best', '--all-subs', '--username', 'PRIVATE', '--password', 'PRIVATE', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '--ap-mso', 'DTV', '--continue', '--no-check-certificate', '--proxy', '107.17.92.18:8080', 'http://watchdisneyjunior.go.com/mickey-and-the-roadster-racers/video/vdka3788100/01/12-the-impossible-race-the-happiest-helpers-cruise#playlist=PL551978168', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.04.14
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-82833-gedb4f5d, ffprobe N-82833-gedb4f5d, rtmpdump 2.3
[debug] Proxy map: {'http': '107.17.92.18:8080', 'https': '107.17.92.18:8080'}
[Go] 12-the-impossible-race-the-happiest-helpers-cruise: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [WinError 10060]An attempt to connect failed because the party had connected, did not respond properly after a period of time, or established connection was terminated because the host did not respond> (caused by URLError(TimeoutError(10060, 'An attempt to connect failed because the party had connected, did not respond properly after a period of time, or established connection was terminated because the host did not respond', None, 10060, None),))
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpykl6x8ju\build\youtube_dl\extractor\common.py", line 498, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpykl6x8ju\build\youtube_dl\YoutubeDL.py", line 2100, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpykl6x8ju\build\youtube_dl\utils.py", line 925, in http_open
  File "C:\Python\Python34\lib\urllib\request.py", line 1185, in do_open
...
<end of log>
```

---
- Single video: http://watchdisneyjunior.go.com/mickey-and-the-roadster-racers/video/vdka3788100/01/12-the-impossible-race-the-happiest-helpers-cruise#playlist=PL551978168

---

### Description of issue

When I try using proxy from a free proxy list (hidemyass). It never works. I've also tried other ones, but I don't understand why. Maybe I'm just a noob. But I don't get this at all. I type IP and port. (--proxy 107.17.92.18:8080). It works fine with usual VPN.

**Comment by dstftw** [comment]
107.17.92.18:8080 is dead as well as most of the free proxies.

**Comment by RuneMagle** [comment]
Can you maybe refer me somewhere with proxys that work?

**Comment by RuneMagle** [comment]
But isn't tor just a browser?

**Comment by dstftw** [comment]
No.

**Comment by RuneMagle** [comment]
I just found one that works. But it didn't recognize it. It still said I was outside the US.
```
[debug] Proxy map: {'https': '144.217.223.219:8080', 'http': '144.217.223.219:8080'}
[Go] 02-the-french-toast-connection-take-me-out-to-the-pug-game: Downloading webpage
[Go] 3787705: Downloading JSON metadata
[Go] 3787705: Downloading Provider Redirect Page
[Go] 3787705: Downloading Provider Login Page
[Go] 3787705: Logging in
[Go] 3787705: Confirming Login
[Go] 3787705: Retrieving Session
[Go] 3787705: Retrieving Authorization Token
[Go] 3787705: Retrieving Media Token
[Go] 3787705: Downloading JSON metadata
WARNING: [Go] Video is geo restricted. Retrying extraction with fake IP 3.206.158.35 (US) as X-Forwarded-For.
[Go] 02-the-french-toast-connection-take-me-out-to-the-pug-game: Downloading webpage
[Go] 3787705: Downloading JSON metadata
[Go] 3787705: Retrieving Media Token
[Go] 3787705: Downloading Provider Redirect Page
[Go] 3787705: Downloading Provider Login Page
[Go] 3787705: Logging in
[Go] 3787705: Confirming Login
[Go] 3787705: Retrieving Session
[Go] 3787705: Retrieving Authorization Token
[Go] 3787705: Downloading JSON metadata
ERROR: 1002:You appear to be outside the United States or its territories. Due to international rights agreements, we only offer this video to viewers located within the United States and its territories.
This video is available in United States.
You might want to use a VPN or a proxy server (with --proxy) to workaround.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpykl6x8ju\build\youtube_dl\YoutubeDL.py", line 761, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpykl6x8ju\build\youtube_dl\extractor\common.py", line 429, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpykl6x8ju\build\youtube_dl\extractor\go.py", line 114, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpykl6x8ju\build\youtube_dl\extractor\common.py", line 713, in raise_geo_restricted
youtube_dl.utils.GeoRestrictedError: 1002:You appear to be outside the United States or its territories. Due to international rights agreements, we only offer this video to viewers located within the United States and its territories.
```

Huh...Maybe it's just not meant to work for me...

**Comment by dstftw** [comment]
It's not an US IP that is clearly stated in error message.

**Comment by RuneMagle** [comment]
But it says on website that it was United States. I just tried another one, it says the same. Plus, I'm in Denmark. And when I don't use VPN at all. It just says couldn't retrieve files for playback. Not that I'm in another country.

**Comment by dstftw** [comment]
```
$ whois 144.217.223.219
...
NetRange:       144.217.0.0 - 144.217.255.255
...
OrgName:        OVH Hosting, Inc.
OrgId:          HO-2
Address:        800-1801 McGill College
City:           Montreal
StateProv:      QC
PostalCode:     H3A 2N4
Country:        CA
...
```
>Country:        CA

**Comment by RuneMagle** [comment]
Lol. I guess I'm just gonna keep trying... Thanks for helping! :)

**Comment by therohanchawla** [comment]
Is there an explanation some where on How to use YouTube DL and Tor

**Comment by dstftw** [comment]
--proxy socks5://127.0.0.1:9050 if you did not touch its settings.

**Comment by RuneMagle** [comment]
That command doesn't work with me. ```ERROR: Unable to download webpage```

**Comment by yan12125** [comment]
@RuneMagle Please check that your Tor server is up and listening port 9050.

**Comment by RuneMagle** [comment]
I don't understand it. Whatever...

**Comment by Mithgol** [comment]
@RuneMagle It's actually `youtube-dl --proxy socks5://127.0.0.1:9150` because on Windows [Tor Browser listens on port 9150.](https://www.torproject.org/docs/faq.html.en#TBBSocksPort)
