### ISSUE TITLE
Cannot identify player ...player-vflF8UZsJ/en_US/base.js with youtube-dl 2017.04.11

### ISSUE THREAD

**Issue by patraulea** [rg3/youtube-dl#12731]
[x] I've **verified** and **I assure** that I'm running youtube-dl **2017.04.11**

[x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

- [x] Bug report (encountered problems with youtube-dl)

Encountered using mps-youtube. The traceback is:
```
ERROR: Signature extraction failed: Traceback (most recent call last):                                   
  File "/home/bogdan/.local/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1081, in _decrypt_signature
    video_id, player_url, s
  File "/home/bogdan/.local/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 969, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflF8UZsJ/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflF8UZsJ/en_US/base.js';
```
I usually have to play the same video a couple of times to reproduce it.

More configuration info:
```
mpsyt version      : 0.2.7.1
   notes           : released 6 July 2016
pafy version       : 0.5.3.1 (youtube-dl backend)
youtube-dl version : 2017.04.11
Python version     : 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609]
Processor          : x86_64
Machine type       : x86_64
Architecture       : 64bit, ELF
Platform           : Linux-4.4.0-71-generic-x86_64-with-Ubuntu-16.04-xenial
sys.stdout.enc     : UTF-8
default enc        : utf-8
Config dir         : /home/bogdan/.config/mps-youtube
env:TERM           : xterm-256color
env:SHELL          : /bin/bash
env:LANG           : en_US.UTF-8
env:LANGUAGE       : en_US
```

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
