### ISSUE TITLE
bug: CWTV creating .ismv files all of a sudden

### ISSUE THREAD

**Issue by jschwalbe** [rg3/youtube-dl#12755]
- [X ] I've **verified** and **I assure** that I'm running youtube-dl **2017.04.16**
- [X ] Bug report (encountered problems with youtube-dl)

---

When downloading certain shows from CWTV I've noticed that often the file type is `.ismv` rather than `.mp4`.  Once I re-ran the command and that fixed it but lately not so. I've tried on two different machines (both macOS). Strangely enough, other CWTV programs _do work_. 
Any ideas?
Thanks! Log below.
```
$ youtube-dl -v "http://www.cwtv.com/shows/dcs-legends-of-tomorrow/aruba/?play=280d9392-d40c-4a42-b1be-775316e9677c"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'http://www.cwtv.com/shows/dcs-legends-of-tomorrow/aruba/?play=280d9392-d40c-4a42-b1be-775316e9677c']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.04.16
[debug] Python version 2.7.10 - Darwin-16.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.0.1, ffprobe 3.0.1, rtmpdump 2.4
[debug] Proxy map: {}
[CWTV] 280d9392-d40c-4a42-b1be-775316e9677c: Downloading JSON metadata
[CWTV] 280d9392-d40c-4a42-b1be-775316e9677c: Downloading m3u8 information
[CWTV] 280d9392-d40c-4a42-b1be-775316e9677c: Downloading JSON metadata
[CWTV] 280d9392-d40c-4a42-b1be-775316e9677c: Checking http-8628 URL
[CWTV] 280d9392-d40c-4a42-b1be-775316e9677c: http-8628 URL is invalid, skipping
[CWTV] 280d9392-d40c-4a42-b1be-775316e9677c: Checking http-464 URL
[CWTV] 280d9392-d40c-4a42-b1be-775316e9677c: Checking http-664 URL
[CWTV] 280d9392-d40c-4a42-b1be-775316e9677c: Checking http-6628 URL
[CWTV] 280d9392-d40c-4a42-b1be-775316e9677c: http-6628 URL is invalid, skipping
[CWTV] 280d9392-d40c-4a42-b1be-775316e9677c: Checking http-3596 URL
[CWTV] 280d9392-d40c-4a42-b1be-775316e9677c: Checking http-1296 URL
[CWTV] 280d9392-d40c-4a42-b1be-775316e9677c: Checking http-264 URL
[CWTV] 280d9392-d40c-4a42-b1be-775316e9677c: Checking http-5128 URL
[CWTV] 280d9392-d40c-4a42-b1be-775316e9677c: Downloading ISM manifest
[debug] Invoking downloader on u'http://cwsmooth-vod.hss.adaptive.level3.net/09f2b26a-1479-4802-abe3-acd38956ad8e/LegendsOfTomorrow-217-Aruba-T1320017-CW-Stereo.ism/manifest'
[ism] Total fragments: 1244
[download] Destination: Aruba-280d9392-d40c-4a42-b1be-775316e9677c.fmss-3372.ismv
[download] 100% of 1002.09MiB in 20:40
[debug] Invoking downloader on u'http://cwsmooth-vod.hss.adaptive.level3.net/09f2b26a-1479-4802-abe3-acd38956ad8e/LegendsOfTomorrow-217-Aruba-T1320017-CW-Stereo.ism/manifest'
[ism] Total fragments: 1242
[download] Destination: Aruba-280d9392-d40c-4a42-b1be-775316e9677c.fmss-aac_UND_2_127-127.isma
[download] 100% of 39.11MiB in 04:21
[ffmpeg] Merging formats into "Aruba-280d9392-d40c-4a42-b1be-775316e9677c.ismv"
[debug] ffmpeg command line: ffmpeg -y -i file:Aruba-280d9392-d40c-4a42-b1be-775316e9677c.fmss-3372.ismv -i file:Aruba-280d9392-d40c-4a42-b1be-775316e9677c.fmss-aac_UND_2_127-127.isma -c copy -map 0:v:0 -map 1:a:0 file:Aruba-280d9392-d40c-4a42-b1be-775316e9677c.temp.ismv
Deleting original file Aruba-280d9392-d40c-4a42-b1be-775316e9677c.fmss-3372.ismv (pass -k to keep)
Deleting original file Aruba-280d9392-d40c-4a42-b1be-775316e9677c.fmss-aac_UND_2_127-127.isma (pass -k to keep)
<end of log>
```

Also - one might think that the url `http://www.cwtv.com/shows/dcs-legends-of-tomorrow/aruba` might work, but it fails as well:
```
$ youtube-dl -v "http://www.cwtv.com/shows/dcs-legends-of-tomorrow/aruba"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'http://www.cwtv.com/shows/dcs-legends-of-tomorrow/aruba']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.04.16
[debug] Python version 2.7.10 - Darwin-16.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.0.1, ffprobe 3.0.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] aruba: Requesting header
WARNING: Falling back on generic information extractor.
[generic] aruba: Downloading webpage
[generic] aruba: Extracting information
ERROR: Unsupported URL: http://www.cwtv.com/shows/dcs-legends-of-tomorrow/aruba
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1888, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2526, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2515, in _XML
    parser.feed(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 4, column 319
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 760, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 429, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2750, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.cwtv.com/shows/dcs-legends-of-tomorrow/aruba
```

**Comment by dstftw** [comment]
This is expected. If you don't want ism (that is bestaudio/bestvideo) to be download then setup [format selection appropriately](https://github.com/rg3/youtube-dl#format-selection).

**Comment by jschwalbe** [comment]
Can you comment what .ismv is? The link you showed me doesn't mention it at all.. Thanks!

**Comment by dstftw** [comment]
https://en.wikipedia.org/wiki/Adaptive_bitrate_streaming#Microsoft_Smooth_Streaming

**Comment by Chariblaze** [comment]
Does is matter that bestvideo+bestaudio isn't the best quality overall on this site? At least if filesize is an indication:

http://www.cwtv.com/shows/supergirl/nevertheless-she-persisted/?play=acdc4520-b0f3-47c9-8bdc-b8245f1fb351

`Nevertheless, She Persisted-acdc4520-b0f3-47c9-8bdc-b8245f1fb351.ismv | 1.05 GB (bestvideo+bestaudio)`
`Nevertheless, She Persisted-acdc4520-b0f3-47c9-8bdc-b8245f1fb351.mp4 | 1.47 GB (best)`

bestvideo+bestaudio as default is good for YouTube, but does it work here if it's downloading a lower-quality format that most players can't handle out-of-the-box (tried PotPlayer, VLC, WMP)?
