### ISSUE TITLE
Site-support request: 100huntley.com

### ISSUE THREAD

**Issue by hub2git** [rg3/youtube-dl#12768]
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.04.17**
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Site support request (request for adding support for a new site)

```
 $ youtube-dl -v http://www.100huntley.com/watch?id=223812&title=life-stories-julia-bayer
[1] 5611
me@laptop ~ $ [debug] System config: [u'-o', u'~/Videos/youtube-dl/%(title)s_%(id)s.%(ext)s', u'--netrc', u'--restrict-filenames', u'--write-description', u'--write-sub', u'--yes-playlist', u'--ignore-errors']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'http://www.100huntley.com/watch?id=223812']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.04.17
[debug] Python version 2.7.12 - Linux-4.4.0-71-generic-x86_64-with-LinuxMint-18.1-serena
[debug] exe versions: ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1
[debug] Proxy map: {}
[generic] watch?id=223812: Requesting header
WARNING: Falling back on generic information extractor.
[generic] watch?id=223812: Downloading webpage
[generic] watch?id=223812: Extracting information
ERROR: Unsupported URL: http://www.100huntley.com/watch?id=223812
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1898, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2526, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2515, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: syntax error: line 1, column 0
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 760, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 429, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2765, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.100huntley.com/watch?id=223812


[1]+  Exit 1                  youtube-dl -v http://www.100huntley.com/watch?id=223812
```
---
### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://www.100huntley.com/watch?id=223812&title=life-stories-julia-bayer
---

### Description of your *issue*, suggested solution and other information
When I right-click on the video, I see a pop-up box that says "Powered by JW Player 7.10.5".

It looks like youtube-dl  is set up to download "JW Player" videos, as evidenced https://github.com/rg3/youtube-dl/issues/685. I guess this means that youtube-dl  just has to add 100huntley.com to the list of supported URLs.

**Comment by yan12125** [comment]
crossroadscloud embeds (http://stream.crossroadscloud.com/watch?cdnID=1470764493&resolution=360p)
