### ISSUE TITLE
Unable to extract video from Swivl when it has slides attached

### ISSUE THREAD

**Issue by eriknstr** [rg3/youtube-dl#12770]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.04.17*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.04.17**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v https://cloud.swivl.com/v/a504a4448d88a4479af8480b25f301dd
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://cloud.swivl.com/v/a504a4448d88a4479af
8480b25f301dd']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.04.17
[debug] Python version 3.5.3 - FreeBSD-11.0-RELEASE-p8-amd64-64bit-ELF
[debug] exe versions: ffmpeg 3.2.4, ffprobe 3.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[generic] a504a4448d88a4479af8480b25f301dd: Requesting header
WARNING: Falling back on generic information extractor.
[generic] a504a4448d88a4479af8480b25f301dd: Downloading webpage
[generic] a504a4448d88a4479af8480b25f301dd: Extracting information
ERROR: Unsupported URL: https://cloud.swivl.com/v/a504a4448d88a4479af8480b25f301dd
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 760, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 429, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.5/site-packages/youtube_dl/extractor/generic.py", line 2765, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://cloud.swivl.com/v/a504a4448d88a4479af8480b25f301dd
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single regular video: https://cloud.swivl.com/v/e4a0e92223672c37a21ff2788007f823
- Single video with slides attached: https://cloud.swivl.com/v/a504a4448d88a4479af8480b25f301dd

---

### Description of your *issue*, suggested solution and other information

youtube-dl is able to download a lot of videos from Swivl just fine but it seems that when the videos have slides attached, it doesn't work at all.

youtube-dl is able to download the following regular video fine: https://cloud.swivl.com/v/e4a0e92223672c37a21ff2788007f823

youtube-dl is unable to download the following video which has slides attached: https://cloud.swivl.com/v/a504a4448d88a4479af8480b25f301dd

Ideally youtube-dl might even download the slides that go with such videos, but the most important bit is that the videos themselves are downloaded.

**Comment by yan12125** [comment]
Swivl is not supported yet. For slides, see #12889 for discussions.
