### ISSUE TITLE
can't download instagram videos

### ISSUE THREAD

**Issue by kiendy** [rg3/youtube-dl#12777]
youtube-dl -f '[ext=mp4]' --batch-file='baby.txt'
[Instagram] BHgBH0Sh523: Downloading webpage
WARNING: unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/__init__.py", line 464, in main
    _real_main(argv)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/__init__.py", line 454, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1896, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 760, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 429, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/instagram.py", line 206, in _real_extract
    'comments': comments,
UnboundLocalError: local variable 'comments' referenced before assignment
root@vps393873:~/

i try update youtube-dl "sudo pip install --upgrade youtube-dl"
after the update is complete, I am still having the same problem.
few weeks ago I did not experience this problem

sorry my english bad
and sorry if I'm wrong because im new here
thanks

**Comment by raminious** [comment]
same issue. Instagram extraction has been broken

**Comment by dprski33** [comment]
ditto

**Comment by dprski33** [comment]
@dstftw Can you let us know when we can expect this fix available?

**Comment by Hrxn** [comment]
If you need it immediately, run or install it directly from source.

**Comment by nnact** [comment]
@Hrxn Could you show me how to run or install this lib from source code please? I need this fix. Thank you.

**Comment by Hrxn** [comment]
Either way, you first need [Python](https://www.python.org/) for your OS.

Then, grab the source via git or by clicking that green 'clone or download' button to get the source archive file.

Extract, navigate to the target directory and run `python setup.py install` or run it from the same location with `python youtube_dl/__init__.py`
