### ISSUE TITLE
[Instagram] unable to extract uploader id, UnboundLocalError: local variable 'comments' referenced before assignment

### ISSUE THREAD

**Issue by shaicoleman** [rg3/youtube-dl#12787]
```
$ youtube-dl --verbose https://www.instagram.com/p/BTDFg3cBW4b/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.instagram.com/p/BTDFg3cBW4b/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.04.17
[debug] Python version 3.5.2 - Linux-4.4.0-72-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 3.2.4-1, ffprobe 3.2.4-1
[debug] Proxy map: {}
[Instagram] BTDFg3cBW4b: Downloading webpage
WARNING: unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/__init__.py", line 464, in main
    _real_main(argv)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/__init__.py", line 454, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/YoutubeDL.py", line 1896, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/YoutubeDL.py", line 760, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/common.py", line 429, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/instagram.py", line 206, in _real_extract
    'comments': comments,
UnboundLocalError: local variable 'comments' referenced before assignment
```

As a workaround, I've deleted in extractor/instagram.py line 206, `'comments': comments,`

**Comment by shaicoleman** [comment]
Duplicate of #12777
