### ISSUE TITLE
Extractor error on Akamai AMP feed, KeyError: 'channel'

### ISSUE THREAD

**Issue by AlJohri** [rg3/youtube-dl#12795]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.04.17*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.04.17**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
youtube-dl --verbose --skip-download --write-sub "http://video.foxnews.com/v/4032976847001/"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--skip-download', '--write-sub', 'http://video.foxnews.com/v/4032976847001/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.04.17
[debug] Python version 3.6.0 - Darwin-16.5.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.3, ffprobe 3.3
[debug] Proxy map: {}
[foxnews] Downloading Akamai AMP feed
ERROR: An extractor error has occurred. (caused by KeyError('channel',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/Users/johria/.virtualenvs/late-night-talk-show-analysis/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 429, in extract
    ie_result = self._real_extract(url)
  File "/Users/johria/.virtualenvs/late-night-talk-show-analysis/lib/python3.6/site-packages/youtube_dl/extractor/foxnews.py", line 65, in _real_extract
    'http://%s/v/feed/video/%s.js?template=fox' % (host, video_id))
  File "/Users/johria/.virtualenvs/late-night-talk-show-analysis/lib/python3.6/site-packages/youtube_dl/extractor/amp.py", line 18, in _extract_feed_info
    'Unable to download Akamai AMP feed')['channel']['item']
KeyError: 'channel'
Traceback (most recent call last):
  File "/Users/johria/.virtualenvs/late-night-talk-show-analysis/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 429, in extract
    ie_result = self._real_extract(url)
  File "/Users/johria/.virtualenvs/late-night-talk-show-analysis/lib/python3.6/site-packages/youtube_dl/extractor/foxnews.py", line 65, in _real_extract
    'http://%s/v/feed/video/%s.js?template=fox' % (host, video_id))
  File "/Users/johria/.virtualenvs/late-night-talk-show-analysis/lib/python3.6/site-packages/youtube_dl/extractor/amp.py", line 18, in _extract_feed_info
    'Unable to download Akamai AMP feed')['channel']['item']
KeyError: 'channel'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/johria/.virtualenvs/late-night-talk-show-analysis/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 760, in extract_info
    ie_result = ie.extract(url)
  File "/Users/johria/.virtualenvs/late-night-talk-show-analysis/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 442, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('channel',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

---

### Description of your *issue*, suggested solution and other information

Ran into an error while trying to download a video from foxnews using `FoxNewIE`. Seems to be a generic error related to the `AMPIE`.

**Comment by AlJohri** [comment]
Thanks @remitamine!
