### ISSUE TITLE
Instagram videos failed

### ISSUE THREAD

**Issue by kale20** [rg3/youtube-dl#12827]
Hello
Not download instagram videos via youtube-dl.  What is solution ? 
Check verbose log.
Thank you for reply

```

`[root@mypc ~]# youtube-dl https://www.instagram.com/p/BTPZZ46Drye/ -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.instagram.com/p/BTPZZ46Drye/', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.04.17
[debug] Python version 2.7.5 - Linux-3.14.32-xxxx-grs-ipv6-64-x86_64-with-centos-7.2.1511-Core
[debug] exe versions: ffmpeg N-80062-gdefb960, ffprobe N-80062-gdefb960
[debug] Proxy map: {}
[Instagram] BTPZZ46Drye: Downloading webpage
WARNING: unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/youtube_dl/__init__.py", line 464, in main
    _real_main(argv)
  File "/usr/lib/python2.7/site-packages/youtube_dl/__init__.py", line 454, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 1896, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 760, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 429, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/instagram.py", line 206, in _real_extract
    'comments': comments,
UnboundLocalError: local variable 'comments' referenced before assignment`
```

**Comment by ohhai** [comment]
What is the main issue, if this is a duplicate?
There are only 8 open issues related with Instagram, all seem unrelated.
