### ISSUE TITLE
Adult Swim: Dying on subtitles

### ISSUE THREAD

**Issue by keybounce** [rg3/youtube-dl#12829]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.04.17*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2017.04.17**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---
```
keybounceMBP:Jack michael$ youtube-dl -v -a dl-list 
[debug] System config: []
[debug] User config: [u'-o', u'%(title)s-%(timestamp)6i.%(ext)s', u'-f', u'\nbest[ext=mp4][height>431][height<=576]/\nbestvideo[ext=mp4][height=480]+bestaudio[ext=m4a]/\nbest[ext=mp4][height>340][height<=431]/\nbestvideo[ext=mp4][height>360][height<=576]+bestaudio/\nbest[height>340][height<=576]/\nbestvideo[height>360][height<=576]+bestaudio/\nbestvideo[height=360]+bestaudio/\nbest[ext=mp4][height>=280][height<=360]/\nbest[height<=576]/\nworst', u'--ap-mso', u'Dish', u'--ap-username', u'PRIVATE', u'--ap-password', u'PRIVATE', u'--write-sub', u'--write-auto-sub', u'--sub-lang', u'en,enUS,en-us', u'--sub-format', u'ass/srt/best', u'--convert-subs', u'ass', u'--embed-subs', u'--recode-video', u'mp4', u'--mark-watched']
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-a', u'dl-list']
[debug] Batch file urls: [u'http://www.adultswim.com/videos/samurai-jack/xcii/', u'http://www.adultswim.com/videos/samurai-jack/xciii/', u'http://www.adultswim.com/videos/samurai-jack/xciv/', u'http://www.adultswim.com/videos/samurai-jack/xcv/', u'http://www.adultswim.com/videos/samurai-jack/xcvi/', u'http://www.adultswim.com/videos/samurai-jack/xcvii/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.04.17
[debug] Python version 2.7.5 - Darwin-13.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.2.4, ffprobe 3.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[AdultSwim] xcii: Downloading page
[AdultSwim] I3Yw7ynsSUqU5H2jNpRKKg: Downloading JSON metadata
[AdultSwim] I3Yw7ynsSUqU5H2jNpRKKg: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[AdultSwim] I3Yw7ynsSUqU5H2jNpRKKg: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[AdultSwim] I3Yw7ynsSUqU5H2jNpRKKg: Downloading m3u8 information
[AdultSwim] I3Yw7ynsSUqU5H2jNpRKKg: Downloading f4m manifest
[AdultSwim] I3Yw7ynsSUqU5H2jNpRKKg: Downloading f4m manifest
[AdultSwim] I3Yw7ynsSUqU5H2jNpRKKg: Downloading f4m manifest
WARNING: Unable to download f4m manifest: HTTP Error 404: Not Found
[AdultSwim] I3Yw7ynsSUqU5H2jNpRKKg: Downloading f4m manifest
WARNING: Unable to download f4m manifest: HTTP Error 404: Not Found
[AdultSwim] I3Yw7ynsSUqU5H2jNpRKKg: Downloading f4m manifest
WARNING: Unable to download f4m manifest: HTTP Error 404: Not Found
[AdultSwim] I3Yw7ynsSUqU5H2jNpRKKg: Downloading f4m manifest
WARNING: Unable to download f4m manifest: HTTP Error 404: Not Found
WARNING: enUS subtitles not available for I3Yw7ynsSUqU5H2jNpRKKg
WARNING: en-us subtitles not available for I3Yw7ynsSUqU5H2jNpRKKg
[info] Writing video subtitles to: XCII-1491533567.en.ttml
[debug] Invoking downloader on u'http://amd.cdn.turner.com/adultswim/episodes/us_geo/samjack/2017/03/samjack_cc_092_Digital_XCII_bajtweuyuav8w6tva8/hls/samjack_cc_092_Digital_XCII_bajtweuyuav8w6tva8_stream_7.m3u8'
[download] XCII-1491533567.mp4 has already been downloaded
[download] 100% of 581.29MiB
[ffmpeg] Not converting video file XCII-1491533567.mp4 - already is in target format mp4
[ffmpeg] Converting subtitles
WARNING: You have requested to convert dfxp (TTML) subtitles into another format, which results in style information loss
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/michael/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/Users/michael/bin/youtube-dl/youtube_dl/__init__.py", line 464, in main
  File "/Users/michael/bin/youtube-dl/youtube_dl/__init__.py", line 454, in _real_main
  File "/Users/michael/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1896, in download
  File "/Users/michael/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 771, in extract_info
  File "/Users/michael/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 825, in process_ie_result
  File "/Users/michael/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1539, in process_video_result
  File "/Users/michael/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1877, in process_info
  File "/Users/michael/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1942, in post_process
  File "/Users/michael/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 564, in run
  File "/Users/michael/bin/youtube-dl/youtube_dl/utils.py", line 2616, in dfxp2srt
  File "/Users/michael/bin/youtube-dl/youtube_dl/compat.py", line 2526, in compat_etree_fromstring
  File "/Users/michael/bin/youtube-dl/youtube_dl/compat.py", line 2516, in _XML
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1654, in close
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: no element found: line 1, column 0
keybounceMBP:Jack michael$ 
```

The video is downloaded (this is the first, non-cable login restricted, one). The subtitle file is length 0.

**Comment by dstftw** [comment]
adultswim is currently not supported.

**Comment by gkoelln** [comment]
See #12121 for current discussion/update on the Adult Swim extractor.
