### ISSUE TITLE
Unable to get subtitles from Discovery/Science channel

### ISSUE THREAD

**Issue by keybounce** [rg3/youtube-dl#12848]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.04.26*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2017.04.26**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

Attempting to fetch a video from Science Channel will not fetch the subtitles.

NB: This sample is currently a free video, but history shows that they becomes provider locked after a week, and they don't support my provider :-(

```
keybounceMBP:Science michael$ 
keybounceMBP:Science michael$ youtube-dl -v https://www.sciencechannelgo.com/through-the-wormhole-with-morgan-freeman/is-th
e-force-with-us/
[debug] System config: []
[debug] User config: [u'-o', u's%(season_number)02de%(episode_number)02d - %(title)s.%(ext)s', u'-f', u'\nbest[ext=mp4][height>431][height<=576]/\nbestvideo[ext=mp4][height=480]+bestaudio[ext=m4a]/\nbest[ext=mp4][height>340][height<=431]/\nbestvideo[ext=mp4][height>360][height<=576]+bestaudio/\nbest[height>340][height<=576]/\nbestvideo[height>360][height<=576]+bestaudio/\nbestvideo[height=360]+bestaudio/\nbest[ext=mp4][height>=280][height<=360]/\nbest[height<=576]/\nworst', u'--ap-mso', u'Dish', u'--ap-username', u'PRIVATE', u'--ap-password', u'PRIVATE', u'--write-sub', u'--write-auto-sub', u'--sub-lang', u'en,enUS,en-us', u'--sub-format', u'ass/srt/best', u'--convert-subs', u'ass', u'--embed-subs', u'--recode-video', u'mp4', u'--mark-watched']
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.sciencechannelgo.com/through-the-wormhole-with-morgan-freeman/is-the-force-with-us/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.04.26
[debug] Python version 2.7.5 - Darwin-13.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.2.4, ffprobe 3.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Using fake IP 3.44.200.45 (US) as X-Forwarded-For.
[DiscoveryGo] is-the-force-with-us: Downloading webpage
[DiscoveryGo] is-the-force-with-us: Downloading m3u8 information
WARNING: enUS subtitles not available for 5900cd3e6b66d1822824e64e
WARNING: en-us subtitles not available for 5900cd3e6b66d1822824e64e
WARNING: Unable to download subtitle for "en": <urlopen error [Errno 1] _ssl.c:504: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure>
[debug] Invoking downloader on u'https://dscusvod-vh.akamaihd.net/i/longform/2017-04/26/151709.006.02.048-74716-,500k,200k,350k,800k,1200k,1600k,2200k,3000k,4500k,.mp4.csmil/index_5_av.m3u8?null=0&hdntl=exp=1493317227~acl=%2f*~data=hdntl~hmac=16c05cf5f33dda3290143ca884c93082586d3630d3fcc6a5fb9b1df8fcabf45c'
[download] s08e01 - Is the Force with Us.mp4 has already been downloaded
[download] 100% of 528.67MiB
[debug] ffmpeg command line: ffprobe -show_streams 'file:s08e01 - Is the Force with Us.mp4'
[ffmpeg] Fixing malformated aac bitstream in "s08e01 - Is the Force with Us.mp4"
[debug] ffmpeg command line: ffmpeg -y -i 'file:s08e01 - Is the Force with Us.mp4' -c copy -f mp4 -bsf:a aac_adtstoasc 'file:s08e01 - Is the Force with Us.temp.mp4'
[ffmpeg] Not converting video file s08e01 - Is the Force with Us.mp4 - already is in target format mp4
[ffmpeg] Converting subtitles
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/michael/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/Users/michael/bin/youtube-dl/youtube_dl/__init__.py", line 465, in main
  File "/Users/michael/bin/youtube-dl/youtube_dl/__init__.py", line 455, in _real_main
  File "/Users/michael/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1896, in download
  File "/Users/michael/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 771, in extract_info
  File "/Users/michael/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 825, in process_ie_result
  File "/Users/michael/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1539, in process_video_result
  File "/Users/michael/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1877, in process_info
  File "/Users/michael/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1942, in post_process
  File "/Users/michael/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 580, in run
  File "/Users/michael/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 206, in run_ffmpeg
  File "/Users/michael/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 180, in run_ffmpeg_multiple_files
  File "/Users/michael/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 180, in <genexpr>
OSError: [Errno 2] No such file or directory: 's08e01 - Is the Force with Us.en.xml'
keybounceMBP:Science michael$ 
```

**Comment by dstftw** [comment]
Update python.
