### ISSUE TITLE
"Failed to parse JSON' error

### ISSUE THREAD

**Issue by PhilWinger** [rg3/youtube-dl#12945]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.05.01*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.05.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2017.05.01
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```
C:\Users\Brad\Downloads\rtmpdump>youtube-dl "http://www.foxsports.com/nascar/rac
ehub/video?vid=907656771601" --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['http://www.foxsports.com/nascar/racehub/video?vid=9
07656771601', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.05.01
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-81989-g7845c13, ffprobe N-81989-g7845c13, rtmpdum
p 2.4
[debug] Proxy map: {}
[FoxSports] video?vid=907656771601: Downloading webpage
ERROR: video?vid=907656771601: Failed to parse JSON  (caused by ValueError('Expe
cting property name enclosed in double quotes: line 1 column 2 (char 1)',)); ple
ase report this issue on https://yt-dl.org/bug . Make sure you are using the lat
est version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the
 --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0io2aq9r\bu
ild\youtube_dl\extractor\common.py", line 672, in _parse_json
  File "C:\Python\Python34\lib\json\__init__.py", line 318, in loads
  File "C:\Python\Python34\lib\json\decoder.py", line 343, in decode
  File "C:\Python\Python34\lib\json\decoder.py", line 359, in raw_decode
ValueError: Expecting property name enclosed in double quotes: line 1 column 2 (
char 1)
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0io2aq9r\bu
ild\youtube_dl\extractor\common.py", line 672, in _parse_json
  File "C:\Python\Python34\lib\json\__init__.py", line 318, in loads
  File "C:\Python\Python34\lib\json\decoder.py", line 343, in decode
  File "C:\Python\Python34\lib\json\decoder.py", line 359, in raw_decode
ValueError: Expecting property name enclosed in double quotes: line 1 column 2 (
char 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0io2aq9r\bu
ild\youtube_dl\YoutubeDL.py", line 760, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0io2aq9r\bu
ild\youtube_dl\extractor\common.py", line 429, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0io2aq9r\bu
ild\youtube_dl\extractor\foxsports.py", line 36, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0io2aq9r\bu
ild\youtube_dl\extractor\common.py", line 676, in _parse_json
youtube_dl.utils.ExtractorError: video?vid=907656771601: Failed to parse JSON  (
caused by ValueError('Expecting property name enclosed in double quotes: line 1
column 2 (char 1)',)); please report this issue on https://yt-dl.org/bug . Make
sure you are using the latest version; type  youtube-dl -U  to update. Be sure t
o call youtube-dl with the --verbose flag and include its complete output.
```
---


### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

Youtube-dl fails to download videos from foxsports.com, see the errors from command line output.  This is a BUG report since foxsports.com is a supported site.   These are public videos available from their website.  I currently use youtube-dl to successfully download videos from other supported sites without any problems.

**Comment by PhilWinger** [comment]
Sorry, this format was a little confusing at first.  I believe I accidentally submitted report before completing form as requested.

**Comment by PhilWinger** [comment]
Sorry again, my first use of github.  I unintenionally closed and am now re-opening.
