### ISSUE TITLE
my.mail.ru currently not recognized

### ISSUE THREAD

**Issue by jengelh** [rg3/youtube-dl#12940]
### Before submitting an *issue* make sure you have:
- [*] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [*] [Searched](https://github.com/rg3/youtube-dl/issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [*] Site support request (request for adding support for a new site)

```
$ ./YTD -v https://my.mail.ru/video/embed/50599499340448671
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://my.mail.ru/video/embed/50599499340448671']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.05.01
[debug] Python version 2.7.12 - Linux-4.11.0-rc8-3-default-x86_64-with-SuSE-42.2-x86_64
[debug] exe versions: ffmpeg 3.3, ffprobe 3.3, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 50599499340448671: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 50599499340448671: Downloading webpage
[generic] 50599499340448671: Extracting information
ERROR: Unsupported URL: https://my.mail.ru/video/embed/50599499340448671
Traceback (most recent call last):
  File "./YTD/youtube_dl/extractor/generic.py", line 1955, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "./YTD/youtube_dl/compat.py", line 2526, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "./YTD/youtube_dl/compat.py", line 2515, in _XML
    parser.feed(text)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 14, column 111691
Traceback (most recent call last):
  File "./YTD/youtube_dl/YoutubeDL.py", line 760, in extract_info
    ie_result = ie.extract(url)
  File "./YTD/youtube_dl/extractor/common.py", line 429, in extract
    ie_result = self._real_extract(url)
  File "./YTD/youtube_dl/extractor/generic.py", line 2834, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://my.mail.ru/video/embed/50599499340448671
```
Opening the URL in a browser yields a usable <video> element, but maybe that's hidden and created on-the-fly by the javascripts?

**Comment by LoneFox78** [comment]
It's not the subdomain that causes the problem. The plugin simply doesn't support embedded videos.

**Comment by WolfganP** [comment]
My workaround: if you click in the lower right corner of the embedded video you'll be redirected to the main video page, and you'll get an URL that youtube-dl may understand (in your case it'll be https://my.mail.ru/mail/proffit/video/EuropeBestSEO/927.html)
