### ISSUE TITLE
Vice-Video Not Available in My Country

### ISSUE THREAD

**Issue by annomatik** [rg3/youtube-dl#12967]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.05.01*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.05.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

Hi! Youtube-DL keeps telling me "This video is not available in your country" for most Vice Videos, even though they show just fine through Chrome. Please help!

Example:

---

C:\>youtube-dl -v https://video.vice.com/alps/video/ulfs-wien-beruchtigste-grafitti-crew-part-1/581b12b60a0e1f4c0fb6ea2f
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://video.vice.com/alps/video/ulfs-wien-beruchtigste-grafitti-crew-part-1/581b12b60a0e1f4c0fb6ea2f']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.05.01
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-77197-gdf2ce13, ffprobe N-77197-gdf2ce13
[debug] Proxy map: {}
[Vice] ulfs-wien-beruchtigste-grafitti-crew-part-1: Downloading webpage
[Vice] 581b12b60a0e1f4c0fb6ea2f: Downloading JSON metadata
ERROR: Vice said: This video is not available in your country
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0io2aq9r\build\youtube_dl\extractor\common.py", line 498, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0io2aq9r\build\youtube_dl\YoutubeDL.py", line 2106, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
urllib.error.HTTPError: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0io2aq9r\build\youtube_dl\extractor\vice.py", line 48, in _extract_preplay_video
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0io2aq9r\build\youtube_dl\extractor\common.py", line 662, in _download_json
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0io2aq9r\build\youtube_dl\extractor\common.py", line 630, in _download_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0io2aq9r\build\youtube_dl\extractor\adobepass.py", line 1315, in _download_webpage_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0io2aq9r\build\youtube_dl\extractor\common.py", line 527, in _download_webpage_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0io2aq9r\build\youtube_dl\extractor\common.py", line 507, in _request_webpage
youtube_dl.utils.ExtractorError: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by HTTPError()); please report this issue on https://yt-d
l.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its compl
ete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0io2aq9r\build\youtube_dl\extractor\common.py", line 498, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0io2aq9r\build\youtube_dl\YoutubeDL.py", line 2106, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
urllib.error.HTTPError: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0io2aq9r\build\youtube_dl\extractor\vice.py", line 48, in _extract_preplay_video
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0io2aq9r\build\youtube_dl\extractor\common.py", line 662, in _download_json
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0io2aq9r\build\youtube_dl\extractor\common.py", line 630, in _download_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0io2aq9r\build\youtube_dl\extractor\adobepass.py", line 1315, in _download_webpage_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0io2aq9r\build\youtube_dl\extractor\common.py", line 527, in _download_webpage_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0io2aq9r\build\youtube_dl\extractor\common.py", line 507, in _request_webpage
youtube_dl.utils.ExtractorError: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by HTTPError()); please report this issue on https://yt-d
l.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its compl
ete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0io2aq9r\build\youtube_dl\YoutubeDL.py", line 760, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0io2aq9r\build\youtube_dl\extractor\common.py", line 429, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0io2aq9r\build\youtube_dl\extractor\vice.py", line 156, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0io2aq9r\build\youtube_dl\extractor\vice.py", line 52, in _extract_preplay_video
youtube_dl.utils.ExtractorError: Vice said: This video is not available in your country

**Comment by dstftw** [comment]
Post the output with `--call-home`.
In Chrome go to http://yt-dl.org/ip and post the output.

**Comment by annomatik** [comment]
http://yt-dl.org/ip says: 81.217.163.183

c:\>youtube-dl -v --call-home https://video.vice.com/alps/video/ulfs-wien-beruchtigste-grafitti-crew-part-1/581b12b60a0e1f4c0fb6ea2f
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--call-home', 'https://video.vice.com/alps/video/ulfs-wien-beruchtigste-grafitti-crew-part-1/581b12b60a0e1f4c0fb6ea2f']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.05.01
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-77197-gdf2ce13, ffprobe N-77197-gdf2ce13
[debug] Proxy map: {}
[debug] Public IP address: 81.217.163.183
[Vice] ulfs-wien-beruchtigste-grafitti-crew-part-1: Downloading webpage
[Vice] 581b12b60a0e1f4c0fb6ea2f: Downloading JSON metadata
ERROR: Vice said: This video is not available in your country
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0io2aq9r\build\youtube_dl\extractor\common.py", line 498, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0io2aq9r\build\youtube_dl\YoutubeDL.py", line 2106, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
urllib.error.HTTPError: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0io2aq9r\build\youtube_dl\extractor\vice.py", line 48, in _extract_preplay_video
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0io2aq9r\build\youtube_dl\extractor\common.py", line 662, in _download_json
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0io2aq9r\build\youtube_dl\extractor\common.py", line 630, in _download_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0io2aq9r\build\youtube_dl\extractor\adobepass.py", line 1315, in _download_webpage_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0io2aq9r\build\youtube_dl\extractor\common.py", line 527, in _download_webpage_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0io2aq9r\build\youtube_dl\extractor\common.py", line 507, in _request_webpage
youtube_dl.utils.ExtractorError: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by HTTPError()); please report this issue on https://yt-d
l.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its compl
ete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0io2aq9r\build\youtube_dl\extractor\common.py", line 498, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0io2aq9r\build\youtube_dl\YoutubeDL.py", line 2106, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
urllib.error.HTTPError: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0io2aq9r\build\youtube_dl\extractor\vice.py", line 48, in _extract_preplay_video
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0io2aq9r\build\youtube_dl\extractor\common.py", line 662, in _download_json
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0io2aq9r\build\youtube_dl\extractor\common.py", line 630, in _download_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0io2aq9r\build\youtube_dl\extractor\adobepass.py", line 1315, in _download_webpage_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0io2aq9r\build\youtube_dl\extractor\common.py", line 527, in _download_webpage_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0io2aq9r\build\youtube_dl\extractor\common.py", line 507, in _request_webpage
youtube_dl.utils.ExtractorError: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by HTTPError()); please report this issue on https://yt-d
l.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its compl
ete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0io2aq9r\build\youtube_dl\YoutubeDL.py", line 760, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0io2aq9r\build\youtube_dl\extractor\common.py", line 429, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0io2aq9r\build\youtube_dl\extractor\vice.py", line 156, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0io2aq9r\build\youtube_dl\extractor\vice.py", line 52, in _extract_preplay_video
youtube_dl.utils.ExtractorError: Vice said: This video is not available in your country

**Comment by sa7mon** [comment]
Try running it with the following flag set: `--geo-bypass-country US `

**Comment by evansoner** [comment]
I have similar problem. This flag not help in my case.

**Comment by yan12125** [comment]
Thanks for the report. Such videos will be supported in the next version.

**Comment by annomatik** [comment]
Thank You!
