### ISSUE TITLE
Unable to extract CNN url

### ISSUE THREAD

**Issue by d-damien** [rg3/youtube-dl#12972]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.05.01*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.05.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Log
```
youtube-dl --verbose http://edition.cnn.com/2010/WORLD/europe/12/11/brittany.language/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'http://edition.cnn.com/2010/WORLD/europe/12/11/brittany.language/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.05.01
[debug] Python version 2.7.6 - Linux-4.4.0-34-generic-x86_64-with-LinuxMint-17.1-rebecca
[debug] exe versions: avconv 9.20-6, avprobe 9.20-6
[debug] Proxy map: {}
[CNNArticle] brittany.language: Downloading webpage
ERROR: Unable to extract cnn url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 760, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 429, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/cnn.py", line 147, in _real_extract
    cnn_url = self._html_search_regex(r"video:\s*'([^']+)'", webpage, 'cnn url')
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 787, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 778, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
```

### Issue
CNN urls won't work. Tested with other urls.

**Comment by parmjitv** [comment]
Hi d-damien,

Are you able to view this video on the CNN site in your browser?  Nothing happens for me when I click on the Play button.

It seems CNN updated the generated html source for the edition video pages back in September, 2011.  Edition videos featured on pages prior to this date will not be detected by the extractor, as you have noted.  At any rate these videos no longer appear to be available for viewing or download.

Cheers,

Parmjit V.

**Comment by d-damien** [comment]
As of today (sorry I had forgotten I opened this issue), vidéo is definitely played in  

> Chromium 58.0.3029.110 Built on Ubuntu , running on LinuxMint 18.1 (64-bit)

Although with an error :
> 404 on http://us.cnn.com/video/data/3.0/video/international/relateds_12.xml

But it works :)

**Comment by Guiraud** [comment]
Having same issue : youtube-dl --verbose http://money.cnn.com/mostly-human/silicon-valleys-secret/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'http://money.cnn.com/mostly-human/silicon-valleys-secret/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.05.18.1
[debug] Python version 3.5.3 - Linux-4.9.0-3-amd64-x86_64-with-debian-9.0
[debug] exe versions: ffmpeg 3.2.5-1, ffprobe 3.2.5-1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] silicon-valleys-secret: Requesting header
WARNING: Falling back on generic information extractor.
[generic] silicon-valleys-secret: Downloading webpage
[generic] silicon-valleys-secret: Extracting information
ERROR: Unsupported URL: http://money.cnn.com/mostly-human/silicon-valleys-secret/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 760, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/generic.py", line 2795, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: http://money.cnn.com/mostly-human/silicon-valleys-secret/

**Comment by parmjitv** [comment]
@d-damien - Really!  Strange that the video does not play for me.  I will try again using the specs you have outlined.

@Guiraud  - This appears to be a separate issue with the extractor.  Issue #13666 has been created to attend to this.

Many thanks gentlemen!

**Comment by stinkteeth** [comment]
@d-damien xml for video;
http://us.cnn.com/video/data/3.0/video/international/2010/12/13/hooper.breton.language.cnn/index.xml
video url (best):
http://ht.cdn.turner.com/cnn/big/international/2010/12/13/hooper.breton.language.cnn_1280x720.mp4

**Comment by mk-pmb** [comment]
Same with 2021.12.17

> ERROR: Unable to extract cnn url; please report this issue on https://yt-dl.org/bug

**Comment by 89z** [comment]
I found an API for this:

~~~
GET /api/v1/documentlookup/https%3A%2F%2Fwww.cnn.com%2Fvideos%2Ftravel%2F2018%2F04%2F10%2Fexplore-parts-unknown-bourdain-little-los-angeles-little-armenia-episode-4.roads--kingdoms HTTP/2.0
Host: cerebro.api.cnn.io
authorization: Bearer f3e42d720e65004a4a911d466c62de13

cnn-app-version: 6.18.4

cnn-location: us

cnn-platform: android-phone

~~~

but for some reason, it does not work with all videos:

~~~
GET /api/v1/documentlookup/https%3A%2F%2Fmoney.cnn.com%2Fmostly-human%2Fsilicon-valleys-secret%2F HTTP/2.0
Host: cerebro.api.cnn.io
authorization: Bearer f3e42d720e65004a4a911d466c62de13

cnn-app-version: 6.18.4

cnn-location: us

cnn-platform: android-phone

~~~

so it seems the only option is to parse the HTML.
