### ISSUE TITLE
PBS Broken

### ISSUE THREAD

**Issue by helpdeskdan** [rg3/youtube-dl#12981]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.05.01*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X ] I've **verified** and **I assure** that I'm running youtube-dl **2017.05.01**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
youtube-dl -v http://www.pbs.org/wgbh/americanexperience/films/command-and-control/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'http://www.pbs.org/wgbh/americanexperience/films/command-and-control/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.05.01
[debug] Python version 2.7.12+ - Linux-4.8.0-45-generic-x86_64-with-Ubuntu-16.10-yakkety
[debug] exe versions: ffmpeg 3.0.7-0ubuntu0.16.10.1, ffprobe 3.0.7-0ubuntu0.16.10.1, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Using fake IP 3.34.115.130 (US) as X-Forwarded-For.
[pbs] Downloading JSON metadata
[pbs] command-and-control: Downloading webpage
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/bin/youtube-dl/youtube_dl/__init__.py", line 465, in main
  File "/usr/bin/youtube-dl/youtube_dl/__init__.py", line 455, in _real_main
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1896, in download
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 760, in extract_info
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 429, in extract
  File "/usr/bin/youtube-dl/youtube_dl/extractor/pbs.py", line 445, in _real_extract
  File "/usr/bin/youtube-dl/youtube_dl/extractor/pbs.py", line 427, in _extract_webpage
  File "/usr/lib/python2.7/re.py", line 141, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or buffer

<end of log>
```

---

---

### Description of your *issue*, suggested solution and other information

PBS extractor appears to be broken.  Will try to look at source code for due dilligence, but I'm not a python guru.  Thanks for your time.

**Comment by helpdeskdan** [comment]
There no partnerplayer to grep on in the iframe.  I do see cloudfront though, "https://d2ok2u3bz752mp.cloudfront.net/js/gc.js"
