### ISSUE TITLE
[pornhub] some videos are not working

### ISSUE THREAD

**Issue by dban0001** [rg3/youtube-dl#12996]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.05.01*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.05.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

```
youtube-dl "https://fr.pornhub.com/video/show?viewkey=ph578e8478012f9" --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://fr.pornhub.com/video/show?viewkey=ph578e8478012f9', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.05.01
[debug] Python version 2.7.12 - Linux-4.4.0-21-generic-x86_64-with-LinuxMint-18-sarah
[debug] exe versions: ffmpeg N-85548-g3390a2b, ffprobe N-85548-g3390a2b, rtmpdump 2.4
[debug] Proxy map: {}
[generic] show?viewkey=ph578e8478012f9: Requesting header
WARNING: Falling back on generic information extractor.
[generic] show?viewkey=ph578e8478012f9: Downloading webpage
[generic] show?viewkey=ph578e8478012f9: Extracting information
[download] Downloading playlist: None
[generic] playlist None: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[debug] Invoking downloader on u'data:"+n+";base64,"+B+"'
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 465, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 455, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1896, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 771, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 962, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 825, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1539, in process_video_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1803, in process_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1745, in dl
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 360, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 61, in real_download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2106, in urlopen
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2460, in data_open
binascii.Error: Incorrect padding
```

---

It only happens for this video, all others work. When using the latest youtube-dl version directly from github, it shows this:

```
youtube-dl "https://pornhub.com/video/show?viewkey=ph578e8478012f9" --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://pornhub.com/video/show?viewkey=ph578e8478012f9', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.05.01
[debug] Python version 2.7.12 - Linux-3.14.32-xxxx-grs-ipv6-64-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg N-82837-gb7e4ea0, ffprobe N-82837-gb7e4ea0
[debug] Proxy map: {}
[generic] show?viewkey=ph578e8478012f9: Requesting header
WARNING: Falling back on generic information extractor.
[generic] show?viewkey=ph578e8478012f9: Downloading webpage
[generic] show?viewkey=ph578e8478012f9: Extracting information
ERROR: Unsupported URL: https://pornhub.com/video/show?viewkey=ph578e8478012f9
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 760, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 429, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2834, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://pornhub.com/video/show?viewkey=ph578e8478012f9
```

**Comment by mddrill** [comment]
Why was this issue closed? I am still getting it in version 2018.08.28
