### ISSUE TITLE
How to embed a thumbnail to MKV on Windows?

### ISSUE THREAD

**Issue by bnr0723** [rg3/youtube-dl#13010]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.05.07*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.05.07**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### Log

```
youtube-dl -v --no-check-certificate --format "bestvideo+bestaudio" --write-sub --sub-lang en -o "C:\Users\bnr07\Videos\CrashCourse\CC Philosophy\%(title)s.%(ext)s" --embed-subs --embed-thumbnail --convert-subtitles srt --add-metadata --ffmpeg-location "C:\Users\bnr07\Downloads\ffmpeg\bin" --prefer-ffmpeg https://www.youtube.com/playlist?list=PL8dPuuaLjXtNgK6MZucdYldNkMybYIHKR
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--no-check-certificate', '--format', 'bestvideo+bestaudio', '--write-sub', '--sub-lang', 'en', '-o', 'C:\\Users\\bnr07\\Videos\\CrashCourse\\CC Philosophy\\%(title)s.%(ext)s', '--embed-subs', '--embed-thumbnail', '--convert-subtitles', 'srt', '--add-metadata', '--ffmpeg-location', 'C:\\Users\\bnr07\\Downloads\\ffmpeg\\bin', '--prefer-ffmpeg', 'https://www.youtube.com/playlist?list=PL8dPuuaLjXtNgK6MZucdYldNkMybYIHKR']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.05.07
[debug] Python version 3.4.4 - Windows-10-10.0.15063
[debug] exe versions: ffmpeg N-85588-g6108805, ffprobe N-85588-g6108805
[debug] Proxy map: {}
[youtube:playlist] PL8dPuuaLjXtNgK6MZucdYldNkMybYIHKR: Downloading webpage
[download] Downloading playlist: Philosophy
[youtube:playlist] playlist Philosophy: Downloading 46 videos
[download] Downloading video 1 of 46
[youtube] 1A_CAkYt3GY: Downloading webpage
[youtube] 1A_CAkYt3GY: Downloading video info webpage
[youtube] 1A_CAkYt3GY: Extracting video information
[youtube] 1A_CAkYt3GY: Downloading MPD manifest
[info] Writing video subtitles to: C:\Users\bnr07\Videos\CrashCourse\CC Philosophy\What is Philosophy - Crash Course Philosophy #1.en.vtt
[youtube] 1A_CAkYt3GY: Downloading thumbnail ...
[youtube] 1A_CAkYt3GY: Writing thumbnail to: C:\Users\bnr07\Videos\CrashCourse\CC Philosophy\What is Philosophy - Crash Course Philosophy #1.jpg
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on 'https://r6---sn-vgqs7nls.googlevideo.com/videoplayback?id=d40fc202462ddc66&itag=137&source=youtube&requiressl=yes&initcwndbps=11757500&pl=21&mm=31&ei=850OWdGlCcbJuAK2777ICA&ms=au&mv=m&mn=sn-vgqs7nls&ratebypass=yes&mime=video/mp4&gir=yes&clen=202555407&lmt=1493084098499775&dur=634.508&signature=5179713620FAB1E848877B11E97027DA06CABDBD.8B327322FC777A2E1E79B536FB3640992FA74F25&key=dg_yt0&mt=1494130099&upn=v8TTkWAsBv8&ip=173.239.240.75&ipbits=0&expire=1494151763&sparams=ip,ipbits,expire,id,itag,source,requiressl,initcwndbps,pl,mm,ei,ms,mv,mn,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: C:\Users\bnr07\Videos\CrashCourse\CC Philosophy\What is Philosophy - Crash Course Philosophy #1.f137.mp4
[download] 100% of 193.17MiB in 00:17
[debug] Invoking downloader on 'https://r6---sn-vgqs7nls.googlevideo.com/videoplayback?mime=audio%2Fwebm&upn=6619WOfWdnY&id=o-APBQjxi19vakn5HLQRGN92y8M7CgVhNSJfCLycQvglPe&dur=634.521&mt=1494130043&pl=21&mv=m&ms=au&requiressl=yes&mm=31&ip=173.239.240.75&mn=sn-vgqs7nls&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&lmt=1493085885045434&gir=yes&ipbits=0&clen=10317485&itag=251&source=youtube&signature=1904E693D5C3E8E9E7D748F1C505B29BE8932B1E.0466E1B115A4161D16908C59C1EA4732CF9423DD&key=yt6&keepalive=yes&ei=8p0OWZ6AIJSUuAL9u6ygAw&expire=1494151762&initcwndbps=1356250&ratebypass=yes'
[download] Destination: C:\Users\bnr07\Videos\CrashCourse\CC Philosophy\What is Philosophy - Crash Course Philosophy #1.f251.webm
[download] 100% of 9.84MiB in 00:00
[ffmpeg] Merging formats into "C:\Users\bnr07\Videos\CrashCourse\CC Philosophy\What is Philosophy - Crash Course Philosophy #1.mkv"
[debug] ffmpeg command line: 'C:\Users\bnr07\Downloads\ffmpeg\bin\ffmpeg' -y -i 'file:C:\Users\bnr07\Videos\CrashCourse\CC Philosophy\What is Philosophy - Crash Course Philosophy #1.f137.mp4' -i 'file:C:\Users\bnr07\Videos\CrashCourse\CC Philosophy\What is Philosophy - Crash Course Philosophy #1.f251.webm' -c copy -map 0:v:0 -map 1:a:0 'file:C:\Users\bnr07\Videos\CrashCourse\CC Philosophy\What is Philosophy - Crash Course Philosophy #1.temp.mkv'
Deleting original file C:\Users\bnr07\Videos\CrashCourse\CC Philosophy\What is Philosophy - Crash Course Philosophy #1.f137.mp4 (pass -k to keep)
Deleting original file C:\Users\bnr07\Videos\CrashCourse\CC Philosophy\What is Philosophy - Crash Course Philosophy #1.f251.webm (pass -k to keep)
[ffmpeg] Adding metadata to 'C:\Users\bnr07\Videos\CrashCourse\CC Philosophy\What is Philosophy - Crash Course Philosophy #1.mkv'
[debug] ffmpeg command line: 'C:\Users\bnr07\Downloads\ffmpeg\bin\ffmpeg' -y -i 'file:C:\Users\bnr07\Videos\CrashCourse\CC Philosophy\What is Philosophy - Crash Course Philosophy #1.mkv' -c copy -metadata 'description=Today Hank begins to teach you about Philosophy by discussing the historical origins of philosophy in ancient Greece, and its three main divisions: metaphysics, epistemology, and value theory. He will also introduce logic, and how you’re going to use it to understand and critically evaluate a whole host of different worldviews throughout this course. And also, hopefully, the rest of your life.

--

Images and video via VideoBlocks or Wikimedia Commons, licensed under Creative Commons by 4.0:
https://creativecommons.org/licenses/by/4.0/

--

Produced in collaboration with PBS Digital Studios: http://youtube.com/pbsdigitalstudios

Crash Course Philosophy is sponsored by Squarespace.
http://www.squarespace.com/crashcourse

--

Want to find Crash Course elsewhere on the internet?
Facebook - http://www.facebook.com/YouTubeCrashCourse
Twitter - http://www.twitter.com/TheCrashCourse
Tumblr - http://thecrashcourse.tumblr.com
Support CrashCourse on Patreon: http://www.patreon.com/crashcourse

CC Kids: http://www.youtube.com/crashcoursekids' -metadata 'title=What is Philosophy?: Crash Course Philosophy #1' -metadata 'comment=Today Hank begins to teach you about Philosophy by discussing the historical origins of philosophy in ancient Greece, and its three main divisions: metaphysics, epistemology, and value theory. He will also introduce logic, and how you’re going to use it to understand and critically evaluate a whole host of different worldviews throughout this course. And also, hopefully, the rest of your life.

--

Images and video via VideoBlocks or Wikimedia Commons, licensed under Creative Commons by 4.0:
https://creativecommons.org/licenses/by/4.0/

--

Produced in collaboration with PBS Digital Studios: http://youtube.com/pbsdigitalstudios

Crash Course Philosophy is sponsored by Squarespace.
http://www.squarespace.com/crashcourse

--

Want to find Crash Course elsewhere on the internet?
Facebook - http://www.facebook.com/YouTubeCrashCourse
Twitter - http://www.twitter.com/TheCrashCourse
Tumblr - http://thecrashcourse.tumblr.com
Support CrashCourse on Patreon: http://www.patreon.com/crashcourse

CC Kids: http://www.youtube.com/crashcoursekids' -metadata 'purl=https://www.youtube.com/watch?v=1A_CAkYt3GY' -metadata date=20160208 -metadata artist=CrashCourse 'file:C:\Users\bnr07\Videos\CrashCourse\CC Philosophy\What is Philosophy - Crash Course Philosophy #1.temp.mkv'
[ffmpeg] Converting subtitles
[debug] ffmpeg command line: 'C:\Users\bnr07\Downloads\ffmpeg\bin\ffmpeg' -y -i 'file:C:\Users\bnr07\Videos\CrashCourse\CC Philosophy\What is Philosophy - Crash Course Philosophy #1.en.vtt' -f srt 'file:C:\Users\bnr07\Videos\CrashCourse\CC Philosophy\What is Philosophy - Crash Course Philosophy #1.en.srt'
Deleting original file C:\Users\bnr07\Videos\CrashCourse\CC Philosophy\What is Philosophy - Crash Course Philosophy #1.en.vtt (pass -k to keep)
[ffmpeg] Embedding subtitles in 'C:\Users\bnr07\Videos\CrashCourse\CC Philosophy\What is Philosophy - Crash Course Philosophy #1.mkv'
[debug] ffmpeg command line: 'C:\Users\bnr07\Downloads\ffmpeg\bin\ffmpeg' -y -i 'file:C:\Users\bnr07\Videos\CrashCourse\CC Philosophy\What is Philosophy - Crash Course Philosophy #1.mkv' -i 'file:C:\Users\bnr07\Videos\CrashCourse\CC Philosophy\What is Philosophy - Crash Course Philosophy #1.en.srt' -map 0 -c copy -map -0:s -map 1:0 -metadata:s:s:0 language=eng 'file:C:\Users\bnr07\Videos\CrashCourse\CC Philosophy\What is Philosophy - Crash Course Philosophy #1.temp.mkv'
Deleting original file C:\Users\bnr07\Videos\CrashCourse\CC Philosophy\What is Philosophy - Crash Course Philosophy #1.en.srt (pass -k to keep)
ERROR: Only mp3 and m4a/mp4 are supported for thumbnail embedding for now.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpt73_83v_\build\youtube_dl\YoutubeDL.py", line 1942, in post_process
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpt73_83v_\build\youtube_dl\postprocessor\embedthumbnail.py", line 90, in run
youtube_dl.postprocessor.embedthumbnail.EmbedThumbnailPPError: Only mp3 and m4a/mp4 are supported for thumbnail embedding for now.
```

---

### Issue

I am trying to have thumbnails from YouTube videos embedded into MKV files. I cannot figure out how to do this on Windows. I searched around on here, and all I found were seemingly non-Windows answers that were also beyond my expertise.

How can I have youtube-dl embed thumbnails to MKV outputs on Windows? (I am using ffmpeg)

Also, on a slight side note, the metadata is incorrect on the MKV file. What is going on?

**Comment by dstftw** [comment]
Embedding in mkv is not supported.

**Comment by bnr0723** [comment]
Yes, I know that. I read the last line of the log. Other people have talked about a workaround on Linux, so I was just asking if there was a known/possible workaround for Windows.

So, there is no workaround for Windows?
