### ISSUE TITLE
Downloading all the videos for a search result

### ISSUE THREAD

**Issue by Logmytech** [rg3/youtube-dl#13044]
I have a few doubts and questions.

I download youtube search results by using `youtube-dl -iltc "https://youtube.com/results?search_query=Pewdiepie" --match-title pewdiepie`. 
But it downloads only about 20 videos.
What if I want to download all the results even though it may be infinite.

Can I use `youtube-dl "ytsearch:pewdipie"` for downloading multiple(unlimited) results?

**Comment by dstftw** [comment]
`ytsearch<N|all>:pewdipie`.

**Comment by McSinyx** [comment]
Hi there, I'm not sure why that doesn't work on my machine:

```
$ youtube-dl "ytsearch<N|all>:pewdipie" -vJ --flat-playlist
[debug] System config: []
[debug] User config: ['--external-downloader=aria2c', '--format=best']
[debug] Custom config: []
[debug] Command-line args: ['ytsearch<N|all>:pewdipie', '-vJ', '--flat-playlist']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.05.14
[debug] Python version 3.5.3 - Linux-4.9.0-2-686-pae-i686-with-debian-9.0
[debug] exe versions: ffmpeg 3.2.4-1, ffprobe 3.2.4-1
[debug] Proxy map: {}
ERROR: 'ytsearch<N|all>:pewdipie' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:ytsearch<N|all>:pewdipie" ) to search YouTube
Traceback (most recent call last):
  File "/home/cnx/.local/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 760, in extract_info
    ie_result = ie.extract(url)
  File "/home/cnx/.local/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "/home/cnx/.local/lib/python3.5/site-packages/youtube_dl/extractor/generic.py", line 1860, in _real_extract
    % (url, url), expected=True)
youtube_dl.utils.ExtractorError: 'ytsearch<N|all>:pewdipie' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:ytsearch<N|all>:pewdipie" ) to search YouTube
```

**Comment by Logmytech** [comment]
@McSinyx You have to use it like this `youtube-dl "ytsearch30:pewdipie"`. Without `<>` or `|` . This downloads the first 30 videos. I guess if you want all vids for pewdipie search you need `youtube-dl "ytsearchall:pwediepie"`

**Comment by Hrxn** [comment]
All vids with `"pewdiepie"` included in their title?
That will be a lot. Like really a lot.
