### ISSUE TITLE
[Site support request] add www.ludo.fr player playlists of FranceTV site

### ISSUE THREAD

**Issue by ymartin59** [rg3/youtube-dl#13087]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.05.14*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.05.14**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [X] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
~/bin/youtube-dl -v --proxy $http_proxy --write-description --write-info-json --ignore-errors http://www.ludo.fr/heros/star-wars-rebels
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--proxy', u'http://hidden', u'--write-description', u'--write-info-json', u'--ignore-errors', u'http://www.ludo.fr/heros/star-wars-rebels']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.05.14
[debug] Python version 2.7.12 - Linux-3.2.40-i686-with-glibc2.0
[debug] exe versions: ffmpeg 3.2.2, ffprobe 3.2.2, rtmpdump 2.4
[debug] Proxy map: {u'http': u'http://46.218.85.101:3129', u'https': u'http://46.218.85.101:3129'}
[generic] star-wars-rebels: Requesting header
WARNING: Falling back on generic information extractor.
[generic] star-wars-rebels: Downloading webpage
[generic] star-wars-rebels: Extracting information
ERROR: Unsupported URL: http://www.ludo.fr/heros/star-wars-rebels
Traceback (most recent call last):
  File "/var/services/homes/admin/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1970, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/var/services/homes/admin/bin/youtube-dl/youtube_dl/compat.py", line 2526, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/var/services/homes/admin/bin/youtube-dl/youtube_dl/compat.py", line 2515, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 2, column 70
Traceback (most recent call last):
  File "/var/services/homes/admin/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 760, in extract_info
    ie_result = ie.extract(url)
  File "/var/services/homes/admin/bin/youtube-dl/youtube_dl/extractor/common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "/var/services/homes/admin/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2795, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.ludo.fr/heros/star-wars-rebels
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Playlist: http://www.ludo.fr/heros/star-wars-rebels
- Playlist: http://www.ludo.fr/heros/il-etait-une-fois-la-vie

---

### Description

Playlists in subdomain sites like `www.ludo.fr` refers to videos for which I cannot find URLs at https://www.france.tv/

For instance, these two playlists have more videos available from `www.ludo.fr` than at
- https://www.france.tv/france-4/star-wars-rebels/
- https://www.france.tv/france-4/il-etait-une-fois-la-vie/

Again well done for this great tool !

**Comment by ymartin59** [comment]
I started some code for that but it is still really draft as it is my first IE for youtube-dl...

**Comment by ymartin59** [comment]
I found a good trick to get full playlist the best way (single call, pure JSON returned): http://www.ludo.fr/heros/il-etait-une-fois-la-vie/playlist?limit=20&offset=0
