### ISSUE TITLE
[tv2hu] Unable to extract format url

### ISSUE THREAD

**Issue by Vukkk** [rg3/youtube-dl#13088]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.05.14*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.05.14**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl --verbose http://tv2.hu/musoraink/extrem_activity/235503_extrem-activity---23.-adas-1.-resz.html
[debug] System config: []
[debug] User config: [u'--retries', u'infinite', u'--fragment-retries', u'infinite', u'--buffer-size', u'1024K', u'--external-downloader', u'aria2c.exe', u'--external-downloader-args', u'-x4 -m5 -t10', u'--fixup', u'warn']
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'http://tv2.hu/musoraink/extrem_activity/235503_extrem-activity---23.-adas-1.-resz.html']
[debug] Encodings: locale cp1250, fs mbcs, out cp852, pref cp1250
[debug] youtube-dl version 2017.05.14
[debug] Python version 2.7.11 - Windows-10-10.0.10586
[debug] exe versions: ffmpeg 3.2.4, ffprobe 3.2.4
[debug] Proxy map: {}
[tv2.hu] 235503: Downloading webpage
[tv2.hu] 235503: Downloading JSON metadata
ERROR: Unable to extract format url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.py", line 760, in extract_info
    ie_result = ie.extract(url)
  File "youtube_dl\extractor\common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "youtube_dl\extractor\tv2hu.py", line 43, in _real_extract
    m3u8_url, video_id, skip_protocols=['rtmp', 'rtsp']))
  File "youtube_dl\extractor\common.py", line 2208, in _extract_wowza_formats
    url_base = self._search_regex(r'(?:https?|rtmp|rtsp)(://[^?]+)', url, 'format url')
  File "youtube_dl\extractor\common.py", line 782, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract format url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by Vukkk** [comment]
The problem is the [m3u8_url](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/tv2hu.py#L39) variable does not contain any protocol, so it starts with `//`.
I'm not sure if it is the best solution, but adding `http:` in front of it fixes the issue:
```
m3u8_url = 'http:' + bitrates.get('hls')
```
