### ISSUE TITLE
cloudtime.to video - RegexNotFoundError: Unable to extract title

### ISSUE THREAD

**Issue by aghu** [rg3/youtube-dl#13108]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.05.14*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.05.14**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The purpose of this *issue* is a *bug report*. Full verbose output follows:

```
$ youtube-dl -F --verbose http://www.cloudtime.to/video/e87faf2d0b099
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-F', u'--verbose', u'http://www.cloudtime.to/video/e87faf2d0b099']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.05.14
[debug] Python version 2.7.10 - Windows-XP-5.1.2600-SP3
[debug] exe versions: ffmpeg N-71403-g415f1fa, ffprobe N-71403-g415f1fa
[debug] Proxy map: {}
[cloudtime] e87faf2d0b099: Downloading video page
[cloudtime] e87faf2d0b099: Downloading continue to the video page
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "PYTHON_ROOT\lib\site-packages\youtube_dl\YoutubeDL.py", line 760, in extract_info
    ie_result = ie.extract(url)
  File "PYTHON_ROOT\lib\site-packages\youtube_dl\extractor\common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "PYTHON_ROOT\lib\site-packages\youtube_dl\extractor\novamov.py", line 81, in _real_extract
    title = self._html_search_regex(self._TITLE_REGEX, webpage, 'title')
  File "PYTHON_ROOT\lib\site-packages\youtube_dl\extractor\common.py", line 791, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "PYTHON_ROOT\lib\site-packages\youtube_dl\extractor\common.py", line 782, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

### Description of the *issue*

- Trying to download video from http://www.cloudtime.to/video/e87faf2d0b099 
- I'm able to watch it from the browser at the time of writing this issue.
- I installed/upgraded **youtube-dl** with **`pip install -U youtube-dl`**

**Comment by aghu** [comment]
Hi @dstftw !

Is it duplicate of Issue [#11331](https://github.com/rg3/youtube-dl/issues/11331)?

Issue [#11331](https://github.com/rg3/youtube-dl/issues/11331) mentions **filekey**, but in this issue mention **title**.

Also, tracebacks show different function calls.

Thanks anyway :-D
