### ISSUE TITLE
Error Downloading youtube Katy Perry - Roar MP3

### ISSUE THREAD

**Issue by harshil93** [rg3/youtube-dl#13115]
```
$ youtube-dl-mp3 https://www.youtube.com/watch?v=CevxZvSJLk8 --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--extract-audio', '--audio-format', 'mp3', '-o', '%(title)s.%(ext)s', 'https://www.youtube.com/watch?v=CevxZvSJLk8', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.02.27
[debug] Python version 3.4.4 - Windows-10-10.0.15063
[debug] exe versions: ffmpeg N-74505-gc1507db, ffprobe N-74505-gc1507db
[debug] Proxy map: {}
[youtube] CevxZvSJLk8: Downloading webpage
[youtube] CevxZvSJLk8: Downloading video info webpage
[youtube] CevxZvSJLk8: Extracting video information
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {22} signature length 40.40, html5 player None
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp8vj_ibhq\build\youtube_dl\extractor\youtube.py", line 1070, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp8vj_ibhq\build\youtube_dl\extractor\youtube.py", line 958, in _extract_signature_function
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflxXnk_G/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflxXnk_G/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp8vj_ibhq\build\youtube_dl\extractor\youtube.py", line 1070, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp8vj_ibhq\build\youtube_dl\extractor\youtube.py", line 958, in _extract_signature_function
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflxXnk_G/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp8vj_ibhq\build\youtube_dl\extractor\youtube.py", line 1070, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp8vj_ibhq\build\youtube_dl\extractor\youtube.py", line 958, in _extract_signature_function
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflxXnk_G/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp8vj_ibhq\build\youtube_dl\YoutubeDL.py", line 761, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp8vj_ibhq\build\youtube_dl\extractor\common.py", line 427, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp8vj_ibhq\build\youtube_dl\extractor\youtube.py", line 1659, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp8vj_ibhq\build\youtube_dl\extractor\youtube.py", line 1080, in _decrypt_signature
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp8vj_ibhq\build\youtube_dl\extractor\youtube.py", line 1070, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp8vj_ibhq\build\youtube_dl\extractor\youtube.py", line 958, in _extract_signature_function
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflxXnk_G/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflxXnk_G/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by harshil93** [comment]
Using old version.
