### ISSUE TITLE
TypeError: not all arguments converted during string formatting

### ISSUE THREAD

**Issue by TheBITLINK** [rg3/youtube-dl#13134]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.05.18*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.05.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl --verbose -4jf bestaudio/best "https://www.youtube.com/watch?v=OFqeoXFSlms"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'-4jf', u'bestaudio/best', u'https://www.youtube.com/watch?v=OFqeoXFSlms']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.05.18
[debug] Python version 2.7.12 - Linux-4.4.0-78-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg N-85581-ge22d495538-static, ffprobe N-85581-ge22d495538-static
[debug] Proxy map: {}
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "./node_modules/ytdl-getinfo/ytdl/youtube-dl/youtube_dl/extractor/youtube.py", line 1162, in _decrypt_signature
    video_id, player_url, s
  File "./node_modules/ytdl-getinfo/ytdl/youtube-dl/youtube_dl/extractor/youtube.py", line 1085, in _extract_signature_function
    cache_res = res(test_string)
  File "./node_modules/ytdl-getinfo/ytdl/youtube-dl/youtube_dl/extractor/youtube.py", line 1138, in <lambda>
    return lambda s: initial_function([s])
  File "./node_modules/ytdl-getinfo/ytdl/youtube-dl/youtube_dl/jsinterp.py", line 255, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "./node_modules/ytdl-getinfo/ytdl/youtube-dl/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "./node_modules/ytdl-getinfo/ytdl/youtube-dl/youtube_dl/jsinterp.py", line 143, in interpret_expression
    self._objects[variable] = self.extract_object(variable)
  File "./node_modules/ytdl-getinfo/ytdl/youtube-dl/youtube_dl/jsinterp.py", line 219, in extract_object
    r'\}\s*;' % _FUNC_NAME_RE,
TypeError: not all arguments converted during string formatting
 (caused by TypeError('not all arguments converted during string formatting',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "./node_modules/ytdl-getinfo/ytdl/youtube-dl/youtube_dl/extractor/youtube.py", line 1162, in _decrypt_signature
    video_id, player_url, s
  File "./node_modules/ytdl-getinfo/ytdl/youtube-dl/youtube_dl/extractor/youtube.py", line 1085, in _extract_signature_function
    cache_res = res(test_string)
  File "./node_modules/ytdl-getinfo/ytdl/youtube-dl/youtube_dl/extractor/youtube.py", line 1138, in <lambda>
    return lambda s: initial_function([s])
  File "./node_modules/ytdl-getinfo/ytdl/youtube-dl/youtube_dl/jsinterp.py", line 255, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "./node_modules/ytdl-getinfo/ytdl/youtube-dl/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "./node_modules/ytdl-getinfo/ytdl/youtube-dl/youtube_dl/jsinterp.py", line 143, in interpret_expression
    self._objects[variable] = self.extract_object(variable)
  File "./node_modules/ytdl-getinfo/ytdl/youtube-dl/youtube_dl/jsinterp.py", line 219, in extract_object
    r'\}\s*;' % _FUNC_NAME_RE,
TypeError: not all arguments converted during string formatting
Traceback (most recent call last):
  File "./node_modules/ytdl-getinfo/ytdl/youtube-dl/youtube_dl/YoutubeDL.py", line 760, in extract_info
    ie_result = ie.extract(url)
  File "./node_modules/ytdl-getinfo/ytdl/youtube-dl/youtube_dl/extractor/common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "./node_modules/ytdl-getinfo/ytdl/youtube-dl/youtube_dl/extractor/youtube.py", line 1755, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "./node_modules/ytdl-getinfo/ytdl/youtube-dl/youtube_dl/extractor/youtube.py", line 1172, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "./node_modules/ytdl-getinfo/ytdl/youtube-dl/youtube_dl/extractor/youtube.py", line 1162, in _decrypt_signature
    video_id, player_url, s
  File "./node_modules/ytdl-getinfo/ytdl/youtube-dl/youtube_dl/extractor/youtube.py", line 1085, in _extract_signature_function
    cache_res = res(test_string)
  File "./node_modules/ytdl-getinfo/ytdl/youtube-dl/youtube_dl/extractor/youtube.py", line 1138, in <lambda>
    return lambda s: initial_function([s])
  File "./node_modules/ytdl-getinfo/ytdl/youtube-dl/youtube_dl/jsinterp.py", line 255, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "./node_modules/ytdl-getinfo/ytdl/youtube-dl/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "./node_modules/ytdl-getinfo/ytdl/youtube-dl/youtube_dl/jsinterp.py", line 143, in interpret_expression
    self._objects[variable] = self.extract_object(variable)
  File "./node_modules/ytdl-getinfo/ytdl/youtube-dl/youtube_dl/jsinterp.py", line 219, in extract_object
    r'\}\s*;' % _FUNC_NAME_RE,
TypeError: not all arguments converted during string formatting
 (caused by TypeError('not all arguments converted during string formatting',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

### Description of your *issue*, suggested solution and other information

This is only happening with some specific videos, for example, https://www.youtube.com/watch?v=xuCn8ux2gbs is working fine, but https://www.youtube.com/watch?v=OFqeoXFSlms isn't

**Comment by perfaram** [comment]
I'm running 2017.05.18 too and have the very same issue.

**Comment by lawlmart** [comment]
The fix to #13123 seems to have regressed.

**Comment by ehmo** [comment]
Yes, the reason is that @dstftw [introduced an error into the code](https://github.com/rg3/youtube-dl/commit/7769f837018cbfa6cab615b8ae938528f895ce8c)

**Comment by MaskedDeath** [comment]
I'm also getting this bug. Updated to the newest version, and it still keeps occurring. It depends on the video. The part of log when it's trying to play:

Downloading webpage
Downloading embed webpage

and either it works after printing:

Extracting video information

or doesn't work after printing:

Downloading js player
