### ISSUE TITLE
Signature extraction failed

### ISSUE THREAD

**Issue by chmaynard** [rg3/youtube-dl#13152]
Details at https://gist.github.com/chmaynard/a2d724a03f0147798ba51f948f41e244

I'm using the latest version in Homebrew: 2017.05.14

**Comment by joshuamfawcett** [comment]
Having the exact same issue 
`[0;31mERROR:[0m Signature extraction failed: Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1081, in _decrypt_signature
    video_id, player_url, s
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1004, in _extract_signature_function
    cache_res = res(test_string)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1057, in <lambda>
    return lambda s: initial_function([s])
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 254, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 55, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 211, in interpret_expression
    raise ExtractorError('Unsupported JS expression %r' % expr)
youtube_dl.utils.ExtractorError: Unsupported JS expression 'oE["do"](a,67)'
 (caused by ExtractorError('Unsupported JS expression \'oE["do"](a,67)\'',))`

**Comment by Hrxn** [comment]
Outdated versions of youtube-dl.

**Comment by XCanG** [comment]
@dstftw What if I get similar error, but I already upgrade my package yesterday to .18.1?
```
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1070, in _decrypt_signature
    video_id, player_url, s
  File "C:\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 958, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflJ6jfXc/en_US/base.js'
 (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflJ6jfXc/en_US/base.js'",))
```
I tried to force reinstall package, but it not helps:
```
python -m pip install -I youtube-dl
Collecting youtube-dl
  Using cached youtube_dl-2017.5.18.1-py2.py3-none-any.whl
Installing collected packages: youtube-dl
Successfully installed youtube-dl-2017.5.18.1
```
