### ISSUE TITLE
SITE REQUEST: pruffme.com webinars live video downloads

### ISSUE THREAD

**Issue by nmr50** [rg3/youtube-dl#13163]
Hello dearest coders!
I want to ask you to code this pruffme.com site into YDL so it will get live feed to one .mp4 file, or what video format it has.
The log:
R:\0.VYBORY2016_camrip>youtube-dl.exe -F -v https://pruffme.com/a1eae7cd-662c-4938-9d19-2448fb34db0d
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-F', '-v', 'https://pruffme.com/a1eae7cd-662c-4938-9d19-2448fb34db0d']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2017.05.18.1
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 3.2.4, ffprobe 3.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[generic] a1eae7cd-662c-4938-9d19-2448fb34db0d: Requesting header
WARNING: Falling back on generic information extractor.
[generic] a1eae7cd-662c-4938-9d19-2448fb34db0d: Downloading webpage
[generic] a1eae7cd-662c-4938-9d19-2448fb34db0d: Extracting information
ERROR: Unsupported URL: https://pruffme.com/a1eae7cd-662c-4938-9d19-2448fb34db0d
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpwgfs80it\build\youtube_dl\YoutubeDL.py", line 760,in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpwgfs80it\build\youtube_dl\extractor\common.py", line 433, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpwgfs80it\build\youtube_dl\extractor\generic.py", line 2795, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://pruffme.com/a1eae7cd-662c-4938-9d19-2448fb34db0d
---
This video feed will be online for 3 hours only since 19:20 UTC+03 (22 minutes already passed), so - if you can, please take a look at that flash video url ASAP!:)

Thanks in advance!!!

**Comment by dstftw** [comment]
There is no video at this URL.

**Comment by nmr50** [comment]
<video autoplay="1" id="ed41c3fb544d05460eb3f0a1ba6a98e2_video" poster1="https://130422.selcdn.ru/pruffme/user/7cca4a9404acc5243f0b77c16ff4a477/logos/43cd8e1c4eba6702867b4ebe2d7cdb30_big.jpg" src="blob:https://pruffme.com/a1eae7cd-662c-4938-9d19-2448fb34db0d"></video>

This is what I see in html debug, that is pointing to this video...
BTW, the player on site points on the same video...

**Comment by dstftw** [comment]
No such code:
```
$ curl -s https://pruffme.com/a1eae7cd-662c-4938-9d19-2448fb34db0d | grep '</video'
$ 
```

**Comment by nmr50** [comment]
OK, man, I just tried to point "video url", seems like it does not work - or - this pruffme.com has its own protection schemes, heck! Can you check out source url by yourself and see how it works ? The video/audio feed is transmitting right now, url is - once again again - :
https://pruffme.com/webinar/?id=708350956fa29442d5f1743fc7b53e8d

Many thanks in advance !
