### ISSUE TITLE
Signature extraction failed

### ISSUE THREAD

**Issue by Takesikaityo** [rg3/youtube-dl#13160]
## Signature extraction failed: Traceback (most recent call last)

OS : Windows10 Home 64bit
Type : exe
commandline : WindowsPowerShelll

```
$ PS C:\xampp\htdocs\ytdl> youtube-dl "http://youtube.com/watch?v=4aQDOUbErNg"
[youtube] 4aQDOUbErNg: Downloading webpage
[youtube] 4aQDOUbErNg: Downloading video info webpage
[youtube] 4aQDOUbErNg: Extracting video information
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpam8ojdsi\build\youtube_dl\extractor\youtube.py", line 1081, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpam8ojdsi\build\youtube_dl\extractor\youtube.py", line 969, in _extract_signature_function
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vfl4Xq3l4/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vfl4Xq3l4/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
...
<end of log>
```

I also tried https.

```
$ PS C:\xampp\htdocs\ytdl> youtube-dl "https://youtube.com/watch?v=4aQDOUbErNg"
[youtube] 4aQDOUbErNg: Downloading webpage
[youtube] 4aQDOUbErNg: Downloading video info webpage
[youtube] 4aQDOUbErNg: Extracting video information
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpam8ojdsi\build\youtube_dl\extractor\youtube.py", line 1081, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpam8ojdsi\build\youtube_dl\extractor\youtube.py", line 969, in _extract_signature_function
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vfl4Xq3l4/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vfl4Xq3l4/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
...
<end of log>
```

I also tried this.

```
$ PS C:\xampp\htdocs\ytdl> youtube-dl "youtube.com/watch?v=4aQDOUbErNg"
WARNING: The url doesn't specify the protocol, trying with http
[youtube] 4aQDOUbErNg: Downloading webpage
[youtube] 4aQDOUbErNg: Downloading video info webpage
[youtube] 4aQDOUbErNg: Extracting video information
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpam8ojdsi\build\youtube_dl\extractor\youtube.py", line 1081, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpam8ojdsi\build\youtube_dl\extractor\youtube.py", line 969, in _extract_signature_function
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vfl4Xq3l4/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vfl4Xq3l4/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
...
<end of log>
```

**Comment by dstftw** [comment]
Outdated version.
