### ISSUE TITLE
[hollywoodlife] site support request

### ISSUE THREAD

**Issue by RuneMagle** [rg3/youtube-dl#13166]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.05.18.1**
### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
```
C:\Users\Desktop\youtube-dl>youtube-dl.exe -f best --all-subs http://hollywoodlife.com/2017/05/19/andi-mack-dad-jonah-sneak-peek-episode-video/ -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'best', '--all-subs', 'http://hollywoodlife.com/2017/05/19/andi-mack-dad-jonah-sneak-peek-episode-video/', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.05.18.1
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-83034-gf48b6b8, ffprobe N-83096-g6596b34
[debug] Proxy map: {}
[generic] andi-mack-dad-jonah-sneak-peek-episode-video: Requesting header
WARNING: Falling back on generic information extractor.
[generic] andi-mack-dad-jonah-sneak-peek-episode-video: Downloading webpage
[generic] andi-mack-dad-jonah-sneak-peek-episode-video: Extracting information
ERROR: Unsupported URL: http://hollywoodlife.com/2017/05/19/andi-mack-dad-jonah-sneak-peek-episode-video/
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpwgfs80it\build\youtube_dl\YoutubeDL.py", line 760, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpwgfs80it\build\youtube_dl\extractor\common.py", line 433, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpwgfs80it\build\youtube_dl\extractor\generic.py", line 2795, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: http://hollywoodlife.com/2017/05/19/andi-mack-dad-jonah-sneak-peek-episode-video/
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://hollywoodlife.com/2017/05/19/andi-mack-dad-jonah-sneak-peek-episode-video/
- Single video: http://hollywoodlife.com/2017/05/05/quantico-sneak-peek-scene-new-episode-video/
- Single video: http://hollywoodlife.com/2017/04/18/pretty-little-liars-premiere-sneak-peek-spencer-mary-drake-video/

### Description of my *ssue
Can you add hollywoodlife.com? Thanks!

**Comment by RuneMagle** [comment]
nvm
