### ISSUE TITLE
[YouTube] Crash when downloading playlist with private video in it

### ISSUE THREAD

**Issue by formtapez** [rg3/youtube-dl#13170]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.05.18.1**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)

---

```
form@server:~$ youtube-dl -v https://www.youtube.com/playlist?list=PLLyofhmfnvHLsg3ECsSlH6i7d74vNYXd9
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/playlist?list=PLLyofhmfnvHLsg3ECsSlH6i7d74vNYXd9']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.05.18.1
[debug] Python version 2.7.12 - Linux-4.4.0-77-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:playlist] PLLyofhmfnvHLsg3ECsSlH6i7d74vNYXd9: Downloading webpage
[download] Downloading playlist: Testplaylist
[youtube:playlist] playlist Testplaylist: Downloading 3 videos
[download] Downloading video 1 of 3
[youtube] 2HQStlsMD6A: Downloading webpage
[youtube] 2HQStlsMD6A: Downloading video info webpage
[youtube] 2HQStlsMD6A: Extracting video information
[youtube] 2HQStlsMD6A: Downloading MPD manifest
[youtube] 2HQStlsMD6A: Downloading MPD manifest
[debug] Invoking downloader on u'https://r1---sn-4g5e6ne6.googlevideo.com/videoplayback/id/d87412b65b0c0fa0/itag/136/source/yt_otf/requiressl/yes/ei/CxQgWZ6xL9T1WviTk6gB/ms/au/mv/m/mm/31/mn/sn-4g5e6ne6/initcwndbps/1002500/pl/34/ratebypass/yes/mime/video%2Fmp4/otfp/1/otf/1/lmt/1495273933945982/mt/1495274421/key/dg_yt0/signature/42CE12E364D90D11F457A06C4879F5D37983C327.409324FBA4699A551FCA5DF0018AE421C82E4B91/upn/bM0Ap3teHuk/ip/2003:d5:63cc:600:bf61:7e58:f914:49c5/ipbits/0/expire/1495296107/sparams/ip,ipbits,expire,id,itag,source,requiressl,ei,ms,mv,mm,mn,initcwndbps,pl,ratebypass,mime,otfp,otf,lmt/'
[dashsegments] Total fragments: 58
[download] Destination: Testvideo 1 - Not Listed-2HQStlsMD6A.f136.mp4
[download] 100% of 2.22MiB in 00:12
[debug] Invoking downloader on u'https://r1---sn-4g5e6ne6.googlevideo.com/videoplayback/id/d87412b65b0c0fa0/itag/140/source/youtube/requiressl/yes/ei/CxQgWZ6xL9T1WviTk6gB/ms/au/mv/m/mm/31/mn/sn-4g5e6ne6/initcwndbps/1002500/pl/34/ratebypass/yes/mime/audio%2Fmp4/otfp/1/gir/yes/clen/4774496/lmt/1495273919206161/dur/300.350/mt/1495274421/key/dg_yt0/signature/70C63728BD4560883927D8DB9EF2D0D6A2B48D7D.01421D265DD0AEFB6D821E9B696AC785F651D346/upn/bM0Ap3teHuk/ip/2003:d5:63cc:600:bf61:7e58:f914:49c5/ipbits/0/expire/1495296107/sparams/ip,ipbits,expire,id,itag,source,requiressl,ei,ms,mv,mm,mn,initcwndbps,pl,ratebypass,mime,otfp,gir,clen,lmt,dur/'
[dashsegments] Total fragments: 62
[download] Destination: Testvideo 1 - Not Listed-2HQStlsMD6A.f140.m4a
[download] 100% of 4.55MiB in 00:06
[ffmpeg] Merging formats into "Testvideo 1 - Not Listed-2HQStlsMD6A.mp4"
[debug] ffmpeg command line: ffmpeg -y -i 'file:Testvideo 1 - Not Listed-2HQStlsMD6A.f136.mp4' -i 'file:Testvideo 1 - Not Listed-2HQStlsMD6A.f140.m4a' -c copy -map 0:v:0 -map 1:a:0 'file:Testvideo 1 - Not Listed-2HQStlsMD6A.temp.mp4'
Deleting original file Testvideo 1 - Not Listed-2HQStlsMD6A.f136.mp4 (pass -k to keep)
Deleting original file Testvideo 1 - Not Listed-2HQStlsMD6A.f140.m4a (pass -k to keep)
[download] Downloading video 2 of 3
[youtube] bqNIZicbG8k: Downloading webpage
[youtube] bqNIZicbG8k: Downloading embed webpage
[youtube] bqNIZicbG8k: Refetching age-gated info webpage
ERROR: bqNIZicbG8k: YouTube said: This video is private.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 760, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1498, in _real_extract
    expected=True, video_id=video_id)
ExtractorError: bqNIZicbG8k: YouTube said: This video is private.

form@server:~$
```

---

### Description of your *issue*, suggested solution and other information

When downloading a YouTube-Playlist which contains a video that is flagged as "private" (and you have no access right to it), youtube-dl will crash and doesnt download the "normal" videos which may appear after that private-one in the playlist.

To reproduce, i created a public playlist so you can try it yourself:
```
youtube-dl -v https://www.youtube.com/playlist?list=PLLyofhmfnvHLsg3ECsSlH6i7d74vNYXd9
```
Video 1 is flagged as "Not listed"
Video 2 is flagged as "Private" - This will not be downloaded
Video 3 is flagged as "Public" - This will not be downloaded

**Comment by dstftw** [comment]
`-i`.
