### ISSUE TITLE
Can't download YouTube subscriptions videos on Android QPython with Python 3.2

### ISSUE THREAD

**Issue by vmassuchetto** [rg3/youtube-dl#13179]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.05.18.1*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.05.18.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

I get this error running youtube-dl with the `-v` option:

```
$ youtube-dl -v --no-check-certificate --cache-dir "/sdcard/YouTube/cache" -u PRIVATE -p PRIVATE -f "best[width<=720]" -o "/sdcard/YouTube/%(upload_date)s %(uploader)s - %(title)s.%(ext)s" "https://www.youtube.com/feed/subscriptions"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--no-check-certificate', '--cache-dir', '/sdcard/YouTube/cache', '-u', 'PRIVATE', '-p', 'PRIVATE', '-f', 'best[width<=720]', '-o', '/sdcard/YouTube/%(upload_date)s %(uploader)s - %(title)s.%(ext)s', 'https://www.youtube.com/feed/subscriptions']
[debug] Encodings: locale utf-8, fs utf-8, out utf-8, pref utf-8
[debug] youtube-dl version 2017.05.18.1
Traceback (most recent call last):
  File "/data/data/org.qpython.qpy3/files/bin/youtube-dl", line 9, in <module>
    load_entry_point('youtube-dl==2017.05.18.1', 'console_scripts', 'youtube-dl')()
  File "/data/data/org.qpython.qpy3/files/lib/python3.2/site-packages/youtube_dl/__init__.py", line 465, in main
    _real_main(argv)
  File "/data/data/org.qpython.qpy3/files/lib/python3.2/site-packages/youtube_dl/__init__.py", line 432, in _real_main
    with YoutubeDL(ydl_opts) as ydl:
  File "/data/data/org.qpython.qpy3/files/lib/python3.2/site-packages/youtube_dl/YoutubeDL.py", line 391, in __init__
    self.print_debug_header()
  File "/data/data/org.qpython.qpy3/files/lib/python3.2/site-packages/youtube_dl/YoutubeDL.py", line 2145, in print_debug_header
    platform.python_version(), platform_name()))
  File "/data/data/org.qpython.qpy3/files/lib/python3.2/site-packages/youtube_dl/utils.py", line 1303, in platform_name
    res = platform.platform()
  File "/data/data/org.qpython.qpy3/files/lib/python3.2/python32.zip/platform.py", line 1545, in platform
  File "/data/data/org.qpython.qpy3/files/lib/python3.2/python32.zip/platform.py", line 184, in libc_ver
TypeError: unorderable types: NoneType() > str()
```

If I remove the `-v` option, I get two different errors (sometimes one, sometimes another):

Error 1 -- local variable 'check_cookie_url' referenced before assignment

```
$ youtube-dl -v --no-check-certificate --cache-dir "/sdcard/YouTube/cache" -u PRIVATE -p PRIVATE -f "best[width<=720]" -o "/sdcard/YouTube/%(upload_date)s %(uploader)s - %(title)s.%(ext)s" "https://www.youtube.com/feed/subscriptions"
[youtube:subscriptions] Downloading login page
[youtube:subscriptions] Looking up account info
[youtube:subscriptions] Logging in
Traceback (most recent call last):
  File "/data/data/org.qpython.qpy3/files/bin/youtube-dl", line 9, in <module>
    load_entry_point('youtube-dl==2017.05.18.1', 'console_scripts', 'youtube-dl')()
  File "/data/data/org.qpython.qpy3/files/lib/python3.2/site-packages/youtube_dl/__init__.py", line 465, in main
    _real_main(argv)
  File "/data/data/org.qpython.qpy3/files/lib/python3.2/site-packages/youtube_dl/__init__.py", line 455, in _real_main
    retcode = ydl.download(all_urls)
  File "/data/data/org.qpython.qpy3/files/lib/python3.2/site-packages/youtube_dl/YoutubeDL.py", line 1896, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/data/data/org.qpython.qpy3/files/lib/python3.2/site-packages/youtube_dl/YoutubeDL.py", line 760, in extract_info
    ie_result = ie.extract(url)
  File "/data/data/org.qpython.qpy3/files/lib/python3.2/site-packages/youtube_dl/extractor/common.py", line 432, in extract
    self.initialize()
  File "/data/data/org.qpython.qpy3/files/lib/python3.2/site-packages/youtube_dl/extractor/common.py", line 390, in initialize
    self._real_initialize()
  File "/data/data/org.qpython.qpy3/files/lib/python3.2/site-packages/youtube_dl/extractor/youtube.py", line 2563, in _real_initialize
    self._login()
  File "/data/data/org.qpython.qpy3/files/lib/python3.2/site-packages/youtube_dl/extractor/youtube.py", line 232, in _login
    if not check_cookie_url:
UnboundLocalError: local variable 'check_cookie_url' referenced before assignment
```

Error 2 -- html.parser.HTMLParseError: EOF in middle of construct, at line 1, column 1

```
$ youtube-dl -v --no-check-certificate --cache-dir "/sdcard/YouTube/cache" -u PRIVATE -p PRIVATE -f "best[width<=720]" -o "/sdcard/YouTube/%(upload_date)s %(uploader)s - %(title)s.%(ext)s" "https://www.youtube.com/feed/subscriptions"
[youtube:subscriptions] Downloading login page
Traceback (most recent call last):
  File "/data/data/org.qpython.qpy3/files/bin/youtube-dl", line 9, in <module>
    load_entry_point('youtube-dl==2017.05.18.1', 'console_scripts', 'youtube-dl')()
  File "/data/data/org.qpython.qpy3/files/lib/python3.2/site-packages/youtube_dl/__init__.py", line 465, in main
    _real_main(argv)
  File "/data/data/org.qpython.qpy3/files/lib/python3.2/site-packages/youtube_dl/__init__.py", line 455, in _real_main
    retcode = ydl.download(all_urls)
  File "/data/data/org.qpython.qpy3/files/lib/python3.2/site-packages/youtube_dl/YoutubeDL.py", line 1896, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/data/data/org.qpython.qpy3/files/lib/python3.2/site-packages/youtube_dl/YoutubeDL.py", line 760, in extract_info
    ie_result = ie.extract(url)
  File "/data/data/org.qpython.qpy3/files/lib/python3.2/site-packages/youtube_dl/extractor/common.py", line 432, in extract
    self.initialize()
  File "/data/data/org.qpython.qpy3/files/lib/python3.2/site-packages/youtube_dl/extractor/common.py", line 390, in initialize
    self._real_initialize()
  File "/data/data/org.qpython.qpy3/files/lib/python3.2/site-packages/youtube_dl/extractor/youtube.py", line 2563, in _real_initialize
    self._login()
  File "/data/data/org.qpython.qpy3/files/lib/python3.2/site-packages/youtube_dl/extractor/youtube.py", line 100, in _login
    login_form = self._hidden_inputs(login_page)
  File "/data/data/org.qpython.qpy3/files/lib/python3.2/site-packages/youtube_dl/extractor/common.py", line 1037, in _hidden_inputs
    attrs = extract_attributes(input)
  File "/data/data/org.qpython.qpy3/files/lib/python3.2/site-packages/youtube_dl/utils.py", line 413, in extract_attributes
    parser.close()
  File "/data/data/org.qpython.qpy3/files/lib/python3.2/python32.zip/html/parser.py", line 137, in close
  File "/data/data/org.qpython.qpy3/files/lib/python3.2/python32.zip/html/parser.py", line 191, in goahead
  File "/data/data/org.qpython.qpy3/files/lib/python3.2/python32.zip/html/parser.py", line 140, in error
html.parser.HTMLParseError: EOF in middle of construct, at line 1, column 1
```

---

### Description of your *issue*, suggested solution and other information

All errors occur on pip console, after installing youtube-dl with `pip install youtube-dl`. I tested on both QPython with Python 2.7 and Python 3.2. More often the error HTMLParseError occurs.

**Comment by dstftw** [comment]
1. `platform.platform()` is broken on your python implementation report it to its developers.
2. Post the output with `--dump-pages`.

**Comment by vmassuchetto** [comment]
1. Looks like it has [already been reported](https://github.com/qpython-android/qpython.org/issues/124) -- not much attention, though;
2. Link to `--dump-pages` output: https://www.pastiebin.com/59230cba33cc0

**Comment by yan12125** [comment]
Please follow #13822 for the second issue. For the first issue, I suggest moving away from QPython, which is quite old and not working well with Android. Python 3.6+ is recommended.
