### ISSUE TITLE
zdnet.com/video/ gives "UnsupportedError: Unsupported URL"

### ISSUE THREAD

**Issue by GETandSELECT** [rg3/youtube-dl#13213]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.05.26*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.05.26**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
> youtube-dl -v http://www.zdnet.com/video/huawei-matebook-x-video/
[debug] System config: [u'--recode-video=mp4']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'http://www.zdnet.com/video/huawei-matebook-x-video/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.05.26
[debug] Python version 2.7.13 - Darwin-16.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.3.1, ffprobe 3.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] huawei-matebook-x-video: Requesting header
WARNING: Falling back on generic information extractor.
[generic] huawei-matebook-x-video: Downloading webpage
[generic] huawei-matebook-x-video: Extracting information
ERROR: Unsupported URL: http://www.zdnet.com/video/huawei-matebook-x-video/
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1970, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2526, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2515, in _XML
    parser.feed(text)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 33, column 46
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 760, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2795, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.zdnet.com/video/huawei-matebook-x-video/

```

### Description of your *issue*, suggested solution and other information

zdnet.com extractor broken "UnsupportedError: Unsupported URL: http://www.zdnet.com/video/huawei-matebook-x-video/"

**Comment by GETandSELECT** [comment]
thanks @dstftw 

Note to others: you need to use the option `--prefer-ffmpeg`
Without this option the error `Application provided invalid, non monotonically increasing dts to muxer in stream` pops up.

Works fine.

```
Input #0, hls,applehttp, from 'http://ipad-streaming.techrepublic.com/media/2017/05/23/951220803720/HuaweiMatebookX_1136073_5000/HuaweiMatebookX_1136073_5000.m3u8':
  Duration: 00:01:35.35, start: 1.460200, bitrate: 0 kb/s
  Program 0 
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: h264 (Main), 1 reference frame ([27][0][0][0] / 0x001B), yuv420p(left), 1920x1080 (1920x1088) [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 90k tbn, 47.95 tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
Output #0, mp4, to 'file:Huawei Matebook X (Video)-BU_gFyM4QL9Af1tyK6df23KKp9q8UXe9.mp4.part':
  Metadata:
    encoder         : Lavf57.71.100
    Stream #0:0: Video: h264 (Main), 1 reference frame ([33][0][0][0] / 0x0021), yuv420p(left), 1920x1080 (0x0) [SAR 1:1 DAR 16:9], q=2-31, 23.98 fps, 23.98 tbr, 90k tbn, 90k tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) ([64][0][0][0] / 0x0040), 44100 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
Automatically inserted bitstream filter 'aac_adtstoasc'; args=''
[hls,applehttp @ 0x7fc24b800000] HLS request for url 'http://ipad-streaming.techrepublic.com/media/2017/05/23/951220803720/HuaweiMatebookX_1136073_5000/HuaweiMatebookX_1136073_5000_1.ts', offset 0, playlist 0
[hls,applehttp @ 0x7fc24b800000] HLS request for url 'http://ipad-streaming.techrepublic.com/media/2017/05/23/951220803720/HuaweiMatebookX_1136073_5000/HuaweiMatebookX_1136073_5000_2.ts', offset 0, playlist 0
[hls,applehttp @ 0x7fc24b800000] HLS request for url 'http://ipad-streaming.techrepublic.com/media/2017/05/23/951220803720/HuaweiMatebookX_1136073_5000/HuaweiMatebookX_1136073_5000_3.ts', offset 0, playlist 0
[hls,applehttp @ 0x7fc24b800000] HLS request for url 'http://ipad-streaming.techrepublic.com/media/2017/05/23/951220803720/HuaweiMatebookX_1136073_5000/HuaweiMatebookX_1136073_5000_4.ts', offset 0, playlist 0
[hls,applehttp @ 0x7fc24b800000] HLS request for url 'http://ipad-streaming.techrepublic.com/media/2017/05/23/951220803720/HuaweiMatebookX_1136073_5000/HuaweiMatebookX_1136073_5000_5.ts', offset 0, playlist 0
[hls,applehttp @ 0x7fc24b800000] HLS request for url 'http://ipad-streaming.techrepublic.com/media/2017/05/23/951220803720/HuaweiMatebookX_1136073_5000/HuaweiMatebookX_1136073_5000_6.ts', offset 0, playlist 0
[hls,applehttp @ 0x7fc24b800000] HLS request for url 'http://ipad-streaming.techrepublic.com/media/2017/05/23/951220803720/HuaweiMatebookX_1136073_5000/HuaweiMatebookX_1136073_5000_7.ts', offset 0, playlist 0
[hls,applehttp @ 0x7fc24b800000] HLS request for url 'http://ipad-streaming.techrepublic.com/media/2017/05/23/951220803720/HuaweiMatebookX_1136073_5000/HuaweiMatebookX_1136073_5000_8.ts', offset 0, playlist 0
[hls,applehttp @ 0x7fc24b800000] HLS request for url 'http://ipad-streaming.techrepublic.com/media/2017/05/23/951220803720/HuaweiMatebookX_1136073_5000/HuaweiMatebookX_1136073_5000_9.ts', offset 0, playlist 0
[hls,applehttp @ 0x7fc24b800000] HLS request for url 'http://ipad-streaming.techrepublic.com/media/2017/05/23/951220803720/HuaweiMatebookX_1136073_5000/HuaweiMatebookX_1136073_5000_10.ts', offset 0, playlist 0
[hls,applehttp @ 0x7fc24b800000] HLS request for url 'http://ipad-streaming.techrepublic.com/media/2017/05/23/951220803720/HuaweiMatebookX_1136073_5000/HuaweiMatebookX_1136073_5000_11.ts', offset 0, playlist 0
[hls,applehttp @ 0x7fc24b800000] HLS request for url 'http://ipad-streaming.techrepublic.com/media/2017/05/23/951220803720/HuaweiMatebookX_1136073_5000/HuaweiMatebookX_1136073_5000_12.ts', offset 0, playlist 0
[hls,applehttp @ 0x7fc24b800000] HLS request for url 'http://ipad-streaming.techrepublic.com/media/2017/05/23/951220803720/HuaweiMatebookX_1136073_5000/HuaweiMatebookX_1136073_5000_13.ts', offset 0, playlist 0
[hls,applehttp @ 0x7fc24b800000] HLS request for url 'http://ipad-streaming.techrepublic.com/media/2017/05/23/951220803720/HuaweiMatebookX_1136073_5000/HuaweiMatebookX_1136073_5000_14.ts', offset 0, playlist 0
[hls,applehttp @ 0x7fc24b800000] HLS request for url 'http://ipad-streaming.techrepublic.com/media/2017/05/23/951220803720/HuaweiMatebookX_1136073_5000/HuaweiMatebookX_1136073_5000_15.ts', offset 0, playlist 0
No more output streams to write to, finishing.e=00:01:34.15 bitrate=5196.9kbits/s speed=3.26x    
frame= 2284 fps= 79 q=-1.0 Lsize=   60267kB time=00:01:35.31 bitrate=5179.6kbits/s speed=3.29x    
video:58668kB audio:1545kB subtitle:0kB other streams:0kB global headers:1kB muxing overhead: 0.089578%
Input file #0 (http://ipad-streaming.techrepublic.com/media/2017/05/23/951220803720/HuaweiMatebookX_1136073_5000/HuaweiMatebookX_1136073_5000.m3u8):
  Input stream #0:0 (video): 2284 packets read (60075961 bytes); 
  Input stream #0:1 (audio): 4106 packets read (1581879 bytes); 
  Total: 6390 packets (61657840 bytes) demuxed
Output file #0 (file:Huawei Matebook X (Video)-BU_gFyM4QL9Af1tyK6df23KKp9q8UXe9.mp4.part):
  Output stream #0:0 (video): 2284 packets muxed (60075961 bytes); 
  Output stream #0:1 (audio): 4106 packets muxed (1581879 bytes); 
  Total: 6390 packets (61657840 bytes) muxed
[ffmpeg] Downloaded 61713072 bytes
[download] 100% of 58.85MiB
```
