### ISSUE TITLE
Support for nickjr.es (Spanish version of nickjr.com)

### ISSUE THREAD

**Issue by jjarava** [rg3/youtube-dl#13230]
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2017.05.29**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
    - I've seen that nickjr.com is supported, but for whatever reason nickjr is not.

### What is the purpose of your *issue*?
- [x] Site support request (request for adding support for a new site)

### Example video URL:
- Single Video: <http://www.nickjr.es/la-patrulla-canina/videos/la-patrulla-salva-a-una-familia-de-elefantes-/>

### Output of `youtube-dl -v`:

```python
2017-05-30 17:07:51 jjarava $ youtube-dl -v http://www.nickjr.es/la-patrulla-canina/videos/la-patrulla-salva-a-una-familia-de-elefantes-/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'http://www.nickjr.es/la-patrulla-canina/videos/la-patrulla-salva-a-una-familia-de-elefantes-/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.05.29
[debug] Python version 2.7.10 - Darwin-15.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.1.4-tessus, ffprobe 3.1.4-tessus
[debug] Proxy map: {}
[generic] la-patrulla-salva-a-una-familia-de-elefantes-: Requesting header
WARNING: Falling back on generic information extractor.
[generic] la-patrulla-salva-a-una-familia-de-elefantes-: Downloading webpage
[generic] la-patrulla-salva-a-una-familia-de-elefantes-: Extracting information
ERROR: Unsupported URL: http://www.nickjr.es/la-patrulla-canina/videos/la-patrulla-salva-a-una-familia-de-elefantes-/
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1970, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2526, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2515, in _XML
    parser.feed(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 26, column 12872
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 760, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2795, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.nickjr.es/la-patrulla-canina/videos/la-patrulla-salva-a-una-familia-de-elefantes-/
```
Thanks a lot

**Comment by odikrause** [comment]
would be the same for nickjr.de

**Comment by dimitricappelle** [comment]
would be the same for nickjr.nl

**Comment by allardhoeve** [comment]
Works fine with 2018.05.01 👍 Suggest closing the bug.

**Comment by odikrause** [comment]
Updating to version 2018.05.09 ...
Updated youtube-dl. Restart youtube-dl to use the new version.

http://www.nickjr.de/blaze-und-die-monster-maschinen/videos/f6caaf8f-e4e8-4cc1-b489-9380d6dcd059/
youtube-dl: error: no such option: -V
$ youtube-dl -v  http://www.nickjr.de/blaze-und-die-monster-maschinen/videos/f6caaf8f-e4e8-4cc1-b489-9380d6dcd059/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'http://www.nickjr.de/blaze-und-die-monster-maschinen/videos/f6caaf8f-e4e8-4cc1-b489-9380d6dcd059/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.05.09
[debug] Python version 2.7.15rc1 (CPython) - Linux-4.15.0-20-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: avconv 3.4.2-2, avprobe 3.4.2-2, ffmpeg 3.4.2-2, ffprobe 3.4.2-2, rtmpdump 2.4
[debug] Proxy map: {}
[generic] f6caaf8f-e4e8-4cc1-b489-9380d6dcd059: Requesting header
WARNING: Falling back on generic information extractor.
[generic] f6caaf8f-e4e8-4cc1-b489-9380d6dcd059: Downloading webpage
[generic] f6caaf8f-e4e8-4cc1-b489-9380d6dcd059: Extracting information
ERROR: Unsupported URL: http://www.nickjr.de/blaze-und-die-monster-maschinen/videos/f6caaf8f-e4e8-4cc1-b489-9380d6dcd059/
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2261, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2542, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2531, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 26, column 14544
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 503, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3201, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.nickjr.de/blaze-und-die-monster-maschinen/videos/f6caaf8f-e4e8-4cc1-b489-9380d6dcd059/
