### ISSUE TITLE
Downloading from Ooyala - Flograpping

### ISSUE THREAD

**Issue by Gizmundo** [rg3/youtube-dl#13263]
Hi I am trying to download the video from this page: 

http://www.flograppling.com/video/1209962-andre-galvao-works-out-one-week-before-ibjjf-worlds#.WTGnl8aTSUk

It is my understanding that the youtube-dl supports Ooyala and looking at the source code the video is run by Ooyala. I ran the following commands but had no luck:

youtube-dl.exe "http://www.flograppling.com/video/1209962-andre-galvao-works-out-one-week-before-ibjjf-worlds#.WTGnl8aTSUk"

youtube-dl -v -o "/media/%(title)s.mp4" http://www.flograppling.com/video/1209962-andre-galvao-works-out-one-week-before-ibjjf-worlds#.WTGnl8aTSUk

I am not sure I would class this as an issue because I am a noob and I am sure I am doing something wrong, so your help would be greatly appreciated.

**Comment by remitamine** [comment]
for now you can use this command to download download this video:
`youtube-dl ooyala:1sZHBmYjE6MoCVzv1p_bbmAkk2P6Ec5f`

**Comment by Gizmundo** [comment]
It worked, thank you very much for your help.

**Comment by Gizmundo** [comment]
Hi, 

For the last two weeks this has worked for me but I have run in to another problem which I hope you can help me with. When using the command "youtube-dl ooyala:" with the embed code I am getting this error:

```C:\Users\Isaac\Desktop\youtube>youtube-dl ooyala:NiajJrYjE6RPxn2VtIvVYrIuzbgmWLKP
[Ooyala] NiajJrYjE6RPxn2VtIvVYrIuzbgmWLKP: Downloading JSON metadata
[Ooyala] NiajJrYjE6RPxn2VtIvVYrIuzbgmWLKP: Downloading JSON metadata
[Ooyala] NiajJrYjE6RPxn2VtIvVYrIuzbgmWLKP: Downloading f4m manifest
[Ooyala] NiajJrYjE6RPxn2VtIvVYrIuzbgmWLKP: Downloading m3u8 information
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkyaecyzu\build\youtube_dl\__init__.py", line 465, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkyaecyzu\build\youtube_dl\__init__.py", line 455, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkyaecyzu\build\youtube_dl\YoutubeDL.py", line 1919, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkyaecyzu\build\youtube_dl\YoutubeDL.py", line 773, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkyaecyzu\build\youtube_dl\YoutubeDL.py", line 827, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkyaecyzu\build\youtube_dl\YoutubeDL.py", line 1496, in process_video_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkyaecyzu\build\youtube_dl\YoutubeDL.py", line 1325, in _calc_headers
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkyaecyzu\build\youtube_dl\YoutubeDL.py", line 1337, in _calc_cookies
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkyaecyzu\build\youtube_dl\utils.py", line 546, in sanitized_Request
  File "C:\Python\Python34\lib\urllib\request.py", line 267, in __init__
  File "C:\Python\Python34\lib\urllib\request.py", line 293, in full_url
  File "C:\Python\Python34\lib\urllib\request.py", line 322, in _parse
ValueError: unknown url type: ''
```
Updating the program didn't help either, any ideas?

**Comment by Gizmundo** [comment]
@remitamine any ideas?

**Comment by remitamine** [comment]
i'm sorry, i would've like to debug the problem, fix it and add support for this website.
unfortunately, i can't start working on anything of this for now(and may be for a long time).

**Comment by parmjitv** [comment]
Hi @Gizmundo,

Are you still seeing this issue with the Ooyala extractor?

I am able fetch the video you reference above as:
[Tex Johnson vs Kaliffa Oliviera Fight to Win Pro 36-NiajJrYjE6RPxn2VtIvVYrIuzbgmWLKP.mp4]

This is using the latest build - version 2017.07.02 .

Cheers,

Parmjit V.

**Comment by parmjitv** [comment]
Please see issue #13444 - apparently this was fixed with the latest build.
