### ISSUE TITLE
Specific youtube-URL(6apO2GA_3so) not downloading but browser plays OK

### ISSUE THREAD

**Issue by FluffDragon** [rg3/youtube-dl#13272]
CONFIRMED: Running 'youtube-dl --version'=*2017.05.29*
DESCRIBING COMMENTS: URL="...youtube.com/watch?v=6apO2GA_3so" plays in browser but does NOT download via youtube-dl.exe.
Thank-you for your attention and effort.
________________________________________________________________________________________________________
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like
---
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.05.29*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.05.29**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [X] Other= Verify "HTTP Error 404: Not Found" due to "redirector.googlevideo.com" error
---
### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*
---
### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:
Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
____________________________________________________________________________________________________
C:\Users\user\Downloads>youtube-dl.exe "https://www.youtube.com/watch?v=6apO2GA_3so" -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=6apO2GA_3so', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.05.29
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] 6apO2GA_3so: Downloading webpage
[youtube] 6apO2GA_3so: Downloading video info webpage
[youtube] 6apO2GA_3so: Extracting video information
[youtube] 6apO2GA_3so: Downloading MPD manifest
[debug] Invoking downloader on 'https://redirector.googlevideo.com/videoplayback
?sparams=ei%2Cgcr%2Cid%2Cip%2Cipbits%2Citag%2Cmime%2Cratebypass%2Crequiressl%2Cs
ource%2Cexpire&key=yt6&ei=OD8yWfiQJ4PPqQWTgaygCA&id=6apO2GA_3so.1&gcr=us&signatu
re=3A1A134B0A99B1450E6E260B1BEE2A28C709D1CA.0524B474870439EB644442470885D54F1F62
D51D&itag=18&requiressl=yes&mime=video%2Fmp4&ip=68.205.8.5&ratebypass=yes&ipbits
=0&source=youtube&expire=1496486808'
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpf1wnshrp\build\youtube_dl\YoutubeDL.py", line 1803, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpf1wnshrp\build\youtube_dl\YoutubeDL.py", line 1745, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpf1wnshrp\build\youtube_dl\downloader\common.py", line 360, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpf1wnshrp\build\youtube_dl\downloader\http.py", line 61, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpf1wnshrp\build\youtube_dl\YoutubeDL.py", line 2106, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 502, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 685, in http_error_302
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found
___________________________________________________________________________________________________________
```
---
____NOT__APPLICABLE_____________________________________________________________NOT__APPLICABLE___
### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.
---
________________________________________________________________________________________________________
### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.
_________________________________
SUSPECTED PROBLEM ORIGIN:  Unknown.  Previous video content of same type for this YouTube user
downloaded via youtube-dl.exe without difficulty. 
________________________________________________________________________________________________________

**Comment by FluffDragon** [comment]
UPDATE:__201706Jun03-15:29:31________________________________________________________________________
Googlevideo.com has "healed itself":
______________________________________
C:\Users\user\Downloads>youtube-dl.exe "https://www.youtube.com/watch?v=6apO2GA_
3so" -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=6apO2GA_3so', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.05.29
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] 6apO2GA_3so: Downloading webpage
[youtube] 6apO2GA_3so: Downloading video info webpage
[youtube] 6apO2GA_3so: Extracting video information
[youtube] 6apO2GA_3so: Downloading MPD manifest
[debug] Invoking downloader on 'https://r2---sn-q4f7sn76.googlevideo.com/videoplayback?sparams=dur%2Cei%2Cgcr%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmi
me%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&source=youtube&initcwndbps=1140000&pl=15&id=o-AH3jdIAqLwTDPnnqYajkhoLela1Z2_V1vj7KsWP6LD
PH&expire=1496570018&ei=QoQzWaLBAsGgqgWVsLawDA&gcr=us&ip=68.205.8.5&lmt=1496518171347815&ms=au&mt=1496548345&mv=m&dur=4165.822&itag=22&key=yt6&signature=4FF9A62
FA8B6FB908379AACF42CE3FE40BD2263B.D09580AD828836EE6F9A41CE65A7CA03363CBFD5&mn=sn-q4f7sn76&ipbits=0&mime=video%2Fmp4&mm=31&ratebypass=yes&requiressl=yes'
[download] Destination: Friday, 06_02_2017 False Flag Weekly News-6apO2GA_3so.mp4
[download] 100% of 545.26MiB in 04:36
C:\Users\user\Downloads>
___________________________________________________________________________________________________________
More recent previous attempts to use youtube-dl.exe resulted in lower resolution video(640x360) but
now the latest(attached above) is the hoped for (1280x720).   The fault appears to be with delays or
other mis-processing within the land of Google-YouTube.
Many thanks to all the contributors who attempted to duplicate the fail but found
"CANT-REPRODUCE".  Happy solstice to all!
REQUEST_FOR_CLOSING_#13272:______________Now how do I close this report?  Thanks!
