### ISSUE TITLE
vrv.co extractor not working

### ISSUE THREAD

**Issue by IamCarbonMan** [rg3/youtube-dl#13274]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.05.29*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.05.29**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2017.05.29
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

The following command `youtube-dl -v https://vrv.co/watch/G65VE5K06/Bee-and-PuppyCat:Bee-and-PuppyCat-Pilot` fails with this error:

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://vrv.co/watch/G649DW70Y/Yu-Gi-Oh-VRAINS:First-Contact']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.05.29
[debug] Python version 3.6.1 - Linux-4.11.3-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 3.3.1, ffprobe 3.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[vrv] G649DW70Y: Downloading webpage
[vrv] G649DW70Y: Downloading resource path JSON metadata
[vrv] G649DW70Y: Downloading CMS Signing JSON metadata
[vrv] G649DW70Y: Downloading video JSON metadata
[vrv] G649DW70Y: Downloading streams JSON metadata
[vrv] G649DW70Y: Downloading ja-JP MPD information
Traceback (most recent call last):
  File "/usr/bin/youtube-dl", line 11, in <module>
    load_entry_point('youtube-dl==2017.5.29', 'console_scripts', 'youtube-dl')()
  File "/usr/lib/python3.6/site-packages/youtube_dl/__init__.py", line 465, in main
    _real_main(argv)
  File "/usr/lib/python3.6/site-packages/youtube_dl/__init__.py", line 455, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 1896, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 760, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/vrv.py", line 132, in _real_extract
    fatal=False)
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 1736, in _extract_mpd_formats
    compat_etree_fromstring(mpd.encode('utf-8')), mpd_id, mpd_base_url,
  File "/usr/lib/python3.6/site-packages/youtube_dl/compat.py", line 2497, in compat_etree_fromstring
    return etree.XML(text, parser=etree.XMLParser(target=_TreeBuilder()))
  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 1314, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 19, column 325
```

**Comment by jakepbrown27** [comment]
I have also encountered this issue:::
`[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://vrv.co/watch/GR098QNGR/Attack-on-Titan', '-u', 'PRIVATE', '-p', 'PRIVATE']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2017.06.18
[debug] Python version 3.4.4 - Windows-10-10.0.15063
[debug] exe versions: none
[debug] Proxy map: {}
[vrv] GR098QNGR: Downloading webpage
ERROR: An extractor error has occurred. (caused by KeyError('streams',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U 
 to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp_9wocfhk\build\youtube_dl\extractor\common.py", line 433, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp_9wocfhk\build\youtube_dl\extractor\vrv.py", line 110, in _real_extract
KeyError: 'streams'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp_9wocfhk\build\youtube_dl\extractor\common.py", line 433, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp_9wocfhk\build\youtube_dl\extractor\vrv.py", line 110, in _real_extract
KeyError: 'streams'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp_9wocfhk\build\youtube_dl\YoutubeDL.py", line 762, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp_9wocfhk\build\youtube_dl\extractor\common.py", line 446, in extract
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('streams',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest 
version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.`

**Comment by Kasijjuf** [comment]
I am also having this issue
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://vrv.co/watch/GY8V590JY/Fairy-Tail:The-Fairy-Tail']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.07.09
[debug] Python version 2.7.13 - Linux-4.10.0-22-generic-x86_64-with-Ubuntu-17.04-zesty
[debug] exe versions: ffmpeg 3.2.4-1build2, ffprobe 3.2.4-1build2
[debug] Proxy map: {}
[vrv] GY8V590JY: Downloading webpage
[vrv] GY8V590JY: Downloading en-US MPD information
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 465, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 455, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1927, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 762, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 433, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/vrv.py", line 132, in _real_extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1736, in _extract_mpd_formats
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2539, in compat_etree_fromstring
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2528, in _XML
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 19, column 301
```

**Comment by IamCarbonMan** [comment]
@dstftw, I doubt this is a geo-restriction issue. I can access the stream correctly from my browser on the same system. I can watch the same video in my browser from the same host just fine.

**Comment by remitamine** [comment]
```
python __main__.py -F https://vrv.co/watch/G649DW70Y/Yu-Gi-Oh-VRAINS:First-Contact
[vrv] G649DW70Y: Downloading webpage
[vrv] G649DW70Y: Downloading ja-JP MPD information
[vrv] G649DW70Y: Downloading de-DE MPD information
[vrv] G649DW70Y: Downloading en-US MPD information
[vrv] G649DW70Y: Downloading es-LA MPD information
[vrv] G649DW70Y: Downloading pt-BR MPD information
[vrv] G649DW70Y: Downloading ja-JP m3u8 information
[vrv] G649DW70Y: Downloading de-DE m3u8 information
[vrv] G649DW70Y: Downloading en-US m3u8 information
[vrv] G649DW70Y: Downloading es-LA m3u8 information
[vrv] G649DW70Y: Downloading pt-BR m3u8 information
[info] Available formats for G649DW70Y:
format code          extension  resolution note
dash-de-DE-f4-a1-x3  m4a        audio only [ja-JP] DASH audio   64k , mp4a.40.2 (22050Hz)
dash-en-US-f5-a1-x3  m4a        audio only [ja-JP] DASH audio   64k , mp4a.40.2 (22050Hz)
dash-es-LA-f5-a1-x3  m4a        audio only [ja-JP] DASH audio   64k , mp4a.40.2 (22050Hz)
dash-ja-JP-f5-a1-x3  m4a        audio only [ja-JP] DASH audio   64k , mp4a.40.2 (22050Hz)
dash-pt-BR-f5-a1-x3  m4a        audio only [ja-JP] DASH audio   64k , mp4a.40.2 (22050Hz)
dash-de-DE-f2-a1-x3  m4a        audio only [ja-JP] DASH audio   96k , mp4a.40.2 (44100Hz)
dash-en-US-f3-a1-x3  m4a        audio only [ja-JP] DASH audio   96k , mp4a.40.2 (44100Hz)
dash-es-LA-f3-a1-x3  m4a        audio only [ja-JP] DASH audio   96k , mp4a.40.2 (44100Hz)
dash-ja-JP-f3-a1-x3  m4a        audio only [ja-JP] DASH audio   96k , mp4a.40.2 (44100Hz)
dash-pt-BR-f3-a1-x3  m4a        audio only [ja-JP] DASH audio   96k , mp4a.40.2 (44100Hz)
dash-de-DE-f1-a1-x3  m4a        audio only [ja-JP] DASH audio  128k , mp4a.40.2 (44100Hz)
dash-en-US-f1-a1-x3  m4a        audio only [ja-JP] DASH audio  128k , mp4a.40.2 (44100Hz)
dash-es-LA-f1-a1-x3  m4a        audio only [ja-JP] DASH audio  128k , mp4a.40.2 (44100Hz)
dash-ja-JP-f1-a1-x3  m4a        audio only [ja-JP] DASH audio  128k , mp4a.40.2 (44100Hz)
dash-pt-BR-f1-a1-x3  m4a        audio only [ja-JP] DASH audio  128k , mp4a.40.2 (44100Hz)
dash-ja-JP-f5-v1-x3  mp4        432x240    DASH video  318k , avc1.42c015, video only
dash-en-US-f5-v1-x3  mp4        432x240    DASH video  327k , avc1.42c015, video only
dash-pt-BR-f5-v1-x3  mp4        432x240    DASH video  329k , avc1.42c015, video only
dash-es-LA-f5-v1-x3  mp4        432x240    DASH video  329k , avc1.42c015, video only
dash-de-DE-f4-v1-x3  mp4        432x240    DASH video  331k , avc1.42c015, video only
dash-ja-JP-f4-v1-x3  mp4        640x360    DASH video  451k , avc1.4d401f, video only
dash-en-US-f4-v1-x3  mp4        640x360    DASH video  455k , avc1.4d401f, video only
dash-de-DE-f3-v1-x3  mp4        640x360    DASH video  456k , avc1.4d401f, video only
dash-pt-BR-f4-v1-x3  mp4        640x360    DASH video  456k , avc1.4d401f, video only
dash-es-LA-f4-v1-x3  mp4        640x360    DASH video  457k , avc1.4d401f, video only
dash-ja-JP-f3-v1-x3  mp4        848x480    DASH video  873k , avc1.4d401f, video only
dash-en-US-f3-v1-x3  mp4        848x480    DASH video  899k , avc1.4d401f, video only
dash-es-LA-f3-v1-x3  mp4        848x480    DASH video  904k , avc1.4d401f, video only
dash-pt-BR-f3-v1-x3  mp4        848x480    DASH video  905k , avc1.4d401f, video only
dash-de-DE-f2-v1-x3  mp4        848x480    DASH video  907k , avc1.4d401f, video only
dash-de-DE-f1-v1-x3  mp4        1280x720   DASH video 2613k , avc1.640028, video only
dash-ja-JP-f1-v1-x3  mp4        1280x720   DASH video 2631k , avc1.640028, video only
dash-en-US-f1-v1-x3  mp4        1280x720   DASH video 2631k , avc1.640028, video only
dash-pt-BR-f1-v1-x3  mp4        1280x720   DASH video 2636k , avc1.640028, video only
dash-es-LA-f1-v1-x3  mp4        1280x720   DASH video 2636k , avc1.640028, video only
dash-pt-BR-f2-v1-x3  mp4        1920x1080  DASH video 7177k , avc1.640028, video only
dash-es-LA-f2-v1-x3  mp4        1920x1080  DASH video 7182k , avc1.640028, video only
dash-en-US-f2-v1-x3  mp4        1920x1080  DASH video 7192k , avc1.640028, video only
dash-ja-JP-f2-v1-x3  mp4        1920x1080  DASH video 7300k , avc1.640028, video only
hls-ja-JP-382-0      mp4        432x240    [ja-JP]  382k , avc1.42c015, 29.97fps, mp4a.40.2
hls-ja-JP-382-1      mp4        432x240    [ja-JP]  382k , avc1.42c015, 29.97fps, mp4a.40.2
hls-ja-JP-382-2      mp4        432x240    [ja-JP]  382k , avc1.42c015, 29.97fps, mp4a.40.2
hls-en-US-391-0      mp4        432x240    [ja-JP]  391k , avc1.42c015, 29.97fps, mp4a.40.2
hls-en-US-391-1      mp4        432x240    [ja-JP]  391k , avc1.42c015, 29.97fps, mp4a.40.2
hls-en-US-391-2      mp4        432x240    [ja-JP]  391k , avc1.42c015, 29.97fps, mp4a.40.2
hls-pt-BR-393        mp4        432x240    [ja-JP]  393k , avc1.42c015, 29.97fps, mp4a.40.2
hls-es-LA-393        mp4        432x240    [ja-JP]  393k , avc1.42c015, 29.97fps, mp4a.40.2
hls-de-DE-395        mp4        432x240    [ja-JP]  395k , avc1.42c015, 29.97fps, mp4a.40.2
hls-ja-JP-547-0      mp4        640x360    [ja-JP]  547k , avc1.4d401f, 29.97fps, mp4a.40.2
hls-ja-JP-547-1      mp4        640x360    [ja-JP]  547k , avc1.4d401f, 29.97fps, mp4a.40.2
hls-ja-JP-547-2      mp4        640x360    [ja-JP]  547k , avc1.4d401f, 29.97fps, mp4a.40.2
hls-en-US-551-0      mp4        640x360    [ja-JP]  551k , avc1.4d401f, 29.97fps, mp4a.40.2
hls-en-US-551-1      mp4        640x360    [ja-JP]  551k , avc1.4d401f, 29.97fps, mp4a.40.2
hls-en-US-551-2      mp4        640x360    [ja-JP]  551k , avc1.4d401f, 29.97fps, mp4a.40.2
hls-de-DE-552        mp4        640x360    [ja-JP]  552k , avc1.4d401f, 29.97fps, mp4a.40.2
hls-pt-BR-552        mp4        640x360    [ja-JP]  552k , avc1.4d401f, 29.97fps, mp4a.40.2
hls-es-LA-553        mp4        640x360    [ja-JP]  553k , avc1.4d401f, 29.97fps, mp4a.40.2
hls-ja-JP-969-0      mp4        848x480    [ja-JP]  969k , avc1.4d401f, 29.97fps, mp4a.40.2
hls-ja-JP-969-1      mp4        848x480    [ja-JP]  969k , avc1.4d401f, 29.97fps, mp4a.40.2
hls-ja-JP-969-2      mp4        848x480    [ja-JP]  969k , avc1.4d401f, 29.97fps, mp4a.40.2
hls-en-US-995-0      mp4        848x480    [ja-JP]  995k , avc1.4d401f, 29.97fps, mp4a.40.2
hls-en-US-995-1      mp4        848x480    [ja-JP]  995k , avc1.4d401f, 29.97fps, mp4a.40.2
hls-en-US-995-2      mp4        848x480    [ja-JP]  995k , avc1.4d401f, 29.97fps, mp4a.40.2
hls-es-LA-1000       mp4        848x480    [ja-JP] 1000k , avc1.4d401f, 29.97fps, mp4a.40.2
hls-pt-BR-1001       mp4        848x480    [ja-JP] 1001k , avc1.4d401f, 29.97fps, mp4a.40.2
hls-de-DE-1003       mp4        848x480    [ja-JP] 1003k , avc1.4d401f, 29.97fps, mp4a.40.2
hls-de-DE-2741       mp4        1280x720   [ja-JP] 2741k , avc1.640028, 29.97fps, mp4a.40.2
hls-ja-JP-2759-0     mp4        1280x720   [ja-JP] 2759k , avc1.640028, 29.97fps, mp4a.40.2
hls-ja-JP-2759-1     mp4        1280x720   [ja-JP] 2759k , avc1.640028, 29.97fps, mp4a.40.2
hls-ja-JP-2759-2     mp4        1280x720   [ja-JP] 2759k , avc1.640028, 29.97fps, mp4a.40.2
hls-en-US-2759-0     mp4        1280x720   [ja-JP] 2759k , avc1.640028, 29.97fps, mp4a.40.2
hls-en-US-2759-1     mp4        1280x720   [ja-JP] 2759k , avc1.640028, 29.97fps, mp4a.40.2
hls-en-US-2759-2     mp4        1280x720   [ja-JP] 2759k , avc1.640028, 29.97fps, mp4a.40.2
hls-pt-BR-2764       mp4        1280x720   [ja-JP] 2764k , avc1.640028, 29.97fps, mp4a.40.2
hls-es-LA-2764       mp4        1280x720   [ja-JP] 2764k , avc1.640028, 29.97fps, mp4a.40.2
hls-pt-BR-7305       mp4        1920x1080  [ja-JP] 7305k , avc1.640028, 29.97fps, mp4a.40.2
hls-es-LA-7310       mp4        1920x1080  [ja-JP] 7310k , avc1.640028, 29.97fps, mp4a.40.2
hls-en-US-7320-0     mp4        1920x1080  [ja-JP] 7320k , avc1.640028, 29.97fps, mp4a.40.2
hls-en-US-7320-1     mp4        1920x1080  [ja-JP] 7320k , avc1.640028, 29.97fps, mp4a.40.2
hls-en-US-7320-2     mp4        1920x1080  [ja-JP] 7320k , avc1.640028, 29.97fps, mp4a.40.2
hls-ja-JP-7428-0     mp4        1920x1080  [ja-JP] 7428k , avc1.640028, 29.97fps, mp4a.40.2
hls-ja-JP-7428-1     mp4        1920x1080  [ja-JP] 7428k , avc1.640028, 29.97fps, mp4a.40.2
hls-ja-JP-7428-2     mp4        1920x1080  [ja-JP] 7428k , avc1.640028, 29.97fps, mp4a.40.2 (best)
```
```
python __main__.py -F https://vrv.co/watch/GY8V590JY/Fairy-Tail:The-Fairy-Tail
[vrv] GY8V590JY: Downloading webpage
[vrv] GY8V590JY: Downloading en-US MPD information
[vrv] GY8V590JY: Downloading en-US m3u8 information
[info] Available formats for GY8V590JY:
format code          extension  resolution note
dash-en-US-f1-a1-x3  m4a        audio only [en-US] DASH audio  125k , mp4a.40.2 (44100Hz)
dash-en-US-f4-v1-x3  mp4        640x360    DASH video  537k , avc1.4d401f, video only
dash-en-US-f3-v1-x3  mp4        848x480    DASH video 1150k , avc1.4d401f, video only
dash-en-US-f1-v1-x3  mp4        1280x720   DASH video 1979k , avc1.640032, video only
dash-en-US-f2-v1-x3  mp4        1920x1080  DASH video 4391k , avc1.640032, video only
hls-en-US-662-0      mp4        640x360    [en-US]  662k , avc1.4d401f, 23.98fps, mp4a.40.2
hls-en-US-662-1      mp4        640x360    [en-US]  662k , avc1.4d401f, 23.98fps, mp4a.40.2
hls-en-US-662-2      mp4        640x360    [en-US]  662k , avc1.4d401f, 23.98fps, mp4a.40.2
hls-en-US-1275-0     mp4        848x480    [en-US] 1275k , avc1.4d401f, 23.98fps, mp4a.40.2
hls-en-US-1275-1     mp4        848x480    [en-US] 1275k , avc1.4d401f, 23.98fps, mp4a.40.2
hls-en-US-1275-2     mp4        848x480    [en-US] 1275k , avc1.4d401f, 23.98fps, mp4a.40.2
hls-en-US-2105-0     mp4        1280x720   [en-US] 2105k , avc1.640032, 23.98fps, mp4a.40.2
hls-en-US-2105-1     mp4        1280x720   [en-US] 2105k , avc1.640032, 23.98fps, mp4a.40.2
hls-en-US-2105-2     mp4        1280x720   [en-US] 2105k , avc1.640032, 23.98fps, mp4a.40.2
hls-en-US-4516-0     mp4        1920x1080  [en-US] 4516k , avc1.640032, 23.98fps, mp4a.40.2
hls-en-US-4516-1     mp4        1920x1080  [en-US] 4516k , avc1.640032, 23.98fps, mp4a.40.2
hls-en-US-4516-2     mp4        1920x1080  [en-US] 4516k , avc1.640032, 23.98fps, mp4a.40.2 (best)
```
