### ISSUE TITLE
Query: downloading YouTube links (rather than embeddings) from a generic webpage

### ISSUE THREAD

**Issue by kwill** [rg3/youtube-dl#13283]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.05.29*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.05.29**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Feature request (request for a new functionality)
- [x] Question

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
> youtube-dl -v http://gdquest.com/tutorial/art/krita-tutorial-for-game-artists/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://gdquest.com/tutorial/art/krita-tutorial-for-game-artists/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.05.29
[debug] Python version 3.5.3 - Linux-4.10.0-21-generic-x86_64-with-Ubuntu-17.04-zesty
[debug] exe versions: none
[debug] Proxy map: {}
[generic] krita-tutorial-for-game-artists: Requesting header
WARNING: Falling back on generic information extractor.
[generic] krita-tutorial-for-game-artists: Downloading webpage
[generic] krita-tutorial-for-game-artists: Extracting information
ERROR: Unsupported URL: http://gdquest.com/tutorial/art/krita-tutorial-for-game-artists/
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 760, in extract_info
    ie_result = ie.extract(url)
  File "/home/user/.local/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "/home/user/.local/lib/python3.5/site-packages/youtube_dl/extractor/generic.py", line 2795, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: http://gdquest.com/tutorial/art/krita-tutorial-for-game-artists/
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Playlist: http://gdquest.com/tutorial/art/krita-tutorial-for-game-artists/

---

### Description of your *issue*, suggested solution and other information

Sometimes I find a page which contains a hand-made list of links to YouTube videos (or other sites). I'd like to treat this as a playlist, is this possible?

If not, is it possible to add markup to the page (e.g. HTML microformats) so that `youtube-dl` would recognise generic HTML as a playlist? This would be helpful for making arbitrary sites usable with `youtube-dl`.

**Comment by dstftw** [comment]
It's possible with custom extractor. This won't be included in generic extractor (at least as default) since it's supposed to only extract embedded videos and this will slow down the extraction and may produce false positives.
You can add additional markup to mask it behind JWPlayer pattern, HTML5 media entries or so.
