### ISSUE TITLE
Site support: Blender Cloud

### ISSUE THREAD

**Issue by kwill** [rg3/youtube-dl#13282]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.05.29*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.05.29**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Site support request (request for adding support for a new site)

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
> youtube-dl -v https://cloud.blender.org/p/game-asset-creation/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://cloud.blender.org/p/game-asset-creation/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.05.29
[debug] Python version 3.5.3 - Linux-4.10.0-21-generic-x86_64-with-Ubuntu-17.04-zesty
[debug] exe versions: none
[debug] Proxy map: {}
[generic] game-asset-creation: Requesting header
WARNING: Falling back on generic information extractor.
[generic] game-asset-creation: Downloading webpage
[generic] game-asset-creation: Extracting information
[download] Downloading playlist: None
[generic] playlist None: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[debug] Invoking downloader on 'https://storage.googleapis.com/56041550044a2a00d0d7e063/_/f53b6d69cc675ef97ab96fab6fefa357da130fea.mp4?GoogleAccessId=956532172770-27ie9eb8e4u326l89p7b113gcb04cdgd@developer.gserviceaccount.com&Expires=1496618989&Signature=sXGE22BsVMaGJEYH4M15yzXS5LhpzCvCnIMpuqSTPztd7lpFLgBJ/AaJ94vv2xVPAugsGGIwSD25hJyq5kOsnmRVFh4QuYjT26eohlxIdaiAtlKi6grbCBESxK48us6o8WgvyG6VP5iAZfdcmlaj0hapKbnJMfbJqT+douqjPry/2AYmsi+VOICkA9jyxqOEXnTkzZqCA+WDYarq5OZdwz0xNCdSWZPMGktb/7mrtZL/7Y+dGPIj2l8xjDiqbhBWVW5sXAix+SgOucODWscRoDHQZDz3qoSmHKA+BQwGsZc/Z7Wqlau0IhKxX63rWpBEi/da/Bqw0ZxGSYF6gRcJ7Q=='
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 1803, in process_info
    success = dl(filename, info_dict)
  File "/home/user/.local/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 1745, in dl
    return fd.download(name, info)
  File "/home/user/.local/lib/python3.5/site-packages/youtube_dl/downloader/common.py", line 360, in download
    return self.real_download(filename, info_dict)
  File "/home/user/.local/lib/python3.5/site-packages/youtube_dl/downloader/http.py", line 61, in real_download
    data = self.ydl.urlopen(request)
  File "/home/user/.local/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 2106, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```
```
> youtube-dl -v https://cloud.blender.org/p/game-asset-creation/56041550044a2a00d0d7e068
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://cloud.blender.org/p/game-asset-creation/56041550044a2a00d0d7e068']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.05.29
[debug] Python version 3.5.3 - Linux-4.10.0-21-generic-x86_64-with-Ubuntu-17.04-zesty
[debug] exe versions: none
[debug] Proxy map: {}
[generic] 56041550044a2a00d0d7e068: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 56041550044a2a00d0d7e068: Downloading webpage
[generic] 56041550044a2a00d0d7e068: Extracting information
ERROR: Unsupported URL: https://cloud.blender.org/p/game-asset-creation/56041550044a2a00d0d7e068
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 760, in extract_info
    ie_result = ie.extract(url)
  File "/home/user/.local/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "/home/user/.local/lib/python3.5/site-packages/youtube_dl/extractor/generic.py", line 2795, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://cloud.blender.org/p/game-asset-creation/56041550044a2a00d0d7e068
```
---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://cloud.blender.org/p/game-asset-creation/56041550044a2a00d0d7e068
- Single video: https://cloud.blender.org/p/game-asset-creation/56041550044a2a00d0d7e06a
- Playlist: https://cloud.blender.org/p/game-asset-creation/
- Playlist (subsection): https://cloud.blender.org/p/game-asset-creation/56041550044a2a00d0d7e069

---

### Description of your *issue*, suggested solution and other information

Some playlists and some videos in public playlists would require signing in with a BlenderID, see https://store.blender.org/product/membership/ for details.

**Comment by parmjitv** [comment]
Hi kwill,

I am going to give this one a shot.  Regarding the restricted videos for members - is there a Bender ID available that we can use for testing?

Cheers,

Parmjit V.

**Comment by kwill** [comment]
I don't have one (yet :smile_cat: ). Perhaps you can [contact Blender Cloud](https://store.blender.org/contact/) for an ID with appropriate permissions.

**Comment by parmjitv** [comment]
Cool.  I will check that out, we might get lucky.  At the very least we should be able to fetch the free videos off the site.  Thanks!

Parmjit
