### ISSUE TITLE
[YouTube Red] Got HTTP Error. Retrying...

### ISSUE THREAD

**Issue by RuneMagle** [rg3/youtube-dl#13285]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.06.05**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
```
C:\Users\Desktop\youtube-dl>youtube-dl.exe -f 266 --username PRIVATE --password PRIVATE https://www.youtube.com/watch?v=dh_m5Vph8h0 -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', '266', '--username', 'PRIVATE', '--password', 'PRIVATE', 'https://www.youtube.com/watch?v=dh_m5Vph8h0', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.06.05
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-82833-gedb4f5d, ffprobe N-82833-gedb4f5d, rtmpdump 2.3
[debug] Proxy map: {}
[youtube] Downloading login page
[youtube] Looking up account info
[youtube] Logging in
[youtube] Checking cookie
[youtube] dh_m5Vph8h0: Downloading webpage
[youtube] dh_m5Vph8h0: Downloading video info webpage
[youtube] dh_m5Vph8h0: Extracting video information
[youtube] {22} signature length 42.43, html5 player vflZ_L_3c
[youtube] {43} signature length 42.43, html5 player vflZ_L_3c
[youtube] {18} signature length 42.43, html5 player vflZ_L_3c
[youtube] {36} signature length 42.43, html5 player vflZ_L_3c
[youtube] {17} signature length 42.43, html5 player vflZ_L_3c
[youtube] {313} signature length 42.43, html5 player vflZ_L_3c
[youtube] {264} signature length 42.43, html5 player vflZ_L_3c
[youtube] {271} signature length 42.43, html5 player vflZ_L_3c
[youtube] {137} signature length 42.43, html5 player vflZ_L_3c
[youtube] {248} signature length 42.43, html5 player vflZ_L_3c
[youtube] {136} signature length 42.43, html5 player vflZ_L_3c
[youtube] {247} signature length 42.43, html5 player vflZ_L_3c
[youtube] {135} signature length 42.43, html5 player vflZ_L_3c
[youtube] {244} signature length 42.43, html5 player vflZ_L_3c
[youtube] {134} signature length 42.43, html5 player vflZ_L_3c
[youtube] {243} signature length 42.43, html5 player vflZ_L_3c
[youtube] {133} signature length 42.43, html5 player vflZ_L_3c
[youtube] {242} signature length 42.43, html5 player vflZ_L_3c
[youtube] {160} signature length 42.43, html5 player vflZ_L_3c
[youtube] {278} signature length 42.43, html5 player vflZ_L_3c
[youtube] {140} signature length 42.43, html5 player vflZ_L_3c
[youtube] {171} signature length 42.43, html5 player vflZ_L_3c
[youtube] {249} signature length 42.43, html5 player vflZ_L_3c
[youtube] {250} signature length 42.43, html5 player vflZ_L_3c
[youtube] {251} signature length 42.43, html5 player vflZ_L_3c
[youtube] {256} signature length 42.43, html5 player vflZ_L_3c
[youtube] {258} signature length 42.43, html5 player vflZ_L_3c
[youtube] dh_m5Vph8h0: Downloading MPD manifest
[debug] Invoking downloader on 'https://r1---sn-4pcp5q3-j2ie.googlevideo.com/videoplayback?id=761fe6e55a61f21d&itag=266&source=youtube&requiressl=yes&gcr=dk&initcwndbps=3341250&ei=hU80WdKkM4v01gKFx4LICA&mv=m&ctier=A&ms=au&hightc=yes&mm=31&mn=sn-4pcp5q3-j2ie&pfa=5&cmbypass=yes&pl=20&ratebypass=yes&mime=video/mp4&gir=yes&clen=2244879159&lmt=1496180648688970&dur=1415.121&mt=1496600312&key=dg_yt0&signature=44AD19541F059CADE485BFABB3E146749B611F16.8BA8DCFF8EA5865FC3355FDD7C259BE49EF20D0B&ip=5.186.113.128&ipbits=0&expire=1496622054&sparams=ip,ipbits,expire,id,itag,source,requiressl,gcr,initcwndbps,ei,mv,ctier,ms,hightc,mm,mn,pfa,cmbypass,pl,ratebypass,mime,gir,clen,lmt,dur'
[download] Resuming download at byte 94371120
[download] Got server HTTP error. Retrying (attempt 1 of 10)...
[download] Got server HTTP error. Retrying (attempt 2 of 10)...
[download] Got server HTTP error. Retrying (attempt 3 of 10)...
[download] Got server HTTP error. Retrying (attempt 4 of 10)...
[download] Got server HTTP error. Retrying (attempt 5 of 10)...
[download] Got server HTTP error. Retrying (attempt 6 of 10)...
[download] Got server HTTP error. Retrying (attempt 7 of 10)...
[download] Got server HTTP error. Retrying (attempt 8 of 10)...
[download] Got server HTTP error. Retrying (attempt 9 of 10)...
[download] Got server HTTP error. Retrying (attempt 10 of 10)...
ERROR: giving up after 10 retries
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6q2mjw76\build\youtube_dl\__init__.py", line 465, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6q2mjw76\build\youtube_dl\__init__.py", line 455, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6q2mjw76\build\youtube_dl\YoutubeDL.py", line 1897, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6q2mjw76\build\youtube_dl\YoutubeDL.py", line 772, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6q2mjw76\build\youtube_dl\YoutubeDL.py", line 826, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6q2mjw76\build\youtube_dl\YoutubeDL.py", line 1540, in process_video_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6q2mjw76\build\youtube_dl\YoutubeDL.py", line 1804, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6q2mjw76\build\youtube_dl\YoutubeDL.py", line 1746, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6q2mjw76\build\youtube_dl\downloader\common.py", line 360, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6q2mjw76\build\youtube_dl\downloader\http.py", line 131, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6q2mjw76\build\youtube_dl\downloader\common.py", line 162, in report_error
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6q2mjw76\build\youtube_dl\YoutubeDL.py", line 590, in report_error
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6q2mjw76\build\youtube_dl\YoutubeDL.py", line 552, in trouble

---------------------------AND--------------------------------------------
C:\Users\Desktop\youtube-dl>youtube-dl.exe -f 266 --username PRIVATE --password PRIVATE https://www.youtube.com/watch?v=dh_m5Vph8h0 -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', '266', '--username', 'PRIVATE', '--password', 'PRIVATE', 'https://www.youtube.com/watch?v=dh_m5Vph8h0', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.06.05
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-82833-gedb4f5d, ffprobe N-82833-gedb4f5d, rtmpdump 2.3
[debug] Proxy map: {}
[youtube] Downloading login page
[youtube] Looking up account info
[youtube] Logging in
[youtube] Checking cookie
[youtube] dh_m5Vph8h0: Downloading webpage
[youtube] dh_m5Vph8h0: Downloading video info webpage
[youtube] dh_m5Vph8h0: Extracting video information
[youtube] {22} signature length 42.43, html5 player vflZ_L_3c
[youtube] {43} signature length 42.43, html5 player vflZ_L_3c
[youtube] {18} signature length 42.43, html5 player vflZ_L_3c
[youtube] {36} signature length 42.43, html5 player vflZ_L_3c
[youtube] {17} signature length 42.43, html5 player vflZ_L_3c
[youtube] {313} signature length 42.43, html5 player vflZ_L_3c
[youtube] {264} signature length 42.43, html5 player vflZ_L_3c
[youtube] {271} signature length 42.43, html5 player vflZ_L_3c
[youtube] {137} signature length 42.43, html5 player vflZ_L_3c
[youtube] {248} signature length 42.43, html5 player vflZ_L_3c
[youtube] {136} signature length 42.43, html5 player vflZ_L_3c
[youtube] {247} signature length 42.43, html5 player vflZ_L_3c
[youtube] {135} signature length 42.43, html5 player vflZ_L_3c
[youtube] {244} signature length 42.43, html5 player vflZ_L_3c
[youtube] {134} signature length 42.43, html5 player vflZ_L_3c
[youtube] {243} signature length 42.43, html5 player vflZ_L_3c
[youtube] {133} signature length 42.43, html5 player vflZ_L_3c
[youtube] {242} signature length 42.43, html5 player vflZ_L_3c
[youtube] {160} signature length 42.43, html5 player vflZ_L_3c
[youtube] {278} signature length 42.43, html5 player vflZ_L_3c
[youtube] {140} signature length 42.43, html5 player vflZ_L_3c
[youtube] {171} signature length 42.43, html5 player vflZ_L_3c
[youtube] {249} signature length 42.43, html5 player vflZ_L_3c
[youtube] {250} signature length 42.43, html5 player vflZ_L_3c
[youtube] {251} signature length 42.43, html5 player vflZ_L_3c
[youtube] {256} signature length 42.43, html5 player vflZ_L_3c
[youtube] {258} signature length 42.43, html5 player vflZ_L_3c
[youtube] dh_m5Vph8h0: Downloading MPD manifest
[debug] Invoking downloader on 'https://r1---sn-a8au-p5qs.googlevideo.com/videoplayback?id=761fe6e55a61f21d&itag=266&source=youtube&requiressl=yes&gcr=us&mn=sn-a8au-p5qs&mm=31&pl=24&mv=u&ms=au&hightc=yes&ctier=A&pfa=5&cmbypass=yes&ei=K1A0WfSGKoXd1gLGwZuoBA&ratebypass=yes&mime=video/mp4&gir=yes&clen=2244879159&lmt=1496180648688970&dur=1415.121&mt=1496600333&signature=4EE4520649B321A0029FB9B3241F18C8894D4ABD.695497E0D8871C4E832EACE3A4CB2671124DCB9F&key=dg_yt0&beids=[9466593]&ip=50.63.14.70&ipbits=0&expire=1496622219&sparams=ip,ipbits,expire,id,itag,source,requiressl,gcr,mn,mm,pl,mv,ms,hightc,ctier,pfa,cmbypass,ei,ratebypass,mime,gir,clen,lmt,dur'
[download] Resuming download at byte 94371120
[download] Destination: The Interview - Hyperlinked (Ep 8)-dh_m5Vph8h0.mp4
[download]   4.3% of 2.09GiB at 115.24KiB/s ETA 05:03:27ERROR: content too short (expected 2244879159 bytes and served 96468256)
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6q2mjw76\build\youtube_dl\YoutubeDL.py", line 1804, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6q2mjw76\build\youtube_dl\YoutubeDL.py", line 1746, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6q2mjw76\build\youtube_dl\downloader\common.py", line 360, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6q2mjw76\build\youtube_dl\downloader\http.py", line 238, in real_download
youtube_dl.utils.ContentTooShortError: Downloaded 96468256 bytes, expected 2244879159 bytes
...
<end of log>
```

---

- Single video: https://www.youtube.com/watch?v=dh_m5Vph8h0
- Single video: https://www.youtube.com/watch?v=dh_m5Vph8h0
- Playlist: https://www.youtube.com/playlist?list=PLpSnlSGciSWM9NH5FU1WWaNn8gjqZrSYg

---

### Description of *issue*

It keeps giving errors, no matter what I try.

**Comment by dstftw** [comment]
Most likely an intermittent Youtube side issue.
