### ISSUE TITLE
Exception on ArteTVBaseIE

### ISSUE THREAD

**Issue by BendingRodriguez** [rg3/youtube-dl#13289]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.06.05*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.06.05**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

$ youtube-dl -v http://www.arte.tv/de/videos/051656-000-A/die-revolution-der-selbstlosen
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'http://www.arte.tv/de/videos/051656-000-A/die-revolution-der-selbstlosen']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.06.05
[debug] Python version 2.7.9 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.8
[debug] exe versions: avconv 11.9-6, avprobe 11.9-6, rtmpdump 2.4
[debug] Proxy map: {}
[arte.tv:+7] die-revolution-der-selbstlosen: Downloading webpage
[arte.tv:+7] die-revolution-der-selbstlosen: Downloading JSON metadata
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/__init__.py", line 465, in main
    _real_main(argv)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/__init__.py", line 455, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1897, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 761, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/arte.py", line 203, in _real_extract
    return self._extract_from_webpage(webpage, video_id, lang)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/arte.py", line 246, in _extract_from_webpage
    return self._extract_from_json_url(json_url, video_id, lang, title=title)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/arte.py", line 110, in _extract_from_json_url
    for format_id, format_dict in player_info['VSR'].items():
AttributeError: 'list' object has no attribute 'items'

**Comment by BendingRodriguez** [comment]
damn, video not available anymore. sorry.
