### ISSUE TITLE
Problem with some videos on NatGeo

### ISSUE THREAD

**Issue by keybounce** [rg3/youtube-dl#13298]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.06.05*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2017.06.05**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

Some, not all, videos on natgeo are failing.

```
keybounceMBP:Breakthrough michael$ youtube-dl -v 'http://channel.nationalgeographic.com/breakthrough-series/vi
deos/addiction-a-psychedelic-cure/'
[debug] System config: []
[debug] User config: ['-k', '-o', '%(title)s-%(timestamp)6i.%(ext)s', '-f', '\nbest[ext=mp4][height>431][height<=576]/\nbestvideo[ext=mp4][height=480]+bestaudio[ext=m4a]/\nbest[ext=mp4][height>340][height<=431]/\nbestvideo[ext=mp4][height>360][height<=576]+bestaudio/\nbest[height>340][height<=576]/\nbestvideo[height>360][height<=576]+bestaudio/\nbestvideo[height=360]+bestaudio/\nbest[ext=mp4][height>=280][height<=360]/\nbest[height<=576]/\nworst', '--ap-mso', 'Dish', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '--write-sub', '--write-auto-sub', '--sub-lang', 'en,enUS,en-us', '--sub-format', 'ass/srt/best', '--convert-subs', 'ass', '--embed-subs', '--recode-video', 'mp4', '--mark-watched', '--download-archive', 'downloaded-videos.txt']
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://channel.nationalgeographic.com/breakthrough-series/videos/addiction-a-psychedelic-cure/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.06.05
[debug] Python version 3.6.1 - Darwin-13.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.2.4, ffprobe 3.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[natgeo] addiction-a-psychedelic-cure: Downloading webpage
[natgeo] FnncmlR7GxHu: Retrieving Authorization Token
ERROR: Unable to extract details; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/Users/michael/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 761, in extract_info
    ie_result = ie.extract(url)
  File "/Users/michael/bin/youtube-dl/youtube_dl/extractor/common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "/Users/michael/bin/youtube-dl/youtube_dl/extractor/nationalgeographic.py", line 124, in _real_extract
    query['auth'] = self._extract_mvpd_auth(url, video_id, 'natgeo', auth_resource_id)
  File "/Users/michael/bin/youtube-dl/youtube_dl/extractor/adobepass.py", line 1555, in _extract_mvpd_auth
    raise ExtractorError(xml_text(authorize, 'details'), expected=True)
  File "/Users/michael/bin/youtube-dl/youtube_dl/extractor/adobepass.py", line 1345, in xml_text
    '<%s>(.+?)</%s>' % (tag, tag), xml_str, tag)
  File "/Users/michael/bin/youtube-dl/youtube_dl/extractor/common.py", line 782, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract details; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

keybounceMBP:Breakthrough michael$ 
```

**Comment by remitamine** [comment]
Dish Network is not one of the supported TV Providers.

**Comment by keybounce** [comment]
Pull request #12000 works for dish.

**Comment by remitamine** [comment]
```
youtube-dl --external-downloader curl --ap-mso Comcast_SSO http://channel.nationalgeographic.com/breakthrough-series/videos/addiction-a-psychedelic-cure/
[natgeo] addiction-a-psychedelic-cure: Downloading webpage
[natgeo] FnncmlR7GxHu: Retrieving Authorization Token
[natgeo] FnncmlR7GxHu: Retrieving Media Token
[natgeo] FnncmlR7GxHu: Downloading http SMIL data
[natgeo] FnncmlR7GxHu: Checking video URL
[natgeo] FnncmlR7GxHu: Checking video URL
[natgeo] FnncmlR7GxHu: Checking video URL
[natgeo] FnncmlR7GxHu: Checking video URL
[natgeo] FnncmlR7GxHu: Checking video URL
[natgeo] FnncmlR7GxHu: Checking video URL
[natgeo] FnncmlR7GxHu: Downloading m3u SMIL data
[natgeo] FnncmlR7GxHu: Downloading m3u8 information
[natgeo] addiction-a-psychedelic-cure: Downloading JSON metadata
WARNING: ar subtitles not available for FnncmlR7GxHu
[info] Writing video subtitles to: Addiction - A Psychedelic Cure-FnncmlR7GxHu.en.srt
[download] Destination: Addiction - A Psychedelic Cure-FnncmlR7GxHu.mp4
```

**Comment by keybounce** [comment]
--external-downloader curl? 

I will give that a try in the morning. 

So why does it work with curl and not directly?

**Comment by remitamine** [comment]
> So why does it work with curl and not directly?

it's not related to `--external-downloader curl`, i use it to avoid the 403 error in fox websites(NatGeo, FXNetworks) when i'm using `aria2c` in the config.
as the output show it works fine using `Comcast_SSO` on the same scenario(expiration of the authorization token).

**Comment by keybounce** [comment]
Now here's an oddity. It's working today. But it has slightly different output:

```
[debug] Proxy map: {}
[natgeo] addiction-a-psychedelic-cure: Downloading webpage
[natgeo] FnncmlR7GxHu: Retrieving Media Token
[natgeo] FnncmlR7GxHu: Downloading http SMIL data
```

Note that the "[natgeo] FnncmlR7GxHu: Retrieving Authorization Token" line is missing?

Interestingly, the website claims that the episode is still locked.

Alright, time to file a "not quite ready" report to pull request 12000.
