### ISSUE TITLE
Problems with Disney: Different sites, different rules (3 of 2 :-)

### ISSUE THREAD

**Issue by keybounce** [rg3/youtube-dl#13305]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.06.05*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [xx ] I've **verified** and **I assure** that I'm running youtube-dl **2017.06.05**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ x] Bug report (encountered problems with youtube-dl)
- [x ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

Disney has the same show available from different URL's and different sites.

Star vs the forces of evil works from Disney XD:
http://watchdisneyxd.go.com/star-vs-the-forces-of-evil

It fails from Disney Channel:
http://watchdisneychannel.go.com/star-vs-the-forces-of-evil-disney-channel

```
keybounceMBP:Disney michael$ ./yt-dl -v http://watchdisneychannel.go.com/star-vs-the-forces-of-evil-disney-cha
nnel

[debug] System config: []
[debug] User config: ['-k', '-o', '%(title)s-%(timestamp)6i.%(ext)s', '-f', '\nbest[ext=mp4][height>431][height<=576]/\nbestvideo[ext=mp4][height=480]+bestaudio[ext=m4a]/\nbest[ext=mp4][height>340][height<=431]/\nbestvideo[ext=mp4][height>360][height<=576]+bestaudio/\nbest[height>340][height<=576]/\nbestvideo[height>360][height<=576]+bestaudio/\nbestvideo[height=360]+bestaudio/\nbest[ext=mp4][height>=280][height<=360]/\nbest[height<=576]/\nworst', '--ap-mso', 'Dish', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '--write-sub', '--write-auto-sub', '--sub-lang', 'en,enUS,en-us', '--sub-format', 'ass/srt/best', '--convert-subs', 'ass', '--embed-subs', '--recode-video', 'mp4', '--mark-watched', '--download-archive', 'downloaded-videos.txt']
[debug] Custom config: []
[debug] Command-line args: ['-o', '%(series)s/s%(season_number)02d-e%(episode_number)02d-%(title)s.%(ext)s', '-v', 'http://watchdisneychannel.go.com/star-vs-the-forces-of-evil-disney-channel']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.06.05
[debug] Python version 3.6.1 - Darwin-13.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.2.4, ffprobe 3.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[Go] star-vs-the-forces-of-evil-disney-channel: Downloading webpage
[Go] SH553862036: Downloading JSON metadata
[download] Downloading playlist: Star vs the Forces of Evil
[Go] playlist Star vs the Forces of Evil: Collected 6 video ids (downloading 6 of them)
[download] Downloading video 1 of 6
[Go] vdka3862755: Downloading JSON metadata
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/michael/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/Users/michael/bin/youtube-dl/youtube_dl/__init__.py", line 465, in main
  File "/Users/michael/bin/youtube-dl/youtube_dl/__init__.py", line 455, in _real_main
  File "/Users/michael/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1897, in download
  File "/Users/michael/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 772, in extract_info
  File "/Users/michael/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 963, in process_ie_result
  File "/Users/michael/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 833, in process_ie_result
  File "/Users/michael/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 761, in extract_info
  File "/Users/michael/bin/youtube-dl/youtube_dl/extractor/common.py", line 433, in extract
  File "/Users/michael/bin/youtube-dl/youtube_dl/extractor/go.py", line 95, in _real_extract
IndexError: list index out of range
keybounceMBP:Disney michael$ 
```

The same issue and error: Sofia the First works from Disney Junior: 
http://watchdisneyjunior.go.com/sofia-the-first

And fails from Disney Channel:
http://watchdisneychannel.go.com/sofia-the-first-disney-channel

```
keybounceMBP:Disney michael$ ./yt-dl -v http://watchdisneychannel.go.com/sofia-the-first-disney-channel
[debug] System config: []
[debug] User config: ['-k', '-o', '%(title)s-%(timestamp)6i.%(ext)s', '-f', '\nbest[ext=mp4][height>431][height<=576]/\nbestvideo[ext=mp4][height=480]+bestaudio[ext=m4a]/\nbest[ext=mp4][height>340][height<=431]/\nbestvideo[ext=mp4][height>360][height<=576]+bestaudio/\nbest[height>340][height<=576]/\nbestvideo[height>360][height<=576]+bestaudio/\nbestvideo[height=360]+bestaudio/\nbest[ext=mp4][height>=280][height<=360]/\nbest[height<=576]/\nworst', '--ap-mso', 'Dish', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '--write-sub', '--write-auto-sub', '--sub-lang', 'en,enUS,en-us', '--sub-format', 'ass/srt/best', '--convert-subs', 'ass', '--embed-subs', '--recode-video', 'mp4', '--mark-watched', '--download-archive', 'downloaded-videos.txt']
[debug] Custom config: []
[debug] Command-line args: ['-o', '%(series)s/s%(season_number)02d-e%(episode_number)02d-%(title)s.%(ext)s', '-v', 'http://watchdisneychannel.go.com/sofia-the-first-disney-channel']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.06.05
[debug] Python version 3.6.1 - Darwin-13.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.2.4, ffprobe 3.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[Go] sofia-the-first-disney-channel: Downloading webpage
[Go] SH553867121: Downloading JSON metadata
[download] Downloading playlist: Sofia the First
[Go] playlist Sofia the First: Collected 5 video ids (downloading 5 of them)
[download] Downloading video 1 of 5
[Go] vdka3869184: Downloading JSON metadata
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/michael/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/Users/michael/bin/youtube-dl/youtube_dl/__init__.py", line 465, in main
  File "/Users/michael/bin/youtube-dl/youtube_dl/__init__.py", line 455, in _real_main
  File "/Users/michael/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1897, in download
  File "/Users/michael/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 772, in extract_info
  File "/Users/michael/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 963, in process_ie_result
  File "/Users/michael/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 833, in process_ie_result
  File "/Users/michael/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 761, in extract_info
  File "/Users/michael/bin/youtube-dl/youtube_dl/extractor/common.py", line 433, in extract
  File "/Users/michael/bin/youtube-dl/youtube_dl/extractor/go.py", line 95, in _real_extract
IndexError: list index out of range
keybounceMBP:Disney michael$ 
```

(NB: In both cases, there are more episodes on Junior/XD, so fetching from there is preferable anyways.)

**Comment by dstftw** [comment]
Dish MSO is not supported.

**Comment by gkoelln** [comment]
@dstftw, he's using #12000. I get the same results when I use my MSO from #12641.

**Comment by keybounce** [comment]
Yea, the dish access works really really well. Only place it doesn't work is Science Channel :-) .

**Comment by gkoelln** [comment]
It appears to be an issue with the site.  If I look at the playlist gathered and replace the URLs (watchdisneyjunior with watchdisneychannel), they come up in the browser.
