### ISSUE TITLE
NRL on livestream.com

### ISSUE THREAD

**Issue by Brandhand** [rg3/youtube-dl#13334]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.06.05*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.06.05**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
youtube-dl https://livestream.com/nrl/eelsvcowboys2017 -v
[debug] System config: []
[debug] User config: [u'--prefer-ffmpeg', u'--download-archive', u'/home/meikel/.youtube']
[debug] Custom config: []
[debug] Command-line args: [u'https://livestream.com/nrl/eelsvcowboys2017', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.06.05
[debug] Python version 2.7.13 - Linux-4.9.0-3-amd64-x86_64-with-debian-9.0
[debug] exe versions: avconv 3.2.5-1, avprobe 3.2.5-1, ffmpeg 3.2.5-1, ffprobe 3.2.5-1, rtmpdump 2.4
[debug] Proxy map: {}
[livestream] Downloading JSON metadata
[livestream] 6990822: Downloading page 1
[livestream] 6990822: Downloading page 2
[download] Downloading playlist: Eels v Cowboys
[livestream] playlist Eels v Cowboys: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[livestream] 157912343: Downloading JSON metadata
[livestream] 157912343: Downloading SMIL file
[debug] Invoking downloader on u'http://livestream-f.akamaihd.net/3161248_6990822_lsi66jqrsv6l908g377_1_2320@407740?fp=WIN%25+14%2C0%2C0%2C145&v=3.0.3&ssek=805'
[download] Destination: Eels v Cowboys-157912343.flv
[download]   0.1% of 2.00GiB at 219.22KiB/s ETA 02:39:16ERROR: content too short (expected 2147483647 bytes and served 2248877)
Traceback (most recent call last):
  File "/home/meikel/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1804, in process_info
    success = dl(filename, info_dict)
  File "/home/meikel/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1746, in dl
    return fd.download(name, info)
  File "/home/meikel/bin/youtube-dl/youtube_dl/downloader/common.py", line 360, in download
    return self.real_download(filename, info_dict)
  File "/home/meikel/bin/youtube-dl/youtube_dl/downloader/http.py", line 238, in real_download
    raise ContentTooShortError(byte_counter, int(data_len))
ContentTooShortError: Downloaded 2248877 bytes, expected 2147483647 bytes 

---

**Comment by Brandhand** [comment]
The stream from the above URL is now downloadable. But here is a new one which isn't:
```
youtube-dl https://livestream.com/nrl/newsouthwalesvqueenslandSOO2017 -v
[debug] System config: []
[debug] User config: [u'--prefer-ffmpeg', u'--download-archive', u'/home/meikel/.youtube']
[debug] Custom config: []
[debug] Command-line args: [u'https://livestream.com/nrl/newsouthwalesvqueenslandSOO2017', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.06.18
[debug] Python version 2.7.13 - Linux-4.9.0-3-amd64-x86_64-with-debian-9.0
[debug] exe versions: avconv 3.2.5-1, avprobe 3.2.5-1, ffmpeg 3.2.5-1, ffprobe 3.2.5-1, rtmpdump 2.4
[debug] Proxy map: {}
[livestream] Downloading JSON metadata
[livestream] 7103183: Downloading page 1
[livestream] 7103183: Downloading page 2
[download] Downloading playlist: New South Wales v Queensland
[livestream] playlist New South Wales v Queensland: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[livestream] 158560011: Downloading JSON metadata
[livestream] 158560011: Downloading SMIL file
[debug] Invoking downloader on u'http://livestream-f.akamaihd.net/3161248_7103183_lsi8yh9rm3krndb3hky_1_2320@125978?fp=WIN%25+14%2C0%2C0%2C145&v=3.0.3&ssek=1473'
[download] Resuming download at byte 2645489
[download] Unable to resume
[download] Destination: New South Wales v Queensland-158560011.flv
[download]   0.1% of 2.00GiB at 258.85KiB/s ETA 02:14:51ERROR: content too short (expected 2147483647 bytes and served 2645490)
Traceback (most recent call last):
  File "/home/meikel/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1826, in process_info
    success = dl(filename, info_dict)
  File "/home/meikel/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1768, in dl
    return fd.download(name, info)
  File "/home/meikel/bin/youtube-dl/youtube_dl/downloader/common.py", line 361, in download
    return self.real_download(filename, info_dict)
  File "/home/meikel/bin/youtube-dl/youtube_dl/downloader/http.py", line 238, in real_download
    raise ContentTooShortError(byte_counter, int(data_len))
ContentTooShortError: Downloaded 2645490 bytes, expected 2147483647 bytes 
```

**Comment by Brandhand** [comment]
The NRL closed the account on livestream.com. So this issued can be closed, too.
