### ISSUE TITLE
only fail to download 1080p

### ISSUE THREAD

**Issue by nskzhd** [rg3/youtube-dl#13342]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.06.05*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2017.06.05**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
youtube-dl

>youtube-dl -v -F "http://www.msn.com/en-gb/video/watch/msn-meets-taylor-schilli
ng-and-jason-biggs-full-length-interview/vi-BBG2lT"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'http://www.msn.com/en-gb/video/watch/ms
n-meets-taylor-schilling-and-jason-biggs-full-length-interview/vi-BBG2lT']
[debug] Encodings: locale cp949, fs mbcs, out cp949, pref cp949
[debug] youtube-dl version 2017.06.05
[debug] Python version 3.4.4 - Windows-8-6.2.9200-SP0
[debug] exe versions: ffmpeg N-86175-g64ea4d1, ffprobe N-86175-g64ea4d1
[debug] Proxy map: {}
[MSN] msn-meets-taylor-schilling-and-jason-biggs-full-length-interview: Download
ing webpage
[MSN] msn-meets-taylor-schilling-and-jason-biggs-full-length-interview: Download
ing ISM manifest
WARNING: [MSN] WVC1 is not a supported codec
WARNING: [MSN] WVC1 is not a supported codec
WARNING: [MSN] WVC1 is not a supported codec
WARNING: [MSN] WVC1 is not a supported codec
WARNING: [MSN] WVC1 is not a supported codec
WARNING: [MSN] WVC1 is not a supported codec
WARNING: [MSN] WVC1 is not a supported codec
WARNING: [MSN] WVC1 is not a supported codec
WARNING: [MSN] WMAP is not a supported codec
[info] Available formats for BBG2lT:
format code  extension  resolution note
http-0       mp4        320x180
http-1       mp4        640x360
http-2       mp4        1024x576
http-3       mp4        1280x720
http-4       mp4        1920x1080  (best)

>youtube-dl -v -f http-4 "http://www.msn.com/en-gb/video/watch/msn-meets-taylor-
schilling-and-jason-biggs-full-length-interview/vi-BBG2lT"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-f', 'http-4', 'http://www.msn.com/en-gb/vide
o/watch/msn-meets-taylor-schilling-and-jason-biggs-full-length-interview/vi-BBG2
lT']
[debug] Encodings: locale cp949, fs mbcs, out cp949, pref cp949
[debug] youtube-dl version 2017.06.05
[debug] Python version 3.4.4 - Windows-8-6.2.9200-SP0
[debug] exe versions: ffmpeg N-86175-g64ea4d1, ffprobe N-86175-g64ea4d1
[debug] Proxy map: {}
[MSN] msn-meets-taylor-schilling-and-jason-biggs-full-length-interview: Download
ing webpage
[MSN] msn-meets-taylor-schilling-and-jason-biggs-full-length-interview: Download
ing ISM manifest
WARNING: [MSN] WVC1 is not a supported codec
WARNING: [MSN] WVC1 is not a supported codec
WARNING: [MSN] WVC1 is not a supported codec
WARNING: [MSN] WVC1 is not a supported codec
WARNING: [MSN] WVC1 is not a supported codec
WARNING: [MSN] WVC1 is not a supported codec
WARNING: [MSN] WVC1 is not a supported codec
WARNING: [MSN] WVC1 is not a supported codec
WARNING: [MSN] WMAP is not a supported codec
[debug] Invoking downloader on 'http://msnvideo-s.akamaihd.net/ondemand/o01/ENGB
_msnvideo_ENGB_msnvideo_original_tv/1004/654ee149-ac4b-4a11-9fd2-2a55e677decf.is
m'
ERROR: unable to download video data: HTTP Error 400: Bad Request
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6q2mjw76\bu
ild\youtube_dl\YoutubeDL.py", line 1804, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6q2mjw76\bu
ild\youtube_dl\YoutubeDL.py", line 1746, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6q2mjw76\bu
ild\youtube_dl\downloader\common.py", line 360, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6q2mjw76\bu
ild\youtube_dl\downloader\http.py", line 61, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6q2mjw76\bu
ild\youtube_dl\YoutubeDL.py", line 2107, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_defau
lt
urllib.error.HTTPError: HTTP Error 400: Bad Request


>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

It doesn't let me download "http-4 1920x1080 (best)" from "http://www.msn.com/en-gb/video/watch/msn-meets-taylor-schilling-and-jason-biggs-full-length-interview/vi-BBG2lT"
I was able to download "http-3 1280x720", but not 1080p.

Anyone can help with this issue?

Sorry for my english.

**Comment by Hrxn** [comment]
Can reproduce..
```
ERROR: unable to download video data: HTTP Error 400: Bad Request
...
PS E:\test> youtube-dl -v
[debug] System config: []
[debug] User config: ['--format', 'bestvideo[ext=webm]+bestaudio[ext=webm]/bestvideo+bestaudio']
[debug] Custom config: []
[debug] Command-line args: ['-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.06.05
[debug] Python version 3.4.4 - Windows-10-10.0.15063
[debug] exe versions: ffmpeg 3.2.4, ffprobe 3.2.4
[debug] Proxy map: {}
Usage: youtube-dl.exe [OPTIONS] URL [URL...]

```

**Comment by nskzhd** [comment]
I just noticed that when I try to download 1080p, youtube-dl gives me the url "~.ism" unlike other resolution. So I was searching how to download files from '.ism' url, and I found out "[ismdownloader](http://md5decrypt.altervista.org/ismdownloaderavc1.htm)" reading [this post](https://forum.videohelp.com/threads/356428-How-to-record-or-capture-silverlight-ism-manifest-stream).

And it works!!!

I am just a noob to all the video downloading, so I don't know this could be available with youtube-dl, but really hope it will!
