### ISSUE TITLE
ERROR: unable to download video data: urlopen error [Errno 65] No route to host

### ISSUE THREAD

**Issue by arielelkin** [rg3/youtube-dl#13356]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.06.12*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.06.12**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

```
$ youtube-dl --version
2017.06.12
$
$ youtube-dl -v https://youtu.be/Wx_5GI0QRdw
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://youtu.be/Wx_5GI0QRdw']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.06.12
[debug] Python version 2.7.10 - Darwin-16.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.2.4, ffprobe 3.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] Wx_5GI0QRdw: Downloading webpage
[youtube] Wx_5GI0QRdw: Downloading video info webpage
[youtube] Wx_5GI0QRdw: Extracting video information
[youtube] Wx_5GI0QRdw: Downloading MPD manifest
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on u'https://r4---sn-uxaxjxougv-x1xk.googlevideo.com/videoplayback?key=yt6&pl=22&ipbits=0&initcwndbps=1358750&ip=186.23.209.2&expire=1497319780&lmt=1496175794140045&signature=45CDAF01DD5072E2F939AA057B69188B368F1828.5B16B1C324F8F76595B1BCBF3A5C6DB840481214&mm=31&mn=sn-uxaxjxougv-x1xk&gir=yes&mime=video%2Fwebm&dur=28.395&id=o-AMaKwJwKgtmtqIme7QfIVevrufw5A87pw-3q71AZLJbE&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&mv=m&mt=1497297936&ms=au&source=youtube&clen=5259254&keepalive=yes&itag=247&requiressl=yes&ei=BPU-Wf_kF4PAwwS5lqmQCA&ratebypass=yes'
ERROR: unable to download video data: <urlopen error [Errno 65] No route to host>
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1820, in process_info
    partial_success = dl(fname, new_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1768, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 360, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 61, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2129, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1087, in https_open
    req, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 65] No route to host>
```

**Comment by dstftw** [comment]
Connectivity issue between you and r4---sn-uxaxjxougv-x1xk.googlevideo.com.

**Comment by arielelkin** [comment]
Ok, thanks for the reply. Kind of a weird error because I'm obviously able to watch the video on the browser.. how can I fix it?

**Comment by theStupidProwler** [comment]
Are you behind a proxy?

**Comment by arielelkin** [comment]
No.

**Comment by theStupidProwler** [comment]
At least, I will have tried ;)
