### ISSUE TITLE
History.ca only downloads an html file, not the video.

### ISSUE THREAD

**Issue by level42ca** [rg3/youtube-dl#13359]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.06.12*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.06.12**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v --ap-mso Rogers -n http://www.history.ca/the-world-without-canada/video/full-episodes/natural-resources/video.html?v=955054659646#video

SUCCESS: Specified value was saved.
[debug] System config: []
[debug] User config: [u'-o', u'c:/YouTube-DL/%(series)s - S0%(season_number)sE0%(episode_number)s - %(title)s.%(ext)s', u'-n', u'--ap-mso', u'Rogers']
[debug] Custom config: []
[debug] Command-line args: [u'http://www.history.ca/the-world-without-canada/video/full-episodes/natural-resources/video.html?v=955054659646', u'-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.06.12
[debug] Python version 2.7.12 - Windows-10-10.0.14393
[debug] exe versions: none
[debug] Proxy map: {}
[generic] video: Requesting header
WARNING: Falling back on generic information extractor.
[generic] video: Downloading webpage
[generic] video: Extracting information
[debug] Invoking downloader on u'http://www.history.ca/the-world-without-canada/video/full-episodes/natural-resources/video.html?v=955054659646'
[download] c:\YouTube-DL\NA - S0NAE0NA - The World Without Canada Video - Natural Resources _ Season 1 Episode 1 - history.ca.html has already been downloaded
[download] 100% of 50.05KiB
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://www.history.ca/the-world-without-canada/video/full-episodes/natural-resources/video.html?v=955054659646#video

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

I haven't used YDL in a long time, however, when ever I try to download something from history.ca I get nothing but a 50kb .html file. that is all. Not sure what is going on and I've been unable to find any info online.

**Comment by level42ca** [comment]
I appreciate the quick response, however now I get the following error with -v

I double checked my corous.py file to ensure it included the changes that you've made, but still, no go.

```
SUCCESS: Specified value was saved.
[debug] System config: []
[debug] User config: [u'-o', u'c:/YouTube-DL/%(series)s - S0%(season_number)sE0%(episode_number)s - %(title)s.%(ext)s', u'-n', u'--ap-mso', u'Rogers']
[debug] Custom config: []
[debug] Command-line args: [u'http://www.history.ca/the-world-without-canada/video/full-episodes/natural-resources/video.html?v=955054659646', u'-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.06.12
[debug] Python version 2.7.12 - Windows-10-10.0.14393
[debug] exe versions: none
[debug] Proxy map: {}
[Corus] 955054659646: Downloading JSON metadata
[Corus] 955054659646: Downloading SMIL data for MP4 MBR
[Corus] 955054659646: Downloading SMIL data for HDS
[Corus] 955054659646: Downloading SMIL data for HLS
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\python27\youtube-dl-master\youtube_dl\YoutubeDL.py", line 762, in extract_info
    ie_result = ie.extract(url)
  File "c:\python27\youtube-dl-master\youtube_dl\extractor\common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "c:\python27\youtube-dl-master\youtube_dl\extractor\corus.py", line 95, in _real_extract
    }, feed_info['account_id'])
  File "c:\python27\youtube-dl-master\youtube_dl\extractor\theplatform.py", line 362, in _extract_feed_info
    self._sort_formats(formats)
  File "c:\python27\youtube-dl-master\youtube_dl\extractor\common.py", line 1056, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
