### ISSUE TITLE
[Go90] HTTP Error: 401 Forbidden

### ISSUE THREAD

**Issue by RuneMagle** [rg3/youtube-dl#13369]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.06.12**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
```
C:\Users\Desktop\youtube-dl>youtube-dl.exe -f best --all-subs --geo-bypass --geo-bypass-country US https://www.go90.com/videos/1n5H0Jz1jh2 -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'best', '--all-subs', '--geo-bypass', '--geo-bypass-country', 'US', 'https://www.go90.com/videos/1n5H0Jz1jh2', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.06.12
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-82833-gedb4f5d, ffprobe N-82833-gedb4f5d, rtmpdump 2.3
[debug] Proxy map: {}
[debug] Using fake IP 3.231.214.230 (US) as X-Forwarded-For.
[Go90] 1n5H0Jz1jh2: Downloading JSON metadata
[Go90] 1n5H0Jz1jh2: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 403: Forbidden
[Go90] 1n5H0Jz1jh2: Downloading m3u8 information
[debug] Invoking downloader on 'https://streams-a.revvel-static.io/2rwdJAI1OCV/mp4-1080-4800K-9vsG2U8WLaG.mp4'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkyaecyzu\build\youtube_dl\YoutubeDL.py", line 1826, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkyaecyzu\build\youtube_dl\YoutubeDL.py", line 1768, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkyaecyzu\build\youtube_dl\downloader\common.py", line 360, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkyaecyzu\build\youtube_dl\downloader\http.py", line 61, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkyaecyzu\build\youtube_dl\YoutubeDL.py", line 2129, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden
--------------------------------------------------SECOND------------------------------------------------
C:\Users\Desktop\youtube-dl>youtube-dl.exe -f best --all-subs https://streams-a.revvel-static.io/2rwdJAI1OCV/mp4-1080-4800K-9vsG2U8WLaG.mp4?b7iMb9xz3WcbZSRDTK6vSjzHOfs-B9iAgVQSpnGq_gsuMl26WSjWp9PYwVFkYGoz1YGwStdiGZcxbJoa-o-S_PVnDrmdb0FvVxqKQEBQOtRJF1n-oDEj2c1A2h-bNwLrQZwn7ekpTGfoRcEnFjCSWLG6zvRtnGNM7JXfMW0645D5D4J6tyYqDKPfo_FoevgB_cZpdrEG8q8iR5UL6sckB-lgRfAQGkcFAtk -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'best', '--all-subs', 'https://streams-a.revvel-static.io/2rwdJAI1OCV/mp4-1080-4800K-9vsG2U8WLaG.mp4?b7iMb9xz3WcbZSRDTK6vSjzHOfs-B9iAgVQSpnGq_gsuMl26WSjWp9PYwVFkYGoz1YGwStdiGZcxbJoa-o-S_PVnDrmdb0FvVxqKQEBQOtRJF1n-oDEj2c1A2h-bNwLrQZwn7ekpTGfoRcEnFjCSWLG6zvRtnGNM7JXfMW0645D5D4J6tyYqDKPfo_FoevgB_cZpdrEG8q8iR5UL6sckB-lgRfAQGkcFAtk', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.06.05
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-82833-gedb4f5d, ffprobe N-82833-gedb4f5d, rtmpdump 2.3
[debug] Proxy map: {}
[generic] mp4-1080-4800K-9vsG2U8WLaG: Requesting header
WARNING: Could not send HEAD request to https://streams-a.revvel-static.io/2rwdJAI1OCV/mp4-1080-4800K-9vsG2U8WLaG.mp4?b7iMb9xz3WcbZSRDTK6vSjzHOfs-B9iAgVQSpnGq_gsuMl26WSjWp9PYwVFkYGoz1YGwStdiGZcxbJoa-o-S_PVnDrmdb0FvVxqKQEBQOtRJF1n-oDEj2c1A2h-bNwLrQZwn7ekpTGfoRcEnFjCSWLG6zvRtnGNM7JXfMW0645D5D4J6tyYqDKPfo_FoevgB_cZpdrEG8q8iR5UL6sckB-lgRfAQGkcFAtk: HTTP Error 403: Forbidden
[generic] mp4-1080-4800K-9vsG2U8WLaG: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6q2mjw76\build\youtube_dl\extractor\common.py", line 502, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6q2mjw76\build\youtube_dl\YoutubeDL.py", line 2107, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
...
<end of log>
```

---

- Single video: https://www.go90.com/videos/1n5H0Jz1jh2

---

### Description of *issue*

Usually worked before, not anymore. Also before I could just grab the link from where it said "Invoking Download", and insert in yt-dl, and it would download fine, now it doesn't. But it works fine if I put the link in FFmpeg.

**Comment by dstftw** [comment]
Video is geo restricted:
```
> py -3.6 .\youtube_dl\__main__.py https://www.go90.com/videos/1n5H0Jz1jh2 --proxy 52.10.104.200:3128
[Go90] 1n5H0Jz1jh2: Downloading JSON metadata
[Go90] 1n5H0Jz1jh2: Downloading MPD manifest
[Go90] 1n5H0Jz1jh2: Downloading m3u8 information
[download] Destination: t@gged - CONFRONTATION-1n5H0Jz1jh2.fdash-1080_1784874.mp4
[download]   0.3% of 300.91MiB at 384.10KiB/s ETA 13:19
ERROR: Interrupted by user
```

**Comment by RuneMagle** [comment]
No, because when I do it:
```
C:\Users\rumag\Desktop\youtube-dl>youtube-dl.exe -f best --all-subs --proxy 52.10.104.200:3128 https://www.go90.com/videos/1n5H0Jz1jh2 -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'best', '--all-subs', '--proxy', '52.10.104.200:3128', 'https://www.go90.com/videos/1n5H0Jz1jh2', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.06.12
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-82833-gedb4f5d, ffprobe N-82833-gedb4f5d, rtmpdump 2.3
[debug] Proxy map: {'https': '52.10.104.200:3128', 'http': '52.10.104.200:3128'}
[Go90] 1n5H0Jz1jh2: Downloading JSON metadata
[Go90] 1n5H0Jz1jh2: Downloading MPD manifest
[Go90] 1n5H0Jz1jh2: Downloading m3u8 information
[debug] Invoking downloader on 'https://www.revvel.io/api/playlists/sub/1n5H0Jz1jh2/6w9FaLuzcYM/hls/hls-1080-4800K?key=go90&expires_at=1497371656&v_source=a&token=019b52c102b6f94229f97c4af0266eedba5715ac45828218f5b849d93aaf3471'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 283
[download] Destination: t@gged - CONFRONTATION-1n5H0Jz1jh2.mp4
[download]   0.0% of ~98.59GiB at  1.69MiB/s ETA 17:39:44
```

**Comment by dstftw** [comment]
Filesize is extrapolated and approximate.
