### ISSUE TITLE
2-way auth to google

### ISSUE THREAD

**Issue by Forever-Young** [rg3/youtube-dl#1336]
Does youtube-dl work with 2-way authentication to google, or application-specific passwords?
I tried both account password and app-specific generated password, 'unable to log in'

**Comment by scottfromsf** [comment]
Google 2FA seems to be working now. I don't know how long this has been the case but someone might want to close this issue.

**Comment by yan12125** [comment]
Since #3534 TOTP (using the Google Authenticator app or equivalent) is supported via --twofactor. I don't use other 2FA code generation approaches. Maybe others can have a check?

**Comment by mholt** [comment]
Using 2FA with TOTP on my Google acount results in a 500 error (using youtube-dl 2017.06.25):

```
youtube-dl https://www.youtube.com/watch?v=rAUJN48IHXw --username="<email>"
Type account password and press [Return]: 
[youtube] Downloading login page
[youtube] Looking up account info
[youtube] Logging in
Type 2-step verification code and press [Return]: 
[youtube] Submitting TFA code
WARNING: Unable to submit TFA code: HTTP Error 500: Internal Server Error
```

After entering my password, my Android Phone asks "are you trying to log in to your Google account?" - I've tried various combinations of saying Yes and ignoring the prompt and entering the TOTP code into the terminal but all result in the 500 error. So, I don't think this is working...

**Comment by AzureRaptor** [comment]
I'm in the exact situation as mholt above, except my error is "400:  Bad Request".  The video(s) are not DRM-protected or anything special.  I get the prompt on my Android phone, etc., and enter the 2FA code, but no matter what I do, it always errors out with that 400 error.

It seems like the Google Authenticator 2FA code is not being properly submitted somehow.  Is there any movement on this issue?

**Comment by chenrui333** [comment]
Have the exact problem. 
```
$ youtube-dl -u "<email>"  https://www.youtube.com/watch?v=rAUJN48IHXw -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-u', u'PRIVATE', u'https://youtube.com/watch?v=rAUJN48IHXw', u'-v']
Type account password and press [Return]:
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.10.29
[debug] Python version 2.7.15 (CPython) - Darwin-18.0.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.0.2, ffprobe 4.0.2
[debug] Proxy map: {}
[youtube] Downloading login page
[youtube] Looking up account info
[youtube] Logging in
Type 2-step verification code and press [Return]:
[youtube] Submitting TFA code
WARNING: Unable to submit TFA code: HTTP Error 500: Internal Server Error
[youtube] rAUJN48IHXw: Downloading webpage
[youtube] rAUJN48IHXw: Downloading video info webpage
WARNING: Unable to extract video title
ERROR: This video is unavailable.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1897, in _real_extract
    raise ExtractorError(error_message, expected=True)
ExtractorError: This video is unavailable.
```

**Comment by dimpase** [comment]
I'd have tried using an "app password", which you can generate in the 2FA settings of your Google account.
