### ISSUE TITLE
[nationalpost] Site support

### ISSUE THREAD

**Issue by jnbdz** [rg3/youtube-dl#13368]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.06.12*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.06.12**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v http://news.nationalpost.com/news/world/bana-alabed-the-seven-year-old-who-live-tweeted-horrors-of-syrian-war-escapes-from-aleppo
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'http://news.nationalpost.com/news/world/bana-alabed-the-seven-year-old-who-live-tweeted-horrors-of-syrian-war-escapes-from-aleppo']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.06.12
[debug] Python version 2.7.12 - Linux-4.4.0-72-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1
[debug] Proxy map: {}
[generic] bana-alabed-the-seven-year-old-who-live-tweeted-horrors-of-syrian-war-escapes-from-aleppo: Requesting header
WARNING: Falling back on generic information extractor.
[generic] bana-alabed-the-seven-year-old-who-live-tweeted-horrors-of-syrian-war-escapes-from-aleppo: Downloading webpage
[generic] bana-alabed-the-seven-year-old-who-live-tweeted-horrors-of-syrian-war-escapes-from-aleppo: Extracting information
ERROR: Unsupported URL: http://news.nationalpost.com/news/world/bana-alabed-the-seven-year-old-who-live-tweeted-horrors-of-syrian-war-escapes-from-aleppo
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1971, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2539, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2528, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 2, column 193
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 762, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2796, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://news.nationalpost.com/news/world/bana-alabed-the-seven-year-old-who-live-tweeted-horrors-of-syrian-war-escapes-from-aleppo
...
<end of log>
```

---

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Just site support.

**Comment by jnbdz** [comment]
Another example with another video player.

```
youtube-dl -v http://nationalpost.com/news/world/is-vladimir-putin-a-judo-fraud-an-investigation/wcm/0497e342-d746-47aa-9c08-385c076db18b
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'http://nationalpost.com/news/world/is-vladimir-putin-a-judo-fraud-an-investigation/wcm/0497e342-d746-47aa-9c08-385c076db18b']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.07.15
[debug] Python version 2.7.12 - Linux-4.4.0-72-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1
[debug] Proxy map: {}
[generic] 0497e342-d746-47aa-9c08-385c076db18b: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 0497e342-d746-47aa-9c08-385c076db18b: Downloading webpage
[generic] 0497e342-d746-47aa-9c08-385c076db18b: Extracting information
ERROR: Unsupported URL: http://nationalpost.com/news/world/is-vladimir-putin-a-judo-fraud-an-investigation/wcm/0497e342-d746-47aa-9c08-385c076db18b
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2060, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2539, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2528, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 56, column 343
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 776, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2915, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://nationalpost.com/news/world/is-vladimir-putin-a-judo-fraud-an-investigation/wcm/0497e342-d746-47aa-9c08-385c076db18b
```

**Comment by jnbdz** [comment]
I tried it again today with: youtube-dl https://nationalpost.com/news/ontario-election/ontario-liberals-promise-1-transit-fares-across-the-province-would-cost-1-1b

> [generic] ontario-liberals-promise-1-transit-fares-across-the-province-would-cost-1-1b: Requesting header
> WARNING: Falling back on generic information extractor.
> [generic] ontario-liberals-promise-1-transit-fares-across-the-province-would-cost-1-1b: Downloading webpage
> [generic] ontario-liberals-promise-1-transit-fares-across-the-province-would-cost-1-1b: Extracting information
> ERROR: Unsupported URL: https://nationalpost.com/news/ontario-election/ontario-liberals-promise-1-transit-fares-across-the-province-would-cost-1-1b

Version: 2021.12.17
