### ISSUE TITLE
[ETB] Mediateca not working

### ISSUE THREAD

**Issue by a-l-e-k** [rg3/youtube-dl#13374]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.06.12**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Bug report (encountered problems with youtube-dl)

- Single video: http://www.eitb.eus/eu/kirolak/txirrindularitza/bideoak/osoa/4895232/bideoa-rohan-dennisek-irabazi-du-suitzako-tourreko-lehenengo-etapa/

**description**
URLs of the type eitb.eus/eu/ are not working.
URLs of the type eitb.tv/es/video/ from the same site are working fine.

**log**
```
youtube-dl.exe -v http://www.eitb.eus/eu/kirolak/txirrindularitza/bideoak/osoa/4895232/bideoa-rohan-dennisek-irabazi-du-suitzako-tourreko-lehenengo-etapa/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://www.eitb.eus/eu/kirolak/txirrindularitza/bideoak/osoa/4895232/bideoa-rohan-dennisek-irabazi-du-suitzako-tourreko-lehenengo-etapa/']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.06.12
[debug] Python version 3.4.4
[debug] exe versions: ffmpeg N-67100-g6dc99fd, ffprobe N-67100-g6dc99fd, rtmpdump 2.4
[debug] Proxy map: {}
[generic] bideoa-rohan-dennisek-irabazi-du-suitzako-tourreko-lehenengo-etapa: Requesting header
WARNING: Falling back on generic information extractor.
[generic] bideoa-rohan-dennisek-irabazi-du-suitzako-tourreko-lehenengo-etapa: Downloading webpage
[generic] bideoa-rohan-dennisek-irabazi-du-suitzako-tourreko-lehenengo-etapa: Extracting information
ERROR: Unsupported URL: http://www.eitb.eus/eu/kirolak/txirrindularitza/bideoak/osoa/4895232/bideoa-rohan-dennisek-irabazi-du-suitzako-tourreko-lehenengo-etapa/
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkyaecyzu\build\youtube_dl\YoutubeDL.py", line 762, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkyaecyzu\build\youtube_dl\extractor\common.py", line 433, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkyaecyzu\build\youtube_dl\extractor\generic.py", line 2796, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.eitb.eus/eu/kirolak/txirrindularitza/bideoak/osoa/4895232/bideoa-rohan-dennisek-irabazi-du-suitzako-tourreko-lehenengo-etapa/
<end of log>
```

**Comment by theStupidProwler** [comment]
In the https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/eitb.py , the _VALID_URL need an .tv url, you just need to add the .eus to this file and commit ;)

**Comment by theStupidProwler** [comment]
it use the generic.py extractor because, the https://github.com/rg3/youtube-dl/edit/master/youtube_dl/extractor/eitb.py , don't consider your url as valid

**Comment by theStupidProwler** [comment]
https://github.com/rg3/youtube-dl/pull/13389
