### ISSUE TITLE
Unable to extract title

### ISSUE THREAD

**Issue by balibell** [rg3/youtube-dl#13387]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.06.12**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)

---

### We got "Unable to extract title" error:

```
$ youtube-dl "http://www.bilibili.com/video/av8903802/" -o /tmp/bilibili_8903802.mp4 --referer "http://www.bilibili.com/1497440965527"
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
➜  scram git:(master) ✗ ./spidernet/bin/youtube-dl -v "http://www.bilibili.com/video/av8903802/" -o /tmp/bilibili_8903802.mp4 --referer "http://www.bilibili.com/1497440965527"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'http://www.bilibili.com/video/av8903802/', u'-o', u'/tmp/bilibili_8903802.mp4', u'--referer', u'http://www.bilibili.com/1497440965527']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.06.12
[debug] Git HEAD: 3043505
[debug] Python version 2.7.10 - Darwin-16.4.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[BiliBili] 8903802: Downloading webpage
[BiliBili] 8903802: Downloading video info page
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/Users/balibell/GitHub/scram/spidernet/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 762, in extract_info
    ie_result = ie.extract(url)
  File "/Users/balibell/GitHub/scram/spidernet/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "/Users/balibell/GitHub/scram/spidernet/lib/python2.7/site-packages/youtube_dl/extractor/bilibili.py", line 138, in _real_extract
    title = self._html_search_regex('<h1[^>]+title="([^"]+)">', webpage, 'title')
  File "/Users/balibell/GitHub/scram/spidernet/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 791, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/Users/balibell/GitHub/scram/spidernet/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 782, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

---

**Comment by yan12125** [comment]
Thanks for the report. Such videos will be fixed in the next version.
