### ISSUE TITLE
Extractor Error when attempting to download Vevo Playlist

### ISSUE THREAD

**Issue by thomco** [rg3/youtube-dl#13394]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.06.12*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.06.12**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl --ignore-config http://www.vevo.com/watch/playlist/d1aa61ff-1f40-466f-b527-8277de057768


[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--ignore-config', '-v', 'http://www.vevo.com/watch/playlist/d1aa61ff-1f40-466f-b527-8277de057768']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2017.06.12
[debug] Python version 3.6.1 - Windows-10-10.0.15063-SP0
[debug] exe versions: ffmpeg N-83454-g3aae1ef, ffprobe N-83454-g3aae1ef
[debug] Proxy map: {}
[VevoPlaylist] d1aa61ff-1f40-466f-b527-8277de057768: Downloading webpage
ERROR: An extractor error has occurred. (caused by KeyError('playlists',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\users\thomas\miniconda3\envs\ytdl\lib\site-packages\youtube_dl\extractor\common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "c:\users\thomas\miniconda3\envs\ytdl\lib\site-packages\youtube_dl\extractor\vevo.py", line 359, in _real_extract
    playlists = self._extract_json(webpage, playlist_id)['default']['%ss' % playlist_kind]
KeyError: 'playlists'
Traceback (most recent call last):
  File "c:\users\thomas\miniconda3\envs\ytdl\lib\site-packages\youtube_dl\extractor\common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "c:\users\thomas\miniconda3\envs\ytdl\lib\site-packages\youtube_dl\extractor\vevo.py", line 359, in _real_extract
    playlists = self._extract_json(webpage, playlist_id)['default']['%ss' % playlist_kind]
KeyError: 'playlists'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\thomas\miniconda3\envs\ytdl\lib\site-packages\youtube_dl\YoutubeDL.py", line 762, in extract_info
    ie_result = ie.extract(url)
  File "c:\users\thomas\miniconda3\envs\ytdl\lib\site-packages\youtube_dl\extractor\common.py", line 446, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('playlists',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by thomco** [comment]
I notice @dstftw added the 'geo-restricted' label

If it matters, I am accessing this URL from a US ip address.  The videos and playlist are all available for playback in the browser from this address.   Thanks
