### ISSUE TITLE
ERROR: unable to download video data: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by star001007** [rg3/youtube-dl#13391]
```
root@beta-api:~# youtube-dl https://www.youtube.com/watch?v=Bob9Hueb1uY -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.youtube.com/watch?v=Bob9Hueb1uY', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.06.12
[debug] Python version 2.7.6 - Linux-3.13.0-116-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] Bob9Hueb1uY: Downloading webpage
[youtube] Bob9Hueb1uY: Downloading video info webpage
[youtube] Bob9Hueb1uY: Extracting video information
[youtube] Bob9Hueb1uY: Downloading MPD manifest
[debug] Invoking downloader on u'https://r2---sn-i3beln76.googlevideo.com/videoplayback?ei=bXJCWcbED8S94gL88LeYAQ&requiressl=yes&ratebypass=yes&ipbits=0&ip=103.218.243.95&expire=1497548493&mime=video%2Fmp4&mm=31&source=youtube&key=yt6&itag=22&ms=au&mt=1497526513&mv=u&id=o-AFRMG33yATsC7rSivsKXYQy0c8DcNYzgL4y8WzN4VcNC&dur=601.930&mn=sn-i3beln76&lmt=1481784077045135&sparams=dur%2Cei%2Cid%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&pl=24&signature=B01A392990607B5F6E0545B4BCAA38FF06A5A10D.BD0C5924A751EED01DD450C1A898F3BA6FDF0EC4'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1826, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1768, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 360, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 61, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2129, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden
```

hope someone can help me. it's okey until yesterday.

**Comment by yan12125** [comment]
The link generated on your side https://r4---sn-vgqs7nez.googlevideo.com/videoplayback?ei=bXJCWcbED8S94gL88LeYAQ&requiressl=yes&ratebypass=yes&ipbits=0&ip=103.218.243.95&expire=1497548493&mime=video%2Fmp4&source=youtube&key=cms1&itag=22&id=o-AFRMG33yATsC7rSivsKXYQy0c8DcNYzgL4y8WzN4VcNC&dur=601.930&lmt=1481784077045135&sparams=dur,ei,expire,id,ip,ipbits,ipbypass,itag,lmt,mime,mip,mm,mn,ms,mv,pl,ratebypass,requiressl,source&pl=21&signature=77B3E5954E65E2922C17316B36142BB2C75385D5.7B6F73C9AF7DE4E12FEB08BA2D1147E83BF0CBD5&req_id=89c8c8004154a3ee&ipbypass=yes&mip=140.112.28.103&cm2rm=sn-u5oxu-un5e7e,sn-un5e7l&redirect_counter=3&cms_redirect=yes&mm=34&mn=sn-vgqs7nez&ms=ltu&mt=1497533193&mv=m works fine even on my machine. Maybe your ISP or China's Great Firewall (GFW) blocks connections to YouTube? Could you view the link above in browsers? If not could you ping r2---sn-i3beln76.googlevideo.com?

**Comment by star001007** [comment]
@yan12125 ，great thanks. my local machine works fine, but not for my webserver.  the webserver uses proxy service, maybe i need to check it. 
```
root@beta-api:~# ping r5---sn-i3beln76.googlevideo.com
PING r5.sn-i3beln76.googlevideo.com (173.194.59.75) 56(84) bytes of data.
64 bytes from 173.194.59.75: icmp_seq=1 ttl=56 time=238 ms
64 bytes from 173.194.59.75: icmp_seq=2 ttl=56 time=2.16 ms
64 bytes from 173.194.59.75: icmp_seq=3 ttl=56 time=95.4 ms
64 bytes from 173.194.59.75: icmp_seq=4 ttl=56 time=2.15 ms
64 bytes from 173.194.59.75: icmp_seq=5 ttl=56 time=91.2 ms
```

**Comment by DonRichards** [comment]
Not the same URL for me and I'm getting a JSON response with the following error. 
 https://github-production-release-asset-2e65be.s3.amazonaws.com/1039520/495761be-4f16-11e7-8c38-4efeffc58f2e?X-A

```json
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>5739A87C541EBA98</RequestId>
<HostId>
QLJwGy9CYZx+H1DJ87Y4qRGDgPtEog8o4Van/34lFUAGyIH8vVsBoVKxQ+x+iDgAabSovCdWzQU=
</HostId>
</Error>
```

**Comment by yan12125** [comment]
173.194.59.75 is a valid Google IP. I guess your server is blocked by YouTube, so I'm closing this here. If you have any new findings, (for example using the webserver as a proxy and YouTube works) feel free to leave comments here or to #13388.

**Comment by star001007** [comment]
@yan12125 ,okey, great thanks.
