### ISSUE TITLE
Site Support Request for IL-TV

### ISSUE THREAD

**Issue by Jiriss** [rg3/youtube-dl#13421]
I would like support for IL-TV videos into Finnish news site: www.iltalehti.fi

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.06.18*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.06.18**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [X] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other
---
### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v http://www.iltalehti.fi/viihdeuutiset/201706182200215720_vd.shtml

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'http://www.iltalehti.fi/viihdeuutiset/201706182200215720_vd.shtml']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.06.18
[debug] Python version 2.7.6 - Linux-3.13.0-119-generic-x86_64
[debug] exe versions: avconv 9.20-6, avprobe 9.20-6, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 201706182200215720_vd: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 201706182200215720_vd: Downloading webpage
[generic] 201706182200215720_vd: Extracting information
ERROR: Unsupported URL: http://www.iltalehti.fi/viihdeuutiset/201706182200215720_vd.shtml
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1971, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2539, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2528, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: syntax error: line 1, column 0
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 762, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2796, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.iltalehti.fi/viihdeuutiset/201706182200215720_vd.shtml
--
### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Some videos has been embedded with the news into www.iltalehti.fi
but their also have own sub-page for videos: http://www.iltalehti.fi/iltv/

The videos aren't geo-restricted. This are a few examples for videos:

http://www.iltalehti.fi/viihdeuutiset/201706182200215720_vd.shtml
http://www.iltalehti.fi/iltvuutiset/201706170203148_v0.shtml
http://www.iltalehti.fi/iltv-paivarinta/201706140190928_iv.shtml

**Comment by Jiriss** [comment]
I'd like if the developers of the youtube-dl could say something about the status of this request

**Comment by joonas-foo** [comment]
It still doesn't work, try out https://www.iltalehti.fi/iltv . It would be nice if you supported it! And thanks for the excellent tool!
