### ISSUE TITLE
[globalnews] Site support

### ISSUE THREAD

**Issue by jnbdz** [rg3/youtube-dl#13430]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.06.18*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.06.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v http://globalnews.ca/video/2066998/focus-montreal-doulia-hamad-and-nebras-m-warsi
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'http://globalnews.ca/video/2066998/focus-montreal-doulia-hamad-and-nebras-m-warsi']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.06.18
[debug] Python version 2.7.12 - Linux-4.4.0-72-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1
[debug] Proxy map: {}
[generic] focus-montreal-doulia-hamad-and-nebras-m-warsi: Requesting header
WARNING: Falling back on generic information extractor.
[generic] focus-montreal-doulia-hamad-and-nebras-m-warsi: Downloading webpage
[generic] focus-montreal-doulia-hamad-and-nebras-m-warsi: Extracting information
ERROR: Unsupported URL: http://globalnews.ca/video/2066998/focus-montreal-doulia-hamad-and-nebras-m-warsi
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1971, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2539, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2528, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 34, column 148
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 762, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2796, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://globalnews.ca/video/2066998/focus-montreal-doulia-hamad-and-nebras-m-warsi

...
<end of log>
```

---

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Just site support.

**Comment by super017** [comment]
Hello,I want to ask if I want to change the audio and video download parameters, such as plus or minus a parameter, where is the change

**Comment by super017** [comment]
I mean, I've  changed data storage paths to stored in the database。I want to add a field on the basis of the existing storage field .From now on,there are this field and its value in the database when the code run.

**Comment by gfabiano** [comment]
@super017 ok, but I don't understand why you ask it on this issue.

**Comment by makeworld-the-better-one** [comment]
```
❯ youtube-dl -Fv https://globalnews.ca/video/5327391/16-year-old-senior-barber-hones-craft-at-toronto-shop
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-Fv', 'https://globalnews.ca/video/5327391/16-year-old-senior-barber-hones-craft-at-toronto-shop']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.05.20
[debug] Python version 3.7.3 (CPython) - Linux-5.1.5-arch1-2-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 16-year-old-senior-barber-hones-craft-at-toronto-shop: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 16-year-old-senior-barber-hones-craft-at-toronto-shop: Downloading webpage
[generic] 16-year-old-senior-barber-hones-craft-at-toronto-shop: Extracting information
[download] Downloading playlist: None
[generic] playlist None: Collected 11 video ids (downloading 11 of them)
[download] Downloading video 1 of 11
[info] Available formats for ONLINE TEEN BARBER (WESTOLL) 2:
format code  extension  resolution note
0            mp4        unknown    
[download] Downloading video 2 of 11
[info] Available formats for Global Peterborough Business Beat May 27:
format code  extension  resolution note
0            mp4        unknown    
[download] Downloading video 3 of 11
[info] Available formats for GK280519_owls:
format code  extension  resolution note
0            mp4        unknown    
[download] Downloading video 4 of 11
[info] Available formats for WEB     LINDA    OWL:
format code  extension  resolution note
0            mp4        unknown    
[download] Downloading video 5 of 11
[info] Available formats for RAPTOR TATTOOS (SHALLIM_TOR1EHHH:
format code  extension  resolution note
0            mp4        unknown    
[download] Downloading video 6 of 11
[info] Available formats for online EMPLOYEE PRAISED (CARYN) MAY 6:
format code  extension  resolution note
0            mp4        unknown    
[download] Downloading video 7 of 11
[info] Available formats for 20 year old pot shop owner:
format code  extension  resolution note
0            mp4        unknown    
[download] Downloading video 8 of 11
[info] Available formats for Junior Acheivement Business Halk of Fame Ceremony in Peterborough:
format code  extension  resolution note
0            mp4        unknown    
[download] Downloading video 9 of 11
[info] Available formats for CUSHNIE_PLEAD_OUT-SOT_EDMGFCD8:
format code  extension  resolution note
0            mp4        unknown    
[download] Downloading video 10 of 11
[info] Available formats for raptorsfansontruck260519:
format code  extension  resolution note
0            mp4        unknown    
[download] Downloading video 11 of 11
[info] Available formats for trafficsnarlsraptors260519:
format code  extension  resolution note
0            mp4        unknown    
[download] Finished downloading playlist: None
```

Is this still active? Will there be support for this site in the future possibly?
