### ISSUE TITLE
Making a search without downloading anything

### ISSUE THREAD

**Issue by mertyildiran** [rg3/youtube-dl#13436]
Hi, I know it's possible to make a search with this command: `youtube-dl "ytsearch:dank memes compilation"`

I would like to be able to just make a search and get the URLs and Titles but not download anything.

My goal is using youtube-dl as a library or a tool in my project [Dragonfire](https://github.com/mertyildiran/Dragonfire). I know youtube-dl is not a search tool but a **downloader**. But youtube-dl is maybe the only tool that guarantee to be always up to date with YouTube. So youtube-dl is **the best option** for such a task even if it's not the main purpose.

When I looked up to the source code, I found [this function](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/youtube.py#L2480) which is handling the request. So I have imported that part and tried to use it:

```python
>>> from youtube_dl.extractor.youtube import YoutubeSearchIE
>>> a = YoutubeSearchIE()
>>> a._get_n_results('PewDiePie',1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 2497, in _get_n_results
    query={'spf': 'navigate'})
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 666, in _download_json
    encoding=encoding, data=data, headers=headers, query=query)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 634, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 531, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 492, in _request_webpage
    self.to_screen('%s: %s' % (video_id, note))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 691, in to_screen
    self._downloader.to_screen('[%s] %s' % (self.IE_NAME, msg))
AttributeError: 'NoneType' object has no attribute 'to_screen'
```

I got an error probably because it's not suppose to be used as the way I tried to use. So if it's not possible to use youtube-dl in such a way then this issue is a feature request :smile:

*<sup>P.S. if the developers guide me then maybe I can implement this feature by myself and send a pull request...</sup>*

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#embedding-youtube-dl
```
info = ydl.extract_info('ytsearch:dank memes compilation', download=False, ie_key='YoutubeSearch')
// process info
```

**Comment by mertyildiran** [comment]
@dstftw thank you so much, these options solved my problem:

```python
>>> from __future__ import unicode_literals
>>> import youtube_dl
>>>
>>> ydl_opts = {'default_search': 'ytsearch', 'forcetitle': True, 'skip_download': True}
>>> with youtube_dl.YoutubeDL(ydl_opts) as ydl:
...     ydl.download(['PewDiePie'])
... 
[youtube:search] query "PewDiePie": Downloading page 1
[download] Downloading playlist: PewDiePie
[youtube:search] playlist PewDiePie: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[youtube] u57obOmxrts: Downloading webpage
[youtube] u57obOmxrts: Downloading video info webpage
[youtube] u57obOmxrts: Extracting video information
[youtube] u57obOmxrts: Downloading MPD manifest
Tired of trying...
[download] Finished downloading playlist: PewDiePie
0
```
