### ISSUE TITLE
Generic/Ooyala fails: ValueError: unknown url type: ''"

### ISSUE THREAD

**Issue by RingoTheDog** [rg3/youtube-dl#13444]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.06.18*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.06.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
youtube-dl.py -v "https://www.torontofc.ca/post/2017/06/19/i-always-think-rivalries-grow-whenever-importance-game-grows-greg-vanney"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.torontofc.ca/post/2017/06/19/i-always-think-rivalries-grow-whenever-importance-game-grows-greg-vanney']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.06.18
[debug] Python version 3.5.1 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-71727-g46778ab, ffprobe 3.2, rtmpdump 2.4
[debug] Proxy map: {}
[generic] i-always-think-rivalries-grow-whenever-importance-game-grows-greg-vanney: Requesting header
WARNING: Falling back on generic information extractor.
[generic] i-always-think-rivalries-grow-whenever-importance-game-grows-greg-vanney: Downloading webpage
[generic] i-always-think-rivalries-grow-whenever-importance-game-grows-greg-vanney: Extracting information
[Ooyala] hiMGxtYjE6R9kOPKX5ZAxrtSGIQSqAbm: Downloading JSON metadata
[Ooyala] hiMGxtYjE6R9kOPKX5ZAxrtSGIQSqAbm: Downloading JSON metadata
[Ooyala] hiMGxtYjE6R9kOPKX5ZAxrtSGIQSqAbm: Downloading f4m manifest
[Ooyala] hiMGxtYjE6R9kOPKX5ZAxrtSGIQSqAbm: Downloading m3u8 information
Traceback (most recent call last):
  File "C:\Program Files\Python35\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\Python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Transmogrifier\youtube-dl.py\__main__.py", line 19, in <module>
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\__init__.py", line 465, in main
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\__init__.py", line 455, in _real_main
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 1919, in download
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 773, in extract_info
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 834, in process_ie_result
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 773, in extract_info
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 827, in process_ie_result
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 1496, in process_video_result
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 1325, in _calc_headers
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 1337, in _calc_cookies
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\utils.py", line 545, in sanitized_Request
  File "C:\Program Files\Python35\lib\urllib\request.py", line 268, in __init__
    self.full_url = url
  File "C:\Program Files\Python35\lib\urllib\request.py", line 294, in full_url
    self._parse()
  File "C:\Program Files\Python35\lib\urllib\request.py", line 323, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: ''
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.torontofc.ca/post/2017/06/19/i-always-think-rivalries-grow-whenever-importance-game-grows-greg-vanney

---

The direct link to the Ooyala video DOES work correctly (uses generic extractor):
https://secure-cf-c.ooyala.com/hiMGxtYjE6R9kOPKX5ZAxrtSGIQSqAbm/DOcJ-FxaFrRg4gtDEwOnVhOjBrO_9PjD?_=xtbyfu

...however the link from the Toronto FC website errors...so I am not really sure if this is a site request or a bug report (?)

Thanks
Ringo

**Comment by RingoTheDog** [comment]
Totally different site...but the exact same result.
This time with PGATOUR.COM...I'm pretty certain the PGA videos used to work automagically


URL: http://www.pgatour.com/video/2017/06/23/marc-leishman-s-105-yard-birdie-is-the-shot-of-the-day.html




```
youtube-dl.py -v "http://www.pgatour.com/video/2017/06/23/marc-leishman-s-105-yard-birdie-is-the-shot-of-the-day.html"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://www.pgatour.com/video/2017/06/23/marc-leishman-s-105-yard-birdie-is-the-shot-of-the-day.html']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.06.23
[debug] Python version 3.5.1 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-71727-g46778ab, ffprobe 3.2, rtmpdump 2.4
[debug] Proxy map: {}
[generic] marc-leishman-s-105-yard-birdie-is-the-shot-of-the-day: Requesting header
WARNING: Falling back on generic information extractor.
[generic] marc-leishman-s-105-yard-birdie-is-the-shot-of-the-day: Downloading webpage
[generic] marc-leishman-s-105-yard-birdie-is-the-shot-of-the-day: Extracting information
[Ooyala] 5nYnZvYjE63g5zFEjMTUN62GtlYz1XGD: Downloading JSON metadata
[Ooyala] 5nYnZvYjE63g5zFEjMTUN62GtlYz1XGD: Downloading JSON metadata
[Ooyala] 5nYnZvYjE63g5zFEjMTUN62GtlYz1XGD: Downloading m3u8 information
Traceback (most recent call last):
  File "C:\Program Files\Python35\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\Python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Transmogrifier\youtube-dl.py\__main__.py", line 19, in <module>
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\__init__.py", line 465, in main
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\__init__.py", line 455, in _real_main
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 1919, in download
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 773, in extract_info
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 834, in process_ie_result
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 773, in extract_info
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 827, in process_ie_result
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 1496, in process_video_result
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 1325, in _calc_headers
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 1337, in _calc_cookies
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\utils.py", line 545, in sanitized_Request
  File "C:\Program Files\Python35\lib\urllib\request.py", line 268, in __init__
    self.full_url = url
  File "C:\Program Files\Python35\lib\urllib\request.py", line 294, in full_url
    self._parse()
  File "C:\Program Files\Python35\lib\urllib\request.py", line 323, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: ''
```

**Comment by Argn0** [comment]
This was fixed. You need to download the latest version.

**Comment by yan12125** [comment]
Thanks @Argn0. That's indeed already fixed.
