### ISSUE TITLE
[YouTube Red] ERROR: giving up after 10 retries

### ISSUE THREAD

**Issue by RuneMagle** [rg3/youtube-dl#13478]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.06.23**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
```
C:\Users\Desktop\youtube-dl>youtube-dl.exe -f 266 https://www.youtube.com/watch?v=bS2vhgnFddU -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', '266', 'https://www.youtube.com/watch?v=bS2vhgnFddU', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.06.23
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-82833-gedb4f5d, ffprobe N-82833-gedb4f5d, rtmpdump 2.3
[debug] Proxy map: {}
[youtube] bS2vhgnFddU: Downloading webpage
[youtube] bS2vhgnFddU: Downloading video info webpage
[youtube] bS2vhgnFddU: Extracting video information
[youtube] {22} signature length 40.42, html5 player vfl1Renoe
[youtube] {43} signature length 40.42, html5 player vfl1Renoe
[youtube] {18} signature length 40.42, html5 player vfl1Renoe
[youtube] {36} signature length 40.42, html5 player vfl1Renoe
[youtube] {17} signature length 40.42, html5 player vfl1Renoe
[youtube] {313} signature length 40.42, html5 player vfl1Renoe
[youtube] {264} signature length 40.42, html5 player vfl1Renoe
[youtube] {271} signature length 40.42, html5 player vfl1Renoe
[youtube] {137} signature length 40.42, html5 player vfl1Renoe
[youtube] {248} signature length 40.42, html5 player vfl1Renoe
[youtube] {136} signature length 40.42, html5 player vfl1Renoe
[youtube] {247} signature length 40.42, html5 player vfl1Renoe
[youtube] {135} signature length 40.42, html5 player vfl1Renoe
[youtube] {244} signature length 40.42, html5 player vfl1Renoe
[youtube] {134} signature length 40.42, html5 player vfl1Renoe
[youtube] {243} signature length 40.42, html5 player vfl1Renoe
[youtube] {133} signature length 40.42, html5 player vfl1Renoe
[youtube] {242} signature length 40.42, html5 player vfl1Renoe
[youtube] {160} signature length 40.42, html5 player vfl1Renoe
[youtube] {278} signature length 40.42, html5 player vfl1Renoe
[youtube] {140} signature length 40.42, html5 player vfl1Renoe
[youtube] {171} signature length 40.42, html5 player vfl1Renoe
[youtube] {249} signature length 40.42, html5 player vfl1Renoe
[youtube] {250} signature length 40.42, html5 player vfl1Renoe
[youtube] {251} signature length 40.42, html5 player vfl1Renoe
[youtube] {256} signature length 40.42, html5 player vfl1Renoe
[youtube] {258} signature length 40.42, html5 player vfl1Renoe
[youtube] bS2vhgnFddU: Downloading MPD manifest
[debug] Invoking downloader on 'https://r3---sn-4pcp5q3-j2ie.googlevideo.com/videoplayback?id=6d2daf8609c575d5&itag=266&source=youtube&requiressl=yes&initcwndbps=3563750&mm=31&gcr=dk&pl=20&ms=au&ei=Cw9NWdfPK9O81gK566X4Dw&mv=m&mn=sn-4pcp5q3-j2ie&ratebypass=yes&mime=video/mp4&gir=yes&clen=3598186235&lmt=1466864306659746&dur=1395.226&beids=[9466591]&key=dg_yt0&mt=1498222271&signature=0C5DFFA881B50DEED120AC1D28D5911B11E6574C.4D49BD5148EDAFD8B4586EEC312A6836E2BD0DF3&ip=5.186.125.191&ipbits=0&expire=1498243947&sparams=ip,ipbits,expire,id,itag,source,requiressl,initcwndbps,mm,gcr,pl,ms,ei,mv,mn,ratebypass,mime,gir,clen,lmt,dur'
[download] Resuming download at byte 4194272
[download] Got server HTTP error. Retrying (attempt 1 of 10)...
[download] Got server HTTP error. Retrying (attempt 2 of 10)...
[download] Got server HTTP error. Retrying (attempt 3 of 10)...
[download] Got server HTTP error. Retrying (attempt 4 of 10)...
[download] Got server HTTP error. Retrying (attempt 5 of 10)...
[download] Got server HTTP error. Retrying (attempt 6 of 10)...
[download] Got server HTTP error. Retrying (attempt 7 of 10)...
[download] Got server HTTP error. Retrying (attempt 8 of 10)...
[download] Got server HTTP error. Retrying (attempt 9 of 10)...
[download] Got server HTTP error. Retrying (attempt 10 of 10)...
ERROR: giving up after 10 retries
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpsrujt7wq\build\youtube_dl\__init__.py", line 465, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpsrujt7wq\build\youtube_dl\__init__.py", line 455, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpsrujt7wq\build\youtube_dl\YoutubeDL.py", line 1919, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpsrujt7wq\build\youtube_dl\YoutubeDL.py", line 773, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpsrujt7wq\build\youtube_dl\YoutubeDL.py", line 827, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpsrujt7wq\build\youtube_dl\YoutubeDL.py", line 1562, in process_video_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpsrujt7wq\build\youtube_dl\YoutubeDL.py", line 1826, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpsrujt7wq\build\youtube_dl\YoutubeDL.py", line 1768, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpsrujt7wq\build\youtube_dl\downloader\common.py", line 361, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpsrujt7wq\build\youtube_dl\downloader\http.py", line 131, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpsrujt7wq\build\youtube_dl\downloader\common.py", line 163, in report_error
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpsrujt7wq\build\youtube_dl\YoutubeDL.py", line 602, in report_error
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpsrujt7wq\build\youtube_dl\YoutubeDL.py", line 564, in trouble
...
<end of log>
```

---
- Single video: https://www.youtube.com/watch?v=bS2vhgnFddU
- Single video: https://www.youtube.com/watch?v=jtT6QuMKWXc
- Playlist: https://www.youtube.com/playlist?list=PLRfpyIF9ZtKKInt1xZ_Ns5Btar4OZzIEP

---

### Description of *issue*

It doesn't won't to download. Even when trying `--force-generic`, it says format not available, when it clearly is.

**Comment by RuneMagle** [comment]
Second command:
```
C:\Users\rumag\Desktop\youtube-dl>youtube-dl.exe -f 266 https://www.youtube.com/watch?v=bS2vhgnFddU -v --geo-bypass
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', '266', 'https://www.youtube.com/watch?v=bS2vhgnFddU', '-v', '--geo-bypass']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.06.23
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-82833-gedb4f5d, ffprobe N-82833-gedb4f5d, rtmpdump 2.3
[debug] Proxy map: {}
[youtube] bS2vhgnFddU: Downloading webpage
[youtube] bS2vhgnFddU: Downloading video info webpage
[youtube] bS2vhgnFddU: Extracting video information
[youtube] {22} signature length 40.42, html5 player vfl1Renoe
[youtube] {43} signature length 40.42, html5 player vfl1Renoe
[youtube] {18} signature length 40.42, html5 player vfl1Renoe
[youtube] {36} signature length 40.42, html5 player vfl1Renoe
[youtube] {17} signature length 40.42, html5 player vfl1Renoe
[youtube] {313} signature length 40.42, html5 player vfl1Renoe
[youtube] {264} signature length 40.42, html5 player vfl1Renoe
[youtube] {271} signature length 40.42, html5 player vfl1Renoe
[youtube] {137} signature length 40.42, html5 player vfl1Renoe
[youtube] {248} signature length 40.42, html5 player vfl1Renoe
[youtube] {136} signature length 40.42, html5 player vfl1Renoe
[youtube] {247} signature length 40.42, html5 player vfl1Renoe
[youtube] {135} signature length 40.42, html5 player vfl1Renoe
[youtube] {244} signature length 40.42, html5 player vfl1Renoe
[youtube] {134} signature length 40.42, html5 player vfl1Renoe
[youtube] {243} signature length 40.42, html5 player vfl1Renoe
[youtube] {133} signature length 40.42, html5 player vfl1Renoe
[youtube] {242} signature length 40.42, html5 player vfl1Renoe
[youtube] {160} signature length 40.42, html5 player vfl1Renoe
[youtube] {278} signature length 40.42, html5 player vfl1Renoe
[youtube] {140} signature length 40.42, html5 player vfl1Renoe
[youtube] {171} signature length 40.42, html5 player vfl1Renoe
[youtube] {249} signature length 40.42, html5 player vfl1Renoe
[youtube] {250} signature length 40.42, html5 player vfl1Renoe
[youtube] {251} signature length 40.42, html5 player vfl1Renoe
[youtube] {256} signature length 40.42, html5 player vfl1Renoe
[youtube] {258} signature length 40.42, html5 player vfl1Renoe
[youtube] bS2vhgnFddU: Downloading MPD manifest
[debug] Invoking downloader on 'https://r3---sn-4pcp5q3-j2ie.googlevideo.com/videoplayback?id=6d2daf8609c575d5&itag=266&source=youtube&requiressl=yes&ei=GRBNWavzMNDn1gK0tKrQBA&initcwndbps=3546250&gcr=dk&mm=31&pl=20&mn=sn-4pcp5q3-j2ie&ms=au&mv=m&ratebypass=yes&mime=video/mp4&gir=yes&clen=3598186235&lmt=1466864306659746&dur=1395.226&key=dg_yt0&signature=11A5E8E216C32C4DAF258E75FDD79B52AC40A213.437E37B20B3A1C408B97EB9E7719327A7F7F70E7&mt=1498222504&ip=5.186.125.191&ipbits=0&expire=1498244217&sparams=ip,ipbits,expire,id,itag,source,requiressl,ei,initcwndbps,gcr,mm,pl,mn,ms,mv,ratebypass,mime,gir,clen,lmt,dur'
[download] Resuming download at byte 4194272
[download] Destination: An Invitation - Escape the Night-bS2vhgnFddU.mp4
[download]   0.3% of 3.35GiB at  9.11MiB/s ETA 06:15    ERROR: content too short (expected 3598186235 bytes and served 10485680)
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpsrujt7wq\build\youtube_dl\YoutubeDL.py", line 1826, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpsrujt7wq\build\youtube_dl\YoutubeDL.py", line 1768, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpsrujt7wq\build\youtube_dl\downloader\common.py", line 361, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpsrujt7wq\build\youtube_dl\downloader\http.py", line 238, in real_download
youtube_dl.utils.ContentTooShortError: Downloaded 10485680 bytes, expected 3598186235 bytes
```
