### ISSUE TITLE
RegexNotFoundError: Unable to extract title

### ISSUE THREAD

**Issue by nemophobia** [rg3/youtube-dl#13477]
t=PLD40592D2BABB04D5uality FORMAT --verbose https://www.youtube.com/playlist?lis 
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-citk', '--max-quality', 'FORMAT', '--verbose', 'https://www.youtube.com/playlist?list=PLD40592D2BABB04D5']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.08.05
[debug] Python version 2.7.9 - Linux-4.4.50-v7+-armv7l-with-debian-8.0
[debug] Proxy map: {}
[youtube:playlist] PLD40592D2BABB04D5: Downloading webpage
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 516, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 170, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 1050, in _real_extract
    page, u'title')
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 401, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 391, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by dstftw** [comment]
Outdated version.
