### ISSUE TITLE
Add support for skypixel

### ISSUE THREAD

**Issue by rollopack** [rg3/youtube-dl#13495]
- [X ] I've **verified** and **I assure** that I'm running youtube-dl **2017.06.25**

- [ X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [X ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other
---
youtube-dl https://www.skypixel.com/share/video/check-out-my-latest-artwork-4f90b8ac-e7c3-4ed8-82c2-203addfd629e -v                                      2 ↵
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.skypixel.com/share/video/check-out-my-latest-artwork-4f90b8ac-e7c3-4ed8-82c2-203addfd629e', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.06.25
[debug] Python version 2.7.13 - Linux-4.9.0-3-amd64-x86_64-with-debian-9.0
[debug] exe versions: ffmpeg 3.2.5-1, ffprobe 3.2.5-1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] check-out-my-latest-artwork-4f90b8ac-e7c3-4ed8-82c2-203addfd629e: Requesting header
WARNING: Falling back on generic information extractor.
[generic] check-out-my-latest-artwork-4f90b8ac-e7c3-4ed8-82c2-203addfd629e: Downloading webpage
[generic] check-out-my-latest-artwork-4f90b8ac-e7c3-4ed8-82c2-203addfd629e: Extracting information
ERROR: Unsupported URL: https://www.skypixel.com/share/video/check-out-my-latest-artwork-4f90b8ac-e7c3-4ed8-82c2-203addfd629e
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1971, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/bin/youtube-dl/youtube_dl/compat.py", line 2539, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/bin/youtube-dl/youtube_dl/compat.py", line 2528, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 2, column 12517
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 762, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2796, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.skypixel.com/share/video/check-out-my-latest-artwork-4f90b8ac-e7c3-4ed8-82c2-203addfd629e
<end of log>
```

- Single video: https://www.skypixel.com/share/video/check-out-my-latest-artwork-4f90b8ac-e7c3-4ed8-82c2-203addfd629e

Please add support for skypixel.com

**Comment by Loknar** [comment]
hi @rollopack 

I saw your issue/feature request and took a look at how hard it would be to implement, turned out to be rather straight forward so I implemented it, see https://github.com/rg3/youtube-dl/pull/14185

now the only thing left is to cross fingers and hope one of the maintainers review and accept the pull request :shipit:
