### ISSUE TITLE
Ustream.tv No video formats found

### ISSUE THREAD

**Issue by zoltanvi** [rg3/youtube-dl#13520]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.06.25*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.06.25**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
Hi!
I'm trying to download a video from ustream, and get this error: 
```
youtube-dl --verbose http://www.ustream.tv/recorded/105007891
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'http://www.ustream.tv/recorded/105007891']
[debug] Encodings: locale cp1250, fs mbcs, out cp852, pref cp1250
[debug] youtube-dl version 2017.06.25
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: none
[debug] Proxy map: {}
[ustream] 105007891: Downloading JSON metadata
[ustream] 105007891: Downloading connection info
[ustream] 105007891: Downloading stream info
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpuoca4kkw\build\youtube_dl\YoutubeDL.py", line 762, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpuoca4kkw\build\youtube_dl\extractor\common.py", line 433, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpuoca4kkw\build\youtube_dl\extractor\ustream.py", line 217, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpuoca4kkw\build\youtube_dl\extractor\common.py", line 1056, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


```

**Comment by parmjitv** [comment]
Also see issues #11072 and #12662.  Apparently this has been an ongoing issue for some time now.

The JSON data can be retrieved for this particular video without any problems, but does not contain any references to media links for some wonky reason:

{u'protect': u'public', u'description': u'NEBU_KURO', u'links': {u'channel': {u'href': u'https://api.ustream.tv/channels/13457243.json', u'id': u'13457243'}}, u'title': u'NEBU_KURO', u'url': u'http://www.ustream.tv/recorded/105007891', u'created_at': 1498040649, u'views': 3265, u'tinyurl': u'http://ustre.am/:76BlF', u'added_at': 1498040649, u'thumbnail': {u'default': u'https://ustvstaticcdn2-a.akamaihd.net/i/video/picture/0/1/105/105007/105007891/1_13457243_105007891,192x108,b,1:1.jpg'}, u'locks': {}, u'owner': {u'username': u'NEBU_KURO', u'picture': u'https://ustvstaticcdn1-a.akamaihd.net/images/defaults/user_48x48:3.png', u'id': u'21577342'}, u'length': u'517.090', u'chapters': [], u'file_size': u'97798463', u'schedule': None, **u'media_urls': {u'flv': None}**, u'id': u'105007891'}

... Perhaps this is related to geo-restrictions of some kind?

Cheers,

Parmjit V.

**Comment by bingowings** [comment]
I'm having the exact same problem with version **_2017.09.15_**.

<pre><code>youtube-dl -v 
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.09.15
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-86755-g0780ad9, ffprobe N-86755-g0780ad9
[debug] Proxy map: {}
</code></pre>
I'm unable to download recorded Ustream videos. "No video format found."
<pre><code>
youtube-dl -f bestvideo+bestaudio "http://www.ustream.tv/
recorded/107949320" --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'bestvideo+bestaudio', 'http://www.ustream.tv/
recorded/107949320', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.09.15
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-86755-g0780ad9, ffprobe N-86755-g0780ad9
[debug] Proxy map: {}
[ustream] 107949320: Downloading JSON metadata
[ustream] 107949320: Downloading connection info
[ustream] 107949320: Downloading stream info
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug
 . Make sure you are using the latest version; type  youtube-dl -U  to update. B
e sure to call youtube-dl with the --verbose flag and include its complete outpu
t.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpl1klaw4y\bu
ild\youtube_dl\YoutubeDL.py", line 776, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpl1klaw4y\bu
ild\youtube_dl\extractor\common.py", line 434, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpl1klaw4y\bu
ild\youtube_dl\extractor\ustream.py", line 217, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpl1klaw4y\bu
ild\youtube_dl\extractor\common.py", line 1072, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issu
e on https://yt-dl.org/bug . Make sure you are using the latest version; type  y
outube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and
include its complete output.
</code></pre>

**Comment by scienceteacher1972** [comment]
I think I discovered something.
I also had problems downloading certain videos.
But as soon as I started watching one of those videos with my browser, just a couple seconds of it, I was able to download them immediately.
Seems like a lot of videos are just 'offline' when not watched for a long time.
And as soon as you watch them with browser, they seem to be get 'waken up' and made 'online' again.

**Comment by MrBurberry** [comment]
Thank you for answering. But I’m afraid I can’t.For the fastest speed I installed the software at my server ,so I can’t use browser. And when I download videos of youtube , the sound and video are two files, both pc and server

Best regards

在 2017年12月28日，上午1:38，scienceteacher1972 <notifications@github.com<mailto:notifications@github.com>> 写道：


I think I discovered something.
I also had problems downloading certain videos.
But as soon as I started watching one of those videos with my browser, just a couple seconds of it, I was able to download them immediately.
Seems like a lot of videos are just 'offline' when not watched for a long time.
And as soon as you watch them with browser, they seem to be get 'waken up' and made 'online' again.

**Comment by 89z** [comment]
Issue should be closed, URL is dead
