### ISSUE TITLE
ThisOldHouse extractor error

### ISSUE THREAD

**Issue by smrss** [rg3/youtube-dl#13530]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.06.25*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.06.25**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'-f', u'[height=720]', u'--all-subs', u'-o', u'/d/rain-garden-lighting.mp4', u'https://www.thisoldhouse.com/watch/ask-toh-rain-garden-lighting']
[debug] Encodings: locale ANSI_X3.4-1968, fs UTF-8, out UTF-8, pref ANSI_X3.4-1968
[debug] youtube-dl version 2017.06.25
[debug] Python version 2.7.12 - CYGWIN_NT-6.1-WOW-2.7.0-0.306-5-3-i686-32bit
[debug] exe versions: ffmpeg N-83749-g035e932, ffprobe N-83749-g035e932
[debug] Proxy map: {}
[ThisOldHouse] ask-toh-rain-garden-lighting: Downloading webpage
ERROR: An extractor error has occurred. (caused by KeyError(u'jwplatform',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/thisoldhouse.py", line 34, in _real_extract
    video_id = drupal_settings['jwplatform']['video_id']
KeyError: u'jwplatform'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 762, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 446, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
ExtractorError: An extractor error has occurred. (caused by KeyError(u'jwplatform',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by parmjitv** [comment]
Hi @smrss,

It appears the embedded JSON data has been updated on this site.  I will submit a new PR with a fix in place for this shortly.

Cheers,

Parmjit V.
