### ISSUE TITLE
No video formats found error when manifest contains video information

### ISSUE THREAD

**Issue by 1470258369** [rg3/youtube-dl#13538]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.06.25*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.06.25**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
python youtube-dl https://vod-drm.medialaancdn.be/2017/06/
27/257200671624000/1498595993/dash/drm/castlabs/Manifest.mpd --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://vod-drm.medialaancdn.be/2017/06/27/257200671624000/1498595993/dash/drm/castlabs/Manifest.mpd', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.06.25
[debug] Python version 3.5.0 - Windows-post2012Server-6.3.9600
[debug] exe versions: ffmpeg 2.8.4
[debug] Proxy map: {}
[generic] Manifest: Requesting header
WARNING: Falling back on generic information extractor.
[generic] Manifest: Downloading webpage
[generic] Manifest: Extracting information
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube-dl\youtube_dl\YoutubeDL.py", line 762, in extract_info
    ie_result = ie.extract(url)
  File "youtube-dl\youtube_dl\extractor\common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "youtube-dl\youtube_dl\extractor\generic.py", line 1989, in _real_extract

    self._sort_formats(info_dict['formats'])
  File "youtube-dl\youtube_dl\extractor\common.py", line 1056, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

---

### Description of your *issue*, suggested solution and other information

I get a *no video formats found* error. But when I go to the manifest, there is a video section with contents:

```
<!--com.castlabs.drmtoday.encrypter dashencrypter 2.0.135
-->
<!--isoparser-1.1.21-->
<MPD profiles="urn:mpeg:dash:profile:isoff-on-demand:2011" type="static" minBufferTime="PT79S" mediaPresentationDuration="PT51M4S">
    <ProgramInformation moreInformationURL="www.castLabs.com"/>
    <Period id="0" start="PT0S" duration="PT51M4S">
        <AdaptationSet id="1" segmentAlignment="true" subsegmentAlignment="true" subsegmentStartsWithSAP="1" startWithSAP="1" bitstreamSwitching="true" mimeType="video/mp4" par="16:9" frameRate="25000/1000" sar="1:1" minWidth="320" maxWidth="1024" minHeight="180" maxHeight="576" minBandwidth="297000" maxBandwidth="985800">
            <ContentProtection cenc:default_KID="7dba728b-977d-4dc2-86ca-297e3befbb31" schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc"/>
            <ContentProtection schemeIdUri="urn:uuid:9a04f079-9840-4286-ab92-e65be0885f95">
                <cenc:pssh>AAADLnBzc2gAAAAAmgTweZhAQoarkuZb4IhflQAAAw4OAwAAAQABAAQDPABXAFIATQBIAEUAQQBEAEUAUgAgAHgAbQBsAG4AcwA9ACIAaAB0AHQAcAA6AC8ALwBzAGMAaABlAG0AYQBzAC4AbQBpAGMAcgBvAHMAbwBmAHQALgBjAG8AbQAvAEQAUgBNAC8AMgAwADAANwAvADAAMwAvAFAAbABhAHkAUgBlAGEAZAB5AEgAZQBhAGQAZQByACIAIAB2AGUAcgBzAGkAbwBuAD0AIgA0AC4AMAAuADAALgAwACIAPgA8AEQAQQBUAEEAPgA8AFAAUgBPAFQARQBDAFQASQBOAEYATwA+ADwASwBFAFkATABFAE4APgAxADYAPAAvAEsARQBZAEwARQBOAD4APABBAEwARwBJAEQAPgBBAEUAUwBDAFQAUgA8AC8AQQBMAEcASQBEAD4APAAvAFAAUgBPAFQARQBDAFQASQBOAEYATwA+ADwASwBJAEQAPgBpADMASwA2AGYAWAAyAFgAdwBrADIARwB5AGkAbAArAE8AKwArADcATQBRAD0APQA8AC8ASwBJAEQAPgA8AEwAQQBfAFUAUgBMAD4AaAB0AHQAcABzADoALwAvAGwAaQBjAC4AZAByAG0AdABvAGQAYQB5AC4AYwBvAG0ALwBsAGkAYwBlAG4AcwBlAC0AcAByAG8AeAB5AC0AaABlAGEAZABlAHIAYQB1AHQAaAAvAGQAcgBtAHQAbwBkAGEAeQAvAFIAaQBnAGgAdABzAE0AYQBuAGEAZwBlAHIALgBhAHMAbQB4ADwALwBMAEEAXwBVAFIATAA+ADwATABVAEkAXwBVAFIATAA+AGgAdAB0AHAAOgAvAC8AbQBlAGQAaQBhAGwAYQBhAG4ALgBiAGUAPAAvAEwAVQBJAF8AVQBSAEwAPgA8AEMASABFAEMASwBTAFUATQA+AEoAZQB2AE4ANQB0AE4AMABBAEkAQQA9ADwALwBDAEgARQBDAEsAUwBVAE0APgA8AC8ARABBAFQAQQA+ADwALwBXAFIATQBIAEUAQQBEAEUAUgA+AA==</cenc:pssh>
                <mspr:pro>DgMAAAEAAQAEAzwAVwBSAE0ASABFAEEARABFAFIAIAB4AG0AbABuAHMAPQAiAGgAdAB0AHAAOgAvAC8AcwBjAGgAZQBtAGEAcwAuAG0AaQBjAHIAbwBzAG8AZgB0AC4AYwBvAG0ALwBEAFIATQAvADIAMAAwADcALwAwADMALwBQAGwAYQB5AFIAZQBhAGQAeQBIAGUAYQBkAGUAcgAiACAAdgBlAHIAcwBpAG8AbgA9ACIANAAuADAALgAwAC4AMAAiAD4APABEAEEAVABBAD4APABQAFIATwBUAEUAQwBUAEkATgBGAE8APgA8AEsARQBZAEwARQBOAD4AMQA2ADwALwBLAEUAWQBMAEUATgA+ADwAQQBMAEcASQBEAD4AQQBFAFMAQwBUAFIAPAAvAEEATABHAEkARAA+ADwALwBQAFIATwBUAEUAQwBUAEkATgBGAE8APgA8AEsASQBEAD4AaQAzAEsANgBmAFgAMgBYAHcAawAyAEcAeQBpAGwAKwBPACsAKwA3AE0AUQA9AD0APAAvAEsASQBEAD4APABMAEEAXwBVAFIATAA+AGgAdAB0AHAAcwA6AC8ALwBsAGkAYwAuAGQAcgBtAHQAbwBkAGEAeQAuAGMAbwBtAC8AbABpAGMAZQBuAHMAZQAtAHAAcgBvAHgAeQAtAGgAZQBhAGQAZQByAGEAdQB0AGgALwBkAHIAbQB0AG8AZABhAHkALwBSAGkAZwBoAHQAcwBNAGEAbgBhAGcAZQByAC4AYQBzAG0AeAA8AC8ATABBAF8AVQBSAEwAPgA8AEwAVQBJAF8AVQBSAEwAPgBoAHQAdABwADoALwAvAG0AZQBkAGkAYQBsAGEAYQBuAC4AYgBlADwALwBMAFUASQBfAFUAUgBMAD4APABDAEgARQBDAEsAUwBVAE0APgBKAGUAdgBOADUAdABOADAAQQBJAEEAPQA8AC8AQwBIAEUAQwBLAFMAVQBNAD4APAAvAEQAQQBUAEEAPgA8AC8AVwBSAE0ASABFAEEARABFAFIAPgA=</mspr:pro>
            </ContentProtection>
            <ContentProtection schemeIdUri="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed">
                <cenc:pssh>AAAAVHBzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAADQIARIQfbpyi5d9TcKGyil+O++7MRoIY2FzdGxhYnMiEH26couXfU3ChsopfjvvuzEqAlNE</cenc:pssh>
            </ContentProtection>
            <Role schemeIdUri="urn:mpeg:dash:role:2011" value="main"/>
            <Representation codecs="avc1.4d400d" width="320" height="180" id="Low.mp4" bandwidth="297000">
                <BaseURL>Low.mp4</BaseURL>
                <SegmentBase timescale="90000" indexRangeExact="true" indexRange="1685-5400">
                    <Initialization range="0-1684"/>
                </SegmentBase>
            </Representation>
            <Representation codecs="avc1.4d4015" width="480" height="270" id="Medium.mp4" bandwidth="496200">
                <BaseURL>Medium.mp4</BaseURL>
                <SegmentBase timescale="90000" indexRangeExact="true" indexRange="1685-5400">
                    <Initialization range="0-1684"/>
                </SegmentBase>
            </Representation>
            <Representation codecs="avc1.4d401e" width="640" height="360" id="High.mp4" bandwidth="891400">
                <BaseURL>High.mp4</BaseURL>
                <SegmentBase timescale="90000" indexRangeExact="true" indexRange="1684-5399">
                    <Initialization range="0-1683"/>
                </SegmentBase>
            </Representation>
            <Representation codecs="avc1.4d401f" width="1024" height="576" id="BB.mp4" bandwidth="985800">
                <BaseURL>BB.mp4</BaseURL>
                <SegmentBase timescale="90000" indexRangeExact="true" indexRange="1685-5400">
                    <Initialization range="0-1684"/>
                </SegmentBase>
            </Representation>
        </AdaptationSet>
        <AdaptationSet segmentAlignment="true" subsegmentAlignment="true" subsegmentStartsWithSAP="1" startWithSAP="1" bitstreamSwitching="true" mimeType="audio/mp4">
            <ContentProtection cenc:default_KID="7dba728b-977d-4dc2-86ca-297e3befbb31" schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc"/>
            <ContentProtection schemeIdUri="urn:uuid:9a04f079-9840-4286-ab92-e65be0885f95">
                <cenc:pssh>AAADLnBzc2gAAAAAmgTweZhAQoarkuZb4IhflQAAAw4OAwAAAQABAAQDPABXAFIATQBIAEUAQQBEAEUAUgAgAHgAbQBsAG4AcwA9ACIAaAB0AHQAcAA6AC8ALwBzAGMAaABlAG0AYQBzAC4AbQBpAGMAcgBvAHMAbwBmAHQALgBjAG8AbQAvAEQAUgBNAC8AMgAwADAANwAvADAAMwAvAFAAbABhAHkAUgBlAGEAZAB5AEgAZQBhAGQAZQByACIAIAB2AGUAcgBzAGkAbwBuAD0AIgA0AC4AMAAuADAALgAwACIAPgA8AEQAQQBUAEEAPgA8AFAAUgBPAFQARQBDAFQASQBOAEYATwA+ADwASwBFAFkATABFAE4APgAxADYAPAAvAEsARQBZAEwARQBOAD4APABBAEwARwBJAEQAPgBBAEUAUwBDAFQAUgA8AC8AQQBMAEcASQBEAD4APAAvAFAAUgBPAFQARQBDAFQASQBOAEYATwA+ADwASwBJAEQAPgBpADMASwA2AGYAWAAyAFgAdwBrADIARwB5AGkAbAArAE8AKwArADcATQBRAD0APQA8AC8ASwBJAEQAPgA8AEwAQQBfAFUAUgBMAD4AaAB0AHQAcABzADoALwAvAGwAaQBjAC4AZAByAG0AdABvAGQAYQB5AC4AYwBvAG0ALwBsAGkAYwBlAG4AcwBlAC0AcAByAG8AeAB5AC0AaABlAGEAZABlAHIAYQB1AHQAaAAvAGQAcgBtAHQAbwBkAGEAeQAvAFIAaQBnAGgAdABzAE0AYQBuAGEAZwBlAHIALgBhAHMAbQB4ADwALwBMAEEAXwBVAFIATAA+ADwATABVAEkAXwBVAFIATAA+AGgAdAB0AHAAOgAvAC8AbQBlAGQAaQBhAGwAYQBhAG4ALgBiAGUAPAAvAEwAVQBJAF8AVQBSAEwAPgA8AEMASABFAEMASwBTAFUATQA+AEoAZQB2AE4ANQB0AE4AMABBAEkAQQA9ADwALwBDAEgARQBDAEsAUwBVAE0APgA8AC8ARABBAFQAQQA+ADwALwBXAFIATQBIAEUAQQBEAEUAUgA+AA==</cenc:pssh>
                <mspr:pro>DgMAAAEAAQAEAzwAVwBSAE0ASABFAEEARABFAFIAIAB4AG0AbABuAHMAPQAiAGgAdAB0AHAAOgAvAC8AcwBjAGgAZQBtAGEAcwAuAG0AaQBjAHIAbwBzAG8AZgB0AC4AYwBvAG0ALwBEAFIATQAvADIAMAAwADcALwAwADMALwBQAGwAYQB5AFIAZQBhAGQAeQBIAGUAYQBkAGUAcgAiACAAdgBlAHIAcwBpAG8AbgA9ACIANAAuADAALgAwAC4AMAAiAD4APABEAEEAVABBAD4APABQAFIATwBUAEUAQwBUAEkATgBGAE8APgA8AEsARQBZAEwARQBOAD4AMQA2ADwALwBLAEUAWQBMAEUATgA+ADwAQQBMAEcASQBEAD4AQQBFAFMAQwBUAFIAPAAvAEEATABHAEkARAA+ADwALwBQAFIATwBUAEUAQwBUAEkATgBGAE8APgA8AEsASQBEAD4AaQAzAEsANgBmAFgAMgBYAHcAawAyAEcAeQBpAGwAKwBPACsAKwA3AE0AUQA9AD0APAAvAEsASQBEAD4APABMAEEAXwBVAFIATAA+AGgAdAB0AHAAcwA6AC8ALwBsAGkAYwAuAGQAcgBtAHQAbwBkAGEAeQAuAGMAbwBtAC8AbABpAGMAZQBuAHMAZQAtAHAAcgBvAHgAeQAtAGgAZQBhAGQAZQByAGEAdQB0AGgALwBkAHIAbQB0AG8AZABhAHkALwBSAGkAZwBoAHQAcwBNAGEAbgBhAGcAZQByAC4AYQBzAG0AeAA8AC8ATABBAF8AVQBSAEwAPgA8AEwAVQBJAF8AVQBSAEwAPgBoAHQAdABwADoALwAvAG0AZQBkAGkAYQBsAGEAYQBuAC4AYgBlADwALwBMAFUASQBfAFUAUgBMAD4APABDAEgARQBDAEsAUwBVAE0APgBKAGUAdgBOADUAdABOADAAQQBJAEEAPQA8AC8AQwBIAEUAQwBLAFMAVQBNAD4APAAvAEQAQQBUAEEAPgA8AC8AVwBSAE0ASABFAEEARABFAFIAPgA=</mspr:pro>
            </ContentProtection>
            <ContentProtection schemeIdUri="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed">
                <cenc:pssh>AAAAVHBzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAADQIARIQfbpyi5d9TcKGyil+O++7MRoIY2FzdGxhYnMiEH26couXfU3ChsopfjvvuzEqAlNE</cenc:pssh>
            </ContentProtection>
            <Role schemeIdUri="urn:mpeg:dash:role:2011" value="main"/>
            <Representation codecs="mp4a.40.2" audioSamplingRate="48000" id="BB_2.mp4" bandwidth="63700">
                <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
                <BaseURL>BB_2.mp4</BaseURL>
                <SegmentBase timescale="48000" indexRangeExact="true" indexRange="1622-4101">
                    <Initialization range="0-1621"/>
                </SegmentBase>
            </Representation>
            <Representation codecs="mp4a.40.2" audioSamplingRate="48000" id="High_2.mp4" bandwidth="63700">
                <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
                <BaseURL>High_2.mp4</BaseURL>
                <SegmentBase timescale="48000" indexRangeExact="true" indexRange="1622-4101">
                    <Initialization range="0-1621"/>
                </SegmentBase>
            </Representation>
            <Representation codecs="mp4a.40.2" audioSamplingRate="48000" id="Low_2.mp4" bandwidth="63700">
                <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
                <BaseURL>Low_2.mp4</BaseURL>
                <SegmentBase timescale="48000" indexRangeExact="true" indexRange="1622-4101">
                    <Initialization range="0-1621"/>
                </SegmentBase>
            </Representation>
            <Representation codecs="mp4a.40.2" audioSamplingRate="48000" id="Medium_2.mp4" bandwidth="63700">
                <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
                <BaseURL>Medium_2.mp4</BaseURL>
                <SegmentBase timescale="48000" indexRangeExact="true" indexRange="1622-4101">
                    <Initialization range="0-1621"/>
                </SegmentBase>
            </Representation>
        </AdaptationSet>
    </Period>
</MPD>
```

**Comment by dstftw** [comment]
This media is DRM protected.
