### ISSUE TITLE
douyu TV    no download

### ISSUE THREAD

**Issue by lbcake** [rg3/youtube-dl#13544]
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpuoca4kkw\bu
ild\youtube_dl\__init__.py", line 465, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpuoca4kkw\bu
ild\youtube_dl\__init__.py", line 455, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpuoca4kkw\bu
ild\youtube_dl\YoutubeDL.py", line 1927, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpuoca4kkw\bu
ild\youtube_dl\YoutubeDL.py", line 762, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpuoca4kkw\bu
ild\youtube_dl\extractor\common.py", line 433, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpuoca4kkw\bu
ild\youtube_dl\extractor\douyutv.py", line 106, in _real_extract
TypeError: list indices must be integers, not str

no download     请解决

**Comment by lbcake** [comment]
C:\Users\Administrator>C:\Users\Administrator\Desktop\youtube-dl.exe https://www
.douyu.com/206858
[DouyuTV] 206858: Downloading room info
[DouyuTV] 206858: Downloading video URL info
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpuoca4kkw\bu
ild\youtube_dl\__init__.py", line 465, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpuoca4kkw\bu
ild\youtube_dl\__init__.py", line 455, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpuoca4kkw\bu
ild\youtube_dl\YoutubeDL.py", line 1927, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpuoca4kkw\bu
ild\youtube_dl\YoutubeDL.py", line 762, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpuoca4kkw\bu
ild\youtube_dl\extractor\common.py", line 433, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpuoca4kkw\bu
ild\youtube_dl\extractor\douyutv.py", line 106, in _real_extract
TypeError: list indices must be integers, not str

**Comment by lbcake** [comment]
link：https://www.douyu.com/206858



Make sure you are using the latest version: run youtube-dl --version and ensure your version is 2017.06.25. If it's not read this FAQ entry and update. Issues with outdated version will be rejected.

 I've verified and I assure that I'm running youtube-dl 2017.06.25

**Comment by lbcake** [comment]
Make sure you are using the latest version: run youtube-dl --version and ensure your version is 2017.06.25. If it's not read this FAQ entry and update. Issues with outdated version will be rejected.

 I've verified and I assure that I'm running youtube-dl 2017.06.25

**Comment by lbcake** [comment]
How do you do it?

**Comment by dstftw** [comment]
This is not yet fixed.

**Comment by lbcake** [comment]
希望尽快解决！

**Comment by dstftw** [comment]
Duplicate of #13419. Move there for further discussions.
