### ISSUE TITLE
DailyMotion - ERROR: unable to download video data: HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by rnoremacc** [rg3/youtube-dl#13559]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.07.02*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.07.02**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
EXAMPLE 1 which does download the subtitles, but not the video:
~$ youtube-dl --verbose -i --write-sub --sub-lang en,id --sub-format srt http://www.dailymotion.com/video/x5sfc9c_eng-sub-indo-sub-m-i-r-2-ep-09_tv
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'-i', u'--write-sub', u'--sub-lang', u'en,id', u'--sub-format', u'srt', u'http://www.dailymotion.com/video/x5sfc9c_eng-sub-indo-sub-m-i-r-2-ep-09_tv']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.07.02
[debug] Python version 2.7.13 - Linux-4.10.0-26-generic-x86_64-with-Ubuntu-17.04-zesty
[debug] exe versions: ffmpeg 3.2.4-1build2, ffprobe 3.2.4-1build2
[debug] Proxy map: {}
[dailymotion] x5sfc9c: Downloading webpage
[dailymotion] x5sfc9c: Downloading m3u8 information
[dailymotion] x5sfc9c: Downloading m3u8 information
[dailymotion] x5sfc9c: Downloading m3u8 information
[dailymotion] x5sfc9c: Downloading m3u8 information
[dailymotion] x5sfc9c: Downloading m3u8 information
[dailymotion] x5sfc9c: Downloading m3u8 information
[info] Writing video subtitles to: [Eng Sub_Indo Sub] M.I.R.2 Ep.09-x5sfc9c.en.srt
[info] Writing video subtitles to: [Eng Sub_Indo Sub] M.I.R.2 Ep.09-x5sfc9c.id.srt
[debug] Invoking downloader on u'https://www.dailymotion.com/cdn/H264-1920x1080/video/x5sfc9c.mp4?auth=1499309373-2562-ujtey0in-34973af069944660e7a8b69fe956e59f'
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1834, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1776, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 361, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 61, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2137, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 467, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 654, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found
---------------------------------------------------------
EXAMPLE 2:
$ youtube-dl -i http://www.dailymotion.com/video/x5sf6ty_engsub-bl-2moonss-the-series-ep-9-full-hd1080p_tv
[dailymotion] x5sf6ty: Downloading webpage
[dailymotion] x5sf6ty: Downloading m3u8 information
[dailymotion] x5sf6ty: Downloading m3u8 information
[dailymotion] x5sf6ty: Downloading m3u8 information
[dailymotion] x5sf6ty: Downloading m3u8 information
[dailymotion] x5sf6ty: Downloading m3u8 information
[dailymotion] x5sf6ty: Downloading m3u8 information
[dailymotion] x5sf6ty: Downloading m3u8 information
ERROR: unable to download video data: HTTP Error 404: Not Found

...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Downloads worked 24 hours ago, now every file I try fails.

**Comment by rnoremacc** [comment]
Hi,
Sorry I forgot to invoke verbose on the second example:

$ youtube-dl --verbose -i http://www.dailymotion.com/video/x5sf6ty_engsub-bl-2moonss-the-series-ep-9-full-hd1080p_tv
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'-i', u'http://www.dailymotion.com/video/x5sf6ty_engsub-bl-2moonss-the-series-ep-9-full-hd1080p_tv']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.07.02
[debug] Python version 2.7.13 - Linux-4.10.0-26-generic-x86_64-with-Ubuntu-17.04-zesty
[debug] exe versions: ffmpeg 3.2.4-1build2, ffprobe 3.2.4-1build2
[debug] Proxy map: {}
[dailymotion] x5sf6ty: Downloading webpage
[dailymotion] x5sf6ty: Downloading m3u8 information
[dailymotion] x5sf6ty: Downloading m3u8 information
[dailymotion] x5sf6ty: Downloading m3u8 information
[dailymotion] x5sf6ty: Downloading m3u8 information
[dailymotion] x5sf6ty: Downloading m3u8 information
[dailymotion] x5sf6ty: Downloading m3u8 information
[dailymotion] x5sf6ty: Downloading m3u8 information
[debug] Invoking downloader on u'https://www.dailymotion.com/cdn/H264-1920x1080/video/x5sf6ty.mp4?auth=1499317304-2562-6icp2vha-65b79126b40808f24bfc5993a75bd125'
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1834, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1776, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 361, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 61, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2137, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 467, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 654, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found

Regards,
Chris.

**Comment by rnoremacc** [comment]
Hi,
The problem seems to have been with the DailyMotion website, as both my example files have now downloaded correctly. I saw some reports that even the regular web browser playback from DM wasn't working, so they must have had a problem internally.
Sorry to have wasted anyone's time.
Chris.

**Comment by omidraha** [comment]
I [have](https://github.com/rg3/youtube-dl/issues/5337) [same](https://github.com/rg3/youtube-dl/issues/4782) [issue](https://github.com/rg3/youtube-dl/issues/2563) with some videos in youtube.

`ERROR: unable to download video data: HTTP Error 404: Not Found`

Traceback:
```

Traceback (most recent call last):
  File "/home/or/.local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 1903, in process_info
    partial_success = dl(fname, new_info)
  File "/home/or/.local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 1848, in dl
    return fd.download(name, info)
  File "/home/or/.local/lib/python2.7/site-packages/youtube_dl/downloader/common.py", line 364, in download
    return self.real_download(filename, info_dict)
  File "/home/or/.local/lib/python2.7/site-packages/youtube_dl/downloader/http.py", line 341, in real_download
    establish_connection()
  File "/home/or/.local/lib/python2.7/site-packages/youtube_dl/downloader/http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/home/or/.local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 2212, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 467, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 654, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found
```
```

$ youtube-dl --version
2019.01.10
```

**Comment by fx86** [comment]
I was getting the same error for trying to download a youtube playlist. Upgrading to `2019.01.30.1` from `2018.11.18` fixed it.
