### ISSUE TITLE
Add support for craftsy.com

### ISSUE THREAD

**Issue by Steveland** [rg3/youtube-dl#13550]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.07.02*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.07.02**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
youtube-dl.exe -v https://course.craftsy.com/play/11292
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://course.craftsy.com/play/11292']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.07.02
[debug] Python version 3.4.4 - Windows-10-10.0.15063
[debug] exe versions: ffmpeg 3.2.2, ffprobe 3.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 11292: Requesting header
WARNING: Could not send HEAD request to https://course.craftsy.com/play/11292: HTTP Error 405: Method Not Allowed
[generic] 11292: Downloading webpage
WARNING: Falling back on generic information extractor.
[generic] 11292: Extracting information
ERROR: Unsupported URL: https://course.craftsy.com/play/11292
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcnuqbtg0\build\youtube_dl\YoutubeDL.py", line 762, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcnuqbtg0\build\youtube_dl\extractor\common.py", line 433, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcnuqbtg0\build\youtube_dl\extractor\generic.py", line 2824, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://course.craftsy.com/play/11292

```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://course.craftsy.com/play/11292

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

**Comment by barsnick** [comment]
Since you can't view that video in a browser without a login, youtube-dl won't be able to download it either. Have you tried providing login credentials? (I'm not sure whether yt-dl needs to understand the login mechanism though.)

**Comment by Steveland** [comment]
Thank you barsnick for your help. I did not try with login credentials. I'll try this!

**Comment by barsnick** [comment]
Hi Steveland, I tried that myself and it doesn't work, probably because yt-dl can't handle the credentials with ```-u``` and ```-p``` (i.e. doesn't know how the login page works).

If any developer gets that done, I'm sure the rest is easy. The direct URL to the video is contained in the HTML5 enabled video page, in the tag ```<source src="https://host/videourl.mp4" ...>```. I copied that URL into a download tool (or a separate browser tab), and the complete 720p video landed on my disk.
