### ISSUE TITLE
SITE REQUEST: tvrain.ru

### ISSUE THREAD

**Issue by nmr50** [rg3/youtube-dl#13557]
Hello dearest coders!
I want to ask you to add tvrain.ru (m3u8 - multiple resolutions' chunks lists) to YDL. The log is here:
C:\>youtube-dl -F -v https://tvrain.ru/lite/teleshow/kak_vse_nachinalos/namin-418921/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-F', '-v', 'https://tvrain.ru/lite/teleshow/kak_vse_nachinalos/namin-418921/']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2017.07.02
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2, rtmpdump 2.4
[debug] Proxy map: {}
[generic] namin-418921: Requesting header
WARNING: Falling back on generic information extractor.
[generic] namin-418921: Downloading webpage
[generic] namin-418921: Extracting information
ERROR: Unsupported URL: https://tvrain.ru/lite/teleshow/kak_vse_nachinalos/namin-418921/
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcnuqbtg0\build\youtube_dl\YoutubeDL.py", line 762,in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcnuqbtg0\build\youtube_dl\extractor\common.py", line 433, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcnuqbtg0\build\youtube_dl\extractor\generic.py", line 2824, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://tvrain.ru/lite/teleshow/kak_vse_nachinalos/namin-418921/

Thanks in advance!

**Comment by nmr50** [comment]
It works now, THANK you very much!!:)
