### ISSUE TITLE
vier.be not working anymore

### ISSUE THREAD

**Issue by xplorr** [rg3/youtube-dl#13575]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.07.02*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.07.02**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

---

### Description of your *issue*, suggested solution and other information

site Vier.be worked before. But since website changed, it's not supported anymore, even when supplying userid and password.

---

F:\Temp\>**youtube-dl -v https://www.vier.be/video/achter-de-rug/2017/achter-de-rug-seizoen-1-aflevering-6**
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.vier.be/video/achter-de-rug/2017/achter-de-rug-seizoen-1-aflevering-6']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.06.18
[debug] Python version 2.7.13 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-77704-g68eb208, ffprobe 2.2.3
[debug] Proxy map: {}
[generic] achter-de-rug-seizoen-1-aflevering-6: Requesting header
WARNING: Falling back on generic information extractor.
[generic] achter-de-rug-seizoen-1-aflevering-6: Downloading webpage
[generic] achter-de-rug-seizoen-1-aflevering-6: Extracting information
ERROR: Unsupported URL: https://www.vier.be/video/achter-de-rug/2017/achter-de-rug-seizoen-1-aflevering-6
Traceback (most recent call last):
  File "youtube_dl\extractor\generic.pyo", line 1971, in _real_extract
  File "youtube_dl\compat.pyo", line 2539, in compat_etree_fromstring
  File "youtube_dl\compat.pyo", line 2528, in _XML
  File "xml\etree\ElementTree.pyo", line 1653, in feed
  File "xml\etree\ElementTree.pyo", line 1517, in _raiseerror
ParseError: not well-formed (invalid token): line 33, column 46
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 762, in extract_info
  File "youtube_dl\extractor\common.pyo", line 433, in extract
  File "youtube_dl\extractor\generic.pyo", line 2796, in _real_extract
**UnsupportedError: Unsupported URL: https://www.vier.be/video/achter-de-rug/2017/achter-de-rug-seizoen-1-aflevering-6**

**Comment by Ruud-cb** [comment]
I am still not able to download from vier.be
Not sure if it is due authentication or geo-restrict. Url I try to download:
https://www.vier.be/video/de-slimste-mens-ter-wereld/de-slimste-mens-ter-wereld-seizoen-15/de-slimste-mens-ter-wereld-seizoen-15-aflevering-4

When using username and password.
PS C:\Users\Ruud\Dropbox\Ruud\Installers> .\youtube-dl.exe --username r.faessen@hotmail.com --p
assword qAeMdz24Scxw24% https://www.vier.be/video/de-slimste-mens-ter-wereld/de-slimste-mens-te
r-wereld-seizoen-15/de-slimste-mens-ter-wereld-seizoen-15-aflevering-4 --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--username', 'PRIVATE', '--password', 'PRIVATE', 'https://www.vier.be/video/de-slimste-mens-ter-wereld/de-slimste-mens-ter-wereld-seizoen-15/de-slimste-mens-ter-wereld-seizoen-15-aflevering-4', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.10.29
[debug] Python version 3.4.4 - Windows-10-10.0.15063
[debug] exe versions: none
[debug] Proxy map: {}
[vier] Logging in
ERROR: Unable to log in: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\build\youtube_dl\extractor\common.py", line 503, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\build\youtube_dl\YoutubeDL.py", line 2195, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default

Read in some others that authentication is bypassed, so tried without:

PS C:\Users\Ruud\Dropbox\Ruud\Installers> .\youtube-dl.exe --geo-bypass-country BE https://www.
vier.be/video/de-slimste-mens-ter-wereld/de-slimste-mens-ter-wereld-seizoen-15/de-slimste-mens-
ter-wereld-seizoen-15-aflevering-4 --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--geo-bypass-country', 'BE', 'https://www.vier.be/video/de-slimste-mens-ter-wereld/de-slimste-mens-ter-wereld-seizoen-15/de-slimste-mens-ter-wereld-seizoen-15-aflevering-4', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.10.29
[debug] Python version 3.4.4 - Windows-10-10.0.15063
[debug] exe versions: none
[debug] Proxy map: {}
[debug] Using fake IP 57.143.117.198 (BE) as X-Forwarded-For.
[vier] de-slimste-mens-ter-wereld-seizoen-15-aflevering-4: Downloading webpage
ERROR: Unable to extract filename; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\build\youtube_dl\YoutubeDL.py", line 784, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\build\youtube_dl\extractor\common.py", line 434, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\build\youtube_dl\extractor\vier.py", line 170, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\build\youtube_dl\extractor\common.py", line 797, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract filename; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Any help?

**Comment by xplorr** [comment]
Try with my custom version of youtube-dl https://forum.videohelp.com/threads/382423-YoutubeVideoDownloader-download-video-and-audio-from-900-sites
Let me know if that works.

**Comment by brechtm** [comment]
@wernerkarlheisenberg implemented this in #15412

**Comment by 89z** [comment]
Issue should be closed, URL is dead
