### ISSUE TITLE
[soundcloud] Problems with names when downloading

### ISSUE THREAD

**Issue by lucas59356** [rg3/youtube-dl#13645]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.07.09*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2017.07.09**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
User@USER-PC D:\Users\User\Music\download\Naldo 2016                                                                                                                      
$ youtube-dl https://soundcloud.com/arnaldo-leandro/sets/naldo-2016 --add-metadata --embed-thumbnail -v                                                                   
[debug] System config: []                                                                                                                                                 
[debug] User config: []                                                                                                                                                   
[debug] Custom config: []                                                                                                                                                 
[debug] Command-line args: ['https://soundcloud.com/arnaldo-leandro/sets/naldo-2016', '--add-metadata', '--embed-thumbnail', '-v']                                        
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252                                                                                                         
[debug] youtube-dl version 2017.07.09                                                                                                                                     
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1                                                                                                                     
[debug] exe versions: ffmpeg 2.8.4                                                                                                                                        
[debug] Proxy map: {}                                                                                                                                                     
[soundcloud:set] arnaldo-leandro/sets/naldo-2016: Resolving id                                                                                                            
[soundcloud:set] arnaldo-leandro/sets/naldo-2016: Downloading JSON metadata                                                                                               
[download] Downloading playlist: Naldo 2016                                                                                                                               
[soundcloud:set] playlist Naldo 2016: Collected 32 video ids (downloading 32 of them)                                                                                     
[download] Downloading video 1 of 32                                                                                                                                      
[soundcloud] gr6-explode/mc-hariel-e-mc-pedrinho-4m-no-toque-lyric-video: Resolving id                                                                                    
[soundcloud] gr6-explode/mc-hariel-e-mc-pedrinho-4m-no-toque-lyric-video: Downloading info JSON                                                                           
[soundcloud] 248777263: Downloading track url                                                                                                                             
[soundcloud] 248777263: Downloading m3u8 information                                                                                                                      
[soundcloud] 248777263: Checking download video format URL                                                                                                                
[soundcloud] 248777263: Checking hls_mp3_128_url video format URL                                                                                                         
[soundcloud] 248777263: Checking http_mp3_128_url video format URL                                                                                                        
[soundcloud] 248777263: Downloading thumbnail ...                                                                                                                         
[soundcloud] 248777263: Writing thumbnail to: MC Hariel e MC Pedrinho - 4M No Toque (Lyric Vídeo)-248777263.jpg                                                           
[debug] Invoking downloader on 'https://api.soundcloud.com/tracks/248777263/download?client_id=2t9loNQH90kzJcsFCODdigxfp325aq4z'                                          
[download] MC Hariel e MC Pedrinho - 4M No Toque (Lyric Vídeo)-248777263.mp3 has already been downloaded                                                                  
[download] 100% of 5.21MiB                                                                                                                                                
[ffmpeg] Adding metadata to 'MC Hariel e MC Pedrinho - 4M No Toque (Lyric Vídeo)-248777263.mp3'                                                                           
[debug] ffmpeg command line: ffmpeg -y -i "file:MC Hariel e MC Pedrinho - 4M No Toque (Lyric Vídeo)-248777263.mp3" -c copy -metadata "title=MC Hariel e MC Pedrinho - 4M N
o Toque (Lyric Vídeo)" -metadata "description=" -metadata "comment=" -metadata "date=20160225" -metadata "artist=GR6 EXPLODE" -metadata "purl=https://soundcloud.com/gr6-e
xplode/mc-hariel-e-mc-pedrinho-4m-no-toque-lyric-video" "file:MC Hariel e MC Pedrinho - 4M No Toque (Lyric Vídeo)-248777263.temp.mp3"                                     
[ffmpeg] Adding thumbnail to "MC Hariel e MC Pedrinho - 4M No Toque (Lyric Vídeo)-248777263.mp3"                                                                          
[debug] ffmpeg command line: ffmpeg -y -i "file:MC Hariel e MC Pedrinho - 4M No Toque (Lyric Vídeo)-248777263.mp3" -i "file:MC Hariel e MC Pedrinho - 4M No Toque (Lyric V
ídeo)-248777263.jpg" -c copy -map 0 -map 1 "-metadata:s:v" "title=\"Album cover\"" "-metadata:s:v" "comment=\"Cover (Front)\"" "file:MC Hariel e MC Pedrinho - 4M No Toque
 (Lyric Vídeo)-248777263.temp.mp3"                                                                                                                                        
ERROR: file:MC Hariel e MC Pedrinho - 4M No Toque (Lyric Vídeo)-248777263.jpg: No such file or directory                                                                  
Traceback (most recent call last):                                                                                                                                        
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp7cj3193h\build\youtube_dl\YoutubeDL.py", line 1973, in post_process                                  
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp7cj3193h\build\youtube_dl\postprocessor\embedthumbnail.py", line 50, in run                          
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp7cj3193h\build\youtube_dl\postprocessor\ffmpeg.py", line 204, in run_ffmpeg_multiple_files           
youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError: file:MC Hariel e MC Pedrinho - 4M No Toque (Lyric Vídeo)-248777263.jpg: No such file or directory               
                                                                                                                                                                          ...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
https://soundcloud.com/arnaldo-leandro/sets/naldo-2016
https://soundcloud.com/arnaldo-leandro/sets/arnaldo-leandro

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

I had try to download two soundcloud playlists that my friend has uploaded on soundcloud. I have used the switches to save the metadata and cover inside the music file. I had this sucessfully with a migrated playlist from spotify to youtube but in this case I can't do this without these errors. Sorry if someone cannot understand something that I said.

**Comment by dstftw** [comment]
Update ffmpeg.

**Comment by lucas59356** [comment]
Thank you ^^ working perfectly

2017-07-13 13:09 GMT-03:00 Sergey M. <notifications@github.com>:
