### ISSUE TITLE
ExtractorError on Linux-3.13.0-123-generic-x86_64-with-debian-jessie-sid

### ISSUE THREAD

**Issue by grcdeepak1** [rg3/youtube-dl#13652]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.07.15**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*
```
cmd: youtube-dl --format '140' --simulate --verbose --no-color --no-progress --print-json 

 Here is the command output: STDOUT:

 [debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8

 STDERR:
 [debug] User config: []
 [debug] System config: []
 [debug] Command-line args: [u'--format', u'140', u'--simulate', u'--verbose', u'--no-color', u'--no-progress', u'--print-json', u'https://www.youtube.com/watch?v=7OrLroFa0AI']
 [debug] youtube-dl version 2016.09.11.1
 ERROR: Signature extraction failed: Traceback (most recent call last):
 [debug] Python version 2.7.10 - Linux-3.13.0-123-generic-x86_64-with-debian-jessie-sid
 [debug] exe versions: none
   File "/app/vendor/bundle/ruby/2.3.0/bundler/gems/youtube-dl.rb-05cc66ae863a/vendor/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1005, in _decrypt_signature
 [debug] Proxy map: {}
 WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  (caused by ExtractorError(u"Cannot identify player u'/yts/jsbin/player-vflL_WLGI/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 Traceback (most recent call last):
     video_id, player_url, s
   File "/app/vendor/bundle/ruby/2.3.0/bundler/gems/youtube-dl.rb-05cc66ae863a/vendor/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1005, in _decrypt_signature
   File "/app/vendor/bundle/ruby/2.3.0/bundler/gems/youtube-dl.rb-05cc66ae863a/vendor/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 897, in _extract_signature_function
 ExtractorError: Cannot identify player u'/yts/jsbin/player-vflL_WLGI/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
   File "/app/vendor/bundle/ruby/2.3.0/bundler/gems/youtube-dl.rb-05cc66ae863a/vendor/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 897, in _extract_signature_function
     raise ExtractorError('Cannot identify player %r' % player_url)
 Traceback (most recent call last):
     raise ExtractorError('Cannot identify player %r' % player_url)
   File "/app/vendor/bundle/ruby/2.3.0/bundler/gems/youtube-dl.rb-05cc66ae863a/vendor/bin/youtube-dl/youtube_dl/extractor/common.py", line 347, in extract
     video_id, player_url, s
 ExtractorError: Cannot identify player u'/yts/jsbin/player-vflL_WLGI/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
     ie_result = ie.extract(url)
   File "/app/vendor/bundle/ruby/2.3.0/bundler/gems/youtube-dl.rb-05cc66ae863a/vendor/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 691, in extract_info
     return self._real_extract(url)
   File "/app/vendor/bundle/ruby/2.3.0/bundler/gems/youtube-dl.rb-05cc66ae863a/vendor/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1584, in _real_extract
     encrypted_sig, video_id, player_url, age_gate)
     'Signature extraction failed: ' + tb, cause=e)
   File "/app/vendor/bundle/ruby/2.3.0/bundler/gems/youtube-dl.rb-05cc66ae863a/vendor/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1015, in _decrypt_signature
 ExtractorError: Cannot identify player u'/yts/jsbin/player-vflL_WLGI/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 ExtractorError: Signature extraction failed: Traceback (most recent call last):
   File "/app/vendor/bundle/ruby/2.3.0/bundler/gems/youtube-dl.rb-05cc66ae863a/vendor/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1005, in _decrypt_signature
     video_id, player_url, s
   File "/app/vendor/bundle/ruby/2.3.0/bundler/gems/youtube-dl.rb-05cc66ae863a/vendor/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 897, in _extract_signature_function
 ):
 F, [2017-07-15T01:17:28.853681 #4] FATAL -- : [c3e13add-ada8-4836-bf17-d87faff0396c]
     raise ExtractorError('Cannot identify player %r' % player_url)
  (caused by ExtractorError(u"Cannot identify player u'/yts/jsbin/player-vflL_WLGI/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
<end of log>
```
---
Example:
- Single video: https://www.youtube.com/watch?v=gvdf5n-zI14
---

### Description of your *issue*, suggested solution and other information
cmd with options:
youtube-dl --format '140' --simulate --verbose --no-color --no-progress --print-json "https://www.youtube.com/watch?v=gvdf5n-zI14"
I am able to run this command successfully on  my mac (debug info below). But, when I deploy my application on Ubuntu OS (Linux-3.13.0-123-generic-x86_64-with-debian-jessie-sid) it fails with ExtractorError and above stacktrace.

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--format', u'140', u'--simulate', u'--verbose', u'--no-color', u'--no-progress', u'--print-json', u'https://www.youtube.com/watch?v=gvdf5n-zI14']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.07.09
[debug] Python version 2.7.10 - Darwin-15.5.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}

**Comment by yan12125** [comment]
> [debug] youtube-dl version 2016.09.11.1

You already know the problem :) https://github.com/layer8x/youtube-dl.rb/issues/59

**Comment by grcdeepak1** [comment]
Yes, I tried updating the bin and giving pull-request, for some reason one of my build was failing. Can someone please update the vendor/bin.
