### ISSUE TITLE
Unable to rip Twitter URLs with 2017.07.15

### ISSUE THREAD

**Issue by dprski33** [rg3/youtube-dl#13674]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.07.15*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.07.15**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
[admins@ripper-production-Aug2016 bin]$ youtube-dl -v -k -f mp4 -o '/tmp/twitter837141618239102976.mp4' https://twitter.com/sidneyking07/status/837141618239102976
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-k', u'-f', u'mp4', u'-o', u'/tmp/twitter837141618239102976.mp4', u'https://twitter.com/sidneyking07/status/837141618239102976']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.07.15
[debug] Python version 2.7.6 - Linux-3.13.0-93-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: ffmpeg N-80901-gfebc862, ffprobe N-80901-gfebc862
[debug] Proxy map: {}
[twitter] 837141618239102976: Downloading webpage
[twitter:card] 837141618239102976: Downloading webpage
[twitter:card] 837141618239102976: Downloading m3u8 information
[twitter:card] 837141618239102976: Downloading mobile webpage
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/bin/youtube-dl/youtube_dl/__init__.py", line 465, in main
  File "/usr/bin/youtube-dl/youtube_dl/__init__.py", line 455, in _real_main
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1941, in download
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 787, in extract_info
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 853, in process_ie_result
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 776, in extract_info
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 433, in extract
  File "/usr/bin/youtube-dl/youtube_dl/extractor/twitter.py", line 225, in _real_extract
  File "/usr/bin/youtube-dl/youtube_dl/extractor/twitter.py", line 144, in _extract_mobile_formats
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 634, in _download_webpage
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 531, in _download_webpage_handle
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 502, in _request_webpage
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2151, in urlopen
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/bin/youtube-dl/youtube_dl/utils.py", line 989, in http_response
IOError: CRC check failed 0xdfd9fe8 != 0x857ccdb9L
```

---

### Description of your *issue*, suggested solution and other information

Same twitter URL works correctly with 2017.07.09, but broke with 2017.07.15
Rolling back allows successful rip.

I have tried with multiple twitter urls and they all have failed for the same reason:
https://www.twitter.com/QualityJukin/status/819318078714429441 
https://www.twitter.com/paigekrill/status/682662065862012928
https://www.twitter.com/stoolive/status/800424897881186304

**Comment by dstftw** [comment]
Update python.

**Comment by dprski33** [comment]
To what version?

**Comment by dstftw** [comment]
To the latest.
