### ISSUE TITLE
please support site and6.com

### ISSUE THREAD

**Issue by CiscoPress** [rg3/youtube-dl#13714]
there is a deep link to mp4 (for example https://video.and6.com/and6.com/21699/596e91b3b4411_360p.mp4)

thanks for fantastic work

```
> youtube-dl -v 'https://www.and6.com/sex-model/Dea-21699'
[debug] System config: [u'--recode-video=mp4']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.and6.com/sex-model/Dea-21699']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.07.23
[debug] Python version 2.7.10 - Darwin-16.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2, rtmpdump 2.4
[debug] Proxy map: {'http': 'http://127.0.0.1:8118', 'https': 'http://127.0.0.1:8118'}
[generic] Dea-21699: Requesting header
WARNING: Falling back on generic information extractor.
[generic] Dea-21699: Downloading webpage
[generic] Dea-21699: Extracting information
ERROR: Unsupported URL: https://www.and6.com/sex-model/Dea-21699
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2063, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2539, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2528, in _XML
    parser.feed(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: mismatched tag: line 31, column 3
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 776, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2923, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.and6.com/sex-model/Dea-21699
```

**Comment by CiscoPress** [comment]
bump
