### ISSUE TITLE
getting "ValueError: insecure string pickle" since I updated Homebrew and youtube-dl

### ISSUE THREAD

**Issue by SuperHenkie** [rg3/youtube-dl#13717]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.07.23**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

- [x] Bug report (encountered problems with youtube-dl)

```
youtube-dl -v https://www.youtube.com/watch?v=XTvixl9d1Ec

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=XTvixl9d1Ec']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.07.23
[debug] Python version 2.7.10 - Darwin-16.6.0-x86_64-i386-64bit
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 465, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 432, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 405, in __init__
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2207, in print_debug_header
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 76, in get_versions
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 60, in __init__
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 117, in _determine_executables
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 117, in <genexpr>
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1906, in get_exe_version
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1334, in _execute_child
    child_exception = pickle.loads(data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 1382, in loads
    return Unpickler(file).load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 966, in load_string
    raise ValueError, "insecure string pickle"
ValueError: insecure string pickle
```

### Description of your *issue*, suggested solution and other information

I updated my Homebrew and ever since, whenever I try and download something with `youtube-dl` I get the above error output.

I vaguely recall Homebrew doing some Python related updates earlier today, but I can't recall exactly what. It all scrolled through my screen when doing `brew update`. 
My Homebrew seems to be OK though, everything is up to date as far as I can tell, and `brew doctor` says `Your system is ready to brew`.

Note that this problem occurs with ANY video I try to download.

**Comment by SuperHenkie** [comment]
Note: while searching for similar issues, I noticed someone suggested to rebuild `ffmpeg`. I also did that, but to no avail, the same error keeps occurring.

**Comment by dstftw** [comment]
Update python.

**Comment by SuperHenkie** [comment]
Thanks, I thought my python was fully up to date, but I now see:

`python --version` says `2.7.10`
whereas 
`brew info python` says: `python: stable 2.7.13 (bottled), HEAD`

From many different resources I see a strong recommendation NOT to mess with my main macOS' python version, but instead install a second version separately. Which I apparently have done with brew already. 

Question: how do I let youtube-dl use the more recent Python version that is installed through Homebrew, in my case v2.7.13 which resides in `/usr/local/Cellar/python/2.7.13_1` ?
(as opposed to the macOS default older python installation which is in `/usr/bin/python`)

**Comment by maxxer** [comment]
@SuperHenkie did you manage to fix it? thanks

**Comment by jomo** [comment]
Apparently youtube-dl expects python3 but doesn't explicitly require it. This worked for me:

```bash
python3 $(which youtube-dl) $args
```

Alternatively, make sure `/usr/bin/env python` gives you python3.
