### ISSUE TITLE
[WNEP.COM] News Site Support Request 

### ISSUE THREAD

**Issue by AdamDanischewski** [rg3/youtube-dl#13727]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.07.23*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ X] I've **verified** and **I assure** that I'm running youtube-dl **2017.07.23**

### Before submitting an *issue* make sure you have:
- [X ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ X] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*
---
 youtube-dl -v "http://wnep.com/2017/07/22/steampunk-fest-com" 
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'http://wnep.com/2017/07/22/steampunk-fest-comes-to-honesdale/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.07.23
[debug] Python version 2.7.6 - Linux-3.8.11-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.20-6, avprobe 9.20-6
[debug] Proxy map: {}
[generic] steampunk-fest-comes-to-honesdale: Requesting header
WARNING: Falling back on generic information extractor.
[generic] steampunk-fest-comes-to-honesdale: Downloading webpage
[generic] steampunk-fest-comes-to-honesdale: Extracting information
ERROR: Unsupported URL: http://wnep.com/2017/07/22/steampunk-fest-comes-to-honesdale/
Traceback (most recent call last):
  File "/scripthome/scripts/youtube-dl/youtube_dl/extractor/generic.py", line 2063, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/scripthome/scripts/youtube-dl/youtube_dl/compat.py", line 2539, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/scripthome/scripts/youtube-dl/youtube_dl/compat.py", line 2528, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 29, column 44
Traceback (most recent call last):
  File "/scripthome/scripts/youtube-dl/youtube_dl/YoutubeDL.py", line 776, in extract_info
    ie_result = ie.extract(url)
  File "/scripthome/scripts/youtube-dl/youtube_dl/extractor/common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "/scripthome/scripts/youtube-dl/youtube_dl/extractor/generic.py", line 2923, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://wnep.com/2017/07/22/steampunk-fest-comes-to-honesdale/

**Comment by AdamDanischewski** [comment]
It works, thanks.
