### ISSUE TITLE
Please add Watchbox.de

### ISSUE THREAD

**Issue by GeorgeHamp** [rg3/youtube-dl#13739]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.07.23*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.07.23**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.watchbox.de/serien/he-man-and-the-masters-of-the-universe-12247/staffel-1/der-kosmische-komet-328614']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.07.23
[debug] Python version 3.4.4 - Windows 10
[debug] exe versions: ffmpeg N-71883-geb9fb50, ffprobe N-71883-geb9fb50
[debug] Proxy map: {}
[generic] der-kosmische-komet-328614: Requesting header
WARNING: Falling back on generic information extractor.
[generic] der-kosmische-komet-328614: Downloading webpage
[generic] der-kosmische-komet-328614: Extracting information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://www.example.com/video123.flv'
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpu6zpd7mk\build\youtube_dl\YoutubeDL.py", line 1863, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpu6zpd7mk\build\youtube_dl\YoutubeDL.py", line 1805, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpu6zpd7mk\build\youtube_dl\downloader\common.py", line 361, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpu6zpd7mk\build\youtube_dl\downloader\http.py", line 61, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpu6zpd7mk\build\youtube_dl\YoutubeDL.py", line 2166, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.watchbox.de/serien/he-man-and-the-masters-of-the-universe-12247/staffel-1/der-kosmische-komet-328614.html
- Single video: https://www.watchbox.de/filme/free-jimmy-12325.html
- Playlist: https://www.watchbox.de/serien/he-man-and-the-masters-of-the-universe-12247/

Note: Content seems to be region-locked to German speaking areas.
Watchbox.de replaces Clipfish.de

Site seems to use MPEG-DASH

**Comment by sleeksorrow** [comment]
The site is embedding a HLS Playlist that can be played right away with mpv or vlc.

Example:
```
wget -q -O - "https://www.watchbox.de/filme/donnie-darko-14491.html" |grep hls 
            hls: 'https://vodwbusohls-a.akamaihd.net/proxy/manifest-wb-clear/at-ch-de/344218-1-28733.ism/fairplay.m3u8',
```

Hope that helps to include it! Thank you!

**Comment by themightyglider** [comment]
As far I understand it watchbox.de is the successor of clipfish.de, which already was supported by youtube-dl. I don't know if the underlying technologie has changed, but if I remember right clipfish was based on the services of akamai as well.
I guess adding support for watchbox should be trivial because of that.
On the other hand I know that on other pages based on akamai services it is now much harder to stream videos with extermal apps. Since a few weeks akamai returns an Error 403 if you try to access the m3u8 files with vlc or mplayer.
Maybe this also could cause truble with youtube-dl.

I hope this informations are helpful.

**Comment by GeorgeHamp** [comment]
Watchbox.de ist the successor of Clipfish.de, but the specs changed:
- higher bitrates
- higher resolution
- no flash required

Clipfish used .mp4-files linked in source-code, not .m3u8

**Comment by themightyglider** [comment]
So I am sure you will have to jump over the same hurdles like on other akamai based media pages.
I will check this out later but I expect that there will be any authentication process you have to pass in order to access the m3u8-file that leads to the mp4.
I'm not sure if youtube-dl can handle this. Bit if it can, it maybe could be possible to add a generic support for media pages that use akamai as underlying service.

**Comment by Risebell** [comment]
For me watchbox.de playlist downloads seem to be broken.
Example link: [https://www.watchbox.de/serien/blood-c-12633/](https://www.watchbox.de/serien/blood-c-12633/)
Output:
```
youtube-dl -v https://www.watchbox.de/serien/blood-c-12633/ 
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.watchbox.de/serien/blood-c-12633/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.11.26
[debug] Python version 3.6.3 - Linux-4.13.12-1-ARCH-x86_64-with-arch-Arch-Linux
[debug] exe versions: ffmpeg 3.4, ffprobe 3.4, rtmpdump 2.4
[debug] Proxy map: {}
[WatchBox] 12633: Downloading webpage
[WatchBox] 12633: Downloading JSON metadata
ERROR: An extractor error has occurred. (caused by KeyError('title',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 437, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/watchbox.py", line 88, in _real_extract
    compat_str) or source['title']
KeyError: 'title'
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 437, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/watchbox.py", line 88, in _real_extract
    compat_str) or source['title']
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 450, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('title',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

Single videos, like this series [first episode](https://www.watchbox.de/serien/blood-c-12633/staffel-1/der-kampf-beginnt-330536.html) seem to work fine on the other hand.
As OP's first and third example URL bring up 404 error's, I guess they might have changed there website again?

**Comment by saitho** [comment]
Watchbox is now part of TVNow. See https://www.tvnow.de/specials/watchbox.
