### ISSUE TITLE
[YouTube] Certain videos resulting in "Last message repeated 1 times"

### ISSUE THREAD

**Issue by evilarceus** [rg3/youtube-dl#13749]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.07.23*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.07.23**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

**Log 1 (normal):**
```
$ youtube-dl -f bestvideo+bestaudio --merge-output-format mp4 https://www.youtube.com/watch\?v\=CVHM7n1ONpY -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'bestvideo+bestaudio', '--merge-output-format', 'mp4', 'https://www.youtube.com/watch?v=CVHM7n1ONpY', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.07.23
[debug] Python version 3.6.1 - Linux-4.11.9-1-ARCH-x86_64-with-arch-Arch-Linux
[debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] CVHM7n1ONpY: Downloading webpage
[youtube] CVHM7n1ONpY: Downloading video info webpage
[youtube] CVHM7n1ONpY: Extracting video information
[youtube] {22} signature length 40.40, html5 player vflUtw7jb
[youtube] {43} signature length 40.40, html5 player vflUtw7jb
[youtube] {18} signature length 40.40, html5 player vflUtw7jb
[youtube] {36} signature length 40.40, html5 player vflUtw7jb
[youtube] {17} signature length 40.40, html5 player vflUtw7jb
[youtube] {137} signature length 40.40, html5 player vflUtw7jb
[youtube] {248} signature length 40.40, html5 player vflUtw7jb
[youtube] {299} signature length 40.40, html5 player vflUtw7jb
[youtube] {303} signature length 40.40, html5 player vflUtw7jb
[youtube] {136} signature length 40.40, html5 player vflUtw7jb
[youtube] {247} signature length 40.40, html5 player vflUtw7jb
[youtube] {298} signature length 40.40, html5 player vflUtw7jb
[youtube] {302} signature length 40.40, html5 player vflUtw7jb
[youtube] {135} signature length 40.40, html5 player vflUtw7jb
[youtube] {244} signature length 40.40, html5 player vflUtw7jb
[youtube] {134} signature length 40.40, html5 player vflUtw7jb
[youtube] {243} signature length 40.40, html5 player vflUtw7jb
[youtube] {133} signature length 40.40, html5 player vflUtw7jb
[youtube] {242} signature length 40.40, html5 player vflUtw7jb
[youtube] {160} signature length 40.40, html5 player vflUtw7jb
[youtube] {278} signature length 40.40, html5 player vflUtw7jb
[youtube] {140} signature length 40.40, html5 player vflUtw7jb
[youtube] {171} signature length 40.40, html5 player vflUtw7jb
[youtube] {249} signature length 40.40, html5 player vflUtw7jb
[youtube] {250} signature length 40.40, html5 player vflUtw7jb
[youtube] {251} signature length 40.40, html5 player vflUtw7jb
[youtube] CVHM7n1ONpY: Downloading MPD manifest
[debug] Invoking downloader on 'https://r3---sn-a5meknlz.googlevideo.com/videoplayback?id=0951ccee7d4e3696&itag=299&source=youtube&requiressl=yes&mn=sn-a5meknlz&mm=31&ei=aTd5Wa62HJS4-gOMwrnQCg&pl=32&ms=au&mv=m&initcwndbps=1661250&ratebypass=yes&mime=video/mp4&gir=yes&clen=45894914&lmt=1500609151507925&dur=183.916&key=dg_yt0&signature=82B3A9DB8B49A3C09ABD3AB15AD02D62C6D85EC4.8B82C8271EC3F7FA947D3654CD7269F0850C6CE0&mt=1501116179&ip=2605:e000:a79b:2800:4ecc:6aff:fe67:e5a2&ipbits=0&expire=1501137865&sparams=ip,ipbits,expire,id,itag,source,requiressl,mn,mm,ei,pl,ms,mv,initcwndbps,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: Conro - Close [Monstercat Release]-CVHM7n1ONpY.f299.mp4
[download] 100% of 43.77MiB in 00:03
[debug] Invoking downloader on 'https://r3---sn-a5mlrnel.googlevideo.com/videoplayback?itag=171&mime=audio%2Fwebm&expire=1501137865&id=o-AGcjQynsB5Mfyx9YwfqUbbPpaSWEf5SuY-S_RSUJtGa6&lmt=1500609815862232&pl=32&mv=m&clen=3152971&source=youtube&mn=sn-a5mlrnel&mm=31&keepalive=yes&key=yt6&ip=2605%3Ae000%3Aa79b%3A2800%3A4ecc%3A6aff%3Afe67%3Ae5a2&ms=au&ipbits=0&initcwndbps=1661250&gir=yes&mt=1501116179&requiressl=yes&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&dur=183.920&ei=aDd5Wc-cN4mz-gOf1rnADw&signature=7EC56DEA255FDD9EF85AC77FCFD751C5DB65DDC3.D11E7584F62C122ABE0BBD5FB3AB084D4EA0A61B&ratebypass=yes'
[download] Destination: Conro - Close [Monstercat Release]-CVHM7n1ONpY.f171.webm
[download] 100% of 3.01MiB in 00:00
[ffmpeg] Merging formats into "Conro - Close [Monstercat Release]-CVHM7n1ONpY.mp4"
[debug] ffmpeg command line: ffmpeg -y -i 'file:Conro - Close [Monstercat Release]-CVHM7n1ONpY.f299.mp4' -i 'file:Conro - Close [Monstercat Release]-CVHM7n1ONpY.f171.webm' -c copy -map 0:v:0 -map 1:a:0 'file:Conro - Close [Monstercat Release]-CVHM7n1ONpY.temp.mp4'
Deleting original file Conro - Close [Monstercat Release]-CVHM7n1ONpY.f299.mp4 (pass -k to keep)
Deleting original file Conro - Close [Monstercat Release]-CVHM7n1ONpY.f171.webm (pass -k to keep)
```
**Log 2 (bug):**
```
$ youtube-dl -f bestvideo+bestaudio --merge-output-format mp4 https://www.youtube.com/watch\?v\=QUzYHe0Htf0 -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'bestvideo+bestaudio', '--merge-output-format', 'mp4', 'https://www.youtube.com/watch?v=QUzYHe0Htf0', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.07.23
[debug] Python version 3.6.1 - Linux-4.11.9-1-ARCH-x86_64-with-arch-Arch-Linux
[debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] QUzYHe0Htf0: Downloading webpage
[youtube] QUzYHe0Htf0: Downloading video info webpage
[youtube] QUzYHe0Htf0: Extracting video information
[youtube] {22} signature length 40.40, html5 player vflUtw7jb
[youtube] {43} signature length 40.40, html5 player vflUtw7jb
[youtube] {18} signature length 40.40, html5 player vflUtw7jb
[youtube] {36} signature length 40.40, html5 player vflUtw7jb
[youtube] {17} signature length 40.40, html5 player vflUtw7jb
[youtube] {137} signature length 40.40, html5 player vflUtw7jb
[youtube] {248} signature length 40.40, html5 player vflUtw7jb
[youtube] {299} signature length 40.40, html5 player vflUtw7jb
[youtube] {303} signature length 40.40, html5 player vflUtw7jb
[youtube] {136} signature length 40.40, html5 player vflUtw7jb
[youtube] {247} signature length 40.40, html5 player vflUtw7jb
[youtube] {298} signature length 40.40, html5 player vflUtw7jb
[youtube] {302} signature length 40.40, html5 player vflUtw7jb
[youtube] {135} signature length 40.40, html5 player vflUtw7jb
[youtube] {244} signature length 40.40, html5 player vflUtw7jb
[youtube] {134} signature length 40.40, html5 player vflUtw7jb
[youtube] {243} signature length 40.40, html5 player vflUtw7jb
[youtube] {133} signature length 40.40, html5 player vflUtw7jb
[youtube] {242} signature length 40.40, html5 player vflUtw7jb
[youtube] {160} signature length 40.40, html5 player vflUtw7jb
[youtube] {278} signature length 40.40, html5 player vflUtw7jb
[youtube] {140} signature length 40.40, html5 player vflUtw7jb
[youtube] {171} signature length 40.40, html5 player vflUtw7jb
[youtube] {249} signature length 40.40, html5 player vflUtw7jb
[youtube] {250} signature length 40.40, html5 player vflUtw7jb
[youtube] {251} signature length 40.40, html5 player vflUtw7jb
[youtube] QUzYHe0Htf0: Downloading MPD manifest
[debug] Invoking downloader on 'https://r5---sn-a5mlrnel.googlevideo.com/videoplayback?lmt=1500788734391572&clen=87314497&source=youtube&mime=video%2Fwebm&itag=303&ipbits=0&expire=1501137528&gir=yes&initcwndbps=1657500&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&requiressl=yes&ei=GDZ5WY6pGNHB-AOChI_oBg&dur=195.283&keepalive=yes&ip=2605%3Ae000%3Aa79b%3A2800%3A4ecc%3A6aff%3Afe67%3Ae5a2&key=yt6&mn=sn-a5mlrnel&mm=31&ms=au&id=o-AKYNfBrMF43Gl3t5BL6oJo2lSD6RVjw6VU-uagK7w-tl&mv=m&pl=32&mt=1501115826&signature=D7425D72438C765370A7B9EB1BFFD9C33983FAB1.B0290EB35DFED2FD0695D53D0DA5D13C8F243242&ratebypass=yes'
[download] Destination: Mindsight & Duumu - What Feels Right [Monstercat Release]-QUzYHe0Htf0.f303.webm
[download] 100% of 83.27MiB in 00:06
[debug] Invoking downloader on 'https://r5---sn-a5mlrnel.googlevideo.com/videoplayback?lmt=1500788481484704&clen=3178237&source=youtube&mime=audio%2Fwebm&itag=171&ipbits=0&expire=1501137528&gir=yes&initcwndbps=1657500&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&requiressl=yes&ei=GDZ5WY6pGNHB-AOChI_oBg&dur=195.296&keepalive=yes&ip=2605%3Ae000%3Aa79b%3A2800%3A4ecc%3A6aff%3Afe67%3Ae5a2&key=yt6&mn=sn-a5mlrnel&mm=31&ms=au&id=o-AKYNfBrMF43Gl3t5BL6oJo2lSD6RVjw6VU-uagK7w-tl&mv=m&pl=32&mt=1501115826&signature=3146E90AE5FC992C149EA55ADB095B430E6174AD.6E8753A5FA8D0F0ED137854D7D65974629CAB018&ratebypass=yes'
[download] Destination: Mindsight & Duumu - What Feels Right [Monstercat Release]-QUzYHe0Htf0.f171.webm
[download] 100% of 3.03MiB in 00:00
[ffmpeg] Merging formats into "Mindsight & Duumu - What Feels Right [Monstercat Release]-QUzYHe0Htf0.mp4"
[debug] ffmpeg command line: ffmpeg -y -i 'file:Mindsight & Duumu - What Feels Right [Monstercat Release]-QUzYHe0Htf0.f303.webm' -i 'file:Mindsight & Duumu - What Feels Right [Monstercat Release]-QUzYHe0Htf0.f171.webm' -c copy -map 0:v:0 -map 1:a:0 'file:Mindsight & Duumu - What Feels Right [Monstercat Release]-QUzYHe0Htf0.temp.mp4'
ERROR:     Last message repeated 1 times
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 2002, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/lib/python3.6/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 479, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/usr/lib/python3.6/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 204, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError:     Last message repeated 1 times
```
---

### Description of your *issue*, suggested solution and other information

In the first log, everything works as usual. However, in the second log, it raises an "ERROR: Last message repeated 1 times" when attempting to merge the two files into a .mp4. I'm not entirely sure why it does this or if there's a proper solution to it.

**Working video:** https://www.youtube.com/watch?v=CVHM7n1ONpY
**Not working video:** https://www.youtube.com/watch?v=QUzYHe0Htf0

**Linux distro:** Arch Linux
**youtube-dl version:** 2017.07.23
**ffmpeg version:** 3.3.2

**Comment by dstftw** [comment]
webm can't be merged into mp4 container.

**Comment by evilarceus** [comment]
Ah, okay. I replaced ```bestvideo+bestaudio``` with  ```bestvideo[ext=mp4]+bestaudio[ext=m4a]``` and everything is working well :)

**Comment by peterwillcn** [comment]
```
[debug] ffmpeg command line: ffmpeg -y -i 'file:4K VIDEO ultrahd hdr sony 4K VIDEOS demo test nature relaxation movie for 4k oled tv-Bey4XXJAqS8.f313.webm' -i 'file:4K VIDEO ultrahd hdr sony 4K VIDEOS demo test nature relaxation movie for 4k oled tv-Bey4XXJAqS8.f251.webm' -c copy -map '0:v:0' -map '1:a:0' 'file:4K VIDEO ultrahd hdr sony 4K VIDEOS demo test nature relaxation movie for 4k oled tv-Bey4XXJAqS8.temp.mp4'
ERROR:     Last message repeated 1 times
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2051, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 506, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 232, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
FFmpegPostProcessorError:     Last message repeated 1 times
```
