### ISSUE TITLE
No Download from RMC Découverte

### ISSUE THREAD

**Issue by Ak-911** [rg3/youtube-dl#13762]
It's ok with the last version : 
youtube-dl version 2017.07.23
ok !

u can closed or delete

Hi,
I have this error  : 

_youtube-dl --verbose http://rmcdecouverte.bfmtv.com/mediaplayer-replay/?id=16542
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'http://rmcdecouverte.bfmtv.com/mediaplayer-replay/?id=16542']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.05.01
[debug] Python version 3.6.2 - Linux-4.4.78-1-MANJARO-x86_64-with-glibc2.3.4
[debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2, rtmpdump 2.4
[debug] Proxy map: {}
[RMCDecouverte] 16542: Downloading webpage
ERROR: An extractor error has occurred. (caused by KeyError('@videoPlayer',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 429, in extract
    ie_result = self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/rmcdecouverte.py", line 38, in _real_extract
    brightcove_id = compat_parse_qs(compat_urlparse.urlparse(brightcove_legacy_url).query)['@videoPlayer'][0]
KeyError: '@videoPlayer'
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 429, in extract
    ie_result = self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/rmcdecouverte.py", line 38, in _real_extract
    brightcove_id = compat_parse_qs(compat_urlparse.urlparse(brightcove_legacy_url).query)['@videoPlayer'][0]
KeyError: '@videoPlayer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 760, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 442, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('@videoPlayer',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output._
when i want download this url : 
http://rmcdecouverte.bfmtv.com/mediaplayer-replay/?id=16542&title=FIN%20DU%20MONDE%3ALE%20JOUR%20D%27APRES
Thanks if you find and correct the problem ;)

**Comment by Ak-911** [comment]
ok with last version, you can delete comment
