### ISSUE TITLE
Add Support for NBC.com American Ninja Warrior Exclusive Videos

### ISSUE THREAD

**Issue by jdunn0** [rg3/youtube-dl#13765]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.07.23*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.07.23**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v https://www.nbc.com/american-ninja-warrior/exclusives/crashing-the-course/video/3531306
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.nbc.com/american-ninja-warrior/exclusives/crashing-the-course/video/3531306']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.07.23
[debug] Python version 2.7.12 - Linux-4.4.26-gentoo-x86_64-Intel-R-_Core-TM-_i7-6700K_CPU_@_4.00GHz-with-gentoo-2.3
[debug] exe versions: ffmpeg 3.2.4, ffprobe 3.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 3531306: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 3531306: Downloading webpage
[generic] 3531306: Extracting information
ERROR: Unsupported URL: https://www.nbc.com/american-ninja-warrior/exclusives/crashing-the-course/video/3531306
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/generic.py", line 2063, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/lib64/python2.7/site-packages/youtube_dl/compat.py", line 2539, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/lib64/python2.7/site-packages/youtube_dl/compat.py", line 2528, in _XML
    parser.feed(text)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 3, column 47
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 776, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/generic.py", line 2923, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.nbc.com/american-ninja-warrior/exclusives/crashing-the-course/video/3531306
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.nbc.com/american-ninja-warrior/exclusives/crashing-the-course/video/3531306

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information
Add support for the 2017 Web Exclusive videos for American Ninja Warrior listed at https://www.nbc.com/american-ninja-warrior/exclusives/crashing-the-course.
I specifically say 2017 as the 2016 Web Exclusives at https://www.nbc.com/american-ninja-warrior-crashing-the-course are already supported by youtube-dl.

**Comment by remitamine** [comment]
for now you can use this url: http://www.nbc.com/american-ninja-warrior/video/crashing-the-course-los-angeles-presented-by-pom-wonderful/3531306.

**Comment by jdunn0** [comment]
That URL works.
I looked some more and it seems all the Web Exclusives are available under alternate URLs that are supported by using the Clips section of the page at https://www.nbc.com/american-ninja-warrior.
Though I do need to change the URLs to be HTTP instead of HTTPS to download them with youtube-dl (using HTTPS gives me the error "IndexError: list index out of range" in nbc.py line 78).

**Comment by jajajaime** [comment]
@remitamine how did you find that URL? I am experiencing the same issue but with The Good Place's The Selection exclusive.
An example video link is https://www.nbc.com/the-good-place/exclusives/the-selection/video/4027739
