### ISSUE TITLE
I used XX-Net with command 'youtube-dl --no-check-certificate "https://www.youtube.com/watch?v=fegAeph9UaA&feature=youtu.be"'

### ISSUE THREAD

**Issue by sixEdge** [rg3/youtube-dl#13768]
I used **XX-Net** with command 
`youtube-dl -v --no-check-certificate "https://www.youtube.com/watch?v=fegAeph9UaA&feature=youtu.be"`

The error (really verbose):
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--no-check-certificate', 'https://www.youtube.com/watch?v=fegAeph9UaA&feature=youtu.be']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2017.07.23
[debug] Python version 3.4.4 - Windows-10-10.0.15063
[debug] exe versions: none
[debug] Proxy map: {'http': 'http://127.0.0.1:8087', 'https': 'https://127.0.0.1:8087', 'ftp': 'ftp://127.0.0.1:8087'}
[youtube] fegAeph9UaA: Downloading webpage
[youtube] fegAeph9UaA: Downloading video info webpage
ERROR: fegAeph9UaA: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to upda
te. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpu6zpd7mk\build\youtube_dl\YoutubeDL.py", line 776, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpu6zpd7mk\build\youtube_dl\extractor\common.py", line 433, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpu6zpd7mk\build\youtube_dl\extractor\youtube.py", line 1541, in _real_extract
youtube_dl.utils.ExtractorError: fegAeph9UaA: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; ty
pe  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl/pull/13743#issuecomment-318155798
