### ISSUE TITLE
Unable to download videos from video.vice.com.

### ISSUE THREAD

**Issue by antdude** [rg3/youtube-dl#13778]
Example:

$ youtube-dl -v https://video.vice.com/en_us/video/waypoint-escaping-prison-with-dungeons-and-dragons/590203308f5eea75522614ee
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://video.vice.com/en_us/video/waypoint-escaping-prison-with-dungeons-and-dragons/590203308f5eea75522614ee']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.07.30.1
[debug] Python version 3.4.2 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.9
[debug] exe versions: ffmpeg 3.2.5-1, ffprobe 3.2.5-1, rtmpdump 2.4
[debug] Proxy map: {}
[vice] waypoint-escaping-prison-with-dungeons-and-dragons: Downloading webpage
ERROR: Unable to extract watch hub; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 776, in extract_info
    ie_result = ie.extract(url)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/vice.py", line 161, in _real_extract
    return self._extract_preplay_video(urlh.geturl(), locale, webpage)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/vice.py", line 25, in _extract_preplay_video
    r'(?s)(<watch-hub\s*.+?</watch-hub>)', webpage, 'watch hub'))
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/common.py", line 782, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract watch hub; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Thank you in advance. :)

**Comment by voltagex** [comment]
PS C:\Users\Adam\Videos> youtube-dl.exe --verbose https://video.vice.com/en_us/video/motherboard-speed-daemons-los-angeles-drag-racing/58ee471250a511f57762b8fb
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://video.vice.com/en_us/video/motherboard-speed-daemons-los-angeles-drag-racing/58ee471250a511f57762b8fb']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.09.15
[debug] Python version 3.4.4 - Windows-10-10.0.15063
[debug] exe versions: ffmpeg N-86669-gc1d1274, ffprobe N-86935-g44e9783, rtmpdump 2.4-20151223-gfa8646d-LibreSSL_2.5.4-x86_64-static
[debug] Proxy map: {}
[vice] motherboard-speed-daemons-los-angeles-drag-racing: Downloading webpage
ERROR: Unable to extract watch hub; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpl1klaw4y\build\youtube_dl\YoutubeDL.py", line 776, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpl1klaw4y\build\youtube_dl\extractor\common.py", line 434, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpl1klaw4y\build\youtube_dl\extractor\vice.py", line 162, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpl1klaw4y\build\youtube_dl\extractor\vice.py", line 26, in _extract_preplay_video
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpl1klaw4y\build\youtube_dl\extractor\common.py", line 797, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract watch hub; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete o
utput.```
```

**Comment by voltagex** [comment]
I found the m3u8 by inspecting traffic: https://content-auso1.uplynk.com/7a62751d55c3460da708e914f3d6ef70/g.m3u8?pbs=bf399b6d7bef4787ae752c72144dcb0e. youtube-dl is able to grab that directly, ffmpeg uses crypto+https to download it.

**Comment by ahmedtds** [comment]
I'm getting exact same error. Will this be fixed?
