### ISSUE TITLE
[teamfourstar] Error when downloading (site has switched players)

### ISSUE THREAD

**Issue by Chariblaze** [rg3/youtube-dl#13782]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.07.30.1**
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)

```
youtube-dl -v http://teamfourstar.com/dragon-ball-z-abridged-episode-59-the-hard-cell/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['http://teamfourstar.com/dragon-ball-z-abridged-episode-59-the-hard-cell/', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.07.30.1
[debug] Python version 3.4.4 - Windows-10-10.0.15063
[debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2, rtmpdump 2.3
[debug] Proxy map: {}
[TeamFourStar] dragon-ball-z-abridged-episode-59-the-hard-cell: Downloading webpage
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpfdfxmx88\build\youtube_dl\__init__.py", line 465, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpfdfxmx88\build\youtube_dl\__init__.py", line 455, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpfdfxmx88\build\youtube_dl\YoutubeDL.py", line 1956, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpfdfxmx88\build\youtube_dl\YoutubeDL.py", line 787, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpfdfxmx88\build\youtube_dl\YoutubeDL.py", line 831, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpfdfxmx88\build\youtube_dl\utils.py", line 541, in sanitize_url
AttributeError: 'NoneType' object has no attribute 'startswith'
```
---

- Single video: http://teamfourstar.com/dragon-ball-z-abridged-episode-59-the-hard-cell/
- Another: http://teamfourstar.com/tfs-abridged-parody-episode-1-2/

---

Extractor: https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/teamfourstar.py

The extractor worked when the site was using the Screenwave player or JW Platform or whatever, but now it uses Vidme. The Vidme link is in the source of the video pages, and that downloads fine: https://vid.me/e/f8aw?stats=1

**Comment by Chariblaze** [comment]
Since the site is just using Vidme embeds now, it is easy enough to click the Vidme logo on the player and get the URL from there. That makes the teamfourstar extractor less necessary, so maybe it should be removed altogether?
