### ISSUE TITLE
MPEG-DASH, No video formats found 

### ISSUE THREAD

**Issue by troych** [rg3/youtube-dl#13791]
- [x] Bug report (encountered problems with youtube-dl)

I'm trying to download an MPEG-DASH livestream, having trouble making it work though. Any idea where the problem is? Not sure if it's geo restricted, if you can't get the .mpd manifest I've included the contents further down.

Log:
```
youtube-dl -v "https://xtendx17tc-a.akamaihd.net/smsla-m10-tc/_definst_/ngrp:765/4041/57419/f834a38f3e97d758092f1aff6c566651_all/manifest.mpd?sid=1501516774514"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://xtendx17tc-a.akamaihd.net/smsla-m10-tc/_definst_/ngrp:765/4041/57419/f834a38f3e97d758092f1aff6c566651_all/manifest.mpd?sid=1501516774514']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.07.30.1
[debug] Python version 2.7.9 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.8
[debug] exe versions: ffmpeg 3.2.5-1, ffprobe 3.2.5-1
[debug] Proxy map: {}
[generic] manifest: Requesting header
WARNING: Falling back on generic information extractor.
[generic] manifest: Downloading webpage
[generic] manifest: Extracting information
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 776, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2095, in _real_extract
    self._sort_formats(info_dict['formats'])
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 1056, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

DASH Manifest:

```
<?xml version="1.0" encoding="UTF-8"?>
<MPD xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xmlns="urn:mpeg:dash:schema:mpd:2011"
     xmlns:xlink="http://www.w3.org/1999/xlink"
     xsi:schemaLocation="urn:mpeg:DASH:schema:MPD:2011 http://standards.iso.org/ittf/PubliclyAvailableStandards/MPEG-DASH_schema_files/DASH-MPD.xsd"
     profiles="urn:mpeg:dash:profile:isoff-live:2011"
     type="dynamic"
     minimumUpdatePeriod="PT1.927S" 
     publishTime="2017-07-31T16:01:18Z" 
     availabilityStartTime="2017-07-30T17:02:15Z" 
     timeShiftBufferDepth="PT12.0S"
     suggestedPresentationDelay="PT4.0S" 
     minBufferTime="PT6.0S">
<ProgramInformation>
    <Title>765/4041/57419/f834a38f3e97d758092f1aff6c566651_all</Title>
</ProgramInformation>
<Period id="0" start="PT0.0S">
    <AdaptationSet id="0" group="1" mimeType="video/mp4" maxWidth="1920" maxHeight="1080" par="16:9" frameRate="25" segmentAlignment="true" startWithSAP="1" subsegmentAlignment="true" subsegmentStartsWithSAP="1">
        <SegmentTemplate timescale="90000" media="chunk_u8rsy42it_ctvideo_cfm4s_rid$RepresentationID$_cs$Time$_mpd.m4s" initialization="chunk_u8rsy42it_ctvideo_cfm4s_rid$RepresentationID$_cinit_mpd.m4s">
            <SegmentTimeline>
                <S t="7445700000" d="180000"/>
                <S d="180000"/>
                <S d="180000"/>
                <S d="180000"/>
                <S d="180000"/>
                <S d="180000"/>
            </SegmentTimeline>
        </SegmentTemplate>
        <Representation id="p0va0br4096000" codecs="avc1.4d4028" width="1920" height="1080" sar="1:1" bandwidth="4096000" />
        <Representation id="p0va0br2500000" codecs="avc1.428029" width="1280" height="720" sar="1:1" bandwidth="2500000" />
        <Representation id="p0va0br1250000" codecs="avc1.428020" width="854" height="480" sar="1:1" bandwidth="1250000" />
    </AdaptationSet>
    <AdaptationSet id="1" group="2" mimeType="audio/mp4" lang="eng" segmentAlignment="true" startWithSAP="1" subsegmentAlignment="true" subsegmentStartsWithSAP="1">
        <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
        <SegmentTemplate timescale="48000" media="chunk_u8rsy42it_ctaudio_cfm4s_rid$RepresentationID$_cs$Time$_mpd.m4s" initialization="chunk_u8rsy42it_ctaudio_cfm4s_rid$RepresentationID$_cinit_mpd.m4s">
            <SegmentTimeline>
                <S t="3971040192" d="96240"/>
                <S d="96240"/>
                <S d="96288"/>
                <S d="95232"/>
                <S d="96240"/>
                <S d="96240"/>
            </SegmentTimeline>
        </SegmentTemplate>
        <Representation id="p0aa0br196608" codecs="mp4a.40.2" audioSamplingRate="48000" bandwidth="196608">
        </Representation>
    </AdaptationSet>
</Period>
<UTCTiming schemeIdUri="urn:mpeg:dash:utc:direct:2014" value="2017-07-31T16:01:18Z"/>
</MPD>

```

**Comment by dstftw** [comment]
DASH live streams are not supported.
