### ISSUE TITLE
HBO-GO, No video formats found

### ISSUE THREAD

**Issue by john745** [rg3/youtube-dl#13813]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.07.30.1*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.07.30.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not pplicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
D:\Software\youtube-dl>youtube-dl.exe -v "https://l3edvpsbbp04.secure.footprint.net/B60695706HD_11EPRSS10C/B60695706HD_11EPRSS10C_w9.ism/Manifest" --cookies "D:\hbo\ff-cookies"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://l3edvpsbbp04.secure.footprint.net/B60695706HD_11EPRSS10C/B60695706HD_11EPRSS10C_w9.ism/Manifest', '--cookies', 'D:\\hbo\\ff-cookies']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.07.30.1
[debug] Python version 3.4.4 - Windows-10-10.0.15063
[debug] exe versions: ffmpeg 3.0, rtmpdump 2.3
[debug] Proxy map: {}
[generic] Manifest: Requesting header
WARNING: Falling back on generic information extractor.
[generic] Manifest: Downloading webpage
[generic] Manifest: Extracting information
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpfdfxmx88\build\youtube_dl\YoutubeDL.py", line 776, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpfdfxmx88\build\youtube_dl\extractor\common.py", line 433, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpfdfxmx88\build\youtube_dl\extractor\generic.py", line 2082, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpfdfxmx88\build\youtube_dl\extractor\common.py", line 1056, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpfdfxmx88\build\youtube_dl\YoutubeDL.py", line 776, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpfdfxmx88\build\youtube_dl\extractor\common.py", line 433, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpfdfxmx88\build\youtube_dl\extractor\generic.py", line 2082, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpfdfxmx88\build\youtube_dl\extractor\common.py", line 1056, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpfdfxmx88\build\youtube_dl\__init__.py", line 455, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpfdfxmx88\build\youtube_dl\YoutubeDL.py", line 1956, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpfdfxmx88\build\youtube_dl\YoutubeDL.py", line 799, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpfdfxmx88\build\youtube_dl\YoutubeDL.py", line 604, in report_error
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpfdfxmx88\build\youtube_dl\YoutubeDL.py", line 574, in trouble
youtube_dl.utils.DownloadError: ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpfdfxmx88\build\youtube_dl\__init__.py", line 465, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpfdfxmx88\build\youtube_dl\__init__.py", line 458, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpfdfxmx88\build\youtube_dl\YoutubeDL.py", line 545, in __exit__
  File "C:\Python\Python34\lib\http\cookiejar.py", line 2068, in save
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\hbo\\ff-cookies'
```

---

So guys, I'm trying to download a video from HBO GO, but I think I'm doing something wrong. I have my cable provider credentials and I'm able to watch it with no problems. I managed to find the manifest file containing all of the fragments of the video, but yt-dl doesn't seem to recognize it. Can anyone help me.
P.S.: I live in Brazil and use HBO GO Brazil, and I don't know if it works in a different way compared to the American HBO GO.
Thanks in advance.

**Comment by dstftw** [comment]
DRM not supported.
