### ISSUE TITLE
ERROR: Unable to extract SAML Login URL

### ISSUE THREAD

**Issue by streammonkey** [rg3/youtube-dl#13848]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.08.06*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2017.08.06**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['http://www.sproutonline.com/watch/birthday-kapow', '--ap-mso', 'Verizon', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp65001, pref cp1252
[debug] youtube-dl version 2017.08.06
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: rtmpdump 2.4
[debug] Proxy map: {}
[Sprout] birthday-kapow: Downloading webpage
[Sprout] Z__2_gm4__Pp: Downloading Provider Redirect Page
[Sprout] Z__2_gm4__Pp: Downloading SAML Login Page
ERROR: Unable to extract SAML Login URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube
-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpdfgr210e\build\youtube_dl\YoutubeDL.py", line 776, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpdfgr210e\build\youtube_dl\extractor\common.py", line 433, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpdfgr210e\build\youtube_dl\extractor\sprout.py", line 43, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpdfgr210e\build\youtube_dl\extractor\adobepass.py", line 1482, in _extract_mvpd_au
th
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpdfgr210e\build\youtube_dl\extractor\common.py", line 782, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract SAML Login URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the
 latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
...
<end of log>
```

---

### Description of your *issue*, suggested solution and other information

The issue presents on several different computers using either a Verizon or a Comcast login. 

I have verified that the credentials and syntax are correct and the video from that page plays fine in the browser after logging in.

The same issue presents on other websites as well, e.g. http://www.aetv.com/shows/intervention/season-16/episode-1

Thank you for any help you can provide.

**Comment by SkiTheSlicer** [comment]
https://github.com/rg3/youtube-dl/pull/14363 should address some, if not all, of these issues if/when it gets merged. I was able to retrieve that episode from AETV (http://www.aetv.com/shows/intervention/season-16/episode-1). However, I couldn't successfully test Sprout because it's not included in my subscription package, though my error changed from:

```
[Sprout] birthday-kapow: Downloading webpage
[Sprout] Z__2_gm4__Pp: Downloading Provider Redirect Page
[Sprout] Z__2_gm4__Pp: Downloading SAML Login Page
ERROR: Unable to extract SAML Login URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the
 latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and
 include its complete output.
```

to:

```
[Sprout] birthday-kapow: Downloading webpage
[Sprout] Z__2_gm4__Pp: Downloading Provider Redirect Page
[Sprout] Z__2_gm4__Pp: Downloading SAML Login Page
[Sprout] Z__2_gm4__Pp: Logging in
[Sprout] Z__2_gm4__Pp: Downloading SAML Response
ERROR: An extractor error has occurred. (caused by KeyError(u'targetValue',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

which to means seems to be a good sign.
