### ISSUE TITLE
Getting a strange error youtube-dl/ytdl-core

### ISSUE THREAD

**Issue by godleydemon** [rg3/youtube-dl#13854]
```javascript
[21:40:45] { Error: Command failed: /home/athena/node_modules/youtube-dl/bin/youtube-dl --dump-json -f best --no-warnings https://r7---sn-q4f7snsk.googlevide
o.com/videoplayback?expire=1502091637&lmt=1500405114427482&mime=audio%2Fwebm&gir=yes&requiressl=yes&keepalive=yes&clen=5217877&source=youtube&signature=5AF0D
8A281B3906530DB2A766A77E1F7FC336EBA.68345327EFF6A2D68FE42DA18C956B90F99E8036&key=yt6&ei=FcWHWb3HCoHOuwXBxLGQDg&ipbits=0&id=o-AKcJF-Skg8f8fRU4PXGE-oRRGWOzfU76
h7Jvi4PRRdVf&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2C
expire&ms=au&itag=251&initcwndbps=1566250&dur=323.201&mv=m&mt=1502069977&pl=17&mn=sn-q4f7snsk&mm=31&ip=70.121.137.80&ratebypass=yes
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/athena/node_modules/youtube-dl/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/home/athena/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/__init__.py", line 465, in main
  File "/home/athena/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/__init__.py", line 455, in _real_main
  File "/home/athena/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1956, in download
  File "/home/athena/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 787, in extract_info
  File "/home/athena/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 848, in process_ie_result
  File "/home/athena/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 787, in extract_info
  File "/home/athena/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 841, in process_ie_result
  File "/home/athena/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1544, in process_video_result
IndexError: list index out of range

    at ChildProcess.exithandler (child_process.js:198:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:891:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/home/athena/node_modules/youtube-dl/bin/youtube-dl --dump-json -f best --no-warnings https://r7---sn-q4f7snsk.googlevideo.com/videoplayback?expire=1502091637&lmt=1500405114427482&mime=audio%2Fwebm&gir=yes&requiressl=yes&keepalive=yes&clen=5217877&source=youtube&signature=5AF0D8A281B3906530DB2A766A77E1F7FC336EBA.68345327EFF6A2D68FE42DA18C956B90F99E8036&key=yt6&ei=FcWHWb3HCoHOuwXBxLGQDg&ipbits=0&id=o-AKcJF-Skg8f8fRU4PXGE-oRRGWOzfU76h7Jvi4PRRdVf&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&ms=au&itag=251&initcwndbps=1566250&dur=323.201&mv=m&mt=1502069977&pl=17&mn=sn-q4f7snsk&mm=31&ip=70.121.137.80&ratebypass=yes' }
```

Not quite sure what it causing this, and not really sure what else to give you guys in the direction. As this error is bizarre to me.

getting this when trying to run straight through youtube-dl
https://hastebin.com/memizekuri.pl

**Comment by dstftw** [comment]
1. Issues with 3rdparty software should be addressed to 3rdparties.
2. https://github.com/rg3/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command.
3. youtube-dl should not be called on URLs returned by `--get-url`.

**Comment by godleydemon** [comment]
wait what? I don't understand at all what your referring to. This is how I've always done it and this is the first time I'm having issues with it. I'm not 100% sure even where to look for the issues on why this is occurring as it's returning a 403.

**Comment by dstftw** [comment]
As said **you should not** call it on URL obtained with `--get-url`. Even if you do you must call it with from [**the same IP, with the same cookies and headers**](https://github.com/rg3/youtube-dl#i-extracted-a-video-url-with--g-but-it-does-not-play-on-another-machine--in-my-web-browser).
