### ISSUE TITLE
Wrong handeling of YouTube start time arguments

### ISSUE THREAD

**Issue by fbruetting** [rg3/youtube-dl#13862]
• I'm running youtube-dl **2017.07.23**, which is not that far behind. I don’t want to reinstall it and I don’t have the time to read thousand lines of readme or bugs. Delete or consider my bug report. I’m happy to help, but I won’t waste my time – overviewing and deleting it takes you just a few seconds, if it’s inappropriate.

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [x] Feature request (request for a new functionality) [depends on if this behaviour isn’t supported yet]

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

```
$ youtube-dl -v https://www.youtube.com/watch?time_continue=229&v=mzPtI0yog0A -x
[1] 19369
bash: -x: Command not found...
$ [debug] System config: ['--prefer-free-formats']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?time_continue=229']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.07.23
[debug] Python version 3.6.2 - Linux-4.11.11-300.fc26.x86_64-x86_64-with-fedora-26-Twenty_Six
[debug] exe versions: ffmpeg 3.3.3, ffprobe 3.3.3
[debug] Proxy map: {}
[generic] watch?time_continue=229: Requesting header
[redirect] Following redirect to https://www.youtube.com/
[generic] www.youtube: Requesting header
WARNING: Falling back on generic information extractor.
[generic] www.youtube: Downloading webpage
[generic] www.youtube: Extracting information
ERROR: Unsupported URL: https://www.youtube.com/
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 775, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/generic.py", line 2923, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.youtube.com/
```

or

```
$ youtube-dl -vx https://www.youtube.com/watch?time_continue=229&v=mzPtI0yog0A
[1] 19448
$ [debug] System config: ['--prefer-free-formats']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-vx', 'https://www.youtube.com/watch?time_continue=229']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.07.23
[debug] Python version 3.6.2 - Linux-4.11.11-300.fc26.x86_64-x86_64-with-fedora-26-Twenty_Six
[debug] exe versions: ffmpeg 3.3.3, ffprobe 3.3.3
[debug] Proxy map: {}
[generic] watch?time_continue=229: Requesting header
[redirect] Following redirect to https://www.youtube.com/
[generic] www.youtube: Requesting header
WARNING: Falling back on generic information extractor.
[generic] www.youtube: Downloading webpage
[generic] www.youtube: Extracting information
ERROR: Unsupported URL: https://www.youtube.com/
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 775, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/generic.py", line 2923, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.youtube.com/
```

### Description of your *issue*, suggested solution and other information

When a start time is given, there should be a notification about the given start time (for the case if this is not clear to the user) and it should then either be ignored (if unsupported), or cut appropriately after download (of this could be done). At the moment, this leads to total misbehaviour, since URL arguments aren’t respected, filtered or exceptioned appropriately.

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command

**Comment by fbruetting** [comment]
Ah, thanks! :)
If there is some possibility to detect this, this would be great!
