### ISSUE TITLE
Mixcloud failed to parse json

### ISSUE THREAD

**Issue by kabachook** [rg3/youtube-dl#13867]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.08.06*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.08.06**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
### Log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.mixcloud.com/union77radio/noir-12-04-2016-quatri%C3%A8me/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.08.06
[debug] Python version 3.6.2 - Linux-4.10.8-docker-1-x86_64-with
[debug] exe versions: none
[debug] Proxy map: {}
[mixcloud] union77radio-noir-12-04-2016-quatrième: Downloading webpage
ERROR: union77radio-noir-12-04-2016-quatrième: Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 676, in _parse_json
    return json.loads(json_string)
  File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 676, in _parse_json
    return json.loads(json_string)
  File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 776, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/extractor/mixcloud.py", line 82, in _real_extract
    self._decrypt_play_info(encrypted_play_info), track_id)
  File "/usr/local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 680, in _parse_json
    raise ExtractorError(errmsg, cause=ve)
youtube_dl.utils.ExtractorError: union77radio-noir-12-04-2016-quatrième: Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

---

### Description of your *issue*, suggested solution and other information
When downloading from Mixcloud json parser error occurs

**Comment by AndyRubio** [comment]
It looks like the decryption of the JSON contained in ``encrypted-play_info`` isn't working but the key ``pleasedontdownloadourmusictheartistswontgetpaid`` is still present in https://www.mixcloud.com/media/js2/www_js_2.js

**Comment by kabachook** [comment]
Probably connected with this js code that decrypt m-play-info contains
```js
 function v(e, t) {
                var n, o, r = "pleasedontdownloadourmusictheartistswontgetpaid", i = r.length, a = 0, l = [];
                for (!t && f.player.value && (r = f.player.value,
                i = r.length),
                o = atob(e),
                n = o.length; n > a; a++)
                    l[a] = o.charCodeAt(a) ^ r.charCodeAt(a % i);
                var c = String.fromCharCode.apply(String, l);
                try {
                    return JSON.parse(c)
                } catch (s) {
                    if (t)
                        throw s;
                    return v(e, !0)
                }
```

**Comment by AndyRubio** [comment]
The key ``pleasedontdownloadourmusictheartistswontgetpaid`` hasn't altered since yesterday when mixcloud was downloadable.

**Comment by kabachook** [comment]
It works in only browser for me. I run youtube-dl in a debugger and got wrongly decrypted string but code seems to be ok

**Comment by kabachook** [comment]
[UPDATE]
Key value now is `(function() { return new Date().toLocaleDateString(); })()`

**Comment by kabachook** [comment]
Test passed
```
python test\test_download.py TestDownload.test_Mixcloud
[mixcloud] dholbach-cryptkeeper: Downloading webpage
[info] Writing video description metadata as JSON to: test_Mixcloud_dholbach-cryptkeeper.info.json
[debug] Invoking downloader on 'https://stream5.mixcloud.com/c/m4a/64/6/f/c/d/d610-b93d-40e5-9086-d731038019d9.m4a'
[download] Destination: test_Mixcloud_dholbach-cryptkeeper.m4a
[download] 100% of 10.00KiB in 00:00
.
----------------------------------------------------------------------
Ran 1 test in 2.407s

OK
```
New to github, need some help about how to make a pull request

**Comment by AndyRubio** [comment]
What value does the key value have for you? ``new Date().toLocaleDateString()`` resolves to ``09/08/2017`` for me (I'm in the UK), my tests are still failing. I've tried different variations ...

**Comment by kabachook** [comment]
It's a string

**Comment by AndyRubio** [comment]
Thanks - yep saw it on the fix. Good work!
