### ISSUE TITLE
Support videos from Google Photos

### ISSUE THREAD

**Issue by jcsalomon** [rg3/youtube-dl#13889]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.08.09**
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
C:\Users\Chesky\Downloads\Temp> youtube-dl -v https://goo.gl/photos/tMFzthXCku9jyzaY9
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://goo.gl/photos/tMFzthXCku9jyzaY9']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.08.09
[debug] Python version 3.4.4 - Windows-10-10.0.15063
[debug] exe versions: ffmpeg N-83657-g7e4f32f, ffprobe N-83657-g7e4f32f
[debug] Proxy map: {}
[generic] tMFzthXCku9jyzaY9: Requesting header
[redirect] Following redirect to https://photos.google.com/share/AF1QipO9WO5MnYm7850JgwAl7DIvRzbCoEcJamtywXL-oQ49rwF3K1frOSK63fjYD5MD-A?key=ZEV4S3RmYXd0bWNzQjRfQ09KQlBud1M4OUU1RzZn
[generic] AF1QipO9WO5MnYm7850JgwAl7DIvRzbCoEcJamtywXL-oQ49rwF3K1frOSK63fjYD5MD-A?key=ZEV4S3RmYXd0bWNzQjRfQ09KQlBud1M4OUU1RzZn: Requesting header
WARNING: Falling back on generic information extractor.
[generic] AF1QipO9WO5MnYm7850JgwAl7DIvRzbCoEcJamtywXL-oQ49rwF3K1frOSK63fjYD5MD-A?key=ZEV4S3RmYXd0bWNzQjRfQ09KQlBud1M4OUU1RzZn: Downloading webpage
[generic] AF1QipO9WO5MnYm7850JgwAl7DIvRzbCoEcJamtywXL-oQ49rwF3K1frOSK63fjYD5MD-A?key=ZEV4S3RmYXd0bWNzQjRfQ09KQlBud1M4OUU1RzZn: Extracting information
ERROR: Unsupported URL: https://photos.google.com/share/AF1QipO9WO5MnYm7850JgwAl7DIvRzbCoEcJamtywXL-oQ49rwF3K1frOSK63fjYD5MD-A?key=ZEV4S3RmYXd0bWNzQjRfQ09KQlBud1M4OUU1RzZn
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpf7t6lw0k\build\youtube_dl\YoutubeDL.py", line 776, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpf7t6lw0k\build\youtube_dl\extractor\common.py", line 433, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpf7t6lw0k\build\youtube_dl\extractor\generic.py", line 2944, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://photos.google.com/share/AF1QipO9WO5MnYm7850JgwAl7DIvRzbCoEcJamtywXL-oQ49rwF3K1frOSK63fjYD5MD-A?key=ZEV4S3RmYXd0bWNzQjRfQ09KQlBud1M4OUU1RzZn
```

```
C:\Users\Chesky\Downloads\Temp> youtube-dl -v https://photos.google.com/share/AF1QipO9WO5MnYm7850JgwAl7DIvRzbCoEcJamtywX
L-oQ49rwF3K1frOSK63fjYD5MD-A/photo/AF1QipPRvvdy6-3EOqSACtJb7Q8QfmlXN4d4MwX5ico8?key=ZEV4S3RmYXd0bWNzQjRfQ09KQlBud1M4OUU1
RzZn
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://photos.google.com/share/AF1QipO9WO5MnYm7850JgwAl7DIvRzbCoEcJamtywXL-oQ49rwF3K1frOSK63fjYD5MD-A/photo/AF1QipPRvvdy6-3EOqSACtJb7Q8QfmlXN4d4MwX5ico8?key=ZEV4S3RmYXd0bWNzQjRfQ09KQlBud1M4OUU1RzZn']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.08.09
[debug] Python version 3.4.4 - Windows-10-10.0.15063
[debug] exe versions: ffmpeg N-83657-g7e4f32f, ffprobe N-83657-g7e4f32f
[debug] Proxy map: {}
[generic] AF1QipPRvvdy6-3EOqSACtJb7Q8QfmlXN4d4MwX5ico8?key=ZEV4S3RmYXd0bWNzQjRfQ09KQlBud1M4OUU1RzZn: Requesting header
WARNING: Falling back on generic information extractor.
[generic] AF1QipPRvvdy6-3EOqSACtJb7Q8QfmlXN4d4MwX5ico8?key=ZEV4S3RmYXd0bWNzQjRfQ09KQlBud1M4OUU1RzZn: Downloading webpage
[generic] AF1QipPRvvdy6-3EOqSACtJb7Q8QfmlXN4d4MwX5ico8?key=ZEV4S3RmYXd0bWNzQjRfQ09KQlBud1M4OUU1RzZn: Extracting information
ERROR: Unsupported URL: https://photos.google.com/share/AF1QipO9WO5MnYm7850JgwAl7DIvRzbCoEcJamtywXL-oQ49rwF3K1frOSK63fjYD5MD-A/photo/AF1QipPRvvdy6-3EOqSACtJb7Q8QfmlXN4d4MwX5ico8?key=ZEV4S3RmYXd0bWNzQjRfQ09KQlBud1M4OUU1RzZn
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpf7t6lw0k\build\youtube_dl\YoutubeDL.py", line 776, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpf7t6lw0k\build\youtube_dl\extractor\common.py", line 433, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpf7t6lw0k\build\youtube_dl\extractor\generic.py", line 2944, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://photos.google.com/share/AF1QipO9WO5MnYm7850JgwAl7DIvRzbCoEcJamtywXL-oQ49rwF3K1frOSK63fjYD5MD-A/photo/AF1QipPRvvdy6-3EOqSACtJb7Q8QfmlXN4d4MwX5ico8?key=ZEV4S3RmYXd0bWNzQjRfQ09KQlBud1M4OUU1RzZn
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://photos.google.com/share/AF1QipO9WO5MnYm7850JgwAl7DIvRzbCoEcJamtywXL-oQ49rwF3K1frOSK63fjYD5MD-A/photo/AF1QipPRvvdy6-3EOqSACtJb7Q8QfmlXN4d4MwX5ico8?key=ZEV4S3RmYXd0bWNzQjRfQ09KQlBud1M4OUU1RzZn
- Playlist: https://goo.gl/photos/tMFzthXCku9jyzaY9, which expands to
- Playlist: https://photos.google.com/share/AF1QipO9WO5MnYm7850JgwAl7DIvRzbCoEcJamtywXL-oQ49rwF3K1frOSK63fjYD5MD-A?key=ZEV4S3RmYXd0bWNzQjRfQ09KQlBud1M4OUU1RzZn

---

### Description of your *issue*, suggested solution and other information

I’ve created a “shared album” on Google Photos, permissions set so anyone with the URL should be able to view the contents. I’d like to be able to download a video from such an album, preferably by using the short album URL as a playlist.

**Comment by tokune** [comment]
see my fork https://github.com/tokune/youtube-dl
the single video should work

**Comment by hahuy** [comment]
please support google photos

**Comment by soredake** [comment]
@tokune can you pls create pull request?

**Comment by niranjanshr13** [comment]
use this for now.
```
#!/usr/bin/env python3
import requests
link = 'https://photos.google.com/share/AF1QipO9WO5MnYm7850JgwAl7DIvRzbCoEcJamtywXL-oQ49rwF3K1frOSK63fjYD5MD-A/photo/AF1QipPRvvdy6-3EOqSACtJb7Q8QfmlXN4d4MwX5ico8?key=ZEV4S3RmYXd0bWNzQjRfQ09KQlBud1M4OUU1RzZn'
r = requests.get(link).text
for x in r.split('\n'):
    if 'video-downloads.googleusercontent.com' in x:
        v = x.split('"')[1]
        print(v)
```

**Comment by ihsudg** [comment]
Hello, why is this the ticket still been open for 3 years? I have tested and it works.

**Comment by eGit** [comment]
I also just tested it with 

1. a single shared Google Photos video URL 
2. a shared Google Photos album URL

both don't work.

**Comment by myns23** [comment]
any update

**Comment by Raprodent** [comment]
Please keep this updated!

**Comment by 89z** [comment]
None of the links on this page are valid, so it will be hard to fix this, even if someone wanted to. If you wish for this to be fixed, you should provide a valid example URL.

**Comment by Raprodent** [comment]
https://photos.app.goo.gl/oyzdm7G1LXjpDaBU7

**Comment by Raprodent** [comment]
or this one https://photos.app.goo.gl/hbvncnNATND4Uqpb8
