### ISSUE TITLE
Tudou/Youku Channel Support 

### ISSUE THREAD

**Issue by dkl3** [rg3/youtube-dl#13896]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.08.09*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.08.09**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

**Tudou:**

~$ youtube-dl  http://id.tudou.com/i/UMTE2NzI5MDI4/videos -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['http://id.tudou.com/i/UMTE2NzI5MDI4/videos', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.08.09
[debug] Python version 3.4.5 - Linux-3.10.0-514.26.1.el7.x86_64-x86_64-with-centos-7.3.1611-Core
[debug] exe versions: ffmpeg 2.6.8, ffprobe 2.6.8
[debug] Proxy map: {}
[generic] videos: Requesting header
WARNING: Falling back on generic information extractor.
[generic] videos: Downloading webpage
[generic] videos: Extracting information
ERROR: Unsupported URL: http://id.tudou.com/i/UMTE2NzI5MDI4/videos
Traceback (most recent call last):
  File "/home/gazlene/.local/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 776, in extract_info
    ie_result = ie.extract(url)
  File "/home/gazlene/.local/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "/home/gazlene/.local/lib/python3.4/site-packages/youtube_dl/extractor/generic.py", line 2944, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: http://id.tudou.com/i/UMTE2NzI5MDI4/videos

**Youku:**
youtube-dl  http://i.youku.com/i/UNzY4NDMy/videos -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['http://i.youku.com/i/UNzY4NDMy/videos', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.08.09
[debug] Python version 3.4.5 - Linux-3.10.0-514.26.1.el7.x86_64-x86_64-with-centos-7.3.1611-Core
[debug] exe versions: ffmpeg 2.6.8, ffprobe 2.6.8
[debug] Proxy map: {}
[generic] videos: Requesting header
WARNING: Falling back on generic information extractor.
[generic] videos: Downloading webpage
[generic] videos: Extracting information
ERROR: Unsupported URL: http://i.youku.com/i/UNzY4NDMy/videos
Traceback (most recent call last):
  File "/home/gazlene/.local/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 776, in extract_info
    ie_result = ie.extract(url)
  File "/home/gazlene/.local/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "/home/gazlene/.local/lib/python3.4/site-packages/youtube_dl/extractor/generic.py", line 2944, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: http://i.youku.com/i/UNzY4NDMy/videos

---

### Description of your *issue*, suggested solution and other information

Is there a way to support the download of Tudou and Youku channels? I'm an archivist, and i upload channels to Internet Archive (archive.org). There have been a couple i've been trying to archive, and if youtube channel support was implemented, then Youku/Tudou should be no problem. thank you. :)

**Comment by yan12125** [comment]
Related: #10626
