### ISSUE TITLE
[mixcloud] Failed to parse JSON

### ISSUE THREAD

**Issue by funwhilelost** [rg3/youtube-dl#13905]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.08.09**
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--extract-audio', '--audio-format=mp3', 'https://www.mixcloud.com/zedsdead/zeds-dead-diplo-friends-mix-2016/', '--verbose']

[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.08.09
[debug] Python version 3.4.4 - Windows-8.1-6.3.9600
[debug] exe versions: ffmpeg 2.8.4, ffprobe 3.3.2
[debug] Proxy map: {}
[mixcloud] zedsdead-zeds-dead-diplo-friends-mix-2016: Downloading webpage
ERROR: zedsdead-zeds-dead-diplo-friends-mix-2016: Failed to parse JSON  (caused by ValueError('Expecting value: line 1 column 1 (char 0)',)); please rep
ort this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with th
e --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpf7t6lw0k\build\youtube_dl\extractor\common.py", line 676, in _parse_json
  File "C:\Python\Python34\lib\json\__init__.py", line 318, in loads
  File "C:\Python\Python34\lib\json\decoder.py", line 343, in decode
  File "C:\Python\Python34\lib\json\decoder.py", line 361, in raw_decode
ValueError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpf7t6lw0k\build\youtube_dl\extractor\common.py", line 676, in _parse_json
  File "C:\Python\Python34\lib\json\__init__.py", line 318, in loads
  File "C:\Python\Python34\lib\json\decoder.py", line 343, in decode
  File "C:\Python\Python34\lib\json\decoder.py", line 361, in raw_decode
ValueError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpf7t6lw0k\build\youtube_dl\YoutubeDL.py", line 776, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpf7t6lw0k\build\youtube_dl\extractor\common.py", line 433, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpf7t6lw0k\build\youtube_dl\extractor\mixcloud.py", line 89, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpf7t6lw0k\build\youtube_dl\extractor\mixcloud.py", line 69, in _decrypt_play_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpf7t6lw0k\build\youtube_dl\extractor\common.py", line 680, in _parse_json
youtube_dl.utils.ExtractorError: zedsdead-zeds-dead-diplo-friends-mix-2016: Failed to parse JSON  (caused by ValueError('Expecting value: line 1 column
1 (char 0)',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure
to call youtube-dl with the --verbose flag and include its complete output.
```

Certain Mixcloud shows are failing to download with a JSON parsing error.  In this case the example URL is https://www.mixcloud.com/zedsdead/zeds-dead-diplo-friends-mix-2016

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [this FAQ entry](https://yt-dl.org/update) if you have troubles updating.

**Comment by funwhilelost** [comment]
Well it was current when I filed it and it continues to fail in 8.13
