### ISSUE TITLE
[mixcloud] Failed to parse JSON

### ISSUE THREAD

**Issue by mbunkus** [rg3/youtube-dl#13922]
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.08.13**
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Bug report (encountered problems with youtube-dl)

Downloading from Mixcloud fails with an exception in the JSON parser. Download works neither with valid login credentials nor without credentials.

There's currently no open issue related to "mixcloud" or "JSON" that matches my problem.

Here's the full output with `--verbose` directly after downloading 2017.08.13:

```
0 mosu@sweet-chili ~/dl] ./youtube-dl --verbose https://www.mixcloud.com/JazzStandard/jazz-beats-and-flow-004-alfa-mist/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.mixcloud.com/JazzStandard/jazz-beats-and-flow-004-alfa-mist/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.08.13
[debug] Python version 3.6.2 - Linux-4.12.6-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 3.3.3, ffprobe 3.3.3, rtmpdump 2.4
[debug] Proxy map: {}
[mixcloud] JazzStandard-jazz-beats-and-flow-004-alfa-mist: Downloading webpage
ERROR: JazzStandard-jazz-beats-and-flow-004-alfa-mist: Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/extractor/common.py", line 676, in _parse_json
    return json.loads(json_string)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/extractor/common.py", line 676, in _parse_json
    return json.loads(json_string)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 776, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/mixcloud.py", line 90, in _real_extract
    play_info = self._decrypt_play_info(encrypted_play_info, track_id)
  File "./youtube-dl/youtube_dl/extractor/mixcloud.py", line 70, in _decrypt_play_info
    video_id)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 680, in _parse_json
    raise ExtractorError(errmsg, cause=ve)
youtube_dl.utils.ExtractorError: JazzStandard-jazz-beats-and-flow-004-alfa-mist: Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by dstftw** [comment]
Already fixed.
