### ISSUE TITLE
[mixcloud] Failed to parse JSON 

### ISSUE THREAD

**Issue by funwhilelost** [rg3/youtube-dl#13939]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.08.13*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.08.13**
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--extract-audio', '--audio-format=mp3', 'https://www.mixcloud.com/zedsdead/zeds-dead-diplo-friends-mix-2016',
 '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.08.13
[debug] Python version 3.4.4 - Windows-8.1-6.3.9600
[debug] exe versions: ffmpeg 2.8.4, ffprobe 3.3.2
[debug] Proxy map: {}
[mixcloud] zedsdead-zeds-dead-diplo-friends-mix-2016: Downloading webpage
ERROR: zedsdead-zeds-dead-diplo-friends-mix-2016: Failed to parse JSON  (caused by ValueError('Expecting value: line 1 column 1 (char 0)',
)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sur
e to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc3a66tbr\build\youtube_dl\extractor\common.py", line 676, in _parse_j
son
  File "C:\Python\Python34\lib\json\__init__.py", line 318, in loads
  File "C:\Python\Python34\lib\json\decoder.py", line 343, in decode
  File "C:\Python\Python34\lib\json\decoder.py", line 361, in raw_decode
ValueError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc3a66tbr\build\youtube_dl\extractor\common.py", line 676, in _parse_j
son
  File "C:\Python\Python34\lib\json\__init__.py", line 318, in loads
  File "C:\Python\Python34\lib\json\decoder.py", line 343, in decode
  File "C:\Python\Python34\lib\json\decoder.py", line 361, in raw_decode
ValueError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc3a66tbr\build\youtube_dl\YoutubeDL.py", line 776, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc3a66tbr\build\youtube_dl\extractor\common.py", line 433, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc3a66tbr\build\youtube_dl\extractor\mixcloud.py", line 90, in _real_e
xtract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc3a66tbr\build\youtube_dl\extractor\mixcloud.py", line 70, in _decryp
t_play_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc3a66tbr\build\youtube_dl\extractor\common.py", line 680, in _parse_j
son
youtube_dl.utils.ExtractorError: zedsdead-zeds-dead-diplo-friends-mix-2016: Failed to parse JSON  (caused by ValueError('Expecting value:
line 1 column 1 (char 0)',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtub
e-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

---

### Description of your *issue*, suggested solution and other information

When trying to download this sound file it is throwing an exception while parsing JSON for the file.  I had another issue for this but it was closed for using an outdated version - which it wasn't.  I've updated to 8.13 and it continues to happen.  @dstftw made a change (da20951a57bddd4a0102cd776ff93a2adc6db77d) three days ago but it's not available through the self updater yet.

**Comment by dstftw** [comment]
It's not yet released.

**Comment by funwhilelost** [comment]
@dstftw - verified it's working against `master` - thanks so much for your help on this project.  :1st_place_medal:
