### ISSUE TITLE
[arte.tv:+7] If video is not available anymore, provide a properly error message

### ISSUE THREAD

**Issue by andreygursky** [rg3/youtube-dl#13945]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.08.13*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.08.13**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.arte.tv/de/videos/030273-563-A/arte-reportage']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.08.13
[debug] Python version 2.7.13 - Linux-4.11.0-2-amd64-x86_64-with-debian-9.0
[debug] exe versions: ffmpeg 3.2.4-1, ffprobe 3.2.4-1, rtmpdump 2.4
[debug] Proxy map: {}
[arte.tv:+7] arte-reportage: Downloading webpage
[arte.tv:+7] arte-reportage: Downloading JSON metadata
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/andrey/progs/youtube-dl/__main__.py", line 19, in <module>
  File "/home/andrey/progs/youtube-dl/youtube_dl/__init__.py", line 465, in main
  File "/home/andrey/progs/youtube-dl/youtube_dl/__init__.py", line 455, in _real_main
  File "/home/andrey/progs/youtube-dl/youtube_dl/YoutubeDL.py", line 1956, in download
  File "/home/andrey/progs/youtube-dl/youtube_dl/YoutubeDL.py", line 776, in extract_info
  File "/home/andrey/progs/youtube-dl/youtube_dl/extractor/common.py", line 433, in extract
  File "/home/andrey/progs/youtube-dl/youtube_dl/extractor/arte.py", line 203, in _real_extract
  File "/home/andrey/progs/youtube-dl/youtube_dl/extractor/arte.py", line 246, in _extract_from_webpage
  File "/home/andrey/progs/youtube-dl/youtube_dl/extractor/arte.py", line 110, in _extract_from_json_url
AttributeError: 'list' object has no attribute 'items'
```

---

### Description of your *issue*, suggested solution and other information

Such bug has been reported but closed by its reporter: https://github.com/rg3/youtube-dl/issues/13289. Actually, if a video is not available anymore, youtube-dl should not stop with an exception in its source code. Please print a properly error message instead: like "cannot find a download link (video is likely not available anymore)".

**Comment by andreygursky** [comment]
@dstftw, thanks for the fast fix.
