### ISSUE TITLE
Unable to extract video ids

### ISSUE THREAD

**Issue by bcassid** [rg3/youtube-dl#13967]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.08.18*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ ] I've **verified** and **I assure** that I'm running youtube-dl **2017.08.18**

### Before submitting an *issue* make sure you have:
- [ ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
2017-08-19 10:16:12.412 MVRP[7664:583909] MVRP 1.0.5
2017-08-19 10:16:29.173 MVRP[7664:583909] downloadUrl: https://www.facebook.com/delfina.ochoa1/videos/1557199590986494/ ripMode: 0
2017-08-19 10:16:29.179 MVRP[7664:583909] s: https://www.facebook.com/delfina.ochoa1/videos/1557199590986494/ d: /Users/bcassidy/Desktop
2017-08-19 10:16:29.184 MVRP[7664:585413] time since last update check: 6527459
2017-08-19 10:16:29.184 MVRP[7664:585413] updating tool...
Updating to version 2017.08.18 ...
Updated youtube-dl. Restart youtube-dl to use the new version.
2017-08-19 10:16:34.969 MVRP[7664:583909] osv 10.12.6
2017-08-19 10:16:34.969 MVRP[7664:583909] task env: {
    "Apple_PubSub_Socket_Render" = "/private/tmp/com.apple.launchd.jKTZC4rxAd/Render";
    HOME = "/Users/bcassidy";
    LOGNAME = bcassidy;
    PATH = "/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Mac VideoRipper Pro.app/Contents/Resources";
    SHELL = "/bin/bash";
    "SSH_AUTH_SOCK" = "/private/tmp/com.apple.launchd.Dv5Sp5FO7X/Listeners";
    TMPDIR = "/var/folders/6c/_hkfgkwd6fn137r21jkxvs480000gp/T/";
    USER = bcassidy;
    "XPC_FLAGS" = 0x0;
    "XPC_SERVICE_NAME" = "com.mvrp.MVRP.27380";
    "__CF_USER_TEXT_ENCODING" = "0x1F6:0x0:0x0";
}
2017-08-19 10:16:34.969 MVRP[7664:583909] launching task 0x618000087260
2017-08-19 10:16:34.970 MVRP[7664:583909] task 0x618000087260 launched
2017-08-19 10:16:35.701 MVRP[7664:583909] <ERROR 0x618000087260> [debug] System config: []
2017-08-19 10:16:35.701 MVRP[7664:583909] <ERROR 0x618000087260> [debug] User config: []
2017-08-19 10:16:35.701 MVRP[7664:583909] <ERROR 0x618000087260> [debug] Custom config: []
2017-08-19 10:16:35.701 MVRP[7664:583909] <ERROR 0x618000087260> 
2017-08-19 10:16:35.701 MVRP[7664:583909] <ERROR 0x618000087260> [debug] Command-line args: [u'--ignore-config', u'--no-color', u'--no-call-home', u'--newline', u'--verbose', u'--no-playlist', u'--prefer-ffmpeg', u'--ffmpeg-location', u'/Applications/Mac VideoRipper Pro.app/Contents/Resources/ffmpeg', u'--merge-output-format', u'mp4', u'-f', u'best[height=1080][ext=mp4]/bestvideo[height<=1080][vcodec!=vp9]+bestaudio[ext=m4a]/best[height<=1080][ext=mp4]/best', u'--recode-video', u'mp4', u'https://www.facebook.com/delfina.ochoa1/videos/1557199590986494/']
2017-08-19 10:16:35.701 MVRP[7664:583909] <ERROR 0x618000087260> 
2017-08-19 10:16:35.707 MVRP[7664:583909] <ERROR 0x618000087260> [debug] Encodings: locale US-ASCII, fs utf-8, out None, pref US-ASCII
2017-08-19 10:16:35.707 MVRP[7664:583909] <ERROR 0x618000087260> [debug] youtube-dl version 2017.08.18
2017-08-19 10:16:35.707 MVRP[7664:583909] <ERROR 0x618000087260> 
2017-08-19 10:16:35.750 MVRP[7664:583909] <ERROR 0x618000087260> [debug] Python version 2.7.10 - Darwin-16.7.0-x86_64-i386-64bit
2017-08-19 10:16:35.750 MVRP[7664:583909] <ERROR 0x618000087260> 
2017-08-19 10:16:35.907 MVRP[7664:583909] <ERROR 0x618000087260> [debug] exe versions: ffmpeg 3.2.2-tessus, ffprobe 3.2.2-tessus, rtmpdump 2.4
2017-08-19 10:16:35.907 MVRP[7664:583909] <ERROR 0x618000087260> [debug] Proxy map: {}
2017-08-19 10:16:35.907 MVRP[7664:583909] <ERROR 0x618000087260> 
2017-08-19 10:16:36.106 MVRP[7664:583909] <OUTPUT 0x618000087260> [facebook] 1557199590986494: Downloading webpage
2017-08-19 10:16:36.106 MVRP[7664:583909] <OUTPUT 0x618000087260> 
2017-08-19 10:16:36.436 MVRP[7664:583909] <OUTPUT 0x618000087260> [facebook] 1557199590986494: Downloading webpage
2017-08-19 10:16:36.436 MVRP[7664:583909] <OUTPUT 0x618000087260> 
2017-08-19 10:16:36.724 MVRP[7664:583909] <ERROR 0x618000087260> ERROR: This video is only available for registered users. Use --username and --password or --netrc to provide account credentials.
2017-08-19 10:16:36.724 MVRP[7664:583909] <ERROR 0x618000087260> 
2017-08-19 10:16:36.735 MVRP[7664:583909] <ERROR 0x618000087260> Traceback (most recent call last):
2017-08-19 10:16:36.736 MVRP[7664:583909] <ERROR 0x618000087260>   File "/var/folders/6c/_hkfgkwd6fn137r21jkxvs480000gp/T/mvrp.dX6YV4/youtube_dl/YoutubeDL.py", line 776, in extract_info
2017-08-19 10:16:36.736 MVRP[7664:583909] <ERROR 0x618000087260>     ie_result = ie.extract(url)
2017-08-19 10:16:36.736 MVRP[7664:583909] <ERROR 0x618000087260>   File "/var/folders/6c/_hkfgkwd6fn137r21jkxvs480000gp/T/mvrp.dX6YV4/youtube_dl/extractor/common.py", line 433, in extract
2017-08-19 10:16:36.736 MVRP[7664:583909] <ERROR 0x618000087260>     ie_result = self._real_extract(url)
2017-08-19 10:16:36.736 MVRP[7664:583909] <ERROR 0x618000087260>   File "/var/folders/6c/_hkfgkwd6fn137r21jkxvs480000gp/T/mvrp.dX6YV4/youtube_dl/extractor/facebook.py", line 412, in _real_extract
2017-08-19 10:16:36.736 MVRP[7664:583909] <ERROR 0x618000087260>     video_id, fatal_if_no_video=True)
2017-08-19 10:16:36.736 MVRP[7664:583909] <ERROR 0x618000087260>   File "/var/folders/6c/_hkfgkwd6fn137r21jkxvs480000gp/T/mvrp.dX6YV4/youtube_dl/extractor/facebook.py", line 327, in _extract_from_url
2017-08-19 10:16:36.736 MVRP[7664:583909] <ERROR 0x618000087260>     self.raise_login_required()
2017-08-19 10:16:36.736 MVRP[7664:583909] <ERROR 0x618000087260>   File "/var/folders/6c/_hkfgkwd6fn137r21jkxvs480000gp/T/mvrp.dX6YV4/youtube_dl/extractor/common.py", line 713, in raise_login_required
2017-08-19 10:16:36.736 MVRP[7664:583909] <ERROR 0x618000087260>     expected=True)
2017-08-19 10:16:36.736 MVRP[7664:583909] <ERROR 0x618000087260> ExtractorError: This video is only available for registered users. Use --username and --password or --netrc to provide account credentials.
2017-08-19 10:16:36.736 MVRP[7664:583909] <ERROR 0x618000087260> 
2017-08-19 10:16:36.736 MVRP[7664:583909] <ERROR 0x618000087260> 
2017-08-19 10:16:36.752 MVRP[7664:583920] task 0x618000087260 done
2017-08-19 10:18:34.544 MVRP[7664:583909] downloadUrl: https://www.facebook.com/delfina.ochoa1/videos/1557199590986494/ ripMode: 0
2017-08-19 10:18:34.545 MVRP[7664:583909] s: https://www.facebook.com/delfina.ochoa1/videos/1557199590986494/ d: /Users/bcassidy/Desktop
2017-08-19 10:18:34.546 MVRP[7664:589824] time since last update check: 120
2017-08-19 10:18:34.849 MVRP[7664:583909] osv 10.12.6
2017-08-19 10:18:34.849 MVRP[7664:583909] task env: {
    "Apple_PubSub_Socket_Render" = "/private/tmp/com.apple.launchd.jKTZC4rxAd/Render";
    HOME = "/Users/bcassidy";
    LOGNAME = bcassidy;
    PATH = "/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Mac VideoRipper Pro.app/Contents/Resources";
    SHELL = "/bin/bash";
    "SSH_AUTH_SOCK" = "/private/tmp/com.apple.launchd.Dv5Sp5FO7X/Listeners";
    TMPDIR = "/var/folders/6c/_hkfgkwd6fn137r21jkxvs480000gp/T/";
    USER = bcassidy;
    "XPC_FLAGS" = 0x0;
    "XPC_SERVICE_NAME" = "com.mvrp.MVRP.27380";
    "__CF_USER_TEXT_ENCODING" = "0x1F6:0x0:0x0";
}
2017-08-19 10:18:34.849 MVRP[7664:583909] launching task 0x618000090b80
2017-08-19 10:18:34.856 MVRP[7664:583909] task 0x618000090b80 launched
2017-08-19 10:18:35.583 MVRP[7664:583909] <ERROR 0x618000090b80> [debug] System config: []
2017-08-19 10:18:35.583 MVRP[7664:583909] <ERROR 0x618000090b80> [debug] User config: []
2017-08-19 10:18:35.584 MVRP[7664:583909] <ERROR 0x618000090b80> [debug] Custom config: []
2017-08-19 10:18:35.584 MVRP[7664:583909] <ERROR 0x618000090b80> 
2017-08-19 10:18:35.584 MVRP[7664:583909] <ERROR 0x618000090b80> [debug] Command-line args: [u'--ignore-config', u'--no-color', u'--no-call-home', u'--newline', u'--verbose', u'--no-playlist', u'--prefer-ffmpeg', u'--ffmpeg-location', u'/Applications/Mac VideoRipper Pro.app/Contents/Resources/ffmpeg', u'--merge-output-format', u'mp4', u'-f', u'best[height=1080][ext=mp4]/bestvideo[height<=1080][vcodec!=vp9]+bestaudio[ext=m4a]/best[height<=1080][ext=mp4]/best', u'--recode-video', u'mp4', u'https://www.facebook.com/delfina.ochoa1/videos/1557199590986494/']
2017-08-19 10:18:35.584 MVRP[7664:583909] <ERROR 0x618000090b80> 
2017-08-19 10:18:35.590 MVRP[7664:583909] <ERROR 0x618000090b80> [debug] Encodings: locale US-ASCII, fs utf-8, out None, pref US-ASCII
2017-08-19 10:18:35.590 MVRP[7664:583909] <ERROR 0x618000090b80> [debug] youtube-dl version 2017.08.18
2017-08-19 10:18:35.590 MVRP[7664:583909] <ERROR 0x618000090b80> 
2017-08-19 10:18:35.604 MVRP[7664:583909] <ERROR 0x618000090b80> [debug] Python version 2.7.10 - Darwin-16.7.0-x86_64-i386-64bit
2017-08-19 10:18:35.604 MVRP[7664:583909] <ERROR 0x618000090b80> 
2017-08-19 10:18:35.664 MVRP[7664:583909] <ERROR 0x618000090b80> [debug] exe versions: ffmpeg 3.2.2-tessus, ffprobe 3.2.2-tessus, rtmpdump 2.4
2017-08-19 10:18:35.664 MVRP[7664:583909] <ERROR 0x618000090b80> [debug] Proxy map: {}
2017-08-19 10:18:35.664 MVRP[7664:583909] <ERROR 0x618000090b80> 
2017-08-19 10:18:35.855 MVRP[7664:583909] <OUTPUT 0x618000090b80> [facebook] 1557199590986494: Downloading webpage
2017-08-19 10:18:35.855 MVRP[7664:583909] <OUTPUT 0x618000090b80> 
2017-08-19 10:18:36.113 MVRP[7664:583909] <OUTPUT 0x618000090b80> [facebook] 1557199590986494: Downloading webpage
2017-08-19 10:18:36.113 MVRP[7664:583909] <OUTPUT 0x618000090b80> 
2017-08-19 10:18:36.346 MVRP[7664:583909] <ERROR 0x618000090b80> ERROR: This video is only available for registered users. Use --username and --password or --netrc to provide account credentials.
2017-08-19 10:18:36.346 MVRP[7664:583909] <ERROR 0x618000090b80> 
2017-08-19 10:18:36.349 MVRP[7664:583909] <ERROR 0x618000090b80> Traceback (most recent call last):
2017-08-19 10:18:36.349 MVRP[7664:583909] <ERROR 0x618000090b80>   File "/var/folders/6c/_hkfgkwd6fn137r21jkxvs480000gp/T/mvrp.3NApJp/youtube_dl/YoutubeDL.py", line 776, in extract_info
2017-08-19 10:18:36.349 MVRP[7664:583909] <ERROR 0x618000090b80>     ie_result = ie.extract(url)
2017-08-19 10:18:36.349 MVRP[7664:583909] <ERROR 0x618000090b80>   File "/var/folders/6c/_hkfgkwd6fn137r21jkxvs480000gp/T/mvrp.3NApJp/youtube_dl/extractor/common.py", line 433, in extract
2017-08-19 10:18:36.350 MVRP[7664:583909] <ERROR 0x618000090b80>     ie_result = self._real_extract(url)
2017-08-19 10:18:36.350 MVRP[7664:583909] <ERROR 0x618000090b80>   File "/var/folders/6c/_hkfgkwd6fn137r21jkxvs480000gp/T/mvrp.3NApJp/youtube_dl/extractor/facebook.py", line 412, in _real_extract
2017-08-19 10:18:36.350 MVRP[7664:583909] <ERROR 0x618000090b80>     video_id, fatal_if_no_video=True)
2017-08-19 10:18:36.350 MVRP[7664:583909] <ERROR 0x618000090b80>   File "/var/folders/6c/_hkfgkwd6fn137r21jkxvs480000gp/T/mvrp.3NApJp/youtube_dl/extractor/facebook.py", line 327, in _extract_from_url
2017-08-19 10:18:36.350 MVRP[7664:583909] <ERROR 0x618000090b80>     self.raise_login_required()
2017-08-19 10:18:36.350 MVRP[7664:583909] <ERROR 0x618000090b80>   File "/var/folders/6c/_hkfgkwd6fn137r21jkxvs480000gp/T/mvrp.3NApJp/youtube_dl/extractor/common.py", line 713, in raise_login_required
2017-08-19 10:18:36.350 MVRP[7664:583909] <ERROR 0x618000090b80>     expected=True)
2017-08-19 10:18:36.350 MVRP[7664:583909] <ERROR 0x618000090b80> ExtractorError: This video is only available for registered users. Use --username and --password or --netrc to provide account credentials.
2017-08-19 10:18:36.350 MVRP[7664:583909] <ERROR 0x618000090b80> 
2017-08-19 10:18:36.350 MVRP[7664:583909] <ERROR 0x618000090b80> 
2017-08-19 10:18:36.373 MVRP[7664:589522] task 0x618000090b80 done
2017-08-19 10:44:30.222 MVRP[7664:583909] downloadUrl: https://www.facebook.com/delfina.ochoa1/posts/1557199620986491?from_close_friend=1&notif_t=close_friend_activity&notif_id=1503110772110122 ripMode: 0
2017-08-19 10:44:30.229 MVRP[7664:583909] s: https://www.facebook.com/delfina.ochoa1/posts/1557199620986491?from_close_friend=1&notif_t=close_friend_activity&notif_id=1503110772110122 d: /Users/bcassidy/Desktop
2017-08-19 10:44:30.231 MVRP[7664:620777] time since last update check: 1675
2017-08-19 10:44:30.544 MVRP[7664:583909] osv 10.12.6
2017-08-19 10:44:30.544 MVRP[7664:583909] task env: {
    "Apple_PubSub_Socket_Render" = "/private/tmp/com.apple.launchd.jKTZC4rxAd/Render";
    HOME = "/Users/bcassidy";
    LOGNAME = bcassidy;
    PATH = "/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Mac VideoRipper Pro.app/Contents/Resources";
    SHELL = "/bin/bash";
    "SSH_AUTH_SOCK" = "/private/tmp/com.apple.launchd.Dv5Sp5FO7X/Listeners";
    TMPDIR = "/var/folders/6c/_hkfgkwd6fn137r21jkxvs480000gp/T/";
    USER = bcassidy;
    "XPC_FLAGS" = 0x0;
    "XPC_SERVICE_NAME" = "com.mvrp.MVRP.27380";
    "__CF_USER_TEXT_ENCODING" = "0x1F6:0x0:0x0";
}
2017-08-19 10:44:30.544 MVRP[7664:583909] launching task 0x6080000896f0
2017-08-19 10:44:30.553 MVRP[7664:583909] task 0x6080000896f0 launched
2017-08-19 10:44:31.505 MVRP[7664:583909] <ERROR 0x6080000896f0> [debug] System config: []
2017-08-19 10:44:31.506 MVRP[7664:583909] <ERROR 0x6080000896f0> [debug] User config: []
2017-08-19 10:44:31.506 MVRP[7664:583909] <ERROR 0x6080000896f0> [debug] Custom config: []
2017-08-19 10:44:31.506 MVRP[7664:583909] <ERROR 0x6080000896f0> 
2017-08-19 10:44:31.506 MVRP[7664:583909] <ERROR 0x6080000896f0> [debug] Command-line args: [u'--ignore-config', u'--no-color', u'--no-call-home', u'--newline', u'--verbose', u'--no-playlist', u'--prefer-ffmpeg', u'--ffmpeg-location', u'/Applications/Mac VideoRipper Pro.app/Contents/Resources/ffmpeg', u'--merge-output-format', u'mp4', u'-f', u'best[height=1080][ext=mp4]/bestvideo[height<=1080][vcodec!=vp9]+bestaudio[ext=m4a]/best[height<=1080][ext=mp4]/best', u'--recode-video', u'mp4', u'https://www.facebook.com/delfina.ochoa1/posts/1557199620986491?from_close_friend=1&notif_t=close_friend_activity&notif_id=1503110772110122']
2017-08-19 10:44:31.506 MVRP[7664:583909] <ERROR 0x6080000896f0> 
2017-08-19 10:44:31.513 MVRP[7664:583909] <ERROR 0x6080000896f0> [debug] Encodings: locale US-ASCII, fs utf-8, out None, pref US-ASCII
2017-08-19 10:44:31.513 MVRP[7664:583909] <ERROR 0x6080000896f0> [debug] youtube-dl version 2017.08.18
2017-08-19 10:44:31.513 MVRP[7664:583909] <ERROR 0x6080000896f0> 
2017-08-19 10:44:31.553 MVRP[7664:583909] <ERROR 0x6080000896f0> [debug] Python version 2.7.10 - Darwin-16.7.0-x86_64-i386-64bit
2017-08-19 10:44:31.553 MVRP[7664:583909] <ERROR 0x6080000896f0> 
2017-08-19 10:44:31.665 MVRP[7664:583909] <ERROR 0x6080000896f0> [debug] exe versions: ffmpeg 3.2.2-tessus, ffprobe 3.2.2-tessus, rtmpdump 2.4
2017-08-19 10:44:31.665 MVRP[7664:583909] <ERROR 0x6080000896f0> [debug] Proxy map: {}
2017-08-19 10:44:31.665 MVRP[7664:583909] <ERROR 0x6080000896f0> 
2017-08-19 10:44:31.861 MVRP[7664:583909] <OUTPUT 0x6080000896f0> [facebook] 1557199620986491: Downloading webpage
2017-08-19 10:44:31.861 MVRP[7664:583909] <OUTPUT 0x6080000896f0> 
2017-08-19 10:44:32.189 MVRP[7664:583909] <ERROR 0x6080000896f0> ERROR: Unable to extract video ids; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
2017-08-19 10:44:32.189 MVRP[7664:583909] <ERROR 0x6080000896f0> 
2017-08-19 10:44:32.192 MVRP[7664:583909] <ERROR 0x6080000896f0> Traceback (most recent call last):
2017-08-19 10:44:32.192 MVRP[7664:583909] <ERROR 0x6080000896f0>   File "/var/folders/6c/_hkfgkwd6fn137r21jkxvs480000gp/T/mvrp.atKPAV/youtube_dl/YoutubeDL.py", line 776, in extract_info
2017-08-19 10:44:32.192 MVRP[7664:583909] <ERROR 0x6080000896f0>     ie_result = ie.extract(url)
2017-08-19 10:44:32.192 MVRP[7664:583909] <ERROR 0x6080000896f0>   File "/var/folders/6c/_hkfgkwd6fn137r21jkxvs480000gp/T/mvrp.atKPAV/youtube_dl/extractor/common.py", line 433, in extract
2017-08-19 10:44:32.193 MVRP[7664:583909] <ERROR 0x6080000896f0>     ie_result = self._real_extract(url)
2017-08-19 10:44:32.193 MVRP[7664:583909] <ERROR 0x6080000896f0>   File "/var/folders/6c/_hkfgkwd6fn137r21jkxvs480000gp/T/mvrp.atKPAV/youtube_dl/extractor/facebook.py", line 405, in _real_extract
2017-08-19 10:44:32.193 MVRP[7664:583909] <ERROR 0x6080000896f0>     webpage, 'video ids', group='ids'),
2017-08-19 10:44:32.193 MVRP[7664:583909] <ERROR 0x6080000896f0>   File "/var/folders/6c/_hkfgkwd6fn137r21jkxvs480000gp/T/mvrp.atKPAV/youtube_dl/extractor/common.py", line 782, in _search_regex
2017-08-19 10:44:32.193 MVRP[7664:583909] <ERROR 0x6080000896f0>     raise RegexNotFoundError('Unable to extract %s' % _name)
2017-08-19 10:44:32.193 MVRP[7664:583909] <ERROR 0x6080000896f0> RegexNotFoundError: Unable to extract video ids; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
2017-08-19 10:44:32.193 MVRP[7664:583909] <ERROR 0x6080000896f0> 
2017-08-19 10:44:32.193 MVRP[7664:583909] <ERROR 0x6080000896f0> 
2017-08-19 10:44:32.218 MVRP[7664:620379] task 0x6080000896f0 done
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

**Comment by dstftw** [comment]
None of these available in browser either.
