### ISSUE TITLE
More problems with Disney -- New spiderman

### ISSUE THREAD

**Issue by keybounce** [rg3/youtube-dl#14008]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.08.23*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2017.08.23**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
keybounceMBP:Disney michael$ ./yt-dl -v http://watchdisneyxd.go.com/marvels-spiderman-collection
[debug] System config: []
[debug] User config: ['-k', '--hls-prefer-native', '-o', '%(series)s/s%(season_number)02d-e%(episode_number)02d-%(title)s.%(ext)s', '-f', '\nbest[ext=mp4][height>431][height<=576]/\nbestvideo[ext=mp4][height=480]+bestaudio[ext=m4a]/\nbest[ext=mp4][height>340][height<=431]/\nbestvideo[ext=mp4][height>360][height<=576]+bestaudio/\nbest[height>340][height<=576]/\nbestvideo[height>360][height<=576]+bestaudio/\nbestvideo[height=360]+bestaudio/\nbest[ext=mp4][height>=280][height<=360]/\nbest[height<=576]/\nworst', '--ap-mso', 'Dish', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '--write-sub', '--write-auto-sub', '--sub-lang', 'en,enUS,en-us', '--sub-format', 'ass/srt/best', '--convert-subs', 'ass', '--embed-subs', '--mark-watched', '--download-archive', 'downloaded-videos.txt']
[debug] Custom config: []
[debug] Command-line args: ['--hls-prefer-native', '-o', '%(series)s/s%(season_number)02d-e%(episode_number)02d-%(title)s.%(ext)s', '-v', 'http://watchdisneyxd.go.com/marvels-spiderman-collection']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.08.23
[debug] Python version 3.6.2 - Darwin-13.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.3.3, ffprobe 3.3.3, rtmpdump 2.4
[debug] Proxy map: {}
[Go] marvels-spiderman-collection: Downloading webpage
ERROR: Unable to extract show id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/Users/michael/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 776, in extract_info
    ie_result = ie.extract(url)
  File "/Users/michael/bin/youtube-dl/youtube_dl/extractor/common.py", line 434, in extract
    ie_result = self._real_extract(url)
  File "/Users/michael/bin/youtube-dl/youtube_dl/extractor/go.py", line 86, in _real_extract
    show_id = self._search_regex(r'data-show-id=["\']*(SH\d+)', webpage, 'show id')
  File "/Users/michael/bin/youtube-dl/youtube_dl/extractor/common.py", line 797, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract show id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

keybounceMBP:Disney michael$ ./yt-dl -v http://watchdisneyxd.go.com/marvels-spiderman-collection/video/vdka401
4812/01/01-horizon-high-part-one
[debug] System config: []
[debug] User config: ['-k', '--hls-prefer-native', '-o', '%(series)s/s%(season_number)02d-e%(episode_number)02d-%(title)s.%(ext)s', '-f', '\nbest[ext=mp4][height>431][height<=576]/\nbestvideo[ext=mp4][height=480]+bestaudio[ext=m4a]/\nbest[ext=mp4][height>340][height<=431]/\nbestvideo[ext=mp4][height>360][height<=576]+bestaudio/\nbest[height>340][height<=576]/\nbestvideo[height>360][height<=576]+bestaudio/\nbestvideo[height=360]+bestaudio/\nbest[ext=mp4][height>=280][height<=360]/\nbest[height<=576]/\nworst', '--ap-mso', 'Dish', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '--write-sub', '--write-auto-sub', '--sub-lang', 'en,enUS,en-us', '--sub-format', 'ass/srt/best', '--convert-subs', 'ass', '--embed-subs', '--mark-watched', '--download-archive', 'downloaded-videos.txt']
[debug] Custom config: []
[debug] Command-line args: ['--hls-prefer-native', '-o', '%(series)s/s%(season_number)02d-e%(episode_number)02d-%(title)s.%(ext)s', '-v', 'http://watchdisneyxd.go.com/marvels-spiderman-collection/video/vdka4014812/01/01-horizon-high-part-one']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.08.23
[debug] Python version 3.6.2 - Darwin-13.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.3.3, ffprobe 3.3.3, rtmpdump 2.4
[debug] Proxy map: {}
[Go] vdka4014812: Downloading JSON metadata
[debug] Using fake IP 3.91.32.77 (US) as X-Forwarded-For.
[Go] VDKA4014812: Downloading JSON metadata
[Go] VDKA4014812: Downloading m3u8 information
WARNING: en subtitles not available for VDKA4014812
WARNING: enUS subtitles not available for VDKA4014812
[info] Writing video subtitles to: Marvel's Spider-Man/s01-e01-S1 E1 - Horizon High Part One.en-us.ttml
[debug] Invoking downloader on 'http://content-auso2.uplynk.com/bd302a4cd04344158f466bfeae8c80a0/f.m3u8?exp=1503550463&ct=a&oid=21885d134fa441488df8e1d7acee8c66&eid=10099879&iph=a0c1fd46a7257143058b97d42e0acae6defe06ecdc31b985971d8290d5bdaf81&rays=jihgfedcb&euid=4813421B-E7EF-4622-80CB-9D47F49AF1D6_000_0_001_lf_05-06-00_NA&cdn=ec&stgcfg=datg&pp2ip=0&ddp=1&sig=51cafa4862ccd4cdae7f65278db199fad5b05a1f0819b22f9761176ed43d7d31&pbs=ced90babab7f4527bb08f6223ce9c286'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 333
[download] Destination: Marvel's Spider-Man/s01-e01-S1 E1 - Horizon High Part One.mp4
[download]  20.4% of ~190.24MiB at  6.24MiB/s ETA 03:15
```

Disney's new spiderman series will not download from the playlist page; it will download individual episodes.

**Comment by kayb94** [comment]
I'd say that is maybe not super mega high comfort, but pretty okay. Please note, everyone is just volunteering here.

Regards
Kay

**Comment by keybounce** [comment]
Still not working.

I am willing to help, but I don't know how to get started fixing this. Can someone walk me though fixing/updating a regex?

(and is there a reason that the error message does not include the search string and the regex that was being used? That might help a lot.)


```
keybounceMBP:Disney michael$ ./yt-dl http://watchdisneyxd.go.com/marvels-spiderman-collection
[Go] marvels-spiderman-collection: Downloading webpage
ERROR: Unable to extract show id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
keybounceMBP:Disney michael$ ./yt-dl -v http://watchdisneyxd.go.com/marvels-spiderman-collection
[debug] System config: []
[debug] User config: ['-k', '--hls-prefer-native', '--abort-on-unavailable-fragment', '-o', '%(series)s/s%(season_number)02d-e%(episode_number)02d-%(title)s.%(ext)s', '-f', '\nbest[ext=mp4][height>431][height<=576]/\nbestvideo[ext=mp4][height=480]+bestaudio[ext=m4a]/\nbest[ext=mp4][height>340][height<=431]/\nbestvideo[ext=mp4][height>360][height<=576]+bestaudio/\nbest[height>340][height<=576]/\nbestvideo[height>360][height<=576]+bestaudio/\nbestvideo[height=360]+bestaudio/\nbest[ext=mp4][height>=280][height<=360]/\nbest[height<=576]/\nworst', '--ap-mso', 'Dish', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '--write-sub', '--write-auto-sub', '--sub-lang', 'en,enUS,en-us', '--sub-format', 'ass/srt/best', '--convert-subs', 'ass', '--embed-subs', '--mark-watched', '--download-archive', 'downloaded-videos.txt']
[debug] Custom config: []
[debug] Command-line args: ['--hls-prefer-native', '-o', '%(series)s/s%(season_number)02d-e%(episode_number)02d-%(title)s.%(ext)s', '-v', 'http://watchdisneyxd.go.com/marvels-spiderman-collection']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.11.15
[debug] Python version 3.6.3 - Darwin-13.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.3.4, ffprobe 3.3.4, rtmpdump 2.4
[debug] Proxy map: {}
[Go] marvels-spiderman-collection: Downloading webpage
ERROR: Unable to extract show id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/Users/michael/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "/Users/michael/bin/youtube-dl/youtube_dl/extractor/common.py", line 437, in extract
    ie_result = self._real_extract(url)
  File "/Users/michael/bin/youtube-dl/youtube_dl/extractor/go.py", line 86, in _real_extract
    show_id = self._search_regex(r'data-show-id=["\']*(SH\d+)', webpage, 'show id')
  File "/Users/michael/bin/youtube-dl/youtube_dl/extractor/common.py", line 800, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract show id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

keybounceMBP:Disney michael$ 
```
