### ISSUE TITLE
mixcloud: unable to extract play info

### ISSUE THREAD

**Issue by hippyTed** [rg3/youtube-dl#14003]
### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
---
---
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.mixcloud.com/indigo-herder/indigo-herder-dj-set-tribal-sphere-outdoors-sunday-morning-060817-chilliout-pt-2/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.08.18
[debug] Python version 3.4.5 - Linux-4.9.34-gentoo-kora-037-x86_64-Intel-R-_Core-TM-_i5-2540M_CPU_@_2.60GHz-with-gentoo-2.3
[debug] exe versions: ffmpeg 3.2.6, ffprobe 3.2.6, rtmpdump 2.4
[debug] Proxy map: {}
[mixcloud] indigo-herder-indigo-herder-dj-set-tribal-sphere-outdoors-sunday-morning-060817-chilliout-pt-2: Downloading webpage
ERROR: Unable to extract play info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 776, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib64/python3.4/site-packages/youtube_dl/extractor/common.py", line 434, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib64/python3.4/site-packages/youtube_dl/extractor/mixcloud.py", line 108, in _real_extract
    r'm-play-info="([^"]+)"', webpage, 'play info')
  File "/usr/lib64/python3.4/site-packages/youtube_dl/extractor/common.py", line 797, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract play info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
<end of log>
```
---
---

**Comment by dstftw** [comment]
Already fixed.

**Comment by hippyTed** [comment]
I have updated youtube-dl to today's new version 2017.08.23 and the same problem is still there.
