### ISSUE TITLE
Please support brighttalk.com

### ISSUE THREAD

**Issue by dash17291** [rg3/youtube-dl#14026]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.08.23**

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

```
$ youtube-dl -v https://www.brighttalk.com/webcast/5522/252893/the-truth-about-802-11ac-wave-2-technology
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.brighttalk.com/webcast/5522/252893/the-truth-about-802-11ac-wave-2-technology']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.08.23
[debug] Python version 2.7.9 - Linux-4.9.0-0.bpo.3-amd64-x86_64-with-debian-8.9
[debug] exe versions: ffmpeg 3.2.5-1, ffprobe 3.2.5-1
[debug] Proxy map: {}
[generic] the-truth-about-802-11ac-wave-2-technology: Requesting header
WARNING: Falling back on generic information extractor.
[generic] the-truth-about-802-11ac-wave-2-technology: Downloading webpage
[generic] the-truth-about-802-11ac-wave-2-technology: Extracting information
ERROR: Unsupported URL: https://www.brighttalk.com/webcast/5522/252893/the-truth-about-802-11ac-wave-2-technology
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2116, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2539, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2528, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: syntax error: line 1, column 0
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 776, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 434, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2989, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.brighttalk.com/webcast/5522/252893/the-truth-about-802-11ac-wave-2-technology
```

**Comment by AlexCzar** [comment]
```
$ youtube-dl --version                                                                                                                                      
2018.07.29
```
brighttalk support still missing.
