### ISSUE TITLE
youtube-dl doesn't work with "limited" videos

### ISSUE THREAD

**Issue by ballo** [rg3/youtube-dl#14042]
### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl -v -F https://www.youtube.com/watch\?v\=Q2Ki6XwaQ94
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-F', u'https://www.youtube.com/watch?v=Q2Ki6XwaQ94']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.07.02
[debug] Python version 2.7.10 - Darwin-14.5.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2
[debug] Proxy map: {}
[youtube] Q2Ki6XwaQ94: Downloading webpage
[youtube] Q2Ki6XwaQ94: Downloading video info webpage
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 465, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 455, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1927, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 762, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 433, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1595, in _real_extract
ValueError: invalid literal for int() with base 10: ''
...
<end of log>
```

### Description of your *issue*, suggested solution and other information

Herr Schmidt's YouTube now has a "limited" mode for videos espousing wrongthink according to the ADL (such as painting a swastika on a helmet for the purpose of battle reenactments). These "limited" videos cannot currently be downloaded by youtube-dl.

**Comment by Hrxn** [comment]
> `[debug] youtube-dl version 2017.07.02`

Please try it with the latest version.

**Comment by ballo** [comment]
According to brew, I have the latest version

**Comment by ballo** [comment]
```
youtube-dl -v -F https://www.youtube.com/watch\?v\=Q2Ki6XwaQ94\&bpctr\=1503822371
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-F', u'https://www.youtube.com/watch?v=Q2Ki6XwaQ94&bpctr=1503822371']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.08.23
[debug] Python version 2.7.10 - Darwin-14.5.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2
[debug] Proxy map: {}
[youtube] Q2Ki6XwaQ94: Downloading webpage
[youtube] Q2Ki6XwaQ94: Downloading video info webpage
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 465, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 455, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1958, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 776, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 434, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1596, in _real_extract
ValueError: invalid literal for int() with base 10: ''

```

**Comment by Hrxn** [comment]
Latest version is `youtube-dl 2017.08.27.1`

**Comment by ballo** [comment]
Feel free to try the same line.

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [this FAQ entry](https://yt-dl.org/update) if you have troubles updating.
