### ISSUE TITLE
Can not access url

### ISSUE THREAD

**Issue by arenadoon** [rg3/youtube-dl#14046]
Hi

I can not access this url, but only the expert can fix it.

Regards
______________________________________
[root@1 ~]# youtube-dl -j https://drive.google.com/file/d/0B-vUyvmDLdWDcEt4WjBqcmI2XzQ/view -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-j', u'https://drive.google.com/file/d/0B-vUyvmDLdWDcEt4WjBqcmI2XzQ/view', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.08.23
[debug] Python version 2.6.6 - Linux-2.6.32-696.10.1.el6.x86_64-x86_64-with-centos-6.9-Final
[debug] exe versions: none
[debug] Proxy map: {}
ERROR: Die Wiedergabe dieses Videos ist zurzeit nicht möglich. Die Anzahl der erlaubten Wiedergaben wurde überschritten. Bitte versuchen Sie es später noch einmal.; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 776, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 434, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/googledrive.py", line 153, in _real_extract
    raise ExtractorError(reason)
ExtractorError: Die Wiedergabe dieses Videos ist zurzeit nicht m\xf6glich. Die Anzahl der erlaubten Wiedergaben wurde \xfcberschritten. Bitte versuchen Sie es sp\xe4ter noch einmal.; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by arenadoon** [comment]
Thank You

Regards
