### ISSUE TITLE
[youtube playlist] ERROR: [Errno 32] Broken pipe with vlc

### ISSUE THREAD

**Issue by carlodoro88** [rg3/youtube-dl#14044]
With last upgrade version 2017.08.27.1 this command doesn't work anymore:

`youtube-dl -v -i -f "best[height<=?720]" -g https://www.youtube.com/playlist?list=PL4t1iG6D25Rubmt-1OGq6cuEuTxxxxxx | vlc -
`

Before this last upgrade I could load a playlist of youtube videos in vlc with this command.

Now I receive this error :

`ERROR: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 787, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 841, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1560, in process_video_result
    self.to_stdout('[debug] Default format spec: %s' % req_format)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 500, in to_stdout
    self._write_string(output, self._screen_file)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 489, in _write_string
    write_string(s, out=out, encoding=self.params.get('encoding'))
  File "/usr/bin/youtube-dl/youtube_dl/utils.py", line 1401, in write_string
    out.flush()
`

Can you fix this bug?

THANK YOU VERY MUCH.

**Comment by Hrxn** [comment]
What if you only try `-f 'best'` as format parameter?

**Comment by carlodoro88** [comment]
I've resolved changing the kernel of my Ubuntu distro. This error exits if you use kernel intel-drm-next or drm-next version 4.13.0-996-generic, while returning at the previous official kernel 4.4.0-92-generic #115~14.04.1-Ubuntu...youtube-dl works !

For me the issue has resolved.
