### ISSUE TITLE
Cannot download Watch Later playlist when authenticated correctly

### ISSUE THREAD

**Issue by hkdobrev** [rg3/youtube-dl#14057]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.08.27.1**
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)

---

Full verbose output as follows:

``` shell
$ youtube-dl --version
2017.08.27.1
```
``` shell
$ youtube-dl -v https://www.youtube.com/playlist?list=WL
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/playlist?list=WL']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.08.27.1
[debug] Python version 2.7.10 - Darwin-17.0.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[youtube:watchlater] WL: Downloading webpage
ERROR: This playlist does not exist.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 776, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 434, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 2697, in _real_extract
    _, playlist = self._extract_playlist('WL')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 2239, in _extract_playlist
    raise ExtractorError(message, expected=True)
ExtractorError: This playlist does not exist.
```

---

I have successfully authenticated with YouTube and I can _successfully_ download **private** YouTube playlists.

However, when I then try to download my Watch Later playlist using:

```shell
youtube-dl https://www.youtube.com/playlist?list=WL
```

I am getting the above error saying this playlist does not exist.
It correctly recognises to use the `youtube:watchlater` info extractor.

I've tried username/password/2FA on the command line. `.netrc` credentials and interactively entering my 2FA token. In all 3 cases I could download other private playlists I have, but I'm getting the same error message for my watch later playlist.

**Comment by dstftw** [comment]
In the log provided you did not specify any form of authentication.

**Comment by hkdobrev** [comment]
@dstftw Updated log with `.netrc` authentication.

**Comment by hkdobrev** [comment]
Here is some more info on authentication:

``` shell
$ youtube-dl -n -v https://www.youtube.com/playlist?list=PLwdaw9XLU1cPRJi-NUJqf-CT0XAsrFUxI
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-n', u'-v', u'https://www.youtube.com/playlist?list=PLwdaw9XLU1cPRJi-NUJqf-CT0XAsrFUxI']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.08.27.1
[debug] Python version 2.7.10 - Darwin-17.0.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[youtube:playlist] Downloading login page
[youtube:playlist] Looking up account info
[youtube:playlist] Logging in
Type 2-step verification code and press [Return]:
[youtube:playlist] Submitting TFA code
WARNING: Unable to submit TFA code: HTTP Error 500: Internal Server Error
WARNING: Unable to extract CheckCookie URL
[youtube:playlist] PLwdaw9XLU1cPRJi-NUJqf-CT0XAsrFUxI: Downloading webpage
[download] Downloading playlist: CTO
[youtube:playlist] playlist CTO: Downloading 3 videos
[download] Downloading video 1 of 3
[youtube] Downloading login page
[youtube] Looking up account info
[youtube] Logging in
Type 2-step verification code and press [Return]:
[youtube] Submitting TFA code
WARNING: Unable to submit TFA code: HTTP Error 500: Internal Server Error
WARNING: Unable to extract CheckCookie URL
[youtube] gcS04BI2sbk: Downloading webpage
[youtube] gcS04BI2sbk: Downloading video info webpage
[youtube] gcS04BI2sbk: Extracting video information
[youtube] gcS04BI2sbk: Downloading MPD manifest
[debug] Default format spec: best
[debug] Invoking downloader on u'https://r1---sn-p25jju-nv4l.googlevideo.com/videoplayback?requiressl=yes&initcwndbps=2927500&mt=1504044386&gir=yes&mime=video%2Fmp4&key=yt6&itag=18&mn=sn-p25jju-nv4l&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&signature=409976BFC02EF51C69AA75AF47F50C4EC5796D02.5677881280DBD633AFFA7D3263049ED1271C5957&ei=zuWlWY2sMo3ccNjpvdAE&ms=au&ipbits=0&mv=m&pl=20&source=youtube&ip=93.152.130.28&id=o-AD771Ume9kUjSa85Pp9h4Lca5lVYzkKxgKMd_-CtaJaN&mm=31&expire=1504066094&clen=281273364&ratebypass=yes&dur=6172.049&lmt=1429956509205369'
[download] Resuming download at byte 62092982
[download] Destination: Reinventing Organizations-gcS04BI2sbk.mp4
[download]  27.2% of 268.24MiB at  3.22MiB/s ETA 01:00^C
ERROR: Interrupted by user
```

☝️ This is me downloading a private playlist of mine. For some reason, it gets 500 and asks me 2FA token twice every time, but it works.

When I use user/password/2fa on the command line it gets cookies and then I'm able to download without additional arguments.
