### ISSUE TITLE
please support ManyVids preview vids (NSFW)

### ISSUE THREAD

**Issue by CiscoPress** [rg3/youtube-dl#14053]
thank you in advance

```
> youtube-dl -v https://www.manyvids.com/Video/421154/Playing-with-my-huge-natural-tits/
[debug] System config: [u'--recode-video=mp4', u'-f', u'bestvideo+bestaudio/best']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.manyvids.com/Video/421154/Playing-with-my-huge-natural-tits/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.08.27.1
[debug] Python version 2.7.10 - Darwin-16.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.3.3, ffprobe 3.3.3, rtmpdump 2.4
[debug] Proxy map: {'http': 'http://127.0.0.1:8118', 'https': 'http://127.0.0.1:8118'}
[generic] Playing-with-my-huge-natural-tits: Requesting header
WARNING: Falling back on generic information extractor.
[generic] Playing-with-my-huge-natural-tits: Downloading webpage
[generic] Playing-with-my-huge-natural-tits: Extracting information
ERROR: Unsupported URL: https://www.manyvids.com/Video/421154/Playing-with-my-huge-natural-tits/
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2116, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2539, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2528, in _XML
    parser.feed(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: mismatched tag: line 42, column 2
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 776, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 434, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2989, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.manyvids.com/Video/421154/Playing-with-my-huge-natural-tits/
```

**Comment by ArabInBerlin1** [comment]
youtube-dl -v https://www.manyvids.com/Video/421154/Playing-with-my-huge-natural-tits/

**Comment by ArabInBerlin1** [comment]
[debug] System config: [u'--recode-video=mp4', u'-f', u'bestvideo+bestaudio/best']

**Comment by ArabInBerlin1** [comment]
[debug] User config: []

**Comment by ArabInBerlin1** [comment]
[debug] Custom config: [
