### ISSUE TITLE
Youtube said: This video does not exist. [dynamic temporary video ids!?]

### ISSUE THREAD

**Issue by fzg** [rg3/youtube-dl#14066]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.08.27.1*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.08.27.1**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-g', u'-i', u'https://www.youtube.com/watch?v=iZndUzFtXht', u'-u', u'PRIVATE']
Type account password and press [Return]: 
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.08.27.1
[debug] Python version 2.7.13 - Linux-4.9.6-rt6-x86_64-with-Debian-unstable-sid
[debug] exe versions: ffmpeg 3.0.1, ffprobe 3.0.1, rtmpdump 2.4
[debug] Proxy map: {}
ERROR: iZndUzFtXht: YouTube said: This video does not exist.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 776, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 434, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1565, in _real_extract
    expected=True, video_id=video_id)
ExtractorError: iZndUzFtXht: YouTube said: This video does not exist.

```

---

- Single video: https://www.youtube.com/watch?v=iZndUzFtXht
---

I can watch the video in Chromium [Version 56.0.2924.76 built on Debian 9.0, running on Debian (64-bit))  whilst logged using the same username.

**Comment by fzg** [comment]
Edit: Now the video id is iZndUzFtXp0, what the ***!?
It's embedded from _http://www.funkykit.com/reviews/iqos-tobacco-heating-system-review/_

**Comment by fzg** [comment]
Hum, seems that there is no fix once the video ids expire. Closing this :)
