### ISSUE TITLE
specify quality format with pornhub doesn't work...

### ISSUE THREAD

**Issue by demonluo** [rg3/youtube-dl#14121]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.09.02*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.09.02**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2017.09.02
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

i use this -f "best[height<=480]" on youtube/dailymotion/vimeo etc & it work but for pornhub this doesn't work even if the video have 480p/240p, i only get 720p using -f "best[height<=480]/best"...

...
eg, http://www.pornhub.com/view_video.php?viewkey=ph56cc2f5c35d68
```

**Comment by rautamiekka** [comment]
The reason is simple: you're not using `-v` or `--verbose` flag which'd tell you such formats aren't downloadable. Look what my script is printing which is told to get only the 360p and 480p formats by any ways necessary:

**First bestvideo at 360p + bestaudio, then the same at 480p:**
```
C:\Users\jaervinen\Desktop>"python.exe" "C:\Users\Public\Downloads\youtube-dl.pyc" --ignore-config --verbose --verbose --ignore-errors --no-mark-watched --format "bestvideo[height=360]+bestaudio" --audio-format best --audio-quality 0 --no-playlist --output "C:\Users\jaervinen\Desktop/%(uploader_id)s"/"%(title)s %(resolution)s #%(id)s#.%(ext)s" --console-title --no-mtime --buffer-size 10M --retries infinite --continue --no-overwrites --fragment-retries infinite "https://www.redtube.com/1513831" "http://www.pornhub.com/view_video.php?viewkey=ph56cc2f5c35d68"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--ignore-config', '--verbose', '--verbose', '--ignore-errors', '--no-mark-watched', '--format', 'bestvideo[height=360]+bestaudio', '--audio-format', 'best', '--audio-quality', '0', '--no-playlist', '--output', 'C:\\Users\\jaervinen\\Desktop/%(uploader_id)s/%(title)s %(resolution)s #%(id)s#.%(ext)s', '--console-title', '--no-mtime', '--buffer-size', '10M', '--retries', 'infinite', '--continue', '--no-overwrites', '--fragment-retries', 'infinite', 'https://www.redtube.com/1513831', 'http://www.pornhub.com/view_video.php?viewkey=ph56cc2f5c35d68']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2017.09.02
[debug] Python version 3.6.2 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[RedTube] 1513831: Downloading webpage
WARNING: unable to extract duration; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
ERROR: requested format not available
Traceback (most recent call last):
  File "C:\Users\Public\Downloads\youtube-dl.pyc\youtube_dl\YoutubeDL.py", line 787, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Users\Public\Downloads\youtube-dl.pyc\youtube_dl\YoutubeDL.py", line 841, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "C:\Users\Public\Downloads\youtube-dl.pyc\youtube_dl\YoutubeDL.py", line 1593, in process_video_result
    expected=True)
youtube_dl.utils.ExtractorError: requested format not available

[PornHub] ph56cc2f5c35d68: Downloading webpage
[PornHub] ph56cc2f5c35d68: Downloading webpage
ERROR: requested format not available
Traceback (most recent call last):
  File "C:\Users\Public\Downloads\youtube-dl.pyc\youtube_dl\YoutubeDL.py", line 787, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Users\Public\Downloads\youtube-dl.pyc\youtube_dl\YoutubeDL.py", line 841, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "C:\Users\Public\Downloads\youtube-dl.pyc\youtube_dl\YoutubeDL.py", line 1593, in process_video_result
    expected=True)
youtube_dl.utils.ExtractorError: requested format not available


C:\Users\jaervinen\Desktop>"python.exe" "C:\Users\Public\Downloads\youtube-dl.pyc" --ignore-config --verbose --verbose --ignore-errors --no-mark-watched --format "bestvideo[height=480]+bestaudio" --audio-format best --audio-quality 0 --no-playlist --output "C:\Users\jaervinen\Desktop/%(uploader_id)s"/"%(title)s %(resolution)s #%(id)s#.%(ext)s" --console-title --no-mtime --buffer-size 10M --retries infinite --continue --no-overwrites --fragment-retries infinite "https://www.redtube.com/1513831" "http://www.pornhub.com/view_video.php?viewkey=ph56cc2f5c35d68"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--ignore-config', '--verbose', '--verbose', '--ignore-errors', '--no-mark-watched', '--format', 'bestvideo[height=480]+bestaudio', '--audio-format', 'best', '--audio-quality', '0', '--no-playlist', '--output', 'C:\\Users\\jaervinen\\Desktop/%(uploader_id)s/%(title)s %(resolution)s #%(id)s#.%(ext)s', '--console-title', '--no-mtime', '--buffer-size', '10M', '--retries', 'infinite', '--continue', '--no-overwrites', '--fragment-retries', 'infinite', 'https://www.redtube.com/1513831', 'http://www.pornhub.com/view_video.php?viewkey=ph56cc2f5c35d68']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2017.09.02
[debug] Python version 3.6.2 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[RedTube] 1513831: Downloading webpage
WARNING: unable to extract duration; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
ERROR: requested format not available
Traceback (most recent call last):
  File "C:\Users\Public\Downloads\youtube-dl.pyc\youtube_dl\YoutubeDL.py", line 787, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Users\Public\Downloads\youtube-dl.pyc\youtube_dl\YoutubeDL.py", line 841, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "C:\Users\Public\Downloads\youtube-dl.pyc\youtube_dl\YoutubeDL.py", line 1593, in process_video_result
    expected=True)
youtube_dl.utils.ExtractorError: requested format not available

[PornHub] ph56cc2f5c35d68: Downloading webpage
[PornHub] ph56cc2f5c35d68: Downloading webpage
ERROR: requested format not available
Traceback (most recent call last):
  File "C:\Users\Public\Downloads\youtube-dl.pyc\youtube_dl\YoutubeDL.py", line 787, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Users\Public\Downloads\youtube-dl.pyc\youtube_dl\YoutubeDL.py", line 841, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "C:\Users\Public\Downloads\youtube-dl.pyc\youtube_dl\YoutubeDL.py", line 1593, in process_video_result
    expected=True)
youtube_dl.utils.ExtractorError: requested format not available
```

**Next, the best combination at 360p and 480p:**
```
C:\Users\jaervinen\Desktop>"python.exe" "C:\Users\Public\Downloads\youtube-dl.pyc" --ignore-config --verbose --verbose --ignore-errors --no-mark-watched --format "best[height=360]" --audio-format best --audio-quality 0 --no-playlist --output "C:\Users\jaervinen\Desktop/%(uploader_id)s"/"%(title)s %(resolution)s #%(id)s#.%(ext)s" --console-title --no-mtime --buffer-size 10M --retries infinite --continue --no-overwrites --fragment-retries infinite "https://www.redtube.com/1513831" "http://www.pornhub.com/view_video.php?viewkey=ph56cc2f5c35d68"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--ignore-config', '--verbose', '--verbose', '--ignore-errors', '--no-mark-watched', '--format', 'best[height=360]', '--audio-format', 'best', '--audio-quality', '0', '--no-playlist', '--output', 'C:\\Users\\jaervinen\\Desktop/%(uploader_id)s/%(title)s %(resolution)s #%(id)s#.%(ext)s', '--console-title', '--no-mtime', '--buffer-size', '10M', '--retries', 'infinite', '--continue', '--no-overwrites', '--fragment-retries', 'infinite', 'https://www.redtube.com/1513831', 'http://www.pornhub.com/view_video.php?viewkey=ph56cc2f5c35d68']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2017.09.02
[debug] Python version 3.6.2 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[RedTube] 1513831: Downloading webpage
WARNING: unable to extract duration; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
ERROR: requested format not available
Traceback (most recent call last):
  File "C:\Users\Public\Downloads\youtube-dl.pyc\youtube_dl\YoutubeDL.py", line 787, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Users\Public\Downloads\youtube-dl.pyc\youtube_dl\YoutubeDL.py", line 841, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "C:\Users\Public\Downloads\youtube-dl.pyc\youtube_dl\YoutubeDL.py", line 1593, in process_video_result
    expected=True)
youtube_dl.utils.ExtractorError: requested format not available

[PornHub] ph56cc2f5c35d68: Downloading webpage
[PornHub] ph56cc2f5c35d68: Downloading webpage
ERROR: requested format not available
Traceback (most recent call last):
  File "C:\Users\Public\Downloads\youtube-dl.pyc\youtube_dl\YoutubeDL.py", line 787, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Users\Public\Downloads\youtube-dl.pyc\youtube_dl\YoutubeDL.py", line 841, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "C:\Users\Public\Downloads\youtube-dl.pyc\youtube_dl\YoutubeDL.py", line 1593, in process_video_result
    expected=True)
youtube_dl.utils.ExtractorError: requested format not available


C:\Users\jaervinen\Desktop>"python.exe" "C:\Users\Public\Downloads\youtube-dl.pyc" --ignore-config --verbose --verbose --ignore-errors --no-mark-watched --format "best[height=480]" --audio-format best --audio-quality 0 --no-playlist --output "C:\Users\jaervinen\Desktop/%(uploader_id)s"/"%(title)s %(resolution)s #%(id)s#.%(ext)s" --console-title --no-mtime --buffer-size 10M --retries infinite --continue --no-overwrites --fragment-retries infinite "https://www.redtube.com/1513831" "http://www.pornhub.com/view_video.php?viewkey=ph56cc2f5c35d68"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--ignore-config', '--verbose', '--verbose', '--ignore-errors', '--no-mark-watched', '--format', 'best[height=480]', '--audio-format', 'best', '--audio-quality', '0', '--no-playlist', '--output', 'C:\\Users\\jaervinen\\Desktop/%(uploader_id)s/%(title)s %(resolution)s #%(id)s#.%(ext)s', '--console-title', '--no-mtime', '--buffer-size', '10M', '--retries', 'infinite', '--continue', '--no-overwrites', '--fragment-retries', 'infinite', 'https://www.redtube.com/1513831', 'http://www.pornhub.com/view_video.php?viewkey=ph56cc2f5c35d68']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2017.09.02
[debug] Python version 3.6.2 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[RedTube] 1513831: Downloading webpage
WARNING: unable to extract duration; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
ERROR: requested format not available
Traceback (most recent call last):
  File "C:\Users\Public\Downloads\youtube-dl.pyc\youtube_dl\YoutubeDL.py", line 787, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Users\Public\Downloads\youtube-dl.pyc\youtube_dl\YoutubeDL.py", line 841, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "C:\Users\Public\Downloads\youtube-dl.pyc\youtube_dl\YoutubeDL.py", line 1593, in process_video_result
    expected=True)
youtube_dl.utils.ExtractorError: requested format not available

[PornHub] ph56cc2f5c35d68: Downloading webpage
[PornHub] ph56cc2f5c35d68: Downloading webpage
ERROR: requested format not available
Traceback (most recent call last):
  File "C:\Users\Public\Downloads\youtube-dl.pyc\youtube_dl\YoutubeDL.py", line 787, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Users\Public\Downloads\youtube-dl.pyc\youtube_dl\YoutubeDL.py", line 841, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "C:\Users\Public\Downloads\youtube-dl.pyc\youtube_dl\YoutubeDL.py", line 1593, in process_video_result
    expected=True)
youtube_dl.utils.ExtractorError: requested format not available
```

**_Therefore you're getting the best since you're not getting what you ask for first._**
