### ISSUE TITLE
nicovideo error

### ISSUE THREAD

**Issue by Approximately** [rg3/youtube-dl#14154]
Tried downloading HEAD BORONE from nicovideo.jp... got this.

Keep in mind I'm using the newest version.

Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptra0egnk\build\youtube_dl\__init__.py", line 465, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptra0egnk\build\youtube_dl\__init__.py", line 455, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptra0egnk\build\youtube_dl\YoutubeDL.py", line 1958, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptra0egnk\build\youtube_dl\YoutubeDL.py", line 787, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptra0egnk\build\youtube_dl\YoutubeDL.py", line 848, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptra0egnk\build\youtube_dl\YoutubeDL.py", line 776, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptra0egnk\build\youtube_dl\extractor\common.py", line 434, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptra0egnk\build\youtube_dl\extractor\niconico.py", line 399, in _real_extract
AttributeError: 'NoneType' object has no attribute 'get'

Any help?

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
