### ISSUE TITLE
[twitch] UnsupportedError: Unsupported URL

### ISSUE THREAD

**Issue by hasnogaems** [rg3/youtube-dl#14162]
Few months ago i download using the same command just fine. How make it work?

```
I:\youtube-dl-master\bin>youtube-dl.exe -v --ffmpeg-location E:\ffmpeg2\bin http
s://www.twitch.tv/videos/173659948
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'--ffmpeg-location', u'E:\\ffmpeg2\\bin', u'
https://www.twitch.tv/videos/173659948']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.03.25
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-76331-gf8d429e, ffprobe N-76331-gf8d429e
[debug] Proxy map: {}
[generic] 173659948: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 173659948: Downloading webpage
[generic] 173659948: Extracting information
ERROR: Unsupported URL: https://www.twitch.tv/videos/173659948
Traceback (most recent call last):
  File "youtube_dl\extractor\generic.pyo", line 1343, in _real_extract
  File "youtube_dl\compat.pyo", line 253, in compat_etree_fromstring
  File "youtube_dl\compat.pyo", line 242, in _XML
  File "xml\etree\ElementTree.pyo", line 1642, in feed
  File "xml\etree\ElementTree.pyo", line 1506, in _raiseerror
ParseError: mismatched tag: line 176, column 2
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 668, in extract_info
  File "youtube_dl\extractor\common.pyo", line 320, in extract
  File "youtube_dl\extractor\generic.pyo", line 2003, in _real_extract
UnsupportedError: Unsupported URL: https://www.twitch.tv/videos/173659948
```

**Comment by hasnogaems** [comment]
I updated to last version. It work fine now.
