### ISSUE TITLE
Finds a format with -F but not with -f

### ISSUE THREAD

**Issue by entrity** [rg3/youtube-dl#14175]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.09.11*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.09.11**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[user@machine 2]$ youtube-dl -v -i -f '[height=480]'  https://www.youtube.com/watch?v=vH76v-vofxM&index=33&list=PL2623B0CF29C34A33
[1] 19388
[2] 19389
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-i', '-f', '[height=480]', 'https://www.youtube.com/watch?v=vH76v-vofxM']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.09.11
[debug] Python version 3.6.1 - Linux-4.10.13-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 3.3, ffprobe 3.3, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] vH76v-vofxM: Downloading webpage
[youtube] vH76v-vofxM: Downloading video info webpage
[youtube] vH76v-vofxM: Extracting video information
[youtube] vH76v-vofxM: Downloading MPD manifest
ERROR: requested format not available
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 787, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 841, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 1593, in process_video_result
    expected=True)
youtube_dl.utils.ExtractorError: requested format not available

[1]-  Exit 1                  youtube-dl -v -i -f '[height=480]' https://www.youtube.com/watch?v=vH76v-vofxM
[2]+  Done                    index=33
[user@machine 2]$ youtube-dl -v -F https://www.youtube.com/watch?v=vH76v-vofxM&index=33&list=PL2623B0CF29C34A33
[1] 19415
[2] 19416
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://www.youtube.com/watch?v=vH76v-vofxM']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.09.11
[debug] Python version 3.6.1 - Linux-4.10.13-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 3.3, ffprobe 3.3, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] vH76v-vofxM: Downloading webpage
[youtube] vH76v-vofxM: Downloading video info webpage
[youtube] vH76v-vofxM: Extracting video information
[youtube] vH76v-vofxM: Downloading MPD manifest
[info] Available formats for vH76v-vofxM:
format code  extension  resolution note
139          m4a        audio only DASH audio   49k , m4a_dash container, mp4a.40.5@ 48k (22050Hz), 2.70MiB
249          webm       audio only DASH audio   55k , opus @ 50k, 2.87MiB
250          webm       audio only DASH audio   79k , opus @ 70k, 3.73MiB
140          m4a        audio only DASH audio  129k , m4a_dash container, mp4a.40.2@128k (44100Hz), 7.19MiB
171          webm       audio only DASH audio  130k , vorbis@128k, 6.33MiB
251          webm       audio only DASH audio  185k , opus @160k, 8.88MiB
278          webm       256x144    144p   97k , webm container, vp9, 15fps, video only, 4.25MiB
160          mp4        256x144    DASH video  122k , avc1.4d400c, 15fps, video only, 6.00MiB
242          webm       426x240    240p  252k , vp9, 30fps, video only, 9.89MiB
133          mp4        426x240    DASH video  264k , avc1.4d4015, 30fps, video only, 13.61MiB
243          webm       640x360    360p  464k , vp9, 30fps, video only, 17.80MiB
134          mp4        640x360    DASH video  603k , avc1.4d401e, 30fps, video only, 19.41MiB
244          webm       854x480    480p  836k , vp9, 30fps, video only, 31.58MiB
135          mp4        854x480    DASH video 1104k , avc1.4d401f, 30fps, video only, 36.82MiB
247          webm       1280x720   720p 1824k , vp9, 30fps, video only, 67.93MiB
136          mp4        1280x720   DASH video 2116k , avc1.4d401f, 30fps, video only, 72.21MiB
17           3gp        176x144    small , mp4v.20.3, mp4a.40.2@ 24k
36           3gp        320x180    small , mp4v.20.3, mp4a.40.2
43           webm       640x360    medium , vp8.0, vorbis@128k
18           mp4        640x360    medium , avc1.42001E, mp4a.40.2@ 96k
22           mp4        1280x720   hd720 , avc1.64001F, mp4a.40.2@192k (best)
[user@machine 2]$ youtube-dl -v -f 135 https://www.youtube.com/watch?v=vH76v-vofxM&index=33&list=PL2623B0CF29C34A33
[3] 19435
[4] 19436
[1]   Done                    youtube-dl -v -F https://www.youtube.com/watch?v=vH76v-vofxM
[2]   Done                    index=33
System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-f', '135', 'https://www.youtube.com/watch?v=vH76v-vofxM']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.09.11
[debug] Python version 3.6.1 - Linux-4.10.13-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 3.3, ffprobe 3.3, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] vH76v-vofxM: Downloading webpage
[youtube] vH76v-vofxM: Downloading video info webpage
[youtube] vH76v-vofxM: Extracting video information
[youtube] vH76v-vofxM: Downloading MPD manifest
[debug] Invoking downloader on 'https://r20---sn-o097zne7.googlevideo.com/videoplayback?id=bc7efabfebe87f13&itag=135&source=youtube&requiressl=yes&mv=m&ms=au&mm=31&mn=sn-o097zne7&pl=16&initcwndbps=5370000&ei=hw23WaeeIM26-wOhi6i4Dg&ratebypass=yes&mime=video/mp4&gir=yes&clen=38609125&lmt=1401220475542612&dur=469.203&key=dg_yt0&signature=10C96BB22114CF41B38981B80D659071CF279330.2A7D525509094B468BFF10A018FC781F5883912E&mt=1505168647&ip=169.237.108.223&ipbits=0&expire=1505190375&sparams=ip,ipbits,expire,id,itag,source,requiressl,mv,ms,mm,mn,pl,initcwndbps,ei,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: YCPT - 3.10 - Sakigake!! Otokojuku - The Dodgeball-vH76v-vofxM.mp4
[download] 100% of 36.82MiB in 00:09

[3]-  Done                    youtube-dl -v -f 135 https://www.youtube.com/watch?v=vH76v-vofxM
[4]+  Done                    index=33
[user@machine 2]$ mediainfo YCPT\ -\ 3.10\ -\ Sakigake\!\!\ Otokojuku\ -\ The\ Dodgeball-vH76v-vofxM.mp4 | grep -P 'Height|Width'
Width                                    : 854 pixels
Height                                   : 480 pixels
...
<end of log>
```

### Description of your *issue*, suggested solution and other information

I'm using version `2017.09.11` of `youtube-dl` on Arch Linux to download a Youtube video, and my format specification is not handled as documented:

If I specify `-F`, I see a number of formats (given in the long log above), including:

```
244          webm       854x480    480p  836k , vp9, 30fps, video only, 31.58MiB
135          mp4        854x480    DASH video 1104k , avc1.4d401f, 30fps, video only, 36.82MiB
```

- If I try to download with `-f [height=480]`, `youtube-dl` outputs `ERROR: requested format not available`.
- If I try to download with `-f [height<600]`, `youtube-dl` downloads the 630x360 instead of the 854x640.
- If I try to download with `-f 135`, `youtube-dl` downloads the intended 854x640.

The problem appears to be that `youtube-dl` cannot find the sought format (except when performing an `-F` command.

**Comment by dstftw** [comment]
1. https://github.com/rg3/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command
2. https://github.com/rg3/youtube-dl#format-selection
