### ISSUE TITLE
can't download video with contentProtection tag

### ISSUE THREAD

**Issue by briu** [rg3/youtube-dl#14170]
I'm trying to download video with this mpd:
`https://level3-usp-dash-arch.cmore.se/live/3201122.isml/3201122.mpd`

youtube-dl raised error:
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://level3-usp-dash-arch.cmore.se/live/3201122.isml/3201122.mpd?t=2017-09-06T16:55:00.000-2017-09-06T18:40:00.000', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.09.02
[debug] Python version 2.7.11 - Darwin-16.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.2.2, ffprobe 3.2.2
[debug] Proxy map: {}
[generic] 3201122.mpd?t=2017-09-06T16:55:00.000-2017-09-06T18:40:00: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 3201122.mpd?t=2017-09-06T16:55:00.000-2017-09-06T18:40:00: Downloading webpage
[generic] 3201122.mpd?t=2017-09-06T16:55:00.000-2017-09-06T18:40:00: Extracting information
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 776, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 434, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2134, in _real_extract
    self._sort_formats(info_dict['formats'])
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1072, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

This mpd file contain `ContentProtection` tags, and haven't `SegmentList` tags. Is it possible to download video with manifest contained this tags?

**Comment by dstftw** [comment]
Not possible.
