### ISSUE TITLE
Downloading Youtube private video with cookiefile no longer works

### ISSUE THREAD

**Issue by dkess** [rg3/youtube-dl#14182]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.09.11*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.09.11**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other
---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--cookies', 'cookies.txt', 'https://youtu.be/sdYucbUu_sw']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.09.11
[debug] Python version 3.6.2 - Linux-4.12.12-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 3.3.3, ffprobe 3.3.3, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] sdYucbUu_sw: Downloading webpage
[youtube] sdYucbUu_sw: Downloading embed webpage
[youtube] sdYucbUu_sw: Refetching age-gated info webpage
ERROR: sdYucbUu_sw: YouTube said: This video is private.
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 776, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 434, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1608, in _real_extract
    expected=True, video_id=video_id)
youtube_dl.utils.ExtractorError: sdYucbUu_sw: YouTube said: This video is private.

```

---

### Description of your *issue*, suggested solution and other information
My university hosts webcast lectures on Youtube, but requires being logged in as the correct user. In the past I have been able to use a cookies.txt file (from [this](https://chrome.google.com/webstore/detail/cookiestxt/njabckikapfpffapmjgojcnbfjonfjfg) Chrome extension) to download the video through youtube-dl. However I am now given the error: "This video is private."

**Comment by dkess** [comment]
After some experimentation I've determined that this is not a youtube-dl bug. Using [this script](https://gist.github.com/hackerb9/d382e09683a52dcac492ebcdaf1b79af) with Firefox I have been able to download videos again.
