### ISSUE TITLE
Dramafever Premium login / 720p bitrate no longer accessible

### ISSUE THREAD

**Issue by cassidyrps** [rg3/youtube-dl#14192]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.09.11*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.09.11**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'https://dramafever-i.akamaihd.net/i/138561/region1/6a72fd68-515a-4df0-a307-21d5bd2ceacd_,3000,400,.mp4.csmil/index_0_av.m3u8?null=0&hdntl=exp=1505266418~acl=%2fi%2f138561%2fregion1%2f6a72fd68-515a-4df0-a307-21d5bd2ceacd_*~data=hdntl~hmac=01a1b0f2df05124f7a5028990b42ae2eedd53e2e00fa6990ec3b35ce5aefdb06']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.09.11
[debug] Python version 2.7.10 - Darwin-15.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.2, ffprobe 3.2, rtmpdump 2.4
[debug] Proxy map: {}
[generic] index_0_av: Requesting header
WARNING: Could not send HEAD request to https://dramafever-i.akamaihd.net/i/138561/region1/6a72fd68-515a-4df0-a307-21d5bd2ceacd_,3000,400,.mp4.csmil/index_0_av.m3u8?null=0&hdntl=exp=1505266418~acl=%2fi%2f138561%2fregion1%2f6a72fd68-515a-4df0-a307-21d5bd2ceacd_*~data=hdntl~hmac=01a1b0f2df05124f7a5028990b42ae2eedd53e2e00fa6990ec3b35ce5aefdb06: HTTP Error 405: Method Not Allowed
[generic] index_0_av: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 503, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2176, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
...
<end of log>
```
---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://dramafever-i.akamaihd.net/i/138561/region1/6a72fd68-515a-4df0-a307-21d5bd2ceacd_,3000,400,.mp4.csmil/index_0_av.m3u8?null=0&hdntl=exp=1505266418~acl=%2fi%2f138561%2fregion1%2f6a72fd68-515a-4df0-a307-21d5bd2ceacd_*~data=hdntl~hmac=01a1b0f2df05124f7a5028990b42ae2eedd53e2e00fa6990ec3b35ce5aefdb06
- Single video: https://www.dramafever.com/drama/5004/6/Lovely_Love_Lie_%2528The_Liar_and_His_Lover%2529/

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

When attempting to download 720p video at the bitrate only accessible to Dramafever premium members, I receive this error. 

I also can't log into my account via Terminal when simply inputting the URL for any given episode. Just wanted to test if that was part of the issue; the link first listed above is via Video DownloadHelper as youtube-dl can't usually access the higher bitrate 720p as part of the format list to an episode URL. The Video DownloadHelper method worked until Dramafever updated its website a few days ago.

**Comment by dstftw** [comment]
You must use original dramafever URL not m3u8 URL.

**Comment by cassidyrps** [comment]
Not possible as I cannot login to the site via youtube-dl and therefore download this bitrate. The bitrate is unaccessible without a premium login.

**Comment by cassidyrps** [comment]
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'https://www.dramafever.com/drama/5004/6/Lovely_Love_Lie_%2528The_Liar_and_His_Lover%2529/?ap=1']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.09.11
[debug] Python version 2.7.10 - Darwin-15.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.2, ffprobe 3.2, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Using fake IP 99.254.12.110 (CA) as X-Forwarded-For.
[dramafever] Logging in as PRIVATE
ERROR: Unable to log in; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 776, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 433, in extract
    self.initialize()
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 391, in initialize
    self._real_initialize()
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/dramafever.py", line 41, in _real_initialize
    self._login()
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/dramafever.py", line 66, in _login
    raise ExtractorError('Unable to log in')
ExtractorError: Unable to log in; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by dstftw** [comment]
Post the output with `--dump-pages`.

**Comment by cassidyrps** [comment]
Sure thing!

```
[dramafever] Logging in as PRIVATE
[dramafever] Dumping request to https://www.dramafever.com/accounts/login/
PCFkb2N0eXBlIGh0bWw+CjxodG1sIG5nLWFwcD0iZHJhbWFmZXZlciIgbmctY29udHJvbGxlcj0iREZBcHBsaWNhdGlvbkNvbnRyb2xsZXIgYXMgcm0iPgo8aGVhZD4KICA8bWV0YSBjaGFyc2V0PSJ1dGYtOCI+CiAgPHRpdGxlIG5nLWJpbmQ9InJtLm1ldGEoKS50aXRsZSI+V2F0Y2ggS29yZWFuIERyYW1hIEZyZWUgfCBLb3JlYW4gTW92aWVzIE9ubGluZSAmIFRlbGVub3ZlbGEgfCBEcmFtYUZldmVyIHwgS0RyYW1hPC90aXRsZT4KCiAgPCEtLSBidWlsZDpiYXNlIC0tPgogIDxiYXNlIGhyZWY9Ii8iPgogIDwhLS0gZW5kYnVpbGQgLS0+CgogIDxtZXRhIG5hbWU9ImRlc2NyaXB0aW9uIiBjb250ZW50PSJ7e3JtLm1ldGEoKS5kZXNjcmlwdGlvbn19Ij4KICA8bWV0YSBuYW1lPSJrZXl3b3JkcyIgY29udGVudD0ie3sgcm0ubWV0YSgpLmtleXdvcmRzIH19Ij4KCiAgPG1ldGEgbmFtZT0idmlld3BvcnQiIGNvbnRlbnQ9IndpZHRoPWRldmljZS13aWR0aCI+CiAgPG1ldGEgbmFtZT0iZHJhbWFmZXZlcjpoZWFsdGgiIGNvbnRlbnQ9Imdvb2QiPgoKICA8IS0tIFR3aXR0ZXIgQ2FyZCBJbmZvcm1hdGlvbiAtLT4KICA8bWV0YSBuYW1lPSJ0d2l0dGVyOmNhcmQiIGNvbnRlbnQ9InN1bW1hcnlfbGFyZ2VfaW1hZ2UiPgogIDxtZXRhIG5hbWU9InR3aXR0ZXI6dGl0bGUiIGNvbnRlbnQ9Int7cm0ubWV0YSgpLnRpdGxlfX0iPgogIDxtZXRhIG5hbWU9InR3aXR0ZXI6c2l0ZSIgY29udGVudD0iRHJhbWFmZXZlciI+CiAgPG1ldGEgbmFtZT0idHdpdHRlcjpkZXNjcmlwdGlvbiIgY29udGVudD0ie3tybS5tZXRhKCkuZGVzY3JpcHRpb259fSI+CiAgPG1ldGEgbmFtZT0idHdpdHRlcjpjcmVhdG9yIiBjb250ZW50PSJEcmFtYWZldmVyIj4KICA8bWV0YSBuYW1lPSJ0d2l0dGVyOmltYWdlOnNyYyIgY29udGVudD0ie3tybS5tZXRhKCkuaW1hZ2UgfCBidWlsZFBhdGg6IHRydWV9fSI+CgogIDwhLS0gT3Blbi1HcmFwaCBJbmZvcm1hdGlvbiAtLT4KICA8bWV0YSBwcm9wZXJ0eT0ib2c6dHlwZSIgY29udGVudD0iYXJ0aWNsZSI+CiAgPG1ldGEgcHJvcGVydHk9Im9nOnRpdGxlIiBjb250ZW50PSJ7e3JtLm1ldGEoKS50aXRsZX19Ij4KICA8bWV0YSBwcm9wZXJ0eT0ib2c6c2l0ZV9uYW1lIiBjb250ZW50PSJEcmFtYWZldmVyIj4KICA8bWV0YSBwcm9wZXJ0eT0ib2c6ZGVzY3JpcHRpb24iIGNvbnRlbnQ9Int7cm0ubWV0YSgpLmRlc2NyaXB0aW9ufX0iPgogIDxtZXRhIHByb3BlcnR5PSJvZzppbWFnZSIgY29udGVudD0ie3tybS5tZXRhKCkuaW1hZ2UgfCBidWlsZFBhdGg6IHRydWV9fSI+CiAgPG1ldGEgcHJvcGVydHk9Im9nOnVybCIgY29udGVudD0ie3tybS5hYnNVcmwoKX19Ij4KICA8bWV0YSBwcm9wZXJ0eT0ib2c6bG9jYWxlIiBjb250ZW50PSJ7e3JtLlVybExhbmd1YWdlLmFjdGl2ZUxhbmd1YWdlfX0iPgogIDxtZXRhIHByb3BlcnR5PSJmYjphcHBfaWQiIGNvbnRlbnQ9IkBAZmFjZWJvb2suYXBwX2lkIj4KICA8bWV0YSBwcm9wZXJ0eT0iZmI6YWRtaW5zIiBjb250ZW50PSI3MjUwNDE0MjMsNTAzODc5Njg1LDc2OTQxMzUwMywxMjA5NTksMTE1NzI1MTI3MCI+CgoKICA8bWV0YSBwcm9wZXJ0eT0ib2c6dmlkZW8iIGNvbnRlbnQ9Int7cm0uYWJzVXJsKCl9fSIgbmctaWY9InJtLm1ldGEoKS5oYXNWaWRlbyI+CgogIDxtZXRhIHByb3BlcnR5PSJvZzp2aWRlbzp1cmwiIGNvbnRlbnQ9Int7cm0uYWJzVXJsKCl9fSIgbmctaWY9InJtLm1ldGEoKS5oYXNWaWRlbyI+CiAgPG1ldGEgcHJvcGVydHk9Im9nOnZpZGVvOnR5cGUiIGNvbnRlbnQ9InZpZGVvL21wNCIgbmctaWY9InJtLm1ldGEoKS5oYXNWaWRlbyI+CiAgPG1ldGEgcHJvcGVydHk9Im9nOnZpZGVvOndpZHRoIiBjb250ZW50PSI2NDAiIG5nLWlmPSJybS5tZXRhKCkuaGFzVmlkZW8iPgogIDxtZXRhIHByb3BlcnR5PSJvZzp2aWRlbzpoZWlnaHQiIGNvbnRlbnQ9IjM3NSIgbmctaWY9InJtLm1ldGEoKS5oYXNWaWRlbyI+CiAgPG1ldGEgbmFtZT0idmlkZW9fdHlwZSIgY29udGVudD0idmlkZW8vbXA0IiBuZy1pZj0icm0ubWV0YSgpLmhhc1ZpZGVvIj4KICA8bWV0YSBuYW1lPSJtZWRpdW0iIGNvbnRlbnQ9InZpZGVvIiBuZy1pZj0icm0ubWV0YSgpLmhhc1ZpZGVvIj4KICA8bWV0YSBuYW1lPSJ2aWRlb193aWR0aCIgY29udGVudD0iMTAwJSIgbmctaWY9InJtLm1ldGEoKS5oYXNWaWRlbyI+CiAgPG1ldGEgbmFtZT0idmlkZW9faGVpZ2h0IiBjb250ZW50PSIxMDAlIiBuZy1pZj0icm0ubWV0YSgpLmhhc1ZpZGVvIj4KCiAgPGxpbmsgcmVsPSJhcHBsZS10b3VjaC1pY29uLXByZWNvbXBvc2VkIiBzaXplcz0iMTUyeDE1MiIgaHJlZj0ie3snaW1hZ2VzL2Zhdmljb24tMTUyeDE1Mi5wbmcnIHwgYnVpbGRQYXRofX0iPgogIDxsaW5rIHJlbD0iYXBwbGUtdG91Y2gtaWNvbi1wcmVjb21wb3NlZCIgc2l6ZXM9IjE0NHgxNDQiIGhyZWY9Int7J2ltYWdlcy9mYXZpY29uLTE0NHgxNDQucG5nJyB8IGJ1aWxkUGF0aH19Ij4KICA8bGluayByZWw9ImFwcGxlLXRvdWNoLWljb24tcHJlY29tcG9zZWQiIHNpemVzPSIxMjB4MTIwIiBocmVmPSJ7eydpbWFnZXMvZmF2aWNvbi0xMjB4MTIwLnBuZycgfCBidWlsZFBhdGh9fSI+CiAgPGxpbmsgcmVsPSJhcHBsZS10b3VjaC1pY29uLXByZWNvbXBvc2VkIiBzaXplcz0iMTE0eDExNCIgaHJlZj0ie3snaW1hZ2VzL2Zhdmljb24tMTE0eDExNC5wbmcnIHwgYnVpbGRQYXRofX0iPgogIDxsaW5rIHJlbD0iYXBwbGUtdG91Y2gtaWNvbi1wcmVjb21wb3NlZCIgc2l6ZXM9IjcyeDcyIiBocmVmPSJ7eydpbWFnZXMvZmF2aWNvbi03Mng3Mi5wbmcnIHwgYnVpbGRQYXRofX0iPgogIDxsaW5rIHJlbD0iYXBwbGUtdG91Y2gtaWNvbi1wcmVjb21wb3NlZCIgaHJlZj0ie3snaW1hZ2VzL2Zhdmljb24tNTd4NTcucG5nJyB8IGJ1aWxkUGF0aH19Ij4KICA8bGluayByZWw9Imljb24iIGhyZWY9Int7J2ltYWdlcy9mYXZpY29uLTMyeDMyLnBuZycgfCBidWlsZFBhdGh9fSIgc2l6ZXM9IjMyeDMyIj4KCiAgPGxpbmsgbmctaHJlZj0ie3snc3R5bGVzL2ZvbnRhc3RpYy5jc3MnIHwgYnVpbGRQYXRofX0iIHJlbD0ic3R5bGVzaGVldCIgdHlwZT0idGV4dC9jc3MiPgogIDxsaW5rIGhyZWY9Imh0dHBzOi8vZm9udHMuZ29vZ2xlYXBpcy5jb20vY3NzP2ZhbWlseT1PcGVuK1NhbnM6NDAwLDcwMHxSYWxld2F5OjQwMCw3MDAsODAwIiByZWw9InN0eWxlc2hlZXQiPgoKICA8IS0tIGJvd2VyOmNzcyAtLT4KICA8bGluayByZWw9InN0eWxlc2hlZXQiIGhyZWY9ImJ1aWxkcy81MC9saWJzLm1pbi5jc3MiPgogIDwhLS0gZW5kaW5qZWN0IC0tPgoKICA8IS0tIGluamVjdDpjc3MgLS0+CiAgPGxpbmsgcmVsPSJzdHlsZXNoZWV0IiBocmVmPSJidWlsZHMvNTAvZHJhbWFmZXZlci5taW4uY3NzIj4KICA8IS0tIGVuZGluamVjdCAtLT4KCiAgPHNjcmlwdD53aW5kb3cuYXBwQ29uZmlnID0geyAiYXBwbGljYXRpb24iOnsic3RvcmFnZSI6ImxvY2FsIiwiaWQiOiJ3d3ciLCJ1cmwiOiJodHRwczovL3d3dy5kcmFtYWZldmVyLmNvbSJ9LCJyYXZlbiI6eyJkc24iOiJodHRwczovLzliMjA1YWFlNjhhZTQ5YTA4OWNiNGYzZWRkYTk3MWM1QHNlbnRyeS5pby8xNjAyMTUifSwgInN3aWZ0eXBlIjp7ImVuZ2luZUtleSI6IkN5d3p5c2NKQUhLQ3dyZXpmenBOIn0sICJidWlsZCI6IHsiaWQiOiI1MCIsImRlc3RpbmF0aW9uIjoiZGlzdC9idWlsZHMvNTAiLCJkZXN0T25seSI6Ii9idWlsZHMvNTAifSwgImZhY2Vib29rUGl4ZWwiOiB7ImlkIjoiMTExMjQ0MDYxMTIwIn0sICJmcmVld2hlZWwiOiB7InVybCI6Imh0dHBzOi8vNWUwZDIudi5md21ybS5uZXQvYWQvZy8xIiwibnciOiIzODUyMzQiLCJwcm9mIjoiMzg1MjM0OmRmX2h0bWw1X2Rlc2t0b3BfbGl2ZSIsInJlc3AiOiJ2YXN0MyIsImNzaWQiOiJkZl9kZXNrdG9wX2VwaXNvZGVfaHRtbDUiLCJhc253IjoiMzg1MjM0Iiwic3NudyI6IjM4NTIzNCIsImZsYWciOiIrYW1jYitleHZ0K2VtY3IrYWV0aStzbHRwIiwibWV0ciI6IjEwMjMiLCJwbGF0Zm9ybSI6IndlYiIsImVudiI6InByb2QiLCJuaWVsc29uIjoiWTBnNU5ESnhaVkZpUXpKdk9tMHpkbk41TTNnNU9YUjNPRFkzZVVkcVZUTlEiLCJpT1MiOnsicHJvZiI6IjM4NTIzNDpkZl9pb3N3ZWJfbGl2ZSIsImNzaWQiOiJkZl9tb2JpbGV3ZWJfaW9zX3ZpZGVvIn0sImFuZHJvaWQiOnsicHJvZiI6IjM4NTIzNDpkZl9hbmRyb2lkd2ViX2xpdmUiLCJjc2lkIjoiZGZfbW9iaWxld2ViX2FuZHJvaWRfdmlkZW8ifSwidGltZW91dCI6MX0sICJjb21TY29yZSI6IHsiYzIiOiIxNDkwOTcwMSIsInN0YXRpb25UaXRsZSI6IkRSQU1BRkVWRVIiLCJkaWN0aW9uYXJ5IjoiRFJBTUFGRVZFUiJ9LCAieW91Ym9yYSI6IHsiYWNjb3VudENvZGUiOiJkcmFtYWZldmVyIiwiZW5hYmxlQW5hbHl0aWNzIjp0cnVlLCJjaGFubmVsIjoiZHJhbWFmZXZlciJ9IH07PC9zY3JpcHQ+CgogIDwhLS0gRmFjZWJvb2sgUGl4ZWwgQ29kZSBub3QgaWRlYWwgcGxhY2UgYnV0IHRoaXMgaXMgd2hlcmUgRmFjZWJvb2sgd2FudHMgdGhlIHNjcmlwdCB0byBiZS4tLT4KICA8c2NyaXB0PgogICFmdW5jdGlvbihmLGIsZSx2LG4sdCxzKXtpZihmLmZicSlyZXR1cm47bj1mLmZicT1mdW5jdGlvbigpe24uY2FsbE1ldGhvZD8KICBuLmNhbGxNZXRob2QuYXBwbHkobixhcmd1bWVudHMpOm4ucXVldWUucHVzaChhcmd1bWVudHMpfTtpZighZi5fZmJxKWYuX2ZicT1uOwogIG4ucHVzaD1uO24ubG9hZGVkPSEwO24udmVyc2lvbj0nMi4wJztuLnF1ZXVlPVtdO3Q9Yi5jcmVhdGVFbGVtZW50KGUpO3QuYXN5bmM9ITA7CiAgdC5zcmM9djtzPWIuZ2V0RWxlbWVudHNCeVRhZ05hbWUoZSlbMF07cy5wYXJlbnROb2RlLmluc2VydEJlZm9yZSh0LHMpfSh3aW5kb3csCiAgZG9jdW1lbnQsJ3NjcmlwdCcsJ2h0dHBzOi8vY29ubmVjdC5mYWNlYm9vay5uZXQvZW5fVVMvZmJldmVudHMuanMnKTsKCiAgZmJxKCdpbml0JywgJzExMTI0NDA2MTEyMCcpOwogIDwvc2NyaXB0PgogIDxub3NjcmlwdD48aW1nIGhlaWdodD0iMSIgd2lkdGg9IjEiIHN0eWxlPSJkaXNwbGF5Om5vbmUiIHNyYz0iaHR0cHM6Ly93d3cuZmFjZWJvb2suY29tL3RyP2lkPTExMTI0NDA2MTEyMCZldj1QYWdlVmlldyZub3NjcmlwdD0xIj48L25vc2NyaXB0PgogIDwhLS0gRW5kIEZhY2Vib29rIFBpeGVsIENvZGUgLS0+CjwvaGVhZD4KPGJvZHk+CiAgPGRpdiBuZy1pbmNsdWRlPSIncGFydGlhbHMvaGVhZGVyL21vYmlsZS1uYXYtbGVnYWN5Lmh0bWwnIj48L2Rpdj4KICA8ZGl2IGNsYXNzPSJzaXRlLWNvbnRhaW5lciIgdWktdmlldyBhdXRvc2Nyb2xsPSJ0cnVlIiBuZy1jbGFzcz0ie29wZW5idXJnZXI6cm0uYWN0aXZlTW9iaWxlTWVudSB9Ij48L2Rpdj4KICA8c2VhcmNoOm92ZXJsYXk+PC9zZWFyY2g6b3ZlcmxheT4KCiAgPCEtLSBib3dlcjpqcyAtLT4KICA8c2NyaXB0IHNyYz0iYnVpbGRzLzUwL2xpYnMubWluLmpzIj48L3NjcmlwdD4KICA8IS0tIGVuZGluamVjdCAtLT4KCiAgPCEtLSBpbmplY3Q6bW9kdWxlcyAtLT4KICA8c2NyaXB0IHNyYz0iYnVpbGRzLzUwL2RyYW1hZmV2ZXItYnVuZGxlLmpzIj48L3NjcmlwdD4KICA8IS0tIGVuZGluamVjdCAtLT4KCiAgPCEtLSBpbmplY3Q6anMgLS0+CiAgPHNjcmlwdCBzcmM9ImJ1aWxkcy81MC9kcmFtYWZldmVyLm1pbi5qcyI+PC9zY3JpcHQ+CiAgPCEtLSBlbmRpbmplY3QgLS0+CgogIDwhLS0gaW5qZWN0OnBhcnRpYWxzIC0tPgogIDxzY3JpcHQgc3JjPSJidWlsZHMvNTAvZHJhbWFmZXZlci50ZW1wbGF0ZXMuanMiPjwvc2NyaXB0PgogIDwhLS0gZW5kaW5qZWN0IC0tPgoKICA8c2NyaXB0IHR5cGU9InRleHQvamF2YXNjcmlwdCI+CiAgICAvL1NlbnRyeSBDb25maWcKICAgIFJhdmVuLmNvbmZpZygnaHR0cHM6Ly85YjIwNWFhZTY4YWU0OWEwODljYjRmM2VkZGE5NzFjNUBzZW50cnkuaW8vMTYwMjE1JywgewogICAgICByZWxlYXNlOiAnNTAnCiAgICB9KS5pbnN0YWxsKCk7CiAgICAvL0dvb2dsZSBBbmFseXRpY3MKICAgIChmdW5jdGlvbihpLHMsbyxnLHIsYSxtKXtpWydHb29nbGVBbmFseXRpY3NPYmplY3QnXT1yO2lbcl09aVtyXXx8ZnVuY3Rpb24oKXsKICAgIChpW3JdLnE9aVtyXS5xfHxbXSkucHVzaChhcmd1bWVudHMpfSxpW3JdLmw9MSpuZXcgRGF0ZSgpO2E9cy5jcmVhdGVFbGVtZW50KG8pLAogICAgbT1zLmdldEVsZW1lbnRzQnlUYWdOYW1lKG8pWzBdO2EuYXN5bmM9MTthLnNyYz1nO20ucGFyZW50Tm9kZS5pbnNlcnRCZWZvcmUoYSxtKQogICAgfSkod2luZG93LGRvY3VtZW50LCdzY3JpcHQnLCdodHRwczovL3d3dy5nb29nbGUtYW5hbHl0aWNzLmNvbS9hbmFseXRpY3MuanMnLCdnYScpOwoKICAgIGdhKCdjcmVhdGUnLCAnVUEtNTI1NDczNy0xJywgJ2F1dG8nKTsKICA8L3NjcmlwdD4KCiAgPGRpdiBpZD0iZmItcm9vdCI+PC9kaXY+CiAgPHNjcmlwdD4oZnVuY3Rpb24oZCwgcywgaWQpIHsKICAgIHZhciBqcywgZmpzID0gZC5nZXRFbGVtZW50c0J5VGFnTmFtZShzKVswXTsKICAgIGlmIChkLmdldEVsZW1lbnRCeUlkKGlkKSkgcmV0dXJuOwogICAganMgPSBkLmNyZWF0ZUVsZW1lbnQocyk7IGpzLmlkID0gaWQ7CiAgICBqcy5zcmMgPSAiLy9jb25uZWN0LmZhY2Vib29rLm5ldC9lbl9VUy9zZGsuanMjeGZibWw9MSZ2ZXJzaW9uPXYyLjciOwogICAgZmpzLnBhcmVudE5vZGUuaW5zZXJ0QmVmb3JlKGpzLCBmanMpOwogIH0oZG9jdW1lbnQsICdzY3JpcHQnLCAnZmFjZWJvb2stanNzZGsnKSk7PC9zY3JpcHQ+CgogIDwhLS0gR29vZ2xlIFRhZyBNYW5hZ2VyIC0tPgogIDxzY3JpcHQ+KGZ1bmN0aW9uKHcsZCxzLGwsaSl7d1tsXT13W2xdfHxbXTt3W2xdLnB1c2goeydndG0uc3RhcnQnOgogIG5ldyBEYXRlKCkuZ2V0VGltZSgpLGV2ZW50OidndG0uanMnfSk7dmFyIGY9ZC5nZXRFbGVtZW50c0J5VGFnTmFtZShzKVswXSwKICBqPWQuY3JlYXRlRWxlbWVudChzKSxkbD1sIT0nZGF0YUxheWVyJz8nJmw9JytsOicnO2ouYXN5bmM9dHJ1ZTtqLnNyYz0KICAnaHR0cHM6Ly93d3cuZ29vZ2xldGFnbWFuYWdlci5jb20vZ3RtLmpzP2lkPScraStkbDtmLnBhcmVudE5vZGUuaW5zZXJ0QmVmb3JlKGosZik7CiAgfSkod2luZG93LGRvY3VtZW50LCdzY3JpcHQnLCdkYXRhTGF5ZXInLCdHVE0tVEhWVkxQRCcpOzwvc2NyaXB0PgogIDwhLS0gRW5kIEdvb2dsZSBUYWcgTWFuYWdlciAtLT4KCiAgPCEtLSBTZWdtZW50IEFuYWx5dGljcyAtLT4KICA8c2NyaXB0PgogICAgIWZ1bmN0aW9uKCl7dmFyIGFuYWx5dGljcz13aW5kb3cuYW5hbHl0aWNzPXdpbmRvdy5hbmFseXRpY3N8fFtdO2lmKCFhbmFseXRpY3MuaW5pdGlhbGl6ZSlpZihhbmFseXRpY3MuaW52b2tlZCl3aW5kb3cuY29uc29sZSYmY29uc29sZS5lcnJvciYmY29uc29sZS5lcnJvcigiU2VnbWVudCBzbmlwcGV0IGluY2x1ZGVkIHR3aWNlLiIpO2Vsc2V7YW5hbHl0aWNzLmludm9rZWQ9ITA7YW5hbHl0aWNzLm1ldGhvZHM9WyJ0cmFja1N1Ym1pdCIsInRyYWNrQ2xpY2siLCJ0cmFja0xpbmsiLCJ0cmFja0Zvcm0iLCJwYWdldmlldyIsImlkZW50aWZ5IiwicmVzZXQiLCJncm91cCIsInRyYWNrIiwicmVhZHkiLCJhbGlhcyIsImRlYnVnIiwicGFnZSIsIm9uY2UiLCJvZmYiLCJvbiJdO2FuYWx5dGljcy5mYWN0b3J5PWZ1bmN0aW9uKHQpe3JldHVybiBmdW5jdGlvbigpe3ZhciBlPUFycmF5LnByb3RvdHlwZS5zbGljZS5jYWxsKGFyZ3VtZW50cyk7ZS51bnNoaWZ0KHQpO2FuYWx5dGljcy5wdXNoKGUpO3JldHVybiBhbmFseXRpY3N9fTtmb3IodmFyIHQ9MDt0PGFuYWx5dGljcy5tZXRob2RzLmxlbmd0aDt0Kyspe3ZhciBlPWFuYWx5dGljcy5tZXRob2RzW3RdO2FuYWx5dGljc1tlXT1hbmFseXRpY3MuZmFjdG9yeShlKX1hbmFseXRpY3MubG9hZD1mdW5jdGlvbih0KXt2YXIgZT1kb2N1bWVudC5jcmVhdGVFbGVtZW50KCJzY3JpcHQiKTtlLnR5cGU9InRleHQvamF2YXNjcmlwdCI7ZS5hc3luYz0hMDtlLnNyYz0oImh0dHBzOiI9PT1kb2N1bWVudC5sb2NhdGlvbi5wcm90b2NvbD8iaHR0cHM6Ly8iOiJodHRwOi8vIikrImNkbi5zZWdtZW50LmNvbS9hbmFseXRpY3MuanMvdjEvIit0KyIvYW5hbHl0aWNzLm1pbi5qcyI7dmFyIG49ZG9jdW1lbnQuZ2V0RWxlbWVudHNCeVRhZ05hbWUoInNjcmlwdCIpWzBdO24ucGFyZW50Tm9kZS5pbnNlcnRCZWZvcmUoZSxuKX07YW5hbHl0aWNzLlNOSVBQRVRfVkVSU0lPTj0iNC4wLjAiOwogICAgYW5hbHl0aWNzLmxvYWQoImFOWlhZaXZ0WklmeUFUWFNqZDJhakg0a2pVTkRxMnlJIik7CiAgICB9fSgpOwogIDwvc2NyaXB0PgogIDwhLS0gRW5kIFNlZ21lbnQgQW5hbHl0aWNzIC0tPgoKPC9ib2R5Pgo8L2h0bWw+Cg==
ERROR: Unable to log in; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
