### ISSUE TITLE
VRV list index out of range when parsing en-US MPD information

### ISSUE THREAD

**Issue by Tookmund** [rg3/youtube-dl#14212]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.09.11*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.09.11**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
PS C:\Users\jacob_2\Videos> .\youtube-dl.exe -U
youtube-dl is up-to-date (2017.09.11)
PS C:\Users\jacob_2\Videos> .\youtube-dl.exe --verbose https://vrv.co/watch/GYX084D3R/HarmonQuest:The-Quest-Begins
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://vrv.co/watch/GYX084D3R/HarmonQuest:The-Quest-Begins']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.09.11
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[vrv] GYX084D3R: Downloading webpage
[vrv] GYX084D3R: Downloading en-US MPD information
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp24lzs8ny\build\youtube_dl\__init__.py", line 465, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp24lzs8ny\build\youtube_dl\__init__.py", line 455, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp24lzs8ny\build\youtube_dl\YoutubeDL.py", line 1966, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp24lzs8ny\build\youtube_dl\YoutubeDL.py", line 776, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp24lzs8ny\build\youtube_dl\extractor\common.py", line 434, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp24lzs8ny\build\youtube_dl\extractor\vrv.py", line 132, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp24lzs8ny\build\youtube_dl\extractor\common.py", line 1753, in _extract_mpd_formats
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp24lzs8ny\build\youtube_dl\extractor\common.py", line 1975, in _parse_mpd_formats
IndexError: list index out of range
```

```
PS C:\Users\jacob_2\Videos> .\youtube-dl.exe --verbose https://vrv.co/watch/GR2P9WQ7R/HarmonQuest:The-Stone-Saw-Mines
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://vrv.co/watch/GR2P9WQ7R/HarmonQuest:The-Stone-Saw-Mines']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.09.11
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 3.3.3, ffprobe 3.3.3
[debug] Proxy map: {}
[vrv] GR2P9WQ7R: Downloading webpage
[vrv] GR2P9WQ7R: Downloading en-US MPD information
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp24lzs8ny\build\youtube_dl\__init__.py", line 465, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp24lzs8ny\build\youtube_dl\__init__.py", line 455, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp24lzs8ny\build\youtube_dl\YoutubeDL.py", line 1966, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp24lzs8ny\build\youtube_dl\YoutubeDL.py", line 776, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp24lzs8ny\build\youtube_dl\extractor\common.py", line 434, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp24lzs8ny\build\youtube_dl\extractor\vrv.py", line 132, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp24lzs8ny\build\youtube_dl\extractor\common.py", line 1753, in _extract_mpd_formats
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp24lzs8ny\build\youtube_dl\extractor\common.py", line 1975, in _parse_mpd_formats
IndexError: list index out of range
```

I've only been able to reproduce this issue with episodes 1 & 2 of Harmon Quest Season 1, but I've been able to do so consistently. 
https://vrv.co/watch/GYX084D3R/HarmonQuest:The-Quest-Begins
https://vrv.co/watch/GR2P9WQ7R/HarmonQuest:The-Stone-Saw-Mines
So it's probably a corrupted MPD or something  and perhaps not something youtube-dl can work around.

**Comment by opsoyo** [comment]
I'm having this happen on multiple Dragon Ball Super episodes. It's strange how it will happen a while (about a week or two) for certain episodes but only a brief period for others. 

The first episode of both the original series and the dubbed series have this happen in the same way.

`[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.12.31
[debug] Python version 3.4.4 - Windows-10-10.0.15063
[debug] exe versions: ffmpeg git-2017-12-28-be4dfbf
[debug] Proxy map: {}
[vrv] GRWE0W4KR: Downloading webpage
[vrv] GRWE0W4KR: Downloading ja-JP m3u8 information
[vrv] GRWE0W4KR: Downloading en-US m3u8 information
[vrv] GRWE0W4KR: Downloading es-LA m3u8 information
[vrv] GRWE0W4KR: Downloading pt-BR m3u8 information
[vrv] GRWE0W4KR: Downloading ja-JP MPD information
ERROR: list index out of range
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpheifp6ll\build\youtube_dl\YoutubeDL.py", line 784, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpheifp6ll\build\youtube_dl\extractor\common.py", line 438, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpheifp6ll\build\youtube_dl\extractor\vrv.py", line 132, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpheifp6ll\build\youtube_dl\extractor\common.py", line 1751, in _extract_mpd_formats
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpheifp6ll\build\youtube_dl\extractor\common.py", line 1973, in _parse_mpd_formats
IndexError: list index out of range`

`[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.12.31
[debug] Python version 3.4.4 - Windows-10-10.0.15063
[debug] exe versions: ffmpeg git-2017-12-28-be4dfbf
[debug] Proxy map: {}
[vrv] GYX0W0KNR: Downloading webpage
[vrv] GYX0W0KNR: Downloading en-US m3u8 information
[vrv] GYX0W0KNR: Downloading en-US MPD information
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpheifp6ll\build\youtube_dl\__init__.py", line 465, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpheifp6ll\build\youtube_dl\__init__.py", line 455, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpheifp6ll\build\youtube_dl\YoutubeDL.py", line 1988, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpheifp6ll\build\youtube_dl\YoutubeDL.py", line 784, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpheifp6ll\build\youtube_dl\extractor\common.py", line 438, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpheifp6ll\build\youtube_dl\extractor\vrv.py", line 132, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpheifp6ll\build\youtube_dl\extractor\common.py", line 1751, in _extract_mpd_formats
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpheifp6ll\build\youtube_dl\extractor\common.py", line 1973, in _parse_mpd_formats
IndexError: list index out of range`

https://vrv.co/watch/GRWE0W4KR/ (Original)
https://vrv.co/watch/GYX0W0KNR/ (English dubbed)
