### ISSUE TITLE
Unable to extract title

### ISSUE THREAD

**Issue by sae13** [rg3/youtube-dl#14246]
```
➜  /tmp youtube-dl -v "https://www.youtube.com/watch?v=8-7M1--bbOM&list=PLEZm9Qpp2gIOUhkPjL9SwVp1Lex5Wuyd1"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=8-7M1--bbOM&list=PLEZm9Qpp2gIOUhkPjL9SwVp1Lex5Wuyd1']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.22
[debug] Python version 2.7.12 - Linux-4.4.0-93-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:playlist] Downloading playlist PLEZm9Qpp2gIOUhkPjL9SwVp1Lex5Wuyd1 - add --no-playlist to just download video 8-7M1--bbOM
[youtube:playlist] PLEZm9Qpp2gIOUhkPjL9SwVp1Lex5Wuyd1: Downloading webpage
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 666, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 316, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 1730, in _real_extract
    return self._extract_playlist(playlist_id)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 1700, in _extract_playlist
    page, 'title')
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 620, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 611, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

➜  /tmp 

```

Hi there, I dont know if I must say any detail or not

**Comment by yan12125** [comment]
Version 2016.02.22 is way too old. Please check https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl.
