### ISSUE TITLE
solving opendload 400 bad request

### ISSUE THREAD

**Issue by MuhamadOmr** [rg3/youtube-dl#14299]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.09.15*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.09.15**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

```
I:\youtube-dl>youtube-dl.exe -v http://openload.co/embed/miEoI5oT8JE
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://openload.co/embed/miEoI5oT8JE']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.09.15
[debug] Python version 3.4.4 - Windows-10-10.0.15063
[debug] exe versions: none
[debug] Proxy map: {}
[Openload] miEoI5oT8JE: Downloading webpage
[debug] Default format spec: best
[debug] Invoking downloader on 'https://openload.co/stream/QÅÎôÀr©ZÊÓ$\x1f¬ÊÎôM¦±ZìÐ$\x1f¸ØÎô¤Á©ZÀÐ$\x1f\x00ÅÎô@¦±Zm)Ê\x14êÝÎôY¦±ZÖÐ$\x1f|ÅÎôX¦±ZÔÐ$\x1f(ÅÎôc¦±ZêÐ$\x1foÅÎôJ¦±ZßÐ$\x1f*ÅÎô~¦±ZÅÐ$\x1f_ÅÎôb¦±Z°Ð$\x1fSÅÎôx¦±ZÏÐ$\x1fUÅÎô3¦±ZÞÐ$\x1fCÅÎôS¦±ZÙÐ$\x1fFÅÎô7¦±ZñÐ$\x1f[ÅÎôb¦±ZÖÐ$\x1f*ÅÎôq¦±ZòÐ$\x1fsÅÎôB¦±ZòÐ$\x1f(ÅÎô]¦±ZÔÐ$\x1fZÅÎôl¦±ZÊÐ$\x1f*ÅÎôB¦±ZëÐ$\x1fyÅÎôr¦±ZïÐ$\x1f)ÅÎô\\¦±ZöÐ$\x1fnÅÎô\\¦±ZÆÐ$\x1f(ÅÎôR¦±ZÆÐ$\x1fzÅÎô@¦±Z¬Ð$\x1f?mime=true'
ERROR: unable to download video data: HTTP Error 400: Bad Request
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpl1klaw4y\build\youtube_dl\YoutubeDL.py", line 1874, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpl1klaw4y\build\youtube_dl\YoutubeDL.py", line 1813, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpl1klaw4y\build\youtube_dl\downloader\common.py", line 361, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpl1klaw4y\build\youtube_dl\downloader\http.py", line 286, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpl1klaw4y\build\youtube_dl\downloader\http.py", line 74, in establish_connection
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpl1klaw4y\build\youtube_dl\YoutubeDL.py", line 2177, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
urllib.error.HTTPError: HTTP Error 400: Bad Request

```

---

### Description of your *issue*, suggested solution and other information

when i execute the command it gives me 400 bad request or download a very small size file in bytes of the video that doesn't work
solution maybe the encoding of the openload url string to be set correctly 
as in here 
```
https://openload.co/stream/QÅÎôÀr©ZÊÓ$\x1f¬ÊÎôM¦±ZìÐ$\x1f¸ØÎô¤Á©ZÀÐ$\x1f\x00ÅÎô@¦±Zm)Ê\x14êÝÎôY¦±ZÖÐ$\x1f|ÅÎôX¦±ZÔÐ$\x1f(ÅÎôc¦±ZêÐ$\x1foÅÎôJ¦±ZßÐ$\x1f*ÅÎô~¦±ZÅÐ$\x1f_ÅÎôb¦±Z°Ð$\x1fSÅÎôx¦±ZÏÐ$\x1fUÅÎô3¦±ZÞÐ$\x1fCÅÎôS¦±ZÙÐ$\x1fFÅÎô7¦±ZñÐ$\x1f[ÅÎôb¦±ZÖÐ$\x1f*ÅÎôq¦±ZòÐ$\x1fsÅÎôB¦±ZòÐ$\x1f(ÅÎô]¦±ZÔÐ$\x1fZÅÎôl¦±ZÊÐ$\x1f*ÅÎôB¦±ZëÐ$\x1fyÅÎôr¦±ZïÐ$\x1f)ÅÎô\\¦±ZöÐ$\x1fnÅÎô\\¦±ZÆÐ$\x1f(ÅÎôR¦±ZÆÐ$\x1fzÅÎô@¦±Z¬Ð$\x1f?mime=true
```

**Comment by viethqph00671** [comment]
openload-dl https://openload.co/embed/VeaYZDfeucw/
[Openload] VeaYZDfeucw: Downloading webpage
[Openload] VeaYZDfeucw: Executing JS on webpage
[download] Resuming download at byte 29356032
[download] Destination: eid77972fid4742tid11.mp4-VeaYZDfeucw.mp4
[download] 100% of 53.84MiB in 00:04
