### ISSUE TITLE
Specific video on tv.nrk.no does not download

### ISSUE THREAD

**Issue by forthrin** [rg3/youtube-dl#14304]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.09.15**
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Bug report (encountered problems with youtube-dl)

```
$ youtube-dl --verbose https://tv.nrk.no/serie/skavlan/KMTE50006217/22-09-2017
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://tv.nrk.no/serie/skavlan/KMTE50006217/22-09-2017']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.09.15
[debug] Python version 2.7.10 - Darwin-16.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.3.4, ffprobe 3.3.4, rtmpdump 2.4
[debug] Proxy map: {}
[NRKTV] KMTE50006217: Downloading mediaelement JSON
[NRKTV] KMTE50006217: Downloading f4m manifest
WARNING: Unable to download f4m manifest: HTTP Error 404: Not Found
[NRKTV] KMTE50006217: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 404: Not Found
[NRKTV] KMTE50006217: Downloading f4m manifest
WARNING: Unable to download f4m manifest: HTTP Error 404: Not Found
[NRKTV] KMTE50006217: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 404: Not Found
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 776, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 434, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/nrk.py", line 79, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1072, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

Video does not download. Video plays in browser. Other videos from the same site download.

**Comment by dstftw** [comment]
```
> py -3.6 .\youtube_dl\__main__.py https://tv.nrk.no/serie/skavlan/KMTE50006217/22-09-2017
[NRKTV] KMTE50006217: Downloading mediaelement JSON
[NRKTV] KMTE50006217: Downloading f4m manifest
[NRKTV] KMTE50006217: Downloading m3u8 information
[download] Downloading playlist: Skavlan 22.09.2017
[NRKTV] playlist Skavlan 22.09.2017: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 349
[download] Destination: Skavlan 22.09.2017-KMTE50006217AA.mp4
[download]   0.2% of ~1000.28MiB at  3.38MiB/s ETA 10:01
ERROR: Interrupted by user
```

**Comment by forthrin** [comment]
@dstftw: Tried it again. Now it behaves slightly different. It gets a few errors, but starts downloading, then gets more errors on the fragments. Can you reproduce this?

```
[NRKTV] KMTE50006217: Downloading mediaelement JSON
[NRKTV] KMTE50006217: Downloading f4m manifest
WARNING: Unable to download f4m manifest: HTTP Error 404: Not Found
[NRKTV] KMTE50006217: Downloading m3u8 information
...
[download] Destination: Skavlan 22.09.2017.mp4
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 7 (attempt 1 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 7 (attempt 2 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 7 (attempt 3 of 10)...

```

**Comment by dstftw** [comment]
I can reproduce the behavior from the first log that is also reproduced in browser.
![image](https://user-images.githubusercontent.com/1908898/30775880-a38b2164-a0c6-11e7-8e30-7000a693a6bb.png)
Thus this is clearly server side problem.

**Comment by forthrin** [comment]
The video works in the browser for me. The error in the screenshot usually comes when you've blocked JavaScript or IP adresses.

**Comment by dstftw** [comment]
I can watch other geo restricted videos in browser.

**Comment by forthrin** [comment]
@dstftw: Maybe there is a slight error with the metadata for this particular video that makes youtube-dl fail, but the browser is still able to play it.

**Comment by oky2abbas** [comment]
+1
