### ISSUE TITLE
gfycat.com is broken

### ISSUE THREAD

**Issue by l29ah** [rg3/youtube-dl#14322]
```
‰ youtube-dl -v https://gfycat.com/gifs/detail/UnconsciousLankyIvorygull   
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-n', '-c', '--format', 'best[height<=800]/best', '-v', 'https://gfycat.com/gifs/detail/UnconsciousLankyIvorygull']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.09.24
[debug] Python version 3.4.6 - Linux-4.9.39-unofficial+grsec+-x86_64-Intel-R-_Core-TM-_i5-3320M_CPU_@_2.60GHz-with-gentoo-2.4.1
[debug] exe versions: ffmpeg N-87347-gbba9c1c6bb, ffprobe N-87347-gbba9c1c6bb, rtmpdump 2.4
[debug] Proxy map: {}
[Gfycat] gifs: Downloading video info
ERROR: Gfycat said: gifs does not exist.
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 777, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib64/python3.4/site-packages/youtube_dl/extractor/common.py", line 434, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib64/python3.4/site-packages/youtube_dl/extractor/gfycat.py", line 56, in _real_extract
    raise ExtractorError('Gfycat said: ' + gfy['error'], expected=True)
youtube_dl.utils.ExtractorError: Gfycat said: gifs does not exist.
```

**Comment by sw7tch** [comment]
@l29ah Try changing your URL. Replace "gifs/detail" with "ifr"
