### ISSUE TITLE
Please support https://www.tvnz.co.nz/

### ISSUE THREAD

**Issue by Oberschlumpf007** [rg3/youtube-dl#14356]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.09.24*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ ] I've **verified** and **I assure** that I'm running youtube-dl **2017.09.24**

### Before submitting an *issue* make sure you have:
- [ ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
[stefan@localhost ~]$ youtube-dl --all-subs -v https://www.tvnz.co.nz/shows/when-we-go-to-war
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--all-subs', u'-v', u'https://www.tvnz.co.nz/shows/when-we-go-to-war']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.09.24
[debug] Python version 2.7.5 - Linux-3.10.0-693.2.2.el7.x86_64-x86_64-with-centos-7.4.1708-Core
[debug] exe versions: ffmpeg 2.6.8, ffprobe 2.6.8, rtmpdump 2.4
[debug] Proxy map: {}
[generic] when-we-go-to-war: Requesting header
WARNING: Falling back on generic information extractor.
[generic] when-we-go-to-war: Downloading webpage
[generic] when-we-go-to-war: Extracting information
ERROR: Unsupported URL: https://www.tvnz.co.nz/shows/when-we-go-to-war
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2125, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2539, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2528, in _XML
    parser.feed(text)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 4, column 526
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 777, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 434, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2980, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.tvnz.co.nz/shows/when-we-go-to-war

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
https://www.tvnz.co.nz/shows/dirty-laundry
https://www.tvnz.co.nz/shows/clique
https://www.tvnz.co.nz/shows/the-level
https://www.tvnz.co.nz/shows/apple-tree-yard
https://www.tvnz.co.nz/shows/queen-sugar

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information
Please support https://www.tvnz.co.nz/

**Comment by colexyz** [comment]
Would this not be considered copyright infringement?

**Comment by Oberschlumpf007** [comment]
No, I am living in NZ.

________________________________
Von: Cole Carter <notifications@github.com>
Gesendet: Donnerstag, 28. September 2017 22:34
An: rg3/youtube-dl
Cc: Oberschlumpf007; Author
Betreff: Re: [rg3/youtube-dl] Please support https://www.tvnz.co.nz/ (#14356)


Would this not be considered copyright infringement?

**Comment by ringofyre** [comment]
Shortland Street viewer detected...
