### ISSUE TITLE
AsianCrush site support has broken (at least for two URLs)

### ISSUE THREAD

**Issue by cjfsyntropy** [rg3/youtube-dl#14360]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.09.24*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.09.24**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
$ youtube-dl -v https://www.asiancrush.com/video/005086v/pengi-and-sommi
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.asiancrush.com/video/005086v/pengi-and-sommi']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.09.24
[debug] Python version 2.7.9 - Linux-4.9.0-3-amd64-x86_64-with-debian-8.9
[debug] exe versions: ffmpeg 3.2-2, ffprobe 3.2-2, rtmpdump 2.4
[debug] Proxy map: {}
[AsianCrush] 5086: Downloading JSON metadata
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/cjf/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/home/cjf/bin/youtube-dl/youtube_dl/__init__.py", line 465, in main
  File "/home/cjf/bin/youtube-dl/youtube_dl/__init__.py", line 455, in _real_main
  File "/home/cjf/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1968, in download
  File "/home/cjf/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 777, in extract_info
  File "/home/cjf/bin/youtube-dl/youtube_dl/extractor/common.py", line 434, in extract
  File "/home/cjf/bin/youtube-dl/youtube_dl/extractor/asiancrush.py", line 44, in _real_extract
TypeError: 'int' object has no attribute '__getitem__'

```

---

---

### Description of your *issue*, suggested solution and other information

I have downloaded videos from AsianCrush before (using youtube-dl version 2017.08.27.1). That version can no longer downloaded what I got before and upgrading to the latest version, it seems still broken. Therefore, the AsianCrush site must have changed and broken youtube-dl.

Previously I downloaded https://www.asiancrush.com/video/005086v/pengi-and-sommi
Neither that nor the video detailed in the -v output above work at present. As the output makes clear.

**Comment by jaykay12** [comment]
Noo @cjfsyntropy , apparently it looks like there is no problem with the extractor, Actually the AsianCrush site service is broken for now as they are facing some technical glitch.

![asiancrush_issue](https://user-images.githubusercontent.com/13948542/31159409-647daa6e-a8e6-11e7-9b96-08792596af83.png)

Once they are back to action, hopefully you will be able to use youtube-dl as before :+1:
