### ISSUE TITLE
youtube-dl can't download vooplayer videos

### ISSUE THREAD

**Issue by azkikr** [rg3/youtube-dl#14371]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.09.24*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.09.24**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.vooplayer.com/v3/watch/watch.php?v=NzgwNTg=']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.09.24
[debug] Python version 3.4.4 - Windows-10-10.0.10586
[debug] exe versions: none
[debug] Proxy map: {}
[generic] watch: Requesting header
WARNING: Falling back on generic information extractor.
[generic] watch: Downloading webpage
[generic] watch: Extracting information
ERROR: Unsupported URL: https://www.vooplayer.com/v3/watch/watch.php?v=NzgwNTg=
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp1uop9avr\build\youtube_dl\YoutubeDL.py", line 777, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp1uop9avr\build\youtube_dl\extractor\common.py", line 434, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp1uop9avr\build\youtube_dl\extractor\generic.py", line 2980, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.vooplayer.com/v3/watch/watch.php?v=NzgwNTg=

'clearVars' is not recognized as an internal or external command,
operable program or batch file.
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.vooplayer.com/v3/watch/watch.php?v=NzgwNTg=&clearVars=1
- Single video: 
- Playlist: 

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

hi youtube-dl team!

i've been trying hard to download the video lessons i've purchased for offline learning (similar to what youtube-dl can do to udemy) with youtube-dl but youtube-dl is prompting that it does not support vooplayer urls, example https://www.vooplayer.com/v3/watch/watch.php?v=NzgwNTg=&clearVars=1.

my apologies if i've marked [x] Site support request and [x] Feature request because i'm really not sure what specific request should i make to the youtube-dl team.

i hope your team can help and make downloading of vooplayer videos possible.

thank you for youtube-dl -- it's the best downloader for almost everything! :)

looking forward to your reply.

respectfully yours,
az
![vooplayer_image](https://user-images.githubusercontent.com/32423654/31050349-5db268be-a67a-11e7-9de0-81dc472cd82a.PNG)

**Comment by azkikr** [comment]
thank you dstfw, it's now easy to download vooplayer videos! :) that's really a fast youtube-dl update, WOW!
