### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by Terax235** [rg3/youtube-dl#14397]
I tried to search a video with youtube-dl, and it said:
```
{ Error: Command failed: PRIVATE/node_modules/youtube-dl/bin/youtube-dl --dump-json -f best --no-warnings --force-ipv4 gvsearch1:Human
ERROR: Unable to download webpage: HTTP Error 503: Service Unavailable (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

    at ChildProcess.exithandler (child_process.js:271:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:547:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'PRIVATE/node_modules/youtube-dl/bin/youtube-dl --dump-json -f best --no-warnings --force-ipv4 gvsearch1:Human' }
```

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
