### ISSUE TITLE
New NBC website bug.

### ISSUE THREAD

**Issue by michaelcrossland** [rg3/youtube-dl#14419]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.10.01*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ ] I've **verified** and **I assure** that I'm running youtube-dl **2017.10.01**

### Before submitting an *issue* make sure you have:
- [ ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2017.10.01
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

Okay I can download the NBC Nightly News for the time being as the old nbcnews.com website for that show is still up. But NBC is moving all of there old nbcnews.com shows from there to the new nbc.com website. I have tried this with both NBC Nightly News and Dateline, Dateline still has it's old nbcnews.com site but only for older eps a year plus back. If you want the new shows you have to use nbc.com not nbcnews.com site.
here is what youtube-dl puts out be it on the nightly news or there dateline shows on the new NBC.com site.

youtube-dl -v -F https://www.nbc.com/dateline/video/frantic/3592972
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-F', u'https://www.nbc.com/dateline/video/frantic/3592972']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.10.01
[debug] Python version 2.7.13 - Linux-4.10.0-36-generic-x86_64-with-Ubuntu-17.04-zesty
[debug] exe versions: ffmpeg 3.2.4-1build2, ffprobe 3.2.4-1build2, rtmpdump 2.4
[debug] Proxy map: {}
[NBC] 3592972: Downloading JSON metadata
Traceback (most recent call last):
  File "/usr/bin/youtube-dl", line 6, in <module>
    youtube_dl.main()
  File "/home/michael/.local/lib/python2.7/site-packages/youtube_dl/__init__.py", line 465, in main
    _real_main(argv)
  File "/home/michael/.local/lib/python2.7/site-packages/youtube_dl/__init__.py", line 455, in _real_main
    retcode = ydl.download(all_urls)
  File "/home/michael/.local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 1974, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/home/michael/.local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 783, in extract_info
    ie_result = ie.extract(url)
  File "/home/michael/.local/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 434, in extract                                                                                  
    ie_result = self._real_extract(url)                                                                                                                                                         
  File "/home/michael/.local/lib/python2.7/site-packages/youtube_dl/extractor/nbc.py", line 78, in _real_extract                                                                                
    })['data'][0]['attributes']                                                                                                                                                                 
IndexError: list index out of range

This IndexError happens on any of the new nbc.com webite's show. As I can't get the Dish Network mod to work, I think it's because Dish keeps playing games with how it has sites do the rerouting to get the key need to to login with there info.
But I can get the NBC Nightly news from https://www.nbcnews.com/nightly-news and as I have said the old https://www.nbcnews.com/dateline site is still there and I can get the videos off of that site but they are over a year or more old. I hope someone can take some time and look into this love this tool works better then any of the paid stuff on M$ Windows.
If I know more about how to program for python I would try my hand at it but I don't understand alot of what python does. So I will stay with what I know C C++ and other scripting langs.

**Comment by michaelcrossland** [comment]
would you be nice to point to the # that this is a dup of thanks. I looked
but there are so many tickets that did not see this in the list. thanks

On Oct 5, 2017 8:55 AM, "Sergey M." <notifications@github.com> wrote:

Closed #14419 <https://github.com/rg3/youtube-dl/issues/14419>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/rg3/youtube-dl/issues/14419#event-1279964503>, or mute
the thread
