### ISSUE TITLE
FFmpegPostProcessorError: Could not write header for output file #0

### ISSUE THREAD

**Issue by elisar80** [rg3/youtube-dl#14444]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.10.07*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2017.10.07**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

```
youtube-dl http://www.bbc.com/news/video_and_audio/must_see/41510708/kelo-the-parrot-ni-football-team-s-biggest-feathered-fan --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'http://www.bbc.com/news/video_and_audio/must_see/41510708/kelo-the-parrot-ni-football-team-s-biggest-feathered-fan', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.10.07
[debug] Python version 2.7.12 - Linux-4.4.0-53-generic-x86_64-with-LinuxMint-18.1-serena
[debug] exe versions: avconv 2.8.11-0ubuntu0.16.04.1, avprobe 2.8.11-0ubuntu0.16.04.1, ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1, rtmpdump 2.4-n111-gitfa8646d-ppa9p2
[debug] Proxy map: {}
[bbc] kelo-the-parrot-ni-football-team-s-biggest-feathered-fan: Downloading webpage
[bbc] p05j3srv: Downloading media selection XML
[bbc] p05j3srv: Downloading m3u8 information
[bbc] p05j3srv: Downloading m3u8 information
[bbc] p05j3srv: Downloading MPD manifest
[bbc] p05j3srv: Downloading m3u8 information
[bbc] p05j3srv: Downloading m3u8 information
[bbc] p05j3srv: Downloading MPD manifest
[bbc] p05j3srv: Downloading m3u8 information
[bbc] p05j3srv: Downloading m3u8 information
[bbc] p05j3srv: Downloading MPD manifest
[bbc] p05j3srv: Downloading m3u8 information
[bbc] p05j3srv: Downloading m3u8 information
[bbc] p05j3srv: Downloading MPD manifest
[download] Downloading playlist: Must See
[bbc] playlist Must See: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://vod-dash-ww-live.bbcfmt.hs.llnwd.net/usp/auth/vod/piff_abr_full_sd/8085f5-p05j3srv/vf_p05j3srv_936f7165-72b7-47b2-a3e0-394d5faded8b.ism.hlsv2.ism/dash/'
[dashsegments] Total fragments: 13
[download] Destination: Kelo the parrot chirps his support for Northern Ireland.-p05j3srv.fstream-nonuk-iptv_streaming_concrete_combined_sd_mf_limelight_world_dash_https-video=1570000.mp4
[download] 100% of 7.90MiB in 00:35
[debug] Invoking downloader on u'https://vod-dash-ww-live.bbcfmt.hs.llnwd.net/usp/auth/vod/piff_abr_full_sd/8085f5-p05j3srv/vf_p05j3srv_936f7165-72b7-47b2-a3e0-394d5faded8b.ism.hlsv2.ism/dash/'
[dashsegments] Total fragments: 13
[download] Destination: Kelo the parrot chirps his support for Northern Ireland.-p05j3srv.fstream-nonuk-iptv_streaming_concrete_combined_sd_mf_limelight_world_dash_https-audio_eng_1=128000.m4a
[download] 100% of 662.43KiB in 00:06
[ffmpeg] Merging formats into "Kelo the parrot chirps his support for Northern Ireland.-p05j3srv.mp4"
[debug] ffmpeg command line: avconv -y -i 'file:Kelo the parrot chirps his support for Northern Ireland.-p05j3srv.fstream-nonuk-iptv_streaming_concrete_combined_sd_mf_limelight_world_dash_https-video=1570000.mp4' -i 'file:Kelo the parrot chirps his support for Northern Ireland.-p05j3srv.fstream-nonuk-iptv_streaming_concrete_combined_sd_mf_limelight_world_dash_https-audio_eng_1=128000.m4a' -c copy -map '0:v:0' -map '1:a:0' 'file:Kelo the parrot chirps his support for Northern Ireland.-p05j3srv.temp.mp4'
ERROR: Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2026, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 479, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 204, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
FFmpegPostProcessorError: Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument

<end of log>
```

---

### Description of your *issue*, suggested solution and other information

The issue applies to all videos on BBC News. It worked fine until a few days/weeks ago. 
I read similar topics. Most solutions involved updating the ffmpeg, but I couldn't find a newer version and I believe my ffmpeg is up to date.

**Comment by dstftw** [comment]
Outdated ffmpeg.
