### ISSUE TITLE
Site support request: DAZN.com

### ISSUE THREAD

**Issue by bahhhhh** [rg3/youtube-dl#14445]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.10.07*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.10.07**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.dazn.com/en-CA/competition/Competition:wy3kluvb4efae1of0d8146c1/ArticleId:f8nvxa8g55ty12hyzllyr0iei']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.10.07
[debug] Python version 2.7.10 - Darwin-17.0.0-x86_64-i386-64bit
[debug] exe versions: avconv 12.2, avprobe 12.2, ffmpeg 3.3.4, ffprobe 3.3.4, phantomjs 2.1.1
[debug] Proxy map: {}
[generic] ArticleId:f8nvxa8g55ty12hyzllyr0iei: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ArticleId:f8nvxa8g55ty12hyzllyr0iei: Downloading webpage
[generic] ArticleId:f8nvxa8g55ty12hyzllyr0iei: Extracting information
ERROR: Unsupported URL: https://www.dazn.com/en-CA/competition/Competition:wy3kluvb4efae1of0d8146c1/ArticleId:f8nvxa8g55ty12hyzllyr0iei
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2156, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2539, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2528, in _XML
    parser.feed(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: mismatched tag: line 45, column 2
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 434, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3051, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.dazn.com/en-CA/competition/Competition:wy3kluvb4efae1of0d8146c1/ArticleId:f8nvxa8g55ty12hyzllyr0iei
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.dazn.com/en-CA/competition/Competition:wy3kluvb4efae1of0d8146c1/ArticleId:f8nvxa8g55ty12hyzllyr0iei

---

### Description of your *issue*, suggested solution and other information

No issue.

**Comment by Hrxn** [comment]
Account required?

**Comment by bahhhhh** [comment]
@Hrxn Yes, an account is required. My mistake - forgot to specify.

**Comment by fagits** [comment]
has this website been added?

**Comment by Hrxn** [comment]
Not yet...

**Comment by PlaceboPRS** [comment]
Would it help if you were provided with a working login?

**Comment by rein-10** [comment]
does it help that dazn has now added chromecast support?

**Comment by dirkf** [comment]
No.
