### ISSUE TITLE
Can't watch CBC The National newscast video

### ISSUE THREAD

**Issue by rkm-github** [rg3/youtube-dl#14458]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.10.07*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.10.07**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
./youtube-dl -v http://www.cbc.ca/player/play/1067218499691 >>error.txt 2>>error.txt
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'http://www.cbc.ca/player/play/1067218499691']
[debug] Encodings: locale ISO-8859-1, fs ISO-8859-1, out None, pref ISO-8859-1
[debug] youtube-dl version 2017.10.07
[debug] Python version 2.7.13 - Linux-4.9.9-i686-with-glibc2.0
[debug] exe versions: none
[debug] Proxy map: {}
[ThePlatform] 1067218499691: Downloading SMIL data
[ThePlatform] 1067218499691: Checking video URL
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "./youtube-dl/__main__.py", line 19, in <module>
  File "./youtube-dl/youtube_dl/__init__.py", line 465, in main
  File "./youtube-dl/youtube_dl/__init__.py", line 455, in _real_main
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 1980, in download
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 795, in extract_info
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 861, in process_ie_result
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 784, in extract_info
  File "./youtube-dl/youtube_dl/extractor/common.py", line 434, in extract
  File "./youtube-dl/youtube_dl/extractor/theplatform.py", line 295, in _real_extract
  File "./youtube-dl/youtube_dl/extractor/theplatform.py", line 49, in _extract_theplatform_smil
  File "./youtube-dl/youtube_dl/extractor/common.py", line 1666, in _parse_smil_formats
  File "./youtube-dl/youtube_dl/extractor/common.py", line 1170, in _is_valid_url
  File "./youtube-dl/youtube_dl/extractor/common.py", line 503, in _request_webpage
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 2190, in urlopen
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "./youtube-dl/youtube_dl/utils.py", line 1086, in https_open
  File "/usr/lib/python2.7/urllib2.py", line 1195, in do_open
    h.request(req.get_method(), req.get_selector(), req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1263, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python2.7/ssl.py", line 363, in wrap_socket
    _context=self)
  File "/usr/lib/python2.7/ssl.py", line 611, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 848, in do_handshake
    match_hostname(self.getpeercert(), self.server_hostname)
  File "/usr/lib/python2.7/ssl.py", line 282, in match_hostname
    % (hostname, ', '.join(map(repr, dnsnames))))
ssl.CertificateError: hostname u'progressive.cbc.ca' doesn't match either of '*.akamaized.net', '*.akamaihd-staging.net', '*.akamaized-staging.net', '*.akamaihd.net', 'a248.e.akamai.net'

...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://www.cbc.ca/player/play/1067218499691

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

I used to be able to watch videos from http://www.cbc.ca/player/, but for a few weeks now I have not been able to, and I always get error messages such as the one I've reported here.

**Comment by fluks** [comment]
There's some sort of an SSL certificate error. At least for a temporary fix you can pass `--no-check-certificate` option to youtube-dl.

**Comment by yan12125** [comment]
In browsers another SMIL url is used:
```
http://link.theplatform.com/s/ExhSPC/2B6xu7LZUAzW/meta.smil?format=smil&mbr=true&manifest=m3u
```
