### ISSUE TITLE
[youtube] Can't download recently finished broadcast.

### ISSUE THREAD

**Issue by ficofabrid** [rg3/youtube-dl#14479]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.10.12**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

```
C:\Users\User>youtube-dl -v https://www.youtube.com/watch?v=ELUCUFQp1_k
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=ELUCUFQp1_k']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2017.10.12
[debug] Python version 3.4.4 - Windows-10-10.0.15063
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] ELUCUFQp1_k: Downloading webpage
[youtube] ELUCUFQp1_k: Downloading video info webpage
[youtube] ELUCUFQp1_k: Extracting video information
[youtube] ELUCUFQp1_k: Downloading MPD manifest
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://r3---sn-gvnuxaxjvh-5c5e.googlevideo.com/videoplayback?requiressl=yes&expire=1507877736&itag=18&signature=0F3E3E3EFBFB541F1EACC11FB2D7D05ED33DE7A2.75620A6D2348AD91819D4563CAFB3A769932DA4C&key=yt6&ms=lv&id=ELUCUFQp1_k.0&ei=CA_gWZz4DcaudM7hn8gM&mv=m&pl=18&mt=1507856060&sparams=ei%2Cgcr%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&mn=sn-gvnuxaxjvh-5c5e&gcr=ru&source=youtube&mm=32&ipbits=0&ratebypass=yes&initcwndbps=940000&ip=2.61.71.203&mime=video%2Fmp4'
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmphdp9utoa\build\youtube_dl\YoutubeDL.py", line 1892, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmphdp9utoa\build\youtube_dl\YoutubeDL.py", line 1831, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmphdp9utoa\build\youtube_dl\downloader\common.py", line 361, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmphdp9utoa\build\youtube_dl\downloader\http.py", line 286, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmphdp9utoa\build\youtube_dl\downloader\http.py", line 74, in establish_connection
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmphdp9utoa\build\youtube_dl\YoutubeDL.py", line 2195, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found
```
https://www.youtube.com/watch?v=ELUCUFQp1_k
It's temporary issue, so example would be useless in time.

**Comment by dstftw** [comment]
Most likely requested format wasn't yet encoded at the time of a request.
