### ISSUE TITLE
Thanks for allowing me use your code freely. Please see the problem below!

### ISSUE THREAD

**Issue by chidiigwe** [rg3/youtube-dl#14491]
I do not know what the following description means. But I know that you will find out. Youtube-dl failed me for the first time and I just wanted to let you know. Knowing about this may help you as you continue to make the code better. Thanks for your help to the community.
```
youtube-dl https://www.youtube.com/watch?v=yDv5FIAeyoY
[youtube] yDv5FIAeyoY: Downloading webpage
[youtube] yDv5FIAeyoY: Downloading video info webpage
[youtube] yDv5FIAeyoY: Extracting video information
WARNING: unable to extract uploader nickname
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1081, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 969, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflwcUIMe/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflwcUIMe/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
root@ubuntu:...# apt install youtube-dl
Reading package lists... Done
Building dependency tree       
Reading state information... Done
youtube-dl is already the newest version (2017.03.26-1).
```

**Comment by Hrxn** [comment]
Jesus, can you please try to fix your text formatting here?

**Comment by yan12125** [comment]
Some points:

1. **NEVER** install youtube-dl from apt-get. Check https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl and install version 2017.10.12.
2. Don't run youtube-dl as root.
