### ISSUE TITLE
"Failed to parse JSON" on Reddit Video link

### ISSUE THREAD

**Issue by hay** [rg3/youtube-dl#14495]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.10.15*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.10.15**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl --verbose "https://www.reddit.com/r/AnimalsBeingDerps/comments/74k652/so_cute_she_cant_stand_it/?st=J8J7L0M3&sh=6b05cdab"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.reddit.com/r/AnimalsBeingDerps/comments/74k652/so_cute_she_cant_stand_it/?st=J8J7L0M3&sh=6b05cdab']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.10.15
[debug] Python version 2.7.13 - Darwin-16.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.3, ffprobe 3.3
[debug] Proxy map: {}
[RedditR] 74k652: Downloading JSON metadata
ERROR: 74k652: Failed to parse JSON  (caused by ValueError('No JSON object could be decoded',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 691, in _parse_json
    return json.loads(json_string)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 434, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/reddit.py", line 89, in _real_extract
    url + '.json', video_id)[0]['data']['children'][0]['data']
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 685, in _download_json
    json_string, video_id, transform_source=transform_source, fatal=fatal)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 695, in _parse_json
    raise ExtractorError(errmsg, cause=ve)
ExtractorError: 74k652: Failed to parse JSON  (caused by ValueError('No JSON object could be decoded',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

---
### Description of your *issue*, suggested solution and other information
I've tried downloading [this video](https://www.reddit.com/r/AnimalsBeingDerps/comments/74k652/so_cute_she_cant_stand_it/?st=J8J7L0M3&sh=6b05cdab) but i'm getting a "Failed to parse JSON" error. [Here's another link](https://www.reddit.com/r/AnimalsBeingJerks/comments/75ooqf/oh_is_that_your_phone/?st=J8PLVR7I&sh=55036867) that has the same issue. `youtube-dl` is working fine if i use the `fallback_url` from the `.json` link (e.g. `https://v.redd.it/f0ytj9lj17rz/DASH_4_8_M`).

**Comment by hay** [comment]
@dstftw awesome, thanks!
