### ISSUE TITLE
Soundcloud search with multiple words query not working

### ISSUE THREAD

**Issue by bitnol** [rg3/youtube-dl#14505]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.10.15.1*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.10.15.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[root@vmi81951 ~]# youtube-dl -s --verbose scsearch10:chal chaiyaa
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-s', u'--verbose', u'scsearch10:chal', u'chaiyaa']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.10.15.1
[debug] Python version 2.7.5 - Linux-3.10.0-693.2.2.el7.x86_64-x86_64-with-centos-7.4.1708-Core
[debug] exe versions: none
[debug] Proxy map: {}
[download] Downloading playlist: chal
[soundcloud:search] chal: Downloading page 1
[soundcloud:search] playlist chal: Downloading 10 videos
[download] Downloading video 1 of 10
[soundcloud] 216248090: Downloading info JSON
[soundcloud] 216248090: Downloading track url
[soundcloud] 216248090: Downloading m3u8 information
[soundcloud] 216248090: Downloading m3u8 information
[soundcloud] 216248090: Checking hls_opus_64_url video format URL
[soundcloud] 216248090: Checking hls_mp3_128_url video format URL
[soundcloud] 216248090: Checking http_mp3_128_url video format URL
[debug] Default format spec: bestvideo+bestaudio/best
[download] Downloading video 2 of 10
[soundcloud] 146963718: Downloading info JSON
[soundcloud] 146963718: Downloading track url
[soundcloud] 146963718: Downloading m3u8 information
[soundcloud] 146963718: Downloading m3u8 information
[soundcloud] 146963718: Checking hls_opus_64_url video format URL
[soundcloud] 146963718: Checking hls_mp3_128_url video format URL
[soundcloud] 146963718: Checking http_mp3_128_url video format URL
[debug] Default format spec: bestvideo+bestaudio/best
[download] Downloading video 3 of 10
[soundcloud] 325037787: Downloading info JSON
[soundcloud] 325037787: Downloading track url
[soundcloud] 325037787: Downloading m3u8 information
[soundcloud] 325037787: Checking hls_mp3_128_url video format URL
[soundcloud] 325037787: Checking http_mp3_128_url video format URL
[debug] Default format spec: bestvideo+bestaudio/best
[download] Downloading video 4 of 10
[soundcloud] 171750419: Downloading info JSON
[soundcloud] 171750419: Downloading track url
[soundcloud] 171750419: Downloading m3u8 information
[soundcloud] 171750419: Downloading m3u8 information
[soundcloud] 171750419: Checking hls_opus_64_url video format URL
[soundcloud] 171750419: Checking hls_mp3_128_url video format URL
[soundcloud] 171750419: Checking http_mp3_128_url video format URL
[debug] Default format spec: bestvideo+bestaudio/best
[download] Downloading video 5 of 10
[soundcloud] 283156700: Downloading info JSON
[soundcloud] 283156700: Downloading track url
[soundcloud] 283156700: Downloading m3u8 information
[soundcloud] 283156700: Downloading m3u8 information
[soundcloud] 283156700: Checking hls_opus_64_url video format URL
[soundcloud] 283156700: Checking hls_mp3_128_url video format URL
[soundcloud] 283156700: Checking http_mp3_128_url video format URL
[debug] Default format spec: bestvideo+bestaudio/best
[download] Downloading video 6 of 10
[soundcloud] 113628520: Downloading info JSON
[soundcloud] 113628520: Downloading track url
[soundcloud] 113628520: Downloading m3u8 information
[soundcloud] 113628520: Downloading m3u8 information
[soundcloud] 113628520: Checking hls_opus_64_url video format URL
[soundcloud] 113628520: Checking hls_mp3_128_url video format URL
[soundcloud] 113628520: Checking http_mp3_128_url video format URL
[debug] Default format spec: bestvideo+bestaudio/best
[download] Downloading video 7 of 10
[soundcloud] 100082830: Downloading info JSON
[soundcloud] 100082830: Downloading track url
[soundcloud] 100082830: Downloading m3u8 information
[soundcloud] 100082830: Downloading m3u8 information
[soundcloud] 100082830: Checking hls_opus_64_url video format URL
[soundcloud] 100082830: Checking hls_mp3_128_url video format URL
[soundcloud] 100082830: Checking http_mp3_128_url video format URL
[debug] Default format spec: bestvideo+bestaudio/best
[download] Downloading video 8 of 10
[soundcloud] 15780941: Downloading info JSON
[soundcloud] 15780941: Downloading track url
[soundcloud] 15780941: Downloading m3u8 information
[soundcloud] 15780941: Downloading m3u8 information
[soundcloud] 15780941: Checking hls_opus_64_url video format URL
[soundcloud] 15780941: Checking hls_mp3_128_url video format URL
[soundcloud] 15780941: Checking http_mp3_128_url video format URL
[debug] Default format spec: bestvideo+bestaudio/best
[download] Downloading video 9 of 10
[soundcloud] 216110308: Downloading info JSON
[soundcloud] 216110308: Downloading track url
[soundcloud] 216110308: Downloading m3u8 information
[soundcloud] 216110308: Downloading m3u8 information
[soundcloud] 216110308: Checking hls_opus_64_url video format URL
[soundcloud] 216110308: Checking hls_mp3_128_url video format URL
[soundcloud] 216110308: Checking http_mp3_128_url video format URL
[debug] Default format spec: bestvideo+bestaudio/best
[download] Downloading video 10 of 10
[soundcloud] 311647914: Downloading info JSON
[soundcloud] 311647914: Downloading track url
[soundcloud] 311647914: Downloading m3u8 information
[soundcloud] 311647914: Checking hls_mp3_128_url video format URL
[soundcloud] 311647914: Checking http_mp3_128_url video format URL
[debug] Default format spec: bestvideo+bestaudio/best
[download] Finished downloading playlist: chal
ERROR: u'chaiyaa' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:chaiyaa" ) to search YouTube
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 434, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2049, in _real_extract
    % (url, url), expected=True)
ExtractorError: u'chaiyaa' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:chaiyaa" ) to search YouTube

```

### Description of your *issue*, suggested solution and other information

Issue is related to the Soundcloud search. Normally it works well when the query have single word. Issue happens when the query has multiple words like 'one two three'.

youtube-dl scsearch10:one two three

Above command is returning results for "one" only, not for whole query.

Although query with multiple words works in YouTube search but it have the following format
youtube-dl "ytsearch10:one two three"

I have tried using the quotes in the Soundcloud search but then it doesn't work.
youtube-dl "scsearch10:one two three"

**Comment by dstftw** [comment]
```
PS C:\Dev\youtube-dl\master> py -2.7 .\youtube_dl\__main__.py "scsearch10:one two three"
[download] Downloading playlist: one two three
[soundcloud:search] one two three: Downloading page 1
[soundcloud:search] playlist one two three: Downloading 10 videos
[download] Downloading video 1 of 10
[soundcloud] 185095698: Downloading info JSON
[soundcloud] 185095698: Downloading track url
[soundcloud] 185095698: Downloading m3u8 information
[soundcloud] 185095698: Downloading m3u8 information
[soundcloud] 185095698: Checking hls_opus_64_url video format URL
[soundcloud] 185095698: Checking hls_mp3_128_url video format URL
[soundcloud] 185095698: Checking http_mp3_128_url video format URL
[download] Destination: One Two Three Britney Spears -Nightcore-185095698.mp3
[download] 100% of 2.38MiB in 00:00
[download] Downloading video 2 of 10
[soundcloud] 98244374: Downloading info JSON
[soundcloud] 98244374: Downloading track url
[soundcloud] 98244374: Downloading m3u8 information
[soundcloud] 98244374: Downloading m3u8 information
[soundcloud] 98244374: Checking hls_opus_64_url video format URL
[soundcloud] 98244374: Checking hls_mp3_128_url video format URL
[soundcloud] 98244374: Checking http_mp3_128_url video format URL
[download] Destination: One Two Three Four (Full Audio Song) - Chennai Express [2013]-98244374.mp3
[download]  14.3% of 3.49MiB at 440.14KiB/s ETA 00:06
ERROR: Interrupted by user
```
