### ISSUE TITLE
[arte] crash if video is not available anymore

### ISSUE THREAD

**Issue by cladisch** [rg3/youtube-dl#14503]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.10.15.1**

- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

- [x] Bug report (encountered problems with youtube-dl)

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.arte.tv/de/videos/067736-000-A/der-weihnachtskuchen/']
[debug] Encodings: locale ISO-8859-1, fs ISO-8859-1, out ISO-8859-1, pref ISO-8859-1
[debug] youtube-dl version 2017.10.15.1
[debug] Python version 2.7.14 - Linux-4.13.0-rc7+-x86_64-AMD_Phenom-tm-_II_X6_1090T_Processor-with-slackware-14.2
[debug] exe versions: ffmpeg 3.3.4, ffprobe 3.3.4
[debug] Proxy map: {}
[arte.tv:+7] der-weihnachtskuchen: Downloading webpage
[arte.tv:+7] der-weihnachtskuchen: Downloading JSON metadata
ERROR: An extractor error has occurred. (caused by KeyError(u'VSR',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/extractor/common.py", line 434, in extract
    ie_result = self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/arte.py", line 211, in _real_extract
    return self._extract_from_webpage(webpage, video_id, lang)
  File "./youtube-dl/youtube_dl/extractor/arte.py", line 254, in _extract_from_webpage
    return self._extract_from_json_url(json_url, video_id, lang, title=title)
  File "./youtube-dl/youtube_dl/extractor/arte.py", line 83, in _extract_from_json_url
    vsr = player_info['VSR']
KeyError: u'VSR'
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 447, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
ExtractorError: An extractor error has occurred. (caused by KeyError(u'VSR',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

If the video is no longer available, the extractor tries to access a key that does not exist in the JSON file.

The changes made for recent issues #13945 and #14112 did not actually fix this.
As far as I can see, that line should have used `.get()`.

**Comment by dstftw** [comment]
Using `get` won't solve anything.
