### ISSUE TITLE
error in downloading vimeo videos

### ISSUE THREAD

**Issue by azkikr** [rg3/youtube-dl#14530]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.10.15.1*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.10.15.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [x] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
PS D:\> youtube-dl -v "https://player.vimeo.com/video/161263135" --referer "https://www.wp101com/tutorial/installing-woo
commerce/"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://player.vimeo.com/video/161263135', '--referer', 'https://www.wp101com/tutoria
l/installing-woocommerce/']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2017.10.15.1
[debug] Python version 3.6.1 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[vimeo] 161263135: Downloading webpage
ERROR: Cannot download embed-only video without embedding URL. Please call youtube-dl with the URL of the page that embe
ds this video.
Traceback (most recent call last):
  File "c:\users\work\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\extractor\common.py", line 503
, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "c:\users\work\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\YoutubeDL.py", line 2195, in u
rlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "c:\users\work\appdata\local\programs\python\python36\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "c:\users\work\appdata\local\programs\python\python36\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\users\work\appdata\local\programs\python\python36\lib\urllib\request.py", line 570, in error
    return self._call_chain(*args)
  File "c:\users\work\appdata\local\programs\python\python36\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "c:\users\work\appdata\local\programs\python\python36\lib\urllib\request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\work\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\extractor\vimeo.py", line 470,
 in _real_extract
    webpage, urlh = self._download_webpage_handle(request, video_id)
  File "c:\users\work\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\extractor\common.py", line 532
, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query
)
  File "c:\users\work\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\extractor\common.py", line 512
, in _request_webpage
    raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
youtube_dl.utils.ExtractorError: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbi
dden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt
-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\users\work\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\extractor\common.py", line 503
, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "c:\users\work\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\YoutubeDL.py", line 2195, in u
rlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "c:\users\work\appdata\local\programs\python\python36\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "c:\users\work\appdata\local\programs\python\python36\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\users\work\appdata\local\programs\python\python36\lib\urllib\request.py", line 570, in error
    return self._call_chain(*args)
  File "c:\users\work\appdata\local\programs\python\python36\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "c:\users\work\appdata\local\programs\python\python36\lib\urllib\request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\work\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\extractor\vimeo.py", line 470,
 in _real_extract
    webpage, urlh = self._download_webpage_handle(request, video_id)
  File "c:\users\work\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\extractor\common.py", line 532
, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query
)
  File "c:\users\work\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\extractor\common.py", line 512
, in _request_webpage
    raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
youtube_dl.utils.ExtractorError: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbi
dden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt
-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\work\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\YoutubeDL.py", line 784, in ex
tract_info
    ie_result = ie.extract(url)
  File "c:\users\work\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\extractor\common.py", line 434
, in extract
    ie_result = self._real_extract(url)
  File "c:\users\work\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\extractor\vimeo.py", line 484,
 in _real_extract
    expected=True)
youtube_dl.utils.ExtractorError: Cannot download embed-only video without embedding URL. Please call youtube-dl with the
 URL of the page that embeds this video.
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://player.vimeo.com/video/161263135 
referer >> https://www.wp101com/tutorial/installing-woocommerce/
- Single video: 
- Playlist: 

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

i've also tried downloading the following...
https://player.vimeo.com/video/161263264 referer >> https://www.wp101com/tutorial/woocommerce-general-settings/
https://player.vimeo.com/video/161263420 referer >> https://www.wp101com/tutorial/woocommerce-products-settings/

**Comment by dstftw** [comment]
Referer does not look valid.

**Comment by azkikr** [comment]
thank you dstftw! thanks for pointing-it-out, it really was just a missing " . " on the wp101com, it should've been wp101.com, my mistake :)
