### ISSUE TITLE
Unable to download imdb.com's videos.

### ISSUE THREAD

**Issue by antdude** [rg3/youtube-dl#14557]
```
$ youtube-dl -vvv http://www.imdb.com/list/ls025720609/videoplayer/vi3478894873
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-vvv', 'http://www.imdb.com/list/ls025720609/videoplayer/vi3478894873']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.10.20
[debug] Python version 3.4.2 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.9
[debug] exe versions: ffmpeg 3.2.5-1, ffprobe 3.2.5-1, rtmpdump 2.4
[debug] Proxy map: {}
[imdb:list] ls025720609: Downloading webpage
ERROR: Unable to extract list title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/common.py", line 434, in extract
    ie_result = self._real_extract(url)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/imdb.py", line 121, in _real_extract
    r'<h1 class="header">(.*?)</h1>', webpage, 'list title')
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/common.py", line 806, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/common.py", line 797, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract list title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

Thank you in advance. :)

**Comment by goggle** [comment]
Have you found this exact URL on imdb.com? It seems as though "list" and "videoplayer" get mixed up. The "real" video link http://www.imdb.com/videoplayer/vi3478894873 seems to work with youtube-dl.

**Comment by antdude** [comment]
Goggle, how did you manage to get that video URL?

**Comment by goggle** [comment]
I first removed the last part of your posted URL http://www.imdb.com/list/ls025720609/videoplayer/vi3478894873, so I opened http://www.imdb.com/list/ls025720609. This is a regular list of videos, but I did not find your video in this list. So I was suspicious, and removed the list/ls025720609 part from the first URL to get to the video directly.

**Comment by antdude** [comment]
Oh wow, impressive find. :+1:

**Comment by vapeurs** [comment]
Mark as solved, than?

**Comment by goggle** [comment]
I'm not sure. If the URL posted by antdude is a valid URL, youtube-dl should be able to handle this case.

**Comment by antdude** [comment]
Not solved. We shouldn't be able to dig for those playlist's specific video URLs to be able to download.

**Comment by antdude** [comment]
https://www.imdb.com/list/ls025720609/videoplayer/vi3082730265 is another example. :(

**Comment by IoanPaleru** [comment]
Is there any way you can make youtube-dl automatically find and download the correct video for an .aspx link on imdb.com like this one "https://www.imdb.com/title/tt0107659/videoplayer/vi2761425177?ref_=tt_ov_vi"? How do you download those videos? Thanks.
