### ISSUE TITLE
Dramafever - Unable to login

### ISSUE THREAD

**Issue by diwanr** [rg3/youtube-dl#14556]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.10.20*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X ] I've **verified** and **I assure** that I'm running youtube-dl **2017.10.20**

### Before submitting an *issue* make sure you have:
- [X ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'--dump-pages', u'--proxy', u'socks5://192.168.1.1:1000/', u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'-f', u'list', u'--playlist-items', u'1', u'--write-sub', u'--sub-lang', u'English', u'https://www.dramafever.com/drama/5040/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.10.20
[debug] Python version 2.7.13 - Linux-4.9.0-4-amd64-x86_64-with-debian-9.2
[debug] exe versions: ffmpeg 3.2.8-1, ffprobe 3.2.8-1
[debug] Proxy map: {u'http': u'socks5://192.168.1.1:1000/', u'https': u'socks5://192.168.1.1:1000/'}
[debug] Using fake IP 3.90.100.148 (US) as X-Forwarded-For.
[dramafever:series] Logging in as **redacted**
[dramafever:series] Dumping request to https://www.dramafever.com/accounts/login/
PCFkb2N0eXBlIGh0bWw+CjxodG1sIG5nLWFwcD0iZHJhbWFmZXZlciIgbmctY29udHJvbGxlcj0iREZBcHBsaWNhdGlvbkNvbnRyb2xsZXIgYXMgcm0iPgo8aGVhZD4KICA8bWV0YSBjaGFyc2V0PSJ1dGYtOCI+CiAgPHRpdGxlIG5nLWJpbmQ9InJtLm1ldGEoKS50aXRsZSI+V2F0Y2ggS29yZWFuIERyYW1hIEZyZWUgfCBLb3JlYW4gTW92aWVzIE9ubGluZSAmIFRlbGVub3ZlbGEgfCBEcmFtYUZldmVyIHwgS0RyYW1hPC90aXRsZT4KCiAgPCEtLSBidWlsZDpiYXNlIC0tPgogIDxiYXNlIGhyZWY9Ii8iPgogIDwhLS0gZW5kYnVpbGQgLS0+CgogIDxtZXRhIG5hbWU9ImRlc2NyaXB0aW9uIiBjb250ZW50PSJ7e3JtLm1ldGEoKS5kZXNjcmlwdGlvbn19Ij4KICA8bWV0YSBuYW1lPSJrZXl3b3JkcyIgY29udGVudD0ie3sgcm0ubWV0YSgpLmtleXdvcmRzIH19Ij4KCiAgPG1ldGEgbmFtZT0idmlld3BvcnQiIGNvbnRlbnQ9IndpZHRoPWRldmljZS13aWR0aCI+CiAgPG1ldGEgbmFtZT0iZHJhbWFmZXZlcjpoZWFsdGgiIGNvbnRlbnQ9Imdvb2QiPgoKICA8IS0tIFR3aXR0ZXIgQ2FyZCBJbmZvcm1hdGlvbiAtLT4KICA8bWV0YSBuYW1lPSJ0d2l0dGVyOmNhcmQiIGNvbnRlbnQ9InN1bW1hcnlfbGFyZ2VfaW1hZ2UiPgogIDxtZXRhIG5hbWU9InR3aXR0ZXI6dGl0bGUiIGNvbnRlbnQ9Int7cm0ubWV0YSgpLnRpdGxlfX0iPgogIDxtZXRhIG5hbWU9InR3aXR0ZXI6c2l0ZSIgY29udGVudD0iRHJhbWFmZXZlciI+CiAgPG1ldGEgbmFtZT0idHdpdHRlcjpkZXNjcmlwdGlvbiIgY29udGVudD0ie3tybS5tZXRhKCkuZGVzY3JpcHRpb259fSI+CiAgPG1ldGEgbmFtZT0idHdpdHRlcjpjcmVhdG9yIiBjb250ZW50PSJEcmFtYWZldmVyIj4KICA8bWV0YSBuYW1lPSJ0d2l0dGVyOmltYWdlOnNyYyIgY29udGVudD0ie3tybS5tZXRhKCkuaW1hZ2UgfCBidWlsZFBhdGg6IHRydWV9fSI+CgogIDwhLS0gT3Blbi1HcmFwaCBJbmZvcm1hdGlvbiAtLT4KICA8bWV0YSBwcm9wZXJ0eT0ib2c6dHlwZSIgY29udGVudD0iYXJ0aWNsZSI+CiAgPG1ldGEgcHJvcGVydHk9Im9nOnRpdGxlIiBjb250ZW50PSJ7e3JtLm1ldGEoKS50aXRsZX19Ij4KICA8bWV0YSBwcm9wZXJ0eT0ib2c6c2l0ZV9uYW1lIiBjb250ZW50PSJEcmFtYWZldmVyIj4KICA8bWV0YSBwcm9wZXJ0eT0ib2c6ZGVzY3JpcHRpb24iIGNvbnRlbnQ9Int7cm0ubWV0YSgpLmRlc2NyaXB0aW9ufX0iPgogIDxtZXRhIHByb3BlcnR5PSJvZzppbWFnZSIgY29udGVudD0ie3tybS5tZXRhKCkuaW1hZ2UgfCBidWlsZFBhdGg6IHRydWV9fSI+CiAgPG1ldGEgcHJvcGVydHk9Im9nOnVybCIgY29udGVudD0ie3tybS5hYnNVcmwoKX19Ij4KICA8bWV0YSBwcm9wZXJ0eT0ib2c6bG9jYWxlIiBjb250ZW50PSJ7e3JtLlVybExhbmd1YWdlLmFjdGl2ZUxhbmd1YWdlfX0iPgogIDxtZXRhIHByb3BlcnR5PSJmYjphcHBfaWQiIGNvbnRlbnQ9IkBAZmFjZWJvb2suYXBwX2lkIj4KICA8bWV0YSBwcm9wZXJ0eT0iZmI6YWRtaW5zIiBjb250ZW50PSI3MjUwNDE0MjMsNTAzODc5Njg1LDc2OTQxMzUwMywxMjA5NTksMTE1NzI1MTI3MCI+CgoKICA8bWV0YSBwcm9wZXJ0eT0ib2c6dmlkZW8iIGNvbnRlbnQ9Int7cm0uYWJzVXJsKCl9fSIgbmctaWY9InJtLm1ldGEoKS5oYXNWaWRlbyI+CgogIDxtZXRhIHByb3BlcnR5PSJvZzp2aWRlbzp1cmwiIGNvbnRlbnQ9Int7cm0uYWJzVXJsKCl9fSIgbmctaWY9InJtLm1ldGEoKS5oYXNWaWRlbyI+CiAgPG1ldGEgcHJvcGVydHk9Im9nOnZpZGVvOnR5cGUiIGNvbnRlbnQ9InZpZGVvL21wNCIgbmctaWY9InJtLm1ldGEoKS5oYXNWaWRlbyI+CiAgPG1ldGEgcHJvcGVydHk9Im9nOnZpZGVvOndpZHRoIiBjb250ZW50PSI2NDAiIG5nLWlmPSJybS5tZXRhKCkuaGFzVmlkZW8iPgogIDxtZXRhIHByb3BlcnR5PSJvZzp2aWRlbzpoZWlnaHQiIGNvbnRlbnQ9IjM3NSIgbmctaWY9InJtLm1ldGEoKS5oYXNWaWRlbyI+CiAgPG1ldGEgbmFtZT0idmlkZW9fdHlwZSIgY29udGVudD0idmlkZW8vbXA0IiBuZy1pZj0icm0ubWV0YSgpLmhhc1ZpZGVvIj4KICA8bWV0YSBuYW1lPSJtZWRpdW0iIGNvbnRlbnQ9InZpZGVvIiBuZy1pZj0icm0ubWV0YSgpLmhhc1ZpZGVvIj4KICA8bWV0YSBuYW1lPSJ2aWRlb193aWR0aCIgY29udGVudD0iMTAwJSIgbmctaWY9InJtLm1ldGEoKS5oYXNWaWRlbyI+CiAgPG1ldGEgbmFtZT0idmlkZW9faGVpZ2h0IiBjb250ZW50PSIxMDAlIiBuZy1pZj0icm0ubWV0YSgpLmhhc1ZpZGVvIj4KCiAgPGxpbmsgcmVsPSJhcHBsZS10b3VjaC1pY29uLXByZWNvbXBvc2VkIiBzaXplcz0iMTUyeDE1MiIgaHJlZj0ie3snaW1hZ2VzL2Zhdmljb24tMTUyeDE1Mi5wbmcnIHwgYnVpbGRQYXRofX0iPgogIDxsaW5rIHJlbD0iYXBwbGUtdG91Y2gtaWNvbi1wcmVjb21wb3NlZCIgc2l6ZXM9IjE0NHgxNDQiIGhyZWY9Int7J2ltYWdlcy9mYXZpY29uLTE0NHgxNDQucG5nJyB8IGJ1aWxkUGF0aH19Ij4KICA8bGluayByZWw9ImFwcGxlLXRvdWNoLWljb24tcHJlY29tcG9zZWQiIHNpemVzPSIxMjB4MTIwIiBocmVmPSJ7eydpbWFnZXMvZmF2aWNvbi0xMjB4MTIwLnBuZycgfCBidWlsZFBhdGh9fSI+CiAgPGxpbmsgcmVsPSJhcHBsZS10b3VjaC1pY29uLXByZWNvbXBvc2VkIiBzaXplcz0iMTE0eDExNCIgaHJlZj0ie3snaW1hZ2VzL2Zhdmljb24tMTE0eDExNC5wbmcnIHwgYnVpbGRQYXRofX0iPgogIDxsaW5rIHJlbD0iYXBwbGUtdG91Y2gtaWNvbi1wcmVjb21wb3NlZCIgc2l6ZXM9IjcyeDcyIiBocmVmPSJ7eydpbWFnZXMvZmF2aWNvbi03Mng3Mi5wbmcnIHwgYnVpbGRQYXRofX0iPgogIDxsaW5rIHJlbD0iYXBwbGUtdG91Y2gtaWNvbi1wcmVjb21wb3NlZCIgaHJlZj0ie3snaW1hZ2VzL2Zhdmljb24tNTd4NTcucG5nJyB8IGJ1aWxkUGF0aH19Ij4KICA8bGluayByZWw9Imljb24iIGhyZWY9Int7J2ltYWdlcy9mYXZpY29uLTMyeDMyLnBuZycgfCBidWlsZFBhdGh9fSIgc2l6ZXM9IjMyeDMyIj4KCiAgPGxpbmsgbmctaHJlZj0ie3snc3R5bGVzL2ZvbnRhc3RpYy5jc3MnIHwgYnVpbGRQYXRofX0iIHJlbD0ic3R5bGVzaGVldCIgdHlwZT0idGV4dC9jc3MiPgogIDxsaW5rIGhyZWY9Imh0dHBzOi8vZm9udHMuZ29vZ2xlYXBpcy5jb20vY3NzP2ZhbWlseT1PcGVuK1NhbnM6NDAwLDcwMHxSYWxld2F5OjQwMCw3MDAsODAwIiByZWw9InN0eWxlc2hlZXQiPgoKICA8IS0tIGJvd2VyOmNzcyAtLT4KICA8bGluayByZWw9InN0eWxlc2hlZXQiIGhyZWY9ImJ1aWxkcy81Ny9saWJzLm1pbi5jc3MiPgogIDwhLS0gZW5kaW5qZWN0IC0tPgoKICA8IS0tIGluamVjdDpjc3MgLS0+CiAgPGxpbmsgcmVsPSJzdHlsZXNoZWV0IiBocmVmPSJidWlsZHMvNTcvZHJhbWFmZXZlci5taW4uY3NzIj4KICA8IS0tIGVuZGluamVjdCAtLT4KCiAgPHNjcmlwdD53aW5kb3cuYXBwQ29uZmlnID0geyAiYXBwbGljYXRpb24iOnsic3RvcmFnZSI6ImxvY2FsIiwiaWQiOiJ3d3ciLCJ1cmwiOiJodHRwczovL3d3dy5kcmFtYWZldmVyLmNvbSJ9LCJyYXZlbiI6eyJkc24iOiJodHRwczovLzliMjA1YWFlNjhhZTQ5YTA4OWNiNGYzZWRkYTk3MWM1QHNlbnRyeS5pby8xNjAyMTUifSwgInN3aWZ0eXBlIjp7ImVuZ2luZUtleSI6IkN5d3p5c2NKQUhLQ3dyZXpmenBOIn0sICJidWlsZCI6IHsiaWQiOiI1NyIsImRlc3RpbmF0aW9uIjoiZGlzdC9idWlsZHMvNTciLCJkZXN0T25seSI6Ii9idWlsZHMvNTcifSwgImZhY2Vib29rUGl4ZWwiOiB7ImlkIjoiMTExMjQ0MDYxMTIwIn0sICJmcmVld2hlZWwiOiB7InVybCI6Imh0dHBzOi8vNWUwZDIudi5md21ybS5uZXQvYWQvZy8xIiwibnciOiIzODUyMzQiLCJwcm9mIjoiMzg1MjM0OmRmX2h0bWw1X2Rlc2t0b3BfbGl2ZSIsInJlc3AiOiJ2YXN0MyIsImNzaWQiOiJkZl9kZXNrdG9wX2VwaXNvZGVfaHRtbDUiLCJhc253IjoiMzg1MjM0Iiwic3NudyI6IjM4NTIzNCIsImZsYWciOiIrYW1jYitleHZ0K2VtY3IrYWV0aStzbHRwIiwibWV0ciI6IjEwMjMiLCJwbGF0Zm9ybSI6IndlYiIsImVudiI6InByb2QiLCJuaWVsc29uIjoiWTBnNU5ESnhaVkZpUXpKdk9tMHpkbk41TTNnNU9YUjNPRFkzZVVkcVZUTlEiLCJpT1MiOnsicHJvZiI6IjM4NTIzNDpkZl9pb3N3ZWJfbGl2ZSIsImNzaWQiOiJkZl9tb2JpbGV3ZWJfaW9zX3ZpZGVvIn0sImFuZHJvaWQiOnsicHJvZiI6IjM4NTIzNDpkZl9hbmRyb2lkd2ViX2xpdmUiLCJjc2lkIjoiZGZfbW9iaWxld2ViX2FuZHJvaWRfdmlkZW8ifSwidGltZW91dCI6MX0sICJjb21TY29yZSI6IHsiYzIiOiIxNDkwOTcwMSIsInN0YXRpb25UaXRsZSI6IkRSQU1BRkVWRVIiLCJkaWN0aW9uYXJ5IjoiRFJBTUFGRVZFUiJ9LCAieW91Ym9yYSI6IHsiYWNjb3VudENvZGUiOiJkcmFtYWZldmVyIiwiZW5hYmxlQW5hbHl0aWNzIjp0cnVlLCJjaGFubmVsIjoiZHJhbWFmZXZlciJ9IH07PC9zY3JpcHQ+CgogIDwhLS0gRmFjZWJvb2sgUGl4ZWwgQ29kZSBub3QgaWRlYWwgcGxhY2UgYnV0IHRoaXMgaXMgd2hlcmUgRmFjZWJvb2sgd2FudHMgdGhlIHNjcmlwdCB0byBiZS4tLT4KICA8c2NyaXB0PgogICFmdW5jdGlvbihmLGIsZSx2LG4sdCxzKXtpZihmLmZicSlyZXR1cm47bj1mLmZicT1mdW5jdGlvbigpe24uY2FsbE1ldGhvZD8KICBuLmNhbGxNZXRob2QuYXBwbHkobixhcmd1bWVudHMpOm4ucXVldWUucHVzaChhcmd1bWVudHMpfTtpZighZi5fZmJxKWYuX2ZicT1uOwogIG4ucHVzaD1uO24ubG9hZGVkPSEwO24udmVyc2lvbj0nMi4wJztuLnF1ZXVlPVtdO3Q9Yi5jcmVhdGVFbGVtZW50KGUpO3QuYXN5bmM9ITA7CiAgdC5zcmM9djtzPWIuZ2V0RWxlbWVudHNCeVRhZ05hbWUoZSlbMF07cy5wYXJlbnROb2RlLmluc2VydEJlZm9yZSh0LHMpfSh3aW5kb3csCiAgZG9jdW1lbnQsJ3NjcmlwdCcsJ2h0dHBzOi8vY29ubmVjdC5mYWNlYm9vay5uZXQvZW5fVVMvZmJldmVudHMuanMnKTsKCiAgZmJxKCdpbml0JywgJzExMTI0NDA2MTEyMCcpOwogIDwvc2NyaXB0PgogIDxub3NjcmlwdD48aW1nIGhlaWdodD0iMSIgd2lkdGg9IjEiIHN0eWxlPSJkaXNwbGF5Om5vbmUiIHNyYz0iaHR0cHM6Ly93d3cuZmFjZWJvb2suY29tL3RyP2lkPTExMTI0NDA2MTEyMCZldj1QYWdlVmlldyZub3NjcmlwdD0xIj48L25vc2NyaXB0PgogIDwhLS0gRW5kIEZhY2Vib29rIFBpeGVsIENvZGUgLS0+CgogIDwhLS0gd2IgZGZwIG92ZXJyaWRlIC0tPgogIDxzY3JpcHQgYXN5bmMgc3JjPSIvL2pzLXNlYy5pbmRleHd3LmNvbS9odC9odHctd2IuanMiIHR5cGU9InRleHQvamF2YXNjcmlwdCI+PC9zY3JpcHQ+CiAgPHNjcmlwdCB0eXBlPSJ0ZXh0L2phdmFzY3JpcHQiPgogICAgICB3aW5kb3cuZ29vZ2xldGFnID0gd2luZG93Lmdvb2dsZXRhZyB8fCB7fTsKICAgICAgZ29vZ2xldGFnLmNtZCA9IHdpbmRvdy5nb29nbGV0YWcuY21kIHx8IFtdOwogICAgICBnb29nbGV0YWcuY21kLnB1c2goZnVuY3Rpb24oKSB7CiAgICAgICAgICBpZiAodHlwZW9mIHdpbmRvdy5oZWFkZXJ0YWcgPT09ICd1bmRlZmluZWQnIHx8IHdpbmRvdy5oZWFkZXJ0YWcuYXBpUmVhZHkgIT09IHRydWUpIHsKICAgICAgICAgICAgICB3aW5kb3cuaGVhZGVydGFnID0gZ29vZ2xldGFnOwogICAgICAgICAgfQogICAgICB9KTsKICA8L3NjcmlwdD4KICA8IS0tIGVuZCB3YiBkZnAgb3ZlcnJpZGUgLS0+CjwvaGVhZD4KPGJvZHk+CiAgPGRpdiBuZy1pbmNsdWRlPSIncGFydGlhbHMvaGVhZGVyL21vYmlsZS1uYXYuaHRtbCciPjwvZGl2PgogIDxkaXYgY2xhc3M9InNpdGUtY29udGFpbmVyIiB1aS12aWV3IGF1dG9zY3JvbGw9InRydWUiIG5nLWNsYXNzPSJ7b3BlbmJ1cmdlcjpybS5hY3RpdmVNb2JpbGVNZW51IH0iPjwvZGl2PgogIDxzZWFyY2g6b3ZlcmxheT48L3NlYXJjaDpvdmVybGF5PgoKICA8IS0tIGJvd2VyOmpzIC0tPgogIDxzY3JpcHQgc3JjPSJidWlsZHMvNTcvbGlicy5taW4uanMiPjwvc2NyaXB0PgogIDwhLS0gZW5kaW5qZWN0IC0tPgoKICA8IS0tIGluamVjdDptb2R1bGVzIC0tPgogIDxzY3JpcHQgc3JjPSJidWlsZHMvNTcvZHJhbWFmZXZlci1idW5kbGUuanMiPjwvc2NyaXB0PgogIDwhLS0gZW5kaW5qZWN0IC0tPgoKICA8IS0tIGluamVjdDpqcyAtLT4KICA8c2NyaXB0IHNyYz0iYnVpbGRzLzU3L2RyYW1hZmV2ZXIubWluLmpzIj48L3NjcmlwdD4KICA8IS0tIGVuZGluamVjdCAtLT4KCiAgPCEtLSBpbmplY3Q6cGFydGlhbHMgLS0+CiAgPHNjcmlwdCBzcmM9ImJ1aWxkcy81Ny9kcmFtYWZldmVyLnRlbXBsYXRlcy5qcyI+PC9zY3JpcHQ+CiAgPCEtLSBlbmRpbmplY3QgLS0+CgogIDxzY3JpcHQgdHlwZT0idGV4dC9qYXZhc2NyaXB0Ij4KICAgIC8vU2VudHJ5IENvbmZpZwogICAgUmF2ZW4uY29uZmlnKCdodHRwczovLzliMjA1YWFlNjhhZTQ5YTA4OWNiNGYzZWRkYTk3MWM1QHNlbnRyeS5pby8xNjAyMTUnLCB7CiAgICAgIHJlbGVhc2U6ICc1NycKICAgIH0pLmluc3RhbGwoKTsKICAgIC8vR29vZ2xlIEFuYWx5dGljcwogICAgKGZ1bmN0aW9uKGkscyxvLGcscixhLG0pe2lbJ0dvb2dsZUFuYWx5dGljc09iamVjdCddPXI7aVtyXT1pW3JdfHxmdW5jdGlvbigpewogICAgKGlbcl0ucT1pW3JdLnF8fFtdKS5wdXNoKGFyZ3VtZW50cyl9LGlbcl0ubD0xKm5ldyBEYXRlKCk7YT1zLmNyZWF0ZUVsZW1lbnQobyksCiAgICBtPXMuZ2V0RWxlbWVudHNCeVRhZ05hbWUobylbMF07YS5hc3luYz0xO2Euc3JjPWc7bS5wYXJlbnROb2RlLmluc2VydEJlZm9yZShhLG0pCiAgICB9KSh3aW5kb3csZG9jdW1lbnQsJ3NjcmlwdCcsJ2h0dHBzOi8vd3d3Lmdvb2dsZS1hbmFseXRpY3MuY29tL2FuYWx5dGljcy5qcycsJ2dhJyk7CgogICAgZ2EoJ2NyZWF0ZScsICdVQS01MjU0NzM3LTEnLCAnYXV0bycpOwogIDwvc2NyaXB0PgoKICA8ZGl2IGlkPSJmYi1yb290Ij48L2Rpdj4KICA8c2NyaXB0PihmdW5jdGlvbihkLCBzLCBpZCkgewogICAgdmFyIGpzLCBmanMgPSBkLmdldEVsZW1lbnRzQnlUYWdOYW1lKHMpWzBdOwogICAgaWYgKGQuZ2V0RWxlbWVudEJ5SWQoaWQpKSByZXR1cm47CiAgICBqcyA9IGQuY3JlYXRlRWxlbWVudChzKTsganMuaWQgPSBpZDsKICAgIGpzLnNyYyA9ICIvL2Nvbm5lY3QuZmFjZWJvb2submV0L2VuX1VTL3Nkay5qcyN4ZmJtbD0xJnZlcnNpb249djIuNyI7CiAgICBmanMucGFyZW50Tm9kZS5pbnNlcnRCZWZvcmUoanMsIGZqcyk7CiAgfShkb2N1bWVudCwgJ3NjcmlwdCcsICdmYWNlYm9vay1qc3NkaycpKTs8L3NjcmlwdD4KCiAgPCEtLSBHb29nbGUgVGFnIE1hbmFnZXIgLS0+CiAgPHNjcmlwdD4oZnVuY3Rpb24odyxkLHMsbCxpKXt3W2xdPXdbbF18fFtdO3dbbF0ucHVzaCh7J2d0bS5zdGFydCc6CiAgbmV3IERhdGUoKS5nZXRUaW1lKCksZXZlbnQ6J2d0bS5qcyd9KTt2YXIgZj1kLmdldEVsZW1lbnRzQnlUYWdOYW1lKHMpWzBdLAogIGo9ZC5jcmVhdGVFbGVtZW50KHMpLGRsPWwhPSdkYXRhTGF5ZXInPycmbD0nK2w6Jyc7ai5hc3luYz10cnVlO2ouc3JjPQogICdodHRwczovL3d3dy5nb29nbGV0YWdtYW5hZ2VyLmNvbS9ndG0uanM/aWQ9JytpK2RsO2YucGFyZW50Tm9kZS5pbnNlcnRCZWZvcmUoaixmKTsKICB9KSh3aW5kb3csZG9jdW1lbnQsJ3NjcmlwdCcsJ2RhdGFMYXllcicsJ0dUTS1USFZWTFBEJyk7PC9zY3JpcHQ+CiAgPCEtLSBFbmQgR29vZ2xlIFRhZyBNYW5hZ2VyIC0tPgoKICA8IS0tIFNlZ21lbnQgQW5hbHl0aWNzIC0tPgogIDxzY3JpcHQ+CiAgICAhZnVuY3Rpb24oKXt2YXIgYW5hbHl0aWNzPXdpbmRvdy5hbmFseXRpY3M9d2luZG93LmFuYWx5dGljc3x8W107aWYoIWFuYWx5dGljcy5pbml0aWFsaXplKWlmKGFuYWx5dGljcy5pbnZva2VkKXdpbmRvdy5jb25zb2xlJiZjb25zb2xlLmVycm9yJiZjb25zb2xlLmVycm9yKCJTZWdtZW50IHNuaXBwZXQgaW5jbHVkZWQgdHdpY2UuIik7ZWxzZXthbmFseXRpY3MuaW52b2tlZD0hMDthbmFseXRpY3MubWV0aG9kcz1bInRyYWNrU3VibWl0IiwidHJhY2tDbGljayIsInRyYWNrTGluayIsInRyYWNrRm9ybSIsInBhZ2V2aWV3IiwiaWRlbnRpZnkiLCJyZXNldCIsImdyb3VwIiwidHJhY2siLCJyZWFkeSIsImFsaWFzIiwiZGVidWciLCJwYWdlIiwib25jZSIsIm9mZiIsIm9uIl07YW5hbHl0aWNzLmZhY3Rvcnk9ZnVuY3Rpb24odCl7cmV0dXJuIGZ1bmN0aW9uKCl7dmFyIGU9QXJyYXkucHJvdG90eXBlLnNsaWNlLmNhbGwoYXJndW1lbnRzKTtlLnVuc2hpZnQodCk7YW5hbHl0aWNzLnB1c2goZSk7cmV0dXJuIGFuYWx5dGljc319O2Zvcih2YXIgdD0wO3Q8YW5hbHl0aWNzLm1ldGhvZHMubGVuZ3RoO3QrKyl7dmFyIGU9YW5hbHl0aWNzLm1ldGhvZHNbdF07YW5hbHl0aWNzW2VdPWFuYWx5dGljcy5mYWN0b3J5KGUpfWFuYWx5dGljcy5sb2FkPWZ1bmN0aW9uKHQpe3ZhciBlPWRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoInNjcmlwdCIpO2UudHlwZT0idGV4dC9qYXZhc2NyaXB0IjtlLmFzeW5jPSEwO2Uuc3JjPSgiaHR0cHM6Ij09PWRvY3VtZW50LmxvY2F0aW9uLnByb3RvY29sPyJodHRwczovLyI6Imh0dHA6Ly8iKSsiY2RuLnNlZ21lbnQuY29tL2FuYWx5dGljcy5qcy92MS8iK3QrIi9hbmFseXRpY3MubWluLmpzIjt2YXIgbj1kb2N1bWVudC5nZXRFbGVtZW50c0J5VGFnTmFtZSgic2NyaXB0IilbMF07bi5wYXJlbnROb2RlLmluc2VydEJlZm9yZShlLG4pfTthbmFseXRpY3MuU05JUFBFVF9WRVJTSU9OPSI0LjAuMCI7CiAgICBhbmFseXRpY3MubG9hZCgiYU5aWFlpdnRaSWZ5QVRYU2pkMmFqSDRralVORHEyeUkiKTsKICAgIH19KCk7CiAgPC9zY3JpcHQ+CiAgPCEtLSBFbmQgU2VnbWVudCBBbmFseXRpY3MgLS0+Cgo8L2JvZHk+CjwvaHRtbD4K
ERROR: Unable to log in; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 433, in extract
    self.initialize()
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 391, in initialize
    self._real_initialize()
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/dramafever.py", line 41, in _real_initialize
    self._login()
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/dramafever.py", line 66, in _login
    raise ExtractorError('Unable to log in')
ExtractorError: Unable to log in; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### Description of your *issue*, suggested solution and other information

While trying to grab a video from dramafever, it is now saying it is unable to login. I can still login using this username and password on the main site through a browser.
This issue occurs with or without the socks5 proxy enabled.

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

**Comment by diwanr** [comment]
When you mean, "cant-reproduce" do you mean you can successfully grab the above link without any issues or that you do not have an account with dramafever to reproduce this issue?

Thanks

**Comment by dstftw** [comment]
The former.

**Comment by aurora-of-earth** [comment]
@remitamine @diwanr  close this issue as <a href="https://www.dramafever.com/">dramafever</a> is no longer available. #20868
