### ISSUE TITLE
Funimation: cannot parse json

### ISSUE THREAD

**Issue by viruscmd** [rg3/youtube-dl#14569]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.10.20*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.10.20**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [X] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

**Command run** `pbpaste | youtube-dl -u username -p 'password' -a - --restrict-filename --verbose`

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'-a', u'-', u'--restrict-filename', u'--verbose']
[debug] Batch file urls: [u'https://funimation.com/shows/prince-of-stride-alternative/home-the-one-and-only/', u'https://funimation.com/shows/prince-of-stride-alternative/stand-up-because-you-were-there/', u'https://funimation.com/shows/prince-of-stride-alternative/high-touch-for-you-who-gave-me-the-smile/', u'https://funimation.com/shows/prince-of-stride-alternative/end-of-summer-and-beyond/', u'https://funimation.com/shows/prince-of-stride-alternative/on-your-mark-the-beginning-of-destiny/', u'https://funimation.com/shows/prince-of-stride-alternative/believe-i-will-always-be-here/', u'https://funimation.com/shows/prince-of-stride-alternative/galaxy-now-the-stars-shine/', u'https://funimation.com/shows/prince-of-stride-alternative/run-when-the-mind-is-full/', u'https://funimation.com/shows/prince-of-stride-alternative/again-just-you-only-you/', u'https://funimation.com/shows/prince-of-stride-alternative/team-connect-emotions-become-the-wind/', u'https://funimation.com/shows/prince-of-stride-alternative/rival-a-promise-for-august/', u'https://funimation.com/shows/prince-of-stride-alternative/wall-chasing-still-so-far-away/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.10.20
[debug] Python version 2.7.10 - Darwin-17.0.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2
[debug] Proxy map: {}
[Funimation] Logging in as virus.cmd@gmail.com
[Funimation] home-the-one-and-only: Downloading webpage
WARNING: [Funimation] home-the-one-and-only: Failed to parse JSON No JSON object could be decoded
ERROR: Unable to extract al:web:url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 434, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/funimation.py", line 97, in _real_extract
    ], webpage, fatal=True)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 927, in _html_search_meta
    html, display_name, fatal=fatal, group='content', **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 806, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 797, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract al:web:url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output....
<end of log>
```

---

### Sites list (content of pbpaste):
https://funimation.com/shows/prince-of-stride-alternative/home-the-one-and-only/
https://funimation.com/shows/prince-of-stride-alternative/stand-up-because-you-were-there/
https://funimation.com/shows/prince-of-stride-alternative/high-touch-for-you-who-gave-me-the-smile/
https://funimation.com/shows/prince-of-stride-alternative/end-of-summer-and-beyond/
https://funimation.com/shows/prince-of-stride-alternative/on-your-mark-the-beginning-of-destiny/
https://funimation.com/shows/prince-of-stride-alternative/believe-i-will-always-be-here/
https://funimation.com/shows/prince-of-stride-alternative/galaxy-now-the-stars-shine/
https://funimation.com/shows/prince-of-stride-alternative/run-when-the-mind-is-full/
https://funimation.com/shows/prince-of-stride-alternative/again-just-you-only-you/
https://funimation.com/shows/prince-of-stride-alternative/team-connect-emotions-become-the-wind/
https://funimation.com/shows/prince-of-stride-alternative/rival-a-promise-for-august/
https://funimation.com/shows/prince-of-stride-alternative/wall-chasing-still-so-far-away/

---

**Comment by viruscmd** [comment]
Has there been any progress on this?

**Comment by viruscmd** [comment]
# Example  stream url

-  (1920x1080) [https://d132fumi6di1wa.cloudfront.net/FunimationStoreFront/1609152/English/1609152_English_7633c2d7-de61-e711-8175-020165574d09_Layer9.m3u8](https://d132fumi6di1wa.cloudfront.net/FunimationStoreFront/1609152/English/1609152_English_7633c2d7-de61-e711-8175-020165574d09_Layer9.m3u8)
- (1440x810) [https://d132fumi6di1wa.cloudfront.net/FunimationStoreFront/1609152/English/1609152_English_7633c2d7-de61-e711-8175-020165574d09_Layer8.m3u8](https://d132fumi6di1wa.cloudfront.net/FunimationStoreFront/1609152/English/1609152_English_7633c2d7-de61-e711-8175-020165574d09_Layer8.m3u8)
- (960x540) [https://d132fumi6di1wa.cloudfront.net/FunimationStoreFront/1609152/English/1609152_English_7633c2d7-de61-e711-8175-020165574d09_Layer5.m3u8](https://d132fumi6di1wa.cloudfront.net/FunimationStoreFront/1609152/English/1609152_English_7633c2d7-de61-e711-8175-020165574d09_Layer5.m3u8)
- (640x360) [https://d132fumi6di1wa.cloudfront.net/FunimationStoreFront/1609152/English/1609152_English_7633c2d7-de61-e711-8175-020165574d09_Layer4.m3u8](https://d132fumi6di1wa.cloudfront.net/FunimationStoreFront/1609152/English/1609152_English_7633c2d7-de61-e711-8175-020165574d09_Layer4.m3u8)
- (480x270) [https://d132fumi6di1wa.cloudfront.net/FunimationStoreFront/1609152/English/1609152_English_7633c2d7-de61-e711-8175-020165574d09_Layer2.m3u8](https://d132fumi6di1wa.cloudfront.net/FunimationStoreFront/1609152/English/1609152_English_7633c2d7-de61-e711-8175-020165574d09_Layer2.m3u8)
- (416x234) [https://d132fumi6di1wa.cloudfront.net/FunimationStoreFront/1609152/English/1609152_English_7633c2d7-de61-e711-8175-020165574d09_Layer1.m3u8](https://d132fumi6di1wa.cloudfront.net/FunimationStoreFront/1609152/English/1609152_English_7633c2d7-de61-e711-8175-020165574d09_Layer1.m3u8)

**Comment by ElonSatoshi** [comment]
Damn. I can't download Dragon Ball.

**Comment by eyemirror** [comment]
I have no idea how to code it but here is how to grab the stream and the subtitles

From episode page (https://www.funimation.com/shows/aokana-four-rhythm-across-the-blue/udon/)
Curl the page with headers (Browser agent, etc)
Find <meta property="og:video:url" content="
which gives you <meta property="og:video:url" content="/player/572567">

Go to https://www.funimation.com/player/572567/
and find "screenshots": [
which gives you "screenshots": ["https://d132fumi6di1wa.cloudfront.net/exp/FunimationStoreFront/1777600/English/1777600_English_62eb807c-466f-e811-8175-020165574d09.mp4"],
and "screenshots": ["https://d132fumi6di1wa.cloudfront.net/exp/FunimationStoreFront/1777600/English/1777600_English_62eb807c-466f-e811-8175-020165574d09.m3u8"],
replace .m3u8 with _Layer10.m3u8

Subtitles can be found under "textTracks": 
"textTracks": [{"src": "https://d132fumi6di1wa.cloudfront.net/FunimationStoreFront/1777600/English/1777600_English_61eb807c-466f-e811-8175-020165574d09.vtt", "kind": "subtitle", "type": "CC", "language": "en", "label": "English"}, {"src": "https://d132fumi6di1wa.cloudfront.net/FunimationStoreFront/1777600/English/1777600_English_63eb807c-466f-e811-8175-020165574d09.dfxp", "kind": "subtitle", "type": "CC", "language": "en", "label": "English"}, {"src": "https://d132fumi6di1wa.cloudfront.net/FunimationStoreFront/1777600/English/1777600_English_64eb807c-466f-e811-8175-020165574d09.srt", "kind": "subtitle", "type": "CC", "language": "en", "label": "English"}]},

**Comment by eyemirror** [comment]
To get the ID's for each episode in the series you can curl the series page (view-source:https://www.funimation.com/shows/aokana-four-rhythm-across-the-blue/#videos)
and search for `KANE_customdimensions.showID = '` which will give you the show ID.

This ID can then be used on the funimation api (https://prod-api-funimationnow.dadcdigital.com/api/funimation/episodes/?limit=99999&title_id=567789)
replacing the ID after &title_id= with the one for that series.

The ID for each episode can be found under `"experience":` this is then passed onto the player URL

**Comment by uzZyOGNX** [comment]
Issue is still present in youtube-dl version 2020.06.16.1.

**Comment by LuSo58** [comment]
Also had this issue, resolved by getting a paid funimation plan. Perhaps something with the ads.

**Comment by en1gma713** [comment]
Issue still present in version 2021.04.26

**Comment by NSExceptional** [comment]
Still present in 2021.12.17
