### ISSUE TITLE
[vimeo] Can't download embedded video

### ISSUE THREAD

**Issue by Rudloff** [rg3/youtube-dl#14600]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.10.20*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.10.20**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://greenpeacefilmfestival.org/les-films/les-films-en-competition-2017/finance-et-economie/food-coop/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.10.20
[debug] Git HEAD: 0f37dc1
[debug] Python version 2.7.13 - Linux-4.9.0-4-amd64-x86_64-with-debian-9.2
[debug] exe versions: avconv 3.2.8-1, avprobe 3.2.8-1, ffmpeg 3.2.8-1, ffprobe 3.2.8-1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] food-coop: Requesting header
WARNING: Falling back on generic information extractor.
[generic] food-coop: Downloading webpage
[generic] food-coop: Extracting information
[download] Downloading playlist: Greenpeace Film Festival : votez pour votre film préféré
[generic] playlist Greenpeace Film Festival : votez pour votre film préféré: Collected 2 video ids (downloading 2 of them)
[download] Downloading video 1 of 2
ERROR: no suitable InfoExtractor for URL https://player.vimeo.com/video/'+video_type+'#__youtubedl_smuggle=%7B%22http_headers%22%3A+%7B%22Referer%22%3A+%22https%3A%2F%2Fgreenpeacefilmfestival.org%2Fles-films%2Fles-films-en-competition-2017%2Ffinance-et-economie%2Ffood-coop%2F%22%7D%7D
  File "vendor/rg3/youtube-dl/youtube_dl/__main__.py", line 19, in <module>
    youtube_dl.main()
  File "/home/pierre/www/alltube/vendor/rg3/youtube-dl/youtube_dl/__init__.py", line 465, in main
    _real_main(argv)
  File "/home/pierre/www/alltube/vendor/rg3/youtube-dl/youtube_dl/__init__.py", line 455, in _real_main
    retcode = ydl.download(all_urls)
  File "/home/pierre/www/alltube/vendor/rg3/youtube-dl/youtube_dl/YoutubeDL.py", line 1985, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/home/pierre/www/alltube/vendor/rg3/youtube-dl/youtube_dl/YoutubeDL.py", line 795, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/pierre/www/alltube/vendor/rg3/youtube-dl/youtube_dl/YoutubeDL.py", line 991, in process_ie_result
    extra_info=extra)
  File "/home/pierre/www/alltube/vendor/rg3/youtube-dl/youtube_dl/YoutubeDL.py", line 856, in process_ie_result
    extra_info=extra_info)
  File "/home/pierre/www/alltube/vendor/rg3/youtube-dl/youtube_dl/YoutubeDL.py", line 818, in extract_info
    self.report_error('no suitable InfoExtractor for URL %s' % url)
  File "/home/pierre/www/alltube/vendor/rg3/youtube-dl/youtube_dl/YoutubeDL.py", line 612, in report_error
    self.trouble(error_message, tb)
  File "/home/pierre/www/alltube/vendor/rg3/youtube-dl/youtube_dl/YoutubeDL.py", line 574, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())
```

And if I try the embed directly, I get this:
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://player.vimeo.com/video/225818903']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.10.20
[debug] Git HEAD: 0f37dc1
[debug] Python version 2.7.13 - Linux-4.9.0-4-amd64-x86_64-with-debian-9.2
[debug] exe versions: avconv 3.2.8-1, avprobe 3.2.8-1, ffmpeg 3.2.8-1, ffprobe 3.2.8-1, rtmpdump 2.4
[debug] Proxy map: {}
[vimeo] 225818903: Downloading webpage
ERROR: Cannot download embed-only video without embedding URL. Please call youtube-dl with the URL of the page that embeds this video.
Traceback (most recent call last):
  File "/home/pierre/www/alltube/vendor/rg3/youtube-dl/youtube_dl/extractor/vimeo.py", line 470, in _real_extract
    webpage, urlh = self._download_webpage_handle(request, video_id)
  File "/home/pierre/www/alltube/vendor/rg3/youtube-dl/youtube_dl/extractor/common.py", line 532, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "/home/pierre/www/alltube/vendor/rg3/youtube-dl/youtube_dl/extractor/common.py", line 512, in _request_webpage
    raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
ExtractorError: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/pierre/www/alltube/vendor/rg3/youtube-dl/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "/home/pierre/www/alltube/vendor/rg3/youtube-dl/youtube_dl/extractor/common.py", line 434, in extract
    ie_result = self._real_extract(url)
  File "/home/pierre/www/alltube/vendor/rg3/youtube-dl/youtube_dl/extractor/vimeo.py", line 484, in _real_extract
    expected=True)
ExtractorError: Cannot download embed-only video without embedding URL. Please call youtube-dl with the URL of the page that embeds this video.
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Embedded video: https://greenpeacefilmfestival.org/les-films/les-films-en-competition-2017/finance-et-economie/food-coop/

**Comment by Hrxn** [comment]
Try it with `--referer URL `

**Comment by Rudloff** [comment]
It does work when calling it with `https://player.vimeo.com/video/225818903 --referer https://greenpeacefilmfestival.org/les-films/les-films-en-competition-2017/finance-et-economie/food-coop/`, thanks!
