### ISSUE TITLE
[disneyabcpress] ERROR: Unsupported URL

### ISSUE THREAD

**Issue by RuneMagle** [rg3/youtube-dl#14611]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.10.20**
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
```
C:\Users\rumag\Desktop\youtube-dl>youtube-dl.exe -f best --all-subs http://www.disneyabcpress.com/disneychannel/shows/andi-mack/episodes/hey-who-wants-pizza/ -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'best', '--all-subs', 'http://www.disneyabcpress.com/disneychannel/shows/andi-mack/episodes/hey-who-wants-pizza/', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.10.20
[debug] Python version 3.4.4 - Windows-10-10.0.15063
[debug] exe versions: ffmpeg N-86911-gb664d1f, ffprobe N-86911-gb664d1f
[debug] Proxy map: {}
[generic] hey-who-wants-pizza: Requesting header
WARNING: Falling back on generic information extractor.
[generic] hey-who-wants-pizza: Downloading webpage
[generic] hey-who-wants-pizza: Extracting information
ERROR: Unsupported URL: http://www.disneyabcpress.com/disneychannel/shows/andi-mack/episodes/hey-who-wants-pizza/
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpvdixi2dy\build\youtube_dl\YoutubeDL.py", line 784, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpvdixi2dy\build\youtube_dl\extractor\common.py", line 434, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpvdixi2dy\build\youtube_dl\extractor\generic.py", line 3059, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.disneyabcpress.com/disneychannel/shows/andi-mack/episodes/hey-who-wants-pizza/
...
<end of log>
```

---
- Single video: http://www.disneyabcpress.com/disneychannel/shows/andi-mack/episodes/hey-who-wants-pizza/

### Description of your issue

There's two videos available on the site. It would be cool if you could add support for it.

**Comment by enigmaquip** [comment]
couldn't you use http://watchdisneychannel.go.com/andi-mack/video/vdka4131503/02/01-hey-who-wants-pizza which is supported by youtube-dl

**Comment by RuneMagle** [comment]
Yes. I only want the clips.
