### ISSUE TITLE
Unable to download http://www.mtvbase.com's music videos...

### ISSUE THREAD

**Issue by antdude** [rg3/youtube-dl#14632]
Example:

$ youtube-dl -v http://www.mtvbase.com/music/videos/obpo2i/Future-Love-Paradise
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://www.mtvbase.com/music/videos/obpo2i/Future-Love-Paradise']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.10.29
[debug] Python version 3.4.2 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.9
[debug] exe versions: ffmpeg 3.2.5-1, ffprobe 3.2.5-1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] Future-Love-Paradise: Requesting header
WARNING: Falling back on generic information extractor.
[generic] Future-Love-Paradise: Downloading webpage
[generic] Future-Love-Paradise: Extracting information
ERROR: Unsupported URL: http://www.mtvbase.com/music/videos/obpo2i/Future-Love-Paradise
Traceback (most recent call last):
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/common.py", line 434, in extract
    ie_result = self._real_extract(url)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3059, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.mtvbase.com/music/videos/obpo2i/Future-Love-Paradise

Thank you in advance. :)

**Comment by Hrxn** [comment]
Site is not supported (yet), apparently..
