### ISSUE TITLE
YT-DL dont downloading from new page of IPRIMA TV 

### ISSUE THREAD

**Issue by etit01** [rg3/youtube-dl#14654]
youtube-dl -u ******@seznam.cz --verbose -F http://play.iprima.cz/filmy/bitva-o-sevastopol
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-u', u'PRIVATE', u'--verbose', u'-F', u'http://play.iprima.cz/filmy/bitva-o-sevastopol']
Type account password and press [Return]: 
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.10.29
[debug] Python version 2.7.13 - Linux-4.9.0-4-amd64-x86_64-with-debian-9.2
[debug] exe versions: avconv 3.2.8-1, avprobe 3.2.8-1, ffmpeg 3.2.8-1, ffprobe 3.2.8-1
[debug] Proxy map: {}
[IPrima] bitva-o-sevastopol: Downloading webpage
[IPrima] p396592: Downloading player
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 434, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/iprima.py", line 93, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1072, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by jirih** [comment]
This url is not georestricted: http://prima.iprima.cz/vinari/hody

**Comment by helb** [comment]
@etit01 Could you please check if my fixes (#14974) in iprima extractor would help with your issue? The URL in your report returns 404 now and i don't have an account anyway. Thanks!

Contact me if you need any help with getting/running the patched youtube_dl.

**Comment by helb** [comment]
@etit01 Could you please check if my fixes (#14993) in iprima extractor would help with your issue? The URL in your report returns 404 now and i don't have an account anyway. Thanks!

Contact me if you need any help with getting/running the patched youtube_dl.

**Comment by kibeb** [comment]
@helb iPrima URL that requires -u is not working in youtube-dl version 2018.01.14. 
How can I check if your patches work? TIA.

**Comment by cotwitch** [comment]
If this issue still needs credentials (as labeled) u can use this:

`https://auth.iprima.cz/oauth2/login`
`brahma@mailmetrash.com`
`123456l`

Example url: `https://prima.iprima.cz/prostreno/libor-paulik`

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--username=PRIVATE', '--password=PRIVATE', '-vU', 'https://prima.iprima.cz/prostreno/libor-paulik']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.8 (CPython) - macOS-12.1-x86_64-i386-64bit
[debug] exe versions: ffmpeg 5.1.2, ffprobe 5.1.2, rtmpdump 2.4
[debug] Proxy map: {}
It looks like you installed youtube-dl with a package manager, pip, setup.py or a tarball. Please use that to update.
[IPrima] libor-paulik: Downloading webpage
ERROR: Unable to extract real id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/iprima.py", line 85, in _real_extract
    video_id = self._search_regex(
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract real id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
