### ISSUE TITLE
[gamespot] Add support for video embeds in article pages(was: RegexNotFoundError: Unable to extract data video)

### ISSUE THREAD

**Issue by Hrxn** [rg3/youtube-dl#14652]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.10.29**

- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

####  What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
GameSpot.com extraction broken, due to site change I assume.

Example URL:
`https://www.gamespot.com/articles/the-last-of-us-2-receives-new-ps4-trailer/1100-6454469/`

---

```
PS D:\> youtube-dl --verbose --ignore-config "https://www.gamespot.com/articles/the-last-of-us-2-receives-new-ps4-trailer/1100-6454469/"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--ignore-config', 'https://www.gamespot.com/articles/the-last-of-us-2-receives-new-ps4-trailer/1100-6454469/']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.10.29
[debug] Python version 3.4.4 - Windows-10-10.0.16299
[debug] exe versions: ffmpeg 3.4, ffprobe 3.4
[debug] Proxy map: {}
[GameSpot] 6454469: Downloading webpage
ERROR: Unable to extract data video; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\build\youtube_dl\YoutubeDL.py", line 784, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\build\youtube_dl\extractor\common.py", line 434, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\build\youtube_dl\extractor\gamespot.py", line 44, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\build\youtube_dl\extractor\common.py", line 797, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract data video; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

PS D:\>
```

**Comment by Hrxn** [comment]
#### Addendum

More luck with this URL
`https://www.gamespot.com/videos/the-last-of-us-part-ii-pgw-2017-trailer/2300-6441610/`

This is the _Share_ link from within the player controls.

__But:__
It's only 720p, and has some kind of advertising at the beginning, fuck yeah.

----
The _Embed_ link does not work:
```
PS E:\Test> youtube-dl --verbose --ignore-config "https://www.gamespot.com/videos/embed/6441610/"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--ignore-config', 'https://www.gamespot.com/videos/embed/6441610/']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.10.29
[debug] Python version 3.4.4 - Windows-10-10.0.16299
[debug] exe versions: ffmpeg 3.4, ffprobe 3.4
[debug] Proxy map: {}
[generic] 6441610: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 6441610: Downloading webpage
[generic] 6441610: Extracting information
ERROR: Unsupported URL: https://www.gamespot.com/videos/embed/6441610/
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\build\youtube_dl\YoutubeDL.py", line 784, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\build\youtube_dl\extractor\common.py", line 434, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\build\youtube_dl\extractor\generic.py", line 3059, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.gamespot.com/videos/embed/6441610/

PS E:\Test>
```

__But:__
The embed page has a 1080p version, apparently..

```PowerShell
PS E:\Test>
>> curl.exe -s "https://www.gamespot.com/videos/embed/6441610/" |
>> pup -p "div.js-video-player-new.av-video-player.av-desktop-player.av-video-on-demand.is-vid-noseek.is-vid-show-controls.is-vid-uvpjs-player attr{data-video}" |
>> jq '.videoStreams .adaptive_hd'
>>
"https://gamespot-vh.akamaihd.net/i/d5/2017/10/30/Trailer_LastofUs_PGW_20171030_,4000,.mp4.csmil/master.m3u8"
PS E:\Test>
```

**Comment by Hrxn** [comment]
@remitamine I think this issue has been mentioned on the Changelog/Relnotes, so what's the status on this? Still fixes in the pipeline?

**Comment by remitamine** [comment]
```
python __main__.py https://www.gamespot.com/videos/embed/6441610/
[GameSpot] 6441610: Downloading webpage
[GameSpot] 6441610: Downloading m3u8 information
[GameSpot] 6441610: Downloading m3u8 information
[GameSpot] 6441610: Checking http-2000 video format URL
[GameSpot] 6441610: Checking http-4400 video format URL
[GameSpot] 6441610: Checking http-3000 video format URL
[GameSpot] 6441610: Checking http-1200 video format URL
[GameSpot] 6441610: Checking http-764 video format URL
[GameSpot] 6441610: Checking http-512 video format URL
[GameSpot] 6441610: Checking http-264 video format URL
[download] Destination: The Last Of Us Part II - PGW 2017 Trailer-gs-2300-6441610.mp4
[download] 100% of 172.31MiB in 06:14
```
video and embed pages support has been fixed, video embeds in articles pages are not supported yet, it's easy to add support for them but i'm not working on it for now,

**Comment by Hrxn** [comment]
Isn't that the video with additional ~ 15s advertising at the beginning?

**Comment by remitamine** [comment]
no, i just watched the downloaded video and it doesn't contain any ads, you can try yourself with version 2017.11.06 it contain the fix for video pages.

**Comment by Hrxn** [comment]
Call of Duty: WWII ad at the beginning 😄

**Comment by remitamine** [comment]
```
python __main__.py -F https://www.gamespot.com/videos/the-last-of-us-part-ii-pgw-2017-trailer/2300-6441610/
[GameSpot] 6441610: Downloading webpage
[GameSpot] 6441610: Downloading m3u8 information
[GameSpot] 6441610: Downloading m3u8 information
[GameSpot] 6441610: Checking http-2000 video format URL
[GameSpot] 6441610: Checking http-4400 video format URL
[GameSpot] 6441610: Checking http-3000 video format URL
[GameSpot] 6441610: Checking http-1200 video format URL
[GameSpot] 6441610: Checking http-764 video format URL
[GameSpot] 6441610: Checking http-512 video format URL
[GameSpot] 6441610: Checking http-264 video format URL
[info] Available formats for gs-2300-6441610:
format code  extension  resolution note
hls-264      mp4        256x144     264k , avc1.42001e, mp4a.40.5
http-264     mp4        256x144     264k , avc1.42001e, mp4a.40.5
hls-512      mp4        384x216     512k , avc1.42001e, mp4a.40.5
http-512     mp4        384x216     512k , avc1.42001e, mp4a.40.5
hls-764      mp4        480x270     764k , avc1.42001e, mp4a.40.2
http-764     mp4        480x270     764k , avc1.42001e, mp4a.40.2
hls-778      mp4        640x360     778k 
hls-1055     mp4        640x360    1055k 
hls-1200     mp4        640x360    1200k , avc1.42001f, mp4a.40.2
http-1200    mp4        640x360    1200k , avc1.42001f, mp4a.40.2
hls-1796     mp4        960x540    1796k 
hls-2000     mp4        960x540    2000k , avc1.4d001f, mp4a.40.2
http-2000    mp4        960x540    2000k , avc1.4d001f, mp4a.40.2
hls-2444     mp4        1280x720   2444k 
hls-3000     mp4        1280x720   3000k , avc1.4d001f, mp4a.40.2
http-3000    mp4        1280x720   3000k , avc1.4d001f, mp4a.40.2
hls-3097     mp4        1280x720   3097k 
hls-3839     mp4        1920x1080  3839k 
hls-4400     mp4        1280x720   4400k , avc1.640028, mp4a.40.2
http-4400    mp4        1280x720   4400k , avc1.640028, mp4a.40.2 (best)
```
the 1080p is not selected because the 720p has higher bitrate, the ads are only included in the `http` formats.

**Comment by remitamine** [comment]
in the next release, article pages will be supported and formats that has ads will be skipped.

**Comment by 07416** [comment]
Were reviews ever supported?

`youtube-dl https://www.gamespot.com/reviews/gears-of-war-review/1900-6161188/`

```
[generic] 1900-6161188: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 1900-6161188: Downloading webpage
[generic] 1900-6161188: Extracting information
ERROR: Unsupported URL: https://www.gamespot.com/reviews/gears-of-war-review/1900-6161188/
```

**Comment by Hrxn** [comment]
Nope, looks like that URL format is not supported..

Can you access the same vid with another URL? Like, something along the lines of `https://www.gamespot.com/videos/...........`?

**Comment by remitamine** [comment]
you can download this video using share URL(https://www.gamespot.com/videos/gears-of-war-video-review/2300-6161200/ or https://www.gamespot.com/videos/embed/6161200/), downloading from review URLs will be supported in the next version.

**Comment by 07416** [comment]
> Can you access the same vid with another URL? Like, something along the lines of `https://www.gamespot.com/videos/...........`?

Yes, I found the URL eventually via the share menu.
`https://www.gamespot.com/videos/gears-of-war-video-review/2300-6182341/`

 Initially I used Google to search under `https://www.gamespot.com/gears-of-war/videos/`, found the URL `https://www.gamespot.com/videos/gears-of-war-video-review/2300-6182341/` which fails and redirects to [the PC review](https://www.gamespot.com/reviews/gears-of-war-review/1900-6182319/).

**Comment by 07416** [comment]
@remitamine Yes, I successfully downloaded the video.

`youtube-dl https://www.gamespot.com/videos/gears-of-war-video-review/2300-6161200/`

**Comment by remitamine** [comment]
> Perhaps the age-gated videos aren't supported?

no, it's not it just requires more changes to the extractor, you can download the video using https://gamespot-pdl.akamaized.net/d3/gsc/2007/11/169_gearsofwar_vr_01_pc_110507_hr.mp4.
