### ISSUE TITLE
Livestream.com giving back 404 error

### ISSUE THREAD

**Issue by itsnotmyfault1** [rg3/youtube-dl#14660]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.10.29*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.10.29**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
```
C:\Users\winbox\Documents\Feminism\YouTube>youtube-dl -v https://livestream.com/accounts/13547932/events/7865962/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://livestream.com/accounts/13547932/events/7865962/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.10.29
[debug] Python version 3.4.4 - Windows-10-10.0.15063
[debug] exe versions: ffmpeg N-50911-g9efcfbe
[debug] Proxy map: {}
[livestream] Downloading JSON metadata
[livestream] 7865962: Downloading page 1
[livestream] 7865962: Downloading page 2
[download] Downloading playlist: The First Amendment on Campus Symposium
[livestream] playlist The First Amendment on Campus Symposium: Collected 2 video ids (downloading 2 of them)
[download] Downloading video 1 of 2
[livestream] 165037191: Downloading JSON metadata
[livestream] 165037191: Downloading SMIL file
[livestream] 165037191: Downloading m3u8 information
[livestream] 165037191: Downloading f4m manifest
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://api.new.livestream.com/accounts/13547932/events/7865962/videos/165037191.f4m'
[f4m] Downloading f4m manifest
[f4m] Total fragments: 2171
[download] Destination: Pt 2 -  The First Amendment on Campus - Identifying Principles for Best Practices for Managing and Resolving Disputes-165037191.flv
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\build\youtube_dl\YoutubeDL.py", line 1892, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\build\youtube_dl\YoutubeDL.py", line 1831, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\build\youtube_dl\downloader\common.py", line 361, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\build\youtube_dl\downloader\f4m.py", line 391, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\build\youtube_dl\downloader\fragment.py", line 97, in _download_fragment
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\build\youtube_dl\downloader\common.py", line 361, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\build\youtube_dl\downloader\http.py", line 286, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\build\youtube_dl\downloader\http.py", line 74, in establish_connection
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\build\youtube_dl\YoutubeDL.py", line 2195, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

```
---

I have no idea what I'm doing, but I took a look at http://api.new.livestream.com/accounts/13547932/events/7865962/videos/165037191.f4m

which provided a manifest.f4m that included the following

```
<?xml version="1.0" encoding="UTF-8"?>
<manifest xmlns="http://ns.adobe.com/f4m/1.0">
    <streamType>recorded</streamType>
    <baseURL>http://vod.livestream.com/events/000000000078066a/</baseURL>
    <duration>12220.922</duration>
    <bootstrapInfo profile="named" id="bootstrap_1">AAAAq2Fic3QAAAAAAAAAAQAAAAPoAAAAAADNo1YAAAAAAAAAAAAAAAAAAQAAABlhc3J0AAAAAAAAAAABAAAAAQAACYoBAAAAZmFmcnQAAAAAAAAD6AAAAAAFAAAA/AAAAAAAEys/AAATjQAACXAAAAAAALhvIwAAE78AAAlxAAAAAAC4guIAABONAAAKhQAAAAAAzZbmAAAMcAAAAAAAAAAAAAAAAAAAAAAA</bootstrapInfo>
    <bootstrapInfo profile="named" id="bootstrap_2">AAAAq2Fic3QAAAAAAAAAAQAAAAPoAAAAAADNpHMAAAAAAAAAAAAAAAAAAQAAABlhc3J0AAAAAAAAAAABAAAAAQAACYoBAAAAZmFmcnQAAAAAAAAD6AAAAAAFAAAA/AAAAAAAEys/AAATjQAACXAAAAAAALhvIwAAE78AAAlxAAAAAAC4guIAABONAAAKhQAAAAAAzZbmAAANjQAAAAAAAAAAAAAAAAAAAAAA</bootstrapInfo>
    <bootstrapInfo profile="named" id="bootstrap_3">AAAA62Fic3QAAAAAAAAAAQAAAAPoAAAAAADNp28AAAAAAAAAAAAAAAAAAQAAABlhc3J0AAAAAAAAAAABAAAAAQAACYoBAAAApmFmcnQAAAAAAAAD6AAAAAAJAAAA/AAAAAAAEy11AAATjQAABBIAAAAAAE+CkwAAFYAAAAQTAAAAAABPmBMAABONAAAHzAAAAAAAmF/4AAAWSQAAB80AAAAAAJh2QQAAE40AAAlwAAAAAAC4dggAABO/AAAJcQAAAAAAuInHAAATjQAACoUAAAAAAM2dywAACaQAAAAAAAAAAAAAAAAAAAAAAA==</bootstrapInfo>
    <media url="faf62b01-ccec-467a-92ff-02b0301f557f_198" bootstrapInfoId="bootstrap_1" bitrate="329" width="480" height="270" videoCodec="avc1.42e020" audioCodec="mp4a.40.2">
        <metadata>AgAKb25NZXRhRGF0YQgAAAAIAAhkdXJhdGlvbgBAylJY1P3ztgAFd2lkdGgAQH4AAAAAAAAABmhlaWdodABAcOAAAAAAAAAJZnJhbWVyYXRlAEBN+EqISKnGAA12aWRlb2RhdGFyYXRlAEBw6iuUpHwMAAx2aWRlb2NvZGVjaWQAQBwAAAAAAAAADWF1ZGlvZGF0YXJhdGUAQEdv/e3xQYEADGF1ZGlvY29kZWNpZABAJAAAAAAAAAAACQ==</metadata>
    </media>
    <media url="faf62b01-ccec-467a-92ff-02b0301f557f_678" bootstrapInfoId="bootstrap_2" bitrate="1050" width="768" height="432" videoCodec="avc1.4d0029" audioCodec="mp4a.40.2">
        <metadata>AgAKb25NZXRhRGF0YQgAAAAIAAhkdXJhdGlvbgBAylJ9T987ZAAFd2lkdGgAQIgAAAAAAAAABmhlaWdodABAewAAAAAAAAAJZnJhbWVyYXRlAEBN+EpUuTxJAA12aWRlb2RhdGFyYXRlAECMclzS9jPWAAx2aWRlb2NvZGVjaWQAQBwAAAAAAAAADWF1ZGlvZGF0YXJhdGUAQF8//ElSCp8ADGF1ZGlvY29kZWNpZABAJAAAAAAAAAAACQ==</metadata>
    </media>
    <media url="faf62b01-ccec-467a-92ff-02b0301f557f_2320" bootstrapInfoId="bootstrap_3" bitrate="3562" width="1280" height="720" videoCodec="avc1.4d0029" audioCodec="mp4a.40.2">
        <metadata>AgAKb25NZXRhRGF0YQgAAAAIAAhkdXJhdGlvbgBAylLfGp++dwAFd2lkdGgAQJQAAAAAAAAABmhlaWdodABAhoAAAAAAAAAJZnJhbWVyYXRlAEBN+ErU8w8fAA12aWRlb2RhdGFyYXRlAECpRW0fgFM0AAx2aWRlb2NvZGVjaWQAQBwAAAAAAAAADWF1ZGlvZGF0YXJhdGUAQHOH+7R1j7AADGF1ZGlvY29kZWNpZABAJAAAAAAAAAAACQ==</metadata>
    </media>
</manifest>
```
I took an educated guess and went to links indicated the one with the highest resolution/bitrate. Probably not doing this correctly, but I was wondering if there's something there that I could just manually download via my browser. I went to 

http://vod.livestream.com/events/000000000078066a/
http://vod.livestream.com/events/000000000078066a/faf62b01-ccec-467a-92ff-02b0301f557f_2320
http://vod.livestream.com/events/000000000078066a/faf62b01-ccec-467a-92ff-02b0301f557f_2320.mp4 (this one looks slightly different)
http://vod.livestream.com/events/000000000078066a/faf62b01-ccec-467a-92ff-02b0301f557f_2320.mp4a
http://vod.livestream.com/events/000000000078066a/faf62b01-ccec-467a-92ff-02b0301f557f_2320.mp4a.420.2
http://vod.livestream.com/events/000000000078066a/faf62b01-ccec-467a-92ff-02b0301f557f_2320.avcl.4d0029

All of these give me "Not Found", so I guess youtube-dl is not just lying to me.

I'm not sure why it can find that there are videos, provide details on the number of videos, their names, and even the total fragments and runtime in the manifest, but the videos are missing.

I've also tried using the individual URLs instead of the playlist. Provides the same result.

**Comment by itsnotmyfault1** [comment]
Tried to download some other random video 

```


C:\Users\winbox\Documents\Feminism\YouTube>youtube-dl -v https://livestream.com/accounts/6115179/events/6764928/videos/144884262
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://livestream.com/accounts/6115179/events/6764928/videos/144884262']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.10.29
[debug] Python version 3.4.4 - Windows-10-10.0.15063
[debug] exe versions: ffmpeg N-50911-g9efcfbe
[debug] Proxy map: {}
[livestream] 144884262: Downloading JSON metadata
[livestream] 144884262: Downloading SMIL file
[livestream] 144884262: Downloading m3u8 information
[livestream] 144884262: Downloading f4m manifest
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://vod.livestream.com/events/0000000000673980/b90f532f-b0f6-4f4e-8289-706d490b2fd8_2292.m3u8?token=0_5a00a896_9e8437fbb1fe79adfc19c4ef4faa1af898c90d28&start=0&end=282'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 46
[download] Destination: Ganguly - Gut feeling is that match will end in a draw-144884262.mp4
[download] 100% of 72.90MiB in 00:14
ERROR: ffprobe or avprobe not found. Please install one.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\build\youtube_dl\YoutubeDL.py", line 2031, in post_process
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\build\youtube_dl\postprocessor\ffmpeg.py", line 541, in run
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\build\youtube_dl\postprocessor\ffmpeg.py", line 156, in get_audio_codec
youtube_dl.utils.PostProcessingError: ffprobe or avprobe not found. Please install one.
```
So that worked... Not sure why the other ones won't work still.
