### ISSUE TITLE
Hotstar.com giving HTTP Error 403 : Forbidden error

### ISSUE THREAD

**Issue by droidnafiz** [rg3/youtube-dl#14672]
- [ yes] I've **verified** and **I assure** that I'm running youtube-dl **2017.10.29**
- [yes ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ yes] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [this ] Bug report (encountered problems with youtube-dl)

---

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://www.hotstar.com/tv/ishqbaaaz/9567/gauri-to-marry-ajay/1000193218']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.10.29
[debug] Python version 3.4.4 - Windows-10-10.0.15063
[debug] exe versions: ffmpeg N-86265-gb946bd8, ffprobe N-86265-gb946bd8
[debug] Proxy map: {}
[HotStar] 1000193218: Downloading JSON metadata
[HotStar] 1000193218: Downloading JIO JSON metadata
[HotStar] 1000193218: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\build\youtube_dl\YoutubeDL.py", line 784, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\build\youtube_dl\extractor\common.py", line 434, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\build\youtube_dl\extractor\hotstar.py", line 89, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\build\youtube_dl\extractor\common.py", line 1072, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
...
<end of log>
```

---

previously this site was working very fine. now when downloading it shows 403 forbidden error. please have a look into it

**Comment by dstftw** [comment]
This video is geo restricted.
