### ISSUE TITLE
daisuki support broken

### ISSUE THREAD

**Issue by SonGokuSSJ** [rg3/youtube-dl#14681]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.10.29*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ X] I've **verified** and **I assure** that I'm running youtube-dl **2017.10.29**

### Before submitting an *issue* make sure you have:
- [X ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://motto.daisuki.net/framewatch/embed/embedDRAGONBALLSUPERUniverseSurvivalsaga/P2e/760/428']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.10.29
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 3.3.3, ffprobe 3.3.3
[debug] Proxy map: {}
[generic] 428: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 428: Downloading webpage
[generic] 428: Extracting information
ERROR: Unsupported URL: http://motto.daisuki.net/framewatch/embed/embedDRAGONBAL
LSUPERUniverseSurvivalsaga/P2e/760/428
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\build\youtube_dl\YoutubeDL.py", line 784, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\build\youtube_dl\extractor\common.py", line 434, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpk63cqkyt\build\youtube_dl\extractor\generic.py", line 3059, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: http://motto.daisuki.net/framewatch/embed/embedDRAGONBALLSUPERUniverseSurvivalsaga/P2e/760/428
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://motto.daisuki.net/framewatch/embed/embedDRAGONBALLSUPERUniverseSurvivalsaga/P2e/760/428

---

### Description of your *issue*, suggested solution and other information

When I try to download the latest DBS episode from daisuki I get "ERROR: Unsupported URL: http://motto.daisuki.net/framewatch/embed/embedDRAGONBALLSUPERUniverseSurvivalsaga/P2e/760/428 "

I guess it has something to do that daisuki changed it service to Dragon Ball Super only.

**Comment by SonGokuSSJ** [comment]
For me (I am in Germany) it is not geo-restricted. Atleast I think so because I can watch it with their own Flash Player. Only download with youtube-dl does not work.

**Comment by SonGokuSSJ** [comment]
Changing the daisuki player to the flow player reveals another url. Hope this url helps:

<param name="flashvars" value="hostname=motto.daisuki.net&amp;url=https://bngn-vh.akamaihd.net/i/43383936/35470338/smil/DE/00050/413880037823066.smil/master.m3u8?hdnea%3Dst%3D1511043160~exp%3D1511043460~acl%3D/*~hmac%3D84ff99feffac9b400f120b27eab3c0d15cc14b375b7467cd316c56b208536b33&amp;callback=fpCallback996391865347&amp;proxy=best&amp;live=false&amp;debug=false&amp;splash=false&amp;hlsQualities=true&amp;initialVolume=1&amp;">

It is from episode 115. That url would be http://motto.daisuki.net/framewatch/embed/embedDRAGONBALLSUPERUniverseSurvivalsaga/R2e/760/428

**Comment by SonGokuSSJ** [comment]
Thank you very much. It is working fine (tested on 2 computers in 2 locations).
