### ISSUE TITLE
ERROR: bbc returned error: selectionunavailable

### ISSUE THREAD

**Issue by RingoTheDog** [rg3/youtube-dl#14697]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.11.06*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.11.06**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
>youtube-dl.py -v "http://www.bbc.co.uk/news/world-middle-east-35917663"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://www.bbc.co.uk/news/world-middle-east-35917663']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.11.06
[debug] Python version 3.5.1 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-71727-g46778ab, ffprobe 3.2, rtmpdump 2.4
[debug] Proxy map: {}
[bbc] world-middle-east-35917663: Downloading webpage
[bbc] p03pd4fv: Downloading media selection XML
[bbc] p03pd4fv: Downloading media selection XML
[bbc] p03pd4fv: Downloading media selection XML
ERROR: bbc returned error: selectionunavailable
Traceback (most recent call last):
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\common.py", line 437, in extract
    ie_result = self._real_extract(url)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\bbc.py", line 881, in _real_extract
    formats, subtitles = self._download_media_selector(programme_id)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\bbc.py", line 333, in _download_media_selector
    self._raise_extractor_error(last_exception)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\bbc.py", line 320, in _raise_extractor_error
    expected=True)
youtube_dl.utils.ExtractorError: bbc returned error: selectionunavailable
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://www.bbc.co.uk/news/world-middle-east-35917663
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Seems to work correctly with all the other BBC RSS links..just fails on this one...might be a BBC issue?

**Comment by al1fr** [comment]
That's use rtmp protocol.
To download with rtmpdump.exe and this very complexe command:

'rtmpdump -r "rtmp://cp44293.edgefcs.net:1935/ondemand" ^
-a "ondemand?auth=daEbubYcfc5cwaMcDdpdFawblcaclbqdjcy-bAceMG-bWG-BolFFpDpHBvGwzH&aifp=v001&slist=public/secure_auth/480kbps/galileo/p03pcx5j.e048d3b2-5124-4643-bdb8-f3ba052208d1_flv_avc1_low.mp4;public/secure_auth/800kbps/galileo/p03pcx5j.e048d3b2-5124-4643-bdb8-f3ba052208d1_flv_avc1_med.mp4;public/secure_auth/1500kbps/galileo/p03pcx5j.e048d3b2-5124-4643-bdb8-f3ba052208d1_flv_avc1_high.mp4" ^
-f "WIN 27,0,0,183" ^
-W "http://emp.bbci.co.uk/emp/SMPf/1.20.0/StandardMediaPlayerChromelessFlash.swf" ^
-p "http://www.bbc.com/news/av/world-middle-east-35914926/egyptair-hijack-seven-people-still-on-plane-aviation-minister" ^
-C O:1 ^
-C O:0 ^
-y "mp4:public/secure_auth/1500kbps/galileo/p03pcx5j.e048d3b2-5124-4643-bdb8-f3ba052208d1_flv_avc1_high.mp4?auth=daEbubYcfc5cwaMcDdpdFawblcaclbqdjcy-bAceMG-bWG-BolFFpDpHBvGwzH&aifp=v001&slist=public/secure_auth/480kbps/galileo/p03pcx5j.e048d3b2-5124-4643-bdb8-f3ba052208d1_flv_avc1_low.mp4;public/secure_auth/800kbps/galileo/p03pcx5j.e048d3b2-5124-4643-bdb8-f3ba052208d1_flv_avc1_med.mp4;public/secure_auth/1500kbps/galileo/p03pcx5j.e048d3b2-5124-4643-bdb8-f3ba052208d1_flv_avc1_high.mp4" ^
-o "2017-11-12_02-18-36_p03pcx5j.e048d3b2-5124-4643-bdb8-f3ba052208d1_flv_avc1_high.flv"'

**Comment by danepedersen** [comment]
I'm having the same problem, although it appears that iplayer has switched from XML to JSON for its metadata:

> Beginning download, this box will output progress
> Using yt-dlp as the download provider.
> yt-dlp has been found and set
> Generating output directory structure
> The output was generated and will be used
> Custom was requested, skipping quality + format
> The quality and format has been set
> Arguments have been generated
> Arguments have been generated and are readonly in the textbox
> Creating download thread
> Created download thread, starting...
> Error: [debug] Command-line config: ['https://www.bbc.co.uk/iplayer/episode/p0bjkjlr/the-fast-and-the-farmerish-series-1-4-scotland-heat', '-o', 'D:\\Downloaded Audio-Video Tracks\\ViaYouTubeDL\\co.uk\\Custom\\%(title)s-%(id)s.%(ext)s', '-o', 'D:/Downloaded Audio-Video Tracks/BBC/ScotlandHeat.mp4', '--cookies', 'D:/www.bbc.co.uk_cookies.txt', '--verbose']
> Error: [debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out cp1252 (No VT), error cp1252 (No VT), screen cp1252 (No VT)
> Error: [debug] yt-dlp version stable@2023.07.06 [b532a3481] (win_exe)
> Error: [debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
> Error: [debug] exe versions: ffmpeg 5.1.2-essentials_build-www.gyan.dev (setts), ffprobe 5.1.2-essentials_build-www.gyan.dev
> Error: [debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
> Error: [debug] Proxy map: {}
> Error: [debug] Loaded 1855 extractors
> [bbc.co.uk] Extracting URL: https://www.bbc.co.uk/iplayer/episode/p0bjkjlr/the-fast-and-the-farmerish-series-1-4-scotland-heat
> [bbc.co.uk] p0bjkjlr: Downloading video page
> [bbc.co.uk] p0bjkjlr: Downloading playlist JSON
> [bbc.co.uk] m001jw0n: Downloading media selection JSON
> [bbc.co.uk] m001jw0n: Downloading media selection JSON
> Error: ERROR: [bbc.co.uk] p0bjkjlr: bbc.co.uk returned error: selectionunavailable
> Error:   File "yt_dlp\extractor\common.py", line 710, in extract
> Error:   File "yt_dlp\extractor\bbc.py", line 576, in _real_extract
> Error:   File "yt_dlp\extractor\bbc.py", line 463, in _download_playlist
> Error:   File "yt_dlp\extractor\bbc.py", line 342, in _download_media_selector
> Error:   File "yt_dlp\extractor\bbc.py", line 327, in _raise_extractor_error
> An error occured
> THIS IS A YOUTUBE-DL ERROR, NOT A ERROR WITH THIS PROGRAM!

As with RingoTheDog, the problem only affects certain episodes.  I was able to download five out of seven episodes successfully.

**Comment by dirkf** [comment]
#30839: "if you were actually running yt-dlp ..."
