### ISSUE TITLE
ESPN broken

### ISSUE THREAD

**Issue by dwaderich** [rg3/youtube-dl#14715]
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'ULNK-3573', 'http://www.espn.com/watch/player?id=3211683', '--ap-mso', 'DTV', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '--hls-prefer-native', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.11.06
[debug] Python version 3.4.4 - Windows-2012ServerR2-6.3.9600
[debug] exe versions: ffmpeg N-71320-gc4b2017, ffprobe N-80912-gce466d0
[debug] Proxy map: {}
[ESPN] 3211683: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp1ogvhjus\build\youtube_dl\extractor\common.py", line 506, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp1ogvhjus\build\youtube_dl\YoutubeDL.py", line 2195, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default

**Comment by goggle** [comment]
Opening http://www.espn.com/watch/player?id=3211683 in Browser gives my "Page Error". It seems as though there is no video.

**Comment by haggis42** [comment]
Having the exact same problem with the exact same ESPN Video too - same error. I've tried DTV as the provider and also ATTOTT but no luck.

Ran from the latest tarball

The page opens fine in any browser for me though, no page error here.

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'http://www.espn.com/watch/player?id=3211683', u'--ap-mso', u'ATTOTT', u'--ap-username', u'PRIVATE', u'--ap-password', u'PRIVATE', u'--hls-prefer-native', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.11.06
[debug] Python version 2.7.10 - Darwin-17.3.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.3.4-tessus
[debug] Proxy map: {}
[ESPN] 3211683: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dwaderich** [comment]
what can i do to help without providing the account user/pass?

**Comment by hpr** [comment]
Here's another example of an espn video archive that gives me a HTTP 400 error with youtube_dl @goggle, if the first link didn't work: http://www.espn.com/watch/player?id=3273802

**Comment by oxguy3** [comment]
Having this issue as well with this video, using DTV as my MSO identifier (or with no MSO specified): [Akron vs. Western Michigan (First Round, Game 4) (MAC Men's Basketball Tournament)](http://www.espn.com/watch/player?id=3321968)

**Comment by sjeble** [comment]
Also having trouble w/ESPN

**Comment by sjeble** [comment]
My ESPN issue these days — "Unable to extract video id":
`youtube-dl https://www.espn.com/watch/player?id=c0463886-bd83-4aff-a042-6ce06a8ba2b6 --ap-mso ATT --ap-username PRIVATE --ap-password PRIVATE --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.espn.com/watch/player?id=c0463886-bd83-4aff-a042-6ce06a8ba2b6', u'--ap-mso', u'ATT', u'--ap-username', u'PRIVATE', u'--ap-password', u'PRIVATE', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.09.28
[debug] Python version 2.7.10 (CPython) - Darwin-18.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1, rtmpdump 2.4
[debug] Proxy map: {}
[ESPNArticle] player?id=c0463886-bd83-4aff-a042-6ce06a8ba2b6: Downloading webpage
ERROR: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/espn.py", line 208, in _real_extract
    webpage, 'video id', group='id')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.`

**Comment by Qiangong2** [comment]
Still can't download ESPN videos due to it needing a TV Provider
