### ISSUE TITLE
6play : ffmpeg spams output and exits with error

### ISSUE THREAD

**Issue by cafehaine** [rg3/youtube-dl#14719]
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.11.06**
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Bug report (encountered problems with youtube-dl)

The log : (too long to post here, ffmpeg spams the output)
[https://gist.github.com/cafehaine/b973d481be22636b532430bbc9859fd7](https://gist.github.com/cafehaine/b973d481be22636b532430bbc9859fd7)

Self explanatory, something changed on their side and now it is broken on our side.
the video tested was at this url : https://www.6play.fr/cauchemar-en-cuisine-avec-philippe-etchebest-p_841/arcais-c_11610886

**Comment by cafehaine** [comment]
An account I just created for the site :
login : cafehaine at gmail.com
password : demoaccount

**Comment by yan12125** [comment]
This video insists that I don't have a Flash Player even if I have passed the Adobe Flash test
```
You have version 27,0,0,183 installed
```

**Comment by cafehaine** [comment]
Honestly I'm using youtube-dl since I cannot use the website since I'm running firefox 57 (no longer compatible with flash), so.. yeah.
Their ads are running with HTML5, so maybe they are transitioning to html5, I don't really know what they are doing.

**Comment by yan12125** [comment]
I guess their website is just broken. Feel free to leave comments if those videos are working again.

**Comment by cafehaine** [comment]
Update : Website seems to be fixed, no longer needs flash, however youtube-dl now gets a 403 error code from the server :
```
$[ 2 ] 10:17   Videos    > youtube-dl -v -u cafehaine@gmail.com -p demoaccount https://www.6play.fr/norbert-commis-d-office-p_4668/Jade-contrefacon-de-lasagnes-au-chocolat-Jean-Baptiste-trahison-de-tapas-c_11828928
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-u', 'PRIVATE', '-p', 'PRIVATE', 'https://www.6play.fr/norbert-commis-d-office-p_4668/Jade-contrefacon-de-lasagnes-au-chocolat-Jean-Baptiste-trahison-de-tapas-c_11828928']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.01.14
[debug] Python version 3.6.4 (CPython) - Linux-4.14.13-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 3.4.1, ffprobe 3.4.1, rtmpdump 2.4
[debug] Proxy map: {}
[6play] 11828928: Downloading JSON metadata
[6play] 11828928: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[6play] 11828928: Downloading f4m manifest
WARNING: Unable to download f4m manifest: HTTP Error 403: Forbidden
[6play] 11828928: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 403: Forbidden
[6play] 11828928: Downloading ISM manifest
WARNING: Failed to download ISM manifest: HTTP Error 403: Forbidden
[6play] 11828928: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[6play] 11828928: Downloading f4m manifest
WARNING: Unable to download f4m manifest: HTTP Error 403: Forbidden
[6play] 11828928: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 403: Forbidden
[6play] 11828928: Downloading ISM manifest
WARNING: Failed to download ISM manifest: HTTP Error 403: Forbidden
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 438, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/sixplay.py", line 86, in _real_extract
    self._sort_formats(formats)
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 1069, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by campones** [comment]
issue is still on going
