### ISSUE TITLE
Error - "utf-8' codec can't decode byte 0xfc in position 38: invalid start byte"

### ISSUE THREAD

**Issue by Hansota** [rg3/youtube-dl#14747]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.11.06**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'youtube-dl', 'https://www.youtube.com/playlist?list=PLf94FoubBX-MhS9CTnDp-XkCWyFuYdJTV', '--download-archive', 'archive.txt', '--ignore-errors', '-x', '--audio-format', 'mp3', '--audio-quality', '0']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.11.06
[debug] Python version 3.4.4 - Windows-10-10.0.17025
[debug] exe versions: ffmpeg N-87353-g183fd30, ffprobe N-87353-g183fd30
[debug] Proxy map: {}
ERROR: 'youtube-dl' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:youtube-dl" ) to search YouTube
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp1ogvhjus\build\youtube_dl\YoutubeDL.py", line 784, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp1ogvhjus\build\youtube_dl\extractor\common.py", line 437, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp1ogvhjus\build\youtube_dl\extractor\generic.py", line 2049, in _real_extract
youtube_dl.utils.ExtractorError: 'youtube-dl' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:youtube-dl" ) to search YouTube

[youtube:playlist] PLf94FoubBX-MhS9CTnDp-XkCWyFuYdJTV: Downloading webpage
[download] Downloading playlist: Musik aller Art
[youtube:playlist] PLf94FoubBX-MhS9CTnDp-XkCWyFuYdJTV: Downloading page #1
[youtube:playlist] PLf94FoubBX-MhS9CTnDp-XkCWyFuYdJTV: Downloading page #2
[youtube:playlist] PLf94FoubBX-MhS9CTnDp-XkCWyFuYdJTV: Downloading page #3
[youtube:playlist] PLf94FoubBX-MhS9CTnDp-XkCWyFuYdJTV: Downloading page #4
[youtube:playlist] PLf94FoubBX-MhS9CTnDp-XkCWyFuYdJTV: Downloading page #5
[youtube:playlist] PLf94FoubBX-MhS9CTnDp-XkCWyFuYdJTV: Downloading page #6
[youtube:playlist] PLf94FoubBX-MhS9CTnDp-XkCWyFuYdJTV: Downloading page #7
[youtube:playlist] PLf94FoubBX-MhS9CTnDp-XkCWyFuYdJTV: Downloading page #8
[youtube:playlist] PLf94FoubBX-MhS9CTnDp-XkCWyFuYdJTV: Downloading page #9
[youtube:playlist] PLf94FoubBX-MhS9CTnDp-XkCWyFuYdJTV: Downloading page #10
[youtube:playlist] PLf94FoubBX-MhS9CTnDp-XkCWyFuYdJTV: Downloading page #11
[youtube:playlist] PLf94FoubBX-MhS9CTnDp-XkCWyFuYdJTV: Downloading page #12
[youtube:playlist] playlist Musik aller Art: Downloading 1249 videos
[download] Downloading video 1 of 1249
ERROR: 'utf-8' codec can't decode byte 0xfc in position 38: invalid start byte
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp1ogvhjus\build\youtube_dl\YoutubeDL.py", line 795, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp1ogvhjus\build\youtube_dl\YoutubeDL.py", line 984, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp1ogvhjus\build\youtube_dl\YoutubeDL.py", line 740, in _match_entry
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp1ogvhjus\build\youtube_dl\YoutubeDL.py", line 2064, in in_download_archive
  File "C:\Python\Python34\lib\codecs.py", line 319, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfc in position 38: invalid start byte
```

---

### Description of your *issue*, suggested solution and other information

when I try to download my youtube playlist the downlaod will start as usal. After the whole "Downloading page #xx" is done the download will interrupt and it gives me this error code: 
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfc in position 38: invalid start byte

**Comment by dstftw** [comment]
Most likely `archive.txt` is not in UTF-8.
