### ISSUE TITLE
Download from pornhub, HTTP Error 400: Bad request

### ISSUE THREAD

**Issue by BruceDai003** [rg3/youtube-dl#14745]
```
C:\Users\brucedai> youtube-dl -v https://www.pornhub.com/view_video.php?viewkey=ph59fccff273b6d
[debug] System config: []
[debug] User config: ['--proxy', '127.0.0.1:51069', '-o', 'E:/Movies/%(title)s.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.pornhub.com/view_video.php?viewkey=ph59fccff273b6d']
[debug] Encodings: locale cp936, fs utf-8, out utf-8, pref cp936
[debug] youtube-dl version 2017.11.06
[debug] Python version 3.6.1 - Windows-10-10.0.15063-SP0
[debug] exe versions: none
[debug] Proxy map: {'http': '127.0.0.1:51069', 'https': '127.0.0.1:51069'}
[PornHub] ph59fccff273b6d: Downloading webpage
[PornHub] ph59fccff273b6d: Downloading webpage
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://bv.phncdn.com/videos/201711/03/139654502/720P_1500K_139654502.mp4?ip=45.76.195.
03/8&rs=140&ri=1600&s=1510647608&e=1510654808&h=96dda37059c22527100298ae27bc18ec'
ERROR: unable to download video data: HTTP Error 400: Bad Request
Traceback (most recent call last):
  File "d:\anaconda3\lib\site-packages\youtube_dl\YoutubeDL.py", line 1892, in process_info
    success = dl(filename, info_dict)
  File "d:\anaconda3\lib\site-packages\youtube_dl\YoutubeDL.py", line 1831, in dl
    return fd.download(name, info)
  File "d:\anaconda3\lib\site-packages\youtube_dl\downloader\common.py", line 361, in download
    return self.real_download(filename, info_dict)
  File "d:\anaconda3\lib\site-packages\youtube_dl\downloader\http.py", line 286, in real_download
    establish_connection()
  File "d:\anaconda3\lib\site-packages\youtube_dl\downloader\http.py", line 74, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "d:\anaconda3\lib\site-packages\youtube_dl\YoutubeDL.py", line 2195, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "d:\anaconda3\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "d:\anaconda3\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "d:\anaconda3\lib\urllib\request.py", line 570, in error
    return self._call_chain(*args)
  File "d:\anaconda3\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "d:\anaconda3\lib\urllib\request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request
```

I used to be able to download videos from pornhub via my proxy 3 months ago, but not now. Please help me.

**Comment by dstftw** [comment]
Most likely caused by your proxy.
