### ISSUE TITLE
hotstar and voot livestreamer not downloading video from voot ERROR: unable to download video data: HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by shank06** [rg3/youtube-dl#14758]
i was downlading videos from voot smoothely using youtube-dl v,exe but today i m not able to download single file i am getting error '

C:\Hotstar and Voot Downloader>v "https://www.voot.com/playlist/bigg-boss-uncut-
scenes/333246/hina-misses-her-pooh/548208/?&trayLayout=playlistMedias"
[Voot] 548208: Downloading JSON metadata
[Kaltura] 0_layzbckh: Downloading video info JSON
[Kaltura] 0_layzbckh: Downloading m3u8 information
ERROR: unable to download video data: HTTP Error 404: Not Found

C:\Hotstar and Voot Downloader>

I have even updated to current version

**Comment by shanmugam023** [comment]
Same error please find the solution

**Comment by Redball45** [comment]
Verbose output for the linked video
```
C:\Users\James>youtube-dl -v https://www.voot.com/playlist/bigg-boss-uncut-scenes/333246/hina-misses-her-pooh/548208/?&trayLayout=playlistMedias
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.voot.com/playlist/bigg-boss-uncut-scenes/333246/hina-misses-her-pooh/548208/?']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.11.15
[debug] Python version 3.5.4 - Windows-10-10.0.15063-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[debug] Using fake IP 117.244.81.97 (IN) as X-Forwarded-For.
[Voot] 548208: Downloading JSON metadata
[Kaltura] 0_layzbckh: Downloading video info JSON
[Kaltura] 0_layzbckh: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 404: Not Found
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'http://cdnapi.kaltura.com/p/1982551/sp/198255100/playManifest/entryId/0_layzbckh/format/url/protocol/http/flavorId/0_08ha83z2'
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "c:\users\james\appdata\local\programs\python\python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 1893, in process_info
    success = dl(filename, info_dict)
  File "c:\users\james\appdata\local\programs\python\python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 1832, in dl
    return fd.download(name, info)
  File "c:\users\james\appdata\local\programs\python\python35\lib\site-packages\youtube_dl\downloader\common.py", line 361, in download
    return self.real_download(filename, info_dict)
  File "c:\users\james\appdata\local\programs\python\python35\lib\site-packages\youtube_dl\downloader\http.py", line 286, in real_download
    establish_connection()
  File "c:\users\james\appdata\local\programs\python\python35\lib\site-packages\youtube_dl\downloader\http.py", line 74, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "c:\users\james\appdata\local\programs\python\python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 2196, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "c:\users\james\appdata\local\programs\python\python35\lib\urllib\request.py", line 472, in open
    response = meth(req, response)
  File "c:\users\james\appdata\local\programs\python\python35\lib\urllib\request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\users\james\appdata\local\programs\python\python35\lib\urllib\request.py", line 504, in error
    result = self._call_chain(*args)
  File "c:\users\james\appdata\local\programs\python\python35\lib\urllib\request.py", line 444, in _call_chain
    result = func(*args)
  File "c:\users\james\appdata\local\programs\python\python35\lib\urllib\request.py", line 696, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "c:\users\james\appdata\local\programs\python\python35\lib\urllib\request.py", line 472, in open
    response = meth(req, response)
  File "c:\users\james\appdata\local\programs\python\python35\lib\urllib\request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\users\james\appdata\local\programs\python\python35\lib\urllib\request.py", line 510, in error
    return self._call_chain(*args)
  File "c:\users\james\appdata\local\programs\python\python35\lib\urllib\request.py", line 444, in _call_chain
    result = func(*args)
  File "c:\users\james\appdata\local\programs\python\python35\lib\urllib\request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

'trayLayout' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by shank06** [comment]
Guys till the time ur livestreamer exe not working u can download videos Through an android app I.e. videoder.apk its not in play store its available on Google

**Comment by shank06** [comment]
https://www.watchmetech.com/voot-video-downloader/

**Comment by teamrajput** [comment]
I am also facing the same Issue on voot.com. Please rectify this issue.  I have pasted the verbose output below.
C:\Users\Thakur Rajesh Singh>"D:\Youtube-dl\youtube-dl.exe"  -v   --hls-use-mpegts --no-part -o "D:\Test.%(ext)s" "https://www.voot.com/movie/sapnay/520822"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--hls-use-mpegts', '--no-part', '-o', 'D:\\Test.%(ext)s', 'https://www.voot.com/movie/sapnay/520822']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.12.02
[debug] Python version 3.4.4 - Windows-10-10.0.16299
[debug] exe versions: ffmpeg 3.4
[debug] Proxy map: {}
[debug] Using fake IP 117.211.208.5 (IN) as X-Forwarded-For.
[Voot] 520822: Downloading JSON metadata
[Kaltura] 0_18gtopyl: Downloading video info JSON
[Kaltura] 0_18gtopyl: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://cdnapi.kaltura.com/p/1982551/sp/198255100/playManifest/entryId/0_18gtopyl/format/url/protocol/http/flavorId/0_delizpgf'
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcuf0d0kb\build\youtube_dl\YoutubeDL.py", line 1893, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcuf0d0kb\build\youtube_dl\YoutubeDL.py", line 1832, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcuf0d0kb\build\youtube_dl\downloader\common.py", line 361, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcuf0d0kb\build\youtube_dl\downloader\http.py", line 286, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcuf0d0kb\build\youtube_dl\downloader\http.py", line 74, in establish_connection
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcuf0d0kb\build\youtube_dl\YoutubeDL.py", line 2196, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 502, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 685, in http_error_302
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

**Comment by PannenkoekenNL** [comment]
I sadly get the exact same error.

**Comment by teamrajput** [comment]
The esteemed Developers,  please rectify this issue. Its pending for more than a month. A humble request.

**Comment by teamrajput** [comment]
The error still persists in the new version of youtube-dl version 2017.12.14  . The verbose output: 

C:\Windows\system32>"D:\Youtube-dl\youtube-dl.exe"  -v   --hls-use-mpegts --no-part -o "H:\Bedardi.%(ext)s" "https://www.voot.com/movie/bedardi/550020"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--hls-use-mpegts', '--no-part', '-o', 'H:\\Bedardi.%(ext)s', 'https://www.voot.com/movie/bedardi/550020']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.12.14
[debug] Python version 3.4.4 - Windows-10-10.0.16299
[debug] exe versions: ffmpeg 3.4
[debug] Proxy map: {}
[debug] Using fake IP 117.234.230.40 (IN) as X-Forwarded-For.
[Voot] 550020: Downloading JSON metadata
[Kaltura] 0_7syz6hpi: Downloading video info JSON
[Kaltura] 0_7syz6hpi: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://cdnapi.kaltura.com/p/1982551/sp/198255100/playManifest/entryId/0_7syz6hpi/format/url/protocol/http/flavorId/0_mwbkv31x'
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpekokknty\build\youtube_dl\YoutubeDL.py", line 1893, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpekokknty\build\youtube_dl\YoutubeDL.py", line 1832, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpekokknty\build\youtube_dl\downloader\common.py", line 361, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpekokknty\build\youtube_dl\downloader\http.py", line 286, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpekokknty\build\youtube_dl\downloader\http.py", line 74, in establish_connection
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpekokknty\build\youtube_dl\YoutubeDL.py", line 2196, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 502, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 685, in http_error_302
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

**Comment by teamrajput** [comment]
Dear  Esteemed Developer
                 The error still persists in the latest version of youtube-dl .   I am pasting the verbose output below:

C:\Windows\system32>"D:\Youtube-dl\youtube-dl.exe"  -v   --hls-use-mpegts --no-part -o "H:\Bedardi.%(ext)s" "https://www.voot.com/movie/bedardi/550020"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--hls-use-mpegts', '--no-part', '-o', 'H:\\Bedardi.%(ext)s', 'https://www.voot.com/movie/bedardi/550020']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.12.14
[debug] Python version 3.4.4 - Windows-10-10.0.16299
[debug] exe versions: ffmpeg 3.4
[debug] Proxy map: {}
[debug] Using fake IP 117.234.230.40 (IN) as X-Forwarded-For.
[Voot] 550020: Downloading JSON metadata
[Kaltura] 0_7syz6hpi: Downloading video info JSON
[Kaltura] 0_7syz6hpi: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://cdnapi.kaltura.com/p/1982551/sp/198255100/playManifest/entryId/0_7syz6hpi/format/url/protocol/http/flavorId/0_mwbkv31x'
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpekokknty\build\youtube_dl\YoutubeDL.py", line 1893, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpekokknty\build\youtube_dl\YoutubeDL.py", line 1832, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpekokknty\build\youtube_dl\downloader\common.py", line 361, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpekokknty\build\youtube_dl\downloader\http.py", line 286, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpekokknty\build\youtube_dl\downloader\http.py", line 74, in establish_connection
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpekokknty\build\youtube_dl\YoutubeDL.py", line 2196, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 502, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 685, in http_error_302
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found






Please look into this.

With Regards
Rajesh Singh

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by remitamine** [comment]
it's not released yet.

**Comment by teamrajput** [comment]
Hi @remitamine
             Thanks for rectifying the error regarding voot.com. God bless u.

Regards
Rajesh Singh
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
