### ISSUE TITLE
Unable to download Facebook.com's embedded videos.

### ISSUE THREAD

**Issue by antdude** [rg3/youtube-dl#14761]
Example:

$  youtube-dl -v "https://www.facebook.com/BlueManGroupFans/posts/1747439181956701"   [debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.facebook.com/BlueManGroupFans/posts/1747439181956701']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.11.15
[debug] Python version 3.4.2 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.9
[debug] exe versions: ffmpeg 3.2.5-1, ffprobe 3.2.5-1, rtmpdump 2.4
[debug] Proxy map: {}
[facebook] 1747439181956701: Downloading webpage
ERROR: Unable to extract video ids; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/common.py", line 437, in extract
    ie_result = self._real_extract(url)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/facebook.py", line 415, in _real_extract
    webpage, 'video ids', group='ids'),
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/common.py", line 800, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract video ids; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Thank you in advance. :)

**Comment by yan12125** [comment]
This is actually an Instagram embedded video https://www.instagram.com/p/BbdT4kHAt1G/, which is supported by youtube-dl. The URL can be retrieved via right click -> open link in new tab in Firefox.

**Comment by antdude** [comment]
Thank you, yan12125. I didn't know about that trick. :)

**Comment by mzfr** [comment]
@antdude if you don't have this issue now then please close the issue

**Comment by antdude** [comment]
mzfr: Shouldn't youtube-dl detect it for users?

**Comment by yan12125** [comment]
@antdude is right. This is still a valid issue.

**Comment by antdude** [comment]
Thank you, yan12125. :)

**Comment by NulAsh** [comment]
youtube-dl.exe --socket-timeout=30 --verbose https://www.instagram.com/p/Bzk06ekhirOu2XoyYnrpsSDqq49PTrvO8CYihY0/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--socket-timeout=30', '--verbose', 'https://www.instagram.com/p/Bzk06ekhirOu2XoyYnrpsSDqq49PTrvO8CYihY0/']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2019.11.05
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-93755-ga5387f983d, ffprobe N-93755-ga5387f983d
[debug] Proxy map: {'no': '192.168.99.100'}
[Instagram] Bzk06ekhirOu2XoyYnrpsSDqq49PTrvO8CYihY0: Downloading webpage
ERROR: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7hc5a09v\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7hc5a09v\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7hc5a09v\build\youtube_dl\extractor\instagram.py", line 195, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7hc5a09v\build\youtube_dl\extractor\common.py", line 1123, in _og_search_video_url
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7hc5a09v\build\youtube_dl\extractor\common.py", line 1014, in _html_search_regex
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp7hc5a09v\build\youtube_dl\extractor\common.py", line 1005, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by turkeyphant** [comment]
Instagram stories are also currently unsupported to I'd like to request this too please.
