### ISSUE TITLE
Cannot download specific video from VEVO.com

### ISSUE THREAD

**Issue by Klaus1189** [rg3/youtube-dl#14787]
When I try to download https://www.vevo.com/watch/elena-paparizoy/(official-music-video)/GRUV71700172 I get **ERROR: string indices must be integers**

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.

**Comment by Klaus1189** [comment]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.11.15*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ ] I've **verified** and **I assure** that I'm running youtube-dl **2017.11.15**

### Before submitting an *issue* make sure you have:
- [ ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2017.11.15
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.


C:\Users\Klaus\Documents\Programme\youtube-dl>youtube-dl -F -v https://www.vevo.com/watch/elena-paparizoy/(official-music-video)/GRUV71700172
[debug] System config: []
[debug] User config: ['--no-check-certificate', '--ignore-errors', '--no-continue', '--no-overwrites', '--proxy', '']
[debug] Custom config: []
[debug] Command-line args: ['-F', '-v', 'https://www.vevo.com/watch/elena-paparizoy/(official-music-video)/GRUV71700172']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.11.15
[debug] Python version 3.4.4 - Windows-10-10.0.16299
[debug] exe versions: none
[debug] Proxy map: {}
[Vevo] Retrieving oauth token
[Vevo] GRUV71700172: Downloading api video info
ERROR: string indices must be integers
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp10f7prtw\build\youtube_dl\extractor\common.py", line 506, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp10f7prtw\build\youtube_dl\YoutubeDL.py", line 2196, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
urllib.error.HTTPError: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp10f7prtw\build\youtube_dl\extractor\vevo.py", line 178, in _call_api
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp10f7prtw\build\youtube_dl\extractor\common.py", line 684, in _download_json
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp10f7prtw\build\youtube_dl\extractor\common.py", line 638, in _download_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp10f7prtw\build\youtube_dl\extractor\common.py", line 535, in _download_webpage_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp10f7prtw\build\youtube_dl\extractor\common.py", line 515, in _request_webpage
youtube_dl.utils.ExtractorError: Failed to download video info: HTTP Error 400: Bad Request (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp10f7prtw\build\youtube_dl\YoutubeDL.py", line 784, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp10f7prtw\build\youtube_dl\extractor\common.py", line 437, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp10f7prtw\build\youtube_dl\extractor\vevo.py", line 194, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp10f7prtw\build\youtube_dl\extractor\vevo.py", line 182, in _call_api
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp10f7prtw\build\youtube_dl\extractor\vevo.py", line 182, in <listcomp>
TypeError: string indices must be integers


C:\Users\Klaus\Documents\Programme\youtube-dl>

**Comment by Klaus1189** [comment]
Srry it's too high for me, let me know if you more info :(

**Comment by Klaus1189** [comment]
enough info?

**Comment by Klaus1189** [comment]
??

**Comment by Hrxn** [comment]
Can you try it with `youtube-dl --verbose --ignore-config LINK`?

**Comment by Klaus1189** [comment]
Ok, I tried it, I get:

C:\Users\Klaus\Documents\Programme\youtube-dl>youtube-dl --verbose --ignore-config -F https://www.vevo.com/watch/elena-paparizoy/(official-music-video)/GRUV71700172
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--ignore-config', '-F', 'https://www.vevo.com/watch/elena-paparizoy/(official-music-video)/GRUV71700172']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.11.15
[debug] Python version 3.4.4 - Windows-10-10.0.16299
[debug] exe versions: none
[debug] Proxy map: {}
[Vevo] Retrieving oauth token
[Vevo] GRUV71700172: Downloading api video info
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp10f7prtw\build\youtube_dl\extractor\common.py", line 506, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp10f7prtw\build\youtube_dl\YoutubeDL.py", line 2196, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
urllib.error.HTTPError: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp10f7prtw\build\youtube_dl\extractor\vevo.py", line 178, in _call_api
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp10f7prtw\build\youtube_dl\extractor\common.py", line 684, in _download_json
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp10f7prtw\build\youtube_dl\extractor\common.py", line 638, in _download_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp10f7prtw\build\youtube_dl\extractor\common.py", line 535, in _download_webpage_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp10f7prtw\build\youtube_dl\extractor\common.py", line 515, in _request_webpage
youtube_dl.utils.ExtractorError: Failed to download video info: HTTP Error 400: Bad Request (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp10f7prtw\build\youtube_dl\__init__.py", line 465, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp10f7prtw\build\youtube_dl\__init__.py", line 455, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp10f7prtw\build\youtube_dl\YoutubeDL.py", line 1986, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp10f7prtw\build\youtube_dl\YoutubeDL.py", line 784, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp10f7prtw\build\youtube_dl\extractor\common.py", line 437, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp10f7prtw\build\youtube_dl\extractor\vevo.py", line 194, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp10f7prtw\build\youtube_dl\extractor\vevo.py", line 182, in _call_api
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp10f7prtw\build\youtube_dl\extractor\vevo.py", line 182, in <listcomp>
TypeError: string indices must be integers

C:\Users\Klaus\Documents\Programme\youtube-dl>

**Comment by Klaus1189** [comment]
What else can I do?

**Comment by Klaus1189** [comment]
Still doesn't work :(
