### ISSUE TITLE
Youku api need to be updated, error -6004: 客户端无权播放

### ISSUE THREAD

**Issue by jimmylab** [rg3/youtube-dl#14815]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.11.15*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.11.15**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://v.youku.com/v_show/id_XMzE3MDY1MTExMg==.html']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2017.11.15
[debug] Python version 3.4.4 - Windows-8.1-6.3.9600
[debug] exe versions: ffmpeg N-83882-g58f0bbc, ffprobe N-83882-g58f0bbc
[debug] Proxy map: {}
[youku] XMzE3MDY1MTExMg: Retrieving cna info
[youku] XMzE3MDY1MTExMg: Downloading JSON metadata
ERROR: Youku server reported error -6004: 客户端无权播放,201; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp10f7prtw\build\youtube_dl\YoutubeDL.py", line 784, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp10f7prtw\build\youtube_dl\extractor\common.py", line 437, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp10f7prtw\build\youtube_dl\extractor\youku.py", line 189, in _real_extract
youtube_dl.utils.ExtractorError: Youku server reported error -6004: 客户端无权播放,201; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://v.youku.com/v_show/id_XMzE3MDY1MTExMg==.html

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

You can pick up **any** video on index page, and test if it has the same issue.

**Comment by jimmylab** [comment]
Parameter 'ccode' needs to be updated, reference: https://github.com/soimort/you-get/issues/2506 @yan12125

**Comment by yan12125** [comment]
@jimmylab: Thank you for the pointer and thank @epdq for the fix. youtube-dl will be fixed for Youku videos in the next version.

**Comment by ziyangchen123** [comment]
修改：youku.py第157行
将'ccode': '0402' if 'tudou.com' in url else '0401',修改为
    'ccode': '0502' if 'tudou.com' in url else '0502',主要是因为优酷更新了，修改了ccode值。
该文件位于/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youku.py
具体需要看你将yutube-dl安装在哪里

**Comment by CoXier** [comment]
2017.11.15 version seems not fixed.@yan12125

**Comment by yan12125** [comment]
@CoXier: The fix is not included in the current version yet. Please wait for the next version.

**Comment by CoXier** [comment]
@yan12125 2017.11.26 has same bug.

Test Url:   http://v.youku.com/v_show/id_XMTM1NzMyMzMy.html

**Comment by ellicefix** [comment]
I encountered the same problem

**Comment by willguxy** [comment]
https://github.com/rg3/youtube-dl/commit/0981585befc7af01331b72304ed11b9865b40401#diff-523488407b0e8dec3ea0f0487c4ed54f

was this commit intentional? line 157 was changed to '5002' previously, but now it's '5001'

**Comment by ipfans** [comment]
It also broken on 2017.12.14. 

```
$ youtube-dl --version
2017.12.14

$ youtube-dl --verbose http://v.youku.com/v_show/id_XMzE3NDM4NDg1Ng\=\=.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'http://v.youku.com/v_show/id_XMzE3NDM4NDg1Ng==.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.12.14
[debug] Python version 3.6.3 - Darwin-17.3.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.4.1, ffprobe 3.4.1, phantomjs 2.1.1
[debug] Proxy map: {'https': 'http://127.0.0.1:8032', 'http': 'http://127.0.0.1:8032'}
[youku] XMzE3NDM4NDg1Ng: Retrieving cna info
[youku] XMzE3NDM4NDg1Ng: Downloading JSON metadata
ERROR: Youku server reported error -6004: 客户端无权播放,201; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/Users/USER/.pyenv/versions/3.6.3/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "/Users/USER/.pyenv/versions/3.6.3/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 437, in extract
    ie_result = self._real_extract(url)
  File "/Users/USER/.pyenv/versions/3.6.3/lib/python3.6/site-packages/youtube_dl/extractor/youku.py", line 189, in _real_extract
    raise ExtractorError(msg)
youtube_dl.utils.ExtractorError: Youku server reported error -6004: 客户端无权播放,201; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by krungchen** [comment]
i am getting the same error in youtube-dl version 2018.08.04

**Comment by Iyozhikov** [comment]
Hi. just updated an also have same error:
#> youtube-dl "https://v.youku.com/v_show/id_XOTM0OTM4OTUy.html?spm=a2h0k.11417342.soresults.dtitle" --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://v.youku.com/v_show/id_XOTM0OTM4OTUy.html?spm=a2h0k.11417342.soresults.dtitle', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.09.10
[debug] Python version 3.6.5 (CPython) - Linux-4.15.0-29deepin-generic-x86_64-with-Deepin-15.7-unstable
[debug] exe versions: ffmpeg 3.4.2-2, ffprobe 3.4.2-2, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youku] XOTM0OTM4OTUy: Retrieving cna info
[youku] XOTM0OTM4OTUy: Downloading JSON metadata
ERROR: Youku server reported error -6004: 客户端无权播放,201; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/mad666/.local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/home/mad666/.local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 502, in extract
    ie_result = self._real_extract(url)
  File "/home/mad666/.local/lib/python3.6/site-packages/youtube_dl/extractor/youku.py", line 189, in _real_extract
    raise ExtractorError(msg)
youtube_dl.utils.ExtractorError: Youku server reported error -6004: 客户端无权播放,201; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
#> youtube-dl --version
2018.09.10
