### ISSUE TITLE
Unsupported URL :- cricket.com.au

### ISSUE THREAD

**Issue by rajucomp** [rg3/youtube-dl#14846]
Cricket.com.au yields Unspported URL.  <br>
Here is the log. <br>
youtube-dl -v http://www.cricket.com.au/news/match-report/australia-england-first-ashes-test-day-three-gabba-live-stream-scores-highlights-scores-smith-marsh/2017-11-25 > log.txt
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--prefer-ffmpeg', u'-v', u'http://www.cricket.com.au/news/match-report/australia-england-first-ashes-test-day-three-gabba-live-stream-scores-highlights-scores-smith-marsh/2017-11-25']
[debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8
[debug] youtube-dl version 2017.11.15
[debug] Python version 2.7.12 - Linux-4.4.0-101-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 10.7, avprobe 10.7, ffmpeg 3.4-1, ffprobe 3.4-1
[debug] Proxy map: {}
WARNING: Falling back on generic information extractor.
ERROR: Unsupported URL: http://www.cricket.com.au/news/match-report/australia-england-first-ashes-test-day-three-gabba-live-stream-scores-highlights-scores-smith-marsh/2017-11-25
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 2170, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/compat.py", line 2539, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/compat.py", line 2528, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 19, column 26
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 437, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 3075, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.cricket.com.au/news/match-report/australia-england-first-ashes-test-day-three-gabba-live-stream-scores-highlights-scores-smith-marsh/2017-11-25

**Comment by philipl** [comment]
I wrote an extractor: https://github.com/philipl/youtube-dl-cricket/
