### ISSUE TITLE
Download MPD File - no video formats found

### ISSUE THREAD

**Issue by ben45c** [rg3/youtube-dl#14853]
Hi all, I'm trying to download a MPD file which contains dash format videos, however when I put the link into youtube-dl, it spits out this error:
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp10f7prtw\build\youtube_dl\YoutubeDL.py", line 784, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp10f7prtw\build\youtube_dl\extractor\common.py", line 437, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp10f7prtw\build\youtube_dl\extractor\generic.py", line 2188, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp10f7prtw\build\youtube_dl\extractor\common.py", line 1075, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

I have the latest version but still having problems. If any of you could help that would be much appreciated. The link to the MPD is https://foxteldashlive01.akamaized.net/live/channel024/channel024_mcs.isml/playlist_high.mpd?hdnts=exp=1511712453~hmac=1dcc0e05de36d7edbdf314a737ace2f359ef7c8043f2232cd494b9de96f95cb8. Cheers

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
