### ISSUE TITLE
PBS format not found

### ISSUE THREAD

**Issue by curgeo** [rg3/youtube-dl#14865]
### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)

---
youtube-dl -F -v http://www.pbs.org/video/episode-5-immigrant-nation-bv37tx/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-F', '-v', 'http://www.pbs.org/video/episode-5-immigrant-nation-bv37tx/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.11.26
[debug] Python version 3.4.4 - Windows-10-10.0.15063
[debug] exe versions: ffmpeg N-86755-g0780ad9, ffprobe N-86755-g0780ad9
[debug] Proxy map: {}
[debug] Using fake IP 3.4.94.46 (US) as X-Forwarded-For.
[pbs] Downloading JSON metadata
[pbs] episode-5-immigrant-nation-bv37tx: Downloading webpage
[pbs] Downloading widget/partnerplayer page
WARNING: Unable to download webpage: HTTP Error 404: Not Found
[pbs] Downloading portalplayer page
WARNING: Unable to download webpage: HTTP Error 404: Not Found
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp42up454x\build\youtube_dl\YoutubeDL.py", line 784, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp42up454x\build\youtube_dl\extractor\common.py", line 437, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp42up454x\build\youtube_dl\extractor\pbs.py", line 589, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp42up454x\build\youtube_dl\extractor\common.py", line 1067, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug

---

### Description of your *issue*, suggested solution and other information

PBS format not found. Worked previously.

**Comment by remitamine** [comment]
already fixed, the fix will be included in the next release.
