### ISSUE TITLE
KIJK.NL  (SBS6) downloads have stopped working...

### ISSUE THREAD

**Issue by MatrixView** [rg3/youtube-dl#14891]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.11.26**
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Bug report (encountered problems with youtube-dl)

---
KIJK.NL downloads don't seem to work anymore. Maybe a consent.sbs6.nl cookie is needed?
Hope you can fix this! Thx in advance!

```
youtube-dl -v "http://www.sbs6.nl/programmas/de-grote-verbouwing/videos/z33355IlYBk/de-grote-verbouwing/"

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://www.sbs6.nl/programmas/de-grote-verbouwing/videos/z33355IlYBk/de-grote-verbouwing/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.11.26
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-67388-g37425fc, ffprobe N-67388-g37425fc, rtmpdump 2.4-47-gc26c541
[debug] Proxy map: {}
[generic] de-grote-verbouwing: Requesting header
[redirect] Following redirect to http://consent.sbs6.nl/?url=http://www.sbs6.nl/programmas/de-grote-verbouwing/videos/z33355IlYBk/de-grote-verbouwing/
[generic] de-grote-verbouwing: Requesting header
WARNING: Falling back on generic information extractor.
[generic] de-grote-verbouwing: Downloading webpage
[generic] de-grote-verbouwing: Extracting information
ERROR: Unsupported URL: http://consent.sbs6.nl/?url=http://www.sbs6.nl/programmas/de-grote-verbouwing/videos/z33355IlYBk/de-grote-verbouwing/
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp42up454x\build\youtube_dl\YoutubeDL.py", line 784, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp42up454x\build\youtube_dl\extractor\common.py", line 437, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp42up454x\build\youtube_dl\extractor\generic.py", line 3088, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: http://consent.sbs6.nl/?url=http://www.sbs6.nl/programmas/de-grote-verbouwing/videos/z33355IlYBk/de-grote-verbouwing/
```

**Comment by matthijsbreemans** [comment]
Cookie needs to be set: OPTOUTMULTI: 0:0c5:0c1:0c4:0c3:0c2:0

**Comment by solipsist01** [comment]
can you give an example of your cookies.txt entry

**Comment by Invictaz** [comment]
@MatrixView @matthijsbreemans 

Did you get this working. I did as @solipsist01 did with the cookies file and it still gives unsupported URL.

**Comment by zmrh** [comment]
Same problem here. The cookie is **not** the problem, as without a cookie it would redirect to consent.kijk.nl to set a cookie.

_Without cookie:_
`youtube-dl https://www.kijk.nl/sbs6/demeldkamer/videos/k9EvhSDpgeP/de-meldkamer`
```
[generic] de-meldkamer: Requesting header
[redirect] Following redirect to http://consent.kijk.nl/?url=https://www.kijk.nl/sbs6/demeldkamer/videos/k9EvhSDpgeP/de-meldkamer
[generic] de-meldkamer: Requesting header
WARNING: Falling back on generic information extractor.
[generic] de-meldkamer: Downloading webpage
[generic] de-meldkamer: Extracting information
ERROR: Unsupported URL: http://consent.kijk.nl/?url=https://www.kijk.nl/sbs6/demeldkamer/videos/k9EvhSDpgeP/de-meldkamer
```

_With cookie:_
`youtube-dl https://www.kijk.nl/sbs6/demeldkamer/videos/k9EvhSDpgeP/de-meldkamer --add-header Cookie:OPTOUTMULTI=0:0%7Cc5:0%7Cc1:0%7Cc4:0%7Cc3:0%7Cc2:0`

```
[generic] de-meldkamer: Requesting header
WARNING: Falling back on generic information extractor.
[generic] de-meldkamer: Downloading webpage
[generic] de-meldkamer: Extracting information
ERROR: Unsupported URL: https://www.kijk.nl/sbs6/demeldkamer/videos/k9EvhSDpgeP/de-meldkamer
```


_Verbose output_

`youtube-dl -v https://www.kijk.nl/sbs6/demeldkamer/videos/k9EvhSDpgeP/de-meldkamer --add-header Cookie:OPTOUTMULTI=0:0%7Cc5:0%7Cc1:0%7Cc4:0%7Cc3:0%7Cc2:0`
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.kijk.nl/sbs6/demeldkamer/videos/k9EvhSDpgeP/de-meldkamer', u'--add-header', u'Cookie:OPTOUTMULTI=0:0%7Cc5:0%7Cc1:0%7Cc4:0%7Cc3:0%7Cc2:0']
[debug] Adding header from command line option Cookie:OPTOUTMULTI=0:0%7Cc5:0%7Cc1:0%7Cc4:0%7Cc3:0%7Cc2:0
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.02.26
[debug] Python version 2.7.10 (CPython) - Darwin-17.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.4.1, ffprobe 3.4.1
[debug] Proxy map: {}
[generic] de-meldkamer: Requesting header
WARNING: Falling back on generic information extractor.
[generic] de-meldkamer: Downloading webpage
[generic] de-meldkamer: Extracting information
ERROR: Unsupported URL: https://www.kijk.nl/sbs6/demeldkamer/videos/k9EvhSDpgeP/de-meldkamer
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2208, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2542, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2531, in _XML
    parser.feed(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: syntax error: line 1, column 0
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 785, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3127, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.kijk.nl/sbs6/demeldkamer/videos/k9EvhSDpgeP/de-meldkamer

```
