### ISSUE TITLE
openload.co: AttributeError: 'PhantomJSwrapper' object has no attribute '_TMP_FILES'

### ISSUE THREAD

**Issue by cweiske** [rg3/youtube-dl#14928]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.12.02**
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)

---

```
$ youtube-dl -v https://openload.co/f/dp324oEiB3M
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://openload.co/f/dp324oEiB3M']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.12.02
[debug] Python version 3.4.3 - Linux-3.13.0-135-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 11.3-6, avprobe 11.3-6, ffmpeg 0.8.13-6, rtmpdump 2.4
[debug] Proxy map: {}
[Openload] dp324oEiB3M: Downloading webpage
ERROR: PhantomJS executable not found in PATH, download it from http://phantomjs.org
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.4/dist-packages/youtube_dl/extractor/common.py", line 437, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.4/dist-packages/youtube_dl/extractor/openload.py", line 314, in _real_extract
    phantom = PhantomJSwrapper(self, required_version='2.0')
  File "/usr/local/lib/python3.4/dist-packages/youtube_dl/extractor/openload.py", line 119, in __init__
    expected=True)
youtube_dl.utils.ExtractorError: PhantomJS executable not found in PATH, download it from http://phantomjs.org

Exception ignored in: <bound method PhantomJSwrapper.__del__ of <youtube_dl.extractor.openload.PhantomJSwrapper object at 0x7f15b518b5f8>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/youtube_dl/extractor/openload.py", line 142, in __del__
    os.remove(self._TMP_FILES[name].name)
AttributeError: 'PhantomJSwrapper' object has no attribute '_TMP_FILES'
```
---

### Description of your *issue*, suggested solution and other information

Downloading a file from openload.co fails with the error

> AttributeError: 'PhantomJSwrapper' object has no attribute '_TMP_FILES'

Example:  `$ youtube-dl -v https://openload.co/f/dp324oEiB3M`

**Comment by dstftw** [comment]
>ERROR: PhantomJS executable not found in PATH, download it from http://phantomjs.org
