### ISSUE TITLE
Youtube Red Videos Weird Issues

### ISSUE THREAD

**Issue by misaka00251** [rg3/youtube-dl#14939]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.12.02*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.12.02**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'-f', u'137+251', u'https://www.youtube.com/watch?v=zD68reVP0Ek']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.12.02
[debug] Python version 2.6.6 - Linux-2.6.32-642.el6.x86_64-x86_64-with-centos-6.9-Final
[debug] exe versions: ffmpeg 2.6.8, ffprobe 2.6.8
[debug] Proxy map: {}
[youtube] Downloading login page
[youtube] Looking up account info
[youtube] Logging in
Traceback (most recent call last):
  File "/usr/lib64/python2.6/runpy.py", line 122, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.6/runpy.py", line 34, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 465, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 455, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1986, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 784, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 436, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 394, in initialize
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 258, in _real_initialize
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 233, in _login
UnboundLocalError: local variable 'check_cookie_url' referenced before assignment
```

---

### Description of your *issue*, suggested solution and other information

Sometimes it works but couldn't login, but i'm *sure* i type the correct password:
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'-f', u'137+251', u'https://www.youtube.com/watch?v=qZXpgf8N6hs']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.12.02
[debug] Python version 2.6.6 - Linux-2.6.32-642.el6.x86_64-x86_64-with-centos-6.9-Final
[debug] exe versions: ffmpeg 2.6.8, ffprobe 2.6.8
[debug] Proxy map: {}
[youtube] Downloading login page
[youtube] Looking up account info
[youtube] Logging in
WARNING: Unable to login: Invalid password
[youtube] qZXpgf8N6hs: Downloading webpage
[youtube] riV8wRmElec: Downloading webpage
[youtube] riV8wRmElec: Downloading video info webpage
[youtube] riV8wRmElec: Extracting video information
[youtube] {22} signature length 40.40, html5 player vfl4OEYh9
[youtube] {43} signature length 40.40, html5 player vfl4OEYh9
[youtube] {18} signature length 40.40, html5 player vfl4OEYh9
[youtube] {36} signature length 40.40, html5 player vfl4OEYh9
[youtube] {17} signature length 40.40, html5 player vfl4OEYh9
[youtube] {137} signature length 40.40, html5 player vfl4OEYh9
[youtube] {248} signature length 40.40, html5 player vfl4OEYh9
[youtube] {136} signature length 40.40, html5 player vfl4OEYh9
[youtube] {247} signature length 40.40, html5 player vfl4OEYh9
[youtube] {135} signature length 40.40, html5 player vfl4OEYh9
[youtube] {244} signature length 40.40, html5 player vfl4OEYh9
[youtube] {134} signature length 40.40, html5 player vfl4OEYh9
[youtube] {243} signature length 38.40, html5 player vfl4OEYh9
[youtube] riV8wRmElec: Downloading player https://www.youtube.com/yts/jsbin/player-vfl4OEYh9/en_US/base.js
[youtube] {133} signature length 40.40, html5 player vfl4OEYh9
[youtube] {242} signature length 40.40, html5 player vfl4OEYh9
[youtube] {160} signature length 40.40, html5 player vfl4OEYh9
[youtube] {278} signature length 40.40, html5 player vfl4OEYh9
[youtube] {140} signature length 40.40, html5 player vfl4OEYh9
[youtube] {171} signature length 40.40, html5 player vfl4OEYh9
[youtube] {249} signature length 40.40, html5 player vfl4OEYh9
[youtube] {250} signature length 40.40, html5 player vfl4OEYh9
[youtube] {251} signature length 40.40, html5 player vfl4OEYh9
[youtube] riV8wRmElec: Downloading MPD manifest
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[download] Mind Field - Episode 4 Free Preview-riV8wRmElec.mkv has already been downloaded and merged
```
Never mind that's google's fault

**Comment by dstftw** [comment]
Post the failed output with `--dump-pages`.

**Comment by misaka00251** [comment]
output is [here](https://gist.github.com/misaka00251/5e4c8fddd5b56d830567e01570547531)

**Comment by dstftw** [comment]
>**failed output**

**Comment by misaka00251** [comment]
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'-f', u'137+251', u'https://www.youtube.com/watch?v=qZXpgf8N6hs', u'--dump-pages']
[debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8
[debug] youtube-dl version 2017.12.02
[debug] Python version 2.6.6 - Linux-2.6.32-642.el6.x86_64-x86_64-with-centos-6.9-Final
[debug] exe versions: ffmpeg 2.6.8, ffprobe 2.6.8
[debug] Proxy map: {}
Traceback (most recent call last):
  File "/usr/lib64/python2.6/runpy.py", line 122, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.6/runpy.py", line 34, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 465, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 455, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1986, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 784, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 436, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 394, in initialize
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 258, in _real_initialize
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 233, in _login
UnboundLocalError: local variable 'check_cookie_url' referenced before assignment
```

**Comment by misaka00251** [comment]
Terminal only output that...
Also, when I try to save the output into a txt file, it is a incomplete output too. >.>
[Screenshot](https://imgur.com/a/iiAu4)

**Comment by dstftw** [comment]
Cause you did not redirect stderr but only stdout.

**Comment by misaka00251** [comment]
I'm so sorry I make a mistake of it.
[Seems ok now.](https://gist.github.com/misaka00251/91dba86cca6c99d85ec178daa487db40)
