### ISSUE TITLE
Downloading playlist fails

### ISSUE THREAD

**Issue by Spenhouet** [rg3/youtube-dl#14940]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.12.02**
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)

---

```
youtube-dl -v --ignore-config https://www.youtube.com/watch?v=B8vlk1UR99k&list=PLr9smI_szfwmoB6HvBF6uC-ax1XQsm9SV
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--ignore-config', 'https://www.youtube.com/watch?v=B8vlk1UR99k']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.12.02
[debug] Python version 3.4.4 - Windows-10-10.0.16299
[debug] exe versions: ffmpeg N-86809-g012620a, ffprobe N-86809-g012620a
[debug] Proxy map: {}
[youtube] B8vlk1UR99k: Downloading webpage
[youtube] B8vlk1UR99k: Downloading video info webpage
[youtube] B8vlk1UR99k: Extracting video information
[youtube] {22} signature length 40.40, html5 player vfl4OEYh9
[youtube] {43} signature length 40.40, html5 player vfl4OEYh9
[youtube] {18} signature length 40.40, html5 player vfl4OEYh9
[youtube] {36} signature length 40.40, html5 player vfl4OEYh9
[youtube] {17} signature length 40.40, html5 player vfl4OEYh9
[youtube] {137} signature length 40.40, html5 player vfl4OEYh9
[youtube] {248} signature length 40.40, html5 player vfl4OEYh9
[youtube] {136} signature length 40.40, html5 player vfl4OEYh9
[youtube] {247} signature length 40.40, html5 player vfl4OEYh9
[youtube] {135} signature length 40.40, html5 player vfl4OEYh9
[youtube] {244} signature length 40.40, html5 player vfl4OEYh9
[youtube] {134} signature length 40.40, html5 player vfl4OEYh9
[youtube] {243} signature length 40.40, html5 player vfl4OEYh9
[youtube] {133} signature length 40.40, html5 player vfl4OEYh9
[youtube] {242} signature length 40.40, html5 player vfl4OEYh9
[youtube] {160} signature length 40.40, html5 player vfl4OEYh9
[youtube] {278} signature length 40.40, html5 player vfl4OEYh9
[youtube] {140} signature length 40.40, html5 player vfl4OEYh9
[youtube] {171} signature length 40.40, html5 player vfl4OEYh9
[youtube] {249} signature length 40.40, html5 player vfl4OEYh9
[youtube] {250} signature length 40.40, html5 player vfl4OEYh9
[youtube] {251} signature length 40.40, html5 player vfl4OEYh9
[youtube] B8vlk1UR99k: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on 'https://r1---sn-4g5edne7.googlevideo.com/videoplayback?id=07cbe5935511f7d9&itag=137&source=youtube&requiressl=yes&ei=3AwsWv7GNI-K1wLok7eADQ&mv=m&mm=31&mn=sn-4g5edne7&pl=17&ms=au&initcwndbps=1380000&ratebypass=yes&mime=video/mp4&gir=yes&clen=61264593&lmt=1507174675260407&dur=231.439&signature=8A632BBBF86AD2CF521D1E8959FBEF726BDAA94A.75A94913380B1A153F0BDEF9252315A320A41FBF&mt=1512836208&key=dg_yt0&ip=95.208.119.39&ipbits=0&expire=1512857916&sparams=ip,ipbits,expire,id,itag,source,requiressl,ei,mv,mm,mn,pl,ms,initcwndbps,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: Sub Focus - Tidal Wave ft. Alpines-B8vlk1UR99k.f137.mp4
[download] 100% of 58.43MiB in 00:01
[debug] Invoking downloader on 'https://r1---sn-4g5e6nl6.googlevideo.com/videoplayback?gir=yes&lmt=1449553953562959&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&ei=3AwsWvS2DoPS1gKJ9Z_ACA&initcwndbps=1273750&dur=231.481&key=yt6&ipbits=0&itag=251&keepalive=yes&clen=3736054&ip=95.208.119.39&mime=audio%2Fwebm&requiressl=yes&mn=sn-4g5e6nl6&pl=17&source=youtube&mm=31&mv=m&mt=1512836208&ms=au&id=o-AMi9r7UVwpRlpFbKTuKQ3kCy5gmH4msZ-U58WzUZIbvf&expire=1512857916&signature=D160784A5F05ACE9D728A43C09246A0A6F7F530C.30C5A692B4C16C2A4E13F117703F58943B741633&ratebypass=yes'
[download] Destination: Sub Focus - Tidal Wave ft. Alpines-B8vlk1UR99k.f251.webm
[download] 100% of 3.56MiB in 00:00
[ffmpeg] Merging formats into "Sub Focus - Tidal Wave ft. Alpines-B8vlk1UR99k.mkv"
[debug] ffmpeg command line: ffmpeg -y -i "file:Sub Focus - Tidal Wave ft. Alpines-B8vlk1UR99k.f137.mp4" -i "file:Sub Focus - Tidal Wave ft. Alpines-B8vlk1UR99k.f251.webm" -c copy -map "0:v:0" -map "1:a:0" "file:Sub Focus - Tidal Wave ft. Alpines-B8vlk1UR99k.temp.mkv"
ERROR: file:Sub Focus - Tidal Wave ft. Alpines-B8vlk1UR99k.f137.mp4: No such file or directory
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcuf0d0kb\build\youtube_dl\YoutubeDL.py", line 2032, in post_process
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcuf0d0kb\build\youtube_dl\postprocessor\ffmpeg.py", line 479, in run
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcuf0d0kb\build\youtube_dl\postprocessor\ffmpeg.py", line 204, in run_ffmpeg_multiple_files
youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError: file:Sub Focus - Tidal Wave ft. Alpines-B8vlk1UR99k.f137.mp4: No such file or directory

Der Befehl "list" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
...
<end of log>
```

---

### Description

I'm trying to download a playlist from YouTube (https://www.youtube.com/watch?v=B8vlk1UR99k&list=PLr9smI_szfwmoB6HvBF6uC-ax1XQsm9SV) but it fails.

I don't know why. Normally I don't have any issue using youtube-dl.

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command

**Comment by Spenhouet** [comment]
That was fast. Damn, I just forgot to set quotes around the url.. Sorry for bothering you.
