### ISSUE TITLE
Egghead download issue for one specific free course

### ISSUE THREAD

**Issue by atuttle** [rg3/youtube-dl#14950]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.12.10**
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

```
youtube-dl -o "%(autonumber)s-%(title)s.%(ext)s" https://egghead.io/courses/leverage-new-features-of-react-16 --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-o', u'%(autonumber)s-%(title)s.%(ext)s', u'https://egghead.io/courses/leverage-new-features-of-react-16', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.12.10
[debug] Python version 2.7.10 - Darwin-16.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.8.6, ffprobe 2.8.6
[debug] Proxy map: {}
[egghead:course] leverage-new-features-of-react-16: Downloading course lessons JSON
[egghead:course] leverage-new-features-of-react-16: Downloading course JSON
[download] Downloading playlist: Leverage New Features of React 16
[egghead:course] playlist Leverage New Features of React 16: Collected 6 video ids (downloading 6 of them)
[download] Downloading video 1 of 6
[egghead:lesson] react-error-handling-using-error-boundaries-in-react-16: Downloading JSON metadata
[egghead:lesson] 2464: Downloading m3u8 information
[egghead:lesson] 2464: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
[download] 00001-Error Handling using Error Boundaries in React 16.mp4 has already been downloaded and merged
[download] Downloading video 2 of 6
[egghead:lesson] react-render-multiple-elements-without-a-wrapping-element-in-a-component-in-react-16: Downloading JSON metadata
[egghead:lesson] 2572: Downloading m3u8 information
[egghead:lesson] 2572: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
[download] 00002-Render Multiple Elements without a Wrapping Element in a Component in React 16.mp4 has already been downloaded and merged
[download] Downloading video 3 of 6
[egghead:lesson] react-render-text-only-components-in-react-16: Downloading JSON metadata
ERROR: An extractor error has occurred. (caused by KeyError(u'media_urls',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 437, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/egghead.py", line 97, in _real_extract
    for _, format_url in lesson['media_urls'].items():
KeyError: u'media_urls'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 450, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
ExtractorError: An extractor error has occurred. (caused by KeyError(u'media_urls',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

---

### Description of your *issue*, suggested solution and other information

The downloader seems to work fine on other egghead playlists, but has failed for [this one in particular](https://egghead.io/courses/leverage-new-features-of-react-16) for at least the last two versions of yt-dl.

**Comment by dstftw** [comment]
Videos 3 to 6 are paid ones.
