### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by sergiopoverony** [rg3/youtube-dl#14957]
D:\YouTube>youtube-dl "http://www.youtube.com/watch?v=HqPysxa_v5Y"
[youtube] HqPysxa_v5Y: Downloading webpage
[youtube] HqPysxa_v5Y: Downloading video info webpage
[youtube] HqPysxa_v5Y: Extracting video information
WARNING: unable to extract uploader nickname
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpje2_cfdl\build\youtube_dl\extractor\youtube.py", line 1081, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpje2_cfdl\build\youtube_dl\extractor\youtube.py", line 969, in _extract_signature_function
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vfl4OEYh9/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vfl4OEYh9/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by sergiopoverony** [comment]
need update/ closed
