### ISSUE TITLE
BYU TV

### ISSUE THREAD

**Issue by mfocht** [rg3/youtube-dl#14966]
Ok, a bit of a beginner here.  I ran into an issue when trying to download an episode of Studio C from BYU TV.  Basically, any links from the site aren't recognized as valid links.  This is a reasonably large problem, but it was also fairly easy to solve.  Essentially, in the URL, they changed watch to player.  So I changed that, and links were recognized again.  That's progress.  But, it still spits out the error "ERROR: Unable to extract episode information"  I've narrowed this down to line 38 I believe.  I don't really know how to fix this error, since it seems to be calling another function within common.py at line 2581.  I don't really have the expertise to diagnose this any further.  Hopefully someone else will see this and know what to do.  I'm committing this because regardless of the fact that an error still exists, this fixes one.  I would spend more time on this, but it's nearing 1 am and I have a feeling I'll forget what I was doing when I wake up.  I'll create a issue and reference this pull request as well.  Thanks for the help, Micah.

## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.12.10*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2017.12.10**
This issue was present on 2017.12.10, and after I tested the change, the other one appears.
### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

**BEFORE MY CHANGE:**

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.byutv.org/player/a1199bd3-0012-4ca0-9ea1-fc0d21979127', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.12.10
[debug] Python version 2.7.12 - Linux-4.10.0-42-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1
[debug] Proxy map: {}
[generic] a1199bd3-0012-4ca0-9ea1-fc0d21979127: Requesting header
WARNING: Falling back on generic information extractor.
[generic] a1199bd3-0012-4ca0-9ea1-fc0d21979127: Downloading webpage
[generic] a1199bd3-0012-4ca0-9ea1-fc0d21979127: Extracting information
ERROR: Unsupported URL: https://www.byutv.org/player/a1199bd3-0012-4ca0-9ea1-fc0d21979127
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2163, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2539, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2528, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 1, column 733
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 437, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3063, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.byutv.org/player/a1199bd3-0012-4ca0-9ea1-fc0d21979127
```
**AFTER MY CHANGE:**
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.byutv.org/player/a1199bd3-0012-4ca0-9ea1-fc0d21979127', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.12.10
[debug] Git HEAD: 1596025
[debug] Python version 2.7.12 - Linux-4.10.0-42-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1
[debug] Proxy map: {}
[BYUtv] a1199bd3-0012-4ca0-9ea1-fc0d21979127: Downloading webpage
ERROR: Unable to extract episode information; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/plexmedia/Files/youtube-dl/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "/plexmedia/Files/youtube-dl/youtube_dl/extractor/common.py", line 437, in extract
    ie_result = self._real_extract(url)
  File "/plexmedia/Files/youtube-dl/youtube_dl/extractor/byutv.py", line 38, in _real_extract
    r'(?s)episode:(.*?\}),\s*\n', webpage, 'episode information')
  File "/plexmedia/Files/youtube-dl/youtube_dl/extractor/common.py", line 792, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract episode information; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
...
<end of log>
```

**Comment by mfocht** [comment]
[I created a pull request with my half fix here.  ](https://github.com/rg3/youtube-dl/pull/14967)
