### ISSUE TITLE
ERROR: Did not get any data blocks

### ISSUE THREAD

**Issue by ParsaFakhar** [rg3/youtube-dl#14968]
youtube-dl -v -f mp4 --write-sub --sub-lang en --write-auto-sub --sub-format ttml --convert-subtitles srt --embed-subs https://www.youtube.com/watch\?v\=mBXGjD5ASrQ

what's wrong?!!

[download]   0.6% of 37.67MiB at 612.90KiB/s ETA 01:02[download] Got server HTTP error: Downloaded 251081 bytes, expected 39498228 bytes. Retrying (attempt 1 of 10)...
[download] Resuming download at byte 251081

ERROR: Did not get any data blocks
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 287, in real_download
    download()
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 265, in download
    retry(err)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 175, in retry
    raise RetryDownload(e)
RetryDownload

**Comment by yan12125** [comment]
See https://github.com/rg3/youtube-dl/issues/14733#issuecomment-344290335
