### ISSUE TITLE
youtube-dl wrongly reports no xattr support, throws error, interrupts playlist download

### ISSUE THREAD

**Issue by NickSto** [rg3/youtube-dl#14971]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.12.10*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.12.10**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

While downloading videos from a playlist using the `--xattrs` option, I ran into an issue where a video is properly filtered out by `--max-filesize`, but youtube-dl also throws an error saying extended attributes aren't supported (incorrect), and exits in the middle of the playlist.

Here's the command I ran:
`$ youtube-dl --no-mtime --xattrs --playlist-reverse --max-filesize 500m -f 22 -o '%(playlist_index)s - %(title)s [src %(uploader_id)s] [posted %(upload_date)s] [id %(id)s].%(ext)s' https://www.youtube.com/user/pbsideachannel`
And the log messages for the video where it threw the error:
```
[download] Downloading video 318 of 367
[youtube] zPDgEUAowPA: Downloading webpage
[youtube] zPDgEUAowPA: Downloading video info webpage
[youtube] zPDgEUAowPA: Extracting video information
[youtube] zPDgEUAowPA: Downloading MPD manifest
[download] File is larger than max-filesize (5568799069 bytes > 524288000 bytes). Aborting.
[metadata] Writing metadata to file's xattrs
ERROR: This filesystem doesn't support extended attributes. (You may have to enable them in your /etc/fstab)
```

If I remove the `--xattrs` option from the command, the download continues fine, minus that `ERROR` line.

It seems to have the same underlying cause as #5589. If the underlying cause can't be fixed, it could probably be worked around with a similar solution, turning it into a warning, not an error.

#### Technical details

This is repeatable, and the same log messages are printed when you try it on the single video:
`$ youtube-dl --max-filesize 500m -f 22 --xattrs 'https://www.youtube.com/watch?v=zPDgEUAowPA'`
vs
`$ youtube-dl --max-filesize 500m -f 22 'https://www.youtube.com/watch?v=zPDgEUAowPA'`

I know that extended attributes are actually supported on the filesystem, since they were written to other videos in the playlist (examined with the `attr` command).

All the same, this is the line in `/etc/fstab` for one of the drives it occurred on:
`/dev/mapper/ubuntu--vg-root / ext4 discard,noatime,nodiratime,errors=remount-ro 0 1`
I'm on Ubuntu 16.04.3, 64-bit, and the drives in question (it happened on multiple) are all ext4-formatted.
Just in case it matters, all the drives are full-disk encrypted. One (the one whose fstab line is shown) is using the standard Ubuntu dm-crypt/cryptsetup/LUKS, and the other uses VeraCrypt (in TrueCrypt compatibility mode).

Here's the verbose version of the single-video command:
```
$ youtube-dl -v --max-filesize 500m -f 22 --xattrs 'https://www.youtube.com/watch?v=zPDgEUAowPA'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--max-filesize', '500m', '-f', '22', '--xattrs', 'https://www.youtube.com/watch?v=zPDgEUAowPA']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.12.10
[debug] Python version 3.5.2 - Linux-4.10.0-42-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1
[debug] Proxy map: {}
[youtube] zPDgEUAowPA: Downloading webpage
[youtube] zPDgEUAowPA: Downloading video info webpage
[youtube] zPDgEUAowPA: Extracting video information
[youtube] zPDgEUAowPA: Downloading MPD manifest
[debug] Invoking downloader on 'https://r2---sn-n4v7knls.googlevideo.com/videoplayback?pl=22&source=youtube&expire=1513183512&dur=39631.772&mv=m&mt=1513161820&ms=au&mn=sn-n4v7knls&mm=31&ratebypass=yes&mime=video%2Fmp4&key=yt6&lmt=1486024775920876&requiressl=yes&initcwndbps=1561250&itag=22&ei=uAQxWo52zbn6A5aMqegG&id=o-AIzBRuAh2a8OMn1vm2g14y88yMQlatBctUNLq7T4YjXe&sparams=dur%2Cei%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&signature=369E8F050EA510D65E8125676873436916AC340B.E1ADD4E39DDA8AE5F584D280AA06FD79C25B6C93&ipbits=0&ip=67.174.242.16'
[download] File is larger than max-filesize (5568799069 bytes > 524288000 bytes). Aborting.
[metadata] Writing metadata to file's xattrs
ERROR: This filesystem doesn't support extended attributes. (You may have to enable them in your /etc/fstab)
Traceback (most recent call last):
  File "/home/me/.local/lib/python3.5/site-packages/youtube_dl/utils.py", line 3760, in write_xattr
    import xattr
ImportError: No module named 'xattr'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/me/.local/lib/python3.5/site-packages/youtube_dl/postprocessor/xattrpp.py", line 54, in run
    write_xattr(filename, xattrname, byte_value)
  File "/home/me/.local/lib/python3.5/site-packages/youtube_dl/utils.py", line 3823, in write_xattr
    raise XAttrMetadataError(p.returncode, stderr)
youtube_dl.utils.XAttrMetadataError: setfattr: The Bee Movie But Every Time They Say Bee We Explain The Deal With Bee Movie-zPDgEUAowPA.mp4: No such file or directory



```

**Comment by NickSto** [comment]
That was quick, thanks!
