### ISSUE TITLE
Add support for zapp.nl

### ISSUE THREAD

**Issue by ArchCarrier** [rg3/youtube-dl#14987]
### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

[debug] System config: []
[debug] User config: ['--ignore-errors']
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.zapp.nl/1803-skelterlab/instructie-video-s/740-instructievideo-s/POMS_AT_11736927']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.12.14
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-87353-g183fd30, ffprobe N-87353-g183fd30, rtmpdump 2.4
[debug] Proxy map: {}
[npo] 740-instructievideo-s: Downloading JSON metadata
ERROR: An extractor error has occurred. (caused by KeyError('titel',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpekokknty\build\youtube_dl\extractor\common.py", line 437, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpekokknty\build\youtube_dl\extractor\npo.py", line 163, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpekokknty\build\youtube_dl\extractor\npo.py", line 180, in _get_info
KeyError: 'titel'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpekokknty\build\youtube_dl\extractor\common.py", line 437, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpekokknty\build\youtube_dl\extractor\npo.py", line 163, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpekokknty\build\youtube_dl\extractor\npo.py", line 180, in _get_info
KeyError: 'titel'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpekokknty\build\youtube_dl\YoutubeDL.py", line 784, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpekokknty\build\youtube_dl\extractor\common.py", line 450, in extractyoutube_dl.utils.
ExtractorError: An extractor error has occurred. (caused by Key Error('titel',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.zapp.nl/1803-skelterlab/instructie-video-s/740-instructievideo-s/POMS_AT_11736927

### Remark ###
The site uses the same infrastructure as npo.nl, so I suspect the same extractor can be used.

**Comment by helb** [comment]
Zapp.nl is actually [already supported](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/npo.py#L41) by npo.nl extractor. They probably just changed the URL structure and broke it. Seems to be an easy fix, i'll give it a try and create a PR.
