### ISSUE TITLE
abcnews.go.com not downloading video

### ISSUE THREAD

**Issue by sant527** [rg3/youtube-dl#14998]
$ youtube-dl --version
2017.12.14

$ youtube-dl -v "http://abcnews.go.com/US/snow-cold-continue-midwest-northeast/story?id=51785886"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://abcnews.go.com/US/snow-cold-continue-midwest-northeast/story?id=51785886']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.12.14
[debug] Python version 3.6.0 - Linux-4.10.2-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 3.2.4, ffprobe 3.2.4, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[abcnews] 51785886: Downloading webpage
[abcnews:video] Downloading Akamai AMP feed
[abcnews:video] 51786251: Downloading f4m manifest
[abcnews:video] 51786251: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://abcvod.abcnews.com/z/abcnews/2017/12/171214_gma_pilgrim_0711_,500,800,1200,1800,2500,3200,4500,.mp4.csmil/manifest.f4m?hdcore=3.4.0&plugin=aasp-3.4.0.132.124'
[f4m] Downloading f4m manifest
ERROR: unable to download video data: HTTP Error 504: Gateway Timeout
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 1893, in process_info
    success = dl(filename, info_dict)
  File "/usr/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 1832, in dl
    return fd.download(name, info)
  File "/usr/lib/python3.6/site-packages/youtube_dl/downloader/common.py", line 361, in download
    return self.real_download(filename, info_dict)
  File "/usr/lib/python3.6/site-packages/youtube_dl/downloader/f4m.py", line 324, in real_download
    urlh = self.ydl.urlopen(self._prepare_url(info_dict, man_url))
  File "/usr/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 2196, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 504: Gateway Timeout

**Comment by helb** [comment]
Works for me. The `504: Gateway Timeout` error sounds like ABC News had some temporary server issues.

**Comment by sant527** [comment]
Its really slow. Is this has to do something with geo location. I am from india
