### ISSUE TITLE
ValueError: Invalid IPv6 URL

### ISSUE THREAD

**Issue by UHFT** [rg3/youtube-dl#15019]
I'm using latest version and have the following issue to download afreecatv video.

$ youtube-dl -v http://vod.afreecatv.com/PLAYER/STATION/28725990
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://vod.afreecatv.com/PLAYER/STATION/28725990']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.12.14
[debug] Python version 3.6.3 - Darwin-17.3.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.4.1, ffprobe 3.4.1
[debug] Proxy map: {}
[afreecatv] 28725990: Downloading XML
[afreecatv] 28725990: Downloading part 1 m3u8 information
Traceback (most recent call last):
  File "/Users/insuyu/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/insuyu/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 465, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 455, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1986, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 784, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 437, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/afreecatv.py", line 234, in _real_extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1343, in _extract_m3u8_formats
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1455, in _parse_m3u8_formats
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1359, in <lambda>
  File "/Users/insuyu/anaconda3/lib/python3.6/urllib/parse.py", line 490, in urljoin
    urlparse(url, bscheme, allow_fragments)
  File "/Users/insuyu/anaconda3/lib/python3.6/urllib/parse.py", line 366, in urlparse
    splitresult = urlsplit(url, scheme, allow_fragments)
  File "/Users/insuyu/anaconda3/lib/python3.6/urllib/parse.py", line 439, in urlsplit
    raise ValueError("Invalid IPv6 URL")
ValueError: Invalid IPv6 URL
$ 

how to resolve ValueError: Invalid IPv6 URL issue ?

**Comment by dstftw** [comment]
Post the output with `--dump-pages`.

**Comment by UHFT** [comment]
The debug file is over 700MB. It does not allow to upload such a big file.

**Comment by UHFT** [comment]
Tested with another video which is only 1 min 30 seconds (35MB in dump file)


$ youtube-dl -v --dump-pages http://vod.afreecatv.com/PLAYER/STATION/28927142 > out.txt
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--dump-pages', 'http://vod.afreecatv.com/PLAYER/STATION/28927142']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.12.14
[debug] Python version 3.6.3 - Darwin-17.3.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.4.1, ffprobe 3.4.1
[debug] Proxy map: {}
Traceback (most recent call last):
  File "/Users/insuyu/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/insuyu/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 465, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 455, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1986, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 784, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 437, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/afreecatv.py", line 234, in _real_extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1343, in _extract_m3u8_formats
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1455, in _parse_m3u8_formats
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1359, in <lambda>
  File "/Users/insuyu/anaconda3/lib/python3.6/urllib/parse.py", line 490, in urljoin
    urlparse(url, bscheme, allow_fragments)
  File "/Users/insuyu/anaconda3/lib/python3.6/urllib/parse.py", line 366, in urlparse
    splitresult = urlsplit(url, scheme, allow_fragments)
  File "/Users/insuyu/anaconda3/lib/python3.6/urllib/parse.py", line 439, in urlsplit
    raise ValueError("Invalid IPv6 URL")
ValueError: Invalid IPv6 URL
 

[289.txt.zip](https://github.com/rg3/youtube-dl/files/1566179/289.txt.zip)

**Comment by UHFT** [comment]
any progress ?
