### ISSUE TITLE
ERROR: av_interleaved_write_frame(): Invalid argument

### ISSUE THREAD

**Issue by habi** [rg3/youtube-dl#15010]
## Please follow the guide below

- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.12.14**
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)

```
$ youtube-dl -v https://www.srf.ch/play/tv/dok/video
/liebesnoete-in-japan?id=3074e619-8774-4cf1-bd6d-22ed38320096&station=69e8ac16-
4327-4af4-b873-fd5cd6e895a7
[1] 3516
$ [debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.srf.ch/play/tv/dok/video/liebesnoete-in-japan?id=3074e619-8774-4cf1-bd6d-22ed38320096']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.12.14
[debug] Python version 2.7.10 - Darwin-16.7.0-x86_64-i386-64bit
[debug] exe versions: avconv 12.1, avprobe 12.1, ffmpeg 3.3.3, ffprobe 3.3.3, rtmpdump 2.4
[debug] Proxy map: {}
[SRGSSR] 3074e619-8774-4cf1-bd6d-22ed38320096: Downloading JSON metadata
[SRGSSR] 3074e619-8774-4cf1-bd6d-22ed38320096: Downloading HTTP-HDS-HD token
[SRGSSR] 3074e619-8774-4cf1-bd6d-22ed38320096: Downloading f4m manifest
[SRGSSR] 3074e619-8774-4cf1-bd6d-22ed38320096: Downloading HTTP-HDS-SD token
[SRGSSR] 3074e619-8774-4cf1-bd6d-22ed38320096: Downloading f4m manifest
[SRGSSR] 3074e619-8774-4cf1-bd6d-22ed38320096: Downloading HTTP-HLS-SD token
[SRGSSR] 3074e619-8774-4cf1-bd6d-22ed38320096: Downloading m3u8 information
[SRGSSR] 3074e619-8774-4cf1-bd6d-22ed38320096: Downloading HTTP-HLS-HD token
[SRGSSR] 3074e619-8774-4cf1-bd6d-22ed38320096: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://srfvodhd-vh.akamaihd.net/i/vod/dok/2017/11/dok_20171122_230019_7839257_v_webcast_h264_,q40,q10,q20,q30,q50,q60,.mp4.csmil/index_5_av.m3u8?null=0'
[download] Liebesnöte in Japan-3074e619-8774-4cf1-bd6d-22ed38320096.mp4 has already been downloaded
[download] 100% of 1.34GiB
[debug] avconv command line: avprobe -show_streams 'file:Liebesnöte in Japan-3074e619-8774-4cf1-bd6d-22ed38320096.mp4'
[ffmpeg] Fixing malformed AAC bitstream in "Liebesnöte in Japan-3074e619-8774-4cf1-bd6d-22ed38320096.mp4"
[debug] ffmpeg command line: avconv -y -i 'file:Liebesnöte in Japan-3074e619-8774-4cf1-bd6d-22ed38320096.mp4' -c copy -f mp4 '-bsf:a' aac_adtstoasc 'file:Liebesnöte in Japan-3074e619-8774-4cf1-bd6d-22ed38320096.temp.mp4'
ERROR: av_interleaved_write_frame(): Invalid argument
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2032, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 546, in run
    self.run_ffmpeg(filename, temp_filename, options)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 208, in run_ffmpeg
    self.run_ffmpeg_multiple_files([path], out_path, opts)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 204, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
FFmpegPostProcessorError: av_interleaved_write_frame(): Invalid argument
```
### Description of your *issue*, suggested solution and other information

I often try to download Documentations from the Swiss National TV for offline consumptions (as given in the command above).
This used to work nicely, but today I noticed the error given in the title of this issue
The video seems to be downloaded correctly (Liebesnöte in Japan-3074e619-8774-4cf1-bd6d-22ed38320096.mp4 with a size of 1.44 GB), but there's an additional file on my disk which wasn't there with using `youtube-dl`before (Liebesnöte in Japan-3074e619-8774-4cf1-bd6d-22ed38320096.temp.mp4, 601 *Bytes*).

**Comment by dstftw** [comment]
avconv issue. Update or use ffmpeg.

**Comment by habi** [comment]
Thanks a lot for the hint, which solved my problem.

For future reference (I'm on OS X, also forgot to mention that), I upgraded `avconv` with [Homebrew](https://brew.sh) by issuing
```
brew upgrade libav
```
in the terminal.
Now the error mentioned in this issue is gone.
