### ISSUE TITLE
Openload.co Error - PhantomJS not found

### ISSUE THREAD

**Issue by devingDev** [rg3/youtube-dl#15069]
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2017.12.23**
- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-g', 'https://openload.co/f/HIDDENVIDEOEID']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.12.23
[debug] Python version 3.4.4 - Windows-10-10.0.15063
[debug] exe versions: none
[debug] Proxy map: {}
ERROR: PhantomJS executable not found in PATH, download it from http://phantomjs.org
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp27__tkx0\build\youtube_dl\YoutubeDL.py", line 784, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp27__tkx0\build\youtube_dl\extractor\common.py", line 438, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp27__tkx0\build\youtube_dl\extractor\openload.py", line 314, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp27__tkx0\build\youtube_dl\extractor\openload.py", line 119, in __init__
youtube_dl.utils.ExtractorError: PhantomJS executable not found in PATH, download it from http://phantomjs.org

Exception ignored in: <bound method PhantomJSwrapper.__del__ of <youtube_dl.extractor.openload.PhantomJSwrapper object at 0x04A635B0>>
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp27__tkx0\build\youtube_dl\extractor\openload.py", line 142, in __del__
AttributeError: 'PhantomJSwrapper' object has no attribute '_TMP_FILES'
<end of log>
```

I have the newest youtube-dl and tested it with openload.co video, but it keeps throwing this error. I thought this works without additional installs. Do I have to install PhantomJS now on every pc i want to use it?

**Comment by Hrxn** [comment]
Yes, you have to use the PhantomJS binary file (`phantomjs.exe`) along with `youtube-dl.exe` (on Windows), but no need to "install" anything.

**Comment by devingDev** [comment]
Ah I see, I didn't see that part anywhere so I assumed it does not need any other executables or apps. Thanks
