### ISSUE TITLE
Support request for knowledgekids.ca

### ISSUE THREAD

**Issue by RyanVoProductions** [rg3/youtube-dl#15091]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.12.23*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.12.23**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl -v http://www.knowledgekids.ca/videos/shutterbugs/bugathon-wind-blows-s1-e1
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://www.knowledgekids.ca/videos/shutterbugs/bugathon-wind-blows-s1-e1']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.12.23
[debug] Python version 3.4.4 - Windows-10-10.0.16299
[debug] exe versions: ffmpeg 3.3.4, ffprobe 3.3.4, rtmpdump 2.4
[debug] Proxy map: {}
[generic] bugathon-wind-blows-s1-e1: Requesting header
WARNING: Falling back on generic information extractor.
[generic] bugathon-wind-blows-s1-e1: Downloading webpage
[generic] bugathon-wind-blows-s1-e1: Extracting information
ERROR: Unsupported URL: http://www.knowledgekids.ca/videos/shutterbugs/bugathon-wind-blows-s1-e1
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp27__tkx0\build\youtube_dl\YoutubeDL.py", line 784, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp27__tkx0\build\youtube_dl\extractor\common.py", line 438, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp27__tkx0\build\youtube_dl\extractor\generic.py", line 3063, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.knowledgekids.ca/videos/shutterbugs/bugathon-wind-blows-s1-e1
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://www.knowledgekids.ca/videos/shutterbugs/bugathon-wind-blows-s1-e1

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

**Comment by RyanVoProductions** [comment]
@dstftw Are you still working on this? The video players are powered by JW Player.

And it's also easy to get m3u8 links: http://videos-f.jwpsrv.com/content/conversions/D6IiMaB8/videos/CCWa8rsI-23509834.mp4.m3u8?token=0_5a90d2e6_0x7a08479bd393cfc7d9d7c2bfac94c0c13bbdaf68

**Comment by dstftw** [comment]
Not working on this.
