### ISSUE TITLE
error -6004:客户端无权播放,201

### ISSUE THREAD

**Issue by wfyoutubedl** [rg3/youtube-dl#15098]
when try text a video from youku(www.youku.com);error -6004:客户端无权播放,201;

**Comment by yan12125** [comment]
This is fixed in git-master and will be included in the next version.

**Comment by WeiqiChenCN** [comment]
```
D:\天狼>youtube-dl --verbose http://v.youku.com/v_show/id_XMTYyMzQ3NzQwNA==.html?spm=a2h0k.8191407.0.0&from=s1.8-1-1.2
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'http://v.youku.com/v_show/id_XMTYyMzQ3NzQwNA==.html?spm=a2h0k.8191407.0.0']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2018.03.20
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.16299
[debug] exe versions: none
[debug] Proxy map: {}
[youku] XMTYyMzQ3NzQwNA: Retrieving cna info
[youku] XMTYyMzQ3NzQwNA: Downloading JSON metadata
ERROR: Youku server reported error -6004: 客户端无权播放,201; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpbt_jbnlh\build\youtube_dl\YoutubeDL.py", line 785, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpbt_jbnlh\build\youtube_dl\extractor\common.py", line 440, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpbt_jbnlh\build\youtube_dl\extractor\youku.py", line 189, in _real_extract
youtube_dl.utils.ExtractorError: Youku server reported error -6004: 客户端无权播放,201; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

'from' is not recognized as an internal or external command,
operable program or batch file.

D:\天狼>youtube-dl --version
2018.03.20
```

**Comment by yan12125** [comment]
> It's seem that youku changes something..

Yes you're right. Please move to https://github.com/rg3/youtube-dl/issues/14932 for further discussions.
