### ISSUE TITLE
Unable to download videos from Hotstar

### ISSUE THREAD

**Issue by rajucomp** [rg3/youtube-dl#15107]
I can play the videos fine in Google Chrome but I am unable to download the videos through. Here is the log.  The proxy is not an issue here. I am using the same to play them in my browser.
youtube-dl.exe --verbose http://www.hotstar.com/movies/ishq/1000104631/watch  
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'http://www.hotstar.com/movies/ishq/1000104631/watch']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.12.28
[debug] Python version 3.4.4 - Windows-10-10.0.15063
[debug] exe versions: ffmpeg N-88193-g5834cba05e, ffprobe N-88193-g5834cba05e
[debug] Proxy map: {'http': 'http://172.29.58.90:8080', 'https': 'https://172.29.58.90:8080', 'ftp': 'ftp://172.29.58.90:8080'}
[debug] Using fake IP 117.232.133.164 (IN) as X-Forwarded-For.
[HotStar] 1000104631: Downloading JSON metadata
[HotStar] 1000104631: Downloading JIO JSON metadata
WARNING: Unable to download JSON metadata: HTTP Error 403: URLBlocked
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpheifp6ll\build\youtube_dl\__init__.py", line 465, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpheifp6ll\build\youtube_dl\__init__.py", line 455, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpheifp6ll\build\youtube_dl\YoutubeDL.py", line 1988, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpheifp6ll\build\youtube_dl\YoutubeDL.py", line 784, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpheifp6ll\build\youtube_dl\extractor\common.py", line 438, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpheifp6ll\build\youtube_dl\extractor\hotstar.py", line 82, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpheifp6ll\build\youtube_dl\extractor\hotstar.py", line 20, in _download_json
TypeError: 'NoneType' object is not subscriptable`

**Comment by remitamine** [comment]
try without a proxy:
```
youtube-dl http://www.hotstar.com/movies/ishq/1000104631/watch
[HotStar] 1000104631: Downloading JSON metadata
[HotStar] 1000104631: Downloading JIO JSON metadata
[HotStar] 1000104631: Downloading m3u8 information
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 1562
[download] Destination: _-1000104631.mp4
[download]   0.0% of ~2.49GiB at 100.68KiB/s ETA 09:06:20
```

**Comment by adeen-s** [comment]
The error is not in youtube-dl but it seems that your ISP or the proxy has blocked access to Hotstar.

>WARNING: Unable to download JSON metadata: HTTP Error 403: URLBlocked

**Comment by rajucomp** [comment]
I can't access the internet without a proxy. I don't think the proxy has blocked access to Hotstar because I can stream the same video in Chrome using the same proxy.

**Comment by rajucomp** [comment]
Never mind. Hotstar blocks access if it detects that we are using a vpn or a proxy. But I still can't figure out how the videos can play in the browser then.
