### ISSUE TITLE
support for   http://money.cnn.com/2017/12/29/*

### ISSUE THREAD

**Issue by sant527** [rg3/youtube-dl#15110]
$ youtube-dl --version
2017.12.14

$ youtube-dl --verbose "http://money.cnn.com/2017/12/29/technology/reliance-communications-jio-telecom-deal/index.html"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'http://money.cnn.com/2017/12/29/technology/reliance-communications-jio-telecom-deal/index.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.12.14
[debug] Python version 3.6.0 - Linux-4.10.2-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 3.2.4, ffprobe 3.2.4, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] index: Requesting header
WARNING: Falling back on generic information extractor.
[generic] index: Downloading webpage
[generic] index: Extracting information
ERROR: Unsupported URL: http://money.cnn.com/2017/12/29/technology/reliance-communications-jio-telecom-deal/index.html
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 437, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/generic.py", line 3063, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: http://money.cnn.com/2017/12/29/technology/reliance-communications-jio-telecom-deal/index.html

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/12972

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/12972
