### ISSUE TITLE
crash when downloading from udemy

### ISSUE THREAD

**Issue by imphat** [rg3/youtube-dl#15134]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.12.31*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.12.31**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--proxy', u'http://localhost:3128', u'-o', u'%(autonumber)02d - %(title)s.%(ext)s', u'--username', u'PRIVATE', u'--password', u'PRIVATE', u'https://www.udemy.com/understand-nodejs/learn/v4/content', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.12.31
[debug] Python version 2.7.14 - Linux-4.13.0-21-generic-x86_64-with-Ubuntu-17.10-artful
[debug] exe versions: ffmpeg 3.3.4-2, ffprobe 3.3.4-2, rtmpdump 2.4
[debug] Proxy map: {u'http': u'http://localhost:3128', u'https': u'http://localhost:3128'}
[udemy:course] Downloading login popup
[udemy:course] Logging in
[udemy:course] understand-nodejs: Downloading webpage
[udemy:course] 461160: Downloading course curriculum
[download] Downloading playlist: Learn and Understand NodeJS
[udemy:course] playlist Learn and Understand NodeJS: Collected 93 video ids (downloading 93 of them)
[download] Downloading video 1 of 93
[udemy] Downloading login popup
[udemy] 3452978: Downloading webpage
[udemy] 3452978: Downloading lecture JSON
[udemy] 4113756: Downloading m3u8 information
ERROR: An extractor error has occurred. (caused by KeyError('_Request__r_host',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 438, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/udemy.py", line 340, in _real_extract
    extract_formats(data.get('sources'))
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/udemy.py", line 263, in extract_formats
    m3u8_id='hls', fatal=False))
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1335, in _extract_m3u8_formats
    fatal=fatal)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 537, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 517, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2198, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1088, in https_open
    req, **kwargs)
  File "/usr/lib/python2.7/urllib2.py", line 1195, in do_open
    h.request(req.get_method(), req.get_selector(), req.data, headers)
  File "/usr/lib/python2.7/urllib2.py", line 294, in get_selector
    return self.__r_host
  File "/usr/lib/python2.7/urllib2.py", line 253, in __getattr__
    return self.__dict__[attr]
KeyError: '_Request__r_host'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 451, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
ExtractorError: An extractor error has occurred. (caused by KeyError('_Request__r_host',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Udemy Course content: https://www.udemy.com/understand-nodejs/learn/v4/content

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information
downloads from udemy are breaking on retries and resumes.

**Comment by imphat** [comment]
@dstftw , sorry buy I couldn´t find another issue regarding the same matter. Can you please link it here?

**Comment by imphat** [comment]
it seems to be a problem when using python 2.7 in ubuntu (17.10). `python3 `which youtube-dl`` seems to fix the problem caused by the bad m3u8 parsing.
