### ISSUE TITLE
Pornhub - can't download playlist

### ISSUE THREAD

**Issue by stepkinn** [rg3/youtube-dl#15148]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.12.31*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2017.12.31**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

youtube-dl -v https://fr.pornhub.com/playlist/35170711
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://fr.pornhub.com/playlist/35170711']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.12.31
[debug] Python version 2.7.9 - Linux-4.9.35-v7+-armv7l-with-debian-8.0
[debug] exe versions: none
[debug] Proxy map: {}
[generic] 35170711: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 35170711: Downloading webpage
[generic] 35170711: Extracting information
[download] Downloading playlist: FFM FFFM F+.../M - Liste de Lecture de VidÃ©os Pornos Ishouldknow | Pornhub.com
[generic] playlist FFM FFFM F+.../M - Liste de Lecture de VidÃ©os Pornos Ishouldknow | Pornhub.com: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on u'data:"+o+";base64,"+E+"'
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 465, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 455, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1988, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 795, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 994, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 849, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1622, in process_video_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1895, in process_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1834, in dl
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 361, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 286, in real_download
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 74, in establish_connection
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2198, in urlopen
  File "/usr/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2473, in data_open
binascii.Error: Incorrect padding

---
Examples :
- Playlist: https://fr.pornhub.com/playlist/38516402
- Playlist : https://fr.pornhub.com/playlist/35170711
---

I can't download playlist on Pornhub. I have tested already in Youporn and same result.
Same result with all playlist.
I have seen another issue closed with the same problem here but no information into it.

**Comment by Hrxn** [comment]
What about `https://www.pornhub.com/playlist/xxxxxxxx`? (i.e. no `fr.`)

**Comment by stepkinn** [comment]
Oh yeah ! It's ok now.
Thanks Hrxn for reactivity.
