### ISSUE TITLE
Support for ulozto.net

### ISSUE THREAD

**Issue by sale2000** [rg3/youtube-dl#15178]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.12.31*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ X] I've **verified** and **I assure** that I'm running youtube-dl **2017.12.31**

### Before submitting an *issue* make sure you have:
- [X ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?

- [X] Site support request (request for adding support for a new site)

```
youtube-dl -v https://ulozto.net/\!0RY7XoUyjoD0/riding-news-1-3-ski-freestyle-freeride-extreme
[debug] System config: []
[debug] User config: [u'-o', u'./%(title)s.%(ext)s', u'--max-downloads=5', u'--restrict-filenames']
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://ulozto.net/!0RY7XoUyjoD0/riding-news-1-3-ski-freestyle-freeride-extreme']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.12.31
[debug] Python version 2.7.12 - Linux-4.4.0-02-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg N-87177-g69e6877de8-static, ffprobe N-87177-g69e6877de8-static, rtmpdump 2.4
[debug] Proxy map: {}
[generic] riding-news-1-3-ski-freestyle-freeride-extreme: Requesting header
WARNING: Falling back on generic information extractor.
[generic] riding-news-1-3-ski-freestyle-freeride-extreme: Downloading webpage
[generic] riding-news-1-3-ski-freestyle-freeride-extreme: Extracting information
ERROR: Unsupported URL: https://ulozto.net/!0RY7XoUyjoD0/riding-news-1-3-ski-freestyle-freeride-extreme
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2176, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2539, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2528, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: syntax error: line 1, column 0
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 438, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3086, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://ulozto.net/!0RY7XoUyjoD0/riding-news-1-3-ski-freestyle-freeride-extreme



...
<end of log>
```

---

- Single video: https://ulozto.net/\!0RY7XoUyjoD0/riding-news-1-3-ski-freestyle-freeride-extreme

**Comment by dstftw** [comment]
There is no video on this page.
