### ISSUE TITLE
[YouTube] Unable to authenticate with enabled TFA

### ISSUE THREAD

**Issue by fixator10** [rg3/youtube-dl#15184]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.12.31*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.12.31**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: ['-x', '--audio-format', 'mp3', '--audio-quality', '0']
[debug] Custom config: []
[debug] Command-line args: ['-n', '-v', 'https://www.youtube.com/watch?v=tM8x5Zhe5O0']
[debug] Encodings: locale cp1251, fs utf-8, out utf-8, pref cp1251
[debug] youtube-dl version 2017.12.31
[debug] Python version 3.6.3 - Windows-10-10.0.16299-SP0
[debug] exe versions: ffmpeg N-88355-g05beee44c6, ffprobe N-88355-g05beee44c6
[debug] Proxy map: {}
[youtube] Downloading login page
[youtube] Looking up account info
[youtube] Logging in
Type 2-step verification code and press [Return]:
[youtube] Submitting TFA code
WARNING: Unable to submit TFA code: HTTP Error 400: Bad Request
WARNING: Unable to extract CheckCookie URL
[youtube] tM8x5Zhe5O0: Downloading webpage
[youtube] tM8x5Zhe5O0: Downloading video info webpage
ERROR: tM8x5Zhe5O0: YouTube said: Please sign in to view this video.
Traceback (most recent call last):
  File "d:\program files\python36-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "d:\program files\python36-32\lib\site-packages\youtube_dl\extractor\common.py", line 438, in extract
    ie_result = self._real_extract(url)
  File "d:\program files\python36-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1609, in _real_extract
    expected=True, video_id=video_id)
youtube_dl.utils.ExtractorError: tM8x5Zhe5O0: YouTube said: Please sign in to view this video.
```

```
[debug] System config: []
[debug] User config: ['-x', '--audio-format', 'mp3', '--audio-quality', '0']
[debug] Custom config: []
[debug] Command-line args: ['-u', 'PRIVATE', '-p', 'PRIVATE', '-v', 'https://www.youtube.com/watch?v=tM8x5Zhe5O0']
[debug] Encodings: locale cp1251, fs utf-8, out utf-8, pref cp1251
[debug] youtube-dl version 2017.12.31
[debug] Python version 3.6.3 - Windows-10-10.0.16299-SP0
[debug] exe versions: ffmpeg N-88355-g05beee44c6, ffprobe N-88355-g05beee44c6
[debug] Proxy map: {}
[youtube] Downloading login page
[youtube] Looking up account info
[youtube] Logging in
Type 2-step verification code and press [Return]:
[youtube] Submitting TFA code
WARNING: Unable to submit TFA code: HTTP Error 400: Bad Request
WARNING: Unable to extract CheckCookie URL
[youtube] tM8x5Zhe5O0: Downloading webpage
[youtube] tM8x5Zhe5O0: Downloading video info webpage
ERROR: tM8x5Zhe5O0: YouTube said: Please sign in to view this video.
Traceback (most recent call last):
  File "d:\program files\python36-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "d:\program files\python36-32\lib\site-packages\youtube_dl\extractor\common.py", line 438, in extract
    ie_result = self._real_extract(url)
  File "d:\program files\python36-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1609, in _real_extract
    expected=True, video_id=video_id)
youtube_dl.utils.ExtractorError: tM8x5Zhe5O0: YouTube said: Please sign in to view this video.
```
```
[debug] System config: []
[debug] User config: ['-x', '--audio-format', 'mp3', '--audio-quality', '0']
[debug] Custom config: []
[debug] Command-line args: ['-u', 'PRIVATE', '-p', 'PRIVATE', '-2', '123456', '-v', 'https://www.youtube.com/watch?v=tM8x5Zhe5O0']
[debug] Encodings: locale cp1251, fs utf-8, out utf-8, pref cp1251
[debug] youtube-dl version 2017.12.31
[debug] Python version 3.6.3 - Windows-10-10.0.16299-SP0
[debug] exe versions: ffmpeg N-88355-g05beee44c6, ffprobe N-88355-g05beee44c6
[debug] Proxy map: {}
[youtube] Downloading login page
[youtube] Looking up account info
[youtube] Logging in
[youtube] Submitting TFA code
WARNING: Unable to submit TFA code: HTTP Error 400: Bad Request
WARNING: Unable to extract CheckCookie URL
[youtube] tM8x5Zhe5O0: Downloading webpage
[youtube] tM8x5Zhe5O0: Downloading video info webpage
ERROR: tM8x5Zhe5O0: YouTube said: Please sign in to view this video.
Traceback (most recent call last):
  File "d:\program files\python36-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "d:\program files\python36-32\lib\site-packages\youtube_dl\extractor\common.py", line 438, in extract
    ie_result = self._real_extract(url)
  File "d:\program files\python36-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1609, in _real_extract
    expected=True, video_id=video_id)
youtube_dl.utils.ExtractorError: tM8x5Zhe5O0: YouTube said: Please sign in to view this video.
```
---

### Description of your *issue*, suggested solution and other information

Unable to authenticate with enabled TFA on account.
Returns HTTP Error 400 after typing 2-step verification code.
Happens in any way of authentication: `.netrc`, direct passing login+pass via cmd args, direct passing login+pass+tfacode via cmd args.

**Comment by rmanly** [comment]
Found the same issue just now when attempting to grab my Watch Later for a flight.


```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-i', u'-f', u'bestvideo[ext=mp4]+bestaudio[ext=m4a]', u'--restrict-filenames', u'-u', u'PRIVATE', u'-2', u'867468', u'-o', u'/Users/ryan/Downloads/later/%(title)s.%(ext)s', u'https://www.youtube.com/playlist?list=WL']
Type account password and press [Return]: 
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.12.31
[debug] Python version 2.7.10 - Darwin-17.3.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.3.3-tessus, ffprobe 3.3.3-tessus, phantomjs 2.1.1
[debug] Proxy map: {}
[youtube:watchlater] Downloading login page
[youtube:watchlater] Looking up account info
[youtube:watchlater] Logging in
[youtube:watchlater] Submitting TFA code
WARNING: Unable to submit TFA code: HTTP Error 500: Internal Server Error
WARNING: Unable to extract CheckCookie URL
[youtube:watchlater] WL: Downloading webpage
ERROR: This playlist does not exist.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 438, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 2737, in _real_extract
    _, playlist = self._extract_playlist('WL')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 2259, in _extract_playlist
    raise ExtractorError(message, expected=True)
ExtractorError: This playlist does not exist.
```

**Comment by iGoreSchmidt** [comment]
Same *it here. Looks like cookie was expired and app tried to login back, but can't get thru TFA

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-s', u'--verbose', u':ytwatchlater', u'--ignore-config', u'-u', u'PRIVATE', u'--dump-pages']
Type account password and press [Return]: 
[debug] Encodings: locale UTF-8, fs utf-8, out None, pref UTF-8
[debug] youtube-dl version 2018.05.18
[debug] Python version 2.7.15 (CPython) - Darwin-17.5.0-x86_64-i386-64bit
[debug] exe versions: avconv 12.3, avprobe 12.3, ffmpeg 4.0, ffprobe 4.0, rtmpdump 2.4
[debug] Proxy map: {}
Type 2-step verification code and press [Return]: 
WARNING: Unable to submit TFA code: HTTP Error 500: Internal Server Error
ERROR: This playlist does not exist.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 503, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 2776, in _real_extract
    _, playlist = self._extract_playlist('WL')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 2291, in _extract_playlist
    raise ExtractorError(message, expected=True)
ExtractorError: This playlist does not exist.

```

Just for sure with Python 3.x.x
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-s', '--verbose', ':ytwatchlater', '--ignore-config', '-u', 'PRIVATE', '--dump-pages']
Type account password and press [Return]: 
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.05.18
[debug] Python version 3.6.5 (CPython) - Darwin-17.5.0-x86_64-i386-64bit
[debug] exe versions: avconv 12.3, avprobe 12.3, ffmpeg 4.0, ffprobe 4.0, rtmpdump 2.4
[debug] Proxy map: {}
Type 2-step verification code and press [Return]: 
WARNING: Unable to submit TFA code: HTTP Error 500: Internal Server Error
ERROR: This playlist does not exist.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 503, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 2776, in _real_extract
    _, playlist = self._extract_playlist('WL')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 2291, in _extract_playlist
    raise ExtractorError(message, expected=True)
youtube_dl.utils.ExtractorError: This playlist does not exist.

```

[--dump-pages here](https://www.dropbox.com/s/8dybyn94i7ovtbp/YTDL.zip?dl=0)

**Comment by reidcooper** [comment]
Receiving same error with Python 2.7.x

```
[debug] System config: []
[debug] User config: [u'-x', u'--audio-format', u'm4a', u'-o', u'~/Desktop/%(playlist_title)s/%(title)s.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'https://www.youtube.com/playlist?list=WL']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.06.04
[debug] Python version 2.7.10 (CPython) - Darwin-17.5.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.3.3, ffprobe 3.3.3, phantomjs 2.1.1
[debug] Proxy map: {}
[youtube:watchlater] Downloading login page
[youtube:watchlater] Looking up account info
[youtube:watchlater] Logging in
Type 2-step verification code and press [Return]:
[youtube:watchlater] Submitting TFA code
WARNING: Unable to submit TFA code: HTTP Error 500: Internal Server Error
[youtube:watchlater] WL: Downloading webpage
ERROR: This playlist does not exist.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 500, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 2790, in _real_extract
    _, playlist = self._extract_playlist('WL')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 2305, in _extract_playlist
    raise ExtractorError(message, expected=True)
ExtractorError: This playlist does not exist.
```

**Comment by eduardog3000** [comment]
@Vulp35 I'm working on a fix. What 2FA methods (Authenticator code, texted code, prompt in Google/Gmail app) do you have turned on on your Google account? Which one is the default, the one it asks for when you try to log in with a browser (use incognito if you don't know)?

**Comment by sandalle** [comment]
@eduardog3000 , for mine, my YouTube 2FA is via Google Authenticator.
```
Enter a verification code
Get a verification code from the Google Authenticator app
Enter the 6-digit code
```

**Comment by eduardog3000** [comment]
@sandalle What error do you get when you try to log in with youtube-dl? `HTTP Error 500: Internal Server Error` or `HTTP Error 400: Bad Request`.

Then can you download [this branch](https://github.com/eduardog3000/youtube-dl/tree/tfa-fix) and tell me what happens when you try to log in.

**Comment by sandalle** [comment]
@eduardog3000 
```
$ youtube-dl --version
2018.12.09
```
```
$ youtube-dl -u sandalle@gmail.com -2 https://www.youtube.com/watch?v=UcRZQL-grSs
Type account password and press [Return]:
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options.
```
```
$ youtube-dl -u sandalle@gmail.com -p -2 https://www.youtube.com/watch?v=UcRZQL-grSs
[youtube] Downloading login page
[youtube] Looking up account info
[youtube] Logging in
WARNING: Unable to login: Invalid password
[youtube] UcRZQL-grSs: Downloading webpage
[youtube] UcRZQL-grSs: Downloading video info webpage
^C
ERROR: Interrupted by user
```
I'm unsure why those aren't working, but using my ~/.netrc values worked in that I got `HTTP Error 500` for 2FA:
```
$ youtube-dl -n https://www.youtube.com/watch?v=UcRZQL-grSs
[youtube] Downloading login page
[youtube] Looking up account info
[youtube] Logging in
Type 2-step verification code and press [Return]:
[youtube] Submitting TFA code
WARNING: Unable to submit TFA code: HTTP Error 500: Internal Server Error
[youtube] UcRZQL-grSs: Downloading webpage
[youtube] UcRZQL-grSs: Downloading video info webpage
[download] Destination: The Diver's Grave _ Critical Role _ Campaign 2, Episode 44-UcRZQL-grSs.mp4
[download]   0.1% of 920.30MiB at 814.70KiB/s ETA 19:16^C
ERROR: Interrupted by user
```

I've cloned git@github.com:eduardog3000/youtube-dl.git seems to work with 2FA. :)
```
$ git checkout -b tfa-fix origin/tfa-fix
Branch 'tfa-fix' set up to track remote branch 'tfa-fix' from 'origin'.
Switched to a new branch 'tfa-fix'
````
```
$ python -m youtube_dl --version
2018.12.09
```
```
$ python -m youtube_dl -v -n https://www.youtube.com/watch?v=UcRZQL-grSs
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-n', u'https://www.youtube.com/watch?v=UcRZQL-grSs']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.12.09
[debug] Git HEAD: 40217df7e
[debug] Python version 2.7.15 (CPython) - Darwin-18.2.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] Downloading login page
[youtube] Looking up account info
[youtube] Logging in
Type 2-step verification code and press [Return]:
[youtube] Selecting TOTP TFA challenge
[youtube] Submitting TFA code
[youtube] Checking cookie
[youtube] UcRZQL-grSs: Downloading webpage
[youtube] UcRZQL-grSs: Downloading video info webpage
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on u'https://r5---sn-nx5s7n7s.googlevideo.com/videoplayback?signature=2A320C3FB21974C9F1211145558B3196BB5E8096.58844199BEE09D65408089751A52812BECE6CD43&expire=1544763840&source=youtube&sparams=dur%2Cei%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&txp=5535432&ip=2600%3A1%3A9810%3Aad5b%3A9095%3A43ad%3A377%3A83b6&fvip=5&itag=22&mime=video%2Fmp4&id=o-ANcaqnqgoVSCJDZq4rs6YxKGWaPKe3eJbZLQ6xvDsDEY&ratebypass=yes&requiressl=yes&mn=sn-nx5s7n7s%2Csn-nx57ynlz&mm=31%2C29&c=WEB&ipbits=0&initcwndbps=617500&key=yt6&lmt=1544553774170529&dur=16280.555&mv=m&pl=44&mt=1544742111&ms=au%2Crdu&ei=YOUSXN6ZBcrHkgbGlqCgAQ'
[download] Resuming download at byte 6225101
[download] Destination: The Diver's Grave _ Critical Role _ Campaign 2, Episode 44-UcRZQL-grSs.mp4
[download]   1.1% of 920.30MiB at 275.75KiB/s ETA 56:21^C
ERROR: Interrupted by user
```

I also tried downloading a playlist, and the first item worked with 2FA and the second continued to work with the 2FA session. :)
```
[youtube] Checking cookie
[youtube] YW01AC2NJAc: Downloading webpage
[youtube] YW01AC2NJAc: Downloading video info webpage
[youtube] YW01AC2NJAc: Marking watched
```

**Comment by rautamiekka** [comment]
If I were you I'd mask your logins.

**Comment by eduardog3000** [comment]
@sandalle 

`$ youtube-dl -u sandalle@gmail.com -p -2 https://www.youtube.com/watch?v=UcRZQL-grSs`
is because you have the syntax wrong, you have to put your 6 digit TOTP code after `-2`.

But it's good to see my code works for you. Just to be sure, this is the _very first_ screen you see after inputting your password in a normal browser?

![image](https://i.imgur.com/TFZLq3c.png)

**Not** something like this:

![image](https://i.imgur.com/POVLiWT.png)

**Comment by sandalle** [comment]
> @sandalle
> But it's good to see my code works for you. Just to be sure, this is the _very first_ screen you see after inputting your password in a normal browser?

Correct, that's what I see after using a browser in Privacy mode.

**Comment by eduardog3000** [comment]
@sandalle Thank you. Now I need someone who gets the `HTTP Error 400: Bad Request` (and probably should have the app prompt as their default method) to make sure I fixed that too.

Once I confirm that I should be ready to submit a PR.

**Comment by Vulp35** [comment]
> 
> 
> @Vulp35 I'm working on a fix. What 2FA methods (Authenticator code, texted code, prompt in Google/Gmail app) do you have turned on on your Google account? Which one is the default, the one it asks for when you try to log in with a browser (use incognito if you don't know)?

![screenshot_2018-12-13 2-step verification](https://user-images.githubusercontent.com/45741898/49977024-2af11a80-ff0a-11e8-9bc0-4d8f58f3b4d1.png)


I can add prompt aswell if that helps you.

**Comment by eduardog3000** [comment]
Oh, good, Prompt started working for me (you can see in the image above I got locked out of it), so I could test it myself.

Looks like all is good, I'll submit the PR.

**Comment by Vulp35** [comment]
> 
> 
> Oh, good, Prompt started working for me (you can see in my image above I got locked out of it), so I could test it myself.

Anything special I have to do for prompt? I accepted then hit enter but that didn't seem to work?

**Comment by eduardog3000** [comment]
@Vulp35 youtube-dl can't actually use the prompt, it still needs the Google Authenticator code, but I wanted to make sure that someone with the prompt enabled was still able to use the code through youtube-dl. The way the fix works I wasn't completely sure it would work when Google asks for the prompt by default.

**Comment by Vulp35** [comment]
@eduardog3000 oh gotcha! Yup can also confirm it working with prompt enabled as the default but using a code from Authenticator in youtube-dl

**Comment by uruiamme** [comment]
I am having the same difficulty with the version 2018.11.23 and the forked version that was modified by @eduardog3000 . This was difficult to test on Windows without an executable, but I figured it out. In any case, when I temporarily disable 2FA on my account, both the stock and modified versions worked for me. So I am not sure what the fix was supposed to do, but I saw no change in behavior.

```
[youtube] Downloading login page
[youtube] Looking up account info
[youtube] Logging in
WARNING: Unable to log in: HTTP Error 400: Bad Request
```

**Comment by briansmithbeta** [comment]
I'm still having this issue in version 2019.02.08. I use SMS messages as my TFA method. 


Version proof:
```
.\youtube-dl.exe --version
2019.02.08

```

Debug output on Windows:
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [':ytwatchlater', '-i', '--get-id', '-v', '-r', '4.2M', '--username', 'PRIVATE', '-p', 'PRIVATE']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.02.08
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg N-80386-g5f5a97d, ffprobe N-80386-g5f5a97d
[debug] Proxy map: {}
Type 2-step verification code and press [Return]:
WARNING: Unable to submit TFA code: HTTP Error 400: Bad Request
ERROR: This playlist does not exist.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6w61832c\build\youtube_dl\YoutubeDL.py", line 794, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6w61832c\build\youtube_dl\extractor\common.py", line 508, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6w61832c\build\youtube_dl\extractor\youtube.py", line 2923, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6w61832c\build\youtube_dl\extractor\youtube.py", line 2435, in _extract_playlist
youtube_dl.utils.ExtractorError: This playlist does not exist.
```

Side note:
First, I was unable to log in using an App Password, which should bypass TFA. [This comment ](https://github.com/rg3/youtube-dl/issues/5280#issuecomment-86683566) on #5280 led me to attempt to login using my regular password and TFA instead (not my preference, but I was willing to try it as a workaround). But that's failing too, which led me to this ticket. 
It seems like both App Passwords and TFA are broken in version 2019.02.08. Can someone familiar with how to correctly use youtube-dl with an App Password confirm/debunk that? If both are broken, that makes it very difficult to get private playlists of any kind.

**Comment by eduardog3000** [comment]
@uruiamme Which version is that log from? My fork might be broken for reasons other than TFA because it is a fork of an old version. The newest official version still doesn't work with TFA because no fix has been merged in.

[This branch](https://github.com/eduardog3000/youtube-dl/commits/tfa-fix-2019) is both the newest youtube-dl version, and has my fix applied. It should work for you and anyone who has TOTP TFA enabled. If not, post the log from it.

**Comment by uruiamme** [comment]
@eduardog3000 I had followed your link to https://github.com/eduardog3000/youtube-dl/tree/tfa-fix
but you just gave this new link:
https://github.com/eduardog3000/youtube-dl/commits/tfa-fix-2019

So my test found out that both 2018.11.23 (stock) and yours based on 2018.11.23 were both still not working. I have not tried the new one. Why would the new one work? Did your fix change anything or did the main trunk make changes to TFA problems?

**Comment by eduardog3000** [comment]
@uruiamme 2018.11.23 stock is old and doesn't work anymore for reasons unrelated to TFA. YouTube changes things a lot, and youtube-dl has to keep up. My version based on 2018.11.23 doesn't work for the same reason.

The new branch is based on the latest commit to this main repo, so it should work where 2018.11.23 doesn't. But if YouTube has changed anything about TFA since then, my fix might not work no matter the base version.

Try my `tfa-fix-2019` branch, if it doesn't work, paste the error log.

**Comment by FranciscoPombal** [comment]
@dstftw @remitamine 
I apologize for possibly tagging excessively, but 2FA on Youtube has been broken for months, yet a working fix has existed for almost as long.

Can you at least say what the current blockers are for merging the fix? The latest PR was simply locked with no further feedback given.

Links:
- [The original PR fixing this issue](https://github.com/rg3/youtube-dl/pull/18521)
- [A new branch by the original author of the PR with the same fix but based on a more recent commit of the master branch](https://github.com/eduardog3000/youtube-dl/tree/tfa-fix-2019)

@eduardog3000 just curious, why create a new branch instead of rebasing the old one?

**Comment by eduardog3000** [comment]
@FranciscoPombal as a quick fix for the person who was asking me about it here. If the maintainers are willing to merge my code I'd happily get it all sorted. Although the code in my PR, while based on an old upstream commit, can still be merged without conflict.

**Comment by LoneFenris** [comment]
Is there some lingering issue with the PR that's preventing merge?

**Comment by eduardog3000** [comment]
@LoneFenris There was an issue, I fixed it, then the collaborator never responded and eventually locked the conversation.

**Comment by raffaem** [comment]
Still having this issue with youtube-dl version 2019.10.29

**Comment by LoneFenris** [comment]
@raffaem From the conversation on the associated PR, it appears there may be two issues with it:

1. There is a concern that having TFA support could cause ytdl to overflow the number of TFA challenges Google allows in a time period

2. There is a suggested improvement to how the PR responds to challenges that is yet to be implemented
