### ISSUE TITLE
Not able to download videos

### ISSUE THREAD

**Issue by dhananjaygoel** [rg3/youtube-dl#15251]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.01.14*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.01.14**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

youtube-dl -v -u testname -p testpass -o "C:/MyVideos/test/" https://videos.raywenderlich.com/courses/105-testing-in-ios/lessons/22

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'-o', u'C:/MyVideos/test/', u'https://videos.r
aywenderlich.com/courses/105-testing-in-ios/lessons/22']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.01.14
[debug] Python version 2.7.13 (CPython) - Windows-2012ServerR2-6.3.9600
[debug] exe versions: ffmpeg N-89794-gc51301db14
[debug] Proxy map: {}
[generic] 22: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 22: Downloading webpage
[generic] 22: Extracting information
ERROR: Unsupported URL: https://videos.raywenderlich.com/courses/105-testing-in-ios/lessons/22
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\youtube_dl\extractor\generic.py", line 2176, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "c:\python27\lib\site-packages\youtube_dl\compat.py", line 2541, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "c:\python27\lib\site-packages\youtube_dl\compat.py", line 2530, in _XML
    parser.feed(text)
  File "c:\python27\lib\xml\etree\ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "c:\python27\lib\xml\etree\ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: mismatched tag: line 74, column 4
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "c:\python27\lib\site-packages\youtube_dl\extractor\common.py", line 438, in extract
    ie_result = self._real_extract(url)
  File "c:\python27\lib\site-packages\youtube_dl\extractor\generic.py", line 3086, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://videos.raywenderlich.com/courses/105-testing-in-ios/lessons/22

**Comment by mesolaries** [comment]
Use only youtube video URL. Other URL's not supported as error says (UnsupportedError: Unsupported URL: https://videos.raywenderlich.com/courses/105-testing-in-ios/lessons/22)

**Comment by mesolaries** [comment]
The site you trying to download from, seems to be unsupported. Check supported sites: https://github.com/rg3/youtube-dl/blob/master/docs/supportedsites.md
