### ISSUE TITLE
[SVT] Add support for "Kanaler" livestreams

### ISSUE THREAD

**Issue by hubiqs** [rg3/youtube-dl#15279]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.01.14*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.01.14**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
$ youtube-dl -v "https://www.svtplay.se/kanaler/svt1"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.svtplay.se/kanaler/svt1']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.01.14
[debug] Python version 3.6.4 (CPython) - Linux-4.14.13-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 3.4.1, ffprobe 3.4.1
[debug] Proxy map: {}
[generic] svt1: Requesting header
WARNING: Falling back on generic information extractor.
[generic] svt1: Downloading webpage
[generic] svt1: Extracting information
ERROR: Unsupported URL: https://www.svtplay.se/kanaler/svt1
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 438, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/generic.py", line 3086, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.svtplay.se/kanaler/svt1
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.svtplay.se/kanaler/svt1
- Single video: https://www.svtplay.se/kanaler/svt2
- Single video: https://www.svtplay.se/kanaler/svt24
- Single video: https://www.svtplay.se/kanaler/barnkanalen
- Single video: https://www.svtplay.se/kanaler/kunskapskanalen

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

This is a plea for someone to figure out how to support the livestreams available on Swedish SVT-Play (on-demand videos already work fine.) This would make it very convenient to watch on the desktop by piping the output to for instance vlc.
```$ youtube-dl -o - "https://www.svtplay.se/kanaler/svt1" | vlc -```
Grateful for any and all efforts made to make this happen!

**Comment by hubiqs** [comment]
Well, I'm not a programmer and I don't know streaming tech nor python, but I made some small adaptations to ```extractor/svt.py``` and I can at least get y-dl to download one segment of the live stream. That's all though. I suspect there are some very important bits missing here, but I guess it's a start. People who actually know what they're doing could surely make better sense of this stuff...

```
class SVTLiveIE(SVTBaseIE):
    IE_DESC = 'SVT Play Live Streams'
    _VALID_URL = r'https?://(?:www\.)?svtplay\.se/kanaler/(?P<id>svt1|svt2|svt24|barnkanalen|kunskapskanalen)'
    _TESTS = []

    def _real_extract(self, url):
        video_id = self._match_id(url)

        webpage = self._download_webpage(url, video_id)

        if video_id:
            data = self._download_json(
                'https://api.svt.se/videoplayer-api/video/ch-%s' % video_id,
                video_id, headers=self.geo_verification_headers())
            info_dict = self._extract_video(data, video_id)
            if not info_dict.get('title'):
                info_dict['title'] = re.sub(
                    r'\s*\|\s*.+?$', '',
                    info_dict.get('episode') or self._og_search_title(webpage))
            return info_dict
```
Any ideas about what's missing here? I have no clue what I'm doing, any pointers are welcome. Or better yet, actual programmers. Whatever I end up hacking together probably won't be or merge-worthy...

**Comment by hubiqs** [comment]
I've finally had a moment to try this out, and it works great! Thanks a lot @0x9fff00 ! Good work! :-)
