### ISSUE TITLE
Unable to download video from MPD manifest

### ISSUE THREAD

**Issue by southrop** [rg3/youtube-dl#15273]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.01.14*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.01.14**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
$ youtube-dl -F -v "http://wpc.40576.mucdn.net/8040576/cxldfaclvod1/02ed2c7c-ad16-41b5-9951-ae2899c7b7db/1590_20171017151005807.ism/manifest(format=mpd-time-csf)?token=Ms64OzP7Zj0ZXUuQrEOVf0eRqJcc8PZg2a30gMCFy4e6wWe16LoLhvu1cYKgt9RW"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-F', '-v', 'http://wpc.40576.mucdn.net/8040576/cxldfaclvod1/02ed2c7c-ad16-41b5-9951-ae2899c7b7db/1590_20171017151005807.ism/manifest(format=mpd-time-csf)?token=Ms64OzP7Zj0ZXUuQrEOVf0eRqJcc8PZg2a30gMCFy4e6wWe16LoLhvu1cYKgt9RW']
[debug] Encodings: locale cp932, fs mbcs, out cp932, pref cp932
[debug] youtube-dl version 2018.01.14
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.16299
[debug] exe versions: ffmpeg 3.4, ffprobe 3.4, rtmpdump 2.3
[debug] Proxy map: {}
[generic] manifest(format=mpd-time-csf)?token=Ms64OzP7Zj0ZXUuQrEOVf0eRqJcc8PZg2a30gMCFy4e6wWe16LoLhvu1cYKgt9RW: Requesting header
WARNING: Falling back on generic information extractor.
[generic] manifest(format=mpd-time-csf)?token=Ms64OzP7Zj0ZXUuQrEOVf0eRqJcc8PZg2a30gMCFy4e6wWe16LoLhvu1cYKgt9RW: Downloading webpage
[generic] manifest(format=mpd-time-csf)?token=Ms64OzP7Zj0ZXUuQrEOVf0eRqJcc8PZg2a30gMCFy4e6wWe16LoLhvu1cYKgt9RW: Extracting information
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpo17hktrm\build\youtube_dl\YoutubeDL.py", line 784, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpo17hktrm\build\youtube_dl\extractor\common.py", line 438, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpo17hktrm\build\youtube_dl\extractor\generic.py", line 2194, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpo17hktrm\build\youtube_dl\extractor\common.py", line 1069, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

### Description of your *issue*, suggested solution and other information

I'm trying to download a video from dreamfactory.video. In particular, the one I am trying to download is [this one](http://dreamfactory.video/web/contents/detail/64133159e59d1c94dcb). It's easy to find the [MPD manifest URL](http://wpc.40576.mucdn.net/8040576/cxldfaclvod1/02ed2c7c-ad16-41b5-9951-ae2899c7b7db/1590_20171017151005807.ism/manifest(format=mpd-time-csf)?token=Ms64OzP7Zj0ZXUuQrEOVf0eRqJcc8PZg2a30gMCFy4e6wWe16LoLhvu1cYKgt9RW) using Chrome Dev Tools, but when I plug that into youtube-dl, I get the error above.

Downloading the manifest file itself and opening it in a text editor gives me this:

```
<?xml version="1.0" encoding="utf-8"?>
<MPD
  xmlns="urn:mpeg:dash:schema:mpd:2011"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  profiles="urn:mpeg:dash:profile:isoff-live:2011"
  type="static"
  xmlns:sea="urn:mpeg:dash:schema:sea:2012"
  mediaPresentationDuration="PT16.213S"
  minBufferTime="PT3S">
  <Period>
    <AdaptationSet id="1" group="1" profiles="ccff" bitstreamSwitching="false" segmentAlignment="true" contentType="video" mimeType="video/mp4" codecs="avc1.64001F" maxWidth="1280" maxHeight="720" startWithSAP="1">
      <ContentProtection schemeIdUri="urn:mpeg:dash:sea:2012"><sea:SegmentEncryption schemeIdUri="urn:mpeg:dash:sea:aes128-cbc:2013"/><sea:KeySystem keySystemUri="urn:mpeg:dash:sea:keysys:http:2013"/><sea:CryptoPeriod keyUriTemplate="https://cxldfaclvod1.keydelivery.japaneast.media.azure.net/?KID=4783c02d-354c-4114-89d6-aec561639db9" IV="0xB4BB18B13C61ACE34AD0F98748807977"/></ContentProtection>
      <SegmentTemplate timescale="10000000" media="QualityLevels($Bandwidth$)/Fragments(video=$Time$,format=mpd-time-csf)" initialization="QualityLevels($Bandwidth$)/Fragments(video=i,format=mpd-time-csf)">
        <SegmentTimeline><S d="20020000" r="7"/><S d="1001000"/></SegmentTimeline>
      </SegmentTemplate><Representation id="1_V_video_1" bandwidth="1411160" width="1280" height="720"/><Representation id="1_V_video_2" bandwidth="700704" codecs="avc1.4D401F" width="640" height="360"/></AdaptationSet>
    <AdaptationSet id="2" group="5" profiles="ccff" bitstreamSwitching="false" segmentAlignment="true" contentType="audio" mimeType="audio/mp4" codecs="mp4a.40.2">
      <ContentProtection schemeIdUri="urn:mpeg:dash:sea:2012"><sea:SegmentEncryption schemeIdUri="urn:mpeg:dash:sea:aes128-cbc:2013"/><sea:KeySystem keySystemUri="urn:mpeg:dash:sea:keysys:http:2013"/><sea:CryptoPeriod keyUriTemplate="https://cxldfaclvod1.keydelivery.japaneast.media.azure.net/?KID=4783c02d-354c-4114-89d6-aec561639db9" IV="0xB4BB18B13C61ACE34AD0F98748807977"/></ContentProtection>
      <SegmentTemplate timescale="10000000" media="QualityLevels($Bandwidth$)/Fragments(aac_UND_2_128=$Time$,format=mpd-time-csf)" initialization="QualityLevels($Bandwidth$)/Fragments(aac_UND_2_128=i,format=mpd-time-csf)">
        <SegmentTimeline><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="20053334"/><S d="20053333" r="1"/><S d="1706667"/></SegmentTimeline>
      </SegmentTemplate><Representation id="5_A_aac_UND_2_128_1" bandwidth="128124" audioSamplingRate="48000"/></AdaptationSet>
  </Period>
</MPD>
```

**Comment by dstftw** [comment]
DRM is not supported.
