### ISSUE TITLE
Support for nick.com

### ISSUE THREAD

**Issue by ghost** [rg3/youtube-dl#1528]
Nick.com doesn't work with the generic downloader.

`$ youtube-dl http://www.nick.com/videos/clip/legend-of-korra-116-full-episode.html`

```bash
WARNING: Falling back on generic information extractor.
[generic] legend-of-korra-116-full-episode.html: Downloading webpage
[generic] legend-of-korra-116-full-episode.html: Extracting information
ERROR: Invalid URL: http://www.nick.com/videos/clip/legend-of-korra-116-full-episode.html; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
$ youtube-dl http://www.nick.com/videos/clip/legend-of-korra-116-full-episode.html --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://www.nick.com/videos/clip/legend-of-korra-116-full-episode.html', '--verbose']
[debug] youtube-dl version 2013.09.20.1
[debug] Python version 2.7.2 - Darwin-12.5.0-x86_64-i386-64bit
[debug] Proxy map: {}
WARNING: Falling back on generic information extractor.
[generic] legend-of-korra-116-full-episode.html: Downloading webpage
[generic] legend-of-korra-116-full-episode.html: Extracting information
ERROR: Invalid URL: http://www.nick.com/videos/clip/legend-of-korra-116-full-episode.html; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 321, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 103, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 163, in _real_extract
    raise ExtractorError(u'Invalid URL: %s' % url)
ExtractorError: Invalid URL: http://www.nick.com/videos/clip/legend-of-korra-116-full-episode.html; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
```

Sample video: http://www.nick.com/videos/clip/legend-of-korra-116-full-episode.html

**Comment by jamesBrosnahan** [comment]
Here is a video on how to get links using ettercap. https://www.youtube.com/watch?v=8tGR2lS-F8Q 
search with grep for rtmp links

**Comment by remitamine** [comment]
will be supported in the next version.
