### ISSUE TITLE
[Spiegel.de] Unable to extract server URL with nexxPLAY

### ISSUE THREAD

**Issue by Hb-** [rg3/youtube-dl#15285]
Downloading videos from Spiegel.de fails on Windows 7 64 Bit and on Ubuntu.
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--write-pages', 'http://www.spiegel.de/video/spiegel-tv-magazin-ueber-guellekrise-in-schleswig-holstein-video-99012776.html']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.01.14
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[Spiegel] 99012776: Downloading webpage
[Spiegel] Saving request to 99012776_http_-_www.spiegel.de_video_spiegel-tv-magazin-ueber-guellekrise-in-schleswig-holstein-video-99012776.html.dump
ERROR: Unable to extract server URL; please report [... Hb-]
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpo17hktrm\build\youtube_dl\YoutubeDL.py", line 784, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpo17hktrm\build\youtube_dl\extractor\common.py", line 438, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpo17hktrm\build\youtube_dl\extractor\spiegel.py", line 71, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpo17hktrm\build\youtube_dl\extractor\common.py", line 794, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract server URL; please report [... Hb-]
```
Dump file is on https://gist.github.com/Hb-/b5c0b6b67858b644acce0ccd1c91b0f4

Same bug on Ubuntu:
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'http://www.spiegel.de/video/spiegel-tv-magazin-ueber-guellekrise-in-schleswig-holstein-video-99012776.html', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8
[debug] youtube-dl version 2018.01.14
[debug] Python version 2.7.12 (CPython) - Linux-4.4.0-92-generic-i686-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1, rtmpdump 2.4
[debug] Proxy map: {}
[Spiegel] 99012776: Downloading webpage
ERROR: Unable to extract server URL; please report [... Hb-]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 784, in extract_info ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 438, in extract ie_result = self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/spiegel.py", line 71, in _real_extract webpage, 'server URL', group='url')
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 794, in _search_regex raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract server URL; please report [... Hb-]
```

**Comment by Hb-** [comment]
Fix verified with version 2018.01.18. Thanks.
