### ISSUE TITLE
unable to download JSON metadata(eduonix) 

### ISSUE THREAD

**Issue by ragavanrajan** [rg3/youtube-dl#15307]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.01.14*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.01.14**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
C:\youtube-dl>youtube-dl -v https://www.eduonix.com/dashboard/Become-A-Certified-Web-Developer-From-Scratch/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.eduonix.com/dashboard/Become-A-Certified-Web-Developer-From-Scratch/']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.01.14
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.16299
[debug] exe versions: none
[debug] Proxy map: {}
[generic] Become-A-Certified-Web-Developer-From-Scratch: Requesting header
WARNING: Falling back on generic information extractor.
[generic] Become-A-Certified-Web-Developer-From-Scratch: Downloading webpage
[generic] Become-A-Certified-Web-Developer-From-Scratch: Extracting information
ERROR: Unsupported URL: https://www.eduonix.com/dashboard/Become-A-Certified-Web-Developer-From-Scratch/
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpo17hktrm\build\youtube_dl\YoutubeDL.py", line 784, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpo17hktrm\build\youtube_dl\extractor\common.py", line 438, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpo17hktrm\build\youtube_dl\extractor\generic.py", line 3086, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.eduonix.com/dashboard/Become-A-Certified-Web-Developer-From-Scratch/
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.eduonix.com/dashboard/Become-A-Certified-Web-Developer-From-Scratch/
- Playlist: Hard to identify

---

### Description of your *issue*, suggested solution and other information

I am trying to download videos from the above URL. I have a valid account and followed all the procedures. If I try to download the playlist  I am ending up with below error. 

Logs for your reference

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--cookies', 'C:\\Users\\ragavanrajan\\Downloads\\cookiesjan.txt', '-o', 'C:\\plural\\%(playlist_index)s - %(title)s.%(ext)s', '--min-sleep-interval', '31', '--max-sleep-interval', '32', 'https://www.eduonix.com/dashboard/Become-A-Certified-Web-Developer-From-Scratch/lecture/', '--playlist-start', '1', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.01.14
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.16299
[debug] exe versions: none
[debug] Proxy map: {}
[generic] lecture: Requesting header
WARNING: Falling back on generic information extractor.
[generic] lecture: Downloading webpage
[generic] lecture: Extracting information
ERROR: Unsupported URL: https://www.eduonix.com/dashboard/Become-A-Certified-Web-Developer-From-Scratch/lecture/
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpo17hktrm\build\youtube_dl\YoutubeDL.py", line 784, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpo17hktrm\build\youtube_dl\extractor\common.py", line 438, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpo17hktrm\build\youtube_dl\extractor\generic.py", line 3086, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.eduonix.com/dashboard/Become-A-Certified-Web-Developer-From-Scratch/lecture/
```
Kindly help.

**Comment by ragavanrajan** [comment]
Any update on this site support please.

**Comment by LocksmithArmy** [comment]
Any chance this eduonix downloads work yet? I am having the same error "Unsupported URL".

Thanks
