### ISSUE TITLE
Fox.com failing since December2017

### ISSUE THREAD

**Issue by reubenbrown13** [rg3/youtube-dl#15333]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.01.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--sub-lang', u'en', u'--write-sub', u'--convert-subs', u'srt', u'--embed-subs', u'-f', u'best', u'-v', u'https://www.fox.com/watch/ea20f60f94d0dfb74ed2869864a0376f/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.01.18
[debug] Python version 2.7.12 (CPython) - Linux-4.13.0-21-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1, rtmpdump 2.4
[debug] Proxy map: {}
[FOX] ea20f60f94d0dfb74ed2869864a0376f: Downloading JSON metadata
[FOX] ea20f60f94d0dfb74ed2869864a0376f: Downloading webpage
[uplynk:preplay] f4b871951085424ea77355be45c85006: Downloading JSON metadata
[uplynk:preplay] f4b871951085424ea77355be45c85006: Downloading m3u8 information
[uplynk:preplay] f4b871951085424ea77355be45c85006: Downloading JSON metadata
[info] Writing video subtitles to: 3 X 1-f4b871951085424ea77355be45c85006.en.scc
[debug] Invoking downloader on u'http://content-ausc2.uplynk.com/f4b871951085424ea77355be45c85006/k.m3u8'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 663
[download] Destination: 3 X 1-f4b871951085424ea77355be45c85006.mp4
[download]   0.2% of ~1.80GiB at Unknown speed ETA Unknown ETAERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1895, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1834, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 361, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/hls.py", line 167, in real_download
    self._prepare_url(info_dict, decrypt_info['URI'])).read()
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2198, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden

...
<end of log>
```
---
* any video from fox.com will do, but here is one that I was able to download in November
- Single video: https://www.fox.com/watch/ea20f60f94d0dfb74ed2869864a0376f/
---
I don't know if fox.com changed the way they stream files, but it looks like it loads a playlist with a bunch of video slices in it.  When trying to access the slices directly, I get errors when trying to download them.

**Comment by reubenbrown13** [comment]
I know this is very similar to #14147, but it is caused in different parts of the code from what I can see in the error out put.

**Comment by StevenDTX** [comment]
This works just fine for me

```
E:\>youtube-dl --verbose https://www.fox.com/watch/ea20f60f94d0dfb74ed2869864a0376f/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.fox.com/watch/ea20f60f94d0dfb74ed2869864a0376f/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.01.14
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-89395-g71421f382f, ffprobe N-72383-g7206b94, rtmpdump 2.4
[debug] Proxy map: {}
[FOX] ea20f60f94d0dfb74ed2869864a0376f: Downloading JSON metadata
[FOX] ea20f60f94d0dfb74ed2869864a0376f: Downloading webpage
[uplynk:preplay] f4b871951085424ea77355be45c85006: Downloading JSON metadata
[uplynk:preplay] f4b871951085424ea77355be45c85006: Downloading m3u8 information
[uplynk:preplay] f4b871951085424ea77355be45c85006: Downloading JSON metadata
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://content-ausc4.uplynk.com/f4b871951085424ea77355be45c85006/k.m3u8'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 663
[download] Destination: 3 X 1-f4b871951085424ea77355be45c85006.mp4
[download]   0.5% of ~1.69GiB at  7.71MiB/s ETA 05:39
ERROR: Interrupted by user
```

**Comment by StevenDTX** [comment]
I went ahead and let it complete, just to make sure. And on 2018.01.18.

```
E:\>youtube-dl --verbose https://www.fox.com/watch/ea20f60f94d0dfb74ed2869864a0376f/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.fox.com/watch/ea20f60f94d0dfb74ed2869864a0376f/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.01.18
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-89395-g71421f382f, ffprobe N-72383-g7206b94, rtmpdump 2.4
[debug] Proxy map: {}
[FOX] ea20f60f94d0dfb74ed2869864a0376f: Downloading JSON metadata
[FOX] ea20f60f94d0dfb74ed2869864a0376f: Downloading webpage
[uplynk:preplay] f4b871951085424ea77355be45c85006: Downloading JSON metadata
[uplynk:preplay] f4b871951085424ea77355be45c85006: Downloading m3u8 information
[uplynk:preplay] f4b871951085424ea77355be45c85006: Downloading JSON metadata
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://content-ause2.uplynk.com/f4b871951085424ea77355be45c85006/k.m3u8'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 663
[download] Destination: 3 X 1-f4b871951085424ea77355be45c85006.mp4
[download] 100% of 1.63GiB in 06:22
[debug] ffmpeg command line: ffprobe -show_streams "file:3 X 1-f4b871951085424ea77355be45c85006.mp4"
[ffmpeg] Fixing malformed AAC bitstream in "3 X 1-f4b871951085424ea77355be45c85006.mp4"
[debug] ffmpeg command line: ffmpeg -y -i "file:3 X 1-f4b871951085424ea77355be45c85006.mp4" -c copy -f mp4 "-bsf:a" aac_adtstoasc "file:3 X 1-f4b871951085424ea77355be45c85006.temp.mp4"

```

**Comment by reubenbrown13** [comment]
Seems like it must be related to one of the files I have installed.  On my Ubuntu 17.10 machine that is running the 2017.09.24 version it works:
youtube-dl  --sub-lang en --write-sub --convert-subs srt --embed-subs -f best --verbose https://www.fox.com/watch/ea20f60f94d0dfb74ed2869864a0376f/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--sub-lang', 'en', '--write-sub', '--convert-subs', 'srt', '--embed-subs', '-f', 'best', '--verbose', 'https://www.fox.com/watch/ea20f60f94d0dfb74ed2869864a0376f/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.09.24
[debug] Python version 3.6.3 - Linux-4.13.0-25-generic-x86_64-with-Ubuntu-17.10-artful
[debug] exe versions: avconv 13_dev0, avprobe 13_dev0, ffmpeg 3.3.4-2, ffprobe 3.3.4-2, rtmpdump 2.4
[debug] Proxy map: {}
[FOX] ea20f60f94d0dfb74ed2869864a0376f: Downloading JSON metadata
[FOX] ea20f60f94d0dfb74ed2869864a0376f: Downloading JSON metadata
[FOX] ea20f60f94d0dfb74ed2869864a0376f: Downloading m3u8 information
[debug] Invoking downloader on 'https://content-auso4.uplynk.com/f4b871951085424ea77355be45c85006/k.m3u8?pbs=e041511a9e544fe3a78eae00702128b4'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 730
[download] Destination: 3 X 1-ea20f60f94d0dfb74ed2869864a0376f.mp4

on the Ubuntu 16.04 computer I get:
youtube-dl --verbose https://www.fox.com/watch/ea20f60f94d0dfb74ed2869864a0376f/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.fox.com/watch/ea20f60f94d0dfb74ed2869864a0376f/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.01.07
[debug] Python version 2.7.12 (CPython) - Linux-4.13.0-21-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1, rtmpdump 2.4
[debug] Proxy map: {}
[FOX] ea20f60f94d0dfb74ed2869864a0376f: Downloading JSON metadata
[FOX] ea20f60f94d0dfb74ed2869864a0376f: Downloading webpage
[uplynk:preplay] f4b871951085424ea77355be45c85006: Downloading JSON metadata
[uplynk:preplay] f4b871951085424ea77355be45c85006: Downloading m3u8 information
[uplynk:preplay] f4b871951085424ea77355be45c85006: Downloading JSON metadata
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'http://content-ausc1.uplynk.com/f4b871951085424ea77355be45c85006/k.m3u8'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 663
[download] Destination: 3 X 1-f4b871951085424ea77355be45c85006.mp4
[download]   0.2% of ~1.80GiB at  7.40MiB/s ETA 04:23ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1895, in process_info
    success = dl(filename, info_dict)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1834, in dl
    return fd.download(name, info)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/downloader/common.py", line 361, in download
    return self.real_download(filename, info_dict)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/downloader/hls.py", line 167, in real_download
    self._prepare_url(info_dict, decrypt_info['URI'])).read()
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 2198, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden

**Comment by rellik31** [comment]
@reubenbrown13 does youtube-dl version 2017.09.24 also include the adds being downloaded for you?

i cant use the new versions of ytdl because i get the http error  but version 2017.09.24 does work  because it uses ffmpeg to do the download but it also downloads the adds (the time stamp freezes when they play)

have you watch the video download that you have done to know if it works?

thanks

**Comment by StevenDTX** [comment]
Yes, with v2017.09.24, it downloads commercials. It plays just fine in VLC.

```
E:\>youtube-dl.2017.09.24.exe --verbose https://www.fox.com/watch/ea20f60f94d0dfb74ed2869864a0376f/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.fox.com/watch/ea20f60f94d0dfb74ed2869864a0376f/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.09.24
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-89395-g71421f382f, ffprobe N-72383-g7206b94, rtmpdump 2.4
[debug] Proxy map: {}
[FOX] ea20f60f94d0dfb74ed2869864a0376f: Downloading JSON metadata
[FOX] ea20f60f94d0dfb74ed2869864a0376f: Downloading JSON metadata
[FOX] ea20f60f94d0dfb74ed2869864a0376f: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://content-ause4.uplynk.com/f4b871951085424ea77355be45c85006/k.m3u8?pbs=7d6b831e177a4858ba4c170c26036441'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 746
[download] Destination: 3 X 1-ea20f60f94d0dfb74ed2869864a0376f.mp4
[download] 100% of 1.75GiB in 07:45
[debug] ffmpeg command line: ffprobe -show_streams "file:3 X 1-ea20f60f94d0dfb74ed2869864a0376f.mp4"
[ffmpeg] Fixing malformed AAC bitstream in "3 X 1-ea20f60f94d0dfb74ed2869864a0376f.mp4"
[debug] ffmpeg command line: ffmpeg -y -i "file:3 X 1-ea20f60f94d0dfb74ed2869864a0376f.mp4" -c copy -f mp4 "-bsf:a" aac_adtstoasc "file:3 X 1-ea20f60f94d0dfb74ed2869864a0376f.temp.mp4"
```

**Comment by reubenbrown13** [comment]
I get ads and no sound weirdly enough.  There is an audio track, but it doesn't play.  When I open the file in HandBrake, it shows an audio track in the HE-AAC format, but if I re-transcode it, there is still no audio playback.

**Comment by Nii-90** [comment]
@reubenbrown13 
The obvious difference is that the non-working instance is running under Python 2.7, and the working one is running under Python 3.6.  Some of the other issues on here (not necessarily related to Fox) have mentioned Python 2.7 being a problem lately.  My money's on that.  Use pip3 to explicitly install under Python 3 and see if that resolves it.

**Comment by Rick7C2** [comment]
I am having the same issues on my linux machines. Works fine on windows.

Working windows...

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--ap-mso', 'Charter_Direct', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', 'https://www.fox.com/watch/3b70eb8b2ce846d1695e2ac3d8b25bab/', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.02.04
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.16299
[debug] exe versions: ffmpeg git-2017-12-18-74f408c, ffprobe git-2017-12-18-74f408c
[debug] Proxy map: {}
[FOX] 3b70eb8b2ce846d1695e2ac3d8b25bab: Downloading JSON metadata
[FOX] 3b70eb8b2ce846d1695e2ac3d8b25bab: Retrieving Media Token
[FOX] 3b70eb8b2ce846d1695e2ac3d8b25bab: Downloading webpage
[uplynk:preplay] dab971c1f3a149ae9f0d60f466b72a7e: Downloading JSON metadata
[uplynk:preplay] dab971c1f3a149ae9f0d60f466b72a7e: Downloading m3u8 information
[uplynk:preplay] dab971c1f3a149ae9f0d60f466b72a7e: Downloading JSON metadata
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://content-ause3.uplynk.com/dab971c1f3a149ae9f0d60f466b72a7e/k.m3u8'
[download] All-Star Finale-dab971c1f3a149ae9f0d60f466b72a7e.mp4 has already been downloaded
[download] 100% of 1.53GiB
[debug] ffmpeg command line: ffprobe -show_streams "file:All-Star Finale-dab971c1f3a149ae9f0d60f466b72a7e.mp4"
[ffmpeg] Fixing malformed AAC bitstream in "All-Star Finale-dab971c1f3a149ae9f0d60f466b72a7e.mp4"
[debug] ffmpeg command line: ffmpeg -y -i "file:All-Star Finale-dab971c1f3a149ae9f0d60f466b72a7e.mp4" -c copy -f mp4 "-bsf:a" aac_adtstoasc "file:All-Star Finale-dab971c1f3a149ae9f0d60f466b72a7e.temp.mp4"
```

Linux box 1 non working python2

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--ap-mso', u'Charter_Direct', u'--ap-username', u'PRIVATE', u'--ap-password', u'PRIVATE', u'https://www.fox.com/watch/3b70eb8b2ce846d1695e2ac3d8b25bab/', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.01.27
[debug] Python version 2.7.12 (CPython) - Linux-4.10.0-38-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 3.4.1, ffprobe 3.4.1
[debug] Proxy map: {}
[FOX] 3b70eb8b2ce846d1695e2ac3d8b25bab: Downloading JSON metadata
[FOX] 3b70eb8b2ce846d1695e2ac3d8b25bab: Retrieving Media Token
[FOX] 3b70eb8b2ce846d1695e2ac3d8b25bab: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/home/rick/scripts/youtube-dl/youtube_dl/extractor/common.py", line 517, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/home/rick/scripts/youtube-dl/youtube_dl/YoutubeDL.py", line 2198, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)


```

Linux box 2 non working python3

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--ap-mso', 'Charter_Direct', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', 'https://www.fox.com/watch/3b70eb8b2ce846d1695e2ac3d8b25bab/', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.02.04
[debug] Python version 3.5.2 (CPython) - Linux-4.10.0-38-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 3.4.1, ffprobe 3.4.1
[debug] Proxy map: {}
[FOX] 3b70eb8b2ce846d1695e2ac3d8b25bab: Downloading JSON metadata
[FOX] 3b70eb8b2ce846d1695e2ac3d8b25bab: Retrieving Media Token
[FOX] 3b70eb8b2ce846d1695e2ac3d8b25bab: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/home/rick/env/python3/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 519, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/home/rick/env/python3/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 2199, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)


```

**Comment by Rick7C2** [comment]
@reubenbrown13 Your linux bos that is not working. Is it by chance located outside the USA?

I have found that --geo-verification-proxy URL doesn't cut it with fox. You must use --proxy URL


Using --geo-verification-proxy

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--force-ipv4', u'--geo-bypass', u'--geo-verification-proxy', u'PRIVATE', u'--ap-mso', u'Charter_Direct', u'--ap-username', u'PRIVATE', u'--ap-password', u'PRIVATE', u'--referer', u'http://www.fox.com/hells-kitchen', u'https://www.fox.com/watch/3b70eb8b2ce846d1695e2ac3d8b25bab/', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.01.27
[debug] Python version 2.7.12 (CPython) - Linux-4.10.0-38-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 3.4.1, ffprobe 3.4.1
[debug] Proxy map: {}
[FOX] 3b70eb8b2ce846d1695e2ac3d8b25bab: Downloading JSON metadata
[FOX] 3b70eb8b2ce846d1695e2ac3d8b25bab: Retrieving Media Token
[FOX] 3b70eb8b2ce846d1695e2ac3d8b25bab: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/home/rick/scripts/youtube-dl/youtube_dl/extractor/common.py", line 517, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/home/rick/scripts/youtube-dl/youtube_dl/YoutubeDL.py", line 2198, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)


```

Using --proxy

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--force-ipv4', u'--geo-bypass', u'--proxy', u'PRIVATE', u'--ap-mso', u'Charter_Direct', u'--ap-username', u'PRIVATE', u'--ap-password', u'PRIVATE', u'--referer', u'http://www.fox.com/hells-kitchen', u'https://www.fox.com/watch/3b70eb8b2ce846d1695e2ac3d8b25bab/', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.01.27
[debug] Python version 2.7.12 (CPython) - Linux-4.10.0-38-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 3.4.1, ffprobe 3.4.1
[debug] Proxy map: {u'http': u'http://ty45q9hel22hvjbm.duckdns.org:8118/', u'https': u'http://ty45q9hel22hvjbm.duckdns.org:8118/'}
[FOX] 3b70eb8b2ce846d1695e2ac3d8b25bab: Downloading JSON metadata
[FOX] 3b70eb8b2ce846d1695e2ac3d8b25bab: Retrieving Media Token
[FOX] 3b70eb8b2ce846d1695e2ac3d8b25bab: Downloading webpage
[uplynk:preplay] dab971c1f3a149ae9f0d60f466b72a7e: Downloading JSON metadata
[uplynk:preplay] dab971c1f3a149ae9f0d60f466b72a7e: Downloading m3u8 information
[uplynk:preplay] dab971c1f3a149ae9f0d60f466b72a7e: Downloading JSON metadata
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'http://content-ausw1.uplynk.com/dab971c1f3a149ae9f0d60f466b72a7e/k.m3u8'
[hlsnative] Downloading m3u8 manifest
ERROR: pycrypto not found. Please install it.
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/rick/scripts/youtube-dl/__main__.py", line 19, in <module>
    youtube_dl.main()
  File "/home/rick/scripts/youtube-dl/youtube_dl/__init__.py", line 465, in main
    _real_main(argv)
  File "/home/rick/scripts/youtube-dl/youtube_dl/__init__.py", line 455, in _real_main
    retcode = ydl.download(all_urls)
  File "/home/rick/scripts/youtube-dl/youtube_dl/YoutubeDL.py", line 1988, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/home/rick/scripts/youtube-dl/youtube_dl/YoutubeDL.py", line 795, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/rick/scripts/youtube-dl/youtube_dl/YoutubeDL.py", line 887, in process_ie_result
    new_result, download=download, extra_info=extra_info)
  File "/home/rick/scripts/youtube-dl/youtube_dl/YoutubeDL.py", line 849, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/home/rick/scripts/youtube-dl/youtube_dl/YoutubeDL.py", line 1622, in process_video_result
    self.process_info(new_info)
  File "/home/rick/scripts/youtube-dl/youtube_dl/YoutubeDL.py", line 1895, in process_info
    success = dl(filename, info_dict)
  File "/home/rick/scripts/youtube-dl/youtube_dl/YoutubeDL.py", line 1834, in dl
    return fd.download(name, info)
  File "/home/rick/scripts/youtube-dl/youtube_dl/downloader/common.py", line 361, in download
    return self.real_download(filename, info_dict)
  File "/home/rick/scripts/youtube-dl/youtube_dl/downloader/hls.py", line 68, in real_download
    self.report_error('pycrypto not found. Please install it.')
  File "/home/rick/scripts/youtube-dl/youtube_dl/downloader/common.py", line 163, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/home/rick/scripts/youtube-dl/youtube_dl/YoutubeDL.py", line 612, in report_error
    self.trouble(error_message, tb)
  File "/home/rick/scripts/youtube-dl/youtube_dl/YoutubeDL.py", line 574, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())


```

It seems it would have downloaded if I had pycrypto installed.

**Comment by reubenbrown13** [comment]
I am based in the US, so that should not be an issue.  Based on your suggestion tho, I did connect to vpnbook to see if trying to download via the vpn would make a difference and it seems to be working.  it is VERY slow.

**Comment by reubenbrown13** [comment]
This is quite frustrating and confusing.  It does work in windows when setup using Chocolatey.  Ubuntu 16.04 and 17.10 both fail to run.  What is the version of ffmpeg that is required?
