### ISSUE TITLE
[skynewsarabia:article] Unable to extract limelight media id

### ISSUE THREAD

**Issue by hicrop** [rg3/youtube-dl#15343]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.01.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

https://www.skynewsarabia.com/web/article/1014064/%D9%82%D9%88%D8%A7%D8%AA-%D8%A7%D9%84%D8%B4%D8%B1%D8%B9%D9%8A%D8%A9-%D8%AA%D8%B3%D9%8A%D8%B7%D8%B1-%D9%85%D9%86%D8%A7%D8%B7%D9%82-%D8%A7%D8%B3%D8%AA%D8%B1%D8%A7%D8%AA%D9%8A%D8%AC%D9%8A%D8%A9-%D8%A7%D9%84%D8%AC%D9%88%D9%81

```
ERROR: Unable to extract limelight media id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 438, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/skynewsarabia.py", line 105, in _real_extract
    'url': 'limelight:media:%s' % self._get_limelight_media_id(media_asset['videoUrl'][0]['url']),
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/skynewsarabia.py", line 19, in _get_limelight_media_id
    return self._search_regex(r'/media/[^/]+/([a-z0-9]{32})', url, 'limelight media id')
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 794, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract limelight media id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by dirkf** [comment]
The site switched from Limelight (now defunct) to JWPlatform.

Now, and probably since then, videos, though not playlists embedded in articles, can be extracted (using the ld+json block in the page) with `--force-generic`.
