### ISSUE TITLE
I am unable to download study material (video) from one of the web site 

### ISSUE THREAD

**Issue by subbu1969** [rg3/youtube-dl#15364]
I am unable to download study material (video) from one of the web site ,which i used to down load it for the last 5 day. But suddenly it shows error in downloading the video. 
1)I tried with --verbose 
2) updated youtube-dl (version 2018.01.18)
but still the issue exist. I am using Ubuntu 17.04 and it was working fine til yesterday. Internet connection is fine , cookies are also used

youtube-dl  --verbose --cookies cookies.txt --all-sub --prefer-ffmpeg https://www.lynda.com/Business-Skills-tutorials/Writing-Resume/429634-2.html  --username shankertvm1969@gmail.com --password Pr@n@v#07
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'--cookies', u'cookies.txt', u'--all-sub', u'--prefer-ffmpeg', u'https://www.lynda.com/Business-Skills-tutorials/Writing-Resume/429634-2.html', u'--username', u'PRIVATE', u'--password', u'PRIVATE']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.01.18
[debug] Python version 2.7.14 (CPython) - Linux-4.13.0-25-generic-x86_64-with-Ubuntu-17.10-artful
[debug] exe versions: avconv 3.3.4-2, avprobe 3.3.4-2, ffmpeg 3.3.4-2, ffprobe 3.3.4-2, rtmpdump 2.4
[debug] Proxy map: {}
[lynda:course] Downloading signin page
[lynda:course] 429634: Downloading course JSON
[download] Downloading playlist: Writing a Resume
[lynda:course] playlist Writing a Resume: Collected 45 video ids (downloading 45 of them)
[download] Downloading video 1 of 45
[lynda] Downloading signin page
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/__init__.py", line 465, in main
    _real_main(argv)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/__init__.py", line 455, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1988, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 795, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 994, in process_ie_result
    extra_info=extra)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 861, in process_ie_result
    extra_info=extra_info, download=False, process=False)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 437, in extract
    self.initialize()
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 395, in initialize
    self._real_initialize()
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/lynda.py", line 26, in _real_initialize
    self._login()
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/lynda.py", line 72, in _login
    self._SIGNIN_URL, None, 'Downloading signin page')
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 632, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 541, in _download_webpage_handle
    content = self._webpage_read_content(urlh, url_or_request, video_id, note, errnote, fatal, encoding=encoding)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 591, in _webpage_read_content
    webpage_bytes = urlh.read()
  File "/usr/lib/python2.7/socket.py", line 355, in read
    data = self._sock.recv(rbufsize)
  File "/usr/lib/python2.7/httplib.py", line 597, in read
    s = self.fp.read(amt)
  File "/usr/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/usr/lib/python2.7/ssl.py", line 766, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 653, in read
    v = self._sslobj.read(len)
socket.error: [Errno 104] Connection reset by peer

**Comment by dstftw** [comment]
Most likely a network issue on your side.
