### ISSUE TITLE
PBS - Some Videos Error Out - AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by SPDurkee** [rg3/youtube-dl#15373]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.01.18*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.01.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://www.pbs.org/wgbh/roadshow/watch/episode/2105-indianapolis-hour-2/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.01.18
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.16299
[debug] exe versions: ffmpeg N-89395-g71421f382f, ffprobe N-89395-g71421f382f, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Using fake IP 3.124.15.82 (US) as X-Forwarded-For.
[pbs] Downloading JSON metadata
[pbs] 2105-indianapolis-hour-2: Downloading webpage
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpun_444l4\build\youtube_dl\__init__.py", line 465, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpun_444l4\build\youtube_dl\__init__.py", line 455, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpun_444l4\build\youtube_dl\YoutubeDL.py", line 1988, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpun_444l4\build\youtube_dl\YoutubeDL.py", line 784, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpun_444l4\build\youtube_dl\extractor\common.py", line 438, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpun_444l4\build\youtube_dl\extractor\pbs.py", line 477, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpun_444l4\build\youtube_dl\extractor\pbs.py", line 461, in _extract_webpage
AttributeError: 'NoneType' object has no attribute 'group'
...
<end of log>
```

### Description of your *issue*, suggested solution and other information

Some videos on PBS work and some don't the ones that don't result in a AttributeError: 'NoneType' object has no attribute 'group' error.
e.g. http://www.pbs.org/wgbh/roadshow/watch/episode/2105-indianapolis-hour-2/

**Comment by bberberov** [comment]
I think this is a wider issue with PBS, but I'm not up to date.  Hopefully someone else can follow up.

```console
...
[debug] Command-line args: [u'-v', u'-F', u'https://www.pbs.org/video/scanning-the-pyramids-hqvc7x/']
...
[debug] Proxy map: {}
[debug] Using fake IP 3.59.196.255 (US) as X-Forwarded-For.
[pbs] Downloading JSON metadata
[pbs] scanning-the-pyramids-hqvc7x: Downloading webpage
[pbs] Downloading widget/partnerplayer page
WARNING: Unable to download webpage: HTTP Error 404: Not Found
[pbs] Downloading portalplayer page
WARNING: Unable to download webpage: HTTP Error 404: Not Found
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 437, in extract
    ie_result = self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/pbs.py", line 589, in _real_extract
    self._sort_formats(formats)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 1075, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by AngelBlue01** [comment]
I have the same issue.

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'http://www.pbs.org/wnet/nature/animals-cameras-episode-1/15926/', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.02.26
[debug] Python version 2.7.13 (CPython) - Linux-4.4.114-42-default-x86_64-with-SuSE-42.3-x86_64
[debug] exe versions: ffmpeg 3.4.2, ffprobe 3.4.2
[debug] Proxy map: {}
[debug] Using fake IP 3.249.111.18 (US) as X-Forwarded-For.
[pbs] Downloading JSON metadata
[pbs] 15926: Downloading webpage
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 471, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 461, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1989, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 785, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 440, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/pbs.py", line 477, in _real_extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/pbs.py", line 461, in _extract_webpage
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by benfishbus** [comment]
I did not experience this error message with PBS until recently, and now am getting it on virtually every video I try to download.

**Comment by Urgau** [comment]
The issue is still here. Try with : https://www.pbs.org/wgbh/masterpiece/episodes/victoria-s2-e7/
