### ISSUE TITLE
EOFError on Twitter

### ISSUE THREAD

**Issue by eliblanco87** [rg3/youtube-dl#15383]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.01.21** (Windows precompiled exe)
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Bug report (encountered problems with youtube-dl)

---

There seems to be a problem with specific Twitter videos:
```

$ youtube-dl --verbose https://twitter.com/NBA/status/942826674680246272
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://twitter.com/NBA/status/942826674680246272']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2018.01.21
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[twitter] 942826674680246272: Downloading webpage
[twitter:card] 942826674680246272: Downloading webpage
[twitter:card] 942826674680246272: Downloading XML
[twitter:card] 942826674680246272: Downloading m3u8 information
[twitter:card] 942826674680246272: Downloading mobile webpage
[twitter:card] 942826674680246272: Downloading main script
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpm93u0ksi\build\youtube_dl\__init__.py", line 465, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpm93u0ksi\build\youtube_dl\__init__.py", line 455, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpm93u0ksi\build\youtube_dl\YoutubeDL.py", line 1988, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpm93u0ksi\build\youtube_dl\YoutubeDL.py", line 795, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpm93u0ksi\build\youtube_dl\YoutubeDL.py", line 861, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpm93u0ksi\build\youtube_dl\YoutubeDL.py", line 784, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpm93u0ksi\build\youtube_dl\extractor\common.py", line 438, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpm93u0ksi\build\youtube_dl\extractor\twitter.py", line 223, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpm93u0ksi\build\youtube_dl\extractor\twitter.py", line 146, in _extract_mobile_formats
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpm93u0ksi\build\youtube_dl\extractor\common.py", line 632, in _download_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpm93u0ksi\build\youtube_dl\extractor\common.py", line 537, in _download_webpage_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpm93u0ksi\build\youtube_dl\extractor\common.py", line 517, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpm93u0ksi\build\youtube_dl\YoutubeDL.py", line 2198, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpm93u0ksi\build\youtube_dl\utils.py", line 980, in http_response
  File "C:\Python\Python34\lib\gzip.py", line 360, in read
  File "C:\Python\Python34\lib\gzip.py", line 449, in _read
  File "C:\Python\Python34\lib\gzip.py", line 482, in _read_eof
  File "C:\Python\Python34\lib\gzip.py", line 286, in _read_exact
EOFError: Compressed file ended before the end-of-stream marker was reached
```

**Comment by dstftw** [comment]
Most likely an issue with your network.

**Comment by eliblanco87** [comment]
It worked in the same network but on a Debian box... how strange

**Comment by ajayinvictus10** [comment]
I had the same issue,I found a workaround by adding a custom header
youtube-dl   --add-header Accept-Encoding:deflate [url]
