### ISSUE TITLE
[tbs] Some series not working

### ISSUE THREAD

**Issue by StevenDTX** [rg3/youtube-dl#15395]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.01.21*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2018.01.21**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
---

```
E:\>youtube-dl http://www.tntdrama.com/shows/good-behavior/season-2/episode-1/explicit-the-heart-attack-is-the-best-way --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['http://www.tntdrama.com/shows/good-behavior/season-2/episode-1/explicit-the-heart-attack-is-the-best-way', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.01.21
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-89395-g71421f382f, ffprobe N-72383-g7206b94, rtmpdump 2.4
[debug] Proxy map: {}
[TBS] explicit-the-heart-attack-is-the-best-way: Downloading webpage
[TBS] 64481b6ad61c8e6437560c6a356ebb811412832c: Downloading JSON metadata
[TBS] 64481b6ad61c8e6437560c6a356ebb811412832c: Downloading XML
ERROR: Content: invalid video id
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpm93u0ksi\build\youtube_dl\YoutubeDL.py", line 784, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpm93u0ksi\build\youtube_dl\extractor\common.py", line 438, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpm93u0ksi\build\youtube_dl\extractor\tbs.py", line 65, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpm93u0ksi\build\youtube_dl\extractor\turner.py", line 40, in _add_akamai_spe_token
youtube_dl.utils.ExtractorError: Content: invalid video id...

```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
Not working:
 http://www.tntdrama.com/shows/good-behavior/season-2/episode-1/explicit-the-heart-attack-is-the-best-way
http://www.tbs.com/shows/the-detour/season-2/episode-2/the-club

Working:
http://www.tbs.com/shows/seinfeld/season-5/episode-2/the-puffy-shirt
http://www.tbs.com/shows/married-with-children/season-5/episode-6/kelly-bounces-back

---

### Description of your *issue*, suggested solution and other information

ERROR: Content: invalid video id on some series.  I have tried it with and without --ap-mso credentials.

**Comment by StevenDTX** [comment]
@remitamine 

That does start downloading, but it downloads only the first segment of the video. This is the same error you fixed last month.

```

C:\support\Python36-32\Lib\youtube-dl-master>python -m youtube-dl --restrict-filenames --continue --no-check-certificate --hls-prefer-native --verbose http://www.tbs.com/shows/the-detour/season-2/episode-1/the-city
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--restrict-filenames', '--continue', '--no-check-certificate', '--hls-prefer-native', '--verbose', 'http://www.tbs.com/shows/the-detour/season-2/episode-1/the-city']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2018.01.21
[debug] Python version 3.6.4 (CPython) - Windows-10-10.0.14393-SP0
[debug] exe versions: ffmpeg N-89395-g71421f382f, ffprobe N-72383-g7206b94, rtmpdump 2.4
[debug] Proxy map: {}
[TBS] the-city: Downloading webpage
[TBS] b3cbf49b64ed6fb1f2d2b10a4e810e173d943812: Downloading JSON metadata
[TBS] b3cbf49b64ed6fb1f2d2b10a4e810e173d943812: Downloading XML
[TBS] b3cbf49b64ed6fb1f2d2b10a4e810e173d943812: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://tve.cdn.turner.com/tbs/102334c0947640036ebfc5580342d09f/layer7/layer7_bk.m3u8?hdntl=exp=1516859481~acl=%2ftbs%2f102334c0947640036ebfc5580342d09f%2f*~hmac=3299b61a772c96bc1ed21e0c3b2cd0ced3d0139586b832a2527480a6d07dc25f'
[hlsnative] Downloading m3u8 manifest
WARNING: hlsnative has detected features it does not support, extraction will be delegated to ffmpeg
[download] Destination: The_City-b3cbf49b64ed6fb1f2d2b10a4e810e173d943812.mp4
[debug] ffmpeg command line: ffmpeg -y -loglevel verbose -headers "User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/47.0 (Chrome)
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Encoding: gzip, deflate
Accept-Language: en-us,en;q=0.5
Cookie: hdntl=exp=1516859481~acl=%2ftbs%2f102334c0947640036ebfc5580342d09f%2f*~hmac=3299b61a772c96bc1ed21e0c3b2cd0ced3d0139586b832a2527480a6d07dc25f
" -i "https://tve.cdn.turner.com/tbs/102334c0947640036ebfc5580342d09f/layer7/layer7_bk.m3u8?hdntl=exp=1516859481~acl=%2ftbs%2f102334c0947640036ebfc5580342d09f%2f*~hmac=3299b61a772c96bc1ed21e0c3b2cd0ced3d0139586b832a2527480a6d07dc25f" -c copy -f mp4 "-bsf:a" aac_adtstoasc "file:The_City-b3cbf49b64ed6fb1f2d2b10a4e810e173d943812.mp4.part"
ffmpeg version N-89395-g71421f382f Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 7.2.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-cuda --enable-cuvid --enable-d3d11va --enable-nvenc --enable-dxva2 --enable-avisynth --enable-libmfx
  libavutil      56.  5.100 / 56.  5.100
  libavcodec     58.  6.102 / 58.  6.102
  libavformat    58.  2.103 / 58.  2.103
  libavdevice    58.  0.100 / 58.  0.100
  libavfilter     7.  6.100 /  7.  6.100
  libswscale      5.  0.101 /  5.  0.101
  libswresample   3.  0.101 /  3.  0.101
  libpostproc    55.  0.100 / 55.  0.100
[hls,applehttp @ 00000213060fa520] HLS request for url 'https://tve.cdn.turner.com/tbs/102334c0947640036ebfc5580342d09f/layer7/seg-0_00000.ts', offset 0, playlist 0
[hls,applehttp @ 00000213060fa520] Opening 'https://tve.cdn.turner.com/tbs/102334c0947640036ebfc5580342d09f/layer7/seg.key' for reading
[hls,applehttp @ 00000213060fa520] Opening 'crypto+https://tve.cdn.turner.com/tbs/102334c0947640036ebfc5580342d09f/layer7/seg-0_00000.ts' for reading
[h264 @ 0000021306e63e80] Reinit context to 1920x1088, pix_fmt: yuv420p
Input #0, hls,applehttp, from 'https://tve.cdn.turner.com/tbs/102334c0947640036ebfc5580342d09f/layer7/layer7_bk.m3u8?hdntl=exp=1516859481~acl=%2ftbs%2f102334c0947640036ebfc5580342d09f%2f*~hmac=3299b61a772c96bc1ed21e0c3b2cd0ced3d0139586b832a2527480a6d07dc25f':
  Duration: 00:21:09.13, start: 1.466733, bitrate: 0 kb/s
  Program 0
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: h264 (High), 1 reference frame ([27][0][0][0] / 0x001B), yuv420p(left), 1920x1080 (1920x1088) [SAR 1:1 DAR 16:9], Closed Captions, 29.97 fps, 29.97 tbr, 90k tbn, 59.94 tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
Output #0, mp4, to 'file:The_City-b3cbf49b64ed6fb1f2d2b10a4e810e173d943812.mp4.part':
  Metadata:
    encoder         : Lavf58.2.103
    Stream #0:0: Video: h264 (High), 1 reference frame (avc1 / 0x31637661), yuv420p(left), 1920x1080 (0x0) [SAR 1:1 DAR 16:9], q=2-31, 29.97 fps, 29.97 tbr, 90k tbn, 90k tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
[hls,applehttp @ 00000213060fa520] HLS request for url 'https://tve.cdn.turner.com/tbs/102334c0947640036ebfc5580342d09f/layer7/seg-0_00001.ts', offset 0, playlist 0
[hls,applehttp @ 00000213060fa520] Opening 'crypto+https://tve.cdn.turner.com/tbs/102334c0947640036ebfc5580342d09f/layer7/seg-0_00001.ts' for reading
[hls,applehttp @ 00000213060fa520] HLS request for url 'https://tve.cdn.turner.com/tbs/102334c0947640036ebfc5580342d09f/layer7/seg-0_00002.ts', offset 0, playlist 0
[hls,applehttp @ 00000213060fa520] Opening 'crypto+https://tve.cdn.turner.com/tbs/102334c0947640036ebfc5580342d09f/layer7/seg-0_00002.ts' for reading
frame=  447 fps=336 q=-1.0 Lsize=    7623kB time=00:00:14.81 bitrate=4215.1kbits/s speed=11.1x
video:7383kB audio:222kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.236282%
Input file #0 (https://tve.cdn.turner.com/tbs/102334c0947640036ebfc5580342d09f/layer7/layer7_bk.m3u8?hdntl=exp=1516859481~acl=%2ftbs%2f102334c0947640036ebfc5580342d09f%2f*~hmac=3299b61a772c96bc1ed21e0c3b2cd0ced3d0139586b832a2527480a6d07dc25f):
  Input stream #0:0 (video): 447 packets read (7560429 bytes);
  Input stream #0:1 (audio): 621 packets read (231237 bytes);
  Total: 1068 packets (7791666 bytes) demuxed
Output file #0 (file:The_City-b3cbf49b64ed6fb1f2d2b10a4e810e173d943812.mp4.part):
  Output stream #0:0 (video): 447 packets muxed (7560429 bytes);
  Output stream #0:1 (audio): 621 packets muxed (226890 bytes);
  Total: 1068 packets (7787319 bytes) muxed
Exiting normally, received signal 2.

ERROR: Interrupted by user

```

Thanks!

**Comment by remitamine** [comment]
@StevenDTX i can't actually play the video in the browser, but the requests made by youtube-dl are similar to the ones that i see in browser's console.
and also the metadata exposed by tbs has the same duration as the one reported by ffmpeg.

**Comment by astral2k5** [comment]
@remitamine, @StevenDTX

I've tried a few videos from TBS, TNT and I get from FFMPEG a lot of:

[mp4 @ 0x7f897a01bc00] Non-monotonous DTS in output stream 0:0; previous: 598061, current: 467644; changing to 598062. This may result in incorrect timestamps in the output file.
[mp4 @ 0x7f897a01bc00] Non-monotonous DTS in output stream 0:0; previous: 598062, current: 468044; changing to 598063. This may result in incorrect timestamps in the output file.
[mp4 @ 0x7f897a01bc00] Non-monotonous DTS in output stream 0:0; previous: 598063, current: 468444; changing to 598064. This may result in incorrect timestamps in the output file.

And the output mp4 file has the duration of the first segment of the video, sometimes is longer but not the full video:

The M3U8 manifest has some discontinuity tags, which I think are the reason of this issue and FFMPEG seems it doesn't support it. I've tried the native-hls downloader the ouput file has almost same size as witth FFMPEG but the duration is still just first segment

#EXT-X-DISCONTINUITY
#EXT-X-CUE-OUT:0
