### ISSUE TITLE
Add ElTrece support

### ISSUE THREAD

**Issue by ciroiriarte** [rg3/youtube-dl#15410]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.01.21*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2018.01.21**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.eltrecetv.com.ar/programas/simona/capitulos-completos/capitulo-2_099427']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.01.21
[debug] Python version 2.7.13 (CPython) - Linux-4.4.104-18.44-default-x86_64-with-SuSE-42.2-x86_64
[debug] exe versions: ffmpeg 3.3.4, ffprobe 3.3.4
[debug] Proxy map: {}
[generic] capitulo-2_099427: Requesting header
WARNING: Falling back on generic information extractor.
[generic] capitulo-2_099427: Downloading webpage
[generic] capitulo-2_099427: Extracting information
ERROR: Unsupported URL: https://www.eltrecetv.com.ar/programas/simona/capitulos-completos/capitulo-2_099427
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2192, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2541, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2530, in _XML
    parser.feed(text)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 4, column 124
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 438, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3108, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.eltrecetv.com.ar/programas/simona/capitulos-completos/capitulo-2_099427

```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Programs index: https://www.eltrecetv.com.ar/capitulos-completos
- Episodes from a single program: https://www.eltrecetv.com.ar/las-estrellas/capitulos-completos
- Episode: https://www.eltrecetv.com.ar/programas/las-estrellas/capitulos-completos/capitulo-171_099424
- Episode link provided for embedding: http://www.eltrecetv.com.ar/node/99424/player.html

---

### Description of your *issue*, suggested solution and other information

This is a TV station from Argentina, which publishes already aired shows in UHD.

**Comment by ciroiriarte** [comment]
There's some work here that might be of interest:

https://github.com/jcodagnone/roku-ar/blob/master/eltrece.py
https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/eltrecetv.py

**Comment by marium0505** [comment]
Would love to see support for eltrecetv added!
