### ISSUE TITLE
[Pro7sat1] Not get a Video ID download faild

### ISSUE THREAD

**Issue by kiam001** [rg3/youtube-dl#15436]
youtube-dl https://www.prosiebenmaxx.de/anime/psycho-pass/videos/17-folge-7-was-violette-orchideen-symbolisieren-ganze-folge -C --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.prosiebenmaxx.de/anime/psycho-pass/videos/17-folge-7-was-violette-orchideen-symbolisieren-ganze-folge', '-C', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.01.21
[debug] Python version 3.6.4 (CPython) - Linux-3.18.31-perf-g517c70f-00106-g2ab6438-armv7l-with-libc
[debug] exe versions: ffmpeg 3.4.1, ffprobe 3.4.1
[debug] Proxy map: {}
[debug] Public IP address: 89.0.61.151
[prosiebensat1] anime/psycho-pass/videos/17-folge-7-was-violette-orchideen-symbolisieren-ganze-folge: Downloading webpage
ERROR: Unable to extract clip id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 438, in extract
    ie_result = self._real_extract(url)
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/youtube_dl/extractor/prosiebensat1.py", line 443, in _real_extract
    return self._extract_clip(url, webpage)
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/youtube_dl/extractor/prosiebensat1.py", line 388, in _extract_clip
    self._CLIPID_REGEXES, webpage, 'clip id')
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 803, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 794, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract clip id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
Already fixed.

**Comment by kiam001** [comment]
How to load the fix?

**Comment by dstftw** [comment]
Run from sources or wait for the next release.
