### ISSUE TITLE
[bilibili] RegexNotFoundError: Unable to extract player parameters

### ISSUE THREAD

**Issue by thomco** [rg3/youtube-dl#15430]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.01.21**
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

```
youtube-dl https://www.bilibili.com/video/av16492411/
[BiliBili] 16492411: Downloading webpage
ERROR: Unable to extract player parameters; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

(base) C:\Users\Thomas\temp>youtube-dl -v https://www.bilibili.com/video/av16492411/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.bilibili.com/video/av16492411/']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2018.01.21
[debug] Python version 3.6.4 (CPython) - Windows-10-10.0.16299-SP0
[debug] exe versions: ffmpeg 3.2.4, ffprobe 3.2.4
[debug] Proxy map: {}
[BiliBili] 16492411: Downloading webpage
ERROR: Unable to extract player parameters; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\users\thomas\anaconda3\lib\site-packages\youtube_dl\YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "c:\users\thomas\anaconda3\lib\site-packages\youtube_dl\extractor\common.py", line 438, in extract
    ie_result = self._real_extract(url)
  File "c:\users\thomas\anaconda3\lib\site-packages\youtube_dl\extractor\bilibili.py", line 98, in _real_extract
    webpage, 'player parameters'))['cid'][0]
  File "c:\users\thomas\anaconda3\lib\site-packages\youtube_dl\extractor\common.py", line 794, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract player parameters;

```

---

**Comment by Jicksaw** [comment]
It would seem some pages don't have cid defined in EmbedPlayer. I'm looking into alternatives.

**Comment by SnowOnion** [comment]
+1, still `ERROR: Unable to extract player parameters;` in youtube-dl version `2018.03.03` when downloading https://www.bilibili.com/video/av19850361/ .

```
youtube-dl --verbose https://www.bilibili.com/video/av19850361/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.bilibili.com/video/av19850361/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.03.03
[debug] Python version 2.7.13 (CPython) - Darwin-17.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.2.4, ffprobe 3.2.4
[debug] Proxy map: {}
[BiliBili] 19850361: Downloading webpage
ERROR: Unable to extract player parameters; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 785, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/bilibili.py", line 98, in _real_extract
    webpage, 'player parameters'))['cid'][0]
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 796, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract player parameters; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
