### ISSUE TITLE
Unable to download a specific YouTube Red video

### ISSUE THREAD

**Issue by nyuszika7h** [rg3/youtube-dl#15439]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.01.27*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.01.27**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--ignore-config', '-v', '--cookies', 'youtube-cookies.txt', 'https://www.youtube.com/watch?v=ET2YuRb004w']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.01.27
[debug] Python version 3.6.1+ (CPython) - Linux-4.9.0-3-amd64-x86_64-with-debian-9.3
[debug] exe versions: ffmpeg 3.2.9-1, ffprobe 3.2.9-1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] ET2YuRb004w: Downloading webpage
[youtube] ET2YuRb004w: Downloading video info webpage
ERROR: ET2YuRb004w: YouTube said: This video is not available.
Traceback (most recent call last):
  File "/home/nyuszika7h/.local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "/home/nyuszika7h/.local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 438, in extract
    ie_result = self._real_extract(url)
  File "/home/nyuszika7h/.local/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1620, in _real_extract
    expected=True, video_id=video_id)
youtube_dl.utils.ExtractorError: ET2YuRb004w: YouTube said: This video is not available.
```

---

### Description of your *issue*, suggested solution and other information
A certain YouTube Red video (https://www.youtube.com/watch?v=ET2YuRb004w) that plays fine in Chrome can't be downloaded by youtube-dl. I'm using the cookies of my account with an active subscription, and other vidos still work.

**Comment by asm95** [comment]
This happens to also to me when I'm trying to download some kpop music from https://www.youtube.com/watch?v=c7rCyll5AeY but it gives me _"HTTP Error 500: Internal Server Error"_
