### ISSUE TITLE
CNET/CBS videos issues

### ISSUE THREAD

**Issue by risner** [rg3/youtube-dl#15451]
- [ X ] I've **verified** and **I assure** that I'm running youtube-dl **2018.01.27**
- [ X ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ X ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ X ] Bug report (encountered problems with youtube-dl)
- [ X ] Site support request (request for adding support for a new site)
---
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.cnet.com/videos/the-seabin-project-aims-to-rid-the-oceans-of-plastic/']
[debug] Encodings: locale utf-8, fs utf-8, out utf-8, pref utf-8
[debug] youtube-dl version 2018.01.27
[debug] Python version 2.7.14 (CPython) - Darwin-17.4.0-x86_64-i386-64bit
[debug] exe versions: avconv 11.3, avprobe 11.3, ffmpeg 3.4.1, ffprobe 3.4.1
[debug] Proxy map: {}
[CBSInteractive] the-seabin-project-aims-to-rid-the-oceans-of-plastic: Downloading webpage
ERROR: Unable to extract data json; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/opt/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "/opt/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 438, in extract
    ie_result = self._real_extract(url)
  File "/opt/local/bin/youtube-dl/youtube_dl/extractor/cbsinteractive.py", line 79, in _real_extract
    webpage, 'data json')
  File "/opt/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 803, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/opt/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 794, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract data json; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.cnet.com/videos/step-inside-julian-assanges-office/']
[debug] Encodings: locale utf-8, fs utf-8, out utf-8, pref utf-8
[debug] youtube-dl version 2018.01.27
[debug] Python version 2.7.14 (CPython) - Darwin-17.4.0-x86_64-i386-64bit
[debug] exe versions: avconv 11.3, avprobe 11.3, ffmpeg 3.4.1, ffprobe 3.4.1
[debug] Proxy map: {}
[CBSInteractive] step-inside-julian-assanges-office: Downloading webpage
ERROR: Unable to extract data json; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/opt/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "/opt/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 438, in extract
    ie_result = self._real_extract(url)
  File "/opt/local/bin/youtube-dl/youtube_dl/extractor/cbsinteractive.py", line 79, in _real_extract
    webpage, 'data json')
  File "/opt/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 803, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/opt/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 794, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract data json; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
---
Most of the CNET/CBS videos studder when watched in a browser for me on either ISP I have available. I use Youtube-DL to download and stream to my TV via Beamer.app on MacOS.

Several CNET vidoes of CBS Interactive clips report this error when running youtube-dl:
Unable to extract data json

youtube-dl "https://www.cnet.com/videos/step-inside-julian-assanges-office/"
[CBSInteractive] step-inside-julian-assanges-office: Downloading webpage
ERROR: Unable to extract data json; please report this issue ...

youtube-dl "https://www.cnet.com/videos/the-seabin-project-aims-to-rid-the-oceans-of-plastic/"
[CBSInteractive] the-seabin-project-aims-to-rid-the-oceans-of-plastic: Downloading webpage
ERROR: Unable to extract data json; please report this issue ...

**Comment by risner** [comment]
If it helps, they should have youtube links like the seabin youtube link:
https://www.youtube.com/watch?v=ySp7HKD7jaw
