### ISSUE TITLE
RTL-XL extractor stopped working...

### ISSUE THREAD

**Issue by MatrixView** [rg3/youtube-dl#15459]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.01.27**
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Bug report (encountered problems with youtube-dl)

---

The extractor for RTL-XL doesn't seem to work anymore...  also for older/last weeks videos which downloaded just fine then.

```
youtube-dl -v https://www.rtl.nl/video/206a0db0-9bc8-3a32-bda3-e9b3a9d4d377/

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.rtl.nl/video/206a0db0-9bc8-3a32-bda3-e9b3a9d4d377/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.01.27
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-67388-g37425fc, ffprobe N-67388-g37425fc, rtmpdump 2.4-47-gc26c541
[debug] Proxy map: {}
[rtl.nl] 206a0db0-9bc8-3a32-bda3-e9b3a9d4d377: Downloading JSON metadata
[rtl.nl] 206a0db0-9bc8-3a32-bda3-e9b3a9d4d377: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://pg.us.rtl.nl/rtlxl/network/nettv/progressive/components/videorecorder/30/301978/402905/206a0db0-9bc8-3a32-bda3-e9b3a9d4d377.ssm/206a0db0-9bc8-3a32-bda3-e9b3a9d4d377.mp4'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpn97fzem4\build\youtube_dl\YoutubeDL.py", line 1895, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpn97fzem4\build\youtube_dl\YoutubeDL.py", line 1834, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpn97fzem4\build\youtube_dl\downloader\common.py", line 361, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpn97fzem4\build\youtube_dl\downloader\http.py", line 286, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpn97fzem4\build\youtube_dl\downloader\http.py", line 74, in establish_connection
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpn97fzem4\build\youtube_dl\YoutubeDL.py", line 2198, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
```

Thanx in advance!

**Comment by dofl** [comment]
Same here with the latest version 2018.01.27 of youtube-dl. Tried two different IP's, one of which normally never connects to RTL-XL, so it's not a banned IP address.

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.01.27
[debug] Python version 2.7.12 (CPython) - Linux-4.4.0-112-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: none
[rtl.nl] 56bec0be-b745-3754-8b40-5010914b25f1: Downloading JSON metadata
[rtl.nl] 56bec0be-b745-3754-8b40-5010914b25f1: Downloading m3u8 information
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on u'http://pg.us.rtl.nl/rtlxl/network/nettv/progressive/components/actueel/rtlnieuws/390569/2018w05/56bec0be-b745-3754-8b40-5010914b25f1.ssm/56bec0be-b745-3754-8b40-5010914b25f1.mp4'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1895, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1834, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 361, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 286, in real_download
    establish_connection()
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 74, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2198, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden
```
