### ISSUE TITLE
Please add https://www.universalmusic.fr support

### ISSUE THREAD

**Issue by kalon33** [rg3/youtube-dl#15463]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.01.21**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Site support request (request for adding support for a new site)

Full verbose output:

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.universalmusic.fr/artiste/10732-calogero/videos', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.01.21
[debug] Python version 3.6.3 (CPython) - Linux-4.13.0-31-generic-x86_64-with-Ubuntu-17.10-artful
[debug] exe versions: ffmpeg 3.3.4-2, ffprobe 3.3.4-2, rtmpdump 2.4
[debug] Proxy map: {}
[generic] videos: Requesting header
WARNING: Falling back on generic information extractor.
[generic] videos: Downloading webpage
[generic] videos: Extracting information
ERROR: Unsupported URL: https://www.universalmusic.fr/artiste/10732-calogero/videos
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 438, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/generic.py", line 3108, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.universalmusic.fr/artiste/10732-calogero/videos
```

---
Please add support for https://www.universalmusic.fr, for example, here is a video list:

Playlist: https://www.universalmusic.fr/artiste/10732-calogero/videos

Here is another one:
Playlist: https://www.universalmusic.fr/artiste/10732-calogero/videos?page_more=1

And another:

Playlist: https://www.universalmusic.fr/artiste/10732-calogero/videos?page_more=2

And videos:

Video: https://www.universalmusic.fr/artiste/10732-calogero/videos/39415-fondamental#contentPart
Video: https://www.universalmusic.fr/artiste/10732-calogero/videos/25041-le-monde-moderne#contentPart
Video: https://www.universalmusic.fr/artiste/10732-calogero/videos/20076-prendre-racine-live-symphonique#contentPart

**Comment by kalon33** [comment]
@dstftw dupe of which one? Currently that doesn't work... And I can't find any open issue or PR dealing with this...
