### ISSUE TITLE
401 problem, yet I gave my login info... What's wrong?

### ISSUE THREAD

**Issue by caravalo91** [rg3/youtube-dl#15540]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.02.08*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.02.08**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-u', 'PRIVATE', '-p', 'PRIVATE', '--hls-prefer-native', 'https://hlsevent-aksc.ams1.media.eurosportplayer.com/hdnts=exp=1518275058~acl=/*~id=3d9225b7-d437-42db-bb76-ded52280e39f-14-f4f8093e34e4532681f1c540ade9bffb30f86034~hmac=4ca58fb00334cde28d68d63da1fec9960bd25c224ee81a3d955a437c6c6638ce/b5631821d732cd7cf7e096c2cfc95cea/ls01/eurosport/event/2018/02/05/Arminia_Bielefeld_1_FC_Un_20180205_1517783310425/3500K/3500_complete-trimmed.m3u8']
[debug] Encodings: locale cp1250, fs mbcs, out cp852, pref cp1250
[debug] youtube-dl version 2018.02.08
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-89951-g3caecf7ce8, ffprobe N-89951-g3caecf7ce8
[debug] Proxy map: {}
[generic] 3500_complete-trimmed: Requesting header
[generic] 3500_complete-trimmed: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://hlsevent-aksc.ams1.media.eurosportplayer.com/hdnts=exp=1518275058~acl=/*~id=3d9225b7-d437-42db-bb76-ded52280e39f-14-f4f8093e34e4532681f1c540ade9bffb30f86034~hmac=4ca58fb00334cde28d68d63da1fec9960bd25c224ee81a3d955a437c6c6638ce/b5631821d732cd7cf7e096c2cfc95cea/ls01/eurosport/event/2018/02/05/Arminia_Bielefeld_1_FC_Un_20180205_1517783310425/3500K/3500_complete-trimmed.m3u8'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 1550
[download] Destination: 3500_complete-trimmed-3500_complete-trimmed.mp4
[download]   0.1% of ~3.68GiB at Unknown speed ETA Unknown ETAERROR: unable to download video data: HTTP Error 401: Unauthorized
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpn4uo9muj\build\youtube_dl\YoutubeDL.py", line 1896, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpn4uo9muj\build\youtube_dl\YoutubeDL.py", line 1835, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpn4uo9muj\build\youtube_dl\downloader\common.py", line 364, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpn4uo9muj\build\youtube_dl\downloader\hls.py", line 167, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpn4uo9muj\build\youtube_dl\YoutubeDL.py", line 2199, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
urllib.error.HTTPError: HTTP Error 401: Unauthorized
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Hi there!
I plan to download from Eurosport Player, and I understand that the site is not supported (yet?), however I can manage to find the m3u8 files where I can download the videos from (using the videodownloadhelper browser extension). The problem is, no matter I add my login info to the command line (I use the -u, -p parameters, the login parameters to the site itself is an email, and a password), it gives the error that you can see in the log.
Am I doing something wrong (maybe using the-u, -p parameters in a wrong way), or why does it give this error? What other parameters should I add to the command line to make the download start?

(Some other info I should add: all the grabbed urls have one similarity (in my case: "id=3d9225b7-d437-42db-bb76-ded52280e39f-14-f4f8093e34e4532681f1c540ade9bffb30f86034"), the other parts are different always different.)

**Comment by dstftw** [comment]
Obviously you did not provide required headers/query/etc. See what browser does and mimic its behavior.
