### ISSUE TITLE
Request for adding URL of a university video catalog

### ISSUE THREAD

**Issue by ipers** [rg3/youtube-dl#15573]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.02.11*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ ] I've **verified** and **I assure** that I'm running youtube-dl **2018.02.11**
> youtube-dl --version
> 2014.02.17
> sudo apt-get install --only-upgrade youtube-dl
>youtube-dl is already the newest version.

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser
> https://www.uninettuno.tv/Video.aspx?v=594

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.uninettuno.tv/Video.aspx?v=594
- Playlist: https://www.uninettuno.tv/Canale.aspx?t=gruppo&g=1
> The site content seems to be copyrighted but is open and available on the web without registration

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

**Comment by clampak** [comment]
Your youtube-dl is seriously out of date.  You need to update that.  However, these links are still unsupported with the current version.

`$ youtube-dl -v "https://www.uninettuno.tv/Canale.aspx?t=gruppo&g=1"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.uninettuno.tv/Canale.aspx?t=gruppo&g=1']
[debug] Encodings: locale cp1252, fs utf-8, out cp1252, pref cp1252
[debug] youtube-dl version 2018.02.11
[debug] Python version 3.6.4 (CPython) - Windows-10-10.0.16299-SP0
[debug] exe versions: ffmpeg N-89951-g3caecf7ce8, ffprobe N-89951-g3caecf7ce8
[debug] Proxy map: {}
[generic] Canale: Requesting header
WARNING: Falling back on generic information extractor.
[generic] Canale: Downloading webpage
[generic] Canale: Extracting information
ERROR: Unsupported URL: https://www.uninettuno.tv/Canale.aspx?t=gruppo&g=1
Traceback (most recent call last):
  File "c:\python\python36-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 785, in extract_info
    ie_result = ie.extract(url)
  File "c:\python\python36-32\lib\site-packages\youtube_dl\extractor\common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "c:\python\python36-32\lib\site-packages\youtube_dl\extractor\generic.py", line 3111, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.uninettuno.tv/Canale.aspx?t=gruppo&g=1
`
`$ youtube-dl -v "https://www.uninettuno.tv/Video.aspx?v=594"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.uninettuno.tv/Video.aspx?v=594']
[debug] Encodings: locale cp1252, fs utf-8, out cp1252, pref cp1252
[debug] youtube-dl version 2018.02.11
[debug] Python version 3.6.4 (CPython) - Windows-10-10.0.16299-SP0
[debug] exe versions: ffmpeg N-89951-g3caecf7ce8, ffprobe N-89951-g3caecf7ce8
[debug] Proxy map: {}
[generic] Video: Requesting header
WARNING: Falling back on generic information extractor.
[generic] Video: Downloading webpage
[generic] Video: Extracting information
ERROR: Unsupported URL: https://www.uninettuno.tv/Video.aspx?v=594
Traceback (most recent call last):
  File "c:\python\python36-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 785, in extract_info
    ie_result = ie.extract(url)
  File "c:\python\python36-32\lib\site-packages\youtube_dl\extractor\common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "c:\python\python36-32\lib\site-packages\youtube_dl\extractor\generic.py", line 3111, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.uninettuno.tv/Video.aspx?v=594
`
