### ISSUE TITLE
Udemy - Unable to extract course id

### ISSUE THREAD

**Issue by sh0thub** [rg3/youtube-dl#15609]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.02.11*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.02.11**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)

---
I'm not able to download udemy video, error is: Unable to extract course id. I login with Udemy for Business - Team account. 
---
I tried these URL with same error:
https://www.udemy.com/learn-ansible/
https://www.udemy.com/learn-ansible/learn/v4/t/lecture/7133354

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-u', 'PRIVATE', '-p', 'PRIVATE', 'https://www.udemy.com/learn-ansible/learn/v4/t/lecture/7133354', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.02.11
[debug] Python version 3.6.4 (CPython) - Linux-4.14.18-300.fc27.x86_64-x86_64-with-fedora-27-Twenty_Seven
[debug] exe versions: none
[debug] Proxy map: {}
[udemy] Downloading login popup
[udemy] Logging in
[udemy] 7133354: Downloading webpage
ERROR: Unable to extract course id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/shot/.local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 785, in extract_info
    ie_result = ie.extract(url)
  File "/home/shot/.local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "/home/shot/.local/lib/python3.6/site-packages/youtube_dl/extractor/udemy.py", line 187, in _real_extract
    course_id, _ = self._extract_course_info(webpage, lecture_id)
  File "/home/shot/.local/lib/python3.6/site-packages/youtube_dl/extractor/udemy.py", line 69, in _extract_course_info
    r'data-course-id=["\'](\d+)', webpage, 'course id')
  File "/home/shot/.local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 796, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract course id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- https://www.udemy.com/learn-ansible/
- https://www.udemy.com/learn-ansible/learn/v4/t/lecture/7133354

---

### Description of your *issue*, suggested solution and other information

Probably udemy changed website, so udemy extractor can't find course id.

**Comment by sh0thub** [comment]
Sorry, now everything is working fine. I have to login to www.udemy.com first with my Udemy for business account. After that, downloading started working. Thanks for a great work.
