### ISSUE TITLE
mylifetime.com no video formats (Possibly aenetworks wide)

### ISSUE THREAD

**Issue by remlap** [rg3/youtube-dl#15612]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.02.11*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.02.11**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl http://www.mylifetime.com/movies/the-psycho-she-met-online/full-movie -F -v                      
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'http://www.mylifetime.com/movies/the-psycho-she-met-online/full-movie', u'-F', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.02.11
[debug] Python version 2.7.14 (CPython) - Linux-4.13.0-32-generic-x86_64-with-Ubuntu-17.10-artful
[debug] exe versions: ffmpeg 3.3.4-2, ffprobe 3.3.4-2, rtmpdump 2.4
[debug] Proxy map: {'http': 'REDACTED', u'https': 'socks5://REDACTED}
[aenetworks] the-psycho-she-met-online: Downloading webpage
[aenetworks] 917143107811: Downloading JSON metadata
WARNING: unable to extract JSON-LD; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[aenetworks] 917143107811: Downloading SMIL data
[aenetworks] 917143107811: Checking video URL
[aenetworks] 917143107811: video URL is invalid, skipping
[aenetworks] 917143107811: Checking video URL
[aenetworks] 917143107811: video URL is invalid, skipping
[aenetworks] 917143107811: Checking video URL
[aenetworks] 917143107811: video URL is invalid, skipping
[aenetworks] 917143107811: Checking video URL
[aenetworks] 917143107811: video URL is invalid, skipping
[aenetworks] 917143107811: Checking video URL
[aenetworks] 917143107811: video URL is invalid, skipping
[aenetworks] 917143107811: Checking video URL
[aenetworks] 917143107811: video URL is invalid, skipping
[aenetworks] 917143107811: Checking video URL
[aenetworks] 917143107811: video URL is invalid, skipping
[aenetworks] 917143107811: Checking video URL
[aenetworks] 917143107811: video URL is invalid, skipping
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 785, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/aenetworks.py", line 148, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1071, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://www.mylifetime.com/movies/the-psycho-she-met-online/full-movie
- Single video: https://www.lifetimemovieclub.com/movies/odd-girl-out

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Videos will no longer download, am seeing some 640x360 videos on some movies on lifetimemovieclub.com but no 720p.

**Comment by halolordkiller3** [comment]
Can confirm the exact same issue on history channel

**Comment by flipzmode** [comment]
Just confirming I'm seeing the same issue on aetv.com itself. Using current version (2018.02.11). 

```
youtube-dl --verbose http://www.aetv.com/shows/intervention/season-18/episode-1
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'http://www.aetv.com/shows/intervention/season-18/episode-1']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.02.11
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.16299
[debug] exe versions: none
[debug] Proxy map: {}
[aenetworks] intervention/season-18/episode-1: Downloading webpage
[aenetworks] 1127548995567: Downloading JSON metadata
[aenetworks] 1127548995567: Retrieving Media Token
[aenetworks] 1127548995567: Downloading SMIL data
[aenetworks] 1127548995567: Checking video URL
[aenetworks] 1127548995567: video URL is invalid, skipping
[aenetworks] 1127548995567: Checking video URL
[aenetworks] 1127548995567: video URL is invalid, skipping
[aenetworks] 1127548995567: Checking video URL
[aenetworks] 1127548995567: video URL is invalid, skipping
[aenetworks] 1127548995567: Checking video URL
[aenetworks] 1127548995567: video URL is invalid, skipping
[aenetworks] 1127548995567: Checking video URL
[aenetworks] 1127548995567: video URL is invalid, skipping
[aenetworks] 1127548995567: Checking video URL
[aenetworks] 1127548995567: video URL is invalid, skipping
[aenetworks] 1127548995567: Checking video URL
[aenetworks] 1127548995567: video URL is invalid, skipping
[aenetworks] 1127548995567: Checking video URL
[aenetworks] 1127548995567: video URL is invalid, skipping
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpy028tx8p\build\youtube_dl\YoutubeDL.py", line 785, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpy028tx8p\build\youtube_dl\extractor\common.py", line 440, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpy028tx8p\build\youtube_dl\extractor\aenetworks.py", line 148, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpy028tx8p\build\youtube_dl\extractor\common.py", line 1071, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

Thanks.
