### ISSUE TITLE
Can't extract Facebook videos

### ISSUE THREAD

**Issue by deadrop** [rg3/youtube-dl#15625]
[debug] Command-line args: [u'--verbose', u'https://www.facebook.com/padraocarvalheira/videos/1607606815918150/', u'--no-check-certificate']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.02.11
[debug] Python version 2.7.12 (CPython) - Linux-4.4.0-109-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: none
[debug] Proxy map: {}
[facebook] 1607606815918150: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
Can you watch it in clean browser session in the first place?

**Comment by deadrop** [comment]
Yes, I can open the url in a clean browser. 
https://www.facebook.com/padraocarvalheira/videos/1607606815918150/

**Comment by deadrop** [comment]
File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/facebook.py", line 266, in _extract_from_url
    raise ExtractorError('Cannot parse data')

**Comment by someziggyman** [comment]
Same here. Looks like Facebook is glitching... 
Sometimes it works, sometimes it does not.

I tried this video - https://www.facebook.com/suppiah.mages/videos/1820194114720060/
or this - https://www.facebook.com/groups/257215347635453/permalink/1828834257140213/
Just try it a couple times in a row.

Here's the output, I'm getting.

=========================
youtube-dl --verbose https://www.facebook.com/suppiah.mages/videos/1820194114720060
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.facebook.com/suppiah.mages/videos/1820194114720060']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.02.22
[debug] Python version 2.7.10 (CPython) - Darwin-16.7.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[facebook] 1820194114720060: Downloading webpage
WARNING: [facebook] 1820194114720060: Failed to parse JSON Expecting property name enclosed in double quotes: line 1 column 194393 (char 194392)
[facebook] 1820194114720060: Downloading webpage
WARNING: [facebook] 1820194114720060: Failed to parse JSON Expecting property name enclosed in double quotes: line 1 column 194253 (char 194252)
ERROR: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 785, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/facebook.py", line 422, in _real_extract
    video_id, fatal_if_no_video=True)
  File "./youtube-dl/youtube_dl/extractor/facebook.py", line 337, in _extract_from_url
    raise ExtractorError('Cannot parse data')
ExtractorError: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
=========================

**Comment by AvirahJ** [comment]
Hi, 
I cannot download videos anymore from facebook. The error is : "Failed to parse JSON Expecting property name enclosed in double quotes: line 1 column 219953 (char 219952)". youtube-dl version is up to date - 2018.02.22 . The URL is: https://www.facebook.com/te.desa.5/videos/1615394748528261/ 

The detailed log is here. Is it has something to do with fb url's with names having "." (dot) in between :

```
 $ youtube-dl -F https://www.facebook.com/te.desa.5/videos/1615394748528261/ --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-F', u'https://www.facebook.com/te.desa.5/videos/1615394748528261/', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.02.22
[debug] Python version 2.7.9 (CPython) - Linux-4.13.0-14.1-liquorix-amd64-x86_64-with-LinuxMint-2-betsy
[debug] exe versions: avconv 2.6.9, avprobe 2.6.9, ffmpeg 2.6.9, ffprobe 2.6.9
[debug] Proxy map: {}
[facebook] 1615394748528261: Downloading webpage
[info] Available formats for 1615394748528261:
format code               extension  resolution note
188435145221922vd         mp4        512x640    DASH video  429k , mp4_dash container, avc1.4d401e, 30fps, video only
dash_sd_src               mp4        unknown    
dash_sd_src_no_ratelimit  mp4        unknown    (best)
```

```
$ youtube-dl -f dash_sd_src_no_ratelimit https://www.facebook.com/te.desa.5/videos/1615394748528261/ --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-f', u'dash_sd_src_no_ratelimit', u'https://www.facebook.com/te.desa.5/videos/1615394748528261/', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.02.22
[debug] Python version 2.7.9 (CPython) - Linux-4.13.0-14.1-liquorix-amd64-x86_64-with-LinuxMint-2-betsy
[debug] exe versions: avconv 2.6.9, avprobe 2.6.9, ffmpeg 2.6.9, ffprobe 2.6.9
[debug] Proxy map: {}
[facebook] 1615394748528261: Downloading webpage
WARNING: [facebook] 1615394748528261: Failed to parse JSON Expecting property name enclosed in double quotes: line 1 column 219962 (char 219961)
[facebook] 1615394748528261: Downloading webpage
WARNING: [facebook] 1615394748528261: Failed to parse JSON Expecting property name enclosed in double quotes: line 1 column 219970 (char 219969)
ERROR: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 785, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/facebook.py", line 422, in _real_extract
    video_id, fatal_if_no_video=True)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/facebook.py", line 337, in _extract_from_url
    raise ExtractorError('Cannot parse data')
ExtractorError: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
