### ISSUE TITLE
Failed to parse json from tunein

### ISSUE THREAD

**Issue by shraddha-kapoor** [rg3/youtube-dl#15633]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.02.11**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

Bug report:

```
[debug] System config: [u'--prefer-free-formats']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--skip-download', u'--print-json', u'-v', u'https://tunein.com/radio/Grupera-931-s161252/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.02.11
[debug] Python version 2.7.14 (CPython) - Linux-4.14.18-300.fc27.x86_64-x86_64-with-fedora-27-Twenty_Seven
[debug] exe versions: ffmpeg 3.3.6, ffprobe 3.3.6
[debug] Proxy map: {}
ERROR: 161252: Failed to parse JSON  (caused by ValueError('No JSON object could be decoded',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/extractor/common.py", line 690, in _parse_json
    return json.loads(json_string)
  File "/usr/lib64/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 785, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/tunein.py", line 38, in _real_extract
    transform_source=lambda s: re.sub(r'^\s*\((.*)\);\s*$', r'\1', s))['Streams']
  File "./youtube-dl/youtube_dl/extractor/common.py", line 684, in _download_json
    json_string, video_id, transform_source=transform_source, fatal=fatal)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 694, in _parse_json
    raise ExtractorError(errmsg, cause=ve)
ExtractorError: 161252: Failed to parse JSON  (caused by ValueError('No JSON object could be decoded',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by dstftw** [comment]
Post the output with `--dump-pages`.

**Comment by shraddha-kapoor** [comment]
Thanks, I've added that argument but it produced the same output as my description.

**Comment by dstftw** [comment]
Remove all other options.

**Comment by shraddha-kapoor** [comment]
Thank you, I'm sorry but it worked again. I'm not sure why. I'm sorry...
