### ISSUE TITLE
Add support for yle

### ISSUE THREAD

**Issue by nemobis** [rg3/youtube-dl#1574]
https://github.com/aajanki/yle-dl by @aajanki may provide what needed

$ ./youtube-dl --verbose http://areena.yle.fi/radio/2048905
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://areena.yle.fi/radio/2048905']
[debug] youtube-dl version 2013.10.07
[debug] Python version 2.6.6 - Linux-3.2.46-grbfs-kapsi-x86_64-with-debian-6.0.7
[debug] Proxy map: {}
WARNING: Falling back on generic information extractor.
[generic] 2048905: Downloading webpage
[generic] 2048905: Extracting information
ERROR: Unsupported URL: http://areena.yle.fi/radio/2048905; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 348, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 117, in extract
    return self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/generic.py", line 152, in _real_extract
    raise ExtractorError(u'Unsupported URL: %s' % url)
ExtractorError: Unsupported URL: http://areena.yle.fi/radio/2048905; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by yan12125** [comment]
Another form of URL: http://arenan.yle.fi/1-3094091 (from #8896)

**Comment by rautamiekka** [comment]
https://areena.yle.fi/1-4200978 is a link which returns `Unsupported URL`.

**Comment by Hegezcc** [comment]
I am working with this on pull request #20274.

**Comment by Zuccace** [comment]
Great! I think I could test it already. :)

**Comment by Hegezcc** [comment]
It works on my computer, just clone the branch and run it with `python -m youtube_dl https://areena.yle.fi/1-4256816`. 

I recommend adding `-f 'mp4[height<=1080]'` flag to the end of the command if you don't require absolutely best quality with a cost in download time and disk space, as youtube-dl default setting is to download with best possible quality and Areena's Kaltura API is very flexible regarding that.

**Comment by Zuccace** [comment]
I did try it but the first try went nowhere. :(
```
youtube-dl -f 'bestvideo+bestaudio/best' https://areena.yle.fi/1-4551318
[YleAreena] 1-4551318: Downloading webpage
ERROR: Unable to extract OpenGraph video:url;
```

I also created [an ebuild for adventurous gentoo users](https://github.com/Zuccace/zucca-overlay/tree/master/net-misc/youtube-dl-yle).

**Comment by Hegezcc** [comment]
@Zuccace 
Looks like that media is not using the Kaltura API. I might have to reverse engineer that too.

Does this work? Also, that ` -f 'bestvideo+bestaudio/best'` is used by default, you don't need to explicitly give that to get best quality.
```
youtube-dl https://areena.yle.fi/1-4664683 --test
```

**Comment by Zuccace** [comment]
> Does this work?

Sure. I just don't know what to do with `.mxf`.

**Comment by Hegezcc** [comment]
Looks like Yle has lots of different players across its systems, but Areena has mostly Kaltura players for videos. I don't know why Yle is distributing that document series without Kaltura, as they have some metadata for that series there and the series is quite new. Probably a copyright issue.

`yle-dl` project has made the following extractors:
* ElavaArkistoExtractor
* ArkivetExtractor
* AreenaLiveRadioExtractor
* AreenaLiveTVHLSExtractor
* AreenaLiveTVHDSExtractor
* YleUutisetExtractor
* AreenaExtractor

Lots of code there. `yle-dl`'s AreenaExtractor has checks for Full HD, HTML5, Elävä Arkisto and Mediakanta medias. Those use at least Kaltura and Akamai services.

**Comment by Zuccace** [comment]
Probably because some of the content is still delivered trough flash. And yle has stated that they cannot/won't change that for older content.

What a mess...
    -- Ilja Sara

**Comment by Zuccace** [comment]
So I did a test download using best possible quality. I got 14 gig video. **MPEG2, 1080i**. Holy cow! Yle _still_ using **mpeg2**? Madness...
I need to adjust my download script (wrapper for youtube-dl, not public, yet...) for yle then to accept only h.264, h.265, VP8 or VP9 video codecs.
