### ISSUE TITLE
urlopen error [Errno11004] getaddrinfo failed

### ISSUE THREAD

**Issue by obnews** [rg3/youtube-dl#15746]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.03.03*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.03.03**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

I had a error when I use youtube-dl for the first time.
Can somebody help me, here is the log:

D:\>youtube-dl.exe --verbose "https://www.youtube.com/watch?v=DYj1KNk5Wnw"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=DYj1KNk5Wnw']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2018.03.03
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] DYj1KNk5Wnw: Downloading webpage
[youtube] DYj1KNk5Wnw: Downloading video info webpage
[youtube] DYj1KNk5Wnw: Extracting video information
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://r7---sn-uxaxovg-vnar.googlevideo.com/videoplayback?source=youtube&initcwndbps=1102500&ei=gsWZWoiWHcGGYd-Cq6gO&requir
essl=yes&sparams=dur%2Cei%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpir
e&lmt=1520000594451898&ipbits=0&mt=1520026911&mv=m&pcm2cms=yes&ms=au%2Crdu&signature=3FB7CED649580582D814AF421DF609F5C96F7B78.4CBFFA060F80ABC83FE0B496FE66FB
8E563CCB70&id=o-AOtkpdieZojNlL1sXGrWAqWVEVi1QOHRK99fvpDlgRtH&mm=31%2C29&ip=148.122.184.250&mn=sn-uxaxovg-vnar%2Csn-5goeen7y&pl=20&expire=1520048610&c=WEB&mi
me=video%2Fmp4&key=yt6&fvip=5&ratebypass=yes&itag=22&dur=3489.657'
ERROR: unable to download video data: <urlopen error [Errno 11004] getaddrinfo failed>
Traceback (most recent call last):
  File "C:\Python\Python34\lib\urllib\request.py", line 1183, in do_open
  File "C:\Python\Python34\lib\http\client.py", line 1137, in request
  File "C:\Python\Python34\lib\http\client.py", line 1182, in _send_request
  File "C:\Python\Python34\lib\http\client.py", line 1133, in endheaders
  File "C:\Python\Python34\lib\http\client.py", line 963, in _send_output
  File "C:\Python\Python34\lib\http\client.py", line 898, in send
  File "C:\Python\Python34\lib\http\client.py", line 1279, in connect
  File "C:\Python\Python34\lib\http\client.py", line 871, in connect
  File "C:\Python\Python34\lib\socket.py", line 498, in create_connection
  File "C:\Python\Python34\lib\socket.py", line 537, in getaddrinfo
socket.gaierror: [Errno 11004] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0wqp9d0n\build\youtube_dl\YoutubeDL.py", line 1896, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0wqp9d0n\build\youtube_dl\YoutubeDL.py", line 1835, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0wqp9d0n\build\youtube_dl\downloader\common.py", line 364, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0wqp9d0n\build\youtube_dl\downloader\http.py", line 340, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0wqp9d0n\build\youtube_dl\downloader\http.py", line 109, in establish_connection
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0wqp9d0n\build\youtube_dl\YoutubeDL.py", line 2199, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0wqp9d0n\build\youtube_dl\utils.py", line 1101, in https_open
  File "C:\Python\Python34\lib\urllib\request.py", line 1185, in do_open
urllib.error.URLError: <urlopen error [Errno 11004] getaddrinfo failed>

**Comment by dstftw** [comment]
Most likely a DNS issue on your side.
