### ISSUE TITLE
Snagfilms/ViewLift is broken

### ISSUE THREAD

**Issue by ahmedtds** [rg3/youtube-dl#15766]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.03.03**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.snagfilms.com/films/title/splinters']
[debug] Encodings: locale cp1254, fs mbcs, out cp1254, pref cp1254
[debug] youtube-dl version 2018.03.03
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-90173-gfa0c9d69d3, ffprobe N-90173-gfa0c9d69d3
[debug] Proxy map: {}
[ViewLift] splinters: Downloading webpage
ERROR: Unable to extract film id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0wqp9d0n\build\youtube_dl\YoutubeDL.py", line 785, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0wqp9d0n\build\youtube_dl\extractor\common.py", line 440, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0wqp9d0n\build\youtube_dl\extractor\viewlift.py", line 159, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0wqp9d0n\build\youtube_dl\extractor\common.py", line 796, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract film id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
And this is after I tried with the embed URL:
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.snagfilms.com/embed/player?filmId=5be0a810-4cef-11e1-945b-123139220831']
[debug] Encodings: locale cp1254, fs mbcs, out cp1254, pref cp1254
[debug] youtube-dl version 2018.03.03
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-90173-gfa0c9d69d3, ffprobe N-90173-gfa0c9d69d3
[debug] Proxy map: {}
[ViewLiftEmbed] 5be0a810-4cef-11e1-945b-123139220831: Downloading webpage
ERROR: Unable to extract json; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0wqp9d0n\build\youtube_dl\YoutubeDL.py", line 785, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0wqp9d0n\build\youtube_dl\extractor\common.py", line 440, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0wqp9d0n\build\youtube_dl\extractor\viewlift.py", line 64, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0wqp9d0n\build\youtube_dl\extractor\common.py", line 796, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract json; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
---

Example URLs:
https://www.snagfilms.com/films/title/splinters
or embed URL:
https://www.snagfilms.com/embed/player?filmId=5be0a810-4cef-11e1-945b-123139220831

It should be very easy to fix because I can just find the url of the mp4 file by inspecting and can download it. It doesn't have any security or hls stream etc.. Just a mp4 file.
Thanks!

**Comment by ahmedtds** [comment]
I noticed that example URL I give only has 1 quality option. These example URLs have several quality options:

https://www.snagfilms.com/films/title/we-the-people-the-market-basket-effect
https://www.snagfilms.com/films/title/lost_for_life

And this is a movie with region restriction:
https://www.snagfilms.com/films/title/devils_arithmetic
