### ISSUE TITLE
[Laracasts.com] Can't download embedded Vimeo

### ISSUE THREAD

**Issue by pihug12** [rg3/youtube-dl#15763]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.03.03*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.03.03**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
λ python C:\Users\User\Downloads\youtube-dl -v https://laracasts.com/series/visual-studio-code-for-php-developers/episodes/2
[debug] System config: []
[debug] User config: [u'--no-mtime', u'--no-cache-dir']
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://laracasts.com/series/visual-studio-code-for-php-developers/episodes/2']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.03.03
[debug] Python version 2.7.13 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 3.2.4, ffprobe 3.2.4
[debug] Proxy map: {}
[generic] 2: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 2: Downloading webpage
[generic] 2: Extracting information
ERROR: Unsupported URL: https://laracasts.com/series/visual-studio-code-for-php-developers/episodes/2
Traceback (most recent call last):
  File "C:\Users\User\Downloads\youtube-dl\youtube_dl\extractor\generic.py", line 2221, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "C:\Users\User\Downloads\youtube-dl\youtube_dl\compat.py", line 2542, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "C:\Users\User\Downloads\youtube-dl\youtube_dl\compat.py", line 2531, in _XML
    parser.feed(text)
  File "D:\Python27\lib\xml\etree\ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "D:\Python27\lib\xml\etree\ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: mismatched tag: line 38, column 2
Traceback (most recent call last):
  File "C:\Users\User\Downloads\youtube-dl\youtube_dl\YoutubeDL.py", line 785, in extract_info
    ie_result = ie.extract(url)
  File "C:\Users\User\Downloads\youtube-dl\youtube_dl\extractor\common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\User\Downloads\youtube-dl\youtube_dl\extractor\generic.py", line 3145, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://laracasts.com/series/visual-studio-code-for-php-developers/episodes/2
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://laracasts.com/series/visual-studio-code-for-php-developers/episodes/2

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Laracasts.com uses embedded Vimeo video. **youtube-dl** doesn't seem to be able to extract it parsing the HTML document.

**Comment by kayb94** [comment]
I guess, the `vimeo-id` in line 161 of the webpage might help. But I did not come any further.

**Comment by pirate486743186** [comment]
vimeo-id is for the iframe
with the referrer you can download the iframe

wget --referer "https://laracasts.com" "https://player.vimeo.com/video/243120448"

in the iframe "var config" holds the video links
