### ISSUE TITLE
[go] ERROR: 0033:The customer is not authorized for the content requested

### ISSUE THREAD

**Issue by RuneMagle** [rg3/youtube-dl#15800]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.03.03**
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

```
C:\Users\BARN\Desktop\youtube-dl>youtube-dl.exe -f best --all-subs --ap-username PRIVATE --ap-password PRIVATE http://watchdisneychannel.go.com/disney-channel-movies/video/vdka0_aja8vy8p/01/01-gotta-kick-it-up -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'best', '--all-subs', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', 'http://watchdisneychannel.go.com/disney-channel-movies/video/vdka0_aja8vy8p/01/01-gotta-kick-it-up', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.03.03
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.16299
[debug] exe versions: ffmpeg N-83034-gf48b6b8, ffprobe N-83096-g6596b34
[debug] Proxy map: {}
[Go] vdka0_aja8vy8p: Downloading JSON metadata
[Go] VDKA0_aja8vy8p: Retrieving Authorization Token
ERROR: 0033:The customer is not authorized for the content requested
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0wqp9d0n\build\youtube_dl\YoutubeDL.py", line 785, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0wqp9d0n\build\youtube_dl\extractor\common.py", line 440, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0wqp9d0n\build\youtube_dl\extractor\go.py", line 119, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0wqp9d0n\build\youtube_dl\extractor\adobepass.py", line 1545, in _extract_mvpd_auth
youtube_dl.utils.ExtractorError: 0033:The customer is not authorized for the content requested
...
<end of log>
```

---
- Single video: http://watchdisneychannel.go.com/disney-channel-movies/video/vdka0_aja8vy8p/01/01-gotta-kick-it-up
- Single video: http://watchdisneychannel.go.com/disney-channel-movies/video/vdka0_hxev78pk/01/01-double-teamed

---

### Description of *issue*
Video won't download. It's definitely not the DTV account, since it works just fine. I can login and watch the movie on the website, so something is wrong. It gave me the same error code every time, except for once, where it said A network error occured when communicating with the provider's authorization service".

**Comment by RuneMagle** [comment]
I even signed in and grabbed the link myself, but I have problems with download it:
```
youtube-dl.exe -f best --all-subs "https://content-ausw1.uplynk.com/73fc8262406541aa8f451f8ba67c6c89/i.m3u8" -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'best', '--all-subs', 'https://content-ausw1.uplynk.com/73fc8262406541aa8f451f8ba67c6c89/i.m3u8', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.03.03
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.16299
[debug] exe versions: ffmpeg N-83034-gf48b6b8, ffprobe N-83096-g6596b34
[debug] Proxy map: {}
[generic] i: Requesting header
[generic] i: Downloading m3u8 information
[debug] Invoking downloader on 'https://content-ausw1.uplynk.com/73fc8262406541aa8f451f8ba67c6c89/i.m3u8'
[download] Destination: i-i.mp4
[debug] ffmpeg command line: ffmpeg -y -loglevel verbose -headers "Accept-Encoding: gzip, deflate
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-us,en;q=0.5
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0 (Chrome)
" -i "https://content-ausw1.uplynk.com/73fc8262406541aa8f451f8ba67c6c89/i.m3u8" -c copy -f mp4 "-bsf:a" aac_adtstoasc "file:i-i.mp4.part"
ffmpeg version N-83034-gf48b6b8 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 5.4.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-dxva2 --enable-libmfx --enable-nvenc --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-decklink --enable-zlib
  libavutil      55. 43.100 / 55. 43.100
  libavcodec     57. 71.100 / 57. 71.100
  libavformat    57. 62.100 / 57. 62.100
  libavdevice    57.  2.100 / 57.  2.100
  libavfilter     6. 68.100 /  6. 68.100
  libswscale      4.  3.101 /  4.  3.101
  libswresample   2.  4.100 /  2.  4.100
  libpostproc    54.  2.100 / 54.  2.100
[hls,applehttp @ 0000000004602560] HLS request for url 'https://stgec-ausw-tmp.uplynk.com/80C078/ausw/slices/73f/21885d134fa441488df8e1d7acee8c66/73fc8262406541aa8f451f8ba67c6c89/I00000000.ts?x=0&si=0', offset 0, playlist 0
[tls @ 0000000004a41800] Server closed the connection
[https @ 000000000467bc20] HTTP error 403 Forbidden
Unable to open key file https://content-ausw1.uplynk.com/check2?b=73fc8262406541aa8f451f8ba67c6c89&v=73fc8262406541aa8f451f8ba67c6c89&r=i
[hls,applehttp @ 0000000004602560] Error when loading first segment 'https://stgec-ausw-tmp.uplynk.com/80C078/ausw/slices/73f/21885d134fa441488df8e1d7acee8c66/73fc8262406541aa8f451f8ba67c6c89/I00000000.ts?x=0&si=0'
https://content-ausw1.uplynk.com/73fc8262406541aa8f451f8ba67c6c89/i.m3u8: Invalid data found when processing input


ERROR: ffmpeg exited with code 1
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0wqp9d0n\build\youtube_dl\__init__.py", line 471, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0wqp9d0n\build\youtube_dl\__init__.py", line 461, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0wqp9d0n\build\youtube_dl\YoutubeDL.py", line 1989, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0wqp9d0n\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0wqp9d0n\build\youtube_dl\YoutubeDL.py", line 850, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0wqp9d0n\build\youtube_dl\YoutubeDL.py", line 1623, in process_video_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0wqp9d0n\build\youtube_dl\YoutubeDL.py", line 1896, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0wqp9d0n\build\youtube_dl\YoutubeDL.py", line 1835, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0wqp9d0n\build\youtube_dl\downloader\common.py", line 364, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0wqp9d0n\build\youtube_dl\downloader\external.py", line 57, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0wqp9d0n\build\youtube_dl\downloader\common.py", line 166, in report_error
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0wqp9d0n\build\youtube_dl\YoutubeDL.py", line 613, in report_error
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0wqp9d0n\build\youtube_dl\YoutubeDL.py", line 575, in trouble```
