### ISSUE TITLE
heise.de/video links to cdnapisec.kaltura.com: URLError: <urlopen error Tunnel connection failed: 503 Connect failed>

### ISSUE THREAD

**Issue by CiscoPress** [rg3/youtube-dl#15819]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.03.10*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.03.10**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

```
youtube-dl -v https://www.heise.de/video/artikel/Kurz-informiert-vom-27-02-2018-IT-Verschluesselung-Netzneutralitaet-Selbstfahrende-Autos-Russisches-3981632.html?wt_mc=rss.video.beitrag.atom
[debug] System config: [u'--recode-video=mp4', u'-f', u'(bestvideo[width>=1920]/bestvideo)+bestaudio/best']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.heise.de/video/artikel/Kurz-informiert-vom-27-02-2018-IT-Verschluesselung-Netzneutralitaet-Selbstfahrende-Autos-Russisches-3981632.html?wt_mc=rss.video.beitrag.atom']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.03.10
[debug] Python version 2.7.10 (CPython) - Darwin-17.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.4.2, ffprobe 3.4.2, rtmpdump 2.4
[debug] Proxy map: {'http': 'http://127.0.0.1:8118', 'https': 'http://127.0.0.1:8118'}
[Heise] 3981632: Downloading webpage
[Kaltura] 1_kau1wws8: Downloading video info JSON
[Kaltura] 1_kau1wws8: Downloading m3u8 information
[debug] Invoking downloader on u'https://cdnapisec.kaltura.com/p/2238431/sp/223843100/playManifest/entryId/1_kau1wws8/format/url/protocol/https/flavorId/0_fnlkixyl?referrer=aHR0cHM6Ly93d3cuaGVpc2UuZGU='
ERROR: unable to download video data: <urlopen error Tunnel connection failed: 503 Connect failed>
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1896, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1835, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 364, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 340, in real_download
    establish_connection()
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2199, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 469, in error
    result = self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 656, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1101, in https_open
    req, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
URLError: <urlopen error Tunnel connection failed: 503 Connect failed>

> ping cdnapisec.kaltura.com
PING e4669.g.akamaiedge.net (23.53.173.72): 56 data bytes
64 bytes from 23.53.173.72: icmp_seq=0 ttl=56 time=20.216 ms
64 bytes from 23.53.173.72: icmp_seq=1 ttl=56 time=23.900 ms
64 bytes from 23.53.173.72: icmp_seq=2 ttl=56 time=21.079 ms
^C
--- e4669.g.akamaiedge.net ping statistics ---
3 packets transmitted, 3 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 20.216/21.732/23.900/1.573 ms


> curl -v https://cdnapisec.kaltura.com/p/2238431/sp/223843100/playManifest/entryId/1_kau1wws8/format/url/protocol/https/flavorId/0_fnlkixyl?referrer=aHR0cHM6Ly93d3cuaGVpc2UuZGU=
*   Trying 23.53.173.72...
* TCP_NODELAY set
* Connected to cdnapisec.kaltura.com (23.53.173.72) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.2 (IN), TLS handshake, Server hello (2):
{ [108 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [2890 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [333 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [70 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
{ [1 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: C=US; ST=New York; L=New York; O=Kaltura Inc; OU=Operations; CN=*.kaltura.com
*  start date: Jan 25 00:00:00 2018 GMT
*  expire date: Apr 26 12:00:00 2019 GMT
*  subjectAltName: host "cdnapisec.kaltura.com" matched cert's "*.kaltura.com"
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert SHA2 Secure Server CA
*  SSL certificate verify ok.
> GET /p/2238431/sp/223843100/playManifest/entryId/1_kau1wws8/format/url/protocol/https/flavorId/0_fnlkixyl?referrer=aHR0cHM6Ly93d3cuaGVpc2UuZGU= HTTP/1.1
> Host: cdnapisec.kaltura.com
> User-Agent: Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0)
> Accept: */*
> 
< HTTP/1.1 302 Moved Temporarily
< Server: Apache
< X-Me: ny-front-api38
< X-Kaltura: cached-dispatcher,playManifest-fb8eed9aa1159a9f1afd0142852e8e09,0.00060486793518066
< Location: https://cfvod.kaltura.com/scf/pd/p/2238431/sp/223843100/serveFlavor/entryId/1_kau1wws8/v/2/ev/5/flavorId/0_fnlkixyl/name/a.mp4?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9jZnZvZC5rYWx0dXJhLmNvbS9zY2YvcGQvcC8yMjM4NDMxL3NwLzIyMzg0MzEwMC9zZXJ2ZUZsYXZvci9lbnRyeUlkLzFfa2F1MXd3czgvdi8yL2V2LzUvZmxhdm9ySWQvMF9mbmxraXh5bC9uYW1lLyoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE1MjA3OTcyNjV9fX1dfQ__&Signature=OOXKroE3Vr1PIxHoK0vBkDQgqVHuuDkJzc6fE-WI5htx~hQcJhIGRQ7HJPnUbJVb8TdPNFFXnh0rO4oiJUsimKgnbZcuWBElTz~f3V~TQPAgtjmnSNGSIreI9UcK1mjv88lfiEy6W0ODSshEAHKi-~kMHIeaISKPjCwjvjwVvsdJiQhjcdtEwIwE0bkmeoMRUcq5A6049iClTTDdKOj616156PhV6mYZ0vqLdSvarVDloSDM0MsMpmTJBwp2OupLzZthm1qov7FFd~JCBwFsA7P1b5Dxz7y4g62ikrvNe4bZ5ZLLoZUsosb2cuyiPQGb4Z09ci~Bhzq8XAm-PVU~tg__&Key-Pair-Id=APKAJT6QIWSKVYK3V34A
< Access-Control-Allow-Origin: *
< Access-Control-Expose-Headers: Server,range,Content-Length,Content-Range
< Content-Encoding: gzip
< Content-Length: 21
< Content-Type: text/html
< Expires: Sat, 10 Mar 2018 19:41:05 GMT
< Cache-Control: max-age=0, no-cache, no-store
< Pragma: no-cache
< Date: Sat, 10 Mar 2018 19:41:05 GMT
< Connection: keep-alive
< 
{ [21 bytes data]
######################################################################## 100.0%* Connection #0 to host cdnapisec.kaltura.com left intact


> cat ../.curlrc 
progress-bar
show-error
#remote-time
ipv4
user-agent = "Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0)"
remote-name-all


```

**Comment by dstftw** [comment]
Most likely a proxy issue.
