### ISSUE TITLE
[ddtuniverse] Add extractor

### ISSUE THREAD

**Issue by namX1337** [rg3/youtube-dl#15816]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.03.10*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.03.10**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://ddtuniverse.com/program/index/20180302_REC_DDT', u'-o', u'test.ts', u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'--hls-use-mpegts', u'--restrict-filenames', u'-v']
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
[debug] youtube-dl version 2018.03.10
[debug] Python version 2.7.14+ (CPython) - Linux-4.14.0-3-amd64-x86_64-with-debian-buster-sid
[debug] exe versions: ffmpeg 3.4.2, ffprobe 3.4.2
[debug] Proxy map: {}
[generic] 20180302_REC_DDT: Requesting header
WARNING: Could not send HEAD request to https://ddtuniverse.com/program/index/20180302_REC_DDT: HTTP Error 403: Forbidden
[generic] 20180302_REC_DDT: Downloading webpage
WARNING: Falling back on generic information extractor.
[generic] 20180302_REC_DDT: Extracting information
ERROR: Unsupported URL: https://ddtuniverse.com/program/index/20180302_REC_DDT
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2222, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2542, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2531, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
ParseError: mismatched tag: line 615, column 2
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 785, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3151, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://ddtuniverse.com/program/index/20180302_REC_DDT
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://ddtuniverse.com/program/index/20180302_REC_DDT
- Single video: https://ddtuniverse.com/program/index/20180302_DDT_000
- Playlist: https://ddtuniverse.com/program_group/index/20180302_DDT
- Playlist: https://ddtuniverse.com/program_group/index/20180303_BSR

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

[DDT UNIVERSE](http://ddtuniverse.com) is the online streaming service for DDT (Dramatic Dream Tem), a japanese wrestling organisation. The site works similar to (in some cases easier than) [NJPW World](http://njpwworld.com).

#### Authentication:
URL: https://ddtuniverse.com/auth/login
POST: 
 - login_id > Usernname
 - pw > Password

#### Extraction (Playlist):
A playlist is a plain list of linked single videos. All URLs in the playlist website that match the RegEx pattern **https?://ddtuniverse\.com/program/index/(?P<id>[a-zA-Z0-9_]+)** should be viable candidates for the playlist.

#### Extraction (Single Video):
The website of the single video URL contains (if the authentication was successful) a javascript part which contains the url to a **iPhonePlaylist.m3u8** (RexEx: https://www2.uliza.jp/IF/iphone/iPhonePlaylist.m3u8\?v=[a-zA-Z0-9=&]+) which can be accessed without further authentication. This information is available only once in the webpage.

#### Note:
Authentication can provided if the aforementioned information is not sufficient.

**Comment by BryantD** [comment]
FWIW: this site has been rolled into a larger site, wrestle-universe.com, which includes more Japanese wrestling promotions. The extraction notes for this request are no longer valid, even if you substitute in the new URL.

**Comment by 89z** [comment]
@BryantD do you have an example URL?
