### ISSUE TITLE
XNXX.com - ERROR: Unable to extract video URL

### ISSUE THREAD

**Issue by analogged** [rg3/youtube-dl#15817]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.03.10**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
### What is the purpose of your _issue_?
- [x] Bug report (encountered problems with youtube-dl)
### Full verbose output:

```
-bash-4.1# youtube --version
2018.03.10


-bash-4.1# youtube -v -j http://www.xnxx.com/video-i7eij1a/non_nude_sexy_teen_tease
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-j', u'http://www.xnxx.com/video-i7eij1a/non_nude_sexy_teen_tease']
WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
[debug] youtube-dl version 2018.03.10
[debug] Python version 2.6.6 (CPython) - Linux-2.6.32-042stab108.5-x86_64-with-centos-6.9-Final
[debug] exe versions: ffmpeg 2.6.8, ffprobe 2.6.8
[debug] Proxy map: {}
ERROR: Unable to extract video URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube/youtube_dl/YoutubeDL.py", line 785, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube/youtube_dl/extractor/common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube/youtube_dl/extractor/xnxx.py", line 32, in _real_extract
    webpage, 'video URL')
  File "/usr/local/bin/youtube/youtube_dl/extractor/common.py", line 796, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.



```

---
### Description of issue

youtube-dl outputs `ERROR: Unable to extract video URL;
` errors when trying to download or find links on any xnxx.com videos.

Video used in this example - http://www.xnxx.com/video-i7eij1a/non_nude_sexy_teen_tease

Seems to be the case for all videos I've tested on the site

**Comment by Hrxn** [comment]
Can reproduce.
