### ISSUE TITLE
Can't download from Tou.TV extra ("Unable to extract access token")

### ISSUE THREAD

**Issue by twomby** [rg3/youtube-dl#15843]
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2018.03.10**
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

```
youtube-dl --verbose -u username_redacted -p password_redacted https://ici.tou.tv/lacher-prise/S01E01
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'https://ici.tou.tv/lacher-prise/S01E01']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.03.10
[debug] Python version 2.7.12 (CPython) - Linux-4.13.0-36-generic-x86_64-with-LinuxMint-18.3-sylvia
[debug] exe versions: ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1
[debug] Proxy map: {}
[tou.tv] Downloading homepage
[tou.tv] Downloading login page
[tou.tv] Logging in
[tou.tv] Following Redirection
ERROR: Unable to extract access token; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 785, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 439, in extract
    self.initialize()
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 397, in initialize
    self._real_initialize()
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/toutv.py", line 88, in _real_initialize
    urlh.geturl(), 'access token')
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 796, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract access token; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

---

### Description of your *issue*, suggested solution and other information

Can't seem to be able to download anything from Tou.TV extra, although it works on the regular (i.e. non-premium) streams. Has to do with Acess token, but I'm lost. This error message "Unable to extract access token" shows up on any premium content I have tried to download so far. 

I'd be much grateful for any help! Regards,

**Comment by twomby** [comment]
I can provide account credentials if needed to investigate the issue. Sorry I forgot to mention it. Just message me privately.

**Comment by JayV3e** [comment]
I've been able to launch the download using version 2018.03.14, you might want to try again.

[debug] youtube-dl version 2018.03.14
[debug] Python version 2.7.12 (CPython) - Darwin-16.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.4.2, ffprobe 3.4.2

**Comment by twomby** [comment]
Thanks for testing on your end JayV3e! Unfortunately, after updating to 2018.03.14, I still encounter the exact same error message.  I see that your called libraries/binaries are much more recent than mine. I wonder if that could be the issue, but I really don't know what to do at this point.  

Merci quand même :)

**Comment by twomby** [comment]
FYI, I have updated ffmpeg and ffprobe to the latest version (3.4.2.1), just as yours, to see if it would help. I do get the same error message.  But it seems like it really has to do with youtube-dl itself and its extractor module. I don't know why I'm experiencing this python error...

**Comment by alexhuot1** [comment]
I sent a pull request (#18700) for issue #16398. I'm not sure if it will fix this issue, but it might.

**Comment by tabarnakos** [comment]
In the meantime, manually checking out Alex's branch "toutv_account" and building it from source worked for me. Just downloaded all the "Les aventures du Pharmachien" episodes.
