### ISSUE TITLE
Download from 3sat Mediathek - Unsupported URL: http://www.3sat.de/mediathek/?mode=play

### ISSUE THREAD

**Issue by ds2k5** [rg3/youtube-dl#15845]
Hello,
try to Download from 3sat Mediathek but did not work for me.

$ youtube-dl --version
**2018.02.26**
tryed with 2018.03.10 too

youtube-dl --verbose http://www.3sat.de/mediathek/?mode=play&obj=71841

ERROR: Unsupported URL: http://www.3sat.de/mediathek/?mode=play
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 785, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/generic.py", line 3127, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.3sat.de/mediathek/?mode=play

**with Version: 2018.03.10** 

./youtube-dl.1 --verbose http://www.3sat.de/mediathek/?mode=play&obj=71841

ERROR: Unsupported URL: http://www.3sat.de/mediathek/?mode=play
Traceback (most recent call last):
  File "./youtube-dl.1/youtube_dl/YoutubeDL.py", line 785, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl.1/youtube_dl/extractor/common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "./youtube-dl.1/youtube_dl/extractor/generic.py", line 3151, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.3sat.de/mediathek/?mode=play

How to fix this ?

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command

**Comment by ds2k5** [comment]
Thanks but did only download 8 MB, but the VIDEO is near 50 minutes long
