### ISSUE TITLE
ERROR: local variable 'check_cookie_url' referenced before assignment

### ISSUE THREAD

**Issue by LoyCog** [rg3/youtube-dl#15871]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.03.14*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.03.14**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-i', u'--source-address', u'12.12.12.12', u'--socket-timeout', u'5', u'--geo-bypass', u'-f', u'bestaudio/best', u'--write-info-json', u'--no-mtime', u'--netrc', u'--verbose', u'-o', u'/home/www/v/videos/1514636790651|%(id)s', u'https://www.youtube.com/watch?v=SabJF7y9TWE']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.03.14
[debug] Python version 2.7.5 (CPython) - Linux-3.14.32-xxxx-grs-ipv6-64-x86_64-with-centos-7.4.1708-Core
[debug] exe versions: ffmpeg 2.6.8, ffprobe 2.6.8
[debug] Proxy map: {}
[youtube] Downloading login page
[youtube] Looking up account info
[youtube] Logging in
ERROR: local variable 'check_cookie_url' referenced before assignment
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 785, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 439, in extract
    self.initialize()
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 397, in initialize
    self._real_initialize()
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 258, in _real_initialize
    if not self._login():
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 233, in _login
    if not check_cookie_url:
UnboundLocalError: local variable 'check_cookie_url' referenced before assignment
```

### Description of your *issue*, suggested solution and other information

Can't login to youtube using --netrc or --username --password. 
Same error: ERROR: local variable 'check_cookie_url' referenced before assignment.
I am sure that login credentials are correct.

**Comment by LoyCog** [comment]
@dstftw Duplicate? How to fix this then?
