### ISSUE TITLE
Error when downloading a free movie from vrv.co

### ISSUE THREAD

**Issue by adamryczkowski** [rg3/youtube-dl#15887]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.03.14**
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

```
$ youtube-dl -v https://vrv.co/watch/G6QWGX3P6/Paradigms-How-We-Know-What-We-Know:The-Science-of-Seeing

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://vrv.co/watch/G6QWGX3P6/Paradigms-How-We-Know-What-We-Know:The-Science-of-Seeing']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.03.14
[debug] Python version 3.5.2 (CPython) - Linux-4.15.8-x86_64-linode103-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: none
[debug] Proxy map: {}
[vrv] G6QWGX3P6: Downloading webpage
[vrv] G6QWGX3P6: Downloading en-US MPD information
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/__init__.py", line 471, in main
    _real_main(argv)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/__init__.py", line 461, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/YoutubeDL.py", line 1989, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/YoutubeDL.py", line 785, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/vrv.py", line 132, in _real_extract
    fatal=False)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/common.py", line 1753, in _extract_mpd_formats
    formats_dict=formats_dict, mpd_url=mpd_url)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/common.py", line 1976, in _parse_mpd_formats
    segment_uri = representation_ms_info['segment_urls'][segment_index]
IndexError: list index out of range
```

### Description of your *issue*, suggested solution and other information

Geo-restricted. **The [https://vrv.co/watch/G6QWGX3P6/Paradigms-How-We-Know-What-We-Know:The-Science-of-Seeing](https://vrv.co/watch/G6QWGX3P6/Paradigms-How-We-Know-What-We-Know:The-Science-of-Seeing) is available only if your IP is registered in U.S, so perhaps you will need to use a proxy**. Once I made sure my IP is U.S. I was able to download the movie anonymously, without setting up an account at vrv.co

**Comment by remitamine** [comment]
```
python __main__.py --geo-verification-proxy localhost:8080 https://vrv.co/watch/G6QWGX3P6/Paradigms-How-We-Know-What-We-Know:The-Science-of-Seeing
[vrv] G6QWGX3P6: Downloading webpage
[vrv] G6QWGX3P6: Downloading en-US MPD information
[vrv] G6QWGX3P6: Downloading en-US m3u8 information
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 87
[download] Destination: The Science of Seeing-G6QWGX3P6.mp4
[download]   1.1% of ~31.48MiB at 500.26KiB/s ETA 02:47
```
