### ISSUE TITLE
HOw to download videos which are played in chrome but not supported by youtube-dl

### ISSUE THREAD

**Issue by sant527** [rg3/youtube-dl#15895]
I want to know how to extract the m3u8 from the following url: "http://www.channeleye.lk/index.php?option=com_content&view=article&id=1847:nidahas-trophy-6th-match-sri-vs-ban-mp4&catid=61:cricket&Itemid=209"

When i tried 

```
$ youtube-dl --verbose --no-mtime --restrict-filenames --no-part --verbose --age-limit 50 --get-filename -f 'worst[height>=360][ext*=mp4]/worst/bestvideo[height>=360][ext=mp4]' -o '%(title)s_fmt_%(format_id)s.%(ext)s' 'http://www.channeleye.lk/index.php?option=com_content&view=article&id=1847:nidahas-trophy-6th-match-sri-vs-ban-mp4&catid=61:cricket&Itemid=209'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--no-mtime', '--restrict-filenames', '--no-part', '--verbose', '--age-limit', '50', '--get-filename', '-f', 'worst[height>=360][ext*=mp4]/worst/bestvideo[height>=360][ext=mp4]', '-o', '%(title)s_fmt_%(format_id)s.%(ext)s', 'http://www.channeleye.lk/index.php?option=com_content&view=article&id=1847:nidahas-trophy-6th-match-sri-vs-ban-mp4&catid=61:cricket&Itemid=209']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.02.11
[debug] Python version 3.6.0 (CPython) - Linux-4.10.2-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 3.2.4, ffprobe 3.2.4, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
WARNING: Falling back on generic information extractor.
ERROR: Unsupported URL: http://www.channeleye.lk/index.php?option=com_content&view=article&id=1847:nidahas-trophy-6th-match-sri-vs-ban-mp4&catid=61:cricket&Itemid=209
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 785, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/generic.py", line 3127, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.channeleye.lk/index.php?option=com_content&view=article&id=1847:nidahas-trophy-6th-match-sri-vs-ban-mp4&catid=61:cricket&Itemid=209

```

Later i went to chrome and i was able to watch the video. So from the network i found the url:
"http://dammikartmp.tulix.tv/dvod/_definst_/cds/eye_programmes/cricket/6th%20match.mp4/chunklist_w533292373.m3u8"

With this url i was able to download the video.

`youtube-dl "http://dammikartmp.tulix.tv/dvod/_definst_/cds/eye_programmes/cricket/6th%20match.mp4/chunklist_w533292373.m3u8"`

Is there any way I can get the m3u8 urls if its not directly supported by youtube-dl

**Comment by dstftw** [comment]
By going to browser's network tools as you already did.

**Comment by sant527** [comment]
but how youtube-dl does it for other sites. How does it search the network urls

**Comment by dstftw** [comment]
Particular site's extractor handles extraction for this site.
