### ISSUE TITLE
url not working: http://www.news.com.au/

### ISSUE THREAD

**Issue by sant527** [rg3/youtube-dl#15909]
```
youtube-dl --verbose --no-mtime --restrict-filenames --no-part --verbose --age-limit 50 --get-filename -f 'worst[height>=360][ext*=mp4]/worst/bestvideo[height>=360][ext=mp4]' -o '%(title)s_fmt_%(format_id)s.%(ext)s' 'http://www.news.com.au/finance/work/leaders/russian-election-2018-vladimir-putin-set-to-win-again/news-story/7569d0c87e583d0a527eb7a9d61030d0?from=rss-basic'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--no-mtime', '--restrict-filenames', '--no-part', '--verbose', '--age-limit', '50', '--get-filename', '-f', 'worst[height>=360][ext*=mp4]/worst/bestvideo[height>=360][ext=mp4]', '-o', '%(title)s_fmt_%(format_id)s.%(ext)s', 'http://www.news.com.au/finance/work/leaders/russian-election-2018-vladimir-putin-set-to-win-again/news-story/7569d0c87e583d0a527eb7a9d61030d0?from=rss-basic']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.02.11
[debug] Python version 3.6.0 (CPython) - Linux-4.10.2-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 3.2.4, ffprobe 3.2.4, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
WARNING: Falling back on generic information extractor.
ERROR: Unsupported URL: http://www.news.com.au/finance/work/leaders/russian-election-2018-vladimir-putin-set-to-win-again/news-story/7569d0c87e583d0a527eb7a9d61030d0?from=rss-basic
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 785, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/generic.py", line 3127, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.news.com.au/finance/work/leaders/russian-election-2018-vladimir-putin-set-to-win-again/news-story/7569d0c87e583d0a527eb7a9d61030d0?from=rss-basic


```

**Comment by remitamine** [comment]
URL from #16820 :
https://www.news.com.au/technology/innovation/inventions/china-looks-to-bolster-surveillance-network-with-birdlike-drones/news-story/fbef8af0169a08cb64ebddbf6cf44981.
URL from #23024 :
https://www.couriermail.com.au/news/queensland/full-list-of-alerts-and-evacuations-for-bushfires/news-story/ca318b6b127eec26e30c18199f1ff1ac
URL from #23025:
https://www.news.com.au/national/queensland/bushfires-tear-through-homes-and-rage-through-to-saturday-morning-live-updates/news-story/ee562f9338946141e80b34210426c2b0
