### ISSUE TITLE
[Errno 36] File name too long on ext4

### ISSUE THREAD

**Issue by mbnoimi** [rg3/youtube-dl#15901]
Hi,

The following bug occurs with most videos named with Arabic characters.

```
youtube-dl -v https://www.youtube.com/watch?v=ej9z7iHbQrU&feature=em-uploademail
[1] 5323
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=ej9z7iHbQrU']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.03.10
[debug] Python version 2.7.12 (CPython) - Linux-4.10.0-38-generic-x86_64-with-LinuxMint-18.3-sylvia
[debug] exe versions: ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1
[debug] Proxy map: {}
[youtube] ej9z7iHbQrU: Downloading webpage
[youtube] ej9z7iHbQrU: Downloading video info webpage
[youtube] ej9z7iHbQrU: Extracting video information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://r4---sn-4g5ednly.googlevideo.com/videoplayback?ipbits=0&mime=video%2Fmp4&initcwndbps=425000&itag=137&fvip=6&expire=1521390146&sparams=aitags%2Cclen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&mt=1521368409&key=yt6&beids=%5B9466591%5D&gir=yes&id=o-ADC9UEeEVtJVg4JGOHO25u5BieQtDOuk3iwnRvVbgFhq&mn=sn-4g5ednly%2Csn-nv47lnls&mm=31%2C26&aitags=137&pl=22&dur=1158.040&lmt=1521368369457417&ip=195.155.234.50&ms=au%2Conr&keepalive=yes&ei=4j2uWt2PI5mZ1gLFgpXABg&mv=m&source=youtube&requiressl=yes&clen=525258987&c=WEB&signature=17C234BD72940B8314578E5E4E1562BCFFBCE296.BC887A9E49ABDB6015D36B243989EC3681C61714&ratebypass=yes'
ERROR: unable to open for writing: [Errno 36] File name too long: '\xe2\x80\xab\xd8\xa7\xd9\x84\xd8\xaf\xd9\x86\xd9\x8a\xd8\xa7 \xd8\xb1\xd9\x88\xd8\xb2\xd9\x8a _ \xd8\xad\xd9\x84\xd9\x82\xd8\xa7\xd8\xaa \xd9\x83\xd8\xa7\xd9\x85\xd9\x84\xd8\xa9 _ \xd8\xb1\xd8\xb3\xd9\x88\xd9\x85 \xd9\x85\xd8\xaa\xd8\xad\xd8\xb1\xd9\x83\xd8\xa9 \xd8\xb9\xd8\xb1\xd8\xa8\xd9\x8a\xd8\xa9 \xd9\x84\xd9\x84\xd8\xa3\xd8\xb7\xd9\x81\xd8\xa7\xd9\x84 _  SPACETOON _ \xd8\xa7\xd9\x84\xd8\xb1\xd8\xb3\xd8\xa7\xd8\xa6\xd9\x84 \xd9\x88\xd8\xa7\xd9\x84\xd8\xaf\xd8\xb9\xd9\x88\xd8\xa7\xd8\xaa-ej9z7iHbQrU.f137.mp4.part'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/downloader/http.py", line 249, in download
    ctx.tmpfilename, ctx.open_mode)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/utils.py", line 457, in sanitize_open
    stream = open(encodeFilename(filename), open_mode)
IOError: [Errno 36] File name too long: '\xe2\x80\xab\xd8\xa7\xd9\x84\xd8\xaf\xd9\x86\xd9\x8a\xd8\xa7 \xd8\xb1\xd9\x88\xd8\xb2\xd9\x8a _ \xd8\xad\xd9\x84\xd9\x82\xd8\xa7\xd8\xaa \xd9\x83\xd8\xa7\xd9\x85\xd9\x84\xd8\xa9 _ \xd8\xb1\xd8\xb3\xd9\x88\xd9\x85 \xd9\x85\xd8\xaa\xd8\xad\xd8\xb1\xd9\x83\xd8\xa9 \xd8\xb9\xd8\xb1\xd8\xa8\xd9\x8a\xd8\xa9 \xd9\x84\xd9\x84\xd8\xa3\xd8\xb7\xd9\x81\xd8\xa7\xd9\x84 _  SPACETOON _ \xd8\xa7\xd9\x84\xd8\xb1\xd8\xb3\xd8\xa7\xd8\xa6\xd9\x84 \xd9\x88\xd8\xa7\xd9\x84\xd8\xaf\xd8\xb9\xd9\x88\xd8\xa7\xd8\xaa-ej9z7iHbQrU.f137.mp4.part'

^C
[1]+  Exit 1                  youtube-dl -v https://www.youtube.com/watch?v=ej9z7iHbQrU$ 
```

**Comment by mbnoimi** [comment]
There is a similar bug #5908 but it's not exactly the same because I didn't encrypt my hard disk so it suppose to work fine with UTF8 encoding.
