### ISSUE TITLE
YouTubeTV does't work

### ISSUE THREAD

**Issue by sou7611** [rg3/youtube-dl#15926]
Login to YTTV fails ... the login page is not the same as regular YT, so ytdl can't parse it.

YTTV has a free trial, easy to test, with pretty much any video.  Access is only possible by clicking the "Already a Member?" link on the redirected page, then entering your google acct info.

youtube-dl --verbose -F -u <username> -p <password> "https://tv.youtube.com/watch/a43h5AS8ik4?vpp=2AEA"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-F', '-u', 'PRIVATE', '-p', 'PRIVATE', 'https://tv.youtube.com/watch/a43h5AS8ik4?vpp=2AEA']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.03.20
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.16299
[debug] exe versions: ffmpeg N-77380-g2dba040
[debug] Proxy map: {}
[generic] a43h5AS8ik4?vpp=2AEA: Requesting header
[redirect] Following redirect to https://tv.youtube.com/welcome/?vpp=2AEA&dst=watch/a43h5AS8ik4
[youtube:user] Downloading login page
[youtube:user] Looking up account info
[youtube:user] Logging in
WARNING: Unable to login: Invalid password
[youtube:user] welcome: Downloading channel page
WARNING: Unable to download webpage: HTTP Error 404: Not Found
[youtube:user] welcome: Downloading page #1
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpbt_jbnlh\build\youtube_dl\extractor\common.py", line 519, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpbt_jbnlh\build\youtube_dl\YoutubeDL.py", line 2199, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default

**Comment by nammakudla** [comment]
I get the following error message for Quest videos using the mpd links while trying to download from youtube-dl

C:\Users\admin>youtube-dl.exe https://dplaynordics-vod-24.akamaized.net/dplaydni/41678/1/dash/1380260001/manifest.mpd?hdnts=st=1536489918~exp=1536576318~acl=/*~hmac=e6f98c244897fde2c9a2c9541341adc16975be33338a10e5d35f291507011f81&bw_start=800
[generic] *~hmac=e6f98c244897fde2c9a2c9541341adc16975be33338a10e5d35f291507011f81: Requesting header
WARNING: Falling back on generic information extractor.
[generic] *~hmac=e6f98c244897fde2c9a2c9541341adc16975be33338a10e5d35f291507011f81: Downloading webpage
[generic] *~hmac=e6f98c244897fde2c9a2c9541341adc16975be33338a10e5d35f291507011f81: Extracting information
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
'bw_start' is not recognized as an internal or external command,
operable program or batch file.

Can some one please help?

**Comment by arcanez** [comment]
#14984

**Comment by johnchoi8** [comment]
This still isn't working. I am able to get logged in, but still won't download. Of note here is that the portion after vp= (redacted for obvious reasons) is necessary to paste it in to a browser window to have it open the recorded video directly. Somehow it is adding the "&dst=watch%2FcqH1uQ4ilPI" on the redirect and I am not sure why that is. I have tested pasting in to a browser and then logging in. It works to play directly when I do that. 

D:\Video\>youtube-dl --verbose -u account@gmail.com -p password "https://tv.youtube.com/watch/cqH1uQ4ilPI?vpp=6gEJCOCXz-EFEMwcgALgl8_hBQ%3D%3D&vp=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-u', 'PRIVATE', '-p', 'PRIVATE', 'https://tv.youtube.com/watch/cqH1uQ4ilPI?vpp=6gEJCOCXz-EFEMwcgALgl8_hBQ%3D%3D&vp=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.01.02
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: none
[debug] Proxy map: {}
[generic] cqH1uQ4ilPI?vpp=6gEJCOCXz-EFEMwcgALgl8_hBQ==&vp=0gERCgkI4JfP4QUQzBwY4JfP4QU=: Requesting header
[redirect] Following redirect to https://tv.youtube.com/welcome/?vpp=6gEJCOCXz-EFEMwcgALgl8_hBQ%3D%3D&vp=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&dst=watch%2FcqH1uQ4ilPI
[youtube:user] Downloading login page
[youtube:user] Looking up account info
[youtube:user] Logging in
[youtube:user] Checking cookie
[youtube:user] welcome: Downloading channel page
WARNING: Unable to download webpage: HTTP Error 404: Not Found
[youtube:user] welcome: Downloading page #1
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5nai6j15\build\youtube_dl\extractor\common.py", line 605, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5nai6j15\build\youtube_dl\YoutubeDL.py", line 2212, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default

**Comment by CYRiXplaysHalo** [comment]
Any update on this?

**Comment by tml** [comment]
Using cookie login instead of u/p login (cookie values replaced with string `<redacted>`)

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-F', '--print-traffic', '--cookie', '/zpool1/media/youtube-dl/tv/cookies.txt', 'https://tv.youtube.com/watch/QwAY9Ip2yp8?vpp=2AEA']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.07.16
[debug] Python version 3.7.3 (CPython) - Linux-4.9.73-0-hardened-x86_64-with
[debug] exe versions: none
[debug] Proxy map: {}
[generic] QwAY9Ip2yp8?vpp=2AEA: Requesting header
WARNING: Falling back on generic information extractor.
[generic] QwAY9Ip2yp8?vpp=2AEA: Downloading webpage
send: b'HEAD /watch/QwAY9Ip2yp8?vpp=2AEA HTTP/1.1\r\nHost: tv.youtube.com\r\nCookie: <redacted>\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.57 Safari/537.36\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Encoding: gzip, deflate\r\nAccept-Language: en-us,en;q=0.5\r\nConnection: close\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: X-Content-Type-Options: nosniff
header: Strict-Transport-Security: max-age=31536000
header: Content-Encoding: gzip
header: Expires: Tue, 27 Apr 1971 19:44:06 EST
header: Cache-Control: no-cache
header: Feature-Policy: picture-in-picture 'none'
header: Content-Type: text/html; charset=utf-8
header: X-Frame-Options: SAMEORIGIN
header: Date: Wed, 24 Jul 2019 00:31:32 GMT
header: Server: YouTube Frontend Proxy
header: X-XSS-Protection: 0
header: Set-Cookie: <redacted>
header: Transfer-Encoding: chunked
header: Alt-Svc: quic=":443"; ma=2592000; v="46,43,39"
header: Connection: close
[generic] QwAY9Ip2yp8?vpp=2AEA: Extracting information
send: b'GET /watch/QwAY9Ip2yp8?vpp=2AEA HTTP/1.1\r\nHost: tv.youtube.com\r\nCookie: <redacted>\r\nAccept-Encoding: *\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.57 Safari/537.36\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Language: en-us,en;q=0.5\r\nConnection: close\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Cache-Control: no-cache
header: X-Content-Type-Options: nosniff
header: X-Frame-Options: SAMEORIGIN
header: Expires: Tue, 27 Apr 1971 19:44:06 EST
header: Feature-Policy: picture-in-picture 'none'
header: Content-Type: text/html; charset=utf-8
header: Strict-Transport-Security: max-age=31536000
header: Date: Wed, 24 Jul 2019 00:31:32 GMT
header: Server: YouTube Frontend Proxy
header: X-XSS-Protection: 0
header: Set-Cookie: <redacted>
header: Alt-Svc: quic=":443"; ma=2592000; v="46,43,39"
header: Accept-Ranges: none
header: Vary: Accept-Encoding
header: Connection: close
ERROR: Unsupported URL: https://tv.youtube.com/watch/QwAY9Ip2yp8?vpp=2AEA
Traceback (most recent call last):
  File "/home/joey/.virtualenvs/main/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/home/joey/.virtualenvs/main/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/home/joey/.virtualenvs/main/lib/python3.7/site-packages/youtube_dl/extractor/generic.py", line 3333, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://tv.youtube.com/watch/QwAY9Ip2yp8?vpp=2AEA


```

**Comment by harryt04** [comment]
Any update on this? I would LOVE YT-TV support. My python ability isn't sufficient to try and figure it out and contribute on my own, though.

**Comment by qome** [comment]
I am not having this issue, despite my issue being closed and locked as a duplicate.

I am not getting an invalid password warning, I am not getting a failure to download the login page, and I do not have any form of two-factor authentication enabled.

You're kind of a jerk to people who are just trying to report bugs dude.

**Comment by darthnithin** [comment]
> 
> 
> I am not having this issue, despite my issue being closed and locked as a duplicate.
> 
> I am not getting an invalid password warning, I am not getting a failure to download the login page, and I do not have any form of two-factor authentication enabled, and I'm not using YouTube TV.
> 
> You're kind of a jerk to people who are just trying to report bugs dude.
> 
> There are no currently open for comment bug reports about my issue, or the issue #11270 I linked.

By you are not having this issue do you mean you are able to download from youtubetv? how?
