### ISSUE TITLE
Support request for yourlisten.com

### ISSUE THREAD

**Issue by Hackerpcs** [rg3/youtube-dl#15959]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.03.20*.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.03.20**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Site support request (request for adding support for a new site)

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

```
youtube-dl.exe -v https://yourlisten.com/Metrosport/EzY2ExND
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://yourlisten.com/Metrosport/EzY2ExND']
[debug] Encodings: locale cp1253, fs mbcs, out cp737, pref cp1253
[debug] youtube-dl version 2018.03.20
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-90061-gfb580731c1, ffprobe N-90061-gfb580731c1, phantomjs 2.1.1
[debug] Proxy map: {'ftp': 'ftp://127.0.0.1:3128', 'https': 'https://127.0.0.1:3128', 'http': 'http://127.0.0.1:3128'}
[generic] EzY2ExND: Requesting header
WARNING: Falling back on generic information extractor.
[generic] EzY2ExND: Downloading webpage
[generic] EzY2ExND: Extracting information
ERROR: Unsupported URL: https://yourlisten.com/Metrosport/EzY2ExND
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpbt_jbnlh\build\youtube_dl\YoutubeDL.py", line 785, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpbt_jbnlh\build\youtube_dl\extractor\common.py", line 440, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpbt_jbnlh\build\youtube_dl\extractor\generic.py", line 3161, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://yourlisten.com/Metrosport/EzY2ExND
```
---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://yourlisten.com/Metrosport/EzY2ExND
- Plenty of similar links: https://yourlisten.com/Metrosport

---

Audio hosting site

**Comment by Vangelis66** [comment]
`https://yourlisten.com/Metrosport/EzY2ExND` => simple progressive download (streaming) of file: 

`https://yourlisten.com/player/director/17718688.mp3`

**Comment by Hackerpcs** [comment]
I know, I'm asking for support to mass-download links or play directly with a simple mpv url
