### ISSUE TITLE
Support request for skai.gr

### ISSUE THREAD

**Issue by Hackerpcs** [rg3/youtube-dl#15962]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.03.20*.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.03.20**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Site support request (request for adding support for a new site)

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output:

```
youtube-dl.exe -v http://www.skai.gr/player/TV/?mmid=303411
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://www.skai.gr/player/TV/?mmid=303411']
[debug] Encodings: locale cp1253, fs mbcs, out cp737, pref cp1253
[debug] youtube-dl version 2018.03.20
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-90399-ged0e0fe102, ffprobe N-90399-ged0e0fe102, phantomjs 2.1.1
[debug] Proxy map: {'https': 'https://127.0.0.1:3128', 'ftp': 'ftp://127.0.0.1:3128', 'http': 'http://127.0.0.1:3128'}
[generic] ?mmid=303411: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ?mmid=303411: Downloading webpage
[generic] ?mmid=303411: Extracting information
[download] Downloading playlist: SURVIVOR
[generic] playlist SURVIVOR: Collected 2 video ids (downloading 2 of them)
[download] Downloading video 1 of 2
[youtube] _jJt22AHqV0: Downloading webpage
[youtube] _jJt22AHqV0: Downloading video info webpage
[youtube] _jJt22AHqV0: Extracting video information
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on 'https://.googlevideo.com/videoplayback?'
[download] Destination: IHT Global Conversation - Democracy Under Pressure (Greek)-_jJt22AHqV0.f134.mp4
[download]   0.1% of 337.24MiB at 751.47KiB/s ETA 07:38
ERROR: Interrupted by user
```
Interrupted because it detected two irrelevant YouTube videos

```
youtube-dl.exe -v http://survivor.skai.gr/survivor-episodio-37-19032018/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://survivor.skai.gr/survivor-episodio-37-19032018/']
[debug] Encodings: locale cp1253, fs mbcs, out cp737, pref cp1253
[debug] youtube-dl version 2018.03.20
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-90399-ged0e0fe102, ffprobe N-90399-ged0e0fe102, phantomjs 2.1.1
[debug] Proxy map: {'http': 'http://127.0.0.1:3128', 'ftp': 'ftp://127.0.0.1:3128', 'https': 'https://127.0.0.1:3128'}
[generic] survivor-episodio-37-19032018: Requesting header
WARNING: Falling back on generic information extractor.
[generic] survivor-episodio-37-19032018: Downloading webpage
[generic] survivor-episodio-37-19032018: Extracting information
ERROR: Unsupported URL: http://survivor.skai.gr/survivor-episodio-37-19032018/
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpbt_jbnlh\build\youtube_dl\YoutubeDL.py", line 785, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpbt_jbnlh\build\youtube_dl\extractor\common.py", line 440, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpbt_jbnlh\build\youtube_dl\extractor\generic.py", line 3161, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: http://survivor.skai.gr/survivor-episodio-37-19032018/
```
---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://www.skai.gr/player/TV/?mmid=303411
- Single video: http://survivor.skai.gr/survivor-episodio-37-19032018/
- Show dropdown list: http://www.skai.gr/tv/show/?showid=66630

---

Web TV site of Greek TV station Skai

**Comment by Vangelis66** [comment]
`http://www.skai.gr/player/TV/?mmid=303411` => `http://videostream.skai.gr/GrCyTargeting/Gr/survivor20180321.mp4.m3u8`

`http://survivor.skai.gr/survivor-episodio-37-19032018/` => progressive download 
`http://download.skai.gr/GrCyTargeting/Gr/survivor20180319.mp4`

Both streams probably blocked from outside of Greece...
