### ISSUE TITLE
Unable to extract OpenGraph title

### ISSUE THREAD

**Issue by igordi8** [rg3/youtube-dl#16011]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.03.26.1*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2018.03.26.1**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.prosieben.de/tv/late-night-berlin-mit-klaas-heufer-umlauf/video/13-ganze-folge-late-night-berlin-3-ganze-folge']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.03.26.1
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.16299
[debug] exe versions: none
[debug] Proxy map: {}
[prosiebensat1] tv/late-night-berlin-mit-klaas-heufer-umlauf/video/13-ganze-folge-late-night-berlin-3-ganze-folge: Downloading webpage
ERROR: Unable to extract OpenGraph title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmph9lcnopy\build\youtube_dl\YoutubeDL.py", line 785, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmph9lcnopy\build\youtube_dl\extractor\common.py", line 440, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmph9lcnopy\build\youtube_dl\extractor\prosiebensat1.py", line 450, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmph9lcnopy\build\youtube_dl\extractor\prosiebensat1.py", line 398, in _extract_clip
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmph9lcnopy\build\youtube_dl\extractor\common.py", line 920, in _og_search_title
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmph9lcnopy\build\youtube_dl\extractor\common.py", line 908, in _og_search_property
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmph9lcnopy\build\youtube_dl\extractor\common.py", line 808, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract OpenGraph title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.prosieben.de/tv/late-night-berlin-mit-klaas-heufer-umlauf/video/13-ganze-folge-late-night-berlin-3-ganze-folge
- Single video: https://www.prosieben.de/tv/late-night-berlin-mit-klaas-heufer-umlauf/video/12-ganze-folge-late-night-berlin-2-ganze-folge

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

Last week I was able to download the second link I gave above (with an older version of youtube-dl.exe). But today both links provided doesn't work (anymore), giving me the OpenGraph-Error.
Thanks for reading my issue!

**Comment by igordi8** [comment]
I tried to download the given links again and it worked fine. I don't know why and I don't know if I should close this issue now...

**Comment by efenka** [comment]
I think i have a similar issue (I can file a different report if its something different):

```
$ youtube-dl --verbose 'https://www.prosieben.de/tv/germanys-next-topmodel/episoden/138-episode-8-magic-bride'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.prosieben.de/tv/germanys-next-topmodel/episoden/138-episode-8-magic-bride']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.03.26.1
[debug] Python version 2.7.12 (CPython) - Linux-4.4.0-116-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 2.8.11-0ubuntu0.16.04.1, avprobe 2.8.11-0ubuntu0.16.04.1, ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1
[debug] Proxy map: {}
[prosiebensat1] tv/germanys-next-topmodel/episoden/138-episode-8-magic-bride: Downloading webpage
[prosiebensat1] 2847174: Downloading videos JSON
ERROR: An extractor error has occurred. (caused by KeyError(u'sources',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/prosiebensat1.py", line 450, in _real_extract
    return self._extract_clip(url, webpage)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/prosiebensat1.py", line 399, in _extract_clip
    info = self._extract_video_info(url, clip_id)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/prosiebensat1.py", line 35, in _extract_video_info
    source_ids = [compat_str(source['id']) for source in video['sources']]
KeyError: u'sources'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 785, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 453, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
ExtractorError: An extractor error has occurred. (caused by KeyError(u'sources',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
