### ISSUE TITLE
Telequebec De garde 247

### ISSUE THREAD

**Issue by stefer09** [rg3/youtube-dl#16045]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.03.26.1*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2018.03.26.1**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [x ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```


D:\youtube-dl>youtube-dl.exe http://zonevideo.telequebec.tv/media/22692/profession-medecin/de-garde-247 -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['http://zonevideo.telequebec.tv/media/22692/profession-medecin/de-garde-247', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.03.26.1
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.16299
[debug] exe versions: ffmpeg N-90518-gaf043b839c, ffprobe N-90518-gaf043b839c
[debug] Proxy map: {}
[TeleQuebec] 22692: Downloading JSON metadata
[debug] Using fake IP 99.254.2.70 (CA) as X-Forwarded-For.
[limelight] 78de178d22f340deb72f7715bbaddf8d: Downloading PlaylistService getPlaylistByMediaId JSON
ERROR: 78de178d22f340deb72f7715bbaddf8d: Failed to parse JSON  (caused by ValueError('Expecting value: line 1 column 1 (char 0)',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmph9lcnopy\build\youtube_dl\extractor\common.py", line 702, in _parse_json
  File "C:\Python\Python34\lib\json\__init__.py", line 318, in loads
  File "C:\Python\Python34\lib\json\decoder.py", line 343, in decode
  File "C:\Python\Python34\lib\json\decoder.py", line 361, in raw_decode
ValueError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmph9lcnopy\build\youtube_dl\extractor\common.py", line 702, in _parse_json
  File "C:\Python\Python34\lib\json\__init__.py", line 318, in loads
  File "C:\Python\Python34\lib\json\decoder.py", line 343, in decode
  File "C:\Python\Python34\lib\json\decoder.py", line 361, in raw_decode
ValueError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmph9lcnopy\build\youtube_dl\YoutubeDL.py", line 785, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmph9lcnopy\build\youtube_dl\extractor\common.py", line 440, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmph9lcnopy\build\youtube_dl\extractor\limelight.py", line 290, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmph9lcnopy\build\youtube_dl\extractor\limelight.py", line 88, in _extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmph9lcnopy\build\youtube_dl\extractor\limelight.py", line 73, in _call_playlist_service
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmph9lcnopy\build\youtube_dl\extractor\common.py", line 696, in _download_json
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmph9lcnopy\build\youtube_dl\extractor\common.py", line 706, in _parse_json
youtube_dl.utils.ExtractorError: 78de178d22f340deb72f7715bbaddf8d: Failed to parse JSON  (caused by ValueError('Expecting value: line 1 column 1 (char 0)',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
http://zonevideo.telequebec.tv/media/22692/profession-medecin/de-garde-247
http://zonevideo.telequebec.tv/media/23914/adrenaline/de-garde-247

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Was trying to download a Telequebec show, called De Garde 24/7.  Wasn't working until i found out that i have to use their zonevideo site.  I did, but it still won't work.  Any ideas?

**Comment by dstftw** [comment]
Post the output with `--dump-pages`.

**Comment by stefer09** [comment]
SORRY!  That was my bad....  I have a new installation of Pi-hole on my network to block ads and for some reason it stopped me from getting the video.  Oddly enough, they play all fine on the website (I always make sure they do before trying to pull them with youtube-dl)
Had to whitelist this url in order for it to work : 

production-ps.lvp.llnw.net
