### ISSUE TITLE
[Odnoklassniki] Unsupported URL

### ISSUE THREAD

**Issue by gjedeer** [rg3/youtube-dl#16081]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.04.03**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl -v 'https://m.ok.ru/dk?st.cmd=movieLayer&st.discId=863789452017&st.retLoc=friend&st.rtu=%2Fdk%3Fst.cmd%3DfriendMovies%26st.mode%3Down%26st.mrkId%3D%257B%2522uploadedMovieMarker%2522%253A%257B%2522marker%2522%253A%25221519410114503%2522%252C%2522hasMore%2522%253Atrue%257D%252C%2522sharedMovieMarker%2522%253A%257B%2522marker%2522%253Anull%252C%2522hasMore%2522%253Afalse%257D%257D%26st.friendId%3D561722190321%26st.frwd%3Don%26_prevCmd%3DfriendMovies%26tkn%3D7257&st.discType=MOVIE&st.mvId=863789452017&_prevCmd=friendMovies&tkn=3648#lst#'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://m.ok.ru/dk?st.cmd=movieLayer&st.discId=863789452017&st.retLoc=friend&st.rtu=%2Fdk%3Fst.cmd%3DfriendMovies%26st.mode%3Down%26st.mrkId%3D%257B%2522uploadedMovieMarker%2522%253A%257B%2522marker%2522%253A%25221519410114503%2522%252C%2522hasMore%2522%253Atrue%257D%252C%2522sharedMovieMarker%2522%253A%257B%2522marker%2522%253Anull%252C%2522hasMore%2522%253Afalse%257D%257D%26st.friendId%3D561722190321%26st.frwd%3Don%26_prevCmd%3DfriendMovies%26tkn%3D7257&st.discType=MOVIE&st.mvId=863789452017&_prevCmd=friendMovies&tkn=3648#lst#']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.04.03
[debug] Python version 2.7.12 (CPython) - Linux-4.13.0-37-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1, phantomjs 2.1.3
[debug] Proxy map: {}
[generic] dk?st.cmd=movieLayer&st.discId=863789452017&st.retLoc=friend&st.rtu=/dk?st.cmd=friendMovies&st.mode=own&st.mrkId=%7B%22uploadedMovieMarker%22%3A%7B%22marker%22%3A%221519410114503%22%2C%22hasMore%22%3Atrue%7D%2C%22sharedMovieMarker%22%3A%7B%22marker%22%3Anull%2C%22hasMore%22%3Afalse%7D%7D&st.friendId=561722190321&st.frwd=on&_prevCmd=friendMovies&tkn=7257&st.discType=MOVIE&st: Requesting header
[redirect] Following redirect to https://m.ok.ru/dk?st.cmd=movieLayer&st.discId=863789452017&st.retLoc=friend&st.rtu=%2Fdk%3Fst.cmd%3DfriendMovies%26st.mode%3Down%26st.mrkId%3D%257B%2522uploadedMovieMarker%2522%253A%257B%2522marker%2522%253A%25221519410114503%2522%252C%2522hasMore%2522%253Atrue%257D%252C%2522sharedMovieMarker%2522%253A%257B%2522marker%2522%253Anull%252C%2522hasMore%2522%253Afalse%257D%257D%26st.friendId%3D561722190321%26st.frwd%3Don%26_prevCmd%3DfriendMovies%26tkn%3D7257&st.discType=MOVIE&st.mvId=863789452017&_prevCmd=friendMovies&tkn=3648#lst
[generic] dk?st.cmd=movieLayer&st.discId=863789452017&st.retLoc=friend&st.rtu=/dk?st.cmd=friendMovies&st.mode=own&st.mrkId=%7B%22uploadedMovieMarker%22%3A%7B%22marker%22%3A%221519410114503%22%2C%22hasMore%22%3Atrue%7D%2C%22sharedMovieMarker%22%3A%7B%22marker%22%3Anull%2C%22hasMore%22%3Afalse%7D%7D&st.friendId=561722190321&st.frwd=on&_prevCmd=friendMovies&tkn=7257&st.discType=MOVIE&st: Requesting header
WARNING: Falling back on generic information extractor.
[generic] dk?st.cmd=movieLayer&st.discId=863789452017&st.retLoc=friend&st.rtu=/dk?st.cmd=friendMovies&st.mode=own&st.mrkId=%7B%22uploadedMovieMarker%22%3A%7B%22marker%22%3A%221519410114503%22%2C%22hasMore%22%3Atrue%7D%2C%22sharedMovieMarker%22%3A%7B%22marker%22%3Anull%2C%22hasMore%22%3Afalse%7D%7D&st.friendId=561722190321&st.frwd=on&_prevCmd=friendMovies&tkn=7257&st.discType=MOVIE&st: Downloading webpage
[generic] dk?st.cmd=movieLayer&st.discId=863789452017&st.retLoc=friend&st.rtu=/dk?st.cmd=friendMovies&st.mode=own&st.mrkId=%7B%22uploadedMovieMarker%22%3A%7B%22marker%22%3A%221519410114503%22%2C%22hasMore%22%3Atrue%7D%2C%22sharedMovieMarker%22%3A%7B%22marker%22%3Anull%2C%22hasMore%22%3Afalse%7D%7D&st.friendId=561722190321&st.frwd=on&_prevCmd=friendMovies&tkn=7257&st.discType=MOVIE&st: Extracting information
ERROR: Unsupported URL: https://m.ok.ru/dk?st.cmd=movieLayer&st.discId=863789452017&st.retLoc=friend&st.rtu=%2Fdk%3Fst.cmd%3DfriendMovies%26st.mode%3Down%26st.mrkId%3D%257B%2522uploadedMovieMarker%2522%253A%257B%2522marker%2522%253A%25221519410114503%2522%252C%2522hasMore%2522%253Atrue%257D%252C%2522sharedMovieMarker%2522%253A%257B%2522marker%2522%253Anull%252C%2522hasMore%2522%253Afalse%257D%257D%26st.friendId%3D561722190321%26st.frwd%3Don%26_prevCmd%3DfriendMovies%26tkn%3D7257&st.discType=MOVIE&st.mvId=863789452017&_prevCmd=friendMovies&tkn=3648#lst
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 2205, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/compat.py", line 2542, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/compat.py", line 2531, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 1, column 677
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 785, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 3143, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://m.ok.ru/dk?st.cmd=movieLayer&st.discId=863789452017&st.retLoc=friend&st.rtu=%2Fdk%3Fst.cmd%3DfriendMovies%26st.mode%3Down%26st.mrkId%3D%257B%2522uploadedMovieMarker%2522%253A%257B%2522marker%2522%253A%25221519410114503%2522%252C%2522hasMore%2522%253Atrue%257D%252C%2522sharedMovieMarker%2522%253A%257B%2522marker%2522%253Anull%252C%2522hasMore%2522%253Afalse%257D%257D%26st.friendId%3D561722190321%26st.frwd%3Don%26_prevCmd%3DfriendMovies%26tkn%3D7257&st.discType=MOVIE&st.mvId=863789452017&_prevCmd=friendMovies&tkn=3648#lst
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://m.ok.ru/dk?st.cmd=movieLayer&st.discId=863789452017&st.retLoc=friend&st.rtu=%2Fdk%3Fst.cmd%3DfriendMovies%26st.mode%3Down%26st.mrkId%3D%257B%2522uploadedMovieMarker%2522%253A%257B%2522marker%2522%253A%25221519410114503%2522%252C%2522hasMore%2522%253Atrue%257D%252C%2522sharedMovieMarker%2522%253A%257B%2522marker%2522%253Anull%252C%2522hasMore%2522%253Afalse%257D%257D%26st.friendId%3D561722190321%26st.frwd%3Don%26_prevCmd%3DfriendMovies%26tkn%3D7257&st.discType=MOVIE&st.mvId=863789452017&_prevCmd=friendMovies&tkn=3648#lst#

---

### Description of your *issue*, suggested solution and other information

Can't download a video from ok.ru - Unsupported URL

**Comment by WolfganP** [comment]
You have too much stuff in that URL. Navigate the site and somehow reach a simpler URL, ie:on the format https://ok.ru/video/1110925839033
It works for me.

**Comment by gjedeer** [comment]
Okay I tried different numbers in my URL and st.mvId URL variable worked:

https://ok.ru/video/863789452017
