### ISSUE TITLE
[Openload] Unable to extract stream URL

### ISSUE THREAD

**Issue by Rudloff** [rg3/youtube-dl#16136]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.04.09*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.04.09**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://openload.co/f/kUEfGclsU9o']
[debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8
[debug] youtube-dl version 2018.04.09
[debug] Git HEAD: 0d26920
[debug] Python version 2.7.13 (CPython) - Linux-4.9.0-6-amd64-x86_64-with-debian-9.4
[debug] exe versions: avconv 3.2.10-1, avprobe 3.2.10-1, ffmpeg 3.4.1-static, ffprobe 3.2.10-1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[Openload] kUEfGclsU9o: Downloading embed webpage
[Openload] kUEfGclsU9o: Executing JS on webpage
ERROR: Unable to extract stream URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/pierre/www/alltube/vendor/rg3/youtube-dl/youtube_dl/YoutubeDL.py", line 789, in extract_info
    ie_result = ie.extract(url)
  File "/home/pierre/www/alltube/vendor/rg3/youtube-dl/youtube_dl/extractor/common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "/home/pierre/www/alltube/vendor/rg3/youtube-dl/youtube_dl/extractor/openload.py", line 344, in _real_extract
    'stream URL'))
  File "/home/pierre/www/alltube/vendor/rg3/youtube-dl/youtube_dl/extractor/common.py", line 808, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract stream URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by dstftw** [comment]
No such commit 0d26920.

**Comment by Rudloff** [comment]
I was running youtube-dl inside another Git project folder so it picked the commit from this other project. I'm running the 2018.04.09 release from [its zip file](https://github.com/rg3/youtube-dl/archive/2018.04.09.zip).

**Comment by dstftw** [comment]
Most likely you haven't picked all relevant commits.

**Comment by Rudloff** [comment]
I can also reproduce on the latest master:
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://openload.co/f/kUEfGclsU9o']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.04.09
[debug] Git HEAD: f7f9757ef
[debug] Python version 2.7.13 (CPython) - Linux-4.9.0-6-amd64-x86_64-with-debian-9.4
[debug] exe versions: avconv 3.2.10-1, avprobe 3.2.10-1, ffmpeg 3.2.10-1, ffprobe 3.2.10-1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[Openload] kUEfGclsU9o: Downloading embed webpage
[Openload] kUEfGclsU9o: Executing JS on webpage
ERROR: Unable to extract stream URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/pierre/www/youtube-dl/youtube_dl/YoutubeDL.py", line 789, in extract_info
    ie_result = ie.extract(url)
  File "/home/pierre/www/youtube-dl/youtube_dl/extractor/common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "/home/pierre/www/youtube-dl/youtube_dl/extractor/openload.py", line 344, in _real_extract
    'stream URL'))
  File "/home/pierre/www/youtube-dl/youtube_dl/extractor/common.py", line 808, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract stream URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by ozcs** [comment]
just an update that I fixed my problem, it was sever side, phantomJs issue, more info on issue #16205
