### ISSUE TITLE
[PornHubUserVideos] Unable to extract encoded url for public playlist

### ISSUE THREAD

**Issue by Celti** [rg3/youtube-dl#16199]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.04.16*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2018.04.16**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
debug] System config: []
[debug] User config: ['--no-mtime']
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.pornhub.com/users/rosieandalena/videos/public']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.04.16
[debug] Python version 3.6.4 (CPython) - Linux-4.15.15-1-zen-x86_64-with-arch
[debug] exe versions: ffmpeg 3.4.2, ffprobe 3.4.2, rtmpdump 2.4
[debug] Proxy map: {}
[PornHubUserVideos] rosieandalena: Downloading page 1
[PornHubUserVideos] rosieandalena: Downloading page 2
[PornHubUserVideos] rosieandalena: Downloading page 3
[download] Downloading playlist: rosieandalena
[PornHubUserVideos] playlist rosieandalena: Collected 84 video ids (downloading 84 of them)
[download] Downloading video 1 of 84
[PornHub] ph5acac96dc7513: Downloading webpage
[PornHub] ph5acac96dc7513: Downloading webpage
ERROR: Unable to extract encoded url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/celti/youtube-dl/youtube_dl/YoutubeDL.py", line 789, in extract_info
    ie_result = ie.extract(url)
  File "/home/celti/youtube-dl/youtube_dl/extractor/common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "/home/celti/youtube-dl/youtube_dl/extractor/pornhub.py", line 141, in _real_extract
    'encoded url').split(';')
  File "/home/celti/youtube-dl/youtube_dl/extractor/common.py", line 808, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract encoded url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

---
### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Playlist: (public user playlist) https://www.pornhub.com/users/rosieandalena/videos/public

---

### Description of your *issue*, suggested solution and other information
Mass downloads of public user playlists from PornHub do not appear to be working. Downloads of single videos appear to be working fine, it is *only* playlists that appear to be having issues. I have seen a couple other very similar bug reports closed after a (unheeded) request for `--dump-pages` output, so I am including that in a comment.

**Comment by Celti** [comment]
Apparently the log is too large to fit into a comment, so it is attached as [ytdl.log](https://github.com/rg3/youtube-dl/files/1916003/ytdl.log).
