### ISSUE TITLE
Add site support for motortrendondemand.com

### ISSUE THREAD

**Issue by csprl** [rg3/youtube-dl#16211]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.04.16*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.04.16**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.motortrendondemand.com/detail/el-paso-to-la-the-hard-way/0_dmio874f/']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.04.16
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.16299
[debug] exe versions: ffmpeg N-77045-ga16243a, ffprobe N-77045-ga16243a
[debug] Proxy map: {}
[generic] 0_dmio874f: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 0_dmio874f: Downloading webpage
[generic] 0_dmio874f: Extracting information
ERROR: Unsupported URL: https://www.motortrendondemand.com/detail/el-paso-to-la-the-hard-way/0_dmio874f/
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9r95p1_v\build\youtube_dl\YoutubeDL.py", line 789, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9r95p1_v\build\youtube_dl\extractor\common.py", line 440, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp9r95p1_v\build\youtube_dl\extractor\generic.py", line 3166, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.motortrendondemand.com/detail/el-paso-to-la-the-hard-way/0_dmio874f/
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.motortrendondemand.com/detail/el-paso-to-la-the-hard-way/0_dmio874f/
- Another single video: https://www.motortrendondemand.com/detail/700-horsepower-2-400-miles-crusher-camaro-engine-swap-aftermath/0_zn84jd9j/

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

The site uses Kaltura to stream the video but the Kaltura extractor doesn't seem to recognize/support it. This results in `ERROR: Unsupported URL`. This could be fixed by either modifying the existing Kaltura extractor (I think) or by creating a new one specifically for this site. The generic extractor seems to be able to download the video if a direct m3u8 link is passed (inspect element -> network tab -> set `a.m3u8` as filter and copy URL). The recent commit e30991f9206f98605ba6c4880ed40ad5556fa0b8 did not address this issue either.

Note: The site likes to prompt users who use adblocking software to login/create an account, pausing or whitelisting the site should get past it.

**Comment by bircoe** [comment]
Seconded, I have a subscription but none of my devices have MOTD apps available so it would be nice to be able to download the streams and view them via Plex.

If there's any additional information I can provide please let me know.

**Comment by hyiltiz** [comment]
The method mention in OP worked for the site reported at #16337. I do use uBlock Origin and it didn't interfere with playing or downloading the video at several browsers and several network environments (school, work, home etc.)
