### ISSUE TITLE
Download Facebook videos from feed as playlist

### ISSUE THREAD

**Issue by forthrin** [rg3/youtube-dl#16221]
## Please follow the guide below

- [X] I've **verified** and **I assure** that I'm running youtube-dl **2018.04.16**
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

```
$ youtube-dl --verbose 'https://www.facebook.com/SKAMaustin/'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.facebook.com/SKAMaustin/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.04.16
[debug] Python version 2.7.10 (CPython) - Darwin-16.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.4.2, ffprobe 3.4.2, rtmpdump 2.4
[debug] Proxy map: {}
[generic] SKAMaustin: Requesting header
WARNING: Falling back on generic information extractor.
[generic] SKAMaustin: Downloading webpage
[generic] SKAMaustin: Extracting information
[redirect] Following redirect to https://www.facebook.com/SKAMaustin/?_fb_noscript=1
[generic] ?_fb_noscript=1: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ?_fb_noscript=1: Downloading webpage
[generic] ?_fb_noscript=1: Extracting information
ERROR: Unsupported URL: https://www.facebook.com/SKAMaustin/?_fb_noscript=1
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2216, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2542, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2531, in _XML
    parser.feed(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 3, column 1530
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 789, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3166, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.facebook.com/SKAMaustin/?_fb_noscript=1
```

For some reason, these Facebook videos fall back to "generic extractor" / "UnsupportedError" even though Facebook is generally supported by `youtube-dl`.

**Comment by forthrin** [comment]
OK, I found out that the problem is the videos are embedded in the feed, with no direct link available to the user. The videos later were posted with their own URL, and then the downloading works as normal. So the request would be to support downloads from the feed, in the form of "playlist download", which I suppose would be useful to people who want to stay updated on all videos posted in a feed.
