### ISSUE TITLE
www.puls4.com  video leads to a KeyError: u'mediaCurrent'

### ISSUE THREAD

**Issue by avl42** [rg3/youtube-dl#16242]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.04.16**
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

```
$ youtube-dl -v "https://www.puls4.com/sehr-witzig/ganze-folgen/Sehr-witzig\!-Der-Witze-Stammtisch-vom-16.04.2018-Tricky-Niki-627662" 
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.puls4.com/sehr-witzig/ganze-folgen/Sehr-witzig\\!-Der-Witze-Stammtisch-vom-16.04.2018-Tricky-Niki-627662']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.04.16
[debug] Python version 2.7.12 (CPython) - Linux-4.4.0-119-generic-i686-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 2.8.14-0ubuntu0.16.04.1, avprobe 2.8.14-0ubuntu0.16.04.1, ffmpeg 2.8.14-0ubuntu0.16.04.1, ffprobe 2.8.14-0ubuntu0.16.04.1
[debug] Proxy map: {}
[Puls4] sehr-witzig/ganze-folgen/Sehr-witzig\!-Der-Witze-Stammtisch-vom-16.04.2018-Tricky-Niki-627662: Downloading JSON metadata
[Puls4] /api/json-fe/components/153530/153530: Downloading JSON metadata
ERROR: An extractor error has occurred. (caused by KeyError(u'mediaCurrent',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/avl/bin/youtube-dl/youtube_dl/extractor/common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "/home/avl/bin/youtube-dl/youtube_dl/extractor/puls4.py", line 42, in _real_extract
    content_path)['mediaCurrent']
KeyError: u'mediaCurrent'
Traceback (most recent call last):
  File "/home/avl/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 789, in extract_info
    ie_result = ie.extract(url)
  File "/home/avl/bin/youtube-dl/youtube_dl/extractor/common.py", line 453, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
ExtractorError: An extractor error has occurred. (caused by KeyError(u'mediaCurrent',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

There have been old issues about this site, but this exact symptom seemed to be new.

**Comment by avl42** [comment]
I apologize again... it turned out to be wrong !-quoting on my side.  I used "...\!..." but should have used "..."\!"..."
