### ISSUE TITLE
[PornHub] youtube_dl.utils.RegexNotFoundError: Unable to extract encoded url;

### ISSUE THREAD

**Issue by krtjfghnazesdrryjsredthsedrhj** [rg3/youtube-dl#16262]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.04.16*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.04.16**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
---
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: ['--ignore-errors', '-o', '%(uploader)s (%(uploader_id)s)/%(upload_date)s - %(title)s - (%(duration)ss) [%(resolution)s] [%(id)s].%(ext)s', '--download-archive', 'youtube-dl-archive.txt', '-a', 'youtube-dl-channels-test.txt', '--dump-pages', '-v', '--prefer-ffmpeg', '--merge-output-format', 'mkv', '-f', 'best', '--add-metadata', '--write-description', '-v', '--playlist-random', '--sleep-interval', '5', '--max-sleep-interval', '15', '--continue', '--cookies', 'youtube-dl-cookies.txt', '--cache-dir', './YTDLCache']
[debug] Command-line args: ['--config-location', 'youtube-dl.conf']
[debug] Batch file urls: ['https://www.pornhub.com/view_video.php?viewkey=ph57e1e4b49563f']
[debug] Encodings: locale cp1252, fs utf-8, out cp1252, pref cp1252
[debug] youtube-dl version 2018.04.16
[debug] Python version 3.6.4 (CPython) - Windows-10-10.0.16299-SP0
[debug] exe versions: none
[debug] Proxy map: {}
ERROR: Unable to extract encoded url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\users\xxxxxx\appdata\local\programs\python\python36-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 789, in extract_info
    ie_result = ie.extract(url)
  File "c:\users\xxxxxx\appdata\local\programs\python\python36-32\lib\site-packages\youtube_dl\extractor\common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "c:\users\xxxxxx\appdata\local\programs\python\python36-32\lib\site-packages\youtube_dl\extractor\pornhub.py", line 141, in _real_extract
    'encoded url').split(';')
  File "c:\users\xxxxxx\appdata\local\programs\python\python36-32\lib\site-packages\youtube_dl\extractor\common.py", line 808, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract encoded url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
[Page dump](https://github.com/rg3/youtube-dl/files/1940156/download2.log)

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.pornhub.com/view_video.php?viewkey=ph57e1e4b49563f
- Channel: https://www.pornhub.com/users/rosieandalena/videos/public
In truth, no channel or video seems to work.

---

### Description of your *issue*, suggested solution and other information

Attempting to download anything from PornHub will produce the error supplied above. It does not matter if it's a channel or a specific video.

I have tried changing out several values in the configuration file, but none seem to work.

I experienced this on the previous version, but thought it was an issue on PHs side. Waiting did not resolve the problem.

I see several other issues have similar wording, but none of the other issues have produced a solution for me.

Do let me know if you want me to try something specific.

**Comment by mjolnir870** [comment]
Also have the same issue. I'm using youtube-dl 2018.04.25 (latest as of today). Trying to download https://www.pornhub.com/users/alice_coquine/videos/public.

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: ['--no-mtime', '--no-playlist', '--playlist-reverse', '-i', '-w']
[debug] Command-line args: ['-v', '--config-location', 'C:\\Users\\USERNAME\\COMPUTERNAME\\Scripts\\youtube-dl-ondemand.conf', '--ffmpeg-location', 'C:\\Users\\USERNAME\\COMPUTERNAME\\Apps\\ffmpeg\\bin\\ffmpeg.exe', '--download-archive', 'M:\\pm\\Webcams\\Alice_coquine\\!pro\\!pornhub\\~youtube-dl_history.txt', '-f', 'bestvideo+bestaudio/best', '--write-thumbnail', '--external-downloader', 'C:\\Users\\USERNAME\\COMPUTERNAME\\Apps\\aria2\\64bit\\aria2c.exe', '--external-downloader-args', '--file-allocation=none -x 4 -k 1M', '-o', 'M:\\pm\\Webcams\\Alice_coquine\\!pro\\!pornhub\\%(title)s_%(id)s.%(ext)s', 'https://www.pornhub.com/users/alice_coquine/videos/public']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2018.04.25
[debug] Python version 3.4.4 (CPython) - Windows-8.1-6.3.9600
[debug] exe versions: ffmpeg N-89467-g0e5260226a, ffprobe N-89467-g0e5260226a
[debug] Proxy map: {}
[PornHubUserVideos] alice_coquine: Downloading page 1
[PornHubUserVideos] alice_coquine: Downloading page 2
[PornHubUserVideos] alice_coquine: Downloading page 3
[download] Downloading playlist: alice_coquine
[PornHubUserVideos] playlist alice_coquine: Collected 69 video ids (downloading 69 of them)
[download] Downloading video 1 of 69
[PornHub] ph5acdee363452e: Downloading webpage
[PornHub] ph5acdee363452e: Downloading webpage
ERROR: Unable to extract encoded url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpad1hmn8r\build\youtube_dl\YoutubeDL.py", line 789, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpad1hmn8r\build\youtube_dl\extractor\common.py", line 440, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpad1hmn8r\build\youtube_dl\extractor\pornhub.py", line 141, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpad1hmn8r\build\youtube_dl\extractor\common.py", line 808, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract encoded url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

[download] Downloading video 2 of 69
[PornHub] ph5ad9cc1eaa294: Downloading webpage
[PornHub] ph5ad9cc1eaa294: Downloading webpage
ERROR: Unable to extract encoded url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpad1hmn8r\build\youtube_dl\YoutubeDL.py", line 789, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpad1hmn8r\build\youtube_dl\extractor\common.py", line 440, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpad1hmn8r\build\youtube_dl\extractor\pornhub.py", line 141, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpad1hmn8r\build\youtube_dl\extractor\common.py", line 808, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract encoded url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

...

[download] Downloading video 69 of 69
[PornHub] ph5ae0aeefdb6bd: Downloading webpage
[PornHub] ph5ae0aeefdb6bd: Downloading webpage
ERROR: Unable to extract encoded url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpad1hmn8r\build\youtube_dl\YoutubeDL.py", line 789, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpad1hmn8r\build\youtube_dl\extractor\common.py", line 440, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpad1hmn8r\build\youtube_dl\extractor\pornhub.py", line 141, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpad1hmn8r\build\youtube_dl\extractor\common.py", line 808, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract encoded url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

[download] Finished downloading playlist: alice_coquine
```
[youtube-dl-ondemand_20180428_11450487.log](https://github.com/rg3/youtube-dl/files/1957933/youtube-dl-ondemand_20180428_11450487.log)

**Comment by krtjfghnazesdrryjsredthsedrhj** [comment]
Confirming it is still an issue on 2018.04.25
