### ISSUE TITLE
atresplayer.com: youtube-dl falling back on generic information extractor.

### ISSUE THREAD

**Issue by vitaminace33** [rg3/youtube-dl#16278]
### Make sure you are using the *latest* version.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.04.25**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Verbose output.

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.atresplayer.com/lasexta/noticias/noticias-1/abril-2018/cristina-cifuentes-dimite-y-denuncia-una-campana-de-acoso-la-tolerancia-cero-contra-la-corrupcion-tiene-un-precio_5ae07c5d7ed1a84af1936465/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.04.25
[debug] Python version 2.7.12 (CPython) - Linux-4.13.0-39-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.14-0ubuntu0.16.04.1, ffprobe 2.8.14-0ubuntu0.16.04.1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] cristina-cifuentes-dimite-y-denuncia-una-campana-de-acoso-la-tolerancia-cero-contra-la-corrupcion-tiene-un-precio_5ae07c5d7ed1a84af1936465: Requesting header
WARNING: Falling back on generic information extractor.
[generic] cristina-cifuentes-dimite-y-denuncia-una-campana-de-acoso-la-tolerancia-cero-contra-la-corrupcion-tiene-un-precio_5ae07c5d7ed1a84af1936465: Downloading webpage
[generic] cristina-cifuentes-dimite-y-denuncia-una-campana-de-acoso-la-tolerancia-cero-contra-la-corrupcion-tiene-un-precio_5ae07c5d7ed1a84af1936465: Extracting information
ERROR: Unsupported URL: https://www.atresplayer.com/lasexta/noticias/noticias-1/abril-2018/cristina-cifuentes-dimite-y-denuncia-una-campana-de-acoso-la-tolerancia-cero-contra-la-corrupcion-tiene-un-precio_5ae07c5d7ed1a84af1936465/
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/extractor/generic.py", line 2232, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "./youtube-dl/youtube_dl/compat.py", line 2542, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "./youtube-dl/youtube_dl/compat.py", line 2531, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 14, column 267
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 789, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/generic.py", line 3182, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.atresplayer.com/lasexta/noticias/noticias-1/abril-2018/cristina-cifuentes-dimite-y-denuncia-una-campana-de-acoso-la-tolerancia-cero-contra-la-corrupcion-tiene-un-precio_5ae07c5d7ed1a84af1936465/
```

---

### URLs for *site support request*.
- Single video: https://www.atresplayer.com/lasexta/noticias/noticias-1/abril-2018/cristina-cifuentes-dimite-y-denuncia-una-campana-de-acoso-la-tolerancia-cero-contra-la-corrupcion-tiene-un-precio_5ae07c5d7ed1a84af1936465/
- Playlist: https://www.atresplayer.com/lasexta/noticias/noticias-1/

Note that I have included the playlist since videos on this platform require login past some days of the publication (the exact number depends on the show channel). Therefore, the provided link will "expire" for the non-registered public in 1 week or so. Always choose the most recent video on the provided playlist to make sure it does not require login.

Note also that the website might require proper geo-localization (Spain).

---

### Description of the *issue* (no solution).

The AtresPlayer site has recently updated its webplayer platform, as a consequence youtube-dl does no longer recognize it and, instead of using the [AtresPlayer] module, it resorts to the [generic] one, which fails to retrieve the video. The user is left with no option but to use the webplayer.

I have doubly qualified the issue since the AtresPlayer platform was supported in the past (bug report), but it is in some sense a new platform (site support request).

**Comment by vitaminace33** [comment]
Duplicate of [#16277](https://github.com/rg3/youtube-dl/issues/16277). It seems we wrote on the same bug at the same time.
