### ISSUE TITLE
1up.com listed on supported sites but returns unsupported URL error

### ISSUE THREAD

**Issue by egerber95** [rg3/youtube-dl#16279]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.04.25*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ X] I've **verified** and **I assure** that I'm running youtube-dl **2018.04.25**

### Before submitting an *issue* make sure you have:
- [ X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

The site 1up.com is listed under the supported sites, but videos that are hosted on the site itself return an unsupported URL error.

Tried with this URL: http://www.1up.com/reviews/sly-4-review.html

```[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://www.1up.com/reviews/sly-4-review.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.04.25
[debug] Python version 3.5.1 (CPython) - Darwin-17.4.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[generic] sly-4-review: Requesting header
WARNING: Falling back on generic information extractor.
[generic] sly-4-review: Downloading webpage
[generic] sly-4-review: Extracting information
ERROR: Unsupported URL: http://www.1up.com/reviews/sly-4-review.html
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 789, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3166, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.1up.com/reviews/sly-4-review.html

**Comment by party98** [comment]
`1up.com` is incorrectly listed as supported as only the subdomain `gamevideos.1up.com` is supported.
