### ISSUE TITLE
UKTV "Main Page" Video Support

### ISSUE THREAD

**Issue by thecoreyburton** [rg3/youtube-dl#16294]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.04.25*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.04.25**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl https://uktvplay.uktv.co.uk/shows/alan-davies-xmas-untitled/watch-online/ -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://uktvplay.uktv.co.uk/shows/alan-davies-xmas-untitled/watch-online/', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.04.25
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.16299
[debug] exe versions: ffmpeg N-90656-ga26c9fdd1b, ffprobe N-90656-ga26c9fdd1b
[debug] Proxy map: {}
[generic] watch-online: Requesting header
WARNING: Falling back on generic information extractor.
[generic] watch-online: Downloading webpage
[generic] watch-online: Extracting information
ERROR: Unsupported URL: https://uktvplay.uktv.co.uk/shows/alan-davies-xmas-untitled/watch-online/
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpad1hmn8r\build\youtube_dl\YoutubeDL.py", line 789, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpad1hmn8r\build\youtube_dl\extractor\common.py", line 440, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpad1hmn8r\build\youtube_dl\extractor\generic.py", line 3182, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://uktvplay.uktv.co.uk/shows/alan-davies-xmas-untitled/watch-online/
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- https://uktvplay.uktv.co.uk/shows/alan-davies-xmas-untitled/watch-online/

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

I'd like to see support for single-episode UKTV shows. Currently youtube-dl has no problem downloading specific episode links (eg: https://uktvplay.uktv.co.uk/shows/alan-davies-as-yet-untitled/watch-online/?video=3973655453001), but for shows where only a single episode is present and only the "main page" URL is available (eg specials: https://uktvplay.uktv.co.uk/shows/alan-davies-xmas-untitled/watch-online/) youtube-dl cannot grab the episode (likely because no episode ID is specified). The video still plays correctly in web browsers when giventhe provided URL. If you would like any further information, please do not hesitate to ask,

**Comment by zang74** [comment]
Until this possibly gets added to the UKTV downloader plugin, there's a manual fix.

It would appear the video code for single videos is appended as "videoId=xxxxxxxxxxxxxxx" to the end of the poster image URL in the video-content <div> of the HTML. "Inspecting" the element within your browser, you can get that "empty" url and just add "?video=xxxxxxxxxxxxxxx" to the end.

**Comment by zang74** [comment]
Just wanted to add that I have officially confirmed that manually grabbing that code and adding it to the URL does download the correct video in youtube-dl.

**Comment by thecoreyburton** [comment]
I appreciate knowing there is a workaround for the time being, thank you for looking in to this for me @zang74

**Comment by thecoreyburton** [comment]
I greatly appreciate knowing there is a workaround until this is fixed. Thank you for looking in to this for me @zang74

**Comment by ChildishGiant** [comment]
The workaround seems to no longer be working:
```
youtube-dl https://uktvplay.uktv.co.uk/shows/secrets-of-the-london-underground/watch-online/?video=6261469555001 --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://uktvplay.uktv.co.uk/shows/secrets-of-the-london-underground/watch-online/?video=6261469555001', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.8.10 (CPython) - Linux-5.11.0-25-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[brightcove:new] 6261469555001: Downloading JSON metadata
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/brightcove.py", line 668, in _real_extract
    return self._parse_brightcove_metadata(
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/brightcove.py", line 549, in _parse_brightcove_metadata
    self._sort_formats(formats)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 1327, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

They seem to now be separate pages and not just one, as the video ids are no longer a query string but a new page.
