### ISSUE TITLE
URL extraction: tilde in URL?

### ISSUE THREAD

**Issue by hyiltiz** [rg3/youtube-dl#16337]
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.04.25**
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

```
/p/tmp $ youtube-dl -v 'http://www.cns.nyu.edu/~eero/math-tools/Videos/lecture-05sep2017.html'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'http://www.cns.nyu.edu/~eero/math-tools/Videos/lecture-05sep2017.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.04.25
[debug] Python version 2.7.10 (CPython) - Darwin-15.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.4.1, ffprobe 3.4.1
[debug] Proxy map: {}
[generic] lecture-05sep2017: Requesting header
WARNING: Falling back on generic information extractor.
[generic] lecture-05sep2017: Downloading webpage
[generic] lecture-05sep2017: Extracting information
ERROR: Unsupported URL: http://www.cns.nyu.edu/~eero/math-tools/Videos/lecture-05sep2017.html
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2232, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2542, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2531, in _XML
    parser.feed(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 12, column 136
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 789, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3182, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.cns.nyu.edu/~eero/math-tools/Videos/lecture-05sep2017.html

/p/tmp $ youtube-dl --version
2018.04.25
```

I think the website and the video is publicly available as I was able to play the video in Firefox Private without logging into anything from various networks. So I am looking suspiciously at tilde `~`, or that the extractor is somehow failing to reconstruct the API request to Kaltura. But using the URL for the `.m3u8` request works as suggested at #16211. Would be wonderful it this process could be automated, so we won't have to manually look through the requests and find the URL.

**Comment by hyiltiz** [comment]
Duplicate of #16211.
