### ISSUE TITLE
Error report on "https://www.culturall.com/ticket/ists/static/test_stream/1.mc"

### ISSUE THREAD

**Issue by hwk** [rg3/youtube-dl#1637]
Hi,
## I got the following error output, Win8 Pro 64Bit:

E:>youtube-dl --verbose https://www.culturall.com/ticket/ists/static/test_strea
m/1.mc
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'https://www.culturall.com/ticket/ists/
static/test_stream/1.mc']
[debug] youtube-dl version 2013.10.18.2
[debug] Python version 2.7.5 - Windows-8-6.2.9200
[debug] Proxy map: {}
WARNING: Falling back on generic information extractor.
[generic] 1.mc: Downloading webpage
[generic] 1.mc: Extracting information
ERROR: Unsupported URL: https://www.culturall.com/ticket/ists/static/test_stream
/1.mc; please report this issue on https://yt-dl.org/bug . Be sure to call youtu
be-dl with the --verbose flag and include its complete output. Make sure you are
 using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 353, in extract_info
  File "youtube_dl\extractor\common.pyo", line 117, in extract
  File "youtube_dl\extractor\generic.pyo", line 180, in _real_extract
ExtractorError: Unsupported URL: https://www.culturall.com/ticket/ists/static/te
st_stream/1.mc; please report this issue on https://yt-dl.org/bug . Be sure to c
all youtube-dl with the --verbose flag and include its complete output. Make sur
## e you are using the latest version; type  youtube-dl -U  to update.

Kind regards, Hans

**Comment by TRox1972** [comment]
URL doesn't seem to work anymore.

**Comment by yan12125** [comment]
Still working and is a Ooyala embed.

**Comment by TRox1972** [comment]
Didn't see that only part of the URL is highlighted. No wonder I got an error page ...
