### ISSUE TITLE
Cant download the video on the Youtube.

### ISSUE THREAD

**Issue by lionelliu2000** [rg3/youtube-dl#16380]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.05.01*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.05.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

C:\Users\Leo>youtube-dl https://youtu.be/pRxkRcJiyng -v
[debug] System config: []
[debug] User config: ['--write-auto-sub', '-o', 'F:\\Youtube-dl\\%(title)s%\\%(title)s.%(ext)s', '-f', 'bestvideo+bestaudio', '--proxy', 'socks5://127.0.0.1:1080', '--write-thumbnail']
[debug] Custom config: []
[debug] Command-line args: ['https://youtu.be/pRxkRcJiyng', '-v']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2018.05.01
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.16299
[debug] exe versions: ffmpeg N-90920-ge07b1913fc, ffprobe N-90920-ge07b1913fc
[debug] Proxy map: {'http': 'socks5://127.0.0.1:1080', 'https': 'socks5://127.0.0.1:1080'}
[youtube] pRxkRcJiyng: Downloading webpage
[youtube] pRxkRcJiyng: Downloading video info webpage
[youtube] pRxkRcJiyng: Extracting video information
[youtube] pRxkRcJiyng: Looking for automatic captions
WARNING: Couldn't find automatic captions for pRxkRcJiyng
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpulhs0gaq\build\youtube_dl\__init__.py", line 471, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpulhs0gaq\build\youtube_dl\__init__.py", line 461, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpulhs0gaq\build\youtube_dl\YoutubeDL.py", line 1993, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpulhs0gaq\build\youtube_dl\YoutubeDL.py", line 800, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpulhs0gaq\build\youtube_dl\YoutubeDL.py", line 854, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpulhs0gaq\build\youtube_dl\YoutubeDL.py", line 1627, in process_video_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpulhs0gaq\build\youtube_dl\YoutubeDL.py", line 1705, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpulhs0gaq\build\youtube_dl\YoutubeDL.py", line 703, in prepare_filename
TypeError: not enough arguments for format string

---

I don't know why that suddenly I can't download the video, I have tried to change a URL, but it's useless.
Can anyone help me please?

**Comment by dstftw** [comment]
Invalid argument passed to `-o`.

**Comment by lionelliu2000** [comment]
I try to change the conf file, but it is useless
