### ISSUE TITLE
openclassrooms.com

### ISSUE THREAD

**Issue by Rudloff** [rg3/youtube-dl#1638]
```
pierre@Rudloff:~$ youtube-dl http://claireplayer.openclassrooms.com/players/11_.html -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://claireplayer.openclassrooms.com/players/11_.html', '-v']
[debug] youtube-dl version 2013.10.18.2
[debug] Python version 2.7.3 - Linux-3.2.0-4-amd64-x86_64-with-debian-7.2
[debug] Proxy map: {}
WARNING: Falling back on generic information extractor.
[generic] 11_.html: Downloading webpage
[generic] 11_.html: Extracting information
ERROR: Unsupported URL: http://claireplayer.openclassrooms.com/players/11_.html; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 353, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 117, in extract
    return self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/generic.py", line 180, in _real_extract
    raise ExtractorError(u'Unsupported URL: %s' % url)
ExtractorError: Unsupported URL: http://claireplayer.openclassrooms.com/players/11_.html; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
```

**Comment by TRox1972** [comment]
The provided URL does not seem to work anymore.

**Comment by TRox1972** [comment]
Updated URL: https://openclassrooms.com/courses/understanding-the-web

The site seems to be using Vimeo embeds, at least for their free videos, but the embeds are currently not detected. Improving Vimeo embed detection should close this issue.

**Comment by yan12125** [comment]
Thanks @TRox1972 such vimeo embedded videos will be recognized in the next versin.
