### ISSUE TITLE
Download music stream from Amazon

### ISSUE THREAD

**Issue by Rudloff** [rg3/youtube-dl#1641]
It would be nice to be able to download the music here:

```
pierre@Rudloff:~$ youtube-dl "http://www.amazon.com/gp/feature.html?ie=UTF8&docId=1001428681#" -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://www.amazon.com/gp/feature.html?ie=UTF8&docId=1001428681#', '-v']
[debug] youtube-dl version 2013.10.18.2
[debug] Python version 2.7.3 - Linux-3.2.0-4-amd64-x86_64-with-debian-7.2
[debug] Proxy map: {}
[redirect] Following redirect to http://www.amazon.com/gp/feature.html?ie=UTF8&docId=1001428681
WARNING: Falling back on generic information extractor.
[generic] feature.html?ie=UTF8&docId=1001428681: Downloading webpage
[generic] feature.html?ie=UTF8&docId=1001428681: Extracting information
ERROR: Unsupported URL: http://www.amazon.com/gp/feature.html?ie=UTF8&docId=1001428681; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 353, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 117, in extract
    return self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/generic.py", line 180, in _real_extract
    raise ExtractorError(u'Unsupported URL: %s' % url)
ExtractorError: Unsupported URL: http://www.amazon.com/gp/feature.html?ie=UTF8&docId=1001428681; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
```

**Comment by Rudloff** [comment]
The music is now here: https://www.amazon.com/Lindsey-Stirling/dp/B00FMJJ064/ref=tmm_msc_swatch_0?_encoding=UTF8&qid=&sr=

But it still does not work:
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.amazon.com/Lindsey-Stirling/dp/B00FMJJ064/ref=tmm_msc_swatch_0?_encoding=UTF8&qid=&sr=', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.03.22
[debug] Python version 2.7.9 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.7
[debug] exe versions: avconv 11.8-6, avprobe 11.8-6, rtmpdump 2.4
[debug] Proxy map: {}
[generic] ref=tmm_msc_swatch_0?_encoding=UTF8&qid=&sr=: Requesting header
WARNING: Could not send HEAD request to https://www.amazon.com/Lindsey-Stirling/dp/B00FMJJ064/ref=tmm_msc_swatch_0?_encoding=UTF8&qid=&sr=: HTTP Error 405: MethodNotAllowed
[generic] ref=tmm_msc_swatch_0?_encoding=UTF8&qid=&sr=: Downloading webpage
WARNING: Falling back on generic information extractor.
[generic] ref=tmm_msc_swatch_0?_encoding=UTF8&qid=&sr=: Extracting information
ERROR: Unsupported URL: https://www.amazon.com/Lindsey-Stirling/dp/B00FMJJ064/ref=tmm_msc_swatch_0?_encoding=UTF8&qid=&sr=
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 1790, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/compat.py", line 2526, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/compat.py", line 2515, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: mismatched tag: line 26, column 2
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 761, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 428, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 2653, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.amazon.com/Lindsey-Stirling/dp/B00FMJJ064/ref=tmm_msc_swatch_0?_encoding=UTF8&qid=&sr=
```
