### ISSUE TITLE
Twitch clips fail to download - Unable to extract clip info

### ISSUE THREAD

**Issue by KyleReese** [rg3/youtube-dl#16429]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.05.09*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.05.09**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://clips.twitch.tv/MushyEnchantingCrabsKeyboardCat']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.05.09
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.16299
[debug] exe versions: ffmpeg 3.4.1, ffprobe 3.4.1, rtmpdump 2.3
[debug] Proxy map: {}
[twitch:clips] MushyEnchantingCrabsKeyboardCat: Downloading webpage
ERROR: Unable to extract clip info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplwokk3j3\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplwokk3j3\build\youtube_dl\extractor\common.py", line 503, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplwokk3j3\build\youtube_dl\extractor\twitch.py", line 654, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplwokk3j3\build\youtube_dl\extractor\common.py", line 883, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract clip info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
...
<end of log>
```

### Description of your *issue*, suggested solution and other information

Twitch clips fail to download, it seems like youtube-dl cannot find the video stream. I am not a web developer but right clicking the video in chrome gives options about a separate frame, maybe that is part of the issue?

 An example of a clip that does not download is here: https://clips.twitch.tv/MushyEnchantingCrabsKeyboardCat

**Comment by edwinjue** [comment]
Why is this issue closed? I am experiencing the same thing on linux:

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-cik', u'-f', u'mp4', u'--restrict-filenames', u'-o', u'%(title)s-%(id)s.%(ext)s', u'-v', u'https://clips.twitch.tv/SullenGentleCheddarDatSheffy']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.05.09
[debug] Python version 2.7.12 (CPython) - Linux-4.4.0-124-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 3.0.2-4, ffprobe 3.0.2-4, rtmpdump 2.4
[debug] Proxy map: {}
[twitch:clips] SullenGentleCheddarDatSheffy: Downloading webpage
ERROR: Unable to extract clip info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 503, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/twitch.py", line 654, in _real_extract
    r'(?s)clipInfo\s*=\s*({.+?});', webpage, 'clip info'),
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 883, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract clip info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by Hrxn** [comment]
Closed with commit https://github.com/rg3/youtube-dl/commit/49fa7de301019e23e66c01e5007561eefd51ca47, because this is the fix.

Not included in current release version, so either wait for next release version or run git master.

**Comment by h633537** [comment]
I'm getting 360p with best quality now.

```
youtube-dl https://clips.twitch.tv/MushyEnchantingCrabsKeyboardCat -F
[twitch:clips] MushyEnchantingCrabsKeyboardCat: Downloading JSON metadata
[twitch:clips] MushyEnchantingCrabsKeyboardCat: Downloading JSON metadata
[info] Available formats for 235534736:
format code  extension  resolution note
1080         mp4        1080p      60fps
720          mp4        720p       60fps
480          mp4        480p       30fps
360          mp4        360p       30fps (best)
```
