### ISSUE TITLE
Problem with spaced password on vimeo account

### ISSUE THREAD

**Issue by wyup** [rg3/youtube-dl#16423]
When trying:
youtube-dl --video-password SPACED PASSWORD https://vimeo.com/123456789
throws:
ERROR: 'PASSWORD' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:PASSWORD" ) to search YouTube

if I try --video-password "SPACED PASSWORD" or --video-password 'SPACED PASSWORD' or --video-password="SPACED PASSWORD" doesn't work either.

When I view the video on the browser with the supplied password it works.

**Comment by wyup** [comment]
youtube-dl --verbose --video-password SPACED PASSWORD https://vimeopro.com/banatufilmak/cineclub-fas-1/video/182850420

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--video-password', 'PRIVATE', 'PASSWORD', 'https://vimeopro.com/banatufilmak/cineclub-fas-1/video/182850420']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.05.09
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg N-90848-g8ea8be5951, ffprobe N-90848-g8ea8be5951
[debug] Proxy map: {}
ERROR: 'PASSWORD' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:PASSWORD" ) to search YouTube
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplwokk3j3\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplwokk3j3\build\youtube_dl\extractor\common.py", line 503, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplwokk3j3\build\youtube_dl\extractor\generic.py", line 2151, in _real_extract
youtube_dl.utils.ExtractorError: 'PASSWORD' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:PASSWORD" ) to search YouTube
