### ISSUE TITLE
[BUG] [YOUTUBE] Unable to extract uploader name

### ISSUE THREAD

**Issue by anaggh** [rg3/youtube-dl#16444]
```bash
$ youtube-dl --version
2018.05.09
```

```bash
$ youtube-dl "https://www.youtube.com/watch?v=be89BcNR6vA&list=PL8TWxe78E9Wvic0-RjHRzwEcaQXuaGJQn" --extract-audio --audio-format mp3 --playlist-start 63 --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.youtube.com/watch?v=be89BcNR6vA&list=PL8TWxe78E9Wvic0-RjHRzwEcaQXuaGJQn', u'--extract-audio', u'--audio-format', u'mp3', u'--playlist-start', u'63', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.05.09
[debug] Python version 2.7.15rc1 (CPython) - Linux-4.15.0-20-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.2-2, ffprobe 3.4.2-2, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:playlist] Downloading playlist PL8TWxe78E9Wvic0-RjHRzwEcaQXuaGJQn - add --no-playlist to just download video be89BcNR6vA
[youtube:playlist] PL8TWxe78E9Wvic0-RjHRzwEcaQXuaGJQn: Downloading webpage
[download] Downloading playlist: 17tumba playlist [Uploads 600-800] LATEST!
[youtube:playlist] PL8TWxe78E9Wvic0-RjHRzwEcaQXuaGJQn: Downloading page #1
[youtube:playlist] playlist 17tumba playlist [Uploads 600-800] LATEST!: Downloading 104 videos
[download] Downloading video 1 of 104
[youtube] cwXR4LCbK3Q: Downloading webpage
[youtube] cwXR4LCbK3Q: Downloading video info webpage
WARNING: Unable to extract video title
[youtube] cwXR4LCbK3Q: Extracting video information
ERROR: Unable to extract uploader name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 503, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1701, in _real_extract
    raise ExtractorError('Unable to extract uploader name')
ExtractorError: Unable to extract uploader name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by anaggh** [comment]
Seems like it fails here https://www.youtube.com/watch?v=cwXR4LCbK3Q

**Comment by dstftw** [comment]
Both videos are not available.

**Comment by anaggh** [comment]
Just checked the playlist. The videos are either Private or Deleted. Is there any argument to skip these?

**Comment by dstftw** [comment]
`-i`.
