### ISSUE TITLE
PBS.org links no longer working within the last day: "No video formats found"

### ISSUE THREAD

**Issue by umccullough** [rg3/youtube-dl#16474]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.05.09*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.05.09**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
C:\Temp\youtube-dl>youtube-dl.exe --verbose http://www.pbs.org/video/frontline-choice-2012-again/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'http://www.pbs.org/video/frontline-choice-2012-again/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.05.09
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.15063
[debug] exe versions: ffmpeg N-86935-g44e9783, ffprobe N-86935-g44e9783
[debug] Proxy map: {}
[debug] Using fake IP 3.12.244.172 (US) as X-Forwarded-For.
[pbs] Downloading JSON metadata
[pbs] frontline-choice-2012-again: Downloading webpage
[pbs] frontline-choice-2012-again: Downloading widget/partnerplayer page
[pbs] frontline-choice-2012-again: Downloading portalplayer page
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplwokk3j3\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplwokk3j3\build\youtube_dl\extractor\common.py", line 503, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplwokk3j3\build\youtube_dl\extractor\pbs.py", line 590, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplwokk3j3\build\youtube_dl\extractor\common.py", line 1193, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
...
<end of log>
```

---

### Description of your *issue*, suggested solution and other information

It seems within the last day, pbs.org links no longer work in youtube-dl - I know i successfully grabbed a Frontline episode yesterday in fact, so they must have changed something? I tried several other links and none of them seem to work now - including the one i used successfully yesterday.

Another example (worked 2018-05-15):
http://www.pbs.org/video/myanmars-killing-fields-wwdvdm/

**Comment by bigcitypix** [comment]
Still doesn't work: 
https://www.pbs.org/video/bombshell-the-hedy-lamarr-story-xxkyoj/
https://www.pbs.org/video/the-worlds-most-wanted-animal-evunge/

**Comment by remitamine** [comment]
@bigcitypix no it does work:
```
youtube-dl https://www.pbs.org/video/bombshell-the-hedy-lamarr-story-xxkyoj/
[pbs] Downloading JSON metadata
[pbs] bombshell-the-hedy-lamarr-story-xxkyoj: Downloading webpage
[pbs] bombshell-the-hedy-lamarr-story-xxkyoj: Downloading widget/partnerplayer page
[pbs] bombshell-the-hedy-lamarr-story-xxkyoj: Downloading portalplayer page
[pbs] bombshell-the-hedy-lamarr-story-xxkyoj: Downloading hls-16x9-1080p video url info
[pbs] bombshell-the-hedy-lamarr-story-xxkyoj: Downloading m3u8 information
[pbs] bombshell-the-hedy-lamarr-story-xxkyoj: Downloading mp4-16x9-720p video url info
[pbs] bombshell-the-hedy-lamarr-story-xxkyoj: Downloading hls-16x9-720p video url info
[pbs] bombshell-the-hedy-lamarr-story-xxkyoj: Downloading m3u8 information
[pbs] bombshell-the-hedy-lamarr-story-xxkyoj: Checking http-2000k video URL
[pbs] bombshell-the-hedy-lamarr-story-xxkyoj: http-2000k video URL is invalid, skipping
[pbs] bombshell-the-hedy-lamarr-story-xxkyoj: Checking http-6500k video URL
[pbs] bombshell-the-hedy-lamarr-story-xxkyoj: http-6500k video URL is invalid, skipping
[pbs] bombshell-the-hedy-lamarr-story-xxkyoj: Checking http-4500k video URL
[pbs] bombshell-the-hedy-lamarr-story-xxkyoj: http-4500k video URL is invalid, skipping
[pbs] bombshell-the-hedy-lamarr-story-xxkyoj: Checking http-3000k video URL
[pbs] bombshell-the-hedy-lamarr-story-xxkyoj: Checking http-1100k video URL
[pbs] bombshell-the-hedy-lamarr-story-xxkyoj: http-1100k video URL is invalid, skipping
[pbs] bombshell-the-hedy-lamarr-story-xxkyoj: Checking http-730k video URL
[pbs] bombshell-the-hedy-lamarr-story-xxkyoj: http-730k video URL is invalid, skipping
[pbs] bombshell-the-hedy-lamarr-story-xxkyoj: Checking http-730k video URL
[pbs] bombshell-the-hedy-lamarr-story-xxkyoj: http-730k video URL is invalid, skipping
[pbs] bombshell-the-hedy-lamarr-story-xxkyoj: Checking http-3000k video URL
[pbs] bombshell-the-hedy-lamarr-story-xxkyoj: Checking http-2000k video URL
[pbs] bombshell-the-hedy-lamarr-story-xxkyoj: http-2000k video URL is invalid, skipping
[pbs] bombshell-the-hedy-lamarr-story-xxkyoj: Checking http-1100k video URL
[pbs] bombshell-the-hedy-lamarr-story-xxkyoj: http-1100k video URL is invalid, skipping
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 834
[download] Destination: American Masters - Bombshell - The Hedy Lamarr Story-3012683352.mp4
[download]   0.0% of ~2.84GiB at 476.12KiB/s ETA 02:56:00
```
```
youtube-dl https://www.pbs.org/video/the-worlds-most-wanted-animal-evunge/
[pbs] Downloading JSON metadata
[pbs] the-worlds-most-wanted-animal-evunge: Downloading webpage
[pbs] the-worlds-most-wanted-animal-evunge: Downloading widget/partnerplayer page
[pbs] the-worlds-most-wanted-animal-evunge: Downloading portalplayer page
[pbs] the-worlds-most-wanted-animal-evunge: Downloading hls-16x9-1080p video url info
[pbs] the-worlds-most-wanted-animal-evunge: Downloading m3u8 information
[pbs] the-worlds-most-wanted-animal-evunge: Downloading mp4-16x9-720p video url info
[pbs] the-worlds-most-wanted-animal-evunge: Downloading hls-16x9-720p video url info
[pbs] the-worlds-most-wanted-animal-evunge: Downloading m3u8 information
[pbs] the-worlds-most-wanted-animal-evunge: Checking http-2000k video URL
[pbs] the-worlds-most-wanted-animal-evunge: http-2000k video URL is invalid, skipping
[pbs] the-worlds-most-wanted-animal-evunge: Checking http-6500k video URL
[pbs] the-worlds-most-wanted-animal-evunge: http-6500k video URL is invalid, skipping
[pbs] the-worlds-most-wanted-animal-evunge: Checking http-4500k video URL
[pbs] the-worlds-most-wanted-animal-evunge: http-4500k video URL is invalid, skipping
[pbs] the-worlds-most-wanted-animal-evunge: Checking http-3000k video URL
[pbs] the-worlds-most-wanted-animal-evunge: Checking http-1100k video URL
[pbs] the-worlds-most-wanted-animal-evunge: http-1100k video URL is invalid, skipping
[pbs] the-worlds-most-wanted-animal-evunge: Checking http-730k video URL
[pbs] the-worlds-most-wanted-animal-evunge: http-730k video URL is invalid, skipping
[pbs] the-worlds-most-wanted-animal-evunge: Checking http-730k video URL
[pbs] the-worlds-most-wanted-animal-evunge: http-730k video URL is invalid, skipping
[pbs] the-worlds-most-wanted-animal-evunge: Checking http-3000k video URL
[pbs] the-worlds-most-wanted-animal-evunge: Checking http-2000k video URL
[pbs] the-worlds-most-wanted-animal-evunge: http-2000k video URL is invalid, skipping
[pbs] the-worlds-most-wanted-animal-evunge: Checking http-1100k video URL
[pbs] the-worlds-most-wanted-animal-evunge: http-1100k video URL is invalid, skipping
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 530
[download] Destination: Nature - The World's Most Wanted Animal-3012748880.mp4
[download]   0.0% of ~1.90GiB at 387.15KiB/s ETA 03:29:38
```
