### ISSUE TITLE
Downloading wrong or no video (teamcoco)

### ISSUE THREAD

**Issue by jmraker** [rg3/youtube-dl#16484]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.05.18*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2018.05.18**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
$ youtube-dl.exe -v "http://teamcoco.com/italy/jordan-schlansky-lectures-conan-about-coffee-in-naples?playlist=x;eyJ0eXBlIjoidGFnIiwiaWQiOjF9"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://teamcoco.com/italy/jordan-schlansky-lectures-conan-about-coffee-in-naples?playlist=x;eyJ0eXBlIjoidGFnIiwiaWQiOjF9']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2018.05.18
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: avconv v11.7, avprobe v11.7, ffmpeg 3.2.2, ffprobe 3.2.2, rtmpdump 2.3
[debug] Proxy map: {}
[generic] jordan-schlansky-lectures-conan-about-coffee-in-naples?playlist=x;eyJ0eXBlIjoidGFnIiwiaWQiOjF9: Requesting header
WARNING: Falling back on generic information extractor.
[generic] jordan-schlansky-lectures-conan-about-coffee-in-naples?playlist=x;eyJ0eXBlIjoidGFnIiwiaWQiOjF9: Downloading webpage
[generic] jordan-schlansky-lectures-conan-about-coffee-in-naples?playlist=x;eyJ0eXBlIjoidGFnIiwiaWQiOjF9: Extracting information
[download] Downloading playlist: Jordan Schlansky Lectures Conan About Coffee In Naples
[generic] playlist Jordan Schlansky Lectures Conan About Coffee In Naples: Collected 2 video ids (downloading 2 of them)
[download] Downloading video 1 of 2
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://ak.static.teamcoco.com/evergreen/eggs/durst/Durst.mp3'
[download] Jordan Schlansky Lectures Conan About Coffee In Naples (1)-jordan-schlansky-lectures-conan-about-coffee-in-naplesplaylist=x;eyJ0eXBlIjoidGFnIiwiaWQiOjF9-1.mp3 has already been downloaded
[download] 100% of 12.62KiB
[download] Downloading video 2 of 2
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://static.teamcococdn.com/www/promos/uk-promo.mp4'
[download] Jordan Schlansky Lectures Conan About Coffee In Naples (2)-jordan-schlansky-lectures-conan-about-coffee-in-naplesplaylist=x;eyJ0eXBlIjoidGFnIiwiaWQiOjF9-2.mp4 has already been downloaded
[download] 100% of 3.20MiB
[download] Finished downloading playlist: Jordan Schlansky Lectures Conan About Coffee In Naples
```

---

### Description of your *issue*, suggested solution and other information

The youtube-dl support for teamcoco site was updated last week and it works except for the "jordan schlansky" videos.

These download a mp3 and the United Kingdom trailer
http://teamcoco.com/italy/conan-jordan-schlansky-hit-the-streets-of-florence
http://teamcoco.com/italy/jordan-schlansky-poses-as-a-nude-model
http://teamcoco.com/italy/conan-jordan-schlansky-go-truffle-hunting
http://teamcoco.com/italy/conan-jordan-schlansky-s-italian-wine-tasting
http://teamcoco.com/italy/jordan-schlansky-lectures-conan-about-coffee-in-naples

These fail to download anything with the error: ERROR: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
http://teamcoco.com/italy/conan-jordan-schlansky-s-italian-road-trip
http://teamcoco.com/italy/conan-visits-jordan-s-favorite-restaurant
http://teamcoco.com/italy/conan-jordan-s-fake-italian-movie-trailer

```
$ youtube-dl.exe -v "http://teamcoco.com/italy/conan-jordan-s-fake-italian-movie-trailer"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://teamcoco.com/italy/conan-jordan-s-fake-italian-movie-trailer']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2018.05.18
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: avconv v11.7, avprobe v11.7, ffmpeg 3.2.2, ffprobe 3.2.2, rtmpdump 2.3
[debug] Proxy map: {}
[generic] conan-jordan-s-fake-italian-movie-trailer: Requesting header
WARNING: Falling back on generic information extractor.
[generic] conan-jordan-s-fake-italian-movie-trailer: Downloading webpage
[generic] conan-jordan-s-fake-italian-movie-trailer: Extracting information
[Instagram] BfXB57dlgqf: Downloading webpage
ERROR: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpco7jv88i\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpco7jv88i\build\youtube_dl\extractor\common.py", line 503, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpco7jv88i\build\youtube_dl\extractor\instagram.py", line 191, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpco7jv88i\build\youtube_dl\extractor\common.py", line 1001, in _og_search_video_url
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpco7jv88i\build\youtube_dl\extractor\common.py", line 892, in _html_search_regex
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpco7jv88i\build\youtube_dl\extractor\common.py", line 883, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by jmraker** [comment]
This also fails to download, possibly due to the date at the end 04/25/18 looking like subdirectories, but it works on the website.
```
$ youtube-dl.exe -v http://teamcoco.com/video/the-conan-audiencey-awards-for-04/25/18
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://teamcoco.com/video/the-conan-audiencey-awards-for-04/25/18']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2018.05.18
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: avconv v11.7, avprobe v11.7, ffmpeg 3.2.2, ffprobe 3.2.2, rtmpdump 2.3
[debug] Proxy map: {}
[Teamcoco] the-conan-audiencey-awards-for-04: Downloading JSON metadata
ERROR: This video is no longer available.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpco7jv88i\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpco7jv88i\build\youtube_dl\extractor\common.py", line 503, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpco7jv88i\build\youtube_dl\extractor\teamcoco.py", line 106, in _real_extract
youtube_dl.utils.ExtractorError: This video is no longer available.
```

**Comment by osm0sis** [comment]
This appears to be a problem again now that everything's switched over to classic.teamcoco.com, for example https://classic.teamcoco.com/node/106270 / https://classic.teamcoco.com/late-night-with-conan-obrien/season-6/episode-82/conan-in-ireland-03-17-99 has the following output:

```
C:\Users\Chris\Desktop>youtube-dl -v "https://classic.teamcoco.com/late-night-with-conan-obrien/season-6/episode-82/conan-in-ireland-03-17-99"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://classic.teamcoco.com/late-night-with-conan-obrien/season-6/episode-82/conan-in-ireland-03-17-99']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[Teamcoco] late-night-with-conan-obrien/season-6/episode-82/conan-in-ireland-03-17-99: Downloading JSON metadata
ERROR: This video is no longer available.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\teamcoco.py", line 131, in _real_extract
youtube_dl.utils.ExtractorError: This video is no longer available.
```
