### ISSUE TITLE
Joining vid+aud fails for Sat1 download

### ISSUE THREAD

**Issue by ghoffart** [rg3/youtube-dl#16496]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.05.18*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.05.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```

$ youtube-dl  -v "https://www.sat1.de/tv/der-letzte-bulle/video/112-staffel-1-episode-12-bei-kuscheln-mord-ganze-folge2"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.sat1.de/tv/der-letzte-bulle/video/112-staffel-1-episode-12-bei-kuscheln-mord-ganze-folge2']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.05.18
[debug] Python version 2.7.15 (CPython) - Darwin-17.5.0-x86_64-i386-64bit
[debug] exe versions: avconv 12.3, avprobe 12.3, ffmpeg 4.0, ffprobe 4.0, rtmpdump 2.4
[debug] Proxy map: {}
[prosiebensat1] tv/der-letzte-bulle/video/112-staffel-1-episode-12-bei-kuscheln-mord-ganze-folge2: Downloading webpage
[prosiebensat1] 1414464: Downloading videos JSON
[prosiebensat1] 1414464: Downloading sources JSON
[prosiebensat1] 1414464: Downloading urls JSON
[prosiebensat1] 1414464: Downloading f4m manifest
[prosiebensat1] 1414464: Downloading urls JSON
[prosiebensat1] 1414464: Downloading m3u8 information
[prosiebensat1] 1414464: Downloading urls JSON
[prosiebensat1] 1414464: Downloading MPD manifest
[prosiebensat1] 1414464: Downloading urls JSON
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'http://ac-vod-0002-mds.p7s1video.net/01/v/t-ru/2.0/dash/01/VsdaEg9TiFgugB8CqTQZQub0Mse7vMhNg38j230TGD-rLZlmZKOa6dpCqaOyhmug30Kogv4earsk-WPAhkiAscJv_yxrsdw5Upiqm2nIQ3cOa-A0aC9u_px431bzPhDDgHz6-agBeuEYqzPg8YKejw/v.ism/dash/'
[dashsegments] Total fragments: 1329
[download] Destination: Der letzte Bulle - Staffel 1 Episode 12 - Bei Kuscheln Mord-1414464.fdash-video=3500000.mp4
[download] 100% of 1.00GiB in 10:59
[debug] Invoking downloader on u'http://ac-vod-0002-mds.p7s1video.net/01/v/t-ru/2.0/dash/01/VsdaEg9TiFgugB8CqTQZQub0Mse7vMhNg38j230TGD-rLZlmZKOa6dpCqaOyhmug30Kogv4earsk-WPAhkiAscJv_yxrsdw5Upiqm2nIQ3cOa-A0aC9u_px431bzPhDDgHz6-agBeuEYqzPg8YKejw/v.ism/dash/'
[dashsegments] Total fragments: 1329
[download] Destination: Der letzte Bulle - Staffel 1 Episode 12 - Bei Kuscheln Mord-1414464.fdash-audio=128000.m4a
[download] 100% of 41.25MiB in 02:24
[ffmpeg] Merging formats into "Der letzte Bulle - Staffel 1 Episode 12 - Bei Kuscheln Mord-1414464.mp4"
[debug] ffmpeg command line: avconv -y -i 'file:Der letzte Bulle - Staffel 1 Episode 12 - Bei Kuscheln Mord-1414464.fdash-video=3500000.mp4' -i 'file:Der letzte Bulle - Staffel 1 Episode 12 - Bei Kuscheln Mord-1414464.fdash-audio=128000.m4a' -c copy -map '0:v:0' -map '1:a:0' 'file:Der letzte Bulle - Staffel 1 Episode 12 - Bei Kuscheln Mord-1414464.temp.mp4'
ERROR: av_interleaved_write_frame(): Invalid argument
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2047, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 479, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 204, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
FFmpegPostProcessorError: av_interleaved_write_frame(): Invalid argument

youtube-dl -v   27,67s user 25,86s system 6% cpu 13:30,41 total
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Joining video+audio fails because of wrong arguments. The downloaded video itself plays fine, just audio is missing. When watching the video on the webpage with a browser, it’s all fine.

**Comment by ghoffart** [comment]
```
$ ffmpeg -version                                                  ❌ 1 ↵
ffmpeg version 4.0 Copyright (c) 2000-2018 the FFmpeg developers
built with Apple LLVM version 9.1.0 (clang-902.0.39.1)
configuration: --prefix=/usr/local/Cellar/ffmpeg/4.0 --enable-shared --enable-pthreads --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-gpl --enable-libmp3lame --enable-libx264 --enable-libxvid --enable-opencl --enable-videotoolbox --disable-lzma
libavutil      56. 14.100 / 56. 14.100
libavcodec     58. 18.100 / 58. 18.100
libavformat    58. 12.100 / 58. 12.100
libavdevice    58.  3.100 / 58.  3.100
libavfilter     7. 16.100 /  7. 16.100
libavresample   4.  0.  0 /  4.  0.  0
libswscale      5.  1.100 /  5.  1.100
libswresample   3.  1.100 /  3.  1.100
libpostproc    55.  1.100 / 55.  1.100
```
