### ISSUE TITLE
vlive extractor recognition error

### ISSUE THREAD

**Issue by socialily** [rg3/youtube-dl#16523]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.05.18*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x ] I've **verified** and **I assure** that I'm running youtube-dl **2018.05.18**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [  ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ x ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```

C:\Users\nichi_000\Desktop\youtube_dl>youtube-dl.exe --config-location C:\Users\nichi_000\AppData\Roaming\youtube-dl\vlive.txt --cookies C:\Users\nichi_000\Desktop\youtube_dl\Cookies\vlive_cookies.txt -v https://www.vlive.tv/video/vplus/9427
[debug] System config: []
[debug] User config: []
[debug] Custom config: ['--prefer-ffmpeg', '--no-mark-watched', '-f', 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best', '--merge-output-format', 'mp4', '--ffmpeg-location', 'C:\\video\\ffmpeg.exe', '-o', 'C:\\Vlive\\%(uploader)s - %(title)s.%(ext)s', '--no-check-certificate', '--abort-on-unavailable-fragment', '--write-sub', '--sub-lang', 'en', '--write-auto-sub', '--convert-subs', 'srt', '--write-thumbnail', '--add-metadata']
[debug] Command-line args: ['--config-location', 'C:\\Users\\nichi_000\\AppData\\Roaming\\youtube-dl\\vlive.txt', '--cookies', 'C:\\Users\\nichi_000\\Desktop\\youtube_dl\\Cookies\\vlive_cookies.txt', '-v', 'https://www.vlive.tv/video/vplus/9427']
[debug] Encodings: locale cp1250, fs mbcs, out cp852, pref cp1250
[debug] youtube-dl version 2018.05.18
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.16299
[debug] exe versions: ffmpeg N-65426-gd6af706, ffprobe N-65426-gd6af706
[debug] Proxy map: {}
[generic] 9427: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 9427: Downloading webpage
[generic] 9427: Extracting information
ERROR: Unsupported URL: https://www.vlive.tv/video/vplus/9427
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpco7jv88i\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpco7jv88i\build\youtube_dl\extractor\common.py", line 503, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpco7jv88i\build\youtube_dl\extractor\generic.py", line 3201, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.vlive.tv/video/vplus/9427
---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

**Comment by socialily** [comment]
i'm assuming adding https://www.vlive.tv/video/vplus/ to the urls that uses the normal vlive extractor (and not the generic one should work since it's essentially the same site

**Comment by kajeagentspi** [comment]
@dstftw do you need an account with channel+? I have one that you can borrow
