### ISSUE TITLE
TF1 not working

### ISSUE THREAD

**Issue by Nazo22** [rg3/youtube-dl#16533]
Dear team,

I'm trying to get the multimedia link for below stream using youtube-dl but it is not working. Please find below the details.

Can you please support to fix it ?

Thanks.

**Link**: https://tf1.fr/tf1/direct

**Verbose**:

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-g', u'https://tf1.fr/tf1/direct', u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.05.18
[debug] Python version 2.7.12 (CPython) - Linux-4.4.0-124-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg N-75193-gf855353-Xtream-Codes, ffprobe N-75193-gf855353-Xtream-Codes
[debug] Proxy map: {}
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 472, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 462, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2001, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 803, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 864, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 803, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 864, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 503, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/wat.py", line 64, in _real_extract
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by Urgau** [comment]
DISCLAIMER : I am not a official contributor

https://tf1.fr/tf1/direct is the live for tf1 however youtube-dl don't support livestream but only video if you want to watch the live use [streamlink](https://streamlink.github.io/) instead.
