### ISSUE TITLE
ITV no longer works since a few days and exits with "ERROR: Unable to extract params;"

### ISSUE THREAD

**Issue by k3ck3c** [rg3/youtube-dl#16541]
### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: [] Ubuntu 

$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=17.04
DISTRIB_CODENAME=zesty
DISTRIB_DESCRIPTION="Ubuntu 17.04"

[debug] User config: 

$ youtube-dl --version
2018.05.18

I try to download from itv.com 
the following video

https://www.itv.com/hub/midsomer-murders/Ya1096

using this command (and a proxy)

youtube-dl -v -4 https://www.itv.com/hub/midsomer-murders/Ya1096 --all-subs --convert-subs srt --proxy 'http://46.101.11.131:3128'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-4', u'https://www.itv.com/hub/midsomer-murders/Ya1096', u'--all-subs', u'--convert-subs', u'srt', u'--proxy', u'http://46.101.11.131:3128']
[debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8
[debug] youtube-dl version 2018.05.18
[debug] Python version 2.7.13 (CPython) - Linux-4.10.0-42-generic-x86_64-with-Ubuntu-17.04-zesty
[debug] exe versions: avconv 3.2.4-1build2, avprobe 3.2.4-1build2, ffmpeg 3.2.4-1build2, ffprobe 3.2.4-1build2, rtmpdump 2.4-n111-gitfa8646d-ppa9p2
[debug] Proxy map: {u'http': u'http://46.101.11.131:3128', u'https': u'http://46.101.11.131:3128'}
[debug] Using fake IP 25.25.93.127 (GB) as X-Forwarded-For.
[ITV] Ya1096: Downloading webpage
ERROR: Unable to extract params; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 792, in extract_info
      ie_result = ie.extract(url)
        File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 503, in extract
	    ie_result = self._real_extract(url)
	      File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/itv.py", line 60, in _real_extract
	          r'(?s)(<[^>]+id="video"[^>]*>)', webpage, 'params'))
		    File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 883, in _search_regex
		        raise RegexNotFoundError('Unable to extract %s' % _name)
			RegexNotFoundError: Unable to extract params; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


...
<end of log>
```

**Comment by dstftw** [comment]
FYI, you don't need to use proxy.
