### ISSUE TITLE
Issue downloading from Telemundo (ThePlatform)

### ISSUE THREAD

**Issue by ravonel** [rg3/youtube-dl#16559]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.05.26*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.05.26**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'http://www.telemundo.com/series-y-nove
las/2018/04/09/mi-familia-perfecta-capitulo-1-la-familia-guerrero-lucha-unida-po
r-traer']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.05.26
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-87353-g183fd30, ffprobe N-87353-g183fd30, phantom
js 2.1.1, rtmpdump 2.3
[debug] Proxy map: {}
[generic] mi-familia-perfecta-capitulo-1-la-familia-guerrero-lucha-unida-por-tra
er: Requesting header
WARNING: Falling back on generic information extractor.
[generic] mi-familia-perfecta-capitulo-1-la-familia-guerrero-lucha-unida-por-tra
er: Downloading webpage
[generic] mi-familia-perfecta-capitulo-1-la-familia-guerrero-lucha-unida-por-tra
er: Extracting information
[download] Downloading playlist: Mi Familia Perfecta, Capítulo 1: La familia Gue
rrero lucha unida por traer a su madre de vuelta a los Estados Unidos
[generic] playlist Mi Familia Perfecta, Capítulo 1: La familia Guerrero lucha un
ida por traer a su madre de vuelta a los Estados Unidos: Collected 1 video ids (
downloading 1 of them)
[download] Downloading video 1 of 1
[ThePlatform] 7fEp8BzPeTNl: Downloading SMIL data
[ThePlatform] 7fEp8BzPeTNl: Checking video URL
[ThePlatform] 7fEp8BzPeTNl: video URL is invalid, skipping
[ThePlatform] 7fEp8BzPeTNl: Checking video URL
[ThePlatform] 7fEp8BzPeTNl: video URL is invalid, skipping
[ThePlatform] 7fEp8BzPeTNl: Checking video URL
[ThePlatform] 7fEp8BzPeTNl: video URL is invalid, skipping
[ThePlatform] 7fEp8BzPeTNl: Checking video URL
[ThePlatform] 7fEp8BzPeTNl: video URL is invalid, skipping
[ThePlatform] 7fEp8BzPeTNl: Checking video URL
[ThePlatform] 7fEp8BzPeTNl: video URL is invalid, skipping
[ThePlatform] 7fEp8BzPeTNl: Checking video URL
[ThePlatform] 7fEp8BzPeTNl: video URL is invalid, skipping
[ThePlatform] 7fEp8BzPeTNl: Checking video URL
[ThePlatform] 7fEp8BzPeTNl: video URL is invalid, skipping
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug
 . Make sure you are using the latest version; type  youtube-dl -U  to update. B
e sure to call youtube-dl with the --verbose flag and include its complete outpu
t.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpyarvtrja\bu
ild\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpyarvtrja\bu
ild\youtube_dl\extractor\common.py", line 500, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpyarvtrja\bu
ild\youtube_dl\extractor\theplatform.py", line 296, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpyarvtrja\bu
ild\youtube_dl\extractor\common.py", line 1190, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issu
e on https://yt-dl.org/bug . Make sure you are using the latest version; type  y
outube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and
include its complete output.
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://www.telemundo.com/series-y-novelas/2018/04/09/mi-familia-perfecta-capitulo-1-la-familia-guerrero-lucha-unida-por-traer

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

I've marked this as both a bug report and site support request because although Telemundo uses ThePlatform which is already supported, maybe it's still considered a new site.

Telemundo's site is freely accessible to everyone at least in the US, I'm not sure if a VPN is needed outside it. No account or registration is needed to view the videos.

From what I can see, youtube-dl looks up the link URL (http://link.theplatform.com/s/0L7ZPC/7fEp8BzPeTNl?mbr=true for the video above) and gets a SMIL xml file, with the video links of the type: 
```	
<video src="http://telemundo-vh.akamaihd.net/z/MPX/video/NBCU_Telemundo/20180409/3698356_1523301962/180409_3698356_Mi_Familia_Perfecta__Capitulo_1__La_familia__4000.mp4?hdnea=st=1527362164~exp=1527369394~acl=/z/MPX/video/NBCU_Telemundo/20180409/3698356_1523301962/180409_3698356_Mi_Familia_Perfecta__Capitulo_1__La_familia__*~id=d5de207c-193a-443c-8202-83a543d8bd05~hmac=fef08bdf2c2b9721284cae70cf3cb3161ddac93ff96c563cb7197d0ec96ce525" system-bitrate="4096000" height="1080" width="1920"/>
<video src="http://telemundo-vh.akamaihd.net/z/MPX/video/NBCU_Telemundo/20180409/3698356_1523301962/180409_3698356_Mi_Familia_Perfecta__Capitulo_1__La_familia__2500.mp4?hdnea=st=1527362164~exp=1527369394~acl=/z/MPX/video/NBCU_Telemundo/20180409/3698356_1523301962/180409_3698356_Mi_Familia_Perfecta__Capitulo_1__La_familia__*~id=d5de207c-193a-443c-8202-83a543d8bd05~hmac=fef08bdf2c2b9721284cae70cf3cb3161ddac93ff96c563cb7197d0ec96ce525" system-bitrate="2560000" height="720" width="1280"/>
```
But none of those are accessible, which is why you get a whole list of video URL is invalid missing errors. I also tried running youtube-dl on the master.m3u8 and got an error.
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://telemundo-vh.akamaihd.net/i/MPX/video
/NBCU_Telemundo/20180409/3698356_1523301962/180409_3698356_Mi_Familia_Perfecta__
Capitulo_1__La_familia__,40,25,18,12,7,4,2,00.mp4.csmil/master.m3u8?__b__=1000']

[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.05.26
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-87353-g183fd30, ffprobe N-87353-g183fd30, phantom
js 2.1.1, rtmpdump 2.3
[debug] Proxy map: {}
[generic] master: Requesting header
WARNING: Could not send HEAD request to https://telemundo-vh.akamaihd.net/i/MPX/
video/NBCU_Telemundo/20180409/3698356_1523301962/180409_3698356_Mi_Familia_Perfe
cta__Capitulo_1__La_familia__,40,25,18,12,7,4,2,00.mp4.csmil/master.m3u8?__b__=1
000: HTTP Error 405: Method Not Allowed
[generic] master: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPErro
r()); please report this issue on https://yt-dl.org/bug . Make sure you are usin
g the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl
 with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpyarvtrja\bu
ild\youtube_dl\extractor\common.py", line 579, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpyarvtrja\bu
ild\youtube_dl\YoutubeDL.py", line 2211, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
```
There's a similar result with the index_*_av.m3u8 files.

**Comment by fnadde42** [comment]
I had recently a similar problem when trying to download a video with a `index_*_av.m3u8` link. I got a `405: Method Not Allowed` as well. It turned out to be the web server denying any tool except a web browser. I got the 405 error when I used `curl` as well as `youtube-dl` but not when I pasted the link directly in the browser, so I used the build in option to modify headers in youtube-dl. When I ran the command like this, all the links I got 405 on started to work:

```bash
youtube-dl --add-header 'User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0' <my_URL>
```

You can of course get your own `User-Agent` value and replace mine with it.
