### ISSUE TITLE
youtube-dl falsely alarms for bugreport, while there's no bug, just a removed video in a playlist

### ISSUE THREAD

**Issue by Petrox** [rg3/youtube-dl#16566]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.05.26*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2018.05.26**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
...
<end of log>
```
/usr/local/bin/youtube-dl "https://www.youtube.com/watch?v=OUYTNywPk-s&list=PLj6h78yzYM2N8GdbjmhVU65KYm_68qBmo"
[youtube:playlist] Downloading playlist PLj6h78yzYM2N8GdbjmhVU65KYm_68qBmo - add --no-playlist to just download video OUYTNywPk-s
[youtube:playlist] PLj6h78yzYM2N8GdbjmhVU65KYm_68qBmo: Downloading webpage
[download] Downloading playlist: KubeCon + CloudNativeCon 2018 - Copenhagen
[youtube:playlist] PLj6h78yzYM2N8GdbjmhVU65KYm_68qBmo: Downloading page #1
[youtube:playlist] PLj6h78yzYM2N8GdbjmhVU65KYm_68qBmo: Downloading page #2
[youtube:playlist] PLj6h78yzYM2N8GdbjmhVU65KYm_68qBmo: Downloading page #3
[youtube:playlist] playlist KubeCon + CloudNativeCon 2018 - Copenhagen: Downloading 309 videos
[download] Downloading video 1 of 309
[youtube] OUYTNywPk-s: Downloading webpage
[youtube] OUYTNywPk-s: Downloading video info webpage
[youtube] OUYTNywPk-s: Extracting video information
[download] Keynote - Anatomy of a Production Kubernetes Outage - Oliver Beattie, Head of Engineering, Monzo Bank-OUYTNywPk-s.webm has already been downloaded and merged
[download] Downloading video 2 of 309
[youtube] _CFgSksTT54: Downloading webpage
[youtube] _CFgSksTT54: Downloading video info webpage
[youtube] _CFgSksTT54: Extracting video information
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[download] Cloud Native Landscape Intro – Dan Kohn, Cloud Native Computing Foundation (Any Skill Level)-_CFgSksTT54.mkv has already been downloaded and merged
[download] Downloading video 3 of 309
[youtube] _A7G5cpU4Xw: Downloading webpage
[youtube] _A7G5cpU4Xw: Downloading video info webpage
[youtube] _A7G5cpU4Xw: Extracting video information
[youtube] _A7G5cpU4Xw: Downloading MPD manifest
[youtube] _A7G5cpU4Xw: Downloading MPD manifest
[download] OpenStack SIG Intro – Chris Hoge, OpenStack Foundation, & David Lyle, Intel (Any Skill Level)-_A7G5cpU4Xw.mp4 has already been downloaded and merged
[download] Downloading video 4 of 309
[youtube] YprD0zoWXX0: Downloading webpage
[youtube] YprD0zoWXX0: Downloading video info webpage
[youtube] YprD0zoWXX0: Extracting video information
[youtube] YprD0zoWXX0: Downloading MPD manifest
[youtube] YprD0zoWXX0: Downloading MPD manifest
[download] Kubernetes Policy WG Intro – Zhipeng Huang, Huawei (Any Skill Level)-YprD0zoWXX0.mp4 has already been downloaded and merged
[download] Downloading video 5 of 309
[youtube] ug3lYZdN0Bk: Downloading webpage
[youtube] ug3lYZdN0Bk: Downloading video info webpage
[youtube] ug3lYZdN0Bk: Extracting video information
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[download] Low-Overhead Tracing Using eBPF for Observability into Kubernetes Apps and Services - Gaurav Gupta-ug3lYZdN0Bk.mkv has already been downloaded and merged
[download] Downloading video 6 of 309
[youtube] oNBpZFhL94s: Downloading webpage
[youtube] oNBpZFhL94s: Downloading video info webpage
[youtube] oNBpZFhL94s: Extracting video information
[youtube] oNBpZFhL94s: Downloading MPD manifest
[youtube] oNBpZFhL94s: Downloading MPD manifest
[download] Scalable Monitoring Using Prometheus with Apache Spark - Diane Feddema & Zak Hassan, Red Hat Inc-oNBpZFhL94s.mp4 has already been downloaded and merged
[download] Downloading video 7 of 309
[youtube] Zk09Mbu0YQk: Downloading webpage
[youtube] Zk09Mbu0YQk: Downloading video info webpage
[youtube] Zk09Mbu0YQk: Extracting video information
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[download] How to Export Prometheus Metrics from Just About Anything - Matt Layher, DigitalOcean-Zk09Mbu0YQk.mkv has already been downloaded and merged
[download] Downloading video 8 of 309
[youtube] ZHCSmYvA_sg: Downloading webpage
[youtube] ZHCSmYvA_sg: Downloading video info webpage
[youtube] ZHCSmYvA_sg: Extracting video information
[youtube] ZHCSmYvA_sg: Downloading MPD manifest
[youtube] ZHCSmYvA_sg: Downloading MPD manifest
[download] Prometheus for Devs - Hubert Ströbitzer, Freelancer (Beginner Skill Level)-ZHCSmYvA_sg.mp4 has already been downloaded and merged
[download] Downloading video 9 of 309
[youtube] Nxqd7y78h7Q: Downloading webpage
[youtube] Nxqd7y78h7Q: Downloading video info webpage
WARNING: Unable to extract video title
[youtube] Nxqd7y78h7Q: Extracting video information
WARNING: unable to extract uploader name
WARNING: unable to extract uploader nickname
WARNING: unable to extract video duration; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
ERROR: This video is unavailable.

with verbose:

$ /usr/local/bin/youtube-dl "https://www.youtube.com/watch?v=OUYTNywPk-s&list=PLj6h78yzYM2N8GdbjmhVU65KYm_68qBmo" --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.youtube.com/watch?v=OUYTNywPk-s&list=PLj6h78yzYM2N8GdbjmhVU65KYm_68qBmo', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.05.26
[debug] Python version 2.7.6 (CPython) - Linux-4.4.0-124-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 11.3-6, avprobe 11.3-6, ffmpeg 3.3.3, ffprobe 3.3.3, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:playlist] Downloading playlist PLj6h78yzYM2N8GdbjmhVU65KYm_68qBmo - add --no-playlist to just download video OUYTNywPk-s
[youtube:playlist] PLj6h78yzYM2N8GdbjmhVU65KYm_68qBmo: Downloading webpage
[download] Downloading playlist: KubeCon + CloudNativeCon 2018 - Copenhagen
[youtube:playlist] PLj6h78yzYM2N8GdbjmhVU65KYm_68qBmo: Downloading page #1
[youtube:playlist] PLj6h78yzYM2N8GdbjmhVU65KYm_68qBmo: Downloading page #2
[youtube:playlist] PLj6h78yzYM2N8GdbjmhVU65KYm_68qBmo: Downloading page #3
[youtube:playlist] playlist KubeCon + CloudNativeCon 2018 - Copenhagen: Downloading 309 videos
[download] Downloading video 1 of 309
[youtube] OUYTNywPk-s: Downloading webpage
[youtube] OUYTNywPk-s: Downloading video info webpage
[youtube] OUYTNywPk-s: Extracting video information
[debug] Default format spec: bestvideo+bestaudio/best
[download] Keynote - Anatomy of a Production Kubernetes Outage - Oliver Beattie, Head of Engineering, Monzo Bank-OUYTNywPk-s.webm has already been downloaded and merged
[download] Downloading video 2 of 309
[youtube] _CFgSksTT54: Downloading webpage
[youtube] _CFgSksTT54: Downloading video info webpage
[youtube] _CFgSksTT54: Extracting video information
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[download] Cloud Native Landscape Intro – Dan Kohn, Cloud Native Computing Foundation (Any Skill Level)-_CFgSksTT54.mkv has already been downloaded and merged
[download] Downloading video 3 of 309
[youtube] _A7G5cpU4Xw: Downloading webpage
[youtube] _A7G5cpU4Xw: Downloading video info webpage
[youtube] _A7G5cpU4Xw: Extracting video information
[youtube] _A7G5cpU4Xw: Downloading MPD manifest
[youtube] _A7G5cpU4Xw: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
[download] OpenStack SIG Intro – Chris Hoge, OpenStack Foundation, & David Lyle, Intel (Any Skill Level)-_A7G5cpU4Xw.mp4 has already been downloaded and merged
[download] Downloading video 4 of 309
[youtube] YprD0zoWXX0: Downloading webpage
[youtube] YprD0zoWXX0: Downloading video info webpage
[youtube] YprD0zoWXX0: Extracting video information
[youtube] YprD0zoWXX0: Downloading MPD manifest
[youtube] YprD0zoWXX0: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
[download] Kubernetes Policy WG Intro – Zhipeng Huang, Huawei (Any Skill Level)-YprD0zoWXX0.mp4 has already been downloaded and merged
[download] Downloading video 5 of 309
[youtube] ug3lYZdN0Bk: Downloading webpage
[youtube] ug3lYZdN0Bk: Downloading video info webpage
[youtube] ug3lYZdN0Bk: Extracting video information
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[download] Low-Overhead Tracing Using eBPF for Observability into Kubernetes Apps and Services - Gaurav Gupta-ug3lYZdN0Bk.mkv has already been downloaded and merged
[download] Downloading video 6 of 309
[youtube] oNBpZFhL94s: Downloading webpage
[youtube] oNBpZFhL94s: Downloading video info webpage
[youtube] oNBpZFhL94s: Extracting video information
[youtube] oNBpZFhL94s: Downloading MPD manifest
[youtube] oNBpZFhL94s: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
[download] Scalable Monitoring Using Prometheus with Apache Spark - Diane Feddema & Zak Hassan, Red Hat Inc-oNBpZFhL94s.mp4 has already been downloaded and merged
[download] Downloading video 7 of 309
[youtube] Zk09Mbu0YQk: Downloading webpage
[youtube] Zk09Mbu0YQk: Downloading video info webpage
[youtube] Zk09Mbu0YQk: Extracting video information
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[download] How to Export Prometheus Metrics from Just About Anything - Matt Layher, DigitalOcean-Zk09Mbu0YQk.mkv has already been downloaded and merged
[download] Downloading video 8 of 309
[youtube] ZHCSmYvA_sg: Downloading webpage
[youtube] ZHCSmYvA_sg: Downloading video info webpage
[youtube] ZHCSmYvA_sg: Extracting video information
[youtube] ZHCSmYvA_sg: Downloading MPD manifest
[youtube] ZHCSmYvA_sg: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
[download] Prometheus for Devs - Hubert Ströbitzer, Freelancer (Beginner Skill Level)-ZHCSmYvA_sg.mp4 has already been downloaded and merged
[download] Downloading video 9 of 309
[youtube] Nxqd7y78h7Q: Downloading webpage
[youtube] Nxqd7y78h7Q: Downloading video info webpage
WARNING: Unable to extract video title
[youtube] Nxqd7y78h7Q: Extracting video information
WARNING: unable to extract uploader name
WARNING: unable to extract uploader nickname
WARNING: unable to extract video duration; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
ERROR: This video is unavailable.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 500, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 1990, in _real_extract
    raise ExtractorError(error_message, expected=True)
ExtractorError: This video is unavailable.

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):

https://www.youtube.com/watch?v=OUYTNywPk-s&list=PLj6h78yzYM2N8GdbjmhVU65KYm_68qBmo

---

### Description of your *issue*, suggested solution and other information

So we've got a playlist with some removed videos in it - "normal youtube user experience".

youtube-dl quits with an error message: "ERROR: This video is unavailable." this is not a problem - though it could help the users to use -i to not quit. (Actually that could be the default setting but that's not the scope here.)

The problem is, that youtube-dl scares the user to submit a bug:

[youtube] Nxqd7y78h7Q: Downloading video info webpage
WARNING: Unable to extract video title
[youtube] Nxqd7y78h7Q: Extracting video information
WARNING: unable to extract uploader name
WARNING: unable to extract uploader nickname
WARNING: unable to extract video duration; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

So the only BUG is that the program should check for the "ERROR: This video is unavailable" before telling people "this is a bug please file a bug!". 

Actually https://github.com/rg3/youtube-dl/issues/16510 is the very nice example, that your program asks your users to submit bugs, then later you close it as not a bug, but this was all unnecessary, if the bugfiling would be not printed when the playlist contains a missing video (actually this playlist  contains a removed and at least one "private" marked video, so it's nice to test with.)

**Comment by Petrox** [comment]
FYI: For a later try youtube gave a different response (the video might contain music maybe)


WARNING: unable to extract video duration; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
ERROR: This video has been removed for violating YouTube's Terms of Service.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 500, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 1990, in _real_extract
    raise ExtractorError(error_message, expected=True)
ExtractorError: This video has been removed for violating YouTube's Terms of Service.
