### ISSUE TITLE
Site support request: polony.tv

### ISSUE THREAD

**Issue by pitrou** [rg3/youtube-dl#16572]
This is a French journalism TV and extracting videos currently fails:

```
$ youtube-dl --version
2018.05.26
$ youtube-dl -v https://polony.tv/rencontres/pierre-manent-il-faut-arreter-l-ingenierie-in
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://polony.tv/rencontres/pierre-manent-il-faut-arreter-l-ingenierie-in']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.05.26
[debug] Python version 3.6.3 (CPython) - Linux-4.15.0-22-generic-x86_64-with-debian-stretch-sid
[debug] exe versions: avconv 2.8.14-0ubuntu0.16.04.1, avprobe 2.8.14-0ubuntu0.16.04.1, ffmpeg 2.8.14-0ubuntu0.16.04.1, ffprobe 2.8.14-0ubuntu0.16.04.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] pierre-manent-il-faut-arreter-l-ingenierie-in: Requesting header
WARNING: Falling back on generic information extractor.
[generic] pierre-manent-il-faut-arreter-l-ingenierie-in: Downloading webpage
[generic] pierre-manent-il-faut-arreter-l-ingenierie-in: Extracting information
ERROR: Unsupported URL: https://polony.tv/rencontres/pierre-manent-il-faut-arreter-l-ingenierie-in
Traceback (most recent call last):
  File "/home/antoine/miniconda3/envs/youtube-dl/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/home/antoine/miniconda3/envs/youtube-dl/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 500, in extract
    ie_result = self._real_extract(url)
  File "/home/antoine/miniconda3/envs/youtube-dl/lib/python3.6/site-packages/youtube_dl/extractor/generic.py", line 3240, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://polony.tv/rencontres/pierre-manent-il-faut-arreter-l-ingenierie-in
```

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.05.26*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.05.26**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other
---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://polony.tv/rencontres/pierre-manent-il-faut-arreter-l-ingenierie-in

**Comment by pitrou** [comment]
Updated request, still doesn't work:
```
$ youtube-dl --version
2019.11.05
$ youtube-dl -v "https://polony.tv/rencontres/david-cayla-l-enseignement-de-l-economie-doit-"
[debug] System config: []
[debug] User config: ['--no-playlist']
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://polony.tv/rencontres/david-cayla-l-enseignement-de-l-economie-doit-']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.11.05
[debug] Python version 3.6.9 (CPython) - Linux-4.15.0-70-generic-x86_64-with-debian-buster-sid
[debug] exe versions: avconv 3.4.6, avprobe 3.4.6, ffmpeg 3.4.6, ffprobe 3.4.6, rtmpdump 2.4
[debug] Proxy map: {}
[generic] david-cayla-l-enseignement-de-l-economie-doit-: Requesting header
WARNING: Falling back on generic information extractor.
[generic] david-cayla-l-enseignement-de-l-economie-doit-: Downloading webpage
[generic] david-cayla-l-enseignement-de-l-economie-doit-: Extracting information
ERROR: Unsupported URL: https://polony.tv/rencontres/david-cayla-l-enseignement-de-l-economie-doit-
Traceback (most recent call last):
  File "/home/antoine/miniconda3/envs/youtube-dl/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/home/antoine/miniconda3/envs/youtube-dl/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/home/antoine/miniconda3/envs/youtube-dl/lib/python3.6/site-packages/youtube_dl/extractor/generic.py", line 3354, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://polony.tv/rencontres/david-cayla-l-enseignement-de-l-economie-doit-

```
