### ISSUE TITLE
Twitter video downloads no longer work

### ISSUE THREAD

**Issue by mwpher** [rg3/youtube-dl#16586]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.05.30**
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

When attempting to download this URL: https://twitter.com/LisPower1/status/1001551623938805763

I get this message:

```PS C:\Users\Matt\bin> .\youtube-dl.exe https://twitter.com/LisPower1/status/1001551623938805763
[twitter] 1001551623938805763: Downloading webpage
[twitter:card] 1001551623938805763: Downloading webpage
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest ve
rsion; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete outpu
t.
PS C:\Users\Matt\bin>
```

Here's the verbose output:
```PS C:\Users\Matt\bin> .\youtube-dl.exe https://twitter.com/LisPower1/status/1001551623938805763 --verbose *> debug.txt
[debug] System config: []
[debug] User config: ['--embed-subs', '--embed-thumbnail', '--add-metadata', '-f', 'mp4', '-o', '%(upload_date)s_%(title
)s.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: ['https://twitter.com/LisPower1/status/1001551623938805763', '--verbose', '*>', 'debug.txt']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.05.30
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 3.4.1, ffprobe 3.4.1, rtmpdump 2.3
[debug] Proxy map: {}
[twitter] 1001551623938805763: Downloading webpage
[twitter:card] 1001551623938805763: Downloading webpage
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest ve
rsion; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete outpu
t.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpreyzoe3x\build\youtube_dl\YoutubeDL.py", line 792,
in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpreyzoe3x\build\youtube_dl\extractor\common.py", lin
e 500, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpreyzoe3x\build\youtube_dl\extractor\twitter.py", li
ne 229, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpreyzoe3x\build\youtube_dl\extractor\common.py", lin
e 1190, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure y
ou are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and
include its complete output.

PS C:\Users\Matt\bin>
```

I notice that Firefox DownloadHelper can't get the video either. I presume Twitter changed how they display video.

**Comment by aaether32323** [comment]
Seconding this, I can reproduce with the following configuration:
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://twitter.com/LisPower1/status/1001551623938805763', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2018.04.09
[debug] Python version 3.6.5 (CPython) - Windows-10-10.0.16299-SP0
[debug] exe versions: ffmpeg 4.0, ffprobe 4.0
[debug] Proxy map: {}
[twitter] 1001551623938805763: Downloading webpage
ERROR: Unable to extract OpenGraph title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\users\a3\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\YoutubeDL.py", line 789, in extract_info
    ie_result = ie.extract(url)
  File "c:\users\a3\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\extractor\common.py", line 440, in extract

    ie_result = self._real_extract(url)
  File "c:\users\a3\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\extractor\twitter.py", line 395, in _real_extract
    username = remove_end(self._og_search_title(webpage), ' on Twitter')
  File "c:\users\a3\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\extractor\common.py", line 920, in _og_search_title
    return self._og_search_property('title', html, **kargs)
  File "c:\users\a3\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\extractor\common.py", line 908, in _og_search_property
    escaped = self._search_regex(og_regexes, html, name, flags=re.DOTALL, **kargs)
  File "c:\users\a3\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\extractor\common.py", line 808, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract OpenGraph title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by adamhotep** [comment]
This is true even of videos I've previously pulled without incident. Twitter must have changed something.  here's a Debian verbose dump (using latest youtube-dl available in [Deb Multimedia](https://www.deb-multimedia.org/)):
```none
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://twitter.com/KentMurphy/status/990955691878813697']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.05.26
[debug] Python version 3.6.5rc1 (CPython) - Linux-4.16.0-1-amd64-x86_64-with-Debian-9.0-stretch
[debug] exe versions: ffmpeg 4.0, ffprobe 4.0, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[twitter] 990955691878813697: Downloading webpage
[twitter:card] 990955691878813697: Downloading webpage
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 500, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/twitter.py", line 229, in _real_extract
    self._sort_formats(formats)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 1190, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by moniesoke** [comment]
In fact, videos from May 29th is still downloadable now. However, videos on May 30th are not downloadable at all.

**Comment by Kikobeats** [comment]
I confirm May 30th introducing a bug there:

Previous build
https://travis-ci.org/microlinkhq/metascraper/builds/385291329

Same build but using youtube-dl Day 30 compilation:
https://travis-ci.org/microlinkhq/metascraper/builds/386107431

**Comment by valdotdev** [comment]
Same on mine. Using version `2018.05.18`

**Comment by RealJTG** [comment]
There's `blob://` source now :(
```html
<video 
preload="none" 
playsinline="" poster="https://pbs.twimg.com/ext_tw_video_thumb/1001434684172124160/pu/img/iA7CJzdkdtrGQdlM.jpg" 
src="blob:https://twitter.com/62b27569-7fb4-4157-bfa2-e860685ed1b5"
style="width: 100%; height: 100%; position: absolute; transform: rotate(0deg) scale(1);">
</video>
```

**Comment by gbe1** [comment]
More evidence:

[twitter_error.log](https://github.com/rg3/youtube-dl/files/2060095/twitter_error.log)
