### ISSUE TITLE
HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by decentsam** [rg3/youtube-dl#16615]
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by decentsam** [comment]
[download] Downloading video 1 of 267
[debug] Using fake IP 117.234.134.49 (IN) as X-Forwarded-For.
[HotStar] 1000213346: Downloading JSON metadata
[HotStar] 1000213346: Downloading JIO JSON metadata
[HotStar] 1000213346: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp2pwxs9zy\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp2pwxs9zy\build\youtube_dl\extractor\common.py", line 500, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp2pwxs9zy\build\youtube_dl\extractor\hotstar.py", line 102, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp2pwxs9zy\build\youtube_dl\extractor\common.py", line 1190, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
