### ISSUE TITLE
Trouble downloading videos that require a cable provider

### ISSUE THREAD

**Issue by case100** [rg3/youtube-dl#16630]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.06.04*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.06.04**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['http://www.adultswim.com/videos/joe-pera-talks-with-you/joe-pera-shows-you-iron/', '--ap-mso=Comcast_SSO', '--ap-username=PRIVATE', '--ap-password=PRIVATE', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.06.04
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg 3.4, ffprobe 3.4
[debug] Proxy map: {}
[AdultSwim] joe-pera-shows-you-iron: Downloading webpage
[AdultSwim] AWNfUf_ZHAeP4-pUPfOc: Downloading XML
ERROR: Could not find XML element's text headline; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptg2apcao\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptg2apcao\build\youtube_dl\extractor\common.py", line 500, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptg2apcao\build\youtube_dl\extractor\adultswim.py", line 138, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptg2apcao\build\youtube_dl\extractor\turner.py", line 54, in _extract_cvp_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptg2apcao\build\youtube_dl\utils.py", line 321, in xpath_text
youtube_dl.utils.ExtractorError: Could not find XML element's text headline; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://www.adultswim.com/videos/joe-pera-talks-with-you/joe-pera-shows-you-iron
- Single video: http://www.adultswim.com/videos/joe-pera-talks-with-you/joe-pera-takes-you-to-breakfast
- Single video: http://www.adultswim.com/videos/joe-pera-talks-with-you/joe-pera-takes-you-on-a-fall-drive
- Single video: http://www.adultswim.com/videos/joe-pera-talks-with-you/joe-pera-shows-you-how-to-dance

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Every time I attempt to download videos that require a cable provider login, I get this error message below:

ERROR: Could not find XML element's text headline; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

I tried the following formats:
Code:
youtube-dl -U
youtube-dl --verbose
youtube-dl -F url
youtube-dl url --ap-mso=Comcast_SSO --ap-username=USERNAME --ap-password=PASSWORD
I tried: cleaning my cache, TVDownloader, reconnecting to the Internet, restarting my computer.

I need help downloading the videos.

**Comment by DragonVsKira** [comment]
SAME plz fix it

**Comment by BlohoJo** [comment]
Same issue on Adult Swim.

(I missed this post and opened a duplicate issue. Sorry about that).

Youtube-dl version 2018.07.10, "Could not find XML element's text headline", tried both cookies and mso.

--cookies:
```
K:\temp_ytdl>youtube-dl.exe --verbose --all-subs --embed-subs --cookies cookies.
txt "http://www.adultswim.com/videos/mostly-4-millennials/diversity/"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--all-subs', '--embed-subs', '--cookie
s', 'cookies.txt', 'http://www.adultswim.com/videos/mostly-4-millennials/diversi
ty/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.07.10
[debug] Python version 3.4.4 (CPython) - Windows-XP-5.1.2600-SP3
[debug] exe versions: ffmpeg N-86763-g341f012-Reino, ffprobe N-72220-gd0ac2f5
[debug] Proxy map: {}
[AdultSwim] diversity: Downloading webpage
[AdultSwim] AWRc13fHTdxzjxdCmuVQ: Downloading XML
ERROR: Could not find XML element's text headline; please report this issue on h
ttps://yt-dl.org/bug . Make sure you are using the latest version; type  youtube
-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and includ
e its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4etivjk5\bu
ild\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4etivjk5\bu
ild\youtube_dl\extractor\common.py", line 502, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4etivjk5\bu
ild\youtube_dl\extractor\adultswim.py", line 138, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4etivjk5\bu
ild\youtube_dl\extractor\turner.py", line 54, in _extract_cvp_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4etivjk5\bu
ild\youtube_dl\utils.py", line 322, in xpath_text
youtube_dl.utils.ExtractorError: Could not find XML element's text headline; ple
ase report this issue on https://yt-dl.org/bug . Make sure you are using the lat
est version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the
 --verbose flag and include its complete output.
...
<end of log>
```

--ap-mso:
```
K:\temp_ytdl>youtube-dl.exe --verbose --all-subs --embed-subs --ap-mso Charter_D
irect --ap-username PRIVATE --ap-password PRIVATE "http://
www.adultswim.com/videos/mostly-4-millennials/diversity/"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--all-subs', '--embed-subs', '--ap-mso
', 'Charter_Direct', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', 'ht
tp://www.adultswim.com/videos/mostly-4-millennials/diversity/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.07.10
[debug] Python version 3.4.4 (CPython) - Windows-XP-5.1.2600-SP3
[debug] exe versions: ffmpeg N-86763-g341f012-Reino, ffprobe N-72220-gd0ac2f5
[debug] Proxy map: {}
[AdultSwim] diversity: Downloading webpage
[AdultSwim] AWRc13fHTdxzjxdCmuVQ: Downloading XML
ERROR: Could not find XML element's text headline; please report this issue on h
ttps://yt-dl.org/bug . Make sure you are using the latest version; type  youtube
-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and includ
e its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4etivjk5\bu
ild\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4etivjk5\bu
ild\youtube_dl\extractor\common.py", line 502, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4etivjk5\bu
ild\youtube_dl\extractor\adultswim.py", line 138, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4etivjk5\bu
ild\youtube_dl\extractor\turner.py", line 54, in _extract_cvp_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4etivjk5\bu
ild\youtube_dl\utils.py", line 322, in xpath_text
youtube_dl.utils.ExtractorError: Could not find XML element's text headline; ple
ase report this issue on https://yt-dl.org/bug . Make sure you are using the lat
est version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the
 --verbose flag and include its complete output.
...
<end of log>
```
