### ISSUE TITLE
Dmm.co.jp site temporary download support request

### ISSUE THREAD

**Issue by supermansaga** [rg3/youtube-dl#16648]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.06.04**
- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Site support request (request for adding support for a new site)

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
C:\youtube_dl>youtube-dl -v http://www.dmm.co.jp/digital/-/player/=/player=html5/act=playlist/pid=118abp00504/view_flag=1/parent_product_id=118abp00504/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://www.dmm.co.jp/digital/-/player/=/player=html5/act=playlist/pid=118abp00504/view_flag=1/parent_product_id=118abp00504/']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2018.06.04
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg N-90872-g92a0a6bea9
[debug] Proxy map: {}
[generic] parent_product_id=118abp00504: Requesting header
[redirect] Following redirect to https://www.dmm.co.jp/my/-/login/=/path=SgVZXg9CAF4XSB5IX1cfUhNKCxlAVQVABxAKDkYIWwVKAFNNW0YNU0EJWEtHGRZeBVgHBwhYBklSUgJWBkpBWQAWb18KVwYPCUpBWUFTCEM%2AFURZVEwHTT0LU1sDVA9RBxEACVMGVR0_/
[generic] path=SgVZXg9CAF4XSB5IX1cfUhNKCxlAVQVABxAKDkYIWwVKAFNNW0YNU0EJWEtHGRZeBVgHBwhYBklSUgJWBkpBWQAWb18KVwYPCUpBWUFTCEM*FURZVEwHTT0LU1sDVA9RBxEACVMGVR0_: Requesting header
WARNING: Falling back on generic information extractor.
[generic] path=SgVZXg9CAF4XSB5IX1cfUhNKCxlAVQVABxAKDkYIWwVKAFNNW0YNU0EJWEtHGRZeBVgHBwhYBklSUgJWBkpBWQAWb18KVwYPCUpBWUFTCEM*FURZVEwHTT0LU1sDVA9RBxEACVMGVR0_: Downloading webpage
[generic] path=SgVZXg9CAF4XSB5IX1cfUhNKCxlAVQVABxAKDkYIWwVKAFNNW0YNU0EJWEtHGRZeBVgHBwhYBklSUgJWBkpBWQAWb18KVwYPCUpBWUFTCEM*FURZVEwHTT0LU1sDVA9RBxEACVMGVR0_: Extracting information
ERROR: Unsupported URL: https://www.dmm.co.jp/my/-/login/=/path=SgVZXg9CAF4XSB5IX1cfUhNKCxlAVQVABxAKDkYIWwVKAFNNW0YNU0EJWEtHGRZeBVgHBwhYBklSUgJWBkpBWQAWb18KVwYPCUpBWUFTCEM%2AFURZVEwHTT0LU1sDVA9RBxEACVMGVR0_/
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptg2apcao\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptg2apcao\build\youtube_dl\extractor\common.py", line 500, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptg2apcao\build\youtube_dl\extractor\generic.py", line 3263, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.dmm.co.jp/my/-/login/=/path=SgVZXg9CAF4XSB5IX1cfUhNKCxlAVQVABxAKDkYIWwVKAFNNW0YNU0EJWEtHGRZeBVgHBwhYBklSUgJWBkpBWQAWb18KVwYPCUpBWUFTCEM%2AFURZVEwHTT0LU1sDVA9RBxEACVMGVR0_/
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

htxp://www.dmm.co.jp/digital/-/player/=/player=html5/act=playlist/pid=118abp00504/view_flag=1/parent_product_id=118abp00504/

I ran into the said url after purchasing streaming right for 7 days. At the highest quality of 6000kbps, the video keeps buffering and buffering. Is there a way for youtube-dl to support this site so that i could download it without streaming/buffering it every single time? After 7 days, I'll delete the video. Thanks,

**Comment by UnixNight** [comment]
I would also like this site to be supported by Youtube-dl
