### ISSUE TITLE
PBS video says: "Unable to extract video ID; please report this issue on https://yt-dl.org/bug"

### ISSUE THREAD

**Issue by ethus3h** [rg3/youtube-dl#16684]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.06.04*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.06.04**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones **This link is broken, it lists recent issues instead of giving a way to search for issues. The current URL seems to be to just use the issues page in the format [https://github.com/rg3/youtube-dl/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+search+term](https://github.com/rg3/youtube-dl/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+search+term)...**
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
kyan@elegiac ~/ytdled-2018june09 nohup compiz --replace openbox $ youtube-dl -i --geo-bypass --write-description --write-info-json --write-annotations --write-thumbnail --write-all-thumbnails --write-sub --write-auto-sub --all-subs -k --verbose 'https://player.pbs.org/partnerplayer/tOz9tM5ljOXQqIIWke53UA==/'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-i', u'--geo-bypass', u'--write-description', u'--write-info-json', u'--write-annotations', u'--write-thumbnail', u'--write-all-thumbnails', u'--write-sub', u'--write-auto-sub', u'--all-subs', u'-k', u'--verbose', u'https://player.pbs.org/partnerplayer/tOz9tM5ljOXQqIIWke53UA==/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.06.04
[debug] Python version 2.7.14 (CPython) - Linux-4.9.34-wreathe-x86_64-Intel-R-_Core-TM-_i7-6560U_CPU_@_2.20GHz-with-gentoo-2.4.1
[debug] exe versions: ffmpeg 3.4.2, ffprobe 3.4.2, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Using fake IP 3.64.220.217 (US) as X-Forwarded-For.
[pbs] Downloading JSON metadata
[pbs] tOz9tM5ljOXQqIIWke53UA==: Downloading player page
ERROR: Unable to extract video ID; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/common.py", line 500, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/pbs.py", line 493, in _real_extract
    video_id, display_id, upload_date, description = self._extract_webpage(url)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/pbs.py", line 485, in _extract_webpage
    r'<div\s+id="video_([0-9]+)"', player_page, 'video ID')
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/common.py", line 880, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video ID; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

Downloading this item fails with 'Unable to extract video ID; please report this issue on https://yt-dl.org/bug'. I'm using a version from git earlier today, rather than tagged release, for what it's worth. Using Gentoo GNU/Linux. Here is the video link for test in Web browser: [https://player.pbs.org/partnerplayer/tOz9tM5ljOXQqIIWke53UA==/](https://player.pbs.org/partnerplayer/tOz9tM5ljOXQqIIWke53UA==/)

**Comment by ethus3h** [comment]
Sweet, tested and it works now! Thank you @Urgau and @dstftw ! :)
