### ISSUE TITLE
Simple command fails to download only video on webpage

### ISSUE THREAD

**Issue by Kaos-Industries** [rg3/youtube-dl#16693]
### Make sure you are using the latest version: run youtube-dl --version and ensure your version is 2018.06.11.

- [x] I've verified and I assure that I'm running youtube-dl 2018.06.11

### Before submitting an *issue* make sure you have:

- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

I'm trying to download the only video at the following link:

http://www.primeeg.com/catalog/program/1277/zara-the-story-of-the-world-s-richest-man#

I used the following command:

`youtube-dl -v http://www.primeeg.com/catalog/program/1277/zara-the-story-of-the-world-s-richest-man`

And got the following output:

```
[debug] System config: []
[debug] User config: ['-o', 'B:/Users/Me/Desktop/youtube-dl Output/%(title)s
.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://www.primeeg.com/catalog/program/1277/z
ara-the-story-of-the-world-s-richest-man']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.06.11
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-78268-g0ab25da, ffprobe N-78268-g0ab25da
[debug] Proxy map: {}
[generic] zara-the-story-of-the-world-s-richest-man: Requesting header
WARNING: Falling back on generic information extractor.
[generic] zara-the-story-of-the-world-s-richest-man: Downloading webpage
[generic] zara-the-story-of-the-world-s-richest-man: Extracting information
[download] Downloading playlist: Prime Entertainment Group
[generic] playlist Prime Entertainment Group: Collected 1 video ids (downloading
 1 of them)
[download] Downloading video 1 of 1
[dailymotion] k7GrmOZSTLeNVxlxLPB: Downloading webpage
ERROR: An extractor error has occurred. (caused by KeyError('title',)); please report this issue on https://yt-dl.org/bug. Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0ud6453h\build\youtube_dl\extractor\common.py", line 500, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0ud6453h\build\youtube_dl\extractor\dailymotion.py", line 170, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0ud6453h\build\youtube_dl\extractor\dailymotion.py", line 306, in _check_error
KeyError: 'title'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0ud6453h\build\youtube_dl\extractor\common.py", line 500, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0ud6453h\build\youtube_dl\extractor\dailymotion.py", line 170, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0ud6453h\build\youtube_dl\extractor\dailymotion.py", line 306, in _check_error
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0ud6453h\build\youtube_dl\YoutubeDL.py", line 792, in extract_info 
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0ud6453h\build\youtube_dl\extractor\common.py", line 513, in extract youtube_dl.utils.ExtractorError: An extractor error has  occurred. (caused by KeyError('title',)); please report this issue on https://yt-dl.org/bug. Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

The video is protected by a password, which is `prime` - however, passing `--video-password prime` into the command results in a fatal error all the same. 

Does anyone have any idea what could be causing this?

**Comment by Kaos-Industries** [comment]
It would be nice if someone could tell me what exactly this is a duplicate of, as I've already searched the forums and couldn't find the same issue.

**Comment by remitamine** [comment]
#9789
