### ISSUE TITLE
facebook video parsing issue

### ISSUE THREAD

**Issue by halpz** [rg3/youtube-dl#16695]
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2018.06.11**
- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

```
Bittorrent-Bastard:~ Paul$ youtube-dl https://www.facebook.com/AncestralTomb/videos/1692837340799447 --verbose
[debug] System config: [u'--no-check-certificate', u'-o', u'~/Downloads/%(title)s.%(ext)s', u'-f', u'bestvideo+bestaudio/best', u'--write-sub', u'--sub-format', u'srt/vtt/best', u'--sub-lang', u'en', u'--prefer-ffmpeg', u'--netrc']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.facebook.com/AncestralTomb/videos/1692837340799447', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.06.11
[debug] Python version 2.7.10 (CPython) - Darwin-17.5.0-x86_64-i386-64bit
[debug] exe versions: avconv 12.3, avprobe 12.3, ffmpeg 4.0, ffprobe 4.0, rtmpdump 2.4
[debug] Proxy map: {}
[facebook] Downloading login page
[facebook] Logging in
[facebook] 1692837340799447: Downloading webpage
[facebook] 1692837340799447: Downloading webpage
[facebook] 1692837340799447: Downloading webpage
ERROR: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 500, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/facebook.py", line 462, in _real_extract
    video_id, fatal_if_no_video=True)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/facebook.py", line 376, in _extract_from_url
    raise ExtractorError('Cannot parse data')
ExtractorError: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

### Description of your *issue*, suggested solution and other information

Can't download facebook video

**Comment by halpz** [comment]
can you point me to the duplicate question please, the issue still remains
