### ISSUE TITLE
Site support request: tlc.de

### ISSUE THREAD

**Issue by OlliC** [rg3/youtube-dl#16724]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.06.11*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2018.06.11**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [X] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.tlc.de/programme/der-wunderheiler/video/die-gabe/DCB459460001100']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.06.11
[debug] Python version 3.6.5 (CPython) - Linux-4.16.13-2-ARCH-x86_64-with-arch-Arch-Linux
[debug] exe versions: ffmpeg 4.0, ffprobe 4.0, rtmpdump 2.4
[debug] Proxy map: {}
[generic] DCB459460001100: Requesting header
WARNING: Falling back on generic information extractor.
[generic] DCB459460001100: Downloading webpage
[generic] DCB459460001100: Extracting information
ERROR: Unsupported URL: https://www.tlc.de/programme/der-wunderheiler/video/die-gabe/DCB459460001100
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 500, in extract
    ie_result = self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/generic.py", line 3263, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.tlc.de/programme/der-wunderheiler/video/die-gabe/DCB459460001100

```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.tlc.de/programme/der-wunderheiler/video/die-gabe/DCB459460001100
- Single video: https://www.tlc.de/programme/mein-leben-mit-300-kg/video/amber/DCB369150001100
- Single video: https://www.tlc.de/programme/alle-meine-frauen/video/hochzeitswahnsinn-teil-1/DCB432260018100

---

### Description of your *issue*, suggested solution and other information

Hi, could please add support for 'https://www.tlc.de'. It was supported once in 2014. See issue #2748.

**Comment by OlliC** [comment]
Thank you!
