### ISSUE TITLE
ERROR: Did not get any data blocks (for youtube video with id: 7KHWNRVdnlQ)

### ISSUE THREAD

**Issue by olspookishmagus** [rg3/youtube-dl#16721]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.06.11*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.06.11**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--write-sub', u'--sub-lang', u'en', u'--convert-subs', u'srt', u'--yes-playlist', u'--output', u'%(uploader)s/%(title)s [%(extractor)s, %(id)s].%(ext)s', u'-f', u'22,136+140,18', u'-v', u'7KHWNRVdnlQ']
[debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8
[debug] youtube-dl version 2018.06.11
[debug] Python version 2.7.15 (CPython) - Linux-4.14.0-3-amd64-x86_64-with-debian-buster-sid
[debug] exe versions: avconv 3.4.2-2, avprobe 3.4.2-2, ffmpeg 3.4.2-2, ffprobe 3.4.2-2, phantomjs ., rtmpdump 2.4
[debug] Proxy map: {}
[youtube] 7KHWNRVdnlQ: Downloading webpage
[youtube] 7KHWNRVdnlQ: Downloading video info webpage
[info] 7KHWNRVdnlQ: downloading video in 3 formats
[info] Writing video subtitles to: Mathispower4u/Cartesian and Polar Equation of a Circle from a Graph - Center (0,0) [youtube, 7KHWNRVdnlQ].en.vtt
[debug] Invoking downloader on u'https://r5---sn-vuxbavcx-5uis.googlevideo.com/videoplayback?mn=sn-vuxbavcx-5uis%2Csn-4g5ednsk&mt=1528867165&sparams=dur%2Cei%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&id=o-AEHZkoqi5WYPIgqmHoPvamHqwU6Ck1VMCAkpHCI5qT4h&signature=3E17BD13B9C182246B4F74ACEFA3519CF20CCF3B.13918B9973385C246FA4E5F10A7B482DA5BB4F6A&key=yt6&mime=video%2Fmp4&ms=au%2Crdu&mv=m&pl=16&ipbits=0&initcwndbps=536250&mm=31%2C29&ip=79.130.225.170&ratebypass=yes&expire=1528888839&lmt=1528401774150401&requiressl=yes&c=WEB&ei=pqkgW-XzOIjO1gLy4IaYBQ&itag=22&source=youtube&fvip=1&dur=213.368'
[download] Destination: Mathispower4u/Cartesian and Polar Equation of a Circle from a Graph - Center (0,0) [youtube, 7KHWNRVdnlQ].mp4

[download]   0.0% of 5.66MiB at 524.42KiB/s ETA 00:11
[download]   0.1% of 5.66MiB at 191.85KiB/s ETA 00:30
[download]   0.1% of 5.66MiB at 429.21KiB/s ETA 00:13
[download]   0.3% of 5.66MiB at 864.80KiB/s ETA 00:06
[download]   0.5% of 5.66MiB at 723.12KiB/s ETA 00:07
[download]   1.1% of 5.66MiB at 932.10KiB/s ETA 00:06
[download]   1.7% of 5.66MiB at 308.43KiB/s ETA 00:18[download] Got server HTTP error: Downloaded 101344 bytes, expected 5933681 bytes. Retrying (attempt 1 of 10)...


ERROR: Did not get any data blocks
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 341, in real_download
    return download()
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 319, in download
    retry(err)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 224, in retry
    raise RetryDownload(e)
RetryDownload

```

### Description of your *issue*, suggested solution and other information

YouTube video with id: 7KHWNRVdnlQ cannot be downloaded using the latest (as of today) youtube-dl.

**Comment by dstftw** [comment]
Youtube server side error. 22 is not available.

**Comment by olspookishmagus** [comment]
```
~$ youtube-dl -v -F 7KHWNRVdnlQ
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-F', u'7KHWNRVdnlQ']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.06.14
[debug] Python version 2.7.15 (CPython) - Linux-4.16.0-2-amd64-x86_64-with-debian-buster-sid
[debug] exe versions: avconv 3.4.2-2, avprobe 3.4.2-2, ffmpeg 3.4.2-2, ffprobe 3.4.2-2, phantomjs ., rtmpdump 2.4
[debug] Proxy map: {}
[youtube] 7KHWNRVdnlQ: Downloading webpage
[youtube] 7KHWNRVdnlQ: Downloading video info webpage
[info] Available formats for 7KHWNRVdnlQ:
format code  extension  resolution note
249          webm       audio only DASH audio   49k , opus @ 50k, 1.16MiB
250          webm       audio only DASH audio   60k , opus @ 70k, 1.43MiB
171          webm       audio only DASH audio   95k , vorbis@128k, 2.22MiB
251          webm       audio only DASH audio  109k , opus @160k, 2.58MiB
140          m4a        audio only DASH audio  127k , m4a_dash container, mp4a.40.2@128k, 3.23MiB
160          mp4        248x144    144p   26k , avc1.4d400c, 30fps, video only, 407.63KiB
278          webm       248x144    144p   48k , webm container, vp9, 30fps, video only, 778.67KiB
133          mp4        412x240    240p   52k , avc1.4d400d, 30fps, video only, 698.19KiB
134          mp4        620x360    360p   82k , avc1.4d401e, 30fps, video only, 1008.37KiB
242          webm       412x240    240p   85k , vp9, 30fps, video only, 1.06MiB
135          mp4        826x480    480p  140k , avc1.4d401f, 30fps, video only, 1.52MiB
243          webm       620x360    360p  151k , vp9, 30fps, video only, 1.72MiB
136          mp4        1238x720   720p  231k , avc1.4d401f, 30fps, video only, 2.45MiB
244          webm       826x480    480p  248k , vp9, 30fps, video only, 2.55MiB
247          webm       1238x720   720p  483k , vp9, 30fps, video only, 4.11MiB
17           3gp        176x144    small , mp4v.20.3, mp4a.40.2@ 24k, 1.14MiB
36           3gp        320x186    small , mp4v.20.3, mp4a.40.2, 3.15MiB
43           webm       640x360    medium , vp8.0, vorbis@128k, 5.08MiB
18           mp4        620x360    medium , avc1.42001E, mp4a.40.2@ 96k, 7.05MiB
22           mp4        1238x720   hd720 , avc1.64001F, mp4a.40.2@192k (best)
```

**Comment by olspookishmagus** [comment]
```
$ youtube-dl -v --write-sub --sub-lang en --convert-subs srt --yes-playlist --output "%(uploader)s/%(title)s [%(extractor)s, %(id)s].%(ext)s" -f '136+140' 7KHWNRVdnlQ
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--write-sub', u'--sub-lang', u'en', u'--convert-subs', u'srt', u'--yes-playlist', u'--output', u'%(uploader)s/%(title)s [%(extractor)s, %(id)s].%(ext)s', u'-f', u'136+140', u'7KHWNRVdnlQ']
[debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8
[debug] youtube-dl version 2018.06.14
[debug] Python version 2.7.15 (CPython) - Linux-4.16.0-2-amd64-x86_64-with-debian-buster-sid
[debug] exe versions: avconv 3.4.2-2, avprobe 3.4.2-2, ffmpeg 3.4.2-2, ffprobe 3.4.2-2, phantomjs ., rtmpdump 2.4
[debug] Proxy map: {}
[youtube] 7KHWNRVdnlQ: Downloading webpage
[youtube] 7KHWNRVdnlQ: Downloading video info webpage
[info] Writing video subtitles to: Mathispower4u/Cartesian and Polar Equation of a Circle from a Graph - Center (0,0) [youtube, 7KHWNRVdnlQ].en.vtt
[debug] Invoking downloader on u'https://r5---sn-vuxbavcx-5uis.googlevideo.com/videoplayback?ei=LQciW_nWKY7kgQelm6kI&dur=213.266&sparams=aitags%2Cclen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Crequiressl%2Csource%2Cexpire&requiressl=yes&expire=1528978317&pcm2cms=yes&mime=video%2Fmp4&c=WEB&itag=136&key=yt6&ipbits=0&clen=2566088&source=youtube&fvip=1&lmt=1528401738362390&id=o-AK8A8CfqnDCNnov7n63D_d842pKpP9ywvN7hkbI98D1w&ms=au%2Crdu&mt=1528956612&mv=m&gir=yes&pl=16&initcwndbps=552500&signature=5319CB620C2184A1E805BD4CC56D298F312E1747.9C1C311F41773257BAB396077C6A0DF8E722A42D&keepalive=yes&ip=79.130.225.170&mn=sn-vuxbavcx-5uis%2Csn-4g5e6n7k&mm=31%2C29&aitags=133%2C134%2C135%2C136%2C160%2C242%2C243%2C244%2C247%2C278&ratebypass=yes'
[download] Destination: Mathispower4u/Cartesian and Polar Equation of a Circle from a Graph - Center (0,0) [youtube, 7KHWNRVdnlQ].f136.mp4

[download]   0.0% of 2.45MiB at 54.72KiB/s ETA 00:45
[download]   0.1% of 2.45MiB at 160.83KiB/s ETA 00:15
[download]   0.3% of 2.45MiB at 369.22KiB/s ETA 00:06
[download]   0.6% of 2.45MiB at 778.54KiB/s ETA 00:03
[download]   1.2% of 2.45MiB at 393.79KiB/s ETA 00:06
[download]   2.5% of 2.45MiB at 352.32KiB/s ETA 00:06
[download]   5.1% of 2.45MiB at 276.79KiB/s ETA 00:08
[download]  10.2% of 2.45MiB at 179.74KiB/s ETA 00:12
[download]  15.5% of 2.45MiB at 144.96KiB/s ETA 00:14
[download]  19.7% of 2.45MiB at 148.02KiB/s ETA 00:13
[download]  26.1% of 2.45MiB at 148.82KiB/s ETA 00:12
[download]  32.2% of 2.45MiB at 152.65KiB/s ETA 00:11
[download]  39.0% of 2.45MiB at 159.76KiB/s ETA 00:09
[download]  47.2% of 2.45MiB at 168.43KiB/s ETA 00:07
[download]  56.3% of 2.45MiB at 173.60KiB/s ETA 00:06
[download]  64.5% of 2.45MiB at 177.61KiB/s ETA 00:05
[download]  72.9% of 2.45MiB at 181.11KiB/s ETA 00:03
[download]  81.4% of 2.45MiB at 189.30KiB/s ETA 00:02
[download]  93.7% of 2.45MiB at 193.85KiB/s ETA 00:00
[download] 100.0% of 2.45MiB at 195.17KiB/s ETA 00:00
[download] 100% of 2.45MiB in 00:13
[debug] Invoking downloader on u'https://r5---sn-vuxbavcx-5uis.googlevideo.com/videoplayback?ei=LQciW_nWKY7kgQelm6kI&dur=213.368&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Crequiressl%2Csource%2Cexpire&requiressl=yes&expire=1528978317&pcm2cms=yes&mime=audio%2Fmp4&c=WEB&itag=140&ipbits=0&clen=3389499&source=youtube&fvip=1&lmt=1528401737051328&id=o-AK8A8CfqnDCNnov7n63D_d842pKpP9ywvN7hkbI98D1w&ms=au%2Crdu&mt=1528956612&mv=m&gir=yes&pl=16&initcwndbps=552500&signature=2CE087A827C9FD6DCFFFB86C284242C3F8444571.6897D5F59C57F52580E4E1FDE2E20AF079D2623E&keepalive=yes&ip=79.130.225.170&key=yt6&mm=31%2C29&mn=sn-vuxbavcx-5uis%2Csn-4g5e6n7k&ratebypass=yes'
[download] Destination: Mathispower4u/Cartesian and Polar Equation of a Circle from a Graph - Center (0,0) [youtube, 7KHWNRVdnlQ].f140.m4a

[download]   0.0% of 3.23MiB at 55.04KiB/s ETA 01:00
[download]   0.1% of 3.23MiB at 164.01KiB/s ETA 00:20
[download]   0.2% of 3.23MiB at 379.98KiB/s ETA 00:08
[download]   0.5% of 3.23MiB at 808.62KiB/s ETA 00:04
[download]   0.9% of 3.23MiB at 542.89KiB/s ETA 00:06
[download]   1.9% of 3.23MiB at 489.21KiB/s ETA 00:06
[download]   3.8% of 3.23MiB at 409.18KiB/s ETA 00:07
[download]   7.7% of 3.23MiB at 307.31KiB/s ETA 00:09
[download]  15.1% of 3.23MiB at 230.94KiB/s ETA 00:12
[download]  20.7% of 3.23MiB at 227.59KiB/s ETA 00:11
[download]  27.3% of 3.23MiB at 222.09KiB/s ETA 00:10
[download]  33.5% of 3.23MiB at 221.70KiB/s ETA 00:09
[download]  40.2% of 3.23MiB at 222.87KiB/s ETA 00:08
[download]  47.1% of 3.23MiB at 225.04KiB/s ETA 00:07
[download]  54.3% of 3.23MiB at 226.73KiB/s ETA 00:06
[download]  61.5% of 3.23MiB at 227.57KiB/s ETA 00:05
[download]  68.6% of 3.23MiB at 229.12KiB/s ETA 00:04
[download]  76.0% of 3.23MiB at 230.64KiB/s ETA 00:03
[download]  83.4% of 3.23MiB at 233.12KiB/s ETA 00:02
[download]  91.3% of 3.23MiB at 235.15KiB/s ETA 00:01
[download]  99.1% of 3.23MiB at 233.86KiB/s ETA 00:00
[download] 100.0% of 3.23MiB at 234.94KiB/s ETA 00:00
[download] 100% of 3.23MiB in 00:14
[ffmpeg] Merging formats into "Mathispower4u/Cartesian and Polar Equation of a Circle from a Graph - Center (0,0) [youtube, 7KHWNRVdnlQ].mp4"
WARNING: Your copy of avconv is outdated, update avconv to version 10-0 or newer if you encounter any errors.
[debug] ffmpeg command line: avconv -y -i 'file:Mathispower4u/Cartesian and Polar Equation of a Circle from a Graph - Center (0,0) [youtube, 7KHWNRVdnlQ].f136.mp4' -i 'file:Mathispower4u/Cartesian and Polar Equation of a Circle from a Graph - Center (0,0) [youtube, 7KHWNRVdnlQ].f140.m4a' -c copy -map '0:v:0' -map '1:a:0' 'file:Mathispower4u/Cartesian and Polar Equation of a Circle from a Graph - Center (0,0) [youtube, 7KHWNRVdnlQ].temp.mp4'
Deleting original file Mathispower4u/Cartesian and Polar Equation of a Circle from a Graph - Center (0,0) [youtube, 7KHWNRVdnlQ].f136.mp4 (pass -k to keep)
Deleting original file Mathispower4u/Cartesian and Polar Equation of a Circle from a Graph - Center (0,0) [youtube, 7KHWNRVdnlQ].f140.m4a (pass -k to keep)
[ffmpeg] Converting subtitles
WARNING: Your copy of avconv is outdated, update avconv to version 10-0 or newer if you encounter any errors.
[debug] ffmpeg command line: avconv -y -i 'file:Mathispower4u/Cartesian and Polar Equation of a Circle from a Graph - Center (0,0) [youtube, 7KHWNRVdnlQ].en.vtt' -f srt 'file:Mathispower4u/Cartesian and Polar Equation of a Circle from a Graph - Center (0,0) [youtube, 7KHWNRVdnlQ].en.srt'
Deleting original file Mathispower4u/Cartesian and Polar Equation of a Circle from a Graph - Center (0,0) [youtube, 7KHWNRVdnlQ].en.vtt (pass -k to keep)
```
