### ISSUE TITLE
ORF Downloader stopped working

### ISSUE THREAD

**Issue by annomatik** [rg3/youtube-dl#16736]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.06.14*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.06.14**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
$ youtube-dl -v --nocheck-certificate https://tvthek.orf.at/profile/Schnell-ermittelt/13886955

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--no-check-certificate', 'https://tvthek.orf.at/profile/Schnell-ermittelt/13886955']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.06.14
[debug] Python version 3.2.3 (CPython) - Linux-4.1.19+-armv6l-with-debian-7.11
[debug] exe versions: avconv 9.14-6, avprobe 9.14-6, ffprobe 4.0-static, rtmpdump 2.4
[debug] Proxy map: {}
[orf:tvthek] 13886955: Downloading webpage
[orf:tvthek] 14314583: Checking hls-QXB-Adaptiv video format URL
[orf:tvthek] 14314583: Checking hds-Q1A-Niedrig video format URL
[orf:tvthek] 14314583: Checking hds-Q4A-Mittel video format URL
[orf:tvthek] 14314583: Checking hds-Q6A-Hoch video format URL
[orf:tvthek] 14314583: Checking hds-Q8C-Sehr hoch video format URL
[orf:tvthek] 14314583: Checking hls-Q1A-Niedrig video format URL
[orf:tvthek] 14314583: Checking hls-Q4A-Mittel video format URL
[orf:tvthek] 14314583: Checking hls-Q6A-Hoch video format URL
[orf:tvthek] 14314583: Checking hls-Q8C-Sehr hoch video format URL
[orf:tvthek] 14314583: Checking progressive-Q1A-Niedrig video format URL
[orf:tvthek] 14314583: progressive-Q1A-Niedrig video format URL is invalid, skipping
[orf:tvthek] 14314583: Checking progressive-Q4A-Mittel video format URL
[orf:tvthek] 14314583: progressive-Q4A-Mittel video format URL is invalid, skipping
[orf:tvthek] 14314583: Checking progressive-Q6A-Hoch video format URL
[orf:tvthek] 14314583: progressive-Q6A-Hoch video format URL is invalid, skipping
[orf:tvthek] 14314583: Checking progressive-Q8C-Sehr hoch video format URL
[orf:tvthek] 14314583: progressive-Q8C-Sehr hoch video format URL is invalid, skipping
[download] Downloading playlist: 13886955
[orf:tvthek] playlist 13886955: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
WARNING: Your copy of avconv is outdated and unable to properly mux separate video and audio files, youtube-dl will download single file media. Update avconv to version 10-0 or newer to fix this.
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'rtmp://apasfw.apa.at/cms-worldwide/mp4:2018-06-11_2015_sd_01_Schnell-ermitte_____13979501__o__1339304012__s14314583_3__BCK1HD_20153313P_21033213P_Q8C.mp4'
[download] Destination: Schnell ermittelt - Alan Richter-14314583.mp4
[debug] rtmpdump command line: rtmpdump --verbose -r 'rtmp://apasfw.apa.at/cms-worldwide/mp4:2018-06-11_2015_sd_01_Schnell-ermitte_____13979501__o__1339304012__s14314583_3__BCK1HD_20153313P_21033213P_Q8C.mp4' -o 'Schnell ermittelt - Alan Richter-14314583.mp4.part' --resume --skip 1
Traceback (most recent call last):
  File "/usr/lib/python3.2/runpy.py", line 161, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python3.2/runpy.py", line 74, in _run_code
    exec(code, run_globals)
  File "/usr/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/bin/youtube-dl/youtube_dl/__init__.py", line 472, in main
  File "/usr/bin/youtube-dl/youtube_dl/__init__.py", line 462, in _real_main
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2001, in download
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 803, in extract_info
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1002, in process_ie_result
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 857, in process_ie_result
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1635, in process_video_result
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1908, in process_info
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1847, in dl
  File "/usr/bin/youtube-dl/youtube_dl/downloader/common.py", line 364, in download
  File "/usr/bin/youtube-dl/youtube_dl/downloader/rtmp.py", line 176, in real_download
  File "/usr/bin/youtube-dl/youtube_dl/downloader/rtmp.py", line 95, in run_rtmpdump
  File "/usr/bin/youtube-dl/youtube_dl/downloader/rtmp.py", line 89, in dl
UnboundLocalError: local variable 'cursor_in_new_line' referenced before assignment

```

---

### Description of your *issue*, suggested solution and other information

Hi! A couple of days ago, downloads for ORF stopped working for me, they worked fine before. Youtube-DL tells me, that rtmpdump exited with status 1, I have also pasted the debug log above.

Youtube-DL works fine for other sites, also, the URL works fine when I open it in a browser.

More example URLs (all of them currently not working):

- https://tvthek.orf.at/profile/Schnell-ermittelt/13886955
- https://tvthek.orf.at/profile/Tatort/2713749
- https://tvthek.orf.at/profile/Universum/35429
- https://tvthek.orf.at/profile/Universum-History/6000179
 
Thanks for your time!

**Comment by dstftw** [comment]
Update avconv as clearly stated in warning message or remove `-v` to download with rtmpdump.

**Comment by annomatik** [comment]
avconv does not do the downloading. All that -v does is, to my understanding, make the output more verbose. If I remove the "-v", it does not work either:

```
$ youtube-dl --no-check-certificate https://tvthek.orf.at/profile/Schnell-ermittelt/13886955
[orf:tvthek] 13886955: Downloading webpage
[orf:tvthek] 14314583: Checking hls-QXB-Adaptiv video format URL
[orf:tvthek] 14314583: Checking hds-Q1A-Niedrig video format URL
[orf:tvthek] 14314583: Checking hds-Q4A-Mittel video format URL
[orf:tvthek] 14314583: Checking hds-Q6A-Hoch video format URL
[orf:tvthek] 14314583: Checking hds-Q8C-Sehr hoch video format URL
[orf:tvthek] 14314583: Checking hls-Q1A-Niedrig video format URL
[orf:tvthek] 14314583: Checking hls-Q4A-Mittel video format URL
[orf:tvthek] 14314583: Checking hls-Q6A-Hoch video format URL
[orf:tvthek] 14314583: Checking hls-Q8C-Sehr hoch video format URL
[orf:tvthek] 14314583: Checking progressive-Q1A-Niedrig video format URL
[orf:tvthek] 14314583: progressive-Q1A-Niedrig video format URL is invalid, skipping
[orf:tvthek] 14314583: Checking progressive-Q4A-Mittel video format URL
[orf:tvthek] 14314583: progressive-Q4A-Mittel video format URL is invalid, skipping
[orf:tvthek] 14314583: Checking progressive-Q6A-Hoch video format URL
[orf:tvthek] 14314583: progressive-Q6A-Hoch video format URL is invalid, skipping
[orf:tvthek] 14314583: Checking progressive-Q8C-Sehr hoch video format URL
[orf:tvthek] 14314583: progressive-Q8C-Sehr hoch video format URL is invalid, skipping
[download] Downloading playlist: 13886955
[orf:tvthek] playlist 13886955: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
WARNING: Your copy of avconv is outdated and unable to properly mux separate video and audio files, youtube-dl will download single file media. Update avconv to version 10-0 or newer to fix this.
[download] Destination: Schnell ermittelt - Alan Richter-14314583.mp4
[rtmpdump] Downloaded 0 bytes


ERROR: rtmpdump exited with code 1
$
```

If you can tell me, how I can update avconv (without buying a new hardware, I'm running a RPi 1 here), I'm all ears, but I don't think it will help me:

```
$ sudo apt-get install libav-tools
Reading package lists... Done
Building dependency tree
Reading state information... Done
libav-tools is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 113 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue [Y/n]? y
Setting up python-setuptools (0.6.24-1) ...
Traceback (most recent call last):
  File "/usr/bin/pycompile", line 35, in <module>
    from debpython.version import SUPPORTED, debsorted, vrepr, \
  File "/usr/share/python/debpython/version.py", line 24, in <module>
    from ConfigParser import SafeConfigParser
ImportError: No module named ConfigParser
dpkg: error processing python-setuptools (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 python-setuptools
E: Sub-process /usr/bin/dpkg returned an error code (1)
$
```

Again: It worked about a week ago, with the current avconv, with the current rtmpdump, even with this warning, which is a warning, not an error.

**Comment by dstftw** [comment]
I guess we should start banning for
>It worked about a week ago

Everything **changes constantly**.
Also update python. Yours is extremely outdated and does not support TLS 1.1 that is required by their direct HTTP links now.
