### ISSUE TITLE
[SBS] sbs ondemand: some videos not working

### ISSUE THREAD

**Issue by deant** [rg3/youtube-dl#16744]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.06.14*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.06.14**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)

---

I just tried to download 22 videos from https://sbs.com.au/ondemand
19 worked perfectly.  3 repeatedly gave errors.
I have verified that I can get those 3 to play inside my browser (Google Chrome) although oddly I had to refresh the browser page a couple of times on each video before it played successfully.
Note that these videos are *probably* region-locked to Australian users only, though I haven't confirmed that.
The 3 --verbose mode logs are below:

(1)
```
youtube-dl.exe -o "C:\DOWNLOADS\John McCain Maverick.%%(ext)s" --restrict-filenames --ignore-errors --continue --retries 10 --skip-unavailable-fragments --fragment-retries 10 --convert-subs srt --no-overwrites --recode-video mp4 --postprocessor-args "-codec copy" "https://www.sbs.com.au/ondemand/video/1242879043727/john-mccain-maverick" --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-o', 'C:\\DOWNLOADS\\John McCain Maverick.%%(ext)s', '--restrict-filenames', '--ignore-errors', '--continue', '--retries', '10', '--skip-unavailable-fragments', '--fragment-retries', '10', '--convert-subs', 'srt', '--no-overwrites', '--recode-video', 'mp4', '--postprocessor-args', '-codec copy', 'https://www.sbs.com.au/ondemand/video/1242879043727/john-mccain-maverick', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.06.14
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg N-91288-g29cddc99cd, ffprobe N-91288-g29cddc99cd
[debug] Proxy map: {}
[SBS] 1242879043727: Downloading JSON metadata
[ThePlatform] 60RwkWWN2GVN: Downloading SMIL data
[ThePlatform] 60RwkWWN2GVN: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6bcc20cp\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6bcc20cp\build\youtube_dl\extractor\common.py", line 500, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6bcc20cp\build\youtube_dl\extractor\theplatform.py", line 296, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6bcc20cp\build\youtube_dl\extractor\common.py", line 1190, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

(2)
```
youtube-dl.exe -o "C:\DOWNLOADS\The Queen's Favorite Animals.%%(ext)s" --restrict-filenames --ignore-errors --continue --retries 10 --skip-unavailable-fragments --fragment-retries 10 --convert-subs srt --no-overwrites --recode-video mp4 --postprocessor-args "-codec copy" "https://www.sbs.com.au/ondemand/video/1254957123965/the-queens-favourite-animals" --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-o', "C:\\DOWNLOADS\\The Queen's Favorite Animals.%%(ext)s", '--restrict-filenames', '--ignore-errors', '--continue', '--retries', '10', '--skip-unavailable-fragments', '--fragment-retries', '10', '--convert-subs', 'srt', '--no-overwrites', '--recode-video', 'mp4', '--postprocessor-args', '-codec copy', 'https://www.sbs.com.au/ondemand/video/1254957123965/the-queens-favourite-animals', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.06.14
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg N-91288-g29cddc99cd, ffprobe N-91288-g29cddc99cd
[debug] Proxy map: {}
[SBS] 1254957123965: Downloading JSON metadata
[ThePlatform] lHPeY8Z_w7Fy: Downloading SMIL data
[ThePlatform] lHPeY8Z_w7Fy: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6bcc20cp\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6bcc20cp\build\youtube_dl\extractor\common.py", line 500, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6bcc20cp\build\youtube_dl\extractor\theplatform.py", line 296, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6bcc20cp\build\youtube_dl\extractor\common.py", line 1190, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

(3)
```
youtube-dl.exe -o "C:\DOWNLOADS\Australia With Simon Reeve Ep 1.%%(ext)s" --restrict-filenames --ignore-errors --continue --retries 10 --skip-unavailable-fragments --fragment-retries 10 --convert-subs srt --no-overwrites --recode-video mp4 --postprocessor-args "-codec copy" "https://www.sbs.com.au/ondemand/video/36767811596/australia-with-simon-reeve" --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-o', 'C:\\DOWNLOADS\\Australia With Simon Reeve Ep 1.%%(ext)s', '--restrict-filenames', '--ignore-errors', '--continue', '--retries', '10', '--skip-unavailable-fragments', '--fragment-retries', '10', '--convert-subs', 'srt', '--no-overwrites', '--recode-video', 'mp4', '--postprocessor-args', '-codec copy', 'https://www.sbs.com.au/ondemand/video/36767811596/australia-with-simon-reeve', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.06.14
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg N-91288-g29cddc99cd, ffprobe N-91288-g29cddc99cd
[debug] Proxy map: {}
[SBS] 36767811596: Downloading JSON metadata
[ThePlatform] DulgNCe6ndgK: Downloading SMIL data
[ThePlatform] DulgNCe6ndgK: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6bcc20cp\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6bcc20cp\build\youtube_dl\extractor\common.py", line 500, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6bcc20cp\build\youtube_dl\extractor\theplatform.py", line 296, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6bcc20cp\build\youtube_dl\extractor\common.py", line 1190, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by deant** [comment]
R.e. the "account-needed" thing:  You need an account to play the videos in-browser, but you DON'T need one either to simply search for video titles/URLs on their website, nor to download videos via youtube-dl (unless something has just changed, and that's the problem with the videos above...?)
Also, accounts are free.

**Comment by deant** [comment]
Well, I tried logging in and then using youtube-dl with cookies exported from my browser.  Made no difference.  Also tried the -u and -p parameters (username/password).  Also made no difference.

**Comment by philacid** [comment]
Find the real mp4 file-link being played through browser

**Comment by deant** [comment]
Philacid, it's not an mp4 file as such, it's a stream, delivered in segments.  Using the Network tab of Chrome's developer tools, I see that for the first video above, it gets its initial chunk of data from:

https://sbsvodns-vh.akamaihd.net/i/svod/SBS/managed/2018/06/06/2018-06-06_625550_,1000,1500,512,128,K.mp4.csmil/index_1_av.m3u8?set-akamai-hls-revision=5&id=AgDL1iFHlmWhBWpULVtIGTMRaiOcmjpCGuRzfFXBbF1g+t9aO5jx1Sh2LaI08dSkJPIhmqzy1D8I6Q%3d%3d&hdntl=exp=1529783786~acl=%2fi%2fsvod%2fSBS%2fmanaged%2f2018%2f06%2f06%2f2018-06-06_625550_*~data=hdntl~hmac=96495c6649c53acfb3543e43a97a57facedfc3b197186f6a4a8fff5555064bd2

and then further segments follow as the video plays:

https://sbsvodns-vh.akamaihd.net/i/svod/SBS/managed/2018/06/06/2018-06-06_625550_,1000,1500,512,128,K.mp4.csmil/segment2_1_av.ts?set-akamai-hls-revision=5&id=AgDL1iFHlmWhBWpULVtIGTMRaiOcmjpCGuRzfFXBbF1g+t9aO5jx1Sh2LaI08dSkJPIhmqzy1D8I6Q%3d%3d&hdntl=exp=1529783786~acl=/i/svod/SBS/managed/2018/06/06/2018-06-06_625550_*~data=hdntl~hmac=96495c6649c53acfb3543e43a97a57facedfc3b197186f6a4a8fff5555064bd2
https://sbsvodns-vh.akamaihd.net/i/svod/SBS/managed/2018/06/06/2018-06-06_625550_,1000,1500,512,128,K.mp4.csmil/segment3_1_av.ts?set-akamai-hls-revision=5&id=AgDL1iFHlmWhBWpULVtIGTMRaiOcmjpCGuRzfFXBbF1g+t9aO5jx1Sh2LaI08dSkJPIhmqzy1D8I6Q%3d%3d&hdntl=exp=1529783786~acl=/i/svod/SBS/managed/2018/06/06/2018-06-06_625550_*~data=hdntl~hmac=96495c6649c53acfb3543e43a97a57facedfc3b197186f6a4a8fff5555064bd2
https://sbsvodns-vh.akamaihd.net/i/svod/SBS/managed/2018/06/06/2018-06-06_625550_,1000,1500,512,128,K.mp4.csmil/segment4_1_av.ts?set-akamai-hls-revision=5&id=AgDL1iFHlmWhBWpULVtIGTMRaiOcmjpCGuRzfFXBbF1g+t9aO5jx1Sh2LaI08dSkJPIhmqzy1D8I6Q%3d%3d&hdntl=exp=1529783786~acl=/i/svod/SBS/managed/2018/06/06/2018-06-06_625550_*~data=hdntl~hmac=96495c6649c53acfb3543e43a97a57facedfc3b197186f6a4a8fff5555064bd2

... etc.

(Note that the above 3 URLs are identical except for the segment2_1_av.ts, segment3_1_av.ts, segment4_1_av.ts, ... parts)


Does that help?
Do you need the info for the other two videos also?

**Comment by philacid** [comment]
You are in the right area hypothetically.  Perhaps playing around with the various links seen in the network analysis might work hypothetically. Not that I have done exactly that myself. Certainly I didn't do it with Firefox network analysis using the built in filters to show only media types in the network stream, and I didn't then use youtube-dl with what looked like the most likely file-link served on the akamaihd server.  Saying any more could trigger an unwanted change to this hypothetical hole.

**Comment by philacid** [comment]
future updates to youtube-dl might allow passing username and password as I understand works already with other sites. I don't use OBS Studio when all else fails.

**Comment by TommoCrabb** [comment]
@deant, I came here because I was having a similar issue to you. I tried to download about 20 videos; most of them worked, but two or three failed with the same sort of output you posted. After reading this thread, I signed up for an account with SBS. I then retried downloading the videos that had failed earlier, only this time, I used the -u (username) and -p (password) flags with youtube-dl. This time, the downloads worked perfectly. If I had to guess, I'd say SBS has started requiring verification for certain videos. Maybe it's a gradual roll out?

Having said that, I tested the "John McCain, Maverick" link you posted above, and it downloaded for me just fine, even without the username and password flags. So, I dunno what the full story is.

**Comment by deant** [comment]
@TommoCrabb that's interesting, because I tried using the -u and -p options with youtube-dl, and it didn't help me.  So maybe it's a different issue, or maybe the SBS server is undergoing ongoing changes.  Alternatively, the way youtube-dl passes -u and -p options to the SBS server might have changed slightly, if there's been a new version release in the last 9 days... hard to say!

**Comment by TommoCrabb** [comment]
Okay, here's one that I couldn't download without using the username and password options.

[Stacey Dooley: Face to Face with Isis](https://www.sbs.com.au/ondemand/program/stacey-dooley-face-to-face-with-isis)

@deant, I assume that's what you meant?

**Comment by deant** [comment]
@TommoCrabb Actually I wasn't sure if the username parameter was my displayed username or my email, but if memory serves correctly I tried both, just to be safe.  I didn't try changing the other options, no; they didn't look like they had much to do with the error I was getting, and they're added by the frontend I usually use to invoke youtube-dl (a little paste-your-links floating box called YT-DL Dropper), which has until now always worked fine for me.

Interestingly, the same link you just posted, I also downloaded a few days ago, and it worked without any problems for me (and without any username/password parameters in the commandline options).

It may be this is just some kind of intermittent server problem affecting certain videos somehow, although it seems that the "effect" persists for 1-2 days at least once it happens (based on my experience with the the first 3 videos I posted).

Hopefully someone from youtube-dl will investigate while we have a non-working link to demonstrate to them...?

**Comment by philacid** [comment]
@deant Obtuse! Prize for stating the bleedin obvious even if you don't have the correct sense of obtuse; but I do understand what you meant to write.  
Hmm, now why would someone living in Australia not post the URI's of the actual streams served from a TV provider,  thus providing the exact means of defeating their file protection mechanism?

"I don't know OBS Studio" - now that's obtuse, like saying 'I don't know frickin google'.
Seems to me from reading the thread so far, the devs have got enough info to make things simple again for the entitled among us, shame they are volunteers or you could crack the whip a little.

For the rest of us with no developer training but can use a search engine to learn a tiny bit about media serving, none of the files from this particular provider are inaccessible to youtube-dl because after starting to play the file in the browser, the network traffic monitor in Firefox **very soon** reveals **only one link** that makes sense to pass to youtube-dl.

**Comment by deant** [comment]
@philacid Well, checking some online dictionaries, most give the meaning of obtuse as "dull".  But Oxford dictionary also allows "Difficult to understand, especially deliberately so".  What I was going for was that, more-or-less, although "deliberately unhelpful" would probably be closer, and AFAIK obtuse _is_ often used in exactly that sense, especially when you describe someone as "_being_ obtuse".  At least one person on English.stackexchange [agrees with me on that definition](https://english.stackexchange.com/questions/364438/whats-a-word-to-describe-a-person-being-deliberately-unclear-obfuscatory#comment849456_364452).

Hmm, well, *I* live in Australia, and I'm fairly sure saving video streams for personal viewing is not illegal here, any more than recording a TV show on VCR would be.  (Unless you then distribute the recording, of course).  In any case there's zero chance SBS would bother coming after you for it.  At worst they might cancel your free SBS user account, assuming there's any way they could connect your github username to it (and you could always just make another).  Or possibly you think they're trawling github issue trackers for suspicious URLs to see if they have cause to improve their servers' security mechanisms?  I assure you, they aren't.  Although it's been discontinued now (I believe because the author didn't want to maintain it anymore), for _years_ there was a program called SBSRipper, designed specifically for downloading SBS streaming content.  It had it's own website and everything, and SBS didn't care.  The well-known Australian internet forum Whirlpool maintains an ongoing, public, 9-year-old and much-used discussion thread specifically about how to download SBS OnDemand programs ([part 1](https://forums.whirlpool.net.au/forum-replies.cfm?t=1342590), [part 2](https://forums.whirlpool.net.au/forum-replies.cfm?t=2320227&p=1), [part 3](https://forums.whirlpool.net.au/forum-replies.cfm?t=2699206)), as well as [a page including some helpful technical information about the service](https://whirlpool.net.au/wiki/?tag=SBS%20Downloader).  Which all goes to say, I think you're being overly paranoid.  *Waaaay* overly.  (<sarcasm>Also, if someone _did_ want to come after you, I'm pretty sure that saying it's just what you "hypothetically didn't do" isn't a bulletproof legal defence strategy</sarcasm>).

I dunno why you think I'm obtuse if I don't know OBS Studio.  Just about everybody with a computer or smartphone searches the internet, so they know _frickin_ Google.  But not everyone does video recording or mixing on their computer - I don't, except to save some TV streams, and sometimes a YouTube or Vimeo video that I just use a browser add-on to get - so there's no reason to assume I'd have heard of some popular software package(s) for doing that.  I never heard of OBS Studio before, and the fact is I'll probably never have reason to use it.  And _your_ usage of "obtuse" was rude.

Oh, I *am* a professional software developer, just BTW.  (Not for youtube-dl, though, obviously).
I think I'm _not_ going to "crack the whip" on the youtube-dl bug team...  as you point out, they are volunteers, and for now at least I'm going to assume that they know best where their valuable and freely-donated time most needs to be spent, without my screaming "Fix my bug!", "Fix my bug!" at them ...especially since there's an easy workaround anyway.  But you know, you can go right ahead and do that yourself, if you're that-way inclined: it's a free country.
