### ISSUE TITLE
twitter video download not working

### ISSUE THREAD

**Issue by jeyca** [rg3/youtube-dl#16752]
Yes ok I admit, I am using an old version (2018.01.21) and therefore my issue should be rejected here.

**But please** check if this video

https://twitter.com/Erdrandbewohner/status/1007723717303128065

works with the latest version or fails there. I don't want to have to change the software setup on my system and set up and maintain a manual installation instead of the automatic package installation just for making up this issue here. However, I want to inform you that there might be an issue that yout can test with a current version.

My Error log has shown:

```
03128065
[twitter] 1007723717303128065: Downloading webpage
[twitter:card] 1007723717303128065: Downloading webpage
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
user@user:~$ cd movies/
user@user:~/movies$ youtube-dl https://twitter.com/Erdrandbewohner/status/1007723717303128065 --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://twitter.com/Erdrandbewohner/status/1007723717303128065', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.01.21
[debug] Python version 2.7.12 (CPython) - Linux-4.13.0-45-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.14-0ubuntu0.16.04.1, ffprobe 2.8.14-0ubuntu0.16.04.1
[debug] Proxy map: {}
[twitter] 1007723717303128065: Downloading webpage
[twitter:card] 1007723717303128065: Downloading webpage
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 438, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/twitter.py", line 229, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 1069, in _sort_formats
    raise ExtractorError('No video formats found')
```

**Comment by dstftw** [comment]
Works.
