### ISSUE TITLE
ORF stopped working

### ISSUE THREAD

**Issue by RavenRabbit** [rg3/youtube-dl#16753]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.06.14*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.06.14**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
% youtube-dl -v "https://tvthek.orf.at/profile/ZIB-1300/71280"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://tvthek.orf.at/profile/ZIB-1300/71280']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.06.14
[debug] Python version 3.5.3 (CPython) - Linux-4.9.0-6-amd64-x86_64-with-debian-9.4
[debug] exe versions: ffmpeg 3.2.10-1, ffprobe 3.2.10-1
[debug] Proxy map: {}
[orf:tvthek] 71280: Downloading webpage
[orf:tvthek] 14318288: Checking hls-QXB-Adaptiv video format URL
[orf:tvthek] 14318288: Checking hds-Q1A-Niedrig video format URL
[orf:tvthek] 14318288: Checking hds-Q4A-Mittel video format URL
[orf:tvthek] 14318288: Checking hds-Q6A-Hoch video format URL
[orf:tvthek] 14318288: Checking hds-Q8C-Sehr hoch video format URL
[orf:tvthek] 14318288: Checking hls-Q1A-Niedrig video format URL
[orf:tvthek] 14318288: Checking hls-Q4A-Mittel video format URL
[orf:tvthek] 14318288: Checking hls-Q6A-Hoch video format URL
[orf:tvthek] 14318288: Checking hls-Q8C-Sehr hoch video format URL
[orf:tvthek] 14318288: Checking progressive-Q1A-Niedrig video format URL
Traceback (most recent call last):
  File "/home/user/youtube-dl/bin/youtube-dl", line 11, in <module>
    sys.exit(main())
  File "/home/user/youtube-dl/lib/python3.5/site-packages/youtube_dl/__init__.py", line 472, in main
    _real_main(argv)
  File "/home/user/youtube-dl/lib/python3.5/site-packages/youtube_dl/__init__.py", line 462, in _real_main
    retcode = ydl.download(all_urls)
  File "/home/user/youtube-dl/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 2001, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/home/user/youtube-dl/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/home/user/youtube-dl/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 500, in extract
    ie_result = self._real_extract(url)
  File "/home/user/youtube-dl/lib/python3.5/site-packages/youtube_dl/extractor/orf.py", line 114, in _real_extract
    self._check_formats(formats, video_id)
  File "/home/user/youtube-dl/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 1270, in _check_formats
    formats)
  File "/home/user/youtube-dl/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 1269, in <lambda>
    item='%s video format' % f.get('format_id') if f.get('format_id') else 'video'),
  File "/home/user/youtube-dl/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 1288, in _is_valid_url
    self._request_webpage(url, video_id, 'Checking %s URL' % item, headers=headers)
  File "/home/user/youtube-dl/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 579, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/home/user/youtube-dl/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 2211, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/home/user/youtube-dl/lib/python3.5/site-packages/youtube_dl/utils.py", line 1101, in https_open
    req, **kwargs)
  File "/usr/lib/python3.5/urllib/request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 1261, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python3.5/ssl.py", line 385, in wrap_socket
    _context=self)
  File "/usr/lib/python3.5/ssl.py", line 760, in __init__
    self.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 996, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 646, in do_handshake
    match_hostname(self.getpeercert(), self.server_hostname)
  File "/usr/lib/python3.5/ssl.py", line 309, in match_hostname
    % (hostname, dnsnames[0]))
ssl.CertificateError: hostname 'apasfpd.apa.at' doesn't match '*.sf.apa.at'
...
<end of log>
```

---
### Description of your *issue*, suggested solution and other information

Downloads for the site ([tvthek.orf.at](https://tvthek.orf.at/)) stopped working recently with the message posted above. Other tools like [Mediathekviewer ](https://github.com/mediathekview/MediathekView) experience a similar [issue (in German)](https://github.com/mediathekview/MediathekView/issues/321)

**Comment by dstftw** [comment]
As clearly stated in the error message they have invalid SSL certificate for some formats' hosts. Either report to them of use `--no-check-certificate` if you don't care.
