### ISSUE TITLE
Some TED videos do not download

### ISSUE THREAD

**Issue by ZNemesis** [rg3/youtube-dl#16756]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.06.18**
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

```
C:\Users\ZNemesis\Downloads\youtube-dl>youtube-dl.exe --verbose https://www.ted.com/talks/tom_thum_the_orchestra_in_my_mouth
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.ted.com/talks/tom_thum_the_orchestra_in_my_mouth']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.06.18
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.16299
[debug] exe versions: ffmpeg 3.4.1, ffprobe 3.4.1
[debug] Proxy map: {}
[ted] tom_thum_the_orchestra_in_my_mouth: Downloading webpage
ERROR: An extractor error has occurred. (caused by KeyError('nativeDownloads',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpu1zifx01\build\youtube_dl\extractor\common.py", line 500, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpu1zifx01\build\youtube_dl\extractor\ted.py", line 131, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpu1zifx01\build\youtube_dl\extractor\ted.py", line 184, in _talk_info
KeyError: 'nativeDownloads'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpu1zifx01\build\youtube_dl\extractor\common.py", line 500, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpu1zifx01\build\youtube_dl\extractor\ted.py", line 131, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpu1zifx01\build\youtube_dl\extractor\ted.py", line 184, in _talk_info
KeyError: 'nativeDownloads'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpu1zifx01\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpu1zifx01\build\youtube_dl\extractor\common.py", line 513, in extract
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('nativeDownloads',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
---

### Description of your *issue*, suggested solution and other information

This particular video does not download https://www.ted.com/talks/tom_thum_the_orchestra_in_my_mouth but other TED videos do work, for example https://www.ted.com/talks/nicole_paris_and_ed_cage_a_beatboxing_lesson_from_a_father_daughter_duo

**Comment by rajalakshmi-v15** [comment]
Hi, @ZNemesis. May I know whether this issue is suitable for a beginner? If yes, I would like to work on it.

**Comment by timendum** [comment]
Hi @rajalakshmi-v15 
I think this is a great issue for a beginner, the error is quite clear from the description and it's repeatable.
