### ISSUE TITLE
failed to download cbslocal video

### ISSUE THREAD

**Issue by ginabythebay** [rg3/youtube-dl#16788]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.06.19*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2018.06.19**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'http://sanfrancisco.cbslocal.com/2016/06/17/source-oakland-cop-on-leave-for-having-girlfriend-help-with-police-reports/']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2018.06.19
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-81300-gce2217b
[debug] Proxy map: {}
[CBSLocal] source-oakland-cop-on-leave-for-having-girlfriend-help-with-police-reports: Downloading webpage
[CBSLocal] 3417601: Fetching server time
ERROR: An extractor error has occurred. (caused by KeyError('DVzl9QRzox3ZZsP9bNu5Li3X7obQOnqP',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp3niajf93\build\youtube_dl\extractor\common.py", line 501, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp3niajf93\build\youtube_dl\extractor\cbslocal.py", line 92, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp3niajf93\build\youtube_dl\extractor\anvato.py", line 276, in _extract_anvato_videos
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp3niajf93\build\youtube_dl\extractor\anvato.py", line 182, in _get_anvato_videos
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp3niajf93\build\youtube_dl\extractor\anvato.py", line 172, in _get_video_json
KeyError: 'DVzl9QRzox3ZZsP9bNu5Li3X7obQOnqP'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp3niajf93\build\youtube_dl\extractor\common.py", line 501, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp3niajf93\build\youtube_dl\extractor\cbslocal.py", line 92, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp3niajf93\build\youtube_dl\extractor\anvato.py", line 276, in _extract_anvato_videos
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp3niajf93\build\youtube_dl\extractor\anvato.py", line 182, in _get_anvato_videos
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp3niajf93\build\youtube_dl\extractor\anvato.py", line 172, in _get_video_json
KeyError: 'DVzl9QRzox3ZZsP9bNu5Li3X7obQOnqP'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp3niajf93\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp3niajf93\build\youtube_dl\extractor\common.py", line 514, in extract
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('DVzl9QRzox3ZZsP9bNu5Li3X7obQOnqP',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

...
<end of log>
```

### Description of your *issue*, suggested solution and other information

Tried to use youtube-dl for the first time, on http://sanfrancisco.cbslocal.com/2016/06/17/source-oakland-cop-on-leave-for-having-girlfriend-help-with-police-reports/, got the error above.

CBSLocal is listed as being supported.

**Comment by Tatsh** [comment]
For CBS Local (tested with newyork.cbslocal.com):

```python
_ANVACK_TABLE = {
# ...
    'DVzl9QRzox3ZZsP9bNu5Li3X7obQOnqP': '3hwbSuqqT690uxjNYBktSQpa5ZrpYYR0Iofx7NcJHyA',
# ...
}
```
