### ISSUE TITLE
ssl.CertificateError with URL used up to now without problems 

### ISSUE THREAD

**Issue by WBirkelbachB** [rg3/youtube-dl#16836]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.06.25*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2018.06.25**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

```
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. Alle Rechte vorbehalten.

D:\HerunterGel>youtube-dl -v "https://tvthek.orf.at/profile/Sommernachtsgala-201
8/13889111/Sommernachtsgala-2018/13980730"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://tvthek.orf.at/profile/Sommernachtsgal
a-2018/13889111/Sommernachtsgala-2018/13980730']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.06.25
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-80011-gaf3e944, ffprobe N-80011-gaf3e944
[debug] Proxy map: {}
[orf:tvthek] 13980730: Downloading webpage
[orf:tvthek] 14321593: Checking hls-QXB-Adaptiv video format URL
[orf:tvthek] 14321593: Checking hds-Q1A-Niedrig video format URL
[orf:tvthek] 14321593: Checking hds-Q4A-Mittel video format URL
[orf:tvthek] 14321593: Checking hds-Q6A-Hoch video format URL
[orf:tvthek] 14321593: Checking hds-Q8C-Sehr hoch video format URL
[orf:tvthek] 14321593: Checking hls-Q1A-Niedrig video format URL
[orf:tvthek] 14321593: Checking hls-Q4A-Mittel video format URL
[orf:tvthek] 14321593: Checking hls-Q6A-Hoch video format URL
[orf:tvthek] 14321593: Checking hls-Q8C-Sehr hoch video format URL
[orf:tvthek] 14321593: Checking progressive-Q1A-Niedrig video format URL
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkc931nsv\bu
ild\youtube_dl\__init__.py", line 472, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkc931nsv\bu
ild\youtube_dl\__init__.py", line 462, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkc931nsv\bu
ild\youtube_dl\YoutubeDL.py", line 2001, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkc931nsv\bu
ild\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkc931nsv\bu
ild\youtube_dl\extractor\common.py", line 501, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkc931nsv\bu
ild\youtube_dl\extractor\orf.py", line 114, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkc931nsv\bu
ild\youtube_dl\extractor\common.py", line 1361, in _check_formats
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkc931nsv\bu
ild\youtube_dl\extractor\common.py", line 1360, in <lambda>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkc931nsv\bu
ild\youtube_dl\extractor\common.py", line 1379, in _is_valid_url
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkc931nsv\bu
ild\youtube_dl\extractor\common.py", line 598, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkc931nsv\bu
ild\youtube_dl\YoutubeDL.py", line 2211, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkc931nsv\bu
ild\youtube_dl\utils.py", line 1101, in https_open
  File "C:\Python\Python34\lib\urllib\request.py", line 1183, in do_open
  File "C:\Python\Python34\lib\http\client.py", line 1137, in request
  File "C:\Python\Python34\lib\http\client.py", line 1182, in _send_request
  File "C:\Python\Python34\lib\http\client.py", line 1133, in endheaders
  File "C:\Python\Python34\lib\http\client.py", line 963, in _send_output
  File "C:\Python\Python34\lib\http\client.py", line 898, in send
  File "C:\Python\Python34\lib\http\client.py", line 1287, in connect
  File "C:\Python\Python34\lib\ssl.py", line 362, in wrap_socket
  File "C:\Python\Python34\lib\ssl.py", line 580, in __init__
  File "C:\Python\Python34\lib\ssl.py", line 815, in do_handshake
  File "C:\Python\Python34\lib\ssl.py", line 286, in match_hostname
ssl.CertificateError: hostname 'apasfpd.apa.at' doesn't match '*.sf.apa.at'

D:\HerunterGel>

<end of log>
```
Tried to download a video from URL https://tvthek.orf.at/ as I did several times before, last successful download about three weeks ago; now I got the error above.
orf:tvthek: ORF TVthek is listed as being supported.

**Comment by dstftw** [comment]
Misconfigured certificate server side. Report to them or `--no-check-certificate` if you don't care.
