### ISSUE TITLE
[CartoonNetwork] KeyError: 'id'

### ISSUE THREAD

**Issue by JamesTheAwesomeDude** [rg3/youtube-dl#16854]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.06.25**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

```
youtube-dl --hls-prefer-native -v https://www.cartoonnetwork.com/video/unlocked/mindful-education-episode.html 
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--hls-prefer-native', '-v', 'https://www.cartoonnetwork.com/video/unlocked/mindful-education-episode.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.06.25
[debug] Python version 3.5.3 (CPython) - Linux-4.9.0-6-amd64-x86_64-with-debian-9.4
[debug] exe versions: ffmpeg 3.2.10-1, ffprobe 3.2.10-1
[debug] Proxy map: {}
[CartoonNetwork] mindful-education: Downloading webpage
[CartoonNetwork] 8c2025d2be242d2de504aae5e8804556aa1d35dc: Downloading XML
ERROR: An extractor error has occurred. (caused by KeyError('id',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/james/.local/lib/python3.5/site-packages/youtube_dl-2018.6.25-py3.5.egg/youtube_dl/extractor/common.py", line 501, in extract
    ie_result = self._real_extract(url)
  File "/home/james/.local/lib/python3.5/site-packages/youtube_dl-2018.6.25-py3.5.egg/youtube_dl/extractor/cartoonnetwork.py", line 41, in _real_extract
    webpage, 'auth required', default='false') == 'true',
  File "/home/james/.local/lib/python3.5/site-packages/youtube_dl-2018.6.25-py3.5.egg/youtube_dl/extractor/turner.py", line 53, in _extract_cvp_info
    video_id = video_data.attrib['id']
KeyError: 'id'
Traceback (most recent call last):
  File "/home/james/.local/lib/python3.5/site-packages/youtube_dl-2018.6.25-py3.5.egg/youtube_dl/extractor/common.py", line 501, in extract
    ie_result = self._real_extract(url)
  File "/home/james/.local/lib/python3.5/site-packages/youtube_dl-2018.6.25-py3.5.egg/youtube_dl/extractor/cartoonnetwork.py", line 41, in _real_extract
    webpage, 'auth required', default='false') == 'true',
  File "/home/james/.local/lib/python3.5/site-packages/youtube_dl-2018.6.25-py3.5.egg/youtube_dl/extractor/turner.py", line 53, in _extract_cvp_info
    video_id = video_data.attrib['id']
KeyError: 'id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/james/.local/lib/python3.5/site-packages/youtube_dl-2018.6.25-py3.5.egg/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/home/james/.local/lib/python3.5/site-packages/youtube_dl-2018.6.25-py3.5.egg/youtube_dl/extractor/common.py", line 514, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('id',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

---

### Description of your *issue*, suggested solution and other information

Despite `pycrypto` and ffmpeg being installed, as well as the appropriate flags from last time being used, the video is not downloaded.

I'm using Git HEAD as of 2018-06-28 1:15PM CDT.  
`git clone $url && cd y* && python3 setup.py install --user`

Might be worth noting that with `--dump-pages`, the second page dumped:

````
[CartoonNetwork] mindful-education: Downloading webpage
[CartoonNetwork] Dumping request to https://www.cartoonnetwork.com/video/unlocked/mindful-education-episode.html
CgoKCgoKCgoKPCFET0NUWVBFIGh0bW[SNIPPED ~1.8MiB]
[CartoonNetwork] 8c2025d2be242d2de504aae5e8804556aa1d35dc: Downloading XML
[CartoonNetwork] Dumping request to https://video-api.cartoonnetwork.com/contentXML/8c2025d2be242d2de504aae5e8804556aa1d35dc
PHZpZGVvLz4=
````

`PHZpZGVvLz4=` translates to `<video/>`

**Comment by JamesTheAwesomeDude** [comment]
NB: I used to be able to download from CN quite easily.

I have migrated to a new machine recently; but on the other hand it's been at least around a year since I last downloaded, so I am not 100% sure whether or not I'm just missing some as-yet-undocumented dependencies of `cartoonnetwork.py`, or if the site actually broke during this hiatus.

**Comment by JamesTheAwesomeDude** [comment]
Hmm

Upon further inspection I see the duplicate

(I also had to wade through the pile of these that have been opened and silently closed-as-duplicate)

For future reference / anyone stumbling across this thread:

# #15664

(I wonder what's up with the single deleted comment, absolutely no responses, followed by the thread-lock.....🤔)
