### ISSUE TITLE
ABC iView - 'movie length' tv shows

### ISSUE THREAD

**Issue by NateWard** [rg3/youtube-dl#16868]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.06.25*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.06.25**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://iview.abc.net.au/show/octonauts-and-operation-deep-freeze']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.06.25
[debug] Python version 2.7.15 (CPython) - Darwin-17.5.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.0, ffprobe 4.0
[debug] Proxy map: {}
[generic] octonauts-and-operation-deep-freeze: Requesting header
WARNING: Falling back on generic information extractor.
[generic] octonauts-and-operation-deep-freeze: Downloading webpage
[generic] octonauts-and-operation-deep-freeze: Extracting information
ERROR: Unsupported URL: https://iview.abc.net.au/show/octonauts-and-operation-deep-freeze
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2309, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2542, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2531, in _XML
    parser.feed(text)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 6, column 700
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 501, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3269, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://iview.abc.net.au/show/octonauts-and-operation-deep-freeze
```
---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

I know there have been a few ABC iView issue of late. The comments on those have helped immensely but I haven't been able to get the 'movie' length episodes to work as they have their own unique pages. Any advice or assistance would be great.

**Comment by noideajase** [comment]
The URLs are now only available by following the 'share' links, otherwise using the direct link from the  image appears to act as a hidden $_POST action or similar.
Also ensure you have the latest version of -dl 
sudo youtube-dl -U
Cheers

**Comment by NateWard** [comment]
Thanks for that. I've updated to the latest version. the share link works for the standard tv shows but not for the 'movie length' ones such as the link above. (https://iview.abc.net.au/show/octonauts-and-operation-deep-freeze). If its not possible do fix it (or a work around) just let me know and I'll stop bugging you.

P.S. LOVE the program!

**Comment by noideajase** [comment]
I was sharing the work around I found as I had the same issue with normal
length shows the same day and an update of the package and using the link
worked in that case.
Unfortunately looks like my info did not help you further.
Yeah these guys have put together an awesome package - I couldn't code
something like this to save myself :-)

**Comment by NateWard** [comment]
I've think if you search through the page source code you can find the ID for the episode and then use http://[PAGE URL]/video/[VIDEO ID]

**Comment by shtrom** [comment]
I tried to implement @NateWard in #23401. It worked for me on a few cursory tests, but happy for more eyeballs giving it a go (because, you know, you need to give a go to have a go, or something...)

**Comment by gamer191** [comment]
This is no longer an issue, because clicking the play button on movies, on abc iview, redirects to a URL which does work in youtube-dl. That said, youtube-dl should do this redirect automatically, so imo this issue should be kept open.
