### ISSUE TITLE
ValueError: unsupported format character 'D' (0x44) at index 335

### ISSUE THREAD

**Issue by rofl0r** [rg3/youtube-dl#16867]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.06.25*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.06.25**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
$ youtube-dl -v https://bigleaguepolitics.com/laura-loomer-presses-assault-charges-against-maxine-waters/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://bigleaguepolitics.com/laura-loomer-presses-assault-charges-against-maxine-waters/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.06.25
[debug] Python version 2.7.15 (CPython) - Linux-4.14.50-x86_64-with-libc
[debug] exe versions: ffmpeg 3.4.1, ffprobe 3.4.1
[debug] Proxy map: {}
[generic] laura-loomer-presses-assault-charges-against-maxine-waters: Requesting header
WARNING: Falling back on generic information extractor.
[generic] laura-loomer-presses-assault-charges-against-maxine-waters: Downloading webpage
[generic] laura-loomer-presses-assault-charges-against-maxine-waters: Extracting information
[download] Downloading playlist: Laura Loomer Presses Assault Charges Against Maxine Waters - Big League Politics
[generic] playlist Laura Loomer Presses Assault Charges Against Maxine Waters - Big League Politics: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[brightcove:new] 5802332407001: Downloading webpage
[brightcove:new] 5802332407001: Downloading JSON metadata
[brightcove:new] 5802332407001: Downloading m3u8 information
[brightcove:new] 5802332407001: Downloading m3u8 information
[brightcove:new] 5802332407001: Downloading m3u8 information
[brightcove:new] 5802332407001: Downloading m3u8 information
[brightcove:new] 5802332407001: Downloading MPD manifest
Traceback (most recent call last):
  File "/bin/youtube-dl", line 9, in <module>
    load_entry_point('youtube-dl==2018.06.25', 'console_scripts', 'youtube-dl')()
  File "/lib/python2.7/site-packages/youtube_dl/__init__.py", line 472, in main
    _real_main(argv)
  File "/lib/python2.7/site-packages/youtube_dl/__init__.py", line 462, in _real_main
    retcode = ydl.download(all_urls)
  File "/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 2001, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 803, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 1002, in process_ie_result
    extra_info=extra)
  File "/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 864, in process_ie_result
    extra_info=extra_info)
  File "/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 501, in extract
    ie_result = self._real_extract(url)
  File "/lib/python2.7/site-packages/youtube_dl/extractor/brightcove.py", line 743, in _real_extract
    json_data, video_id, headers=headers)
  File "/lib/python2.7/site-packages/youtube_dl/extractor/brightcove.py", line 586, in _parse_brightcove_metadata
    formats.extend(self._extract_mpd_formats(src, video_id, 'dash', fatal=False))
  File "/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 1971, in _extract_mpd_formats
    formats_dict=formats_dict, mpd_url=mpd_url)
  File "/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 2127, in _parse_mpd_formats
    'Bandwidth': bandwidth,
ValueError: unsupported format character 'D' (0x44) at index 335

```

---

### Description of your *issue*, suggested solution and other information

https://bigleaguepolitics.com/laura-loomer-presses-assault-charges-against-maxine-waters/

**Comment by rofl0r** [comment]
thanks! i applied your patch to 06.25, now this video works but i get a new error:

```
[generic] watch-gop-releases-toughest-political-ad-since-the-daisy-girl-in-1964: Extracting information
Traceback (most recent call last):
  File "/bin/youtube-dl", line 9, in <module>
    load_entry_point('youtube-dl==2018.06.25', 'console_scripts', 'youtube-dl')()
  File "/lib/python2.7/site-packages/youtube_dl/__init__.py", line 472, in main
    _real_main(argv)
  File "/lib/python2.7/site-packages/youtube_dl/__init__.py", line 462, in _real_main
    retcode = ydl.download(all_urls)
  File "/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 2001, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 501, in extract
    ie_result = self._real_extract(url)
  File "/lib/python2.7/site-packages/youtube_dl/extractor/generic.py", line 3129, in _real_extract
    jwplayer_data, video_id, require_title=False, base_url=url)
  File "/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 2573, in _parse_jwplayer_data
    video_data['sources'] = [video_data]
TypeError: 'unicode' object does not support item assignment
```

with https://www.westernjournal.com/ct/watch-gop-releases-toughest-political-ad-since-the-daisy-girl-in-1964/

**Comment by Hrxn** [comment]
Does it work with Python 3?

**Comment by rofl0r** [comment]
i don't have python3 (i didn't port it yet to my custom OS)

btw:

```
[foxnews:article] woman-dubbed-permitpatty-appears-to-call-cops-on-: Downloading webpage
Traceback (most recent call last):
  File "/bin/youtube-dl", line 9, in <module>
    load_entry_point('youtube-dl==2018.06.25', 'console_scripts', 'youtube-dl')()
  File "/lib/python2.7/site-packages/youtube_dl/__init__.py", line 472, in main
    _real_main(argv)
  File "/lib/python2.7/site-packages/youtube_dl/__init__.py", line 462, in _real_main
    retcode = ydl.download(all_urls)
  File "/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 2001, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 501, in extract
    ie_result = self._real_extract(url)
  File "/lib/python2.7/site-packages/youtube_dl/extractor/foxnews.py", line 127, in _real_extract
    FoxNewsIE._extract_urls(webpage)[0], FoxNewsIE.ie_key())
IndexError: list index out of range
```
http://www.foxnews.com/us/2018/06/24/woman-dubbed-permitpatty-appears-to-call-cops-on-8-year-old-girl-selling-water-in-viral-video.html
