### ISSUE TITLE
Verizon ap never works

### ISSUE THREAD

**Issue by thesteveway** [rg3/youtube-dl#16879]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.06.25*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2018.06.25**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Stephens-MacBook-Pro:~ stephenway$ youtube-dl -v --ap-mso Verizon --ap-username **** --ap-password **** https://www.fox.com/watch/6fd3f46510c80192879e8cbdc896cf6a/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--ap-mso', u'Verizon', u'--ap-username', u'PRIVATE', u'--ap-password', u'PRIVATE', u'https://www.fox.com/watch/6fd3f46510c80192879e8cbdc896cf6a/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.06.25
[debug] Python version 2.7.10 (CPython) - Darwin-17.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.0, ffprobe 4.0, rtmpdump 2.4
[debug] Proxy map: {}
[FOX] 6fd3f46510c80192879e8cbdc896cf6a: Downloading JSON metadata
[FOX] 6fd3f46510c80192879e8cbdc896cf6a: Downloading Provider Redirect Page
[FOX] 6fd3f46510c80192879e8cbdc896cf6a: Downloading SAML Login Page
ERROR: Unable to extract SAML Login URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 501, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/fox.py", line 87, in _real_extract
    url, video_id, 'fbc-fox', resource)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/adobepass.py", line 1482, in _extract_mvpd_auth
    saml_login_page, 'SAML Login URL', group='url')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 971, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract SAML Login URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

---

AP has never worked for me, the URL is the latest I've tried.

**Comment by thesteveway** [comment]
@dstftw can you please link me to the duplicate thread? I can't find any others with my same issue
