### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '5994666.666666'

### ISSUE THREAD

**Issue by romelako** [rg3/youtube-dl#16876]
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2018.06.25**
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other
---
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '< url omitted >']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.06.25
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: none
[debug] Proxy map: {}
[generic] manifest-167330494-1530380469: Requesting header
WARNING: Falling back on generic information extractor.
[generic] manifest-167330494-1530380469: Downloading webpage
[generic] manifest-167330494-1530380469: Extracting information
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkc931nsv\build\youtube_dl\__init__.py", line 472, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkc931nsv\build\youtube_dl\__init__.py", line 462, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkc931nsv\build\youtube_dl\YoutubeDL.py", line 2001, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkc931nsv\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkc931nsv\build\youtube_dl\extractor\common.py", line 501, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkc931nsv\build\youtube_dl\extractor\generic.py", line 2330, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkc931nsv\build\youtube_dl\extractor\common.py", line 2106, in _parse_mpd_formats
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkc931nsv\build\youtube_dl\extractor\common.py", line 2039, in extract_multisegment_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkc931nsv\build\youtube_dl\extractor\common.py", line 2011, in extract_common
ValueError: invalid literal for int() with base 10: '5994666.666666'
```
It appears that the program is trying to cast `5994666.666666` to an int. Here is a snippet of the .mpd:

```
<SegmentTemplate timescale="1000000" initialization="segment-0.mp4" media="segment-$Number$.m4s">
    <SegmentTimeline>
        <S t="0" d="5994666.666666"/>
        <S t="5994666.6666667" d="6016000"/>
        <S t="12010666.666667" d="5994666.666666"/>
        <S t="18005333.333333" d="5994666.666667"/>
```

**Comment by dstftw** [comment]
Post the original manifest URL.
