### ISSUE TITLE
youtube-dl cannot handle /? in VIMEO url 

### ISSUE THREAD

**Issue by symdeb** [rg3/youtube-dl#16886]
Vimeo downloading videos did work before, but not anymore after a /? sequence was added in their urls.

youtube-dl --verbose https://www.learndutch.org/free-dutch-grammar-preview-lesson/?utm_source=Weekly+newletter+Learndutch.org&utm_campaign=e5e3e3c024-startsubclause_COPY_01&utm_medium=email&utm_term=0_efbe1f10f1-e5e3e3c024-266208549&mc_cid=e5e3e3c024&mc_eid=6b905899c0 >> log
[1] 3946
[2] 3947
[3] 3948
[4] 3949
[5] 3950
[3]   Done                    utm_medium=email
[4]-  Done                    utm_term=0_efbe1f10f1-e5e3e3c024-266208549
user@H3U1:~$ [debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.learndutch.org/free-dutch-grammar-preview-lesson/?utm_source=Weekly+newletter+Learndutch.org']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.06.25
[debug] Python version 2.7.15rc1 (CPython) - Linux-4.15.0-23-lowlatency-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: avconv 3.4.2-2, avprobe 3.4.2-2, ffmpeg 3.4.2-2, ffprobe 3.4.2-2, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] ?utm_source=Weekly+newletter+Learndutch: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ?utm_source=Weekly+newletter+Learndutch: Downloading webpage
[generic] ?utm_source=Weekly+newletter+Learndutch: Extracting information
ERROR: Unsupported URL: https://www.learndutch.org/free-dutch-grammar-preview-lesson/?utm_source=Weekly+newletter+Learndutch.org
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 2309, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/compat.py", line 2542, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/compat.py", line 2531, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 13, column 280
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 501, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 3269, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.learndutch.org/free-dutch-grammar-preview-lesson/?utm_source=Weekly+newletter+Learndutch.org

**Comment by dstftw** [comment]
1. https://github.com/rg3/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command
2. learndutch.org not supported.
