### ISSUE TITLE
Site support for altbalaji.com please. 

### ISSUE THREAD

**Issue by shirishag75** [rg3/youtube-dl#16907]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.07.04*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ ] I've **verified** and **I assure** that I'm running youtube-dl **2018.07.04**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

```
$ youtube-dl --verbose "https://altbalaji.com/episode/3141"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://altbalaji.com/episode/3141']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.06.18
[debug] Python version 3.6.6 (CPython) - Linux-4.16.0-2-amd64-x86_64-with-debian-buster-sid
[debug] exe versions: ffmpeg 3.4.2-2, ffprobe 3.4.2-2, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 3141: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 3141: Downloading webpage
[generic] 3141: Extracting information
ERROR: Unsupported URL: https://altbalaji.com/episode/3141
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 500, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/generic.py", line 3263, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://altbalaji.com/episode/3141
```

While the youtube-dl version is a little stale but I looked at tickets, both open and closed if somebody had mentioned altbalaji.com as a site-support request but found it not there hence doing it. If somebody does get any success please share the success to me. Currently the site needs signing in credentials and then does streaming but only streaming :(

**Comment by shirishag75** [comment]
Still with the latest version the same issue is there :(

```
:/usr/local/bin$ ./youtube-dl --verbose "https://altbalaji.com/episode/3141"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://altbalaji.com/episode/3141']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.08.28
[debug] Python version 2.7.15 (CPython) - Linux-4.17.0-3-amd64-x86_64-with-debian-buster-sid
[debug] exe versions: ffmpeg 4.0.2-1, ffprobe 4.0.2-1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 3141: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 3141: Downloading webpage
[generic] 3141: Extracting information
ERROR: Unsupported URL: https://altbalaji.com/episode/3141
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/extractor/generic.py", line 2324, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "./youtube-dl/youtube_dl/compat.py", line 2542, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "./youtube-dl/youtube_dl/compat.py", line 2531, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 1, column 28
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 502, in extract
    ie_result = self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/generic.py", line 3294, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://altbalaji.com/episode/3141
```

**Comment by shirishag75** [comment]
same with the most recentish version I have - 

```
$ youtube-dl --verbose "https://altbalaji.com/show/236?directPlay=0"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://altbalaji.com/show/236?directPlay=0']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.09.10
[debug] Python version 3.6.6 (CPython) - Linux-4.18.0-1-amd64-x86_64-with-debian-buster-sid
[debug] exe versions: ffmpeg 4.0.2-1, ffprobe 4.0.2-1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 236?directPlay=0: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 236?directPlay=0: Downloading webpage
[generic] 236?directPlay=0: Extracting information
ERROR: Unsupported URL: https://altbalaji.com/show/236?directPlay=0
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 502, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/generic.py", line 3298, in _real_extract
    raise UnsupportedError(url)

```
