### ISSUE TITLE
Please support passthesalt.ubicast.tv

### ISSUE THREAD

**Issue by kradan** [rg3/youtube-dl#16926]
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [X] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

$ youtube-dl -v https://passthesalt.ubicast.tv/permalink/v125aaf957761ckbt1ll/
[debug] System config: []                                                                                  
[debug] User config: []                                                                                         
[debug] Custom config: []                                                               
[debug] Command-line args: [u'-v', u'https://passthesalt.ubicast.tv/permalink/v125aaf957761ckbt1ll/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8        
[debug] youtube-dl version 2018.07.04
[debug] Python version 2.7.13 (CPython) - Linux-4.9.0-6-amd64-x86_64-with-debian-9.4
[debug] exe versions: ffmpeg 3.2.10-1, ffprobe 3.2.10-1, rtmpdump 2.4
[debug] Proxy map: {}                                           
[generic] v125aaf957761ckbt1ll: Requesting header
WARNING: Falling back on generic information extractor.                                           
[generic] v125aaf957761ckbt1ll: Downloading webpage
[generic] v125aaf957761ckbt1ll: Extracting information                                              
ERROR: Unsupported URL: https://passthesalt.ubicast.tv/permalink/v125aaf957761ckbt1ll/
Traceback (most recent call last):                                                                          
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 2298, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))                                       
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/compat.py", line 2542, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/compat.py", line 2531, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 26, column 203
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 501, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 3258, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://passthesalt.ubicast.tv/permalink/v125aaf957761ckbt1ll/
<end of log>
```

**Comment by DuckHP** [comment]
@kradan Have you tried using the download url for the video(s) ?

e.g `$ tubeup https://passthesalt.ubicast.tv/downloads/file/v125aaf9568a03rq4scb/?url=https%3A//d2u3lzih3uhb7x.cloudfront.net/passthesalt/r125aaf9568a0n33nutcsq8dqt1tse/v125aaf9568a03rq4scb_2160.mp4`
