### ISSUE TITLE
vk ERROR: Video does not exist.

### ISSUE THREAD

**Issue by akula22** [rg3/youtube-dl#16923]
youtube-dl https://vk.com/video25702507_456241957 --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://vk.com/video25702507_456241957', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.07.04
[debug] Python version 2.7.6 (CPython) - Linux-4.9.103-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.20-6, avprobe 9.20-6
[debug] Proxy map: {}
[vk] 25702507_456241957: Downloading webpage
ERROR: Video 25702507_456241957 does not exist.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 501, in extract
    ie_result = self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/vk.py", line 352, in _real_extract
    raise ExtractorError(error_msg % video_id, expected=True)
ExtractorError: Video 25702507_456241957 does not exist.

**Comment by dstftw** [comment]
You did not pass account credentials.

**Comment by lynkas** [comment]
Totally same problem. It never happened before, and this is public video.

`$ youtube-dl 'https://vk.com/bemiraculous?w=wall-122455412_211532' --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://vk.com/bemiraculous?w=wall-122455412_211532', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.07.04
[debug] Python version 3.5.2 (CPython) - Linux-4.9.0-040900-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 3.4.2-1, ffprobe 3.4.2-1
[debug] Proxy map: {}
[vk:wallpost] 122455412_211532: Downloading webpage
[download] Downloading playlist: Miraculous | Леди Баг и Супер-Кот - Wall post 122455412_211532
[vk:wallpost] playlist Miraculous | Леди Баг и Супер-Кот - Wall post 122455412_211532: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[vk] -122455412_456239972: Downloading webpage
ERROR: Video -122455412_456239972 does not exist.
Traceback (most recent call last):
  File "/home/cat/.local/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/home/cat/.local/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 501, in extract
    ie_result = self._real_extract(url)
  File "/home/cat/.local/lib/python3.5/site-packages/youtube_dl/extractor/vk.py", line 352, in _real_extract
    raise ExtractorError(error_msg % video_id, expected=True)
youtube_dl.utils.ExtractorError: Video -122455412_456239972 does not exist.`

**Comment by spvkgn** [comment]
@dstftw  However, `streamlink` can handle VK streams without needing account credentials.
```
$ streamlink -l debug https://vk.com/video25702507_456241957 best -o /tmp/output.mp4
[cli][debug] OS:         Linux-4.15.0-22-generic-x86_64-with-Ubuntu-18.04-bionic
[cli][debug] Python:     3.6.5
[cli][debug] Streamlink: 0+unknown
[cli][debug] Requests(2.19.1), Socks(1.6.7), Websocket(0.48.0)
[cli][info] Found matching plugin vk for URL https://vk.com/video25702507_456241957
[plugin.vk][debug] video ID: 25702507_456241957
[cli][info] Available streams: 240p (worst), 360p, 480p, 720p, 1080p (best)
[cli][info] Opening stream: 1080p (http)
[cli][debug] Pre-buffering 8192 bytes
[cli][debug] Checking file output
[cli][debug] Writing stream to output
[download][output.mp4] Written 2.3 MB (3s @ 631.5 KB/s)                                                                                       
^C[cli][info] Stream ended
Interrupted! Exiting...
[cli][info] Closing currently open stream...
```
So why not do same with `youtube-dl`?
```
$ youtube-dl --ignore-config -v https://vk.com/video-27532693_456243764
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--ignore-config', '-v', 'https://vk.com/video-27532693_456243764']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.07.04
[debug] Python version 3.6.5 (CPython) - Linux-4.15.0-22-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.2-2, ffprobe 3.4.2-2, phantomjs 16, rtmpdump 2.4
[debug] Proxy map: {}
[vk] -27532693_456243764: Downloading webpage
ERROR: Video -27532693_456243764 does not exist.
Traceback (most recent call last):
  File "/home/pavel/.local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/home/pavel/.local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 501, in extract
    ie_result = self._real_extract(url)
  File "/home/pavel/.local/lib/python3.6/site-packages/youtube_dl/extractor/vk.py", line 352, in _real_extract
    raise ExtractorError(error_msg % video_id, expected=True)
youtube_dl.utils.ExtractorError: Video -27532693_456243764 does not exist.
```

**Comment by Wiiplay123** [comment]
Same problem here, they're all public videos that I can watch on the site so why can't I do it in youtube-dl?

**Comment by kasper93** [comment]
@remitamine Good job. Finally, after all this time... We could have it sooner :) https://github.com/rg3/youtube-dl/pull/10755

Back then I opted for fallback to "inline" link instead of using it directly. Not all videos were available on inline link. But it was a long time ago and my memory is foggy.
