### ISSUE TITLE
Unable to Download Pornhub User's Public Videos RegexNotFoundError

### ISSUE THREAD

**Issue by 12345yay12345** [rg3/youtube-dl#16959]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.07.10*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.07.10**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
$ youtube-dl -v https://www.pornhub.com/users/gfandi/videos/public
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.pornhub.com/users/gfandi/videos/public']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.07.10
[debug] Python version 3.6.1 (CPython) - Darwin-17.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2
[debug] Proxy map: {}
[PornHubUserVideos] gfandi: Downloading page 1
[PornHubUserVideos] gfandi: Downloading page 2
[download] Downloading playlist: gfandi
[PornHubUserVideos] playlist gfandi: Collected 2 video ids (downloading 2 of them)
[download] Downloading video 1 of 2
[PornHub] ph5b4661cf85c3e: Downloading webpage
[PornHub] ph5b4661cf85c3e: Downloading webpage
ERROR: Unable to extract encoded url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 502, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/pornhub.py", line 141, in _real_extract
    'encoded url').split(';')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 972, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract encoded url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
...
<end of log>
```

---

### Description of your *issue*, suggested solution and other information
Just trying to download all of a user's videos.  I have done this with this tool before but it stopped working.

**Comment by 12345yay12345** [comment]
The account has since been removed, however, the error still stands with the following

```
$ youtube-dl -v https://www.pornhub.com/users/dirtylatincouple/videos/public
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.pornhub.com/users/dirtylatincouple/videos/public']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.07.10
[debug] Python version 3.6.1 (CPython) - Darwin-17.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2
[debug] Proxy map: {}
[PornHubUserVideos] dirtylatincouple: Downloading page 1
[PornHubUserVideos] dirtylatincouple: Downloading page 2
[download] Downloading playlist: dirtylatincouple
[PornHubUserVideos] playlist dirtylatincouple: Collected 11 video ids (downloading 11 of them)
[download] Downloading video 1 of 11
[PornHub] ph5b14a800d5032: Downloading webpage
[PornHub] ph5b14a800d5032: Downloading webpage
ERROR: Unable to extract encoded url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 502, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/pornhub.py", line 141, in _real_extract
    'encoded url').split(';')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 972, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract encoded url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by dstftw** [comment]
Post the output with `--dump-pages`.

**Comment by 12345yay12345** [comment]
The output was too big (over the 65,536 character limits), here it is with the mish mosh of random characters omitted

```
$ youtube-dl -v --dump-pages https://www.pornhub.com/users/blackmajicc/videos/public
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--dump-pages', 'https://www.pornhub.com/users/blackmajicc/videos/public']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.07.10
[debug] Python version 3.6.1 (CPython) - Darwin-17.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2
[debug] Proxy map: {}
[PornHubUserVideos] blackmajicc: Downloading page 1
[PornHubUserVideos] Dumping request to https://www.pornhub.com/users/blackmajicc/videos/public?page=1
PCFET0NUWVBFIGh0bWw+CjwhLS1baWYgbHQgSUUgNyBdPiA8aHRtbCBjbGFzcz0iaWU2IGxhbmd1YWdlLWVuIiBsYW5nPSJlbiI+IDwhW2VuZGlmXS0tPgo8IS0tW2lmIElFIDcgXT4JPGh0bWwgY2xhc3M9ImllNyBsYW5ndWFnZS1lbiIgbGFuZz0iZW4iPiA8IVtlbmRpZl0tLT4KPCEtLVtpZiBJRSA4IF0+CTxodG1sIGNsYXNzPSJpZTggbGFuZ3VhZ2UtZW4iIGxhbmc9ImVuIj4gPCFbZW5kaWZdLS0+CjwhLS1baWYg...

this goes on for a long time

...lciBNb25pdG9yaW5nCgkJICovCgkJaWYgKHR5cGVvZiBpc1Nob3dQYWdlID09ICd1bmRlZmluZWQnKSB7CgkJCXZhciBtZ1BlcmZvcm1hbmNlVGltaW5nU2V0dGluZ3MgPSB7CgkJCQlwYWdlVHlwZSA6ICdvdGhlcicJCQl9CgkJfQoJPC9zY3JpcHQ+CgoJCQk8c2NyaXB0IHNyYz0iaHR0cHM6Ly9jZG4xZC1zdGF0aWMtc2hhcmVkLnBobmNkbi5jb20vbmV0d29ya2Jhci00LjAuMy5qcyI+PC9zY3JpcHQ+CgkKCgoKPC9ib2R5Pgo8L2h0bWw+Cg==
[PornHubUserVideos] blackmajicc: Downloading page 2
[download] Downloading playlist: blackmajicc
[PornHubUserVideos] playlist blackmajicc: Collected 2 video ids (downloading 2 of them)
[download] Downloading video 1 of 2
[PornHub] ph5b48266268bf0: Downloading webpage
[PornHub] Dumping request to https://www.pornhub.com/view_video.php?viewkey=ph5b48266268bf0
PCFET0NUWVBFIGh0bWw+CjwhLS1baWYgbHQgSUUgNyBdPiA8aHRtbCBjbGFzcz0iaWU2IGxhbmd1YWdlLWVuIiBsYW5nPSJlbiI+IDwhW2VuZGlmXS0tPgo8IS0tW2lmIElFIDcgXT4JPGh0bWwgY2xhc3M9ImllNyBsYW5ndWFnZS1lbiIgbGFuZz0iZW4iPiA8IVtlbmRpZl0tLT4KPCEtLVtpZiBJRSA4IF0+CTxodG1sIGNsYXNzPSJpZTggbGFuZ3VhZ2UtZW4iIGxhbmc9ImVuIj4gPCFbZW5kaWZdLS0+CjwhLS1baWYg...

this goes on for a long time

...B7CgkJCXZhciBtZ1BlcmZvcm1hbmNlVGltaW5nU2V0dGluZ3MgPSB7CgkJCQlwYWdlVHlwZSA6ICd2aWRlbycJCQl9CgkJfQoJPC9zY3JpcHQ+CgoJCQk8c2NyaXB0IHNyYz0iaHR0cHM6Ly9jZG4xZC1zdGF0aWMtc2hhcmVkLnBobmNkbi5jb20vbmV0d29ya2Jhci00LjAuMy5qcyI+PC9zY3JpcHQ+CgkKCgoKPC9ib2R5Pgo8L2h0bWw+Cg==
ERROR: Unable to extract encoded url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 502, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/pornhub.py", line 141, in _real_extract
    'encoded url').split(';')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 972, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract encoded url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by dstftw** [comment]
You must post the complete log. Use any file sharing service.

**Comment by 12345yay12345** [comment]
https://github.com/12345yay12345/dump/tree/master

**Comment by 12345yay12345** [comment]
Hey why was this closed?

**Comment by Hrxn** [comment]
Because it was fixed with commit https://github.com/rg3/youtube-dl/commit/79367a98208fbf01d6e04b6747a6e01d0b1f8b9a?
(I assume, have not tested for myself)

No new release though, so either wait or run git master.

**Comment by 12345yay12345** [comment]
Ah, sorry, didn't see that, thanks all!
