### ISSUE TITLE
weibo unsupported or bug report

### ISSUE THREAD

**Issue by wsky11** [rg3/youtube-dl#16980]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.07.10*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.07.10**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are **not completely sure** provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.weibo.com/tv/v/FxSmHFoFw?from=vhot']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.07.10
[debug] Python version 2.7.10 (CPython) - Darwin-16.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.0.1, ffprobe 4.0.1
[debug] Proxy map: {}
[generic] FxSmHFoFw?from=vhot: Requesting header
[redirect] Following redirect to https://passport.weibo.com/visitor/visitor?entry=miniblog&a=enter&url=https%3A%2F%2Fweibo.com%2Ftv%2Fv%2FFxSmHFoFw%3Ffrom%3Dvhot&domain=.weibo.com&ua=php-sso_sdk_client-0.6.28&_rand=1531680191.3988
[generic] visitor?entry=miniblog&a=enter&url=https://weibo.com/tv/v/FxSmHFoFw?from=vhot&domain=.weibo.com&ua=php-sso_sdk_client-0.6.28&_rand=1531680191: Requesting header
WARNING: Falling back on generic information extractor.
[generic] visitor?entry=miniblog&a=enter&url=https://weibo.com/tv/v/FxSmHFoFw?from=vhot&domain=.weibo.com&ua=php-sso_sdk_client-0.6.28&_rand=1531680191: Downloading webpage
[generic] visitor?entry=miniblog&a=enter&url=https://weibo.com/tv/v/FxSmHFoFw?from=vhot&domain=.weibo.com&ua=php-sso_sdk_client-0.6.28&_rand=1531680191: Extracting information
ERROR: Unsupported URL: https://passport.weibo.com/visitor/visitor?entry=miniblog&a=enter&url=https%3A%2F%2Fweibo.com%2Ftv%2Fv%2FFxSmHFoFw%3Ffrom%3Dvhot&domain=.weibo.com&ua=php-sso_sdk_client-0.6.28&_rand=1531680191.3988
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2298, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2542, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2531, in _XML
    parser.feed(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 20, column 38
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 502, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3258, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://passport.weibo.com/visitor/visitor?entry=miniblog&a=enter&url=https%3A%2F%2Fweibo.com%2Ftv%2Fv%2FFxSmHFoFw%3Ffrom%3Dvhot&domain=.weibo.com&ua=php-sso_sdk_client-0.6.28&_rand=1531680191.3988
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.weibo.com/tv/v/FxSmHFoFw?from=vhot

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

**Comment by bato3** [comment]
Here is some anti-boot / anti add-block mechanisms. Try add browser cookies: https://github.com/rg3/youtube-dl#how-do-i-pass-cookies-to-youtube-dl

**Comment by wsky11** [comment]
I disabled my adblock extensions, added the cookies extension, and downloaded the cookies.txt. However I'm now getting HTTP Error 404: Not Found (caused by HTTPError());
