### ISSUE TITLE
ivysilani (ceskatelevize.cz) Problem

### ISSUE THREAD

**Issue by Martianno** [rg3/youtube-dl#16997]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.07.10*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2018.07.10**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2018.07.10
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

Hello, Unfortunately youtube-dl is currently not working for ivysilani (ceskatelevize.cz)
I am getting this message in cmd:

C:\CT>youtube-dl https://www.ceskatelevize.cz/ivysilani/1097181328-udalosti
[CeskaTelevize] 1097181328-udalosti: Downloading webpage
[CeskaTelevize] 1097181328-udalosti: Downloading JSON metadata
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4etivjk5\build\youtube_dl\__init__.py", line 472, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4etivjk5\build\youtube_dl\__init__.py", line 462, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4etivjk5\build\youtube_dl\YoutubeDL.py", line 2001, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4etivjk5\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4etivjk5\build\youtube_dl\extractor\common.py", line 502, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4etivjk5\build\youtube_dl\extractor\ceskatelevize.py", line 130, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4etivjk5\build\youtube_dl\utils.py", line 561, in sanitized_Request
  File "C:\Python\Python34\lib\urllib\request.py", line 267, in __init__
  File "C:\Python\Python34\lib\urllib\request.py", line 293, in full_url
  File "C:\Python\Python34\lib\urllib\request.py", line 322, in _parse
ValueError: unknown url type: 'Error'

I use the win .exe youtube-dl, last version

**Comment by mcepl** [comment]
@NiesmialyGosc you haven't applied the patch from fda2aa630318c5b7a384f9059aefdb535c7bf788

**Comment by mcepl** [comment]
```
matej@mitmanek: ~$ curl -L -I -v https://www.ceskatelevize.cz/ivysilani/ajax/get-client-playlist
* About to connect() to www.ceskatelevize.cz port 443 (#0)
*   Trying 212.47.2.209...
* Connected to www.ceskatelevize.cz (212.47.2.209) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLS_DHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate:
* 	subject: CN=ceskatelevize.cz,OU=IT,O=ČESKÁ TELEVIZE,L=Praha,C=CZ,serialNumber=00027383,incorporationCountry=CZ,businessCategory=Private Organization
* 	start date: Jun 25 00:00:00 2018 GMT
* 	expire date: Oct 18 12:00:00 2019 GMT
* 	common name: ceskatelevize.cz
* 	issuer: CN=GeoTrust EV RSA CA 2018,OU=www.digicert.com,O=DigiCert Inc,C=US
> HEAD /ivysilani/ajax/get-client-playlist HTTP/1.1
> User-Agent: curl/7.29.0
> Host: www.ceskatelevize.cz
> Accept: */*
> 
< HTTP/1.1 403 Forbidden
HTTP/1.1 403 Forbidden
< Server: nginx
Server: nginx
< Date: Mon, 23 Jul 2018 13:35:21 GMT
Date: Mon, 23 Jul 2018 13:35:21 GMT
< Content-Type: text/html; charset=iso-8859-1
Content-Type: text/html; charset=iso-8859-1
< Content-Length: 226
Content-Length: 226
< Connection: keep-alive
Connection: keep-alive

< 
* Connection #0 to host www.ceskatelevize.cz left intact
matej@mitmanek: ~$
```
Unfortunately, Česká Televize apparently still uses certificate which has been distrusted by most operating systems and browsers.

**Comment by borhub** [comment]
Thanks. This workaround fixed the issue for me too.

**Comment by Drakonosh** [comment]
Could you make a new version with this diff soon please?

**Comment by bato3** [comment]
@Drakonosh it's merged
for https://www.ceskatelevize.cz/ivysilani/10988632309-smrt-prichazi-do-pemberley/216381479580001 `Pořad bylo možné přehrát do 28. 7. 2018 22:50`

also add `--no-check-certificate`

**Comment by mcepl** [comment]
This should be closed, shouldn’t it?

**Comment by bato3** [comment]
Probably yes. Take tests, you'll know. XD

**Comment by porn** [comment]
The certificate problem seems to be solved by ceskatelevize.cz

**Comment by mcepl** [comment]
ping? Could somebody close this?

**Comment by dirkf** [comment]
Was fixed, but now see #31922.
