### ISSUE TITLE
Site support request for Kijk.nl

### ISSUE THREAD

**Issue by Amitari** [rg3/youtube-dl#16991]
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2018.07.10**
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser
- [X] Site support request (request for adding support for a new site)

```
[user@halebop youtube-dl]$ youtube-dl -v https://www.kijk.nl/sbs6/despa/videos/ZEiG4I6789w/de-spa
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.kijk.nl/sbs6/despa/videos/ZEiG4I6789w/de-spa']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.07.10
[debug] Python version 3.6.6 (CPython) - Linux-4.17.5-1-MANJARO-x86_64-with-arch-Manjaro-Linux
[debug] exe versions: ffmpeg 4.0.1, ffprobe 4.0.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] de-spa: Requesting header
[redirect] Following redirect to https://consent.kijk.nl/?url=https://www.kijk.nl/sbs6/despa/videos/ZEiG4I6789w/de-spa
[generic] de-spa: Requesting header
WARNING: Falling back on generic information extractor.
[generic] de-spa: Downloading webpage
[generic] de-spa: Extracting information
ERROR: Unsupported URL: https://consent.kijk.nl/?url=https://www.kijk.nl/sbs6/despa/videos/ZEiG4I6789w/de-spa
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 502, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/generic.py", line 3258, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://consent.kijk.nl/?url=https://www.kijk.nl/sbs6/despa/videos/ZEiG4I6789w/de-spa

[user@halebop youtube-dl]$ 
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.kijk.nl/sbs6/despa/videos/ZEiG4I6789w/de-spa
- Playlist: https://www.kijk.nl/sbs6/despa/

---

### Description of your *issue*, suggested solution and other information

This Dutch streaming site used to be supported, but after the compatibility was broken, support seems to have been dropped completely since it's not in the supported sites list anymore. But if anyone is interested in reimplementing it, I want to show my interest. It seems like the site has to be accessed from a Dutch IP address though, since I had to use a VPN.

**Comment by martysmarty** [comment]
It still works if you send a cookie file with consent cookie, and use the direct m3u8 file

**Comment by sarffy1986** [comment]
Nagyon szépen megkérek mindenkit hogy ebből én nemcsináltam semmit és soha
nem is akartam volna senkit se megbántani és aztse tudhattam hogy nem lehet
mert akkor nem megyek rá a holnapra azért regisztráltam amit az imént
betöltött az átküldött linkben és láttam bevan jelentkezve de én abból soha
nem csináltam még a nevét se tudom a honlapnak rólam raktak fel állítólag
valami olyant ami nem fedi a valóságot és akor kerestem amit nem találtam
és feladtam a keresést mert én soha senkit nem sértenék és nagyon ne
haragudj bocsánatot kérek
2020. febr. 27. 11:19 ezt írta ("martysmarty" <notifications@github.com>):

**Comment by robster7674** [comment]
Just tried with youtube-dl -v https://www.kijk.nl/programmas/steenrijk-straatarm/FKkgQMmowzv, but that fails with unsupported protocol:
```
Mac@Book ~ % youtube-dl -v https://www.kijk.nl/programmas/steenrijk-straatarm/FKkgQMmowzv
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.kijk.nl/programmas/steenrijk-straatarm/FKkgQMmowzv']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: c092d64
[debug] Python version 3.10.7 (CPython) - macOS-10.15.7-x86_64-i386-64bit
[debug] exe versions: avconv 11.4, avprobe 11.4, rtmpdump 2.4
[debug] Proxy map: {}
[generic] FKkgQMmowzv: Requesting header
WARNING: Falling back on generic information extractor.
[generic] FKkgQMmowzv: Downloading webpage
[generic] FKkgQMmowzv: Extracting information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://vod.prd1.talpatvcdn.nl/b3649a4879e84636b2d97956d1dc0316/d6640161dc6742f9a8d3dd909deea8ea/8090c2be20294a89b811fc891eff4801/index.m3u8'
[download] Destination: Steenrijk, straatarm - Seizoen 8 Aflevering 1 gemist Bekijk hier de hele uitzending - kijk.nl-FKkgQMmowzv.m3u8
[debug] avconv command line: avconv -y -loglevel verbose -headers 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3773.1 Safari/537.36
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Encoding: gzip, deflate
Accept-Language: en-us,en;q=0.5
' -i https://vod.prd1.talpatvcdn.nl/b3649a4879e84636b2d97956d1dc0316/d6640161dc6742f9a8d3dd909deea8ea/8090c2be20294a89b811fc891eff4801/index.m3u8 -c copy -f mp4 'file:Steenrijk, straatarm - Seizoen 8 Aflevering 1 gemist Bekijk hier de hele uitzending - kijk.nl-FKkgQMmowzv.m3u8.part'
avconv version 11.4, Copyright (c) 2000-2014 the Libav developers
  built on Sep 24 2016 09:22:24 with Apple LLVM version 7.0.2 (clang-700.1.81)
  configuration: --disable-debug --disable-shared --disable-indev=jack --prefix=/usr/local/Cellar/libav/11.4_2 --enable-gpl --enable-nonfree --enable-version3 --enable-vda --cc=clang --host-cflags= --host-ldflags= --enable-libfaac --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libxvid
  libavutil     54.  3. 0 / 54.  3. 0
  libavcodec    56.  1. 0 / 56.  1. 0
  libavformat   56.  1. 0 / 56.  1. 0
  libavdevice   55.  0. 0 / 55.  0. 0
  libavfilter    5.  0. 0 /  5.  0. 0
  libavresample  2.  1. 0 /  2.  1. 0
  libswscale     3.  0. 0 /  3.  0. 0
https://vod.prd1.talpatvcdn.nl/b3649a4879e84636b2d97956d1dc0316/d6640161dc6742f9a8d3dd909deea8ea/8090c2be20294a89b811fc891eff4801/index.m3u8: Protocol not found


ERROR: ffmpeg exited with code 1
  File "/usr/local/bin/youtube-dl", line 33, in <module>
    sys.exit(load_entry_point('youtube-dl==2021.12.17', 'console_scripts', 'youtube-dl')())
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/__init__.py", line 475, in main
    _real_main(argv)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/__init__.py", line 465, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 2068, in download
    res = self.extract_info(
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 808, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 847, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 881, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 1692, in process_video_result
    self.process_info(new_info)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 1976, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 1915, in dl
    return fd.download(name, info)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/downloader/external.py", line 63, in real_download
    self.report_error('%s exited with code %d' % (
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/downloader/common.py", line 165, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 628, in report_error
    self.trouble(error_message, tb)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 590, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())
```
@martysmarty : how could I try the option you are suggesting?
