### ISSUE TITLE
HTTP error: HTTP Error 503: Service Unavailable. yvUXAqLakQw

### ISSUE THREAD

**Issue by olspookishmagus** [rg3/youtube-dl#17016]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.07.10*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.07.10**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
$ youtube-dl -F yvUXAqLakQw
[youtube] yvUXAqLakQw: Downloading webpage
[youtube] yvUXAqLakQw: Downloading video info webpage
[info] Available formats for yvUXAqLakQw:
format code  extension  resolution note
249          webm       audio only DASH audio   81k , opus @ 50k, 133.05MiB
250          webm       audio only DASH audio   95k , opus @ 70k, 169.72MiB
171          webm       audio only DASH audio  104k , vorbis@128k, 173.87MiB
140          m4a        audio only DASH audio  148k , m4a_dash container, mp4a.40.2@128k, 327.15MiB
251          webm       audio only DASH audio  159k , opus @160k, 327.76MiB
278          webm       256x144    144p  143k , webm container, vp9, 6fps, video only, 83.66MiB
134          mp4        640x360    360p  149k , avc1.4d4016, 6fps, video only, 203.83MiB
242          webm       426x240    240p  150k , vp9, 6fps, video only, 104.14MiB
243          webm       640x360    360p  179k , vp9, 6fps, video only, 176.59MiB
160          mp4        256x144    144p  182k , avc1.4d400c, 6fps, video only, 122.26MiB
244          webm       854x480    480p  207k , vp9, 6fps, video only, 245.45MiB
135          mp4        854x480    480p  217k , avc1.4d4016, 6fps, video only, 378.75MiB
247          webm       1280x720   720p  253k , vp9, 6fps, video only, 349.39MiB
248          webm       1920x1080  1080p  301k , vp9, 6fps, video only, 454.01MiB
133          mp4        426x240    240p  313k , avc1.4d4015, 6fps, video only, 266.77MiB
136          mp4        1280x720   720p  344k , avc1.4d401f, 6fps, video only, 680.81MiB
137          mp4        1920x1080  1080p  569k , avc1.640028, 6fps, video only, 1.17GiB
17           3gp        176x144    small , mp4v.20.3, mp4a.40.2@ 24k, 86.46MiB
36           3gp        320x180    small , mp4v.20.3, mp4a.40.2, 144.87MiB
43           webm       640x360    medium , vp8.0, vorbis@128k, 314.24MiB
18           mp4        640x360    medium , avc1.42001E, mp4a.40.2@ 96k, 405.63MiB
22           mp4        1280x720   hd720 , avc1.64001F, mp4a.40.2@192k (best)
$ youtube-dl -v -f 251 yvUXAqLakQw
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-f', u'251', u'yvUXAqLakQw']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.07.10
[debug] Python version 2.7.15 (CPython) - Linux-4.9.0-6-amd64-x86_64-with-debian-buster-sid
[debug] exe versions: avconv 3.4.2-2, avprobe 3.4.2-2, ffmpeg 3.4.2-2, ffprobe 3.4.2-2, phantomjs ., rtmpdump 2.4
[debug] Proxy map: {}
[youtube] yvUXAqLakQw: Downloading webpage
[youtube] yvUXAqLakQw: Downloading video info webpage
[debug] Invoking downloader on u'https://r3---sn-vuxbavcx-5uis.googlevideo.com/videoplayback?id=o-ALdFAg7rA1sBdDNsyHRNUMTZiHLMFAcc9qm8GqujCrwI&dur=21599.000&source=youtube&fvip=1&keepalive=yes&ip=2.87.131.112&requiressl=yes&itag=251&lmt=1440633701399058&ms=au%2Crdu&ei=1EdQW9aSAdibgQfbvaroAg&mv=m&pl=16&mt=1531987911&clen=343685539&signature=C058DDFD251B2E50AC6C7FD396739A4F507D0EAC.6A45B77167A144E012ECB7181AE4067EC7FE7F20&key=yt6&mn=sn-vuxbavcx-5uis%2Csn-4g5ednsz&mm=31%2C29&c=WEB&gir=yes&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&fexp=23709359%2C23745105&ipbits=0&initcwndbps=507500&expire=1532009524&mime=audio%2Fwebm&ratebypass=yes'
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 1 of 10)...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 2 of 10)...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 3 of 10)...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 4 of 10)...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 5 of 10)...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 6 of 10)...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 7 of 10)...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 8 of 10)...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 9 of 10)...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 10 of 10)...
ERROR: giving up after 10 retries
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 341, in real_download
    establish_connection()
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 182, in establish_connection
    raise RetryDownload(err)
RetryDownload

```

This error also persists even when using cookies.

**Comment by dstftw** [comment]
251 is not available for this video server side.
