### ISSUE TITLE
support for google docs

### ISSUE THREAD

**Issue by 5shekel** [rg3/youtube-dl#1701]
```
m:\bin\youtube-dl>youtube-dl.exe https://docs.google.com/open?id=0B-9-TQYz6mpNMF84Y3YwYTBpQjQ --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['https://docs.google.com/open?id=0B-9-TQYz6mpNMF84Y3YwYTBpQjQ', '--verbose']
[debug] youtube-dl version 2013.10.09
[debug] Python version 2.7.5 - Windows-7-6.1.7601-SP1
[debug] Proxy map: {}
[redirect] Following redirect to https://docs.google.com/file/d/0B-9-TQYz6mpNMF84Y3YwYTBpQjQ/edit?usp=drive_web
WARNING: Falling back on generic information extractor.
[generic] edit?usp=drive_web: Downloading webpage
[generic] edit?usp=drive_web: Extracting information
ERROR: Unsupported URL: https://docs.google.com/file/d/0B-9-TQYz6mpNMF84Y3YwYTBpQjQ/edit?usp=drive_web; please report this is
ure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; t
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 348, in extract_info
  File "youtube_dl\extractor\common.pyo", line 117, in extract
  File "youtube_dl\extractor\generic.pyo", line 152, in _real_extract
ExtractorError: Unsupported URL: https://docs.google.com/file/d/0B-9-TQYz6mpNMF84Y3YwYTBpQjQ/edit?usp=drive_web; please repor
ug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest v
ate.
````

**Comment by remitamine** [comment]
will be supported in the next version.
