### ISSUE TITLE
iwara.tv is not working anymore

### ISSUE THREAD

**Issue by SecTec** [rg3/youtube-dl#17026]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.07.10*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.07.10**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [x] Other

---

### Downloading of videos from iwara.tv is not working anymore.

The last time youtube-dl has worked with that site is 2018-07-18.

```
youtube-dl --version
2018.07.10

youtube-dl https://www.iwara.tv/videos/daek6sze7gtkemzex
[Iwara] daek6sze7gtkemzex: Downloading webpage
[Iwara] daek6sze7gtkemzex: Downloading JSON metadata
ERROR: unable to download video data: HTTP Error 418:

```

**Comment by Rektis** [comment]
The modified extractor posted by user dstftw above doesn't fix it for me.
I also tried AlexAplin's modified iwara extractor (https://github.com/rg3/youtube-dl/pull/16741/commits/d26a533272c55957edcb13163fbe91788769b1b3), but it doesn't work anymore, either.



## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.07.21*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2018.07.21**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Full verbose output:


```

C:\Users\USERNAME>py -m youtube_dl -o "F:/HT/HT/VID/youtube-dl_automatic/iwara/%(uploader)s/%(upload_date)s --- %(id)s --- %(uploader)s --- %(title)s.%(ext)s" --batch-file="F:/HT/HT/VID/youtube-dl_automatic/dl_list.txt" -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-o', 'F:/HT/HT/VID/youtube-dl_automatic/iwara/%(uploader)s/%(upload_date)s --- %(id)s --- %(uploader)s --- %(title)s.%(ext)s', '--batch-file=F:/HT/HT/VID/youtube-dl_automatic/dl_list.txt', '-v']
[debug] Batch file urls: ['https://ecchi.iwara.tv/videos/b1mg6c6l3f36vold', 'https://ecchi.iwara.tv/videos/yjmbxsqaauoz245g', 'https://ecchi.iwara.tv/videos/ejoa3cb9m3tkv5kza', 'https://ecchi.iwara.tv/videos/k0we2hqkrwszrb1bp?language=en', 'https://ecchi.iwara.tv/videos/bbr7otwpvxf31b07g?language=en', 'https://ecchi.iwara.tv/videos/7kaqqurkdqcmgp9ng?language=en', 'https://ecchi.iwara.tv/videos/5zm8qtpvy3iw427nm?language=en', 'https://ecchi.iwara.tv/videos/k0zpqfqkrwszr0qmz?language=en', 'https://ecchi.iwara.tv/videos/elje6ubneqtmmveey?language=en', 'https://ecchi.iwara.tv/videos/my8m1ibgzgt88jxaq?language=en', 'https://ecchi.iwara.tv/videos/wyw2rugyvjcqq9zqb?language=en', 'https://ecchi.iwara.tv/videos/woqjpuvyvjsyyzblg?language=en', 'https://ecchi.iwara.tv/videos/e6grqsb4rktkk9vgm?language=en', 'https://ecchi.iwara.tv/videos/1qppmcz102u3308rp?language=en', 'https://ecchi.iwara.tv/videos/bpddzh0lqwsll8rp8?language=en', 'https://ecchi.iwara.tv/videos/4rpd8upo41iyywel5?language=en', 'https://ecchi.iwara.tv/videos/7kqxbirkdqcmmbggq?language=en', 'https://ecchi.iwara.tv/videos/dnymbfdgnqck7ovlr?language=en', 'https://ecchi.iwara.tv/videos/xrvertkaglcwnzoq1?language=en', 'https://ecchi.iwara.tv/videos/yovxvckj7qcog180w?language=en', 'https://ecchi.iwara.tv/videos/1ko8muz102u3yzywp?language=en', 'https://ecchi.iwara.tv/videos/z4oxgixyv1fkoe5zb?language=en', 'https://ecchi.iwara.tv/videos/v4krku68mxter9g1b?language=en', 'https://ecchi.iwara.tv/videos/pkrmyhzbk9togmq9z?language=en', 'https://ecchi.iwara.tv/videos/lb300ulq49t8brob9?language=en', 'https://ecchi.iwara.tv/videos/baao3swpvxf3j4amz?language=en', 'https://ecchi.iwara.tv/videos/owrovcaeebs6oj5mz?language=en', 'https://ecchi.iwara.tv/videos/0z88efeqo7szgqb0z?language=en', 'https://ecchi.iwara.tv/videos/jg1k9ugkgpuwlmyld?language=en', 'https://ecchi.iwara.tv/videos/1z85bcz5jef3e11rm?language=en', 'https://ecchi.iwara.tv/videos/g3yeyhrww3h7va1rn?language=en', 'https://ecchi.iwara.tv/videos/z2mmjur5bikkear4?language=en', 'https://ecchi.iwara.tv/videos/kegr1fz3gwhz3p1wv?language=en', 'https://ecchi.iwara.tv/videos/x1vz1u2pvuwvmeym?language=en', 'https://ecchi.iwara.tv/videos/jj1qmizgmyce03vej?language=en', 'https://ecchi.iwara.tv/videos/mlmk2crlrio7azol?language=en', 'https://ecchi.iwara.tv/videos/wgvgotnkgtyopm40?language=en', 'https://ecchi.iwara.tv/videos/gjlk7h212sopbq2w?language=en', 'https://ecchi.iwara.tv/videos/gjlkgs212sopbq0m?language=en', 'https://ecchi.iwara.tv/videos/ljmg1hjyjfwjed9l?language=en', 'https://ecchi.iwara.tv/videos/q9vj1hjqrbtr2wkox?language=en', 'https://ecchi.iwara.tv/videos/yjmrnt4p8fozaxjx?language=en', 'https://ecchi.iwara.tv/videos/ljmnqsly8oswjemym?language=en', 'https://ecchi.iwara.tv/videos/o5mqkc6lbxu1gjqx6?language=en', 'https://ecchi.iwara.tv/videos/kgmm5tzowwhqy32va?language=en', 'https://ecchi.iwara.tv/videos/jg1y2czzxyhwlzq3v?language=en', 'https://ecchi.iwara.tv/videos/z2m5wi39wyfkkq9w0?language=en', 'https://ecchi.iwara.tv/videos/9dyontqyeaiz2jn24?language=en', 'https://ecchi.iwara.tv/videos/o5mr1h6wri1gjjz0?language=en', 'https://ecchi.iwara.tv/videos/owgwqsrz51h6oveye?language=en', 'https://ecchi.iwara.tv/videos/g3y23sajaf7v0o0l?language=en', 'https://ecchi.iwara.tv/videos/rrr2jf90r6soqv2nm?language=en', 'https://ecchi.iwara.tv/videos/1zmbxslbvh3ea5b9?language=en', 'https://ecchi.iwara.tv/videos/1zmbmfbbzi3ea5vb?language=en', 'https://ecchi.iwara.tv/videos/60qvnirrzvuo1zll2?language=en', 'https://ecchi.iwara.tv/videos/9d4peuwjmpiz2qq57?language=en', 'https://ecchi.iwara.tv/videos/q9ywrcwjlsr2kzdy?language=en', 'https://ecchi.iwara.tv/videos/gj6djcka7copd4bv?language=en', 'https://ecchi.iwara.tv/videos/5q2johbbdiw1gzyn?language=en', 'https://ecchi.iwara.tv/videos/ej2y3hbovwckvaqo1?language=en', 'https://ecchi.iwara.tv/videos/4oax3fdl3hy0kloo?language=en', 'https://ecchi.iwara.tv/videos/q9ymvsjbqmsr2kbzl?language=en', 'https://ecchi.iwara.tv/videos/706g9tll3wfmw2m6z?language=en', 'https://ecchi.iwara.tv/videos/wgzaasz1vsyoabyq?language=en', 'https://ecchi.iwara.tv/videos/g3kgrtr2xu7vj8ew?language=en', 'https://ecchi.iwara.tv/videos/3jw92trk7u45kevm?language=en', 'https://ecchi.iwara.tv/videos/2xnqzfm6asq7kpkw?language=en', 'https://ecchi.iwara.tv/videos/60qw0s8wo1io1za2e?language=en', 'https://ecchi.iwara.tv/videos/60qmrsge6fo1ze8j?language=en', 'https://ecchi.iwara.tv/videos/o5p7gswn7s1gqqpg?language=en', 'https://ecchi.iwara.tv/videos/qe872tzpkeul8qvlj?language=en', 'https://ecchi.iwara.tv/videos/4oa6ycdzzafy0omvq?language=en', 'https://ecchi.iwara.tv/videos/o5pbph6gyof1gyyjb?language=en', 'https://ecchi.iwara.tv/videos/5q25dcjmwhw1qgdr?language=en', 'https://ecchi.iwara.tv/videos/706b1ieaaksmwzdzy?language=en', 'https://ecchi.iwara.tv/videos/x1zqziyklquwvwrg7?language=en', 'https://ecchi.iwara.tv/videos/bjrbouym1dhl1v2wq?language=en', 'https://ecchi.iwara.tv/videos/y6zjqikd2of0od8wj?language=en', 'https://ecchi.iwara.tv/videos/aombbipgqu7a1zrj?language=en', 'https://ecchi.iwara.tv/videos/ljw7mily6bhwjyy5y?language=en', 'https://ecchi.iwara.tv/videos/80jpef34w7flmvmyj?language=en', 'https://ecchi.iwara.tv/videos/y6zqoudbah0odem9?language=en', 'https://ecchi.iwara.tv/videos/bjraqc0gklil1vz1p?language=en', 'https://ecchi.iwara.tv/videos/9d4apselmcz2lnqb?language=en', 'https://ecchi.iwara.tv/videos/mbjkoirwlzi8pj0pg?language=en', 'https://ecchi.iwara.tv/videos/9d4o1s4oqfz2ljob?language=en', 'https://ecchi.iwara.tv/videos/gj6z3uzmjtop2g18?language=en', 'https://ecchi.iwara.tv/videos/abrk8h68af8rbbar?language=en', 'https://ecchi.iwara.tv/videos/vwkg4ir0yjiek732y?language=en', 'https://ecchi.iwara.tv/videos/y6z8wfm3rc0on75y?language=en', 'https://ecchi.iwara.tv/videos/r0robiyeq4hzx4np5?language=en', 'https://ecchi.iwara.tv/videos/lby2lugvext8ewnw1?language=en', 'https://ecchi.iwara.tv/videos/x1z3osmw3fwvdwko?language=en', 'https://ecchi.iwara.tv/videos/3jwvasqywwu45a4v7?language=en', 'https://ecchi.iwara.tv/videos/jg0w8ug799uwlew4p?language=en', 'https://ecchi.iwara.tv/videos/ml9mjfmoevio7qe3b?language=en', 'https://ecchi.iwara.tv/videos/daemxu5mbikeya03?language=en', 'https://ecchi.iwara.tv/videos/z2xjlslnpckk9wyl?language=en', 'https://ecchi.iwara.tv/videos/jg0mycdnnltwlqqrr?language=en', 'https://ecchi.iwara.tv/videos/1zmeliz3olu3eqqpz?language=en', 'https://ecchi.iwara.tv/videos/2xna2s9w8cq7dg8r?language=en', 'https://ecchi.iwara.tv/videos/o5pw0s6mbzf1gm5a4?language=en', 'https://ecchi.iwara.tv/videos/vwkypcx0ziekagb4?language=en', 'https://ecchi.iwara.tv/videos/z2xv7fx5r4fkk9gwn?language=en', 'https://ecchi.iwara.tv/videos/lby8rcgzrdh8eyyna?language=en', 'https://ecchi.iwara.tv/videos/abr0xi6yeu8r70r2?language=en', 'https://ecchi.iwara.tv/videos/5q2qru1n6cw1zknj?language=en', 'https://ecchi.iwara.tv/videos/ej2xwf7nzqckvp1gg?language=en', 'https://ecchi.iwara.tv/videos/3jw0pt71ot459j2n?language=en', 'https://ecchi.iwara.tv/videos/r0rkrfko15izx8vqz?language=en', 'https://ecchi.iwara.tv/videos/abr8eimjvaf8r7wvk?language=en', 'https://ecchi.iwara.tv/videos/ker15cq086sz3kaqm?language=en', 'https://ecchi.iwara.tv/videos/1zqbmck4zs3eolky?language=en', 'https://ecchi.iwara.tv/videos/y6kvjux3wf0oy30w?language=en', 'https://ecchi.iwara.tv/videos/owqbrurebu6okzvr?language=en', 'https://ecchi.iwara.tv/videos/q9jw3ukjyur2jrjg?language=en', 'https://ecchi.iwara.tv/videos/pk45jtb7bhogeakr?language=en']
[debug] Encodings: locale cp932, fs utf-8, out utf-8, pref cp932
[debug] youtube-dl version 2017.09.24
[debug] Python version 3.6.2 - Windows-10-10.0.15063-SP0
[debug] exe versions: ffmpeg N-90710-gaedbf1640c, ffprobe N-90710-gaedbf1640c
[debug] Proxy map: {}
[Iwara] b1mg6c6l3f36vold: Downloading webpage
[Iwara] b1mg6c6l3f36vold: Downloading JSON metadata
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://kokone.iwara.tv/file.php?expire=1532709896&hash=218feef7091e9e0e939acca31e9bd86a5b7f2c97&file=2017%2F03%2F29%2F1490751243_b1mG6C6L3F36vOlD_Source.mp4&op=dl&r=0'
ERROR: unable to download video data: HTTP Error 418:
Traceback (most recent call last):
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python36-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 1875, in process_info
    success = dl(filename, info_dict)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python36-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 1814, in dl
    return fd.download(name, info)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python36-32\lib\site-packages\youtube_dl\downloader\common.py", line 361, in download
    return self.real_download(filename, info_dict)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python36-32\lib\site-packages\youtube_dl\downloader\http.py", line 286, in real_download
    establish_connection()
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python36-32\lib\site-packages\youtube_dl\downloader\http.py", line 74, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "C:\UsersUSERNAME\AppData\Local\Programs\Python\Python36-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 2178, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 570, in error
    return self._call_chain(*args)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 418:


...
<end of log>
```

---

### Example URLs:
- Single video: https://www.iwara.tv/videos/woqbjs38viyyz57w
- Single video: https://ecchi.iwara.tv/videos/yrjv4uvrmc0vy8j8

---

### Description of your *issue*, suggested solution and other information

When I try to download any video on iwara.tv, I get an error saying "ERROR: unable to download video data: HTTP Error 418:" (nothing follows the colon) and youtube-dl doesn't download the files. I want to be able to download videos again. Usually, I batch-download them.
 
It had been working until a ~4 days ago, which coincides with an update to iwara, though the admin didn't specify what was changed. This might just be a coincidence, though.

I'm using Python version 2.7.14 on Windows 10. I tried dstftw's and AlexAplin's modified iwara extractors, too, but it didn't fix the problem.
