### ISSUE TITLE
[Site support request] blackpills.com

### ISSUE THREAD

**Issue by cassidyrps** [rg3/youtube-dl#17037]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.07.21*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.07.21**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://player.blackpills.com/episode/dab314be9f24cc21b087d5f508c34ed498536854e13']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.07.10
[debug] Python version 2.7.10 (CPython) - Darwin-15.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.2, ffprobe 3.2, rtmpdump 2.4
[debug] Proxy map: {}
[generic] dab314be9f24cc21b087d5f508c34ed498536854e13: Requesting header
WARNING: Falling back on generic information extractor.
[generic] dab314be9f24cc21b087d5f508c34ed498536854e13: Downloading webpage
[generic] dab314be9f24cc21b087d5f508c34ed498536854e13: Extracting information
ERROR: Unsupported URL: https://player.blackpills.com/episode/dab314be9f24cc21b087d5f508c34ed498536854e13
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2298, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2542, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2531, in _XML
    parser.feed(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 9, column 14
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 502, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3258, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://player.blackpills.com/episode/dab314be9f24cc21b087d5f508c34ed498536854e13
```

---

- Single video: https://player.blackpills.com/episode/dab314be9f24cc21b087d5f508c34ed498536854e13
- Playlist: https://player.blackpills.com/series/dab312cbe017eb303a039c6b34644a86071c779292d

---

### Description of your *issue*, suggested solution and other information

Would love Blackpills support. Thanks!

**Comment by ryvec** [comment]
blackpills is easy to rip from: look for m3u8 in network analyzer, and download with ffmpeg
