### ISSUE TITLE
[Site support request] kocowa.com

### ISSUE THREAD

**Issue by cassidyrps** [rg3/youtube-dl#17030]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.07.10*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.07.10**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.kocowa.com/episode/tempted-episode-1/842290']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.07.10
[debug] Python version 2.7.10 (CPython) - Darwin-15.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.2, ffprobe 3.2, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 842290: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 842290: Downloading webpage
[generic] 842290: Extracting information
ERROR: Unsupported URL: https://www.kocowa.com/episode/tempted-episode-1/842290
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2298, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2542, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2531, in _XML
    parser.feed(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: mismatched tag: line 28, column 2
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 502, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3258, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.kocowa.com/episode/tempted-episode-1/842290

```

---

- Single video: https://www.kocowa.com/episode/tempted-episode-1/842290

---

### Description of your *issue*, suggested solution and other information

Would love Kocowa support. Thanks!

**Comment by Anvithlobo** [comment]
```

youtube-dl.exe https://www.kocowa.com/episode/episode-itemepisodenumber/1081443 -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.kocowa.com/episode/episode-itemepisodenumber/1081443', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.09.08
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg N-91500-g3870ed7ab3
[debug] Proxy map: {}
[generic] 1081443: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 1081443: Downloading webpage
[generic] 1081443: Extracting information
ERROR: Unsupported URL: https://www.kocowa.com/episode/episode-itemepisodenumber/1081443
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpork090uw\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpork090uw\build\youtube_dl\extractor\common.py", line 502, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpork090uw\build\youtube_dl\extractor\generic.py", line 3298, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.kocowa.com/episode/episode-itemepisodenumber/1081443

```

- Single video: https://www.kocowa.com/episode/episode-itemepisodenumber/1081443
- Playlist: https://www.kocowa.com/series/hi-school-love-on/1081437

Its is Geo-restricted to USA  (not sure about what other countries it operates in) 
It does need a premium account for few series / episodes but rest are free to watch with ads

**Comment by Gosokan** [comment]
is it possible to add support for this site, with only using the manifest.mpd url?  This manifest url is not geo restricted, like single video or playlist url as mentioned in the Anvithlobo post above. Because if I embed mpd manifest url to html5 player on my blog, anyone can play this video without geo restricted.

**Comment by zackmark29** [comment]
Is there any progress about this request? 
Kocowa is really great
