### ISSUE TITLE
Implement support for Real.video site 

### ISSUE THREAD

**Issue by ZaxonXP** [rg3/youtube-dl#17058]
Current version crashes when trying to download some video.

user@localhost:~$ youtube-dl https://www.real.video/5813274279001
[generic] 5813274279001: Requesting header
WARNING: Could not send HEAD request to https://www.real.video/5813274279001: HTTP Error 403: Forbidden
[generic] 5813274279001: Downloading webpage
WARNING: Falling back on generic information extractor.
[generic] 5813274279001: Extracting information
[download] Downloading playlist: Online censorship is a WAR against human KNOWLEDGE and human CIVILIZATION - Real.Video
[generic] playlist Online censorship is a WAR against human KNOWLEDGE and human CIVILIZATION - Real.Video: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[brightcove:new] 5813274279001: Downloading webpage
[brightcove:new] 5813274279001: Downloading JSON metadata
[brightcove:new] 5813274279001: Downloading m3u8 information
[brightcove:new] 5813274279001: Downloading m3u8 information
[brightcove:new] 5813274279001: Downloading m3u8 information
[brightcove:new] 5813274279001: Downloading m3u8 information
[brightcove:new] 5813274279001: Downloading MPD manifest
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl", line 11, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.5/site-packages/youtube_dl/__init__.py", line 472, in main
    _real_main(argv)
  File "/home/user/.local/lib/python3.5/site-packages/youtube_dl/__init__.py", line 462, in _real_main
    retcode = ydl.download(all_urls)
  File "/home/user/.local/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 2001, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/home/user/.local/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 803, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/user/.local/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 1002, in process_ie_result
    extra_info=extra)
  File "/home/user/.local/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 864, in process_ie_result
    extra_info=extra_info)
  File "/home/user/.local/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/home/user/.local/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 503, in extract
    ie_result = self._real_extract(url)
  File "/home/user/.local/lib/python3.5/site-packages/youtube_dl/extractor/brightcove.py", line 734, in _real_extract
    json_data, video_id, headers=headers)
  File "/home/user/.local/lib/python3.5/site-packages/youtube_dl/extractor/brightcove.py", line 585, in _parse_brightcove_metadata
    formats.extend(self._extract_mpd_formats(src, video_id, 'dash', fatal=False))
  File "/home/user/.local/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 1883, in _extract_mpd_formats
    formats_dict=formats_dict, mpd_url=mpd_url)
  File "/home/user/.local/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 2039, in _parse_mpd_formats
    'Bandwidth': bandwidth,
ValueError: unsupported format character 'D' (0x44) at index 335

**Comment by ZaxonXP** [comment]
The crash was from latest version: `youtube-dl --version -> 2018.05.18`

**Comment by dstftw** [comment]
It's not latest.
