### ISSUE TITLE
(crunchyroll) Can't extract title on python 2.x

### ISSUE THREAD

**Issue by bato3** [rg3/youtube-dl#17069]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.07.21*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.07.21**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
```
youtube-dl http://www.crunchyroll.com/media-774793 -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['http://www.crunchyroll.com/media-774793', '-v']
[debug] Encodings: locale cp1250, fs mbcs, out cp852, pref cp1250
[debug] youtube-dl version 2018.07.21
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg 4.0, ffprobe 4.0, phantomjs 2.1.1
[debug] Proxy map: {}
[Crunchyroll] 774793: Downloading webpage
ERROR: This is a sample clip. To watch the full video, start a free trial today!; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpphie_b_3\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpphie_b_3\build\youtube_dl\extractor\common.py", line 502, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpphie_b_3\build\youtube_dl\extractor\crunchyroll.py", line 426, in _real_extract
youtube_dl.utils.ExtractorError: This is a sample clip. To watch the full video, start a free trial today!; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
```
python -m youtube_dl http://www.crunchyroll.com/media-774793 -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'http://www.crunchyroll.com/media-774793', u'-v']
[debug] Encodings: locale cp1250, fs mbcs, out cp852, pref cp1250
[debug] youtube-dl version 2018.07.10
[debug] Git HEAD: fda2aa630
[debug] Python version 2.7.14 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg 4.0, ffprobe 4.0, phantomjs 2.1.1
[debug] Proxy map: {}
[crunchyroll:playlist] media-774793: Downloading webpage
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "youtube_dl\extractor\common.py", line 502, in extract
    ie_result = self._real_extract(url)
  File "youtube_dl\extractor\crunchyroll.py", line 615, in _real_extract
    webpage, 'title')
  File "youtube_dl\extractor\common.py", line 981, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "youtube_dl\extractor\common.py", line 972, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
```
youtube-dl http://www.crunchyroll.com/media-774793 --proxy PRIVATE -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'http://www.crunchyroll.com/media-774793', u'--proxy', u'PRIVATE', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.07.21
[debug] Python version 2.7.13 (CPython) - Linux-4.9.0-6-amd64-x86_64-with-debian-9.4
[debug] exe versions: ffmpeg 3.2.11-1, ffprobe 3.2.11-1, phantomjs 2.1.1
[debug] Proxy map: {PRIVATE}
[crunchyroll:playlist] media-774793: Downloading webpage
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 502, in extract
    ie_result = self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/crunchyroll.py", line 615, in _real_extract
    webpage, 'title')
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 981, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 972, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

---

### Description of your *issue*, suggested solution and other information

When is used 2.7.x (CPython) extractor can't find title

**Comment by bato3** [comment]
Reason was, that `http://www.crunchyroll.com/media-774793` was valid for `CrunchyrollIE` and `CrunchyrollShowPlaylistIE`, and in this case was used `CrunchyrollShowPlaylistIE`
