### ISSUE TITLE
 Premium can not download vdo

### ISSUE THREAD

**Issue by tachitjusom** [rg3/youtube-dl#17064]
C:\Users\Win10x64_Bit\Desktop\youtub-dl>youtube-dl -u xxxxxx@gmail.com -p xxxx751 -v https://www.monomaxxx.com/asia-movies-series/detail/450028889_Bringiton,GhostEP.3.html?page=3&type=thai
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-u', 'PRIVATE', '-p', 'PRIVATE', '-v', 'https://www.monomaxxx.com/asia-movies-series/detail/450028889_Bringiton,GhostEP.3.html?page=3']
[debug] Encodings: locale cp874, fs mbcs, out cp874, pref cp874
[debug] youtube-dl version 2018.06.19
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg N-91330-ga990184007, ffprobe N-91330-ga990184007
[debug] Proxy map: {}
[generic] 450028889_Bringiton,GhostEP.3: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 450028889_Bringiton,GhostEP.3: Downloading webpage
[generic] 450028889_Bringiton,GhostEP.3: Extracting information
ERROR: Unsupported URL: https://www.monomaxxx.com/asia-movies-series/detail/450028889_Bringiton,GhostEP.3.html?page=3
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp3niajf93\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp3niajf93\build\youtube_dl\extractor\common.py", line 501, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp3niajf93\build\youtube_dl\extractor\generic.py", line 3263, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.monomaxxx.com/asia-movies-series/detail/450028889_Bringiton,GhostEP.3.html?page=3

**Comment by bato3** [comment]
generic extractor don't support login
instead provide cookies: https://github.com/rg3/youtube-dl#how-do-i-pass-cookies-to-youtube-dl

**Comment by tachitjusom** [comment]
how to export my cookies

**Comment by tachitjusom** [comment]
@bato3  i try with "youtube-dl --cookies cookies.txt -v https://www.monomaxxx.com/asia-movies-series/detail/450028888_Bringiton,GhostEP.2.html?page=2"
but not working
