### ISSUE TITLE
Facebook video credential issues

### ISSUE THREAD

**Issue by bobflem** [rg3/youtube-dl#17072]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.07.21*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.07.21**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl https://www.facebook.com/umadidiot/videos/2018895471454904/ --username XXXXX --p
assword XXXXX -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.facebook.com/umadidiot/videos/2018895471454904/', '--username', 'PRIVATE', '--password', 'PRIVATE', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.07.21
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg N-91273-g67747c89ad, ffprobe N-89803-g856b7cae9f
[debug] Proxy map: {}
[facebook] Downloading login page
[facebook] Logging in
[facebook] 2018895471454904: Downloading webpage
[facebook] 2018895471454904: Downloading webpage
[facebook] 2018895471454904: Downloading webpage
ERROR: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpphie_b_3\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpphie_b_3\build\youtube_dl\extractor\common.py", line 502, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpphie_b_3\build\youtube_dl\extractor\facebook.py", line 469, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpphie_b_3\build\youtube_dl\extractor\facebook.py", line 378, in _extract_from_url
youtube_dl.utils.ExtractorError: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

Downloading private videos using credentials does not work. It appears that any facebook video that has /video/ in the url doesn't work when using user credentials, even public videos. The same public video that won't work when using credentials will work when you don't supply credentials. If the private video is shared, and you use the shared post link to try and download the video (/posts/), while using credentials, the video downloads. Example:

Public video: https://www.facebook.com/severeweatherEU/videos/2292036711019417/
Downloading without credentials works. Downloading with credentials fails. If you find someone who has shared this video, take their share link and try to download that with credentials, it downloads fine.

Here are two outputs. The first one is me trying to download the public video with credentials:

```
.\youtube-dl.exe https://www.facebook.com/severeweatherEU/videos/2292036711019417/ --username XXXXX --password XXXXX -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.facebook.com/severeweatherEU/videos/2292036711019417/', '--username', 'PRIVATE', '--password', 'PRIVATE', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.07.21
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg N-91273-g67747c89ad, ffprobe N-89803-g856b7cae9f
[debug] Proxy map: {}
[facebook] Downloading login page
[facebook] Logging in
[facebook] 2292036711019417: Downloading webpage
[facebook] 2292036711019417: Downloading webpage
[facebook] 2292036711019417: Downloading webpage
ERROR: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpphie_b_3\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpphie_b_3\build\youtube_dl\extractor\common.py", line 502, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpphie_b_3\build\youtube_dl\extractor\facebook.py", line 469, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpphie_b_3\build\youtube_dl\extractor\facebook.py", line 378, in _extract_from_url
youtube_dl.utils.ExtractorError: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
The second one is me trying to download the video through somebody's public share link:
```
.\youtube-dl.exe https://www.facebook.com/nna.emeka.37/posts/2837814706444325 --username XXXXX --password XXXXX -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.facebook.com/nna.emeka.37/posts/2837814706444325', '--username', 'PRIVATE', '--password', 'PRIVATE', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.07.21
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg N-91273-g67747c89ad, ffprobe N-89803-g856b7cae9f
[debug] Proxy map: {}
[facebook] Downloading login page
[facebook] Logging in
[facebook] 2837814706444325: Downloading webpage
WARNING: unable to extract thumbnail URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://video.ford4-1.fna.fbcdn.net/v/t42.1790-2/37830536_2094712210776830_2193482189394411520_n.mp4?_nc_cat=0&efg=eyJ2ZW5jb2RlX3RhZyI6ImRhc2hfdjRfcGFzc3Rocm91Z2hfZnJhZ18yX3ZpZGVvIn0=&oh=4aedba9e9afdbc237b0561e7d74dda16&oe=5B5AB0C3'
[download] Destination: Facebook video #2837814706444325-2837814706444325.f2094712200776831vd.mp4
[download] 100% of 651.80KiB in 00:00
[debug] Invoking downloader on 'https://video.ford4-1.fna.fbcdn.net/v/t42.1790-2/37788864_897446893777062_5998358511073886208_n.mp4?_nc_cat=0&efg=eyJ2ZW5jb2RlX3RhZyI6ImRhc2hfdjRfcGFzc3Rocm91Z2hfZnJhZ18yX2F1ZGlvIn0=&oh=f6c8b964bbb0f1e5aa1100711f8b856b&oe=5B5AB18D'
[download] Destination: Facebook video #2837814706444325-2837814706444325.f897446880443730ad.m4a
[download] 100% of 76.92KiB in 00:00
[ffmpeg] Merging formats into "Facebook video #2837814706444325-2837814706444325.mp4"
[debug] ffmpeg command line: ffmpeg -y -i "file:Facebook video #2837814706444325-2837814706444325.f2094712200776831vd.mp4" -i "file:Facebook video #2837814706444325-2837814706444325.f897446880443730ad.m4a" -c copy -map "0:v:0" -map "1:a:0" "file:Facebook video #2837814706444325-2837814706444325.temp.mp4"
Deleting original file Facebook video #2837814706444325-2837814706444325.f2094712200776831vd.mp4 (pass -k to keep)
Deleting original file Facebook video #2837814706444325-2837814706444325.f897446880443730ad.m4a (pass -k to keep)
```

First method doesn't work, second one works.

**Comment by bobflem** [comment]
Duplicate of which issue exactly? I searched and didn't find one that was related to this.
