### ISSUE TITLE
[site-support-request] maoritelevision.com

### ISSUE THREAD

**Issue by T-jw** [rg3/youtube-dl#17081]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.07.21*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.07.21**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl -v -f "best[height <=? 1080]" 'https://www.maoritelevision.com/tv/shows/tongue-tied/S01E001/tongue-tied-series-1-episode-1'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--no-mtime', '--sub-lang=de', '-f', 'best[height <=? 720]', '-v', '-f', 'best[height <=? 1080]', 'https://www.maoritelevision.com/tv/shows/tongue-tied/S01E001/tongue-tied-series-1-episode-1']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.07.21
[debug] Python version 3.6.6 (CPython) - Linux-4.1.52-1-MANJARO-i686-with-arch-Manjaro-Linux
[debug] exe versions: ffmpeg 4.0.1, ffprobe 4.0.1, phantomjs 18, rtmpdump 2.4
[debug] Proxy map: {}
[generic] tongue-tied-series-1-episode-1: Requesting header
WARNING: Falling back on generic information extractor.
[generic] tongue-tied-series-1-episode-1: Downloading webpage
[generic] tongue-tied-series-1-episode-1: Extracting information
ERROR: Unsupported URL: https://www.maoritelevision.com/tv/shows/tongue-tied/S01E001/tongue-tied-series-1-episode-1
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 502, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3259, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.maoritelevision.com/tv/shows/tongue-tied/S01E001/tongue-tied-series-1-episode-1
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.maoritelevision.com/tv/shows/tongue-tied/S01E001/tongue-tied-series-1-episode-1
- Playlist [required login]: https://www.maoritelevision.com/user/playlists

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

- This url does not work: https://www.maoritelevision.com/tv/shows/tongue-tied/S01E001/tongue-tied-series-1-episode-1
- This url _does_ work: https://www.maoritelevision.com/tv/shows/tongue-tied/S01E002/tongue-tied-series-1-episode-2

**Comment by Stuntaneous** [comment]
+1

https://www.maoritelevision.com/shows/te-araroa-tales-trails/on-demand 
-- series 1, all but episode 5 worked and 5 later worked spontaneously
-- series 2, episode 1 worked and others failed

**Comment by Richienb** [comment]
Unsupported shows seem to be fetchable by finding the `m3u8` file that the website requests and piping that to the downloader.
