### ISSUE TITLE
parse Error on ted some links

### ISSUE THREAD

**Issue by design365** [rg3/youtube-dl#17106]
the link is :https://www.ted.com/talks/lina_marieth_hoyos_what_is_the_coldest_thing_in_the_world
and the extractor show error:

ERROR: An extractor error has occurred. (caused by KeyError(u'nativeDownloads',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 503, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/ted.py", line 131, in _real_extract
    return self._talk_info(url, name)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/ted.py", line 184, in _talk_info
    dict) or talk_info['nativeDownloads']
KeyError: u'nativeDownloads'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 516, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
ExtractorError: An extractor error has occurred. (caused by KeyError(u'nativeDownloads',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by design365** [comment]
thanks for your help, but now ,the parse result is M3U8 format , how can i get mp4 format?

**Comment by design365** [comment]
@dstftw thanks for your help, but now ,the parse result is M3U8 format , how can i get mp4 format?
