### ISSUE TITLE
URL not available from PBS with 2018.07.29

### ISSUE THREAD

**Issue by ManuelUrrutia** [rg3/youtube-dl#17109]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.07.29*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.07.29**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other
---

### Description of your *issue*, suggested solution and other information

PBS has "updated" its web site on or about midnight of July 29, 2018. Version 2018.05.18 could obtain videos' URL before that point in time. Update to freshly available current version (2018.07.29) was also unable to obtain URL. Therefore, it seems youtube-dl will have to be modified to adapt to the new scheme.

Here is the output with and without the verbose flag for a video that is available through their website player:

```
ComputerName:~UserName$ youtube-dl -g "https://www.pbs.org/video/secrets-dead-alcatraz-escape/"
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
ComputerName:~UserName$
ComputerName:~UserName$
ComputerName:~UserName$  youtube-dl --verbose "https://www.pbs.org/video/secrets-dead-alcatraz-escape/"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
debug] Command-line args: [u'--verbose', u'https://www.pbs.org/video/secrets-dead-alcatraz-escape/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.07.29
[debug] Python version 2.7.10 (CPython) - Darwin-15.6.0-x86_64-i386-64bit
[debug] exe versions: avconv 12.3, avprobe 12.3, ffmpeg 4.0.2, ffprobe 4.0.2, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Using fake IP 3.115.157.64 (US) as X-Forwarded-For.
[pbs] Downloading JSON metadata
[pbs] secrets-dead-alcatraz-escape: Downloading webpage
[pbs] secrets-dead-alcatraz-escape: Downloading widget/partnerplayer page
[pbs] secrets-dead-alcatraz-escape: Downloading portalplayer page
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 502, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/pbs.py", line 653, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1281, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

ComputerName:~UserName$ 
```

Unfortunately, I have no suggested solution other than to follow the process that solved this when the scheme was last changed on or about May 17, 2018 (solved in 2018.05.18). And prior to that, it happened on or about August 5, 2017 (solved in 2017.08.06). 

Thank you.

**Comment by ManuelUrrutia** [comment]
Thank you for solving the issue. 

Now to wait for the solution to show up in the downloadable...
