### ISSUE TITLE
Support for questod.co.uk

### ISSUE THREAD

**Issue by mjefferys** [rg3/youtube-dl#17124]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.07.29*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.07.29**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
michael@Caprica:~$ ./youtube-dl -v https://www.questod.co.uk/show/katie-price-my-crazy-life/video/everything-changes/EHD_210703B
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.questod.co.uk/show/katie-price-my-crazy-life/video/everything-changes/EHD_210703B']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.07.29
[debug] Python version 2.7.15rc1 (CPython) - Linux-4.4.0-17134-Microsoft-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.2-2, ffprobe 3.4.2-2
[debug] Proxy map: {}
[generic] EHD_210703B: Requesting header
WARNING: Falling back on generic information extractor.
[generic] EHD_210703B: Downloading webpage
[generic] EHD_210703B: Extracting information
ERROR: Unsupported URL: https://www.questod.co.uk/show/katie-price-my-crazy-life/video/everything-changes/EHD_210703B
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/extractor/generic.py", line 2299, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "./youtube-dl/youtube_dl/compat.py", line 2542, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "./youtube-dl/youtube_dl/compat.py", line 2531, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 5, column 58
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 502, in extract
    ie_result = self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/generic.py", line 3259, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.questod.co.uk/show/katie-price-my-crazy-life/video/everything-changes/EHD_210703B
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.questod.co.uk/show/katie-price-my-crazy-life/video/everything-changes/EHD_210703B

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Quest have launched a new site. It's brightcove video so should in theory be supported but because they are loading the video in a reactjs pop up thingy I think youtube-dl is missing it. I can't work out how to get direct to the video file so it would be great if it was added natively.

**Comment by oxhey** [comment]
I too would like to see this work. I would finally be able to get HD versions of their shows.

**Comment by torbs723** [comment]
Not too sure why the geo-restricted tag has been added to this. It's geo-restricted to a certain country like some of the other sites supported by youtube-dl and this isn't usually a reason not to add support for it.
