### ISSUE TITLE
PBS Video Stopped Working Again

### ISSUE THREAD

**Issue by wright546** [rg3/youtube-dl#17137]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.07.29**
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

- [x] Bug report (encountered problems with youtube-dl)

```
./youtube-dl -F https://www.pbs.org/video/separated-children-at-the-border-abt8su/
[pbs] Downloading JSON metadata
[pbs] separated-children-at-the-border-abt8su: Downloading webpage
[pbs] separated-children-at-the-border-abt8su: Downloading widget/partnerplayer page
[pbs] separated-children-at-the-border-abt8su: Downloading portalplayer page
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
SUN-T400 7:39am ~ >./youtube-dl -F "https://www.pbs.org/video/separated-children-at-the-border-abt8su/"
[pbs] Downloading JSON metadata
[pbs] separated-children-at-the-border-abt8su: Downloading webpage
[pbs] separated-children-at-the-border-abt8su: Downloading widget/partnerplayer page
[pbs] separated-children-at-the-border-abt8su: Downloading portalplayer page
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
SUN-T400 7:39am ~ >./youtube-dl -v -F "https://www.pbs.org/video/separated-children-at-the-border-abt8su/"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-F', u'https://www.pbs.org/video/separated-children-at-the-border-abt8su/']
[debug] Encodings: locale US-ASCII, fs US-ASCII, out US-ASCII, pref US-ASCII
[debug] youtube-dl version 2018.07.29
[debug] Python version 2.7.14 (CPython) - FreeBSD-11.1-RELEASE-p9-amd64-64bit-ELF
[debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2
[debug] Proxy map: {}
[debug] Using fake IP 3.247.188.48 (US) as X-Forwarded-For.
[pbs] Downloading JSON metadata
[pbs] separated-children-at-the-border-abt8su: Downloading webpage
[pbs] separated-children-at-the-border-abt8su: Downloading widget/partnerplayer page
[pbs] separated-children-at-the-border-abt8su: Downloading portalplayer page
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 502, in extract
    ie_result = self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/pbs.py", line 653, in _real_extract
    self._sort_formats(formats)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 1281, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output....
<end of log>
```

---

https://www.pbs.org/video/separated-children-at-the-border-abt8su/

---

It looks like PBS changed their website again and youtube-dl can no longer find any valid video formats. youtube-dl worked successfully on the PBS site last week, so the change PBS made must have been in the last 7 days. This has happened a couple of times in the past, #7565, #8499, and #16478.

**Comment by antika0n** [comment]
It just happened to me too. 

https://www.pbs.org/video/queens-nyc-ixejwj/

```
[pbs] Downloading JSON metadata
[pbs] queens-nyc-ixejwj: Downloading webpage
[pbs] queens-nyc-ixejwj: Downloading widget/partnerplayer page
[pbs] queens-nyc-ixejwj: Downloading portalplayer page
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
cross@lateralus:/DATA/video/tv/pbs/no_passport_required$ youtube-dl https://www.pbs.org/video/queens-nyc-ixejwj/
[pbs] Downloading JSON metadata
[pbs] queens-nyc-ixejwj: Downloading webpage
[pbs] queens-nyc-ixejwj: Downloading widget/partnerplayer page
[pbs] queens-nyc-ixejwj: Downloading portalplayer page
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
cross@lateralus:/DATA/video/tv/pbs/no_passport_required$ youtube-dl --verbose https://www.pbs.org/video/queens-nyc-ixejwj/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.pbs.org/video/queens-nyc-ixejwj/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.07.29
[debug] Python version 2.7.15rc1 (CPython) - Linux-4.15.0-23-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: avprobe 3.4.2-2, ffmpeg 3.4.2-2, ffprobe 3.4.2-2, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Using fake IP 3.78.1.53 (US) as X-Forwarded-For.
[pbs] Downloading JSON metadata
[pbs] queens-nyc-ixejwj: Downloading webpage
[pbs] queens-nyc-ixejwj: Downloading widget/partnerplayer page
[pbs] queens-nyc-ixejwj: Downloading portalplayer page
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 502, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/pbs.py", line 653, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1281, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by thesteveway** [comment]
It happened Monday, I believe

**Comment by yardenac** [comment]
I'm still seeing this issue...
