### ISSUE TITLE
Twitch VODs no longer downloadable

### ISSUE THREAD

**Issue by alph4numb3r** [rg3/youtube-dl#17135]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.07.29*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.07.29**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: ['--no-playlist', '--ignore-errors', '--mark-watched', '--hls-use-mpegts', '--continue', '--no-part', '--merge-output-format', 'mkv', '--write-sub', '--sub-lang', 'en', '--format', 'bestvideo[height<=?720]+bestaudio/best[height<=?720]/best', '--audio-format', 'mp3', '--cookies', 'S:\\Programs\\youtube-dl\\cookies.txt', '--add-metadata']
[debug] Custom config: []
[debug] Command-line args: ['https://www.twitch.tv/northernlion/video/291940395', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.01.21
[debug] Python version 3.5.1 (CPython) - Windows-10-10.0.17134-SP0
[debug] exe versions: ffmpeg N-83622-gdcd3418, ffprobe N-83622-gdcd3418
[debug] Proxy map: {}
[twitch:stream] northernlion: Downloading stream JSON
ERROR: northernlion is offline
Traceback (most recent call last):
  File "s:\programs\python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "s:\programs\python35\lib\site-packages\youtube_dl\extractor\common.py", line 438, in extract
    ie_result = self._real_extract(url)
  File "s:\programs\python35\lib\site-packages\youtube_dl\extractor\twitch.py", line 535, in _real_extract
    raise ExtractorError('%s is offline' % channel_id, expected=True)
youtube_dl.utils.ExtractorError: northernlion is offline
```

---

### Description of your *issue*, suggested solution and other information

Refuses to download VODs since the new Twitch update, citing "CHANNELNAME is offline"

**Comment by alph4numb3r** [comment]
Managed to download it manually by downloading `https://fastly.vod.hls.ttvnw.net/4ae604f8eba1e9f38f84_northernlion_29731669904_926899532/chunked/index-dvr.m3u8` with extra flags `--hls-prefer-native`
