### ISSUE TITLE
VVVVID not supported anymore

### ISSUE THREAD

**Issue by ppoe6** [rg3/youtube-dl#17162]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.08.04*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.08.04**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [x] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.vvvvid.it/#!channel/0/You/464834/video/cowboy-bebop-asteroid-blues-e01']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.08.04
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg N-91407-g3c4af577aa, ffprobe N-91407-g3c4af577aa
[debug] Proxy map: {}
[generic] cowboy-bebop-asteroid-blues-e01: Requesting header
WARNING: Falling back on generic information extractor.
[generic] cowboy-bebop-asteroid-blues-e01: Downloading webpage
[generic] cowboy-bebop-asteroid-blues-e01: Extracting information
ERROR: Unsupported URL: https://www.vvvvid.it/#!channel/0/You/464834/video/cowboy-bebop-asteroid-blues-e01
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpckoq891b\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpckoq891b\build\youtube_dl\extractor\common.py", line 502, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpckoq891b\build\youtube_dl\extractor\generic.py", line 3274, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.vvvvid.it/#!channel/0/You/464834/video/cowboy-bebop-asteroid-blues-e01
```

---

---

### Description of your *issue*, suggested solution and other information

The site VVVVID is in the list of supported sites but I can't download from it.
But seems that it's not supported anymore.

Could this issue be solved?

**Comment by federicorosso1993** [comment]
I was able to download
https://www.vvvvid.it/#!show/236/cowboy-bebop/226/464834/asteroid-blues
with youtube-dl.

**Comment by ppoe6** [comment]
I tried opening the link from another browser and it worked.

**Comment by ppoe6** [comment]
I don't know what's wrong. 
Now, opening the link with the same browser that worked before, it says again "unsupported url".

**Comment by ppoe6** [comment]
Any updates?
