### ISSUE TITLE
[facebook] Download Facebook authenticated only videos

### ISSUE THREAD

**Issue by PSlava** [rg3/youtube-dl#17171]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.08.04*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2018.08.04**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

bash-3.2$ ./youtube-dl https://www.facebook.com/Chefclubcocktailsuk/videos/1556391614435227/ --username MyUsername --password MyPassword -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.facebook.com/Chefclubcocktailsuk/videos/1556391614435227/', u'--username', u'PRIVATE', u'--password', u'PRIVATE', u'-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.08.04
[debug] Python version 2.7.10 (CPython) - Darwin-15.6.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[facebook] Downloading login page
[facebook] Logging in
[facebook] 1556391614435227: Downloading webpage
[facebook] 1556391614435227: Downloading webpage
[facebook] 1556391614435227: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "./youtube-dl/youtube_dl/extractor/common.py", line 599, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 2211, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

---

### Description of your *issue*, suggested solution and other information

When trying to download a private video on Facebook, even if the authentication is successful. This issue similar to closed #17050. But this fix doesn't work anymore.

**Comment by yousef-kas133** [comment]
I have the same issue

**Comment by affinityv** [comment]
$ youtube-dl -v --proxy socks5://127.0.0.1:9350 --netrc https://www.facebookcorewwwi.onion/InsidersABC/videos/544227449349547/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--proxy', u'socks5://127.0.0.1:9350', u'--netrc', u'https://www.facebookcorewwwi.onion/InsidersABC/videos/544227449349547/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.09.01
[debug] Python version 2.7.12 (CPython) - Linux-4.15.0-33-generic-x86_64-with-LinuxMint-18.3-sylvia
[debug] exe versions: avconv 2.8.15-0ubuntu0.16.04.1, avprobe 2.8.15-0ubuntu0.16.04.1, ffmpeg 2.8.15-0ubuntu0.16.04.1, ffprobe 2.8.15-0ubuntu0.16.04.1
[debug] Proxy map: {u'http': u'socks5://127.0.0.1:9350', u'https': u'socks5://127.0.0.1:9350'}
[facebook] Downloading login page
[facebook] Logging in
[facebook] 544227449349547: Downloading webpage
[facebook] 544227449349547: Downloading webpage
ERROR: This video is only available for registered users. Use --username and --password or --netrc to provide account credentials.
Traceback (most recent call last):
  File "/home/andrewm/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/home/andrewm/bin/youtube-dl/youtube_dl/extractor/common.py", line 502, in extract
    ie_result = self._real_extract(url)
  File "/home/andrewm/bin/youtube-dl/youtube_dl/extractor/facebook.py", line 471, in _real_extract
    video_id, fatal_if_no_video=True)
  File "/home/andrewm/bin/youtube-dl/youtube_dl/extractor/facebook.py", line 351, in _extract_from_url
    self.raise_login_required()
  File "/home/andrewm/bin/youtube-dl/youtube_dl/extractor/common.py", line 903, in raise_login_required
    expected=True)
ExtractorError: This video is only available for registered users. Use --username and --password or --netrc to provide account credentials.

I did have a more complex password that had spaces and many words (long), I changed by password to be more simple (still random letters and numbers and 30 characters), but it still fails

**Comment by affinityv** [comment]
There are no problems with fb over .onion address for videos that don't need a login.
