### ISSUE TITLE
[PornHub] Cannot download from PornHub with socks proxy half the time

### ISSUE THREAD

**Issue by huddlearoundyt** [rg3/youtube-dl#17174]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.08.04*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.08.04**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

I ran the same command twice and it failed the first time but succeeded the second time.

```
$ youtube-dl -v --proxy socks5://127.0.0.1:9050 https://www.pornhub.com/view_video.php?viewkey=ph57c89b5288aa3
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--proxy', u'socks5://127.0.0.1:9050', u'https://www.pornhub.com/view_video.php?viewkey=ph57c89b5288aa3']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.08.04
[debug] Python version 2.7.15rc1 (CPython) - Linux-4.15.0-29-generic-x86_64-with-LinuxMint-19-tara
[debug] exe versions: ffmpeg 3.4.2-2, ffprobe 3.4.2-2
[debug] Proxy map: {u'http': u'socks5://127.0.0.1:9050', u'https': u'socks5://127.0.0.1:9050'}
[PornHub] ph57c89b5288aa3: Downloading pc webpage
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 502, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/pornhub.py", line 164, in _real_extract
    webpage, 'title', group='title')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 972, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

```
$ youtube-dl -v --proxy socks5://127.0.0.1:9050 https://www.pornhub.com/view_video.php?viewkey=ph57c89b5288aa3
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--proxy', u'socks5://127.0.0.1:9050', u'https://www.pornhub.com/view_video.php?viewkey=ph57c89b5288aa3']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.08.04
[debug] Python version 2.7.15rc1 (CPython) - Linux-4.15.0-29-generic-x86_64-with-LinuxMint-19-tara
[debug] exe versions: ffmpeg 3.4.2-2, ffprobe 3.4.2-2
[debug] Proxy map: {u'http': u'socks5://127.0.0.1:9050', u'https': u'socks5://127.0.0.1:9050'}
[PornHub] ph57c89b5288aa3: Downloading pc webpage
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://cv.phncdn.com/videos/201609/01/88011871/720P_1500K_88011871.mp4?a5dcae8e1adc0bdaed975f0d61fb5e05756dc4acc488d2f9e61ef33953093512602c6cb1feb47dcafe6042f7cf3a22f478a9e1b9a2db1d1f165165b4b4061451f3e9ef11175c9c491eb9ed59e3bea3bdb93522de5a32328c359a434a0090a8d24eed9bd68abf383699b9d3e50065425b022deeca06c738c8a087'
```

The socks proxy at 127.0.0.1 port 9050 was running both times, and these two commands were run within 30 seconds of each other. Sometimes the download fails and sometimes it doesn't.

---

When downloading a channel, it downloads the pages and attempts to start downloading videos, but then it might fail:

```
$ youtube-dl -v --proxy socks5://127.0.0.1:9050 https://www.pornhub.com/channels/russian-tgirls/videos
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--proxy', u'socks5://127.0.0.1:9050', u'https://www.pornhub.com/channels/russian-tgirls/videos']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.08.04
[debug] Python version 2.7.15rc1 (CPython) - Linux-4.15.0-29-generic-x86_64-with-LinuxMint-19-tara
[debug] exe versions: ffmpeg 3.4.2-2, ffprobe 3.4.2-2
[debug] Proxy map: {u'http': u'socks5://127.0.0.1:9050', u'https': u'socks5://127.0.0.1:9050'}
[PornHubUserVideos] russian-tgirls: Downloading page 1
[PornHubUserVideos] russian-tgirls: Downloading page 2
[PornHubUserVideos] russian-tgirls: Downloading page 3
[download] Downloading playlist: russian-tgirls
[PornHubUserVideos] playlist russian-tgirls: Collected 42 video ids (downloading 42 of them)
[download] Downloading video 1 of 42
[PornHub] ph5add6a9028783: Downloading pc webpage
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 502, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/pornhub.py", line 164, in _real_extract
    webpage, 'title', group='title')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 972, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

---

When downloading user pages, it either collects the video IDs and then fails half the time _or_ it just collects zero video IDs:

```
$ youtube-dl -v --proxy socks5://127.0.0.1:9050 https://www.pornhub.com/users/danika_mori/videos/public
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--proxy', u'socks5://127.0.0.1:9050', u'https://www.pornhub.com/users/danika_mori/videos/public']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.08.04
[debug] Python version 2.7.15rc1 (CPython) - Linux-4.15.0-29-generic-x86_64-with-LinuxMint-19-tara
[debug] exe versions: ffmpeg 3.4.2-2, ffprobe 3.4.2-2
[debug] Proxy map: {u'http': u'socks5://127.0.0.1:9050', u'https': u'socks5://127.0.0.1:9050'}
[PornHubUserVideos] danika_mori: Downloading page 1
[download] Downloading playlist: danika_mori
[PornHubUserVideos] playlist danika_mori: Collected 0 video ids (downloading 0 of them)
[download] Finished downloading playlist: danika_mori
```

```
youtube-dl -v --proxy socks5://127.0.0.1:9050 https://www.pornhub.com/users/danika_mori/videos/public
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--proxy', u'socks5://127.0.0.1:9050', u'https://www.pornhub.com/users/danika_mori/videos/public']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.08.04
[debug] Python version 2.7.15rc1 (CPython) - Linux-4.15.0-29-generic-x86_64-with-LinuxMint-19-tara
[debug] exe versions: ffmpeg 3.4.2-2, ffprobe 3.4.2-2
[debug] Proxy map: {u'http': u'socks5://127.0.0.1:9050', u'https': u'socks5://127.0.0.1:9050'}
[PornHubUserVideos] danika_mori: Downloading page 1
[PornHubUserVideos] danika_mori: Downloading page 2
[PornHubUserVideos] danika_mori: Downloading page 3
[PornHubUserVideos] danika_mori: Downloading page 4
[download] Downloading playlist: danika_mori
[PornHubUserVideos] playlist danika_mori: Collected 151 video ids (downloading 151 of them)
[download] Downloading video 1 of 151
[PornHub] ph5b623e6371958: Downloading pc webpage
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://cv.phncdn.com/videos/201808/02/176928751/720P_1500K_176928751.mp4?a5dcae8e1adc0bdaed975f0d67fb5e0527c20903c5bb57a6cad7e6cb50bc41fbb1152c24e90eef01906ed343d2bfe65d71a6856a8946314a6832509dd0c3731c1935b0bf2fa6193fdeacd80bfc91a5be4ebc0b8f009bc418bc67a0269467e29110cd2413ea7e749be537181cad184b0855a80fe9f3b2c22944060d8c'
[download] Destination: Let's go to the kitchen, it's more easy to clean! - Caught sitting on a toy-ph5b623e6371958.mp4
[download]   0.5% of 118.33MiB at 170.23KiB/s ETA 11:48^C
ERROR: Interrupted by user
```

---

One time it collected fewer video IDs than it had before for the same URL:

```
$ youtube-dl -v --proxy socks5://127.0.0.1:9050 https://www.pornhub.com/users/danika_mori/videos/public
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--proxy', u'socks5://127.0.0.1:9050', u'https://www.pornhub.com/users/danika_mori/videos/public']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.08.04
[debug] Python version 2.7.15rc1 (CPython) - Linux-4.15.0-29-generic-x86_64-with-LinuxMint-19-tara
[debug] exe versions: ffmpeg 3.4.2-2, ffprobe 3.4.2-2
[debug] Proxy map: {u'http': u'socks5://127.0.0.1:9050', u'https': u'socks5://127.0.0.1:9050'}
[PornHubUserVideos] danika_mori: Downloading page 1
[PornHubUserVideos] danika_mori: Downloading page 2
[download] Downloading playlist: danika_mori
[PornHubUserVideos] playlist danika_mori: Collected 52 video ids (downloading 52 of them)
[download] Downloading video 1 of 52
[PornHub] ph5b623e6371958: Downloading pc webpage
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://cv.phncdn.com/videos/201808/02/176928751/720P_1500K_176928751.mp4?a5dcae8e1adc0bdaed975f0d67fb5e0527c20903c5bb57a6cad7e6cb50bc41fbb1152c24e90eef01906ed343d2bfe65d71a6856a8946314a6832509dd0c3731c1935b0bf2fa6193fdeacd80bfc91a5be4ebc0b8f009bc418bc67a0269467e29113c6201bea7e749b5f487f9ca5c0d25eff06d3001e5cb9611bd9bbbf'
[download] Destination: Let's go to the kitchen, it's more easy to clean! - Caught sitting on a toy-ph5b623e6371958.mp4
[download]   0.2% of 118.33MiB at 205.09KiB/s ETA 09:49^C
ERROR: Interrupted by user
```

Example URLs:
https://www.pornhub.com/view_video.php?viewkey=ph57c89b5288aa3
https://www.pornhub.com/view_video.php?viewkey=ph5b1e8b4218cbe
https://www.pornhub.com/view_video.php?viewkey=648719015

**Comment by dstftw** [comment]
Obviously your proxy fails or being served with captcha/stub page. Reproduce without proxy and post the output with `--dump-pages`.

**Comment by huddlearoundyt** [comment]
Reproduced without proxy and with `--dump-pages`.
