### ISSUE TITLE
New Ray Wenderlich

### ISSUE THREAD

**Issue by rickwierenga** [rg3/youtube-dl#17225]
Hi there,

I noticed that the raywenderlich.com extractor doesn't work with the new ray wenderlich website. I have already updated to the latest version (2018.08.04). I hope this could be fixed.

I didn't post an error message as I don't think it's useful because it simply doesn't work. If you need additional information, please ask.

Thanks in advance.

**Comment by ktkanishka** [comment]
Hi,
I recently purchased wenderlich account and could not download videos using youtube-dl. Please guide if anyone has done it. RayWenderlich is mentioned as a supported site in youtube-dl.

Thanks in advance.

**Comment by dstftw** [comment]
Authentication is not supported.

**Comment by ktkanishka** [comment]
youtube-dl -v -u "a@mail.com" -p testpassword  https://www.raywenderlich.com/4743-beginning-rxswift/lessons/1
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'https://www.raywenderlich.com/4743-beginning-rxswift/lessons/1']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.09.18
[debug] Python version 2.7.10 (CPython) - Darwin-17.3.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[RayWenderlich] 4743-beginning-rxswift/1: Downloading webpage
[RayWenderlich] 4743-beginning-rxswift/1: Downloading JSON metadata
[vimeo] Downloading login page
[vimeo] Logging in
ERROR: Unable to log in: bad username or password
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/vimeo.py", line 61, in _login
    'Referer': self._LOGIN_URL,
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 766, in _download_webpage
    expected_status=expected_status)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 632, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 617, in _request_webpage
    raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
ExtractorError: Unable to download webpage: HTTP Error 418: I'm a teapot (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 506, in extract
    self.initialize()
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 410, in initialize
    self._real_initialize()
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/vimeo.py", line 463, in _real_initialize
    self._login()
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/vimeo.py", line 67, in _login
    expected=True)
ExtractorError: Unable to log in: bad username or password

**Comment by abhiperry** [comment]
Any update on this issue ?

**Comment by umammaulana** [comment]
got same error, any update?

**Comment by rickwierenga** [comment]
I can download a [free course](https://www.raywenderlich.com/3770-server-side-swift-with-kitura). Authentication is still unsupported however.

**Comment by umammaulana** [comment]
yes only free course can be downloaded, hope someone will fix this soon

**Comment by raunakv7** [comment]
Same issue
