### ISSUE TITLE
YouTube  content_html error

### ISSUE THREAD

**Issue by rshadow** [rg3/youtube-dl#17231]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.08.04*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.08.04**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--no-overwrites', '--no-progress', '--download-archive=/home/rubin/bin/youtube-dl.archive.txt', '--ignore-errors', '--rate-limit=512k', '--retries=1', '--buffer-size=16K', '--continue', '--prefer-free-formats', '--merge-output-format=mkv', '--add-metadata', '--output=/srv/media/music/Monstercat Release/Dubstep/%(title)s.%(ext)s', '--extract-audio', '--audio-format=mp3', '--no-post-overwrites', '--audio-quality=0', 'https://www.youtube.com/playlist?list=PLF5C76212C58C464A']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.05.18.1
[debug] Python version 3.5.3 - Linux-4.9.0-4-amd64-x86_64-with-debian-9.5
[debug] exe versions: ffmpeg 2.6.4, ffprobe 2.6.4
[debug] Proxy map: {}
[youtube:playlist] PLF5C76212C58C464A: Downloading webpage
[download] Downloading playlist: Dubstep
[youtube:playlist] PLF5C76212C58C464A: Downloading page #1
ERROR: 'content_html'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 771, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 923, in process_ie_result
    ie_entries, playliststart, playlistend))
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 272, in _entries
    content_html = more['content_html']
KeyError: 'content_html'
```

### Description of your *issue*, suggested solution and other information

Error while downloading playlist `https://www.youtube.com/playlist?list=PLF5C76212C58C464A`

**Comment by dstftw** [comment]
Post the output with `--dump-pages`.

**Comment by rshadow** [comment]
[log.txt](https://github.com/rg3/youtube-dl/files/2282909/log.txt)

**Comment by rshadow** [comment]
Reopen pls

**Comment by Elijas** [comment]
What worked for someone with this bug was to create a duplicate playlist with all of the original playlist videos inside, and then run the app on the new playlist

There are 12 closed issues, probably all are linked (search `content_html`), maybe there will be more solutions

**Comment by amcgregor** [comment]
Please see [this ongoing official support thread](https://support.google.com/youtube/thread/10329866). Google have, apparently, rolled out an update a few weeks back that proactively searches for advertisement blocking techniques, and seem to have implemented it in the ("safe" from a security perspective) assume everyone is guilty, only innocent if we can prove the ad is visible, approach. Thus automated clients not executing JavaScript will fail that check by default.  [My response](https://support.google.com/youtube/thread/10329866?hl=en&dark=1&msgid=55874094) has details about my setup, and some of the testing I have attempted, which has only solidified it as being AdBlock in-browser, and failure to execute JS in YouTube-DL's case.

**Comment by myt00seven** [comment]
Just try to upgrade to the latest version 2020.06.16.1. That solved my issue.

**Comment by a-y-u-s-h** [comment]
`sudo youtube-dl -U` works for me.
