### ISSUE TITLE
ABC iview download fails with "KeyError: 'playlist'"

### ISSUE THREAD

**Issue by bignose-debian** [rg3/youtube-dl#17232]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.08.04**

```
$ youtube-dl --version
2018.08.04
```

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

```
$ youtube-dl -v https://iview.abc.net.au/show/full-proof/series/1/video/ZW0299A001S00
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://iview.abc.net.au/show/full-proof/series/1/video/ZW0299A001S00']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.08.04
[debug] Python version 3.6.6 (CPython) - Linux-4.17.0-1-amd64-x86_64-with-debian-buster-sid
[debug] exe versions: ffmpeg 4.0.2-1, ffprobe 4.0.2-1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Using fake IP 1.132.235.155 (AU) as X-Forwarded-For.
[abc.net.au:iview] ZW0299A001S00: Downloading JSON metadata
ERROR: An extractor error has occurred. (caused by KeyError('playlist',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/bignose/youtube-dl/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 502, in extract
    ie_result = self._real_extract(url)
  File "/home/bignose/youtube-dl/lib/python3.6/site-packages/youtube_dl/extractor/abc.py", line 135, in _real_extract
    stream = next(s for s in video_params['playlist'] if s.get('type') in ('program', 'livestream'))
KeyError: 'playlist'
Traceback (most recent call last):
  File "/home/bignose/youtube-dl/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 502, in extract
    ie_result = self._real_extract(url)
  File "/home/bignose/youtube-dl/lib/python3.6/site-packages/youtube_dl/extractor/abc.py", line 135, in _real_extract
    stream = next(s for s in video_params['playlist'] if s.get('type') in ('program', 'livestream'))
KeyError: 'playlist'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bignose/youtube-dl/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/home/bignose/youtube-dl/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 515, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('playlist',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by mattym444** [comment]
I'm not a Youtube-dl programmer, but it has the same error for me as well. The show has only episodes 10 - 13 available. Maybe try manually pasting each episode into Youtube-dl?

**Comment by remitamine** [comment]
> This episode is no longer available in iview.
