### ISSUE TITLE
[nova.py] ValueError: substring not found

### ISSUE THREAD

**Issue by kibeb** [rg3/youtube-dl#17241]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.08.04*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.08.04**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)

---

```
>youtube-dl -v "http://tn.nova.cz/clanek/tajemstvi-ukryte-v-podzemi-specialni-nemocnice-v-prazske-krci.html#player_13260"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://tn.nova.cz/clanek/tajemstvi-ukryte-v-podzemi-specialni-nemocnice-v-prazske-krci.html#player_13260']
[debug] Encodings: locale cp1250, fs mbcs, out cp852, pref cp1250
[debug] youtube-dl version 2018.08.04
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg N-77715-gfc703f5, ffprobe N-77715-gfc703f5, rtmpdump 2.3
[debug] Proxy map: {}
[Nova] tajemstvi-ukryte-v-podzemi-specialni-nemocnice-v-prazske-krci: Downloading webpage
[Nova] tajemstvi-ukryte-v-podzemi-specialni-nemocnice-v-prazske-krci: Downloading config JSON
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpckoq891b\build\youtube_dl\__init__.py", line 472, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpckoq891b\build\youtube_dl\__init__.py", line 462, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpckoq891b\build\youtube_dl\YoutubeDL.py", line 2001, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpckoq891b\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpckoq891b\build\youtube_dl\extractor\common.py", line 502, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpckoq891b\build\youtube_dl\extractor\nova.py", line 138, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpckoq891b\build\youtube_dl\extractor\common.py", line 859, in _download_json
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpckoq891b\build\youtube_dl\extractor\common.py", line 843, in _download_json_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpckoq891b\build\youtube_dl\extractor\common.py", line 864, in _parse_json
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpckoq891b\build\youtube_dl\extractor\nova.py", line 138, in <lambda>
ValueError: substring not found
```

---

### Description of your *issue*, suggested solution and other information

youtube-dl doesn't work on Nova.cz sites anymore, always fails like above, here on URL http://tn.nova.cz/clanek/tajemstvi-ukryte-v-podzemi-specialni-nemocnice-v-prazske-krci.html#player_13260 which is one of the tests I found still working in a web browser.

The main site https://novaplus.nova.cz/ seems to be completely reworked.

Hopefully someone can fix this. Thanks in advance.

**Comment by kibeb** [comment]
Yes, d6ef8b4 seems to work fine on tn.nova.cz, but still fails on novaplus.nova.cz:
```
>python -m youtube_dl --no-check-certificate -v https://novaplus.nova.cz/porad/televizni-noviny/epizoda/18131-14-8-2018
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--no-check-certificate', u'-v', u'https://novaplus.nova.cz/porad/televizni-noviny/epizoda/18131-14-8-2018']
[debug] Encodings: locale cp1250, fs mbcs, out cp852, pref cp1250
[debug] youtube-dl version 2018.08.04
[debug] Python version 2.7.2 (CPython) - Windows-post2008Server-6.2.9200
[debug] exe versions: ffmpeg N-77715-gfc703f5, ffprobe N-77715-gfc703f5, rtmpdump 2.3
[debug] Proxy map: {}
[Nova] 18131-14-8-2018: Downloading webpage
ERROR: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "youtube_dl\extractor\common.py", line 502, in extract
    ie_result = self._real_extract(url)
  File "youtube_dl\extractor\nova.py", line 113, in _real_extract
    webpage, 'video id')
  File "youtube_dl\extractor\common.py", line 972, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
Thank you.
