### ISSUE TITLE
site-support request: techsnips.io

### ISSUE THREAD

**Issue by MatrixView** [rg3/youtube-dl#17279]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.08.04**
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Site support request (request for adding support for a new site)

---
youtube-dl -v "https://www.techsnips.io/en/playing/how-to-manage-arrays-in-powershell"

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.techsnips.io/en/playing/how-to-manage-arrays-in-powershell']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.08.04
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-89894-g18e2ac032e, ffprobe N-67388-g37425fc, phantomjs 2.1.1, rtmpdump 2.4-47-gc26c541
[debug] Proxy map: {}
[generic] how-to-manage-arrays-in-powershell: Requesting header
WARNING: Falling back on generic information extractor.
[generic] how-to-manage-arrays-in-powershell: Downloading webpage
[generic] how-to-manage-arrays-in-powershell: Extracting information
ERROR: Unsupported URL: https://www.techsnips.io/en/playing/how-to-manage-arrays-in-powershell
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpckoq891b\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpckoq891b\build\youtube_dl\extractor\common.py", line 502, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpckoq891b\build\youtube_dl\extractor\generic.py", line 3274, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.techsnips.io/en/playing/how-to-manage-arrays-in-powershell
```

---

...or a playlist by keyword:

https://www.techsnips.io/en/powershell1

**Comment by oznotes** [comment]
They have media folder on cloud front and player keys and location is generated after it is clicked and gets expired after player running ..

**Comment by MatrixView** [comment]
@stinkteeth Thank you! That works, great!

**Comment by stinkteeth** [comment]
All of the qualities in the page source have the 360p url, regardless of the labeling.  The higher qualities are requested via a separate call.
`https://www.techsnips.io/en/video/getNewSignedUrlForPlayer?video_url=https%3A%2F%2Fd34ymkuact6zup.cloudfront.net%2Fuploads%2Fmovie_stream%2Ffull_movie%2F281638%2FHow_to_Manage_Arrays_in_PowerShell_1210.mp4`
