### ISSUE TITLE
Site-supprt-request: dw.com

### ISSUE THREAD

**Issue by lemmy04** [rg3/youtube-dl#17281]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.08.04*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2018.08.04**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [X] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

---

```
[debug] System config: []
[debug] User config: [u'-o', u'%(title)s.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.dw.com/en/in-1968-warsaw-pact-troops-suppressed-the-prague-spring/a-45138213']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.08.04
[debug] Python version 2.7.13 (CPython) - Linux-4.4.143-65-default-x86_64-with-SuSE-42.3-x86_64
[debug] exe versions: ffmpeg 3.4.4, ffprobe 3.4.4, rtmpdump 2.4
[debug] Proxy map: {}
[dw:article] 45138213: Downloading webpage
ERROR: Unable to extract media url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 502, in extract
    ie_result = self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/dw.py", line 106, in _real_extract
    media_path = self._search_regex(r'href="([^"]+av-%s)"\s+class="overlayLink"' % media_id, webpage, 'media url')
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 972, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract media url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


---



---

dw.com stopped working again, according to past issues that site was supported at least twice.

**Comment by bato3** [comment]
@lemmy04 plaese change title to `[dw:article] extractor bug` or similar. DW has extractor, but it is borken now

**Comment by jorgesumle** [comment]
Using version 2020.07.28:
```
youtube-dl https://www.dw.com/de/nordkorea-lehnt-auslandshilfe-ab/a-54592149
[dw:article] 54592149: Downloading webpage
ERROR: An extractor error has occurred. (caused by KeyError('media_id')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
