### ISSUE TITLE
unable to download videos from Crunchyroll Premium

### ISSUE THREAD

**Issue by ergosteur** [rg3/youtube-dl#17343]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.08.22*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.08.22**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--cookies', '/ocean/atlantic/users/matt/cookies-crunchyroll.txt', 'http://www.crunchyroll.com/my-hero-academia/episode-58-special-episode-save-the-world-with-love-775777']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.08.22
[debug] Python version 3.4.2 (CPython) - Linux-4.9.0-0.bpo.6-amd64-x86_64-with-debian-8.11
[debug] exe versions: ffmpeg 2.8.15, ffprobe 2.8.15
[debug] Proxy map: {}
[Crunchyroll] 775777: Downloading webpage
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.4/dist-packages/youtube_dl/extractor/common.py", line 502, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.4/dist-packages/youtube_dl/extractor/crunchyroll.py", line 544, in _real_extract
    self._sort_formats(formats, ('height', 'width', 'tbr', 'fps'))
  File "/usr/local/lib/python3.4/dist-packages/youtube_dl/extractor/common.py", line 1281, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

### Description of your *issue*, suggested solution and other information

I am unable to download videos from crunchyroll.com as of 2018-08-26. This was working yesterday morning as my daily cron job was able to download the episode mentioned in the debug output above yesterday, 2018-06-25 around 7am EDT.  

I have attempted creating a new cookies.txt file using the cookies.txt extension for Chrome but to no avail. I can provide this file privately if credentials are required for testing.

**Comment by ratchetfreak** [comment]
I believe this is caused by crunchy's new html5 player. 

It removes the links to the resolutions used in crunchyroll.py line 460 and further.

The stream info is now instead in a line starting with `vilos.config.media` followed by a json containing a lot of what ends up in in youtube-dl's json output. No resolution info until you follow the url in the streams list.

I don't know how to force either the flash or the html5 player to appear. Other than that it is related to the VILOS_ROLLOUT cookie

attached is the file `--write-pages` dumped out. Line 421 is where the json with the stream info should be

[crunchyroll html5 sample.txt](https://github.com/rg3/youtube-dl/files/2333662/crunchyroll.html5.sample.txt)

**Comment by RGFRv2** [comment]
A idea to solve that ?

**Comment by remitamine** [comment]
wait for the next release.

**Comment by batestota** [comment]
It worked to download after the 01-09-2018 update but the latest episodes which available for premium user is not downloadable even if you login with your premium user 
example : if u try to download **### http://www.crunchyroll.com/boruto-naruto-next-generations/episode-70-the-other-side-of-anxiety-775200**  it will download
if you try to download **### http://www.crunchyroll.com/boruto-naruto-next-generations/episode-71-the-hardest-rock-in-the-world-775201** it will not download

**Comment by kseniasolo** [comment]
The new release doesn't change anything, I've got this error right now.

> ERROR: Wrong login info: HTTP Error 302: The HTTP server returned a redirect error that would lead to an infinite loop.

**Comment by kseniasolo** [comment]
The new release doesn't change anything, I've got this error right now.

> ERROR: Wrong login info: HTTP Error 302: The HTTP server returned a redirect error that would lead to an infinite loop. 

@remitamine
