### ISSUE TITLE
Youku download failure

### ISSUE THREAD

**Issue by robbiewu008** [rg3/youtube-dl#17380]
C:\BUILD\youtube>c:\Apps\youtube-dl.exe -f bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best https://v.youku.com/v_show/id_XNzM2NTAxNDAw.html --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best', 'https://v.youku.com/v_show/id_XNzM2NTAxNDAw.html', '--verbose']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2018.08.28
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg 3.4.2, ffprobe 3.4.2
[debug] Proxy map: {}
[youku] XNzM2NTAxNDAw: Retrieving cna info
[youku] XNzM2NTAxNDAw: Downloading JSON metadata
ERROR: Youku server reported error -6004: 客户端无权播放,201; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc4srko6s\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc4srko6s\build\youtube_dl\extractor\common.py", line 502, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc4srko6s\build\youtube_dl\extractor\youku.py", line 189, in _real_extract
youtube_dl.utils.ExtractorError: Youku server reported error -6004: 客户端无权播放,201; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

C:\BUILD\youtube>c:\Apps\youtube-dl.exe --version
2018.08.28

**Comment by ProgrammerAKL** [comment]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.09.01*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.09.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl -o "C:/Video/%(title)s.%(ext)s" "https://v.youku.com/v_show/id_XMzA5ODE5MzIxMg==.html?spm=0.8251843.0.0&f=51260620&o=1" --no-check-certificate --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-o', 'C:/Video/%(title)s.%(ext)s', 'https://v.youku
.com/v_show/id_XMzA5ODE5MzIxMg==.html?spm=0.8251843.0.0&f=51260620&o=1', '--no-c
heck-certificate', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.09.01
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[youku] XMzA5ODE5MzIxMg: Retrieving cna info
[youku] XMzA5ODE5MzIxMg: Downloading JSON metadata
ERROR: Youku server reported error -6004: 客户端无权播放,201; please report this issue
on https://yt-dl.org/bug . Make sure you are using the latest version; type  you
tube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and in
clude its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkzpz548c\bu
ild\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkzpz548c\bu
ild\youtube_dl\extractor\common.py", line 502, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkzpz548c\bu
ild\youtube_dl\extractor\youku.py", line 189, in _real_extract
youtube_dl.utils.ExtractorError: Youku server reported error -6004: 客户端无权播放,201;
 please report this issue on https://yt-dl.org/bug . Make sure you are using the
 latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with
 the --verbose flag and include its complete output.
...
<end of log>
```

---


---

### Description of your *issue*, suggested solution and other information


The video is definitely playable in a browser, although only when cookies are enabled.

**Comment by freeleefly** [comment]
- [x] Bug report (encountered problems with youtube-dl)
Can't downloading files from `Youku.com`

>youtube-dl --version
>2018.09.18

```
youtube-dl -v  https://v.youku.com/v_show/id_XMzc2MTc2NzYwOA==.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://v.youku.com/v_show/id_XMzc2MTc2NzYwOA==.html']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2018.09.18
[debug] Python version 3.5.3 (CPython) - Windows-10-10.0.17134-SP0
[debug] exe versions: ffmpeg N-85588-g6108805, ffprobe N-85588-g6108805
[debug] Proxy map: {}
[youku] XMzc2MTc2NzYwOA: Retrieving cna info
[youku] XMzc2MTc2NzYwOA: Downloading JSON metadata
ERROR: Youku server reported error -6004: 客户端无权播放,201; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "c:\python35\lib\site-packages\youtube_dl\extractor\common.py", line 507, in extract
    ie_result = self._real_extract(url)
  File "c:\python35\lib\site-packages\youtube_dl\extractor\youku.py", line 189, in _real_extract
    raise ExtractorError(msg)
youtube_dl.utils.ExtractorError: Youku server reported error -6004: 客户端无权播放,201; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by huichen90** [comment]
I have fix the bug

**Comment by pirate486743186** [comment]
it seams to be working now
