### ISSUE TITLE
[PornHub] Format and links for user pages have changed

### ISSUE THREAD

**Issue by mjolnir870** [rg3/youtube-dl#17388]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.08.28*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.08.28**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl.exe --no-mtime --no-playlist --playlist-reverse -i -w --ffmpeg-location "C:\Users\USERNAME\Apps\ffmpeg\bin\ffmpeg.exe" -f "bestvideo+bestaudio/best" --write-thumbnail --external-downloader C:\Users\USERNAME\Apps\aria2\64bit\aria2c.exe --external-downloader-args "--file-allocation=none -x 4 -k 1M" -o "V:\test\%(title)s_%(id)s.%(ext)s" -v https://www.pornhub.com/pornstar/jenny-blighe/videos/upload
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--no-mtime', '--no-playlist', '--playlist-reverse', '-i', '-w', '--ffmpeg-location', 'C:\\Users\\USERNAME\\Apps\\ffmpeg\\bin\\ffmpeg.exe', '-f', 'bestvideo+bestaudio/best', '--write-thumbnail', '--external-downloader', 'C:\\Users\\USERNAME\\Apps\\aria2\\64bit\\aria2c.exe', '--external-downloader-args', '--file-allocation=none -x 4 -k 1M', '-o', 'V:\\test\\%(title)s_%(id)s.%(ext)s', '-v', 'https://www.pornhub.com/pornstar/jenny-blighe/videos/upload']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.08.28
[debug] Python version 3.4.4 (CPython) - Windows-8.1-6.3.9600
[debug] exe versions: ffmpeg N-90960-gbcff983dc3, ffprobe N-90960-gbcff983dc3
[debug] Proxy map: {}
[generic] upload: Requesting header
WARNING: Falling back on generic information extractor.
[generic] upload: Downloading webpage
[generic] upload: Extracting information
[download] Downloading playlist: Porn Videos Uploaded by Pornstar Jenny Blighe | Pornhub
[generic] playlist Porn Videos Uploaded by Pornstar Jenny Blighe | Pornhub: Collected 2 video ids (downloading 2 of them)
[download] Downloading video 1 of 2
[debug] Invoking downloader on 'data:"+o+"; base64,"+i+"'
[download] Destination: V:\test\Porn Videos Uploaded by Pornstar Jenny Blighe _Pornhub (2)_upload-2.unknown_video
[download] 100% of 5.00B in 00:00
[download] Downloading video 2 of 2
[debug] Invoking downloader on 'data:"+o+";base64,"+i+"'
ERROR: Incorrect padding
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc4srko6s\build\youtube_dl\YoutubeDL.py", line 803, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc4srko6s\build\youtube_dl\YoutubeDL.py", line 1002, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc4srko6s\build\youtube_dl\YoutubeDL.py", line 857, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc4srko6s\build\youtube_dl\YoutubeDL.py", line 1635, in process_video_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc4srko6s\build\youtube_dl\YoutubeDL.py", line 1908, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc4srko6s\build\youtube_dl\YoutubeDL.py", line 1847, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc4srko6s\build\youtube_dl\downloader\common.py", line 364, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc4srko6s\build\youtube_dl\downloader\http.py", line 341, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc4srko6s\build\youtube_dl\downloader\http.py", line 109, in establish_connection
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpc4srko6s\build\youtube_dl\YoutubeDL.py", line 2211, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 1496, in data_open
  File "C:\Python\Python34\lib\base64.py", line 554, in decodebytes
binascii.Error: Incorrect padding
```

---

### Description of your *issue*, suggested solution and other information

It looks like PornHub has changed the formatting of user pages.

Old user page link: https://www.pornhub.com/users/jenny-blighe/videos/public
New user page link: https://www.pornhub.com/pornstar/jenny-blighe/videos/upload

The above debug log is for the new page link.

Also, the links for the new pages come in two different versions:  a "pornstar" version and a "model" version.

Pornstar version: [https://www.pornhub.com/_**pornstar**_/jenny-blighe/videos/upload](https://www.pornhub.com/pornstar/jenny-blighe/videos/upload)
Model version: [https://www.pornhub.com/_**model**_/jayndrea/videos/upload](https://www.pornhub.com/model/jayndrea/videos/upload)

**Comment by mjolnir870** [comment]
It looks like some users still use the old format, but the new formats above are being used for most verified user accounts from what I can tell.

**Comment by mjolnir870** [comment]
https://www.pornhub.com/blog/6401

PornHub's blog post about the changes. I don't think there's any information that I haven't shared, but just thought I'd throw this on the ticket.
