### ISSUE TITLE
Add support for Philo as MSO

### ISSUE THREAD

**Issue by jlick** [rg3/youtube-dl#17395]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.08.28*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.08.28**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.aetv.com/shows/the-first-48/season-17/episode-19', u'--cookies', u'cookies.txt']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.08.28
[debug] Python version 2.7.13 (CPython) - Linux-4.9.0-8-amd64-x86_64-with-debian-9.5
[debug] exe versions: ffmpeg 3.2.12-1, ffprobe 3.2.12-1
[debug] Proxy map: {}
[aenetworks] the-first-48/season-17/episode-19: Downloading webpage
[aenetworks] 1308825667564: Downloading JSON metadata
ERROR: This video is only available for users of participating TV providers. Use --ap-mso to specify Adobe Pass Multiple-system operator Identifier and --ap-username and --ap-password or --netrc to provide account credentials.
Traceback (most recent call last):
  File "/home/jlick/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/home/jlick/bin/youtube-dl/youtube_dl/extractor/common.py", line 502, in extract
    ie_result = self._real_extract(url)
  File "/home/jlick/bin/youtube-dl/youtube_dl/extractor/aenetworks.py", line 144, in _real_extract
    url, video_id, requestor_id, resource)
  File "/home/jlick/bin/youtube-dl/youtube_dl/extractor/adobepass.py", line 1409, in _extract_mvpd_auth
    raise_mvpd_required()
  File "/home/jlick/bin/youtube-dl/youtube_dl/extractor/adobepass.py", line 1374, in raise_mvpd_required
    'and --ap-username and --ap-password or --netrc to provide account credentials.', expected=True)
ExtractorError: This video is only available for users of participating TV providers. Use --ap-mso to specify Adobe Pass Multiple-system operator Identifier and --ap-username and --ap-password or --netrc to provide account credentials.
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.aetv.com/shows/the-first-48/season-17/episode-19 (When using Philo as activated service provider.)

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

I use the video streaming service Philo for channels such as A&E. I can also access A&E through my web browser by "signing in" with Philo as my service provider. After activation, I'm able to play videos that would normally be locked. In addition, Philo doesn't use a login and password to sign in but instead uses a one-time password sent to a mobile phone. 

Currently youtube-dl doesn't appear to support Philo as an MSO. Even if it did, the current code requires a login and password, which isn't used on Philo. I tried using youtube-dl with complete cookies and no authentication but it doesn't work. Please consider adding support for Philo as MSO for aetv.com as it is an increasingly popular "skinny bundle" streaming service.

Philo has a free trial available.

**Comment by Aniruddh-J** [comment]
I have added support for Philo in the repo I forked. I have submitted a pull request for this, too.

If you don't want to wait till the pull request is approved, you may go ahead and clone the forked repository in my account: https://github.com/Aniruddh-J/youtube-dl

You need to switch to Philo branch for Philo MSO support.

**Comment by Aniruddh-J** [comment]
I have added support for Philo in the repo I forked. I have submitted a pull request for this, too.

If you don't want to wait till the pull request is approved, you may go ahead and clone the forked repository in my account: https://github.com/Aniruddh-J/youtube-dl

You need to switch to Philo branch for Philo MSO support.

**Comment by dinki** [comment]
@Aniruddh-J Excuse my ignorance, but I'm wanting to try your Philo repo.  I've cloned it but I'm not sure what to do next.  

Do I have to build youtube-dl from the cloned repo?  Sorry to be so burdensome, but could you point me to something that tells me how to do this?   Really would like to use youtube-dl with Philo.  

Thanks!

**Comment by faizjamil** [comment]
This been merged yet? Asking cause I'm looking into watching content from A&E Networks using a trial of Philo

**Comment by jlick** [comment]
> This been merged yet?

No, you have to build your own youtube-dl with the pull-request added (which is what I do) or use one of the custom forks that is both updated and includes the pull. You can't use the above fork version as-is because the A&E extractor in it is outdated.

**Comment by llacb47** [comment]
@faizjamil it's been added to `https://github.com/yt-dlp/yt-dlp`

**Comment by faizjamil** [comment]
> @faizjamil it's been added to `https://github.com/yt-dlp/yt-dlp`

I see thanks.

In the case that I need to use Philo to authenticate to download an episode of a show on History Channel, how would I go about doing that?

I get this error in particular

>>> ERROR: This video is only available for users of participating TV providers. Use --ap-mso to specify Adobe Pass Multiple-system operator Identifier and --ap-username and --ap-password or --netrc to provide account credentials.

**Comment by jlick** [comment]
> In the case that I need to use Philo to authenticate to download an episode of a show on History Channel, how would I go about doing that?

Discovery channels (such as History) don't use MSO. Instead you need to authenticate on the channel web site in a web browser, export cookies to a cookies.txt file (there are extensions to do this), then use youtube-dl's "--cookies cookies.txt" option. To make this even more of a challenge, Discovery authentication tokens expire after about 15 minutes so you have to reload the page and export cookies for each download.

**Comment by sovrinbloc** [comment]
Any update on this? Downloaded the latest version of yt-dlp, tried to download first-48 episodes using extracted `--cookies` (Netscape) and also `--cookies-from-browser`. Neither of them give results. 

```
$ yt-dlp https://play.aetv.com/shows/the-first-48/season-22/episode-9 --cookies-from-browser chrome

[Cookies] Extracting cookies from chrome
[Cookies] Extracted 4169 cookies from chrome
[aenetworks] /shows/the-first-48/season-22/episode-9: Downloading JSON metadata
[aenetworks] 1984493635941: Downloading JSON metadata
[aenetworks] 1984493635941: Retrieving Session
ERROR: [aenetworks] shows/the-first-48/season-22/episode-9: This video is only available for users of participating TV providers. Use --ap-mso to specify Adobe Pass Multiple-system operator Identifier and --ap-username and --ap-password or --netrc to provide account credentials.
```

```
yt-dlp https://play.aetv.com/shows/the-first-48/season-22/episode-9 --cookies ${PWD}/c.txt
[aenetworks] /shows/the-first-48/season-22/episode-9: Downloading JSON metadata
[aenetworks] 1984493635941: Downloading JSON metadata
[aenetworks] 1984493635941: Retrieving Session
ERROR: [aenetworks] shows/the-first-48/season-22/episode-9: This video is only available for users of participating TV providers. Use --ap-mso to specify Adobe Pass Multiple-system operator Identifier and --ap-username and --ap-password or --netrc to provide account credentials.
```

**Comment by yemaozitw** [comment]
> I've also tried regular `--ap-mso Philo --ap-username <email>@gmail.com --netrc` and when it prompts for the code I have nothing to give it.

This works for me with current yt-dlp+Philo+A&E (cookies from Chrome): 
 --cookies cookies.txt --ap-mso=Philo --ap-username=<phone number> --ap-password=None

<phone number> is the Philo account registered 10 digit phone number (no leading 1, no dashes), e.g. 8085551212

If it asks for a code and you don't get one on your phone within a couple of minutes, just leave it blank and it'll probably work.

**Comment by 89z** [comment]
This isn't the YT-DLP repo.
