### ISSUE TITLE
Error while trying download with cookies. How to fix?

### ISSUE THREAD

**Issue by hasnogaems** [rg3/youtube-dl#17391]
```
F:\twitch download\bin>youtube-dl.exe --ffmpeg-location C:\Users\anonimous\Deskt
op\ffmpeg\ffmpeg-20180404-2accdd3-win64-static\ffmpeg-20180404-2accdd3-win64-sta
tic\bin --cookies 'F:/twitch download/bin/cookies.txt' --hls-prefer-native https
://cdn-video.pvgna.com/782/original-1487910128-1080p/1080p.m3u8
WARNING: The url doesn't specify the protocol, trying with http
[generic] cookies: Requesting header
WARNING: Could not send HEAD request to http://download/bin/cookies.txt': <urlop
en error [Errno 11004] getaddrinfo failed>
[generic] cookies: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [Errno 11004] getaddrinfo fail
ed> (caused by URLError(gaierror(11004, 'getaddrinfo failed'),))
Traceback (most recent call last):
  File "C:\Python\Python34\lib\urllib\request.py", line 1183, in do_open
  File "C:\Python\Python34\lib\http\client.py", line 1137, in request
  File "C:\Python\Python34\lib\http\client.py", line 1182, in _send_request
  File "C:\Python\Python34\lib\http\client.py", line 1133, in endheaders
  File "C:\Python\Python34\lib\http\client.py", line 963, in _send_output
  File "C:\Python\Python34\lib\http\client.py", line 898, in send
  File "C:\Python\Python34\lib\http\client.py", line 871, in connect
  File "C:\Python\Python34\lib\socket.py", line 498, in create_connection
  File "C:\Python\Python34\lib\socket.py", line 537, in getaddrinfo
socket.gaierror: [Errno 11004] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpl1klaw4y\bu
ild\youtube_dl\extractor\common.py", line 503, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpl1klaw4y\bu
ild\youtube_dl\YoutubeDL.py", line 2177, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpl1klaw4y\bu
ild\youtube_dl\utils.py", line 930, in http_open
  File "C:\Python\Python34\lib\urllib\request.py", line 1185, in do_open
urllib.error.URLError: <urlopen error [Errno 11004] getaddrinfo failed>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpl1klaw4y\bu
ild\youtube_dl\YoutubeDL.py", line 776, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpl1klaw4y\bu
ild\youtube_dl\extractor\common.py", line 434, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpl1klaw4y\bu
ild\youtube_dl\extractor\generic.py", line 2043, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpl1klaw4y\bu
ild\youtube_dl\extractor\common.py", line 512, in _request_webpage
youtube_dl.utils.ExtractorError: Unable to download webpage: <urlopen error [Err
no 11004] getaddrinfo failed> (caused by URLError(gaierror(11004, 'getaddrinfo f
ailed'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpl1klaw4y\bu
ild\youtube_dl\__init__.py", line 455, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpl1klaw4y\bu
ild\youtube_dl\YoutubeDL.py", line 1967, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpl1klaw4y\bu
ild\youtube_dl\YoutubeDL.py", line 787, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpl1klaw4y\bu
ild\youtube_dl\YoutubeDL.py", line 848, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpl1klaw4y\bu
ild\youtube_dl\YoutubeDL.py", line 799, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpl1klaw4y\bu
ild\youtube_dl\YoutubeDL.py", line 604, in report_error
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpl1klaw4y\bu
ild\youtube_dl\YoutubeDL.py", line 574, in trouble
youtube_dl.utils.DownloadError: ERROR: Unable to download webpage: <urlopen erro
r [Errno 11004] getaddrinfo failed> (caused by URLError(gaierror(11004, 'getaddr
info failed'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpl1klaw4y\bu
ild\youtube_dl\__init__.py", line 465, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpl1klaw4y\bu
ild\youtube_dl\__init__.py", line 458, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpl1klaw4y\bu
ild\youtube_dl\YoutubeDL.py", line 545, in __exit__
  File "C:\Python\Python34\lib\http\cookiejar.py", line 2068, in save
OSError: [Errno 22] Invalid argument: "'F:/twitch"
```

**Comment by dstftw** [comment]
Stop posting duplicates. I've already pointed out: **it's not possible with cookies alone**. You must mimic browser's behavior exactly. It's not possible without writing separate extractor.
