### ISSUE TITLE
Failed youtube login

### ISSUE THREAD

**Issue by Shigeto1** [rg3/youtube-dl#17401]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.08.28*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.08.28**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### Log
```
/home/shigeto/bin/youtube-dl -vvv -f bestvideo+bestaudio/best --netrc --ignore-config --ignore-errors -c --user-agent "Mozilla/5.0 (Windows NT 6.1; rv:52.0) Gecko/20100101 Firefox/52.0" --add-metadata --external-downloader aria2c --external-downloader-args "-j 16 -x 16 -s 16 -k 1M" --download-archive ~/files/Archive/logs/ydlfancamarchive.txt --merge-output-format mkv -o '~/files/Archive/Downloaded/[%(upload_date)s] - %(uploader)s - %(title)s___%(id)s.%(ext)s' https://www.youtube.com/playlist?list=PLFx04tuShoP7t3u3xzotMMD480_gjncHc
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-vvv', u'-f', u'bestvideo+bestaudio/best', u'--netrc', u'--ignore-config', u'--ignore-errors', u'-c', u'--user-agent', u'Mozilla/5.0 (Windows NT 6.1; rv:52.0) Gecko/20100101 Firefox/52.0', u'--add-metadata', u'--external-downloader', u'aria2c', u'--external-downloader-args', u'-j 16 -x 16 -s 16 -k 1M', u'--download-archive', u'/home/shigeto/files/Archive/logs/ydlfancamarchive.txt', u'--merge-output-format', u'mkv', u'-o', u'~/files/Archive/Downloaded/[%(upload_date)s] - %(uploader)s - %(title)s___%(id)s.%(ext)s', u'https://www.youtube.com/playlist?list=PLFx04tuShoP7t3u3xzotMMD480_gjncHc']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.08.28
[debug] Python version 2.7.14 (CPython) - Linux-4.14.40-gentoo-whatbox-x86_64-Intel-R-_Xeon-R-_CPU_E5-2699_v3_@_2.30GHz-with-gentoo-2.4.1
[debug] exe versions: ffmpeg 4.0.2, ffprobe 4.0.2
[debug] Proxy map: {}
[youtube:playlist] Downloading login page
[youtube:playlist] Looking up account info
[youtube:playlist] Logging in
WARNING: Unable to login: Invalid password
[youtube:playlist] PLFx04tuShoP7t3u3xzotMMD480_gjncHc: Downloading webpage
ERROR: This playlist is private, use --username or --netrc to access it.
Traceback (most recent call last):
  File "/home/shigeto/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/home/shigeto/bin/youtube-dl/youtube_dl/extractor/common.py", line 502, in extract
    ie_result = self._real_extract(url)
  File "/home/shigeto/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 2397, in _real_extract
    has_videos, playlist = self._extract_playlist(playlist_id)
  File "/home/shigeto/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 2320, in _extract_playlist
    raise ExtractorError(message, expected=True)
ExtractorError: This playlist is private, use --username or --netrc to access it.
...
<end of log>
```

### Description of your *issue*, suggested solution and other information

Logging into Youtube isn't working, worked perfect not long ago. The credentials work fine via browser and I don't have 2-factor enabled. I was using version 2018.08.XX originally which worked fine until now but updated to 2018.08.28 and got the same thing. I was using -u and -p but changed to --netrc for the purpose of logging. Appears to be a duplicate of #10140

**Comment by Shigeto1** [comment]
I'm not sure why this was closed as the duplicate issue was similarly closed without ever being addressed. Nothing has changed with my configuration which means it can only be caused by a change on Youtube's end and/or the youtube-dl extractor needing an update.
