### ISSUE TITLE
[crunchyroll] Better (best) selection + language swith

### ISSUE THREAD

**Issue by bato3** [rg3/youtube-dl#17431]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.09.01*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.09.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

```
 http://www.crunchyroll.com/oneroom/episode-4-hanasaka-yui-is-near-me-774694 -F
[crunchyroll] 774694: Downloading webpage
[crunchyroll] 774694: Downloading enUS m3u8 information
[crunchyroll] 774694: Downloading arME m3u8 information
[crunchyroll] 774694: Downloading deDE m3u8 information
[crunchyroll] 774694: Downloading ruRU m3u8 information
[crunchyroll] 774694: Downloading frFR m3u8 information
[crunchyroll] 774694: Downloading ptBR m3u8 information
[crunchyroll] 774694: Downloading itIT m3u8 information
[crunchyroll] 774694: Downloading esES m3u8 information
[crunchyroll] 774694: Downloading esLA m3u8 information
[crunchyroll] 774694: Downloading jaJP m3u8 information
[crunchyroll] 774694: Downloading media info
[info] Available formats for 774694:
format code      extension  resolution note
hls-jaJP-387-0   mp4        428x240    [jaJP]  387k , avc1.42c015, 23.974fps, mp4a.40.2
hls-jaJP-387-1   mp4        428x240    [jaJP]  387k , avc1.42c015, 23.974fps, mp4a.40.2
hls-jaJP-387-2   mp4        428x240    [jaJP]  387k , avc1.42c015, 23.974fps, mp4a.40.2
hls-arME-392-0   mp4        428x240    [jaJP]  392k , avc1.42c015, 23.974fps, mp4a.40.2
hls-arME-392-1   mp4        428x240    [jaJP]  392k , avc1.42c015, 23.974fps, mp4a.40.2
hls-arME-392-2   mp4        428x240    [jaJP]  392k , avc1.42c015, 23.974fps, mp4a.40.2
hls-ruRU-392-0   mp4        428x240    [jaJP]  392k , avc1.42c015, 23.974fps, mp4a.40.2
hls-ruRU-392-1   mp4        428x240    [jaJP]  392k , avc1.42c015, 23.974fps, mp4a.40.2
hls-ruRU-392-2   mp4        428x240    [jaJP]  392k , avc1.42c015, 23.974fps, mp4a.40.2
hls-ptBR-393-0   mp4        428x240    [jaJP]  393k , avc1.42c015, 23.974fps, mp4a.40.2
hls-ptBR-393-1   mp4        428x240    [jaJP]  393k , avc1.42c015, 23.974fps, mp4a.40.2
hls-ptBR-393-2   mp4        428x240    [jaJP]  393k , avc1.42c015, 23.974fps, mp4a.40.2
hls-frFR-393-0   mp4        428x240    [jaJP]  393k , avc1.42c015, 23.974fps, mp4a.40.2
hls-frFR-393-1   mp4        428x240    [jaJP]  393k , avc1.42c015, 23.974fps, mp4a.40.2
hls-frFR-393-2   mp4        428x240    [jaJP]  393k , avc1.42c015, 23.974fps, mp4a.40.2
hls-esES-394-0   mp4        428x240    [jaJP]  394k , avc1.42c015, 23.974fps, mp4a.40.2
hls-esES-394-1   mp4        428x240    [jaJP]  394k , avc1.42c015, 23.974fps, mp4a.40.2
hls-esES-394-2   mp4        428x240    [jaJP]  394k , avc1.42c015, 23.974fps, mp4a.40.2
hls-esLA-394-0   mp4        428x240    [jaJP]  394k , avc1.42c015, 23.974fps, mp4a.40.2
hls-esLA-394-1   mp4        428x240    [jaJP]  394k , avc1.42c015, 23.974fps, mp4a.40.2
hls-esLA-394-2   mp4        428x240    [jaJP]  394k , avc1.42c015, 23.974fps, mp4a.40.2
hls-enUS-394-0   mp4        428x240    [jaJP]  394k , avc1.42c015, 23.974fps, mp4a.40.2
hls-enUS-394-1   mp4        428x240    [jaJP]  394k , avc1.42c015, 23.974fps, mp4a.40.2
hls-enUS-394-2   mp4        428x240    [jaJP]  394k , avc1.42c015, 23.974fps, mp4a.40.2
hls-deDE-395-0   mp4        428x240    [jaJP]  395k , avc1.42c015, 23.974fps, mp4a.40.2
hls-deDE-395-1   mp4        428x240    [jaJP]  395k , avc1.42c015, 23.974fps, mp4a.40.2
hls-deDE-395-2   mp4        428x240    [jaJP]  395k , avc1.42c015, 23.974fps, mp4a.40.2
hls-itIT-395-0   mp4        428x240    [jaJP]  395k , avc1.42c015, 23.974fps, mp4a.40.2
hls-itIT-395-1   mp4        428x240    [jaJP]  395k , avc1.42c015, 23.974fps, mp4a.40.2
hls-itIT-395-2   mp4        428x240    [jaJP]  395k , avc1.42c015, 23.974fps, mp4a.40.2
hls-jaJP-489-0   mp4        640x360    [jaJP]  489k , avc1.4d401e, 23.974fps, mp4a.40.2
hls-jaJP-489-1   mp4        640x360    [jaJP]  489k , avc1.4d401e, 23.974fps, mp4a.40.2
hls-jaJP-489-2   mp4        640x360    [jaJP]  489k , avc1.4d401e, 23.974fps, mp4a.40.2
hls-deDE-491-0   mp4        640x360    [jaJP]  491k , avc1.4d401e, 23.974fps, mp4a.40.2
hls-deDE-491-1   mp4        640x360    [jaJP]  491k , avc1.4d401e, 23.974fps, mp4a.40.2
hls-deDE-491-2   mp4        640x360    [jaJP]  491k , avc1.4d401e, 23.974fps, mp4a.40.2
hls-arME-491-0   mp4        640x360    [jaJP]  491k , avc1.4d401e, 23.974fps, mp4a.40.2
hls-arME-491-1   mp4        640x360    [jaJP]  491k , avc1.4d401e, 23.974fps, mp4a.40.2
hls-arME-491-2   mp4        640x360    [jaJP]  491k , avc1.4d401e, 23.974fps, mp4a.40.2
hls-ptBR-491-0   mp4        640x360    [jaJP]  491k , avc1.4d401e, 23.974fps, mp4a.40.2
hls-ptBR-491-1   mp4        640x360    [jaJP]  491k , avc1.4d401e, 23.974fps, mp4a.40.2
hls-ptBR-491-2   mp4        640x360    [jaJP]  491k , avc1.4d401e, 23.974fps, mp4a.40.2
hls-esLA-492-0   mp4        640x360    [jaJP]  492k , avc1.4d401e, 23.974fps, mp4a.40.2
hls-esLA-492-1   mp4        640x360    [jaJP]  492k , avc1.4d401e, 23.974fps, mp4a.40.2
hls-esLA-492-2   mp4        640x360    [jaJP]  492k , avc1.4d401e, 23.974fps, mp4a.40.2
hls-enUS-492-0   mp4        640x360    [jaJP]  492k , avc1.4d401e, 23.974fps, mp4a.40.2
hls-enUS-492-1   mp4        640x360    [jaJP]  492k , avc1.4d401e, 23.974fps, mp4a.40.2
hls-enUS-492-2   mp4        640x360    [jaJP]  492k , avc1.4d401e, 23.974fps, mp4a.40.2
hls-ruRU-493-0   mp4        640x360    [jaJP]  493k , avc1.4d401e, 23.974fps, mp4a.40.2
hls-ruRU-493-1   mp4        640x360    [jaJP]  493k , avc1.4d401e, 23.974fps, mp4a.40.2
hls-ruRU-493-2   mp4        640x360    [jaJP]  493k , avc1.4d401e, 23.974fps, mp4a.40.2
hls-esES-493-0   mp4        640x360    [jaJP]  493k , avc1.4d401e, 23.974fps, mp4a.40.2
hls-esES-493-1   mp4        640x360    [jaJP]  493k , avc1.4d401e, 23.974fps, mp4a.40.2
hls-esES-493-2   mp4        640x360    [jaJP]  493k , avc1.4d401e, 23.974fps, mp4a.40.2
hls-frFR-493-0   mp4        640x360    [jaJP]  493k , avc1.4d401e, 23.974fps, mp4a.40.2
hls-frFR-493-1   mp4        640x360    [jaJP]  493k , avc1.4d401e, 23.974fps, mp4a.40.2
hls-frFR-493-2   mp4        640x360    [jaJP]  493k , avc1.4d401e, 23.974fps, mp4a.40.2
hls-itIT-493-0   mp4        640x360    [jaJP]  493k , avc1.4d401e, 23.974fps, mp4a.40.2
hls-itIT-493-1   mp4        640x360    [jaJP]  493k , avc1.4d401e, 23.974fps, mp4a.40.2
hls-itIT-493-2   mp4        640x360    [jaJP]  493k , avc1.4d401e, 23.974fps, mp4a.40.2
hls-jaJP-785-0   mp4        848x480    [jaJP]  785k , avc1.4d401f, 23.974fps, mp4a.40.2
hls-jaJP-785-1   mp4        848x480    [jaJP]  785k , avc1.4d401f, 23.974fps, mp4a.40.2
hls-jaJP-785-2   mp4        848x480    [jaJP]  785k , avc1.4d401f, 23.974fps, mp4a.40.2
hls-arME-793-0   mp4        848x480    [jaJP]  793k , avc1.4d401f, 23.974fps, mp4a.40.2
hls-arME-793-1   mp4        848x480    [jaJP]  793k , avc1.4d401f, 23.974fps, mp4a.40.2
hls-arME-793-2   mp4        848x480    [jaJP]  793k , avc1.4d401f, 23.974fps, mp4a.40.2
hls-ruRU-795-0   mp4        848x480    [jaJP]  795k , avc1.4d401f, 23.974fps, mp4a.40.2
hls-ruRU-795-1   mp4        848x480    [jaJP]  795k , avc1.4d401f, 23.974fps, mp4a.40.2
hls-ruRU-795-2   mp4        848x480    [jaJP]  795k , avc1.4d401f, 23.974fps, mp4a.40.2
hls-enUS-797-0   mp4        848x480    [jaJP]  797k , avc1.4d401f, 23.974fps, mp4a.40.2
hls-enUS-797-1   mp4        848x480    [jaJP]  797k , avc1.4d401f, 23.974fps, mp4a.40.2
hls-enUS-797-2   mp4        848x480    [jaJP]  797k , avc1.4d401f, 23.974fps, mp4a.40.2
hls-esLA-797-0   mp4        848x480    [jaJP]  797k , avc1.4d401f, 23.974fps, mp4a.40.2
hls-esLA-797-1   mp4        848x480    [jaJP]  797k , avc1.4d401f, 23.974fps, mp4a.40.2
hls-esLA-797-2   mp4        848x480    [jaJP]  797k , avc1.4d401f, 23.974fps, mp4a.40.2
hls-frFR-797-0   mp4        848x480    [jaJP]  797k , avc1.4d401f, 23.974fps, mp4a.40.2
hls-frFR-797-1   mp4        848x480    [jaJP]  797k , avc1.4d401f, 23.974fps, mp4a.40.2
hls-frFR-797-2   mp4        848x480    [jaJP]  797k , avc1.4d401f, 23.974fps, mp4a.40.2
hls-ptBR-798-0   mp4        848x480    [jaJP]  798k , avc1.4d401f, 23.974fps, mp4a.40.2
hls-ptBR-798-1   mp4        848x480    [jaJP]  798k , avc1.4d401f, 23.974fps, mp4a.40.2
hls-ptBR-798-2   mp4        848x480    [jaJP]  798k , avc1.4d401f, 23.974fps, mp4a.40.2
hls-esES-798-0   mp4        848x480    [jaJP]  798k , avc1.4d401f, 23.974fps, mp4a.40.2
hls-esES-798-1   mp4        848x480    [jaJP]  798k , avc1.4d401f, 23.974fps, mp4a.40.2
hls-esES-798-2   mp4        848x480    [jaJP]  798k , avc1.4d401f, 23.974fps, mp4a.40.2
hls-deDE-799-0   mp4        848x480    [jaJP]  799k , avc1.4d401f, 23.974fps, mp4a.40.2
hls-deDE-799-1   mp4        848x480    [jaJP]  799k , avc1.4d401f, 23.974fps, mp4a.40.2
hls-deDE-799-2   mp4        848x480    [jaJP]  799k , avc1.4d401f, 23.974fps, mp4a.40.2
hls-itIT-800-0   mp4        848x480    [jaJP]  800k , avc1.4d401f, 23.974fps, mp4a.40.2
hls-itIT-800-1   mp4        848x480    [jaJP]  800k , avc1.4d401f, 23.974fps, mp4a.40.2
hls-itIT-800-2   mp4        848x480    [jaJP]  800k , avc1.4d401f, 23.974fps, mp4a.40.2
hls-jaJP-1883-0  mp4        1280x720   [jaJP] 1883k , avc1.640028, 23.974fps, mp4a.40.2
hls-jaJP-1883-1  mp4        1280x720   [jaJP] 1883k , avc1.640028, 23.974fps, mp4a.40.2
hls-jaJP-1883-2  mp4        1280x720   [jaJP] 1883k , avc1.640028, 23.974fps, mp4a.40.2
hls-deDE-1897-0  mp4        1280x720   [jaJP] 1897k , avc1.640028, 23.974fps, mp4a.40.2
hls-deDE-1897-1  mp4        1280x720   [jaJP] 1897k , avc1.640028, 23.974fps, mp4a.40.2
hls-deDE-1897-2  mp4        1280x720   [jaJP] 1897k , avc1.640028, 23.974fps, mp4a.40.2
hls-ptBR-1898-0  mp4        1280x720   [jaJP] 1898k , avc1.640028, 23.974fps, mp4a.40.2
hls-ptBR-1898-1  mp4        1280x720   [jaJP] 1898k , avc1.640028, 23.974fps, mp4a.40.2
hls-ptBR-1898-2  mp4        1280x720   [jaJP] 1898k , avc1.640028, 23.974fps, mp4a.40.2
hls-arME-1899-0  mp4        1280x720   [jaJP] 1899k , avc1.640028, 23.974fps, mp4a.40.2
hls-arME-1899-1  mp4        1280x720   [jaJP] 1899k , avc1.640028, 23.974fps, mp4a.40.2
hls-arME-1899-2  mp4        1280x720   [jaJP] 1899k , avc1.640028, 23.974fps, mp4a.40.2
hls-ruRU-1900-0  mp4        1280x720   [jaJP] 1900k , avc1.640028, 23.974fps, mp4a.40.2
hls-ruRU-1900-1  mp4        1280x720   [jaJP] 1900k , avc1.640028, 23.974fps, mp4a.40.2
hls-ruRU-1900-2  mp4        1280x720   [jaJP] 1900k , avc1.640028, 23.974fps, mp4a.40.2
hls-frFR-1900-0  mp4        1280x720   [jaJP] 1900k , avc1.640028, 23.974fps, mp4a.40.2
hls-frFR-1900-1  mp4        1280x720   [jaJP] 1900k , avc1.640028, 23.974fps, mp4a.40.2
hls-frFR-1900-2  mp4        1280x720   [jaJP] 1900k , avc1.640028, 23.974fps, mp4a.40.2
hls-esES-1900-0  mp4        1280x720   [jaJP] 1900k , avc1.640028, 23.974fps, mp4a.40.2
hls-esES-1900-1  mp4        1280x720   [jaJP] 1900k , avc1.640028, 23.974fps, mp4a.40.2
hls-esES-1900-2  mp4        1280x720   [jaJP] 1900k , avc1.640028, 23.974fps, mp4a.40.2
hls-itIT-1901-0  mp4        1280x720   [jaJP] 1901k , avc1.640028, 23.974fps, mp4a.40.2
hls-itIT-1901-1  mp4        1280x720   [jaJP] 1901k , avc1.640028, 23.974fps, mp4a.40.2
hls-itIT-1901-2  mp4        1280x720   [jaJP] 1901k , avc1.640028, 23.974fps, mp4a.40.2
hls-enUS-1901-0  mp4        1280x720   [jaJP] 1901k , avc1.640028, 23.974fps, mp4a.40.2
hls-enUS-1901-1  mp4        1280x720   [jaJP] 1901k , avc1.640028, 23.974fps, mp4a.40.2
hls-enUS-1901-2  mp4        1280x720   [jaJP] 1901k , avc1.640028, 23.974fps, mp4a.40.2
hls-esLA-1901-0  mp4        1280x720   [jaJP] 1901k , avc1.640028, 23.974fps, mp4a.40.2
hls-esLA-1901-1  mp4        1280x720   [jaJP] 1901k , avc1.640028, 23.974fps, mp4a.40.2
hls-esLA-1901-2  mp4        1280x720   [jaJP] 1901k , avc1.640028, 23.974fps, mp4a.40.2
hls-deDE-3758-0  mp4        1920x1080  [jaJP] 3758k , avc1.640028, 23.974fps, mp4a.40.2
hls-deDE-3758-1  mp4        1920x1080  [jaJP] 3758k , avc1.640028, 23.974fps, mp4a.40.2
hls-deDE-3758-2  mp4        1920x1080  [jaJP] 3758k , avc1.640028, 23.974fps, mp4a.40.2
hls-jaJP-3762-0  mp4        1920x1080  [jaJP] 3762k , avc1.640028, 23.974fps, mp4a.40.2
hls-jaJP-3762-1  mp4        1920x1080  [jaJP] 3762k , avc1.640028, 23.974fps, mp4a.40.2
hls-jaJP-3762-2  mp4        1920x1080  [jaJP] 3762k , avc1.640028, 23.974fps, mp4a.40.2
hls-itIT-3763-0  mp4        1920x1080  [jaJP] 3763k , avc1.640028, 23.974fps, mp4a.40.2
hls-itIT-3763-1  mp4        1920x1080  [jaJP] 3763k , avc1.640028, 23.974fps, mp4a.40.2
hls-itIT-3763-2  mp4        1920x1080  [jaJP] 3763k , avc1.640028, 23.974fps, mp4a.40.2
hls-ptBR-3766-0  mp4        1920x1080  [jaJP] 3766k , avc1.640028, 23.974fps, mp4a.40.2
hls-ptBR-3766-1  mp4        1920x1080  [jaJP] 3766k , avc1.640028, 23.974fps, mp4a.40.2
hls-ptBR-3766-2  mp4        1920x1080  [jaJP] 3766k , avc1.640028, 23.974fps, mp4a.40.2
hls-arME-3768-0  mp4        1920x1080  [jaJP] 3768k , avc1.640028, 23.974fps, mp4a.40.2
hls-arME-3768-1  mp4        1920x1080  [jaJP] 3768k , avc1.640028, 23.974fps, mp4a.40.2
hls-arME-3768-2  mp4        1920x1080  [jaJP] 3768k , avc1.640028, 23.974fps, mp4a.40.2
hls-ruRU-3769-0  mp4        1920x1080  [jaJP] 3769k , avc1.640028, 23.974fps, mp4a.40.2
hls-ruRU-3769-1  mp4        1920x1080  [jaJP] 3769k , avc1.640028, 23.974fps, mp4a.40.2
hls-ruRU-3769-2  mp4        1920x1080  [jaJP] 3769k , avc1.640028, 23.974fps, mp4a.40.2
hls-esLA-3769-0  mp4        1920x1080  [jaJP] 3769k , avc1.640028, 23.974fps, mp4a.40.2
hls-esLA-3769-1  mp4        1920x1080  [jaJP] 3769k , avc1.640028, 23.974fps, mp4a.40.2
hls-esLA-3769-2  mp4        1920x1080  [jaJP] 3769k , avc1.640028, 23.974fps, mp4a.40.2
hls-esES-3769-0  mp4        1920x1080  [jaJP] 3769k , avc1.640028, 23.974fps, mp4a.40.2
hls-esES-3769-1  mp4        1920x1080  [jaJP] 3769k , avc1.640028, 23.974fps, mp4a.40.2
hls-esES-3769-2  mp4        1920x1080  [jaJP] 3769k , avc1.640028, 23.974fps, mp4a.40.2
hls-enUS-3770-0  mp4        1920x1080  [jaJP] 3770k , avc1.640028, 23.974fps, mp4a.40.2
hls-enUS-3770-1  mp4        1920x1080  [jaJP] 3770k , avc1.640028, 23.974fps, mp4a.40.2
hls-enUS-3770-2  mp4        1920x1080  [jaJP] 3770k , avc1.640028, 23.974fps, mp4a.40.2
hls-frFR-3779-0  mp4        1920x1080  [jaJP] 3779k , avc1.640028, 23.974fps, mp4a.40.2
hls-frFR-3779-1  mp4        1920x1080  [jaJP] 3779k , avc1.640028, 23.974fps, mp4a.40.2
hls-frFR-3779-2  mp4        1920x1080  [jaJP] 3779k , avc1.640028, 23.974fps, mp4a.40.2 (best)
```

---

### Description of your *issue*, suggested solution and other information

I suggest add `--lang` switch (with default `jaJP` value or ja+en) to download only preferred language or make `hls-jaJP-` `(best)` version. Now it is highest bitrate...

PS.: Is possible add also sub language to description? And remove space before coma (`3779k ,`)

**Comment by Osche42** [comment]
Definitely in favor of this. Until hat happens you could use "-f '(bestvideo[height<=720]+bestaudio/best[height<=720])[format_id*=jaJP]' "
This downloads the video file without any burn-in subtitles (at least it does for me)

**Comment by Wilma456** [comment]
@Osche42 Your argument give me this error:
```Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/jakob/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/home/jakob/bin/youtube-dl/youtube_dl/__init__.py", line 472, in main
  File "/home/jakob/bin/youtube-dl/youtube_dl/__init__.py", line 462, in _real_main
  File "/home/jakob/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2001, in download
  File "/home/jakob/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 803, in extract_info
  File "/home/jakob/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 857, in process_ie_result
  File "/home/jakob/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1596, in process_video_result
  File "/home/jakob/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1355, in build_format_selector
SyntaxError: Invalid format specification: Missing closing/opening brackets or parenthesis
	(bestvideo[height<=XYZ]+bestaudio/best[height<=XYZ)[format_id*=jaJP]
	                                                                    ^
```

**Comment by Osche42** [comment]
youtube-dl -f '(bestvideo[height<=720]+bestaudio/best[height<=720])[format_id*=jaJP]' --cookies cookies.txt http://www.crunchyroll.com/..... 
Works for me.
Did you add the ' ' apostrophes around the argument? 
It also relies on Crunchyroll naming the stream with burn-in subs "hls-jaJP-XXXX", so it's not really a good solution, in case CR just decides to change their naming scheme.
