### ISSUE TITLE
cannot convert video [fix it please]

### ISSUE THREAD

**Issue by AngerKingz** [rg3/youtube-dl#17476]
```
C:\Users\Angel\Desktop\testing file\downloadeeeeee>youtube-dl https://www.youtube.com/watch?v=geqZRB2-XlI
[youtube] geqZRB2-XlI: Downloading webpage
[youtube] geqZRB2-XlI: Downloading video info webpage
[youtube] geqZRB2-XlI: Downloading js player vflvABTsY
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "c:\users\angel\appdata\local\programs\python\python37-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1210, in _decrypt_signature
    video_id, player_url, s
  File "c:\users\angel\appdata\local\programs\python\python37-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1121, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "c:\users\angel\appdata\local\programs\python\python37-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1182, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "c:\users\angel\appdata\local\programs\python\python37-32\lib\site-packages\youtube_dl\extractor\common.py", line 972, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

C:\Users\Angel\Desktop\testing file\downloadeeeeee>
```

**Comment by Anvithlobo** [comment]
Duplicate Issue [#17457](https://github.com/rg3/youtube-dl/issues/17457)
