### ISSUE TITLE
cbs does not work with geo-verification-proxy - system hangs

### ISSUE THREAD

**Issue by justa9** [rg3/youtube-dl#17482]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.09.08*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.09.08**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-f', 'best', 'cbs:E8aYmGjxuQ5HFdZTwL_6CIckRtxvkAS3', '--geo-verification-proxy', 'XXX.XXX.XXX.XXX:XX', '--ignore-config']
[debug] Encodings: locale cp1253, fs mbcs, out cp1253, pref cp1253
[debug] youtube-dl version 2018.09.08
[debug] Python version 3.4.4 (CPython) - Windows-XP-5.1.2600-SP3
[debug] exe versions: ffmpeg 3.3, ffprobe N-82759-g1f5630a-Sherpya, phantomjs 1.9.8, rtmpdump 2.4
[debug] Proxy map: {}
[CBS] E8aYmGjxuQ5HFdZTwL_6CIckRtxvkAS3: Downloading XML
[CBS] E8aYmGjxuQ5HFdZTwL_6CIckRtxvkAS3: Downloading StreamPack SMIL data
[CBS] E8aYmGjxuQ5HFdZTwL_6CIckRtxvkAS3: Downloading RTMP SMIL data
ERROR: E8aYmGjxuQ5HFdZTwL_6CIckRtxvkAS3: Failed to parse XML  (caused by ParseError('not well-formed (invalid token): line 1, column 4',)); please report this issue on https://yt-d
l.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpork090uw\build\youtube_dl\extractor\common.py", line 816, in _parse_xml
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpork090uw\build\youtube_dl\compat.py", line 2513, in compat_etree_fromstring
  File "C:\Python\Python34\lib\xml\etree\ElementTree.py", line 1335, in XML
  File "<string>", line None
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 4
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpork090uw\build\youtube_dl\extractor\common.py", line 816, in _parse_xml
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpork090uw\build\youtube_dl\compat.py", line 2513, in compat_etree_fromstring
  File "C:\Python\Python34\lib\xml\etree\ElementTree.py", line 1335, in XML
  File "<string>", line None
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 4

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpork090uw\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpork090uw\build\youtube_dl\extractor\common.py", line 502, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpork090uw\build\youtube_dl\extractor\cbs.py", line 108, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpork090uw\build\youtube_dl\extractor\cbs.py", line 89, in _extract_video_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpork090uw\build\youtube_dl\extractor\cbs.py", line 82, in _extract_video_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpork090uw\build\youtube_dl\extractor\theplatform.py", line 40, in _extract_theplatform_smil
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpork090uw\build\youtube_dl\extractor\common.py", line 809, in _download_xml
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpork090uw\build\youtube_dl\extractor\common.py", line 793, in _download_xml_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpork090uw\build\youtube_dl\extractor\common.py", line 820, in _parse_xml
youtube_dl.utils.ExtractorError: E8aYmGjxuQ5HFdZTwL_6CIckRtxvkAS3: Failed to parse XML  (caused by ParseError('not well-formed (invalid token): line 1, column 4',)); please report
this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its
 complete output.


```

---

### Description of your *issue*, suggested solution and other information

CBS stopped working with a geo-verification proxy a couple of days ago (proxy removed from log, but it's working correctly with other sites). Issues does not appear to be OS-specific.

**Comment by remitamine** [comment]
most likely it a problem in the response from your proxy,
```
youtube-dl --geo-verification-proxy localhost:8080 cbs:E8aYmGjxuQ5HFdZTwL_6CIckRtxvkAS3
[CBS] E8aYmGjxuQ5HFdZTwL_6CIckRtxvkAS3: Downloading XML
[CBS] E8aYmGjxuQ5HFdZTwL_6CIckRtxvkAS3: Downloading StreamPack SMIL data
[CBS] E8aYmGjxuQ5HFdZTwL_6CIckRtxvkAS3: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[CBS] E8aYmGjxuQ5HFdZTwL_6CIckRtxvkAS3: Downloading RTMP SMIL data
[CBS] E8aYmGjxuQ5HFdZTwL_6CIckRtxvkAS3: Downloading JSON metadata
[download] Destination: The Late Late Show - 9_6_18 (Blake Griffin, Paul Feig, Demetri Martin)-E8aYmGjxuQ5HFdZTwL_6CIckRtxvkAS3.flv
[download]   1.0% of ~406.79MiB at 333.83KiB/s ETA 20:00
```
