### ISSUE TITLE
pluralsight not logging in

### ISSUE THREAD

**Issue by jrvjrv** [rg3/youtube-dl#17518]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.09.10*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.09.10**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

I have trouble now with a course that I successfully downloaded on Aug 14. I can't you tell which version I used successfully on Aug 14, but it would have been very recent. I update my youtuble-dl roughly weekly. The account is still current and I am able to view the course on-line.

On the login page is now a reCAPTCHA. That might be the problem.

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'--sleep-interval', u'45', u'--max-sleep-interval', u'90', u'--limit-rate', u'30K', u'-o', u'MWL%(autonumber)s %(title)s.%(ext)s', u'https://app.pluralsight.com/library/courses/angular-material/table-of-contents']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.09.10
[debug] Python version 2.7.15rc1 (CPython) - Linux-4.15.0-33-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.4-0ubuntu0.18.04.1, ffprobe 3.4.4-0ubuntu0.18.04.1
[debug] Proxy map: {}
[pluralsight:course] angular-material: Downloading JSON metadata
[download] Downloading playlist: Angular Material
[pluralsight:course] playlist Angular Material: Collected 62 video ids (downloading 62 of them)
[download] Downloading video 1 of 62
[pluralsight] Downloading login page
[pluralsight] Logging in
ERROR: Unable to log in; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/jrv/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/home/jrv/bin/youtube-dl/youtube_dl/extractor/common.py", line 501, in extract
    self.initialize()
  File "/home/jrv/bin/youtube-dl/youtube_dl/extractor/common.py", line 405, in initialize
    self._real_initialize()
  File "/home/jrv/bin/youtube-dl/youtube_dl/extractor/pluralsight.py", line 164, in _real_initialize
    self._login()
  File "/home/jrv/bin/youtube-dl/youtube_dl/extractor/pluralsight.py", line 211, in _login
    raise ExtractorError('Unable to log in')
ExtractorError: Unable to log in; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by jrvjrv** [comment]
As quick as the reCAPTCHA appeared on the pluralsight login screen, it is now gone and youtube-dl is working again. Who can explain it, who can tell you why?
