### ISSUE TITLE
Can't get Json from youtube

### ISSUE THREAD

**Issue by llwmagic** [rg3/youtube-dl#17525]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.09.10*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.09.10**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
C:\Users\kaifaniuB2\Desktop\youtube>ytb -v --proxy 127.0.0.1:1080 -J https://www.youtube.com/watch?v=Q4-jOuHO-z4
[debug] Override config: ['-v', '--proxy', '127.0.0.1:1080', '-J', 'https://www.youtube.com/watch?v=Q4-jOuHO-z4']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2018.09.10
[debug] Python version 3.4.0 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {'https': '127.0.0.1:1080', 'http': '127.0.0.1:1080'}
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the
 latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and
 include its complete output.
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\kaifaniuB2\Desktop\youtube\lib\urllib\request.py", line 1235, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "C:\Users\kaifaniuB2\Desktop\youtube\lib\http\client.py", line 1066, in request
    self._send_request(method, url, body, headers)
  File "C:\Users\kaifaniuB2\Desktop\youtube\lib\http\client.py", line 1104, in _send_request
    self.endheaders(body)
  File "C:\Users\kaifaniuB2\Desktop\youtube\lib\http\client.py", line 1062, in endheaders
    self._send_output(message_body)
  File "C:\Users\kaifaniuB2\Desktop\youtube\lib\http\client.py", line 907, in _send_output
    self.send(msg)
  File "C:\Users\kaifaniuB2\Desktop\youtube\lib\http\client.py", line 842, in send
    self.connect()
  File "C:\Users\kaifaniuB2\Desktop\youtube\lib\http\client.py", line 1206, in connect
    server_hostname=server_hostname)
  File "C:\Users\kaifaniuB2\Desktop\youtube\lib\ssl.py", line 344, in wrap_socket
    _context=self)
  File "C:\Users\kaifaniuB2\Desktop\youtube\lib\ssl.py", line 540, in __init__
    self.do_handshake()
  File "C:\Users\kaifaniuB2\Desktop\youtube\lib\ssl.py", line 767, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:598)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\kaifaniuB2\Desktop\youtube\youtube_dl\extractor\common.py", line 599, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "C:\Users\kaifaniuB2\Desktop\youtube\youtube_dl\YoutubeDL.py", line 2211, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "C:\Users\kaifaniuB2\Desktop\youtube\lib\urllib\request.py", line 455, in open
    response = self._open(req, data)
  File "C:\Users\kaifaniuB2\Desktop\youtube\lib\urllib\request.py", line 473, in _open
    '_open', req)
  File "C:\Users\kaifaniuB2\Desktop\youtube\lib\urllib\request.py", line 433, in _call_chain
    result = func(*args)
  File "C:\Users\kaifaniuB2\Desktop\youtube\youtube_dl\utils.py", line 1139, in https_open
    req, **kwargs)
  File "C:\Users\kaifaniuB2\Desktop\youtube\lib\urllib\request.py", line 1238, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:598)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\kaifaniuB2\Desktop\youtube\youtube_dl\extractor\youtube.py", line 1212, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\kaifaniuB2\Desktop\youtube\youtube_dl\extractor\youtube.py", line 1120, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "C:\Users\kaifaniuB2\Desktop\youtube\youtube_dl\extractor\common.py", line 761, in _download_webpage
    expected_status=expected_status)
  File "C:\Users\kaifaniuB2\Desktop\youtube\youtube_dl\extractor\youtube.py", line 264, in _download_webpage_handle
    *args, **compat_kwargs(kwargs))
  File "C:\Users\kaifaniuB2\Desktop\youtube\youtube_dl\extractor\common.py", line 627, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query
, expected_status=expected_status)
  File "C:\Users\kaifaniuB2\Desktop\youtube\youtube_dl\extractor\common.py", line 612, in _request_webpage
    raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
youtube_dl.utils.ExtractorError: Download of https://www.youtube.com/yts/jsbin/player_ias_remote_ux-vflpDjiQc/en_US/base
.js failed: <urlopen error EOF occurred in violation of protocol (_ssl.c:598)> (caused by URLError(SSLEOFError(8, 'EOF o
ccurred in violation of protocol (_ssl.c:598)'),))
 (caused by ExtractorError("Download of https://www.youtube.com/yts/jsbin/player_ias_remote_ux-vflpDjiQc/en_US/base.js f
ailed: <urlopen error EOF occurred in violation of protocol (_ssl.c:598)> (caused by URLError(SSLEOFError(8, 'EOF occurr
ed in violation of protocol (_ssl.c:598)'),))",)); please report this issue on https://yt-dl.org/bug . Make sure you are
 using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbos
e flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\kaifaniuB2\Desktop\youtube\lib\urllib\request.py", line 1235, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "C:\Users\kaifaniuB2\Desktop\youtube\lib\http\client.py", line 1066, in request
    self._send_request(method, url, body, headers)
  File "C:\Users\kaifaniuB2\Desktop\youtube\lib\http\client.py", line 1104, in _send_request
    self.endheaders(body)
  File "C:\Users\kaifaniuB2\Desktop\youtube\lib\http\client.py", line 1062, in endheaders
    self._send_output(message_body)
  File "C:\Users\kaifaniuB2\Desktop\youtube\lib\http\client.py", line 907, in _send_output
    self.send(msg)
  File "C:\Users\kaifaniuB2\Desktop\youtube\lib\http\client.py", line 842, in send
    self.connect()
  File "C:\Users\kaifaniuB2\Desktop\youtube\lib\http\client.py", line 1206, in connect
    server_hostname=server_hostname)
  File "C:\Users\kaifaniuB2\Desktop\youtube\lib\ssl.py", line 344, in wrap_socket
    _context=self)
  File "C:\Users\kaifaniuB2\Desktop\youtube\lib\ssl.py", line 540, in __init__
    self.do_handshake()
  File "C:\Users\kaifaniuB2\Desktop\youtube\lib\ssl.py", line 767, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:598)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\kaifaniuB2\Desktop\youtube\youtube_dl\extractor\common.py", line 599, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "C:\Users\kaifaniuB2\Desktop\youtube\youtube_dl\YoutubeDL.py", line 2211, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "C:\Users\kaifaniuB2\Desktop\youtube\lib\urllib\request.py", line 455, in open
    response = self._open(req, data)
  File "C:\Users\kaifaniuB2\Desktop\youtube\lib\urllib\request.py", line 473, in _open
    '_open', req)
  File "C:\Users\kaifaniuB2\Desktop\youtube\lib\urllib\request.py", line 433, in _call_chain
    result = func(*args)
  File "C:\Users\kaifaniuB2\Desktop\youtube\youtube_dl\utils.py", line 1139, in https_open
    req, **kwargs)
  File "C:\Users\kaifaniuB2\Desktop\youtube\lib\urllib\request.py", line 1238, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:598)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\kaifaniuB2\Desktop\youtube\youtube_dl\extractor\youtube.py", line 1212, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\kaifaniuB2\Desktop\youtube\youtube_dl\extractor\youtube.py", line 1120, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "C:\Users\kaifaniuB2\Desktop\youtube\youtube_dl\extractor\common.py", line 761, in _download_webpage
    expected_status=expected_status)
  File "C:\Users\kaifaniuB2\Desktop\youtube\youtube_dl\extractor\youtube.py", line 264, in _download_webpage_handle
    *args, **compat_kwargs(kwargs))
  File "C:\Users\kaifaniuB2\Desktop\youtube\youtube_dl\extractor\common.py", line 627, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query
, expected_status=expected_status)
  File "C:\Users\kaifaniuB2\Desktop\youtube\youtube_dl\extractor\common.py", line 612, in _request_webpage
    raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
youtube_dl.utils.ExtractorError: Download of https://www.youtube.com/yts/jsbin/player_ias_remote_ux-vflpDjiQc/en_US/base
.js failed: <urlopen error EOF occurred in violation of protocol (_ssl.c:598)> (caused by URLError(SSLEOFError(8, 'EOF o
ccurred in violation of protocol (_ssl.c:598)'),))
Traceback (most recent call last):
  File "C:\Users\kaifaniuB2\Desktop\youtube\lib\urllib\request.py", line 1235, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "C:\Users\kaifaniuB2\Desktop\youtube\lib\http\client.py", line 1066, in request
    self._send_request(method, url, body, headers)
  File "C:\Users\kaifaniuB2\Desktop\youtube\lib\http\client.py", line 1104, in _send_request
    self.endheaders(body)
  File "C:\Users\kaifaniuB2\Desktop\youtube\lib\http\client.py", line 1062, in endheaders
    self._send_output(message_body)
  File "C:\Users\kaifaniuB2\Desktop\youtube\lib\http\client.py", line 907, in _send_output
    self.send(msg)
  File "C:\Users\kaifaniuB2\Desktop\youtube\lib\http\client.py", line 842, in send
    self.connect()
  File "C:\Users\kaifaniuB2\Desktop\youtube\lib\http\client.py", line 1206, in connect
    server_hostname=server_hostname)
  File "C:\Users\kaifaniuB2\Desktop\youtube\lib\ssl.py", line 344, in wrap_socket
    _context=self)
  File "C:\Users\kaifaniuB2\Desktop\youtube\lib\ssl.py", line 540, in __init__
    self.do_handshake()
  File "C:\Users\kaifaniuB2\Desktop\youtube\lib\ssl.py", line 767, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:598)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\kaifaniuB2\Desktop\youtube\youtube_dl\extractor\common.py", line 599, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "C:\Users\kaifaniuB2\Desktop\youtube\youtube_dl\YoutubeDL.py", line 2211, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "C:\Users\kaifaniuB2\Desktop\youtube\lib\urllib\request.py", line 455, in open
    response = self._open(req, data)
  File "C:\Users\kaifaniuB2\Desktop\youtube\lib\urllib\request.py", line 473, in _open
    '_open', req)
  File "C:\Users\kaifaniuB2\Desktop\youtube\lib\urllib\request.py", line 433, in _call_chain
    result = func(*args)
  File "C:\Users\kaifaniuB2\Desktop\youtube\youtube_dl\utils.py", line 1139, in https_open
    req, **kwargs)
  File "C:\Users\kaifaniuB2\Desktop\youtube\lib\urllib\request.py", line 1238, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:598)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\kaifaniuB2\Desktop\youtube\youtube_dl\extractor\youtube.py", line 1212, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\kaifaniuB2\Desktop\youtube\youtube_dl\extractor\youtube.py", line 1120, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "C:\Users\kaifaniuB2\Desktop\youtube\youtube_dl\extractor\common.py", line 761, in _download_webpage
    expected_status=expected_status)
  File "C:\Users\kaifaniuB2\Desktop\youtube\youtube_dl\extractor\youtube.py", line 264, in _download_webpage_handle
    *args, **compat_kwargs(kwargs))
  File "C:\Users\kaifaniuB2\Desktop\youtube\youtube_dl\extractor\common.py", line 627, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query
, expected_status=expected_status)
  File "C:\Users\kaifaniuB2\Desktop\youtube\youtube_dl\extractor\common.py", line 612, in _request_webpage
    raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
youtube_dl.utils.ExtractorError: Download of https://www.youtube.com/yts/jsbin/player_ias_remote_ux-vflpDjiQc/en_US/base
.js failed: <urlopen error EOF occurred in violation of protocol (_ssl.c:598)> (caused by URLError(SSLEOFError(8, 'EOF o
ccurred in violation of protocol (_ssl.c:598)'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\kaifaniuB2\Desktop\youtube\youtube_dl\YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "C:\Users\kaifaniuB2\Desktop\youtube\youtube_dl\extractor\common.py", line 502, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\kaifaniuB2\Desktop\youtube\youtube_dl\extractor\youtube.py", line 1805, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "C:\Users\kaifaniuB2\Desktop\youtube\youtube_dl\extractor\youtube.py", line 1222, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\kaifaniuB2\Desktop\youtube\lib\urllib\request.py", line 1235, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "C:\Users\kaifaniuB2\Desktop\youtube\lib\http\client.py", line 1066, in request
    self._send_request(method, url, body, headers)
  File "C:\Users\kaifaniuB2\Desktop\youtube\lib\http\client.py", line 1104, in _send_request
    self.endheaders(body)
  File "C:\Users\kaifaniuB2\Desktop\youtube\lib\http\client.py", line 1062, in endheaders
    self._send_output(message_body)
  File "C:\Users\kaifaniuB2\Desktop\youtube\lib\http\client.py", line 907, in _send_output
    self.send(msg)
  File "C:\Users\kaifaniuB2\Desktop\youtube\lib\http\client.py", line 842, in send
    self.connect()
  File "C:\Users\kaifaniuB2\Desktop\youtube\lib\http\client.py", line 1206, in connect
    server_hostname=server_hostname)
  File "C:\Users\kaifaniuB2\Desktop\youtube\lib\ssl.py", line 344, in wrap_socket
    _context=self)
  File "C:\Users\kaifaniuB2\Desktop\youtube\lib\ssl.py", line 540, in __init__
    self.do_handshake()
  File "C:\Users\kaifaniuB2\Desktop\youtube\lib\ssl.py", line 767, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:598)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\kaifaniuB2\Desktop\youtube\youtube_dl\extractor\common.py", line 599, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "C:\Users\kaifaniuB2\Desktop\youtube\youtube_dl\YoutubeDL.py", line 2211, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "C:\Users\kaifaniuB2\Desktop\youtube\lib\urllib\request.py", line 455, in open
    response = self._open(req, data)
  File "C:\Users\kaifaniuB2\Desktop\youtube\lib\urllib\request.py", line 473, in _open
    '_open', req)
  File "C:\Users\kaifaniuB2\Desktop\youtube\lib\urllib\request.py", line 433, in _call_chain
    result = func(*args)
  File "C:\Users\kaifaniuB2\Desktop\youtube\youtube_dl\utils.py", line 1139, in https_open
    req, **kwargs)
  File "C:\Users\kaifaniuB2\Desktop\youtube\lib\urllib\request.py", line 1238, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:598)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\kaifaniuB2\Desktop\youtube\youtube_dl\extractor\youtube.py", line 1212, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\kaifaniuB2\Desktop\youtube\youtube_dl\extractor\youtube.py", line 1120, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "C:\Users\kaifaniuB2\Desktop\youtube\youtube_dl\extractor\common.py", line 761, in _download_webpage
    expected_status=expected_status)
  File "C:\Users\kaifaniuB2\Desktop\youtube\youtube_dl\extractor\youtube.py", line 264, in _download_webpage_handle
    *args, **compat_kwargs(kwargs))
  File "C:\Users\kaifaniuB2\Desktop\youtube\youtube_dl\extractor\common.py", line 627, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query
, expected_status=expected_status)
  File "C:\Users\kaifaniuB2\Desktop\youtube\youtube_dl\extractor\common.py", line 612, in _request_webpage
    raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
youtube_dl.utils.ExtractorError: Download of https://www.youtube.com/yts/jsbin/player_ias_remote_ux-vflpDjiQc/en_US/base
.js failed: <urlopen error EOF occurred in violation of protocol (_ssl.c:598)> (caused by URLError(SSLEOFError(8, 'EOF o
ccurred in violation of protocol (_ssl.c:598)'),))
 (caused by ExtractorError("Download of https://www.youtube.com/yts/jsbin/player_ias_remote_ux-vflpDjiQc/en_US/base.js f
ailed: <urlopen error EOF occurred in violation of protocol (_ssl.c:598)> (caused by URLError(SSLEOFError(8, 'EOF occurr
ed in violation of protocol (_ssl.c:598)'),))",)); please report this issue on https://yt-dl.org/bug . Make sure you are
 using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbos
e flag and include its complete output.
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

It happend since saturday, and the result is instable, sometimes the output is right, but also get warning "WARNING: unable to download video info webpage: <urlopen error EOF occurred in violation of protocol (_ssl.c:598)>", and sometimes it gose wrong, just like the log says,

**Comment by llwmagic** [comment]
ytb -v --proxy -J https://www.youtube.com/watch?v=Q4-jOuHO-z4
The video is going well on youtube, but can't be analysed.

**Comment by dstftw** [comment]
Most likely caused by your proxy.
