### ISSUE TITLE
ERROR: Signature extraction failed on youtube videos

### ISSUE THREAD

**Issue by GourangaDas** [rg3/youtube-dl#17522]
Currently, I am getting the '**ERROR: Signature extraction failed**' on some youtube videos. 
While I am trying to execute the below:
`youtube-dl https://www.youtube.com/watch?v=HXbq49vLRC8 -F`
It sadly gives me some error as:

```
[youtube] HXbq49vLRC8: Downloading webpage
[youtube] HXbq49vLRC8: Downloading video info webpage
[youtube] HXbq49vLRC8: Downloading js player vflvABTsY
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkzpz548c\build\youtube_dl\extractor\youtube.py", line 1210, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkzpz548c\build\youtube_dl\extractor\youtube.py", line 1121, in _extract_signature_function
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkzpz548c\build\youtube_dl\extractor\youtube.py", line 1182, in _parse_sig_js
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpkzpz548c\build\youtube_dl\extractor\common.py", line 972, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; 
please report this issue on https://yt-dl.org/bug . 
Make sure you are using the latest version; 
type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract Initial JS player signature function name; 
please report this issue on https://yt-dl.org/bug . 
Make sure you are using the latest version; type  youtube-dl -U  to update. 
Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . 
Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

Here's are more links to check out that also have same issue:

https://www.youtube.com/watch?v=UsU8EVKCw_k
https://www.youtube.com/watch?v=lciCUTNuEt4
https://www.youtube.com/watch?v=HXbq49vLRC8
https://www.youtube.com/watch?v=fiIklhLZ39Y
https://www.youtube.com/watch?v=1fc-XKh7obg

What should I do to overcome this issue?

Current version is **2018.09.01**

**Comment by GourangaDas** [comment]
Sorry for submitting this issue.
**Update 'YOUTUBE-DL" to 2018.09.10 salve this issue.**
