### ISSUE TITLE
YouTube: unable to download video data: Remote end closed connection without response

### ISSUE THREAD

**Issue by aft90** [rg3/youtube-dl#17533]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.09.10*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.09.10**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

```
[debug] System config: ['--prefer-free-formats']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=c6Lt9jf9wAQ']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.09.10
[debug] Python version 3.6.6 (CPython) - Linux-4.17.19-200.fc28.x86_64-x86_64-with-fedora-28-Twenty_Eight
[debug] exe versions: ffmpeg n4.0.2, ffprobe n4.0.2, phantomjs 2.1.1
[debug] Proxy map: {}
[youtube] c6Lt9jf9wAQ: Downloading webpage
[youtube] c6Lt9jf9wAQ: Downloading video info webpage
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://r3---sn-8pgbpohxqp5-ajtl.googlevideo.com/videoplayback?txp=5532332&key=yt6&signature=04228F2C522146AF79166EC57C4F338C2B34BDCB.2E05ABA3B4B3A7EA026E3D8EB7B0364223F0D5E4&gir=yes&dur=262.474&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C271%2C278%2C298%2C299%2C302%2C303%2C308%2C313%2C315&source=youtube&lmt=1535786944134868&requiressl=yes&fvip=4&itag=315&expire=1536637510&keepalive=yes&mn=sn-8pgbpohxqp5-ajtl%2Csn-aigl6ner&mm=31%2C29&id=o-AKoqCC8bmOQ21s1xkAbTwiav51XWz-eRRC9ovI12nKoI&mv=m&mt=1536615824&ms=au%2Crdu&ei=5uWWW5WpIoGEVf-YoeAP&ip=82.34.108.111&pl=22&initcwndbps=1285000&c=WEB&ipbits=0&clen=867526321&sparams=aitags%2Cclen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&mime=video%2Fwebm&ratebypass=yes'
ERROR: unable to download video data: Remote end closed connection without response
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 1902, in process_info
    partial_success = dl(fname, new_info)
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 1847, in dl
    return fd.download(name, info)
  File "./youtube-dl/youtube_dl/downloader/common.py", line 364, in download
    return self.real_download(filename, info_dict)
  File "./youtube-dl/youtube_dl/downloader/http.py", line 341, in real_download
    establish_connection()
  File "./youtube-dl/youtube_dl/downloader/http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 2211, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib64/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib64/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib64/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "./youtube-dl/youtube_dl/utils.py", line 1139, in https_open
    req, **kwargs)
  File "/usr/lib64/python3.6/urllib/request.py", line 1321, in do_open
    r = h.getresponse()
  File "/usr/lib64/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib64/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
```

The above URL is an example but it's happened with numerous other videos on youtube. I get a similar error if I run it with python2:
```
[debug] System config: [u'--prefer-free-formats']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=c6Lt9jf9wAQ']
[debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8
[debug] youtube-dl version 2018.09.10
[debug] Python version 2.7.15 (CPython) - Linux-4.17.19-200.fc28.x86_64-x86_64-with-fedora-28-Twenty_Eight
[debug] exe versions: ffmpeg n4.0.2, ffprobe n4.0.2, phantomjs 2.1.1
[debug] Proxy map: {}
[youtube] c6Lt9jf9wAQ: Downloading webpage
[youtube] c6Lt9jf9wAQ: Downloading video info webpage
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://r3---sn-8pgbpohxqp5-ajtl.googlevideo.com/videoplayback?c=WEB&key=yt6&ei=nuaWW5-SCISOV5aDpqgB&txp=5532332&ipbits=0&clen=867526321&source=youtube&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C271%2C278%2C298%2C299%2C302%2C303%2C308%2C313%2C315&signature=A2F2FF04AF2A3734BCB7E70F93958518A425AB8F.DD5E2175822ED5DED0B5990B40B0ED0FFEFE111B&expire=1536637694&lmt=1535786944134868&requiressl=yes&gir=yes&mime=video%2Fwebm&fvip=4&keepalive=yes&sparams=aitags%2Cclen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&id=o-ACmylxsmbPq8aW5Go8GOWTco5Opk2fxxdTg9ESxJP9bJ&mt=1536615931&mv=m&dur=262.474&initcwndbps=1306250&itag=315&ms=au%2Crdu&ip=82.34.108.111&mm=31%2C29&mn=sn-8pgbpohxqp5-ajtl%2Csn-aigzrn7z&pl=22&ratebypass=yes'
ERROR: unable to download video data: ''
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 1902, in process_info
    partial_success = dl(fname, new_info)
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 1847, in dl
    return fd.download(name, info)
  File "./youtube-dl/youtube_dl/downloader/common.py", line 364, in download
    return self.real_download(filename, info_dict)
  File "./youtube-dl/youtube_dl/downloader/http.py", line 341, in real_download
    establish_connection()
  File "./youtube-dl/youtube_dl/downloader/http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 2211, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "./youtube-dl/youtube_dl/utils.py", line 1139, in https_open
    req, **kwargs)
  File "/usr/lib64/python2.7/urllib2.py", line 1203, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib64/python2.7/httplib.py", line 1121, in getresponse
    response.begin()
  File "/usr/lib64/python2.7/httplib.py", line 438, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python2.7/httplib.py", line 402, in _read_status
    raise BadStatusLine(line)
BadStatusLine: ''
```

**Comment by dstftw** [comment]
Most likely a connectivity issue between you and youtube host.
