### ISSUE TITLE
youtube TimeoutError: [Errno 110] Connection timed out

### ISSUE THREAD

**Issue by bunder2015** [rg3/youtube-dl#17547]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.09.10*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.09.10**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
$ youtube-dl -4 -f bestvideo+bestaudio[acodec!=opus] --playlist-start 3 -v https://www.youtube.com/playlist?list=PLaUVvul17xSedlXipesHxfzDm74lXj0ab
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-4', '-f', 'bestvideo+bestaudio[acodec!=opus]', '--playlist-start', '3', '-v', 'https://www.youtube.com/playlist?list=PLaUVvul17xSedlXipesHxfzDm74lXj0ab']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.09.10
[debug] Python version 3.6.5 (CPython) - Linux-4.14.66-gentoo-x86_64-Intel-R-_Core-TM-_i7-7700HQ_CPU_@_2.80GHz-with-gentoo-2.4.1
[debug] exe versions: ffmpeg 3.3.6, ffprobe 3.3.6
[debug] Proxy map: {}
[youtube:playlist] PLaUVvul17xSedlXipesHxfzDm74lXj0ab: Downloading webpage
[download] Downloading playlist: OpenZFS Developer Summit 2015
[youtube:playlist] playlist OpenZFS Developer Summit 2015: Downloading 14 videos
[download] Downloading video 1 of 14
[youtube] IQp_FglfzUQ: Downloading webpage
[youtube] IQp_FglfzUQ: Downloading video info webpage
[debug] Invoking downloader on 'https://r3---sn-jvbxjv-tihe.googlevideo.com/videoplayback?itag=137&pl=19&dur=2707.637&keepalive=yes&sparams=aitags%2Cclen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2
Cmm%2Cmn%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Crequiressl%2Csource%2Cexpire&source=youtube&expire=1536726018&gir=yes&c=WEB&mime=video%2Fmp4&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&signature=D83606596277C34041AEE
BEAFFB5DE86F9F71741.A485B559FB618945DAF160F42E61625CAD1C6764&pcm2cms=yes&ipbits=0&clen=496554576&initcwndbps=1553750&ip=72.38.201.124&key=yt6&ms=au%2Crdu&beids=9466587&mv=m&mt=1536704359&id=o-AN3jXo35yJc_yKWpkmU5SFoayY3czb88dXHV4BGL5fkx&
mn=sn-jvbxjv-tihe%2Csn-tt1e7nee&mm=31%2C29&lmt=1445687346747635&fvip=6&ei=oj-YW_2yLYLWD_X_ucAD&requiressl=yes&ratebypass=yes'
ERROR: unable to download video data: <urlopen error [Errno 110] Connection timed out>
Traceback (most recent call last):
  File "/usr/lib64/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib64/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/lib64/python3.6/http/client.py", line 1392, in connect
    super().connect()
  File "/usr/lib64/python3.6/http/client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib64/python3.6/site-packages/youtube_dl/utils.py", line 918, in _create_connection
    raise err
  File "/usr/lib64/python3.6/site-packages/youtube_dl/utils.py", line 910, in _create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 1902, in process_info
    partial_success = dl(fname, new_info)
  File "/usr/lib64/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 1847, in dl
    return fd.download(name, info)
  File "/usr/lib64/python3.6/site-packages/youtube_dl/downloader/common.py", line 364, in download
    return self.real_download(filename, info_dict)
  File "/usr/lib64/python3.6/site-packages/youtube_dl/downloader/http.py", line 341, in real_download
    establish_connection()
  File "/usr/lib64/python3.6/site-packages/youtube_dl/downloader/http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/lib64/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 2211, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib64/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib64/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib64/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.6/site-packages/youtube_dl/utils.py", line 1139, in https_open
    req, **kwargs)
  File "/usr/lib64/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>
```
---

### Description of your *issue*, suggested solution and other information

Downloaded 10-20 videos yesterday and now all I get back is timeouts.  I tried adding a browser user agent as well, no change.

**Comment by bunder2015** [comment]
Tried a proxy, works... it's my busted ISP.
