### ISSUE TITLE
[RaiPlay] Unable to download

### ISSUE THREAD

**Issue by becmin** [rg3/youtube-dl#17561]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.09.10*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2018.09.10**

### Before submitting an *issue* make sure you have:
- [X ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [X ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

youtube-dl https://www.raiplay.it/video/2017/09/La-pazza-gioia-a64825e8-1c7e-461a-b2f2-55319d69c28e.html --verbose
[debug] System config: []
[debug] User config: ['--embed-subs', '--write-sub', '--all-subs', '--convert-subs', 'srt', '--add-metadata', '--xattrs', '--prefer-ffmpeg', '--merge-output-format', 'mkv', '-o', '~/Downloads/[%(uploader)s].S%(season_number)s.E%(episode_number)s.%(title)s.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: ['https://www.raiplay.it/video/2017/09/La-pazza-gioia-a64825e8-1c7e-461a-b2f2-55319d69c28e.html', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.09.10
[debug] Python version 3.7.0 (CPython) - Linux-4.18.6-arch1-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg n4.0.2, ffprobe n4.0.2, rtmpdump 2.4
[debug] Proxy map: {}
[RaiPlay] a64825e8-1c7e-461a-b2f2-55319d69c28e: Downloading video JSON
[RaiPlay] a64825e8-1c7e-461a-b2f2-55319d69c28e: Downloading XML metadata for platform mon
[RaiPlay] a64825e8-1c7e-461a-b2f2-55319d69c28e: Downloading XML metadata for platform flash
[RaiPlay] a64825e8-1c7e-461a-b2f2-55319d69c28e: Downloading XML metadata for platform native
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 502, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/rai.py", line 181, in _real_extract
    self._sort_formats(relinker_info['formats'])
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1281, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

---

Cannot Download videos from Raiplay (Italian Public Television website). If you try to access the page on the browser you are required to log in in order to see the video, but in the past I could download videos with youtube-dl without giving any credential.

**Comment by iamleot** [comment]
Hello @becmin,
maybe they have permitted to watch the movie only for a certain period of time and now it is no more available? (I have noticed that for example with some TV series)

With the URL in your example I have "Error 404" (page not available), and trying other possible URLs for "La pazza gioia":

````
% python2.7 -m youtube_dl --verbose 'https://www.raiplay.it/programmi/lapazzagioia/'
[debug] System config: []
[debug] User config: [u'-f', u'bestvideo[height<=?720]+bestaudio/best[height<=?720]', u'-o', u'%(playlist_index)s - %(title)s.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.raiplay.it/programmi/lapazzagioia/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.09.18
[debug] Git HEAD: bfcff8a5e
[debug] Python version 2.7.15 (CPython) - NetBSD-8.99.15-amd64-x86_64-64bit-ELF
[debug] exe versions: ffmpeg 3.4.2, ffprobe 3.4.2
[debug] Proxy map: {'perl_lwp_env': '1'}
[RaiPlayPlaylist] lapazzagioia: Downloading webpage
[download] Downloading playlist: La pazza gioia
[RaiPlayPlaylist] playlist La pazza gioia: Collected 0 video ids (downloading 0 of them)
[download] Finished downloading playlist: La pazza gioia
% python2.7 -m youtube_dl --verbose 'https://www.raiplay.it/programmi/lapazzagioia/film'
[debug] System config: []
[debug] User config: [u'-f', u'bestvideo[height<=?720]+bestaudio/best[height<=?720]', u'-o', u'%(playlist_index)s - %(title)s.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.raiplay.it/programmi/lapazzagioia/film']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.09.18
[debug] Git HEAD: bfcff8a5e
[debug] Python version 2.7.15 (CPython) - NetBSD-8.99.15-amd64-x86_64-64bit-ELF
[debug] exe versions: ffmpeg 3.4.2, ffprobe 3.4.2
[debug] Proxy map: {'perl_lwp_env': '1'}
[RaiPlayPlaylist] lapazzagioia: Downloading webpage
[download] Downloading playlist: La pazza gioia
[RaiPlayPlaylist] playlist La pazza gioia: Collected 0 video ids (downloading 0 of them)
[download] Finished downloading playlist: La pazza gioia
% python2.7 -m youtube_dl --verbose 'https://www.raiplay.it/programmi/lapazzagioia/ContentSet-bc3210d3-7ef9-49f5-b5c0-b222c2385c37.html'
[debug] System config: []
[debug] User config: [u'-f', u'bestvideo[height<=?720]+bestaudio/best[height<=?720]', u'-o', u'%(playlist_index)s - %(title)s.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.raiplay.it/programmi/lapazzagioia/ContentSet-bc3210d3-7ef9-49f5-b5c0-b222c2385c37.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.09.18
[debug] Git HEAD: bfcff8a5e
[debug] Python version 2.7.15 (CPython) - NetBSD-8.99.15-amd64-x86_64-64bit-ELF
[debug] exe versions: ffmpeg 3.4.2, ffprobe 3.4.2
[debug] Proxy map: {'perl_lwp_env': '1'}
[RaiPlay] bc3210d3-7ef9-49f5-b5c0-b222c2385c37: Downloading video JSON
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "youtube_dl/extractor/common.py", line 604, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "youtube_dl/YoutubeDL.py", line 2211, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/pkg/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/pkg/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/pkg/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/pkg/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/pkg/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

Exit 1
% python2.7 -m youtube_dl --verbose 'https://www.raiplay.it/programmi/lapazzagioia/ContentSet-bc3210d3-7ef9-49f5-b5c0-b222c2385c37-json.html?json'
[debug] System config: []
[debug] User config: [u'-f', u'bestvideo[height<=?720]+bestaudio/best[height<=?720]', u'-o', u'%(playlist_index)s - %(title)s.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.raiplay.it/programmi/lapazzagioia/ContentSet-bc3210d3-7ef9-49f5-b5c0-b222c2385c37-json.html?json']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.09.18
[debug] Git HEAD: bfcff8a5e
[debug] Python version 2.7.15 (CPython) - NetBSD-8.99.15-amd64-x86_64-64bit-ELF
[debug] exe versions: ffmpeg 3.4.2, ffprobe 3.4.2
[debug] Proxy map: {'perl_lwp_env': '1'}
[RaiPlayPlaylist] lapazzagioia: Downloading webpage
WARNING: unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract description; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[download] Downloading playlist: lapazzagioia
[RaiPlayPlaylist] playlist lapazzagioia: Collected 0 video ids (downloading 0 of them)
[download] Finished downloading playlist: lapazzagioia
````

But trying a different movie seems to work, e.g.: <https://www.raiplay.it/video/2018/02/La-felicita-e-un-sistema-complesso-ce033aff-14a5-4359-aa5e-85398a57da22.html> ("La felicità è un sistema complesso").

**Comment by becmin** [comment]
I tried to download the same video you linked, @iamleot, but still no luck: in fact, I get the same "No video formats found error" here.
```
youtube-dl https://www.raiplay.it/video/2018/02/La-felicita-e-un-sistema-complesso-ce033aff-14a5-4359-aa5e-85398a57da22.html -v
[debug] System config: []
[debug] User config: ['--embed-subs', '--write-sub', '--all-subs', '--convert-subs', 'srt', '--add-metadata', '--xattrs', '--prefer-ffmpeg', '--merge-output-format', 'mkv', '-o', '~/Downloads/[%(uploader)s].S%(season_number)s.E%(episode_number)s.%(title)s.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: ['https://www.raiplay.it/video/2018/02/La-felicita-e-un-sistema-complesso-ce033aff-14a5-4359-aa5e-85398a57da22.html', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.09.18
[debug] Python version 3.7.0 (CPython) - Linux-4.18.8-arch1-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg n4.0.2, ffprobe n4.0.2, rtmpdump 2.4
[debug] Proxy map: {}
[RaiPlay] ce033aff-14a5-4359-aa5e-85398a57da22: Downloading video JSON
[RaiPlay] ce033aff-14a5-4359-aa5e-85398a57da22: Downloading XML metadata for platform mon
[RaiPlay] ce033aff-14a5-4359-aa5e-85398a57da22: Downloading XML metadata for platform flash
[RaiPlay] ce033aff-14a5-4359-aa5e-85398a57da22: Downloading XML metadata for platform native
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 507, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/rai.py", line 181, in _real_extract
    self._sort_formats(relinker_info['formats'])
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1286, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.`
```
I tried another video ("La ragazza del lago") but I get the same error. I also added `--ignore-config` just to make sure that my configuration was not messing things up, but that didn't matter. (I also ran `--ignore config` on "La felicità," but I got the same errors)

```
youtube-dl https://www.raiplay.it/programmi/laragazzadellago/ -v --ignore-config
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.raiplay.it/programmi/laragazzadellago/', '-v', '--ignore-config']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.09.18
[debug] Python version 3.7.0 (CPython) - Linux-4.18.8-arch1-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg n4.0.2, ffprobe n4.0.2, rtmpdump 2.4
[debug] Proxy map: {}
[RaiPlayPlaylist] laragazzadellago: Downloading webpage
Il commissario Giovanni Sanzio indaga sull'omicidio di una studentessa giocatrice di hockey il cui corpo viene rinvenuto sulle sponde di un lago in Friuli. Dieci David e tre Nastri d'Argento 2008. Tratto dal romanzo "Lo sguardo di uno sconosciuto" di Karin Fossum.
[download] Downloading playlist: La ragazza del lago
[RaiPlayPlaylist] playlist La ragazza del lago: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[RaiPlay] 7fdb6be4-90c2-4605-ba37-ee23be8f0a07: Downloading video JSON
[RaiPlay] 7fdb6be4-90c2-4605-ba37-ee23be8f0a07: Downloading XML metadata for platform mon
[RaiPlay] 7fdb6be4-90c2-4605-ba37-ee23be8f0a07: Downloading XML metadata for platform flash
[RaiPlay] 7fdb6be4-90c2-4605-ba37-ee23be8f0a07: Downloading XML metadata for platform native
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 507, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/rai.py", line 181, in _real_extract
    self._sort_formats(relinker_info['formats'])
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1286, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by iamleot** [comment]
Hello @becmin,
only for completeness here both seems to work ("La felicità è un
sistema complesso"):

````
% youtube-dl --ignore-config -v https://www.raiplay.it/video/2018/02/La-felicita-e-un-sistema-complesso-ce033aff-14a5-4359-aa5e-85398a57da22.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--ignore-config', u'-v', u'https://www.raiplay.it/video/2018/02/La-felicita-e-un-sistema-complesso-ce033aff-14a5-4359-aa5e-85398a57da22.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.09.18
[debug] Python version 2.7.15 (CPython) - NetBSD-8.99.15-amd64-x86_64-64bit-ELF
[debug] exe versions: ffmpeg 3.4.2, ffmpeg3 3.4.2, ffmpeg4 4.0.1, ffprobe 3.4.2, ffprobe3 3.4.2, ffprobe4 4.0.1
[debug] Proxy map: {'perl_lwp_env': '1'}
[RaiPlay] ce033aff-14a5-4359-aa5e-85398a57da22: Downloading video JSON
[RaiPlay] ce033aff-14a5-4359-aa5e-85398a57da22: Downloading XML metadata for platform mon
[RaiPlay] ce033aff-14a5-4359-aa5e-85398a57da22: Downloading m3u8 information
[RaiPlay] ce033aff-14a5-4359-aa5e-85398a57da22: Downloading XML metadata for platform flash
[RaiPlay] ce033aff-14a5-4359-aa5e-85398a57da22: Downloading XML metadata for platform native
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://b2ushds2-vh.akamaihd.net/i/podcastcdn/teche_root/PLAYRAI_TECHE_CINEMA_SD/8810305_,700,1200,1800,2400,.mp4.csmil/index_3_av.m3u8?null=0'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 674
[download] Destination: La felicità è un sistema complesso-ce033aff-14a5-4359-aa5e-85398a57da22.mp4
[download]   0.1% of ~1.71GiB at 891.20KiB/s ETA 40:35^C
ERROR: Interrupted by user
Exit 1
````

...and ("La ragazza del lago"):

````
% youtube-dl --ignore-config -v https://www.raiplay.it/programmi/laragazzadellago/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--ignore-config', u'-v', u'https://www.raiplay.it/programmi/laragazzadellago/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.09.18
[debug] Python version 2.7.15 (CPython) - NetBSD-8.99.15-amd64-x86_64-64bit-ELF
[debug] exe versions: ffmpeg 3.4.2, ffmpeg3 3.4.2, ffmpeg4 4.0.1, ffprobe 3.4.2, ffprobe3 3.4.2, ffprobe4 4.0.1
[debug] Proxy map: {'perl_lwp_env': '1'}
[RaiPlayPlaylist] laragazzadellago: Downloading webpage
[download] Downloading playlist: La ragazza del lago
[RaiPlayPlaylist] playlist La ragazza del lago: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[RaiPlay] 7fdb6be4-90c2-4605-ba37-ee23be8f0a07: Downloading video JSON
[RaiPlay] 7fdb6be4-90c2-4605-ba37-ee23be8f0a07: Downloading XML metadata for platform mon
[RaiPlay] 7fdb6be4-90c2-4605-ba37-ee23be8f0a07: Downloading m3u8 information
[RaiPlay] 7fdb6be4-90c2-4605-ba37-ee23be8f0a07: Downloading XML metadata for platform flash
[RaiPlay] 7fdb6be4-90c2-4605-ba37-ee23be8f0a07: Downloading XML metadata for platform native
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://2uscreativem2-vh.akamaihd.net/i/Italy/podcastmhp/replaytv/raimovie_replaytv/9299966_,800,1800,.mp4.csmil/index_1_av.m3u8'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 550
[download] Destination: La ragazza del lago-7fdb6be4-90c2-4605-ba37-ee23be8f0a07.mp4
[download]   0.2% of ~1.26GiB at 406.66KiB/s ETA 37:31^C
ERROR: Interrupted by user
Exit 1
````

(I have in both case interrupted the download few seconds after
starting.)

Unfortunately I have no idea what can go wrong, sorry.  Maybe using
the `--write-pages` option will shed some light.

**Comment by dstftw** [comment]
>Ops... ci dispiace
il contenuto non è disponibile

**Comment by serl** [comment]
I had the same issue. Having an account on the website, I tried if I could watch the video by logging in, this is the answer:

![screenshot](https://user-images.githubusercontent.com/2742655/51085147-724f0e80-1735-11e9-920a-447bd36c12a0.png)

So, some content is available only if you are in the right region. Maybe it is possible to catch the error and present it in a meaningful way..?

**Comment by iamleot** [comment]
Hello Sergio,

Sergio Livi writes:
> I had the same issue. Having an account on the website, I tried if I could watch the video by logging in, this is the answer:
>
> ![screenshot](https://user-images.githubusercontent.com/2742655/51085147-724f0e80-1735-11e9-920a-447bd36c12a0.png)
> [...]

Can you please also share how youtube-dl was invoked (better to
also add a `-v' too for verbose output) and its output?


Thanks!

**Comment by serl** [comment]
Sure!

```
$ youtube-dl --ignore-config -v 'https://www.raiplay.it/video/2019/01/Quello-che-non-ho-f1bd4061-522f-4247-b7e6-6309510f3929.html'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--ignore-config', u'-v', u'https://www.raiplay.it/video/2019/01/Quello-che-non-ho-f1bd4061-522f-4247-b7e6-6309510f3929.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.01.10
[debug] Python version 2.7.12 (CPython) - Linux-4.15.0-43-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.15-0ubuntu0.16.04.1, ffprobe 2.8.15-0ubuntu0.16.04.1
[debug] Proxy map: {}
[RaiPlay] f1bd4061-522f-4247-b7e6-6309510f3929: Downloading video JSON
[RaiPlay] f1bd4061-522f-4247-b7e6-6309510f3929: Downloading XML metadata for platform mon
[RaiPlay] f1bd4061-522f-4247-b7e6-6309510f3929: Downloading XML metadata for platform flash
[RaiPlay] f1bd4061-522f-4247-b7e6-6309510f3929: Downloading XML metadata for platform native
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 793, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/rai.py", line 181, in _real_extract
    self._sort_formats(relinker_info['formats'])
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 1302, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
...and the contents of the `video JSON`:

```json
      {
        "author":"",
        "channel":"Rai Scuola",
  	    "editor":"",
        "bsp": "",
				"adv": true,
				
        "datePublished":"12/01/2019",
        "timePublished":"21:16",
        "parentPage":"Page-055fe6a9-ab81-443b-93e3-0dbabe67c858",
        "parentBlock":"PublishingBlock-5ea3d0b7-306e-4cce-a939-47b85d833495",
        "parentSet":"ContentSet-124f4e47-6459-4fde-b4e0-f3927129ccd9",
        "label":"",
        "stagione":"",
        "episodio":"",
        "titoloEpisodio":"",
        "raccolte": [], 
        "generi":[],
        "sottogeneri":[],
	  	"correlati":"",
        "caption":" Neri Marcor\u00E8 propone un'interpre...",
        "description":" Neri Marcor\u00E8 propone un'interpretazione del presente in bilico tra le canzoni di Fabrizio De Andr\u00E8 e il pensiero di Pier Paolo Pasolini accompagnato dai musicisti Giua, Pietro Guarracino e Vieri Sturlini e con la  regia di Giorgio Gallione.",
        "isPartOf":{
    	    

        
        "tipologia" : [
              {"nome": "Teatro", 
              "id" : "Category-8be38cbf-6791-4f60-a38e-dee2a0e86b43"}],  
          
                  "layout" : "single",
                
    "channel" : "Rai 5",
    "editor" : "",
    "social" : {
    "sms" : "",
      "telefono" : "",
      "whatsapp" : "",
      "email" : ""
    },
    "orario" : "",
    "generi" :[],
      "correlati" : "Category:Teatro:Category-8be38cbf-6791-4f60-a38e-dee2a0e86b43^",
    "sottogenere" : [],
    "subtitle" : "2018",
    "anno" : "2018",
    "regia" : "",
        "produzione" : "",
       "country" : "",
        
        "durataFirstItem" : "01:24:44",
      

    "interpreti" : "",
    "conduttore" : "",
        "numeroStagioni" : "",
        "description" : "Neri Marcor\u00E8 propone un'interpretazione del presente in bilico tra le canzoni di Fabrizio De Andr\u00E8 e il pensiero di Pier Paolo Pasolini accompagnato dai musicisti Giua, Pietro Guarracino e Vieri Sturlini e con la  regia di Giorgio Gallione.",
        "label":"",

        
    "ID" : "ContentItem-79f3c88d-0b9c-4d2e-a52f-bf797bda4cc8",
    
        "name" : "Quello che non ho",
      
    "weblink" : "/raiplay/programmi/quellochenonho",
    "PathID" : "/raiplay/programmi/quellochenonho/index.html?json",
    "az" : true,
    "images": {
          "landscape" : "https://www.raiplay.it/resizegd/[RESOLUTION]/dl/img/2019/01/11/1547197920672_2048x1152.jpg",
              "portrait" : "https://www.raiplay.it/resizegd/[RESOLUTION]/dl/img/2019/01/11/1547197911142_1152x2048.jpg",
              "square" : "https://www.raiplay.it/resizegd/[RESOLUTION]/dl/img/2019/01/11/1547197911142_2048x2048.jpg",
                "landscape43" : "https://www.raiplay.it/resizegd/[RESOLUTION]/dl/img/2019/01/11/1547197911143_2048x1536.jpg",
                "portrait43" : "https://www.raiplay.it/resizegd/[RESOLUTION]/dl/img/2019/01/11/1547197911142_1536x2048.jpg"
        },
        
        "rights-management" : {
          "Diritti" : {
            "diretta":{
            },
            "offline":{
            },
            "VOD":{
            },
            "Zona Geografica":{
            }
          }
        }
        ,


        "sito": "",
        "bsp" : "",
        "fmt" : "",
        "keyw" : "",
        "banner300x250" : "",
        "bannerUnicoLoc": "",
        
		"dfp" : {
		 	"label" : ""
		 	
		 		,"name_escaped" : "Quellochenonho"
		 	
		 		,"tipologia_escaped" : [
		        {"nome": "Teatro",
		        "id" : "Category-8be38cbf-6791-4f60-a38e-dee2a0e86b43"}]
		 	
		 },
	 
        "adv": true,
        "type" : "Teatro"
      
		},
		"forma":"Integrale",
        
        "video":{
				
            "contentUrl": "http://mediapolisvod.rai.it/relinker/relinkerServlet.htm?cont=1i2UsSdssSlashAKoeeqqEEqual",
					
						
            "videoQuality": "",
            "videoFrameSize" : "",
            "duration": "01:24:44",
            "highlights":"",
            "subtitles":""
            
        },
            
    	"images":{
      		"landscape":"http://www.rai.it/resizegd/[RESOLUTION]/dl/img/2019/01/11/1547198354575_2048x1152.jpg",
            "portrait":"",
		    "square":"",
	        "landscape43":"",
	        "portrait43":""
      	},
        "ID": "ContentItem-f1bd4061-522f-4247-b7e6-6309510f3929",
        "pathID" : "/raiplay/video/2019/01/Quello-che-non-ho-f1bd4061-522f-4247-b7e6-6309510f3929.html?json",
        "name": "Quello che non ho",
        "subtitle": "Quello che non ho",
			
		"availabilities":[{"start":"01-01-2010 00:00:00","end":"2021-11-23 23:59:00"}],
				
		"regia" : "",
		"interpreti" : "",
		"type": "RaiTv Media Video Item",
        "weblink":"/raiplay/video/2019/01/Quello-che-non-ho-f1bd4061-522f-4247-b7e6-6309510f3929.html",
        "rating" : "",
        "rights-management" : {
        	"Diritti" : {
          
            "diretta":{},
              "offline":{},
                "VOD":{},
                "Zona Geografica":{}
            
            }
        }
        
      }
```

Note that the `rights-management` part is the same as in non-region-restricted videos... (for example, I can download this one without any issue: https://www.raiplay.it/video/2019/01/Fabrizio-De-Andre-20-anni-senza-il-grande-artista-e-poeta-10012019-8abfe2fd-3378-46a7-8a83-8823b980d466.html)
