### ISSUE TITLE
ERROR: audio conversion failed: Unknown encoder 'libvorbis

### ISSUE THREAD

**Issue by gakowihuwi** [rg3/youtube-dl#17606]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.09.18*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.09.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
Martins-MacBook-Pro:Downloads martin$ youtube-dl -v --extract-audio --audio-format vorbis --audio-quality 9 --yes-playlist -o "%(title)s.%(ext)s" https://www.youtube.com/playlist?list=PLiTjqszqNFy7P1A2PZBvUfqKfvG2sugjA
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--extract-audio', u'--audio-format', u'vorbis', u'--audio-quality', u'9', u'--yes-playlist', u'-o', u'%(title)s.%(ext)s', u'https://www.youtube.com/playlist?list=PLiTjqszqNFy7P1A2PZBvUfqKfvG2sugjA']
[debug] Encodings: locale US-ASCII, fs utf-8, out US-ASCII, pref US-ASCII
[debug] youtube-dl version 2018.09.10
[debug] Python version 2.7.10 (CPython) - Darwin-17.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.0.2, ffprobe 4.0.2
[debug] Proxy map: {}
[youtube:playlist] PLiTjqszqNFy7P1A2PZBvUfqKfvG2sugjA: Downloading webpage
[download] Downloading playlist: test
[youtube:playlist] playlist test: Downloading 1 videos
[download] Downloading video 1 of 1
[youtube] NCtzkaL2t_Y: Downloading webpage
[youtube] NCtzkaL2t_Y: Downloading video info webpage
[youtube] {18} signature length 42.42, html5 player vflkUTZn2
[youtube] {36} signature length 42.42, html5 player vflkUTZn2
[youtube] {17} signature length 42.42, html5 player vflkUTZn2
[youtube] {137} signature length 42.42, html5 player vflkUTZn2
[youtube] {248} signature length 42.42, html5 player vflkUTZn2
[youtube] {136} signature length 42.42, html5 player vflkUTZn2
[youtube] {247} signature length 42.42, html5 player vflkUTZn2
[youtube] {135} signature length 42.42, html5 player vflkUTZn2
[youtube] {244} signature length 42.42, html5 player vflkUTZn2
[youtube] {397} signature length 42.42, html5 player vflkUTZn2
[youtube] {134} signature length 42.42, html5 player vflkUTZn2
[youtube] {243} signature length 42.42, html5 player vflkUTZn2
[youtube] {396} signature length 42.42, html5 player vflkUTZn2
[youtube] {133} signature length 42.42, html5 player vflkUTZn2
[youtube] {242} signature length 42.42, html5 player vflkUTZn2
[youtube] {395} signature length 42.42, html5 player vflkUTZn2
[youtube] {160} signature length 42.42, html5 player vflkUTZn2
[youtube] {278} signature length 42.42, html5 player vflkUTZn2
[youtube] {394} signature length 42.42, html5 player vflkUTZn2
[youtube] {140} signature length 42.42, html5 player vflkUTZn2
[youtube] {171} signature length 42.42, html5 player vflkUTZn2
[youtube] {249} signature length 42.42, html5 player vflkUTZn2
[youtube] {250} signature length 42.42, html5 player vflkUTZn2
[youtube] {251} signature length 42.42, html5 player vflkUTZn2
[debug] Invoking downloader on u'https://r4---sn-5goeen76.googlevideo.com/videoplayback?sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&requiressl=yes&fvip=1&source=youtube&dur=211.201&lmt=1502283851945029&clen=3158737&gir=yes&mn=sn-5goeen76%2Csn-5go7yn7z&initcwndbps=1950000&key=yt6&mime=audio%2Fwebm&ei=URahW4mVN5DpyAWRnKHwDw&c=WEB&expire=1537305266&id=o-AHRcSmZx221H-bhluk7gEwAYIzlSLvfXwoykp65fUfn8&pl=22&keepalive=yes&ms=au%2Crdu&mv=m&mt=1537283552&itag=251&mm=31%2C29&ip=82.99.21.45&ipbits=0&signature=8AC94A1CADE51A0935A340F72E3559AC258B4E8F.715547293D55E387DCBDF5429653E18D62A60427&ratebypass=yes'
[download] Destination: The Beatles - Don't Let Me Down.webm
[download] 100% of 3.01MiB in 00:00
[debug] ffmpeg command line: ffprobe -show_streams 'file:The Beatles - Don'"'"'t Let Me Down.webm'
[ffmpeg] Destination: The Beatles - Don't Let Me Down.ogg
[debug] ffmpeg command line: ffmpeg -y -i 'file:The Beatles - Don'"'"'t Let Me Down.webm' -vn -acodec libvorbis '-q:a' 9 'file:The Beatles - Don'"'"'t Let Me Down.ogg'
ERROR: audio conversion failed: Unknown encoder 'libvorbis'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2047, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 308, in run
    'audio conversion failed: ' + e.msg)
PostProcessingError: audio conversion failed: Unknown encoder 'libvorbis'


```

---

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

I get "ERROR: audio conversion failed: Unknown encoder 'libvorbis'" when I run latest youtube-dl on 
 macOS 10.13.6. 

I have vorbis-tools 1.4.0 installed with brew. 

It also used to work fine when I last used youtube-dl a couple of months before. Back then it was most certanly an older version.

/Martin

**Comment by gakowihuwi** [comment]
Thanks a lot. Strange that I couldn't find this when I searched the error.
