### ISSUE TITLE
[YouTube] Video won't download - too poor quality?

### ISSUE THREAD

**Issue by FredMSloniker** [rg3/youtube-dl#17602]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.09.18*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.09.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'oKd5sv9LIiA']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.09.18
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] oKd5sv9LIiA: Downloading webpage
[youtube] oKd5sv9LIiA: Downloading video info webpage
[info] Available formats for oKd5sv9LIiA:
format code  extension  resolution note
249          webm       audio only DASH audio   62k , opus @ 50k, 5.47MiB
250          webm       audio only DASH audio   77k , opus @ 70k, 6.86MiB
171          webm       audio only DASH audio  103k , vorbis@128k, 9.02MiB
140          m4a        audio only DASH audio  128k , m4a_dash container, mp4a.40.2@128k, 12.72MiB
251          webm       audio only DASH audio  152k , opus @160k, 13.54MiB
278          webm       192x144    144p   78k , webm container, vp9, 30fps, video only, 6.72MiB
160          mp4        192x144    144p  138k , avc1.42c00c, 15fps, video only, 11.27MiB
242          webm       320x240    240p  187k , vp9, 30fps, video only, 15.23MiB
133          mp4        320x240    240p  302k , avc1.4d400d, 30fps, video only, 24.73MiB
17           3gp        176x144    small , mp4v.20.3, mp4a.40.2@ 24k, 8.97MiB
36           3gp        320x240    small , mp4v.20.3, mp4a.40.2, 22.79MiB
18           mp4        320x240    small , avc1.42001E, mp4a.40.2@ 96k, 45.72MiB
43           webm       640x360    medium , vp8.0, vorbis@128k, 46.48MiB (best)

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'oKd5sv9LIiA']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.09.18
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] oKd5sv9LIiA: Downloading webpage
[youtube] oKd5sv9LIiA: Downloading video info webpage
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://r1---sn-uhvcpax0n5-x5ue.googlevideo.com/videoplayback?dur=0.000&fvip=11&usequic=no&signature=20ECD34DC550F03FD407BE5A1F2004E33BB14601.0E60938CC413CC1FAF21FA6980F53FFDE985F210&initcwndbps=150000&pcm2cms=yes&ei=PrugW9uHBJbMkgakio6oCQ&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cusequic%2Cexpire&lmt=1437161434131218&gir=yes&expire=1537281950&id=o-AILxiexu7Ss_aAk6BiCYCpnbKf02-7D6fGrhpNzLUvow&ms=au%2Crdu&mt=1537260267&mv=m&source=youtube&mm=31%2C29&mn=sn-uhvcpax0n5-x5ue%2Csn-nx57yn7r&pl=23&requiressl=yes&ip=172.58.46.130&mime=video%2Fwebm&c=WEB&clen=48738160&itag=43&ipbits=0&ratebypass=yes&key=yt6'
ERROR: unable to download video data: ''
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpipjeparb\build\youtube_dl\YoutubeDL.py", line 1908, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpipjeparb\build\youtube_dl\YoutubeDL.py", line 1847, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpipjeparb\build\youtube_dl\downloader\common.py", line 364, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpipjeparb\build\youtube_dl\downloader\http.py", line 341, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpipjeparb\build\youtube_dl\downloader\http.py", line 109, in establish_connection
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpipjeparb\build\youtube_dl\YoutubeDL.py", line 2211, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpipjeparb\build\youtube_dl\utils.py", line 1139, in https_open
  File "C:\Python\Python34\lib\urllib\request.py", line 1186, in do_open
  File "C:\Python\Python34\lib\http\client.py", line 1227, in getresponse
  File "C:\Python\Python34\lib\http\client.py", line 386, in begin
  File "C:\Python\Python34\lib\http\client.py", line 356, in _read_status
http.client.BadStatusLine: ''
```

---

### Description of your *issue*, suggested solution and other information

While I can view this video in the browser, and I can get format information from youtube-dl (see the first hunk of debug output), attempting to actually download the video fails (see the second hunk of debug output). Any idea what's going wrong? Does it have something to do with the video being so *small?*

**Comment by dstftw** [comment]
Most likely a network issue on your side.
