### ISSUE TITLE
[Site support request] dbr.ee

### ISSUE THREAD

**Issue by NXVXRRE** [rg3/youtube-dl#17617]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.09.18*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.09.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
A:\Projects\Melodore>youtube-dl --ffmpeg-location A:\Projects\Melodore\ffmpeg.exe -v https://dbr.ee/vAeD
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--ffmpeg-location', 'A:\\Projects\\Melodore\\ffmpeg.exe', '-v', 'https://dbr.ee/vAeD']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2017.12.02
[debug] Python version 3.6.6 - Windows-10-10.0.17760-SP0
[debug] exe versions: ffmpeg N-77380-g2dba040, ffprobe N-77380-g2dba040
[debug] Proxy map: {}
[generic] vAeD: Requesting header
WARNING: Falling back on generic information extractor.
[generic] vAeD: Downloading webpage
[generic] vAeD: Extracting information
ERROR: Unsupported URL: https://dbr.ee/vAeD
Traceback (most recent call last):
  File "c:\users\novocy\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "c:\users\novocy\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\extractor\common.py", line 437, in extract
    ie_result = self._real_extract(url)
  File "c:\users\novocy\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\extractor\generic.py", line 3088, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://dbr.ee/vAeD
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single audio clip: https://dbr.ee/00as

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

**Comment by NXVXRRE** [comment]
I accidentally didn't have youtube-dl to the latest version - I've updated it and the result is exactly the same. ```A:\Projects\Melodore>youtube-dl --ffmpeg-location A:\Projects\Melodore\ffmpeg.exe -v https://dbr.ee/vAeD
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--ffmpeg-location', 'A:\\Projects\\Melodore\\ffmpeg.exe', '-v', 'https://dbr.ee/vAeD']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2018.09.18
[debug] Python version 3.6.6 (CPython) - Windows-10-10.0.17760-SP0
[debug] exe versions: ffmpeg N-77380-g2dba040, ffprobe N-77380-g2dba040
[debug] Proxy map: {}
[generic] vAeD: Requesting header
WARNING: Falling back on generic information extractor.
[generic] vAeD: Downloading webpage
[generic] vAeD: Extracting information
ERROR: Unsupported URL: https://dbr.ee/vAeD
Traceback (most recent call last):
  File "c:\users\novocy\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "c:\users\novocy\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\extractor\common.py", line 507, in extract
    ie_result = self._real_extract(url)
  File "c:\users\novocy\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\extractor\generic.py", line 3298, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://dbr.ee/vAeD
```
