### ISSUE TITLE
Cannot download video from youtube

### ISSUE THREAD

**Issue by JustForBugReports** [rg3/youtube-dl#17632]
Hello, I run the correct version, did my homework and would like to report a bug.

On some youtube videos the download just stops, here is the verbose output :
$ youtube-dl -v -f best -citw https://www.youtube.com/watch?v=AkI8MvKk64I
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-f', u'best', u'-citw', u'-v', u'https://www.youtube.com/watch?v=AkI8MvKk64I']
WARNING: --title is deprecated. Use -o "%(title)s-%(id)s.%(ext)s" instead.
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.09.18
[debug] Python version 2.7.15rc1 (CPython) - Linux-4.15.0-34-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] AkI8MvKk64I: Downloading webpage
[youtube] AkI8MvKk64I: Downloading video info webpage
[debug] Invoking downloader on u'https://r4---sn-oxv-25ge.googlevideo.com/videoplayback?source=youtube&lmt=1501515122511055&c=WEB&ei=dSqmW9-LHIKWhAeXubOwDA&mt=1537616400&sparams=dur%2Cei%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&mv=m&ms=au%2Crdu&ip=185.39.141.105&pcm2=no&requiressl=yes&mm=31%2C29&mn=sn-oxv-25ge%2Csn-n4g-jqbes&id=o-AE7orSPpVgrZao8zSOKA2w5nXNx1HaDPwRX4F1cnO6tq&pl=22&initcwndbps=1411250&itag=22&ratebypass=yes&expire=1537638101&ipbits=0&dur=4491.644&fvip=5&mime=video%2Fmp4&key=yt6&signature=85A9AE12C2F5AF1287D7E555B9B4E495ACCD7A59.7E4C3F472B693D0E895BE837270E5ACFB9272A06'
[download] Destination: Radio Melon - Des Melons et des Hommes 2 - Arnaud et Saint Claude-AkI8MvKk64I.mp4
[download]   1.4% of 143.45MiB at  6.04MiB/s ETA 00:23[download] Got server HTTP error: Downloaded 2097136 bytes, expected 150422827 bytes. Retrying (attempt 1 of 10)...

ERROR: Did not get any data blocks
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/http.py", line 342, in real_download
    return download()
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/http.py", line 320, in download
    retry(err)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/http.py", line 225, in retry
    raise RetryDownload(e)
RetryDownload

$

If I try to resume I get the following :
$ youtube-dl -v -f best -citw https://www.youtube.com/watch?v=AkI8MvKk64I
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-f', u'best', u'-citw', u'https://www.youtube.com/watch?v=AkI8MvKk64I']
WARNING: --title is deprecated. Use -o "%(title)s-%(id)s.%(ext)s" instead.
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.09.18
[debug] Python version 2.7.15rc1 (CPython) - Linux-4.15.0-34-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] AkI8MvKk64I: Downloading webpage
[youtube] AkI8MvKk64I: Downloading video info webpage
[debug] Invoking downloader on u'https://r4---sn-oxv-25ge.googlevideo.com/videoplayback?key=yt6&mime=video%2Fmp4&source=youtube&initcwndbps=1490000&requiressl=yes&itag=22&ei=RSumW7_nNsq2VpeJivAG&ratebypass=yes&pl=22&fvip=5&ms=au%2Crdu&sparams=dur%2Cei%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&mv=m&signature=046B898DBE9929BEE850250E347F08DBF0483608.8E27F8ADB49F3149554AAAF73F3A8B3CD102A28E&lmt=1501515122511055&mt=1537616562&ip=185.39.141.105&c=WEB&expire=1537638309&id=o-AHW0OavTii1W8dRLfxd18cmcChJnbSWTPxupd69-n4pX&dur=4491.644&mn=sn-oxv-25ge%2Csn-n4g-jqbes&mm=31%2C29&ipbits=0'
[download] Resuming download at byte 2097136

ERROR: Did not get any data blocks
  File "/usr/local/bin/youtube-dl", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/__init__.py", line 472, in main
    _real_main(argv)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/__init__.py", line 462, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 2001, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 803, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 857, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1635, in process_video_result
    self.process_info(new_info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1908, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1847, in dl
    return fd.download(name, info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/common.py", line 364, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/http.py", line 342, in real_download
    return download()
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/http.py", line 312, in download
    self.report_error('Did not get any data blocks')
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/common.py", line 165, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 620, in report_error
    self.trouble(error_message, tb)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 582, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())

$

The video plays fine in my browser, so I can only assume it's a bug in youtube-dl.

**Comment by dstftw** [comment]
Server side youtube issue for `best` format.
