### ISSUE TITLE
Failed to download video

### ISSUE THREAD

**Issue by lamensje** [rg3/youtube-dl#17647]
My CMD output with verbose flag:

"I:\Program Installers\YouTube-DL\youtube-dl.exe" -o "*PATH*/%(title)s.%(ext)s" https://www.youtube.com/playlist?list=PLFyi2v9igyDDCyozHyQjXZs95mWeIWiQR --playlist-start 46 --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-o', '*PATH*/%(title)s.%(ext)s', 'https://www.youtube.com/playlist?list=PLFyi2v9igyDDCyozHyQjXZs95mWeIWiQR', '--playlist-start', '46', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.06.04
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg N-91254-g2bd26dea66, ffprobe N-91254-g2bd26dea66
[debug] Proxy map: {}
[youtube:playlist] PLFyi2v9igyDDCyozHyQjXZs95mWeIWiQR: Downloading webpage
[download] Downloading playlist: Ideas
[youtube:playlist] PLFyi2v9igyDDCyozHyQjXZs95mWeIWiQR: Downloading page #1
[youtube:playlist] playlist Ideas: Downloading 149 videos
[download] Downloading video 1 of 149
[youtube] i2IqtFRJsiU: Downloading webpage
[youtube] i2IqtFRJsiU: Downloading video info webpage
[youtube] {22} signature length 43.44, html5 player vflUpPEZ9
[youtube] i2IqtFRJsiU: Downloading player https://www.youtube.com/yts/jsbin/player-vflUpPEZ9/en_US/base.js
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptg2apcao\build\youtube_dl\extractor\youtube.py", line 1199, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptg2apcao\build\youtube_dl\extractor\youtube.py", line 1110, in _extract_signature_function
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptg2apcao\build\youtube_dl\extractor\youtube.py", line 1171, in _parse_sig_js
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptg2apcao\build\youtube_dl\extractor\common.py", line 880, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptg2apcao\build\youtube_dl\extractor\youtube.py", line 1199, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptg2apcao\build\youtube_dl\extractor\youtube.py", line 1110, in _extract_signature_function
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptg2apcao\build\youtube_dl\extractor\youtube.py", line 1171, in _parse_sig_js
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptg2apcao\build\youtube_dl\extractor\common.py", line 880, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptg2apcao\build\youtube_dl\extractor\youtube.py", line 1199, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptg2apcao\build\youtube_dl\extractor\youtube.py", line 1110, in _extract_signature_function
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptg2apcao\build\youtube_dl\extractor\youtube.py", line 1171, in _parse_sig_js
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptg2apcao\build\youtube_dl\extractor\common.py", line 880, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by lamensje** [comment]
updating fixed the problem.
Thanks for fixing this bug!
