### ISSUE TITLE
TV3 rebranded Virginmedia

### ISSUE THREAD

**Issue by lcsneil** [rg3/youtube-dl#17664]
TV3 in Ireland has rebranded to virginmedia and currently error is site is not supported but URL is the same apart from TVE

e.g. 

old URL that worked

https://www.tv3.ie/player/show/1025/148233/0/Gogglebox-Ireland

NEW URL that gives site not supported

https://www.virginmediatelevision.ie/player/show/1025/148233/0/Gogglebox-Ireland

Hopefully a simple update of code?

**Comment by StephenCarroll1982** [comment]
stevie@stevie-Standard-PC-Q35-ICH9-2009:~/Videos/telifis$ youtube-dl -v https://www.virginmediatelevision.ie/player/show/1025/0/0/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.virginmediatelevision.ie/player/show/1025/0/0/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.09.01
[debug] Python version 2.7.15rc1 (CPython) - Linux-4.15.0-34-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.4-0ubuntu0.18.04.1, ffprobe 3.4.4-0ubuntu0.18.04.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 0: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 0: Downloading webpage
[generic] 0: Extracting information
ERROR: Unsupported URL: https://www.virginmediatelevision.ie/player/show/1025/0/0/
Traceback (most recent call last):
  File "/home/stevie/.local/lib/python2.7/site-packages/youtube_dl/extractor/generic.py", line 2324, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/home/stevie/.local/lib/python2.7/site-packages/youtube_dl/compat.py", line 2542, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/home/stevie/.local/lib/python2.7/site-packages/youtube_dl/compat.py", line 2531, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
ParseError: syntax error: line 1, column 0
Traceback (most recent call last):
  File "/home/stevie/.local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/home/stevie/.local/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 502, in extract
    ie_result = self._real_extract(url)
  File "/home/stevie/.local/lib/python2.7/site-packages/youtube_dl/extractor/generic.py", line 3298, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.virginmediatelevision.ie/player/show/1025/0/0/

**Comment by StephenCarroll1982** [comment]
Sorry had to update youtube-dl

`stevie@stevie-Standard-PC-Q35-ICH9-2009:~/Videos/telifis$ youtube-dl -v https://www.virginmediatelevision.ie/player/show/1025/0/0/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.virginmediatelevision.ie/player/show/1025/0/0/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.10.05
[debug] Python version 2.7.15rc1 (CPython) - Linux-4.15.0-34-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.4-0ubuntu0.18.04.1, ffprobe 3.4.4-0ubuntu0.18.04.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 0: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 0: Downloading webpage
[generic] 0: Extracting information
ERROR: Unsupported URL: https://www.virginmediatelevision.ie/player/show/1025/0/0/
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2324, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/bin/youtube-dl/youtube_dl/compat.py", line 2542, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/bin/youtube-dl/youtube_dl/compat.py", line 2531, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
ParseError: syntax error: line 1, column 0
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 507, in extract
    ie_result = self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3298, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.virginmediatelevision.ie/player/show/1025/0/0/
`

**Comment by StephenCarroll1982** [comment]
Looking at the page source of the above programme. I've taken the following info.

# ooyala video embedded with http://player.ooyala.com/static/v4/stable/4.24.11/core.min.js
url 'url': 'https://www.virginmediatelevision.ie/player/show/1025/149821/0/
 'info_dict': {
                'id': '102500149821', - I think this is the right ID
                'ext': 'mp4',
                'title': 'Virgin Media Player | Gogglebox Ireland - Gogglebox Ireland',
                'duration': 43.276,', - couldn't get the duration ?

There's also a description meta tag as below.

<meta property="og:description" content="A fourth series of the show in which the critical wit and wisdom of regular TV watchers is revealed."/><meta name="description" content="A fourth series of the show in which the critical wit and wisdom of regular TV watchers is revealed.">

Is this enought to add into generaric or do I need to add a new extractor ?
