### ISSUE TITLE
Fresh pull of youtube-dl fails to download from youku.  This has been the case for a long while now.

### ISSUE THREAD

**Issue by caoliver** [rg3/youtube-dl#17678]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.09.26*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ ] I've **verified** and **I assure** that I'm running youtube-dl **2018.09.26**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--id', u'https://v.youku.com/v_show/id_XMzgxNDM1NTUxMg==.html?spm=..m_26673_c_32078.5~5!2~5~5~5~A&debug=flv']
[debug] Encodings: locale ISO-8859-1, fs ISO-8859-1, out None, pref ISO-8859-1
[debug] youtube-dl version 2018.09.26
[debug] Python version 2.7.14 (CPython) - Linux-4.9.75-x86_64-Intel-R-_Core-TM-_i5-3570_CPU_@_3.40GHz-with-slackware-14.2
[debug] exe versions: ffmpeg 3.3, ffprobe 3.3
[debug] Proxy map: {}
[youku] XMzgxNDM1NTUxMg: Retrieving cna info
[youku] XMzgxNDM1NTUxMg: Downloading JSON metadata
ERROR: Youku server reported error -6004: ,201; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/staff/oliver/.local/lib64/python2.7/site-packages/youtube_dl-2018.9.26-py2.7.egg/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/home/staff/oliver/.local/lib64/python2.7/site-packages/youtube_dl-2018.9.26-py2.7.egg/youtube_dl/extractor/common.py", line 507, in extract
    ie_result = self._real_extract(url)
  File "/home/staff/oliver/.local/lib64/python2.7/site-packages/youtube_dl-2018.9.26-py2.7.egg/youtube_dl/extractor/youku.py", line 189, in _real_extract
    raise ExtractorError(msg)
ExtractorError: Youku server reported error -6004: \u5ba2\u6237\u7aef\u65e0\u6743\u64ad\u653e,201; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

youtube-dl exited with status code 1
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

**Comment by caoliver** [comment]
I can't edit, but:
hostname: youtube-dl --version
2018.09.26

**Comment by caoliver** [comment]
This has the correct info.  The other doesn't have the info.
