### ISSUE TITLE
[marvelhq.com] Add support

### ISSUE THREAD

**Issue by RuneMagle** [rg3/youtube-dl#17714]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.09.26**
### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other
---
```
C:\Users\Desktop\youtube-dl>youtube-dl.exe -F https://marvelrising.marvelhq.com/videos/disneychannel-marvel-rising-initiation-episode-1-ghost-hunter -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-F', 'https://marvelrising.marvelhq.com/videos/disneychannel-marvel-rising-initiation-episode-1-ghost-hunter', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.09.26
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg N-86911-gb664d1f, ffprobe N-86911-gb664d1f, rtmpdump 2.4
[debug] Proxy map: {}
[generic] disneychannel-marvel-rising-initiation-episode-1-ghost-hunter: Requesting header
WARNING: Falling back on generic information extractor.
[generic] disneychannel-marvel-rising-initiation-episode-1-ghost-hunter: Downloading webpage
[generic] disneychannel-marvel-rising-initiation-episode-1-ghost-hunter: Extracting information
ERROR: Unsupported URL: https://marvelrising.marvelhq.com/videos/disneychannel-marvel-rising-initiation-episode-1-ghost-hunter
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcaq35cl9\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcaq35cl9\build\youtube_dl\extractor\common.py", line 507, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcaq35cl9\build\youtube_dl\extractor\generic.py", line 3298, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://marvelrising.marvelhq.com/videos/disneychannel-marvel-rising-initiation-episode-1-ghost-hunter
...
<end of log>
```

---
- Single video: https://marvelrising.marvelhq.com/videos/disneychannel-marvel-rising-initiation-episode-1-ghost-hunter
- Single video: https://marvelrising.marvelhq.com/videos/disneychannel-marvel-rising-initiation-episode-6-the-secrets-we-keep

---

### Description of *issue*
If you could be so nice to add support for this site, it would be great. :)

**Comment by RuneMagle** [comment]
Nevermind. Found videos on DisneyNOW.
