### ISSUE TITLE
etonline.com broken

### ISSUE THREAD

**Issue by abrock** [rg3/youtube-dl#17719]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.09.26**
- [x] I've at least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

I found the original request to support the site #12236 which was closed via 922ab7840b01bd108887849063572cffa855cdc1. The extractor was removed in 171625469ab1b2a4dc99ed173a10be45e7fc13d6 since the site was covered by the general purpose extractor.

- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

Video plays in Firefox 62.0.2.

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
---
### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl --verbose https://www.etonline.com/media/videos/my-little-pony-friendship-is-magic-gets-a-musical-visit-from-rachel-bloom-exclusive
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.etonline.com/media/videos/my-little-pony-friendship-is-magic-gets-a-musical-visit-from-rachel-bloom-exclusive']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.09.26
[debug] Python version 2.7.15+ (CPython) - Linux-4.17.0-3-amd64-x86_64-with-debian-buster-sid
[debug] exe versions: ffmpeg 4.0.2-2, ffprobe 4.0.2-2
[debug] Proxy map: {}
[generic] my-little-pony-friendship-is-magic-gets-a-musical-visit-from-rachel-bloom-exclusive: Requesting header
WARNING: Falling back on generic information extractor.
[generic] my-little-pony-friendship-is-magic-gets-a-musical-visit-from-rachel-bloom-exclusive: Downloading webpage
[generic] my-little-pony-friendship-is-magic-gets-a-musical-visit-from-rachel-bloom-exclusive: Extracting information
[download] Downloading playlist: 'My Little Pony': Rachel Bloom Sings 'A Karin Tale'
[generic] playlist 'My Little Pony': Rachel Bloom Sings 'A Karin Tale': Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[brightcove:legacy] AQ~~,AAABIWNF7qE~,EJbsvFObVfJEm7rEo1Xk3nNXqnvaIG9q: Downloading playlist information
ERROR: Empty playlist; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 507, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/brightcove.py", line 307, in _real_extract
    return self._get_playlist_info(player_key[0])
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/brightcove.py", line 350, in _get_playlist_info
    raise ExtractorError('Empty playlist')
ExtractorError: Empty playlist; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

---

### Description of your *issue*, suggested solution and other information

Download for the site seems broken, I clicked the video section and tried to download the first video, same problem:

```
youtube-dl -v https://www.etonline.com/media/videos/jennifer-lopez-gushes-over-supportive-alex-rodriguez-at-final-vegas-show-110675
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.etonline.com/media/videos/jennifer-lopez-gushes-over-supportive-alex-rodriguez-at-final-vegas-show-110675']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.09.26
[debug] Python version 2.7.15+ (CPython) - Linux-4.17.0-3-amd64-x86_64-with-debian-buster-sid
[debug] exe versions: ffmpeg 4.0.2-2, ffprobe 4.0.2-2
[debug] Proxy map: {}
[generic] jennifer-lopez-gushes-over-supportive-alex-rodriguez-at-final-vegas-show-110675: Requesting header
WARNING: Falling back on generic information extractor.
[generic] jennifer-lopez-gushes-over-supportive-alex-rodriguez-at-final-vegas-show-110675: Downloading webpage
[generic] jennifer-lopez-gushes-over-supportive-alex-rodriguez-at-final-vegas-show-110675: Extracting information
[download] Downloading playlist: Jennifer Lopez Gushes Over 'Supportive' A-Rod!
[generic] playlist Jennifer Lopez Gushes Over 'Supportive' A-Rod!: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[brightcove:legacy] AQ~~,AAABIWNF7qE~,EJbsvFObVfJEm7rEo1Xk3nNXqnvaIG9q: Downloading playlist information
ERROR: Empty playlist; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 507, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/brightcove.py", line 307, in _real_extract
    return self._get_playlist_info(player_key[0])
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/brightcove.py", line 350, in _get_playlist_info
    raise ExtractorError('Empty playlist')
ExtractorError: Empty playlist; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

I tried downloading a random youtube video to see if I completely broke my installation or similar but youtube is no problem:

```
 youtube-dl -v https://www.youtube.com/watch?v=77umP7IRxD4
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=77umP7IRxD4']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.09.26
[debug] Python version 2.7.15+ (CPython) - Linux-4.17.0-3-amd64-x86_64-with-debian-buster-sid
[debug] exe versions: ffmpeg 4.0.2-2, ffprobe 4.0.2-2
[debug] Proxy map: {}
[youtube] 77umP7IRxD4: Downloading webpage
[youtube] 77umP7IRxD4: Downloading video info webpage
[youtube] {18} signature length 40.42, html5 player vfl07ioI6
[youtube] {36} signature length 40.42, html5 player vfl07ioI6
[youtube] {17} signature length 40.42, html5 player vfl07ioI6
[youtube] {135} signature length 40.42, html5 player vfl07ioI6
[youtube] {244} signature length 40.42, html5 player vfl07ioI6
[youtube] {134} signature length 40.42, html5 player vfl07ioI6
[youtube] {243} signature length 40.42, html5 player vfl07ioI6
[youtube] {133} signature length 40.42, html5 player vfl07ioI6
[youtube] {242} signature length 40.42, html5 player vfl07ioI6
[youtube] {160} signature length 38.42, html5 player vfl07ioI6
[youtube] 77umP7IRxD4: Downloading player https://www.youtube.com/yts/jsbin/player-vfl07ioI6/en_US/base.js
[youtube] {278} signature length 40.42, html5 player vfl07ioI6
[youtube] {140} signature length 40.42, html5 player vfl07ioI6
[youtube] {171} signature length 40.42, html5 player vfl07ioI6
[youtube] {249} signature length 40.42, html5 player vfl07ioI6
[youtube] {250} signature length 40.42, html5 player vfl07ioI6
[youtube] {251} signature length 40.42, html5 player vfl07ioI6
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://r4---sn-4g5edney.googlevideo.com/videoplayback?initcwndbps=1516250&ipbits=0&pl=18&txp=5532332&mm=31%2C29&key=yt6&itag=244&ei=zFOxW_HoDNft7gP8o7yYDA&requiressl=yes&sparams=aitags%2Cclen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&ip=109.193.76.143&keepalive=yes&mt=1538347874&mv=m&ms=au%2Crdu&clen=14448453&source=youtube&mime=video%2Fwebm&gir=yes&c=WEB&mn=sn-4g5edney%2Csn-4g5e6nsz&id=o-ACSl_134OCfpFXeVK7ZVJA7UG006JwJWQvJO2Q2TXC7l&dur=325.720&fvip=4&lmt=1538060417234360&expire=1538369580&aitags=133%2C134%2C135%2C160%2C242%2C243%2C244%2C278&signature=93B5B631FC9B1FA85566E2939A020E4D6B4645B7.7A5C3D11859B0750A5D7D6B991211EECAD53D807&ratebypass=yes'
[download] Destination: The Music of the Night - Andrew Lloyd Webber's The Phantom of the Opera-77umP7IRxD4.f244.webm
[download] 100% of 13.78MiB in 00:05
[debug] Invoking downloader on u'https://r4---sn-4g5edney.googlevideo.com/videoplayback?initcwndbps=1516250&ipbits=0&pl=18&txp=5511222&mm=31%2C29&key=yt6&itag=251&ei=zFOxW_HoDNft7gP8o7yYDA&requiressl=yes&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&ip=109.193.76.143&keepalive=yes&mt=1538347874&mv=m&ms=au%2Crdu&clen=5491885&source=youtube&mime=audio%2Fwebm&gir=yes&c=WEB&mn=sn-4g5edney%2Csn-4g5e6nsz&id=o-ACSl_134OCfpFXeVK7ZVJA7UG006JwJWQvJO2Q2TXC7l&dur=325.741&fvip=4&lmt=1538063172342732&expire=1538369580&signature=AD78C5D5CB209D2D8393D0493BEFE78D4AE85CC7.DAA5DF83CDBE9ADB6E386B9074DFD602910B6C15&ratebypass=yes'
[download] Destination: The Music of the Night - Andrew Lloyd Webber's The Phantom of the Opera-77umP7IRxD4.f251.webm
[download] 100% of 5.24MiB in 00:02
[ffmpeg] Merging formats into "The Music of the Night - Andrew Lloyd Webber's The Phantom of the Opera-77umP7IRxD4.webm"
[debug] ffmpeg command line: ffmpeg -y -i 'file:The Music of the Night - Andrew Lloyd Webber'"'"'s The Phantom of the Opera-77umP7IRxD4.f244.webm' -i 'file:The Music of the Night - Andrew Lloyd Webber'"'"'s The Phantom of the Opera-77umP7IRxD4.f251.webm' -c copy -map '0:v:0' -map '1:a:0' 'file:The Music of the Night - Andrew Lloyd Webber'"'"'s The Phantom of the Opera-77umP7IRxD4.temp.webm'
Deleting original file The Music of the Night - Andrew Lloyd Webber's The Phantom of the Opera-77umP7IRxD4.f244.webm (pass -k to keep)
Deleting original file The Music of the Night - Andrew Lloyd Webber's The Phantom of the Opera-77umP7IRxD4.f251.webm (pass -k to keep)
```

**Comment by abrock** [comment]
Update: The bug is still present in the current version of youtube-dl:

```
youtube-dl --verbose https://www.etonline.com/media/videos/my-little-pony-friendship-is-magic-gets-a-musical-visit-from-rachel-bloom-exclusive
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.etonline.com/media/videos/my-little-pony-friendship-is-magic-gets-a-musical-visit-from-rachel-bloom-exclusive']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.12.03
[debug] Python version 2.7.15+ (CPython) - Linux-4.18.0-3-amd64-x86_64-with-debian-buster-sid
[debug] exe versions: ffmpeg 4.0.3-1, ffprobe 4.0.3-1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] my-little-pony-friendship-is-magic-gets-a-musical-visit-from-rachel-bloom-exclusive: Requesting header
WARNING: Falling back on generic information extractor.
[generic] my-little-pony-friendship-is-magic-gets-a-musical-visit-from-rachel-bloom-exclusive: Downloading webpage
[generic] my-little-pony-friendship-is-magic-gets-a-musical-visit-from-rachel-bloom-exclusive: Extracting information
[download] Downloading playlist: 'My Little Pony': Rachel Bloom Sings 'A Karin Tale'
[generic] playlist 'My Little Pony': Rachel Bloom Sings 'A Karin Tale': Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[brightcove:legacy] AQ~~,AAABIWNF7qE~,EJbsvFObVfJEm7rEo1Xk3nNXqnvaIG9q: Downloading playlist information
ERROR: Empty playlist; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/brightcove.py", line 309, in _real_extract
    return self._get_playlist_info(player_key[0])
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/brightcove.py", line 378, in _get_playlist_info
    raise ExtractorError('Empty playlist')
ExtractorError: Empty playlist; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
