### ISSUE TITLE
Unable to download purchased movie

### ISSUE THREAD

**Issue by notjames** [rg3/youtube-dl#1774]
Attempted to download a purchased movie to see if I could download it via youtube-dl

Unfortunately, the following trace occurred with the run args:

```
$ youtube-dl --verbose -ct -u 'username@domain.com' -p 'password' 'z4l7OZLIh9w'

[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '-ct', '-u', '<PRIVATE>', '-p', '<PRIVATE>', 'z4l7OZLIh9w']
[debug] youtube-dl version 2013.11.15.1
[debug] Python version 2.7.3 - Linux-3.2.0-55-generic-x86_64-with-Ubuntu-12.04-precise
[debug] Proxy map: {}
[youtube] Setting language
[youtube] Logging in
[youtube] Confirming age
[youtube] z4l7OZLIh9w: Downloading video webpage
[youtube] z4l7OZLIh9w: Downloading video info webpage
[youtube] z4l7OZLIh9w: Extracting video information
[youtube] z4l7OZLIh9w: Encrypted signatures detected.
[youtube] encrypted signature length 85 (40.44), itag 60, html5 player vflqSl9GX
[youtube] encrypted signature length 85 (40.44), itag 52, html5 player vflqSl9GX
ERROR: no known formats available for video; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 348, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 125, in extract
    return self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1452, in _real_extract
    video_url_list = self._get_video_url_list(url_map)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1189, in _get_video_url_list
    raise ExtractorError(u'no known formats available for video')
ExtractorError: no known formats available for video; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
```

Also tried specifying mp4. I'll try other formats.

**Comment by mholt** [comment]
Has there been any progress on this?

**Comment by notjames** [comment]
I tried the fix as mentioned above but as memory serves, it did not work. I haven't really messed with it since, however, it would be nice to download the movie I purchased. If I get time, I'll look into it again.

**Comment by voltagex** [comment]
Ping. Any updates on this?

**Comment by NateJackDev** [comment]
Any updates on this?

**Comment by ealgase** [comment]
Yes.  The movie is encrypted with some sort of DRM.  A good movie to try is [https://www.youtube.com/watch?v=s7_qI6_mIXc](https://www.youtube.com/watch?v=s7_qI6_mIXc), as it is free to watch.

**Comment by Fabian42** [comment]
Confirmed for 2019.03.01. Has there been any research into the DRM since 2013?

**Comment by ealgase** [comment]
Doesn't appear to be much research.  It should probably be easy to reverse engineer though.

**Comment by joshobrien91** [comment]
Still interested to see if there has been any further progress on this, as above after exactly 11 seconds the video turns to grey due to DRM protection. 

Unfortunately only avenue to purchase a TV show was via YouTube, assuming I'd be able to save it using yt-dl :(

**Comment by ealgase** [comment]
Unfortunately, nope, that's the same experience everyone faces here.

**Comment by antdude** [comment]
For free official YouTube movies, you can use any from https://www.youtube.com/playlist?list=PLHPTxTxtC0ibVZrT2_WKWUl2SAxsKuKwx to test. I ran into the same problem today. :(

**Comment by Fabian42** [comment]
The behaviour has changed in the lastest version, it now outputs this error message:

>ERROR: Watch this video on YouTube. Playback on other websites has been disabled by the video owner.

That's a weird way to word it for a YouTube downloader (if I use it, I obviously do not want or can not watch it on YouTube), but it's better than downloading 20 minutes and producing data garbage, I guess.

**Comment by jdbodker** [comment]
I'm downloading a purchased tv show, something I grew up on in the 80's, and i'm able to use my credentials to download the file through user and password, but about 8-10 seconds in, the audio cuts out and the video gets super corrupted.  Any changes or solutions??? Thanks

**Comment by vivalamovie** [comment]
> I'm downloading a purchased tv show, something I grew up on in the 80's, and i'm able to use my credentials to download the file through user and password, but about 8-10 seconds in, the audio cuts out and the video gets super corrupted. Any changes or solutions??? Thanks

Same here.

**Comment by 89z** [comment]
Issue should be closed, account needed

**Comment by notjames** [comment]
Out of curiosity, what does the "Account Needed" label mean?

**Comment by zhengliw** [comment]
Any update? I am looking for a way to download my purchased movies but I am not sure if this would work or not.

**Comment by 89z** [comment]
If the movie free, then we just need someone to provide example URL. Otherwise someone would need to share account for testing

**Comment by KevDoy** [comment]
> If the movie free, then we just need someone to provide example URL. Otherwise someone would need to share account for testing

YouTube provides movies for free that have the same DRM as purchased content. 

https://youtube.com/movies see the "free to watch" section.

**Comment by 89z** [comment]
If the movie free, then we just need someone to provide example URL. Otherwise someone would need to share account for testing

**Comment by zhengliw** [comment]
I'm not exactly sure, but the famous "Never Gonna Give You Up" video from Rick Astley seems to be copyrighted and therfore DRM-protected. I am going to try to download that video later (essentially rickrolling myself :/) and report back.

Here is the link if you want to try: https://youtu.be/dQw4w9WgXcQ

**Comment by zhengliw** [comment]
Yep, totally works, but just not sure if this is actually DRM-protected, as said.

**Comment by 89z** [comment]
@zhengliw that has absolutely nothing to do with this issue.

**Comment by zhengliw** [comment]
Sorry... Is there any other way I can help?

**Comment by 89z** [comment]
@zhengliw unless you have experience decrypting DRM, the best thing you could do would be to just stop commenting.
