### ISSUE TITLE
Some sections in telecinco.es aren't working

### ISSUE THREAD

**Issue by andor-pierdelacabeza** [rg3/youtube-dl#17765]
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2018.09.26**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)

---

Seems like this subsection isn't working (I think it's new, so probably it never worked before):
https://www.telecinco.es/granhermanovip/mejor-GH-VIP-Limite-horas_5_2637150001.html

Verbose log:
```~/.local/bin/youtube-dl --verbose https://www.telecinco.es/granhermanovip/mejor-GH-VIP-Limite-horas_5_2637150001.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.telecinco.es/granhermanovip/mejor-GH-VIP-Limite-horas_5_2637150001.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.09.26
[debug] Python version 3.5.3 (CPython) - Linux-4.18.0-0.bpo.1-amd64-x86_64-with-debian-9.5
[debug] exe versions: ffmpeg 3.2.12-1, ffprobe 3.2.12-1
[debug] Proxy map: {}
[Telecinco] mejor-GH-VIP-Limite-horas_5_2637150001: Downloading webpage
ERROR: Unable to extract article; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/agonzalez/.local/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/home/agonzalez/.local/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 507, in extract
    ie_result = self._real_extract(url)
  File "/home/agonzalez/.local/lib/python3.5/site-packages/youtube_dl/extractor/telecinco.py", line 139, in _real_extract
    webpage, 'article'), display_id)['article']
  File "/home/agonzalez/.local/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 977, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract article; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
Although some other subsections work ok and seem to come from the same CDN:

```~/.local/bin/youtube-dl --verbose https://www.telecinco.es/granhermanovip/gh-vip-6/limite-48-horas/limite-48-horas-2--25-09-18/surrealista-Aramis-Fuster-GH-VIP_2_2633430012.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.telecinco.es/granhermanovip/gh-vip-6/limite-48-horas/limite-48-horas-2--25-09-18/surrealista-Aramis-Fuster-GH-VIP_2_2633430012.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.09.26
[debug] Python version 3.5.3 (CPython) - Linux-4.18.0-0.bpo.1-amd64-x86_64-with-debian-9.5
[debug] exe versions: ffmpeg 3.2.12-1, ffprobe 3.2.12-1
[debug] Proxy map: {}
[Telecinco] surrealista-Aramis-Fuster-GH-VIP_2_2633430012: Downloading webpage
[Telecinco] PtpjLWfHLHLYfVxP2Yea56: Downloading config JSON
[Telecinco] PtpjLWfHLHLYfVxP2Yea56: Downloading flash mmc JSON
[Telecinco] PtpjLWfHLHLYfVxP2Yea56: Downloading JSON metadata
[Telecinco] PtpjLWfHLHLYfVxP2Yea56: Downloading f4m manifest
[Telecinco] PtpjLWfHLHLYfVxP2Yea56: Downloading html5 mmc JSON
[Telecinco] PtpjLWfHLHLYfVxP2Yea56: Downloading JSON metadata
[Telecinco] PtpjLWfHLHLYfVxP2Yea56: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://telecinco1-vh.akamaihd.net/i/geo/Pt/pj/PtpjLWfHLHLYfVxP2Yea56/slgozU4dxDk5NrgB9aBse.1200,,.mp4.csmil/index_0_av.m3u8?null=0'
[download] ¡El surrealista desmayo de Aramís Fuster en ‘GH VIP 6’!-PtpjLWfHLHLYfVxP2Yea56.mp4 has already been downloaded
[download] 100% of 41.30MiB
[debug] ffmpeg command line: ffprobe -show_streams 'file:¡El surrealista desmayo de Aramís Fuster en ‘GH VIP 6’!-PtpjLWfHLHLYfVxP2Yea56.mp4'
[ffmpeg] Fixing malformed AAC bitstream in "¡El surrealista desmayo de Aramís Fuster en ‘GH VIP 6’!-PtpjLWfHLHLYfVxP2Yea56.mp4"
[debug] ffmpeg command line: ffmpeg -y -i 'file:¡El surrealista desmayo de Aramís Fuster en ‘GH VIP 6’!-PtpjLWfHLHLYfVxP2Yea56.mp4' -c copy -f mp4 -bsf:a aac_adtstoasc 'file:¡El surrealista desmayo de Aramís Fuster en ‘GH VIP 6’!-PtpjLWfHLHLYfVxP2Yea56.temp.mp4'```

Looks like the internal structure is different on those subsections...

**Comment by 89z** [comment]
geo block:

> Sorry, this content is not available in your country,
> this content is not available in your country
