### ISSUE TITLE
New URL scheme for atresplayer.com

### ISSUE THREAD

**Issue by BlackHoleSpain** [rg3/youtube-dl#17788]
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2018.10.05**
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [X] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other
---
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.atresplayer.com/neox/series/the-big-ban
g-theory/temporada-12/capitulo-1-la-configuracion-conyugal_5bb0eb737ed1a83e98b8d
578/', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.10.05
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 4.0.2, ffprobe 4.0.2, rtmpdump 2.4
[debug] Proxy map: {}
[generic] capitulo-1-la-configuracion-conyugal_5bb0eb737ed1a83e98b8d578: Requesting header WARNING: Falling back on generic information extractor.
[generic] capitulo-1-la-configuracion-conyugal_5bb0eb737ed1a83e98b8d578: Downloading webpage
[generic] capitulo-1-la-configuracion-conyugal_5bb0eb737ed1a83e98b8d578: Extracting information
ERROR: Unsupported URL: https://www.atresplayer.com/neox/series/the-big-bang-theory/temporada-12/capitulo-1-la-configuracion-conyugal_5bb0eb737ed1a83e98b8d578/
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5xdqinp2\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5xdqinp2\build\youtube_dl\extractor\common.py", line 507, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5xdqinp2\build\youtube_dl\extractor\generic.py", line 3298, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.atresplayer.com/neox/series/the-big-bang-theory/temporada-12/capitulo-1-la-configuracion-conyugal_5bb0eb737ed1a83e98b8d578/
---

### Description of your *issue*, suggested solution and other information

atresmedia.com site changed their URL scheme some months ago. When a similar case was opened, another user developed a solution, but in the end his code was never integrated in the main branch. He only changed some Python sources, but we people who only can access Win32 binaries, cannot use his solution. Could you check that, please?

**Comment by BlackHoleSpain** [comment]
It's NOT a duplicate, that open issue was open for a different reason.
