### ISSUE TITLE
Unable to Download HotStar video

### ISSUE THREAD

**Issue by SpEcHiDe** [rg3/youtube-dl#17806]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.10.05*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.10.05**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.hotstar.com/movies/madhuranombarakkattu/1000034564']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.10.05
[debug] Git HEAD: fccf95c
[debug] Python version 3.5.3 (CPython) - Linux-4.9.0-6-amd64-x86_64-with-debian-9.5
[debug] exe versions: ffmpeg 3.2.10-1, ffprobe 3.2.10-1, phantomjs .
[debug] Proxy map: {}
[hotstar] 1000034564: Downloading webpage
ERROR: Unable to extract app state; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/shrimadhav/AnyDLBot/VENV/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/home/shrimadhav/AnyDLBot/VENV/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 507, in extract
    ie_result = self._real_extract(url)
  File "/home/shrimadhav/AnyDLBot/VENV/lib/python3.5/site-packages/youtube_dl/extractor/hotstar.py", line 75, in _real_extract
    webpage, 'app state'), video_id)
  File "/home/shrimadhav/AnyDLBot/VENV/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 977, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract app state; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by parind** [comment]
Seems Hotstar has upped it's protection. Before this update, the videos used to download but another one. What I think is they are added another layer for auth. The m3u8 or mpd link given by the api is same for each and every video, it takes to some "*/cricket2/*" (* means something) which downloads a video around 38mb in size and all the video contains is some text "Update your Hotstar app. Seems you are using an outdated version".

**Comment by remitamine** [comment]
there is no video in https://www.hotstar.com/movies/madhuranombarakkattu/1000034564.
the actual URL of the video is https://www.hotstar.com/movies/madhuranombarakkattu/1000034564/watch.

**Comment by SpEcHiDe** [comment]
Still facing the same issue.

**Comment by remitamine** [comment]
```
[hotstar] 1000034564: Downloading webpage
[hotstar] 1000034564: Downloading JSON metadata
[hotstar] 1000034564: Downloading m3u8 information
[download] Destination: Madhuranombarakkattu-1000034564.mp4
ffmpeg version n4.0.2 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 8.2.0 (GCC)
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-nvdec --enable-nvenc --enable-omx --enable-shared --enable-version3
  libavutil      56. 14.100 / 56. 14.100
  libavcodec     58. 18.100 / 58. 18.100
  libavformat    58. 12.100 / 58. 12.100
  libavdevice    58.  3.100 / 58.  3.100
  libavfilter     7. 16.100 /  7. 16.100
  libswscale      5.  1.100 /  5.  1.100
  libswresample   3.  1.100 /  3.  1.100
  libpostproc    55.  1.100 / 55.  1.100
[tcp @ 0x5589451aa7c0] Connection to tcp://localhost:8080 failed (Connection refused), trying next address
[hls,applehttp @ 0x5589451a55c0] Opening 'https://staragvod3-vh.akamaihd.net/i/videos/worldwide/movies/malayalam/madhuranombarakkattu/1000034564_,16,54,106,180,400,800,1300,2000,3000,4500,_STAR.mp4.csmil/crypt.key?null=0&id=AgCLOxGBFwNGlaHnuFsvjysUGOZHSfct5EsXzSTdfVL8I3HjeriNMQz09YatakdgbZ2Ph2DypgDckA%3d%3d' for reading
[tcp @ 0x5589458a9740] Connection to tcp://localhost:8080 failed (Connection refused), trying next address
[hls,applehttp @ 0x5589451a55c0] Opening 'crypto+http://staragvod3-vh.akamaihd.net/i/videos/worldwide/movies/malayalam/madhuranombarakkattu/1000034564_,16,54,106,180,400,800,1300,2000,3000,4500,_STAR.mp4.csmil/segment1_7_av.ts?null=0&id=AgCLOxGBFwNGlaHnuFsvjysUGOZHSfct5EsXzSTdfVL8I3HjeriNMQz09YatakdgbZ2Ph2DypgDckA%3d%3d' for reading
[tcp @ 0x5589457bf780] Connection to tcp://localhost:8080 failed (Connection refused), trying next address
[NULL @ 0x5589458fa440] non-existing SPS 0 referenced in buffering period
[NULL @ 0x5589458fa440] SPS unavailable in decode_picture_timing
[h264 @ 0x5589458f8740] non-existing SPS 0 referenced in buffering period
[h264 @ 0x5589458f8740] SPS unavailable in decode_picture_timing
Input #0, hls,applehttp, from 'https://staragvod3-vh.akamaihd.net/i/videos/worldwide/movies/malayalam/madhuranombarakkattu/1000034564_,16,54,106,180,400,800,1300,2000,3000,4500,_STAR.mp4.csmil/index_7_av.m3u8?null=0&id=AgCLOxGBFwNGlaHnuFsvjysUGOZHSfct5EsXzSTdfVL8I3HjeriNMQz09YatakdgbZ2Ph2DypgDckA%3d%3d':
  Duration: 02:26:28.52, start: 0.100667, bitrate: 0 kb/s
  Program 0 
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
Output #0, mp4, to 'file:Madhuranombarakkattu-1000034564.mp4.part':
  Metadata:
    encoder         : Lavf58.12.100
    Stream #0:0: Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], q=2-31, 25 fps, 25 tbr, 90k tbn, 90k tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=   24 fps=0.0 q=-1.0 size=     256kB time=00:00:00.98 bitrate=2137.4kbits
```

**Comment by CalvinGA** [comment]
Facing the Same Issue.

**Comment by SpEcHiDe** [comment]
```[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.hotstar.com/movies/madhuranombarakkattu/1000034564/watch', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.10.05
[debug] Git HEAD: fccf95c
[debug] Python version 3.7.0 (CPython) - Linux-4.9.0-6-amd64-x86_64-with-debian-9.5
[debug] exe versions: ffmpeg 3.2.10-1, ffprobe 3.2.10-1, phantomjs .
[debug] Proxy map: {}
[hotstar] 1000034564: Downloading webpage
ERROR: Unable to extract app state; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/shrimadhav/AnyDLBot/venv/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/home/shrimadhav/AnyDLBot/venv/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 507, in extract
    ie_result = self._real_extract(url)
  File "/home/shrimadhav/AnyDLBot/venv/lib/python3.7/site-packages/youtube_dl/extractor/hotstar.py", line 75, in _real_extract
    webpage, 'app state'), video_id)
  File "/home/shrimadhav/AnyDLBot/venv/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 977, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract app state; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

**Comment by remitamine** [comment]
post the output of `youtube-dl -v --dump-pages https://www.hotstar.com/movies/madhuranombarakkattu/1000034564/watch`

**Comment by SpEcHiDe** [comment]
http://ix.io/1oK8 please find the output in the link.

**Comment by remitamine** [comment]
```html
    <h1>Coming soon to Europe!</h1>
    <p>
       Hotstar.com is unavailable for residents in Europe. We continue to work through changes in light of the <a target=\"_blank\" href=\"https://ec.europa.eu/info/law/law-topic/data-protection_en\">General Data Protection Regulation</a> (GDPR), which went into effect May 25, 2018. We apologize for the inconvenience, and intend to launch our services in EU soon. Thank you for your patience.
    </p>

    <p>
      If you are not accessing Hotstar from EU, please check your IP address to ensure you donâ\u0080\u0099t have VPN/Proxy services turned on.
    </p>
```
