### ISSUE TITLE
Errors with http://www.speedvid.net

### ISSUE THREAD

**Issue by jd1p3k80** [rg3/youtube-dl#17844]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.10.05*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.10.05**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
 $ youtube-dl --verbose http://www.speedvid.net/qylg99af10as 
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'http://www.speedvid.net/qylg99af10as']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.10.05
[debug] Python version 3.5.2 (CPython) - Linux-4.8.13-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 3.2.2, ffprobe 3.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[generic] qylg99af10as: Requesting header
WARNING: Could not send HEAD request to http://www.speedvid.net/qylg99af10as: HTTP Error 503: Service Temporarily Unavailable
[generic] qylg99af10as: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 503: Service Temporarily Unavailable (caused by <HTTPError 503: 'Service Temporarily Unavailable'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 604, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2211, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

```

---

### Description of your *issue*, suggested solution and other information

This site now seems to be having trouble:
http://www.speedvid.net

But accessing the urls through the web browser seem to work.

**Comment by jerrydark** [comment]
After some investigation, turns out speedvid.net is using cloudflare ddos protection. I'm currently looking for solution.

**Comment by metulburr** [comment]
is this still an issue? After updating youtube-dl no longer even attempts to even download. It worked before on that site no problem.

```
metulburr@ubuntu:~/kids/puppy_dog_pals/s02$ youtube-dl --version
2019.01.10
metulburr@ubuntu:~/kids/puppy_dog_pals/s02$ youtube-dl https://www.speedvid.net/yg3kpv1ffok3
[generic] yg3kpv1ffok3: Requesting header
WARNING: Could not send HEAD request to https://www.speedvid.net/yg3kpv1ffok3: HTTP Error 403: Forbidden
[generic] yg3kpv1ffok3: Downloading webpage
WARNING: Falling back on generic information extractor.
[generic] yg3kpv1ffok3: Extracting information
ERROR: Unsupported URL: https://www.speedvid.net/yg3kpv1ffok3
metulburr@ubuntu:~/kids/puppy_dog_pals/s02$ youtube-dl --verbose https://www.speedvid.net/yg3kpv1ffok3
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.speedvid.net/yg3kpv1ffok3']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.01.10
[debug] Python version 2.7.12 (CPython) - Linux-4.4.0-141-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 3.4.1-1, avprobe 3.4.1-1, ffmpeg 3.4.1-1, ffprobe 3.4.1-1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] yg3kpv1ffok3: Requesting header
WARNING: Could not send HEAD request to https://www.speedvid.net/yg3kpv1ffok3: HTTP Error 403: Forbidden
[generic] yg3kpv1ffok3: Downloading webpage
WARNING: Falling back on generic information extractor.
[generic] yg3kpv1ffok3: Extracting information
ERROR: Unsupported URL: https://www.speedvid.net/yg3kpv1ffok3
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 2337, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/compat.py", line 2542, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/compat.py", line 2531, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 21, column 19
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 793, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 3320, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.speedvid.net/yg3kpv1ffok3

```

**Comment by jd1p3k80** [comment]
Yes still the same issue for me.
