### ISSUE TITLE
Youtube videos do not download 720p, despite being available on the website.

### ISSUE THREAD

**Issue by cyber** [rg3/youtube-dl#17864]
This problem only occurs on popular videos, for example https://www.youtube.com/watch?v=JQbjS0_ZfJ0.
- When selecting quality like -f 22, it will say not quality available
- When selecting quality using 'bestvideo[ext=mp4]+bestaudio[ext=m4a.... it will also say quality not available which leads me to believe that you can recognize the qualities but not download on popular videos. Maybe youtube uses a different method of storing the raw video for those.

This happens on both the executable and the python lib

**Comment by remitamine** [comment]
```
youtube-dl -f 'bestvideo[height=720][ext=mp4]+bestaudio[ext=m4a]' https://www.youtube.com/watch?v=JQbjS0_ZfJ0
[youtube] JQbjS0_ZfJ0: Downloading webpage
[youtube] JQbjS0_ZfJ0: Downloading video info webpage
[youtube] JQbjS0_ZfJ0: Downloading js player vflO1Ey5k
[download] Destination: Kendrick Lamar, SZA - All The Stars-JQbjS0_ZfJ0.f136.mp4
[download] 100% of 36.94MiB in 00:04
[download] Destination: Kendrick Lamar, SZA - All The Stars-JQbjS0_ZfJ0.f140.m4a
[download] 100% of 3.55MiB in 00:00
[ffmpeg] Merging formats into "Kendrick Lamar, SZA - All The Stars-JQbjS0_ZfJ0.mp4"
Deleting original file Kendrick Lamar, SZA - All The Stars-JQbjS0_ZfJ0.f136.mp4 (pass -k to keep)
Deleting original file Kendrick Lamar, SZA - All The Stars-JQbjS0_ZfJ0.f140.m4a (pass -k to keep)
```

**Comment by cyber** [comment]
@remitamine Error still occurs for me.
```
pip install --upgrade youtube_dl (Its the latest version)

youtube-dl -f 'bestvideo[height=720][ext=mp4]+bestaudio[ext=m4a]' https://www.youtube.com/watch?v=JQbjS0_ZfJ0
[youtube] JQbjS0_ZfJ0: Downloading webpage
[youtube] JQbjS0_ZfJ0: Downloading video info webpage
ERROR: requested format not available
```
Still doesn't work for me, heres the debug:
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-f', u"'bestvideo[height=720][ext=mp4]+bestaudio[ext=m4a]'", u'https://www.youtube.com/watch?v=JQbjS0_ZfJ0', u'-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.10.05
[debug] Python version 2.7.13 (CPython) - Windows-10-10.0.17134
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] JQbjS0_ZfJ0: Downloading webpage
[youtube] JQbjS0_ZfJ0: Downloading video info webpage
[youtube] {18} signature length 40.44, html5 player vflO1Ey5k
[youtube] {36} signature length 40.44, html5 player vflO1Ey5k
[youtube] {17} signature length 40.44, html5 player vflO1Ey5k
[youtube] {137} signature length 40.44, html5 player vflO1Ey5k
[youtube] {248} signature length 40.44, html5 player vflO1Ey5k
[youtube] {136} signature length 40.44, html5 player vflO1Ey5k
[youtube] {247} signature length 40.44, html5 player vflO1Ey5k
[youtube] {135} signature length 40.44, html5 player vflO1Ey5k
[youtube] {244} signature length 40.44, html5 player vflO1Ey5k
[youtube] {397} signature length 40.44, html5 player vflO1Ey5k
[youtube] {134} signature length 40.44, html5 player vflO1Ey5k
[youtube] {243} signature length 40.44, html5 player vflO1Ey5k
[youtube] {396} signature length 40.44, html5 player vflO1Ey5k
[youtube] {133} signature length 40.44, html5 player vflO1Ey5k
[youtube] {242} signature length 40.44, html5 player vflO1Ey5k
[youtube] {395} signature length 40.44, html5 player vflO1Ey5k
[youtube] {160} signature length 40.44, html5 player vflO1Ey5k
[youtube] {278} signature length 40.44, html5 player vflO1Ey5k
[youtube] {394} signature length 40.44, html5 player vflO1Ey5k
[youtube] {140} signature length 40.44, html5 player vflO1Ey5k
[youtube] {171} signature length 40.44, html5 player vflO1Ey5k
[youtube] {249} signature length 40.44, html5 player vflO1Ey5k
[youtube] {250} signature length 40.44, html5 player vflO1Ey5k
[youtube] {251} signature length 40.44, html5 player vflO1Ey5k
ERROR: requested format not available
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 803, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "c:\python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 857, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "c:\python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 1627, in process_video_result
    expected=True)
ExtractorError: requested format not available
```

**Comment by remitamine** [comment]
For Windows you have to use the double quotes:
`youtube-dl -f "bestvideo[height=720][ext=mp4]+bestaudio[ext=m4a]" https://www.youtube.com/watch?v=JQbjS0_ZfJ0`
