### ISSUE TITLE
Bloomberg video broken

### ISSUE THREAD

**Issue by fbgameresearch** [rg3/youtube-dl#17875]
```
The url doesn't specify the protocol, trying with http
[Bloomberg] -bloomberg-markets-the-close-full-show-10-12-2018-video: Downloading webpage
ERROR: Unable to extract id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 507, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python2.7/site-packages/youtube_dl/extractor/bloomberg.py", line 58, in _real_extract
    r'BPlayer\(null,\s*({[^;]+})\);', webpage, 'id'), name)
  File "/usr/local/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 977, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by fbgameresearch** [comment]
@dstftw Why is this closed?

**Comment by shirishag75** [comment]
It is closed because enough info. was not given. Let me give it a shot in a new issue.
