### ISSUE TITLE
Support of gotowebinar

### ISSUE THREAD

**Issue by nara20** [rg3/youtube-dl#17896]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.10.05*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.10.05**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ x] Feature request (request for a new functionality)

------------------------------------------------
Is it possible that YouTube-dl support gotowebinar.com url, please ?
Thanks for advance...
------------------------------------------------
Hi,
youtube-dl.exe "https://register.gotowebinar.com/recording/recordingView?webinarKey=323480013258908683&registrantEmail=toto.titi%40tata.com" -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://register.gotowebinar.com/recording/recordingView?webinarKey=323480013258908683&registrantEmail=toto.titi%40tata.com', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.10.05
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg N-91206-g9827bb88e7
[debug] Proxy map: {}
[generic] recordingView?webinarKey=323480013258908683&registrantEmail=toto.titi@tata: Requesting header
WARNING: Falling back on generic information extractor.
[generic] recordingView?webinarKey=323480013258908683&registrantEmail=toto.titi@tata: Downloading webpage
[generic] recordingView?webinarKey=323480013258908683&registrantEmail=toto.titi@tata: Extracting information
ERROR: Unsupported URL: https://register.gotowebinar.com/recording/recordingView?webinarKey=323480013258908683&registrantEmail=toto.titi%40tata.com
Traceback (most recent call last):
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5xdqinp2\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5xdqinp2\build\youtube_dl\extractor\common.py", line 507, in extract
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5xdqinp2\build\youtube_dl\extractor\generic.py", line 3298, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://register.gotowebinar.com/recording/recordingView?webinarKey=323480013258908683&registrantEmail=toto.titi%40tata.com
Regards
Nara

**Comment by jpeacock29** [comment]
For now a straightforward work around is provided [here](https://www.youtube.com/watch?v=WxDpnue99vk). It seems like this wouldn't be difficult to implement.

**Comment by BakasuraRCE** [comment]
+1

**Comment by jnahmias** [comment]
This is still an issue in 2020.05.08.

**Comment by mrkaragoz** [comment]
This is still an issue in 2021.03.14
