### ISSUE TITLE
[cc.com] Converting scc subtitles to srt error

### ISSUE THREAD

**Issue by goonis** [rg3/youtube-dl#17892]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.10.05*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.10.05**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
D:\Utils\Youtube-DL>youtube-dl.exe -v -f best --write-sub --convert-subtitles srt http://www.cc.com/episodes/cznh14/comedy-central-stand-up-presents-ryan-o-flanagan-season-2-ep-205

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-f', 'best', '--write-sub', '--convert-subtitles', 'srt', 'http://www.cc.com/episodes/cznh14/comedy-central-stand-up-presents-ryan-o-flanagan-season-2-ep-205']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2018.10.05
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-80924-gb450b82, ffprobe N-80924-gb450b82
[debug] Proxy map: {}
[ComedyCentral] comedy-central-stand-up-presents-ryan-o-flanagan-season-2-ep-205: Downloading webpage
[ComedyCentral] Downloading JSON metadata
[ComedyCentral] 0a61e452-34a8-11e8-bfd4-0026b9414f30: Downloading info
[ComedyCentral] 05bf4680-0c76-4e11-9eb5-0b0cdc13b451: Extracting information
[ComedyCentral] 05bf4680-0c76-4e11-9eb5-0b0cdc13b451: Downloading video urls
[ComedyCentral] 05bf4680-0c76-4e11-9eb5-0b0cdc13b451: Downloading m3u8 information
[ComedyCentral] c4d7aaf1-b675-478b-8bc5-081d1de31bf5: Extracting information
[ComedyCentral] c4d7aaf1-b675-478b-8bc5-081d1de31bf5: Downloading video urls
[ComedyCentral] c4d7aaf1-b675-478b-8bc5-081d1de31bf5: Downloading m3u8 information
[ComedyCentral] a773a33e-cc62-414c-8254-f7e0cdd2540f: Extracting information
[ComedyCentral] a773a33e-cc62-414c-8254-f7e0cdd2540f: Downloading video urls
[ComedyCentral] a773a33e-cc62-414c-8254-f7e0cdd2540f: Downloading m3u8 information
[ComedyCentral] 47d52ae8-7491-4393-990b-ea22ebd75b70: Extracting information
[ComedyCentral] 47d52ae8-7491-4393-990b-ea22ebd75b70: Downloading video urls
[ComedyCentral] 47d52ae8-7491-4393-990b-ea22ebd75b70: Downloading m3u8 information
[ComedyCentral] 6aac0119-d97f-4c9c-85c0-ed126b396a63: Extracting information
[ComedyCentral] 6aac0119-d97f-4c9c-85c0-ed126b396a63: Downloading video urls
[ComedyCentral] 6aac0119-d97f-4c9c-85c0-ed126b396a63: Downloading m3u8 information
[download] Downloading playlist: Ryan O'Flanagan
[ComedyCentral] playlist Ryan O'Flanagan: Collected 5 video ids (downloading 5 of them)
[download] Downloading video 1 of 5
[info] Writing video subtitles to: Comedy Central Stand-Up Presents_October 13, 2018_2_205_Ryan O'Flanagan_Act 1-05bf4680-0c76-4e11-9eb5-0b0cdc13b451.en.scc
[debug] Invoking downloader on 'https://dlvrsvc.mtvnservices.com/api/playlist/gsp.alias/mediabus/comedy.com/2018/10/08/01/18/30/7b17d555371041f187b0c2072b165aab/1936394/0/stream_19
20x1080_4419156.m3u8?tk=st=1539551125~exp=1539565525~acl=/api/playlist/gsp.alias/mediabus/comedy.com/2018/10/08/01/18/30/7b17d555371041f187b0c2072b165aab/1936394/0/stream_1920x1080_4419156.m3u8*~hmac=c0765aa5e6f59d1036e42083c787ed653e79ad5ab0f8292f58c9ebbac8be6933&account=comedycentral.com'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 72
[download] Destination: Comedy Central Stand-Up Presents_October 13, 2018_2_205_Ryan O'Flanagan_Act 1-05bf4680-0c76-4e11-9eb5-0b0cdc13b451.mp4
[download] 100% of 233.37MiB in 03:48
[debug] ffmpeg command line: ffprobe -show_streams "file:Comedy Central Stand-Up Presents_October 13, 2018_2_205_Ryan O'Flanagan_Act 1-05bf4680-0c76-4e11-9eb5-0b0cdc13b451.mp4"
[ffmpeg] Fixing malformed AAC bitstream in "Comedy Central Stand-Up Presents_October 13, 2018_2_205_Ryan O'Flanagan_Act 1-05bf4680-0c76-4e11-9eb5-0b0cdc13b451.mp4"
[debug] ffmpeg command line: ffmpeg -y -i "file:Comedy Central Stand-Up Presents_October 13, 2018_2_205_Ryan O'Flanagan_Act 1-05bf4680-0c76-4e11-9eb5-0b0cdc13b451.mp4" -c copy -f mp4 "-bsf:a" aac_adtstoasc "file:Comedy Central Stand-Up Presents_October 13, 2018_2_205_Ryan O'Flanagan_Act 1-05bf4680-0c76-4e11-9eb5-0b0cdc13b451.temp.mp4"
[ffmpeg] Converting subtitles
[debug] ffmpeg command line: ffmpeg -y -i "file:Comedy Central Stand-Up Presents_October 13, 2018_2_205_Ryan O'Flanagan_Act 1-05bf4680-0c76-4e11-9eb5-0b0cdc13b451.en.scc" -f srt "file:Comedy Central Stand-Up Presents_October 13, 2018_2_205_Ryan O'Flanagan_Act 1-05bf4680-0c76-4e11-9eb5-0b0cdc13b451.en.srt"
ERROR: file:Comedy Central Stand-Up Presents_October 13, 2018_2_205_Ryan O'Flanagan_Act 1-05bf4680-0c76-4e11-9eb5-0b0cdc13b451.en.scc: Invalid data found when processing input
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5xdqinp2\build\youtube_dl\YoutubeDL.py", line 2047, in post_process
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5xdqinp2\build\youtube_dl\postprocessor\ffmpeg.py", line 605, in run
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5xdqinp2\build\youtube_dl\postprocessor\ffmpeg.py", line 208, in run_ffmpeg
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5xdqinp2\build\youtube_dl\postprocessor\ffmpeg.py", line 204, in run_ffmpeg_multiple_files
youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError: file:Comedy Central Stand-Up Presents_October 13, 2018_2_205_Ryan O'Flanagan_Act 1-05bf4680-0c76-4e11-9eb5-0b0cdc13b451.en.scc: Invalid data found when processing input
```

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

Subtitles in scc format on cc.com doesn't convert to srt with youtube-dl.
Any external software (like Subtitle Edit for example) converts the same scc subtitles to srt without problem.

**Comment by remitamine** [comment]
update ffmpeg:
```
youtube-dl --sub-format scc --write-sub --convert-subtitles srt http://www.cc.com/episodes/cznh14/comedy-central-stand-up-presents-ryan-o-flanagan-season-2-ep-205
[ComedyCentral] comedy-central-stand-up-presents-ryan-o-flanagan-season-2-ep-205: Downloading webpage
[ComedyCentral] Downloading JSON metadata
[ComedyCentral] 0a61e452-34a8-11e8-bfd4-0026b9414f30: Downloading info
[ComedyCentral] 05bf4680-0c76-4e11-9eb5-0b0cdc13b451: Extracting information
[ComedyCentral] 05bf4680-0c76-4e11-9eb5-0b0cdc13b451: Downloading video urls
[ComedyCentral] 05bf4680-0c76-4e11-9eb5-0b0cdc13b451: Downloading m3u8 information
[ComedyCentral] c4d7aaf1-b675-478b-8bc5-081d1de31bf5: Extracting information
[ComedyCentral] c4d7aaf1-b675-478b-8bc5-081d1de31bf5: Downloading video urls
[ComedyCentral] c4d7aaf1-b675-478b-8bc5-081d1de31bf5: Downloading m3u8 information
[ComedyCentral] a773a33e-cc62-414c-8254-f7e0cdd2540f: Extracting information
[ComedyCentral] a773a33e-cc62-414c-8254-f7e0cdd2540f: Downloading video urls
[ComedyCentral] a773a33e-cc62-414c-8254-f7e0cdd2540f: Downloading m3u8 information
[ComedyCentral] 47d52ae8-7491-4393-990b-ea22ebd75b70: Extracting information
[ComedyCentral] 47d52ae8-7491-4393-990b-ea22ebd75b70: Downloading video urls
[ComedyCentral] 47d52ae8-7491-4393-990b-ea22ebd75b70: Downloading m3u8 information
[ComedyCentral] 6aac0119-d97f-4c9c-85c0-ed126b396a63: Extracting information
[ComedyCentral] 6aac0119-d97f-4c9c-85c0-ed126b396a63: Downloading video urls
[ComedyCentral] 6aac0119-d97f-4c9c-85c0-ed126b396a63: Downloading m3u8 information
[download] Downloading playlist: Ryan O'Flanagan
[ComedyCentral] playlist Ryan O'Flanagan: Collected 5 video ids (downloading 5 of them)
[download] Downloading video 1 of 5
[info] Writing video subtitles to: Comedy Central Stand-Up Presents_October 13, 2018_2_205_Ryan O'Flanagan_Act 1-05bf4680-0c76-4e11-9eb5-0b0cdc13b451.en.scc
[download] Destination: Comedy Central Stand-Up Presents_October 13, 2018_2_205_Ryan O'Flanagan_Act 1-05bf4680-0c76-4e11-9eb5-0b0cdc13b451.mp4
ffmpeg version n4.0.2 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 8.2.0 (GCC)
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-nvdec --enable-nvenc --enable-omx --enable-shared --enable-version3
  libavutil      56. 14.100 / 56. 14.100
  libavcodec     58. 18.100 / 58. 18.100
  libavformat    58. 12.100 / 58. 12.100
  libavdevice    58.  3.100 / 58.  3.100
  libavfilter     7. 16.100 /  7. 16.100
  libswscale      5.  1.100 /  5.  1.100
  libswresample   3.  1.100 /  3.  1.100
  libpostproc    55.  1.100 / 55.  1.100
[hls,applehttp @ 0x557d237d4580] Opening 'https://keysvc.mtvnservices.com/get/encrypt.key?acl=gsp.alias/mediabus/comedy.com/2018/10/08/01/18/30/7b17d555371041f187b0c2072b165aab/1936394/0&tk=st=1539582736~exp=1539597136~acl=/get/encrypt.key?acl=gsp.alias/mediabus/comedy.com/2018/10/08/01/18/30/7b17d555371041f187b0c2072b165aab/1936394/0*~hmac=b258b8a6ab66b4d91727ae820f24ba833dafeba3ef8fc2e590f5bd8fb6c480ab' for reading
[hls,applehttp @ 0x557d237d4580] Opening 'crypto+https://cc-l3.ts.mtvnservices.com/gsp.alias/mediabus/comedy.com/2018/10/08/01/18/30/7b17d555371041f187b0c2072b165aab/1936394/0/seg_1280x720_1889754_0.ts' for reading
Input #0, hls,applehttp, from 'https://dlvrsvc.mtvnservices.com/api/playlist/gsp.alias/mediabus/comedy.com/2018/10/08/01/18/30/7b17d555371041f187b0c2072b165aab/1936394/0/stream_1280x720_1889754.m3u8?tk=st=1539581945~exp=1539596345~acl=/api/playlist/gsp.alias/mediabus/comedy.com/2018/10/08/01/18/30/7b17d555371041f187b0c2072b165aab/1936394/0/stream_1280x720_1889754.m3u8*~hmac=474da099296a67222de5d152ff8f79c4bf036ecd77f4101dcc5ea23afd35934d&account=comedycentral.com':
  Duration: 00:07:08.68, start: 0.000000, bitrate: 0 kb/s
  Program 0 
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 90k tbn, 47.95 tbc
    Metadata:
      variant_bitrate : 0
Output #0, mp4, to 'file:Comedy Central Stand-Up Presents_October 13, 2018_2_205_Ryan O'Flanagan_Act 1-05bf4680-0c76-4e11-9eb5-0b0cdc13b451.mp4.part':
  Metadata:
    encoder         : Lavf58.12.100
    Stream #0:0: Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], q=2-31, 23.98 fps, 23.98 tbr, 90k tbn, 90k tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
Stream mapping:
  Stream #0:1 -> #0:0 (copy)
  Stream #0:0 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=   33 fps=0.0 q=-1.0 size=     512kB time=00:00:01.45 bitrate=2891.6kbits
...
frame=10278 fps= 54 q=-1.0 Lsize=   99002kB time=00:07:08.65 bitrate=1892.0kbits/s speed=2.24x    
video:91981kB audio:6698kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.325961%
[ffmpeg] Downloaded 101377624 bytes
[download] 100% of 96.68MiB in 03:13
[ffmpeg] Fixing malformed AAC bitstream in "Comedy Central Stand-Up Presents_October 13, 2018_2_205_Ryan O'Flanagan_Act 1-05bf4680-0c76-4e11-9eb5-0b0cdc13b451.mp4"
[ffmpeg] Converting subtitles
Deleting original file Comedy Central Stand-Up Presents_October 13, 2018_2_205_Ryan O'Flanagan_Act 1-05bf4680-0c76-4e11-9eb5-0b0cdc13b451.en.scc (pass -k to keep)
```
