### ISSUE TITLE
geo or proxy problem Viki

### ISSUE THREAD

**Issue by apt425410** [rg3/youtube-dl#17913]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.10.05*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ ] I've **verified** and **I assure** that I'm running youtube-dl **2018.10.05**

### Before submitting an *issue* make sure you have:
- [ ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2018.10.05
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

![image](https://user-images.githubusercontent.com/27874509/47133077-41477500-d2d1-11e8-99e1-23038be08cb6.png)

follow image , i can watch on brower without vpn why youtube-dl say Sorry "this content is not available in your region"

**Comment by apt425410** [comment]
ykdl https://www.viki.com/videos/1124274v-nirvana-in-fire-2-episode-1
Traceback (most recent call last):
  File "c:\users\apt\appdata\local\programs\python\python37-32\lib\site-packages\ykdl\common.py", line 38, in url_to_module
    m = import_module('.'.join(['ykdl','extractors', short_name]))
  File "c:\users\apt\appdata\local\programs\python\python37-32\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'ykdl.extractors.viki'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\apt\Downloads\Downloader\ykdl-script.py", line 11, in <module>
    load_entry_point('ykdl==1.6.2', 'console_scripts', 'ykdl')()
  File "c:\users\apt\appdata\local\programs\python\python37-32\lib\site-packages\cykdl\__main__.py", line 168, in main
    m,u = url_to_module(url)
  File "c:\users\apt\appdata\local\programs\python\python37-32\lib\site-packages\ykdl\common.py", line 46, in url_to_module
    new_url = get_location(url, headers = {})
  File "c:\users\apt\appdata\local\programs\python\python37-32\lib\site-packages\ykdl\util\html.py", line 46, in get_location
    response = urlopen(Request(url, headers = headers))
  File "c:\users\apt\appdata\local\programs\python\python37-32\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "c:\users\apt\appdata\local\programs\python\python37-32\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "c:\users\apt\appdata\local\programs\python\python37-32\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\users\apt\appdata\local\programs\python\python37-32\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "c:\users\apt\appdata\local\programs\python\python37-32\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "c:\users\apt\appdata\local\programs\python\python37-32\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
![image](https://user-images.githubusercontent.com/27874509/47218754-07f92d00-d3d7-11e8-91b4-d1200a0076ff.png)
