### ISSUE TITLE
Cannot download vimeo video

### ISSUE THREAD

**Issue by mcepl** [rg3/youtube-dl#1793]
```
matej@wycliff: ~$ youtube-dl --verbose 'http://vimeo.com/groups/pcf/videos/79724250'
[debug] System config: ['--prefer-free-formats']
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://vimeo.com/groups/pcf/videos/79724250']
[debug] youtube-dl version 2013.09.24.2
[debug] Python version 2.7.5 - Linux-3.10.0-50.el7.x86_64-x86_64-with-redhat-7.0-Maipo
[debug] Proxy map: {}
[vimeo] 79724250: Downloading webpage
[vimeo] 79724250: Extracting information
ERROR: Unable to extract info section; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/extractor/vimeo.py", line 126, in _real_extract
    webpage, u'info section', flags=re.DOTALL)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 237, in _search_regex
    raise ExtractorError(u'Unable to extract %s' % _name)
ExtractorError: Unable to extract info section; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 334, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 103, in extract
    return self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/vimeo.py", line 136, in _real_extract
    raise ExtractorError(u'Unable to extract info section')
ExtractorError: Unable to extract info section; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

matej@wycliff: ~$ 
```

**Comment by lcguida** [comment]
I'm getting this error in the version 2014.02.17 on a Ubuntu 14.04 machine. 

```
youtube-dl -v http://vimeo.com/12705404
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://vimeo.com/12705404']
[debug] Encodings: locale 'UTF-8', fs 'UTF-8', out 'UTF-8', pref: 'UTF-8'
[debug] youtube-dl version 2014.02.17
[debug] Python version 2.7.6 - Linux-3.13.0-43-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] Proxy map: {}
[vimeo] 12705404: Downloading webpage
[vimeo] 12705404: Extracting information
[vimeo] 12705404: Downloading webpage
Traceback (most recent call last):
  File "/usr/bin/youtube-dl", line 6, in <module>
    youtube_dl.main()
  File "/usr/lib/python2.7/dist-packages/youtube_dl/__init__.py", line 804, in main
    _real_main(argv)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/__init__.py", line 794, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 982, in download
    self.extract_info(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 493, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 158, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/vimeo.py", line 223, in _real_extract
    _, video_thumbnail = sorted((int(width), t_url) for (width, t_url) in config["video"]["thumbs"].items())[-1]
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/vimeo.py", line 223, in <genexpr>
    _, video_thumbnail = sorted((int(width), t_url) for (width, t_url) in config["video"]["thumbs"].items())[-1]
ValueError: invalid literal for int() with base 10: 'base'
```

**Comment by phihag** [comment]
@lcguida That version is close to a year old. See [our FAQ](https://yt-dl.org/update) on how to update.

**Comment by lcguida** [comment]
Missed that one. 

I was using apt ans the version there is pretty outdated. Re-installed with pip and worked.
