### ISSUE TITLE
[youtube] ExtractorError: This video is not available (with latest version only)

### ISSUE THREAD

**Issue by hedii** [rg3/youtube-dl#17937]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.10.05*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.10.05**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl -v https://www.youtube.com/watch?v=FoC-sV1KmXA
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=FoC-sV1KmXA']
WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
[debug] youtube-dl version 2018.10.05
[debug] Python version 2.7.13 (CPython) - Linux-4.9.127-xxxx-std-ipv6-64-x86_64-with-debian-9.5
[debug] exe versions: ffmpeg 3.2.12-1, ffprobe 3.2.12-1
[debug] Proxy map: {}
[youtube] FoC-sV1KmXA: Downloading webpage
[youtube] FoC-sV1KmXA: Downloading video info webpage
ERROR: This video is not available.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 507, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 1897, in _real_extract
    raise ExtractorError(error_message, expected=True)
ExtractorError: This video is not available.
```

### Description of your *issue*, suggested solution and other information

I can access this video from my browser in France : https://www.youtube.com/watch?v=FoC-sV1KmXA
I get an error running latest youtube-dl (2018.10.05) from multiple servers located in France to download the same video (see log above).

I do not have any problem downloading this video with a youtube-dl older version (2018.09.18), see log below:

```
youtube-dl -v https://www.youtube.com/watch\?v\=FoC-sV1KmXA
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=FoC-sV1KmXA']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.09.18
[debug] Python version 2.7.15 (CPython) - Darwin-18.0.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.0.2, ffprobe 4.0.2
[debug] Proxy map: {}
[youtube] FoC-sV1KmXA: Downloading webpage
[youtube] FoC-sV1KmXA: Downloading video info webpage
[youtube] {22} signature length 44.40, html5 player vflICk6QU
[youtube] {43} signature length 44.40, html5 player vflICk6QU
[youtube] {18} signature length 44.40, html5 player vflICk6QU
[youtube] {36} signature length 44.40, html5 player vflICk6QU
[youtube] {17} signature length 44.40, html5 player vflICk6QU
[youtube] {137} signature length 44.40, html5 player vflICk6QU
[youtube] {248} signature length 44.40, html5 player vflICk6QU
[youtube] {136} signature length 44.40, html5 player vflICk6QU
[youtube] {247} signature length 44.40, html5 player vflICk6QU
[youtube] {135} signature length 44.40, html5 player vflICk6QU
[youtube] {244} signature length 44.40, html5 player vflICk6QU
[youtube] {134} signature length 44.40, html5 player vflICk6QU
[youtube] {243} signature length 44.40, html5 player vflICk6QU
[youtube] {133} signature length 44.40, html5 player vflICk6QU
[youtube] {242} signature length 44.40, html5 player vflICk6QU
[youtube] {160} signature length 44.40, html5 player vflICk6QU
[youtube] {278} signature length 44.40, html5 player vflICk6QU
[youtube] {140} signature length 44.40, html5 player vflICk6QU
[youtube] {171} signature length 44.40, html5 player vflICk6QU
[youtube] {249} signature length 44.40, html5 player vflICk6QU
[youtube] {250} signature length 44.40, html5 player vflICk6QU
[youtube] {251} signature length 44.40, html5 player vflICk6QU
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on u'https://r7---sn-4gxx-hgnz.googlevideo.com/videoplayback?ei=mUbMW_7NDYeCxgKJsJ6QAQ&mm=31%2C29&ipbits=0&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&sparams=aitags%2Cclen%2Cdur%2Cei%2Cgcr%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpl%2Crequiressl%2Csource%2Cexpire&requiressl=yes&itag=137&fvip=11&dur=90.560&lmt=1540060062372051&keepalive=yes&nh=%2CEAE&expire=1540135673&pl=23&mime=video%2Fmp4&key=yt6&initcwndbps=513750&c=WEB&id=o-AFGefFqznkUvJr2PlxtxqGQ69galKHY8UrfO36jGp4yr&source=youtube&gir=yes&clen=32790135&mn=sn-4gxx-hgnz%2Csn-4gxx-25ge7&gcr=fr&ms=au%2Crdu&mt=1540113972&mv=m&txp=5432432&ip=82.228.83.80&signature=1DAEA3A95F145075DDCAA9252946E9874ED5C793.1C430B75FF6C188013EE3E62815CF07FD9856C74&ratebypass=yes'
[download] Destination: Il était une fois... L'Homme - Le générique de début-FoC-sV1KmXA.f137.mp4
[download] 100% of 31.27MiB in 00:11
[debug] Invoking downloader on u'https://r7---sn-4gxx-hgnz.googlevideo.com/videoplayback?ei=mUbMW_7NDYeCxgKJsJ6QAQ&mm=31%2C29&ipbits=0&sparams=clen%2Cdur%2Cei%2Cgcr%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpl%2Crequiressl%2Csource%2Cexpire&requiressl=yes&itag=251&fvip=11&dur=90.581&lmt=1540060774039468&keepalive=yes&nh=%2CEAE&expire=1540135673&pl=23&mime=audio%2Fwebm&key=yt6&initcwndbps=513750&c=WEB&id=o-AFGefFqznkUvJr2PlxtxqGQ69galKHY8UrfO36jGp4yr&source=youtube&gir=yes&clen=1676846&mn=sn-4gxx-hgnz%2Csn-4gxx-25ge7&gcr=fr&ms=au%2Crdu&mt=1540113972&mv=m&txp=5411222&ip=82.228.83.80&signature=13EF83270875B3630E49D6909186D4A2CF5B0372.4413A84067716AA4EF56DAD35725702AB77BE49F&ratebypass=yes'
[download] Destination: Il était une fois... L'Homme - Le générique de début-FoC-sV1KmXA.f251.webm
[download] 100% of 1.60MiB in 00:00
[ffmpeg] Merging formats into "Il était une fois... L'Homme - Le générique de début-FoC-sV1KmXA.mkv"
[debug] ffmpeg command line: ffmpeg -y -i 'file:Il était une fois... L'"'"'Homme - Le générique de début-FoC-sV1KmXA.f137.mp4' -i 'file:Il était une fois... L'"'"'Homme - Le générique de début-FoC-sV1KmXA.f251.webm' -c copy -map '0:v:0' -map '1:a:0' 'file:Il était une fois... L'"'"'Homme - Le générique de début-FoC-sV1KmXA.temp.mkv'
Deleting original file Il était une fois... L'Homme - Le générique de début-FoC-sV1KmXA.f137.mp4 (pass -k to keep)
Deleting original file Il était une fois... L'Homme - Le générique de début-FoC-sV1KmXA.f251.webm (pass -k to keep)
```

**Comment by dstftw** [comment]
Can you watch it in browser from exactly the same machine and exactly the same network interface where youtube-dl fails?

**Comment by hedii** [comment]
@dstfw is there any way you are aware of doing a browser test on a Linux server? Please don’t close, I will try to find one.

Is it ok if I do a curl request on the 2 dash url?

**Comment by dstftw** [comment]
Open a SSH tunnel to the Linux server from client and setup SOCKS proxy in browser.
Most likely server's IP is not recognized by youtube as from FR.

**Comment by hedii** [comment]
Well...

```
curl -I https://www.youtube.com/watch?v=FoC-sV1KmXA
HTTP/2 404
x-frame-options: SAMEORIGIN
strict-transport-security: max-age=31536000
cache-control: no-cache
content-type: text/html; charset=utf-8
x-xss-protection: 1; mode=block; report=https://www.google.com/appserve/security-bugs/log/youtube
expires: Tue, 27 Apr 1971 19:44:06 EST
x-content-type-options: nosniff
p3p: CP="This is not a P3P policy! See http://support.google.com/accounts/answer/151657?hl=en for more info."
date: Sun, 21 Oct 2018 10:04:14 GMT
server: YouTube Frontend Proxy
set-cookie: VISITOR_INFO1_LIVE=zDSxvdoUVVg; path=/; domain=.youtube.com; expires=Fri, 19-Apr-2019 10:04:14 GMT; httponly
set-cookie: GPS=1; path=/; domain=.youtube.com; expires=Sun, 21-Oct-2018 10:34:14 GMT
set-cookie: YSC=VqMGtCRFgAY; path=/; domain=.youtube.com; httponly
alt-svc: quic=":443"; ma=2592000; v="44,43,39,35"
accept-ranges: none
vary: Accept-Encoding
```
