### ISSUE TITLE
Youtube-dl RegexNotFoundError

### ISSUE THREAD

**Issue by mensaguy** [rg3/youtube-dl#17995]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.10.05*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X ] I've **verified** and **I assure** that I'm running youtube-dl **2018.10.05**

### Before submitting an *issue* make sure you have:
- [X ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
eakin@eakin-Inspiron-5555:~$ sudo youtube-dl --update
youtube-dl is up-to-date (2018.10.05)
eakin@eakin-Inspiron-5555:~$ youtube-dl --verbose -f '(mp4,mkv)[height<=480]' -o ~/Videos/Sentdex/How_to_Build_a_Computer_and_Overclock_It/%\(title\)s.%\(ext\)s https://www.youtube.com/playlist?list=PLQVvvaa0QuDcb8DSkkmhkOjrBssY45sYo
[debug] System config: []
[debug] User config: ['-f', '(mp4,mkv)[height<=480]', '-o', '~/Videos/%(title)s.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-f', '(mp4,mkv)[height<=480]', '-o', '/home/eakin/Videos/Sentdex/How_to_Build_a_Computer_and_Overclock_It/%(title)s.%(ext)s', 'https://www.youtube.com/playlist?list=PLQVvvaa0QuDcb8DSkkmhkOjrBssY45sYo']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.03.14
[debug] Python version 3.6.6 (CPython) - Linux-4.15.0-23-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.4-0ubuntu0.18.04.1, ffprobe 3.4.4-0ubuntu0.18.04.1, phantomjs ., rtmpdump 2.4
[debug] Proxy map: {}
[youtube:playlist] PLQVvvaa0QuDcb8DSkkmhkOjrBssY45sYo: Downloading webpage
[download] Downloading playlist: How to Build a Computer and Overclock it
[youtube:playlist] playlist How to Build a Computer and Overclock it: Downloading 14 videos
[download] Downloading video 1 of 14
[youtube] 1c0tRZ5T590: Downloading webpage
[youtube] 1c0tRZ5T590: Downloading video info webpage
[youtube] 1c0tRZ5T590: Extracting video information
[debug] Invoking downloader on 'https://r4---sn-vgqs7nlz.googlevideo.com/videoplayback?source=youtube&requiressl=yes&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&fvip=2&ip=69.81.74.92&mm=31%2C29&itag=18&ipbits=0&id=o-AGvh-j4LRhXmpdNeTjL6uq3_861Np6W9zyjUfdtO2Fp7&pl=22&ms=au%2Crdu&mt=1540700029&mv=m&mime=video%2Fmp4&key=yt6&ei=9DfVW4r1DpeYiwThxay4Cg&expire=1540721748&c=WEB&signature=464BB6DE2296A9118630747885563715C8FE8611.2B739DADB30F6FFF443A3E00E8856CBFE664D94C&initcwndbps=1561250&clen=8477915&gir=yes&mn=sn-vgqs7nlz%2Csn-vgqskn7z&ratebypass=yes&dur=228.368&lmt=1374433574846404&beids=9466585'
[download] /home/eakin/Videos/Sentdex/How_to_Build_a_Computer_and_Overclock_It/How to build a computer Part 1 - Getting Started.mp4 has already been downloaded
[download] 100% of 8.09MiB
[download] Downloading video 2 of 14
[youtube] MVDBxnSXBiQ: Downloading webpage
[youtube] MVDBxnSXBiQ: Downloading video info webpage
[youtube] MVDBxnSXBiQ: Extracting video information
[debug] Invoking downloader on 'https://r6---sn-vgqsrn7d.googlevideo.com/videoplayback?ratebypass=yes&signature=11AD1CFC2C187CFE0A15E2F37CFB67DAF32411D2.3989C024CB22670C76573C4219316F5F9CAD438D&requiressl=yes&beids=9466585&initcwndbps=1545000&key=yt6&gir=yes&mime=video%2Fmp4&dur=517.294&ipbits=0&expire=1540721750&lmt=1374434482871307&fvip=5&pl=22&itag=18&ei=9jfVW5WtEYKUiwTjrZbIBw&source=youtube&mn=sn-vgqsrn7d%2Csn-p5qlsnsr&mm=31%2C26&id=o-AHoNnh22NGT0__q8eOmodLUE4WVOD1E8rLF91BItYPxH&c=WEB&clen=23479248&ip=69.81.74.92&mv=m&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&mt=1540700029&ms=au%2Conr'
[download] /home/eakin/Videos/Sentdex/How_to_Build_a_Computer_and_Overclock_It/How to build a computer Tutorial Part 2.mp4 has already been downloaded
[download] 100% of 22.39MiB
[download] Downloading video 3 of 14
[youtube] CWp_MBkBEZY: Downloading webpage
[youtube] CWp_MBkBEZY: Downloading video info webpage
[youtube] CWp_MBkBEZY: Extracting video information
[debug] Invoking downloader on 'https://r1---sn-vgqsknek.googlevideo.com/videoplayback?mime=video%2Fmp4&pl=22&ip=69.81.74.92&expire=1540721752&clen=32159098&beids=9466585&key=yt6&ratebypass=yes&source=youtube&dur=411.271&lmt=1460588377494518&ipbits=0&requiressl=yes&gir=yes&signature=6D463DB5E864BD379692FD7B453AB4A690A433B3.27A18B7A36D39EF074EDE21FC214BEAB1EFFB920&fvip=1&c=WEB&id=o-ALnGIx8vNjX4FkYo31oyvhVxIQFvCgsPAvPAdYZS_ORe&mm=31%2C29&mn=sn-vgqsknek%2Csn-vgqsrn7l&ei=9zfVW-HLNZT0NoafqKAO&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&mt=1540700029&mv=m&initcwndbps=1545000&ms=au%2Crdu&itag=18'
[download] /home/eakin/Videos/Sentdex/How_to_Build_a_Computer_and_Overclock_It/How to build a computer Tutorial Part 3.mp4 has already been downloaded
[download] 100% of 30.67MiB
[download] Downloading video 4 of 14
[youtube] J9wRTXxmaQo: Downloading webpage
[youtube] J9wRTXxmaQo: Downloading video info webpage
[youtube] J9wRTXxmaQo: Extracting video information
[debug] Invoking downloader on 'https://r1---sn-vgqsknel.googlevideo.com/videoplayback?sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&key=yt6&ip=69.81.74.92&ms=au%2Conr&beids=9466585&gir=yes&mt=1540700029&id=o-AA9jPQ0AcMRvpcxwmtqtBG_P-jrPODU_NOdzBxHcucon&mn=sn-vgqsknel%2Csn-p5qs7nek&mm=31%2C26&signature=5B8BAB2FFBB5D1DDDA8B09DF5EB7797454BC871D.76D8BB11F16E8BA654E5700CDDF36A4DB350951D&ratebypass=yes&ipbits=0&clen=33269909&initcwndbps=1545000&pl=22&itag=18&dur=399.847&mv=m&expire=1540721753&c=WEB&mime=video%2Fmp4&source=youtube&lmt=1374437747355718&fvip=1&ei=-TfVW-G1IszvigTF-7a4DQ&requiressl=yes'
[download] /home/eakin/Videos/Sentdex/How_to_Build_a_Computer_and_Overclock_It/How to build a computer Tutorial Part 4.mp4 has already been downloaded
[download] 100% of 31.73MiB
[download] Downloading video 5 of 14
[youtube] Kugq5bRGAjo: Downloading webpage
[youtube] Kugq5bRGAjo: Downloading video info webpage
[youtube] Kugq5bRGAjo: Extracting video information
[debug] Invoking downloader on 'https://r3---sn-vgqsknek.googlevideo.com/videoplayback?clen=27074246&id=o-ABulzRZPwZTEX44RaHbs8q6R2nCX7HEa3cKkaVvGg6E2&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&ei=-zfVW9KxBcOpD8D_mvAB&ip=69.81.74.92&mv=m&mt=1540700029&ms=au%2Crdu&signature=0118F83868AB4548D59B4B794F40AB10E53770C3.18F34C5726B78487DE279173B75F07AA8DC3B6A4&c=WEB&mn=sn-vgqsknek%2Csn-vgqs7nlk&mm=31%2C29&expire=1540721755&key=yt6&mime=video%2Fmp4&fvip=3&itag=18&ipbits=0&lmt=1374439006439742&ratebypass=yes&source=youtube&dur=323.198&pl=22&initcwndbps=1545000&beids=9466585&gir=yes&requiressl=yes'
[download] /home/eakin/Videos/Sentdex/How_to_Build_a_Computer_and_Overclock_It/How to build a computer Tutorial Part 5.mp4 has already been downloaded
[download] 100% of 25.82MiB
[download] Downloading video 6 of 14
[youtube] ONvua0YzlEc: Downloading webpage
[youtube] ONvua0YzlEc: Downloading video info webpage
[youtube] ONvua0YzlEc: Extracting video information
[debug] Invoking downloader on 'https://r1---sn-vgqs7ney.googlevideo.com/videoplayback?signature=08633663ED592D05EF808F9ED1D07572D96AE369.15ACC8FF2C4139DCD4DD24E7714A67B0EE308269&key=yt6&gir=yes&requiressl=yes&dur=530.506&source=youtube&lmt=1374441167487748&fvip=3&ratebypass=yes&expire=1540721757&itag=18&mn=sn-vgqs7ney%2Csn-p5qlsndz&mm=31%2C26&id=o-AA2YkBEiSpS_aTvgiv6_vEu9xBBA_KOq4cH_iMCk6mAQ&c=WEB&clen=44972160&ip=69.81.74.92&pl=22&mv=m&mt=1540700029&ms=au%2Conr&ei=_DfVW9jXJ5OiDc6firAF&beids=9466585&ipbits=0&initcwndbps=1561250&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&mime=video%2Fmp4'
[download] /home/eakin/Videos/Sentdex/How_to_Build_a_Computer_and_Overclock_It/How to build a computer Tutorial Part 6.mp4 has already been downloaded
[download] 100% of 42.89MiB
[download] Downloading video 7 of 14
[youtube] F44xxqlGzeU: Downloading webpage
[youtube] F44xxqlGzeU: Downloading video info webpage
[youtube] F44xxqlGzeU: Extracting video information
[debug] Invoking downloader on 'https://r6---sn-vgqsrnee.googlevideo.com/videoplayback?ei=_jfVW_DPJ9DDwQH68ZjIBA&id=o-AIa1oMWMwGGWqkKNEOLoBqiE3zBs8nCpIXkkpeqBcr-Y&initcwndbps=1561250&fvip=5&lmt=1460723582529522&beids=9466585&ip=69.81.74.92&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&ms=au%2Crdu&ipbits=0&mv=m&mt=1540700029&source=youtube&requiressl=yes&clen=35909103&key=yt6&mn=sn-vgqsrnee%2Csn-vgqsknlz&mm=31%2C29&itag=18&mime=video%2Fmp4&c=WEB&signature=B9E3E7A116AF4110BB0A79492CBC2B318A3285D6.E38DFFD58144613146B69E7F5C6486BB2EEA505B&gir=yes&expire=1540721758&dur=465.792&pl=22&ratebypass=yes'
[download] /home/eakin/Videos/Sentdex/How_to_Build_a_Computer_and_Overclock_It/How to build a computer Tutorial Part 7.mp4 has already been downloaded
[download] 100% of 34.25MiB
[download] Downloading video 8 of 14
[youtube] 3PfFqW1vGRM: Downloading webpage
[youtube] 3PfFqW1vGRM: Downloading video info webpage
[youtube] 3PfFqW1vGRM: Extracting video information
[debug] Invoking downloader on 'https://r2---sn-vgqsrnll.googlevideo.com/videoplayback?ei=ADjVW_WnEIWNigT37YrwBw&c=WEB&key=yt6&ipbits=0&mm=31%2C26&mn=sn-vgqsrnll%2Csn-p5qlsndk&pl=22&mt=1540700029&mv=m&dur=530.877&initcwndbps=1561250&itag=18&ms=au%2Conr&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&id=o-ADEJnM31z69tCClM9dt8u0ire1zYbShxvs6m8DgrLRcW&fvip=2&requiressl=yes&gir=yes&mime=video%2Fmp4&ratebypass=yes&lmt=1374445198318214&expire=1540721760&beids=9466585&signature=133D6565D40F8987171D348532E4EEE60E79B5F1.2CAECAD7B7774FA0655F1BBAD51BA75FB5CB4687&source=youtube&ip=69.81.74.92&clen=41193091'
[download] /home/eakin/Videos/Sentdex/How_to_Build_a_Computer_and_Overclock_It/How to build a computer Tutorial Part 8.mp4 has already been downloaded
[download] 100% of 39.28MiB
[download] Downloading video 9 of 14
[youtube] Z2IlEB4Q4OE: Downloading webpage
[youtube] Z2IlEB4Q4OE: Downloading video info webpage
[youtube] Z2IlEB4Q4OE: Extracting video information
[debug] Invoking downloader on 'https://r4---sn-vgqsrn7s.googlevideo.com/videoplayback?sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&clen=23015662&ipbits=0&beids=9466585&mime=video%2Fmp4&initcwndbps=1545000&ip=69.81.74.92&pl=22&mt=1540700029&mv=m&ei=ATjVW_26N4qbwQGx9LqYDw&ms=au%2Conr&mm=31%2C26&mn=sn-vgqsrn7s%2Csn-p5qlsndr&id=o-ACAX60y00-19WeSxGRpRVd5V9mod5sjYvL48vv0K4Dru&expire=1540721762&itag=18&ratebypass=yes&fvip=4&requiressl=yes&source=youtube&dur=317.277&lmt=1374446378342826&c=WEB&gir=yes&key=yt6&signature=D06EB79BA1C2310EE7B9ABA0BEF318D233136F74.08C2C0A8B67BCAF225FFBCE6F483B70479DFD4A4'
[download] /home/eakin/Videos/Sentdex/How_to_Build_a_Computer_and_Overclock_It/How to build a computer Tutorial Part 9.mp4 has already been downloaded
[download] 100% of 21.95MiB
[download] Downloading video 10 of 14
[youtube] JDVc7UD5PTo: Downloading webpage
[youtube] JDVc7UD5PTo: Downloading video info webpage
[youtube] JDVc7UD5PTo: Extracting video information
[debug] Invoking downloader on 'https://r1---sn-vgqsknls.googlevideo.com/videoplayback?ms=au%2Crdu&ei=AzjVW_zaGsLpwQGew6roAg&itag=18&pl=22&mt=1540700029&mv=m&clen=27149223&expire=1540721763&mm=31%2C29&requiressl=yes&mn=sn-vgqsknls%2Csn-vgqsrnes&mime=video%2Fmp4&beids=9466585&signature=8D173D501D620649D1A02D9C406E0B221ACEC4A1.36A5DCD5EBA985FA169424F1F39FC8629BEE93F1&source=youtube&dur=364.831&key=yt6&lmt=1374447851576704&ipbits=0&initcwndbps=1577500&ratebypass=yes&id=o-AFibpbOxUkSRl90nL-Rit9a1iBONBsbcFbZgBkto468E&fvip=1&c=WEB&gir=yes&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&ip=69.81.74.92'
[download] /home/eakin/Videos/Sentdex/How_to_Build_a_Computer_and_Overclock_It/How to build a computer Tutorial Part 10.mp4 has already been downloaded
[download] 100% of 25.89MiB
[download] Downloading video 11 of 14
[youtube] PU8hLRBGm30: Downloading webpage
[youtube] PU8hLRBGm30: Downloading video info webpage
[youtube] PU8hLRBGm30: Extracting video information
[debug] Invoking downloader on 'https://r1---sn-vgqsknll.googlevideo.com/videoplayback?ip=69.81.74.92&ms=au%2Conr&mt=1540700029&mv=m&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&id=o-ABhnjQOx3DSKBO9YF-5nPIzlqVrjpToy7xaxeiiVICNg&mm=31%2C26&mn=sn-vgqsknll%2Csn-p5qs7ned&clen=36481785&c=WEB&initcwndbps=1561250&requiressl=yes&beids=9466585&gir=yes&mime=video%2Fmp4&key=yt6&signature=2E02BB92824CB6EAF365F1C224DBAF454635485E.154B630E2B3CF65F547CDEBCB898D0186E63CAA9&ratebypass=yes&lmt=1374449872332642&ipbits=0&dur=512.255&expire=1540721765&source=youtube&pl=22&fvip=1&ei=BDjVW7aOOIG0wQGItJsQ&itag=18'
[download] /home/eakin/Videos/Sentdex/How_to_Build_a_Computer_and_Overclock_It/How to build a computer Tutorial Part 11.mp4 has already been downloaded
[download] 100% of 34.79MiB
[download] Downloading video 12 of 14
[youtube] Nps-yf86ayc: Downloading webpage
[youtube] Nps-yf86ayc: Downloading video info webpage
[youtube] Nps-yf86ayc: Extracting video information
[youtube] {22} signature length 42.40, html5 player vflXM3IU_
[youtube] Nps-yf86ayc: Downloading player https://www.youtube.com/yts/jsbin/player-vflXM3IU_/en_US/base.js
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1191, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1102, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1163, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 796, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract \x1b[0;34mInitial JS player signature function name\x1b[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1191, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1102, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1163, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 796, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1191, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1102, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1163, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 796, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/YoutubeDL.py", line 785, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1899, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1201, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1191, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1102, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1163, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 796, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract \x1b[0;34mInitial JS player signature function name\x1b[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Trying to download the playlist of Sentdex's "How to Build a Computer and Overclock It"
found at
https://www.youtube.com/playlist?list=PLQVvvaa0QuDcb8DSkkmhkOjrBssY45sYo

Got to video 12 of 14, and started spewing all this stuff about RegexNotFoundError, and to please report this issue on https://yt-dl.org/bug.

As far as checking whether I've got the latest version, I did:

$ sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
$ sudo chmod a+rx /usr/local/bin/youtube-dl

Then:
$ sudo youtube-dl --update
youtube-dl is up-to-date (2018.10.05)

but, when I did:
$ youtube-dl --version
2018.03.14

$ youtube-dl --update
Usage: youtube-dl [OPTIONS] URL [URL...]
youtube-dl: error: youtube-dl's self-update mechanism is disabled on Debian.
Please update youtube-dl using apt(8).
See https://packages.debian.org/sid/youtube-dl for the latest packaged version.

So, I'm not even sure if I've got the latest version.  
$ sudo apt-cache show youtube-dl
Package: youtube-dl
Architecture: all
Version: 2018.03.14-1
....

thus, the conundrum

**Comment by Hrxn** [comment]
> $ sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
$ sudo chmod a+rx /usr/local/bin/youtube-dl

Yeah..it's using the wrong version. If you get youtube-dl like that (or via pip), remove the apt package.
