### ISSUE TITLE
mixcloud url is incorrect

### ISSUE THREAD

**Issue by qyscott** [rg3/youtube-dl#18016]
[root@zookeeper1 youtube-dl]# ./youtube-dl -g -v https://www.mixcloud.com/johndigweed/transitions-with-john-digweed-and-jimmy-van-m-extended-edition/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-g', u'-v', u'https://www.mixcloud.com/johndigweed/transitions-with-john-digweed-and-jimmy-van-m-extended-edition/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.10.05
[debug] Python version 2.7.5 (CPython) - Linux-3.10.0-693.2.2.el7.x86_64-x86_64-with-centos-7.4.1708-Core
[debug] exe versions: none
[debug] Proxy map: {}
encrypted_play_info:None
{u'dashUrl': u'ITItPyZtbmE1ISwsLmF6JDosMDggMiF6My4kazcqLTomIWAzLz8nc2sjfX5ieGY8bCp3MyFkdW8qNHp1eTZkZSdzN2dkMGRqYyp0fGFiciomaiJ6LnspLjknKioyMGg/Pyk=', u'url': u'ITItPyZtbmEnIDogID9gZz49KzcjKDAwfiImKWs8KywhNip4LWMidSVpZHtiKGZpbHlgMWsvfj8qeGR3KzV5fHIjYnkrYTFgeSx3fGM1cnBxdnwtLXopezZxPyYmeTE+KQgXBBcyJwkZESUeHyEaIis7PAU=', u'hlsUrl': u'ITItPyZtbmE1ISwsLmN6JDosMDggMiF6My4kazcqLTomIWA/Ij9gJGt3fXpiKWY+eyoqeHd/IzhiYWAjfnk2eiByfzd5amM2Z3Zyd2czI2cpcC5hJjogKi9gIXw0fA==', u'uuid': u'5957186A-65D9-4980-8B46-09EC7B6C8AB9'}
WARNING: Failed to download m3u8 information: HTTP Error 400: Bad Request
WARNING: Failed to download MPD manifest: HTTP Error 404: Not Found
[debug] Default format spec: bestvideo+bestaudio/best
https://stream4.mixcloud.com"zrctak6y7j0d;021|5=#>%e;n7{c>=8~b82&w*<j3e)*x$(,r7$!75id<p4c&~hr-y{hZCMDft]VV`JO`Sfb}eJ

**Comment by Hackerpcs** [comment]
I get a different error but I can't download too

```
youtube-dl.exe --verbose https://www.mixcloud.com/johndigweed/transitions-with-john-digweed-and-jimmy-van-m-extended-edition/
[debug] System config: []
[debug] User config: ['--embed-thumbnail', '--add-metadata', '--fixup', 'warn', '--convert-subs', 'srt', '--all-subs', '--embed-subs', '--write-info-json', '--merge-output-format', 'mkv']
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.mixcloud.com/johndigweed/transitions-with-john-digweed-and-jimmy-van-m-extended-edition/']
[debug] Encodings: locale cp1253, fs mbcs, out cp737, pref cp1253
[debug] youtube-dl version 2018.10.29
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-92292-ge95987f6ca, ffprobe N-92292-ge95987f6ca, phantomjs 2.1.1
[debug] Proxy map: {}
[mixcloud] johndigweed-transitions-with-john-digweed-and-jimmy-van-m-extended-edition: Downloading webpage
ERROR: Unable to extract play info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U
  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpadzwnijc\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpadzwnijc\build\youtube_dl\extractor\common.py", line 508, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpadzwnijc\build\youtube_dl\extractor\mixcloud.py", line 87, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpadzwnijc\build\youtube_dl\extractor\common.py", line 987, in _html_search_regex
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpadzwnijc\build\youtube_dl\extractor\common.py", line 978, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract play info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by hexbraker** [comment]
same here mixcloud not working anymore

**Comment by Hackerpcs** [comment]
Problem now seems to be fixed on its own, maybe it was a problem on Mixcloud's end

**Comment by tinydynamite00** [comment]
I am not certain the problem is fixed; still encountering <code>unable to extract play info</code> error when attempting download from Mixcloud - youtube-dl version 2018.10.29 Error log follows:

ydl --verbose 'https://www.mixcloud.com/nicolemoudaber/in-the-mood-episode-235-fur-coat-takeover/'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--no-resize-buffer', '--extract-audio', '--prefer-ffmpeg', '--audio-format', 'mp3', '--audio-quality', '1', '--add-metadata', '--embed-thumbnail', '--verbose', 'https://www.mixcloud.com/nicolemoudaber/in-the-mood-episode-235-fur-coat-takeover/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.10.29
[debug] Python version 3.7.1 (CPython) - Linux-4.4.147-lineage-gbbb2b75-aarch64-with-libc
[debug] exe versions: ffmpeg 4.0.2, ffprobe 4.0.2
[debug] Proxy map: {}
[mixcloud] nicolemoudaber-in-the-mood-episode-235-fur-coat-takeover: Downloading webpage
ERROR: Unable to extract play info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/youtube_dl/extractor/mixcloud.py", line 87, in _real_extract
    webpage, 'play info'), 'play info')
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 987, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 978, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract play info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by e-d-n-a** [comment]
Same problem here (invalid URL) with the following command tested just now:

**youtube-dl -v https://www.mixcloud.com/DjBeenie/dj-beenie-garage-kiss-2-autumn-2011/**

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.mixcloud.com/DjBeenie/dj-beenie-garage-kiss-2-autumn-2011/']
[debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8
[debug] youtube-dl version 2018.10.29
[debug] Python version 2.7.3 (CPython) - Linux-3.12.24+-armv6l-with-debian-7.5
[debug] exe versions: avconv 9.14-6, avprobe 9.14-6, rtmpdump 2.4
[debug] Proxy map: {}
[mixcloud] DjBeenie-dj-beenie-garage-kiss-2-autumn-2011: Downloading webpage
[mixcloud] DjBeenie-dj-beenie-garage-kiss-2-autumn-2011: Downloading JS
[mixcloud] DjBeenie-dj-beenie-garage-kiss-2-autumn-2011: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 404: Not Found
[mixcloud] DjBeenie-dj-beenie-garage-kiss-2-autumn-2011: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 404: Not Found
WARNING: Your copy of avconv is outdated and unable to properly mux separate video and audio files, youtube-dl will download single file media. Update avconv to version 10-0 or newer to fix this.
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on u'https://stream4.mixcloud.com"zrctak6y7j0d;021}5m#2%`;9=)6>m8/f82p&~<08a#**&!,r=-r2e<3<p4c&~hr-ODz)\x7fxa%py,Rj*KIj%0QjJ'
ERROR: unable to download video data: <urlopen error [Errno -2] Name or service not known>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1908, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1847, in dl
    return fd.download(name, info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/common.py", line 364, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/http.py", line 341, in real_download
    establish_connection()
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 2211, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 401, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 419, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 379, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/utils.py", line 1139, in https_open
    req, **kwargs)
  File "/usr/lib/python2.7/urllib2.py", line 1181, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno -2] Name or service not known>
```

Also tested with another installation on Win7:

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.mixcloud.com/DjBeenie/dj-beenie-garage-kiss-2-autumn-2011/']
[debug] Encodings: locale cp1252, fs utf-8, out cp1252, pref cp1252
[debug] youtube-dl version 2018.10.29
[debug] Python version 3.7.0 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[mixcloud] DjBeenie-dj-beenie-garage-kiss-2-autumn-2011: Downloading webpage
[mixcloud] DjBeenie-dj-beenie-garage-kiss-2-autumn-2011: Downloading JS
[mixcloud] DjBeenie-dj-beenie-garage-kiss-2-autumn-2011: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 404: Not Found
[mixcloud] DjBeenie-dj-beenie-garage-kiss-2-autumn-2011: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 404: Not Found
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://stream5.mixcloud.com"zrctak6y7j0d;021}5m#2%`;9=)6>m8/f82p&~<08a#**&!,r=-r2e<3<p4c&~hr-ODz)\x7fxa%py,Rj*KIj%0QjJ'
ERROR: unable to download video data: <urlopen error [Errno 11004] getaddrinfo failed>
Traceback (most recent call last):
  File "c:\program files (x86)\python37-32\lib\urllib\request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "c:\program files (x86)\python37-32\lib\http\client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "c:\program files (x86)\python37-32\lib\http\client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "c:\program files (x86)\python37-32\lib\http\client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "c:\program files (x86)\python37-32\lib\http\client.py", line 1016, in _send_output
    self.send(msg)
  File "c:\program files (x86)\python37-32\lib\http\client.py", line 956, in send
    self.connect()
  File "c:\program files (x86)\python37-32\lib\http\client.py", line 1384, in connect
    super().connect()
  File "c:\program files (x86)\python37-32\lib\http\client.py", line 928, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "c:\program files (x86)\python37-32\lib\socket.py", line 707, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "c:\program files (x86)\python37-32\lib\socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11004] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files (x86)\python37-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 1908, in process_info
    success = dl(filename, info_dict)
  File "c:\program files (x86)\python37-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 1847, in dl
    return fd.download(name, info)
  File "c:\program files (x86)\python37-32\lib\site-packages\youtube_dl\downloader\common.py", line 364, in download
    return self.real_download(filename, info_dict)
  File "c:\program files (x86)\python37-32\lib\site-packages\youtube_dl\downloader\http.py", line 341, in real_download
    establish_connection()
  File "c:\program files (x86)\python37-32\lib\site-packages\youtube_dl\downloader\http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "c:\program files (x86)\python37-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 2211, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "c:\program files (x86)\python37-32\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "c:\program files (x86)\python37-32\lib\urllib\request.py", line 543, in _open
    '_open', req)
  File "c:\program files (x86)\python37-32\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "c:\program files (x86)\python37-32\lib\site-packages\youtube_dl\utils.py", line 1139, in https_open
    req, **kwargs)
  File "c:\program files (x86)\python37-32\lib\urllib\request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 11004] getaddrinfo failed>
```

**Comment by Hackerpcs** [comment]
Problem is back on with errors as @e-d-n-a wrote

**Comment by DeonNel1** [comment]
i'm also getting this error with mixcloud uploads...

**Comment by benoon** [comment]
Here the same, error.

**Comment by floge77** [comment]
Same here. Is it possible to provide some help without knowledge about security related stuff?

As far as I can see what we need is the signature for a download url. As a reference I used http://www.mixcloud-downloader.com/ which is still able to download tracks from mixcloud.

Example:
https://www.mixcloud.com/Q-dance/q-dance-presents-hardstyle-top-40-l-october-2018/

After clicking play on the URL (at mixcloud.com) I can see in the chrome developer tools under network (check at media) following URL: https://audiocdn6.mixcloud.com/previews/6/7/d/5/9ceb-6bcf-4277-a802-4e3254677cc8.mp3

Download URL generated by mixcloud-downloader.com:
http://stream8.mixcloud.com/secure/c/m4a/64/6/7/d/5/9ceb-6bcf-4277-a802-4e3254677cc8.m4a?sig=k0rJaou07CtJCbLw-pT59g

So it seems like we can extract the trackID out of the URL we receive when clicking play-button. Here the track id is: 
https://audiocdn6.mixcloud.com/previews/ **6/7/d/5/9ceb-6bcf-4277-a802-4e3254677cc8** .mp3


The download URL can somehow be created with this pattern:  http://stream + an Integer + .mixcloud.com/secure/c/m4a/64 + trackID + signature

For me the big question is _how to get the signature?_

**Comment by benoon** [comment]
Did you find out how to make mixcloud working again ?
