### ISSUE TITLE
Unable to download cnbc videos. 

### ISSUE THREAD

**Issue by shirishag75** [rg3/youtube-dl#18010]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.10.29*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.10.29**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

```
$ ./youtube-dl --version
2018.10.29

$ ./youtube-dl --verbose "https://www.cnbc.com/video/2018/10/29/watch-the-full-interview-with-ibm-and-red-hat-ceos-on-33-billion-deal.html"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.cnbc.com/video/2018/10/29/watch-the-full-interview-with-ibm-and-red-hat-ceos-on-33-billion-deal.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.10.29
[debug] Python version 2.7.15+ (CPython) - Linux-4.18.0-2-amd64-x86_64-with-debian-buster-sid
[debug] exe versions: ffmpeg 4.0.2-2, ffprobe 4.0.2-2, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] watch-the-full-interview-with-ibm-and-red-hat-ceos-on-33-billion-deal: Requesting header
WARNING: Falling back on generic information extractor.
[generic] watch-the-full-interview-with-ibm-and-red-hat-ceos-on-33-billion-deal: Downloading webpage
[generic] watch-the-full-interview-with-ibm-and-red-hat-ceos-on-33-billion-deal: Extracting information
ERROR: Unsupported URL: https://www.cnbc.com/video/2018/10/29/watch-the-full-interview-with-ibm-and-red-hat-ceos-on-33-billion-deal.html
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/extractor/generic.py", line 2324, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "./youtube-dl/youtube_dl/compat.py", line 2542, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "./youtube-dl/youtube_dl/compat.py", line 2531, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 3, column 48
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/generic.py", line 3298, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.cnbc.com/video/2018/10/29/watch-the-full-interview-with-ibm-and-red-hat-ceos-on-33-billion-deal.html
```

**Comment by shirishag75** [comment]
you should have at least shared the original query if made by someone so I could look at that.
