### ISSUE TITLE
Steam's new age check breaks youtube-dl

### ISSUE THREAD

**Issue by RunningDroid** [rg3/youtube-dl#18022]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.10.29*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.10.29**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: [u'--rate-limit', u'1M', u'--console-title', u'--write-sub', u'--sub-lang', u'en', u'--add-metadata']
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://store.steampowered.com/app/268990/The_Dishwasher_Vampire_Smile']
[debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8
[debug] youtube-dl version 2018.10.29
[debug] Python version 2.7.15 (CPython) - Linux-4.18.16_2-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.0.2, ffprobe 4.0.2
[debug] Proxy map: {}
[22;0t[Steam] 268990: Downloading webpage
ERROR: Unable to extract flash vars; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/steam.py", line 90, in _real_extract
    'flash vars'), playlist_id, js_to_json)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 978, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract flash vars; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

[23;0t
<end of log>
```
---

### Description of your *issue*, suggested solution and other information

Steam pages that redirect to the age check cause youtube-dl to throw a 'Unable to extract flash vars' error; pages that do not redirect to the age check still work.
- Working page: https://store.steampowered.com/app/274520/Darkwood
- Broken page, basic age check: https://store.steampowered.com/app/268990/The_Dishwasher_Vampire_Smile
- Broken page, sign-in age check: https://store.steampowered.com/app/723090/Meltys_Quest

**Comment by Steffo99** [comment]
I just tried https://store.steampowered.com/app/268990/The_Dishwasher_Vampire_Smile and it works without any problem, while https://store.steampowered.com/app/723090/Meltys_Quest still does not work.

**Comment by RunningDroid** [comment]
@Steffo99 I just tried both of them with 2019.04.24 and they're both still broken for me, is it possible Steam is looking up your IP and choosing to not give you an age check because of the country you are in? (I'm in the US, if it helps.)
