### ISSUE TITLE
Site support request dimsum.my

### ISSUE THREAD

**Issue by Anvithlobo** [rg3/youtube-dl#18031]
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2018.10.29**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [X] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

```

ytdl\youtube-dl.exe' https://www.dimsum.my/drama/thailand/series-809?lang=en#! -v                 [debug] System config: []                                                                                                                                 [debug] User config: []                                                                                                                                   [debug] Custom config: []                                                                                                                                 [debug] Command-line args: ['https://www.dimsum.my/drama/thailand/series-809?lang=en#!', '-v']                                                            [debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252                                                                                         [debug] youtube-dl version 2018.10.29                                                                                                                     [debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134                                                                                            [debug] exe versions: ffmpeg N-91500-g3870ed7ab3                                                                                                          [debug] Proxy map: {}                                                                                                                                     [generic] series-809?lang=en#!: Requesting header                                                                                                         WARNING: Falling back on generic information extractor.                                                                                                   [generic] series-809?lang=en#!: Downloading webpage                                                                                                       [generic] series-809?lang=en#!: Extracting information                                                                                                    ERROR: Unsupported URL: https://www.dimsum.my/drama/thailand/series-809?lang=en#!                                                                         Traceback (most recent call last):                                                                                                                          File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpadzwnijc\build\youtube_dl\YoutubeDL.py", line 792, in extract_info                     File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpadzwnijc\build\youtube_dl\extractor\common.py", line 508, in extract                   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpadzwnijc\build\youtube_dl\extractor\generic.py", line 3298, in _real_extract         youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.dimsum.my/drama/thailand/series-809?lang=en#!
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: cant get the link of single video 
- Playlist: https://www.dimsum.my/drama/thailand/series-743?lang=en

site support request for www.dimsum.my a account is needed for it but theres a free 30 day trail for those who want to try

**Comment by marlenexxx** [comment]
also you need malaysian connection to open that website
