### ISSUE TITLE
Can't download WavePad tutorial on youtube.com

### ISSUE THREAD

**Issue by johnthecracker** [rg3/youtube-dl#18073]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.11.03*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2018.11.03**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

```
C:\>youtube-dl.exe -v --hls-prefer-native --no-check-certificate --no-overwrites "https://www.youtube.com/watch?v=mlb5diXf1Y8"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--hls-prefer-native', '--no-check-certificate', '--no-overwrites', 'https://www.youtube.com/watch?v=mlb5diXf1Y8']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.11.03
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg N-92087-gdcbd89e000-ffmpeg-windows-build-helpers, ffprobe N-92087-gdcbd89e000-ffmpeg-windows-build-helpers, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] mlb5diXf1Y8: Downloading webpage
[youtube] mlb5diXf1Y8: Downloading video info webpage
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://r3---sn-cu-auoz.googlevideo.com/videoplayback?gir=yes&sparams=aitags%2Cclen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&requiressl=yes&key=yt6&clen=18383360&aitags=133%2C134%2C135%2C160&keepalive=yes&itag=135&mn=sn-cu-auoz%2Csn-5hnekn7d&ipbits=0&mm=31%2C26&signature=4C0A32983C7C93B6F19849CF2C3AD658595B0E59.1064A0A9425A490E371ACBC7E8F9446BD203165C&ms=au%2Conr&mime=video%2Fmp4&mv=m&ip=86.182.54.230&source=youtube&pl=25&id=o-APmmbdnXnPnC5pr5OcY2jA9bCao9hWpU8gQ6xS0QJ4kO&initcwndbps=1733750&fvip=3&dur=491.066&ei=HPveW-HVAvP17gTxkpiADg&mt=1541339788&c=WEB&lmt=1431838679740620&expire=1541361532&ratebypass=yes'
ERROR: unable to download video data: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
Traceback (most recent call last):
  File "C:\Python\Python34\lib\urllib\request.py", line 1183, in do_open
  File "C:\Python\Python34\lib\http\client.py", line 1137, in request
  File "C:\Python\Python34\lib\http\client.py", line 1182, in _send_request
  File "C:\Python\Python34\lib\http\client.py", line 1133, in endheaders
  File "C:\Python\Python34\lib\http\client.py", line 963, in _send_output
  File "C:\Python\Python34\lib\http\client.py", line 898, in send
  File "C:\Python\Python34\lib\http\client.py", line 1279, in connect
  File "C:\Python\Python34\lib\http\client.py", line 871, in connect
  File "C:\Python\Python34\lib\socket.py", line 516, in create_connection
  File "C:\Python\Python34\lib\socket.py", line 507, in create_connection
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpxh4iffn2\build\youtube_dl\YoutubeDL.py", line 1902, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpxh4iffn2\build\youtube_dl\YoutubeDL.py", line 1847, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpxh4iffn2\build\youtube_dl\downloader\common.py", line 364, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpxh4iffn2\build\youtube_dl\downloader\http.py", line 341, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpxh4iffn2\build\youtube_dl\downloader\http.py", line 109, in establish_connection
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpxh4iffn2\build\youtube_dl\YoutubeDL.py", line 2211, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpxh4iffn2\build\youtube_dl\utils.py", line 1139, in https_open
  File "C:\Python\Python34\lib\urllib\request.py", line 1185, in do_open
urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>

```

---

### Description of your *issue*, suggested solution and other information

Can't download video from this youtube url:

https://www.youtube.com/watch?v=mlb5diXf1Y8

```
C:\>youtube-dl.exe -v -F --hls-prefer-native --no-check-certificate "https://www.youtube.com/watch?v=mlb5diXf1Y8"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', '--hls-prefer-native', '--no-check-certificate', 'https://www.youtube.com/watch?v=mlb5diXf1Y8']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.11.03
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg N-92087-gdcbd89e000-ffmpeg-windows-build-helpers, ffprobe N-92087-gdcbd89e000-ffmpeg-windows-build-helpers, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] mlb5diXf1Y8: Downloading webpage
[youtube] mlb5diXf1Y8: Downloading video info webpage
[info] Available formats for mlb5diXf1Y8:
format code  extension  resolution note
171          webm       audio only DASH audio   73k , 1fps, vorbis@128k, 4.07MiB
140          m4a        audio only DASH audio   96k , m4a_dash container, mp4a.40.2@128k, 5.57MiB
160          mp4        256x144    144p  136k , avc1.4d400c, 15fps, video only, 5.99MiB
133          mp4        426x240    240p  304k , avc1.4d4015, 30fps, video only, 13.28MiB
134          mp4        640x360    360p  584k , avc1.4d401e, 30fps, video only, 8.02MiB
135          mp4        854x480    480p 1107k , avc1.4d401f, 30fps, video only, 17.53MiB
17           3gp        176x144    small , mp4v.20.3, mp4a.40.2@ 24k, 3.74MiB
36           3gp        320x180    small , mp4v.20.3, mp4a.40.2, 12.92MiB
43           webm       640x360    medium , vp8.0, vorbis@128k, 17.30MiB
18           mp4        640x360    medium , avc1.42001E, mp4a.40.2@ 96k, 19.64MiB (best)
```

**Comment by dstftw** [comment]
Most likely network issue on your side.

**Comment by johnthecracker** [comment]
Thank you for the reply.
It works for me now as well, I didn't make any change on my sistem, don't know what could had caused the error.

```

C:\>youtube-dl.exe -v --hls-prefer-native --no-check-certificate --no-overwrites "https://www.youtube.com/watch?v=mlb5diXf1Y8"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--hls-prefer-native', '--no-check-certificate', '--no-overwrites', 'https://www.youtube.com/watch?v=mlb5diXf1Y8']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.11.03
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg N-92087-gdcbd89e000-ffmpeg-windows-build-helpers, ffprobe N-92087-gdcbd89e000-ffmpeg-windows-build-helpers, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] mlb5diXf1Y8: Downloading webpage
[youtube] mlb5diXf1Y8: Downloading video info webpage
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://r3---sn-cu-auoz.googlevideo.com/videoplayback?ei=s5DfW7aFIJyG7AT1yII4&c=WEB&key=yt6&ipbits=0&mm=31%2C26&mn=sn-cu-auoz%2Csn-5hne6nsk&pl=25&mt=1541378102&mv=m&dur=491.066&initcwndbps=1587500&itag=135&ms=au%2Conr&sparams=aitags%2Cclen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&id=o-AG0V6d01Eq6O6llarqNyQl9ksfkgYFllIi2nYhJk-kYC&fvip=3&keepalive=yes&requiressl=yes&gir=yes&mime=video%2Fmp4&lmt=1431838679740620&expire=1541399827&signature=A24D98AA8593C7F13B2B996A627C2DEDD1961F13.300F929BB6E0238557CE5536262C739DEA8E8A59&source=youtube&ip=86.182.54.230&aitags=133%2C134%2C135%2C160&clen=18383360&ratebypass=yes'
[download] Destination: WavePad Audio Editing Software _ Intro to Editing-mlb5diXf1Y8.f135.mp4
[download] 100% of 17.53MiB in 00:08
[debug] Invoking downloader on 'https://r3---sn-cu-auoz.googlevideo.com/videoplayback?ei=s5DfW7aFIJyG7AT1yII4&c=WEB&key=yt6&ipbits=0&mm=31%2C26&mn=sn-cu-auoz%2Csn-5hne6nsk&pl=25&mt=1541378102&mv=m&dur=491.171&initcwndbps=1587500&itag=140&ms=au%2Conr&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&id=o-AG0V6d01Eq6O6llarqNyQl9ksfkgYFllIi2nYhJk-kYC&fvip=3&keepalive=yes&requiressl=yes&gir=yes&mime=audio%2Fmp4&lmt=1431838634082274&expire=1541399827&signature=36A28004F5DD709CE3EB91F7EAAF7FDFDA6EADD4.D0A639C444BE08BFAC56EDEAB6DDC5909388354D&source=youtube&ip=86.182.54.230&clen=5836825&ratebypass=yes'
[download] Destination: WavePad Audio Editing Software _ Intro to Editing-mlb5diXf1Y8.f140.m4a
[download] 100% of 5.57MiB in 00:02
[ffmpeg] Merging formats into "WavePad Audio Editing Software _ Intro to Editing-mlb5diXf1Y8.mp4"
[debug] ffmpeg command line: ffmpeg -y -i "file:WavePad Audio Editing Software _ Intro to Editing-mlb5diXf1Y8.f135.mp4" -i "file:WavePad Audio Editing Software _ Intro to Editing-mlb5diXf1Y8.f140.m4a" -c copy -map "0:v:0" -map "1:a:0" "file:WavePad Audio Editing Software _ Intro to Editing-mlb5diXf1Y8.temp.mp4"
Deleting original file WavePad Audio Editing Software _ Intro to Editing-mlb5diXf1Y8.f135.mp4 (pass -k to keep)
Deleting original file WavePad Audio Editing Software _ Intro to Editing-mlb5diXf1Y8.f140.m4a (pass -k to keep)
```
