### ISSUE TITLE
error occured youtube-dlg

### ISSUE THREAD

**Issue by fredvsfred** [rg3/youtube-dl#18088]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.11.03*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.11.03**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[11/06/18 21:05:02] [debug] System config: []
[11/06/18 21:05:02] [debug] User config: []
[11/06/18 21:05:02] [debug] Custom config: []
[11/06/18 21:05:02] [debug] Command-line args: ['--newline', '-i', '-o', 'E:\\Lieder\\%(title)s.%(ext)s', '-x', '--audio-format', 'mp3', '-v', '--ignore-config', '--hls-prefer-native', 'https://www.youtube.com/watch?v=w41lh1xV500']
[11/06/18 21:05:02] [debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[11/06/18 21:05:02] [debug] youtube-dl version 2018.07.29
[11/06/18 21:05:02] [debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[11/06/18 21:05:02] [debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2
[11/06/18 21:05:02] [debug] Proxy map: {}
[11/06/18 21:05:02] WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[11/06/18 21:05:02] ERROR: Signature extraction failed: Traceback (most recent call last):
[11/06/18 21:05:02]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4sw50z9e\build\youtube_dl\extractor\youtube.py", line 1210, in _decrypt_signature
[11/06/18 21:05:02]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4sw50z9e\build\youtube_dl\extractor\youtube.py", line 1121, in _extract_signature_function
[11/06/18 21:05:02]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4sw50z9e\build\youtube_dl\extractor\youtube.py", line 1182, in _parse_sig_js
[11/06/18 21:05:02]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4sw50z9e\build\youtube_dl\extractor\common.py", line 972, in _search_regex
[11/06/18 21:05:02] youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[11/06/18 21:05:02]  (caused by RegexNotFoundError('Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[11/06/18 21:05:02] Traceback (most recent call last):
[11/06/18 21:05:02]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4sw50z9e\build\youtube_dl\extractor\youtube.py", line 1210, in _decrypt_signature
[11/06/18 21:05:02]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4sw50z9e\build\youtube_dl\extractor\youtube.py", line 1121, in _extract_signature_function
[11/06/18 21:05:02]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4sw50z9e\build\youtube_dl\extractor\youtube.py", line 1182, in _parse_sig_js
[11/06/18 21:05:02]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4sw50z9e\build\youtube_dl\extractor\common.py", line 972, in _search_regex
[11/06/18 21:05:02] youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[11/06/18 21:05:02] Traceback (most recent call last):
[11/06/18 21:05:02]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4sw50z9e\build\youtube_dl\extractor\youtube.py", line 1210, in _decrypt_signature
[11/06/18 21:05:02]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4sw50z9e\build\youtube_dl\extractor\youtube.py", line 1121, in _extract_signature_function
[11/06/18 21:05:02]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4sw50z9e\build\youtube_dl\extractor\youtube.py", line 1182, in _parse_sig_js
[11/06/18 21:05:02]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4sw50z9e\build\youtube_dl\extractor\common.py", line 972, in _search_regex
[11/06/18 21:05:02] youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[11/06/18 21:05:02] 
[11/06/18 21:05:02] During handling of the above exception, another exception occurred:
[11/06/18 21:05:02] 
[11/06/18 21:05:02] Traceback (most recent call last):
[11/06/18 21:05:02]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4sw50z9e\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
[11/06/18 21:05:02]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4sw50z9e\build\youtube_dl\extractor\common.py", line 502, in extract
[11/06/18 21:05:02]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4sw50z9e\build\youtube_dl\extractor\youtube.py", line 1803, in _real_extract
[11/06/18 21:05:02]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4sw50z9e\build\youtube_dl\extractor\youtube.py", line 1220, in _decrypt_signature
[11/06/18 21:05:02] youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
[11/06/18 21:05:02]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4sw50z9e\build\youtube_dl\extractor\youtube.py", line 1210, in _decrypt_signature
[11/06/18 21:05:02]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4sw50z9e\build\youtube_dl\extractor\youtube.py", line 1121, in _extract_signature_function
[11/06/18 21:05:02]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4sw50z9e\build\youtube_dl\extractor\youtube.py", line 1182, in _parse_sig_js
[11/06/18 21:05:02]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp4sw50z9e\build\youtube_dl\extractor\common.py", line 972, in _search_regex
[11/06/18 21:05:02] youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[11/06/18 21:05:02]  (caused by RegexNotFoundError('Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[11/06/18 21:05:02] 

```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

**Comment by lonelyhearth** [comment]
`[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=zrV5of2p-oc']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.11.03
[debug] Python version 3.6.6 (CPython) - Linux-4.15.0-38-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.4-0ubuntu0.18.04.1, ffprobe 3.4.4-0ubuntu0.18.04.1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] zrV5of2p-oc: Downloading webpage
[youtube] zrV5of2p-oc: Downloading video info webpage
[youtube] {22} signature length 41.41, html5 player vfls4aurX
[youtube] zrV5of2p-oc: Downloading player https://www.youtube.com/yts/jsbin/player-vfls4aurX/en_US/base.js
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/home/ubmatias/.local/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1221, in _decrypt_signature
    video_id, player_url, s
  File "/home/ubmatias/.local/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1130, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/home/ubmatias/.local/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1193, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "/home/ubmatias/.local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 983, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract \x1b[0;34mInitial JS player signature function name\x1b[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/ubmatias/.local/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1221, in _decrypt_signature
    video_id, player_url, s
  File "/home/ubmatias/.local/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1130, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/home/ubmatias/.local/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1193, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "/home/ubmatias/.local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 983, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/ubmatias/.local/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1221, in _decrypt_signature
    video_id, player_url, s
  File "/home/ubmatias/.local/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1130, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/home/ubmatias/.local/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1193, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "/home/ubmatias/.local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 983, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubmatias/.local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/home/ubmatias/.local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/home/ubmatias/.local/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1814, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/home/ubmatias/.local/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1231, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/home/ubmatias/.local/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1221, in _decrypt_signature
    video_id, player_url, s
  File "/home/ubmatias/.local/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1130, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/home/ubmatias/.local/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1193, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "/home/ubmatias/.local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 983, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract \x1b[0;34mInitial JS player signature function name\x1b[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
`
Here is my oput.

**Comment by kaizerbacter** [comment]
same error here:
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1221, in _decrypt_signature
    video_id, player_url, s
  File "/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1130, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1193, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "/bin/youtube-dl/youtube_dl/extractor/common.py", line 983, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be su
re to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError(u'Unable to extract \x1b[0;34mInitial JS player signature function name\x1b[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  y
outube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type
  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
