### ISSUE TITLE
Support request for tvopen.gr

### ISSUE THREAD

**Issue by Hackerpcs** [rg3/youtube-dl#18084]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.11.03*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.11.03**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Site support request (request for adding support for a new site)

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

```
youtube-dl -v "https://www.tvopen.gr/seires/oy-foneyseis/season/01/episode/0003"
[debug] System config: []
[debug] User config: ['--embed-thumbnail', '--add-metadata', '--fixup', 'warn', '--convert-subs', 'srt', '--all-subs', '--embed-subs', '--write-info-json', '--merge-output-format', 'mkv']
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.tvopen.gr/seires/oy-foneyseis/season/01/episode/0003']
[debug] Encodings: locale cp1253, fs mbcs, out cp1253, pref cp1253
[debug] youtube-dl version 2018.11.03
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-92356-g89a0d33e3a, ffprobe N-92356-g89a0d33e3a, phantomjs 2.1.1
[debug] Proxy map: {}
[generic] 0003: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 0003: Downloading webpage
[generic] 0003: Extracting information
WARNING: [generic] 0003: Failed to parse JSON Invalid control character at: line 4 column 28 (char 86)
ERROR: Unsupported URL: https://www.tvopen.gr/seires/oy-foneyseis/season/01/episode/0003
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpxh4iffn2\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpxh4iffn2\build\youtube_dl\extractor\common.py", line 508, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpxh4iffn2\build\youtube_dl\extractor\generic.py", line 3298, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.tvopen.gr/seires/oy-foneyseis/season/01/episode/0003
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.tvopen.gr/seires/oy-foneyseis/season/01/episode/0001
- Single video: https://www.tvopen.gr/seires/oy-foneyseis/season/01/episode/0003
- Playlist: https://www.tvopen.gr/seires/oy-foneyseis/videos

---

Web TV site of new Greek TV station Open Beyond

**Comment by Vangelis66** [comment]
... You can always sniff the master HLS playlist URI for the episode, using your browser's dev tools (WebConsole), and feed that to yt-dl; you **must** also include the `Referer` Request Header, else you'll get a 403 from the media server; yes, it involves some manual labour, but gets the programme to disk (in 720p): 

`youtube-dl --console-title --hls-prefer-native -c --no-part --add-header "Referer:https://www.tvopen.gr/" "https://epsilonvod.akamaized.net/hls/p/2299551/sp/229955100/serveFlavor/entryId/1_e6r88w9o/v/1/ev/4/flavorId/1_vyj658qq/name/a.mp4/index.m3u8" -o "OpenBeyondTV_Oy-foneyseis_Se1Ep3.mp4"`
```
[generic] index: Requesting header
[generic] index: Downloading m3u8 information
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 261
[download] Destination: OpenBeyondTV_Oy-foneyseis_Se1Ep3.mp4
[download]  16.5% of ~468.65MiB at  1.17MiB/s ETA 04:19
```
PS: Tested from within Greece, unsure whether any geo-fence is implemented for non-Greek IPs...

**Comment by Hackerpcs** [comment]
Thanks (similar download speed to me heh), I know that and I made a little script to automate it (also deletes the nonsense metadata that are annoying on players)
https://pastebin.com/NmsjDZW1
but that's why youtube-dl is for, to automate things :)

**Comment by Hackerpcs** [comment]
@Vangelis66 
Hey, can you download videos from here? Even if adding referrer it says 403
