### ISSUE TITLE
Unable to extract info url it.dplay.com

### ISSUE THREAD

**Issue by tudo75** [rg3/youtube-dl#18085]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.11.03*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.11.03**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

youtube-dl.exe -v -f "best[height=720]" --cookies cookie.txt -r 550K https://it.dplay.com/nove/dio-perdona-io-no-film/dio-perdona-io-no-streaming-ita/

[debug] System config: []
[debug] User config: ['-v', '-o', '.\\%(title)s.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: ['-v', '-f', 'best[height=720]', '--cookies', 'cookie.txt', '-r', '550K', 'https://it.dplay.com/nove/dio-perdona-io-no-film/dio-perdona-io-no-streaming-ita/']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.11.03
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg 4.0.2, ffprobe 4.0.2
[debug] Proxy map: {}
[debug] Using fake IP 79.4.98.59 (IT) as X-Forwarded-For.
[DPlayIt] dio-perdona-io-no-streaming-ita: Downloading webpage
ERROR: Unable to extract info url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpxh4iffn2\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpxh4iffn2\build\youtube_dl\extractor\common.py", line 508, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpxh4iffn2\build\youtube_dl\extractor\dplay.py", line 316, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpxh4iffn2\build\youtube_dl\extractor\common.py", line 983, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract info url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

---

### Description of your *issue*, suggested solution and other information

In Firefox video play fine

Usually cookies are not needed but I tried and also with them don't work.

This work:
youtube-dl.exe -v -f "best[height=720]" -r 550K https://it.dplay.com/giallo/lispettore-barnaby/stagione-13-episodio-6-la-nobile-arte/

**Comment by tudo75** [comment]
wrong cookie file. sorry
