### ISSUE TITLE
Signature extraction failed on Music videos

### ISSUE THREAD

**Issue by Roshke** [rg3/youtube-dl#18091]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.11.03*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2018.11.03**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: [Ubuntu 18 latest Youtube-DL]
[debug] User config: []
[debug] Command-line args: [ -i --no-call-home --no-playlist -J -x https://www.youtube.com/watch?v=rpOZblmWQd4]
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2018.11.03
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Hi,

On YouTube links that contain licensed Music I started to get an error just a few hours ago.
It works normally on "normal" videos.

```
roshke@nl1:~/sinusbot_viper$ python /home/roshke/sinusbot2/youtube-dl -i --no-call-home --no-playlist -J -x https://www.youtube.com/watch?v=rpOZblmWQd4
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/home/roshke/sinusbot2/youtube-dl/youtube_dl/extractor/youtube.py", line 1221, in _decrypt_signature
    video_id, player_url, s
  File "/home/roshke/sinusbot2/youtube-dl/youtube_dl/extractor/youtube.py", line 1130, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/home/roshke/sinusbot2/youtube-dl/youtube_dl/extractor/youtube.py", line 1193, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "/home/roshke/sinusbot2/youtube-dl/youtube_dl/extractor/common.py", line 983, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError(u'Unable to extract \x1b[0;34mInitial JS player signature function name\x1b[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
null
```

**Comment by DruggedBunny** [comment]
Same here as of just now, even with Nov 3 update:

```
M:\YTDL>youtube-dl.exe https://www.youtube.com/watch?v=hlHFlrXZmKQ
[youtube] hlHFlrXZmKQ: Downloading webpage
[youtube] hlHFlrXZmKQ: Downloading video info webpage
[youtube] hlHFlrXZmKQ: Downloading js player vfls4aurX
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpxh4iffn2\bu
ild\youtube_dl\extractor\youtube.py", line 1221, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpxh4iffn2\bu
ild\youtube_dl\extractor\youtube.py", line 1130, in _extract_signature_function
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpxh4iffn2\bu
ild\youtube_dl\extractor\youtube.py", line 1193, in _parse_sig_js
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpxh4iffn2\bu
ild\youtube_dl\extractor\common.py", line 983, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signatu
re function name; please report this issue on https://yt-dl.org/bug . Make sure
you are using the latest version; type  youtube-dl -U  to update. Be sure to cal
l youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract Initial JS player signature fu
nction name; please report this issue on https://yt-dl.org/bug . Make sure you a
re using the latest version; type  youtube-dl -U  to update. Be sure to call you
tube-dl with the --verbose flag and include its complete output.',)); please rep
ort this issue on https://yt-dl.org/bug . Make sure you are using the latest ver
sion; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verb
ose flag and include its complete output.
```

**Comment by akcho** [comment]
cho$ youtube-dl -x --audio-format wav --audio-quality 0 https://www.youtube.com/watch?v=tvgXibRjjps
[youtube] tvgXibRjjps: Downloading webpage
[youtube] tvgXibRjjps: Downloading video info webpage
[youtube] tvgXibRjjps: Downloading js player vfl6LN1Nj
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1221, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1130, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1193, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 983, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract \x1b[0;34mInitial JS player signature function name\x1b[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by kooroshh** [comment]
`youtube-dl --proxy socks5://127.0.0.1:1080 -f bestaudio --extract-audio --audio-format mp3 --audio-quality 0 --embed-thumbnail --add-metadata --verbose https://www.youtube.com/watch?v=nsidqyx9IoE
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--proxy', 'socks5://127.0.0.1:1080', '-f', 'bestaudio', '--extract-audio', '--audio-format', 'mp3', '--audio-quality', '0', '--embed-thumbnail', '--add-metadata', '--verbose', 'https://www.youtube.com/watch?v=nsidqyx9IoE']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.11.03
[debug] Python version 3.5.3 (CPython) - Linux-4.4.0-17763-Microsoft-x86_64-with-debian-9.5
[debug] exe versions: none
[debug] Proxy map: {'http': 'socks5://127.0.0.1:1080', 'https': 'socks5://127.0.0.1:1080'}
[youtube] nsidqyx9IoE: Downloading webpage
[youtube] nsidqyx9IoE: Downloading video info webpage
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {18} signature length 41.41, html5 player None
[youtube] nsidqyx9IoE: Downloading player https://www.youtube.com/yts/jsbin/player_ias-vfl6LN1Nj/en_US/base.js
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 1221, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 1130, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 1193, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/common.py", line 983, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract \x1b[0;34mInitial JS player signature function name\x1b[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 1221, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 1130, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 1193, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/common.py", line 983, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 1221, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 1130, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 1193, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/common.py", line 983, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 1814, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 1231, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 1221, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 1130, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 1193, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/common.py", line 983, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract \x1b[0;34mInitial JS player signature function name\x1b[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.`

**Comment by NoirPi** [comment]
```$ youtube-dl -x --audio-format wav --audio-quality 0 https://www.youtube.com/watch?v=tvgXibRjjps
WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
[youtube] tvgXibRjjps: Downloading webpage
[youtube] tvgXibRjjps: Downloading video info webpage
[youtube] tvgXibRjjps: Downloading js player vfls4aurX
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1221, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1130, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1193, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 983, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl-U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract \x1b[0;34mInitial JS player signature function name\x1b[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.```

**Comment by knaik94** [comment]
C:\Users\Karan\Desktop>"C:\Users\kn\ytd.exe" "https://www.youtube.com/watch?v=qDcFryDXQ7U" -F --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=qDcFryDXQ7U', '-F', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.09.10
[debug] Python version 3.4.4 (CPython) - Windows-8.1-6.3.9600
[debug] exe versions: ffmpeg N-92372-gbeaa350e24, ffprobe N-92372-gbeaa350e24
[debug] Proxy map: {}
[youtube] qDcFryDXQ7U: Downloading webpage
[youtube] qDcFryDXQ7U: Downloading video info webpage
[youtube] {18} signature length 41.41, html5 player vfls4aurX
[youtube] qDcFryDXQ7U: Downloading player https://www.youtube.com/yts/jsbin/player-vfls4aurX/en_US/base.js
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0icdbhzn\build\youtube_dl\extractor\youtube.py
", line 1212, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0icdbhzn\build\youtube_dl\extractor\youtube.py
", line 1121, in _extract_signature_function
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0icdbhzn\build\youtube_dl\extractor\youtube.py
", line 1184, in _parse_sig_js
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0icdbhzn\build\youtube_dl\extractor\common.py"
, line 972, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report thi
s issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be s
ure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract Initial JS player signature function name; please report this iss
ue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure t
o call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https:/
/yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtub
e-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0icdbhzn\build\youtube_dl\extractor\youtube.py
", line 1212, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0icdbhzn\build\youtube_dl\extractor\youtube.py
", line 1121, in _extract_signature_function
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0icdbhzn\build\youtube_dl\extractor\youtube.py
", line 1184, in _parse_sig_js
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0icdbhzn\build\youtube_dl\extractor\common.py"
, line 972, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report thi
s issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be s
ure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0icdbhzn\build\youtube_dl\extractor\youtube.py
", line 1212, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0icdbhzn\build\youtube_dl\extractor\youtube.py
", line 1121, in _extract_signature_function
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0icdbhzn\build\youtube_dl\extractor\youtube.py
", line 1184, in _parse_sig_js
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0icdbhzn\build\youtube_dl\extractor\common.py"
, line 972, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report thi
s issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be s
ure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0icdbhzn\build\youtube_dl\YoutubeDL.py", line
792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0icdbhzn\build\youtube_dl\extractor\common.py"
, line 502, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0icdbhzn\build\youtube_dl\extractor\youtube.py
", line 1805, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0icdbhzn\build\youtube_dl\extractor\youtube.py
", line 1222, in _decrypt_signature
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0icdbhzn\build\youtube_dl\extractor\youtube.py
", line 1212, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0icdbhzn\build\youtube_dl\extractor\youtube.py
", line 1121, in _extract_signature_function
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0icdbhzn\build\youtube_dl\extractor\youtube.py
", line 1184, in _parse_sig_js
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0icdbhzn\build\youtube_dl\extractor\common.py"
, line 972, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report thi
s issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be s
ure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract Initial JS player signature function name; please report this iss
ue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure t
o call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https:/
/yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtub
e-dl with the --verbose flag and include its complete output.

**Comment by MasterOfTheTiger** [comment]
I am having the same problems on pretty much any video I want to download.

**Comment by MasterOfTheTiger** [comment]
I believe this is something deeper and more sinister. Possibly YouTube has disabled some way youtube-dl downloads videos. I am going to do more research myself on this.

**Comment by jonathonball** [comment]
same issue
```
$ ./youtube-dl -U
youtube-dl is up-to-date (2018.11.03)
```

**Comment by DruggedBunny** [comment]
Some stuff definitely still works -- example URL:

https://www.youtube.com/watch?v=rIYZYSqj1UA
