### ISSUE TITLE
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug

### ISSUE THREAD

**Issue by douknoukkem** [rg3/youtube-dl#18107]
youtube-dl --verbose 'https://www.youtube.com/watch?v=9T6GCsMCqrk'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=9T6GCsMCqrk']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.10.29
[debug] Python version 3.6.5 (CPython) - Linux-4.18.14-gentoo-x86_64-AMD_FX-tm-8350_Eight-Core_Processor-with-gentoo-2.4.1
[debug] exe versions: ffmpeg 3.4.4, ffprobe 3.4.4, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] 9T6GCsMCqrk: Downloading webpage
[youtube] 9T6GCsMCqrk: Downloading video info webpage
[youtube] {22} signature length 41.41, html5 player vfls4aurX
[youtube] 9T6GCsMCqrk: Downloading player https://www.youtube.com/yts/jsbin/player-vfls4aurX/en_US/base.js
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1221, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib64/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1130, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib64/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1193, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "/usr/lib64/python3.6/site-packages/youtube_dl/extractor/common.py", line 978, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract \x1b[0;34mInitial JS player signature function name\x1b[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1221, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib64/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1130, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib64/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1193, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "/usr/lib64/python3.6/site-packages/youtube_dl/extractor/common.py", line 978, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1221, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib64/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1130, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib64/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1193, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "/usr/lib64/python3.6/site-packages/youtube_dl/extractor/common.py", line 978, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib64/python3.6/site-packages/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib64/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1814, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/usr/lib64/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1231, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1221, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib64/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1130, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib64/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1193, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "/usr/lib64/python3.6/site-packages/youtube_dl/extractor/common.py", line 978, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract \x1b[0;34mInitial JS player signature function name\x1b[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by gunqqer** [comment]
Same/simmilar issue here. Verbose output https://pastebin.com/raw/F2Z7BUQf
