### ISSUE TITLE
youtube: Signature extraction failed

### ISSUE THREAD

**Issue by Earnestly** [rg3/youtube-dl#18106]
* youtube-dl 2018.10.29 (https://github.com/rg3/youtube-dl/commit/f81d44aab6d8ee01024a637cb80374251737872e)

It may be the case of needing more signatures, but currently having this issue with a variety of youtube links.  Here is `-v` output for one of them:

```
% youtube-dl -vg 'https://www.youtube.com/watch?v=5rAOyh7YmEc'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-vg', 'https://www.youtube.com/watch?v=5rAOyh7YmEc']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.10.29
[debug] Python version 3.7.1 (CPython) - Linux-4.19.1-arch1-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg n4.0.3, ffprobe n4.0.3, rtmpdump present
[debug] Proxy map: {}
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 1221, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 1130, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 1193, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 978, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract \x1b[0;34mInitial JS player signature function name\x1b[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 1221, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 1130, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 1193, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 978, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 1221, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 1130, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 1193, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 978, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 1814, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 1231, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 1221, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 1130, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 1193, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 978, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract \x1b[0;34mInitial JS player signature function name\x1b[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by Earnestly** [comment]
It is literally the latest commit as of writing...
