### ISSUE TITLE
Youtube - ERROR: Signature extraction failed: and RegexNotFoundError 8-nov-2018

### ISSUE THREAD

**Issue by onlinepara** [rg3/youtube-dl#18114]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.11.07*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.11.07**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
---
```
# youtube-dl -v https://www.youtube.com/watch?v=8j741TUIET0
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=8j741TUIET0']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.11.07
[debug] Python version 2.7.5 (CPython) - Linux-3.10.0-693.2.2.el7.x86_64-x86_64-with-centos-7.5.1804-Core
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] 8j741TUIET0: Downloading webpage
[youtube] 8j741TUIET0: Downloading video info webpage
[youtube] {18} signature length 102, html5 player vfls4aurX
[youtube] 8j741TUIET0: Downloading player https://www.youtube.com/yts/jsbin/player-vfls4aurX/en_US/base.js
[youtube] {36} signature length 110, html5 player vfls4aurX
[youtube] 8j741TUIET0: Downloading player https://www.youtube.com/yts/jsbin/player-vfls4aurX/en_US/base.js
[youtube] {17} signature length 110, html5 player vfls4aurX
[youtube] {137} signature length 108, html5 player vfls4aurX
[youtube] 8j741TUIET0: Downloading player https://www.youtube.com/yts/jsbin/player-vfls4aurX/en_US/base.js
[youtube] {248} signature length 110, html5 player vfls4aurX
[youtube] {136} signature length 110, html5 player vfls4aurX
[youtube] {247} signature length 102, html5 player vfls4aurX
[youtube] {398} signature length 110, html5 player vfls4aurX
[youtube] {135} signature length 110, html5 player vfls4aurX
[youtube] {244} signature length 108, html5 player vfls4aurX
[youtube] {397} signature length 110, html5 player vfls4aurX
[youtube] {134} signature length 110, html5 player vfls4aurX
[youtube] {243} signature length 110, html5 player vfls4aurX
[youtube] {396} signature length 108, html5 player vfls4aurX
[youtube] {133} signature length 108, html5 player vfls4aurX
[youtube] {242} signature length 102, html5 player vfls4aurX
[youtube] {395} signature length 110, html5 player vfls4aurX
[youtube] {160} signature length 110, html5 player vfls4aurX
[youtube] {278} signature length 102, html5 player vfls4aurX
[youtube] {394} signature length 110, html5 player vfls4aurX
[youtube] {140} signature length 110, html5 player vfls4aurX
[youtube] {171} signature length 102, html5 player vfls4aurX
[youtube] {249} signature length 110, html5 player vfls4aurX
[youtube] {250} signature length 102, html5 player vfls4aurX
[youtube] {251} signature length 110, html5 player vfls4aurX
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on u'https://r1---sn-4g5e6nlk.googlevideo.com/videoplayback?txp=5531432&ip=2a01%3A4f8%3A200%3A50f4%3A%3A2&requiressl=yes&initcwndbps=1250000&gir=yes&mime=video%2Fmp4&ms=au%2Crdu&mt=1541683666&mv=m&sparams=expire%2Cei%2Cip%2Csource%2Cratebypass%2Cmime%2Cdur%2Cclen%2Cipbits%2Cid%2Citag%2Clmt%2Cgir%2Crequiressl&id=o-ANNN5CF40TFV1zwuPIDPYkKbHvm7BS_O8sTN3rzjQjDG&pl=48&mm=31%2C29&mn=sn-4g5e6nlk%2Csn-4g5edns7&clen=9197070&itag=18&lmt=1540794029754096&lsig=AJH55T4wRAIgBDKVdMw_T26f50AH8jahhooTYE_jNdclgVqGIzuT2Z0CIH21KQx-sVGHO7TB157ver9k_G6Z-rOojgKQUl2a30TJ&source=youtube&lsparams=ms%2Cmn%2Cinitcwndbps%2Cpl%2Cmv%2Cmm&ipbits=0&fvip=1&dur=193.979&ei=cTrkW--CFNLt-gb_wK3ABg&ratebypass=yes&expire=1541705425&c=WEB&signature=AHoPOyMwRAIgAJxzwHtVA7puskmEb2fTqya-7o1j0cbUIwAXrg7ZGwkCIBhkYQKoOLCuVC0i9dQnbB_JIWDBzjxYrYHfwRRvZlSZ'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1908, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1847, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 364, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 341, in real_download
    establish_connection()
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2211, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden
```

### Description of your *issue*, suggested solution and other information

My system was working until 2-3 days ago. I have installed litespeed on server. But this issue occurs on apache too. (Probably not about litespeed). I have uptaded to *2018.11.07* today. I got this error.

Also when i tried simple code on ssh, it is working well.
```
# youtube-dl https://www.youtube.com/watch?v=8j741TUIET0
[youtube] 8j741TUIET0: Downloading webpage
[youtube] 8j741TUIET0: Downloading video info webpage
[download] Destination: X Ambassadors - Renegades (Lyric Video)-8j741TUIET0.mp4
[download] 100% of 8.77MiB in 00:00
```
But cannot working on php. getting this error, when works:
-- exec("youtube-dl https://www.youtube.com/watch?v=4ZHwu0uut3k 2>&1", $output); --
```
ERROR: Signature extraction failed: Traceback (most recent call last):" [5]=> string(100) " File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1221, in _decrypt_signature" [6]=> string(27) " video_id, player_url, s" [7]=> string(109) " File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1130, in _extract_signature_function" [8]=> string(34) " res = self._parse_sig_js(code)" [9]=> string(95) " File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1193, in _parse_sig_js" [10]=> string(69) " jscode, 'Initial JS player signature function name', group='sig')" [11]=> string(93) " File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 977, in _search_regex" [12]=> string(60) " raise RegexNotFoundError('Unable to extract %s' % _name)" [13]=> string(292) "RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update.
```
Thanks in advance for help. (My first post so my apologies if I made a mistake.)

**Comment by ramp856** [comment]
I am also getting the same error with version: 2018.09.26, it used to work before few days.

**Comment by TheJayWright** [comment]
I just began getting the error yesterday.

**Comment by ramp856** [comment]
Download the latest version. It fiixed my issue. Hopefully that might fix
your errors too. If it’s not working try re-downloading YouTube-dl again.
