### ISSUE TITLE
Site Support Request -- https://www.thirteen.org/

### ISSUE THREAD

**Issue by digitalhybrid** [rg3/youtube-dl#18127]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.11.07*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2018.11.07**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [X] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Could you please add site support for https://www.thirteen.org/? It is a part of the PBS network.

Example URLs are ...

https://www.thirteen.org/programs/scott-bailey/season-1-episode-1-bnefxg/

https://www.thirteen.org/programs/poldark-masterpiece/episode-1-ohas5n/

https://www.thirteen.org/programs/jamestown/episode-1-xpsgwx/

https://www.thirteen.org/programs/thirteen-specials/brewed-in-brooklyn-i62791/

**Comment by nlevitt** [comment]
+1

```
$ youtube-dl --verbose 'https://www.thirteen.org/programs/america-reframed/detroit-48202-conversations-along-a-postal-route-tzx2ee/'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.thirteen.org/programs/america-reframed/detroit-48202-conversations-along-a-postal-route-tzx2ee/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.05.20
[debug] Python version 3.6.8 (CPython) - FreeBSD-12.0-RELEASE-amd64-64bit-ELF
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3
[debug] Proxy map: {}
[generic] detroit-48202-conversations-along-a-postal-route-tzx2ee: Requesting header
WARNING: Falling back on generic information extractor.
[generic] detroit-48202-conversations-along-a-postal-route-tzx2ee: Downloading webpage
[generic] detroit-48202-conversations-along-a-postal-route-tzx2ee: Extracting information
ERROR: Unsupported URL: https://www.thirteen.org/programs/america-reframed/detroit-48202-conversations-along-a-postal-route-tzx2ee/
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3329, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.thirteen.org/programs/america-reframed/detroit-48202-conversations-along-a-postal-route-tzx2ee/
```

There seems to be a standard PBS video streaming system. I found this video on two other PBS station websites, and they all look similar, and all result in the same error with youtube-dl. It'd be nice if one effort led to support all of these kinds of sites.

https://www.pbssocal.org/programs/america-reframed/detroit-48202-conversations-along-a-postal-route-tzx2ee/
https://www.wliw.org/programs/america-reframed/detroit-48202-conversations-along-a-postal-route-tzx2ee/
