### ISSUE TITLE
Another one try on vk.com/video_ext.php error (seems it truncates id and hash from URL)

### ISSUE THREAD

**Issue by alexander-ii** [rg3/youtube-dl#18142]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.11.07**
- [x] Bug report (encountered problems with youtube-dl)

---

So. We have a link of an embedded video on VK: https://vk.com/video_ext.php?oid=-153313854&id=456239545&hash=0df9a596a1159f31  
The video plays without any problems in an incognito mode. But when you try to download the video from this particular URL it ends with an error.

---

#### Regular video URL

```
MacBook-Pro:Downloads alexander$ youtube-dl -sv https://vk.com/video-153313854_456239545
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-sv', u'https://vk.com/video-153313854_456239545']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.11.07
[debug] Python version 2.7.10 (CPython) - Darwin-18.0.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1-tessus, ffprobe 4.1-tessus
[debug] Proxy map: {}
[vk] -153313854_456239545: Downloading webpage
[vk] -153313854_456239545: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
```

---

#### Embedded video URL

```
MacBook-Pro:Downloads alexander$ youtube-dl -sv https://vk.com/video_ext.php?oid=-153313854&id=456239545&hash=0df9a596a1159f31
[1] 13702
[2] 13703
[2]+  Завершён        id=456239545
MacBook-Pro:Downloads alexander$ [debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-sv', u'https://vk.com/video_ext.php?oid=-153313854']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.11.07
[debug] Python version 2.7.10 (CPython) - Darwin-18.0.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1-tessus, ffprobe 4.1-tessus
[debug] Proxy map: {}
[generic] video_ext: Requesting header
WARNING: Could not send HEAD request to https://vk.com/video_ext.php?oid=-153313854: HTTP Error 418:
[generic] video_ext: Downloading webpage
WARNING: Falling back on generic information extractor.
[generic] video_ext: Extracting information
[redirect] Following redirect to https://vk.com/badbrowser.php
[generic] badbrowser: Requesting header
WARNING: Could not send HEAD request to https://vk.com/badbrowser.php: HTTP Error 418:
[generic] badbrowser: Downloading webpage
WARNING: Falling back on generic information extractor.
[generic] badbrowser: Extracting information
ERROR: Unsupported URL: https://vk.com/badbrowser.php
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2324, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2542, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2532, in _XML
    return parser.close()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1654, in close
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: no element found: line 57, column 7
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3298, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://vk.com/badbrowser.php
```

---

I assume the reason is this line:  
`[debug] Command-line args: [u' - sv', u'https://vk.com/video_ext.php?oid=-153313854']`  
Where mandatory part `&id=456239545&hash=0df9a596a1159f31` is missing.

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command
