### ISSUE TITLE
Unable to download login form for Lynda.com using 2018.11.07 version

### ISSUE THREAD

**Issue by BigData101ex** [rg3/youtube-dl#18158]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.11.07*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2018.11.07**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
C:\Users\bannu\Downloads>youtube-dl.exe --proxy http://web-proxy.in.com:8088 https://www.lynda.com/Python-tutorials/NLP-Python-Machine-Learning-Essential-Training/622075-2.html -u xxxx -p xxxx --no-overwrites --continue --write-description --cookies C:\Users\bannu\Documents\Lynda\cookies.txt  --all-subs -o C:\Users\bannu\Documents\Lynda\Lynda\%(playlist)s\%(chapter)s\%(display_id)s-%(title)s.%(ext)s --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--proxy', 'http://web-proxy.in.com:8088', 'https://www.lynda.com/Python-tutorials/NLP-Python-Machine-Learning-Essential-Training/622075-2.html', '-u', 'PRIVATE', '-p', 'PRIVATE', '--no-overwrites', '--continue', '--write-description', '--cookies', 'C:\\Users\\bannu\\Documents\\Lynda\\cookies.txt', '--all-subs', '-o', 'C:\\Users\\bannu\\Documents\\Lynda\\Lynda\\%(playlist)s\\%(chapter)s\\%(display_id)s-%(title)s.%(ext)s', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.11.07
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.16299
[debug] exe versions: none
[debug] Proxy map: {'http': 'http://web-proxy.in.com:8088', 'https': 'http://web-proxy.in.com:8088'}
[lynda:course] Downloading signin page
ERROR: Unable to extract signin form; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpj6iiia1g\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpj6iiia1g\build\youtube_dl\extractor\common.py", line 507, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpj6iiia1g\build\youtube_dl\extractor\common.py", line 411, in initialize
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpj6iiia1g\build\youtube_dl\extractor\lynda.py", line 25, in _real_initialize
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpj6iiia1g\build\youtube_dl\extractor\lynda.py", line 75, in _login
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpj6iiia1g\build\youtube_dl\extractor\common.py", line 983, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract signin form; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

**Comment by namaljayathunga** [comment]
youtube-dl -u USERNAME -p PASSWARD -o "%(playlist)s/%(chapter_number)s-%(chapter)s/%(playlist_index)s-%(title)s.%(ext)s" -f 1-720 http://www.lynda.com/course-tutorials/BIM-Management-Techniques-Managing-People-Processes/674585-2.html -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-u', 'PRIVATE', '-p', 'PRIVATE', '-o', '%(playlist)s/%(chapter_number)s-%(chapter)s/%(playlist_index)s-%(title)s.%(ext)s', '-f', '1-720', 'http://www.lynda.com/course-tutorials/BIM-Management-Techniques-Managing-People-Processes/674585-2.html', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.11.07
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg N-91211-g5ee203076f, ffprobe N-91211-g5ee203076f
[debug] Proxy map: {}
[lynda:course] Downloading signin page
ERROR: Unable to extract signin form; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpj6iiia1g\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpj6iiia1g\build\youtube_dl\extractor\common.py", line 507, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpj6iiia1g\build\youtube_dl\extractor\common.py", line 411, in initialize
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpj6iiia1g\build\youtube_dl\extractor\lynda.py", line 25, in _real_initialize
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpj6iiia1g\build\youtube_dl\extractor\lynda.py", line 75, in _login
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpj6iiia1g\build\youtube_dl\extractor\common.py", line 983, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract signin form; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by BigData101ex** [comment]
Yes looks like the login elements on Lynda.com have changed and hence the youtube-dl latest version is unable to parse the webpage.

**Comment by BigData101ex** [comment]
How do we submit this issue to the developers?

**Comment by BigData101ex** [comment]
I downloaded the latest version of the exe 11.18 and the issue still persists. The main problem is the exe looks to extract to "C:\\Users\dst\" which doesn't exist, Rather it should use the existing/logged in user location instead of "C:\\Users\dst"

 File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmph_ixabnp\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmph_ixabnp\build\youtube_dl\extractor\common.py", line 507, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmph_ixabnp\build\youtube_dl\extractor\common.py", line 411, in initialize
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmph_ixabnp\build\youtube_dl\extractor\lynda.py", line 25, in _real_initialize
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmph_ixabnp\build\youtube_dl\extractor\lynda.py", line 75, in _login
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmph_ixabnp\build\youtube_dl\extractor\common.py", line 983, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract signin form; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
