### ISSUE TITLE
Signature extraction failed: Traceback (most recent call last)

### ISSUE THREAD

**Issue by mrscientist666** [rg3/youtube-dl#18151]
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpipjeparb\build\youtube_dl\extractor\youtube.py", line 1216, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpipjeparb\build\youtube_dl\extractor\youtube.py", line 1125, in _extract_signature_function
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpipjeparb\build\youtube_dl\extractor\youtube.py", line 1188, in _parse_sig_js
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpipjeparb\build\youtube_dl\extractor\common.py", line 977, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by Hrxn** [comment]
Probably outdated version. But you did not include a full log.
