### ISSUE TITLE
ERROR: WARNING: unable to obtain file audio codec with ffprobe [in YouTube || v 2018.11.07]

### ISSUE THREAD

**Issue by ahoicaptain94** [rg3/youtube-dl#18165]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.11.07*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.11.07**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
PS C:\Users\username\Desktop\ffmpeg\bin> .\youtube-dl.exe -v -x --audio-format mp3 --audio-quality 0 https://www.youtube.co
m/playlist?list=PLM_wSO5nBF4NdBZOmsjcm_f7m6PYbjvPm
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-x', '--audio-format', 'mp3', '--audio-quality', '0', 'https://www.youtube.com/playlist?list=PLM_wSO5nBF4NdBZOmsjcm_f7m6PYbjvPm']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.11.07
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg present, ffprobe present
[debug] Proxy map: {}
[youtube:playlist] PLM_wSO5nBF4NdBZOmsjcm_f7m6PYbjvPm: Downloading webpage
[download] Downloading playlist: for download
[youtube:playlist] PLM_wSO5nBF4NdBZOmsjcm_f7m6PYbjvPm: Downloading page #1
[youtube:playlist] playlist for download: Downloading 103 videos
[download] Downloading video 1 of 103
[youtube] qZRTBplJAyg: Downloading webpage
[youtube] qZRTBplJAyg: Downloading video info webpage
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {18} signature length 41.41, html5 player None
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {36} signature length 41.41, html5 player None
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {17} signature length 41.41, html5 player None
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {135} signature length 41.41, html5 player None
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {244} signature length 41.41, html5 player None
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {134} signature length 41.41, html5 player None
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {243} signature length 41.41, html5 player None
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {133} signature length 41.41, html5 player None
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {242} signature length 41.41, html5 player None
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {160} signature length 41.41, html5 player None
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {278} signature length 41.41, html5 player None
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {140} signature length 41.41, html5 player None
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {171} signature length 41.41, html5 player None
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {249} signature length 41.41, html5 player None
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {250} signature length 41.41, html5 player None
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {251} signature length 41.41, html5 player None
[debug] Invoking downloader on 'https://r3---sn-vuxbavcx-5uid.googlevideo.com/videoplayback?gir=yes&clen=2504490&keepalive=yes&source=youtube&mime=audio%2Fwebm&key=yt6&itag=251&c=WEB&ei=_7zpW7OQA4S0gAeF0rqAAw&fvip=1&mm=31%2C29&mn=sn-vuxbavcx-5uid%2Csn-4g5e6nld&pl=19&id=o-ALwe2An6vXFdN_QyoEuPP7yyUvfqu0kD0ZqNe2jaQWac&requiressl=yes&dur=142.461&mt=1542044805&mv=m&ms=au%2Crdu&ip=85.73.44.154&initcwndbps=570000&lmt=1509097525015208&ipbits=0&expire=1542066527&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&signature=35481EF3FD4341BF5C3B6BCB01DFA254A95BC53F.272C784EDEB0DBDC332D6ABB31E2617C94C6B8DC&ratebypass=yes'
[download] Destination: Alex Clare-Damn Your Eyes Lyrics-qZRTBplJAyg.webm
[download] 100% of 2.39MiB in 00:06
[debug] ffmpeg command line: ffprobe -show_streams "file:Alex Clare-Damn Your Eyes Lyrics-qZRTBplJAyg.webm"
ERROR: WARNING: unable to obtain file audio codec with ffprobe
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpj6iiia1g\build\youtube_dl\YoutubeDL.py", line 2047, in post_process
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpj6iiia1g\build\youtube_dl\postprocessor\ffmpeg.py", line 243, in run
youtube_dl.utils.PostProcessingError: WARNING: unable to obtain file audio codec with ffprobe

<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Hello, I've been trying for a few days now to download some Youtube vids and convert them to mp3 but I'm getting the following error "ERROR: WARNING: unable to obtain file audio codec with ffprobe". I do have the latest version of the Youtube-dl and the full ffmpeg pack (Up to date as well). Last time I checked (a few weeks back) I could download and convert without a problem. I tried several different solutions and I did troubleshoot a lot but couldn't solve it. Some things that might help:
* Using Win10 64 bit
* I have both Python 2 and 3 installed as I use them. (I Uninstalled them and tried to run again but to no avail)
* I usually use the powershell to run the .exe (tried the cmd as well but same error)
* Re-downloaded both Youtube-dl.exe and the FFMPEG pack (same error)
* Tried different playlists, songs etc. (same error)
* Tried the solutions from similar threads (same issue)
* When I tried to reproduce the error by calling the ffprobe.exe and giving the same command the youtube-dl.exe does, the ffprobe.exe worked properly (I think). Heres the log for that:
```
PS C:\Users\username\Desktop\ffmpeg\bin> ./ffprobe -show_streams "file:Alex Clare-Damn Your Eyes Lyrics-qZRTBplJAyg.webm"
ffprobe version N-91646-g78d4b6bd43 Copyright (c) 2007-2018 the FFmpeg developers
  built with gcc 8.2.1 (GCC) 20180813
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
  libavutil      56. 19.100 / 56. 19.100
  libavcodec     58. 23.100 / 58. 23.100
  libavformat    58. 17.103 / 58. 17.103
  libavdevice    58.  4.101 / 58.  4.101
  libavfilter     7. 26.100 /  7. 26.100
  libswscale      5.  2.100 /  5.  2.100
  libswresample   3.  2.100 /  3.  2.100
  libpostproc    55.  2.100 / 55.  2.100
Input #0, matroska,webm, from 'file:Alex Clare-Damn Your Eyes Lyrics-qZRTBplJAyg.webm':
  Metadata:
    encoder         : google/video-file
  Duration: 00:02:22.46, start: -0.007000, bitrate: 140 kb/s
    Stream #0:0(eng): Audio: opus, 48000 Hz, stereo, fltp (default)
[STREAM]
index=0
codec_name=opus
codec_long_name=Opus (Opus Interactive Audio Codec)
profile=unknown
codec_type=audio
codec_time_base=1/48000
codec_tag_string=[0][0][0][0]
codec_tag=0x0000
sample_fmt=fltp
sample_rate=48000
channels=2
channel_layout=stereo
bits_per_sample=0
id=N/A
r_frame_rate=0/0
avg_frame_rate=0/0
time_base=1/1000
start_pts=-7
start_time=-0.007000
duration_ts=N/A
duration=N/A
bit_rate=N/A
max_bit_rate=N/A
bits_per_raw_sample=N/A
nb_frames=N/A
nb_read_frames=N/A
nb_read_packets=N/A
DISPOSITION:default=1
DISPOSITION:dub=0
DISPOSITION:original=0
DISPOSITION:comment=0
DISPOSITION:lyrics=0
DISPOSITION:karaoke=0
DISPOSITION:forced=0
DISPOSITION:hearing_impaired=0
DISPOSITION:visual_impaired=0
DISPOSITION:clean_effects=0
DISPOSITION:attached_pic=0
DISPOSITION:timed_thumbnails=0
TAG:language=eng
[/STREAM]

END OF LOG
```
Any ideas? Thanks a lot!

**Comment by dstftw** [comment]
Broken ffmpeg/ffprobe setup.

**Comment by AndrewMTA** [comment]
I'm getting the same error
