### ISSUE TITLE
Unable to download youtube video 403 forbidden

### ISSUE THREAD

**Issue by flhang** [rg3/youtube-dl#18161]
> youtube-dl --version
2018.11.07

> youtube-dl  "https://www.youtube.com/watch?v=71wQeC3ohug" -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=71wQeC3ohug', '-v']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2018.11.07
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg 3.4.2, ffprobe 3.4.2, rtmpdump 2.4.0
[debug] Proxy map: {'https': 'https://127.0.0.1:1080', 'http': 'http://127.0.0.1:1080', 'ftp': 'ftp://127.0.0.1:1080'}
[youtube] 71wQeC3ohug: Downloading webpage
[youtube] 71wQeC3ohug: Downloading video info webpage
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on 'https://r2---sn-ogul7n7d.googlevideo.com/videoplayback?mt=1542023459&pl=23&mv=m&ei=h2npW-uJN9CAqAGFnpMQ&ms=au%2Crdu&mm=31%2C29&expire=1542045160&clen=111336310&ip=121.50.46.248&requiressl=yes&source=youtube&signature=3C71BF6D8D3534FB1CED7E1D596E1E1D9A1EF2E4.5A9776AA7C50D77B217E68FA5905265D375BB3E9&lmt=1540632754231181&mime=video%2Fmp4&key=yt6&itag=137&dur=216.416&fvip=2&gcr=jp&initcwndbps=867500&ipbits=0&c=WEB&keepalive=yes&id=o-ABsW8vL4iJo_Mi2WfsnX9pVP_9KPiHcpoOMaNvXvV1OT&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&gir=yes&mn=sn-ogul7n7d%2Csn-oguelnl7&sparams=aitags%2Cclen%2Cdur%2Cei%2Cgcr%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&txp=5432432&ratebypass=yes'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpj6iiia1g\build\youtube_dl\YoutubeDL.py", line 1902, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpj6iiia1g\build\youtube_dl\YoutubeDL.py", line 1847, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpj6iiia1g\build\youtube_dl\downloader\common.py", line 364, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpj6iiia1g\build\youtube_dl\downloader\http.py", line 341, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpj6iiia1g\build\youtube_dl\downloader\http.py", line 109, in establish_connection
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpj6iiia1g\build\youtube_dl\YoutubeDL.py", line 2211, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by dstftw** [comment]
Most likely caused by your proxy.
