### ISSUE TITLE
AETV error IndexError: list index out of range

### ISSUE THREAD

**Issue by jlick** [rg3/youtube-dl#18167]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.11.07*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.11.07**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--list-formats', u'https://www.aetv.com/shows/live-pd/season-3/episode-17']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.11.07
[debug] Python version 2.7.13 (CPython) - Linux-4.9.0-8-amd64-x86_64-with-debian-9.6
[debug] exe versions: ffmpeg 3.2.12-1, ffprobe 3.2.12-1
[debug] Proxy map: {}
[aenetworks] live-pd/season-3/episode-17: Downloading webpage
[aenetworks] 1367458883918: Downloading JSON metadata
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/jlick/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/home/jlick/bin/youtube-dl/youtube_dl/__init__.py", line 472, in main
  File "/home/jlick/bin/youtube-dl/youtube_dl/__init__.py", line 462, in _real_main
  File "/home/jlick/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2001, in download
  File "/home/jlick/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
  File "/home/jlick/bin/youtube-dl/youtube_dl/extractor/common.py", line 508, in extract
  File "/home/jlick/bin/youtube-dl/youtube_dl/extractor/aenetworks.py", line 142, in _real_extract
IndexError: list index out of range
```

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

Getting the error "IndexError: list index out of range" when trying to use youtube-dl do anything with https://www.aetv.com/shows/live-pd/season-3/episode-17

Example command to show error: youtube-dl --list-formats https://www.aetv.com/shows/live-pd/season-3/episode-17

This episode plays fine in Chrome or Firefox.

Other episodes (e.g. 16) work fine with youtube-dl.

**Comment by remitamine** [comment]
```
[aenetworks] live-pd/season-3/episode-17: Downloading webpage
[aenetworks] 1371630659947: Downloading JSON metadata
[aenetworks] 1371630659947: Retrieving Media Token
[aenetworks] 1371630659947: Downloading SMIL data
[aenetworks] 1371630659947: Downloading m3u8 information
[download] Destination: Live PD - 160-1371630659947.mp4
ffmpeg version n4.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 8.2.1 (GCC) 20180831
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-nvdec --enable-nvenc --enable-omx --enable-shared --enable-version3
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
[hls,applehttp @ 0x55d5d90ad4c0] Opening 'https://os-vh.akamaihd.net/i/AETN-AETV_VMS/BRANDHD2997_AEN_LPDO_216827_TVE_444_5994_180_20181110_00_,25,18,13,10,7,4,2,1,00.mp4.csmil/crypt.key?null=0&id=AgBo7ZO%2fFzDURL8R9FutFvP51UHrxWyIkwzcEbE9na2CiQaXcwzyAJJMpmHXuv2LPDRBNVrwy0hmeQ%3d%3d&hdntl=exp=1542808383~acl=/i/AETN-AETV_VMS/BRANDHD2997_AEN_LPDO_216827_TVE_444_5994_180_20181110_00_*~data=hdntl~hmac=ca83aa049acb39572513027854995b52d6950e6f75683ada69135036ba528c0d' for reading
[hls,applehttp @ 0x55d5d90ad4c0] Opening 'crypto+https://os-vh.akamaihd.net/i/AETN-AETV_VMS/BRANDHD2997_AEN_LPDO_216827_TVE_444_5994_180_20181110_00_,25,18,13,10,7,4,2,1,00.mp4.csmil/segment1_0_av.ts?null=0&id=AgBo7ZO%2fFzDURL8R9FutFvP51UHrxWyIkwzcEbE9na2CiQaXcwzyAJJMpmHXuv2LPDRBNVrwy0hmeQ%3d%3d&hdntl=exp=1542808383~acl=/i/AETN-AETV_VMS/BRANDHD2997_AEN_LPDO_216827_TVE_444_5994_180_20181110_00_*~data=hdntl~hmac=ca83aa049acb39572513027854995b52d6950e6f75683ada69135036ba528c0d' for reading
Input #0, hls,applehttp, from 'https://os-vh.akamaihd.net/i/AETN-AETV_VMS/BRANDHD2997_AEN_LPDO_216827_TVE_444_5994_180_20181110_00_,25,18,13,10,7,4,2,1,00.mp4.csmil/index_0_av.m3u8?null=0&id=AgBo7ZO%2fFzDURL8R9FutFvP51UHrxWyIkwzcEbE9na2CiQaXcwzyAJJMpmHXuv2LPDRBNVrwy0hmeQ%3d%3d&hdntl=exp=1542808383~acl=%2fi%2fAETN-AETV_VMS%2fBRANDHD2997_AEN_LPDO_216827_TVE_444_5994_180_20181110_00_*~data=hdntl~hmac=ca83aa049acb39572513027854995b52d6950e6f75683ada69135036ba528c0d':
  Duration: 02:11:30.09, start: 0.100667, bitrate: 0 kb/s
  Program 0 
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], Closed Captions, 29.97 tbr, 90k tbn, 59.94 tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
Output #0, mp4, to 'file:Live PD - 160-1371630659947.mp4.part':
  Metadata:
    encoder         : Lavf58.20.100
    Stream #0:0: Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], q=2-31, 29.97 tbr, 90k tbn, 90k tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=  180 fps=0.0 q=-1.0 size=     256kB time=00:00:06.01 bitrate= 348.7kbits
```
