### ISSUE TITLE
YouTube signature error

### ISSUE THREAD

**Issue by mesb1** [rg3/youtube-dl#18197]
---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.11.07*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2018.11.07**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
Ver:
youtube-dl -U
youtube-dl is up-to-date (2018.11.07)

[ant@flagship1 ~]$ youtube-dl https://www.youtube.com/watch?v=mIQbC5SfI8o --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.youtube.com/watch?v=mIQbC5SfI8o', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.11.07
[debug] Python version 2.7.15 (CPython) - Linux-4.14.78-desktop-1.mga6-x86_64-with-mageia-6-Official
[debug] exe versions: ffmpeg 3.3.8, ffprobe 3.3.8
[debug] Proxy map: {}
[youtube] mIQbC5SfI8o: Downloading webpage
[youtube] mIQbC5SfI8o: Downloading video info webpage
[youtube] {22} signature length 43.40, html5 player vflVKnssA
[youtube] mIQbC5SfI8o: Downloading player https://www.youtube.com/yts/jsbin/player-vflVKnssA/en_US/base.js
[youtube] {43} signature length 43.40, html5 player vflVKnssA
[youtube] {18} signature length 43.40, html5 player vflVKnssA
[youtube] {36} signature length 41.40, html5 player vflVKnssA
[youtube] mIQbC5SfI8o: Downloading player https://www.youtube.com/yts/jsbin/player-vflVKnssA/en_US/base.js
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1225, in _decrypt_signature
    video_id, player_url, s
  File "/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1132, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "/bin/youtube-dl/youtube_dl/extractor/common.py", line 772, in _download_webpage
    expected_status=expected_status)
  File "/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 267, in _download_webpage_handle
    *args, **compat_kwargs(kwargs))
  File "/bin/youtube-dl/youtube_dl/extractor/common.py", line 638, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "/bin/youtube-dl/youtube_dl/extractor/common.py", line 623, in _request_webpage
    raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
ExtractorError: Download of https://www.youtube.com/yts/jsbin/player-vflVKnssA/en_US/base.js failed: <urlopen error [Errno 104] Connection reset by peer> (caused by URLError(error(104, 'Connection reset by peer'),))
 (caused by ExtractorError(u"Download of https://www.youtube.com/yts/jsbin/player-vflVKnssA/en_US/base.js failed: <urlopen error [Errno 104] Connection reset by peer> (caused by URLError(error(104, 'Connection reset by peer'),))",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1225, in _decrypt_signature
    video_id, player_url, s
  File "/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1132, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "/bin/youtube-dl/youtube_dl/extractor/common.py", line 772, in _download_webpage
    expected_status=expected_status)
  File "/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 267, in _download_webpage_handle
    *args, **compat_kwargs(kwargs))
  File "/bin/youtube-dl/youtube_dl/extractor/common.py", line 638, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "/bin/youtube-dl/youtube_dl/extractor/common.py", line 623, in _request_webpage
    raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
ExtractorError: Download of https://www.youtube.com/yts/jsbin/player-vflVKnssA/en_US/base.js failed: <urlopen error [Errno 104] Connection reset by peer> (caused by URLError(error(104, 'Connection reset by peer'),))
Traceback (most recent call last):
  File "/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/bin/youtube-dl/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1837, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1235, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1225, in _decrypt_signature
    video_id, player_url, s
  File "/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1132, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "/bin/youtube-dl/youtube_dl/extractor/common.py", line 772, in _download_webpage
    expected_status=expected_status)
  File "/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 267, in _download_webpage_handle
    *args, **compat_kwargs(kwargs))
  File "/bin/youtube-dl/youtube_dl/extractor/common.py", line 638, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "/bin/youtube-dl/youtube_dl/extractor/common.py", line 623, in _request_webpage
    raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
ExtractorError: Download of https://www.youtube.com/yts/jsbin/player-vflVKnssA/en_US/base.js failed: <urlopen error [Errno 104] Connection reset by peer> (caused by URLError(error(104, 'Connection reset by peer'),))
 (caused by ExtractorError(u"Download of https://www.youtube.com/yts/jsbin/player-vflVKnssA/en_US/base.js failed: <urlopen error [Errno 104] Connection reset by peer> (caused by URLError(error(104, 'Connection reset by peer'),))",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
Network issue on your side.

**Comment by hugbubby** [comment]
It is very much not. You have decided to close like 5 of these same issues. I'm having the exact same problem.

**Comment by Hrxn** [comment]
Based from the log info submitted here, it very much looks like a network issue though..
