### ISSUE TITLE
tubepornclassic.com

### ISSUE THREAD

**Issue by colemar** [rg3/youtube-dl#18190]
---

- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.11.07**

- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
```
C:\tmp>youtube-dl -v https://it.tubepornclassic.com/videos/1033544/softcore-nudes-578-1960-s-scene-6/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://it.tubepornclassic.com/videos/1033544/softcore-nudes-578-1960-s-scene-6/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.11.07
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg N-82889-g54931fd, ffprobe N-82889-g54931fd, phantomjs 2.1.1
[debug] Proxy map: {}
[generic] softcore-nudes-578-1960-s-scene-6: Requesting header
WARNING: Falling back on generic information extractor.
[generic] softcore-nudes-578-1960-s-scene-6: Downloading webpage
[generic] softcore-nudes-578-1960-s-scene-6: Extracting information
ERROR: Unsupported URL: https://it.tubepornclassic.com/videos/1033544/softcore-nudes-578-1960-s-scene-6/
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpj6iiia1g\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpj6iiia1g\build\youtube_dl\extractor\common.py", line 508, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpj6iiia1g\build\youtube_dl\extractor\generic.py", line 3298, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://it.tubepornclassic.com/videos/1033544/softcore-nudes-578-1960-s-scene-6/
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://it.tubepornclassic.com/videos/1033544/softcore-nudes-578-1960-s-scene-6/
- Single video: https://tubepornclassic.com/videos/148951/mangiati-vivi/
- Playlist: https://tubepornclassic.com/playlist/5/

**Comment by Chronigan** [comment]
I'd like to up vote this. The site uses m3u8 files to serve the videos.
