### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0'

### ISSUE THREAD

**Issue by canavan** [rg3/youtube-dl#1822]
The following error occurs on both Linux and IRIX, both using python 2.7:

$ ./youtube-dl --verbose http://www.collegehumor.com/video/6939029
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.collegehumor.com/video/6939029']
[debug] youtube-dl version 2013.11.24.1
[debug] Python version 2.7.5+ - Linux-3.11.6-i686-with-Ubuntu-13.10-saucy
[debug] Proxy map: {}
[CollegeHumor] 6939029: Extracting information
[CollegeHumor] 6939029: Downloading info XML
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "./youtube-dl/__main__.py", line 18, in <module>
  File "./youtube-dl/youtube_dl/**init**.py", line 775, in main
  File "./youtube-dl/youtube_dl/**init**.py", line 728, in _real_main
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 791, in download
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 416, in extract_info
  File "./youtube-dl/youtube_dl/extractor/common.py", line 129, in extract
  File "./youtube-dl/youtube_dl/extractor/collegehumor.py", line 53, in _real_extract
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1640, in feed
    self._parser.Parse(data, 0)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 1416: ordinal not in range(128)

**Comment by canavan** [comment]
You will have to post the full output of youtube-dl downloading a video that causes the problem with `--verbose` added to the command line. Even if  it's also a collegehumor video, you'll probably have to open a new issue, but if the debug output is substantially similar, refer to this issue in the new one.
