### ISSUE TITLE
some videos report error "Signature extraction failed ... http.client.IncompleteRead: IncompleteRead"

### ISSUE THREAD

**Issue by changjian-k2k** [rg3/youtube-dl#18232]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.11.18*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2018.11.18**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-F', 'SdzLl-XpJt0']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2018.11.18
[debug] Python version 3.5.2 (CPython) - Windows-10-10.0.17134-SP0
[debug] exe versions: none
[debug] Proxy map: {'ftp': 'ftp://127.0.0.1:8087', 'http': 'http://127.0.0.1:8087', 'https': 'https://127.0.0.1:8087'}
[youtube] SdzLl-XpJt0: Downloading webpage
[youtube] SdzLl-XpJt0: Downloading video info webpage
[youtube] {18} signature length 44.40, html5 player vflWnjS_n
[youtube] SdzLl-XpJt0: Downloading player https://www.youtube.com/yts/jsbin/player-vflWnjS_n/en_US/base.js
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "c:\python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1225, in _decrypt_signature
    video_id, player_url, s
  File "c:\python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1132, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "c:\python35\lib\site-packages\youtube_dl\extractor\common.py", line 777, in _download_webpage
    raise e
  File "c:\python35\lib\site-packages\youtube_dl\extractor\common.py", line 772, in _download_webpage
    expected_status=expected_status)
  File "c:\python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 267, in _download_webpage_handle
    *args, **compat_kwargs(kwargs))
  File "c:\python35\lib\site-packages\youtube_dl\extractor\common.py", line 642, in _download_webpage_handle
    content = self._webpage_read_content(urlh, url_or_request, video_id, note, errnote, fatal, encoding=encoding)
  File "c:\python35\lib\site-packages\youtube_dl\extractor\common.py", line 692, in _webpage_read_content
    webpage_bytes = urlh.read()
  File "c:\python35\lib\http\client.py", line 461, in read
    s = self._safe_read(self.length)
  File "c:\python35\lib\http\client.py", line 609, in _safe_read
    raise IncompleteRead(b''.join(s), amt)
http.client.IncompleteRead: IncompleteRead(524288 bytes read, 808090 more expected)
 (caused by IncompleteRead(524288 bytes read, 808090 more expected)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1225, in _decrypt_signature
    video_id, player_url, s
  File "c:\python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1132, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "c:\python35\lib\site-packages\youtube_dl\extractor\common.py", line 777, in _download_webpage
    raise e
  File "c:\python35\lib\site-packages\youtube_dl\extractor\common.py", line 772, in _download_webpage
    expected_status=expected_status)
  File "c:\python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 267, in _download_webpage_handle
    *args, **compat_kwargs(kwargs))
  File "c:\python35\lib\site-packages\youtube_dl\extractor\common.py", line 642, in _download_webpage_handle
    content = self._webpage_read_content(urlh, url_or_request, video_id, note, errnote, fatal, encoding=encoding)
  File "c:\python35\lib\site-packages\youtube_dl\extractor\common.py", line 692, in _webpage_read_content
    webpage_bytes = urlh.read()
  File "c:\python35\lib\http\client.py", line 461, in read
    s = self._safe_read(self.length)
  File "c:\python35\lib\http\client.py", line 609, in _safe_read
    raise IncompleteRead(b''.join(s), amt)
http.client.IncompleteRead: IncompleteRead(524288 bytes read, 808090 more expected)
Traceback (most recent call last):
  File "c:\python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1225, in _decrypt_signature
    video_id, player_url, s
  File "c:\python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1132, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "c:\python35\lib\site-packages\youtube_dl\extractor\common.py", line 777, in _download_webpage
    raise e
  File "c:\python35\lib\site-packages\youtube_dl\extractor\common.py", line 772, in _download_webpage
    expected_status=expected_status)
  File "c:\python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 267, in _download_webpage_handle
    *args, **compat_kwargs(kwargs))
  File "c:\python35\lib\site-packages\youtube_dl\extractor\common.py", line 642, in _download_webpage_handle
    content = self._webpage_read_content(urlh, url_or_request, video_id, note, errnote, fatal, encoding=encoding)
  File "c:\python35\lib\site-packages\youtube_dl\extractor\common.py", line 692, in _webpage_read_content
    webpage_bytes = urlh.read()
  File "c:\python35\lib\http\client.py", line 461, in read
    s = self._safe_read(self.length)
  File "c:\python35\lib\http\client.py", line 609, in _safe_read
    raise IncompleteRead(b''.join(s), amt)
http.client.IncompleteRead: IncompleteRead(524288 bytes read, 808090 more expected)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "c:\python35\lib\site-packages\youtube_dl\extractor\common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "c:\python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1837, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "c:\python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1235, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "c:\python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1225, in _decrypt_signature
    video_id, player_url, s
  File "c:\python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1132, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "c:\python35\lib\site-packages\youtube_dl\extractor\common.py", line 777, in _download_webpage
    raise e
  File "c:\python35\lib\site-packages\youtube_dl\extractor\common.py", line 772, in _download_webpage
    expected_status=expected_status)
  File "c:\python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 267, in _download_webpage_handle
    *args, **compat_kwargs(kwargs))
  File "c:\python35\lib\site-packages\youtube_dl\extractor\common.py", line 642, in _download_webpage_handle
    content = self._webpage_read_content(urlh, url_or_request, video_id, note, errnote, fatal, encoding=encoding)
  File "c:\python35\lib\site-packages\youtube_dl\extractor\common.py", line 692, in _webpage_read_content
    webpage_bytes = urlh.read()
  File "c:\python35\lib\http\client.py", line 461, in read
    s = self._safe_read(self.length)
  File "c:\python35\lib\http\client.py", line 609, in _safe_read
    raise IncompleteRead(b''.join(s), amt)
http.client.IncompleteRead: IncompleteRead(524288 bytes read, 808090 more expected)
 (caused by IncompleteRead(524288 bytes read, 808090 more expected)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

---

---

### Description of your *issue*, suggested solution and other information

ERROR: Signature extraction failed: Traceback (most recent call last):
...
http.client.IncompleteRead: IncompleteRead(524288 bytes read, 808090 more expected)
 (caused by IncompleteRead(524288 bytes read, 808090 more expected)); ...

Some youtube videos can be downloaded properly, but some of them cannot be downloaded with error: http.client.IncompleteRead. While all the videos can be played in explorer.

I searched the closed issues and found that @dstftw had said it was an error caused by proxy. However, video can be played in the explorer correctly. I think there should be other reasons causing this issue.

**Comment by dstftw** [comment]
This caused by your proxy. Your browser may play different format.
