### ISSUE TITLE
Site support request: narando.com

### ISSUE THREAD

**Issue by Nudin** [rg3/youtube-dl#18252]
---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.11.18*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.11.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://narando.com/articles/icarus-forscher-beobachten-tiere-via-iss']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.11.18
[debug] Python version 3.7.1 (CPython) - Linux-4.18.19.a-1-hardened-x86_64-with-arch
[debug] exe versions: ffmpeg n4.1, ffprobe n4.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] icarus-forscher-beobachten-tiere-via-iss: Requesting header
WARNING: Falling back on generic information extractor.
[generic] icarus-forscher-beobachten-tiere-via-iss: Downloading webpage
[generic] icarus-forscher-beobachten-tiere-via-iss: Extracting information
ERROR: Unsupported URL: https://narando.com/articles/icarus-forscher-beobachten-tiere-via-iss
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/generic.py", line 3318, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://narando.com/articles/icarus-forscher-beobachten-tiere-via-iss
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single audio: https://narando.com/articles/icarus-forscher-beobachten-tiere-via-iss
- Embeded player: https://www.golem.de/news/icarus-forscher-beobachten-tiere-via-iss-1811-137720.html

---

### Description of your *issue*, suggested solution and other information

Narando is a service that provides spoken versions of articles of multiple (mostly German) news sites and online journals. They use html-audio-player playing static mp3-files, so writing an extractor should be possible.

**Comment by ealgase** [comment]
Looks doable, working on it now.
