### ISSUE TITLE
Issue #18249 still happening with verified videos- multiple vids on multiple platforms

### ISSUE THREAD

**Issue by Datan0de** [rg3/youtube-dl#18256]
Nope. Still happening with different videos. Got error message, then verified that it plays properly in browser. Windows and Mac.

pornacct$ youtube-dl --verbose https://xhamster.com/videos/teen-snapchat-compilation-10492935
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://xhamster.com/videos/teen-snapchat-compilation-10492935']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.11.18
[debug] Python version 2.7.10 (CPython) - Darwin-17.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.3.1, ffprobe 3.3.1
[debug] Proxy map: {}
[XHamster] 10492935: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://19-12.b.cdn13.com/010/492/935/720p.h264.mp4?cdn_creation_time=1542682800&cdn_ttl=14400&cdn_bw=192k&cdn_bw_fs=784k&cdn_cv_data=24.164.53.152-dvp&cdn_hash=38bb168a5cbd9cd617616a37bfea669f'
ERROR: unable to download video data: <urlopen error [Errno 8] nodename nor servname provided, or not known>
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1908, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1847, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 364, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 341, in real_download
    establish_connection()
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2211, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1139, in https_open
    req, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 8] nodename nor servname provided, or not known>

_Originally posted by @Datan0de in https://github.com/rg3/youtube-dl/issue_comments#issuecomment-440128881_

**Comment by dstftw** [comment]
DNS issue on your side.

**Comment by Datan0de** [comment]
Thank you.
