### ISSUE TITLE
VRT nu - "De Ideale Wereld " not working

### ISSUE THREAD

**Issue by aTerACeNT** [rg3/youtube-dl#18267]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.11.18*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.11.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
C:\Users\aTerACeNT\Desktop>yt -v https://www.vrt.be/vrtnu/a-z/de-ideale-wereld/2018-nj/de-ideale-wereld-d20181120/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.vrt.be/vrtnu/a-z/de-ideale-wereld/2018-nj/de-ideale-wereld-d20181120/']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.11.18
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: none
[debug] Proxy map: {}
[VrtNU] de-ideale-wereld-d20181120: Downloading webpage
[VrtNU] de-ideale-wereld-d20181120: Downloading JSON metadata
[Canvas] pbs-pub-98548fad-878a-45ea-8704-6d279aa23c5e$vid-6fc12be0-0293-4972-975c-55c92e0dab2a: Downloading JSON metadata
[Canvas] pbs-pub-98548fad-878a-45ea-8704-6d279aa23c5e$vid-6fc12be0-0293-4972-975c-55c92e0dab2a: Downloading m3u8 information
WARNING: Failed to download m3u8 information: <urlopen error [Errno 11001] getaddrinfo failed>
[Canvas] pbs-pub-98548fad-878a-45ea-8704-6d279aa23c5e$vid-6fc12be0-0293-4972-975c-55c92e0dab2a: Downloading MPD manifest
WARNING: Failed to download MPD manifest: <urlopen error [Errno 11001] getaddrinfo failed>
[Canvas] pbs-pub-98548fad-878a-45ea-8704-6d279aa23c5e$vid-6fc12be0-0293-4972-975c-55c92e0dab2a: Downloading ISM manifest
WARNING: Failed to download ISM manifest: <urlopen error [Errno 11001] getaddrinfo failed>
[Canvas] pbs-pub-98548fad-878a-45ea-8704-6d279aa23c5e$vid-6fc12be0-0293-4972-975c-55c92e0dab2a: Downloading f4m manifest
WARNING: Unable to download f4m manifest: <urlopen error [Errno 11001] getaddrinfo failed>
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmph_ixabnp\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmph_ixabnp\build\youtube_dl\extractor\common.py", line 508, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmph_ixabnp\build\youtube_dl\extractor\canvas.py", line 73, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmph_ixabnp\build\youtube_dl\extractor\common.py", line 1292, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

---

### Description of your *issue*, suggested solution and other information

The website VRT and VRTnu are supported (as you can find in [this list](http://rg3.github.io/youtube-dl/supportedsites.html))
All links are working, except the links for "De Ideale Wereld"
Working links are eg https://www.vrt.be/vrtnu/a-z/publiek-geheim/2012/publiek-geheim-s2012a7/
But every link for "De Ideale Wereld" is not working
```
C:\Users\aTerACeNT\Desktop>yt https://www.vrt.be/vrtnu/a-z/publiek-geheim/2012/publiek-geheim-s2012a7/
[VrtNU] publiek-geheim-s2012a7: Downloading webpage
[VrtNU] publiek-geheim-s2012a7: Downloading JSON metadata
[Canvas] pbs-pub-f1d00421-9795-4876-8073-6438fd370c56$vid-23624ddf-a1e1-4c02-a979-5dac1f8d4242: Downloading JSON metadata
[Canvas] pbs-pub-f1d00421-9795-4876-8073-6438fd370c56$vid-23624ddf-a1e1-4c02-a979-5dac1f8d4242: Downloading m3u8 information
[Canvas] pbs-pub-f1d00421-9795-4876-8073-6438fd370c56$vid-23624ddf-a1e1-4c02-a979-5dac1f8d4242: Downloading MPD manifest
WARNING: [Canvas] Unknown MIME type application/mp4 in DASH manifest
[Canvas] pbs-pub-f1d00421-9795-4876-8073-6438fd370c56$vid-23624ddf-a1e1-4c02-a979-5dac1f8d4242: Downloading ISM manifest
[Canvas] pbs-pub-f1d00421-9795-4876-8073-6438fd370c56$vid-23624ddf-a1e1-4c02-a979-5dac1f8d4242: Downloading f4m manifest
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 261
[download] Destination: De grafgalerijen van Laken-pbs-pub-f1d00421-9795-4876-8073-6438fd370c56$vid-23624ddf-a1e1-4c02-a979-5dac1f8d4242.mp4
[download] 100% of 219.87MiB in 04:00
WARNING: pbs-pub-f1d00421-9795-4876-8073-6438fd370c56$vid-23624ddf-a1e1-4c02-a979-5dac1f8d4242: malformed AAC bitstream detected. Install ffmpeg or avconv to fix this automatically.
```

**Comment by aTerACeNT** [comment]
If you consider this a duplicate, would you mind mentioning the "original" issue that would still be open?
