### ISSUE TITLE
Site support request: academy.gns3.com

### ISSUE THREAD

**Issue by therom123** [rg3/youtube-dl#18272]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.11.18**

- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

- [x] Site support request (request for adding support for a new site)

---

- Playlist: https://academy.gns3.com/courses/423415
It downloads only first video in the playlist, but not all remaining videos:

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-u', 'PRIVATE', '-p', 'PRIVATE', '-f', 'mp4_video-0
', '-v', 'https://academy.gns3.com/courses/423415']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.11.18
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[generic] 423415: Requesting header
[redirect] Following redirect to https://academy.gns3.com/p/gns3-certified-associate
[generic] gns3-certified-associate: Requesting header
WARNING: Falling back on generic information extractor.
[generic] gns3-certified-associate: Downloading webpage
[generic] gns3-certified-associate: Extracting information
[Wistia] 7mrhxioa0j: Downloading JSON metadata
[debug] Invoking downloader on 'http://embed.wistia.com/deliveries/d49222e1de9970d559f8db9e4a44fc6d13d4bdb4.bin'
[download] Destination: GNS3 Exam Introduction v1.4.mp4-7mrhxioa0j.mp4
[download] 100% of 21.92MiB in 00:22

- First video: https://academy.gns3.com/courses/423415/lectures/6842364
The first video in the playlist can also be successfully downloaded from the direct link, but it does not download all remaining videos that play automatically afterwards:

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-u', 'PRIVATE', '-p', 'PRIVATE', '-f', 'mp4_video-0
', '-v', 'https://academy.gns3.com/courses/423415/lectures/6842364']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.11.18
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[generic] 6842364: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 6842364: Downloading webpage
[generic] 6842364: Extracting information
[Wistia] untlgzk1v7: Downloading JSON metadata
[debug] Invoking downloader on 'http://embed.wistia.com/deliveries/b4950947475376fe892c906de7aea4ad2a4bb469.bin'
[download] Destination: GNS3 Exam Introduction v1.4.mp4-untlgzk1v7.mp4
[download] 100% of 21.91MiB in 00:18

- Second video: https://academy.gns3.com/courses/423415/lectures/6885939
All other videos in the playlist are not downloaded with "Unsupported URL" error message:

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-u', 'PRIVATE', '-p', 'PRIVATE', '-f', 'mp4_video-0
', '-v', 'https://academy.gns3.com/courses/423415/lectures/6885939']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.11.18
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[generic] 6885939: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 6885939: Downloading webpage
[generic] 6885939: Extracting information
ERROR: Unsupported URL: https://academy.gns3.com/courses/423415/lectures/6885939

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmph_ixabnp\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmph_ixabnp\build\youtube_dl\extractor\common.py", line 508, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmph_ixabnp\build\youtube_dl\extractor\generic.py", line 3318, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://academy.gns3.com/courses/423415/lectures/6885939

---

Thank you

**Comment by therom123** [comment]
How can I post my account info? Couldn't find in FAQ

**Comment by therom123** [comment]
Sent credentials to dstftw gmail address
Thank you

**Comment by therom123** [comment]
THANK YOU!!!!
