### ISSUE TITLE
Looks Like ITV Hub is Broken Again

### ISSUE THREAD

**Issue by digitalhybrid** [rg3/youtube-dl#18301]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.11.23*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.11.23**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

[11/25/18 23:19:28] [debug] System config: []
[11/25/18 23:19:28] [debug] User config: []
[11/25/18 23:19:28] [debug] Custom config: []
[11/25/18 23:19:28] [debug] Command-line args: ['--newline', '-i', '-o', 'D:\\_Videos\\_New_Downloads\\%(title)s.%(ext)s', '--ignore-config', '--hls-prefer-native', '-v', 'https://www.itv.com/hub/the-americans/2a2471a0061']
[11/25/18 23:19:28] [debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[11/25/18 23:19:28] [debug] youtube-dl version 2018.11.23
[11/25/18 23:19:28] [debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[11/25/18 23:19:28] [debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2, rtmpdump 2.4
[11/25/18 23:19:28] [debug] Proxy map: {}
[11/25/18 23:19:28] WARNING: Unable to download XML: HTTP Error 504: Gateway Time-out
[11/25/18 23:19:28] WARNING: Unable to download JSON metadata: HTTP Error 403: Forbidden
[11/25/18 23:19:28] ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[11/25/18 23:19:28] Traceback (most recent call last):
[11/25/18 23:19:28]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6bh3thhm\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
[11/25/18 23:19:28]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6bh3thhm\build\youtube_dl\extractor\common.py", line 508, in extract
[11/25/18 23:19:28]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6bh3thhm\build\youtube_dl\extractor\itv.py", line 260, in _real_extract
[11/25/18 23:19:28]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6bh3thhm\build\youtube_dl\extractor\common.py", line 1292, in _sort_formats
[11/25/18 23:19:28] youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[11/25/18 23:19:28] 
[11/25/18 23:19:55] WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[11/25/18 23:19:55] WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[11/25/18 23:19:55] WARNING: Failed to download MPD manifest: HTTP Error 403: Forbidden
[11/25/18 23:19:55] WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[11/25/18 23:19:55] WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[11/25/18 23:19:55] WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[11/25/18 23:19:55] WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[11/25/18 23:19:55] WARNING: Failed to download MPD manifest: HTTP Error 403: Forbidden
[11/25/18 23:19:55] WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[11/25/18 23:19:55] WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[11/25/18 23:19:57] [debug] System config: []
[11/25/18 23:19:57] [debug] User config: []
[11/25/18 23:19:57] [debug] Custom config: []
[11/25/18 23:19:57] [debug] Command-line args: ['--newline', '-i', '-o', 'D:\\_Videos\\_New_Downloads\\%(title)s.%(ext)s', '--ignore-config', '--hls-prefer-native', '-v', 'https://www.itv.com/hub/teen-titans-go/2a3033a0115']
[11/25/18 23:19:57] [debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[11/25/18 23:19:57] [debug] youtube-dl version 2018.11.23
[11/25/18 23:19:57] [debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[11/25/18 23:19:57] [debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2, rtmpdump 2.4
[11/25/18 23:19:57] [debug] Proxy map: {}
[11/25/18 23:19:57] WARNING: Unable to download XML: HTTP Error 504: Gateway Time-out
[11/25/18 23:19:57] WARNING: Unable to download JSON metadata: HTTP Error 403: Forbidden
[11/25/18 23:19:57] ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[11/25/18 23:19:57] Traceback (most recent call last):
[11/25/18 23:19:57]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6bh3thhm\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
[11/25/18 23:19:57]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6bh3thhm\build\youtube_dl\extractor\common.py", line 508, in extract
[11/25/18 23:19:57]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6bh3thhm\build\youtube_dl\extractor\itv.py", line 260, in _real_extract
[11/25/18 23:19:57]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6bh3thhm\build\youtube_dl\extractor\common.py", line 1292, in _sort_formats
[11/25/18 23:19:57] youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[11/25/18 23:19:57] 
[11/25/18 23:20:22] [debug] System config: []
[11/25/18 23:20:22] [debug] User config: []
[11/25/18 23:20:22] [debug] Custom config: []
[11/25/18 23:20:22] [debug] Command-line args: ['--newline', '-i', '-o', 'D:\\_Videos\\_New_Downloads\\%(title)s.%(ext)s', '--ignore-config', '--hls-prefer-native', '-v', 'https://www.itv.com/hub/midsomer-murders/1a7317a0012']
[11/25/18 23:20:22] [debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[11/25/18 23:20:22] [debug] youtube-dl version 2018.11.23
[11/25/18 23:20:22] [debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[11/25/18 23:20:22] [debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2, rtmpdump 2.4
[11/25/18 23:20:22] [debug] Proxy map: {}
[11/25/18 23:20:22] WARNING: Unable to download XML: HTTP Error 504: Gateway Time-out
[11/25/18 23:20:22] WARNING: Unable to download JSON metadata: HTTP Error 403: Forbidden
[11/25/18 23:20:22] ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[11/25/18 23:20:22] Traceback (most recent call last):
[11/25/18 23:20:22]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6bh3thhm\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
[11/25/18 23:20:22]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6bh3thhm\build\youtube_dl\extractor\common.py", line 508, in extract
[11/25/18 23:20:22]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6bh3thhm\build\youtube_dl\extractor\itv.py", line 260, in _real_extract
[11/25/18 23:20:22]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6bh3thhm\build\youtube_dl\extractor\common.py", line 1292, in _sort_formats
[11/25/18 23:20:22] youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[11/25/18 23:20:22] 
...
<end of log>
```

---

### Description of your *issue*, suggested solution and other information

The problem of gateway timeouts and no video formats being founds appears to be happening on all UTV Hub links, and this has been the case for almost a week. I've tried multiple VPN servers and using my login credentials, but nothing works.

Other UK-based links appear unaffected, including the BBC.

Following are a few example URLs, but I can provide many more if required ...

https://www.itv.com/hub/the-americans/2a2471a0061
https://www.itv.com/hub/teen-titans-go/2a3033a0115
https://www.itv.com/hub/midsomer-murders/1a7317a0012

**Comment by dstftw** [comment]
It's geo restricted.
```
PS C:\Dev\youtube-dl\master> py -3.7 .\youtube_dl\__main__.py https://www.itv.com/hub/teen-titans-go/2a3033a0115 --proxy <snip>
[ITV] 2a3033a0115: Downloading webpage
[ITV] 2a3033a0115: Downloading XML
WARNING: Unable to download XML: HTTP Error 504: Gateway Time-out
[ITV] 2a3033a0115: Downloading JSON metadata
[ITV] 2a3033a0115: Downloading m3u8 information
[hlsnative] Downloading m3u8 manifest
WARNING: hlsnative has detected features it does not support, extraction will be delegated to ffmpeg
[download] Destination: Chapter 1 - NBTS Special-2a3033a0115.mp4
ffmpeg version N-85653-gb4330a0 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 6.3.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-cuda --enable-cuvid --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-nvenc --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-zlib
  libavutil      55. 61.100 / 55. 61.100
  libavcodec     57. 93.100 / 57. 93.100
  libavformat    57. 72.101 / 57. 72.101
  libavdevice    57.  7.100 / 57.  7.100
  libavfilter     6. 87.100 /  6. 87.100
  libswscale      4.  7.101 /  4.  7.101
  libswresample   2.  8.100 /  2.  8.100
  libpostproc    54.  6.100 / 54.  6.100
...
```

**Comment by OwenMelbz** [comment]
@dstftw is this deffo working still? I've tried on https://www.itv.com/hub/strangers/2a5287a0003 and getting similar errors

**Comment by dstftw** [comment]
```
PS C:\Dev\youtube-dl\master> py -3.6 .\youtube_dl\__main__.py https://www.itv.com/hub/strangers/2a5287a0003 --proxy ...
[ITV] 2a5287a0003: Downloading webpage
[ITV] 2a5287a0003: Downloading XML
WARNING: Unable to download XML: HTTP Error 504: Gateway Time-out
[ITV] 2a5287a0003: Downloading JSON metadata
[ITV] 2a5287a0003: Downloading m3u8 information
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 227
[download] Destination: Series 1 - Episode 3-2a5287a0003.mp4
[download]   0.1% of ~563.32MiB at 212.45KiB/s ETA 01:23:11
ERROR: Interrupted by user
```

**Comment by OwenMelbz** [comment]
Hmm odd, I'm on OSX and in UK so shouldn't be any problem, will try again tomoz see if it decides to work!

**Comment by dstftw** [comment]
Can you play it in browser in the first place?

**Comment by OwenMelbz** [comment]
Yeah and on ITV hub Samsung tv - was just getting fed up of adverts every 20 seconds so thought would download and chuck on Plex instead
