### ISSUE TITLE
ValueError: Invalid IPv6 URL

### ISSUE THREAD

**Issue by iTeddy-w** [rg3/youtube-dl#18309]
I'm using latest version and have the following issue to download youtube video.My PC browser Chrome can open the url (https://youtu.be/pZw9veQ76fo?list=RDpZw9veQ76fo)  and watch the video using the shadowsocks 4.1.2。

$ C:\Users\CRI>youtube-dl -F [https://youtu.be/pZw9veQ76fo?list=RDpZw9veQ76fo]
WARNING: The url doesn't specify the protocol, trying with http
Traceback (most recent call last):
  File "c:\users\cri\appdata\local\programs\python\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\cri\appdata\local\programs\python\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\CRI\AppData\Local\Programs\Python\Python37-32\Scripts\youtube-dl.exe\__main__.py", line 9, in <module>
  File "c:\users\cri\appdata\local\programs\python\python37-32\lib\site-packages\youtube_dl\__init__.py", line 472, in main
    _real_main(argv)
  File "c:\users\cri\appdata\local\programs\python\python37-32\lib\site-packages\youtube_dl\__init__.py", line 462, in _real_main
    retcode = ydl.download(all_urls)
  File "c:\users\cri\appdata\local\programs\python\python37-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 2001, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "c:\users\cri\appdata\local\programs\python\python37-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 803, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "c:\users\cri\appdata\local\programs\python\python37-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 864, in process_ie_result
    extra_info=extra_info)
  File "c:\users\cri\appdata\local\programs\python\python37-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "c:\users\cri\appdata\local\programs\python\python37-32\lib\site-packages\youtube_dl\extractor\common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "c:\users\cri\appdata\local\programs\python\python37-32\lib\site-packages\youtube_dl\extractor\generic.py", line 2204, in _real_extract
    parsed_url = compat_urlparse.urlparse(url)
  File "c:\users\cri\appdata\local\programs\python\python37-32\lib\urllib\parse.py", line 368, in urlparse
    splitresult = urlsplit(url, scheme, allow_fragments)
  File "c:\users\cri\appdata\local\programs\python\python37-32\lib\urllib\parse.py", line 417, in urlsplit
    raise ValueError("Invalid IPv6 URL")
ValueError: Invalid IPv6 URL
$

But i can download the youku video using youtube-dl without the shadowsocks。
how to resolve ValueError: Invalid IPv6 URL issue ?

**Comment by dstftw** [comment]
There should not be any braces around the URL.
