### ISSUE TITLE
Universal Kids

### ISSUE THREAD

**Issue by jsbain** [rg3/youtube-dl#18348]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.11.23*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.11.23**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.universalkids.com/shows/american-ninja-warrior-junior/season/1/videos/junior-qualifier-8

---

### Description of your *issue*, suggested solution and other information

I'm trying to add a universalkids extractor. This seems to be very similar to nbc, usanetworks, etc, which use ThePlatform/adobepass.  
However, I can't seem to find good documentation on what I need to provide in _real_extract in those cases.  I gather I'm supposed to perhaps set ie_key='ThePlatform', and perhaps use _extract_mvpd_auth and smuggle in the resulting auth into url?   
I'm willing to give it a go, but am having trouble untangling the examples.

**Comment by jsbain** [comment]
Okay, trying to use theplatform on one of these links directly gives me this:
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--ap-mso', u'TWC', u'--ap-username', u'PRIVATE', u'--ap-password', u'PRIVATE', u'https://player.theplatform.com/p/HNK2IC/z1qGG6CScEDH/select/media/guid/2702430253/3809336#__youtubedl_smuggle=%7B%22force_smil_url%22%3A+true%7D']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.11.23
[debug] Python version 2.7.13 (CPython) - Windows-10-10.0.17134
[debug] exe versions: none
[debug] Proxy map: {}
[ThePlatform] 3809336: Downloading SMIL data
ERROR: 3809336: Failed to parse XML  (caused by ParseError(ExpatError('not well-formed (invalid token): line 7, column 54',),)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\youtube_dl-2018.11.23-py2.7.egg\youtube_dl\extractor\common.py", line 827, in _parse_xml
    return compat_etree_fromstring(xml_string.encode('utf-8'))
  File "C:\Python27\lib\site-packages\youtube_dl-2018.11.23-py2.7.egg\youtube_dl\compat.py", line 2542, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "C:\Python27\lib\site-packages\youtube_dl-2018.11.23-py2.7.egg\youtube_dl\compat.py", line 2531, in _XML
    parser.feed(text)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 7, column 54
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\youtube_dl-2018.11.23-py2.7.egg\youtube_dl\YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "C:\Python27\lib\site-packages\youtube_dl-2018.11.23-py2.7.egg\youtube_dl\extractor\common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "C:\Python27\lib\site-packages\youtube_dl-2018.11.23-py2.7.egg\youtube_dl\extractor\theplatform.py", line 305, in _real_extract
    formats, subtitles = self._extract_theplatform_smil(smil_url, video_id)
  File "C:\Python27\lib\site-packages\youtube_dl-2018.11.23-py2.7.egg\youtube_dl\extractor\theplatform.py", line 40, in _extract_theplatform_smil
    headers=self.geo_verification_headers())
  File "C:\Python27\lib\site-packages\youtube_dl-2018.11.23-py2.7.egg\youtube_dl\extractor\common.py", line 820, in _download_xml
    expected_status=expected_status)
  File "C:\Python27\lib\site-packages\youtube_dl-2018.11.23-py2.7.egg\youtube_dl\extractor\common.py", line 804, in _download_xml_handle
    fatal=fatal), urlh
  File "C:\Python27\lib\site-packages\youtube_dl-2018.11.23-py2.7.egg\youtube_dl\extractor\common.py", line 831, in _parse_xml
    raise ExtractorError(errmsg, cause=ve)
ExtractorError: 3809336: Failed to parse XML  (caused by ParseError(ExpatError('not well-formed (invalid token): line 7, column 54',),)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
I used -dump-pages to look at the offending xml line, which is 
```
	<link rel="alternate" href="urn:none?form=rss&linkUrl=https%3A%2F%2Fplayer.theplatform.com%2Fp%2FHNK2IC%2Fz1qGG6CScEDH%2Fselect%2Fmedia%2F%7BmediaPid%7D" type="application/rss+xml" />
```

column 54 is the equal sign after linkUrl.

**Comment by 89z** [comment]
Issue should be closed, URL is dead
