### ISSUE TITLE
Deutschlandfunk SSL handshake problem

### ISSUE THREAD

**Issue by lightonflux** [rg3/youtube-dl#18376]
### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)

``` 
youtube-dl -v https://www.deutschlandfunk.de/vererbte-wunden-wie-traumata-ueber-generationen-weiterwirken.1176.de.html\?dram:article_id\=427296
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--add-metadata', u'-c', u'--format=bestvideo[height<=?1080][ext!=webm]+bestaudio/best', u'-v', u'https://www.deutschlandfunk.de/vererbte-wunden-wie-traumata-ueber-generationen-weiterwirken.1176.de.html?dram:article_id=427296']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.12.03
[debug] Python version 2.7.15+ (CPython) - Linux-4.18.0-2-amd64-x86_64-with-debian-buster-sid
[debug] exe versions: ffmpeg 4.0.3-1, ffprobe 4.0.3-1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] vererbte-wunden-wie-traumata-ueber-generationen-weiterwirken.1176.de: Requesting header
WARNING: Falling back on generic information extractor.
[generic] vererbte-wunden-wie-traumata-ueber-generationen-weiterwirken.1176.de: Downloading webpage
[generic] vererbte-wunden-wie-traumata-ueber-generationen-weiterwirken.1176.de: Extracting information
[generic] vererbte-wunden-wie-traumata-ueber-generationen-weiterwirken.2595.de: Requesting header
WARNING: Could not send HEAD request to https://srv.deutschlandradio.de/vererbte-wunden-wie-traumata-ueber-generationen-weiterwirken.2595.de.twc?dram:article_id=427296: <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:727)>
[generic] vererbte-wunden-wie-traumata-ueber-generationen-weiterwirken.2595.de: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:727)> (caused by URLError(SSLError(1, u'[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:727)'),))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 605, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 2211, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/utils.py", line 1139, in https_open
    req, **kwargs)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)

```

### Description of your *issue*, suggested solution and other information

Deutschlandfunk link does not work because of SSL error.

### Technical Details

Installed via pip on Debian Buster.

**Comment by evexoio** [comment]
I just ran the same command and I didn't get the SSL error

P.S: Same version of youtube-dl

```
$ youtube-dl -v https://www.deutschlandfunk.de/vererbte-wunden-wie-traumata-ueber-generationen-weiterwirken.1176.de.html\?dram:article_id\=427296
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.deutschlandfunk.de/vererbte-wunden-wie-traumata-ueber-generationen-weiterwirken.1176.de.html?dram:article_id=427296']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.12.03
[debug] Python version 3.6.3 (CPython) - Darwin-17.7.0-x86_64-i386-64bit
[debug] exe versions: avconv 12, avprobe 12, ffmpeg present, ffprobe present, phantomjs 2.1.1
[debug] Proxy map: {}
[generic] vererbte-wunden-wie-traumata-ueber-generationen-weiterwirken.1176.de: Requesting header
WARNING: Falling back on generic information extractor.
[generic] vererbte-wunden-wie-traumata-ueber-generationen-weiterwirken.1176.de: Downloading webpage
[generic] vererbte-wunden-wie-traumata-ueber-generationen-weiterwirken.1176.de: Extracting information
[generic] vererbte-wunden-wie-traumata-ueber-generationen-weiterwirken.2595.de: Requesting header
WARNING: Falling back on generic information extractor.
[generic] vererbte-wunden-wie-traumata-ueber-generationen-weiterwirken.2595.de: Downloading webpage
[generic] vererbte-wunden-wie-traumata-ueber-generationen-weiterwirken.2595.de: Extracting information
ERROR: Unsupported URL: https://srv.deutschlandradio.de/vererbte-wunden-wie-traumata-ueber-generationen-weiterwirken.2595.de.twc?dram:article_id=427296
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3318, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://srv.deutschlandradio.de/vererbte-wunden-wie-traumata-ueber-generationen-weiterwirken.2595.de.twc?dram:article_id=427296
```

Should be something with PyOpenSSL, you can install it like this

```
easy_install pyOpenSSL
```
