### ISSUE TITLE
Failed to download from youtube

### ISSUE THREAD

**Issue by mikedesu** [rg3/youtube-dl#18373]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.12.03*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.12.03**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--no-check-certificate', '--add-metadata', '-ic', '-x', '--audio-format', 'mp3', '--verbose', 'https://www.youtube.com/watch?v=_7QoPhEA-s8']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.09.18
[debug] Python version 3.6.4 (CPython) - Darwin-18.2.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.0, ffprobe 4.0
[debug] Proxy map: {}
[youtube] _7QoPhEA-s8: Downloading webpage
[youtube] _7QoPhEA-s8: Downloading video info webpage
[youtube] {18} signature length 46.40, html5 player vflBGiA6J
[youtube] _7QoPhEA-s8: Downloading player https://www.youtube.com/yts/jsbin/player-vflBGiA6J/en_US/base.js
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1216, in _decrypt_signature
    video_id, player_url, s
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1125, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1188, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 977, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract \x1b[0;34mInitial JS player signature function name\x1b[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1216, in _decrypt_signature
    video_id, player_url, s
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1125, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1188, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 977, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1216, in _decrypt_signature
    video_id, player_url, s
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1125, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1188, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 977, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 507, in extract
    ie_result = self._real_extract(url)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1809, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1226, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1216, in _decrypt_signature
    video_id, player_url, s
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1125, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1188, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 977, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract \x1b[0;34mInitial JS player signature function name\x1b[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Tried downloading from youtube, failed.

**Comment by goggle** [comment]
You are using an outdated version (2018.09.18) of youtube-dl!
