### ISSUE TITLE
Failed to download playlist from youtube

### ISSUE THREAD

**Issue by itsyourboychipsahoy** [rg3/youtube-dl#18400]
# Youtube-dl verbose output
```
$ youtube-dl https://www.youtube.com/playlist\?list\=PL64wiCrrxh4Jisi7OcCJIUpguV_f5jGnZ -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.youtube.com/playlist?list=PL64wiCrrxh4Jisi7OcCJIUpguV_f5jGnZ', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.12.03
[debug] Python version 2.7.15rc1 (CPython) - Linux-4.15.0-39-generic-x86_64-with-LinuxMint-19-tara
[debug] exe versions: ffmpeg 3.4.4-0ubuntu0.18.04.1, ffprobe 3.4.4-0ubuntu0.18.04.1
[debug] Proxy map: {}
[youtube:playlist] PL64wiCrrxh4Jisi7OcCJIUpguV_f5jGnZ: Downloading webpage
[download] Downloading playlist: Just For Func
[youtube:playlist] playlist Just For Func: Downloading 44 videos
[download] Downloading video 1 of 44
[youtube] H_4eRD8aegk: Downloading webpage
[youtube] H_4eRD8aegk: Downloading video info webpage
ERROR: This video is unavailable.
Traceback (most recent call last):
  File "/home/mint/.local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/home/mint/.local/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/home/mint/.local/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 1920, in _real_extract
    raise ExtractorError(error_message, expected=True)
ExtractorError: This video is unavailable.
<end of log>
```

### Description of your *issue*, suggested solution and other information
I tried to download a playlist from youtube and got this error
i think it might be because there is an active premiere right now, i'll try again later once its gone and report here :-)

**Comment by dstftw** [comment]
First video is not yet available as clearly stated in the error message.

**Comment by itsyourboychipsahoy** [comment]
@dstftw ah i see because the playlist is ordered in the wrong order, and the premiere is the "newest video" i tried downloading with this command `https://www.youtube.com/watch?v=aeF3l-zmPsY&index=3&list=PL64wiCrrxh4Jisi7OcCJIUpguV_f5jGnZ` and it still tried to download from the first video. am i doing something wrong?

**Comment by kylebebak** [comment]
Check out the **-i, --ignore-errors** options:

>Continue on download errors, for example to skip unavailable videos in a playlist
