### ISSUE TITLE
Canvas.py extractor not working

### ISSUE THREAD

**Issue by xplorr** [rg3/youtube-dl#18415]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.12.03**
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser
- [x] Bug report (encountered problems with youtube-dl)
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-f', 'best', '-u', 'PRIVATE', '-p', 'PRIVATE', 'https://www.vrt.be/vrtnu/a-z/de-ideale-wereld/2018-nj/de-ideale-wereld-d20181204/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.12.03
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg 3.4, ffprobe 3.4, rtmpdump 2.4
[debug] Proxy map: {}
[VrtNU] Logging in
[VrtNU] Requesting a token
[VrtNU] de-ideale-wereld-d20181204: Downloading webpage
[VrtNU] de-ideale-wereld-d20181204: Downloading JSON metadata
[Canvas] pbs-pub-a9c6f774-ea0c-4161-b479-f067cf65ab1b$vid-bac286cb-8574-4f84-b557-978c91db3f43: Downloading JSON metadata
[Canvas] pbs-pub-a9c6f774-ea0c-4161-b479-f067cf65ab1b$vid-bac286cb-8574-4f84-b557-978c91db3f43: Downloading m3u8 information
WARNING: Failed to download m3u8 information: <urlopen error [Errno 11001] getaddrinfo failed>
[Canvas] pbs-pub-a9c6f774-ea0c-4161-b479-f067cf65ab1b$vid-bac286cb-8574-4f84-b557-978c91db3f43: Downloading MPD manifest
WARNING: Failed to download MPD manifest: <urlopen error [Errno 11001] getaddrinfo failed>
[Canvas] pbs-pub-a9c6f774-ea0c-4161-b479-f067cf65ab1b$vid-bac286cb-8574-4f84-b557-978c91db3f43: Downloading ISM manifest
WARNING: Failed to download ISM manifest: <urlopen error [Errno 11001] getaddrinfo failed>
[Canvas] pbs-pub-a9c6f774-ea0c-4161-b479-f067cf65ab1b$vid-bac286cb-8574-4f84-b557-978c91db3f43: Downloading f4m manifest
WARNING: Unable to download f4m manifest: <urlopen error [Errno 11001] getaddrinfo failed>
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpflqtkr62\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpflqtkr62\build\youtube_dl\extractor\common.py", line 508, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpflqtkr62\build\youtube_dl\extractor\canvas.py", line 73, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpflqtkr62\build\youtube_dl\extractor\common.py", line 1292, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by dstftw** [comment]
Stop posting duplicates.

**Comment by xplorr** [comment]
duplicate of what?

**Comment by michaelarnauts** [comment]
@xplorr duplicate of https://github.com/rg3/youtube-dl/issues/17701
