### ISSUE TITLE
Does Clipfish work?

### ISSUE THREAD

**Issue by xubuntu4iran** [rg3/youtube-dl#1842]
youtube-dl  -v http://www.clipfish.de/special/game-trailer/video/3966754/fifa-14-e3-2013-trailer/
[debug] System config: []
[debug] User config: ['--proxy', 'http://127.0.0.1:8580']
[debug] Command-line args: ['-v', 'http://www.clipfish.de/special/game-trailer/video/3966754/fifa-14-e3-2013-trailer/']
[debug] youtube-dl version 2013.11.26
[debug] Python version 2.7.5+ - Linux-3.9.6-i686-with-debian-7.0
[debug] Proxy map: {'http': 'http://127.0.0.1:8580', 'https': 'http://127.0.0.1:8580'}
[clipfish] 3966754: Downloading info page
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 18, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 694, in main
    
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 684, in _real_main
    
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 805, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 443, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 468, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 585, in process_video_result
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 769, in determine_ext
AttributeError: 'NoneType' object has no attribute 'partition'

**Comment by dstftw** [comment]
This issue has been fixed and will be available in the next version. Thanks for the report.
