### ISSUE TITLE
Error downloading recent VEVO video

### ISSUE THREAD

**Issue by Mabuse89** [rg3/youtube-dl#1843]
Error downloading a recent VEVO video. Other VEVO videos (tested) downloaded well.

Command:
D:\youtubedl>youtube-dl.exe --verbose http://www.vevo.com/watch/sky-ferreira/night-time-my-time/USUV71302652

[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.vevo.com/watch/sky-ferreira/night-time-my-time/USUV71302652']
[debug] youtube-dl version 2013.11.26
[debug] Python version 2.7.5 - Windows-XP-5.1.2600-SP3
[debug] Proxy map: {}
[Vevo] USUV71302652: Downloading json info
Traceback (most recent call last):
  File "__main__.py", line 18, in <module>
  File "youtube_dl\__init__.pyo", line 694, in main
  File "youtube_dl\__init__.pyo", line 684, in _real_main
  File "youtube_dl\YoutubeDL.pyo", line 805, in download
  File "youtube_dl\YoutubeDL.pyo", line 428, in extract_info
  File "youtube_dl\extractor\common.pyo", line 131, in extract
  File "youtube_dl\extractor\vevo.pyo", line 102, in _real_extract
  File "youtube_dl\extractor\vevo.pyo", line 36, in _formats_from_json
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by yan12125** [comment]
From the error message it's because videos without ```video_info``` field are not handled correctly. I guess it's the same situation as #7802, and should be fixed in ff51983e1563db08734e43a07d5671a517f99ef6. Note that the fix will not be included until the next version. If there are still problems in the next version for Vevo videos, feel free to open new issues.
