### ISSUE TITLE
Thumbnail images have different names than expected when unusual characters are used

### ISSUE THREAD

**Issue by yesiateyoursheep** [rg3/youtube-dl#18450]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.12.03**
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--ffmpeg-location', 'C:\\Portable\\', '-f', 'bestaudio', '-x', '--audio-format', 'mp3', '--embed-thumbnail', '--ignore-errors', 'https://www.youtube.com/watch?v=uf6HiKQSDEI']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.12.03
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg N-71883-geb9fb50, ffprobe N-71883-geb9fb50
[debug] Proxy map: {}
[youtube] uf6HiKQSDEI: Downloading webpage
[youtube] uf6HiKQSDEI: Downloading video info webpage
[youtube] uf6HiKQSDEI: Downloading thumbnail ...
[youtube] uf6HiKQSDEI: Writing thumbnail to: Crywolf - C E P H A L Ø T U S (Official Visual)-uf6HiKQSDEI.jpg
[debug] Invoking downloader on 'https://r2---sn-ug0nu2vfxg-53al.googlevideo.com/videoplayback?signature=010A5DA9AC638D5A2C863E9CEFBDCE0D16F767B8.5BA459575276CAA4826A3F7F1769AE5C5D7E352B&fvip=2&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Crequiressl%2Csource%2Cexpire&ei=4F4LXIqeMILlqQGp0oDYCA&itag=251&key=yt6&txp=5411222&mime=audio%2Fwebm&pcm2cms=yes&source=youtube&pl=22&keepalive=yes&requiressl=yes&gir=yes&lmt=1544207445049809&ipbits=0&mm=31%2C29&mn=sn-ug0nu2vfxg-53al%2Csn-8vq54voxo1-53a6&c=WEB&id=o-AO-VsNGSKvBykEm6bnfMFeN5Fu0bwgb4ykWZKB6XWCfW&initcwndbps=1203750&ip=115.69.180.130&clen=3861295&mt=1544248944&mv=m&dur=209.941&expire=1544270656&ms=au%2Crdu&ratebypass=yes'
[download] Crywolf - C E P H A L Ø T U S (Official Visual)-uf6HiKQSDEI.webm has already been downloaded
[download] 100% of 3.68MiB
[debug] ffmpeg command line: "C:\Portable\ffprobe" -show_streams "file:Crywolf - C E P H A L Ø T U S (Official Visual)-uf6HiKQSDEI.webm"
[ffmpeg] Destination: Crywolf - C E P H A L Ø T U S (Official Visual)-uf6HiKQSDEI.mp3
[debug] ffmpeg command line: "C:\Portable\ffmpeg" -y -i "file:Crywolf - C E P H A L Ø T U S (Official Visual)-uf6HiKQSDEI.webm" -vn -acodec libmp3lame "-q:a" 5 "file:Crywolf - C E P H A L Ø T U S (Official Visual)-uf6HiKQSDEI.mp3"
Deleting original file Crywolf - C E P H A L Ø T U S (Official Visual)-uf6HiKQSDEI.webm (pass -k to keep)
[ffmpeg] Adding thumbnail to "Crywolf - C E P H A L Ø T U S (Official Visual)-uf6HiKQSDEI.mp3"
[debug] ffmpeg command line: "C:\Portable\ffmpeg" -y -i "file:Crywolf - C E P H A L Ø T U S (Official Visual)-uf6HiKQSDEI.mp3" -i "file:Crywolf - C E P H A L Ø T U S (Official Visual)-uf6HiKQSDEI.jpg" -c copy -map 0 -map 1 "-metadata:s:v" "title=\"Album cover\"" "-metadata:s:v" "comment=\"Cover (Front)\"" "file:Crywolf - C E P H A L Ø T U S (Official Visual)-uf6HiKQSDEI.temp.mp3"
ERROR: file:Crywolf - C E P H A L Ø T U S (Official Visual)-uf6HiKQSDEI.jpg: No such file or directory
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpflqtkr62\build\youtube_dl\YoutubeDL.py", line 2047, in post_process
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpflqtkr62\build\youtube_dl\postprocessor\embedthumbnail.py", line 51, in run
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpflqtkr62\build\youtube_dl\postprocessor\ffmpeg.py", line 204, in run_ffmpeg_multiple_files
youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError: file:Crywolf - C E P H A L Ø T U S (Official Visual)-uf6HiKQSDEI.jpg: No such file or directory
```

---

### Description of your *issue*, suggested solution and other information

The issue is related to unusual characters, as this script works perfectly fine with anything that doesn't have unusual characters. In this case the file had the same name on the disk, including the unusual character (though that isn't always the case) and it seems to be unable to find it when it comes to embedding and deleting the image later.

**Comment by dstftw** [comment]
Outdated ffmpeg.

**Comment by yesiateyoursheep** [comment]
Wouldn't be a good idea to leave a helpful error message and delete the image anyway in that case?
