### ISSUE TITLE
NOT TEACHABLE / Unsupported URL in atresplayer

### ISSUE THREAD

**Issue by eliblanco87** [rg3/youtube-dl#18486]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.12.09*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.12.09**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---
```
youtube-dl -v 'https://www.atresplayer.com/lasexta/programas/salvados/temporada-14/vox-al-natural_5c0d0cd67ed1a82e4d4656be/'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.atresplayer.com/lasexta/programas/salvados/temporada-14/vox-al-natural_5c0d0cd67ed1a82e4d4656be/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.12.09
[debug] Python version 2.7.13 (CPython) - Linux-4.9.0-8-amd64-x86_64-with-debian-9.5
[debug] exe versions: ffmpeg 3.2.12-1, ffprobe 3.2.12-1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] vox-al-natural_5c0d0cd67ed1a82e4d4656be: Requesting header
WARNING: Falling back on generic information extractor.
[generic] vox-al-natural_5c0d0cd67ed1a82e4d4656be: Downloading webpage
[generic] vox-al-natural_5c0d0cd67ed1a82e4d4656be: Extracting information
NOT TEACHABLE
ERROR: Unsupported URL: https://www.atresplayer.com/lasexta/programas/salvados/temporada-14/vox-al-natural_5c0d0cd67ed1a82e4d4656be/
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2340, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2542, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2531, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 86, column 3375
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 793, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3323, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.atresplayer.com/lasexta/programas/salvados/temporada-14/vox-al-natural_5c0d0cd67ed1a82e4d4656be/
```

**Comment by eliblanco87** [comment]
Which issue # is duplicated respect to this one?
