### ISSUE TITLE
module 'urllib.request' has no attribute 'HTTPSHandler'

### ISSUE THREAD

**Issue by ZhangKuixun** [rg3/youtube-dl#18495]
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/data/user/0/com.jventura.pyapp/assets/python/bootstrap.py", line 9, in <module>
>     import youtube_dl
>   File "/data/user/0/com.jventura.pyapp/assets/python/youtube_dl/__init__.py", line 15, in <module>
>     from .options import (
>   File "/data/user/0/com.jventura.pyapp/assets/python/youtube_dl/options.py", line 8, in <module>
>     from .downloader.external import list_external_downloaders
>   File "/data/user/0/com.jventura.pyapp/assets/python/youtube_dl/downloader/__init__.py", line 3, in <module>
>     from .common import FileDownloader
>   File "/data/user/0/com.jventura.pyapp/assets/python/youtube_dl/downloader/common.py", line 10, in <module>
>     from ..utils import (
>   File "/data/user/0/com.jventura.pyapp/assets/python/youtube_dl/utils.py", line 1117, in <module>
>     class YoutubeDLHTTPSHandler(compat_urllib_request.HTTPSHandler):
> AttributeError: module 'urllib.request' has no attribute 'HTTPSHandler'

I use android call C, C call python agin. put it in assets.

**Comment by ZhangKuixun** [comment]
@dstftw
