### ISSUE TITLE
ffmpeg "Correcting container" called on already downloaded m4a files

### ISSUE THREAD

**Issue by durai23** [rg3/youtube-dl#18505]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.12.09*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2018.12.09**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [ x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
PS C:\cygwin64\home\axon\scripts_youtube_dl> python .\home_playlist.py --url "https://www.youtube.com/playlist?list=PLUoFIzNiYRRsA2CTRYhTHKnlcFeGyTcuQ"
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.12.09
[debug] Python version 2.7.11 (CPython) - Windows-8.1-6.3.9600
[debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2
[debug] Proxy map: {}
[youtube:playlist] PLUoFIzNiYRRsA2CTRYhTHKnlcFeGyTcuQ: Downloading webpage
[download] Downloading playlist: Deniro
[youtube:playlist] playlist Deniro: Downloading 31 videos
[download] Downloading video 1 of 31
[youtube] yTOGheewG1E: Downloading webpage
[youtube] yTOGheewG1E: Downloading embed webpage
[youtube] yTOGheewG1E: Refetching age-gated info webpage
ERROR: Watch this video on YouTube. Playback on other websites has been disabled by the video owner.
Traceback (most recent call last):
  File "C:\Users\axon\Anaconda\lib\site-packages\youtube_dl\YoutubeDL.py", line 793, in extract_info
    ie_result = ie.extract(url)
  File "C:\Users\axon\Anaconda\lib\site-packages\youtube_dl\extractor\common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\axon\Anaconda\lib\site-packages\youtube_dl\extractor\youtube.py", line 1920, in _real_extract
    raise ExtractorError(error_message, expected=True)
ExtractorError: Watch this video on YouTube. Playback on other websites has been disabled by the video owner.

[download] Downloading video 2 of 31
[youtube] aZSzMIFZT7Q: Downloading webpage
[youtube] aZSzMIFZT7Q: Downloading video info webpage
Dirty Grandpa Official Trailer #1 (2016) - Zac Efron, Robert De Niro Comedy HD
[debug] Invoking downloader on u'https://r5---sn-4g5edn7s.googlevideo.com/videoplayback?key=yt6&lmt=1540962307151528&dur=116.657&source=youtube&beids=9466585&sparams=clen
%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&clen=1853456&expire=1544644030&
pl=16&mime=audio%2Fmp4&txp=5432432&ei=XhERXM7QMY-K1wL7gZewCw&ipbits=0&itag=140&ms=au%2Conr&initcwndbps=1695000&mv=m&mt=1544622287&mn=sn-4g5edn7s%2Csn-i5h7lner&mm=31%2C26&
keepalive=yes&id=o-ABdlEICnZR1dJGr73vUrUy7vntnXZu3LNn0zMiKovhtq&c=WEB&signature=C4A19D960D7393C9A11387DB7AADFBE4C0483DA3.295FDE4FE3E50FECB3A8D64A3C11CE7BC00A310D&gir=yes&
requiressl=yes&ip=143.49.3.100&fvip=5&ratebypass=yes'
[download] M:\yt2018\aZSzMIFZT7Q_Dirty Grandpa Official Trailer #1 (2016) - Zac Efron, Robert De Niro Comedy HD_PLUoFIzNiYRRsA2CTRYhTHKnlcFeGyTcuQ_Deniro_20151029_NA_128_
140.m4a has already been downloaded
[download] 100% of 1.77MiB
**[ffmpeg] Correcting container in "M:\yt2018\aZSzMIFZT7Q_Dirty Grandpa Official Trailer #1 (2016) - Zac Efron, Robert De Niro Comedy HD_PLUoFIzNiYRRsA2CTRYhTHKnlcFeGyTcuQ_
Deniro_20151029_NA_128_140.m4a"
[debug] ffmpeg command line: ffmpeg -y -i "file:M:\yt2018\aZSzMIFZT7Q_Dirty Grandpa Official Trailer #1 (2016) - Zac Efron, Robert De Niro Comedy HD_PLUoFIzNiYRRsA2CTRYhT
HKnlcFeGyTcuQ_Deniro_20151029_NA_128_140.m4a" -c copy -f mp4 "file:M:\yt2018\aZSzMIFZT7Q_Dirty Grandpa Official Trailer #1 (2016) - Zac Efron, Robert De Niro Comedy HD_PL
UoFIzNiYRRsA2CTRYhTHKnlcFeGyTcuQ_Deniro_20151029_NA_128_140.temp.m4a"**
[download] Downloading video 3 of 31
[youtube] mfT-UZCA6Tg: Downloading webpage
[youtube] mfT-UZCA6Tg: Downloading video info webpage
Robert De Niro Impressed By Tom Hiddleston's Robert De Niro Impression - The Graham Norton Show
[debug] Invoking downloader on u'https://r1---sn-4g5ednek.googlevideo.com/videoplayback?mm=31%2C29&mn=sn-4g5ednek%2Csn-4g5e6nz7&keepalive=yes&sparams=clen%2Cdur%2Cei%2Cgi
r%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&initcwndbps=1695000&ei=YRERXIu9MMaA7gO3zI3QAQ&i
tag=171&ms=au%2Crdu&mt=1544622287&txp=5511222&mv=m&mime=audio%2Fwebm&lmt=1540493264228435&pl=16&clen=5174336&expire=1544644033&beids=9466585&key=yt6&ip=143.49.3.100&sourc
e=youtube&dur=371.677&gir=yes&signature=A73E689167B7EB5AE0E2F6AA95E490F88C0E85ED.26E94FDF809239820DA6F32AFEA9D9CBEA029770&ipbits=0&requiressl=yes&fvip=1&id=o-ANFHOKDkyJCQ
tR0s0FqSIQiTdHiyrVfzdFVPzsJI7iZP&c=WEB&ratebypass=yes'
[download] M:\yt2018\mfT-UZCA6Tg_Robert De Niro Impressed By Tom Hiddleston's Robert De Niro Impression - The Graham Norton Show_PLUoFIzNiYRRsA2CTRYhTHKnlcFeGyTcuQ_Deniro
_20151002_NA_128_171.webm has already been downloaded
[download] 100% of 4.93MiB
[download] Downloading video 4 of 31
[youtube] ZU3Xban0Y6A: Downloading webpage
[youtube] ZU3Xban0Y6A: Downloading video info webpage
The Intern - Official Trailer [HD]
[debug] Invoking downloader on u'https://r2---sn-4g5e6nsz.googlevideo.com/videoplayback?sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%
2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&lmt=1516256554740768&ipbits=0&beids=9466585&requiressl=yes&source=youtube&initcwndbps=1695000&ei=YxER
XIL6C5KG-gbqwJ-ICw&keepalive=yes&mm=31%2C26&ip=143.49.3.100&mn=sn-4g5e6nsz%2Csn-i5heen7s&pl=16&itag=171&gir=yes&signature=ABF1D68BF7A5A52C6EBE250190EEB91556D47A59.7D18C06
378382527A95544DABA5D961FDA9EA003&id=o-AHKV8IcuYh4_IdBV8uAAxIOncbERTDmvr-NS7OwzH-4k&mt=1544622287&mv=m&ms=au%2Conr&key=yt6&mime=audio%2Fwebm&c=WEB&clen=2120713&dur=152.07
1&expire=1544644035&fvip=2&ratebypass=yes'
[download] M:\yt2018\ZU3Xban0Y6A_The Intern - Official Trailer [HD]_PLUoFIzNiYRRsA2CTRYhTHKnlcFeGyTcuQ_Deniro_20150513_NA_128_171.webm has already been downloaded
[download] 100% of 2.02MiB
[download] Downloading video 5 of 31
[youtube] W-DEy3mylCs: Downloading webpage
[youtube] W-DEy3mylCs: Downloading video info webpage
The Intern Official Trailer #1 (2015) - Anne Hathaway, Robert De Niro Movie HD
[debug] Invoking downloader on u'https://r2---sn-4g5edns6.googlevideo.com/videoplayback?ip=143.49.3.100&ms=au%2Crdu&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%
2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&mv=m&mt=1544622287&keepalive=yes&id=o-AB_8jCo0a12eaFwqGG2L8aecp6rDC_Df_jT
o9NpxxFpR&mn=sn-4g5edns6%2Csn-4g5e6nzl&mm=31%2C29&clen=2346515&c=WEB&initcwndbps=1695000&beids=9466585&requiressl=yes&key=yt6&mime=audio%2Fmp4&gir=yes&signature=8992DDEE6
6953100B1FDA4C983B5A5891C5702B8.7A3CB8AF15A61260941C647FF518648802C417FA&lmt=1541563901397639&dur=147.702&ipbits=0&expire=1544644036&txp=5432432&source=youtube&pl=16&fvip
=2&itag=140&ei=ZBERXPXGIIqK1gLsnKSABQ&ratebypass=yes'
[download] M:\yt2018\W-DEy3mylCs_The Intern Official Trailer #1 (2015) - Anne Hathaway, Robert De Niro Movie HD_PLUoFIzNiYRRsA2CTRYhTHKnlcFeGyTcuQ_Deniro_20150513_NA_128_
140.m4a has already been downloaded
[download] 100% of 2.24MiB
**[ffmpeg] Correcting container in "M:\yt2018\W-DEy3mylCs_The Intern Official Trailer #1 (2015) - Anne Hathaway, Robert De Niro Movie HD_PLUoFIzNiYRRsA2CTRYhTHKnlcFeGyTcuQ_
Deniro_20150513_NA_128_140.m4a"
[debug] ffmpeg command line: ffmpeg -y -i "file:M:\yt2018\W-DEy3mylCs_The Intern Official Trailer #1 (2015) - Anne Hathaway, Robert De Niro Movie HD_PLUoFIzNiYRRsA2CTRYhT
HKnlcFeGyTcuQ_Deniro_20150513_NA_128_140.m4a" -c copy -f mp4 "file:M:\yt2018\W-DEy3mylCs_The Intern Official Trailer #1 (2015) - Anne Hathaway, Robert De Niro Movie HD_PL
UoFIzNiYRRsA2CTRYhTHKnlcFeGyTcuQ_Deniro_20150513_NA_128_140.temp.m4a"**
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

**ffmpeg container called on already downloaded m4a files**

I sometimes have playlists that are processed a second time (by youtube-dl). The great thing is youtube-dl detects that the file is already present and reports in the verbose output("has already been downloaded"). This works great for video files. For audio files, unfortunately, youtube-dl invokes ffmpeg which processes the existing m4a files again (as seen in the log). This causes unnecessary use of network and disk time and is highly inefficient. Also this causes the creation time of these files, making it look like the files were created just now. This problem is only when the format is m4a (does not happen for webm files).

How to avoid this?

Thanks.

**Comment by outhud** [comment]
This issue is still present in the 2021.12.17 version.

**Comment by kikuyan** [comment]
This should be an intended behavior against m4a_dash by this commit https://github.com/ytdl-org/youtube-dl/commit/62cd676c7474f696804eda653558ada94c5953a0 .
See the linked issue reports what was the problem.
