### ISSUE TITLE
Site Support Request: olympicchannel.com

### ISSUE THREAD

**Issue by kyjb70** [rg3/youtube-dl#18522]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.12.09*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.12.09**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

```
C:\Users\Kyle>youtube-dl -v https://www.olympicchannel.com/en/video/detail/day-1-stance-isa-world-adaptive-championship-la-jolla/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.olympicchannel.com/en/video/detail/day-1-stance-isa-world-adaptive-championship-la-jolla/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.12.09
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg N-92237-g305e523105
[debug] Proxy map: {}
[generic] day-1-stance-isa-world-adaptive-championship-la-jolla: Requesting header
WARNING: Falling back on generic information extractor.
[generic] day-1-stance-isa-world-adaptive-championship-la-jolla: Downloading webpage
[generic] day-1-stance-isa-world-adaptive-championship-la-jolla: Extracting information
NOT TEACHABLE
ERROR: Unsupported URL: https://www.olympicchannel.com/en/video/detail/day-1-stance-isa-world-adaptive-championship-la-jolla/
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpg8efod20\build\youtube_dl\YoutubeDL.py", line 793, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpg8efod20\build\youtube_dl\extractor\common.py", line 508, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpg8efod20\build\youtube_dl\extractor\generic.py", line 3323, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.olympicchannel.com/en/video/detail/day-1-stance-isa-world-adaptive-championship-la-jolla/
```

---

Sample URL: https://www.olympicchannel.com/en/video/detail/day-1-stance-isa-world-adaptive-championship-la-jolla/
https://www.olympicchannel.com/en/original-series/detail/fashion-behind-the-games/fashion-behind-the-games-season-season-1/episodes/past-and-present-field-hockey/

**Comment by ealgase** [comment]
Should be doable (the website is actually really nice and easily exposes the m3u8 file).
