### ISSUE TITLE
Signature extraction failed: Traceback (most recent call last)

### ISSUE THREAD

**Issue by Gainfun** [rg3/youtube-dl#18544]
C:\Users\Walves>youtube-dl --version
2018.12.09

C:\Users\Walves>youtube-dl -F https://www.youtube.com/watch?v=dhQ5IC0NGUM
[youtube] dhQ5IC0NGUM: Downloading webpage
[youtube] dhQ5IC0NGUM: Downloading video info webpage
[youtube] dhQ5IC0NGUM: Downloading js player vfl4UMq4Z
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "e:\program files\python\lib\site-packages\youtube_dl\extractor\youtube.py", line 1225, in _decrypt_signature
    video_id, player_url, s
  File "e:\program files\python\lib\site-packages\youtube_dl\extractor\youtube.py", line 1132, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "e:\program files\python\lib\site-packages\youtube_dl\extractor\common.py", line 777, in _download_webpage
    raise e
  File "e:\program files\python\lib\site-packages\youtube_dl\extractor\common.py", line 772, in _download_webpage
    expected_status=expected_status)
  File "e:\program files\python\lib\site-packages\youtube_dl\extractor\youtube.py", line 267, in _download_webpage_handle
    *args, **compat_kwargs(kwargs))
  File "e:\program files\python\lib\site-packages\youtube_dl\extractor\common.py", line 642, in _download_webpage_handle
    content = self._webpage_read_content(urlh, url_or_request, video_id, note, errnote, fatal, encoding=encoding)
  File "e:\program files\python\lib\site-packages\youtube_dl\extractor\common.py", line 692, in _webpage_read_content
    webpage_bytes = urlh.read()
  File "e:\program files\python\lib\http\client.py", line 461, in read
    s = self._safe_read(self.length)
  File "e:\program files\python\lib\http\client.py", line 609, in _safe_read
    raise IncompleteRead(b''.join(s), amt)
http.client.IncompleteRead: IncompleteRead(524288 bytes read, 567781 more expected)
 (caused by IncompleteRead(524288 bytes read, 567781 more expected)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
Network issue on your side.
