### ISSUE TITLE
HGTV - Unsupported URL

### ISSUE THREAD

**Issue by nerdily** [rg3/youtube-dl#18548]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.12.09*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.12.09**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

It appears the URL scheme that hgtv uses for its various shows has changed. From what I can tell in hgtv.py it's expecting hgtv.com/shows/.... whereas now it's watch.hgtv.com/tv-shows/....

I have log in information available as the example video is behind the cable subscriber log in.

---

```
youtube-dl 'https://watch.hgtv.com/tv-shows/house-hunters-international/full-episodes/home-base-in-belgium' -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://watch.hgtv.com/tv-shows/house-hunters-international/full-episodes/home-base-in-belgium', u'-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.12.09
[debug] Python version 2.7.10 (CPython) - Darwin-18.2.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.2.4, ffprobe 3.2.4
[debug] Proxy map: {}
[generic] home-base-in-belgium: Requesting header
WARNING: Falling back on generic information extractor.
[generic] home-base-in-belgium: Downloading webpage
[generic] home-base-in-belgium: Extracting information
NOT TEACHABLE
ERROR: Unsupported URL: https://watch.hgtv.com/tv-shows/house-hunters-international/full-episodes/home-base-in-belgium
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2340, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2542, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2531, in _XML
    parser.feed(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 1, column 72
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 793, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3323, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://watch.hgtv.com/tv-shows/house-hunters-international/full-episodes/home-base-in-belgium
```

**Comment by nerdily** [comment]
Let me know how I can provide login details if needed

**Comment by nerdily** [comment]
Yeah realized it looks like https://github.com/rg3/youtube-dl/pull/17959 fixes it. Just trying to figure out how to test it. (New to all this)
