### ISSUE TITLE
Specific YouTube video giving extraction errors and timeout

### ISSUE THREAD

**Issue by nyuszika7h** [rg3/youtube-dl#18586]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.12.17*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.12.17**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
> youtube-dl -v --ignore-config "https://www.youtube.com/watch?v=xSGIilPdXKg"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--ignore-config', 'https://www.youtube.com/watch?v=xSGIilPdXKg']
[debug] Encodings: locale cp65001, fs utf-8, out utf-8, pref cp65001
[debug] youtube-dl version 2018.12.17
[debug] Python version 3.7.1 (CPython) - Windows-10-10.0.17763-SP0
[debug] exe versions: ffmpeg N-92202-gf72b9904fe, ffprobe N-92202-gf72b9904fe
[debug] Proxy map: {}
[youtube] xSGIilPdXKg: Downloading webpage
[youtube] xSGIilPdXKg: Downloading video info webpage
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {22} signature length 42.41, html5 player None
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {43} signature length 42.41, html5 player None
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {18} signature length 42.41, html5 player None
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {36} signature length 42.41, html5 player None
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {17} signature length 42.41, html5 player None
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {136} signature length 42.41, html5 player None
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {247} signature length 42.41, html5 player None
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {135} signature length 42.41, html5 player None
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {244} signature length 42.41, html5 player None
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {134} signature length 42.41, html5 player None
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {243} signature length 42.41, html5 player None
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {133} signature length 42.41, html5 player None
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {242} signature length 42.41, html5 player None
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {160} signature length 42.41, html5 player None
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {278} signature length 42.41, html5 player None
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {140} signature length 42.41, html5 player None
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {171} signature length 42.41, html5 player None
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {249} signature length 42.41, html5 player None
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {250} signature length 42.41, html5 player None
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {251} signature length 42.41, html5 player None
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://r6---sn-h5bt5guxax3vh-c0qk.googlevideo.com/videoplayback?fvip=3&txp=5535432&c=WEB&ei=V5waXOuoLZWLgQf6qq2gBQ&ip=84.2.121.96&pcm2cms=yes&aitags=133%2C134%2C135%2C136%2C160%2C242%2C243%2C244%2C247%2C278&itag=247&key=yt6&mime=video%2Fwebm&keepalive=yes&gir=yes&clen=341345131&expire=1545269431&ipbits=0&sparams=aitags%2Cclen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Crequiressl%2Csource%2Cexpire&initcwndbps=341250&lmt=1545217245545266&ms=au%2Crdu&mv=m&mt=1545247709&source=youtube&requiressl=yes&dur=5128.560&id=o-AF4WDaVlGuELcbut2Gc8LQuyyscztKgDWQJyoKhsBqCz&mn=sn-h5bt5guxax3vh-c0qk%2Csn-c0q7lnly&pl=19&mm=31%2C29&signature=DB5AD6AA2607FFA7805694DB68635BCBA36C05AE.77E763BE0BCCCC281070F1FCE24F01CFD37027F6&ratebypass=yes'
ERROR: unable to download video data: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
Traceback (most recent call last):
  File "c:\users\nyuszika7h\appdata\local\programs\python\python37\lib\urllib\request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "c:\users\nyuszika7h\appdata\local\programs\python\python37\lib\http\client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "c:\users\nyuszika7h\appdata\local\programs\python\python37\lib\http\client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "c:\users\nyuszika7h\appdata\local\programs\python\python37\lib\http\client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "c:\users\nyuszika7h\appdata\local\programs\python\python37\lib\http\client.py", line 1016, in _send_output
    self.send(msg)
  File "c:\users\nyuszika7h\appdata\local\programs\python\python37\lib\http\client.py", line 956, in send
    self.connect()
  File "c:\users\nyuszika7h\appdata\local\programs\python\python37\lib\http\client.py", line 1384, in connect
    super().connect()
  File "c:\users\nyuszika7h\appdata\local\programs\python\python37\lib\http\client.py", line 928, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "c:\users\nyuszika7h\appdata\local\programs\python\python37\lib\socket.py", line 727, in create_connection
    raise err
  File "c:\users\nyuszika7h\appdata\local\programs\python\python37\lib\socket.py", line 716, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\nyuszika7h\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\YoutubeDL.py", line 1903, in process_info
    partial_success = dl(fname, new_info)
  File "c:\users\nyuszika7h\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\YoutubeDL.py", line 1848, in dl
    return fd.download(name, info)
  File "c:\users\nyuszika7h\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\downloader\common.py", line 364, in download
    return self.real_download(filename, info_dict)
  File "c:\users\nyuszika7h\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\downloader\http.py", line 341, in real_download
    establish_connection()
  File "c:\users\nyuszika7h\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\downloader\http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "c:\users\nyuszika7h\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\YoutubeDL.py", line 2212, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "c:\users\nyuszika7h\appdata\local\programs\python\python37\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "c:\users\nyuszika7h\appdata\local\programs\python\python37\lib\urllib\request.py", line 543, in _open
    '_open', req)
  File "c:\users\nyuszika7h\appdata\local\programs\python\python37\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "c:\users\nyuszika7h\appdata\local\programs\python\python37\lib\site-packages\youtube_dl\utils.py", line 1140, in https_open
    req, **kwargs)
  File "c:\users\nyuszika7h\appdata\local\programs\python\python37\lib\urllib\request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
```

---

### Description of your *issue*, suggested solution and other information

I'm unable to download this video, but it plays fine in Chrome 71: https://www.youtube.com/watch?v=xSGIilPdXKg

**Comment by dstftw** [comment]
Most likely a network issue on your side.

**Comment by nyuszika7h** [comment]
In Chrome it also fails but it falls back to r3---sn-c0q7lnly.googlevideo.com (74.125.154.8) which appears to be a Google US CDN. Perhaps it would be possible to implement a fallback in youtube-dl as well.

**Comment by xftroxgpx** [comment]
I'm seeing this with multiple videos since at least yesterday. A fallback like the one mentioned [above](https://github.com/rg3/youtube-dl/issues/18586#issuecomment-448759844) would be great.

Several hosts are down, apparently, (in chromium also, but due to some fallback it chooses different hosts and it then works after a few seconds):
So we get `ERROR: unable to download video data: <urlopen error timed out>` with youtube-dl.

Hosts down that I know of, so far:
```
31.46.22.90 r7---sn-h5bt5guxax3vh-c0qk.googlevideo.com                          
31.46.22.92 r9---sn-h5bt5guxax3vh-c0qk.googlevideo.com
31.46.22.98 r15---sn-h5bt5guxax3vh-c0qk.googlevideo.com
```
I do remember one host(the r9 one), yesterday, responding to ping but not to TCP (ie. SYN_SENT was the only one visible in `netstat`). Today none respond to ping.

Sample affected videos(for the above 3 hosts):
https://www.youtube.com/watch?v=_YxSQy1aeDc
https://www.youtube.com/watch?v=SOQVQZS3UJo
https://www.youtube.com/watch?v=0tvsdRY86lc
