### ISSUE TITLE
[Pluralsight] No video formats found

### ISSUE THREAD

**Issue by crow50** [rg3/youtube-dl#18591]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.12.17*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.12.17**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[download] Downloading video 1 of 141
[pluralsight] Downloading login page
[pluralsight] Logging in
[pluralsight] docker-swarm-mode-getting-started-m0-0: Downloading JSON metadata
[pluralsight] docker-swarm-mode-getting-started-m0-0: Downloading mp4-high-widescreen viewclip graphql
[pluralsight] docker-swarm-mode-getting-started-m0-0: Waiting for 2 seconds to avoid throttling
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on u'https://vid.pluralsight.com/clips/resolution/3df05bc9-b1e1-4b44-8314-45e783995971/current/mp4/1280x720.mp4?sgXLDsh8J5kVoUhJGV7wTNmDguqh-56xXKrYBREI1EN_eui5_S0C8gD-eYrAkEjer6beeT2jXfDOrYwJgBU2PJnspsRquJy_oxIdUxt369dJKdP0OFLAA3UT2exDc1mKXQP22mm-eQ8LVTk0dlW1MRv5olqV-f-pt9KDaMmDe_pc7bZYGQDyLI5-SHdC'
[download] /complete/Getting Started with Docker Swarm Mode/1 - Course Overview/Course Overview.mp4 has already been downloaded
[download] 100% of 4.22MiB
[download] Downloading video 2 of 141
[pluralsight] docker-swarm-mode-getting-started-m1-0: Downloading JSON metadata
[pluralsight] docker-swarm-mode-getting-started-m1-0: Downloading mp4-high-widescreen viewclip graphql
[pluralsight] docker-swarm-mode-getting-started-m1-0: Waiting for 2 seconds to avoid throttling
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 793, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/pluralsight.py", line 421, in _real_extract
    self._sort_formats(formats)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 1292, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
---

### Description of your *issue*, suggested solution and other information

It appears as though Pluralsight changed the way the course URLs work. 

https://app.pluralsight.com/library/courses/docker-swarm-mode-getting-started 
-->
https://app.pluralsight.com/library/courses/docker-swarm-mode-getting-started/table-of-contents

Changing the URL does not fix the issue.

**Comment by crow50** [comment]
It took awhile to show up but I guess my plan expired. Sorry.
