### ISSUE TITLE
Can't download from rbb-online.de

### ISSUE THREAD

**Issue by cboltz** [rg3/youtube-dl#18642]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.12.17**
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

```
# youtube-dl -v https://www.rbb-online.de/maerchenfilm/archiv/allerleirauh/allerleirauh.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.rbb-online.de/maerchenfilm/archiv/allerleirauh/allerleirauh.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.12.17
[debug] Python version 2.7.15 (CPython) - Linux-4.19.8-1-default-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.1, ffprobe 4.1
[debug] Proxy map: {}
[generic] allerleirauh: Requesting header
WARNING: Falling back on generic information extractor.
[generic] allerleirauh: Downloading webpage
[generic] allerleirauh: Extracting information
ERROR: Unsupported URL: https://www.rbb-online.de/maerchenfilm/archiv/allerleirauh/allerleirauh.html
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2340, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/bin/youtube-dl/youtube_dl/compat.py", line 2542, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/bin/youtube-dl/youtube_dl/compat.py", line 2531, in _XML
    parser.feed(text)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
ParseError: undefined entity: line 36, column 0
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 793, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3323, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.rbb-online.de/maerchenfilm/archiv/allerleirauh/allerleirauh.html
```

---

### example URLs
- Single video: https://www.rbb-online.de/maerchenfilm/archiv/allerleirauh/allerleirauh.html
- Single video: https://www.rbb-online.de/maerchenfilm/archiv/aschenputtel/aschenputtel.html
- Overview page (the first ~10 links point to a page with a video, the others only to the video description): https://www.rbb-online.de/maerchenfilm/archiv/sechs_auf_einen_streich.html

---

### Description of your *issue*, suggested solution and other information

Please add support to download videos from the rbb-online.de page.

(Workaround: rbb belongs to ARD, so if you are lucky, ardmediathek.de will also have the movies.)

**Comment by o5729** [comment]
here https://www.youtube.com/watch?v=dQw4w9WgXcQ
