### ISSUE TITLE
Site support request: play.cine.ar

### ISSUE THREAD

**Issue by AlejandroBOFH** [rg3/youtube-dl#18701]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.12.17**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Site support request (request for adding support for a new site)

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
D:\Portables\youtube-dl>youtube-dl -v https://play.cine.ar/INCAA/produccion/1361/reproducir
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://play.cine.ar/INCAA/produccion/1361/reproducir']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg N-59275-g9b195dd, ffprobe N-59275-g9b195dd
[debug] Proxy map: {}
[generic] reproducir: Requesting header
[redirect] Following redirect to https://play.cine.ar/#/INCAA/produccion/1361/reproducir
[generic] reproducir: Requesting header
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5g6wx9_e\build\youtube_dl\utils.py", line 989, in deflate
zlib.error: Error -5 while decompressing data: incomplete or truncated stream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5g6wx9_e\build\youtube_dl\__init__.py", line 472, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5g6wx9_e\build\youtube_dl\__init__.py", line 462, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5g6wx9_e\build\youtube_dl\YoutubeDL.py", line 2002, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5g6wx9_e\build\youtube_dl\YoutubeDL.py", line 804, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5g6wx9_e\build\youtube_dl\YoutubeDL.py", line 865, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5g6wx9_e\build\youtube_dl\YoutubeDL.py", line 793, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5g6wx9_e\build\youtube_dl\extractor\common.py", line 508, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5g6wx9_e\build\youtube_dl\extractor\generic.py", line 2251, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5g6wx9_e\build\youtube_dl\extractor\common.py", line 605, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5g6wx9_e\build\youtube_dl\YoutubeDL.py", line 2212, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5g6wx9_e\build\youtube_dl\utils.py", line 1049, in http_response
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5g6wx9_e\build\youtube_dl\utils.py", line 991, in deflate
zlib.error: Error -5 while decompressing data: incomplete or truncated stream
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://play.cine.ar/INCAA/produccion/1361
- Single video: https://play.cine.ar/INCAA/produccion/1361/reproducir
- 
- Playlist: https://play.cine.ar/INCAA/produccion/4253
- Single video from above playlist: https://play.cine.ar/INCAA/produccion/4253/reproducir/4254

---

### Description of your *issue*, suggested solution and other information

Argentina's government publishes tv and cinema productions that had help from the government. It's a legit site for Argentina's content.

**Comment by OscarL** [comment]
Just in case someone wants to work on this... The source code for the official Kodi addon for the site in question might be helpful:

https://github.com/arsat/odeon-kodi
