### ISSUE TITLE
ERROR: Signature extraction failed: Traceback (most recent call last)

### ISSUE THREAD

**Issue by gbcaptain** [rg3/youtube-dl#18724]
***************************
** My software version: **
***************************
➜  youtube-dl --version
2018.03.14

*********************
** error message: **
*********************
➜  youtube-dl -F https://www.youtube.com/watch\?v\=XXXXXXXXXXXXX
[youtube] 3F44De8jeaE: Downloading webpage
[youtube] 3F44De8jeaE: Downloading video info webpage
[youtube] 3F44De8jeaE: Extracting video information
[youtube] 3F44De8jeaE: Downloading js player vflSzU_20
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1191, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1102, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/youtube.py", line 1163, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "/usr/lib/python3/dist-packages/youtube_dl/extractor/common.py", line 796, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract \x1b[0;34mInitial JS player signature function name\x1b[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by gbcaptain** [comment]
@dstftw what is the resolution for this issue? I have update my software to the latest version, what do you mean by "outdated-version", please advice. thanks.
