### ISSUE TITLE
NSFW site support request: kpopdeepfakes.club

### ISSUE THREAD

**Issue by user375s** [rg3/youtube-dl#18737]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.01.02*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.01.02**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://kpopdeepfakes.club/deepfakes/request-%EC%A7%81%EC%BA%A0_fancam-160408-%EB%A0%88%EC%9D%B4%EC%83%A4laysha-%ED%98%9C%EB%A6%AC-emergency-%EC%B6%A9%EB%82%A8%EB%8C%80-%EA%B3%B5%EB%8C%80-by-dumdumm/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.01.02
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.16299
[debug] exe versions: ffmpeg 4.1, ffprobe 4.1, phantomjs 2.1.1
[debug] Proxy map: {}
[generic] request-직캠_fancam-160408-레이샤laysha-혜리-emergency-충남대-공대-by-dumdumm: Requesting header
WARNING: Falling back on generic information extractor.
[generic] request-직캠_fancam-160408-레이샤laysha-혜리-emergency-충남대-공대-by-dumdumm: Downloading webpage
[generic] request-직캠_fancam-160408-레이샤laysha-혜리-emergency-충남대-공대-by-dumdumm: Extracting information
[generic] request-직캠_fancam-160408-레이샤laysha-혜리-emergency-충남대-공대-by-dumdumm: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 404: Not Found
ERROR: Unsupported URL: https://kpopdeepfakes.club/deepfakes/request-%EC%A7%81%EC%BA%A0_fancam-160408-%EB%A0%88%EC%9D%B4%EC%83%A4laysha-%ED%98%9C%EB%A6%AC-emergency-%EC%B6%A9%EB%82%A8%EB%8C%80-%EA%B3%B5%EB%8C%80-by-dumdumm/
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5nai6j15\build\youtube_dl\YoutubeDL.py", line 793, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5nai6j15\build\youtube_dl\extractor\common.py", line 508, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5nai6j15\build\youtube_dl\extractor\generic.py", line 3320, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://kpopdeepfakes.club/deepfakes/request-%EC%A7%81%EC%BA%A0_fancam-160408-%EB%A0%88%EC%9D%B4%EC%83%A4laysha-%ED%98%9C%EB%A6%AC-emergency-%EC%B6%A9%EB%82%A8%EB%8C%80-%EA%B3%B5%EB%8C%80-by-dumdumm/
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://kpopdeepfakes.club/deepfakes/request-%EC%A7%81%EC%BA%A0_fancam-160408-%EB%A0%88%EC%9D%B4%EC%83%A4laysha-%ED%98%9C%EB%A6%AC-emergency-%EC%B6%A9%EB%82%A8%EB%8C%80-%EA%B3%B5%EB%8C%80-by-dumdumm/

---

### Description of your *issue*, suggested solution and other information

Request site support for kpopdeepfakes.club

**Comment by ealgase** [comment]
Not sure if it makes sense to support this site based off of the type of content it contains.

**Comment by rautamiekka** [comment]
Agree. Whole deep fake stuff shouldn't be allowed anyway.
