### ISSUE TITLE
[Site support request] children french television replay.gulli.fr

### ISSUE THREAD

**Issue by ymartin59** [rg3/youtube-dl#18766]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.01.02*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.01.02**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Site support request (request for adding support for a new site)

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
~/bin/youtube-dl -v http://replay.gulli.fr/emissions/C-est-pas-sorcier2/VOD69001441731000 
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'http://replay.gulli.fr/emissions/C-est-pas-sorcier2/VOD69001441731000']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.01.02
[debug] Python version 2.7.12 (CPython) - Linux-3.2.40-i686-with-glibc2.0
[debug] exe versions: ffmpeg 2.7.1
[debug] Proxy map: {}
[generic] VOD69001441731000: Requesting header
WARNING: Falling back on generic information extractor.
[generic] VOD69001441731000: Downloading webpage
[generic] VOD69001441731000: Extracting information
ERROR: Unsupported URL: http://replay.gulli.fr/emissions/C-est-pas-sorcier2/VOD69001441731000
Traceback (most recent call last):
  File "/var/services/homes/yma/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2337, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/var/services/homes/yma/bin/youtube-dl/youtube_dl/compat.py", line 2542, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/var/services/homes/yma/bin/youtube-dl/youtube_dl/compat.py", line 2531, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: mismatched tag: line 36, column 350
Traceback (most recent call last):
  File "/var/services/homes/yma/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 793, in extract_info
    ie_result = ie.extract(url)
  File "/var/services/homes/yma/bin/youtube-dl/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/var/services/homes/yma/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3320, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://replay.gulli.fr/emissions/C-est-pas-sorcier2/VOD69001441731000
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video:  http://replay.gulli.fr/emissions/C-est-pas-sorcier2/VOD69001441731000
- Playlist: http://replay.gulli.fr/emissions/C-est-pas-sorcier2

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Basic site support request for french television replay.gulli.fr

**Comment by mavosaure** [comment]
I don't know if it's true for all videos, but some are hosted on another CDN
**1st example:**
Initial URL : http://replay.gulli.fr/dessins-animes/Dragons-Par-dela-les-rives2/VOD68994312414000
Streaming playlist URL : http://gulli-hls-replay.akamaized.net/68994312414000/68994312414000_ipad.smil/playlist.m3u8

**2nd example**
Initial URL : http://replay.gulli.fr/dessins-animes/Arthur-et-les-Minimoys/VOD69055316930000
Streaming playlist URL : http://gulli-hls-replay.akamaized.net/69055316930000/69055316930000_ipad.smil/playlist.m3u8

**Using this playlist directly in youtube-dl, it works. **
And as you can see, it's easy to deduce the playlist URL from the initial URL.

So, it's a workaround, but it could be easy to create a pseudo extractor!
Currently, it lacks support of metadata.
