### ISSUE TITLE
YouTube video fails with 404 on video data

### ISSUE THREAD

**Issue by minus7** [rg3/youtube-dl#18804]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.01.10*.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.01.10**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
$ youtube-dl -v 'https://www.youtube.com/watch?v=oijg6zlPYrg'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=oijg6zlPYrg']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.01.10
[debug] Python version 3.7.2 (CPython) - Linux-4.19.12-arch1-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg n4.1, ffprobe n4.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] oijg6zlPYrg: Downloading webpage
[youtube] oijg6zlPYrg: Downloading embed webpage
[youtube] oijg6zlPYrg: Refetching age-gated info webpage
[youtube] {18} signature length 40.40, html5 player vflUSUx0c
[youtube] {36} signature length 40.40, html5 player vflUSUx0c
[youtube] {17} signature length 40.40, html5 player vflUSUx0c
[youtube] {137} signature length 40.40, html5 player vflUSUx0c
[youtube] {136} signature length 40.40, html5 player vflUSUx0c
[youtube] {135} signature length 40.40, html5 player vflUSUx0c
[youtube] {134} signature length 40.40, html5 player vflUSUx0c
[youtube] {133} signature length 40.40, html5 player vflUSUx0c
[youtube] {160} signature length 40.40, html5 player vflUSUx0c
[youtube] {140} signature length 40.40, html5 player vflUSUx0c
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://r1---sn-h0jeened.googlevideo.com/videoplayback?ipbits=0&lmt=1524792889889162&sparams=aitags%2Cdur%2Cei%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cotf%2Cotfp%2Cpl%2Crequiressl%2Csource%2Cexpire&mn=sn-h0jeened%2Csn-4g5ednld&mm=31%2C26&ip=188.*snip*&dur=0.000&aitags=133%2C134%2C135%2C136%2C137%2C160&id=o-AH1UeWc9YAoZvw0u9zu5566EgjyvtUe8wG1DRW6H4DPm&mime=video%2Fmp4&ms=au%2Conr&requiressl=yes&pl=20&mv=m&mt=1547138451&expire=1547160148&otf=1&initcwndbps=1636250&key=yt6&keepalive=yes&ei=9HU3XPHFBI_zVqjoq8gJ&source=yt_otf&otfp=1&itag=136&fvip=1&c=WEB&signature=99C2DCB98BD9B1995CE8C2193692B91F6933AC63.89717AC2DF9E4071A14CADB5FF848836A76686D9&ratebypass=yes'
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 1903, in process_info
    partial_success = dl(fname, new_info)
  File "/usr/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 1848, in dl
    return fd.download(name, info)
  File "/usr/lib/python3.7/site-packages/youtube_dl/downloader/common.py", line 364, in download
    return self.real_download(filename, info_dict)
  File "/usr/lib/python3.7/site-packages/youtube_dl/downloader/http.py", line 341, in real_download
    establish_connection()
  File "/usr/lib/python3.7/site-packages/youtube_dl/downloader/http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 2212, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

```

---

### Description of your *issue*, suggested solution and other information

Download of [this YouTube video](https://www.youtube.com/watch?v=oijg6zlPYrg) fails with a 404 on the video data URL. It's age gated and can only be viewed in the browser when logged in.

**Comment by minus7** [comment]
I also tested with videos from https://github.com/rg3/youtube-dl/issues/17604#issuecomment-422367440 and they worked as expected (all working except the one with no embed + age restriction, but latter showin the appropriate error message)

**Comment by jakobkogler** [comment]
I don't think it has something to do with being age restricted.
The same thing also happens with this video (not age gated): https://www.youtube.com/watch?v=fd11gQVqy78

```
youtube-dl -v 'https://www.youtube.com/watch?v=fd11gQVqy78'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=fd11gQVqy78']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.01.10
[debug] Python version 2.7.15rc1 (CPython) - Linux-4.15.0-42-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.4-0ubuntu0.18.04.1, ffprobe 3.4.4-0ubuntu0.18.04.1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] fd11gQVqy78: Downloading webpage
[youtube] fd11gQVqy78: Downloading video info webpage
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://r15---sn-uxax3vh50nugp5-8pxe7.googlevideo.com/videoplayback?requiressl=yes&ei=2Ks3XJb0F9a2gAeviLjgBA&ms=au%2Crdu&mt=1547152227&mv=m&mm=31%2C29&mn=sn-uxax3vh50nugp5-8pxe7%2Csn-c0q7lns7&otfp=1&c=WEB&keepalive=yes&itag=136&aitags=133%2C134%2C135%2C136%2C137%2C160&pl=19&mime=video%2Fmp4&signature=E02656D5FB12C386CB6F98DBDA718054653FD9AB.8359F72D9F1B5A9156531EF8F73FEAA31772A336&ipbits=0&sparams=aitags%2Cdur%2Cei%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cotf%2Cotfp%2Cpl%2Crequiressl%2Csource%2Cexpire&id=o-AMoYHVbG4wDWeGA-XBUW0iRJzshOZxxfnPs-u6U5yUMg&fvip=1&source=yt_otf&initcwndbps=605000&dur=0.000&expire=1547173944&ip=213.147.166.41&key=yt6&lmt=1547134404185395&otf=1&ratebypass=yes'
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1903, in process_info
    partial_success = dl(fname, new_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1848, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 364, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 341, in real_download
    establish_connection()
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2212, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found
```

**Comment by minus7** [comment]
> The same thing also happens with this video (not age gated): https://www.youtube.com/watch?v=fd11gQVqy78

Works for me

**Comment by jakobkogler** [comment]
Strange, now my video also works also for me. But it definitely didn't worked before. Maybe because it was uploaded only a few hours ago?

**Comment by marabu88** [comment]
Yes....I also catch this error of some videos and have problem with first video from this issue - oijg6zlPYrg
All this videos I can see without autorization in another browser.

First problems with live streams, now this. YouTube decided to ruin the lives of all of us? :)

**Comment by marabu88** [comment]
I get also 2 (!) different error for last video

`youtube-dl -v https://www.youtube.com/watch?v=6D9abFolBxs
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=6D9abFolBxs']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2019.01.10
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg 4.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] 6D9abFolBxs: Downloading webpage
[youtube] 6D9abFolBxs: Downloading video info webpage
[youtube] {22} signature length 104, html5 player vfls55OIb
[youtube] {43} signature length 104, html5 player vfls55OIb
[youtube] {18} signature length 104, html5 player vfls55OIb
[youtube] {36} signature length 104, html5 player vfls55OIb
[youtube] {17} signature length 100, html5 player vfls55OIb
[youtube] {137} signature length 104, html5 player vfls55OIb
[youtube] {136} signature length 104, html5 player vfls55OIb
[youtube] {135} signature length 104, html5 player vfls55OIb
[youtube] {134} signature length 104, html5 player vfls55OIb
[youtube] {133} signature length 104, html5 player vfls55OIb
[youtube] {160} signature length 104, html5 player vfls55OIb
[youtube] {140} signature length 100, html5 player vfls55OIb
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://r15---sn-n8v7kn7e.googlevideo.com/videoplayback?ipbits=0&sparams=expire%2Cei%2Cip%2Crequiressl%2Clmt%2Cid%2Cotfp%2Cdur%2Cotf%2Cmime%2Cipbits%2Citag%2Csource%2Ckeepalive%2Caitags&mime=video%2Fmp4&pl=22&itag=136&nh=IgpwcjAzLnN2bzA1KgkxMjcuMC4wLjE%2C&keepalive=yes&aitags=133%2C134%2C135%2C136%2C137%2C160&lsparams=pl%2Cmv%2Cnh%2Cinitcwndbps%2Cms%2Cmn%2Cmm&lsig=ANVabiowRgIhAIjYKvi1KgE1zKZ4oiv6ahCa2EVqkFay-AeNQYulHhZoAiEAosdb2eLrltYaRZexitSUGCTHtMhug5DMgSGhZiTtFus%3D&c=WEB&otfp=1&mn=sn-n8v7kn7e%2Csn-4g5e6nzz&mm=31%2C26&ms=au%2Conr&ei=cO43XJS6MMXsyQWz15GQDg&mv=m&mt=1547169288&beids=9466586&requiressl=yes&otf=1&expire=1547190992&dur=0.000&lmt=1547119774036269&ip=128.72.118.251&fvip=2&initcwndbps=1602500&source=yt_otf&id=o-ACwRtoKPbE-PEkMJOQZx_7kdC7eIZBHjBuuHqXlPwonP&signature=AMao4c4wRQIhAIehkKvkA7Z7omMauQFEZZ8UFQNTJBSkImb6WGC-CB5QAiBFNtMkZfXMCDQ8hHX5-SldE0wTCabn4o82n67XkKb6wg==&ratebypass=yes'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpmxuexrxr\build\youtube_dl\YoutubeDL.py", line 1903, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpmxuexrxr\build\youtube_dl\YoutubeDL.py", line 1848, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpmxuexrxr\build\youtube_dl\downloader\common.py", line 364, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpmxuexrxr\build\youtube_dl\downloader\http.py", line 341, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpmxuexrxr\build\youtube_dl\downloader\http.py", line 109, in establish_connection
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpmxuexrxr\build\youtube_dl\YoutubeDL.py", line 2212, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden


youtube-dl -v https://www.youtube.com/watch?v=6D9abFolBxs
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=6D9abFolBxs']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2019.01.10
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg 4.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] 6D9abFolBxs: Downloading webpage
[youtube] 6D9abFolBxs: Downloading video info webpage
[youtube] {22} signature length 40.40, html5 player vfls55OIb
[youtube] {43} signature length 40.40, html5 player vfls55OIb
[youtube] {18} signature length 40.40, html5 player vfls55OIb
[youtube] {36} signature length 40.40, html5 player vfls55OIb
[youtube] {17} signature length 40.40, html5 player vfls55OIb
[youtube] {137} signature length 40.40, html5 player vfls55OIb
[youtube] {136} signature length 40.40, html5 player vfls55OIb
[youtube] {135} signature length 40.40, html5 player vfls55OIb
[youtube] {134} signature length 40.40, html5 player vfls55OIb
[youtube] {133} signature length 40.40, html5 player vfls55OIb
[youtube] {160} signature length 40.38, html5 player vfls55OIb
[youtube] {140} signature length 40.40, html5 player vfls55OIb
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://r15---sn-n8v7kn7e.googlevideo.com/videoplayback?otf=1&pl=22&initcwndbps=1738750&ipbits=0&sparams=aitags%2Cdur%2Cei%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cotf%2Cotfp%2Cpl%2Crequiressl%2Csource%2Cexpire&nh=IgpwcjAzLnN2bzA1KgkxMjcuMC4wLjE%2C&key=yt6&id=o-AH6mIERLVf6qdeX7JD4B2IOfS0c4x8OaxrZau-LdDqSy&otfp=1&aitags=133%2C134%2C135%2C136%2C137%2C160&expire=1547191056&lmt=1547119774036269&ms=au%2Conr&mm=31%2C26&mv=m&mt=1547169352&ip=128.72.118.251&dur=0.000&source=yt_otf&c=WEB&mn=sn-n8v7kn7e%2Csn-4g5edne6&mime=video%2Fmp4&requiressl=yes&ei=r-43XNvsO4StyAXHlZvoBQ&itag=136&fvip=2&keepalive=yes&signature=C4EB105D2FDEEBC53F0CE983735109D5389E317E.3C04C004F860518DB78F86818166885C6549F28C&ratebypass=yes'
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpmxuexrxr\build\youtube_dl\YoutubeDL.py", line 1903, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpmxuexrxr\build\youtube_dl\YoutubeDL.py", line 1848, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpmxuexrxr\build\youtube_dl\downloader\common.py", line 364, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpmxuexrxr\build\youtube_dl\downloader\http.py", line 341, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpmxuexrxr\build\youtube_dl\downloader\http.py", line 109, in establish_connection
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpmxuexrxr\build\youtube_dl\YoutubeDL.py", line 2212, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 502, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 685, in http_error_302
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found`

**Comment by ethus3h** [comment]
Here is a log of another video with this or a similar problem of 404 of video data, if it's any help, although I don't think this video is age restricted, live stream, or recently added:

```
kyan@elegiac ~/ytdle-2019jan11 nohup compiz --replace openbox $ youtube-dl --verbose https://www.youtube.com/watch?v=Z4Vy8R84T1U
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.youtube.com/watch?v=Z4Vy8R84T1U']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.01.10
[debug] Python version 2.7.14 (CPython) - Linux-4.9.34-wreathe-x86_64-Intel-R-_Core-TM-_i7-6560U_CPU_@_2.20GHz-with-gentoo-2.4.1
[debug] exe versions: ffmpeg 3.3.6, ffprobe 3.3.6, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] Z4Vy8R84T1U: Downloading webpage
[youtube] Z4Vy8R84T1U: Downloading video info webpage
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on u'https://r4---sn-45pg2vpou-2fhe.googlevideo.com/videoplayback?sparams=aitags%2Cdur%2Cei%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cotf%2Cotfp%2Cpl%2Crequiressl%2Csource%2Cexpire&ipbits=0&signature=94C36F3C753353CC150A348BACAE08D1E1618CA4.A5E7FA492FB9736DFFC9054575C8BC8E46F5D787&ip=72.65.98.123&key=yt6&lmt=1461350238724573&dur=0.000&expire=1547270087&otf=1&id=o-AOH-0j92Dhr81Ez9OPd8VJ14fgOGHrdmNZcUZq-FZwMd&source=yt_otf&initcwndbps=533750&fvip=1&mm=31%2C29&mn=sn-45pg2vpou-2fhe%2Csn-ab5l6nsy&otfp=1&requiressl=yes&mt=1547248410&mv=m&ei=ZyM5XLPHINDEhwa5u4q4CQ&ms=au%2Crdu&aitags=133%2C134%2C135%2C136%2C137%2C160&itag=137&pl=24&mime=video%2Fmp4&c=WEB&keepalive=yes&ratebypass=yes'
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 1903, in process_info
    partial_success = dl(fname, new_info)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 1848, in dl
    return fd.download(name, info)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/downloader/common.py", line 364, in download
    return self.real_download(filename, info_dict)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/downloader/http.py", line 341, in real_download
    establish_connection()
  File "/usr/lib64/python2.7/site-packages/youtube_dl/downloader/http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 2212, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found

/bin/bash
failed with the error on /usr/bin/error-notify line 28 in /home/kyan/ytdle-2019jan11 at 20190111181449495235663_2d303530300a:
An error was reported on  line 4 in /home/kyan/ytdle-2019jan11 at 20190111231449478561647U2d303530300a.
kyan@elegiac ~/ytdle-2019jan11 nohup compiz --replace openbox $ 
```

**Comment by marabu88** [comment]
how i understand this problem for argument "-f bestvideo" or without any argumentd for a video format. all work fine with argument "-f best", but this argument - not best quality :(

If you check the list of formats and manually select the required one, then the download takes place without problems. I believe that the problem is incorrect calculation of the best quality stream in the current version of the program.

also need check this for "bestaudio" also
