### ISSUE TITLE
(YouTube) ERROR: unable to download video data: HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by Negativland** [rg3/youtube-dl#18818]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.01.10*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2019.01.10**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=CtVaixekJhU']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.01.10
[debug] Python version 2.7.12 (CPython) - Linux-4.4.0-141-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.15-0ubuntu0.16.04.1, ffprobe 2.8.15-0ubuntu0.16.04.1
[debug] Proxy map: {}
[youtube] CtVaixekJhU: Downloading webpage
[youtube] CtVaixekJhU: Downloading video info webpage
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://r4---sn-8xgn5uxa-4g5e.googlevideo.com/videoplayback?expire=1547245012&keepalive=yes&pl=24&requiressl=yes&fvip=4&pcm2cms=yes&itag=135&key=yt6&mime=video%2Fmp4&aitags=133%2C134%2C135%2C136%2C160&otf=1&ipbits=0&signature=67883B3F9221304EFB7800972A8AD469344B9568.0D127A4FCEE3D45F2DF7C1EDC414A6C55B6A8208&lmt=1544016663585214&otfp=1&mn=sn-8xgn5uxa-4g5e%2Csn-4g5ednsr&source=yt_otf&mm=31%2C29&c=WEB&dur=0.000&mv=m&mt=1547223330&ms=au%2Crdu&ip=88.130.55.203&ei=dME4XIC5ApPMgQeBnYaoAw&sparams=aitags%2Cdur%2Cei%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cotf%2Cotfp%2Cpcm2cms%2Cpl%2Crequiressl%2Csource%2Cexpire&id=o-AHle7Gi27Rsd_u9D7N81IsxT6KE0ROoW446fgK3XJZJM&initcwndbps=1470000&ratebypass=yes'
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1903, in process_info
    partial_success = dl(fname, new_info)
  File "/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1848, in dl
    return fd.download(name, info)
  File "/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 364, in download
    return self.real_download(filename, info_dict)
  File "/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 341, in real_download
    establish_connection()
  File "/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2212, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found


...
<end of log>
```

---

### Description of your *issue*, suggested solution and other information

Download of a simple YouTube video fails with Error 404. The Video is located at 
https://www.youtube.com/watch?v=CtVaixekJhU and has no access restrictions, it can be played in any browser. 

This problem has appeared before in https://github.com/rg3/youtube-dl/issues/6238
Adding `-f` to the command line works for the video above too. But as youtoube-dl's "best format guessing" normally works fine, I still consider throwing ERROR 404 to be a defect.

**Comment by Negativland** [comment]
@dstftw — just being curious: duplicate to which issue? Knowing that might improve my search next time. THX for your support.
