### ISSUE TITLE
Nova Play

### ISSUE THREAD

**Issue by minus273dot15** [rg3/youtube-dl#18837]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.01.10*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2019.01.10**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [X] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-vv', u'https://play.nova.bg/video/novinite-na-nova-tsentralna-emisiya/season-23/kalendar-ce-2019-01-12']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.01.10
[debug] Python version 2.7.13 (CPython) - Linux-4.18.0-0.bpo.3-amd64-x86_64-with-debian-9.6
[debug] exe versions: ffmpeg 3.3.9, ffprobe 3.3.9, rtmpdump 2.4
[debug] Proxy map: {}
[generic] kalendar-ce-2019-01-12: Requesting header
WARNING: Falling back on generic information extractor.
[generic] kalendar-ce-2019-01-12: Downloading webpage
[generic] kalendar-ce-2019-01-12: Extracting information
ERROR: Unsupported URL: https://play.nova.bg/video/novinite-na-nova-tsentralna-emisiya/season-23/kalendar-ce-2019-01-12
Traceback (most recent call last):
  File "bin/youtube-dl/youtube_dl/extractor/generic.py", line 2337, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "bin/youtube-dl/youtube_dl/compat.py", line 2542, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "bin/youtube-dl/youtube_dl/compat.py", line 2531, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 72, column 16
Traceback (most recent call last):
  File "bin/youtube-dl/youtube_dl/YoutubeDL.py", line 793, in extract_info
    ie_result = ie.extract(url)
  File "bin/youtube-dl/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "bin/youtube-dl/youtube_dl/extractor/generic.py", line 3320, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://play.nova.bg/video/novinite-na-nova-tsentralna-emisiya/season-23/kalendar-ce-2019-01-12
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://play.nova.bg/video/novinite-na-nova-tsentralna-emisiya/season-23/kalendar-ce-2019-01-12
- Playlist: https://neuclnlds1610lon.akamaized.net/nlds_vod/novaplay/vod/2019/01/12/23cfa360-d6d8-3de3-5190-b9b6ac148001/v1/stream/23cfa360-d6d8-3de3-5190-b9b6ac148001_1_pc.mp4.m3u8?h=306e5aae22e7c07a33b24254656294ec.1547323927812&amp;hdnea=exp=1547323987~acl=/*~hmac=FC5FA09684591EFA5007E8F1CB9B7F36F6DAC092D99EE0C197D2C582513691BA&amp;nltid=novaplay&amp;nltdt=0

---

### Description of your *issue*, suggested solution and other information

This is a site support request for https://play.nova.bg.

**Comment by minus273dot15** [comment]
Any updates on this?

**Comment by Bojidarist** [comment]
Hi! I recently made a pull request for Nova Play extractor for videos :+1: #28556

**Comment by minus273dot15** [comment]
Thanks, can confirm https://github.com/ytdl-org/youtube-dl/pull/28556 to be working:

```
~/src/youtube-dl$ git status
On branch novaplay
Your branch is up to date with 'origin/novaplay'.

python -m youtube_dl https://play.nova.bg/video/novinite-na-nova-kusna-emisiya/season-25/kalendar-kusna-2021-03-29/552873

ls -A -1 *mp4
'Новините на NOVA (29.03.2021 - късна емисия)-552873.mp4'
```
