### ISSUE TITLE
[vrt.nu] no video formats found

### ISSUE THREAD

**Issue by radiowest** [rg3/youtube-dl#18856]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.01.10*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2019.01.10**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl -v https://www.vrt.be/vrtnu/a-z/reizen-waes/4/reizen-waes-s4a4-polen/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.vrt.be/vrtnu/a-z/reizen-waes/4/reizen-waes-s4a4-polen/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.01.10
[debug] Python version 2.7.10 (CPython) - Darwin-17.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1, ffprobe 4.1
[debug] Proxy map: {}
[VrtNU] reizen-waes-s4a4-polen: Downloading webpage
WARNING: [VrtNU] reizen-waes-s4a4-polen: Failed to parse JSON Invalid \escape: line 9 column 75 (char 229)
[VrtNU] reizen-waes-s4a4-polen: Downloading JSON metadata
[Canvas] pbs-pub-fbca3718-390f-49a1-aed7-07ad3e180cb3$vid-b88661ef-54be-4870-9264-c000d08b536f: Downloading JSON metadata
[Canvas] pbs-pub-fbca3718-390f-49a1-aed7-07ad3e180cb3$vid-b88661ef-54be-4870-9264-c000d08b536f: Downloading m3u8 information
WARNING: Failed to download m3u8 information: <urlopen error [Errno 8] nodename nor servname provided, or not known>
[Canvas] pbs-pub-fbca3718-390f-49a1-aed7-07ad3e180cb3$vid-b88661ef-54be-4870-9264-c000d08b536f: Downloading MPD manifest
WARNING: Failed to download MPD manifest: <urlopen error [Errno 8] nodename nor servname provided, or not known>
[Canvas] pbs-pub-fbca3718-390f-49a1-aed7-07ad3e180cb3$vid-b88661ef-54be-4870-9264-c000d08b536f: Downloading ISM manifest
WARNING: Failed to download ISM manifest: <urlopen error [Errno 8] nodename nor servname provided, or not known>
[Canvas] pbs-pub-fbca3718-390f-49a1-aed7-07ad3e180cb3$vid-b88661ef-54be-4870-9264-c000d08b536f: Downloading f4m manifest
WARNING: Unable to download f4m manifest: <urlopen error [Errno 8] nodename nor servname provided, or not known>
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 793, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/canvas.py", line 73, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1302, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
...
<end of log>
```

---
### Description of your *issue*, suggested solution and other information

`vrt.nu` is no longer working since recently. See log attached.

**Comment by radiowest** [comment]
Please let me know of what issue this is a duplicate.
