### ISSUE TITLE
[SeznamZpravy] Extractor broken

### ISSUE THREAD

**Issue by oskar456** [rg3/youtube-dl#18866]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.01.10*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.01.10**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

```
$ youtube-dl -v 'https://www.seznamzpravy.cz/clanek/nauci-nas-poslanec-ondracek-zachazet-s-obuskem-pohladi-milos-zeman-vratu-po-vlasech-a-chcete-zazit-palachuv-tyden-znova-sledujte-nove-stastne-pondeli-64087?seq-no=1&dop-ab-variant=&source=clanky-home'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.seznamzpravy.cz/clanek/nauci-nas-poslanec-ondracek-zachazet-s-obuskem-pohladi-milos-zeman-vratu-po-vlasech-a-chcete-zazit-palachuv-tyden-znova-sledujte-nove-stastne-pondeli-64087?seq-no=1&dop-ab-variant=&source=clanky-home']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.01.10
[debug] Python version 3.6.5 (CPython) - Linux-4.20.0-x86_64-Intel-R-_Core-TM-_i7-2600_CPU_@_3.40GHz-with-gentoo-2.6
[debug] exe versions: ffmpeg 3.3.6, ffprobe 3.3.6, rtmpdump 2.4
[debug] Proxy map: {}
[SeznamZpravyArticle] 64087: Downloading webpage
WARNING: unable to extract OpenGraph description; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[download] Downloading playlist: Naučí nás poslanec Ondráček zacházet s obuškem? Pohladí Miloš Zeman Vráťu po vlasech? A chcete zažít Palachův týden znova? Sledujte nové Šťastné pondělí
[SeznamZpravyArticle] playlist Naučí nás poslanec Ondráček zacházet s obuškem? Pohladí Miloš Zeman Vráťu po vlasech? A chcete zažít Palachův týden znova? Sledujte nové Šťastné pondělí: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
ERROR: no suitable InfoExtractor for URL https://www.seznamzpravy.cz/iframe/player?lazyLoad=false&version=6.0.117&serviceName=Seznam%20Zpr%C3%A1vy&dotService=zpravy&gemiusPrismIdentifier=zD3g7byfW5ekpXmxTVLaq5Srjw5i4hsYo0HY1aBwIe..27&autoContentSwitch=true&imServer=i.imedia.cz&contentInfoTitle=false&nielsenEnabled=true&countAds=true&regression=false
  File "/usr/lib/python-exec/python3.6/youtube-dl", line 11, in <module>
    load_entry_point('youtube-dl==2019.1.10', 'console_scripts', 'youtube-dl')()
  File "/usr/lib64/python3.6/site-packages/youtube_dl/__init__.py", line 472, in main
    _real_main(argv)
  File "/usr/lib64/python3.6/site-packages/youtube_dl/__init__.py", line 462, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/lib64/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 2002, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/lib64/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 804, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib64/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 1003, in process_ie_result
    extra_info=extra)
  File "/usr/lib64/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 865, in process_ie_result
    extra_info=extra_info)
  File "/usr/lib64/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 827, in extract_info
    self.report_error('no suitable InfoExtractor for URL %s' % url)
  File "/usr/lib64/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 621, in report_error
    self.trouble(error_message, tb)
  File "/usr/lib64/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 583, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())
```

---

### Description of your *issue*, suggested solution and other information

It seems that Seznam has changed the video platform somehow, the iframe links now don't contain `src=` parameter, which is necessary for the current version of `SeznamZpravyIE`.

Example URL (I hope not georesricted) is here:
 - `https://www.seznamzpravy.cz/clanek/nauci-nas-poslanec-ondracek-zachazet-s-obuskem-pohladi-milos-zeman-vratu-po-vlasech-a-chcete-zazit-palachuv-tyden-znova-sledujte-nove-stastne-pondeli-64087?seq-no=1&dop-ab-variant=&source=clanky-home`

**Comment by ondrejmirtes** [comment]
I second this:

```
youtube-dl -v 'https://www.seznamzpravy.cz/iframe/player?lazyLoad=false&version=6.2.10&serviceName=Seznam%20Zpr%C3%A1vy&dotService=zpravy&gemiusPrismIdentifier=zD3g7byfW5ekpXmxTVLaq5Srjw5i4hsYo0HY1aBwIe..27&autoContentSwitch=true&imServer=i.imedia.cz&contentInfoTitle=false&nielsenEnabled=true&pipButton=false&countAds=true&regression=false'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.seznamzpravy.cz/iframe/player?lazyLoad=false&version=6.2.10&serviceName=Seznam%20Zpr%C3%A1vy&dotService=zpravy&gemiusPrismIdentifier=zD3g7byfW5ekpXmxTVLaq5Srjw5i4hsYo0HY1aBwIe..27&autoContentSwitch=true&imServer=i.imedia.cz&contentInfoTitle=false&nielsenEnabled=true&pipButton=false&countAds=true&regression=false']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.02.18
[debug] Python version 2.7.10 (CPython) - Darwin-18.2.0-x86_64-i386-64bit
[debug] exe versions: rtmpdump 2.4
[debug] Proxy map: {}
[generic] player?lazyLoad=false&version=6.2.10&serviceName=Seznam Zprávy&dotService=zpravy&gemiusPrismIdentifier=zD3g7byfW5ekpXmxTVLaq5Srjw5i4hsYo0HY1aBwIe..27&autoContentSwitch=true&imServer=i.imedia: Requesting header
WARNING: Falling back on generic information extractor.
[generic] player?lazyLoad=false&version=6.2.10&serviceName=Seznam Zprávy&dotService=zpravy&gemiusPrismIdentifier=zD3g7byfW5ekpXmxTVLaq5Srjw5i4hsYo0HY1aBwIe..27&autoContentSwitch=true&imServer=i.imedia: Downloading webpage
[generic] player?lazyLoad=false&version=6.2.10&serviceName=Seznam Zprávy&dotService=zpravy&gemiusPrismIdentifier=zD3g7byfW5ekpXmxTVLaq5Srjw5i4hsYo0HY1aBwIe..27&autoContentSwitch=true&imServer=i.imedia: Extracting information
[download] Downloading playlist: video
[generic] playlist video: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on u'https://www.seznamzpravy.cz/iframe/undefined'
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1913, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1852, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 364, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 341, in real_download
    establish_connection()
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2225, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found
```

**Comment by mcepl** [comment]
Would it be possible to extended URLs for that extractor even to this one, please?

```
~@stitny$ youtube-dl --version 'https://www.televizeseznam.cz/video/stastne-pondeli/stastne-pondeli-zeman-urazil-klause-neverte-mu-nevi-o-cem-mluvi-prohlasil-64102902'
2020.09.20
~@stitny$ youtube-dl --verbose 'https://www.televizeseznam.cz/video/stastne-pondeli/stastne-pondeli-zeman-urazil-klause-neverte-mu-nevi-o-cem-mluvi-prohlasil-64102902'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.televizeseznam.cz/video/stastne-pondeli/stastne-pondeli-zeman-urazil-klause-neverte-mu-nevi-o-cem-mluvi-prohlasil-64102902']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.09.20
[debug] Python version 3.8.5 (CPython) - Linux-5.8.14-1-default-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1
[debug] Proxy map: {}
[generic] stastne-pondeli-zeman-urazil-klause-neverte-mu-nevi-o-cem-mluvi-prohlasil-64102902: Requesting header
WARNING: Falling back on generic information extractor.
[generic] stastne-pondeli-zeman-urazil-klause-neverte-mu-nevi-o-cem-mluvi-prohlasil-64102902: Downloading webpage
[generic] stastne-pondeli-zeman-urazil-klause-neverte-mu-nevi-o-cem-mluvi-prohlasil-64102902: Extracting information
ERROR: Unsupported URL: https://www.televizeseznam.cz/video/stastne-pondeli/stastne-pondeli-zeman-urazil-klause-neverte-mu-nevi-o-cem-mluvi-prohlasil-64102902
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3382, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.televizeseznam.cz/video/stastne-pondeli/stastne-pondeli-zeman-urazil-klause-neverte-mu-nevi-o-cem-mluvi-prohlasil-64102902

~@stitny$ 
```

**Comment by MightyPork** [comment]
Same issue confirmed in 2020.09.20
