### ISSUE TITLE
Failue to download YouTube video -- "Could not find JS function 'encodeURIComponent'"

### ISSUE THREAD

**Issue by RalphORama** [rg3/youtube-dl#18891]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.01.16*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.01.16**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://www.youtube.com/watch?v=jr41skFqzb8']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2019.01.16
[debug] Python version 3.7.1 (CPython) - Windows-10-10.0.17763-SP0
[debug] exe versions: ffmpeg 4.1, ffprobe 4.1
[debug] Proxy map: {}
[youtube] jr41skFqzb8: Downloading webpage
[youtube] jr41skFqzb8: Downloading video info webpage
[youtube] {18} signature length 43.40, html5 player vflxwIF7f
[youtube] jr41skFqzb8: Downloading player https://www.youtube.com/yts/jsbin/player_ias-vflxwIF7f/en_US/base.js
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\Ralph\AppData\Roaming\Python\Python37\site-packages\youtube_dl\extractor\youtube.py", line 1232, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\Ralph\AppData\Roaming\Python\Python37\site-packages\youtube_dl\extractor\youtube.py", line 1140, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "C:\Users\Ralph\AppData\Roaming\Python\Python37\site-packages\youtube_dl\extractor\youtube.py", line 1207, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "C:\Users\Ralph\AppData\Roaming\Python\Python37\site-packages\youtube_dl\jsinterp.py", line 245, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'encodeURIComponent'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Could not find JS function 'encodeURIComponent'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.")); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\Ralph\AppData\Roaming\Python\Python37\site-packages\youtube_dl\extractor\youtube.py", line 1232, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\Ralph\AppData\Roaming\Python\Python37\site-packages\youtube_dl\extractor\youtube.py", line 1140, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "C:\Users\Ralph\AppData\Roaming\Python\Python37\site-packages\youtube_dl\extractor\youtube.py", line 1207, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "C:\Users\Ralph\AppData\Roaming\Python\Python37\site-packages\youtube_dl\jsinterp.py", line 245, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'encodeURIComponent'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\Ralph\AppData\Roaming\Python\Python37\site-packages\youtube_dl\extractor\youtube.py", line 1232, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\Ralph\AppData\Roaming\Python\Python37\site-packages\youtube_dl\extractor\youtube.py", line 1140, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "C:\Users\Ralph\AppData\Roaming\Python\Python37\site-packages\youtube_dl\extractor\youtube.py", line 1207, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "C:\Users\Ralph\AppData\Roaming\Python\Python37\site-packages\youtube_dl\jsinterp.py", line 245, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'encodeURIComponent'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Ralph\AppData\Roaming\Python\Python37\site-packages\youtube_dl\YoutubeDL.py", line 793, in extract_info
    ie_result = ie.extract(url)
  File "C:\Users\Ralph\AppData\Roaming\Python\Python37\site-packages\youtube_dl\extractor\common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\Ralph\AppData\Roaming\Python\Python37\site-packages\youtube_dl\extractor\youtube.py", line 1888, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "C:\Users\Ralph\AppData\Roaming\Python\Python37\site-packages\youtube_dl\extractor\youtube.py", line 1242, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\Ralph\AppData\Roaming\Python\Python37\site-packages\youtube_dl\extractor\youtube.py", line 1232, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\Ralph\AppData\Roaming\Python\Python37\site-packages\youtube_dl\extractor\youtube.py", line 1140, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "C:\Users\Ralph\AppData\Roaming\Python\Python37\site-packages\youtube_dl\extractor\youtube.py", line 1207, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "C:\Users\Ralph\AppData\Roaming\Python\Python37\site-packages\youtube_dl\jsinterp.py", line 245, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'encodeURIComponent'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Could not find JS function 'encodeURIComponent'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.")); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

---

### Description of your *issue*, suggested solution and other information

It appears that I cannot download YouTube videos.  I've attempted with the following links, but receive the error `Could not find JS function 'encodeURIComponent'` with every attempt.  This issue was brought up by a friend who is experiencing the same problem.

- https://www.youtube.com/watch?v=jr41skFqzb8
- https://www.youtube.com/watch?v=zF8OMK5vVJc
- https://www.youtube.com/watch?v=6ONRf7h3Mdk
- https://www.youtube.com/watch?v=BNzc6hG3yN4
- https://www.youtube.com/watch?v=1-nkbipHEdk

However, I **am able** to download the following videos:

- https://www.youtube.com/watch?v=PNIiTb6mfy0
- https://www.youtube.com/watch?v=zR8sRjBJgQ8
- https://www.youtube.com/watch?v=5f7_AI9H3N4
- https://www.youtube.com/watch?v=V1LgLfItk8Q
- https://www.youtube.com/watch?v=47ClcUcGB7U

I'm not sure what the difference is between them, but the first five don't work and the last five do.  Any help would be appreciated.

**Comment by carlbennett** [comment]
@RalphORama failed this step:
> Searched the bugtracker for similar issues including closed ones

#18873

**Comment by RalphORama** [comment]
@carlbennett Mentioned issue does not provide verbose log as is requested and very few examples.  Thanks.

**Comment by carlbennett** [comment]
@RalphORama Okay what do you say about #18890 then? You should tag along examples and verbose logs to the #18873.

**Comment by RalphORama** [comment]
@carlbennett thank you for your input, I'll wait and see what youtube-dl contributors say the issue was.  I'm excited for a fix.

**Comment by carlbennett** [comment]
Learn to search better.

**Comment by carlbennett** [comment]
Someone already made a fix in that issue I linked.

**Comment by carlbennett** [comment]
Someone already made a fix in that issue I linked.

**Comment by carlbennett** [comment]
Someone already made a fix in that issue I linked.

**Comment by RalphORama** [comment]
@carlbennett bug reports are neither the time nor place to flame other users.  I appreciate your linking of other issues but I think your usefulness in this thread has reached its limit.

**Comment by carlbennett** [comment]
@RalphORama "Usefulness" hasn't ended. Seriously, take a look at this guy's commit:
https://github.com/Khang-NT/youtube-dl/commit/f829ef2e13c4e791f455282a9b7f0ecde9891252

**Comment by cosynox** [comment]
I have the same problem:
youtube-dl -i -v --extract-audio --audio-format mp3 -o "%(title)s.%(ext)s" https://www.youtube.com/watch?v=W434iQM7Lzw
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-i', u'-v', u'--extract-audio', u'--audio-format', u'mp3', u'-o', u'%(title)s.%(ext)s', u'https://www.youtube.com/watch?v=W434iQM7Lzw']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.01.16
[debug] Python version 2.7.13 (CPython) - Linux-4.9.0-8-amd64-x86_64-with-debian-9.6
[debug] exe versions: ffmpeg 3.3.9, ffprobe 3.3.9, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] W434iQM7Lzw: Downloading webpage
[youtube] W434iQM7Lzw: Downloading video info webpage
[youtube] {18} signature length 43.40, html5 player vflxwIF7f
[youtube] W434iQM7Lzw: Downloading player https://www.youtube.com/yts/jsbin/player_ias-vflxwIF7f/en_US/base.js
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1232, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1140, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1207, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 245, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
ExtractorError: Could not find JS function u'encodeURIComponent'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Could not find JS function u'encodeURIComponent'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1232, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1140, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1207, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 245, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
ExtractorError: Could not find JS function u'encodeURIComponent'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 793, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1888, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1242, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1232, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1140, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1207, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 245, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
ExtractorError: Could not find JS function u'encodeURIComponent'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Could not find JS function u'encodeURIComponent'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by RalphORama** [comment]
@carlbennett I appreciate Mr. Khang's fix much more than I appreciate your trolling in this thread.

**Comment by Ornosunite** [comment]
@RalphORama is the real troll here, @carlbennett is just following the repository's contributing guidelines unlike @RalphORama who makes duplicate issues and lies about searching for similar ones.

There's a fix already, y'all calm down and go download your videos.

**Comment by RalphORama** [comment]
@Ornosunite please keep comments related to the issue at hand.  Thank you.

**Comment by mitchle** [comment]
@carlbennett you sound like an npc bro

**Comment by linuxbird** [comment]
I get identical results as cosynox.   Running current version.  Was copying files, and this died in the last two hours.

**Comment by iPaat** [comment]
Where can I find the mentioned fix?

**Comment by carlbennett** [comment]
@iPaat https://github.com/Khang-NT/youtube-dl/commit/f829ef2e13c4e791f455282a9b7f0ecde9891252

**Comment by iPaat** [comment]
Could someone be a nice mate and compile a version for Windows for me?

**Comment by carlbennett** [comment]
@mitchle what happened to your npc comment? too afraid to leave it up? lmfao

**Comment by scallywag41** [comment]
Please forgive me as I am not a coder.  I am an end user who is curious.  If someone might have the kindness to explain to me how I might update to the latest fixed version?

~# pip install --upgrade youtube-dl
Requirement already up-to-date: youtube-dl in /usr/local/lib/python3.6/dist-packages (2019.1.16)
~#

**Comment by RalphORama** [comment]
@scallywag41 there's no new release yet, simply a proposed fix.  I assume a new version will be deployed on pip later this week.

**Comment by scallywag41** [comment]
@RalphORama Thank you sir.  I will keep an eye on the thread.  Sorry if I've interrupted.  I don't use git a great deal and so I hope I haven't broken any etiquette.

**Comment by jchook** [comment]
Here is the one-liner fix for future visitors:

```
pip install https://github.com/Khang-NT/youtube-dl/archive/master.zip
```

**Comment by cosynox** [comment]
I have applied the fix that was proposed by carlbennet and it works for me very well.
Syndey Youngblood ist playing Sit and Wait... Thank you!

**Comment by jc3213** [comment]
Sorry, but this bug still persists in Windows version 2019.01.17. Here is the debug log:

PS: I'm using a http proxy for downloading since I can't access youtube directly. other videos without `js player` works fine.

Download url: https://www.youtube.com/watch?v=dhQ5IC0NGUM&t=10s
[youtube] dhQ5IC0NGUM: Downloading webpage
[youtube] dhQ5IC0NGUM: Downloading video info webpage
[youtube] dhQ5IC0NGUM: Downloading js player vfl-jbnrr
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpgf__qgjd\build\youtube_dl\extractor\youtube.py", line 1232, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpgf__qgjd\build\youtube_dl\extractor\youtube.py", line 1139, in _extract_signature_function
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpgf__qgjd\build\youtube_dl\extractor\common.py", line 777, in _download_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpgf__qgjd\build\youtube_dl\extractor\common.py", line 772, in _download_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpgf__qgjd\build\youtube_dl\extractor\youtube.py", line 268, in _download_webpage_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpgf__qgjd\build\youtube_dl\extractor\common.py", line 642, in _download_webpage_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpgf__qgjd\build\youtube_dl\extractor\common.py", line 692, in _webpage_read_content
  File "C:\Python\Python34\lib\http\client.py", line 549, in read
  File "C:\Python\Python34\lib\http\client.py", line 701, in _safe_read
http.client.IncompleteRead: IncompleteRead(524288 bytes read, 583283 more expected)
 (caused by IncompleteRead(524288 bytes read, 583283 more expected)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
't' is not recognized as an internal or external command,
operable program or batch file.
Press any key to continue . . .

**Comment by baobabKoodaa** [comment]
Same, this persists for me as well on Windows version 2019.01.17

**Comment by Hrxn** [comment]
`https://www.youtube.com/watch?v=dhQ5IC0NGUM` seems to work for me..

```
[debug] youtube-dl version 2019.01.17
[debug] Python version 3.7.1 (CPython) - Windows-10-10.0.17763-SP0
[debug] exe versions: ffmpeg 4.1, ffprobe 4.1
```

These settings used in `youtube-dl.conf`:
```
--netrc
--output "%(title)s.%(ext)s"
--format "(bestvideo[vcodec=vp9.2]/bestvideo[vcodec=vp9][fps>30]/bestvideo[vcodec=vp9][height>=1080]/bestvideo[fps>30]/bestvideo[height>720])+(bestaudio[acodec=opus]/bestaudio)/best"
--restrict-filenames
--download-archive "D:\\Media\\ytdl-archive.log"
```

Dunno, but signing in (cf. `--netrc`) might help.
Alternatively, try this: youtube-dl uses a cache in $HOME (same location as config file, usually)
I.e. `$HOME\.cache\youtube-dl\youtube-sigfuncs`

Maybe try deleting that whole thing, not sure if this makes any difference.

**Comment by jc3213** [comment]
@Hrxn I've tried `-n` aka `--netrc` but youtube-dl only shows `WARNING: parsing .netrc: Could not find .netrc: $HOME is not set` and nothing changed.

It seems you are on Linux, but I have the problem on Windows.

**Comment by morrishopkins** [comment]
Still having this issue with the latest release.

I updated to the latest version after removing old versions:
```
➜ pip install --upgrade youtube-dl
Collecting youtube-dl  Using cached https://files.pythonhosted.org/packages/72/35/415e01c9cf57e6aafb757237d7cd61a72bcb5c6f830b8c050858b76243a5/youtube_dl-2019.1.30.1-py2.py3-none-any.whlInstalling collected packages: youtube-dlSuccessfully installed youtube-dl-2019.1.30.1
```

But I am still getting this issue

```
File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 816, in extract_info
    self.report_error(compat_str(e), e.format_traceback())
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 621, in report_error
    self.trouble(error_message, tb)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 591, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 1231, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 1139, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 1206, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/jsinterp.py", line 245, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'encodeURIComponent'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Could not find JS function 'encodeURIComponent'; please repo...
```
example video https://www.youtube.com/watch?v=pkHlze-Pg3g
