### ISSUE TITLE
Issue - Linkedin Learning "unknown url type:"

### ISSUE THREAD

**Issue by circuitgeeks** [rg3/youtube-dl#18897]
I am using youtube-dl v 2019.1.17
but I am unable to download video from https://www.linkedin.com/learning/
I have a premium Linkedin account, You can obtain a premium account for free for 3 months >>

Steps:
1. Sign up for the FREE Visual Studio Dev Essentials program that you can find here: https://www.visualstudio.com/en-us/products/visual-studio-dev-essentials-vs.aspx
2. After you create your account, Click on the “Get Code” under the Linkedin Learning Tile

And I am getting this result when downloading

C:\Users\BM>youtube-dl -u user@user.com -p password "https://www.linkedin.com/learning/c-programming-for-embedded-applications"
[linkedin:learning:course] Downloading login page
[linkedin:learning:course] Logging in
[linkedin:learning:course] Downloading JSON metadata
[download] Downloading playlist: C Programming for Embedded Applications
[linkedin:learning:course] playlist C Programming for Embedded Applications: Collected 28 video ids (downloading 28 of them)
[download] Downloading video 1 of 28
[linkedin:learning] Downloading login page
[linkedin:learning] Logging in
Traceback (most recent call last):
  File "c:\users\BM\appdata\local\programs\python\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\BM\appdata\local\programs\python\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\BM\AppData\Local\Programs\Python\Python36-32\Scripts\youtube-dl.exe\__main__.py", line 9, in <module>
  File "c:\users\BM\appdata\local\programs\python\python36-32\lib\site-packages\youtube_dl\__init__.py", line 472, in main
    _real_main(argv)
  File "c:\users\BM\appdata\local\programs\python\python36-32\lib\site-packages\youtube_dl\__init__.py", line 462, in _real_main
    retcode = ydl.download(all_urls)
  File "c:\users\BM\appdata\local\programs\python\python36-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 2002, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "c:\users\BM\appdata\local\programs\python\python36-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 804, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "c:\users\BM\appdata\local\programs\python\python36-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 1003, in process_ie_result
    extra_info=extra)
  File "c:\users\BM\appdata\local\programs\python\python36-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 870, in process_ie_result
    extra_info=extra_info, download=False, process=False)
  File "c:\users\BM\appdata\local\programs\python\python36-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 793, in extract_info
    ie_result = ie.extract(url)
  File "c:\users\BM\appdata\local\programs\python\python36-32\lib\site-packages\youtube_dl\extractor\common.py", line 507, in extract
    self.initialize()
  File "c:\users\BM\appdata\local\programs\python\python36-32\lib\site-packages\youtube_dl\extractor\common.py", line 411, in initialize
    self._real_initialize()
  File "c:\users\BM\appdata\local\programs\python\python36-32\lib\site-packages\youtube_dl\extractor\linkedin.py", line 62, in _real_initialize
    data=urlencode_postdata(data))
  File "c:\users\BM\appdata\local\programs\python\python36-32\lib\site-packages\youtube_dl\extractor\common.py", line 772, in _download_webpage
    expected_status=expected_status)
  File "c:\users\BM\appdata\local\programs\python\python36-32\lib\site-packages\youtube_dl\extractor\common.py", line 638, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "c:\users\BM\appdata\local\programs\python\python36-32\lib\site-packages\youtube_dl\extractor\common.py", line 603, in _request_webpage
    url_or_request = sanitized_Request(url_or_request, data, headers)
  File "c:\users\BM\appdata\local\programs\python\python36-32\lib\site-packages\youtube_dl\utils.py", line 561, in sanitized_Request
    return compat_urllib_request.Request(sanitize_url(url), *args, **kwargs)
  File "c:\users\BM\appdata\local\programs\python\python36-32\lib\urllib\request.py", line 329, in __init__
    self.full_url = url
  File "c:\users\BM\appdata\local\programs\python\python36-32\lib\urllib\request.py", line 355, in full_url
    self._parse()
  File "c:\users\BM\appdata\local\programs\python\python36-32\lib\urllib\request.py", line 384, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/checkpoint/lg/login-submit'

**Comment by dxxvi** [comment]
I have a similar issuse
`
Arch:/dev/shm $ youtube-dl --verbose 'https://www.linkedin.com/learning/kubernetes-for-java-developers/applying-java-skills-to-kubernetes'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.linkedin.com/learning/kubernetes-for-java-developers/applying-java-skills-to-kubernetes']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.02.18
[debug] Python version 3.7.2 (CPython) - Linux-4.20.12-arch1-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 4.1.1, ffprobe 4.1.1, rtmpdump 2.4
[debug] Proxy map: {}
ERROR: An extractor error has occurred. (caused by KeyError('JSESSIONID')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/linkedin.py", line 95, in _real_extract
    course_slug, 'selectedVideo', video_slug, height)['selectedVideo']
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/linkedin.py", line 34, in _call_api
    'Csrf-Token': self._get_cookies(api_url)['JSESSIONID'].value,
KeyError: 'JSESSIONID'
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/linkedin.py", line 95, in _real_extract
    course_slug, 'selectedVideo', video_slug, height)['selectedVideo']
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/linkedin.py", line 34, in _call_api
    'Csrf-Token': self._get_cookies(api_url)['JSESSIONID'].value,
KeyError: 'JSESSIONID'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 794, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 521, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('JSESSIONID')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
`
