### ISSUE TITLE
How do i fix this error?

### ISSUE THREAD

**Issue by JustAnotherPythonProgrammer** [rg3/youtube-dl#18893]
[youtube] VbrEsOLu75c: Downloading webpage
[youtube] VbrEsOLu75c: Downloading video info webpage
[youtube] Downloading just video VbrEsOLu75c because of --no-playlist
[youtube] VbrEsOLu75c: Downloading js player vflxwIF7f
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\youtube_dl\extractor\youtube.py", line 1232, in _decrypt_signature
    video_id, player_url, s
  File "C:\Program Files\Python36\lib\site-packages\youtube_dl\extractor\youtube.py", line 1140, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "C:\Program Files\Python36\lib\site-packages\youtube_dl\extractor\youtube.py", line 1207, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "C:\Program Files\Python36\lib\site-packages\youtube_dl\jsinterp.py", line 245, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'encodeURIComponent'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Could not find JS function 'encodeURIComponent'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\youtube_dl\extractor\youtube.py", line 1232, in _decrypt_signature
    video_id, player_url, s
  File "C:\Program Files\Python36\lib\site-packages\youtube_dl\extractor\youtube.py", line 1140, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "C:\Program Files\Python36\lib\site-packages\youtube_dl\extractor\youtube.py", line 1207, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "C:\Program Files\Python36\lib\site-packages\youtube_dl\jsinterp.py", line 245, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'encodeURIComponent'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\youtube_dl\YoutubeDL.py", line 793, in extract_info
    ie_result = ie.extract(url)
  File "C:\Program Files\Python36\lib\site-packages\youtube_dl\extractor\common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "C:\Program Files\Python36\lib\site-packages\youtube_dl\extractor\youtube.py", line 1888, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "C:\Program Files\Python36\lib\site-packages\youtube_dl\extractor\youtube.py", line 1242, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\youtube_dl\extractor\youtube.py", line 1232, in _decrypt_signature
    video_id, player_url, s
  File "C:\Program Files\Python36\lib\site-packages\youtube_dl\extractor\youtube.py", line 1140, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "C:\Program Files\Python36\lib\site-packages\youtube_dl\extractor\youtube.py", line 1207, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "C:\Program Files\Python36\lib\site-packages\youtube_dl\jsinterp.py", line 245, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'encodeURIComponent'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Could not find JS function 'encodeURIComponent'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Download.pyw", line 44, in <module>
    Download()
  File "Download.pyw", line 29, in Download
    ydl.download([Songs[Index]['Link']])
  File "C:\Program Files\Python36\lib\site-packages\youtube_dl\YoutubeDL.py", line 2002, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "C:\Program Files\Python36\lib\site-packages\youtube_dl\YoutubeDL.py", line 816, in extract_info
    self.report_error(compat_str(e), e.format_traceback())
  File "C:\Program Files\Python36\lib\site-packages\youtube_dl\YoutubeDL.py", line 621, in report_error
    self.trouble(error_message, tb)
  File "C:\Program Files\Python36\lib\site-packages\youtube_dl\YoutubeDL.py", line 591, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\youtube_dl\extractor\youtube.py", line 1232, in _decrypt_signature
    video_id, player_url, s
  File "C:\Program Files\Python36\lib\site-packages\youtube_dl\extractor\youtube.py", line 1140, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "C:\Program Files\Python36\lib\site-packages\youtube_dl\extractor\youtube.py", line 1207, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "C:\Program Files\Python36\lib\site-packages\youtube_dl\jsinterp.py", line 245, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'encodeURIComponent'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Could not find JS function 'encodeURIComponent'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by iPaat** [comment]
Duplicate of #18891

**Comment by mbytescs** [comment]
Curious about this one as I'm seeing it also, yesterday with the Dec 2018 version of youtube-dl it was running fine, today getting the issue (see log below).  Even after updating to 1-16-19 version same thing, have seen this "fixed" a few times over the last couple of years why does it keep happening?

[youtube-dl_debug.log](https://github.com/rg3/youtube-dl/files/2766882/youtube-dl_debug.log)
