### ISSUE TITLE
[videomore] Extend _VALID_URL

### ISSUE THREAD

**Issue by Jeffin21** [rg3/youtube-dl#18908]
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://videomore.ru/molodezhka/6_sezon/29_ seriya?utm_source=videomore']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.01.17
[debug] Python version 2.7.10 (CPython) - Linux-2.6.32-754.2.1.el6.x86_64-x86_64 -with-centos-6.10-Final
[debug] exe versions: ffmpeg 4.1-static, ffprobe 4.1-static
[debug] Proxy map: {}
[generic] 29_seriya?utm_source=videomore: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 29_seriya?utm_source=videomore: Downloading webpage
[generic] 29_seriya?utm_source=videomore: Extracting information
ERROR: Unsupported URL: https://videomore.ru/molodezhka/6_sezon/29_seriya?utm_so urce=videomore
Traceback (most recent call last):
File "youtube-dl/youtube_dl/extractor/generic.py", line 2337, in _real_extract
doc = compat_etree_fromstring(webpage.encode('utf-8'))
File "youtube-dl/youtube_dl/compat.py", line 2542, in compat_etree_fromstring
doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory= _element_factory)))
File "youtube-dl/youtube_dl/compat.py", line 2531, in _XML
parser.feed(text)
File "/usr/local/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
self._raiseerror(v)
File "/usr/local/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raise error
raise err
ParseError: not well-formed (invalid token): line 8, column 48
Traceback (most recent call last):
File "youtube-dl/youtube_dl/YoutubeDL.py", line 793, in extract_info
ie_result = ie.extract(url)
File "youtube-dl/youtube_dl/extractor/common.py", line 508, in extract
ie_result = self._real_extract(url)
File "youtube-dl/youtube_dl/extractor/generic.py", line 3320, in _real_extract
raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://videomore.ru/molodezhka/6_sezon/29_se riya?utm_source=videomore

**Comment by ealgase** [comment]
Can you change this to the formatting of a site support request?

**Comment by Jeffin21** [comment]
@ealgase sure
