### ISSUE TITLE
unable to download video webpage

### ISSUE THREAD

**Issue by alq974120alq** [rg3/youtube-dl#1891]
using proxy, my safari browser works well, 
but on terminal, it doesn't work

python:2.6.1
max os x : 10.6.8

who can give me some suggestion?

follow is the youtube-dl's output:
-F --proxy "http://192.168.0.123:8080" -v  http://www.youtube.com/watch?v=6DKNKI27GdA 
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-F', '--proxy', 'http://192.168.0.123:8080', '-v', 'http://www.youtube.com/watch?v=6DKNKI27GdA']
[debug] youtube-dl version 2013.12.03
[debug] Python version 2.6.1 - Darwin-10.8.0-i386-64bit
[debug] Proxy map: {'http': 'http://192.168.0.123:8080', 'https': 'http://192.168.0.123:8080'}
[youtube] Setting language
WARNING: unable to set language: 
[youtube] 6DKNKI27GdA: Downloading video webpage
ERROR: Unable to download video webpage: ; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/Users/alq/workspace/online-video-downloader/trunk/dist/VideoDownloader_dbg.app/Contents/MacOS/yd/youtube_dl/extractor/youtube.py", line 1265, in _real_extract
    video_webpage_bytes = compat_urllib_request.urlopen(request).read()
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/urllib2.py", line 124, in urlopen
    return _opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/urllib2.py", line 383, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/urllib2.py", line 401, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/urllib2.py", line 361, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/urllib2.py", line 701, in <lambda>
    meth(r, proxy, type))
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/urllib2.py", line 724, in proxy_open
    return self.parent.open(req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/urllib2.py", line 383, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/urllib2.py", line 401, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/urllib2.py", line 361, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/urllib2.py", line 1141, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/urllib2.py", line 1114, in do_open
    r = h.getresponse()
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/httplib.py", line 950, in getresponse
    response.begin()
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/httplib.py", line 390, in begin
    version, status, reason = self._read_status()
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/httplib.py", line 354, in _read_status
    raise BadStatusLine(line)
BadStatusLine
Traceback (most recent call last):
  File "/Users/alq/workspace/online-video-downloader/trunk/dist/VideoDownloader_dbg.app/Contents/MacOS/yd/youtube_dl/YoutubeDL.py", line 429, in extract_info
    ie_result = ie.extract(url)
  File "/Users/alq/workspace/online-video-downloader/trunk/dist/VideoDownloader_dbg.app/Contents/MacOS/yd/youtube_dl/extractor/common.py", line 131, in extract
    return self._real_extract(url)
  File "/Users/alq/workspace/online-video-downloader/trunk/dist/VideoDownloader_dbg.app/Contents/MacOS/yd/youtube_dl/extractor/youtube.py", line 1267, in _real_extract
    raise ExtractorError(u'Unable to download video webpage: %s' % compat_str(err))
ExtractorError: Unable to download video webpage: ; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by dstftw** [comment]
Most likely this is caused by your proxy.
