### ISSUE TITLE
ytbbotdler issue cant  run on ubuntu 16.04 lts

### ISSUE THREAD

**Issue by destroyer19991** [rg3/youtube-dl#18914]
Error: Command failed: /home/adi/ytbBotDler/node_modules/youtube-dl/bin/youtube-dl --dump-json --format=18 http://www.youtube.com/watch?v=gcmzYjQRq0A
WARNING: unable to extract uploader nickname
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/home/adi/ytbBotDler/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1005, in _decrypt_signature
    video_id, player_url, s
  File "/home/adi/ytbBotDler/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 897, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
ExtractorError: Cannot identify player u'/yts/jsbin/player_ias-vfl-jbnrr/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Cannot identify player u'/yts/jsbin/player_ias-vfl-jbnrr/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:821:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

**Comment by destroyer19991** [comment]
can you tell me whats the problem
