### ISSUE TITLE
Failing to download specific YouTube video

### ISSUE THREAD

**Issue by KingOfTheNorthStar** [rg3/youtube-dl#18916]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.01.17*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.01.17**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

```
$ youtube-dl https://www.youtube.com/watch?v=DqxD97yMYu4 --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.youtube.com/watch?v=DqxD97yMYu4', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.01.17
[debug] Python version 2.7.15 (CPython) - Linux-4.19.10-300.fc29.x86_64-x86_64-with-fedora-29-Twenty_Nine
[debug] exe versions: ffmpeg 4.0.3, ffprobe 4.0.3, phantomjs 2.1.1
[debug] Proxy map: {}
[youtube] DqxD97yMYu4: Downloading webpage
[youtube] DqxD97yMYu4: Downloading video info webpage
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://r3---sn-vgqs7nly.googlevideo.com/videoplayback?itag=299&expire=1547869053&sparams=aitags%2Cclen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&source=youtube&mime=video%2Fmp4&fvip=3&keepalive=yes&lmt=1416380017610884&clen=290096370&mt=1547847292&mv=m&ms=au%2Conr&mm=31%2C26&mn=sn-vgqs7nly%2Csn-p5qs7n7z&dur=439.455&gir=yes&id=o-AMVAHJdoIEGsWgY-vcK768gZ70-GwnPUJl89ineAnRhJ&ei=HUdCXNHRIZfcNseXtagF&ip=2605%3Aa000%3Af607%3Aca00%3Ae23f%3A49ff%3Afe7e%3A6071&key=yt6&ipbits=0&signature=84E528EB220442935000E97CD524DCD73C9A39C3.E33BF99606743017D71DA24FE53F89AB810B5009&aitags=133%2C134%2C135%2C136%2C137%2C160%2C298%2C299&requiressl=yes&pl=32&c=WEB&initcwndbps=1737500&ratebypass=yes'
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 1 of 10)...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 2 of 10)...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 3 of 10)...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 4 of 10)...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 5 of 10)...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 6 of 10)...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 7 of 10)...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 8 of 10)...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 9 of 10)...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 10 of 10)...
ERROR: giving up after 10 retries
Traceback (most recent call last):
  File "/home/watson/bin/youtube-dl/youtube_dl/downloader/http.py", line 341, in real_download
    establish_connection()
  File "/home/watson/bin/youtube-dl/youtube_dl/downloader/http.py", line 182, in establish_connection
    raise RetryDownload(err)
RetryDownload

```

---
### Description of your *issue*, suggested solution and other information

Attempting to download `https://www.youtube.com/watch?v=DqxD97yMYu4` returns HTTP Error 503: Service Unavailable.

**Comment by marabu88** [comment]
This problem for some formats again.
`youtube-dl.exe -f 299 DqxD97yMYu4` - don't work (bestvideo or default settings). 
`youtube-dl.exe -f 298 DqxD97yMYu4` or youtube-dl.exe -f best DqxD97yMYu4 - work fine
```
youtube-dl.exe -F DqxD97yMYu4
[youtube] DqxD97yMYu4: Downloading webpage
[youtube] DqxD97yMYu4: Downloading video info webpage
[info] Available formats for DqxD97yMYu4:
format code  extension  resolution note
140          m4a        audio only DASH audio  129k , m4a_dash container, mp4a.40.2@128k, 6.73MiB
160          mp4        256x144    144p  111k , avc1.4d400c, 15fps, video only, 5.71MiB
133          mp4        426x240    240p  254k , avc1.4d4015, 30fps, video only, 12.84MiB
134          mp4        640x360    360p  617k , avc1.4d401e, 30fps, video only, 29.19MiB
135          mp4        854x480    480p 1125k , avc1.4d401f, 30fps, video only, 53.78MiB
136          mp4        1280x720   720p 2245k , avc1.4d401f, 30fps, video only, 107.36MiB
298          mp4        1280x720   720p60 3336k , avc1.4d4020, 60fps, video only, 163.14MiB
137          mp4        1920x1080  1080p 4181k , avc1.640028, 30fps, video only, 202.45MiB
299          mp4        1920x1080  1080p60 5575k , avc1.64002a, 60fps, video only, 276.66MiB
17           3gp        176x144    small   82k , mp4v.20.3, mp4a.40.2@ 24k (22050Hz), 4.30MiB
36           3gp        320x180    small  227k , mp4v.20.3, mp4a.40.2 (22050Hz), 11.92MiB
43           webm       640x360    medium , vp8.0, vorbis@128k, 46.52MiB
18           mp4        640x360    medium  712k , avc1.42001E, mp4a.40.2@ 96k (44100Hz), 37.31MiB
22           mp4        1280x720   hd720    4k , avc1.64001F, mp4a.40.2@192k (44100Hz) (best)
```

**Comment by dstftw** [comment]
Server side youtube issue. Select another format.
