### ISSUE TITLE
ERROR: Signature extraction failed: Traceback (most recent call last):

### ISSUE THREAD

**Issue by Big-Tex** [rg3/youtube-dl#18921]
## Getting errors while playing a song with my discord.py bot, 

- This error hasn't been happening, and i didn't edit so I don't know why now it's happening. 

---

### So I don't know what the problem is but when i play other songs it works but when i play this song `https://www.youtube.com/watch?v=_Yhyp-_hX2s`, It just gives me the error below!!!! What is the difference? They're both YouTube videos and it's not a playlist or something, it straight a video.

ERROR: Signature extraction failed: Traceback (most recent call last):
2019-01-19T13:47:49.048394+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1226, in _decrypt_signature
2019-01-19T13:47:49.048396+00:00 app[worker.1]:     video_id, player_url, s
2019-01-19T13:47:49.048413+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1134, in _extract_signature_function
2019-01-19T13:47:49.048415+00:00 app[worker.1]:     res = self._parse_sig_js(code)
2019-01-19T13:47:49.048417+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1201, in _parse_sig_js
2019-01-19T13:47:49.048419+00:00 app[worker.1]:     initial_function = jsi.extract_function(funcname)
2019-01-19T13:47:49.048425+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/youtube_dl/jsinterp.py", line 245, in extract_function
2019-01-19T13:47:49.048427+00:00 app[worker.1]:     raise ExtractorError('Could not find JS function %r' % funcname)
2019-01-19T13:47:49.048430+00:00 app[worker.1]: youtube_dl.utils.ExtractorError: Could not find JS function 'encodeURIComponent'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
2019-01-19T13:47:49.048434+00:00 app[worker.1]:  (caused by ExtractorError("Could not find JS function 'encodeURIComponent'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

I'm not going to share my respiratory but it's like this https://github.com/CharmingMother/kurusaki_voice/blob/ddc2628cbb2ebe1fe2987a37fa3733f1316064d4/audio.py and same issue with that too, so IDK

**Comment by KoolerTheFirst** [comment]
it's not just your program, it seems to be a problem with youtube-dl itself.  i tried downloading a video `https://www.youtube.com/watch?v=UysJ2Kh35O4` just now and got the same error.

[youtube] UysJ2Kh35O4: Downloading webpage
[youtube] UysJ2Kh35O4: Downloading video info webpage
[youtube] UysJ2Kh35O4: Downloading js player vfl-jbnrr
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5nai6j15\build\youtube_dl\extractor\youtube.py", line 1231, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5nai6j15\build\youtube_dl\extractor\youtube.py", line 1139, in _extract_signature_function
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5nai6j15\build\youtube_dl\extractor\youtube.py", line 1206, in _parse_sig_js
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp5nai6j15\build\youtube_dl\jsinterp.py", line 245, in extract_function
youtube_dl.utils.ExtractorError: Could not find JS function 'encodeURIComponent'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Could not find JS function 'encodeURIComponent'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

i think it might be a problem on youtube's side, considering the "encodeURIComponent" part of the error.  either way, i hope it can be fixed before it causes too many problems.

**Comment by Zipdox** [comment]
I had the problem too. I realized it didn't update successfully because I had youtube-dl in /home/user/.local/bin/ and in /usr/local/bin/ and it would only execute the first one. I had to delete it and move the new one there. After updating it worked again.

**Comment by ap4gh** [comment]
Hmm... I am having this `Signature extraction failed: Traceback` error not only from youtube-dl but also from `mpv` and `NewPipe`. NewPipe released *v0.15* yesterday it works on 0.15 but later version have same error. Also, mpv gives the same error!

I think Google have changed the code again. Need for an update.

**Comment by ap4gh** [comment]
My Solution for Mac/Linux & Unix:

Uninstall youtube-dl via your package manager and install the lastest build from the official website. https://rg3.github.io/youtube-dl/download.html

I saw there has been a commit to `youtube.py` extractor file 3 days ago, but the build version from the apt archive is 2018.10.03, which is quite old at this point. So just download the latest binary from its site.

**Comment by marlonlom** [comment]
what about WIndows?? IN version 2020-01-15 the bug persists :(

**Comment by polarberg** [comment]
Also doesn't work for me on Windows. It only doesn't work for music videos

**Comment by mihaiolteanu** [comment]
Not only on Windows. 2020-01-15 has the same issue on Linux, too.

**Comment by polarberg** [comment]
@mihaiolteanu @marlonlom Update to the version that came out today. Works now!

**Comment by zaheer-s** [comment]
New version works fine on my windows using WSL
