### ISSUE TITLE
[YouTube] Certain videos do not work after login

### ISSUE THREAD

**Issue by goggle** [rg3/youtube-dl#18950]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.01.17*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.01.17**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Description

Certain YouTube videos do not work when I use youtube-dl with my Google account credentials. Everything works fine, when I don't provide them to youtube-dl:
```
youtube-dl GW_gsNVM498 -f 313+251 -v --ignore-config
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['GW_gsNVM498', '-f', '313+251', '-v', '--ignore-config']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.01.17
[debug] Python version 3.7.2 (CPython) - Linux-4.20.0-arch1-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 4.1, ffprobe 4.1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] GW_gsNVM498: Downloading webpage
[youtube] GW_gsNVM498: Downloading video info webpage
[youtube] {18} signature length 42.44, html5 player vfl-jbnrr
[youtube] GW_gsNVM498: Downloading player https://www.youtube.com/yts/jsbin/player_ias-vfl-jbnrr/en_US/base.js
[youtube] {36} signature length 42.44, html5 player vfl-jbnrr
[youtube] {17} signature length 42.44, html5 player vfl-jbnrr
[youtube] {313} signature length 42.44, html5 player vfl-jbnrr
[youtube] {271} signature length 42.44, html5 player vfl-jbnrr
[youtube] {137} signature length 42.44, html5 player vfl-jbnrr
[youtube] {248} signature length 42.44, html5 player vfl-jbnrr
[youtube] {136} signature length 42.44, html5 player vfl-jbnrr
[youtube] {247} signature length 42.44, html5 player vfl-jbnrr
[youtube] {135} signature length 42.44, html5 player vfl-jbnrr
[youtube] {244} signature length 42.44, html5 player vfl-jbnrr
[youtube] {134} signature length 42.44, html5 player vfl-jbnrr
[youtube] {243} signature length 42.44, html5 player vfl-jbnrr
[youtube] {133} signature length 42.44, html5 player vfl-jbnrr
[youtube] {242} signature length 42.44, html5 player vfl-jbnrr
[youtube] {160} signature length 42.44, html5 player vfl-jbnrr
[youtube] {278} signature length 42.44, html5 player vfl-jbnrr
[youtube] {140} signature length 42.44, html5 player vfl-jbnrr
[youtube] {171} signature length 42.44, html5 player vfl-jbnrr
[youtube] {249} signature length 42.44, html5 player vfl-jbnrr
[youtube] {250} signature length 42.44, html5 player vfl-jbnrr
[youtube] {251} signature length 42.44, html5 player vfl-jbnrr
[debug] Invoking downloader on 'https://r1---sn-1gieen7e.googlevideo.com/videoplayback?mime=video%2Fwebm&expire=1548192347&key=yt6&txp=5532432&c=WEB&gir=yes&mn=sn-1gieen7e%2Csn-1gi7znes&ip=2a05%3A41c0%3A7%3Aa00%3A8850%3Af0d5%3A7b45%3A6911&mm=31%2C29&itag=313&pl=29&mv=m&mt=1548170620&ms=au%2Crdu&id=o-AHV6_nQtC7Ya9i6qNIQte84twcJyBi6N6TN9JvjNBGxP&beids=9466588&lmt=1538709857331076&sparams=aitags%2Cclen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C271%2C278%2C313&ipbits=0&initcwndbps=1898750&source=youtube&keepalive=yes&ei=-zVHXMSBJ4PfgAfp5KqQBw&requiressl=yes&clen=445381081&dur=249.874&fvip=1&signature=0E9E6468C48202610BCA72066BE7DD698E4295EF.81587E87284E97AD9AAA2D2172A0D38F3C857FD5&ratebypass=yes'
[download] Destination: Genie in a Bottle - Christina Aguilera ('60s Style Cover) ft. Brielle Von Hugel-GW_gsNVM498.f313.webm
[download] 100% of 424.75MiB in 00:22
[debug] Invoking downloader on 'https://r1---sn-1gieen7e.googlevideo.com/videoplayback?mime=audio%2Fwebm&expire=1548192347&key=yt6&txp=5511222&c=WEB&gir=yes&mn=sn-1gieen7e%2Csn-1gi7znes&ip=2a05%3A41c0%3A7%3Aa00%3A8850%3Af0d5%3A7b45%3A6911&mm=31%2C29&itag=251&pl=29&mv=m&mt=1548170620&ms=au%2Crdu&id=o-AHV6_nQtC7Ya9i6qNIQte84twcJyBi6N6TN9JvjNBGxP&beids=9466588&lmt=1538710666354817&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&ipbits=0&initcwndbps=1898750&source=youtube&keepalive=yes&ei=-zVHXMSBJ4PfgAfp5KqQBw&requiressl=yes&clen=3890663&dur=249.901&fvip=1&signature=9EF4F90FC20BA95EFCDD6FB190261EAA49FB9843.5330BB6DA2A9E5A3D07214C31D85D24F38819A0F&ratebypass=yes'
[download] Destination: Genie in a Bottle - Christina Aguilera ('60s Style Cover) ft. Brielle Von Hugel-GW_gsNVM498.f251.webm
[download] 100% of 3.71MiB in 00:00
[ffmpeg] Merging formats into "Genie in a Bottle - Christina Aguilera ('60s Style Cover) ft. Brielle Von Hugel-GW_gsNVM498.webm"
[debug] ffmpeg command line: ffmpeg -y -i 'file:Genie in a Bottle - Christina Aguilera ('"'"'60s Style Cover) ft. Brielle Von Hugel-GW_gsNVM498.f313.webm' -i 'file:Genie in a Bottle - Christina Aguilera ('"'"'60s Style Cover) ft. Brielle Von Hugel-GW_gsNVM498.f251.webm' -c copy -map 0:v:0 -map 1:a:0 'file:Genie in a Bottle - Christina Aguilera ('"'"'60s Style Cover) ft. Brielle Von Hugel-GW_gsNVM498.temp.webm'
Deleting original file Genie in a Bottle - Christina Aguilera ('60s Style Cover) ft. Brielle Von Hugel-GW_gsNVM498.f313.webm (pass -k to keep)
Deleting original file Genie in a Bottle - Christina Aguilera ('60s Style Cover) ft. Brielle Von Hugel-GW_gsNVM498.f251.webm (pass -k to keep)
```

Using youtube-dl by providing my Google account credentials leads to a failure:
```
youtube-dl GW_gsNVM498 -f 313+251 -v
[debug] System config: []
[debug] User config: ['--netrc']
[debug] Custom config: []
[debug] Command-line args: ['GW_gsNVM498', '-f', '313+251', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.01.17
[debug] Python version 3.7.2 (CPython) - Linux-4.20.0-arch1-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 4.1, ffprobe 4.1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] Downloading login page
[youtube] Looking up account info
[youtube] Logging in
[youtube] Checking cookie
[youtube] GW_gsNVM498: Downloading webpage
[youtube] GW_gsNVM498: Downloading video info webpage
[youtube] {18} signature length 110, html5 player vfl-jbnrr
[youtube] {36} signature length 110, html5 player vfl-jbnrr
[youtube] {17} signature length 110, html5 player vfl-jbnrr
[youtube] {313} signature length 110, html5 player vfl-jbnrr
[youtube] {271} signature length 106, html5 player vfl-jbnrr
[youtube] {137} signature length 106, html5 player vfl-jbnrr
[youtube] {248} signature length 110, html5 player vfl-jbnrr
[youtube] {136} signature length 110, html5 player vfl-jbnrr
[youtube] {247} signature length 110, html5 player vfl-jbnrr
[youtube] {135} signature length 106, html5 player vfl-jbnrr
[youtube] {244} signature length 106, html5 player vfl-jbnrr
[youtube] {134} signature length 110, html5 player vfl-jbnrr
[youtube] {243} signature length 110, html5 player vfl-jbnrr
[youtube] {133} signature length 110, html5 player vfl-jbnrr
[youtube] {242} signature length 110, html5 player vfl-jbnrr
[youtube] {160} signature length 106, html5 player vfl-jbnrr
[youtube] {278} signature length 110, html5 player vfl-jbnrr
[youtube] {140} signature length 110, html5 player vfl-jbnrr
[youtube] {171} signature length 106, html5 player vfl-jbnrr
[youtube] {249} signature length 110, html5 player vfl-jbnrr
[youtube] {250} signature length 110, html5 player vfl-jbnrr
[youtube] {251} signature length 110, html5 player vfl-jbnrr
[debug] Invoking downloader on 'https://r1---sn-1gieen7e.googlevideo.com/videoplayback?ipbits=0&lsparams=mn%2Cmm%2Cinitcwndbps%2Cpl%2Cms%2Cmv&txp=5532432&mm=31%2C29&mn=sn-1gieen7e%2Csn-1gi7znes&itag=313&clen=445381081&requiressl=yes&pl=29&ip=2a05%3A41c0%3A7%3Aa00%3A8850%3Af0d5%3A7b45%3A6911&mime=video%2Fwebm&keepalive=yes&dur=249.874&expire=1548192299&source=youtube&lmt=1538709857331076&id=o-AN6e7c4U-x4K4GCvADYhDM2f7RyhXNvlZsZuzphWl4sq&ei=yjVHXMCnMJOpgAflq4LADw&ms=au%2Crdu&mt=1548170620&mv=m&sparams=expire%2Cei%2Cip%2Clmt%2Cgir%2Csource%2Cid%2Crequiressl%2Citag%2Ckeepalive%2Cclen%2Cmime%2Cipbits%2Cdur%2Caitags&c=WEB&pbrmi=600&fvip=1&gir=yes&lsig=ANVabiowRAIgEfUN8HzbCkmn5I9dW-lN_3bQJY5Kg7oJ8igqqLZoawsCIDBAg-j7mHwhkKBfg7p0oERaNRgaiHOAuA1iOwBFkanz&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C271%2C278%2C313&initcwndbps=1898750&signature=AMao4c4wRQIgcRqjdLb1zOzeS699Jm4Y9hfTCEQgMjMfD3NE30hU0y0CIQCx5BQDPcZvSLQZc4lOKaePXMP887665WOxadw7ASq5EA==&ratebypass=yes'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 1903, in process_info
    partial_success = dl(fname, new_info)
  File "/usr/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 1848, in dl
    return fd.download(name, info)
  File "/usr/lib/python3.7/site-packages/youtube_dl/downloader/common.py", line 364, in download
    return self.real_download(filename, info_dict)
  File "/usr/lib/python3.7/site-packages/youtube_dl/downloader/http.py", line 341, in real_download
    establish_connection()
  File "/usr/lib/python3.7/site-packages/youtube_dl/downloader/http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 2212, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by goggle** [comment]
@dstftw Where is the original issue report? I could not find it...

**Comment by dstftw** [comment]
#18841.
