### ISSUE TITLE
Format selection broken

### ISSUE THREAD

**Issue by treelimb330** [rg3/youtube-dl#18961]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.01.23*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.01.23**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: [u'-f', u'(bestvideo+bestaudio/best)[ext!=webm]', u'--restrict-filenames', u'--no-part', u'-o', u'***', u'--cookies', u'***']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--mark-watched', u'https://www.youtube.com/playlist?list=WL']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.01.23
[debug] Python version 2.7.13 (CPython) - Linux-4.9.0-8-amd64-x86_64-with-debian-9.6
[debug] exe versions: ffmpeg 3.2.12-1, ffprobe 3.2.12-1
[debug] Proxy map: {}
[youtube:watchlater] WL: Downloading webpage
[download] Downloading playlist: Watch Later Playlist
[youtube:watchlater] playlist Watch Later Playlist: Downloading 3 videos
[download] Downloading video 1 of 3
[youtube] ***: Downloading webpage
[youtube] ***: Downloading video info webpage
[youtube] ***: Marking watched
ERROR: requested format not available
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 804, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 858, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1631, in process_video_result
    expected=True)
ExtractorError: requested format not available
```

---

### Description of your *issue*, suggested solution and other information

The previously valid format selection of `(bestvideo+bestaudio/best)[ext!=webm]` no longer is valid since yesterday's release. Removing the `[ext!=webm]` avoids the error and shows it was rejecting a video of mp4 video and m4a audio [[link]](https://www.youtube.com/watch?v=GoQG6Tin-1E&t). After commit 2cc779f497ae20d6e0e28fc546a25723cfea631a, `!=` looks like it should still be valid per the updated documentation.

**Comment by treelimb330** [comment]
Noticed that the unit tests don't rule out that the negation change doesn't just reject everything.
