### ISSUE TITLE
ERROR: Unsupported URL: https://oload.club

### ISSUE THREAD

**Issue by mattyicer** [rg3/youtube-dl#18971]
I've verified and I assure that I'm running youtube-dl 2019.01.24
  At least skimmed through README and most notably FAQ and BUGS sections
  Searched the bugtracker for similar issues including closed ones
What is the purpose of your issue?
  Bug report (encountered problems with youtube-dl)
Full verbose output:
-bash-4.1# youtube-dl --version
2019.01.23

[root@mmdc ~]$ youtube-dl --verbose https://oload.club/f/Nr1L-aZ2dbQ
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://oload.club/f/Nr1L-aZ2dbQ']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.01.23
[debug] Python version 2.7.10 (CPython) - Darwin-17.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1, ffprobe 4.1, phantomjs 2.1.1
[debug] Proxy map: {}
[generic] Nr1L-aZ2dbQ: Requesting header
WARNING: Falling back on generic information extractor.
[generic] Nr1L-aZ2dbQ: Downloading webpage
[generic] Nr1L-aZ2dbQ: Extracting information
ERROR: Unsupported URL: https://oload.club/f/Nr1L-aZ2dbQ
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2337, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2542, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2531, in _XML
    parser.feed(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 18, column 11
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 793, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3320, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://oload.club/f/Nr1L-aZ2dbQ

Description of issue
youtube-dl outputs ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug error when trying to download links on Oload.cloud (Openload) videos.

Video used in this example - https://oload.club/f/Nr1L-aZ2dbQ

Seems to be the case for all videos I've tested on the site

**Comment by mattyicer** [comment]
why are you deleting/closing the issue?
