### ISSUE TITLE
Vivo download isn't working

### ISSUE THREAD

**Issue by SernS** [rg3/youtube-dl#18973]
youtube-dl is up-to-date (2019.01.24)

crt@crt:~$ youtube-dl --verbose "https://vivo.sx/d30356ee1d"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://vivo.sx/d30356ee1d']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.01.24
[debug] Python version 2.7.15rc1 (CPython) - Linux-4.15.0-43-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.4, ffprobe 3.4.4, rtmpdump 2.4
[debug] Proxy map: {}
[Vivo] d30356ee1d: Downloading webpage
WARNING: unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 472, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 462, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2005, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 793, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 508, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/shared.py", line 26, in _real_extract
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2938, in compat_b64decode
  File "/usr/lib/python2.7/base64.py", line 75, in b64decode
    return binascii.a2b_base64(s)
TypeError: a2b_base64() argument 1 must be string or buffer, not None

**Comment by reglos** [comment]
still have the same issue on youtube-dl version 2019.03.09
It is *not* a duplicate to previously patched vivo issues
