### ISSUE TITLE
ERROR: Signature extraction failed: Traceback (most recent call last)

### ISSUE THREAD

**Issue by ddimka** [rg3/youtube-dl#18998]
Hi.

youtube-dl -U returning 
**youtube-dl is up-to-date (2019.01.24)**

In last version I get:

Error getting video url: Error: Command failed: /var/www/back/node_modules/youtube-dl/bin/youtube-dl --dump-json --force-ipv4 --format=18 http://www.youtube.com/watch?v=k4YRWT_Aldo

ERROR: Signature extraction failed: Traceback (most recent call last):
File "/var/www/telll/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1225, in _decrypt_signature
video_id, player_url, s

File "/var/www/telll/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1133, in _extract_signature_function
res = self._parse_sig_js(code)

File "/var/www/telll/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1200, in _parse_sig_js
initial_function = jsi.extract_function(funcname)

File "/var/www/telll/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/jsinterp.py", line 245, in extract_function
raise ExtractorError('Could not find JS function %r' % funcname)

ExtractorError: Could not find JS function u'encodeURIComponent'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError(u"Could not find JS function u'encodeURIComponent'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Can someone help?

**Comment by ddimka** [comment]
I'm sorry.

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.01.24
[debug] Python version 2.7.12 (CPython) - Linux-4.4.0-1035-aws-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 3.3.2-1, ffprobe 3.3.2-1, rtmpdump 2.4
[debug] Proxy map: {}
Usage: youtube-dl [OPTIONS] URL [URL...]

**Comment by dstftw** [comment]
Again: carefully read the issue template.

**Comment by ddimka** [comment]
youtube-dl -v http://www.youtube.com/watch?v=NoNrPUg8e-0
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=NoNrPUg8e-0']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.01.24
[debug] Python version 2.7.12 (CPython) - Linux-4.4.0-1035-aws-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 3.3.2-1, ffprobe 3.3.2-1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] NoNrPUg8e-0: Downloading webpage
[youtube] NoNrPUg8e-0: Downloading video info webpage
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[download] Батя и сын смотрят «ШТИРЛИЦ» – КТО ХОРОШИЙ – самый обсуждаемый номер Дизель Шоу _ ЮМОР ICTV-NoNrPUg8e-0.mkv has already been downloaded and merged
