### ISSUE TITLE
Issue 'no video formats found' when downloading from 6ter replay (uses 6play.fr)

### ISSUE THREAD

**Issue by net-tools** [rg3/youtube-dl#19016]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.01.24*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2019.01.24**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.6play.fr/renovation-impossible-p_6410/se-mettre-au-verre-c_12254075']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.01.24
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: none
[debug] Proxy map: {}
[6play] 12254075: Downloading JSON metadata
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpa8aoq3sz\build\youtube_dl\YoutubeDL.py", line 793, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpa8aoq3sz\build\youtube_dl\extractor\common.py", line 508, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpa8aoq3sz\build\youtube_dl\extractor\sixplay.py", line 107, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpa8aoq3sz\build\youtube_dl\extractor\common.py", line 1302, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

---

### Description of your *issue*, suggested solution and other information

When downloading from 6play.fr, videos from 6ter TV can't be downloaded ("no video formats found"). However, when viewing it from the browser (with same URL), it works.

For your information, 6play.fr host videos for several French TV channels : m6, w9, and 6ter. Replays from m6 are working fine (for example : https://www.6play.fr/turbo-p_884/emission-du-20-janvier-c_12261497) but those from 6ter don't (https://www.6play.fr/renovation-impossible-p_6410/se-mettre-au-verre-c_12254075). 

URL seems identical in their syntax, I had a look in manifest files through Chrome developer console, they also look alike (except for video titles, of course). 

This issue should be debugged directly in py files, but this is not something I'm used to.

Thanks.

**Comment by net-tools** [comment]
Ok, maybe this is a duplicate, but from which # issue here ? Didn't find anything mentioning exactly my issue (m6 ok, 6ter ko). Is there a workaround ? 
Please provide here the link to the duplicate post, so that I could learn more about that. Thanks
