### ISSUE TITLE
Add britbox

### ISSUE THREAD

**Issue by jtc242** [rg3/youtube-dl#19010]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.01.24*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2019.01.24**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl  https://www.britbox.com/us/episode/Doctor_Who_S14_E22_7466 -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.britbox.com/us/episode/Doctor_Who_S14_E22_7466', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.01.24
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-93001-g87c165c237, ffprobe N-93001-g87c165c237
[debug] Proxy map: {}
[generic] Doctor_Who_S14_E22_7466: Requesting header
WARNING: Falling back on generic information extractor.
[generic] Doctor_Who_S14_E22_7466: Downloading webpage
[generic] Doctor_Who_S14_E22_7466: Extracting information
ERROR: Unsupported URL: https://www.britbox.com/us/episode/Doctor_Who_S14_E22_7466
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpa8aoq3sz\build\youtube_dl\YoutubeDL.py", line 793, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpa8aoq3sz\build\youtube_dl\extractor\common.py", line 508, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpa8aoq3sz\build\youtube_dl\extractor\generic.py", line 3320, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.britbox.com/us/episode/Doctor_Who_S14_E22_7466
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.britbox.com/us/episode/Doctor_Who_S4_E7_14566
- Single video: https://www.britbox.com/us/episode/Doctor_Who_S1_E1_8031
- Playlist: https://www.britbox.com/us/season/Doctor_Who_S4_12799
- Playlist: https://www.britbox.com/us/show/5969

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

I tried to add this myself but I am unable to find the proper url. Thanks

**Comment by jtc242** [comment]
I can provide login with temporary password if needed.

**Comment by jtc242** [comment]
Just sent credentials to your gmail account

**Comment by jtc242** [comment]
FYI I am able to download them one at a time using chrome extension Stream Video Downloader but that is the only way I have been able to do so.

**Comment by jtc242** [comment]
I am changing my credentials back. Let me know if/when you need the account and I will let you know the login info.

**Comment by warren-bank** [comment]
fwiw, this website looks an awful lot like that of the BBC iPlayer. My Britbox account is expired, so I can't confirm that their javascript player is identical.. but since Britbox is operated (at least in part) by the BBC.. there's a very fair chance of this. In which case, the extractor for the [BBC iPlayer](https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/extractor/bbc.py) should be a very good starting point for modification.

**Comment by Matt14451** [comment]
Launched in UK today, does it work with youtube-dl?

**Comment by timethrow** [comment]
> Launched in UK today, does it work with youtube-dl? Will start a free trial when it works

Could be wrong but it looks like it uses Widevine DRM, if so will be unlikely to get an extractor for this

**Comment by Matt14451** [comment]
> > Launched in UK today, does it work with youtube-dl? Will start a free trial when it works
> 
> Could be wrong but it looks like it uses Widevine DRM, if so will be unlikely to get an extractor for this

Shame

**Comment by Dmole** [comment]
> FYI I am able to download them one at a time using chrome extension Stream Video Downloader but that is the only way I have been able to do so.

@jtc242 please share a URL.

**Comment by 89z** [comment]
Issue should be closed, URL is dead

**Comment by Dmole** [comment]
> Issue should be closed, URL is dead

Or just update the URL

Playlist: https://www.britbox.com/ca/show/Doctor_Who_b006q2x0

**Comment by 89z** [comment]
Template asks for single video, so that URL is not valid.
