### ISSUE TITLE
German umlaut - unable to open for writing: [Errno 22] invalid mode ('wb') or filename: ...

### ISSUE THREAD

**Issue by ABihler** [rg3/youtube-dl#19043]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.01.27*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.01.27**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
--> found https://github.com/rg3/youtube-dl/issues/14607 but there was no solution or usefull hint. I tried option --restrict-filenames but it gave youtube-dl: error: no such option: --restrict-filenames.
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
It starts downloading the playlist but stopps on video 6 of 17. Maybe due to German umlaut in title. This is on Raspbian.
Here is the output:
```
pi@leda:/media/usb0/Mia/Laura $ youtube-dl --version
2019.01.27
pi@leda:/media/usb0/Mia/Laura $ youtube-dl -v --restrict-filenames. https://youtu.be/Iq02vOmvVL4?list=PL2Vo0h1bDpsoXkxNa44j9Am8Ibf66YWZO
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: no such option: --restrict-filenames.
pi@leda:/media/usb0/Mia/Laura $ youtube-dl -v https://youtu.be/Iq02vOmvVL4?list=PL2Vo0h1bDpsoXkxNa44j9Am8Ibf66YWZO
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://youtu.be/Iq02vOmvVL4?list=PL2Vo0h1bDpsoXkxNa44j9Am8Ibf66YWZO']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.01.27
[debug] Python version 2.7.13 (CPython) - Linux-4.9.59+-armv6l-with-debian-9.6
[debug] exe versions: none
[debug] Proxy map: {}
[youtube:playlist] Downloading playlist PL2Vo0h1bDpsoXkxNa44j9Am8Ibf66YWZO - add --no-playlist to just download video Iq02vOmvVL4
[youtube:playlist] PL2Vo0h1bDpsoXkxNa44j9Am8Ibf66YWZO: Downloading webpage
[download] Downloading playlist: Lauras Stern Staffel 3 deutsch Ganze Folgen
[youtube:playlist] playlist Lauras Stern Staffel 3 deutsch Ganze Folgen: Downloading 17 videos
[download] Downloading video 1 of 17
[youtube] JjSiE8QHKEo: Downloading webpage
[youtube] JjSiE8QHKEo: Downloading video info webpage
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on u'https://r2---sn-oxujvavbox-jboz.googlevideo.com/videoplayback?ip=2a0a%3Aa541%3A9669%3A0%3Ae7d5%3Ac10%3A9428%3A1de&pl=29&mv=m&mt=1548692135&ms=au%2Crdu&ei=FytPXKX6A9OG8gOjq4fwAg&mn=sn-oxujvavbox-jboz%2Csn-4g5e6nsy&mm=31%2C29&id=o-AG6kY4tn3bRyqdBdeUMcnKOcggcI_fdLbdzeaJiOZqMI&expire=1548713847&itag=18&fvip=2&ratebypass=yes&requiressl=yes&dur=698.734&source=youtube&lmt=1473136258721702&key=yt6&signature=7689C318B2B6513DFF49427F8430CA9D7CA68F49.8E23CC9E78D346186ECE08F79C3DEFE2B647EE7B&gir=yes&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&clen=36156290&mime=video%2Fmp4&c=WEB&ipbits=0&initcwndbps=1418750'
[download] Lauras Stern Staffel 3 Folge 1 Der Teddyforscher deutsch ganze Folge-JjSiE8QHKEo.mp4 has already been downloaded
[download] 100% of 34.48MiB
[download] Downloading video 2 of 17
[youtube] Lz1fj0DlJvc: Downloading webpage
[youtube] Lz1fj0DlJvc: Downloading video info webpage
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on u'https://r3---sn-oxujvavbox-jboz.googlevideo.com/videoplayback?id=o-AA27f4-2kf4G6gio5gWUeysC7B04zg80bOtUb6EdI6X5&mm=31%2C29&mn=sn-oxujvavbox-jboz%2Csn-4g5ednsz&ei=HStPXMLgL8i_gAesuqGQCw&ms=au%2Crdu&ipbits=0&pl=29&mv=m&signature=99D703B2DDB70664516FC2AA0763D235771B4FF1.84A39B977B3145AA2573AF660AB2F42541B6FD34&ip=2a0a%3Aa541%3A9669%3A0%3Ae7d5%3Ac10%3A9428%3A1de&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&source=youtube&txp=5531432&itag=18&mime=video%2Fmp4&gir=yes&key=yt6&requiressl=yes&initcwndbps=1418750&expire=1548713854&ratebypass=yes&dur=680.971&lmt=1542470253843957&c=WEB&fvip=3&clen=34633556&mt=1548692135'
[download] Lauras Stern Staffel 3 Folge 2 Das neue Rad deutsch ganze Folge-Lz1fj0DlJvc.mp4 has already been downloaded
[download] 100% of 33.03MiB
[download] Downloading video 3 of 17
[youtube] UQAxaZ37olw: Downloading webpage
[youtube] UQAxaZ37olw: Downloading video info webpage
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on u'https://r2---sn-oxujvavbox-jbol.googlevideo.com/videoplayback?gir=yes&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&lmt=1469644242857643&ei=JStPXKP0FpH_gAfGsrq4DA&initcwndbps=1283750&dur=677.976&fvip=6&signature=09DAEE5CE2B179A043E34CC6C350C6626B5726E5.2F4E4EB92CDE6A6289C549AB1E164802DB265E1F&key=yt6&ratebypass=yes&ipbits=0&clen=35948664&itag=18&c=WEB&requiressl=yes&mime=video%2Fmp4&ip=2a0a%3Aa541%3A9669%3A0%3Ae7d5%3Ac10%3A9428%3A1de&mm=31%2C29&source=youtube&pl=29&mn=sn-oxujvavbox-jbol%2Csn-4g5edne7&id=o-APcI6s-Hfn3c3xnYray7QMszj_kCVt4iVZp1zUcVZxQl&ms=au%2Crdu&mt=1548692135&mv=m&expire=1548713861'
[download] Lauras Stern Staffel 3 Folge 3 Der Malwettbewerb deutsch ganze Folge-UQAxaZ37olw.mp4 has already been downloaded
[download] 100% of 34.28MiB
[download] Downloading video 4 of 17
[youtube] IWJAWCjmzU8: Downloading webpage
[youtube] IWJAWCjmzU8: Downloading video info webpage
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on u'https://r1---sn-oxujvavbox-jboz.googlevideo.com/videoplayback?signature=83D479A3EB6BC1D2B422C688A9563E295D01CA48.A58067B976D883D06FF3AAF1608BEEF6F1F6624F&key=yt6&gir=yes&requiressl=yes&dur=666.668&source=youtube&lmt=1469776784720612&c=WEB&ipbits=0&initcwndbps=1418750&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&mime=video%2Fmp4&mn=sn-oxujvavbox-jboz%2Csn-4g5e6ney&mm=31%2C29&id=o-AEqmphrsclSqZMPCNdSgSsogN8eC9Kd4f5r4Q0c47ORg&clen=34681326&ip=2a0a%3Aa541%3A9669%3A0%3Ae7d5%3Ac10%3A9428%3A1de&pl=29&mv=m&mt=1548692135&ms=au%2Crdu&ei=LCtPXNPSJpXR1wK3g46oBw&fvip=1&ratebypass=yes&expire=1548713868&itag=18'
[download] Lauras Stern Staffel 3 Folge 4 Laura verirrt sich deutsch ganze Folge-IWJAWCjmzU8.mp4 has already been downloaded
[download] 100% of 33.07MiB
[download] Downloading video 5 of 17
[youtube] aQxOugx9AiM: Downloading webpage
[youtube] aQxOugx9AiM: Downloading video info webpage
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on u'https://r1---sn-oxujvavbox-jboe.googlevideo.com/videoplayback?txp=5431432&initcwndbps=1290000&c=WEB&expire=1548713875&ei=MytPXOimG9HngQfPuqLYCw&key=yt6&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&mn=sn-oxujvavbox-jboe%2Csn-4g5e6nez&ip=2a0a%3Aa541%3A9669%3A0%3Ae7d5%3Ac10%3A9428%3A1de&mm=31%2C29&requiressl=yes&ms=au%2Crdu&itag=18&pl=29&mt=1548692135&dur=710.623&id=o-AI4XazemgbSeqwxvjcBbFGY_yGogGBMVFHXgWLLYQUYL&mv=m&ipbits=0&gir=yes&lmt=1541474875012452&signature=75B11DC792E3109B0900CDCD915B1810C77C707C.7FF729CBA69FFF83B940B6AFBF9F938F992CD725&source=youtube&ratebypass=yes&mime=video%2Fmp4&fvip=2&clen=39655405'
[download] Lauras Stern Staffel 3 Folge 5 Wo ist Fiffi deutsch ganze Folge-aQxOugx9AiM.mp4 has already been downloaded
[download] 100% of 37.82MiB
[download] Downloading video 6 of 17
[youtube] 73qGkfi7AZ0: Downloading webpage
[youtube] 73qGkfi7AZ0: Downloading video info webpage
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on u'https://r3---sn-oxujvavbox-jbos.googlevideo.com/videoplayback?mn=sn-oxujvavbox-jbos%2Csn-4g5edned&expire=1548713882&mm=31%2C29&id=o-AJWOlpUPq1XoP0-7rJ6zrnyTOmzGGJShaVknyH2UR_UF&ip=2a0a%3Aa541%3A9669%3A0%3Ae7d5%3Ac10%3A9428%3A1de&mv=m&pl=29&ipbits=0&ms=au%2Crdu&ei=OitPXLLCI5WvgQfg35DICA&fvip=3&c=WEB&lmt=1541911152563902&dur=710.368&ratebypass=yes&clen=36906283&key=yt6&gir=yes&mime=video%2Fmp4&mt=1548692135&initcwndbps=1255000&requiressl=yes&signature=5F773FC3133D09FA2B2FD63DC8B25ED28F9A1B57.3E29B4530044C4DB841253BAAC5051A3B7C80231&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&source=youtube&itag=18&txp=5531432'
ERROR: unable to open for writing: [Errno 22] invalid mode ('wb') or filename: 'Lauras Stern Staffel 3 Folge 7 Der R\xc3\xa4uber deutsch ganze Folge-73qGkfi7AZ0.mp4.part'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 250, in download
    ctx.tmpfilename, ctx.open_mode)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 458, in sanitize_open
    stream = open(encodeFilename(filename), open_mode)
IOError: [Errno 22] invalid mode ('wb') or filename: 'Lauras Stern Staffel 3 Folge 7 Der R\xc3\xa4uber deutsch ganze Folge-73qGkfi7AZ0.mp4.part'



...
<end of log>
```

**Comment by dstftw** [comment]
Most likely your fs does not support this.

**Comment by ABihler** [comment]
The --restrict-filenames option actually works. Thanks for the hint. There was a copy paste error in the command.
