### ISSUE TITLE
[Crunchyroll] Premium only videos not working.

### ISSUE THREAD

**Issue by skid9000** [rg3/youtube-dl#19070]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.01.30.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

```
E:\youtube-dl\live>E:\youtube-dl\youtube-dl.exe --cookies C:\ProgramData\Crunchy-DL\cookies.txt --write-sub --sub-lang frFR --sub-format ass --verbose https://www.crunchyroll.com/mob-psycho-100/episode-4-inside-evil-spirit-780923
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--cookies', 'C:\\ProgramData\\Crunchy-DL\\cookies.txt', '--write-sub', '--sub-lang', 'frFR', '--sub-format', 'ass', '--verbose', 'https://www.crunchyroll.com/mob-psycho-100/episode-4-inside-evil-spirit-780923']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.01.30.1
[debug] Python version 3.4.4 (CPython) - Windows-2012Server-6.2.9200-SP0
[debug] exe versions: ffmpeg N-86848-g03a9e6f, ffprobe N-86848-g03a9e6f
[debug] Proxy map: {}
[crunchyroll] 780923: Downloading webpage
ERROR: Ceci est un extrait. Pour visionner la vidéo en entier,  testez gratuitement notre offre !!; please report this issue on https://yt-dl.org/bug . 
Make sure you are using the latest version; type  youtube-dl -U  to update. 
Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp36zpl0n4\build\youtube_dl\YoutubeDL.py", line 793, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp36zpl0n4\build\youtube_dl\extractor\common.py", line 508, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp36zpl0n4\build\youtube_dl\extractor\crunchyroll.py", line 436, in _real_extract
youtube_dl.utils.ExtractorError: Ceci est un extrait. Pour visionner la vidéo en entier,  testez gratuitement notre offre !!; 
please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. 
Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.crunchyroll.com/mob-psycho-100/episode-4-inside-evil-spirit-780923

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Someone reported to me [this](https://github.com/skid9000/Crunchyroll-Downloader/issues/26)
So i tried and it broke only when i try to download premium only videos... 
Otherwise, i can download other videos in 1080p normally

**Comment by remitamine** [comment]
```
youtube-dl --cookies ~/Downloads/cookies.txt https://www.crunchyroll.com/mob-psycho-100/episode-4-inside-evil-spirit-780923
[crunchyroll] 780923: Downloading webpage
[crunchyroll] 780923: Downloading audio-jaJP-hardsub-ruRU m3u8 information
[crunchyroll] 780923: Downloading audio-jaJP-hardsub-itIT m3u8 information
[crunchyroll] 780923: Downloading audio-jaJP-hardsub-arME m3u8 information
[crunchyroll] 780923: Downloading audio-jaJP m3u8 information
[crunchyroll] 780923: Downloading audio-jaJP-hardsub-esES m3u8 information
[crunchyroll] 780923: Downloading audio-jaJP-hardsub-frFR m3u8 information
[crunchyroll] 780923: Downloading audio-jaJP-hardsub-deDE m3u8 information
[crunchyroll] 780923: Downloading audio-jaJP-hardsub-esLA m3u8 information
[crunchyroll] 780923: Downloading audio-jaJP-hardsub-enUS m3u8 information
[crunchyroll] 780923: Downloading audio-jaJP-hardsub-ptBR m3u8 information
[crunchyroll] 780923: Downloading media info
[download] Destination: Mob Psycho 100 II Episode 4 – Inside ~Evil Spirit~-780923.mp4
ffmpeg version n4.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 8.2.1 (GCC) 20181127
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-nvdec --enable-nvenc --enable-omx --enable-shared --enable-version3
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
[hls,applehttp @ 0x55c1ac716000] Opening 'https://v.vrv.co/evs/7af4e6aad582da45e1c2af3dac1446b3/assets/129100baa0c0b3eefd54b629b2f19c18_3619924.mp4/encryption.key?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly92LnZydi5jby9ldnMvN2FmNGU2YWFkNTgyZGE0NWUxYzJhZjNkYWMxNDQ2YjMvYXNzZXRzLzEyOTEwMGJhYTBjMGIzZWVmZDU0YjYyOWIyZjE5YzE4XzM2MTk5MjQubXA0LyoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE1NDg5MjUxMDZ9fX1dfQ__&Signature=VjY8SUjBSCoSHyNd~4YC8DsEH~iRlUglWvmFlYWo6DYyUL1VNPi~53WynLFaedmflbH2P1cWE1dPE54SBsRUx07NV5lscrWN2wY2WOsErFlmmnMKYNfFzuyxmq5J8NVHJZacrMwxPHgFAO24TZ045qrlVeVld84kSuH8LTWCWVI2gr9xQR48ZX9~HmfYh8CaSxFtq1q2mNH9mnc2omgrIsJJgNDv8Ypj9yy9L6kZWiFu2zbFGVQXenxxQdKjjutJQvG1TYDqOI3eDKmXmoJKfLl4B51MWboMaGLAQDGck6di4YaLeE9DmmbckBxhkG152lDIIoGftE2Vtu6dTQsMHA__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA' for reading
[hls,applehttp @ 0x55c1ac716000] Opening 'crypto+https://v.vrv.co/evs/7af4e6aad582da45e1c2af3dac1446b3/assets/129100baa0c0b3eefd54b629b2f19c18_3619924.mp4/seg-1-v1-a1.ts?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly92LnZydi5jby9ldnMvN2FmNGU2YWFkNTgyZGE0NWUxYzJhZjNkYWMxNDQ2YjMvYXNzZXRzLzEyOTEwMGJhYTBjMGIzZWVmZDU0YjYyOWIyZjE5YzE4XzM2MTk5MjQubXA0LyoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE1NDg5MjUxMDZ9fX1dfQ__&Signature=VjY8SUjBSCoSHyNd~4YC8DsEH~iRlUglWvmFlYWo6DYyUL1VNPi~53WynLFaedmflbH2P1cWE1dPE54SBsRUx07NV5lscrWN2wY2WOsErFlmmnMKYNfFzuyxmq5J8NVHJZacrMwxPHgFAO24TZ045qrlVeVld84kSuH8LTWCWVI2gr9xQR48ZX9~HmfYh8CaSxFtq1q2mNH9mnc2omgrIsJJgNDv8Ypj9yy9L6kZWiFu2zbFGVQXenxxQdKjjutJQvG1TYDqOI3eDKmXmoJKfLl4B51MWboMaGLAQDGck6di4YaLeE9DmmbckBxhkG152lDIIoGftE2Vtu6dTQsMHA__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA' for reading
Input #0, hls,applehttp, from 'https://v.vrv.co/evs/7af4e6aad582da45e1c2af3dac1446b3/assets/129100baa0c0b3eefd54b629b2f19c18_3619924.mp4/index-v1-a1.m3u8?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly92LnZydi5jby9ldnMvN2FmNGU2YWFkNTgyZGE0NWUxYzJhZjNkYWMxNDQ2YjMvYXNzZXRzLzEyOTEwMGJhYTBjMGIzZWVmZDU0YjYyOWIyZjE5YzE4XyoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE1NDg5MjUxMDZ9fX1dfQ__&Signature=rHt0VCWJjDlq1BaXQLjD3tEkUrsEpKQBJN7bzzwOoc8iBoV42UN2x8~epABMZEk-~SnNblWyKfJ~GTF9f4b7JwjEu0x4BMVZ1fY-7OtoEccCPU2fG3YOCtz4VKwCWFxHWtHV8OQhHachs19XX8O9Iyx2OEB0AyTX7HTg1X0TXmZJe3Z77OY8zNGIfRwtJme1pZfpIjZy8TbpPMo~cYK~KhZVCy9NPpm5aPpE5xokjIExIXCgfLPiP7wxJYrYB-~3WCvgcnu84yjGjoxlWJdAlN5K9Mivq5T9aoRi1Y7XCFKdAykA07gUdOJqZCKVWFZ5-~XRrcH-9e-UfjXC-9uWTw__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA':
  Duration: 00:24:10.07, start: 0.101000, bitrate: N/A
  Program 0 
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 90k tbn, 47.95 tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
    Stream #0:2: Data: timed_id3 (ID3  / 0x20334449)
    Metadata:
      variant_bitrate : 0
Output #0, mp4, to 'file:Mob Psycho 100 II Episode 4 – Inside ~Evil Spirit~-780923.mp4.part':
  Metadata:
    encoder         : Lavf58.20.100
    Stream #0:0: Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], q=2-31, 23.98 fps, 23.98 tbr, 90k tbn, 90k tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=   49 fps=0.0 q=-1.0 size=     256kB time=00:00:02.00 bitrate=1047.7kbits
```

**Comment by skid9000** [comment]
Then why can i download other vids in 1080p ? :/
