### ISSUE TITLE
vshare.io error 404

### ISSUE THREAD

**Issue by grill02** [rg3/youtube-dl#19164]
Several vshare.io videos of the form https://vshare.io/v/video-id fail ( for various values of video-id). 
It works fine via a web browser. But plain wget gives a 404. Maybe its something to do with auth?
For example:

``
```
youtube-dl -F vshare.io/v/ccahbnt --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-F', u'vshare.io/v/ccahbnt', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.01.30.1
[debug] Python version 2.7.13 (CPython) - Linux-4.9.0-6-amd64-x86_64-with-debian-9.3
[debug] exe versions: none
[debug] Proxy map: {}
WARNING: The url doesn't specify the protocol, trying with http
[VShare] ccahbnt: Downloading webpage
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/f/furt/.python_scripts/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 793, in extract_info
    ie_result = ie.extract(url)
  File "/home/f/furt/.python_scripts/bin/youtube-dl/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/home/f/furt/.python_scripts/bin/youtube-dl/youtube_dl/extractor/vshare.py", line 54, in _real_extract
    r'<title>([^<]+)</title>', webpage, 'title')
  File "/home/f/furt/.python_scripts/bin/youtube-dl/youtube_dl/extractor/common.py", line 992, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/home/f/furt/.python_scripts/bin/youtube-dl/youtube_dl/extractor/common.py", line 983, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

**Comment by alexvong1995** [comment]
Are you sure https://vshare.io/v/ccahbnt is viewable on a browser?

I got a 404:
![ccahbnt](https://user-images.githubusercontent.com/10696787/52441516-c645eb00-2b5b-11e9-83e2-8dc6b5604020.png)
