### ISSUE TITLE
This error frequently occurs when downloading YouTube videos

### ISSUE THREAD

**Issue by wudisk** [rg3/youtube-dl#19186]
C:\Users\sk1\Desktop\youtube>youtube-dl -v -f 136+140 --write-auto-sub --sub-lang zh-Hans --sub-format vtt --convert-subtitles srt -o tuXENvKPrFY.mp4 https://www.youtube.com/watch?v=tuXENvKPrFY
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-f', '136+140', '--write-auto-sub', '--sub-lang', 'zh-Hans', '--sub-format', 'vtt', '--convert-subtitles', 'srt', '-o', 'tuXENvKPrFY.mp4', 'https://www.youtube.com/watch?v=tuXENvKPrFY']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2019.01.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg N-92714-g436bffaca2, ffprobe N-92714-g436bffaca2
[debug] Proxy map: {'ftp': 'ftp://127.0.0.1:6666', 'http': 'http://127.0.0.1:6666', 'https': 'https://127.0.0.1:6666'}
[youtube] tuXENvKPrFY: Downloading webpage
[youtube] tuXENvKPrFY: Downloading video info webpage
[youtube] tuXENvKPrFY: Looking for automatic captions
[info] Writing video subtitles to: tuXENvKPrFY.zh-Hans.vtt
[debug] Invoking downloader on 'https://r4---sn-i3beln7d.googlevideo.com/videoplayback?beids=9466588&dur=201.901&mm=31%2C29&expire=1549818745&key=yt6&ip=35.220.142.181&lmt=1549773814318951&fvip=6&source=youtube&id=o-AEC4fQ_W6u3QcrJLa1DNn6GJiDOdpIO3CwJ-rE-wH4T_&ipbits=0&sparams=aitags%2Cclen%2Cdur%2Cei%2Cgir%2Cid%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&signature=26E3B15B53DAEC0F8CD1EA450B83399F3FAA7E4D.C3EFD3074399B0DAFCD3A955BF83B29FE5588646&mime=video%2Fmp4&itag=136&txp=2316222&pl=23&aitags=133%2C134%2C135%2C136%2C137%2C160&keepalive=yes&c=WEB&gir=yes&clen=42901660&mn=sn-i3beln7d%2Csn-i3b7kn7s&ei=GQdgXPWKDIOUgAO08a6oDA&ms=au%2Crdu&mt=1549797049&mv=m&requiressl=yes&ratebypass=yes'
[download] Destination: tuXENvKPrFY.f136.mp4
[download]  25.2% of 40.91MiB at 242.57KiB/s ETA 02:09  ERROR: unable to download video data: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1748)
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpgf__qgjd\build\youtube_dl\YoutubeDL.py", line 1903, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpgf__qgjd\build\youtube_dl\YoutubeDL.py", line 1848, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpgf__qgjd\build\youtube_dl\downloader\common.py", line 364, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpgf__qgjd\build\youtube_dl\downloader\http.py", line 342, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpgf__qgjd\build\youtube_dl\downloader\http.py", line 230, in download
  File "C:\Python\Python34\lib\http\client.py", line 537, in read
  File "C:\Python\Python34\lib\http\client.py", line 576, in readinto
  File "C:\Python\Python34\lib\socket.py", line 378, in readinto
  File "C:\Python\Python34\lib\ssl.py", line 748, in recv_into
  File "C:\Python\Python34\lib\ssl.py", line 620, in read
ssl.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1748)

**Comment by dstftw** [comment]
Most likely caused by your proxy.

**Comment by totalamd** [comment]
So what should I do if I have the same issue? Open a new one?
