### ISSUE TITLE
Site support request (ITVDN.com)

### ISSUE THREAD

**Issue by AOne-T** [rg3/youtube-dl#19197]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.02.08*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.02.08**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [*] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
>youtube-dl.exe -v https://itvdn.com/ru/patterns
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://itvdn.com/ru/patterns']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2019.02.08
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: none
[debug] Proxy map: {}
[generic] patterns: Requesting header
WARNING: Falling back on generic information extractor.
[generic] patterns: Downloading webpage
[generic] patterns: Extracting information
ERROR: Unsupported URL: https://itvdn.com/ru/patterns
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6w61832c\build\youtube_dl\YoutubeDL.py", line 794, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6w61832c\build\youtube_dl\extractor\common.py", line 508, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6w61832c\build\youtube_dl\extractor\generic.py", line 3320, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://itvdn.com/ru/patterns
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

**Comment by Vangelis66** [comment]
... The first **free** full video available at the URI specified is hosted on VIMEO; with a bit of URL sniffing (via Web Console), it can be downloaded with the following command: 

`youtube-dl -c --no-part --referer "https://itvdn.com/ru/patterns" -f "http-720p" "https://player.vimeo.com/video/170944837" -o "Шаблоны проектирования - Введение (Full).mp4"` => 

```
[vimeo] 170944837: Downloading webpage
[vimeo] 170944837: Extracting information
[vimeo] 170944837: Downloading JSON metadata
WARNING: Unable to download JSON metadata: HTTP Error 404: Not Found
[vimeo] 170944837: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 170944837: Downloading fastly_skyfire m3u8 information
[vimeo] 170944837: Downloading akfire_interconnect_quic MPD information
[vimeo] 170944837: Downloading akfire_interconnect_quic MPD information
[vimeo] 170944837: Downloading fastly_skyfire MPD information
[vimeo] 170944837: Downloading fastly_skyfire MPD information
[download] Destination: Шаблоны проектирования - Введение (Full).mp4
[download]  23.0% of 80.32MiB at  1.47MiB/s ETA 00:42
```
Though not tried, I expect the rest of the **free** videos (of the playlist) to be downloadable via a similar fashion... 😜

**Comment by AOne-T** [comment]
Using developer console in browser, I only found out that it downloads video is m4s segments. Where did you find the full url?

**Comment by AOne-T** [comment]
Using the url you provided I found other urls throughout the course (it is free up to february 13th) and downloaded it. Thanks!
But having it automated would be nice.

**Comment by Vangelis66** [comment]
> Using developer console in browser, 
> I only found out that it downloads video is m4s segments. 
> Where did you find the full url?

Hello Alex 😄 
As I already said, I used **Web Console** (CTRL+SHIFT+K) among the Developer Tools in a **Mozilla** type browser (I avoid Google Chrome like the plague...) - once I loaded the free video and it started playing, I noticed the `vimeo.api/oembed.json` web request (meaning the embedded video is hosted on VIMEO) and soon after the link to the video itself, `player.vimeo.com/video/170944837`: 

![vimeolink](https://user-images.githubusercontent.com/9669492/52661467-cd2d7e80-2f0a-11e9-90b1-129641c18471.jpg)

I hope it's clearer now for you... 😉 
Regards

**Comment by AOne-T** [comment]
@Vangelis66 Thanks for explanation!
