### ISSUE TITLE
Support website nowvideo.club

### ISSUE THREAD

**Issue by leewdch** [rg3/youtube-dl#19208]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.02.08*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.02.08**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl --verbose "http://nowvideo.club/videos/n1nlo6r87pnv"
[debug] System config: []
[debug] User config: ['-r', '1M']
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'http://nowvideo.club/videos/n1nlo6r87pnv']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.02.08
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg N-93016-gb8ebce4f84, ffprobe N-93016-gb8ebce4f84
[debug] Proxy map: {}
[generic] n1nlo6r87pnv: Requesting header
[redirect] Following redirect to http://nowvideo.club/play/n1nlo6r87pnv
[generic] n1nlo6r87pnv: Requesting header
WARNING: Falling back on generic information extractor.
[generic] n1nlo6r87pnv: Downloading webpage
[generic] n1nlo6r87pnv: Extracting information
ERROR: Unsupported URL: http://nowvideo.club/play/n1nlo6r87pnv
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6w61832c\build\youtube_dl\YoutubeDL.py", line 794, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6w61832c\build\youtube_dl\extractor\common.py", line 508, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6w61832c\build\youtube_dl\extractor\generic.py", line 3320, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: http://nowvideo.club/play/n1nlo6r87pnv

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://nowvideo.club/videos/n1nlo6r87pnv

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

I checked the supported websites on youtube-dl webpage and NowVideo is reported as supported but I'm still having troubles downloading from it. I think this is caused by a possible nowvideo mirror that isn't recognized by youtube-dl. Regarding the video itself I'm trying to download, it's a video previously hosted on my national free web streaming website and later vanished from it. Since the website itself is supported by youtube-dl there should be no problem whatsoever with this website support request or so I think. Just wanted to make the source of the video clear here in the description of the issue.

Regarding the website itself I think it's kind of sketchy and full of ads (I'm using an adblock and I think you should do the same in case you are going to visit the url when checking it out. I also tried registering but it fails to redirect to a proper registration prompt. I don't know if this is an issue with mirrored websites or if the website itself is just using nowvideo name to get web traffic but the video itself works.

**Comment by ealgase** [comment]
Video is not available.
