### ISSUE TITLE
HTTPError: HTTP Error 302: The HTTP server returned a redirect error that would lead to an infinite loop. The last 30x error message was: Found

### ISSUE THREAD

**Issue by Elite** [rg3/youtube-dl#1923]
No idea what happened here, in first attempt this worked but said `ERROR: content too short (expected 4926888 bytes and served 2097136)` but on subsequent tries it said  `ERROR: unable to download video data: HTTP Error 302: The HTTP server returned a redirect error that would lead to an infinite loop. The last 30x error message was: Found`.
```
root@debian7:~# youtube-dl -v -f 141/140/139 http://www.youtube.com/watch?v=n6ibFSDLz_E
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', '-f', '141/140/139', 'http://www.youtube.com/watch?v=n6ibFSDLz_E']
[debug] youtube-dl version 2013.12.08.1
[debug] Python version 2.7.3 - Linux-3.2.0-4-amd64-x86_64-with-debian-7.2
[debug] Proxy map: {}
[youtube] Setting language
[youtube] n6ibFSDLz_E: Downloading webpage
[youtube] n6ibFSDLz_E: Downloading video info webpage
[youtube] n6ibFSDLz_E: Extracting video information
[download] Destination: ÐÑÐµ ÐÐ²ÐµÐ·Ð´Ñ -- Ð ÐµÐ°Ð»ÑÐ½Ð° Ð¢Ð¾Ð»ÑÐºÐ¾ ÐÑÐ·ÑÐºÐ° (prod. by Tema Yurev & Shaplin)-n6ibFSDLz_E.m4a
[download] 100% of 4.70MiB in 00:00
ERROR: content too short (expected 4926888 bytes and served 2097136)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 806, in process_info
    success = self.fd._do_download(filename, info_dict)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/FileDownloader.py", line 660, in _do_download
    raise ContentTooShortError(byte_counter, int(data_len))
ContentTooShortError

```

```
root@debian7:~# youtube-dl -f 141/140/139 http://www.youtube.com/watch?v=n6ibFSDLz_E
[youtube] Setting language
[youtube] n6ibFSDLz_E: Downloading webpage
[youtube] n6ibFSDLz_E: Downloading video info webpage
[youtube] n6ibFSDLz_E: Extracting video information
[download] Resuming download at byte 2097136
[download] Got server HTTP error. Retrying (attempt 1 of 10)...
[download] Got server HTTP error. Retrying (attempt 2 of 10)...
[download] Got server HTTP error. Retrying (attempt 3 of 10)...
[download] Got server HTTP error. Retrying (attempt 4 of 10)...
ERROR: unable to download video data: HTTP Error 302: The HTTP server returned a redirect error that would lead t                                       o an infinite loop.
The last 30x error message was:
Found
```

```
root@debian7:~# youtube-dl -v -f 141/140/139 http://www.youtube.com/watch?v=n6ibFSDLz_E
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', '-f', '141/140/139', 'http://www.youtube.com/watch?v=n6ibFSDLz_E']
[debug] youtube-dl version 2013.12.08.1
[debug] Python version 2.7.3 - Linux-3.2.0-4-amd64-x86_64-with-debian-7.2
[debug] Proxy map: {}
[youtube] Setting language
[youtube] n6ibFSDLz_E: Downloading webpage
[youtube] n6ibFSDLz_E: Downloading video info webpage
[youtube] n6ibFSDLz_E: Extracting video information
[download] Resuming download at byte 2097136
[download] Got server HTTP error. Retrying (attempt 1 of 10)...
[download] Got server HTTP error. Retrying (attempt 2 of 10)...
[download] Got server HTTP error. Retrying (attempt 3 of 10)...
[download] Got server HTTP error. Retrying (attempt 4 of 10)...
ERROR: unable to download video data: HTTP Error 302: The HTTP server returned a redirect error that would lead t                                       o an infinite loop.
The last 30x error message was:
Found
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 806, in process_info
    success = self.fd._do_download(filename, info_dict)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/FileDownloader.py", line 540, in _do_download
    data = compat_urllib_request.urlopen(request)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 407, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 520, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 439, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 379, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 616, in http_error_302
    self.inf_msg + msg, headers, fp)
HTTPError: HTTP Error 302: The HTTP server returned a redirect error that would lead to an infinite loop.
The last 30x error message was:
Found
```

**Comment by remitamine** [comment]
it's now working:
```
youtube-dl -v -f 141/140/139 http://www.youtube.com/watch?v=n6ibFSDLz_E
[debug] System config: []
[debug] User config: ['--external-downloader', 'aria2c', '--external-downloader-args', '-x 16 --check-certificate=false', '-f', 'best[height<=?720]', '--sub-lang', 'ar,en', '--write-sub']
[debug] Command-line args: ['-v', '-f', '141/140/139', 'http://www.youtube.com/watch?v=n6ibFSDLz_E']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.07.21
[debug] Python version 3.4.3 - Linux-4.1.2-2-ARCH-x86_64-with-arch-Arch-Linux
[debug] exe versions: ffmpeg 2.7.2, ffprobe 2.7.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] n6ibFSDLz_E: Downloading webpage
[youtube] n6ibFSDLz_E: Downloading video info webpage
[youtube] n6ibFSDLz_E: Extracting video information
WARNING: video doesn't have subtitles
[youtube] {22} signature length 40.40, html5 player en_US-vflGx3XCd
[youtube] {43} signature length 40.40, html5 player en_US-vflGx3XCd
[youtube] {18} signature length 40.40, html5 player en_US-vflGx3XCd
[youtube] {5} signature length 40.40, html5 player en_US-vflGx3XCd
[youtube] {36} signature length 40.40, html5 player en_US-vflGx3XCd
[youtube] {17} signature length 40.40, html5 player en_US-vflGx3XCd
[youtube] {137} signature length 40.40, html5 player en_US-vflGx3XCd
[youtube] {248} signature length 40.40, html5 player en_US-vflGx3XCd
[youtube] {136} signature length 40.40, html5 player en_US-vflGx3XCd
[youtube] {247} signature length 40.40, html5 player en_US-vflGx3XCd
[youtube] {135} signature length 40.40, html5 player en_US-vflGx3XCd
[youtube] {244} signature length 40.40, html5 player en_US-vflGx3XCd
[youtube] {134} signature length 40.40, html5 player en_US-vflGx3XCd
[youtube] {243} signature length 40.40, html5 player en_US-vflGx3XCd
[youtube] {133} signature length 40.40, html5 player en_US-vflGx3XCd
[youtube] {242} signature length 40.40, html5 player en_US-vflGx3XCd
[youtube] {160} signature length 40.40, html5 player en_US-vflGx3XCd
[youtube] {140} signature length 40.40, html5 player en_US-vflGx3XCd
[youtube] {171} signature length 40.40, html5 player en_US-vflGx3XCd
[youtube] n6ibFSDLz_E: Downloading DASH manifest
[youtube] n6ibFSDLz_E: Downloading player https://s.ytimg.com/yts/jsbin/html5player-en_US-vflGx3XCd/html5player.js
[youtube] n6ibFSDLz_E: Downloading DASH manifest
WARNING: Could not download DASH manifest: HTTP Error 403: Forbidden
[debug] Invoking downloader on 'https://r5---sn-nx5cvox-2hvl.googlevideo.com/videoplayback?id=9fa89b1520cbcff1&itag=141&source=youtube&requiressl=yes&gcr=dz&ms=au&mv=m&pl=17&mm=31&mn=sn-nx5cvox-2hvl&ratebypass=yes&mime=audio/mp4&gir=yes&clen=9888902&lmt=1417043650597226&dur=310.148&fexp=9407538,9407663,9407942,9408505,9408710,9409207,9414764,9415365,9415435,9415485,9415942,9416126,9416277,9416347,9416371,9416729,9417129,9417348,9417580,9418008,9418201&sver=3&mt=1438354932&upn=xvrvFe3TDu8&signature=8A110279E4A397C982CFAC6C2532F5F0DD78D956.73BB34176423EC2C9AFC94078FD10DF89C75727B&key=dg_yt0&ip=197.205.50.22&ipbits=0&expire=1438376637&sparams=ip,ipbits,expire,id,itag,source,requiressl,gcr,ms,mv,pl,mm,mn,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: Все Звезды -- Реальна Только Музыка (prod. by Tema Yurev & Shaplin)-n6ibFSDLz_E.m4a
[debug] aria2c command line: aria2c -c -x 16 --check-certificate=false --out 'Все Звезды -- Реальна Только Музыка (prod. by Tema Yurev & Shaplin)-n6ibFSDLz_E.m4a.part' --header 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' --header 'Accept-Encoding: gzip, deflate' --header 'Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7' --header 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/20.0 (Chrome)' --header 'Accept-Language: en-us,en;q=0.5' -- 'https://r5---sn-nx5cvox-2hvl.googlevideo.com/videoplayback?id=9fa89b1520cbcff1&itag=141&source=youtube&requiressl=yes&gcr=dz&ms=au&mv=m&pl=17&mm=31&mn=sn-nx5cvox-2hvl&ratebypass=yes&mime=audio/mp4&gir=yes&clen=9888902&lmt=1417043650597226&dur=310.148&fexp=9407538,9407663,9407942,9408505,9408710,9409207,9414764,9415365,9415435,9415485,9415942,9416126,9416277,9416347,9416371,9416729,9417129,9417348,9417580,9418008,9418201&sver=3&mt=1438354932&upn=xvrvFe3TDu8&signature=8A110279E4A397C982CFAC6C2532F5F0DD78D956.73BB34176423EC2C9AFC94078FD10DF89C75727B&key=dg_yt0&ip=197.205.50.22&ipbits=0&expire=1438376637&sparams=ip,ipbits,expire,id,itag,source,requiressl,gcr,ms,mv,pl,mm,mn,ratebypass,mime,gir,clen,lmt,dur'
[#9d3d58 9.3MiB/9.4MiB(98%) CN:2 DL:218KiB]                                    
07/31 16:01:48 [NOTICE] Download complete: /home/amine/Videos/Все Звезды -- Реальна Только Музыка (prod. by Tema Yurev & Shaplin)-n6ibFSDLz_E.m4a.part

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
9d3d58|OK  |   231KiB/s|/home/amine/Videos/Все Звезды -- Реальна Только Музыка (prod. by Tema Yurev & Shaplin)-n6ibFSDLz_E.m4a.part

Status Legend:
(OK):download completed.
[aria2c] Downloaded 9888902 bytes
[download] 100% of 9.43MiB
[ffmpeg] Correcting container in "Все Звезды -- Реальна Только Музыка (prod. by Tema Yurev & Shaplin)-n6ibFSDLz_E.m4a"
[debug] ffmpeg command line: ffmpeg -y -i 'Все Звезды -- Реальна Только Музыка (prod. by Tema Yurev & Shaplin)-n6ibFSDLz_E.m4a' -c copy -f mp4 'Все Звезды -- Реальна Только Музыка (prod. by Tema Yurev & Shaplin)-n6ibFSDLz_E.temp.m4a'
```

**Comment by yan12125** [comment]
Yes it's working now. Closing.

**Comment by yan12125** [comment]
Related: #3721
