### ISSUE TITLE
Return of Extractor Error

### ISSUE THREAD

**Issue by rootVIII** [rg3/youtube-dl#19245]
```
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.02.08**
More importantly, this error reappeared with your Feb. 08 update.


(virtualenv) 17:22 ~/mysite $ pip3 freeze | grep -i youtube
youtube-dl==2019.2.8   



- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

```
### What is the purpose of your *issue*?
```
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other
```

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []                                                                                                                                                                                  
[debug] User config: []                                                                                                                                                                                    
[debug] Custom config: []                                                                                                                                                                                  
[debug] Command-line args: ['-v', 'http://www.youtube.com/watch?v=BaW_jenozKcj']                                                                                                                           
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8                                                                                                                                           
[debug] youtube-dl version 2019.02.08                                                                                                                                                                      
[debug] Python version 3.5.2 (CPython) - Linux-4.4.0-1072-aws-x86_64-with-Ubuntu-14.04-trusty                                                                                                              
[debug] exe versions: avconv 9.20-6, avprobe 9.20-6                                                                                                                                                        
[debug] Proxy map: {}                                                                                                                                                                                      
[youtube] BaW_jenozKc: Downloading webpage                                                                                                                                                                 
[youtube] BaW_jenozKc: Downloading video info webpage

```
---

### Description of your *issue*, suggested solution and other information

I am sure you know about this one already. I experienced this issue months ago and upgrading along with pafy resolved it. However the problem has returned, and I am using the latest version of youtube-dl according to your Github and Pypi repo.
```
2019-02-16 00:54:05,546: ERROR: Signature extraction failed: Traceback (most recent call last):
2019-02-16 00:54:05,547:   File "/home/co/.virtualenvs/virtualenv/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1225, in _decrypt_signature
2019-02-16 00:54:05,547:     elif not re.match(r'https?://', player_url):
2019-02-16 00:54:05,547:   File "/home/co/.virtualenvs/virtualenv/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1133, in _extract_signature_function
2019-02-16 00:54:05,547:     'Downloading %s player %s' % (player_type, player_id)
2019-02-16 00:54:05,547:   File "/home/co/.virtualenvs/virtualenv/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1200, in _parse_sig_js
2019-02-16 00:54:05,548:     r'\.sig\|\|(?P<sig>[a-zA-Z0-9$]+)\(',
2019-02-16 00:54:05,548:   File "/home/co/.virtualenvs/virtualenv/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 245, in extract_function
2019-02-16 00:54:05,548:     raise ExtractorError('Could not find JS function %r' % funcname)
2019-02-16 00:54:05,548: youtube_dl.utils.ExtractorError: Could not find JS function 'encodeURIComponent'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
2019-02-16 00:54:05,548:  (caused by ExtractorError("Could not find JS function 'encodeURIComponent'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by dstftw** [comment]
As already pointed out you're using an outdated version.

>I am using the latest version of youtube-dl

You must **prove** that with single complete verbose log.

**Comment by rootVIII** [comment]
Is that not the log I provided above???
```[debug] youtube-dl version 2019.02.08```

I'll just save us both the trouble and stop using the module

**Comment by dstftw** [comment]
Again: you must provide the **compile log of run that fails**, not two logs from different runs. 99% that you are using different versions from console and from where it fails. Bother to read issue template already.
