### ISSUE TITLE
[youtube] b6d_kDN_EDs: Downloading webpage << is running into an error, maybe because of wrong Proxy configuration?

### ISSUE THREAD

**Issue by GecoMynx** [rg3/youtube-dl#19272]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.02.18**
- [x] At least skimmed through the [README] **most notably** the [FAQ] and [BUGS] sections
- [x] [Searched] the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other
---
Verbose Log:
```
PS C:\Windows\system32> youtube-dl.exe -v --config-location C:\bin\youtube-dl.conf https://www.youtube.com/watch?v=b6d_kDN_EDs
[debug] System config: []
[debug] User config: []
[debug] Custom config: ['--no-mtime', '--proxy', 'socks5://proxyde.hoist.de:8881/', '-f', 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best', '-o', 'C:UserskevtDesktop%(title)s.%(ext)s']
[debug] Command-line args: ['-v', '--config-location', 'C:\\bin\\youtube-dl.conf', 'https://www.youtube.com/watch?v=b6d_kDN_EDs']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.02.18
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.15063
[debug] exe versions: ffmpeg 4.1, ffprobe 4.1
[debug] Proxy map: {'http': 'socks5://proxyde.hoist.de:8881/', 'https': 'socks5://proxyde.hoist.de:8881/'}
[youtube] b6d_kDN_EDs: Downloading webpage
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw73a_6nx\build\youtube_dl\__init__.py", line 472, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw73a_6nx\build\youtube_dl\__init__.py", line 462, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw73a_6nx\build\youtube_dl\YoutubeDL.py", line 2006, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw73a_6nx\build\youtube_dl\YoutubeDL.py", line 794, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw73a_6nx\build\youtube_dl\extractor\common.py", line 508, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw73a_6nx\build\youtube_dl\extractor\youtube.py", line 1533, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw73a_6nx\build\youtube_dl\extractor\common.py", line 772, in _download_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw73a_6nx\build\youtube_dl\extractor\youtube.py", line 268, in _download_webpage_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw73a_6nx\build\youtube_dl\extractor\common.py", line 638, in _download_webpage_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw73a_6nx\build\youtube_dl\extractor\common.py", line 605, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw73a_6nx\build\youtube_dl\YoutubeDL.py", line 2225, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw73a_6nx\build\youtube_dl\utils.py", line 1140, in https_open
  File "C:\Python\Python34\lib\urllib\request.py", line 1183, in do_open
  File "C:\Python\Python34\lib\http\client.py", line 1137, in request
  File "C:\Python\Python34\lib\http\client.py", line 1182, in _send_request
  File "C:\Python\Python34\lib\http\client.py", line 1133, in endheaders
  File "C:\Python\Python34\lib\http\client.py", line 963, in _send_output
  File "C:\Python\Python34\lib\http\client.py", line 898, in send
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw73a_6nx\build\youtube_dl\utils.py", line 1106, in connect
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw73a_6nx\build\youtube_dl\socks.py", line 270, in connect
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw73a_6nx\build\youtube_dl\socks.py", line 266, in _make_proxy
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw73a_6nx\build\youtube_dl\socks.py", line 221, in _setup_socks5
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw73a_6nx\build\youtube_dl\socks.py", line 192, in _socks5_auth
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw73a_6nx\build\youtube_dl\socks.py", line 131, in _recv_bytes
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw73a_6nx\build\youtube_dl\socks.py", line 126, in recvall
EOFError: 2 bytes missing
PS C:\Windows\system32>
```

### Description of your *issue*:
I'm inside a company network that uses a proxy. But I'm not quite sure, why the download isn't working. I *can* download youtube videos using other graphical downloaders like Free Download Manager. Also, I *can* view this video in any browser without having to find a way around the proxy.
I'm not sure if the proxy is hindering youtube-dl to download the webpage to get all necessary information out of it, or maybe I just entered the proxy wrong?

I'd really appreciate your help.
Thank you in advance and kind regards,
Kevin van Thiel

p.S.: Attached you can find Screenshots of the Configuration File and the cmd output:
![2019-02-19 14_26_11-administrator_ windows powershell](https://user-images.githubusercontent.com/25452924/53018294-46b8f580-3452-11e9-9b36-2f294c3885c7.png)
![2019-02-19 14_14_21-_c__bin_youtube-dl conf - notepad](https://user-images.githubusercontent.com/25452924/53017566-939bcc80-3450-11e9-999f-5830d9d46c61.png)

**Comment by dstftw** [comment]
Most likely it's not a socks5 proxy.

**Comment by GecoMynx** [comment]
> Most likely it's not a socks5 proxy.

Okay, what do I have to enter for the Proxy to work then? 
`--proxy http://proxyde.hoist.de:8881/` ?
or maybe
`--proxy http**s**://proxyde.hoist.de:8881/` ?
Or somehow both of that? Can't find anything according to the syntax in the manual. :/
Maybe it's just 
`--proxy proxyde.hoist.de:8881` ?

However, it doesn't seem to matter what I'm entering there.
I'm still getting error messages:
```
PS C:\Windows\system32> youtube-dl.exe -v --config-location C:\bin\youtube-dl.conf https://www.youtube.com/watch?v=b6d_kDN_EDs
[debug] System config: []
[debug] User config: []
[debug] Custom config: ['--no-mtime', '--proxy', 'proxyde.hoist.de:8881', '-f', 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best', '-o', 'C:UserskevtDesktop%(title)s.%(ext)s']
[debug] Command-line args: ['-v', '--config-location', 'C:\\bin\\youtube-dl.conf', 'https://www.youtube.com/watch?v=b6d_kDN_EDs']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.02.18
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.15063
[debug] exe versions: ffmpeg 4.1, ffprobe 4.1
[debug] Proxy map: {'https': 'proxyde.hoist.de:8881', 'http': 'proxyde.hoist.de:8881'}
[youtube] b6d_kDN_EDs: Downloading webpage
ERROR: Unable to download webpage: <urlopen error Tunnel connection failed: 407 Proxy Authentication Required> (caused by URLError(OSError('Tunnel connection failed: 407 Proxy Authentication Required',),))
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw73a_6nx\build\youtube_dl\extractor\common.py", line 605, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw73a_6nx\build\youtube_dl\YoutubeDL.py", line 2225, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw73a_6nx\build\youtube_dl\utils.py", line 1140, in https_open
  File "C:\Python\Python34\lib\urllib\request.py", line 1185, in do_open
```
The Error-Message looks always the same, whatever I'm trying to use as a proxy.
Is it because the Proxy is blocking it? I can't read the verbose log, so it would be great to know why it's erroring out...

**Comment by GecoMynx** [comment]
Our Proxy is using authentication for the Users. 
Is it possible that I have to enter my credentials at some point? 
But how tho?

**Comment by GecoMynx** [comment]
Okay, you can close this case now, I found the issue.
I just had to explicitly **NOT** use the Proxy by entering the following line to the config-file:
`--proxy ""`
