### ISSUE TITLE
[soundcloud] Error when downloading file in playlist

### ISSUE THREAD

**Issue by diffycat** [rg3/youtube-dl#1967]
Full log: https://gist.github.com/diffycat/7960595

Short log:
```
$ youtube-dl --add-metadata https://soundcloud.com/simgretina --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--add-metadata', 'https://soundcloud.com/simgretina', '--verbose']
[debug] youtube-dl version 2013.12.11.2
[debug] Python version 3.3.3 - Linux-3.12.3-1-ARCH-x86_64-with-arch-Arch-Linux
[debug] Proxy map: {}

<snip/>

[download] Downloading video #116 of 161
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
File "/usr/lib/python3.3/site-packages/youtube_dl/YoutubeDL.py", line 848, in process_info
success = self.fd._do_download(filename, info_dict)
File "/usr/lib/python3.3/site-packages/youtube_dl/FileDownloader.py", line 568, in _do_download
data = compat_urllib_request.urlopen(request)
File "/usr/lib/python3.3/urllib/request.py", line 156, in urlopen
return opener.open(url, data, timeout)
File "/usr/lib/python3.3/urllib/request.py", line 475, in open
response = meth(req, response)
File "/usr/lib/python3.3/urllib/request.py", line 587, in http_response
'http', request, response, code, msg, hdrs)
File "/usr/lib/python3.3/urllib/request.py", line 513, in error
return self._call_chain(*args)
File "/usr/lib/python3.3/urllib/request.py", line 447, in _call_chain
result = func(*args)
File "/usr/lib/python3.3/urllib/request.py", line 595, in http_error_default
raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

Looks like I can't download https://soundcloud.com/simgretina/octavias-secret-doomzone-remix from playlist, but it works if I do that using single song downloading.

**Comment by dstftw** [comment]
Fixed in 1ae72fb.
