### ISSUE TITLE
uptostream.com/iframe not working

### ISSUE THREAD

**Issue by Ara0n** [rg3/youtube-dl#19919]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.02.18*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.02.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl -v https://uptostream.com/iframe/qj1z477e0ntm -o test.mp4
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://uptostream.com/iframe/qj1z477e0ntm', u'-o', u'test.mp4']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.02.18
[debug] Python version 2.7.15+ (CPython) - Linux-4.18.0-2-amd64-x86_64-with-debian-buster-sid
[debug] exe versions: ffmpeg 4.1-1, ffprobe 4.1-1
[debug] Proxy map: {}
[generic] qj1z477e0ntm: Requesting header
WARNING: Falling back on generic information extractor.
[generic] qj1z477e0ntm: Downloading webpage
[generic] qj1z477e0ntm: Extracting information
ERROR: Unsupported URL: https://uptostream.com/iframe/qj1z477e0ntm
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2337, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2542, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2531, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
ParseError: mismatched tag: line 36, column 2
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 794, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3320, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://uptostream.com/iframe/qj1z477e0ntm
...
<end of log>
```

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

I tried multiple different urls but all of them resulted in that same error.

**Comment by DiagonalArg** [comment]
I appear to be having similar problems.

```
$ youtube-dl.new --verbose --prefer-ffmpeg "https://uptostream.com/iframe/ucz8elinfcp6"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'--prefer-ffmpeg', u'https://uptostream.com/iframe/ucz8elinfcp6']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.06.08
[debug] Python version 2.7.12 (CPython) - Linux-4.4.0-150-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 3.4.4-1, avprobe 3.4.4-1, ffmpeg 3.4.4-1, ffprobe 3.4.4-1, rtmpdump 2.4
[debug] Proxy map: {'socks': 'socks://localhost:9999/'}
[generic] ucz8elinfcp6: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ucz8elinfcp6: Downloading webpage
[generic] ucz8elinfcp6: Extracting information
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/dev/bin/youtube-dl.new/youtube_dl/extractor/generic.py", line 2340, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/home/dev/bin/youtube-dl.new/youtube_dl/compat.py", line 2551, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/home/dev/bin/youtube-dl.new/youtube_dl/compat.py", line 2540, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: junk after document element: line 2, column 0
Traceback (most recent call last):
  File "/home/dev/bin/youtube-dl.new/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/home/dev/bin/youtube-dl.new/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/home/dev/bin/youtube-dl.new/youtube_dl/extractor/generic.py", line 3165, in _real_extract
    self._sort_formats(entry['formats'])
  File "/home/dev/bin/youtube-dl.new/youtube_dl/extractor/common.py", line 1327, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by DiagonalArg** [comment]
Looking at the source of the uptostream.com page, I find that this URL is working, though it's quite slow:
```
https://www46.uptostream.com/igw2hk2809/360/0/video.mp4
```

**Comment by regseb** [comment]
The URL of the video can be extract with the following JavaScript code (it can be used as a lead for Python).

```JavaScript
fetch("https://uptostream.com/api/streaming/source/get?token=null" +
                           `&file_code=ucz8elinfcp6`).then(async (response) => {
    const json = await response.json();
    const sources = eval(`"use strict"; ${json.data.sources}; sources`);
    console.log(sources);
});
```

Here is, from what I understand, the behavior of the _Uptostream_ site. The web page calls the API `https://uptostream.com/api/streaming/source/get?token=null&file_code=ucz8elinfcp6` which returns JSON. The JSON contains JavaScript code which can be summarized as:

```JavaScript
// A variable with a random name surely contains the obfuscated data.
var _0x864c = ['wrTCosONRQ==', 'd30jwrY=', /* ... */, 'GcOQw7XDkw=='];
// Deliberately complex code to de-obfuscate the data.
(function(_0x3eb659, _0x864cae) { /* ... */ }(_0x864c, 0x16b));var _0xa091 = function() { /* ... */ };
// The array that will contain the data in plain text.
var sources = [];;
// More complex code to de-obfuscate data.
sources[_0xa091('0x2a', '@KkE')](function setTheLink() { /* ... */ }());
```

The web page executes this code and retrieves the following data in the `sources` variable:

```JSON
[
    {
        "src":    "https://www46.uptostream.com/33hv1na0249/360/0/video.mp4",
        "type":   "video/mp4",
        "label":  "360p",
        "res":    "360",
        "lang":   "unknown 0",
        "idLang": "0"
    }
]
```
