### ISSUE TITLE
Unable to download video webpage: [Errno 10054] An existing connection wa s forcibly closed by the remote host

### ISSUE THREAD

**Issue by sirinath** [rg3/youtube-dl#1996]
[download] Downloading video #16 of 156
[youtube] pnYn4aQgcb0: Downloading video webpage
ERROR: Unable to download video webpage: [Errno 10054] An existing connection wa
s forcibly closed by the remote host; please report this issue on https://yt-dl.
org/bug . Be sure to call youtube-dl with the --verbose flag and include its com
plete output. Make sure you are using the latest version; type  youtube-dl -U  t
o update.
Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 1265, in _real_extract
  File "urllib2.pyo", line 127, in urlopen
  File "urllib2.pyo", line 404, in open
  File "urllib2.pyo", line 422, in _open
  File "urllib2.pyo", line 382, in _call_chain
  File "youtube_dl\utils.pyo", line 561, in https_open
  File "urllib2.pyo", line 1187, in do_open
  File "httplib.pyo", line 1045, in getresponse
  File "httplib.pyo", line 409, in begin
  File "httplib.pyo", line 365, in _read_status
  File "socket.pyo", line 476, in readline
  File "ssl.pyo", line 241, in recv
  File "ssl.pyo", line 160, in read
error: [Errno 10054] An existing connection was forcibly closed by the remote ho
st
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 429, in extract_info
  File "youtube_dl\extractor\common.pyo", line 131, in extract
  File "youtube_dl\extractor\youtube.pyo", line 1267, in _real_extract
ExtractorError: Unable to download video webpage: [Errno 10054] An existing conn
ection was forcibly closed by the remote host; please report this issue on https
://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and includ
e its complete output. Make sure you are using the latest version; type  youtube
-dl -U  to update.

**Comment by yan12125** [comment]
Sorry for being late. In general those errors are caused by unstable networks. Please move on to #8203 for further discussions.
