### ISSUE TITLE
Bug Poker Go certain files show as 403

### ISSUE THREAD

**Issue by cakeaz** [rg3/youtube-dl#20079]
Some files i can grab just fine, others i can watch just fine but when i try to download it, i get a 403 error.

02/27/19 20:10:37] ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[02/27/19 20:12:01] [debug] System config: []
[02/27/19 20:12:01] [debug] User config: []
[02/27/19 20:12:01] [debug] Custom config: []
[02/27/19 20:12:01] [debug] Command-line args: ['--newline', '-o', 'C:\\Users\\Ajax\\%(title)s.%(ext)s', '-v', '--ignore-config', '--hls-prefer-native', '--verbose', ' ']
[02/27/19 20:12:01] [debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[02/27/19 20:12:01] [debug] youtube-dl version 2019.02.18
[02/27/19 20:12:01] [debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[02/27/19 20:12:01] [debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2
[02/27/19 20:12:01] [debug] Proxy map: {}
[02/27/19 20:12:01] ERROR: '' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:" ) to search YouTube
[02/27/19 20:12:01] Traceback (most recent call last):
[02/27/19 20:12:01]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw73a_6nx\build\youtube_dl\YoutubeDL.py", line 794, in extract_info
[02/27/19 20:12:01]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw73a_6nx\build\youtube_dl\extractor\common.py", line 508, in extract
[02/27/19 20:12:01]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw73a_6nx\build\youtube_dl\extractor\generic.py", line 2227, in _real_extract
[02/27/19 20:12:01] youtube_dl.utils.ExtractorError: '' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:" ) to search YouTube
[02/27/19 20:12:01] 
[02/27/19 20:12:01] [debug] System config: []
[02/27/19 20:12:01] [debug] User config: []
[02/27/19 20:12:01] [debug] Custom config: []
[02/27/19 20:12:01] [debug] Command-line args: ['--newline', '-o', 'C:\\Users\\Ajax\\%(title)s.%(ext)s', '-v', '--ignore-config', '--hls-prefer-native', '--verbose', 'https://neunlds1003.akamaized.net/nlds_vod/pokergo/vod/2017/08/16/30980/2_30980_a01_t30980_2017_b_whole_1_pc.mp4.m3u8?h=ee0812ef908a29409f2c7e9651e1239f.1551236140746&hdnea=exp=1551236200~acl=/*~hmac=FEA1CE67BA2FDBBB187EDEC74DB58DED1A5DF0276AEB05E80E2B187761B8398B&nltid=pokergo&nltdt=0&uid=1170454']
[02/27/19 20:12:01] [debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[02/27/19 20:12:01] [debug] youtube-dl version 2019.02.18
[02/27/19 20:12:02] [debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[02/27/19 20:12:02] [debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2
[02/27/19 20:12:02] [debug] Proxy map: {}
[02/27/19 20:12:02] WARNING: Could not send HEAD request to https://neunlds1003.akamaized.net/nlds_vod/pokergo/vod/2017/08/16/30980/2_30980_a01_t30980_2017_b_whole_1_pc.mp4.m3u8?h=ee0812ef908a29409f2c7e9651e1239f.1551236140746&hdnea=exp=1551236200~acl=/*~hmac=FEA1CE67BA2FDBBB187EDEC74DB58DED1A5DF0276AEB05E80E2B187761B8398B&nltid=pokergo&nltdt=0&uid=1170454: HTTP Error 403: Forbidden
[02/27/19 20:12:02] ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[02/27/19 20:12:02]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw73a_6nx\build\youtube_dl\extractor\common.py", line 605, in _request_webpage
[02/27/19 20:12:02]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw73a_6nx\build\youtube_dl\YoutubeDL.py", line 2225, in urlopen
[02/27/19 20:12:02]   File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
[02/27/19 20:12:02]   File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
[02/27/19 20:12:02]   File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
[02/27/19 20:12:02]   File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
[02/27/19 20:12:02]   File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
[02/27/19 20:12:02]

**Comment by dstftw** [comment]
You must use the original URL.
