### ISSUE TITLE
Still a error with NPO download.

### ISSUE THREAD

**Issue by WuvorWenda** [rg3/youtube-dl#20225]
Thank you for the commit,
But i get this error now with version 2019.03.01
[debug] Custom config: []
[debug] Command-line args: ['-f', '0', 'https://www.npostart.nl/keuringsdienst-van-waarde/28-02-2019/KN_1704077']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.03.01
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-91789-g11cec34829, rtmpdump 2.4
[debug] Proxy map: {}
[npo] KN_1704077: Downloading token
[npo] KN_1704077: Downloading player JSON
[npo] KN_1704077: Downloading hls profile JSON
[npo] KN_1704077: Downloading dash-widevine profile JSON
[npo] KN_1704077: Downloading MPD manifest
[npo] KN_1704077: Downloading dash-playready profile JSON
[npo] KN_1704077: Downloading MPD manifest
[npo] KN_1704077: Downloading smooth profile JSON
[npo] KN_1704077: Downloading ISM manifest
[npo] KN_1704077: Downloading JSON metadata
[npo] KN_1704077: Downloading token
[npo] KN_1704077: Downloading formats JSON
[npo] KN_1704077: Downloading Adaptive stream JSON
[npo] KN_1704077: Downloading Hoog stream JSON
[npo] KN_1704077: Downloading Normaal stream JSON
[npo] KN_1704077: Downloading Laag stream JSON
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtu
be-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplyslo9xs\build\youtube_dl\extractor\npo.py", line 185, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplyslo9xs\build\youtube_dl\extractor\npo.py", line 249, in _get_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplyslo9xs\build\youtube_dl\extractor\common.py", line 1305, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to upd
ate. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplyslo9xs\build\youtube_dl\extractor\npo.py", line 185, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplyslo9xs\build\youtube_dl\extractor\npo.py", line 249, in _get_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplyslo9xs\build\youtube_dl\extractor\common.py", line 1305, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to upd
ate. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplyslo9xs\build\youtube_dl\YoutubeDL.py", line 794, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplyslo9xs\build\youtube_dl\extractor\common.py", line 508, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplyslo9xs\build\youtube_dl\extractor\npo.py", line 187, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplyslo9xs\build\youtube_dl\extractor\npo.py", line 456, in _get_old_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplyslo9xs\build\youtube_dl\extractor\common.py", line 1305, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to upd
ate. Be sure to call youtube-dl with the --verbose flag and include its complete output.

_Originally posted by @WuvorWenda in https://github.com/rg3/youtube-dl/issues/20084#issuecomment-468711046_

**Comment by dstftw** [comment]
As already pointed out: content is DRM protected.
