### ISSUE TITLE
Kaltura download error

### ISSUE THREAD

**Issue by ryvec** [rg3/youtube-dl#20237]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.03.01*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ ] I've **verified** and **I assure** that I'm running youtube-dl **2019.03.01**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x ] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

D:\>youtube-dl -v kaltura:1955031:1_y39fkhaq -f mp4-2929
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'kaltura:1955031:1_y39fkhaq', '-f', 'mp4-2929'
]
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2019.03.01
[debug] Python version 3.4.4 (CPython) - Windows-8.1-6.3.9600
[debug] exe versions: ffmpeg 4.1, ffprobe N-89980-ge752da5464, rtmpdump 2.4
[debug] Proxy map: {}
[Kaltura] 1_y39fkhaq: Downloading video info JSON
[Kaltura] 1_y39fkhaq: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 404: Not Found
[debug] Invoking downloader on 'http://cdnapi.kaltura.com/p/1955031/sp/195503100
/playManifest/entryId/1_y39fkhaq/format/url/protocol/http/flavorId/1_6jf9b626'
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplyslo9xs\bu
ild\youtube_dl\YoutubeDL.py", line 1913, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplyslo9xs\bu
ild\youtube_dl\YoutubeDL.py", line 1852, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplyslo9xs\bu
ild\youtube_dl\downloader\common.py", line 364, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplyslo9xs\bu
ild\youtube_dl\downloader\http.py", line 341, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplyslo9xs\bu
ild\youtube_dl\downloader\http.py", line 109, in establish_connection
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmplyslo9xs\bu
ild\youtube_dl\YoutubeDL.py", line 2225, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* requires account credentials please provide them or explain how one can obtain them.

Cannot download video.
Command is:
youtube-dl -v kaltura:1955031:1_y39fkhaq -f mp4-2929
Command gets the overall "flavors" page, but can't download manifest for partricular flavor

**Comment by ryvec** [comment]
Analyzing in Fiddler, youtube-dl tries to get those URLs:
http://cdnapi.kaltura.com/p/1955031/sp/195503100/playManifest/entryId/1_y39fkhaq/format/applehttp/protocol/http
http://cdnapi.kaltura.com/p/1955031/sp/195503100/playManifest/entryId/1_y39fkhaq/format/url/protocol/http/flavorId/1_6jf9b626
and fails. Opening them in browser results in error too

**Comment by dstftw** [comment]
Post the original link.

**Comment by ryvec** [comment]
https://areena.yle.fi/1-4265502

**Comment by ryvec** [comment]
> Post the original link.

https://areena.yle.fi/1-4265502

**Comment by ryvec** [comment]
To clarify: when I'm VPNing to Finland, I can watch and download episode via conventional means (with FFMPEG) just fine, but trying to access it via youtube-dl doesn't work

**Comment by ryvec** [comment]
Any ideas?

**Comment by Hegezcc** [comment]
Looks like this is intentional geo restriction feature in Kaltura public API. No ideas on how to pass it.

**Comment by maxst33l** [comment]
I'm getting a similar issue with the following: https://curio.ca/en/video/the-great-transformation-1746/ Note that I am in the region I am trying to stream from (I can stream it no problem).
youtube-dl -v kaltura:1307701:1_ph1xslf9
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'kaltura:1307701:1_ph1xslf9']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg git-2020-06-17-0b3bd00
[debug] Proxy map: {}
[Kaltura] 1_ph1xslf9: Downloading video info JSON
[Kaltura] 1_ph1xslf9: Checking mp4-1373 URL
[Kaltura] 1_ph1xslf9: mp4-1373 URL is invalid, skipping
[Kaltura] 1_ph1xslf9: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 404: Not Found
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://cdnapi.kaltura.com/p/1307701/sp/130770100/playManifest/entryId/1_ph1xslf9/format/url/protocol/http/flavorId/1_hlcfxgv2'
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\YoutubeDL.py", line 1926, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\YoutubeDL.py", line 1865, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\downloader\common.py", line 366, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\downloader\http.py", line 341, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\downloader\http.py", line 109, in establish_connection
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\YoutubeDL.py", line 2238, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found
