### ISSUE TITLE
[soundcloud] youtube_dl.utils.ExtractorError: requested format not available

### ISSUE THREAD

**Issue by Geremia** [rg3/youtube-dl#20271]
```
$ youtube-dl -v https://soundcloud.com/azpolicy/ben-shapiro
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--no-warnings', '-if', 'bestvideo[height<=480]+bestaudio/best[height<=480]', '-v', 'https://soundcloud.com/azpolicy/ben-shapiro']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.03.01
[debug] Python version 3.7.2 (CPython) - Linux-4.19.25-x86_64-AMD_Ryzen_Threadripper_2990WX_32-Core_Processor-with-slackware-14.2
[debug] exe versions: ffmpeg 3.4.2, ffprobe 3.4.2
[debug] Proxy map: {}
[soundcloud] azpolicy/ben-shapiro: Resolving id
[soundcloud] azpolicy/ben-shapiro: Downloading info JSON
[soundcloud] 581324589: Downloading track url
[soundcloud] 581324589: Downloading m3u8 information
[soundcloud] 581324589: Downloading m3u8 information
[soundcloud] 581324589: Checking http_mp3_128_url video format URL
[soundcloud] 581324589: Checking hls_mp3_128_url video format URL
[soundcloud] 581324589: Checking hls_opus_64_url video format URL
ERROR: requested format not available
Traceback (most recent call last):
  File "/usr/lib64/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 805, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib64/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 859, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/lib64/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 1632, in process_video_result
    expected=True)
youtube_dl.utils.ExtractorError: requested format not available
```

**Comment by Geremia** [comment]
accidentally specified  -if 'bestvideo[height<=480]+bestaudio/best[height<=480]' on a SoundCloud (audio only!) URL
no wonder
