### ISSUE TITLE
[soundcloud] Can't add metadata info to m4a

### ISSUE THREAD

**Issue by diffycat** [rg3/youtube-dl#2079]
```
$ youtube-dl https://soundcloud.com/thelivingtombstone/tombmobilehiphop1 --verbose --add-metadata 
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['https://soundcloud.com/thelivingtombstone/tombmobilehiphop1', '--verbose', '--add-metadata']
[debug] Encodings: locale 'UTF-8', fs 'utf-8', out 'UTF-8', pref: 'UTF-8'
[debug] youtube-dl version 2013.12.26
[debug] Python version 3.3.3 - Linux-3.12.6-1-ARCH-x86_64-with-arch-Arch-Linux
[debug] Proxy map: {}
[soundcloud] thelivingtombstone/tombmobilehiphop1: Resolving id
[soundcloud] thelivingtombstone/tombmobilehiphop1: Downloading info JSON
[download] TombMobileHiphop1-31218527.m4a has already been downloaded
[ffmpeg] Adding metadata to 'TombMobileHiphop1-31218527.m4a'
[debug] ffmpeg command line: ffmpeg -y -i TombMobileHiphop1-31218527.m4a -c copy -metadata title=TombMobileHiphop1 -metadata date=20111221 -metadata 'artist=The Living Tombstone' -f m4a TombMobileHiphop1-31218527.m4a.temp
ERROR: TombMobileHiphop1-31218527.m4a.temp: Invalid argument
Traceback (most recent call last):
  File "/usr/lib/python3.3/site-packages/youtube_dl/YoutubeDL.py", line 942, in post_process
    keep_video_wish, new_info = pp.run(info)
  File "/usr/lib/python3.3/site-packages/youtube_dl/PostProcessor.py", line 508, in run
    self.run_ffmpeg(filename, temp_filename, options)
  File "/usr/lib/python3.3/site-packages/youtube_dl/PostProcessor.py", line 102, in run_ffmpeg
    self.run_ffmpeg_multiple_files([path], out_path, opts)
  File "/usr/lib/python3.3/site-packages/youtube_dl/PostProcessor.py", line 99, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
youtube_dl.PostProcessor.FFmpegPostProcessorError: TombMobileHiphop1-31218527.m4a.temp: Invalid argument
```

**Comment by chriselrod** [comment]
I have
```
$ youtube-dl --version
2021.12.17
```
yet
```
$ youtube-dl -i --yes-playlist 'https://music.youtube.com/playlist?list=OLAK5uy_n58EKRGeKcOlbTEpKGy_98h1vVoJfFo-g&feature=share'
[youtube:tab] OLAK5uy_n58EKRGeKcOlbTEpKGy_98h1vVoJfFo-g: Downloading webpage
[download] Downloading playlist: Album - Iowa
[youtube:tab] playlist Album - Iowa: Downloading 14 videos
[download] Downloading video 1 of 14
[youtube] L871Dxqj_gU: Downloading webpage
[download] Destination: /home/chriselrod/Music/Album - Iowa/01-[515].m4a
[download] 100% of 948.29KiB in 00:21
[ffmpeg] Correcting container in "/home/chriselrod/Music/Album - Iowa/01-[515].m4a"
[ffmpeg] Post-process file /home/chriselrod/Music/Album - Iowa/01-[515].m4a exists, skipping
[ffmpeg] Adding metadata to '/home/chriselrod/Music/Album - Iowa/01-[515].m4a'
ERROR: file:/home/chriselrod/Music/Album - Iowa/01-[515].temp.m4a: Invalid argument
```
With config
```
# Always extract audio
-x

# Do not copy the mtime
--no-mtime

--add-metadata

-o '~/Music/%(playlist_title)s/%(playlist_index)s-%(title)s.%(ext)s'
```

**Comment by dirkf** [comment]
Your problem is similar to the original but not the same. If you want help with it, posting in an ancient closed issue is probably not the right thing. You should open a new issue, unless an issue for the actual same problem is already active (#30839).

**Comment by chriselrod** [comment]
FWIW, I'm now using a different computer (one where the distro is willing to ship proprietary software) to download, and then rsyncing. Seemed easier, and seems to avoid the problem.
