### ISSUE TITLE
http://www.franceinter.fr/emission-la-marche-de-l-histoire-l-histoire-dans-les-jeux-video

### ISSUE THREAD

**Issue by Rudloff** [rg3/youtube-dl#2105]
Hello,
It would be nice to be able to download http://www.franceinter.fr/emission-la-marche-de-l-histoire-l-histoire-dans-les-jeux-video (or http://www.franceinter.fr/player/reecouter?play=793962).

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.franceinter.fr/emission-la-marche-de-l-histoire-l-histoire-dans-les-jeux-video']
[debug] Encodings: locale 'UTF-8', fs 'UTF-8', out 'UTF-8', pref: 'UTF-8'
[debug] youtube-dl version 2014.01.05.6
[debug] Python version 2.7.3 - Linux-3.2.0-4-amd64-x86_64-with-debian-7.3
[debug] Proxy map: {}
[generic] emission-la-marche-de-l-histoire-l-histoire-dans-les-jeux-video: Requesting header
WARNING: Falling back on generic information extractor.
[generic] emission-la-marche-de-l-histoire-l-histoire-dans-les-jeux-video: Downloading webpage
[generic] emission-la-marche-de-l-histoire-l-histoire-dans-les-jeux-video: Extracting information
ERROR: Unsupported URL: http://www.franceinter.fr/emission-la-marche-de-l-histoire-l-histoire-dans-les-jeux-video; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 489, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 150, in extract
    return self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/generic.py", line 331, in _real_extract
    raise ExtractorError(u'Unsupported URL: %s' % url)
ExtractorError: Unsupported URL: http://www.franceinter.fr/emission-la-marche-de-l-histoire-l-histoire-dans-les-jeux-video; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

```

Regards,

**Comment by dstftw** [comment]
Closed as per a942d6cb48994c5ff14ccef8773fb086a5544970.
