### ISSUE TITLE
[lynda course] ERROR: unable to download video data: HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by blnk** [rg3/youtube-dl#2185]
Downloading works on some courses, doesn’t work on others.

 ```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-u', '<PRIVATE>', '-p', '<PRIVATE>', 'http://www.lynda.com/Mac-OS-X-10-6-tutorials/Unix-for-Mac-OS-X-Users/78546-2.html', '--verbose']
[debug] Encodings: locale 'UTF-8', fs 'utf-8', out 'UTF-8', pref: 'UTF-8'
[debug] youtube-dl version 2014.01.17.2
[debug] Python version 2.7.5 - Darwin-13.0.0-x86_64-i386-64bit
[debug] Proxy map: {}
[lynda:course] 78546: Downloading course JSON
[download] Downloading playlist: Unix for Mac OS X Users
[lynda:course] playlist 'Unix for Mac OS X Users': Collected 82 video ids (downloading 82 of them)
[download] Downloading video #1 of 82
[lynda] Logging in as ________
[lynda] 83608: Downloading video JSON
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 923, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 907, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 290, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 52, in real_download
    data = compat_urllib_request.urlopen(request)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found
 ```

**Comment by dstftw** [comment]
This will be fixed in the next version. Thanks for the report.

**Comment by phihag** [comment]
The fix made it into youtube-dl 2015.01.25. See [our FAQ](https://yt-dl.org/update) if you need help updating.

**Comment by aimkeepachieve** [comment]
You may also refer to this step by step guide to download lynda course, videos to MP4, MOV, AVI, WMV, 3GP etc on Mac or Windows  at http://www.allavsoft.com/how-to/lynda-video-downloader.html

**Comment by availablespace** [comment]
I use Allavsoft to download Lynda video courses at  http://www.allavsoft.com/how-to/lynda-video-downloader.html

It can directly download Lynda courses to MP4, AVI, WMV, 3GP, MOV, MKV, MP3, WAV etc.
