### ISSUE TITLE
Add vk.com authentification options

### ISSUE THREAD

**Issue by spvkgn** [rg3/youtube-dl#2206]
Many videos on vk.com are private and can be watched only when logged in. Would be nice if you could add authentification options for vk.com. I can watch this video in browser when I logged in.

youtube-dl -vg http://vk.com/video-8871596_164049491
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-vg', 'http://vk.com/video-8871596_164049491']
[debug] Encodings: locale 'UTF-8', fs 'UTF-8', out 'UTF-8', pref: 'UTF-8'
[debug] youtube-dl version 2014.01.23
[debug] Python version 2.7.3 - Linux-3.2.0-39-generic-i686-with-LinuxMint-13-maya
[debug] Proxy map: {}
ERROR: Unable to extract vars; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/home/pavel/apps/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 497, in extract_info
    ie_result = ie.extract(url)
  File "/home/pavel/apps/bin/youtube-dl/youtube_dl/extractor/common.py", line 157, in extract
    return self._real_extract(url)
  File "/home/pavel/apps/bin/youtube-dl/youtube_dl/extractor/vk.py", line 46, in _real_extract
    data_json = self._search_regex(r'var vars = ({.*?});', info_page, 'vars')
  File "/home/pavel/apps/bin/youtube-dl/youtube_dl/extractor/common.py", line 352, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract vars; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by spvkgn** [comment]
Can you please take a look at this issue with authentication on vk.com ? https://github.com/rg3/youtube-dl/issues/4967
