### ISSUE TITLE
youtube-dl using wrong file names internally for video with Russian title

### ISSUE THREAD

**Issue by hurda** [rg3/youtube-dl#2225]
youtube-dl version 2014.01.23.4

URL: https://www.youtube.com/watch?v=8ke_HEaWrLY

Console-log:
```
C:\Users\user\Desktop>youtube-dl.exe -f 134+140 https://www.youtube.com/watch?v=8ke_HEaWrLY
[youtube] Setting language
[youtube] 8ke_HEaWrLY: Downloading webpage
[youtube] 8ke_HEaWrLY: Downloading video info webpage
[youtube] 8ke_HEaWrLY: Extracting video information
[download] Destination:   ,  -8ke_HEaWrLY.f134.mp4
[download] 100% of 1.37MiB in 00:03
[download] Destination:   ,  -8ke_HEaWrLY.f140.m4a
[download] 100% of 586.57KiB in 00:01
[ffmpeg] Merging formats into "  ,  -8ke_HEaWrLY.mp4"
ERROR:   ,  -8ke_HEaWrLY.f134.mp4: No such file or directory
```

But the names of the downloaded files are `Супер Быстрая Девочка, Нереальная Скорость-8ke_HEaWrLY.f134.mp4` and `Супер Быстрая Девочка, Нереальная Скорость-8ke_HEaWrLY.f140.m4a`.

It's working with `--restrict-filenames`, but it shouldn't be necessary.

PS: I know `-f 134+140` isn't necessary for this video, it was just a test.

EDIT:
```
C:\Users\user\Desktop>youtube-dl.exe -f 134+140 -v https://www.youtube.com/watch?v=8ke_HEaWrLY
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-f', '134+140', '-v', 'https://www.youtube.com/watch?v=8ke_HEaWrLY']
[debug] Encodings: locale 'cp1252', fs 'mbcs', out 'cp850', pref: 'cp1252'
[debug] youtube-dl version 2014.01.23.4
[debug] Python version 2.7.5 - Windows-7-6.1.7601-SP1
[debug] Proxy map: {}
[youtube] Setting language
[youtube] 8ke_HEaWrLY: Downloading webpage
[youtube] 8ke_HEaWrLY: Downloading video info webpage
[youtube] 8ke_HEaWrLY: Extracting video information
[download] Destination:   ,  -8ke_HEaWrLY.f134.mp4
[download] 100% of 1.37MiB in 00:02
[download] Destination:   ,  -8ke_HEaWrLY.f140.m4a
[download] 100% of 586.57KiB in 00:01
[ffmpeg] Merging formats into "  ,  -8ke_HEaWrLY.mp4"
[debug] ffmpeg command line: ffmpeg -y -i '  ,  -8ke_HEaWrLY.f134.mp4' -i '  ,
-8ke_HEaWrLY.f140.m4a' -c copy '  ,  -8ke_HEaWrLY.mp4'
ERROR:   ,  -8ke_HEaWrLY.f134.mp4: No such file or directory
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 1016, in post_process
  File "youtube_dl\postprocessor\ffmpeg.pyo", line 483, in run
  File "youtube_dl\postprocessor\ffmpeg.pyo", line 61, in run_ffmpeg_multiple_fi
les
FFmpegPostProcessorError
```

**Comment by dstftw** [comment]
This was fixed with switch to python 3.4 for Windows build.
