### ISSUE TITLE
ERROR: unable to download video data: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by eone1000** [rg3/youtube-dl#2320]
This program is awesome. However, lately the program failed to download a music video from youtube. The music video is owned by emimusic:

$ youtube-dl -x http://www.youtube.com/watch?v=_BFXCgm5270 --verbose
[debug] System config: ['--prefer-free-formats']
[debug] User config: []
[debug] Command-line args: ['-x', 'http://www.youtube.com/watch?v=_BFXCgm5270', '--verbose']
[debug] Encodings: locale 'UTF-8', fs 'UTF-8', out 'UTF-8', pref: 'UTF-8'
[debug] youtube-dl version 2014.01.23
[debug] Python version 2.6.6 - Linux-2.6.32-358.2.1.el6.x86_64-x86_64-with-centos-6.4-Final
[debug] Proxy map: {}
[youtube] Setting language
[youtube] _BFXCgm5270: Downloading webpage
[youtube] _BFXCgm5270: Downloading video info webpage
[youtube] _BFXCgm5270: Extracting video information
[youtube] _BFXCgm5270: Encrypted signatures detected.
[youtube] encrypted signature length 90 (46.43), itag 43, html5 player vfle-mVwz
[youtube] _BFXCgm5270: Downloading js player mVwz
WARNING: Writing cache to u'/home/dev1/.cache/youtube-dl/youtube-sigfuncs/js_mVwz_90.json' failed: Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 362, in _extract_signature_function
    cache_res = res(test_string)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 523, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 518, in resf
    res = interpret_statement(stmt, local_vars)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 453, in interpret_statement
    v = interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 506, in interpret_expression
    raise ExtractorError(u'Unsupported JS expression %r' % expr)
ExtractorError: Unsupported JS expression u'$y(a,7)'; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 955, in _decrypt_signature
    return func(s)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 523, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 518, in resf
    res = interpret_statement(stmt, local_vars)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 453, in interpret_statement
    v = interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 506, in interpret_expression
    raise ExtractorError(u'Unsupported JS expression %r' % expr)
ExtractorError: Unsupported JS expression u'$y(a,7)'; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

WARNING: Warning: Falling back to static signature algorithm
[youtube] encrypted signature length 90 (46.43), itag 18, html5 player vfle-mVwz
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 955, in _decrypt_signature
    return func(s)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 523, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 518, in resf
    res = interpret_statement(stmt, local_vars)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 453, in interpret_statement
    v = interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 506, in interpret_expression
    raise ExtractorError(u'Unsupported JS expression %r' % expr)
ExtractorError: Unsupported JS expression u'$y(a,7)'; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

WARNING: Warning: Falling back to static signature algorithm
[youtube] encrypted signature length 90 (46.43), itag 5, html5 player vfle-mVwz
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 955, in _decrypt_signature
    return func(s)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 523, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 518, in resf
    res = interpret_statement(stmt, local_vars)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 453, in interpret_statement
    v = interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 506, in interpret_expression
    raise ExtractorError(u'Unsupported JS expression %r' % expr)
ExtractorError: Unsupported JS expression u'$y(a,7)'; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

WARNING: Warning: Falling back to static signature algorithm
[youtube] encrypted signature length 90 (46.43), itag 36, html5 player vfle-mVwz
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 955, in _decrypt_signature
    return func(s)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 523, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 518, in resf
    res = interpret_statement(stmt, local_vars)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 453, in interpret_statement
    v = interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 506, in interpret_expression
    raise ExtractorError(u'Unsupported JS expression %r' % expr)
ExtractorError: Unsupported JS expression u'$y(a,7)'; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

WARNING: Warning: Falling back to static signature algorithm
[youtube] encrypted signature length 90 (46.43), itag 17, html5 player vfle-mVwz
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 955, in _decrypt_signature
    return func(s)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 523, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 518, in resf
    res = interpret_statement(stmt, local_vars)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 453, in interpret_statement
    v = interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 506, in interpret_expression
    raise ExtractorError(u'Unsupported JS expression %r' % expr)
ExtractorError: Unsupported JS expression u'$y(a,7)'; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

WARNING: Warning: Falling back to static signature algorithm
[youtube] encrypted signature length 85 (42.42), itag 135, html5 player vfle-mVwz
[youtube] _BFXCgm5270: Downloading js player mVwz
WARNING: Writing cache to u'/home/dev1/.cache/youtube-dl/youtube-sigfuncs/js_mVwz_85.json' failed: Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 362, in _extract_signature_function
    cache_res = res(test_string)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 523, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 518, in resf
    res = interpret_statement(stmt, local_vars)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 453, in interpret_statement
    v = interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 506, in interpret_expression
    raise ExtractorError(u'Unsupported JS expression %r' % expr)
ExtractorError: Unsupported JS expression u'$y(a,7)'; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 955, in _decrypt_signature
    return func(s)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 523, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 518, in resf
    res = interpret_statement(stmt, local_vars)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 453, in interpret_statement
    v = interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 506, in interpret_expression
    raise ExtractorError(u'Unsupported JS expression %r' % expr)
ExtractorError: Unsupported JS expression u'$y(a,7)'; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

WARNING: Warning: Falling back to static signature algorithm
[youtube] encrypted signature length 83 (40.42), itag 134, html5 player vfle-mVwz
[youtube] _BFXCgm5270: Downloading js player mVwz
WARNING: Writing cache to u'/home/dev1/.cache/youtube-dl/youtube-sigfuncs/js_mVwz_83.json' failed: Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 362, in _extract_signature_function
    cache_res = res(test_string)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 523, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 518, in resf
    res = interpret_statement(stmt, local_vars)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 453, in interpret_statement
    v = interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 506, in interpret_expression
    raise ExtractorError(u'Unsupported JS expression %r' % expr)
ExtractorError: Unsupported JS expression u'$y(a,7)'; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 955, in _decrypt_signature
    return func(s)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 523, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 518, in resf
    res = interpret_statement(stmt, local_vars)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 453, in interpret_statement
    v = interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 506, in interpret_expression
    raise ExtractorError(u'Unsupported JS expression %r' % expr)
ExtractorError: Unsupported JS expression u'$y(a,7)'; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

WARNING: Warning: Falling back to static signature algorithm
[youtube] encrypted signature length 85 (42.42), itag 133, html5 player vfle-mVwz
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 955, in _decrypt_signature
    return func(s)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 523, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 518, in resf
    res = interpret_statement(stmt, local_vars)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 453, in interpret_statement
    v = interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 506, in interpret_expression
    raise ExtractorError(u'Unsupported JS expression %r' % expr)
ExtractorError: Unsupported JS expression u'$y(a,7)'; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

WARNING: Warning: Falling back to static signature algorithm
[youtube] encrypted signature length 85 (42.42), itag 160, html5 player vfle-mVwz
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 955, in _decrypt_signature
    return func(s)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 523, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 518, in resf
    res = interpret_statement(stmt, local_vars)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 453, in interpret_statement
    v = interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 506, in interpret_expression
    raise ExtractorError(u'Unsupported JS expression %r' % expr)
ExtractorError: Unsupported JS expression u'$y(a,7)'; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

WARNING: Warning: Falling back to static signature algorithm
[youtube] encrypted signature length 85 (42.42), itag 140, html5 player vfle-mVwz
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 955, in _decrypt_signature
    return func(s)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 523, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 518, in resf
    res = interpret_statement(stmt, local_vars)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 453, in interpret_statement
    v = interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 506, in interpret_expression
    raise ExtractorError(u'Unsupported JS expression %r' % expr)
ExtractorError: Unsupported JS expression u'$y(a,7)'; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

WARNING: Warning: Falling back to static signature algorithm
[youtube] encrypted signature length 90 (46.43), itag 135, html5 player vfle-mVwz
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 955, in _decrypt_signature
    return func(s)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 523, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 518, in resf
    res = interpret_statement(stmt, local_vars)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 453, in interpret_statement
    v = interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 506, in interpret_expression
    raise ExtractorError(u'Unsupported JS expression %r' % expr)
ExtractorError: Unsupported JS expression u'$y(a,7)'; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

WARNING: Warning: Falling back to static signature algorithm
[youtube] encrypted signature length 90 (46.43), itag 134, html5 player vfle-mVwz
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 955, in _decrypt_signature
    return func(s)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 523, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 518, in resf
    res = interpret_statement(stmt, local_vars)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 453, in interpret_statement
    v = interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 506, in interpret_expression
    raise ExtractorError(u'Unsupported JS expression %r' % expr)
ExtractorError: Unsupported JS expression u'$y(a,7)'; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

WARNING: Warning: Falling back to static signature algorithm
[youtube] encrypted signature length 90 (46.43), itag 133, html5 player vfle-mVwz
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 955, in _decrypt_signature
    return func(s)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 523, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 518, in resf
    res = interpret_statement(stmt, local_vars)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 453, in interpret_statement
    v = interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 506, in interpret_expression
    raise ExtractorError(u'Unsupported JS expression %r' % expr)
ExtractorError: Unsupported JS expression u'$y(a,7)'; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

WARNING: Warning: Falling back to static signature algorithm
[youtube] encrypted signature length 90 (46.43), itag 160, html5 player vfle-mVwz
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 955, in _decrypt_signature
    return func(s)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 523, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 518, in resf
    res = interpret_statement(stmt, local_vars)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 453, in interpret_statement
    v = interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 506, in interpret_expression
    raise ExtractorError(u'Unsupported JS expression %r' % expr)
ExtractorError: Unsupported JS expression u'$y(a,7)'; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

WARNING: Warning: Falling back to static signature algorithm
[youtube] encrypted signature length 90 (46.43), itag 140, html5 player vfle-mVwz
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 955, in _decrypt_signature
    return func(s)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 523, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 518, in resf
    res = interpret_statement(stmt, local_vars)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 453, in interpret_statement
    v = interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 506, in interpret_expression
    raise ExtractorError(u'Unsupported JS expression %r' % expr)
ExtractorError: Unsupported JS expression u'$y(a,7)'; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

WARNING: Warning: Falling back to static signature algorithm
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 955, in process_info
    success = dl(filename, info_dict)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 931, in dl
    return fd.download(name, info)
  File "/usr/bin/youtube-dl/youtube_dl/downloader/common.py", line 290, in download
    return self.real_download(filename, info_dict)
  File "/usr/bin/youtube-dl/youtube_dl/downloader/http.py", line 52, in real_download
    data = compat_urllib_request.urlopen(request)
  File "/usr/lib64/python2.6/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib64/python2.6/urllib2.py", line 397, in open
    response = meth(req, response)
  File "/usr/lib64/python2.6/urllib2.py", line 510, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.6/urllib2.py", line 435, in error
    return self._call_chain(_args)
  File "/usr/lib64/python2.6/urllib2.py", line 369, in _call_chain
    result = func(_args)
  File "/usr/lib64/python2.6/urllib2.py", line 518, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden

**Comment by matrixdownload** [comment]
Ho provato a capire da cosa potesse dipendere , ho risolto facendo una lista dei formati  cambiando il formato del download , dovevo estrarre l'audio dal video e scarcarlo , la richiesta era .mp3  ma ottenevo questo errore anche io ..ma facendo una lista dei formati non era presente in elenco , quindi ho inserito altro formato pensando che potesse essere questo il problema  , quindi ho inserito altr formato audio m4a ed il download è riuscito.   spero possa dipendere da questo anche nel vostro caso.   comunque ha funzionato non ho piu' otttenuto quell'errore.

**Comment by matrixdownload** [comment]
ho ottenuto ancora quell'errore ed ho risolto in uno scenario in cui volevo estrarre soltanto l'audio in questo modo , ho fatto una lista dei formati ed ho provato ad inserire altro formato invece di mp3 , in questo secondo caso ho risolto inserendo questa stringa: users\youtube-dl.exe  --extract-audio ytsearch:webm  https://nomevideo   invece di m4a   ed al posto di mp3 con i quali ottenevo errore , magari vi è utile per capire da cosa dipende e per trovare una alternativa temporanea.

**Comment by matrixdownload** [comment]
potrebbe esservi utile confrontare queste due stringhe ? in una ha funzionato la conversione ed il download nel caso di youtube-dl invece ho ottenuto il solito errore forbidden  ..

http://www.xxxxxxxxxxx.com/music?vid=BhmloO5m158&s=youtube&ext=.mp3&conv=2&format=0&displayid=BhmloO5m158&audiourl=https%3A%2F%2Fr6---sn-u2oxu-f5f6.googlevideo.com%2Fvideoplayback%3Fms%3Dau%26mv%3Dm%26mt%3D1439886373%26upn%3DOYXD5u3Oi6c%26mn%3Dsn-u2oxu-f5f6%26mm%3D31%26key%3Dyt6%26mime%3Dvideo%2Fmp4%26expire%3D1439908038%26itag%3D18%26sver%3D3%26lmt%3D1394256909897168%26ipbits%3D0%26pcm2cms%3Dyes%26gcr%3Dfr%26source%3Dyoutube%26ratebypass%3Dyes%26pl%3D20%26initcwndbps%3D1161250%26dur%3D255.094%26requiressl%3Dyes%26id%3Do-ABvxvqOgkNH20aXp88G0-sBrU_belIwrJm7bgm_TxlgT%26fexp%3D9408144%2C9408541%2C9408710%2C9409069%2C9409249%2C9414703%2C9415365%2C9415436%2C9415485%2C9415656%2C9416023%2C9416126%2C9416837%2C9417000%2C9417368%2C9417578%2C9417707%2C9418153%2C9418235%2C9419339%2C9419445%26sparams%3Ddur%2Cgcr%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire%26ip%3Dxxx.xxx.xxx.xxx%26signature%3D6E61885236AEF41872E84ED1C857809A468DCEBD.180C4858BBD21719AB18C1016F752730E2BF9AC9%26title%3Daudio

stringa youtube-dl con errore

https://r5---sn-hpa7lne7.googlevideo.com/videoplayback?initcwndbps=631250&source=youtube&dur=255.
094&clen=4052088&fexp=9405348%2C9405994%2C9407991%2C9408212%2C9408710%2C9409069%2C9409207%2C9412842%2C9415365%2C9415485%2C9415868%
2C9416023%2C9416126%2C9416521%2C9416575%2C9416729%2C9417285%2C9417707%2C9417827%2C9417938%2C9418153%2C9418184&expire=1439907917&gc
r=it&itag=140&keepalive=yes&mm=31&requiressl=yes&ms=au&mv=m&mt=1439886262&sparams=clen%2Cdur%2Cgcr%2Cgir%2Cid%2Cinitcwndbps%2Cip%2
Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&pl=16&id=o-ALbeUV4iYWzGepnAQ
4y2VPmifKmZDkhrp4Cse2djwKPP&mime=audio%2Fmp4&sver=3&gir=yes&mn=sn-hpa7lne7&ip=xx.xx.xxx.xxx&key=yt5&ipbits=0&lmt=1394256903901242&u
pn=uYhs8VioemI&signature=923F988173765E9340AE3354A5BDFADD1178EBC6.8285D88E99283ECCF340F8AA5B07F152DD9FBC57&ratebypass=yes

**Comment by chernikalxde** [comment]
Hey !!
Just run >> youtube-dl --rm-cache-dir
It will remove cache dir and solve the issue. It helped me =)
