### ISSUE TITLE
86 character or longer search text bugs

### ISSUE THREAD

**Issue by davidhedlund** [rg3/youtube-dl#2348]
The original title "Electric Scientists - Do You Seek Knowledge In Time Travel (Electric Universe & G.M.S Collaboration)" is 101 character. Lots of original titles are longer than 100 characters of everything ever released (see discogs.com). I suggest that you set the limit to 200.

[youtube:search] query "Electric Universe - Do You Seek Knowledge In Time Travel (Electric Universe & G.M.S Collaboration)": Downloading page 1
ERROR: [youtube] No video results; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 493, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 158, in extract
    return self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 562, in _real_extract
    return self._get_n_results(query, n)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1696, in _get_n_results
    raise ExtractorError(u'[youtube] No video results')
ExtractorError: [youtube] No video results; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by davidhedlund** [comment]
@jaimeMF @dstftw Fixed, I tested this successfully:
> youtube-dl "ytsearch:DJ Maretimo - Best Of Del Mar Vol.2 (part 1) continuous DJ mix, HD, 2017, Chillout Cafe Sounds"
