### ISSUE TITLE
ERROR: unable to download video data: HTTP Error 410: Gone

### ISSUE THREAD

**Issue by davidhedlund** [rg3/youtube-dl#2352]
youtube-dl --version
2014.02.08.2

youtube-dl "ytsearch10:Etnica - Floating Universe" -f 43 --verbose --max-downloads 1
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['ytsearch10:Etnica - Floating Universe', '-f', '43', '--verbose', '--max-downloads', '1']
[debug] Encodings: locale 'UTF-8', fs 'UTF-8', out 'UTF-8', pref: 'UTF-8'
[debug] youtube-dl version 2014.02.08.2
[debug] Python version 2.7.3 - Linux-3.2.0-58-generic-x86_64-with-Trisquel-6.0-toutatis
[debug] Proxy map: {}
[youtube:search] query "Etnica - Floating Universe": Downloading page 1
[download] Downloading playlist: Etnica - Floating Universe
[youtube:search] playlist Etnica - Floating Universe: Collected 10 video ids (downloading 10 of them)
[download] Downloading video #1 of 10
[youtube] Setting language
[youtube] m34r0BLy5YU: Downloading webpage
[youtube] m34r0BLy5YU: Downloading video info webpage
[youtube] m34r0BLy5YU: Extracting video information
ERROR: unable to download video data: HTTP Error 410: Gone
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 953, in process_info
    success = dl(filename, info_dict)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 929, in dl
    return fd.download(name, info)
  File "/usr/bin/youtube-dl/youtube_dl/downloader/common.py", line 290, in download
    return self.real_download(filename, info_dict)
  File "/usr/bin/youtube-dl/youtube_dl/downloader/http.py", line 52, in real_download
    data = compat_urllib_request.urlopen(request)
  File "/usr/lib/python2.7/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 406, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 519, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 444, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 527, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 410: Gone

**Comment by davidhedlund** [comment]
@dstftw @jaimeMF Great, I cannot reproduce the same error with youtube-dl 2016.04.06.
