### ISSUE TITLE
Unable to extract OpenGraph title

### ISSUE THREAD

**Issue by sirinath** [rg3/youtube-dl#2359]
Following error

C:\Downloads>youtube-dl -i -w -c -r 100k -f mp4 -v -o "%(uploader)s\%(playlist)s
\%(playlist_index)s-%(title)s-%(id)s.%(ext)s" http://www.youtube.com/playlist?li
st=UUQJ6ESCWQotBwtJm0Ff_gyQ
Waiting for file handle to be closed ...
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-i', '-w', '-c', '-r', '100k', '-f', 'mp4', '-v', '
-o', '%(uploader)s\%(playlist)s\%(playlist_index)s-%(title)s-%(id)s.%(ext)s',
'http://www.youtube.com/playlist?list=UUQJ6ESCWQotBwtJm0Ff_gyQ']
[debug] youtube-dl version 2013.12.04
[debug] Python version 2.7.5 - Windows-8-6.2.9200
[debug] Proxy map: {}
[youtube:playlist] UUQJ6ESCWQotBwtJm0Ff_gyQ: Downloading page #1
ERROR: Unable to extract OpenGraph title; please report this issue on https://yt
-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its
 complete output. Make sure you are using the latest version; type  youtube-dl -
U  to update.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 429, in extract_info
  File "youtube_dl\extractor\common.pyo", line 131, in extract
  File "youtube_dl\extractor\youtube.pyo", line 1604, in _real_extract
  File "youtube_dl\extractor\common.pyo", line 356, in _og_search_title
  File "youtube_dl\extractor\common.pyo", line 344, in _og_search_property
  File "youtube_dl\extractor\common.pyo", line 284, in _search_regex
RegexNotFoundError: Unable to extract OpenGraph title; please report this issue
on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag an
d include its complete output. Make sure you are using the latest version; type
 youtube-dl -U  to update.

**Comment by hakermania** [comment]
```
youtube-dl --verbose --audio-quality 0 'https://www.youtube.com/watch?v=X0ESbFwt7hk&index=10&list=PLoSPhha8FysVbAnwnhY1TbLLgR5pkmL7g'[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '--audio-quality', '0', 'https://www.youtube.com/watch?v=X0ESbFwt7hk&index=10&list=PLoSPhha8FysVbAnwnhY1TbLLgR5pkmL7g']
[debug] Encodings: locale 'UTF-8', fs 'UTF-8', out 'UTF-8', pref: 'UTF-8'
[debug] youtube-dl version 2014.02.06
[debug] Python version 2.7.8 - Linux-3.16.0-30-generic-x86_64-with-Ubuntu-14.10-utopic
[debug] Proxy map: {}
[youtube:playlist] Downloading playlist PLPLoSPhha8FysVbAnwnhY1TbLLgR5pkmL7g - add --no-playlist to just download video X0ESbFwt7hk
[youtube:playlist] PLoSPhha8FysVbAnwnhY1TbLLgR5pkmL7g: Downloading page #1
WARNING: [youtube:playlist] PLoSPhha8FysVbAnwnhY1TbLLgR5pkmL7g: Playlist page is missing OpenGraph title, falling back ...
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1510, in _real_extract
    playlist_title = self._og_search_title(page)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 425, in _og_search_title
    return self._og_search_property('title', html, **kargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 413, in _og_search_property
    escaped = self._search_regex(self._og_regexes(prop), html, name, flags=re.DOTALL, **kargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 353, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract OpenGraph title; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 493, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 158, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1516, in _real_extract
    r'<h1 class="pl-header-title">(.*?)</h1>', page, u'title')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 363, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 353, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
```

Same problem here with the latest version as for now.

**Comment by phihag** [comment]
@hakermania Your version is over a year old. Since we release nearly every day, I cannot fathom why you'd think of it as the latest. Running `sudo youtube-dl -U` once should be sufficient to update.

**Comment by hakermania** [comment]
You are absolutely right. I was almost sure that it wrote 2015 there and not 2014. My bad.
