### ISSUE TITLE
Unable to extract title

### ISSUE THREAD

**Issue by ardezo** [rg3/youtube-dl#2429]
youtube-dl --verbose  'http://www.youtube.com/watch?v=tqPOF_G5GBM&list=PLBD65F319DF307821'
[debug] System config: []
[debug] User config: ['--restrict-filenames', '-t']
[debug] Command-line args: ['--verbose', 'http://www.youtube.com/watch?v=tqPOF_G5GBM&list=PLBD65F319DF307821']
[debug] Encodings: locale 'UTF-8', fs 'UTF-8', out 'UTF-8', pref: 'UTF-8'
[debug] youtube-dl version 2014.02.20
[debug] Python version 2.7.3 - Linux-3.2.0-59-generic-x86_64-with-Ubuntu-12.04-precise
[debug] Proxy map: {}
[youtube:playlist] Downloading playlist PLPLBD65F319DF307821 - add --no-playlist to just download video tqPOF_G5GBM
[youtube:playlist] PLBD65F319DF307821: Downloading page #1
WARNING: [youtube:playlist] PLBD65F319DF307821: Playlist page is missing OpenGraph title, falling back ...
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 1512, in _real_extract
    playlist_title = self._og_search_title(page)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 428, in _og_search_title
    return self._og_search_property('title', html, *_kargs)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 416, in _og_search_property
    escaped = self._search_regex(self._og_regexes(prop), html, name, flags=re.DOTALL, *_kargs)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 356, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract OpenGraph title; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 493, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 158, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 1518, in _real_extract
    r'<h1 class="pl-header-title">(.*?)</h1>', page, u'title')
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 366, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 356, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

I did execute 
sudo apt-get update
sudo apt-get upgrade
and still get this error

**Comment by Lujaw** [comment]
had the same problem, solved after removing the package installed using apt-get and reinstalling from the source using curl..
