### ISSUE TITLE
Viddler sample failed

### ISSUE THREAD

**Issue by xubuntu4iran** [rg3/youtube-dl#2466]
<pre>youtube-dl -v https://learnenglish.britishcouncil.org/en/word-street/big-meal-scene-2-language-focus
[debug] System config: []
[debug] User config: ['--proxy', 'http://localhost:8118']
[debug] Command-line args: ['-v', 'https://learnenglish.britishcouncil.org/en/word-street/big-meal-scene-2-language-focus']
[debug] Encodings: locale 'UTF-8', fs 'UTF-8', out 'UTF-8', pref: 'UTF-8'
[debug] youtube-dl version 2014.02.26
[debug] Python version 2.7.5 - Linux-3.13.3-201.fc20.i686-i686-with-fedora-20-Heisenbug
[debug] Proxy map: {u'http': 'http://localhost:8118', u'https': 'http://localhost:8118'}
[generic] big-meal-scene-2-language-focus: Requesting header
WARNING: Falling back on generic information extractor.
[generic] big-meal-scene-2-language-focus: Downloading webpage
[generic] big-meal-scene-2-language-focus: Extracting information
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 953, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 929, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 290, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 52, in real_download
    data = compat_urllib_request.urlopen(request)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden
</pre>

**Comment by HyShai** [comment]
Seems to be an issue with the video - can't get the video to play in a browser, getting a 404 for the [video url](https://bclearnenglish-vfs.cdn-ec.viddler.com/BCLearnenglish_1jmltmo0hxssvw0fe0658tpop14q3h.flv?fd9f2a1c14aadf1069f046ce65f41e2be6a8a954d660046f2dd7ff5c15d014baff130114d7272d4b6a7983d7ecff83ec50534d32f48bf77ec7fe47b87d275f3a7608c13087abd88d0070fe8bae39247074dbb10fba65&ec_rate=181&ec_prebuf=10).

**Comment by dstftw** [comment]
Thanks for the report. This will be fixed in the next version of youtube-dl.
