### ISSUE TITLE
error in tune.pk extractor 

### ISSUE THREAD

**Issue by fehmitn** [rg3/youtube-dl#24905]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.03.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```
youtube-dl "https://tune.pk/video/8763931/ntsfr-mlb-p03e01-arabic"
[TunePk] 8763931: Downloading webpage
ERROR: Unable to extract tune player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
fehmi@DESKTOP-5NS3UTH:~$ youtube-dl "https://tune.pk/video/8763931/ntsfr-mlb-p03e01-arabic" --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://tune.pk/video/8763931/ntsfr-mlb-p03e01-arabic', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.03.24
[debug] Python version 2.7.17 (CPython) - Linux-4.4.0-18362-Microsoft-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6, phantomjs ., rtmpdump 2.4
[debug] Proxy map: {}
[TunePk] 8763931: Downloading webpage
ERROR: Unable to extract tune player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/tunepk.py", line 52, in _real_extract
    r'new\s+TunePlayer\(({.+?})\)\s*;\s*\n', webpage, 'tune player'),
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract tune player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Description

can't download video from this page
https://tune.pk/video/8763931/ntsfr-mlb-p03e01-arabic

WRITE DESCRIPTION HERE

**Comment by temtemy** [comment]
Duplicate of #17953?
