### ISSUE TITLE
FoodNetwork/DIYNework Support??

### ISSUE THREAD

**Issue by ghost** [rg3/youtube-dl#2504]
Hello!  Is there any chance of adding support for http://www.foodnetwork.com/ or http://www.doityourself.com/???

**Comment by asc6** [comment]
Very interested in adding foodnetwork.com as well. Still not compatible w/ version 2017.03.26

**Comment by WolfganP** [comment]
I tried with foodnetwork.ca and ytdl failed as well:

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--force-ipv4', '--ffmpeg-location', 'D:\\_Downloads\\AV_edition\\ffmpeg\\bin', '--geo-bypass-country', 'CA', 'http://www.foodnetwork.ca/shows/top-chef-canada/video/episode/retail-wars/video.html?v=926949443651', '-F']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.05.01
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg 3.2.4, ffprobe 3.2.4
[debug] Proxy map: {}
[debug] Using fake IP 99.251.89.130 (CA) as X-Forwarded-For.
[Corus] 926949443651: Downloading JSON metadata
[Corus] 926949443651: Downloading SMIL data for MP4 MBR
[Corus] 926949443651: Downloading SMIL data for medium
[Corus] 926949443651: Downloading SMIL data for MP4
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0io2aq9r\build\youtube_dl\YoutubeDL.py", line 760, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0io2aq9r\build\youtube_dl\extractor\common.py", line 429, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0io2aq9r\build\youtube_dl\extractor\corus.py", line 72, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0io2aq9r\build\youtube_dl\extractor\theplatform.py", line 343, in _extract_feed_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp0io2aq9r\build\youtube_dl\extractor\common.py", line 1052, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by dstftw** [comment]
foodnetwork.ca is geo restricted to CA.

**Comment by WolfganP** [comment]
Thx @dstftw. I know it's georestricted and that's why I run the test with '--geo-bypass-country CA' (I have no issues with australian sites, so I assumed this should work as well)

**Comment by dstftw** [comment]
>I know it's georestricted and that's why I run the test with '--geo-bypass-country CA'

It's **not supposed to work in all cases**. Bypass **will only work** for sites that respect X-Forwarded-For.
