### ISSUE TITLE
Unsupported page

### ISSUE THREAD

**Issue by Popolon** [rg3/youtube-dl#2525]
youtube-dl --verbose http://www.arte.tv/fr/7541126.html

[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.arte.tv/fr/7541126.html']
[debug] Encodings: locale 'UTF-8', fs 'UTF-8', out 'UTF-8', pref: 'UTF-8'
[debug] youtube-dl version 2014.03.06
[debug] Python version 2.7.5+ - Linux-3.11.0-17-generic-x86_64-with-Ubuntu-13.10-saucy
[debug] Proxy map: {}
[generic] 7541126: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 7541126: Downloading webpage
[generic] 7541126: Extracting information
ERROR: Unsupported URL: http://www.arte.tv/fr/7541126.html; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 277, in _real_extract
    doc = xml.etree.ElementTree.fromstring(webpage.encode('utf-8'))
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 2, column 54
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 500, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 162, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 472, in _real_extract
    raise ExtractorError('Unsupported URL: %s' % url)
ExtractorError: Unsupported URL: http://www.arte.tv/fr/7541126.html; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by dstftw** [comment]
Example URL http://www.arte.tv/fr/7541126.html has gone.
