### ISSUE TITLE
Failure to download CNN video

### ISSUE THREAD

**Issue by mcepl** [rg3/youtube-dl#2572]
```
matej@wycliff: ~$ youtube-dl --verbose 'http://edition.cnn.com/2014/03/16/world/europe/ukraine-crisis/index.html?hpt=hp_t1'
[debug] System config: ['--prefer-free-formats']
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://edition.cnn.com/2014/03/16/world/europe/ukraine-crisis/index.html?hpt=hp_t1']
[debug] Encodings: locale 'UTF-8', fs 'UTF-8', out 'UTF-8', pref: 'UTF-8'
[debug] youtube-dl version 2014.03.07.1
[debug] Python version 2.7.5 - Linux-3.10.0-108.el7.x86_64-x86_64-with-redhat-7.0-Maipo
[debug] Proxy map: {}
[generic] index: Requesting header
WARNING: Falling back on generic information extractor.
[generic] index: Downloading webpage
[generic] index: Extracting information
ERROR: Unsupported URL: http://edition.cnn.com/2014/03/16/world/europe/ukraine-crisis/index.html?hpt=hp_t1; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/extractor/generic.py", line 277, in _real_extract
    doc = xml.etree.ElementTree.fromstring(webpage.encode('utf-8'))
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 2, column 16
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 500, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 162, in extract
    return self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/generic.py", line 472, in _real_extract
    raise ExtractorError('Unsupported URL: %s' % url)
ExtractorError: Unsupported URL: http://edition.cnn.com/2014/03/16/world/europe/ukraine-crisis/index.html?hpt=hp_t1; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
```

**Comment by dstftw** [comment]
Works with latest version.

**Comment by mcepl** [comment]
Yes, it does. Thanks.
