### ISSUE TITLE
add-metadata gets year wrong and crashes on strange characters

### ISSUE THREAD

**Issue by svrnwnsch** [rg3/youtube-dl#2583]
If I run "youtube-dl https://www.youtube.com/watch?v=sHF1q1qGuNU -f 1
37+140 --embed-subs --add-metadata" the year presented under windows is 11065 which should be more like 17.06.2013 as this is the day when the video was uploaded. 

Also if I run "youtube-dl https://www.youtube.com/watch?v=Pv-Do30-P8A -f 1
37+140 --add-metadata -v" I get the Traceback:

[ffmpeg] Adding metadata to 'SOFLES ù LIMITLESS.-Pv-Do30-P8A.mp4'
[debug] ffmpeg command line: ffmpeg -y -i 'SOFLES ù LIMITLESS.-Pv-Do30-P8A.mp4'
-c copy -metadata date=20131122 -metadata artist=ironlakfilms -metadata 'title=S
OFLES ù LIMITLESS.' 'SOFLES ù LIMITLESS.-Pv-Do30-P8A.temp.mp4'
Traceback (most recent call last):
  File "__main__.py", line 18, in <module>
  File "youtube_dl\__init__.pyo", line 811, in main
  File "youtube_dl\__init__.pyo", line 801, in _real_main
  File "youtube_dl\YoutubeDL.pyo", line 1016, in download
  File "youtube_dl\YoutubeDL.pyo", line 521, in extract_info
  File "youtube_dl\YoutubeDL.pyo", line 550, in process_ie_result
  File "youtube_dl\YoutubeDL.pyo", line 797, in process_video_result
  File "youtube_dl\YoutubeDL.pyo", line 999, in process_info
  File "youtube_dl\YoutubeDL.pyo", line 1050, in post_process
  File "youtube_dl\postprocessor\ffmpeg.pyo", line 472, in run
  File "youtube_dl\postprocessor\ffmpeg.pyo", line 64, in run_ffmpeg
  File "youtube_dl\postprocessor\ffmpeg.pyo", line 56, in run_ffmpeg_multiple_fi
les
  File "subprocess.pyo", line 711, in __init__
  File "subprocess.pyo", line 907, in _execute_child
  File "subprocess.pyo", line 646, in list2cmdline
UnicodeDecodeError: 'ascii' codec can't decode byte 0x97 in position 0: ordinal
not in range(128)

**Comment by dstftw** [comment]
Works fine with latest version.
