### ISSUE TITLE
Cannot download tv-replay

### ISSUE THREAD

**Issue by unbewusst** [rg3/youtube-dl#2620]
$ youtube-dl --verbose -o x-enius-arte.mp4 http://www.tv-replay.fr/redirection/20-03-14/x-enius-arte-10753389.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '-o', 'x-enius-arte.mp4', 'http://www.tv-replay.fr/redirection/20-03-14/x-enius-arte-10753389.html']
[debug] Encodings: locale 'UTF-8', fs 'utf-8', out 'UTF-8', pref: 'UTF-8'
[debug] youtube-dl version 2014.03.21.5
[debug] Python version 2.7.5 - Darwin-12.0.0-i386-64bit
[debug] Proxy map: {}
[generic] x-enius-arte-10753389: Requesting header
WARNING: Falling back on generic information extractor.
[generic] x-enius-arte-10753389: Downloading webpage
[generic] x-enius-arte-10753389: Extracting information
ERROR: Unsupported URL: http://www.tv-replay.fr/redirection/20-03-14/x-enius-arte-10753389.html; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/Users/yt/bin/youtube-dl/youtube_dl/extractor/generic.py", line 320, in _real_extract
    doc = parse_xml(webpage)
  File "/Users/yt/bin/youtube-dl/youtube_dl/utils.py", line 1286, in parse_xml
    return xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 9, column 182
Traceback (most recent call last):
  File "/Users/yt/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 506, in extract_info
    ie_result = ie.extract(url)
  File "/Users/yt/bin/youtube-dl/youtube_dl/extractor/common.py", line 161, in extract
    return self._real_extract(url)
  File "/Users/yt/bin/youtube-dl/youtube_dl/extractor/generic.py", line 535, in _real_extract
    raise ExtractorError('Unsupported URL: %s' % url)
ExtractorError: Unsupported URL: http://www.tv-replay.fr/redirection/20-03-14/x-enius-arte-10753389.html; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by brunetton** [comment]
Hi,

Is this still supported ? I just tried with http://www.tv-replay.fr/redirection/09-04-16/arte-reportage-arte-11508975.html with *2015.06.04.1* from Debian, and *2016.04.06* from repo

<pre>
./youtube-dl 'http://www.tv-replay.fr/redirection/09-04-16/arte-reportage-arte-11508975.html'
[generic] arte-reportage-arte-11508975: Requesting header
WARNING: Falling back on generic information extractor.
[generic] arte-reportage-arte-11508975: Downloading webpage
[generic] arte-reportage-arte-11508975: Extracting information
ERROR: Unsupported URL: http://www.tv-replay.fr/redirection/09-04-16/arte-reportage-arte-11508975.html
</pre>

Is tv-replay.fr still supported ?
Thanks

**Comment by yan12125** [comment]
This page uses a different layout than the first one. In the next version youtube-dl will support both.
