### ISSUE TITLE
audio conversion failed: Audio encoding failed

### ISSUE THREAD

**Issue by Nothing4You** [rg3/youtube-dl#2655]
Hi there, `youtube-dl` was installed as binary from yt-dl.org.
I'm using `youtube-dl -v -f 22/45/35/44/18/34/43/6/5/36/17/13 -x --audio-format mp3 --audio-quality 0 -k --add-metadata ytsearch100:braindrillerz`.

```
[debug] System config: []
[debug] User config: ['-v']
[debug] Command-line args: ['-v', '-f', '22/45/35/44/18/34/43/6/5/36/17/13', '-x', '--audio-format', 'mp3', '--audio-quality', '0', '-k', '--add-metadata', 'ytsearch100:braindrillerz']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.03.30
[debug] Python version 2.7.3 - Linux-2.6.32-openvz-042stab083.2-amd64-x86_64-with-debian-7.4
[debug] Proxy map: {}
[youtube:search] query "braindrillerz": Downloading page 1
[youtube:search] query "braindrillerz": Downloading page 2
[download] Downloading playlist: braindrillerz
[youtube:search] playlist braindrillerz: Collected 100 video ids (downloading 100 of them)
[download] Downloading video #1 of 100
[youtube] Setting language
[youtube] I6_CcDGMbYs: Downloading webpage
--- SNIP ---
[download] Downloading video #66 of 100
[youtube] _GT_KUTgwIc: Downloading webpage
[youtube] _GT_KUTgwIc: Downloading video info webpage
[youtube] _GT_KUTgwIc: Extracting video information
[download] Destination: Randy vs The Braindrillerz LIVE @ FOOTWORXX 10.03.2012-_GT_KUTgwIc.mp4
[download] 100% of 19.46MiB in 00:02
[ffmpeg] Adding metadata to 'Randy vs The Braindrillerz LIVE @ FOOTWORXX 10.03.2012-_GT_KUTgwIc.mp4'
[debug] ffmpeg command line: avconv -y -i 'Randy vs The Braindrillerz LIVE @ FOOTWORXX 10.03.2012-_GT_KUTgwIc.mp4' -c copy -metadata date=20120312 -metadata artist=WonderlandsTerror -metadata 'title=Randy vs The Braindrillerz LIVE @ FOOTWORXX 10.03.2012' 'Randy vs The Braindrillerz LIVE @ FOOTWORXX 10.03.2012-_GT_KUTgwIc.temp.mp4'
[avconv] Destination: Randy vs The Braindrillerz LIVE @ FOOTWORXX 10.03.2012-_GT_KUTgwIc.mp3
[debug] ffmpeg command line: avconv -y -i 'Randy vs The Braindrillerz LIVE @ FOOTWORXX 10.03.2012-_GT_KUTgwIc.mp4' -vn -acodec libmp3lame -q:a 0 'Randy vs The Braindrillerz LIVE @ FOOTWORXX 10.03.2012-_GT_KUTgwIc.mp3'
ERROR: audio conversion failed: Audio encoding failed
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1059, in post_process
    keep_video_wish, new_info = pp.run(info)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 189, in run
    raise PostProcessingError(msg)
PostProcessingError
```

**Comment by Nothing4You** [comment]
I don't have any system with this issue anymore so I'm closing this. If someone happens to run into the same issue feel free to open a new issue for this.
