### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by requiredregistration** [rg3/youtube-dl#2679]

**Comment by zenaan** [comment]
cnet.com currently not working, ISTM:

$ youtube-dl 'http://www.cnet.com/products/samsung-un50hu8550/2/' -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://www.cnet.com/products/samsung-un50hu8550/2/', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.03.28
[debug] Python version 2.7.9 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.0
[debug] exe versions: rtmpdump 2.4
[debug] Proxy map: {}
[generic] 2: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 2: Downloading webpage
[generic] 2: Extracting information
ERROR: Unsupported URL: http://www.cnet.com/products/samsung-un50hu8550/2/
Traceback (most recent call last):
  File "/home/justa/bin/youtube-dl/youtube_dl/extractor/generic.py", line 825, in _real_extract
    doc = parse_xml(webpage)
  File "/home/justa/bin/youtube-dl/youtube_dl/utils.py", line 1528, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 28, column 570
Traceback (most recent call last):
  File "/home/justa/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 651, in extract_info
    ie_result = ie.extract(url)
  File "/home/justa/bin/youtube-dl/youtube_dl/extractor/common.py", line 275, in extract
    return self._real_extract(url)
  File "/home/justa/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1313, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.cnet.com/products/samsung-un50hu8550/2/

**Comment by zenaan** [comment]
Can't see a button to reopen an issue - are we supposed to create a new issue, or just comment on an issue like this? What about changing the subject, eg, in this case, to say "cnet.com site support request"?

debian.org website provides for logged in users to do these types of janitorial tasks, but I can't see how to do those two tasks here.

**Comment by jaimeMF** [comment]
@zenaan open a new issue. We currently only support urls like http://www.cnet.com/videos/hands-on-with-microsofts-windows-8-1-update/.
