### ISSUE TITLE
Video extractor issue at MTV

### ISSUE THREAD

**Issue by nico1975** [rg3/youtube-dl#2848]
Please find the verbose output attached

outube-dl --verbose "http://www.mtv.de/artists/8620-tiemo-hauer/video/60929-adler"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.mtv.de/artists/8620-tiemo-hauer/video/60929-adler']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.04.30.1
[debug] Python version 2.7.3 - Linux-3.2.0-61-generic-x86_64-with-Ubuntu-12.04-precise
[debug] Proxy map: {}
[generic] 60929-adler: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 60929-adler: Downloading webpage
[generic] 60929-adler: Extracting information
ERROR: Unsupported URL: http://www.mtv.de/artists/8620-tiemo-hauer/video/60929-adler; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/extractor/generic.py", line 421, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/bin/youtube-dl/youtube_dl/utils.py", line 1396, in parse_xml
    return xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1301, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1643, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1507, in _raiseerror
    raise err
ParseError: mismatched tag: line 69, column 119
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 516, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 161, in extract
    return self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/generic.py", line 682, in _real_extract
    raise ExtractorError('Unsupported URL: %s' % url)
ExtractorError: Unsupported URL: http://www.mtv.de/artists/8620-tiemo-hauer/video/60929-adler; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

Hope thate and you can fix the MTV extractor...

Regards,

Nico

**Comment by desseim** [comment]
This URL seems to be now supported in the latest version (`2015.11.21`).
I think the issue can be closed.
