### ISSUE TITLE
ServusTV.com mediathek does not work (anymore?)

### ISSUE THREAD

**Issue by grexe** [rg3/youtube-dl#2855]
tried to download the movie "Castaway" but got an error, even after debugging into the page
http://www.servustv.com/cs/Satellite/Article/Castaway---Die-Insel-011259581836730
and feeding the pesky embedded flashplayer data URL:

```
[grexe@grexbox Filme]$ youtube-dl -v -t "http://c.brightcove.com/services/viewer/federated_f9?&amp;width=892&amp;height=541&amp;flashID=stv_brightcove&amp;wmode=transparent&amp;bgcolor=000000&amp;playerID=1254928709001&amp;playerKey=AQ~~%2CAAAA0Zd2KCE~%2Ca1ZzPs5ODGffVvk2dn1CRCof3Ru_I9gE&amp;isVid=true&amp;isUI=true&amp;dynamicStreaming=true&amp;%40videoList=ref%3Aempty&amp;autoStart=&amp;debuggerID=&amp;startTime=1399229952929"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', '-t', 'http://c.brightcove.com/services/viewer/federated_f9?&amp;width=892&amp;height=541&amp;flashID=stv_brightcove&amp;wmode=transparent&amp;bgcolor=000000&amp;playerID=1254928709001&amp;playerKey=AQ~~%2CAAAA0Zd2KCE~%2Ca1ZzPs5ODGffVvk2dn1CRCof3Ru_I9gE&amp;isVid=true&amp;isUI=true&amp;dynamicStreaming=true&amp;%40videoList=ref%3Aempty&amp;autoStart=&amp;debuggerID=&amp;startTime=1399229952929']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.04.30.1
[debug] Python version 2.7.6 - Linux-3.12.15-1-CHAKRA-x86_64-with-chakra
[debug] Proxy map: {}
[Brightcove] AQ~~,AAAA0Zd2KCE~,a1ZzPs5ODGffVvk2dn1CRCof3Ru_I9gE: Downloading playlist information
ERROR: Empty playlist; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 516, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 161, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/brightcove.py", line 177, in _real_extract
    return self._get_playlist_info(player_key[0])
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/brightcove.py", line 204, in _get_playlist_info
    raise ExtractorError('Empty playlist')
ExtractorError: Empty playlist; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
```

**Comment by dstftw** [comment]
Works fine with latest version. Closing.
