### ISSUE TITLE
Unsupported URL: http://theync.com

### ISSUE THREAD

**Issue by FernandoMiguel** [rg3/youtube-dl#2860]
> youtube-dl.exe -v  http://theync.com/fight/girl-hit-in-the-face-with-a-shovel.htm
> [debug] System config: []
> [debug] User config: []
> [debug] Command-line args: ['-v', 'http://theync.com/fight/girl-hit-in-the-face-
> with-a-shovel.htm']
> [debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
> [debug] youtube-dl version 2014.05.05
> [debug] Python version 2.7.5 - Windows-8-6.2.9200
> [debug] Proxy map: {}
> [generic] girl-hit-in-the-face-with-a-shovel: Requesting header
> WARNING: Falling back on generic information extractor.
> [generic] girl-hit-in-the-face-with-a-shovel: Downloading webpage
> [generic] girl-hit-in-the-face-with-a-shovel: Extracting information
> ERROR: Unsupported URL: http://theync.com/fight/girl-hit-in-the-face-with-a-shov
> el.htm; please report this issue on https://yt-dl.org/bug . Be sure to call yout
> ube-dl with the --verbose flag and include its complete output. Make sure you ar
> e using the latest version; type  youtube-dl -U  to update.
> Traceback (most recent call last):
>   File "youtube_dl\extractor\generic.pyo", line 418, in _real_extract
>   File "youtube_dl\utils.pyo", line 1396, in parse_xml
>   File "xml\etree\ElementTree.pyo", line 1300, in XML
>   File "xml\etree\ElementTree.pyo", line 1642, in feed
>   File "xml\etree\ElementTree.pyo", line 1506, in _raiseerror
> ParseError: not well-formed (invalid token): line 118, column 32
> Traceback (most recent call last):
>   File "youtube_dl\YoutubeDL.pyo", line 516, in extract_info
>   File "youtube_dl\extractor\common.pyo", line 161, in extract
>   File "youtube_dl\extractor\generic.pyo", line 687, in _real_extract
> ExtractorError: Unsupported URL: http://theync.com/fight/girl-hit-in-the-face-wi
> th-a-shovel.htm; please report this issue on https://yt-dl.org/bug . Be sure to
> call youtube-dl with the --verbose flag and include its complete output. Make su
> re you are using the latest version; type  youtube-dl -U  to update.

**Comment by TRox1972** [comment]
Generic extractor seems to catch it as of version 2016.05.21.2, but it downloads the same video two times.

**Comment by TRox1972** [comment]
Currently working
