### ISSUE TITLE
[music.*.*] embedded bandcamp support

### ISSUE THREAD

**Issue by requiredregistration** [rg3/youtube-dl#2868]
http://music.davethomasjunior.com/track/i-cant-make-you-love-me

```
C:\>youtube-dl.exe -v http://music.davethomasjunior.com/track/i-cant-make-you-love-me
[debug] Command-line args: ['-v', 'http://music.davethomasjunior.com/track/i-cant-make-you-love-me']
[debug] youtube-dl version 2014.05.05
[generic] i-cant-make-you-love-me: Requesting header
WARNING: Falling back on generic information extractor.
[generic] i-cant-make-you-love-me: Downloading webpage
[generic] i-cant-make-you-love-me: Extracting information
[Bandcamp:album] davethomasjunior: Downloading webpage
ERROR: The page doesn't contain any tracks;
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 516, in extract_info
  File "youtube_dl\extractor\common.pyo", line 161, in extract
  File "youtube_dl\extractor\bandcamp.pyo", line 137, in _real_extract
```

**Comment by dstftw** [comment]
`music.davethomasjunior.com` does not resolve anymore.
