### ISSUE TITLE
[fc2] 403 error

### ISSUE THREAD

**Issue by phihag** [rg3/youtube-dl#2912]
```
youtube-dl http://video.fc2.com/en/content/20130113eqtNRAv5 -v
[debug] System config: []
[debug] User config: ['--age-limit', '17']
[debug] Command-line args: ['http://video.fc2.com/en/content/20130113eqtNRAv5', '-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.05.13
[debug] Git HEAD: 1800eee
[debug] Python version 2.7.6 - Linux-3.13-1-amd64-x86_64-with-debian-jessie-sid
[debug] Proxy map: {}
[fc2] 20130113eqtNRAv5: Downloading webpage
[fc2] 20130113eqtNRAv5: Downloading info page
ERROR: Error code: 403; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "youtube_dl/YoutubeDL.py", line 516, in extract_info
    ie_result = ie.extract(url)
  File "youtube_dl/extractor/common.py", line 161, in extract
    return self._real_extract(url)
  File "youtube_dl/extractor/fc2.py", line 50, in _real_extract
    raise ExtractorError('Error code: %s' % info['err_code'][0])
ExtractorError: Error code: 403; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
```

It looks like the problem is the missing PHPSESSID cookie. We should fix cookie handling in fc2.

**Comment by TRox1972** [comment]
Not working for the first video (http://video.fc2.com/en/content/20130113eqtNRAv) as of 2016.07.07, though a different error is raised. The two other videos are unavailable (they require login or are removed).

```
$ youtube-dl -v http://video.fc2.com/en/content/20130113eqtNRAv | pbcopy
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://video.fc2.com/en/content/20130113eqtNRAv']
[debug] Encodings: locale UTF-8, fs utf-8, out None, pref UTF-8
[debug] youtube-dl version 2016.07.07
[debug] Python version 2.7.11 - Darwin-15.3.0-x86_64-i386-64bit
[debug] exe versions: avconv 11.4, avprobe 11.4, ffmpeg 3.0.2, ffprobe 3.0.2, rtmpdump 2.4
[debug] Proxy map: {}
ERROR: Unable to extract OpenGraph title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 681, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 343, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/fc2.py", line 82, in _real_extract
    title = self._og_search_title(webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 740, in _og_search_title
    return self._og_search_property('title', html, **kargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 728, in _og_search_property
    escaped = self._search_regex(self._og_regexes(prop), html, name, flags=re.DOTALL, **kargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 646, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract OpenGraph title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by Uron0238** [comment]
youtube-dl.exe -v http://video.fc2.com/ja/a/content/20160712vBJB4txY/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://video.fc2.com/ja/a/content/20160712vBJB4txY/']
[debug] Encodings: locale cp932, fs mbcs, out cp932, pref cp932
[debug] youtube-dl version 2016.06.03
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[fc2] 20160712vBJB4txY: Downloading webpage
[fc2] 20160712vBJB4txY: Downloading info page
[debug] Invoking downloader on 'http://vip.video19000-cdn2.fc2.com/up/flv/201607/12/v/20160712vBJB4txY.cdn.flv?mid=f0a6b539d423e4e1b4665640a8adf577'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpjletvtok\build\youtube_dl\YoutubeDL.py", line 1644, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpjletvtok\build\youtube_dl\YoutubeDL.py", line 1586, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpjletvtok\build\youtube_dl\downloader\common.py", line 350, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpjletvtok\build\youtube_dl\downloader\http.py", line 58, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpjletvtok\build\youtube_dl\YoutubeDL.py", line 1946, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_defaulturllib.error.HTTPError: HTTP Error 403: Forbidden

I couldn't download this video. I want download free video, but I seem it download vip video.
