### ISSUE TITLE
py2exe execution fails if cwd contains Cyrillic characters

### ISSUE THREAD

**Issue by phihag** [rg3/youtube-dl#2919]
```
C:\Users\Минка\Desktop>youtube-dl
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\py2exe\boot_common.py", line 92, in <module>
ImportError: No module named linecache
Traceback (most recent call last):
  File "<install zipextimporter>", line 1, in <module>
ImportError: No module named zipextimporter
Traceback (most recent call last):
  File "__main__.py", line 15, in <module>
ImportError: No module named youtube_dl
```

**Comment by sunpakky** [comment]
Any updates on this ?
