### ISSUE TITLE
[site-support-request] movie.naver.com

### ISSUE THREAD

**Issue by ubless607** [rg3/youtube-dl#2943]
<pre>C:\rtmp>youtube-dl --verbose http://movie.naver.com/movie/bi/mi/mediaView.nhn?code=57278&mid=22567

[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://movie.naver.com/movie/bi/mi/mediaView.nhn?code=57278']
[debug] Encodings: locale cp949, fs mbcs, out cp949, pref cp949
[debug] youtube-dl version 2014.08.29
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] Proxy map: {}
[generic] mediaView: Requesting header
WARNING: Falling back on generic information extractor.
[generic] mediaView: Downloading webpage
[generic] mediaView: Extracting information
ERROR: Unsupported URL: http://movie.naver.com/movie/bi/mi/mediaView.nhn?code=57278; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "youtube_dl\extractor\generic.pyo", line 530, in _real_extract
  File "youtube_dl\utils.pyo", line 1469, in parse_xml
  File "xml\etree\ElementTree.pyo", line 1300, in XML
  File "xml\etree\ElementTree.pyo", line 1642, in feed
  File "xml\etree\ElementTree.pyo", line 1506, in _raiseerror
ParseError: mismatched tag: line 84, column 2
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 521, in extract_info
  File "youtube_dl\extractor\common.pyo", line 178, in extract
  File "youtube_dl\extractor\generic.pyo", line 869, in _real_extract
ExtractorError: Unsupported URL: http://movie.naver.com/movie/bi/mi/mediaView.nhn?code=57278; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

'mid'은(는) 내부 또는 외부 명령, 실행할 수 있는 프로그램, 또는
배치 파일이 아닙니다.
</pre>

**Comment by mpenkov** [comment]
Still unsupported in the current master:

```
misha@cabron:~/git/youtube-dl$ git rev-parse --short HEAD
7ff129d3e
misha@cabron:~/git/youtube-dl$ bin/youtube-dl "http://movie.naver.com/movie/bi/mi/mediaView.nhn?code=57278&mid=22567"
[generic] mediaView: Requesting header
[redirect] Following redirect to https://movie.naver.com/movie/bi/mi/mediaView.nhn?code=57278&mid=22567
[generic] mediaView: Requesting header
WARNING: Falling back on generic information extractor.
[generic] mediaView: Downloading webpage
[generic] mediaView: Extracting information
ERROR: Unsupported URL: https://movie.naver.com/movie/bi/mi/mediaView.nhn?code=57278&mid=22567
```
