### ISSUE TITLE
[NBCNews] Broken IE - doesn't work for show clips

### ISSUE THREAD

**Issue by anovicecodemonkey** [rg3/youtube-dl#2946]
For show clips it's falling back to the generic extractor. Looks like they use "The Platform.com" for the videos on these parts of the site, though ``ThePlatformIE`` doesn't even work when given the URL directly. The pattern must be wrong. 

Example URL: http://www.nbcnews.com/watch/meet-the-press/pete-williams-extended-interview-with-glenn-greenwald-259423811721

OR 

http://www.nbcnews.com/meet-the-press/pete-williams-extended-interview-glenn-greenwald-n108366

It's the same video but a different link format

```
$ youtube-dl -v http://www.nbcnews.com/watch/meet-the-press/pete-williams-extended-interview-with-glenn-greenwald-259423811721
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.nbcnews.com/watch/meet-the-press/pete-williams-extended-interview-with-glenn-greenwald-259423811721']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.05.13
[debug] Python version 3.4.0 - Linux-3.14.1-1-ARCH-x86_64-with-arch
[debug] Proxy map: {}
[generic] pete-williams-extended-interview-with-glenn-greenwald-259423811721: Requesting header
WARNING: Falling back on generic information extractor.
[generic] pete-williams-extended-interview-with-glenn-greenwald-259423811721: Downloading webpage
[generic] pete-williams-extended-interview-with-glenn-greenwald-259423811721: Extracting information
ERROR: Unsupported URL: http://www.nbcnews.com/watch/meet-the-press/pete-williams-extended-interview-with-glenn-greenwald-259423811721; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 516, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 161, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/generic.py", line 687, in _real_extract
    raise ExtractorError('Unsupported URL: %s' % url)
youtube_dl.utils.ExtractorError: Unsupported URL: http://www.nbcnews.com/watch/meet-the-press/pete-williams-extended-interview-with-glenn-greenwald-259423811721; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
```

```
$ youtube-dl -v http://www.nbcnews.com/meet-the-press/pete-williams-extended-interview-glenn-greenwald-n108366
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.nbcnews.com/meet-the-press/pete-williams-extended-interview-glenn-greenwald-n108366']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.05.13
[debug] Python version 3.4.0 - Linux-3.14.1-1-ARCH-x86_64-with-arch
[debug] Proxy map: {}
[generic] pete-williams-extended-interview-glenn-greenwald-n108366: Requesting header
WARNING: Falling back on generic information extractor.
[generic] pete-williams-extended-interview-glenn-greenwald-n108366: Downloading webpage
[generic] pete-williams-extended-interview-glenn-greenwald-n108366: Extracting information
ERROR: Unsupported URL: http://www.nbcnews.com/meet-the-press/pete-williams-extended-interview-glenn-greenwald-n108366; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 516, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 161, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/generic.py", line 687, in _real_extract
    raise ExtractorError('Unsupported URL: %s' % url)
youtube_dl.utils.ExtractorError: Unsupported URL: http://www.nbcnews.com/meet-the-press/pete-williams-extended-interview-glenn-greenwald-n108366; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
```

When supplying The Platform URL directly:

```
$ youtube-dl -v  http://player.theplatform.com/p/2E2eJC/NBCNewsIE8?guid=x_dc_mtp_greenwaldfull_140518
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://player.theplatform.com/p/2E2eJC/NBCNewsIE8?guid=x_dc_mtp_greenwaldfull_140518']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.05.13
[debug] Python version 3.4.0 - Linux-3.14.1-1-ARCH-x86_64-with-arch
[debug] Proxy map: {}
[ThePlatform] NBCNewsIE8: Downloading XML
ERROR: Unable to download XML: HTTP Error 404: Not Found; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 194, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 1214, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 461, in open
    response = meth(req, response)
  File "/usr/lib/python3.4/urllib/request.py", line 574, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.4/urllib/request.py", line 499, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 433, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 582, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
``

**Comment by remitamine** [comment]
will be fixed in the next version,
