### ISSUE TITLE
[NBCNewsIE] Broken IE - doesn't work for full episodes

### ISSUE THREAD

**Issue by anovicecodemonkey** [rg3/youtube-dl#2947]
Falls back to the generic extractor. I opened a separate issue to #2946 due to the sufficiently different URL structure. I suspect a new IE will be needed in this case.

Example URL: http://tve-nbcnews.nbcuni.com/tve/show/Meet%20the%20Press#show/Meet%20the%20Press/239227971771/0/Meet%20the%20Press%2C%20April%2027%2C%202014

```
$ youtube-dl -v http://tve-nbcnews.nbcuni.com/tve/show/Meet%20the%20Press#show/Meet%20the%20Press/239227971771/0/Meet%20the%20Press%2C%20April%2027%2C%202014
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://tve-nbcnews.nbcuni.com/tve/show/Meet%20the%20Press#show/Meet%20the%20Press/239227971771/0/Meet%20the%20Press%2C%20April%2027%2C%202014']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.05.13
[debug] Python version 3.4.0 - Linux-3.14.1-1-ARCH-x86_64-with-arch
[debug] Proxy map: {}
[generic] Meet%20the%20Press%2C%20April%2027%2C%202014: Requesting header
WARNING: Falling back on generic information extractor.
[generic] Meet%20the%20Press%2C%20April%2027%2C%202014: Downloading webpage
[generic] Meet%20the%20Press%2C%20April%2027%2C%202014: Extracting information
ERROR: Unsupported URL: http://tve-nbcnews.nbcuni.com/tve/show/Meet%20the%20Press#show/Meet%20the%20Press/239227971771/0/Meet%20the%20Press%2C%20April%2027%2C%202014; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 516, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 161, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/generic.py", line 687, in _real_extract
    raise ExtractorError('Unsupported URL: %s' % url)
youtube_dl.utils.ExtractorError: Unsupported URL: http://tve-nbcnews.nbcuni.com/tve/show/Meet%20the%20Press#show/Meet%20the%20Press/239227971771/0/Meet%20the%20Press%2C%20April%2027%2C%202014; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

```

**Comment by yan12125** [comment]
Now the URL of the provided example is:
http://tvenbcnews.nbcuni.com/now/#show/Meet%20the%20Press/239227971771/0/Meet%20the%20Press%2C%20April%2027%2C%202014
and there's another example from #11736:
http://tvenbcnews.nbcuni.com/now/dateline/full-episode/after-the-storm/855288387677
