### ISSUE TITLE
VRV Failed Downloads

### ISSUE THREAD

**Issue by ItsRogueRen** [rg3/youtube-dl#29871]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```youtube-dl -v -f 'bestvideo[format_id!*=hardsub]+bestaudio[format_id!*=hardsub]' 'https://vrv.co/watch/GZ7UVPP8N/Girlfriend-Girlfriend:Tsun-Is-Dere'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-f', 'bestvideo[format_id!*=hardsub]+bestaudio[format_id!*=hardsub]', 'https://vrv.co/watch/GZ7UVPP8N/Girlfriend-Girlfriend:Tsun-Is-Dere']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.9.5 (CPython) - Linux-5.11.0-7620-generic-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.3.2-0, ffprobe 4.3.2-0, rtmpdump 2.4
[debug] Proxy map: {}
[vrv] None: Downloading webpage
[vrv] GZ7UVPP8N: Downloading resource path JSON metadata
[vrv] GZ7UVPP8N: Downloading CMS Signing JSON metadata
[vrv] GZ7UVPP8N: Downloading object JSON metadata
[vrv] GZ7UVPP8N: Downloading video JSON metadata
[vrv] GZ7UVPP8N: Downloading streams JSON metadata
[vrv] GZ7UVPP8N: Downloading dash-audio-ja-JP information
[vrv] GZ7UVPP8N: Downloading dash-audio-ja-JP-hardsub-ar-ME information
[vrv] GZ7UVPP8N: Downloading dash-audio-ja-JP-hardsub-de-DE information
[vrv] GZ7UVPP8N: Downloading dash-audio-ja-JP-hardsub-en-US information
[vrv] GZ7UVPP8N: Downloading dash-audio-ja-JP-hardsub-es-ES information
[vrv] GZ7UVPP8N: Downloading dash-audio-ja-JP-hardsub-es-LA information
[vrv] GZ7UVPP8N: Downloading dash-audio-ja-JP-hardsub-fr-FR information
[vrv] GZ7UVPP8N: Downloading dash-audio-ja-JP-hardsub-it-IT information
[vrv] GZ7UVPP8N: Downloading dash-audio-ja-JP-hardsub-pt-BR information
[vrv] GZ7UVPP8N: Downloading dash-audio-ja-JP-hardsub-ru-RU information
[vrv] GZ7UVPP8N: Downloading hls-audio-ja-JP information
[vrv] GZ7UVPP8N: Downloading hls-audio-ja-JP-hardsub-ar-ME information
[vrv] GZ7UVPP8N: Downloading hls-audio-ja-JP-hardsub-de-DE information
[vrv] GZ7UVPP8N: Downloading hls-audio-ja-JP-hardsub-en-US information
[vrv] GZ7UVPP8N: Downloading hls-audio-ja-JP-hardsub-es-ES information
[vrv] GZ7UVPP8N: Downloading hls-audio-ja-JP-hardsub-es-LA information
[vrv] GZ7UVPP8N: Downloading hls-audio-ja-JP-hardsub-fr-FR information
[vrv] GZ7UVPP8N: Downloading hls-audio-ja-JP-hardsub-it-IT information
[vrv] GZ7UVPP8N: Downloading hls-audio-ja-JP-hardsub-pt-BR information
[vrv] GZ7UVPP8N: Downloading hls-audio-ja-JP-hardsub-ru-RU information
[debug] Invoking downloader on 'https://pl.crunchyroll.com/evs1/687b0244d1d4b02044578b3b94fdd346/assets/b58402ac7091e175143eb344a9d9cfde_,4124050.mp4,4124051.mp4,4124049.mp4,4124047.mp4,4124048.mp4,.urlset/manifest.mpd?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cCo6Ly9wbC5jcnVuY2h5cm9sbC5jb20vZXZzMS82ODdiMDI0NGQxZDRiMDIwNDQ1NzhiM2I5NGZkZDM0Ni9hc3NldHMvYjU4NDAyYWM3MDkxZTE3NTE0M2ViMzQ0YTlkOWNmZGVfLDQxMjQwNTAubXA0LDQxMjQwNTEubXA0LDQxMjQwNDkubXA0LDQxMjQwNDcubXA0LDQxMjQwNDgubXA0LC51cmxzZXQvbWFuaWZlc3QubXBkIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjMwMTg3ODg5fX19XX0_&Signature=ay9zvIHZwmdmgeZC5GahLc5yBu384vCo8rlDMeJwQKrCsRJNr~wHKmYVkRcftUA~98DQwlTgcDHXhbkaLXXj~C8dCAWZbMMeRqTf0Lb80qqzIqqA19rrAQyrpnjHdQGuUS7bJfQ5A1uCGvpLfSiKHJpfsVJDfxWLNWGwKxe~sLCFcJrOk1EU3-wgV2tIsGfzjQpDmBC0AR3Uyncudf1RyuQ2QrzSOwcBbdQgFzITnllpb9kl4eEeFtP2iiNkJm~vA~iOeBJI3N3S5-wq58xWB5kkHN26-URUFa8N3JhVwk2hTpb2OOLP2pjaRbUW50rI7g3VH2onaT0mancMMI9w8A__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA'
[dashsegments] Total fragments: 734
[download] Destination: Tsun Is Dere-GZ7UVPP8N.fdash-audio-ja-JP-f2-v1-x3.mp4
[download]  91.8% of ~1.36GiB at  1.01MiB/s ETA 03:20ERROR: unable to download video data: <urlopen error EOF occurred in violation of protocol (_ssl.c:1129)>
Traceback (most recent call last):
  File "/usr/lib/python3.9/urllib/request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.9/http/client.py", line 1253, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1299, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1248, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1008, in _send_output
    self.send(msg)
  File "/usr/lib/python3.9/http/client.py", line 948, in send
    self.connect()
  File "/usr/lib/python3.9/http/client.py", line 1422, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/usr/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/youtube_dl/YoutubeDL.py", line 1970, in process_info
    partial_success = dl(fname, new_info)
  File "/usr/local/lib/python3.9/dist-packages/youtube_dl/YoutubeDL.py", line 1915, in dl
    return fd.download(name, info)
  File "/usr/local/lib/python3.9/dist-packages/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/lib/python3.9/dist-packages/youtube_dl/downloader/dash.py", line 48, in real_download
    success, frag_content = self._download_fragment(ctx, fragment_url, info_dict)
  File "/usr/local/lib/python3.9/dist-packages/youtube_dl/downloader/fragment.py", line 104, in _download_fragment
    success = ctx['dl'].download(fragment_filename, fragment_info_dict)
  File "/usr/local/lib/python3.9/dist-packages/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/lib/python3.9/dist-packages/youtube_dl/downloader/http.py", line 351, in real_download
    establish_connection()
  File "/usr/local/lib/python3.9/dist-packages/youtube_dl/downloader/http.py", line 116, in establish_connection
    raise err
  File "/usr/local/lib/python3.9/dist-packages/youtube_dl/downloader/http.py", line 110, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/local/lib/python3.9/dist-packages/youtube_dl/YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/usr/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.9/dist-packages/youtube_dl/utils.py", line 2735, in https_open
    return self.do_open(functools.partial(
  File "/usr/lib/python3.9/urllib/request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:1129)>

```

## Description

I have read through every issue I can find for VRV and none of them have seemed to work, `--no-check-certificate` produces the same result. I can watch all the videos I try to download in Firefox 91 without issue. All I'm attempting to do is download JP audio and EN subs.
(running Pop!_OS 21.04 Linux, Ubuntu-based)

**Comment by ItsRogueRen** [comment]
> 

I.... uh.... have no idea what you are saying, I'm sorry I'm and idiot.

**Comment by dirkf** [comment]
Consider reading the [Manual](https://github.com/ytdl-org/youtube-dl#readme).

Consider testing command lines like those I suggested (not much different from what you tried, that failed mysteriously), eg:
```
youtube-dl --write-sub --sub-lang en-US -f 'best[format_id!*=hardsub]' 'https://vrv.co/watch/GZ7UVPP8N/Girlfriend-Girlfriend:Tsun-Is-Dere'
```
If none of these works, post a log with `-v` again.

**Comment by Mr986897** [comment]
Have you solved it?

**Comment by Mr986897** [comment]
请问解决了吗？
我也遇到了同样的问题，现在寸步难行。

**Comment by Mr986897** [comment]
Have you solved it?
I have the same problem and can't move any further.

**Comment by ItsRogueRen** [comment]
> Have you solved it?
> I have the same problem and can't move any further.

no, I don't have the time to do all this troubleshooting

**Comment by Mr986897** [comment]
It seems that the network is not good, my solution now is to send the request again; Because resources can be reconnected;

**Comment by Mr986897** [comment]
![image](https://user-images.githubusercontent.com/34566540/144740547-70975036-6d49-458e-af08-9d210b1a5b92.png)

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/30437

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/30438
