### ISSUE TITLE
VLIVE CH+ extract not working 

### ISSUE THREAD

**Issue by yy0901** [rg3/youtube-dl#29873]
## Checklist

- [ x ] I'm asking a question
- [ x ] I've looked through the README and FAQ for similar questions
- [ x ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

Vlive page is updating its security every now and then, and I cannot download the CH+ (subscription paid video) videos. I have tried many different method, downloading each m4s files and merging them but merged vid is cracking. 

following attached file is the line i have used following other's line for using vlive.py for paid vlive vid
vid link I would like to extract is this:
https://www.vlive.tv/post/1-18241380

**Comment by dirkf** [comment]
The issue is confused because of a bug in the exception handling routine, which wrongly assumes that an error comes with some explanatory `dict` including a `message`.

In the browser, the equivalent step, fetching https://www.vlive.tv/globalv-web/vam-web/video/v1.0/vod/154039/inkey?appId=8c6cc7b45d2568fb668be6e05b6e5a3b&platformType=PC&gcc=AU&locale=en_US, gives HTTP error 403 but no `message` is associated with the `compat_HTTPError`.

The browser UI says that 5 devices are already registered for the content and the video can't be accessed without buying it again. It's not clear how the "devices" are recognised.

**Comment by yy0901** [comment]
I was able to grab mpd but still showing this issue 

https://g-aegis-naver.pstatic.net/globalv/owfs_rmc/read/global_v_2016_06_29_2/cenc/745f91c5-fbd7-11e7-b3a9-7ec174b847b4/stream.mpd


[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--username', 'PRIVATE', '--password', 'PRIVATE', 'https://g-aegis-naver.pstatic.net/globalv/owfs_rmc/read/global_v_2016_06_29_2/cenc/745f91c5-fbd7-11e7-b3a9-7ec174b847b4/stream.mpd']
[debug] Encodings: locale cp949, fs mbcs, out cp949, pref cp949
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[generic] stream: Requesting header
WARNING: Falling back on generic information extractor.
[generic] stream: Downloading webpage
[generic] stream: Extracting information
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\generic.py", line 2525, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 1374, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


if it is DRM Widevine V1 is there any way to extract?

**Comment by 89z** [comment]
Issue should be closed, DRM MPD requires License URL, which has not been provided
