### ISSUE TITLE
Cannot download videos from 91porn.com

### ISSUE THREAD

**Issue by Oliv1a** [rg3/youtube-dl#30089]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dl -v 'https://91porn.com/view_video.php?viewkey=bc863a1b7c7560040660'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://91porn.com/view_video.php?viewkey=bc863a1b7c7560040660']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.9.5 (CPython) - Linux-5.11.0-1019-raspi-aarch64-with-glibc2.33
[debug] exe versions: none
[debug] Proxy map: {}
[91porn] bc863a1b7c7560040660: Downloading webpage
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.9/dist-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.9/dist-packages/youtube_dl/extractor/porn91.py", line 38, in _real_extract
    title = self._search_regex(
  File "/usr/local/lib/python3.9/dist-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

The video cannot be downloaded from 91porn.com, it can be played normally in the browser, and it cannot be downloaded even when using a proxy. The link used in the test is normal as of the time of posting. If the link fails later, you can open a video from 91porn.com for testing. Thank you for your time!

**Comment by dirkf** [comment]
The site structure is not as expected by the extractor. In particular the specific HTML element used to find the title is missing, and the extractor doesn't fall back to using the `<title>`. Possibly that small tweak would restore operation, implementation and testing required.

**Comment by dirkf** [comment]
In fact, both the page and its embedding page where the extractor hopes to find the media URL now have an HTML5 video element whose contents is dynamically written by encrypted JS (`encode_version = "jsjiami.com.v5"`).

Unfortunately the JS is a bit too fancy for the toy interpreter in `jsinterp.py` and for other Python-based JS implementations except for [Js2Py](https://github.com/PiotrDabkowski/Js2Py) which in turn has too many dependencies. Other extractors use PhantomJS, or possibly the relevant part of the decryptor source [here](https://github.com/liulihaocai/JSDec/blob/master/js/dec.js) could be translated into Python.

**Comment by gitxxfan** [comment]
> In fact, both the page and its embedding page where the extractor hopes to find the media URL now have an HTML5 video element whose contents is dynamically written by encrypted JS (`encode_version = "jsjiami.com.v5"`).
> 
> Unfortunately the JS is a bit too fancy for the toy interpreter in `jsinterp.py` and for other Python-based JS implementations except for [Js2Py](https://github.com/PiotrDabkowski/Js2Py) which in turn has too many dependencies. Other extractors use PhantomJS, or possibly the relevant part of the decryptor source [here](https://github.com/liulihaocai/JSDec/blob/master/js/dec.js) could be translated into Python.

Hello, @dirkf @PeterDing Is that possible to solve this site video download issue? I have the same problem downloading from that site,  the verbose log as below,  can you give some suggestions? Many thanks.

- C:\Users\15318>youtube-dl --list-format https://91porn.com/view_video.php?viewkey=47cf6015e4d4536708cd -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--list-format', 'https://91porn.com/view_video.php?viewkey=47cf6015e4d4536708cd', '-v']
[debug] Encodings: locale cp65001, fs utf-8, out utf-8, pref cp65001
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.0 (CPython) - Windows-10-10.0.19042-SP0
[debug] exe versions: ffmpeg 2022-01-24-git-0a83ecbf48-full_build-www.gyan.dev, ffprobe 2022-01-24-git-0a83ecbf48-full_build-www.gyan.dev
[debug] Proxy map: {}
[91porn] 47cf6015e4d4536708cd: Downloading webpage
[91porn] 47cf6015e4d4536708cd: Downloading webpage
Traceback (most recent call last):
  File "D:\Program Files\Python\Python310\Scripts\youtube-dl-script.py", line 33, in <module>
    sys.exit(load_entry_point('youtube-dl==2021.12.17', 'console_scripts', 'youtube-dl')())
  File "D:\Program Files\Python\Python310\lib\site-packages\youtube_dl-2021.12.17-py3.10.egg\youtube_dl\__init__.py", line 475, in main
    _real_main(argv)
  File "D:\Program Files\Python\Python310\lib\site-packages\youtube_dl-2021.12.17-py3.10.egg\youtube_dl\__init__.py", line 465, in _real_main
    retcode = ydl.download(all_urls)
  File "D:\Program Files\Python\Python310\lib\site-packages\youtube_dl-2021.12.17-py3.10.egg\youtube_dl\YoutubeDL.py", line 2068, in download
    res = self.extract_info(
  File "D:\Program Files\Python\Python310\lib\site-packages\youtube_dl-2021.12.17-py3.10.egg\youtube_dl\YoutubeDL.py", line 808, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "D:\Program Files\Python\Python310\lib\site-packages\youtube_dl-2021.12.17-py3.10.egg\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "D:\Program Files\Python\Python310\lib\site-packages\youtube_dl-2021.12.17-py3.10.egg\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "D:\Program Files\Python\Python310\lib\site-packages\youtube_dl-2021.12.17-py3.10.egg\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "D:\Program Files\Python\Python310\lib\site-packages\youtube_dl-2021.12.17-py3.10.egg\youtube_dl\extractor\porn91.py", line 70, in _real_extract
    info_dict = self._parse_html5_media_entries(url, videopage, video_id)[0]
IndexError: list index out of range
