### ISSUE TITLE
Instagram broken

### ISSUE THREAD

**Issue by ghost** [rg3/youtube-dl#30106]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.instagram.com/reel/CULi-mwDuGZ/?utm_source=ig_web_copy_link']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.9.7 (CPython) - macOS-11.6-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4, rtmpdump 2.4
[debug] Proxy map: {}
[Instagram] CULi-mwDuGZ: Downloading webpage
ERROR: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.6.6/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/Cellar/youtube-dl/2021.6.6/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.6.6/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/youtube-dl/2021.6.6/libexec/lib/python3.9/site-packages/youtube_dl/extractor/instagram.py", line 240, in _real_extract
    video_url = self._og_search_video_url(webpage, secure=False)
  File "/usr/local/Cellar/youtube-dl/2021.6.6/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 1130, in _og_search_video_url
    return self._html_search_regex(regexes, html, name, **kargs)
  File "/usr/local/Cellar/youtube-dl/2021.6.6/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 1021, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/Cellar/youtube-dl/2021.6.6/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

No instagram videos download at all.

```
% youtube-dl 'https://www.instagram.com/reel/CULi-mwDuGZ/?utm_source=ig_web_copy_link'
[Instagram] CULi-mwDuGZ: Downloading webpage
ERROR: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

Neither reels nor posts.

**Comment by 89z** [comment]
If you are on Windows, I have a build [1], otherwise you need to build yourself [2].

1. https://github.com/89z/mech/releases/tag/v1.34.9
2. https://github.com/89z/mech/tree/master/cmd

**Comment by dirkf** [comment]
Your original link doesn't fail here:
```
$ youtube-dl -F -v 'https://www.instagram.com/reel/CULi-mwDuGZ/?utm_source=ig_web_copy_link'
[debug] System config: ['--prefer-ffmpeg']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-F', '-v', 'https://www.instagram.com/reel/CULi-mwDuGZ/?utm_source=ig_web_copy_link']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.9.7 (CPython) - Linux-4.4.0-210-generic-i686-with-glibc2.23
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[Instagram] CULi-mwDuGZ: Downloading webpage
[info] Available formats for CULi-mwDuGZ:
format code  extension  resolution note
0            mp4        640x1138 
$
```
So you should verify that the page and media do actually show in your browser. If it does, but yt-dl still fails, maybe the browser is using some proxy or VPN that is not configured for yt-dl?

**Comment by dirkf** [comment]
Did I mention that I had to put the laptop inside a [pentacle](https://en.wikipedia.org/wiki/Pentacle) and recite the [Parrot Sketch](https://www.dailymotion.com/video/x2hwqnp) backwards?

Seriously, it still works for me so there must be some network issue for you. You can use the `--print-traffic` option to see the HTTP headers sent and received by yt-dl, or `--write-pages` to save the received HTML pages as files.

**Comment by leocjj** [comment]
I have exactly the same issue when I try to run the same with an AWS EC2 instance, but it works well on my local computer. Can this information help? I really need to run this in AWS but it doesn't work for Facebook and Instagram even if I use my FB user/password

**Comment by dirkf** [comment]
Please provide a verbose log of the Instagram failure in EC2, and possibly the additional debug logs mentioned above.

**Comment by leocjj** [comment]
Hi @dirkf , this is the log from an EC2 instance, in my local it works well:
```
$ youtube-dl -F -v 'https://www.instagram.com/reel/CULi-mwDuGZ/?utm_source=ig_web_copy_link'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-F', '-v', 'https://www.instagram.com/reel/CULi-mwDuGZ/?utm_source=ig_web_copy_link']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.8.10 (CPython) - Linux-5.11.0-1020-aws-x86_64-with-glibc2.29
[debug] exe versions: none
[debug] Proxy map: {}
[Instagram] CULi-mwDuGZ: Downloading webpage
ERROR: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/instagram.py", line 240, in _real_extract
    video_url = self._og_search_video_url(webpage, secure=False)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1130, in _og_search_video_url
    return self._html_search_regex(regexes, html, name, **kargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1021, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
And this is the full log with --print-traffic:
```
$ youtube-dl --print-traffic 'https://www.instagram.com/reel/CULi-mwDuGZ/?utm_source=ig_web_copy_link'
[Instagram] CULi-mwDuGZ: Downloading webpage
send: b'GET /reel/CULi-mwDuGZ HTTP/1.1\r\nHost: www.instagram.com\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.15 Safari/537.36\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Encoding: gzip, deflate\r\nAccept-Language: en-us,en;q=0.5\r\nConnection: close\r\n\r\n'
reply: 'HTTP/1.1 301 Moved Permanently\r\n'
header: Content-Type: text/html; charset=utf-8
header: Location: https://www.instagram.com/reel/CULi-mwDuGZ/
header: Vary: Accept-Language, Cookie
header: Date: Thu, 25 Nov 2021 17:58:21 GMT
header: Strict-Transport-Security: max-age=31536000
header: Cache-Control: private, no-cache, no-store, must-revalidate
header: Pragma: no-cache
header: Expires: Sat, 01 Jan 2000 00:00:00 GMT
header: X-Frame-Options: SAMEORIGIN
header: content-security-policy: report-uri https://www.instagram.com/security/csp_report/; default-src 'self' https://www.instagram.com; img-src data: blob: https://*.fbcdn.net https://*.instagram.com https://*.cdninstagram.com https://*.facebook.com https://*.fbsbx.com https://*.giphy.com; font-src data: https://*.fbcdn.net https://*.instagram.com https://*.cdninstagram.com; media-src 'self' blob: https://www.instagram.com https://*.cdninstagram.com https://*.fbcdn.net; manifest-src 'self' https://www.instagram.com; script-src 'self' https://instagram.com https://www.instagram.com https://*.www.instagram.com https://*.cdninstagram.com wss://www.instagram.com https://*.facebook.com https://*.fbcdn.net https://*.facebook.net 'unsafe-inline' 'unsafe-eval' blob:; style-src 'self' https://*.www.instagram.com https://www.instagram.com 'unsafe-inline'; connect-src 'self' https://instagram.com https://www.instagram.com https://*.www.instagram.com https://graph.instagram.com https://*.graph.instagram.com https://i.instagram.com/graphql_www https://graphql.instagram.com https://*.cdninstagram.com https://api.instagram.com https://i.instagram.com https://*.i.instagram.com wss://www.instagram.com wss://edge-chat.instagram.com https://*.facebook.com https://*.fbcdn.net https://*.facebook.net chrome-extension://boadgeojelhgndaghljhdicfkmllpafd blob:; worker-src 'self' blob: https://www.instagram.com; frame-src 'self' https://instagram.com https://www.instagram.com https://*.instagram.com https://staticxx.facebook.com https://www.facebook.com https://web.facebook.com https://connect.facebook.net https://m.facebook.com; object-src 'none'; upgrade-insecure-requests
header: X-Content-Type-Options: nosniff
header: X-XSS-Protection: 0
header: x-ig-push-state: c2
header: x-aed: 48
header: Access-Control-Expose-Headers: X-IG-Set-WWW-Claim
header: Set-Cookie: ig_did=D060D481-BB70-4E3F-BDD6-B6E1C86169BA; Domain=.instagram.com; expires=Sat, 25-Nov-2023 17:58:21 GMT; HttpOnly; Max-Age=63072000; Path=/; Secure
header: Set-Cookie: ig_nrcb=1; Domain=.instagram.com; expires=Fri, 25-Nov-2022 17:58:21 GMT; Max-Age=31536000; Path=/; Secure
header: x-ig-origin-region: atn
header: X-FB-TRIP-ID: 1679558926
header: Alt-Svc: h3=":443"; ma=3600,h3-29=":443"; ma=3600
header: Connection: close
header: Content-Length: 0
send: b'GET /reel/CULi-mwDuGZ/ HTTP/1.1\r\nHost: www.instagram.com\r\nCookie: ig_did=D060D481-BB70-4E3F-BDD6-B6E1C86169BA; ig_nrcb=1\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.15 Safari/537.36\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Encoding: gzip, deflate\r\nAccept-Language: en-us,en;q=0.5\r\nConnection: close\r\n\r\n'
reply: 'HTTP/1.1 302 Found\r\n'
header: Content-Type: text/html; charset=utf-8
header: Location: https://www.instagram.com/accounts/login/
header: Vary: Accept-Language, Cookie
header: Content-Language: en
header: Date: Thu, 25 Nov 2021 17:58:21 GMT
header: Strict-Transport-Security: max-age=31536000
header: Cache-Control: private, no-cache, no-store, must-revalidate
header: Pragma: no-cache
header: Expires: Sat, 01 Jan 2000 00:00:00 GMT
header: X-Frame-Options: SAMEORIGIN
header: content-security-policy: report-uri https://www.instagram.com/security/csp_report/; default-src 'self' https://www.instagram.com; img-src data: blob: https://*.fbcdn.net https://*.instagram.com https://*.cdninstagram.com https://*.facebook.com https://*.fbsbx.com https://*.giphy.com; font-src data: https://*.fbcdn.net https://*.instagram.com https://*.cdninstagram.com; media-src 'self' blob: https://www.instagram.com https://*.cdninstagram.com https://*.fbcdn.net; manifest-src 'self' https://www.instagram.com; script-src 'self' https://instagram.com https://www.instagram.com https://*.www.instagram.com https://*.cdninstagram.com wss://www.instagram.com https://*.facebook.com https://*.fbcdn.net https://*.facebook.net 'unsafe-inline' 'unsafe-eval' blob:; style-src 'self' https://*.www.instagram.com https://www.instagram.com 'unsafe-inline'; connect-src 'self' https://instagram.com https://www.instagram.com https://*.www.instagram.com https://graph.instagram.com https://*.graph.instagram.com https://i.instagram.com/graphql_www https://graphql.instagram.com https://*.cdninstagram.com https://api.instagram.com https://i.instagram.com https://*.i.instagram.com wss://www.instagram.com wss://edge-chat.instagram.com https://*.facebook.com https://*.fbcdn.net https://*.facebook.net chrome-extension://boadgeojelhgndaghljhdicfkmllpafd blob:; worker-src 'self' blob: https://www.instagram.com; frame-src 'self' https://instagram.com https://www.instagram.com https://*.instagram.com https://staticxx.facebook.com https://www.facebook.com https://web.facebook.com https://connect.facebook.net https://m.facebook.com; object-src 'none'; upgrade-insecure-requests
header: X-Content-Type-Options: nosniff
header: X-XSS-Protection: 0
header: x-ig-push-state: c2
header: x-aed: 48
header: Access-Control-Expose-Headers: X-IG-Set-WWW-Claim
header: Set-Cookie: mid=YZ_OvQALAAE86FuLIx34xIvBG-cr; Domain=.instagram.com; expires=Sat, 25-Nov-2023 17:58:21 GMT; Max-Age=63072000; Path=/; Secure
header: x-ig-origin-region: atn
header: X-FB-TRIP-ID: 1679558926
header: Alt-Svc: h3=":443"; ma=3600,h3-29=":443"; ma=3600
header: Connection: close
header: Content-Length: 0
send: b'GET /accounts/login/ HTTP/1.1\r\nHost: www.instagram.com\r\nCookie: ig_did=D060D481-BB70-4E3F-BDD6-B6E1C86169BA; ig_nrcb=1; mid=YZ_OvQALAAE86FuLIx34xIvBG-cr\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.15 Safari/537.36\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Encoding: gzip, deflate\r\nAccept-Language: en-us,en;q=0.5\r\nConnection: close\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Content-Type: text/html; charset=utf-8
header: ig-set-password-encryption-web-key-id: 87
header: ig-set-password-encryption-web-pub-key: 8dd9aad29d9a614c338cff479f850d3ec57c525c33b3f702ab65e9e057fc087e
header: ig-set-password-encryption-web-key-version: 9
header: Last-Modified: Thu, 25 Nov 2021 17:58:21 GMT
header: Expires: Sat, 01 Jan 2000 00:00:00 GMT
header: Cache-Control: private, no-cache, no-store, must-revalidate
header: Vary: Accept-Language, Cookie, Accept-Encoding
header: Content-Language: en
header: Date: Thu, 25 Nov 2021 17:58:21 GMT
header: Content-Encoding: gzip
header: Strict-Transport-Security: max-age=31536000
header: Pragma: no-cache
header: X-Frame-Options: SAMEORIGIN
header: content-security-policy: report-uri https://www.instagram.com/security/csp_report/; default-src 'self' https://www.instagram.com; img-src data: blob: https://*.fbcdn.net https://*.instagram.com https://*.cdninstagram.com https://*.facebook.com https://*.fbsbx.com https://*.giphy.com; font-src data: https://*.fbcdn.net https://*.instagram.com https://*.cdninstagram.com; media-src 'self' blob: https://www.instagram.com https://*.cdninstagram.com https://*.fbcdn.net; manifest-src 'self' https://www.instagram.com; script-src 'self' https://instagram.com https://www.instagram.com https://*.www.instagram.com https://*.cdninstagram.com wss://www.instagram.com https://*.facebook.com https://*.fbcdn.net https://*.facebook.net 'unsafe-inline' 'unsafe-eval' blob:; style-src 'self' https://*.www.instagram.com https://www.instagram.com 'unsafe-inline'; connect-src 'self' https://instagram.com https://www.instagram.com https://*.www.instagram.com https://graph.instagram.com https://*.graph.instagram.com https://i.instagram.com/graphql_www https://graphql.instagram.com https://*.cdninstagram.com https://api.instagram.com https://i.instagram.com https://*.i.instagram.com wss://www.instagram.com wss://edge-chat.instagram.com https://*.facebook.com https://*.fbcdn.net https://*.facebook.net chrome-extension://boadgeojelhgndaghljhdicfkmllpafd blob:; worker-src 'self' blob: https://www.instagram.com; frame-src 'self' https://instagram.com https://www.instagram.com https://*.instagram.com https://staticxx.facebook.com https://www.facebook.com https://web.facebook.com https://connect.facebook.net https://m.facebook.com; object-src 'none'; upgrade-insecure-requests
header: X-Content-Type-Options: nosniff
header: X-XSS-Protection: 0
header: x-ig-push-state: c2
header: x-aed: 48
header: Access-Control-Expose-Headers: X-IG-Set-WWW-Claim
header: Set-Cookie: sessionid=""; Domain=instagram.com; expires=Thu, 01-Jan-1970 00:00:00 GMT; Max-Age=0; Path=/
header: Set-Cookie: sessionid=""; Domain=.instagram.com; expires=Thu, 01-Jan-1970 00:00:00 GMT; Max-Age=0; Path=/
header: Set-Cookie: sessionid=""; Domain=i.instagram.com; expires=Thu, 01-Jan-1970 00:00:00 GMT; Max-Age=0; Path=/
header: Set-Cookie: sessionid=""; Domain=.i.instagram.com; expires=Thu, 01-Jan-1970 00:00:00 GMT; Max-Age=0; Path=/
header: Set-Cookie: sessionid=""; Domain=www.instagram.com; expires=Thu, 01-Jan-1970 00:00:00 GMT; Max-Age=0; Path=/
header: Set-Cookie: sessionid=""; Domain=.www.instagram.com; expires=Thu, 01-Jan-1970 00:00:00 GMT; Max-Age=0; Path=/
header: Set-Cookie: sessionid=""; expires=Thu, 01-Jan-1970 00:00:00 GMT; Max-Age=0; Path=/
header: Set-Cookie: csrftoken=JO5942LlceUJiQOBr3p3Dfe6h0F3b5xo; Domain=.instagram.com; expires=Thu, 24-Nov-2022 17:58:21 GMT; Max-Age=31449600; Path=/; Secure
header: x-ig-origin-region: atn
header: X-FB-TRIP-ID: 1679558926
header: Alt-Svc: h3=":443"; ma=3600,h3-29=":443"; ma=3600
header: Connection: close
header: Content-Length: 23857
ERROR: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

Thanks in advance for your help!

**Comment by dirkf** [comment]
In your EC2 transcript the page is being redirected to a login page:
```
send: b'GET /reel/CULi-mwDuGZ/ HTTP/1.1\r\nHost: www.instagram.com\r\nCookie: ig_did=D060D481-BB70-4E3F-BDD6-B6E1C86169BA; ig_nrcb=1\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.15 Safari/537.36\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Encoding: gzip, deflate\r\nAccept-Language: en-us,en;q=0.5\r\nConnection: close\r\n\r\n'
reply: 'HTTP/1.1 302 Found\r\n'
header: Content-Type: text/html; charset=utf-8
header: Location: https://www.instagram.com/accounts/login/
```
This doesn't happen for me.

I wondered if the Python version is relevant, but WFM with 2.7, 3.5, 3.9.

I guess Instagram doesn't like clients from AWS IPs.

You could try sending cookies from a login session to see if the redirect is avoided.

**Comment by AGrills** [comment]
Hey was wondering if Instagram has changed anything under the hood as youtube-dl.exe no longer is able to download videos as of this morning.  Same issue as noted above, Unable to extract video url

**Comment by 89z** [comment]
@dirkf example only works for a limited number of tries. In my case, it works three times then failed exactly as the author. In which case, I have an alternative tool that allows authentication for further requests:

~~~
PS C:\> instagram -a -v CB7CmZ7JiNl
GET /p/CB7CmZ7JiNl/?__a=1 HTTP/1.1
Host: www.instagram.com
Authorization: Bearer IGT:2:eyJkc191c2VyX2lkIjoiNDkzNzgxNzEzMzQiLCJzZXNzaW9ua...
User-Agent: Instagram 214.1.0.29.120 Android

GET https://scontent-hou1-1.cdninstagram.com/v/t50.2886-16/104889613_300054504485744_7972794599033206493_n.mp4?efg=eyJ2ZW5jb2RlX3RhZyI6InZ0c192b2RfdXJsZ2VuLjcyMC5mZWVkLmRlZmF1bHQifQ&_nc_ht=scontent-hou1-1.cdninstagram.com&_nc_cat=108&_nc_ohc=la1OgP36oNsAX8-_eX4&edm=AABBvjUBAAAA&vs=17891794249542449_3392401259&_nc_vs=HBksFQAYJEdBMTlRQVp3TXlmaTVSQUJBTjMyaGpaeURxVnVia1lMQUFBRhUAAsgBABUAGCRHRmF5UWdaUDNlOXFzcmtKQUU1MnVRSURvYXdUYmtZTEFBQUYVAgLIAQAoABgAGwGIB3VzZV9vaWwBMBUAACbins3tvp%2FIPxUCKAJDMywXQCghysCDEm8YEmRhc2hfYmFzZWxpbmVfMV92MREAdeoHAA%3D%3D&_nc_rid=76156ed093&ccb=7-4&oe=61C0144C&oh=00_AT99MREUS3RcH-ZDfC7rwaRAxuQHrMNIyqnjFKgO_XJw5A&_nc_sid=83d603
~~~

https://github.com/89z/mech

**Comment by dirkf** [comment]
>only works for a limited number of tries. 

Aha: a fourth attempt causes IG to send a login page. This check should be in the extractor:
```
--- old/youtube-dl/youtube_dl/extractor/instagram.py
+++ new/youtube-dl/youtube_dl/extractor/instagram.py
@@ -161,9 +161,16 @@
                 (lambda x: x['entry_data']['PostPage'][0]['graphql']['shortcode_media'],
                  lambda x: x['entry_data']['PostPage'][0]['media']),
                 dict)
+
         # _sharedData.entry_data.PostPage is empty when authenticated (see
         # https://github.com/ytdl-org/youtube-dl/pull/22880)
         if not media:
+            if self._html_search_regex(
+                    r'<title\b[^>]*>\s*([Ll]ogin\W+[Ii]nstagram)\s*</title',
+                    webpage, 'login required?', default=None):
+                raise ExtractorError(
+                    '''Instagram requires you to log in to access this video. Use '--cookies' to provide cookies acquired from a current logged-in browser session, or try again later: Instagram only allows infrequent access without logging in.''',
+                    expected=True)
             additional_data = self._parse_json(
                 self._search_regex(
                     r'window\.__additionalDataLoaded\s*\(\s*[^,]+,\s*({.+?})\s*\)\s*;',
```
Additionally, the login could be implemented, as in https://github.com/89z/mech/blob/master/instagram/instagram.go, and then a different message would be needed . Neither cookies nor login help unless the user has an IG account.

**Comment by someziggyman** [comment]
Thanks for this login page patch improvement @dirkf 
I've tried passing my cookies file in there, but getting an error anyway:
ytdlp works without cookies with their "embedded page trick" (with cookies it fails as well though).

I though it'd be possible to make this one work... Any advice is appreciated

youtube-dl -v --cookies /Users/user/Desktop/cookies.txt -F https://instagram.com/p/BQRRC8IAZ86/ 
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'--cookies', u'/Users/user/Desktop/cookies.txt', u'-F', u'https://instagram.com/p/BQRRC8IAZ86/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 2.7.16 (CPython) - Darwin-20.6.0-arm64-arm-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[Instagram] BQRRC8IAZ86: Downloading webpage
ERROR: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/youtube-dl/youtube_dl/extractor/common.py", line 546, in extract
    ie_result = self._real_extract(url)
  File "/youtube-dl/youtube_dl/extractor/instagram.py", line 249, in _real_extract
    video_url = self._og_search_video_url(webpage, secure=False)
  File "/youtube-dl/youtube_dl/extractor/common.py", line 1147, in _og_search_video_url
    return self._html_search_regex(regexes, html, name, **kargs)
  File "/youtube-dl/youtube_dl/extractor/common.py", line 1038, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/youtube-dl/youtube_dl/extractor/common.py", line 1029, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dirkf** [comment]
IG wants you to log in, as would be shown with the patch.

As you note, yt-dlp works without cookies. The same work-around doesn't seem to work with yt-dl, even if the headers are adjusted (eg, `--add-header 'Sec-Fetch-Mode: navigate'`).

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/30399

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/28021

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/29736

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/29486

**Comment by 89z** [comment]
https://github.com/ytdl-org/youtube-dl/issues/25575

**Comment by someziggyman** [comment]
There's a login fix on ytdlp page now https://github.com/yt-dlp/yt-dlp/commit/013322a95e396ab21c8febc3e560d8a177c87f4a
 Maybe, it can somehow be applied here and login patch above can be improved?

**Comment by dirkf** [comment]
The PR yt-dlp#2349 in that commit needs some extra common functions that would have to be back-ported. Eventually, once that's done, the yt-dlp IG extractor could also be back-ported.

The patch doesn't change the login procedure: it tries to extract content from the page differently once IG thinks you're logged in.

**Comment by 89z** [comment]
I changed my tool to use GraphQL, as the other API was giving different result depending on country. However it works fine, even with authentication:

~~~
PS C:\> instagram -a -v BQRRC8IAZ86
POST /graphql/query/ HTTP/1.1
Host: i.instagram.com
Authorization: Bearer IGT:2:eyJkc191c2VyX2lkIjoiNDkzNzgxNzEzMzQiLCJzZXNzaW9ua...
Content-Type: application/json
User-Agent: Instagram 214.1.0.29.120 Android

{"query_hash":"7d4d42b121a214d23bd43206e5142c8c","variables":{"shortcode":"BQRRC8IAZ86","fetch_comment_count":9}}
GET https://scontent-dfw5-1.cdninstagram.com/v/t51.2885-15/e15/16230662_1672445723048255_342696608778944512_n.jpg?_nc_ht=scontent-dfw5-1.cdninstagram.com&_nc_cat=111&_nc_ohc=X5t3BCG4EtUAX88tV3w&edm=AP_V10EBAAAA&ccb=7-4&oh=00_AT9sAYZEUm_rJfQzl2hp3RjjqaE5s_Z1nQf2hldt_Tk1gA&oe=61F39F81&_nc_sid=4f375e
GET https://scontent-dfw5-2.cdninstagram.com/v/t50.2886-16/16680454_2216304575261534_8448236959410683904_n.mp4?efg=eyJxZV9ncm91cHMiOiJbXCJpZ19wcm9ncmVzc2l2ZV91cmxnZW4ucHJvZHVjdF90eXBlLmZlZWRcIl0ifQ&_nc_ht=scontent-dfw5-2.cdninstagram.com&_nc_cat=102&_nc_ohc=3SVKNAfQsfQAX8f6Nwj&edm=AP_V10EBAAAA&ccb=7-4&oe=61F34B8C&oh=00_AT-7fyJlefXcbHyMK6NW2vjyuyBQBHeCZZFp9Oy6UYEt1w&_nc_sid=4f375e
~~~

https://github.com/89z/mech

**Comment by 89z** [comment]
Instead of parsing HTML, you can login using the host `i.instagram.com`:

https://github.com/89z/mech/blob/v1.46.7/instagram/item.go#L50-L79

(this was previously linked to, but the previous link is not valid anymore)

**Comment by IngFrustrado** [comment]
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['www.instagram.com/tv/Cd9qyaRDRju', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: 30e3d8883
[debug] Python version 3.10.1 (CPython) - macOS-12.3.1-arm64-arm-64bit
[debug] exe versions: none
[debug] Proxy map: {}
WARNING: The url doesn't specify the protocol, trying with http
[Instagram] Cd9qyaRDRju: Downloading webpage
ERROR: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/instagram.py", line 240, in _real_extract
    video_url = self._og_search_video_url(webpage, secure=False)
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 1130, in _og_search_video_url
    return self._html_search_regex(regexes, html, name, **kargs)
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 1021, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by PabloCastellano** [comment]
JFTR, this online tool worked for me: https://instavideosave.net/

I downloaded it from the web browser and then clicked on "copy the download link".

After removing some useless parameters, the link was something like:

> https://scontent-sjc3-1.cdninstagram.com/v/t50.2886-16/10000000_123456789012345_1234567890123456789_n.mp4?_nc_ht=AAAAA&_nc_cat=BBB&_nc_ohc=CCCCCCCCC&edm=DDDDDDD&ccb=EEE&oe=FFFFFF&oh=GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG

and I used `wget` to download the video from that url.

Another way to get the video url is by filtering the network requests inside the developer tools. I simply search "mp4" and get an url like the previous url. Only the hostname changed to `https://instagram.fagp1-2.fna.fbcdn.net`
