### ISSUE TITLE
Failing to download videos from Instagram 

### ISSUE THREAD

**Issue by snowman907** [rg3/youtube-dl#30145]
## Checklist

- [x ] I'm reporting a broken site support
- [ x] I've verified that I'm running youtube-dl version **2021.06.06**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
C:\Users\Eyal\Downloads>youtube-dl.exe -v https://www.instagram.com/p/B_cXkgOg3h3J1ZrgCTgLLok8sMQcrqQF5bWtOc0/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.instagram.com/p/B_cXkgOg3h3J1ZrgCTgLLok8sMQcrqQF5bWtOc0/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.22000
[debug] exe versions: none
[debug] Proxy map: {}
[Instagram] B_cXkgOg3h3J1ZrgCTgLLok8sMQcrqQF5bWtOc0: Downloading webpage
ERROR: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\instagram.py", line 240, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 1130, in _og_search_video_url
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 1021, in _html_search_regex
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


```

## Description

Hello, I am successful in downloading videos from Facebook, but not Instagram. A quick search in the youtube_dl Broken site support did not recover any issues related to Instagram. I need to download Instagram videos and I was wondering if someone has a solution.
Thanks

**Comment by Arsh1219** [comment]
> 4\. u rafiki203

Same issue. did you get any solution?

**Comment by sugandeez** [comment]
> @AtomicNess123 , I used my Instagram username and password and a cookies file. Since I use Firefox I used a Firefox extension to save cookies to a .txt file.
> 
> 1. Get Instagram Username and Password
> 2. Install browser cookies extension ( Get cookies.txt ([for Chrome](https://chrome.google.com/webstore/detail/get-cookiestxt/bgaddhkoddajcdgocldbbfleckgcbcid/)) or cookies.txt ([for Firefox](https://addons.mozilla.org/en-US/firefox/addon/cookies-txt/)).
> 3. After visiting Instagram and browsing a bit, with cookies-extension save the cookies to a .txt file.
> 4. Provide all the information in the command line
>    5.ube-dl.exe -u rafiki203 -p Ixhdhfrkejd! --cookies C:\Users\rafiki\Downloads\cookies.txt  -v https://www.instagram.com/p/CFy1HEwh6KB/
> 
> Hope that works for you.

no idea what this means -_-
