### ISSUE TITLE
Unable to extract from: http://www.frogtoon.com

### ISSUE THREAD

**Issue by camstuart** [rg3/youtube-dl#3019]
youtube-dl --verbose http://www.frogtoon.com/Track/Horus/Peregrination+016+(February+2014)
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.frogtoon.com/Track/Horus/Peregrination+016+(February+2014)']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.05.19
[debug] Python version 2.7.5 - Darwin-13.2.0-x86_64-i386-64bit
[debug] Proxy map: {}
[generic] Peregrination+016+(February+2014): Requesting header
WARNING: Falling back on generic information extractor.
[generic] Peregrination+016+(February+2014): Downloading webpage
[generic] Peregrination+016+(February+2014): Extracting information
ERROR: Unsupported URL: http://www.frogtoon.com/Track/Horus/Peregrination+016+(February+2014); please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 418, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1406, in parse_xml
    return xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 21, column 312
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 516, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 163, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 687, in _real_extract
    raise ExtractorError('Unsupported URL: %s' % url)
ExtractorError: Unsupported URL: http://www.frogtoon.com/Track/Horus/Peregrination+016+(February+2014); please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by TRox1972** [comment]
YouTube-embed, but not working.
