### ISSUE TITLE
[puls4.com / atv.at] Sites have changed to same site/player as prosieben.at/.de is using --> not working

### ISSUE THREAD

**Issue by nob000dy** [rg3/youtube-dl#30624]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

PS C:\> .\youtube-dl.exe -v "https://www.puls4.com/tv/2-minuten-2-millionen/staffel-9/2-minuten-2-millionen-vom-08022022/2-minuten-2-millionen-vom-08022022"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.puls4.com/tv/2-minuten-2-millionen/staffel-9/2-minuten-2-millionen-vom-08022022/2-minuten-2-millionen-vom-08022022']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[Puls4] tv/2-minuten-2-millionen/staffel-9/2-minuten-2-millionen-vom-08022022/2-minuten-2-millionen-vom-08022022: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 634, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 2288, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 502, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 685, in http_error_302
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default

PS C:\> .\youtube-dl.exe -v "https://www.atv.at/tv/die-finanzpolizei/staffel-03/episode-06/staffel-03-folge-06-die-finanzpolizei"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.atv.at/tv/die-finanzpolizei/staffel-03/episode-06/staffel-03-folge-06-die-finanzpolizei']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
[generic] staffel-03-folge-06-die-finanzpolizei: Requesting header
WARNING: Falling back on generic information extractor.
[generic] staffel-03-folge-06-die-finanzpolizei: Downloading webpage
[generic] staffel-03-folge-06-die-finanzpolizei: Extracting information
ERROR: Unsupported URL: https://www.atv.at/tv/die-finanzpolizei/staffel-03/episode-06/staffel-03-folge-06-die-finanzpolizei
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\generic.py", line 3489, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.atv.at/tv/die-finanzpolizei/staffel-03/episode-06/staffel-03-folge-06-die-finanzpolizei

## Description

The sites puls4.com and atv.at have recently changed the website and player to the same as prosieben.at / .de and the other sites from the ProSiebenSat.1 Media Group are using.

**Comment by dirkf** [comment]
Even ProSieben itself has issues: #30598. This may need some help from users in the coverage area. More research needed.

**Comment by dirkf** [comment]
I checked puls4.com and the page looks very similar to one from prosiebenmaxx.

In principle, just making the Puls4 IE inherit directly from the ProSieben IE rather than its base seems promising, but these class vars may need to be specialised
```
    _ACCESS_ID = 'x_prosiebenmaxx-de'
    _ENCRYPTION_KEY = 'Eeyeey9oquahthainoofashoyoikosag'
    _IV = 'Aeluchoc6aevechuipiexeeboowedaok'
    _CLIENT_NAME = 'kolibri-2.0.19-splec4'
```
and these may need to be updated
```
    _TOKEN = 'puls4'
    _SALT = '01!kaNgaiNgah1Ie4AeSha'
```
I think that if we can solve https://github.com/yt-dlp/yt-dlp/issues/2679, that will open the route to the other sites. Unfortunately the geo-restriction policies of the various sites make debugging difficult without a local presence.

**Comment by hydrandt** [comment]
I'm available to test if necessary (from Austria).

**Comment by aklaffenboeck** [comment]
Any updates here?
