### ISSUE TITLE
Not downloading from twitcast (i think they changed servers again)

### ISSUE THREAD

**Issue by Pyzza28** [rg3/youtube-dl#30659]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

Was trying to download a stream with three m3u8 links (cuz it was three hours long) and it was mentioned to me that they possibly changed servers in order to keep ppl from downloading.

The said error comes up when I try to dl:
```
[TwitCasting] 721738886: Downloading webpage
ERROR: Unable to extract movie playlist; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by 89z** [comment]
please provide example URL

**Comment by dirkf** [comment]
>PASTE VERBOSE LOG HERE

So do it.

**Comment by MarqFJA87** [comment]
I have the same error. Here is my verbose log.

> [debug] System config: []
> [debug] User config: []
> [debug] Custom config: []
> [debug] Command-line args: ['https://twitcasting.tv/95rn16/movie/722245771', '--verbose']
> [debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
> [debug] youtube-dl version 2021.12.17
> [debug] Python version 3.10.0 (CPython) - Windows-10-10.0.19043-SP0
> [debug] exe versions: none
> [debug] Proxy map: {}
> [TwitCasting] 722245771: Downloading webpage
> ERROR: Unable to extract movie playlist; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> Traceback (most recent call last):
>   File "D:\Programs\Python\Python310\lib\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
>     return func(self, *args, **kwargs)
>   File "D:\Programs\Python\Python310\lib\site-packages\youtube_dl\YoutubeDL.py", line 836, in __extract_info
>     ie_result = ie.extract(url)
>   File "D:\Programs\Python\Python310\lib\site-packages\youtube_dl\extractor\common.py", line 534, in extract
>     ie_result = self._real_extract(url)
>   File "D:\Programs\Python\Python310\lib\site-packages\youtube_dl\extractor\twitcasting.py", line 79, in _real_extract
>     video_js_data = self._parse_json(self._search_regex(
>   File "D:\Programs\Python\Python310\lib\site-packages\youtube_dl\extractor\common.py", line 1012, in _search_regex
>     raise RegexNotFoundError('Unable to extract %s' % _name)
> youtube_dl.utils.RegexNotFoundError: Unable to extract movie playlist; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dirkf** [comment]
In the problem page, the item targeted by the playlist regex is no longer a list but a dict (JSON object) like `{"2": list}`, where `list` has the previously expected format.

However the m3u8 URL gives 400 Bad Request.
