### ISSUE TITLE
[brightcove] Problem with redbull videos (was: Unterminated string brightcove)

### ISSUE THREAD

**Issue by jwm-art-net** [rg3/youtube-dl#3081]
```
youtube-dl --verbose http://www.redbull.com/en/bike/stories/1331655643987/replay-uci-dh-world-cup-2014-from-fort-william
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.redbull.com/en/bike/stories/1331655643987/replay-uci-dh-world-cup-2014-from-fort-william']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.06.09
[debug] Python version 3.4.1 - Linux-3.14.6-1-ARCH-x86_64-with-arch
[debug] Proxy map: {}
[generic] replay-uci-dh-world-cup-2014-from-fort-william: Requesting header
WARNING: Falling back on generic information extractor.
[generic] replay-uci-dh-world-cup-2014-from-fort-william: Downloading webpage
[generic] replay-uci-dh-world-cup-2014-from-fort-william: Extracting information
[generic] Brightcove video detected.
[download] Downloading playlist: Replay: UCI DH World Cup 2014 - Fort William
[generic] playlist Replay: UCI DH World Cup 2014 - Fort William: Collected 1 video ids (downloading 1 of them)
[download] Downloading video #1 of 1
[Brightcove] ref:BC2996102916001: Downloading webpage
[Brightcove] ref:BC2996102916001: Extracting information
Traceback (most recent call last):
  File "/usr/bin/youtube-dl", line 9, in <module>
    load_entry_point('youtube-dl==2014.06.09', 'console_scripts', 'youtube-dl')()
  File "/usr/lib/python3.4/site-packages/youtube_dl/__init__.py", line 852, in main
    _real_main(argv)
  File "/usr/lib/python3.4/site-packages/youtube_dl/__init__.py", line 842, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 1050, in download
    self.extract_info(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 527, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 645, in process_ie_result
    extra_info=extra)
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 571, in process_ie_result
    extra_info=extra_info)
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 516, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 167, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/brightcove.py", line 174, in _real_extract
    videoPlayer[0], query_str, query, referer=referer)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/brightcove.py", line 191, in _get_video_info
    info = json.loads(info)['data']
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 359, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Unterminated string starting at: line 1 column 513 (char 512)
```

**Comment by dstftw** [comment]
Video does not play in browser anymore.
