### ISSUE TITLE
ExtractorError: "token" parameter not in video info for unknown reason;

### ISSUE THREAD

**Issue by larryxiao** [rg3/youtube-dl#3083]
```
[debug] System config: []                                                                                                                                               
[debug] User config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=k2waw0wZ7VA']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.06.09
[youtube] Setting language
[youtube] k2waw0wZ7VA: Downloading webpage
[youtube] k2waw0wZ7VA: Downloading video info webpage
ERROR: k2waw0wZ7VA: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose fl
ag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 516, in extract_info
    ie_result = ie.extract(url)
  File "/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 167, in extract
    return self._real_extract(url)
  File "/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1093, in _real_extract
    video_id=video_id)
ExtractorError: k2waw0wZ7VA: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --v
erbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
```

**Comment by dstftw** [comment]
Then pass `--proxy` to youtube-dl also.
