### ISSUE TITLE
[CCMA] "ValueError: date not matching format" when downloading video

### ISSUE THREAD

**Issue by adaliaramon** [rg3/youtube-dl#30961]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.ccma.cat/tv3/alacarta/crims/manoli/video/6158990/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.4 (CPython) - Linux-5.17.8-arch1-1-x86_64-with-glibc2.35
[debug] exe versions: ffmpeg 5.0, ffprobe 5.0
[debug] Proxy map: {}
[CCMA] 6158990: Downloading JSON metadata
Traceback (most recent call last):
  File "/usr/bin/youtube-dl", line 33, in <module>
    sys.exit(load_entry_point('youtube-dl==2021.12.17', 'console_scripts', 'youtube-dl')())
  File "/usr/lib/python3.10/site-packages/youtube_dl/__init__.py", line 475, in main
    _real_main(argv)
  File "/usr/lib/python3.10/site-packages/youtube_dl/__init__.py", line 465, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 2068, in download
    res = self.extract_info(
  File "/usr/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 808, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "/usr/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.10/site-packages/youtube_dl/extractor/ccma.py", line 103, in _real_extract
    timestamp = calendar.timegm((datetime.datetime.strptime(
  File "/usr/lib/python3.10/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/lib/python3.10/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2022-05-16T22:09:06' does not match format '%Y-%d-%mT%H:%M:%S'
```

## Description

Got a ValueError when attempting to download this video. It seems like the date is actually matching the format, so no idea about what's going on.

**Comment by dirkf** [comment]
Some home-made code can be replaced by a standard utility:
```
--- old/youtube_dl/extractor/ccma.py
+++ new/youtube_dl/extractor/ccma.py
@@ -11,6 +11,7 @@ from ..utils import (
     extract_timezone,
     int_or_none,
     parse_duration,
+    parse_iso8601,
     parse_resolution,
     try_get,
     url_or_none,
@@ -25,7 +26,7 @@ class CCMAIE(InfoExtractor):
         'info_dict': {
             'id': '5630208',
             'ext': 'mp4',
-            'title': 'L\'espot de La Marató de TV3',
+            'title': r'''re:^L'espot de La Marató''',
             'description': 'md5:f12987f320e2f6e988e9908e4fe97765',
             'timestamp': 1478608140,
             'upload_date': '20161108',
@@ -39,8 +40,8 @@ class CCMAIE(InfoExtractor):
             'ext': 'mp3',
             'title': 'El Consell de Savis analitza el derbi',
             'description': 'md5:e2a3648145f3241cb9c6b4b624033e53',
-            'upload_date': '20170512',
-            'timestamp': 1494622500,
             'vcodec': 'none',
             'categories': ['Esports'],
         }
@@ -50,9 +51,9 @@ class CCMAIE(InfoExtractor):
         'info_dict': {
             'id': '6031387',
             'ext': 'mp4',
-            'title': 'Crims - Josep Talleda, l\'"Espereu-me" (capítol 1)',
+            'title': r'''re:\bJosep Talleda, l'"Espereu-me"''',
             'description': 'md5:7cbdafb640da9d0d2c0f62bad1e74e60',
-            'timestamp': 1582577700,
+            'timestamp': 1582577919,
             'upload_date': '20200224',
             'subtitles': 'mincount:4',
             'age_limit': 16,
@@ -96,14 +97,7 @@ class CCMAIE(InfoExtractor):
         duration = int_or_none(durada.get('milisegons'), 1000) or parse_duration(durada.get('text'))
         tematica = try_get(informacio, lambda x: x['tematica']['text'])
 
-        timestamp = None
-        data_utc = try_get(informacio, lambda x: x['data_emissio']['utc'])
-        try:
-            timezone, data_utc = extract_timezone(data_utc)
-            timestamp = calendar.timegm((datetime.datetime.strptime(
-                data_utc, '%Y-%d-%mT%H:%M:%S') - timezone).timetuple())
-        except TypeError:
-            pass
+        timestamp = parse_iso8601(try_get(informacio, lambda x: x['data_emissio']['utc']))
 
         subtitles = {}
         subtitols = media.get('subtitols') or []
```

**Comment by idrilirdi** [comment]
Can confirm that by modifying the code like shown up here downloading from CCMA works. Without the modification it fails because when checking for timestamp it is returned as %y-%m-%d instead of %y-%d-%m, as is normal outside of the US
