### ISSUE TITLE
ARD gives 'IndexError: list index out of range'

### ISSUE THREAD

**Issue by ringprince** [rg3/youtube-dl#3099]
Hi,

I do

    $ youtube-dl --verbose 'http://www.ardmediathek.de/tv/M%C3%A4rchen/Des-Kaisers-neue-Kleider/MDR-Fernsehen/Video?documentId=21904852&bcastId=17603866'

And I get this error:

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.ardmediathek.de/tv/M%C3%A4rchen/Des-Kaisers-neue-Kleider/MDR-Fernsehen/Video?documentId=21904852&bcastId=17603866']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.06.16
[debug] Python version 2.7.7 - Darwin-13.1.0-x86_64-i386-64bit
[debug] Proxy map: {}
[ARD] 21904852: Downloading webpage
[ARD] 21904852: Downloading JSON metadata
Traceback (most recent call last):
  File "/Users/al22/homebrew/Cellar/python/2.7.7_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Users/al22/homebrew/Cellar/python/2.7.7_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/al22/bin/youtube-dl/__main__.py", line 18, in <module>
  File "/Users/al22/bin/youtube-dl/youtube_dl/__init__.py", line 852, in main
  File "/Users/al22/bin/youtube-dl/youtube_dl/__init__.py", line 842, in _real_main
  File "/Users/al22/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1050, in download
  File "/Users/al22/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 516, in extract_info
  File "/Users/al22/bin/youtube-dl/youtube_dl/extractor/common.py", line 167, in extract
  File "/Users/al22/bin/youtube-dl/youtube_dl/extractor/ard.py", line 53, in _real_extract
IndexError: list index out of range
```
This is on osx.  I get the same on debian, though (version '2014.06.07').

**Comment by yan12125** [comment]
Seems the original video is gone. ("Leider konnte die gewünschte Seite nicht gefunden werden.") If there's still a problem regarding ARD, feel free to open a new issue.
