### ISSUE TITLE
[Smotrim.ru] Source removed from supported?

### ISSUE THREAD

**Issue by betterthanever2** [rg3/youtube-dl#31045]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[generic] 2426877: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 2426877: Downloading webpage
[generic] 2426877: Extracting information
ERROR: Unsupported URL: https://smotrim.ru/video/2426877
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\generic.py", line 3489, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://smotrim.ru/video/2426877
```

## Description

Just several days ago I was able to download vids from smotrim.ru (via generic extractor; [example vid](https://smotrim.ru/video/2426877)), but not anymore. Is this due to the change in their architecture, or is this some kind of ban on your side?

**Comment by gamer191** [comment]
> is this some kind of ban on your side?

Yeah, youtube-dl (which was last updated in December) includes a hidden virus in it that lets them modify your copy of the program, such as to block websites, without them even needing to release an update!

Just kidding, youtube-dl isn't [Windows XP](https://web.archive.org/web/20200219180230/http://slated.org/windows_by_stealth_the_updates_you_dont_want)

Jokes aside, youtube-dl currently doesn't block Russian propaganda, and I honestly feel like Russia would rejoice if they did (because Russia's lies and propaganda would stop being so easy to archive). That is all just my opinion though, and I'm absolutely not an expert

**Comment by dirkf** [comment]
Or perhaps there should be a [bolshiy Translation Movement](https://www.economist.com/china/2022/05/19/a-new-twitter-account-shows-how-the-chinese-communist-party-stirs-up-ultra-nationalism) to show the rest of the world the nonsense that passes for news in today's Russia. Fortunately Putin [Godwin](https://en.wikipedia.org/wiki/Godwin%27s_law)ned as his first move so there's no shame in others pointing out how he recapitulates Goebbels.

Anyhow smotrim.ru doesn't know about HTML syntax:
```
Error: The main element must not appear as a descendant of the main element.

From line 270, column 17; to line 270, column 51

          <main class="layout layout--video">↩     

Error: A document must not include more than one visible main element.

From line 270, column 17; to line 270, column 51

          <main class="layout layout--video">↩     
```
Apart from that it has nice ld+json that should be handled by the generic extractor, but (a) the ld+json extraction doesn't handle the `embedUrl` property (b) the URL there would need additional extraction to get player JSON from `window.pl.data.dataUrl = '...'`. In this case the link is //player.smotrim.ru/iframe/datavideo/id/2426877/sid/vh and the contents include this:
```json
          "sources": {
            "m3u8": {
              "auto": "https://cdn-v.rtr-vesti.ru/_cdn_auth/secure/v/vh/vod_hls/definst/smil:vh/smil/002/582/836_d20220616020530.smil/playlist.m3u8?auth=mh&vid=2582836&uid=wKgcM2Ky+KW0HQx2yUfiAg=="
            },
            "http": {
              "234": "https://cdn-v.rtr-vesti.ru/_cdn_auth/secure/v/vh/mp4/low-wide/002/582/836.mp4?auth=mh&vid=2582836",
              "360": "https://cdn-v.rtr-vesti.ru/_cdn_auth/secure/v/vh/mp4/medium-wide/002/582/836.mp4?auth=mh&vid=2582836",
              "540": "https://cdn-v.rtr-vesti.ru/_cdn_auth/secure/v/vh/mp4/high-wide/002/582/836.mp4?auth=mh&vid=2582836",
              "720": "https://cdn-v.rtr-vesti.ru/_cdn_auth/secure/v/vh/mp4/hd-wide/002/582/836.mp4?auth=mh&vid=2582836",
              "1080": "https://cdn-v.rtr-vesti.ru/_cdn_auth/secure/v/vh/mp4/fhd-wide/002/582/836.mp4?auth=mh&vid=2582836"
            }
          }
```
Together with the ld+json metadata, that's all that's needed for extraction.

**Comment by betterthanever2** [comment]
> The link to your site is your owner's link

I see what you mean. Am I a moron or what? :D Here's the [public view link](https://shoomow.info/?p=144&lang=en).
Thanks for working on the issue!

**Comment by gamer191** [comment]
> Wow. Thank you. Didn't know about this. I guess, [what I'm doing](https://shoomow.info/wp-admin/post.php?post=144&action=edit) then could be called a 'small translation movement'.

I owe you an apology, because I initially assumed that you were a pro-Putin conspiracy theorist (which is why my original message was rude and sarcastic). Sorry

**Comment by betterthanever2** [comment]
> I owe you an apology, because I initially assumed that you were a pro-Putin conspiracy theorist (which is why my original message was rude and sarcastic). Sorry

All is cool :) And just so you know: what you think is rude is actually childplay in comparison with what these people say in their endless ramblings. The definition of toxic, they are.

**Comment by dirkf** [comment]
Indeed. From the UK `player.rutv.ru` is not responding, but `player.smotrim.ru` is fine:
```diff
--- old/youtube_dl/extractor/rutv.py
+++ new/youtube_dl/extractor/rutv.py
@@ -15,11 +15,12 @@ class RUTVIE(InfoExtractor):
     IE_DESC = 'RUTV.RU'
     _VALID_URL = r'''(?x)
                     https?://
-                        (?:test)?player\.(?:rutv\.ru|vgtrk\.com)/
+                        (?:(?:test)?player\.)?(?:rutv\.ru|vgtrk\.com|smotrim\.ru)/
                         (?P<path>
                             flash\d+v/container\.swf\?id=|
                             iframe/(?P<type>swf|video|live)/id/|
-                            index/iframe/cast_id/
+                            index/iframe/cast_id/|
+                            (?<=smotrim\.ru/)video/
                         )
                         (?P<id>\d+)
                     '''
@@ -52,6 +53,7 @@ class RUTVIE(InfoExtractor):
                 # m3u8 download
                 'skip_download': True,
             },
+            'skip': 'Not found -- 1113: Видео недоступно для просмотра (404)',
         },
         {
             'url': 'http://player.rutv.ru/iframe/swf/id/766888/sid/hitech/?acc_video_id=4000',
@@ -97,6 +99,7 @@ class RUTVIE(InfoExtractor):
                 'id': '21',
                 'ext': 'mp4',
                 'title': 're:^Россия 24. Прямой эфир [0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}$',
+                'description': 'Прямой эфир информационного телеканала "Россия 24". Новости, интервью, репортажи 24 часа в сутки.',
                 'is_live': True,
             },
             'params': {
@@ -108,6 +111,19 @@ class RUTVIE(InfoExtractor):
             'url': 'https://testplayer.vgtrk.com/iframe/live/id/19201/showZoomBtn/false/isPlay/true/',
             'only_matching': True,
         },
+        {
+            'url': 'https://smotrim.ru/video/2426877',
+            'info_dict': {
+                'id': '2426877',
+                'ext': 'mp4',
+                'title': 'Вечер с Владимиром Соловьевым. Украина, Запад и политические кидалы. Эфир от 15.06.2022',
+                'description': 'md5:cf87249921fe6877ab439cf6d41c730f',
+            },
+            'params': {
+                # m3u8 download
+                'skip_download': True,
+            },
+        },
     ]
 
     @classmethod
@@ -127,24 +143,25 @@ class RUTVIE(InfoExtractor):
         mobj = re.match(self._VALID_URL, url)
         video_id = mobj.group('id')
         video_path = mobj.group('path')
+        player = 'http://player.smotrim.ru'
 
-        if re.match(r'flash\d+v', video_path):
-            video_type = 'video'
-        elif video_path.startswith('iframe'):
+        if video_path.startswith('iframe'):
             video_type = mobj.group('type')
             if video_type == 'swf':
                 video_type = 'video'
         elif video_path.startswith('index/iframe/cast_id'):
             video_type = 'live'
+        else:
+            video_type = 'video'
 
         is_live = video_type == 'live'
 
         json_data = self._download_json(
-            'http://player.rutv.ru/iframe/data%s/id/%s' % ('live' if is_live else 'video', video_id),
+            '%s/iframe/data%s/id/%s' % (player, 'live' if is_live else 'video', video_id),
             video_id, 'Downloading JSON')
 
-        if json_data['errors']:
-            raise ExtractorError('%s said: %s' % (self.IE_NAME, json_data['errors']), expected=True)
+        if json_data.get('errors'):
+            raise ExtractorError('%s said: %s (%s)' % (self.IE_NAME, json_data['errors'], json_data.get('status', '-')), expected=True)
 
         playlist = json_data['data']['playlist']
         medialist = playlist['medialist']
@@ -153,7 +170,7 @@ class RUTVIE(InfoExtractor):
         if media['errors']:
             raise ExtractorError('%s said: %s' % (self.IE_NAME, media['errors']), expected=True)
 
-        view_count = playlist.get('count_views')
+        view_count = int_or_none(playlist.get('count_views'))
         priority_transport = playlist['priority_transport']
 
         thumbnail = media['picture']
@@ -176,8 +193,8 @@ class RUTVIE(InfoExtractor):
                         'url': mobj.group('url'),
                         'play_path': mobj.group('playpath'),
                         'app': mobj.group('app'),
-                        'page_url': 'http://player.rutv.ru',
-                        'player_url': 'http://player.rutv.ru/flash3v/osmf.swf?i=22',
+                        'page_url': player,
+                        'player_url': player + '/flash3v/osmf.swf?i=22',
                         'rtmp_live': True,
                         'ext': 'flv',
                         'vbr': str_to_int(quality),
```
