### ISSUE TITLE
Unsupported URL firsttv.py sport videos

### ISSUE THREAD

**Issue by kvk-2015** [rg3/youtube-dl#31069]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.sport1tv.ru/sport/figurnoe-katanie-na-pervom/za-kadrom/gid-po-tancam-na-ldu-elementy-urovni-goe-kak-vse-ustroeno']
[debug] Encodings: locale cp1251, fs utf-8, out utf-8, pref cp1251
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.5 (CPython) - Windows-10-10.0.19044-SP0
[debug] exe versions: none
[debug] Proxy map: {}
WARNING: Falling back on generic information extractor.
ERROR: Unsupported URL: https://www.sport1tv.ru/sport/figurnoe-katanie-na-pervom/za-kadrom/gid-po-tancam-na-ldu-elementy-urovni-goe-kak-vse-ustroeno
Traceback (most recent call last):
  File "C:\Users\*****\AppData\Local\Programs\Python\Python310\lib\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\*****\AppData\Local\Programs\Python\Python310\lib\site-packages\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "C:\Users\*****\AppData\Local\Programs\Python\Python310\lib\site-packages\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\*****\AppData\Local\Programs\Python\Python310\lib\site-packages\youtube_dl\extractor\generic.py", line 3489, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.sport1tv.ru/sport/figurnoe-katanie-na-pervom/za-kadrom/gid-po-tancam-na-ldu-elementy-urovni-goe-kak-vse-ustroeno
```

## Description

Can't download sport videos on 1tv.ru This: _VALID_URL = r'https?://(?:www\.)?(?:sport)?1tv\.ru/(?:[^/]+/)+(?P<id>[^/?#]+)' in firsttv.py fixses the problem.

**Comment by dirkf** [comment]
Thanks, yes it does:
```diff
--- a/youtube_dl/extractor/firsttv.py
+++ b/youtube_dl/extractor/firsttv.py
@@ -17,10 +17,10 @@ from ..utils import (
 class FirstTVIE(InfoExtractor):
     IE_NAME = '1tv'
     IE_DESC = 'Первый канал'
-    _VALID_URL = r'https?://(?:www\.)?1tv\.ru/(?:[^/]+/)+(?P<id>[^/?#]+)'
+    _VALID_URL = r'https?://(?:www\.)?(?:sport)?1tv\.ru/(?:[^/]+/)+(?P<id>[^/?#]+)'
 
     _TESTS = [{
-        # single format
+        # single format plus HLS
         'url': 'http://www.1tv.ru/shows/naedine-so-vsemi/vypuski/gost-lyudmila-senchina-naedine-so-vsemi-vypusk-ot-12-02-2015',
         'md5': 'a1b6b60d530ebcf8daacf4565762bbaf',
         'info_dict': {
@@ -31,6 +31,9 @@ class FirstTVIE(InfoExtractor):
             'upload_date': '20150212',
             'duration': 2694,
         },
+        'params': {
+            'format': '[format_id !^= hls]',
+        },
     }, {
         # multiple formats
         'url': 'http://www.1tv.ru/shows/dobroe-utro/pro-zdorove/vesennyaya-allergiya-dobroe-utro-fragment-vypuska-ot-07042016',
@@ -47,13 +50,26 @@ class FirstTVIE(InfoExtractor):
             'skip_download': True,
         },
     }, {
-        'url': 'http://www.1tv.ru/news/issue/2016-12-01/14:00',
+        'url': 'http://www.1tv.ru/news/issue/2016-12-01/21:00',
         'info_dict': {
-            'id': '14:00',
-            'title': 'Выпуск новостей в 14:00   1 декабря 2016 года. Новости. Первый канал',
+            'id': '21:00',
+            'title': 'Выпуск новостей в 18:00   1 декабря 2016 года. Новости. Первый канал',
             'description': 'md5:2e921b948f8c1ff93901da78ebdb1dfd',
         },
-        'playlist_count': 13,
+        'playlist_count': 1,
+    }, {
+        'url': 'https://www.sport1tv.ru/sport/figurnoe-katanie-na-pervom/za-kadrom/gid-po-tancam-na-ldu-elementy-urovni-goe-kak-vse-ustroeno',
+        'info_dict': {
+            'id': '651835',
+            'ext': 'mp4',
+            'title': 'Гид по танцам на льду: элементы, уровни, GOE — как все устроено',
+            'thumbnail': r're:^https?://.*\.(?:jpg|JPG)$',
+            'upload_date': '20220212',
+            'duration': 1933,
+        },
+        'params': {
+            'skip_download': True,
+        },
     }, {
         'url': 'http://www.1tv.ru/shows/tochvtoch-supersezon/vystupleniya/evgeniy-dyatlov-vladimir-vysockiy-koni-priveredlivye-toch-v-toch-supersezon-fragment-vypuska-ot-06-11-2016',
         'only_matching': True,
```
The test URL http://www.1tv.ru/news/issue/2016-12-01/14:00 now gives the news show "Время" в 20:00" and similar URLs give single item playlists.
