### ISSUE TITLE
Unable to download from madou.club

### ISSUE THREAD

**Issue by beesuns** [rg3/youtube-dl#31061]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://madou.club/hongkongdoll-%e5%8d%95%e4%ba%ba%e9%9b%86-%e7%8b%ac%e8%87%aa%e7%bb%83%e4%b9%a0.html

## Description

system info:
```
uname -a                                                                                                                                                  
Linux kali 5.17.0-kali3-amd64 #1 SMP PREEMPT Debian 5.17.11-1kali1 (2022-05-30) x86_64 GNU/Linux
```
youtube-dl version:
```
youtube-dl --version
2021.12.17
```
I tried to download a video from madou.club:
```
youtube-dl --proxy="http://127.0.0.1:7890" https://madou.club/hongkongdoll-%e5%8d%95%e4%ba%ba%e9%9b%86-%e7%8b%ac%e8%87%aa%e7%bb%83%e4%b9%a0.html --verbose
[debug] System config: ['--proxy', 'http://127.0.0.1:8889/', '-o', '/home/xxx/Videos/%(title)s.%(ext)s']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--proxy=http://127.0.0.1:7890', 'https://madou.club/hongkongdoll-%e5%8d%95%e4%ba%ba%e9%9b%86-%e7%8b%ac%e8%87%aa%e7%bb%83%e4%b9%a0.html', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.4 (CPython) - Linux-5.17.0-kali3-amd64-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4.2-1, ffprobe 4.4.2-1
[debug] Proxy map: {'http': 'http://127.0.0.1:7890', 'https': 'http://127.0.0.1:7890'}
[generic] hongkongdoll-单人集-独自练习: Requesting header
WARNING: Falling back on generic information extractor.
[generic] hongkongdoll-单人集-独自练习: Downloading webpage
[generic] hongkongdoll-单人集-独自练习: Extracting information
ERROR: Unsupported URL: https://madou.club/hongkongdoll-%e5%8d%95%e4%ba%ba%e9%9b%86-%e7%8b%ac%e8%87%aa%e7%bb%83%e4%b9%a0.html
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3489, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://madou.club/hongkongdoll-%e5%8d%95%e4%ba%ba%e9%9b%86-%e7%8b%ac%e8%87%aa%e7%bb%83%e4%b9%a0.html
```

**Comment by dirkf** [comment]
The site isn't known to yt-dl.

Complete the checklist!

**Comment by beesuns** [comment]
@dirkf How to complete the checklist?

**Comment by beesuns** [comment]
@dirkf Thanks. I already updated the Checklist.

**Comment by Whatwhatio** [comment]
I am also having this same issue.
