### ISSUE TITLE
RegexNotFoundError: Unable to extract Initial JS player signature function name

### ISSUE THREAD

**Issue by mothlight** [rg3/youtube-dl#3112]
youtube-dl -t   https://www.youtube.com/watch?v=jYeDY6YkzIg
[youtube] Setting language
[youtube] jYeDY6YkzIg: Downloading webpage
[youtube] jYeDY6YkzIg: Downloading video info webpage
[youtube] jYeDY6YkzIg: Extracting video information
[youtube] jYeDY6YkzIg: Encrypted signatures detected.
[youtube] jYeDY6YkzIg: Downloading js player vflazPBMd
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 874, in _decrypt_signature
    video_id, player_url, len(s)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 376, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 444, in _parse_sig_js
    u'Initial JS player signature function name')
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 383, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

WARNING: Warning: Falling back to static signature algorithm
[youtube] jYeDY6YkzIg: Downloading js player vflazPBMd
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 874, in _decrypt_signature
    video_id, player_url, len(s)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 376, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 444, in _parse_sig_js
    u'Initial JS player signature function name')
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 383, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

WARNING: Warning: Falling back to static signature algorithm
[youtube] jYeDY6YkzIg: Downloading js player vflazPBMd
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 874, in _decrypt_signature
    video_id, player_url, len(s)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 376, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 444, in _parse_sig_js
    u'Initial JS player signature function name')
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 383, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

WARNING: Warning: Falling back to static signature algorithm
[youtube] jYeDY6YkzIg: Downloading js player vflazPBMd
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 874, in _decrypt_signature
    video_id, player_url, len(s)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 376, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 444, in _parse_sig_js
    u'Initial JS player signature function name')
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 383, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

WARNING: Warning: Falling back to static signature algorithm
[youtube] jYeDY6YkzIg: Downloading js player vflazPBMd
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 874, in _decrypt_signature
    video_id, player_url, len(s)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 376, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 444, in _parse_sig_js
    u'Initial JS player signature function name')
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 383, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

WARNING: Warning: Falling back to static signature algorithm
[youtube] jYeDY6YkzIg: Downloading js player vflazPBMd
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 874, in _decrypt_signature
    video_id, player_url, len(s)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 376, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 444, in _parse_sig_js
    u'Initial JS player signature function name')
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 383, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

WARNING: Warning: Falling back to static signature algorithm
[youtube] jYeDY6YkzIg: Downloading js player vflazPBMd
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 874, in _decrypt_signature
    video_id, player_url, len(s)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 376, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 444, in _parse_sig_js
    u'Initial JS player signature function name')
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 383, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

WARNING: Warning: Falling back to static signature algorithm
[youtube] jYeDY6YkzIg: Downloading js player vflazPBMd
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 874, in _decrypt_signature
    video_id, player_url, len(s)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 376, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 444, in _parse_sig_js
    u'Initial JS player signature function name')
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 383, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

WARNING: Warning: Falling back to static signature algorithm
[youtube] jYeDY6YkzIg: Downloading js player vflazPBMd
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 874, in _decrypt_signature
    video_id, player_url, len(s)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 376, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 444, in _parse_sig_js
    u'Initial JS player signature function name')
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 383, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

WARNING: Warning: Falling back to static signature algorithm
[youtube] jYeDY6YkzIg: Downloading js player vflazPBMd
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 874, in _decrypt_signature
    video_id, player_url, len(s)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 376, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 444, in _parse_sig_js
    u'Initial JS player signature function name')
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 383, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

WARNING: Warning: Falling back to static signature algorithm
[youtube] jYeDY6YkzIg: Downloading js player vflazPBMd
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 874, in _decrypt_signature
    video_id, player_url, len(s)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 376, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 444, in _parse_sig_js
    u'Initial JS player signature function name')
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 383, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

WARNING: Warning: Falling back to static signature algorithm
[youtube] jYeDY6YkzIg: Downloading js player vflazPBMd
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 874, in _decrypt_signature
    video_id, player_url, len(s)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 376, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 444, in _parse_sig_js
    u'Initial JS player signature function name')
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 383, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

WARNING: Warning: Falling back to static signature algorithm
[youtube] jYeDY6YkzIg: Downloading js player vflazPBMd
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 874, in _decrypt_signature
    video_id, player_url, len(s)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 376, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 444, in _parse_sig_js
    u'Initial JS player signature function name')
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 383, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

WARNING: Warning: Falling back to static signature algorithm
[youtube] jYeDY6YkzIg: Downloading js player vflazPBMd
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 874, in _decrypt_signature
    video_id, player_url, len(s)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 376, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 444, in _parse_sig_js
    u'Initial JS player signature function name')
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 383, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

WARNING: Warning: Falling back to static signature algorithm
ERROR: unable to download video data: HTTP Error 403: Forbidden

**Comment by Havrushchyk** [comment]
Update helped! Thanks!
