### ISSUE TITLE
http://putlocker.is/watch-lemony-snickets-a-series-of-unfortunate-events-online-free-putlocker.html

### ISSUE THREAD

**Issue by Rudloff** [rg3/youtube-dl#3115]
The generic extractor does not seem to catch the JW Player:
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://putlocker.is/watch-lemony-snickets-a-series-of-unfortunate-events-online-free-putlocker.html', '-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.06.19
[debug] Python version 2.7.3 - Linux-3.2.0-4-amd64-x86_64-with-debian-7.5
[debug] Proxy map: {}
[generic] watch-lemony-snickets-a-series-of-unfortunate-events-online-free-putlocker: Requesting header
WARNING: Falling back on generic information extractor.
[generic] watch-lemony-snickets-a-series-of-unfortunate-events-online-free-putlocker: Downloading webpage
[generic] watch-lemony-snickets-a-series-of-unfortunate-events-online-free-putlocker: Extracting information
ERROR: Unsupported URL: http://putlocker.is/watch-lemony-snickets-a-series-of-unfortunate-events-online-free-putlocker.html; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/extractor/generic.py", line 440, in _real_extract
    doc = parse_xml(webpage)
  File "./youtube-dl/youtube_dl/utils.py", line 1406, in parse_xml
    return xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1301, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1643, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1507, in _raiseerror
    raise err
ParseError: mismatched tag: line 32, column 151
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 516, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 167, in extract
    return self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/generic.py", line 722, in _real_extract
    raise ExtractorError('Unsupported URL: %s' % url)
ExtractorError: Unsupported URL: http://putlocker.is/watch-lemony-snickets-a-series-of-unfortunate-events-online-free-putlocker.html; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
```

**Comment by dstftw** [comment]
putlocker.is is clearly dedicated to copyright infringement therefore can't be supported by youtube-dl.
