### ISSUE TITLE
please add support for youtube-like-player

### ISSUE THREAD

**Issue by CiscoPress** [rg3/youtube-dl#3121]
> youtube-dl -v 'http://watchgirlspeeing.com/blog/amateur-roadside-pee/'
[debug] System config: ['-t', '--restrict-filenames']
[debug] User config: []
[debug] Command-line args: ['-v', 'http://watchgirlspeeing.com/blog/amateur-roadside-pee/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.06.19
[debug] Python version 2.7.5 - Darwin-13.2.0-x86_64-i386-64bit
[debug] Proxy map: {'http': 'http://127.0.0.1:8228', 'https': 'http://127.0.0.1:8228'}
[generic] amateur-roadside-pee: Requesting header
WARNING: Falling back on generic information extractor.
[generic] amateur-roadside-pee: Downloading webpage
[generic] amateur-roadside-pee: Extracting information
ERROR: Unsupported URL: http://watchgirlspeeing.com/blog/amateur-roadside-pee/; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 440, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1406, in parse_xml
    return xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: undefined entity: line 13, column 2
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 516, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 167, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 722, in _real_extract
    raise ExtractorError('Unsupported URL: %s' % url)
ExtractorError: Unsupported URL: http://watchgirlspeeing.com/blog/amateur-roadside-pee/; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by dstftw** [comment]
Google Drive is supported for quite some time already.
