### ISSUE TITLE
Unsupported URL - https://mat6tube.com/watch/-68355713_456239357

### ISSUE THREAD

**Issue by tmblrxaos** [rg3/youtube-dl#31392]
## Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running youtube-dl version **2021.12.17**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs violate any copyrights
- [X] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://mat6tube.com/watch/-68355713_456239357
- Playlist: ...?

## Description

Unable to download videos from: https://mat6tube.com.
```
**youtube-dl -v  -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best' 'https://mat6tube.com/watch/-68355713_456239357'**
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-f', 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best', 'https://mat6tube.com/watch/-68355713_456239357']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.8 (CPython) - macOS-11.7.1-x86_64-i386-64bit
[debug] exe versions: ffmpeg 5.1.2, ffprobe 5.1.2, rtmpdump 2.4
[debug] Proxy map: {}
[generic] -68355713_456239357: Requesting header
WARNING: Falling back on generic information extractor.
[generic] -68355713_456239357: Downloading webpage
[generic] -68355713_456239357: Extracting information
[debug] Invoking downloader on 'https://mat6tube.com/videofile/-68355713_456239357.mp4'
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 1976, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 1915, in dl
    return fd.download(name, info)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/downloader/http.py", line 351, in real_download
    establish_connection()
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/downloader/http.py", line 116, in establish_connection
    raise err
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/downloader/http.py", line 110, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by dirkf** [comment]
As this site is not yet supported, please complete the correct template as I've edited above.

**Comment by dirkf** [comment]
This site looks like a rip-off or re-brand of biqle.org, which is broken in yt-dl release and git master too. Unless anyone can find URLs of this site that aren't equally valid

**Comment by dirkf** [comment]
Yes, that works. A PR to come.
```shell
$ python -m youtube_dl -v -F 'https://mat6tube.com/watch/-68355713_456239357'
[debug] System config: [u'--prefer-ffmpeg']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-F', u'https://mat6tube.com/watch/-68355713_456239357']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: 774b346f9
[debug] Python version 2.7.18 (CPython) - Linux-4.4.0-210-generic-i686-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[BIQLE] -68355713_456239357: Downloading webpage
[vk] -68355713_456239357: Downloading webpage
[vk] -68355713_456239357: Downloading m3u8 information
[vk] -68355713_456239357: Downloading MPD manifest
[vk] -68355713_456239357: Downloading MPD manifest
[info] Available formats for -68355713_456239357:
format code  extension  resolution note
dash_sep-4   m4a        audio only DASH audio   36k , m4a_dash container, mp4a.40.2 (44100Hz)
dash_sep-5   m4a        audio only DASH audio   52k , m4a_dash container, mp4a.40.2 (44100Hz)
dash_sep-6   m4a        audio only DASH audio   69k , m4a_dash container, mp4a.40.2 (44100Hz)
dash_sep-1   mp4        250x144    DASH video   91k , mp4_dash container, avc1.64000C, video only
dash_sep-2   mp4        416x240    DASH video  307k , mp4_dash container, avc1.64000D, video only
dash_sep-3   mp4        624x360    DASH video  554k , mp4_dash container, avc1.64001E, video only
url240       mp4        240p       
url360       mp4        360p       
dash_uni-1   mp4        250x144    DASH video  127k , mp4_dash container, avc1.64000C, mp4a.40.2 (44100Hz)
hls-192      mp4        250x144     192k , 30.0fps
dash_uni-2   mp4        416x240    DASH video  360k , mp4_dash container, avc1.64000D, mp4a.40.2 (44100Hz)
hls-429      mp4        416x240     429k , 30.0fps
dash_uni-3   mp4        624x360    DASH video  623k , mp4_dash container, avc1.64001E, mp4a.40.2 (44100Hz)
hls-699      mp4        624x360     699k , 30.0fps (best)
$
```
