### ISSUE TITLE
[pbs] Add support for playlists

### ISSUE THREAD

**Issue by bjoseru** [rg3/youtube-dl#3162]
Although PBS should be supported, this particular format doesn't seem to work.
There are usually several videos listed on one page, clicking on one doesn't change the URL in the address bar. I'm using the latest MacPorts youtube-dl at this time.

Here's an example output:

```
~/Movies$ youtube-dl --verbose http://www.pbs.org/woodwrightsshop/watch-on-line/2009-2010-episodes/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.pbs.org/woodwrightsshop/watch-on-line/2009-2010-episodes/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.06.19
[debug] Python version 2.7.7 - Darwin-13.2.0-x86_64-i386-64bit
[debug] Proxy map: {}
[PBS] 2009-2010-episodes: Downloading webpage
ERROR: Unable to extract player URL; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/opt/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 516, in extract_info
    ie_result = ie.extract(url)
  File "/opt/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 167, in extract
    return self._real_extract(url)
  File "/opt/local/bin/youtube-dl/youtube_dl/extractor/pbs.py", line 44, in _real_extract
    webpage, 'player URL')
  File "/opt/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 383, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract player URL; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
```

**Comment by bjoseru** [comment]
I hadn't tried this in a while. It is still now working, but it now looks like a different error is coming up. It appears some exception handling in the PBS extractor is broken.

    $ youtube-dl --verbose --flat-playlist 'http://www.pbs.org/woodwrightsshop/watch-on-line/watch-season-episodes/2015-2016-episodes/'
    [debug] System config: []
    [debug] User config: []
    [debug] Command-line args: [u'--verbose', u'--flat-playlist', u'http://www.pbs.org/woodwrightsshop/watch-on-line/watch-season-episodes/2015-2016-episodes/']
    [debug] Encodings: locale US-ASCII, fs utf-8, out US-ASCII, pref US-ASCII
    [debug] youtube-dl version 2016.01.01
    [debug] Python version 2.7.10 - Darwin-14.5.0-x86_64-i386-64bit
    [debug] exe versions: ffmpeg 2.7.2, ffprobe 2.7.2, rtmpdump 2.4
    [debug] Proxy map: {}
    [pbs] 2015-2016-episodes: Downloading webpage
    Traceback (most recent call last):
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
    File "/Users/me/bin/youtube-dl/__main__.py", line 19, in <module>
    File "/Users/me/bin/youtube-dl/youtube_dl/__init__.py", line 410, in main
    File "/Users/me/bin/youtube-dl/youtube_dl/__init__.py", line 400, in _real_main
    File "/Users/me/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1677, in download
    File "/Users/me/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 665, in extract_info
    File "/Users/me/bin/youtube-dl/youtube_dl/extractor/common.py", line 291, in extract
    File "/Users/me/bin/youtube-dl/youtube_dl/extractor/pbs.py", line 427, in _real_extract
    File "/Users/me/bin/youtube-dl/youtube_dl/extractor/pbs.py", line 409, in _extract_webpage
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py", line 141, in match
    return _compile(pattern, flags).match(string)
    TypeError: expected string or buffer
