### ISSUE TITLE
the verge videos

### ISSUE THREAD

**Issue by FernandoMiguel** [rg3/youtube-dl#3182]
videos embebed into the verge site are not parsed
http://www.theverge.com/2014/6/27/5849272/material-world-how-google-discovered-what-software-is-made-of

$ youtube-dl -vvv "http://www.theverge.com/2014/6/27/5849272/material-world-how-google-discovered-what-software-is-made-of#ooid=11eXZobjrG8DCSTgrNjVinU-YmmdYjhe"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-vvv', 'http://www.theverge.com/2014/6/27/5849272/material-world-how-google-discovered-what-software-is-made-of#ooid=11eXZobjrG8DCSTgrNjVinU-YmmdYjhe']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.06.26
[debug] Python version 2.7.7 - Linux-3.15.0-6-generic-x86_64-with-Ubuntu-14.10-utopic
[debug] Proxy map: {}
[generic] material-world-how-google-discovered-what-software-is-made-of#ooid=11eXZobjrG8DCSTgrNjVinU-YmmdYjhe: Requesting header
WARNING: Falling back on generic information extractor.
[generic] material-world-how-google-discovered-what-software-is-made-of#ooid=11eXZobjrG8DCSTgrNjVinU-YmmdYjhe: Downloading webpage
[generic] material-world-how-google-discovered-what-software-is-made-of#ooid=11eXZobjrG8DCSTgrNjVinU-YmmdYjhe: Extracting information
[download] Downloading playlist: Material world: how Google discovered what software is made of | The Verge
[generic] playlist Material world: how Google discovered what software is made of | The Verge: Collected 1 video ids (downloading 1 of them)
[download] Downloading video #1 of 1
[youtube] Setting language
[youtube] Q8TXgCzxEnw: Downloading webpage
[youtube] Q8TXgCzxEnw: Downloading video info webpage
[youtube] Q8TXgCzxEnw: Extracting video information
[download] Destination: Material design-Q8TXgCzxEnw.mp4
[download] 100% of 4.46MiB in 00:00

instead it downloaded the embeded youtube video :(

**Comment by aaronvegh** [comment]
Almost a year later, I can add to this, if it please you. My attempts to download are similar to above.
```
$ youtube-dl -vvv "http://www.theverge.com/2015/9/3/9252787/samsung-gear-s-2-watch-video-hands-on"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-vvv', u'http://www.theverge.com/2015/9/3/9252787/samsung-gear-s-2-watch-video-hands-on']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.09.03
[debug] Python version 2.7.10 - Darwin-14.5.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[generic] samsung-gear-s-2-watch-video-hands-on: Requesting header
WARNING: Falling back on generic information extractor.
[generic] samsung-gear-s-2-watch-video-hands-on: Downloading webpage
[generic] samsung-gear-s-2-watch-video-hands-on: Extracting information
ERROR: Unsupported URL: http://www.theverge.com/2015/9/3/9252787/samsung-gear-s-2-watch-video-hands-on
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1222, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1599, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: syntax error: line 1, column 0
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 655, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 287, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1820, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.theverge.com/2015/9/3/9252787/samsung-gear-s-2-watch-video-hands-on
```

**Comment by aaronvegh** [comment]
This is still going on. In this case, this is a Youtube embed in the page.

```
$ sudo youtube-dl -U
Password:
Updating to version 2015.12.06 ...
Updated youtube-dl. Restart youtube-dl to use the new version.
Iliad:Jezter aaron$ youtube-dl -vvv "http://www.theverge.com/2015/12/8/9869980/google-pixel-c-tablet-review-android"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-vvv', u'http://www.theverge.com/2015/12/8/9869980/google-pixel-c-tablet-review-android']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.12.06
[debug] Python version 2.7.10 - Darwin-15.0.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[generic] google-pixel-c-tablet-review-android: Requesting header
WARNING: Falling back on generic information extractor.
[generic] google-pixel-c-tablet-review-android: Downloading webpage
[generic] google-pixel-c-tablet-review-android: Extracting information
ERROR: Unsupported URL: http://www.theverge.com/2015/12/8/9869980/google-pixel-c-tablet-review-android
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1285, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 248, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=etree.TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 237, in _XML
    parser.feed(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: syntax error: line 1, column 0
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 663, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1890, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.theverge.com/2015/12/8/9869980/google-pixel-c-tablet-review-android
```

**Comment by hheimbuerger** [comment]
@remitamine 

    $ youtube-dl.exe -vvv "http://www.theverge.com/2016/5/19/11711704/android-n-new-features"
    [debug] System config: []
    [debug] User config: []
    [debug] Command-line args: [u'-vvv', u'http://www.theverge.com/2016/5/19/11711704/android-n-new-features']
    [debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
    [debug] youtube-dl version 2016.05.21.2
    [debug] Python version 2.7.10 - Windows-8-6.2.9200
    [debug] exe versions: none
    [debug] Proxy map: {}
    [VoxMedia] android-n-new-features: Downloading webpage
    [VoxMedia] 35487d7c4: Downloading webpage
    ERROR: 35487d7c4: Failed to parse JSON  (caused by ValueError('Extra data: line 1 column 1151 - line 1 column 8438 (char 1150 - 8437)',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
    Traceback (most recent call last):
      File "youtube_dl\extractor\common.pyo", line 543, in _parse_json
      File "json\__init__.pyo", line 338, in loads
      File "json\decoder.pyo", line 369, in decode
    ValueError: Extra data: line 1 column 1151 - line 1 column 8438 (char 1150 - 8437)
    Traceback (most recent call last):
      File "youtube_dl\YoutubeDL.pyo", line 676, in extract_info
      File "youtube_dl\extractor\common.pyo", line 341, in extract
      File "youtube_dl\extractor\voxmedia.pyo", line 120, in _real_extract
      File "youtube_dl\extractor\common.pyo", line 547, in _parse_json
    ExtractorError: 35487d7c4: Failed to parse JSON  (caused by ValueError('Extra data: line 1 column 1151 - line 1 column 8438 (char 1150 - 8437)',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the
    latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by remitamine** [comment]
there was a change in the wabsite(volume emebds), it will be fixed in the next version.
however you can download this video using:`youtube-dl ooyala:hqazNsMzE6xI8BCRjlkQaYMdsdMARQLj`
