### ISSUE TITLE
XML parsing error on http://www.daisuki.net/anime/watch/MUSHISHI_Next_Passage/gNc

### ISSUE THREAD

**Issue by jillh510** [rg3/youtube-dl#3186]
python -m youtube_dl -v --write-info-json --skip-download http://www.daisuki.net/anime/watch/MUSHISHI_Next_Passage/gNc
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', '--write-info-json', '--skip-download', 'http://www.daisuki.net/anime/watch/MUSHISHI_Next_Passage/gNc']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.06.24.1
[debug] Python version 2.7.5 - Darwin-13.2.0-x86_64-i386-64bit
[debug] Proxy map: {}
[generic] gNc: Requesting header
WARNING: Falling back on generic information extractor.
[generic] gNc: Downloading webpage
[generic] gNc: Extracting information
ERROR: Unsupported URL: http://www.daisuki.net/anime/watch/MUSHISHI_Next_Passage/gNc; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/Users/jill/june/.virtualenv/lib/python2.7/site-packages/youtube_dl/extractor/generic.py", line 451, in _real_extract
    doc = parse_xml(webpage)
  File "/Users/jill/june/.virtualenv/lib/python2.7/site-packages/youtube_dl/utils.py", line 1406, in parse_xml
    return xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: mismatched tag: line 44, column 2
Traceback (most recent call last):
  File "/Users/jill/june/.virtualenv/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 516, in extract_info
    ie_result = ie.extract(url)
  File "/Users/jill/june/.virtualenv/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 167, in extract
    return self._real_extract(url)
  File "/Users/jill/june/.virtualenv/lib/python2.7/site-packages/youtube_dl/extractor/generic.py", line 741, in _real_extract
    raise ExtractorError('Unsupported URL: %s' % url)
ExtractorError: Unsupported URL: http://www.daisuki.net/anime/watch/MUSHISHI_Next_Passage/gNc; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by yan12125** [comment]
http://www.daisuki.net/anime/watch/MUSHISHI_Next_Passage/gNc is gone. Please move to #4738 for further discussions.
