### ISSUE TITLE
Unable to extract uploader id

### ISSUE THREAD

**Issue by chandpriyankara** [rg3/youtube-dl#31910]
## Checklist

- [ X] I'm reporting a broken site support issue
- [ X] I've verified that I'm running youtube-dl version **2021.12.17**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ X] I've searched the bugtracker for similar bug reports including closed ones
- [ X] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-x', '--audio-format', 'mp3', '-w', '--audio-quality', '5', 'https://www.youtube.com/watch?v=SDmzwQEYKVU']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.6 (CPython) - Linux-6.3.0-rc2-chand-x86_64-with-glibc2.35
[debug] exe versions: ffmpeg 4.4.2, ffprobe 4.4.2
[debug] Proxy map: {}
[youtube] SDmzwQEYKVU: Downloading webpage
[youtube] SDmzwQEYKVU: Downloading MPD manifest
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

youtube-dl fail to download the link provided, saying a uploader id wasn't able to extract.
https://www.youtube.com/watch?v=SDmzwQEYKVU

**Comment by Aremu-damilare** [comment]
I experience this issue while using flask along side the youtube-dl, I had to uninstall and pip install youtube_dl==2020.11.18 then it worked

**Comment by chandpriyankara** [comment]
That works for me also. Then again this is a bug on latest version [2021.12.17]

**Comment by Aremu-damilare** [comment]
> That works for me also. Then again this is a bug on latest version [2021.12.17]

Yes.

**Comment by dirkf** [comment]
>[X] I've searched the bugtracker for similar bug reports including closed ones

Read #30839 (**again**?) to learn how.

>[X] I've read bugs section in FAQ

Use the knowledge.

2020.11.18 will fail differently.
