### ISSUE TITLE
ARD Mediathek doesn't work with 2014.06.26

### ISSUE THREAD

**Issue by tkan** [rg3/youtube-dl#3193]
Trying to access ARD Mediathek on Ubuntu 12.04

    sudo youtube-dl -U
    >> youtube-dl is up-to-date (2014.06.26)

For exampe this link `http://mediathek.daserste.de/sendungen_a-z/21675666_fifa-wm-2014/22226718_mehmet-scholl-das-ist-nicht-mehr-mein-sport-?buchstabe=F` throws this error message:

	[ARD] 22226718_mehmet-scholl-das-ist-nicht-mehr-mein-sport-: Downloading webpage
	WARNING: unable to extract description; please report this issue on http://yt-dl.org/bug
	WARNING: unable to extract thumbnail url; please report this issue on http://yt-dl.org/bug
	[ARD] 22226718_mehmet-scholl-das-ist-nicht-mehr-mein-sport-: Downloading JSON metadata
	ERROR: Failed to download JSON; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
	Traceback (most recent call last):
	  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 307, in _download_json
		return json.loads(json_string)
	  File "/usr/lib/python2.7/json/__init__.py", line 326, in loads
		return _default_decoder.decode(s)
	  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
		obj, end = self.raw_decode(s, idx=_w(s, 0).end())
	  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
		raise ValueError("No JSON object could be decoded")
	ValueError: No JSON object could be decoded
	Traceback (most recent call last):
	  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 516, in extract_info
		ie_result = ie.extract(url)
	  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 167, in extract
		return self._real_extract(url)
	  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/ard.py", line 51, in _real_extract
		'http://www.ardmediathek.de/play/media/%s' % video_id, video_id)
	  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 309, in _download_json
		raise ExtractorError('Failed to download JSON', cause=ve)
	ExtractorError: Failed to download JSON; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by TRox1972** [comment]
The provided URL doesn't point to any one video, just like the test URL in `ard.py`. Videos that do link to one video still work, though, like [this one](http://mediathek.daserste.de/Sportschau-live/Wittmann-will-Erfolg-wiederholen/Video?bcastId=723230&documentId=29516744)

**Comment by dstftw** [comment]
Should work fine with latest version.
