### ISSUE TITLE
please report this issue on https://yt-dl.org/bug

### ISSUE THREAD

**Issue by philiprbrenan** [rg3/youtube-dl#31970]
As requested in the output from youtube-dl:

```
youtube-dl -vv https://www.youtube.com/watch?v=fNsHmjdgcHI&list=RDEME57zQmiWw8Qt3SWu3xOuWQ&index=5
[1] 221692
[2] 221693
phil@p:~/Downloads$ [debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-vv', 'https://www.youtube.com/watch?v=fNsHmjdgcHI']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.8.10 (CPython) - Linux-5.8.0-59-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] fNsHmjdgcHI: Downloading webpage
[youtube] fNsHmjdgcHI: Downloading player 931a8913
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by dirkf** [comment]
When it says "report this issue on", this is shorthand for "follow the reporting procedure laid out at" and obviously don't report it again if it's already been reported. This should have been apparent when you read the pinned issue #30839. The issue title "READ THIS BEFORE OPENING A NEW ISSUE! THIS MEANS YOU!" should have been a hint. Read it again.

**Comment by philiprbrenan** [comment]
Possibly you could add such an important warning to your software to avoid such outcome in the future.  When reading the message produced by the software it implies that something so unusual has gone wrong that there is some urgency to the situation which warrants immediate action.   Without this request, as worded,  one  might well have reported the problem in the usual manner if one had time to do so - or not if one did not have the  time or interest to do so.

**Comment by dirkf** [comment]
It was important when it was first reported, less so after more than 300 people so far independently thought it might be helpful to do so again and especially since there is already a solution. See https://github.com/ytdl-org/youtube-dl#user-content-bugs. I really don't think that the instructions in the issue tracker could be plainer.
