### ISSUE TITLE
youtube-dl from nightly build is suspicious?

### ISSUE THREAD

**Issue by FFortissimo** [rg3/youtube-dl#32042]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question
Working on Windows 11.
youtube-dl.exe gives "ERROR: Unable to extract uploader id;"
I checked here and found the problem
I went to https://github.com/ytdl-patched/youtube-dl/releases and downloaded the latest build (youtube-dl 2023.04.14.19419 Latest).
When I tried running youtube-dl.exe I first got a warning from Windows that the file was unsafe and next a warning from F-Secure.
Inspecting the information brought me to https://www.f-secure.com/v-descs/w32_malware.shtml.

The version from http://ytdl-org.github.io/youtube-dl/download.html (2021.12.17) didn't trigger anything.

What can be the reason for this trigger and block of youtube-dl.exe?

**Comment by dirkf** [comment]
The Windows yt-dl program expands the entire program and enough of Python 3.4 to run it. Probably, this is what causes the anti-virus concern. However, since anti-virus detection is equivalent to the Halting Problem, it can't work reliably.

See also https://github.com/yt-dlp/yt-dlp/issues/25.

Disable this heuristic in the anti-virus program, or use a different antivirus tool, or submit the latest download here to get it white-listed (or, worst case, to find that there actually is a malware issue -- please report that for sure): https://www.f-secure.com/en/business/support-and-downloads/submit-a-sample

If you have or install Python on your system, you can install the program as a Python module and probably avoid anti-virus shenanigans. Or use the Windows Subsystem for Linux (if available) with the single file POSIX build.

**Comment by FFortissimo** [comment]
I submitted the file.
I'll try to remember to put their response here ;)

**Comment by stefanw1337** [comment]
From windows I'm getting similar problems with "id". Also I don't know how to make the script use youtube-dl.exe instead of
"from youtube_dl import YoutubeDL"
(I put the youtube-dl.exe in both the folder and in %Windows-whatever%\system32 and added it in PATH.
I assume the errors within yt_chapters.py stems from it not able to download it correctly.

F:\Download\OTXO>py yt_chapters.py --split "https://www.youtube.com/watch?v=3prx6jXJCkQ"
[youtube] 3prx6jXJCkQ: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\youtube_dl\extractor\common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Download\OTXO\yt_chapters.py", line 118, in <module>
    infos = get_infos( link_to_download, options, USE_CLI )
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Download\OTXO\handleYDL.py", line 32, in get_infos
    extracted_infos = ydl.extract_info( url, download=False )
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\youtube_dl\YoutubeDL.py", line 808, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\youtube_dl\YoutubeDL.py", line 824, in wrapper
    self.report_error(compat_str(e), e.format_traceback())
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\youtube_dl\YoutubeDL.py", line 628, in report_error
    self.trouble(error_message, tb)
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\youtube_dl\YoutubeDL.py", line 598, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dirkf** [comment]
@stefanw1337, review #30839 as requested to find your solution. This issue about a (presumably false) virus detection in one solution.

**Comment by dirkf** [comment]
@FFortissimo: any result? Ofc there have been new nightly releases since then.
