### ISSUE TITLE
 unable to download video data: <urlopen error [Errno -2] Name or service not known>

### ISSUE THREAD

**Issue by gopal-srinivas** [rg3/youtube-dl#3204]
I am getting the following error on ubuntu 14.04

youtube-dl -f 137 -v http://www.youtube.com/watch?v=1FaTtBk2rCg
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-f', '137', '-v', 'http://www.youtube.com/watch?v=1FaTtBk2rCg']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.06.26
[debug] Python version 2.7.6 - Linux-3.8.0-42-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] Proxy map: {}
[youtube] Setting language
[youtube] 1FaTtBk2rCg: Downloading webpage
[youtube] 1FaTtBk2rCg: Downloading video info webpage
[youtube] 1FaTtBk2rCg: Extracting video information
ERROR: unable to download video data: <urlopen error [Errno -2] Name or service not known>
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1020, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 996, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 291, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 58, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1225, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 591, in https_open
    return self.do_open(HTTPSConnectionV3, req)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno -2] Name or service not known>

**Comment by feuerbach** [comment]
Just ran into the same/similar issue:

```
% youtube-dl -v 'https://www.youtube.com/watch?v=sE1qWyQWWVY'                                                                                                                                 
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=sE1qWyQWWVY']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.06.06
[debug] Python version 3.7.7 (CPython) - Linux-5.6.15-200.fc31.x86_64-x86_64-with-fedora-31-Thirty_One
[debug] exe versions: ffmpeg 4.2.3, ffprobe 4.2.3
[debug] Proxy map: {}
[youtube] sE1qWyQWWVY: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [Errno -2] Name or service not known> (caused by URLError(gaierror(-2, 'Name or service not known')))
  File "/home/feuerbach/.local/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 627, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/home/feuerbach/.local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib64/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib64/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/usr/lib64/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/home/feuerbach/.local/lib/python3.7/site-packages/youtube_dl/utils.py", line 2736, in https_open
    req, **kwargs)
  File "/usr/lib64/python3.7/urllib/request.py", line 1321, in do_open
    raise URLError(err)
```

**Comment by vdbhb59** [comment]
Facing this several times in each download, at various % levels.
1. [download]  54.3% of 1.26GiB at  7.53MiB/s ETA 01:18ERROR: 
2. [download]  62.6% of 1.26GiB at  1.87MiB/s ETA 04:19ERROR: 
3. [download]  73.6% of 1.26GiB at  1.87MiB/s ETA 03:09ERROR:

**Comment by kalimba666** [comment]
I have this error, too:
"ERROR: Unable to download webpage: <urlopen error [Errno -2] Name or service not known> (caused by URLError(gaierror(-2, 'Name or service not known')))"

It's on Ubuntu 20.10

**Comment by qianqianjie1** [comment]
Did you solve this problem, I ran into the same problem

**Comment by kalimba666** [comment]
> Did you solve this problem, I ran into the same problem

Nope.

**Comment by fuzxi** [comment]
This has started for me recently as well. It always throws this error on the first attempt to download a video, then completes successfully on the second attempt.

**Comment by fuzxi** [comment]
Example: output of `youtube-dl -v https://www.youtube.com/watch\?v\=3Kwj5aowCEg`

[youtube-dl-output.txt](https://github.com/ytdl-org/youtube-dl/files/6120610/youtube-dl-output.txt)
