### ISSUE TITLE
README installation instructions should use pip install git+https://github.com/ytdl-org/youtube-dl.git

### ISSUE THREAD

**Issue by paulrougieux** [rg3/youtube-dl#32069]
## Checklist

- [ ] I'm reporting a broken site support issue
- [X] I've verified that I'm running youtube-dl version **2021.12.17**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Description

This is about the [README.md](https://github.com/ytdl-org/youtube-dl/blob/master/README.md) installation instructions, related to issue https://github.com/ytdl-org/youtube-dl/issues/31585 and hidden messages at the end of issue  https://github.com/ytdl-org/youtube-dl/issues/31530. It would be nice to make it clear that the current pip install instruction in the readme is not going to work (as long as the version is not updated as explained in issue #31585 ).

### Current installation instruction

You can also use pip:

    sudo -H pip install --upgrade youtube-dl

### Proposed installation instruction

You can also use pip to install or upgrade to the latest version from the git repository:

     pip install --upgrade --force-reinstall git+https://github.com/ytdl-org/youtube-dl.git

**Comment by paulrougieux** [comment]
> This installation is described in the appropriate post in #31530, which is the right place for it. In future it shouldn't be necessary.

Sure, but since this future takes a long time to materialize, I thought it would be nice to just provide at least an install instruction for the latest version that will always work.

**Comment by benjibasson83** [comment]
pip install --upgrade youtube-dl give
Requirement already satisfied: youtube-dl in /data/data/com.termux/files/usr/lib/python3.11/site-packages (2021.12.17)

Please give me the fix for youtube-dl --no-cache-dir --extract-audio --audio-format mp3 -w -i -o "%(title)s.%(ext)s" https://m.youtube.com/watch?v=JQCD5LBJ1jU --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--no-cache-dir', '--extract-audio', '--audio-format', 'mp3', '-w', '-i', '-o', '%(title)s.%(ext)s', 'https://m.youtube.com/watch?v=JQCD5LBJ1jU', '--verbose']
[debug] Encodings: locale utf-8, fs utf-8, out utf-8, pref utf-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.11.3 (CPython) - Linux-4.19.157-perf+-aarch64-with-libc
[debug] exe versions: ffmpeg 6.0, ffprobe 6.0
[debug] Proxy map: {}
[youtube] JQCD5LBJ1jU: Downloading webpage
[youtube] JQCD5LBJ1jU: Downloading MPD manifest
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dirkf** [comment]
Also, the appropriate _pip_ command argument for users with no _git_, like the previous poster, is given in [the post in #31530](https://github.com/ytdl-org/youtube-dl/issues/31530#issuecomment-1435477247).

**Comment by ProvisionlabTeam** [comment]
@dirkf maybe this is an unobtrusive request to release a new version))

**Comment by benjibasson83** [comment]
@dirkf if therecare many error report, many users saying that it doesn't
work that means your solution is understandable.
The solution is to release an update once per year is not calling for the
moon

Le dimanche 23 avril 2023, Dmytro Usenko ***@***.***> a
écrit :

**Comment by holms** [comment]
Can someone explain me why there's no 2023 build? And what this ticket is even about.. latest version from pip doesn't even work. Why there are no nightly builds, why latest version is from 2021? Wtf is happening.

**Comment by benjibasson83** [comment]
Hi @dirkf <https://github.com/dirkf> I confirm your readme is useless.
because there is only
2021.12.17 <https://yt-dl.org/downloads/2021.12.17/youtube-dl> (sig
<https://yt-dl.org/downloads/2021.12.17/youtube-dl.sig>)* SHA256*:
7880e01abe282c7fd596f429c35189851180d6177302bb215be1cdec78d6d06d on
http://ytdl-org.github.io/youtube-dl/download.html
you never release update of tyny program even when youtube change its
system.
In contrast of ubuntu whom release update every day for the whole OS

Le dim. 23 avr. 2023 à 23:46, Roman Gorodeckij ***@***.***> a
écrit :

**Comment by kalaolani** [comment]
![image](https://user-images.githubusercontent.com/25650400/235252707-df89810c-f5d6-4970-9d3f-8be27d5ba433.png)

**Comment by ProvisionlabTeam** [comment]
What is valuable in this image lol?

**Comment by 4cq2** [comment]
I dont agree with the original post. a better method would be:

~~~
pip install https://github.com/ytdl-org/youtube-dl/archive/refs/heads/master.zip
~~~

as the method described in the original comments assume a user has an installed and working Git environment.

**Comment by dirkf** [comment]
What I said: https://github.com/ytdl-org/youtube-dl/issues/32069#issuecomment-1518738013

**Comment by 4cq2** [comment]
sorry man but I DO have to agree with the original poster on one point. all these comments you are linking to, that data should be here:

https://github.com/ytdl-org/youtube-dl#installation

not buried in some comment linked to a comment linked to a comment, that doesn't even give an example command like I did. you want to hold off on a new release for years, of course thats your decision. but at least make the HEAD install as painless as possible, with clear and direct communication to the end users.

**Comment by benjibasson83** [comment]
I agree with Steven Penny
