### ISSUE TITLE
unable to DL from Bitchute.com

### ISSUE THREAD

**Issue by jd1008** [rg3/youtube-dl#32198]
$ youtube-dl -v -F https://www.bitchute.com/video/cTaQFilUsGW6/
[debug] System config: ['--prefer-free-formats']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://www.bitchute.com/video/cTaQFilUsGW6/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.8 (CPython) - Linux-6.0.8-100.fc35.x86_64-x86_64-with-glibc2.34
[debug] exe versions: ffmpeg 4.4.3, ffprobe N-51556-ge278500
[debug] Proxy map: {}
[BitChute] cTaQFilUsGW6: Downloading webpage
[BitChute] cTaQFilUsGW6: Checking video URL
[BitChute] cTaQFilUsGW6: video URL is invalid, skipping: HTTP Error 404: Not Found
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/sdb3/home/jd/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/sdb3/home/jd/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/sdb3/home/jd/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/sdb3/home/jd/bin/youtube-dl/youtube_dl/extractor/bitchute.py", line 66, in _real_extract
    self._sort_formats(formats)
  File "/sdb3/home/jd/bin/youtube-dl/youtube_dl/extractor/common.py", line 1374, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Checklist

- [ ] I'm reporting a broken site support
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by dirkf** [comment]
Test PR #31019 (comment there), or, for now, use `--force-generic`.

**Comment by girante** [comment]
this issue is still not solved on the current HEAD version (or we are seeing a regression). Using "--force-generic" is also not working.

**Comment by dirkf** [comment]
Change www.bitchute.com to old.bitchute.com. Also, test the PR (but it should probably be replaced with a new back-port from _yt-dlp_).
