### ISSUE TITLE
Support for life ok (also based on ooyla) 

### ISSUE THREAD

**Issue by shirishag75** [rg3/youtube-dl#3221]
Hi all, 
This is same/similar issue reported at #3044 

    $ youtube-dl --verbose http://www.lifeok.com/shows/nadaan-parinde/full-episode-videos/purab-decides-to-find-out-the-truth-behind-the-attack-on-baba/590-864-1-68229
    [debug] System config: []
    [debug] User config: []
    [debug] Command-line args: ['--verbose', 'http://www.lifeok.com/shows/nadaan-parinde/full-episode-videos/purab-decides-to-find-out-the-truth-behind-the-attack-on-baba/590-864-1-68229']
    [debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
    [debug] youtube-dl version 2014.06.19
    [debug] Python version 2.7.7 - Linux-3.14-1-amd64-x86_64-with-debian-jessie-sid
    [debug] Proxy map: {}
    [generic] 590-864-1-68229: Requesting header
    WARNING: Falling back on generic information extractor.
    [generic] 590-864-1-68229: Downloading webpage
    [generic] 590-864-1-68229: Extracting information
    ERROR: Unsupported URL: http://www.lifeok.com/shows/nadaan-parinde/full-episode-videos/purab-decides-to-find-out-the-truth-behind-the-attack-on-baba/590-864-1-68229; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 440, in _real_extract
        doc = parse_xml(webpage)
      File "/usr/lib/python2.7/dist-packages/youtube_dl/utils.py", line 1406, in parse_xml
        return xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
      File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
        parser.feed(text)
      File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
        self._raiseerror(v)
      File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
        raise err
    ParseError: not well-formed (invalid token): line 6, column 685
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 516, in extract_info
        ie_result = ie.extract(url)
      File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 167, in extract
        return self._real_extract(url)
      File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 722, in _real_extract
        raise ExtractorError('Unsupported URL: %s' % url)
    ExtractorError: Unsupported URL: http://www.lifeok.com/shows/nadaan-parinde/full-episode-videos/purab-decides-to-find-out-the-truth-behind-the-attack-on-baba/590-864-1-68229; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

Hoping to hear from the developer.

**Comment by remitamine** [comment]
works with the latest version.
