### ISSUE TITLE
URL can't download

### ISSUE THREAD

**Issue by nicolasgrise** [rg3/youtube-dl#32338]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
user@users-MacBook-Air desktop % youtube-dl https://youtu.be/svcgO8ahbME
[youtube] svcgO8ahbME: Downloading webpage
[youtube] svcgO8ahbME: Downloading player 6ed0d907
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/extractor/youtube.py", line 1360, in _decrypt_signature
    func = self._extract_signature_function(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/extractor/youtube.py", line 1277, in _extract_signature_function
    cache_res = res(test_string)
                ^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/extractor/youtube.py", line 1344, in <lambda>
    return lambda s: initial_function([s])
                     ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/jsinterp.py", line 258, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/jsinterp.py", line 182, in interpret_expression
    return obj[member](argvals)
           ~~~^^^^^^^^
KeyError: 'QV'
 (caused by KeyError('QV')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
user@users-MacBook-Air desktop % youtube-dl -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.11.3 (CPython) - macOS-12.6.5-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options.
user@users-MacBook-Air desktop % youtube-dl -v https://youtu.be/svcgO8ahbME
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://youtu.be/svcgO8ahbME']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.11.3 (CPython) - macOS-12.6.5-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] svcgO8ahbME: Downloading webpage
[youtube] svcgO8ahbME: Downloading player 6ed0d907
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/extractor/youtube.py", line 1360, in _decrypt_signature
    func = self._extract_signature_function(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/extractor/youtube.py", line 1277, in _extract_signature_function
    cache_res = res(test_string)
                ^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/extractor/youtube.py", line 1344, in <lambda>
    return lambda s: initial_function([s])
                     ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/jsinterp.py", line 258, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/jsinterp.py", line 182, in interpret_expression
    return obj[member](argvals)
           ~~~^^^^^^^^
KeyError: 'QV'
 (caused by KeyError('QV')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/extractor/youtube.py", line 1360, in _decrypt_signature
    func = self._extract_signature_function(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/extractor/youtube.py", line 1277, in _extract_signature_function
    cache_res = res(test_string)
                ^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/extractor/youtube.py", line 1344, in <lambda>
    return lambda s: initial_function([s])
                     ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/jsinterp.py", line 258, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/jsinterp.py", line 182, in interpret_expression
    return obj[member](argvals)
           ~~~^^^^^^^^
KeyError: 'QV'
Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/extractor/youtube.py", line 1360, in _decrypt_signature
    func = self._extract_signature_function(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/extractor/youtube.py", line 1277, in _extract_signature_function
    cache_res = res(test_string)
                ^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/extractor/youtube.py", line 1344, in <lambda>
    return lambda s: initial_function([s])
                     ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/jsinterp.py", line 258, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/jsinterp.py", line 182, in interpret_expression
    return obj[member](argvals)
           ~~~^^^^^^^^
KeyError: 'QV'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/extractor/youtube.py", line 1641, in _real_extract
    signature = self._decrypt_signature(sc['s'][0], video_id, player_url)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/extractor/youtube.py", line 1370, in _decrypt_signature
    raise ExtractorError(
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/extractor/youtube.py", line 1360, in _decrypt_signature
    func = self._extract_signature_function(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/extractor/youtube.py", line 1277, in _extract_signature_function
    cache_res = res(test_string)
                ^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/extractor/youtube.py", line 1344, in <lambda>
    return lambda s: initial_function([s])
                     ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/jsinterp.py", line 258, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.11/site-packages/youtube_dl/jsinterp.py", line 182, in interpret_expression
    return obj[member](argvals)
           ~~~^^^^^^^^
KeyError: 'QV'
 (caused by KeyError('QV')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

user@users-MacBook-Air desktop % sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl

sudo chmod a+rx /usr/local/bin/youtube-dl
Password:
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     3  100     3    0     0      2      0  0:00:01  0:00:01 --:--:--     2
100     3  100     3    0     0      2      0  0:00:01  0:00:01 --:--:--     2
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
100 1794k  100 1794k    0     0   571k      0  0:00:03  0:00:03 --:--:-- 8631k
user@users-MacBook-Air desktop % sudo pip install --upgrade youtube_dl
sudo: pip: command not found
user@users-MacBook-Air desktop % youtube-dl https://youtu.be/svcgO8ahbME
env: python: No such file or directory
user@users-MacBook-Air desktop % sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
sudo chmod a+rx /usr/local/bin/youtube-dl
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     3  100     3    0     0      3      0  0:00:01 --:--:--  0:00:01     3
100     3  100     3    0     0      1      0  0:00:03  0:00:01  0:00:02     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
100 1794k  100 1794k    0     0   618k      0  0:00:02  0:00:02 --:--:-- 3640k
user@users-MacBook-Air desktop % youtube-dl https://youtu.be/svcgO8ahbME
env: python: No such file or directory
```

## Description

I've been trying to download a file from youtube but it doesn't seem to work. I've checked for bugs and updates but now it only says "env: python: No such file or directory". Any suggestions on what to do next?

**Comment by wolfman616** [comment]
I have the same symptom.
[debug] System config: []
[debug] User config: ['-o', 'S:/IN/_ youtube/%(title)s.%(ext)s', '-x', '--extract-audio', '--audio-format', 'best']
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=t96uNVl1x2A', '-o', 'S:/IN/_ youtube/%(title)s-%(id)s.%(ext)s', '-x', '--extract-audio', '--audio-format', 'best', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg git-2020-03-28-3362330, ffprobe git-2020-03-28-3362330
[debug] Proxy map: {}
[youtube] t96uNVl1x2A: Downloading webpage
[youtube] t96uNVl1x2A: Downloading player 6ed0d907
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\youtube.py", line 1361, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\youtube.py", line 1277, in _extract_signature_function
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\youtube.py", line 1344, in <lambda>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\jsinterp.py", line 258, in resf
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\jsinterp.py", line 56, in interpret_statement
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\jsinterp.py", line 182, in interpret_expression
KeyError: 'QV'
 (caused by KeyError('QV',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\youtube.py", line 1361, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\youtube.py", line 1277, in _extract_signature_function
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\youtube.py", line 1344, in <lambda>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\jsinterp.py", line 258, in resf
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\jsinterp.py", line 56, in interpret_statement
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\jsinterp.py", line 182, in interpret_expression
KeyError: 'QV'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\youtube.py", line 1361, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\youtube.py", line 1277, in _extract_signature_function
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\youtube.py", line 1344, in <lambda>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\jsinterp.py", line 258, in resf
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\jsinterp.py", line 56, in interpret_statement
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\jsinterp.py", line 182, in interpret_expression
KeyError: 'QV'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\youtube.py", line 1641, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\youtube.py", line 1371, in _decrypt_signature
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\youtube.py", line 1361, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\youtube.py", line 1277, in _extract_signature_function
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\youtube.py", line 1344, in <lambda>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\jsinterp.py", line 258, in resf
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\jsinterp.py", line 56, in interpret_statement
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\jsinterp.py", line 182, in interpret_expression
KeyError: 'QV'
 (caused by KeyError('QV',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
