### ISSUE TITLE
screencast.com support

### ISSUE THREAD

**Issue by Nikoli** [rg3/youtube-dl#3236]
Please add support for http://screencast.com/

**Comment by CFXd** [comment]
Hi there, thank you guys for working on this handy tool. I came across this related thread when trying to grab a screencast.com video file. Here's my command line output:

```
$ youtube-dl --verbose http://screencast.com/t/fQLBHT22A
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://screencast.com/t/fQLBHT22A']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.01.09
[debug] Python version 2.7.11 - Darwin-14.5.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.8.4, ffprobe 2.8.4, rtmpdump 2.4
[debug] Proxy map: {}
[generic] fQLBHT22A: Requesting header
WARNING: Falling back on generic information extractor.
[generic] fQLBHT22A: Downloading webpage
[generic] fQLBHT22A: Extracting information
ERROR: Unsupported URL: http://screencast.com/t/fQLBHT22A
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1289, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 248, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=etree.TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 237, in _XML
    parser.feed(text)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 34, column 71
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 665, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 312, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1908, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://screencast.com/t/fQLBHT22A
```
