### ISSUE TITLE
rtl-now.rtl.de

### ISSUE THREAD

**Issue by Fusl** [rg3/youtube-dl#3237]
Hi,

trying to download a file from rtl-now.rtl.de after logging in and buying the episode doesn't work with youtube-dl. I tried to pass the mail address and the password with the -u and -p parameters and also tried to load a (from Firefox) reported cookie file:

```
 $ youtube-dl 'http://rtl-now.rtl.de/doctors-diary/hurra-endlich-wieder-liebeskummer.php?container_id=26905&player=1&season=2' --cookies cookies.txt --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://rtl-now.rtl.de/doctors-diary/hurra-endlich-wieder-liebeskummer.php?container_id=26905&player=1&season=2', '--cookies', 'cookies.txt', '--verbose']
[debug] Encodings: locale US-ASCII, fs utf-8, out US-ASCII, pref US-ASCII
[debug] youtube-dl version 2014.07.11.1
[debug] Python version 2.7.5 - Darwin-13.2.0-x86_64-i386-64bit
[debug] Proxy map: {}
[RTLnow] 26905: Downloading webpage
WARNING: unable to extract upload date; please report this issue on http://yt-dl.org/bug
ERROR: Unable to extract playerdata_url; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 516, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 168, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/rtlnow.py", line 129, in _real_extract
    r"'playerdata': '(?P<playerdata_url>[^']+)'", webpage, 'playerdata_url')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 394, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 384, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract playerdata_url; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
```

Omitting the GET parameter from the URL results in a slightly different error message:

```
 $ youtube-dl 'http://rtl-now.rtl.de/doctors-diary/hurra-endlich-wieder-liebeskummer.php' --cookies cookies.txt --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://rtl-now.rtl.de/doctors-diary/hurra-endlich-wieder-liebeskummer.php', '--cookies', 'cookies.txt', '--verbose']
[debug] Encodings: locale US-ASCII, fs utf-8, out US-ASCII, pref US-ASCII
[debug] youtube-dl version 2014.07.11.1
[debug] Python version 2.7.5 - Darwin-13.2.0-x86_64-i386-64bit
[debug] Proxy map: {}
[generic] hurra-endlich-wieder-liebeskummer: Requesting header
[redirect] Following redirect to http://rtl-now.rtl.de/doctors-diary.php
[generic] doctors-diary: Requesting header
WARNING: Falling back on generic information extractor.
[generic] doctors-diary: Downloading webpage
[generic] doctors-diary: Extracting information
ERROR: Unsupported URL: http://rtl-now.rtl.de/doctors-diary.php; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 456, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1409, in parse_xml
    return xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: mismatched tag: line 154, column 2
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 516, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 168, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 751, in _real_extract
    raise ExtractorError('Unsupported URL: %s' % url)
ExtractorError: Unsupported URL: http://rtl-now.rtl.de/doctors-diary.php; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
```

Would be really cool if you can fix this :)

Thanks in advance!

- Fusl

**Comment by dstftw** [comment]
Closing since rtl is now served by nowtv.de.
