### ISSUE TITLE
error downloading with 2014.07.11.3 but 2041.07.10 works fine

### ISSUE THREAD

**Issue by graysky2** [rg3/youtube-dl#3251]
Here is the output when downloading with the latest release.  
Note that I edited the invoking downloader info since I noticed it had my ip in there and bunch of other info I didn't understand.

```
% youtube-dl -v -q http://www.youtube.com/watch?v=sgJlBOR1KXk                                        :(
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', '-q', 'http://www.youtube.com/watch?v=sgJlBOR1KXk']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.07.11.3
[debug] Python version 3.4.1 - Linux-3.15.5-custom-2-x86_64-with-arch
[debug] Proxy map: {}
[debug] Invoking downloader on 'https://r3---sn-vgqs7nez.googlevideo.com/videoplayback?itag=22<<<EDITED>>>

ERROR: unable to download video data: ''
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 1022, in process_info
    success = dl(filename, info_dict)
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 998, in dl
    return fd.download(name, info)
  File "/usr/lib/python3.4/site-packages/youtube_dl/downloader/common.py", line 291, in download
    return self.real_download(filename, info_dict)
  File "/usr/lib/python3.4/site-packages/youtube_dl/downloader/http.py", line 58, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 1227, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 455, in open
    response = self._open(req, data)
  File "/usr/lib/python3.4/urllib/request.py", line 473, in _open
    '_open', req)
  File "/usr/lib/python3.4/urllib/request.py", line 433, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 1230, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.4/urllib/request.py", line 1194, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.4/http/client.py", line 1172, in getresponse
    response.begin()
  File "/usr/lib/python3.4/http/client.py", line 351, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine: ''
```
Downgrading to 2014.07.10 works fine.

**Comment by remitamine** [comment]
now, it's working.
```
youtube-dl -v http://www.youtube.com/watch?v=sgJlBOR1KXk
[debug] System config: []
[debug] User config: ['--external-downloader', 'aria2c', '--external-downloader-args', '-x 16 --check-certificate=false', '-f', 'best[height<=?720]', '--sub-lang', 'ar,en', '--write-sub']
[debug] Command-line args: ['-v', 'http://www.youtube.com/watch?v=sgJlBOR1KXk']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.07.21
[debug] Python version 3.4.3 - Linux-4.1.2-2-ARCH-x86_64-with-arch-Arch-Linux
[debug] exe versions: ffmpeg 2.7.2, ffprobe 2.7.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] sgJlBOR1KXk: Downloading webpage
[youtube] sgJlBOR1KXk: Downloading video info webpage
[youtube] sgJlBOR1KXk: Extracting video information
[youtube] sgJlBOR1KXk: Downloading DASH manifest
[youtube] sgJlBOR1KXk: Downloading DASH manifest
WARNING: ar subtitles not available for sgJlBOR1KXk
[info] Writing video subtitles to: Refrigerator Repair- Replacing the Icemaker Control & Motor Assembly (Whirlpool Part# W10190935)-sgJlBOR1KXk.en.srt
[debug] Invoking downloader on 'https://r19---sn-hpa7lne7.googlevideo.com/videoplayback?initcwndbps=551250&ipbits=0&pl=17&sparams=dur%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&key=yt5&requiressl=yes&itag=22&mm=31&mn=sn-hpa7lne7&ms=au&mt=1438366069&mv=m&source=youtube&ip=197.205.50.22&fexp=9405994%2C9407169%2C9407991%2C9408206%2C9408710%2C9414764%2C9414855%2C9415365%2C9415485%2C9416126%2C9416485%2C9417193%2C9417930%2C9417991%2C9418201%2C9418203&sver=3&id=o-APARiVTYup_4y0z4rTyqclSSB4tPKmgBWLza2CgIzXJj&dur=336.271&mime=video%2Fmp4&signature=D6658A673530E71ECD1E4BE8BD69F1833706642B.EAECF3EB08DD0880C0FBBA3AEE3EAF8C2DFEE97E&upn=dolwbGuW3RU&ratebypass=yes&lmt=1392015659898095&expire=1438387708'
[download] Destination: Refrigerator Repair- Replacing the Icemaker Control & Motor Assembly (Whirlpool Part# W10190935)-sgJlBOR1KXk.mp4
[debug] aria2c command line: aria2c -c -x 16 --check-certificate=false --out 'Refrigerator Repair- Replacing the Icemaker Control & Motor Assembly (Whirlpool Part# W10190935)-sgJlBOR1KXk.mp4.part' --header 'Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7' --header 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' --header 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/20.0 (Chrome)' --header 'Accept-Encoding: gzip, deflate' --header 'Accept-Language: en-us,en;q=0.5' -- 'https://r19---sn-hpa7lne7.googlevideo.com/videoplayback?initcwndbps=551250&ipbits=0&pl=17&sparams=dur%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&key=yt5&requiressl=yes&itag=22&mm=31&mn=sn-hpa7lne7&ms=au&mt=1438366069&mv=m&source=youtube&ip=197.205.50.22&fexp=9405994%2C9407169%2C9407991%2C9408206%2C9408710%2C9414764%2C9414855%2C9415365%2C9415485%2C9416126%2C9416485%2C9417193%2C9417930%2C9417991%2C9418201%2C9418203&sver=3&id=o-APARiVTYup_4y0z4rTyqclSSB4tPKmgBWLza2CgIzXJj&dur=336.271&mime=video%2Fmp4&signature=D6658A673530E71ECD1E4BE8BD69F1833706642B.EAECF3EB08DD0880C0FBBA3AEE3EAF8C2DFEE97E&upn=dolwbGuW3RU&ratebypass=yes&lmt=1392015659898095&expire=1438387708'
[#c6381b 1.0MiB/58MiB(1%) CN:16 DL:279KiB ETA:3m30s]
```

**Comment by dstftw** [comment]
Closing since it works fine with the latest version.
