### ISSUE TITLE
ERROR: Automatic signature extraction failed

### ISSUE THREAD

**Issue by aliensunmin** [rg3/youtube-dl#3262]
Hi all,
## I get the following error message

[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://www.youtube.com/watch?v=EqHxnJholtI', '--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8
[debug] youtube-dl version 2014.07.11.3
[debug] Python version 2.7.4 - Linux-3.8.0-35-generic-x86_64-with-Ubuntu-13.04-raring
[debug] Proxy map: {}
[youtube] Setting language
[youtube] EqHxnJholtI: Downloading webpage
[youtube] EqHxnJholtI: Downloading video info webpage
[youtube] EqHxnJholtI: Extracting video information
[youtube] EqHxnJholtI: Encrypted signatures detected.
[youtube] encrypted signature length 84 (40.43), itag 22, html5 player en_US-vfl0Cbn9e
[youtube] EqHxnJholtI: Downloading js player vfl0Cbn9e
WARNING: Writing cache to u'/home/sunmin/.cache/youtube-dl/youtube-sigfuncs/js_vfl0Cbn9e_84.json' failed: Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 391, in _extract_signature_function
    cache_res = res(test_string)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 449, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/bin/youtube-dl/youtube_dl/jsinterp.py", line 113, in resf
    res = self.interpret_statement(stmt, local_vars)
  File "/usr/bin/youtube-dl/youtube_dl/jsinterp.py", line 45, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/bin/youtube-dl/youtube_dl/jsinterp.py", line 58, in interpret_expression
    val = local_vars[m.group('in')]
KeyError: u'fo'

ERROR: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 883, in _decrypt_signature
    return func(s)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 449, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/bin/youtube-dl/youtube_dl/jsinterp.py", line 113, in resf
    res = self.interpret_statement(stmt, local_vars)
  File "/usr/bin/youtube-dl/youtube_dl/jsinterp.py", line 45, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/bin/youtube-dl/youtube_dl/jsinterp.py", line 58, in interpret_expression
    val = local_vars[m.group('in')]
KeyError: u'fo'
; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 883, in _decrypt_signature
    return func(s)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 449, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/bin/youtube-dl/youtube_dl/jsinterp.py", line 113, in resf
    res = self.interpret_statement(stmt, local_vars)
  File "/usr/bin/youtube-dl/youtube_dl/jsinterp.py", line 45, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/bin/youtube-dl/youtube_dl/jsinterp.py", line 58, in interpret_expression
    val = local_vars[m.group('in')]
KeyError: u'fo'
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 516, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 168, in extract
    return self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1249, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 887, in _decrypt_signature
    u'Automatic signature extraction failed: ' + tb, cause=e)
ExtractorError: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 883, in _decrypt_signature
    return func(s)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 449, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/bin/youtube-dl/youtube_dl/jsinterp.py", line 113, in resf
    res = self.interpret_statement(stmt, local_vars)
  File "/usr/bin/youtube-dl/youtube_dl/jsinterp.py", line 45, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/bin/youtube-dl/youtube_dl/jsinterp.py", line 58, in interpret_expression
    val = local_vars[m.group('in')]
KeyError: u'fo'
## I just updated by youtube-dl version.

youtube-dl --version
## 2014.07.11.3

This error only happens for some videos.
Please help or let me know if you have seen similar issues.

Thanks,

**Comment by sudarsun** [comment]
Upgrading to [2016.05.01](http://yt-dl.org/downloads/2016.05.01/) solved the problem for me today.
