### ISSUE TITLE
Can't download from TikTok (again)

### ISSUE THREAD

**Issue by ghost** [rg3/youtube-dl#32761]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2024.03.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.tiktok.com/@vloneari/video/7266211410852515105']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2024.03.28 [21792b88b] (single file build)
[debug] ** This version was built from the latest master code at https://github.com/ytdl-org/youtube-dl.
[debug] ** For support, visit the main site.
[debug] Python 3.4.4 (CPython AMD64 32bit) - Windows-10-10.0.19041 - OpenSSL 1.0.2d 9 Jul 2015
[debug] exe versions: ffmpeg 2024-03-20-git-e04c638f5f-full_build-www.gyan.dev, ffprobe 2024-03-20-git-e04c638f5f-full_build-www.gyan.dev
[debug] Proxy map: {}
[TikTok] Setting up session
[TikTok] 7266211410852515105: Downloading webpage
ERROR: Unable to extract data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "D:\a\ytdl-nightly\ytdl-nightly\youtube_dl\YoutubeDL.py", line 863, in wrapper
  File "D:\a\ytdl-nightly\ytdl-nightly\youtube_dl\YoutubeDL.py", line 959, in __extract_info
  File "D:\a\ytdl-nightly\ytdl-nightly\youtube_dl\extractor\common.py", line 571, in extract
  File "D:\a\ytdl-nightly\ytdl-nightly\youtube_dl\extractor\tiktok.py", line 112, in _real_extract
  File "D:\a\ytdl-nightly\ytdl-nightly\youtube_dl\extractor\common.py", line 1101, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

It seems TikTok has obfuscated the download process even further (according to discussions on similar older issues ([1](https://github.com/ytdl-org/youtube-dl/issues/20809), [2](https://github.com/ytdl-org/youtube-dl/issues/31150), etc) TikTok does this a lot). I have tried using the outright URL in the address bar and the share link, neither worked.

**Comment by dirkf** [comment]
Seems like all the significant _yt-dlp_ issues for TikTok are closed, so we should pull and adapt the latest version from there.

**Comment by dirkf** [comment]
And indeed:
```console
$ python -m youtube_dl -vF 'https://www.tiktok.com/@vloneari/video/7266211410852515105'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-vF', u'https://www.tiktok.com/@vloneari/video/7266211410852515105']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: 8cd66b76f
[debug] Python 2.7.15 (CPython i686 32bit) - Linux-6.1.0-18-686-pae-i686-with-debian-12.5 - OpenSSL 1.1.1a  20 Nov 2018 - glibc 2.1.3
[debug] exe versions: ffmpeg 5.1.4-0, ffprobe 5.1.4-0
[debug] Proxy map: {}
[debug] [TikTok] {u'iid': u'7351149742343391009', u'manifest_app_version': u'2023401020', u'app_version': u'34.1.2', u'app_name': u'musical_ly', u'aid': u'0'}
[TikTok] 7266211410852515105: Downloading video feed
[info] Available formats for 7266211410852515105:
format code              extension  resolution note
download_addr-0          mp4        720x1280   Download video, watermarked , h264, aac  , 2.29MiB
download_addr-1          mp4        720x1280   Download video, watermarked , h264, aac  , 2.29MiB
download_addr-2          mp4        720x1280   Download video, watermarked (API) , h264, aac  , 2.29MiB
h264_540p_1585157-0      mp4        576x576    Direct video 1585k , h264, aac  , 2.22MiB
h264_540p_1585157-1      mp4        576x576    Direct video 1585k , h264, aac  , 2.22MiB
h264_540p_1585157-2      mp4        576x576    Direct video (API) 1585k , h264, aac  , 2.22MiB
bytevc1_540p_513967-0    mp4        576x576    Direct video  513k , h265, aac  , 737.07KiB
bytevc1_540p_513967-1    mp4        576x576    Direct video  513k , h265, aac  , 737.07KiB
bytevc1_540p_513967-2    mp4        576x576    Direct video (API)  513k , h265, aac  , 737.07KiB
bytevc1_540p_404870-0    mp4        576x576    Playback video  404k , h265, aac  , 580.62KiB
bytevc1_540p_404870-1    mp4        576x576    Playback video  404k , h265, aac  , 580.62KiB
bytevc1_540p_404870-2    mp4        576x576    Playback video (API)  404k , h265, aac  , 580.62KiB
bytevc1_540p_358582-0    mp4        576x576    Playback video  358k , h265, aac  , 514.24KiB
bytevc1_540p_358582-1    mp4        576x576    Playback video  358k , h265, aac  , 514.24KiB
bytevc1_540p_358582-2    mp4        576x576    Playback video (API)  358k , h265, aac  , 514.24KiB
bytevc1_720p_646693-0    mp4        720x720    Playback video  646k , h265, aac  , 927.41KiB
bytevc1_720p_646693-1    mp4        720x720    Playback video  646k , h265, aac  , 927.41KiB
bytevc1_720p_646693-2    mp4        720x720    Playback video (API)  646k , h265, aac  , 927.41KiB
bytevc1_1080p_1035108-0  mp4        1080x1080  Playback video 1035k , h265, aac  , 1.45MiB
bytevc1_1080p_1035108-1  mp4        1080x1080  Playback video 1035k , h265, aac  , 1.45MiB
bytevc1_1080p_1035108-2  mp4        1080x1080  Playback video (API) 1035k , h265, aac  , 1.45MiB (best)
$ 
```

**Comment by idrinkandiknowthing** [comment]
I'm encountering this issue as well,

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-vF', 'https://www.tiktok.com/@vloneari/video/7266211410852515105']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python 3.9.5 (CPython aarch64 64bit) - Linux-6.5.11-linuxkit-aarch64-with-glibc2.31 - OpenSSL 1.1.1f  31 Mar 2020 - glibc 2.31
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7
[debug] Proxy map: {}
[TikTok] Setting up session
[TikTok] 7266211410852515105: Downloading webpage
ERROR: Unable to extract data; please report this issue on https://github.com/ytdl-org/youtube-dl/issues , using the appropriate issue template. Make sure you are using the latest version; see  https://github.com/ytdl-org/youtube-dl/#user-content-installation  on how to update. Be sure to call youtube-dl with the --verbose option and include the complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/youtube_dl/YoutubeDL.py", line 859, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/youtube_dl/YoutubeDL.py", line 955, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.9/dist-packages/youtube_dl/extractor/common.py", line 571, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.9/dist-packages/youtube_dl/extractor/tiktok.py", line 110, in _real_extract
    page_props = self._parse_json(self._search_regex(
  File "/usr/local/lib/python3.9/dist-packages/youtube_dl/extractor/common.py", line 1101, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract data; please report this issue on https://github.com/ytdl-org/youtube-dl/issues , using the appropriate issue template. Make sure you are using the latest version; see  https://github.com/ytdl-org/youtube-dl/#user-content-installation  on how to update. Be sure to call youtube-dl with the --verbose option and include the complete output.

**Comment by dirkf** [comment]
Looks like the back-port is almost ready to go:
```console
$ python -m youtube_dl -vF 'https://www.tiktok.com/@vloneari/video/7266211410852515105'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-vF', u'https://www.tiktok.com/@vloneari/video/7266211410852515105']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: 6bc98a17a
[debug] Python 2.7.15 (CPython i686 32bit) - Linux-6.1.0-18-686-pae-i686-with-debian-12.5 - OpenSSL 1.1.1a  20 Nov 2018 - glibc 2.1.3
[debug] exe versions: ffmpeg 5.1.4-0, ffprobe 5.1.4-0
[debug] Proxy map: {}
[debug] [TikTok] {u'iid': u'7351153174894626592', u'manifest_app_version': u'2023401020', u'app_version': u'34.1.2', u'app_name': u'musical_ly', u'aid': u'0'}
[TikTok] 7266211410852515105: Downloading video feed
[info] Available formats for 7266211410852515105:
format code              extension  resolution note
download_addr-0          mp4        720x1280   Download video, watermarked , h264, aac  , 2.29MiB
download_addr-1          mp4        720x1280   Download video, watermarked , h264, aac  , 2.29MiB
download_addr-2          mp4        720x1280   Download video, watermarked (API) , h264, aac  , 2.29MiB
h264_540p_1585157-0      mp4        576x576    Direct video 1585k , h264, aac  , 2.22MiB
h264_540p_1585157-1      mp4        576x576    Direct video 1585k , h264, aac  , 2.22MiB
h264_540p_1585157-2      mp4        576x576    Direct video (API) 1585k , h264, aac  , 2.22MiB
bytevc1_540p_513967-0    mp4        576x576    Direct video  513k , h265, aac  , 737.07KiB
bytevc1_540p_513967-1    mp4        576x576    Direct video  513k , h265, aac  , 737.07KiB
bytevc1_540p_513967-2    mp4        576x576    Direct video (API)  513k , h265, aac  , 737.07KiB
bytevc1_540p_404870-0    mp4        576x576    Playback video  404k , h265, aac  , 580.62KiB
bytevc1_540p_404870-1    mp4        576x576    Playback video  404k , h265, aac  , 580.62KiB
bytevc1_540p_404870-2    mp4        576x576    Playback video (API)  404k , h265, aac  , 580.62KiB
bytevc1_540p_358582-0    mp4        576x576    Playback video  358k , h265, aac  , 514.24KiB
bytevc1_540p_358582-1    mp4        576x576    Playback video  358k , h265, aac  , 514.24KiB
bytevc1_540p_358582-2    mp4        576x576    Playback video (API)  358k , h265, aac  , 514.24KiB
bytevc1_720p_646693-0    mp4        720x720    Playback video  646k , h265, aac  , 927.41KiB
bytevc1_720p_646693-1    mp4        720x720    Playback video  646k , h265, aac  , 927.41KiB
bytevc1_720p_646693-2    mp4        720x720    Playback video (API)  646k , h265, aac  , 927.41KiB
bytevc1_1080p_1035108-0  mp4        1080x1080  Playback video 1035k , h265, aac  , 1.45MiB
bytevc1_1080p_1035108-1  mp4        1080x1080  Playback video 1035k , h265, aac  , 1.45MiB
bytevc1_1080p_1035108-2  mp4        1080x1080  Playback video (API) 1035k , h265, aac  , 1.45MiB (best)
$ 
```
