### ISSUE TITLE
[Livestream] info_dict['url'] is None

### ISSUE THREAD

**Issue by epitron** [rg3/youtube-dl#3308]
Not sure what happened -- this was working yesterday!
```
$ youtube-dl -g http://new.livestream.com/accounts/686369/events/3195566
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/scripts/youtube-dl/__main__.py", line 18, in <module>
  File "/usr/scripts/youtube-dl/youtube_dl/__init__.py", line 859, in main
    
  File "/usr/scripts/youtube-dl/youtube_dl/__init__.py", line 849, in _real_main
    
  File "/usr/scripts/youtube-dl/youtube_dl/YoutubeDL.py", line 1052, in download
  File "/usr/scripts/youtube-dl/youtube_dl/YoutubeDL.py", line 527, in extract_info
  File "/usr/scripts/youtube-dl/youtube_dl/YoutubeDL.py", line 645, in process_ie_result
  File "/usr/scripts/youtube-dl/youtube_dl/YoutubeDL.py", line 564, in process_ie_result
  File "/usr/scripts/youtube-dl/youtube_dl/YoutubeDL.py", line 830, in process_video_result
  File "/usr/scripts/youtube-dl/youtube_dl/YoutubeDL.py", line 871, in process_info
TypeError: unsupported operand type(s) for +: 'NoneType' and 'unicode'
```

(It happens without the `-g` option as well.)

**Comment by jaimeMF** [comment]
It's working now for me, so I'm closing the issue. If you can reproduce the error with the last youtube-dl version, please comment here or open a new issue.
