### ISSUE TITLE
[youtube] unable to download video data: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by sg-s** [rg3/youtube-dl#3316]
Sorry if duplicate,

The full error message is this:

```

~$ 
[youtube] Setting language
[youtube] GHwyHyIuFhk: Downloading webpage
[youtube] GHwyHyIuFhk: Downloading video info webpage
[youtube] GHwyHyIuFhk: Extracting video information
[youtube] GHwyHyIuFhk: Encrypted signatures detected.
[youtube] GHwyHyIuFhk: Downloading js player vflqZIm5b
WARNING: Writing cache to u'/Users/[username]/.cache/youtube-dl/youtube-sigfuncs/js_vflqZIm5b_88.json' failed: Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 388, in _extract_signature_function
    cache_res = res(test_string)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 446, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 113, in resf
    res = self.interpret_statement(stmt, local_vars)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 45, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 58, in interpret_expression
    val = local_vars[m.group('in')]
KeyError: u'lo'

WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 878, in _decrypt_signature
    return func(s)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 446, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 113, in resf
    res = self.interpret_statement(stmt, local_vars)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 45, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 58, in interpret_expression
    val = local_vars[m.group('in')]
KeyError: u'lo'

WARNING: Warning: Falling back to static signature algorithm
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 878, in _decrypt_signature
    return func(s)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 446, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 113, in resf
    res = self.interpret_statement(stmt, local_vars)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 45, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 58, in interpret_expression
    val = local_vars[m.group('in')]
KeyError: u'lo'

WARNING: Warning: Falling back to static signature algorithm
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 878, in _decrypt_signature
    return func(s)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 446, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 113, in resf
    res = self.interpret_statement(stmt, local_vars)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 45, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 58, in interpret_expression
    val = local_vars[m.group('in')]
KeyError: u'lo'

WARNING: Warning: Falling back to static signature algorithm
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 878, in _decrypt_signature
    return func(s)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 446, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 113, in resf
    res = self.interpret_statement(stmt, local_vars)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 45, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 58, in interpret_expression
    val = local_vars[m.group('in')]
KeyError: u'lo'

WARNING: Warning: Falling back to static signature algorithm
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 878, in _decrypt_signature
    return func(s)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 446, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 113, in resf
    res = self.interpret_statement(stmt, local_vars)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 45, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 58, in interpret_expression
    val = local_vars[m.group('in')]
KeyError: u'lo'

WARNING: Warning: Falling back to static signature algorithm
[youtube] GHwyHyIuFhk: Downloading js player vflqZIm5b
WARNING: Writing cache to u'/Users/[username]/.cache/youtube-dl/youtube-sigfuncs/js_vflqZIm5b_82.json' failed: Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 388, in _extract_signature_function
    cache_res = res(test_string)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 446, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 113, in resf
    res = self.interpret_statement(stmt, local_vars)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 45, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 58, in interpret_expression
    val = local_vars[m.group('in')]
KeyError: u'lo'

WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 878, in _decrypt_signature
    return func(s)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 446, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 113, in resf
    res = self.interpret_statement(stmt, local_vars)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 45, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 58, in interpret_expression
    val = local_vars[m.group('in')]
KeyError: u'lo'

WARNING: Warning: Falling back to static signature algorithm
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 878, in _decrypt_signature
    return func(s)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 446, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 113, in resf
    res = self.interpret_statement(stmt, local_vars)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 45, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 58, in interpret_expression
    val = local_vars[m.group('in')]
KeyError: u'lo'

WARNING: Warning: Falling back to static signature algorithm
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 878, in _decrypt_signature
    return func(s)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 446, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 113, in resf
    res = self.interpret_statement(stmt, local_vars)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 45, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 58, in interpret_expression
    val = local_vars[m.group('in')]
KeyError: u'lo'

WARNING: Warning: Falling back to static signature algorithm
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 878, in _decrypt_signature
    return func(s)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 446, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 113, in resf
    res = self.interpret_statement(stmt, local_vars)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 45, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 58, in interpret_expression
    val = local_vars[m.group('in')]
KeyError: u'lo'

WARNING: Warning: Falling back to static signature algorithm
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 878, in _decrypt_signature
    return func(s)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 446, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 113, in resf
    res = self.interpret_statement(stmt, local_vars)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 45, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 58, in interpret_expression
    val = local_vars[m.group('in')]
KeyError: u'lo'

WARNING: Warning: Falling back to static signature algorithm
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 878, in _decrypt_signature
    return func(s)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 446, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 113, in resf
    res = self.interpret_statement(stmt, local_vars)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 45, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 58, in interpret_expression
    val = local_vars[m.group('in')]
KeyError: u'lo'

WARNING: Warning: Falling back to static signature algorithm
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 878, in _decrypt_signature
    return func(s)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 446, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 113, in resf
    res = self.interpret_statement(stmt, local_vars)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 45, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 58, in interpret_expression
    val = local_vars[m.group('in')]
KeyError: u'lo'

WARNING: Warning: Falling back to static signature algorithm
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 878, in _decrypt_signature
    return func(s)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 446, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 113, in resf
    res = self.interpret_statement(stmt, local_vars)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 45, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 58, in interpret_expression
    val = local_vars[m.group('in')]
KeyError: u'lo'

WARNING: Warning: Falling back to static signature algorithm
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 878, in _decrypt_signature
    return func(s)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 446, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 113, in resf
    res = self.interpret_statement(stmt, local_vars)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 45, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 58, in interpret_expression
    val = local_vars[m.group('in')]
KeyError: u'lo'

WARNING: Warning: Falling back to static signature algorithm
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 878, in _decrypt_signature
    return func(s)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 446, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 113, in resf
    res = self.interpret_statement(stmt, local_vars)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 45, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 58, in interpret_expression
    val = local_vars[m.group('in')]
KeyError: u'lo'

WARNING: Warning: Falling back to static signature algorithm
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 878, in _decrypt_signature
    return func(s)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 446, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 113, in resf
    res = self.interpret_statement(stmt, local_vars)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 45, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 58, in interpret_expression
    val = local_vars[m.group('in')]
KeyError: u'lo'

WARNING: Warning: Falling back to static signature algorithm
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 878, in _decrypt_signature
    return func(s)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 446, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 113, in resf
    res = self.interpret_statement(stmt, local_vars)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 45, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 58, in interpret_expression
    val = local_vars[m.group('in')]
KeyError: u'lo'

WARNING: Warning: Falling back to static signature algorithm
ERROR: unable to download video data: HTTP Error 403: Forbidden

```

**Comment by chernikalxde** [comment]
Hey !!
Can't update to 2014.06.19 or higher to solve the issue =( 
My system says "youtube-dl is up-to-date (2020.03.24)"
Is 2014.06.19 version available for x32 architecture machine on Ubuntu 16.04 with LXDE ?
