### ISSUE TITLE
AttributeError while downloading (transcoding?) from Livestream.com

### ISSUE THREAD

**Issue by joepie91** [rg3/youtube-dl#3318]
The following happened:

```
[http @ 0x1e2b2a0] HTTP error 404 Not Foundtime=316.85 bitrate=2126.1kbits/s    
http://api.new.livestream.com/accounts/9197973/events/3195646/videos/57095862.m3u8?dw=0&hdnea=st=1405970094~exp=1405970994~acl=/i/9197973_1198167_1cd4ee13_1@43651/*~hmac=f45e90d8234b39a08570cbeb699ffcfc836324ae7b40ce168f5eb61139b35a26: Input/output error
frame= 9556 fps=104 q=-1.0 Lsize=   83452kB time=319.95 bitrate=2136.7kbits/s    
video:78064kB audio:5094kB global headers:0kB muxing overhead 0.353446%
[avconv] 85454550 bytes
[download] Downloading video #2 of 10
Traceback (most recent call last):
  File "/usr/bin/youtube-dl", line 9, in <module>
    load_entry_point('youtube-dl==2014.07.21', 'console_scripts', 'youtube-dl')()
  File "/usr/lib/python2.7/site-packages/youtube_dl/__init__.py", line 857, in main
    _real_main(argv)
  File "/usr/lib/python2.7/site-packages/youtube_dl/__init__.py", line 847, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 1052, in download
    self.extract_info(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 527, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 645, in process_ie_result
    extra_info=extra)
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 564, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 770, in process_video_result
    format['ext'] = determine_ext(format['url']).lower()
  File "/usr/lib/python2.7/site-packages/youtube_dl/utils.py", line 855, in determine_ext
    guess = url.partition(u'?')[0].rpartition(u'.')[2]
AttributeError: 'NoneType' object has no attribute 'partition'
```

Command run:

```
youtube-dl http://new.livestream.com/internetsociety2/hopex2
```

Latest version, installed from pip minutes ago. `youtube-dl` failed to continue after this uncaught exception, breaking the download of the remainder of the channel. I can reproduce the problem reliably; it always breaks on this video.

**Comment by jaimeMF** [comment]
It's working now for me, so I'm closing the issue. If you can reproduce the error with the last youtube-dl version, please comment here or open a new issue.
