### ISSUE TITLE
Add support for wabcradio.com (was: Unsupported URL)

### ISSUE THREAD

**Issue by gasgas4** [rg3/youtube-dl#3345]
debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.wabcradio.com/common/more.php?m=58&ts=1406157603&article=96F2442E12B911E4B51EFEFDADE6840A&mode=2']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.06.26
[debug] Python version 2.7.5 - Darwin-13.3.0-x86_64-i386-64bit
[debug] Proxy map: {}
[generic] more: Requesting header
WARNING: Falling back on generic information extractor.
[generic] more: Downloading webpage
[generic] more: Extracting information
ERROR: Unsupported URL: http://www.wabcradio.com/common/more.php?m=58&ts=1406157603&article=96F2442E12B911E4B51EFEFDADE6840A&mode=2; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 451, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1406, in parse_xml
    return xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 25, column 15
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 516, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 167, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 741, in _real_extract
    raise ExtractorError('Unsupported URL: %s' % url)
ExtractorError: Unsupported URL: http://www.wabcradio.com/common/more.php?m=58&ts=1406157603&article=96F2442E12B911E4B51EFEFDADE6840A&mode=2; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by dstftw** [comment]
>www.wabcradio.com - Access Denied
