### ISSUE TITLE
Add support for WCJ

### ISSUE THREAD

**Issue by gptg** [rg3/youtube-dl#3398]
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--print-traffic', '-v', 'http://www.webcamjackers.com/video/oh-my-i-like-where-this-is-going-1509.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.07.25.1
[debug] Python version 2.7.5 - Darwin-13.3.0-x86_64-i386-64bit
[debug] Proxy map: {}
[generic] oh-my-i-like-where-this-is-going-1509: Requesting header
WARNING: Falling back on generic information extractor.
[generic] oh-my-i-like-where-this-is-going-1509: Downloading webpage
send: u'GET /video/oh-my-i-like-where-this-is-going-1509.html HTTP/1.1\r\nHost: www.webcamjackers.com\r\nAccept-Language: en-us,en;q=0.5\r\nAccept-Encoding: gzip, deflate\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nUser-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20100101 Firefox/10.0 (Chrome)\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nConnection: close\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Tue, 29 Jul 2014 22:20:49 GMT
header: Server: Apache/2.2.3 (CentOS)
header: X-Powered-By: PHP/5.3.3
header: Set-Cookie: PHPSESSID=biu6ur9vn24su4i5glenel1lp6; path=/
header: Expires: Thu, 19 Nov 1981 08:52:00 GMT
header: Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
header: Pragma: no-cache
header: Connection: close
header: Transfer-Encoding: chunked
header: Content-Type: text/html; charset: iso-8859-1; charset=utf-8
[generic] oh-my-i-like-where-this-is-going-1509: Extracting information
ERROR: Unsupported URL: http://www.webcamjackers.com/video/oh-my-i-like-where-this-is-going-1509.html; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 456, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1418, in parse_xml
    return xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 195, column 92
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 516, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 169, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 751, in _real_extract
    raise ExtractorError('Unsupported URL: %s' % url)
ExtractorError: Unsupported URL: http://www.webcamjackers.com/video/oh-my-i-like-where-this-is-going-1509.html; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
```

**Comment by dstftw** [comment]
Works fine with latest version (2016.05.21.2).
