### ISSUE TITLE
Youtube video download fails with "AttributeError: 'NoneType' object has no attribute 'group'"

### ISSUE THREAD

**Issue by kostaz** [rg3/youtube-dl#3417]
## Issue

Tried to download Etherium youtube video using the below command:

```
    $ youtube-dl https://www.youtube.com/watch?v=GJGIeSCgskc&feature=youtu.be
```

Download fails with the below error message:

```
    "unable to download video data: HTTP Error 403: Forbidden"
```
## The setup

Ubuntu 14.04 64-bit

```
$ cat /etc/issue
Ubuntu 14.04.1 LTS \n \l

$ uname -a
Linux kostaz-HP-Pavilion-15-Notebook-PC 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```
## Version

```
$ youtube-dl --version
2014.02.17
```
## Full output

```
$ youtube-dl "https://www.youtube.com/watch?v=GJGIeSCgskc&feature=youtu.be"
[youtube] Setting language
[youtube] GJGIeSCgskc: Downloading webpage
[youtube] GJGIeSCgskc: Downloading video info webpage
[youtube] GJGIeSCgskc: Extracting video information
[youtube] GJGIeSCgskc: Encrypted signatures detected.
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 957, in _decrypt_signature
    video_id, player_url, len(s)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 331, in _extract_signature_function
    player_type = id_m.group('ext')
AttributeError: 'NoneType' object has no attribute 'group'

WARNING: Warning: Falling back to static signature algorithm
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 957, in _decrypt_signature
    video_id, player_url, len(s)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 331, in _extract_signature_function
    player_type = id_m.group('ext')
AttributeError: 'NoneType' object has no attribute 'group'

WARNING: Warning: Falling back to static signature algorithm
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 957, in _decrypt_signature
    video_id, player_url, len(s)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 331, in _extract_signature_function
    player_type = id_m.group('ext')
AttributeError: 'NoneType' object has no attribute 'group'

WARNING: Warning: Falling back to static signature algorithm
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 957, in _decrypt_signature
    video_id, player_url, len(s)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 331, in _extract_signature_function
    player_type = id_m.group('ext')
AttributeError: 'NoneType' object has no attribute 'group'

WARNING: Warning: Falling back to static signature algorithm
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 957, in _decrypt_signature
    video_id, player_url, len(s)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 331, in _extract_signature_function
    player_type = id_m.group('ext')
AttributeError: 'NoneType' object has no attribute 'group'

WARNING: Warning: Falling back to static signature algorithm
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 957, in _decrypt_signature
    video_id, player_url, len(s)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 331, in _extract_signature_function
    player_type = id_m.group('ext')
AttributeError: 'NoneType' object has no attribute 'group'

WARNING: Warning: Falling back to static signature algorithm
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 957, in _decrypt_signature
    video_id, player_url, len(s)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 331, in _extract_signature_function
    player_type = id_m.group('ext')
AttributeError: 'NoneType' object has no attribute 'group'

WARNING: Warning: Falling back to static signature algorithm
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 957, in _decrypt_signature
    video_id, player_url, len(s)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 331, in _extract_signature_function
    player_type = id_m.group('ext')
AttributeError: 'NoneType' object has no attribute 'group'

WARNING: Warning: Falling back to static signature algorithm
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 957, in _decrypt_signature
    video_id, player_url, len(s)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 331, in _extract_signature_function
    player_type = id_m.group('ext')
AttributeError: 'NoneType' object has no attribute 'group'

WARNING: Warning: Falling back to static signature algorithm
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 957, in _decrypt_signature
    video_id, player_url, len(s)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 331, in _extract_signature_function
    player_type = id_m.group('ext')
AttributeError: 'NoneType' object has no attribute 'group'

WARNING: Warning: Falling back to static signature algorithm
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 957, in _decrypt_signature
    video_id, player_url, len(s)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 331, in _extract_signature_function
    player_type = id_m.group('ext')
AttributeError: 'NoneType' object has no attribute 'group'

WARNING: Warning: Falling back to static signature algorithm
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 957, in _decrypt_signature
    video_id, player_url, len(s)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 331, in _extract_signature_function
    player_type = id_m.group('ext')
AttributeError: 'NoneType' object has no attribute 'group'

WARNING: Warning: Falling back to static signature algorithm
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 957, in _decrypt_signature
    video_id, player_url, len(s)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 331, in _extract_signature_function
    player_type = id_m.group('ext')
AttributeError: 'NoneType' object has no attribute 'group'

WARNING: Warning: Falling back to static signature algorithm
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 957, in _decrypt_signature
    video_id, player_url, len(s)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 331, in _extract_signature_function
    player_type = id_m.group('ext')
AttributeError: 'NoneType' object has no attribute 'group'

WARNING: Warning: Falling back to static signature algorithm
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 957, in _decrypt_signature
    video_id, player_url, len(s)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 331, in _extract_signature_function
    player_type = id_m.group('ext')
AttributeError: 'NoneType' object has no attribute 'group'

WARNING: Warning: Falling back to static signature algorithm
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 957, in _decrypt_signature
    video_id, player_url, len(s)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 331, in _extract_signature_function
    player_type = id_m.group('ext')
AttributeError: 'NoneType' object has no attribute 'group'

WARNING: Warning: Falling back to static signature algorithm
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 957, in _decrypt_signature
    video_id, player_url, len(s)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 331, in _extract_signature_function
    player_type = id_m.group('ext')
AttributeError: 'NoneType' object has no attribute 'group'

WARNING: Warning: Falling back to static signature algorithm
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 957, in _decrypt_signature
    video_id, player_url, len(s)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 331, in _extract_signature_function
    player_type = id_m.group('ext')
AttributeError: 'NoneType' object has no attribute 'group'

WARNING: Warning: Falling back to static signature algorithm
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 957, in _decrypt_signature
    video_id, player_url, len(s)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 331, in _extract_signature_function
    player_type = id_m.group('ext')
AttributeError: 'NoneType' object has no attribute 'group'

WARNING: Warning: Falling back to static signature algorithm
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 957, in _decrypt_signature
    video_id, player_url, len(s)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 331, in _extract_signature_function
    player_type = id_m.group('ext')
AttributeError: 'NoneType' object has no attribute 'group'

WARNING: Warning: Falling back to static signature algorithm
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 957, in _decrypt_signature
    video_id, player_url, len(s)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 331, in _extract_signature_function
    player_type = id_m.group('ext')
AttributeError: 'NoneType' object has no attribute 'group'

WARNING: Warning: Falling back to static signature algorithm
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 957, in _decrypt_signature
    video_id, player_url, len(s)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 331, in _extract_signature_function
    player_type = id_m.group('ext')
AttributeError: 'NoneType' object has no attribute 'group'

WARNING: Warning: Falling back to static signature algorithm
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 957, in _decrypt_signature
    video_id, player_url, len(s)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 331, in _extract_signature_function
    player_type = id_m.group('ext')
AttributeError: 'NoneType' object has no attribute 'group'

WARNING: Warning: Falling back to static signature algorithm
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 957, in _decrypt_signature
    video_id, player_url, len(s)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 331, in _extract_signature_function
    player_type = id_m.group('ext')
AttributeError: 'NoneType' object has no attribute 'group'

WARNING: Warning: Falling back to static signature algorithm
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 957, in _decrypt_signature
    video_id, player_url, len(s)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 331, in _extract_signature_function
    player_type = id_m.group('ext')
AttributeError: 'NoneType' object has no attribute 'group'

WARNING: Warning: Falling back to static signature algorithm
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 957, in _decrypt_signature
    video_id, player_url, len(s)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 331, in _extract_signature_function
    player_type = id_m.group('ext')
AttributeError: 'NoneType' object has no attribute 'group'

WARNING: Warning: Falling back to static signature algorithm
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 957, in _decrypt_signature
    video_id, player_url, len(s)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 331, in _extract_signature_function
    player_type = id_m.group('ext')
AttributeError: 'NoneType' object has no attribute 'group'

WARNING: Warning: Falling back to static signature algorithm
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 957, in _decrypt_signature
    video_id, player_url, len(s)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 331, in _extract_signature_function
    player_type = id_m.group('ext')
AttributeError: 'NoneType' object has no attribute 'group'

WARNING: Warning: Falling back to static signature algorithm
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 957, in _decrypt_signature
    video_id, player_url, len(s)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 331, in _extract_signature_function
    player_type = id_m.group('ext')
AttributeError: 'NoneType' object has no attribute 'group'

WARNING: Warning: Falling back to static signature algorithm
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 957, in _decrypt_signature
    video_id, player_url, len(s)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 331, in _extract_signature_function
    player_type = id_m.group('ext')
AttributeError: 'NoneType' object has no attribute 'group'

WARNING: Warning: Falling back to static signature algorithm
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 957, in _decrypt_signature
    video_id, player_url, len(s)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 331, in _extract_signature_function
    player_type = id_m.group('ext')
AttributeError: 'NoneType' object has no attribute 'group'

WARNING: Warning: Falling back to static signature algorithm
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 957, in _decrypt_signature
    video_id, player_url, len(s)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 331, in _extract_signature_function
    player_type = id_m.group('ext')
AttributeError: 'NoneType' object has no attribute 'group'

WARNING: Warning: Falling back to static signature algorithm
ERROR: unable to download video data: HTTP Error 403: Forbidden
```

**Comment by JeffersonEmanuel** [comment]
Thanks phihag this really helped!!

**Comment by raikeiji** [comment]
phihahg, it so much help. Big thanks :+1:
