### ISSUE TITLE
msnbc failing

### ISSUE THREAD

**Issue by warbear** [rg3/youtube-dl#3424]
>youtube-dl -v http://www.msnbc.com/all-in-with-chris-hayes/watch/the-chaotic-gop-immigration-vote-314487875924
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.msnbc.com/all-in-with-chris-hayes/watch/the-chaotic-gop-immigration-vote-314487875924']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2014.08.02.1
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] Proxy map: {}
[generic] the-chaotic-gop-immigration-vote-314487875924: Requesting header
WARNING: Falling back on generic information extractor.
[generic] the-chaotic-gop-immigration-vote-314487875924: Downloading webpage
[generic] the-chaotic-gop-immigration-vote-314487875924: Extracting information
[debug] Invoking downloader on u'http://www.msnbc.com/all-in-with-chris-hayes/watch/the-chaotic-gop-immigration-vote-314487875924'
[download] Destination: The chaotic GOP immigration vote _ MSNBC-the-chaotic-gop-immigration-vote-314487875924.unknown_video
[download] 100% of N/A in 00:00

**Comment by yan12125** [comment]
MSNBC.com will be support in the next version. Thanks for the report.

**Comment by sporkman** [comment]
Here's a sample of MSNBC failing:

https://www.msnbc.com/rachel-maddow/watch/sanders-deeply-satisfied-to-see-his-2016-ideas-in-2020-candidates-63630405955?cid=sm_npd_ms_tw_ma

`frankentosh:~ spork$ youtube-dl https://www.msnbc.com/rachel-maddow/watch/sanders-deeply-satisfied-to-see-his-2016-ideas-in-2020-candidates-63630405955?cid=sm_npd_ms_tw_ma
[ThePlatformFeed] 63630405955: Downloading JSON metadata
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 474, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 464, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2008, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 807, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 873, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/theplatform.py", line 411, in _real_extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/theplatform.py", line 345, in _extract_feed_info
IndexError: list index out of range
frankentosh:~ spork$ which youtube-dl
/usr/local/bin/youtube-dl
frankentosh:~ spork$ youtube-dl --version

2019.07.12
frankentosh:~ spork$
`
