### ISSUE TITLE
Certificate error

### ISSUE THREAD

**Issue by Jofsey** [rg3/youtube-dl#3435]
I'm trying to list available formats for live stream but get the following exception.
```
$ youtube-dl -F http://www.youtube.com/watch?v=SwrKzkRUlaw                                                                                                                             
[youtube] Setting language
[youtube] SwrKzkRUlaw: Downloading webpage
[youtube] SwrKzkRUlaw: Downloading video info webpage
[youtube] SwrKzkRUlaw: Extracting video information
[youtube] SwrKzkRUlaw: Downloading formats manifest
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/youtube-dl/__main__.py", line 18, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 889, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 879, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1052, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 516, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 170, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 868, in _real_extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 579, in _extract_from_m3u8
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 283, in _download_webpage
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 223, in _download_webpage_handle
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 203, in _request_webpage
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1231, in urlopen
  File "/usr/lib/python3.4/urllib/request.py", line 455, in open
    response = self._open(req, data)
  File "/usr/lib/python3.4/urllib/request.py", line 473, in _open
    '_open', req)
  File "/usr/lib/python3.4/urllib/request.py", line 433, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 1230, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.4/urllib/request.py", line 1189, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.4/http/client.py", line 1090, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.4/http/client.py", line 1128, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.4/http/client.py", line 1086, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.4/http/client.py", line 924, in _send_output
    self.send(msg)
  File "/usr/lib/python3.4/http/client.py", line 859, in send
    self.connect()
  File "/usr/lib/python3.4/http/client.py", line 1233, in connect
    ssl.match_hostname(self.sock.getpeercert(), server_hostname)
  File "/usr/lib/python3.4/ssl.py", line 288, in match_hostname
    % (hostname, dnsnames[0]))
ssl.CertificateError: hostname 'manifest.googlevideo.com' doesn't match 'www.google.com'
```

**Comment by dstftw** [comment]
This live event has ended.
