### ISSUE TITLE
dmax.de support

### ISSUE THREAD

**Issue by BCallifornia** [rg3/youtube-dl#3437]
download videos from dmax.de would be a nice to have.

[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.dmax.de/programme/amish-mafia/videos/amish-mafia-der-kutschen-crash/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.08.02.1
[debug] Python version 2.7.3 - Linux-3.10.9-xxxx-grs-ipv6-64-x86_64-with-Ubuntu-12.04-precise
[debug] Proxy map: {}
[generic] amish-mafia-der-kutschen-crash: Requesting header
WARNING: Falling back on generic information extractor.
[generic] amish-mafia-der-kutschen-crash: Downloading webpage
[generic] amish-mafia-der-kutschen-crash: Extracting information
ERROR: Unsupported URL: http://www.dmax.de/programme/amish-mafia/videos/amish-mafia-der-kutschen-crash/; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 457, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1420, in parse_xml
    return xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1301, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1643, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1507, in _raiseerror
    raise err
ParseError: undefined entity: line 25, column 97
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 516, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 170, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 752, in _real_extract
    raise ExtractorError('Unsupported URL: %s' % url)
ExtractorError: Unsupported URL: http://www.dmax.de/programme/amish-mafia/videos/amish-mafia-der-kutschen-crash/; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by remitamine** [comment]
works with the latest version.
