### ISSUE TITLE
ytwatchlater Error

### ISSUE THREAD

**Issue by rtvance** [rg3/youtube-dl#3463]
I am getting the same error in Windows 7 and Ubuntu Username/Password removed for security reasons. 
I am able to download individual URLs. I am up to date as of a reinstall of yt-dl this morning. 

youtube-dl -u *** -p ** :ytwatchlater
-v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-u', '<PRIVATE>', '-p', '<PRIVATE>', ':ytwatchlater
', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2014.08.05
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] Proxy map: {}
[youtube:watch_later] Downloading login page
[youtube:watch_later] Logging in
[youtube:watch_later] watch_later feed: Downloading page 1
ERROR: Failed to download JSON; please report this issue on https://yt-dl.org/bu
g . Be sure to call youtube-dl with the --verbose flag and include its complete
output. Make sure you are using the latest version; type  youtube-dl -U  to upda
te.
Traceback (most recent call last):
  File "youtube_dl\extractor\common.pyo", line 314, in _download_json
  File "json\__init__.pyo", line 338, in loads
  File "json\decoder.pyo", line 366, in decode
  File "json\decoder.pyo", line 382, in raw_decode
ValueError: Invalid \escape: line 1 column 386580 (char 386579)
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 516, in extract_info
  File "youtube_dl\extractor\common.pyo", line 170, in extract
  File "youtube_dl\extractor\youtube.pyo", line 1337, in _real_extract
  File "youtube_dl\extractor\common.pyo", line 316, in _download_json
ExtractorError: Failed to download JSON; please report this issue on https://yt-
dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its
complete output. Make sure you are using the latest version; type  youtube-dl -U
  to update.

**Comment by dstftw** [comment]
Will be fixed in the next version.
