### ISSUE TITLE
lincolncenter.org

### ISSUE THREAD

**Issue by ArfArf** [rg3/youtube-dl#3467]
youtube-dl --verbose http://watch.lincolncenter.org/pages/emmylou-harris-and-rodney-crowell
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://watch.lincolncenter.org/pages/emmylou-harris-and-rodney-crowell']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.08.05
[debug] Python version 2.7.5 - Darwin-13.3.0-x86_64-i386-64bit
[debug] Proxy map: {}
[generic] emmylou-harris-and-rodney-crowell: Requesting header
WARNING: Falling back on generic information extractor.
[generic] emmylou-harris-and-rodney-crowell: Downloading webpage
[generic] emmylou-harris-and-rodney-crowell: Extracting information
ERROR: Unsupported URL: http://watch.lincolncenter.org/pages/emmylou-harris-and-rodney-crowell; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 457, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1420, in parse_xml
    return xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 71, column 29
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 516, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 170, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 752, in _real_extract
    raise ExtractorError('Unsupported URL: %s' % url)
ExtractorError: Unsupported URL: http://watch.lincolncenter.org/pages/emmylou-harris-and-rodney-crowell; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

Thanks!

**Comment by TRox1972** [comment]
Provided URL not working. All videos on the site seems to be either YouTube-embeds or livestream-embeds. Should this be closed?

Example YouTube-embed: http://www.lincolncenter.org/video/571781ca548b50e518ad2715
Example livestream-embed: http://www.lincolncenter.org/video/57d9683a0299c9ef449e779d

**Comment by yan12125** [comment]
Thanks @TRox1972.
