### ISSUE TITLE
[site-support-request] howstuffworks.com

### ISSUE THREAD

**Issue by BonzoFestoon** [rg3/youtube-dl#3500]
Returns URLError (11004) in getaddrinfo
```
D:\youtube-dl>youtube-dl.exe --update
youtube-dl is up-to-date (2014.08.10)

D:\youtube-dl>youtube-dl.exe --verbose http://adventure.howstuffworks.com/5266-cool-jobs-iditarod-musher-video.htm
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://adventure.howstuffworks.com/5266-cool-jobs-iditarod-musher-video.htm']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2014.08.10
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] Proxy map: {}
[generic] 5266-cool-jobs-iditarod-musher-video: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 5266-cool-jobs-iditarod-musher-video: Downloading webpage
[generic] 5266-cool-jobs-iditarod-musher-video: Extracting information
[debug] Invoking downloader on u'http://video.player.howstuffworks.com/swf/video-asset-page-player.swf?_playerApplicatio
rk=hsw&_staticDomain=s.hswstatic.com'
ERROR: unable to download video data: <urlopen error [Errno 11004] getaddrinfo failed>
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 1022, in process_info
  File "youtube_dl\YoutubeDL.pyo", line 998, in dl
  File "youtube_dl\downloader\common.pyo", line 291, in download
  File "youtube_dl\downloader\http.pyo", line 58, in real_download
  File "youtube_dl\YoutubeDL.pyo", line 1231, in urlopen
  File "urllib2.pyo", line 404, in open
  File "urllib2.pyo", line 422, in _open
  File "urllib2.pyo", line 382, in _call_chain
  File "urllib2.pyo", line 1214, in http_open
  File "urllib2.pyo", line 1184, in do_open
URLError: <urlopen error [Errno 11004] getaddrinfo failed>
```

**Comment by naglis** [comment]
howstuffworks.com has been supported since youtube-dl 2014.08.21. Refer to [our FAQ](https://yt-dl.org/update) if you need help updating.
