### ISSUE TITLE
[site-support-request] redflagnews.com

### ISSUE THREAD

**Issue by BonzoFestoon** [rg3/youtube-dl#3501]
```
D:\youtube-dl>youtube-dl.exe --update
youtube-dl is up-to-date (2014.08.10)

D:\youtube-dl>youtube-dl.exe --verbose http://www.redflagnews.com/headlines/nbc-news-crew-threatened-with-arrest-for-filming-a-fema-camp-you-will-be-s
tunned-by-what-the-officer-says-to-the-reporter
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.redflagnews.com/headlines/nbc-news-crew-threatened-with-arrest-for-filming-a-fema-camp-you-will-b
e-stunned-by-what-the-officer-says-to-the-reporter']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2014.08.10
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] Proxy map: {}
[generic] nbc-news-crew-threatened-with-arrest-for-filming-a-fema-camp-you-will-be-stunned-by-what-the-officer-says-to-the-reporter: Requesting header

WARNING: Falling back on generic information extractor.
[generic] nbc-news-crew-threatened-with-arrest-for-filming-a-fema-camp-you-will-be-stunned-by-what-the-officer-says-to-the-reporter: Downloading webpa
ge
[generic] nbc-news-crew-threatened-with-arrest-for-filming-a-fema-camp-you-will-be-stunned-by-what-the-officer-says-to-the-reporter: Extracting inform
ation
ERROR: Unsupported URL: http://www.redflagnews.com/headlines/nbc-news-crew-threatened-with-arrest-for-filming-a-fema-camp-you-will-be-stunned-by-what-
the-officer-says-to-the-reporter; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include i
ts complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "youtube_dl\extractor\generic.pyo", line 457, in _real_extract
  File "youtube_dl\utils.pyo", line 1426, in parse_xml
  File "xml\etree\ElementTree.pyo", line 1300, in XML
  File "xml\etree\ElementTree.pyo", line 1642, in feed
  File "xml\etree\ElementTree.pyo", line 1506, in _raiseerror
ParseError: syntax error: line 1, column 0
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 516, in extract_info
  File "youtube_dl\extractor\common.pyo", line 170, in extract
  File "youtube_dl\extractor\generic.pyo", line 752, in _real_extract
ExtractorError: Unsupported URL: http://www.redflagnews.com/headlines/nbc-news-crew-threatened-with-arrest-for-filming-a-fema-camp-you-will-be-stunned
-by-what-the-officer-says-to-the-reporter; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and
include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
```

**Comment by TRox1972** [comment]
YouTube embed. Still doesn't work, though.
