### ISSUE TITLE
http://videopediaworld.com causes struct.error: unpack requires a string argument of length 4

### ISSUE THREAD

**Issue by BonzoFestoon** [rg3/youtube-dl#3502]
```
D:\youtube-dl>youtube-dl.exe --update
youtube-dl is up-to-date (2014.08.10)

D:\youtube-dl>youtube-dl.exe --verbose http://videopediaworld.com/video/23478/Greece-The-Geography-and-History-of-Greece
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://videopediaworld.com/video/23478/Greece-The-Geography-and-History-of-Greece']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2014.08.10
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] Proxy map: {}
[generic] Greece-The-Geography-and-History-of-Greece: Requesting header
WARNING: Falling back on generic information extractor.
[generic] Greece-The-Geography-and-History-of-Greece: Downloading webpage
Traceback (most recent call last):
  File "__main__.py", line 18, in <module>
  File "youtube_dl\__init__.pyo", line 892, in main
  File "youtube_dl\__init__.pyo", line 882, in _real_main
  File "youtube_dl\YoutubeDL.pyo", line 1052, in download
  File "youtube_dl\YoutubeDL.pyo", line 516, in extract_info
  File "youtube_dl\extractor\common.pyo", line 170, in extract
  File "youtube_dl\extractor\generic.pyo", line 447, in _real_extract
  File "youtube_dl\extractor\common.pyo", line 283, in _download_webpage
  File "youtube_dl\extractor\common.pyo", line 223, in _download_webpage_handle
  File "youtube_dl\extractor\common.pyo", line 203, in _request_webpage
  File "youtube_dl\YoutubeDL.pyo", line 1231, in urlopen
  File "urllib2.pyo", line 410, in open
  File "youtube_dl\utils.pyo", line 759, in http_response
  File "gzip.pyo", line 254, in read
  File "gzip.pyo", line 325, in _read
  File "gzip.pyo", line 344, in _read_eof
  File "gzip.pyo", line 25, in read32
struct.error: unpack requires a string argument of length 4
```

**Comment by dstftw** [comment]
videopediaworld.com is down.
