### ISSUE TITLE
Cannot download gamespot video

### ISSUE THREAD

**Issue by shakeyourbunny** [rg3/youtube-dl#3517]
Video URL: http://www.gamespot.com/videos/wow-warlords-of-draenor-cinematic-and-street-date-/2300-6420659/

$ youtube-dl -U
youtube-dl is up-to-date (2014.08.10)

$ youtube-dl --verbose http://www.gamespot.com/videos/wow-warlords-of-draenor-cinematic-and-street-date-/2300-6420659/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.gamespot.com/videos/wow-warlords-of-draenor-cinematic-and-street-date-/2300-6420659/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.08.10
[debug] Python version 2.7.3 - Linux-3.2.0-4-686-pae-i686-with-debian-7.6
[debug] Proxy map: {}
[GameSpot] 6420659: Downloading webpage
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/pulaski/bin/youtube-dl/__main__.py", line 18, in <module>
  File "/home/pulaski/bin/youtube-dl/youtube_dl/__init__.py", line 892, in main
  File "/home/pulaski/bin/youtube-dl/youtube_dl/__init__.py", line 882, in _real_main
  File "/home/pulaski/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1052, in download
  File "/home/pulaski/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 516, in extract_info
  File "/home/pulaski/bin/youtube-dl/youtube_dl/extractor/common.py", line 170, in extract
  File "/home/pulaski/bin/youtube-dl/youtube_dl/extractor/gamespot.py", line 37, in _real_extract
KeyError: u'f4m_stream'

$ uname -a
Linux debby 3.2.0-4-686-pae #1 SMP Debian 3.2.60-1+deb7u3 i686 GNU/Linux

$ python --version
Python 2.7.3

please help :-)

**Comment by luizdelducca** [comment]
http://www.getspot.tk/?url=http://www.gamespot.com/videos/wow-warlords-of-draenor-cinematic-and-street-date-/2300-6420659/

**Comment by jaimeMF** [comment]
I'm closing the issue. If you get the error again, please comment here or open a new issue.

@luizdelducca This is the bug tracker for youtube-dl, please don't post links to other tools when youtube-dl can download the video without any problem.
