### ISSUE TITLE
Unsupported url -- https://accounts.coursera.org/signin?course_id=...

### ISSUE THREAD

**Issue by Twangist** [rg3/youtube-dl#3559]
I tried to download videos of a coursera course I'm enrolled in, first using:
`youtube-dl -s --get-filename -u <REDACTED> -p <REDACTED>  --verbose https://class.coursera.org/ml-006/lecture`
to check what would be downloaded. However, this produced an `ERROR: Unsupported URL...` and `please report this issue on https://yt-dl.org/bug`, so I'm doing so.
Here's the complete output youtube-dl output:

> [debug] System config: []
> [debug] User config: []
> [debug] Command-line args: ['-s', '--get-filename', '-u', '<PRIVATE>', '-p', '<PRIVATE>', '--verbose', 'https://class.coursera.org/ml-006/lecture']
> [debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
> [debug] youtube-dl version 2014.08.10
> [debug] Python version 3.4.1 - Darwin-11.4.0-x86_64-i386-64bit
> [debug] Proxy map: {}
> WARNING: Falling back on generic information extractor.
> ERROR: Unsupported URL: https://accounts.coursera.org/signin?course_id=972303&r=https%3A%2F%2Fclass.coursera.org%2Fml-006%2Flecture&user_action=class&topic_name=Machine%20Learning; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
> Traceback (most recent call last):
>  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 516, in extract_info
>     ie_result = ie.extract(url)
>  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 170, in extract
>     return self._real_extract(url)
>  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 752, in _real_extract
>     raise ExtractorError('Unsupported URL: %s' % url)
> youtube_dl.utils.ExtractorError: Unsupported URL: https://accounts.coursera.org/signin?course_id=972303&r=https%3A%2F%2Fclass.coursera.org%2Fml-006%2Flecture&user_action=class&topic_name=Machine%20Learning; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by jvschiavo** [comment]
It has passed 6 years. Has anyone looked into it since then?

**Comment by fharper** [comment]
I didn't try it, but I saw https://github.com/coursera-dl/coursera-dl that would do it!
