### ISSUE TITLE
PBS HD support (Was: Error Great Performances download)

### ISSUE THREAD

**Issue by steve1001** [rg3/youtube-dl#3564]
Attempted to download a video from www.pbs.org.  The following is the error message.

c:\>youtube-dl --verbose  -o e:\req "http://www.pbs.org/wnet/gperf/dudamel-condu
cts-verdi-requiem-hollywood-bowl-full-episode/3374/"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '-o', 'e:\\req', 'http://www.pbs.org/wn
et/gperf/dudamel-conducts-verdi-requiem-hollywood-bowl-full-episode/3374/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2014.08.21.3
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] Proxy map: {}
[PBS] 3374: Downloading webpage
ERROR: Unable to extract player URL; please report this issue on https://yt-dl.o
rg/bug . Be sure to call youtube-dl with the --verbose flag and include its comp
lete output. Make sure you are using the latest version; type  youtube-dl -U  to
 update.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 517, in extract_info
  File "youtube_dl\extractor\common.pyo", line 170, in extract
  File "youtube_dl\extractor\pbs.pyo", line 98, in _real_extract
  File "youtube_dl\extractor\pbs.pyo", line 79, in _extract_ids
  File "youtube_dl\extractor\common.pyo", line 391, in _search_regex

**Comment by steve1001** [comment]
Thanks
