### ISSUE TITLE
culturebox.francetvinfo.fr issue

### ISSUE THREAD

**Issue by victoryn** [rg3/youtube-dl#3580]
Hello guys!

I'm actually trying to download this video : http://culturebox.francetvinfo.fr/live/musique/rock/franz-ferdinand-a-rock-en-seine-2013-140483 because it expires in a week and i just love it !

I just installed ffmpeg

I'm using the Windows executable and this is the error i'm getting:

C:\Users\Victor\Downloads\Programs>youtube-dl.exe "http://culturebox.francetvinf
o.fr/live/musique/rock/franz-ferdinand-a-rock-en-seine-2013-140483" --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://culturebox.francetvinfo.fr/live/musique/rock
/franz-ferdinand-a-rock-en-seine-2013-140483', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2014.08.24.5
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] Proxy map: {}
[culturebox.francetvinfo.fr] live/musique/rock/franz-ferdinand-a-rock-en-seine-2
013-140483: Downloading webpage
[culturebox.francetvinfo.fr] EV_1891: Downloading XML config
[debug] Invoking downloader on u'http://ftvodhdsecz-f.akamaihd.net/i/streaming-a
daptatif/evt/pf-culture/2013/08/1891-20130823-3-,398,632,934,2176,k.mp4.csmil/in
dex_3_av.m3u8'
[download] Destination: Franz Ferdinand à Rock en Seine 2013-EV_1891.mp4
Traceback (most recent call last):
  File "__main__.py", line 18, in <module>
  File "youtube_dl\__init__.pyo", line 895, in main
  File "youtube_dl\__init__.pyo", line 885, in _real_main
  File "youtube_dl\YoutubeDL.pyo", line 1061, in download
  File "youtube_dl\YoutubeDL.pyo", line 531, in extract_info
  File "youtube_dl\YoutubeDL.pyo", line 573, in process_ie_result
  File "youtube_dl\YoutubeDL.pyo", line 839, in process_video_result
  File "youtube_dl\YoutubeDL.pyo", line 1031, in process_info
  File "youtube_dl\YoutubeDL.pyo", line 1007, in dl
  File "youtube_dl\downloader\common.pyo", line 291, in download
  File "youtube_dl\downloader\hls.pyo", line 31, in real_download
  File "subprocess.pyo", line 522, in call
  File "subprocess.pyo", line 710, in __init__
  File "subprocess.pyo", line 913, in _execute_child
  File "subprocess.pyo", line 644, in list2cmdline
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe0 in position 0: ordinal
not in range(128)

any clue? i'm really in need of this video :/
Thanks !

**Comment by trervorx** [comment]
Have same error again on another videos. Updated to latest version.  all fine with --restrict-filenames option. May i suggest rename output file only after muxing is complete and use temporary names while ffmpeg working with files?

**Comment by dstftw** [comment]
This will be fixed in the next version. Thanks for the report.

**Comment by phihag** [comment]
I believe this issue to be fixed in youtube-dl 2015.02.02.2. See [our FAQ](https://yt-dl.org/update) if you need help updating.
