### ISSUE TITLE
Filename of thumbnail picture differs from downloaded thumbnail file when trying to add using AtomicParsley

### ISSUE THREAD

**Issue by k11i** [rg3/youtube-dl#3613]
When I try to download a video from youtube and give the option --embed-thumbnail to add the thumbnail to the extracted audio as cover art, the filename of the thumbnail used in the call to AtomicParsley is different from the file the thumbnail was safed in, resulting in an error:

```
$  ./youtube-dl -vvv 'https://www.youtube.com/watch?v=kYNPtDbykp0'
[debug] System config: []
[debug] User config: ['--youtube-include-dash-manifest', '--restrict-filenames', '--write-description', '--write-info-json', '--write-annotations', '--write-thumbnail', '--write-sub', '--all-subs', '--extract-audio', '--keep-video', '--embed-thumbnail', '--add-metadata', '--xattrs', '-f', 'bestvideo+bestaudio']
[debug] Command-line args: ['-vvv', 'https://www.youtube.com/watch?v=kYNPtDbykp0']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.08.29
[debug] Python version 2.7.5 - Darwin-13.3.0-x86_64-i386-64bit
[debug] Proxy map: {'http': 'http://extra1.int.wubv.de:3128', 'https': 'http://extra1.int.wubv.de:3128'}
[youtube] Setting language
[youtube] Confirming age
[youtube] kYNPtDbykp0: Downloading webpage
[youtube] kYNPtDbykp0: Downloading video info webpage
[youtube] kYNPtDbykp0: Extracting video information
WARNING: video doesn't have subtitles
[youtube] kYNPtDbykp0: Searching for annotations.
[youtube] kYNPtDbykp0: Downloading DASH manifest
[info] Writing video description to: Simpsons_ALS_Ice_Bucket_Challenge_THE_SIMPSONS_ANIMATION_on_FOX-kYNPtDbykp0.mp4.description
[info] Writing video annotations to: Simpsons_ALS_Ice_Bucket_Challenge_THE_SIMPSONS_ANIMATION_on_FOX-kYNPtDbykp0.mp4.annotations.xml
[info] Writing video description metadata as JSON to: Simpsons_ALS_Ice_Bucket_Challenge_THE_SIMPSONS_ANIMATION_on_FOX-kYNPtDbykp0.info.json
[youtube] kYNPtDbykp0: Downloading thumbnail ...
[youtube] kYNPtDbykp0: Writing thumbnail to: Simpsons_ALS_Ice_Bucket_Challenge_THE_SIMPSONS_ANIMATION_on_FOX-kYNPtDbykp0.jpg
[debug] Invoking downloader on 'https://r2---sn-xjpm-q0ns.googlevideo.com/videoplayback?id=91834fb436f2929d&itag=137&source=youtube&requiressl=yes&mv=m&ms=au&playback_host=r2---sn-xjpm-q0ns.googlevideo.com&mm=31&cmbypass=yes&ratebypass=yes&mime=video/mp4&gir=yes&clen=13272103&lmt=1409097395274826&dur=40.248&fexp=902408,902534,908599,912328,927622,931983,932404,932625,934024,934030,938008,941433,946021&upn=0u7vt3vpcRA&key=dg_yt0&sver=3&mt=1409301471&signature=7FE499F9D1B2CDFCEF57BAB5F2B7B97188BFBEF7.20EDAA906D756D87D345B1AD197640BC754813EC&ip=37.4.56.72&ipbits=0&expire=1409323114&sparams=ip,ipbits,expire,id,itag,source,requiressl,mv,ms,playback_host,mm,cmbypass,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: Simpsons_ALS_Ice_Bucket_Challenge_THE_SIMPSONS_ANIMATION_on_FOX-kYNPtDbykp0.f137.mp4
[download] 100% of 12.66MiB in 00:01
[debug] Invoking downloader on 'https://r2---sn-xjpm-q0ns.googlevideo.com/videoplayback?id=91834fb436f2929d&itag=141&source=youtube&requiressl=yes&mv=m&ms=au&playback_host=r2---sn-xjpm-q0ns.googlevideo.com&mm=31&cmbypass=yes&ratebypass=yes&mime=audio/mp4&gir=yes&clen=1285842&lmt=1409097367070448&dur=40.309&fexp=902408,902534,908599,912328,927622,931983,932404,932625,934024,934030,938008,941433,946021&upn=0u7vt3vpcRA&key=dg_yt0&sver=3&mt=1409301471&signature=4754978992BD2336205346F37B2CC84925D7D591.23DB89F5E9AB63D1DB82373DE02AAB2F1495F90D&ip=37.4.56.72&ipbits=0&expire=1409323114&sparams=ip,ipbits,expire,id,itag,source,requiressl,mv,ms,playback_host,mm,cmbypass,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: Simpsons_ALS_Ice_Bucket_Challenge_THE_SIMPSONS_ANIMATION_on_FOX-kYNPtDbykp0.f141.m4a
[download] 100% of 1.23MiB in 00:00
[ffmpeg] Merging formats into "Simpsons_ALS_Ice_Bucket_Challenge_THE_SIMPSONS_ANIMATION_on_FOX-kYNPtDbykp0.mp4"
[debug] ffmpeg command line: ffmpeg -y -i Simpsons_ALS_Ice_Bucket_Challenge_THE_SIMPSONS_ANIMATION_on_FOX-kYNPtDbykp0.f137.mp4 -i Simpsons_ALS_Ice_Bucket_Challenge_THE_SIMPSONS_ANIMATION_on_FOX-kYNPtDbykp0.f141.m4a -c copy Simpsons_ALS_Ice_Bucket_Challenge_THE_SIMPSONS_ANIMATION_on_FOX-kYNPtDbykp0.mp4
[ffmpeg] Adding metadata to 'Simpsons_ALS_Ice_Bucket_Challenge_THE_SIMPSONS_ANIMATION_on_FOX-kYNPtDbykp0.mp4'
[debug] ffmpeg command line: ffmpeg -y -i Simpsons_ALS_Ice_Bucket_Challenge_THE_SIMPSONS_ANIMATION_on_FOX-kYNPtDbykp0.mp4 -c copy -metadata date=20140826 -metadata 'artist=Animation Domination' -metadata 'title=Simpsons ALS Ice Bucket Challenge | THE SIMPSONS | ANIMATION on FOX' Simpsons_ALS_Ice_Bucket_Challenge_THE_SIMPSONS_ANIMATION_on_FOX-kYNPtDbykp0.temp.mp4
[ffmpeg] Destination: Simpsons_ALS_Ice_Bucket_Challenge_THE_SIMPSONS_ANIMATION_on_FOX-kYNPtDbykp0.m4a
[debug] ffmpeg command line: ffmpeg -y -i Simpsons_ALS_Ice_Bucket_Challenge_THE_SIMPSONS_ANIMATION_on_FOX-kYNPtDbykp0.mp4 -vn -acodec copy -absf aac_adtstoasc Simpsons_ALS_Ice_Bucket_Challenge_THE_SIMPSONS_ANIMATION_on_FOX-kYNPtDbykp0.m4a
[metadata] Writing metadata to file's xattrs
[atomicparsley] Adding thumbnail to "Simpsons_ALS_Ice_Bucket_Challenge_THE_SIMPSONS_ANIMATION_on_FOX-kYNPtDbykp0.m4a"
[debug] AtomicParsley command line: AtomicParsley Simpsons_ALS_Ice_Bucket_Challenge_THE_SIMPSONS_ANIMATION_on_FOX-kYNPtDbykp0.m4a --artwork Simpsons_ALS_Ice_Bucket_Challenge_THE_SIMPSONS_ANIMATION_on_FOX-kYNPtDbykp0.thumb.m4a -o Simpsons_ALS_Ice_Bucket_Challenge_THE_SIMPSONS_ANIMATION_on_FOX-kYNPtDbykp0.temp.m4a
ERROR: Image 'Simpsons_ALS_Ice_Bucket_Challenge_THE_SIMPSONS_ANIMATION_on_FOX-kYNPtDbykp0.thumb.m4a' could not be loaded.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 1097, in post_process
    keep_video_wish, new_info = pp.run(info)
  File "./youtube-dl/youtube_dl/postprocessor/atomicparsley.py", line 50, in run
    raise AtomicParsleyPPError(msg)
AtomicParsleyPPError
```

In this example the thumbnail is downloaded here:

```
[youtube] kYNPtDbykp0: Downloading thumbnail ...
[youtube] kYNPtDbykp0: Writing thumbnail to: Simpsons_ALS_Ice_Bucket_Challenge_THE_SIMPSONS_ANIMATION_on_FOX-kYNPtDbykp0.jpg
```

using the filename "Simpsons_ALS_Ice_Bucket_Challenge_THE_SIMPSONS_ANIMATION_on_FOX-kYNPtDbykp0.jpg" but later on the call to AtomicParsley uses a different name:

```
[atomicparsley] Adding thumbnail to "Simpsons_ALS_Ice_Bucket_Challenge_THE_SIMPSONS_ANIMATION_on_FOX-kYNPtDbykp0.m4a"
[debug] AtomicParsley command line: AtomicParsley Simpsons_ALS_Ice_Bucket_Challenge_THE_SIMPSONS_ANIMATION_on_FOX-kYNPtDbykp0.m4a --artwork Simpsons_ALS_Ice_Bucket_Challenge_THE_SIMPSONS_ANIMATION_on_FOX-kYNPtDbykp0.thumb.m4a -o Simpsons_ALS_Ice_Bucket_Challenge_THE_SIMPSONS_ANIMATION_on_FOX-kYNPtDbykp0.temp.m4a
```

Now it's called "Simpsons_ALS_Ice_Bucket_Challenge_THE_SIMPSONS_ANIMATION_on_FOX-kYNPtDbykp0.thumb.m4a" which does not exist. So the error:

```
ERROR: Image 'Simpsons_ALS_Ice_Bucket_Challenge_THE_SIMPSONS_ANIMATION_on_FOX-kYNPtDbykp0.thumb.m4a' could not be loaded.
```

Thank you for your consideration of this little problem. 

Have a nice day!

**Comment by 89z** [comment]
You can do this with FFmpeg now, so you don't even need AtomicParsley:

~~~
youtube-dl -x -o audio.m4a kYNPtDbykp0

ffmpeg -i audio.m4a -i http://i.ytimg.com/vi/kYNPtDbykp0/mqdefault.jpg `
-c:a copy -c:v mjpeg -disposition:v attached_pic media.m4a
~~~
