### ISSUE TITLE
'utf8' codec can't decode byte 0x8b in position 1: invalid start byte

### ISSUE THREAD

**Issue by jherazob** [rg3/youtube-dl#366]
Output of youtube-dl 5gVYfDCgYxk:

```
[youtube] Setting language
[youtube] 5gVYfDCgYxk: Downloading video webpage
[youtube] 5gVYfDCgYxk: Downloading video info webpage
[youtube] 5gVYfDCgYxk: Extracting video information
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/jherazob/bin/youtube-dl/__main__.py", line 7, in <module>
  File "/home/jherazob/bin/youtube-dl/__init__.py", line 535, in main

  File "/home/jherazob/bin/youtube-dl/__init__.py", line 519, in _real_main

  File "/home/jherazob/bin/youtube-dl/FileDownloader.py", line 475, in download
  File "/home/jherazob/bin/youtube-dl/InfoExtractors.py", line 80, in extract
  File "/home/jherazob/bin/youtube-dl/InfoExtractors.py", line 350, in _real_extract
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x8b in position 1: invalid start byte
```

The title is normal english text, not exotic characters. I imagine at some point it's assuming the text is unicode but it isn't.

**Comment by ly695908698** [comment]
because the web is gzip,so you should unpack :

if res.info().get('Content-Encoding') == 'gzip':
    buf = io.BytesIO(data)        #if python2 please use StringIO.StringIO
    gzip_f = gzip.GzipFile(fileobj=buf)
    content = gzip_f.read()
else:
    content = response.read()
