### ISSUE TITLE
[site-support-request] frontendmasters.com courses

### ISSUE THREAD

**Issue by brennebeck** [rg3/youtube-dl#3661]
``` bash
[22:14:09] ❯ youtube-dl --version
2014.09.01.1

[22:14:02] ❯ youtube-dl --verbose -t -A https://frontendmasters.com/courses/functional-javascript/#vztm1db2pwi --username=xxx --password=xxxx
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '-t', '-A', 'https://frontendmasters.com/courses/functional-javascript/#vztm1db2pwi', '--username=xxx', '--password=xxx']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.09.01.1
[debug] Python version 2.7.8 - Darwin-13.4.0-x86_64-i386-64bit
[debug] Proxy map: {}
[generic] #vztm1db2pwi: Requesting header
WARNING: Falling back on generic information extractor.
[generic] #vztm1db2pwi: Downloading webpage
[generic] #vztm1db2pwi: Extracting information
ERROR: Unsupported URL: https://frontendmasters.com/courses/functional-javascript/#vztm1db2pwi; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 530, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1472, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/local/opt/pyenv/versions/2.7.8/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/local/opt/pyenv/versions/2.7.8/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/local/opt/pyenv/versions/2.7.8/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: undefined entity: line 38, column 0
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 521, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 178, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 869, in _real_extract
    raise ExtractorError('Unsupported URL: %s' % url)
ExtractorError: Unsupported URL: https://frontendmasters.com/courses/functional-javascript/#vztm1db2pwi; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
```

I can try working on a pr, but python is definitely not my forte. If you could help by pointing me in the direction of an extractor that would work similar to this (I'm not sure but maybe I should look at the Lynda extractor?) then I'll give it a shot.

**Comment by dannycallaghan** [comment]
Has there been any movement on the Frontend Masters site request? I can't get it to work. Thanks.
