### ISSUE TITLE
site support request lego.com

### ISSUE THREAD

**Issue by KwadroNaut** [rg3/youtube-dl#3663]
[generic] video-chapter-3: Requesting header  
WARNING: Falling back on generic information extractor.  
[generic] video-chapter-3: Downloading webpage  
[generic] video-chapter-3: Extracting information  
ERROR: Unsupported URL: http://www.lego.com/nl-nl/castle/videos/video-chapter-3; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.  
Traceback (most recent call last):  
  File "./youtube-dl/youtube_dl/extractor/generic.py", line 530, in _real_extract  
    doc = parse_xml(webpage)  
  File "./youtube-dl/youtube_dl/utils.py", line 1472, in parse_xml  
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)  
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1301, in XML  
    parser.feed(text)  
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1643, in feed  
    self._raiseerror(v)  
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1507, in _raiseerror  
    raise err  
ParseError: syntax error: line 1, column 0  
Traceback (most recent call last):  
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 521, in extract_info  
    ie_result = ie.extract(url)  
  File "./youtube-dl/youtube_dl/extractor/common.py", line 178, in extract  
    return self._real_extract(url)  
  File "./youtube-dl/youtube_dl/extractor/generic.py", line 869, in _real_extract  
    raise ExtractorError('Unsupported URL: %s' % url)  
ExtractorError: Unsupported URL: http://www.lego.com/nl-nl/castle/videos/video-chapter-3; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.  

./youtube-dl --version
2014.09.01.2

**Comment by dstftw** [comment]
Works fine with latest version (2016.05.21.2).
