### ISSUE TITLE
Instagram Photo Support

### ISSUE THREAD

**Issue by limechord** [rg3/youtube-dl#3696]
```
m@bogon:/media/Data$ python youtube-dl http://instagram.com/p/spUjo2hQQd/ --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://instagram.com/p/spUjo2hQQd/', '--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.09.06
[debug] Python version 2.7.8 - Linux-3.14-2-686-pae-i686-with-debian-jessie-sid
[debug] Proxy map: {}
[Instagram] spUjo2hQQd: Downloading webpage
ERROR: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "youtube/youtube-dl/youtube_dl/YoutubeDL.py", line 523, in extract_info
    ie_result = ie.extract(url)
  File "youtube/youtube-dl/youtube_dl/extractor/common.py", line 178, in extract
    return self._real_extract(url)
  File "youtube/youtube-dl/youtube_dl/extractor/instagram.py", line 36, in _real_extract
    'url': self._og_search_video_url(webpage, secure=False),
  File "youtube/youtube-dl/youtube_dl/extractor/common.py", line 493, in _og_search_video_url
    return self._html_search_regex(regexes, html, name, **kargs)
  File "youtube/youtube-dl/youtube_dl/extractor/common.py", line 409, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags)
  File "youtube/youtube-dl/youtube_dl/extractor/common.py", line 399, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
```

**Comment by jaimeMF** [comment]
I'm closing the issue for the [same reasons why we closed the issue about flickr images](https://github.com/rg3/youtube-dl/issues/2157#issuecomment-32796488).
