### ISSUE TITLE
Support for Redbull.com

### ISSUE THREAD

**Issue by uberushaximus** [rg3/youtube-dl#3697]
Website is currently failing with this output

[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['https://www.redbull.com/ca/en/music/stories/1331676000794/diggin-in-the-carts-episode-one', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.09.04.3
[debug] Python version 3.4.1 - Linux-3.16.2-1-ARCH-x86_64-with-arch
[debug] Proxy map: {}
[generic] diggin-in-the-carts-episode-one: Requesting header
WARNING: Falling back on generic information extractor.
[generic] diggin-in-the-carts-episode-one: Downloading webpage
[generic] diggin-in-the-carts-episode-one: Extracting information
[generic] Brightcove video detected.
[download] Downloading playlist: Catch the first episode of RBMA’s Diggin’ In The Carts
[generic] playlist Catch the first episode of RBMA’s Diggin’ In The Carts: Collected 1 video ids (downloading 1 of them)
[download] Downloading video #1 of 1
[Brightcove] ref:digginInTheCards: Downloading webpage
Traceback (most recent call last):
  File "/usr/bin/youtube-dl", line 9, in <module>
    load_entry_point('youtube-dl==2014.09.04.3', 'console_scripts', 'youtube-dl')()
  File "/usr/lib/python3.4/site-packages/youtube_dl/**init**.py", line 896, in main
    _real_main(argv)
  File "/usr/lib/python3.4/site-packages/youtube_dl/__init__.py", line 886, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 1065, in download
    self.extract_info(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 534, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 658, in process_ie_result
    extra_info=extra)
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 583, in process_ie_result
    extra_info=extra_info)
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 523, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 178, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/brightcove.py", line 192, in _real_extract
    videoPlayer[0], query_str, query, referer=referer)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/brightcove.py", line 209, in _get_video_info
    webpage = self._download_webpage(req, video_id)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 291, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 231, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 211, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 1244, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 455, in open
    response = self._open(req, data)
  File "/usr/lib/python3.4/urllib/request.py", line 473, in _open
    '_open', req)
  File "/usr/lib/python3.4/urllib/request.py", line 433, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 1215, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.4/urllib/request.py", line 1189, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.4/http/client.py", line 1090, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.4/http/client.py", line 1123, in _send_request
    self.putheader(hdr, value)
  File "/usr/lib/python3.4/http/client.py", line 1066, in putheader
    values[i] = one_value.encode('latin-1')
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2019' in position 80: ordinal not in range(256)

**Comment by dstftw** [comment]
Works with latest version.

**Comment by desseim** [comment]
Actually `redbull.tv` and `redbullradio.com` links are supported, but `redbullmusicacademy.com` links like the aforementioned [http://www.redbullmusicacademy.com/magazine/diggin-in-the-carts]() don't.
Should a new issue be opened to add support for these ?
