### ISSUE TITLE
[generic] Brightcove - ExtractorError: Cannot find playerKey= variable

### ISSUE THREAD

**Issue by monocult** [rg3/youtube-dl#3704]
```
youtube-dl -v "http://www.os1.tv/Video/46408282001/"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.os1.tv/Video/46408282001/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.09.06
[debug] Python version 2.7.8 - Darwin-13.3.0-x86_64-i386-64bit
[debug] Proxy map: {}
[generic] 46408282001: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 46408282001: Downloading webpage
[generic] 46408282001: Extracting information
[generic] Brightcove video detected.
[download] Downloading playlist: os1.tv - Ihr TV-Sender für Ihre Region. Keiner ist näher dran!
[generic] playlist os1.tv - Ihr TV-Sender für Ihre Region. Keiner ist näher dran!: Collected 1 video ids (downloading 1 of them)[download] Downloading video #1 of 1
ERROR: Cannot find playerKey= variable. Did you forget quotes in a shell invocation?
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 523, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 178, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/brightcove.py", line 199, in _real_extract
    expected=True)
ExtractorError: Cannot find playerKey= variable. Did you forget quotes in a shell invocation?
```

**Comment by remitamine** [comment]
now, the page is not available.
