### ISSUE TITLE
Dailymotion previews

### ISSUE THREAD

**Issue by Rudloff** [rg3/youtube-dl#3705]
Hello,

youtube-dl does not seem to be able to download previews for paid videos on Dailymotion:

```
[dailymotion] x24u2h3: Downloading webpage
[dailymotion] x24u2h3: Extracting information
[dailymotion] x24u2h3: Downloading embed page
ERROR: Unable to extract video URL; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
pierre@home:~/youtube-dl$ ./youtube-dl http://www.dailymotion.com/video/x24u2h3_dessous-des-cartes-le-detroit-de-bering-pont-ou-frontiere_tv?start=8 -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://www.dailymotion.com/video/x24u2h3_dessous-des-cartes-le-detroit-de-bering-pont-ou-frontiere_tv?start=8', '-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.09.06
[debug] Python version 2.7.3 - Linux-3.2.0-4-amd64-x86_64-with-debian-7.6
[debug] Proxy map: {}
[dailymotion] x24u2h3: Downloading webpage
[dailymotion] x24u2h3: Extracting information
[dailymotion] x24u2h3: Downloading embed page
ERROR: Unable to extract video URL; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 523, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 178, in extract
    return self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/dailymotion.py", line 142, in _real_extract
    raise ExtractorError('Unable to extract video URL')
ExtractorError: Unable to extract video URL; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
```

**Comment by Rudloff** [comment]
This seems to work now.
