### ISSUE TITLE
youjizz link error

### ISSUE THREAD

**Issue by ghost** [rg3/youtube-dl#3722]
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 18, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/**init**.py", line 897, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/**init**.py", line 887, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1065, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 523, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 178, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youjizz.py", line 29, in _real_extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 291, in _download_webpage
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 231, in _download_webpage_handle
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 211, in _request_webpage
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1244, in urlopen
  File "/usr/lib/python2.7/urllib2.py", line 393, in open
    protocol = req.get_type()
  File "/usr/lib/python2.7/urllib2.py", line 255, in get_type
    raise ValueError, "unknown url type: %s" % self.__original
ValueError: unknown url type: www.youjizz.com/videos/great-cumshot-compilation-5807621.html

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 18, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/**init**.py", line 897, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/**init**.py", line 887, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1065, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 523, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 178, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youjizz.py", line 29, in _real_extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 291, in _download_webpage
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 231, in _download_webpage_handle
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 211, in _request_webpage
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1244, in urlopen
  File "/usr/lib/python2.7/urllib2.py", line 393, in open
    protocol = req.get_type()
  File "/usr/lib/python2.7/urllib2.py", line 255, in get_type
    raise ValueError, "unknown url type: %s" % self.__original
ValueError: unknown url type: youjizz.com/videos/great-cumshot-compilation-5807621.html

**Comment by ifenldrmk** [comment]
_操_逼_视频,你懂的  [点击进入](https://www.scc5.top/)

_操_逼_视频,你懂的  [点击进入](https://www.scc8.top/)

      
焕贸暇凳赜奄首医拐傺我是哪
