### ISSUE TITLE
Unable to download http://www.ustream.tv/channel/svp-network

### ISSUE THREAD

**Issue by chzuping** [rg3/youtube-dl#3728]
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.ustream.tv/channel/svp-network']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2014.09.10.1
[debug] Python version 2.7.8 - Windows-XP-5.1.2600-SP3
[debug] Proxy map: {}
[ustream:channel] svp-network: Downloading webpage
[ustream:channel] svp-network: Downloading video information (next: 1)
[ustream:channel] svp-network: Downloading video information (next: 13)
[download] Downloading playlist: 13279106
[ustream:channel] playlist 13279106: Collected 18 video ids (downloading 18 of them)
[download] Downloading video #1 of 18
[ustream] 49446313: Downloading webpage
[ustream] 49446313: Extracting information
[debug] Invoking downloader on u'http://tcdn.ustream.tv/video/49446313'
ERROR: unable to download video data: [Errno 10054] An existing connection was forcibly closed by the remote host
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 1035, in process_info
  File "youtube_dl\YoutubeDL.pyo", line 1011, in dl
  File "youtube_dl\downloader\common.pyo", line 291, in download
  File "youtube_dl\downloader\http.pyo", line 66, in real_download
  File "youtube_dl\YoutubeDL.pyo", line 1244, in urlopen
  File "urllib2.pyo", line 410, in open
  File "urllib2.pyo", line 523, in http_response
  File "urllib2.pyo", line 442, in error
  File "urllib2.pyo", line 382, in _call_chain
  File "urllib2.pyo", line 629, in http_error_302
  File "urllib2.pyo", line 404, in open
  File "urllib2.pyo", line 422, in _open
  File "urllib2.pyo", line 382, in _call_chain
  File "urllib2.pyo", line 1214, in http_open
  File "urllib2.pyo", line 1187, in do_open
  File "httplib.pyo", line 1067, in getresponse
  File "httplib.pyo", line 409, in begin
  File "httplib.pyo", line 365, in _read_status
  File "socket.pyo", line 476, in readline
error: [Errno 10054] An existing connection was forcibly closed by the remote host

**Comment by yan12125** [comment]
youtube-dl should be working for this video in the next version. Please confirm that. If you still encounter problems, feel free to open a new issue.

**Comment by dstftw** [comment]
This has been fixed in youtube-dl 2015.04.26. See our [FAQ](https://yt-dl.org/update) if you have problems updating.
