### ISSUE TITLE
obizgo.tv

### ISSUE THREAD

**Issue by markienzuk** [rg3/youtube-dl#3737]
fails to download video from this user pays site. I was already logged in and authenticated, copied the URL and pasted it next to the command line to download the video.
laptop is running latest ubuntu 14.04, completely updated and running latest version of youtube-dl
here is the error message
PC:~/Videos$ youtube-dl --verbose http://obizgo.tv/VoIrC/13851/468895
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://obizgo.tv/VoIrC/13851/468895']
[debug] Encodings: locale 'UTF-8', fs 'UTF-8', out 'UTF-8', pref: 'UTF-8'
[debug] youtube-dl version 2014.02.17
[debug] Python version 2.7.6 - Linux-3.13.0-35-generic-i686-with-Ubuntu-14.04-trusty
[debug] Proxy map: {}
[generic] 468895: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 468895: Downloading webpage
[generic] 468895: Extracting information
ERROR: Unsupported URL: http://obizgo.tv/VoIrC/13851/468895; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 493, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 158, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 380, in _real_extract
    raise ExtractorError('Unsupported URL: %s' % url)
ExtractorError: Unsupported URL: http://obizgo.tv/VoIrC/13851/468895; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by TRox1972** [comment]
Account required. At least for the provided URL.
