### ISSUE TITLE
ustream.tv nasa tv cannot access

### ISSUE THREAD

**Issue by o3814080** [rg3/youtube-dl#3771]
Hi, 
I suppose use the stdout to export to mplayer but have problems occured.
This is the log.

youtube-dl --verbose -o - http://ustream.tv/nasahdtv
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '-o', '-', 'http://ustream.tv/nasahdtv']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.09.16
[debug] Python version 2.7.3 - Linux-3.2.0-51-generic-x86_64-with-LinuxMint-13-maya
[debug] Proxy map: {}
[generic] nasahdtv: Requesting header
[redirect] Following redirect to http://www.ustream.tv/nasahdtv
[generic] nasahdtv: Requesting header
WARNING: Falling back on generic information extractor.
[generic] nasahdtv: Downloading webpage
[generic] nasahdtv: Extracting information
ERROR: Unsupported URL: http://www.ustream.tv/nasahdtv; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 545, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1509, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1301, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1643, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1507, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 82, column 2701
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 524, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 178, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 890, in _real_extract
    raise ExtractorError('Unsupported URL: %s' % url)
ExtractorError: Unsupported URL: http://www.ustream.tv/nasahdtv; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

let me know if anyone need further information.
Thanks !

**Comment by GitSkunk** [comment]
Fallback to the generic extractor still happens in 2015.04.17.

youtube-dl.exe --verbose "http://www.ustream.tv/nasahdtv"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.ustream.tv/nasahdtv']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.04.17
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-50911-g9efcfbe, ffprobe N-44818-g13f0cd6, rtmpdump 2.3
[debug] Proxy map: {}
[generic] nasahdtv: Requesting header
WARNING: Falling back on generic information extractor.
[generic] nasahdtv: Downloading webpage
[generic] nasahdtv: Extracting information
ERROR: Unsupported URL: http://www.ustream.tv/nasahdtv
Traceback (most recent call last):
  File "youtube_dl\extractor\generic.pyo", line 923, in _real_extract
  File "youtube_dl\utils.pyo", line 1531, in parse_xml
  File "xml\etree\ElementTree.pyo", line 1300, in XML
  File "xml\etree\ElementTree.pyo", line 1642, in feed
  File "xml\etree\ElementTree.pyo", line 1506, in _raiseerror
ParseError: not well-formed (invalid token): line 82, column 2118
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 651, in extract_info
  File "youtube_dl\extractor\common.pyo", line 275, in extract
  File "youtube_dl\extractor\generic.pyo", line 1442, in _real_extract
UnsupportedError: Unsupported URL: http://www.ustream.tv/nasahdtv
