### ISSUE TITLE
Unable to update - HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by Rosuav** [rg3/youtube-dl#3780]
Trying to download any video from Youtube results in "KeyError: 'sig'", so I'm trying to update youtube-dl to see if there are any changes.

```
$ sudo youtube-dl --updateUpdating to latest version...
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 7, in <module>
  File "/usr/local/bin/youtube-dl/__init__.py", line 536, in main
    
  File "/usr/local/bin/youtube-dl/__init__.py", line 510, in _real_main
    
  File "/usr/local/bin/youtube-dl/__init__.py", line 55, in updateSelf
    
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 407, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 520, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 439, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 379, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 626, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python2.7/urllib2.py", line 407, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 520, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 445, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 379, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 528, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found
$ youtube-dl --version
2012.09.27
```

Am I on a version that's too old to automatically update? If so, what's the recommended approach?

**Comment by dstftw** [comment]
Manual instruction can be found here: http://rg3.github.io/youtube-dl/download.html.
