### ISSUE TITLE
[site-support-request] video.nationalgeographic.com

### ISSUE THREAD

**Issue by BonzoFestoon** [rg3/youtube-dl#3796]
```
D:\youtube-dl>Waiting for file handle to be closed ...
Updated youtube-dl to version 2014.09.19.

D:\youtube-dl>youtube-dl.exe --verbose http://video.nationalgeographic.com/video/smallpox-sci
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://video.nationalgeographic.com/video/smallpox-sci']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2014.09.19
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] Proxy map: {}
[generic] smallpox-sci: Requesting header
WARNING: Falling back on generic information extractor.
[generic] smallpox-sci: Downloading webpage
[generic] smallpox-sci: Extracting information
ERROR: Unsupported URL: http://video.nationalgeographic.com/video/smallpox-sci; please report this issue on https://yt-dl.org/bug . Be sure to call yo
utube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "youtube_dl\extractor\generic.pyo", line 545, in _real_extract
  File "youtube_dl\utils.pyo", line 1509, in parse_xml
  File "xml\etree\ElementTree.pyo", line 1300, in XML
  File "xml\etree\ElementTree.pyo", line 1642, in feed
  File "xml\etree\ElementTree.pyo", line 1506, in _raiseerror
ParseError: undefined entity: line 30, column 0
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 524, in extract_info
  File "youtube_dl\extractor\common.pyo", line 180, in extract
  File "youtube_dl\extractor\generic.pyo", line 890, in _real_extract
ExtractorError: Unsupported URL: http://video.nationalgeographic.com/video/smallpox-sci; please report this issue on https://yt-dl.org/bug . Be sure t
o call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

```

**Comment by naglis** [comment]
Support for nationalgeographic has been added in youtube-dl 2015.02.19.3. Refer to [our FAQ](https://yt-dl.org/update) if you need help updating.
