### ISSUE TITLE
site support request http://www.msnbc.com/global-citizen-festival

### ISSUE THREAD

**Issue by FortunateBliss** [rg3/youtube-dl#3843]
please add support for:
http://www.msnbc.com/global-citizen-festival

C:\Program Files (x86)\YouTube-DL>youtube-dl.exe http://www.msnbc.com/global-citizen-festival  --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://www.msnbc.com/global-citizen-festival', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2014.09.25
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] Proxy map: {}
[generic] global-citizen-festival: Requesting header
WARNING: Falling back on generic information extractor.
[generic] global-citizen-festival: Downloading webpage
[generic] global-citizen-festival: Extracting information
ERROR: Unsupported URL: http://www.msnbc.com/global-citizen-festival; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "youtube_dl\extractor\generic.pyo", line 545, in _real_extract
  File "youtube_dl\utils.pyo", line 1509, in parse_xml
  File "xml\etree\ElementTree.pyo", line 1300, in XML
  File "xml\etree\ElementTree.pyo", line 1642, in feed
  File "xml\etree\ElementTree.pyo", line 1506, in _raiseerror
ParseError: not well-formed (invalid token): line 121, column 43
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 524, in extract_info
  File "youtube_dl\extractor\common.pyo", line 181, in extract
  File "youtube_dl\extractor\generic.pyo", line 892, in _real_extract
ExtractorError: Unsupported URL: http://www.msnbc.com/global-citizen-festival; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

C:\Program Files (x86)\YouTube-DL>

**Comment by yan12125** [comment]
Single videos like http://www.msnbc.com/msnbc/watch/living-on-a-dollar-a-day-reality-of-extreme-poverty-revealed-329367619968 will be supported in the next version, while http://www.msnbc.com/global-citizen-festival is not directly supported yet.
