### ISSUE TITLE
Need support for tou.tv

### ISSUE THREAD

**Issue by interlocuteur** [rg3/youtube-dl#3859]
youtube-dl --verbose 'http://ici.tou.tv/unite-9/S03E01'
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://ici.tou.tv/unite-9/S03E01']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.09.29.2
[debug] Python version 2.7.6 - Linux-3.14.18-desktop-3.mga4-x86_64-with-mandrake-4-Official
[debug] Proxy map: {}
[generic] S03E01: Requesting header
WARNING: Falling back on generic information extractor.
[generic] S03E01: Downloading webpage
[generic] S03E01: Extracting information
ERROR: Unsupported URL: http://ici.tou.tv/unite-9/S03E01; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/extractor/generic.py", line 556, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/bin/youtube-dl/youtube_dl/utils.py", line 1540, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: syntax error: line 3, column 0
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 524, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 191, in extract
    return self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/generic.py", line 913, in _real_extract
    raise ExtractorError('Unsupported URL: %s' % url)
ExtractorError: Unsupported URL: http://ici.tou.tv/unite-9/S03E01; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by gineadai** [comment]
Redirects to http://ici.tou.tv/non-supportes.html
`Unfortunately, the site is not optimized for this browser version.`
