### ISSUE TITLE
Vice (Ooyala) not working with generic extractor

### ISSUE THREAD

**Issue by zacs** [rg3/youtube-dl#3880]
Looking back at old commits, looks like the Vice functionality was removed from its own IE and added to the Ooyala one. I may be wrong about that. Verbose output:

```
$ youtube-dl -v http://www.vice.com/the-real/the-real-true-detective-010                                                         10/04/2014 15:55:08 PDT
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.vice.com/the-real/the-real-true-detective-010']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.10.02
[debug] Python version 2.7.6 - Darwin-13.3.0-x86_64-i386-64bit
[debug] Proxy map: {}
[generic] the-real-true-detective-010: Requesting header
WARNING: Falling back on generic information extractor.
[generic] the-real-true-detective-010: Downloading webpage
[generic] the-real-true-detective-010: Extracting information
ERROR: Unsupported URL: http://www.vice.com/the-real/the-real-true-detective-010; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 540, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1549, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 74, column 50
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 524, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 191, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 897, in _real_extract
    raise ExtractorError('Unsupported URL: %s' % url)
ExtractorError: Unsupported URL: http://www.vice.com/the-real/the-real-true-detective-010; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
```

**Comment by naglis** [comment]
Vice extractor has been re-added, so it should work with youtube-dl 2014.11.09 and newer. Please update and try, if it works for you (see [our FAQ](https://yt-dl.org/update) if you have problems updating).

Please note, however, that the URL you had problem's with no longer exists or the URL scheme on Vice.com has changed a bit - I've found it to now be: `http://www.vice.com/video/the-real-true-detective-010`.

I am closing this now, comment here if the problem still persists after updating and I'll reopen it, or open a new issue.
