### ISSUE TITLE
CBS Unsupported URL (v. 2014.10.05.2)

### ISSUE THREAD

**Issue by ghost** [rg3/youtube-dl#3889]
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.cbs.com/shows/ncis/video/']

[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2014.10.05.2
[debug] Python version 3.4.1 - Windows-8-6.2.9200
[debug] Proxy map: {}
[generic] video: Requesting header
WARNING: Falling back on generic information extractor.
[generic] video: Downloading webpage
[generic] video: Extracting information
ERROR: Unsupported URL: http://www.cbs.com/shows/ncis/video/; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "youtube-dl\youtube_dl\YoutubeDL.py", line 524, in extract_info
    ie_result = ie.extract(url)
  File "youtube-dl\youtube_dl\extractor\common.py", line 193, in extract
    return self._real_extract(url)
  File "youtube-dl\youtube_dl\extractor\generic.py", line 907, in _real_extract
    raise ExtractorError('Unsupported URL: %s' % url)
youtube_dl.utils.ExtractorError: Unsupported URL: http://www.cbs.com/shows/ncis/video/; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by d3str0y3r** [comment]
I don't have these problems with CBS.
Maybe this issue can be closed then...

**Comment by mpenkov** [comment]
Is this still a problem? If not, then perhaps we can close it.
