### ISSUE TITLE
Getting 403 Forbidden Error 

### ISSUE THREAD

**Issue by BonzoFestoon** [rg3/youtube-dl#3897]
Not sure if this is fixable, but thought I would report as an issue just to be sure.
```
D:\youtube-dl>youtube-dl.exe --verbose http://learnenglishteens.britishcouncil.org/grammar-vocabulary/grammar-videos/third-conditional
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://learnenglishteens.britishcouncil.org/grammar-vocabulary/grammar-videos/third-conditional']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2014.10.05.2
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] Proxy map: {}
[generic] third-conditional: Requesting header
WARNING: Falling back on generic information extractor.
[generic] third-conditional: Downloading webpage
[generic] third-conditional: Extracting information
[download] Downloading playlist: None
[generic] playlist None: Collected 2 video ids (downloading 2 of them)
[download] Downloading video #1 of 2
[debug] Invoking downloader on u'http://www.viddler.com/file/221ebbbd/html5mobile?openURL=14451388'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 1037, in process_info
  File "youtube_dl\YoutubeDL.pyo", line 1013, in dl
  File "youtube_dl\downloader\common.pyo", line 292, in download
  File "youtube_dl\downloader\http.pyo", line 64, in real_download
  File "youtube_dl\YoutubeDL.pyo", line 1266, in urlopen
  File "urllib2.pyo", line 410, in open
  File "urllib2.pyo", line 523, in http_response
  File "urllib2.pyo", line 448, in error
  File "urllib2.pyo", line 382, in _call_chain
  File "urllib2.pyo", line 531, in http_error_default
HTTPError: HTTP Error 403: Forbidden


D:\youtube-dl>
```

**Comment by dstftw** [comment]
Thanks for the report. This will be fixed in the next version of youtube-dl.
