### ISSUE TITLE
add support for  vod.dmi.ae

### ISSUE THREAD

**Issue by Muhammad-Z** [rg3/youtube-dl#3907]
youtube-dl --verbose http://vod.dmi.ae/media/218271/%D8%A7%D9%84%D9%82%D8%B1%D8%A2%D9%86_%D8%B9%D9%84%D9%85_%D9%88%D8%A8%D9%8A%D8%A7%D9%86_04_01_2013 > reportttas
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://vod.dmi.ae/media/218271/%D8%A7%D9%84%D9%82%D8%B1%D8%A2%D9%86_%D8%B9%D9%84%D9%85_%D9%88%D8%A8%D9%8A%D8%A7%D9%86_04_01_2013']
[debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8
[debug] youtube-dl version 2014.10.05.2
[debug] Python version 2.7.3 - Linux-3.2.0-69-generic-pae-i686-with-elementary_OS-0.2.1-luna
[debug] Proxy map: {}
WARNING: Falling back on generic information extractor.
ERROR: Unsupported URL: http://vod.dmi.ae/media/218271/%D8%A7%D9%84%D9%82%D8%B1%D8%A2%D9%86_%D8%B9%D9%84%D9%85_%D9%88%D8%A8%D9%8A%D8%A7%D9%86_04_01_2013; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 540, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1550, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1301, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1643, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1507, in _raiseerror
    raise err
ParseError: mismatched tag: line 64, column 4
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 524, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 193, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 907, in _real_extract
    raise ExtractorError('Unsupported URL: %s' % url)
ExtractorError: Unsupported URL: http://vod.dmi.ae/media/218271/%D8%A7%D9%84%D9%82%D8%B1%D8%A2%D9%86_%D8%B9%D9%84%D9%85_%D9%88%D8%A8%D9%8A%D8%A7%D9%86_04_01_2013; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by remitamine** [comment]
works with the latest version.
