### ISSUE TITLE
'youtube-dl.exe -U' fails with "Access is denied." even with administrator rights, windows 7

### ISSUE THREAD

**Issue by requiredregistration** [rg3/youtube-dl#3912]

**Comment by codaman** [comment]
i also get this error

Traceback (most recent call last): File "main.py", line 19, in File "youtube_dl__init__.pyo", line 410, in main File "youtube_dl__init__.pyo", line 377, in real_main File "youtube_dl\YoutubeDL.pyo", line 338, in __init_ File "youtube_dl\YoutubeDL.pyo", line 1969, in _setup_opener File "youtube_dl\utils.pyo", line 492, in make_HTTPS_handler File "ssl.pyo", line 440, in create_default_context File "ssl.pyo", line 391, in load_default_certs File "ssl.pyo", line 378, in _load_windows_store_certs WindowsError: [Error 5] Access is denied

after version 2015.10.18

**Comment by yan12125** [comment]
@codaman Due to insufficient information I'm not sure whether your problems is the same as others in this thread or not. Please open a new issue as I'm going to close this one.

@requiredregistration @Scroph @iggyvolz Could you paste the output of ```youtube-dl -U```?

**Comment by codaman** [comment]
i think same youtube-dl try to access windows certification store if even use --no-check-certificate. so windows blocks this operation you'll get Access is Denied error. may be i'm wrong but i'll get same error in my server

**Comment by trandinhnam** [comment]
any update for this issue?

**Comment by Hrxn** [comment]
I'd bet on issues with your %Path%...

**Comment by Taurus3ye** [comment]
Had the same problem and could fix it by adding youtube-dl to the Environment Variables.
