### ISSUE TITLE
'NoneType' object has no attribute 'replace' while downloading YouTube Mix

### ISSUE THREAD

**Issue by cyberjacob** [rg3/youtube-dl#3914]
Getting a nice little AttributeError after downloading the first video in a YouTube Mix playlist in version 2014.10.05.2 under Python 2.7.1 on OS X 10.7.5. The mix in question is RDHCs-z409g1yaka

    youtube-dl -vix --audio-format mp3 RDHCs-z409g1yakapyth
    **CUT**
    [download] Destination: Celine Dion - Right in front of you-Tm30Taxdl58.m4a
    [download] 100% of 3.88MiB in 00:02
    [ffmpeg] Destination: Celine Dion - Right in front of you-Tm30Taxdl58.mp3
    [debug] ffmpeg command line: ffmpeg -y -i 'Celine Dion - Right in front of you-Tm30Taxdl58.m4a' -vn -acodec libmp3lame -aq 5 'Celine Dion - Right in front of you-Tm30Taxdl58.mp3'
    Deleting original file Celine Dion - Right in front of you-Tm30Taxdl58.m4a (pass -k to keep)
    [youtube:playlist] RDHCs-z409g1yaka: Downloading Youtube mix
    ERROR: 'NoneType' object has no attribute 'replace'
    Traceback (most recent call last):
      File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 524, in extract_info
        ie_result = ie.extract(url)
      File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 193, in extract
        return self._real_extract(url)
      File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1137, in _real_extract
        return self._extract_mix(playlist_id)
      File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1109, in _extract_mix
        title = clean_html(title_span)
      File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 447, in clean_html
        html = html.replace('\n', ' ')
    AttributeError: 'NoneType' object has no attribute 'replace'
    pangea:Birthday ccuk$ youtube-dl --version
    2014.10.05.2
    pangea:Birthday ccuk$

**Comment by dstftw** [comment]
Closing due to no response for a long time.
