### ISSUE TITLE
redbull.tv - site support request

### ISSUE THREAD

**Issue by jpfl** [rg3/youtube-dl#3919]
Please add support for Redbull.tv, in particular there is the Austin City Limits Music Festival going on from Oct 10-12th on 2 channels:

http://aclfest.redbull.tv/#!/stream/1
http://aclfest.redbull.tv/#!/stream/2

support for redbull.tv live events and VOD in general would be very nice

I have updated youtube-dl and then ran it with --verbose:

C:\Program Files (x86)\YouTube-DL>youtube-dl.exe "http://aclfest.redbull.tv/#!/s
tream/1" --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://aclfest.redbull.tv/#!/stream/1', '--verbose'
]
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2014.10.05.2
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] Proxy map: {}
[generic] 1: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 1: Downloading webpage
[generic] 1: Extracting information
ERROR: Unsupported URL: http://aclfest.redbull.tv/#!/stream/1; please report thi
s issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose
 flag and include its complete output. Make sure you are using the latest versio
n; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "youtube_dl\extractor\generic.pyo", line 540, in _real_extract
  File "youtube_dl\utils.pyo", line 1550, in parse_xml
  File "xml\etree\ElementTree.pyo", line 1300, in XML
  File "xml\etree\ElementTree.pyo", line 1642, in feed
  File "xml\etree\ElementTree.pyo", line 1506, in _raiseerror
ParseError: syntax error: line 1, column 0
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 524, in extract_info
  File "youtube_dl\extractor\common.pyo", line 193, in extract
  File "youtube_dl\extractor\generic.pyo", line 907, in _real_extract
ExtractorError: Unsupported URL: http://aclfest.redbull.tv/#!/stream/1; please r
eport this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the
--verbose flag and include its complete output. Make sure you are using the late
st version; type  youtube-dl -U  to update.

and for channel 2:

C:\Program Files (x86)\YouTube-DL>youtube-dl.exe "http://aclfest.redbull.tv/#!/s
tream/2" --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://aclfest.redbull.tv/#!/stream/2', '--verbose'
]
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2014.10.05.2
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] Proxy map: {}
[generic] 2: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 2: Downloading webpage
[generic] 2: Extracting information
ERROR: Unsupported URL: http://aclfest.redbull.tv/#!/stream/2; please report thi
s issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose
 flag and include its complete output. Make sure you are using the latest versio
n; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "youtube_dl\extractor\generic.pyo", line 540, in _real_extract
  File "youtube_dl\utils.pyo", line 1550, in parse_xml
  File "xml\etree\ElementTree.pyo", line 1300, in XML
  File "xml\etree\ElementTree.pyo", line 1642, in feed
  File "xml\etree\ElementTree.pyo", line 1506, in _raiseerror
ParseError: syntax error: line 1, column 0
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 524, in extract_info
  File "youtube_dl\extractor\common.pyo", line 193, in extract
  File "youtube_dl\extractor\generic.pyo", line 907, in _real_extract
ExtractorError: Unsupported URL: http://aclfest.redbull.tv/#!/stream/2; please r
eport this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the
--verbose flag and include its complete output. Make sure you are using the late
st version; type  youtube-dl -U  to update.

**Comment by renaudguerin** [comment]
Seconding this one, unsupported in latest version : 
$ youtube-dl -U
youtube-dl is up-to-date (2015.01.25)

Example URL:
http://www.redbull.tv/videos/AP-1GH81DB191W11/lindsey-vonn-the-climb#autostart

Pretty sure it's using Brightcove like Redbull.com, so it should just be a matter of detecting it correctly.

**Comment by luke29ermtb** [comment]
+1 Thanks for this excellent software. 

Using version 2015.02.06

ERROR: Unsupported URL: http://www.redbull.tv/videos/event-stream-346/cross-country-men
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/extractor/generic.py", line 707, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/bin/youtube-dl/youtube_dl/utils.py", line 1501, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 12, column 312
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 619, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 268, in extract
    return self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1132, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.redbull.tv/videos/event-stream-346/cross-country-men

**Comment by luke29ermtb** [comment]
http://www.redbull.com/au/en/bike/stories/1331644431583/replay-uci-xco-world-cup-2014-from-pietermaritzburg works but http://www.redbull.tv/videos/event-stream-346/cross-country-men doesn't so I'm guessing the cause of the post above isn't youtube-dl.

**Comment by voltagex** [comment]
PS C:\Users\Adam\Videos> youtube-dl.exe --verbose http://www.redbull.tv/episodes/AP-1K4GF3YSW2111/inside-ice-cross-down
ill
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.redbull.tv/episodes/AP-1K4GF3YSW2111/inside-ice-cross-downhill']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.11.27.1
[debug] Python version 2.7.10 - Windows-8-6.2.9200
[debug] exe versions: ffmpeg N-77045-ga16243a, ffprobe N-77045-ga16243a, rtmpdump 2.4
[debug] Proxy map: {}
[generic] inside-ice-cross-downhill: Requesting header
WARNING: Falling back on generic information extractor.
[generic] inside-ice-cross-downhill: Downloading webpage
[generic] inside-ice-cross-downhill: Extracting information
ERROR: Unsupported URL: http://www.redbull.tv/episodes/AP-1K4GF3YSW2111/inside-ice-cross-downhill
Traceback (most recent call last):
  File "youtube_dl\extractor\generic.pyo", line 1282, in _real_extract
  File "youtube_dl\compat.pyo", line 248, in compat_etree_fromstring
  File "youtube_dl\compat.pyo", line 237, in _XML
  File "xml\etree\ElementTree.pyo", line 1642, in feed
  File "xml\etree\ElementTree.pyo", line 1506, in _raiseerror
ParseError: not well-formed (invalid token): line 12, column 311
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 663, in extract_info
  File "youtube_dl\extractor\common.pyo", line 290, in extract
  File "youtube_dl\extractor\generic.pyo", line 1887, in _real_extract
UnsupportedError: Unsupported URL: http://www.redbull.tv/episodes/AP-1K4GF3YSW2111/inside-ice-cross-downhill

**Comment by voltagex** [comment]
Loading https://www.redbull.tv/episodes/AP-1K4GF3YSW2111/inside-ice-cross-downhill while spoofing user-agent as iPad suggests a Brightcove extractor might work, but I'm getting so many Javascript and SSL errors in Chrome that it's difficult to test further

**Comment by voltagex** [comment]
Found in the meta tag of the above site, secure.brightcove URL - PS C:\Users\Adam\Videos> youtube-dl.exe --verbose "https://secure.brightcove.com/services/viewer/federated_f9?&amp;width
=100%25&amp;height=100%25&amp;isVid=true&amp;playerKey=AQ~~,AAACZYoJeMk~,6-AuiH-yar7vhFK8T1lKHxOJlJLkWYk4&amp;secureConn
ections=true&amp;secureHTMLConnections=true&amp;videoID=MI201509080017&amp;allowFullScreen=true&amp;allowScriptAccess=tr
ue&amp;autoStart=false&amp;dynamicStreaming=true&amp;quality=high&amp;debuggerID="
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://secure.brightcove.com/services/viewer/federated_f9?&amp;width=100%25
&amp;height=100%25&amp;isVid=true&amp;playerKey=AQ~~,AAACZYoJeMk~,6-AuiH-yar7vhFK8T1lKHxOJlJLkWYk4&amp;secureConnections
=true&amp;secureHTMLConnections=true&amp;videoID=MI201509080017&amp;allowFullScreen=true&amp;allowScriptAccess=true&amp;
autoStart=false&amp;dynamicStreaming=true&amp;quality=high&amp;debuggerID=']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.11.27.1
[debug] Python version 2.7.10 - Windows-8-6.2.9200
[debug] exe versions: ffmpeg N-77045-ga16243a, ffprobe N-77045-ga16243a, rtmpdump 2.4
[debug] Proxy map: {}
[brightcove:legacy] AQ~~,AAACZYoJeMk~,6-AuiH-yar7vhFK8T1lKHxOJlJLkWYk4: Downloading playlist information
ERROR: Empty playlist; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; t
ype  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 663, in extract_info
  File "youtube_dl\extractor\common.pyo", line 290, in extract
  File "youtube_dl\extractor\brightcove.pyo", line 245, in _real_extract
  File "youtube_dl\extractor\brightcove.pyo", line 283, in _get_playlist_info
ExtractorError: Empty playlist; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest v
ersion; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete outp
ut.

**Comment by johny1** [comment]
hi. I'm having the same issue and would also like to see this site supported


youtube-dl -v www.redbull.tv/episodes/AP-1GH4VU4NS2111
/lima
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'www.redbull.tv/episodes/AP-1GH4VU4NS2111/li
ma']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.01.09
[debug] Python version 2.7.10 - Windows-8-6.2.9200
[debug] exe versions: ffmpeg N-77234-g906c0b7
[debug] Proxy map: {}
WARNING: The url doesn't specify the protocol, trying with http
[generic] lima: Requesting header
WARNING: Falling back on generic information extractor.
[generic] lima: Downloading webpage
[generic] lima: Extracting information
ERROR: Unsupported URL: http://www.redbull.tv/episodes/AP-1GH4VU4NS2111/lima
Traceback (most recent call last):
  File "youtube_dl\extractor\generic.pyo", line 1289, in _real_extract
  File "youtube_dl\compat.pyo", line 248, in compat_etree_fromstring
  File "youtube_dl\compat.pyo", line 237, in _XML
  File "xml\etree\ElementTree.pyo", line 1642, in feed
  File "xml\etree\ElementTree.pyo", line 1506, in _raiseerror
ParseError: not well-formed (invalid token): line 12, column 311
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 665, in extract_info
  File "youtube_dl\extractor\common.pyo", line 312, in extract
  File "youtube_dl\extractor\generic.pyo", line 1908, in _real_extract
UnsupportedError: Unsupported URL: http://www.redbull.tv/episodes/AP-1GH4VU4NS21
11/lima

**Comment by voltagex** [comment]
Should I open a separate issue for beta.redbull.tv?

```
PS C:\Users\live\Videos> youtube-dl.exe -v http://beta.redbull.tv/live/AP-1KNHZ1SD11W11/simple-session
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://beta.redbull.tv/live/AP-1KNHZ1SD11W11/simple-session']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.05.10
[debug] Python version 2.7.10 - Windows-8-6.2.9200
[debug] exe versions: ffmpeg 3.0.1, ffprobe 3.0.1, rtmpdump 2.3
[debug] Proxy map: {}
[generic] simple-session: Requesting header
WARNING: Falling back on generic information extractor.
[generic] simple-session: Downloading webpage
[generic] simple-session: Extracting information
ERROR: Unsupported URL: http://beta.redbull.tv/live/AP-1KNHZ1SD11W11/simple-session
Traceback (most recent call last):
  File "youtube_dl\extractor\generic.pyo", line 1393, in _real_extract
  File "youtube_dl\compat.pyo", line 280, in compat_etree_fromstring
  File "youtube_dl\compat.pyo", line 269, in _XML
  File "xml\etree\ElementTree.pyo", line 1642, in feed
  File "xml\etree\ElementTree.pyo", line 1506, in _raiseerror
ParseError: not well-formed (invalid token): line 9, column 625
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 676, in extract_info
  File "youtube_dl\extractor\common.pyo", line 341, in extract
  File "youtube_dl\extractor\generic.pyo", line 2063, in _real_extract
UnsupportedError: Unsupported URL: http://beta.redbull.tv/live/AP-1KNHZ1SD11W11/simple-session
```
