### ISSUE TITLE
The Onion, site support request

### ISSUE THREAD

**Issue by privong** [rg3/youtube-dl#3928]
```
$ youtube-dl --verbose http://www.theonion.com/video/man-wearing-mm-jacket-gods-image,36918/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.theonion.com/video/man-wearing-mm-jacket-gods-image,36918/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.10.05.2
[debug] Python version 3.4.2 - Linux-3.16.4-1-ARCH-x86_64-with-arch
[debug] Proxy map: {}
[generic] man-wearing-mm-jacket-gods-image,36918: Requesting header
WARNING: Falling back on generic information extractor.
[generic] man-wearing-mm-jacket-gods-image,36918: Downloading webpage
[generic] man-wearing-mm-jacket-gods-image,36918: Extracting information
ERROR: Unsupported URL: http://www.theonion.com/video/man-wearing-mm-jacket-gods-image,36918/; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 524, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 193, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/generic.py", line 907, in _real_extract
    raise ExtractorError('Unsupported URL: %s' % url)
youtube_dl.utils.ExtractorError: Unsupported URL: http://www.theonion.com/video/man-wearing-mm-jacket-gods-image,36918/; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

$ youtube-dl --version
2014.10.05.2
```

**Comment by antdude** [comment]
@utack FYI: I opened a new one in my https://github.com/ytdl-org/youtube-dl/issues/22237.
