### ISSUE TITLE
AT&T Tech Channel, site support request

### ISSUE THREAD

**Issue by privong** [rg3/youtube-dl#3938]
Probably low priority, but the AT&T Tech Channel might be useful to have.

```
$ youtube-dl --verbose http://techchannel.att.com/play-video.cfm/2014/1/27/ATT-Archives-The-UNIX-System-Making-Computers-Easier-to-Use
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://techchannel.att.com/play-video.cfm/2014/1/27/ATT-Archives-The-UNIX-System-Making-Computers-Easier-to-Use']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.10.05.2
[debug] Python version 3.4.2 - Linux-3.16.4-1-ARCH-x86_64-with-arch
[debug] Proxy map: {}
[generic] ATT-Archives-The-UNIX-System-Making-Computers-Easier-to-Use: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ATT-Archives-The-UNIX-System-Making-Computers-Easier-to-Use: Downloading webpage
[generic] ATT-Archives-The-UNIX-System-Making-Computers-Easier-to-Use: Extracting information
ERROR: Unsupported URL: http://techchannel.att.com/play-video.cfm/2014/1/27/ATT-Archives-The-UNIX-System-Making-Computers-Easier-to-Use; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 524, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 193, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/generic.py", line 907, in _real_extract
    raise ExtractorError('Unsupported URL: %s' % url)
youtube_dl.utils.ExtractorError: Unsupported URL: http://techchannel.att.com/play-video.cfm/2014/1/27/ATT-Archives-The-UNIX-System-Making-Computers-Easier-to-Use; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
```

**Comment by phihag** [comment]
I believe this issue to be fixed in youtube-dl 2015.01.10.1 and newer. See [our FAQ](https://yt-dl.org/update) if you need help updating.
