### ISSUE TITLE
RTE.ie Player support

### ISSUE THREAD

**Issue by httpless** [rg3/youtube-dl#3953]
Is it possible to get support for the rte.ie player (http://www.rte.ie/player)?   Output from `--verbose` on a freshly updated install to an example video

    $ youtube-dl --verbose http://www.rte.ie/player/se/show/10333418/
    [debug] System config: []
    [debug] User config: []
    [debug] Command-line args: ['--verbose', 'http://www.rte.ie/player/se/show/10333418/']
    [debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
    [debug] youtube-dl version 2014.10.13
    [debug] Python version 2.7.6 - Linux-3.13.0-36-generic-x86_64-with-Ubuntu-14.04-trusty
    [debug] Proxy map: {}
    [generic] 10333418: Requesting header
    WARNING: Falling back on generic information extractor.
    [generic] 10333418: Downloading webpage
    [generic] 10333418: Extracting information
    ERROR: Unsupported URL: http://www.rte.ie/player/se/show/10333418/; please report this issue on https://yt-dl.org/bug . Be sure to call     youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 540, in _real_extract
        doc = parse_xml(webpage)
      File "/usr/local/lib/python2.7/dist-packages/youtube_dl/utils.py", line 1550, in parse_xml
        tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
      File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
        parser.feed(text)
      File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
        self._raiseerror(v)
      File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
        raise err
    ParseError: undefined entity: line 12, column 25
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 524, in extract_info
        ie_result = ie.extract(url)
      File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 193, in extract
        return self._real_extract(url)
      File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 911, in _real_extract
        raise ExtractorError('Unsupported URL: %s' % url)
    ExtractorError: Unsupported URL: http://www.rte.ie/player/se/show/10333418/; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by httpless** [comment]
I've tested this and it appears to be working well. Thank you

**Comment by jaimeMF** [comment]
We forgot to close this issue, @Dineshs91 added support for it.

**Comment by httpless** [comment]
hi @jaimeMF / @Dineshs91   I've noticed some audio problems on downloads, should I create new ticket or is it better to reopen this?

**Comment by jaimeMF** [comment]
Please open a new issue with the output of `youtube-dl --verbose URL`, the player you use and a description of the problem.
