### ISSUE TITLE
[mixcloud] Error with specific url

### ISSUE THREAD

**Issue by jaimeMF** [rg3/youtube-dl#3990]
```
$ youtube-dl 'http://www.mixcloud.com/adambeyer/dcr219-drumcode-radio-live-sam-paganini-live-at-lehmann-club-stuttgart/'
[debug] System config: []
[debug] User config: ['--keep-video', '--write-info-json', '--write-thumbnail', '--verbose']
[debug] Command-line args: ['http://www.mixcloud.com/adambeyer/dcr219-drumcode-radio-live-sam-paganini-live-at-lehmann-club-stuttgart/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.10.18
[debug] Git HEAD: cc98a3f
[debug] Python version 3.4.2 - Darwin-13.4.0-x86_64-i386-64bit
[debug] Proxy map: {}
[mixcloud] adambeyer-dcr219-drumcode-radio-live-sam-paganini-live-at-lehmann-club-stuttgart: Downloading webpage
Traceback (most recent call last):
  File "~/local/bin/youtube-dl", line 4, in <module>
    youtube_dl.main()
  File "youtube_dl/__init__.py", line 431, in main
    _real_main(argv)
  File "youtube_dl/__init__.py", line 421, in _real_main
    retcode = ydl.download(all_urls)
  File "youtube_dl/YoutubeDL.py", line 1067, in download
    self.extract_info(url)
  File "youtube_dl/YoutubeDL.py", line 524, in extract_info
    ie_result = ie.extract(url)
  File "youtube_dl/extractor/common.py", line 193, in extract
    return self._real_extract(url)
  File "youtube_dl/extractor/mixcloud.py", line 64, in _real_extract
    final_song_url = self._get_url(track_id, template_url)
  File "youtube_dl/extractor/mixcloud.py", line 39, in _get_url
    url = template_url % i
TypeError: not all arguments converted during string formatting
```

We are not correctly extracting the preview url.

**Comment by remitamine** [comment]
now, it's working.
```
youtube-dl -v --ignore-config https://www.mixcloud.com/adambeyer/dcr219-drumcode-radio-live-sam-paganini-live-at-lehmann-club-stuttgart/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', '--ignore-config', 'https://www.mixcloud.com/adambeyer/dcr219-drumcode-radio-live-sam-paganini-live-at-lehmann-club-stuttgart/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.07.21
[debug] Python version 3.4.3 - Linux-4.1.2-2-ARCH-x86_64-with-arch-Arch-Linux
[debug] exe versions: ffmpeg 2.7.2, ffprobe 2.7.2, rtmpdump 2.4
[debug] Proxy map: {}
[mixcloud] adambeyer-dcr219-drumcode-radio-live-sam-paganini-live-at-lehmann-club-stuttgart: Downloading webpage
[mixcloud] adambeyer-dcr219-drumcode-radio-live-sam-paganini-live-at-lehmann-club-stuttgart: Trying mp3 URL
[debug] Invoking downloader on 'https://stream18.mixcloud.com/c/originals/c/b/7/4/a9bf-e14a-4cec-98dc-e7346ccd7764.mp3'
[download] Destination: DCR219 - Drumcode Radio Live - Sam Paganini Live At Lehmann Club, Stuttgart-adambeyer-dcr219-drumcode-radio-live-sam-paganini-live-at-lehmann-club-stuttgart.mp3
[download]   3.0% of 150.86MiB at 152.79KiB/s ETA 16:20
```

**Comment by PaTiToMaSteR** [comment]
This still happening in the latest version with youtube, any workaround?

Is it the cache ?

**Comment by PaTiToMaSteR** [comment]
I can confirm with continue_dl = False and rm_cachedir = True doesn't fix the problem. Although change the cache dir and delete the already downloaded data fixed.

I cancel the download with CONTROL+C probably make that problem.
