### ISSUE TITLE
Videos with Viewer Discretion/Verify Controversy crash youtube_dl

### ISSUE THREAD

**Issue by TheBoroer** [rg3/youtube-dl#4016]
Some videos now have the Viewer Discretion prompt (Continue/Cancel) that breaks youtube_dl.

Example Video URL (WITH the prompt):
`http://www.youtube.com/watch?v=EH6pXx5WjVI`

If I add `&bpctr=9999999999` to the end of the video URL and try it out in my browser, it will skip the viewer discretion continue/cancel prompt (even without being logged into YouTube).

If someone could please modify youtube_dl to include that parameter asap that would be much appreciated! Thank you in advance :)

Video URL (WITHOUT the prompt):
`http://www.youtube.com/watch?v=EH6pXx5WjVI&bpctr=9999999999`

Command used:
`./youtube-link -f 140 -v -g http://www.youtube.com/watch?v=EH6pXx5WjVI`

Results:

```
WARNING: unable to extract uploader nickname
WARNING: unable to extract categories; please report this issue on http://yt-dl.org/bug
Traceback (most recent call last):
  File "/usr/lib64/python2.6/runpy.py", line 122, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.6/runpy.py", line 34, in _run_code
    exec code in run_globals
  File "./youtube-link/__main__.py", line 18, in <module>
  File "./youtube-link/youtube_dl/__init__.py", line 431, in main
  File "./youtube-link/youtube_dl/__init__.py", line 421, in _real_main
  File "./youtube-link/youtube_dl/YoutubeDL.py", line 1067, in download
  File "./youtube-link/youtube_dl/YoutubeDL.py", line 524, in extract_info
  File "./youtube-link/youtube_dl/extractor/common.py", line 193, in extract
  File "./youtube-link/youtube_dl/extractor/youtube.py", line 953, in _real_extract
UnboundLocalError: local variable 'ytplayer_config' referenced before assignment
```

**Comment by kiroma** [comment]
It seems this is no longer working. Attempting to download this video: https://www.youtube.com/watch?v=XkEGGLu_fNU results in `ERROR: XkEGGLu_fNU: YouTube said: Unable to extract video data`

**Comment by llacb47** [comment]
@kiroma don't dig up old issues. It's bad and you should feel bad. 
https://github.com/ytdl-org/youtube-dl/issues/26152
