### ISSUE TITLE
pjtv.com support

### ISSUE THREAD

**Issue by kb5won** [rg3/youtube-dl#4021]
I tried to download a video from pjtv.com, but no luck.  The text from the terminal session is pasted below.  If more is needed, please let me know.

aaa@bbbb ~/youtube-dl $ ./youtube-dl --verbose https://www.pjtv.com/?cmd=mpg&mpid=640&acim-id=3030&right-side-bar-category-id=341&top-container-category-id=325&right-side-bar-return-link-params=EZWWCY3SN4WXG33VOJRWKLLUPFYGKPLNMFUW4LLDN5XHIZLOOQWWE3DPMNVSM3LBMNZG6LLTN52XEY3FFVQWIZDJORUW63TBNQWWIYLUME6TMNBQ
[1] 13189
[2] 13190
[3] 13191
[4] 13192
[5] 13193
acim-id=3030: command not found
top-container-category-id=325: command not found
[2]   Done                    mpid=640
right-side-bar-category-id=341: command not found
right-side-bar-return-link-params=EZWWCY3SN4WXG33VOJRWKLLUPFYGKPLNMFUW4LLDN5XHIZLOOQWWE3DPMNVSM3LBMNZG6LLTN52XEY3FFVQWIZDJORUW63TBNQWWIYLUME6TMNBQ: command not found
[2]   Done                    mpid=640
[2]   Done                    mpid=640
[3]   Exit 127                acim-id=3030
[4]-  Exit 127                right-side-bar-category-id=341
[5]+  Exit 127                top-container-category-id=325
aaa@bbbb ~/youtube-dl $ [debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'https://www.pjtv.com/?cmd=mpg']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.10.24
[debug] Python version 2.7.6 - Linux-3.13.0-24-generic-x86_64-with-LinuxMint-17-qiana
[debug] Proxy map: {}
[generic] ?cmd=mpg: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ?cmd=mpg: Downloading webpage
[generic] ?cmd=mpg: Extracting information
ERROR: Unsupported URL: https://www.pjtv.com/?cmd=mpg; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/extractor/generic.py", line 553, in _real_extract
    doc = parse_xml(webpage)
  File "./youtube-dl/youtube_dl/utils.py", line 1550, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: duplicate attribute: line 1, column 510
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 526, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 193, in extract
    return self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/generic.py", line 933, in _real_extract
    raise ExtractorError('Unsupported URL: %s' % url)
ExtractorError: Unsupported URL: https://www.pjtv.com/?cmd=mpg; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

[1]+  Exit 1                  ./youtube-dl --verbose https://www.pjtv.com/?cmd=mpg

**Comment by remitamine** [comment]
urls that contains an ampersand should be quoted https://github.com/rg3/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command.
the url in the issue redirect to https://pjmedia.com/video/.
tested some of the urls in the page, they are working using the generic extractor.
