### ISSUE TITLE
Support request - CTV.ca

### ISSUE THREAD

**Issue by daitod** [rg3/youtube-dl#4077]
Support request - CTV.ca

youtube-dl --verbose http://www.ctv.ca/MarvelsAgentsofShield.aspx

[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.ctv.ca/MarvelsAgentsofShield.aspx']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.10.30
[debug] Python version 2.7.5 - Darwin-13.4.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {'http': 'http://127.0.0.1:8118', u'https': 'http://127.0.0.1:8118'}
[generic] MarvelsAgentsofShield: Requesting header
WARNING: Falling back on generic information extractor.
[generic] MarvelsAgentsofShield: Downloading webpage
[generic] MarvelsAgentsofShield: Extracting information
ERROR: Unsupported URL: http://www.ctv.ca/MarvelsAgentsofShield.aspx; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 581, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1629, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 17, column 129
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 533, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 198, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 962, in _real_extract
    raise ExtractorError('Unsupported URL: %s' % url)
ExtractorError: Unsupported URL: http://www.ctv.ca/MarvelsAgentsofShield.aspx; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by johnku1** [comment]
+1

**Comment by RingoTheDog** [comment]
I am not sure if these are similar under the hood, but I just noticed that you already have an extractor for RDS: 
https://github.com/rg3/youtube-dl/commit/28fb109ed0276e85207966ac925e9885c2ed0e7b

RDS is the french version of TSN: http://www.tsn.ca/video
..both are bellmedia properties.

**Comment by dstftw** [comment]
Both use 9c9media.com for streaming that is [not supported currently](https://github.com/rg3/youtube-dl/blob/28fb109ed0276e85207966ac925e9885c2ed0e7b/youtube_dl/extractor/rds.py#L42).
