### ISSUE TITLE
Support request - giga.de

### ISSUE THREAD

**Issue by xythobuz** [rg3/youtube-dl#4090]
Support request for [giga.de](http://www.giga.de/filme/anime-awesome/trailer/anime-awesome-chihiros-reise-ins-zauberland-das-beste-kommt-zum-schluss/)

```
$ youtube-dl --verbose http://www.giga.de/filme/anime-awesome/trailer/anime-awesome-chihiros-reise-ins-zauberland-das-beste-kommt-zum-schluss/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.giga.de/filme/anime-awesome/trailer/anime-awesome-chihiros-reise-ins-zauberland-das-beste-kommt-zum-schluss/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.11.02.1
[debug] Python version 2.7.6 - Darwin-14.0.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[generic] anime-awesome-chihiros-reise-ins-zauberland-das-beste-kommt-zum-schluss: Requesting header
WARNING: Falling back on generic information extractor.
[generic] anime-awesome-chihiros-reise-ins-zauberland-das-beste-kommt-zum-schluss: Downloading webpage
[generic] anime-awesome-chihiros-reise-ins-zauberland-das-beste-kommt-zum-schluss: Extracting information
[redirect] Following redirect to http://www.giga.de/filme/anime-awesome/trailer/anime-awesome-chihiros-reise-ins-zauberland-das-beste-kommt-zum-schluss/?ModPagespeed=noscript
[generic] ?ModPagespeed=noscript: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ?ModPagespeed=noscript: Downloading webpage
[generic] ?ModPagespeed=noscript: Extracting information
ERROR: Unsupported URL: http://www.giga.de/filme/anime-awesome/trailer/anime-awesome-chihiros-reise-ins-zauberland-das-beste-kommt-zum-schluss/?ModPagespeed=noscript; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/youtube_dl/extractor/generic.py", line 581, in _real_extract
    doc = parse_xml(webpage)
  File "/Library/Python/2.7/site-packages/youtube_dl/utils.py", line 1629, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 61, column 189
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/youtube_dl/YoutubeDL.py", line 533, in extract_info
    ie_result = ie.extract(url)
  File "/Library/Python/2.7/site-packages/youtube_dl/extractor/common.py", line 198, in extract
    return self._real_extract(url)
  File "/Library/Python/2.7/site-packages/youtube_dl/extractor/generic.py", line 962, in _real_extract
    raise ExtractorError('Unsupported URL: %s' % url)
ExtractorError: Unsupported URL: http://www.giga.de/filme/anime-awesome/trailer/anime-awesome-chihiros-reise-ins-zauberland-das-beste-kommt-zum-schluss/?ModPagespeed=noscript; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
```

**Comment by dstftw** [comment]
giga games will be supported in the next version of youtube-dl. Thanks for the report.

**Comment by phihag** [comment]
I believe this issue to be fixed in youtube-dl 2015.01.05 or newer. See [our FAQ](https://yt-dl.org/update) if you need help updating.

**Comment by dstftw** [comment]
@phihag not really, 0df2dea happened after 2015.01.05.1 has been released.

**Comment by phihag** [comment]
Oops, sorry about that. 2015.01.07 does definitely include the changes.

**Comment by phihag** [comment]
youtube-dl 2015.01.08 does include them. See [our FAQ](https://yt-dl.org/update) if you need help updating.
