### ISSUE TITLE
Unable to download thatguywiththeglasses.com's videos.

### ISSUE THREAD

**Issue by antdude** [rg3/youtube-dl#4106]
Example:

$ youtube-dl -v http://thatguywiththeglasses.com/videolinks/thatguywiththeglasses/nostalgia-critic/45455-rise-of-the-commercials
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://thatguywiththeglasses.com/videolinks/thatguywiththeglasses/nostalgia-critic/45455-rise-of-the-commercials']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.11.02.1
[debug] Python version 2.7.3 - Linux-3.2.0-4-amd64-x86_64-with-debian-7.7
[debug] exe versions: avconv 1.0.10, avprobe 1.0.10, ffmpeg 1.0.10, ffprobe 1.0.10
[debug] Proxy map: {}
[generic] 45455-rise-of-the-commercials: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 45455-rise-of-the-commercials: Downloading webpage
[generic] 45455-rise-of-the-commercials: Extracting information
[BlipTV] gbk7g7GfSAI: Resolving lookup id
ERROR: Unable to extract video_id; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 533, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 198, in extract
    return self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/bliptv.py", line 78, in _real_extract
    video_id = self._search_regex(r'data-episode-id="([0-9]+)', info_page, 'video_id')
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 432, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video_id; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

Thank you in advance. :)

**Comment by robin007bond** [comment]
The URLs have changed, the video is now on:
http://channelawesome.com/nostalgia-critic-rise-of-the-commercials/

```
 youtube-dl -v --test 'http://channelawesome.com/nostalgia-critic-rise-of-the-commercials/'
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', '--test', 'http://channelawesome.com/nostalgia-critic-rise-of-the-commercials/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.02.06
[debug] Python version 3.4.2 - Linux-3.18.6-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 2.5.3, ffprobe 2.5.3, rtmpdump 2.4
[debug] Proxy map: {}
[generic] nostalgia-critic-rise-of-the-commercials: Requesting header
[generic] nostalgia-critic-rise-of-the-commercials: Downloading webpage
[generic] nostalgia-critic-rise-of-the-commercials: Extracting information
[BlipTV] gbk7g7GfSAI: Resolving lookup id
[BlipTV] 7098212: Downloading video RSS
[BlipTV] 7081529: Resolving URL for Source
[BlipTV] 7081529: Resolving URL for Blip LD
[BlipTV] 7081529: Resolving URL for Blip SD
[BlipTV] 7081529: Resolving URL for Blip HD 720
[debug] Invoking downloader on 'http://j-mirror.video1.blip.tv/NostalgiaCritic-NCRiseOfTheCommercials327.mp4?ir=563518&sr=14010'
[download] Destination: NC - Rise of the Commercials-7081529.mp4
[download] 100% of 10.00KiB in 00:00
```
Worked like a charm.

**Comment by TRox1972** [comment]
@rrooij Doesn't seem to work anymore.  The video is now a Vessel embed.

**Comment by antdude** [comment]
Trox1972: Just click on its Vessel watermark to go to its server like https://www.vessel.com/videos/VgLyMhhIk ... It will work.

**Comment by TRox1972** [comment]
Thanks @antdude. Guess we should add/extend support for Vessel embeds.

**Comment by antdude** [comment]
Trox1972: Uh, but youtube-dl can download already?

**Comment by TRox1972** [comment]
@antdude youtube-dl works fine for downloading Vessel-videos from vessel.com. Adding support for Vessel embeds would mean that youtube-dl would detect Vessel videos on e.g. channelawesome.com and then download them.

**Comment by antdude** [comment]
@TRox1972 Ah OK and thanks. :D
