### ISSUE TITLE
[YouTube] ERROR: Unable to extract age gate player URL

### ISSUE THREAD

**Issue by TheBoroer** [rg3/youtube-dl#4108]
Getting that error when trying to download this video: `http://www.youtube.com/watch?v=6kLq3WMV1nU`

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.youtube.com/watch?v=6kLq3WMV1nU']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.11.04
[debug] Python version 2.6.6 - Linux-3.10.23-xxxx-std-ipv6-64-x86_64-with-centos-6.5-Final
[debug] exe versions: ffmpeg 0.6.5, ffprobe 0.6.5
[debug] Proxy map: {}
[youtube] Confirming age
[youtube] 6kLq3WMV1nU: Downloading webpage
[youtube] 6kLq3WMV1nU: Downloading video info webpage
[youtube] 6kLq3WMV1nU: Refetching age-gated info webpage
[youtube] 6kLq3WMV1nU: Extracting video information
ERROR: Unable to extract age gate player URL; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "./youtube-link/youtube_dl/extractor/youtube.py", line 841, in _real_extract
    raise ValueError('Could not find vevo ID')
ValueError: Could not find vevo ID
Traceback (most recent call last):
  File "./youtube-link/youtube_dl/YoutubeDL.py", line 536, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-link/youtube_dl/extractor/common.py", line 199, in extract
    return self._real_extract(url)
  File "./youtube-link/youtube_dl/extractor/youtube.py", line 909, in _real_extract
    video_webpage, 'age gate player URL')
  File "./youtube-link/youtube_dl/extractor/common.py", line 436, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract age gate player URL; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
```

**Comment by phihag** [comment]
I believe this issue to be fixed in youtube-dl 2015.01.05 or newer. See [our FAQ](https://yt-dl.org/update) if you need help updating.

**Comment by joecrayne** [comment]
Seems broken again.

> $ youtube-dl -t 'https://www.youtube.com/watch?v=tC1Mk5Ge_XA'
> [youtube] tC1Mk5Ge_XA: Downloading webpage
> [youtube] tC1Mk5Ge_XA: Downloading embed webpage
> [youtube] tC1Mk5Ge_XA: Refetching age-gated info webpage
> ERROR: tC1Mk5Ge_XA: YouTube said: Please sign in to view this video.

**Comment by 0xced** [comment]
The error seems to have changed.
> $ youtube-dl -t 'https://www.youtube.com/watch?v=tC1Mk5Ge_XA'
[youtube] tC1Mk5Ge_XA: Downloading webpage
[youtube] tC1Mk5Ge_XA: Downloading video info webpage
ERROR: tC1Mk5Ge_XA: YouTube said: This video has been removed by the user.

**Comment by jaimeMF** [comment]
@joecrayne I can't watch the video on a browser: `This video has been removed by the user`(which is also the message I get with youtube-dl).
