### ISSUE TITLE
Unicode failure with a ex.ua URL (stack trace)

### ISSUE THREAD

**Issue by bubbleguuum** [rg3/youtube-dl#4111]
./youtube-dl http://ex.ua/get/70679750
[generic] 70679750: Requesting header
./youtube-dl/youtube_dl/extractor/generic.py:541: UnicodeWarning: Unicode unequal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "./youtube-dl/__main__.py", line 18, in <module>
  File "./youtube-dl/youtube_dl/__init__.py", line 349, in main
  File "./youtube-dl/youtube_dl/__init__.py", line 339, in _real_main
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 1082, in download
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 533, in extract_info
  File "./youtube-dl/youtube_dl/extractor/common.py", line 198, in extract
  File "./youtube-dl/youtube_dl/extractor/generic.py", line 542, in _real_extract
  File "./youtube-dl/youtube_dl/extractor/generic.py", line 425, in report_following_redirect
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 68: ordinal not in range(128)

------------

This URL redirects to another URL with weird characters but if you open it in Firefox, it works:

 wget -S --spider http://ex.ua/get/70679750
Spider mode enabled. Check if remote file exists.
--2014-11-05 13:35:33--  http://ex.ua/get/70679750
Resolving ex.ua (ex.ua)... 77.120.115.178
Connecting to ex.ua (ex.ua)|77.120.115.178|:80... connected.
HTTP request sent, awaiting response...
  HTTP/1.1 302 Moved
  Server: nginx/1.6.2
  Date: Wed, 05 Nov 2014 12:35:33 GMT
  Connection: keep-alive
  Location: http://fs75.www.ex.ua/get/7e75b1f11f1f5110030129224baa5326/70679750/Камеди%20Клаб%20в%20Юрмале.%20Сезон%201.%20Выпуск%202.flv
Location: http://fs75.www.ex.ua/get/7e75b1f11f1f5110030129224baa5326/70679750/%D0%9A%D0%B0%D0%BC%D0%B5%D0%B4%D0%B8%20%D0%9A%D0%BB%D0%B0%D0%B1%20%D0%B2%20%D0%AE%D1%80%D0%BC%D0%B0%D0%BB%D0%B5.%20%D0%A1%D0%B5%D0%B7%D0%BE%D0%BD%201.%20%D0%92%D1%8B%D0%BF%D1%83%D1%81%D0%BA%202.flv [following]
Spider mode enabled. Check if remote file exists.

**Comment by dstftw** [comment]
Works fine with latest version.
