### ISSUE TITLE
Bug report - cobra.be - AttributeError: 'NoneType' object has no attribute 'text'

### ISSUE THREAD

**Issue by midas02** [rg3/youtube-dl#4121]
Hi,

Normally the software should be able to download from cobra.be. For this particular video, I'm getting an attribute error though:
>>>youtube-dl.exe -v http://cobra.be/permalink/1.1427340
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://cobra.be/permalink/1.1427340']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2014.11.04
[debug] Python version 2.7.8 - Windows-XP-5.1.2600-SP3
[debug] exe versions: ffmpeg N-58869-, ffprobe N-63644-, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 1: Requesting header
[redirect] Following redirect to http://cobra.be/cm/cobra/videozone/archief/kunsten/1.1427340
[VRT] 1.1427340: Downloading webpage
[VRT] 1427340: Downloading m3u8 information
[VRT] 1427340: Downloading f4m manifest
[debug] Invoking downloader on u'http://iphone.streampower.be/vrtnieuws_nogeo/_definst_/2012/09/113239822AFL0004GO470244
0.urlMP4_H.264.m4v/manifest.f4m'
[download] Downloading f4m manifest
[download] Destination: Goudvis over Berlinde De Bruyckere-1427340.flv
Traceback (most recent call last):
  File "__main__.py", line 18, in <module>
  File "youtube_dl\__init__.pyo", line 351, in main
  File "youtube_dl\__init__.pyo", line 341, in _real_main
  File "youtube_dl\YoutubeDL.pyo", line 1085, in download
  File "youtube_dl\YoutubeDL.pyo", line 547, in extract_info
  File "youtube_dl\YoutubeDL.pyo", line 600, in process_ie_result
  File "youtube_dl\YoutubeDL.pyo", line 547, in extract_info
  File "youtube_dl\YoutubeDL.pyo", line 593, in process_ie_result
  File "youtube_dl\YoutubeDL.pyo", line 861, in process_video_result
  File "youtube_dl\YoutubeDL.pyo", line 1055, in process_info
  File "youtube_dl\YoutubeDL.pyo", line 1031, in dl
  File "youtube_dl\downloader\common.pyo", line 292, in download
  File "youtube_dl\downloader\f4m.pyo", line 248, in real_download
AttributeError: 'NoneType' object has no attribute 'text'

Thanks for having a look into it.

Rgds,
Midas

**Comment by midas02** [comment]
The Cobra.be website is no longer being maintained, so this issue can be ignored.
