### ISSUE TITLE
bbc.co.uk/music/ support

### ISSUE THREAD

**Issue by canavan** [rg3/youtube-dl#4143]
Apparently, the BBC launched a new site. Please add support for bbc.co.uk/music/ support

youtube-dl  --verbose http://www.bbc.co.uk/music/clips/p02b9vkd
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.bbc.co.uk/music/clips/p02b9vkd']
[debug] Encodings: locale ISO8859-1, fs ISO8859-1, out ISO8859-1, pref ISO8859-1
[debug] youtube-dl version 2014.11.04
[debug] Python version 2.7.6 - IRIX64-6.5-IP35-mips-n32bit-ELF
[debug] exe versions: ffmpeg UNKNOWN, ffprobe UNKNOWN, rtmpdump 2.2b
[debug] Proxy map: {}
[generic] p02b9vkd: Requesting header
WARNING: Falling back on generic information extractor.
[generic] p02b9vkd: Downloading webpage
[generic] p02b9vkd: Extracting information
ERROR: Unsupported URL: http://www.bbc.co.uk/music/clips/p02b9vkd; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/nekoware/bin/youtube-dl/youtube_dl/extractor/generic.py", line 596, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/nekoware/bin/youtube-dl/youtube_dl/utils.py", line 1311, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/nekoware/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/nekoware/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/nekoware/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: mismatched tag: line 29, column 5579
Traceback (most recent call last):
  File "/usr/nekoware/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 536, in extract_info
    ie_result = ie.extract(url)
  File "/usr/nekoware/bin/youtube-dl/youtube_dl/extractor/common.py", line 199, in extract
    return self._real_extract(url)
  File "/usr/nekoware/bin/youtube-dl/youtube_dl/extractor/generic.py", line 977, in _real_extract
    raise ExtractorError('Unsupported URL: %s' % url)
ExtractorError: Unsupported URL: http://www.bbc.co.uk/music/clips/p02b9vkd; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by dstftw** [comment]
BBC Music Clips will be supported in the next version. Thanks for the report.

**Comment by canavan** [comment]
Verified working with 2015.01.03. 

Thanks!
