### ISSUE TITLE
Error downloading GDC video

### ISSUE THREAD

**Issue by odelalleau** [rg3/youtube-dl#4170]
Actually it's an audio file, not a video. Verbose output is below. Note that downloading free content (audio & video) seems to work. Just in case it might be a problem, there is a `*` character in my password (which I can't change). I'm using quotes on the command line (`-p "my*password"`)

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', '-u', u'PRIVATE', '-p', u'PRIVATE', 'http://ww
w.gdcvault.com/play/515/Challenging-Everyone-Dynamic-Difficulty']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2014.11.12.1
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {'http': 'http://proxy-mtl.ubisoft.org:3128', u'https': 'http
://proxy-mtl.ubisoft.org:3128'}
[GDCVault] 515: Downloading webpage
[GDCVault] 515: Logging in
[GDCVault] 515: Getting authenticated video page
[GDCVault] 515: Logging out
ERROR: Unable to extract xml root; please report this issue on https://yt-dl.org
/bug . Be sure to call youtube-dl with the --verbose flag and include its comple
te output. Make sure you are using the latest version; type  youtube-dl -U  to u
pdate.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 536, in extract_info
  File "youtube_dl\extractor\common.pyo", line 199, in extract
  File "youtube_dl\extractor\gdcvault.pyo", line 145, in _real_extract
  File "youtube_dl\extractor\common.pyo", line 446, in _html_search_regex
  File "youtube_dl\extractor\common.pyo", line 436, in _search_regex
RegexNotFoundError: Unable to extract xml root; please report this issue on http
s://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and inclu
de its complete output. Make sure you are using the latest version; type  youtub
e-dl -U  to update.
```

**Comment by gl-bars** [comment]
I'm getting error 500 when trying to download non-free video:
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-u', u'PRIVATE', '-p', u'PRIVATE', '--verbose', 'http://gdcvault.com/play/1020653/Math-for-Game-Programmers-Dictionary']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.03.03.1
[debug] Python version 2.7.6 - Linux-3.16.0-30-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: rtmpdump 2.4
[debug] Proxy map: {}
[GDCVault] 1020653: Downloading webpage
[GDCVault] 1020653: Logging in
ERROR: Unable to download webpage: HTTP Error 500: Internal Server Error (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "./youtube-dl/youtube_dl/extractor/common.py", line 314, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 1674, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
```

**Comment by ENDERthegamer** [comment]
I am also running into the same problem while attempting to download non-free video from GDC Vault. Has anyone discovered a solution to this?

**Comment by 3id0** [comment]
Hello, I'm getting an "Unsupported URL" error with (I think) a free GDC Vault video, with both URL types 'http://gdcvault.com/play/1020791/' and 'http://evt.dispeak.com/ubm/gdc/sf14/player.html?xml=201403828316_AJKF.xml&token=3c6c000ab0766078310c'.
Here's my verbose output for the last one :
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://evt.dispeak.com/ubm/gdc/sf14/player.html?xml=201403828316_AJKF.xml&token=3c6c000ab0766078310c', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.03.15
[debug] Python version 2.7.2 - Darwin-12.5.0-x86_64-i386-64bit
[debug] exe versions: rtmpdump 2.4
[debug] Proxy map: {}
[generic] player.html?xml=201403828316_AJKF: Requesting header
WARNING: Falling back on generic information extractor.
[generic] player.html?xml=201403828316_AJKF: Downloading webpage
[generic] player.html?xml=201403828316_AJKF: Extracting information
ERROR: Unsupported URL: http://evt.dispeak.com/ubm/gdc/sf14/player.html?xml=201403828316_AJKF.xml&token=3c6c000ab0766078310c
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 654, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 275, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1283, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://evt.dispeak.com/ubm/gdc/sf14/player.html?xml=201403828316_AJKF.xml&token=3c6c000ab0766078310c
```

**Comment by jaimeMF** [comment]
@3id0 your issue is unrelated, please [open a new issue](https://github.com/rg3/youtube-dl/issues/new)

**Comment by Wribbe** [comment]
Got the same error on a free video I wanted to watch through mpv, same result when running youtube-dl bare against it.

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.gdcvault.com/play/1025784/Designing-Path-of-Exile-to']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.04.07
[debug] Python version 3.7.3 (CPython) - Linux-5.0.2-arch1-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 4.1.2, ffprobe 4.1.2, rtmpdump 2.4
[debug] Proxy map: {}
[GDCVault] Designing-Path-of-Exile-to: Downloading webpage
WARNING: [GDCVault] It looks like http://www.gdcvault.com/play/1025784 requires a login. Try specifying a username and password and try again.
WARNING: [GDCVault] Could not login.
ERROR: Unable to extract xml filename; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 529, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/gdcvault.py", line 166, in _real_extract
    start_page, 'xml filename')
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 1013, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 1004, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract xml filename; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
