### ISSUE TITLE
RegexNotFoundError: Unable to extract Initial JS player signature function name

### ISSUE THREAD

**Issue by speed-gh** [rg3/youtube-dl#4175]
(just performed 'pip install --upgrade youtube-dl' and still have this problem afterwards)

youtube-dl -F --verbose https://www.youtube.com/watch?v=HBh17_dmaFw
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-F', '--verbose', 'https://www.youtube.com/watch?v=HBh17_dmaFw']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.11.12.1
[debug] Python version 2.7.8 - Linux-3.16.0-24-generic-i686-with-Ubuntu-14.10-utopic
[debug] exe versions: avconv 11-6, avprobe 11-6, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] Confirming age
[youtube] HBh17_dmaFw: Downloading webpage
[youtube] HBh17_dmaFw: Downloading video info webpage
[youtube] HBh17_dmaFw: Extracting video information
[youtube] HBh17_dmaFw: Encrypted signatures detected.
[youtube] {43} signature length 45.43, html5 player en_US-vfln6g5Eq
[youtube] HBh17_dmaFw: Downloading js player vfln6g5Eq
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 539, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 453, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 514, in _parse_sig_js
    'Initial JS player signature function name')
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 436, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
 (caused by RegexNotFoundError(u'Unable to extract \x1b[0;34mInitial JS player signature function name\x1b[0m; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.',)); please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 539, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 453, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 514, in _parse_sig_js
    'Initial JS player signature function name')
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 436, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 536, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 199, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 934, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 549, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 539, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 453, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 514, in _parse_sig_js
    'Initial JS player signature function name')
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 436, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
 (caused by RegexNotFoundError(u'Unable to extract \x1b[0;34mInitial JS player signature function name\x1b[0m; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.',)); please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by akautsar** [comment]
Hello,

I have the same error above with below information (youtube-dl version (2016.10.19)):

[pluralsight] Downloading login page
[pluralsight] Logging in as akautsar
[pluralsight] csharp-language-internals-part2-m1-0: Downloading webpage
ERROR: Unable to extract initial state; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
File "C:\Users\dst\AppData\Roaming\Build archive\youtubedl\rg3\tmpv25gpk4f\build\youtube_dl\YoutubeDL.py", line 694, in extract_info
File "C:\Users\dst\AppData\Roaming\Build archive\youtubedl\rg3\tmpv25gpk4f\build\youtube_dl\extractor\common.py", line 356, in extract
File "C:\Users\dst\AppData\Roaming\Build archive\youtubedl\rg3\tmpv25gpk4f\build\youtube_dl\extractor\pluralsight.py", line 170, in_real_extract
File "C:\Users\dst\AppData\Roaming\Build archive\youtubedl\rg3\tmpv25gpk4f\build\youtube_dl\extractor\common.py", line 659, in_search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract initial state; please report this issue on https://yt-dl.org/bug.
Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Thanks.

**Comment by yan12125** [comment]
@akautsar That's a different bug, see #10972

**Comment by electronicous** [comment]
Getting this in 2019 but only with certain video(s).

**Comment by remitamine** [comment]
@electronicous always use the latest version.
