### ISSUE TITLE
Crunchyroll: UnicodeDecodeError: 'ascii' codec can't decode byte

### ISSUE THREAD

**Issue by yldrx** [rg3/youtube-dl#4181]
When downloading a video from Crunchyroll, I encoutered this problem.

**Cmdline**: youtube-dl 'http://www.crunchyroll.com/case-closed/episode-754-the-tragedy-of-the-red-woman-steam-663019?p360=1' -F

**version**: 2014.11.13

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://www.crunchyroll.com/case-closed/episode-754-the-tragedy-of-the-red-woman-steam-663019?p360=1', '-F', '--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.11.13
[debug] Python version 2.7.3
[debug] exe versions: ffmpeg 0.8.12, ffprobe 0.8.12
[debug] Proxy map: {'http': 'http://127.0.0.1:4324', u'https': 'http://127.0.0.1:4324'}
[Crunchyroll] 663019: Downloading webpage
[Crunchyroll] 663019: Downloading media info
[Crunchyroll] 663019: Downloading media info for 360p
[Crunchyroll] 663019: Downloading media info for 480p
[Crunchyroll] 663019: Downloading media info for 720p
[Crunchyroll] 663019: Downloading media info for 1080p
[Crunchyroll] 663019: Downloading subtitles for English (US)
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 18, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 351, in main

  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 341, in _real_main

  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1094, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 536, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 199, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/crunchyroll.py", line 262, in _real_extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/crunchyroll.py", line 108, in _decrypt_subtitles
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 847, in intlist_to_bytes
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 0: ordinal not in range(128)
```
## Analysis

I've taken a look at the `intlist_to_bytes` function with my limited python knowledge, but was not able to fix the issue:
Things such as trying to set an encoding (utf-8) did not work out, and only changed the error, persumably because the bytes are consumed one by one by the chr function.

Also changing the function to essentially a `return bytes(xs)` did not work out, as the zlib.decode in the `_decrypt_subtitles` failed to work.

I'm not at all knowledgeable in python, but I think something is deep wrong with the `intlist_to_bytes` function. it should be an easy built-in python function, and should work with byte-strings or something. But who am I to say that. :)

Can you take a look at this?

**Comment by DragonNeos** [comment]
This issue seems to still occur on the latest version of youtube-dl (2015.03.28). Here is the output:

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'-f', u'360p', u'http://www.crunchyroll.com/
fairy-tail/episode-50-the-lightning-man-677437']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.03.28
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-71182-g5cba529, ffprobe N-71182-g5cba529, rtmpdum
p 2.4
[debug] Proxy map: {}
[Crunchyroll] 677437: Downloading webpage
[Crunchyroll] 677437: Downloading media info
[Crunchyroll] 677437: Downloading media info for 360p
[Crunchyroll] 677437: Downloading media info for 480p
[Crunchyroll] 677437: Downloading media info for 720p
[Crunchyroll] 677437: Downloading media info for 720p
[Crunchyroll] 677437: Downloading media info for 1080p
[Crunchyroll] 677437: Downloading media info for 1080p
[debug] Invoking downloader on 'rtmpe://cp150757.edgefcs.net/ondemand/?auth=daEd
haya7c8bidkaHc1asdAazdXb_amdQc8-bvg5B4-dHa-sAHwusHBFxu&aifp=0009&slist=c1/s/ve17
46531/video.mp4'
[download] Destination: Fairy Tail Series 2 Episode 50 - The Lightning Man-67743
7.flv
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "youtube_dl\__init__.pyo", line 408, in main
  File "youtube_dl\__init__.pyo", line 398, in _real_main
  File "youtube_dl\YoutubeDL.pyo", line 1446, in download
  File "youtube_dl\YoutubeDL.pyo", line 662, in extract_info
  File "youtube_dl\YoutubeDL.pyo", line 708, in process_ie_result
  File "youtube_dl\YoutubeDL.pyo", line 1150, in process_video_result
  File "youtube_dl\YoutubeDL.pyo", line 1379, in process_info
  File "youtube_dl\YoutubeDL.pyo", line 1354, in dl
  File "youtube_dl\downloader\common.pyo", line 341, in download
  File "youtube_dl\downloader\rtmp.pyo", line 162, in real_download
UnicodeDecodeError: 'ascii' codec can't decode byte 0x96 in position 31: ordinal
 not in range(128)
