### ISSUE TITLE
Unsupported URL eonline

### ISSUE THREAD

**Issue by lolobo** [rg3/youtube-dl#4191]
Not sure if this is due to credentials that are/can not be passed to the site. Reviewed help to check for a solution. Will look through some other issue requests.

MacBook-Pro:~ LOLobo$ youtube-dl --version
2014.11.13.3
MacBook-Pro:~ LOLobo$ youtube-dl -v "http://www.eonline.com/now/full-episode/whats-that-racquet/355854403525"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.eonline.com/now/full-episode/whats-that-racquet/355854403525']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.11.13.3
[debug] Python version 2.7.6 - Darwin-14.0.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.4.3, ffprobe 2.4.3
[debug] Proxy map: {}
[generic] 355854403525: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 355854403525: Downloading webpage
[generic] 355854403525: Extracting information
ERROR: Unsupported URL: http://www.eonline.com/now/full-episode/whats-that-racquet/355854403525; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 609, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1307, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 112, column 73
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 536, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 199, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 996, in _real_extract
    raise ExtractorError('Unsupported URL: %s' % url)
ExtractorError: Unsupported URL: http://www.eonline.com/now/full-episode/whats-that-racquet/355854403525; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by yan12125** [comment]
Superseded by #6198
