### ISSUE TITLE
site support request: gazeta.ru

### ISSUE THREAD

**Issue by spvkgn** [rg3/youtube-dl#4222]
Can you please add support, example url http://www.gazeta.ru/video/main/zadaite_vopros_vladislavu_yurevichu.shtml
```
youtube-dl -vg http://www.gazeta.ru/video/main/zadaite_vopros_vladislavu_yurevichu.shtml[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-vg', 'http://www.gazeta.ru/video/main/zadaite_vopros_vladislavu_yurevichu.shtml']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.11.16
[debug] Python version 2.7.3 - Linux-3.2.0-69-generic-pae-i686-with-LinuxMint-13-maya
[debug] exe versions: ffmpeg 2.4.2, ffprobe 2.4.2, rtmpdump 2.4
[debug] Proxy map: {}
WARNING: Falling back on generic information extractor.
ERROR: Unsupported URL: http://www.gazeta.ru/video/main/zadaite_vopros_vladislavu_yurevichu.shtml; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 609, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1319, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1301, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1643, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1507, in _raiseerror
    raise err
ParseError: undefined entity: line 81, column 19
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 536, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 199, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 996, in _real_extract
    raise ExtractorError('Unsupported URL: %s' % url)
ExtractorError: Unsupported URL: http://www.gazeta.ru/video/main/zadaite_vopros_vladislavu_yurevichu.shtml; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
```

**Comment by naglis** [comment]
Support for gazeta.ru should be available in the next release of youtube-dl. Thanks for the report!
