### ISSUE TITLE
Latest Version of youtube-dl gives Python errors

### ISSUE THREAD

**Issue by eddmy** [rg3/youtube-dl#4223]
Upgrading with
$ youtube-dl -U
breakes something...
$ youtube-dl 
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/bin/youtube-dl/__main__.py", line 18, in <module>
  File "/usr/bin/youtube-dl/youtube_dl/**init**.py", line 351, in main
  File "/usr/bin/youtube-dl/youtube_dl/**init**.py", line 60, in _real_main
  File "/usr/bin/youtube-dl/youtube_dl/options.py", line 122, in parseOpts
  File "/usr/lib64/python2.7/optparse.py", line 1018, in add_option
    raise TypeError, "invalid arguments"
TypeError: invalid arguments

Do I have to upgrade Python ?

**Comment by kimnkhan** [comment]
I'm having same problem still with latest youtube-dl. I have Ubuntu 15.10 64bit
Here is my log with -v option:
youtube-dl -v https://youtu.be/aPw1M_Ehg94
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://youtu.be/aPw1M_Ehg94']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.12.14
[debug] Python version 2.7.10 - Linux-3.14.32-xxxx-grs-ipv6-64-x86_64-with-Ubuntu-15.10-wily
[debug] exe versions: ffmpeg 2.7.5-0ubuntu0.15.10.1, ffprobe 2.7.5-0ubuntu0.15.10.1
[debug] Proxy map: {}
[youtube] aPw1M_Ehg94: Downloading webpage
[youtube] aPw1M_Ehg94: Downloading video info webpage
WARNING: unable to download video info webpage: HTTP Error 402: Payment Required
WARNING: unable to download video info webpage: HTTP Error 402: Payment Required
WARNING: unable to download video info webpage: HTTP Error 402: Payment Required
WARNING: unable to download video info webpage: HTTP Error 402: Payment Required
WARNING: unable to download video info webpage: HTTP Error 402: Payment Required
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 465, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 455, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1986, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 784, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 437, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1599, in _real_extract
TypeError: argument of type 'NoneType' is not iterable

But if I run the same youtube video on a different server I don't get the same error. 

Please note that Ubuntu 15.10 has python version 3:
#python3 -V
Python 3.4.3+
