### ISSUE TITLE
Failure on adaptive streaming video from WDR mediathek

### ISSUE THREAD

**Issue by mschilling007** [rg3/youtube-dl#4242]
Unfortunately downloading this videos fails:

``` 
ms@uvps:~/tmp/youtube-dl$ youtube-dl --verbose http://www1.wdr.de/mediathek/video/sendungen/quarks_und_co/videoichbindochnochda100.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www1.wdr.de/mediathek/video/sendungen/quarks_und_co/videoichbindochnochda100.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.11.16
[debug] Python version 2.7.3 - Linux-3.2.0-4-686-pae-i686-with-debian-7.7
[debug] exe versions: rtmpdump 2.4
[debug] Proxy map: {}
[WDR] mediathek/video/sendungen/quarks_und_co/videoichbindochnochda100: Downloading webpage
[download] Downloading playlist: mediathek/video/sendungen/quarks_und_co/videoichbindochnochda100
[WDR] playlist mediathek/video/sendungen/quarks_und_co/videoichbindochnochda100: Collected 1 video ids (downloading 1 of them)
[download] Downloading video #1 of 1
[WDR] mediathek/video/sendungen/quarks_und_co/videoichbindochnochda100: Downloading webpage
[debug] Invoking downloader on u'http://adaptiv.wdr.de/z/medstdp/ww/fsk0/57/572243/,572243_6043518,572243_6043519,572243_6043520,572243_6043521,.mp4.csmil/manifest.f4m?hdcore=3.2.0&plugin=aasp-3.2.0.77.18'
[download] Downloading f4m manifest
[download] Destination: Quarks & Co - Ich bin doch noch da - Leben im Wachkoma-mdb-572243.flv
[download]  42.7% of 504.96MiB at     ---b/s ETA 08:36ERROR: unable to download video data: timed out
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1064, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1040, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 292, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/f4m.py", line 306, in real_download
    success = http_dl.download(frag_filename, {'url': url})
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 292, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 64, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1298, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 401, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 419, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 379, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1211, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1034, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 407, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 365, in _read_status
    line = self.fp.readline()
  File "/usr/lib/python2.7/socket.py", line 447, in readline
    data = self._sock.recv(self._rbufsize)
timeout: timed out

ms@uvps:~/tmp/youtube-dl$
```

**Comment by yan12125** [comment]
Closing as this video is gone. Most likely it's a network issue. Feel free to open new issues if problems are still.
