### ISSUE TITLE
[Request] support for old npo.nl Silverlight video-streams

### ISSUE THREAD

**Issue by Reino17** [rg3/youtube-dl#4276]
```
youtube-dl.exe -vF http://www.npo.nl/de-nieuwe-mens-deel-1/21-07-2010/WO_VPRO_043706
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-vF', 'http://www.npo.nl/de-nieuwe-mens-deel-1/21-07-2010WO_VPR
O_043706']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2014.11.20
[debug] Python version 2.7.8 - Windows-XP-5.1.2600-SP3
[debug] exe versions: ffmpeg N-65810-
[debug] Proxy map: {}
[npo.nl] WO_VPRO_043706: Downloading JSON metadata
[npo.nl] WO_VPRO_043706: Downloading token
Traceback (most recent call last):
  File "__main__.py", line 18, in <module>
  File "youtube_dl\__init__.pyo", line 356, in main
  File "youtube_dl\__init__.pyo", line 346, in _real_main
  File "youtube_dl\YoutubeDL.pyo", line 1094, in download
  File "youtube_dl\YoutubeDL.pyo", line 536, in extract_info
  File "youtube_dl\extractor\common.pyo", line 199, in extract
  File "youtube_dl\extractor\npo.pyo", line 60, in _real_extract
  File "youtube_dl\extractor\npo.pyo", line 78, in _get_info
KeyError: u'pubopties'
```

Firefox's webconsole detects
http://cgi.omroep.nl/cgi-bin/streams?/tv/vpro/GE/bb.20060421.asf?title=De%20nieuwe%20mens%20-%20Deel%201
which downloads as **streams.wmv** and contains:

``` xml
<ASX version = "3.0">
<ENTRY>
<Ref href = "mms://hurley.omroep.nl/public/ug-od/media6/ru_14/ap/media/tv/vpro/GE/bb.2006042
1.asf?wmt=5470f7cd&wmhash=7c7d45ac"/>
<title>De nieuwe mens - Deel 1</title>
</ENTRY>

</ASX>
```

---

```
youtube-dl.exe -vF http://www.npo.nl/valentijn/15-05-2013/WO_VARA_010361
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-vF', 'http://www.npo.nl/valentijn/15-05-2013/WO_VARA_010361']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2014.11.20
[debug] Python version 2.7.8 - Windows-XP-5.1.2600-SP3
[debug] exe versions: ffmpeg N-65810-
[debug] Proxy map: {}
[npo.nl] WO_VARA_010361: Downloading JSON metadata
[npo.nl] WO_VARA_010361: Downloading token
Traceback (most recent call last):
  File "__main__.py", line 18, in <module>
  File "youtube_dl\__init__.pyo", line 356, in main
  File "youtube_dl\__init__.pyo", line 346, in _real_main
  File "youtube_dl\YoutubeDL.pyo", line 1094, in download
  File "youtube_dl\YoutubeDL.pyo", line 536, in extract_info
  File "youtube_dl\extractor\common.pyo", line 199, in extract
  File "youtube_dl\extractor\npo.pyo", line 60, in _real_extract
  File "youtube_dl\extractor\npo.pyo", line 78, in _get_info
KeyError: u'pubopties'
```

Firefox's webconsole detects
http://cgi.omroep.nl/legacy/player?/id/VARA/rest/2007/VARA_101158543/bb.20071030.asf
which downloads as **player.wmv** and contains:

``` xml
<ASX version = "3.0">
<ENTRY>
<Ref href = "mms://hurley.omroep.nl/public/ug-od/media4/ru_28/ap/media/id/VARA/rest/2007/VAR
A_101158543/bb.20071030.asf?wmt=54710b30&wmhash=4f31c006"/>
</ENTRY>

</ASX>
```

Does youtube-dl support the mms-protocol? FFMpeg doesn't, in which case [libmms](http://sourceforge.net/projects/libmms/) might be needed.

**Comment by corone17** [comment]
I was getting used to youtube-dl being updated at least once a week. Now 2014.12.17.2 is still the latest version. I would love to test this fix of yours, dstftw, but youtube-dl needs to be updated first.
(Or if someone can explain to me step-by-step how I can compile the exe-file myself, I would welcome that too. I'm no programmer, sorry.)

**Comment by dstftw** [comment]
There is no need in compiling the exe - you can run if from sources. Grab the latest sources from [here](https://github.com/rg3/youtube-dl/archive/master.zip) and unzip or just clone the git repository: `git clone https://github.com/rg3/youtube-dl`. Then navigate with command line to a directory where you grabbed the sources and run `python -m youtube_dl URL`. You'll need python installed.

**Comment by corone17** [comment]
First one is ok now, but not the second one:

```
youtube-dl.exe -vF http://www.npo.nl/valentijn/15-05-2013/WO_VARA_010361
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-vF', 'http://www.npo.nl/valentijn/15-05-2013/WO_VARA_010361']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.01.02
[debug] Python version 2.7.8 - Windows-XP-5.1.2600-SP3
[debug] exe versions: ffmpeg N-65810-g1b5ec6a
[debug] Proxy map: {}
[npo.nl] WO_VARA_010361: Downloading JSON metadata
[npo.nl] WO_VARA_010361: Downloading token
[npo.nl] WO_VARA_010361: Downloading stream 0 ASX playlist
[npo.nl] WO_VARA_010361: Downloading stream 1 ASX playlist
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "youtube_dl\__init__.pyo", line 361, in main
  File "youtube_dl\__init__.pyo", line 351, in _real_main
  File "youtube_dl\YoutubeDL.pyo", line 1165, in download
  File "youtube_dl\YoutubeDL.pyo", line 592, in extract_info
  File "youtube_dl\extractor\common.pyo", line 243, in extract
  File "youtube_dl\extractor\npo.pyo", line 75, in _real_extract
  File "youtube_dl\extractor\npo.pyo", line 152, in _get_info
  File "youtube_dl\utils.pyo", line 1224, in parse_duration
AttributeError: 'bool' object has no attribute 'strip'
```

**Comment by francesco1119** [comment]
Same problem: I cannot download the video http://www.rai.tv/dl/RaiTV/programmi/media/ContentItem-bde5986e-e524-4700-9eac-999afdd0f197.html from the URL: http://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=MjDPE0Bw1uIeeqqEEqual where actually is stored. At that URL the video is easy to see with VLC so I was wondering if it could be possible to use youtube-dl + VLC in order to download it.

Thank you

**Comment by francesco1119** [comment]
Fresh, update:
I can see the video on VLC but when I try to download it it says:

L'ingresso non può essere aperto:
VLC non è in grado di aprire il MRL 'mms://wms2.rai.it/raitrecdn/raitre/parlaconme/273146.wmv'. Controlla il registro per i dettagli.

what's that URL? The file is there!!!

**Comment by jaimeMF** [comment]
@francesco1119 your issue is unrelated (it's a different site), please [read the bug reporting instructions](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs) and open a new issue.
