### ISSUE TITLE
Site Request: http://nasheedbay.com

### ISSUE THREAD

**Issue by smohsin** [rg3/youtube-dl#4293]
PS C:\Users\Salman\Videos\YouTube-dl> C:\Software\youtube-dl.exe http://nasheedbay.com/husseinkalla/for-the-pleasure-of-allah/bow-my-head --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://nasheedbay.com/husseinkalla/for-the-pleasure-of-allah/bow-my-head', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2014.11.16
[debug] Python version 2.7.8 - Windows-8-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {}
[generic] bow-my-head: Requesting header
WARNING: Falling back on generic information extractor.
[generic] bow-my-head: Downloading webpage
[generic] bow-my-head: Extracting information
ERROR: Unsupported URL: http://nasheedbay.com/husseinkalla/for-the-pleasure-of-allah/bow-my-head; please report this iss
ue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make s
ure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "youtube_dl\extractor\generic.pyo", line 609, in _real_extract
  File "youtube_dl\utils.pyo", line 1319, in parse_xml
  File "xml\etree\ElementTree.pyo", line 1300, in XML
  File "xml\etree\ElementTree.pyo", line 1642, in feed
  File "xml\etree\ElementTree.pyo", line 1506, in _raiseerror
ParseError: undefined entity: line 5, column 118
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 536, in extract_info
  File "youtube_dl\extractor\common.pyo", line 199, in extract
  File "youtube_dl\extractor\generic.pyo", line 996, in _real_extract
ExtractorError: Unsupported URL: http://nasheedbay.com/husseinkalla/for-the-pleasure-of-allah/bow-my-head; please report
 this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete outpu
t. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by dstftw** [comment]
Works fine with latest version (2016.05.21.2).
