### ISSUE TITLE
[gotporn] Site support request

### ISSUE THREAD

**Issue by kendalls63** [rg3/youtube-dl#4368]
youtube-dl --verbose http://www.hardsextube.com/video/1029401/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.hardsextube.com/video/1029401/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2014.12.03
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: rtmpdump 2.3
[debug] Proxy map: {}
[generic] 1029401: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 1029401: Downloading webpage
[generic] 1029401: Extracting information
ERROR: Unsupported URL: http://www.hardsextube.com/video/1029401/; please report this issue on https://yt-dl.org/bug
Make sure you are using the latest version; type  youtube-dl -U  to update.
Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dl\extractor\generic.pyo", line 651, in _real_extract
  File "youtube_dl\utils.pyo", line 1411, in parse_xml
  File "xml\etree\ElementTree.pyo", line 1300, in XML
  File "xml\etree\ElementTree.pyo", line 1642, in feed
  File "xml\etree\ElementTree.pyo", line 1506, in _raiseerror
ParseError: mismatched tag: line 33, column 12
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 553, in extract_info
  File "youtube_dl\extractor\common.pyo", line 241, in extract
  File "youtube_dl\extractor\generic.pyo", line 1044, in _real_extract
ExtractorError: Unsupported URL: http://www.hardsextube.com/video/1029401/; please report this issue on https:
//yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call
youtube-dl with the --verbose flag and include its complete output.

**Comment by TRox1972** [comment]
Currently working, but id is way too long, and no extension is extracted

**Comment by drguildo** [comment]
I've added this in #10924.

**Comment by dstftw** [comment]
Works fine with generic extractor.
