### ISSUE TITLE
blogtalkradio

### ISSUE THREAD

**Issue by ghost** [rg3/youtube-dl#4428]
mint@mint ~ $ ~/youtube-dl http://undergroundwellness.com/podcasts/306-5-steps-to-permanent-gut-healing/ --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://undergroundwellness.com/podcasts/306-5-steps-to-permanent-gut-healing/', '--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.12.06.1
[debug] Python version 2.7.6 - Linux-3.13.0-24-generic-i686-with-LinuxMint-17-qiana
[debug] exe versions: none
[debug] Proxy map: {}
[generic] 306-5-steps-to-permanent-gut-healing: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 306-5-steps-to-permanent-gut-healing: Downloading webpage
[generic] 306-5-steps-to-permanent-gut-healing: Extracting information
ERROR: Unsupported URL: http://undergroundwellness.com/podcasts/306-5-steps-to-permanent-gut-healing/; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/mint/youtube-dl/youtube_dl/extractor/generic.py", line 651, in _real_extract
    doc = parse_xml(webpage)
  File "/home/mint/youtube-dl/youtube_dl/utils.py", line 1425, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: undefined entity: line 29, column 0
Traceback (most recent call last):
  File "/home/mint/youtube-dl/youtube_dl/YoutubeDL.py", line 553, in extract_info
    ie_result = ie.extract(url)
  File "/home/mint/youtube-dl/youtube_dl/extractor/common.py", line 241, in extract
    return self._real_extract(url)
  File "/home/mint/youtube-dl/youtube_dl/extractor/generic.py", line 1044, in _real_extract
    raise ExtractorError('Unsupported URL: %s' % url)
ExtractorError: Unsupported URL: http://undergroundwellness.com/podcasts/306-5-steps-to-permanent-gut-healing/;

**Comment by Pr0Wolf29** [comment]
I just tried a blogtalkradio url and it didn't work. It looks like the .mp3 file is easily accessible within the page source. It would be nice to be able to download all of the podcasts from a BTR user too.

**Comment by yan12125** [comment]
@Pr0Wolf29 Could you open a new issue for that?

**Comment by Pr0Wolf29** [comment]
Will do.
