### ISSUE TITLE
Not able to download video https://www.youtube.com/watch?v=XfH3erWacsQ

### ISSUE THREAD

**Issue by marcelcorso** [rg3/youtube-dl#4452]
I'm having problems downloading this guy:
https://www.youtube.com/watch?v=XfH3erWacsQ

```
$ sudo youtube-dl -U 
[sudo] password for love: 
Updating to version 2014.12.12.1 ...
Updated youtube-dl. Restart youtube-dl to use the new version.

$ export http_proxy=http://a.proxy.in.the.us:3128/; youtube-dl --verbose https://www.youtube.com/watch?v=XfH3erWacsQ
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=XfH3erWacsQ']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.12.12.1
[debug] Python version 2.7.6 - Linux-3.13.0-24-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: ffmpeg 1.2.6-7, ffprobe 1.2.6-7
[debug] Proxy map: {'http': 'http://a.proxy.in.the.us:3128/', u'https': 'http://a.proxy.in.the.us:3128/'}
[youtube] XfH3erWacsQ: Downloading webpage
[youtube] XfH3erWacsQ: Extracting video information
[youtube] {22} signature length 46.34.3, html5 player en_US-vflkOb-do
[youtube] XfH3erWacsQ: Downloading js player do
[youtube] {43} signature length 46.34.3, html5 player en_US-vflkOb-do
[youtube] {18} signature length 46.34.3, html5 player en_US-vflkOb-do
[youtube] {5} signature length 46.34.3, html5 player en_US-vflkOb-do
[youtube] {36} signature length 46.34.3, html5 player en_US-vflkOb-do
[youtube] {17} signature length 46.34.3, html5 player en_US-vflkOb-do
[youtube] {136} signature length 46.34.3, html5 player en_US-vflkOb-do
[youtube] {247} signature length 46.34.3, html5 player en_US-vflkOb-do
[youtube] {135} signature length 46.34.3, html5 player en_US-vflkOb-do
[youtube] {244} signature length 46.34.3, html5 player en_US-vflkOb-do
[youtube] {134} signature length 46.34.3, html5 player en_US-vflkOb-do
[youtube] {243} signature length 46.34.3, html5 player en_US-vflkOb-do
[youtube] {133} signature length 46.34.3, html5 player en_US-vflkOb-do
[youtube] {242} signature length 46.34.3, html5 player en_US-vflkOb-do
[youtube] {160} signature length 40.42, html5 player en_US-vflkOb-do
[youtube] XfH3erWacsQ: Downloading js player do
[youtube] {140} signature length 46.34.3, html5 player en_US-vflkOb-do
[youtube] {171} signature length 46.34.3, html5 player en_US-vflkOb-do
[youtube] XfH3erWacsQ: Downloading DASH manifest
[debug] Invoking downloader on u'https://r10---sn-p5qlsnss.googlevideo.com/videoplayback?requiressl=yes&ipbits=0&mime=video%2Fmp4&ip=a.proxy.in.the.us&expire=1418414292&nh=IgpwcjAxLmlhZDI2KgkxMjcuMC4wLjE&sver=3&id=o-ACkZ6uDWKJTCtSsQAqrQFfO27WOv2aRG2KVX7BvItGP4&gcr=us&mt=1418392643&fexp=900718%2C914951%2C924637%2C927622%2C930809%2C932404%2C938648%2C942627%2C943917%2C947209%2C948124%2C949427%2C952302%2C952605%2C952901%2C953912%2C955301%2C957103%2C957105%2C957201&mm=31&sparams=dur%2Cgcr%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Cmime%2Cmm%2Cms%2Cmv%2Cnh%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&upn=SSr41ngtG94&key=yt5&mv=m&dur=499.182&source=youtube&ratebypass=yes&itag=22&ms=au&initcwndbps=14282500&signature=DA37F325466B9F112E3105505F3AD30820C44F44.36882204BEB37F6A101FE7B96EA7045AD93E7110'
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1097, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1073, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 294, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 66, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1331, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found
```

thanks!

**Comment by dstftw** [comment]
Works fine with latest version (2016.05.16).
