### ISSUE TITLE
Unsupported URL: grooveshark

### ISSUE THREAD

**Issue by komuW** [rg3/youtube-dl#4496]
I tried downloading from an album in grooveshark using the following command (note: the url is quoted and it also fails without the quotes)
$ youtube-dl 'http://grooveshark.com/#!/album/Baptized/9357848' --verbose

[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://grooveshark.com/#!/album/Baptized/9357848', '--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.12.16.2
[debug] Python version 2.7.6 - Linux-3.8.11-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: none
[debug] Proxy map: {}
[generic] 9357848: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 9357848: Downloading webpage
[generic] 9357848: Extracting information
ERROR: Unsupported URL: http://grooveshark.com/#!/album/Baptized/9357848; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 660, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/utils.py", line 1444, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 80, column 26
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 592, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 243, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 1060, in _real_extract
    raise ExtractorError('Unsupported URL: %s' % url)
ExtractorError: Unsupported URL: http://grooveshark.com/#!/album/Baptized/9357848; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by yan12125** [comment]
Unfortunately Grooveshark was shut down yesterday. See the announcement at http://grooveshark.com/. Closing.
