### ISSUE TITLE
Streetfire.net site support request

### ISSUE THREAD

**Issue by Nilloc** [rg3/youtube-dl#4525]
Would like support for video clips and segmented videos if possible.

Thanks, error dumps follows:

    debug] System config: []
    [debug] User config: []
    [debug] Command-line args: ['http://www.streetfire.net/video/top-gear-bolivia-special-season-14-episode-6_1994638.htm', '--verbose']
    [debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
    [debug] youtube-dl version 2014.11.04
    [debug] Python version 2.7.1 - Darwin-11.4.2-x86_64-i386-64bit
    [debug] exe versions: ffmpeg 2.3-, rtmpdump 2.4
    [debug] Proxy map: {}
    [generic] top-gear-bolivia-special-season-14-episode-6_1994638: Requesting header
    WARNING: Falling back on generic information extractor.
    [generic] top-gear-bolivia-special-season-14-episode-6_1994638: Downloading webpage
    [generic] top-gear-bolivia-special-season-14-episode-6_1994638: Extracting information
    ERROR: Unsupported URL: http://www.streetfire.net/video/top-gear-bolivia-special-season-14-episode-6_1994638.htm; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
    Traceback (most recent call last):
      File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 596, in _real_extract
        doc = parse_xml(webpage)
      File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1311, in parse_xml
        tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1282, in XML
        parser.feed(text)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1624, in feed
        self._raiseerror(v)
          File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1488, in _raiseerror
        raise err
    ParseError: not well-formed (invalid token): line 76, column 82
    Traceback (most recent call last):
      File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 536, in extract_info
        ie_result = ie.extract(url)
      File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 199, in extract
        return self._real_extract(url)
      File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 977, in _real_extract
        raise ExtractorError('Unsupported URL: %s' % url)
    ExtractorError: Unsupported URL: http://www.streetfire.net/video/top-gear-bolivia-special-season-14-episode-6_1994638.htm; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by naglis** [comment]
The video content on the website of the provided URL seems to be copyright infringing, [without obvious proof of distribution rights](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free). Therefore we can't support this service, unless you can provide a URL to a video that the service is obviously allowed to distribute.
