### ISSUE TITLE
Link extraction from sportdeutschland.tv not working any more.

### ISSUE THREAD

**Issue by sulge** [rg3/youtube-dl#4544]
Example link:
http://sportdeutschland.tv/ttbl/vs-pokal-finale-fulda-duesseldorf-suess-gionis

[code]
youtube-dl.exe http://sportdeutschland.tv/ttbl/vs-pokal-finale-fulda-duesseldorf-suess-gionis
[SportDeutschland] vs-pokal-finale-fulda-duesseldorf-suess-gionis: Downloading JSON metadata
Traceback (most recent call last):
  File "**main**.py", line 19, in <module>
  File "youtube_dl__init__.pyo", line 361, in main
  File "youtube_dl__init__.pyo", line 351, in _real_main
  File "youtube_dl\YoutubeDL.pyo", line 1166, in download
  File "youtube_dl\YoutubeDL.pyo", line 592, in extract_info
  File "youtube_dl\extractor\common.pyo", line 243, in extract
  File "youtube_dl\extractor\sportdeutschland.pyo", line 65, in _real_extract
KeyError: u'video'
[/code]

At now there is no item 'video' but 'plays' and player's page contain video's url.

**Comment by phihag** [comment]
I believe this issue to be fixed in youtube-dl 2015.01.05 or newer. See [our FAQ](https://yt-dl.org/update) if you need help updating.
