### ISSUE TITLE
Unable to download twitch VODs

### ISSUE THREAD

**Issue by Creat** [rg3/youtube-dl#4556]
Hello,

I wanted to grab a twitch vod, as for some reason the official player seems to freeze every now and again for me. Youtube-dl failed though and asked me to report it as a bug here (and yes, I made sure I had the latest version).

Command line used: youtube-dl.exe --verbose --ignore-config "http://www.twitch.tv/ksptv/v/3622000"
(I have a few youtube-specific default options set for formats/names, hence the ignore)

Resulting output:

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '--ignore-config', 'http://www.twitch.tv/ksptv/v/3622000']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2014.12.17.2
[debug] Python version 2.7.8 - Windows-2008ServerR2-6.1.7601-SP1
[debug] exe versions: ffmpeg N-68141-g4280150
[debug] Proxy map: {}
[generic] 3622000: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 3622000: Downloading webpage
[generic] 3622000: Extracting information
ERROR: Unsupported URL: http://www.twitch.tv/ksptv/v/3622000; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dl\extractor\generic.pyo", line 660, in _real_extract
  File "youtube_dl\utils.pyo", line 1444, in parse_xml
  File "xml\etree\ElementTree.pyo", line 1300, in XML
  File "xml\etree\ElementTree.pyo", line 1642, in feed
  File "xml\etree\ElementTree.pyo", line 1506, in _raiseerror
ParseError: not well-formed (invalid token): line 20, column 89
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 592, in extract_info
  File "youtube_dl\extractor\common.pyo", line 243, in extract
  File "youtube_dl\extractor\generic.pyo", line 1060, in _real_extract
ExtractorError: Unsupported URL: http://www.twitch.tv/ksptv/v/3622000; please report this issue on https://yt-dl.org/bug. Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

Was there something changed with twitch recently, as I remember this worked fine very recently...

Thanks
Creat

**Comment by phihag** [comment]
I believe this issue to be fixed in youtube-dl 2015.01.05 or newer. See [our FAQ](https://yt-dl.org/update) if you need help updating.
