### ISSUE TITLE
Unable to download video from dailymotion

### ISSUE THREAD

**Issue by eklavyathareja** [rg3/youtube-dl#4558]
I was trying to download video from dailymotion using youtube-dl 2014.12.17.2 and I got this
```
youtube-dl --verbose https://www.dailymotion.com/video/x12p8um_helsinki-wcotw_lifestyle
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'https://www.dailymotion.com/video/x12p8um_helsinki-wcotw_lifestyle']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.12.17.2
[debug] Python version 2.7.6 - Linux-3.13.0-24-generic-x86_64-with-LinuxMint-17.1-rebecca
[debug] exe versions: none
[debug] Proxy map: {}
[dailymotion] x12p8um: Downloading webpage
[dailymotion] x12p8um: Extracting information
[dailymotion] x12p8um: Downloading embed page
ERROR: Unable to extract video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 592, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 243, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/dailymotion.py", line 119, in _real_extract
    'video info', flags=re.MULTILINE)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 489, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by eklavyathareja** [comment]
No, I am unable to watch it either. It shows error(2101). I tried it with both Chrome and Firefox. Both show the same error. 

And it is true for all dailymotion videos so the problem is not in that particular video. Also, I am able to watch videos on other sites.

**Comment by jaimeMF** [comment]
Then it's something on your network/computer. We can't do anything if you can't watch the video in your browser.
