### ISSUE TITLE
Add support for dr.dk

### ISSUE THREAD

**Issue by mortenivar** [rg3/youtube-dl#4581]
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.dr.dk/bonanza/serie/portraetter/Talkshowet.htm?assetId=65517']
[debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8
[debug] youtube-dl version 2014.12.01
[debug] Python version 2.7.9 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.0
[debug] exe versions: avconv 11-6, avprobe 11-6, rtmpdump 2.4
[debug] Proxy map: {}
[generic] Talkshowet: Requesting header
WARNING: Falling back on generic information extractor.
[generic] Talkshowet: Downloading webpage
[generic] Talkshowet: Extracting information
ERROR: Unsupported URL: http://www.dr.dk/bonanza/serie/portraetter/Talkshowet.htm?assetId=65517; please report this issue on https://yt-dl.org/bug . Make sure you are\
 using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 651, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/utils.py", line 1411, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: mismatched tag: line 73, column 3
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 553, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 241, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 1044, in _real_extract
    raise ExtractorError('Unsupported URL: %s' % url)
ExtractorError: Unsupported URL: http://www.dr.dk/bonanza/serie/portraetter/Talkshowet.htm?assetId=65517; please report this issue on https://yt-dl.org/bug . Make sur\
e you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete outpu\
t.

**Comment by Josso** [comment]
@flehen: Yours didn't work because of https. It has been fixed in #4684.

The original url by @mortenivar can now be downloaded as per the #4687.
It's worth noting, that when downloading DR Bonanza-links you should preferable include the assetId-query-parameter. Otherwise it will just download the first video on the page.
If you navigate onto a video and the query-parameter doesn't get updated (because it's an old JavaScript/Flash website) the easiest way to get the updated URL is to find the "Email a friend"-link and copy it from there.
