### ISSUE TITLE
Add support for nintendo.com

### ISSUE THREAD

**Issue by PressStartandSelect** [rg3/youtube-dl#4592]
Hello,

Could you please add support for videos on nintendo.com?

Here are some examples:
http://www.nintendo.com/games/detail/yEiAzhU2eQI1KZ7wOHhngFoAHc1FpHwj
http://www.nintendo.com/wiiu/videos/#all/Why_You_Want_Wii_U
http://www.nintendo.com/nintendo-direct/04-30-2014/#/video-ndirect

```
$ youtube-dl "http://www.nintendo.com/wiiu/videos/#all/Why_You_Want_Wii_U" --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://www.nintendo.com/wiiu/videos/#all/Why_You_Want_Wii_U', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.12.17.2
[debug] Python version 2.7.6 - Darwin-14.0.0-x86_64-i386-64bit
[debug] exe versions: rtmpdump 2.4
[debug] Proxy map: {}
[generic] Why_You_Want_Wii_U: Requesting header
WARNING: Falling back on generic information extractor.
[generic] Why_You_Want_Wii_U: Downloading webpage
[generic] Why_You_Want_Wii_U: Extracting information
ERROR: Unsupported URL: http://www.nintendo.com/wiiu/videos/#all/Why_You_Want_Wii_U; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 660, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1444, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 651, column 139
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 592, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 243, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1060, in _real_extract
    raise ExtractorError('Unsupported URL: %s' % url)
ExtractorError: Unsupported URL: http://www.nintendo.com/wiiu/videos/#all/Why_You_Want_Wii_U; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

$ 
```

**Comment by TRox1972** [comment]
This is already supported

**Comment by dstftw** [comment]
Not all URL formats supported.
