### ISSUE TITLE
www.southparkstudios.dk

### ISSUE THREAD

**Issue by ole-tange** [rg3/youtube-dl#4605]
$ youtube-dl --verbose http://www.southparkstudios.dk/full-episodes/s18e07-grounded-vindaloop
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.southparkstudios.dk/full-episodes/s18e07-grounded-vindaloop']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.12.17.2
[debug] Python version 2.7.6 - Linux-3.13.0-32-lowlatency-x86_64-with-LinuxMint-17-qiana
[debug] exe versions: avconv 9.16-6, avprobe 9.16-6, ffmpeg 0.8.9-6, rtmpdump 2.4
[debug] Proxy map: {}
[generic] s18e07-grounded-vindaloop: Requesting header
WARNING: Falling back on generic information extractor.
[generic] s18e07-grounded-vindaloop: Downloading webpage
[generic] s18e07-grounded-vindaloop: Extracting information
ERROR: Unsupported URL: http://www.southparkstudios.dk/full-episodes/s18e07-grounded-vindaloop; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 660, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1444, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 270, column 106
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 592, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 243, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1060, in _real_extract
    raise ExtractorError('Unsupported URL: %s' % url)
ExtractorError: Unsupported URL: http://www.southparkstudios.dk/full-episodes/s18e07-grounded-vindaloop; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
southparkstudios.dk will be supported in the next version. Thanks for the report.
