### ISSUE TITLE
-x error about avconv/ffmpeg, but works anyway?

### ISSUE THREAD

**Issue by Core-Xii** [rg3/youtube-dl#4607]
I get the error about avconv/ffmpeg missing when I use the -x option, but the audio file is created anyway and works fine! I don't understand - why stop with an error (hinders downloading whole playlists) when the process worked? I need it to stop throwing pointless errors or at least a flag to ignore them and continue with the playlist.

**Comment by dstftw** [comment]
Post the **full** output you get when running [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs)
To ignore errors use `--ignore-errors`.

**Comment by Core-Xii** [comment]
Here's a full output.

```
H:\files\applications>youtube-dl -x https://www.youtube.com/watch?v=xHGAZD4Pr1Y
--verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-x', 'https://www.youtube.com/watch?v=xHGAZD4Pr1Y',
 '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2014.12.17.2
[debug] Python version 2.7.8 - Windows-8-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] xHGAZD4Pr1Y: Downloading webpage
[youtube] xHGAZD4Pr1Y: Extracting video information
[youtube] {43} signature length 40.41, html5 player en_US-vflw4H1P-
[youtube] {18} signature length 40.41, html5 player en_US-vflw4H1P-
[youtube] {5} signature length 40.41, html5 player en_US-vflw4H1P-
[youtube] {36} signature length 40.41, html5 player en_US-vflw4H1P-
[youtube] {17} signature length 40.41, html5 player en_US-vflw4H1P-
[youtube] {135} signature length 40.41, html5 player en_US-vflw4H1P-
[youtube] {244} signature length 40.41, html5 player en_US-vflw4H1P-
[youtube] {134} signature length 40.41, html5 player en_US-vflw4H1P-
[youtube] {243} signature length 40.41, html5 player en_US-vflw4H1P-
[youtube] {133} signature length 40.41, html5 player en_US-vflw4H1P-
[youtube] {242} signature length 40.41, html5 player en_US-vflw4H1P-
[youtube] {160} signature length 40.41, html5 player en_US-vflw4H1P-
[youtube] {140} signature length 40.41, html5 player en_US-vflw4H1P-
[youtube] {171} signature length 40.41, html5 player en_US-vflw4H1P-
[youtube] xHGAZD4Pr1Y: Downloading DASH manifest
[debug] Invoking downloader on 'https://r2---sn-4ox-ixae.googlevideo.com/videopl
ayback?id=c47180643e0faf56&itag=141&source=youtube&requiressl=yes&mv=m&mm=31&ms=
au&ratebypass=yes&mime=audio/mp4&gir=yes&clen=8688852&lmt=1417344161619522&dur=2
72.509&fexp=900245,900718,912109,919514,927622,932404,934947,936118,9405684,9405
846,941004,943917,947209,947218,948124,952302,952605,952901,955301,957103,957105
,957201,958618&key=dg_yt0&signature=1A87B1989AB875AE5D11D574A5FFE9B85AB4A106.084
C34178360ED579C685EC3A702CE99383D3C6E&upn=FVW1P4XLJ9E&sver=3&mt=1420128443&ip=10
9.204.191.48&ipbits=0&expire=1420150061&sparams=ip,ipbits,expire,id,itag,source,
requiressl,mv,mm,ms,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: Parov Stelar - The Phantom  (1930 Version)-xHGAZD4Pr1Y.m
4a
[download] 100% of 8.29MiB in 00:02
ERROR: ffprobe or avprobe not found. Please install one.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 1203, in post_process
  File "youtube_dl\postprocessor\ffmpeg.pyo", line 156, in run
  File "youtube_dl\postprocessor\ffmpeg.pyo", line 122, in get_audio_codec
PostProcessingError


H:\files\applications>
```

The output is an 8.28 MB seemingly audio-only 4 min 32 sec long .m4a file that contains exactly what it should - the audio extracted from the given video.

**Comment by dstftw** [comment]
>the audio extracted from the given video

Not really, it has just downloaded audio-only format of the best available quality.
