### ISSUE TITLE
XTube: Unable to extract player quality

### ISSUE THREAD

**Issue by youtubedlissue** [rg3/youtube-dl#4611]
youtube-dl http://www.xtube.com/watch.php?v=FlOej-S896- --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://www.xtube.com/watch.php?v=FlOej-S896-', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.12.17.2
[debug] Python version 3.4.2 - Linux-3.17.6-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 2.5.2, ffprobe 2.5.2, rtmpdump 2.4
[debug] Proxy map: {}
[XTube] FlOej-S896-: Downloading webpage
WARNING: unable to extract uploader; please report this issue on http://yt-dl.org/bug
ERROR: Unable to extract player quality option; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 592, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 243, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/xtube.py", line 58, in _real_extract
    r'playerQualityOption = ({.+?});', webpage, 'player quality option'))
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 499, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 489, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract player quality option; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by youtubedlissue** [comment]
Whoops, it's been fixed in 2015.01.01 with https://github.com/rg3/youtube-dl/commit/16ea8179681263d570e632d3ce523ed23ddbf204, but my distro hasn't updated the package yet.
$ pacman -Ss youtube-dl
community/youtube-dl 2014.12.17.2-1 [installed]
    A small command-line program to download videos from YouTube.com and a few
    more sites
