### ISSUE TITLE
Add support for apple.com

### ISSUE THREAD

**Issue by PressStartandSelect** [rg3/youtube-dl#4637]
Hello,

Could you please add support for videos on apple.com?

Here are some examples:
http://www.apple.com/apple-events/2014-oct-event/
http://www.apple.com/ipad-air-2/change/

The video on the second link is slightly different, it only shows up after the "Watch the film" button is clicked. (Most of the non-event videos are like this.)

```
$ youtube-dl --verbose http://www.apple.com/apple-events/2014-oct-event/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.apple.com/apple-events/2014-oct-event/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.01.04
[debug] Python version 2.7.6 - Darwin-14.0.0-x86_64-i386-64bit
[debug] exe versions: rtmpdump 2.4
[debug] Proxy map: {}
[generic] 2014-oct-event: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 2014-oct-event: Downloading webpage
[generic] 2014-oct-event: Extracting information
ERROR: Unsupported URL: http://www.apple.com/apple-events/2014-oct-event/
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 669, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1451, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 7, column 1232
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 592, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 245, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1074, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.apple.com/apple-events/2014-oct-event/

$ 
```

**Comment by aaronvegh** [comment]
I'd also add the trailers site to this list, if it's not under consideration already! here's an example: http://trailers.apple.com/trailers/independent/goodnightmommy/

**Comment by lyndmi** [comment]
Anyone are willing to add support for apple special events?
https://www.apple.com/apple-events/

**Comment by ValZapod** [comment]
Continuing tradaition: https://events-delivery.apple.com/1402uekefjejgldkvaqrqxgjmtehwhez/m3u8/vod_index-VEPhheWQmQZLrgakajRXoUbKAmmjVXxZ.m3u8

now with atmos!

**Comment by ValZapod** [comment]
Again lets continue the cool tradition with new WWDC 2022:

https://events-delivery.apple.com/0205eyyhwbbqexozkwmgccegwnjyrktg/m3u8/vod_index-dpyfrsVksFWjneFiptbXnAMYBtGYbXeZ.m3u8

FFplay cannot seek due to a bug in fmp4!
