### ISSUE TITLE
error ubuntu 14.04

### ISSUE THREAD

**Issue by fabiopr2** [rg3/youtube-dl#4645]
the program is very good
the windows version is okay
however the ubuntu version gave an error

follows below
Note I have premium account

~# youtube-dl -f 480p --all-subs --sub-format ass --username xxx --password xxx --verbose --rate-limit 1000K http://www.crunchyroll.com/parasyte-the-maxim-/episode-12-kokoro-662605
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-f', '480p', '--all-subs', '--sub-format', 'ass', '--username', u'PRIVATE', '--password', u'PRIVATE', '--verbose', '--rate-limit', '1000K', 'http://www.crunchyroll.com/parasyte-the-maxim-/episode-12-kokoro-662605']
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
[debug] youtube-dl version 2015.01.05
[debug] Python version 2.7.6 - Linux-2.6.32-32-pve-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.16-6, avprobe 9.16-6, rtmpdump 2.4
[debug] Proxy map: {}
[Crunchyroll] Logging in
[Crunchyroll] 662605: Downloading webpage
[Crunchyroll] 662605: Downloading media info
[Crunchyroll] 662605: Downloading media info for 360p
[Crunchyroll] 662605: Downloading media info for 480p
[Crunchyroll] 662605: Downloading media info for 720p
[Crunchyroll] 662605: Downloading media info for 1080p
[Crunchyroll] 662605: Downloading subtitles for English (US)
[Crunchyroll] 662605: Downloading subtitles for Espaol
[Crunchyroll] 662605: Downloading subtitles for Franais (France)
[Crunchyroll] 662605: Downloading subtitles for Portugus (Brasil)
[Crunchyroll] 662605: Downloading subtitles for Deutsch
[info] Writing video subtitles to: Parasyte -the maxim- Episode 12  Kokoro-662605.ptBR.ass
[info] Writing video subtitles to: Parasyte -the maxim- Episode 12  Kokoro-662605.deDE.ass
[info] Writing video subtitles to: Parasyte -the maxim- Episode 12  Kokoro-662605.frFR.ass
[info] Writing video subtitles to: Parasyte -the maxim- Episode 12  Kokoro-662605.enUS.ass
[info] Writing video subtitles to: Parasyte -the maxim- Episode 12  Kokoro-662605.esLA.ass
[debug] Invoking downloader on 'rtmpe://cp150757.edgefcs.net/ondemand/?auth=daEcQbIbuaOatalbfcIdFdcc5cQbObFbkdr-buQTnw-dHa-nBHxlqHAGuv&aifp=0009&slist=c2/s/ve1647879/video.mp4'
[download] Destination: Parasyte -the maxim- Episode 12  Kokoro-662605.flv
[debug] rtmpdump command line: rtmpdump --verbose -r 'rtmpe://cp150757.edgefcs.net/ondemand/?auth=daEcQbIbuaOatalbfcIdFdcc5cQbObFbkdr-buQTnw-dHa-nBHxlqHAGuv&aifp=0009&slist=c2/s/ve1647879/video.mp4' -o 'Parasyte -the maxim- Episode 12  Kokoro-662605.flv.part' --playpath mp4:c2/s/ve1647879/video.mp4 --resume --skip 1
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 361, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 351, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1165, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 603, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 649, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 938, in process_video_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1136, in process_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1112, in dl
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 297, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/rtmp.py", line 174, in real_download
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/rtmp.py", line 30, in run_rtmpdump
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
TypeError: execv() arg 2 must contain only strings

despite the error

if I run the manual command

--verbose rtmpdump -r'rtmpe://cp150757.edgefcs.net/ondemand/?auth=daEcQbIbuaOatalbfcIdFdcc5cQbObFbkdr-buQTnw-dHa-nBHxlqHAGuv&aifp=0009&slist=c2/s/ve1647879/video.mp4' -o 'Parasyte -the maxim- Episode 12 Kokoro-662605.flv.part' --playpath mp4: c2 / s / ve1647879 / video.mp4 --resume --skip 1

the download is done

**Comment by dstftw** [comment]
Works fine with latest version (2016.05.16).
