### ISSUE TITLE
Add support for bravotv.com

### ISSUE THREAD

**Issue by nevafuse** [rg3/youtube-dl#4657]
Example URL: http://www.bravotv.com/now/top-chef/full-episode/lck-ep-1-part-2-redemption/369257539730

Appears to be using akamaihd.net which is the same streaming service a couple of other support sites use such as brightcove & livestream.  Thanks!

**Comment by remitamine** [comment]
added support for free videos.
full episode video require authentication.

**Comment by StevenDTX** [comment]
So, should this work with the DTV authenication that the aenetworks extractor works with?

```
E:\>youtube-dl --verbose http://www.bravotv.com/flipping-out/season-9/ep-5-mary-mary-quite-contrary
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.bravotv.com/flipping-out/season-9/ep-5-mary-mary-quite-contrary']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.08.13
[debug] Python version 3.4.4 - Windows-10-10.0.10586
[debug] exe versions: ffmpeg N-72383-g7206b94, ffprobe N-72383-g7206b94, rtmpdump 2.4
[debug] Proxy map: {}
[generic] ep-5-mary-mary-quite-contrary: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ep-5-mary-mary-quite-contrary: Downloading webpage
[generic] ep-5-mary-mary-quite-contrary: Extracting information
ERROR: Unsupported URL: http://www.bravotv.com/flipping-out/season-9/ep-5-mary-mary-quite-contrary
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpz_7f3hc1\build\youtube_dl\YoutubeDL.py", line 691, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpz_7f3hc1\build\youtube_dl\extractor\common.py", line 347, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpz_7f3hc1\build\youtube_dl\extractor\generic.py", line 2344, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.bravotv.com/flipping-out/season-9/ep-5-mary-mary-quite-contrary
```
