### ISSUE TITLE
problems downloading youtube playlists

### ISSUE THREAD

**Issue by kaefert** [rg3/youtube-dl#4658]
Hi there!

I've downloaded the latest youtube-dl like this:
curl https://yt-dl.org/downloads/2015.01.07.2/youtube-dl -o youtube-dl

confirming version:
````
./youtube-dl --version
2015.01.07.2
````

trying to download a youtube playlist (some playlists work without a problem, this one doesn't..)
````
./youtube-dl --verbose --prefer-ffmpeg --write-sub --write-auto-sub --sub-lang 'en,de' -f 264+141/264+140/137+141/137+140/136+141/136+140/22/135+141/135+140/134+141/134+140/18 "https://www.youtube.com/playlist?list=PLVXq77mXV53_3HqhCLGv4mz3oVGYd2Aup"
[youtube:playlist] PLVXq77mXV53_3HqhCLGv4mz3oVGYd2Aup: Downloading webpage
[youtube:playlist] PLVXq77mXV53_3HqhCLGv4mz3oVGYd2Aup: Downloading page #1
[youtube:playlist] PLVXq77mXV53_3HqhCLGv4mz3oVGYd2Aup: Downloading page #2
[youtube:playlist] PLVXq77mXV53_3HqhCLGv4mz3oVGYd2Aup: Downloading page #3
ERROR: Unable to download JSON metadata: <urlopen error [Errno 8] _ssl.c:510: EOF occurred in violation of protocol> (caused by URLError(SSLError(8, '_ssl.c:510: EOF occurred in violation of protocol'),))
````

a second try, with --verbose option:
````
$ ./youtube-dl --verbose --prefer-ffmpeg --write-sub --write-auto-sub --sub-lang 'en,de' -f 264+141/264+140/137+141/137+140/136+141/136+140/22/135+141/135+140/134+141/134+140/18 "https://www.youtube.com/playlist?list=PLVXq77mXV53_3HqhCLGv4mz3oVGYd2Aup"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '--prefer-ffmpeg', '--write-sub', '--write-auto-sub', '--sub-lang', 'en,de', '-f', '264+141/264+140/137+141/137+140/136+141/136+140/22/135+141/135+140/134+141/134+140/18', 'https://www.youtube.com/playlist?list=PLVXq77mXV53_3HqhCLGv4mz3oVGYd2Aup']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.01.07.2
[debug] Python version 2.7.6 - Linux-3.13.0-37-generic-x86_64-with-LinuxMint-17.1-rebecca
[debug] exe versions: avconv 11, avprobe 11, ffmpeg N-68674-gb51cc70, ffprobe N-68674-gb51cc70
[debug] Proxy map: {}
[youtube:playlist] PLVXq77mXV53_3HqhCLGv4mz3oVGYd2Aup: Downloading webpage
[youtube:playlist] PLVXq77mXV53_3HqhCLGv4mz3oVGYd2Aup: Downloading page #1
[youtube:playlist] PLVXq77mXV53_3HqhCLGv4mz3oVGYd2Aup: Downloading page #2
[youtube:playlist] PLVXq77mXV53_3HqhCLGv4mz3oVGYd2Aup: Downloading page #3
[youtube:playlist] PLVXq77mXV53_3HqhCLGv4mz3oVGYd2Aup: Downloading page #4
[download] Downloading playlist: Top Classical Music Tracks
[youtube:playlist] playlist Top Classical Music Tracks: Collected 499 video ids (downloading 499 of them)
[download] Downloading video 1 of 499
[youtube] 75uRFWqbs58: Downloading webpage
[youtube] 75uRFWqbs58: Extracting video information
[youtube] 75uRFWqbs58: Looking for automatic captions
WARNING: Couldn't find automatic captions for 75uRFWqbs58
WARNING: video doesn't have subtitles
[youtube] 75uRFWqbs58: Downloading DASH manifest
[debug] Invoking downloader on 'https://r2---sn-oxmua5txg-8pxe.googlevideo.com/videoplayback?id=ef9b91156a9bb39f&itag=137&source=youtube&requiressl=yes&mm=31&gcr=at&mv=u&ms=au&ratebypass=yes&mime=video/mp4&gir=yes&clen=8671442&lmt=1419392160982533&dur=178.978&sver=3&signature=23314047E752FE9BA7D7508543C884DAEDC9473D.9269AF1DB12400E2AB4E13DEB3289ADB871A8451&mt=1420634456&upn=9wRXQN8QuxA&fexp=900718,904726,917000,924637,927622,932404,9405454,941004,943605,943917,947209,947218,948124,952302,952605,952901,955301,957103,957105,957201&key=dg_yt0&ip=2a02:60:106:9a21:e834:98c7:2f0:92d9&ipbits=0&expire=1420656267&sparams=ip,ipbits,expire,id,itag,source,requiressl,mm,gcr,mv,ms,ratebypass,mime,gir,clen,lmt,dur'
ERROR: unable to open for writing: [Errno 36] File name too long: '\xe3\x83\x97\xe3\x83\x83\xe3\x83\x81\xe3\x83\xbc\xe3\x83\x8b - \xe6\xad\x8c\xe5\x8a\x87\xef\xbd\xa2\xe3\x83\x88\xe3\x82\xa5\xe3\x83\xbc\xe3\x83\xa9\xe3\x83\xb3\xe3\x83\x89\xe3\x83\x83\xe3\x83\x88\xef\xbd\xa3\xef\xbc\x9a\xe8\xaa\xb0\xe3\x82\x82\xe5\xaf\x9d\xe3\x81\xa6\xe3\x81\xaf\xe3\x81\xaa\xe3\x82\x89\xe3\x81\xaa\xe3\x81\x84(\xe7\xac\xac3\xe5\xb9\x95)\xef\xbc\xbb\xe3\x83\x8a\xe3\x82\xaf\xe3\x82\xbd\xe3\x82\xb9\xe3\x83\xbb\xe3\x82\xaf\xe3\x83\xa9\xe3\x82\xb7\xe3\x83\x83\xe3\x82\xaf\xe3\x83\xbb\xe3\x82\xad\xe3\x83\xa5\xe3\x83\xac\xe3\x83\xbc\xe3\x82\xb7\xe3\x83\xa7\xe3\x83\xb3 #\xe7\x89\xb9\xe5\x88\xa5\xe7\xb7\xa8\xef\xbc\x9a\xe3\x82\xb5\xe3\x83\x83\xe3\x82\xab\xe3\x83\xbcW\xe6\x9d\xaf\xef\xbc\xbd-75uRFWqbs58.f137.mp4.part'
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/downloader/http.py", line 157, in real_download
    (stream, tmpfilename) = sanitize_open(tmpfilename, open_mode)
  File "./youtube-dl/youtube_dl/utils.py", line 250, in sanitize_open
    stream = open(encodeFilename(filename), open_mode)
IOError: [Errno 36] File name too long: '\xe3\x83\x97\xe3\x83\x83\xe3\x83\x81\xe3\x83\xbc\xe3\x83\x8b - \xe6\xad\x8c\xe5\x8a\x87\xef\xbd\xa2\xe3\x83\x88\xe3\x82\xa5\xe3\x83\xbc\xe3\x83\xa9\xe3\x83\xb3\xe3\x83\x89\xe3\x83\x83\xe3\x83\x88\xef\xbd\xa3\xef\xbc\x9a\xe8\xaa\xb0\xe3\x82\x82\xe5\xaf\x9d\xe3\x81\xa6\xe3\x81\xaf\xe3\x81\xaa\xe3\x82\x89\xe3\x81\xaa\xe3\x81\x84(\xe7\xac\xac3\xe5\xb9\x95)\xef\xbc\xbb\xe3\x83\x8a\xe3\x82\xaf\xe3\x82\xbd\xe3\x82\xb9\xe3\x83\xbb\xe3\x82\xaf\xe3\x83\xa9\xe3\x82\xb7\xe3\x83\x83\xe3\x82\xaf\xe3\x83\xbb\xe3\x82\xad\xe3\x83\xa5\xe3\x83\xac\xe3\x83\xbc\xe3\x82\xb7\xe3\x83\xa7\xe3\x83\xb3 #\xe7\x89\xb9\xe5\x88\xa5\xe7\xb7\xa8\xef\xbc\x9a\xe3\x82\xb5\xe3\x83\x83\xe3\x82\xab\xe3\x83\xbcW\xe6\x9d\xaf\xef\xbc\xbd-75uRFWqbs58.f137.mp4.part'
````

**Comment by sf55** [comment]
Have you tried it with the --playlist-start option?

I'm having similar errors. 
`sebastiaan@hp:~$ youtube-dl --version
2015.01.07.2`

Here is the output with the verbose option.
`@hp:/home/sebastiaan# youtube-dl --verbose --playlist-start 1 https://www.youtube.com/watch?v=pWStaRmuXzY&list=PL8MZVvHPR7RzyEfsrAGCeB_UXxJhnIXGb
[1] 3141
root@hp:/home/sebastiaan# [debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '--playlist-start', '1', 'https://www.youtube.com/watch?v=pWStaRmuXzY']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.01.07.2
[debug] Python version 2.7.6 - Linux-3.13.0-43-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.16-6, avprobe 9.16-6, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] pWStaRmuXzY: Downloading webpage
[youtube] pWStaRmuXzY: Extracting video information
[youtube] {43} signature length 40.41, html5 player en_US-vflw4H1P-
[youtube] {18} signature length 40.41, html5 player en_US-vflw4H1P-
[youtube] {5} signature length 40.41, html5 player en_US-vflw4H1P-
[youtube] {36} signature length 40.41, html5 player en_US-vflw4H1P-
[youtube] {17} signature length 40.41, html5 player en_US-vflw4H1P-
[youtube] {135} signature length 40.41, html5 player en_US-vflw4H1P-
[youtube] {244} signature length 40.41, html5 player en_US-vflw4H1P-
[youtube] {134} signature length 40.41, html5 player en_US-vflw4H1P-
[youtube] {243} signature length 40.41, html5 player en_US-vflw4H1P-
[youtube] {133} signature length 40.41, html5 player en_US-vflw4H1P-
[youtube] {242} signature length 40.41, html5 player en_US-vflw4H1P-
[youtube] {160} signature length 40.41, html5 player en_US-vflw4H1P-
[youtube] {140} signature length 40.41, html5 player en_US-vflw4H1P-
[youtube] {171} signature length 40.41, html5 player en_US-vflw4H1P-
[youtube] pWStaRmuXzY: Downloading DASH manifest
[debug] Invoking downloader on u'https://r1---sn-ni5f-t8gl.googlevideo.com/videoplayback?source=youtube&upn=EPJeu6qa1QY&mime=video%2Fmp4&key=yt5&requiressl=yes&initcwndbps=1693750&ratebypass=yes&fexp=900718%2C904845%2C927606%2C927622%2C932404%2C933112%2C9405436%2C941004%2C943917%2C947209%2C947218%2C947225%2C948124%2C952302%2C952605%2C952901%2C955301%2C957103%2C957105%2C957201%2C959701&itag=18&mt=1420733050&mv=m&sparams=dur%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Cmime%2Cmm%2Cms%2Cmv%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&ms=au&ip=24.69.46.0&expire=1420754717&ipbits=0&mm=31&dur=380.157&id=o-AOHpyO42cI1dJ4PqJjNGotQK7EpAtNWX-VbNtrBF6-8G&sver=3&signature=48CA1F92D129FB50F33E9D79A2E864CB9FAE0C55.2DEE16649D3690FD153EEA90B9CD1A8D0E933608'
[download] Destination: Swans - Failure-pWStaRmuXzY.mp4
[download] 100% of 9.54MiB in 0.04`

**Comment by sf55** [comment]
Have you also tried it with the --playlist-start option? 

I'm having similar problems. In my case youtube-dl only downloads the first video of the playlist.

**Comment by kaefert** [comment]
I found that on a different system it worked - and wrote a file with lots of chinese characters, so I guess there is something missing in my terminal of the first PC I tried that prevents youtube-dl from recognizing the correct encoding?

But also I regularly stumble upon some errors (during downloading lists) like:
````YouTube said: This video does not exist.````

It would be brilliant if there was a option to just continue with the next file and simply skip the error

**Comment by jaimeMF** [comment]
@kaefert `--ignore-errors` should work.
About the `File name too long`, in which directory are you running youtube-dl from? maybe the filesystem is limiting the filename size.

**Comment by kaefert** [comment]
it was on an ext4 formatted disk = system disk in the path /home/kaefert/Videos/youtube/
thanks for the --ignore-errors option will try that :)
