### ISSUE TITLE
problem when converting videos with special characters in title to mp3

### ISSUE THREAD

**Issue by moloz** [rg3/youtube-dl#4668]
Hi,

I was trying to download and convert the video at this URL here (hXXps://www.youtube.com/watch?v=Y9o7ILCPSFU) with the following command:

youtube-dl.exe --extract-audio --audio-format mp3 hXXps://www.youtube.com/watch?v=Y9o7ILCPSFU

It kept  failing with the following error:

[youtube] Y9o7ILCPSFU: Downloading webpage
[youtube] Y9o7ILCPSFU: Extracting video information
[youtube] Y9o7ILCPSFU: Downloading DASH manifest
[download] Destination: Trentemøller - Miss You (Mahmut Orhan Remix)-Y9o7ILCPSFU
.m4a
[download] 100% of 8.28MiB in 00:36
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "youtube_dl\__init__.pyo", line 355, in main
  File "youtube_dl\__init__.pyo", line 345, in _real_main
  File "youtube_dl\YoutubeDL.pyo", line 1121, in download
  File "youtube_dl\YoutubeDL.pyo", line 564, in extract_info
  File "youtube_dl\YoutubeDL.pyo", line 610, in process_ie_result
  File "youtube_dl\YoutubeDL.pyo", line 897, in process_video_result
  File "youtube_dl\YoutubeDL.pyo", line 1103, in process_info
  File "youtube_dl\YoutubeDL.pyo", line 1158, in post_process
  File "youtube_dl\postprocessor\ffmpeg.pyo", line 156, in run
  File "youtube_dl\postprocessor\ffmpeg.pyo", line 128, in get_audio_codec
  File "subprocess.pyo", line 710, in __init__
  File "subprocess.pyo", line 913, in _execute_child
  File "subprocess.pyo", line 644, in list2cmdline
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf8 in position 0: ordinal
not in range(128)

Not an expert with this stuff, but my guess is it fails due to the "ø" character in the title. I don't know if it's intended or a bug but just thought giving you guys a heads up. I guess it affects also videos with other special characters in title.

Cheers!

**Comment by phihag** [comment]
Thank you for the report! I believe this issue to be fixed in youtube-dl 2015.01.09 and newer. See [our FAQ](https://yt-dl.org/update) if you need help updating.
