### ISSUE TITLE
vk.com not working: AssertionError

### ISSUE THREAD

**Issue by spvkgn** [rg3/youtube-dl#4672]
Could you please fix this issue with vk.com

youtube-dl -v https://vk.com/video-57424472_171223169
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'https://vk.com/video-57424472_171223169']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.01.08
[debug] Python version 2.7.3 - Linux-3.2.0-69-generic-pae-i686-with-LinuxMint-13-maya
[debug] exe versions: ffmpeg 2.4.2, ffprobe 2.4.2, rtmpdump 2.4
[debug] Proxy map: {}
[vk.com] -57424472_171223169: Downloading webpage
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 359, in main
    
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 349, in _real_main
    
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1161, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 588, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 246, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/vk.py", line 169, in _real_extract
AssertionError

**Comment by jaimeMF** [comment]
Fixed, it will work in the next version. Thanks for the report.

**Comment by phihag** [comment]
I apologize for introducing that error. Type `sudo youtube-dl -U` to update to youtube-dl 2015.01.09 where this is fixed.
