### ISSUE TITLE
[crunchyroll] Licensing restrictions.

### ISSUE THREAD

**Issue by Belderak** [rg3/youtube-dl#4676]
ERROR: crunchyroll returned error: Sorry, this video is not available in your region due to licensing restrictions.
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-u', u'PRIVATE', '-p', u'PRIVATE', 'http://www.crunchyroll.fr/shonen-hollywood-holly-stage-for-49-/episode-14-667969', '--verbose', '-f', '720p', '--sub-format=ass', '--write-sub', '-o', '.flv']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.01.09.2
[debug] Python version 2.7.6 - Linux-3.13.0-43-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: ffmpeg 2.5.2, ffprobe 2.5.2, rtmpdump 2.4
[debug] Proxy map: {}
[Crunchyroll] Logging in
[Crunchyroll] 667969: Downloading webpage
ERROR: crunchyroll returned error: Sorry, this video is not available in your region due to licensing restrictions.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 588, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 257, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/crunchyroll.py", line 209, in _real_extract
    raise ExtractorError('crunchyroll returned error: %s' % msg['message_body'], expected=True)
ExtractorError: crunchyroll returned error: Sorry, this video is not available in your region due to licensing restrictions.

I can't download it due to localization but my account is french and I should be able to download it.

Thanks a lot :)

**Comment by Belderak** [comment]
My bad. It was my fault. There's some restrictions because of my ip adress. To bypass, I had to use a french vpn :)
