### ISSUE TITLE
[Bug] certain old npo.nl Silverlight video-streams not recognized

### ISSUE THREAD

**Issue by corone17** [rg3/youtube-dl#4679]
Link: http://www.npo.nl/valentijn/15-05-2013/WO_VARA_010361
(Reference: #4276)

```
youtube-dl.exe -vF http://www.npo.nl/valentijn/15-05-2013/WO_VARA_010361
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-vF', 'http://www.npo.nl/valentijn/15-05-2013/WO_VARA_010361']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.01.10.2
[debug] Python version 2.7.8 - Windows-XP-5.1.2600-SP3
[debug] exe versions: ffmpeg N-65810-g1b5ec6a
[debug] Proxy map: {}
[npo.nl] WO_VARA_010361: Downloading JSON metadata
[npo.nl] WO_VARA_010361: Downloading token
[npo.nl] WO_VARA_010361: Downloading stream 0 ASX playlist
[npo.nl] WO_VARA_010361: Downloading stream 1 ASX playlist
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "youtube_dl\__init__.pyo", line 365, in main
  File "youtube_dl\__init__.pyo", line 355, in _real_main
  File "youtube_dl\YoutubeDL.pyo", line 1208, in download
  File "youtube_dl\YoutubeDL.pyo", line 600, in extract_info
  File "youtube_dl\extractor\common.pyo", line 260, in extract
  File "youtube_dl\extractor\npo.pyo", line 75, in _real_extract
  File "youtube_dl\extractor\npo.pyo", line 152, in _get_info
  File "youtube_dl\utils.pyo", line 1273, in parse_duration
AttributeError: 'bool' object has no attribute 'strip'
```

**Comment by corone17** [comment]
Fix confirmed. It's working perfectly now.
Thanks a lot!
