### ISSUE TITLE
Add support for grooveshark albums, artists and playlists

### ISSUE THREAD

**Issue by Kokxx** [rg3/youtube-dl#4694]
Follow-up to #1968 

The grooveshark extractor is currently only able to download single songs. It would be a great improvement to support albums, artists and playlists.
Example URLs:
Artist: [grooveshark.com/#!/artist/Eminem/276](grooveshark.com/#!/artist/Eminem/276)
Album: [http://grooveshark.com/#!/album/Relapse/2925887](http://grooveshark.com/#!/album/Relapse/2925887)
Playlist/Broadcast: [http://grooveshark.com/#!/ethan1397/broadcast/54b4db7dc0746749418b4567](http://grooveshark.com/#!/ethan1397/broadcast/54b4db7dc0746749418b4567)

Currently the URL will not be detected by the grooveshark extractor (I am using the latest git version of youtube-dl):
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://grooveshark.com/#!/album/Relapse/2925887']
WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
[debug] Encodings: locale ANSI_X3.4-1968, fs ascii, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
[debug] youtube-dl version 2015.01.11
[debug] Git HEAD: a5fb718
[debug] Python version 3.4.2 - Linux-3.17.6-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 2.5.3, ffprobe 2.5.3, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 2925887: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 2925887: Downloading webpage
[generic] 2925887: Extracting information
ERROR: Unsupported URL: http://grooveshark.com/#!/album/Relapse/2925887
Traceback (most recent call last):
  File "/home/kokxx/dev/python/youtube-dl/youtube_dl/YoutubeDL.py", line 600, in extract_info
    ie_result = ie.extract(url)
  File "/home/kokxx/dev/python/youtube-dl/youtube_dl/extractor/common.py", line 260, in extract
    return self._real_extract(url)
  File "/home/kokxx/dev/python/youtube-dl/youtube_dl/extractor/generic.py", line 1075, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: http://grooveshark.com/#!/album/Relapse/2925887
```

**Comment by fleuryc** [comment]
:+1:

**Comment by yan12125** [comment]
Unfortunately Grooveshark was shut down yesterday. See the announcement at http://grooveshark.com/. Closing.
