### ISSUE TITLE
youtube-dl wont run, because it is missing something lewd.

### ISSUE THREAD

**Issue by lordzweigar** [rg3/youtube-dl#4699]
qt@werk:~$ youtube-dl
Traceback (most recent call last):
  File "/usr/bin/youtube-dl", line 3, in <module>
    import youtube_dl
  File "/usr/lib64/python2.7/site-packages/youtube_dl/__init__.py", line 41, in <module>
    from .extractor import gen_extractors
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/__init__.py", line 109, in <module>
    from .empflix import EMPFlixIE
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/empflix.py", line 3, in <module>
    from .tnaflix import TNAFlixIE
ImportError: No module named tnaflix

I'm running Sabayon Linux; latest version.

**Comment by dstftw** [comment]
Post the **full** output you get when running [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by lordzweigar** [comment]
qt@werk:~$ youtube-dl --verbose
Traceback (most recent call last):
  File "/usr/bin/youtube-dl", line 3, in <module>
    import youtube_dl
  File "/usr/lib64/python2.7/site-packages/youtube_dl/__init__.py", line 41, in <module>
    from .extractor import gen_extractors
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/__init__.py", line 109, in <module>
    from .empflix import EMPFlixIE
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/empflix.py", line 3, in <module>
    from .tnaflix import TNAFlixIE
ImportError: No module named tnaflix

**Comment by lordzweigar** [comment]
Youtube-dl was updated when running a system update, I am unable to run youtube-dl -U

**Comment by dstftw** [comment]
Most likely you are using some old `gentoo_no_offensive_sites` version from gentoo repos with dropped "offensive" extractiors.
I encourage you to install youtube-dl manually according to [our FAQ](https://yt-dl.org/update). Feel free to open a new issue if you will have troubles with actual latest version that is `2015.01.11` atm.
