### ISSUE TITLE
VideoMega not working?

### ISSUE THREAD

**Issue by api984** [rg3/youtube-dl#4703]
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 600, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 260, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/videomega.py", line 35, in _real_extract
    r'unescape\("([^"]+)"\)', webpage, 'escaped data')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 516, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract escaped data;

updated to latest.

**Comment by jaimeMF** [comment]
Please [post the **full output** you get when you add the `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs), there's nothing we can do without more information (you haven't even post the url you are trying to download).

**Comment by naglis** [comment]
This issue should be fixed in the next release of youtube-dl. Thanks for the report. However, as @jaimeMF mentioned, next time please include the complete output of youtube-dl with the `--verbose` option, it helps us a lot.

**Comment by api984** [comment]
Sorry about that…. http://videomega.tv/?ref=G64G3RFB0000BFR3G46G

**Comment by dstftw** [comment]
VideoMega was fixed in youtube-dl 2015.01.15.1. Refer to [our FAQ](https://yt-dl.org/update) if you need help updating.
