### ISSUE TITLE
Vevo Videos Broken

### ISSUE THREAD

**Issue by psycotica0** [rg3/youtube-dl#4710]
Hello.
I noticed yesterday that another youtube scraper was broken, but you guys still worked.

Then earlier today they both worked with no changes, but now neither works.

Here's my trace:
$ youtube_dl -v "https://www.youtube.com/watch?v=0KSOMA3QBU0"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=0KSOMA3QBU0']
[debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8
[debug] youtube-dl version 2014.11.13.1
[debug] Git HEAD: 68d1d41
[debug] Python version 2.7.6 - Linux-3.13.0-43-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.16-6, avprobe 9.16-6
[debug] Proxy map: {}
[youtube] Confirming age
[youtube] 0KSOMA3QBU0: Downloading webpage
[youtube] 0KSOMA3QBU0: Downloading video info webpage
[youtube] 0KSOMA3QBU0: Extracting video information
[youtube] 0KSOMA3QBU0: Encrypted signatures detected.
[youtube] {22} signature length 45.40, html5 player en_US-vfl86Quee
[youtube] 0KSOMA3QBU0: Downloading js player vfl86Quee
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/home/psycotica0/Code/youtube-dl/youtube_dl/extractor/youtube.py", line 539, in _decrypt_signature
    video_id, player_url, s
  File "/home/psycotica0/Code/youtube-dl/youtube_dl/extractor/youtube.py", line 453, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/home/psycotica0/Code/youtube-dl/youtube_dl/extractor/youtube.py", line 514, in _parse_sig_js
    'Initial JS player signature function name')
  File "/home/psycotica0/Code/youtube-dl/youtube_dl/extractor/common.py", line 436, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
 (caused by RegexNotFoundError(u'Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.',)); please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/home/psycotica0/Code/youtube-dl/youtube_dl/extractor/youtube.py", line 539, in _decrypt_signature
    video_id, player_url, s
  File "/home/psycotica0/Code/youtube-dl/youtube_dl/extractor/youtube.py", line 453, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/home/psycotica0/Code/youtube-dl/youtube_dl/extractor/youtube.py", line 514, in _parse_sig_js
    'Initial JS player signature function name')
  File "/home/psycotica0/Code/youtube-dl/youtube_dl/extractor/common.py", line 436, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/home/psycotica0/Code/youtube-dl/youtube_dl/YoutubeDL.py", line 536, in extract_info
    ie_result = ie.extract(url)
  File "/home/psycotica0/Code/youtube-dl/youtube_dl/extractor/common.py", line 199, in extract
    return self._real_extract(url)
  File "/home/psycotica0/Code/youtube-dl/youtube_dl/extractor/youtube.py", line 934, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/home/psycotica0/Code/youtube-dl/youtube_dl/extractor/youtube.py", line 549, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/home/psycotica0/Code/youtube-dl/youtube_dl/extractor/youtube.py", line 539, in _decrypt_signature
    video_id, player_url, s
  File "/home/psycotica0/Code/youtube-dl/youtube_dl/extractor/youtube.py", line 453, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/home/psycotica0/Code/youtube-dl/youtube_dl/extractor/youtube.py", line 514, in _parse_sig_js
    'Initial JS player signature function name')
  File "/home/psycotica0/Code/youtube-dl/youtube_dl/extractor/common.py", line 436, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
 (caused by RegexNotFoundError(u'Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.',)); please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by psycotica0** [comment]
Hang on. Maybe I'm too late.

**Comment by dstftw** [comment]
This issue was fixed in youtube-dl 2015.01.15.1. Refer to [our FAQ](https://yt-dl.org/update) if you need help updating.
