### ISSUE TITLE
Youtube signature decipher Error

### ISSUE THREAD

**Issue by docsuleman** [rg3/youtube-dl#4712]
I am using youtube-dl with YSD helper. it was working fine until recently it started giving me this error of signature extraction. 

[youtube] (YSD video): Downloading js player en_US-vfl86Quee
Traceback (most recent call last):
  File "./yt-api.py", line 37, in <module>
    print(sig_extractor._decrypt_signature(sig, u'(YSD video)', url, False))
  File "/home/admin/web/server1.yt-api.com/public_html/youtube_dl/extractor/youtube.py", line 613, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):

 File "/home/admin/web/server1.yt-api.com/public_html/youtube_dl/extractor/youtube.py", line 613, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/home/admin/web/server1.yt-api.com/public_html/youtube_dl/extractor/youtube.py", line 603, in _decrypt_signature
    video_id, player_url, s
  File "/home/admin/web/server1.yt-api.com/public_html/youtube_dl/extractor/youtube.py", line 517, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/home/admin/web/server1.yt-api.com/public_html/youtube_dl/extractor/youtube.py", line 578, in _parse_sig_js
    'Initial JS player signature function name')
  File "/home/admin/web/server1.yt-api.com/public_html/youtube_dl/extractor/common.py", line 492, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError(u'Unable to extract \x1b[0;34mInitial JS player signature function name\x1b[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

It seem like youtube has updated its decipher algorithm again. can any body fix this? Thanks in advance

**Comment by dstftw** [comment]
This is already fixed and will be available in the next release. Thanks for the report.

**Comment by docsuleman** [comment]
Thank you so much :) waiting for next release :)

**Comment by dstftw** [comment]
This issue was fixed in youtube-dl 2015.01.15.1. Refer to [our FAQ](https://yt-dl.org/update) if you need help updating.
