### ISSUE TITLE
RegexNotFoundError: Unable to extract h

### ISSUE THREAD

**Issue by Munksgaard** [rg3/youtube-dl#4724]
I'm trying to download a video from a private page but I get this error:

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '-u', u'PRIVATE', '-p', u'PRIVATE', 'https://www.facebook.com/video.php?v=10152962205232567']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.01.15.1-gentoo_no_offensive_sites
[debug] Python version 2.7.9 - Linux-3.19.0-rc2-eudyptula-00219-g693a30b8-x86_64-Intel-R-_Core-TM-_i7-4600U_CPU_@_2.10GHz-with-gentoo-2.2
[debug] exe versions: ffmpeg 2.2.11, ffprobe 2.2.11
[debug] Proxy map: {}
[facebook] Downloading login page
[facebook] Logging in
ERROR: Unable to extract h; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 600, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/common.py", line 259, in extract
    self.initialize()
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/common.py", line 254, in initialize
    self._real_initialize()
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/facebook.py", line 107, in _real_initialize
    self._login()
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/facebook.py", line 93, in _login
    r'name="h"\s+(?:\w+="[^"]+"\s+)*?value="([^"]+)"', login_results, 'h'),
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/common.py", line 516, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract h; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

```
$ youtube-dl --version
2015.01.15.1-gentoo_no_offensive_sites
```

**Comment by Munksgaard** [comment]
Ah, turns out it was my own fault, Facebook didn't recognize the browser and didn't let me authenticate.
