### ISSUE TITLE
site support request: abc7news.com

### ISSUE THREAD

**Issue by privong** [rg3/youtube-dl#4734]
```
$ youtube-dl --version
2015.01.11

$ youtube-dl --verbose http://abc7news.com/entertainment/east-bay-museum-celebrates-vintage-synthesizers/472581/
[debug] System config: []
[debug] User config: ['--console-title']
[debug] Command-line args: ['--verbose', 'http://abc7news.com/entertainment/east-bay-museum-celebrates-vintage-synthesizers/472581/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.01.11
[debug] Python version 3.4.2 - Linux-3.18.2-2-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 2.5.3, ffprobe 2.5.3, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 472581: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 472581: Downloading webpage
[generic] 472581: Extracting information
ERROR: Unsupported URL: http://abc7news.com/entertainment/east-bay-museum-celebrates-vintage-synthesizers/472581/
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 600, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 260, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/generic.py", line 1075, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: http://abc7news.com/entertainment/east-bay-museum-celebrates-vintage-synthesizers/472581/
```

**Comment by dstftw** [comment]
abc7news will be supported in the next version. Thanks for the report.

**Comment by privong** [comment]
Thanks, @dstftw!
