### ISSUE TITLE
site support request: hearthis.at

### ISSUE THREAD

**Issue by privong** [rg3/youtube-dl#4743]
```
$ youtube-dl --verbose https://hearthis.at/moofi/dr-kreep/ 
[debug] System config: []
[debug] User config: ['--console-title']
[debug] Command-line args: ['--verbose', 'https://hearthis.at/moofi/dr-kreep/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.01.11
[debug] Python version 3.4.2 - Linux-3.18.2-2-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 2.5.3, ffprobe 2.5.3, rtmpdump 2.4
[debug] Proxy map: {}
[generic] dr-kreep: Requesting header
WARNING: Falling back on generic information extractor.
[generic] dr-kreep: Downloading webpage
[generic] dr-kreep: Extracting information
ERROR: Unsupported URL: https://hearthis.at/moofi/dr-kreep/
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 600, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 260, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/generic.py", line 1075, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://hearthis.at/moofi/dr-kreep/
```

**Comment by naglis** [comment]
Support for hearthis.at has been added and should be available in the next release of youtube-dl. Thank you for the report.

**Comment by privong** [comment]
Great, thanks for the quick turnaround, @naglis.

**Comment by naglis** [comment]
youtube-dl 2015.01.22 and newer should support hearthis.at. Refer to our [FAQ](https://yt-dl.org/update) if you need help updating.
