### ISSUE TITLE
NDTV plugin need update

### ISSUE THREAD

**Issue by TheGr33k** [rg3/youtube-dl#4746]
Example url : http://www.ndtv.com/video/live/channel/ndtv24x7

youtube-dl --verbose  -g http://www.ndtv.com/video/live/channel/ndtv24x7
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '-g', 'http://www.ndtv.com/video/live/channel/ndtv24x7']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.01.16
[debug] Python version 2.7.9 - Linux-3.10.0-123.13.2.el7.x86_64-x86_64-with-centos-7.0.1406-Core
[debug] exe versions: none
[debug] Proxy map: {}
WARNING: Falling back on generic information extractor.
ERROR: Unsupported URL: http://www.ndtv.com/video/live/channel/ndtv24x7
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 670, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1504, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/local/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/local/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/local/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 49, column 81
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 600, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 260, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1075, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.ndtv.com/video/live/channel/ndtv24x7

**Comment by phihag** [comment]
Note that this is a live URL; the extraction process for those is completely different than the one for NDTV videos.

**Comment by adamgilchristt1** [comment]
Here you can find out NDTV Live Streams or Player goo.gl/g0osNg with quality. i searching for the live streams, but no one providing. here i found out sharing with you. Check once.
