### ISSUE TITLE
Bilibili broken again

### ISSUE THREAD

**Issue by shichao-an** [rg3/youtube-dl#4750]
Version 2015.01.16 seemed to work a few days ago, although when tested with a 20-min video, youtude-dl only gets an 5-min clip (initial part of the video instead of the whole).

Now the entire extractor seems broken:

```
$ youtube-dl http://www.bilibili.com/video/av530528/index_11.html --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://www.bilibili.com/video/av530528/index_11.html', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.01.16
[debug] Python version 2.7.8 - Darwin-14.0.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[BiliBili] 530528: Downloading webpage
ERROR: Unable to extract video code; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/Users/shichao/envs/youtube-dl/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 600, in extract_info
    ie_result = ie.extract(url)
  File "/Users/shichao/envs/youtube-dl/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 260, in extract
    return self._real_extract(url)
  File "/Users/shichao/envs/youtube-dl/lib/python2.7/site-packages/youtube_dl/extractor/bilibili.py", line 34, in _real_extract
    r'(?s)<div itemprop="video".*?>(.*?)</div>', webpage, 'video code')
  File "/Users/shichao/envs/youtube-dl/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 516, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video code; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by dstftw** [comment]
Could you run it with `--write-pages` and upload `*.dump` files that will be created?

**Comment by shichao-an** [comment]
It seems it is working today (no broken problem), but still, only part of the whole video is downloaded. For the link above, the downloaded video (in flv format) is only 6 minutes long, though it should be approx 20 minutes.

I put the dump files in a single gist at https://gist.github.com/shichao-an/03e49eaf02fec307ad1a

**Comment by yan12125** [comment]
The video you provide has multiple parts, and I've extend BiliBili extractor so that multipart videos can be downloaded correctly. (See  c4a21bc9db1868e8be114f496899f6786b9982ec) If you still encounter problems, feel free to open a new issue.
