### ISSUE TITLE
Some video cannot be downloaded 

### ISSUE THREAD

**Issue by whatvn** [rg3/youtube-dl#4751]
```bash
 $ youtube-dl https://www.youtube.com/watch?v=YPqKCnL8eJY
[youtube] YPqKCnL8eJY: Downloading webpage
[youtube] YPqKCnL8eJY: Extracting video information
[youtube] YPqKCnL8eJY: Downloading DASH manifest
[download] Destination: [MV] Bro '그런 남자' - 그런 남자-YPqKCnL8eJY.mp4
[download] 100% of 16.24MiB in 00:01
[root@server youtubedl]# youtube-dl http://www.youtube.com/watch?v=RKhsHGfrFmY
[youtube] RKhsHGfrFmY: Downloading webpage
[youtube] RKhsHGfrFmY: Extracting video information
[youtube] RKhsHGfrFmY: Downloading js player en_US-vfl19kCnd
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 588, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 502, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 563, in _parse_sig_js
    'Initial JS player signature function name')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 489, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError(u'Unable to extract \x1b[0;34mInitial JS player signature function name\x1b[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by phihag** [comment]
> Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by JarRawr** [comment]
It's happening to me too.
`youtube-dl -f 5 http://youtube.com/watch?v=2vjPBrBU-TM --id --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-f', '5', 'http://youtube.com/watch?v=2vjPBrBU-TM', '--id', '--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.01.16
[debug] Python version 2.7.3 - Linux-2.6.32-042stab102.9-i686-with-debian-7.8
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] 2vjPBrBU-TM: Downloading webpage
[youtube] 2vjPBrBU-TM: Downloading video info webpage
[youtube] 2vjPBrBU-TM: Extracting video information
ERROR: Unable to extract JS player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 836, in _real_extract
    raise ValueError('Could not find ytplayer.config')  # caught below
ValueError: Could not find ytplayer.config
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 600, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 260, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1022, in _real_extract
    embed_webpage if age_gate else video_webpage, 'JS player URL')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 516, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract JS player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
`

**Comment by phihag** [comment]
@JarRawr Your error is completely different - even the error message is another one! Please [open a new issue](https://github.com/rg3/youtube-dl/issues/new).

**Comment by whatvn** [comment]
hmm, today I suddenly  can download that file, don't know why. 
```bash
 youtube-dl --verbose http://www.youtube.com/watch?v=RKhsHGfrFmY
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.youtube.com/watch?v=RKhsHGfrFmY']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.12.16
[debug] Python version 2.6.6 - Linux-2.6.32-279.el6.x86_64-x86_64-with-centos-6.3-Final
[debug] exe versions: ffmpeg 0.6.5, ffprobe 0.6.5
[debug] Proxy map: {}
[youtube] RKhsHGfrFmY: Downloading webpage
[youtube] RKhsHGfrFmY: Extracting video information
[youtube] {22} signature length 42.40, html5 player en_US-vflbHLA_P
[youtube] RKhsHGfrFmY: Downloading js player en_US-vflbHLA_P
[youtube] {43} signature length 42.40, html5 player en_US-vflbHLA_P
[youtube] {18} signature length 42.40, html5 player en_US-vflbHLA_P
[youtube] {5} signature length 42.40, html5 player en_US-vflbHLA_P
[youtube] {36} signature length 42.40, html5 player en_US-vflbHLA_P
[youtube] {17} signature length 42.40, html5 player en_US-vflbHLA_P
[youtube] {137} signature length 42.40, html5 player en_US-vflbHLA_P
[youtube] {248} signature length 42.40, html5 player en_US-vflbHLA_P
[youtube] {136} signature length 42.40, html5 player en_US-vflbHLA_P
[youtube] {247} signature length 42.40, html5 player en_US-vflbHLA_P
[youtube] {135} signature length 42.40, html5 player en_US-vflbHLA_P
[youtube] {244} signature length 42.40, html5 player en_US-vflbHLA_P
[youtube] {134} signature length 42.40, html5 player en_US-vflbHLA_P
[youtube] {243} signature length 42.40, html5 player en_US-vflbHLA_P
[youtube] {133} signature length 42.40, html5 player en_US-vflbHLA_P
[youtube] {242} signature length 42.38, html5 player en_US-vflbHLA_P
[youtube] RKhsHGfrFmY: Downloading js player en_US-vflbHLA_P
[youtube] {160} signature length 42.40, html5 player en_US-vflbHLA_P
[youtube] {140} signature length 42.40, html5 player en_US-vflbHLA_P
[youtube] {171} signature length 42.40, html5 player en_US-vflbHLA_P
[youtube] RKhsHGfrFmY: Downloading DASH manifest
[debug] Invoking downloader on u'https://r7---sn-8pxuuxa-i5or.googlevideo.com/videoplayback?source=youtube&sparams=dur%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Cmime%2Cmm%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&fexp=900718%2C907263%2C927622%2C941004%2C943917%2C947209%2C947225%2C948124%2C952302%2C952605%2C952901%2C953900%2C955301%2C957103%2C957105%2C957201%2C959701&sver=3&dur=225.628&expire=1421850836&initcwndbps=1510000&requiressl=yes&ip=125.212.220.133&ms=au&mv=m&mt=1421829179&pl=21&mime=video%2Fmp4&id=o-ADyl214fGW-jYN5POFdF2PpnczXuDD92C-nDDvfuPQ7U&mm=31&ipbits=0&itag=22&key=yt5&ratebypass=yes&upn=1jFKqqcpWYA&signature=B82B25E4AEEFACEF2589FF388AB2DD661A474A99.0ED69C87E62556ABE1218CB60EEEA80B04019104'
[download] Destination: G-DRAGON - 삐딱하게 (CROOKED) M_V-RKhsHGfrFmY.mp4
[download] 100% of 85.36MiB in 00:07
```

**Comment by jaimeMF** [comment]
I'm closing the issue then. If it fails again, please post the output with the `--verbose` option and we will reopen the issue.
