### ISSUE TITLE
Signature extraction failed

### ISSUE THREAD

**Issue by alt0v14** [rg3/youtube-dl#4755]
alt@LM85:~/Музыка/YouTube$ ./youtube-dl --verbose -x https://www.youtube.com/watch?v=iyTTX6Wlf1Y
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '-x', 'https://www.youtube.com/watch?v=iyTTX6Wlf1Y']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.11.13.3
[debug] Python version 2.7.6 - Linux-3.13.0-44-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.16-6, avprobe 9.16-6, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] Confirming age
[youtube] iyTTX6Wlf1Y: Downloading webpage
[youtube] iyTTX6Wlf1Y: Downloading video info webpage
[youtube] iyTTX6Wlf1Y: Extracting video information
[youtube] iyTTX6Wlf1Y: Encrypted signatures detected.
[youtube] {22} signature length 41.41, html5 player en_US-vfl19kCnd
[youtube] iyTTX6Wlf1Y: Downloading js player vfl19kCnd
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/extractor/youtube.py", line 539, in _decrypt_signature
    video_id, player_url, s
  File "./youtube-dl/youtube_dl/extractor/youtube.py", line 453, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "./youtube-dl/youtube_dl/extractor/youtube.py", line 514, in _parse_sig_js
    'Initial JS player signature function name')
  File "./youtube-dl/youtube_dl/extractor/common.py", line 436, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
 (caused by RegexNotFoundError(u'Unable to extract \x1b[0;34mInitial JS player signature function name\x1b[0m; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.',)); please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/extractor/youtube.py", line 539, in _decrypt_signature
    video_id, player_url, s
  File "./youtube-dl/youtube_dl/extractor/youtube.py", line 453, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "./youtube-dl/youtube_dl/extractor/youtube.py", line 514, in _parse_sig_js
    'Initial JS player signature function name')
  File "./youtube-dl/youtube_dl/extractor/common.py", line 436, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 536, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 199, in extract
    return self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/youtube.py", line 934, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "./youtube-dl/youtube_dl/extractor/youtube.py", line 549, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/extractor/youtube.py", line 539, in _decrypt_signature
    video_id, player_url, s
  File "./youtube-dl/youtube_dl/extractor/youtube.py", line 453, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "./youtube-dl/youtube_dl/extractor/youtube.py", line 514, in _parse_sig_js
    'Initial JS player signature function name')
  File "./youtube-dl/youtube_dl/extractor/common.py", line 436, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
 (caused by RegexNotFoundError(u'Unable to extract \x1b[0;34mInitial JS player signature function name\x1b[0m; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.',)); please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by alt0v14** [comment]
Sorry works on new version.
