### ISSUE TITLE
Unable to download some YouTube videos

### ISSUE THREAD

**Issue by JarRawr** [rg3/youtube-dl#4760]
Several YouTube videos seem to not work, one of them being ebXbLfLACGM.
` youtube-dl -v -f 5 http://youtube.com/watch?v=ebXbLfLACGM --id
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', '-f', '5', 'http://youtube.com/watch?v=ebXbLfLACGM', '--id']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.01.16
[debug] Python version 2.7.3 - Linux-2.6.32-042stab102.9-i686-with-debian-7.8
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] ebXbLfLACGM: Downloading webpage
[youtube] ebXbLfLACGM: Downloading video info webpage
[youtube] ebXbLfLACGM: Extracting video information
ERROR: Unable to extract JS player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 836, in _real_extract
    raise ValueError('Could not find ytplayer.config')  # caught below
ValueError: Could not find ytplayer.config
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 600, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 260, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1022, in _real_extract
    embed_webpage if age_gate else video_webpage, 'JS player URL')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 516, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract JS player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
`

**Comment by JarRawr** [comment]
I've figured out the issue, the video was being blocked because of country.
