### ISSUE TITLE
VideoMega broken again i think?

### ISSUE THREAD

**Issue by api984** [rg3/youtube-dl#4763]
$ youtube-dl -v http://videomega.tv/?ref=I6KSDVV579975VVDSK6I
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://videomega.tv/?ref=I6KSDVV579975VVDSK6I']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.01.16
[debug] Python version 2.7.1 - Darwin-11.4.2-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[VideoMega] I6KSDVV579975VVDSK6I: Downloading webpage
[debug] Invoking downloader on u'http://st105.u1.videomega.tv/v/6f6d9ef30f19bfac28502823b3305193.mp4?st=GRznnMNqIweW1csFVBJk8g&hash=mwDjCRlNe7zYzSTlV3W3oA'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1155, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1131, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 308, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 67, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1412, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 400, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 513, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 438, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 372, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 521, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden

must be some new protection i think....

**Comment by Kaligule** [comment]
I tried to reproduce the bug. The error message is different for me (Fedora 20)
$ youtube-dl --version
2014.12.10.3
$ youtube-dl -v "http://videomega.tv/?ref=I6KSDVV579975VVDSK6I"
[debug] System config: ['--prefer-free-formats']
[debug] User config: []
[debug] Command-line args: ['-v', 'http://videomega.tv/?ref=I6KSDVV579975VVDSK6I']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.12.10.3
[debug] Python version 2.7.5 - Linux-3.17.8-200.fc20.x86_64-x86_64-with-fedora-20-Heisenbug
[debug] exe versions: none
[debug] Proxy map: {}
[VideoMega] I6KSDVV579975VVDSK6I: Downloading webpage
ERROR: Unable to extract escaped data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 554, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 242, in extract
    return self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/videomega.py", line 37, in _real_extract
    r'unescape\("([^"]+)"\)', webpage, 'escaped data')
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 484, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract escaped data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by api984** [comment]
i dont get it why its different... strange ... something must have changed....

**Comment by naglis** [comment]
Thanks for the report. This issue should be fixed in the next release of youtube-dl.

Indeed, this is the second time videomega has changed in the short while, not sure why.

@Kaligule, the output you get is different because you are running an older version of youtube-dl (the videomega extractor has been updated recently).

**Comment by Kaligule** [comment]
Thanks
