### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 17: ordinal not in range(128)

### ISSUE THREAD

**Issue by gdudau** [rg3/youtube-dl#4775]
This is happend when i want to extract audio using this command:
youtube-dl -x --audio-format "mp3" --audio-quality 0 "https://www.youtube.com/watch?v=7kHCOwakEIM"

[debug] System config: ['--prefer-free-formats']
[debug] User config: []
[debug] Command-line args: ['--verbose', '--extract-audio', '--audio-format', 'mp3', '--audio-quality', '0', 'https://www.youtube.com/watch?v=7kHCOwakEIM']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.01.23.4
[debug] Python version 2.7.5 - Linux-3.17.6-200.fc20.x86_64-x86_64-with-fedora-20-Heisenbug
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/bin/youtube-dl/youtube_dl/__init__.py", line 366, in main
  File "/usr/bin/youtube-dl/youtube_dl/__init__.py", line 335, in _real_main
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 300, in __init__
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1524, in print_debug_header
  File "/usr/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 51, in get_versions
  File "/usr/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 51, in <genexpr>
  File "/usr/bin/youtube-dl/youtube_dl/utils.py", line 1322, in get_exe_version
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 17: ordinal not in range(128)

This not happend if i use:
youtube-dl  "https://www.youtube.com/watch?v=7kHCOwakEIM"

Only audio extract is affected.

**Comment by dstftw** [comment]
Post the **full** output you get when running [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by gdudau** [comment]
i edited

**Comment by dstftw** [comment]
Could you also post the output of `ffmpeg -version` and `whereis ffmpeg`?

**Comment by gdudau** [comment]
path - **/bin/ffmpeg**
ffmpeg version 2.1.7 Copyright (c) 2000-2014 the FFmpeg developers
  built on Jan  3 2015 22:57:36 with gcc 4.8.3 (GCC) 20140911 (Red Hat 4.8.3-7)

FFMPEG it's working standalone:
for vid in *.mp4; do ffmpeg -i "$vid" -vn -acodec libmp3lame "${vid%}.mp3"; done 
MP3 is extracted from video.

**Comment by gdudau** [comment]
ffmpeg: 
/usr/bin/ffmpeg 
/usr/share/ffmpeg 
/usr/share/man/man1/ffmpeg.1.gz

**Comment by gdudau** [comment]
If i add 
**--prefer-ffmpeg** 
**--ffmpeg-location "/usr/bin/ffmpeg"** all are OK.

No error.

youtube-dl --prefer-ffmpeg --ffmpeg-location "/usr/bin/ffmpeg" --extract-audio --audio-format "mp3"   --audio-quality 0 "https://www.youtube.com/watch?v=7kHCOwakEIM"
