### ISSUE TITLE
bestvideo+bestaudio prevent video from playing

### ISSUE THREAD

**Issue by dragonmoony** [rg3/youtube-dl#4797]
using youtube-dl and MPV, I get an error when trying to play this one link: http://youtu.be/FltfN5TnrTA all other videos work fine. I found that removing "ytdl-format=bestvideo+bestaudio/best" from mpv.conf fixes the issue but then I lose the benefit of that line. pretty much all other videos work fine with that line intact.

both mvp and youtube-dl are up to date and that video link works fine in my browser (and works fine without the bestvideo+bestaudio line)

**Comment by jaimeMF** [comment]
You should always [post the output you get when running `youtube-dl --verbose URL OTHER_OPTIONS`](https://github.com/rg3/youtube-dl#bugs), it helps us for debugging issues, and in this case it could be a problem in mpv. For reference, here it is:
```shell
$ youtube-dl --ignore-config  'http://youtu.be/FltfN5TnrTA' -f bestvideo+bestaudio/best --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--ignore-config', 'http://youtu.be/FltfN5TnrTA', '-f', 'bestvideo+bestaudio/best', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.01.25
[debug] Git HEAD: 3a0d2f5
[debug] Python version 3.4.2 - Darwin-13.4.0-x86_64-i386-64bit
[debug] exe versions: avconv 11.2, avprobe 11.2, ffmpeg 2.5.3, ffprobe 2.5.3, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] FltfN5TnrTA: Downloading webpage
[youtube] FltfN5TnrTA: Extracting video information
[youtube] FltfN5TnrTA: Downloading DASH manifest
[debug] Invoking downloader on 'https://r9---sn-h5q7enl7.googlevideo.com/videoplayback?<removed>'
ERROR: unable to download video data: HTTP Error 410: Gone
Traceback (most recent call last):
  File "<src>/youtube_dl/YoutubeDL.py", line 1275, in process_info
    partial_success = dl(fname, new_info)
  File "<src>/youtube_dl/YoutubeDL.py", line 1256, in dl
    return fd.download(name, info)
  File "<src>/youtube_dl/downloader/common.py", line 316, in download
    return self.real_download(filename, info_dict)
  File "<src>/youtube_dl/downloader/http.py", line 63, in real_download
    data = self.ydl.urlopen(request)
  File "<src>/youtube_dl/YoutubeDL.py", line 1573, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 461, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 571, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 499, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 433, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 579, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 410: Gone
```

This is an error on YouTube, I have tried in Safari and you get the same error if you try to play at 1080p (Chrome uses the webm version instead, which works). Other formats works fine, for example `-f 136+bestaudio` (you can run with `-F` to see all the available formats)
