### ISSUE TITLE
NHL URL failure...

### ISSUE THREAD

**Issue by RingoTheDog** [rg3/youtube-dl#4805]
URL: 
http://www.nhl.com/ice/news.htm?id=750727
http://video.nhl.com/videocenter/?id=736722
 (different URLs, same video...same result)

>youtube-dl.py -v "http://www.nhl.com/ice/news.htm?id=750727"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.nhl.com/ice/news.htm?id=750727']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.01.25
[debug] Python version 2.7.5 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-40824-g31dfe20, rtmpdump 2.4
[debug] Proxy map: {}
[generic] news: Requesting header
WARNING: Falling back on generic information extractor.
[generic] news: Downloading webpage
[generic] news: Extracting information
ERROR: Unsupported URL: http://www.nhl.com/ice/news.htm?id=750727
Traceback (most recent call last):
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\generic.py", line 681, in _real_extract
    doc = parse_xml(webpage)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\utils.py", line 1490, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 88, column 87
Traceback (most recent call last):
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 613, in extract_info
    ie_result = ie.extract(url)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\common.py", line 266, in extract
    return self._real_extract(url)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\generic.py", line 1090, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.nhl.com/ice/news.htm?id=750727

>youtube-dl.py -v "http://video.nhl.com/videocenter/?id=736722"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://video.nhl.com/videocenter/?id=736722']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.01.25
[debug] Python version 2.7.5 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-40824-g31dfe20, rtmpdump 2.4
[debug] Proxy map: {}
[generic] ?id=736722: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ?id=736722: Downloading webpage
[generic] ?id=736722: Extracting information
ERROR: Unsupported URL: http://video.nhl.com/videocenter/?id=736722
Traceback (most recent call last):
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\generic.py", line 681, in _real_extract
    doc = parse_xml(webpage)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\utils.py", line 1490, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 22, column 109
Traceback (most recent call last):
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 613, in extract_info
    ie_result = ie.extract(url)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\common.py", line 266, in extract
    return self._real_extract(url)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\generic.py", line 1090, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://video.nhl.com/videocenter/?id=736722

Thanks (again....)
Ringo

**Comment by dstftw** [comment]
Will be fixed in the next version, thanks for teh report.

**Comment by phihag** [comment]
youtube-dl 2015.02.02 and newer add support for these URLs as well. Unfortunately, the nhl seems to be pretty nimble when it comes to inventing new URL formats. Thanks for the continuing reports! See [our FAQ](https://yt-dl.org/update) if you need help updating.
