### ISSUE TITLE
broken: dr.dk/tv/se/

### ISSUE THREAD

**Issue by alundr** [rg3/youtube-dl#4814]
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://www.dr.dk/tv/se/bla-oejne', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.01.25
[debug] Python version 3.4.2 - Darwin-13.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.4.4-tessus, ffprobe 2.4.4-tessus, rtmpdump 2.4
[debug] Proxy map: {}
[generic] bla-oejne: Requesting header
WARNING: Falling back on generic information extractor.
[generic] bla-oejne: Downloading webpage
[generic] bla-oejne: Extracting information
ERROR: Unsupported URL: http://www.dr.dk/tv/se/bla-oejne
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 613, in extract_info
    ie_result = ie.extract(url)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 266, in extract
    return self._real_extract(url)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/youtube_dl/extractor/generic.py", line 1090, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.dr.dk/tv/se/bla-oejne

Support for dr.dk/tv/se/ was introduced in issue:
Request for additional site http://dr.dk/tv #3126
http://www.dr.dk/tv/se/partiets-mand/partiets-mand-7-8

The solution seems to have worked well in 2014, but now in 2015 we are back to
WARNING: Falling back on generic information extractor, as shown above.

I suspect a connection to issue:
Add support for dr.dk #4581
'http://www.dr.dk/bonanza/serie/portraetter/Talkshowet.htm?assetId=65517'

The /bonanza/ solution is working now, but please note that the two archives, dr.dk/bonanza/ and dr.dk/tv/se/ are organized differently and need separate extractors.

I hope the two solutions can be made to work concurrently.

**Comment by dstftw** [comment]
Will be fixed in the next version. Thanks for the report.

**Comment by alundr** [comment]
Sorry to report that the problem is not solved. It now looks like the issue:
DR Ramasjang not working #3735

My output looks like this:
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://www.dr.dk/tv/se/bla-oejne', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.02.02
[debug] Python version 3.4.2 - Darwin-14.1.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.4.4-tessus, ffprobe 2.4.4-tessus, rtmpdump 2.4
[debug] Proxy map: {}
[DRTV] bla-oejne: Downloading video JSON
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/bin/youtube-dl", line 11, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/youtube_dl/__init__.py", line 382, in main
    _real_main(argv)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/youtube_dl/__init__.py", line 372, in _real_main
    retcode = ydl.download(all_urls)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 1350, in download
    res = self.extract_info(url)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 619, in extract_info
    ie_result = ie.extract(url)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 267, in extract
    return self._real_extract(url)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/youtube_dl/extractor/drtv.py", line 31, in _real_extract
    data = programcard['Data'][0]
IndexError: list index out of range

Please note that the test url http://www.dr.dk/tv/se/partiets-mand/partiets-mand-7-8 no longer contains a video and does not show the error.

**Comment by dstftw** [comment]
Could you name geo unrestricted example URL that yields the same error?

**Comment by dstftw** [comment]
Nevermind. Will be fixed in the next version.

**Comment by alundr** [comment]
Thanks for your fast response, looking forward to testing the next version!

Although a bit late, I suggest this url assuming it is unrestricted (restriction is hard to test when living in Denmark, but DR's own productions should be unrestricted):
http://www.dr.dk/tv/se/bonderoeven/bonderoeven-4-10-5

Actually, now I tested above danish production, and it downloads without any problem!
Is the problem really related to the geo restriction on certain broadcasts?

**Comment by dstftw** [comment]
No, it was not related to geo restriction.

**Comment by phihag** [comment]
I believe this issue to be in youtube-dl 2015.02.02.2. See [our FAQ](https://yt-dl.org/update) if you need help updating.

**Comment by alundr** [comment]
Yes, upgraded to youtube_dl-2015.02.02.5, and now the download works.
Thanks again.
