### ISSUE TITLE
[Bug] npo.nl live videostreams stopped working

### ISSUE THREAD

**Issue by corone17** [rg3/youtube-dl#4830]
```
youtube-dl.exe -vF http://www.npo.nl/live/npo-1
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-vF', 'http://www.npo.nl/live/npo-1']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.01.30.2
[debug] Python version 2.7.8 - Windows-XP-5.1.2600-SP3
[debug] exe versions: ffmpeg N-65810-g1b5ec6a
[debug] Proxy map: {}
[npo.nl:live] npo-1: Downloading webpage
[npo.nl:live] npo-1: Downloading JSON metadata
[npo.nl:live] npo-1: Downloading token
[npo.nl:live] npo-1: Downloading hds JSON
[npo.nl:live] npo-1: Downloading hds URL
[npo.nl:live] npo-1: Downloading f4m manifest
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "youtube_dl\__init__.pyo", line 382, in main
  File "youtube_dl\__init__.pyo", line 372, in _real_main
  File "youtube_dl\YoutubeDL.pyo", line 1349, in download
  File "youtube_dl\YoutubeDL.pyo", line 618, in extract_info
  File "youtube_dl\extractor\common.pyo", line 266, in extract
  File "youtube_dl\extractor\npo.pyo", line 227, in _real_extract
  File "youtube_dl\extractor\common.pyo", line 779, in _extract_f4m_formats
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

**Comment by robin007bond** [comment]
Can confirm this on Linux:
```
youtube-dl -vF http://www.npo.nl/live/npo-1            
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-vF', 'http://www.npo.nl/live/npo-1']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.02.03
[debug] Python version 3.4.2 - Linux-3.18.5-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 2.5.3, ffprobe 2.5.3, rtmpdump 2.4
[debug] Proxy map: {}
[npo.nl:live] npo-1: Downloading webpage
[npo.nl:live] npo-1: Downloading JSON metadata
[npo.nl:live] npo-1: Downloading token
[npo.nl:live] npo-1: Downloading hds JSON
[npo.nl:live] npo-1: Downloading hds URL
[npo.nl:live] npo-1: Downloading f4m manifest
Traceback (most recent call last):
  File "/usr/bin/youtube-dl", line 9, in <module>
    load_entry_point('youtube-dl==2015.2.3', 'console_scripts', 'youtube-dl')()
  File "/usr/lib/python3.4/site-packages/youtube_dl/__init__.py", line 382, in main
    _real_main(argv)
  File "/usr/lib/python3.4/site-packages/youtube_dl/__init__.py", line 372, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 1350, in download
    res = self.extract_info(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 619, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 267, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/npo.py", line 227, in _real_extract
    f4m_formats = self._extract_f4m_formats(stream_url, display_id)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 780, in _extract_f4m_formats
    manifest_url = '/'.join(manifest_url.split('/')[:-1]) + '/' + media_el.attrib.get('href')
TypeError: Can't convert 'NoneType' object to str implicitly
```

**Comment by dstftw** [comment]
Could you post `*.dump` files when running with `--write-pages`?

**Comment by robin007bond** [comment]
@dstftw Sure!

Can I post them here as comment or should I upload them on pastebin for the convenience?

**Comment by dstftw** [comment]
@robin007bond, whichever you like, but don't forget to wrap it in \`\`\` ``` if you post right here.

**Comment by robin007bond** [comment]
http://filebin.ca/1qeSEarjT0eG/npo-1_http_-_l2cm0f9c9ed69f0054d3e83d000000.c79b466fa562c67d.kpnsmoote1e.npostreaming.nl_d_live_npo_tvlive_ned1_ned1.isml_ned1.f4m.dump

http://filebin.ca/1qeSOGwspuyO/npo-1_http_-_livestreams.omroep.nl_live_npo_tvlive_ned1_ned1.isml_ned1.f4mhashdc2d2c95b22584e7514d12a7ac60c2be_typejsonp_protectionurl.dump

http://filebin.ca/1qeSUW6CshT5/npo-1_http_-_ida.omroep.nl_aapi_streamhttp_-_livestreams.omroep.nl_live_npo_tvlive_ned1_ned1.isml_ned1.f4m_tokendno02dodg2piap7vp4935fo4h6_typejsonp.dump

http://filebin.ca/1qeSZCShQ0sJ/npo-1_http_-_ida.omroep.nl_npoplayer_i.js.dump

http://filebin.ca/1qeSf8FrA3M7/npo-1_http_-_e.omroep.nl_metadata_LI_NEDERLAND1_136692.dump

http://filebin.ca/1qeSkkgqbLgl/npo-1_http_-_www.npo.nl_live_npo-1.dump

**Comment by dstftw** [comment]
Thanks. This will be fixed in the next version.

**Comment by corone17** [comment]
Fix confirmed. Thanks a lot, dstftw!
