### ISSUE TITLE
[YouTube] ERROR: Signature extraction failed / WARNING: unable to extract html5 player

### ISSUE THREAD

**Issue by TheBoroer** [rg3/youtube-dl#4835]
Affected Video URL: `http://www.youtube.com/watch?v=ob7fWMLxl9g`
I can post more youtube video links that this happens to if needed.

Command that was run: `/root/youtube-dl --verbose --cookies /root/cookie.txt -s http://www.youtube.com/watch?v=ob7fWMLxl9g`

**NOTE**: it works fine if I remove the "--cookies /root/cookie.txt" parameter.

**Output:**

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '--cookies', '/root/cookie.txt', '-s', 'http://www.youtube.com/watch?v=ob7fWMLxl9g']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.01.30.2
[debug] Python version 2.6.6 - Linux-3.10.23-xxxx-std-ipv6-64-x86_64-with-centos-6.6-Final
[debug] exe versions: ffmpeg 0.6.5, ffprobe 0.6.5
[debug] Proxy map: {}
[youtube] ob7fWMLxl9g: Downloading webpage
[youtube] ob7fWMLxl9g: Extracting video information
WARNING: unable to extract html5 player; please report this issue on http://yt-dl.org/bug
[youtube] {22} signature length 42.44, html5 player None
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/root/youtube-dl/youtube_dl/extractor/youtube.py", line 635, in _decrypt_signature
    video_id, player_url, s
  File "/root/youtube-dl/youtube_dl/extractor/youtube.py", line 531, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
ExtractorError: Cannot identify player u'https://s.ytimg.com/yts/jsbin/playershards-en_US-vflEi9zrf/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Cannot identify player u'https://s.ytimg.com/yts/jsbin/playershards-en_US-vflEi9zrf/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/root/youtube-dl/youtube_dl/extractor/youtube.py", line 635, in _decrypt_signature
    video_id, player_url, s
  File "/root/youtube-dl/youtube_dl/extractor/youtube.py", line 531, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
ExtractorError: Cannot identify player u'https://s.ytimg.com/yts/jsbin/playershards-en_US-vflEi9zrf/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/root/youtube-dl/youtube_dl/YoutubeDL.py", line 618, in extract_info
    ie_result = ie.extract(url)
  File "/root/youtube-dl/youtube_dl/extractor/common.py", line 266, in extract
    return self._real_extract(url)
  File "/root/youtube-dl/youtube_dl/extractor/youtube.py", line 1065, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/root/youtube-dl/youtube_dl/extractor/youtube.py", line 645, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/root/youtube-dl/youtube_dl/extractor/youtube.py", line 635, in _decrypt_signature
    video_id, player_url, s
  File "/root/youtube-dl/youtube_dl/extractor/youtube.py", line 531, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
ExtractorError: Cannot identify player u'https://s.ytimg.com/yts/jsbin/playershards-en_US-vflEi9zrf/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Cannot identify player u'https://s.ytimg.com/yts/jsbin/playershards-en_US-vflEi9zrf/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Contents of cookie.txt**

```
# Netscape HTTP Cookie File
# http://www.netscape.com/newsref/std/cookie_spec.html
# This is a generated file!  Do not edit.

.youtube.com    TRUE    /       FALSE   1427950905      PREF    f1=50000000&hl=en
.youtube.com    TRUE    /       FALSE   1443747462      VISITOR_INFO1_LIVE      3VhnsbVo654
```

**Comment by moldcraft** [comment]
Similar `https://www.youtube.com/watch?v=vSIPaqGjJvk`

**Comment by dstftw** [comment]
@moldcraft you are using an outdated version of youtube-dl. Read [this FAQ entry](https://yt-dl.org/update) if you have troubles updating.
