### ISSUE TITLE
Regression: France culture

### ISSUE THREAD

**Issue by sciunto** [rg3/youtube-dl#4853]
Hi,

I noticed a regression. I remember I was able to get podcast from france culture a couple of weeks (months?) ago.

Here is the backtrace
```
youtube-dl 'http://www.franceculture.fr/player/reecouter?play=4993305' --verbose                                                      22:05
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://www.franceculture.fr/player/reecouter?play=4993305', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.01.25
[debug] Python version 3.4.2 - Linux-3.18.4-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 2.5.3, ffprobe 2.5.3, rtmpdump 2.4
[debug] Proxy map: {}
[FranceCulture] 4993305: Downloading webpage
ERROR: Unable to extract parameter code; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 613, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 266, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/franceculture.py", line 39, in _real_extract
    webpage, 'parameter code')
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 522, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract parameter code; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

The code source of the page provides easily the content:

```
       <a id="player" data-diffusion-id="4993305" href="/sites/default/files/sons/2015/02/s06/NET_FC_1c9131a8-cdda-4ae6-8777-dbe131d39b6f.mp3" data-br="12410" data-magnetotheque="2015C12410S0033" data-date="1422867600" class="jp-jplayer">
        <img src="http://www.franceculture.fr/sites/default/files/imagecache/fc_player_95x95/2012/08/14/4485895/images/player/Les-Nouveaux-chemins-de-la-connaissance.jpg"/>
        <span class="title">Les Nouveaux chemins de la connaissance</span>
        <span class="title-diffusion">Le TTP de Spinoza (1/4) : Qui doit légiférer sur le sacré ?  </span>
        <span class="path-diffusion">emission-les-nouveaux-chemins-de-la-connaissance-le-ttp-de-spinoza-14-qui-doit-legiferer-sur-le-sacr</span>
        <span class="description">Par Adèle Van Reeth Réalisation : Nicolas Berger Lectures : Jean-Louis Jacopin       ...</span>
      </a>
```

Thank you!

**Comment by phihag** [comment]
Thank you for the report, but are you certain that this is a regression? We haven't touched the franceculture code since adding it, so most likely, this is caused by a changed output format of franceculture, and not a bug introduced into youtube-dl.

**Comment by phihag** [comment]
youtube-dl 2015.02.03.1 and newer include support for the new franceculture format. See [our FAQ](https://yt-dl.org/update) if you need help updating.

**Comment by sciunto** [comment]
Thank you so much @phihag :)
