### ISSUE TITLE
Mixcloud still failing on some URLs

### ISSUE THREAD

**Issue by bubbleguuum** [rg3/youtube-dl#4862]
./youtube-dl --verbose -J  http://www.mixcloud.com/gillespeterson/caribou-7-inch-vinyl-mix-chat/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '-J', 'http://www.mixcloud.com/gillespeterson/caribou-7-inch-vinyl-mix-chat/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.02.03.1
[debug] Python version 2.7.3 - Linux-3.2.0-70-generic-x86_64-with-Ubuntu-12.04-precise
[debug] exe versions: avconv 0.10.12-7, avprobe 0.10.12-7, ffmpeg 0.10.12-7, ffprobe 0.10.12-7
[debug] Proxy map: {}
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "./youtube-dl/__main__.py", line 19, in <module>
  File "./youtube-dl/youtube_dl/__init__.py", line 382, in main
  File "./youtube-dl/youtube_dl/__init__.py", line 372, in _real_main
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 1352, in download
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 619, in extract_info
  File "./youtube-dl/youtube_dl/extractor/common.py", line 268, in extract
  File "./youtube-dl/youtube_dl/extractor/mixcloud.py", line 66, in _real_extract
  File "./youtube-dl/youtube_dl/extractor/mixcloud.py", line 41, in _get_url
TypeError: not all arguments converted during string formatting

**Comment by dstftw** [comment]
Thanks for the report, this will be fixed in the next version.

**Comment by phihag** [comment]
I believe this issue to be fixed in youtube-dl 2015.02.09 and newer. See [our FAQ](https://yt-dl.org/update) if you need help updating.
