### ISSUE TITLE
Failed to download stream from wakanim.tv

### ISSUE THREAD

**Issue by Kcchouette** [rg3/youtube-dl#4868]
I have two url from the same video, because wakanim use one without token, and one with a token (after ads)

The one with token 

```
youtube-dl --verbose "http://www.wakanim.tv/video-streaming/?Token1=DCQj-KkyPUiC60FihJfeFQ&Token2=BapNgNp3ekiacHT2GX91aA&Id=1161"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.wakanim.tv/video-streaming/?Token1=DCQj-KkyPUiC60FihJfeFQ&Token2=BapNgNp3ekiacHT2GX91aA&Id=1161']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.02.03
[debug] Python version 3.4.2 - Linux-3.10.23-xxxx-grs-ipv6-64-x86_64-with-arch
[debug] exe versions: ffmpeg 2.5.3, ffprobe 2.5.3, rtmpdump 2.4
[debug] Proxy map: {}
[generic] ?Token1=DCQj-KkyPUiC60FihJfeFQ&Token2=BapNgNp3ekiacHT2GX91aA&Id=1161: Requesting header
[redirect] Following redirect to http://www.wakanim.tv/video/W9/4-a-rome-fais-comme-les-romains-durarara-x2
[generic] 4-a-rome-fais-comme-les-romains-durarara-x2: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 4-a-rome-fais-comme-les-romains-durarara-x2: Downloading webpage
[generic] 4-a-rome-fais-comme-les-romains-durarara-x2: Extracting information
ERROR: Unsupported URL: http://www.wakanim.tv/video/W9/4-a-rome-fais-comme-les-romains-durarara-x2
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 619, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 267, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/generic.py", line 1110, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.wakanim.tv/video/W9/4-a-rome-fais-comme-les-romains-durarara-x2
```

Thanks for all you do :)

**Comment by Kcchouette** [comment]
See #14374
