### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by Billybangleballs** [rg3/youtube-dl#4872]
I encountered this error using youtube-dl version 2015.02.04
/usr/bin/youtube-dl https://www.youtube.com/watch?v=Bb4TPuXCd8U

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/bin/youtube-dl/youtube_dl/__init__.py", line 382, in main

  File "/usr/bin/youtube-dl/youtube_dl/__init__.py", line 372, in _real_main

  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1352, in download
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 619, in extract_info
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 268, in extract
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 802, in _real_extract
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 396, in _download_webpage
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 320, in _download_webpage_handle
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 294, in _request_webpage
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 460, in report_download_webpage
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 452, in to_screen
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 388, in to_screen
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 402, in to_stdout
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 391, in _write_string
  File "/usr/bin/youtube-dl/youtube_dl/utils.py", line 943, in write_string
IOError: [Errno 32] Broken pipe

It has done it several times with any youtube video 

I tried to look at the files mentioned in the error message but I can't find them.
Sorry I'm a bit of a n00b at this.

**Comment by Billybangleballs** [comment]
I might mention that stdin & stdout are being redirected and this seems to be the root of the problem.

**Comment by Billybangleballs** [comment]
After reading http://stackoverflow.com/questions/15793886/how-to-avoid-a-broken-pipe-error-when-printing-a-large-amount-of-formatted-data

I added a -q to the command line and it provided a work-around.
