### ISSUE TITLE
Problem downloading niconico playlist, KeyError: u'url'

### ISSUE THREAD

**Issue by omwrsn** [rg3/youtube-dl#4874]
F:\>youtube-dl -v http://www.nicovideo.jp/mylist/39968249
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.nicovideo.jp/mylist/39968249']
[debug] Encodings: locale cp932, fs mbcs, out cp932, pref cp932
[debug] youtube-dl version 2015.02.04
[debug] Python version 2.7.8 - Windows-8-6.2.9200
[debug] exe versions: ffmpeg N-67731-gce80f9f, ffprobe N-67731-gce80f9f
[debug] Proxy map: {}
[NiconicoPlaylist] 39968249: Downloading webpage
[download] Downloading playlist: のぞえりRadioGarden
[NiconicoPlaylist] playlist のぞえりRadioGarden: Collected 57 video ids (downlo
ding 57 of them)
[download] Downloading video 1 of 57
[niconico] so22543406: Downloading webpage
[niconico] so22543406: Downloading video info page
[niconico] so22543406: Downloading webpage
[niconico] so22543406: Downloading flv info
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "youtube_dl\__init__.pyo", line 382, in main
  File "youtube_dl\__init__.pyo", line 372, in _real_main
  File "youtube_dl\YoutubeDL.pyo", line 1352, in download
  File "youtube_dl\YoutubeDL.pyo", line 630, in extract_info
  File "youtube_dl\YoutubeDL.pyo", line 789, in process_ie_result
  File "youtube_dl\YoutubeDL.pyo", line 683, in process_ie_result
  File "youtube_dl\YoutubeDL.pyo", line 619, in extract_info
  File "youtube_dl\extractor\common.pyo", line 268, in extract
  File "youtube_dl\extractor\niconico.pyo", line 117, in _real_extract
KeyError: u'url'

**Comment by yan12125** [comment]
Thanks for the report! This playlist can be downloaded in the next version of youtube-dl.
