### ISSUE TITLE
Lynda.com Organization Login

### ISSUE THREAD

**Issue by jtv7** [rg3/youtube-dl#4888]
When I login with my Lynda.com organization login (provided by/through my university), the login fails.  This means I cannot download the full set of videos. Example: youtube-dl -u abc@abc.edu http://lynda-link.com

**Comment by dstftw** [comment]
Post the **full** output you get when running [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by phihag** [comment]
http://lynda-link.com/ does not resolve for me, so I don't think we can support it.

**Comment by jtv7** [comment]
@phihag Sorry, "http://lynda-link.com" was just a placeholder link.  Here is a better example: http://www.lynda.com/Python-tutorials/Up-Running-Python/122467-2.html.  Included is a picture of the organization login.  You click "Login through your organization or school", it re-routes you to the organization login page, you login, and then it re-routes you back to Lynda.com
![lynda_jpg](https://cloud.githubusercontent.com/assets/10890222/6093027/cd1a40ee-aebd-11e4-9beb-7bfead5a07d7.jpg)

@dstftw Here is the output: 
    ERROR: Unable to login, incorrect username and/or password
    Traceback (most recent call last):
      File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 619, in extract_info
        ie_result = ie.extract(url)
      File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 267, in extract
        self.initialize()
      File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 262, in initialize
        self._real_initialize()
      File "/usr/local/bin/youtube-dl/youtube_dl/extractor/lynda.py", line 43, in _real_initialize
        self._login()
      File "/usr/local/bin/youtube-dl/youtube_dl/extractor/lynda.py", line 127, in _login
        raise ExtractorError('Unable to login, incorrect username and/or password', expected=True)
    ExtractorError: Unable to login, incorrect username and/or password

**Comment by dstftw** [comment]
@jtv7, log in through organization or school is not supported and it does not look feasible to implement as we will need to implement authentication for every single organization lynda supports.

**Comment by jtv7** [comment]
@dstftw Injecting cookies should work though, right?  I export my cookies from Firefox, but when I use the --cookies option (youtube-dl --cookies cookies.txt http://www.lynda.com/Python-tutorials/Up-Running-Python/122467-2.html --verbose) I get:
ERROR: Unable to download webpage: HTTP Error 400: Bad Request (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 301, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1578, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

**Comment by dstftw** [comment]
@jtv7 most likely you have [invalid newline format used in cookies file](https://github.com/rg3/youtube-dl/issues/6429#issuecomment-127079504).
I'm closing this since login with cookies works fine.
