### ISSUE TITLE
"Unable to extract h;" on a private facebook video (two-factor auth not enabled)

### ISSUE THREAD

**Issue by Fusl** [rg3/youtube-dl#4902]
The facebook extracter seems to have stopped working. It did work a few days ago and suddenly stopped (not sure when or why). I don't have two-factor auth enabled in facebook and I am obviously passing username and password to youtube-dl. This is the verbose output:

```
 _ youtube-dl --verbose '-u*hidden*' '-p*hidden*' 'https://www.facebook.com/video.php?v=868762769847346'
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '-u*hidden*', '-p*hidden*', 'https://www.facebook.com/video.php?v=868762769847346']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.02.06
[debug] Python version 2.7.6 - Linux-3.11.10-25-desktop-x86_64-with-SuSE-13.1-x86_64
[debug] exe versions: ffmpeg N-68389-g13c3a97, ffprobe N-68389-g13c3a97
[debug] Proxy map: {}
[facebook] Downloading login page
[facebook] Logging in
ERROR: Unable to extract h; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 619, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 267, in extract
    self.initialize()
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 262, in initialize
    self._real_initialize()
  File "/usr/bin/youtube-dl/youtube_dl/extractor/facebook.py", line 107, in _real_initialize
    self._login()
  File "/usr/bin/youtube-dl/youtube_dl/extractor/facebook.py", line 93, in _login
    r'name="h"\s+(?:\w+="[^"]+"\s+)*?value="([^"]+)"', login_results, 'h'),
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 524, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract h; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by szymonszydelko** [comment]
I've stumbled upon the same issue.

**Comment by potentcocktail** [comment]
Same issue here. My log if it helps...

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'https://www.facebook.com/100006236446859/videos/vb.100006236446859/1609450189272847', u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.06.04.1
[debug] Python version 2.7.9 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.1
[debug] exe versions: avconv 11.3-6, avprobe 11.3-6
[debug] Proxy map: {}
[facebook] Downloading login page
[facebook] Logging in
ERROR: Unable to extract h; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/andy/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 650, in extract_info
    ie_result = ie.extract(url)
  File "/home/andy/bin/youtube-dl/youtube_dl/extractor/common.py", line 272, in extract
    self.initialize()
  File "/home/andy/bin/youtube-dl/youtube_dl/extractor/common.py", line 266, in initialize
    self._real_initialize()
  File "/home/andy/bin/youtube-dl/youtube_dl/extractor/facebook.py", line 120, in _real_initialize
    self._login()
  File "/home/andy/bin/youtube-dl/youtube_dl/extractor/facebook.py", line 106, in _login
    r'name="h"\s+(?:\w+="[^"]+"\s+)*?value="([^"]+)"', login_results, 'h'),
  File "/home/andy/bin/youtube-dl/youtube_dl/extractor/common.py", line 555, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract h; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
