### ISSUE TITLE
VPN -> Signature extraction fails

### ISSUE THREAD

**Issue by josueespinosa** [rg3/youtube-dl#4909]
youtube-dl is up-to-date, but I can't seem to download any videos? I am currently using VPN Hotspot Shield. When I turn off my VPN, there are no problems.

youtube-dl is up-to-date (2015.02.06)
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '--output', 'C:\\Users\\Josue\\Downloads/%(title)s.%(ext)s', '--no-mtime', '--extract-audio', '--audio-format', 'mp3', '--audio-quality=320k', 'https://www.youtube.com/watch?v=6SFNW5F8K9Y']
[debug] Encodings: locale cp1252, fs mbcs, out None, pref cp1252
[debug] youtube-dl version 2015.02.06
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {'http': 'http://127.0.0.1:8555', 'https': 'https://127.0.0.1:8555'}
[youtube] 6SFNW5F8K9Y: Downloading webpage
[youtube] 6SFNW5F8K9Y: Extracting video information
[youtube] {43} signature length 43.42, html5 player en_US-vflwImypH
[youtube] 6SFNW5F8K9Y: Downloading js player en_US-vflwImypH
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 634, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 547, in _extract_signature_function
  File "youtube_dl\extractor\common.pyo", line 396, in _download_webpage
  File "youtube_dl\extractor\common.pyo", line 320, in _download_webpage_handle
  File "youtube_dl\extractor\common.pyo", line 301, in _request_webpage
  File "youtube_dl\YoutubeDL.pyo", line 1578, in urlopen
  File "urllib2.pyo", line 410, in open
  File "youtube_dl\utils.pyo", line 637, in http_response
IOError: CRC check failed 0x7d1b8747 != 0xb7b055c3L
 (caused by IOError('CRC check failed 0x7d1b8747 != 0xb7b055c3L',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 634, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 547, in _extract_signature_function
  File "youtube_dl\extractor\common.pyo", line 396, in _download_webpage
  File "youtube_dl\extractor\common.pyo", line 320, in _download_webpage_handle
  File "youtube_dl\extractor\common.pyo", line 301, in _request_webpage
  File "youtube_dl\YoutubeDL.pyo", line 1578, in urlopen
  File "urllib2.pyo", line 410, in open
  File "youtube_dl\utils.pyo", line 637, in http_response
IOError: CRC check failed 0x7d1b8747 != 0xb7b055c3L
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 619, in extract_info
  File "youtube_dl\extractor\common.pyo", line 268, in extract
  File "youtube_dl\extractor\youtube.pyo", line 1064, in _real_extract
  File "youtube_dl\extractor\youtube.pyo", line 644, in _decrypt_signature
ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 634, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 547, in _extract_signature_function
  File "youtube_dl\extractor\common.pyo", line 396, in _download_webpage
  File "youtube_dl\extractor\common.pyo", line 320, in _download_webpage_handle
  File "youtube_dl\extractor\common.pyo", line 301, in _request_webpage
  File "youtube_dl\YoutubeDL.pyo", line 1578, in urlopen
  File "urllib2.pyo", line 410, in open
  File "youtube_dl\utils.pyo", line 637, in http_response
IOError: CRC check failed 0x7d1b8747 != 0xb7b055c3L
 (caused by IOError('CRC check failed 0x7d1b8747 != 0xb7b055c3L',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
Obviously the problem in in your vpn/proxy. Closing as non youtube-dl issue.
