### ISSUE TITLE
'_PseudoRequest' object has no attribute 'get_type' when downloading private YouTube video

### ISSUE THREAD

**Issue by cozgood** [rg3/youtube-dl#4910]
Very similar to https://github.com/rg3/youtube-dl/issues/4861

[jpro:~/Downloads] jesse% /opt/local/bin/youtube-dl -u xxx 'https://www.youtube.com/watch?v=xxx' -p xxx -2 xxx 
[youtube] Downloading login page
[youtube] Logging in
[youtube] Submitting TFA code
[youtube] Ohnccq2SLvY: Downloading webpage
[youtube] Ohnccq2SLvY: Extracting video information
[youtube] Ohnccq2SLvY: Downloading DASH manifest
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/opt/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/opt/local/bin/youtube-dl/youtube_dl/__init__.py", line 382, in main
  File "/opt/local/bin/youtube-dl/youtube_dl/__init__.py", line 372, in _real_main
  File "/opt/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1353, in download
  File "/opt/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 630, in extract_info
  File "/opt/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 676, in process_ie_result
  File "/opt/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1024, in process_video_result
  File "/opt/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 916, in _calc_headers
  File "/opt/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 942, in _calc_cookies
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/cookielib.py", line 1324, in add_cookie_header
    cookies = self._cookies_for_request(request)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/cookielib.py", line 1250, in _cookies_for_request
    cookies.extend(self._cookies_for_domain(domain, request))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/cookielib.py", line 1239, in _cookies_for_domain
    if not self._policy.return_ok(cookie, request):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/cookielib.py", line 1071, in return_ok
    if not fn(cookie, request):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/cookielib.py", line 1097, in return_ok_secure
    if cookie.secure and request.get_type() != "https":
AttributeError: '_PseudoRequest' object has no attribute 'get_type'

**Comment by phihag** [comment]
I suspect that you are using an outdated version of youtube-dl. Can you post the output you get when you add `-v` to the command line?

**Comment by cozgood** [comment]
I don't think that's it. I updated from 02-02-2015 when i saw the bug. Currently have youtube-dl @2015.02.06 (net) installed.

**Comment by phihag** [comment]
Sorry, the information included in the output you get with `-v` is vital for us to debug issues in general (that's why the note is featured prominently in our [contribution notes](https://github.com/rg3/youtube-dl/blob/master/CONTRIBUTING.md)).

I am not sure why you refuse to share that information, but we cannot in good faith extend support to users who are unwilling to provide us any debugging information.

Therefore, I am closing this issue. Feel free to provide the requested information and we'll reopen it.

**Comment by cozgood** [comment]
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v']
[debug] Encodings: locale US-ASCII, fs utf-8, out US-ASCII, pref US-ASCII
[debug] youtube-dl version 2015.02.06
[debug] Python version 2.7.9 - Darwin-14.1.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.5.3, ffprobe 2.5.3
[debug] Proxy map: {}
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options.

**Comment by phihag** [comment]
That does not show the error. Please post the output you get when you add `-v` *and* when the error occurs.

**Comment by truetug** [comment]
```
youtube-dl -v xxx --cookie ~/Downloads/youtube.txt -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'xxx', '--cookie', '/Users/tug/Downloads/youtube.txt', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.02.16
[debug] Python version 2.7.9 - Darwin-14.1.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.5.3, ffprobe 2.5.3
[debug] Proxy map: {}
[youtube] xxx: Downloading webpage
[youtube] xxx: Extracting video information
[youtube] xxx: Downloading DASH manifest
Traceback (most recent call last):
  File "/Users/tug/Work/projects/st-kvartal.ru/env/bin/youtube-dl", line 11, in <module>
    sys.exit(main())
  File "/Users/tug/Work/projects/st-kvartal.ru/env/lib/python2.7/site-packages/youtube_dl/__init__.py", line 389, in main
    _real_main(argv)
  File "/Users/tug/Work/projects/st-kvartal.ru/env/lib/python2.7/site-packages/youtube_dl/__init__.py", line 379, in _real_main
    retcode = ydl.download(all_urls)
  File "/Users/tug/Work/projects/st-kvartal.ru/env/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 1387, in download
    res = self.extract_info(url)
  File "/Users/tug/Work/projects/st-kvartal.ru/env/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 644, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/Users/tug/Work/projects/st-kvartal.ru/env/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 690, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/Users/tug/Work/projects/st-kvartal.ru/env/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 1058, in process_video_result
    format['http_headers'] = self._calc_headers(full_format_info)
  File "/Users/tug/Work/projects/st-kvartal.ru/env/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 947, in _calc_headers
    cookies = self._calc_cookies(info_dict)
  File "/Users/tug/Work/projects/st-kvartal.ru/env/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 976, in _calc_cookies
    self.cookiejar.add_cookie_header(pr)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/cookielib.py", line 1324, in add_cookie_header
    cookies = self._cookies_for_request(request)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/cookielib.py", line 1250, in _cookies_for_request
    cookies.extend(self._cookies_for_domain(domain, request))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/cookielib.py", line 1239, in _cookies_for_domain
    if not self._policy.return_ok(cookie, request):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/cookielib.py", line 1071, in return_ok
    if not fn(cookie, request):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/cookielib.py", line 1097, in return_ok_secure
    if cookie.secure and request.get_type() != "https":
AttributeError: '_PseudoRequest' object has no attribute 'get_type'
```

**Comment by ebpitts** [comment]
I can reproduce this issue. Here is the requested debugging information:

```
$ youtube-dl -u $GUSER --twofactor $TFA -v 'https://www.youtube.com/playlist?list=PLs9IzzdUqHtpMZWdahZXEsuqwVts-si0U'
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-u', u'PRIVATE', '--twofactor', '187972', '-v', 'https://www.youtube.com/playlist?list=PLs9IzzdUqHtpMZWdahZXEsuqwVts-si0U']
Type account password and press [Return]:
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.02.09.3
[debug] Python version 2.7.6 - Darwin-14.1.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.5.3, ffprobe 2.5.3
[debug] Proxy map: {}
[youtube:playlist] Downloading login page
[youtube:playlist] Logging in
[youtube:playlist] Submitting TFA code
[youtube:playlist] PLs9IzzdUqHtpMZWdahZXEsuqwVts-si0U: Downloading webpage
[download] Downloading playlist: Engineering Bootcamp September 2014
[youtube:playlist] playlist Engineering Bootcamp September 2014: Collected 19 video ids (downloading 19 of them)
[download] Downloading video 1 of 19
[youtube] Downloading login page
[youtube] Logging in
[youtube] hxAOFgc9umM: Downloading webpage
[youtube] hxAOFgc9umM: Extracting video information
[youtube] hxAOFgc9umM: Downloading DASH manifest
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 382, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 372, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1373, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 630, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 789, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 683, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 630, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 676, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1044, in process_video_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 933, in _calc_headers
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 962, in _calc_cookies
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/cookielib.py", line 1324, in add_cookie_header
    cookies = self._cookies_for_request(request)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/cookielib.py", line 1250, in _cookies_for_request
    cookies.extend(self._cookies_for_domain(domain, request))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/cookielib.py", line 1239, in _cookies_for_domain
    if not self._policy.return_ok(cookie, request):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/cookielib.py", line 1071, in return_ok
    if not fn(cookie, request):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/cookielib.py", line 1097, in return_ok_secure
    if cookie.secure and request.get_type() != "https":
AttributeError: '_PseudoRequest' object has no attribute 'get_type'
```

**Comment by phihag** [comment]
@ebpitts Can you also reproduce the issue with the [latest version](https://yt-dl.org/latest/version)? See [our FAQ](https://yt-dl.org/update) if you have trouble updating.

**Comment by ebpitts** [comment]
Sorry, 2015.02.09.3 and 2015.02.19.3 looked similar at a glance, and I didn't realize I didn't have the latest version.

Good news! I can no longer reproduce the problem.
