### ISSUE TITLE
Add support for joystiq.com and massively.joystiq.com

### ISSUE THREAD

**Issue by PressStartandSelect** [rg3/youtube-dl#4962]
Hello,

Could you please add support for videos on joystiq.com and massively.joystiq.com?

Here are some examples:
http://www.joystiq.com/video/518137752
http://massively.joystiq.com/video/518617802

```
$ youtube-dl --verbose http://www.joystiq.com/video/518137752
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.joystiq.com/video/518137752']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.02.16.1
[debug] Python version 2.7.6 - Darwin-14.0.0-x86_64-i386-64bit
[debug] exe versions: rtmpdump 2.4
[debug] Proxy map: {}
[generic] 518137752: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 518137752: Downloading webpage
[generic] 518137752: Extracting information
ERROR: Unsupported URL: http://www.joystiq.com/video/518137752
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 729, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1515, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: syntax error: line 1, column 0
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 633, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 270, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1168, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.joystiq.com/video/518137752

$
```

**Comment by dstftw** [comment]
Thanks for the report. joystiq.com will be supported in the next version.

**Comment by phihag** [comment]
Thanks for (massively.)joystiq.com has been added youtube-dl 2015.02.19.3. See [our FAQ](https://yt-dl.org/update) if you need help updating.
