### ISSUE TITLE
Youtube Video Unable to download https://www.youtube.com/watch?v=1AHnQtY1bg4

### ISSUE THREAD

**Issue by kendalls63** [rg3/youtube-dl#4976]
https://www.youtube.com/watch?v=1AHnQtY1bg4
Verbose Output:
youtube-dl --verbose https://www.youtube.com/watch?v=1AHnQtY1bg4
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=1AHnQtY1bg4']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.02.18
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: rtmpdump 2.3
[debug] Proxy map: {}
[youtube] 1AHnQtY1bg4: Downloading webpage
[youtube] 1AHnQtY1bg4: Extracting video information
[youtube] {22} signature length 40.41, html5 player en_US-vflKjOTVq
[youtube] 1AHnQtY1bg4: Downloading js player en_US-vflKjOTVq
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 635, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 549, in _extract_signature_function
  File "youtube_dl\extractor\youtube.pyo", line 613, in _parse_sig_js
  File "youtube_dl\jsinterp.pyo", line 244, in extract_function
ExtractorError: Could not find JS function u'OF'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Could not find JS function u'OF'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl
with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 635, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 549, in _extract_signature_function
  File "youtube_dl\extractor\youtube.pyo", line 613, in _parse_sig_js
  File "youtube_dl\jsinterp.pyo", line 244, in extract_function
ExtractorError: Could not find JS function u'OF'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 643, in extract_info
  File "youtube_dl\extractor\common.pyo", line 269, in extract
  File "youtube_dl\extractor\youtube.pyo", line 1066, in _real_extract
  File "youtube_dl\extractor\youtube.pyo", line 645, in _decrypt_signature
ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 635, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 549, in _extract_signature_function
  File "youtube_dl\extractor\youtube.pyo", line 613, in _parse_sig_js
  File "youtube_dl\jsinterp.pyo", line 244, in extract_function
ExtractorError: Could not find JS function u'OF'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Could not find JS function u'OF'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl
with the --verbose flag and include its complete output.

**Comment by HyShai** [comment]
Same issue here. Different video.

**Comment by HyShai** [comment]
Narrowed down the issue to `JSInterpreter#_remove_comments` - the regex is mistakenly removing the `OF` function.

**Comment by kmb32123** [comment]
I am also running into this. Travis CI is picking it up too; test_Youtube_1, 2, 5, 6, and 9 are all failing on mainline with the same error.

**Comment by phihag** [comment]
Thank you for the report. I believe this issue to be fixed in youtube-dl version 2015.02.18.1 and newer. See [our FAQ](https://yt-dl.org/update) if you have trouble updating.
