### ISSUE TITLE
Cannot download hPIV5guQTpY

### ISSUE THREAD

**Issue by mbodomi** [rg3/youtube-dl#4981]
PS C:\> youtube-dl.exe -x hPIV5guQTpY --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-x', 'hPIV5guQTpY', '--verbose']
[debug] Encodings: locale cp1250, fs mbcs, out cp852, pref cp1250
[debug] youtube-dl version 2015.02.18
[debug] Python version 2.7.8 - Windows-7-6.1.7600
[debug] exe versions: ffmpeg 2.5.2, ffprobe 2.5.2
[debug] Proxy map: {}
[youtube] hPIV5guQTpY: Downloading webpage
[youtube] hPIV5guQTpY: Extracting video information
[youtube] {22} signature length 40.41, html5 player en_US-vflKjOTVq
[youtube] hPIV5guQTpY: Downloading js player en_US-vflKjOTVq
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 635, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 549, in _extract_signature_function
  File "youtube_dl\extractor\youtube.pyo", line 613, in _parse_sig_js
  File "youtube_dl\jsinterp.pyo", line 244, in extract_function
ExtractorError: Could not find JS function u'OF'; please report this issue on https://yt-dl.org/bug . Make sure you are
using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include
 its complete output.
 (caused by ExtractorError(u"Could not find JS function u'OF'; please report this issue on https://yt-dl.org/bug . Make
sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose fla
g and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the
latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its compl
ete output.
Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 635, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 549, in _extract_signature_function
  File "youtube_dl\extractor\youtube.pyo", line 613, in _parse_sig_js
  File "youtube_dl\jsinterp.pyo", line 244, in extract_function
ExtractorError: Could not find JS function u'OF'; please report this issue on https://yt-dl.org/bug . Make sure you are
using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include
 its complete output.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 643, in extract_info
  File "youtube_dl\extractor\common.pyo", line 269, in extract
  File "youtube_dl\extractor\youtube.pyo", line 1066, in _real_extract
  File "youtube_dl\extractor\youtube.pyo", line 645, in _decrypt_signature
ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 635, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 549, in _extract_signature_function
  File "youtube_dl\extractor\youtube.pyo", line 613, in _parse_sig_js
  File "youtube_dl\jsinterp.pyo", line 244, in extract_function
ExtractorError: Could not find JS function u'OF'; please report this issue on https://yt-dl.org/bug . Make sure you are
using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include
 its complete output.
 (caused by ExtractorError(u"Could not find JS function u'OF'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the
latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by kmb32123** [comment]
Running into this same issue running from a `pip install` on debian and windows. Appears to be same issue as #4976.

**Comment by phihag** [comment]
Thank you for the report. I believe this issue to be fixed in youtube-dl version 2015.02.18.1 and newer. See [our FAQ](https://yt-dl.org/update) if you have trouble updating.
