### ISSUE TITLE
[soundcloud] --add-metadata error with .raw format processing 

### ISSUE THREAD

**Issue by pricejn2** [rg3/youtube-dl#4991]
Looks like soundcloud added a new RAW format.

Works correctly with ```format mp3```:
```
youtube-dl --format mp3 https://m.soundcloud.com/guillermo-jose-manzanares-anderson/respirar-tu-aire --add-metadata --prefer-ffmpeg --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--format', 'mp3', 'https://m.soundcloud.com/guillermo-jose-manzanares-anderson/respirar-tu-aire', '--add-metadata', '--prefer-ffmpeg', '--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.02.18.1
[debug] Python version 2.7.3 - Linux-3.14.32-xxxx-grs-ipv6-64-x86_64-with-Debian-7
[debug] exe versions: avconv 1.2.12, avprobe 1.2.12, ffmpeg 1.2.12, ffprobe 1.2.12, rtmpdump 2.4
[debug] Proxy map: {}
[soundcloud] guillermo-jose-manzanares-anderson/respirar-tu-aire: Resolving id
[soundcloud] guillermo-jose-manzanares-anderson/respirar-tu-aire: Downloading info JSON
[soundcloud] 191647306: Downloading track url
[debug] Invoking downloader on u'https://cf-media.sndcdn.com/wwqXdx0rmNRf.128.mp3?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiKjovL2NmLW1lZGlhLnNuZGNkbi5jb20vd3dxWGR4MHJtTlJmLjEyOC5tcDMiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE0MjQyODU2Nzh9fX1dfQ__&Signature=lu2SP4KHq37dLSWznPSeVhanXtKGoJWF424MZOVab9146hRWyclX8zf6OWEapYIAhrImkts6sosDu6GnpR23S~4~rtw27griAre17C7H8idRNgiyDenpoLAbMfiLT3QXBt~xJF1OpBsyfX4L17SxU~iHBk~DC5Jcpxinx09MW4FpMHlhDer297NzM8ORJrt-cKNXQMB5U~oxxb2qE2htcw9K3ivKHOOpWofcYEtB6yaOJZKkJQX4qhi5oIeEi~AQQZPv20WUk2Rt1WOOeXNBfuRAXLxT7CBwY~af5H3Y-Se9hRD4SQZSNaTVz1iRtERWsDdmL8hRpZY9SD86MkWeWA__&Key-Pair-Id=APKAJAGZ7VMH2PFPW6UQ'
[download] Destination: RESPIRAR TU AIRE-191647306.mp3
[download] 100% of 4.53MiB in 00:00
[ffmpeg] Adding metadata to 'RESPIRAR TU AIRE-191647306.mp3'
[debug] ffmpeg command line: ffmpeg -y -i 'RESPIRAR TU AIRE-191647306.mp3' -c copy -metadata 'comment=Otra de las canciones del álbum' -metadata 'description=Otra de las canciones del álbum' -metadata 'artist=Guillermo Jose Anderson' -metadata 'title=RESPIRAR TU AIRE' -metadata date=20150217 -metadata purl=http://soundcloud.com/guillermo-jose-manzanares-anderson/respirar-tu-aire 'RESPIRAR TU AIRE-191647306.temp.mp3'
```

Does not detect ```--format raw```:
```
youtube-dl --format raw https://m.soundcloud.com/guillermo-jose-manzanares-anderson/respirar-tu-aire --add-metadata --prefer-ffmpeg --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--format', 'raw', 'https://m.soundcloud.com/guillermo-jose-manzanares-anderson/respirar-tu-aire', '--add-metadata', '--prefer-ffmpeg', '--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.02.18.1
[debug] Python version 2.7.3 - Linux-3.14.32-xxxx-grs-ipv6-64-x86_64-with-Debian-7
[debug] exe versions: avconv 1.2.12, avprobe 1.2.12, ffmpeg 1.2.12, ffprobe 1.2.12, rtmpdump 2.4
[debug] Proxy map: {}
[soundcloud] guillermo-jose-manzanares-anderson/respirar-tu-aire: Resolving id
[soundcloud] guillermo-jose-manzanares-anderson/respirar-tu-aire: Downloading info JSON
[soundcloud] 191647306: Downloading track url
ERROR: requested format not available
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 654, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 700, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1126, in process_video_result
    expected=True)
ExtractorError: requested format not available
```

Can't add metadata to RAW format:
```
youtube-dl --format best https://m.soundcloud.com/guillermo-jose-manzanares-anderson/respirar-tu-aire --add-metadata --prefer-ffmpeg --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--format', 'best', 'https://m.soundcloud.com/guillermo-jose-manzanares-anderson/respirar-tu-aire', '--add-metadata', '--prefer-ffmpeg', '--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.02.18.1
[debug] Python version 2.7.3 - Linux-3.14.32-xxxx-grs-ipv6-64-x86_64-with-Debian-7
[debug] exe versions: avconv 1.2.12, avprobe 1.2.12, ffmpeg 1.2.12, ffprobe 1.2.12, rtmpdump 2.4
[debug] Proxy map: {}
[soundcloud] guillermo-jose-manzanares-anderson/respirar-tu-aire: Resolving id
[soundcloud] guillermo-jose-manzanares-anderson/respirar-tu-aire: Downloading info JSON
[soundcloud] 191647306: Downloading track url
[debug] Invoking downloader on u'https://api.soundcloud.com/tracks/191647306/download?client_id=b45b1aa10f1ac2941910a7f0d10f8e28'
[download] Destination: RESPIRAR TU AIRE-191647306.raw
[download] 100% of 11.33MiB in 00:05
[ffmpeg] Adding metadata to 'RESPIRAR TU AIRE-191647306.raw'
[debug] ffmpeg command line: ffmpeg -y -i 'RESPIRAR TU AIRE-191647306.raw' -c copy -metadata 'comment=Otra de las canciones del álbum' -metadata 'description=Otra de las canciones del álbum' -metadata 'artist=Guillermo Jose Anderson' -metadata 'title=RESPIRAR TU AIRE' -metadata date=20150217 -metadata purl=http://soundcloud.com/guillermo-jose-manzanares-anderson/respirar-tu-aire 'RESPIRAR TU AIRE-191647306.temp.raw'
ERROR: RESPIRAR TU AIRE-191647306.temp.raw: Invalid argument
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1414, in post_process
    keep_video_wish, info = pp.run(info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/postprocessor/ffmpeg.py", line 576, in run
    self.run_ffmpeg(filename, temp_filename, options)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/postprocessor/ffmpeg.py", line 151, in run_ffmpeg
    self.run_ffmpeg_multiple_files([path], out_path, opts)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/postprocessor/ffmpeg.py", line 144, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
FFmpegPostProcessorError

```

And fails to add metadata with ```---format best``` because of processing order (I believe that ```--add--metadata``` should come after format conversion):
```
youtube-dl --format best https://m.soundcloud.com/guillermo-jose-manzanares-anderson/respirar-tu-aire --add-metadata --prefer-ffmpeg --verbose -x --audio-format mp3
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--format', 'best', 'https://m.soundcloud.com/guillermo-jose-manzanares-anderson/respirar-tu-aire', '--add-metadata', '--prefer-ffmpeg', '--verbose', '-x', '--audio-format', 'mp3']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.02.18.1
[debug] Python version 2.7.3 - Linux-3.14.32-xxxx-grs-ipv6-64-x86_64-with-Debian-7
[debug] exe versions: avconv 1.2.12, avprobe 1.2.12, ffmpeg 1.2.12, ffprobe 1.2.12, rtmpdump 2.4
[debug] Proxy map: {}
[soundcloud] guillermo-jose-manzanares-anderson/respirar-tu-aire: Resolving id
[soundcloud] guillermo-jose-manzanares-anderson/respirar-tu-aire: Downloading info JSON
[soundcloud] 191647306: Downloading track url
[debug] Invoking downloader on u'https://api.soundcloud.com/tracks/191647306/download?client_id=b45b1aa10f1ac2941910a7f0d10f8e28'
[download] Destination: RESPIRAR TU AIRE-191647306.raw
[download] 100% of 11.33MiB in 00:33
[ffmpeg] Adding metadata to 'RESPIRAR TU AIRE-191647306.raw'
[debug] ffmpeg command line: ffmpeg -y -i 'RESPIRAR TU AIRE-191647306.raw' -c copy -metadata 'comment=Otra de las canciones del álbum' -metadata 'description=Otra de las canciones del álbum' -metadata 'artist=Guillermo Jose Anderson' -metadata 'title=RESPIRAR TU AIRE' -metadata date=20150217 -metadata purl=http://soundcloud.com/guillermo-jose-manzanares-anderson/respirar-tu-aire 'RESPIRAR TU AIRE-191647306.temp.raw'
ERROR: RESPIRAR TU AIRE-191647306.temp.raw: Invalid argument
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1414, in post_process
    keep_video_wish, info = pp.run(info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/postprocessor/ffmpeg.py", line 576, in run
    self.run_ffmpeg(filename, temp_filename, options)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/postprocessor/ffmpeg.py", line 151, in run_ffmpeg
    self.run_ffmpeg_multiple_files([path], out_path, opts)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/postprocessor/ffmpeg.py", line 144, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
FFmpegPostProcessorError

```

**Comment by ipatix** [comment]
So I'm running into this issue as well when trying to download this file:
```
https://soundcloud.com/arenanet/blishs-sacrifice
```
The downloaded file appears to be a "raw" file but it actually is just a simple .wav file when looking at the data:
```
Blish's Sacrifice-520487163.raw: RIFF (little-endian) data, WAVE audio, Microsoft PCM, 24 bit, stereo 48000 Hz
```

I checked out the file of @pricejn2 and in that case the raw seems to be an MP3 with ID3.

So I have no idea what youtube-dl is doing but that "raw" just seems to be bugged. Does anyone with more youtube-dl code knowledge know how the soundcloud plugin idenfies these formats?
