### ISSUE TITLE
Pornhub Playlists Unsupported

### ISSUE THREAD

**Issue by somato** [rg3/youtube-dl#4995]
Hello!
Are there any plans to include support for playlists on Pornhub?  They currently fail as unsupported URLs.

youtube-dl --verbose http://www.pornhub.com/playlist/6201671

[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.pornhub.com/playlist/6201671']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.02.18.1
[debug] Python version 2.7.3 - Linux-3.13.0-45-generic-x86_64-with-Ubuntu-12.04-precise
[debug] exe versions: avconv 0.8.16-4, avprobe 0.8.16-4, ffmpeg 0.8.16-4, ffprobe 0.8.16-4, rtmpdump 2.3
[debug] Proxy map: {}
[generic] 6201671: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 6201671: Downloading webpage
[generic] 6201671: Extracting information
ERROR: Unsupported URL: http://www.pornhub.com/playlist/6201671
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 730, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1515, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1301, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1643, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1507, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 75, column 22
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 643, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 269, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1169, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.pornhub.com/playlist/6201671

**Comment by dstftw** [comment]
Playlist will be supported in the next version. Thanks for the report.

**Comment by phihag** [comment]
I believe this issue to be fixed in youtube-dl 2015.02.19.3. See [our FAQ](https://yt-dl.org/update) if you need help updating.
