### ISSUE TITLE
CBS Sports: Unsupported URL

### ISSUE THREAD

**Issue by MaryCoding** [rg3/youtube-dl#4996]
Hello, I was trying to download a video from http://www.cbssports.com/ but there is an error. The link below is in an unsupported url format for youtube-dl. I read the documentation and CBS is a supported site. Your help is much appreciated, Thanks! :)

```
youtube-dl -v -o "/media/%(title)s.mp4" "http://www.cbssports.com/video/player/videos/401093187638/0/is-johnny-manziel-the-future-in-cleveland"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', '-o', '/media/%(title)s.mp4', 'http://www.cbssports.com/video/player/videos/401093187638/0/is-johnny-manziel-the-future-in-cleveland']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.02.18
[debug] Python version 2.7.6 - Linux-3.13.0-35-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: ffmpeg git-2014-12-27-d4fd3f2, ffprobe git-2014-12-27-d4fd3f2
[debug] Proxy map: {}
[generic] is-johnny-manziel-the-future-in-cleveland: Requesting header
WARNING: Falling back on generic information extractor.
[generic] is-johnny-manziel-the-future-in-cleveland: Downloading webpage
[generic] is-johnny-manziel-the-future-in-cleveland: Extracting information
ERROR: Unsupported URL: http://www.cbssports.com/video/player/videos/401093187638/0/is-johnny-manziel-the-future-in-cleveland
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 730, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1515, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 2, column 63
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 643, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 269, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1169, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.cbssports.com/video/player/videos/401093187638/0/is-johnny-manziel-the-future-in-cleveland


```

**Comment by phihag** [comment]
Thank you for the report. When it comes to the technical backend, cbssports.com is completely different to cbs.com though, so the current cbs.com extractor will not help; a new extractor has to be written for cbssports.com.

**Comment by MaryCoding** [comment]
Thank you Philip. You guys are hard working developers. I see that there are 234 issues under the site-support-request tag. Does that indicate that it will be a while before it gets that feature added to youtube-dl?

**Comment by phihag** [comment]
Depends. If you or another developer is interested in writing the extractor, it can will usually be integrated within days, if not hours.

**Comment by MaryCoding** [comment]
I see. I read that youtube-dl supports rtpm. I did a little more digging and found this json file used by cbs http://www.cbssports.com/data/video/player/getVideos/videos?uacheck=1&limit=50 . Could youtube-dl download directly from there using the source url? I tried but it gave an error.

**Comment by jaimeMF** [comment]
It will work in the next version, thanks for the report.

**Comment by MaryCoding** [comment]
Thanks, Jaime! I appreciate your hard work.

**Comment by phihag** [comment]
Suport for cbssports has been added in youtube-dl 2015.02.19.3. See [our FAQ](https://yt-dl.org/update) if you need help updating.
