### ISSUE TITLE
Error 10061 No Connection coukd be made

### ISSUE THREAD

**Issue by hudixt** [rg3/youtube-dl#4999]
hi i am running simple line to download video which is
youtube-dl 'url' 
but i am getting an error 10061 "No Connection Can Be Made Because Target Machine Actively Refused It'

**Comment by jaimeMF** [comment]
Post [the **full output**](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs) you get when running `youtube-dl --verbose PLACE_THE_URL_HERE`.

**Comment by dstftw** [comment]
Closing due to insufficient info. Feel free to open a new issue with [full `--verbose` log](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by stahir** [comment]
i get the same error while download 50fps video, here is the verbose log
`
youtube-dl.exe -f 298 https://www.youtube.com/watch?v=9WQ20BZAos8 --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', '298', 'https://www.youtube.com/watch?v=9WQ20BZAos8', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.07.12
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: avconv v13_dev0-1440-g34c1133, avprobe v13_dev0-1440-g34c1133
[debug] Proxy map: {}
[youtube] 9WQ20BZAos8: Downloading webpage
[youtube] 9WQ20BZAos8: Downloading video info webpage
[debug] Invoking downloader on 'https://r5---sn-2uja-2xfl.googlevideo.com/videoplayback?expire=1562975487&ei=nsgoXdfOMvCQmLAPpuSB8Aw&ip=39.43.77.38&id=o-AKi6rdN-6-hXwl1sk5RjxFzloXLvtGoLCFAx41T5ZUJm&itag=298&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278%2C298%2C299%2C302%2C303&source=youtube&requiressl=yes&mm=31%2C29&mn=sn-2uja-2xfl%2Csn-2uja-3ipd&ms=au%2Crdu&mv=m&mvi=4&pl=17&initcwndbps=141250&mime=video%2Fmp4&gir=yes&clen=77744097&dur=221.460&lmt=1551124589098530&mt=1562953759&fvip=5&keepalive=yes&c=WEB&txp=5432432&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=ALgxI2wwRQIhAP1twOMtbw5Zy2r0_4oZfpUcfbaEjMFs2OeSvhAaX3zXAiBNbdog0n953g95XQdPkoxR4YJmxE8wYGObI_wKRbRgfA%3D%3D&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRQIhAL1IDybNkql6GwnD-2y6toeRgKAFy9PBiQ_wcXf4C3BLAiBG1FoCR2Lfq5auroiOhq2K351YEVd31K7w_4_ii2g9YQ%3D%3D&ratebypass=yes'
ERROR: unable to download video data: <urlopen error [WinError 10061] No connection could be made because the target machine actively refused it>
Traceback (most recent call last):
  File "C:\Python\Python34\lib\urllib\request.py", line 1183, in do_open
  File "C:\Python\Python34\lib\http\client.py", line 1137, in request
  File "C:\Python\Python34\lib\http\client.py", line 1182, in _send_request
  File "C:\Python\Python34\lib\http\client.py", line 1133, in endheaders
  File "C:\Python\Python34\lib\http\client.py", line 963, in _send_output
  File "C:\Python\Python34\lib\http\client.py", line 898, in send
  File "C:\Python\Python34\lib\http\client.py", line 1279, in connect
  File "C:\Python\Python34\lib\http\client.py", line 871, in connect
  File "C:\Python\Python34\lib\socket.py", line 516, in create_connection
  File "C:\Python\Python34\lib\socket.py", line 507, in create_connection
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp50ai1hnn\build\youtube_dl\YoutubeDL.py", line 1915, in process_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp50ai1hnn\build\youtube_dl\YoutubeDL.py", line 1854, in dl
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp50ai1hnn\build\youtube_dl\downloader\common.py", line 366, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp50ai1hnn\build\youtube_dl\downloader\http.py", line 341, in real_download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp50ai1hnn\build\youtube_dl\downloader\http.py", line 109, in establish_connection
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp50ai1hnn\build\youtube_dl\YoutubeDL.py", line 2227, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 464, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 482, in _open
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp50ai1hnn\build\youtube_dl\utils.py", line 2724, in https_open
  File "C:\Python\Python34\lib\urllib\request.py", line 1185, in do_open
urllib.error.URLError: <urlopen error [WinError 10061] No connection could be made because the target machine actively refused it>
`
