### ISSUE TITLE
RegexNotFoundError: Unable to extract Initial JS player signature function name

### ISSUE THREAD

**Issue by mweinelt** [rg3/youtube-dl#5007]
```
$ youtube-dl https://www.youtube.com/watch?v=aJvPjelxxj0
[youtube] Setting language
[youtube] aJvPjelxxj0: Downloading webpage
[youtube] aJvPjelxxj0: Downloading video info webpage
[youtube] aJvPjelxxj0: Extracting video information
[youtube] aJvPjelxxj0: Encrypted signatures detected.
[youtube] aJvPjelxxj0: Downloading js player vflF2Mg88
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 479, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 383, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 454, in _parse_sig_js
    u'Initial JS player signature function name')
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 391, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
```

**Comment by phihag** [comment]
Be sure to call youtube-dl with the `--verbose` flag and include its complete output.

Most likely, you are using an outdated version of youtube-dl. Make sure you are using the latest version; see [our FAQ](https://yt-dl.org/update) if you have trouble updating.

I'm closing this issue now since I strongly believe that your version of youtube-dl is heavily outdated (we changed some part of the outputs approximately a hundred versions ago), and therefore updating should solve this issue. If it does not, please post the complete output you get with `--verbose` and we will reopen this issue. Thanks!

**Comment by mweinelt** [comment]
Please excuse my half-assed bugreport. This was indeed on an Ubuntu 14.10 installation with 2014.08.05.
