### ISSUE TITLE
[Escapist] Unable to extract player URL

### ISSUE THREAD

**Issue by cyberjacob** [rg3/youtube-dl#5017]
Tried to download a video from escapistmagazine.com and got an "Unable to extract player URL"
The video in question is Pikmin 3, at http://www.escapistmagazine.com/videos/view/zero-punctuation/7989-Pikmin-3
Full verbose console output as follows:
```
pangea:zero ccuk$ youtube-dl --verbose "http://www.escapistmagazine.com/videos/view/zero-punctuation/7989-Pikmin-3"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.escapistmagazine.com/videos/view/zero-punctuation/7989-Pikmin-3']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.02.19.3
[debug] Python version 2.7.1 - Darwin-11.4.2-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.5.3, ffprobe 2.5.3, rtmpdump 2.4
[debug] Proxy map: {}
[Escapist] 7989: Downloading webpage
ERROR: Unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 643, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 269, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/escapist.py", line 43, in _real_extract
    player_url = self._og_search_video_url(webpage, name='player URL')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 625, in _og_search_video_url
    return self._html_search_regex(regexes, html, name, **kargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 541, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 531, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

pangea:zero ccuk$
```

**Comment by phihag** [comment]
Thank you for the report. I believe this issue to be fixed in youtube-dl 2015.02.20 and newer. See [our FAQ](https://yt-dl.org/update) if you have trouble updating.
