### ISSUE TITLE
Unable to download embedded videos from cloudy.ec

### ISSUE THREAD

**Issue by j605** [rg3/youtube-dl#5021]
The video url is blocked but I could access the embedded content in chromium. 

```
 youtube-dl --verbose "https://www.cloudy.ec/embed.php?id=d9c438f712b83"                                                                                                  CURRENT TIME: 10:54:27
which: /usr/bin/youtube-dl 

[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'https://www.cloudy.ec/embed.php?id=d9c438f712b83']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.02.19.1
[debug] Python version 3.4.2 - Linux-3.18.6-1-ARCH-x86_64-with-arch-Arch-Linux
[debug] exe versions: ffmpeg 2.5.4, ffprobe 2.5.4, rtmpdump 2.4
[debug] Proxy map: {}
[Cloudy] d9c438f712b83: Downloading webpage
ERROR: Unable to extract file_key; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 643, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 269, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/cloudy.py", line 108, in _real_extract
    r'filekey\s*=\s*"([^"]+)"', webpage, 'file_key')
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 531, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract file_key; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by dstftw** [comment]
Could you run it with `--write-pages` and upload `*.dump` files that will be created?

**Comment by phihag** [comment]
Works fine for me. We'll need the `--write-pages` (or `--dump-intermedia-pages`) output to see what's going on here.

**Comment by j605** [comment]
This is what I get.

```
<!DOCTYPE html>
<html>
<head>
<style>
body {
margin:0; 
padding:0;
}
</style>
<script type="text/javascript" src="/js/mobileapp.js"></script>
</head>
<body>


<script type="text/javascript" src="/player/swfobject.js"></script>
<div name="mediaspace" id="mediaspace">
        	<p>
	        	To view this page ensure that Adobe Flash Player version 
				10.0.0 or greater is installed. 
			</p>
			<script type="text/javascript"> 
				var pageHost = ((document.location.protocol == "https:") ? "https://" :	"http://"); 
				document.write("<a href='http://www.adobe.com/go/getflashplayer'><img src='" 
								+ pageHost + "www.adobe.com/images/shared/download_buttons/get_flash_player.gif' alt='Get Adobe Flash player' /></a>" ); 
			</script> 
	</div>


        <script type="text/javascript">
		   var swfVersionStr = "10.0.0";
		function logout(){
		}

		function disableAds(x,y,z) {
if(z>0){
document.getElementById('adv1').innerHTML ='';
vp=1;
}		}	
			

var winW = 400, winH = 300;
if (document.body && document.body.offsetWidth) {
 winW = document.body.offsetWidth;
 winH = document.body.offsetHeight;
}
if (document.compatMode=='CSS1Compat' &&
    document.documentElement &&
    document.documentElement.offsetWidth ) {
 winW = document.documentElement.offsetWidth;
 winH = document.documentElement.offsetHeight;
}
if (window.innerWidth && window.innerHeight) {
 winW = window.innerWidth;
 winH = window.innerHeight;
var xx=111;
}


      
              

            var flashvars = {};
			flashvars.width=winW;
			flashvars.height=winH;
			flashvars.domain="http://www.cloudy.ec";
			flashvars.file="d9c438f712b83";
			flashvars.filekey="61.3.196.80-daef0f5e66849f4967e3cea6f3aa955f-";
			flashvars.advURL="https://www.cloudy.ec/v/d9c438f712b83";





flashvars.themeStyle="1";
flashvars.theme="/player/themes/cloudy.swf";




            var params = {};
            params.quality = "high";
            params.bgcolor = "#ffffff";
            params.allowscriptaccess = "sameDomain";
            params.allowfullscreen = "true";
			params.wmode = "transparent";
            var attributes = {};
            attributes.id = "videoPlayer";
            attributes.name = "videoPlayer";
            attributes.align = "middle";
			var xiSwfUrlStr = "";
            swfobject.embedSWF("/player/cloudplayer.swf", "mediaspace", 
                winW, winH, 
                swfVersionStr, xiSwfUrlStr, 
                flashvars, params, attributes);
			<!-- JavaScript enabled so display the flashContent div in case it is not replaced with a swf object. -->
			swfobject.createCSS("#mediaspace", "display:block;text-align:left;");
			
			var e = document.getElementById("mediaspace");
			e.style.visibility = '';

			



</script>



<script type="text/javascript">
function adclose(){
document.getElementById('aad').innerHTML="";
}
</script>
<style>
	#aad{
		width:300px;
    	margin-left:-150px;
    	left:50%;
    	margin-top:-50px;
    	top:20%;
		position: absolute;
		z-index: 99999;
		text-align: center;
	}
	#aad span{
		margin-top:5px;
		display: block;
	}
	.btn-newad{
		
		font-weight: bold;
		display: block;
		text-decoration: none;
		cursor: pointer;
		margin-top: 10px;
		padding: 4px 12px 5px;
		text-shadow: 0 1px 1px rgba(255, 255, 255, 0.75);
		font-size: 14px;
		line-height: normal;
		-webkit-border-radius: 4px;
		-moz-border-radius: 4px;
		border-radius: 4px;
		-webkit-box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.2), 0 1px 2px rgba(0, 0, 0, 0.05);
		-moz-box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.2), 0 1px 2px rgba(0, 0, 0, 0.05);
		box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.2), 0 1px 2px rgba(0, 0, 0, 0.05);
		-webkit-transition: 0.1s linear all;
		-moz-transition: 0.1s linear all;
		transition: 0.1s linear all;
		background-color: hsl(0, 0%, 79%);
		background-repeat: repeat-x;
		background-image: -khtml-gradient(linear, left top, left bottom, from(hsl(0, 0%, 121%)), to(hsl(0, 0%, 79%)));
		background-image: -moz-linear-gradient(top, hsl(0, 0%, 121%), hsl(0, 0%, 79%));
		background-image: -ms-linear-gradient(top, hsl(0, 0%, 121%), hsl(0, 0%, 79%));
		background-image: -webkit-gradient(linear, left top, left bottom, color-stop(0%, hsl(0, 0%, 121%)), color-stop(100%, hsl(0, 0%, 79%)));
		background-image: -webkit-linear-gradient(top, hsl(0, 0%, 121%), hsl(0, 0%, 79%));
		background-image: -o-linear-gradient(top, hsl(0, 0%, 121%), hsl(0, 0%, 79%));
		background-image: linear-gradient(hsl(0, 0%, 121%), hsl(0, 0%, 79%));
		border-color: hsl(0, 0%, 79%) hsl(0, 0%, 79%) hsl(0, 0%, 68.5%);
		color: #333;
		text-shadow: 0 1px 1px rgba(255, 255, 255, 0.69);
		-webkit-font-smoothing: antialiased;
	}
	.btn-newad:hover {
		background-position: 0 -15px;
		color: #333;
		text-decoration: none;
	}
	.btn-newad.disabled {
		background-position: 0 -25px;
		color: #333;
	}
</style>

<div id="aad" class="ad">

<iframe src='/ads/ads.php'; height='250' width='300' frameborder='0' border='0' marginwidth='0' marginheight='0' scrolling='no'></iframe>
<a href="javascript:adclose();" class="btn-newad" id="first_btn">Close ad</a>

</div>


<script data-cfasync=false src="//s.ato.mx/p.js#id=7164&type=popunder&size=800x600&hourscap=1"></script>







<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-43817902-1', 'auto');
  ga('send', 'pageview');

</script>


</body>
</html>
```

**Comment by phihag** [comment]
When I inject that locally, it works fine for me too!  (At least the check you're tripping on, that is.) Sorry to pester you so much, but could you post the output you get with `--verbose --dump-intermediate-pages`? You can use `youtube-dl --verbose --dump-intermediate-pages https://www.cloudy.ec/embed.php?id=d9c438f712b83 > log` to write it into a file `log`.

**Comment by j605** [comment]
The log file, https://gist.github.com/j605/6061841a408a4d05eefb

**Comment by dstftw** [comment]
Can you access it from browser with `http://www.cloudy.ec/embed.php?id=d9c438f712b83` (note no **s**)?

**Comment by phihag** [comment]
The log file shows that the video is blocked (most likely by an Indian ISP/government censorship device). How did get you get that `--write-pages` output?

**Comment by dstftw** [comment]
@phihag that is already mentioned in the first post.

**Comment by j605** [comment]
Yes, its blocked. I used a proxy to finally download the video.
