### ISSUE TITLE
Exception: KeyError on id when downloading from 8tracks

### ISSUE THREAD

**Issue by albins** [rg3/youtube-dl#5029]
albin@hecate /tmp/8tracks % HTTP_PROXY="" http_proxy="" HTTPS_PROXY="" https_proxy="" youtube-dl http://8tracks.com/missmaher/scurry-along-little-dove --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://8tracks.com/missmaher/scurry-along-little-dove', '--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.02.21
[debug] Python version 2.7.8 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.0
[debug] exe versions: avconv 11.2-6, avprobe 11.2-6, ffmpeg 0.8.7-6, rtmpdump 2.4
[debug] Proxy map: {'no': 'localhost,127.0.0.0/8,::1'}
[8tracks] scurry-along-little-dove: Downloading webpage
[8tracks] scurry-along-little-dove: Downloading song information 1/13
[8tracks] scurry-along-little-dove: Downloading song information 2/13
[8tracks] scurry-along-little-dove: Downloading song information 3/13
[8tracks] scurry-along-little-dove: Downloading song information 4/13
[8tracks] scurry-along-little-dove: Downloading song information 5/13
[8tracks] scurry-along-little-dove: Waiting for 278.076923077 seconds
[8tracks] scurry-along-little-dove: Downloading song information 5/13
[8tracks] scurry-along-little-dove: Downloading song information 6/13
[8tracks] scurry-along-little-dove: Waiting for 278.076923077 seconds
[8tracks] scurry-along-little-dove: Downloading song information 6/13
[8tracks] scurry-along-little-dove: Downloading song information 7/13
[8tracks] scurry-along-little-dove: Waiting for 278.076923077 seconds
[8tracks] scurry-along-little-dove: Downloading song information 7/13
[8tracks] scurry-along-little-dove: Downloading song information 8/13
[8tracks] scurry-along-little-dove: Waiting for 278.076923077 seconds
[8tracks] scurry-along-little-dove: Downloading song information 8/13
[8tracks] scurry-along-little-dove: Downloading song information 9/13
[8tracks] scurry-along-little-dove: Waiting for 278.076923077 seconds
[8tracks] scurry-along-little-dove: Downloading song information 9/13
[8tracks] scurry-along-little-dove: Downloading song information 10/13
[8tracks] scurry-along-little-dove: Waiting for 278.076923077 seconds
[8tracks] scurry-along-little-dove: Downloading song information 10/13
[8tracks] scurry-along-little-dove: Downloading song information 11/13
[8tracks] scurry-along-little-dove: Downloading song information 12/13
[8tracks] scurry-along-little-dove: Waiting for 278.076923077 seconds
[8tracks] scurry-along-little-dove: Downloading song information 12/13
ERROR: An extractor error has occured. (caused by KeyError(u'id',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/albin/.bin/youtube-dl/youtube_dl/extractor/common.py", line 269, in extract
    return self._real_extract(url)
  File "/home/albin/.bin/youtube-dl/youtube_dl/extractor/eighttracks.py", line 144, in _real_extract
    'id': compat_str(track_data['id']),
KeyError: u'id'
Traceback (most recent call last):
  File "/home/albin/.bin/youtube-dl/youtube_dl/YoutubeDL.py", line 643, in extract_info
    ie_result = ie.extract(url)
  File "/home/albin/.bin/youtube-dl/youtube_dl/extractor/common.py", line 275, in extract
    raise ExtractorError('An extractor error has occured.', cause=e)
ExtractorError: An extractor error has occured. (caused by KeyError(u'id',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by raybesiga** [comment]
Looks like no one has taken a look into it. Time to dig..

**Comment by THPubs** [comment]
Same issue here!

**Comment by Maxog** [comment]
Still an issue.

**Comment by starfleeting** [comment]
Also experiencing this issue
