### ISSUE TITLE
Youtube: "Could not find JS function 'PF'"

### ISSUE THREAD

**Issue by brunal** [rg3/youtube-dl#5031]
Hi,
`youtube-dl` fails to dowload some videos from youtube.

```
$ youtube-dl --version
2015.02.11
$ youtube-dl --verbose https://www.youtube.com/watch?v=vmdldp6OgcI
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=vmdldp6OgcI']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.02.11
[debug] Python version 3.4.2 - Linux-3.18.6-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 2.5.4, ffprobe 2.5.4, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] vmdldp6OgcI: Downloading webpage
[youtube] vmdldp6OgcI: Extracting video information
[youtube] {22} signature length 40.41, html5 player en_US-vflF2Mg88
[youtube] vmdldp6OgcI: Downloading js player en_US-vflF2Mg88
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/youtube.py", line 635, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/youtube.py", line 549, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/youtube.py", line 613, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/lib/python3.4/site-packages/youtube_dl/jsinterp.py", line 244, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'PF'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Could not find JS function 'PF'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/youtube.py", line 635, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/youtube.py", line 549, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/youtube.py", line 613, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/lib/python3.4/site-packages/youtube_dl/jsinterp.py", line 244, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'PF'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/youtube.py", line 635, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/youtube.py", line 549, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/youtube.py", line 613, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/lib/python3.4/site-packages/youtube_dl/jsinterp.py", line 244, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'PF'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 633, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 270, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/youtube.py", line 1066, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/youtube.py", line 645, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/youtube.py", line 635, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/youtube.py", line 549, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/youtube.py", line 613, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/lib/python3.4/site-packages/youtube_dl/jsinterp.py", line 244, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'PF'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Could not find JS function 'PF'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by brunal** [comment]
Just updated to the latest versions, it's already been fixed.
