### ISSUE TITLE
[TenPlay] ERROR: Unable to extract video_id

### ISSUE THREAD

**Issue by pjta** [rg3/youtube-dl#5033]
$ youtube-dl http://tenplay.com.au/channel-eleven/neighbours/2015/2/23
[TenPlay] http://tenplay.com.au/channel-eleven/neighbours/2015/2/23: Downloading webpage
ERROR: Unable to extract video_id; please report this issue on https://yt-dl.org/bug .

$ youtube-dl -U
youtube-dl is up-to-date (2015.02.21)

**Comment by pjta** [comment]
doesn't reproduce in current version

**Comment by porjo** [comment]
I'm getting this error with current version (2015.09.22)

```
$ ./youtube-dl --verbose http://tenplay.com.au/channel-ten/the-bolt-report/2015/9/20
[debug] System config: [u'--prefer-free-formats']
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://tenplay.com.au/channel-ten/the-bolt-report/2015/9/20']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.09.22
[debug] Python version 2.7.10 - Linux-4.1.6-201.fc22.x86_64-x86_64-with-fedora-22-Twenty_Two
[debug] exe versions: ffmpeg 2.6.4, ffprobe 2.6.4, rtmpdump 2.4
[debug] Proxy map: {}
[TenPlay] http://tenplay.com.au/channel-ten/the-bolt-report/2015/9/20: Downloading webpage
ERROR: Unable to extract video_id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 660, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 287, in extract
    return self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/tenplay.py", line 38, in _real_extract
    r'videoID: "(\d+?)"', webpage, 'video_id')
  File "./youtube-dl/youtube_dl/extractor/common.py", line 590, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 581, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video_id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by JKZ9BH** [comment]
porjo,
I can confirm the issue with your download link and current version of youtube-dl. 
But you better create a new bug request. This one is already closed, so developers likely will not see it.

**Comment by pjta** [comment]
porjo,
I can confirm the issue with your download link and current version of youtube-dl.
But you better create a new bug request. This one is already closed, so developers likely will not see it.
