### ISSUE TITLE
ExtractorError: Could not find JS function u'PF'

### ISSUE THREAD

**Issue by msilberg** [rg3/youtube-dl#5047]
Try to run:
youtube-dl -f mp4 --verbose https://www.youtube.com/watch?v=FbzBJrOZiT0

Output:

[debug] System config: ['--prefer-free-formats']
[debug] User config: []
[debug] Command-line args: ['-f', 'mp4', '--verbose', 'https://www.youtube.com/watch?v=FbzBJrOZiT0']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.02.11
[debug] Python version 2.7.8 - Linux-3.18.7-200.fc21.x86_64-x86_64-with-fedora-21-Twenty_One
[debug] exe versions: ffmpeg 2.4.6, ffprobe 2.4.6
[debug] Proxy map: {}
[youtube] FbzBJrOZiT0: Downloading webpage
[youtube] FbzBJrOZiT0: Extracting video information
[youtube] {43} signature length 40.41, html5 player en_US-vflF2Mg88
[youtube] FbzBJrOZiT0: Downloading js player en_US-vflF2Mg88
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 635, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 549, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 613, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/lib/python2.7/site-packages/youtube_dl/jsinterp.py", line 244, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
ExtractorError: Could not find JS function u'PF'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Could not find JS function u'PF'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 635, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 549, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 613, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/lib/python2.7/site-packages/youtube_dl/jsinterp.py", line 244, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
ExtractorError: Could not find JS function u'PF'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 633, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 270, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 1066, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 645, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 635, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 549, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 613, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/lib/python2.7/site-packages/youtube_dl/jsinterp.py", line 244, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
ExtractorError: Could not find JS function u'PF'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Could not find JS function u'PF'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Env Details:

Fedora 21, x86_64.

**Comment by phihag** [comment]
See [our FAQ](https://github.com/rg3/youtube-dl#extractorerror-could-not-find-js-function-uof).

Since I believe this issue to be fixed in current versions of youtube-dl. If the problem persists with the [current version](https://yt-dl.org/latest/version) of youtube-dl, please post the output you get with that version and we will reopen this issue. Thanks!
