### ISSUE TITLE
Unable to extract mp3

### ISSUE THREAD

**Issue by Kcchouette** [rg3/youtube-dl#5062]
Here my traceback:

```
$ youtube-dl --audio-format mp3 "https://www.youtube.com/watch?v=OPf0YbXqDm0" --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--audio-format', 'mp3', 'https://www.youtube.com/watch?v=OPf0YbXqDm0', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.02.11
[debug] Python version 3.4.2 - Linux-3.16.7.6-1-MANJARO-x86_64-with-glibc2.3.4
[debug] exe versions: ffmpeg 2.5.4, ffprobe 2.5.4, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] OPf0YbXqDm0: Downloading webpage
[youtube] OPf0YbXqDm0: Extracting video information
[youtube] {22} signature length 43.41, html5 player en_US-vflQTSOsS
[youtube] OPf0YbXqDm0: Downloading js player en_US-vflQTSOsS
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/youtube.py", line 635, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/youtube.py", line 549, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/youtube.py", line 613, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/lib/python3.4/site-packages/youtube_dl/jsinterp.py", line 244, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'UF'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Could not find JS function 'UF'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/youtube.py", line 635, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/youtube.py", line 549, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/youtube.py", line 613, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/lib/python3.4/site-packages/youtube_dl/jsinterp.py", line 244, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'UF'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/youtube.py", line 635, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/youtube.py", line 549, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/youtube.py", line 613, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/lib/python3.4/site-packages/youtube_dl/jsinterp.py", line 244, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'UF'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 633, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 270, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/youtube.py", line 1066, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/youtube.py", line 645, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/youtube.py", line 635, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/youtube.py", line 549, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/youtube.py", line 613, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/lib/python3.4/site-packages/youtube_dl/jsinterp.py", line 244, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'UF'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Could not find JS function 'UF'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
Thanks

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Refer to [our FAQ](https://yt-dl.org/update) if you have trouble updating.
