### ISSUE TITLE
site request: monumentalnetwork.com

### ISSUE THREAD

**Issue by RingoTheDog** [rg3/youtube-dl#5073]
Example URL: http://www.monumentalnetwork.com/videos/john-carlson-postgame-2-25-15

youtube-dl.py -v "http://www.monumentalnetwork.com/videos/john-carlson-postgame-2-25-15"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.monumentalnetwork.com/videos/john-carlson-postgame-2-25-15']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.02.26.2
[debug] Python version 2.7.5 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-40824-g31dfe20, rtmpdump 2.4
[debug] Proxy map: {}
[generic] john-carlson-postgame-2-25-15: Requesting header
WARNING: Falling back on generic information extractor.
[generic] john-carlson-postgame-2-25-15: Downloading webpage
[generic] john-carlson-postgame-2-25-15: Extracting information
ERROR: Unsupported URL: http://www.monumentalnetwork.com/videos/john-carlson-postgame-2-25-15
Traceback (most recent call last):
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\generic.py", line 739, in _real_extract
    doc = parse_xml(webpage)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\utils.py", line 1522, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: mismatched tag: line 76, column 10
Traceback (most recent call last):
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 643, in extract_info
    ie_result = ie.extract(url)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\common.py", line 275, in extract
    return self._real_extract(url)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\generic.py", line 1184, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.monumentalnetwork.com/videos/john-carlson-postgame-2-25-15

Thanks as always...
Ringo

**Comment by RingoTheDog** [comment]
Not sure if this helps, but I just managed to find the actual video here:
http://cdnapi.kaltura.com/index.php/extwidget/openGraph/wid/1_yp9oaqca

...and YouTube-dl downloaded it correctly from Kaltura.

**Comment by naglis** [comment]
Support for Kaltura embeds on monumentalnetwork.com should be available in the next release of youtube-dl. Thanks for the report!

**Comment by RingoTheDog** [comment]
AWESOME...JUST AWESOME!
(all caps intended ;-)

**Comment by phihag** [comment]
I believe this issue to be fixed in youtube-dl 2015.02.28. See [our FAQ](https://yt-dl.org/update) if you need help updating.
