### ISSUE TITLE
One Youtube video fails to download

### ISSUE THREAD

**Issue by fvdm** [rg3/youtube-dl#5084]
<https://www.youtube.com/watch?v=9p9FON_ztrU>

I installed youtube-dl with Homebrew (OSX 10.10)

Verbose log:

```
$ youtube-dl --verbose https://www.youtube.com/watch?v=9p9FON_ztrU
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=9p9FON_ztrU']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.02.26.2
[debug] Python version 2.7.9 - Darwin-14.1.0-x86_64-i386-64bit
[debug] exe versions: avconv 11.2, avprobe 11.2, ffmpeg 2.5.4, ffprobe 2.5.4
[debug] Proxy map: {}
[youtube] 9p9FON_ztrU: Downloading webpage
[youtube] 9p9FON_ztrU: Extracting video information
ERROR: no conn, hlsvp or url_encoded_fmt_stream_map information found in video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 643, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 275, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1087, in _real_extract
    raise ExtractorError('no conn, hlsvp or url_encoded_fmt_stream_map information found in video info')
ExtractorError: no conn, hlsvp or url_encoded_fmt_stream_map information found in video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by dstftw** [comment]
Can you watch it in browser? Youtube tells me it's starting soon, so there is no video.

**Comment by fvdm** [comment]
@dstftw Indeed, for me too when I test on a computer with Flash.

**Comment by Gouthamve** [comment]
Indeed its not a video that is to be downloaded. But better error reporting would be helpful.
