### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf6

### ISSUE THREAD

**Issue by Retro64** [rg3/youtube-dl#5089]
http://rtl2now.rtl2.de/marvels-agents-of-shield/goetterdaemmerung.php?container_id=197057&player=1&season=1

Error appears on Windows and Linux.

Verbose-Log:
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://rtl2now.rtl2.de/marvels-agents-of-shield/goetterdaemmerung.php?container_id=197057&player=1&season=1', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.02.28
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: rtmpdump 2.4
[debug] Proxy map: {}
[RTLnow] 197057: Downloading webpage
[RTLnow] 197057: Downloading player data XML
[debug] Invoking downloader on u'rtmpe://fms.rtl.de/rtl2now'
[download] Destination: MARVEL's Agents of S.H.I.E.L.D.  - Götterdämmerung-197057.flv
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "youtube_dl\__init__.pyo", line 397, in main
  File "youtube_dl\__init__.pyo", line 387, in _real_main
  File "youtube_dl\YoutubeDL.pyo", line 1442, in download
  File "youtube_dl\YoutubeDL.pyo", line 654, in extract_info
  File "youtube_dl\YoutubeDL.pyo", line 700, in process_ie_result
  File "youtube_dl\YoutubeDL.pyo", line 1143, in process_video_result
  File "youtube_dl\YoutubeDL.pyo", line 1375, in process_info
  File "youtube_dl\YoutubeDL.pyo", line 1350, in dl
  File "youtube_dl\downloader\common.pyo", line 339, in download
  File "youtube_dl\downloader\rtmp.pyo", line 162, in real_download
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf6 in position 36: ordinal not in range(128)

Seems to be an encoding-problem - position 36 is the umlaut "ö".

When reverting the changes in youtube_dl/downloader/rtmp.py added in 2015.02.26.1 download works again (at least on Linux-machine).

**Comment by dstftw** [comment]
Closing since rtl2 is now served by nowtv.de.
