### ISSUE TITLE
"AssertionError: we should not get here!"

### ISSUE THREAD

**Issue by Gumnos** [rg3/youtube-dl#509]
I've been unable to duplicate this (running master, SHA: b7a34316d20d6eee3d44a7c3294cf01592e07388 ), using the same URL listed.  However, code thought unreachable was reached.  Full TB below: 
```
gumnos@box:~$ youtube-dl --get-url --prefer-free-formats -f 43 "http://www.youtube.com/watch?v=YHRxv-40WMU" | xclip -selection clipboard
Fetching from http://www.youtube.com/watch?v=YHRxv-40WMU
(122, 170)
Traceback (most recent call last):
  File "/usr/lib/python2.6/runpy.py", line 122, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.6/runpy.py", line 34, in _run_code
    exec code in run_globals
  File "/home/tim/bin/downloads/youtube-dl/youtube-dl/__main__.py", line 7, in <module>
  File "/home/tim/bin/downloads/youtube-dl/youtube-dl/__init__.py", line 548, in main
    
  File "/home/tim/bin/downloads/youtube-dl/youtube-dl/__init__.py", line 532, in _real_main
    
  File "/home/tim/bin/downloads/youtube-dl/youtube-dl/FileDownloader.py", line 475, in download
  File "/home/tim/bin/downloads/youtube-dl/youtube-dl/InfoExtractors.py", line 82, in extract
  File "/home/tim/bin/downloads/youtube-dl/youtube-dl/InfoExtractors.py", line 379, in _real_extract
  File "/home/tim/bin/downloads/youtube-dl/youtube-dl/utils.py", line 141, in get_element_by_id
  File "/home/tim/bin/downloads/youtube-dl/youtube-dl/utils.py", line 95, in loads
  File "/usr/lib/python2.6/HTMLParser.py", line 108, in feed
    self.goahead(0)
  File "/usr/lib/python2.6/HTMLParser.py", line 148, in goahead
    k = self.parse_starttag(i)
  File "/usr/lib/python2.6/HTMLParser.py", line 229, in parse_starttag
    endpos = self.check_for_whole_start_tag(i)
  File "/usr/lib/python2.6/HTMLParser.py", line 305, in check_for_whole_start_tag
    raise AssertionError("we should not get here!")
AssertionError: we should not get here!

```

**Comment by jaimeMF** [comment]
Starting with 3828505646a58d5e19f0ffe77821650e25d72b3a, we no longer use the HTMLParser from the standard library. Therefore I'm closing the issue. Thanks for the report!
