### ISSUE TITLE
Can't download video from xml page

### ISSUE THREAD

**Issue by ekimyar** [rg3/youtube-dl#5091]
Trying to set up a daily download of the rachel maddow show (don't judge). Only place that seems like it might work is http://podcastfeeds.nbcnews.com/audio/podcast/MSNBC-MADDOW-NETCAST-M4V.xml

Youtube playlist is audio only (weird but true.) Rachel maddow show page on MSNBC doesn't work. 

Doing this from a Raspberry Pi running Raspian 'Wheezy'. Here's what I get:

youtube-dl -o '/media/USBHDD1/TV/The Rachel Maddow Show/%(title)s-%(id)s.%(ext)s'  --download-archive ~/.mydownloads "http://podcastfeeds.nbcnews.com/audio/podcast/MSNBC-MADDOW-NETCAST-M4V.xml"                            [generic] MSNBC-MADDOW-NETCAST-M4V: Requesting header
WARNING: Falling back on generic information extractor.
[generic] MSNBC-MADDOW-NETCAST-M4V: Downloading webpage
[generic] MSNBC-MADDOW-NETCAST-M4V: Extracting information
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 397, in main

  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 387, in _real_main

  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1442, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 643, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 275, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 753, in _real_extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 587, in _extract_rss
AttributeError: 'NoneType' object has no attribute 'text'

**Comment by ekimyar** [comment]
I'm not sure how many Raspberry Pi hacking folks are Rachel Maddow watchers, but just in case the number is more than one, I wrote a bash script to make this work. I'm using it to download her show into my Kodi/XMBC TV directory each day that a new one is available 

> #!/bin/bash 
> ##download maddow each day in theory anyway
> ##of course it's not that easy. The youtube playlist is only audio. Dicks.
> ##so this is supposed to parse the xml, but I'm pretty sure it wont work
> wget "http://podcastfeeds.nbcnews.com/audio/podcast/MSNBC-MADDOW-NETCAST-M4V.xml" -O /home/pi/rachel.xml
> DATA=$(grep "enclosure url" /home/pi/rachel.xml)
> ##The echos are only here so I could watch what was happening while trying to make it work.
> echo $DATA
> url=$( echo $DATA | grep -oPm1 "(?<=<enclosure url\=\")[^\"]+" )
> ##Another debugging echo
> echo $url
> youtube-dl -o "/media/USBHDD1/TV/'The Rachel Maddow Show'/%(title)s-%(id)s.%(ext)s" --download-archive ~/.mydownloads $url

**Comment by phihag** [comment]
Fixed in youtube-dl 2015.03.03 and newer. See [our FAQ](https://yt-dl.org/update) if you need help updating.
