### ISSUE TITLE
.netrc authentication not working with Atresplayer.com site?

### ISSUE THREAD

**Issue by jjarava** [rg3/youtube-dl#5112]
Hi!

I'm trying to use `.netrc` to avoid having to type the username and password for www.Atresplayer.com (and to avoid having the auth. data on my history file). After some googling around, I've set-up my .netrc but regardless of how I put the info on the file, I always get a "stack trace" from youtube-dl:

```python
Mac-JJJ:TEMP_MEDIA_VIDEOS jjarava$ youtube-dl -n -v http://www.atresplayer.com/television/series/bajo-sospecha/temporada-1/capitulo-1-captulo_2015021600453.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-n', '-v', 'http://www.atresplayer.com/television/series/bajo-sospecha/temporada-1/capitulo-1-captulo_2015021600453.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.03.03
[debug] Python version 2.7.5 - Darwin-13.4.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 402, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 392, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1444, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 645, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 274, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 268, in initialize
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/atresplayer.py", line 53, in _real_initialize
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/atresplayer.py", line 56, in _login
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 582, in _get_login_info
AttributeError: 'AtresPlayerIE' object has no attribute '_NETRC_MACHINE'
```

It looks like the atreplayer *extractor* is not ready to get the info from the .netrc file

In case it's relevant, and to make sure the issue is not caused by the syntax in my `.netrc` file, these are the different "variations" of syntax I've tried, with the same results:

* `machine atresplayer login <email address> password <password>`
* `machine atresplayer.com login <email address> password <password>`
* `machine www.atresplayer.com login <email address> password <password>`
* `default login <email address> password <password>`

Thanks a lot for making this project such a great tool!!!

**Comment by phihag** [comment]
Thank you for the report! In youtube-dl 2015.03.03.1 and newer, `machine atresplayer login <email address> password <password>` should work. See [our FAQ](https://yt-dl.org/update) if you need help updating.
