### ISSUE TITLE
some canalplus videos fail on python3.2

### ISSUE THREAD

**Issue by xantares** [rg3/youtube-dl#5132]
altougth that url works fine on python3.4 (archlinux) with the same latest git version of ydl,
it does not on python3.2 (ubuntu 12.04) (also works on python2.7 ubuntu 12.04):
$ ~/.local/bin/youtube-dl -v http://www.canalplus.fr/c-divertissement/c-le-petit-journal/pid6515-emission.html?vid=1225963
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.canalplus.fr/c-divertissement/c-le-petit-journal/pid6515-emission.html?vid=1225963']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.03.03.1
[debug] Git HEAD: 29d9b24
[debug] Python version 3.2.3 - Linux-3.2.0-76-generic-x86_64-with-Ubuntu-12.04-precise
[debug] exe versions: avconv 0.8.16-4, avprobe 0.8.16-4, ffmpeg 0.8.16-4, ffprobe 0.8.16-4
[debug] Proxy map: {}
[Canalplus] pid6515-emission.html: Downloading webpage
[Canalplus] 1225963: Downloading video XML
[Canalplus] 1225963: Downloading f4m manifest
[Canalplus] 1225963: Downloading m3u8 information
[debug] Invoking downloader on 'http://us-cplus-aka.canal-plus.com/z/1503/04/nip_NIP_45844_,200k,400k,800k,1500k,.mp4.csmil/manifest.f4m?hdcore=2.11.3'
[download] Downloading f4m manifest
Traceback (most recent call last):
  File "/home/xantares/.local/bin/youtube-dl", line 9, in <module>
    load_entry_point('youtube-dl==2015.03.03.1', 'console_scripts', 'youtube-dl')()
  File "/home/xantares/.local/lib/python3.2/site-packages/youtube_dl-2015.03.03.1-py3.2.egg/youtube_dl/__init__.py", line 403, in main
    _real_main(argv)
  File "/home/xantares/.local/lib/python3.2/site-packages/youtube_dl-2015.03.03.1-py3.2.egg/youtube_dl/__init__.py", line 393, in _real_main
    retcode = ydl.download(all_urls)
  File "/home/xantares/.local/lib/python3.2/site-packages/youtube_dl-2015.03.03.1-py3.2.egg/youtube_dl/YoutubeDL.py", line 1447, in download
    res = self.extract_info(url)
  File "/home/xantares/.local/lib/python3.2/site-packages/youtube_dl-2015.03.03.1-py3.2.egg/youtube_dl/YoutubeDL.py", line 659, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/xantares/.local/lib/python3.2/site-packages/youtube_dl-2015.03.03.1-py3.2.egg/youtube_dl/YoutubeDL.py", line 705, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/home/xantares/.local/lib/python3.2/site-packages/youtube_dl-2015.03.03.1-py3.2.egg/youtube_dl/YoutubeDL.py", line 1148, in process_video_result
    self.process_info(new_info)
  File "/home/xantares/.local/lib/python3.2/site-packages/youtube_dl-2015.03.03.1-py3.2.egg/youtube_dl/YoutubeDL.py", line 1380, in process_info
    success = dl(filename, info_dict)
  File "/home/xantares/.local/lib/python3.2/site-packages/youtube_dl-2015.03.03.1-py3.2.egg/youtube_dl/YoutubeDL.py", line 1355, in dl
    return fd.download(name, info)
  File "/home/xantares/.local/lib/python3.2/site-packages/youtube_dl-2015.03.03.1-py3.2.egg/youtube_dl/downloader/common.py", line 341, in download
    return self.real_download(filename, info_dict)
  File "/home/xantares/.local/lib/python3.2/site-packages/youtube_dl-2015.03.03.1-py3.2.egg/youtube_dl/downloader/f4m.py", line 307, in real_download
    boot_info, bootstrap_url = self._parse_bootstrap_node(bootstrap_node, base_url)
  File "/home/xantares/.local/lib/python3.2/site-packages/youtube_dl-2015.03.03.1-py3.2.egg/youtube_dl/downloader/f4m.py", line 284, in _parse_bootstrap_node
    bootstrap = base64.b64decode(node.text)
  File "/usr/lib/python3.2/base64.py", line 83, in b64decode
    raise TypeError("expected bytes, not %s" % s.__class__.__name__)
TypeError: expected bytes, not str

**Comment by jaimeMF** [comment]
Thanks for the report, it will work in the next version.
