### ISSUE TITLE
InfoQ: Unable to extract encoded id

### ISSUE THREAD

**Issue by marekasf** [rg3/youtube-dl#5139]
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-u', u'PRIVATE', '-p', u'PRIVATE', 'http://www.infoq.com/presentations/xp-evolution', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.03.03.1
[debug] Python version 2.7.6 - Darwin-14.1.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[InfoQ] xp-evolution: Downloading webpage
WARNING: unable to extract description; please report this issue on http://yt-dl.org/bug
ERROR: Unable to extract encoded id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 648, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 275, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/infoq.py", line 37, in _real_extract
    r"jsclassref\s*=\s*'([^']*)'", webpage, 'encoded id')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 547, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract encoded id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by naglis** [comment]
Could you please include [the full output](https://github.com/rg3/youtube-dl/blob/master/CONTRIBUTING.md) you get with `--verbose`? In this case I'm missing the full URL of the video/presentation.

**Comment by ruozhuochen** [comment]
[error.txt](https://github.com/rg3/youtube-dl/files/570614/error.txt)

Also got the error
