### ISSUE TITLE
Download playlists doesn't work when a newline character is in the title

### ISSUE THREAD

**Issue by rmkraus** [rg3/youtube-dl#5161]
If there is a new line in a playlist H1 tag, youtube-dl is currently unable to parse out the playlist title. An example of such a playlist is here:

https://www.youtube.com/playlist?list=PLIamkchgCKVuSMFn1m8Yj2d67TyGtQxxE

This can be fixed by allowing the . in the regular expression to accept new lines by using the re.S flag. I did this in my own copy by changing line 362 of common.py to have 
flags=re.S 
by default instead of 
flags=0
I haven't found any negative results from this, but I am not familiar enough with the code to say that there aren't any.

At either rate, thanks for all your hard work, this application is great.

**Comment by dstftw** [comment]
Works perfectly for me. [playlist regex](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/youtube.py#L1324) already allows dot to match any character.
Post the **full** output you get when running [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by rmkraus** [comment]
Here is the output. Looks like I could use an update. In hindsight, that may be related.

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['https://www.youtube.com/playlist?list=PLIamkchgCKVuSMFn1m8Yj2d67TyGtQxxE', '--verbose']
[debug] Encodings: locale 'UTF-8', fs 'UTF-8', out 'UTF-8', pref: 'UTF-8'
[debug] youtube-dl version 2014.02.17
[debug] Python version 2.7.6 - Linux-3.13.0-37-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] Proxy map: {}
[youtube:playlist] PLIamkchgCKVuSMFn1m8Yj2d67TyGtQxxE: Downloading page #1
WARNING: [youtube:playlist] PLIamkchgCKVuSMFn1m8Yj2d67TyGtQxxE: Playlist page is missing OpenGraph title, falling back ...
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 1511, in _real_extract
    playlist_title = self._og_search_title(page)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 428, in _og_search_title
    return self._og_search_property('title', html, **kargs)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 416, in _og_search_property
    escaped = self._search_regex(self._og_regexes(prop), html, name, flags=re.DOTALL, **kargs)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 356, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract OpenGraph title; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 493, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 158, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 1517, in _real_extract
    r'<h1 class="pl-header-title">(.*?)</h1>', page, u'title')
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 366, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 356, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
```

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Refer to [our FAQ](https://yt-dl.org/update) if you have trouble updating.
