### ISSUE TITLE
Unable to download Playlist with output directory specified

### ISSUE THREAD

**Issue by kjesso** [rg3/youtube-dl#5176]
When trying to download a playlist to a specific directory youtube-dl fails with a permissions error, but when leaving out the directory path it works fine.

* **Command Example (working):** youtube-dl --yes-playlist "https://www.youtube.com/watch?v=6ikNYC0WVYs&list=PLzA5WNGSs-SF7h0zNhIidlU0h1KZ0WjlF"
 * **Result:** MP4 files are downloaded to the default directory (C:\Users\%username%\)

* **Command Example (failed):** youtube-dl --yes-playlist --output "C:\Temp\Downloads" "https://www.youtube.com/watch?v=6ikNYC0WVYs&list=PLzA5WNGSs-SF7h0zNhIidlU0h1KZ0WjlF"
 * **Result:** YouTube-DL fails and no MP4 files are downloaded to specified directory nor the default directory

**Note:** I also tried specifying the full path to the YouTube-DL executable, but that also fails: "C:\Program Files\Youtube-DL\youtube-dl.exe" --yes-playlist --output "C:\Temp\Downloads" "https://www.youtube.com/watch?v=6ikNYC0WVYs&list=PLzA5WNGSs-SF7h0zNhIidlU0h1KZ0WjlF"

Below is the verbose output from the failed example when specifying the output directory:
```python
youtube-dl -v --yes-playlist --output "C:\Temp\Downloads" "https://www.youtube.com/watch?v=6ikNYC0WVYs&list=PLzA5WNGSs-SF7h0zNhIidlU0h1KZ0WjlF"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', '--yes-playlist', '--output', 'C:\\Temp\\Downloads', 'https://www.youtube.com/watch?v=6ikNYC0WVYs&list=PLzA5WNGSs-SF7h0zNhIidlU0h1KZ0WjlF']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.03.09
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-63548-g6b041cb, ffprobe N-63548-g6b041cb
[debug] Proxy map: {}
[youtube:playlist] Downloading playlist PLzA5WNGSs-SF7h0zNhIidlU0h1KZ0WjlF - add --no-playlist to just download video 6ikNYC0WVYs
[youtube:playlist] PLzA5WNGSs-SF7h0zNhIidlU0h1KZ0WjlF: Downloading webpage
[download] Downloading playlist: Treble Charger - Self Title
[youtube:playlist] playlist Treble Charger - Self Title: Collected 9 video ids (downloading 9 of them)
[download] Downloading video 1 of 9
[youtube] 6ikNYC0WVYs: Downloading webpage
[youtube] 6ikNYC0WVYs: Extracting video information
[youtube] {43} signature length 40.43, html5 player en_US-vflT9SJ6t
[youtube] {18} signature length 40.43, html5 player en_US-vflT9SJ6t
[youtube] {5} signature length 40.43, html5 player en_US-vflT9SJ6t
[youtube] {36} signature length 40.43, html5 player en_US-vflT9SJ6t
[youtube] {17} signature length 40.43, html5 player en_US-vflT9SJ6t
[youtube] {134} signature length 40.43, html5 player en_US-vflT9SJ6t
[youtube] {243} signature length 40.43, html5 player en_US-vflT9SJ6t
[youtube] {133} signature length 40.43, html5 player en_US-vflT9SJ6t
[youtube] {242} signature length 40.43, html5 player en_US-vflT9SJ6t
[youtube] {160} signature length 40.43, html5 player en_US-vflT9SJ6t
[youtube] {140} signature length 40.43, html5 player en_US-vflT9SJ6t
[youtube] {171} signature length 40.43, html5 player en_US-vflT9SJ6t
[youtube] 6ikNYC0WVYs: Downloading DASH manifest
[debug] Invoking downloader on u'https://r9---sn-nx57yne7.googlevideo.com/videoplayback?fexp=907263%2C924622%2C927622%2C934954%2C9406664%2C9406974%2C9407752%2C942661%2C943917%2C948124%2C948703%2C949011%2C951703%2C952302%2C952612%2C952901%2C955301%2C957201%2C959701%2C960602&mm=31&key=yt5&id=o-ALCizc_0JDpRcbH969Bj0RW06acOzHJ-qp0fMTcfcYTU&gcr=ca&dur=195.117&source=youtube&ms=au&requiressl=yes&ip=50.67.208.237&pl=19&mv=m&ratebypass=yes&initcwndbps=1722500&ipbits=0&mt=1426022138&itag=18&expire=1426043823&sparams=dur%2Cgcr%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Cmime%2Cmm%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&upn=WKlvp3DJp9U&sver=3&mime=video%2Fmp4&signature=ACBBA7CBAD6C5D1CD14B39FEAC819C0D5CEA798C.2D80482635E0D4C1AD5BEAB0B2B9FB65AC7F19F8'
ERROR: unable to open for writing: [Errno 13] Permission denied: u'C:\\Temp\\Downloads'
Traceback (most recent call last):
  File "youtube_dl\downloader\http.pyo", line 160, in real_download
  File "youtube_dl\utils.pyo", line 248, in sanitize_open
IOError: [Errno 13] Permission denied: u'C:\\Temp\\Downloads'
```

**Comment by phihag** [comment]
`-o` is an output *template*, not a directory. You want something like `-o "C:\Temp\Downloads\%(title)s-%(id)s.%(ext)s"`.

**Comment by kjesso** [comment]
Great thanks, I'm glad it was just a simple misuse of the syntax.
