### ISSUE TITLE
https://www.tvnz.co.nz/worlds-worst/s1-ep1-video-6251831 fails to download

### ISSUE THREAD

**Issue by zenaan** [rg3/youtube-dl#5183]
I'm happy to run more tests if need be. Would be nice to have tvnz.co.nz videos work with ytdl :)

$ TZ="NZST" youtube-dl 'https://www.tvnz.co.nz/worlds-worst/s1-ep1-video-6251831' --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['https://www.tvnz.co.nz/worlds-worst/s1-ep1-video-6251831', '--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.03.09
[debug] Python version 2.7.9 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.0
[debug] exe versions: rtmpdump 2.4
[debug] Proxy map: {}
[generic] s1-ep1-video-6251831: Requesting header
WARNING: Falling back on generic information extractor.
[generic] s1-ep1-video-6251831: Downloading webpage
[generic] s1-ep1-video-6251831: Extracting information
ERROR: Unsupported URL: https://www.tvnz.co.nz/worlds-worst/s1-ep1-video-6251831
Traceback (most recent call last):
  File "/home/justa/bin/youtube-dl/youtube_dl/extractor/generic.py", line 814, in _real_extract
    doc = parse_xml(webpage)
  File "/home/justa/bin/youtube-dl/youtube_dl/utils.py", line 1521, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: mismatched tag: line 96, column 2
Traceback (most recent call last):
  File "/home/justa/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 649, in extract_info
    ie_result = ie.extract(url)
  File "/home/justa/bin/youtube-dl/youtube_dl/extractor/common.py", line 275, in extract
    return self._real_extract(url)
  File "/home/justa/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1283, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.tvnz.co.nz/worlds-worst/s1-ep1-video-6251831

In Firefox, this site requires the timezone to be correctly set, or an error along the lines "incorrect timezone" is displayed where the video player would normally appear.

**Comment by gardner** [comment]
This may be a duplicate of #4256.

**Comment by 89z** [comment]
issue should be closed, URL is dead
