### ISSUE TITLE
IOError: Invalid argument when downloading from 8tracks

### ISSUE THREAD

**Issue by albins** [rg3/youtube-dl#5200]
It would seem that the waiting instruction is incorrect – how can you possibly sleep for a negative amount of time?
```
albin@hecate ~/Downloads % youtube-dl http://8tracks.com/jatalliah/morning-sun --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://8tracks.com/jatalliah/morning-sun', '--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.03.09
[debug] Python version 2.7.9 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.0
[debug] exe versions: avconv 11.2-6, avprobe 11.2-6, ffmpeg 0.8.7-6, rtmpdump 2.4
[debug] Proxy map: {'http': 'http://localhost:8123/', 'https': 'http://localhost:8123/', 'no': 'localhost,127.0.0.0/8,::1'}
[8tracks] morning-sun: Downloading webpage
[8tracks] morning-sun: Downloading song information 1/24
[8tracks] morning-sun: Downloading song information 2/24
[8tracks] morning-sun: Downloading song information 3/24
[8tracks] morning-sun: Downloading song information 4/24
[8tracks] morning-sun: Downloading song information 5/24
[8tracks] morning-sun: Downloading song information 6/24
[8tracks] morning-sun: Waiting for -1543.04166667 seconds
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/albin/.bin/youtube-dl/__main__.py", line 19, in <module>
  File "/home/albin/.bin/youtube-dl/youtube_dl/__init__.py", line 403, in main
  File "/home/albin/.bin/youtube-dl/youtube_dl/__init__.py", line 393, in _real_main
  File "/home/albin/.bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1448, in download
  File "/home/albin/.bin/youtube-dl/youtube_dl/YoutubeDL.py", line 649, in extract_info
  File "/home/albin/.bin/youtube-dl/youtube_dl/extractor/common.py", line 275, in extract
  File "/home/albin/.bin/youtube-dl/youtube_dl/extractor/eighttracks.py", line 139, in _real_extract
  File "/home/albin/.bin/youtube-dl/youtube_dl/extractor/common.py", line 806, in _sleep
IOError: [Errno 22] Invalid argument
```

**Comment by dstftw** [comment]
It will be fixed in the next version. Thanks for the report.
