### ISSUE TITLE
ARD-Mediathek: Error 403

### ISSUE THREAD

**Issue by kevinm90** [rg3/youtube-dl#5213]
When I try to download a video from ARD Mediathek (ardmediathek.de) it gives me the following error: 
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError());

Edit: I tried to download http://www.ardmediathek.de/tv/Tatort/Grenzfall-Video-tgl-ab-20-Uhr/Das-Erste/Video?documentId=26935962&bcastId=602916

**Comment by dstftw** [comment]
Post the **full** output you get when running [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by kevinm90** [comment]
youtube-dl --verbose http://www.ardmediathek.de/tv/Tatort/Grenzfall-Video-tgl-ab-20-Uhr/Das-Erste/Video?documentId=26935962&bcastId=602916
[1] 26040
Kevins-MacBook-Pro-2:~ kevinmaerz$ [debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.ardmediathek.de/tv/Tatort/Grenzfall-Video-tgl-ab-20-Uhr/Das-Erste/Video?documentId=26935962']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.03.09
[debug] Python version 2.7.6 - Darwin-14.1.0-x86_64-i386-64bit
[debug] exe versions: rtmpdump Reason
[debug] Proxy map: {}
[ARD:mediathek] 26935962: Downloading webpage
[ARD:mediathek] 26935962: Downloading JSON metadata
[debug] Invoking downloader on u'http://mvideos-geo.daserste.de/videoportal/Film/c_510000/513000/format609631.mp4'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1381, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1356, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 341, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 64, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1675, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden

**Comment by dstftw** [comment]
Can you watch it in browser right now?
It tells me that
```
Diese Sendung ist für Jugendliche unter 12 Jahren nicht geeignet. Der Clip ist deshalb nur von 20 bis 6 Uhr verfügbar.
```

**Comment by kevinm90** [comment]
No, I can't. But i could download it before. Maybe they fixed this backdoor to bypass the youth-protection :(

**Comment by dstftw** [comment]
In the next version this error will be captured and shown by youtube-dl. Thanks for the report.

**Comment by kevinm90** [comment]
Great, thanks for the very quick responses and fix.
