### ISSUE TITLE
ERROR: unable to download video data: HTTP Error 403

### ISSUE THREAD

**Issue by larsenlouis** [rg3/youtube-dl#5229]
Running youtube-dl.exe version 2015.03.15 on Windows server 2008 r2 SP1.

```
youtube-dl --proxy=127.0.0.1:8087 www.youtube.com/watch?v=Hy1ht3-QWqE -f 137+140 --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--proxy=127.0.0.1:8087', 'www.youtube.com/watch?v=Hy1ht3-QWqE', '-f', '137+140', '--verbose']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2015.03.09
[debug] Python version 2.7.8 - Windows-2008ServerR2-6.1.7601-SP1
[debug] exe versions: ffmpeg N-70634-g3bedc99
[debug] Proxy map: {u'http': '127.0.0.1:8087', u'https': '127.0.0.1:8087'}
WARNING: The url doesn't specify the protocol, trying with http
[youtube] Hy1ht3-QWqE: Downloading webpage
[youtube] Hy1ht3-QWqE: Extracting video information
[youtube] Hy1ht3-QWqE: Downloading DASH manifest
WARNING: [youtube] Hy1ht3-QWqE: Skipping DASH manifest: ExtractorError(u'Could not download DASH manifest: HTTP Error 403:  (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
[debug] Invoking downloader on u'https://r4---sn-i3b7rne7.googlevideo.com/videoplayback?nh=IgpwcjA0LmhrZzAxKgkxMjcuMC4wLjE&key=yt5&lmt=1426510321179367&source=youtube&cwbf=0.25&mime=video%2Fmp4&pl=16&clen=74218913&dur=192.080&expire=1426676547&mv=m&mm=31&keepalive=yes&upn=9OYO7lhdQ2o&sparams=clen%2Ccwbf%2Cdur%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cms%2Cmv%2Cnh%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&initcwndbps=530000&ms=au&itag=137&mt=1426654880&ip=113.132.128.162&gir=yes&signature=806708D98711F7675D3EAD8D6830714A7C454EDE.20A5BAEC2F0C88FF0EB3338E2BD68CE93DFEC24F&ipbits=0&requiressl=yes&id=oADbK1q_6Ut6L9dd9cDQKlsDgKXtsC65JpXylHgTwBNBk&sver=3&fexp=900720%2C904723%2C907263%2C927622%2C934954%2C936022%2C936117%2C9406594%2C9406827%2C9407103%2C9407792%2C9407880%2C945067%2C948124%2C951511%2C951703%2C952302%2C952612%2C952901%2C955301%2C957201%2C959701%2C961404%2C964752&ratebypass=yes'
ERROR: unable to download video data: HTTP Error 403:
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 1375, in process_info
  File "youtube_dl\YoutubeDL.pyo", line 1356, in dl
  File "youtube_dl\downloader\common.pyo", line 341, in download
  File "youtube_dl\downloader\http.pyo", line 64, in real_download
  File "youtube_dl\YoutubeDL.pyo", line 1675, in urlopen
  File "urllib2.pyo", line 410, in open
  File "urllib2.pyo", line 523, in http_response
  File "urllib2.pyo", line 448, in error
  File "urllib2.pyo", line 382, in _call_chain
  File "urllib2.pyo", line 531, in http_error_default
HTTPError: HTTP Error 403:
```

**Comment by yan12125** [comment]
What's the proxy software running at 127.0.0.1:8087?
Both DASH manists and the final URL has domain ```*.googlevideo.com```, and I guess your proxy does not allow these URLs.

**Comment by larsauswsw** [comment]
Maybe same issue like #5118

**Comment by larsenlouis** [comment]
The proxy is [goagent](https://github.com/goagent/goagent). Today I test it on a Windows 8.1 machine in a different Internet environment with the latest version 2015.07.07.

It does do the download but tried twice to fetch the DASH manifests according to the debug.

```
youtube-dl --proxy=127.0.0.1:8087 www.youtube.com/watch?v=Hy1ht3-QWqE -f 137+140 --verbose > debug.txt
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--proxy=127.0.0.1:8087', u'www.youtube.com/watch?v=Hy1ht3-QWqE', u'-f', u'137+140', u'--verbose']
[debug] Encodings: locale cp936, fs mbcs, out None, pref cp936
[debug] youtube-dl version 2015.07.07
[debug] Python version 2.7.8 - Windows-8-6.2.9200
[debug] exe versions: ffmpeg N-73361-g03b2b40, ffprobe N-73361-g03b2b40, rtmpdump 2.4
[debug] Proxy map: {u'http': u'127.0.0.1:8087', u'https': u'127.0.0.1:8087'}
WARNING: The url doesn't specify the protocol, trying with http
[youtube] Hy1ht3-QWqE: Downloading webpage
[youtube] Hy1ht3-QWqE: Downloading video info webpage
[youtube] Hy1ht3-QWqE: Extracting video information
[youtube] Hy1ht3-QWqE: Downloading DASH manifest
[youtube] Hy1ht3-QWqE: Downloading DASH manifest
[debug] Invoking downloader on 'https://r18---sn-q4f7dn7r.googlevideo.com/videoplayback?id=1f2d61b77f905aa1&itag=137&source=youtube&requiressl=yes&mm=31&ms=au&mn=sn-q4f7dn7r&mv=m&pl=27&ratebypass=yes&mime=video/mp4&gir=yes&clen=44170296&lmt=1427101636508726&dur=192.080&key=dg_yt0&fexp=901816,9406545,9407014,9408142,9408420,9408710,9412526,9412774,9414891,9415560,9415942,9415991,9416126,9416338,9416484,9416529,9416729&signature=11912BD5FBB5AC6F6CC9D09E84F6B73A8A465E45.565C645A0EF24737F359942DC7EB1B96D286F4E0&mt=1436346793&upn=DMw1oUqpvW8&sver=3&ip=107.178.195.207&ipbits=0&expire=1436368487&sparams=ip,ipbits,expire,id,itag,source,requiressl,mm,ms,mn,mv,pl,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: Marit Larsen - I Don't Want To Talk About It (Live)-Hy1ht3-QWqE.f137.mp4
...
...
```
@yan12125 I don't think the proxy blocks the requests.

@larsauswsw It's pretty much like it in the link!

**Comment by yan12125** [comment]
@larsenlouis If you can download via one proxy server while not on another, it's probably the problem of the specific proxy server. Can you reproduce the error now?
And it's normal that youtube-dl downloads multiple DASH manifests due to #6097.

**Comment by dstftw** [comment]
Works fine with latest version (2016.05.16).
