### ISSUE TITLE
Grooveshark - download function broken

### ISSUE THREAD

**Issue by hstracker90** [rg3/youtube-dl#5232]
Hi! Grooveshark just changed their web design and obviously they also changed internals.
This is the output when I try to download a song (I tried others to the same effect):

C:\Windows> ytdl "http://grooveshark.com/#!/s/Tune+Down/21gzJk?src=5" --verbose
[debug] System config: []
[debug] User config: ['-o', 'C:/Users/username/Downloads/%(title)s.%(ext)s']
[debug] Command-line args: ['http://grooveshark.com/#!/s/Tune+Down/21gzJk?src=5', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.03.15
[debug] Python version 2.7.8 - Windows-8-6.2.9200
[debug] exe versions: ffmpeg N-68482-g92a596f, ffprobe N-68482-g92a596f, rtmpdump 2.4
[debug] Proxy map: {}
[Grooveshark] 40fxOl: Downloading player page
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "youtube_dl\__init__.pyo", line 408, in main
  File "youtube_dl\__init__.pyo", line 398, in _real_main
  File "youtube_dl\YoutubeDL.pyo", line 1452, in download
  File "youtube_dl\YoutubeDL.pyo", line 654, in extract_info
  File "youtube_dl\extractor\common.pyo", line 275, in extract
  File "youtube_dl\extractor\grooveshark.pyo", line 158, in _real_extract
IndexError: list index out of range

I kindly ask the experts to look into this. Thank you once again for this great tool!

**Comment by jaimeMF** [comment]
Thanks for the report, it was fixed in b1337948ebeeacfcf104d513fac5913d3a5818a7. It should work in the next version.

**Comment by hstracker90** [comment]
Working again in 2015.03.18! Thanks a lot!
