### ISSUE TITLE
vine.co errors

### ISSUE THREAD

**Issue by Markris** [rg3/youtube-dl#5240]
for example (youtube-dl version 2015.03.18 on Windows7 64bit):

C:\Prog>youtube-dl.exe https://vine.co/v/MInzDm7MVzg
[Vine] MInzDm7MVzg: Downloading webpage
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "youtube_dl\__init__.pyo", line 408, in main
  File "youtube_dl\__init__.pyo", line 398, in _real_main
  File "youtube_dl\YoutubeDL.pyo", line 1452, in download
  File "youtube_dl\YoutubeDL.pyo", line 665, in extract_info
  File "youtube_dl\YoutubeDL.pyo", line 711, in process_ie_result
  File "youtube_dl\YoutubeDL.pyo", line 1067, in process_video_result
  File "youtube_dl\YoutubeDL.pyo", line 968, in _calc_headers
  File "youtube_dl\YoutubeDL.pyo", line 975, in _calc_cookies
  File "urllib2.pyo", line 202, in __init__
  File "urllib.pyo", line 1060, in unwrap
AttributeError: 'NoneType' object has no attribute 'strip'

**Comment by naglis** [comment]
Fixed in ccf3960. This issue should be fixed in the next release of youtube-dl. Thanks for the report.
