### ISSUE TITLE
Error with Netzkino URL

### ISSUE THREAD

**Issue by sket** [rg3/youtube-dl#5251]
The Netzkino extractor seems to have a bug:

 youtube-dl --verbose http://www.netzkino.de/search/blade-runner-the-final-cut-2007
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.netzkino.de/search/blade-runner-the-final-cut-2007']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.03.18
[debug] Python version 2.7.3 - Linux-3.2.0-4-amd64-x86_64-with-debian-7.8
[debug] exe versions: rtmpdump 2.4
[debug] Proxy map: {}
[generic] blade-runner-the-final-cut-2007: Requesting header
[redirect] Following redirect to http://www.netzkino.de/#!/search/blade-runner-the-final-cut-2007
[Netzkino] blade-runner-the-final-cut-2007: Downloading JSON metadata
ERROR: An extractor error has occured. (caused by KeyError(u'posts',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 275, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/netzkino.py", line 45, in _real_extract
    p for p in api_info['posts'] if p['slug'] == video_id)
KeyError: u'posts'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 654, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 281, in extract
    raise ExtractorError('An extractor error has occured.', cause=e)
ExtractorError: An extractor error has occured. (caused by KeyError(u'posts',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dingensundso** [comment]
The link you provided is not working. But I also had issues with this extractor. The API-url is only for main catagories but most categories have subcategories. Thos subcategories are prefixed before the main category + '-'.

So I changed Line 39:
`- category_id = mobj.group('category')`
`+ category_id = mobj.group('category').split('-')[-1]`

Sorry I'm too lazy to create a PR right now.

**Comment by yan12125** [comment]
@dingensundso Do you have a working Netzkino URL?

**Comment by dstftw** [comment]
There is a PR #8550.
