### ISSUE TITLE
Error downloading vine video (AttributeError: 'NoneType' object has no attribute 'strip')

### ISSUE THREAD

**Issue by woodenphone** [rg3/youtube-dl#5274]
C:\Users\User\Dropbox\AnonArchive Folder\ctrl-s\tumblr_api_to_db\youtube-dl>yout
ube-dl.exe -v --update
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', '--update']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.03.18
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
youtube-dl is up-to-date (2015.03.18)

C:\Users\User\Dropbox\AnonArchive Folder\ctrl-s\tumblr_api_to_db\youtube-dl>yout
ube-dl.exe -v https://vine.co/v/hjWIUFOYD31/embed/simple
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'https://vine.co/v/hjWIUFOYD31/embed/simple']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.03.18
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[Vine] hjWIUFOYD31: Downloading webpage
WARNING: unable to extract OpenGraph description; please report this issue on ht
tp://yt-dl.org/bug
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "youtube_dl\__init__.pyo", line 408, in main
  File "youtube_dl\__init__.pyo", line 398, in _real_main
  File "youtube_dl\YoutubeDL.pyo", line 1452, in download
  File "youtube_dl\YoutubeDL.pyo", line 665, in extract_info
  File "youtube_dl\YoutubeDL.pyo", line 711, in process_ie_result
  File "youtube_dl\YoutubeDL.pyo", line 1067, in process_video_result
  File "youtube_dl\YoutubeDL.pyo", line 968, in _calc_headers
  File "youtube_dl\YoutubeDL.pyo", line 975, in _calc_cookies
  File "urllib2.pyo", line 202, in __init__
  File "urllib.pyo", line 1060, in unwrap
AttributeError: 'NoneType' object has no attribute 'strip'

C:\Users\User\Dropbox\AnonArchive Folder\ctrl-s\tumblr_api_to_db\youtube-dl>yout
ube-dl.exe -v https://vine.co/v/hjWIUFOYD31
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'https://vine.co/v/hjWIUFOYD31']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.03.18
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[Vine] hjWIUFOYD31: Downloading webpage
WARNING: unable to extract OpenGraph description; please report this issue on ht
tp://yt-dl.org/bug
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "youtube_dl\__init__.pyo", line 408, in main
  File "youtube_dl\__init__.pyo", line 398, in _real_main
  File "youtube_dl\YoutubeDL.pyo", line 1452, in download
  File "youtube_dl\YoutubeDL.pyo", line 665, in extract_info
  File "youtube_dl\YoutubeDL.pyo", line 711, in process_ie_result
  File "youtube_dl\YoutubeDL.pyo", line 1067, in process_video_result
  File "youtube_dl\YoutubeDL.pyo", line 968, in _calc_headers
  File "youtube_dl\YoutubeDL.pyo", line 975, in _calc_cookies
  File "urllib2.pyo", line 202, in __init__
  File "urllib.pyo", line 1060, in unwrap
AttributeError: 'NoneType' object has no attribute 'strip'

C:\Users\User\Dropbox\AnonArchive Folder\ctrl-s\tumblr_api_to_db\youtube-dl>

**Comment by naglis** [comment]
This issue has already been addressed (see #5240). It should be fixed in the next version, when it comes out. Nevertheless, thanks for reporting it.
