### ISSUE TITLE
[YouTube] Cannot get videos from watch later feed/playlist anymore

### ISSUE THREAD

**Issue by e-d-n-a** [rg3/youtube-dl#5280]
Youtube-dl just exits without any errors, when I try to get the IDs of videos from my watch later feed.

Command line (test):
```
 ytdl :ytwatchlater -i -u [user] -p [password] --get-id --playlist-start 1 --playlist-end 2 -v --print-traffic
```
(with the real credentials and the last two options for debugging only)

I used the same command line dozens of times and it worked until today.
Of course I updated to the most recent version (2015-03-24) after the first encounter, but the problem persists.
When checking the traffic, I see that the instance stops right after this:

```
[...]
send: u'GET /feed_ajax?action_load_personal_feed=1&feed_name=watch_later&paging=0 HTTP/1.1\r\n
[...request headers...]
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Wed, 25 Mar 2015 01:41:01 GMT
header: Server: gwiseguy/2.0
header: Cache-Control: no-cache
header: X-Frame-Options: SAMEORIGIN
header: X-Content-Type-Options: nosniff
header: X-XSS-Protection: 1; mode=block; report=https://www.google.com/appserve/security-bugs/log/youtube
header: Content-Encoding: gzip
header: Content-Type: application/json; charset=UTF-8
header: Content-Disposition: attachment
header: Expires: Tue, 27 Apr 1971 19:44:06 EST
header: Connection: close
header: Transfer-Encoding: chunked
```

Data of reply (watch_later_feed_https_-_www.youtube.com_feed_ajaxact
ion_load_personal_feed\=1_feed_name\=watch_later_paging\=0.dump):
```json
{"content_html": "    \n  \n\n", "load_more_widget_html": "  \n  \n\n\n    \u003cbutton class=\"yt-uix-button yt-uix-button-size-default yt-uix-button-default load-more-button yt-uix-load-more browse-items-load-more-button\" type=\"button\" onclick=\";return false;\" data-uix-load-more-href=\"\/feed_ajax?action_load_personal_feed=1\u0026amp;feed_name=watch_later\" data-uix-load-more-target-id=\"browse-items-primary\"\u003e\u003cspan class=\"yt-uix-button-content\"\u003e  \u003cspan class=\"load-more-loading hid\"\u003e\n      \n  \u003cspan class=\"yt-spinner\"\u003e\n      \n  \u003cspan title=\"Loading icon\" class=\"yt-spinner-img  yt-sprite\"\u003e\u003c\/span\u003e\n\nLoading...\n  \u003c\/span\u003e\n\n  \u003c\/span\u003e\n  \u003cspan class=\"load-more-text\"\u003e\nLoad more\n  \u003c\/span\u003e\n\u003c\/span\u003e\u003c\/button\u003e\n\n"}
```

The content of the reply may seem odd, but I don't know how it looks normally.

If this can be confirmed, there's hopefully an easy way to fix this!?

Thanks in advance for any help in regard of this problem!

**Comment by desdinova69** [comment]
It´s happening for me as well. Maybe Youtube changed something.

**Comment by dstftw** [comment]
Will be fixed in the next version. Thanks for the report.

**Comment by GotenXiao** [comment]
Just tested 448830ce7b180250a9f2cbafc1625a20584e59d3 with my download script and got the following:
```
[youtube:playlist] Downloading login page
[youtube:playlist] Logging in
[youtube:playlist] WL: Downloading webpage
ERROR: The playlist doesn't exist or is private, use --username or --netrc to access it.
```

Invoked as `youtube-dl --netrc --download-archive ~/.cache/youtube-dl-archive -Acit :ytwatchlater`

.netrc contains an unchanged, previously working application password.

**Comment by dstftw** [comment]
This is not yet released. Your script is using an old version.

**Comment by jaimeMF** [comment]
I also got the same error with the last commit from master, running the command a second time worked (don't know why).

**Comment by GotenXiao** [comment]
Just updated to latest master, now running:
```
$ youtube-dl --version
2015.03.26-git-15b67a268adb88098b7fa9752c998c3e886c0d06
```
Same error. Installed via python setup.py install --user from a cloned git repository.

**Comment by jaimeMF** [comment]
I also logged in a browser, that may be the reason why it works now.

**Comment by dstftw** [comment]
Works perfectly for me both with and without browser session.

**Comment by GotenXiao** [comment]
This may well be related to my use of app passwords then, I'll test with alternate credentials.

**Comment by dstftw** [comment]
@GotenXiao post full `--verbose` output.

**Comment by GotenXiao** [comment]
Confirmed working manually supplying --username and --twofactor, so it's likely related to my use of --netrc with an app password.

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--download-archive', u'/home/goten/.cache/youtube-dl-archive', u'-Acit', u':ytwatchlater', u'--netrc', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.03.26-git-15b67a268adb88098b7fa9752c998c3e886c0d06
[debug] Python version 2.7.3 - Linux-3.14-1-amd64-x86_64-with-debian-7.8
[debug] exe versions: avconv 1.0.10, avprobe 1.0.10, ffmpeg 1.0.10, ffprobe 1.0.10, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:watchlater] Downloading login page
[youtube:watchlater] Logging in
[youtube:watchlater] WL: Downloading webpage
ERROR: The playlist doesn't exist or is private, use --username or --netrc to access it.
Traceback (most recent call last):
  File "/home/goten/.local/lib/python2.7/site-packages/youtube_dl-2015.03.26_git_15b67a268adb88098b7fa9752c998c3e886c0d06-py2.7.egg/youtube_dl/YoutubeDL.py", line 651, in extract_info
    ie_result = ie.extract(url)
  File "/home/goten/.local/lib/python2.7/site-packages/youtube_dl-2015.03.26_git_15b67a268adb88098b7fa9752c998c3e886c0d06-py2.7.egg/youtube_dl/extractor/common.py", line 275, in extract
    return self._real_extract(url)
  File "/home/goten/.local/lib/python2.7/site-packages/youtube_dl-2015.03.26_git_15b67a268adb88098b7fa9752c998c3e886c0d06-py2.7.egg/youtube_dl/extractor/youtube.py", line 1665, in _real_extract
    return self._extract_playlist('WL')
  File "/home/goten/.local/lib/python2.7/site-packages/youtube_dl-2015.03.26_git_15b67a268adb88098b7fa9752c998c3e886c0d06-py2.7.egg/youtube_dl/extractor/youtube.py", line 1276, in _extract_playlist
    expected=True)
ExtractorError: The playlist doesn't exist or is private, use --username or --netrc to access it.
```
