### ISSUE TITLE
vine.co loops not downloading for me [AttributeError: 'NoneType' object has no attribute 'strip']

### ISSUE THREAD

**Issue by friedretinas** [rg3/youtube-dl#5285]
Is this not working or am I'm doing something wrong?   Thanks for your assistance w/ this.

youtube-dl --verbose https://vine.co/v/OYwITBmlDYQ
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'https://vine.co/v/OYwITBmlDYQ']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.03.18
[debug] Python version 2.7.6 - Linux-3.13.0-46-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.18-6, avprobe 9.18-6, rtmpdump 2.4
[debug] Proxy map: {}
[Vine] OYwITBmlDYQ: Downloading webpage
Traceback (most recent call last):
  File "/usr/bin/youtube-dl", line 6, in <module>
    youtube_dl.main()
  File "/usr/lib/python2.7/dist-packages/youtube_dl/__init__.py", line 408, in main
    _real_main(argv)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/__init__.py", line 398, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1452, in download
    res = self.extract_info(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 665, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 711, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1067, in process_video_result
    format['http_headers'] = self._calc_headers(full_format_info)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 968, in _calc_headers
    cookies = self._calc_cookies(info_dict)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 975, in _calc_cookies
    pr = compat_urllib_request.Request(info_dict['url'])
  File "/usr/lib/python2.7/urllib2.py", line 202, in __init__
    self.__original = unwrap(url)
  File "/usr/lib/python2.7/urllib.py", line 1060, in unwrap
    url = url.strip()
AttributeError: 'NoneType' object has no attribute 'strip'

**Comment by friedretinas** [comment]
I'd opened this before I'd seen that this issue had been reported & closed 6 days ago in #5240 ; am still using version 2015.03.18 & so I've closed my report of it.  I rely upon webupd8 PPA for updates and that PPA release has not yet been updated to the latest version but normally the PPA maintainer issues prompt updates.
