### ISSUE TITLE
Not properly downloading NBC videos

### ISSUE THREAD

**Issue by lvispy** [rg3/youtube-dl#5300]
When i try to download this video: https://www.nbc.com/classic-tv/miami-vice/video/no-exit/n30544?onid=193196#vc193196=2
I get ERROR: Unsupported URL

I though that NBC was supported, perhaps there's something not working well.

**Comment by yan12125** [comment]
You can try: http://www.nbc.com/classic-tv/miami-vice/video/no-exit/n30544?onid=193196#vc193196=2 (http instead of https)

**Comment by jaimeMF** [comment]
Thanks for the report, `https` urls should work in the next version. Since I the video is georestricted I would appreciate if you could verify that it works.

**Comment by lvispy** [comment]
Using it with http i still can't download it, i get the following:

Edgewater:~ lvispy$ youtube-dl http://www.nbc.com/classic-tv/miami-vice/video/no-exit/n30544?onid=193196#vc193196=2
[NBC] n30544: Downloading webpage
[ThePlatform] BfBfRAGx6UxX: Downloading config
[ThePlatform] BfBfRAGx6UxX: Downloading XML
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 408, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 398, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1446, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 662, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 715, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 651, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 275, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/theplatform.py", line 90, in _real_extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 442, in _download_xml
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: undefined entity &nbsp;: line 56, column 22

**Comment by jaimeMF** [comment]
Make sure you are using the last version and run the command with the options `--verbose --write-pages` and post the `*.dump` files in [a gist](https://gist.github.com/)

**Comment by lvispy** [comment]
It's here: https://gist.github.com/lvispy/865e43f473fbbae238d0
Sure running last version after sudo youtube-dl -U

**Comment by jaimeMF** [comment]
It's geoblocked so I can't reproduce it, I don't know why it's getting an html file. Open a new issue (to make tracking it easier)

**Comment by johny1** [comment]
Hi. I didn't know if I should make a new thread but I'm having the same issue.

Using the following link, http://stream.nbcsports.com/nascar/?pid=18390

[generic] index_nbcsn-generic: Requesting header
WARNING: Falling back on generic information extractor.
[generic] index_nbcsn-generic: Downloading webpage
[generic] index_nbcsn-generic: Extracting information
ERROR: Unsupported URL: http://stream.nbcsports.com/nbcsn/index_nbcsn-generic.ht
ml?pid=18366

Any help would be great!

**Comment by yan12125** [comment]
@johny1 Your problem is different (different URLs). Please open a new issue.
