### ISSUE TITLE
Support for Techcrunch.com

### ISSUE THREAD

**Issue by MaryCoding** [rg3/youtube-dl#5310]
Hi guys,
I was wanting to download a few videos from http://techcrunch.com/. They are a leading news website focused on information technology companies. Unfortunately, youtube-dl wasnt able to extract their videos. 
```
youtube-dl -v -o "/media/%(title)s.mp4"  http://techcrunch.com/video/facebook-creates-on-this-day-crunch-report/518726732/                                     [debug] System config: []o/facebook-creates-on-this-day-crunch-report/518726732/                                                                                                                     [debug] User config: []
[debug] Command-line args: [u'-v', u'-o', u'/media/%(title)s.mp4', u'http://techcrunch.com/video/facebook-creates-on-this-day-crunch-report/518726732/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.03.24
[debug] Python version 2.7.6 - Linux-3.13.0-35-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: ffmpeg git-2014-12-27-d4fd3f2, ffprobe git-2014-12-27-d4fd3f2
[debug] Proxy map: {}
[generic] 518726732: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 518726732: Downloading webpage
[generic] 518726732: Extracting information
ERROR: Unsupported URL: http://techcrunch.com/video/facebook-creates-on-this-day-crunch-report/518726732/
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 825, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1528, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: undefined entity: line 39, column 2
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 651, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 275, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1313, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://techcrunch.com/video/facebook-creates-on-this-day-crunch-report/518726732/
```

**Comment by naglis** [comment]
Thank you for the report. 5min embeds, which are used on techcrunch.com, should be supported in the next version of youtube-dl. Until it is released, you may download techcrunch videos using their IDs and the 5min shorthand, for example:
```bash
youtube-dl '5min:518726732'
```
