### ISSUE TITLE
National Geographic video 'unsupported'

### ISSUE THREAD

**Issue by Fironet** [rg3/youtube-dl#5312]
There's a video on this [National Geographic page](http://www.nationalgeographic.com/trajan-column/index.html) about the Trajan Column, and feeding youtube-dl the link reports the URL is unsupported, although the youtube-dl lists NG as a supported site.

[Here's a link](http://player.d.nationalgeographic.com/players/ngsvideo/share/?feed=http://feed.theplatform.com/f/ngs/dCCn2isYZ9N9&guid=0000014b-eaa8-dcb2-a96b-eebc38d50003&link=http://video.nationalgeographic.com/video/) to the video by itself. Any way to get youtube-dl to download this?

Verbose output:

    [debug] System config: []
    [debug] User config: ['-o', 'M:\\Videos\\%(title)s.%(ext)s', '--restrict-filenames', '--console-title']
    [debug] Command-line args: ['http://www.nationalgeographic.com/trajan-column/index.html', '--verbose']
    [debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
    [debug] youtube-dl version 2015.03.09
    [debug] Python version 2.7.8 - Windows-8-6.2.9200
    [debug] exe versions: ffmpeg N-66742-gf6777ce, ffprobe N-56999-g83fc6c8, rtmpdump 2.4
    [debug] Proxy map: {}
    [generic] index: Requesting header
    WARNING: Falling back on generic information extractor.
    [generic] index: Downloading webpage
    [generic] index: Extracting information
    ERROR: Unsupported URL: http://www.nationalgeographic.com/trajan-column/index.html
    Traceback (most recent call last):
      File "youtube_dl\extractor\generic.pyo", line 814, in _real_extract
      File "youtube_dl\utils.pyo", line 1521, in parse_xml
      File "xml\etree\ElementTree.pyo", line 1300, in XML
      File "xml\etree\ElementTree.pyo", line 1642, in feed
      File "xml\etree\ElementTree.pyo", line 1506, in _raiseerror
    ParseError: not well-formed (invalid token): line 1, column 27
    Traceback (most recent call last):
      File "youtube_dl\YoutubeDL.pyo", line 649, in extract_info
      File "youtube_dl\extractor\common.pyo", line 275, in extract
      File "youtube_dl\extractor\generic.pyo", line 1283, in _real_extract
    UnsupportedError: Unsupported URL: http://www.nationalgeographic.com/trajan-column/index.html

**Comment by naglis** [comment]
For the time being, you may download the video in question using [this link](http://video.nationalgeographic.com/video/magazine/150315-ngm-building-trajans-column):
```bash
youtube-dl 'http://video.nationalgeographic.com/video/magazine/150315-ngm-building-trajans-column'
```

*Note to others*:
The [article](http://www.nationalgeographic.com/trajan-column/article.html) contains an embedded ThePlatform feed, which we do not support yet.

**Comment by Fironet** [comment]
> For the time being, you may download the video in question using this link

Cheers, and thanks for the clarification.
