### ISSUE TITLE
CNET video download error

### ISSUE THREAD

**Issue by MaryCoding** [rg3/youtube-dl#5340]
Hi,  Youtube-dl has cnet as a supported site for video downloads. I tried downloading the video shown below but i get an error. 
LINK: http://www.cnet.com/videos/tesla-model-s-a-second-step-towards-a-cleaner-motoring-future/

```
youtube-dl -v -o "/media/%(title)s.mp4"   http://www.cnet.com/videos/tesla-model-s-a-second-step-towards-a-cleaner-motoring-future/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'-o', u'/media/%(title)s.mp4', u'http://www.cnet.com/videos/tesla-model-s-a-second-step-towards-a-cleaner-motoring-future/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.03.24
[debug] Python version 2.7.6 - Linux-3.13.0-35-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: ffmpeg git-2014-12-27-d4fd3f2, ffprobe git-2014-12-27-d4fd3f2
[debug] Proxy map: {}
[CNET] tesla-model-s-a-second-step-towards-a-cleaner-motoring-future: Downloading webpage
[ThePlatform] 22d_qsQ6MIRT: Downloading XML
[ThePlatform] 22d_qsQ6MIRT: Downloading webpage
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 408, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 398, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1446, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 662, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 720, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 651, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 275, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/theplatform.py", line 149, in _real_extract
AttributeError: 'NoneType' object has no attribute 'findall'
```

**Comment by LennTheVator** [comment]
`_x = lambda p: xpath_with_ns(p, {'smil': 'http://www.w3.org/2005/SMIL21/Language'})`, (theplatform.py, line 22) is a bit strange. Why is it a link to w3.org? Won't that make `ns_map[ns]` in line 169 of youtube-dl/utils.py             `replaced.append('{%s}%s' % (ns_map[ns], tag))` that link? Just some sanity checking here. I could have no idea what I'm talking about.

**Comment by yan12125** [comment]
Thanks for the report. This issue should be fixed in the next version.

By the way, @LennTheVator the w3.org link is the default XML namespace in SMIL 2.1 spec. See http://www.w3.org/TR/SMIL2/smil-basic.html#BaseGuideNS-BasicDefXML.
