### ISSUE TITLE
[lifenews] ERROR: No media links available

### ISSUE THREAD

**Issue by spvkgn** [rg3/youtube-dl#5346]
Seems like there is a bug, can you please fix it
```
~ $ youtube-dl -v http://lifenews.ru/news/152125
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://lifenews.ru/news/152125']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.03.28
[debug] Python version 2.7.3 - Linux-3.2.0-69-generic-pae-i686-with-LinuxMint-13-maya
[debug] exe versions: ffmpeg 2.4.2, ffprobe 2.4.2, rtmpdump 2.4
[debug] Proxy map: {}
[lifenews] 152125: Downloading page
ERROR: No media links available for 152125; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 651, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 275, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/lifenews.py", line 40, in _real_extract
    raise ExtractorError('No media links available for %s' % video_id)
ExtractorError: No media links available for 152125; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by yan12125** [comment]
Thanks for the report. youtube-dl will support such videos in the next version.
