### ISSUE TITLE
Crash when trying to extract audio

### ISSUE THREAD

**Issue by jftuga** [rg3/youtube-dl#5349]
I am using the Windows youtube-dl.exe 2015.04.03 from the web site.

If I run:
youtube-dl.exe --extract-audio --audio-format mp3 -k "https://www.youtube.com/watch?v=AN_iBKvR3fY"

The .mp4 is saved to the hard drive, but then I get this error:

[youtube] AN_iBKvR3fY: Downloading webpage
[youtube] AN_iBKvR3fY: Extracting video information
[youtube] AN_iBKvR3fY: Downloading DASH manifest
[download] Destination: Carol Kaye - Burning Spear-AN_iBKvR3fY.mp4
[download] 100% of 2.30MiB in 00:00
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "youtube_dl\__init__.pyo", line 408, in main
  File "youtube_dl\__init__.pyo", line 398, in _real_main
  File "youtube_dl\YoutubeDL.pyo", line 1446, in download
  File "youtube_dl\YoutubeDL.pyo", line 662, in extract_info
  File "youtube_dl\YoutubeDL.pyo", line 708, in process_ie_result
  File "youtube_dl\YoutubeDL.pyo", line 1150, in process_video_result
  File "youtube_dl\YoutubeDL.pyo", line 1429, in process_info
  File "youtube_dl\YoutubeDL.pyo", line 1487, in post_process
  File "youtube_dl\postprocessor\ffmpeg.pyo", line 208, in run
  File "youtube_dl\postprocessor\ffmpeg.pyo", line 171, in get_audio_codec
  File "youtube_dl\postprocessor\ffmpeg.pyo", line 121, in probe_executable
KeyError: None

I downloaded the youtube-dl python source and then ran:
__main__.py --extract-audio --audio-format mp3 -k "https://www.youtube.com/watch?v=AN_iBKvR3fY"

I now see this error:

[youtube] AN_iBKvR3fY: Downloading webpage
[youtube] AN_iBKvR3fY: Extracting video information
[youtube] AN_iBKvR3fY: Downloading DASH manifest
[download] Destination: Carol Kaye - Burning Spear-AN_iBKvR3fY.mp4
[download] 100% of 2.30MiB in 00:00
Traceback (most recent call last):
  File "E:\mp3\python\__main__.py", line 19, in <module>
    youtube_dl.main()
  File "E:\mp3\python\youtube_dl\__init__.py", line 408, in main
    _real_main(argv)
  File "E:\mp3\python\youtube_dl\__init__.py", line 398, in _real_main
    retcode = ydl.download(all_urls)
  File "E:\mp3\python\youtube_dl\YoutubeDL.py", line 1446, in download
    res = self.extract_info(url)
  File "E:\mp3\python\youtube_dl\YoutubeDL.py", line 662, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "E:\mp3\python\youtube_dl\YoutubeDL.py", line 708, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "E:\mp3\python\youtube_dl\YoutubeDL.py", line 1150, in process_video_result
    self.process_info(new_info)
  File "E:\mp3\python\youtube_dl\YoutubeDL.py", line 1429, in process_info
    self.post_process(filename, info_dict)
  File "E:\mp3\python\youtube_dl\YoutubeDL.py", line 1487, in post_process
    keep_video_wish, info = pp.run(info)
  File "E:\mp3\python\youtube_dl\postprocessor\ffmpeg.py", line 208, in run
    filecodec = self.get_audio_codec(path)
  File "E:\mp3\python\youtube_dl\postprocessor\ffmpeg.py", line 171, in get_audio_codec
    if not self.probe_executable:
  File "E:\mp3\python\youtube_dl\postprocessor\ffmpeg.py", line 121, in probe_executable
    return self._paths[self.probe_basename]
KeyError: None

How can I fix this?

Thanks,
-John

**Comment by jftuga** [comment]
ffmpeg was not installed.
It would be nice if the program reported this problem instead of crashing.
After I installed ffmpeg, everything worked as expected.

**Comment by jaimeMF** [comment]
Thanks for the report, the bug will be fixed in the next version and it will suggest installing the program.
