### ISSUE TITLE
Error extracting title from playlist

### ISSUE THREAD

**Issue by paolo57** [rg3/youtube-dl#5360]
paolo@paolo-laptop2013:~/Downloads/vd$ youtube-dl -cit --verbose "https://www.youtube.com/playlist?list=PLhcbKkzlKr51NwvwholqaYBtqrtZtPDaY"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-cit', '--verbose', 'https://www.youtube.com/playlist?list=PLhcbKkzlKr51NwvwholqaYBtqrtZtPDaY']
[debug] Encodings: locale 'UTF-8', fs 'UTF-8', out 'UTF-8', pref: 'UTF-8'
[debug] youtube-dl version 2014.02.17
[debug] Python version 2.7.6 - Linux-3.13.0-48-generic-i686-with-Ubuntu-14.04-trusty
[debug] Proxy map: {}
[youtube:playlist] PLhcbKkzlKr51NwvwholqaYBtqrtZtPDaY: Downloading page #1
WARNING: [youtube:playlist] PLhcbKkzlKr51NwvwholqaYBtqrtZtPDaY: Playlist page is missing OpenGraph title, falling back ...
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 1511, in _real_extract
    playlist_title = self._og_search_title(page)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 428, in _og_search_title
    return self._og_search_property('title', html, **kargs)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 416, in _og_search_property
    escaped = self._search_regex(self._og_regexes(prop), html, name, flags=re.DOTALL, **kargs)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 356, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract OpenGraph title; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 493, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 158, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 1517, in _real_extract
    r'<h1 class="pl-header-title">(.*?)</h1>', page, u'title')
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 366, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 356, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by yan12125** [comment]
The command you provide works fine for me. Please [update](https://github.com/rg3/youtube-dl#how-do-i-update-youtube-dl) to version 2015.04.03 and try again.

**Comment by paolo57** [comment]
On 04/05/2015 09:26 AM, Yen Chi Hsuan wrote:
>
> The command you provide works fine for me. Please update 
> <https://github.com/rg3/youtube-dl#how-do-i-update-youtube-dl> to 
> version 2015.04.03 and try again.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/rg3/youtube-dl/issues/5360#issuecomment-89730141>.
>
Done. Now it works fine. Thanks a lot
