### ISSUE TITLE
Problem with downloading video from youtube

### ISSUE THREAD

**Issue by gleb-chipiga** [rg3/youtube-dl#5361]
```
youtube-dl --verbose -F qEJwOuvDf7I
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'-F', u'qEJwOuvDf7I']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.04.03
[debug] Python version 2.7.8 - Linux-3.16.7-7-default-x86_64-with-SuSE-13.2-x86_64
[debug] exe versions: ffmpeg 2.6.1, ffprobe 2.6.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] qEJwOuvDf7I: Downloading webpage
[youtube] qEJwOuvDf7I: Extracting video information
ERROR: no conn, hlsvp or url_encoded_fmt_stream_map information found in video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 651, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 275, in extract
    return self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1087, in _real_extract
    raise ExtractorError('no conn, hlsvp or url_encoded_fmt_stream_map information found in video info')
ExtractorError: no conn, hlsvp or url_encoded_fmt_stream_map information found in video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

```
youtube-dl --verbose qEJwOuvDf7I
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'qEJwOuvDf7I']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.04.03
[debug] Python version 2.7.8 - Linux-3.16.7-7-default-x86_64-with-SuSE-13.2-x86_64
[debug] exe versions: ffmpeg 2.6.1, ffprobe 2.6.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] qEJwOuvDf7I: Downloading webpage
[youtube] qEJwOuvDf7I: Extracting video information
ERROR: no conn, hlsvp or url_encoded_fmt_stream_map information found in video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 651, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 275, in extract
    return self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1087, in _real_extract
    raise ExtractorError('no conn, hlsvp or url_encoded_fmt_stream_map information found in video info')
ExtractorError: no conn, hlsvp or url_encoded_fmt_stream_map information found in video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by yan12125** [comment]
Thanks for the report, the bug will be fixed in the next version.
