### ISSUE TITLE
livestream.com now unsupported?

### ISSUE THREAD

**Issue by asevcik** [rg3/youtube-dl#5375]
I was able to download the first few videos from this page and am now getting an error that livestream is unsupported. I updated after experiencing this problem and am getting the same error after the update.

Here is my output:

WKST:~ WKST$ youtube-dl http://livestream.com/bsww/concacafbeachsoccercampeonato2015 --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://livestream.com/bsww/concacafbeachsoccercampeonato2015', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.04.03
[debug] Python version 2.7.6 - Darwin-14.0.0-x86_64-i386-64bit
[debug] exe versions: avconv 10, avprobe 10, ffmpeg 2.4.3, ffprobe 2.4.3, rtmpdump 2.4
[debug] Proxy map: {}
[generic] concacafbeachsoccercampeonato2015: Requesting header
WARNING: Falling back on generic information extractor.
[generic] concacafbeachsoccercampeonato2015: Downloading webpage
[generic] concacafbeachsoccercampeonato2015: Extracting information
ERROR: Unsupported URL: http://livestream.com/bsww/concacafbeachsoccercampeonato2015
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 846, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1528, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 10, column 312
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 651, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 275, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1345, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://livestream.com/bsww/concacafbeachsoccercampeonato2015

**Comment by yan12125** [comment]
Thanks for the report. It should be fixed in the next versoin.
