### ISSUE TITLE
Crunchyroll: UnicodeDecodeError: 'ascii' codec can't decode

### ISSUE THREAD

**Issue by Slyneth** [rg3/youtube-dl#5378]
I can't work with Crunchyroll. Using Yosemite.

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'http://www.crunchyroll.com/tesagure-bukatsumono/episode-1-lets-play-with-female-type-battle-robots-and-one-frame-manga-678213', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.04.03
[debug] Python version 2.7.6 - Darwin-14.1.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.6.1, ffprobe 2.6.1, rtmpdump 2.4
[debug] Proxy map: {}
[Crunchyroll] Logging in
[Crunchyroll] 678213: Downloading webpage
[Crunchyroll] 678213: Downloading media info
[Crunchyroll] 678213: Downloading media info for 360p
[Crunchyroll] 678213: Downloading media info for 480p
[Crunchyroll] 678213: Downloading media info for 720p
[Crunchyroll] 678213: Downloading media info for 1080p
[debug] Invoking downloader on 'rtmpe://cp150757.edgefcs.net/ondemand/?auth=daEbOdxbya_dfdQbYbYandfdWbGdMaVdKc_-bvjocz-dHa-lDGxpqKDCxw&aifp=0009&slist=c17/s/ve1760623/video.mp4'
[download] Destination: Tesagure! 3 Episode 1 – Let's Play With Female-Type Battle Robots and One-Frame Manga-678213.flv
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 408, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 398, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1446, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 662, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 708, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1150, in process_video_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1379, in process_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1354, in dl
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 341, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/rtmp.py", line 166, in real_download
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 375, in _debug_cmd
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 371, in <lambda>
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 23: ordinal not in range(128)

**Comment by JamesTheAwesomeDude** [comment]
This error just started happening to me today.

**Comment by Sunako** [comment]
Same here

**Comment by Slyneth** [comment]
After last rtmpdump upgrade, it got fixed for me. rtmpdump 2.4+20150115

**Comment by yan12125** [comment]
It's indeed youtube-dl's problem, which occurs only with ```-v``` option on Python 2.x. As a temporary workaround, remove the ```-v``` option.

**Comment by dstftw** [comment]
I believe this will be fixed in the next version of youtube-dl. Thanks for the report.
