### ISSUE TITLE
add bbc archive

### ISSUE THREAD

**Issue by treakiandroid** [rg3/youtube-dl#5385]
hi,

could you add support for bbc archive? thanks

example page: http://www.bbc.co.uk/archive/whatwewore/5607.shtml
```
$ youtube-dl http://www.bbc.co.uk/archive/whatwewore/5607.shtml
[generic] 5607: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 5607: Downloading webpage
[generic] 5607: Extracting information
ERROR: Unsupported URL: http://www.bbc.co.uk/archive/whatwewore/5607.shtml
$ 
```

**Comment by TRox1972** [comment]
There is already an extractor for BBC, but it doesn't seem to support `bbc.co.uk/archive/` urls. Shouldn't be to hard to change.

**Comment by insectatorious** [comment]
Would like to add my vote fro this - just tried: 
```
$ youtube-dl -v http://www.bbc.co.uk/archive/feynman/10700.shtml
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.bbc.co.uk/archive/feynman/10700.shtml']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.08.17
[debug] Python version 2.7.6 - Linux-3.13.0-92-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 11.3-6, avprobe 11.3-6, ffmpeg N-80901-gfebc862, ffprobe N-80901-gfebc862
[debug] Proxy map: {}
[bbc] 10700.shtml: Downloading webpage
ERROR: Unable to extract playlist data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 691, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 347, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/bbc.py", line 972, in _real_extract
    webpage, 'playlist data'),
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 650, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract playlist data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

```
$ youtube-dl --version
2016.08.17
```

**Comment by James-UK** [comment]
Also gets my vote too, please; "regular" BBC iPlayer is fine, but BBC Archive pages still fail.

Regards

**Comment by kirbyj** [comment]
+1

```
me@home:~$ youtube-dl --verbose https://www.bbc.co.uk/archive/summer-fashions-in-1959/zm8q47h
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.bbc.co.uk/archive/summer-fashions-in-1959/zm8q47h']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.7.1 (CPython) - Darwin-18.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4, rtmpdump 2.4
[debug] Proxy map: {}
[bbc] zm8q47h: Downloading webpage
ERROR: Unable to extract playlist data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/bbc.py", line 1255, in _real_extract
    webpage, 'playlist data'),
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract playlist data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by dirkf** [comment]
Now 404:
* `http://www.bbc.co.uk/archive/whatwewore/5607.shtml`
* `http://www.bbc.co.uk/archive/feynman/10700.shtml`

Works:
<details><summary>https://www.bbc.co.uk/archive/summer-fashions-in-1959/zm8q47h</summary>

```console
$ python ./youtube-dl -vF 'https://www.bbc.co.uk/archive/summer-fashions-in-1959/zm8q47h'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-vF', u'https://www.bbc.co.uk/archive/summer-fashions-in-1959/zm8q47h']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2025.09.29 [82552faba] (single file build)
[debug] ** This version was built from the latest master code at https://github.com/ytdl-org/youtube-dl.
[debug] ** For support, visit the main site.
[debug] Python 2.7.15 (CPython i686 32bit) - Linux-6.1.0-40-686-pae-i686-with-debian-12.12 - OpenSSL 1.1.1a  20 Nov 2018 - glibc 2.1.3
[debug] exe versions: ffmpeg 5.1.7-0, ffprobe 5.1.7-0
[debug] Proxy map: {}
[bbc] zm8q47h: Downloading webpage
[bbc] p06xv0t7: Downloading media selection JSON
[bbc] p06xv0t7: Downloading m3u8 information
[bbc] p06xv0t7: Downloading m3u8 information
[bbc] p06xv0t7: Downloading MPD manifest
[bbc] p06xv0t7: Downloading MPD manifest
[bbc] p06xv0t7: Downloading m3u8 information
[bbc] p06xv0t7: Downloading m3u8 information
[bbc] p06xv0t7: Downloading MPD manifest
[bbc] p06xv0t7: Downloading MPD manifest
[bbc] p06xv0t7: Downloading m3u8 information
[bbc] p06xv0t7: Downloading m3u8 information
[bbc] p06xv0t7: Downloading MPD manifest
[bbc] p06xv0t7: Downloading MPD manifest
[download] Downloading playlist: BBC Archive: Summer fashions in 1959
[bbc] playlist BBC Archive: Summer fashions in 1959: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[info] Available formats for p06xv0t7:
format code                      extension  resolution note
mf_akamai-audio_eng=96000-0      m4a        audio only [en] DASH audio   96k , m4a_dash container, mp4a.40.5 (48000Hz)
mf_akamai-audio_eng=96000-1      m4a        audio only [en] DASH audio   96k , m4a_dash container, mp4a.40.5 (48000Hz)
mf_bidi-audio_eng=96000-0        m4a        audio only [en] DASH audio   96k , m4a_dash container, mp4a.40.5 (48000Hz)
mf_bidi-audio_eng=96000-1        m4a        audio only [en] DASH audio   96k , m4a_dash container, mp4a.40.5 (48000Hz)
mf_cloudfront-audio_eng=96000-0  m4a        audio only [en] DASH audio   96k , m4a_dash container, mp4a.40.5 (48000Hz)
mf_cloudfront-audio_eng=96000-1  m4a        audio only [en] DASH audio   96k , m4a_dash container, mp4a.40.5 (48000Hz)
mf_akamai-video=86000-0          mp4        192x108    DASH video   86k , mp4_dash container, avc3.42C015, 25fps, video only
mf_akamai-video=86000-1          mp4        192x108    DASH video   86k , mp4_dash container, avc3.42C015, 25fps, video only
mf_bidi-video=86000-0            mp4        192x108    DASH video   86k , mp4_dash container, avc3.42C015, 25fps, video only
mf_bidi-video=86000-1            mp4        192x108    DASH video   86k , mp4_dash container, avc3.42C015, 25fps, video only
mf_cloudfront-video=86000-0      mp4        192x108    DASH video   86k , mp4_dash container, avc3.42C015, 25fps, video only
mf_cloudfront-video=86000-1      mp4        192x108    DASH video   86k , mp4_dash container, avc3.42C015, 25fps, video only
mf_akamai-video=156000-0         mp4        256x144    DASH video  156k , mp4_dash container, avc3.42C015, 25fps, video only
mf_akamai-video=156000-1         mp4        256x144    DASH video  156k , mp4_dash container, avc3.42C015, 25fps, video only
mf_bidi-video=156000-0           mp4        256x144    DASH video  156k , mp4_dash container, avc3.42C015, 25fps, video only
mf_bidi-video=156000-1           mp4        256x144    DASH video  156k , mp4_dash container, avc3.42C015, 25fps, video only
mf_cloudfront-video=156000-0     mp4        256x144    DASH video  156k , mp4_dash container, avc3.42C015, 25fps, video only
mf_cloudfront-video=156000-1     mp4        256x144    DASH video  156k , mp4_dash container, avc3.42C015, 25fps, video only
mf_akamai-video=281000-0         mp4        384x216    DASH video  281k , mp4_dash container, avc3.42C015, 25fps, video only
mf_akamai-video=281000-1         mp4        384x216    DASH video  281k , mp4_dash container, avc3.42C015, 25fps, video only
mf_bidi-video=281000-0           mp4        384x216    DASH video  281k , mp4_dash container, avc3.42C015, 25fps, video only
mf_bidi-video=281000-1           mp4        384x216    DASH video  281k , mp4_dash container, avc3.42C015, 25fps, video only
mf_cloudfront-video=281000-0     mp4        384x216    DASH video  281k , mp4_dash container, avc3.42C015, 25fps, video only
mf_cloudfront-video=281000-1     mp4        384x216    DASH video  281k , mp4_dash container, avc3.42C015, 25fps, video only
mf_akamai-video=437000-0         mp4        512x288    DASH video  437k , mp4_dash container, avc3.4D401E, 25fps, video only
mf_akamai-video=437000-1         mp4        512x288    DASH video  437k , mp4_dash container, avc3.4D401E, 25fps, video only
mf_bidi-video=437000-0           mp4        512x288    DASH video  437k , mp4_dash container, avc3.4D401E, 25fps, video only
mf_bidi-video=437000-1           mp4        512x288    DASH video  437k , mp4_dash container, avc3.4D401E, 25fps, video only
mf_cloudfront-video=437000-0     mp4        512x288    DASH video  437k , mp4_dash container, avc3.4D401E, 25fps, video only
mf_cloudfront-video=437000-1     mp4        512x288    DASH video  437k , mp4_dash container, avc3.4D401E, 25fps, video only
mf_akamai-video=827000-0         mp4        704x396    DASH video  827k , mp4_dash container, avc3.4D401E, 25fps, video only
mf_akamai-video=827000-1         mp4        704x396    DASH video  827k , mp4_dash container, avc3.4D401E, 25fps, video only
mf_bidi-video=827000-0           mp4        704x396    DASH video  827k , mp4_dash container, avc3.4D401E, 25fps, video only
mf_bidi-video=827000-1           mp4        704x396    DASH video  827k , mp4_dash container, avc3.4D401E, 25fps, video only
mf_cloudfront-video=827000-0     mp4        704x396    DASH video  827k , mp4_dash container, avc3.4D401E, 25fps, video only
mf_cloudfront-video=827000-1     mp4        704x396    DASH video  827k , mp4_dash container, avc3.4D401E, 25fps, video only
mf_akamai-video=1604000-0        mp4        960x540    DASH video 1604k , mp4_dash container, avc3.4D401F, 25fps, video only
mf_akamai-video=1604000-1        mp4        960x540    DASH video 1604k , mp4_dash container, avc3.4D401F, 25fps, video only
mf_bidi-video=1604000-0          mp4        960x540    DASH video 1604k , mp4_dash container, avc3.4D401F, 25fps, video only
mf_bidi-video=1604000-1          mp4        960x540    DASH video 1604k , mp4_dash container, avc3.4D401F, 25fps, video only
mf_cloudfront-video=1604000-0    mp4        960x540    DASH video 1604k , mp4_dash container, avc3.4D401F, 25fps, video only
mf_cloudfront-video=1604000-1    mp4        960x540    DASH video 1604k , mp4_dash container, avc3.4D401F, 25fps, video only
mf_akamai-349-0                  mp4        384x216     349k , avc1.42C015@ 281k, 25.0fps, mp4a.40.5@ 48k
mf_akamai-349-1                  mp4        384x216     349k , avc1.42C015@ 281k, 25.0fps, mp4a.40.5@ 48k
mf_bidi-349-0                    mp4        384x216     349k , avc1.42C015@ 281k, 25.0fps, mp4a.40.5@ 48k
mf_bidi-349-1                    mp4        384x216     349k , avc1.42C015@ 281k, 25.0fps, mp4a.40.5@ 48k
mf_cloudfront-349-0              mp4        384x216     349k , avc1.42C015@ 281k, 25.0fps, mp4a.40.5@ 48k
mf_cloudfront-349-1              mp4        384x216     349k , avc1.42C015@ 281k, 25.0fps, mp4a.40.5@ 48k
mf_akamai-565-0                  mp4        512x288     565k , avc1.4D401E@ 437k, 25.0fps, mp4a.40.5@ 96k
mf_akamai-565-1                  mp4        512x288     565k , avc1.4D401E@ 437k, 25.0fps, mp4a.40.5@ 96k
mf_bidi-565-0                    mp4        512x288     565k , avc1.4D401E@ 437k, 25.0fps, mp4a.40.5@ 96k
mf_bidi-565-1                    mp4        512x288     565k , avc1.4D401E@ 437k, 25.0fps, mp4a.40.5@ 96k
mf_cloudfront-565-0              mp4        512x288     565k , avc1.4D401E@ 437k, 25.0fps, mp4a.40.5@ 96k
mf_cloudfront-565-1              mp4        512x288     565k , avc1.4D401E@ 437k, 25.0fps, mp4a.40.5@ 96k
mf_akamai-979-0                  mp4        704x396     979k , avc1.4D401E@ 827k, 25.0fps, mp4a.40.5@ 96k
mf_akamai-979-1                  mp4        704x396     979k , avc1.4D401E@ 827k, 25.0fps, mp4a.40.5@ 96k
mf_bidi-979-0                    mp4        704x396     979k , avc1.4D401E@ 827k, 25.0fps, mp4a.40.5@ 96k
mf_bidi-979-1                    mp4        704x396     979k , avc1.4D401E@ 827k, 25.0fps, mp4a.40.5@ 96k
mf_cloudfront-979-0              mp4        704x396     979k , avc1.4D401E@ 827k, 25.0fps, mp4a.40.5@ 96k
mf_cloudfront-979-1              mp4        704x396     979k , avc1.4D401E@ 827k, 25.0fps, mp4a.40.5@ 96k
mf_akamai-1802-0                 mp4        960x540    1802k , avc1.4D401F@1604k, 25.0fps, mp4a.40.5@ 96k
mf_akamai-1802-1                 mp4        960x540    1802k , avc1.4D401F@1604k, 25.0fps, mp4a.40.5@ 96k
mf_bidi-1802-0                   mp4        960x540    1802k , avc1.4D401F@1604k, 25.0fps, mp4a.40.5@ 96k
mf_bidi-1802-1                   mp4        960x540    1802k , avc1.4D401F@1604k, 25.0fps, mp4a.40.5@ 96k
mf_cloudfront-1802-0             mp4        960x540    1802k , avc1.4D401F@1604k, 25.0fps, mp4a.40.5@ 96k
mf_cloudfront-1802-1             mp4        960x540    1802k , avc1.4D401F@1604k, 25.0fps, mp4a.40.5@ 96k (best)
[download] Finished downloading playlist: BBC Archive: Summer fashions in 1959
$ 
```

</details>

**Comment by James-UK** [comment]
#Dirkf really appreciate your work on this. Regards. On 10 Oct 2025, at 00:15, dirkf ***@***.***> wrote:﻿dirkf left a comment (ytdl-org/youtube-dl#5385)
Now 404:

http://www.bbc.co.uk/archive/whatwewore/5607.shtml
http://www.bbc.co.uk/archive/feynman/10700.shtml

Works:
https://www.bbc.co.uk/archive/summer-fashions-in-1959/zm8q47h
```console
$ python ./youtube-dl -vF 'https://www.bbc.co.uk/archive/summer-fashions-in-1959/zm8q47h'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-vF', u'https://www.bbc.co.uk/archive/summer-fashions-in-1959/zm8q47h']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2025.09.29 [82552faba] (single file build)
[debug] ** This version was built from the latest master code at https://github.com/ytdl-org/youtube-dl.
[debug] ** For support, visit the main site.
[debug] Python 2.7.15 (CPython i686 32bit) - Linux-6.1.0-40-686-pae-i686-with-debian-12.12 - OpenSSL 1.1.1a  20 Nov 2018 - glibc 2.1.3
[debug] exe versions: ffmpeg 5.1.7-0, ffprobe 5.1.7-0
[debug] Proxy map: {}
[bbc] zm8q47h: Downloading webpage
[bbc] p06xv0t7: Downloading media selection JSON
[bbc] p06xv0t7: Downloading m3u8 information
[bbc] p06xv0t7: Downloading m3u8 information
[bbc] p06xv0t7: Downloading MPD manifest
[bbc] p06xv0t7: Downloading MPD manifest
[bbc] p06xv0t7: Downloading m3u8 information
[bbc] p06xv0t7: Downloading m3u8 information
[bbc] p06xv0t7: Downloading MPD manifest
[bbc] p06xv0t7: Downloading MPD manifest
[bbc] p06xv0t7: Downloading m3u8 information
[bbc] p06xv0t7: Downloading m3u8 information
[bbc] p06xv0t7: Downloading MPD manifest
[bbc] p06xv0t7: Downloading MPD manifest
[download] Downloading playlist: BBC Archive: Summer fashions in 1959
[bbc] playlist BBC Archive: Summer fashions in 1959: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[info] Available formats for p06xv0t7:
format code                      extension  resolution note
mf_akamai-audio_eng=96000-0      m4a        audio only [en] DASH audio   96k , m4a_dash container, mp4a.40.5 (48000Hz)
mf_akamai-audio_eng=96000-1      m4a        audio only [en] DASH audio   96k , m4a_dash container, mp4a.40.5 (48000Hz)
mf_bidi-audio_eng=96000-0        m4a        audio only [en] DASH audio   96k , m4a_dash container, mp4a.40.5 (48000Hz)
mf_bidi-audio_eng=96000-1        m4a        audio only [en] DASH audio   96k , m4a_dash container, mp4a.40.5 (48000Hz)
mf_cloudfront-audio_eng=96000-0  m4a        audio only [en] DASH audio   96k , m4a_dash container, mp4a.40.5 (48000Hz)
mf_cloudfront-audio_eng=96000-1  m4a        audio only [en] DASH audio   96k , m4a_dash container, mp4a.40.5 (48000Hz)
mf_akamai-video=86000-0          mp4        192x108    DASH video   86k , mp4_dash container, avc3.42C015, 25fps, video only
mf_akamai-video=86000-1          mp4        192x108    DASH video   86k , mp4_dash container, avc3.42C015, 25fps, video only
mf_bidi-video=86000-0            mp4        192x108    DASH video   86k , mp4_dash container, avc3.42C015, 25fps, video only
mf_bidi-video=86000-1            mp4        192x108    DASH video   86k , mp4_dash container, avc3.42C015, 25fps, video only
mf_cloudfront-video=86000-0      mp4        192x108    DASH video   86k , mp4_dash container, avc3.42C015, 25fps, video only
mf_cloudfront-video=86000-1      mp4        192x108    DASH video   86k , mp4_dash container, avc3.42C015, 25fps, video only
mf_akamai-video=156000-0         mp4        256x144    DASH video  156k , mp4_dash container, avc3.42C015, 25fps, video only
mf_akamai-video=156000-1         mp4        256x144    DASH video  156k , mp4_dash container, avc3.42C015, 25fps, video only
mf_bidi-video=156000-0           mp4        256x144    DASH video  156k , mp4_dash container, avc3.42C015, 25fps, video only
mf_bidi-video=156000-1           mp4        256x144    DASH video  156k , mp4_dash container, avc3.42C015, 25fps, video only
mf_cloudfront-video=156000-0     mp4        256x144    DASH video  156k , mp4_dash container, avc3.42C015, 25fps, video only
mf_cloudfront-video=156000-1     mp4        256x144    DASH video  156k , mp4_dash container, avc3.42C015, 25fps, video only
mf_akamai-video=281000-0         mp4        384x216    DASH video  281k , mp4_dash container, avc3.42C015, 25fps, video only
mf_akamai-video=281000-1         mp4        384x216    DASH video  281k , mp4_dash container, avc3.42C015, 25fps, video only
mf_bidi-video=281000-0           mp4        384x216    DASH video  281k , mp4_dash container, avc3.42C015, 25fps, video only
mf_bidi-video=281000-1           mp4        384x216    DASH video  281k , mp4_dash container, avc3.42C015, 25fps, video only
mf_cloudfront-video=281000-0     mp4        384x216    DASH video  281k , mp4_dash container, avc3.42C015, 25fps, video only
mf_cloudfront-video=281000-1     mp4        384x216    DASH video  281k , mp4_dash container, avc3.42C015, 25fps, video only
mf_akamai-video=437000-0         mp4        512x288    DASH video  437k , mp4_dash container, avc3.4D401E, 25fps, video only
mf_akamai-video=437000-1         mp4        512x288    DASH video  437k , mp4_dash container, avc3.4D401E, 25fps, video only
mf_bidi-video=437000-0           mp4        512x288    DASH video  437k , mp4_dash container, avc3.4D401E, 25fps, video only
mf_bidi-video=437000-1           mp4        512x288    DASH video  437k , mp4_dash container, avc3.4D401E, 25fps, video only
mf_cloudfront-video=437000-0     mp4        512x288    DASH video  437k , mp4_dash container, avc3.4D401E, 25fps, video only
mf_cloudfront-video=437000-1     mp4        512x288    DASH video  437k , mp4_dash container, avc3.4D401E, 25fps, video only
mf_akamai-video=827000-0         mp4        704x396    DASH video  827k , mp4_dash container, avc3.4D401E, 25fps, video only
mf_akamai-video=827000-1         mp4        704x396    DASH video  827k , mp4_dash container, avc3.4D401E, 25fps, video only
mf_bidi-video=827000-0           mp4        704x396    DASH video  827k , mp4_dash container, avc3.4D401E, 25fps, video only
mf_bidi-video=827000-1           mp4        704x396    DASH video  827k , mp4_dash container, avc3.4D401E, 25fps, video only
mf_cloudfront-video=827000-0     mp4        704x396    DASH video  827k , mp4_dash container, avc3.4D401E, 25fps, video only
mf_cloudfront-video=827000-1     mp4        704x396    DASH video  827k , mp4_dash container, avc3.4D401E, 25fps, video only
mf_akamai-video=1604000-0        mp4        960x540    DASH video 1604k , mp4_dash container, avc3.4D401F, 25fps, video only
mf_akamai-video=1604000-1        mp4        960x540    DASH video 1604k , mp4_dash container, avc3.4D401F, 25fps, video only
mf_bidi-video=1604000-0          mp4        960x540    DASH video 1604k , mp4_dash container, avc3.4D401F, 25fps, video only
mf_bidi-video=1604000-1          mp4        960x540    DASH video 1604k , mp4_dash container, avc3.4D401F, 25fps, video only
mf_cloudfront-video=1604000-0    mp4        960x540    DASH video 1604k , mp4_dash container, avc3.4D401F, 25fps, video only
mf_cloudfront-video=1604000-1    mp4        960x540    DASH video 1604k , mp4_dash container, avc3.4D401F, 25fps, video only
mf_akamai-349-0                  mp4        384x216     349k , avc1.42C015@ 281k, 25.0fps, mp4a.40.5@ 48k
mf_akamai-349-1                  mp4        384x216     349k , avc1.42C015@ 281k, 25.0fps, mp4a.40.5@ 48k
mf_bidi-349-0                    mp4        384x216     349k , avc1.42C015@ 281k, 25.0fps, mp4a.40.5@ 48k
mf_bidi-349-1                    mp4        384x216     349k , avc1.42C015@ 281k, 25.0fps, mp4a.40.5@ 48k
mf_cloudfront-349-0              mp4        384x216     349k , avc1.42C015@ 281k, 25.0fps, mp4a.40.5@ 48k
mf_cloudfront-349-1              mp4        384x216     349k , avc1.42C015@ 281k, 25.0fps, mp4a.40.5@ 48k
mf_akamai-565-0                  mp4        512x288     565k , avc1.4D401E@ 437k, 25.0fps, mp4a.40.5@ 96k
mf_akamai-565-1                  mp4        512x288     565k , avc1.4D401E@ 437k, 25.0fps, mp4a.40.5@ 96k
mf_bidi-565-0                    mp4        512x288     565k , avc1.4D401E@ 437k, 25.0fps, mp4a.40.5@ 96k
mf_bidi-565-1                    mp4        512x288     565k , avc1.4D401E@ 437k, 25.0fps, mp4a.40.5@ 96k
mf_cloudfront-565-0              mp4        512x288     565k , avc1.4D401E@ 437k, 25.0fps, mp4a.40.5@ 96k
mf_cloudfront-565-1              mp4        512x288     565k , avc1.4D401E@ 437k, 25.0fps, mp4a.40.5@ 96k
mf_akamai-979-0                  mp4        704x396     979k , avc1.4D401E@ 827k, 25.0fps, mp4a.40.5@ 96k
mf_akamai-979-1                  mp4        704x396     979k , avc1.4D401E@ 827k, 25.0fps, mp4a.40.5@ 96k
mf_bidi-979-0                    mp4        704x396     979k , avc1.4D401E@ 827k, 25.0fps, mp4a.40.5@ 96k
mf_bidi-979-1                    mp4        704x396     979k , avc1.4D401E@ 827k, 25.0fps, mp4a.40.5@ 96k
mf_cloudfront-979-0              mp4        704x396     979k , avc1.4D401E@ 827k, 25.0fps, mp4a.40.5@ 96k
mf_cloudfront-979-1              mp4        704x396     979k , avc1.4D401E@ 827k, 25.0fps, mp4a.40.5@ 96k
mf_akamai-1802-0                 mp4        960x540    1802k , ***@***.***, 25.0fps, mp4a.40.5@ 96k
mf_akamai-1802-1                 mp4        960x540    1802k , ***@***.***, 25.0fps, mp4a.40.5@ 96k
mf_bidi-1802-0                   mp4        960x540    1802k , ***@***.***, 25.0fps, mp4a.40.5@ 96k
mf_bidi-1802-1                   mp4        960x540    1802k , ***@***.***, 25.0fps, mp4a.40.5@ 96k
mf_cloudfront-1802-0             mp4        960x540    1802k , ***@***.***, 25.0fps, mp4a.40.5@ 96k
mf_cloudfront-1802-1             mp4        960x540    1802k , ***@***.***, 25.0fps, mp4a.40.5@ 96k (best)
[download] Finished downloading playlist: BBC Archive: Summer fashions in 1959
$ 
```

**Comment by Vangelis66** [comment]
> Works:
[bbc.co.uk/archive/summer-fashions-in-1959/zm8q47h](https://www.bbc.co.uk/archive/summer-fashions-in-1959/zm8q47h)

... FWIW, the **URL above**, when fed to a _web browser_, **instantly redirects** now to 

https://www.bbc.co.uk/videos/c9elrkx258xo

no longer an `*/archive/*` URL per se 😉 ; that URL works, too, with latest `yt-dl`: 

<details>
<summary>yt-dl -F "https://www.bbc.co.uk/videos/c9elrkx258xo"</summary>

```console
[bbc] c9elrkx258xo: Downloading webpage
[bbc] p06xv0t7: Downloading media selection JSON
[bbc] p06xv0t7: Downloading m3u8 information
[bbc] p06xv0t7: Downloading m3u8 information
[bbc] p06xv0t7: Downloading m3u8 information
[bbc] p06xv0t7: Downloading m3u8 information
[bbc] p06xv0t7: Downloading MPD manifest
[bbc] p06xv0t7: Downloading MPD manifest
[bbc] p06xv0t7: Downloading MPD manifest
[bbc] p06xv0t7: Downloading MPD manifest
[download] Downloading playlist: BBC Archive: Summer fashions in 1959
[bbc] playlist BBC Archive: Summer fashions in 1959: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[info] Available formats for p06xv0t7:
format code                      extension  resolution note
mf_akamai-audio_eng=96000-0      m4a        audio only [en] DASH audio   96k , m4a_dash container, mp4a.40.5 (48000Hz)
mf_akamai-audio_eng=96000-1      m4a        audio only [en] DASH audio   96k , m4a_dash container, mp4a.40.5 (48000Hz)
mf_cloudfront-audio_eng=96000-0  m4a        audio only [en] DASH audio   96k , m4a_dash container, mp4a.40.5 (48000Hz)
mf_cloudfront-audio_eng=96000-1  m4a        audio only [en] DASH audio   96k , m4a_dash container, mp4a.40.5 (48000Hz)
mf_akamai-video=86000-0          mp4        192x108    DASH video   86k , mp4_dash container, avc3.42C015, 25fps, video only
mf_akamai-video=86000-1          mp4        192x108    DASH video   86k , mp4_dash container, avc3.42C015, 25fps, video only
mf_cloudfront-video=86000-0      mp4        192x108    DASH video   86k , mp4_dash container, avc3.42C015, 25fps, video only
mf_cloudfront-video=86000-1      mp4        192x108    DASH video   86k , mp4_dash container, avc3.42C015, 25fps, video only
mf_akamai-video=156000-0         mp4        256x144    DASH video  156k , mp4_dash container, avc3.42C015, 25fps, video only
mf_akamai-video=156000-1         mp4        256x144    DASH video  156k , mp4_dash container, avc3.42C015, 25fps, video only
mf_cloudfront-video=156000-0     mp4        256x144    DASH video  156k , mp4_dash container, avc3.42C015, 25fps, video only
mf_cloudfront-video=156000-1     mp4        256x144    DASH video  156k , mp4_dash container, avc3.42C015, 25fps, video only
mf_akamai-video=281000-0         mp4        384x216    DASH video  281k , mp4_dash container, avc3.42C015, 25fps, video only
mf_akamai-video=281000-1         mp4        384x216    DASH video  281k , mp4_dash container, avc3.42C015, 25fps, video only
mf_cloudfront-video=281000-0     mp4        384x216    DASH video  281k , mp4_dash container, avc3.42C015, 25fps, video only
mf_cloudfront-video=281000-1     mp4        384x216    DASH video  281k , mp4_dash container, avc3.42C015, 25fps, video only
mf_akamai-video=437000-0         mp4        512x288    DASH video  437k , mp4_dash container, avc3.4D401E, 25fps, video only
mf_akamai-video=437000-1         mp4        512x288    DASH video  437k , mp4_dash container, avc3.4D401E, 25fps, video only
mf_cloudfront-video=437000-0     mp4        512x288    DASH video  437k , mp4_dash container, avc3.4D401E, 25fps, video only
mf_cloudfront-video=437000-1     mp4        512x288    DASH video  437k , mp4_dash container, avc3.4D401E, 25fps, video only
mf_akamai-video=827000-0         mp4        704x396    DASH video  827k , mp4_dash container, avc3.4D401E, 25fps, video only
mf_akamai-video=827000-1         mp4        704x396    DASH video  827k , mp4_dash container, avc3.4D401E, 25fps, video only
mf_cloudfront-video=827000-0     mp4        704x396    DASH video  827k , mp4_dash container, avc3.4D401E, 25fps, video only
mf_cloudfront-video=827000-1     mp4        704x396    DASH video  827k , mp4_dash container, avc3.4D401E, 25fps, video only
mf_akamai-video=1604000-0        mp4        960x540    DASH video 1604k , mp4_dash container, avc3.4D401F, 25fps, video only
mf_akamai-video=1604000-1        mp4        960x540    DASH video 1604k , mp4_dash container, avc3.4D401F, 25fps, video only
mf_cloudfront-video=1604000-0    mp4        960x540    DASH video 1604k , mp4_dash container, avc3.4D401F, 25fps, video only
mf_cloudfront-video=1604000-1    mp4        960x540    DASH video 1604k , mp4_dash container, avc3.4D401F, 25fps, video only
mf_akamai-349-0                  mp4        384x216     349k , avc1.42C015@ 281k, 25.0fps, mp4a.40.5@ 48k
mf_akamai-349-1                  mp4        384x216     349k , avc1.42C015@ 281k, 25.0fps, mp4a.40.5@ 48k
mf_cloudfront-349-0              mp4        384x216     349k , avc1.42C015@ 281k, 25.0fps, mp4a.40.5@ 48k
mf_cloudfront-349-1              mp4        384x216     349k , avc1.42C015@ 281k, 25.0fps, mp4a.40.5@ 48k
mf_akamai-565-0                  mp4        512x288     565k , avc1.4D401E@ 437k, 25.0fps, mp4a.40.5@ 96k
mf_akamai-565-1                  mp4        512x288     565k , avc1.4D401E@ 437k, 25.0fps, mp4a.40.5@ 96k
mf_cloudfront-565-0              mp4        512x288     565k , avc1.4D401E@ 437k, 25.0fps, mp4a.40.5@ 96k
mf_cloudfront-565-1              mp4        512x288     565k , avc1.4D401E@ 437k, 25.0fps, mp4a.40.5@ 96k
mf_akamai-979-0                  mp4        704x396     979k , avc1.4D401E@ 827k, 25.0fps, mp4a.40.5@ 96k
mf_akamai-979-1                  mp4        704x396     979k , avc1.4D401E@ 827k, 25.0fps, mp4a.40.5@ 96k
mf_cloudfront-979-0              mp4        704x396     979k , avc1.4D401E@ 827k, 25.0fps, mp4a.40.5@ 96k
mf_cloudfront-979-1              mp4        704x396     979k , avc1.4D401E@ 827k, 25.0fps, mp4a.40.5@ 96k
mf_akamai-1802-0                 mp4        960x540    1802k , avc1.4D401F@1604k, 25.0fps, mp4a.40.5@ 96k
mf_akamai-1802-1                 mp4        960x540    1802k , avc1.4D401F@1604k, 25.0fps, mp4a.40.5@ 96k
mf_cloudfront-1802-0             mp4        960x540    1802k , avc1.4D401F@1604k, 25.0fps, mp4a.40.5@ 96k
mf_cloudfront-1802-1             mp4        960x540    1802k , avc1.4D401F@1604k, 25.0fps, mp4a.40.5@ 96k (best)
[download] Finished downloading playlist: BBC Archive: Summer fashions in 1959
```

</details>
