### ISSUE TITLE
Rai downloader fails

### ISSUE THREAD

**Issue by agatti** [rg3/youtube-dl#5396]
As per error instructions, here's the verbose log using the latest version of youtube-dl:

<pre>
❯❯❯ youtube-dl --verbose http://www.ilcandidato.rai.it/dl/ray/media/Il-Candidato---Primo-episodio-Le-Primarie-28e5525a-b495-45e8-a7c3-bc48ba45d2b6.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.ilcandidato.rai.it/dl/ray/media/Il-Candidato---Primo-episodio-Le-Primarie-28e5525a-b495-45e8-a7c3-bc48ba45d2b6.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.04.09
[debug] Python version 2.7.9 - Darwin-14.3.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.6.1, ffprobe 2.6.1, rtmpdump 2.4
[debug] Proxy map: {}
[Rai] 28e5525a-b495-45e8-a7c3-bc48ba45d2b6: Downloading video JSON
ERROR: 28e5525a-b495-45e8-a7c3-bc48ba45d2b6: Failed to parse JSON  (caused by ValueError('No JSON object could be decoded',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 460, in _parse_json
    return json.loads(json_string)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 651, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 275, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/rai.py", line 71, in _real_extract
    media = self._download_json('%s?json' % mobj.group('url'), video_id, 'Downloading video JSON')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 454, in _download_json
    json_string, video_id, transform_source=transform_source, fatal=fatal)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 464, in _parse_json
    raise ExtractorError(errmsg, cause=ve)
ExtractorError: 28e5525a-b495-45e8-a7c3-bc48ba45d2b6: Failed to parse JSON  (caused by ValueError('No JSON object could be decoded',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
</pre>

**Comment by dstftw** [comment]
Will be fixed in the next version. Thanks for the report.
