### ISSUE TITLE
Issue with AtomicParsley and Thumnnail Embed

### ISSUE THREAD

**Issue by Shamus03** [rg3/youtube-dl#5419]
I'm getting this error when running `youtube-dl --format=worst --embed-thumbnail URL`:

```
[atomicparsley] Adding thumbnail to "Video.3gp"
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/runpy.py", line 122, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/runpy.py", line 34, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 404, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 394, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1451, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 662, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 708, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1155, in process_video_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1434, in process_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1492, in post_process
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/atomicparsley.py", line 55, in run
OSError: [Errno 2] No such file or directory
```

I ran `brew install AtomicParsley` and it works fine alone, but it looks like a file that doesn't exist is trying to be referenced.  Any help on fixing this error?

**Comment by Shamus03** [comment]
Is `--embed-audio` supposed to convert videos to only audio?  Because now when I use it I only end up with an audio file.  Is that intended?  I figured it was supposed to embed the thumbnail into the video file without changing the contents.

**Comment by jaimeMF** [comment]
It won't fail in the next version, but the AtomicParsley can't embed the thumbnail in 3gp files, you may want to run `youtube-dl test:youtube -f worst[ext=mp4] --embed-thumbnail` instead.

For future reports, please [post the full output you get with the --verbose option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs), it gives us important information.

> Is --embed-audio supposed to convert videos to only audio?

Yes, as the help says: `Embed thumbnail in the audio as cover art`. If you want to make it also work for video, please open a new issue.
