### ISSUE TITLE
[walla] extractor is not used for "nick.walla.co.il"

### ISSUE THREAD

**Issue by duduke** [rg3/youtube-dl#5444]
Trying to download "The Legend of Korra" from "http://nick.walla.co.il/" fails (running verbosely):
 
youtube-dl -v http://nick.walla.co.il/?w=//2578863
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://nick.walla.co.il/?w=//2578863']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.04.09
[debug] Python version 2.7.9 - Linux-3.16.0-4-686-pae-i686-with-debian-8.0
[debug] exe versions: avconv 2.6.2, avprobe 2.6.2, ffmpeg 2.6.2, ffprobe 2.6.2, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 2578863: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 2578863: Downloading webpage
[generic] 2578863: Extracting information
ERROR: Unsupported URL: http://nick.walla.co.il/?w=//2578863
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 858, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/utils.py", line 1531, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: syntax error: line 1, column 62
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 651, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 275, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 1364, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://nick.walla.co.il/?w=//2578863

**Comment by nyh** [comment]
I'm seeing the same issue (I tried http://nick.walla.co.il/?w=//2772660). I'm assuming that nick.walla.co.il and vod.walla.co.il use the same software (it definitely looks similar), so much of the walla.py code should be relevant, but I am not familiar enough with what walla.py is doing to be able to fix it.

**Comment by nyh** [comment]
Oh, and even for vod.walla.co.il, something isn't really working: I tried
youtube-dl http://vod.walla.co.il/episode/2597978/inspector-gadget/episode-10
and get an error:

```
...
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/walla.py", line 75, in _real_extract
    self._sort_formats(formats)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 710, in _sort_formats
    raise ExtractorError('No video formats found')
```
