### ISSUE TITLE
DailyMotion download error

### ISSUE THREAD

**Issue by neutrongenious** [rg3/youtube-dl#5460]
Error:
youtube-dl http://www.dailymotion.com/video/x2mdu9j_end-of-time-the-lost-chapters-11th-april-2015_news
[dailymotion] x2mdu9j: Downloading webpage
[dailymotion] x2mdu9j: Extracting information
[dailymotion] x2mdu9j: Downloading embed page
Traceback (most recent call last):
  File "/usr/bin/youtube-dl", line 6, in <module>
    youtube_dl.main()
  File "/usr/lib/python2.7/dist-packages/youtube_dl/__init__.py", line 804, in main
    _real_main(argv)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/__init__.py", line 794, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 982, in download
    self.extract_info(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 493, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 158, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/dailymotion.py", line 154, in _real_extract
    'uploader': info['owner_screenname'],
KeyError: 'owner_screenname'

**Comment by yan12125** [comment]
Dailymotion.com is fixed in version 2015.04.17 Please [update it](https://github.com/rg3/youtube-dl#how-do-i-update-youtube-dl).
