### ISSUE TITLE
Error on culturebox.francetvinfo.fr

### ISSUE THREAD

**Issue by erwdavid** [rg3/youtube-dl#5463]
Hello, 

I got the error (see verbose output at the end) when trying to download from culturebox. It used to work the site may have changed its settings

youtube-dl --verbose http://culturebox.francetvinfo.fr/musique/musique-classique/live-piccolo-saxo-et-compagnie-par-lorchestre-national-de-lille-217121
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://culturebox.francetvinfo.fr/musique/musique-classique/live-piccolo-saxo-et-compagnie-par-lorchestre-national-de-lille-217121']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.04.17
[debug] Python version 2.7.9 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.0
[debug] exe versions: avconv 2.6.2, avprobe 2.6.2, ffmpeg 2.6.2, ffprobe 2.6.2, rtmpdump 2.4
[debug] Proxy map: {}
[culturebox.francetvinfo.fr] musique/musique-classique/live-piccolo-saxo-et-compagnie-par-lorchestre-national-de-lille-217121: Downloading webpage
ERROR: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 651, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 275, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/francetv.py", line 286, in _real_extract
    r'"http://videos\.francetv\.fr/video/([^@]+@[^"]+)"', webpage, 'video id').split('@')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 557, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by remitamine** [comment]
the video in the page is an embed from youtube: https://www.youtube.com/embed/5aB5JDBNOSc.

**Comment by dirkf** [comment]
Mini-site and URL are both dead.
