### ISSUE TITLE
use openPli enigma2

### ISSUE THREAD

**Issue by Dima73** [rg3/youtube-dl#5481]
result = ytdl.extract_info(watch_url, download=False)
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 651, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 275, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 841, in _real_extract
    video_webpage = self._download_webpage(url, video_id)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 426, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 333, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 307, in _request_webpage
    self.report_download_webpage(video_id)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 491, in report_download_webpage
    self.to_screen('%s: Downloading webpage' % video_id)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 483, in to_screen
    self._downloader.to_screen('[%s] %s' % (self.IE_NAME, msg))
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 412, in to_screen
 Titel--> Guns N' Roses   Don't Cry Legendado
Titel--> Guns N' Roses - November Rain [HD]
Titel--> Кино, Спокойная ночь (В.Цой)
Titel--> Кино (Виктор Цой)  - "Спокойная ночь"
Titel--> Кино (В.Цой),Невеселая песня
Titel--> Daily KHL Update - September 21st, 2013
action ->  WizardActions down
self.currList im KeyDown feedlist
7
0
action ->  WizardActions up
self.currList im KeyUp feedlist
action ->  WizardActions ok
self.currList im KeyOK feedlist
(<Plugins.Extensions.MyTube.MyTubeService.MyTubeFeedEntry instance at 0x2c6c9b8>, '\xd0\x9b\xd0\xb8\xd0\xb5\xd0\xbf\xd0\xb0\xd1\x8f \xd0\xb2 \xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe  (\xd1\x87\xd0\xb0\xd1\x81\xd1\x82\xd1\x8c 1).', '\xd1\x84\xd0\xb8\xd0\xbb\xd1\x8c\xd0\xbc\xd1\x8b \xd1\x81\xd0\xbd\xd0\xb8\xd0\xbc\xd0\xb0\xd0\xbb\xd0\xb8 \xd0\xb2 \xd0\x9b\xd0\xb8\xd0\xb5\xd0\xbf\xd0\xb0\xd0\xb5,\xd0\x9b\xd0\xb8\xd0\xb5\xd0\xbf\xd0\xb0\xd0\xb9\xd1\x81\xd0\xba\xd0\xbe\xd0\xbc \xd1\x80\xd0\xb0\xd0\xb9\xd0\xbe\xd0\xbd\xd0\xb5 \xd0\xb8 \xd0\xb5\xd1\x89\xd0\xb5 \xd0\xb3\xd0\xb4\xd0\xb5-\xd1\x82\xd0\xbe \n.........\xd0\xb3\xd0\xbe\xd1\x80\xd0\xbe\xd0\xb4 \xd0\xbf\xd0\xbe\xd0\xb4 \xd0\xbb\xd0\xb8\xd0\xbf\xd0\xb0\xd0\xbc\xd0\xb8 1971.......\xd0\x90\xd1\x80\xd0\xbc\xd0\xb8\xd1\x8f \xd1\x82\xd1\x80\xd1\x8f\xd1\x81\xd0\xbe\xd0\xb3\xd1\x83\xd0\xb7\xd0\xba\xd0\xb8 1964', 'iotR14vtX0E', <enigma.gPixmapPtr; proxy of <Swig Object of type 'ePtr< gPixmap > *' at 0x2c80bd8> >, '\xd0\x94\xd0\xbe\xd0\xb1\xd0\xb0\xd0\xb2\xd0\xbb\xd0\xb5\xd0\xbd\xd0\xbe: 2011-11-20', '\xd0\x9f\xd1\x80\xd0\xbe\xd1\x81\xd0\xbc\xd0\xbe\xd1\x82\xd1\x80: 1372', '\xd0\x94\xd0\xbb\xd0\xb8\xd1\x82\xd0\xb5\xd0\xbb\xd1\x8c\xd0\xbd\xd0\xbe\xd1\x81\xd1\x82\xd1\x8c: 10:44', '\xd0\x9e\xd1\x86\xd0\xb5\xd0\xbd\xd0\xba\xd0\xb8: 12')
[youtube] iotR14vtX0E: Downloading webpage
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Components/ActionMap.py", line 46, in action
  File "/usr/lib/enigma2/python/Plugins/Extensions/MyTube/plugin.py", line 776, in keyOK
    myurl = myentry.getVideoUrl()
  File "/usr/lib/enigma2/python/Plugins/Extensions/MyTube/MyTubeService.py", line 254, in getVideoUrl
    result = ytdl.extract_info(watch_url, download=False)
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 651, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 275, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 841, in _real_extract
    video_webpage = self._download_webpage(url, video_id)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 426, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 333, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 307, in _request_webpage
    self.report_download_webpage(video_id)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 491, in report_download_webpage
    self.to_screen('%s: Downloading webpage' % video_id)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 483, in to_screen
    self._downloader.to_screen('[%s] %s' % (self.IE_NAME, msg))
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 412, in to_screen
    return self.to_stdout(message, skip_eol, check_quiet=True)
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 426, in to_stdout
    self._write_string(output, self._screen_file)
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 415, in _write_string
    write_string(s, out=out, encoding=self.params.get('encoding'))
  File "/usr/lib/python2.7/site-packages/youtube_dl/utils.py", line 977, in write_string
    out.flush()
TypeError: flush() takes no arguments (1 given)
<  1828.660939> (PyObject_CallObject(<bound method ActionMap.action of <Components.ActionMap.ActionMap instance at 0x2d18e40>>,('WizardActions', 'ok')) failed)

**Comment by Dima73** [comment]
solved...
problem only openPli enigma2.
