### ISSUE TITLE
ExtractorError: no conn, hlsvp or url_encoded_fmt_stream_map information found

### ISSUE THREAD

**Issue by magnars** [rg3/youtube-dl#5488]
```
> sudo youtube-dl -U
youtube-dl is up-to-date (2015.04.17)

>  youtube-dl --verbose --no-playlist https://www.youtube.com/watch\?v\=NvF-GZI20L4\&index\=9\&list\=PLZdCLR02grLrKAOj8FJ1GGmNM5l7Okz0a
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'--no-playlist', u'https://www.youtube.com/watch?v=NvF-GZI20L4&index=9&list=PLZdCLR02grLrKAOj8FJ1GGmNM5l7Okz0a']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.04.17
[debug] Python version 2.7.6 - Darwin-13.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.2.2, ffprobe 2.2.2
[debug] Proxy map: {}
[youtube:playlist] Downloading just video NvF-GZI20L4 because of --no-playlist
[youtube] NvF-GZI20L4: Downloading webpage
[youtube] NvF-GZI20L4: Downloading video info webpage
[youtube] NvF-GZI20L4: Extracting video information
ERROR: no conn, hlsvp or url_encoded_fmt_stream_map information found in video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 876, in _real_extract
    raise ValueError('Could not find ytplayer.config')  # caught below
ValueError: Could not find ytplayer.config
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 651, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 275, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1111, in _real_extract
    raise ExtractorError('no conn, hlsvp or url_encoded_fmt_stream_map information found in video info')
ExtractorError: no conn, hlsvp or url_encoded_fmt_stream_map information found in video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by magnars** [comment]
I was able to download the video now, so this must have been a youtube hiccup.
