### ISSUE TITLE
no conn, hlsvp or url_encoded_fmt_stream_map information found in video info

### ISSUE THREAD

**Issue by doublex** [rg3/youtube-dl#5493]
````
youtube-dl --verbose 'http://www.youtube.com/watch?v=a6aXv9oDHc8'
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.youtube.com/watch?v=a6aXv9oDHc8']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.04.17
[debug] Python version 2.7.6 - Linux-3.13.0-49-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: ffmpeg 2.5.2, ffprobe 2.5.2
[debug] Proxy map: {}
[youtube] a6aXv9oDHc8: Downloading webpage
[youtube] a6aXv9oDHc8: Downloading video info webpage
[youtube] a6aXv9oDHc8: Extracting video information
ERROR: no conn, hlsvp or url_encoded_fmt_stream_map information found in video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/extractor/youtube.py", line 883, in _real_extract
    raise ValueError('No stream_map present')  # caught below
ValueError: No stream_map present
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 651, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 275, in extract
    return self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/youtube.py", line 1111, in _real_extract
    raise ExtractorError('no conn, hlsvp or url_encoded_fmt_stream_map information found in video info')
ExtractorError: no conn, hlsvp or url_encoded_fmt_stream_map information found in video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
````

**Comment by dstftw** [comment]
This broadcast is not yet started.
