### ISSUE TITLE
Daily Show still not working, even after latest patch

### ISSUE THREAD

**Issue by steveriley** [rg3/youtube-dl#5497]
Saw the bug report in #5449. Unfortunately, I'm still seeing one of the errors shown there:

```
steve@t520:~$ youtube-dl --verbose http://thedailyshow.cc.com/full-episodes/uwco7b/april-13--2015---adam-horovitz
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://thedailyshow.cc.com/full-episodes/uwco7b/april-13--2015---adam-horovitz']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.04.17
[debug] Python version 2.7.8 - Linux-4.0.0-040000-generic-x86_64-with-Ubuntu-14.10-utopic
[debug] exe versions: avconv 11-6, avprobe 11-6
[debug] Proxy map: {}
[ComedyCentralShows] april-13--2015---adam-horovitz: Downloading webpage
[ComedyCentralShows] april-13--2015---adam-horovitz: Downloading show index
[ComedyCentralShows] april-13--2015---adam-horovitz: Downloading configuration for segment 1 / 4
[ComedyCentralShows] april-13--2015---adam-horovitz: Downloading configuration for segment 2 / 4
[ComedyCentralShows] april-13--2015---adam-horovitz: Downloading configuration for segment 3 / 4
[ComedyCentralShows] april-13--2015---adam-horovitz: Downloading configuration for segment 4 / 4
[download] Downloading playlist: thedailyshow April 13, 2015 - Adam Horovitz
[ComedyCentralShows] playlist thedailyshow April 13, 2015 - Adam Horovitz: Collected 4 video ids (downloading 4 of them)
[download] Downloading video 1 of 4
ERROR: No video formats found!; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 662, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 821, in process_ie_result
    extra_info=extra)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 708, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1047, in process_video_result
    raise ExtractorError('No video formats found!')
ExtractorError: No video formats found!; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
Version:
```
steve@t520:~$ youtube-dl --version
2015.04.17
```

**Comment by falkTX** [comment]
I manually applied the patch and it works for me:
```
$ youtube-dl --verbose http://thedailyshow.cc.com/full-episodes/uwco7b/april-13--2015---adam-horovitz
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://thedailyshow.cc.com/full-episodes/uwco7b/april-13--2015---adam-horovitz']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.04.17
[debug] Python version 2.7.9 - Linux-3.19-5.dmz.1-liquorix-amd64-x86_64-with-debian-8.0
[debug] exe versions: avconv 11.3-6, avprobe 11.3-6, rtmpdump 2.4
[debug] Proxy map: {}
[ComedyCentralShows] april-13--2015---adam-horovitz: Downloading webpage
[ComedyCentralShows] april-13--2015---adam-horovitz: Downloading show index
[ComedyCentralShows] april-13--2015---adam-horovitz: Downloading configuration for segment 1 / 4
[ComedyCentralShows] april-13--2015---adam-horovitz: Downloading configuration for segment 2 / 4
[ComedyCentralShows] april-13--2015---adam-horovitz: Downloading configuration for segment 3 / 4
[ComedyCentralShows] april-13--2015---adam-horovitz: Downloading configuration for segment 4 / 4
[download] Downloading playlist: thedailyshow April 13, 2015 - Adam Horovitz
[ComedyCentralShows] playlist thedailyshow April 13, 2015 - Adam Horovitz: Collected 4 video ids (downloading 4 of them)
[download] Downloading video 1 of 4
[debug] Invoking downloader on u'http://viacommtvstrmfs.fplive.net/gsp.comedystor/com/dailyshow/TDS/season_20/episode_088/ds_20_088_act1_ca22f8bac3_1280x720_3500_h32.mp4'
[download] Destination: thedailyshow april-13--2015---adam-horovitz part 1-5d3a1314-35d8-4010-8c6d-dfae4287164f.mp4
[download]   7.4% of 236.55MiB at  3.10MiB/s ETA 01:10
```

**Comment by jaimeMF** [comment]
It works with the code from the repo, you'll have to wait for the next release.
