### ISSUE TITLE
UnsupportedError - www.foxsports.com/ videos 

### ISSUE THREAD

**Issue by MaryCoding** [rg3/youtube-dl#5517]
Hi, Youtubedl failed to download a video from http://www.foxsports.com/. They currently use the http://link.theplatform.com to host their videos. I tried doing two tests: directly download from theplatform video host and from the foxsport video link. Below are the results:

Edit: here is an xml of their platform video feed http://feed.theplatform.com/f/BKQ29B/fs-mobile-all?byCustomValue={primary}{nba}&sort=pubDate|desc

Using http://www.foxsports.com/video?vid=432609859715
```
root@bullseye2346:~# youtube-dl -v -o "/media/%(title)s.mp4"  http://www.foxsports.com/video?vid=432609859715
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'-o', u'/media/sf_linux_sandbox/%(title)s.mp4', u'http://www.foxsports.com/video?vid=432609859715']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.04.09
[debug] Python version 2.7.6 - Linux-3.13.0-35-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: ffmpeg git-2014-12-27-d4fd3f2, ffprobe git-2014-12-27-d4fd3f2, rtmpdump 2.4
[debug] Proxy map: {}
[generic] video?vid=432609859715: Requesting header
WARNING: Falling back on generic information extractor.
[generic] video?vid=432609859715: Downloading webpage
[generic] video?vid=432609859715: Extracting information
ERROR: Unsupported URL: http://www.foxsports.com/video?vid=432609859715
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 858, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1531, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: mismatched tag: line 62, column 2
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 651, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 275, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1364, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.foxsports.com/video?vid=432609859715

```

Using http://link.theplatform.com/s/BKQ29B/tL4h8PHyBBeU/file.mp4?mbr=true&switch=http&feed=Fox%20Sports%20All%20-%20Mobile&metafile=false

```
youtube-dl -v -o '/media/sf_linux_sandbox/%(title)s.mp4' 'http://link.theplatform.com/s/BKQ29B/tL4h8PHyBBeU/file.mp4?mbr=true&switch=http&feed=Fox%20Sports%20All%20-%20Mobile&metafile=false'
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'-o', u'/media/sf_linux_sandbox/%(title)s.mp4', u'http://link.theplatform.com/s/BKQ29B/tL4h8PHyBBeU/file.mp4?mbr=true&switch=http&feed=Fox%20Sports%20All%20-%20Mobile&metafile=false']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.04.09
[debug] Python version 2.7.6 - Linux-3.13.0-35-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: ffmpeg git-2014-12-27-d4fd3f2, ffprobe git-2014-12-27-d4fd3f2, rtmpdump 2.4
[debug] Proxy map: {}
[ThePlatform] tL4h8PHyBBeU: Downloading XML
[ThePlatform] tL4h8PHyBBeU: Downloading webpage
/usr/local/bin/youtube-dl/youtube_dl/extractor/theplatform.py:132: FutureWarning: The behavior of this method will change in future versions.  Use specific 'len(elem)' or 'elem is not None' test instead.
/usr/local/bin/youtube-dl/youtube_dl/extractor/theplatform.py:166: FutureWarning: The behavior of this method will change in future versions.  Use specific 'len(elem)' or 'elem is not None' test instead.
[debug] Invoking downloader on 'http://fsvideohds-vh.akamaihd.net/z/video/Fox_Sports_Production/921/935/4_bk_150422_grizzlies_blazers_web_2500.mp4?hdnea=st=1429859222~exp=1429859552~acl=/z/video/Fox_Sports_Production/921/935/4_bk_150422_grizzlies_blazers_web_*~id=85f0c72f-41f2-4624-8f09-e0fc27ee3db1~hmac=535c5c05621e975862f2c3d11438c09b475d8f668b626e2e02e02cc52d449f97'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1379, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1354, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 341, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 64, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1673, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden
```

**Comment by MaryCoding** [comment]
Hi guys, I know you are extremely busy. Could someone point a diagnostic of why this is not working even though it uses the supported linkplatform link? Thank you.

**Comment by dstftw** [comment]
Will be fixed in the next version. Thanks for the report.
