### ISSUE TITLE
JSON issue with BBC iplayer

### ISSUE THREAD

**Issue by selvagem** [rg3/youtube-dl#5530]
Most videos work from iplayer but some like this one give the following error. 

User:~ User$ youtube-dl http://bbc.in/1DYuMu5 --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://bbc.in/1DYuMu5', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.04.17
[debug] Python version 2.7.3 - Darwin-14.3.0-x86_64-i386-64bit
[debug] exe versions: rtmpdump 2.4
[debug] Proxy map: {}
[generic] 1DYuMu5: Requesting header
[redirect] Following redirect to http://www.bbc.co.uk/iplayer/episode/b054fn09/ad/natural-world-20152016-2-super-powered-owls
[bbc.co.uk] b054fn09: Downloading video page
[bbc.co.uk] b054fn09: Downloading JSON metadata
ERROR: b054fn09: Failed to parse JSON  (caused by ValueError('No JSON object could be decoded',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 468, in _parse_json
    return json.loads(json_string)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 326, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 651, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 275, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/bbccouk.py", line 334, in _real_extract
    group_id)['jsConf']['player']
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 462, in _download_json
    json_string, video_id, transform_source=transform_source, fatal=fatal)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 472, in _parse_json
    raise ExtractorError(errmsg, cause=ve)
ExtractorError: b054fn09: Failed to parse JSON  (caused by ValueError('No JSON object could be decoded',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
Will be fixed in the next verison.
