### ISSUE TITLE
Yahoo Sports - Video Error download

### ISSUE THREAD

**Issue by MaryCoding** [rg3/youtube-dl#5536]
Great software. You guys are the best. I tried to download the following video and it failed. The link is : http://sports.yahoo.com/news/browns-kruger-eager-homecoming-ravens-164901211--nfl.html

```
root@bullseye2346:~# youtube-dl -v -o "/media/%(title)s.mp4" "http://sports.yahoo.com/news/browns-kruger-eager-homecoming-ravens-164901211--nfl.html"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'-o', u'/media/%(title)s.mp4', u'http://sports.yahoo.com/news/browns-kruger-eager-homecoming-ravens-164901211--nfl.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.04.17
[debug] Python version 2.7.6 - Linux-3.13.0-35-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: ffmpeg git-2014-12-27-d4fd3f2, ffprobe git-2014-12-27-d4fd3f2, rtmpdump 2.4
[debug] Proxy map: {}
[generic] browns-kruger-eager-homecoming-ravens-164901211--nfl: Requesting header
WARNING: Falling back on generic information extractor.
[generic] browns-kruger-eager-homecoming-ravens-164901211--nfl: Downloading webpage
[generic] browns-kruger-eager-homecoming-ravens-164901211--nfl: Extracting information
[debug] Invoking downloader on u'http://l2.yimg.com/bt/api/res/1.2/4.g5VYVfQTXJKyrvDPbZMg--/YXBwaWQ9eW5ld3M7Zmk9ZmlsbDtoPTYwMDtxPTc1O3c9NjAw/http://media.zenfs.com/en_us/Sports/ap/201309131111402622451.cf.png\\'
ERROR: unable to download video data: HTTP Error 401: Authorization Required
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1384, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1359, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 341, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 64, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1678, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 401: Authorization Required
```

**Comment by RingoTheDog** [comment]
Maybe I'm missin' something....but I don't see a video on:
http://sports.yahoo.com/news/browns-kruger-eager-homecoming-ravens-164901211--nfl.html

(just a photo)

**Comment by MaryCoding** [comment]
You are right its an error from my side. Thanks
