### ISSUE TITLE
Vimeo private videos not downloading

### ISSUE THREAD

**Issue by mefromthepast** [rg3/youtube-dl#5542]
Apparently, only few vids are affected.
Two examples with different error outputs.
I'm sure that the videos are uploaded correctly as I am able to watch them embedded on a site!

# ~/Downloads/Python$ youtube-dl https://vimeo.com/126067486
[vimeo] 126067486: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
me@hostname:~/Downloads/downloading/Python$ youtube-dl --verbose http://player.vimeo.com/video/126067486
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://player.vimeo.com/video/126067486']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.04.26
[debug] Python version 2.7.8 - Linux-3.16.0-34-generic-x86_64-with-Ubuntu-14.10-utopic
[debug] exe versions: none
[debug] Proxy map: {}
[vimeo] 126067486: Downloading webpage
[vimeo] 126067486: Extracting information
[debug] Invoking downloader on u'https://pdlvimeocdn-a.akamaihd.net/42354/182/360640182.mp4?token2=1430164552_7e6cb86e14982fda99aaa766984df37a&aksessionid=efc0728cbc76eb38'
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1414, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1363, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 342, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 64, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1701, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found

~/Downloads/downloading/Python$ youtube-dl --verbose http://player.vimeo.com/video/126049994
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://player.vimeo.com/video/126049994']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.04.26
[debug] Python version 2.7.8 - Linux-3.16.0-34-generic-x86_64-with-Ubuntu-14.10-utopic
[debug] exe versions: none
[debug] Proxy map: {}
[vimeo] 126049994: Downloading webpage
[vimeo] 126049994: Extracting information
[debug] Invoking downloader on u'https://pdlvimeocdn-a.akamaihd.net/49293/858/360588191.mp4?token2=1430164319_f135b6fb3cb10b748f980e104b523991&aksessionid=5cdf64d0da46be7f'

ERROR: Did not get any data blocks
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
    youtube_dl.main()
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 402, in main
    _real_main(argv)
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 392, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1481, in download
    res = self.extract_info(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 662, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 708, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1159, in process_video_result
    self.process_info(new_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1414, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1363, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 342, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 218, in real_download
    self.report_error('Did not get any data blocks')
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 155, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 529, in report_error
    self.trouble(error_message, tb)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 491, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())

**Comment by jaimeMF** [comment]
They can be downloaded with `-f h264-sd`, in which page are they embedded?

**Comment by mefromthepast** [comment]
You are right, the videos do not seem to be fully encoded by vimeo yet, or the upload may have failed [probably not, they would not upload different versions]?! Thank you anyways!
http://www.cybrary.it/video/packet-analyzer-part-3/

You'll have to register, but it's totally free … they made it via kickstarter.
https://www.kickstarter.com/projects/1195785519/cybrary-the-worlds-first-free-it-and-cyber-securit/description

**Comment by kfirbreger** [comment]
I believe this ticket can be closed
