### ISSUE TITLE
[Youtube] RegexNotFoundError: Unable to extract Initial JS player signature function name

### ISSUE THREAD

**Issue by shahril96** [rg3/youtube-dl#5546]
```
C:\Users\Shahril\Desktop>youtube-dl -F https://www.youtube.com/watch?v=ctACMnMp3
1M -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-F', 'https://www.youtube.com/watch?v=ctACMnMp31M',
 '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2014.10.18
[debug] Python version 2.7.8 - Windows-8-6.2.9200
[debug] Proxy map: {}
[youtube] Setting language
[youtube] Confirming age
[youtube] ctACMnMp31M: Downloading webpage
[youtube] ctACMnMp31M: Downloading video info webpage
[youtube] ctACMnMp31M: Extracting video information
[youtube] ctACMnMp31M: Encrypted signatures detected.
[youtube] {22} signature length 43.42, html5 player en_US-vflkH_4LI
[youtube] ctACMnMp31M: Downloading js player vflkH_4LI
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 533, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 447, in _extract_signature_funct
ion
  File "youtube_dl\extractor\youtube.pyo", line 508, in _parse_sig_js
  File "youtube_dl\extractor\common.pyo", line 424, in _search_regex
RegexNotFoundError: Unable to extract Initial JS player signature function name;
 please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl
with the --verbose flag and include its complete output. Make sure you are using
 the latest version; type  youtube-dl -U  to update.
 (caused by RegexNotFoundError(u'Unable to extract Initial JS player signature f
unction name; please report this issue on https://yt-dl.org/bug . Be sure to cal
l youtube-dl with the --verbose flag and include its complete output. Make sure
you are using the latest version; type  youtube-dl -U  to update.',)); please re
port this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the -
-verbose flag and include its complete output. Make sure you are using the lates
t version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 533, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 447, in _extract_signature_funct
ion
  File "youtube_dl\extractor\youtube.pyo", line 508, in _parse_sig_js
  File "youtube_dl\extractor\common.pyo", line 424, in _search_regex
RegexNotFoundError: Unable to extract Initial JS player signature function name;
 please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl
with the --verbose flag and include its complete output. Make sure you are using
 the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 524, in extract_info
  File "youtube_dl\extractor\common.pyo", line 193, in extract
  File "youtube_dl\extractor\youtube.pyo", line 928, in _real_extract
  File "youtube_dl\extractor\youtube.pyo", line 543, in _decrypt_signature
ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 533, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 447, in _extract_signature_funct
ion
  File "youtube_dl\extractor\youtube.pyo", line 508, in _parse_sig_js
  File "youtube_dl\extractor\common.pyo", line 424, in _search_regex
RegexNotFoundError: Unable to extract Initial JS player signature function name;
 please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl
with the --verbose flag and include its complete output. Make sure you are using
 the latest version; type  youtube-dl -U  to update.
 (caused by RegexNotFoundError(u'Unable to extract Initial JS player signature f
unction name; please report this issue on https://yt-dl.org/bug . Be sure to cal
l youtube-dl with the --verbose flag and include its complete output. Make sure
you are using the latest version; type  youtube-dl -U  to update.',)); please re
port this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the -
-verbose flag and include its complete output. Make sure you are using the lates
t version; type  youtube-dl -U  to update.
```

**Comment by shahril96** [comment]
Sorry, I was using old youtube-dl version, update to latest version and it's should resolved itself.
