### ISSUE TITLE
[Vporn] ERROR: Unable to extract title

### ISSUE THREAD

**Issue by zay11** [rg3/youtube-dl#5560]
$ youtube-dl -v http://www.vporn.com/female/busty-buffy-big-tits/796952/ 
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.vporn.com/female/busty-buffy-big-tits/796952/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.04.28
[debug] Python version 3.4.3 - Linux-3.19.3-3-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 2.6.2, ffprobe 2.6.2, rtmpdump 2.4
[debug] Proxy map: {}
[Vporn] busty-buffy-big-tits: Downloading webpage
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 649, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 276, in extract
    return self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/vporn.py", line 65, in _real_extract
    r'videoname\s*=\s*\'([^\']+)\'', webpage, 'title').strip()
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 567, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 558, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
Works for me. Could you run it with `--write-pages` and upload *.dump files?

**Comment by zay11** [comment]
The dump file is empty, cannot be uploaded.
