### ISSUE TITLE
--load-info overriding -f choice when -f is a non-DASH stream

### ISSUE THREAD

**Issue by marlencrabapple** [rg3/youtube-dl#5564]
Just updated to youtube-dl version 2015.04.26 and noticed that youtube-dl seems to default to `-f bestvideo+bestaudio`, download those streams, and then finally download the intended stream after an ffmpeg error whenever I try to download a non-dash stream (e.g. `-f 22`) and use `--load-info <file>`. Removing `--load-info <file>` seems to make youtube-dl behave normally. Specifying two dash streams (e.g `-f 136+141`) also works properly, even with `--load-info <file>`.

Relevant Log:
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=pT68FS3YbQ4', u'--load-info', u'./cache/pT68FS3YbQ4', u'--prefer-ffmpeg', u'-f', u'5', u'-o', u'./static/dl/1430411200102342.ytdl']
[debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8
[debug] youtube-dl version 2015.04.26
[debug] Python version 2.7.6 - Linux-3.16.0-36-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: ffmpeg 2.6.2, ffprobe 2.6.2, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Invoking downloader on u'https://r17---sn-a5m7lned.googlevideo.com/videoplayback?id=a53ebc152dd86d0e&itag=135&source=youtube&requiressl=yes&pl=15&mv=m&ms=au&mm=31&gcr=us&ratebypass=yes&mime=video/mp4&gir=yes&clen=23419441&lmt=1429592038630924&dur=191.558&signature=4BE38CF765A28927C462BD4A9AE96E2EBAFA5983.75D8F9461660C28785EDDC5774D3CBD1C4F814C6&sver=3&fexp=900720,907263,934954,938028,938690,9407040,9407454,9408133,9408142,9408597,9408708,9408788,9408941,9412514,9412773,948124,948605,952612,952637,957201&mt=1430412089&upn=JB1KqfxcLfs&key=dg_yt0&ip=23.241.101.187&ipbits=0&expire=1430433810&sparams=ip,ipbits,expire,id,itag,source,requiressl,pl,mv,ms,mm,gcr,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: ./static/dl/1430411200102342.f135.ytdl

[download]   0.0% of 22.33MiB at 79.56KiB/s ETA 04:47
[download]   0.0% of 22.33MiB at 235.94KiB/s ETA 01:36
[download]   0.0% of 22.33MiB at 547.09KiB/s ETA 00:41
[download]   0.1% of 22.33MiB at  1.14MiB/s ETA 00:19
[download]   0.1% of 22.33MiB at  2.04MiB/s ETA 00:10
[download]   0.3% of 22.33MiB at  1.85MiB/s ETA 00:12
[download]   0.6% of 22.33MiB at  2.46MiB/s ETA 00:09
[download]   1.1% of 22.33MiB at  3.51MiB/s ETA 00:06
[download]   2.2% of 22.33MiB at  4.58MiB/s ETA 00:04
[download]   4.5% of 22.33MiB at  5.30MiB/s ETA 00:04
[download]   9.0% of 22.33MiB at  5.79MiB/s ETA 00:03
[download]  17.9% of 22.33MiB at  6.05MiB/s ETA 00:03
[download]  35.8% of 22.33MiB at  5.68MiB/s ETA 00:02
[download]  53.7% of 22.33MiB at  6.26MiB/s ETA 00:01
[download]  71.6% of 22.33MiB at  6.29MiB/s ETA 00:01
[download]  89.5% of 22.33MiB at  6.31MiB/s ETA 00:00
[download] 100.0% of 22.33MiB at  6.32MiB/s ETA 00:00
[download] 100% of 22.33MiB in 00:03
[debug] Invoking downloader on u'https://r17---sn-a5m7lned.googlevideo.com/videoplayback?id=a53ebc152dd86d0e&itag=141&source=youtube&requiressl=yes&pl=15&mv=m&ms=au&mm=31&gcr=us&ratebypass=yes&mime=audio/mp4&gir=yes&clen=6109662&lmt=1429591961175197&dur=191.611&signature=1D05D841E7EF9149CA20F3EE86BF66AA771E53E1.6892EB6D356D51BBB7D0B9069D36F8A5E865E3D6&sver=3&fexp=900720,907263,934954,938028,938690,9407040,9407454,9408133,9408142,9408597,9408708,9408788,9408941,9412514,9412773,948124,948605,952612,952637,957201&mt=1430412089&upn=JB1KqfxcLfs&key=dg_yt0&ip=23.241.101.187&ipbits=0&expire=1430433810&sparams=ip,ipbits,expire,id,itag,source,requiressl,pl,mv,ms,mm,gcr,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: ./static/dl/1430411200102342.f141.ytdl

[download]   0.0% of 5.83MiB at 85.39KiB/s ETA 01:09
[download]   0.1% of 5.83MiB at 253.48KiB/s ETA 00:23
[download]   0.1% of 5.83MiB at 587.05KiB/s ETA 00:10
[download]   0.3% of 5.83MiB at  1.22MiB/s ETA 00:04
[download]   0.5% of 5.83MiB at  1.88MiB/s ETA 00:03
[download]   1.1% of 5.83MiB at  1.97MiB/s ETA 00:02
[download]   2.1% of 5.83MiB at  2.62MiB/s ETA 00:02
[download]   4.3% of 5.83MiB at  3.70MiB/s ETA 00:01
[download]   8.6% of 5.83MiB at  4.69MiB/s ETA 00:01
[download]  17.1% of 5.83MiB at  5.40MiB/s ETA 00:00
[download]  34.3% of 5.83MiB at  5.84MiB/s ETA 00:00
[download]  68.6% of 5.83MiB at  6.08MiB/s ETA 00:00
[download] 100.0% of 5.83MiB at  6.17MiB/s ETA 00:00
[download] 100% of 5.83MiB in 00:00
[ffmpeg] Merging formats into "./static/dl/1430411200102342.ytdl"
[debug] ffmpeg command line: ffmpeg -y -i ./static/dl/1430411200102342.f135.ytdl -i ./static/dl/1430411200102342.f141.ytdl -c copy -map 0:v:0 -map 1:a:0 ./static/dl/1430411200102342.temp.ytdl
ERROR: ./static/dl/1430411200102342.temp.ytdl: Invalid argument
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1520, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/postprocessor/ffmpeg.py", line 589, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/postprocessor/ffmpeg.py", line 148, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
FFmpegPostProcessorError

WARNING: The info failed to download, trying with "https://www.youtube.com/watch?v=pT68FS3YbQ4"
[youtube] pT68FS3YbQ4: Downloading webpage
[youtube] pT68FS3YbQ4: Extracting video information
[youtube] {43} signature length 40.43, html5 player en_US-vfl98hSpx
[youtube] {18} signature length 40.43, html5 player en_US-vfl98hSpx
[youtube] {5} signature length 40.43, html5 player en_US-vfl98hSpx
[youtube] {36} signature length 40.43, html5 player en_US-vfl98hSpx
[youtube] {17} signature length 40.43, html5 player en_US-vfl98hSpx
[youtube] {135} signature length 40.43, html5 player en_US-vfl98hSpx
[youtube] {244} signature length 40.43, html5 player en_US-vfl98hSpx
[youtube] {134} signature length 40.43, html5 player en_US-vfl98hSpx
[youtube] {243} signature length 40.43, html5 player en_US-vfl98hSpx
[youtube] {133} signature length 40.43, html5 player en_US-vfl98hSpx
[youtube] {242} signature length 40.43, html5 player en_US-vfl98hSpx
[youtube] {160} signature length 40.43, html5 player en_US-vfl98hSpx
[youtube] {140} signature length 40.43, html5 player en_US-vfl98hSpx
[youtube] {171} signature length 40.43, html5 player en_US-vfl98hSpx
[youtube] pT68FS3YbQ4: Downloading DASH manifest
[debug] Invoking downloader on u'https://r17---sn-a5m7lned.googlevideo.com/videoplayback?itag=5&mime=video%2Fx-flv&expire=1430433851&id=o-AHoCrHgzyRj7erExRuKaYZ3gmrdXl6yXGGH2pXluiCS6&upn=jxP6ahwtrnM&pl=15&sver=3&source=youtube&mm=31&key=yt5&ip=23.241.101.187&ms=au&ipbits=0&initcwndbps=1683750&mv=m&mt=1430412202&requiressl=yes&sparams=dur%2Cgcr%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Cmime%2Cmm%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&gcr=us&dur=191.608&fexp=900720%2C907263%2C934954%2C936100%2C938028%2C9405994%2C9406475%2C9406612%2C9406640%2C9406848%2C9407715%2C9407991%2C9408706%2C9412544%2C9413039%2C9413054%2C9413104%2C948124%2C952612%2C952637%2C957201&signature=19F53C637CBB5111C295883ECCB0992660F66173.807B367DF76D5BE0068432C9749F9E56DD98CEA8&ratebypass=yes'
[download] Destination: ./static/dl/1430411200102342.ytdl

[download]   0.0% of 8.33MiB at 70.25KiB/s ETA 02:01
[download]   0.0% of 8.33MiB at 208.81KiB/s ETA 00:40
[download]   0.1% of 8.33MiB at 484.30KiB/s ETA 00:17
[download]   0.2% of 8.33MiB at  1.01MiB/s ETA 00:08
[download]   0.4% of 8.33MiB at  1.98MiB/s ETA 00:04
[download]   0.7% of 8.33MiB at  2.02MiB/s ETA 00:04
[download]   1.5% of 8.33MiB at  2.60MiB/s ETA 00:03
[download]   3.0% of 8.33MiB at  3.25MiB/s ETA 00:02
[download]   6.0% of 8.33MiB at  4.38MiB/s ETA 00:01
[download]  12.0% of 8.33MiB at  5.19MiB/s ETA 00:01
[download]  24.0% of 8.33MiB at  5.72MiB/s ETA 00:01
[download]  48.0% of 8.33MiB at  6.02MiB/s ETA 00:00
[download]  96.0% of 8.33MiB at  5.73MiB/s ETA 00:00
[download] 100.0% of 8.33MiB at  5.95MiB/s ETA 00:00
[download] 100% of 8.33MiB in 00:01
```

**Comment by dstftw** [comment]
Will be fixed in the next version. Thanks for the report.
