### ISSUE TITLE
Can't extract video info on Dailymotion

### ISSUE THREAD

**Issue by ssdclickofdeath** [rg3/youtube-dl#5568]
I tried to download a video from Dailymotion with the latest available version of youtube-dl, but it wasn't able to extract the video info. The error returned is, "RegexNotFoundError: Unable to extract video info."

Here's the output:
./youtube-dl --verbose http://www.dailymotion.com/video/x27vaqi_everything-is-awesome_fun
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.dailymotion.com/video/x27vaqi_everything-is-awesome_fun']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.04.28
[debug] Python version 2.7.6 - Linux-3.13.0-49-lowlatency-i686-with-Trisquel-7.0-belenos
[debug] exe versions: avconv 9.18-6, avprobe 9.18-6, ffmpeg 9.16-6, rtmpdump 2.4
[debug] Proxy map: {}
[dailymotion] x27vaqi: Downloading webpage
[dailymotion] x27vaqi: Extracting information
[dailymotion] x27vaqi: Downloading embed page
ERROR: Unable to extract video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 649, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 276, in extract
    return self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/dailymotion.py", line 118, in _real_extract
    'video info', flags=re.MULTILINE)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 558, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by ssdclickofdeath** [comment]
It turns out that dailymotion.com is blocked by my router's content filter.
Sorry for the needless bug report.
Have a nice day.
