### ISSUE TITLE
 CBSSports - extractor error

### ISSUE THREAD

**Issue by MaryCoding** [rg3/youtube-dl#5582]
Hi Guys, I was wanting to download a video from cbssports and it gave an extractor error. Here is the detials of the out put. 
```
youtube-dl -v -f best -o "/media/436905539781.%(ext)s" "http://www.cbssports.com/video/player/nba/436905539781/0/los-angles-clippers-vs-san-antonio-spurs-preview"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'-f', u'best', u'-o', u'/media/436905539781.%(ext)s', u'http://www.cbssports.com/video/player/nba/436905539781/0/los-angles-clippers-vs-san-antonio-spurs-preview']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.04.28
[debug] Python version 2.7.6 - Linux-3.13.0-35-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: ffmpeg git-2014-12-27-d4fd3f2, ffprobe git-2014-12-27-d4fd3f2, rtmpdump 2.4
[debug] Proxy map: {}
[CBSSports] 436905539781: Downloading JSON metadata
ERROR: An extractor error has occured. (caused by StopIteration()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 276, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/cbssports.py", line 29, in _real_extract
    video_info = next(v for v in all_videos if v['pcid'] == video_id)
StopIteration
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 649, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 282, in extract
    raise ExtractorError('An extractor error has occured.', cause=e)
ExtractorError: An extractor error has occured. (caused by StopIteration()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by dstftw** [comment]
There is no such video.

**Comment by MaryCoding** [comment]
The site took the video down. Thanks.
