### ISSUE TITLE
youtube-dl wrongly claims extended attributes are not supported when setxattr() returns ENOSPC

### ISSUE THREAD

**Issue by fstirlitz** [rg3/youtube-dl#5589]
On an ext4 filesystem:
```
$ > x; setfattr -n user.test -v 123 x; getfattr -d x; rm x
# file: x
user.test="123"

$ youtube-dl -v --xattrs 3TR_YuDFIFI
…
[metadata] Writing metadata to file's xattrs
ERROR: This filesystem doesn't support extended attributes. (You may have to enable them in your /etc/fstab)
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/youtube_dl/postprocessor/xattrpp.py", line 120, in run
    write_xattr(filename, xattrname, byte_value)
  File "/usr/lib/python3.4/site-packages/youtube_dl/postprocessor/xattrpp.py", line 54, in write_xattr
    return xattr.setxattr(path, key, value)
OSError: [Errno 28] No space left on device
```
And I wish youtube-dl treated this as a warning anyway, or provided a way to slim down the metadata stored. The only xattr I actually care for is `user.xdg.referrer.url` (the original URL); the rest (usually) already fits inside regular media tags.

**Comment by yan12125** [comment]
Thanks for the report. Now a warning instead of an error is issued in this case.
