### ISSUE TITLE
original.livestream.com Unsupported URL

### ISSUE THREAD

**Issue by arek000000** [rg3/youtube-dl#5598]
This happens when I try to download an archived video from original.livestream.com. It says the URL is unsupported even though the site I'm trying to download from is listed here: https://rg3.github.io/youtube-dl/supportedsites.html

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://original.livestream.com/holyaarom/video?clip
Id=pla_da10db34-440e-4327-bf49-be48de6c498e', '-v', '-o', 'C:\\yt\\%(title)s.%(e
xt)s']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.05.03
[debug] Python version 3.4.3 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-70634-g3bedc99, rtmpdump 2.3
[debug] Proxy map: {}
[generic] video?clipId=pla_da10db34-440e-4327-bf49-be48de6c498e: Requesting head
er
WARNING: Falling back on generic information extractor.
[generic] video?clipId=pla_da10db34-440e-4327-bf49-be48de6c498e: Downloading web
page
[generic] video?clipId=pla_da10db34-440e-4327-bf49-be48de6c498e: Extracting info
rmation
ERROR: Unsupported URL: http://original.livestream.com/holyaarom/video?clipId=pl
a_da10db34-440e-4327-bf49-be48de6c498e
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\youtube_dl\YoutubeDL.py", line 650, in ext
ract_info
    ie_result = ie.extract(url)
  File "C:\Python34\lib\site-packages\youtube_dl\extractor\common.py", line 273,
 in extract
    return self._real_extract(url)
  File "C:\Python34\lib\site-packages\youtube_dl\extractor\generic.py", line 146
3, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: http://original.livestream.c
om/holyaarom/video?clipId=pla_da10db34-440e-4327-bf49-be48de6c498e
```

**Comment by jaimeMF** [comment]
It will work in the next version, thanks for the report.

**Comment by arek000000** [comment]
No, thank *you*! I can't find any other methods of downloading videos from that website, youtube-dl is my only hope :)
