### ISSUE TITLE
[Request] support for kijk.nl video fragments

### ISSUE THREAD

**Issue by corone17** [rg3/youtube-dl#5599]
Video fragment: http://www.kijk.nl/sbs6/hartvannederland/videos/3THw5gImI4CP/ongeval-oosterwolde-1-dode-11-gewonden
```
youtube-dl.exe -vF http://www.kijk.nl/sbs6/hartvannederland/videos/3THw5gImI4CP/ongeval-oost
erwolde-1-dode-11-gewonden
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-vF', u'http://www.kijk.nl/sbs6/hartvannederland/videos/3THw5g
ImI4CP/ongeval-oosterwolde-1-dode-11-gewonden']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.05.03
[debug] Python version 2.7.8 - Windows-XP-5.1.2600-SP3
[debug] exe versions: ffmpeg N-65810-g1b5ec6a
[debug] Proxy map: {}
[generic] ongeval-oosterwolde-1-dode-11-gewonden: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ongeval-oosterwolde-1-dode-11-gewonden: Downloading webpage
[generic] ongeval-oosterwolde-1-dode-11-gewonden: Extracting information
ERROR: Unsupported URL: http://www.kijk.nl/sbs6/hartvannederland/videos/3THw5gImI4CP/ongeval
-oosterwolde-1-dode-11-gewonden
Traceback (most recent call last):
  File "youtube_dl\extractor\generic.pyo", line 938, in _real_extract
  File "youtube_dl\utils.pyo", line 1557, in parse_xml
  File "xml\etree\ElementTree.pyo", line 1300, in XML
  File "xml\etree\ElementTree.pyo", line 1642, in feed
  File "xml\etree\ElementTree.pyo", line 1506, in _raiseerror
ParseError: not well-formed (invalid token): line 1, column 750
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 650, in extract_info
  File "youtube_dl\extractor\common.pyo", line 273, in extract
  File "youtube_dl\extractor\generic.pyo", line 1463, in _real_extract
UnsupportedError: Unsupported URL: http://www.kijk.nl/sbs6/hartvannederland/videos/3THw5gImI
4CP/ongeval-oosterwolde-1-dode-11-gewonden
```

**Comment by corone17** [comment]
It appears in the meantime support has been added. Probably because of other issues/commits.

```bat
youtube-dl.exe -vF http://www.kijk.nl/sbs6/hartvannederland/videos/3THw5gImI4CP/ongeval-oost
erwolde-1-dode-11-gewonden
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-vF', u'http://www.kijk.nl/sbs6/hartvannederland/videos/3THw5g
ImI4CP/o
ngeval-oosterwolde-1-dode-11-gewonden']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.07.07
[debug] Python version 2.7.8 - Windows-XP-5.1.2600-SP3
[debug] exe versions: ffmpeg N-65810-g1b5ec6a
[debug] Proxy map: {}
[generic] ongeval-oosterwolde-1-dode-11-gewonden: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ongeval-oosterwolde-1-dode-11-gewonden: Downloading webpage
[generic] ongeval-oosterwolde-1-dode-11-gewonden: Extracting information
[generic] Brightcove video detected.
[download] Downloading playlist: Hart van Nederland - KIJK
[generic] playlist Hart van Nederland - KIJK: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[Brightcove] 4211822212001: Downloading webpage
[Brightcove] 4211822212001: Extracting information
[info] Available formats for 4211822212001:
format code  extension  resolution note
0            mp4        320x180    5.15MiB
1            mp4        376x212    6.56MiB
2            mp4        440x248    7.92MiB
3            mp4        528x296    9.66MiB
4            mp4        620x348    11.87MiB
5            mp4        732x412    14.69MiB
6            mp4        868x488    18.27MiB
7            mp4        868x488    22.77MiB (best)
```
Thank you. I'll leave it open for now for you to check if the format-codes are extracted correctly.
