### ISSUE TITLE
Foxsports downloader does not support different link formats

### ISSUE THREAD

**Issue by MaryCoding** [rg3/youtube-dl#5611]
Hi, Please take a look at my inital issue [here](https://github.com/rg3/youtube-dl/issues/5517#event-294492450). dstfw did a great job to initialize the foxsport downloader. There are some issues. Below are different format for foxsport links that are not supported for the foxsport downloader. The extractor seems to only handle links with the format http://www.foxsports.com/video?vid=432609859715.  Most importantly could have download directly from the foxsports platform link. Currently it gives error: 
```
ERROR: unable to download video data: HTTP Error 403: Forbidden
```

* http://link.theplatform.com/s/BKQ29B/z2QQOI_emPdP/file.mp4?mbr=true&switch=http&feed=Fox%20Sports%20All%20-%20Mobile&metafile=false

Other common foxsport links:
* http://www.foxsports.com/boxing/story/floyd-mayweather-jr-manny-pacquiao-may-2-las-vegas-reaction-022015
* http://www.foxsports.com/mlb/video?vid=438792259745
* http://www.foxsports.com/tennessee/video/2014-nfl-draft-grades-tennessee-titans-051214
* http://www.foxsports.com/nfl/lists/2015-nfl-draft-grades-dallas-cowboys-cleveland-browns-philadelphia-eagles-050215

**Comment by MaryCoding** [comment]
Hi, I haven't heard any updates. Sorry but want to download few sport videos from foxsports and cant because different format of links is not supported.

**Comment by MaryCoding** [comment]
Hi @dstftw I tested this on the updated version 2015.05.10 and it failed for link: http://www.foxsports.com/tennessee/video/2014-nfl-draft-grades-tennessee-titans-051214 

```
youtube-dl -v -o "/media/test6.%(ext)s" "http://www.foxsports.com/tennessee/video/2014-nfl-draft-grades-tennessee-titans-051214"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'-o', u'/media/test6.%(ext)s', u'http://www.foxsports.com/tennessee/video/2014-nfl-draft-grades-tennessee-titans-051214']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.05.10
[debug] Python version 2.7.6 - Linux-3.13.0-35-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: ffmpeg git-2014-12-27-d4fd3f2, ffprobe git-2014-12-27-d4fd3f2, rtmpdump 2.4
[debug] Proxy map: {}
[FoxSports] 2014-nfl-draft-grades-tennessee-titans-051214: Downloading webpage
ERROR: Unable to extract data player config; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 650, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 273, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/foxsports.py", line 28, in _real_extract
    r"data-player-config='([^']+)'", webpage, 'data player config'),
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 555, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract data player config;
```

**Comment by dstftw** [comment]
Last two urls use different platform that is not supported currently.

**Comment by MaryCoding** [comment]
@dstftw  oh ok. Also, I see several foxsports video links hosted by Theplatform but currently youtube-dl cant download those videos. It gives error. Example:  http://link.theplatform.com/s/BKQ29B/IXxaInYXY02p/file.mp4?mbr=true&switch=http&feed=Fox%20Sports%20All%20-%20Mobile&metafile=false How come?

**Comment by dstftw** [comment]
You have to pass original foxsports links to youtube-dl, not theplatform
ones.

**Comment by MaryCoding** [comment]
@dstftw  Sorry, not my goal to bother. But for example http://www.foxsports.com/nascar/video?vid=442748483521 belongs to http://link.theplatform.com/s/BKQ29B/IXxaInYXY02p/file.mp4?mbr=true&switch=http&feed=Fox%20Sports%20All%20-%20Mobile&metafile=false. I understand the foxsports platform only takes foxsports links. Why cant this platform link format be implemented to the platform extractor?

**Comment by xiangshuii** [comment]
I often use allavsoft to download fOX Sports Videos to MP4, WMV, MOV, AVI, FLV, etc

**Comment by cherishowned** [comment]
I find a workable Foxsports downloader called Allavsoft from http://www.allavsoft.com/how-to/download-foxsports-videos.html
