### ISSUE TITLE
Site Request:  svt.se

### ISSUE THREAD

**Issue by RingoTheDog** [rg3/youtube-dl#5622]
Sveriges Television AB is the Swedish national public TV broadcaster, and I see you already support svtplay..so guessing this should be similar (the same?)

URL: http://www.svt.se/sport/ishockey/jagr-tacklar-giroux-under-intervjun

youtube-dl.py -v "http://www.svt.se/sport/ishockey/jagr-tacklar-giroux-under-intervjun"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.svt.se/sport/ishockey/jagr-tacklar-giroux-under-intervjun']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.05.04
[debug] Python version 2.7.5 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-71727-g46778ab, rtmpdump 2.4
[debug] Proxy map: {}
[generic] jagr-tacklar-giroux-under-intervjun: Requesting header
WARNING: Falling back on generic information extractor.
[generic] jagr-tacklar-giroux-under-intervjun: Downloading webpage
[generic] jagr-tacklar-giroux-under-intervjun: Extracting information
ERROR: Unsupported URL: http://www.svt.se/sport/ishockey/jagr-tacklar-giroux-under-intervjun
Traceback (most recent call last):
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\generic.py", line 938, in _real_extract
    doc = parse_xml(webpage)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\utils.py", line 1557, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: mismatched tag: line 49, column 2
Traceback (most recent call last):
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 650, in extract_info
    ie_result = ie.extract(url)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\common.py", line 273, in extract
    return self._real_extract(url)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\generic.py", line 1463, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.svt.se/sport/ishockey/jagr-tacklar-giroux-under-intervjun

As always...amazing job & Thanks!
Ringo

**Comment by dstftw** [comment]
Will be supported in the next version. Thanks for the report.
