### ISSUE TITLE
[pbs] download broken after latest commit

### ISSUE THREAD

**Issue by ajsgithub** [rg3/youtube-dl#5624]
Using youtube-dl version 2015.05.04, downloads from PBS are broken.

> youtube-dl --write-pages --verbose -t --username <snip> --password <snip> http://video.pbs.org/video/2365417082/

yields

> [debug] System config: []
> [debug] User config: []
> [debug] Command-line args: ['--write-pages', '--verbose', '-t', '--username', 'PRIVATE', '--password', > > 'PRIVATE', 'http://video.pbs.org/video/2365417082/']
> [debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
> [debug] youtube-dl version 2015.05.04
> [debug] Python version 3.4.3 - Darwin-14.3.0-x86_64-i386-64bit
> [debug] exe versions: none
> [debug] Proxy map: {}
> [PBS] 2365417082: Downloading JSON metadata
> [PBS] Saving request to 2365417082_http_-_video.pbs.org_videoInfo_2365417082format=json_type=partner.dump
> [PBS] 2365417082: Downloading recommended_encoding video url info
> [PBS] Saving request to 2365417082_http_-_urs.pbs.org_redirect_ad55d66c23ba4c8ea25087d54ef02519_format=json.dump
> [PBS] 2365417082: Downloading m3u8 information
> [PBS] Saving request to 2365417082_http_-_ga.video.cdn.pbs.org_videos_american-experience_1ce286ab-ba80-402d-a5c3-62b483fd6a51_182680_hd-mezzanine-16x9_16c874ae_ldav000_2hour_episode_m1080-16x9-hls-400-2500k.m3u8.dump
> [PBS] 2365417082: Downloading alternate_encoding video url info
> [PBS] Saving request to 2365417082_http_-_urs.pbs.org_redirect_e92e7e6454f8481b9aae73b54e25018c_format=json.dump
> Traceback (most recent call last):
>   File "/Users/<snip>/anaconda/lib/python3.4/runpy.py", line 170, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/Users/<snip>/anaconda/lib/python3.4/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/Users/<snip>/.local/bin/youtube-dl/__main__.py", line 19, in <module>
>   File "/Users/<snip>/.local/bin/youtube-dl/youtube_dl/__init__.py", line 401, in main
>   File "/Users/<snip>/.local/bin/youtube-dl/youtube_dl/__init__.py", line 391, in _real_main
>   File "/Users/<snip>.local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1482, in download
>   File "/Users/<snip>/.local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 650, in extract_info
>   File "/Users/<snip>/.local/bin/youtube-dl/youtube_dl/extractor/common.py", line 273, in extract
>   File "/Users/<snip>/.local/bin/youtube-dl/youtube_dl/extractor/pbs.py", line 191, in _real_extract
>   File "/Users/<snip>/.local/bin/youtube-dl/youtube_dl/extractor/common.py", line 769, in _sort_formats
> TypeError: unorderable types: NoneType() < str()

Version 2015.04.28 works with the same URL, but the low resolution video is downloaded.

**Comment by ajsgithub** [comment]
##### Contents of 2365417082_http_-_ga.video.cdn.pbs.org_videos_american-experience_1ce286ab-ba80-402d-a5c3-62b483fd6a51_182680_hd-mezzanine-16x9_16c874ae_ldav000_2hour_episode_m1080-16x9-hls-400-2500k.m3u8.dump

> #EXTM3U
> #EXT-X-MEDIA:URI="16c874ae_LDAV000_2Hour_Episode_M1080-captions.m3u8",TYPE=SUBTITLES,GROUP-ID="subs",LANGUAGE="en",NAME="English",DEFAULT=YES,AUTOSELECT=YES,FORCED=NO
> #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1533000,RESOLUTION=854x480,CODECS="avc1.4d001f, mp4a.40.5",SUBTITLES="subs"
16c874ae_ldav000_2hour_episode_m1080-16x9-hls-1200k.m3u8
> #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2963000,RESOLUTION=1280x720,CODECS="avc1.4d001f, mp4a.40.5",SUBTITLES="subs"
16c874ae_ldav000_2hour_episode_m1080-16x9-hls-2500k.m3u8
> #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1093000,RESOLUTION=640x360,CODECS="avc1.4d001f, mp4a.40.5",SUBTITLES="subs"
16c874ae_ldav000_2hour_episode_m1080-16x9-hls-800k.m3u8
> #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=504000,RESOLUTION=416x234,CODECS="avc1.4d001f, mp4a.40.5",SUBTITLES="subs"
16c874ae_ldav000_2hour_episode_m1080-16x9-hls-400k.m3u8

##### Contents of 2365417082_http_-_urs.pbs.org_redirect_ad55d66c23ba4c8ea25087d54ef02519_format=json.dump

> {"url": "http://ga.video.cdn.pbs.org/videos/american-experience/1ce286ab-ba80-402d-a5c3-62b483fd6a51/182680/hd-mezzanine-16x9/16c874ae_ldav000_2hour_episode_m1080-16x9-hls-400-2500k.m3u8", "status": "ok", "message": null, "http_code": 302}

##### 2365417082_http_-_urs.pbs.org_redirect_e92e7e6454f8481b9aae73b54e25018c_format=json.dump

> {"url": "http://ga.video.cdn.pbs.org/videos/american-experience/1ce286ab-ba80-402d-a5c3-62b483fd6a51/182680/hd-mezzanine-16x9/16c874ae_ldav000_2hour_episode_m1080-16x9-mp4-baseline.mp4", "status": "ok", "message": null, "http_code": 302}

##### Contents of 2365417082_http_-_video.pbs.org_videoInfo_2365417082format=json_type=partner.dump

> {"title": "Last Days in Vietnam", "description": "In April of 1975, the North Vietnamese Army was closing in on Saigon as South Vietnamese resistance was crumbling. Approximately 5,000 Americans remained with roughly 24 hours to get out. Their South Vietnamese allies, co-workers, and friends faced certain imprisonment and possible death if they remained behind. Last Days in Vietnam premieres on PBS April 28 at 9/8c.", "short_description": "Approximately 5,000 Americans remained with roughly 24 hours to get out. April 28, 9/8c.", "allow_embed": true, "rating": "NR", "funder_data": {"underwriting": null, "nola_episode": "", "nola_root": "AMEX"}, "related_links": [], "related_content": [], "contentID": 2365417082, "liverail": {"verticals": "program_pbs_american_experience", "id": 1415, "ad_map": "in:warnings:0;in:pbs:0;in:pbs:658.0;in:pbs:1320.0;ov:pbs:6700,6715", "tags": "nolaroot_amex,program_pbs_american_experience,localstation_PBS"}, "program": {"website": "http://www.pbs.org/wgbh/americanexperience/", "page_tracking": "UA-3988626-1", "videos_uri": "http://merlin.pbs.org/rocket/list/program/144/videos/", "description": "American Experience, TV\u2019s most-watched history series, brings to life the compelling stories from our past that inform our understanding of the world today.", "stack_uri": "http://merlin.pbs.org/rocket/list/program/144/videostack/", "title": "American Experience", "event_tracking": "UA-3988626-2", "producer": "pbs", "producer_website": "http://video.pbs.org", "stack": "http://s3.amazonaws.com/pbs.merlin.cdn.prod/program_pages/AMEX_DotOrg_StackCard_080513.380x212.jpeg", "shorts_uri": "http://merlin.pbs.org/rocket/list/program/144/shorts/", "background": "http://s3.amazonaws.com/pbs.merlin.cdn.prod/program_pages/AMEX_background_______5.950x356.jpg", "logo": "http://s3.amazonaws.com/pbs.merlin.cdn.prod/program_pages/AMEX-NEW-TUNEIN-LOGO_1.png", "underwriting": "", "previews_uri": "http://merlin.pbs.org/rocket/list/program/144/previews/", "slug": "american-experience", "nola_root": "AMEX", "episodes_uri": "http://merlin.pbs.org/rocket/list/program/144/episodes/"}, "nola_episode": "", "recommended_encoding": {"url": "http://urs.pbs.org/redirect/ad55d66c23ba4c8ea25087d54ef02519/", "bitrate": 0, "type": "download", "eeid": "hls-400-2500k-16x9", "mime_type": "application/x-mpegURL"}, "alternate_encoding": {"url": "http://urs.pbs.org/redirect/e92e7e6454f8481b9aae73b54e25018c/", "bitrate": 0, "type": "download", "eeid": "mp4-baseline-16x9", "mime_type": "video/mp4"}, "closed_captions_url": "http://ga.video.cdn.pbs.org/captions/american-experience/1ce286ab-ba80-402d-a5c3-62b483fd6a51/captions/324750_Encoded.dfxp", "chapters": [{"duration": 658000, "start_time": 0, "image": "http://image.pbs.org/video-assets/pbs/american-experience/160144/images/chapters/from-peace-to-panic_645.jpg", "title": "From Peace to Panic"}, {"duration": 662000, "start_time": 658000, "image": "http://image.pbs.org/video-assets/pbs/american-experience/160144/images/chapters/an-urgent-situation_020.jpg", "title": "An Urgent Situation"}, {"duration": 771000, "start_time": 1320000, "image": "http://image.pbs.org/video-assets/pbs/american-experience/160144/images/chapters/planning-for-evacuation_798.jpg", "title": "Planning for Evacuation"}, {"duration": 711000, "start_time": 2091000, "image": "http://image.pbs.org/video-assets/pbs/american-experience/160144/images/chapters/saigon-under-attack_970.jpg", "title": "Saigon Under Attack"}, {"duration": 574000, "start_time": 2802000, "image": "http://image.pbs.org/video-assets/pbs/american-experience/160144/images/chapters/rush-to-the-embassy_572.jpg", "title": "Rush to the Embassy"}, {"duration": 736000, "start_time": 3376000, "image": "http://image.pbs.org/video-assets/pbs/american-experience/160144/images/chapters/the-airlift-begins_720.jpg", "title": "The Airlift Begins"}, {"duration": 660000, "start_time": 4112000, "image": "http://image.pbs.org/video-assets/pbs/american-experience/160144/images/chapters/mikis-story_246.jpg", "title": "Miki's Story"}, {"duration": 678000, "start_time": 4772000, "image": "http://image.pbs.org/video-assets/pbs/american-experience/160144/images/chapters/evacuating-the-embassy_754.jpg", "title": "Evacuating the Embassy"}, {"duration": 635000, "start_time": 5450000, "image": "http://image.pbs.org/video-assets/pbs/american-experience/160144/images/chapters/the-last-helicopter_149.jpg", "title": "The Last Helicopter"}, {"duration": 585000, "start_time": 6085000, "image": "http://image.pbs.org/video-assets/pbs/american-experience/160144/images/chapters/surrender-of-saigon_009.jpg", "title": "Surrender of Saigon"}, {"duration": 60000, "start_time": 6670000, "image": "http://image.pbs.org/video-assets/pbs/american-experience/160144/images/chapters/credits_829.jpg", "title": "Credits"}], "dvd_link": "http://www.shoppbs.org/product/index.jsp?productId=57580676&utm_source=PBS&utm_medium=Link&utm_content=amex_lastdaysinvietnam_covebuyit&utm_campaign=cove_buyit", "itunes_link": "", "com_scores": ["030223", "030223"], "duration": 6730, "image_url": "http://image.pbs.org/video-assets/pbs/american-experience/160144/images/mezzanine_576.jpg", "airdate": 1430254800, "expiredate": 1432857600, "not_yet_available": false, "event_tracking": {"station_events": [""], "national_events": ["UA-6766312-2"], "program_events": ["UA-3988626-2"], "program_station_events": [""]}, "mvod": {"station": {"common_name": "PBS", "plus_url": "", "callsign": "pbs", "image": "http://image.pbs.org/station-images/MVOD/pbs.png"}, "nearby_stations": [], "is_mvod_restricted": false, "is_mvod": false, "is_mvod_user": false}}

**Comment by ajsgithub** [comment]
Thanks.  Works great.
