### ISSUE TITLE
UnicodeDecodeError when PATH contains non-ascii

### ISSUE THREAD

**Issue by goeranu** [rg3/youtube-dl#5647]
When trying to use youtube-dl, I consistently get a UnicodeDecodeError thrown from subprocess.py, called from ffmpeg.py.  It seems to be related to the fact that my and home directory contains non ascii (`/home/göran`) and I have a subdirectory of that directory (`/home/göran/.local/bin`) in my PATH.

If I remove the first directory from my PATH, youtube-dl works.

I'm running on Fedora, using 
python-2.7.8-4.1.fc21.x86_64
youtube-dl-2015.04.28-1.fc22.noarch

```
23:09 mimmi$ echo $PATH
/home/göran/.local/bin:/usr/lib64/qt-3.3/bin:/usr/lib64/ccache:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/usr/games:/opt/real/RealPlayer:.:/opt/real/RealPlayer
22:46 mimmi$ youtube-dl -v --prefer-free-formats 'https://www.youtube.com/watch?v=OUoO4YbU774'
[debug] System config: [u'--prefer-free-formats']
[debug] User config: []
[debug] Command-line args: [u'-v', u'--prefer-free-formats', u'https://www.youtube.com/watch?v=OUoO4YbU774']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.04.28
[debug] Python version 2.7.8 - Linux-3.18.3-201.fc21.x86_64-x86_64-with-fedora-14-Laughlin
Traceback (most recent call last):
  File "/usr/bin/youtube-dl", line 6, in <module>
    youtube_dl.main()
  File "/usr/lib/python2.7/site-packages/youtube_dl/__init__.py", line 401, in main
    _real_main(argv)
  File "/usr/lib/python2.7/site-packages/youtube_dl/__init__.py", line 368, in _real_main
    with YoutubeDL(ydl_opts) as ydl:
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 332, in __init__
    self.print_debug_header()
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 1732, in print_debug_header
    exe_versions = FFmpegPostProcessor.get_versions(self)
  File "/usr/lib/python2.7/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 50, in get_versions
    return FFmpegPostProcessor(downloader)._versions
  File "/usr/lib/python2.7/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 34, in __init__
    self._determine_executables()
  File "/usr/lib/python2.7/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 90, in _determine_executables
    (p, get_exe_version(p, args=['-version'])) for p in programs)
  File "/usr/lib/python2.7/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 90, in <genexpr>
    (p, get_exe_version(p, args=['-version'])) for p in programs)
  File "/usr/lib/python2.7/site-packages/youtube_dl/utils.py", line 1374, in get_exe_version
    stdout=subprocess.PIPE, stderr=subprocess.STDOUT).communicate()
  File "/usr/lib64/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 7: ordinal not in range(128)
```

**Comment by jaimeMF** [comment]
Fixed, thanks for the report.
