### ISSUE TITLE
MixCloud: RegexNotFoundError: Unable to extract title

### ISSUE THREAD

**Issue by psycon** [rg3/youtube-dl#5654]
```
22:49 psy@psycoholic:~/Musik/Elektro $ youtube-dl --verbose "https://www.mixcloud.com/ganzweitdraussen/gwd-podcast-018-lekesch-schekel-08-05-15/"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'https://www.mixcloud.com/ganzweitdraussen/gwd-podcast-018-lekesch-schekel-08-05-15/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.08.05
[debug] Python version 2.7.9 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.0
[debug] Proxy map: {}
[mixcloud] ganzweitdraussen-gwd-podcast-018-lekesch-schekel-08-05-15: Downloading webpage
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 516, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 170, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/mixcloud.py", line 75, in _real_extract
    PREFIX + r'm-title="([^"]+)"', webpage, 'title')
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 401, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 391, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
```

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.
