### ISSUE TITLE
[lifenews] ERROR: Unsupported URL

### ISSUE THREAD

**Issue by spvkgn** [rg3/youtube-dl#5660]
Please add support for this new URL format on lifenews.ru.

```
~ $ youtube-dl -v http://lifenews.ru/video/13035
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://lifenews.ru/video/13035']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.05.04
[debug] Python version 2.7.3 - Linux-3.2.0-79-generic-pae-i686-with-LinuxMint-13-maya
[debug] exe versions: ffmpeg 2.5.3-7, ffprobe 2.5.3-7, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 13035: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 13035: Downloading webpage
[generic] 13035: Extracting information
ERROR: Unsupported URL: http://lifenews.ru/video/13035
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 938, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1557, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1301, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1643, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1507, in _raiseerror
    raise err
ParseError: mismatched tag: line 45, column 2
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 650, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 273, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1463, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://lifenews.ru/video/13035
```

**Comment by dstftw** [comment]
This URL format will be supported in the next version. Thanks for the report.
