### ISSUE TITLE
MLB URL

### ISSUE THREAD

**Issue by RingoTheDog** [rg3/youtube-dl#5663]
results in a blank index-index.jsp file.

URL:
http://washington.nationals.mlb.com/mlb/gameday/index.jsp?c_id=was&gid=2015_05_09_atlmlb_wasmlb_1&lang=en&content_id=108309983&mode=video#

C:\>youtube-dl -v "http://washington.nationals.mlb.com/mlb/gameday/index.jsp?c_i
d=was&gid=2015_05_09_atlmlb_wasmlb_1&lang=en&content_id=108309983&mode=video#"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://washington.nationals.mlb.com/mlb/gam
eday/index.jsp?c_id=was&gid=2015_05_09_atlmlb_wasmlb_1&lang=en&content_id=108309
983&mode=video#']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.05.10
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-71346-gdf4fca2
[debug] Proxy map: {}
[generic] index: Requesting header
[redirect] Following redirect to http://washington.nationals.mlb.com/mlb/gameday
/index.jsp?c_id=was&gid=2015_05_09_atlmlb_wasmlb_1&lang=en&content_id=108309983&
mode=video
[generic] index: Requesting header
WARNING: Falling back on generic information extractor.
[generic] index: Downloading webpage
WARNING: URL could be a direct video link, returning it as such.
[debug] Invoking downloader on u'http://washington.nationals.mlb.com/mlb/gameday
/index.jsp?c_id=was&gid=2015_05_09_atlmlb_wasmlb_1&lang=en&content_id=108309983&
mode=video'
[download] Destination: index-index.jsp
[download] 100% of 81.00KiB in 00:00

Thanks
Ringo

**Comment by RingoTheDog** [comment]
Same video...different URL...different result:

http://mlb.mlb.com/mlb/gameday/index.jsp?gid=2015_05_09_atlmlb_wasmlb_1&mode=video&content_id=108309983&tcid=vpp_copy_108309983

C:\>youtube-dl -v "http://mlb.mlb.com/mlb/gameday/index.jsp?gid=2015_05_09_atlml
b_wasmlb_1&mode=video&content_id=108309983&tcid=vpp_copy_108309983"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://mlb.mlb.com/mlb/gameday/index.jsp?gi
d=2015_05_09_atlmlb_wasmlb_1&mode=video&content_id=108309983&tcid=vpp_copy_10830
9983']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.05.10
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-71346-gdf4fca2
[debug] Proxy map: {}
[MLB] index.jsp?gid=2015_05_09_atlmlb_wasmlb_1&mode=video&content_id=108309983&t
cid=vpp_copy_108309983: Downloading webpage
ERROR: Unable to extract video id; please report this issue on https://yt-dl.org
/bug . Make sure you are using the latest version; type  youtube-dl -U  to updat
e. Be sure to call youtube-dl with the --verbose flag and include its complete o
utput.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 650, in extract_info
  File "youtube_dl\extractor\common.pyo", line 273, in extract
  File "youtube_dl\extractor\mlb.pyo", line 128, in _real_extract
  File "youtube_dl\extractor\common.pyo", line 555, in _search_regex
RegexNotFoundError: Unable to extract video id; please report this issue on http
s://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl
 -U  to update. Be sure to call youtube-dl with the --verbose flag and include i
ts complete output.
