### ISSUE TITLE
player2.screenwavemedia.com

### ISSUE THREAD

**Issue by Meneth32** [rg3/youtube-dl#5696]
Screenwavemedia has deployed a new server: player2. Videos using that server cannot be downloaded with youtube-dl as of version 2015.05.10. Here's some output:
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://teamfourstar.com/video/dragonball-z-abridged-episode-47-family-reunion/']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.05.10
[debug] Git HEAD: 372744c
[debug] Python version 3.4.2 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-50911-g9efcfbe
[debug] Proxy map: {}
[TeamFour] dragonball-z-abridged-episode-47-family-reunion: Downloading webpage
ERROR: Unable to extract player data URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.py", line 649, in extract_info
    ie_result = ie.extract(url)
  File "youtube_dl\extractor\common.py", line 273, in extract
    return self._real_extract(url)
  File "youtube_dl\extractor\screenwavemedia.py", line 103, in _real_extract
    webpage, 'player data URL')
  File "youtube_dl\extractor\common.py", line 555, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract player data URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by dstftw** [comment]
player2 will be supported in the next version. Thanks for the report.
