### ISSUE TITLE
[argentinetangovideos.net] YoutubeDL.py:761:process_ie_result:IndexError: list index out of range

### ISSUE THREAD

**Issue by mcepl** [rg3/youtube-dl#5706]
Originally filed as https://bugzilla.redhat.com/show_bug.cgi?id=1201333
```
matej@mitmanek: ~$ youtube-dl --verbose --playlist-items 2 http://www.argentinetangovideos.net/2008/02/mauricio-castro.html
[debug] System config: [u'--prefer-free-formats']
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'--playlist-items', u'2', u'http://www.argentinetangovideos.net/2008/02/mauricio-castro.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.05.10
[debug] Python version 2.7.5 - Linux-3.10.0-241.el7.rhel72drm4.x86_64-x86_64-with-redhat-7.1-Maipo
[debug] exe versions: ffmpeg 2.3.4, ffprobe 2.3.4, rtmpdump 2.4
[debug] Proxy map: {}
[generic] mauricio-castro: Requesting header
WARNING: Falling back on generic information extractor.
[generic] mauricio-castro: Downloading webpage
[generic] mauricio-castro: Extracting information
[download] Downloading playlist: Argentine Tango Videos: Mauricio Castro
Traceback (most recent call last):
  File "/usr/bin/youtube-dl", line 9, in <module>
    load_entry_point('youtube-dl==2015.05.10', 'console_scripts', 'youtube-dl')()
  File "/usr/lib/python2.7/site-packages/youtube_dl/__init__.py", line 401, in main
    _real_main(argv)
  File "/usr/lib/python2.7/site-packages/youtube_dl/__init__.py", line 391, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 1484, in download
    res = self.extract_info(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 661, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 763, in process_ie_result
    entries = [ie_entries[i - 1] for i in playlistitems]
IndexError: list index out of range
matej@mitmanek: ~$ 
```

**Comment by jaimeMF** [comment]
It will be fixed in the next version, thanks for reporting the issue upstream.
