### ISSUE TITLE
instagram: https not recognised as supported

### ISSUE THREAD

**Issue by pabs3** [rg3/youtube-dl#5739]
```
$ youtube-dl --verbose https://instagram.com/schekobon/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'https://instagram.com/schekobon/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.02.28
[debug] Python version 2.7.10rc1 - Linux-4.0.0-1-amd64-x86_64-with-debian-stretch-sid
[debug] exe versions: avconv 11.3-6, avprobe 11.3-6, rtmpdump 2.4
[debug] Proxy map: {}
[generic] schekobon: Requesting header
WARNING: Could not send HEAD request to https://instagram.com/schekobon/: HTTP Error 405: METHOD NOT ALLOWED
[generic] schekobon: Downloading webpage
WARNING: Falling back on generic information extractor.
[generic] schekobon: Extracting information
ERROR: Unsupported URL: https://instagram.com/schekobon/
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 751, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/utils.py", line 1522, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 22, column 110
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 643, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 275, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 1202, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://instagram.com/schekobon/
```

**Comment by jaimeMF** [comment]
Thanks for the report, it will work in the next version.
