### ISSUE TITLE
no conn, hlsvp or url_encoded_fmt_stream_map information found in video info

### ISSUE THREAD

**Issue by hadess** [rg3/youtube-dl#5745]
The broadcast has started, and can be viewed through the browser.

```
$ youtube-dl --verbose "https://www.youtube.com/watch?v=6beCycCN_Ao"
[debug] System config: [u'--prefer-free-formats']
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://www.youtube.com/watch?v=6beCycCN_Ao']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.05.10
[debug] Python version 2.7.9 - Linux-4.0.1-300.fc22.x86_64-x86_64-with-fedora-22-Twenty_Two
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] 6beCycCN_Ao: Downloading webpage
[youtube] 6beCycCN_Ao: Downloading video info webpage
[youtube] 6beCycCN_Ao: Extracting video information
ERROR: no conn, hlsvp or url_encoded_fmt_stream_map information found in video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 882, in _real_extract
    raise ValueError('No stream_map present')  # caught below
ValueError: No stream_map present
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 650, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 273, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 1110, in _real_extract
    raise ExtractorError('no conn, hlsvp or url_encoded_fmt_stream_map information found in video info')
ExtractorError: no conn, hlsvp or url_encoded_fmt_stream_map information found in video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by yan12125** [comment]
I got the same error yesterday and I can download it today. Maybe it's a temporary server issue in youtube. Can you download it now?

**Comment by hadess** [comment]
Yes, although it's much less interesting now as I was hoping to use youtube-dl to stream it to my media player. Thanks for the review though.

**Comment by yan12125** [comment]
You can use ```-o -``` to stream to media players via pipes. For example:
```
youtube-dl -o - "https://www.youtube.com/watch?v=6beCycCN_Ao" | vlc -
```
Note: vlc is my daily-use player. Parameters can be different for other players.

**Comment by hadess** [comment]
I meant streaming the live video. It's finished now, and ended up watching it in a web browser :/
