### ISSUE TITLE
problem with theplatform.com

### ISSUE THREAD

**Issue by 2011** [rg3/youtube-dl#5746]
Output said to report this, so...

Two attempts (same media with slightly different URLs):

$ youtube-dl -v 'https://player.theplatform.com/p/D6x-PC/pulse_preview/embed/select/media/yMBg9E8KFxZD'
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--restrict-filenames', '-o', '%(title)s-%(id)s-%(uploader)s.%(ext)s', '-w', '-v', 'https://player.theplatform.com/p/D6x-PC/pulse_preview/embed/select/media/yMBg9E8KFxZD']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.05.15
[debug] Python version 3.4.1 - Linux-3.18.7-x86_64-Intel-R-_Core-TM-_i5_CPU_750_@_2.67GHz
[debug] exe versions: ffmpeg 2.2.14, ffprobe 2.2.14, rtmpdump 2.4
[debug] Proxy map: {}
[ThePlatform] pulse_preview: Downloading XML
ERROR: Unable to download XML: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/lib64/python3.4/site-packages/youtube_dl/extractor/common.py", line 312, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/lib64/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 1710, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib64/python3.4/urllib/request.py", line 461, in open
    response = meth(req, response)
  File "/usr/lib64/python3.4/urllib/request.py", line 571, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python3.4/urllib/request.py", line 499, in error
    return self._call_chain(*args)
  File "/usr/lib64/python3.4/urllib/request.py", line 433, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.4/urllib/request.py", line 579, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

$ youtube-dl -v 'https://player.theplatform.com/p/D6x-PC/pulse_preview/swf/select/media/yMBg9E8KFxZD'
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--restrict-filenames', '-o', '%(title)s-%(id)s-%(uploader)s.%(ext)s', '-w', '-v', 'https://player.theplatform.com/p/D6x-PC/pulse_preview/swf/select/media/yMBg9E8KFxZD']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.05.15
[debug] Python version 3.4.1 - Linux-3.18.7-x86_64-Intel-R-_Core-TM-_i5_CPU_750_@_2.67GHz
[debug] exe versions: ffmpeg 2.2.14, ffprobe 2.2.14, rtmpdump 2.4
[debug] Proxy map: {}
[ThePlatform] media: Downloading config
[ThePlatform] media: Downloading XML
[ThePlatform] media: Downloading webpage
[ThePlatform] media: Downloading f4m manifest
ERROR: An extractor error has occured. (caused by KeyError('defaultThumbnailUrl',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/youtube_dl/extractor/common.py", line 273, in extract
    return self._real_extract(url)
  File "/usr/lib64/python3.4/site-packages/youtube_dl/extractor/theplatform.py", line 193, in _real_extract
    'thumbnail': info['defaultThumbnailUrl'],
KeyError: 'defaultThumbnailUrl'
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/youtube_dl/extractor/common.py", line 273, in extract
    return self._real_extract(url)
  File "/usr/lib64/python3.4/site-packages/youtube_dl/extractor/theplatform.py", line 193, in _real_extract
    'thumbnail': info['defaultThumbnailUrl'],
KeyError: 'defaultThumbnailUrl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 649, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib64/python3.4/site-packages/youtube_dl/extractor/common.py", line 279, in extract
    raise ExtractorError('An extractor error has occured.', cause=e)
youtube_dl.utils.ExtractorError: An extractor error has occured. (caused by KeyError('defaultThumbnailUrl',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
Will be fixed in the next version. Thanks for the report.
