### ISSUE TITLE
Theplatform video download error

### ISSUE THREAD

**Issue by MaryCoding** [rg3/youtube-dl#5770]
Hi, I am currently trying to download a video from http://link.theplatform.com/s/BKQ29B/ze9gOQjAwlxQ/file.mp4?mbr=true&switch=http&feed=Fox%20Sports%20All%20-%20Mobile&metafile=false but the application returns `ERROR: unable to download video data: HTTP Error 403: Forbidden` . I am aware that `theplatform` is supported by `youtubedl` but not sure of this specific behavior. 

```
youtube-dl -v -o  "/media/%(title)s.%(ext)s" http://link.theplatform.com/s/BKQ29B/ze9gOQjAwlxQ/file.mp4?mbr=true&switch=http&feed=Fox%20Sports%20All%20-%20Mobile&metafile=false
[1] 12447
[2] 12448
[3] 12449
root@bullseye2346:~# [debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'-o', u'/media/%(title)s.%(ext)s', u'http://link.theplatform.com/s/BKQ29B/ze9gOQjAwlxQ/file.mp4?mbr=true']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.05.20
[debug] Python version 2.7.9 - Linux-3.19.0-16-generic-x86_64-with-Ubuntu-15.04-vivid
[debug] exe versions: rtmpdump 2.4
[debug] Proxy map: {}
[ThePlatform] ze9gOQjAwlxQ: Downloading XML
[ThePlatform] ze9gOQjAwlxQ: Downloading webpage
[debug] Invoking downloader on 'http://fsvideohds-vh.akamaihd.net/z/video/Fox_Sports_Production/691/315/4_b_150520_fsmw_wachacohen_web_2500.mp4?hdnea=st=1432188222~exp=1432188552~acl=/z/video/Fox_Sports_Production/691/315/4_b_150520_fsmw_wachacohen_web_*~id=220a1c87-89aa-4f27-aa99-3a119cef2959~hmac=7ba58851c288be948471d4fc1339c0d2db7282146e93653c7b3f2a22c9a752af'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1419, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1361, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 342, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 59, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1712, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden
```

**Comment by jaimeMF** [comment]
Post the url where the original videos is, it can help us.

Two notes:
1. You have to quote the url if it contains `&`, see [this for more info](https://github.com/rg3/youtube-dl/blob/50b901306406d5c37f31880860e2a4dbb5e0a165/README.md#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command).
2. **Don't run youtube-dl** as root. We try to do our best to make youtube-dl secure, but we may make mistakes (or some options you use may be insecure), and in general you should only run programs as root when it's really required.

**Comment by MaryCoding** [comment]
Hi @jaimeMF I tried your suggestions with the quotes and ran youtube-dl not in root. Those suggestion pointed out didnt work. These links come from the foxsports mobile app xml rss feed found here: http://feed.theplatform.com/f/BKQ29B/fs-mobile-top-news-video
