### ISSUE TITLE
[RUTV] Live streams not works - Unsupported URL

### ISSUE THREAD

**Issue by spvkgn** [rg3/youtube-dl#5782]
Streams did work a few days ago and now this issue occurs. Can you please fix the issue ?
```
~ $ youtube-dl -v http://live.russia.tv/index/index/channel_id/3
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://live.russia.tv/index/index/channel_id/3']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.05.20
[debug] Python version 2.7.3 - Linux-3.2.0-79-generic-pae-i686-with-LinuxMint-13-maya
[debug] exe versions: ffmpeg 2.5.3-7, ffprobe 2.5.3-7, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 3: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 3: Downloading webpage
[generic] 3: Extracting information
ERROR: Unsupported URL: http://live.russia.tv/index/index/channel_id/3
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 969, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1558, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1301, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1643, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1507, in _raiseerror
    raise err
ParseError: mismatched tag: line 24, column 2
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 649, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 273, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1504, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://live.russia.tv/index/index/channel_id/3
```

**Comment by dstftw** [comment]
Will be fixed in the next version. Thanks for the report.
