### ISSUE TITLE
site support request: pinkbike.com

### ISSUE THREAD

**Issue by privong** [rg3/youtube-dl#5791]
```
$ youtube-dl --version
2015.05.15
```
```
$ youtube-dl -v http://www.pinkbike.com/video/408888/
[debug] System config: []
[debug] User config: ['--console-title']
[debug] Command-line args: ['-v', 'http://www.pinkbike.com/video/408888/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.05.15
[debug] Python version 3.4.3 - Linux-4.0.4-2-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 2.6.3, ffprobe 2.6.3, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 408888: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 408888: Downloading webpage
[generic] 408888: Extracting information
ERROR: Unsupported URL: http://www.pinkbike.com/video/408888/
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 649, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 273, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/generic.py", line 1467, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.pinkbike.com/video/408888/
```

**Comment by misterhat** [comment]
The video you linked needs a password. Do you mind giving a video link along with its password?

**Comment by privong** [comment]
@misterhat Interesting. It didn't need one when I first loaded the page in Google Chrome and tried to download it with youtube-dl. Unfortunately I do not have a password for it.

Here's an alternate URL for the site, which appears to be password free: http://www.pinkbike.com/video/408457/

**Comment by jaimeMF** [comment]
It should work with the changes in #5807.

**Comment by dstftw** [comment]
Reopening. Password protected videos are not supported yet.

**Comment by misterhat** [comment]
If somebody can find me a password protected link with the password I'd be willing to implement it.
