### ISSUE TITLE
--download-archive compatibility issue with --embed-thumbnail when no thumbnail exists

### ISSUE THREAD

**Issue by gak1234** [rg3/youtube-dl#5797]
I found an interesting condition just now.  When downloading a SoundCloud track that does not have a thumbnail, the track ID will not be written to the archive.txt even though the track was downloaded successfully.

Verbose output:
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', '--embed-thumbnail', '--download-archive', 'archive.txt', '-w', '-i', 'https://soundcloud.com/user4428730/test-upload']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2015.05.20
[debug] Python version 3.4.3 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-70875-g3c5c687
[debug] Proxy map: {}
ERROR: Thumbnail was not found. Nothing to do.
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\youtube_dl\YoutubeDL.py", line 1531, in post_process
    files_to_delete, info = pp.run(info)
  File "C:\Python34\lib\site-packages\youtube_dl\postprocessor\embedthumbnail.py", line 34, in run
    raise EmbedThumbnailPPError('Thumbnail was not found. Nothing to do.')
youtube_dl.postprocessor.embedthumbnail.EmbedThumbnailPPError: Thumbnail was not found. Nothing to do.

ERROR: local variable 'files_to_delete' referenced before assignment
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\youtube_dl\YoutubeDL.py", line 660, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Python34\lib\site-packages\youtube_dl\YoutubeDL.py", line 706, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "C:\Python34\lib\site-packages\youtube_dl\YoutubeDL.py", line 1157, in process_video_result
    self.process_info(new_info)
  File "C:\Python34\lib\site-packages\youtube_dl\YoutubeDL.py", line 1469, in process_info
    self.post_process(filename, info_dict)
  File "C:\Python34\lib\site-packages\youtube_dl\YoutubeDL.py", line 1534, in post_process
    if files_to_delete and not self.params.get('keepvideo', False):
UnboundLocalError: local variable 'files_to_delete' referenced before assignment

**Comment by dstftw** [comment]
Will be fixed in the next version. Thanks for the report.
By the way this issue is not anyhow related to `--download-archive`.
