### ISSUE TITLE
No luck on RTBF

### ISSUE THREAD

**Issue by Fil** [rg3/youtube-dl#5803]
```
$ youtube-dl -U
youtube-dl is up-to-date (2015.05.20)

$ youtube-dl http://www.rtbf.be/video/detail_tout-ca-13-11-jade-et-arnaud-lagardere-million-dirham-baby?id=1775590 --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://www.rtbf.be/video/detail_tout-ca-13-11-jade-et-arnaud-lagardere-million-dirham-baby?id=1775590', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.05.20
[debug] Python version 2.7.9 - Darwin-14.3.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.6.1, ffprobe 2.6.1, rtmpdump 2.4
[debug] Proxy map: {}
[RTBF] 1775590: Downloading webpage
ERROR: Unable to extract data video; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 649, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 273, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/rtbf.py", line 33, in _real_extract
    r'<div class="js-player-embed(?: player-embed)?" data-video="([^"]+)"', page, 'data video'))['data']
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 564, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 555, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract data video; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

**Comment by Fil** [comment]
works! thx!
