### ISSUE TITLE
WARNING: [youtube] mUTtmdb4TCs: Skipping DASH manifest:

### ISSUE THREAD

**Issue by jd1008** [rg3/youtube-dl#5817]
$ rpm -q youtube-dl
youtube-dl-2015.05.10-1.fc21.noarch

Ran the command (ytdl is my alias for youtube-dl)

ytdl -cktli 'https://www.youtube.com/playlist?list=PLMm42O4YsWPMkniN22_uu7xOUyBDUxyvo'
.
.
.
[download] Downloading video 2 of 11
[youtube] mUTtmdb4TCs: Downloading webpage
[youtube] mUTtmdb4TCs: Extracting video information
[youtube] mUTtmdb4TCs: Downloading js player en_US-vflugm_Hi
WARNING: [youtube] mUTtmdb4TCs: Skipping DASH manifest: ExtractorError(u'Signature extraction failed: Traceback (most recent call last):\n  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 653, in _decrypt_signature\n    video_id, player_url, s\n  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 580, in _extract_signature_function\n    cache_res = res(test_string)\n  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 632, in <lambda>\n    return lambda s: initial_function([s])\n  File "/usr/lib/python2.7/site-packages/youtube_dl/jsinterp.py", line 254, in resf\n    res, abort = self.interpret_statement(stmt, local_vars)\n  File "/usr/lib/python2.7/site-packages/youtube_dl/jsinterp.py", line 55, in interpret_statement\n    v = self.interpret_expression(expr, local_vars, allow_recursion)\n  File "/usr/lib/python2.7/site-packages/youtube_dl/jsinterp.py", line 174, in interpret_expression\n    return obj[member](argvals)\n  File "/usr/lib/python2.7/site-packages/youtube_dl/jsinterp.py", line 254, in resf\n    res, abort = self.interpret_statement(stmt, local_vars)\n  File "/usr/lib/python2.7/site-packages/youtube_dl/jsinterp.py", line 55, in interpret_statement\n    v = self.interpret_expression(expr, local_vars, allow_recursion)\n  File "/usr/lib/python2.7/site-packages/youtube_dl/jsinterp.py", line 99, in interpret_expression\n    cur = lvar[idx]\nIndexError: list index out of range\n (caused by IndexError(\'list index out of range\',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
[download] Destination: Amis Raynaut-mUTtmdb4TCs.f248.webm
[download] 100% of 16.73MiB in 00:39
[download] Destination: Amis Raynaut-mUTtmdb4TCs.f171.webm
[download] 100% of 3.41MiB in 00:07
[ffmpeg] Merging formats into "Amis Raynaut-mUTtmdb4TCs.webm"
ERROR: Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
ERROR: local variable 'files_to_delete' referenced before assignment

**Comment by jd1008** [comment]
another error on same command, for track 11

[download] Downloading video 11 of 11
[youtube] iHKONqeNmV8: Downloading webpage
[youtube] iHKONqeNmV8: Extracting video information
[youtube] iHKONqeNmV8: Downloading js player en_US-vflugm_Hi
WARNING: [youtube] iHKONqeNmV8: Skipping DASH manifest: ExtractorError(u'Signature extraction failed: Traceback (most recent call last):\n  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 653, in _decrypt_signature\n    video_id, player_url, s\n  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 580, in _extract_signature_function\n    cache_res = res(test_string)\n  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 632, in <lambda>\n    return lambda s: initial_function([s])\n  File "/usr/lib/python2.7/site-packages/youtube_dl/jsinterp.py", line 254, in resf\n    res, abort = self.interpret_statement(stmt, local_vars)\n  File "/usr/lib/python2.7/site-packages/youtube_dl/jsinterp.py", line 55, in interpret_statement\n    v = self.interpret_expression(expr, local_vars, allow_recursion)\n  File "/usr/lib/python2.7/site-packages/youtube_dl/jsinterp.py", line 174, in interpret_expression\n    return obj[member](argvals)\n  File "/usr/lib/python2.7/site-packages/youtube_dl/jsinterp.py", line 254, in resf\n    res, abort = self.interpret_statement(stmt, local_vars)\n  File "/usr/lib/python2.7/site-packages/youtube_dl/jsinterp.py", line 55, in interpret_statement\n    v = self.interpret_expression(expr, local_vars, allow_recursion)\n  File "/usr/lib/python2.7/site-packages/youtube_dl/jsinterp.py", line 99, in interpret_expression\n    cur = lvar[idx]\nIndexError: list index out of range\n (caused by IndexError(\'list index out of range\',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
[download] Destination: Silver Swan-iHKONqeNmV8.f137.mp4
[download] 100% of 10.71MiB in 01:43
[download] Destination: Silver Swan-iHKONqeNmV8.f140.m4a
[download] 100% of 4.55MiB in 00:55
[ffmpeg] Merging formats into "Silver Swan-iHKONqeNmV8.mp4"
