### ISSUE TITLE
TF1 extractor needs update

### ISSUE THREAD

**Issue by d-robert** [rg3/youtube-dl#5819]
TF1 website has changed. extractor now fails:

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.tf1.fr/tf1/koh-lanta/videos/replay-koh-lanta-22-mai-2015.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.05.20
[debug] Python version 2.7.5 - Linux-3.12.8-desktop-2.mga4-x86_64-with-mandrake-4-Official
[debug] exe versions: ffmpeg 2.0.6, ffprobe 2.0.6
[debug] Proxy map: {}
[generic] replay-koh-lanta-22-mai-2015: Requesting header
WARNING: Falling back on generic information extractor.
[generic] replay-koh-lanta-22-mai-2015: Downloading webpage
[generic] replay-koh-lanta-22-mai-2015: Extracting information
ERROR: Unsupported URL: http://www.tf1.fr/tf1/koh-lanta/videos/replay-koh-lanta-22-mai-2015.html
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/extractor/generic.py", line 969, in _real_extract
    doc = parse_xml(webpage)
  File "./youtube-dl/youtube_dl/utils.py", line 1558, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 19, column 580
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 649, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 273, in extract
    return self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/generic.py", line 1504, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.tf1.fr/tf1/koh-lanta/videos/replay-koh-lanta-22-mai-2015.html

**Comment by yan12125** [comment]
Thanks for the report. This URL will be supported in the next version.
