### ISSUE TITLE
Get error on some pages

### ISSUE THREAD

**Issue by Letux** [rg3/youtube-dl#5824]
HI. I use your script on my site. But sometime I get error like 

```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 405, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 395, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1486, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 649, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 273, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/pornhub.py", line 75, in _real_extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/pornhub.py", line 75, in <lambda>
  File "/usr/lib64/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xbf in position 1: invalid start byte
```
May be we need convert page content to UTF string before use?

**Comment by dstftw** [comment]
Post the **full** output of youtube-dl when run [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by Letux** [comment]
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--dump-json', u'http://www.pornhub.com/view_video.php?viewkey=bed6bca62949b265009e', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.05.20
[debug] Python version 2.7.5 - Linux-3.10.0-229.el7.x86_64-x86_64-with-centos-7.1.1503-Core
[debug] exe versions: ffmpeg 0.6.5, ffprobe 0.6.5
[debug] Proxy map: {}
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 405, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 395, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1486, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 649, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 273, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/pornhub.py", line 75, in _real_extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/pornhub.py", line 75, in <lambda>
  File "/usr/lib64/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x9e in position 0: invalid start byte
```
