### ISSUE TITLE
Failing to handle the newest encrypted signatures YouTube is using for Vevo

### ISSUE THREAD

**Issue by ssokolow** [rg3/youtube-dl#5845]
I just updated to version 2015.05.20 via `youtube-dl -U` and this video still fails to download:

http://www.youtube.com/watch?v=ZTidn2dBYbY

```
[youtube] Setting language
[youtube] ZTidn2dBYbY: Downloading webpage
[youtube] ZTidn2dBYbY: Downloading video info webpage
[youtube] ZTidn2dBYbY: Extracting video information
[youtube] ZTidn2dBYbY: Encrypted signatures detected.
[youtube] ZTidn2dBYbY: Downloading js player new
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 479, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 383, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 454, in _parse_sig_js
    u'Initial JS player signature function name')
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 391, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
```

**Comment by yan12125** [comment]
Can you add the ```--write-pages``` option and upload/paste all *.dump files? For example:
```
youtube-dl --write-pages --verbose "http://www.youtube.com/watch?v=ZTidn2dBYbY"
```

**Comment by ssokolow** [comment]
...and now it's working, even when I run the exact same command as before. Must be something transient on YouTube's end. Should I just close this?

**Comment by yan12125** [comment]
Please close it. If anyone is in the same trouble, open a new issue.
