### ISSUE TITLE
TF1 support broken

### ISSUE THREAD

**Issue by maxliem** [rg3/youtube-dl#5848]
Hi
URL Header of TF1 replay video has been changed recently, could you help to reactivate ? Thanks

youtube-dl http://lci.tf1.fr/sept-a-huit/videos/sept-a-huit-du-24-mai-2015-8611550.html -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://lci.tf1.fr/sept-a-huit/videos/sept-a-huit-du-24-mai-2015-8611550.html', u'-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.05.20
[debug] Python version 2.7.6 - Darwin-14.3.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[generic] sept-a-huit-du-24-mai-2015-8611550: Requesting header
WARNING: Falling back on generic information extractor.
[generic] sept-a-huit-du-24-mai-2015-8611550: Downloading webpage
[generic] sept-a-huit-du-24-mai-2015-8611550: Extracting information
ERROR: Unsupported URL: http://lci.tf1.fr/sept-a-huit/videos/sept-a-huit-du-24-mai-2015-8611550.html
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 969, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1558, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: undefined entity: line 9, column 138
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 649, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 273, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1504, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://lci.tf1.fr/sept-a-huit/videos/sept-a-huit-du-24-mai-2015-8611550.html

**Comment by dstftw** [comment]
Wil be fixed in the next version. Thanks for the report.

**Comment by maxliem** [comment]
thx vm
