### ISSUE TITLE
Download age restricted video from naver

### ISSUE THREAD

**Issue by renuka25165** [rg3/youtube-dl#5857]
How to download video from this url? http://tvcast.naver.com/v/406354
The video is age restricted. Is there anyway to download this video?

C:\Users\Jaimin>youtube-dl http://tvcast.naver.com/v/406354 --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://tvcast.naver.com/v/406354', u'--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.04.09
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-64626-gca671be, ffprobe N-64626-gca671be
[debug] Proxy map: {}
[Naver] 406354: Downloading webpage
ERROR: couldn't extract vid and key; please report this issue on https://yt-dl.o
rg/bug . Make sure you are using the latest version; type  youtube-dl -U  to upd
ate. Be sure to call youtube-dl with the --verbose flag and include its complete
 output.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 651, in extract_info
  File "youtube_dl\extractor\common.pyo", line 275, in extract
  File "youtube_dl\extractor\naver.pyo", line 42, in _real_extract
ExtractorError: couldn't extract vid and key; please report this issue on https:
//yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -
U  to update. Be sure to call youtube-dl with the --verbose flag and include its
 complete output.

**Comment by renuka25165** [comment]
Its been 4 days. any updates?
