### ISSUE TITLE
Patreon: ERROR: Unable to extract playlist JSON

### ISSUE THREAD

**Issue by Hello71** [rg3/youtube-dl#5862]
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['https://www.patreon.com/creation?hid=2518042', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.05.29
[debug] Python version 3.4.3 - Linux-4.1.0-rc5+-x86_64-Intel-R-_Core-TM-_i5_CPU_750_@_2.67GHz-with-gentoo-2.2
[debug] exe versions: ffmpeg 2.6.2, ffprobe 2.6.2
[debug] Proxy map: {}
[Patreon] 2518042: Downloading webpage
ERROR: Unable to extract playlist JSON; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 649, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib64/python3.4/site-packages/youtube_dl/extractor/common.py", line 273, in extract
    return self._real_extract(url)
  File "/usr/lib64/python3.4/site-packages/youtube_dl/extractor/patreon.py", line 103, in _real_extract
    webpage, 'playlist JSON'),
  File "/usr/lib64/python3.4/site-packages/youtube_dl/extractor/common.py", line 555, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract playlist JSON; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by dstftw** [comment]
Will be fixed in the next version. Thanks for the report.
