### ISSUE TITLE
Aftonbladet no longer works

### ISSUE THREAD

**Issue by kuken2** [rg3/youtube-dl#5863]
python test/test_download.py TestDownload.test_Aftonbladet returns 
[Aftonbladet] article36015: Downloading webpage
ERROR: Unable to extract internal_meta_id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/jacob/Videos/youtube-dl/youtube_dl/YoutubeDL.py", line 650, in extract_info
    ie_result = ie.extract(url)
  File "/home/jacob/Videos/youtube-dl/youtube_dl/extractor/common.py", line 273, in extract
    return self._real_extract(url)
  File "/home/jacob/Videos/youtube-dl/youtube_dl/extractor/aftonbladet.py", line 29, in _real_extract
    r'data-aptomaId="([\w\d]+)"', webpage, 'internal_meta_id')
  File "/home/jacob/Videos/youtube-dl/youtube_dl/extractor/common.py", line 564, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/home/jacob/Videos/youtube-dl/youtube_dl/extractor/common.py", line 555, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract internal_meta_id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

E
======================================================================
ERROR: test_Aftonbladet (__main__.TestDownload)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_download.py", line 139, in test_template
    res_dict = ydl.extract_info(test_case['url'])
  File "/home/jacob/Videos/youtube-dl/youtube_dl/YoutubeDL.py", line 665, in extract_info
    self.report_error(compat_str(de), de.format_traceback())
  File "/home/jacob/Videos/youtube-dl/youtube_dl/YoutubeDL.py", line 528, in report_error
    self.trouble(error_message, tb)
  File "/home/jacob/Videos/youtube-dl/youtube_dl/YoutubeDL.py", line 498, in trouble
    raise DownloadError(message, exc_info)
DownloadError: ERROR: Unable to extract internal_meta_id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

----------------------------------------------------------------------
Ran 1 test in 0.530s

FAILED (errors=1)

I'm not a programmer but I know that their URLs have changed format.

**Comment by naglis** [comment]
Thanks for the report. This issue should be fixed in the next release of youtube-dl.
