### ISSUE TITLE
RegexNotFoundError: Unable to extract Initial JS player signature function name

### ISSUE THREAD

**Issue by moisespsena** [rg3/youtube-dl#5865]
youtube-dl -v -t 'https://www.youtube.com/watch?v=yyR8cwK_9z8'
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', '-t', 'https://www.youtube.com/watch?v=yyR8cwK_9z8']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.09.14.3
[debug] Python version 2.7.9 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.0
[debug] Proxy map: {}
[youtube] Setting language
[youtube] Confirming age
[youtube] yyR8cwK_9z8: Downloading webpage
[youtube] yyR8cwK_9z8: Downloading video info webpage
[youtube] yyR8cwK_9z8: Extracting video information
[youtube] yyR8cwK_9z8: Encrypted signatures detected.
[youtube] {43} signature length 42.44, html5 player en_US-vflE8_7k0
[youtube] yyR8cwK_9z8: Downloading js player vflE8_7k0
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/home/moi/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 527, in _decrypt_signature
    video_id, player_url, s
  File "/home/moi/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 441, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/home/moi/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 502, in _parse_sig_js
    'Initial JS player signature function name')
  File "/home/moi/bin/youtube-dl/youtube_dl/extractor/common.py", line 399, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/home/moi/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 527, in _decrypt_signature
    video_id, player_url, s
  File "/home/moi/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 441, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/home/moi/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 502, in _parse_sig_js
    'Initial JS player signature function name')
  File "/home/moi/bin/youtube-dl/youtube_dl/extractor/common.py", line 399, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/home/moi/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 523, in extract_info
    ie_result = ie.extract(url)
  File "/home/moi/bin/youtube-dl/youtube_dl/extractor/common.py", line 178, in extract
    return self._real_extract(url)
  File "/home/moi/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 912, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/home/moi/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 537, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/home/moi/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 527, in _decrypt_signature
    video_id, player_url, s
  File "/home/moi/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 441, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/home/moi/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 502, in _parse_sig_js
    'Initial JS player signature function name')
  File "/home/moi/bin/youtube-dl/youtube_dl/extractor/common.py", line 399, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by jaimeMF** [comment]
You are using an outdated version, [you have to upgrade to a newer one](https://github.com/rg3/youtube-dl/blob/eb6cb9fbe934fe99a35af22065cf91063d416c12/README.md#how-do-i-update-youtube-dl).
