### ISSUE TITLE
ERROR: ffmpeg: unrecognized option '-c'

### ISSUE THREAD

**Issue by wuhaa11** [rg3/youtube-dl#5887]
Hi,

When downloading from youtube (not sure if it does same for other sites), I am unable to get a merged audio/video file. Can someone plaese help. FFMPEG does not like the -c option in this line:

```
[debug] ffmpeg command line: ffmpeg -y -i 'Through The Wormhole S04E05 Will Sex Become Extinct-0bHtB1SXorw.f136.mp4' -i 'Through The Wormhole S04E05 Will Sex Become Extinct-0bHtB1SXorw.f141.m4a' -c copy -map 0:v:0 -map 1:a:0 'Through The Wormhole S04E05 Will Sex Become Extinct-0bHtB1SXorw.temp.mp4'
```

Here are more details:

OS:
Ubuntu 10.04.4 LTS lucid
Linux server 3.0.0-32-generic i686 GNU/Linux

```
$ youtube-dl -v 0bHtB1SXorw
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'0bHtB1SXorw']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.05.20
[debug] Python version 2.6.5 - Linux-3.0.0-32-generic-i686-with-Ubuntu-10.04-lucid
[debug] exe versions: ffmpeg SVN-r0.5.9-4
[debug] Proxy map: {}
[youtube] 0bHtB1SXorw: Downloading webpage
[youtube] 0bHtB1SXorw: Extracting video information
[youtube] 0bHtB1SXorw: Downloading DASH manifest
[debug] Invoking downloader on 'https://r8---sn-tt17dn7r.googlevideo.com/videoplayback?id=d1b1ed075497a2bc&itag=136&source=youtube&requiressl=yes&mv=m&ms=au&pl=22&mm=31&ratebypass=yes&mime=video/mp4&gir=yes&clen=531696159&lmt=1430628550285410&dur=3026.633&key=dg_yt0&mt=1433346375&sver=3&fexp=916723,9405976,9406712,9407991,9408142,9408420,9408710,9408807,9408863,9409207,9412839,9413503,9414611,9415299,9415304,9415436,9415488,9415516&upn=vlXO-XPlgy8&signature=509BFB752CC87C15722539AB238829965065491E.965F26DABAEAAB6F012BE3992B67B77237B3678D&ip=67.55.0.202&ipbits=0&expire=1433368027&sparams=ip,ipbits,expire,id,itag,source,requiressl,mv,ms,pl,mm,ratebypass,mime,gir,clen,lmt,dur'
[download] Through The Wormhole S04E05 Will Sex Become Extinct-0bHtB1SXorw.f136.mp4 has already been downloaded
[download] 100% of 507.06MiB
[debug] Invoking downloader on 'https://r8---sn-tt17dn7r.googlevideo.com/videoplayback?id=d1b1ed075497a2bc&itag=141&source=youtube&requiressl=yes&mv=m&ms=au&pl=22&mm=31&ratebypass=yes&mime=audio/mp4&gir=yes&clen=97018331&lmt=1430628231582121&dur=3026.698&key=dg_yt0&mt=1433346375&sver=3&fexp=916723,9405976,9406712,9407991,9408142,9408420,9408710,9408807,9408863,9409207,9412839,9413503,9414611,9415299,9415304,9415436,9415488,9415516&upn=vlXO-XPlgy8&signature=3DA95CC9249C51146963149FDF07E47F698F3AC9.6D45B10543BB312A513BCE0717AE4CE9940186F5&ip=67.55.0.202&ipbits=0&expire=1433368027&sparams=ip,ipbits,expire,id,itag,source,requiressl,mv,ms,pl,mm,ratebypass,mime,gir,clen,lmt,dur'
[download] Through The Wormhole S04E05 Will Sex Become Extinct-0bHtB1SXorw.f141.m4a has already been downloaded
[download] 100% of 92.52MiB
[ffmpeg] Merging formats into "Through The Wormhole S04E05 Will Sex Become Extinct-0bHtB1SXorw.mp4"
[debug] ffmpeg command line: ffmpeg -y -i 'Through The Wormhole S04E05 Will Sex Become Extinct-0bHtB1SXorw.f136.mp4' -i 'Through The Wormhole S04E05 Will Sex Become Extinct-0bHtB1SXorw.f141.m4a' -c copy -map 0:v:0 -map 1:a:0 'Through The Wormhole S04E05 Will Sex Become Extinct-0bHtB1SXorw.temp.mp4'
ERROR: ffmpeg: unrecognized option '-c'
Traceback (most recent call last):
  File "./ytd/youtube_dl/YoutubeDL.py", line 1531, in post_process
    files_to_delete, info = pp.run(info)
  File "./ytd/youtube_dl/postprocessor/ffmpeg.py", line 590, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "./ytd/youtube_dl/postprocessor/ffmpeg.py", line 148, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
FFmpegPostProcessorError
```

**Comment by dstftw** [comment]
Update ffmpeg,
