### ISSUE TITLE
Please add support for Colbertlateshow.com

### ISSUE THREAD

**Issue by Raradra** [rg3/youtube-dl#5888]
Example URL:
http://colbertlateshow.com/video/8GmB0oY0McANFvp2aEffk9jZZZ2YyXxy/the-colbeard/

```
youtube-dl -v "http://colbertlateshow.com/video/8GmB0oY0McANFvp2aEffk9jZZZ2YyXxy/the-colbeard/"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://colbertlateshow.com/video/8GmB0oY0McANFvp2aEffk9jZZZ2YyXxy/the-colbeard/']
[debug] Encodings: locale cp1250, fs mbcs, out cp852, pref cp1250
[debug] youtube-dl version 2015.05.20
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-65971-g4c92047, rtmpdump 2.4
[debug] Proxy map: {}
[generic] the-colbeard: Requesting header
WARNING: Falling back on generic information extractor.
[generic] the-colbeard: Downloading webpage
[generic] the-colbeard: Extracting information
ERROR: Unsupported URL: http://colbertlateshow.com/video/8GmB0oY0McANFvp2aEffk9jZZZ2YyXxy/the-colbeard/
Traceback (most recent call last):
  File "youtube_dl\extractor\generic.pyo", line 969, in _real_extract
  File "youtube_dl\utils.pyo", line 1558, in parse_xml
  File "xml\etree\ElementTree.pyo", line 1300, in XML
  File "xml\etree\ElementTree.pyo", line 1642, in feed
  File "xml\etree\ElementTree.pyo", line 1506, in _raiseerror
ParseError: mismatched tag: line 151, column 2
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 649, in extract_info
  File "youtube_dl\extractor\common.pyo", line 273, in extract
  File "youtube_dl\extractor\generic.pyo", line 1504, in _real_extract
UnsupportedError: Unsupported URL: http://colbertlateshow.com/video/8GmB0oY0McANFvp2aEffk9jZZZ2YyXxy/the-colbeard/
```

Site was created by the CBS, so I assume it uses same video platform.

**Comment by dstftw** [comment]
colbertlateshow will be supported in the next version. Thanks for the report.
