### ISSUE TITLE
Tube8.com support broken

### ISSUE THREAD

**Issue by floresbarnett** [rg3/youtube-dl#5890]
With latest 5/20 and 5/29 versions.

ERROR: Unable to extract flashvars; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 649, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 273, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/tube8.py", line 50, in _real_extract
    r'var flashvars\s*=\s*({.+?})', webpage, 'flashvars'))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 564, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 555, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract flashvars; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by naglis** [comment]
Please include [the full output](https://github.com/rg3/youtube-dl#bugs) of youtube-dl when run with `-v`.

**Comment by floresbarnett** [comment]
The traceback above is what appears only when -v is included. Do try it with any item on tube8.com

**Comment by naglis** [comment]
The traceback is missing the URL you've used. I'm asking because the test passes ok for me.

**Comment by dstftw** [comment]
This issue is already fixed in 6ebdfe43e439239df051f6071a23c51705c150cf and will be included in the next release.
