### ISSUE TITLE
probem with History

### ISSUE THREAD

**Issue by 2011** [rg3/youtube-dl#5893]
```
youtube-dl -v 'http://www.history.com/shows/engineering-disasters/videos/raging-rocket'
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.history.com/shows/engineering-disasters/videos/raging-rocket']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.05.20
[debug] Python version 3.4.1 - Linux-3.18.7-gentoo-x86_64-Intel-R-_Core-TM-_i5_CPU_750_@_2.67GHz-with-gentoo-2.2
[debug] exe versions: ffmpeg 2.2.14, ffprobe 2.2.14, rtmpdump 2.4
[debug] Proxy map: {}
[History] raging-rocket: Downloading webpage
[ThePlatform] dX9JRjjp0Mnv: Downloading XML
[ThePlatform] dX9JRjjp0Mnv: Downloading webpage
Traceback (most recent call last):
  File "/usr/bin/youtube-dl", line 6, in <module>
    youtube_dl.main()
  File "/usr/lib64/python3.4/site-packages/youtube_dl/__init__.py", line 405, in main
    _real_main(argv)
  File "/usr/lib64/python3.4/site-packages/youtube_dl/__init__.py", line 395, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/lib64/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 1486, in download
    res = self.extract_info(url)
  File "/usr/lib64/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 660, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib64/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 713, in process_ie_result
    extra_info=extra_info)
  File "/usr/lib64/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 649, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib64/python3.4/site-packages/youtube_dl/extractor/common.py", line 273, in extract
    return self._real_extract(url)
  File "/usr/lib64/python3.4/site-packages/youtube_dl/extractor/theplatform.py", line 173, in _real_extract
    for f in switch.findall(_x('smil:video')):
AttributeError: 'NoneType' object has no attribute 'findall'
```

**Comment by dstftw** [comment]
This video can be viewed when you log in with your TV provider that is currently not supported.

**Comment by 2011** [comment]
Obviously, that would be a great feature, :) but no traceback (and more informative error messages) might be worthwhile in the short term (there are probably a lot of sites that require logins for at least some videos, and the extractors ought to recognize when it is required).

**Comment by remitamine** [comment]
i added support only for DirecTV provider, it can be used with AENetwork extractors and National Geographic.
