### ISSUE TITLE
"Unable to extract video info" error on discovery.com / brightcove.com

### ISSUE THREAD

**Issue by l0b0** [rg3/youtube-dl#5898]
With the latest version:

```shell
$ youtube-dl --verbose 'http://www.discovery.com/tv-shows/mythbusters/videos/mythbusters-the-simpsons/'
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.discovery.com/tv-shows/mythbusters/videos/mythbusters-the-simpsons/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.05.20
[debug] Python version 3.4.3 - Linux-4.0.4-2-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 2.6.3, ffprobe 2.6.3, rtmpdump 2.4
[debug] Proxy map: {}
[Discovery] mythbusters-the-simpsons: Downloading webpage
ERROR: Unable to extract video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 649, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 273, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/discovery.py", line 35, in _real_extract
    webpage, 'video info'), video_id)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 555, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
$ youtube-dl --version
2015.05.20
```

The video markup:

```html
<object seamlesstabbing="undefined" class="BrightcoveExperience" id="bcExperienceObj0" data="http://c.brightcove.com/services/viewer/federated_f9?&amp;width=100%25&amp;height=100%25&amp;flashID=bcExperienceObj0&amp;bgcolor=%23000000&amp;playerID=3688727558001&amp;playerKey=AQ~~%2CAAAAAAABkyc~%2CPFOoGLfSWhZ81Y0yRvH9oSpaitgzc4BX&amp;isVid=true&amp;isUI=true&amp;dynamicStreaming=true&amp;htmlFallback=true&amp;forceHTML=&amp;showNoContentMessage=false&amp;wmode=transparent&amp;includeAPI=true&amp;templateReadyHandler=brightcove%5B%22templateReadyHandlerbcExperienceObj0%22%5D&amp;templateErrorHandler=VideoPlayer_templateErrorHandler_1433448771680&amp;autoStart=&amp;debuggerID=&amp;originalTemplateReadyHandler=VideoPlayer_templateReadyHandler_1433448771680&amp;startTime=1433448772339" type="application/x-shockwave-flash" height="100%" width="100%"><param value="always" name="allowScriptAccess"><param value="true" name="allowFullScreen"><param value="false" name="seamlessTabbing"><param value="true" name="swliveconnect"><param value="transparent" name="wmode"><param value="high" name="quality"><param value="#000000" name="bgcolor"></object>
```

**Comment by yan12125** [comment]
Thanks for the report. Discovery videos will be downloaded correctly in the next version.
