### ISSUE TITLE
Error Output for sportsnet.ca

### ISSUE THREAD

**Issue by aaronvegh** [rg3/youtube-dl#5901]
I was just checking a video embedded on sportsnet.ca to see if Youtube-DL would work. Here's the verbose output:

$ youtube-dl -g --verbose http://www.sportsnet.ca/baseball/mlb/sn-presents-russell-martin-world-citizen/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-g', u'--verbose', u'http://www.sportsnet.ca/baseball/mlb/sn-presents-russell-martin-world-citizen/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.06.04.1
[debug] Python version 2.7.3 - Darwin-14.3.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.5, ffprobe 2.5
[debug] Proxy map: {}
WARNING: Falling back on generic information extractor.
ERROR: Cannot find player ID; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 997, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1558, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1301, in XML
    parser.feed(text)
  File "/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1643, in feed
    self._raiseerror(v)
  File "/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1507, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 15, column 440
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 650, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 273, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1046, in _real_extract
    bc_urls = BrightcoveIE._extract_brightcove_urls(webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/brightcove.py", line 191, in _extract_brightcove_urls
    return list(filter(None, [cls._build_brighcove_url(m) for m in matches]))
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/brightcove.py", line 145, in _build_brighcove_url
    raise ExtractorError('Cannot find player ID')
ExtractorError: Cannot find player ID; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by yan12125** [comment]
Thanks for the report. This video will be downloaded correctly in the next version of youtube-dl.
