### ISSUE TITLE
Vimeo: [Errno 36] File name too long

### ISSUE THREAD

**Issue by juandiazq** [rg3/youtube-dl#5908]
Filesystem: EXT4
OS: Ubuntu Linux 14.04 LTS
`youtube-dl --version`: 2015.06.04.1
When I try to download a Vimeo video:

`youtube-dl --ignore-errors --restrict-filenames https://vimeo.com/80352108`

I got the following error:

`ERROR: unable to open for writing: [Errno 36] File name too long: ...`

**Comment by dstftw** [comment]
Post the **full** output of youtube-dl when run [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by juandiazq** [comment]
Command: 

`youtube-dl --verbose --ignore-errors --restrict-filenames https://vimeo.com/80352108`

Output:

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'--ignore-errors', u'--restrict-filenames', u'https://vimeo.com/80352108']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.06.04.1
[debug] Python version 2.7.6 - Linux-4.0.4-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.18-6, avprobe 9.18-6, ffmpeg 2.6.3, ffprobe 2.6.3, rtmpdump 2.4
[debug] Proxy map: {'no': 'localhost,127.0.0.0/8,::1'}
[vimeo] 80352108: Downloading webpage
[vimeo] 80352108: Extracting information
[vimeo] 80352108: Downloading webpage
[debug] Invoking downloader on u'https://pdlvimeocdn-a.akamaihd.net/19466/858/207887776.mp4?token2=1433607436_7bc3e3622d36ab86380807a519b67bb7&aksessionid=021f61e14dcae728'
ERROR: unable to open for writing: [Errno 36] File name too long: 'Oliver_Stone_-_La_historia_no_contada_de_Estados_Unidos_09_-_Bush_y_Clinton_-_El_triunfalismo_americano_y_el_nuevo_orden_mundial-80352108.mp4.part'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 155, in real_download
    (stream, tmpfilename) = sanitize_open(tmpfilename, open_mode)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 249, in sanitize_open
    stream = open(encodeFilename(filename), open_mode)
IOError: [Errno 36] File name too long: 'Oliver_Stone_-_La_historia_no_contada_de_Estados_Unidos_09_-_Bush_y_Clinton_-_El_triunfalismo_americano_y_el_nuevo_orden_mundial-80352108.mp4.part'
```

**Comment by dstftw** [comment]
Works perfectly for me under ext4. It's not even close to filesize limit (255).

**Comment by juandiazq** [comment]
I will check the ext4 mount options.

**Comment by dstftw** [comment]
What's the length of the full path you run youtube-dl in?

**Comment by juandiazq** [comment]
`/usr/local/bin/youtube-dl`

**Comment by dstftw** [comment]
I mean where you download this file.

**Comment by juandiazq** [comment]
`/home/user/Descargas/OliverStone`

**Comment by dstftw** [comment]
What's the output of `getconf NAME_MAX /home/user/Descargas/OliverStone && getconf PATH_MAX /home/user/Descargas/OliverStone`?

**Comment by juandiazq** [comment]
NAME_MAX=143
PATH_MAX=4096

I didn't mention that my /home/user folder is encrypted with ecryptfs. I've just found the answer in this bug that will not be fixed in Ubuntu: https://bugs.launchpad.net/ecryptfs/+bug/1018050. Anyway, Should the filename be truncated?

**Comment by dstftw** [comment]
`NAME_MAX=143` that's it.
Only if we truncate or shorten manually in youtube-dl before writing.

**Comment by juandiazq** [comment]
A workaround is to download in `/tmp` and then move the file to the dest folder with a shorter name or use the `youtube-dl [...] -o <filename>` option.

**Comment by nicolas-raoul** [comment]
It is not only for Vimeo, but for all services.
I sometimes get this error. I believe it is due to a Linux encrypted home. Encrypted home makes the maximum filename size much shorter.

**Comment by yuriw** [comment]
Bug is still here, running cd /tmp helped thx, but permanent fix would be very nice to have.

**Comment by someguy736** [comment]
Long path names are also a problem on Windows. Using symbolic links or juncture points is also a way to fix the issue (so you don't have to add some messy movement operation) but it makes file structures cluttered.

Please add support for longer file names or have some way to truncate all or part of the string in the options.

EXAMPLE
```
--output 'C:\longafname\look\how\long\i\keep\growing\%(uploader)s\%(title)st20\%(title)st20-%(id)s.%(ext)s'
```
Where ```t20``` is the truncate delimiter and 20 is the number of characters before the string gets truncated.

**Comment by sleeksorrow** [comment]
Since Twitter increased their char limit from 140 to 280 chars, this service is also affected when saving on eCryptfs

**Comment by comrat** [comment]
Hello everyone!
I've fix it (sort of kludge) with setting limit for output file name in my [fork](https://github.com/comrat/youtube-dl/tree/issues-5908) in corresponded branch
Hope it helps for somebody

**Comment by shillshocked** [comment]
Your fork didn't fix the problem for me.

**Comment by mbnoimi** [comment]
This bug still occurs on recent version as shown below:

```
youtube-dl -v https://www.youtube.com/watch?v=ej9z7iHbQrU&feature=em-uploademail
[1] 5323
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=ej9z7iHbQrU']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.03.10
[debug] Python version 2.7.12 (CPython) - Linux-4.10.0-38-generic-x86_64-with-LinuxMint-18.3-sylvia
[debug] exe versions: ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1
[debug] Proxy map: {}
[youtube] ej9z7iHbQrU: Downloading webpage
[youtube] ej9z7iHbQrU: Downloading video info webpage
[youtube] ej9z7iHbQrU: Extracting video information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://r4---sn-4g5ednly.googlevideo.com/videoplayback?ipbits=0&mime=video%2Fmp4&initcwndbps=425000&itag=137&fvip=6&expire=1521390146&sparams=aitags%2Cclen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&mt=1521368409&key=yt6&beids=%5B9466591%5D&gir=yes&id=o-ADC9UEeEVtJVg4JGOHO25u5BieQtDOuk3iwnRvVbgFhq&mn=sn-4g5ednly%2Csn-nv47lnls&mm=31%2C26&aitags=137&pl=22&dur=1158.040&lmt=1521368369457417&ip=195.155.234.50&ms=au%2Conr&keepalive=yes&ei=4j2uWt2PI5mZ1gLFgpXABg&mv=m&source=youtube&requiressl=yes&clen=525258987&c=WEB&signature=17C234BD72940B8314578E5E4E1562BCFFBCE296.BC887A9E49ABDB6015D36B243989EC3681C61714&ratebypass=yes'
ERROR: unable to open for writing: [Errno 36] File name too long: '\xe2\x80\xab\xd8\xa7\xd9\x84\xd8\xaf\xd9\x86\xd9\x8a\xd8\xa7 \xd8\xb1\xd9\x88\xd8\xb2\xd9\x8a _ \xd8\xad\xd9\x84\xd9\x82\xd8\xa7\xd8\xaa \xd9\x83\xd8\xa7\xd9\x85\xd9\x84\xd8\xa9 _ \xd8\xb1\xd8\xb3\xd9\x88\xd9\x85 \xd9\x85\xd8\xaa\xd8\xad\xd8\xb1\xd9\x83\xd8\xa9 \xd8\xb9\xd8\xb1\xd8\xa8\xd9\x8a\xd8\xa9 \xd9\x84\xd9\x84\xd8\xa3\xd8\xb7\xd9\x81\xd8\xa7\xd9\x84 _  SPACETOON _ \xd8\xa7\xd9\x84\xd8\xb1\xd8\xb3\xd8\xa7\xd8\xa6\xd9\x84 \xd9\x88\xd8\xa7\xd9\x84\xd8\xaf\xd8\xb9\xd9\x88\xd8\xa7\xd8\xaa-ej9z7iHbQrU.f137.mp4.part'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/downloader/http.py", line 249, in download
    ctx.tmpfilename, ctx.open_mode)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/utils.py", line 457, in sanitize_open
    stream = open(encodeFilename(filename), open_mode)
IOError: [Errno 36] File name too long: '\xe2\x80\xab\xd8\xa7\xd9\x84\xd8\xaf\xd9\x86\xd9\x8a\xd8\xa7 \xd8\xb1\xd9\x88\xd8\xb2\xd9\x8a _ \xd8\xad\xd9\x84\xd9\x82\xd8\xa7\xd8\xaa \xd9\x83\xd8\xa7\xd9\x85\xd9\x84\xd8\xa9 _ \xd8\xb1\xd8\xb3\xd9\x88\xd9\x85 \xd9\x85\xd8\xaa\xd8\xad\xd8\xb1\xd9\x83\xd8\xa9 \xd8\xb9\xd8\xb1\xd8\xa8\xd9\x8a\xd8\xa9 \xd9\x84\xd9\x84\xd8\xa3\xd8\xb7\xd9\x81\xd8\xa7\xd9\x84 _  SPACETOON _ \xd8\xa7\xd9\x84\xd8\xb1\xd8\xb3\xd8\xa7\xd8\xa6\xd9\x84 \xd9\x88\xd8\xa7\xd9\x84\xd8\xaf\xd8\xb9\xd9\x88\xd8\xa7\xd8\xaa-ej9z7iHbQrU.f137.mp4.part'

^C
[1]+  Exit 1                  youtube-dl -v https://www.youtube.com/watch?v=ej9z7iHbQrU$ 
```

**Comment by thomasrussellmurphy** [comment]
I have also recently been experiencing this with Twitter video sources. MacOS 10.14.6, downloading to `/Users/thomasrussellmurphy/Downloads`, typically. The immediate workaround is to re-run with `--id`, producing a low-informative-value output file name, but successfully acquiring the file. I can provide the most recent problem link, if necessary.

**Comment by chovy** [comment]
I want to just automatically truncate long filenames.

**Comment by chovy** [comment]
this doesnt' work: `-o '%(title)st20'`

**Comment by ajj8** [comment]
This output format fixes it: 

>-o %(title).**100**s.%(ext)s

Replace the **100** with whatever you want, a character limit of 240 works good for me. This still should be implemented in to youtube-dl, though.

**Comment by ajj8** [comment]
@chovy This output format fixes it: 

>-o %(title).**100**s-%(id)s.%(ext)s

Replace the **100** with whatever you want, a character limit of 220 works good for me on Windows. This still should be implemented in to youtube-dl, though.

**Comment by in-in** [comment]
I think the limit depends not on the number of characters, but on the number of bytes.
```sh
echo -n "one" | wc --bytes  # 3

# not latin characters
echo -n "раз" | wc --bytes  # 6
```
In my case(Linux), the limit is _255_ bytes for the entire path(filename).

**Comment by msj2** [comment]
Issue is also due to Unicode Support missing.
https://twitter.com/i/status/1249722477577564162

Steps:

1. cd /tmp
2. youtube-dl --verbose  https://twitter.com/i/status/1249722477577564162

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://twitter.com/i/status/1249722477577564162']
[debug] Encodings: **locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8**
[debug] youtube-dl version 2020.03.08
[debug] Python version 2.7.12 (CPython) - Linux-4.4.0-140-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.15, ffprobe 2.8.15
[debug] Proxy map: {}
[twitter] 1249722477577564162: Downloading guest token
[twitter] 1249722477577564162: Downloading JSON metadata
[twitter] 1249722477577564162: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://video.twimg.com/ext_tw_video/1249722345406656513/pu/vid/320x180/T0NEatsKJCrzxJSc.mp4?tag=10'
ERROR: unable to open for writing: [Errno 36] File name too long: 'Kumar Bhanu KS **### \xf0\x9f\x87\xae\xf0\x9f\x87\xb3** - Sri Sri Mahasannidhanam \xf0\x9f\x99\x8f #SringeriJagadGuru Beautifully explained in the below Upanyasa how one must use his money; please watch  Can you find anyone who is not greed for money  No man will not be greedy for money, and if he earns Rs.10, he thinks-1249722477577564162.mp4.part'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/http.py", **_line 250_**, in download
    ctx.tmpfilename, ctx.open_mode)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/utils.py", line 2046, in sanitize_open
    stream = open(encodeFilename(filename), open_mode)
**IOError: [Errno 36] File name too long**: 'Kumar Bhanu KS **\xf0\x9f\x87\xae\xf0\x9f\x87\xb3 - Sri Sri Mahasannidhanam \xf0\x9f\x99\x8f** #SringeriJagadGuru Beautifully explained in the below Upanyasa how one must use his money; please watch  Can you find anyone who is not greed for money  No man will not be greedy for money, and if he earns Rs.10, he thinks-1249722477577564162.mp4.part'

am wondering, if these could help...
1.  Encoding these to Unicode **\xf0\x9f\x87\xae\xf0\x9f\x87\xb3 - Sri Sri Mahasannidhanam \xf0\x9f\x99\x8f**
2. Renaming the output file name to have first 250 Letters & 5 digit counter

**Comment by mayeaux** [comment]
+1 for automatic truncating

**Comment by daniells** [comment]
This issue affects a large number of twitter videos as youtube-dl attempts to use the full tweet as the filename.  EXT4, NTFS, and HFS support only 255 characters per filename, but the current max-tweet is 280 characters.  

Truncating filenames to 255 characters (including extension) should fix "File name too long" in all conceivable use cases.
