### ISSUE TITLE
'NoneType' object has no attribute 'get' downloading from Instagram

### ISSUE THREAD

**Issue by ekalin** [rg3/youtube-dl#5919]
Does not happen for all users. Apparently happens when the user has lots of posts and/or it's an old account, but I can't confirm. Here's one example of a failing account:

$ ./youtube-dl --verbose https://instagram.com/rafakalimann/    
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://instagram.com/rafakalimann/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.06.04.1
[debug] Python version 2.7.10 - Linux-3.16.0-4-amd64-x86_64-with-debian-stretch-sid
[debug] exe versions: ffmpeg 2.6.3, ffprobe 2.6.3
[debug] Proxy map: {}
[instagram:user] rafakalimann: Downloading page 1 
[instagram:user] rafakalimann: Downloading page 2 
......... [similar lines, nothing else in between] ....
[instagram:user] rafakalimann: Downloading page 72 
[instagram:user] rafakalimann: Downloading page 73 
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "./youtube-dl/__main__.py", line 19, in <module>
  File "./youtube-dl/youtube_dl/__init__.py", line 405, in main
  File "./youtube-dl/youtube_dl/__init__.py", line 395, in _real_main
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 1502, in download
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 650, in extract_info
  File "./youtube-dl/youtube_dl/extractor/common.py", line 273, in extract
  File "./youtube-dl/youtube_dl/extractor/instagram.py", line 103, in _real_extract
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by yan12125** [comment]
Thanks for the report. The user's videos will be downloaded correctly in the next version.
