### ISSUE TITLE
CNET videos - extractor error

### ISSUE THREAD

**Issue by MaryCoding** [rg3/youtube-dl#5924]
I am currently trying to download a video from http://www.cnet.com/videos/whiny-pothole-tweets-at-local-government-when-hit-by-cars-tomorrow-daily-187/ but I am getting an extractor error. Thanks for the help

```
[debug] Command-line args: [u'--write-thumbnail', u'-v', u'-f[width <=? 720]', u'-o', u'/media/56527b93-d25d-44e3-b738-f989ce2e49ba.%(ext)s', u'http://www.cnet.com/videos/whiny-pothole-tweets-at-local-government-when-hit-by-cars-tomorrow-daily-187/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.05.20
[debug] Python version 2.7.9 - Linux-3.19.0-18-generic-x86_64-with-Ubuntu-15.04-vivid
[debug] exe versions: ffmpeg 2.6.git, ffprobe 2.6.git, rtmpdump 2.4
[debug] Proxy map: {}
ERROR: An extractor error has occured. (caused by KeyError(u'rtmp',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 273, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/cnet.py", line 45, in _real_extract
    vid = vdata['files']['rtmp']
KeyError: u'rtmp'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 649, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 279, in extract
    raise ExtractorError('An extractor error has occured.', cause=e)
ExtractorError: An extractor error has occured. (caused by KeyError(u'rtmp',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output
```

**Comment by yan12125** [comment]
Thanks for the report. In the next version this problem should have been fixed.
