### ISSUE TITLE
nfl.com URL falls back to generic extractor

### ISSUE THREAD

**Issue by RingoTheDog** [rg3/youtube-dl#5940]
URL: http://www.nfl.com/videos/nfl-network-top-ten/09000d5d810a6bd4/Top-10-Gutsiest-Performances-Jack-Youngblood

Output:
youtube-dl.py -v "http://www.nfl.com/videos/nfl-network-top-ten/09000d5d810a6bd4/Top-10-Gutsiest-Performances-Jack-Youngblood"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.nfl.com/videos/nfl-network-top-ten/09000d5d810a6bd4/Top-10-Gutsiest-Performances-Jack-Youngblood']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.06.04.1
[debug] Python version 2.7.5 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-71727-g46778ab, rtmpdump 2.4
[debug] Proxy map: {}
[generic] Top-10-Gutsiest-Performances-Jack-Youngblood: Requesting header
WARNING: Falling back on generic information extractor.
[generic] Top-10-Gutsiest-Performances-Jack-Youngblood: Downloading webpage
[generic] Top-10-Gutsiest-Performances-Jack-Youngblood: Extracting information
ERROR: Unsupported URL: http://www.nfl.com/videos/nfl-network-top-ten/09000d5d810a6bd4/Top-10-Gutsiest-Performances-Jack-Youngblood
Traceback (most recent call last):
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\generic.py", line 997, in _real_extract
    doc = parse_xml(webpage)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\utils.py", line 1558, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 60, column 22
Traceback (most recent call last):
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 650, in extract_info
    ie_result = ie.extract(url)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\common.py", line 273, in extract
    return self._real_extract(url)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\generic.py", line 1532, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.nfl.com/videos/nfl-network-top-ten/09000d5d810a6bd4/Top-10-Gutsiest-Performances-Jack-Youngblood

Thanks
Ringo

**Comment by yan12125** [comment]
Thanks for the report. This URL is recognized now.
