### ISSUE TITLE
support downloading cbc.ca audio/radio player 

### ISSUE THREAD

**Issue by ivar** [rg3/youtube-dl#5944]
I'd be very grateful if youtube-dl supported downloading the audio from their player URLs
ie: `http://www.cbc.ca/radio/popup/audio/player.html?autoPlay=true&clipIds=2668959997`

verbose log: 
```
➜  ~ youtube-dl -U
youtube-dl is up-to-date (2015.06.04.1)
➜  ~ youtube-dl -v "http://www.cbc.ca/radio/popup/audio/player.html?autoPlay=true&clipIds=2668959997"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.cbc.ca/radio/popup/audio/player.html?autoPlay=true&clipIds=2668959997']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.06.04.1
[debug] Python version 2.7.10 - Darwin-14.3.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.6.3, ffprobe 2.6.3, rtmpdump 2.4
[debug] Proxy map: {}
[generic] player: Requesting header
WARNING: Falling back on generic information extractor.
[generic] player: Downloading webpage
[generic] player: Extracting information
ERROR: Unsupported URL: http://www.cbc.ca/radio/popup/audio/player.html?autoPlay=true&clipIds=2668959997
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 997, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1558, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 44, column 124
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 650, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 273, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1532, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.cbc.ca/radio/popup/audio/player.html?autoPlay=true&clipIds=2668959997
```

**Comment by yan12125** [comment]
CBC radio should work since ad96b4c. Closing as the given example is no longer available. Please open a new issue if any problem regarding CBC radio found in youtube-dl.
