### ISSUE TITLE
No downloads from http://www.theoperaplatform.eu possible

### ISSUE THREAD

**Issue by berlincount** [rg3/youtube-dl#5974]
$ youtube-dl --verbose http://www.theoperaplatform.eu/de/opera/wagner-gotterdammerung
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.theoperaplatform.eu/de/opera/wagner-gotterdammerung']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.06.04.1
[debug] Python version 2.7.8 - Linux-3.16.0-18-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: rtmpdump 2.4
[debug] Proxy map: {}
[generic] wagner-gotterdammerung: Requesting header
WARNING: Falling back on generic information extractor.
[generic] wagner-gotterdammerung: Downloading webpage
[generic] wagner-gotterdammerung: Extracting information
ERROR: Unsupported URL: http://www.theoperaplatform.eu/de/opera/wagner-gotterdammerung
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 997, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1558, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: mismatched tag: line 90, column 2
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 650, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 273, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1532, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.theoperaplatform.eu/de/opera/wagner-gotterdammerung

**Comment by yan12125** [comment]
Superseded by #14513: Opera Platform is now OperaVision
