### ISSUE TITLE
Embedding Missing Thumbnails with AtomicParsley

### ISSUE THREAD

**Issue by Athertonius** [rg3/youtube-dl#5996]
When YouTube can't return any thumbnail through "maxresdefault", it returns a 404 which is unhandled by youtube-dl since it tries to embed a thumbnail which cannot, and has not been downloaded to the file, crashing AtomicParsley.

```
[debug] System config: []
[debug] User config: [u'--add-metadata', u'-o', u'%(upload_date)s - %(title)s.%(ext)s', u'-cf', u'bestvideo[ext=mp4][width<=1920]+bestaudio[ext=m4a]', u'--embed-thumbnail', u'--embed-subs', u'--exec', u'IFS=$n && j={} && k=`expr length $j` && l=`expr $k - 15` && notify-send "YouTube DL" --icon /usr/local/bin/icon.png "`expr substr $j 12 $l`"']
[debug] Command-line args: [u'https://www.youtube.com/playlist?list=PLARhCYccw3tb0ewDzW4eE28DNc9V_oIZE', u'-n', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.06.15
[debug] Python version 2.7.9 - Linux-3.19.0-20-generic-x86_64-with-Ubuntu-15.04-vivid
[debug] exe versions: avconv 11.2-6, avprobe 11.2-6
[debug] Proxy map: {}
[youtube:playlist] Downloading login page
[youtube:playlist] Logging in
[youtube:playlist] PLARhCYccw3tb0ewDzW4eE28DNc9V_oIZE: Downloading webpage
[download] Downloading playlist: Immediacy
[youtube:playlist] playlist Immediacy: Downloading 6 videos
[download] Downloading video 1 of 6
[youtube] Downloading login page
[youtube] Logging in
[youtube] 49srojjrd4I: Downloading webpage
[youtube] 49srojjrd4I: Extracting video information
[youtube] 49srojjrd4I: Downloading DASH manifest
[youtube] 49srojjrd4I: Downloading thumbnail ...
WARNING: Unable to download thumbnail "https://i.ytimg.com/vi/49srojjrd4I/maxresdefault.jpg": HTTP Error 404: Not Found
[download] 20150614 - Product vs Packshot  - Bloomex 3 _ The Checkout.mp4 has already been downloaded and merged
[ffmpeg] Adding metadata to '20150614 - Product vs Packshot  - Bloomex 3 _ The Checkout.mp4'
...

...
[ffmpeg] There aren't any subtitles to embed
[atomicparsley] Adding thumbnail to "20150614 - Product vs Packshot  - Bloomex 3 _ The Checkout.mp4"
[debug] AtomicParsley command line: AtomicParsley '20150614 - Product vs Packshot  - Bloomex 3 _ The Checkout.mp4' --artwork '20150614 - Product vs Packshot  - Bloomex 3 _ The Checkout.jpg' -o '20150614 - Product vs Packshot  - Bloomex 3 _ The Checkout.temp.mp4'
ERROR: 
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1548, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/embedthumbnail.py", line 73, in run
    raise EmbedThumbnailPPError(msg)
EmbedThumbnailPPError
```

**Comment by yan12125** [comment]
Thanks for the report. In the next version thumbnail embedding is skipped if thumbnail downloading fails.
