### ISSUE TITLE
Is it still support download videos from nicovideo.jp?

### ISSUE THREAD

**Issue by Cupcake-iOS** [rg3/youtube-dl#6003]
I try to download the video file from nicovideo.jp, but it's not work.
So is it still support download videos from nicovideo.jp?

I'm using version 2015.06.15.
And download url is http://www.nicovideo.jp/watch/sm26509498

The error message is

```
➜  youtube-dl --verbose "http://www.nicovideo.jp/watch/sm26509498"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.nicovideo.jp/watch/sm26509498']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.06.15
[debug] Python version 2.7.6 - Darwin-14.3.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[niconico] sm26509498: Downloading webpage
[niconico] sm26509498: Downloading video info page
[niconico] sm26509498: Downloading webpage
[niconico] sm26509498: Downloading flv info
ERROR: Unable to find video URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 650, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 273, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/niconico.py", line 163, in _real_extract
    raise ExtractorError('Unable to find video URL')
ExtractorError: Unable to find video URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by yan12125** [comment]
Works for me:
```
$ youtube-dl -v --write-pages "http://www.nicovideo.jp/watch/sm26509498"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', '--write-pages', 'http://www.nicovideo.jp/watch/sm26509498']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.06.15
[debug] Git HEAD: 4470536
[debug] Python version 3.4.3 - Linux-4.0.5-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 2.7, ffprobe 2.7, rtmpdump 2.4
[debug] Proxy map: {}
[niconico] sm26509498: Downloading webpage
[niconico] Saving request to sm26509498_http_-_www.nicovideo.jp_watch_sm26509498.dump
[niconico] sm26509498: Downloading video info page
[niconico] Saving request to sm26509498_http_-_ext.nicovideo.jp_api_getthumbinfo_sm26509498.dump
[niconico] sm26509498: Downloading webpage
[niconico] Saving request to sm26509498_http_-_ext.nicovideo.jp_thumb_watch_sm26509498.dump
[niconico] sm26509498: Downloading flv info
[niconico] Saving request to sm26509498_http_-_ext.nicovideo.jp_thumb_watch.dump
[debug] Invoking downloader on 'http://smile-fnl51.nicovideo.jp/smile?m=26509498.31179'
[download] Destination: ビスマルクで「こっち向いてBaby」【MMD艦これ】-sm26509498.mp4
[download]   6.6% of 15.20MiB at  2.35MiB/s ETA 00:06^C
ERROR: Interrupted by user
```
Could you add the option ```--write-pages``` like the command above and upload/paste all *.dump files?

**Comment by StarkBall** [comment]
It's really strange~~
here is my dump files
* https://www.dropbox.com/s/klybqgvhyna9sta/sm26509498_http_-_www.nicovideo.jp_watch_sm26509498.dump?dl=1
* https://www.dropbox.com/s/5x01gwr96f92rgb/sm26509498_http_-_ext.nicovideo.jp_thumb_watch.dump?dl=1
* https://www.dropbox.com/s/slint25jjvxpmxp/sm26509498_http_-_ext.nicovideo.jp_thumb_watch_sm26509498.dump?dl=1
* https://www.dropbox.com/s/zz53p4o3yzytdls/sm26509498_http_-_ext.nicovideo.jp_api_getthumbinfo_sm26509498.dump?dl=1

**Comment by yan12125** [comment]
There's something strange in sm26509498_http_-_ext.nicovideo.jp_thumb_watch.dump:
```
errno=17&error=invalid_play_key&done=true
```
The play key is from sm26509498_http_-_ext.nicovideo.jp_thumb_watch_sm26509498.dump:
```
,'thumbPlayKey': '1434636487.0.1.sklvT3aSc_7YI9KJ9W4YUJVVy6k...'
```
I got the same error with this key, and I don't know why niconico gives the wrong key.

As a workaround, could you try to download with ```--username``` and ```--password``` options?

**Comment by StarkBall** [comment]
I try to download with ```--username``` and ```--password```.
I don't know is it ok to use Facebook authentication, but the same result, which is 
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'--write-pages', u'http://www.nicovideo.jp/watch/sm26509498', u'--username', u'PRIVATE', u'--password', u'PRIVATE']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.06.15
[debug] Python version 2.7.6 - Darwin-14.3.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[niconico] Logging in
[niconico] Saving request to None_https_-_secure.nicovideo.jp_secure_login.dump
WARNING: unable to log in: bad username or password
[niconico] sm26509498: Downloading webpage
[niconico] Saving request to sm26509498_http_-_www.nicovideo.jp_watch_sm26509498.dump
[niconico] sm26509498: Downloading video info page
[niconico] Saving request to sm26509498_http_-_ext.nicovideo.jp_api_getthumbinfo_sm26509498.dump
[niconico] sm26509498: Downloading webpage
[niconico] Saving request to sm26509498_http_-_ext.nicovideo.jp_thumb_watch_sm26509498.dump
[niconico] sm26509498: Downloading flv info
[niconico] Saving request to sm26509498_http_-_ext.nicovideo.jp_thumb_watch.dump
ERROR: Unable to find video URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 650, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 273, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/niconico.py", line 163, in _real_extract
    raise ExtractorError('Unable to find video URL')
ExtractorError: Unable to find video URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by Clpsplug** [comment]
Same here. Here's yet another examples that `youtube-dl` failed. I'm using **v2016/03/26**. (I was opening the issue when I found this, so I'll c&p what I was writing here)

---

So I heard `youtube-dl` can download from nicovideo, I picked [this video](http://www.nicovideo.jp/watch/sm13892516) for testing, but failed. I tried [another](http://www.nicovideo.jp/watch/sm28414938), but this didn't work either.
I can't test for every single video on there, but looks like nicovideo functionality is dead.

## What happened
**Failure while downloading the video on niconico**. `ExtractorError: Unable to find video URL` has occurred.

## Environment
Mac OS X 10.10.5
HomeBrew-downloaded `youtube-dl` v2016/03/26.
zsh 5.2 (x86_64-apple-darwin14.5.0)

## Steps to reproduce
Try downloading any video on niconico. `youtube-dl http://www.nicovideo.jp/watch/sm*****`

## Expected
Video downloaded to current directory.

## Actual
`youtube-dl` failed with `ExtractorError: Unable to find video URL`.

## Output
```
・ω)┌┘’,;’;≡三<CPlug@localhost H28 03/27 11:22:07)
> youtube-dl http://www.nicovideo.jp/watch/sm13892516 --verbose                                 [~]
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://www.nicovideo.jp/watch/sm13892516', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.03.26
[debug] Python version 2.7.11 - Darwin-14.5.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.0, ffprobe 3.0
[debug] Proxy map: {}
[niconico] sm13892516: Downloading webpage
[niconico] sm13892516: Downloading video info page
[niconico] sm13892516: Downloading webpage
[niconico] sm13892516: Downloading flv info
ERROR: Unable to find video URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 668, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 320, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/niconico.py", line 161, in _real_extract
    raise ExtractorError('Unable to find video URL')
ExtractorError: Unable to find video URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by dstftw** [comment]
Both work fine for me. Post the outputs with `--dump-pages`.

**Comment by Clpsplug** [comment]
OK, so I did `--dump-pages`, but the output was too large (and also they were in base64,) I decoded them and uploaded to my dropbox.

https://www.dropbox.com/s/benfcsmrms8qfjp/youtube-dl%20niconico%20fail.zip?dl=0

Looks like I've got the same issue here. I found `errno=17&error=invalid_play_key&done=true
` in flv info.

**Comment by yan12125** [comment]
Niconico now blocks playing without an account. Does the error occur with credentials?

**Comment by yan12125** [comment]
Closing as no response for a long time.
