### ISSUE TITLE
Add support for snagfilms.com

### ISSUE THREAD

**Issue by selvagem** [rg3/youtube-dl#6007]
Support for snagfilms.com would be very welcome.

**Comment by yan12125** [comment]
Please [post an example URL](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Site support requests must contain an example URL.

**Comment by selvagem** [comment]
user$ youtube-dl --verbose http://www.snagfilms.com/films/title/i_am_fishead
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.snagfilms.com/films/title/i_am_fishead']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.06.15
[debug] Python version 2.7.3 - Darwin-14.3.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.6.3, ffprobe 2.6.3, rtmpdump 2.4
[debug] Proxy map: {}
[generic] i_am_fishead: Requesting header
WARNING: Falling back on generic information extractor.
[generic] i_am_fishead: Downloading webpage
[generic] i_am_fishead: Extracting information
ERROR: Unsupported URL: http://www.snagfilms.com/films/title/i_am_fishead
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1020, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1558, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1301, in XML
    parser.feed(text)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1643, in feed
    self._raiseerror(v)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1507, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 150, column 42
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 650, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 273, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1571, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.snagfilms.com/films/title/i_am_fishead

**Comment by dstftw** [comment]
This issue will be fixed in the next version. Thanks for the report.
