### ISSUE TITLE
Brightcove empty playlist

### ISSUE THREAD

**Issue by eapubpbt** [rg3/youtube-dl#6015]
./youtube-dl --verbose http://aptn.ca/blackstone/video/season-1/

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://aptn.ca/blackstone/video/season-1/']
[debug] Encodings: locale US-ASCII, fs US-ASCII, out US-ASCII, pref US-ASCII
[debug] youtube-dl version 2015.06.15
[debug] Python version 2.7.9 - FreeBSD-8.2-STABLE-amd64-64bit-ELF
[debug] exe versions: ffmpeg 0.11.3, ffprobe 0.11.3
[debug] Proxy map: {}
[generic] season-1: Requesting header
WARNING: Falling back on generic information extractor.
[generic] season-1: Downloading webpage
[generic] season-1: Extracting information
[generic] Brightcove video detected.
[download] Downloading playlist: Blackstone  |  SEASON 1
[generic] playlist Blackstone  |  SEASON 1: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[Brightcove] AQ~~,AAAAEQEb72E~,MYPTzvrWinzoYROX3AWqzRir9E-Up5Qk: Downloading playlist information
ERROR: Empty playlist; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 650, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 273, in extract
    return self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/brightcove.py", line 239, in _real_extract
    return self._get_playlist_info(player_key[0])
  File "./youtube-dl/youtube_dl/extractor/brightcove.py", line 277, in _get_playlist_info
    raise ExtractorError('Empty playlist')
ExtractorError: Empty playlist; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by yan12125** [comment]
Can you watch this video in browsers? I got neither videos nor error messages in Chrome.

**Comment by RingoTheDog** [comment]
The link works for me in a browser, but I get the same YouTube-DL error...

I posted (what I believe is) a similar issue here: https://github.com/rg3/youtube-dl/issues/5955
...maybe you can see that video?


![blackstone](https://cloud.githubusercontent.com/assets/4542921/8312104/b089be18-198f-11e5-8dce-602d7140a5ea.png)

**Comment by yan12125** [comment]
Yes I can see the video in #5955. I've investigated it while I didn't find a solution. I'm not sure whether the two videos have the same problem in youtube-dl or not, either.
