### ISSUE TITLE
pornhub ERROR: Unsupported URL

### ISSUE THREAD

**Issue by whiskycharlie** [rg3/youtube-dl#6019]
Pornhub new links format not supported:
http://www.pornhub.com/view_video.php?viewkey=ph557bbb6676d2d

youtube-dl -j -v http://www.pornhub.com/view_video.php?viewkey=ph557bbb6676d2d
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-j', u'-v', u'http://www.pornhub.com/view_video.php?viewkey=ph557bbb6676d2d']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.06.15
[debug] Python version 2.7.3 - Linux-3.13.0-55-generic-x86_64-with-Ubuntu-12.04-precise
[debug] exe versions: avconv 0.8.17-4, avprobe 0.8.17-4, ffmpeg 0.8.17-4, ffprobe 0.8.17-4
[debug] Proxy map: {}
WARNING: Falling back on generic information extractor.
ERROR: Unsupported URL: http://www.pornhub.com/view_video.php?viewkey=ph557bbb6676d2d
Traceback (most recent call last):
  File "libs/youtube-dl/youtube-dl/youtube_dl/extractor/generic.py", line 1020, in _real_extract
    doc = parse_xml(webpage)
  File "libs/youtube-dl/youtube-dl/youtube_dl/utils.py", line 1558, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1301, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1643, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1507, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 115, column 79
Traceback (most recent call last):
  File "libs/youtube-dl/youtube-dl/youtube_dl/YoutubeDL.py", line 650, in extract_info
    ie_result = ie.extract(url)
  File "libs/youtube-dl/youtube-dl/youtube_dl/extractor/common.py", line 273, in extract
    return self._real_extract(url)
  File "libs/youtube-dl/youtube-dl/youtube_dl/extractor/generic.py", line 1571, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.pornhub.com/view_video.php?viewkey=ph557bbb6676d2d

Maybe wrong regexp in /extractor/pornhub.py:
_VALID_URL = r'https?://(?:www\.)?pornhub\.com/(?:view_video\.php\?viewkey=|embed/)(?P<id>[0-9a-f]+)'

(?P<id>[0-9a-f]+) should be (?P<id>[0-9a-z]+)

**Comment by dstftw** [comment]
This issue will be fixed in the next version. Thanks for the report.
