### ISSUE TITLE
Site support request for pornerbros.com

### ISSUE THREAD

**Issue by cleverpastor** [rg3/youtube-dl#6022]
C:>youtube-dl -v http://www.pornerbros.com/446920/sexy-19.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.pornerbros.com/446920/sexy-19.html']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.06.15
[debug] Python version 2.7.8 - Windows-8-6.2.9200
[debug] exe versions: ffmpeg N-65404-gd34ec64, ffprobe N-65404-gd34ec64, rtmpdump 2.4
[debug] Proxy map: {}
[generic] sexy-19: Requesting header
WARNING: Falling back on generic information extractor.
[generic] sexy-19: Downloading webpage
[generic] sexy-19: Extracting information
ERROR: Unsupported URL: http://www.pornerbros.com/446920/sexy-19.html
Traceback (most recent call last):
  File "youtube_dl\extractor\generic.pyo", line 1020, in _real_extract
  File "youtube_dl\utils.pyo", line 1558, in parse_xml
  File "xml\etree\ElementTree.pyo", line 1300, in XML
  File "xml\etree\ElementTree.pyo", line 1642, in feed
  File "xml\etree\ElementTree.pyo", line 1506, in _raiseerror
ParseError: unbound prefix: line 71, column 83
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 650, in extract_info
  File "youtube_dl\extractor\common.pyo", line 273, in extract
  File "youtube_dl\extractor\generic.pyo", line 1571, in _real_extract
UnsupportedError: Unsupported URL: http://www.pornerbros.com/446920/sexy-19.html

**Comment by cleverpastor** [comment]
Youtube-dl version 2015.07.04 still doesn't correctly identify and download the video on the page.

C:\>youtube-dl -v http://www.pornerbros.com/446920/sexy-19.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.pornerbros.com/446920/sexy-19.html']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.07.04
[debug] Python version 2.7.8 - Windows-8-6.2.9200
[debug] exe versions: ffmpeg N-65404-gd34ec64, ffprobe N-65404-gd34ec64, rtmpdump 2.4
[debug] Proxy map: {}
[generic] sexy-19: Requesting header
[redirect] Following redirect to http://www.pornerbros.com/videos/sexy-19_446920
[generic] sexy-19_446920: Requesting header
WARNING: Falling back on generic information extractor.
[generic] sexy-19_446920: Downloading webpage
[generic] sexy-19_446920: Extracting information
[debug] Invoking downloader on 'http://www.pornerbros.com/videos/sexy-19_446920'
[download] Destination: Sexy 19 _ PornerBros-sexy-19_446920.unknown_video
[download] 100% of 77.26KiB in 00:00
