### ISSUE TITLE
[rtve.es:alacarta] ERROR: content too short

### ISSUE THREAD

**Issue by rewerwer** [rg3/youtube-dl#6023]
``` shell
$ youtube-dl --verbose http://www.rtve.es/alacarta/videos/orbita-laika/orbita-laika-programa-8/2975760/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.rtve.es/alacarta/videos/orbita-laika/orbita-laika-programa-8/2975760/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.06.04.1
[debug] Python version 3.4.3 - Linux-4.0.5
[debug] exe versions: ffmpeg 2.7, ffprobe 2.7, rtmpdump 2.4
[debug] Proxy map: {}
[rtve.es:alacarta] Fetching manager info
[rtve.es:alacarta] 2975760: Downloading JSON metadata
[rtve.es:alacarta] 2975760: Downloading url information
[rtve.es:alacarta] 2975760: Getting video url
[debug] Invoking downloader on 'http://mvod1.akcdn.rtve.es/resources/TE_NGVA/mp4/8/4/1422835816348.mp4?primaryToken=1433696287_4f1292bfc2e6d2186c49f3b0c143cd98'
[download] Destination: Órbita Laika - Programa 8-2975760.mp4
[download]   3.5% of 342.47MiB at 131.94KiB/s ETA 16:59ERROR: content too short (expected 359110940 bytes and served 12582912)
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 1435, in process_info
    success = dl(filename, info_dict)
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 1377, in dl
    return fd.download(name, info)
  File "/usr/lib/python3.4/site-packages/youtube_dl/downloader/common.py", line 342, in download
    return self.real_download(filename, info_dict)
  File "/usr/lib/python3.4/site-packages/youtube_dl/downloader/http.py", line 219, in real_download
    raise ContentTooShortError(byte_counter, int(data_len))
youtube_dl.utils.ContentTooShortError: (12582912, 359110940)
```

**Comment by yan12125** [comment]
It should be a network problem. Could you try again?

**Comment by yan12125** [comment]
What's the result of the following command?
```
wget "http://mvod1.akcdn.rtve.es/resources/TE_NGVA/mp4/8/4/1422835816348.mp4?primaryToken=1433696287_4f1292bfc2e6d2186c49f3b0c143cd98"
```
And, is the downloaded file from the command above 359110940 bytes?

**Comment by rewerwer** [comment]
Yes, 359110940 (I used curl instead of wget).
