### ISSUE TITLE
c't/heise videos

### ISSUE THREAD

**Issue by berlincount** [rg3/youtube-dl#6037]
$ youtube-dl -v http://www.heise.de/newsticker/meldung/c-t-uplink-7-1-VR-Pornos-Bundestags-Hack-Besser-Fotografieren-2718301.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.heise.de/newsticker/meldung/c-t-uplink-7-1-VR-Pornos-Bundestags-Hack-Besser-Fotografieren-2718301.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.06.15
[debug] Python version 2.7.8 - Linux-3.16.0-18-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: rtmpdump 2.4
[debug] Proxy map: {}
[generic] c-t-uplink-7-1-VR-Pornos-Bundestags-Hack-Besser-Fotografieren-2718301: Requesting header
WARNING: Falling back on generic information extractor.
[generic] c-t-uplink-7-1-VR-Pornos-Bundestags-Hack-Besser-Fotografieren-2718301: Downloading webpage
[generic] c-t-uplink-7-1-VR-Pornos-Bundestags-Hack-Besser-Fotografieren-2718301: Extracting information
ERROR: Unsupported URL: http://www.heise.de/newsticker/meldung/c-t-uplink-7-1-VR-Pornos-Bundestags-Hack-Besser-Fotografieren-2718301.html
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1020, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1558, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 113, column 20
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 650, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 273, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1571, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.heise.de/newsticker/meldung/c-t-uplink-7-1-VR-Pornos-Bundestags-Hack-Besser-Fotografieren-2718301.html

**Comment by TheRuedi** [comment]
c't Uplink gibt es aber auch in dem offiziellen Heise Kanal auf youtube:
https://www.youtube.com/user/heisenewsticker

**Comment by TobiX** [comment]
Since #9725 is now merged, this should be fixed.

**Comment by yan12125** [comment]
Yep. Thanks @TobiX!
