### ISSUE TITLE
not working eroprofile

### ISSUE THREAD

**Issue by guestguestguest** [rg3/youtube-dl#6047]
i am to horny for flash... but that makes me not very randy...
```
$ torsocks youtube-dl --verbose http://www.eroprofile.com/m/videos/view/Pooping-Russian-girl
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.eroprofile.com/m/videos/view/Pooping-Russian-girl']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.06.15
[debug] Python version 2.7.8 - Linux-3.1xxx
[debug] exe versions: avconv 2.4.x, avprobe 2.4.3, ffmpeg 2.4.x, ffprobe 2.4.x, rtmpdump 2.x
[debug] Proxy map: {}
[EroProfile] Pooping-Russian-girl: Downloading webpage
ERROR: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 650, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 273, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/eroprofile.py", line 82, in _real_extract
    r'<source src="([^"]+)', webpage, 'video 3u3rl'))
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 555, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


```
plz fix, thanks

**Comment by dstftw** [comment]
There is no video by this URL.
