### ISSUE TITLE
video fails to download with ContentTooShortError

### ISSUE THREAD

**Issue by ralfharing** [rg3/youtube-dl#6075]
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://www.youtube.com/watch?v=Kv_ZJod7wu4', u'-v'
]
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.06.15
[debug] Python version 2.7.7 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] Kv_ZJod7wu4: Downloading webpage
[youtube] Kv_ZJod7wu4: Extracting video information
[youtube] Kv_ZJod7wu4: Downloading DASH manifest
[debug] Invoking downloader on u'https://r2---sn-j5caxoxu-pn2s.googlevideo.com/v
ideoplayback?requiressl=yes&pcm2cms=yes&ratebypass=yes&source=youtube&initcwndbp
s=1707500&pl=21&dur=590.367&itag=22&lmt=1435131681458356&sver=3&ipbits=0&mime=vi
deo%2Fmp4&key=yt5&expire=1435208697&upn=wx7KKRfyU8I&mm=31&mn=sn-j5caxoxu-pn2s&ms
=au&signature=85D9BB75394753D68B5F1C7046BD60B2DB12201A.50379D1EB5712C89142EB8A3A
15F87A5DD9B0976&mt=1435187012&mv=m&usequic=no&sparams=dur%2Cid%2Cinitcwndbps%2Ci
p%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Cratebypass%2
Crequiressl%2Csource%2Cupn%2Cusequic%2Cexpire&fexp=9406006%2C9406631%2C9407141%2
C9408142%2C9408420%2C9408710%2C9413153%2C9413503%2C9415089%2C9415304%2C9415330%2
C9416126%2C9416374%2C9416456%2C9416898%2C952640&ip=24.45.91.95&id=o-AGCiWDLQpABn
vpZW_4sSHOIh1iHYp2U18SFX0byE-FQh'
[download] Destination: X 40.1 - A Berg of Great Magnitude-Kv_ZJod7wu4.mp4
[download]   0.0% of 102.86MiB at 28.99KiB/s ETA 01:00:33ERROR: content too shor
t (expected 107861403 bytes and served 1811)
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 1435, in pr
ocess_info
    success = dl(filename, info_dict)
  File "D:\Python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 1377, in dl

    return fd.download(name, info)
  File "D:\Python27\lib\site-packages\youtube_dl\downloader\common.py", line 342
, in download
    return self.real_download(filename, info_dict)
  File "D:\Python27\lib\site-packages\youtube_dl\downloader\http.py", line 219,
in real_download
    raise ContentTooShortError(byte_counter, int(data_len))
ContentTooShortError
```

**Comment by jaimeMF** [comment]
This are usually errors on YouTube side, you can try downloading it later or use another format (use `-F` to get the list of available formats).
