### ISSUE TITLE
ImportError: No module named xml.parsers.expat

### ISSUE THREAD

**Issue by hillz1** [rg3/youtube-dl#6077]
I'm using youtube-dl on my openwrt router when I run the command it says ImportError: No module named xml.parsers.expat 

root@AngelBeats:/mnt/usb# youtube-dl -v
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/bin/youtube-dl/__main__.py", line 16, in <module>
  File "/usr/bin/youtube-dl/youtube_dl/__init__.py", line 16, in <module>
  File "/usr/bin/youtube-dl/youtube_dl/options.py", line 8, in <module>
  File "/usr/bin/youtube-dl/youtube_dl/downloader/__init__.py", line 3, in <module>
  File "/usr/bin/youtube-dl/youtube_dl/downloader/common.py", line 8, in <module>
  File "/usr/bin/youtube-dl/youtube_dl/compat.py", line 132, in <module>
ImportError: No module named xml.parsers.expat

**Comment by jaimeMF** [comment]
That python is missing xml support, you'll have to rebuild it or install one with the support enabled.

And **don't run youtube-dl as root user**, it's only needed in some setups for updating.
