### ISSUE TITLE
TypeError: POST when trying to download videos as registered user of Lynda.com

### ISSUE THREAD

**Issue by marcovirtual** [rg3/youtube-dl#6088]
>[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://www.lynda.com/Tkinter-tutorials/Entering-displaying-multiple-lines-Text-widget/163607/184111-4.html?autoplay=true', '-v', '-u', 'PRIVATE', '-p', 'PRIVATE']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.06.25
[debug] Python version 3.4.3 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[lynda] Logging in as PRIVATE@gmail.com
Traceback (most recent call last):
  File "C:\Python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Desktop\youtube-dl.exe\__main__.py", line 9, in <module>
  File "C:\Python34\lib\site-packages\youtube_dl\__init__.py", line 406, in main_real_main(argv)
  File "C:\Python34\lib\site-packages\youtube_dl\__init__.py", line 396, in _real_main
    retcode = ydl.download(all_urls)
  File "C:\Python34\lib\site-packages\youtube_dl\YoutubeDL.py", line 1501, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "C:\Python34\lib\site-packages\youtube_dl\YoutubeDL.py", line 654, in extract_info
    ie_result = ie.extract(url)
  File "C:\Python34\lib\site-packages\youtube_dl\extractor\common.py", line 272, in extract
    self.initialize()
  File "C:\Python34\lib\site-packages\youtube_dl\extractor\common.py", line 266, in initialize
    self._real_initialize()
  File "C:\Python34\lib\site-packages\youtube_dl\extractor\lynda.py", line 25, in _real_initialize
    self._login()
  File "C:\Python34\lib\site-packages\youtube_dl\extractor\lynda.py", line 41, in _login
    request, None, 'Logging in as %s' % username)
  File "C:\Python34\lib\site-packages\youtube_dl\extractor\common.py", line 424, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding)
  File "C:\Python34\lib\site-packages\youtube_dl\extractor\common.py", line 331, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal)
  File "C:\Python34\lib\site-packages\youtube_dl\extractor\common.py", line 312, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "C:\Python34\lib\site-packages\youtube_dl\YoutubeDL.py", line 1729, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "C:\Python34\lib\urllib\request.py", line 461, in open
    req = meth(req)
  File "C:\Python34\lib\urllib\request.py", line 1112, in do_request_
    raise TypeError(msg)
TypeError: POST data should be bytes or an iterable of bytes. It cannot be of type str.

**Comment by marcovirtual** [comment]
I managed to solve the problem by using the youtube-dl GUI at youtube-dlg. I'm closing the issue.
