### ISSUE TITLE
Google Signin Incompatible Layout

### ISSUE THREAD

**Issue by Athertonius** [rg3/youtube-dl#6100]
Out of the 4 consecutive times I've tested signing in, and downloading videos from my Watch Later page, I've gotten 3 different response failures, and somehow, a successful retrieval of the playlist - this seems to be linked with the way Google challenges user login attempts when deemed "unusual", or it just being inexplicably stubborn.

```
[debug] System config: []
[debug] User config: [u'--add-metadata', u'-o', u'%(upload_date)s - %(title)s.%(ext)s', u'-c', u'-f', u'bestvideo[ext=mp4][width<=1920]+bestaudio[ext=m4a]', u'--embed-thumbnail', u'--embed-subs', u'--exec', u'IFS=$n && j={} && k=`expr length $j` && l=`expr $k - 15` && notify-send "YouTube DL" --icon /usr/local/bin/icon.png "`expr substr $j 12 $l`"']
[debug] Command-line args: [u':ytwatchlater', u'-n', u'--write-pages', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.06.15
[debug] Python version 2.7.9 - Linux-3.19.0-21-generic-x86_64-with-Ubuntu-15.04-vivid
[debug] exe versions: avconv 11.2-6, avprobe 11.2-6, ffmpeg N-73160-g2c77ca4, ffprobe N-73160-g2c77ca4
[debug] Proxy map: {}
[youtube:watchlater] Downloading login page
[youtube:watchlater] Saving request to None_https_-_accounts.google.com_ServiceLogin.dump
[youtube:watchlater] Logging in
[youtube:watchlater] Saving request to None_https_-_accounts.google.com_ServiceLogin.dump
[youtube:watchlater] WL: Downloading webpage
[youtube:watchlater] Saving request to WL_https_-_www.youtube.com_playlistlist=WL.dump
ERROR: The playlist doesn't exist or is private, use --username or --netrc to access it.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 650, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 273, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1677, in _real_extract
    return self._extract_playlist('WL')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1301, in _extract_playlist
    expected=True)
ExtractorError: The playlist doesn't exist or is private, use --username or --netrc to access it.
```

Failed attempts:
![screencapture-file-none_https_-_accounts-google-com_servicelogin-dump-1435353098398](https://cloud.githubusercontent.com/assets/10201206/8387644/953d654c-1c5a-11e5-9740-38ab46a1097c.png)
![screencapture-file-none_https_-_accounts-google-com_servicelogin-dump-1435353213810](https://cloud.githubusercontent.com/assets/10201206/8387645/954737d4-1c5a-11e5-927d-f0090fc16d34.png)
![screencapture-file-none_https_-_accounts-google-com_servicelogin-dump-1435353288692](https://cloud.githubusercontent.com/assets/10201206/8387646/954f32f4-1c5a-11e5-95b8-069b5d8f3029.png)

**Comment by Athertonius** [comment]
Misdiagnosed. Issue with concurrency.
