### ISSUE TITLE
Existing Signin causes other Instances to typically Fail Signon process

### ISSUE THREAD

**Issue by Athertonius** [rg3/youtube-dl#6101]
When using youtube-dl concurrent to another signed in instance, signin is inconsistent - outright failure occurs, preventing access to private playlists, possibly gated videos as well, however this is not always the case. Between 2 clients, I've been unable to see any pattern; somehow both can fail to signin.

Private Playlist
```
[debug] System config: []
[debug] User config: [u'--add-metadata', u'-o', u'%(upload_date)s - %(title)s.%(ext)s', u'-c', u'-f', u'bestvideo[ext=mp4][width<=1920]+bestaudio[ext=m4a]', u'--embed-thumbnail', u'--embed-subs', u'--exec', u'IFS=$n && j={} && k=`expr length $j` && l=`expr $k - 15` && notify-send "YouTube DL" --icon /usr/local/bin/icon.png "`expr substr $j 12 $l`"']
[debug] Command-line args: [u'https://www.youtube.com/playlist?list=PLARhCYccw3tb0ewDzW4eE28DNc9V_oIZE', u'-n', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.06.25
[debug] Python version 2.7.9 - Linux-3.19.0-21-generic-x86_64-with-Ubuntu-15.04-vivid
[debug] exe versions: avconv 11.2-6, avprobe 11.2-6, ffmpeg N-73160-g2c77ca4, ffprobe N-73160-g2c77ca4
[debug] Proxy map: {}
[youtube:playlist] Downloading login page
[youtube:playlist] Logging in
[youtube:playlist] PLARhCYccw3tb0ewDzW4eE28DNc9V_oIZE: Downloading webpage
ERROR: The playlist doesn't exist or is private, use --username or --netrc to access it.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 654, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 273, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1366, in _real_extract
    return self._extract_playlist(playlist_id)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1303, in _extract_playlist
    expected=True)
ExtractorError: The playlist doesn't exist or is private, use --username or --netrc to access it.
```
Watch Later:
```
...
[debug] Command-line args: [u':ytwatchlater', u'-n', u'-v']
...
[youtube:watchlater] Downloading login page
[youtube:watchlater] Logging in
[youtube:watchlater] WL: Downloading webpage
...
```

**Comment by yan12125** [comment]
Are the credentials specified in .netrc valid for https://www.youtube.com/playlist?list=PLARhCYccw3tb0ewDzW4eE28DNc9V_oIZE? If not, you need to specify additional ```--username``` and ```--password``` in the command line.

**Comment by Athertonius** [comment]
They are definitely correct, as signin is successful on occasion, say I were to leave it in a loop which restarted on a non-zero exit code - I regularly have to update it due to Google's insistence on ostensible suspicious behavior.

**Comment by untergrundbiber** [comment]
>  I regularly have to update it due to Google's insistence on ostensible suspicious behavior.

I have the same problem. Since a few weeks Google sends me once a week an email that a suspicious login was prevented and I have to change the password. I use this account only for youtube-dl and its very annoying.
