### ISSUE TITLE
VK Authentication

### ISSUE THREAD

**Issue by yousufalim** [rg3/youtube-dl#6105]
VK.com authentication seems to no longer work.

[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.06.25
[debug] Python version 2.7.5 - Linux-3.8.13-xxxx-grs-ipv6-64-x86_64-with-fedora-19-Schrödinger’s_Cat
[debug] exe versions: ffmpeg 2.2.13, ffprobe 2.2.13
[debug] Proxy map: {}
[vk.com] Logging in as admin@pixup.us
ERROR: Unable to login, incorrect username and/or password
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 654, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 272, in extract
    self.initialize()
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 266, in initialize
    self._real_initialize()
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/vk.py", line 140, in _real_initialize
    self._login()
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/vk.py", line 137, in _login
    raise ExtractorError('Unable to login, incorrect username and/or password', expected=True)
ExtractorError: Unable to login, incorrect username and/or password

**Comment by dstftw** [comment]
Authentication will work again in the next version. Thanks for the report.
