### ISSUE TITLE
ERROR: Signature extraction failed: Traceback (most recent call last)

### ISSUE THREAD

**Issue by rcolnago** [rg3/youtube-dl#6122]
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 479, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 383, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 454, in _parse_sig_js
    u'Initial JS player signature function name')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 391, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)

**Comment by jaimeMF** [comment]
I would bet you are running an outdated version, but [we need the full output with the --verbose option](https://github.com/rg3/youtube-dl/blob/1bbe660dfa713d377fdf0eeec6b6d6a5fa8c86d9/README.md#bugs) to provide help.

**Comment by dstftw** [comment]
As it was already mentioned, most likely you are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.
Feel free to open a new issue if you can reproduce with latest youtube-dl.
