### ISSUE TITLE
YouTube said: "Watch this video on YouTube." for RTMP videos with content warning

### ISSUE THREAD

**Issue by ivan** [rg3/youtube-dl#6129]
`youtube-dl https://www.youtube.com/user/KoreanFilm/videos` results in a whole lot of this:

```
[youtube] _by9vE3trI8: Downloading webpage
[youtube] _by9vE3trI8: Downloading embed webpage
[youtube] _by9vE3trI8: Refetching age-gated info webpage
ERROR: _by9vE3trI8: YouTube said: <a href="http://www.youtube.com/watch?v=_by9vE3trI8&feature=player_embedded" target="_blank">Watch this video on YouTube.</a><br/>Playback on other websites has been disabled by the video owner.
[download] Downloading video 13 of 109
[youtube] FLh9Lb3G8JU: Downloading webpage
[youtube] FLh9Lb3G8JU: Downloading embed webpage
[youtube] FLh9Lb3G8JU: Refetching age-gated info webpage
ERROR: FLh9Lb3G8JU: YouTube said: <a href="http://www.youtube.com/watch?v=FLh9Lb3G8JU&feature=player_embedded" target="_blank">Watch this video on YouTube.</a><br/>Playback on other websites has been disabled by the video owner.
[...]
[download] Downloading video 15 of 109
[youtube] 8u9syVJc1qA: Downloading webpage
[youtube] 8u9syVJc1qA: Downloading embed webpage
[youtube] 8u9syVJc1qA: Refetching age-gated info webpage
ERROR: 8u9syVJc1qA: YouTube said: <a href="http://www.youtube.com/watch?v=8u9syVJc1qA&feature=player_embedded" target="_blank">Watch this video on YouTube.</a><br/>Playback on other websites has been disabled by the video owner.
[download] Downloading video 16 of 109
[youtube] DnrgRbIL6bY: Downloading webpage
[youtube] DnrgRbIL6bY: Downloading embed webpage
[youtube] DnrgRbIL6bY: Refetching age-gated info webpage
ERROR: DnrgRbIL6bY: YouTube said: <a href="http://www.youtube.com/watch?v=DnrgRbIL6bY&feature=player_embedded" target="_blank">Watch this video on YouTube.</a><br/>Playback on other websites has been disabled by the video owner.
[download] Downloading video 17 of 109
[youtube] K4djhhewVJg: Downloading webpage
[youtube] K4djhhewVJg: Downloading embed webpage
[youtube] K4djhhewVJg: Refetching age-gated info webpage
ERROR: K4djhhewVJg: YouTube said: <a href="http://www.youtube.com/watch?v=K4djhhewVJg&feature=player_embedded" target="_blank">Watch this video on YouTube.</a><br/>Playback on other websites has been disabled by the video owner.
[download] Downloading video 18 of 109
[youtube] ly1GqgJGWpc: Downloading webpage
[youtube] ly1GqgJGWpc: Downloading embed webpage
[youtube] ly1GqgJGWpc: Refetching age-gated info webpage
ERROR: ly1GqgJGWpc: YouTube said: <a href="http://www.youtube.com/watch?v=ly1GqgJGWpc&feature=player_embedded" target="_blank">Watch this video on YouTube.</a><br/>Playback on other websites has been disabled by the video owner.
[download] Downloading video 19 of 109
[youtube] jLvJBBHSRaw: Downloading webpage
[youtube] jLvJBBHSRaw: Downloading embed webpage
[youtube] jLvJBBHSRaw: Refetching age-gated info webpage
ERROR: jLvJBBHSRaw: YouTube said: <a href="http://www.youtube.com/watch?v=jLvJBBHSRaw&feature=player_embedded" target="_blank">Watch this video on YouTube.</a><br/>Playback on other websites has been disabled by the video owner.
```

**Comment by ivan** [comment]
It looks like these are all RTMP videos

**Comment by yan12125** [comment]
Works for me:
```
$ youtube-dl -v "https://www.youtube.com/user/KoreanFilm/videos"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/user/KoreanFilm/videos']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.06.25
[debug] Git HEAD: 0b16efd
[debug] Python version 3.4.3 - Linux-4.0.6-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 2.7.1, ffprobe 2.7.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:user] KoreanFilm: Downloading channel page
[youtube:playlist] UUvH6u_Qzn5RQdz9W198umDw: Downloading webpage
[download] Downloading playlist: Uploads from KoreanFilm
[youtube:playlist] UUvH6u_Qzn5RQdz9W198umDw: Downloading page #1
[youtube:playlist] playlist Uploads from KoreanFilm: Downloading 109 videos
[download] Downloading video 1 of 109
[youtube] 13YR-a8DReQ: Downloading webpage
[youtube] 13YR-a8DReQ: Extracting video information
[youtube] 13YR-a8DReQ: Downloading DASH manifest
[debug] Invoking downloader on 'https://r2---sn-u5oxu-un5e.googlevideo.com/videoplayback?id=d77611f9af0345e4&itag=134&source=youtube&requiressl=yes&mm=31&mv=m&ms=au&mn=sn-u5oxu-un5e&pl=19&ratebypass=yes&mime=video/mp4&gir=yes&clen=245429744&lmt=1435591321802251&dur=6299.992&signature=743557767E4ED3E499FE9863E78E05087FDEDCE5.1D3B3BD99DC9BCE759E7EE601FE528209FC0211C&mt=1435644907&sver=3&upn=8m6mVHuCBF0&key=dg_yt0&fexp=901816,923612,9405186,9407141,9407942,9407992,9408093,9408142,9408420,9408710,9408764,9412548,9413057,9413503,9415041,9415635,9416126,9416334,9416729,952640&ip=140.112.247.145&ipbits=0&expire=1435666531&sparams=ip,ipbits,expire,id,itag,source,requiressl,mm,mv,ms,mn,pl,ratebypass,mime,gir,clen,lmt,dur'
[download] Resuming download at byte 10483712
[download] Destination: 육체의약속 Promises (1975)-13YR-a8DReQ.f134.mp4
[download]  10.4% of 234.06MiB at  4.67MiB/s ETA 00:44^C
ERROR: Interrupted by user
```
Could you post the full verbose log with ```-v``` option?

**Comment by ivan** [comment]
Yeah, the first video in that channel works fine, just the ones with the IDs in my log above are broken.

```
# PYTHONPATH=. python3 -m youtube_dl --verbose _by9vE3trI8
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '_by9vE3trI8']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.06.25
[debug] Git HEAD: f0714c9
[debug] Python version 3.4.0 - Linux-3.13.0-55-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: rtmpdump 2.4
[debug] Proxy map: {}
[youtube] _by9vE3trI8: Downloading webpage
[youtube] _by9vE3trI8: Downloading embed webpage
[youtube] _by9vE3trI8: Refetching age-gated info webpage
ERROR: _by9vE3trI8: YouTube said: <a href="http://www.youtube.com/watch?v=_by9vE3trI8&feature=player_embedded" target="_blank">Watch this video on YouTube.</a><br/>Playback on other websites has been disabled by the video owner.
Traceback (most recent call last):
  File "/home/at/youtube-dl/youtube_dl/YoutubeDL.py", line 654, in extract_info
    ie_result = ie.extract(url)
  File "/home/at/youtube-dl/youtube_dl/extractor/common.py", line 273, in extract
    return self._real_extract(url)
  File "/home/at/youtube-dl/youtube_dl/extractor/youtube.py", line 951, in _real_extract
    expected=True, video_id=video_id)
youtube_dl.utils.ExtractorError: _by9vE3trI8: YouTube said: <a href="http://www.youtube.com/watch?v=_by9vE3trI8&feature=player_embedded" target="_blank">Watch this video on YouTube.</a><br/>Playback on other websites has been disabled by the video owner.
```

**Comment by yan12125** [comment]
This video is both age-restricted and blocking embedding. There's no way to bypass age checking for such videos. You need to specify ```--username``` and ```--password``` to download them.
