### ISSUE TITLE
failed to download PBS video

### ISSUE THREAD

**Issue by cjfsyntropy** [rg3/youtube-dl#6139]
This command fails in the latest June 25th version:
`youtube-dl --verbose http://www.pbs.org/wgbh/americanexperience/films/death/player/`
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.pbs.org/wgbh/americanexperience/films/death/player/']
[debug] Encodings: locale ISO-8859-1, fs ISO-8859-1, out ISO-8859-1, pref ISO-8859-1
[debug] youtube-dl version 2015.06.25
[debug] Python version 2.7.9 - Linux-3.16.0-4-686-pae-i686-with-debian-8.1
[debug] exe versions: avconv 11.3-6, avprobe 11.3-6, ffmpeg 0.8.17-6, rtmpdump 2.4
[debug] Proxy map: {}
[PBS] player: Downloading webpage
ERROR: Unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/cjf/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 654, in extract_info
    ie_result = ie.extract(url)
  File "/home/cjf/bin/youtube-dl/youtube_dl/extractor/common.py", line 273, in extract
    return self._real_extract(url)
  File "/home/cjf/bin/youtube-dl/youtube_dl/extractor/pbs.py", line 146, in _real_extract
    video_id, display_id, upload_date = self._extract_webpage(url)
  File "/home/cjf/bin/youtube-dl/youtube_dl/extractor/pbs.py", line 127, in _extract_webpage
    webpage, 'player URL')
  File "/home/cjf/bin/youtube-dl/youtube_dl/extractor/common.py", line 555, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by yan12125** [comment]
Thanks for the report. This problem will be fixed in the next version.

**Comment by manyanimals** [comment]
Another way to download pbs videos is here http://www.allavsoft.com/how-to/download-pbs-videos.html
