### ISSUE TITLE
infoq extractor broken

### ISSUE THREAD

**Issue by ivanov** [rg3/youtube-dl#6141]
```
$ youtube-dl http://www.infoq.com/presentations/A-Few-of-My-Favorite-Python-Things --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://www.infoq.com/presentations/A-Few-of-My-Favorite-Python-Things', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.06.25
[debug] Python version 2.7.10 - Darwin-13.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.6.3, ffprobe 2.6.3
[debug] Proxy map: {}
[InfoQ] A-Few-of-My-Favorite-Python-Things: Downloading webpage
ERROR: Unable to extract HTTP base URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 654, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 273, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/infoq.py", line 46, in _real_extract
    'HTTP base URL')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 555, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract HTTP base URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

$ youtube-dl --version
2015.06.25

**Comment by yan12125** [comment]
Thanks for the report. InfoQ extractor will be fixed in the next version.
