### ISSUE TITLE
error 410

### ISSUE THREAD

**Issue by katamari1992** [rg3/youtube-dl#6158]
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-f', u'137+141', u'https://www.youtube.com/watch?v=UMHMrzJqvC8', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.07.04
[debug] Python version 2.7.6 - Linux-3.19.0-21-generic-x86_64-with-LinuxMint-17.1-rebecca
[debug] exe versions: avconv 9.18-6, avprobe 9.18-6, ffmpeg 2.7, ffprobe 2.7, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] UMHMrzJqvC8: Downloading webpage
[youtube] UMHMrzJqvC8: Downloading video info webpage
[youtube] UMHMrzJqvC8: Extracting video information
[youtube] UMHMrzJqvC8: Downloading DASH manifest
[youtube] UMHMrzJqvC8: Downloading DASH manifest
[debug] Invoking downloader on 'https://r19---sn-vgqs7n7s.googlevideo.com/videoplayback?id=50c1ccaf326abc2f&itag=137&source=youtube&requiressl=yes&nh=IgpwcjAyLm9yZDEyKgkxMjcuMC4wLjE&mm=31&mn=sn-vgqs7n7s&pl=47&ms=au&mv=m&ratebypass=yes&mime=video/mp4&gir=yes&clen=375115666&lmt=1414947479332034&dur=905.533&signature=70BBA1A6F112CEB1935ED31E83287FA0CAE4AAD4.025F17FEC74B16DD10778C27C2E0A98B36B70BFB&key=dg_yt0&sver=3&mt=1436144445&fexp=901816,9407141,9408142,9408420,9408710,9416126,952640,966300&upn=zj3ZPgXTxEU&ip=2602:306:34ba:2510:41ea:3986:8ec7:8793&ipbits=0&expire=1436166134&sparams=ip,ipbits,expire,id,itag,source,requiressl,nh,mm,mn,pl,ms,mv,ratebypass,mime,gir,clen,lmt,dur'
ERROR: unable to download video data: HTTP Error 410: Gone
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1427, in process_info
    partial_success = dl(fname, new_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1375, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 342, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 59, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1729, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 410: Gone

**Comment by jaimeMF** [comment]
It also fails with the same error when trying to play it on a browser, so it's a problem on YouTube side. `-f 'best'` works though (and maybe other format combinations).
