### ISSUE TITLE
[NowTV] Extractor broken / http://[...]/manifest.f4m.m3u8: Server returned 404 Not Found

### ISSUE THREAD

**Issue by Fusl** [rg3/youtube-dl#6169]
HI,

I have been informed that the NowTV extractor seems to be broken:

```
>_ youtube-dl --verbose http://www.nowtv.de/rtl/familien-im-brennpunkt/edelschuh-verkaeuferin-wird-immer-verzweifelter/player
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.nowtv.de/rtl/familien-im-brennpunkt/edelschuh-verkaeuferin-wird-immer-verzweifelter/player']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.07.07
[debug] Python version 2.7.8 - Linux-3.16.7-21-desktop-x86_64-with-SuSE-13.2-x86_64
[debug] exe versions: ffmpeg 2.6.3, ffprobe 2.6.3
[debug] Proxy map: {}
[NowTV] familien-im-brennpunkt/edelschuh-verkaeuferin-wird-immer-verzweifelter: Downloading JSON metadata
[debug] Invoking downloader on u'http://hls.fra.rtlnow.de/hls-vod-enc/v3/movies/208799-0-6667fc993d4e87d2958269cc56aa22edc352531d/manifest.f4m.m3u8'
[download] Destination: Edelschuh-Verkäuferin wird immer verzweifelter-208799.mp4
ffmpeg version 2.6.3 Copyright (c) 2000-2015 the FFmpeg developers
  built with gcc 4.8 (SUSE Linux)
  configuration: --shlibdir=/usr/lib64 --prefix=/usr --mandir=/usr/share/man --libdir=/usr/lib64 --enable-shared --disable-static --enable-debug --disable-stripping --extra-cflags='-fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g' --enable-pic --optflags='-fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g' --enable-gpl --enable-x11grab --enable-version3 --enable-pthreads --datadir=/usr/share/ffmpeg --enable-avfilter --enable-libpulse --enable-libwebp --enable-libvpx --enable-libopus --enable-libmp3lame --enable-libvorbis --enable-libtheora --enable-libspeex --enable-libxvid --enable-libx264 --enable-libx265 --enable-libschroedinger --enable-libgsm --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-postproc --enable-libdc1394 --enable-librtmp --enable-libfreetype --enable-avresample --enable-libtwolame --enable-libvo-aacenc --enable-gnutls --enable-libass --enable-frei0r --enable-libcelt --enable-libcdio --enable-ladspa
  libavutil      54. 20.100 / 54. 20.100
  libavcodec     56. 26.100 / 56. 26.100
  libavformat    56. 25.101 / 56. 25.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 11.102 /  5. 11.102
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  1.100 /  1.  1.100
  libpostproc    53.  3.100 / 53.  3.100
[http @ 0x2637cc0] HTTP error 404 Not Found
http://hls.fra.rtlnow.de/hls-vod-enc/v3/movies/208799-0-6667fc993d4e87d2958269cc56aa22edc352531d/manifest.f4m.m3u8: Server returned 404 Not Found


ERROR: ffmpeg exited with code 1
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/bin/youtube-dl/__main__.py", line 19, in <module>
    youtube_dl.main()
  File "/usr/bin/youtube-dl/youtube_dl/__init__.py", line 406, in main
    _real_main(argv)
  File "/usr/bin/youtube-dl/youtube_dl/__init__.py", line 396, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1501, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 665, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 711, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1171, in process_video_result
    self.process_info(new_info)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1433, in process_info
    success = dl(filename, info_dict)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1375, in dl
    return fd.download(name, info)
  File "/usr/bin/youtube-dl/youtube_dl/downloader/common.py", line 342, in download
    return self.real_download(filename, info_dict)
  File "/usr/bin/youtube-dl/youtube_dl/downloader/hls.py", line 50, in real_download
    self.report_error('%s exited with code %d' % (ffpp.basename, retval))
  File "/usr/bin/youtube-dl/youtube_dl/downloader/common.py", line 155, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 529, in report_error
    self.trouble(error_message, tb)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 491, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())
```

**Comment by dstftw** [comment]
This issue will be fixed in the next version. Thanks for the report.

**Comment by bromix** [comment]
Since 22.07 and 23.07 most videos are not working anymore.

```
youtube-dl --verbose --hls-prefer-native http://www.nowtv.de/rtl/alles-was-zaehlt/alles-was-zaehlt-11-folge-2225/player
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'--hls-prefer-native', u'http://www.nowtv.de/rtl/alles-was-zaehlt/alles-was-zaehlt-11-folge-2225/player']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.07.21
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[NowTV] alles-was-zaehlt/alles-was-zaehlt-11-folge-2225: Downloading JSON metadata
[debug] Invoking downloader on u'http://hls.fra.rtlnow.de/hls-vod-enc/abr/videos/2/124151/V_808174_SOHY_13-13000718277_124151_abr-1500_2372e246ce118a7357477ea67d879.mp4.m3u8'
[download] Destination: Falscher Verdacht-217057.mp4
[hlsnative] 217057: Downloading m3u8 manifest
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 1435, in process_info
  File "youtube_dl\YoutubeDL.pyo", line 1377, in dl
  File "youtube_dl\downloader\common.pyo", line 342, in download
  File "youtube_dl\downloader\hls.pyo", line 64, in real_download
  File "youtube_dl\YoutubeDL.pyo", line 1731, in urlopen
  File "urllib2.pyo", line 410, in open
  File "urllib2.pyo", line 523, in http_response
  File "urllib2.pyo", line 448, in error
  File "urllib2.pyo", line 382, in _call_chain
  File "urllib2.pyo", line 531, in http_error_default
HTTPError: HTTP Error 404: Not Found
```

**Comment by workbetterv** [comment]
I just find a simple method to directly download or convert F4M or F4F files to MP4, AVI, WMV etc from this article at http://www.allavsoft.com/how-to/convert-f4m-to-mp4.html
