### ISSUE TITLE
clipsyndicate.com extraction fails

### ISSUE THREAD

**Issue by flakzilla** [rg3/youtube-dl#6176]
Although youtube-dl added support for clipsyndicate.com in release 2013.11.29 (https://github.com/rg3/youtube-dl/issues/1744) it seems to be not working now.
```
UnsupportedError: Unsupported URL: http://chic.clipsyndicate.com/video/play/5855946/shark_falls_from_sky
```

Here is the -v output for a sample video, I tested a few of them and they all failed in the same way.
```
$ ./youtube-dl --verbose http://chic.clipsyndicate.com/video/play/5855946/shark_falls_from_sky
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://chic.clipsyndicate.com/video/play/5855946/shark_falls_from_sky']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.07.07
[debug] Python version 2.7.9 - Linux-3.18.9-gentoo-x86_64-Intel-R-_Xeon-R-_CPU_X5650_@_2.67GHz-with-gentoo-2.2
[debug] exe versions: ffmpeg 2.6.3, ffprobe 2.6.3
[debug] Proxy map: {}
[generic] shark_falls_from_sky: Requesting header
WARNING: Falling back on generic information extractor.
[generic] shark_falls_from_sky: Downloading webpage
[generic] shark_falls_from_sky: Extracting information
ERROR: Unsupported URL: http://chic.clipsyndicate.com/video/play/5855946/shark_falls_from_sky
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/extractor/generic.py", line 1092, in _real_extract
    doc = parse_xml(webpage)
  File "./youtube-dl/youtube_dl/utils.py", line 1562, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 191, column 124
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 654, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 273, in extract
    return self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/generic.py", line 1663, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://chic.clipsyndicate.com/video/play/5855946/shark_falls_from_sky
```

**Comment by yan12125** [comment]
Thanks for the report. URLs starts with ```chic``` will be supported in the next version.
