### ISSUE TITLE
twitch: Unable to extract authenticity token

### ISSUE THREAD

**Issue by TheRyuu** [rg3/youtube-dl#6186]
For a few days I've been unable to authenticate with twitch in order to watch subscriber only vods.  I know this worked on the 20150704 build so I tried that one as well and got the same error just to make sure it wasn't anything that's changed in youtube-dl.
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'--username', u'PRIVATE', u'--password', u'P
RIVATE', u'http://www.twitch.tv/day9tv/v/6867120']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.07.07
[debug] Python version 2.7.8 - Windows-8-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {}
[twitch:vod] Downloading login page
ERROR: Unable to extract authenticity token; please report this issue on https:/
/yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U
  to update. Be sure to call youtube-dl with the --verbose flag and include its
complete output.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 654, in extract_info
  File "youtube_dl\extractor\common.pyo", line 272, in extract
  File "youtube_dl\extractor\common.pyo", line 266, in initialize
  File "youtube_dl\extractor\twitch.pyo", line 52, in _real_initialize
  File "youtube_dl\extractor\twitch.pyo", line 64, in _login
  File "youtube_dl\extractor\common.pyo", line 555, in _search_regex
RegexNotFoundError: Unable to extract authenticity token; please report this issue
on https://yt-dl.org/bug . Make sure you are using the latest version; type
youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and
 include its complete output.
```

**Comment by dstftw** [comment]
This issue will be fixed in the next version. Thanks for the report.
