### ISSUE TITLE
Support for Apple Music videos

### ISSUE THREAD

**Issue by Fironet** [rg3/youtube-dl#6189]
Tried downloading a [music video](https://itunes.apple.com/us/post/idsa.4ab17a39-2720-11e5-96c5-a5b38f6c42d3) from Apple Music (itunes.apple.com) and youtube-dl reports it as unsupported. Confirmed with another user, too.

Verbose output:

```
    [debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
    [debug] youtube-dl version 2015.07.07
    [debug] Python version 2.7.8 - Windows-8-6.2.9200
    [debug] exe versions: ffmpeg N-73189-g7728d23, ffprobe N-73189-g7728d23, rtmpdump 2.4
    [debug] Proxy map: {}
    [generic] idsa: Requesting header
    WARNING: Falling back on generic information extractor.
    [generic] idsa: Downloading webpage
    [generic] idsa: Extracting information
    ERROR: Unsupported URL: https://itunes.apple.com/us/post/idsa.4ab17a39-2720-11e5-96c5-a5b38f6c42d3
    Traceback (most recent call last):
      File "youtube_dl\extractor\generic.pyo", line 1092, in _real_extract
      File "youtube_dl\utils.pyo", line 1562, in parse_xml
      File "xml\etree\ElementTree.pyo", line 1300, in XML
      File "xml\etree\ElementTree.pyo", line 1642, in feed
      File "xml\etree\ElementTree.pyo", line 1506, in _raiseerror
    ParseError: not well-formed (invalid token): line 7, column 934
    Traceback (most recent call last):
      File "youtube_dl\YoutubeDL.pyo", line 654, in extract_info
      File "youtube_dl\extractor\common.pyo", line 273, in extract
      File "youtube_dl\extractor\generic.pyo", line 1663, in _real_extract
    UnsupportedError: Unsupported URL: https://itunes.apple.com/us/post/idsa.4ab17a39-2720-11e5-96c5-a5b38f6c42d3
```

**Comment by jaimeMF** [comment]
@remixz added support for it, it will be available in the next version.

**Comment by Fironet** [comment]
Cheers @remixz!

**Comment by fuzzy76** [comment]
This isn't really working... It only downloads the 30 second preview.
