### ISSUE TITLE
Youtube backend fails on some videos

### ISSUE THREAD

**Issue by gsilvis** [rg3/youtube-dl#6191]
It seems to only happen on music

    [debug] System config: []
    [debug] User config: []
    [debug] Command-line args: ['https://www.youtube.com/watch?v=hiwi7d0f91Y', '--verbose']
    [debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8
    [debug] youtube-dl version 2014.08.05
    [debug] Python version 2.7.9 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.1
    [debug] Proxy map: {}
    [youtube] Setting language
    [youtube] hiwi7d0f91Y: Downloading webpage
    [youtube] hiwi7d0f91Y: Downloading video info webpage
    [youtube] hiwi7d0f91Y: Extracting video information
    [youtube] hiwi7d0f91Y: Encrypted signatures detected.
    [youtube] {43} signature length 41.42, html5 player en_US-vflVsMRd_
    [youtube] hiwi7d0f91Y: Downloading js player vflVsMRd_
    ERROR: Signature extraction failed: Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 479, in _decrypt_signature
        video_id, player_url, s
      File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 383, in _extract_signature_function
        res = self._parse_sig_js(code)
      File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 454, in _parse_sig_js
        u'Initial JS player signature function name')
      File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 391, in _search_regex
        raise RegexNotFoundError(u'Unable to extract %s' % _name)
    RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
    ; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 479, in _decrypt_signature
        video_id, player_url, s
      File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 383, in _extract_signature_function
        res = self._parse_sig_js(code)
      File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 454, in _parse_sig_js
        u'Initial JS player signature function name')
      File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 391, in _search_regex
        raise RegexNotFoundError(u'Unable to extract %s' % _name)
    RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 516, in extract_info
        ie_result = ie.extract(url)
      File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 170, in extract
        return self._real_extract(url)
      File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 860, in _real_extract
        encrypted_sig, video_id, player_url, age_gate)
      File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 489, in _decrypt_signature
        u'Signature extraction failed: ' + tb, cause=e)
    ExtractorError: Signature extraction failed: Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 479, in _decrypt_signature
        video_id, player_url, s
      File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 383, in _extract_signature_function
        res = self._parse_sig_js(code)
      File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 454, in _parse_sig_js
        u'Initial JS player signature function name')
      File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 391, in _search_regex
        raise RegexNotFoundError(u'Unable to extract %s' % _name)
    RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
    ; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by yan12125** [comment]
You need to update youtube-dl. Current version is 2015.07.07 while yours is 2014.08.15. Have a look at [this FAQ entry](https://github.com/rg3/youtube-dl#how-do-i-update-youtube-dl) if you have any problem.

**Comment by gsilvis** [comment]
The `hash -r` in the installation instructions is important, it would seem.  Thanks for the help.
