### ISSUE TITLE
myspass new XML unsupported

### ISSUE THREAD

**Issue by jengelh** [rg3/youtube-dl#6206]
Using youtube-dl-2015.07.04, loading
http://www.myspass.de/myspass/shows/tvshows/wochenshow/Wochenshow-vom-12012002--/3416/ yields
```
[MySpass] 3416: Downloading XML
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/bin/youtube-dl/youtube_dl/__init__.py", line 406, in main
  File "/usr/bin/youtube-dl/youtube_dl/__init__.py", line 396, in _real_main
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1501, in download
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 654, in extract_info
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 273, in extract
  File "/usr/bin/youtube-dl/youtube_dl/extractor/myspass.py", line 38, in _real_extract
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 447, in _download_xml
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: XML or text declaration not at start of entity: line 1, column 1
```

**Comment by yan12125** [comment]
Thanks for the report. This will be fixed in the next version.
