### ISSUE TITLE
twitch Unable to extract authenticity token

### ISSUE THREAD

**Issue by librarian** [rg3/youtube-dl#6226]
youtube-dl -n http://www.twitch.tv/gsl/b/673335222 --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-n', u'http://www.twitch.tv/gsl/b/673335222', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.07.07
[debug] Git HEAD: 716e4dc
[debug] Python version 2.7.9 - Darwin-14.3.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.6.1, ffprobe 2.6.1
[debug] Proxy map: {}
[twitch:video] Downloading login page
ERROR: Unable to extract authenticity token; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 654, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 272, in extract
    self.initialize()
  File "/usr/local/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 266, in initialize
    self._real_initialize()
  File "/usr/local/lib/python2.7/site-packages/youtube_dl/extractor/twitch.py", line 52, in _real_initialize
    self._login()
  File "/usr/local/lib/python2.7/site-packages/youtube_dl/extractor/twitch.py", line 64, in _login
    login_page, 'authenticity token')
  File "/usr/local/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 555, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract authenticity token; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
This issue is already fixed and will available in the next version.
