### ISSUE TITLE
Bandcamp and Youtube-dl

### ISSUE THREAD

**Issue by NickWinston123** [rg3/youtube-dl#6231]
Is there any way to do youtube-dl username.bandcamp.com and it download all of the albums? Is that supported yet?

When I tried it gave me this error.

nicks-mac-mini:~ noah$ youtube-dl http://liluglymane.bandcamp.com --verbose flag
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://liluglymane.bandcamp.com', u'--verbose', u'flag']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.07.07
[debug] Python version 2.7.10 - Darwin-13.3.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.7.1, ffprobe 2.7.1
[debug] Proxy map: {}
[Bandcamp:album] liluglymane: Downloading webpage
ERROR: The page doesn't contain any tracks; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 654, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 273, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/bandcamp.py", line 169, in _real_extract
    raise ExtractorError('The page doesn\'t contain any tracks')
ExtractorError: The page doesn't contain any tracks; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
That is not supported. Only per album.

**Comment by djvs** [comment]
A quick ruby script to hack this - requires curb and nokogiri libraries:

    #!/usr/bin/env ruby

    require 'curb'
    require 'nokogiri'

    targetdir = Dir.pwd
    url = ARGV[0]
    yta = 'youtube-dl --no-mtime -o "%(autonumber)s-%(title)s.%(ext)s"'
    unless url.match(/^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$/ix)
      puts "Url is invalid!"
      raise ArgumentError 
    end
    bcsubdmn = url.split("/")[2].split('.').first

    puts "Saving into #{targetdir}..."

    result = Curl.get(url)
    noko = Nokogiri::HTML.parse(result.body_str)
    bandcampalbums = noko.css("a[href*='bandcamp.com/album'], a[href^='/album/']").map{|x|x.attr('href')}.uniq.map{|y| y.match(/^\//) ? "http://#{bcsubdmn}.bandcamp.com#{y}" : y }.map{|x| [x, x.split("/").last.gsub('-',' ') ]}
    bandcampalbums.each do |al|
      puts "Downloading \"#{al.last}\" (#{al.first})..."
      newtarget = "#{targetdir}/#{al.last}"
      puts "  into #{newtarget} ..."
      `mkdir -p "#{newtarget}"; cd "#{newtarget}"; #{yta} "#{al.first}"; cd #{targetdir}` 
    end

**Comment by stefanos82** [comment]
@djvs well, those who are under Linux are quite privileged to use a set of tools, pipeline them together, and produce the desired result in no time.

My way of downloading Bandcamp albums is rather silly, yet so convenient.

All I do is to extract the links (thanks to elinks, a nice text web browser), clean the unnecessary duplicates, and save them in a file.

Then I use that file with `-a` flag and that would be it.

### Step 01

```bash
elinks --dump --no-numbering <URL> | 
grep -e '.com/album' -e '.com/track' | 
sed 's/.*https/https/g' |
uniq > links.txt
```

### Step 02

```bash
youtube-dl -o "Your artist's name - %(playlist)s/%(playlist_index)s. %(title)s.%(ext)s" 
           -a links.txt
```

**Comment by chimmel** [comment]
@dstftw I cannot download per album nor track:

`machine:Downloads superuser$ youtube-dl https://kingephraiim.bandcamp.com/album/osiris
[Bandcamp:album] osiris: Downloading webpage
[download] Downloading playlist: Osiris
[Bandcamp:album] playlist Osiris: Collected 21 video ids (downloading 21 of them)
[download] Downloading video 1 of 21
[Bandcamp] start: Downloading webpage
ERROR: unable to download video data: <urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)>
machine:Downloads superuser$ youtube-dl https://kingephraiim.bandcamp.com/track/start
[Bandcamp] start: Downloading webpage
ERROR: unable to download video data: <urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)>`

@stefanos82 when I tried your method links.txt came out blank.

**Comment by stefanos82** [comment]
@chimmel I have just tried my suggestion and I can download the entire discography of your band.

What exactly did you do if I may ask?

**Comment by virtualbeck** [comment]
@stefanos82 

Made your script a bashrc function.
`function getBandCampMusic(){
  cd ~/Music/
  elinks --dump --no-numbering https://$1.bandcamp.com/ | 
  grep -e '.com/album' -e '.com/track' | 
  sed 's/.*https/https/g' |
  uniq > links.txt
  youtube-dl -o $1" - %(playlist)s/%(playlist_index)s. %(title)s.%(ext)s" -a links.txt
  rm links.txt
}`

**Comment by lyz-code** [comment]
If anyone needs this extractor, I've incorporated the #20207 PR into the `master` branch of [my fork](https://github.com/lyz-code/youtube-dl) and I try to periodically rebase the new changes of the upstream master.

**Comment by v-fox** [comment]
I've been trying to download from [this](https://bandcamp.materiacollective.com/album/resurrection-of-the-night-alucards-elegy-music-from-castlevania-symphony-of-the-night) with and without the aforementioned PR but it always ends up with:
```
[debug] System config: []
[debug] User config: ['-f', 'mkv[vcodec=av01,height<=1080]+bestaudio/webm[vcodec=av01,height<=1080]+bestaudio/bestvideo[vcodec=hevc,height<=1080]+bestaudio/bestvideo[vcodec=vp9,height<=1080]+bestaudio/best[height<=1080]', '--no-cache-dir', '--add-metadata', '--sub-format', 'best', '--write-sub', '--embed-subs', '--sub-lang', 'en,en-CA,ru', '-c', '-R', 'infinite', '--http-chunk-size', '2097152', '--buffer-size', '16K', '--socket-timeout', '30', '--yes-playlist', '--no-check-certificate']
[debug] Custom config: []
[debug] Command-line args: ['https://bandcamp.materiacollective.com/album/resurrection-of-the-night-alucards-elegy-music-from-castlevania-symphony-of-the-night', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.09.20
[debug] Python version 3.8.5 (CPython) - Linux-5.8.10-1932.g33939e8-HSF-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] resurrection-of-the-night-alucards-elegy-music-from-castlevania-symphony-of-the-night: Requesting header
WARNING: Falling back on generic information extractor.
[generic] resurrection-of-the-night-alucards-elegy-music-from-castlevania-symphony-of-the-night: Downloading webpage
[generic] resurrection-of-the-night-alucards-elegy-music-from-castlevania-symphony-of-the-night: Extracting information
[Bandcamp:album] resurrection-of-the-night-alucards-elegy-music-from-castlevania-symphony-of-the-night: Downloading webpage
WARNING: unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[download] Downloading playlist: resurrection-of-the-night-alucards-elegy-music-from-castlevania-symphony-of-the-night
[Bandcamp:album] playlist resurrection-of-the-night-alucards-elegy-music-from-castlevania-symphony-of-the-night: Collected 13 video ids (downloading 13 of them)
[download] Downloading video 1 of 13
[Bandcamp] the-nightmare: Downloading webpage
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/bandcamp.py", line 196, in _real_extract
    self._sort_formats(formats)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 1359, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

Removing format directive from config or overriding it to anything (like '-f best', '-f bestaudio' or '--format none --audio-format best') doesn't change anything.

**Comment by Otiel** [comment]
Bandcamp has changed their metadata formatting recently (in the last day-ish). That's probably the cause and would need a fix on youtube-dl part.

**Comment by gilou** [comment]
This was reported in #26681 and might be fixed by #26684

**Comment by lyz-code** [comment]
I've updated both the PR #20207 and my master branch with @gilou contribution, thanks!

**Comment by mjlee2003** [comment]
@lyz-code 
how do I convert this into an exe

**Comment by lyz-code** [comment]
Hi @mjlee2003 , I have no idea on how to convert python code to exe (I only use Linux), but probably the youtube-dl documentation tells you how.

Once you've discovered how to convert python code to an exe file, clone or download the `feature/bandcamp_user_support` branch of [my repository](https://github.com/lyz-code/youtube-dl/tree/feature/bandcamp_user_support) and convert it.

Sorry for not being able to give you more help :(

**Comment by RFGMM** [comment]
**bc-dl.sh**

#! /bin/bash
if ! [[ $1 =~ https?://.*\.bandcamp\.com.* ]]; then
  echo "Use a valid bandcamp's URL..."
  else
AAName=$(yt-dlp --get-filename --playlist-items 1 -o '%(artist)s-%(album)s' --output-na-placeholder  '' $1)
FixedAAName=${AAName// /-}
echo $FixedAAName
mkdir $FixedAAName
#yt-dlp -o "$FixedAAName/%(artist)s-%(album)s-%(playlist_index)s-%(track)s.%(ext)s" $1 
yt-dlp -o "$FixedAAName/%(playlist_index)s-%(track)s.%(ext)s" $1 
fi

**mdbc-dl.sh**
#! /bin/bash
listfilename=$(date +%F%H%M)
finalfilename=$(echo $RANDOM)
url=$1
if ! [[ $1 =~ https?://.*\.bandcamp\.com.* ]]; then
  echo "Use a valid bandcamp's URL..."
  else
wget  --convert-links $url -O /tmp/$listfilename.txt
cat /tmp/$listfilename.txt |  grep -e "/album" -e "/track/" |sed -n 's/.*href="\([^"]*\).*/\1/p' > /tmp/$finalfilename.txt
wc -l /tmp/$listfilename.txt
rm /tmp/$listfilename.txt
wc -l /tmp/$finalfilename.txt
LINES=$(cat /tmp/$finalfilename.txt)
for LINE in $LINES
do
      bc-dl $LINE
done
rm /tmp/$finalfilename.txt
fi
