### ISSUE TITLE
Can't download bilibili av2587092

### ISSUE THREAD

**Issue by roytam1** [rg3/youtube-dl#6261]
````
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.bilibili.com/video/av2587092/']
[debug] Encodings: locale cp950, fs mbcs, out cp950, pref cp950
[debug] youtube-dl version 2015.07.07
[debug] Python version 2.7.8 - Windows-XP-5.1.2600-SP3
[debug] exe versions: avconv v12_dev0-1569-g2cb34f8, ffmpeg N-73667-g99b0cad
[debug] Proxy map: {}
[BiliBili] 2587092: Downloading webpage
ERROR: Unable to extract cid; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type
  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 654, in extract_info
  File "youtube_dl\extractor\common.pyo", line 273, in extract
  File "youtube_dl\extractor\bilibili.pyo", line 68, in _real_extract
  File "youtube_dl\extractor\common.pyo", line 555, in _search_regex
RegexNotFoundError: Unable to extract cid; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest
version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
````

**Comment by dstftw** [comment]
Can you watch it in browser?

**Comment by yan12125** [comment]
@dstftw It's a China-restricted video.

**Comment by dstftw** [comment]
@yan12125 I've already [figured](c6b68648f45498bcacc71cc8f29696fa93259a7a) that out.

**Comment by yan12125** [comment]
Sorry for not noticing that. I think this issue can be closed as ```--proxy``` works for me.

**Comment by dstftw** [comment]
Well, let's confirm that OP is unable to play it in browser either and close then.

**Comment by roytam1** [comment]
yes I *CANNOT* watch this in browser.
maybe the "error" message should point out that to users?

**Comment by dstftw** [comment]
It [will](https://github.com/rg3/youtube-dl/commit/c6b68648f45498bcacc71cc8f29696fa93259a7a) in the next version.
