### ISSUE TITLE
Youtube-dl Kali Linux

### ISSUE THREAD

**Issue by BIGMOS** [rg3/youtube-dl#6271]
I get this error when runnin youtube-dl

I have tried all methods of downling it  as well
sudo curl https://yt-dl.org/downloads/2015.07.18/youtube-dl -o /usr/local/bin/youtube-dl
sudo chmod a+rx /usr/local/bin/youtube-dl

sudo pip install --upgrade youtube_dl 

pip install said successful

******ERROR BELOW********

root@kali32:~#youtube-dl
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl", line 9, in <module>
    load_entry_point('youtube-dl==2015.07.18', 'console_scripts', 'youtube-dl')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 337, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2279, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1989, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/__init__.py", line 16, in <module>
    from .options import (
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/options.py", line 8, in <module>
    from .downloader.external import list_external_downloaders
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/__init__.py", line 3, in <module>
    from .common import FileDownloader
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/common.py", line 8, in <module>
    from ..compat import compat_str
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/compat.py", line 82, in <module>
    _asciire = re.compile('([\x00-\x7f]+)') if sys.version_info < (2, 7) else compat_urllib_parse._asciire
AttributeError: 'module' object has no attribute '_asciire'

root@kali32:~# wget https://yt-dl.org/downloads/2015.07.18/youtube-dl.sig -O youtube-dl.sig
--2015-07-18 09:52:52--  https://yt-dl.org/downloads/2015.07.18/youtube-dl.sig
Resolving yt-dl.org (yt-dl.org)... 2001:1a50:11:0:5f:8f:acaa:177, 95.143.172.170
Connecting to yt-dl.org (yt-dl.org)|2001:1a50:11:0:5f:8f:acaa:177|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 543 [application/pgp-signature]
Saving to: `youtube-dl.sig'

100%[======================================>] 543         --.-K/s   in 0.001s  

2015-07-18 09:52:55 (1.03 MB/s) - `youtube-dl.sig' saved [543/543]

root@kali32:~#   gpg --verify youtube-dl.sig /usr/local/bin/youtube-dl
gpg: directory `/root/.gnupg' created
gpg: new configuration file `/root/.gnupg/gpg.conf' created
gpg: WARNING: options in `/root/.gnupg/gpg.conf' are not yet active during this run
gpg: keyring `/root/.gnupg/pubring.gpg' created
gpg: Signature made Sat 18 Jul 2015 06:05:48 AM EDT using RSA key ID A4826A18
gpg: Can't check signature: public key not found

**Comment by dstftw** [comment]
This is already fixed and will be available in the next version.
You can also fix this by updating python to 2.7.4 or later.
