### ISSUE TITLE
youtube-dl broken

### ISSUE THREAD

**Issue by WuvorWenda** [rg3/youtube-dl#6280]
After Updating to version 2015.07.18 ...
nothing is working anymore
 python -V
Python 2.7.3
youtube-dl -v
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 16, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 16, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/options.py", line 8, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/__init__.py", line 3, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 8, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 82, in <module>
AttributeError: 'module' object has no attribute '_asciire'

**Comment by dstftw** [comment]
This is already fixed and will be available in the next version.
You can also fix this by updating python to 2.7.4 or later. Or you can use previous version `https://yt-dl.org/downloads/2015.07.07/youtube-dl`.
