### ISSUE TITLE
AttributeError: 'module' object has no attribute '_asciire'

### ISSUE THREAD

**Issue by joepie91** [rg3/youtube-dl#6285]
* __Platform:__ Debian 7, x86_64, OVH image, Python 2.7.3
* __Version:__ 2015.07.18
* __URL:__ None, application does not even start
* __Resolver:__ N/A

```
root@ns503605:~# youtube-dl -v
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl", line 9, in <module>
    load_entry_point('youtube-dl==2015.07.18', 'console_scripts', 'youtube-dl')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 337, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2279, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1989, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/__init__.py", line 16, in <module>
    from .options import (
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/options.py", line 8, in <module>
    from .downloader.external import list_external_downloaders
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/__init__.py", line 3, in <module>
    from .common import FileDownloader
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/common.py", line 8, in <module>
    from ..compat import compat_str
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/compat.py", line 82, in <module>
    _asciire = re.compile('([\x00-\x7f]+)') if sys.version_info < (2, 7) else compat_urllib_parse._asciire
AttributeError: 'module' object has no attribute '_asciire'
```

**Comment by joepie91** [comment]
Can replicate on another Debian 7 system, not using an OVH image, but a stock install.

**Comment by joepie91** [comment]
Apologies, dupe of #6279, #6280, #6281. I'd only searched the open tickets, not the closed ones.
