### ISSUE TITLE
7/18 version completely broken

### ISSUE THREAD

**Issue by joeschmoe40** [rg3/youtube-dl#6289]
Observe:

 % youtube-dl.py -U
Updating to version 2015.07.18 ...
Updated youtube-dl. Restart youtube-dl to use the new version.
 % youtube-dl.py --version
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl.py/__main__.py", line 16, in <module>
  File "/usr/local/bin/youtube-dl.py/youtube_dl/__init__.py", line 16, in <module>
  File "/usr/local/bin/youtube-dl.py/youtube_dl/options.py", line 8, in <module>
  File "/usr/local/bin/youtube-dl.py/youtube_dl/downloader/__init__.py", line 3, in <module>
  File "/usr/local/bin/youtube-dl.py/youtube_dl/downloader/common.py", line 8, in <module>
  File "/usr/local/bin/youtube-dl.py/youtube_dl/compat.py", line 82, in <module>
AttributeError: 'module' object has no attribute '_asciire'
 % 

Tested on Linux (raspberry pi) and OSX with same results.

Previous version (2015.07.07) works fine.

**Comment by dstftw** [comment]
This is already fixed and will be available in the next version.
You can also fix this by updating python to 2.7.4 or later. Or you can use previous version `https://yt-dl.org/downloads/2015.07.07/youtube-dl`.
