### ISSUE TITLE
After updating youtube-dl, I get tons of Python errors now.

### ISSUE THREAD

**Issue by antdude** [rg3/youtube-dl#6295]
$ sudo youtube-dl -U
[sudo] password for myusername:
Updating to version 2015.07.18 ...
Updated youtube-dl. Restart youtube-dl to use the new version.

$ youtube-dl
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/bin/youtube-dl/__main__.py", line 16, in <module>
  File "/usr/bin/youtube-dl/youtube_dl/__init__.py", line 16, in <module>

  File "/usr/bin/youtube-dl/youtube_dl/options.py", line 8, in <module>
  File "/usr/bin/youtube-dl/youtube_dl/downloader/__init__.py", line 3, in <module>
    # $Id$
  File "/usr/bin/youtube-dl/youtube_dl/downloader/common.py", line 8, in <module>
  File "/usr/bin/youtube-dl/youtube_dl/compat.py", line 82, in <module>
AttributeError: 'module' object has no attribute '_asciire'

$ sudo youtube-dl -U
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/bin/youtube-dl/__main__.py", line 16, in <module>
  File "/usr/bin/youtube-dl/youtube_dl/__init__.py", line 16, in <module>

  File "/usr/bin/youtube-dl/youtube_dl/options.py", line 8, in <module>
  File "/usr/bin/youtube-dl/youtube_dl/downloader/__init__.py", line 3, in <module>
    # $Id$
  File "/usr/bin/youtube-dl/youtube_dl/downloader/common.py", line 8, in <module>
  File "/usr/bin/youtube-dl/youtube_dl/compat.py", line 82, in <module>
AttributeError: 'module' object has no attribute '_asciire'

$ python
Python 2.7.3 (default, Mar 13 2014, 11:03:55)
[GCC 4.7.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>

Is it because I still use Debian's oldstable? If so, then where can I download the older version? I think I had the build from 7/7/2015 that worked according to my history log.

Thank you in advance. :)

**Comment by trhodes** [comment]
https://yt-dl.org/downloads/2015.07.07/youtube-dl  is the older, working version (at least it works for me). I'm having the same issue, and there have been some removals of unused re imports that may be to blame. Testing out a fix now. I'm also on python 2.7.3, Slackware 14.0

**Comment by trhodes** [comment]
https://github.com/rg3/youtube-dl/commit/3cc8b4c327585ff4dbb045d17d6f5c160df6fdb8 is what makes this happen for me. Sorry I can't help much more.

**Comment by antdude** [comment]
Thanks trhodes. That 7/7/2015 build worked perfectly again. Where is this fix at? I'd like to test it too with you. ;)

**Comment by dstftw** [comment]
This is already fixed and will be available in the next version.
You can also fix this by updating python to 2.7.4 or later. Or you can use previous version `https://yt-dl.org/downloads/2015.07.07/youtube-dl`.

**Comment by antdude** [comment]
Thanks dstftw. I will stick with 7/7/2015 build. I can't upgrade my Python until I upgrade Debian to current stable which I am not ready for.
