### ISSUE TITLE
canalplus.fr HD video yields HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by s3ththompson** [rg3/youtube-dl#6301]
```sh
$ youtube-dl -w -f HD http://www.canalplus.fr/c-emissions/c-le-petit-journal/pid6515-le-petit-journal.html\?vid\=1286939 --verbose            
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-w', u'-f', u'HD', u'http://www.canalplus.fr/c-emissions/c-le-petit-journal/pid6515-le-petit-journal.html?vid=1286939', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.07.07
[debug] Python version 2.7.6 - Darwin-14.4.0-x86_64-i386-64bit
[debug] exe versions: avconv 11.4, avprobe 11.4, ffmpeg present, ffprobe present
[debug] Proxy map: {}
[Canalplus] pid6515-le-petit-journal.html: Downloading webpage
[Canalplus] 1286939: Downloading video XML
[Canalplus] 1286939: Downloading f4m manifest
[Canalplus] 1286939: Downloading m3u8 information
[debug] Invoking downloader on 'http://vod-flash.canalplus.fr/WWWPLUS/STREAMING/1507/09/nip_NIP_60479_1500k.mp4'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/Users/xxx/.homebrew/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1433, in process_info
    success = dl(filename, info_dict)
  File "/Users/xxx/.homebrew/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1375, in dl
    return fd.download(name, info)
  File "/Users/xxx/.homebrew/bin/youtube-dl/youtube_dl/downloader/common.py", line 342, in download
    return self.real_download(filename, info_dict)
  File "/Users/xxx/.homebrew/bin/youtube-dl/youtube_dl/downloader/http.py", line 59, in real_download
    data = self.ydl.urlopen(request)
  File "/Users/xxx/.homebrew/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1729, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden
```

It looks like the [Video Info](http://service.canal-plus.com/video/rest/getVideosLiees/cplus/1286939) produces a URL that the client is not authorized to fetch.  For what it's worth, I could download lower-quality `.flv` videos without a problem.  It is only the higher-quality `.mp4` videos which produce an error.

**Comment by s3ththompson** [comment]
This issue also appears on the most recent version of youtube-dl
```sh
$ youtube-dl -w -f HD http://www.canalplus.fr/c-emissions/c-le-petit-journal/pid6515-le-petit-journal.html\?vid\=1286939 --verbose           
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-w', u'-f', u'HD', u'http://www.canalplus.fr/c-emissions/c-le-petit-journal/pid6515-le-petit-journal.html?vid=1286939', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.07.21
[debug] Python version 2.7.6 - Darwin-14.4.0-x86_64-i386-64bit
[debug] exe versions: avconv 11.4, avprobe 11.4, ffmpeg present, ffprobe present
[debug] Proxy map: {}
[Canalplus] pid6515-le-petit-journal.html: Downloading webpage
[Canalplus] 1286939: Downloading video XML
[Canalplus] 1286939: Downloading f4m manifest
[Canalplus] 1286939: Downloading m3u8 information
[debug] Invoking downloader on 'http://vod-flash.canalplus.fr/WWWPLUS/STREAMING/1507/09/nip_NIP_60479_1500k.mp4'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/Users/xxx/.homebrew/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1435, in process_info
    success = dl(filename, info_dict)
  File "/Users/xxx/.homebrew/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1377, in dl
    return fd.download(name, info)
  File "/Users/xxx/.homebrew/bin/youtube-dl/youtube_dl/downloader/common.py", line 342, in download
    return self.real_download(filename, info_dict)
  File "/Users/xxx/.homebrew/bin/youtube-dl/youtube_dl/downloader/http.py", line 59, in real_download
    data = self.ydl.urlopen(request)
  File "/Users/xxx/.homebrew/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1731, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden
```

**Comment by dstftw** [comment]
Just use default format (like webplayer itself do), direct links are broken.
They all seem to be of the same quality:
```
<HD>http://vod-flash.canalplus.fr/WWWPLUS/STREAMING/1507/08/nip_NIP_60395_**1500k**.mp4</HD>
<HDS>http://us-cplus-aka.canal-plus.com/z/1507/08/nip_NIP_60395_,200k,400k,800k,**1500k**,.mp4.csmil/manifest.f4m</HDS>
<HLS>http://us-cplus-aka.canal-plus.com/i/1507/08/nip_NIP_60395_,200k,400k,800k,**1500k**,.mp4.csmil/master.m3u8</HLS>
```
