### ISSUE TITLE
AttributeError: 'module' object has no attribute '_asciire'

### ISSUE THREAD

**Issue by prestonconnors** [rg3/youtube-dl#6318]
Whenever I try and run youtube-dl version 2015.07.18 I get the below error message. Can you please help?

youtube-dl -h

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/bin/youtube-dl/__main__.py", line 16, in <module>
  File "/usr/bin/youtube-dl/youtube_dl/__init__.py", line 16, in <module>
    
  File "/usr/bin/youtube-dl/youtube_dl/options.py", line 8, in <module>
  File "/usr/bin/youtube-dl/youtube_dl/downloader/__init__.py", line 3, in <module>
    # $Id$
  File "/usr/bin/youtube-dl/youtube_dl/downloader/common.py", line 8, in <module>
  File "/usr/bin/youtube-dl/youtube_dl/compat.py", line 82, in <module>
AttributeError: 'module' object has no attribute '_asciire'

Python: Python 2.7.3

Distributor ID:	LinuxMint
Description:	Linux Mint 13 Maya
Release:	13
Codename:	maya

**Comment by prestonconnors** [comment]
Nevermind this looks like a dupe and you are in the process of fixing it.
