### ISSUE TITLE
'module' object has no attribute '_asciire'

### ISSUE THREAD

**Issue by linuxsoldier** [rg3/youtube-dl#6320]
Hi. I was trying to download a video from youtube yesterday after I updated youtube-dl with sudo youtube-dl -U and I got the next error:

$ youtube-dl (video url)
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 16, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 16, in <module>
    
  File "/usr/local/bin/youtube-dl/youtube_dl/options.py", line 8, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/__init__.py", line 3, in <module>
    # $Id$
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 8, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 82, in <module>
AttributeError: 'module' object has no attribute '_asciire'

This didn't happen until I update youtube-dl yesterday.
It seems like if the the program is trying to access to an nonexistent instance variable. Further I can't do anything. Cannot check the version, neither update it.

Thanks for your time.

Specifications:
Python version: Python 2.7.3
OS: Kali GNU/Linux moto
Kernel: 3.18.6-1~kali2 (2015-03-02)

Here you have an screenshot: 

![screenshot from 2015-07-21 15 45 55](https://cloud.githubusercontent.com/assets/13441001/8812148/08139564-2fc0-11e5-8ecb-cc9167e03242.png)

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl (this was fixed in 2015.07.21). Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.
