### ISSUE TITLE
Twitch past broadcast. ERROR: Unsupported URL

### ISSUE THREAD

**Issue by Sundheden** [rg3/youtube-dl#6323]
I've been using youtube-dl for a while to download past broadcasts from twitch, it works very well!
I just tried it on a freshly installed Debian 8.1 x64 where I installed youtube-dl via apt-get and get the following from verbose launch:

micke@ferg:~$ youtube-dl --verbose -F http://www.twitch.tv/thethiliacraft/v/8147859
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '-F', 'http://www.twitch.tv/thethiliacraft/v/8147859']
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
[debug] youtube-dl version 2014.08.05
[debug] Python version 2.7.9 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.1
[debug] Proxy map: {}
[generic] 8147859: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 8147859: Downloading webpage
[generic] 8147859: Extracting information
ERROR: Unsupported URL: http://www.twitch.tv/thethiliacraft/v/8147859; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 457, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/utils.py", line 1417, in parse_xml
    return xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 20, column 98
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 516, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 170, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 752, in _real_extract
    raise ExtractorError('Unsupported URL: %s' % url)
ExtractorError: Unsupported URL: http://www.twitch.tv/thethiliacraft/v/8147859; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

I have done apt-get update and upgrade, since youtube-dl -U tells me to use the same package manager as i installed it with.

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.
