### ISSUE TITLE
szpport hclips.com

### ISSUE THREAD

**Issue by leooleo-habbib** [rg3/youtube-dl#6325]
could we add  hclips.com ?

Thanks

**Comment by yan12125** [comment]
Please provide an [example URL](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient).

**Comment by leooleo-habbib** [comment]
e.g.
http://www.hclips.com/videos/candycristy-secret-movie-on-01-07-15-twenty-43-from-chaturbate/?pqr=1:ca02e299655209f5097abfd1528e3e5b:0:347901:1

here is youtube-dl  -v:
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.hclips.com/videos/candycristy-secret-movie-on-01-07-15-twenty-43-from-chaturbate/?pqr=1:ca02e299655209f5097abfd1528e3e5b:0:347901:1']
[debug] Encodings: locale ISO8859-15, fs ISO8859-15, out ISO8859-15, pref ISO8859-15
[debug] youtube-dl version 2015.07.21
[debug] Python version 2.7.10 - FreeBSD-10.2-BETA1-i386-32bit-ELF
[debug] exe versions: ffmpeg N-48118-g3163083, ffprobe N-48118-g3163083, rtmpdump 2.4
[debug] Proxy map: {}
[generic] ?pqr=1:ca02e299655209f5097abfd1528e3e5b:0:347901:1: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ?pqr=1:ca02e299655209f5097abfd1528e3e5b:0:347901:1: Downloading webpage
[generic] ?pqr=1:ca02e299655209f5097abfd1528e3e5b:0:347901:1: Extracting information
ERROR: Unsupported URL: http://www.hclips.com/videos/candycristy-secret-movie-on-01-07-15-twenty-43-from-chaturbate/?pqr=1:ca02e299655209f5097abfd1528e3e5b:0:347901:1
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1123, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1562, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/local/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/local/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/local/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: mismatched tag: line 93, column 176
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 656, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 275, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1712, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.hclips.com/videos/candycristy-secret-movie-on-01-07-15-twenty-43-from-chaturbate/?pqr=1:ca02e299655209f5097abfd1528e3e5b:0:347901:1


Hope that helps

**Comment by leooleo-habbib** [comment]
Again... is doesn't wor for 1-2 Weeks now...seems the hclips.com changed something.

see verbose output:

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'http://www.hclips.com/videos/angelkiuty-dancing-in-front-of-the-camera/?pqr=86:d28fd8fd0412039a4e5b272c612219c1:0:884907:1']
[debug] Encodings: locale ISO8859-15, fs ISO8859-15, out ISO8859-15, pref ISO8859-15
[debug] youtube-dl version 2017.03.10
[debug] Python version 2.7.13 - FreeBSD-11.0-STABLE-i386-32bit-ELF
[debug] exe versions: ffmpeg 3.2.4, ffprobe 3.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[generic] ?pqr=86:d28fd8fd0412039a4e5b272c612219c1:0:884907:1: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ?pqr=86:d28fd8fd0412039a4e5b272c612219c1:0:884907:1: Downloading webpage
[generic] ?pqr=86:d28fd8fd0412039a4e5b272c612219c1:0:884907:1: Extracting information
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 459, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 449, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1883, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 761, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 427, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2554, in _real_extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 2197, in _parse_jwplayer_data
TypeError: 'unicode' object does not support item assignment

hope that could help. Thank you.

**Comment by leooleo-habbib** [comment]
Again....that stoped working... Verbose output:
[debug] System config: []
[debug] User config: [u'--no-mtime']
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-F', u'https://www.hclips.com/videos/exotic-amateur-stockings-girlfriend-adult-clip69136/?pqr=17:d28fd8fd0412039a4e5b272c612219c1:0:1596845:1']
[debug] Encodings: locale ISO8859-15, fs ISO8859-15, out ISO8859-15, pref ISO8859-15
[debug] youtube-dl version 2017.10.29
[debug] Python version 2.7.14 - FreeBSD-11.1-STABLE-i386-32bit-ELF
[debug] exe versions: ffmpeg 3.4, ffprobe 3.4, rtmpdump 2.4
[debug] Proxy map: {}
[generic] ?pqr=17:d28fd8fd0412039a4e5b272c612219c1:0:1596845:1: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ?pqr=17:d28fd8fd0412039a4e5b272c612219c1:0:1596845:1: Downloading webpage
[generic] ?pqr=17:d28fd8fd0412039a4e5b272c612219c1:0:1596845:1: Extracting information
ERROR: Unsupported URL: https://www.hclips.com/videos/exotic-amateur-stockings-girlfriend-adult-clip69136/?pqr=17:d28fd8fd0412039a4e5b272c612219c1:0:1596845:1
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2159, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2539, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 2528, in _XML
    parser.feed(text)
  File "/usr/local/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "/usr/local/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
ParseError: mismatched tag: line 89, column 173
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 434, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3059, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.hclips.com/videos/exotic-amateur-stockings-girlfriend-adult-clip69136/?pqr=17:d28fd8fd0412039a4e5b272c612219c1:0:1596845:1


something changed in hclips webside, i guess.
