### ISSUE TITLE
[viki] TypeError: unorderable types: str() <= int()

### ISSUE THREAD

**Issue by remitamine** [rg3/youtube-dl#6333]
```
youtube-dl -v http://www.viki.com/videos/227452v-wild-cat-episode-1
[debug] System config: []
[debug] User config: ['--external-downloader', 'aria2c', '--external-downloader-args', '-x 16 --check-certificate=false', '-f', 'best[height<=?720]', '--sub-lang', 'ar,en', '--write-sub']
[debug] Command-line args: ['-v', 'http://www.viki.com/videos/227452v-wild-cat-episode-1']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.07.21
[debug] Python version 3.4.3 - Linux-4.1.2-2-ARCH-x86_64-with-arch-Arch-Linux
[debug] exe versions: ffmpeg 2.7.2, ffprobe 2.7.2, rtmpdump 2.4
[debug] Proxy map: {}
[viki] 227452v: Downloading video JSON
[viki] 227452v: Downloading video streams JSON
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
    youtube_dl.main()
  File "/usr/lib/python3.4/site-packages/youtube_dl/__init__.py", line 410, in main
    _real_main(argv)
  File "/usr/lib/python3.4/site-packages/youtube_dl/__init__.py", line 400, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 1503, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 667, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 713, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 1159, in process_video_result
    selected_format = self.select_format(rf, formats)
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 922, in select_format
    format_spec, available_formats)
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 911, in _apply_format_filter
    new_formats = [f for f in available_formats if _filter(f)]
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 911, in <listcomp>
    new_formats = [f for f in available_formats if _filter(f)]
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 910, in _filter
    return op(actual_value, comparison_value)
TypeError: unorderable types: str() <= int()
```

**Comment by dstftw** [comment]
This issue will be fixed in the next version. Thanks for the report.
