### ISSUE TITLE
Exception on bbccouk extractor

### ISSUE THREAD

**Issue by jbradsha** [rg3/youtube-dl#6356]
Exception on downloading.  When tried from browser it wants an acceptance re "strong language" (which seems to store a cookie as it only asks once) before playing.

Another vid with strong language started to download OK - http://www.bbc.co.uk/iplayer/episode/b063034k/before-i-kick-the-bucket - stopped the download on that but it seems OK.

Problem with this URL:
# youtube-dl http://www.bbc.co.uk/iplayer/episode/b063j5bb/wanted-a-very-personal-assistant-episode-1
[bbc.co.uk] b063j5bb: Downloading video page
[bbc.co.uk] b063j59z: Downloading media selection XML
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/bin/youtube-dl/youtube_dl/__init__.py", line 410, in main
  File "/usr/bin/youtube-dl/youtube_dl/__init__.py", line 400, in _real_main
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1503, in download
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 656, in extract_info
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 275, in extract
  File "/usr/bin/youtube-dl/youtube_dl/extractor/bbccouk.py", line 361, in _real_extract
  File "/usr/bin/youtube-dl/youtube_dl/extractor/bbccouk.py", line 281, in _download_media_selector
  File "/usr/bin/youtube-dl/youtube_dl/extractor/bbccouk.py", line 218, in _extract_video
TypeError: int() argument must be a string or a number, not 'NoneType'

# youtube-dl --version
2015.07.21

Thanks!

**Comment by dstftw** [comment]
This is already fixed and will be available in the next version.

**Comment by jbradsha** [comment]
Thanks! What a quick closure of a bug report :-)
