### ISSUE TITLE
youtube-dl fails with TypeError on iplayer video, youtube video downloads. 

### ISSUE THREAD

**Issue by EdgarCarpenter** [rg3/youtube-dl#6363]
Youtube-dl is failing when trying to download any video from BBC's iplayer.  I'm getting a TypeError failure. 

edgarpc saved # youtube-dl -v http://www.bbc.co.uk/iplayer/episode/p02qs82x/frankie-boyles-election-autopsy
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.bbc.co.uk/iplayer/episode/p02qs82x/frankie-boyles-election-autopsy']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.07.21
[debug] Python version 2.7.9 - Linux-3.16.0-4-amd64-x86_64-with-LinuxMint-2-betsy
[debug] exe versions: avconv 2.6.3, avprobe 2.6.3, ffmpeg 2.6.3, ffprobe 2.6.3, rtmpdump 2.4
[debug] Proxy map: {}
[bbc.co.uk] p02qs82x: Downloading video page
[bbc.co.uk] p02qs85f: Downloading media selection XML
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 410, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 400, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1503, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 656, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 275, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/bbccouk.py", line 361, in _real_extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/bbccouk.py", line 281, in _download_media_selector
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/bbccouk.py", line 218, in _extract_video
TypeError: int() argument must be a string or a number, not 'NoneType'

**Comment by dstftw** [comment]
Already fixed.

**Comment by EdgarCarpenter** [comment]
I'm running the latest youtube-dl, and the debug info above was from moments ago.   Is it fixed but not rolled out yet?

**Comment by dstftw** [comment]
Yes.

**Comment by EdgarCarpenter** [comment]
Thanks!
