### ISSUE TITLE
[NowVideo] Extractor AttributeError: 'NoneType' object has no attribute 'to_screen'

### ISSUE THREAD

**Issue by mrd1no** [rg3/youtube-dl#6374]
URL: http://www.nowvideo.li/video/7c345049b9419
OUTPUT:
Traceback (most recent call last):
  File "info.py", line 39, in <module>
    NowVideoIE().extract(url)
  File "C:\Python34\lib\site-packages\youtube_dl\extractor\common.py", line 275, in extract
    return self._real_extract(url)
  File "C:\Python34\lib\site-packages\youtube_dl\extractor\novamov.py", line 45, in _real_extract
    'http://%s/video/%s' % (self._HOST, video_id), video_id, 'Downloading video page')
  File "C:\Python34\lib\site-packages\youtube_dl\extractor\common.py", line 426, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding)
  File "C:\Python34\lib\site-packages\youtube_dl\extractor\common.py", line 333, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal)
  File "C:\Python34\lib\site-packages\youtube_dl\extractor\common.py", line 312, in _request_webpage
    self.to_screen('%s: %s' % (video_id, note))
  File "C:\Python34\lib\site-packages\youtube_dl\extractor\common.py", line 483, in to_screen
    self._downloader.to_screen('[%s] %s' % (self.IE_NAME, msg))
AttributeError: 'NoneType' object has no attribute 'to_screen'

I tried to reproduce the error and debug it step by step, but I couldn't give any valid msg argument in line 483 to extractor/common.py

Thank you for your help in advance!

Mauro

**Comment by dstftw** [comment]
Post the **full** output of youtube-dl when run [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by mrd1no** [comment]
Hi dstftw,

I reduced the script to the minimum to make it easier to debug:

[in]

from youtube_dl.extractor import NowVideoIE

url = "http://www.nowvideo.li/video/7c345049b9419"
NowVideoIE().initialize()
NowVideoIE().extract(url)

[out - from cmd shell using --verbose]

D:\>python nowvideo.py --verbose
Traceback (most recent call last):
  File "nowvideo.py", line 6, in <module>
    NowVideoIE().extract(url)
  File "C:\Python34\lib\site-packages\youtube_dl\extractor\common.py", line 275,
 in extract
    return self._real_extract(url)
  File "C:\Python34\lib\site-packages\youtube_dl\extractor\novamov.py", line 45,
 in _real_extract
    'http://%s/video/%s' % (self._HOST, video_id), video_id, 'Downloading video
page')
  File "C:\Python34\lib\site-packages\youtube_dl\extractor\common.py", line 426,
 in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote,
 fatal, encoding=encoding)
  File "C:\Python34\lib\site-packages\youtube_dl\extractor\common.py", line 333,
 in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal)
  File "C:\Python34\lib\site-packages\youtube_dl\extractor\common.py", line 312,
 in _request_webpage
    self.to_screen('%s: %s' % (video_id, note))
  File "C:\Python34\lib\site-packages\youtube_dl\extractor\common.py", line 483,
 in to_screen
    self._downloader.to_screen('[%s] %s' % (self.IE_NAME, msg))
AttributeError: 'NoneType' object has no attribute 'to_screen'

============================================================
Was it more helpful? May I do anything to make the investigation about this issue easier?

Thank you again!

Mauro

**Comment by dstftw** [comment]
What are you trying to achieve? For embedding youtube-dl you should use it [like that](https://github.com/rg3/youtube-dl#embedding-youtube-dl).

**Comment by mrd1no** [comment]
I was trying to download this video from nowvideo.

The idea it was to integrate this part of the code in another that is using selenium and lxml to collect the links to the episodes of a tv show.

**Comment by jaimeMF** [comment]
Extractor are not designed to be used standalone, you can just do:
```python
import youtube_dl

ydl_opts = {}
with youtube_dl.YoutubeDL(ydl_opts) as ydl:
    info = ydl.extract_info(URL, download=False)
