### ISSUE TITLE
Letv 403 error

### ISSUE THREAD

**Issue by hrzhu** [rg3/youtube-dl#6375]
Get a 403 when trying to download a video
```
python-2.7.10@playground | ruby-2.2.2@playground ~ [12:07:36]
♥ [hachimaki] youtube-dl http://www.letv.com/ptv/vplay/23172891.html\?ref\=baiduletv --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://www.letv.com/ptv/vplay/23172891.html?ref=baiduletv', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.07.21
[debug] Git HEAD: 3db1ac1
[debug] Python version 2.7.10 - Linux-3.16.0-41-generic-x86_64-with-debian-jessie-sid
[debug] exe versions: avconv 9.18-6, avprobe 9.18-6, ffmpeg 2.7.2-static, ffprobe 2.7.2-static
[debug] Proxy map: {}
[Letv] 23172891: Downloading webpage
[Letv] 23172891: Downloading playJson data
WARNING: unable to extract description; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[debug] Invoking downloader on u'http://g3.letv.cn/vod/v2/MTU5LzMvNy9sZXR2LXV0cy8xOS92ZXJfMDBfMjItMzIzOTczOTk3LWF2Yy0xNjkzODI1LWFhYy00NTM2NS01NjYzMTkzLTEyNDE5NjA1MTYtOWE4Y2YwZjQyNmU0NmU2ZmQ1ZjBmOWRhMTg2ZGY2MTctMTQzNzkyMzM0MTk3NS5tcDQ=?splatid=1401&b=%5Bu%271754%27%5D&playid=%5Bu%270%27%5D&payff=%5Bu%270%27%5D&tm=%5Bu%271437970140%27%5D&mmsid=%5Bu%2733644516%27%5D&retry=1&key=%5Bu%27837a63efac8208485d5bb2781e21237c%27%5D&pip=%5Bu%27a46d37fc0d44e7c36eddb2e889e39993%27%5D&vtype=%5Bu%2751%27%5D&platid=14&cvid=%5Bu%27450262258542%27%5D&tss=no'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/home/hachimaki/.pyenv/versions/2.7.10@playground/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 1435, in process_info
    success = dl(filename, info_dict)
  File "/home/hachimaki/.pyenv/versions/2.7.10@playground/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 1377, in dl
    return fd.download(name, info)
  File "/home/hachimaki/.pyenv/versions/2.7.10@playground/lib/python2.7/site-packages/youtube_dl/downloader/common.py", line 342, in download
    return self.real_download(filename, info_dict)
  File "/home/hachimaki/.pyenv/versions/2.7.10@playground/lib/python2.7/site-packages/youtube_dl/downloader/http.py", line 59, in real_download
    data = self.ydl.urlopen(request)
  File "/home/hachimaki/.pyenv/versions/2.7.10@playground/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 1731, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/home/hachimaki/.pyenv/versions/2.7.10/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/home/hachimaki/.pyenv/versions/2.7.10/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/hachimaki/.pyenv/versions/2.7.10/lib/python2.7/urllib2.py", line 469, in error
    result = self._call_chain(*args)
  File "/home/hachimaki/.pyenv/versions/2.7.10/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/home/hachimaki/.pyenv/versions/2.7.10/lib/python2.7/urllib2.py", line 656, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/home/hachimaki/.pyenv/versions/2.7.10/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/home/hachimaki/.pyenv/versions/2.7.10/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/hachimaki/.pyenv/versions/2.7.10/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/home/hachimaki/.pyenv/versions/2.7.10/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/home/hachimaki/.pyenv/versions/2.7.10/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden
```

I can download the same video with you-get and I could download previous episodes with youtude-dl like a month ago.

**Comment by sceext2** [comment]
I also met this bug. 

```
$ python -m youtube_dl -v "http://www.letv.com/ptv/vplay/23164109.html"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.letv.com/ptv/vplay/23164109.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.07.21
[debug] Git HEAD: 4c6bd5b
[debug] Python version 3.4.3 - Linux-4.1.2-2-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 2.7.2, ffprobe 2.7.2, rtmpdump 2.4
[debug] Proxy map: {}
[Letv] 23164109: Downloading webpage
[Letv] 23164109: Downloading playJson data
[debug] Invoking downloader on 'http://g3.letv.cn/vod/v2/MTc1LzMvNC9sZXR2LXV0cy8xNC92ZXJfMDBfMjItMzIzODc5MDczLWF2Yy0yOTk3NjE5LWFhYy0xMjgwMDEtMjcyNDA0MC0xMDY4Mzc2NTU0LTAyYmU3ZjNiY2I2YjliNjQzYzBhNjE4NzFiMWExZDJjLTE0Mzc3NjUyODY1MzkubXA0?vtype=%5B%2752%27%5D&tss=no&mmsid=%5B%2733612520%27%5D&splatid=1401&pip=%5B%27abe56cd09a2de8c5dafa65e041e4e8c2%27%5D&platid=14&playid=%5B%270%27%5D&key=%5B%27a9cce62ac4ccc432ce16f52503d5ac58%27%5D&b=%5B%273137%27%5D&cvid=%5B%27327136352337%27%5D&payff=%5B%270%27%5D&tm=%5B%271437971754%27%5D&retry=1'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/home/d/u/home/sceext/_/r/ev/youtube_dl/youtube_dl/YoutubeDL.py", line 1436, in process_info
    success = dl(filename, info_dict)
  File "/home/d/u/home/sceext/_/r/ev/youtube_dl/youtube_dl/YoutubeDL.py", line 1378, in dl
    return fd.download(name, info)
  File "/home/d/u/home/sceext/_/r/ev/youtube_dl/youtube_dl/downloader/common.py", line 342, in download
    return self.real_download(filename, info_dict)
  File "/home/d/u/home/sceext/_/r/ev/youtube_dl/youtube_dl/downloader/http.py", line 59, in real_download
    data = self.ydl.urlopen(request)
  File "/home/d/u/home/sceext/_/r/ev/youtube_dl/youtube_dl/YoutubeDL.py", line 1732, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 469, in open
    response = meth(req, response)
  File "/usr/lib/python3.4/urllib/request.py", line 579, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.4/urllib/request.py", line 501, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 441, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 684, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 469, in open
    response = meth(req, response)
  File "/usr/lib/python3.4/urllib/request.py", line 579, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.4/urllib/request.py", line 507, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 441, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 587, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

$ 
```

**Comment by yan12125** [comment]
I have a kind-of-dirty solution at #6376. If you have a better idea, please propose it.

**Comment by remitamine** [comment]
why not decrypt the m3u8 manifest in the let extractor and save it in HDD and pass the file path and in the hls downloader test if it's a url than continue as usual and if it's a file than open it from the file system at the end delete the file at the end.

**Comment by yan12125** [comment]
Letv extractors works again for me. @hrzhu @sceext2 could you check it again?

**Comment by hrzhu** [comment]
Yes, it works now.

**Comment by yan12125** [comment]
I'm closing this now as it works. Feel free to open a new issue if Letv is broken again.
