### ISSUE TITLE
Error in extracting videos from BBC 4

### ISSUE THREAD

**Issue by Pat38** [rg3/youtube-dl#6381]
Hi everybody,

Since a few days, it's become impossible to download any videos from the BBC.

Here is the command line : 
youtube-dl --verbose http://www.bbc.co.uk/iplayer/episode/p02vf6z5/partners-in-crime-1-the-secret-adversary-part-one

Here is the result : 
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.bbc.co.uk/iplayer/episode/p02vf6z5/partners-in-crime-1-the-secret-adversary-part-one']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.07.21
[debug] Python version 2.7.10 - Darwin-14.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.7.2, ffprobe 2.7.2, rtmpdump 2.4
[debug] Proxy map: {}
[bbc.co.uk] p02vf6z5: Downloading video page
[bbc.co.uk] b06496b6: Downloading media selection XML
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/opt/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/opt/local/bin/youtube-dl/youtube_dl/__init__.py", line 410, in main
  File "/opt/local/bin/youtube-dl/youtube_dl/__init__.py", line 400, in _real_main
  File "/opt/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1503, in download
  File "/opt/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 656, in extract_info
  File "/opt/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 275, in extract
  File "/opt/local/bin/youtube-dl/youtube_dl/extractor/bbccouk.py", line 361, in _real_extract
  File "/opt/local/bin/youtube-dl/youtube_dl/extractor/bbccouk.py", line 281, in _download_media_selector
  File "/opt/local/bin/youtube-dl/youtube_dl/extractor/bbccouk.py", line 218, in _extract_video
TypeError: int() argument must be a string or a number, not 'NoneType'

Is there a way to solve the problem ?

**Comment by dstftw** [comment]
This issue is already fixed and will be available in the next version of youtube-dl. Until new version releaed you run youtube-dl from [sources](https://github.com/rg3/youtube-dl/archive/master.zip) as described in [developer instuctions](https://github.com/rg3/youtube-dl#developer-instructions).
