### ISSUE TITLE
iplayer BBC not working anymore since Sunday

### ISSUE THREAD

**Issue by jpfl** [rg3/youtube-dl#6386]
Saturdays F1 Qualifying I could still download.
all files from shunday on did not work anymore.

e.g.:
http://www.bbc.co.uk/iplayer/episode/b063zxl5/formula-1-2015-highlights-hungarian-grand-prix

  File "youtube_dl\extractor\bbccouk.pyo", line 218, in _extract_video
TypeError: int() argument must be a string or a number, not 'NoneType'
[bbc.co.uk] b063zxl5: Downloading video page
[bbc.co.uk] b063zxkt: Downloading media selection XML
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "youtube_dl\__init__.pyo", line 406, in main
  File "youtube_dl\__init__.pyo", line 396, in _real_main
  File "youtube_dl\YoutubeDL.pyo", line 1501, in download
  File "youtube_dl\YoutubeDL.pyo", line 654, in extract_info
  File "youtube_dl\extractor\common.pyo", line 273, in extract
  File "youtube_dl\extractor\bbccouk.pyo", line 361, in _real_extract
  File "youtube_dl\extractor\bbccouk.pyo", line 281, in _download_media_selector

**Comment by jaimeMF** [comment]
Could you try with the last version (2015.07.28, just realeased)? I can't access the video because it's georestricted, but according to #6381 the issue should be fixed.

For future reports please post the [full output you get when you run it with the `--verbose` option](https://github.com/rg3/youtube-dl/blob/f993afb26d20ac79891621494922887b3c8df02b/README.md#bug), it really helps us.

**Comment by jpfl** [comment]
I have updated the version right after the request sent and it was exactly the same error.
in the meantime I figured how to rip it. using the hds plugin for firefox and then php with the kds script.
but it would be much nicer and easier if this would work with the YTDL again.

**Comment by jaimeMF** [comment]
Please post the [full output you get when you run it with the `--verbose` option](https://github.com/rg3/youtube-dl/blob/f993afb26d20ac79891621494922887b3c8df02b/README.md#bug), it really helps us.

**Comment by dstftw** [comment]
Works fine with latest version.
