### ISSUE TITLE
[dailymotion] unable to extract video info

### ISSUE THREAD

**Issue by mildred** [rg3/youtube-dl#6387]
Here is what I get when trying to download a dailymotion video:

```
INS mildred@meryl:~$ youtube-dl --verbose -F 'http://www.dailymotion.com/video/x2x4x4k_lecons-d-introduction-historique-a-l-etude-du-droit-par-maitre-damien-viguier-1-6_news'
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '-F', 'http://www.dailymotion.com/video/x2x4x4k_lecons-d-introduction-historique-a-l-etude-du-droit-par-maitre-damien-viguier-1-6_news']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.07.21
[debug] Python version 3.4.3 - Linux-4.0.7-2-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 2.7.1, ffprobe 2.7.1, rtmpdump 2.4
[debug] Proxy map: {}
[dailymotion] x2x4x4k: Downloading webpage
[dailymotion] x2x4x4k: Extracting information
[dailymotion] x2x4x4k: Downloading embed page
ERROR: Unable to extract video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 656, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 275, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/dailymotion.py", line 120, in _real_extract
    'video info', flags=re.MULTILINE)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 557, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

INS mildred@meryl:~$ youtube-dl  --version
2015.07.21
```

**Comment by jaimeMF** [comment]
It should be fixed in version 2015.07.28. Thanks for the report.
