### ISSUE TITLE
410 HTTP error on a YouTube video that is still up and viewable

### ISSUE THREAD

**Issue by vxbinaca** [rg3/youtube-dl#6413]
```
youtube-dl --verbose https://www.youtube.com/watch?v=I7AsdDpWtHY
```
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://www.youtube.com/watch?v=I7AsdDpWtHY']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.07.28
[debug] Python version 2.7.9 - Linux-3.19.0-25-generic-x86_64-with-Ubuntu-15.04-vivid
[debug] exe versions: avconv 11.2-6, avprobe 11.2-6, ffmpeg 2.5.7-0ubuntu0.15.04.1, ffprobe 2.5.7-0ubuntu0.15.04.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] I7AsdDpWtHY: Downloading webpage
[youtube] I7AsdDpWtHY: Downloading video info webpage
[youtube] I7AsdDpWtHY: Extracting video information
[youtube] I7AsdDpWtHY: Downloading DASH manifest
[youtube] I7AsdDpWtHY: Downloading DASH manifest
[debug] Invoking downloader on 'https://r6---sn-hp57kn7z.googlevideo.com/videoplayback?id=23b02c743a56b476&itag=134&source=youtube&requiressl=yes&pl=17&mm=31&mn=sn-hp57kn7z&ms=au&mv=m&nh=IgpwcjAzLm1pYTA0KgkxMjcuMC4wLjE&ratebypass=yes&mime=video/mp4&gir=yes&clen=29898618&lmt=1414139019285128&dur=758.566&signature=84AFF4E4596CC0F91F8E232603FA60423CFE28BD.3C4842EA2D97E84968FF8EBF81E88B701D532204&mt=1438302774&upn=3dMtwmYtf8c&key=dg_yt0&sver=3&fexp=9407147,9407943,9408491,9408710,9412857,9413317,9415365,9415430,9415436,9415485,9415873,9416126,9416279,9416906,9416985,9417942,9418200&ip=73.28.76.5&ipbits=0&expire=1438324424&sparams=ip,ipbits,expire,id,itag,source,requiressl,pl,mm,mn,ms,mv,nh,ratebypass,mime,gir,clen,lmt,dur'
ERROR: unable to download video data: HTTP Error 410: Gone
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1430, in process_info
    partial_success = dl(fname, new_info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1378, in dl
    return fd.download(name, info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/common.py", line 342, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/http.py", line 59, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1732, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 410: Gone
```

What's more interesting is if a more archival appraoch is taken the metadata is downloaded for a video that supposedly doesn't exist as well.

```
youtube-dl --verbose --title --continue --write-info-json --write-description --write-thumbnail --write-annotations --all-subs -f bestvideo+bestaudio I7AsdDpWtHY
```
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'--title', u'--continue', u'--write-info-json', u'--write-description', u'--write-thumbnail', u'--write-annotations', u'--all-subs', u'-f', u'bestvideo+bestaudio', u'I7AsdDpWtHY']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.07.28
[debug] Python version 2.7.9 - Linux-3.19.0-25-generic-x86_64-with-Ubuntu-15.04-vivid
[debug] exe versions: avconv 11.2-6, avprobe 11.2-6, ffmpeg 2.5.7-0ubuntu0.15.04.1, ffprobe 2.5.7-0ubuntu0.15.04.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] I7AsdDpWtHY: Downloading webpage
[youtube] I7AsdDpWtHY: Downloading video info webpage
[youtube] I7AsdDpWtHY: Extracting video information
WARNING: video doesn't have subtitles
[youtube] I7AsdDpWtHY: Searching for annotations.
[youtube] I7AsdDpWtHY: Downloading DASH manifest
[youtube] I7AsdDpWtHY: Downloading DASH manifest
[info] Writing video description to: Leigh Alexander Explains Video Game Journalism #GamerGate-I7AsdDpWtHY.description
[info] Writing video annotations to: Leigh Alexander Explains Video Game Journalism #GamerGate-I7AsdDpWtHY.annotations.xml
[info] Writing video description metadata as JSON to: Leigh Alexander Explains Video Game Journalism #GamerGate-I7AsdDpWtHY.info.json
[youtube] I7AsdDpWtHY: Downloading thumbnail ...
[youtube] I7AsdDpWtHY: Writing thumbnail to: Leigh Alexander Explains Video Game Journalism #GamerGate-I7AsdDpWtHY.jpg
[debug] Invoking downloader on 'https://r6---sn-hp57kn7z.googlevideo.com/videoplayback?id=23b02c743a56b476&itag=134&source=youtube&requiressl=yes&nh=IgpwcjAzLm1pYTA0KgkxMjcuMC4wLjE&pl=17&mm=31&mn=sn-hp57kn7z&mv=m&ms=au&ratebypass=yes&mime=video/mp4&gir=yes&clen=29898618&lmt=1414139019285128&dur=758.566&fexp=9408093,9408492,9408710,9415091,9415365,9415429,9415485,9415868,9416126,9416555,9416688,9417581,9417931,9418062,9418200&signature=52C5CC4A4013272F0995F8A5EACB71A691FF64F4.900F5BA5C2622676FC6FFE8D41DD5330807BD7BB&key=dg_yt0&sver=3&upn=XIaRblJunt8&mt=1438302891&ip=73.28.76.5&ipbits=0&expire=1438324531&sparams=ip,ipbits,expire,id,itag,source,requiressl,nh,pl,mm,mn,mv,ms,ratebypass,mime,gir,clen,lmt,dur'
ERROR: unable to download video data: HTTP Error 410: Gone
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1430, in process_info
    partial_success = dl(fname, new_info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1378, in dl
    return fd.download(name, info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/common.py", line 342, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/http.py", line 59, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1732, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 410: Gone
```

**Comment by remitamine** [comment]
for this video it happen only for format 134 i don't but when requesting the HEAD it said that the respnse is OK(200):
```
curl -I -L $(youtube-dl -g -f 134 https://www.youtube.com/watch?v=I7AsdDpWtHY)
HTTP/1.1 200 OK
Last-Modified: Fri, 24 Oct 2014 08:23:39 GMT
Content-Type: video/mp4
Date: Fri, 31 Jul 2015 06:48:04 GMT
Expires: Fri, 31 Jul 2015 06:48:04 GMT
Cache-Control: private, max-age=21297
Accept-Ranges: bytes
Content-Length: 29898618
Connection: close
Alternate-Protocol: 443:quic,p=0.45
X-Content-Type-Options: nosniff
Server: gvs 1.0
```

**Comment by vxbinaca** [comment]
This bug is really weird.

**Comment by jaimeMF** [comment]
This is a YouTube error, they list the format in their webpage. Unfortunately this happens from time to time with some videos, the only solution is to download other format.
