### ISSUE TITLE
TypeError when downloading BBC iPlayer video

### ISSUE THREAD

**Issue by l0b0** [rg3/youtube-dl#6416]
$ youtube-dl 'http://www.bbc.co.uk/iplayer/episode/b062mfw7/artsnight-series-2-4-samira-ahmed'
    [bbc.co.uk] b062mfw7: Downloading video page
    [bbc.co.uk] b062mfv7: Downloading media selection XML
    Traceback (most recent call last):
      File "/usr/bin/youtube-dl", line 9, in <module>
        load_entry_point('youtube-dl==2015.7.21', 'console_scripts', 'youtube-dl')()
      File "/usr/lib/python3.4/site-packages/youtube_dl/__init__.py", line 410, in main
        _real_main(argv)
      File "/usr/lib/python3.4/site-packages/youtube_dl/__init__.py", line 400, in _real_main
        retcode = ydl.download(all_urls)
      File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 1503, in download
        url, force_generic_extractor=self.params.get('force_generic_extractor', False))
      File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 656, in extract_info
        ie_result = ie.extract(url)
      File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 275, in extract
        return self._real_extract(url)
      File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/bbccouk.py", line 361, in _real_extract
        formats, subtitles = self._download_media_selector(programme_id)
      File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/bbccouk.py", line 281, in _download_media_selector
        formats.extend(self._extract_video(media, programme_id))
      File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/bbccouk.py", line 218, in _extract_video
        file_size = int(media.get('media_file_size'))
    TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
    $ youtube-dl --version
    2015.07.21

**Comment by l0b0** [comment]
Found issue #6386; closing.
