### ISSUE TITLE
nasa download HTTP error()

### ISSUE THREAD

**Issue by Lawrence4sure** [rg3/youtube-dl#6417]
[chronos:youtube-dl ]> ./youtube-dl --verbose https://www.youtube.com/watch?t=63&v=xu0TtqIybsI
[1] 3348
[chronos:youtube-dl ]> [debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://www.youtube.com/watch?t=63']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.07.28
[debug] Python version 2.7.5 - Darwin-13.4.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[generic] watch?t=63: Requesting header
[redirect] Following redirect to https://www.youtube.com/supported_browsers?next_url=%2F
[youtube:user] supported_browsers: Downloading channel page
WARNING: Unable to download webpage: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "./youtube-dl/__main__.py", line 19, in <module>
  File "./youtube-dl/youtube_dl/__init__.py", line 410, in main
  File "./youtube-dl/youtube_dl/__init__.py", line 400, in _real_main
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 1504, in download
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 667, in extract_info
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 720, in process_ie_result
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 656, in extract_info
  File "./youtube-dl/youtube_dl/extractor/common.py", line 279, in extract
  File "./youtube-dl/youtube_dl/extractor/youtube.py", line 1516, in _real_extract
  File "./youtube-dl/youtube_dl/extractor/common.py", line 666, in _html_search_meta
  File "./youtube-dl/youtube_dl/extractor/common.py", line 570, in _html_search_regex
  File "./youtube-dl/youtube_dl/extractor/common.py", line 540, in _search_regex
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py", line 142, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or buffer

[1]+  Exit 1                  ./youtube-dl --verbose https://www.youtube.com/watch?t=63
[chronos:youtube-dl ]>

**Comment by remitamine** [comment]
in linux you should put strings that conatain & between ' or " like that:
youtube-dl 'https://www.youtube.com/watch?t=63&v=xu0TtqIybsI'

**Comment by jaimeMF** [comment]
@remitamine is right, read the [FAQ](https://github.com/rg3/youtube-dl/blob/f993afb26d20ac79891621494922887b3c8df02b/README.md#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command) for more info.
