### ISSUE TITLE
Tudou Error 403

### ISSUE THREAD

**Issue by liaohaohui** [rg3/youtube-dl#6425]
Running youtube_dl with version 2015.07.28 on Tudou as follows:

```
python -myoutube_dl -g --verbose http://www.tudou.com/programs/view/39b_veEwakk/?resourceId=0_06_02_99
```
produces the following output:
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-g', '--verbose', 'http://www.tudou.com/programs/view/39b_veEwakk/?resourceId=0_06_02_99']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.07.28
[debug] Git HEAD: 525a87f
[debug] Python version 3.4.2 - Linux-3.18.2-2-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 2.0, ffprobe 2.0, rtmpdump 2.4
[debug] Proxy map: {}
```
with the following error messages:
```
[Tudou] 39b_veEwakk: Downloading webpage
[Tudou] 39b_veEwakk: found 9 parts
[Tudou] 335880233: Opening the info webpage
[Tudou] 335880234: Opening the info webpage
[Tudou] 335880235: Opening the info webpage
[Tudou] 335880236: Opening the info webpage
[Tudou] 335880237: Opening the info webpage
[Tudou] 335880238: Opening the info webpage
[Tudou] 335880239: Opening the info webpage
[Tudou] 335880240: Opening the info webpage
[Tudou] 335880241: Opening the info webpage
[download] Downloading playlist: [TSKS]Assembly_06
[Tudou] playlist [TSKS]Assembly_06: Collected 9 video ids (downloading 9 of them)
[download] Downloading video 1 of 9
[debug] Invoking downloader on 'http://111.206.132.81/f4v/34/236719134.h264_1_seg_0.040012090055BAD2FDA9E231F37BF685F88CCC-FE3B-5DE6-AAAC-000335880233.f4v?key=78735b21e4bcd1eb249a6355bcb71f0040908c9f9a&qrs=1367658095&p=17652962957293886312&playtype=12&tk=143483463684501481270259018&brt=12&bc=0&xid=040012090055BAD2FDA9E231F37BF685F88CCC-FE3B-5DE6-AAAC-000335880233&nt=0&nw=1&bs=0&ispid=800615&rc=200&inf=12&si=un&npc=4265&pp=-1&ul=0&mt=0&sid=0&pc=0&cip=60.49.48.9&id=tudou&hf=0&hd=0&sta=0&ssid=0&cvid=&itemid=335880233&fi=0&sz=15411079'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/home/liaohaohui/zTmp/youtube_dl/YoutubeDL.py", line 1436, in process_info
    success = dl(filename, info_dict)
  File "/home/liaohaohui/zTmp/youtube_dl/YoutubeDL.py", line 1378, in dl
    return fd.download(name, info)
  File "/home/liaohaohui/zTmp/youtube_dl/downloader/common.py", line 342, in download
    return self.real_download(filename, info_dict)
  File "/home/liaohaohui/zTmp/youtube_dl/downloader/http.py", line 59, in real_download
    data = self.ydl.urlopen(request)
  File "/home/liaohaohui/zTmp/youtube_dl/YoutubeDL.py", line 1732, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 461, in open
    response = meth(req, response)
  File "/usr/lib/python3.4/urllib/request.py", line 571, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.4/urllib/request.py", line 499, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 433, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 579, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by yan12125** [comment]
Can you watch this video in browsers? I got the following error: (I'm outside Mainland China)
```
对不起，由于版权原因，
该视频暂时不能播放。
```
Which means: Sorry, this video is temporarily unavailable due to licensing reasons.

A side note: according to the 4th item in [this FAQ](https://zhuzhuor.wufoo.com/forms/z1soe3bh0c173o4/) (in Chinese), such an error indicates the video is unavailable in Mainland China, too.

**Comment by liaohaohui** [comment]
When I posed the report, I was able to watch it with Firefox under Linux from Malaysia.  They probably discovered the loop hole (which happened during the Tudou and Youku merger?) and remove the video or disable it.  Anyway a big thanks to your wonderful software.  I am extremely grateful.

**Comment by yan12125** [comment]
OK. I'm closing this issue as it's not youtube-dl's problem. Feel free to open a new issue if you have other problems.
