### ISSUE TITLE
Join multiple audio streams into mkv

### ISSUE THREAD

**Issue by jengelh** [rg3/youtube-dl#6430]
Following up on #5784. youtube-dl is currently not capable of downloading-and-merging multiple audio tracks (perhaps even video tracks). It already supports merging into MKV containers on some occassions (e.g. "Requested formats are incompatible for merge and will be merged into mkv."), and so it could just go the same route in case of multi-audio/multi-sub.
```
$ ./youtube-dl -f best+en+jp http://www.gdcvault.com/play/1014631/Classic-Game-Postmortem-PAC
[GDCVault] Classic-Game-Postmortem-PAC: Downloading webpage
[GDCVault] Classic-Game-Postmortem-PAC: Downloading XML
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "./youtube-dl/__main__.py", line 19, in <module>
  File "./youtube-dl/youtube_dl/__init__.py", line 410, in main
  File "./youtube-dl/youtube_dl/__init__.py", line 400, in _real_main
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 1504, in download
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 667, in extract_info
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 713, in process_ie_result
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 1125, in process_video_result
ValueError: too many values to unpack
```

**Comment by Efreak** [comment]
I just spent the past good while looking for this. I'd like to have multiple audio tracks for a youtube file--if the 'best' audio is opus, then I also want mp3 or mp4a for my embedded devices.

It would also be nice to be able to choose the best *and* worst video versions (256x144 + 1920x1080) for PIP playback, but unfortunately, afaik no software actually supports such usage :(

**Comment by enveeed** [comment]
I think its generally possible to download the individual tracks (via selecting them from `-F` output) and later merge them into mkv with `ffmpeg`/`avconv` but I have no idea how to do this manually, I'd love to see something like this built into this great tool
