### ISSUE TITLE
I can't download BBC.com/news/ video

### ISSUE THREAD

**Issue by hub2git** [rg3/youtube-dl#6453]
Exact URL is http://www.bbc.com/news/video_and_audio/must_see/33376376. 
$ youtube-dl -v http://www.bbc.com/news/video_and_audio/must_see/33376376
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.bbc.com/news/video_and_audio/must_see/33376376']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.06.15
[debug] Python version 2.7.6 - Linux-3.13.0-37-generic-x86_64-with-LinuxMint-17.1-rebecca
[debug] exe versions: avconv 9.18-6, avprobe 9.18-6, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 33376376: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 33376376: Downloading webpage
[generic] 33376376: Extracting information
ERROR: Unsupported URL: http://www.bbc.com/news/video_and_audio/must_see/33376376
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1020, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1558, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 80, column 548
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 650, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 273, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1571, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.bbc.com/news/video_and_audio/must_see/33376376

**Comment by hub2git** [comment]
Thank you. I can now download the video!
