### ISSUE TITLE
southpark.de: UnicodeDecodeError 'ascii' codec can't decode byte in position

### ISSUE THREAD

**Issue by PotcFdk** [rg3/youtube-dl#6457]
Calling youtube-dl with this URL works:
`http://www.southpark.de/alle-episoden/s09e08-der-treibhauseffekt`
as does a shorter version, which redirects to the previous one:
`http://www.southpark.de/alle-episoden/s09e08`

However, while this one works:
`http://www.southpark.de/alle-episoden/s09e09-das-weissagungsger%C3%A4t`
the shorter version does not:
`http://www.southpark.de/alle-episoden/s09e09`

Episode 10, `Ei-fersucht`, works again, while episode 11, `Im Körper des Feindes`, does not.
It seems to be caused by the umlaut in the episode's title (/ url ?).

```
[southpark.de] s09e09: Downloading webpage
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "./youtube-dl/__main__.py", line 19, in <module>
  File "./youtube-dl/youtube_dl/__init__.py", line 410, in main
  File "./youtube-dl/youtube_dl/__init__.py", line 400, in _real_main
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 1504, in download
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 656, in extract_info
  File "./youtube-dl/youtube_dl/extractor/common.py", line 279, in extract
  File "./youtube-dl/youtube_dl/extractor/mtv.py", line 185, in _real_extract
  File "./youtube-dl/youtube_dl/extractor/common.py", line 430, in _download_webpage
  File "./youtube-dl/youtube_dl/extractor/common.py", line 337, in _download_webpage_handle
  File "./youtube-dl/youtube_dl/extractor/common.py", line 318, in _request_webpage
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 1732, in urlopen
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 469, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 656, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "./youtube-dl/youtube_dl/utils.py", line 635, in http_open
  File "/usr/lib/python2.7/urllib2.py", line 1194, in do_open
    h.request(req.get_method(), req.get_selector(), req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 1001, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1035, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 997, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 842, in _send_output
    msg = "\r\n".join(self._buffer)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 44: ordinal not in range(128)
```

**Comment by dstftw** [comment]
This issue has been fixed and will be available in the next version. Thanks for the report.
