### ISSUE TITLE
pornhub broken? "no video formats found."

### ISSUE THREAD

**Issue by gregist** [rg3/youtube-dl#6465]
```
$ youtube-dl -g --verbose http://www.pornhub.com/view_video.php?viewkey=870428357
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-g', '--verbose', 'http://www.pornhub.com/view_video.php?viewkey=870428357']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.07.28
[debug] Python version 3.4.3 - Linux-4.0.7-2-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 2.7.1, ffprobe 2.7.1, rtmpdump 2.4
[debug] Proxy map: {'rsync': 'http://127.0.0.1:7070/', 'https': 'http://127.0.0.1:7070/', 'no': 'localhost,127.0.0.1,localaddress,.localdomain.com', 'http': 'http://127.0.0.1:7070/', 'ftp': 'http://127.0.0.1:7070/'}
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 656, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 279, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/pornhub.py", line 113, in _real_extract
    self._sort_formats(formats)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 735, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by dstftw** [comment]
This issue is already fixed and will be available in the next version of youtube-dl.
