### ISSUE TITLE
xhamster support broken

### ISSUE THREAD

**Issue by vijayanandnandam** [rg3/youtube-dl#6466]
```
➜  ~  youtube-dl https://xhamster.com/movies/2479185/threes_company_for_fisting_and_squirting_masterpiece.html\?from\=promo_block
[XHamster] 2479185: Downloading webpage
WARNING: unable to extract thumbnail; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
ERROR: Unable to extract media URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
➜  ~  youtube-dl https://xhamster.com/movies/2479185/threes_company_for_fisting_and_squirting_masterpiece.html\?from\=promo_block --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'https://xhamster.com/movies/2479185/threes_company_for_fisting_and_squirting_masterpiece.html?from=promo_block', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.07.28
[debug] Python version 2.7.6 - Darwin-14.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg present, ffprobe present, rtmpdump 2.4
[debug] Proxy map: {}
[XHamster] 2479185: Downloading webpage
WARNING: unable to extract thumbnail; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
ERROR: Unable to extract media URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 656, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 279, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/xhamster.py", line 100, in _real_extract
    video_url = extract_video_url(webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/xhamster.py", line 52, in extract_video_url
    raise ExtractorError('Unable to extract media URL')
ExtractorError: Unable to extract media URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by vijayanandnandam** [comment]
fixed in pull request #6467
