### ISSUE TITLE
ADD Req: www.xxxbunker.com 

### ISSUE THREAD

**Issue by kendalls63** [rg3/youtube-dl#6471]
Updated youtube-dl to version 2015.07.28
http://xxxbunker.com/#!/1438818007667V1347597
youtube-dl http://xxxbunker.com/#!/1438818007667V1347597
tried several on this site. Get following error:

[generic] 1438818007667V1347597: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 1438818007667V1347597: Downloading webpage
[generic] 1438818007667V1347597: Extracting information
ERROR: unable to download video data: HTTP Error 404: Not Found

**Comment by dstftw** [comment]
This looks like copyrighted content. youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free). Do they have rights to distribute this? If not it has to be replaced with one that does not violate any copyrights.

**Comment by kendalls63** [comment]
Weird, the URL I posted goes to a different video every time I paste it in a browser. Not sure how they do that, but this site is more or less just a search site. I found most of the videos elsewhere. You can close this one.

**Comment by sebma** [comment]
@yan12125 Can you please reopen this issue and try to solve it with this : 

```
$ youtube-dl --ignore-config -v http://xxxbunker.com/amateur_french_slut_lilou_gangbanged
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--ignore-config', u'-v', u'http://xxxbunker.com/amateur_french_slut_lilou_gangbanged']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.09.02
[debug] Python version 2.7.12 - Linux-4.4.0-93-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.20-6, avprobe 9.20-6, ffmpeg 3.3.3, ffprobe 3.3.3, rtmpdump 2.4
[debug] Proxy map: {}
[generic] amateur_french_slut_lilou_gangbanged: Requesting header
WARNING: Falling back on generic information extractor.
[generic] amateur_french_slut_lilou_gangbanged: Downloading webpage
[generic] amateur_french_slut_lilou_gangbanged: Extracting information
WARNING: Your copy of avconv is outdated and unable to properly mux separate video and audio files, youtube-dl will download single file media. Update avconv to version 10-0 or newer to fix this.
[debug] Default format spec: best
[debug] Invoking downloader on u'http://xxxbunker.com/https%3A%2F%2Fxxxbunker.com%2Fvideos%2Finternal%2Fy8a5qoned88e3acb429.flv'
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1865, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1807, in dl
    return fd.download(name, info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/common.py", line 361, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/http.py", line 286, in real_download
    establish_connection()
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/http.py", line 74, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 2168, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found
```

**Comment by yan12125** [comment]
@sebma: This website wont't be supported as most videos violates copyright.

**Comment by sebma** [comment]
@yan12125 The video I gave does not violate copyright

**Comment by yan12125** [comment]
@sebma: It indeed violates copyright. This video is created by sextvx, and the original copy can be found at https://www.sextvx.com/video/711100/amateur-french-slut-lilou-gangbanged?play=t#
