### ISSUE TITLE
Unable to extract media URL on supported site xhamster

### ISSUE THREAD

**Issue by NyeMitchLee** [rg3/youtube-dl#6472]
I found youtube-dl wasn't working for xhamster.  I then checked that the first test URL in xhamster.py is a working page, then tested it.

```
$ youtube-dl --verbose http://xhamster.com/movies/1509445/femaleagent_shy_beauty_takes_the_bait.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://xhamster.com/movies/1509445/femaleagent_shy_beauty_takes_the_bait.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.07.28
[debug] Python version 3.4.3 - Linux-4.1.3-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 2.7.2, ffprobe 2.7.2, rtmpdump 2.4
[debug] Proxy map: {}
[XHamster] 1509445: Downloading webpage
WARNING: unable to extract thumbnail; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
ERROR: Unable to extract media URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 656, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 279, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/xhamster.py", line 100, in _real_extract
    video_url = extract_video_url(webpage)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/xhamster.py", line 52, in extract_video_url
    raise ExtractorError('Unable to extract media URL')
youtube_dl.utils.ExtractorError: Unable to extract media URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by dstftw** [comment]
This issue is already fixed and will be available in the next version of youtube-dl.

**Comment by NyeMitchLee** [comment]
Sorry for the repost of the issue, dstftw.  I tried searching issues before posting and didn't find it.  I see I mistakenly left "is:open" in my query.
