### ISSUE TITLE
madmoizelle.com

### ISSUE THREAD

**Issue by Rudloff** [rg3/youtube-dl#6491]
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://www.madmoizelle.com/ukulete-episode-1-408599', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.08.06.1
[debug] Python version 2.7.9 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.1
[debug] exe versions: avconv 11.4-6, avprobe 11.4-6, rtmpdump 2.4
[debug] Proxy map: {}
[generic] ukulete-episode-1-408599: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ukulete-episode-1-408599: Downloading webpage
[generic] ukulete-episode-1-408599: Extracting information
ERROR: Unsupported URL: http://www.madmoizelle.com/ukulete-episode-1-408599
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 1115, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/utils.py", line 1594, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 22, column 163
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 655, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 282, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 1704, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.madmoizelle.com/ukulete-episode-1-408599
```

**Comment by dstftw** [comment]
For me it's an YouTube embed that downloads just fine.

**Comment by Rudloff** [comment]
Are you sure?
For me it is a [JW Player](http://www.jwplayer.com/learn-more/).

**Comment by dstftw** [comment]
It was YouTube half an hour ago:
```
py26yt http://www.madmoizelle.com/ukulete-episode-1-408599
[generic] ukulete-episode-1-408599: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ukulete-episode-1-408599: Downloading webpage
[generic] ukulete-episode-1-408599: Extracting information
[download] Downloading playlist: Ukul’été - Épisode 1 - Plus besoin de radio !
[generic] playlist Ukul’été - Épisode 1 - Plus besoin de radio !: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[youtube] vRGHV2pVW0U: Downloading webpage
[youtube] vRGHV2pVW0U: Downloading video info webpage
[youtube] vRGHV2pVW0U: Extracting video information
[youtube] vRGHV2pVW0U: Downloading DASH manifest
[youtube] vRGHV2pVW0U: Downloading DASH manifest
[download] Destination: Ukul’t - pisode 1 - Plus besoin de radio !-vRGHV2pVW0U.f137.mp4
[download]   0.2% of 154.79MiB at 495.15KiB/s ETA 05:19
ERROR: Interrupted by user
```

**Comment by yan12125** [comment]
Maybe the site offers different videos for different geolocations. I got a jwplayer too in Taiwan.

**Comment by Rudloff** [comment]
I just noticed there is a Youtube embed in the page that sometimes triggers the Youtube extractor.
Here is another test video without a Youtube embed: http://www.madmoizelle.com/video-dix-ans-madmoizelle-458453

**Comment by Rudloff** [comment]
This seems to work now (using the youtube extractor).
