### ISSUE TITLE
youtube-dl & axel on windows

### ISSUE THREAD

**Issue by mbodomi** [rg3/youtube-dl#6499]
```
C:\Users\Administrator\Desktop>youtube-dl --external-downloader axel https:
//www.youtube.com/watch?v=5jS4uNxwe2U --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--external-downloader', u'axel', u'https://www.you
tube.com/watch?v=5jS4uNxwe2U', u'--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.08.06.1
[debug] Python version 2.7.8 - Windows-7-6.1.7600
[debug] exe versions: ffmpeg 2.5.2, ffprobe 2.5.2
[debug] Proxy map: {}
[youtube] 5jS4uNxwe2U: Downloading webpage
[youtube] 5jS4uNxwe2U: Downloading video info webpage
[youtube] 5jS4uNxwe2U: Extracting video information
[youtube] 5jS4uNxwe2U: Downloading DASH manifest
[youtube] 5jS4uNxwe2U: Downloading DASH manifest
WARNING: Requested formats are incompatible for merge and will be merged into mk
v.
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "youtube_dl\__init__.pyo", line 410, in main
  File "youtube_dl\__init__.pyo", line 400, in _real_main
  File "youtube_dl\YoutubeDL.pyo", line 1653, in download
  File "youtube_dl\YoutubeDL.pyo", line 666, in extract_info
  File "youtube_dl\YoutubeDL.pyo", line 712, in process_ie_result
  File "youtube_dl\YoutubeDL.pyo", line 1323, in process_video_result
  File "youtube_dl\YoutubeDL.pyo", line 1579, in process_info
  File "youtube_dl\YoutubeDL.pyo", line 1522, in dl
  File "youtube_dl\downloader\__init__.pyo", line 35, in get_suitable_downloader

  File "youtube_edl\downloader\external.pyo", line 136, in get_external_downloade
r
KeyError: u'axel'
```
((stupid linebreaks on screen by default settings on cmd.exe))

I have Axel 2,4 from this site: https://st0rage.org/~n2j3/?page_id=225717166
It's a cygwin build.
Till you :hammer:  it: (assuming *both* axel & youtube-dl exe's in path)
```powershell
axel $(youtube-dl -g URL)
```
just works :ok: in powershell

**Comment by dstftw** [comment]
axel is not supported in latest release. You should wait for next release or use version from repository.
