### ISSUE TITLE
error while downloading

### ISSUE THREAD

**Issue by githubuserromi** [rg3/youtube-dl#6512]
youtube-dl http://video.fc2.com/en/content/20140513qsb6VSB7

[fc2] 20140513qsb6VSB7: Downloading webpage
Traceback (most recent call last):
  File "/usr/lib64/python2.6/runpy.py", line 122, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.6/runpy.py", line 34, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 410, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 400, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1653, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 655, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 286, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/fc2.py", line 89, in _real_extract
  File "/usr/lib64/python2.6/urllib.py", line 1234, in quote
    safe_map[c] = (c in safe) and c or ('%%%02X' % i)
TypeError: 'in <string>' requires string as left operand

**Comment by phihag** [comment]
I can reproduce this problem on Python 2.6, but not 2.7, so it's a bug in youtube-dl under 2.6.
