### ISSUE TITLE
external-downloader error

### ISSUE THREAD

**Issue by gulbuhar** [rg3/youtube-dl#6519]
Hi, 

Im getting errors using "external-downloader" option enabled 

$ youtube-dl --proxy 127.0.0.1:9662 --external-downloader axel --external-downloader-args "-n20" --autonumber "0" -o "%(autonumber)s-%(title)s.%(ext)s" http://www.youtube.com/playlist?list=PLLnpHn493BHH5nnK2dKE_42l1oXA6Tq6H -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--proxy', '127.0.0.1:9662', '--external-downloader', 'axel', '--external-downloader-args', '-n20', '--autonumber', '0', '-o', '%(autonumber)s-%(title)s.%(ext)s', 'http://www.youtube.com/playlist?list=PLLnpHn493BHH5nnK2dKE_42l1oXA6Tq6H', '-v']
WARNING: No ssl certificates were loaded, urls that use https won't work
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.04.03
[debug] Python version 3.4.1 - Linux-4.0.5-gentoo-x86_64-Intel-R-_Core-TM-_i3-3110M_CPU_@_2.40GHz-with-gentoo-2.2
[debug] exe versions: ffmpeg 2.6.3, ffprobe 2.6.3
[debug] Proxy map: {'https': '127.0.0.1:9662', 'http': '127.0.0.1:9662'}
[youtube:playlist] PLLnpHn493BHH5nnK2dKE_42l1oXA6Tq6H: Downloading webpage
[download] Downloading playlist: Drupal Tutorials - The Complete Omega 4 Course
[youtube:playlist] playlist Drupal Tutorials - The Complete Omega 4 Course: Collected 23 video ids (downloading 23 of them)
[download] Downloading video 1 of 23
[youtube] 2CM177ldAy8: Downloading webpage
[youtube] 2CM177ldAy8: Extracting video information
[youtube] 2CM177ldAy8: Downloading DASH manifest
Traceback (most recent call last):
  File "/usr/bin/youtube-dl", line 6, in <module>
    youtube_dl.main()
  File "/usr/lib64/python3.4/site-packages/youtube_dl/__init__.py", line 408, in main
    _real_main(argv)
  File "/usr/lib64/python3.4/site-packages/youtube_dl/__init__.py", line 398, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/lib64/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 1446, in download
    res = self.extract_info(url)
  File "/usr/lib64/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 662, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib64/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 821, in process_ie_result
    extra_info=extra)
  File "/usr/lib64/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 715, in process_ie_result
    extra_info=extra_info)
  File "/usr/lib64/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 662, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib64/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 708, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/lib64/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 1150, in process_video_result
    self.process_info(new_info)
  File "/usr/lib64/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 1379, in process_info
    success = dl(filename, info_dict)
  File "/usr/lib64/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 1349, in dl
    fd = get_suitable_downloader(info, self.params)(self, self.params)
  File "/usr/lib64/python3.4/site-packages/youtube_dl/downloader/__init__.py", line 33, in get_suitable_downloader
    ed = get_external_downloader(external_downloader)
  File "/usr/lib64/python3.4/site-packages/youtube_dl/downloader/external.py", line 135, in get_external_downloader
    return _BY_NAME[bn]
KeyError: 'axel'

Also by using Aria2c 

youtube-dl --proxy 127.0.0.1:9662 --external-downloader arai2c --external-downloader-args "-x10" --autonumber "0" -o "%(autonumber)s-%(title)s.%(ext)s" http://www.youtube.com/playlist?list=PLLnpHn493BHH5nnK2dKE_42l1oXA6Tq6H -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--proxy', '127.0.0.1:9662', '--external-downloader', 'arai2c', '--external-downloader-args', '-x10', '--autonumber', '0', '-o', '%(autonumber)s-%(title)s.%(ext)s', 'http://www.youtube.com/playlist?list=PLLnpHn493BHH5nnK2dKE_42l1oXA6Tq6H', '-v']
WARNING: No ssl certificates were loaded, urls that use https won't work
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.04.03
[debug] Python version 3.4.1 - Linux-4.0.5-gentoo-x86_64-Intel-R-_Core-TM-_i3-3110M_CPU_@_2.40GHz-with-gentoo-2.2
[debug] exe versions: ffmpeg 2.6.3, ffprobe 2.6.3
[debug] Proxy map: {'https': '127.0.0.1:9662', 'http': '127.0.0.1:9662'}
[youtube:playlist] PLLnpHn493BHH5nnK2dKE_42l1oXA6Tq6H: Downloading webpage
[download] Downloading playlist: Drupal Tutorials - The Complete Omega 4 Course
[youtube:playlist] playlist Drupal Tutorials - The Complete Omega 4 Course: Collected 23 video ids (downloading 23 of them)
[download] Downloading video 1 of 23
[youtube] 2CM177ldAy8: Downloading webpage
[youtube] 2CM177ldAy8: Extracting video information
[youtube] 2CM177ldAy8: Downloading DASH manifest
Traceback (most recent call last):
  File "/usr/bin/youtube-dl", line 6, in <module>
    youtube_dl.main()
  File "/usr/lib64/python3.4/site-packages/youtube_dl/__init__.py", line 408, in main
    _real_main(argv)
  File "/usr/lib64/python3.4/site-packages/youtube_dl/__init__.py", line 398, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/lib64/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 1446, in download
    res = self.extract_info(url)
  File "/usr/lib64/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 662, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib64/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 821, in process_ie_result
    extra_info=extra)
  File "/usr/lib64/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 715, in process_ie_result
    extra_info=extra_info)
  File "/usr/lib64/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 662, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib64/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 708, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/lib64/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 1150, in process_video_result
    self.process_info(new_info)
  File "/usr/lib64/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 1379, in process_info
    success = dl(filename, info_dict)
  File "/usr/lib64/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 1349, in dl
    fd = get_suitable_downloader(info, self.params)(self, self.params)
  File "/usr/lib64/python3.4/site-packages/youtube_dl/downloader/__init__.py", line 33, in get_suitable_downloader
    ed = get_external_downloader(external_downloader)
  File "/usr/lib64/python3.4/site-packages/youtube_dl/downloader/external.py", line 135, in get_external_downloader
    return _BY_NAME[bn]
KeyError: 'arai2c'

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.

**Comment by gulbuhar** [comment]
I have just updated my yt-dl using 'pip' and still getting similar result 

$ youtube-dl --proxy 127.0.0.1:9662 --external-downloader axel --external-downloader-args "-n10" --autonumber "0" -o "%(autonumber)s-%(title)s.%(ext)s" http://www.youtube.com/playlist?list=PLLnpHn493BHH5nnK2dKE_42l1oXA6Tq6H -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--proxy', u'127.0.0.1:9662', u'--external-downloader', u'axel', u'--external-downloader-args', u'-n10', u'--autonumber', u'0', u'-o', u'%(autonumber)s-%(title)s.%(ext)s', u'http://www.youtube.com/playlist?list=PLLnpHn493BHH5nnK2dKE_42l1oXA6Tq6H', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.08.09
[debug] Python version 2.7.9 - Linux-4.0.5-gentoo-x86_64-Intel-R-_Core-TM-_i3-3110M_CPU_@_2.40GHz-with-gentoo-2.2
[debug] exe versions: ffmpeg 2.6.3, ffprobe 2.6.3
[debug] Proxy map: {u'http': u'127.0.0.1:9662', u'https': u'127.0.0.1:9662'}
[youtube:playlist] PLLnpHn493BHH5nnK2dKE_42l1oXA6Tq6H: Downloading webpage
[download] Downloading playlist: Drupal Tutorials - The Complete Omega 4 Course
[youtube:playlist] playlist Drupal Tutorials - The Complete Omega 4 Course: Downloading 23 videos
[download] Downloading video 1 of 23
[youtube] 2CM177ldAy8: Downloading webpage
[youtube] 2CM177ldAy8: Downloading video info webpage
[youtube] 2CM177ldAy8: Extracting video information
[youtube] 2CM177ldAy8: Downloading DASH manifest
[youtube] 2CM177ldAy8: Downloading DASH manifest
[debug] Invoking downloader on 'https://r5---sn-xjpm-4g5e.googlevideo.com/videoplayback?id=d82335efb95d032f&itag=137&source=youtube&requiressl=yes&mv=m&ms=au&pl=24&mn=sn-xjpm-4g5e&mm=31&ratebypass=yes&mime=video/mp4&gir=yes&clen=5480857&lmt=1389781620972452&dur=144.200&sver=3&signature=52F066FBFD13A001B0956D3D1F0E0CD7D9E1746E.695A45C3B4B19727DCABB3D98D368928DA08ACA8&mt=1439239951&fexp=9407575,9407715,9407992,9408710,9415365,9415485,9416023,9416126,9416729,9417192,9417259,9417709,9418153,9418204,9418562,9418823&upn=X3o0q_Q0Z2c&key=dg_yt0&ip=65.49.68.200&ipbits=0&expire=1439261653&sparams=ip,ipbits,expire,id,itag,source,requiressl,mv,ms,pl,mn,mm,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: 1-Drupal Tutorials - The Complete Guide To Omega 4 #1 - Course Overview.f137.mp4
[debug] axel command line: axel -o '1-Drupal Tutorials - The Complete Guide To Omega 4 #1 - Course Overview.f137.mp4.part' -H 'Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7' -H 'Accept-Language: en-us,en;q=0.5' -H 'Accept-Encoding: gzip, deflate' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/20.0 (Chrome)' -n10 -- 'https://r5---sn-xjpm-4g5e.googlevideo.com/videoplayback?id=d82335efb95d032f&itag=137&source=youtube&requiressl=yes&mv=m&ms=au&pl=24&mn=sn-xjpm-4g5e&mm=31&ratebypass=yes&mime=video/mp4&gir=yes&clen=5480857&lmt=1389781620972452&dur=144.200&sver=3&signature=52F066FBFD13A001B0956D3D1F0E0CD7D9E1746E.695A45C3B4B19727DCABB3D98D368928DA08ACA8&mt=1439239951&fexp=9407575,9407715,9407992,9408710,9415365,9415485,9416023,9416126,9416729,9417192,9417259,9417709,9418153,9418204,9418562,9418823&upn=X3o0q_Q0Z2c&key=dg_yt0&ip=65.49.68.200&ipbits=0&expire=1439261653&sparams=ip,ipbits,expire,id,itag,source,requiressl,mv,ms,pl,mn,mm,ratebypass,mime,gir,clen,lmt,dur'
Initializing download: https://r5---sn-xjpm-4g5e.googlevideo.com/videoplayback?id=d82335efb95d032f&itag=137&source=youtube&requiressl=yes&mv=m&ms=au&pl=24&mn=sn-xjpm-4g5e&mm=31&ratebypass=yes&mime=video/mp4&gir=yes&clen=5480857&lmt=1389781620972452&dur=144.200&sver=3&signature=52F066FBFD13A001B0956D3D1F0E0CD7D9E1746E.695A45C3B4B19727DCABB3D98D368928DA08ACA8&mt=1439239951&fexp=9407575,9407715,9407992,9408710,9415365,9415485,9416023,9416126,9416729,9417192,9417259,9417709,9418153,9418204,9418562,9418823&upn=X3o0q_Q0Z2c&key=dg_yt0&ip=65.49.68.200&ipbits=0&expire=1439261653&sparams=ip,ipbits,expire,id,itag,source,requiressl,mv,ms,pl,mn,mm,ratebypass,mime,gir,clen,lmt,dur
HTTP/1.0 404 Not Found



ERROR: axel exited with code 1
  File "/usr/bin/youtube-dl", line 6, in <module>
    youtube_dl.main()
  File "/usr/lib64/python2.7/site-packages/youtube_dl/__init__.py", line 410, in main
    _real_main(argv)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/__init__.py", line 400, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 1653, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/lib64/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 666, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 827, in process_ie_result
    extra_info=extra)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 719, in process_ie_result
    extra_info=extra_info)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 666, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 712, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 1323, in process_video_result
    self.process_info(new_info)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 1579, in process_info
    partial_success = dl(fname, new_info)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 1527, in dl
    return fd.download(name, info)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/downloader/common.py", line 342, in download
    return self.real_download(filename, info_dict)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/downloader/external.py", line 33, in real_download
    self.get_basename(), retval))
  File "/usr/lib64/python2.7/site-packages/youtube_dl/downloader/common.py", line 155, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 530, in report_error
    self.trouble(error_message, tb)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 492, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())

**Comment by dstftw** [comment]
Absolutely different error. Can you download the URL returned by `youtube-dl -g ...` when passed manually to axel? Is your proxy intended? axel seems missing any `--proxy` command line option so proxy should be setup in `axelrc` if intended.
