### ISSUE TITLE
RegexNotFoundError: Unable to extract Initial JS player signature function name

### ISSUE THREAD

**Issue by JasonSheedy** [rg3/youtube-dl#6526]
Error downloading the following URL: https://www.youtube.com/watch?v=3eIXGMRLqXM

WARNING: Warning: Falling back to static signature algorithm
[youtube] encrypted signature length 84 (40.43), itag 135, html5 player new-en_US-vflo_te46\/html5player-new
[youtube] 3eIXGMRLqXM: Downloading js player new
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 957, in _decrypt_signature
    video_id, player_url, len(s)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 356, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 424, in _parse_sig_js
    u'Initial JS player signature function name')
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 356, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.
