### ISSUE TITLE
“Unable to extract title” error

### ISSUE THREAD

**Issue by starkshaw** [rg3/youtube-dl#6527]
The command and output are as follow, using the latest version of youtube-dl:
`$ youtube-dl http://www.pornhub.com/view_video.php\?viewkey\=XXXXXXXX --verbose`
Output:
```
[debug] System config: []
[debug] User config: [u'-f', u'bestvideo+bestaudio/best']
[debug] Command-line args: [u'http://www.pornhub.com/view_video.php?viewkey=XXXXXXXX', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.08.09
[debug] Python version 2.7.6 - Darwin-14.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.7.2, ffprobe 2.7.2
[debug] Proxy map: {}
[PornHub] 1531821647: Downloading webpage
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 655, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 286, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/pornhub.py", line 67, in _real_extract
    video_title = self._html_search_regex(r'<h1 [^>]+>([^<]+)', webpage, 'title')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 577, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 568, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by dstftw** [comment]
Post the **full** output of `youtube-dl -v --dump-pages ...` with concrete URL.

**Comment by starkshaw** [comment]
@dstftw It is very strange, according to your parameters it works! Can you tell me why?

**Comment by dstftw** [comment]
Do you state it doesn't work with `youtube-dl -f bestvideo+bestaudio/best URL`? If so post the output with concrete URL.

**Comment by dstftw** [comment]
Nvm, you didn't remove the video id. `youtube-dl -f bestvideo+bestaudio/best http://www.pornhub.com/view_video.php?viewkey=1531821647` works just fine for me.

**Comment by starkshaw** [comment]
I used a default setting in `~/.config/youtube-dl/config` which downloaded best quality automatically.

But I didn't get what you mentioned about that video ID. For other websites I copied the address everything works fine, even few days ago PornHub is operational as well. I was thinking some protocol changed on PornHub.

**Comment by dstftw** [comment]
Most likely a temporary issue. Closing.
