### ISSUE TITLE
NBC KeyError

### ISSUE THREAD

**Issue by dd217** [rg3/youtube-dl#6546]
Anyone getting this error? It can be replicated on any NBC video from their site.
An extractor error has occured. (caused by KeyError(u'releaseUrl',));

Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/extractor/common.py", line 273, in extract
    return self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/theplatform.py", line 111, in _real_extract
    smil_url = config['releaseUrl'] + '&format=SMIL&formats=MPEG4&manifest=f4m'
KeyError: u'releaseUrl'
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 654, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 279, in extract
    raise ExtractorError('An extractor error has occured.', cause=e)

using version: v2015.08.09
Have tried archived versions and it still produces the same error

**Comment by yan12125** [comment]
Which URL is causing this error?

**Comment by dd217** [comment]
http://www.nbc.com/parks-and-recreation/episode-guide/season-7/one-last-ride/712

along with every other video that is on their site.

**Comment by yan12125** [comment]
This should be fixed in 2847914. Please check it when the next version is released.
