### ISSUE TITLE
Retries argument not in use? - "ERROR: giving up after 0 retries"

### ISSUE THREAD

**Issue by ping** [rg3/youtube-dl#6549]
Noticed this when trying to download This American Life episodes. 
Although the help manual says that the default is 10, I've noticed that it errors out as "ERROR: giving up after 0 retries". And when I explicitly specify the retries arg, it still says 0.

```
$ youtube-dl --no-mtime --retries 9 --verbose "http://www.thisamericanlife.org/radio-archives/episode/542/wait-do-you-have-the-map"
[debug] System config: []
[debug] User config: [u'--no-mtime']
[debug] Command-line args: [u'--no-mtime', u'--retries', u'9', u'--verbose', u'http://www.thisamericanlife.org/radio-archives/episode/542/wait-do-you-have-the-map']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.08.09
[debug] Python version 2.7.5 - Darwin-13.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.6.2, ffprobe 2.6.2, rtmpdump 2.4
[debug] Proxy map: {}
[ThisAmericanLife] 542: Downloading webpage
[debug] Invoking downloader on u'http://stream.thisamericanlife.org/542/stream/542_64k.m3u8'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 358
[download] Destination: 542 - Wait - Do You Have The Map-542.m4a
[download]  88.3% of ~31.39MiB at 58.72KiB/s ETA 01:21ERROR: giving up after 0 retries
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 60, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1860, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 504: Gateway Timeout 50001
```

**Comment by dstftw** [comment]
This issue has been fixed and will be available in the next version. Thanks for the report.
