### ISSUE TITLE
pornhub.com broken

### ISSUE THREAD

**Issue by notayy** [rg3/youtube-dl#6563]
````
youtube-dl --verbose 'http://www.pornhub.com/view_video.php?viewkey=1304269548'
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.pornhub.com/view_video.php?viewkey=1304269548']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.07.28
[debug] Python version 3.4.3 - Linux-4.1.2-2-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 2.7.1, ffprobe 2.7.1, rtmpdump 2.4
[debug] Proxy map: {}
[PornHub] 1304269548: Downloading webpage
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 656, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 279, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/pornhub.py", line 113, in _real_extract
    self._sort_formats(formats)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 735, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
````

**Comment by yan12125** [comment]
Your youtube-dl copy is old. Version 2015.08.06.1 or newer works.
