### ISSUE TITLE
funnyordie "unknown url type"

### ISSUE THREAD

**Issue by 2011** [rg3/youtube-dl#6569]
I am not much of a programmer (and no nothing about python), but I am guessing this shouldn't be too difficult to track down.

$ youtube-dl -v 'http://www.funnyordie.com/videos/09c5814618/little-republicans'
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--restrict-filenames', '-o', '%(title)s-%(id)s-%(uploader)s.%(ext)s', '-w', '-v', 'http://www.funnyordie.com/videos/09c5814618/little-republicans']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.08.09
[debug] Python version 3.4.1 - Linux-3.18.12-x86_64-Intel-R-_Core-TM-_i5_CPU_750_@_2.67GHz
[debug] exe versions: ffmpeg 2.6.3, ffprobe 2.6.3, rtmpdump 2.4
[debug] Proxy map: {}
[FunnyOrDie] 09c5814618: Downloading webpage
Traceback (most recent call last):
  File "/usr/bin/youtube-dl", line 6, in <module>
    youtube_dl.main()
  File "/usr/lib64/python3.4/site-packages/youtube_dl/__init__.py", line 410, in main
    _real_main(argv)
  File "/usr/lib64/python3.4/site-packages/youtube_dl/__init__.py", line 400, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/lib64/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 1653, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/lib64/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 666, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib64/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 712, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/lib64/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 1283, in process_video_result
    format['http_headers'] = self._calc_headers(full_format_info)
  File "/usr/lib64/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 1176, in _calc_headers
    cookies = self._calc_cookies(info_dict)
  File "/usr/lib64/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 1183, in _calc_cookies
    pr = compat_urllib_request.Request(info_dict['url'])
  File "/usr/lib64/python3.4/urllib/request.py", line 258, in __init__
    self.full_url = url
  File "/usr/lib64/python3.4/urllib/request.py", line 284, in full_url
    self._parse()
  File "/usr/lib64/python3.4/urllib/request.py", line 313, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '//vo.fod4.com/v/09c5814618/v110.webm'

**Comment by dstftw** [comment]
This issue is already fixed and will be available in the next version of youtube-dl. Thanks for the report.
