### ISSUE TITLE
[abc] Youtube embed results in "Unable to extract video urls" error

### ISSUE THREAD

**Issue by anovicecodemonkey** [rg3/youtube-dl#6595]
````

$ youtube-dl --verbose  http://www.abc.net.au/news/2015-08-17/warren-entsch-introduces-same-sex-marriage-bill/6702326
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.abc.net.au/news/2015-08-17/warren-entsch-introduces-same-sex-marriage-bill/6702326']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.08.16.1
[debug] Python version 3.4.3 - Linux-4.0.7-2-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 2.7.1, ffprobe 2.7.1, rtmpdump 2.4
[debug] Proxy map: {}
[abc.net.au] 6702326: Downloading webpage
ERROR: Unable to extract video urls; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 655, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 287, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/abc.py", line 30, in _real_extract
    flags=re.DOTALL)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 569, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract video urls; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

````

**Comment by yan12125** [comment]
Thanks for the report and sorry for the late response. YouTube videos on abc.net.au will be supported in the next version.

**Comment by yan12125** [comment]
@stepshal Could you open a new issue?
