### ISSUE TITLE
YouTube: Not pulling audio, fails to download

### ISSUE THREAD

**Issue by vxbinaca** [rg3/youtube-dl#6598]
```youtube-dl --ignore-config --verbose 2OQp4_k69Cc```

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--ignore-config', u'--verbose', u'2OQp4_k69Cc']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.08.16.1
[debug] Python version 2.7.9 - Linux-3.19.0-26-generic-x86_64-with-Ubuntu-15.04-vivid
[debug] exe versions: avconv 11.2-6, avprobe 11.2-6, ffmpeg 2.5.8-0ubuntu0.15.04.1, ffprobe 2.5.8-0ubuntu0.15.04.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] 2OQp4_k69Cc: Downloading webpage
[youtube] 2OQp4_k69Cc: Downloading video info webpage
[youtube] 2OQp4_k69Cc: Extracting video information
[youtube] 2OQp4_k69Cc: Downloading DASH manifest
[youtube] 2OQp4_k69Cc: Downloading DASH manifest
[debug] Invoking downloader on 'https://r3---sn-hp57kn7d.googlevideo.com/videoplayback?id=d8e429e3f93af427&itag=135&source=youtube&requiressl=yes&nh=IgpwcjAxLm1pYTA0KgkxMjcuMC4wLjE&mn=sn-hp57kn7d&mv=m&ms=au&pl=17&mm=31&ratebypass=yes&mime=video/mp4&gir=yes&clen=13463579&lmt=1379503090328576&dur=114.867&sver=3&fexp=9408208,9408710,9409069,9409170,9412514,9413319,9415365,9415435,9415485,9416023,9416126,9416344,9416520,9417084,9417707,9418153,9418201,9418251,9418339,9418679,9418702,9418897&mt=1439894682&signature=1E8B3D75DE5D21BAD84036EAA7B1DD3FA78E1A17.606160ACAEDA14248743F9FF009C0BF2E8A45E51&upn=kkyFVJclSwI&key=dg_yt0&ip=73.28.76.5&ipbits=0&expire=1439916410&sparams=ip,ipbits,expire,id,itag,source,requiressl,nh,mn,mv,ms,pl,mm,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: Sexsexsexsex!-2OQp4_k69Cc.f135.mp4
[download] 100% of 12.84MiB in 00:06
[debug] Invoking downloader on 'https://r3---sn-hp57kn7d.googlevideo.com/videoplayback?id=d8e429e3f93af427&itag=141&source=youtube&requiressl=yes&nh=IgpwcjAxLm1pYTA0KgkxMjcuMC4wLjE&mn=sn-hp57kn7d&mv=m&ms=au&pl=17&mm=31&ratebypass=yes&mime=audio/mp4&gir=yes&clen=3669599&lmt=1379503090328462&dur=115.078&sver=3&fexp=9408208,9408710,9409069,9409170,9412514,9413319,9415365,9415435,9415485,9416023,9416126,9416344,9416520,9417084,9417707,9418153,9418201,9418251,9418339,9418679,9418702,9418897&mt=1439894682&signature=3C4FF88D26C7E1B364A42B3C48B51829A648BD39.02577CD332BD1C0D406D555C2CD7A62DC4AA6626&upn=kkyFVJclSwI&key=dg_yt0&ip=73.28.76.5&ipbits=0&expire=1439916410&sparams=ip,ipbits,expire,id,itag,source,requiressl,nh,mn,mv,ms,pl,mm,ratebypass,mime,gir,clen,lmt,dur'
[download] Got server HTTP error. Retrying (attempt 1 of 10)...
[download] Got server HTTP error. Retrying (attempt 2 of 10)...
[download] Got server HTTP error. Retrying (attempt 3 of 10)...
[download] Got server HTTP error. Retrying (attempt 4 of 10)...
[download] Got server HTTP error. Retrying (attempt 5 of 10)...
[download] Got server HTTP error. Retrying (attempt 6 of 10)...
[download] Got server HTTP error. Retrying (attempt 7 of 10)...
[download] Got server HTTP error. Retrying (attempt 8 of 10)...
[download] Got server HTTP error. Retrying (attempt 9 of 10)...
[download] Got server HTTP error. Retrying (attempt 10 of 10)...
ERROR: giving up after 10 retries
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/http.py", line 60, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1860, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 500: Internal Server Error
```

**Comment by dstftw** [comment]
Youtube-side issue. `-f 140` is available.
