### ISSUE TITLE
Cannot download from dailymotion

### ISSUE THREAD

**Issue by m-anish** [rg3/youtube-dl#6604]
Please see the log below.

```
[anish@xxxxxxxx ~]$ youtube-dl --verbose http://www.dailymotion.com/playlist/xj7vh_rachit28_1988_bhagvad-gita/1#video=x5hxnn
[debug] System config: [u'--prefer-free-formats']
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.dailymotion.com/playlist/xj7vh_rachit28_1988_bhagvad-gita/1#video=x5hxnn']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.07.04
[debug] Python version 2.7.8 - Linux-4.1.3-100.fc21.x86_64-x86_64-with-fedora-21-Twenty_One
[debug] exe versions: ffmpeg 2.4.10, ffprobe 2.4.10
[debug] Proxy map: {}
[dailymotion:playlist] xj7vh_rachit28_1988_bhagvad-gita: Downloading webpage
[dailymotion:playlist] xj7vh_rachit28_1988_bhagvad-gita: Downloading page 1
[dailymotion:playlist] xj7vh_rachit28_1988_bhagvad-gita: Downloading page 2
[download] Downloading playlist: BHAGVAD GITA
[dailymotion:playlist] playlist BHAGVAD GITA: Collected 33 video ids (downloading 33 of them)
[download] Downloading video 1 of 33
[dailymotion] x5hxnn: Downloading webpage
[dailymotion] x5hxnn: Extracting information
[dailymotion] x5hxnn: Downloading embed page
ERROR: Unable to extract video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 654, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 273, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/dailymotion.py", line 119, in _real_extract
    'video info', flags=re.MULTILINE)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 555, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


```

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.
