### ISSUE TITLE
site support request: theatlantic.com

### ISSUE THREAD

**Issue by privong** [rg3/youtube-dl#6611]
```
$ youtube-dl --version
2015.08.16.1
```
```
$ youtube-dl -v http://www.theatlantic.com/video/index/400241/vanlife/
[debug] System config: []
[debug] User config: ['--console-title']
[debug] Command-line args: ['-v', 'http://www.theatlantic.com/video/index/400241/vanlife/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.08.16.1
[debug] Python version 3.4.3 - Linux-4.1.5-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 2.7.2, ffprobe 2.7.2, rtmpdump 2.4
[debug] Proxy map: {}
[generic] vanlife: Requesting header
WARNING: Falling back on generic information extractor.
[generic] vanlife: Downloading webpage
[generic] vanlife: Extracting information
ERROR: Unsupported URL: http://www.theatlantic.com/video/index/400241/vanlife/
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 655, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 287, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/generic.py", line 1804, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.theatlantic.com/video/index/400241/vanlife/
```

**Comment by TRox1972** [comment]
Developers: The website seems to be using BrightCove. Format info can be found at https://edge.api.brightcove.com/playback/v1/accounts/29913724001/videos/4393559964001, which is inaccessible unless you've visited the website first (is stores a cookie or something).
