### ISSUE TITLE
youtube ExtractorError Cannot decrypt signature without player_url

### ISSUE THREAD

**Issue by wuhaa11** [rg3/youtube-dl#6626]
Hi,

I'm getting this error when grabbing video from youtube. 

```
youtube-dl https://www.youtube.com/watch?v=GFGpWjSwr_0
[youtube] GFGpWjSwr_0: Downloading webpage
[youtube] GFGpWjSwr_0: Downloading video info webpage
[youtube] GFGpWjSwr_0: Extracting video information
[youtube] GFGpWjSwr_0: Downloading DASH manifest
WARNING: [youtube] GFGpWjSwr_0: Skipping DASH manifest: ExtractorError(u'Cannot decrypt signature without player_url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
[download] Destination: Learning to Scale OpenStack An Update from the Rackspace Public Cloud-GFGpWjSwr_0.mp4
[download]   0.0% of 309.16MiB at  1.86MiB/s ETA 02:47ERROR: content too short (expected 324177079 bytes and served 39894)
```

If I try multiple times, I get the following http errors:

```
youtube-dl https://www.youtube.com/watch?v=GFGpWjSwr_0
[youtube] GFGpWjSwr_0: Downloading webpage
[youtube] GFGpWjSwr_0: Downloading video info webpage
[youtube] GFGpWjSwr_0: Extracting video information
[youtube] GFGpWjSwr_0: Downloading DASH manifest
[youtube] GFGpWjSwr_0: Downloading DASH manifest
[download] Resuming download at byte 39894
[download] Got server HTTP error. Retrying (attempt 1 of 10)...
[download] Got server HTTP error. Retrying (attempt 2 of 10)...
[download] Got server HTTP error. Retrying (attempt 3 of 10)...
[download] Got server HTTP error. Retrying (attempt 4 of 10)...
[download] Got server HTTP error. Retrying (attempt 5 of 10)...
[download] Got server HTTP error. Retrying (attempt 6 of 10)...
[download] Got server HTTP error. Retrying (attempt 7 of 10)...
[download] Got server HTTP error. Retrying (attempt 8 of 10)...
[download] Got server HTTP error. Retrying (attempt 9 of 10)...
[download] Got server HTTP error. Retrying (attempt 10 of 10)...
ERROR: giving up after 10 retries
```
Details:

# uname -a
Linux virtual 3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

# python -V
Python 2.7.6

# cat /etc/lsb-release
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=17.1
DISTRIB_CODENAME=rebecca
DISTRIB_DESCRIPTION="Linux Mint 17.1 Rebecca"

# youtube-dl -v
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=GFGpWjSwr_0']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.08.16.1
[debug] Python version 2.7.6 - Linux-3.13.0-37-generic-x86_64-with-LinuxMint-17.1-rebecca
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] GFGpWjSwr_0: Downloading webpage
[youtube] GFGpWjSwr_0: Downloading video info webpage
[youtube] GFGpWjSwr_0: Extracting video information
[youtube] GFGpWjSwr_0: Downloading DASH manifest
[youtube] GFGpWjSwr_0: Downloading DASH manifest
[debug] Invoking downloader on u'https://r6---sn-tt17dn7r.googlevideo.com/videoplayback?mm=31&mn=sn-tt17dn7r&ipbits=0&requiressl=yes&sver=3&expire=1440109858&mt=1440088174&mv=m&ms=au&lmt=1383982227762518&dur=1919.547&key=yt5&ip=67.55.2.23&itag=22&id=o-AHPGBk9ye3zaPATO3qAhK-MDqwen2ZnHxSfJDvwRcmMv&sparams=dur%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&signature=58411522E2B7F7B7656A471D1004E321A2D10AEB.C42C3C90C1CE32D62FB028DC667BAEC7AC8CD51D&mime=video%2Fmp4&upn=LNGN-RXGJqU&fexp=9406715%2C9407991%2C9408207%2C9408710%2C9409069%2C9412773%2C9414856%2C9415365%2C9415485%2C9416023%2C9416126%2C9416330%2C9416985%2C9417117%2C9417707%2C9418058%2C9418153%2C9418449%2C9419339%2C9419427%2C9419751%2C9419817&source=youtube&pl=22&ratebypass=yes&initcwndbps=746250'
[download] Resuming download at byte 39894
[download] Got server HTTP error. Retrying (attempt 1 of 10)...
[download] Got server HTTP error. Retrying (attempt 2 of 10)...
[download] Got server HTTP error. Retrying (attempt 3 of 10)...
[download] Got server HTTP error. Retrying (attempt 4 of 10)...
[download] Got server HTTP error. Retrying (attempt 5 of 10)...
[download] Got server HTTP error. Retrying (attempt 6 of 10)...
[download] Got server HTTP error. Retrying (attempt 7 of 10)...
[download] Got server HTTP error. Retrying (attempt 8 of 10)...
[download] Got server HTTP error. Retrying (attempt 9 of 10)...
[download] Got server HTTP error. Retrying (attempt 10 of 10)...
ERROR: giving up after 10 retries
Traceback (most recent call last):
  File "ytd/youtube_dl/downloader/http.py", line 60, in real_download
    data = self.ydl.urlopen(request)
  File "ytd/youtube_dl/YoutubeDL.py", line 1860, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 500: Internal Server Error
```

**Comment by philippeboyd** [comment]
+1

**Comment by betoharres** [comment]
``` Ruby
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 817, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 709, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
ExtractorError: Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vfl5u6mls/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vfl5u6mls/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.``

**Comment by jaimeMF** [comment]
@betoharres it's not related, open a new issue with the **full output you get when running `youtube-dl --verbose THE_URL` (ase requested in the error message).

**Comment by betoharres** [comment]
@jaimeMF ok!

**Comment by dstftw** [comment]
Works fine with latest version.
