### ISSUE TITLE
Can't download non-public video from Flickr

### ISSUE THREAD

**Issue by l0b0** [rg3/youtube-dl#6631]
I'm able to download publicly available videos from Flickr:

    $ youtube-dl 'https://www.flickr.com/photos/l0b0/15870221972/'
    [Flickr] 15870221972: Downloading webpage
    [Flickr] 15870221972: Downloading first data webpage
    [Flickr] 15870221972: Downloading second data webpage
    [Flickr] 15870221972: Extracting information
    [download] Destination: Guitar slapping street artist-15870221972.mp4
    [download] 100% of 2.96MiB in 00:01

Is it possible to download videos which are **not publicly available** from Flickr? I tried the following:

    $ youtube-dl --verbose 'https://www.flickr.com/photos/[user id]/[video id]/'
    [debug] System config: []
    [debug] User config: []
    [debug] Command-line args: ['--verbose', 'https://www.flickr.com/photos/[user id]/[video id]/']
    [debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
    [debug] youtube-dl version 2015.08.16.1
    [debug] Python version 3.4.3 - Linux-4.1.5-1-ARCH-x86_64-with-arch
    [debug] exe versions: ffmpeg 2.7.2, ffprobe 2.7.2, rtmpdump 2.4
    [debug] Proxy map: {}
    [Flickr] [video id]: Downloading webpage
    ERROR: Unable to extract secret; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
    Traceback (most recent call last):
      File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 655, in extract_info
        ie_result = ie.extract(url)
      File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 287, in extract
        return self._real_extract(url)
      File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/flickr.py", line 40, in _real_extract
        secret = self._search_regex(r'secret"\s*:\s*"(\w+)"', webpage, 'secret')
      File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 569, in _search_regex
        raise RegexNotFoundError('Unable to extract %s' % _name)
    youtube_dl.utils.RegexNotFoundError: Unable to extract secret; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
    $ youtube-dl --version
    2015.08.16.1

**Comment by dstftw** [comment]
Post an example URL of such video.

**Comment by l0b0** [comment]
@dstftw https://www.flickr.com/photos/2r3c/20730714886/ - but you won't be allowed to download it AFAIK.
