### ISSUE TITLE
[Weibo] Unsupported URL

### ISSUE THREAD

**Issue by joepie91** [rg3/youtube-dl#6653]
* __URL:__ http://video.weibo.com/show?fid=1034:7ffc79010fec610ed9a7dc35bd288062
* __Error:__ Unsupported URL: http://video.weibo.com/show?fid=1034:7ffc79010fec610ed9a7dc35bd288062
* __Platform:__ openSUSE 13.1, x86_64, XFCE
* __Version:__ 2015.08.16.1
* __Video player:__ Custom

Oddly, there's supposed to be Weibo support, it seems (#1039). Not sure why it doesn't work here. Different video provider, maybe?

```
sven@linux-etoq:~/archive/shandong-explosion> youtube-dl -v http://video.weibo.com/show?fid=1034:7ffc79010fec610ed9a7dc35bd288062
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://video.weibo.com/show?fid=1034:7ffc79010fec610ed9a7dc35bd288062']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.08.16.1
[debug] Python version 2.7.6 - Linux-3.11.10-29-desktop-x86_64-with-SuSE-13.1-x86_64
[debug] exe versions: ffmpeg 2.7.2, ffprobe 2.7.2, rtmpdump 2.4
[debug] Proxy map: {}
[generic] show?fid=1034:7ffc79010fec610ed9a7dc35bd288062: Requesting header
WARNING: Falling back on generic information extractor.
[generic] show?fid=1034:7ffc79010fec610ed9a7dc35bd288062: Downloading webpage
[generic] show?fid=1034:7ffc79010fec610ed9a7dc35bd288062: Extracting information
ERROR: Unsupported URL: http://video.weibo.com/show?fid=1034:7ffc79010fec610ed9a7dc35bd288062
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/generic.py", line 1211, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/lib/python2.7/site-packages/youtube_dl/utils.py", line 1594, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: syntax error: line 1, column 0
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 655, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 287, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/generic.py", line 1804, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://video.weibo.com/show?fid=1034:7ffc79010fec610ed9a7dc35bd288062
```

**Comment by aaronvegh** [comment]
I would like to corroborate this one. Here's a sample that I was coming here to report on!

```
$ youtube-dl -v -g http://video.weibo.com/show?fid=1034:4c3c0c12039eb46d380e968a57eca250
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'-g', u'http://video.weibo.com/show?fid=1034:4c3c0c12039eb46d380e968a57eca250']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.10.24
[debug] Python version 2.7.10 - Darwin-15.0.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
WARNING: Falling back on generic information extractor.
ERROR: Unsupported URL: http://video.weibo.com/show?fid=1034:4c3c0c12039eb46d380e968a57eca250
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1240, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1667, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: syntax error: line 1, column 0
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 661, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 291, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1838, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://video.weibo.com/show?fid=1034:4c3c0c12039eb46d380e968a57eca250
```
