### ISSUE TITLE
Is the proxy option still working?

### ISSUE THREAD

**Issue by NelsonSR** [rg3/youtube-dl#6706]
In the past I've used successfully youtube-dl to download videos from YouTube blocked by country, but now I've been unable to repeat the process no matter the proxy server I use. I test proxy using nmap and looks fine (server is up and the port is open). This is an example of youtube-dl on a blocked video, only available in Canada (obviously, the proxy server used is Canadian): 

```
youtube-dl "https://www.youtube.com/watch?v=xXww6Rqahnk" --proxy "167.114.104.44:80" --verbose
[debug] System config: []
[debug] User config: [u'--ignore-errors', u'--no-warnings', u'--add-metadata', u'--write-sub', u'--write-auto-sub', u'--sub-lang', u'en,es', u'--prefer-ffmpeg', u'--console-title']
[debug] Command-line args: [u'https://www.youtube.com/watch?v=xXww6Rqahnk', u'--proxy', u'167.114.104.44:80', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.08.28
[debug] Python version 2.7.9 - Linux-3.16.0-4-686-pae-i686-with-debian-8.1
[debug] exe versions: avconv 2.6.4, avprobe 2.6.4, ffmpeg 2.6.4, ffprobe 2.6.4, rtmpdump 2.4
[debug] Proxy map: {u'http': u'167.114.104.44:80', u'https': u'167.114.104.44:80'}
[youtube] xXww6Rqahnk: Downloading webpage
[youtube] xXww6Rqahnk: Downloading video info webpage
ERROR: YouTube said: This video is available in Canada only
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 655, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 287, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1075, in _real_extract
    expected=True)
ExtractorError: YouTube said: This video is available in Canada only
```
I see that youtube-dl is reading the proxy IP address, but even so, YouTube doesn't allow the download. Does YouTube changed its API and youtube-dl needs an update?

**Comment by dstftw** [comment]
Proxy option works fine. YouTube may ban proxies. 173.243.32.40:80 worked for me atm.

**Comment by NelsonSR** [comment]
I tried it with that proxy IP address and the answer was this:
``` 
youtube-dl "https://www.youtube.com/watch?v=xXww6Rqahnk" --proxy "173.243.32.40:80" --verbose
[debug] System config: []
[debug] User config: [u'--ignore-errors', u'--no-warnings', u'--add-metadata', u'--write-sub', u'--write-auto-sub', u'--sub-lang', u'en,es', u'--prefer-ffmpeg', u'--console-title']
[debug] Command-line args: [u'https://www.youtube.com/watch?v=xXww6Rqahnk', u'--proxy', u'173.243.32.40:80', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.08.28
[debug] Python version 2.7.9 - Linux-3.16.0-4-686-pae-i686-with-debian-8.1
[debug] exe versions: avconv 2.6.4, avprobe 2.6.4, ffmpeg 2.6.4, ffprobe 2.6.4, rtmpdump 2.4
[debug] Proxy map: {u'http': u'173.243.32.40:80', u'https': u'173.243.32.40:80'}
[youtube] xXww6Rqahnk: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [Errno 110] Connection timed out> (caused by URLError(error(110, 'Connection timed out'),))
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 326, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1860, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 749, in https_open
    req, **kwargs)
  File "/usr/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
```

**Comment by dstftw** [comment]
It's public proxy therefore slow.

**Comment by NelsonSR** [comment]
Could you try with any of this? http://www.xroxy.com/proxy-country-CA.htm

**Comment by dstftw** [comment]
I've already tried with one I posted.

**Comment by NelsonSR** [comment]
Ok, I just wanted to be sure if those listed on xroxy are really working or are been blocked. In any case the problem is not related to youtube-dl.
