### ISSUE TITLE
can't download untitled video from twitch

### ISSUE THREAD

**Issue by k0377** [rg3/youtube-dl#6716]
Trying to download http://www.twitch.tv/emacsconf/v/13421774 from twitch, I guess the problem is, the video has no title.

```
manu:Downloads/ $ youtube-dl http://www.twitch.tv/emacsconf/v/13421774
[twitch:vod] 13421774: Downloading vod info JSON
[twitch:vod] 13421774: Downloading vod access token
[twitch:vod] 13421774: Downloading m3u8 information
Traceback (most recent call last):
  File "/usr/sbin/youtube-dl", line 9, in <module>
    load_entry_point('youtube-dl==2015.8.16.1', 'console_scripts', 'youtube-dl')()
  File "/usr/lib/python3.4/site-packages/youtube_dl/__init__.py", line 410, in main
    _real_main(argv)
  File "/usr/lib/python3.4/site-packages/youtube_dl/__init__.py", line 400, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 1653, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 666, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 712, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 1323, in process_video_result
    self.process_info(new_info)
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 1388, in process_info
    if len(info_dict['title']) > 200:
TypeError: object of type 'NoneType' has no len()
```

**Comment by jaimeMF** [comment]
This is fixed in 2015.08.28, [see the update instructions](https://github.com/rg3/youtube-dl/blob/eaa5646483d22d3b658dcf63b61e6c3b67aa5bc5/README.md#how-do-i-update-youtube-dl). For future reports, [please post the full output with the --verbose option](https://github.com/rg3/youtube-dl/blob/eaa5646483d22d3b658dcf63b61e6c3b67aa5bc5/README.md#bugs).
