### ISSUE TITLE
Skipping DASH manifest: ExtractorError

### ISSUE THREAD

**Issue by edumj** [rg3/youtube-dl#6721]
Hi,
some YouTube videos fails to download, but onliy in Windows 8, in Windows7 it works ok.

Videos like:
https://www.youtube.com/watch?v=ec0XKhAHR5I
or
https://www.youtube.com/watch?v=POgViZ_Zcek

In Windows 8, it throws this error just when starts "Downloading DASH manifest":

WARNING: [youtube] ec0XKhAHR5I: Skipping DASH manifest: ExtractorError(u'Could not download DASH manifest: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
ERROR: unable to download video data: HTTP Error 403: Forbidden

And full with --verbose:

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'https://www.youtube.com/watch?v=POgViZ_Zcek', u'--verbose', u'-f', u'best', u'-o', u'I:\\DESCAR~1\\W8\\\\Mecano.mp4']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.04.26
[debug] Python version 2.7.8 - Windows-8-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {}
WARNING: [youtube] POgViZ_Zcek: Skipping DASH manifest: ExtractorError(u'Could not download DASH manifest: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 1414, in process_info
  File "youtube_dl\YoutubeDL.pyo", line 1363, in dl
  File "youtube_dl\downloader\common.pyo", line 342, in download
  File "youtube_dl\downloader\http.pyo", line 64, in real_download
  File "youtube_dl\YoutubeDL.pyo", line 1701, in urlopen
  File "urllib2.pyo", line 410, in open
  File "urllib2.pyo", line 523, in http_response
  File "urllib2.pyo", line 448, in error
  File "urllib2.pyo", line 382, in _call_chain
  File "urllib2.pyo", line 531, in http_error_default
HTTPError: HTTP Error 403: Forbidden

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'https://www.youtube.com/watch?v=POgViZ_Zcek', u'--verbose', u'-f', u'best', u'-o', u'I:\\DESCAR~1\\W8\\\\Mecano.mp4']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.04.26
[debug] Python version 2.7.8 - Windows-8-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {}
WARNING: [youtube] POgViZ_Zcek: Skipping DASH manifest: ExtractorError(u'Could not download DASH manifest: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 1414, in process_info
  File "youtube_dl\YoutubeDL.pyo", line 1363, in dl
  File "youtube_dl\downloader\common.pyo", line 342, in download
  File "youtube_dl\downloader\http.pyo", line 64, in real_download
  File "youtube_dl\YoutubeDL.pyo", line 1701, in urlopen
  File "urllib2.pyo", line 410, in open
  File "urllib2.pyo", line 523, in http_response
  File "urllib2.pyo", line 448, in error
  File "urllib2.pyo", line 382, in _call_chain
  File "urllib2.pyo", line 531, in http_error_default
HTTPError: HTTP Error 403: Forbidden

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.

**Comment by edumj** [comment]
Sorry, I used the wrong version, but I also tested with a new one and also the same error. 

I'll post it later.

**Comment by edumj** [comment]
Sorry again! With new version (28-8-15) it Works ok. 
I updated last week with a version 3 days earlier (I think) and didn't work then.
Bye!
