### ISSUE TITLE
ok.ru extractor not working

### ISSUE THREAD

**Issue by ismail** [rg3/youtube-dl#6726]
λ youtube-dl -v http://www.ok.ru/video/20648036891                          
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.ok.ru/video/20648036891']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.08.28
[debug] Python version 3.4.3 - Linux-4.1.6-2-desktop-x86_64-with-SuSE-20150829-x86_64
[debug] exe versions: ffmpeg 2.7.2, ffprobe 2.7.2, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 20648036891: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 20648036891: Downloading webpage
[generic] 20648036891: Extracting information
ERROR: Unsupported URL: http://www.ok.ru/video/20648036891
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 655, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 287, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/generic.py", line 1804, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.ok.ru/video/20648036891

**Comment by ismail** [comment]
Thanks for the ultra-fast fix!

**Comment by ismail** [comment]
@dstftw Could you please explain why did you reopen this issue? In my initial testing it looks like the problem is solved now.
