### ISSUE TITLE
Unable to download this ESPN's film vidoe.

### ISSUE THREAD

**Issue by antdude** [rg3/youtube-dl#6738]
Hi!

$ youtube-dl -v http://espn.go.com/30for30/film?page=the-schedule-makers
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://espn.go.com/30for30/film?page=the-schedule-makers']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.08.28
[debug] Python version 2.7.3 - Linux-3.2.0-4-amd64-x86_64-with-debian-7.9
[debug] exe versions: avconv 1.2.12, avprobe 1.2.12, ffmpeg 1.2.12, ffprobe 1.2.12, rtmpdump 2.4
[debug] Proxy map: {}
WARNING: The program functionality for this site has been marked as broken, and will probably not work.
[ESPN] film?page=the-schedule-makers: Downloading webpage
ERROR: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 655, in extract_info
    ie_result = ie.extract(url)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/common.py", line 287, in extract
    return self._real_extract(url)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/espn.py", line 45, in _real_extract
    webpage, 'video id')
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/common.py", line 575, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Thank you in advance. :)

**Comment by taichatha** [comment]
You need to right click on the video and copy the url. I think you pasted the page of the video in the command line. However, you need to download avcon or ffmpeg.

**Comment by antdude** [comment]
When I right click in Firefox and SeaMonkey, I did not see an URL with the video playing? Did I miss something?
