### ISSUE TITLE
Can't download finalbosses.com's videos.

### ISSUE THREAD

**Issue by antdude** [rg3/youtube-dl#6739]
Hello.

Example: $ youtube-dl -v http://finalbosses.com/playing-with-sacks-golden-axe/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://finalbosses.com/playing-with-sacks-golden-axe/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.08.28
[debug] Python version 2.7.3 - Linux-3.2.0-4-amd64-x86_64-with-debian-7.9
[debug] exe versions: avconv 1.2.12, avprobe 1.2.12, ffmpeg 1.2.12, ffprobe 1.2.12, rtmpdump 2.4
[debug] Proxy map: {}
[generic] playing-with-sacks-golden-axe: Requesting header
WARNING: Falling back on generic information extractor.
[generic] playing-with-sacks-golden-axe: Downloading webpage
[generic] playing-with-sacks-golden-axe: Extracting information
ERROR: Unsupported URL: http://finalbosses.com/playing-with-sacks-golden-axe/
Traceback (most recent call last):
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1211, in _real_extract
    doc = parse_xml(webpage)
  File "/home/ant/bin/youtube-dl/youtube_dl/utils.py", line 1594, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1301, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1643, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1507, in _raiseerror
    raise err
ParseError: undefined entity: line 15, column 0
Traceback (most recent call last):
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 655, in extract_info
    ie_result = ie.extract(url)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/common.py", line 287, in extract
    return self._real_extract(url)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1804, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://finalbosses.com/playing-with-sacks-golden-axe/

Thank you in advance. :)

**Comment by dstftw** [comment]
Works fine with latest version.

**Comment by antdude** [comment]
dstftw: Yep, it works now. Thanks. :)
