### ISSUE TITLE
ruutu.fi site updated, plugin broken as result

### ISSUE THREAD

**Issue by LoneFox78** [rg3/youtube-dl#6759]
It doesn't even recognize the new URLs:
```
tmp (lonefox): youtube-dl --verbose http://www.ruutu.fi/video/2189915
[debug] System config: []
[debug] User config: ['--no-mtime', '--no-cache-dir', '--no-check-certificate', '--youtube-skip-dash-manifest', '-f', 'best']
[debug] Command-line args: ['--verbose', 'http://www.ruutu.fi/video/2189915']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.09.03
[debug] Python version 3.4.3 - Linux-4.1.2-x86_64-AMD_Phenom-tm-_8600B_Triple-Core_Processor-with-glibc2.2.5
[debug] exe versions: avconv 11.4, avprobe 11.4, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 2189915: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 2189915: Downloading webpage
[generic] 2189915: Extracting information
ERROR: Unsupported URL: http://www.ruutu.fi/video/2189915
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 655, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 287, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/generic.py", line 1820, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.ruutu.fi/video/2189915
```

**Comment by dstftw** [comment]
This issue has been fixed and will be available in the next version. Thanks for the report.
