### ISSUE TITLE
ERROR: Signature Extraction Failed

### ISSUE THREAD

**Issue by enfoqueNativo** [rg3/youtube-dl#6763]
It fails with almost any youtube video, full log below

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '-f', '37/22/18', '-x', '--audio-format', 'mp3', '--audio-quality', '0', 'https://www.youtube.com/watch?v=uRfisbSqAUk']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.08.10
[debug] Python version 2.7.8 - Linux-3.16.7-24-desktop-x86_64-with-SuSE-13.2-x86_64
[debug] Proxy map: {}
[youtube] Setting language
[youtube] uRfisbSqAUk: Downloading webpage
[youtube] uRfisbSqAUk: Downloading video info webpage
[youtube] uRfisbSqAUk: Extracting video information
[youtube] uRfisbSqAUk: Encrypted signatures detected.
[youtube] {22} signature length 44.40, html5 player new
[youtube] uRfisbSqAUk: Downloading js player new
ERROR: Signature extraction failed: Traceback (most recent call last):
    File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 516, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 170, in extract
    return self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 860, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 489, in _decrypt_signature
    u'Signature extraction failed: ' + tb, cause=e)
ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 479, in _decrypt_signature
    video_id, player_url, s
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 383, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 454, in _parse_sig_js
    u'Initial JS player signature function name')
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 391, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract Initial JS player signature function name; 
```

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.
