### ISSUE TITLE
RegexNotFoundError: Unable to extract Initial JS player signature function name;

### ISSUE THREAD

**Issue by jaivikram** [rg3/youtube-dl#6766]
```bash
jai@Thunder:~/Music$ youtube-dl --verbose https://www.youtube.com/watch?v=1E7tz0zRlpE
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=1E7tz0zRlpE']
[debug] Encodings: locale 'UTF-8', fs 'UTF-8', out 'UTF-8', pref: 'UTF-8'
[debug] youtube-dl version 2014.02.17
[debug] Python version 2.7.6 - Linux-3.13.0-54-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] Proxy map: {}
[youtube] Setting language
[youtube] 1E7tz0zRlpE: Downloading webpage
[youtube] 1E7tz0zRlpE: Downloading video info webpage
[youtube] 1E7tz0zRlpE: Extracting video information
[youtube] 1E7tz0zRlpE: Encrypted signatures detected.
[youtube] encrypted signature length 85 (44.40), itag 43, html5 player new-en_US-vflCeB3p5\/html5player-new
[youtube] 1E7tz0zRlpE: Downloading js player new
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 957, in _decrypt_signature
    video_id, player_url, len(s)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 356, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 424, in _parse_sig_js
    u'Initial JS player signature function name')
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 356, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

WARNING: Warning: Falling back to static signature algorithm
[youtube] encrypted signature length 85 (44.40), itag 18, html5 player new-en_US-vflCeB3p5\/html5player-new
[youtube] 1E7tz0zRlpE: Downloading js player new
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 957, in _decrypt_signature
    video_id, player_url, len(s)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 356, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 424, in _parse_sig_js
    u'Initial JS player signature function name')
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 356, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

WARNING: Warning: Falling back to static signature algorithm
```

and the last block keeps repeating in a loop

**Comment by jaivikram** [comment]
saw this https://github.com/rg3/youtube-dl/issues/6741#issuecomment-137004406 late.
closing.
