### ISSUE TITLE
error on convert audio ffmpeg 

### ISSUE THREAD

**Issue by tone87** [rg3/youtube-dl#6779]
[debug] System config: [u'--prefer-free-formats']
[debug] User config: []
[debug] Command-line args: [u'https://www.youtube.com/watch?v=GCPQ6_F-xfo', u'--extract-audio', u'--audio-format', u'mp3', u'--verbose']
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out None, pref ANSI_X3.4-1968
[debug] youtube-dl version 2015.09.03
[debug] Python version 2.6.6 - Linux-2.6.32-431.11.2.el6.x86_64-x86_64-with-centos-6.5-Final
[debug] exe versions: ffmpeg 2.2.1, ffprobe 2.2.1
[debug] Proxy map: {}
[youtube] GCPQ6_F-xfo: Downloading webpage
[youtube] GCPQ6_F-xfo: Downloading video info webpage
[youtube] GCPQ6_F-xfo: Extracting video information
[youtube] {22} signature length 44.40, html5 player new-en_US-vflCeB3p5
[youtube] {43} signature length 44.40, html5 player new-en_US-vflCeB3p5
[youtube] {18} signature length 44.40, html5 player new-en_US-vflCeB3p5
[youtube] {5} signature length 44.40, html5 player new-en_US-vflCeB3p5
[youtube] {36} signature length 44.40, html5 player new-en_US-vflCeB3p5
[youtube] {17} signature length 44.40, html5 player new-en_US-vflCeB3p5
[youtube] {13} signature length 44.40, html5 player new-en_US-vflCeB3p5
[youtube] {137} signature length 44.40, html5 player new-en_US-vflCeB3p5
[youtube] {248} signature length 44.40, html5 player new-en_US-vflCeB3p5
[youtube] {136} signature length 44.40, html5 player new-en_US-vflCeB3p5
[youtube] {247} signature length 44.40, html5 player new-en_US-vflCeB3p5
[youtube] {135} signature length 44.40, html5 player new-en_US-vflCeB3p5
[youtube] {244} signature length 44.40, html5 player new-en_US-vflCeB3p5
[youtube] {134} signature length 44.40, html5 player new-en_US-vflCeB3p5
[youtube] {243} signature length 44.40, html5 player new-en_US-vflCeB3p5
[youtube] {133} signature length 44.40, html5 player new-en_US-vflCeB3p5
[youtube] {242} signature length 44.40, html5 player new-en_US-vflCeB3p5
[youtube] {160} signature length 44.40, html5 player new-en_US-vflCeB3p5
[youtube] {278} signature length 44.40, html5 player new-en_US-vflCeB3p5
[youtube] {140} signature length 44.40, html5 player new-en_US-vflCeB3p5
[youtube] {171} signature length 44.40, html5 player new-en_US-vflCeB3p5
[youtube] {249} signature length 44.40, html5 player new-en_US-vflCeB3p5
[youtube] {250} signature length 44.40, html5 player new-en_US-vflCeB3p5
[youtube] {251} signature length 44.40, html5 player new-en_US-vflCeB3p5
[youtube] GCPQ6_F-xfo: Downloading DASH manifest
[debug] Invoking downloader on u'https://r3---sn-uv2pm-ugoe.googlevideo.com/videoplayback?lmt=1436197348636291&requiressl=yes&clen=3379719&sparams=clen%2Cdur%2Cgcr%2Cgir%2Cid%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&expire=1441593653&key=yt5&mv=u&pl=21&mt=1441571661&ms=au&id=o-AHMzu_PvWR3x-haxObL6MRAfGa_VoUSLfEkpZbkRi8jP&mn=sn-uv2pm-ugoe&source=youtube&mm=31&gir=yes&ip=149.3.145.54&itag=251&upn=m1S8j15tnqU&dur=206.161&gcr=it&mime=audio%2Fwebm&sver=3&fexp=9408492%2C9408710%2C9409069%2C9415088%2C9415365%2C9415485%2C9415942%2C9416023%2C9416126%2C9416852%2C9417117%2C9417707%2C9417843%2C9418028%2C9418153%2C9418199%2C9418204%2C9418393%2C9418448%2C9419446%2C9419542%2C9419676%2C9420023%2C9420321%2C9420348&keepalive=yes&ipbits=0&signature=5D95CADFF043766F8192D3201452D0B42B0B6103.EDB9D97FF9E762EE8EDB1937312C872A63688D94&ratebypass=yes'
[download] Destination: Baby K - Roma - Bangkok (Official Video) ft. Giusy Ferreri-GCPQ6_F-xfo.webm
[download] 0.0% of 3.22MiB at Unknown speed ETA Unknown ETA
[download] 0.1% of 3.22MiB at Unknown speed ETA Unknown ETA
[download] 0.2% of 3.22MiB at Unknown speed ETA Unknown ETA
[download] 0.5% of 3.22MiB at Unknown speed ETA Unknown ETA
[download] 0.9% of 3.22MiB at 24.71MiB/s ETA 00:00
[download] 1.9% of 3.22MiB at 38.24MiB/s ETA 00:00
[download] 3.8% of 3.22MiB at 36.16MiB/s ETA 00:00
[download] 7.7% of 3.22MiB at 42.44MiB/s ETA 00:00
[download] 15.5% of 3.22MiB at 47.79MiB/s ETA 00:00
[download] 31.0% of 3.22MiB at 46.03MiB/s ETA 00:00
[download] 62.0% of 3.22MiB at 55.83MiB/s ETA 00:00
[download] 100.0% of 3.22MiB at 56.12MiB/s ETA 00:00
[download] 100% of 3.22MiB in 00:00
[debug] ffmpeg command line: ffprobe -show_streams 'Baby K - Roma - Bangkok (Official Video) ft. Giusy Ferreri-GCPQ6_F-xfo.webm'
[ffmpeg] Destination: Baby K - Roma - Bangkok (Official Video) ft. Giusy Ferreri-GCPQ6_F-xfo.mp3
[debug] ffmpeg command line: ffmpeg -y -i 'Baby K - Roma - Bangkok (Official Video) ft. Giusy Ferreri-GCPQ6_F-xfo.webm' -vn -acodec libmp3lame -q:a 5 'Baby K - Roma - Bangkok (Official Video) ft. Giusy Ferreri-GCPQ6_F-xfo.mp3'
ERROR: audio conversion failed: Error opening filters!
Traceback (most recent call last):
File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1699, in post_process
files_to_delete, info = pp.run(info)
File "/usr/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 276, in run
'audio conversion failed: ' + e.msg)
PostProcessingError

**Comment by yan12125** [comment]
Can you paste the results from the following command?
```
ffmpeg -y -i 'Baby K - Roma - Bangkok (Official Video) ft. Giusy Ferreri-GCPQ6_F-xfo.webm' -vn -acodec libmp3lame -q:a 5 'Baby K - Roma - Bangkok (Official Video) ft. Giusy Ferreri-GCPQ6_F-xfo.mp3'
```

**Comment by tone87** [comment]
ffmpeg version 2.2.1 Copyright (c) 2000-2014 the FFmpeg developers
built on Apr 13 2014 13:00:18 with gcc 4.4.6 (GCC) 20120305 (Red Hat 4.4.6-4)
configuration: --prefix=/usr --libdir=/usr/lib64 --shlibdir=/usr/lib64 --mandir=/usr/share/man --enable-shared --enable-runtime-cpudetect --enable-gpl --enable-version3 --enable-postproc --enable-avfilter --enable-pthreads --enable-x11grab --enable-vdpau --disable-avisynth --enable-frei0r --enable-libopencv --enable-libdc1394 --enable-libgsm --enable-libmp3lame --enable-libnut --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librtmp --enable-libspeex --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libxavs --enable-libxvid --extra-cflags='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -fPIC' --disable-stripping
libavutil 52. 66.100 / 52. 66.100
libavcodec 55. 52.102 / 55. 52.102
libavformat 55. 33.100 / 55. 33.100
libavdevice 55. 10.100 / 55. 10.100
libavfilter 4. 2.100 / 4. 2.100
libswscale 2. 5.102 / 2. 5.102
libswresample 0. 18.100 / 0. 18.100
libpostproc 52. 3.100 / 52. 3.100
Guessed Channel Layout for Input Stream #0.0 : stereo
Input #0, matroska,webm, from 'Baby K - Roma - Bangkok (Official Video) ft. Giusy Ferreri-GCPQ6_F-xfo.webm':
Metadata:
encoder : google
Duration: 00:03:26.16, start: 0.000000, bitrate: 131 kb/s
Stream #0:0(eng): Audio: opus, 48000 Hz, stereo (default)
[abuffer @ 0xe60b60] Unable to parse option value "(null)" as sample format
Last message repeated 1 times
[abuffer @ 0xe60b60] Error setting option sample_fmt to value (null).
[graph 0 input from stream 0:0 @ 0xe60a40] Error applying options to the filter.
Error opening filters!

**Comment by kikuyan** [comment]
ffmpeg pre 2.3 doesn't have native opus decoder and need --enable-libopus.
