### ISSUE TITLE
https://genvideos.org

### ISSUE THREAD

**Issue by antdude** [rg3/youtube-dl#6795]
Hello.

Example: 
$ youtube-dl -v https://genvideos.org/watch?v=Frozen_Fever_2015
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://genvideos.org/watch?v=Frozen_Fever_2015']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.09.03
[debug] Python version 2.7.3 - Linux-3.2.0-4-amd64-x86_64-with-debian-7.9
[debug] exe versions: avconv 1.2.12, avprobe 1.2.12, ffmpeg 1.2.12, ffprobe 1.2.12, rtmpdump 2.4
[debug] Proxy map: {}
[generic] watch?v=Frozen_Fever_2015: Requesting header
WARNING: Falling back on generic information extractor.
[generic] watch?v=Frozen_Fever_2015: Downloading webpage
[generic] watch?v=Frozen_Fever_2015: Extracting information
ERROR: Unsupported URL: https://genvideos.org/watch?v=Frozen_Fever_2015
Traceback (most recent call last):
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1222, in _real_extract
    doc = parse_xml(webpage)
  File "/home/ant/bin/youtube-dl/youtube_dl/utils.py", line 1599, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1301, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1643, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1507, in _raiseerror
    raise err
ParseError: mismatched tag: line 38, column 2
Traceback (most recent call last):
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 655, in extract_info
    ie_result = ie.extract(url)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/common.py", line 287, in extract
    return self._real_extract(url)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1820, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://genvideos.org/watch?v=Frozen_Fever_2015

Thank you in advance. :)

**Comment by yan12125** [comment]
[genvideos.com has lots of illegal contents](http://www.google.com/transparencyreport/removals/copyright/domains/genvideos.com/), and this one seems illegal, too. And according to [youtube-dl's policy](https://github.com/rg3/youtube-dl/#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free), copyright violating websites will not be supported.
