### ISSUE TITLE
Unable to download a playlist - Playlist page is missing OpenGraph title, falling back

### ISSUE THREAD

**Issue by hillz1** [rg3/youtube-dl#6827]
I can't download from this link https://www.youtube.com/playlist?list=PL82YdDfxhWsDJTq5f0Ae7M7yGcA26wevJ 

This is the error log:
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['https://www.youtube.com/playlist?list=PL82YdDfxhWsDJTq5f0Ae7M7yGcA26wevJ', '--verbose']
[debug] Encodings: locale 'UTF-8', fs 'UTF-8', out 'UTF-8', pref: 'UTF-8'
[debug] youtube-dl version 2014.02.17
[debug] Python version 2.7.6 - Linux-3.19.0-28-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] Proxy map: {}
WARNING: [youtube:playlist] PL82YdDfxhWsDJTq5f0Ae7M7yGcA26wevJ: Playlist page is missing OpenGraph title, falling back ...
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 1511, in _real_extract
    playlist_title = self._og_search_title(page)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 428, in _og_search_title
    return self._og_search_property('title', html, **kargs)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 416, in _og_search_property
    escaped = self._search_regex(self._og_regexes(prop), html, name, flags=re.DOTALL, **kargs)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 356, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract OpenGraph title; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 493, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 158, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 1517, in _real_extract
    r'<h1 class="pl-header-title">(.*?)</h1>', page, u'title')
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 366, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 356, in _search_regex
    raise RegexNotFoundError(u'Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.```

Please fix it

**Comment by hillz1** [comment]
Fixed by downloading the latest version, thanks
