### ISSUE TITLE
Clubic support broken

### ISSUE THREAD

**Issue by skyghis** [rg3/youtube-dl#6854]
Clubic support seem broken. Refs #2773

I can't download last clubic-week : 

```
$youtube-dl --verbose http://www.clubic.com/video/video-clubic-week-2-0-apple-iphone-6s-et-plus-mais-surtout-le-pencil-469792.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.clubic.com/video/video-clubic-week-2-0-apple-iphone-6s-et-plus-mais-surtout-le-pencil-469792.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.09.09
[debug] Python version 2.7.9 - Linux-3.19.0-26-generic-x86_64-with-Ubuntu-15.04-vivid
[debug] exe versions: avconv 11.2-6, avprobe 11.2-6
[debug] Proxy map: {}
[generic] video-clubic-week-2-0-apple-iphone-6s-et-plus-mais-surtout-le-pencil-469792: Requesting header
WARNING: Falling back on generic information extractor.
[generic] video-clubic-week-2-0-apple-iphone-6s-et-plus-mais-surtout-le-pencil-469792: Downloading webpage
[generic] video-clubic-week-2-0-apple-iphone-6s-et-plus-mais-surtout-le-pencil-469792: Extracting information
ERROR: Unsupported URL: http://www.clubic.com/video/video-clubic-week-2-0-apple-iphone-6s-et-plus-mais-surtout-le-pencil-469792.html
Traceback (most recent call last):
  File "/home/skyghis/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1222, in _real_extract
    doc = parse_xml(webpage)
  File "/home/skyghis/bin/youtube-dl/youtube_dl/utils.py", line 1656, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: syntax error: line 1, column 0
Traceback (most recent call last):
  File "/home/skyghis/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 660, in extract_info
    ie_result = ie.extract(url)
  File "/home/skyghis/bin/youtube-dl/youtube_dl/extractor/common.py", line 287, in extract
    return self._real_extract(url)
  File "/home/skyghis/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1820, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.clubic.com/video/video-clubic-week-2-0-apple-iphone-6s-et-plus-mais-surtout-le-pencil-469792.html
```

```
$youtube-dl --version
2015.09.09
```

Thanks for all the work :+1:

**Comment by dstftw** [comment]
This issue has been fixed and will be available in the next version. Thanks for the report.
