### ISSUE TITLE
Signature extraction failed

### ISSUE THREAD

**Issue by au2001** [rg3/youtube-dl#6859]
$ youtube-dl --verbose http://youtube.com/watch?v=m-IuNfdXYEA
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://youtube.com/watch?v=m-IuNfdXYEA']
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
[debug] youtube-dl version 2014.08.05
[debug] Python version 2.7.9 - Linux-2.6.32-042stab108.8-x86_64-with-debian-8.2
[debug] Proxy map: {}
[youtube] Setting language
[youtube] m-IuNfdXYEA: Downloading webpage
[youtube] m-IuNfdXYEA: Downloading video info webpage
[youtube] m-IuNfdXYEA: Extracting video information
[youtube] m-IuNfdXYEA: Encrypted signatures detected.
[youtube] {22} signature length 46.43, html5 player new
[youtube] m-IuNfdXYEA: Downloading js player new
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 479, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 382, in _extract_signature_function
    errnote=u'Download of %s failed' % player_url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 283, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 223, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 211, in _request_webpage
    raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
ExtractorError: Download of https://s.ytimg.com/yts/jsbin/html5player-new-en_US-vflhlPTtB/html5player-new.js failed: \<urlopen error [Errno -2] Name or service not known>
; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 479, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 382, in _extract_signature_function
    errnote=u'Download of %s failed' % player_url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 283, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 223, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 211, in _request_webpage
    raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
ExtractorError: Download of https://s.ytimg.com/yts/jsbin/html5player-new-en_US-vflhlPTtB/html5player-new.js failed: \<urlopen error [Errno -2] Name or service not known>
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 516, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 170, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 860, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 489, in _decrypt_signature
    u'Signature extraction failed: ' + tb, cause=e)
ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 479, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 382, in _extract_signature_function
    errnote=u'Download of %s failed' % player_url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 283, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 223, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 211, in _request_webpage
    raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
ExtractorError: Download of https://s.ytimg.com/yts/jsbin/html5player-new-en_US-vflhlPTtB/html5player-new.js failed: \<urlopen error [Errno -2] Name or service not known>

**Comment by jaimeMF** [comment]
> [debug] youtube-dl version 2014.08.05

You are using an outdated version, [you have to upgrade youtube-dl](https://github.com/rg3/youtube-dl/blob/8f9d522f6252f874d41045b2458256ca8cf1a312/README.md#how-do-i-update-youtube-dl).
