### ISSUE TITLE
Libsyn not supported? ERROR: Unsupported URL

### ISSUE THREAD

**Issue by redwrist** [rg3/youtube-dl#6879]
I tried both the site and rss, `youtube-dl http://yourmomshousepodcast.libsyn.com/` and `http://yourmomshousepodcast.libsyn.com/rss`. Getting "ERROR: Unsupported URL" on both.

**Comment by hofmand** [comment]
Here's a log from a Libsyn site that reports "Unsupported URL":

```
C:\>youtube-dl -v https://theamphour.libsyn.com/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://theamphour.libsyn.com/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg N-92681-g0e833f615b, ffprobe N-92681-g0e833f615b
[debug] Proxy map: {}
[generic] theamphour.libsyn: Requesting header
WARNING: Falling back on generic information extractor.
[generic] theamphour.libsyn: Downloading webpage
[generic] theamphour.libsyn: Extracting information
ERROR: Unsupported URL: https://theamphour.libsyn.com/
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbsbtmq\build\youtube_dl\extractor\generic.py", line 3382, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://theamphour.libsyn.com/
```
