### ISSUE TITLE
Site Support Request: Ars Technica

### ISSUE THREAD

**Issue by aaronvegh** [rg3/youtube-dl#6885]
Running the latest 2015.09.09 version, I get this result:

```
$ youtube-dl -v -j "http://arstechnica.com/gadgets/2015/09/smart-rifle-company-trackingpoint-restructures-and-relaunches/"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'-j', u'http://arstechnica.com/gadgets/2015/09/smart-rifle-company-trackingpoint-restructures-and-relaunches/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.09.09
[debug] Python version 2.7.6 - Linux-4.1.0-x86_64-linode59-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.18-6, avprobe 9.18-6, rtmpdump 2.4
[debug] Proxy map: {}
WARNING: Falling back on generic information extractor.
ERROR: Unsupported URL: http://arstechnica.com/gadgets/2015/09/smart-rifle-company-trackingpoint-restructures-and-relaunches/
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1222, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1656, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: mismatched tag: line 76, column 6
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 660, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 287, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1820, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://arstechnica.com/gadgets/2015/09/smart-rifle-company-trackingpoint-restructures-and-relaunches/
```

Notably if I inspect the `video` element on that page, it appears to be a simple MP4 file hosted on Cloudfront. Any chance this can be more readily integrated into youtube-dl than your average hosting service? :-)

**Comment by jaimeMF** [comment]
I can't find any video on that webpage, can you check it and post a screenshot if it displays it for you?

**Comment by aaronvegh** [comment]
Crap, I am *so* sorry! I was messing with a couple of different URLs on that site today and ended up pasting in the wrong one. Let's do it again:

```
$ youtube-dl -v -j "http://arstechnica.com/security/2015/09/video-3d-printed-tsa-travel-sentry-keys-really-do-open-tsa-locks/"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'-j', u'http://arstechnica.com/security/2015/09/video-3d-printed-tsa-travel-sentry-keys-really-do-open-tsa-locks/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.08.23
[debug] Python version 2.7.10 - Darwin-14.5.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
WARNING: Falling back on generic information extractor.
ERROR: Unsupported URL: http://arstechnica.com/security/2015/09/video-3d-printed-tsa-travel-sentry-keys-really-do-open-tsa-locks/
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1211, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1594, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: mismatched tag: line 78, column 6
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 655, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 287, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1804, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://arstechnica.com/security/2015/09/video-3d-printed-tsa-travel-sentry-keys-really-do-open-tsa-locks/
```

**Comment by oliciv** [comment]
@dstftw Oops, thanks - hadn't seen it was covered elsewhere. The CN extractor doesn't seem to work/match for the supplied URL though?
