### ISSUE TITLE
VK.com extractor seems to be broken

### ISSUE THREAD

**Issue by bcomnes** [rg3/youtube-dl#6902]
It seems VK.com might be blocking it:

```
bret-mbr:Downloads bret$ youtube-dl --verbose https://vk.com/wall-74895234_1757
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://vk.com/wall-74895234_1757']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.09.09
[debug] Python version 2.7.10 - Darwin-14.5.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.7.2, ffprobe 2.7.2
[debug] Proxy map: {}
[generic] wall-74895234_1757: Requesting header
WARNING: Could not send HEAD request to https://vk.com/wall-74895234_1757: HTTP Error 501: Not Implemented
[generic] wall-74895234_1757: Downloading webpage
WARNING: Falling back on generic information extractor.
[generic] wall-74895234_1757: Extracting information
[redirect] Following redirect to https://vk.com/badbrowser.php
[generic] badbrowser: Requesting header
WARNING: Could not send HEAD request to https://vk.com/badbrowser.php: HTTP Error 501: Not Implemented
[generic] badbrowser: Downloading webpage
WARNING: Falling back on generic information extractor.
[generic] badbrowser: Extracting information
ERROR: Unsupported URL: https://vk.com/badbrowser.php
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1222, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1656, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1301, in XML
    return parser.close()
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1654, in close
    self._raiseerror(v)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: no element found: line 140, column 7
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 660, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 287, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1820, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://vk.com/badbrowser.php
```

Any workarounds in a situation like this?

**Comment by bcomnes** [comment]
Oops.  Dupe.  Apologies!

**Comment by bcomnes** [comment]
Just informed that youtube-dl does not download audio from VK.com, but the source is easily extracted from the html.
