### ISSUE TITLE
Latest update breaks on 10.6.8

### ISSUE THREAD

**Issue by pps** [rg3/youtube-dl#6905]
I just updated to the latest version of youtube-dl, and it stopped working. Replaced it with an older version, it worked again, updated it, it stopped again.

```
$ yt NzuuU9PU9-c -F
[youtube] NzuuU9PU9-c: Downloading webpage
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/runpy.py", line 121, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/runpy.py", line 34, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 410, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 400, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1658, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 660, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 287, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 989, in _real_extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 438, in _download_webpage
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 345, in _download_webpage_handle
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 326, in _request_webpage
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1865, in urlopen
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/urllib2.py", line 383, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/urllib2.py", line 401, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/urllib2.py", line 361, in _call_chain
    result = func(*args)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 783, in https_open
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/urllib2.py", line 1098, in do_open
    h = http_class(host, timeout=req.timeout) # will parse host:port
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 623, in _create_http_connection
TypeError: __init__() keywords must be strings
```

For what it's worth, I also checked whether /System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/runpy.py was changed on my machine since a backup where everything worked fine, and this was not the case.

Thanks for any help.

**Comment by dstftw** [comment]
Post the **full** output of youtube-dl when run [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by ThomasTheSpaceFox** [comment]
Same error here.  i was just testing GTKplayYT my youtube-dl shell after updating youtube-dl and i get this error. actually had to load a older version of youtube-dl just to watch a video.

**Comment by dstftw** [comment]
Update python to fix this currently.
