### ISSUE TITLE
[ComedyCentral] MTV mgid extractor fails

### ISSUE THREAD

**Issue by GravisZro** [rg3/youtube-dl#6936]
just tried <a href="http://www.cc.com/full-episodes/f7pabz/the-nightly-show-with-larry-wilmore-september-21--2015---bernie-sanders-interview-season-1-ep-01109">watching a show from cc.com</a> with the latest build.

```
$ ./youtube-dl http://www.cc.com/full-episodes/f7pabz/the-nightly-show-with-larry-wilmore-september-21--2015---bernie-sanders-interview-season-1-ep-01109 --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://www.cc.com/full-episodes/f7pabz/the-nightly-show-with-larry-wilmore-september-21--2015---bernie-sanders-interview-season-1-ep-01109', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.09.22
[debug] Python version 2.7.10 - Linux-4.0.0-trunk-amd64-x86_64-with-Ubuntu-12.04-precise
[debug] exe versions: rtmpdump 2.4
[debug] Proxy map: {}
[ComedyCentral] the-nightly-show-with-larry-wilmore-september-21--2015---bernie-sanders-interview-season-1-ep-01109: Downloading webpage
ERROR: Unable to extract mgid; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/extractor/mtv.py", line 193, in _real_extract
    og_url = self._og_search_video_url(webpage)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 680, in _og_search_video_url
    return self._html_search_regex(regexes, html, name, **kargs)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 590, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 581, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 660, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 287, in extract
    return self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/mtv.py", line 203, in _real_extract
    webpage, 'mgid')
  File "./youtube-dl/youtube_dl/extractor/common.py", line 581, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract mgid; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by priestc** [comment]
I'm getting the same error :(

This same issue came up a few months ago regarding The Nightly Show and this `mgid` value.

**Comment by malept** [comment]
#5374 should make it work again.
