### ISSUE TITLE
Cannot find video error in livestream

### ISSUE THREAD

**Issue by valmy** [rg3/youtube-dl#6988]
```
~/.local/bin/youtube-dl http://livestream.com/ChessCast/events/4298205/videos/99776320 --verbose                  
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://livestream.com/ChessCast/events/4298205/videos/99776320', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.09.22
[debug] Python version 2.7.9 - Linux-3.19.0-28-generic-x86_64-with-Ubuntu-15.04-vivid
[debug] exe versions: ffmpeg 2.5.8-0ubuntu0.15.04.1, ffprobe 2.5.8-0ubuntu0.15.04.1
[debug] Proxy map: {}
[livestream] 99776320: Downloading webpage
ERROR: Cannot find video 99776320; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/tbudiman/.local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 660, in extract_info
    ie_result = ie.extract(url)
  File "/home/tbudiman/.local/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 287, in extract
    return self._real_extract(url)
  File "/home/tbudiman/.local/lib/python2.7/site-packages/youtube_dl/extractor/livestream.py", line 190, in _real_extract
    raise ExtractorError('Cannot find video %s' % video_id)
ExtractorError: Cannot find video 99776320; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by jaimeMF** [comment]
It doesn't load on a browser, that it works for you?

**Comment by valmy** [comment]
The link works in my browser, it leads to:
http://api.new.livestream.com/accounts/7928738/events/4298205/videos/99776320.m3u8
on my chrome in Android.

**Comment by corone17** [comment]
It's because this video with id "99776320" and the corresponding mp4- and m3u8-urls is part of the json-element "post" instead of "feed". Also it seems youtube-dl doesn't detect the m3u8-urls at all.
```
  "post": {
    "id": 99776320,
    "caption": "In the studio with Vladimir Kramnik",
    "duration": 1032000,
    "broadcast_id": 99766365,
    "original_duration": 20446747,
    "copied_from": 99766364,
    "description": null,
    "asset": {
      "qualities": [
        {
          "name": "Mobile Quality",
          "bitrate": 174000,
          "width": 480,
          "height": 270,
          "angle": 1
        },
        {
          "name": "Medium Quality",
          "bitrate": 614000,
          "width": 768,
          "height": 432,
          "angle": 1
        },
        {
          "name": "High Quality",
          "bitrate": 1628000,
          "width": 864,
          "height": 486,
          "angle": 1
        },
        {
          "name": "HD Quality",
          "bitrate": 2160000,
          "width": 1280,
          "height": 720,
          "angle": 1
        }
      ],
      "akamai_stream_id": 125242,
      "stream_name": "7928738_4298205_227ff20f_1",
      "workflow_status": "downloaded",
      "state": null,
      "workflow_retry_count": 0,
      "workflow_error": 0,
      "workflow_progress": 0,
      "downloader_progress": 0,
      "transcoded": true,
      "transcode_started_at": "2015-09-20T15:34:44.844Z",
      "inserted_to_download_queue_at": "2015-09-20T15:31:55.354Z",
      "inserted_to_transcoding_queue_at": null,
      "received_video_from_user_at": null,
      "application_name": "Livestream Producer"
    },
    "in": 10955,
    "out": 11987,
    "thumbnail_width": 1280,
    "thumbnail_height": 720,
    "draft": false,
    "tags": null,
    "created_at": "2015-09-20T13:19:36.273Z",
    "updated_at": "2015-09-20T16:33:25.588Z",
    "streamed_at": null,
    "publish_at": "2015-09-20T13:19:35.955Z",
    "views": 17084,
    "likes": {
      "total": 0,
      "data": []
    },
    "comments": {
      "total": 0,
      "data": []
    },
    "thumbnail_url": "http://img.new.livestream.com/events/00000000004195dd/d3d9711a-a8ca-4e9d-8269-cef891b963fe_11280.jpg",
    "thumbnail_url_small": "http://img.new.livestream.com/events/00000000004195dd/d3d9711a-a8ca-4e9d-8269-cef891b963fe_11280_150x84.jpg",
    "progressive_url": "http://pdvod.new.livestream.com/events/00000000004195dd/d3d9711a-a8ca-4e9d-8269-cef891b963fe_614.mp4?start=10955&end=11987&__gda__=1443834614_6e96dd24d399500a32470d83530191ef",
    "progressive_url_hd": "http://pdvod.new.livestream.com/events/00000000004195dd/d3d9711a-a8ca-4e9d-8269-cef891b963fe_2160.mp4?start=10955&end=11987&__gda__=1443834614_7c0aecfdc32688f55e400347fcc9c58d",
    "smil_url": "http://api.new.livestream.com/accounts/7928738/events/4298205/videos/99776320.smil",
    "secure_smil_url": "https://api.new.livestream.com/accounts/7928738/events/4298205/videos/99776320.secure.smil",
    "secure_progressive_url": "https://pdvod.new.livestream.com/events/00000000004195dd/d3d9711a-a8ca-4e9d-8269-cef891b963fe_614.mp4?start=10955&end=11987&__gda__=1443834614_6e96dd24d399500a32470d83530191ef",
    "secure_progressive_url_hd": "https://pdvod.new.livestream.com/events/00000000004195dd/d3d9711a-a8ca-4e9d-8269-cef891b963fe_2160.mp4?start=10955&end=11987&__gda__=1443834614_7c0aecfdc32688f55e400347fcc9c58d",
    "m3u8_url": "http://api.new.livestream.com/accounts/7928738/events/4298205/videos/99776320.m3u8",
    "secure_m3u8_url": "https://api.new.livestream.com/accounts/7928738/events/4298205/videos/99776320.secure.m3u8",
    "f4m_url": "http://api.new.livestream.com/accounts/7928738/events/4298205/videos/99776320.f4m",
    "secure_f4m_url": "https://api.new.livestream.com/accounts/7928738/events/4298205/videos/99776320.secure.f4m",
    "type": "video"
  },
```
