### ISSUE TITLE
IGN - Downloading video from incorrect cdn 

### ISSUE THREAD

**Issue by MaryCoding** [rg3/youtube-dl#7006]
I am trying to extract video from this [LINK](http://www.pcmag.com/videos/2015/09/22/092115-microsoft-office-chief-spitballs-about-3d-office-on-the-hololens). I am in north america, Youtube-dl in this case seems to be downloading from this cdn https://a248.e.akamai.net/assets2.ign.com/videos/zencoder/2015/9/21/640/fb03ab22da0f33c53e711a46433ccd17-500000-1442868763.mp4 which returns a 400 error. After visiting the original [LINK](http://www.pcmag.com/videos/2015/09/22/092115-microsoft-office-chief-spitballs-about-3d-office-on-the-hololens) and checking the network calls, the mp4 file is found here
 http://assets2.ign.com/videos/zencoder/2015/9/21/640/fb03ab22da0f33c53e711a46433ccd17-500000-1442868763.mp4

It seems that difference is in the beginning of the url `[0]https://a248.e.akamai.net/assets2.ign.com` vs `[1]http://assets2.ign.com`

```
youtube-dl -v --no-warnings -o "/media/%(title)s.%(ext)s" "http://www.pcmag.com/videos/ 2015/09/22/092115-microsoft-office-chief-spitballs-about-3d-office-on-the-hololens"
[debug] System config: [u'--ffmpeg-location', u'/home/mimi/bin/ffmpeg']
[debug] User config: []
[debug] Command-line args: [u'-v', u'--no-warnings', u'-o', u'/media/%(title)s.%(ext)s', u'http://www.p cmag.com/videos/2015/09/22/092115-microsoft-office-chief-spitballs-about-3d-office-on-the-hololens']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.09.22
[debug] Python version 2.7.9 - Linux-3.19.0-28-generic-x86_64-with-Ubuntu-15.04-vivid
[debug] exe versions: ffmpeg 2.6.git, ffprobe 2.6.git, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 092115-microsoft-office-chief-spitballs-about-3d-office-on-the-hololens: Requesting header
[generic] 092115-microsoft-office-chief-spitballs-about-3d-office-on-the-hololens: Downloading webpage
[generic] 092115-microsoft-office-chief-spitballs-about-3d-office-on-the-hololens: Extracting information
[debug] Invoking downloader on u'https://a248.e.akamai.net/assets2.ign.com/videos/zencoder/2015/9/21/640/fb03ab22da0f33c53e711a46433ccd17-500000-1442868763.mp4'
ERROR: unable to download video data: HTTP Error 400: Bad Request
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1590, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1532, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 342, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 60, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1865, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 400: Bad Request
```

**Comment by jaimeMF** [comment]
The generic extractors extract the link from the `twitter:player:stream` meta tag:
```
<meta property="twitter:player:stream" content="https://a248.e.akamai.net/assets2.ign.com/videos/zencoder/2015/9/21/640/fb03ab22da0f33c53e711a46433ccd17-500000-1442868763.mp4" />
```

In my case the IGN link (http://www.ign.com/videos/2015/09/22/092115-microsoft-office-chief-spitballs-about-3d-office-on-the-hololens) works, although I can't watch them in the browser.

**Comment by remitamine** [comment]
will be supported in the next version.
