### ISSUE TITLE
Unable to download WACC's recorded Vimeo videos.

### ISSUE THREAD

**Issue by antdude** [rg3/youtube-dl#7013]
Hello.

Is there a way to download these hidden Vimeo videos with youtube-dl like this example?
$ youtube-dl -v http://wacc.aspireonemedia.com/601/5803/23116
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://wacc.aspireonemedia.com/601/5803/23116']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.09.28
[debug] Python version 2.7.3 - Linux-3.2.0-4-amd64-x86_64-with-debian-7.9
[debug] exe versions: avconv 1.2.12, avprobe 1.2.12, ffmpeg 1.2.12, ffprobe 1.2.12, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 23116: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 23116: Downloading webpage
[generic] 23116: Extracting information
ERROR: Unsupported URL: http://wacc.aspireonemedia.com/601/5803/23116
Traceback (most recent call last):
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1240, in _real_extract
    doc = parse_xml(webpage)
  File "/home/ant/bin/youtube-dl/youtube_dl/utils.py", line 1656, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1301, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1643, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1507, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 6, column 568
Traceback (most recent call last):
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 660, in extract_info
    ie_result = ie.extract(url)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/common.py", line 288, in extract
    return self._real_extract(url)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1838, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://wacc.aspireonemedia.com/601/5803/23116

I cannot seem to find its location to properly download it. :( Thank you in advance. :)

**Comment by RingoTheDog** [comment]
https://skyfiregcs-a.akamaihd.net/exp=1443500158~acl=%2A%2F420732761.mp4%2A~hmac=66077a43d655a98ef65ccaa630aa96561a786df98ea977be1949f705c66a5c58/vimeo-prod-skyfire-std-us/01/3138/5/140693865/420732761.mp4

**Comment by antdude** [comment]
RingoTheDog: How did you get that URL? From youtube-dl?

**Comment by Xonshiz** [comment]
It's easy antdude. When the page is loaded, just open "developer console" (press F12 if using chrome, ctrl+shift+q if using mozilla). And navigate in the console to find the link.

Or there's one more way, the easy way. when the page is loading, open developer console and navigate to "Network" tab and in the filter tab, write "media". You'll see the links, copy paste them in a new tab and you'll get the video.

**Comment by antdude** [comment]
Xonshiz: Hmm, I use SeaMonkey that is based on Gecko's engine and don't seem to have that option. The closest I got as a media was https://f.vimeocdn.com/p/flash/moogaloop/6.2.2/moogaloop.swf?clip_id=140693865&z=1443496053308 ...

**Comment by Xonshiz** [comment]
https://addons.mozilla.org/en-us/seamonkey/addon/web-developer/

try this... install this addon.. it should be fine...

**Comment by antdude** [comment]
Xonshiz: I have it installed after downloading and restarting my web browser. I assume it is "Web Developer Extension", but I couldn't seem to find this "Developer Console". So many options. :/

**Comment by Xonshiz** [comment]
I don't use the browser you are using.. So, can't really help you there. I'd recommend installing mozilla too... Side by side, you know.. Mozilla is best when it comes to things like this.

**Comment by antdude** [comment]
It is based on Mozilla's Gecko engine. ;) It would be nice if YouTube-dl could find this URL to download the video.

**Comment by Xonshiz** [comment]
You could request the website to be added in that case.. that would be a better solution to your problem.. :)
