### ISSUE TITLE
[hearthis.at] ExtractorError: An extractor error has occured.

### ISSUE THREAD

**Issue by kirashi3** [rg3/youtube-dl#7049]
Just attempted to run youtube-dl on a hearthis.at song, and it fails during the Extractor phase. Logfile posted below.

```
G:\>youtube-dl.exe --verbose https://hearthis.at/djjbrew/never-gonna-shut-up-dance-rough-draft-2/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://hearthis.at/djjbrew/never-gonna-shut-up-dance-rough-draft-2/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.09.28
[debug] Python version 2.7.8 - Windows-8-6.2.9200
[debug] exe versions: ffmpeg N-69972-g6c91afe, ffprobe N-69972-g6c91afe
[debug] Proxy map: {}
[HearThisAt] djjbrew - never-gonna-shut-up-dance-rough-draft-2: Downloading webpage
[HearThisAt] 443616: Downloading playlist
WARNING: unable to extract comment count; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[HearThisAt] djjbrew - never-gonna-shut-up-dance-rough-draft-2: Determining extension
ERROR: An extractor error has occured. (caused by KeyError(u'content-disposition',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dl\extractor\common.pyo", line 288, in extract
  File "youtube_dl\extractor\hearthisat.pyo", line 94, in _real_extract
  File "youtube_dl\utils.pyo", line 1777, in urlhandle_detect_ext
  File "youtube_dl\utils.pyo", line 1773, in <lambda>
  File "rfc822.pyo", line 388, in __getitem__
KeyError: u'content-disposition'
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 660, in extract_info
  File "youtube_dl\extractor\common.pyo", line 294, in extract
ExtractorError: An extractor error has occured. (caused by KeyError(u'content-disposition',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by yan12125** [comment]
Sorry for the late response. HearThis.at will function again in the next version.
