### ISSUE TITLE
unable to download audio from vk.com posts

### ISSUE THREAD

**Issue by l29ah** [rg3/youtube-dl#7053]
‰ youtube-dl --verbose https://vk.com/wall-34049481_30938 
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-c', u'--verbose', u'https://vk.com/wall-34049481_30938']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.09.28
[debug] Python version 2.7.10 - Linux-4.1.5-grsec+-x86_64-Intel-R-_Core-TM-_i7_CPU_L_620_@_2.00GHz-with-gentoo-2.2
[debug] exe versions: ffmpeg 2.8, ffprobe 2.8, rtmpdump 2.4
[debug] Proxy map: {}
[generic] wall-34049481_30938: Requesting header
WARNING: Could not send HEAD request to https://vk.com/wall-34049481_30938: HTTP Error 501: Not Implemented
[generic] wall-34049481_30938: Downloading webpage
WARNING: Falling back on generic information extractor.
[generic] wall-34049481_30938: Extracting information
[redirect] Following redirect to https://vk.com/badbrowser.php
[generic] badbrowser: Requesting header
WARNING: Could not send HEAD request to https://vk.com/badbrowser.php: HTTP Error 501: Not Implemented
[generic] badbrowser: Downloading webpage
WARNING: Falling back on generic information extractor.
[generic] badbrowser: Extracting information
ERROR: Unsupported URL: https://vk.com/badbrowser.php
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/generic.py", line 1240, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/utils.py", line 1656, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1301, in XML
    return parser.close()
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1654, in close
    self._raiseerror(v)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: no element found: line 140, column 7
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 660, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/common.py", line 288, in extract
    return self._real_extract(url)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/generic.py", line 1838, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://vk.com/badbrowser.php

**Comment by Ristovski** [comment]
Can replicate, returns Not Implemented

**Comment by yan12125** [comment]
Looks similar to #7768. Merged into the newer one.
