### ISSUE TITLE
ERROR: no conn, hlsvp or url_encoded_fmt_stream_map information found in video info;

### ISSUE THREAD

**Issue by markwaters** [rg3/youtube-dl#7070]
youtube-dl --verbose https://www.youtube.com/watch?v=KPRzL5--CCI
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://www.youtube.com/watch?v=KPRzL5--CCI']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.09.28
[debug] Python version 2.7.9 - Linux-3.4.104-bananian-armv7l-with-debian-8.2
[debug] exe versions: avconv 11.4-6, avprobe 11.4-6, rtmpdump 2.4
[debug] Proxy map: {'all': 'http://proxy.collective-b.org.uk:8118', 'http': 'http://proxy.collective-b.org.uk:8118', 'https': 'http://proxy.collective-b.org.uk:8118', 'no': 'localhost,collective-b.org.uk,.collective-b.org.uk'}
[youtube] KPRzL5--CCI: Downloading webpage
[youtube] KPRzL5--CCI: Downloading video info webpage
[youtube] KPRzL5--CCI: Extracting video information
ERROR: no conn, hlsvp or url_encoded_fmt_stream_map information found in video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "./.youtube-dl/youtube_dl/YoutubeDL.py", line 660, in extract_info
    ie_result = ie.extract(url)
  File "./.youtube-dl/youtube_dl/extractor/common.py", line 288, in extract
    return self._real_extract(url)
  File "./.youtube-dl/youtube_dl/extractor/youtube.py", line 1352, in _real_extract
    raise ExtractorError('no conn, hlsvp or url_encoded_fmt_stream_map information found in video info')
ExtractorError: no conn, hlsvp or url_encoded_fmt_stream_map information found in video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Hope that helps...

**Comment by markwaters** [comment]
I see its a webinar from the future ?!
Closed. Sorry.
