### ISSUE TITLE
2015.10.6 does not work

### ISSUE THREAD

**Issue by spvkgn** [rg3/youtube-dl#7078]
Seems there is a bug with latest release. Previous release works well.

```
~ $ youtube-dl --help
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl", line 9, in <module>
    load_entry_point('youtube-dl==2015.10.6', 'console_scripts', 'youtube-dl')()
  File "/usr/local/lib/python3.2/dist-packages/youtube_dl/__init__.py", line 410, in main
    _real_main(argv)
  File "/usr/local/lib/python3.2/dist-packages/youtube_dl/__init__.py", line 57, in _real_main
    parser, opts, args = parseOpts(argv)
  File "/usr/local/lib/python3.2/dist-packages/youtube_dl/options.py", line 104, in parseOpts
    columns = compat_get_terminal_size().columns
  File "/usr/local/lib/python3.2/dist-packages/youtube_dl/compat.py", line 431, in compat_get_terminal_size
    if columns <= 0 or lines <= 0:
TypeError: unorderable types: NoneType() <= int()

~ $ pip3 show youtube-dl
---
Metadata-Version: 1.1
Name: youtube-dl
Version: 2015.10.6
Summary: YouTube video downloader
Home-page: https://github.com/rg3/youtube-dl
Author: Philipp Hagemeister
Author-email: phihag@phihag.de
License: UNKNOWN
Location: /usr/local/lib/python3.2/dist-packages
Requires: 
Entry-points:
  [console_scripts]
  youtube-dl = youtube_dl:main
```

**Comment by phihag** [comment]
Thank you for the report! I apologize for the bug - we did not test sufficiently with old 3.x releases. The bug should be fixed in youtube-dl 2015.10.6.1 and newer. See [our FAQ](https://yt-dl.org/update) if you need help updating (something along the lines of `pip3 install -U youtube-dl` if you used pip).
