### ISSUE TITLE
Failing to download PBS video

### ISSUE THREAD

**Issue by dustinwilson** [rg3/youtube-dl#7095]
When trying to download http://www.pbs.org/wgbh/nova/tech/making-stuff.html#making-stuff-stronger I get an error. Here's the debug output:

```
--verbose http://www.pbs.org/wgbh/nova/tech/making-stuff.html#making-stuff-stronger
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.pbs.org/wgbh/nova/tech/making-stuff.html#making-stuff-stronger']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.10.06.2
[debug] Python version 2.7.10 - Darwin-14.5.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.8, ffprobe 2.8, rtmpdump 2.4
[debug] Proxy map: {}
[PBS] making-stuff: Downloading webpage
[PBS] making-stuff: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 404: NOT FOUND (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 329, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1872, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 469, in error
    result = self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 656, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
```

**Comment by Bandicoot** [comment]
Similar error, same end result (no d/l) with youtube-dl version 2015.11.18

bandy@bandy-dell-mint ~/Videos $ youtube-dl --verbose -c 'http://video.pbs.org/video/2365607500'
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'-c', u'http://video.pbs.org/video/2365607500']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.18
[debug] Python version 2.7.6 - Linux-3.13.0-37-generic-x86_64-with-LinuxMint-17.1-rebecca
[debug] exe versions: avconv 9.18-6, avprobe 9.18-6
[debug] Proxy map: {}
[PBS] 2365607500: Downloading JSON metadata
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 661, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/pbs.py", line 301, in _real_extract
    self._sort_formats(formats)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 766, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

bandy@bandy-dell-mint ~/Videos $

**Comment by dstftw** [comment]
@Bandicoot your issue is unrelated. You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.

**Comment by sydlexius** [comment]
Recently I had no issues with PBS, but I'm now getting the following error:
```
D:\Downloads\Finished\TV>youtube-dl http://www.pbs.org/video/2365659907/ -F --verbose > error.txt
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://www.pbs.org/video/2365659907/', u'-F', u'--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out None, pref cp1252
[debug] youtube-dl version 2016.02.05.1
[debug] Python version 2.7.11 - Windows-10-10.0.11102
[debug] exe versions: ffmpeg N-78313-g6632802, ffprobe N-78313-g6632802
[debug] Proxy map: {}
ERROR: Unable to download JSON metadata: HTTP Error 404: NOT FOUND (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "c:\python27\lib\site-packages\youtube_dl\extractor\common.py", line 352, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "c:\python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 1903, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "c:\python27\lib\urllib2.py", line 437, in open
    response = meth(req, response)
  File "c:\python27\lib\urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\python27\lib\urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "c:\python27\lib\urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "c:\python27\lib\urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
```

**Comment by chkuendig** [comment]
FYI: had the same issue with PBS since a few days, but after updating from 2016.01.01 to 2016.02.10 it works again.

**Comment by anarcat** [comment]
same failure here, tried 2016.06.25-2~bpo8 from debian backports, 2016.11.08.1 from git, and the latest standalone package from today.

**Comment by 89z** [comment]
Looks like that video is not available any more, only the preview:

https://pbs.org/video/nova-making-stuff-stronger-1
