### ISSUE TITLE
BBC website no longer working

### ISSUE THREAD

**Issue by h633537** [rg3/youtube-dl#7104]
```
$ youtube-dl http://www.bbc.co.uk/news/world-us-canada-34473351 --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://www.bbc.co.uk/news/world-us-canada-34473351', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.10.06.2
[debug] Python version 2.7.10 - Linux-4.1.8-200.fc22.x86_64-x86_64-with-fedora-22-Twenty_Two
[debug] exe versions: ffmpeg 2.6.4, ffprobe 2.6.4, rtmpdump 2.4
[debug] Proxy map: {}
[bbc] world-us-canada-34473351: Downloading webpage
ERROR: Unable to extract playlist data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 660, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/bbc.py", line 750, in _real_extract
    webpage, 'playlist data'),
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 584, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract playlist data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by dstftw** [comment]
This issue has been fixed and will be available in the next version.
