### ISSUE TITLE
Vine OpenGraph error

### ISSUE THREAD

**Issue by simplify3** [rg3/youtube-dl#7108]
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-k', u'https://vine.co/v/e0qEd1qqmOd', u'--verbose
']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.10.06.2
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[Vine] e0qEd1qqmOd: Downloading webpage
ERROR: Unable to extract OpenGraph title; please report this issue on https://yt
-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  t
o update. Be sure to call youtube-dl with the --verbose flag and include its com
plete output.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 660, in extract_info
  File "youtube_dl\extractor\common.pyo", line 290, in extract
  File "youtube_dl\extractor\vine.pyo", line 77, in _real_extract
  File "youtube_dl\extractor\common.pyo", line 677, in _og_search_title
  File "youtube_dl\extractor\common.pyo", line 665, in _og_search_property
  File "youtube_dl\extractor\common.pyo", line 584, in _search_regex
RegexNotFoundError: Unable to extract OpenGraph title; please report this issue
on https://yt-dl.org/bug . Make sure you are using the latest version; type  you
tube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and in
clude its complete output.

**Comment by yan12125** [comment]
Thanks for the report. This will be fixed in the next version.
