### ISSUE TITLE
HTTPError: HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by vidhan13j07** [rg3/youtube-dl#7119]
$ youtube-dl https://www.youtube.com//watch?v=naKhF6G36rM -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'https://www.youtube.com//watch?v=naKhF6G36rM', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.10.09
[debug] Python version 2.7.10 - Linux-4.1.8-200.fc22.x86_64-x86_64-with-fedora-22-Twenty_Two
[debug] exe versions: none
[debug] Proxy map: {}
[generic] watch?v=naKhF6G36rM: Requesting header
WARNING: Falling back on generic information extractor.
[generic] watch?v=naKhF6G36rM: Downloading webpage
[generic] watch?v=naKhF6G36rM: Extracting information
[debug] Invoking downloader on u'https://www.youtube.com//\\/\\/www.youtube.com\\/annotations_invideo?cap_hist=1\\u0026video_id=naKhF6G36rM'
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1597, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1539, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 342, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 60, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1872, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found

**Comment by yan12125** [comment]
There's an extra slash '/'. The following command works:
```
youtube-dl "https://www.youtube.com/watch?v=naKhF6G36rM" -v
```
