### ISSUE TITLE
Failing on dailymotion video

### ISSUE THREAD

**Issue by uberscientist** [rg3/youtube-dl#7129]
Here's the full output:
```
$ youtube-dl --verbose http://www.dailymotion.com/video/x397k4q
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.dailymotion.com/video/x397k4q']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.09.28
[debug] Python version 3.5.0 - Linux-4.2.2-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 2.8, ffprobe 2.8, rtmpdump 2.4
[debug] Proxy map: {}
[dailymotion] x397k4q: Downloading webpage
[dailymotion] x397k4q: Downloading embed page
ERROR: Unable to extract video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 660, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 288, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/dailymotion.py", line 201, in _real_extract
    'video info', flags=re.MULTILINE),
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 582, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
Running from Arch linux latest package version 2015.09.28

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.
