### ISSUE TITLE
'list' object has no attribute 'get'

### ISSUE THREAD

**Issue by anxst** [rg3/youtube-dl#7152]
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'https://vimeo.com/141298620', u'--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.10.12
[debug] Python version 2.7.8 - Windows-8-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {}
[vimeo] Logging in
[vimeo] 141298620: Downloading webpage
[vimeo] 141298620: Extracting information
[vimeo] 141298620: Downloading webpage
[vimeo] 141298620: Downloading m3u8 information
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "youtube_dl\__init__.pyo", line 410, in main
  File "youtube_dl\__init__.pyo", line 400, in _real_main
  File "youtube_dl\YoutubeDL.pyo", line 1665, in download
  File "youtube_dl\YoutubeDL.pyo", line 660, in extract_info
  File "youtube_dl\extractor\common.pyo", line 290, in extract
  File "youtube_dl\extractor\vimeo.pyo", line 412, in _real_extract
  File "youtube_dl\extractor\common.pyo", line 824, in _sort_formats
  File "youtube_dl\extractor\common.pyo", line 770, in _formats_key
AttributeError: 'list' object has no attribute 'get'

**Comment by jaimeMF** [comment]
It's [already fixed in the repo](73e732eb6b5fb2edd61701ae110cc52fe6836364), please wait for the next release.

**Comment by anxst** [comment]
That was why I couldn't find what would have thrown that issue when I looked at the source in the repo.

Thanks!
