### ISSUE TITLE
Site Request Stitcher

### ISSUE THREAD

**Issue by canamcy** [rg3/youtube-dl#7162]
http://www.stitcher.com/podcast/the-talking-machines/e/40789481?autoplay=true

**Comment by canamcy** [comment]
[generic] 40789481?autoplay=true: Requesting header
[generic] 40789481?autoplay=true: Downloading webpage
[generic] 40789481?autoplay=true: Extracting information

[generic] 40789481?autoplay=true: Requesting header
[generic] 40789481?autoplay=true: Downloading webpage
[generic] 40789481?autoplay=true: Extracting information
[Error] ytdl for => [debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-f', u'worst', u'-i', u'--verbose', u'--restrict-f
ilenames', u'--youtube-skip-dash-manifest', u'-o', u'..\\..\\..\\yo0\\M\\yodl\\y
outube-dl\\%(extractor)s\\%(title)s-%(id)s.%(ext)s', u'--', u'http://www.stitche
r.com/podcast/the-talking-machines/e/40789481?autoplay=true']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.10.13
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-56800-gad8fbdd, ffprobe N-56800-gad8fbdd
[debug] Proxy map: {}
WARNING: Falling back on generic information extractor.
ERROR: Unsupported URL: http://www.stitcher.com/podcast/the-talking-machines/e/4
0789481?autoplay=true
Traceback (most recent call last):
  File "youtube_dl\extractor\generic.pyo", line 1240, in _real_extract
  File "youtube_dl\utils.pyo", line 1656, in parse_xml
  File "xml\etree\ElementTree.pyo", line 1300, in XML
  File "xml\etree\ElementTree.pyo", line 1642, in feed
  File "xml\etree\ElementTree.pyo", line 1506, in _raiseerror
ParseError: not well-formed (invalid token): line 4, column 407
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 660, in extract_info
  File "youtube_dl\extractor\common.pyo", line 290, in extract
  File "youtube_dl\extractor\generic.pyo", line 1838, in _real_extract
UnsupportedError: Unsupported URL: http://www.stitcher.com/podcast/the-talking-m
achines/e/40789481?autoplay=true

**Comment by mjdubell** [comment]
Added support here #7228

**Comment by canamcy** [comment]
The test url and the following still works in my Chrome browser.(py version is actually 3.2)

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-f', u'worst', u'-i', u'--verbose', u'--restrict-f
ilenames', u'--youtube-skip-dash-manifest', u'-o', u'..\\..\\..\\yo0\\M\\yodl\\y
outube-dl\\%(extractor)s\\%(title)s-%(id)s.%(ext)s', u'--', u'http://www.stitche
r.com/podcast/this-week-in-tech/e/40891040?autoplay=true']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.10.24
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-56800-gad8fbdd, ffprobe N-56800-gad8fbdd
[debug] Proxy map: {}
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 1598, in process_info
  File "youtube_dl\YoutubeDL.pyo", line 1540, in dl
  File "youtube_dl\downloader\common.pyo", line 342, in download
  File "youtube_dl\downloader\http.pyo", line 60, in real_download
  File "youtube_dl\YoutubeDL.pyo", line 1873, in urlopen
  File "urllib2.pyo", line 437, in open
  File "urllib2.pyo", line 550, in http_response
  File "urllib2.pyo", line 475, in error
  File "urllib2.pyo", line 409, in _call_chain
  File "urllib2.pyo", line 558, in http_error_default
HTTPError: HTTP Error 404: Not Found

**Comment by dstftw** [comment]
@canamcy will be fixed in the next version. To get it work now you can remove `-f worst` from command line. Next time open a new issue.

**Comment by canamcy** [comment]
Thank you. Will do.

**Comment by Wurzelmann** [comment]
Hm, Stitcher seems to be broken again:

    youtube-dl -f worst https://www.stitcher.com/podcast/stitcher/unladylike
    [generic] unladylike: Requesting header
    WARNING: Falling back on generic information extractor.
    [generic] unladylike: Downloading webpage
    [generic] unladylike: Extracting information
    ERROR: Unsupported URL: https://www.stitcher.com/podcast/stitcher/unladylike

**Comment by luckysevenserver** [comment]
I'm in the same boat as @Wurzelmann 

Seems that Stitcher seems to be broken again as I am getting an unsupported URL error when trying to download a podcast.
