### ISSUE TITLE
youtube download doesnt work

### ISSUE THREAD

**Issue by peterlazar1993** [rg3/youtube-dl#7172]
youtube-dl -v https://www.youtube.com/watch?v=x7cQ3mrcKaY
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=x7cQ3mrcKaY']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.10.13
[debug] Git HEAD: ee13a27
[debug] Python version 2.7.10 - Darwin-15.0.0-x86_64-i386-64bit
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/youtube_dl/__init__.py", line 410, in main
    _real_main(argv)
  File "/usr/local/lib/python2.7/site-packages/youtube_dl/__init__.py", line 377, in _real_main
    with YoutubeDL(ydl_opts) as ydl:
  File "/usr/local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 340, in __init__
    self.print_debug_header()
  File "/usr/local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 1911, in print_debug_header
    exe_versions = FFmpegPostProcessor.get_versions(self)
  File "/usr/local/lib/python2.7/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 51, in get_versions
    return FFmpegPostProcessor(downloader)._versions
  File "/usr/local/lib/python2.7/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 35, in __init__
    self._determine_executables()
  File "/usr/local/lib/python2.7/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 91, in _determine_executables
    (p, get_exe_version(p, args=['-version'])) for p in programs)
  File "/usr/local/lib/python2.7/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 91, in <genexpr>
    (p, get_exe_version(p, args=['-version'])) for p in programs)
  File "/usr/local/lib/python2.7/site-packages/youtube_dl/utils.py", line 1471, in get_exe_version
    stdout=subprocess.PIPE, stderr=subprocess.STDOUT).communicate()
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1334, in _execute_child
    child_exception = pickle.loads(data)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 1382, in loads
    return Unpickler(file).load()
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 966, in load_string
    raise ValueError, "insecure string pickle"
ValueError: insecure string pickle

**Comment by dstftw** [comment]
See #6840.

**Comment by peterlazar1993** [comment]
@dstftw thank you :)

**Comment by dstftw** [comment]
Close the issue if that solved your problem.

**Comment by richiecannizzo** [comment]
brew install libav

**Comment by richiecannizzo** [comment]
brew install libav
Should fix it instantly on mac or 

sudo apt-get install libav 
#on linux
