### ISSUE TITLE
Can't download untitled video from jeuxvideo.com (object of type 'NoneType' has no len())

### ISSUE THREAD

**Issue by lucascharrierpulpix** [rg3/youtube-dl#7186]
Hi, Trying to download a video on jeuxvideo.com using  "youtube-dl -j http://www.jeuxvideo.com/test/446182/dragon-ball-z-extreme-butoden-peut-mieux-faire.htm --verbose" I get the following output (I guess the problem is, the video has no title):

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-j', u'http://www.jeuxvideo.com/test/446182/dragon-ball-z-extreme-butoden-peut-mieux-faire.htm', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.10.13
[debug] Git HEAD: d984b82
[debug] Python version 2.7.6 - Darwin-14.3.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.7.1, ffprobe 2.7.1
[debug] Proxy map: {}
WARNING: unable to extract name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/Users/admin/Documents/hec/venv/bin/youtube-dl", line 11, in <module>
    sys.exit(main())
  File "/Users/admin/Documents/hec/venv/lib/python2.7/site-packages/youtube_dl/__init__.py", line 410, in main
    _real_main(argv)
  File "/Users/admin/Documents/hec/venv/lib/python2.7/site-packages/youtube_dl/__init__.py", line 400, in _real_main
    retcode = ydl.download(all_urls)
  File "/Users/admin/Documents/hec/venv/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 1665, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/Users/admin/Documents/hec/venv/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 671, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/Users/admin/Documents/hec/venv/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 717, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/Users/admin/Documents/hec/venv/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 1335, in process_video_result
    self.process_info(new_info)
  File "/Users/admin/Documents/hec/venv/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 1400, in process_info
    if len(info_dict['title']) > 200:

**Comment by keepreason** [comment]
You may also try this method to solve can't download untitled video from jeuxvideo.com issue: http://www.allavsoft.com/how-to/download-jeuxvideo-videos.html
