### ISSUE TITLE
Twitter's smarturl - download video error

### ISSUE THREAD

**Issue by MaryCoding** [rg3/youtube-dl#7191]
Hi i am currently trying to download video from twitter's smarturl. However, I am getting an error on download. The page does offer metadata. Link to video: https://amp.twimg.com/v/ec53d188-afdf-48db-a230-73dd113d49f8

```
[debug] System config: [u'--ffmpeg-location', u'/home/user/bin/ffmpeg']
[debug] User config: []
[debug] Command-line args: [u'-v', u'--no-warnings', u'-o', u'/media/%(title)s.%(ext)s', u'https://amp.twimg.com/v                                                                                                                     /ec53d188-afdf-48db-a230-73dd113d49f8']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.10.09
[debug] Python version 2.7.9 - Linux-3.19.0-30-generic-x86_64-with-Ubuntu-15.04-                                                                                                                     vivid
[debug] exe versions: ffmpeg 2.6.git, ffprobe 2.6.git, rtmpdump 2.4
[debug] Proxy map: {}
[generic] ec53d188-afdf-48db-a230-73dd113d49f8: Requesting header
[generic] ec53d188-afdf-48db-a230-73dd113d49f8: Downloading webpage
[generic] ec53d188-afdf-48db-a230-73dd113d49f8: Extracting information
ERROR: Unsupported URL: https://amp.twimg.com/v/ec53d188-afdf-48db-a230-73dd113d                                                                                                                     49f8
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1240, i                                                                                                                     n _real_extract
    doc = parse_xml(webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1656, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: mismatched tag: line 30, column 4
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 660, in extract                                                                                                                     _info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 290, in                                                                                                                      extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1838, i                                                                                                                     n _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://amp.twimg.com/v/ec53d188-afdf-48db-a2                                                                                                                     30-73dd113d49f8


``

**Comment by jaimeMF** [comment]
Thanks to @atomicdryad (#6322) on the git repo the original tweet url https://twitter.com/ddlovato/status/653237587545448452 is supported. Although you url is the orignal tweet page I haven't been able to get it through their interface, is that enough or do you really need support for this url?

**Comment by MaryCoding** [comment]
Hi @jaimeMF ! I personally dont mind. I tried it with the original url and still got an error: 
```
youtube-dl -v --no-warnings -o "/media/sf_linux_sandbox/hashtag_pull/video-downloads/%(title)s.%(ext)s" " https://twitter.com/ddlovato/status/653237587545448452"
[debug] System config: [u'--ffmpeg-location', u'/home/bullseye2346/bin/ffmpeg']
[debug] User config: []
[debug] Command-line args: [u'-v', u'--no-warnings', u'-o', u'/media/%(title)s.%(ext)s', u' https://twitter.com/ddlovato/status/653237587545448452']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.10.09
[debug] Python version 2.7.9 - Linux-3.19.0-30-generic-x86_64-with-Ubuntu-15.04-vivid
[debug] exe versions: ffmpeg 2.6.git, ffprobe 2.6.git, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 653237587545448452: Requesting header
[generic] 653237587545448452: Downloading webpage
[generic] 653237587545448452: Extracting information
[redirect] Following redirect to https://mobile.twitter.com/i/nojs_router?path=/ddlovato/status/653237587545448452
[generic] 653237587545448452: Requesting header
[redirect] Following redirect to https://mobile.twitter.com/ddlovato/status/653237587545448452
[generic] 653237587545448452: Requesting header
[generic] 653237587545448452: Downloading webpage
[generic] 653237587545448452: Extracting information
ERROR: Unsupported URL: https://mobile.twitter.com/ddlovato/status/653237587545448452
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1240, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1656, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: mismatched tag: line 15, column 4
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 660, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1838, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://mobile.twitter.com/ddlovato/status/653237587545448452
```

**Comment by yan12125** [comment]
FYI: Twitter is supported since version 2015.10.18.

**Comment by MaryCoding** [comment]
@yan12125 perfect, It is working. Thanks.
