### ISSUE TITLE
Crunchyroll:playlist  Ladies Versus Butlers ERROR: Unable to extract title

### ISSUE THREAD

**Issue by almostalive** [rg3/youtube-dl#7202]
youtube-dl is unable to use crunchyroll:playlist for http://www.crunchyroll.com/ladies-versus-butlers . Individual episodes work fine though. Premium and mature content only, so that might be causing the problem since you have to login to view the page in the browser. This is using current version (2015.10.16) on Arch Linux x86_64.

```
youtube-dl --verbose 'http://www.crunchyroll.com/ladies-versus-butlers'
[debug] System config: []
[debug] User config: ['--netrc']
[debug] Command-line args: ['--verbose', 'http://www.crunchyroll.com/ladies-versus-butlers']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.10.16
[debug] Python version 3.5.0 - Linux-4.1.10-3-ck-x86_64-with-arch
[debug] exe versions: ffmpeg 2.8.1, ffprobe 2.8.1, rtmpdump 2.4
[debug] Proxy map: {}
[crunchyroll:playlist] ladies-versus-butlers: Downloading webpage
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 660, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/crunchyroll.py", line 372, in _real_extract
    webpage, 'title')
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 593, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 584, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

```
youtube-dl 'http://www.crunchyroll.com/ladies-versus-butlers/episode-1-boy-versus-lady-686995' -v
[debug] System config: []
[debug] User config: ['--netrc']
[debug] Command-line args: ['http://www.crunchyroll.com/ladies-versus-butlers/episode-1-boy-versus-lady-686995', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.10.16
[debug] Python version 3.5.0 - Linux-4.1.10-3-ck-x86_64-with-arch
[debug] exe versions: ffmpeg 2.8.1, ffprobe 2.8.1, rtmpdump 2.4
[debug] Proxy map: {}
[Crunchyroll] Logging in
[Crunchyroll] 686995: Downloading webpage
[Crunchyroll] 686995: Downloading media info
[Crunchyroll] 686995: Downloading media info for 360p
[Crunchyroll] 686995: Checking 360p URL
[Crunchyroll] 686995: Downloading media info for 480p
[Crunchyroll] 686995: Checking 480p URL
[Crunchyroll] 686995: Downloading media info for 720p
[Crunchyroll] 686995: Checking 720p URL
[Crunchyroll] 686995: Downloading media info for 1080p
[Crunchyroll] 686995: Checking 1080p URL
[debug] Invoking downloader on 'http://v.lvlt.crcdn.net/c17/s/ve1994497/video.mp4?nvb=20151017001418&nva=20151017041518&token=04f44bb9634dd2f0973c6'
[download] Destination: Ladies Versus Butlers (Dub) Episode 1 – Boy versus Lady-686995.mp4
[download] 100% of 565.47MiB in 01:34
```

**Comment by dstftw** [comment]
What are the restricted countries?

**Comment by almostalive** [comment]
United States and Canada.

Looking at crunchyroll.py, it seems like to me that crunchroll:playlist doesn't do any logging in when it tries to look up the information so it is unable to get pass the screen asking you to login.

**Comment by almostalive** [comment]
After looking at this a bit more, I notice that anime marked as mature/inappropriate content does not show up in the anime listings when you are not logged in, they only show up after you login and have Show Mature Content set in Video Preferences (which is default I think). 

I also notice the change in url when clicking a direct link to one of these shows.
 http://www.crunchyroll.com/ladies-versus-butlers
changes to
http://www.crunchyroll.com/maturity_wall?next=%2Fladies-versus-butlers%3Fskip_wall%3D1

The individual episodes of course only work when providing the account credentials. So maybe some kind of check in crunchyroll:playlist and the passing of account credentials would probably fix the problem, though I have no clue if that would be easy or not.
