### ISSUE TITLE
RegexNotFoundError when fetching a Dailymotion URL

### ISSUE THREAD

**Issue by danielquinn** [rg3/youtube-dl#7205]
```
$ youtube-dl --verbose http://www.dailymotion.com/video/x20su5f_the-power-of-nightmares-1-the-rise-of-the-politics-of-fear-bbc-2004_news
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.dailymotion.com/video/x20su5f_the-power-of-nightmares-1-the-rise-of-the-politics-of-fear-bbc-2004_news']
WARNING: No ssl certificates were loaded, urls that use https won't work
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.04.03
[debug] Python version 2.7.9 - Linux-3.14.14-gentoo-x86_64-Intel-R-_Celeron-R-_CPU_N2820_@_2.13GHz-with-gentoo-2.2
[debug] exe versions: none
[debug] Proxy map: {}
[dailymotion] x20su5f: Downloading webpage
[dailymotion] x20su5f: Extracting information
[dailymotion] x20su5f: Downloading embed page
ERROR: Unable to extract video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 651, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/common.py", line 275, in extract
    return self._real_extract(url)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/dailymotion.py", line 118, in _real_extract
    'video info', flags=re.MULTILINE)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/common.py", line 547, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.
