### ISSUE TITLE
imdb: UnboundLocalError: local variable 'format_info' referenced before assignment

### ISSUE THREAD

**Issue by kaefert** [rg3/youtube-dl#7220]
I can't download imdb trailers with the latest version 2015.10.16 - I do believe to remember that this was possible with older versions

```
$ youtube-dl "http://www.imdb.com/video/imdb/vi343846681/?ref_=tt_ov_vi" -F --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://www.imdb.com/video/imdb/vi343846681/?ref_=tt_ov_vi', u'-F', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.10.16
[debug] Python version 2.7.6 - Linux-3.13.0-41-generic-x86_64-with-LinuxMint-17.2-rafaela
[debug] exe versions: ffmpeg N-69446-g2a3b7a5, ffprobe N-69446-g2a3b7a5, rtmpdump 2.4
[debug] Proxy map: {}
[imdb] 343846681: Downloading webpage
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/kaefert/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/home/kaefert/bin/youtube-dl/youtube_dl/__init__.py", line 410, in main
  File "/home/kaefert/bin/youtube-dl/youtube_dl/__init__.py", line 400, in _real_main
  File "/home/kaefert/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1665, in download
  File "/home/kaefert/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 660, in extract_info
  File "/home/kaefert/bin/youtube-dl/youtube_dl/extractor/common.py", line 290, in extract
  File "/home/kaefert/bin/youtube-dl/youtube_dl/extractor/imdb.py", line 57, in _real_extract
UnboundLocalError: local variable 'format_info' referenced before assignment
```

**Comment by jaimeMF** [comment]
Thanks for the report, it will work again in the next version.
