### ISSUE TITLE
tvfplay.com isn't supported can you please add it

### ISSUE THREAD

**Issue by surajgupta1489** [rg3/youtube-dl#7224]
youtube-dl http://tvfplay.com/video/detail/477/TVF-Pitchers-S01E05-Where-Magic-Happens --verbose 
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://tvfplay.com/video/detail/477/TVF-Pitchers-S01E05-Where-Magic-Happens', '--verbose']
[debug] Encodings: locale 'UTF-8', fs 'UTF-8', out 'UTF-8', pref: 'UTF-8'
[debug] youtube-dl version 2014.02.17
[debug] Python version 2.7.6 - Linux-3.16.0-50-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] Proxy map: {}
[generic] TVF-Pitchers-S01E05-Where-Magic-Happens: Requesting header
WARNING: Falling back on generic information extractor.
[generic] TVF-Pitchers-S01E05-Where-Magic-Happens: Downloading webpage
[generic] TVF-Pitchers-S01E05-Where-Magic-Happens: Extracting information
ERROR: Unsupported URL: http://tvfplay.com/video/detail/477/TVF-Pitchers-S01E05-Where-Magic-Happens; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 493, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 158, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 380, in _real_extract
    raise ExtractorError('Unsupported URL: %s' % url)
ExtractorError: Unsupported URL: http://tvfplay.com/video/detail/477/TVF-Pitchers-S01E05-Where-Magic-Happens; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by shahankit** [comment]
@remitamine  Any google account would work.

**Comment by dufferzafar** [comment]
9xbuddy.com is a site that can provide direct mp4 links to videos on TVFPlay.

**Comment by alpeshvalia** [comment]
I am working on adding support tvfplay.com. Can someone assign me this issue?

**Comment by Ashish0804** [comment]
Any update? U just need to login with any google account

**Comment by adi928** [comment]
> Any update? U just need to login with any google account

The 'need-account' tag means one needs to pay for the subscription (after logging into an account). Can't view anything with just an account.
