### ISSUE TITLE
While downloading a bandcamp album: ValueError: unknown url type: //popplers...

### ISSUE THREAD

**Issue by topotech** [rg3/youtube-dl#7229]
Basically this is a reproduction of the issue  #4861 with the 2015.10.09 version when I try to download the album
http://tenemosexplosivosoficial.bandcamp.com/album/la-virgen-de-los-mataderos

Weird enough, the program seems to get the stream URL, but it isn't recognized as a proper URL.

Here is the complete trace:

```
[foo@bar yt]$ youtube-dl --verbose http://tenemosexplosivosoficial.bandcamp.com/album/la-virgen-de-los-mataderos
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://tenemosexplosivosoficial.bandcamp.com/album/la-virgen-de-los-mataderos']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.10.09
[debug] Python version 2.7.8 - Linux-4.1.8-100.fc21.i686-i686-with-fedora-21-Twenty_One
[debug] exe versions: ffmpeg 2.4.11, ffprobe 2.4.11
[debug] Proxy map: {}
[Bandcamp:album] la-virgen-de-los-mataderos: Downloading webpage
[download] Downloading playlist: La Virgen de los Mataderos
[Bandcamp:album] playlist La Virgen de los Mataderos: Collected 12 video ids (downloading 12 of them)
[download] Downloading video 1 of 12
[Bandcamp] violencia-y-jerarqu-a: Downloading webpage
[debug] Invoking downloader on u'//popplers5.bandcamp.com/download/track?enc=mp3-128&fsig=aa7e2246c88cd7426c386f28da4c9bf8&id=1308195415&stream=1&ts=1443681396.0'
Traceback (most recent call last):
  File "/usr/bin/youtube-dl", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/youtube_dl/__init__.py", line 410, in main
    _real_main(argv)
  File "/usr/lib/python2.7/site-packages/youtube_dl/__init__.py", line 400, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 1665, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 671, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 832, in process_ie_result
    extra_info=extra)
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 724, in process_ie_result
    extra_info=extra_info)
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 671, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 717, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 1335, in process_video_result
    self.process_info(new_info)
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 1597, in process_info
    success = dl(filename, info_dict)
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 1539, in dl
    return fd.download(name, info)
  File "/usr/lib/python2.7/site-packages/youtube_dl/downloader/common.py", line 342, in download
    return self.real_download(filename, info_dict)
  File "/usr/lib/python2.7/site-packages/youtube_dl/downloader/http.py", line 60, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 1872, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 396, in open
    protocol = req.get_type()
  File "/usr/lib/python2.7/urllib2.py", line 258, in get_type
    raise ValueError, "unknown url type: %s" % self.__original
ValueError: unknown url type: //popplers5.bandcamp.com/download/track?enc=mp3-128&fsig=aa7e2246c88cd7426c386f28da4c9bf8&id=1308195415&stream=1&ts=1443681396.0
``

**Comment by yan12125** [comment]
Version 2015.10.18 works for me. Could you try?

**Comment by topotech** [comment]
Like a charm. I didn't knew there was 10.18 version. If I ever have a problem again I'll try to force upgrade first. Thank you.

**Comment by yan12125** [comment]
OK. Feel free to open a new issue if there are other problems.
