### ISSUE TITLE
Failed to parse JSON

### ISSUE THREAD

**Issue by hynek-jemelik** [rg3/youtube-dl#7254]
unable to download https://vine.co/v/OFjZI9KY1ge

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'--list-formats', u'https://vine.co/v/OFjZI9KY1ge', u'--write-pages', u'--print-traffic']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.10.18
[debug] Git HEAD: 7308b8c
[debug] Python version 2.7.9 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.2
[debug] exe versions: none
[debug] Proxy map: {}
[Vine] OFjZI9KY1ge: Downloading webpage
send: u'GET /v/OFjZI9KY1ge HTTP/1.1\r\nAccept-Language: en-us,en;q=0.5\r\nAccept-Encoding: gzip, deflate\r\nConnection: close\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nUser-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/20.0 (Chrome)\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nHost: vine.co\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Accept-Ranges: bytes
header: Cache-Control: max-age=1800
header: Content-Encoding: gzip
header: Content-Security-Policy: default-src https: data: vine:;img-src 'self' data: https://vine.co https://vines.s3.amazonaws.com https://*.cdn.vine.co https://media.vineapp.com https://t.co https://analytics.twitter.com https://ssl.google-analytics.com https://stats.g.doubleclick.net;script-src 'self' 'unsafe-inline' 'unsafe-eval' https://vine.co https://*.twitter.com https://vines.s3.amazonaws.com https://*.cdn.vine.co https://platform.vine.co https://stats.g.doubleclick.net https://ssl.google-analytics.com https://ajax.googleapis.com https://connect.facebook.net;style-src 'self' 'unsafe-inline' https://vine.co https://vines.s3.amazonaws.com https://*.cdn.vine.co;media-src 'self' blob: https://vine.co https://vines.s3.amazonaws.com https://*.cdn.vine.co https://*.vncdn.co https://media.vineapp.com;object-src 'self' blob: https://vine.co https://vine.co https://vines.s3.amazonaws.com https://*.cdn.vine.co https://media.vineapp.com;connect-src 'self' https://vine.co https://vines.s3.amazonaws.com https://*.cdn.vine.co https://media.vineapp.com https://graph.facebook.com;font-src 'self' https://vine.co https://vines.s3.amazonaws.com https://*.cdn.vine.co;report-uri https://twitter.com/i/csp_report?a=OZUW4ZI=&ro=false
header: Content-Type: text/html; charset=utf-8
header: Date: Wed, 21 Oct 2015 08:16:10 GMT
header: Strict-Transport-Security: max-age=631138519
header: X-Content-Type-Options: nosniff
header: X-Frame-Options: SAMEORIGIN
header: X-XSS-Protection: 1; mode=block
header: Content-Length: 5905
header: Connection: Close
[Vine] Saving request to OFjZI9KY1ge_https_-_vine.co_v_OFjZI9KY1ge.dump
ERROR: OFjZI9KY1ge: Failed to parse JSON  (caused by ValueError("Expecting ',' delimiter: line 1 column 2387 (char 2386)",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dl/extractor/common.py", line 484, in _parse_json
    return json.loads(json_string)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting ',' delimiter: line 1 column 2387 (char 2386)
Traceback (most recent call last):
  File "youtube_dl/YoutubeDL.py", line 661, in extract_info
    ie_result = ie.extract(url)
  File "youtube_dl/extractor/common.py", line 291, in extract
    return self._real_extract(url)
  File "youtube_dl/extractor/vine.py", line 91, in _real_extract
    video_id)
  File "youtube_dl/extractor/common.py", line 488, in _parse_json
    raise ExtractorError(errmsg, cause=ve)
ExtractorError: OFjZI9KY1ge: Failed to parse JSON  (caused by ValueError("Expecting ',' delimiter: line 1 column 2387 (char 2386)",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by hynek-jemelik** [comment]
Proposed fix is in https://github.com/rg3/youtube-dl/pull/7255
