### ISSUE TITLE
ServusTV brightcove issue

### ISSUE THREAD

**Issue by z1atk0** [rg3/youtube-dl#7256]
[thomas@wasser:~]$ python --version
Python 2.7.10
[thomas@wasser:~]$ youtube-dl --version
2015.10.09
[thomas@wasser:~]$ youtube-dl -v -F "http://www.servustv.com/at/Medien/Wer-hat-Angst-vor-dem-Weissen-Hai"
[debug] System config: [u'--prefer-free-formats']
[debug] User config: []
[debug] Command-line args: [u'-v', u'-F', u'http://www.servustv.com/at/Medien/Wer-hat-Angst-vor-dem-Weissen-Hai']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.10.09
[debug] Python version 2.7.10 - Linux-4.2.3-200.fc22.x86_64-x86_64-with-fedora-22-Twenty_Two
[debug] exe versions: ffmpeg 2.6.4, ffprobe 2.6.4
[debug] Proxy map: {}
[generic] Wer-hat-Angst-vor-dem-Weissen-Hai: Requesting header
WARNING: Falling back on generic information extractor.
[generic] Wer-hat-Angst-vor-dem-Weissen-Hai: Downloading webpage
[generic] Wer-hat-Angst-vor-dem-Weissen-Hai: Extracting information
[generic] Brightcove video detected.
[download] Downloading playlist: Wer hat Angst vor dem Weißen Hai? bei ServusTV
[generic] playlist Wer hat Angst vor dem Weißen Hai? bei ServusTV: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[Brightcove] 4566226660001: Downloading webpage
[Brightcove] 4566226660001: Extracting information
Traceback (most recent call last):
  File "/usr/bin/youtube-dl", line 9, in <module>
    load_entry_point('youtube-dl==2015.10.9', 'console_scripts', 'youtube-dl')()
  File "/usr/lib/python2.7/site-packages/youtube_dl/__init__.py", line 410, in main
    _real_main(argv)
  File "/usr/lib/python2.7/site-packages/youtube_dl/__init__.py", line 400, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 1665, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 671, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 832, in process_ie_result
    extra_info=extra)
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 724, in process_ie_result
    extra_info=extra_info)
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 660, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/brightcove.py", line 237, in _real_extract
    videoPlayer[0], query_str, query, referer=referer)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/brightcove.py", line 267, in _get_video_info
    video_info['_youtubedl_adServerURL'] = info.get('adServerURL')
TypeError: 'NoneType' object does not support item assignment

Different box with youtube-dl 2015.10.18 and Python 2.7.3 shows the same problem.

**Comment by z1atk0** [comment]
Feel free to close this one - the example video is no longer available, and newer ones actually work (again?), so the issue seems to have been fixed in the latest version, or the problem has somehow disappeared by itself ...
