### ISSUE TITLE
Unable to download Facebook videos

### ISSUE THREAD

**Issue by dbinoj** [rg3/youtube-dl#7264]
URL which failed: https://www.facebook.com/jerseydemic/videos/10153749930515681/
youtube-dl version: 2015.10.18
Output:
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'https://www.facebook.com/jerseydemic/videos/10153749930515681/', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.10.18
[debug] Python version 2.7.6 - Linux-3.13.0-65-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: ffmpeg 1.2.6-7, ffprobe 1.2.6-7, rtmpdump 2.4
[debug] Proxy map: {}
[facebook] 10153749930515681: Downloading webpage
ERROR: An extractor error has occured. (caused by KeyError(0,)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 291, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/facebook.py", line 145, in _real_extract
    video_data = params['video_data'][0]
KeyError: 0
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 661, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 297, in extract
    raise ExtractorError('An extractor error has occured.', cause=e)
ExtractorError: An extractor error has occured. (caused by KeyError(0,)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by yan12125** [comment]
It's fixed in Git but not included in the latest release yet. Please wait patiently for the next version.
