### ISSUE TITLE
Version 2015.10.23 windows version (MemoryLoadLibrary failed loading _ssl.pyd)

### ISSUE THREAD

**Issue by fullcontroll** [rg3/youtube-dl#7276]
= Version 2015.10.23 =

C:\dev\bin>"youtube-dl.exe"
Traceback (most recent call last):
  File "__main__.py", line 16, in <module>
  File "zipextimporter.pyo", line 82, in load_module
  File "youtube_dl\__init__.pyo", line 15, in <module>
  File "zipextimporter.pyo", line 82, in load_module
  File "youtube_dl\options.pyo", line 7, in <module>
  File "zipextimporter.pyo", line 82, in load_module
  File "youtube_dl\downloader\__init__.pyo", line 3, in <module>
  File "zipextimporter.pyo", line 82, in load_module
  File "youtube_dl\downloader\common.pyo", line 9, in <module>
  File "zipextimporter.pyo", line 82, in load_module
  File "youtube_dl\utils.pyo", line 26, in <module>
  File "zipextimporter.pyo", line 82, in load_module
  File "ssl.pyo", line 97, in <module>
  File "zipextimporter.pyo", line 98, in load_module
ImportError: MemoryLoadLibrary failed loading _ssl.pyd

 = Version 2015.10.18 =

C:\dev>"youtube-dl.exe"
Usage: youtube-dl(3).exe [OPTIONS] URL [URL...]

youtube-dl(3).exe: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options.

Windows 8, 64 bits

related : https://github.com/transifex/transifex-client/issues/82

**Comment by phihag** [comment]
Mmm, this is the first build on the new server (because after the update to Python 2.7.10 it crashed on the old one). Thank you for the report, I'll look into it.
