### ISSUE TITLE
downloading from BBC iplayer fails with stacktrace

### ISSUE THREAD

**Issue by TPolzer** [rg3/youtube-dl#7299]
```
[bbc.co.uk] b06kvt51: Downloading media selection XML
Traceback (most recent call last):
  File "/usr/bin/youtube-dl", line 9, in <module>
    load_entry_point('youtube-dl==2015.6.4.1', 'console_scripts', 'youtube-dl')()
  File "/usr/lib/python2.7/dist-packages/youtube_dl/__init__.py", line 405, in main
    _real_main(argv)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/__init__.py", line 395, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1502, in download
    res = self.extract_info(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 650, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 273, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/bbccouk.py", line 362, in _real_extract
    formats, subtitles = self._download_media_selector(programme_id)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/bbccouk.py", line 282, in _download_media_selector
    formats.extend(self._extract_video(media, programme_id))
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/bbccouk.py", line 204, in _extract_video
    file_size = int(media.get('media_file_size'))
TypeError: int() argument must be a string or a number, not 'NoneType'
```

**Comment by jaimeMF** [comment]
You are using an outdated version. If it fails after you [update](https://github.com/rg3/youtube-dl/blob/edeb3e7cb1ab2d82ff7c712a7cc1e338a9dcd8f8/README.md#how-do-i-update-youtube-dl), post the **full output** when running `youtube-dl --verbose URL` (as explained in [the bug reporting instructions](https://github.com/rg3/youtube-dl/blob/edeb3e7cb1ab2d82ff7c712a7cc1e338a9dcd8f8/README.md#bugs)).

**Comment by apythoncoder** [comment]
Still getting this issue with newest version

Stacktrace:
```
youtube-dl http://www.bbc.co.uk/iplayer/episode/b079s75g/undercover-episode-5 --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://www.bbc.co.uk/iplayer/episode/b079s75g/undercover-episode-5', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.06.04.1
[debug] Python version 2.7.10 - Linux-4.2.0-16-generic-i686-with-Ubuntu-15.10-wily
[debug] exe versions: avconv 2.7.6-0ubuntu0.15.10.1, avprobe 2.7.6-0ubuntu0.15.10.1, ffmpeg 2.7.6-0ubuntu0.15.10.1, ffprobe 2.7.6-0ubuntu0.15.10.1, rtmpdump 2.4
[debug] Proxy map: {}
[bbc.co.uk] b079s75g: Downloading video page
[bbc.co.uk] b079s73b: Downloading media selection XML
Traceback (most recent call last):
  File "/usr/bin/youtube-dl", line 6, in <module>
    youtube_dl.main()
  File "/usr/lib/python2.7/dist-packages/youtube_dl/__init__.py", line 405, in main
    _real_main(argv)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/__init__.py", line 395, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1502, in download
    res = self.extract_info(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 650, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 273, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/bbccouk.py", line 362, in _real_extract
    formats, subtitles = self._download_media_selector(programme_id)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/bbccouk.py", line 282, in _download_media_selector
    formats.extend(self._extract_video(media, programme_id))
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/bbccouk.py", line 204, in _extract_video
    file_size = int(media.get('media_file_size'))
TypeError: int() argument must be a string or a number, not 'NoneType'
```

**Comment by yan12125** [comment]
> [debug] youtube-dl version 2015.06.04.1

The latest version is 2016.05.01.

**Comment by apythoncoder** [comment]
Sorry - that's the version I got from apt 10 minutes ago, so I thought it was the newest.
