### ISSUE TITLE
Facebook login issue

### ISSUE THREAD

**Issue by danieman** [rg3/youtube-dl#7300]
Hi! youtube-dl won't log in to Facebook to get a private video. I have checked four times that the username and password are correct, but I still get this error.

```
youtube-dl -v --username 'user@user.com' --password 'password' 'https://www.facebook.com/user/videos/123456789987654321/'
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'--username', u'PRIVATE', u'--password', u'PRIVATE', u'https://www.facebook.com/user/videos/123456789987654321/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.10.24
[debug] Python version 2.7.2 - Darwin-12.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.5, ffprobe 2.5
[debug] Proxy map: {}
[facebook] Downloading login page
[facebook] Logging in
WARNING: unable to log in: bad username/password, or exceded login rate limit (~3/min). Check credentials or wait.
[facebook] 123456789987654321: Downloading webpage
ERROR: The video is not available, Facebook said: "The link you followed may have expired, or the page may only be visible to an audience you&#039;re not in."
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 661, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 291, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/facebook.py", line 138, in _real_extract
    expected=True)
ExtractorError: The video is not available, Facebook said: "The link you followed may have expired, or the page may only be visible to an audience you&#039;re not in."
```

**Comment by yan12125** [comment]
Facebook login is fixed. Could you check again?

**Comment by yan12125** [comment]
Closing this ticket for no response for a long time. Feel free to open new issues if problems are still.
