### ISSUE TITLE
Crunchyroll videos don't have subtitles

### ISSUE THREAD

**Issue by Fredddi43** [rg3/youtube-dl#7308]
Hey all, 
I just started using this tool today so apologies if theres a colossal oversight on my part, but I can't seem to get subtitles to work when trying to download from Crunchyroll. I've added my acc/pw in the netrc, if that makes any difference. Using the --list-subs on any video from Crunchyroll just returns a generic `<video-id> has no subtitles`, as shown in the example below, and as expected --sub-lang enUS or --all-subs returns `ERROR: requested format not available`. Any help is appreciated!

```
youtube-dl --list-subs http://www.crunchyroll.com/love-chunibyo-other-delusions-heart-throb-/episode-9-resort-last-resort-648797
[Crunchyroll] Logging in
[Crunchyroll] 648797: Downloading webpage
[Crunchyroll] 648797: Downloading media info
[Crunchyroll] 648797: Downloading media info for 360p
[Crunchyroll] 648797: Checking 360p URL
[Crunchyroll] 648797: Downloading media info for 480p
[Crunchyroll] 648797: Checking 480p URL
[Crunchyroll] 648797: Downloading media info for 720p
[Crunchyroll] 648797: Checking 720p URL
[Crunchyroll] 648797: Downloading media info for 1080p
[Crunchyroll] 648797: Checking 1080p URL
648797 has no subtitles
```

**Comment by dstftw** [comment]
Post the **full** output of youtube-dl when run [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by Fredddi43** [comment]
Sure thing, here you go:

```
youtube-dl --all-subs --verbose http://www.crunchyroll.com/love-chunibyo-other-delusions-heart-throb-/episode-9-resort-last-resort-648797
[debug] System config: []
[debug] User config: [u'--netrc', u'-f', u'best[height=360]', u'-o', u'/Users/Fred/Movies/Anime/%(title)s.%(ext)s']
[debug] Command-line args: [u'--all-subs', u'--verbose', u'http://www.crunchyroll.com/love-chunibyo-other-delusions-heart-throb-/episode-9-resort-last-resort-648797']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.10.18
[debug] Python version 2.7.6 - Darwin-14.1.0-x86_64-i386-64bit
[debug] exe versions: rtmpdump 2.4
[debug] Proxy map: {}
[Crunchyroll] Logging in
[Crunchyroll] 648797: Downloading webpage
[Crunchyroll] 648797: Downloading media info
[Crunchyroll] 648797: Downloading media info for 360p
[Crunchyroll] 648797: Checking 360p URL
[Crunchyroll] 648797: Downloading media info for 480p
[Crunchyroll] 648797: Checking 480p URL
[Crunchyroll] 648797: Downloading media info for 720p
[Crunchyroll] 648797: Checking 720p URL
[Crunchyroll] 648797: Downloading media info for 1080p
[Crunchyroll] 648797: Checking 1080p URL
ERROR: requested format not available
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 672, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 718, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1328, in process_video_result
    expected=True)
ExtractorError: requested format not available
```

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.

**Comment by Fredddi43** [comment]
Oh weird, I just installed today using brew, I didn't even think to check that! My bad, that fixed it! Thanks a lot!
