### ISSUE TITLE
LAZR json decoding alexanderstreet extraction

### ISSUE THREAD

**Issue by fu9ar** [rg3/youtube-dl#7321]
So... My university got a subscription to this thing and I've been playing with it to see if youtube-dl could dump it.  I found some information that suggests that it might be using this nonstandard method to serialize json data or something? Anyway... I'll play with this more when I have some free (yeah right) time, but I thought y'all should know about these things anyway. I'll probably actually have the time to play with it in December.

http://bazaar.launchpad.net/~lazr-developers/lazr.json/trunk/view/head:/README.txt

E:\>youtube-dl.exe -v http://search.alexanderstreet.com/view/work/2725242
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://search.alexanderstreet.com/view/work
/2725242']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.10.06.2
[debug] Python version 2.7.8 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[generic] 2725242: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 2725242: Downloading webpage
[generic] 2725242: Extracting information
[download] Downloading playlist: None
[generic] playlist None: Collected 2 video ids (downloading 2 of them)
[download] Downloading video 1 of 2
[debug] Invoking downloader on u'http://search.alexanderstreet.com/view/work/\\/
\\/alexstreet.vo.llnwd.net\\/o25\\/muco\\/1006835xxx\\/1006835573\\/1006835573-d
isc001-file001-400kbps-400pixels.m4v?e=1446197306\\u0026h=749e220b03ae69f6bc6d43
3f9287e47f'
[download] Destination: A Hard Day's Night _ Alexander Street (1)-u0026h=749e220
b03ae69f6bc6d433f9287e47f.m4v
[download] 348.1% of 8.93KiB at Unknown speed ETA Unknown ETAERROR: content too
short (expected 9142 bytes and served 31824)
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 1597, in process_info
  File "youtube_dl\YoutubeDL.pyo", line 1539, in dl
  File "youtube_dl\downloader\common.pyo", line 342, in download
  File "youtube_dl\downloader\http.pyo", line 238, in real_download
ContentTooShortError

E:\>youtube-dl.exe -j http://search.alexanderstreet.com/view/work/2725242
WARNING: Falling back on generic information extractor.
{"display_id": "u0026h=749e220b03ae69f6bc6d433f9287e47f", "extractor": "generic"
, "format": "0 - unknown", "requested_subtitles": null, "uploader": "search.alex
anderstreet.com", "format_id": "0", "playlist_index": 1, "playlist_title": null,
 "playlist": null, "http_headers": {"Accept-Language": "en-us,en;q=0.5", "Accept
-Encoding": "gzip, deflate", "Accept": "text/html,application/xhtml+xml,applicat
ion/xml;q=0.9,*/*;q=0.8", "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:10.0
) Gecko/20150101 Firefox/20.0 (Chrome)", "Accept-Charset": "ISO-8859-1,utf-8;q=0
.7,*;q=0.7", "Cookie": "SESS7beeaee852f6adcf8b7816afcd99defe=Sr4F9GJ0otaCiyLhve1
JXLbsQbGgqL5ry6S5dLzYZ20; cookied_customer_id=17"}, "url": "http://search.alexan
derstreet.com/view/work/\\/\\/alexstreet.vo.llnwd.net\\/o25\\/muco\\/1006835xxx\
\/1006835573\\/1006835573-disc001-file001-400kbps-400pixels.m4v?e=1446197306\\u0
026h=749e220b03ae69f6bc6d433f9287e47f", "extractor_key": "Generic", "title": "A
Hard Day's Night | Alexander Street (1)", "id": "u0026h=749e220b03ae69f6bc6d433f
9287e47f", "playlist_id": null, "ext": "m4v", "webpage_url_basename": "2725242",
 "webpage_url": "http://search.alexanderstreet.com/view/work/2725242", "_filenam
e": "A Hard Day's Night _ Alexander Street (1)-u0026h=749e220b03ae69f6bc6d433f92
87e47f.m4v", "fulltitle": "A Hard Day's Night | Alexander Street (1)", "age_limi
t": 0, "n_entries": 2}
{"display_id": "u0026h=2cf5527087b04ea40775894be8b092c9", "extractor": "generic"
, "format": "0 - unknown", "requested_subtitles": null, "uploader": "search.alex
anderstreet.com", "format_id": "0", "playlist_index": 2, "playlist_title": null,
 "playlist": null, "http_headers": {"Accept-Language": "en-us,en;q=0.5", "Accept
-Encoding": "gzip, deflate", "Accept": "text/html,application/xhtml+xml,applicat
ion/xml;q=0.9,*/*;q=0.8", "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:10.0
) Gecko/20150101 Firefox/20.0 (Chrome)", "Accept-Charset": "ISO-8859-1,utf-8;q=0
.7,*;q=0.7", "Cookie": "SESS7beeaee852f6adcf8b7816afcd99defe=Sr4F9GJ0otaCiyLhve1
JXLbsQbGgqL5ry6S5dLzYZ20; cookied_customer_id=17"}, "url": "http://search.alexan
derstreet.com/view/work/\\/\\/alexstreet.vo.llnwd.net\\/o25\\/muco\\/1006835xxx\
\/1006835573\\/1006835573-disc001-file001-800kbps-640pixels.m4v?e=1446197306\\u0
026h=2cf5527087b04ea40775894be8b092c9", "extractor_key": "Generic", "title": "A
Hard Day's Night | Alexander Street (2)", "id": "u0026h=2cf5527087b04ea40775894b
e8b092c9", "playlist_id": null, "ext": "m4v", "webpage_url_basename": "2725242",
 "webpage_url": "http://search.alexanderstreet.com/view/work/2725242", "_filenam
e": "A Hard Day's Night _ Alexander Street (2)-u0026h=2cf5527087b04ea40775894be8
b092c9.m4v", "fulltitle": "A Hard Day's Night | Alexander Street (2)", "age_limi
t": 0, "n_entries": 2}

E:\>

**Comment by xthursdayx** [comment]
@kevin-vilbig Did you ever figure this out? I'm trying to sort out the same thing.

**Comment by wornt** [comment]
I am also interested in this. Has anyone tried playing with this problem?
