### ISSUE TITLE
Bleacherreport - video download error 

### ISSUE THREAD

**Issue by MaryCoding** [rg3/youtube-dl#7337]
Hi, I tried to download video from this url: http://bleacherreport.com/articles/2584353-a-symphony-in-san-antonio-spurs-big-3-will-soon-stand-alone-as-winningest-trio and got an error. 

```
youtube-dl -v --no-warnings -o "/media/%(title)s.%(ext)s" " http://bleacherreport.com/articles/2584353-a-symphony-in-san-antonio-spurs-big-3-will-soon-stand-alone-as-winningest-trio"
[debug] System config: [u'--ffmpeg-location', u'/home/mimi/bin/ffmpeg']
[debug] User config: []
[debug] Command-line args: [u'-v', u'--no-warnings', u'-o', u'/media/%(title)s.%(ext)s', u' http://bleacherreport.com/video_embed?id=dwYnhoeDqr7iftQD3gc_N37YdXROpnq8']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.10.24
[debug] Python version 2.7.9 - Linux-3.19.0-30-generic-x86_64-with-Ubuntu-15.04-vivid
[debug] exe versions: ffmpeg 2.6.git, ffprobe 2.6.git, rtmpdump 2.4
[debug] Proxy map: {}
[generic] video_embed?id=dwYnhoeDqr7iftQD3gc_N37YdXROpnq8: Requesting header
[generic] video_embed?id=dwYnhoeDqr7iftQD3gc_N37YdXROpnq8: Downloading webpage
[generic] video_embed?id=dwYnhoeDqr7iftQD3gc_N37YdXROpnq8: Extracting information
ERROR: Unsupported URL: http://bleacherreport.com/video_embed?id=dwYnhoeDqr7iftQ                                                   D3gc_N37YdXROpnq8
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1240, in _real_extract
    doc = parse_xml(webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1667, in parse_xml
    tree = xml.etree.ElementTree.XML(s.encode('utf-8'), **kwargs)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 5, column 378
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 661, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 291, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1838, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://bleacherreport.com/video_embed?id=dwYn                                                   hoeDqr7iftQD3gc_N37YdXROpnq8
```

**Comment by remitamine** [comment]
will be supported in the next version.
