### ISSUE TITLE
Support for videolectures.net is broken

### ISSUE THREAD

**Issue by noe** [rg3/youtube-dl#7340]
With youtube-dl version 2015.11.01, the support for videolectures.net seems to be broken as of 2015 November 2nd. None of the example URLs from the original videolectures.net support request (https://github.com/rg3/youtube-dl/issues/1877) works any longer.

The traceback is:

<pre>
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 410, in main
    
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 400, in _real_main
    
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1666, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 672, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 833, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 725, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 672, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 718, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1336, in process_video_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1407, in process_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 606, in _match_entry
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 994, in __contains__
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 957, in date_from_str
  File "/usr/lib/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data 'None' does not match format '%Y%m%d'
</pre>

**Comment by jaimeMF** [comment]
It should work in the next version. Since you didn't provide a URL I have only tested with http://videolectures.net/netadis2013_monasson_graph_theory/, for future reports please post the url and the full output you get with `youtube-dl --verbose URL` (as explained in the [bug reporting instructions](http://videolectures.net/netadis2013_monasson_graph_theory/)).
