### ISSUE TITLE
www.mitele.es no longer working

### ISSUE THREAD

**Issue by jonapom** [rg3/youtube-dl#7343]
myuser@jessie:~$ Desktop/youtube-dl/youtube-dl --continue --buffer-size 10M --no-resize-buffer --rate-limit=75k --output "/downloads/Cuarto.Milenio.S11E427" http://www.mitele.es/programas-tv/cuarto-milenio/temporada-11/programa-427/ -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--continue', u'--buffer-size', u'10M', u'--no-resize-buffer', u'--rate-limit=75k', u'--output', u'/p2p/downloads/Cuarto.Milenio.S11E427', u'http://www.mitele.es/programas-tv/cuarto-milenio/temporada-11/programa-427/', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.01
[debug] Python version 2.7.9 - Linux-3.16.0-4-686-pae-i686-with-debian-8.2
[debug] exe versions: avconv 11.4-6, avprobe 11.4-6, rtmpdump 2.4
[debug] Proxy map: {}
[MiTele] programa-427: Downloading webpage
[MiTele] programa-427: Downloading config JSON
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "Desktop/youtube-dl/youtube-dl/__main__.py", line 19, in <module>
  File "Desktop/youtube-dl/youtube-dl/youtube_dl/__init__.py", line 410, in main
  File "Desktop/youtube-dl/youtube-dl/youtube_dl/__init__.py", line 400, in _real_main
  File "Desktop/youtube-dl/youtube-dl/youtube_dl/YoutubeDL.py", line 1666, in download
  File "Desktop/youtube-dl/youtube-dl/youtube_dl/YoutubeDL.py", line 661, in extract_info
  File "Desktop/youtube-dl/youtube-dl/youtube_dl/extractor/common.py", line 290, in extract
  File "Desktop/youtube-dl/youtube-dl/youtube_dl/extractor/mitele.py", line 39, in _real_extract
  File "Desktop/youtube-dl/youtube-dl/youtube_dl/extractor/common.py", line 473, in _download_json
  File "Desktop/youtube-dl/youtube-dl/youtube_dl/extractor/common.py", line 441, in _download_webpage
  File "Desktop/youtube-dl/youtube-dl/youtube_dl/extractor/common.py", line 348, in _download_webpage_handle
  File "Desktop/youtube-dl/youtube-dl/youtube_dl/extractor/common.py", line 329, in _request_webpage
  File "Desktop/youtube-dl/youtube-dl/youtube_dl/YoutubeDL.py", line 1873, in urlopen
  File "/usr/lib/python2.7/urllib2.py", line 423, in open
    protocol = req.get_type()
  File "/usr/lib/python2.7/urllib2.py", line 285, in get_type
    raise ValueError, "unknown url type: %s" % self.__original
ValueError: unknown url type: /api/cms/mitele/videos/168761/config/final.json

**Comment by jaimeMF** [comment]
Thanks for the report, it will work again in the next version.
