### ISSUE TITLE
[YouTube] # (hashtag) in user name gets replaced for a . (full stop) when the merging starts.

### ISSUE THREAD

**Issue by EraYaN** [rg3/youtube-dl#7367]
So a # (hashtag) in username gets replaced with a . (full stop) when the merging starts.

So ffmpeg fails because it can't find the file.

Config:
```
--prefer-ffmpeg
--all-subs
--restrict-filenames
--output 'downloads/%(uploader)s/%(title)s-%(id)s.%(ext)s'
--cache-dir 'cache/'
--embed-subs
--add-metadata
--xattrs
--ignore-errors
```

batch file
```
@ECHO OFF
CALL :RESOLVE "%~dp0%\..\" TOOLSPATH
set PATH=%PATH%;%TOOLSPATH%FFmpeg;%TOOLSPATH%AtomicParseley;%TOOLSPATH%rtmpdump\original;
ECHO "YouTube. Best quality."
set /p url="Enter URL: " %=%
youtube-dl.exe -f bestvideo+bestaudio "%url%"
if NOT ["%errorlevel%"]==["0"] (
    pause
    exit /b %errorlevel%
)
GOTO :EOF

:RESOLVE
SET %2=%~f1
GOTO :EOF
```

console log (I added --verbose to the batch file listed above)
```
"YouTube. Best quality."
Enter URL: https://www.youtube.com/watch?v=OxrbHYkOr2A
[debug] System config: []
[debug] User config: [u'--prefer-ffmpeg', u'--all-subs', u'--restrict-filenames', u'--output', u'downloads/%(uploader)s/%(title)s-%(id)s.%(ext)s', u'--cache-dir', u'cache/', u'--embed-subs', u'--add-metadata', u'--xattrs
', u'--ignore-errors']
[debug] Command-line args: [u'--verbose', u'-f', u'bestvideo+bestaudio', u'https://www.youtube.com/watch?v=OxrbHYkOr2A']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.11.02
[debug] Python version 2.7.10 - Windows-8-6.2.9200
[debug] exe versions: ffmpeg N-73802-gea8785c, ffprobe N-73802-gea8785c, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] OxrbHYkOr2A: Downloading webpage
[youtube] OxrbHYkOr2A: Downloading video info webpage
[youtube] OxrbHYkOr2A: Extracting video information
WARNING: video doesn't have subtitles
[youtube] OxrbHYkOr2A: Downloading DASH manifest
[youtube] OxrbHYkOr2A: Downloading DASH manifest
[debug] Invoking downloader on u'https://r7---sn-5hne6ned.googlevideo.com/videoplayback?id=3b1adb1d890eaf60&itag=299&source=youtube&requiressl=yes&nh=IgpwcjA0LmFtczE2KgkxMjcuMC4wLjE&mm=31&mn=sn-5hne6ned&pl=20&ms=au&mv=m&
ratebypass=yes&mime=video/mp4&gir=yes&clen=151781030&lmt=1446654121872168&dur=220.169&sver=3&key=dg_yt0&upn=JVe-U50nrkY&signature=98136FBC9E129509280A76A20B86EE2E96239587.968DF5302546DA7858CD915BFE8392BD55A21C3D&mt=14466
74581&fexp=9407118,9408710,9414764,9415554,9416126,9417707,9418203,9418749,9419445,9421551,9422571,9422596,9423662,9423790&ip=83.84.31.179&ipbits=0&expire=1446696294&sparams=ip,ipbits,expire,id,itag,source,requiressl,nh,
mm,mn,pl,ms,mv,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: downloads\Mera_#\151104_A-PINK_-_Remember_Fancam_by_Mera-OxrbHYkOr2A.f299.mp4
[download] 100% of 144.75MiB in 00:09
[debug] Invoking downloader on u'https://r7---sn-5hne6ned.googlevideo.com/videoplayback?id=3b1adb1d890eaf60&itag=140&source=youtube&requiressl=yes&nh=IgpwcjA0LmFtczE2KgkxMjcuMC4wLjE&mm=31&mn=sn-5hne6ned&pl=20&ms=au&mv=m&
ratebypass=yes&mime=audio/mp4&gir=yes&clen=3503389&lmt=1446653898582588&dur=220.519&sver=3&key=dg_yt0&upn=JVe-U50nrkY&signature=1DC0FCCFE8FA67936823B23FDF93A156D31C7930.4FC02683833BB3E8E8E48C700D5B4CEBCB652536&mt=1446674
581&fexp=9407118,9408710,9414764,9415554,9416126,9417707,9418203,9418749,9419445,9421551,9422571,9422596,9423662,9423790&ip=83.84.31.179&ipbits=0&expire=1446696294&sparams=ip,ipbits,expire,id,itag,source,requiressl,nh,mm
,mn,pl,ms,mv,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: downloads\Mera_#\151104_A-PINK_-_Remember_Fancam_by_Mera-OxrbHYkOr2A.f140.m4a
[download] 100% of 3.34MiB in 00:00
[ffmpeg] Merging formats into "downloads\Mera_.\151104_A-PINK_-_Remember_Fancam_by_Mera-OxrbHYkOr2A.mp4"
ERROR: [Error 3] Het systeem kan het opgegeven pad niet vinden: u'downloads\\Mera_.\\151104_A-PINK_-_Remember_Fancam_by_Mera-OxrbHYkOr2A.f299.mp4'
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 672, in extract_info
  File "youtube_dl\YoutubeDL.pyo", line 718, in process_ie_result
  File "youtube_dl\YoutubeDL.pyo", line 1336, in process_video_result
  File "youtube_dl\YoutubeDL.pyo", line 1648, in process_info
  File "youtube_dl\YoutubeDL.pyo", line 1712, in post_process
  File "youtube_dl\postprocessor\ffmpeg.pyo", line 406, in run
  File "youtube_dl\postprocessor\ffmpeg.pyo", line 132, in run_ffmpeg_multiple_files
  File "youtube_dl\postprocessor\ffmpeg.pyo", line 132, in <genexpr>
WindowsError: [Error 3] Het systeem kan het opgegeven pad niet vinden: u'downloads\\Mera_.\\151104_A-PINK_-_Remember_Fancam_by_Mera-OxrbHYkOr2A.f299.mp4'

Press any key to continue . . .
```
"Het systeem kan het opgegeven pad niet vinden" translates to "System can't find given filepath."

**Comment by EraYaN** [comment]
Wow gosh darn that was fast.
