### ISSUE TITLE
Save mp3 file from youtube with hebrew charcter

### ISSUE THREAD

**Issue by yonarad** [rg3/youtube-dl#740]
Hi,

I want to save MP3s from youtube with the title of the song in hebrew.
when I want only download video, i success, but when i want to extract audio, I getting error.
Can you help me?
Thanks

The command:
youtube-dl -t -x --audio-format mp3 http://www.youtube.com/watch?v=OIYeCPUIL1E

The error:
Traceback (most recent call last):
  File "__main__.py", line 17, in <module>
  File "youtube_dl\__init__.pyo", line 516, in main
  File "youtube_dl\__init__.pyo", line 500, in _real_main
  File "youtube_dl\FileDownloader.pyo", line 525, in download
  File "youtube_dl\FileDownloader.pyo", line 480, in process_info
  File "youtube_dl\FileDownloader.pyo", line 544, in post_process
  File "youtube_dl\PostProcessor.pyo", line 140, in run
  File "youtube_dl\PostProcessor.pyo", line 110, in get_audio_codec
  File "subprocess.pyo", line 679, in __init__
  File "subprocess.pyo", line 896, in _execute_child
UnicodeEncodeError: 'ascii' codec can't encode characters in position 23-26: ordinal not in range(128)

**Comment by wildeyes** [comment]
This should be closed as wont-fix.

**Comment by dstftw** [comment]
Works fine with latest version.
