### ISSUE TITLE
ExtractorError

### ISSUE THREAD

**Issue by stephensonsco** [rg3/youtube-dl#7444]
I tried this on a couple machines and got the same error (that was after updating as was pointed out in the error).

There was an error in downloading this video:
https://www.youtube.com/watch?v=FGBhQbmPwH8

I used this command:
$ youtube-dl -v FGBhQbmPwH8

Error text:
____

$ youtube-dl -v FGBhQbmPwH8
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'FGBhQbmPwH8']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.10.24
[debug] Python version 2.7.3 - Darwin-12.5.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.7.2, ffprobe 2.7.2
[debug] Proxy map: {}
[youtube] FGBhQbmPwH8: Downloading webpage
[youtube] FGBhQbmPwH8: Downloading video info webpage
[youtube] FGBhQbmPwH8: Extracting video information
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {43} signature length 40.44, html5 player None
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/Users/isospin/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 817, in _decrypt_signature
    video_id, player_url, s
  File "/Users/isospin/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 709, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
ExtractorError: Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vfljDEtYP/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vfljDEtYP/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/Users/isospin/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 817, in _decrypt_signature
    video_id, player_url, s
  File "/Users/isospin/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 709, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
ExtractorError: Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vfljDEtYP/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/Users/isospin/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 661, in extract_info
    ie_result = ie.extract(url)
  File "/Users/isospin/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 291, in extract
    return self._real_extract(url)
  File "/Users/isospin/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 1345, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/Users/isospin/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 827, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/Users/isospin/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 817, in _decrypt_signature
    video_id, player_url, s
  File "/Users/isospin/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 709, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
ExtractorError: Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vfljDEtYP/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vfljDEtYP/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.

**Comment by stephensonsco** [comment]
Ah, yeah. The machine I grabbed the error from wasn't updated. It is updated now, using homebrew (OSX), but the version is still:
youtube-dl 2015.10.09

which unfortunately still has the error (ExtractionError). This is probably a problem with the package manager. Thanks for the help!
