### ISSUE TITLE
Vimeo - video password verification failed! - v.2015.11.10

### ISSUE THREAD

**Issue by LTIOfficial** [rg3/youtube-dl#7451]
After updating youtube-dl, I tried the same command structure that's worked for me in the past, but no joy.  The page opens and plays when the same password is used directly at the Vimeo hosting page.  Am I missing something?

python2.6 youtube-dl --verbose --video-password xxxxxxx http://vimeo.com/xxxxxxxx

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'--video-password', u'PRIVATE', u'http://vimeo.com/xxxxxxxx']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.10
[debug] Python version 2.6.8 - Linux-2.6.32-042stab104.1-x86_64-with-redhat-5.11-Final
[debug] exe versions: ffmpeg SVN-r19795
[debug] Proxy map: {}
[vimeo] xxxxxxxx: Downloading webpage
[vimeo] xxxxxxxx: Extracting information
[vimeo] xxxxxxxx: Verifying the password
[vimeo] xxxxxxxx: Downloading webpage
[vimeo] xxxxxxxx: Extracting information
ERROR: video password verification failed!; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube-dl/youtube_dl/extractor/vimeo.py", line 316, in _real_extract
    flags=re.DOTALL)
  File "youtube-dl/youtube_dl/extractor/common.py", line 584, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract info section; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube-dl/youtube_dl/YoutubeDL.py", line 661, in extract_info
    ie_result = ie.extract(url)
  File "youtube-dl/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "youtube-dl/youtube_dl/extractor/vimeo.py", line 327, in _real_extract
    smuggle_url(url, {'_video_password_verified': 'verified'}))
  File "youtube-dl/youtube_dl/extractor/vimeo.py", line 324, in _real_extract
    raise ExtractorError('video password verification failed!')
ExtractorError: video password verification failed!; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by LTIOfficial** [comment]
The latest version worked perfectly.  Thank you!
