### ISSUE TITLE
Vimeo: No video formats found

### ISSUE THREAD

**Issue by jpcalkins** [rg3/youtube-dl#7460]
Trying to download video off of Vimeo, https://vimeo.com/144566059, and get this error

    youtube-dl -v https://vimeo.com/144566059
    [debug] System config: []
    [debug] User config: []
    [debug] Command-line args: [u'-v', u'https://vimeo.com/144566059']
    [debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
    [debug] youtube-dl version 2015.11.10
    [debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
    [debug] exe versions: none
    [debug] Proxy map: {}
    [vimeo] 144566059: Downloading webpage
    [vimeo] 144566059: Extracting information
    [vimeo] 144566059: Downloading webpage
    ERROR: No video formats found; please report this issue on https://yt-dl.org/bug.
    Make sure you are using the latest version; type  youtube-dl -U  to update. Be 
    sure to call youtube-dl with the --verbose flag and include its complete output.
    Traceback (most recent call last):
      File "youtube_dl\extractor\vimeo.pyo", line 378, in _real_extract
      File "youtube_dl\extractor\common.pyo", line 584, in _search_regex
    RegexNotFoundError: Unable to extract view count; please report this issue on ht
    tps://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-
    dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include
     its complete output.
    Traceback (most recent call last):
      File "youtube_dl\YoutubeDL.pyo", line 661, in extract_info
      File "youtube_dl\extractor\common.pyo", line 290, in extract
      File "youtube_dl\extractor\vimeo.pyo", line 427, in _real_extract
      File "youtube_dl\extractor\common.pyo", line 766, in _sort_formats
    ExtractorError: No video formats found; please report this issue on https://yt-d
    l.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to
    update. Be sure to call youtube-dl with the --verbose flag and include its compl
    ete output.

I was able to download a few videos just fine before this error popped up and it doesn't have an issue downloading videos from other sites. Is this because of Vimeo's limit on number of videos a person may download per day?

**Comment by vxbinaca** [comment]
I'm getting much the same:

```youtube-dl --verbose --ignore-config https://vimeo.com/junnnktank```

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'--ignore-config', u'https://vimeo.com/junnnktank']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.10
[debug] Python version 2.7.10 - Linux-4.2.0-17-generic-x86_64-with-Ubuntu-15.10-wily
[debug] exe versions: ffmpeg 2.7.2-1build1, ffprobe 2.7.2-1build1, rtmpdump 2.4
[debug] Proxy map: {}
[vimeo:user] junnnktank: Downloading page 1
[vimeo:user] junnnktank: Downloading page 2
[vimeo:user] junnnktank: Downloading page 3
[vimeo:user] junnnktank: Downloading page 4
[vimeo:user] junnnktank: Downloading page 5
[vimeo:user] junnnktank: Downloading page 6
[vimeo:user] junnnktank: Downloading page 7
[vimeo:user] junnnktank: Downloading page 8
[download] Downloading playlist: JUNNNKTANK
[vimeo:user] playlist JUNNNKTANK: Collected 92 video ids (downloading 92 of them)
[download] Downloading video 1 of 92
[vimeo] 140350948: Downloading webpage
[vimeo] 140350948: Extracting information
[vimeo] 140350948: Downloading webpage
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/vimeo.py", line 378, in _real_extract
    view_count = int(self._search_regex(r'UserPlays:(\d+)', webpage, 'view count'))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 584, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract view count; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 661, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/vimeo.py", line 427, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 766, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by broberts01** [comment]
**Unfortunately 2015-11-10 did not fix the issue.**
  Same *No video formats found* on CentOS and Mac O/S X.

```
python $B/youtube-dl --verbose -F "https://vimeo.com/144839702"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'-F', u'https://vimeo.com/144839702']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.10
[debug] Python version 2.7.10 - Darwin-14.5.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.8, ffprobe 2.8
[debug] Proxy map: {}
[vimeo] 144839702: Downloading webpage
[vimeo] 144839702: Extracting information
[vimeo] 144839702: Downloading webpage
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/vimeo.py", line 378, in _real_extract
    view_count = int(self._search_regex(r'UserPlays:(\d+)', webpage, 'view count'))
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 584, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract view count; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 661, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/vimeo.py", line 427, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 766, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
2015.11.10 was released before this issue has appeared.

**Comment by broberts01** [comment]
If I understand correctly it's fixed...but it's not yet in the release branch.  So the -U to upgrade won't help you until the fix makes it into a release.
