### ISSUE TITLE
Error in logging in safaribooksonline with username & password

### ISSUE THREAD

**Issue by dxxvi** [rg3/youtube-dl#7465]
youtube-dl --verbose --username safari10nexas --password Abcd1234 https://www.safaribooksonline.com/library/view/learning-javascript-promises/9781784391355/part00.html?autoStart=True
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '--username', 'PRIVATE', '--password', 'PRIVATE', 'https://www.safaribooksonline.com/library/view/learning-javascript-promises/9781784391355/part00.html?autoStart=True']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.10
[debug] Python version 3.5.0 - Linux-4.2.5-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 2.8.1, ffprobe 2.8.1, rtmpdump 2.4
[debug] Proxy map: {}
[safari] Downloading login form
[safari] Logging in as safari10nexas
Traceback (most recent call last):
  File "/usr/bin/youtube-dl", line 9, in <module>
    load_entry_point('youtube-dl==2015.11.10', 'console_scripts', 'youtube-dl')()
  File "/usr/lib/python3.5/site-packages/youtube_dl/__init__.py", line 410, in main
    _real_main(argv)
  File "/usr/lib/python3.5/site-packages/youtube_dl/__init__.py", line 400, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 1666, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 661, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 289, in extract
    self.initialize()
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 283, in initialize
    self._real_initialize()
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/safari.py", line 33, in _real_initialize
    self._login()
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/safari.py", line 64, in _login
    request, None, 'Logging in as %s' % username)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 441, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 348, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 329, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 1873, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 463, in open
    req = meth(req)
  File "/usr/lib/python3.5/urllib/request.py", line 1170, in do_request_
    raise TypeError(msg)
TypeError: POST data should be bytes or an iterable of bytes. It cannot be of type str.

Note: this username/password is working, but it's a trial account.

**Comment by yan12125** [comment]
Sorry for not responding. Safari login should have been fixed in the latest version of youtube-dl. Feel free to open new issues if there are still problems.
