### ISSUE TITLE
ffmpeg post processing CLI issue

### ISSUE THREAD

**Issue by Starbuck2010** [rg3/youtube-dl#7485]
`C:/Users/Jean-Michel/AppData/Local/labDV.com/Video 360 - Tube/bin/youtube-dl/youtube-dl.exe --verbose -i --playlist-items 2 -o D:/Users/Me/Videos/Tube/the best of  the gladiators/%(title)s.%(ext)s --format bestaudio -x --audio-format mp3 --audio-quality 320k --postprocessor-args -strict experimental --ffmpeg-location C:/Projects/Dev/App/bin/applications/zeranoe/ffmpeg-x64/bin/ffmpeg.exe https://www.youtube.com/watch?v=re2-2j-q6Q8&list=RDre2-2j-q6Q8#t=4
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'-i', u'--playlist-items', u'2', u'-o', u'D:/Users/Me/Videos/Tube/the best of  the gladiators/%(title)s.%(ext)s', u'--format', u'bestaudio', u'-x', u'--audio-format', u'mp3', u'--audio-quality', u'320k', u'--postprocessor-args', u'-strict experimental --ffmpeg-location', u'C:/Projects/Dev/App/bin/applications/zeranoe/ffmpeg-x64/bin/ffmpeg.exe', u'https://www.youtube.com/watch?v=re2-2j-q6Q8&list=RDre2-2j-q6Q8#t=4']
[debug] Encodings: locale cp1252, fs mbcs, out None, pref cp1252
[debug] youtube-dl version 2015.11.10
[debug] Python version 2.7.10 - Windows-8-6.2.9200
[debug] exe versions: ffmpeg N-72443-g2e15f07, ffprobe N-72443-g2e15f07
[debug] Proxy map: {}
[generic] ffmpeg: Requesting header
WARNING: Could not send HEAD request to C:/Projects/Dev/App/bin/applications/zeranoe/ffmpeg-x64/bin/ffmpeg.exe: 
[generic] ffmpeg: Downloading webpage
ERROR: Unable to download webpage:  (caused by URLError(u'unknown url type: c',))
  File "youtube_dl\extractor\common.pyo", line 329, in _request_webpage
  File "youtube_dl\YoutubeDL.pyo", line 1873, in urlopen
  File "urllib2.pyo", line 431, in open
  File "urllib2.pyo", line 454, in _open
  File "urllib2.pyo", line 409, in _call_chain
  File "urllib2.pyo", line 1265, in unknown_open

[youtube:playlist] Downloading playlist RDre2-2j-q6Q8 - add --no-playlist to just download video re2-2j-q6Q8
[youtube:playlist] RDre2-2j-q6Q8: Downloading Youtube mix
[download] Downloading playlist: Mix - the best of  the gladiators
[youtube:playlist] playlist Mix - the best of  the gladiators: Collected 26 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[youtube] qbd_orEZHqU: Downloading webpage
[youtube] qbd_orEZHqU: Downloading video info webpage
[youtube] qbd_orEZHqU: Extracting video information
[youtube] {22} signature length 41.40, html5 player en_US-vflJENbn4
[youtube] {43} signature length 41.40, html5 player en_US-vflJENbn4
[youtube] {18} signature length 41.40, html5 player en_US-vflJENbn4
[youtube] {5} signature length 41.40, html5 player en_US-vflJENbn4
[youtube] {36} signature length 41.40, html5 player en_US-vflJENbn4
[youtube] {17} signature length 41.40, html5 player en_US-vflJENbn4
[youtube] {137} signature length 41.40, html5 player en_US-vflJENbn4
[youtube] {248} signature length 41.40, html5 player en_US-vflJENbn4
[youtube] {136} signature length 41.40, html5 player en_US-vflJENbn4
[youtube] {247} signature length 41.40, html5 player en_US-vflJENbn4
[youtube] {135} signature length 39.40, html5 player en_US-vflJENbn4
[youtube] {244} signature length 41.40, html5 player en_US-vflJENbn4
[youtube] {134} signature length 41.40, html5 player en_US-vflJENbn4
[youtube] {243} signature length 41.40, html5 player en_US-vflJENbn4
[youtube] {133} signature length 41.40, html5 player en_US-vflJENbn4
[youtube] {242} signature length 41.40, html5 player en_US-vflJENbn4
[youtube] {160} signature length 41.40, html5 player en_US-vflJENbn4
[youtube] {278} signature length 41.40, html5 player en_US-vflJENbn4
[youtube] {140} signature length 41.40, html5 player en_US-vflJENbn4
[youtube] {171} signature length 41.40, html5 player en_US-vflJENbn4
[youtube] {249} signature length 41.40, html5 player en_US-vflJENbn4
[youtube] {250} signature length 41.40, html5 player en_US-vflJENbn4
[youtube] {251} signature length 41.40, html5 player en_US-vflJENbn4
[youtube] qbd_orEZHqU: Downloading DASH manifest
[debug] Invoking downloader on u'https://r10---sn-hgn7zn7s.googlevideo.com/videoplayback?id=a9b77fa2b1191ea5&itag=141&source=youtube&requiressl=yes&pl=16&mv=m&ms=au&mn=sn-hgn7zn7s&mm=31&ratebypass=yes&mime=audio/mp4&gir=yes&clen=63097025&lmt=1429714603316862&dur=1979.059&upn=ZXvK6GbJyaU&fexp=9408241,9408710,9414764,9416126,9417683,9420452,9422596,9422618,9423662&sver=3&mt=1447401196&signature=4843F3BBB8E8969717D4C55D6C6A3F96E22A5F61.80694DFC4587C400296A1171FD34627A7D26285A&key=dg_yt0&ip=90.52.190.214&ipbits=0&expire=1447422956&sparams=ip,ipbits,expire,id,itag,source,requiressl,pl,mv,ms,mn,mm,ratebypass,mime,gir,clen,lmt,dur'
[download] D:\Users\Me\Videos\Tube\the best of  the gladiators\The Gladiators - 1982 - Back To Roots (FULL ALBUM).m4a has already been downloaded
[download] 100% of 60.17MiB
[ffmpeg] Correcting container in "D:\Users\Me\Videos\Tube\the best of  the gladiators\The Gladiators - 1982 - Back To Roots (FULL ALBUM).m4a"
[debug] ffmpeg command line: ffmpeg -y -i 'file:D:\Users\Me\Videos\Tube\the best of  the gladiators\The Gladiators - 1982 - Back To Roots (FULL ALBUM).m4a' -c copy -f mp4 -strict experimental --ffmpeg-location 'file:D:\Users\Me\Videos\Tube\the best of  the gladiators\The Gladiators - 1982 - Back To Roots (FULL ALBUM).temp.m4a'
ERROR: Error splitting the argument list: Option not found
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 1712, in post_process
  File "youtube_dl\postprocessor\ffmpeg.pyo", line 457, in run
  File "youtube_dl\postprocessor\ffmpeg.pyo", line 158, in run_ffmpeg
  File "youtube_dl\postprocessor\ffmpeg.pyo", line 154, in run_ffmpeg_multiple_files
FFmpegPostProcessorError

[debug] ffmpeg command line: ffprobe -show_streams 'file:D:\Users\Me\Videos\Tube\the best of  the gladiators\The Gladiators - 1982 - Back To Roots (FULL ALBUM).m4a'
[ffmpeg] Destination: D:\Users\Me\Videos\Tube\the best of  the gladiators\The Gladiators - 1982 - Back To Roots (FULL ALBUM).mp3
[debug] ffmpeg command line: ffmpeg -y -i 'file:D:\Users\Me\Videos\Tube\the best of  the gladiators\The Gladiators - 1982 - Back To Roots (FULL ALBUM).m4a' -vn -acodec libmp3lame -b:a 320k -strict experimental --ffmpeg-location 'file:D:\Users\Me\Videos\Tube\the best of  the gladiators\The Gladiators - 1982 - Back To Roots (FULL ALBUM).mp3'
ERROR: audio conversion failed: Error splitting the argument list: Option not found
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 1712, in post_process
  File "youtube_dl\postprocessor\ffmpeg.pyo", line 279, in run
PostProcessingError`

**[debug] ffmpeg command line: ffmpeg -y -i 'file:D:\Users\Me\Videos\Tube\the best of  the gladiators\The Gladiators - 1982 - Back To Roots (FULL ALBUM).m4a' -vn -acodec libmp3lame -b:a 320k -strict experimental --ffmpeg-location 'file:D:\Users\Me\Videos\Tube\the best of  the gladiators\The Gladiators - 1982 - Back To Roots (FULL ALBUM).mp3'
ERROR: audio conversion failed: Error splitting the argument list: Option not found**

 --ffmpeg-location is in ffmprg command !!!
'file:D:\Users\... seems to be wrong as well

**Comment by Starbuck2010** [comment]
Soory, my mistake, a typo iun my post processors options...
