### ISSUE TITLE
Site Support Request: Twitter Video

### ISSUE THREAD

**Issue by aaronvegh** [rg3/youtube-dl#7489]
```
$ youtube-dl -v -j "https://amp.twimg.com/v/93ad3568-03d2-47b9-a57b-624b88693acd"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'-j', u'https://amp.twimg.com/v/93ad3568-03d2-47b9-a57b-624b88693acd']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.13
[debug] Python version 2.7.10 - Darwin-15.0.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
WARNING: Falling back on generic information extractor.
ERROR: Unsupported URL: https://amp.twimg.com/v/93ad3568-03d2-47b9-a57b-624b88693acd
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1241, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 248, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=etree.TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 237, in _XML
    parser.feed(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: mismatched tag: line 30, column 4
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 661, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1839, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://amp.twimg.com/v/93ad3568-03d2-47b9-a57b-624b88693acd
```

**Comment by RingoTheDog** [comment]
Same video different result....
https://twitter.com/starwars/status/665052190608723968

This twitter link to the video does call the YouTube-dl Twitter extractor but fails with no attribute 'groups'



c:\Transmogrifier>youtube-dl.py -v "https://twitter.com/starwars/status/665052190608723968"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://twitter.com/starwars/status/665052190608723968']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.11.13
[debug] Python version 2.7.5 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-71727-g46778ab, rtmpdump 2.4
[debug] Proxy map: {}
[twitter] 665052190608723968: Downloading webpage
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Transmogrifier\youtube-dl.py\__main__.py", line 19, in <module>
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\__init__.py", line 410, in main
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\__init__.py", line 400, in _real_main
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 1666, in download
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 661, in extract_info
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\common.py", line 290, in extract
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\twitter.py", line 165, in _real_extract
AttributeError: 'NoneType' object has no attribute 'groups'


(maybe a different issue?)

Ringo

**Comment by jaimeMF** [comment]
The original tweet url (https://twitter.com/starwars/status/665052190608723968) will work in the next version.
Like in #7191 I don't see any reason to support the kind of URL you posted. But feel free to expose your opinion if you disagree.
