### ISSUE TITLE
Instagram falls back to generic...

### ISSUE THREAD

**Issue by RingoTheDog** [rg3/youtube-dl#7497]
URL:  https://instagram.com/p/-Cmh1cukG2/

>youtube-dl.py -v "https://instagram.com/p/-Cmh1cukG2/"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://instagram.com/p/-Cmh1cukG2/']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.11.13
[debug] Python version 2.7.5 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-71727-g46778ab, rtmpdump 2.4
[debug] Proxy map: {}
[generic] -Cmh1cukG2: Requesting header
WARNING: Falling back on generic information extractor.
[generic] -Cmh1cukG2: Downloading webpage
[generic] -Cmh1cukG2: Extracting information
[download] Downloading playlist: None
[generic] playlist None: Collected 2 video ids (downloading 2 of them)
[download] Downloading video 1 of 2
[debug] Invoking downloader on u'https://instagram.com/p/-Cmh1cukG2/\\/\\/scontent-ord1-1.cdninstagram.com\\/hphotos-xtp1\\/t50.2886-16\\/12234099_433446366845715_1868829635_n.mp4'
ERROR: unable to download video data: HTTP Error 404: NOT FOUND
Traceback (most recent call last):
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 1598, in process_info
    success = dl(filename, info_dict)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 1540, in dl
    return fd.download(name, info)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\downloader\common.py", line 342, in download
    return self.real_download(filename, info_dict)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\downloader\http.py", line 60, in real_download
    data = self.ydl.urlopen(request)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 1873, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "C:\Python27\lib\urllib2.py", line 410, in open
    response = meth(req, response)
  File "C:\Python27\lib\urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python27\lib\urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "C:\Python27\lib\urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: NOT FOUND

**Comment by RingoTheDog** [comment]
holy crap...3 minutes!!!
NICE!!!
