### ISSUE TITLE
Lynda.com organization login with cookies not working

### ISSUE THREAD

**Issue by jtv7** [rg3/youtube-dl#7500]
I am trying to download videos from Lynda.com, but I keep getting an error.  I downloaded the exact way that I am now about a month ago and everything worked perfectly.
Here are some errors I am getting:

When I first try to start the download:

[lynda:course] 419162: Downloading course JSON
[lynda:course] Logging out

Then:

ERROR: lynda returned error: Session has expired
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 661, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python2.7/site-packages/youtube_dl/extractor/lynda.py", line 122, in _real_extract
    'lynda returned error: %s' % video['Message'], expected=True)
ExtractorError: lynda returned error: Session has expired

I know the session did not expire because I am still logged in with my browser.

**Comment by dstftw** [comment]
Post the **full** output of youtube-dl when run [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).
