### ISSUE TITLE
Error when downloading from comedy central: RegexNotFoundError: Unable to extract mgid

### ISSUE THREAD

**Issue by oskarmurand** [rg3/youtube-dl#7516]
Oskars-MacBook-Pro:South Park 504 oskar$ youtube-dl http://southpark.cc.com/full-episodes/s05e04 --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://southpark.cc.com/full-episodes/s05e04', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.15
[debug] Python version 2.7.10 - Darwin-14.5.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[southpark.cc.com] s05e04: Downloading webpage
ERROR: Unable to extract mgid; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/mtv.py", line 193, in _real_extract
    og_url = self._og_search_video_url(webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 684, in _og_search_video_url
    return self._html_search_regex(regexes, html, name, **kargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 593, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 584, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 661, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/mtv.py", line 209, in _real_extract
    r'embed/(mgid:.+?)["\'&?/]', sm4_embed, 'mgid')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 584, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract mgid; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

---

This is the first video on this site that has had this error.

**Comment by jaimeMF** [comment]
From Spain I get this message in the browser: `We apologize that South Park Studios cannot stream Super Best Friends`, can you play it in a browser?

**Comment by oskarmurand** [comment]
Yes, you are right. I forgot to look at the link. Not a fault of youtube-dl
