### ISSUE TITLE
Can't download some mixcloud shows

### ISSUE THREAD

**Issue by lalinsky** [rg3/youtube-dl#7521]
Downloading [this show](https://www.mixcloud.com/freshlifechurch/moment-maker/) fails with the following error:

```
$ PYTHONPATH=`pwd`  ./bin/youtube-dl --verbose --list-formats 'https://www.mixcloud.com/freshlifechurch/moment-maker/'
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'--list-formats', u'https://www.mixcloud.com/freshlifechurch/moment-maker/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.15
[debug] Git HEAD: bd1512d
[debug] Python version 2.7.9 - Linux-3.19.0-33-generic-x86_64-with-Ubuntu-15.04-vivid
[debug] exe versions: ffmpeg 2.5.8-0ubuntu0.15.04.1, ffprobe 2.5.8-0ubuntu0.15.04.1, rtmpdump 2.4
[debug] Proxy map: {}
[mixcloud] freshlifechurch-moment-maker: Downloading webpage
ERROR: Unable to extract preview url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/lukas/work/youtube-dl/youtube_dl/YoutubeDL.py", line 661, in extract_info
    ie_result = ie.extract(url)
  File "/home/lukas/work/youtube-dl/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/home/lukas/work/youtube-dl/youtube_dl/extractor/mixcloud.py", line 66, in _real_extract
    r'\s(?:data-preview-url|m-preview)="([^"]+)"', webpage, 'preview url')
  File "/home/lukas/work/youtube-dl/youtube_dl/extractor/common.py", line 584, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract preview url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by dstftw** [comment]
It does not work for me in browser either.

**Comment by lalinsky** [comment]
Hm, I can get it to play in browser here. I'll have a look at the code to see what could be wrong.

**Comment by yan12125** [comment]
Mixcloud will be fixed in the next version.
