### ISSUE TITLE
MSNBC has stopped working

### ISSUE THREAD

**Issue by rhinchley** [rg3/youtube-dl#7532]
http://www.msnbc.com/andrea-mitchell-reports/watch/is-the-current-strategy-enough-to-beat-isis--567691331788

[MSNBC] is-the-current-strategy-enough-to-beat-isis--567691331788: Downloading webpage
[ThePlatform] MSNBCEmbeddedOffSite: Downloading webpage
[ThePlatform] MSNBCEmbeddedOffSite: Downloading feed script
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "./you/__main__.py", line 19, in <module>
  File "./you/youtube_dl/__init__.py", line 410, in main
  File "./you/youtube_dl/__init__.py", line 400, in _real_main
  File "./you/youtube_dl/YoutubeDL.py", line 1666, in download
  File "./you/youtube_dl/YoutubeDL.py", line 672, in extract_info
  File "./you/youtube_dl/YoutubeDL.py", line 725, in process_ie_result
  File "./you/youtube_dl/YoutubeDL.py", line 661, in extract_info
  File "./you/youtube_dl/extractor/common.py", line 290, in extract
  File "./you/youtube_dl/extractor/theplatform.py", line 190, in _real_extract
  File "./you/youtube_dl/extractor/common.py", line 441, in _download_webpage
  File "./you/youtube_dl/extractor/common.py", line 348, in _download_webpage_handle
  File "./you/youtube_dl/extractor/common.py", line 329, in _request_webpage
  File "./you/youtube_dl/YoutubeDL.py", line 1873, in urlopen
  File "/usr/local/lib/python2.7/urllib2.py", line 423, in open
    protocol = req.get_type()
  File "/usr/local/lib/python2.7/urllib2.py", line 285, in get_type
    raise ValueError, "unknown url type: %s" % self.__original
ValueError: unknown url type: //assets.adobedtm.com/cd771b0aa897f931a306d7ab6af0d448836b5fd1/satelliteLib-b4a012ca1ff96bd960a7a5db112455f1ce62a52e.js
[ron] ~/scrapecity$ http://www.newsmax.com/Newsfront/barry-mccaffrey-obama-chris-hill-isis/2015/11/16/id/702361/
bash: http://www.newsmax.com/Newsfront/barry-mccaffrey-obama-chris-hill-isis/2015/11/16/id/702361/: No such file or directory
[ron] ~/scrapecity$ you http://www.newsmax.com/Newsfront/barry-mccaffrey-obama-chris-hill-isis/2015/11/16/id/702361/
bash: you: command not found
[ron] ~/scrapecity$ ./you http://www.newsmax.com/Newsfront/barry-mccaffrey-obama-chris-hill-isis/2015/11/16/id/702361/
[generic] 702361: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 702361: Downloading webpage
[generic] 702361: Extracting information
ERROR: Unsupported URL: http://www.newsmax.com/Newsfront/barry-mccaffrey-obama-chris-hill-isis/2015/11/16/id/702361/

**Comment by rhinchley** [comment]
I worked around this (first python keystrokes, know nothing about youtube-dl) after line 436 in youtube_dl/extractor/common.py, function  def _download_webpage,
if not url_or_request[0:4] == 'http':
               url_or_request =  'https:' + url_or_request

I'm sure this is the wrong place to fix it. 

Regards,

Thanks
