### ISSUE TITLE
Unable to extract title

### ISSUE THREAD

**Issue by jajajaime** [rg3/youtube-dl#7544]
```
$ youtube-dl --ignore-errors --verbose https://www.youtube.com/playlist?list=PLDg0b6qfevPvCDeUkcM4N6hNSrYGhbDMU
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--ignore-errors', u'--verbose', u'https://www.youtube.com/playlist?list=PLDg0b6qfevPvCDeUkcM4N6hNSrYGhbDMU']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.15
[debug] Python version 2.7.10 - Darwin-14.5.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[youtube:playlist] PLDg0b6qfevPvCDeUkcM4N6hNSrYGhbDMU: Downloading webpage
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 661, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1644, in _real_extract
    return self._extract_playlist(playlist_id)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1619, in _extract_playlist
    page, 'title')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 593, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 584, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
```

**Comment by balta2ar** [comment]
Same here (my version is couple of days older, but the extraction got broken literally just an hour ago):

```
youtube-dl --verbose -a ../links.txt
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '-a', '../links.txt']
[debug] Batch file urls: ['https://www.youtube.com/playlist?list=PLvJ08ASPN6JPOsN1O91T0uVA-U7jfYBKU']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.10
[debug] Python version 3.5.0 - Linux-4.2.5-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 2.8.2, ffprobe 2.8.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:playlist] PLvJ08ASPN6JPOsN1O91T0uVA-U7jfYBKU: Downloading webpage
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 661, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1644, in _real_extract
    return self._extract_playlist(playlist_id)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1619, in _extract_playlist
    page, 'title')
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 593, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 584, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by jajajaime** [comment]
probably YouTube itself changed something?

**Comment by jaimeMF** [comment]
Thanks for the report, it will work in the next version.

**Comment by KarlBarl** [comment]
Likely that I do not deliver new information with this, but here is my output (download of all videos in the channel was no problem until very recently):

[user@TR 2]$ youtube-dl -v https://www.youtube.com/user/GnosticMedia/videos
[debug] System config: [u'--prefer-free-formats']
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/user/GnosticMedia/videos']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.10.16
[debug] Python version 2.7.8 - Linux-3.18.17-6.pvops.qubes.x86_64-x86_64-with-fedora-21-Twenty_One
[debug] exe versions: none
[debug] Proxy map: {}
[youtube:user] GnosticMedia: Downloading channel page
[youtube:playlist] UU_lvvd3d3K7NgLtWstl6YNg: Downloading webpage
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 660, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 1613, in _real_extract
    return self._extract_playlist(playlist_id)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 1588, in _extract_playlist
    page, 'title')
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 593, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 584, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by yan12125** [comment]
@KarlBarl You're using an out-dated version. (2015.10.16) Follow [update instructions](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) to get the latest version.
