### ISSUE TITLE
Unable to extract title

### ISSUE THREAD

**Issue by hitbox** [rg3/youtube-dl#7554]
Got the following error trying while trying to download. Command I used included.

```
youtube-dl -r 750K 'https://www.youtube.com/playlist?list=PLH4CCskJrtwxEUt5VJS21D3-Sr66kCSro' --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-r', '750K', 'https://www.youtube.com/playlist?list=PLH4CCskJrtwxEUt5VJS21D3-Sr66kCSro', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.10
[debug] Python version 3.5.0 - Linux-4.2.5-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 2.8.2, ffprobe 2.8.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:playlist] PLH4CCskJrtwxEUt5VJS21D3-Sr66kCSro: Downloading webpage
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 661, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1644, in _real_extract
    return self._extract_playlist(playlist_id)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1619, in _extract_playlist
    page, 'title')
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 593, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 584, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.```

**Comment by jaimeMF** [comment]
It's fixed in the last version. See [our FAQ](https://yt-dl.org/update) if you need help updating.
