### ISSUE TITLE
ERROR: Unable to extract title, [youtube]

### ISSUE THREAD

**Issue by CurtisLeeBolin** [rg3/youtube-dl#7556]
YouTube Channel and User downloading isn't working.
https://www.youtube.com/user/SquirrelMonkeyCom
```
$ ~/Projects/youtube-dl/bin/youtube-dl --verbose --continue --format="bestvideo[height<=?720]+bestaudio/best" --audio-format vorbis --embed-subs --embed-thumbnail --add-metadata --merge-output-format mkv --ignore-errors --sub-lang en --write-sub --user-agent "$USER_AGENT" -
-output "%(upload_date)s %(title)s (%(id)s).%(ext)s" https://www.youtube.com/user/SquirrelMonkeyCom                                                                                                                                                                               
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '--continue', '--format=bestvideo[height<=?720]+bestaudio/best', '--audio-format', 'vorbis', '--embed-subs', '--embed-thumbnail', '--add-metadata', '--merge-output-format', 'mkv', '--ignore-errors', '--sub-lang', 'en', '--write-sub', '--user-agent', '', '--output', '%(upload_date)s %(title)s (%(id)s).%(ext)s', 'https://www.youtube.com/user/SquirrelMonkeyCom']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.10
[debug] Python version 3.5.0 - Linux-4.2.5-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 2.8.2, ffprobe 2.8.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:user] SquirrelMonkeyCom: Downloading channel page
[youtube:playlist] UUXA2lepIpHZ24iQU22WgDeA: Downloading webpage
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 661, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1644, in _real_extract
    return self._extract_playlist(playlist_id)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1619, in _extract_playlist
    page, 'title')
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 593, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 584, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by jaimeMF** [comment]
It's fixed in the last version. See [our FAQ](https://yt-dl.org/update) if you need help updating.

**Comment by CurtisLeeBolin** [comment]
I just ran git pull.  The issue is not corrected.

**Comment by dstftw** [comment]
Post the **full** output of youtube-dl when run [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by CurtisLeeBolin** [comment]
```
$ ~/Projects/youtube-dl/bin/youtube-dl --verbose --continue --format="bestvideo[height<=?720]+bestaudio/best" --audio-format vorbis --embed-subs --embed-thumbnail --add-metadata --merge-output-format mkv --ignore-errors --sub-lang en --write-sub --user-agent "$USER_AGENT" --output "%(upload_date)s %(title)s (%(id)s).%(ext)s" https://www.youtube.com/user/SquirrelMonkeyCom
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '--continue', '--format=bestvideo[height<=?720]+bestaudio/best', '--audio-format', 'vorbis', '--embed-subs', '--embed-thumbnail', '--add-metadata', '--merge-output-format', 'mkv', '--ignore-errors', '--sub-lang', 'en', '--write-sub', '--user-agent', '', '--output', '%(upload_date)s %(title)s (%(id)s).%(ext)s', 'https://www.youtube.com/user/SquirrelMonkeyCom']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.10
[debug] Python version 3.5.0 - Linux-4.2.5-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 2.8.2, ffprobe 2.8.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:user] SquirrelMonkeyCom: Downloading channel page
[youtube:playlist] UUXA2lepIpHZ24iQU22WgDeA: Downloading webpage
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 661, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1644, in _real_extract
    return self._extract_playlist(playlist_id)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1619, in _extract_playlist
    page, 'title')
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 593, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 584, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by jaimeMF** [comment]
~/Projects/youtube-dl/bin/youtube-dl is not picking the correct youtube_dl module, it's using the one in /usr/lib/python3.5/site-packages/. [See the instructions for running it](https://github.com/rg3/youtube-dl/blob/741dd8ea65b276997f3eadae43b2879e9a229a80/README.md#developer-instructions).

**Comment by CurtisLeeBolin** [comment]
I see it in the Traceback now.  Sorry
