### ISSUE TITLE
ERROR: Unable to extract title; 

### ISSUE THREAD

**Issue by sleepychild** [rg3/youtube-dl#7558]
openSUSE Tumbleweed
pip installed youtube-dl version 2015.05.15

linux-eqwu:/STORAGE/playout/VIDEO_IN/youtube-dl-19112015 # youtube-dl --verbose --yes-playlist https://www.youtube.com/playlist?list=PLjotfpzP5H4GAiu-knvcdOCiyIKAjM0lg
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'--yes-playlist', u'https://www.youtube.com/playlist?list=PLjotfpzP5H4GAiu-knvcdOCiyIKAjM0lg']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.05.15
[debug] Python version 2.7.10 - Linux-4.2.3-1-default-x86_64-with-SuSE-20151017-x86_64
[debug] exe versions: ffmpeg N-76178-gcdfc61d, ffprobe N-76178-gcdfc61d
[debug] Proxy map: {}
[youtube:playlist] PLjotfpzP5H4GAiu-knvcdOCiyIKAjM0lg: Downloading webpage
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 649, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 273, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 1364, in _real_extract
    return self._extract_playlist(playlist_id)
  File "/usr/local/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 1338, in _extract_playlist
    page, 'title')
  File "/usr/local/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 564, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 555, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by phihag** [comment]
You are using an outdated version of youtube-dl. Support for the new YouTube playlist format has been added in youtube-dl 2015.11.18. See [our FAQ](https://yt-dl.org/update) if you need help updating.
