### ISSUE TITLE
Unable to extract title

### ISSUE THREAD

**Issue by livlab** [rg3/youtube-dl#7559]
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'https://www.youtube.com/playlist?list=PLsT0vUE-wpXMlKe7rf49uKUhzWphM2HXq', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.10.24
[debug] Git HEAD: 18c483f
[debug] Python version 2.7.10 - Darwin-15.0.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[youtube:playlist] PLsT0vUE-wpXMlKe7rf49uKUhzWphM2HXq: Downloading webpage
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 661, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 291, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 1633, in _real_extract
    return self._extract_playlist(playlist_id)
  File "/usr/local/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 1608, in _extract_playlist
    page, 'title')
  File "/usr/local/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 594, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 585, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by phihag** [comment]
You are using an outdated version of youtube-dl. Support for the new YouTube playlist format has been added in youtube-dl 2015.11.18. See [our FAQ](https://yt-dl.org/update) if you need help updating.
