### ISSUE TITLE
Playlist dowload issue

### ISSUE THREAD

**Issue by Kordump** [rg3/youtube-dl#7562]
```
me@here  % youtube-dl "https://www.youtube.com/watch?v=JnIKLRA31nw&list=PLa4yK1a5RlqKBY-MhBOT9Obu0vQMjTGiA&index=1" --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=JnIKLRA31nw&list=PLa4yK1a5RlqKBY-MhBOT9Obu0vQMjTGiA&index=1', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.10.24
[debug] Python version 3.5.0 - Linux-4.2.5-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 2.8.1, ffprobe 2.8.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:playlist] Downloading playlist PLa4yK1a5RlqKBY-MhBOT9Obu0vQMjTGiA - add --no-playlist to just download video JnIKLRA31nw
[youtube:playlist] PLa4yK1a5RlqKBY-MhBOT9Obu0vQMjTGiA: Downloading webpage
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 661, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 291, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1633, in _real_extract
    return self._extract_playlist(playlist_id)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1608, in _extract_playlist
    page, 'title')
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 594, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 585, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by phihag** [comment]
You are using an outdated version of youtube-dl. Support for the new YouTube playlist format has been added in youtube-dl 2015.11.18. See [our FAQ](https://yt-dl.org/update) if you need help updating.
