### ISSUE TITLE
RegexNotFoundError when trying to download a playlist

### ISSUE THREAD

**Issue by fermuch** [rg3/youtube-dl#7564]
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=4WIyrvRYYhg&list=PLtteaOGaVRvR420r4yEqRFuOLYBC-XjWz']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.15
[debug] Python version 3.3.5 - Linux-3.19.3-1~exp1-x86_64-Intel-R-_Core-TM-_i5-2430M_CPU_@_2.40GHz-with-gentoo-2.2.0
[debug] exe versions: ffmpeg 2.8.1, ffprobe 2.8.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:playlist] Downloading playlist PLtteaOGaVRvR420r4yEqRFuOLYBC-XjWz - add --no-playlist to just download video 4WIyrvRYYhg
[youtube:playlist] PLtteaOGaVRvR420r4yEqRFuOLYBC-XjWz: Downloading webpage
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib64/python3.3/site-packages/youtube_dl/YoutubeDL.py", line 661, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib64/python3.3/site-packages/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/lib64/python3.3/site-packages/youtube_dl/extractor/youtube.py", line 1644, in _real_extract
    return self._extract_playlist(playlist_id)
  File "/usr/lib64/python3.3/site-packages/youtube_dl/extractor/youtube.py", line 1619, in _extract_playlist
    page, 'title')
  File "/usr/lib64/python3.3/site-packages/youtube_dl/extractor/common.py", line 593, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/lib64/python3.3/site-packages/youtube_dl/extractor/common.py", line 584, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by jaimeMF** [comment]
You are using an outdated version of youtube-dl. Support for the new YouTube playlist format has been added in youtube-dl 2015.11.18. See [our FAQ](https://yt-dl.org/update) if you need help updating.
