### ISSUE TITLE
EOFError

### ISSUE THREAD

**Issue by volcs0** [rg3/youtube-dl#7567]
Am getting an EOFError with Youtube downloads. I tried some other sites (e.g., SoundCloud), which worked.

Here is the output. I'm guessing this is a Python problem? Advice is appreciated.

$ youtube-dl --verbose --title https://www.youtube.com/watch?v=Zx4Hjq6KwO0
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'--title', u'https://www.youtube.com/watch?v=Zx4Hjq6KwO0']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.19
[debug] Python version 2.7.10 - Darwin-15.0.0-x86_64-i386-64bit
Traceback (most recent call last):
  File "/Users/volcs0/anaconda/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Users/volcs0/anaconda/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 410, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 377, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 341, in __init__
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1912, in print_debug_header
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 51, in get_versions
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 35, in __init__
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 91, in _determine_executables
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 91, in <genexpr>
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1502, in get_exe_version
  File "/Users/volcs0/anaconda/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/Users/volcs0/anaconda/lib/python2.7/subprocess.py", line 1334, in _execute_child
    child_exception = pickle.loads(data)
  File "/Users/volcs0/anaconda/lib/python2.7/pickle.py", line 1382, in loads
    return Unpickler(file).load()
  File "/Users/volcs0/anaconda/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/Users/volcs0/anaconda/lib/python2.7/pickle.py", line 880, in load_eof
    raise EOFError
EOFError
$

**Comment by yan12125** [comment]
I guess you've encountered similar problems as #6840. Check comments there.
