### ISSUE TITLE
Unable to extract title

### ISSUE THREAD

**Issue by bnomis** [rg3/youtube-dl#7572]
```shell
$ youtube-dl --verbose 'https://www.youtube.com/playlist?list=PLZdCLR02grLrl5ie970A24kvti21hGiOf'
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://www.youtube.com/playlist?list=PLZdCLR02grLrl5ie970A24kvti21hGiOf']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.15
[debug] Python version 2.7.10 - Darwin-15.0.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.8.2, ffprobe 2.8.2
[debug] Proxy map: {}
[youtube:playlist] PLZdCLR02grLrl5ie970A24kvti21hGiOf: Downloading webpage
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/opt/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 661, in extract_info
    ie_result = ie.extract(url)
  File "/opt/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/opt/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1644, in _real_extract
    return self._extract_playlist(playlist_id)
  File "/opt/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1619, in _extract_playlist
    page, 'title')
  File "/opt/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 593, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/opt/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 584, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by yan12125** [comment]
You're using an slightly old version (2015.11.15). Please update to at least 2015.11.19. Have a look at [update instructions](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) if you have encountered problems.
