### ISSUE TITLE
ERROR: Unable to extract title

### ISSUE THREAD

**Issue by veedel-astro** [rg3/youtube-dl#7575]
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 661, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1644, in _real_extract
    return self._extract_playlist(playlist_id)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1619, in _extract_playlist
    page, 'title')
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 593, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 584, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug

**Comment by yan12125** [comment]
Though lack of sufficient information, I guess you're using an out-dated version. Follow [update instructions](https://github.com/rg3/youtube-dl/#how-do-i-update-youtube-dl) to upgrade to the latest version (2015.11.19) should fix the problem. If problem is still, post the [full verbose log](https://github.com/rg3/youtube-dl/#bugs) here.
