### ISSUE TITLE
[infoq] Add support for InfoQ Chinese-localized version

### ISSUE THREAD

**Issue by NoviceLive** [rg3/youtube-dl#7576]
# Description

Hi, your current InfoQ extractor does not support InfoQ China.

Chinese-localized InfoQ differs from its brothers, say Fr, Jp and Br, and in fact youtube-dl works like a charm for all InfoQ sites except the Chinese one, which still uses FLV videos.

I inspected the HTML source and found some interesting Javascript. But since I can't debug Javascript, I can't analyze them, and thus unable to update your extractor. Hope you can :).

# Output
```
./youtube_dl/__main__.py http://www.infoq.com/cn/presentations/openstack-continued-delivery --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://www.infoq.com/cn/presentations/openstack-continued-delivery', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.19
[debug] Git HEAD: 67446fd
[debug] Python version 3.5.0 - Linux-4.2.5-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 2.8.2, ffprobe 2.8.2, rtmpdump 2.4
[debug] Proxy map: {}
[InfoQ] openstack-continued-delivery: Downloading webpage
ERROR: Unable to extract encoded id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/novicelive/refsrc/youtube-dl.git/youtube_dl/YoutubeDL.py", line 661, in extract_info
    ie_result = ie.extract(url)
  File "/home/novicelive/refsrc/youtube-dl.git/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/home/novicelive/refsrc/youtube-dl.git/youtube_dl/extractor/infoq.py", line 41, in _real_extract
    r"jsclassref\s*=\s*'([^']*)'", webpage, 'encoded id')
  File "/home/novicelive/refsrc/youtube-dl.git/youtube_dl/extractor/common.py", line 584, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract encoded id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by yan12125** [comment]
Chinese version InfoQ will be supported in the next version. Thanks for the report.
