### ISSUE TITLE
Download fails for some videos with "ERROR: Signature extraction failed"

### ISSUE THREAD

**Issue by isameer** [rg3/youtube-dl#7592]
Hi, I get the error below when trying to download some videos. Output with the `--verbose` flag:

```
$ youtube-dl --verbose "https://www.youtube.com/watch?v=hLQl3WQQoQ0"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://www.youtube.com/watch?v=hLQl3WQQoQ0']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.10.09
[debug] Python version 2.7.6 - Linux-3.19.0-25-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.18-6, avprobe 9.18-6
[debug] Proxy map: {}
[youtube] hLQl3WQQoQ0: Downloading webpage
[youtube] hLQl3WQQoQ0: Downloading video info webpage
[youtube] hLQl3WQQoQ0: Extracting video information
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sur
e you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call
youtube-dl with the --verbose flag and include its complete output.
[youtube] {22} signature length 43.40, html5 player None
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 771, in _decryp
t_signature
    video_id, player_url, s
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 663, in _extrac
t_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
ExtractorError: Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vflCIicNM/base.js
'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; se
e  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and
 include its complete output.
 (caused by ExtractorError(u"Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vflC
IicNM/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the lates
t version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --ver
bose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure $o call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 771, in _decry$t_signature
    video_id, player_url, s
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 663, in _extra$t_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; se
e  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and
 include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 660, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 1299, in _real_
extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 781, in _decryp
t_signature
    'Signature extraction failed: ' + tb, cause=e)
ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 771, in _decryp
t_signature
    video_id, player_url, s
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 663, in _extrac
t_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
ExtractorError: Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vflCIicNM/base.js
'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; se
e  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and
 include its complete output.
 (caused by ExtractorError(u"Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vflC
IicNM/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the lates
t version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --ver
bose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . M
ake sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure t
o call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.
