### ISSUE TITLE
The Daily Show download works for only one segment at a time

### ISSUE THREAD

**Issue by 6461** [rg3/youtube-dl#760]
TDS has four segments (or acts), and therefor one needs to run youtube-dl four times.

[comedycentral] mon-march-25-2013-peter-dinklage: Extracting information
[comedycentral] mon-march-25-2013-peter-dinklage: Downloading show index
[comedycentral] mon-march-25-2013-peter-dinklage: Downloading configuration for 424701
[comedycentral] mon-march-25-2013-peter-dinklage: Downloading configuration for 424702
[comedycentral] mon-march-25-2013-peter-dinklage: Downloading configuration for 424703
[comedycentral] mon-march-25-2013-peter-dinklage: Downloading configuration for 424704
[download] 424701.mp4 has already been downloaded
[download] Resuming download at byte 3201592
[download] Unable to resume
[download] Destination: 424702.mp4
[download] 100.0% of 148.63M at  726.09k/s ETA 00:00
Traceback (most recent call last):
  File "__main__.py", line 17, in <module>
  File "youtube_dl\__init__.pyo", line 516, in main
  File "youtube_dl\__init__.pyo", line 500, in _real_main
  File "youtube_dl\FileDownloader.pyo", line 525, in download
  File "youtube_dl\FileDownloader.pyo", line 468, in process_info
  File "youtube_dl\FileDownloader.pyo", line 790, in _do_download
  File "youtube_dl\FileDownloader.pyo", line 279, in try_utime
  File "youtube_dl\utils.pyo", line 349, in timeconvert
  File "email\_parseaddr.pyo", line 158, in mktime_tz
OverflowError: mktime argument out of range

The version I was using:
[debug] youtube-dl version 2013.02.25

**Comment by yan12125** [comment]
I guess the original URL is http://www.thedailyshow.com/watch/mon-march-25-2013/peter-dinklage? It now redirects to http://www.cc.com/shows/the-daily-show-with-trevor-noah. Unfortunately, Comedy Central playlists are not supported yet. Please move to #10003 for further discussion.
