### ISSUE TITLE
Vimeo download fail

### ISSUE THREAD

**Issue by onabil** [rg3/youtube-dl#7601]
First of all many thanks for this useful tool that I'm enjoining for more than 2 years now.
My issue is when downloading a video using this command:
```youtube-dl --verbose --title --format 18 --no-progress "https://vimeo.com/99011308" > /tmp/out.log 2>/tmp/err.log```
and here is my out.log file:
```[vimeo] 99011308: Downloading webpage
[vimeo] 99011308: Extracting information
[vimeo] 99011308: Downloading webpage```
and my err.log file:
```[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'--title', u'--format', u'18', u'--no-progress', u'https://vimeo.com/99011308']
[debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8
[debug] youtube-dl version 2015.09.09
[debug] Python version 2.7.6 - Linux-3.13.0-68-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: none
[debug] Proxy map: {}
ERROR: No known codec found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/vimeo.py", line 358, in _real_extract
    view_count = int(self._search_regex(r'UserPlays:(\d+)', webpage, 'view count'))
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 575, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract view count; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 660, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 287, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/vimeo.py", line 401, in _real_extract
    raise ExtractorError('No known codec found')
ExtractorError: No known codec found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.```

I installed youtube-dl using pip:
 ```user@lnx-pc:~$ sudo pip install youtube-dl
sudo: unable to resolve host lnx-pc
Downloading/unpacking youtube-dl
  Downloading youtube_dl-2015.11.21-py2.py3-none-any.whl (1.1MB): 1.1MB downloaded
Installing collected packages: youtube-dl
Successfully installed youtube-dl```.

**Comment by onabil** [comment]
I think I'm not able to download any video; I'm having the same issue with a youtube video. I'll check my installation deeply first.

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.

**Comment by onabil** [comment]
yes, you are right, I was using an outdated version.
Many thanks
