### ISSUE TITLE
YouTube ExtractorError 

### ISSUE THREAD

**Issue by hut8** [rg3/youtube-dl#7616]
Please forgive me if this is a duplicate; there are quite a few open issues but searching for "unable to extract html5" yielded some that were close (like #4835, who was trying to set cookies manually). 

% youtube-dl --verbose https://www.youtube.com/watch\?v\=pXRviuL6vMY

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=pXRviuL6vMY']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.10.16
[debug] Python version 3.4.3 - Linux-3.13.0-43-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.18-6, avprobe 9.18-6, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] pXRviuL6vMY: Downloading webpage
[youtube] pXRviuL6vMY: Downloading video info webpage
[youtube] pXRviuL6vMY: Extracting video information
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.or
g/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {22} signature length 43.40, html5 player None
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/youtube_dl/extractor/youtube.py", line 771, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/lib/python3.4/dist-packages/youtube_dl/extractor/youtube.py", line 663, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
youtube_dl.utils.ExtractorError: Cannot identify player 'https://s.ytimg.com/yts/jsbin/player-en_US-vflCIicNM/base.js'; please report this issue on https://yt
-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Cannot identify player 'https://s.ytimg.com/yts/jsbin/player-en_US-vflCIicNM/base.js'; please report this issue on https://yt-dl.o
rg/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/youtube_dl/extractor/youtube.py", line 771, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/lib/python3.4/dist-packages/youtube_dl/extractor/youtube.py", line 663, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
youtube_dl.utils.ExtractorError: Cannot identify player 'https://s.ytimg.com/yts/jsbin/player-en_US-vflCIicNM/base.js'; please report this issue on https://yt
-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag
and include its complete output.
```

I'll try to debug it myself a bit tonight.

**Comment by phihag** [comment]
You are using an outdated version of youtube-dl. See [our FAQ](https://yt-dl.org/update) if you need help updating.

**Comment by hut8** [comment]
@phihag thanks  and sorry about that. I actually had done:

```bash
sudo apt-get remove youtube-dl
pip install -U youtube-dl
```

but apparently I had installed it originally with Python 3 using `pip3`, so I was upgrading the wrong installation.
