### ISSUE TITLE
Youtube VEVO Video not work

### ISSUE THREAD

**Issue by ziko8jp** [rg3/youtube-dl#7623]
E:\work>youtube-dl.exe --verbose -g https://www.youtube.com/watch?v=Q33cuBXuY4s
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'-g', u'https://www.youtube.com/watch?v=Q33cuBXuY4s']
[debug] Encodings: locale cp932, fs mbcs, out cp932, pref cp932
[debug] youtube-dl version 2015.11.23
[debug] Python version 2.7.10 - Windows-7-6.1.7600
[debug] exe versions: none
[debug] Proxy map: {}
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 856, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 783, in _extract_signature_function
  File "youtube_dl\extractor\youtube.pyo", line 835, in <lambda>
  File "youtube_dl\jsinterp.pyo", line 254, in resf
  File "youtube_dl\jsinterp.pyo", line 55, in interpret_statement
  File "youtube_dl\jsinterp.pyo", line 135, in interpret_expression
  File "youtube_dl\jsinterp.pyo", line 220, in extract_object
AttributeError: 'NoneType' object has no attribute 'group'
 (caused by AttributeError("'NoneType' object has no attribute 'group'",)); please report this issue on https://yt-dl.org/bug . Make sure yo
u are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete
output.
Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 856, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 783, in _extract_signature_function
  File "youtube_dl\extractor\youtube.pyo", line 835, in <lambda>
  File "youtube_dl\jsinterp.pyo", line 254, in resf
  File "youtube_dl\jsinterp.pyo", line 55, in interpret_statement
  File "youtube_dl\jsinterp.pyo", line 135, in interpret_expression
  File "youtube_dl\jsinterp.pyo", line 220, in extract_object
AttributeError: 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 663, in extract_info
  File "youtube_dl\extractor\common.pyo", line 290, in extract
  File "youtube_dl\extractor\youtube.pyo", line 1410, in _real_extract
  File "youtube_dl\extractor\youtube.pyo", line 866, in _decrypt_signature
ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 856, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 783, in _extract_signature_function
  File "youtube_dl\extractor\youtube.pyo", line 835, in <lambda>
  File "youtube_dl\jsinterp.pyo", line 254, in resf
  File "youtube_dl\jsinterp.pyo", line 55, in interpret_statement
  File "youtube_dl\jsinterp.pyo", line 135, in interpret_expression
  File "youtube_dl\jsinterp.pyo", line 220, in extract_object
AttributeError: 'NoneType' object has no attribute 'group'
 (caused by AttributeError("'NoneType' object has no attribute 'group'",)); please report this issue on https://yt-dl.org/bug . Make sure yo
u are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete
output.

E:\work>

**Comment by phihag** [comment]
Thank you for the report. I believe this issue to be fixed in youtube-dl 2015.11.24 and newer. See [our FAQ](https://yt-dl.org/update) if you need help updating.

**Comment by ziko8jp** [comment]
Thank you.
