### ISSUE TITLE
youtube error

### ISSUE THREAD

**Issue by bstoked** [rg3/youtube-dl#7624]
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 856, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 783, in _extract_signature_function
    cache_res = res(test_string)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 835, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 254, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 55, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 135, in interpret_expression
    self._objects[variable] = self.extract_object(variable)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 220, in extract_object
    fields = obj_m.group('fields')
AttributeError: 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 663, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1410, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 866, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 856, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 783, in _extract_signature_function
    cache_res = res(test_string)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 835, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 254, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 55, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 135, in interpret_expression
    self._objects[variable] = self.extract_object(variable)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 220, in extract_object
    fields = obj_m.group('fields')
AttributeError: 'NoneType' object has no attribute 'group'
 (caused by AttributeError("'NoneType' object has no attribute 'group'",));

**Comment by phihag** [comment]
Please post the entire output you get when you run youtube-dl with the `-v` option. It should start with something along the lines of `[debug] System config: []`. Without this output, we cannot diagnose the problem and therefore cannot help you.

**Comment by netch80** [comment]
My output for the same final strings:

Script started on Tue Nov 24 08:25:24 2015
command: yt --verbose https://www.youtube.com/watch?v=iCGM6sRopqE&feature=youtu.be
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-c', u'-f', u'37/85/35/22/18', u'-o', u'%(id)s--%(title)s.%(format_id)s.%(ext)s', u'--verbose', u'https://www.youtube.com/watch?v=iCGM6sRopqE&feature=youtu.be']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.23
[debug] Python version 2.7.10 - FreeBSD-10.2-RELEASE-p5-amd64-64bit-ELF
[debug] exe versions: ffmpeg 2.8.2, ffprobe 2.8.2
[debug] Proxy map: {}
[youtube] iCGM6sRopqE: Downloading webpage
[youtube] iCGM6sRopqE: Downloading video info webpage
[youtube] iCGM6sRopqE: Extracting video information
[youtube] {22} signature length 49.43, html5 player en_US-vflUpjAy9
[youtube] iCGM6sRopqE: Downloading player https://s.ytimg.com/yts/jsbin/player-en_US-vflUpjAy9/base.js
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/var2/homes/netch/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 856, in _decrypt_signature
    video_id, player_url, s
  File "/var2/homes/netch/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 783, in _extract_signature_function
    cache_res = res(test_string)
  File "/var2/homes/netch/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 835, in <lambda>
    return lambda s: initial_function([s])
  File "/var2/homes/netch/bin/youtube-dl/youtube_dl/jsinterp.py", line 254, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "/var2/homes/netch/bin/youtube-dl/youtube_dl/jsinterp.py", line 55, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/var2/homes/netch/bin/youtube-dl/youtube_dl/jsinterp.py", line 135, in interpret_expression
    self._objects[variable] = self.extract_object(variable)
  File "/var2/homes/netch/bin/youtube-dl/youtube_dl/jsinterp.py", line 220, in extract_object
    fields = obj_m.group('fields')
AttributeError: 'NoneType' object has no attribute 'group'
 (caused by AttributeError("'NoneType' object has no attribute 'group'",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/var2/homes/netch/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 856, in _decrypt_signature
    video_id, player_url, s
  File "/var2/homes/netch/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 783, in _extract_signature_function
    cache_res = res(test_string)
  File "/var2/homes/netch/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 835, in <lambda>
    return lambda s: initial_function([s])
  File "/var2/homes/netch/bin/youtube-dl/youtube_dl/jsinterp.py", line 254, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "/var2/homes/netch/bin/youtube-dl/youtube_dl/jsinterp.py", line 55, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/var2/homes/netch/bin/youtube-dl/youtube_dl/jsinterp.py", line 135, in interpret_expression
    self._objects[variable] = self.extract_object(variable)
  File "/var2/homes/netch/bin/youtube-dl/youtube_dl/jsinterp.py", line 220, in extract_object
    fields = obj_m.group('fields')
AttributeError: 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/var2/homes/netch/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 663, in extract_info
    ie_result = ie.extract(url)
  File "/var2/homes/netch/bin/youtube-dl/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/var2/homes/netch/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1410, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/var2/homes/netch/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 866, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/var2/homes/netch/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 856, in _decrypt_signature
    video_id, player_url, s
  File "/var2/homes/netch/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 783, in _extract_signature_function
    cache_res = res(test_string)
  File "/var2/homes/netch/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 835, in <lambda>
    return lambda s: initial_function([s])
  File "/var2/homes/netch/bin/youtube-dl/youtube_dl/jsinterp.py", line 254, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "/var2/homes/netch/bin/youtube-dl/youtube_dl/jsinterp.py", line 55, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/var2/homes/netch/bin/youtube-dl/youtube_dl/jsinterp.py", line 135, in interpret_expression
    self._objects[variable] = self.extract_object(variable)
  File "/var2/homes/netch/bin/youtube-dl/youtube_dl/jsinterp.py", line 220, in extract_object
    fields = obj_m.group('fields')
AttributeError: 'NoneType' object has no attribute 'group'
 (caused by AttributeError("'NoneType' object has no attribute 'group'",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


Script done on Tue Nov 24 08:25:26 2015

"yt" is:
$ cat ~/bin/yt
#!/bin/sh
exec ~/bin/youtube-dl -c -f 37/85/35/22/18 \
        -o "%(id)s--%(title)s.%(format_id)s.%(ext)s" \
        "$@"

system is:
$ uname -mrs
FreeBSD 10.2-RELEASE-p5 amd64

Python is: Python 2.7.10 (from ports)

**Comment by bstoked** [comment]
Seems to be working when I remove the https. Please close.

**Comment by netch80** [comment]
NOT fixed for me with changing https to http, please consider again.

**Comment by yan12125** [comment]
Duplicate of #7623

**Comment by phihag** [comment]
Thank you for the report. I believe this issue to be fixed in youtube-dl 2015.11.24 and newer. See [our FAQ](https://yt-dl.org/update) if you need help updating.
