### ISSUE TITLE
Signature Extraction Failed On YouTube

### ISSUE THREAD

**Issue by brennani** [rg3/youtube-dl#7629]
>youtube-dl -o "Written Emotions.mp4" -f mp4 https://www.youtube.com/watch?v=CEsV2z1ymh8 --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-o', u'Written Emotions.mp4', u'-x', u'-f', u'mp4'
, u'https://www.youtube.com/watch?v=CEsV2z1ymh8', u'--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.11.15
[debug] Python version 2.7.10 - Windows-8-6.2.9200
[debug] exe versions: ffmpeg N-76250-g7c8fcbb, ffprobe N-76250-g7c8fcbb
[debug] Proxy map: {}
[youtube] CEsV2z1ymh8: Downloading webpage
[youtube] CEsV2z1ymh8: Downloading video info webpage
[youtube] CEsV2z1ymh8: Extracting video information
[youtube] {22} signature length 49.43, html5 player en_US-vflUpjAy9
[youtube] CEsV2z1ymh8: Downloading player https://s.ytimg.com/yts/jsbin/player-e
n_US-vflUpjAy9/base.js
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 817, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 744, in _extract_signature_funct
ion
  File "youtube_dl\extractor\youtube.pyo", line 796, in <lambda>
  File "youtube_dl\jsinterp.pyo", line 254, in resf
  File "youtube_dl\jsinterp.pyo", line 55, in interpret_statement
  File "youtube_dl\jsinterp.pyo", line 135, in interpret_expression
  File "youtube_dl\jsinterp.pyo", line 220, in extract_object
AttributeError: 'NoneType' object has no attribute 'group'
 (caused by AttributeError("'NoneType' object has no attribute 'group'",)); plea
se report this issue on https://yt-dl.org/bug . Make sure you are using the late
st version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the
--verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 817, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 744, in _extract_signature_funct
ion
  File "youtube_dl\extractor\youtube.pyo", line 796, in <lambda>
  File "youtube_dl\jsinterp.pyo", line 254, in resf
  File "youtube_dl\jsinterp.pyo", line 55, in interpret_statement
  File "youtube_dl\jsinterp.pyo", line 135, in interpret_expression
  File "youtube_dl\jsinterp.pyo", line 220, in extract_object
AttributeError: 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 661, in extract_info
  File "youtube_dl\extractor\common.pyo", line 290, in extract
  File "youtube_dl\extractor\youtube.pyo", line 1356, in _real_extract
  File "youtube_dl\extractor\youtube.pyo", line 827, in _decrypt_signature
ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 817, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 744, in _extract_signature_funct
ion
  File "youtube_dl\extractor\youtube.pyo", line 796, in <lambda>
  File "youtube_dl\jsinterp.pyo", line 254, in resf
  File "youtube_dl\jsinterp.pyo", line 55, in interpret_statement
  File "youtube_dl\jsinterp.pyo", line 135, in interpret_expression
  File "youtube_dl\jsinterp.pyo", line 220, in extract_object
AttributeError: 'NoneType' object has no attribute 'group'
 (caused by AttributeError("'NoneType' object has no attribute 'group'",)); plea
se report this issue on https://yt-dl.org/bug . Make sure you are using the late
st version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the
--verbose flag and include its complete output.

**Comment by phihag** [comment]
You are using an outdated version of youtube-dl. See [our FAQ](https://yt-dl.org/update) if you need help updating.
