### ISSUE TITLE
:ytwatchlater - ExtractorError: The playlist doesn't exist or is private

### ISSUE THREAD

**Issue by rschaten** [rg3/youtube-dl#7634]
I get the following error when trying do download the watch later list:
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'--username', u'PRIVATE', u':ytwatchlater']
Type account password and press [Return]: 
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
[debug] youtube-dl version 2015.11.24
[debug] Python version 2.7.6 - Linux-2.6.32-37-pve-i686-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.18-6, avprobe 9.18-6, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:watchlater] Downloading login page
[youtube:watchlater] Logging in
[youtube:watchlater] WL: Downloading webpage
ERROR: The playlist doesn't exist or is private, use --username or --netrc to access it.
Traceback (most recent call last):
  File "/home/rschaten/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 663, in extract_info
    ie_result = ie.extract(url)
  File "/home/rschaten/bin/youtube-dl/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/home/rschaten/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1993, in _real_extract
    return self._extract_playlist('WL')
  File "/home/rschaten/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1661, in _extract_playlist
    expected=True)
ExtractorError: The playlist doesn't exist or is private, use --username or --netrc to access it.
```
I call it using my credentials, everything worked fine until about a week ago.

**Comment by rschaten** [comment]
When I deliberately give a wrong password I get another error message (`ExtractorError: Please use your account password and a two-factor code instead of an application-specific password.`), so I think the credentials are OK.

**Comment by rschaten** [comment]
Oh, and when I dump the page content, I see that yt-download actually gets a page with content like `Sign in now to see your channels and recommendations!` and `The playlist does not exist.`.

**Comment by rschaten** [comment]
Argh! After several days of struggling with this, I find the simple solution. Within minutes after opening the ticket, of course. :-(
I got "A privacy reminder from Google". So I logged out of YT, and back in. After clicking away the info message, yt-download worked just like always.
Sorry for bothering you!
