### ISSUE TITLE
Unable to extract title

### ISSUE THREAD

**Issue by jd1008** [rg3/youtube-dl#7636]
youtube-dl -ckli --verbose "https://www.youtube.com/watch?v=FkEjY-viVvY&list=PLMm42O4YsWPP3NtJbw7oHeF3a5fr8bh9l"
[debug] System config: [u'--prefer-free-formats']
[debug] User config: []
[debug] Command-line args: [u'-ckli', u'--verbose', u'https://www.youtube.com/watch?v=FkEjY-viVvY&list=PLMm42O4YsWPP3NtJbw7oHeF3a5fr8bh9l']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.10.16
[debug] Python version 2.7.10 - Linux-4.2.6-200.fc22.x86_64-x86_64-with-fedora-22-Twenty_Two
[debug] exe versions: ffmpeg N-51556-ge278500, ffprobe N-51556-ge278500
[debug] Proxy map: {}
[youtube:playlist] Downloading playlist PLMm42O4YsWPP3NtJbw7oHeF3a5fr8bh9l - add --no-playlist to just download video FkEjY-viVvY
[youtube:playlist] PLMm42O4YsWPP3NtJbw7oHeF3a5fr8bh9l: Downloading webpage
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 660, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 1613, in _real_extract
    return self._extract_playlist(playlist_id)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 1588, in _extract_playlist
    page, 'title')
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 593, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 584, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by stevenschlansker** [comment]
Same here.

**Comment by reasonset** [comment]
Me too.

	$ youtube-dl --verbose --write-info-json --id -f bestvideo+bestaudio --fixup detect_or_warn 'https://www.youtube.com/user/disneytsumutsumu/videos'
	[debug] System config: []
	[debug] User config: []
	[debug] Command-line args: ['--verbose', '--write-info-json', '--id', '-f', 'bestvideo+bestaudio', '--fixup', 'detect_or_warn', 'https://www.youtube.com/user/disneytsumutsumu/videos']
	[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
	[debug] youtube-dl version 2015.11.10
	[debug] Python version 3.5.0 - Linux-4.3.0-1-MANJARO-x86_64-with-glibc2.3.4
	[debug] exe versions: ffmpeg 2.8.2, ffprobe 2.8.2, rtmpdump 2.4
	[debug] Proxy map: {}
	[youtube:user] disneytsumutsumu: Downloading channel page
	[youtube:playlist] UUojKq7cKcLiFSJD9ADuLlGw: Downloading webpage
	ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
	Traceback (most recent call last):
	  File "/usr/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 661, in extract_info
	    ie_result = ie.extract(url)
	  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 290, in extract
	    return self._real_extract(url)
	  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1644, in _real_extract
	    return self._extract_playlist(playlist_id)
	  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1619, in _extract_playlist
	    page, 'title')
	  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 593, in _html_search_regex
	    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
	  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 584, in _search_regex
	    raise RegexNotFoundError('Unable to extract %s' % _name)
	youtube_dl.utils.RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by yan12125** [comment]
You are using an outdated version. Please [update to the latest version](https://github.com/rg3/youtube-dl#how-do-i-update-youtube-dl). Feel free to open a new issue if the problem is still in version 2015.11.24
