### ISSUE TITLE
Signature extraction failed

### ISSUE THREAD

**Issue by igel-kun** [rg3/youtube-dl#7637]
youtube-dl 'https://www.youtube.com/watch?v=_O2N4xwIzrw' --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'https://www.youtube.com/watch?v=_O2N4xwIzrw', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.21
[debug] Python version 2.7.10 - Linux-3.17.8-aufs-r1-x86_64-Intel-R-_Core-TM-_i5-4210U_CPU_@_1.70GHz-with-gentoo-2.2
[debug] exe versions: avconv 11.3, avprobe 11.3, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] _O2N4xwIzrw: Downloading webpage
[youtube] _O2N4xwIzrw: Downloading video info webpage
[youtube] _O2N4xwIzrw: Extracting video information
[youtube] {43} signature length 49.43, html5 player en_US-vflUpjAy9
[youtube] _O2N4xwIzrw: Downloading player https://s.ytimg.com/yts/jsbin/player-en_US-vflUpjAy9/base.js
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 828, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 755, in _extract_signature_function
    cache_res = res(test_string)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 807, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/lib64/python2.7/site-packages/youtube_dl/jsinterp.py", line 254, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/jsinterp.py", line 55, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/jsinterp.py", line 135, in interpret_expression
    self._objects[variable] = self.extract_object(variable)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/jsinterp.py", line 220, in extract_object
    fields = obj_m.group('fields')
AttributeError: 'NoneType' object has no attribute 'group'
 (caused by AttributeError("'NoneType' object has no attribute 'group'",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 828, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 755, in _extract_signature_function
    cache_res = res(test_string)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 807, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/lib64/python2.7/site-packages/youtube_dl/jsinterp.py", line 254, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/jsinterp.py", line 55, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/jsinterp.py", line 135, in interpret_expression
    self._objects[variable] = self.extract_object(variable)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/jsinterp.py", line 220, in extract_object
    fields = obj_m.group('fields')
AttributeError: 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 661, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 1367, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 838, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 828, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 755, in _extract_signature_function
    cache_res = res(test_string)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 807, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/lib64/python2.7/site-packages/youtube_dl/jsinterp.py", line 254, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/jsinterp.py", line 55, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/jsinterp.py", line 135, in interpret_expression
    self._objects[variable] = self.extract_object(variable)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/jsinterp.py", line 220, in extract_object
    fields = obj_m.group('fields')
AttributeError: 'NoneType' object has no attribute 'group'
 (caused by AttributeError("'NoneType' object has no attribute 'group'",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

it's a gentoo system with 
 % youtube-dl --version
2015.11.21

(the song is freaking awesome by the way ^^)

**Comment by yan12125** [comment]
You are using an out-dated version. Please update to the latest version (2015.11.24). Check [this FAQ](https://github.com/rg3/youtube-dl#how-do-i-update-youtube-dl) on how to update.
