### ISSUE TITLE
Signature extraction failed

### ISSUE THREAD

**Issue by CapitanCode** [rg3/youtube-dl#7638]
instantmusic -q -s Nightstep - Radioactive
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 828, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 755, in _extract_signature_function
    cache_res = res(test_string)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 807, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 254, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 55, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 135, in interpret_expression
    self._objects[variable] = self.extract_object(variable)
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 220, in extract_object
    fields = obj_m.group('fields')
AttributeError: 'NoneType' object has no attribute 'group'
 (caused by AttributeError("'NoneType' object has no attribute 'group'",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Fixing id3 tags
file not found: Nightstep - Radioactive.m4a
error getting album and lyrics
Nightstep   Radioactive 
local variable 'audiofile' referenced before assignment
couldnt get album art
Downloaded: Nightstep - Radioactive
MacBook-Alex:Nightcore remix alex$

**Comment by yan12125** [comment]
You are using an out-dated version. Please update to the latest version (2015.11.24). Check [this FAQ](https://github.com/rg3/youtube-dl#how-do-i-update-youtube-dl) on how to update.
