### ISSUE TITLE
Support for Het Nieuwsblad

### ISSUE THREAD

**Issue by joepie91** [rg3/youtube-dl#7662]
* __URL:__ http://www.nieuwsblad.be/cnt/dmf20151124_01986463
* __Error:__ Unsupported URL: http://www.nieuwsblad.be/cnt/dmf20151124_01986463
* __Platform:__ openSUSE 13.1, x86_64, XFCE
* __Version:__ 2015.11.24
* __Video player:__ VRT Player (custom?)

```
sven@linux-etoq:/mnt/storage2/archive> ytdl -v http://www.nieuwsblad.be/cnt/dmf20151124_01986463
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--title', u'--continue', u'--retries', u'4', u'--write-info-json', u'--write-description', u'--write-thumbnail', u'--write-annotations', u'--all-subs', u'--ignore-errors', u'--merge-output-format', u'mkv', u'-f', u'bestvideo+bestaudio/best', u'-v', u'http://www.nieuwsblad.be/cnt/dmf20151124_01986463']
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
[debug] youtube-dl version 2015.11.24
[debug] Python version 2.7.6 - Linux-3.11.10-29-desktop-x86_64-with-SuSE-13.1-x86_64
[debug] exe versions: ffmpeg 2.8.2, ffprobe 2.8.2, rtmpdump 2.4
[debug] Proxy map: {}
[generic] dmf20151124_01986463: Requesting header
WARNING: Falling back on generic information extractor.
[generic] dmf20151124_01986463: Downloading webpage
[generic] dmf20151124_01986463: Extracting information
ERROR: Unsupported URL: http://www.nieuwsblad.be/cnt/dmf20151124_01986463
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/generic.py", line 1282, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/lib/python2.7/site-packages/youtube_dl/compat.py", line 248, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=etree.TreeBuilder(element_factory=_element_factory)))
  File "/usr/lib/python2.7/site-packages/youtube_dl/compat.py", line 237, in _XML
    parser.feed(text)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: syntax error: line 3, column 0
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 663, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/generic.py", line 1887, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.nieuwsblad.be/cnt/dmf20151124_01986463
```

**Comment by midas02** [comment]
@fluxw42 Kan jij https://github.com/rg3/youtube-dl/pull/8008 nieuw leven inblazen? Beetje stom dat hij geblokkeerd blijft op één noodzakelijke wijziging. Anders neem ik hem over.

**Comment by fluxw42** [comment]
@midas02 Issues should have been fixed. I think #7662 and #8008 can be resolved.
