### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by zpytela** [rg3/youtube-dl#7703]
Using version 2015.11.13, download on Fedora 22 fails as of today:

  youtube-dl --verbose 'https://www.youtube.com/watch?v=qWmicId9ldk'
[debug] System config: [u'--prefer-free-formats']
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://www.youtube.com/watch?v=qWmicId9ldk']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.13
[debug] Python version 2.7.10 - Linux-4.2.6-200.fc22.x86_64-x86_64-with-fedora-22-Twenty_Two
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] qWmicId9ldk: Downloading webpage
[youtube] qWmicId9ldk: Downloading video info webpage
[youtube] qWmicId9ldk: Extracting video information
[youtube] {43} signature length 49.43, html5 player en_US-vflFEzfy7
[youtube] qWmicId9ldk: Downloading player https://s.ytimg.com/yts/jsbin/player-en_US-vflFEzfy7/base.js
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 817, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 744, in _extract_signature_function
    cache_res = res(test_string)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 796, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/lib/python2.7/site-packages/youtube_dl/jsinterp.py", line 254, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "/usr/lib/python2.7/site-packages/youtube_dl/jsinterp.py", line 55, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/lib/python2.7/site-packages/youtube_dl/jsinterp.py", line 135, in interpret_expression
    self._objects[variable] = self.extract_object(variable)
  File "/usr/lib/python2.7/site-packages/youtube_dl/jsinterp.py", line 220, in extract_object
    fields = obj_m.group('fields')
AttributeError: 'NoneType' object has no attribute 'group'
 (caused by AttributeError("'NoneType' object has no attribute 'group'",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 817, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 744, in _extract_signature_function
    cache_res = res(test_string)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 796, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/lib/python2.7/site-packages/youtube_dl/jsinterp.py", line 254, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "/usr/lib/python2.7/site-packages/youtube_dl/jsinterp.py", line 55, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/lib/python2.7/site-packages/youtube_dl/jsinterp.py", line 135, in interpret_expression
    self._objects[variable] = self.extract_object(variable)
  File "/usr/lib/python2.7/site-packages/youtube_dl/jsinterp.py", line 220, in extract_object
    fields = obj_m.group('fields')
AttributeError: 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 661, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 1356, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 827, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 817, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 744, in _extract_signature_function
    cache_res = res(test_string)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 796, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/lib/python2.7/site-packages/youtube_dl/jsinterp.py", line 254, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "/usr/lib/python2.7/site-packages/youtube_dl/jsinterp.py", line 55, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/lib/python2.7/site-packages/youtube_dl/jsinterp.py", line 135, in interpret_expression
    self._objects[variable] = self.extract_object(variable)
  File "/usr/lib/python2.7/site-packages/youtube_dl/jsinterp.py", line 220, in extract_object
    fields = obj_m.group('fields')
AttributeError: 'NoneType' object has no attribute 'group'
 (caused by AttributeError("'NoneType' object has no attribute 'group'",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by phihag** [comment]
You are using an outdated version of youtube-dl. YouTube changed their interface after the version you were using was release, so you need to update to the current version of youtube-dl. Refer to [our FAQ](https://yt-dl.org/update) if you have trouble updating.
