### ISSUE TITLE
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug 

### ISSUE THREAD

**Issue by saphrano** [rg3/youtube-dl#7711]
as asked in the stoud, i report it here ... (btw. i am using debian strech 32bit)

$ youtube-dl --verbose https://www.youtube.com/playlist?list=PLJXXOD5BZi5PvLZ2RdVYrOpD75vitF29y
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://www.youtube.com/playlist?list=PLJXXOD5BZi5PvLZ2RdVYrOpD75vitF29y']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.10
[debug] Python version 2.7.10+ - Linux-4.3.0-trunk-686-i686-with-debian-stretch-sid
[debug] exe versions: avconv 2.8.2-1, avprobe 2.8.2-1, ffmpeg 2.8.2-1, ffprobe 2.8.2-1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:playlist] PLJXXOD5BZi5PvLZ2RdVYrOpD75vitF29y: Downloading webpage
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 661, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 1644, in _real_extract
    return self._extract_playlist(playlist_id)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 1619, in _extract_playlist
    page, 'title')
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 593, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 584, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.
