### ISSUE TITLE
Site request: ispot.tv

### ISSUE THREAD

**Issue by RingoTheDog** [rg3/youtube-dl#7721]
URL Example: http://www.ispot.tv/ad/7p_Q/viagra-fishing

Output:

C:\>youtube-dl -v http://www.ispot.tv/ad/7p_Q/viagra-fishing
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.ispot.tv/ad/7p_Q/viagra-fishing'
]
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.11.27.1
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-71346-gdf4fca2
[debug] Proxy map: {}
[generic] viagra-fishing: Requesting header
WARNING: Falling back on generic information extractor.
[generic] viagra-fishing: Downloading webpage
[generic] viagra-fishing: Extracting information
ERROR: Unsupported URL: http://www.ispot.tv/ad/7p_Q/viagra-fishing
Traceback (most recent call last):
  File "youtube_dl\extractor\generic.pyo", line 1282, in _real_extract
  File "youtube_dl\compat.pyo", line 248, in compat_etree_fromstring
  File "youtube_dl\compat.pyo", line 237, in _XML
  File "xml\etree\ElementTree.pyo", line 1642, in feed
  File "xml\etree\ElementTree.pyo", line 1506, in _raiseerror
ParseError: mismatched tag: line 79, column 6
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 663, in extract_info
  File "youtube_dl\extractor\common.pyo", line 290, in extract
  File "youtube_dl\extractor\generic.pyo", line 1887, in _real_extract
UnsupportedError: Unsupported URL: http://www.ispot.tv/ad/7p_Q/viagra-fishing

Thanks
Ringo

**Comment by RingoTheDog** [comment]
BTW...direct link to video does download correctly:
http://video.cdn.ispot.tv/media2/001/110/051/7p_Q_360.webm

**Comment by witedragen** [comment]
Bump.

**Comment by rsfinlayson** [comment]
As others have noted, the HTML source for these pages contain a direct link to the video, that works.
Specifically, the HTML contains a
div class="video"
  which contains a
    <div id="video_player"
      which contains a 
        <div class="jwplayer"
          which contains a 
            data-mp4= parameter, that references the video directly.
I hope that this is useful for updating "youtube-dl" to handle these URLs
