### ISSUE TITLE
Unable to Download from BBC site. V 2015.11.24/Linux 4.2.5-1-ARCH  x86_64

### ISSUE THREAD

**Issue by sgargbugreporter** [rg3/youtube-dl#7724]
```bash
$ youtube-dl --verbose "http://www.bbc.com/specialfeatures/horizonsbusiness/seriesfive/episode-16-search-and-beyond/?vid=p038m009"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.bbc.com/specialfeatures/horizonsbusiness/seriesfive/episode-16-search-and-beyond/?vid=p038m009']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.24
[debug] Python version 3.5.0 - Linux-4.2.5-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 2.8.3, ffprobe 2.8.3, rtmpdump 2.4
[debug] Proxy map: {}
[bbc] episode-16-search-and-beyond: Downloading webpage
ERROR: Unable to extract playlist data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 663, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/bbc.py", line 852, in _real_extract
    webpage, 'playlist data'),
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 584, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract playlist data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by sgargbugreporter** [comment]
It works in the latest git commit. Thank you.  Waiting for the packages to be updated.
