### ISSUE TITLE
lynda returned error: Session has expired

### ISSUE THREAD

**Issue by philberndt** [rg3/youtube-dl#7725]
When downloading using a batch file, I get the error "lynda returned error: Session has expired" every time it starts downloading from the second url in the list, it usually happens in the first or second video.

```
ERROR: lynda returned error: Session has expired
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 663, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/lynda.py", line 126, in _real_extract
    'lynda returned error: %s' % video['Message'], expected=True)
ExtractorError: lynda returned error: Session has expired
```

**Comment by dstftw** [comment]
Post the **full** output of youtube-dl when run [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by philberndt** [comment]
```
youtube-dl -u PRIVATE -p PRIVATE --batch-file lynda.txt -o '~/Desktop/Lynda/%(playlist_title)s/%(playlt_index)s - %(title)s.%(ext)s' --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'--batch-file', u'lynda.txt', u'-o', u'~/Desktop/Lynda/%(playlist_title)s/%(playlt_index)s - %(title)s.%(ext)s', u'--verbose']
[debug] Batch file urls: [u'http://www.lynda.com/Instagram-tutorials/Creative-Spark-Lauren-Lemon-Creative-Portrait-Photographer/101506-2.html', u'http://www.lynda.com/iPhoto-tutorials/Enhancing-Photos-iPhoto/115961-2.html', u'http://www.lynda.com/Lightroom-tutorials/Enhancing-Portrait-Young-Woman-Lightroom/141503-2.html', u'http://www.lynda.com/Lightroom-tutorials/Photographing-Assembling-Lunar-Eclipse-Composite/171766-2.html', u'http://www.lynda.com/Lightroom-tutorials/Portrait-Project-Lighting-Portrait-Lightroom/196590-2.html', u'http://www.lynda.com/Lightroom-tutorials/Using-Wacom-Tablets-Lightroom/373091-2.html', u'http://www.lynda.com/Maya-tutorials/Lighting-Rendering-mental-ray-Maya/61222-2.html', u'http://www.lynda.com/Painter-tutorials/Digital-Painting-Transforming-Portrait/126125-2.html', u'http://www.lynda.com/Perfect-Photo-Suite-tutorials/Up-Running-Perfect-Photo-Suite-8/153675-2.html', u'http://www.lynda.com/Photography-Cameras-Gear-tutorials/Advanced-Craft-Photography/123483-2.html', u'http://www.lynda.com/Photography-Cameras-Gear-tutorials/Architectural-Photography-Exteriors/122455-2.html', u'http://www.lynda.com/Photography-Cameras-Gear-tutorials/Art-Craft-Photography/123482-2.html', u'http://www.lynda.com/Photography-Cameras-Gear-tutorials/DIY-Photographer/369185-2.html', u'http://www.lynda.com/Photography-Cameras-Gear-tutorials/Douglas-Kirkland-Photography-Storytelling-through-Photography/121834-2.html', u'http://www.lynda.com/Photography-Cameras-Gear-tutorials/Finding-Perfect-Portrait-Lens/182035-2.html', u'http://www.lynda.com/Photography-Cameras-Gear-tutorials/Insights-Architectural-Photography/122454-2.html', u'http://www.lynda.com/Photography-Cameras-Gear-tutorials/Insights-Photojournalism/120606-2.html', u'http://www.lynda.com/Photography-Cameras-Gear-tutorials/Insights-Product-Photography/135421-2.html', u'http://www.lynda.com/Photography-Cameras-Gear-tutorials/Lighting-Flash-Basics/124551-2.html', u'http://www.lynda.com/Photography-Cameras-Gear-tutorials/Lighting-Flash-Capturing-Dancer-Motion/124553-2.html', u'http://www.lynda.com/Photography-Cameras-Gear-tutorials/Lighting-Flash-Location-from-Close-Up-Portrait/124552-2.html', u'http://www.lynda.com/Photography-Cameras-Gear-tutorials/Lighting-Flash-Sports-from-Action-Portraits/124554-2.html', u'http://www.lynda.com/Photography-Cameras-Gear-tutorials/Lighting-Photographers-Flash-Exposure-Fundamentals/97401-2.html', u'http://www.lynda.com/Photography-Cameras-Gear-tutorials/Lighting-Photographers-Portraiture/103265-2.html', u'http://www.lynda.com/Photography-Cameras-Gear-tutorials/Narrative-Portraiture-On-Location-in-New-York-City/76561-2.html', u'http://www.lynda.com/Photography-Cameras-Gear-Tutorials/Narrative-Portraiture-On-Location-in-New-York-with-Rodney-Smith/79032-2.html', u'http://www.lynda.com/Photography-Cameras-Gear-tutorials/Narrative-Portraiture-On-Location-in-Texas-with-Keith-Carter/76562-2.html', u'http://www.lynda.com/Photography-Cameras-Gear-tutorials/Photographing-High-School-Senior-Portraits/157342-2.html', u'http://www.lynda.com/Photography-Cameras-Gear-tutorials/Shooting-Photo-Essay-Artist-Work/120607-2.html', u'http://www.lynda.com/Photography-Cameras-Gear-tutorials/Shooting-Photo-Essay-Coney-Island/387352-2.html', u'http://www.lynda.com/Photography-Cameras-Gear-tutorials/Shooting-Photo-Essay-Telling-Family-Story/149839-2.html', u'http://www.lynda.com/Photography-Cameras-Gear-tutorials/Shooting-with-Wireless-Flash-Product-Shots/72963-2.html', u'http://www.lynda.com/Photography-Cameras-Gear-tutorials/Street-Photography-Candid-Portraiture/185322-2.html', u'http://www.lynda.com/Photography-Cameras-Gear-tutorials/Travel-Photography-Desert-Road-Trip/121831-2.html', u'http://www.lynda.com/Photography-Cameras-Gear-tutorials/Travel-Photography-Family-Cabin/149289-2.html', u'http://www.lynda.com/Photography-Cameras-Gear-tutorials/Up-Running-Studio-Strobes/148583-2.html', u'http://www.lynda.com/Photography-Creative-Spark-tutorials/Becci-Manson-Retouching-Restoring/186172-2.html', u'http://www.lynda.com/Photography-Creative-Spark-tutorials/Undeveloped-WWII-Film-Discovered/373522-2.html', u'http://www.lynda.com/Photography-Documentaries-tutorials/Creative-Spark-Nick-Onken-Travel-Lifestyle-Photographer/76338-2.html', u'http://www.lynda.com/Photography-Flash-Photography-tutorials/Lighting-Flash-Portrait-Beekeeper-His-Bees/124555-2.html', u'http://www.lynda.com/Photography-Lighting-tutorials/Douglas-Kirkland-on-Photography-Natural-Light-Portraiture/73558-2.html', u'http://www.lynda.com/Photography-Lighting-tutorials/Douglas-Kirkland-on-Photography-Studio-Portraiture/73557-2.html', u'http://www.lynda.com/Photography-Lighting-tutorials/Shooting-Photo-Essay-60-Minutes/170283-2.html', u'http://www.lynda.com/Photography-Lighting-tutorials/Shooting-Soccer-Action-Photo/180778-2.html', u'http://www.lynda.com/Photography-Lighting-tutorials/Up-Running-Lighting-Natural-Light/117105-2.html', u'http://www.lynda.com/Photography-Masking-Compositing-tutorials/Brooke-Shadens-Conceptual-Photography-Start-Finish/140846-2.html', u'http://www.lynda.com/Photography-Masking-Compositing-tutorials/Photo-Restoration-Techniques-Recomposing-Photo/373088-2.html', u'http://www.lynda.com/Photography-Night-Low-Light-tutorials/Shooting-Wireless-Flash-Outdoors-Twilight/85089-2.html', u'http://www.lynda.com/Photography-Night-Low-Light-tutorials/Travel-Photography-Photographer-Cuba/371733-2.html', u'http://www.lynda.com/Photography-Photo-Assignments-tutorials/Narrative-Portraiture-Foundations-of-Portraiture/73663-2.html', u'http://www.lynda.com/Photography-Plugin-tutorials/Basics-Using-Nik-Collection/167143-2.html', u'http://www.lynda.com/Photography-Portraits-tutorials/Street-Photography-Posed-Portraiture/378046-2.html', u'http://www.lynda.com/Photography-Portraits-tutorials/Wedding-Photography-Everyone-Bridal-Portraits/115859-2.html', u'http://www.lynda.com/Photography-Portraits-tutorials/Wedding-Photography-Everyone-Fundamentals/115860-2.html', u'http://www.lynda.com/Photography-tutorials/Douglas-Kirkland-Photography-Life-Pictures/125754-2.html', u'http://www.lynda.com/Photography-tutorials/Douglas-Kirkland-Photography-Photographing-Kids-Families/102629-2.html', u'http://www.lynda.com/Photography-tutorials/Family-Group-Portraiture/90510-2.html', u'http://www.lynda.com/Photography-tutorials/Foundations-Photography-Flash/136568-2.html', u'http://www.lynda.com/Photography-tutorials/Foundations-Photography-Night-Low-Light/90279-2.html', u'http://www.lynda.com/Photography-tutorials/Pictures-Move-Creating-Cinemagraphs-Photoshop-After-Effects-Flixel-Cliplets/361170-2.html', u'http://www.lynda.com/Photography-tutorials/Up-Running-Lighting-Studio-Lights-Flash/122452-2.html', u'http://www.lynda.com/Photoshop-CS2-tutorials/channels-masks/322-2.html', u'http://www.lynda.com/Photoshop-CS3-tutorials/beyond-skin-going-deeper-with/600-2.html', u'http://www.lynda.com/Photoshop-CS3-tutorials/channels-masks-advanced-techniques/506-2.html', u'http://www.lynda.com/Photoshop-CS3-tutorials/channels-masks-the-essentials/468-2.html', u'http://www.lynda.com/Photoshop-CS3-tutorials/portrait-retouching-essentials/532-2.html', u'http://www.lynda.com/Photoshop-CS3-tutorials/portrait-retouching-techniques/566-2.html', u'http://www.lynda.com/Photoshop-CS4-tutorials/image-compositing-for-photographers/58987-2.html', u'http://www.lynda.com/Photoshop-CS4-tutorials/layer-masks-in-depth/55426-2.html', u'http://www.lynda.com/Photoshop-CS4-tutorials/Photo-Restoration-with-Photoshop/84104-2.html', u'http://www.lynda.com/Photoshop-CS4-tutorials/portrait-retouching-essential-training/688-2.html', u'http://www.lynda.com/Photoshop-CS4-tutorials/retouching-fashion-photography-projects/46312-2.html', u'http://www.lynda.com/Photoshop-CS4-tutorials/selections-in-depth/52106-2.html', u'http://www.lynda.com/Photoshop-CS5-tutorials/athletic-retouching-projects/65893-2.html', u'http://www.lynda.com/Photoshop-CS5-tutorials/creative-compositing/65891-2.html', u'http://www.lynda.com/Photoshop-CS5-tutorials/fashion-retouching-projects/68497-2.html', u'http://www.lynda.com/Photoshop-CS5-tutorials/portrait-retouching/64047-2.html', u'http://www.lynda.com/Photoshop-CS5-tutorials/selections-in-depth/67163-2.html', u'http://www.lynda.com/Photoshop-Elements-9-tutorials/scanning-and-restoring-photos/69525-2.html', u'http://www.lynda.com/Photoshop-Elements-tutorials/Photoshop-Elements-11-Essentials-Editing-Retouching-Photos/111234-2.html', u'http://www.lynda.com/Photoshop-Elements-tutorials/Up-Running-Photoshop-Elements-11/108968-2.html', u'http://www.lynda.com/Photoshop-tutorials/Architectural-Photography-Interiors/122453-2.html', u'http://www.lynda.com/Photoshop-tutorials/Art-Photoshop-Compositing/147534-2.html', u'http://www.lynda.com/Photoshop-tutorials/Bert-Monroy-Dreamscapes-Arch-Somewhere-Else/183681-2.html', u'http://www.lynda.com/Photoshop-tutorials/Bert-Monroy-Dreamscapes-Castle-Mountain/183678-2.html', u'http://www.lynda.com/Photoshop-tutorials/Bert-Monroy-Dreamscapes-Haunted-House/367454-2.html', u'http://www.lynda.com/Photoshop-tutorials/Bert-Monroy-Dreamscapes-Magic-Orb/367451-2.html', u'http://www.lynda.com/Photoshop-tutorials/Bert-Monroy-Dreamscapes-Maze/367455-2.html', u'http://www.lynda.com/Photoshop-tutorials/Bert-Monroy-Dreamscapes-Mushroom-House/174493-2.html', u'http://www.lynda.com/Photoshop-tutorials/Bert-Monroy-Dreamscapes-Mystical-Passage/183679-2.html', u'http://www.lynda.com/Photoshop-tutorials/Bert-Monroy-Dreamscapes-Offworld-Mining/367453-2.html', u'http://www.lynda.com/Photoshop-tutorials/Bert-Monroy-Dreamscapes-Sacred-Cavern/367452-2.html', u'http://www.lynda.com/Photoshop-tutorials/Bert-Monroy-Dreamscapes-Sci-Fi-Tower/183680-2.html', u'http://www.lynda.com/Photoshop-tutorials/Bert-Monroy-Dreamscapes-Volume-2/122805-2.html', u'http://www.lynda.com/Photoshop-tutorials/Bert-Monroy-Dreamscapes-Volume-3/124550-2.html', u'http://www.lynda.com/Photoshop-tutorials/Bert-Monroy-Dreamscapes/107926-2.html', u'http://www.lynda.com/Photoshop-tutorials/Colorizing-Black-White-Photographs-Photoshop/133329-2.html', u'http://www.lynda.com/Photoshop-tutorials/Creating-Black-White-Landscape-Photos-Photoshop/169620-2.html', u'http://www.lynda.com/Photoshop-tutorials/Creating-Composites-Photoshop/123551-2.html', u'http://www.lynda.com/Photoshop-tutorials/Creating-Distressed-Vintage-Photo-Effects-Photoshop/168609-2.html', u'http://www.lynda.com/Photoshop-tutorials/Creative-Video-Compositing-Photoshop/141136-2.html', u'http://www.lynda.com/Photoshop-tutorials/Enhancing-Environmental-Portrait-Photoshop/114327-2.html', u'http://www.lynda.com/Photoshop-tutorials/Exploring-Photography-Backlighting/182172-2.html', u'http://www.lynda.com/Photoshop-tutorials/Exploring-Photography-White-Balance-Color-Temperature/182171-2.html', u'http://www.lynda.com/Photoshop-tutorials/Foundations-Photography-Macro-Close-Up/111232-2.html', u'http://www.lynda.com/Photoshop-tutorials/Introduction-Photo-Compositing/191608-2.html', u'http://www.lynda.com/Photoshop-tutorials/Lighting-Photographing-Still-Life/189614-2.html', u'http://www.lynda.com/Photoshop-tutorials/My-Photoshop-Story-Dana-Keller-Photo-Colorizer/384097-2.html', u'http://www.lynda.com/Photoshop-tutorials/Nik-Creative-Effects-Workshop/123499-2.html', u'http://www.lynda.com/Photoshop-tutorials/Photo-Restoration-Techniques-Color-Casts-Fading/180186-2.html', u'http://www.lynda.com/Photoshop-tutorials/Photo-Restoration-Techniques-Damaged-Black-White-Images/180187-2.html', u'http://www.lynda.com/Photoshop-tutorials/Photo-Restoration-Techniques-Removing-Paper-Texture/373087-2.html', u'http://www.lynda.com/Photoshop-tutorials/Photographing-Clothes-Textiles/135423-2.html', u'http://www.lynda.com/Photoshop-tutorials/Photographing-Compositing-Photoshop/374612-2.html', u'http://www.lynda.com/Photoshop-tutorials/Photographing-Jewelry/135422-2.html', u'http://www.lynda.com/Photoshop-tutorials/Photoshop-Artist-Action-Steve-Caplins-Day-Night/123452-2.html', u'http://www.lynda.com/Photoshop-tutorials/Photoshop-Artist-Action-Tim-Greys-Abandoned-Farmhouse/123556-2.html', u'http://www.lynda.com/Photoshop-tutorials/Photoshop-Artist-Action-Tim-Greys-Prayer-Sticks/123557-2.html', u'http://www.lynda.com/Photoshop-tutorials/Photoshop-Artist-Action-Uli-Staigers-Airship/123429-2.html', u'http://www.lynda.com/Photoshop-tutorials/Photoshop-Artist-Action-Uli-Staigers-Atlantis/123430-2.html', u'http://www.lynda.com/Photoshop-tutorials/Photoshop-Artist-Action-Uli-Staigers-Balloonatic/123432-2.html', u'http://www.lynda.com/Photoshop-tutorials/Photoshop-Artist-Action-Uli-Staigers-Perestroika/123549-2.html', u'http://www.lynda.com/Photoshop-tutorials/Photoshop-Artist-Action-Uli-Staigers-Powered-Nature/123479-2.html', u'http://www.lynda.com/Photoshop-tutorials/Photoshop-Artist-Action-Uli-Staigers-Skytrain/123431-2.html', u'http://www.lynda.com/Photoshop-tutorials/Photoshop-Artist-Action-Uli-Staigers-Wasp-Attack/123428-2.html', u'http://www.lynda.com/Photoshop-tutorials/Photoshop-CC-Adjustment-Layer-Blend-Mode-Workshop/374501-2.html', u'http://www.lynda.com/Photoshop-tutorials/Photoshop-CC-Essential-Training-2015/372339-2.html', u'http://www.lynda.com/Photoshop-tutorials/Photoshop-CC-Selections-Layer-Masking-Workshop/126063-2.html', u'http://www.lynda.com/Photoshop-tutorials/Photoshop-Compositing-Project-Replacing-Sky/417093-2.html', u'http://www.lynda.com/Photoshop-tutorials/Photoshop-CS6-Photographers-New-Features/98828-2.html', u'http://www.lynda.com/Photoshop-tutorials/Photoshop-CS6-Selections-Layer-Masking-Workshop/123506-2.html', u'http://www.lynda.com/Photoshop-tutorials/Photoshop-for-Photographers-Portrait-Retouching/103293-2.html', u'http://www.lynda.com/Photoshop-tutorials/Photoshop-Image-Cleanup-Workshop/123467-2.html', u'http://www.lynda.com/Photoshop-tutorials/Photoshop-Insider-Training-Enhancing-Photos/107187-2.html', u'http://www.lynda.com/Photoshop-tutorials/Photoshop-Insider-Training-Photo-Restoration/117537-2.html', u'http://www.lynda.com/Photoshop-tutorials/Photoshop-Insider-Training-Rethinking-Essentials/185323-2.html', u'http://www.lynda.com/photoshop-tutorials/photoshop-interior-design-living-room-composite/142537-2.html', u'http://www.lynda.com/Photoshop-tutorials/Photoshop-Photographers-2015-Creative-Cloud-Updates/373793-2.html', u'http://www.lynda.com/Photoshop-tutorials/Photoshop-Photographers-Compositing/103290-2.html', u'http://www.lynda.com/Photoshop-tutorials/Photoshop-Photographers-Lighting-Effects/142958-2.html', u'http://www.lynda.com/Photoshop-tutorials/Photoshop-Retouching-Techniques-Beauty-Portraits/110286-2.html', u'http://www.lynda.com/Photoshop-tutorials/Photoshop-Retouching-Techniques-Faces/141134-2.html', u'http://www.lynda.com/Photoshop-tutorials/Photoshop-Retouching-Techniques-Fashion-Editorial/121622-2.html', u'http://www.lynda.com/Photoshop-tutorials/Photoshop-Retouching-Techniques-Hair/141135-2.html', u'http://www.lynda.com/Photoshop-tutorials/Photoshop-Retouching-Techniques-Skin/141133-2.html', u'http://www.lynda.com/Photoshop-tutorials/Photoshop-Selections-Workshop/123439-2.html', u'http://www.lynda.com/Photoshop-tutorials/Portrait-Project-Changing-Background-Dramatic-Effect/157117-2.html', u'http://www.lynda.com/Photoshop-tutorials/Portrait-Project-Changing-Sky-Background/157116-2.html', u'http://www.lynda.com/Photoshop-tutorials/Portrait-Project-Changing-Studio-Background/150541-2.html', u'http://www.lynda.com/Photoshop-tutorials/Portrait-Project-Enhancing-Environmental-Portrait-Model/187530-2.html', u'http://www.lynda.com/Photoshop-tutorials/Portrait-Project-Fixing-Distracting-Background/195856-2.html', u'http://www.lynda.com/Photoshop-tutorials/Portrait-Project-Fixing-Group-Photo/196588-2.html', u'http://www.lynda.com/Photoshop-tutorials/Portrait-Project-Retouching-Studio-Portrait/163420-2.html', u'http://www.lynda.com/Photoshop-tutorials/Practical-Photoshop-Selections/147023-2.html', u'http://www.lynda.com/Photoshop-tutorials/Practical-Photoshop-Selections/96664-2.html', u'http://www.lynda.com/Photoshop-tutorials/Processing-Product-Photos-Photoshop/150544-2.html', u'http://www.lynda.com/Photoshop-tutorials/Recolorizing-Photograph-Photoshop/160272-2.html', u'http://www.lynda.com/Photoshop-tutorials/Restoring-Photos-Photoshop-CS6/123528-2.html', u'http://www.lynda.com/Photoshop-tutorials/Retouching-Bridal-Portraits-Photoshop/124089-2.html', u'http://www.lynda.com/Photoshop-tutorials/Sean-Duggans-Fire-Ice-Photo-Composite-Start-Finish/384048-2.html', u'http://www.lynda.com/Photoshop-tutorials/Up-Running-Photoshop-Automation/111989-2.html', u'http://www.lynda.com/Photoshop-tutorials/Using-Wacom-Tablets-Photoshop/373090-2.html', u'http://www.lynda.com/Photoshop-tutorials/Working-Perspective-Photoshop/165352-2.html', u'http://www.lynda.com/Portrait-photography-tips/Shooting-Photo-Essay-Telling-Story-Portraiture/387354-2.html', u'http://www.lynda.com/Portrait-photography-tutorial/5-Day-Photo-Challenge-Portraiture/407210-2.html', u'http://www.lynda.com/Silver-Efex-Pro-tutorials/Learning-Silver-Efex-Pro-2/167142-2.html', u'http://www.lynda.com/Street-Photography-tips/5-Day-Photo-Challenge-Street-Photography/386569-2.html', u'http://www.lynda.com/training/Narrative-Portraiture-Portraits-of-Two-Texas-Artists/94662-2.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.27.1
[debug] Python version 2.7.10 - Darwin-15.0.0-x86_64-i386-64bit
[debug] exe versions: avconv 11.4, avprobe 11.4, ffmpeg 2.8.3, ffprobe 2.8.3, rtmpdump 2.4
[debug] Proxy map: {}
[lynda:course] Logging in as PRIVATE
[lynda:course] 101506: Downloading course JSON
[lynda:course] Logging out
[download] Downloading playlist: The Creative Spark: Lauren Lemon, Creative Portrait Photographer
[lynda:course] playlist The Creative Spark: Lauren Lemon, Creative Portrait Photographer: Collected 5 video ids (downloading 5 of them)
[download] Downloading video 1 of 5
[lynda] Logging in as philipp_berndt
[lynda] 119468: Downloading video JSON
[lynda] 119468: Checking 1-540 video format URL
[lynda] 119468: Checking 1-720 video format URL
[lynda] 119468: Checking 1-360 video format URL
[lynda] 119468: Checking 0-540 video format URL
[lynda] 119468: Checking 0-720 video format URL
[lynda] 119468: Checking 0-360 video format URL
[debug] Invoking downloader on u'http://files3.lynda.com/secure/courses/101506/VBR_MP4h264_main_HD720/101506_00_00_LA24_Preview.mp4?nfQiKlvMXrt6E8DXUI4E-BuQvTQ6k4EelB0bfM-crD5La-jTZCeQD5xFaDfBNZbF49W6VfVkfvKFffC-joS0Bx_1zumDfaYvEvJEHCBro7BxOv836bkNnFyYvjmVRmiOPSxGwgpnZoiPi_4_a1HUndLGdrmRRQLfppvSYD93P82H7-DE9PZGSf7t6G3XXGw&c3.ri=3773565519492081860'
[download] /Users/phil/Desktop/Lynda/The Creative Spark - Lauren Lemon, Creative Portrait Photographer/NA - Preview.mp4 has already been downloaded
[download] 100% of 11.44MiB
[download] Downloading video 2 of 5
[lynda] 116904: Downloading video JSON
[lynda] 116904: Checking 1-540 video format URL
[lynda] 116904: Checking 1-720 video format URL
[lynda] 116904: Checking 1-360 video format URL
[lynda] 116904: Checking 0-540 video format URL
[lynda] 116904: Checking 0-720 video format URL
[lynda] 116904: Checking 0-360 video format URL
[debug] Invoking downloader on u'http://files3.lynda.com/secure/courses/101506/VBR_MP4h264_main_HD720/101506_00_01_LA24_LaurenLemon.mp4?QoZPcayAnp0DgaWoSdNHYZ0MnfJTGFxMZC4ksQ70BwqPRRd40f-6SQcgjzeGPzG04d8shviqKu7DBPlGPth6NmpyO3x2ydhZGjnFKwQ50wdCAROUCMX7ttgRUrH3fmV7ZxnJROnI4HlunC6sMurYd8PK68DeYWhAnI4NK8MRzPzoG0nv_DB13uDXakBRZlPudPZA&c3.ri=3773847001716421855'
[download] Destination: /Users/phil/Desktop/Lynda/The Creative Spark - Lauren Lemon, Creative Portrait Photographer/NA - Lauren Lemon, creative portrait photographer.mp4
[download] 100% of 79.58MiB in 01:38
[download] Downloading video 3 of 5
[lynda] 116906: Downloading video JSON
[lynda] 116906: Checking 1-540 video format URL
[lynda] 116906: Checking 1-720 video format URL
[lynda] 116906: Checking 1-360 video format URL
[lynda] 116906: Checking 0-540 video format URL
[lynda] 116906: Checking 0-720 video format URL
[lynda] 116906: Checking 0-360 video format URL
[debug] Invoking downloader on u'http://files2.lynda.com/secure/courses/101506/VBR_MP4h264_main_HD720/101506_01_01_LA24_Instagram.mp4?c3.ri=3773565519492084493&hashval=1449019104_3a84035b4e06a78b73ff067899d23627'
[download] Destination: /Users/phil/Desktop/Lynda/The Creative Spark - Lauren Lemon, Creative Portrait Photographer/NA - The Instagram story.mp4
[download] 100% of 18.75MiB in 00:02
[download] Downloading video 4 of 5
[lynda] 116907: Downloading video JSON
[lynda] 116907: Checking 1-540 video format URL
[lynda] 116907: Checking 1-720 video format URL
[lynda] 116907: Checking 1-360 video format URL
[lynda] 116907: Checking 0-540 video format URL
[lynda] 116907: Checking 0-720 video format URL
[lynda] 116907: Checking 0-360 video format URL
[debug] Invoking downloader on u'http://files3.lynda.com/secure/courses/101506/VBR_MP4h264_main_HD720/101506_01_02_LA24_365Project.mp4?-In2Jio5RizLpgFBJY2Sg9dUEHDJP5TIMDroi4Konkrs_aLnbplx-AVejVnzbihGslbD9uLUv4H6L2ojZ6-igvyuoLcblv5-HUqqHifKokwONwlFxr-ioyeMy4CJoSTU2JdpGh_9e5gfnwWdsCCFlrKh-ynGL7B1OIf1r6hyJte3aW0CruK4uC2vwVDnlH3Xi8o&c3.ri=3773847001716425082'
[download] Destination: /Users/phil/Desktop/Lynda/The Creative Spark - Lauren Lemon, Creative Portrait Photographer/NA - Shooting the 365 self-portrait project.mp4
[download] 100% of 33.74MiB in 00:02
[download] Downloading video 5 of 5
[lynda] 116908: Downloading video JSON
[lynda] 116908: Checking 1-540 video format URL
[lynda] 116908: Checking 1-720 video format URL
[lynda] 116908: Checking 1-360 video format URL
[lynda] 116908: Checking 0-540 video format URL
[lynda] 116908: Checking 0-720 video format URL
[lynda] 116908: Checking 0-360 video format URL
[debug] Invoking downloader on u'http://files3.lynda.com/secure/courses/101506/VBR_MP4h264_main_HD720/101506_01_03_LA24_SelfPortraitPreProd.mp4?pn0hya0wDAMuMWGEd3ltQSV8gVZrVxUD8VFZKTZESwCd79vtXIAPHtNO68jXJhMq8c1SL3nyppCLFZvmWI8ZVALc0Y1Jv679h3nfUuNsbJnrHwvEerOlxi3sdAAd7EoqPtDl3twabYJ6GfbXUAd4s1TT8m_cvzMiy3gk7v7yrjLzhpXPVN6aP1OQohtX_Jb9s-4iQDnNLlqUkmo&c3.ri=3769906245104731808'
[download] Destination: /Users/phil/Desktop/Lynda/The Creative Spark - Lauren Lemon, Creative Portrait Photographer/NA - Planning a self-portrait photo shoot.mp4
[download] 100% of 38.42MiB in 00:26
[download] Finished downloading playlist: The Creative Spark: Lauren Lemon, Creative Portrait Photographer
[lynda:course] 115961: Downloading course JSON
[lynda:course] Logging out
[download] Downloading playlist: Enhancing Photos with iPhoto
[lynda:course] playlist Enhancing Photos with iPhoto: Collected 46 video ids (downloading 46 of them)
[download] Downloading video 1 of 46
[lynda] 119408: Downloading video JSON
[lynda] 119408: Checking 1-540 video format URL
[lynda] 119408: Checking 1-360 video format URL
[lynda] 119408: Checking 0-540 video format URL
[lynda] 119408: Checking 0-360 video format URL
[debug] Invoking downloader on u'http://files2.lynda.com/secure/courses/115961/VBR_MP4h264_main_SD/115961_00_01_MM11_Welcome.mp4?c3.ri=3774128460409936574&hashval=1449019145_b15b5f63842e1e6b434b9e6a4610ef03'
[download] Destination: /Users/phil/Desktop/Lynda/Enhancing Photos with iPhoto/NA - Welcome.mp4
[download] 100% of 2.14MiB in 00:00
[download] Downloading video 2 of 46
[lynda] 119409: Downloading video JSON
ERROR: lynda returned error: Session has expired
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 663, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/lynda.py", line 126, in _real_extract
    'lynda returned error: %s' % video['Message'], expected=True)
ExtractorError: lynda returned error: Session has expired
```

**Comment by pedramsaleh** [comment]
I got the same error, after the 4th video.  I deleted the first 4 entries and tried again on the 5th and it gives the error right away.  Deleted that 5th entry and it gives the error right away again.  Perhaps this is due to something Lynda did on their end?

**Comment by pedramsaleh** [comment]
Looks like it doesn't give the error if you log in with a username/password.

**Comment by dstftw** [comment]
Should be fixed in the latest version.
