### ISSUE TITLE
InfoQ fails to extract  HTTP base URL

### ISSUE THREAD

**Issue by martinlindhe** [rg3/youtube-dl#7739]
```
youtube-dl --version
2015.11.27.1

youtube-dl --verbose "http://www.infoq.com/presentations/Simple-Made-Easy"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.infoq.com/presentations/Simple-Made-Easy']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.27.1
[debug] Python version 2.7.10 - Darwin-15.0.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.8.3, ffprobe 2.8.3, rtmpdump 2.4
[debug] Proxy map: {}
[InfoQ] Simple-Made-Easy: Downloading webpage
ERROR: Unable to extract HTTP base URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 663, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/infoq.py", line 50, in _real_extract
    'HTTP base URL')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 584, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract HTTP base URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.```

**Comment by yan12125** [comment]
Thanks for the report and sorry for late responses. InfoQ videos will work again in the next version.
