### ISSUE TITLE
Doesn't Work in This Video

### ISSUE THREAD

**Issue by JohnRobson** [rg3/youtube-dl#7748]
Doesn't Work in This Video

https://www.youtube.com/watch?v=L53gjP-TtGE

**Comment by phihag** [comment]
Please post the entire output you get when you run youtube-dl with the `-v` option on this video. Without that output we cannot diagnose what is wrong.

**Comment by JohnRobson** [comment]
Works for you?

$ youtube-dl --version
2015.11.10

$ youtube-dl https://www.youtube.com/watch?v=L53gjP-TtGE
[youtube] L53gjP-TtGE: Downloading webpage
[youtube] L53gjP-TtGE: Downloading video info webpage
[youtube] L53gjP-TtGE: Extracting video information
[youtube] L53gjP-TtGE: Downloading js player en_US-vfln_PDe6
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 817, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 744, in _extract_signature_function
    cache_res = res(test_string)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 796, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 254, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "/usr/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 55, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 135, in interpret_expression
    self._objects[variable] = self.extract_object(variable)
  File "/usr/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 220, in extract_object
    fields = obj_m.group('fields')
AttributeError: 'NoneType' object has no attribute 'group'
 (caused by AttributeError("'NoneType' object has no attribute 'group'",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


$ python2 /usr/bin/youtube-dl https://www.youtube.com/watch?v=L53gjP-TtGE
Traceback (most recent call last):
  File "/usr/bin/youtube-dl", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3095, in <module>
    @_call_aside
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3081, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3108, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 658, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 959, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 846, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'youtube-dl==2015.11.10' distribution was not found and is required by the application



$ youtube-dl --verbose https://www.youtube.com/watch?v=L53gjP-TtGE
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=L53gjP-TtGE']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.10
[debug] Python version 3.5.0 - Linux-4.2.5-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 2.8.2, ffprobe 2.8.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] L53gjP-TtGE: Downloading webpage
[youtube] L53gjP-TtGE: Downloading video info webpage
[youtube] L53gjP-TtGE: Extracting video information
[youtube] {22} signature length 45.42, html5 player en_US-vfln_PDe6
[youtube] L53gjP-TtGE: Downloading player https://s.ytimg.com/yts/jsbin/player-en_US-vfln_PDe6/base.js
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 817, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 744, in _extract_signature_function
    cache_res = res(test_string)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 796, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 254, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "/usr/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 55, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 135, in interpret_expression
    self._objects[variable] = self.extract_object(variable)
  File "/usr/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 220, in extract_object
    fields = obj_m.group('fields')
AttributeError: 'NoneType' object has no attribute 'group'
 (caused by AttributeError("'NoneType' object has no attribute 'group'",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 817, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 744, in _extract_signature_function
    cache_res = res(test_string)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 796, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 254, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "/usr/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 55, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 135, in interpret_expression
    self._objects[variable] = self.extract_object(variable)
  File "/usr/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 220, in extract_object
    fields = obj_m.group('fields')
AttributeError: 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 817, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 744, in _extract_signature_function
    cache_res = res(test_string)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 796, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 254, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "/usr/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 55, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 135, in interpret_expression
    self._objects[variable] = self.extract_object(variable)
  File "/usr/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 220, in extract_object
    fields = obj_m.group('fields')
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 661, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1356, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 827, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 817, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 744, in _extract_signature_function
    cache_res = res(test_string)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 796, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 254, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "/usr/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 55, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 135, in interpret_expression
    self._objects[variable] = self.extract_object(variable)
  File "/usr/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 220, in extract_object
    fields = obj_m.group('fields')
AttributeError: 'NoneType' object has no attribute 'group'
 (caused by AttributeError("'NoneType' object has no attribute 'group'",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.

**Comment by JohnRobson** [comment]
2015.11.10 is outdated?!

Do you tested if this video is working?!

Try by yourself and tell me if you can download this video.

**Comment by phihag** [comment]
YouTube changed their interface on November 24th. Therefore, you need at least youtube-dl v2015.11.25, preferable the [latest](http://yt-dl.org/latest/version), which as of writing is 2015.11.27.1. Using that version, `youtube-dl https://www.youtube.com/watch?v=L53gjP-TtGE` works fine for me.

**Comment by JohnRobson** [comment]
Ok, thank you very much for your support!
