### ISSUE TITLE
Mixcloud stopped working for any URL

### ISSUE THREAD

**Issue by benoon** [rg3/youtube-dl#7751]
ERROR: Unable to extract track url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by Fusl** [comment]
```
› sudo youtube-dl -U
sudo: Swipe your right index finger across the fingerprint reader
youtube-dl is up-to-date (2015.11.27.1)
sudo: Session invalidated
› youtube-dl --verbose https://www.mixcloud.com/djgigadance/hard-noises-chapter-22-mixed-by-giga-dance/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://www.mixcloud.com/djgigadance/hard-noises-chapter-22-mixed-by-giga-dance/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.27.1
[debug] Python version 2.7.8 - Linux-4.1.6-2.gce0123d-desktop-x86_64-with-SuSE-13.2-x86_64
[debug] exe versions: ffmpeg N-74842-gfb04666, ffprobe N-74842-gfb04666
[debug] Proxy map: {}
[mixcloud] djgigadance-hard-noises-chapter-22-mixed-by-giga-dance: Downloading webpage
[mixcloud] djgigadance-hard-noises-chapter-22-mixed-by-giga-dance: Trying mp3 URL
[mixcloud] djgigadance-hard-noises-chapter-22-mixed-by-giga-dance: Trying m4a URL
ERROR: Unable to extract track url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 663, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/mixcloud.py", line 71, in _real_extract
    raise ExtractorError('Unable to extract track url')
ExtractorError: Unable to extract track url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by jaimeMF** [comment]
Thanks for the report, it will be fixed in the next version.

@benoon for future reports: do the same as @Fusi, read the instructions in the error message and post the required information.

**Comment by benoon** [comment]
ok @jaimeMF , thx
