### ISSUE TITLE
BBC Radio clip download fails

### ISSUE THREAD

**Issue by kwaaak** [rg3/youtube-dl#7756]
$ youtube-dl --verbose http://www.bbc.co.uk/programmes/p03b17yy
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.bbc.co.uk/programmes/p03b17yy']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.24
[debug] Python version 2.7.5 - Darwin-13.4.0-x86_64-i386-64bit
[debug] exe versions: avconv present, avprobe present, ffmpeg N-56145-gb2517b0, ffprobe N-56145-gb2517b0, rtmpdump 2.4
[debug] Proxy map: {}
[bbc.co.uk] p03b17yy: Downloading video page
[bbc.co.uk] p03b17z6: Downloading media selection XML
[bbc.co.uk] p03b17z6: Downloading media selection XML
WARNING: unable to extract description; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 410, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 400, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1669, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 663, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 290, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/bbc.py", line 486, in _real_extract
UnboundLocalError: local variable 'duration' referenced before assignment

**Comment by yan12125** [comment]
Thanks for the report. This will be fixed in the next version.
