### ISSUE TITLE
Signature extraction failed

### ISSUE THREAD

**Issue by adib** [rg3/youtube-dl#7758]
athena:Downloads adib$ youtube-dl --verbose -F https://www.youtube.com/watch?v=F7CbZoyzOm0
    [debug] System config: []
    [debug] User config: []
    [debug] Command-line args: [u'--verbose', u'-F', u'https://www.youtube.com/watch?v=F7CbZoyzOm0']
    [debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
    [debug] youtube-dl version 2015.11.19
    [debug] Python version 2.7.10 - Darwin-15.0.0-x86_64-i386-64bit
    [debug] exe versions: ffmpeg 2.6.3, ffprobe 2.6.3
    [debug] Proxy map: {}
    [youtube] F7CbZoyzOm0: Downloading webpage
    [youtube] F7CbZoyzOm0: Downloading video info webpage
    [youtube] F7CbZoyzOm0: Extracting video information
    [youtube] {22} signature length 45.42, html5 player en_US-vfln_PDe6
    [youtube] F7CbZoyzOm0: Downloading player https://s.ytimg.com/yts/jsbin/player-en_US-vfln_PDe6/base.js
    ERROR: Signature extraction failed: Traceback (most recent call last):
      File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 817, in _decrypt_signature
        video_id, player_url, s
      File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 744, in _extract_signature_function
        cache_res = res(test_string)
      File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 796, in <lambda>
        return lambda s: initial_function([s])
      File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 254, in resf
        res, abort = self.interpret_statement(stmt, local_vars)
      File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 55, in interpret_statement
        v = self.interpret_expression(expr, local_vars, allow_recursion)
      File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 135, in interpret_expression
        self._objects[variable] = self.extract_object(variable)
      File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 220, in extract_object
        fields = obj_m.group('fields')
    AttributeError: 'NoneType' object has no attribute 'group'
     (caused by AttributeError("'NoneType' object has no attribute 'group'",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
    Traceback (most recent call last):
      File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 817, in _decrypt_signature
        video_id, player_url, s
      File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 744, in _extract_signature_function
        cache_res = res(test_string)
      File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 796, in <lambda>
        return lambda s: initial_function([s])
      File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 254, in resf
        res, abort = self.interpret_statement(stmt, local_vars)
      File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 55, in interpret_statement
        v = self.interpret_expression(expr, local_vars, allow_recursion)
      File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 135, in interpret_expression
        self._objects[variable] = self.extract_object(variable)
      File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 220, in extract_object
        fields = obj_m.group('fields')
    AttributeError: 'NoneType' object has no attribute 'group'
    Traceback (most recent call last):
      File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 661, in extract_info
        ie_result = ie.extract(url)
      File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 290, in extract
        return self._real_extract(url)
      File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1356, in _real_extract
        encrypted_sig, video_id, player_url, age_gate)
      File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 827, in _decrypt_signature
        'Signature extraction failed: ' + tb, cause=e)
    ExtractorError: Signature extraction failed: Traceback (most recent call last):
      File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 817, in _decrypt_signature
        video_id, player_url, s
      File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 744, in _extract_signature_function
        cache_res = res(test_string)
      File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 796, in <lambda>
        return lambda s: initial_function([s])
      File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 254, in resf
        res, abort = self.interpret_statement(stmt, local_vars)
      File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 55, in interpret_statement
        v = self.interpret_expression(expr, local_vars, allow_recursion)
      File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 135, in interpret_expression
        self._objects[variable] = self.extract_object(variable)
      File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 220, in extract_object
        fields = obj_m.group('fields')
    AttributeError: 'NoneType' object has no attribute 'group'
     (caused by AttributeError("'NoneType' object has no attribute 'group'",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by adib** [comment]
Duplicate of #7726
