### ISSUE TITLE
AttributeError: 'function' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by nadermx** [rg3/youtube-dl#7770]
Not really sure how to fix this error.  
Any help would be greatly appreciated?

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rq/worker.py", line 568, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python2.7/dist-packages/rq/job.py", line 495, in perform
    self._result = self.func(*self.args, **self.kwargs)
  File "/home/www/yout/worker.py", line 91, in extract_audio
    extraction_result = start_extraction(url, audio_filename)
  File "/home/www/yout/worker.py", line 126, in start_extraction
    result = ydl.download([url])
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1669, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 674, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 720, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1339, in process_video_result
    self.process_info(new_info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1417, in process_info
    info_dict['_filename'] = filename = self.prepare_filename(info_dict)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 578, in prepare_filename
    tmpl = compat_expanduser(outtmpl)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/compat.py", line 353, in compat_expanduser
    if not path.startswith('~'):
AttributeError: 'function' object has no attribute 'startswith'
```

**Comment by dstftw** [comment]
Post the **full** output of youtube-dl when run [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by nadermx** [comment]
I do have verbose, that is still the output it is giving.  

here is my dict

```
    ydl_opts = {
    'format': 'bestaudio/best', # choice of quality
    'extractaudio' : True,      # only keep the audio
    'outtmpl': lambda: temp_filepath,  # name the location
    'noplaylist' : True,        # only download single song, not playlist
    'prefer-ffmpeg' : True,
    'verbose': True,
    'postprocessors': [{
            'key': 'FFmpegMetadata'
            },
            {
      'key': 'FFmpegExtractAudio',
      'preferredcodec': 'mp3',
      'preferredquality': '192',
      }],
    'logger': MyLogger(),
    'progress_hooks': [my_hook],
     }
```

**Comment by jaimeMF** [comment]
```python
 'outtmpl': lambda: temp_filepath,
```
It must be a string, not a function.

**Comment by adveatkarnik1** [comment]
Hi, @nadermx were you able to resolve this error?
If so, could you please share your solution

**Comment by dirkf** [comment]
The solution was [not to pass a function where a string is expected](https://github.com/ytdl-org/youtube-dl/issues/7770#issuecomment-162248601).
