### ISSUE TITLE
iqiyi.com download error

### ISSUE THREAD

**Issue by futurely** [rg3/youtube-dl#7772]
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://www.iqiyi.com/v_19rrk9yumc.html', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.12.05
[debug] Python version 2.7.6 - Linux-3.13.0-24-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: ffmpeg 1.2.6-7, ffprobe 1.2.6-7
[debug] Proxy map: {}
[iqiyi] temp_id: download video page
[iqiyi] b73799b5f6cd4891d8018cb66a69be9e: Downloading JSON metadata
ERROR: Unable to load data. Error code: A000001; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 663, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/iqiyi.py", line 229, in _real_extract
    raise ExtractorError('Unable to load data. Error code: ' + raw_data['code'])
ExtractorError: Unable to load data. Error code: A000001; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by futurely** [comment]
you-get works. https://github.com/soimort/you-get/blob/master/src/you_get/extractors/iqiyi.py

**Comment by yan12125** [comment]
Thanks for the report. Iqiyi videos will work again in the next version.
