### ISSUE TITLE
youtube: Playback on other websites has been disabled by the video owner.

### ISSUE THREAD

**Issue by paulguy** [rg3/youtube-dl#7789]
In trying to fetch a video off youtube, I encountered the following error.  I'm wondering if there's a way around this.  youtube-center seems to be able to but it can't download DASH videos.  NSFW warning on that video link by the way.
```
$ youtube-dl -v https://www.youtube.com/watch?v=dxpRkMxTMAE
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=dxpRkMxTMAE']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.27.1
[debug] Python version 2.7.10 - Linux-4.0.5-gentoo-x86_64-Intel-R-_Core-TM-_i7-2600_CPU_@_3.40GHz-with-gentoo-2.2
[debug] exe versions: ffmpeg N-76643-g5324109, ffprobe N-76643-g5324109, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] dxpRkMxTMAE: Downloading webpage
[youtube] dxpRkMxTMAE: Downloading embed webpage
[youtube] dxpRkMxTMAE: Refetching age-gated info webpage
ERROR: dxpRkMxTMAE: YouTube said: <a href="http://www.youtube.com/watch?v=dxpRkMxTMAE&feature=player_embedded" target="_blank">Watch this video on YouTube.</a><br/>Playback on other websites has been disabled by the video owner.
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 663, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 1186, in _real_extract
    expected=True, video_id=video_id)
ExtractorError: dxpRkMxTMAE: YouTube said: <a href="http://www.youtube.com/watch?v=dxpRkMxTMAE&feature=player_embedded" target="_blank">Watch this video on YouTube.</a><br/>Playback on other websites has been disabled by the video owner.
```

**Comment by dstftw** [comment]
Pass login and password with `-u` and `-p` or pass authenticated cookies with `--cookies`.
