### ISSUE TITLE
[generic/BrightcoveNewIE] Brightcove video not detected on smh.com.au

### ISSUE THREAD

**Issue by anovicecodemonkey** [rg3/youtube-dl#7794]
My understanding is that video embeds in news articles should be picked up by BrightcoveNewIE. I can see ```<script src="//players.brightcove.net/3910869709001/21519b5c-4b3b-4363-accb-bdc8f358f823_default/index.min.js"></script>``` on line 1545 of the site's HTML. 

```
$ youtube-dl --verbose http://www.smh.com.au/federal-politics/political-news/everything-is-on-the-table-leaked-coag-agenda-reveals-gst-changes-being-considered-20151208-gli766.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.smh.com.au/federal-politics/political-news/everything-is-on-the-table-leaked-coag-agenda-reveals-gst-changes-being-considered-20151208-gli766.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.12.06
[debug] Python version 3.5.0 - Linux-4.2.5-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 2.8.3, ffprobe 2.8.3, rtmpdump 2.4
[debug] Proxy map: {}
[generic] everything-is-on-the-table-leaked-coag-agenda-reveals-gst-changes-being-considered-20151208-gli766: Requesting header
WARNING: Falling back on generic information extractor.
[generic] everything-is-on-the-table-leaked-coag-agenda-reveals-gst-changes-being-considered-20151208-gli766: Downloading webpage
[generic] everything-is-on-the-table-leaked-coag-agenda-reveals-gst-changes-being-considered-20151208-gli766: Extracting information
ERROR: Unsupported URL: http://www.smh.com.au/federal-politics/political-news/everything-is-on-the-table-leaked-coag-agenda-reveals-gst-changes-being-considered-20151208-gli766.html
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 663, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1890, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.smh.com.au/federal-politics/political-news/everything-is-on-the-table-leaked-coag-agenda-reveals-gst-changes-being-considered-20151208-gli766.html
```

**Comment by dstftw** [comment]
There is no video embedded, nothing can be played in browser.

**Comment by anovicecodemonkey** [comment]
@dstftw There is a video on the page that I am able to play (Chrome 47.0.2526.73) above the text 

"GST reform on the table at COAG
There are eight proposals for changing the GST to bolster government coffers, explains Fairfax's James Massola."
