### ISSUE TITLE
Site Support Request: hitfix.com

### ISSUE THREAD

**Issue by ArchCarrier** [rg3/youtube-dl#7811]
```
youtube-dl -jv http://www.hitfix.com/motion-captured/from-lorenzos-oil-to-happy-feet-lafca-winner-george-miller-traces-the-path-to-fury-road
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-jv', u'http://www.hitfix.com/motion-captured/from-lorenzos-oil-to-happy-feet-lafca-winner-george-miller-traces-the-path-to-fury-road']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.12.06
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-68653-g32c836c, ffprobe N-68653-g32c836c, rtmpdump 2.4
[debug] Proxy map: {}
WARNING: Falling back on generic information extractor.
ERROR: Unsupported URL: http://www.hitfix.com/motion-captured/from-lorenzos-oil-to-happy-feet-lafca-winner-george-miller-traces-the-path-to-fury-road
Traceback (most recent call last):
  File "youtube_dl\extractor\generic.pyo", line 1285, in _real_extract
  File "youtube_dl\compat.pyo", line 248, in compat_etree_fromstring
  File "youtube_dl\compat.pyo", line 237, in _XML
  File "xml\etree\ElementTree.pyo", line 1642, in feed
  File "xml\etree\ElementTree.pyo", line 1506, in _raiseerror
ParseError: not well-formed (invalid token): line 7, column 382
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 663, in extract_info
  File "youtube_dl\extractor\common.pyo", line 290, in extract
  File "youtube_dl\extractor\generic.pyo", line 1890, in _real_extract
UnsupportedError: Unsupported URL: http://www.hitfix.com/motion-captured/from-lorenzos-oil-to-happy-feet-lafca-winner-george-miller-traces-the-path-to-fury-road
```

**Comment by remitamine** [comment]
works with the latest version.
