### ISSUE TITLE
Could not down load playlist

### ISSUE THREAD

**Issue by rocLv** [rg3/youtube-dl#7813]
>youtube-dl https://www.youtube.com/playlist\?list\=PLJesql-aSfX7NJwuiq_gKU5cnjbTr1lRQ --verbose
[debug] System config: [u'--embed-subs', u'-o', u'~/Documents/youtube/%(title)s.%(exe)s']
[debug] User config: []
[debug] Command-line args: [u'https://www.youtube.com/playlist?list=PLJesql-aSfX7NJwuiq_gKU5cnjbTr1lRQ', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.10.18
[debug] Python version 2.7.10 - Darwin-15.0.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.8.1, ffprobe 2.8.1
[debug] Proxy map: {}
[youtube:playlist] PLJesql-aSfX7NJwuiq_gKU5cnjbTr1lRQ: Downloading webpage
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 661, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 291, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1633, in _real_extract
    return self._extract_playlist(playlist_id)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1608, in _extract_playlist
    page, 'title')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 594, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 585, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.
