### ISSUE TITLE
Signature Error

### ISSUE THREAD

**Issue by snowblinder** [rg3/youtube-dl#7814]
I am Getting This Error with the Following VIdeo :

https://www.youtube.com/watch?v=5lLclBfKj48

[youtube] 5lLclBfKj48: Downloading webpage
[youtube] 5lLclBfKj48: Downloading video info webpage
[youtube] 5lLclBfKj48: Extracting video information
[youtube] 5lLclBfKj48: Downloading js player en_US-vflPRjCOu
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 817, in _decrypt_signature
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 744, in _extract_signature_function
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 796, in <lambda>
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 254, in resf
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 55, in interpret_statement
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 135, in interpret_expression
  File "/usr/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 220, in extract_object
AttributeError: 'NoneType' object has no attribute 'group'
 (caused by AttributeError("'NoneType' object has no attribute 'group'",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.
