### ISSUE TITLE
HTTP Error 403: Forbidden when trying to download vevo videos

### ISSUE THREAD

**Issue by virtualsri** [rg3/youtube-dl#7832]
Hi I tried to download the YouTube video from the following link.  Posting the output here.

D:\Downs\torr\trap>youtube-dl --verbose https://www.youtube.com/watch?v=uI_ug1H6u0k
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=uI_ug1H6u0k']
[debug] Encodings: locale 'cp1252', fs 'mbcs', out 'cp437', pref: 'cp1252'
[debug] youtube-dl version 2014.03.29
[debug] Python version 2.7.5 - Windows-7-6.1.7600
[debug] Proxy map: {}
[youtube] Setting language
[youtube] uI_ug1H6u0k: Downloading webpage
[youtube] uI_ug1H6u0k: Downloading video info webpage
[youtube] uI_ug1H6u0k: Extracting video information
[youtube] uI_ug1H6u0k: Encrypted signatures detected.
WARNING: unable to extract html5 player; please report this issue on http://yt-dl.org/bug
[youtube] encrypted signature length 83 (41.41), itag 22, html5 player None
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 974, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 348, in _extract_signature_function
AttributeError: 'NoneType' object has no attribute 'group'

WARNING: Warning: Falling back to static signature algorithm
WARNING: unable to extract html5 player; please report this issue on http://yt-dl.org/bug
[youtube] encrypted signature length 83 (41.41), itag 43, html5 player None
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 974, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 348, in _extract_signature_function
AttributeError: 'NoneType' object has no attribute 'group'

WARNING: Warning: Falling back to static signature algorithm
WARNING: unable to extract html5 player; please report this issue on http://yt-dl.org/bug
[youtube] encrypted signature length 83 (41.41), itag 18, html5 player None
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 974, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 348, in _extract_signature_function
AttributeError: 'NoneType' object has no attribute 'group'

WARNING: Warning: Falling back to static signature algorithm
WARNING: unable to extract html5 player; please report this issue on http://yt-dl.org/bug
[youtube] encrypted signature length 83 (41.41), itag 5, html5 player None
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 974, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 348, in _extract_signature_function
AttributeError: 'NoneType' object has no attribute 'group'

WARNING: Warning: Falling back to static signature algorithm
WARNING: unable to extract html5 player; please report this issue on http://yt-dl.org/bug
[youtube] encrypted signature length 83 (41.41), itag 36, html5 player None
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 974, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 348, in _extract_signature_function
AttributeError: 'NoneType' object has no attribute 'group'

WARNING: Warning: Falling back to static signature algorithm
WARNING: unable to extract html5 player; please report this issue on http://yt-dl.org/bug
[youtube] encrypted signature length 83 (41.41), itag 17, html5 player None
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 974, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 348, in _extract_signature_function
AttributeError: 'NoneType' object has no attribute 'group'

WARNING: Warning: Falling back to static signature algorithm
WARNING: unable to extract html5 player; please report this issue on http://yt-dl.org/bug
[youtube] encrypted signature length 83 (41.41), itag 137, html5 player None
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 974, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 348, in _extract_signature_function
AttributeError: 'NoneType' object has no attribute 'group'

WARNING: Warning: Falling back to static signature algorithm
WARNING: unable to extract html5 player; please report this issue on http://yt-dl.org/bug
[youtube] encrypted signature length 83 (41.41), itag 248, html5 player None
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 974, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 348, in _extract_signature_function
AttributeError: 'NoneType' object has no attribute 'group'

WARNING: Warning: Falling back to static signature algorithm
WARNING: unable to extract html5 player; please report this issue on http://yt-dl.org/bug
[youtube] encrypted signature length 83 (41.41), itag 136, html5 player None
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 974, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 348, in _extract_signature_function
AttributeError: 'NoneType' object has no attribute 'group'

WARNING: Warning: Falling back to static signature algorithm
WARNING: unable to extract html5 player; please report this issue on http://yt-dl.org/bug
[youtube] encrypted signature length 83 (41.41), itag 247, html5 player None
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 974, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 348, in _extract_signature_function
AttributeError: 'NoneType' object has no attribute 'group'

WARNING: Warning: Falling back to static signature algorithm
WARNING: unable to extract html5 player; please report this issue on http://yt-dl.org/bug
[youtube] encrypted signature length 83 (41.41), itag 135, html5 player None
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 974, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 348, in _extract_signature_function
AttributeError: 'NoneType' object has no attribute 'group'

WARNING: Warning: Falling back to static signature algorithm
WARNING: unable to extract html5 player; please report this issue on http://yt-dl.org/bug
[youtube] encrypted signature length 83 (41.41), itag 244, html5 player None
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 974, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 348, in _extract_signature_function
AttributeError: 'NoneType' object has no attribute 'group'

WARNING: Warning: Falling back to static signature algorithm
WARNING: unable to extract html5 player; please report this issue on http://yt-dl.org/bug
[youtube] encrypted signature length 83 (41.41), itag 134, html5 player None
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 974, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 348, in _extract_signature_function
AttributeError: 'NoneType' object has no attribute 'group'

WARNING: Warning: Falling back to static signature algorithm
WARNING: unable to extract html5 player; please report this issue on http://yt-dl.org/bug
[youtube] encrypted signature length 83 (41.41), itag 243, html5 player None
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 974, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 348, in _extract_signature_function
AttributeError: 'NoneType' object has no attribute 'group'

WARNING: Warning: Falling back to static signature algorithm
WARNING: unable to extract html5 player; please report this issue on http://yt-dl.org/bug
[youtube] encrypted signature length 83 (41.41), itag 133, html5 player None
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 974, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 348, in _extract_signature_function
AttributeError: 'NoneType' object has no attribute 'group'

WARNING: Warning: Falling back to static signature algorithm
WARNING: unable to extract html5 player; please report this issue on http://yt-dl.org/bug
[youtube] encrypted signature length 83 (41.41), itag 242, html5 player None
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 974, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 348, in _extract_signature_function
AttributeError: 'NoneType' object has no attribute 'group'

WARNING: Warning: Falling back to static signature algorithm
WARNING: unable to extract html5 player; please report this issue on http://yt-dl.org/bug
[youtube] encrypted signature length 83 (41.41), itag 160, html5 player None
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 974, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 348, in _extract_signature_function
AttributeError: 'NoneType' object has no attribute 'group'

WARNING: Warning: Falling back to static signature algorithm
WARNING: unable to extract html5 player; please report this issue on http://yt-dl.org/bug
[youtube] encrypted signature length 83 (41.41), itag 278, html5 player None
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 974, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 348, in _extract_signature_function
AttributeError: 'NoneType' object has no attribute 'group'

WARNING: Warning: Falling back to static signature algorithm
WARNING: unable to extract html5 player; please report this issue on http://yt-dl.org/bug
[youtube] encrypted signature length 83 (41.41), itag 140, html5 player None
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 974, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 348, in _extract_signature_function
AttributeError: 'NoneType' object has no attribute 'group'

WARNING: Warning: Falling back to static signature algorithm
WARNING: unable to extract html5 player; please report this issue on http://yt-dl.org/bug
[youtube] encrypted signature length 83 (41.41), itag 171, html5 player None
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 974, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 348, in _extract_signature_function
AttributeError: 'NoneType' object has no attribute 'group'

WARNING: Warning: Falling back to static signature algorithm
WARNING: unable to extract html5 player; please report this issue on http://yt-dl.org/bug
[youtube] encrypted signature length 83 (41.41), itag 249, html5 player None
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 974, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 348, in _extract_signature_function
AttributeError: 'NoneType' object has no attribute 'group'

WARNING: Warning: Falling back to static signature algorithm
WARNING: unable to extract html5 player; please report this issue on http://yt-dl.org/bug
[youtube] encrypted signature length 83 (41.41), itag 250, html5 player None
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 974, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 348, in _extract_signature_function
AttributeError: 'NoneType' object has no attribute 'group'

WARNING: Warning: Falling back to static signature algorithm
WARNING: unable to extract html5 player; please report this issue on http://yt-dl.org/bug
[youtube] encrypted signature length 83 (41.41), itag 251, html5 player None
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 974, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 348, in _extract_signature_function
AttributeError: 'NoneType' object has no attribute 'group'

WARNING: Warning: Falling back to static signature algorithm
WARNING: unable to extract html5 player; please report this issue on http://yt-dl.org/bug
[youtube] encrypted signature length 83 (41.41), itag 137, html5 player None
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 974, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 348, in _extract_signature_function
AttributeError: 'NoneType' object has no attribute 'group'

WARNING: Warning: Falling back to static signature algorithm
WARNING: unable to extract html5 player; please report this issue on http://yt-dl.org/bug
[youtube] encrypted signature length 83 (41.41), itag 248, html5 player None
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 974, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 348, in _extract_signature_function
AttributeError: 'NoneType' object has no attribute 'group'

WARNING: Warning: Falling back to static signature algorithm
WARNING: unable to extract html5 player; please report this issue on http://yt-dl.org/bug
[youtube] encrypted signature length 83 (41.41), itag 136, html5 player None
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 974, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 348, in _extract_signature_function
AttributeError: 'NoneType' object has no attribute 'group'

WARNING: Warning: Falling back to static signature algorithm
WARNING: unable to extract html5 player; please report this issue on http://yt-dl.org/bug
[youtube] encrypted signature length 83 (41.41), itag 247, html5 player None
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 974, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 348, in _extract_signature_function
AttributeError: 'NoneType' object has no attribute 'group'

WARNING: Warning: Falling back to static signature algorithm
WARNING: unable to extract html5 player; please report this issue on http://yt-dl.org/bug
[youtube] encrypted signature length 83 (41.41), itag 135, html5 player None
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 974, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 348, in _extract_signature_function
AttributeError: 'NoneType' object has no attribute 'group'

WARNING: Warning: Falling back to static signature algorithm
WARNING: unable to extract html5 player; please report this issue on http://yt-dl.org/bug
[youtube] encrypted signature length 83 (41.41), itag 244, html5 player None
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 974, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 348, in _extract_signature_function
AttributeError: 'NoneType' object has no attribute 'group'

WARNING: Warning: Falling back to static signature algorithm
WARNING: unable to extract html5 player; please report this issue on http://yt-dl.org/bug
[youtube] encrypted signature length 83 (41.41), itag 134, html5 player None
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 974, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 348, in _extract_signature_function
AttributeError: 'NoneType' object has no attribute 'group'

WARNING: Warning: Falling back to static signature algorithm
WARNING: unable to extract html5 player; please report this issue on http://yt-dl.org/bug
[youtube] encrypted signature length 83 (41.41), itag 243, html5 player None
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 974, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 348, in _extract_signature_function
AttributeError: 'NoneType' object has no attribute 'group'

WARNING: Warning: Falling back to static signature algorithm
WARNING: unable to extract html5 player; please report this issue on http://yt-dl.org/bug
[youtube] encrypted signature length 83 (41.41), itag 133, html5 player None
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 974, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 348, in _extract_signature_function
AttributeError: 'NoneType' object has no attribute 'group'

WARNING: Warning: Falling back to static signature algorithm
WARNING: unable to extract html5 player; please report this issue on http://yt-dl.org/bug
[youtube] encrypted signature length 81 (41.39), itag 242, html5 player None
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 974, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 348, in _extract_signature_function
AttributeError: 'NoneType' object has no attribute 'group'

WARNING: Warning: Falling back to static signature algorithm
WARNING: unable to extract html5 player; please report this issue on http://yt-dl.org/bug
[youtube] encrypted signature length 83 (41.41), itag 160, html5 player None
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 974, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 348, in _extract_signature_function
AttributeError: 'NoneType' object has no attribute 'group'

WARNING: Warning: Falling back to static signature algorithm
WARNING: unable to extract html5 player; please report this issue on http://yt-dl.org/bug
[youtube] encrypted signature length 83 (41.41), itag 278, html5 player None
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 974, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 348, in _extract_signature_function
AttributeError: 'NoneType' object has no attribute 'group'

WARNING: Warning: Falling back to static signature algorithm
WARNING: unable to extract html5 player; please report this issue on http://yt-dl.org/bug
[youtube] encrypted signature length 83 (41.41), itag 140, html5 player None
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 974, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 348, in _extract_signature_function
AttributeError: 'NoneType' object has no attribute 'group'

WARNING: Warning: Falling back to static signature algorithm
WARNING: unable to extract html5 player; please report this issue on http://yt-dl.org/bug
[youtube] encrypted signature length 83 (41.41), itag 171, html5 player None
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 974, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 348, in _extract_signature_function
AttributeError: 'NoneType' object has no attribute 'group'

WARNING: Warning: Falling back to static signature algorithm
WARNING: unable to extract html5 player; please report this issue on http://yt-dl.org/bug
[youtube] encrypted signature length 83 (41.41), itag 249, html5 player None
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 974, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 348, in _extract_signature_function
AttributeError: 'NoneType' object has no attribute 'group'

WARNING: Warning: Falling back to static signature algorithm
WARNING: unable to extract html5 player; please report this issue on http://yt-dl.org/bug
[youtube] encrypted signature length 83 (41.41), itag 250, html5 player None
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 974, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 348, in _extract_signature_function
AttributeError: 'NoneType' object has no attribute 'group'

WARNING: Warning: Falling back to static signature algorithm
WARNING: unable to extract html5 player; please report this issue on http://yt-dl.org/bug
[youtube] encrypted signature length 83 (41.41), itag 251, html5 player None
WARNING: Automatic signature extraction failed: Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 974, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 348, in _extract_signature_function
AttributeError: 'NoneType' object has no attribute 'group'

WARNING: Warning: Falling back to static signature algorithm
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 994, in process_info
  File "youtube_dl\YoutubeDL.pyo", line 970, in dl
  File "youtube_dl\downloader\common.pyo", line 290, in download
  File "youtube_dl\downloader\http.pyo", line 54, in real_download
  File "youtube_dl\YoutubeDL.pyo", line 1198, in urlopen
  File "urllib2.pyo", line 410, in open
  File "urllib2.pyo", line 523, in http_response
  File "urllib2.pyo", line 448, in error
  File "urllib2.pyo", line 382, in _call_chain
  File "urllib2.pyo", line 531, in http_error_default
HTTPError: HTTP Error 403: Forbidden

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.
