### ISSUE TITLE
[Mixcloud] Unable to extract track url

### ISSUE THREAD

**Issue by 0xErnie** [rg3/youtube-dl#7839]
Might be related: #7521 (Unable to extract _preview url_)

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'https://www.mixcloud.com/OstbahnhofTechnoMix/sechsunddreizig-36/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.24
[debug] Python version 3.5.0 - Linux-4.2.5-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 2.8.2, ffprobe 2.8.2, rtmpdump 2.4
[debug] Proxy map: {}
[mixcloud] OstbahnhofTechnoMix-sechsunddreizig-36: Downloading webpage
[mixcloud] OstbahnhofTechnoMix-sechsunddreizig-36: Trying mp3 URL
[mixcloud] OstbahnhofTechnoMix-sechsunddreizig-36: Trying m4a URL
ERROR: Unable to extract track url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 663, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/mixcloud.py", line 71, in _real_extract
    raise ExtractorError('Unable to extract track url')
youtube_dl.utils.ExtractorError: Unable to extract track url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by jaimeMF** [comment]
It's fixed in the last version, [you have to update youtube-dl](https://github.com/rg3/youtube-dl/blob/a1b8d815f5716783f5ec9c2b4f60dcdd4d8192d1/README.md#how-do-i-update-youtube-dl)
