### ISSUE TITLE
Regression in youtube-dl

### ISSUE THREAD

**Issue by cmtrindade** [rg3/youtube-dl#7841]
File that I have downloaded before is now unaccessible:

$ youtube-dl --verbose -o ArtBell-ShadowPeople https://www.youtube.com/watch?v=omtRsUqMN6c
[debug] System config: [ ]
[debug] User config: [ ]
[debug] Command-line args: ['--verbose', '-o', 'ArtBell-ShadowPeople', 'https://www.youtube.com/watch?v=omtRsUqMN6c']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.10
[debug] Python version 3.5.0 - Linux-4.1.12-1-MANJARO-x86_64-with-glibc2.3.4
[debug] exe versions: ffmpeg 2.8.1, ffprobe 2.8.1, rtmpdump 2.4
[debug] Proxy map: { }
[youtube] omtRsUqMN6c: Downloading webpage
[youtube] omtRsUqMN6c: Downloading video info webpage
[youtube] omtRsUqMN6c: Extracting video information
[youtube] {43} signature length 43.43, html5 player en_US-vfl2sXoyn
[youtube] omtRsUqMN6c: Downloading player https://s.ytimg.com/yts/jsbin/player-en_US-vfl2sXoyn/base.js
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 817, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 744, in _extract_signature_function
    cache_res = res(test_string)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 796, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 254, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "/usr/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 55, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 135, in interpret_expression
    self._objects[variable] = self.extract_object(variable)
  File "/usr/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 220, in extract_object
    fields = obj_m.group('fields')
AttributeError: 'NoneType' object has no attribute 'group'
 (caused by AttributeError("'NoneType' object has no attribute 'group'",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 817, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 744, in _extract_signature_function
    cache_res = res(test_string)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 796, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 254, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "/usr/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 55, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 135, in interpret_expression
    self._objects[variable] = self.extract_object(variable)
  File "/usr/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 220, in extract_object
    fields = obj_m.group('fields')
AttributeError: 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 817, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 744, in _extract_signature_function
    cache_res = res(test_string)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 796, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 254, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "/usr/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 55, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 135, in interpret_expression
    self._objects[variable] = self.extract_object(variable)
  File "/usr/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 220, in extract_object
    fields = obj_m.group('fields')
AttributeError: 'NoneType' object has no attribute 'group'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 661, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1356, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 827, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 817, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 744, in _extract_signature_function
    cache_res = res(test_string)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 796, in <lambda>
    return lambda s: initial_function([s])
  File "/usr/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 254, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "/usr/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 55, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/usr/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 135, in interpret_expression
    self._objects[variable] = self.extract_object(variable)
  File "/usr/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 220, in extract_object
    fields = obj_m.group('fields')
AttributeError: 'NoneType' object has no attribute 'group'
 (caused by AttributeError("'NoneType' object has no attribute 'group'",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by yan12125** [comment]
You are using an out-dated version (2015.11.10). Please [update your copy](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl). Note that packages provided by distributions (Manjaro or Arch Linux etc.) are usually out-dated.
