### ISSUE TITLE
Failing on DailyMotion Link

### ISSUE THREAD

**Issue by vrajs5** [rg3/youtube-dl#7871]
After latest update I am getting error with dailymotion videos. Following is the log for the same.

user@user-HP-ProBook-430-G2:~$ youtube-dl http://www.dailymotion.com/video/x3gdcog_chh1_lifestyle
[dailymotion] x3gdcog: Downloading webpage
[dailymotion] x3gdcog: Downloading m3u8 information
Traceback (most recent call last):
  File "/usr/bin/youtube-dl", line 6, in <module>
    youtube_dl.main()
  File "/usr/lib/python2.7/dist-packages/youtube_dl/__init__.py", line 410, in main
    _real_main(argv)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/__init__.py", line 400, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1675, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 663, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/dailymotion.py", line 175, in _real_extract
    for subtitle_lang, subtitle in metadata.get('subtitles', {}).get('data', {}).items():
AttributeError: 'list' object has no attribute 'items'

user@user-HP-ProBook-430-G2:~$ youtube-dl --version
2015.12.09

OS is ubuntu 14.04

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.
