### ISSUE TITLE
ValueError: time data '' does not match format '%Y%m%d'

### ISSUE THREAD

**Issue by RBmoimoi** [rg3/youtube-dl#7875]
using version 2015.12.13

#772 looks similar but thats old and mine does not print any time data.
also tried other videos without proxy.

```
python3 /tmp/mnt/usb/scripts/youtube-dl --proxy "157.7.242.91:8080" --no-check-certificate -f 22 https://www.youtube.com/watch?v=eRp6kHSbdN8
WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
[youtube] eRp6kHSbdN8: Downloading webpage
[youtube] eRp6kHSbdN8: Downloading video info webpage
[youtube] eRp6kHSbdN8: Extracting video information
[youtube] eRp6kHSbdN8: Downloading DASH manifest
[youtube] eRp6kHSbdN8: Downloading DASH manifest
Traceback (most recent call last):
  File "/opt/lib/python3.2/runpy.py", line 160, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/opt/lib/python3.2/runpy.py", line 73, in _run_code
    exec(code, run_globals)
  File "/tmp/mnt/usb/scripts/youtube-dl/__main__.py", line 19, in <module>
  File "/tmp/mnt/usb/scripts/youtube-dl/youtube_dl/__init__.py", line 410, in main
  File "/tmp/mnt/usb/scripts/youtube-dl/youtube_dl/__init__.py", line 400, in _real_main
  File "/tmp/mnt/usb/scripts/youtube-dl/youtube_dl/YoutubeDL.py", line 1675, in download
  File "/tmp/mnt/usb/scripts/youtube-dl/youtube_dl/YoutubeDL.py", line 674, in extract_info
  File "/tmp/mnt/usb/scripts/youtube-dl/youtube_dl/YoutubeDL.py", line 720, in process_ie_result
  File "/tmp/mnt/usb/scripts/youtube-dl/youtube_dl/YoutubeDL.py", line 1345, in process_video_result
  File "/tmp/mnt/usb/scripts/youtube-dl/youtube_dl/YoutubeDL.py", line 1416, in process_info
  File "/tmp/mnt/usb/scripts/youtube-dl/youtube_dl/YoutubeDL.py", line 608, in _match_entry
  File "/tmp/mnt/usb/scripts/youtube-dl/youtube_dl/utils.py", line 1029, in __contains__
  File "/tmp/mnt/usb/scripts/youtube-dl/youtube_dl/utils.py", line 992, in date_from_str
  File "/opt/lib/python3.2/_strptime.py", line 488, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/opt/lib/python3.2/_strptime.py", line 337, in _strptime
    (data_string, format))
ValueError: time data '' does not match format '%Y%m%d'
```

**Comment by dstftw** [comment]
Post the output of `python3 /tmp/mnt/usb/scripts/youtube-dl --proxy "157.7.242.91:8080" --no-check-certificate -f 22 https://www.youtube.com/watch?v=eRp6kHSbdN8 --dump-pages`.

**Comment by RBmoimoi** [comment]
The comment was too long

http://pastebin.com/PdXDQ3DK

**Comment by dstftw** [comment]
This log misses [important `[debug] ...` info](https://github.com/rg3/youtube-dl#bugs).

**Comment by RBmoimoi** [comment]
oops notification mail ignored `-v`
http://pastebin.com/6N7Jb9XQ

**Comment by dstftw** [comment]
Have you modified the source code?

**Comment by RBmoimoi** [comment]
nope downloaded and used it right away

**Comment by dstftw** [comment]
Post the output of `md5sum /tmp/mnt/usb/scripts/youtube-dl`.

**Comment by RBmoimoi** [comment]
```2be0126739e0abd48cbf660bd8291c05```

**Comment by lassuviz** [comment]
I got the very same issue here (for all videos on youtube), but I have managed to fix it.
Around line 610 in YoutubeDL.py comment out the following 2 lines:

 # lassuviz null date fix
 #            if date not in dateRange:
 #                return '%s upload date is not in range %s' % (date_from_str(date).isoformat(), dateRange)

Apply these 2 #  and youtube-dl will start to download videos !!!

I am not sure if it has side-effect for special download cases (ie. daterange), but works well flawlessly on normal and playlist download on youtube. :)

I am not python expert, nor familiar with the internals of youtube-dl but I think some system (including mine) supplies/parses date in a wrong manner. 

If  someone could make this null date fix properly on the code-base (regarding my finding) I would be very happy, because I just love youtube-dl project. It is just great!

**Comment by yan12125** [comment]
I guess this is caused by broken ```wcsftime``` in libc. See #9557 for how to check libc. Feel free to leave a comment if your libc is working while youtube-dl not.
