### ISSUE TITLE
ExtractorError ("Could not find JS function u'gr'")

### ISSUE THREAD

**Issue by Matricx-0** [rg3/youtube-dl#7901]
When using the youtube-dl with the following argument 
"http://www.youtube.com/watch?v=FOP_PPavoLA --verbose", the following verbose output is generated:

youtube-dl http://www.youtube.com/watch?v=FOP_PPavoLA
[youtube] FOP_PPavoLA: Downloading webpage
[youtube] FOP_PPavoLA: Downloading video info webpage
[youtube] FOP_PPavoLA: Extracting video information
[youtube] FOP_PPavoLA: Downloading js player en_US-vflXJM_5_
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 877, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 792, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 855, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/jsinterp.py", line 241, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
ExtractorError: Could not find JS function u'gr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Could not find JS function u'gr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
pi@raspberrypi ~ $ youtube-dl http://www.youtube.com/watch?v=FOP_PPavoLA --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://www.youtube.com/watch?v=FOP_PPavoLA', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.12.13
[debug] Python version 2.7.3 - Linux-4.1.7-v7+-armv7l-with-debian-7.8
[debug] exe versions: avconv 9.14-6, avprobe 9.14-6
[debug] Proxy map: {}
[youtube] FOP_PPavoLA: Downloading webpage
[youtube] FOP_PPavoLA: Downloading video info webpage
[youtube] FOP_PPavoLA: Extracting video information
[youtube] {22} signature length 43.43, html5 player en_US-vflXJM_5_
[youtube] FOP_PPavoLA: Downloading player https://s.ytimg.com/yts/jsbin/player-en_US-vflXJM_5_/base.js
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 877, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 792, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 855, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/jsinterp.py", line 241, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
ExtractorError: Could not find JS function u'gr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Could not find JS function u'gr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 877, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 792, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 855, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/jsinterp.py", line 241, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
ExtractorError: Could not find JS function u'gr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 663, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 1431, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 887, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 877, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 792, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 855, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/jsinterp.py", line 241, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
ExtractorError: Could not find JS function u'gr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Could not find JS function u'gr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by pilovali** [comment]
It also happens with http://www.youtube.com/watch?v=YQHsXMglC9A.

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://www.youtube.com/watch?v=YQHsXMglC9A', u'--v
erbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2015.12.13
[debug] Python version 2.7.10 - Windows-2008ServerR2-6.1.7601-SP1
[debug] exe versions: ffmpeg N-76860-g72eaf72, ffprobe N-76860-g72eaf72
[debug] Proxy map: {}
[youtube] YQHsXMglC9A: Downloading webpage
[youtube] YQHsXMglC9A: Downloading video info webpage
[youtube] YQHsXMglC9A: Extracting video information
[youtube] {22} signature length 43.43, html5 player en_US-vflXJM_5_
[youtube] YQHsXMglC9A: Downloading player https://s.ytimg.com/yts/jsbin/player-e
n_US-vflXJM_5_/base.js
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 877, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 792, in _extract_signature_funct
ion
  File "youtube_dl\extractor\youtube.pyo", line 855, in _parse_sig_js
  File "youtube_dl\jsinterp.pyo", line 241, in extract_function
ExtractorError: Could not find JS function u'gr'; please report this issue on ht
tps://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-
dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include
 its complete output.
 (caused by ExtractorError(u"Could not find JS function u'gr'; please report thi
s issue on https://yt-dl.org/bug . Make sure you are using the latest version; t
ype  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose fla
g and include its complete output.",)); please report this issue on https://yt-d
l.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to
update. Be sure to call youtube-dl with the --verbose flag and include its compl
ete output.
Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 877, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 792, in _extract_signature_funct
ion
  File "youtube_dl\extractor\youtube.pyo", line 855, in _parse_sig_js
  File "youtube_dl\jsinterp.pyo", line 241, in extract_function
ExtractorError: Could not find JS function u'gr'; please report this issue on ht
tps://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-
dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include
 its complete output.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 663, in extract_info
  File "youtube_dl\extractor\common.pyo", line 290, in extract
  File "youtube_dl\extractor\youtube.pyo", line 1431, in _real_extract
  File "youtube_dl\extractor\youtube.pyo", line 887, in _decrypt_signature
ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 877, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 792, in _extract_signature_funct
ion
  File "youtube_dl\extractor\youtube.pyo", line 855, in _parse_sig_js
  File "youtube_dl\jsinterp.pyo", line 241, in extract_function
ExtractorError: Could not find JS function u'gr'; please report this issue on ht
tps://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-
dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include
 its complete output.
 (caused by ExtractorError(u"Could not find JS function u'gr'; please report thi
s issue on https://yt-dl.org/bug . Make sure you are using the latest version; t
ype  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose fla
g and include its complete output.",)); please report this issue on https://yt-d
l.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to
update. Be sure to call youtube-dl with the --verbose flag and include its compl
ete output.

**Comment by phihag** [comment]
Thank you for the report. I believe this issue to be fixed in the current version of youtube-dl, 2015.12.18. See [our FAQ](https://yt-dl.org/update) if you need help updating.

**Comment by Matricx-0** [comment]
Thanks for the swift response.

Fix confirmed.

**Comment by llpinokio** [comment]
Ty working normally again

**Comment by zunjae** [comment]
It is still present even after a deleting and reinstalling. http://i.imgur.com/pDutLaa.png Is this related to my python version? my youtube-dl is up to date (2015.12.18)

**Comment by dstftw** [comment]
@zunjae post the **full** output of youtube-dl when run [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by dw9694** [comment]
Thanks. it running!

**Comment by zunjae** [comment]
@dstftw the error is **only** present while using mpsyt. I've also updated that but I still get errors

mpsyt --version
mpsyt version  : 0.2.5

youtube-dl --version
2015.12.18

**Comment by dstftw** [comment]
@zunjae this is youtube-dl issue tracker not mpsyt. Open a new issue if you can reproduce with latest youtube-dl used directly.

**Comment by playqwerty01** [comment]
hi . same bug with this video 

youtube-dl https://www.youtube.com/watch?v=XrrCrtyM4Bg --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'https://www.youtube.com/watch?v=XrrCrtyM4Bg', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.22
[debug] Python version 2.7.12 - Linux-4.6.0-kali1-amd64-x86_64-with-Kali-kali-rolling-kali-rolling
[debug] exe versions: ffmpeg 3.0.2-4, ffprobe 3.0.2-4, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] XrrCrtyM4Bg: Downloading webpage
[youtube] XrrCrtyM4Bg: Downloading video info webpage
[youtube] XrrCrtyM4Bg: Extracting video information
[youtube] {22} signature length 43.40, html5 player en_US-vflL1__zc
[youtube] XrrCrtyM4Bg: Downloading player https://s.ytimg.com/yts/jsbin/player-en_US-vflL1__zc/base.js
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 905, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 820, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 883, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/jsinterp.py", line 241, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
ExtractorError: Could not find JS function u'ur'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Could not find JS function u'ur'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 905, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 820, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 883, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/jsinterp.py", line 241, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
ExtractorError: Could not find JS function u'ur'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 666, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 316, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 1407, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 915, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 905, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 820, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 883, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/jsinterp.py", line 241, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
ExtractorError: Could not find JS function u'ur'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Could not find JS function u'ur'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
@playqwerty01 You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.

**Comment by iqbalu** [comment]
youtube-dl --version --> 2016.04.06
[youtube] -0YdHqlKV8w: Downloading webpage
[youtube] -0YdHqlKV8w: Downloading video info webpage
[youtube] -0YdHqlKV8w: Extracting video information
[youtube] -0YdHqlKV8w: Downloading js player en_US-vflbQww0A
[0;31mERROR:[0m Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 989, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 904, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 967, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/jsinterp.py", line 241, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
ExtractorError: Could not find JS function u'tr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Could not find JS function u'tr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
>> cmd = sprintf('youtube-dl --verbose --no-check-certificate --proxy "202.47.236.242:8080" %s', video_url);
>> system(cmd);
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'--no-check-certificate', u'--proxy', u'202.47.236.242:8080', u'https://www.youtube.com/watch?v=-0YdHqlKV8w']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.04.06
[debug] Python version 2.7.12 - Linux-3.13.0-43-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 1.2.6-7, avprobe 1.2.6-7, ffmpeg 2.2.3, ffprobe 2.2.3, rtmpdump 2.4
[debug] Proxy map: {u'http': u'202.47.236.242:8080', u'https': u'202.47.236.242:8080'}
[youtube] -0YdHqlKV8w: Downloading webpage
[youtube] -0YdHqlKV8w: Downloading video info webpage
[youtube] -0YdHqlKV8w: Extracting video information
[youtube] {22} signature length 43.40, html5 player en_US-vflbQww0A
[youtube] -0YdHqlKV8w: Downloading player https://s.ytimg.com/yts/jsbin/player-en_US-vflbQww0A/base.js
[0;31mERROR:[0m Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 989, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 904, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 967, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/jsinterp.py", line 241, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
ExtractorError: Could not find JS function u'tr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Could not find JS function u'tr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 989, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 904, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 967, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/jsinterp.py", line 241, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
ExtractorError: Could not find JS function u'tr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 669, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 323, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 1562, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 999, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 989, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 904, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 967, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/jsinterp.py", line 241, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
ExtractorError: Could not find JS function u'tr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Could not find JS function u'tr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by yan12125** [comment]
The latest version is 2016.07.17, 2016.04.06 is quite old.

**Comment by iqbalu** [comment]
worked!

**Comment by Premanandh-S** [comment]
Simple method
Remove the package by run the following command in terminal 
 > sudo apt-get remove -f youtube-dl
Reinstall the package by run the following command 
>  sudo apt-get install youtube-dl

**Comment by sietse85** [comment]
version 2016.02.22
same error

**Comment by yan12125** [comment]
@sietse85 2016.02.22 is too old for youtube-dl. The latest version is 2016.09.04.1.

**Comment by sietse85** [comment]
Thanks, DL the latest version and put in /usr/loca/bin working perfect
