### ISSUE TITLE
Youtube video won't be downloaded by YOUTUBE-DL..

### ISSUE THREAD

**Issue by nmr50** [rg3/youtube-dl#7904]
Hello everyone! Got some strange results trying to get formats info and trying to get this video:
https://www.youtube.com/watch?v=vfFxLqiHu2w

youtube-dl v2015.12.18 -v output log is here:
C:\temp>youtube-dl.exe -v https://www.youtube.com/watch?v=vfFxLqiHu2w
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=vfFxLqiHu2w']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2015.12.13
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-77085-g21fbc41, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] vfFxLqiHu2w: Downloading webpage
[youtube] vfFxLqiHu2w: Downloading video info webpage
[youtube] vfFxLqiHu2w: Extracting video information
[youtube] {22} signature length 43.43, html5 player en_US-vflXJM_5_
[youtube] vfFxLqiHu2w: Downloading player https://s.ytimg.com/yts/jsbin/player-en_US-vflXJM_5_/base.js
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 877, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 792, in _extract_signature_function
  File "youtube_dl\extractor\youtube.pyo", line 855, in _parse_sig_js
  File "youtube_dl\jsinterp.pyo", line 241, in extract_function
ExtractorError: Could not find JS function u'gr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Could not find JS function u'gr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to
update. Be sure to call youtube-dl with the --verbose flag and include its compl
ete output.
Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 877, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 792, in _extract_signature_function
  File "youtube_dl\extractor\youtube.pyo", line 855, in _parse_sig_js
  File "youtube_dl\jsinterp.pyo", line 241, in extract_function
ExtractorError: Could not find JS function u'gr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 663, in extract_info
  File "youtube_dl\extractor\common.pyo", line 290, in extract
  File "youtube_dl\extractor\youtube.pyo", line 1431, in _real_extract
  File "youtube_dl\extractor\youtube.pyo", line 887, in _decrypt_signature
ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 877, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 792, in _extract_signature_function
  File "youtube_dl\extractor\youtube.pyo", line 855, in _parse_sig_js
  File "youtube_dl\jsinterp.pyo", line 241, in extract_function
ExtractorError: Could not find JS function u'gr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Could not find JS function u'gr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to
update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Please fix the thing because one of many youtube downloading sites got 720p video w/o problems..
Thanks in advance!
-t

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.

**Comment by nmr50** [comment]
Heck, seems like running youtube-dl -U process w/o success, now I see that I use 2015.12.18 version for sure and this one is getting mentioned video as it supposed to. Thanks!
