### ISSUE TITLE
ExtractorError: Could not find JS function u'gr'

### ISSUE THREAD

**Issue by schachmat** [rg3/youtube-dl#7913]
[debug] System config: []
    [debug] User config: [u'-f', u'best']
    [debug] Command-line args: [u'--verbose', u'https://www.youtube.com/watch?v=cEPazLTGceI']
    [debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
    [debug] youtube-dl version 2015.12.13
    [debug] Python version 2.7.10 - Linux-4.3.0-gentoo-x86_64-Intel-R-_Core-TM-_i7-4600U_CPU_@_2.10GHz-with-gentoo-2.2
    [debug] exe versions: ffmpeg 2.8.3, ffprobe 2.8.3, rtmpdump 2.4
    [debug] Proxy map: {}
    [youtube] cEPazLTGceI: Downloading webpage
    [youtube] cEPazLTGceI: Downloading video info webpage
    [youtube] cEPazLTGceI: Extracting video information
    [youtube] {22} signature length 43.43, html5 player en_US-vflXJM_5_
    [youtube] cEPazLTGceI: Downloading player https://s.ytimg.com/yts/jsbin/player-en_US-vflXJM_5_/base.js
    ERROR: Signature extraction failed: Traceback (most recent call last):
      File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 877, in _decrypt_signature
        video_id, player_url, s
      File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 792, in _extract_signature_function
        res = self._parse_sig_js(code)
      File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 855, in _parse_sig_js
        initial_function = jsi.extract_function(funcname)
      File "/usr/lib64/python2.7/site-packages/youtube_dl/jsinterp.py", line 241, in extract_function
        raise ExtractorError('Could not find JS function %r' % funcname)
    ExtractorError: Could not find JS function u'gr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
     (caused by ExtractorError(u"Could not find JS function u'gr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete
    output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
    Traceback (most recent call last):
      File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 877, in _decrypt_signature
        video_id, player_url, s
      File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 792, in _extract_signature_function
        res = self._parse_sig_js(code)
      File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 855, in _parse_sig_js
        initial_function = jsi.extract_function(funcname)
      File "/usr/lib64/python2.7/site-packages/youtube_dl/jsinterp.py", line 241, in extract_function
        raise ExtractorError('Could not find JS function %r' % funcname)
    ExtractorError: Could not find JS function u'gr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
    Traceback (most recent call last):
      File "/usr/lib64/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 663, in extract_info
        ie_result = ie.extract(url)
      File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/common.py", line 290, in extract
        return self._real_extract(url)
      File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 1431, in _real_extract
        encrypted_sig, video_id, player_url, age_gate)
      File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 887, in _decrypt_signature
        'Signature extraction failed: ' + tb, cause=e)
    ExtractorError: Signature extraction failed: Traceback (most recent call last):
      File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 877, in _decrypt_signature
        video_id, player_url, s
      File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 792, in _extract_signature_function
        res = self._parse_sig_js(code)
      File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 855, in _parse_sig_js
        initial_function = jsi.extract_function(funcname)
      File "/usr/lib64/python2.7/site-packages/youtube_dl/jsinterp.py", line 241, in extract_function
        raise ExtractorError('Could not find JS function %r' % funcname)
    ExtractorError: Could not find JS function u'gr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
     (caused by ExtractorError(u"Could not find JS function u'gr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete
    output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.
