### ISSUE TITLE
Unable to download

### ISSUE THREAD

**Issue by malitech** [rg3/youtube-dl#7914]
Couldn't download this video:
youtube-dl -F --verbose https://www.youtube.com/watch?v=DLiXPbjaZrA
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://www.youtube.com/watch?v=DLiXPbjaZrA']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2015.11.27.1
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] DLiXPbjaZrA: Downloading webpage
[youtube] DLiXPbjaZrA: Downloading video info webpage
[youtube] DLiXPbjaZrA: Extracting video information
[youtube] {22} signature length 43.43, html5 player en_US-vflXJM_5_
[youtube] DLiXPbjaZrA: Downloading player https://s.ytimg.com/yts/jsbin/player-en_US-vflXJM_5_/base.
js
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 856, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 771, in _extract_signature_function
  File "youtube_dl\extractor\youtube.pyo", line 834, in _parse_sig_js
  File "youtube_dl\jsinterp.pyo", line 241, in extract_function
ExtractorError: Could not find JS function u'gr'; please report this issue on https://yt-dl.org/bug
. Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtub
e-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Could not find JS function u'gr'; please report this issue on https://y
t-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure t
o call youtube-dl with the --verbose flag and include its complete output.",)); please report this i
ssue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to
update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 856, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 771, in _extract_signature_function
  File "youtube_dl\extractor\youtube.pyo", line 834, in _parse_sig_js
  File "youtube_dl\jsinterp.pyo", line 241, in extract_function
ExtractorError: Could not find JS function u'gr'; please report this issue on https://yt-dl.org/bug
. Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtub
e-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 663, in extract_info
  File "youtube_dl\extractor\common.pyo", line 290, in extract
  File "youtube_dl\extractor\youtube.pyo", line 1410, in _real_extract
  File "youtube_dl\extractor\youtube.pyo", line 866, in _decrypt_signature
ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 856, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 771, in _extract_signature_function
  File "youtube_dl\extractor\youtube.pyo", line 834, in _parse_sig_js
  File "youtube_dl\jsinterp.pyo", line 241, in extract_function
ExtractorError: Could not find JS function u'gr'; please report this issue on https://yt-dl.org/bug
. Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtub
e-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Could not find JS function u'gr'; please report this issue on https://y
t-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure t
o call youtube-dl with the --verbose flag and include its complete output.",)); please report this i
ssue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to
update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.
