### ISSUE TITLE
Errors downloading from youtube

### ISSUE THREAD

**Issue by klaramalinowska** [rg3/youtube-dl#7932]
Repetitive error using youtube-dl installed through MacPorts on mac OSX 10.9.5

>> youtube-dl --extract-audio --ignore-errors --audio-format mp3 --verbose https://www.youtube.com/watch?v=pbMgo0__ETg
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--extract-audio', u'--ignore-errors', u'--audio-format', u'mp3', u'--verbose', u'https://www.youtube.com/watch?v=pbMgo0__ETg']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.12.13
[debug] Python version 2.7.11 - Darwin-13.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.8.3, ffprobe 2.8.3
[debug] Proxy map: {}
[youtube] pbMgo0__ETg: Downloading webpage
[youtube] pbMgo0__ETg: Downloading video info webpage
[youtube] pbMgo0__ETg: Extracting video information
[youtube] {43} signature length 43.43, html5 player en_US-vflrSqbyh
[youtube] pbMgo0__ETg: Downloading player https://s.ytimg.com/yts/jsbin/player-en_US-vflrSqbyh/base.js
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/opt/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 877, in _decrypt_signature
    video_id, player_url, s
  File "/opt/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 792, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/opt/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 855, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/opt/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 241, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
ExtractorError: Could not find JS function u'gr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Could not find JS function u'gr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/opt/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 877, in _decrypt_signature
    video_id, player_url, s
  File "/opt/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 792, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/opt/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 855, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/opt/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 241, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
ExtractorError: Could not find JS function u'gr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/opt/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 663, in extract_info
    ie_result = ie.extract(url)
  File "/opt/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/opt/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1431, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/opt/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 887, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/opt/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 877, in _decrypt_signature
    video_id, player_url, s
  File "/opt/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 792, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/opt/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 855, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/opt/local/bin/youtube-dl/youtube_dl/jsinterp.py", line 241, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
ExtractorError: Could not find JS function u'gr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Could not find JS function u'gr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by phihag** [comment]
You are using an outdated version of youtube-dl. See [our FAQ](https://yt-dl.org/update) if you need help updating.
