### ISSUE TITLE
AttributeError: 'unicode' object has no attribute 'tb_frame'

### ISSUE THREAD

**Issue by remitamine** [rg3/youtube-dl#7936]
```
youtube-dl -v http://www.audiomack.com/song/xclusiveszone/take-kare
[debug] System config: []
[debug] User config: [u'--external-downloader', u'aria2c', u'--external-downloader-args', u'-x 16', u'-f', u'[height<=?720]', u'--sub-lang', u'ar,arME,en', u'--write-sub', u'--no-check-certificate']
[debug] Command-line args: [u'-v', u'http://www.audiomack.com/song/xclusiveszone/take-kare']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.12.21
[debug] Git HEAD: 0f15ad7
[debug] Python version 2.7.11 - Linux-4.2.5-1-ARCH-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 2.8.3, ffprobe 2.8.3, rtmpdump 2.4
[debug] Proxy map: {}
[audiomack] xclusiveszone/take-kare: Downloading JSON metadata
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
    youtube_dl.main()
  File "/home/amine/youtube-dl/youtube_dl/__init__.py", line 410, in main
    _real_main(argv)
  File "/home/amine/youtube-dl/youtube_dl/__init__.py", line 400, in _real_main
    retcode = ydl.download(all_urls)
  File "/home/amine/youtube-dl/youtube_dl/YoutubeDL.py", line 1677, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/home/amine/youtube-dl/youtube_dl/YoutubeDL.py", line 680, in extract_info
    self.report_error(compat_str(e), e.format_traceback())
  File "/home/amine/youtube-dl/youtube_dl/utils.py", line 562, in format_traceback
    return ''.join(traceback.format_tb(self.traceback))
  File "/usr/lib/python2.7/traceback.py", line 76, in format_tb
    return format_list(extract_tb(tb, limit))
  File "/usr/lib/python2.7/traceback.py", line 95, in extract_tb
    f = tb.tb_frame
AttributeError: 'unicode' object has no attribute 'tb_frame'
```

**Comment by coderkd10** [comment]
The supplied url http://www.audiomack.com/song/xclusiveszone/take-kare is generic page.
It contains link to various playlists. So if you want to download a particular playlist/album you should enter its url instead of this generic page's url.
For example - link to this playlist http://www.audiomack.com/album/xclusiveszone/300-days-300-nights is present on the given page, and all its songs are correctly downloaded by youtube-dl
```
> youtube-dl -v http://www.audiomack.com/album/xclusiveszone/300-days-300-nights
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.audiomack.com/album/xclusiveszone/300-days-300-nights']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.12.09
[debug] Python version 2.7.6 - Linux-3.13.0-73-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.18-6, avprobe 9.18-6, ffmpeg 0.8.7-6, rtmpdump 2.4
[debug] Proxy map: {}
[audiomack:album] xclusiveszone/300-days-300-nights: Querying song information (1)
[audiomack:album] xclusiveszone/300-days-300-nights: Querying song information (2)
[audiomack:album] xclusiveszone/300-days-300-nights: Querying song information (3)
[audiomack:album] xclusiveszone/300-days-300-nights: Querying song information (4)
[audiomack:album] xclusiveszone/300-days-300-nights: Querying song information (5)
[audiomack:album] xclusiveszone/300-days-300-nights: Querying song information (6)
[audiomack:album] xclusiveszone/300-days-300-nights: Querying song information (7)
[audiomack:album] xclusiveszone/300-days-300-nights: Querying song information (8)
[audiomack:album] xclusiveszone/300-days-300-nights: Querying song information (9)
[audiomack:album] xclusiveszone/300-days-300-nights: Querying song information (10)
[audiomack:album] xclusiveszone/300-days-300-nights: Querying song information (11)
[audiomack:album] xclusiveszone/300-days-300-nights: Querying song information (12)
[audiomack:album] xclusiveszone/300-days-300-nights: Querying song information (13)
[audiomack:album] xclusiveszone/300-days-300-nights: Querying song information (14)
[audiomack:album] xclusiveszone/300-days-300-nights: Querying song information (15)
[audiomack:album] xclusiveszone/300-days-300-nights: Querying song information (16)
[audiomack:album] xclusiveszone/300-days-300-nights: Querying song information (17)
[audiomack:album] xclusiveszone/300-days-300-nights: Querying song information (18)
[audiomack:album] xclusiveszone/300-days-300-nights: Querying song information (19)
[audiomack:album] xclusiveszone/300-days-300-nights: Querying song information (20)
[download] Downloading playlist: 300 Days 300 Nights
[audiomack:album] playlist 300 Days 300 Nights: Collected 19 video ids (downloading 19 of them)
[download] Downloading video 1 of 19
[debug] Invoking downloader on u'http://music.audiomack.com/albums/xclusiveszone/300-days-300-nights/streaming/intro-prod.-by-c-sick.mp3?Expires=1450716532&Signature=c05nxDesLgc0G7owy6DIm8UA6Etd0PI7zhwDucQH5RinpQwdZz8BjdesGAO7Bl4a~W40B21KyymQZm0g5iWVgkOHxCijEUJdxf-9xtZj25tNUVLxV6CABtb3iadW4CyGnp0Z7yNWSUs0tiktU5-XY~DPTt~mnAOp9lhfC~B9C7A_&Key-Pair-Id=APKAIKAIRXBA2H7FXITA'
[download] Destination: 300 Days 300 Nights - Intro [Prod. By C-Sick]-1739971.mp3
[download] 100% of 3.89MiB in 00:00
[download] Downloading video 2 of 19
[debug] Invoking downloader on u'http://music.audiomack.com/albums/xclusiveszone/300-days-300-nights/streaming/gunz-n-money-prod.-by-c-sick.mp3?Expires=1450716533&Signature=ZM~BIB007VwpTXKEVF6QklVtkDu3vSyfb4Z9iITOlu4hDm16NKnVJpNIyr0tbMLaeOEfLKp9d0E5hGOx~pCYhQsc~4VRsU5AhiCSjbIpAIAp-uQMvuB~Nvsdak3PN3f-Geea8T0umfoCuxumujnJrGdqpv7MLzkSGOg6Sq5aSTg_&Key-Pair-Id=APKAIKAIRXBA2H7FXITA'
[download] Destination: 300 Days 300 Nights - Gunz N Money [Prod. By C-Sick]-1739974.mp3
[download] 100% of 2.95MiB in 00:01
[download] Downloading video 3 of 19
[debug] Invoking downloader on u'http://music.audiomack.com/albums/xclusiveszone/300-days-300-nights/streaming/make-it-back-prod.-by-inomekindakitchen.mp3?Expires=1450716533&Signature=eZ-FcGwKSns-ECr9KxhkhOaUvkMEyzKslndg-nOc~z5XgGG7wnksMdmEJaczlwDx3PTz0PHviuZ1LWqh1Kw07w4AgtKhAhWTQV6J7fSk4B7c8TT65jk2nJq72rC3UfbXgL3gRDlszH-JgX-vWWr6FD3sKin29JSwH6I9DZvXbvk_&Key-Pair-Id=APKAIKAIRXBA2H7FXITA'
[download] Destination: 300 Days 300 Nights - Make It Back [Prod. By Inomekindakitchen]-1739976.mp3
[download] 100% of 2.68MiB in 00:00
[download] Downloading video 4 of 19
[debug] Invoking downloader on u'http://music.audiomack.com/albums/xclusiveszone/300-days-300-nights/streaming/waffle-house-feat.-young-dolph-prod.-by-c-sick.mp3?Expires=1450716533&Signature=QKp0qPF8ffzmlKli2O2ZsjXRdxDPa7f2omnXHKdnT4VcMjUf47GgORg8ru7nx~b4OR2CkiiPGiBbyczGpTj1drULfmuCtfQx0fACYPPMEw9583w6xJmVdbxGIEXOylOGTYwYr0xB6yWnvtIq74S8EDBquvJXWrRnuvIXVsGUgHQ_&Key-Pair-Id=APKAIKAIRXBA2H7FXITA'
[download] Destination: 300 Days 300 Nights - Waffle House (Feat. Young Dolph) [Prod. By C-Sick]-1739965.mp3
[download] 100% of 3.16MiB in 00:03
[download] Downloading video 5 of 19
[debug] Invoking downloader on u'http://music.audiomack.com/albums/xclusiveszone/300-days-300-nights/streaming/this-case-feat.-hypno-carlito-prod.-by-c-sick.mp3?Expires=1450716533&Signature=CwTDGuNBiple0Vn8ox~G2wYQzUDtdbfwAeXt58YTHGaSwCnfiuKJo78J2SqECixtz1TT0a7Ue5~XA~l0X0siAHXnjskOLV9zouwn3aAu8yQk5NTI5WBfd5n-t5KrQ2mOzT~IQ~g2B1kJnsizU04-PwQSr5gygl6Toiur7dUEEjk_&Key-Pair-Id=APKAIKAIRXBA2H7FXITA'
[download] Destination: 300 Days 300 Nights - This Case (Feat. Hypno Carlito) [Prod. By C-Sick]-1739960.mp3
[download] 100% of 3.19MiB in 00:07
[download] Downloading video 6 of 19
[debug] Invoking downloader on u'http://music.audiomack.com/albums/xclusiveszone/300-days-300-nights/streaming/my-beyonce-feat.-dej-loaf-prod.-by-c-sick.mp3?Expires=1450716533&Signature=iY3iGTqsl--Xcc6Y18dmcFjbMgqk9lpPChP4xjYvGekH0vn86lsQ0YCnXPUDKEGwyZtP9Rtue24-6kultfOu2W3MFl9MttBNtrAI6s5u8W2M~JpaT~Dv0kHNREmpZLttdOSTj~pEO7rLu2QHg8dtnME1cLGlCFceh4dWVwxeXz8_&Key-Pair-Id=APKAIKAIRXBA2H7FXITA'
[download] Destination: 300 Days 300 Nights - My Beyonce (Feat. DeJ Loaf) [Prod. By C-Sick]-1739969.mp3
[download] 100% of 4.34MiB in 00:09
[download] Downloading video 7 of 19
[debug] Invoking downloader on u'http://music.audiomack.com/albums/xclusiveszone/300-days-300-nights/streaming/on-em-prod.-by-murda-beatz.mp3?Expires=1450716534&Signature=cmC9CibFaUYb8as1VOK4nMsAem0vljiA8oSPSv8iK5t--rmg~4RvnK~ktrNn1FoQWDyNqoCumUGLfL4xPtp41ghDabaFwgqV5WGAkA3kbCd9itik06znlxj-iq35sjHqhkLWOS1ugqWPZ97a-3cZb41KPre~RrB2IYZxaw5a~Zc_&Key-Pair-Id=APKAIKAIRXBA2H7FXITA'
[download] Destination: 300 Days 300 Nights - On Em [Prod. By Murda Beatz]-1739973.mp3
[download] 100% of 3.21MiB in 00:04
[download] Downloading video 8 of 19
[debug] Invoking downloader on u'http://music.audiomack.com/albums/xclusiveszone/300-days-300-nights/streaming/believe-it-or-not-prod.-by-nitobeats.mp3?Expires=1450716534&Signature=V6v2qwmXl~Nb1bhauP8X0fx072E-iLlf9Rq7YSsI6jBJ8DqWx~kyHkfpH074-DyVdun0i~QamgIMr7JKZM0005JOETvdvc1xRtwpU156tPqlbPWbJFsPbSv5Fe5SwrdfZ-Mhc69QK6UDwKFPRZg91YvH4cP959-A8Ns0MObM1q0_&Key-Pair-Id=APKAIKAIRXBA2H7FXITA'
[download] Destination: 300 Days 300 Nights - Believe It Or Not [Prod. By NitoBeats]-1739975.mp3
[download] 100% of 1.97MiB in 00:54
[download] Downloading video 9 of 19
[debug] Invoking downloader on u'http://music.audiomack.com/albums/xclusiveszone/300-days-300-nights/streaming/every-night-prod.-by-d.brookz.mp3?Expires=1450716534&Signature=VdwZrqMeOc2OgZsQPj5SdujCKlHKcVnyZLGYgEPO7MZGi~qA6ovgsoWe0dsKN0yvjcuB7wNuQkPO6~fkCfd~ErpI3OizY0pFd9D846YSclQRIh5wbyqxPP1lr41nCQo4MCC5wC3510WSBEYEXfrsNof~G6aCQAi33STYzSP94Cc_&Key-Pair-Id=APKAIKAIRXBA2H7FXITA'
[download] Destination: 300 Days 300 Nights - Every Night [Prod. By D.Brookz]-1739970.mp3
[download] 100% of 3.01MiB in 00:04
[download] Downloading video 10 of 19
[debug] Invoking downloader on u'http://music.audiomack.com/albums/xclusiveszone/300-days-300-nights/streaming/spent-me-feat.-meek-mill-prod.-by-c-sick.mp3?Expires=1450716535&Signature=KRELYnuaRUvDfWyey2k11AcSowOqZ9OQAYtIL0odioqt2AaiQr0rqSZR6bqZoQdMBH4wx0a1MdNGvuGmDoNZ28zeiBnrTKvd4cstudUnFvucctWB1N-q47-QCjsLoWb~34tckV5xJ171~2gR-woJOBLMxKRIBBiCY0Y6PwQ3GGM_&Key-Pair-Id=APKAIKAIRXBA2H7FXITA'
[download] Destination: 300 Days 300 Nights - Spent Me (Feat. Meek Mill) [Prod. By C-Sick]-1739959.mp3
[download] 100% of 3.98MiB in 00:09
[download] Downloading video 11 of 19
[debug] Invoking downloader on u'http://music.audiomack.com/albums/xclusiveszone/300-days-300-nights/streaming/words-from-bump-j.mp3?Expires=1450716535&Signature=hv5U65FoWlm0joJaPccLPQd9ANaj8T-dptQWGvycvq2LNJFKwfYjKV~3XwY9cFpUcIVV2kFtq6gAi1kB50Nz-pnyoyWUY6Rz-Z1bOJzbXjDksF9bLbiVsCvI7b9DKbzlUXHSfK5FZBMixsz5AX2GvonCj~gz1GRw54it6EYPMOY_&Key-Pair-Id=APKAIKAIRXBA2H7FXITA'
[download] Destination: 300 Days 300 Nights - Words From Bump J-1739966.mp3
[download] 100% of 1.17MiB in 00:03
[download] Downloading video 12 of 19
[debug] Invoking downloader on u'http://music.audiomack.com/albums/xclusiveszone/300-days-300-nights/streaming/jump-off-prod.-by-c-sick.mp3?Expires=1450716535&Signature=dsOrgLC6REvMy~IS47pYCDz0W~ewZyeAb6QwrjNPrQ9QIklmku5RmVGG8Q53EOzrmqkr15c1Y6fBIyHyVONy20MC~Z-o~So-D~uqulSmPLB9XXF44B-dFvjON0CXn7rMRbv5-7g94TTfVK6LeWovr7sxK9FiKBmKqHGoxT7xJkw_&Key-Pair-Id=APKAIKAIRXBA2H7FXITA'
[download] Destination: 300 Days 300 Nights - Jump Off [Prod. By C-Sick]-1739962.mp3
[download] 100% of 2.11MiB in 00:02
[download] Downloading video 13 of 19
[debug] Invoking downloader on u'http://music.audiomack.com/albums/xclusiveszone/300-days-300-nights/streaming/on-my-soul-prod.-by-dj-l.mp3?Expires=1450716535&Signature=UQ7d64dGxAshv4K4QqJvw0MV~P2EHyvxIugKhOKfqUIlT-ZPaWGXrByhU4ZO-KNSAHCaA80yVrnQ-0bcksvmshZXUZdzAdmQpTIgOaTnknfOOCfP3GdGNMjE1Qr7NdH8wycLJzizqkPfd5CS7nttZke2iTrBD3Wqg3F0-p8M8Hs_&Key-Pair-Id=APKAIKAIRXBA2H7FXITA'
[download] Destination: 300 Days 300 Nights - On My Soul [Prod. By DJ L]-1739961.mp3
[download] 100% of 2.94MiB in 00:02
[download] Downloading video 14 of 19
[debug] Invoking downloader on u'http://music.audiomack.com/albums/xclusiveszone/300-days-300-nights/streaming/nobody-prod.-by-chopsquad-dj.mp3?Expires=1450716536&Signature=IQVz6h4K73d9Z-qL8EEv9uIuiHzGHXrDhmgB8Dg87e0S3V4n3goyl3P~adYEk6~w~koGBjzwP9nu0Sj67Bn7jwKreSq5asHBNj8eN26FpT1YVYZZXd8HsZUiY2ySo4yJdfM49rXPMSiSgIpw1iR-RqN5DSN4Q4yR0b7C0Hu2ZIM_&Key-Pair-Id=APKAIKAIRXBA2H7FXITA'
[download] Destination: 300 Days 300 Nights - Nobody [Prod. By Chopsquad DJ]-1739967.mp3
[download] 100% of 3.06MiB in 00:02
[download] Downloading video 15 of 19
[debug] Invoking downloader on u'http://music.audiomack.com/albums/xclusiveszone/300-days-300-nights/streaming/street-nigga-prod.-by-dj-l.mp3?Expires=1450716536&Signature=cVOWgJ-TxrTh6TcyfNmCiPyaFz7eSW6Cb8aZzzIJB~De1z8JQWzE4vL~0Sq3FVRkOYEoBXSvtLhNa-A6JMlRKAhdSYNKJWNNWotRUfh~Gj4QJJfVl4-X5qdisehrQ2mDQuYIpg3U4hW~fBMAIpm2Z4xjh9u7vsphQbg8-HwrGt4_&Key-Pair-Id=APKAIKAIRXBA2H7FXITA'
[download] Destination: 300 Days 300 Nights - Street Nigga [Prod. By DJ L]-1739964.mp3
[download] 100% of 1.95MiB in 00:03
[download] Downloading video 16 of 19
[debug] Invoking downloader on u'http://music.audiomack.com/albums/xclusiveszone/300-days-300-nights/streaming/mud.mp3?Expires=1450716536&Signature=drQtyYaQj5~xr-b~bdKatxTIZrc2ZqLjcowB8Zvi3AbiDV6frhZa3lJ414rSIag505m7dogsZxT64u3kAfNfwg6BUUDS3RbirIwCMFOH5M014Pug9iZ-cqkPmX-38YtoFyygXsOkNsMFLIRbK~g5M5rLG6~e4NSAfgEG8eGPA80_&Key-Pair-Id=APKAIKAIRXBA2H7FXITA'
[download] Destination: 300 Days 300 Nights - Mud-1739958.mp3
[download] 100% of 1.93MiB in 00:01
[download] Downloading video 17 of 19
[debug] Invoking downloader on u'http://music.audiomack.com/albums/xclusiveszone/300-days-300-nights/streaming/drug-party-prod.-by-chopsquad-dj.mp3?Expires=1450716536&Signature=ZgbW31uRFmPDpxbVzmZQs445EJ9exNwiuU0GuJNFfDQPGRbwpUfYRPeYBUTaSqlGQyjKgCDHttCBE~7384xR8PmXcwa8MZPSK65M6rpB0awdeaxQULXmvdFprFjAeEgO5K-CpnkJurv3sdAad0p0hKjBgCxuf3UyVhrh8KMyRb4_&Key-Pair-Id=APKAIKAIRXBA2H7FXITA'
[download] Destination: 300 Days 300 Nights - Drug Party [Prod. By Chopsquad DJ]-1739963.mp3
[download] 100% of 2.72MiB in 00:17
[download] Downloading video 18 of 19
[debug] Invoking downloader on u'http://music.audiomack.com/albums/xclusiveszone/300-days-300-nights/streaming/ride-4-me-prod.-by-c-sick.mp3?Expires=1450716537&Signature=Z6ddaVSO7B~octhh3Q6-2HoeumV-ty9C3-DwB62wBm38PMzjkHWZFbSIQRtXi-PSRV~~bOgZiLcs4ps1SGp1GkzdM4-Rg0TwJA3yOWXpRdOsAPRtnaB9RAVGlCD6-fyyLSR~AEloOHFLjJwVXb7xb2ueGeltMY42unwX5U6OzaI_&Key-Pair-Id=APKAIKAIRXBA2H7FXITA'
[download] Destination: 300 Days 300 Nights - Ride 4 Me [Prod. By C-Sick]-1739977.mp3
[download] 100% of 2.95MiB in 00:02
[download] Downloading video 19 of 19
[debug] Invoking downloader on u'http://music.audiomack.com/albums/xclusiveszone/300-days-300-nights/streaming/mean-to-me-feat.-zona-man-future-bonus.mp3?Expires=1450716537&Signature=BRRCIBXiVGMwU5VC7peCWoSyhBTNegSuqBiqnuYWUplJtkZAz218Imt1A~VExVAygkkpiWmiMK~SgSAGhgAWEsmx6ZrVo9ABDFXZCqRV0dDSAxqq-6rswz5XrfNms0jSfnbz2DlOCdK7ZK04fL9bD3aAbDQXDK4hqq2ViiI-1B4_&Key-Pair-Id=APKAIKAIRXBA2H7FXITA'
[download] Destination: 300 Days 300 Nights - Mean To Me (Feat. Zona Man &amp; Future) (Bonus)-1739968.mp3
[download] 100% of 3.27MiB in 00:02
[download] Finished downloading playlist: 300 Days 300 Nights

```

**Comment by remitamine** [comment]
i'm not interested in downloading the playlist.
the url is taken from a test case for audiomack extractor and it fail.
even if the extractor can't extract info from the page, this error `AttributeError: 'unicode' object has no attribute 'tb_frame'` shouldn't happen.
