### ISSUE TITLE
Italian Radio1's Rai problem: "ERROR: Unable to extract iframe"

### ISSUE THREAD

**Issue by pkirk** [rg3/youtube-dl#7945]
```
$ youtube-dl http://www.radio1.rai.it/dl/portaleRadio/media/ContentItem-e9ef8c81-9e17-4747-8c5c-4a241d45a1c3.html
[Rai] e9ef8c81-9e17-4747-8c5c-4a241d45a1c3: Downloading webpage
ERROR: Unable to extract iframe; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
MBP-Paolo:~ paolo$ youtube-dl --verbose http://www.radio1.rai.it/dl/portaleRadio/media/ContentItem-e9ef8c81-9e17-4747-8c5c-4a241d45a1c3.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.radio1.rai.it/dl/portaleRadio/media/ContentItem-e9ef8c81-9e17-4747-8c5c-4a241d45a1c3.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.12.21
[debug] Python version 2.7.10 - Darwin-15.2.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[Rai] e9ef8c81-9e17-4747-8c5c-4a241d45a1c3: Downloading webpage
ERROR: Unable to extract iframe; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 665, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 291, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/rai.py", line 109, in _real_extract
    webpage, 'iframe')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 586, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract iframe; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by remitamine** [comment]
can you listen to to the audio in the browser?

**Comment by pkirk** [comment]
Using the browser works normally.

**Comment by remitamine** [comment]
because recently i added support for audio page extraction.
```
python2 __main__.py -F 'http://www.radio1.rai.it/dl/portaleRadio/media/ContentItem-e9ef8c81-9e17-4747-8c5c-4a241d45a1c3.html'
[RaiTV] e9ef8c81-9e17-4747-8c5c-4a241d45a1c3: Downloading video JSON
[info] Available formats for e9ef8c81-9e17-4747-8c5c-4a241d45a1c3:
format code  extension  resolution note
mp3          mp3        unknown
```
but i can't test if it work because i can't play it in the browser.

**Comment by pkirk** [comment]
How can I test it? I have version 2015.12.23 but the '-F' doesn't work.
(And it tells me [Rai] instead of your [RaiTV])

Thanks,

**Comment by remitamine** [comment]
i will be in the next version.

**Comment by remitamine** [comment]
there is a new version released today you can update and test if it works now.

**Comment by pkirk** [comment]
It works, thanks. If you need me to do some tests, please don't hesitate. Otherwise you can close the issue.

Thanks again,

**Comment by remitamine** [comment]
just to be sure.
can you play the downloaded audio file?

**Comment by pkirk** [comment]
I found that while my OSX is working fine (I can play the downloaded audio file), my Linux Debian Jessie downloaded a 457 Bytes file (instead of 453.64MiB).
```
youtube-dl --verbose http://www.radio1.rai.it/dl/portaleRadio/media/ContentItem-e9ef8c81-9e17-4747-8c5c-4a241d45a1c3.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.radio1.rai.it/dl/portaleRadio/media/ContentItem-e9ef8c81-9e17-4747-8c5c-4a241d45a1c3.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.12.29
[debug] Python version 2.7.9 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.2
[debug] exe versions: none
[debug] Proxy map: {}
[RaiTV] e9ef8c81-9e17-4747-8c5c-4a241d45a1c3: Downloading video JSON
[debug] Invoking downloader on u'http://mediapolisvod.rai.it/relinker/relinkerServlet.htm?cont=cFrAUAQssSlashBH4eeqqEEqual'
[download] Destination: Brasil del 21_12_2015-e9ef8c81-9e17-4747-8c5c-4a241d45a1c3.mp3
[download] 100% of 457.00B in 00:00
```

and that file says:
```
<Mediapolis><url type="content">http://download.rai.it/video_no_available.mp4</url><url type="bumper"></url><url type="bumperend"></url><ct>mp4</ct><bitrate>0</bitrate><smooth>N</smooth><is_live>N</is_live><description>Rai</description><geoprotection>N</geoprotection><category>11111</category><plVod></plVod><plLive></plLive><logo></logo><poster>http://www.rai.tv/dl/RaiTV/2012/images/ogImage.jpg</poster><duration></duration><krpano></krpano></Mediapolis>
```

On the OSX, the verbose output says:
```
$ youtube-dl --verbose http://www.radio1.rai.it/dl/portaleRadio/media/ContentItem-e9ef8c81-9e17-4747-8c5c-4a241d45a1c3.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.radio1.rai.it/dl/portaleRadio/media/ContentItem-e9ef8c81-9e17-4747-8c5c-4a241d45a1c3.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.12.29
[debug] Python version 2.7.10 - Darwin-15.2.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[RaiTV] e9ef8c81-9e17-4747-8c5c-4a241d45a1c3: Downloading video JSON
[debug] Invoking downloader on u'http://mediapolisvod.rai.it/relinker/relinkerServlet.htm?cont=cFrAUAQssSlashBH4eeqqEEqual'
[download] Destination: Brasil del 21_12_2015-e9ef8c81-9e17-4747-8c5c-4a241d45a1c3.mp3
[download] 100% of 453.64MiB in 25:12
```

**Comment by remitamine** [comment]
> my Linux Debian Jessie downloaded a 457 Bytes file.

this is the same error that happen to me when i try to download it(i also use linux).
in the linux system can you play from the webpage in the browser?

**Comment by pkirk** [comment]
That Debian Jessie was a remote server.
I've just tried with my Debian Jessie laptop (w/XFCE) and it works: I can play the webpage and download it.

**Comment by remitamine** [comment]
@pkirk, thanks for help.
i think it is a geo restriction problem i can't fix it.
i will close this issue as it is possible to download it from at least italy and may be other european contries.
