### ISSUE TITLE
Youtube Extractor Error

### ISSUE THREAD

**Issue by fghiufe** [rg3/youtube-dl#7977]
```
$ youtube-dl --version
2015.11.24
```
```
$ youtube-dl https://www.youtube.com/watch?v=ISO94EPI9x8
[youtube] ISO94EPI9x8: Downloading webpage
[youtube] ISO94EPI9x8: Downloading video info webpage
[youtube] ISO94EPI9x8: Extracting video information
[youtube] ISO94EPI9x8: Downloading js player en_US-vflnrstgx
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 856, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 771, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 834, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 241, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'gr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Could not find JS function 'gr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by jaimeMF** [comment]
You are using an outdated version of youtube-dl, [you have to update it](https://github.com/rg3/youtube-dl/blob/fc383f199e73358f88ecf24b7e804dda7400afae/README.md#how-do-i-update-youtube-dl).

**Comment by fghiufe** [comment]
Is it not pushed to the official arch linux repo's yet? I used pacman to install youtube-dl and it's reporting that it's up to date.
```
$ sudo pacman -Syu
:: Synchronising package databases...
 core is up to date
 extra                   1772.2 KiB  5.15M/s 00:00 [######################] 100%
 community is up to date
 multilib is up to date
 archlinuxfr is up to date
:: Starting full system upgrade...
 there is nothing to do
```

**Comment by jaimeMF** [comment]
From the FAQ entry I linked:
> Unfortunately, there is nothing we youtube-dl developers can do if your distribution serves a really outdated version. You can (and should) complain to your distribution in their bugtracker or support forum.

You can still update it manually, but probably pacman will stop tracking it.

**Comment by fghiufe** [comment]
Ah, gotcha. Thanks very much!
