### ISSUE TITLE
Error when using --write-description on some youtube videos

### ISSUE THREAD

**Issue by joaormatos** [rg3/youtube-dl#800]
youtube-dl: 2013.04.22
Python: 2.6.6
OS: Debian Squeeze GNU/Linux amd64

How to reproduce, as of 2013-04-23:

```
$ youtube-dl --write-description http://www.youtube.com/watch?v=fYzDtoYx4vU
[youtube] Setting language
[youtube] fYzDtoYx4vU: Downloading video webpage
[youtube] fYzDtoYx4vU: Downloading video info webpage
[youtube] fYzDtoYx4vU: Extracting video information
[info] Writing video description to: fYzDtoYx4vU.mp4.description
Traceback (most recent call last):
  File "/usr/lib/python2.6/runpy.py", line 122, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.6/runpy.py", line 34, in _run_code
    exec code in run_globals
  File "/afs/ist.utl.pt/users/1/1/ist162511/bin/youtube-dl/__main__.py", line 18, in <module>
  File "/afs/ist.utl.pt/users/1/1/ist162511/bin/youtube-dl/youtube_dl/__init__.py", line 558, in main

  File "/afs/ist.utl.pt/users/1/1/ist162511/bin/youtube-dl/youtube_dl/__init__.py", line 542, in _real_main

  File "/afs/ist.utl.pt/users/1/1/ist162511/bin/youtube-dl/youtube_dl/FileDownloader.py", line 684, in download
  File "/afs/ist.utl.pt/users/1/1/ist162511/bin/youtube-dl/youtube_dl/FileDownloader.py", line 468, in extract_info
  File "/afs/ist.utl.pt/users/1/1/ist162511/bin/youtube-dl/youtube_dl/FileDownloader.py", line 498, in process_ie_result
  File "/afs/ist.utl.pt/users/1/1/ist162511/bin/youtube-dl/youtube_dl/FileDownloader.py", line 600, in process_info
  File "/usr/lib/python2.6/io.py", line 1515, in write
    s.__class__.__name__)
TypeError: can't write str to text stream
```

I have only now begun using the `--write-description` option; this is the only video so far that produces this error.

**Comment by sebma** [comment]
Hi, I have the same problem : 

youtube-dl --verbose --ignore-config --write-description http://www.veoh.com/watch/v46093745wbEGkakh
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'--ignore-config', u'--write-description', u'http://www.veoh.com/watch/v46093745wbEGkakh']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.10.13
[debug] Python version 2.7.8 - Linux-3.16.0-44-generic-x86_64-with-Ubuntu-14.10-utopic
[debug] exe versions: avconv 11.2-6, avprobe 11.2-6, ffmpeg 2.6.2, ffprobe 2.6.2, rtmpdump 2.4
[debug] Proxy map: {}
[Veoh] v46093745wbEGkakh: Downloading video XML
[info] Writing video description to: Pirates Of Silicon Valley-46093745.description
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/__init__.py", line 410, in main
    _real_main(argv)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/__init__.py", line 400, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1665, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 671, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 717, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1335, in process_video_result
    self.process_info(new_info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1465, in process_info
    descfile.write(info_dict['description'])
TypeError: must be unicode, not str

Any idea ?

Seb.
