### ISSUE TITLE
ExtractorError: Could not find JS function u'gr'

### ISSUE THREAD

**Issue by basscadet** [rg3/youtube-dl#8011]
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'-t', u'https://www.youtube.com/watch?v=I2KGqgdgd10']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.10
[debug] Python version 2.7.10 - Darwin-15.2.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.2.1, ffprobe 2.2.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] I2KGqgdgd10: Downloading webpage
[youtube] I2KGqgdgd10: Downloading video info webpage
[youtube] I2KGqgdgd10: Extracting video information
[youtube] {43} signature length 43.43, html5 player en_US-vflnrstgx
[youtube] I2KGqgdgd10: Downloading player https://s.ytimg.com/yts/jsbin/player-en_US-vflnrstgx/base.js
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/Users/makipri/git/youtube-dl/youtube-dl/youtube_dl/extractor/youtube.py", line 817, in _decrypt_signature
    video_id, player_url, s
  File "/Users/makipri/git/youtube-dl/youtube-dl/youtube_dl/extractor/youtube.py", line 732, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/Users/makipri/git/youtube-dl/youtube-dl/youtube_dl/extractor/youtube.py", line 795, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/Users/makipri/git/youtube-dl/youtube-dl/youtube_dl/jsinterp.py", line 241, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
ExtractorError: Could not find JS function u'gr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Could not find JS function u'gr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/Users/makipri/git/youtube-dl/youtube-dl/youtube_dl/extractor/youtube.py", line 817, in _decrypt_signature
    video_id, player_url, s
  File "/Users/makipri/git/youtube-dl/youtube-dl/youtube_dl/extractor/youtube.py", line 732, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/Users/makipri/git/youtube-dl/youtube-dl/youtube_dl/extractor/youtube.py", line 795, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/Users/makipri/git/youtube-dl/youtube-dl/youtube_dl/jsinterp.py", line 241, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
ExtractorError: Could not find JS function u'gr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/Users/makipri/git/youtube-dl/youtube-dl/youtube_dl/YoutubeDL.py", line 661, in extract_info
    ie_result = ie.extract(url)
  File "/Users/makipri/git/youtube-dl/youtube-dl/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/Users/makipri/git/youtube-dl/youtube-dl/youtube_dl/extractor/youtube.py", line 1356, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/Users/makipri/git/youtube-dl/youtube-dl/youtube_dl/extractor/youtube.py", line 827, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/Users/makipri/git/youtube-dl/youtube-dl/youtube_dl/extractor/youtube.py", line 817, in _decrypt_signature
    video_id, player_url, s
  File "/Users/makipri/git/youtube-dl/youtube-dl/youtube_dl/extractor/youtube.py", line 732, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/Users/makipri/git/youtube-dl/youtube-dl/youtube_dl/extractor/youtube.py", line 795, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/Users/makipri/git/youtube-dl/youtube-dl/youtube_dl/jsinterp.py", line 241, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
ExtractorError: Could not find JS function u'gr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Could not find JS function u'gr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by yan12125** [comment]
Version 2015.11.10 is out-dated. Please [update to the latest version (2015.12.23)](https://github.com/rg3/youtube-dl#how-do-i-update-youtube-dl).
