### ISSUE TITLE
RUTV error "No JSON object could be decoded"

### ISSUE THREAD

**Issue by spvkgn** [rg3/youtube-dl#8026]
```
youtube-dl -gv http://live.russia.tv/index/index/channel_id/3
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-gv', 'http://live.russia.tv/index/index/channel_id/3']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.12.23
[debug] Python version 3.2.3 - Linux-3.13.0-68-generic-i686-with-LinuxMint-13-maya
[debug] exe versions: ffmpeg 2.8.3-dpkg, ffprobe 2.8.3-dpkg, rtmpdump 2.4
[debug] Proxy map: {}
WARNING: Falling back on generic information extractor.
ERROR: 21: Failed to parse JSON  (caused by ValueError('No JSON object could be decoded',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.2/json/decoder.py", line 367, in raw_decode
    obj, end = self.scan_once(s, idx)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.2/dist-packages/youtube_dl/extractor/common.py", line 485, in _parse_json
    return json.loads(json_string)
  File "/usr/lib/python3.2/json/__init__.py", line 309, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.2/json/decoder.py", line 351, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.2/json/decoder.py", line 369, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Traceback (most recent call last):
  File "/usr/lib/python3.2/json/decoder.py", line 367, in raw_decode
    obj, end = self.scan_once(s, idx)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.2/dist-packages/youtube_dl/extractor/common.py", line 485, in _parse_json
    return json.loads(json_string)
  File "/usr/lib/python3.2/json/__init__.py", line 309, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.2/json/decoder.py", line 351, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.2/json/decoder.py", line 369, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.2/dist-packages/youtube_dl/YoutubeDL.py", line 665, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.2/dist-packages/youtube_dl/extractor/common.py", line 291, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python3.2/dist-packages/youtube_dl/extractor/rutv.py", line 135, in _real_extract
    video_id, 'Downloading JSON')
  File "/usr/local/lib/python3.2/dist-packages/youtube_dl/extractor/common.py", line 479, in _download_json
    json_string, video_id, transform_source=transform_source, fatal=fatal)
  File "/usr/local/lib/python3.2/dist-packages/youtube_dl/extractor/common.py", line 489, in _parse_json
    raise ExtractorError(errmsg, cause=ve)
youtube_dl.utils.ExtractorError: 21: Failed to parse JSON  (caused by ValueError('No JSON object could be decoded',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by dstftw** [comment]
This issue is already fixed and will be available in the next version.
