### ISSUE TITLE
8tracks download bug

### ISSUE THREAD

**Issue by monodeep12** [rg3/youtube-dl#8034]
**Command** : `youtube-dl -f bestaudio http://8tracks.com/200records/sebastian-habben-s-inner-city-mix -v`

**Version** : `youtube-dl is up-to-date (2015.12.23)`

**Output** : `[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-f', u'bestaudio', u'http://8tracks.com/200records/sebastian-habben-s-inner-city-mix', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.12.23
[debug] Python version 2.7.10 - Linux-3.13.0-73-generic-x86_64-with-debian-jessie-sid
[debug] exe versions: avconv 9.18-6, avprobe 9.18-6
[debug] Proxy map: {}
[8tracks] sebastian-habben-s-inner-city-mix: Downloading webpage
[8tracks] sebastian-habben-s-inner-city-mix: Downloading song information 1/8
Traceback (most recent call last):
  File "/home/monodeep/anaconda/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/monodeep/anaconda/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 410, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 400, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1677, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 665, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 291, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/eighttracks.py", line 148, in _real_extract
TypeError: unsupported operand type(s) for +: 'NoneType' and 'unicode'`

**Comment by davidjameshowell** [comment]
Just as a heads up, the JSON for the URL above below. This appears to be an issue in which we are grabbing a performer value for something that isn't set (null).
```
{
   "set":{
      "at_beginning":true,
      "at_end":false,
      "at_last_track":false,
      "skip_allowed":true,
      "track":{
         "buy_link":"http://redirect.viglink.com/?key=f4be5dc2078785c5846df105343edee0&out=https%3A%2F%2Fsearch.itunes.apple.com%2FWebObjects%2FMZSearch.woa%2Fwa%2Fsearch%3Fterm%3D%5BArtist%2520missing%5D%2520Efdemin%2520-%2520Parallaxis%2520%28Traumprinz%2520Over%25202%2520The%2520End%2520Version%29",
         "buy_icon":"http://8tracks.com/assets/buy/itunes.png",
         "buy_text":"iTunes",
         "track_file_stream_url":"http://cft.8tracks.com/tf/099/000/880/c4YS3b.48k.v3.m4a",
         "stream_source":"upload_v3",
         "user_id":1816553,
         "full_length":true,
         "faved_by_current_user":false,
         "id":56743297,
         "name":"Efdemin - Parallaxis (Traumprinz Over 2 The End Version)",
         "performer":null,
         "url":"http://8tracks.com/tracks/56743297",
         "year":null,
         "uid":56743297,
         "report_delay_s":30,
         "release_name":"Efdemin - Parallaxis (Traumprinz Over 2 The End Version)",
         "is_soundcloud":false
      }
   },
   "status":"200 OK",
   "errors":null,
   "notices":"",
   "logged_in":false,
   "api_version":3
}
```
