### ISSUE TITLE
Cannot find title of playlist

### ISSUE THREAD

**Issue by timjstewart** [rg3/youtube-dl#8036]
I installed youtube-dl via Homebrew.  Rather than a lack of title being a fatal error, the software could fallback to "untitled" or tell the user to supply a title via a --title argument.  Thanks!

youtube-dl --verbose https://www.youtube.com/playlist\?list\=PL8Ky8lYL8-Oh7awp0sqa82o7Ggt4AGhyf
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/playlist?list=PL8Ky8lYL8-Oh7awp0sqa82o7Ggt4AGhyf']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.09.28
[debug] Git HEAD: e043ac9
[debug] Python version 3.6.0a0 - Darwin-14.5.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[youtube:playlist] PL8Ky8lYL8-Oh7awp0sqa82o7Ggt4AGhyf: Downloading webpage
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/HEAD/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 660, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/Cellar/python3/HEAD/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 288, in extract
    return self._real_extract(url)
  File "/usr/local/Cellar/python3/HEAD/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1613, in _real_extract
    return self._extract_playlist(playlist_id)
  File "/usr/local/Cellar/python3/HEAD/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1588, in _extract_playlist
    page, 'title')
  File "/usr/local/Cellar/python3/HEAD/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 591, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/Cellar/python3/HEAD/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 582, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.

**Comment by timjstewart** [comment]
Thanks!  It's working great!
