### ISSUE TITLE
Add support for chetv.ru

### ISSUE THREAD

**Issue by nmr50** [rg3/youtube-dl#8039]
Hiya everyone!
Another site I am asking you, Authors, to be added to nicest all-oses program youtube-dl !
Here is the log:
C:\temp>youtube-dl.exe -v http://chetv.ru/kino/jeleznaya_hvatka/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://chetv.ru/kino/jeleznaya_hvatka/']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2015.12.23
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-77432-gc0f67e1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] jeleznaya_hvatka: Requesting header
WARNING: Falling back on generic information extractor.
[generic] jeleznaya_hvatka: Downloading webpage
[generic] jeleznaya_hvatka: Extracting information
ERROR: Unsupported URL: http://chetv.ru/kino/jeleznaya_hvatka/
Traceback (most recent call last):
  File "youtube_dl\extractor\generic.pyo", line 1287, in _real_extract
  File "youtube_dl\compat.pyo", line 248, in compat_etree_fromstring
  File "youtube_dl\compat.pyo", line 237, in _XML
  File "xml\etree\ElementTree.pyo", line 1642, in feed
  File "xml\etree\ElementTree.pyo", line 1506, in _raiseerror
ParseError: not well-formed (invalid token): line 48, column 116
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 665, in extract_info
  File "youtube_dl\extractor\common.pyo", line 291, in extract
  File "youtube_dl\extractor\generic.pyo", line 1896, in _real_extract
UnsupportedError: Unsupported URL: http://chetv.ru/kino/jeleznaya_hvatka/

Thanks in advance!
-t
ps. btw, sometimes this chetv.ru is redirecting its player to videomore.ru.. I'll open another issue with this site.

**Comment by dstftw** [comment]
Videomore based sites will be supported in the next version. However this video delivered via hds is DRM protected. Non DRM protected videos work fine (e.g. http://chetv.ru/show/dobroe_delo/).

**Comment by nmr50** [comment]
Looks like they're NOT. The log:
C:\temp>youtube-dl -v --list-formats http://chetv.ru/show/dobroe_delo/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'--list-formats', u'http://chetv.ru/show/dob
roe_delo/']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2015.12.29
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-77432-gc0f67e1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] dobroe_delo: Requesting header
WARNING: Falling back on generic information extractor.
[generic] dobroe_delo: Downloading webpage
[generic] dobroe_delo: Extracting information
ERROR: Unsupported URL: http://chetv.ru/show/dobroe_delo/
Traceback (most recent call last):
  File "youtube_dl\extractor\generic.pyo", line 1287, in _real_extract
  File "youtube_dl\compat.pyo", line 248, in compat_etree_fromstring
  File "youtube_dl\compat.pyo", line 237, in _XML
  File "xml\etree\ElementTree.pyo", line 1642, in feed
  File "xml\etree\ElementTree.pyo", line 1506, in _raiseerror
ParseError: not well-formed (invalid token): line 49, column 116
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 665, in extract_info
  File "youtube_dl\extractor\common.pyo", line 291, in extract
  File "youtube_dl\extractor\generic.pyo", line 1896, in _real_extract
UnsupportedError: Unsupported URL: http://chetv.ru/show/dobroe_delo/

Even if I try to get exact video - it won't work. The log:
C:\temp>youtube-dl -v --list-formats http://chetv.ru/show/dobroe_delo/1_sezon/1_vyipusk
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'--list-formats', u'http://chetv.ru/show/dobroe_delo/1_sezon/1_vyipusk']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2015.12.29
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-77432-gc0f67e1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 1_vyipusk: Requesting header
[redirect] Following redirect to http://chetv.ru/show/dobroe_delo/1_sezon/1_vyipusk/
[generic] 1_vyipusk: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 1_vyipusk: Downloading webpage
[generic] 1_vyipusk: Extracting information
ERROR: Unsupported URL: http://chetv.ru/show/dobroe_delo/1_sezon/1_vyipusk/
Traceback (most recent call last):
  File "youtube_dl\extractor\generic.pyo", line 1287, in _real_extract
  File "youtube_dl\compat.pyo", line 248, in compat_etree_fromstring
  File "youtube_dl\compat.pyo", line 237, in _XML
  File "xml\etree\ElementTree.pyo", line 1642, in feed
  File "xml\etree\ElementTree.pyo", line 1506, in _raiseerror
ParseError: not well-formed (invalid token): line 49, column 116
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 665, in extract_info
  File "youtube_dl\extractor\common.pyo", line 291, in extract
  File "youtube_dl\extractor\generic.pyo", line 1896, in _real_extract
UnsupportedError: Unsupported URL: http://chetv.ru/show/dobroe_delo/1_sezon/1_vyipusk/

**Comment by dstftw** [comment]
I've already told you it's **not yet released**.

**Comment by nmr50** [comment]
You've been talking about VIDEOMORE, not chetv, righto ?:) OK, be waiting for major version update and THEN re-check all the pages, then report back:)

**Comment by dstftw** [comment]
>Videomore based sites will be supported in the next version.
>in the **next version**
