### ISSUE TITLE
Add support for videomore.ru

### ISSUE THREAD

**Issue by nmr50** [rg3/youtube-dl#8040]
Hello again!
Another site is to be added - it will be PRETTY nice :)
Here is the log:
C:\temp>youtube-dl.exe -v http://videomore.ru/elki_3
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://videomore.ru/elki_3']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2015.12.23
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-77432-gc0f67e1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] elki_3: Requesting header
WARNING: Falling back on generic information extractor.
[generic] elki_3: Downloading webpage
[generic] elki_3: Extracting information
ERROR: Unsupported URL: http://videomore.ru/elki_3
Traceback (most recent call last):
  File "youtube_dl\extractor\generic.pyo", line 1287, in _real_extract
  File "youtube_dl\compat.pyo", line 248, in compat_etree_fromstring
  File "youtube_dl\compat.pyo", line 237, in _XML
  File "xml\etree\ElementTree.pyo", line 1642, in feed
  File "xml\etree\ElementTree.pyo", line 1506, in _raiseerror
ParseError: not well-formed (invalid token): line 27, column 71
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 665, in extract_info
  File "youtube_dl\extractor\common.pyo", line 291, in extract
  File "youtube_dl\extractor\generic.pyo", line 1896, in _real_extract
UnsupportedError: Unsupported URL: http://videomore.ru/elki_3

Thanks!
-t

**Comment by nmr50** [comment]
Sorry, it seems newest update won't work. The log:
C:\temp>youtube-dl.exe -v http://videomore.ru/elki_3
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://videomore.ru/elki_3']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2015.12.29
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-77432-gc0f67e1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] elki_3: Requesting header
WARNING: Falling back on generic information extractor.
[generic] elki_3: Downloading webpage
[generic] elki_3: Extracting information
ERROR: Unsupported URL: http://videomore.ru/elki_3
Traceback (most recent call last):
  File "youtube_dl\extractor\generic.pyo", line 1287, in _real_extract
  File "youtube_dl\compat.pyo", line 248, in compat_etree_fromstring
  File "youtube_dl\compat.pyo", line 237, in _XML
  File "xml\etree\ElementTree.pyo", line 1642, in feed
  File "xml\etree\ElementTree.pyo", line 1506, in _raiseerror
ParseError: not well-formed (invalid token): line 27, column 71
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 665, in extract_info
  File "youtube_dl\extractor\common.pyo", line 291, in extract
  File "youtube_dl\extractor\generic.pyo", line 1896, in _real_extract
UnsupportedError: Unsupported URL: http://videomore.ru/elki_3

**Comment by dstftw** [comment]
It's not yet released.

**Comment by nmr50** [comment]
Ah, sorry !:)

**Comment by alex-s-m** [comment]
D:\downloads>youtube-dl.exe -v http://videomore.ru/elki_3
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://videomore.ru/elki_3']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.08.19
[debug] Python version 3.4.4 - Windows-10-10.0.14905
[debug] exe versions: none
[debug] Proxy map: {}
[videomore:video] elki_3: Downloading webpage
[videomore] 364623: Downloading video XML
[videomore] 364623: Downloading f4m manifest
[videomore] 364623: Downloading video JSON
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpppfzkhrf\build\youtube_dl\extractor\common.py", line 394, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpppfzkhrf\build\youtube_dl\YoutubeDL.py", line 1996, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default

**Comment by nmr50** [comment]
Confirmed, videomore download still not in use:
C:\temp>youtube-dl.exe -F -v http://videomore.ru/elki_3
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-F', '-v', 'http://videomore.ru/elki_3']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.08.19
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-81391-g2a3720b, ffprobe N-81391-g2a3720b, rtmpdump 2.4
[debug] Proxy map: {}
[videomore:video] elki_3: Downloading webpage
[videomore] 364623: Downloading video XML
[videomore] 364623: Downloading f4m manifest
[videomore] 364623: Downloading video JSON
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by HTTPError()); ple
ase report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; ty
pe  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include it
s complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpppfzkhrf\build\youtube_dl\
extractor\common.py", line 394, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpppfzkhrf\build\youtube_dl\
YoutubeDL.py", line 1996, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
