### ISSUE TITLE
youku.com downloading fails with 403 error

### ISSUE THREAD

**Issue by rupertbaxter2** [rg3/youtube-dl#8068]
Yesterday youku.com downloading was working fine, but today it has stopped working. Below is a sample debug log.  The same 403 error occurs with any video.  I have tried on multiple computers with different IP's attached to different networks.
```
$ youtube-dl -v http://v.youku.com/v_show/id_XMTI5NjA0MzQzMg==.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://v.youku.com/v_show/id_XMTI5NjA0MzQzMg==.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.12.29
[debug] Python version 2.7.3 - CYGWIN_NT-10.0-WOW6-1.7.27-0.271-5-3-i686-32bit
[debug] exe versions: ffmpeg N-71262-g511585c, rtmpdump 2.3
[debug] Proxy map: {}
[youku] XMTI5NjA0MzQzMg: Downloading JSON metadata
[download] Downloading playlist: Tom Cruise Destroy 碟中谍5 毁车镜头(BMW M3道具车)
[youku] playlist Tom Cruise Destroy 碟中谍5 毁车镜头(BMW M3道具车): Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[debug] Invoking downloader on u'http://k.youku.com/player/getFlvPath/sid/54515286915431225abb1_00/st/flv/fileid/030001010055B825D0C1E2044C53959310DECA-8A58-F260-C747-F8C23C953A36?ep=dyaRG0yPXsgJ5Cbbiz8bZSmzJiUOXP4J9h%2BFgNJjALshTZq3mzulx%2B6xO%2F1CEv1qdyEPFeLyqtCTHzNlYfgyrGAQqUyuOfqT%2BfTk5dtbt5IDFRAzcbzUslSaRjHy&ypp=0&ctype=12&myp=0&K=06fcca506542a356282b1110&ev=1&token=4513&hd=1&oip=1626624129'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1609, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1551, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 342, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 58, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1886, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 406, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 519, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 444, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 527, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden
```

**Comment by yan12125** [comment]
I've tried to implement the algorithm mentioned in http://www.cnblogs.com/zhxilin/p/4993074.html#3338262. It seems works but I need to wait for the response from the original author for merging into youtube-dl.

**Comment by tommyjiang** [comment]
Thanks for your contribution @yan12125. Hope it could be merged as soon as possible.

**Comment by yan12125** [comment]
Pushed to master (034caf70b24da1d1de12b00e9ac5620fb7664220). Youku.com will work in the next version again.

**Comment by rupertbaxter2** [comment]
Thanks @yan12125 !
