### ISSUE TITLE
Unable to capture TED videos with 2016.01.01

### ISSUE THREAD

**Issue by stonemirror** [rg3/youtube-dl#8103]
Here's the output:

    $ youtube-dl -v http://www.ted.com/talks/barry_schwartz_on_the_paradox_of_choice
    [debug] System config: []
    [debug] User config: []
    [debug] Command-line args: [u'-v', u'http://www.ted.com/talk /barry_schwartz_on_the_paradox_of_choice']
    [debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
    [debug] youtube-dl version 2016.01.01
    [debug] Python version 2.7.11 - Darwin-15.2.0-x86_64-i386-64bit
    Traceback (most recent call last):
      File "/Users/mcfate/anaconda/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
      File "/Users/mcfate/anaconda/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
      File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
      File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 410, in main
        
      File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 377, in _real_main
        
      File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 345, in __init__
      File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1925, in print_debug_header
      File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 51, in get_versions
      File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 35, in __init__
      File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 92, in _determine_executables
      File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 92, in <genexpr>
      File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1543, in get_exe_version
      File "/Users/mcfate/anaconda/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
      File "/Users/mcfate/anaconda/lib/python2.7/subprocess.py", line 1334, in _execute_child
    child_exception = pickle.loads(data)
      File "/Users/mcfate/anaconda/lib/python2.7/pickle.py", line 1388, in loads
    return Unpickler(file).load()
      File "/Users/mcfate/anaconda/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
      File "/Users/mcfate/anaconda/lib/python2.7/pickle.py", line 886, in load_eof
    raise EOFError
    EOFError

**Comment by georGEO1989** [comment]
What are you running? I was able to download it.

**Comment by stonemirror** [comment]
It's on OS X 10.11.2... Hm.

**Comment by georGEO1989** [comment]
I would try updating your python version to 3.5. I'm running that and I was able to download it. You should be running that by now anyway.

**Comment by jaimeMF** [comment]
It's the same error as #7567, which could be related to #6840. Could you also post the output without the `-v` option?
Could you try to install the libav package with homebrew and see if it works?

**Comment by stonemirror** [comment]
On Jan 2, 2016, at 9:31 AM, Jaime Marquínez Ferrándiz <notifications@github.com> wrote:
> 
> It's the same error as #7567 <https://github.com/rg3/youtube-dl/issues/7567>, which could be related to #6840 <https://github.com/rg3/youtube-dl/issues/6840>. Could you also post the output without the -v option?
> Could you try to install the libav package with homebrew and see if it works?
> 
> 

Okay, installed libav (11.4_2) and this is what I’m getting now. For what it’s worth, running in a Python 3 virtualenv also works (but I probably shouldn’t have to).

$ youtube-dl http://www.ted.com/talks/barry_schwartz_on_the_paradox_of_choice
[ted] barry_schwartz_on_the_paradox_of_choice: Downloading webpage
[ted] barry_schwartz_on_the_paradox_of_choice: Extracting information
[ted] barry_schwartz_on_the_paradox_of_choice: Downloading m3u8 information
[download] Destination: The paradox of choice-93.fhls-1920.mp4
avconv version 11.4, Copyright (c) 2000-2014 the Libav developers
  built on Oct 16 2015 09:05:58 with Apple LLVM version 7.0.0 (clang-700.0.72)
https://hls.ted.com/videos/BarrySchwartz_2005G/video/1500k.m3u8: Protocol not found


ERROR: avconv exited with code 1

**Comment by jaimeMF** [comment]
You have to install libav with `brew install libav --with-gnutls` to enable support for https urls, or if you have ffmpeg you can add `--prefer-ffmpeg` to your [configuration file](https://github.com/rg3/youtube-dl/blob/4059eabd58dd5e68aa1229c0ba0ffce0262ef7d8/README.md#configuration).

> Okay, installed libav (11.4_2) and this is what I’m getting now. For what it’s worth, running in a Python 3 virtualenv also works (but I probably shouldn’t have to). 

To be honest I don't know what can be wrong, we didn't manage to find the cause in #6840.

**Comment by stonemirror** [comment]
Okay, ```brew uninstall libav``` and then ```brew install libav --with-gnutls``` seems to have put things right. Very odd, this only began happening recently; odd that it works right with Python 3 without the fooling around.
