### ISSUE TITLE
Import cache failed. [CRITICAL]

### ISSUE THREAD

**Issue by JeroenMathon** [rg3/youtube-dl#8111]
I cant download anything anymore. all i get is this error

Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl", line 9, in <module>
    load_entry_point('youtube-dl==2016.1.1', 'console_scripts', 'youtube-dl')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl-2016.1.1-py2.7.egg/youtube_dl/__init__.py", line 44, in <module>
    from .YoutubeDL import YoutubeDL
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl-2016.1.1-py2.7.egg/youtube_dl/YoutubeDL.py", line 84, in <module>
    from .cache import Cache
ImportError: No module named cache

**Comment by vxbinaca** [comment]
1. Run ```youtube-dl --verbose``` then your URL you're trying to rip, currently this bug report is useless. Edit your issue with the result.

2. Is this really critical? I bet it's not. I bet if you run ```--rm-cache-dir``` that would fix it, or  ```--no-cache-dir``` to simply ignore caching.

**Comment by yan12125** [comment]
Could you provide more details?
1. Does ```/usr/local/lib/python2.7/dist-packages/youtube_dl-2016.1.1-py2.7.egg/youtube_dl/cache.py``` exist? If not, you need to reinstall youtube-dl.
2. How did you install youtube-dl?
3. Operating system, Python and pip/setuptools versions

**Comment by JeroenMathon** [comment]
It is fixed.the problem was that git did not copy the whole repository
