### ISSUE TITLE
vivelohoy.com (gannet), some videos starting to fail

### ISSUE THREAD

**Issue by rhinchley** [rg3/youtube-dl#8124]
Example output, --compiled today

./youtube-dl -g http://www.vivelohoy.com/video/8528012/crece-la-ola-de-inmigrantes
WARNING: Falling back on generic information extractor.
ERROR: Empty playlist; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Failing specimens:

youtube-dl -g http://www.vivelohoy.com/video/8528012/crece-la-ola-de-inmigrantes
youtube-dl -g http://www.vivelohoy.com/video/8523823/mas-cierres-de-centros-de-detencion-de-inmigrantes
youtube-dl -g http://www.vivelohoy.com/video/8522448/consecuencias-tras-una-multa-por-dui
youtube-dl -g http://www.vivelohoy.com/video/8513520/manejar-bajo-la-influencia-del-alcohol-y-ser-indocumentado

**Comment by rhinchley** [comment]
[ron] ~/scrapecity/youtube-dl$ ./youtube-dl -g --verbose http://www.vivelohoy.com/video/8528012/crece-la-ola-de-inmigrantes
[debug] System config: [u'--prefer-free-formats']
[debug] User config: []
[debug] Command-line args: [u'-g', u'--verbose', u'http://www.vivelohoy.com/video/8528012/crece-la-ola-de-inmigrantes']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.01.01
[debug] Python version 2.7.9 - Linux-2.6.32-573.3.1.el6.x86_64-x86_64-with-centos-6.7-Final
[debug] exe versions: ffmpeg N-71747-g7c24ca1, ffprobe N-71747-g7c24ca1
[debug] Proxy map: {}
WARNING: Falling back on generic information extractor.
ERROR: Empty playlist; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 665, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 292, in extract
    return self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/brightcove.py", line 245, in _real_extract
    return self._get_playlist_info(player_key[0])
  File "./youtube-dl/youtube_dl/extractor/brightcove.py", line 283, in _get_playlist_info
    raise ExtractorError('Empty playlist')
ExtractorError: Empty playlist; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
