### ISSUE TITLE
download not possible => "<urlopen error unknown url type: rtmpt>"

### ISSUE THREAD

**Issue by ArnaudFeld** [rg3/youtube-dl#8126]
When i try to download http://www.zdf.de/ZDFmediathek/beitrag/video/2618996/1.-Schoener-Schein\#/beitrag/video/2618996/1.-Schoener-Schein i get following error:

*youtube-dl --verbose http://www.zdf.de/ZDFmediathek/beitrag/video/2618996/1.-Schoener-Schein\#/beitrag/video/2618996/1.-Schoener-Schein
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-wci', u'-o', u'%(title)s.%(ext)s', u'--recode-video', u'mp4', u'--verbose', u'http://www.zdf.de/ZDFmediathek/beitrag/video/2618996/1.-Schoener-Schein#/beitrag/video/2618996/1.-Schoener-Schein']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.01.01
[debug] Python version 2.7.10 - Darwin-15.2.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.8.4, ffprobe 2.8.4, rtmpdump 2.4
[debug] Proxy map: {}
[ZDF] 2618996: Downloading video info
[ZDF] 2618996: Downloading SMIL file
[ZDF] 2618996: Downloading f4m manifest
[ZDF] 2618996: Downloading m3u8 information
[debug] Invoking downloader on u'rtmpt://cp125301.edgefcs.net'
ERROR: unable to download video data: <urlopen error unknown url type: rtmpt>
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1609, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1551, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 342, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 58, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1886, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 454, in _open
    'unknown_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1265, in unknown_open
    raise URLError('unknown url type: %s' % type)
URLError: <urlopen error unknown url type: rtmpt>*

*youtube-dl --version
2016.01.01*

Any Ideas?

**Comment by jaimeMF** [comment]
It's fixed in the git repo (see 6b461026616b0e3ede9a302c74fc437541e19343 and https://github.com/rg3/youtube-dl/pull/8121#issuecomment-168426918), you can use it or wait for the next release.

Thanks for the report.

**Comment by ArnaudFeld** [comment]
I see that on another Machine (also OS X 10.11) it works.

could this be possible?

**Comment by ArnaudFeld** [comment]
On the machine which has the Problem i can say that it works with the 6b46102 and #8121 :)
