### ISSUE TITLE
unable use youtube-dl in windows

### ISSUE THREAD

**Issue by madhavnikam** [rg3/youtube-dl#8132]
following message display after youtube-dl run in windows OS.

C:\youtube-dl>youtube-dl
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "youtube_dl\__init__.pyo", line 410, in main
  File "youtube_dl\__init__.pyo", line 377, in _real_main
  File "youtube_dl\YoutubeDL.pyo", line 342, in __init__
  File "youtube_dl\YoutubeDL.pyo", line 1982, in _setup_opener
  File "youtube_dl\utils.pyo", line 503, in make_HTTPS_handler
  File "ssl.pyo", line 440, in create_default_context
  File "ssl.pyo", line 391, in load_default_certs
  File "ssl.pyo", line 383, in _load_windows_store_certs
ValueError: Empty certificate data

**Comment by oittaa** [comment]
What Windows version are you using?

**Comment by yan12125** [comment]
As a record, the same error occurs with official Python2 Windows binaries on wine in Arch Linux.
```
$ WINEDEBUG=fixme-all PYTHONPATH=/usr/i686-w64-mingw32/lib/python27 wine /usr/i686-w64-mingw32/bin/python2.exe youtube_dl/__main__.py -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v']
Traceback (most recent call last):
  File "youtube_dl/__main__.py", line 19, in <module>
    youtube_dl.main()
  File "Z:\home\yen\Executables\Multimedia\youtube-dl\youtube_dl\__init__.py", line 410, in main
    _real_main(argv)
  File "Z:\home\yen\Executables\Multimedia\youtube-dl\youtube_dl\__init__.py", line 377, in _real_main
    with YoutubeDL(ydl_opts) as ydl:
  File "Z:\home\yen\Executables\Multimedia\youtube-dl\youtube_dl\YoutubeDL.py", line 342, in __init__
    self._setup_opener()
  File "Z:\home\yen\Executables\Multimedia\youtube-dl\youtube_dl\YoutubeDL.py", line 1986, in _setup_opener
    https_handler = make_HTTPS_handler(self.params, debuglevel=debuglevel)
  File "Z:\home\yen\Executables\Multimedia\youtube-dl\youtube_dl\utils.py", line 518, in make_HTTPS_handler
    context = ssl.create_default_context(ssl.Purpose.SERVER_AUTH)
  File "Z:\usr\i686-w64-mingw32\lib\python27\ssl.py", line 440, in create_default_context
    context.load_default_certs(purpose)
  File "Z:\usr\i686-w64-mingw32\lib\python27\ssl.py", line 391, in load_default_certs
    self._load_windows_store_certs(storename, purpose)
  File "Z:\usr\i686-w64-mingw32\lib\python27\ssl.py", line 383, in _load_windows_store_certs
    self.load_verify_locations(cadata=certs)
ValueError: Empty certificate data
```
This is because ```ssl.enum_certificates("CA")``` returns an empty list on wine.

**Comment by yan12125** [comment]
Related: http://bugs.python.org/issue26313

**Comment by yan12125** [comment]
This bug is fixed upstream. I leave this ticket open until Python 2.7.12 is released (about May 2016 according to [PEP0373](https://www.python.org/dev/peps/pep-0373/#maintenance-releases)).

**Comment by yan12125** [comment]
Python 2.7.12 is released, closing. Note that the official youtube-dl.exe is now built against Python 3.4.4 and does not include the upstream fix. You'll need to install either Python 2.7.12 of Python 3.5 in this case. See #10014 for more further discussion.
