### ISSUE TITLE
"Could not find JS function 'gr'" for this particular youtube video.

### ISSUE THREAD

**Issue by shelvacu** [rg3/youtube-dl#8144]
Trying to download https://www.youtube.com/watch?v=ShI_fv38qYQ
Full --verbose output:

	$ youtube-dl --verbose "https://www.youtube.com/watch?v=ShI_fv38qYQ"
	[debug] System config: []
	[debug] User config: []
	[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=ShI_fv38qYQ']
	WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
	[debug] Encodings: locale ANSI_X3.4-1968, fs ascii, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
	[debug] youtube-dl version 2015.11.24
	[debug] Python version 3.5.1 - Linux-4.1.6-1-ARCH-x86_64-with-arch
	[debug] exe versions: ffmpeg 2.8.4, ffprobe 2.8.4, rtmpdump 2.4
	[debug] Proxy map: {}
	[youtube] ShI_fv38qYQ: Downloading webpage
	[youtube] ShI_fv38qYQ: Downloading video info webpage
	[youtube] ShI_fv38qYQ: Extracting video information
	[youtube] {43} signature length 43.43, html5 player en_US-vflnrstgx
	[youtube] ShI_fv38qYQ: Downloading player https://s.ytimg.com/yts/jsbin/player-en_US-vflnrstgx/base.js
	ERROR: Signature extraction failed: Traceback (most recent call last):
	File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 856, in _decrypt_signature
    video_id, player_url, s
	File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 771, in _extract_signature_function
    res = self._parse_sig_js(code)
	File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 834, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
	File "/usr/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 241, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
	youtube_dl.utils.ExtractorError: Could not find JS function 'gr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
	(caused by ExtractorError("Could not find JS function 'gr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
	Traceback (most recent call last):
	File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 856, in _decrypt_signature
    video_id, player_url, s
	File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 771, in _extract_signature_function
    res = self._parse_sig_js(code)
	File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 834, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
	File "/usr/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 241, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
	youtube_dl.utils.ExtractorError: Could not find JS function 'gr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
	Traceback (most recent call last):
	File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 856, in _decrypt_signature
    video_id, player_url, s
	File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 771, in _extract_signature_function
    res = self._parse_sig_js(code)
	File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 834, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
	File "/usr/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 241, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
	youtube_dl.utils.ExtractorError: Could not find JS function 'gr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

	During handling of the above exception, another exception occurred:

	Traceback (most recent call last):
	File "/usr/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 663, in extract_info
    ie_result = ie.extract(url)
	File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
	File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1410, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
	File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 866, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
	youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
	File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 856, in _decrypt_signature
    video_id, player_url, s
	File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 771, in _extract_signature_function
    res = self._parse_sig_js(code)
	File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 834, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
	File "/usr/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 241, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
	youtube_dl.utils.ExtractorError: Could not find JS function 'gr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
	(caused by ExtractorError("Could not find JS function 'gr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Other youtube videos download just fine. If there's any other info I need to provide please tell me, I'll try my best.

**Comment by yan12125** [comment]
You're using an out-dated version (2015.11.24). Please update to the latest version (2016.01.01) via [update instructions](https://github.com/rg3/youtube-dl/#how-do-i-update-youtube-dl).

**Comment by shelvacu** [comment]
Dang, arch linux is usually pretty good at keeping packages up to date. That worked, thanks for the help, sorry for the bother.
