### ISSUE TITLE
iPlayer Failure

### ISSUE THREAD

**Issue by owlboy** [rg3/youtube-dl#8147]
```
owlboy$ youtube-dl -f best --verbose http://www.bbc.co.uk/programmes/p028bfkf/player

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-f', u'best', u'--verbose', u'http://www.bbc.co.uk/programmes/p028bfkf/player']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.01.01
[debug] Python version 2.7.10 - Darwin-15.2.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.8.1, ffprobe 2.8.1, rtmpdump 2.4
[debug] Proxy map: {}
[bbc.co.uk] p028bfkf: Downloading video page
[bbc.co.uk] p028bfkj: Downloading media selection XML
[bbc.co.uk] p028bfkj: Downloading media selection XML
ERROR: Unable to extract OpenGraph title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 665, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 291, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/bbc.py", line 472, in _real_extract
    title = self._og_search_title(webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 680, in _og_search_title
    return self._og_search_property('title', html, **kargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 668, in _og_search_property
    escaped = self._search_regex(self._og_regexes(prop), html, name, flags=re.DOTALL, **kargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 586, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract OpenGraph title; please report this issue on https://yt-dl.org/bug . 

Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

The video is: http://www.bbc.co.uk/programmes/p028bfkf/player
Originally found on this page: http://www.bbc.co.uk/blogs/adamcurtis/entries/a2094c9d-9864-348e-a241-7aa93adf0c09

I am in the US, on Mac OS X and can play back the video fine inside of by browser. It does not appear a region lock issue would be the cause of the failure.

**Comment by robinpaulson** [comment]
This is the same as the error I got in #8189. I am in New Zealand, there is no indication I am region blocked either.
