### ISSUE TITLE
Vevo

### ISSUE THREAD

**Issue by EdwardMRoche** [rg3/youtube-dl#8159]
Script started on Wed 06 Jan 2016 10:57:25 PM EST
#[01;32mdarwin@darwin-MacBookPro#[01;34m ~ $#[00m youtube-dl https://youtu.be/R-0SMryFWpc###########j-uT4Zkh7oc###########R-0SMryFWpc
#[C#[C#[C#[C#[C#[C#[C#[C#[C#[C#[C#[C#[C#[C#[C#[C#[C#[C#[C#[C#[C#[C#[C#[C#[C#[C#[C#[C#[C#[K#youtube-dl https://youtu.be/R-0SMryFWpc###########j-uT4Zkh7oc###########qJpzRW-8z7E##########APh5Pe1Iwk###########Z-BwyzbF7E4###########UwEED6sOXrI###########Z-BwyzbF7E4###########qAPh5Pe1Iwk##########JpzRW-8z7E###########j-uT4Zkh7oc###########R-0SMryFWpc
#[C#[C#[C#[C#[C#[C#[C#[C#[C#[C#[C#[C#[C#[C#[C#[C#[C#[C#[C#[C#[C#[C#[C#[C#[C#[C#[C#[C#[C#[Kyoutube-dl --verbose http://vevo.ly/cd##[KePUP1
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://vevo.ly/cePUP1']
[debug] Encodings: locale 'UTF-8', fs 'UTF-8', out 'UTF-8', pref: 'UTF-8'
[debug] youtube-dl version 2014.02.17
[debug] Python version 2.7.6 - Linux-3.13.0-37-generic-x86_64-with-LinuxMint-17.1-rebecca
[debug] Proxy map: {}
[generic] cePUP1: Requesting header
[redirect] Following redirect to http://www.vevo.com/watch/GBUV71501362?syndicationid=bb8a16ab-1279-4f17-969b-1dba5eb60eda&shortlink=cePUP1&country=US
[Vevo] GBUV71501362: Downloading JSON metadata
Traceback (most recent call last):
  File "/usr/bin/youtube-dl", line 6, in <module>
    youtube_dl.main()
  File "/usr/lib/python2.7/dist-packages/youtube_dl/__init__.py", line 804, in main
    _real_main(argv)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/__init__.py", line 794, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 982, in download
    self.extract_info(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 510, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 546, in process_ie_result
    extra_info=extra_info)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 493, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 158, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/vevo.py", line 107, in _real_extract
    formats = self._formats_from_json(video_info)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/vevo.py", line 42, in _formats_from_json
    for version in video_info['videoVersions']:
TypeError: 'NoneType' object has no attribute '__getitem__'
#[01;32mdarwin@darwin-MacBookPro#[01;34m ~ $#[00m exit

Script done on Wed 06 Jan 2016 10:58:42 PM EST

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.

**Comment by EdwardMRoche** [comment]
Ok. Many thanks. 
Happy New Year!
