### ISSUE TITLE
ERROR: Unable to extract title

### ISSUE THREAD

**Issue by ulissesnextvision** [rg3/youtube-dl#8161]
root@ulisses:/home/ulisses# youtube-dl https://www.youtube.com/playlist?list=PLfkVgm8720kzm6fmTekjtKyFcppyD4Ubd --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'https://www.youtube.com/playlist?list=PLfkVgm8720kzm6fmTekjtKyFcppyD4Ubd', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.06.04.1
[debug] Python version 2.7.10 - Linux-4.2.0-22-generic-x86_64-with-Ubuntu-15.10-wily
[debug] exe versions: rtmpdump 2.4
[debug] Proxy map: {}
[youtube:playlist] PLfkVgm8720kzm6fmTekjtKyFcppyD4Ubd: Downloading webpage
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 650, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 273, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 1365, in _real_extract
    return self._extract_playlist(playlist_id)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 1339, in _extract_playlist
    page, 'title')
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 564, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 555, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by yan12125** [comment]
You are using an out-dated version (2015.06.04.1). Please update to the latest version (2016.01.01) via [update instructions](https://github.com/rg3/youtube-dl#how-do-i-update-youtube-dl).
