### ISSUE TITLE
Could not find JS function 'hr';

### ISSUE THREAD

**Issue by Nephos** [rg3/youtube-dl#8162]
Hi !
There an issue for
- https://www.youtube.com/watch?v=v7uOXHMhaO8
- https://www.youtube.com/watch?v=xfj6r5tfEf4

```text
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-x', '--audio-format', 'vorbis', 'https://www.youtube.com/watch?v=v7uOXHMhaO8', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.24
[debug] Python version 3.5.1 - Linux-4.3.3-2-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 2.8.4, ffprobe 2.8.4, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] v7uOXHMhaO8: Downloading webpage
[youtube] v7uOXHMhaO8: Downloading video info webpage
[youtube] v7uOXHMhaO8: Extracting video information
[youtube] {22} signature length 40.43, html5 player en_US-vfl2TFPXm
[youtube] v7uOXHMhaO8: Downloading player https://s.ytimg.com/yts/jsbin/player-en_US-vfl2TFPXm/base.js
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 856, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 771, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 834, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 241, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'hr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Could not find JS function 'hr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 856, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 771, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 834, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 241, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'hr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 856, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 771, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 834, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 241, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'hr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 663, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1410, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 866, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 856, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 771, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 834, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 241, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)

```

**Comment by flyingrub** [comment]
same here : 
```
 youtube2mp3 https://www.youtube.com/playlist?list=PLKfM8QA4eHXDQnYA9HApJNLjhZ7JgFpfe --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-t', '-x', '--audio-format', 'mp3', '--audio-quality', '0', 'https://www.youtube.com/playlist?list=PLKfM8QA4eHXDQnYA9HApJNLjhZ7JgFpfe', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.24
[debug] Python version 3.5.1 - Linux-4.3.3-2-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 2.8.4, ffprobe 2.8.4, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:playlist] PLKfM8QA4eHXDQnYA9HApJNLjhZ7JgFpfe: Downloading webpage
[download] Downloading playlist: Feels like: Violent
[youtube:playlist] playlist Feels like: Violent: Downloading 77 videos
[download] Downloading video 1 of 77
[youtube] JSpKPsGoyHc: Downloading webpage
[youtube] JSpKPsGoyHc: Downloading video info webpage
[youtube] JSpKPsGoyHc: Extracting video information
[youtube] {43} signature length 40.43, html5 player en_US-vfl2TFPXm
[youtube] JSpKPsGoyHc: Downloading player https://s.ytimg.com/yts/jsbin/player-en_US-vfl2TFPXm/base.js
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 856, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 771, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 834, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 241, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'hr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Could not find JS function 'hr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 856, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 771, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 834, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 241, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'hr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 856, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 771, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 834, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 241, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'hr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 663, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1410, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 866, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 856, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 771, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 834, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 241, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'hr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Could not find JS function 'hr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

**Comment by phihag** [comment]
Both of you are using outdated versions of youtube-dl. See [our FAQ](https://yt-dl.org/update) on how to update. If you can reproduce the problem with the [current version](https://yt-dl.org/latest/version) (2016.01.01 as of writing), please post the output you get with that version and we will reopen this issue. Thanks!

**Comment by Nephos** [comment]
Ok it's cool.
I bet the community package of Archlinux was up to date enough, and I didn't checkout the version.
My bad Thanks ! :heart_eyes:

**Comment by flyingrub** [comment]
yup the community package is out of date...
