### ISSUE TITLE
MTV changed. No longer downloads.

### ISSUE THREAD

**Issue by StevenDTX** [rg3/youtube-dl#8169]
Thanks.
```
E:\>youtube-dl -v "http://www.mtv.com/full-episodes/0ghr35/teen-mom-why-can-t-we-just-get-along-season-5-ep-511"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.mtv.com/full-episodes/0ghr35/teen-mom-why-can-t-we-just-get-along-season-5-ep-511']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.01.01
[debug] Python version 2.7.10 - Windows-8-6.2.9200
[debug] exe versions: ffmpeg N-72383-g7206b94, ffprobe N-72383-g7206b94, rtmpdump 2.4
[debug] Proxy map: {}
[generic] teen-mom-why-can-t-we-just-get-along-season-5-ep-511: Requesting header
WARNING: Falling back on generic information extractor.
[generic] teen-mom-why-can-t-we-just-get-along-season-5-ep-511: Downloading webpage
[generic] teen-mom-why-can-t-we-just-get-along-season-5-ep-511: Extracting information
ERROR: Unsupported URL: http://www.mtv.com/full-episodes/0ghr35/teen-mom-why-can-t-we-just-get-along-season-5-ep-511
Traceback (most recent call last):
  File "youtube_dl\extractor\generic.pyo", line 1289, in _real_extract
  File "youtube_dl\compat.pyo", line 248, in compat_etree_fromstring
  File "youtube_dl\compat.pyo", line 237, in _XML
  File "xml\etree\ElementTree.pyo", line 1642, in feed
  File "xml\etree\ElementTree.pyo", line 1506, in _raiseerror
ParseError: not well-formed (invalid token): line 36, column 178
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 665, in extract_info
  File "youtube_dl\extractor\common.pyo", line 291, in extract
  File "youtube_dl\extractor\generic.pyo", line 1908, in _real_extract
UnsupportedError: Unsupported URL: http://www.mtv.com/full-episodes/0ghr35/teen-mom-why-can-t-we-just-get-along-season-5-ep-511

```

**Comment by StevenDTX** [comment]
Thanks @remitamine!  It works great!
