### ISSUE TITLE
Vimeo not downloading HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by bilalghouri** [rg3/youtube-dl#8187]
# youtube-dl https://vimeo.com/7809605
[vimeo] 7809605: Downloading webpage
[vimeo] 7809605: Extracting information
[vimeo] 7809605: Downloading webpage
[vimeo] 7809605: Downloading JSON metadata
[vimeo] 7809605: Downloading m3u8 information
ERROR: unable to download video data: HTTP Error 403: Forbidden

**Comment by dstftw** [comment]
Post the **full** output of youtube-dl when run [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by bilalghouri** [comment]
Sorry about that:

# youtube-dl https://vimeo.com/7809605 --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'https://vimeo.com/7809605', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.01.01
[debug] Python version 2.7.9 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.2
[debug] exe versions: none
[debug] Proxy map: {}
[vimeo] 7809605: Downloading webpage
[vimeo] 7809605: Extracting information
[vimeo] 7809605: Downloading webpage
[vimeo] 7809605: Downloading JSON metadata
[vimeo] 7809605: Downloading m3u8 information
[debug] Invoking downloader on u'https://vimeo.com/7809605/download?t=1452284032&v=12289168&s=42e829b677e542fd465bd7a4f220f1011bf957b21e721971490599c580490a8a'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1609, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1551, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 342, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 58, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1886, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden

**Comment by dstftw** [comment]
Will be fixed in the next version. For now you can download specifying different format code, e.g. `-f http-720p`.
