### ISSUE TITLE
[canalc2.tv] http://archives-canalc2.u-strasbg.fr/video.asp?idVideo=11390&voir=oui

### ISSUE THREAD

**Issue by Rudloff** [rg3/youtube-dl#8191]
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://archives-canalc2.u-strasbg.fr/video.asp?idVideo=11390&voir=oui', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.01.09
[debug] Python version 2.7.6 - Linux-3.13.0-74-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.18-6, avprobe 9.18-6, rtmpdump 2.4
[debug] Proxy map: {}
[generic] video: Requesting header
WARNING: Falling back on generic information extractor.
[generic] video: Downloading webpage
[generic] video: Extracting information
ERROR: Unsupported URL: http://archives-canalc2.u-strasbg.fr/video.asp?idVideo=11390&voir=oui
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 1289, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/compat.py", line 248, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=etree.TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/compat.py", line 237, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: undefined entity &nbsp;: line 5, column 42
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 665, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 312, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 1908, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://archives-canalc2.u-strasbg.fr/video.asp?idVideo=11390&voir=oui
```

**Comment by Rudloff** [comment]
It seems the video can also be accessed from here (but it does not work either): http://www.canalc2.tv/video/11390
