### ISSUE TITLE
Windows 7 x64 65001 error

### ISSUE THREAD

**Issue by nickleefly** [rg3/youtube-dl#820]
when i run `youtube-dl --help`
the error is

```
Traceback (most recent call last):
  File "__main__.py", line 18, in <module>
  File "youtube_dl\__init__.pyo", line 590, in main
  File "youtube_dl\__init__.pyo", line 337, in _real_main
  File "youtube_dl\__init__.pyo", line 328, in parseOpts
  File "optparse.pyo", line 1399, in parse_args
  File "optparse.pyo", line 1439, in _process_args
  File "optparse.pyo", line 1514, in _process_long_opt
  File "optparse.pyo", line 788, in process
  File "optparse.pyo", line 810, in take_action
  File "optparse.pyo", line 1669, in print_help
LookupError: unknown encoding: cp65001
```

```
D:\youtube-dl>youtube-dl --verbose
Traceback (most recent call last):
  File "__main__.py", line 18, in <module>
  File "youtube_dl\__init__.pyo", line 590, in main
  File "youtube_dl\__init__.pyo", line 337, in _real_main
  File "youtube_dl\__init__.pyo", line 330, in parseOpts
LookupError: unknown encoding: cp65001
```

```
D:\youtube-dl>youtube-dl --version
2013.05.01

D:\youtube-dl>python --version
Python 2.7.3
```

**Comment by Ghostwalker1** [comment]
This is 3 years later yet when i search for: 
"youtubedl urlopen error [Errno 11004] getaddrinfo failed"
This page gets #2 status in duckduckgo. This issue was resolved when i removed my (massive) host file and DNS servers temporarily then youtubedl resumed it's profound ability to dl. Hope this helps.
