### ISSUE TITLE
PBS giving "Unsupported url" error

### ISSUE THREAD

**Issue by dshimer** [rg3/youtube-dl#8220]
There have been recent changes to the site layout but the links look similar to what I have seen before however the most recent run yields.

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.pbs.org/video/2365639766']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.12.09
[debug] Python version 2.7.10 - Linux-4.2.0-23-generic-x86_64-with-Ubuntu-15.10-wily
[debug] exe versions: avconv 2.7.4-0ubuntu0.15.10.1, avprobe 2.7.4-0ubuntu0.15.10.1, ffmpeg 2.7.4-0ubuntu0.15.10.1, ffprobe 2.7.4-0ubuntu0.15.10.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 2365639766: Requesting header
[redirect] Following redirect to http://www.pbs.org/video/2365639766/
[generic] 2365639766: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 2365639766: Downloading webpage
[generic] 2365639766: Extracting information
ERROR: Unsupported URL: http://www.pbs.org/video/2365639766/
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 1286, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/lib/python2.7/dist-packages/youtube_dl/compat.py", line 248, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=etree.TreeBuilder(element_factory=_element_factory)))
  File "/usr/lib/python2.7/dist-packages/youtube_dl/compat.py", line 237, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: syntax error: line 1, column 0
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 663, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 1890, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.pbs.org/video/2365639766/

**Comment by jaimeMF** [comment]
You are using an outdated version, you have to [upgrade youtube-dl](https://github.com/rg3/youtube-dl/blob/40f796288afe634055c4600993b353da58e29a45/README.md#how-do-i-update-youtube-dl).
