### ISSUE TITLE
Xtube do not Work 

### ISSUE THREAD

**Issue by TotalDay** [rg3/youtube-dl#8224]
Xtube do not Work

**Comment by TotalDay** [comment]
[XTubeUser] xxxxxxxx: Retrieving profile page
ERROR: Unable to extract video count; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 665, in extract_info
  File "youtube_dl\extractor\common.pyo", line 312, in extract
  File "youtube_dl\extractor\xtube.pyo", line 110, in _real_extract
  File "youtube_dl\extractor\common.pyo", line 607, in _search_regex
RegexNotFoundError: Unable to extract video count; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
