### ISSUE TITLE
Can't download a channel with spaces in user name

### ISSUE THREAD

**Issue by kurogetsusai** [rg3/youtube-dl#8248]
Can't download a channel with spaces in user name. I tried to escape them or inserting a %20 instead, but nothing works. Is there a workaround to do it?

```
$ youtube-dl --verbose -ciw 'ytuser:Raon Lee'
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'-ciw', u'ytuser:Raon\xa0Lee']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.06.04.1
[debug] Python version 2.7.10 - Linux-4.2.0-23-generic-x86_64-with-Ubuntu-15.10-wily
[debug] exe versions: ffmpeg 2.7.4-0ubuntu0.15.10.1, ffprobe 2.7.4-0ubuntu0.15.10.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:user] Raon: Downloading channel page
WARNING: Unable to download webpage: HTTP Error 404: Not Found
ERROR: expected string or buffer
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 650, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 273, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 1412, in _real_extract
    channel_page, 'channel id', default=None)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 537, in _search_regex
    mobj = re.search(p, string, flags)
  File "/usr/lib/python2.7/re.py", line 146, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or buffer
```
My version:
```
$ youtube-dl --version
2015.06.04.1
```
A package from Ubuntu 15.10's repo.

**Comment by dstftw** [comment]
Use full channel URL..

**Comment by kurogetsusai** [comment]
How? It doesn't work either:
```
$ youtube-dl --verbose -ciw 'https://www.youtube.com/channel/UCQn1FqrR2OCjSe6Nl4GlVHw'
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'-ciw', u'https://www.youtube.com/channel/UCQn1FqrR2OCjSe6Nl4GlVHw']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.06.04.1
[debug] Python version 2.7.10 - Linux-4.2.0-23-generic-x86_64-with-Ubuntu-15.10-wily
[debug] exe versions: ffmpeg 2.7.4-0ubuntu0.15.10.1, ffprobe 2.7.4-0ubuntu0.15.10.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:channel] UCQn1FqrR2OCjSe6Nl4GlVHw: Downloading channel page
[youtube:playlist] UUQn1FqrR2OCjSe6Nl4GlVHw: Downloading webpage
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 650, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 273, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 1365, in _real_extract
    return self._extract_playlist(playlist_id)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 1339, in _extract_playlist
    page, 'title')
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 564, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 555, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.

**Comment by kurogetsusai** [comment]
Okay, it works now, thanks! I should have tried it before opening an issue, sorry.
