### ISSUE TITLE
youtube-dl is not working with Ubuntu 15.10

### ISSUE THREAD

**Issue by DerSennin** [rg3/youtube-dl#8274]
Hello,

i installt youtube-dl on my VM with Ubuntu 15.10. Unfortunately it is not working. I get this error:

XXX@XXX-VirtualBox:~$ youtube-dl https://www.viewster.com/serie/1289-19113-001/episode-1/
[Viewster] 1289-19113-001: Downloading webpage
[Viewster] 1289-19113-001: Downloading entry JSON
[Viewster] 1289-19113-001: Downloading application/f4m+xml JSON
[Viewster] 1289-19113-001: Downloading f4m manifest
[Viewster] 1289-19113-001: Downloading application/x-mpegURL JSON
[Viewster] 1289-19113-001: Downloading m3u8 information
[Viewster] 1289-19113-001: Downloading video/mp4 JSON
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 410, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 400, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1677, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 665, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 312, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/viewster.py", line 161, in _real_extract
AttributeError: 'NoneType' object has no attribute 'get'

On my HTPC wiht Ubuntu 14.10 i can download the Video. Can some one help me?

**Comment by siddht1** [comment]
Dude its working , just the website is unsupported, use   wget to download the html  . Usage "wget -O [folder_location/file_name.file_type] [url] " , then use  cat and grep as  " cat [folder_location/file_name.file_type] | grep video ",   download the link using wget, terminal returned

**Comment by siddht1** [comment]
I rechecked it , its working , I think you didn`t made youtube-dl   to be executed  .  use chmod +x for this once or use   "sudo wget https://yt-dl.org/downloads/2016.01.15/youtube-dl -O /usr/local/bin/youtube-dl "  followed by  "sudo chmod a+rx /usr/local/bin/youtube-dl"
