### ISSUE TITLE
ExtractorError: Cannot identify player

### ISSUE THREAD

**Issue by akaJedi** [rg3/youtube-dl#8276]
brew -v
Homebrew 0.9.5 (git revision c8deb; last commit 2016-01-19)

youtube-dl https://youtu.be/JmNr3sPyuzs

[youtube] JmNr3sPyuzs: Downloading webpage
[youtube] JmNr3sPyuzs: Extracting video information
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 653, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 545, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
ExtractorError: Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vflGR-A-c/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vflGR-A-c/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by akaJedi** [comment]
Ups
That was my fail

dvt@zozo.local:/Volumes/slave/Video$ youtube-dl -U
Updating to version 2016.01.15 ...
ERROR: no write permissions on /usr/local/bin/youtube-dl

dvt@zozo.local:/Volumes/slave/Video$ ls -al /usr/local/bin/youtube-dl
lrwxr-xr-x  1 dvt  admin  46 May 16  2015 /usr/local/bin/youtube-dl -> ../Cellar/youtube-dl/2015.05.04/bin/youtube-dl

dvt@zozo.local:/Volumes/slave/Video$ sudo youtube-dl -U

Now it works
