### ISSUE TITLE
Site Support Request: PopTV.com

### ISSUE THREAD

**Issue by DragonNeos** [rg3/youtube-dl#8280]
Can you add support for this website?

Example URL: http://poptv.com/post/136762107828/impact-wrestling-premiere-full-episode

```
youtube-dl --verbose http://poptv.com/post/136762107828/impact-wrestling-premiere-full-episode
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://poptv.com/post/136762107828/i
mpact-wrestling-premiere-full-episode']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.01.15
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-77953-gcc83177, ffprobe N-77953-gcc83177, rtmpdum
p 2.4
[debug] Proxy map: {}
[generic] impact-wrestling-premiere-full-episode: Requesting header
WARNING: Falling back on generic information extractor.
[generic] impact-wrestling-premiere-full-episode: Downloading webpage
[generic] impact-wrestling-premiere-full-episode: Extracting information
[brightcove:legacy] AQ~~,AAAB-0j8O8k~,4Zm4raQfNIpvkHb496QWbqJbPs3IHFnC: Download
ing playlist information
ERROR: Empty playlist; please report this issue on https://yt-dl.org/bug . Make
sure you are using the latest version; type  youtube-dl -U  to update. Be sure t
o call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 665, in extract_info
  File "youtube_dl\extractor\common.pyo", line 312, in extract
  File "youtube_dl\extractor\brightcove.pyo", line 245, in _real_extract
  File "youtube_dl\extractor\brightcove.pyo", line 283, in _get_playlist_info
ExtractorError: Empty playlist; please report this issue on https://yt-dl.org/bu
g . Make sure you are using the latest version; type  youtube-dl -U  to update.
Be sure to call youtube-dl with the --verbose flag and include its complete outp
ut.
```

**Comment by davidjameshowell** [comment]
For reference this is using the Brightcove Smart Player. There is a reference to an iFrame page in the div class "video-embed" under "responsive video" which for this specific example goes to 

'''
https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Flink.brightcove.com%2Fservices%2Fplayer%2Fbcpid4687748255001%3Fbctid%3D4687929679001%26secureConnections%3Dtrue%26secureHTMLConnections%3Dtrue%26linkSrc%3Dtwitter%26autoStart%3Dfalse%26height%3D100%2525%26width%3D100%2525&url=http%3A%2F%2Flink.brightcove.com%2Fservices%2Fplayer%2Fbcpid4687748255001%3Fbckey%3DAQ~~%2CAAAB-0j8O8k~%2C4Zm4raQfNIpvkHb496QWbqJbPs3IHFnC%26bctid%3D4687929679001&image=http%3A%2F%2Fbrightcove.vo.llnwd.net%2Fe1%2Fpd%2F2178772909001%2F2178772909001_4688043604001_Impact101-MATCH-797x449.jpg%3FpubId%3D2178772909001&key=a70a993cabda412b8ce79a8f66040de1&type=text%2Fhtml&schema=brightcove
'''
URL decoded to:
'''
https://link.brightcove.com/services/player/bcpid4687748255001?bctid=4687929679001&secureConnections=true&secureHTMLConnections=true&linkSrc=twitter&autoStart=false&height=100%25&width=100%25&url=http://link.brightcove.com/services/player/bcpid4687748255001?bckey=AQ~~,AAAB-0j8O8k~,4Zm4raQfNIpvkHb496QWbqJbPs3IHFnC&bctid=4687929679001&image=http://brightcove.vo.llnwd.net/e1/pd/2178772909001/2178772909001_4688043604001_Impact101-MATCH-797x449.jpg?pubId=2178772909001&key=a70a993cabda412b8ce79a8f66040de1&type=text/html&schema=brightcove
'''

Should be able to hook into the Brightcove extractor for this one.

**Comment by TRox1972** [comment]
@DragonNeos Provided URL doesn't seem to work anymore. Could you provide a new one?

**Comment by DragonNeos** [comment]
@TRox1972 Can you try the following URL? I grabbed the link by clicking on the option Share Video while I was viewing videos on the website (PopTV.com).

URL: http://link.brightcove.com/services/player/bcpid4005240248001?bckey=AQ~~,AAAB-0j8O8k~,4Zm4raQfNIp4mZBi3X42t56GGoTy23H1&bctid=5033724191001

**Comment by remitamine** [comment]
the example url can be downloaded without a problem:
```
python __main__.py 'http://link.brightcove.com/services/player/bcpid4005240248001?bckey=AQ%7E%7E,AAAB-0j8O8k%7E,4Zm4raQfNIp4mZBi3X42t56GGoTy23H1&bctid=5033724191001'
[brightcove:legacy] 5033724191001: Downloading webpage
[brightcove:legacy] 5033724191001: Extracting information
[download] Destination: Impact Wrestling 7_12_16 LIVE-5033724191001.mp4
[#684baf 1.0MiB/2.2GiB(0%) CN:4 DL:127KiB ETA:5h1m58s]
```

**Comment by DragonNeos** [comment]
@remitamine What command did you use in order to download the video? I can't download the video using this command:
```
youtube-dl --verbose http://link.brightcove.com/services/player/bcpid4005240248001?bckey=AQ%7E%7E,AAAB-0j8O8k%7E,4Zm4raQfNIp4mZBi3X42t56GGoTy23H1&bctid=5033724191001
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://link.brightcove.com/services/pl
ayer/bcpid4005240248001?bckey=AQ%7E%7E,AAAB-0j8O8k%7E,4Zm4raQfNIp4mZBi3X42t56GGo
Ty23H1']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.08.13
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-81338-g6612d04, ffprobe N-81338-g6612d04, rtmpdum
p 2.4
[debug] Proxy map: {}
[brightcove:legacy] AQ~~,AAAB-0j8O8k~,4Zm4raQfNIp4mZBi3X42t56GGoTy23H1: Download
ing playlist information
ERROR: Empty playlist; please report this issue on https://yt-dl.org/bug . Make
sure you are using the latest version; type  youtube-dl -U  to update. Be sure t
o call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpz_7f3hc1\bu
ild\youtube_dl\YoutubeDL.py", line 691, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpz_7f3hc1\bu
ild\youtube_dl\extractor\common.py", line 347, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpz_7f3hc1\bu
ild\youtube_dl\extractor\brightcove.py", line 277, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpz_7f3hc1\bu
ild\youtube_dl\extractor\brightcove.py", line 320, in _get_playlist_info
youtube_dl.utils.ExtractorError: Empty playlist; please report this issue on htt
ps://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-d
l -U  to update. Be sure to call youtube-dl with the --verbose flag and include
its complete output.

'bctid' is not recognized as an internal or external command,
operable program or batch file.
```
What is a ```__main__.py``` file? What kind of code or commands are contained in this file in order to allow users to be able to download videos from places such as Brightcove?

**Comment by yan12125** [comment]
@DragonNeos You need to put the URL in double quotes. For example:
```
youtube-dl --verbose "http://link.brightcove.com/services/player/bcpid4005240248001?bckey=AQ%7E%7E,AAAB-0j8O8k%7E,4Zm4raQfNIp4mZBi3X42t56GGoTy23H1&bctid=5033724191001"
```

**Comment by yan12125** [comment]
By the way, as @TRox1972 said, the original URL is gone. Any new examples?

**Comment by joeynotjoe** [comment]
This URL has a full episode that doesn't require any subscriptions. https://poptv.com/letsgetphysical/fullepisodes/2605
