### ISSUE TITLE
youtube-dl, Unable to download videos from dailymotion 

### ISSUE THREAD

**Issue by SMed79** [rg3/youtube-dl#8286]
Hi!
I really use youtube-dl a lot. But my experience with dailymotion videos all time failure and won't download (no problem with youtube.com).

output:

```
youtube-dl http://www.dailymotion.com/video/x3hnk8x
[dailymotion] x3hnk8x: Downloading webpage
[dailymotion] x3hnk8x: Downloading m3u8 information
[download] Destination: Arch Linux vs Manjaro-x3hnk8x.mp4
ffmpeg version 2.8.5 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 5.3.0 (GCC)
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-avisynth --enable-avresample --enable-fontconfig --enable-gnutls --enable-gpl --enable-ladspa --enable-libass --enable-libbluray --enable-libdcadec --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-shared --enable-version3 --enable-x11grab
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
[http @ 0x9cc0200] HTTP error 404 Not Found
http://proxy-41.dailymotion.com/sec(3c3a9a7585d829771b3a2842bd1f63f3)/video/923/150/211051329_mp4_h264_aac_fhd_1.m3u8#cell=core: Server returned 404 Not Found

ERROR: ffmpeg exited with code 1
```

Thanks in advance for your help.
Med

**Comment by slang800** [comment]
I can confirm this - dailymotion support broke for me too

**Comment by ckuu** [comment]
Working for me :
```
youtube-dl -v http://www.dailymotion.com/video/x3hnk8x
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.dailymotion.com/video/x3hnk8x']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.01.15
[debug] Python version 2.7.9 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.2
[debug] exe versions: ffmpeg 2.8.5, ffprobe 2.8.5
[debug] Proxy map: {}
[dailymotion] x3hnk8x: Downloading webpage
[dailymotion] x3hnk8x: Downloading m3u8 information
[debug] Invoking downloader on u'https://www.dailymotion.com/cdn/H264-1920x1080/video/x3hnk8x.mp4?auth=1453554534-2562-shehrf46-11766723a180ebf3fee9ae7af198b016'
[download] Destination: Arch Linux vs Manjaro-x3hnk8x.mp4
[download] 100% of 67.42MiB in 01:29
```

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.

**Comment by SMed79** [comment]
@dstftw You are right, fixed after [updating](http://www.manjaro.fr/forum/viewtopic.php?f=2003&t=6635).
Thank you.

**Comment by khiftikhar** [comment]
I also experience problem downloading from dailymotion,

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 474, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 464, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2018, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/dailymotion.py", line 235, in _real_extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/dailymotion.py", line 50, in _call_api
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/dailymotion.py", line 31, in _get_dailymotion_cookies
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 2831, in _get_cookies
  File "/usr/lib/python2.7/Cookie.py", line 583, in __init__
    if input: self.load(input)
  File "/usr/lib/python2.7/Cookie.py", line 643, in load
    for k, v in rawdata.items():
AttributeError: 'unicode' object has no attribute 'items'

```
