### ISSUE TITLE
Can't DL from yahoo.com

### ISSUE THREAD

**Issue by igv-on-dev** [rg3/youtube-dl#8289]
youtube-dl --verbose https://www.yahoo.com/movies/v/true-story-trailer-173000497.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://www.yahoo.com/movies/v/true-story-trailer-173000497.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.01.15
[debug] Python version 2.7.10 - Darwin-14.5.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.8, ffprobe 2.8
[debug] Proxy map: {}
[Yahoo] true-story-trailer: Downloading webpage
ERROR: Unable to extract content ID; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 665, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 312, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/yahoo.py", line 226, in _real_extract
    CONTENT_ID_REGEXES, webpage, 'content ID')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 607, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract content ID; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by igv-on-dev** [comment]
I made PR which resolve this - #8290
