### ISSUE TITLE
Broken: laola1.tv (site layout changed)

### ISSUE THREAD

**Issue by egolus** [rg3/youtube-dl#8301]
as the site changed its layout, youtube-dl can't find the stream any more.

example link: `http://www.laola1.tv/watch/video/460627`
the livestreams don't work either.

~~~
 .\youtube-dl.exe -v http://www.laola1.tv/watch/video/460627
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.laola1.tv/watch/video/460627']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.01.15
[debug] Python version 2.7.10 - Windows-8-6.2.9200
[debug] exe versions: ffmpeg 2.8.4, ffprobe 2.8.4
[debug] Proxy map: {}
[generic] 460627: Requesting header
[redirect] Following redirect to http://www.laola1.tv/de-de/video/460627
[generic] 460627: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 460627: Downloading webpage
[generic] 460627: Extracting information
ERROR: Unsupported URL: http://www.laola1.tv/de-de/video/460627
Traceback (most recent call last):
  File "youtube_dl\extractor\generic.pyo", line 1289, in _real_extract
  File "youtube_dl\compat.pyo", line 248, in compat_etree_fromstring
  File "youtube_dl\compat.pyo", line 237, in _XML
  File "xml\etree\ElementTree.pyo", line 1642, in feed
  File "xml\etree\ElementTree.pyo", line 1506, in _raiseerror
ParseError: not well-formed (invalid token): line 57, column 32
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 665, in extract_info
  File "youtube_dl\extractor\common.pyo", line 312, in extract
  File "youtube_dl\extractor\generic.pyo", line 1908, in _real_extract
UnsupportedError: Unsupported URL: http://www.laola1.tv/de-de/video/460627
~~~

(run on windows 10)

**Comment by blackwinter** [comment]
This is fixed in 2016.02.22.

**Comment by egolus** [comment]
it works for videos now, but livestreams still error out

example livestream right now: http://www.laola1.tv/de-de/livestream/2016-02-23-cska-moscow-hc-slovan-bratislava-german
~~~
.\youtube-dl.exe -v "http://www.laola1.tv/de-de/livestream/2016-02-23-cska-moscow-hc-slovan-bratislava-german"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.laola1.tv/de-de/livestream/2016-02-23-cska-moscow-hc-slovan-bratislava-german']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.02.22
[debug] Python version 2.7.10 - Windows-8-6.2.9200
[debug] exe versions: ffmpeg 2.8.6, ffprobe 2.8.6
[debug] Proxy map: {}
[Laola1Tv] 2016-02-23-cska-moscow-hc-slovan-bratislava-german: Downloading webpage
[Laola1Tv] 2016-02-23-cska-moscow-hc-slovan-bratislava-german: Downloading iframe
[Laola1Tv] 2016-02-23-cska-moscow-hc-slovan-bratislava-german: Downloading XML
[Laola1Tv] 2016-02-23-cska-moscow-hc-slovan-bratislava-german: Downloading JSON metadata
[Laola1Tv] 2016-02-23-cska-moscow-hc-slovan-bratislava-german: Downloading token
ERROR: Token error: error
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 666, in extract_info
  File "youtube_dl\extractor\common.pyo", line 316, in extract
  File "youtube_dl\extractor\laola1tv.pyo", line 107, in _real_extract
ExtractorError: Token error: error
~~~

**Comment by egolus** [comment]
@blackwinter have you looked at livestreams? Are they very different?

**Comment by blackwinter** [comment]
No, I haven't looked at those specifically, sorry.

**Comment by egolus** [comment]
Thanks for fixing the videos. I will open a new issue for the livestreams
