### ISSUE TITLE
Continue to next video on error in playlist

### ISSUE THREAD

**Issue by camsteffen** [rg3/youtube-dl#8305]
When I tried to download a playlist, the first video failed because it has been removed from YouTube but the rest of the videos in the playlist should download.

```
$ youtube-dl https://www.youtube.com/playlist?list=PLg4aSwO3XsLv8-qsyQeQcFDhL_k04wMPj -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'https://www.youtube.com/playlist?list=PLg4aSwO3XsLv8-qsyQeQcFDhL_k04wMPj', u'-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.01.23
[debug] Python version 2.7.10 - Windows-8-6.2.9200
[debug] exe versions: ffmpeg N-76860-g72eaf72, ffprobe N-76860-g72eaf72
[debug] Proxy map: {}
[youtube:playlist] PLg4aSwO3XsLv8-qsyQeQcFDhL_k04wMPj: Downloading webpage
[download] Downloading playlist: Punch Brothers WHO'S FEELING YOUNG NOW ? New Full Album
[youtube:playlist] playlist Punch Brothers WHO'S FEELING YOUNG NOW ? New Full Album: Downloading 12 videos
[download] Downloading video 1 of 12
[youtube] cgph-dr8W_A: Downloading webpage
[youtube] cgph-dr8W_A: Downloading video info webpage
ERROR: cgph-dr8W_A: YouTube said: "Punch Brothers - Movement A..."
This video is no longer available due to a copyright claim by Warner Music Group.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 666, in extract_info
  File "youtube_dl\extractor\common.pyo", line 313, in extract
  File "youtube_dl\extractor\youtube.pyo", line 1226, in _real_extract
ExtractorError: cgph-dr8W_A: YouTube said: "Punch Brothers - Movement A..."
This video is no longer available due to a copyright claim by Warner Music Group.
```

**Comment by AndroKev** [comment]
use the " -i, --ignore-errors              Continue on download errors, for example to skip unavailable videos in a playlist" option

youtube-dl https://www.youtube.com/playlist?list=PLg4aSwO3XsLv8-qsyQeQcFDhL_k04wMPj -v -i

**Comment by dstftw** [comment]
As mentioned by @AndroKev use `-i` to skip errors.

**Comment by camsteffen** [comment]
Could we add a hint to the output when an error occurs and there are queued videos?
`Hint: use the -i flag to continue on download errors`
