### ISSUE TITLE
Getting Error 5 on running via .sh

### ISSUE THREAD

**Issue by saifsmailbox98** [rg3/youtube-dl#8308]
```
ERROR: unable to open for writing: [Errno 5] Input/output error: '/media/SAIF16GB/shares/yt-dl/BIMethods Fall 2014/05-BIMethods  20140902  Class05 w Bonus Footage.f135.mp4.part'
```

**Comment by dstftw** [comment]
Post the **full** output of youtube-dl when run [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by saifsmailbox98** [comment]
This playlist is getting stuck at fifth video. Here is the log.
```
[youtube:playlist] PLsDYCyUR8mCQSmiO6NomVFQvGc05UImZL: Downloading webpage
[download] Downloading playlist: BIMethods Fall 2014
[youtube:playlist] playlist BIMethods Fall 2014: Downloading 27 videos
[download] Downloading video 1 of 27
[youtube] SPr9riX-hOw: Downloading webpage
[youtube] SPr9riX-hOw: Downloading video info webpage
[youtube] SPr9riX-hOw: Extracting video information
[youtube] SPr9riX-hOw: Downloading DASH manifest
[youtube] SPr9riX-hOw: Downloading DASH manifest
[download] /media/SAIF16GB/shares/yt-dl/BIMethods Fall 2014/01-BIMethods  20140819  Class01.mp4 has already been downloaded and merged
[download] Downloading video 2 of 27
[youtube] t87MwDtBNR8: Downloading webpage
[youtube] t87MwDtBNR8: Downloading video info webpage
[youtube] t87MwDtBNR8: Extracting video information
[youtube] t87MwDtBNR8: Downloading DASH manifest
[youtube] t87MwDtBNR8: Downloading DASH manifest
[download] /media/SAIF16GB/shares/yt-dl/BIMethods Fall 2014/02-BIMethods  20140821  Class02.mp4 has already been downloaded and merged
[download] Downloading video 3 of 27
[youtube] nCXLx4xkGVY: Downloading webpage
[youtube] nCXLx4xkGVY: Downloading video info webpage
[youtube] nCXLx4xkGVY: Extracting video information
[youtube] nCXLx4xkGVY: Downloading DASH manifest
[youtube] nCXLx4xkGVY: Downloading DASH manifest
[download] /media/SAIF16GB/shares/yt-dl/BIMethods Fall 2014/03-BIMethods  20140826  Class03 w Bonus Footage.mp4 has already been downloaded and merged
[download] Downloading video 4 of 27
[youtube] ReXiB6FhEdk: Downloading webpage
[youtube] ReXiB6FhEdk: Downloading video info webpage
[youtube] ReXiB6FhEdk: Extracting video information
[youtube] ReXiB6FhEdk: Downloading DASH manifest
[youtube] ReXiB6FhEdk: Downloading DASH manifest
[download] /media/SAIF16GB/shares/yt-dl/BIMethods Fall 2014/04-BIMethods  20140828  Class04.mp4 has already been downloaded and merged
[download] Downloading video 5 of 27
[youtube] YIDlww0yj_g: Downloading webpage
[youtube] YIDlww0yj_g: Downloading video info webpage
[youtube] YIDlww0yj_g: Extracting video information
[youtube] YIDlww0yj_g: Downloading DASH manifest
[youtube] YIDlww0yj_g: Downloading DASH manifest
[debug] Invoking downloader on u'https://r1---sn-npupj5cax-jj0e.googlevideo.com/videoplayback?id=6080e5c30d328ff8&itag=135&source=youtube&requiressl=yes&pl=24&mm=31&mn=sn-npupj5cax-jj0e&ms=au&mv=m&ratebypass=yes&mime=video/mp4&gir=yes&clen=103182207&lmt=1412916244474454&dur=5959.533&fexp=9408209,9413122,9416126,9419549,9420452,9422596,9423042,9423662,9425006,9425387,9427140,9427168,9427670&upn=SkIH93XJBRU&signature=60EEDF0581BA6EE512FAC5F1A98200B15C6176A4.7C6FC768952C23D13AE018F0BF8E2D2D6DB76F2F&sver=3&key=dg_yt0&mt=1453621049&ip=150.107.10.191&ipbits=0&expire=1453642701&sparams=ip,ipbits,expire,id,itag,source,requiressl,pl,mm,mn,ms,mv,ratebypass,mime,gir,clen,lmt,dur'
```

OUTPUT:
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'-c', u'--no-check-certificate', u'-f', u'135+140/134+140/best+140', u'-o', u'/media/SAIF16GB/shares/yt-dl/%(playlist)s/%(playlist_index)s-%(title)s.%(ext)s', u'--batch-file=/media/SAIF16GB/shares/ytpllist.txt']
[debug] Batch file urls: [u'http://www.youtube.com/playlist?list=PLsDYCyUR8mCQSmiO6NomVFQvGc05UImZL', u'https://www.youtube.com/playlist?list=PL_5KdfXwGw4a5ia5HU8Dp-niG9LYvjokJ']
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out None, pref ANSI_X3.4-1968
[debug] youtube-dl version 2016.01.14
[debug] Python version 2.7.9 - Linux-4.1.7-v7+-armv7l-with-debian-8.0
[debug] exe versions: avconv 11.4-6, avprobe 11.4-6, rtmpdump 2.4
[debug] Proxy map: {}
ERROR: unable to open for writing: [Errno 5] Input/output error: '/media/SAIF16GB/shares/yt-dl/BIMethods Fall 2014/05-BIMethods  20140902  Class05 w Bonus Footage.f135.mp4.part'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 172, in real_download
    (stream, tmpfilename) = sanitize_open(tmpfilename, open_mode)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 310, in sanitize_open
    stream = open(encodeFilename(filename), open_mode)
IOError: [Errno 5] Input/output error: '/media/SAIF16GB/shares/yt-dl/BIMethods Fall 2014/05-BIMethods  20140902  Class05 w Bonus Footage.f135.mp4.part'
```

Files in the folder:
![capture](https://cloud.githubusercontent.com/assets/11242541/12535071/5fd88100-c29c-11e5-80a6-28bc7af0b616.PNG)

**Comment by dstftw** [comment]
Post the output of `df -h`.

**Comment by saifsmailbox98** [comment]
What is that and how should I get the output?

Sorry I am new with this.

**Comment by dstftw** [comment]
Same way you did it for youtube-dl command.

**Comment by saifsmailbox98** [comment]
should i put df -h after youtube-dl command?

**Comment by dstftw** [comment]
No, this is separate command.

**Comment by saifsmailbox98** [comment]
Okay that is so simple.
```
pi@raspberrypi ~ $ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/root       7.2G  4.7G  2.2G  69% /
devtmpfs        459M     0  459M   0% /dev
tmpfs           463M     0  463M   0% /dev/shm
tmpfs           463M  6.6M  457M   2% /run
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           463M     0  463M   0% /sys/fs/cgroup
/dev/mmcblk0p1   56M   20M   37M  36% /boot
/dev/sda1        30G  2.2G   28G   8% /media/SAIF16GB
tmpfs            93M     0   93M   0% /run/user/1000
```

**Comment by saifsmailbox98** [comment]
```/dev/sda1        30G  2.2G   28G   8% /media/SAIF16GB```
This is the device I am downloading my files on.

**Comment by saifsmailbox98** [comment]
Here is the .sh file
```
#!/bin/bash
/usr/local/bin/youtube-dl -v -c --no-check-certificate -f 135+140/134+140/best+140 -o '/media/SAIF16GB/shares/yt-dl/%(playlist)s/%(playlist_index)s-%(title)s.%(ext)s' --batch-file='/media/SAIF16GB/shares/ytpllist.txt' >> /home/pi/yt-dl/QQQQQQQ.log
```

**Comment by dstftw** [comment]
`/dev/sda1` is probably damaged. Try to check for bad blocks or at least write and read the full capacity.

**Comment by saifsmailbox98** [comment]
Yes, I think you are right. I pulled out the device and tried connecting it to my windows PC. The folder containing videos was corrupted and not accessible.

I have formatted the device. What should I do to check it?

Should I use Check Flash 1.16.2?

**Comment by dstftw** [comment]
Use any tool for checking for bad blocks.

**Comment by saifsmailbox98** [comment]
Thanks @dstftw
