### ISSUE TITLE
ERROR:   Reason: image not found

### ISSUE THREAD

**Issue by mananwason** [rg3/youtube-dl#8323]
```
youtube-dl -v https://www.youtube.com/watch?v=zHdoczkqEPA
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=zHdoczkqEPA']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.01.23
[debug] Python version 2.7.10 - Darwin-15.3.0-x86_64-i386-64bit
[debug] exe versions: avconv present, avprobe present, ffmpeg 2.8.4, ffprobe 2.8.4
[debug] Proxy map: {}
[youtube] zHdoczkqEPA: Downloading webpage
[youtube] zHdoczkqEPA: Downloading video info webpage
[youtube] zHdoczkqEPA: Extracting video information
[youtube] zHdoczkqEPA: Downloading DASH manifest
[youtube] zHdoczkqEPA: Downloading DASH manifest
[debug] Invoking downloader on u'https://r1---sn-ci5gup-qxae.googlevideo.com/videoplayback?id=cc776873392a10f0&itag=134&source=youtube&requiressl=yes&pcm2cms=yes&pl=20&mn=sn-ci5gup-qxae&mm=31&mv=m&ms=au&ratebypass=yes&mime=video/mp4&gir=yes&clen=1707670&lmt=1400950455159473&dur=45.041&sver=3&key=dg_yt0&upn=pjXxDs3R3Ws&mt=1453788994&signature=55C9E5BC131436FA5E000FE83F041FB8E700DD95.6C5BB32E77C8097EC6FFE396C63EB8CA5BA9A75C&fexp=9407029,9408509,9413139,9416126,9417577,9418203,9418403,9419451,9420016,9420452,9422596,9423290,9423662,9423980,9424823,9425448,9425540,9425749,9426674,9427167,9427708,9427760&ip=122.176.146.91&ipbits=0&expire=1453810703&sparams=ip,ipbits,expire,id,itag,source,requiressl,pcm2cms,pl,mn,mm,mv,ms,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: Funniest Video Ever 2014  LOL  ROFL  Short Video Clip-zHdoczkqEPA.f134.mp4
[download] 100% of 1.63MiB in 00:01
[debug] Invoking downloader on u'https://r1---sn-ci5gup-qxae.googlevideo.com/videoplayback?id=cc776873392a10f0&itag=141&source=youtube&requiressl=yes&pcm2cms=yes&pl=20&mn=sn-ci5gup-qxae&mm=31&mv=m&ms=au&ratebypass=yes&mime=audio/mp4&gir=yes&clen=1443519&lmt=1400950522442142&dur=45.255&sver=3&key=dg_yt0&upn=pjXxDs3R3Ws&mt=1453788994&signature=2B50682C4C1DE10A778A134D5A7C11C37F7DC7D7.4A3EDA67190620C83EB711939810F1E8ACFB518F&fexp=9407029,9408509,9413139,9416126,9417577,9418203,9418403,9419451,9420016,9420452,9422596,9423290,9423662,9423980,9424823,9425448,9425540,9425749,9426674,9427167,9427708,9427760&ip=122.176.146.91&ipbits=0&expire=1453810703&sparams=ip,ipbits,expire,id,itag,source,requiressl,pcm2cms,pl,mn,mm,mv,ms,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: Funniest Video Ever 2014  LOL  ROFL  Short Video Clip-zHdoczkqEPA.f141.m4a
[download] 100% of 1.38MiB in 00:01
[ffmpeg] Merging formats into "Funniest Video Ever 2014  LOL  ROFL  Short Video Clip-zHdoczkqEPA.mp4"
[debug] ffmpeg command line: avconv -y -i 'file:Funniest Video Ever 2014  LOL  ROFL  Short Video Clip-zHdoczkqEPA.f134.mp4' -i 'file:Funniest Video Ever 2014  LOL  ROFL  Short Video Clip-zHdoczkqEPA.f141.m4a' -c copy -map 0:v:0 -map 1:a:0 'file:Funniest Video Ever 2014  LOL  ROFL  Short Video Clip-zHdoczkqEPA.temp.mp4'
ERROR:   Reason: image not found
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1737, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 407, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 155, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
FFmpegPostProcessorError

```

I am facing this error while downloading any video. The files are not getting merged. Tried merging using ffmpeg manually and it worked. So, not a ffmpeg issue. Any help is appreciated. Thanks!

**Comment by yan12125** [comment]
From the log, avconv is used instead of ffmpeg:
```
avconv -y -i 'file:Funniest Video Ever 2014  LOL  ROFL  Short Video Clip-zHdoczkqEPA.f134.mp4' -i 'file:Funniest Video Ever 2014  LOL  ROFL  Short Video Clip-zHdoczkqEPA.f141.m4a' -c copy -map 0:v:0 -map 1:a:0 'file:Funniest Video Ever 2014  LOL  ROFL  Short Video Clip-zHdoczkqEPA.temp.mp4'
```
Could you run this command directly in the terminal and paste all the output?

> Tried merging using ffmpeg manually and it worked.

What's your command?

Generally, if both ffmpeg and avconv are installed, youtube-dl prefer avconv. I guess your avconv is broken. If this is the case, remove it or add ```--prefer-ffmpeg``` to youtube-dl.

**Comment by mananwason** [comment]
Cool @yan12125. Works now. Didn't know that youtube-dl prefers avconf. Thanks for your help. Closing This :smile:

**Comment by Pysis868** [comment]
`--prefer-avconv` did it for me.

```
> youtube-dl -v (pbpaste)
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'...']
[debug] youtube-dl version 2019.04.30
[debug] Python version 2.7.16 (CPython) - Darwin-17.7.0-x86_64-i386-64bit
[debug] exe versions: avconv 12.3, avprobe 12.3, ffmpeg present, ffprobe present
...
[ffmpeg] Merging formats into ....mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel 'repeat+info' -i 'file:....f133.mp4' -i 'file:....f251.webm' -c copy -map '0:v:0' -map '1:a:0' 'file:....temp.mkv'
ERROR:   Reason: image not found
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2054, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 512, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 235, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
FFmpegPostProcessorError:   Reason: image not found
```

So I had both. Recently heard `avconv` is a rewrite of `ffmpeg` so took it as the newer one.  Assumed it would use `avconv` but still generated an `ffmpeg` CLI string.

Found out it was having this issue:
```
dyld: Library not loaded: /usr/local/opt/fdk-aac/lib/libfdk-aac.1.dylib
  Referenced from: /usr/local/bin/ffmpeg
  Reason: image not found
fish: 'ffmpeg -y -loglevel 'repeat+inf…' terminated by signal SIGABRT (Abort)
```

I've been having an issue like this lately, but mostly I thought with my not up-to-date 10.13.6 MacOS behind by 1 minor version or so some newer programs I installed through Homebrew and such so I have been switching 1 library so far, but nothing like this library.

YT-DL is up-to-date and

Thanks!

**Comment by NightMachinary** [comment]
In my case a macOS upgrade had broken my ffmpeg:

```
$ ffmpeg                                                                                                         1
dyld: Library not loaded: /usr/local/opt/x265/lib/libx265.165.dylib
  Referenced from: /usr/local/bin/ffmpeg
  Reason: image not found
dyld: Library not loaded: /usr/local/opt/x265/lib/libx265.165.dylib
  Referenced from: /usr/local/bin/ffmpeg
  Reason: image not found
```

**Comment by biokillos** [comment]
`brew reinstall ffmpeg` did the trick for me

**Comment by jazzyjackson** [comment]
Same for Catalina 10.15.4, had to run `brew reinstall ffmpeg`

**Comment by iwittkau** [comment]
`brew reinstall ffmpeg` also fixed it for me on High Sierra 10.13.6

**Comment by ChasonDeshotel** [comment]
`brew upgrade ffmpeg` did the trick for me; no need to reinstall

**Comment by NightMachinary** [comment]
@ChasonDeshotel because that reinstalls if your current version is not the latest.

**Comment by ChasonDeshotel** [comment]
@NightMachinary right but I'd never default to reinstalling software without first trying to update it. Usually reinstall means nuking your settings and starting from scratch

But TIL `brew reinstall` "silently preserve[s] previously specified options". Gross
