### ISSUE TITLE
bbc.co.uk returned error: geolocation

### ISSUE THREAD

**Issue by lucendio** [rg3/youtube-dl#8351]
NOTE: tried form within germany

```
youtube-dl --verbose http://www.bbc.co.uk/programmes/p03fdfxm
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.bbc.co.uk/programmes/p03fdfxm']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.01.27
[debug] Python version 2.7.10 - Darwin-14.5.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.8.5, ffprobe 2.8.5, rtmpdump 2.4
[debug] Proxy map: {}
[bbc.co.uk] p03fdfxm: Downloading video page
[bbc.co.uk] p03fdfxm: Downloading playlist JSON
[bbc.co.uk] p03fdg0v: Downloading media selection XML
[bbc.co.uk] p03fdg0v: Downloading media selection XML
ERROR: bbc.co.uk returned error: geolocation
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/bbc.py", line 346, in _download_media_selector
    mediaselector_url % programme_id, programme_id)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/bbc.py", line 363, in _download_media_selector_url
    return self._process_media_selector(media_selection, programme_id)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/bbc.py", line 369, in _process_media_selector
    for media in self._extract_medias(media_selection):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/bbc.py", line 278, in _extract_medias
    raise BBCCoUkIE.MediaSelectionError(error.get('id'))
MediaSelectionError
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 666, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 313, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/bbc.py", line 492, in _real_extract
    programme_id, title, description, duration, formats, subtitles = self._download_playlist(group_id)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/bbc.py", line 396, in _download_playlist
    formats, subtitles = self._download_media_selector(programme_id)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/bbc.py", line 352, in _download_media_selector
    self._raise_extractor_error(last_exception)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/bbc.py", line 339, in _raise_extractor_error
    expected=True)
ExtractorError: bbc.co.uk returned error: geolocation
```

**Comment by yan12125** [comment]
On the webpage it says

> BBC iPlayer TV programmes are available to play in the UK only

**Comment by lucendio** [comment]
Thanks for pointing me to this information, but I am fully aware of BBC claiming this. My point is, it worked just fine on 23rd of January this year - only 5 days ago. So I just wanted to mention it, because it looks like an issue, at least from my perspective.

**Comment by yan12125** [comment]
Can you watch this video in the browser after 01/23?

**Comment by lucendio** [comment]
no, but that didnt work before either. thats why I used this tool. additionally, I never used a VPN.

**Comment by yan12125** [comment]
Codes for handling BBC videos does not change since 2016/01/16 ([history of bbc.py](https://github.com/rg3/youtube-dl/commits/master/youtube_dl/extractor/bbc.py)), so it's likely that BBC.co.uk has fixed something wrong in IP restriction these days.

**Comment by lucendio** [comment]
it seems that some of the offerings are working, some dont. I am able to download audio (radio shows), but videos seem to get blocked. But I am not sure if its caused by the tool or the bbc.

the first link is working:
```
http://www.bbc.co.uk/programmes/b06ybsr7
```

second throws the geolocation error:
```
http://www.bbc.co.uk/programmes/p03dndk1
```

**Comment by yan12125** [comment]
That's the correct behavior. For me the first link plays well in the browser and the second link gives a georestriction message.
