### ISSUE TITLE
Vimeo/Others: fails to download on "-f bestvideo+bestaudio"

### ISSUE THREAD

**Issue by vxbinaca** [rg3/youtube-dl#8355]
```
youtube-dl --verbose  --download-archive ~/.ytdlarchive --no-overwrites --call-home --continue --write-info-json --write-description --write-thumbnail --write-annotations --merge-output-format mkv --all-subs --sub-format srt --convert-subs srt --write-sub --add-metadata -f bestvideo+bestaudio https://vimeo.com/116603551
```

```
[debug] System config: []
[debug] User config: [u'--download-archive', u'~/.ytdlarchive', u'--no-overwrites', u'--call-home', u'--continue', u'--write-info-json', u'--write-description', u'--write-thumbnail', u'--write-annotations', u'--merge-output-format', u'mkv', u'--all-subs', u'--sub-format', u'srt', u'--convert-subs', u'srt', u'--write-sub', u'--add-metadata', u'-f', u'bestvideo+bestaudio']
[debug] Command-line args: [u'--verbose', u'--download-archive', u'/home/vxbinaca/.ytdlarchive', u'--no-overwrites', u'--call-home', u'--continue', u'--write-info-json', u'--write-description', u'--write-thumbnail', u'--write-annotations', u'--merge-output-format', u'mkv', u'--all-subs', u'--sub-format', u'srt', u'--convert-subs', u'srt', u'--write-sub', u'--add-metadata', u'-f', u'bestvideo+bestaudio', u'https://vimeo.com/116603551']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.01.27
[debug] Python version 2.7.10 - Linux-4.2.0-25-generic-x86_64-with-Ubuntu-15.10-wily
[debug] exe versions: ffmpeg 2.7.5-0ubuntu0.15.10.1, ffprobe 2.7.5-0ubuntu0.15.10.1, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Public IP address: 76.101.221.232
[vimeo] 116603551: Downloading webpage
[vimeo] 116603551: Extracting information
[vimeo] 116603551: Downloading webpage
[vimeo] 116603551: Downloading JSON metadata
[vimeo] 116603551: Checking Original video URL
[vimeo] 116603551: Original video URL is invalid, skipping
[vimeo] 116603551: Downloading m3u8 information
ERROR: requested format not available
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 677, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 723, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1353, in process_video_result
    expected=True)
ExtractorError: requested format not available
```

Doesn't the script be default download the best copy?

**Comment by vxbinaca** [comment]
I should add that that flag fails on pretty much every site but youtube and a handful of others.

**Comment by dstftw** [comment]
There is no `bestvideo` and `bestaudio` formats for vimeo as stated in error message. Read [format selection](https://github.com/rg3/youtube-dl#format-selection).

**Comment by phihag** [comment]
If you want the best quality, simply don't pass in any `-f`. If you must use `-f`, add a `/best` at the end.
