### ISSUE TITLE
csapanERROR: unable to download video data: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by rudolf323** [rg3/youtube-dl#8364]
>youtube-dl.exe --verbose "http://www.c-span.org/video/?187762-1/united-
nations-headquarters-renovation"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.c-span.org/video/?187762-
1/united-nations-headquarters-renovation']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.01.27
[debug] Python version 2.7.10 - Windows-2012Server-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {}
[CSpan] 187762: Downloading webpage
[CSpan] 144620: Downloading JSON metadata
[CSpan] 144620: Downloading XML
[download] Downloading playlist: United Nations Headquarters Renovation
[CSpan] playlist United Nations Headquarters Renovation: Collected 3 video ids (
downloading 3 of them)
[download] Downloading video 1 of 3
[debug] Invoking downloader on u'http://media.c-spanvideo.org/trimmed/program/01
4/144620/program.144620.MP4-M20.mp4?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoia
HR0cDovL21lZGlhLmMtc3BhbnZpZGVvLm9yZy90cmltbWVkL3Byb2dyYW0vMDE0LzE0NDYyMC9wcm9nc
mFtLjE0NDYyMC5NUDQtTTIwLm1wNCIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb
2NoVGltZSI6MTQ1NDEwNTEyNn0sIklwQWRkcmVzcyI6eyJBV1M6U291cmNlSXAiOiI1LjE5Ni42OC4yM
zkifX19XX0_&Key-Pair-Id=APKAIHKVWBEAXX562G7Q&Signature=B7bMtci2oCyAnNmLokng~ANI3
Ba76B42WZTqLkHyEznKf70CSVTYFsimuMnoyzuZ4j1kDjMj5FKvDAsHHKIwONh9-Kwmh-Rpjud02ytVA
jNlRRH3iEjSgs32bihaXmTIO1Y-ywQ6eEsa2VfnqDENOZqvz4kqtDIDepkcl4jrccI_'
[download] United Nations Headquarters Renovation part 1-144620_1.mp4 has alread
y been downloaded
[download] 100% of 1.63GiB
[download] Downloading video 2 of 3
[debug] Invoking downloader on u'http://media.c-spanvideo.org/trimmed/blank/blan
kVideo.mp4?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cDovL21lZGlhLmMtc3Bhbn
ZpZGVvLm9yZy90cmltbWVkL2JsYW5rL2JsYW5rVmlkZW8ubXA0IiwiQ29uZGl0aW9uIjp7IkRhdGVMZX
NzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNDU0MTA1MTI2fSwiSXBBZGRyZXNzIjp7IkFXUzpTb3VyY2
VJcCI6IjUuMTk2LjY4LjIzOSJ9fX1dfQ__&amp;Key-Pair-Id=APKAIHKVWBEAXX562G7Q&amp;Sign
ature=NetNSDG725dJJODk8wEAL7zIlguACFmJoQQ~0WFdrV2uejK54m9skl6rcBDNOttzCwvE00tBvh
GOQGM98mGkcfdzwVse1LuEV-bDdwRzwNVRSBlafFITrnSq7XvTwGYmEomVeYiilHLSh8kE1cnTxqzXJc
2p9IIXz-XhZTxX~J0_'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 1623, in process_info
  File "youtube_dl\YoutubeDL.pyo", line 1565, in dl
  File "youtube_dl\downloader\common.pyo", line 342, in download
  File "youtube_dl\downloader\http.pyo", line 58, in real_download
  File "youtube_dl\YoutubeDL.pyo", line 1904, in urlopen
  File "urllib2.pyo", line 437, in open
  File "urllib2.pyo", line 550, in http_response
  File "urllib2.pyo", line 475, in error
  File "urllib2.pyo", line 409, in _call_chain
  File "urllib2.pyo", line 558, in http_error_default
HTTPError: HTTP Error 403: Forbidden

**Comment by rudolf323** [comment]
delete this..
