### ISSUE TITLE
YouTube: --embed-thumbnail doesn't work with --merge-output-format 'mkv'

### ISSUE THREAD

**Issue by vxbinaca** [rg3/youtube-dl#8379]
```
youtube-dl --verbose --ignore-errors --ignore-config --retries 100 --no-overwrites --call-home --continue --write-info-json --write-description --write-thumbnail --write-annotations --all-subs --sub-format srt --convert-subs srt --write-sub --add-metadata -f bestvideo+bestaudio/best --merge-output-format 'mkv' --embed-subs --embed-thumbnail https://www.youtube.com/watch?v=rxouBYVrfUs
```

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'--ignore-errors', u'--ignore-config', u'--retries', u'100', u'--no-overwrites', u'--call-home', u'--continue', u'--write-info-json', u'--write-description', u'--write-thumbnail', u'--write-annotations', u'--all-subs', u'--sub-format', u'srt', u'--convert-subs', u'srt', u'--write-sub', u'--add-metadata', u'-f', u'bestvideo+bestaudio/best', u'--merge-output-format', u'mkv', u'--embed-subs', u'--embed-thumbnail', u'https://www.youtube.com/watch?v=rxouBYVrfUs']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.01.29
[debug] Python version 2.7.10 - Linux-4.2.0-25-generic-x86_64-with-Ubuntu-15.10-wily
[debug] exe versions: ffmpeg 2.7.5-0ubuntu0.15.10.1, ffprobe 2.7.5-0ubuntu0.15.10.1, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Public IP address: 76.101.221.232
[youtube] rxouBYVrfUs: Downloading webpage
[youtube] rxouBYVrfUs: Downloading video info webpage
[youtube] rxouBYVrfUs: Extracting video information
WARNING: video doesn't have subtitles
[youtube] rxouBYVrfUs: Searching for annotations.
[youtube] rxouBYVrfUs: Downloading DASH manifest
[youtube] rxouBYVrfUs: Downloading DASH manifest
[info] Video description is already present
[info] Video annotations are already present
[info] Video description metadata is already present
[youtube] rxouBYVrfUs: Thumbnail is already present
[download] Ichimatsu-sama Shoot-rxouBYVrfUs.mkv has already been downloaded and merged
[ffmpeg] Adding metadata to 'Ichimatsu-sama Shoot-rxouBYVrfUs.mkv'
[debug] ffmpeg command line: ffmpeg -y -i 'file:Ichimatsu-sama Shoot-rxouBYVrfUs.mkv' -c copy -metadata 'comment=一松様シュート
Original link
http://www.nicovideo.jp/watch/sm28012891
Author: SR' -metadata 'description=一松様シュート
Original link
http://www.nicovideo.jp/watch/sm28012891
Author: SR' -metadata artist=Rlcemaster3 -metadata 'title=Ichimatsu-sama Shoot' -metadata date=20160115 -metadata 'purl=https://www.youtube.com/watch?v=rxouBYVrfUs' 'file:Ichimatsu-sama Shoot-rxouBYVrfUs.temp.mkv'
[ffmpeg] There aren't any subtitles to convert
[ffmpeg] There aren't any subtitles to embed
ERROR: Only mp3 and m4a/mp4 are supported for thumbnail embedding for now.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1737, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/postprocessor/embedthumbnail.py", line 90, in run
    raise EmbedThumbnailPPError('Only mp3 and m4a/mp4 are supported for thumbnail embedding for now.')
EmbedThumbnailPPError
```

**Comment by dstftw** [comment]
Dupicate of #6046.

**Comment by vxbinaca** [comment]
My apologies. I'll search better next time.

**Comment by svnpenn** [comment]
https://github.com/rg3/youtube-dl/issues/10359

**Comment by svnpenn** [comment]
http://github.com/rg3/youtube-dl/issues/11981

**Comment by svnpenn** [comment]
http://github.com/rg3/youtube-dl/issues/12126

**Comment by svnpenn** [comment]
http://github.com/rg3/youtube-dl/issues/12459

**Comment by svnpenn** [comment]
https://github.com/rg3/youtube-dl/pull/15445
