### ISSUE TITLE
vidzi.tv not working

### ISSUE THREAD

**Issue by timeDev** [rg3/youtube-dl#8386]
Verbose output, tested with multiple urls:

```
$ youtube-dl "http://vidzi.tv/hwnpbckw1xq9.html" --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://vidzi.tv/hwnpbckw1xq9.html', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.01.31
[debug] Python version 3.5.1 - Linux-4.3.3-3-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 2.8.5, ffprobe 2.8.5, rtmpdump 2.4
[debug] Proxy map: {}
[Vidzi] hwnpbckw1xq9: Downloading webpage
ERROR: Unable to extract video_hash; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 666, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 313, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/vidzi.py", line 27, in _real_extract
    r'\|([a-z0-9]+)\|hls\|type', webpage, 'video_hash')
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 617, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 608, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract video_hash; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by yan12125** [comment]
Thanks for the report. Vidzi.tv support will be fixed in the next version.
