### ISSUE TITLE
C-Span - unable to find video id and type

### ISSUE THREAD

**Issue by Enverex** [rg3/youtube-dl#8401]
Doesn't look like it's able to find the video on this page - http://www.c-span.org/video/?c4578575/clinton-voter-fraud-polk-county-iowa-caucus

Not sure how well C-Span downloading works in general as I've not tried before, but I saw a closed but mentioning that it should work.

**Comment by phihag** [comment]
This bug report is missing required information, namely the complete output of youtube-dl when called with `-v`. Please make sure to consult our [bug reporting guidelines](https://github.com/rg3/youtube-dl/blob/master/CONTRIBUTING.md). Without the required information, we cannot help you. For what it's worth, downloading the URL you mention works fine for me.

**Comment by Enverex** [comment]
Whoops, knew I forgot something. Unfortunately it doesn't seem to contain anything of any use that I can see.

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-o', '%(upload_date)s - %(title)s (%(id)s).%(ext)s', '--embed-subs', '--add-metadata', 'http://www.c-span.org/video/?c4578575/clinton-voter-fraud-polk-county-iowa-caucus', '-vv']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.01.09
[debug] Python version 3.5.1 - Linux-4.2.3-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 2.8.5, ffprobe 2.8.5, rtmpdump 2.4
[debug] Proxy map: {}
[CSpan] c4578575: Downloading webpage
ERROR: unable to find video id and type; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 665, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 312, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/cspan.py", line 77, in _real_extract
    raise ExtractorError('unable to find video id and type')
youtube_dl.utils.ExtractorError: unable to find video id and type; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by phihag** [comment]
You are using an outdated version of youtube-dl. See [our FAQ](https://yt-dl.org/update) on how to update.

**Comment by Enverex** [comment]
I'm using the version available within Arch Linux. I guess they need to be prodded to update. Thanks.
