### ISSUE TITLE
New format of cc.com url, not recognized by youtube-dl

### ISSUE THREAD

**Issue by blha303** [rg3/youtube-dl#8405]
For example http://www.cc.com/shows/the-daily-show-with-trevor-noah/interviews/6yx39d/exclusive-rand-paul-extended-interview, this does not match the regex in [comedycentral.py](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/comedycentral.py#L18-L20), possibly a recent change. I'd PR a fix but unfortunately I'm not sure how to handle the url with all the extra metadata like show names.

```
$ youtube-dl http://www.cc.com/shows/the-daily-show-with-trevor-noah/interviews/6yx39d/exclusive-rand-paul-extended-interview --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://www.cc.com/shows/the-daily-show-with-trevor-noah/interviews/6yx39d/exclusive-rand-paul-extended-interview', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.01
[debug] Python version 2.7.9 - Linux-3.19.0-15-generic-x86_64-with-Ubuntu-15.04-vivid
[debug] exe versions: ffmpeg N-48515-g379ddc6-static, ffprobe N-48515-g379ddc6-static
[debug] Proxy map: {}
[generic] exclusive-rand-paul-extended-interview: Requesting header
WARNING: Falling back on generic information extractor.
[generic] exclusive-rand-paul-extended-interview: Downloading webpage
[generic] exclusive-rand-paul-extended-interview: Extracting information
ERROR: Unsupported URL: http://www.cc.com/shows/the-daily-show-with-trevor-noah/interviews/6yx39d/exclusive-rand-paul-extended-interview
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 1289, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/compat.py", line 248, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=etree.TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/compat.py", line 237, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 37, column 157
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 666, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 313, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 1919, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.cc.com/shows/the-daily-show-with-trevor-noah/interviews/6yx39d/exclusive-rand-paul-extended-interview
```

**Comment by blha303** [comment]
And trying to correct the url doesn't work either, as all old urls seem to redirect to the new site (without keeping what video you were requesting either. so rude)

```
$ youtube-dl http://thedailyshow.cc.com/video-clips/6yx39d/exclusive-rand-paul-extended-interview --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://thedailyshow.cc.com/video-clips/6yx39d/exclusive-rand-paul-extended-interview', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.01
[debug] Python version 2.7.9 - Linux-3.19.0-15-generic-x86_64-with-Ubuntu-15.04-vivid
[debug] exe versions: ffmpeg N-48515-g379ddc6-static, ffprobe N-48515-g379ddc6-static
[debug] Proxy map: {}
[generic] exclusive-rand-paul-extended-interview: Requesting header
[redirect] Following redirect to http://www.cc.com/shows/the-daily-show-with-trevor-noah
[generic] the-daily-show-with-trevor-noah: Requesting header
WARNING: Falling back on generic information extractor.
[generic] the-daily-show-with-trevor-noah: Downloading webpage
[generic] the-daily-show-with-trevor-noah: Extracting information
ERROR: Unsupported URL: http://www.cc.com/shows/the-daily-show-with-trevor-noah
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 1289, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/compat.py", line 248, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=etree.TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/compat.py", line 237, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 34, column 163
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 666, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 313, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 1919, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.cc.com/shows/the-daily-show-with-trevor-noah
```

**Comment by blha303** [comment]
Bump, still not working.

```
$ youtube-dl http://www.cc.com/shows/the-daily-show-with-trevor-noah/interviews/6yx39d/exclusive-rand-paul-extended-interview
[generic] exclusive-rand-paul-extended-interview: Requesting header
WARNING: Falling back on generic information extractor.
[generic] exclusive-rand-paul-extended-interview: Downloading webpage
[generic] exclusive-rand-paul-extended-interview: Extracting information
ERROR: Unsupported URL: http://www.cc.com/shows/the-daily-show-with-trevor-noah/interviews/6yx39d/exclusive-rand-paul-extended-interview

**Comment by jaimeMF** [comment]
Should be fixed in the next version, thanks for the report.

**Comment by blha303** [comment]
Thanks ^_^
