### ISSUE TITLE
site request: atpworldour

### ISSUE THREAD

**Issue by RingoTheDog** [rg3/youtube-dl#8409]
"Association of Tennis Professionals"

URL example: 
http://www.atpworldtour.com/en/video/rotterdam-2015-final-highlights-wawrinka-berdych

Thanks
Ringo

**Comment by RingoTheDog** [comment]
FWIW....

The Generic Extractor appears to work when I give it the direct link to the video:

http://video.atpworldtour.com/FyYjllczpxzMco262GNPRHsaVzAPOJ0x/DOcJ-FxaFrRg4gtDEwOjEzYzowMDE7C3?_=czrqyc766r

(It doesn't seem to recognize the play button overlay?...just a guess)

**Comment by RingoTheDog** [comment]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.04.01*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X ] I've **verified** and **I assure** that I'm running youtube-dl **2016.04.01**

### Before submitting an *issue* make sure you have:
- [X ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ X] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
C:\>youtube-dl.py -v "http://www.atpworldtour.com/en/video/nishikori-downs-kyrgi
os-in-miami-2016"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.atpworldtour.com/en/video/nishik
ori-downs-kyrgios-in-miami-2016']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.04.01
[debug] Python version 2.7.11 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-71346-gdf4fca2
[debug] Proxy map: {}
[generic] nishikori-downs-kyrgios-in-miami-2016: Requesting header
WARNING: Falling back on generic information extractor.
[generic] nishikori-downs-kyrgios-in-miami-2016: Downloading webpage
[generic] nishikori-downs-kyrgios-in-miami-2016: Extracting information
ERROR: Unsupported URL: http://www.atpworldtour.com/en/video/nishikori-downs-kyr
gios-in-miami-2016
Traceback (most recent call last):
  File "C:\youtube-dl.py\youtube_dl\extractor\generic.py", line 1348, in _real_e
xtract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "C:\youtube-dl.py\youtube_dl\compat.py", line 278, in compat_etree_fromst
ring
    doc = _XML(text, parser=etree.XMLParser(target=etree.TreeBuilder(element_fac
tory=_element_factory)))
  File "C:\youtube-dl.py\youtube_dl\compat.py", line 267, in _XML
    parser.feed(text)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 93, column 53
Traceback (most recent call last):
  File "C:\youtube-dl.py\youtube_dl\YoutubeDL.py", line 669, in extract_info
    ie_result = ie.extract(url)
  File "C:\youtube-dl.py\youtube_dl\extractor\common.py", line 323, in extract
    return self._real_extract(url)
  File "C:\youtube-dl.py\youtube_dl\extractor\generic.py", line 2012, in _real_e
xtract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.atpworldtour.com/en/video/nishikor
i-downs-kyrgios-in-miami-2016...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://www.atpworldtour.com/en/video/nishikori-downs-kyrgios-in-miami-2016
- Single video: http://www.atpworldtour.com/en/video/rotterdam-2015-final-highlights-wawrinka-berdych
- Playlist: N/A

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* required an account credentials please provide them or explain how one can obtain them.

Webpage does not work:
http://www.atpworldtour.com/en/video/nishikori-downs-kyrgios-in-miami-2016
But  direct link to video does work:
http://video.atpworldtour.com/d1Z2FpMjE6kQfebHIQ4cLlXYYwrzItHD/DOcJ-FxaFrRg4gtDEwOmk2OjBrO6qGv_?_=tkvgtpsu0vnz6qjmj9k9
