### ISSUE TITLE
www.srf.ch: some downloads work and very similar ones don't with youtube-dl 2016.02.01

### ISSUE THREAD

**Issue by thomas-maeder** [rg3/youtube-dl#8411]
E.g. this works:
http://www.srf.ch/play/tv/aeschbacher/video/nico-georgiadis?id=27849ebf-00f4-4a56-85e9-d053d5247a4a
but this doesn't:
http://www.srf.ch/play/tv/aeschbacher/video/jakob-rickenbach?id=00572972-191b-4710-8017-6d6a30ee2cf1
```
youtube-dl --verbose 'http://www.srf.ch/play/tv/aeschbacher/video/jakob-rickenbach?id=00572972-191b-4710-8017-6d6a30ee2cf1'
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.srf.ch/play/tv/aeschbacher/video/jakob-rickenbach?id=00572972-191b-4710-8017-6d6a30ee2cf1']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.01
[debug] Python version 2.7.8 - Linux-3.16.7-29-default-x86_64-with-SuSE-13.2-x86_64
[debug] exe versions: ffmpeg 2.8.5, ffprobe 2.8.5, rtmpdump 2.4
[debug] Proxy map: {}
[SRGSSR] 00572972-191b-4710-8017-6d6a30ee2cf1: Downloading JSON metadata
ERROR: Unable to extract ext; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 666, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 313, in extract
    return self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/srgssr.py", line 75, in _real_extract
    ext = self._search_regex(r'([a-z0-9]+):[^/]+', asset_url, 'ext')
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 608, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract ext; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
as opposed to
```
youtube-dl --verbose 'http://www.srf.ch/play/tv/aeschbacher/video/nico-georgiadis?id=27849ebf-00f4-4a56-85e9-d053d5247a4a'
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.srf.ch/play/tv/aeschbacher/video/nico-georgiadis?id=27849ebf-00f4-4a56-85e9-d053d5247a4a']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.01
[debug] Python version 2.7.8 - Linux-3.16.7-29-default-x86_64-with-SuSE-13.2-x86_64
[debug] exe versions: ffmpeg 2.8.5, ffprobe 2.8.5, rtmpdump 2.4
[debug] Proxy map: {}
[SRGSSR] 27849ebf-00f4-4a56-85e9-d053d5247a4a: Downloading JSON metadata
[SRGSSR] 27849ebf-00f4-4a56-85e9-d053d5247a4a: Downloading f4m manifest
[SRGSSR] 27849ebf-00f4-4a56-85e9-d053d5247a4a: Downloading m3u8 information
[debug] Invoking downloader on u'http://podcastsource.sf.tv/nps/podcast/aeschbacher/2014/06/aeschbacher_20140626_222613_v_podcast_h264_q30.mp4'
[download] Destination: Nico Georgiadis-27849ebf-00f4-4a56-85e9-d053d5247a4a.mp4
[download]   0.3% of 1.32GiB at  3.60MiB/s ETA 06:14^C
ERROR: Interrupted by user
```

**Comment by remitamine** [comment]
will be fixed in the next version.
