### ISSUE TITLE
[Vidme] Channel downloading doesn't work

### ISSUE THREAD

**Issue by vxbinaca** [rg3/youtube-dl#8416]
Video downloads are supported but not channel dumps.

```
youtube-dl --verbose --write-pages https://vid.me/rizeki
```
```
[debug] System config: []
[debug] User config: [u'--download-archive', u'~/.ytdlarchive', u'--retries', u'100', u'--no-overwrites', u'--call-home', u'--continue', u'--write-info-json', u'--write-description', u'--write-thumbnail', u'--write-annotations', u'--all-subs', u'--sub-format', u'srt', u'--convert-subs', u'srt', u'--write-sub', u'--add-metadata', u'-f', u'bestvideo+bestaudio/best', u'--merge-output-format', u'mkv', u'--embed-subs']
[debug] Command-line args: [u'--verbose', u'--write-pages', u'https://vid.me/rizeki']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.01
[debug] Python version 2.7.10 - Linux-4.2.0-25-generic-x86_64-with-Ubuntu-15.10-wily
[debug] exe versions: ffmpeg 2.7.5-0ubuntu0.15.10.1, ffprobe 2.7.5-0ubuntu0.15.10.1, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Public IP address: 76.101.221.232
[Vidme] rizeki: Downloading JSON metadata
ERROR: Vidme returned error: Video not found
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/vidme.py", line 136, in _real_extract
    'https://api.vid.me/videoByUrl/%s' % video_id, video_id)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 497, in _download_json
    encoding=encoding)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 465, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 372, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 361, in _request_webpage
    raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
ExtractorError: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 666, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 313, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/vidme.py", line 146, in _real_extract
    '%s returned error: %s' % (self.IE_NAME, error), expected=True)
ExtractorError: Vidme returned error: Video not found
```

**Comment by dstftw** [comment]
vidme:user will be supported in the next version.

**Comment by vxbinaca** [comment]
@dstftw requesting re-open this bug has cropped back up
