### ISSUE TITLE
NHL falls back to generic...

### ISSUE THREAD

**Issue by RingoTheDog** [rg3/youtube-dl#8419]
https://www.nhl.com/news/dennis-wideman-suspended/c-278258934

youtube-dl.py -v "https://www.nhl.com/news/dennis-wideman-suspended/c-278258
934"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://www.nhl.com/news/dennis-wideman-sus
pended/c-278258934']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.02.01
[debug] Python version 2.7.11 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-71346-gdf4fca2
[debug] Proxy map: {}
[generic] c-278258934: Requesting header
WARNING: Falling back on generic information extractor.
[generic] c-278258934: Downloading webpage
[generic] c-278258934: Extracting information
ERROR: Unsupported URL: https://www.nhl.com/news/dennis-wideman-suspended/c-2782
58934
Traceback (most recent call last):
  File "C:\youtube-dl.py\youtube_dl\extractor\generic.py", line 1289, in _real_e
xtract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "C:\youtube-dl.py\youtube_dl\compat.py", line 248, in compat_etree_fromst
ring
    doc = _XML(text, parser=etree.XMLParser(target=etree.TreeBuilder(element_fac
tory=_element_factory)))
  File "C:\youtube-dl.py\youtube_dl\compat.py", line 237, in _XML
    parser.feed(text)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 80, column 293
Traceback (most recent call last):
  File "C:\youtube-dl.py\youtube_dl\YoutubeDL.py", line 666, in extract_info
    ie_result = ie.extract(url)
  File "C:\youtube-dl.py\youtube_dl\extractor\common.py", line 313, in extract
    return self._real_extract(url)
  File "C:\youtube-dl.py\youtube_dl\extractor\generic.py", line 1919, in _real_e
xtract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.nhl.com/news/dennis-wideman-suspe
nded/c-278258934

Same video different urls:
https://www.nhl.com/video/c-40784403  this URL forwards to:
https://www.nhl.com/video/wideman-suspended-by-nhl/t-277350912/c-40784403

Thanks
Ringo

**Comment by RingoTheDog** [comment]
Different URL...similar result:
https://www.nhl.com/video/preview-canucks-vs-coyotes/t-277350912/c-41108803

**Comment by RingoTheDog** [comment]
Here is a bit more info...hopefully it will be helpful:

If I attempt this URL:   
https://www.nhl.com/bruins/video/bruins-beat-back-at-home/t-277464000/c-41694303
...the generic fails with usupported URL

The generic extractor IS able to pull the video from the direct link:
http://md-akc.med.nhl.com/mp4/nhl/2016/02/22/ae823bbd-7f7b-4a15-8738-d3a52efd2eb0/1456171579536/asset_1800k.mp4


All of the versions can be found in here: 
```
{"type":"contentXrefSystem","value":"NHL-AMS-WEB","displayName":"NHL-AMS-WEB"}],
"playbacks":[
{"name":"HTTP_CLOUD_MOBILE","width":"null","height":"null","url":"http://md-akc.med.nhl.com/hls/nhl/2016/02/22/ae823bbd-7f7b-4a15-8738-d3a52efd2eb0/1456171579534/master_mobile.m3u8"},
{"name":"HTTP_CLOUD_TABLET","width":"null","height":"null","url":"http://md-akc.med.nhl.com/hls/nhl/2016/02/22/ae823bbd-7f7b-4a15-8738-d3a52efd2eb0/1456171579534/master_tablet.m3u8"},
{"name":"HTTP_CLOUD_TABLET_60","width":null,"height":null,"url":"http://md-akc.med.nhl.com/hls/nhl/2016/02/22/ae823bbd-7f7b-4a15-8738-d3a52efd2eb0/1456171579534/master_tablet60.m3u8"},
{"name":"HTTP_CLOUD_WIRED","width":"null","height":"null","url":"http://md-akc.med.nhl.com/hls/nhl/2016/02/22/ae823bbd-7f7b-4a15-8738-d3a52efd2eb0/1456171579534/master_wired.m3u8"},
{"name":"HTTP_CLOUD_WIRED_60","width":null,"height":null,"url":"http://md-akc.med.nhl.com/hls/nhl/2016/02/22/ae823bbd-7f7b-4a15-8738-d3a52efd2eb0/1456171579534/master_wired60.m3u8"},
{"name":"HTTP_CLOUD_WIRED_WEB","width":null,"height":null,"url":"http://md-akc.med.nhl.com/hls/nhl/2016/02/22/ae823bbd-7f7b-4a15-8738-d3a52efd2eb0/1456171579534/master_wired_web.m3u8"},
{"name":"FLASH_192K_320X180","width":"320","height":"180","url":"http://md-akc.med.nhl.com/mp4/nhl/2016/02/22/ae823bbd-7f7b-4a15-8738-d3a52efd2eb0/1456171579536/asset_192k.mp4"},
{"name":"FLASH_450K_400X224","width":"400","height":"224","url":"http://md-akc.med.nhl.com/mp4/nhl/2016/02/22/ae823bbd-7f7b-4a15-8738-d3a52efd2eb0/1456171579536/asset_450k.mp4"},
{"name":"FLASH_1200K_640X360","width":"640","height":"360","url":"http://md-akc.med.nhl.com/mp4/nhl/2016/02/22/ae823bbd-7f7b-4a15-8738-d3a52efd2eb0/1456171579536/asset_1200k.mp4"},
{"name":"FLASH_1800K_960X540","width":"960","height":"540","url":"http://md-akc.med.nhl.com/mp4/nhl/2016/02/22/ae823bbd-7f7b-4a15-8738-d3a52efd2eb0/1456171579536/asset_1800k.mp4"}]},
```
