### ISSUE TITLE
Downloading Downton Abbey on PBS (WGBH)

### ISSUE THREAD

**Issue by harlanb** [rg3/youtube-dl#8421]
I've been able to download some episodes from this site, but not all of them.  Commands and debugging below.

$ youtube-dl --prefer-ffmpeg http://www.pbs.org/wgbh/masterpiece/watch-online/full-episodes/downton-abbey-season-6-episode-2/
[pbs] downton-abbey-season-6-episode-2: Downloading webpage
[pbs] downton-abbey-season-6-episode-2: Downloading player page
ERROR: Unable to extract video ID; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

youtube-dl is up-to-date (2016.02.01)

$youtube-dl --verbose --prefer-ffmpeg http://www.pbs.org/wgbh/masterpiece/watch-online/full-episodes/downton-abbey-season-6-episode-2/ >da_s6e2.out 2>&1

output:
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'--prefer-ffmpeg', u'http://www.pbs.org/wgbh/masterpiece/watch-online/full-episodes/downton-abbey-season-6-episode-2/']
[debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8
[debug] youtube-dl version 2016.02.01
[debug] Python version 2.7.6 - Linux-3.13.0-37-generic-x86_64-with-LinuxMint-17.1-rebecca
[debug] exe versions: avconv 9.18-6, avprobe 9.18-6, ffmpeg N-76694-ga62178b, ffprobe N-76694-ga62178b, rtmpdump 2.4
[debug] Proxy map: {}
[pbs] downton-abbey-season-6-episode-2: Downloading webpage
[pbs] downton-abbey-season-6-episode-2: Downloading player page
ERROR: Unable to extract video ID; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 666, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 313, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/pbs.py", line 427, in _real_extract
    video_id, display_id, upload_date = self._extract_webpage(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/pbs.py", line 419, in _extract_webpage
    r'<div\s+id="video_([0-9]+)"', player_page, 'video ID')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 608, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video ID; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by 89z** [comment]
It seems that videos are available on Masterpiece (which you linked), but also on the PBS site:

https://pbs.org/video/masterpiece-downton-abbey-season-6-episode-2

The PBS URLs (`pbs.org/video/`) are much easier to extract, as the URL includes the slug that you can plug directly into PBS API.
