### ISSUE TITLE
Unable to extract iframe url

### ISSUE THREAD

**Issue by sieben** [rg3/youtube-dl#8427]
$ youtube-dl -t http://www.arte.tv/guide/fr/053915-009-A/france-allemagne-une-histoire-commune-9-10
[arte.tv:+7] 053915-009-A: Downloading webpage
ERROR: Unable to extract iframe url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

$ youtube-dl --verbose -t http://www.arte.tv/guide/fr/053915-009-A/france-allemagne-une-histoire-commune-9-10
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'-t', u'http://www.arte.tv/guide/fr/053915-009-A/france-allemagne-une-histoire-commune-9-10']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.04
[debug] Python version 2.7.6 - Linux-3.13.0-77-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 11.4, avprobe 11.4, rtmpdump 2.4
[debug] Proxy map: {}
[arte.tv:+7] 053915-009-A: Downloading webpage
ERROR: Unable to extract iframe url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/sieben/.local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 666, in extract_info
    ie_result = ie.extract(url)
  File "/home/sieben/.local/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 313, in extract
    return self._real_extract(url)
  File "/home/sieben/.local/lib/python2.7/site-packages/youtube_dl/extractor/arte.py", line 83, in _real_extract
    return self._extract_from_webpage(webpage, video_id, lang)
  File "/home/sieben/.local/lib/python2.7/site-packages/youtube_dl/extractor/arte.py", line 98, in _extract_from_webpage
    webpage, 'iframe url', group='url')
  File "/home/sieben/.local/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 617, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/home/sieben/.local/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 608, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract iframe url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by hhl** [comment]
same problem/issue on debian sid, i tested it with the debian version
```
 LANG=C apt-cache policy youtube-dl
youtube-dl:
  Installed: (none)
  Candidate: 2015.11.27.1-1.1
```

and the one you provied

```python
$ youtube-dl --verbose -F http://www.arte.tv/guide/de/036943-000-A/360-geo-reportage
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'-F', u'http://www.arte.tv/guide/de/036943-000-A/360-geo-reportage']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.04
[debug] Python version 2.7.11 - Linux-4.4.1-towo.1-siduction-amd64-x86_64-with-debian-stretch-sid
[debug] exe versions: avconv 2.8.6-1, avprobe 2.8.6-1, ffmpeg 2.8.6-1, ffprobe 2.8.6-1, rtmpdump 2.4
[debug] Proxy map: {}
[arte.tv:+7] 036943-000-A: Downloading webpage
ERROR: Unable to extract iframe url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 666, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 313, in extract
    return self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/arte.py", line 83, in _real_extract
    return self._extract_from_webpage(webpage, video_id, lang)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/arte.py", line 98, in _extract_from_webpage
    webpage, 'iframe url', group='url')
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 617, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 608, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract iframe url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by jaimeMF** [comment]
It will be fixed in the next version, thanks for the report.
