### ISSUE TITLE
Unable to extract iframe url

### ISSUE THREAD

**Issue by esonntag** [rg3/youtube-dl#8431]
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.arte.tv/guide/de/055938-001-A/wie-weit-gehen-1-3?autoplay=1&plus7first=1']
[debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8
[debug] youtube-dl version 2016.02.04
[debug] Python version 2.7.6 - Linux-3.13.0-76-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.18-6, avprobe 9.18-6, rtmpdump 2.4
[debug] Proxy map: {}
[arte.tv:+7] 055938-001-A: Downloading webpage
ERROR: Unable to extract iframe url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 666, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 313, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/arte.py", line 83, in _real_extract
    return self._extract_from_webpage(webpage, video_id, lang)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/arte.py", line 98, in _extract_from_webpage
    webpage, 'iframe url', group='url')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 617, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 608, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract iframe url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
This issue is already fixed and fix will be incorporated in the next version of youtube-dl.
