### ISSUE TITLE
site support request: closertotruth.com

### ISSUE THREAD

**Issue by privong** [rg3/youtube-dl#8435]
Sample URL: http://closertotruth.com/series/what-truth#video-49253

```
$ youtube-dl --version
2016.01.09
```

```
$ youtube-dl -v http://closertotruth.com/series/what-truth#video-49253
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://closertotruth.com/series/what-truth#video-49253']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.01.09
[debug] Python version 3.5.1 - Linux-4.4.1-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 2.8.6, ffprobe 2.8.6, rtmpdump 2.4
[debug] Proxy map: {}
[generic] what-truth#video-49253: Requesting header
WARNING: Falling back on generic information extractor.
[generic] what-truth#video-49253: Downloading webpage
[generic] what-truth#video-49253: Extracting information
ERROR: Unsupported URL: http://closertotruth.com/series/what-truth#video-49253
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 665, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 312, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/generic.py", line 1908, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: http://closertotruth.com/series/what-truth#video-49253
```

**Comment by TRox1972** [comment]
As of current version CloserToTruth is supported.
