### ISSUE TITLE
stopped working on arte.tv

### ISSUE THREAD

**Issue by Gro-Tsen** [rg3/youtube-dl#8436]
Various links from http://www.arte.tv/guide/fr/plus7/ worked fine until a few days ago, now fails to download json as per following example (note: the URL passed as parameter in this transcript is just an example: it will no longer be valid in a few days, but any link from http://www.arte.tv/guide/fr/plus7/ should illustrate the same problem).

```
vega david /tmp $ /tmp/youtube-dl -v 'http://www.arte.tv/guide/fr/063676-002-A/yourope'
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.arte.tv/guide/fr/063676-002-A/yourope']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.04
[debug] Python version 2.7.9 - Linux-4.3.0-vega-x86_64-with-debian-8.3
[debug] exe versions: ffmpeg 2.6.5, ffprobe 2.6.5, rtmpdump 2.4
[debug] Proxy map: {}
[arte.tv:+7] 063676-002-A: Downloading webpage
ERROR: Unable to extract iframe url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/tmp/youtube-dl/youtube_dl/YoutubeDL.py", line 666, in extract_info
    ie_result = ie.extract(url)
  File "/tmp/youtube-dl/youtube_dl/extractor/common.py", line 313, in extract
    return self._real_extract(url)
  File "/tmp/youtube-dl/youtube_dl/extractor/arte.py", line 83, in _real_extract
    return self._extract_from_webpage(webpage, video_id, lang)
  File "/tmp/youtube-dl/youtube_dl/extractor/arte.py", line 98, in _extract_from_webpage
    webpage, 'iframe url', group='url')
  File "/tmp/youtube-dl/youtube_dl/extractor/common.py", line 617, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/tmp/youtube-dl/youtube_dl/extractor/common.py", line 608, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract iframe url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by dstftw** [comment]
This issue is already fixed and fix will be incorporated in the next version of youtube-dl.

**Comment by Gro-Tsen** [comment]
Wow, you are *fast*!  Thanks.
