### ISSUE TITLE
--add-metadata for youtube broken

### ISSUE THREAD

**Issue by untergrundbiber** [rg3/youtube-dl#8440]
```# youtube-dl -v --add-metadata https://www.youtube.com/watch?v=yB7iNwhle-A```

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'--add-metadata', u'https://www.youtube.com/watch?v=yB7iNwhle-A']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.05
[debug] Python version 2.7.10 - Linux-4.2.0-27-generic-x86_64-with-Ubuntu-15.10-wily
[debug] exe versions: ffmpeg 2.7.6-0ubuntu0.15.10.1, ffprobe 2.7.6-0ubuntu0.15.10.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] yB7iNwhle-A: Downloading webpage
[youtube] yB7iNwhle-A: Downloading video info webpage
[youtube] yB7iNwhle-A: Extracting video information
[youtube] yB7iNwhle-A: Downloading DASH manifest
[youtube] yB7iNwhle-A: Downloading DASH manifest
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on u'https://r20---sn-5hne6ned.googlevideo.com/videoplayback?id=c81ee23708657be0&itag=133&source=youtube&requiressl=yes&ms=au&mv=m&mm=31&mn=sn-5hne6ned&nh=IgpwcjAxLmFtczE2KgkxMjcuMC4wLjE&pl=18&ratebypass=yes&mime=video/mp4&gir=yes&clen=54564&lmt=1454677705626745&dur=9.066&sver=3&mt=1454678720&key=dg_yt0&fexp=9416126,9417367,9418200,9419452,9420452,9421524,9422596,9422970,9423041,9423661,9423662,9424128,9425731,9426696,9428039&upn=SB4ipQ-f9sQ&signature=96A6DB66DBCB984F1BE4F2E5CCD1E387F74D88B4.4B597DC76AECC9098F44A8407A422A94913A5DED&ip=91.17.201.231&ipbits=0&expire=1454700378&sparams=ip,ipbits,expire,id,itag,source,requiressl,ms,mv,mm,mn,nh,pl,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: tmpvqnkMg-yB7iNwhle-A.f133.mp4
[download] 100% of 53.29KiB in 00:00
[debug] Invoking downloader on u'https://r20---sn-5hne6ned.googlevideo.com/videoplayback?mn=sn-5hne6ned&mm=31&expire=1454700376&upn=knLMoIR58QY&itag=251&pl=18&mv=m&mt=1454678720&ms=au&signature=A468DA94AF71D510DECA1793FC400D7F221C4E97.A9EEB791157D662CF578037516E3B60BDF3E2BC6&source=youtube&mime=audio%2Fwebm&clen=185455&requiressl=yes&nh=IgpwcjAxLmFtczE2KgkxMjcuMC4wLjE&initcwndbps=401250&ipbits=0&key=yt6&lmt=1454677729033095&gir=yes&dur=9.141&fexp=9416126%2C9417367%2C9418200%2C9419452%2C9420452%2C9421524%2C9422596%2C9422970%2C9423041%2C9423661%2C9423662%2C9424128%2C9425731%2C9426696%2C9428039&ip=91.17.201.231&sparams=clen%2Cdur%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&keepalive=yes&id=o-AF_2jY4jcEVBJYMTtHe5KBZscH5ZwouUdn6gCexxOAiL&sver=3&ratebypass=yes'
[download] Destination: tmpvqnkMg-yB7iNwhle-A.f251.webm
[download] 100% of 181.11KiB in 00:01
[ffmpeg] Merging formats into "tmpvqnkMg-yB7iNwhle-A.mkv"
[debug] ffmpeg command line: ffmpeg -y -i file:tmpvqnkMg-yB7iNwhle-A.f133.mp4 -i file:tmpvqnkMg-yB7iNwhle-A.f251.webm -c copy -map 0:v:0 -map 1:a:0 file:tmpvqnkMg-yB7iNwhle-A.temp.mkv
Deleting original file tmpvqnkMg-yB7iNwhle-A.f133.mp4 (pass -k to keep)
Deleting original file tmpvqnkMg-yB7iNwhle-A.f251.webm (pass -k to keep)
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 411, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 401, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1690, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 677, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 722, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1360, in process_video_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1672, in process_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1736, in post_process
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 395, in run
KeyError: u'protocol'
```

**Comment by remitamine** [comment]
it will be fixed in the next version.

**Comment by untergrundbiber** [comment]
Thanks :thumbsup:
