### ISSUE TITLE
Error when embedding converted subs

### ISSUE THREAD

**Issue by ping** [rg3/youtube-dl#8444]
The subtitles does get embedded successfully though. The .srt file also remains.

```
$ youtube-dl -f 18 --write-sub --sub-lang 'en' --embed-subs --convert-subs srt fmMQX7GpCjw -v
[debug] System config: []
[debug] User config: [u'--no-mtime', u'-o', u'/Users/ping/Downloads/%(title)s_%(id)s.%(ext)s']
[debug] Command-line args: [u'-f', u'18', u'--write-sub', u'--sub-lang', u'en', u'--embed-subs', u'--convert-subs', u'srt', u'fmMQX7GpCjw', u'-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.05.1
[debug] Python version 2.7.5 - Darwin-13.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.6.2, ffprobe 2.6.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] fmMQX7GpCjw: Downloading webpage
[youtube] fmMQX7GpCjw: Downloading video info webpage
[youtube] fmMQX7GpCjw: Extracting video information
[youtube] fmMQX7GpCjw: Downloading DASH manifest
[youtube] fmMQX7GpCjw: Downloading DASH manifest
[info] Writing video subtitles to: /Users/ping/Downloads/The Human Condition Season 4 _ 인간의 조건 시즌 4 - Ep.1 (2016.01.29)_fmMQX7GpCjw.en.vtt
[debug] Invoking downloader on u'https://r8---sn-npobuxa-npoez.googlevideo.com/videoplayback?sver=3&sparams=dur%2Cgcr%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&id=o-ALfRpCs0Of-DUdXNGCLmKN0wFhDFRNGMihCBXbeiDuJk&initcwndbps=3462500&mn=sn-npobuxa-npoez&mm=31&source=youtube&ratebypass=yes&dur=5065.595&mv=m&mt=1454763783&ms=au&fexp=9407157%2C9410706%2C9416126%2C9418204%2C9420452%2C9422596%2C9423607%2C9423661%2C9423662%2C9425351%2C9425796%2C9426232%2C9427667%2C9428543&key=yt6&itag=18&mime=video%2Fmp4&ipbits=0&signature=939E3B32157F9763811E770B73710D70C7F6A3F5.255C852A63C50AA3826A43A9A977AA38CC0E27D7&lmt=1454160661354439&pcm2=yes&expire=1454785547&pl=17&upn=kzQha4Dri6k&requiressl=yes&gcr=sg'
[download] Destination: /Users/ping/Downloads/The Human Condition Season 4 _ 인간의 조건 시즌 4 - Ep.1 (2016.01.29)_fmMQX7GpCjw.mp4
[download] 100% of 371.17MiB in 20:01
[ffmpeg] Converting subtitles
[debug] ffmpeg command line: ffmpeg -y -i 'file:/Users/ping/Downloads/The Human Condition Season 4 _ 인간의 조건 시즌 4 - Ep.1 (2016.01.29)_fmMQX7GpCjw.en.vtt' -f srt 'file:/Users/ping/Downloads/The Human Condition Season 4 _ 인간의 조건 시즌 4 - Ep.1 (2016.01.29)_fmMQX7GpCjw.en.srt'
Deleting original file /Users/ping/Downloads/The Human Condition Season 4 _ 인간의 조건 시즌 4 - Ep.1 (2016.01.29)_fmMQX7GpCjw.en.vtt (pass -k to keep)
[ffmpeg] Embedding subtitles in '/Users/ping/Downloads/The Human Condition Season 4 _ 인간의 조건 시즌 4 - Ep.1 (2016.01.29)_fmMQX7GpCjw.mp4'
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 411, in main
    
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 401, in _real_main
    
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1690, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 677, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 722, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1360, in process_video_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1672, in process_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1736, in post_process
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 351, in run
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 133, in run_ffmpeg_multiple_files
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 133, in <genexpr>
OSError: [Errno 2] No such file or directory: '/Users/ping/Downloads/The Human Condition Season 4 _ \xec\x9d\xb8\xea\xb0\x84\xec\x9d\x98 \xec\xa1\xb0\xea\xb1\xb4 \xec\x8b\x9c\xec\xa6\x8c 4 - Ep.1 (2016.01.29)_fmMQX7GpCjw.en.vtt'
```

**Comment by jaimeMF** [comment]
It will be fixed in the next version, thanks for the report!
