### ISSUE TITLE
site support request: www.tg4.ie

### ISSUE THREAD

**Issue by Moilleadoir** [rg3/youtube-dl#8453]
Sample URL: http://www.tg4.ie/ga/player/baile/?pid=4742502074001

```$ youtube-dl --version
2016.01.27```

```$ youtube-dl -v http://www.tg4.ie/ga/player/baile/?pid=4742502074001
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.tg4.ie/ga/player/baile/?pid=4742502074001']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.01.27
[debug] Python version 2.7.6 - Linux-3.13.0-77-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.18-6, avprobe 9.18-6, ffmpeg 2.5.3-1kxstudio1, ffprobe 2.5.3-1kxstudio1, rtmpdump 2.4-n87-gita9f353c-ppa8
[debug] Proxy map: {}
[generic] ?pid=4742502074001: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ?pid=4742502074001: Downloading webpage
[generic] ?pid=4742502074001: Extracting information
ERROR: Unsupported URL: http://www.tg4.ie/ga/player/baile/?pid=4742502074001
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 1289, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/lib/python2.7/dist-packages/youtube_dl/compat.py", line 248, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=etree.TreeBuilder(element_factory=_element_factory)))
  File "/usr/lib/python2.7/dist-packages/youtube_dl/compat.py", line 237, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: syntax error: line 2, column 0
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 666, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 313, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 1908, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.tg4.ie/ga/player/baile/?pid=4742502074001```

**Comment by Moilleadoir** [comment]
In case this example expires, news bulletin links are at (English/Irish interface):
http://www.tg4.ie/en/player/news/
http://www.tg4.ie/ga/player/news/

E.g. 
http://www.tg4.ie/en/player/home/?pid=4778518466001
http://www.tg4.ie/ga/player/baile/?pid=4778518466001

**Comment by andyrozman** [comment]
While base support for TG4 now works (it downloads the video), subtitles are not downloaded anymore (few months ago it downloaded subtitles). Could you please look at this and extend youtube-dl to support this? 
I am not sure if the site changed or the application.

Sample link to use is this:
http://www.tg4.ie/en/player/home/?pid=5416347428001&teideal=Garfield&series=Garfield&dlft=NaN

If you open this on website, subtitle works, but its not downloaded when running from youtube-dl.

Tested with 2017.6.x and 2017.7.x

**Comment by Moilleadoir** [comment]
No longer works.

https://www.tg4.ie/ga/player/baile/?pid=5778156510001&teideal=Nuacht%20TG4&series=Nuacht%20TG4&dlft=35

```
youtube-dl --version
2018.04.03
```
`Error when loading first segment 'https://tg4bcbolt-a.akamaihd.net/media/v1/hls/v5/fairplay/1555966122001/51495285-89d6-4e6f-8a2a-5dea9c1d2e5a/0b55a5df-b2fc-4fcf-aa11-fb0ab89d19fa/32e084f0-b6db-4a8c-8b69-4cddbeac1164/5x/segment0.ts'
https://manifest.prod.boltdns.net/manifest/v1/hls/v5/fairplay/1555966122001/51495285-89d6-4e6f-8a2a-5dea9c1d2e5a/0b55a5df-b2fc-4fcf-aa11-fb0ab89d19fa/10s/rendition.m3u8?fastly_token=NWIwYjZmODdfZDUzMzZlZDE4NmIzZDljN2RiZTEzZjQwOTBjY2U0OWViOGE0YjhiYTk5Nzc4NDEwNzI0YzRkNDFjMjkyMmI4ZA%3D%3D: Invalid data found when processing input`

**Comment by Moilleadoir** [comment]
URL: https://www.tg4.ie/ga/player/baile/?pid=5833603513001&teideal=Nuacht%20TG4&series=Nuacht%20TG4&dlft=3

```
$ youtube-dl --version
2018.09.08

$ youtube-dl -v https://www.tg4.ie/ga/player/baile/?pid=5833603513001&teideal=Nuacht%20TG4&series=Nuacht%20TG4&dlft=35
[1] 13493
[2] 13494
[3] 13495
[2]-  Déanta                 teideal=Nuacht%20TG4
[3]+  Déanta                 series=Nuacht%20TG4
xxxx@xxxx:/xxxxx/xxxxx—xxxxxxx/xxx$ [debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.tg4.ie/ga/player/baile/?pid=5833603513001']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.09.08
[debug] Python version 3.6.5 (CPython) - Linux-4.15.0-34-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.4-0ubuntu0.18.04.1, ffprobe 3.4.4-0ubuntu0.18.04.1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] ?pid=5833603513001: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ?pid=5833603513001: Downloading webpage
[generic] ?pid=5833603513001: Extracting information
[download] Downloading playlist: Nuacht TG4 | Baile | Seinnteoir | TG4
[generic] playlist Nuacht TG4 | Baile | Seinnteoir | TG4: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[brightcove:new] 5833603513001: Downloading webpage
[brightcove:new] 5833603513001: Downloading JSON metadata
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/common.py", line 502, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/brightcove.py", line 743, in _real_extract
    json_data, video_id, headers=headers)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/brightcove.py", line 648, in _parse_brightcove_metadata
    self._sort_formats(formats)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/common.py", line 1281, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
