### ISSUE TITLE
unable to extract html5 player

### ISSUE THREAD

**Issue by papermate** [rg3/youtube-dl#8464]
Hello, first thank you all developers for this neat piece of software.

I tried downloading a bunch of videos before but it gave me an error and since it asks me to report the issue here is the --verbose output. I did an update+upgrade before trying again.
I tried the option --call-home as suggested in the guidelines, but seems like there is no such option.

```
user@computer$ youtube-dl -x --verbose https://www.youtube.com/watch?v=VVXJrbCHD_k
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-x', '--verbose', 'https://www.youtube.com/watch?v=VVXJrbCHD_k']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.08.05
[debug] Python version 2.7.9 - Linux-3.16.0-4-686-pae-i686-with-BunsenLabs-8.1-Hydrogen
[debug] Proxy map: {}
[youtube] Setting language
[youtube] VVXJrbCHD_k: Downloading webpage
[youtube] VVXJrbCHD_k: Downloading video info webpage
[youtube] VVXJrbCHD_k: Extracting video information
[youtube] VVXJrbCHD_k: Encrypted signatures detected.
WARNING: unable to extract html5 player; please report this issue on http://yt-dl.org/bug
[youtube] {22} signature length 41.40, html5 player None
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 479, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 356, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
ExtractorError: Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vfl93P520/base.js'; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 479, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 356, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
ExtractorError: Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vfl93P520/base.js'; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 516, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 170, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 860, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 489, in _decrypt_signature
    u'Signature extraction failed: ' + tb, cause=e)
ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 479, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 356, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
ExtractorError: Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vfl93P520/base.js'; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

```

**Comment by phihag** [comment]
You are using an outdated version of youtube-dl (it's from 2014! The last change of the YouTube interface was in late December 2015). Update to a version from this year. See [our FAQ](https://yt-dl.org/update) if you need help updating.
