### ISSUE TITLE
Dash errors confirmed and download from specified file index question

### ISSUE THREAD

**Issue by NoobishOne** [rg3/youtube-dl#8466]
Confirm often errors with DashSegments!

Question: is it possible to fast-download from certain index position of file?
For my examples when it fails at 4000+ /12000 file, is it possible (or it is a request?) to download from this 4000 file, or next file. 
-c (--continue) - doesnt help. 
I know there is -i (ignore errors) attribute, but...
Filtering --beforedate helps a little, but again, youtube-dl cycles through all 4000 list from scratch with downloading meta and dash manifests for each - so its 10-12 minutes now, and more in perspective. So it good to have something like  --startfrom 4122 so it fast skip  4121 lines from playlists pages.

Back to DashSegments error:
```
[download] Downloading video 4284 of 12889
[youtube] j9s_ZDloG2g: Downloading webpage
[youtube] j9s_ZDloG2g: Downloading video info webpage
[youtube] j9s_ZDloG2g: Extracting video information
[youtube] j9s_ZDloG2g: Downloading DASH manifest
[youtube] j9s_ZDloG2g: Downloading DASH manifest
[debug] Invoking downloader on u'https://r2---sn-jvhnu5g-c35l.googlevideo.com/vi
deoplayback/id/8fdb3f6439681b68/itag/135/source/yt_otf/requiressl/yes/ms/au/pl/2
0/mn/sn-jvhnu5g-c35l/mm/31/mv/m/ratebypass/yes/mime/video%2Fmp4/otfp/1/otf/1/lmt
/1447998553518628/upn/KI9nCpVF_40/signature/198C0C9625F51077B2CAE13AE3F267EFAF2C
74B4.470D1AA30677B1CE0D2F10A2EDF768D6F788D67F/fexp/9415031,9416126,9416916,94174
87,9418199,9420452,9420539,9422596,9423661,9423662,9425972,9426719,9427107,94282
91,9428437/mt/1454961290/key/dg_yt0/sver/3/ip/91.78.243.12/ipbits/0/expire/14549
83027/sparams/ip,ipbits,expire,id,itag,source,requiressl,ms,pl,mn,mm,mv,ratebypa
ss,mime,otfp,otf,lmt/'
[download] Destination: YDK\SAM_0096.20151119.f135.mp4
[DashSegments] j9s_ZDloG2g: Downloading initialization segment
[DashSegments] j9s_ZDloG2g: Downloading segment 1 / 49
[DashSegments] j9s_ZDloG2g: Downloading segment 2 / 49
[DashSegments] j9s_ZDloG2g: Downloading segment 3 / 49
[DashSegments] j9s_ZDloG2g: Downloading segment 4 / 49
[DashSegments] j9s_ZDloG2g: Downloading segment 5 / 49
[DashSegments] j9s_ZDloG2g: Downloading segment 6 / 49
[DashSegments] j9s_ZDloG2g: Downloading segment 7 / 49
[DashSegments] j9s_ZDloG2g: Downloading segment 8 / 49
[DashSegments] j9s_ZDloG2g: Downloading segment 9 / 49
[DashSegments] j9s_ZDloG2g: Downloading segment 10 / 49
[DashSegments] j9s_ZDloG2g: Downloading segment 11 / 49
[DashSegments] j9s_ZDloG2g: Downloading segment 12 / 49
[DashSegments] j9s_ZDloG2g: Downloading segment 13 / 49
[DashSegments] j9s_ZDloG2g: Downloading segment 14 / 49
[DashSegments] j9s_ZDloG2g: Downloading segment 15 / 49
[DashSegments] j9s_ZDloG2g: Downloading segment 16 / 49
[DashSegments] j9s_ZDloG2g: Downloading segment 17 / 49
[DashSegments] j9s_ZDloG2g: Downloading segment 18 / 49
[DashSegments] j9s_ZDloG2g: Downloading segment 19 / 49
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 1616, in process_info
  File "youtube_dl\YoutubeDL.pyo", line 1564, in dl
  File "youtube_dl\downloader\common.pyo", line 343, in download
  File "youtube_dl\downloader\dash.pyo", line 50, in real_download
  File "youtube_dl\downloader\dash.pyo", line 29, in append_url_to_file
  File "youtube_dl\YoutubeDL.pyo", line 1903, in urlopen
  File "urllib2.pyo", line 437, in open
  File "urllib2.pyo", line 550, in http_response
  File "urllib2.pyo", line 469, in error
  File "urllib2.pyo", line 409, in _call_chain
  File "urllib2.pyo", line 656, in http_error_302
  File "urllib2.pyo", line 437, in open
  File "urllib2.pyo", line 550, in http_response
  File "urllib2.pyo", line 469, in error
  File "urllib2.pyo", line 409, in _call_chain
  File "urllib2.pyo", line 656, in http_error_302
  File "urllib2.pyo", line 437, in open
  File "urllib2.pyo", line 550, in http_response
  File "urllib2.pyo", line 475, in error
  File "urllib2.pyo", line 409, in _call_chain
  File "urllib2.pyo", line 558, in http_error_default
HTTPError: HTTP Error 404: Not Found]
```

Sometimes its pass OK, sometimes it fail on audio ( .m4a)
It was no errors until >4000 files (DashSegments appears)
My commandline looks like (if it matters at all):
`youtube-dl -f "135+(140/171/bestaudio)/bestvideo[height<720]+bestaudio" -o "/YDK/%(title)s.%(upload_date)s.%(ext)s" >here link to videos page on YT< --restrict-filenames --verbose`

Sorry for my english and all, first time submit ))  Thx.

UPD:   oh, i miss begining debug part ))
```
C:\Users\Daho\AppData\Roaming\youtube-dlg>youtube-dl
[debug] System config: []
[debug] User config: [u'-f', u'135+(140/171/bestaudio)/bestvideo[height<720]+bes
taudio', u'-o', u'/YDK/%(title)s.%(upload_date)s.%(ext)s', u'https://ww
w.youtube.com/channel/UCeRXV0lrOTQMKEdvcP_z0Pg/videos', u'--restrict-filenames',
 u'--dateafter', u'20150831', u'--datebefore', u'20151119', u'--verbose']
[debug] Command-line args: []
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.02.05.1
[debug] Python version 2.7.10 - Windows-8-6.2.9200
[debug] exe versions: ffmpeg N-71883-geb9fb50, ffprobe N-71883-geb9fb50
[debug] Proxy map: {}
```

**Comment by dstftw** [comment]
```
--playlist-start NUMBER          Playlist video to start at (default is 1)
```

**Comment by marabu88** [comment]
my comment about this problem now. I think it's important. every time I download a file from this error again, the segments downloaded in previous attempts are downloaded much faster and each time a file is downloaded more. but every time it is downloaded from the first segment, and it is a problem if large files!

I think that the downloaded segments cached somewhere. but the main problem is that it is necessary that such files are downloaded automatically. moreover, often have to start the download of the same file many times.

**Comment by Cinerar** [comment]
The interesting thing is that if you watch video that fails to download in your browser till the end. then youtube-dl will be able to download it.

**Comment by Bryannn** [comment]
I'm facing the same issue. Could you please tell in which update will this problem will be fixed? Thanks
