### ISSUE TITLE
Failure by proxy.

### ISSUE THREAD

**Issue by Gaubee** [rg3/youtube-dl#848]
Under normal circumstances I Goagent as proxy access youtube.com.
In commen-line:
```
youtube-dl --proxy "https://127.0.0.1:8087" -v "https://www.youtube.com/watch?v=Moy1nWM3Zmg"
```

and the output is:
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--proxy', 'https://127.0.0.1:8087', '-v', 'https://
www.youtube.com/watch?v=Moy1nWM3Zmg']
[debug] youtube-dl version 2013.05.14
[debug] Python version 2.7.3 - Windows-7-6.1.7601-SP1
[debug] Proxy map: {'http': 'https://127.0.0.1:8087', 'https': 'https://127.0.0.
1:8087'}
[youtube] Setting language
[youtube] Moy1nWM3Zmg: Downloading video webpage
[youtube] Moy1nWM3Zmg: Downloading video info webpage
[youtube] Moy1nWM3Zmg: Extracting video information
[download] Got server HTTP error. Retrying (attempt 1 of 10)...
[download] Got server HTTP error. Retrying (attempt 2 of 10)...
[download] Got server HTTP error. Retrying (attempt 3 of 10)...
[download] Got server HTTP error. Retrying (attempt 4 of 10)...
[download] Got server HTTP error. Retrying (attempt 5 of 10)...
[download] Got server HTTP error. Retrying (attempt 6 of 10)...
[download] Got server HTTP error. Retrying (attempt 7 of 10)...
[download] Got server HTTP error. Retrying (attempt 8 of 10)...
[download] Got server HTTP error. Retrying (attempt 9 of 10)...
[download] Got server HTTP error. Retrying (attempt 10 of 10)...
ERROR: giving up after 10 retries
Traceback (most recent call last):
  File "youtube_dl\FileDownloader.pyo", line 850, in _do_download
  File "urllib2.pyo", line 126, in urlopen
  File "urllib2.pyo", line 406, in open
  File "urllib2.pyo", line 519, in http_response
  File "urllib2.pyo", line 444, in error
  File "urllib2.pyo", line 378, in _call_chain
  File "urllib2.pyo", line 527, in http_error_default
HTTPError: HTTP Error 500: Internal Server Error
```

I don't know how to do .. help~
I'm try it in window7-64 now and will use it in KUbuntu.
Give me some valuable suggestions.
thanks~!

**Comment by dstftw** [comment]
Obvious problem with your proxy.
