### ISSUE TITLE
Metacafe is not working

### ISSUE THREAD

**Issue by RealDeviil** [rg3/youtube-dl#8539]
# youtube-dl -v http://www.metacafe.com/watch/11364899/annoying_orange_super_mario/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.metacafe.com/watch/11364899/annoying_orange_super_mario/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.13
[debug] Python version 2.7.9 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.3
[debug] exe versions: ffmpeg 2.6.5, ffprobe 2.6.5
[debug] Proxy map: {}
[metacafe] Retrieving disclaimer
[metacafe] Confirming age
[metacafe] 11364899: Downloading webpage
[metacafe] 11364899: Extracting information
ERROR: Unsupported video type; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 666, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 315, in extract
    return self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/metacafe.py", line 218, in _real_extract
    raise ExtractorError('Unsupported video type')
ExtractorError: Unsupported video type; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by RealDeviil** [comment]
Looks like they are using m3u8 playlist files now?, e.g.:  http://cdn.metacafe.com/videos/10856000/10856331/10856331.m3u8

Search for "var flashvars" JSON in the video page source.
