### ISSUE TITLE
CBT Nuggets or Coursera

### ISSUE THREAD

**Issue by signalwarrant** [rg3/youtube-dl#8547]
Has anyone gotten this to work with CBT Nuggets or Coursera?

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl/blob/master/README.md#is-the-description-of-the-issue-itself-sufficient

**Comment by lukecamilo** [comment]
Hi, it looks like this is an actual issue. I couldn't download any CBT Nuggets videos.

I'm running the windows version on windows server 2012 R2, using powershell. $url contains the URL where the video landing page is, and $opciones contains the options used for the filename.
$username and $password won't be disclosed, but they are a working set used daily to watch those videos.

Here's the full output:

```
PS C:\Users\Administrator> $url= "https://www.cbtnuggets.com/it-training/microsoft-windows-server-2012-training-70-410-r2/2?autostart=1"
PS C:\Users\Administrator> $opciones= "C:/videos/training/%(playlist_title)s/%(autonumber)s - %(title)s.%(ext)s"
PS C:\Users\Administrator> youtube-dl --no-check-certificate --verbose --username $username --password $password --sleep-interval 240 -o $opciones $url
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--no-check-certificate', u'--verbose', u'--username', u'PRIVATE', u'--password', u'PRIVATE', u'--sleep-interval', u'240', u'-o', u'C:/videos/training/%(playlist_title)s/%(autonumber)s - %(title)s.%(ext)s', u'https://www.cbtnuggets.com/it-training/microsoft-windows-server-2012-training-70-410-r2/2?autostart=1']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.03.01
[debug] Python version 2.7.10 - Windows-2012Server-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {}
[generic] 2?autostart=1: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 2?autostart=1: Downloading webpage
[generic] 2?autostart=1: Extracting information
ERROR: Unsupported URL: https://www.cbtnuggets.com/it-training/microsoft-windows-server-2012-training-70-410-r2/2?autostart=1
Traceback (most recent call last):
  File "youtube_dl\extractor\generic.pyo", line 1309, in _real_extract
  File "youtube_dl\compat.pyo", line 248, in compat_etree_fromstring
  File "youtube_dl\compat.pyo", line 237, in _XML
  File "xml\etree\ElementTree.pyo", line 1642, in feed
  File "xml\etree\ElementTree.pyo", line 1506, in _raiseerror
ParseError: not well-formed (invalid token): line 21, column 795
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 666, in extract_info
  File "youtube_dl\extractor\common.pyo", line 316, in extract
  File "youtube_dl\extractor\generic.pyo", line 1956, in _real_extract
UnsupportedError: Unsupported URL: https://www.cbtnuggets.com/it-training/microsoft-windows-server-2012-training-70-410-r2/2?autostart=1
```

I've also tried the same page without the "autostart=1" parameter at the end, and the results are:

```
PS C:\Users\Administrator> $url="https://www.cbtnuggets.com/it-training/microsoft-windows-server-2012-training-70-410-r2/2"
PS C:\Users\Administrator> youtube-dl --no-check-certificate --verbose --username $username --password $password --sleep-interval 240 -o $opciones $url
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--no-check-certificate', u'--verbose', u'--username', u'PRIVATE', u'--password', u'PRIVATE', u'--sleep-interval', u'240', u'-o', u'C:/videos/training/%(playlist_title)s/%(autonumber)s - %(title)s.%(ext)s', u'https://www.cbtnuggets.com/it-training/microsoft-windows-server-2012-training-70-410-r2/2']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.03.01
[debug] Python version 2.7.10 - Windows-2012Server-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {}
[generic] 2: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 2: Downloading webpage
[generic] 2: Extracting information
ERROR: Unsupported URL: https://www.cbtnuggets.com/it-training/microsoft-windows-server-2012-training-70-410-r2/2
Traceback (most recent call last):
  File "youtube_dl\extractor\generic.pyo", line 1309, in _real_extract
  File "youtube_dl\compat.pyo", line 248, in compat_etree_fromstring
  File "youtube_dl\compat.pyo", line 237, in _XML
  File "xml\etree\ElementTree.pyo", line 1642, in feed
  File "xml\etree\ElementTree.pyo", line 1506, in _raiseerror
ParseError: not well-formed (invalid token): line 21, column 795
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 666, in extract_info
  File "youtube_dl\extractor\common.pyo", line 316, in extract
  File "youtube_dl\extractor\generic.pyo", line 1956, in _real_extract
UnsupportedError: Unsupported URL: https://www.cbtnuggets.com/it-training/microsoft-windows-server-2012-training-70-410-r2/2
```

(If i'm missing something please let me know and i'll update or modify this!)

Thanks!

**Comment by dstftw** [comment]
cbtnuggets is not supported. Open a new site support request.
