### ISSUE TITLE
ERROR: unable to download video data: HTTP Error 504: Gateway Time-out

### ISSUE THREAD

**Issue by samcoresung** [rg3/youtube-dl#8552]
youtube-dl --verbose http://www.rai.tv/dl/RaiTV/dirette/PublishingBlock-1912dbbf-3f96-44c3-b4cf-523681fbacbc.html?channel=EuroNews
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.rai.tv/dl/RaiTV/dirette/PublishingBlock-1912dbbf-3f96-44c3-b4cf-523681fbacbc.html?channel=EuroNews']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.24
[debug] Python version 2.7.9 - Linux-3.19.0-15-generic-x86_64-with-Ubuntu-15.04-vivid
[debug] exe versions: avconv 11.2-6, avprobe 11.2-6, ffmpeg 2.5.10-0ubuntu0.15.04.1, ffprobe 2.5.10-0ubuntu0.15.04.1, rtmpdump 2.4
[debug] Proxy map: {}
[Rai] 1912dbbf-3f96-44c3-b4cf-523681fbacbc: Downloading webpage
[Rai] 1912dbbf-3f96-44c3-b4cf-523681fbacbc: Downloading JSON metadata
[debug] Invoking downloader on u'http://b2.stream8.rai.it/live/smil:euronews.smil/manifest#live_hds.f4m?auth=daEa7a.dkbPdSbNafajb1cWbocvbeaEd8bg-bwV6A_-c0-JjtxrFo&aifp=V001'
[f4m] Downloading f4m manifest
ERROR: unable to download video data: HTTP Error 504: Gateway Time-out
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1601, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1543, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 342, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/f4m.py", line 289, in real_download
    urlh = self.ydl.urlopen(man_url)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1878, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 504: Gateway Time-out

**Comment by samcoresung** [comment]
ERROR: unable to download video data: HTTP Error 504: Gateway Time-out

**Comment by yan12125** [comment]
Thanks for the report and sorry for the late response. Such videos will be correctly downloaded in the next version.
