### ISSUE TITLE
ERROR: audio conversion failed

### ISSUE THREAD

**Issue by watarumohawk** [rg3/youtube-dl#8558]
I tried to extract audio from a video by running this:

```
youtube-dl -x --audio-format m4a URL
```
And I got an error message. My youtube-dl's version is 2016.02.13

Full error code is:

```
youtube-dl -x --audio-format m4a https://www.youtube.com/hoge
[youtube] mIk4xvaf7CY: Downloading webpage
[youtube] mIk4xvaf7CY: Downloading video info webpage
[youtube] mIk4xvaf7CY: Extracting video information
[download] Destination: hoge.webm
[download] 100% of 4.60MiB in 00:02
[ffmpeg] Destination: hoge.m4a
ERROR: audio conversion failed: [aac @ 0x7fe6e2002a00] The encoder 'aac' is experimental but experimental codecs are not enabled, add '-strict -2' if you want to use it.
```

**Comment by dstftw** [comment]
**Post the full output of youtube-dl when run with `-v`**, i.e. add `-v` flag to your command line, copy the **whole** output and post it in the issue body wrapped in \`\`\` for better formatting. It should look similar to this:
```
$ youtube-dl -v http://www.youtube.com/watch?v=BaW_jenozKcj
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2015.12.06
[debug] Git HEAD: 135392e
[debug] Python version 2.6.6 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
```
**Do not post screenshots of verbose log only plain text is acceptable.**

The output (including the first lines) contains important debugging information. Issues without the full output are often not reproducible and therefore do not get solved in short order, if ever.

**Comment by watarumohawk** [comment]
Sorry for not posting this, here you are.

```
$youtube-dl -v http://www.youtube.com/watch\?v\=BaW_jenozKcj

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.13
[debug] Python version 2.7.5 - Darwin-13.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.8.2, ffprobe 2.8.2
[debug] Proxy map: {}
[youtube] BaW_jenozKc: Downloading webpage
[youtube] BaW_jenozKc: Downloading video info webpage
[youtube] BaW_jenozKc: Extracting video information
[youtube] BaW_jenozKc: Downloading MPD manifest
[debug] Invoking downloader on u'https://r3---sn-ogueln76.googlevideo.com/videoplayback?id=05a5bf8de9e8cca7&itag=137&source=youtube&requiressl=yes&mm=31&pl=24&ms=au&mv=m&mn=sn-ogueln76&nh=IgpwcjA0Lm5ydDE5KgkxMjcuMC4wLjE&ratebypass=yes&mime=video/mp4&gir=yes&clen=2208750&lmt=1387961822987808&dur=9.800&fexp=9409166,9416126,9420452,9422596,9423661,9423662&mt=1455458470&key=dg_yt0&upn=KAwAr4x9tcQ&signature=285515893438B166B39A733A198F4F17F32BE3EA.18C513E570F6C4BDFAE994C17B022A519A45905C&sver=3&ip=220.111.56.73&ipbits=0&expire=1455480249&sparams=ip,ipbits,expire,id,itag,source,requiressl,mm,pl,ms,mv,mn,nh,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: youtube-dl test video ''_ä↭𝕐-BaW_jenozKc.f137.mp4
[download] 100% of 2.11MiB in 00:02
[debug] Invoking downloader on u'https://r3---sn-ogueln76.googlevideo.com/videoplayback?id=05a5bf8de9e8cca7&itag=141&source=youtube&requiressl=yes&mm=31&pl=24&ms=au&mv=m&mn=sn-ogueln76&nh=IgpwcjA0Lm5ydDE5KgkxMjcuMC4wLjE&ratebypass=yes&mime=audio/mp4&gir=yes&clen=315992&lmt=1387961817988214&dur=9.891&fexp=9409166,9416126,9420452,9422596,9423661,9423662&mt=1455458470&key=dg_yt0&upn=KAwAr4x9tcQ&signature=1BAB43DD344CD5F0BEFE005E0C80CF9DCED22DFC.9A496E16F050FA5B496AB42A38F00A43C2291521&sver=3&ip=220.111.56.73&ipbits=0&expire=1455480249&sparams=ip,ipbits,expire,id,itag,source,requiressl,mm,pl,ms,mv,mn,nh,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: youtube-dl test video ''_ä↭𝕐-BaW_jenozKc.f141.m4a
[download] 100% of 308.59KiB in 00:00
[ffmpeg] Merging formats into "youtube-dl test video ''_ä↭𝕐-BaW_jenozKc.mp4"
[debug] ffmpeg command line: ffmpeg -y -i 'file:youtube-dl test video '"'"''"'"'_ä↭𝕐-BaW_jenozKc.f137.mp4' -i 'file:youtube-dl test video '"'"''"'"'_ä↭𝕐-BaW_jenozKc.f141.m4a' -c copy -map 0:v:0 -map 1:a:0 'file:youtube-dl test video '"'"''"'"'_ä↭𝕐-BaW_jenozKc.temp.mp4'
Deleting original file youtube-dl test video ''_ä↭𝕐-BaW_jenozKc.f137.mp4 (pass -k to keep)
Deleting original file youtube-dl test video ''_ä↭𝕐-BaW_jenozKc.f141.m4a (pass -k to keep)
```

**Comment by dstftw** [comment]
There is no error here.

**Comment by dstftw** [comment]
@watarumohawk you must use **your** URL in verbose output not BaW_jenozKcj.

**Comment by watarumohawk** [comment]
@dstftw  ```youtube-dl -v URL``` and ```youtube-dl -v -x URL``` are fine, but ```youtube-dl -v -x --audio-format m4a``` gives me an error.

Here is three results.

```
$ youtube-dl -v https://www.youtube.com/watch\?v\=mIk4xvaf7CY
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=mIk4xvaf7CY']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.13
[debug] Python version 2.7.5 - Darwin-13.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.8.6, ffprobe 2.8.6
[debug] Proxy map: {}
[youtube] mIk4xvaf7CY: Downloading webpage
[youtube] mIk4xvaf7CY: Downloading video info webpage
[youtube] mIk4xvaf7CY: Extracting video information
[youtube] {22} signature length 43.43, html5 player en_US-vflCdE8nM
[youtube] {43} signature length 43.43, html5 player en_US-vflCdE8nM
[youtube] {18} signature length 43.43, html5 player en_US-vflCdE8nM
[youtube] {5} signature length 43.43, html5 player en_US-vflCdE8nM
[youtube] {36} signature length 43.43, html5 player en_US-vflCdE8nM
[youtube] {17} signature length 43.43, html5 player en_US-vflCdE8nM
[youtube] {137} signature length 43.43, html5 player en_US-vflCdE8nM
[youtube] {248} signature length 43.43, html5 player en_US-vflCdE8nM
[youtube] {136} signature length 43.43, html5 player en_US-vflCdE8nM
[youtube] {247} signature length 43.43, html5 player en_US-vflCdE8nM
[youtube] {135} signature length 43.43, html5 player en_US-vflCdE8nM
[youtube] {244} signature length 43.43, html5 player en_US-vflCdE8nM
[youtube] {134} signature length 43.43, html5 player en_US-vflCdE8nM
[youtube] {243} signature length 43.43, html5 player en_US-vflCdE8nM
[youtube] {133} signature length 43.43, html5 player en_US-vflCdE8nM
[youtube] {242} signature length 43.43, html5 player en_US-vflCdE8nM
[youtube] {160} signature length 43.43, html5 player en_US-vflCdE8nM
[youtube] {278} signature length 43.43, html5 player en_US-vflCdE8nM
[youtube] {140} signature length 43.43, html5 player en_US-vflCdE8nM
[youtube] {171} signature length 43.43, html5 player en_US-vflCdE8nM
[youtube] {249} signature length 43.43, html5 player en_US-vflCdE8nM
[youtube] {250} signature length 43.43, html5 player en_US-vflCdE8nM
[youtube] {251} signature length 43.43, html5 player en_US-vflCdE8nM
[debug] Invoking downloader on u'https://r3---sn-oguesnze.googlevideo.com/videoplayback?nh=IgpwcjA0Lm5ydDEwKgkxMjcuMC4wLjE&upn=DGzIVnYgbwE&keepalive=yes&source=youtube&sparams=clen%2Cdur%2Cgcr%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&initcwndbps=2132500&pl=24&gcr=jp&ip=220.111.56.73&lmt=1436811572057701&key=yt6&id=o-AOZx9Bhg2ZH_K5S9jYdgab9qONTwBJV9m8ZYu2uXj0qr&expire=1455655515&gir=yes&mm=31&mn=sn-oguesnze&itag=248&mt=1455633724&mv=m&fexp=9407196%2C9408495%2C9416126%2C9417580%2C9417656%2C9418223%2C9419446%2C9420452%2C9420539%2C9421508%2C9422596%2C9422971%2C9423661%2C9423662%2C9425730%2C9427063%2C9428296&ms=au&sver=3&dur=270.145&requiressl=yes&ipbits=0&clen=61111630&mime=video%2Fwebm&signature=D4D02C0F96724A2EC87563DF708257CF3669E17A.E43D239058F6FF0F49D70A364BDD944EE3E75EC8&ratebypass=yes'
[download] Destination: Hatsune Miku - World Is Mine Meets Metal-mIk4xvaf7CY.f248.webm
[download] 100% of 58.28MiB in 00:33
[debug] Invoking downloader on u'https://r3---sn-oguesnze.googlevideo.com/videoplayback?nh=IgpwcjA0Lm5ydDEwKgkxMjcuMC4wLjE&upn=DGzIVnYgbwE&keepalive=yes&source=youtube&sparams=clen%2Cdur%2Cgcr%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&initcwndbps=2132500&pl=24&gcr=jp&ip=220.111.56.73&lmt=1436811349326783&key=yt6&id=o-AOZx9Bhg2ZH_K5S9jYdgab9qONTwBJV9m8ZYu2uXj0qr&expire=1455655515&gir=yes&mm=31&mn=sn-oguesnze&itag=171&mt=1455633724&mv=m&fexp=9407196%2C9408495%2C9416126%2C9417580%2C9417656%2C9418223%2C9419446%2C9420452%2C9420539%2C9421508%2C9422596%2C9422971%2C9423661%2C9423662%2C9425730%2C9427063%2C9428296&ms=au&sver=3&dur=270.174&requiressl=yes&ipbits=0&clen=4819022&mime=audio%2Fwebm&signature=8E1BB0224918715700D6F05940952A9657BB927B.7893921671749F07DD74AF6AB177B3E13FB33DBA&ratebypass=yes'
[download] Destination: Hatsune Miku - World Is Mine Meets Metal-mIk4xvaf7CY.f171.webm
[download] 100% of 4.60MiB in 00:01
[ffmpeg] Merging formats into "Hatsune Miku - World Is Mine Meets Metal-mIk4xvaf7CY.webm"
[debug] ffmpeg command line: ffmpeg -y -i 'file:Hatsune Miku - World Is Mine Meets Metal-mIk4xvaf7CY.f248.webm' -i 'file:Hatsune Miku - World Is Mine Meets Metal-mIk4xvaf7CY.f171.webm' -c copy -map 0:v:0 -map 1:a:0 'file:Hatsune Miku - World Is Mine Meets Metal-mIk4xvaf7CY.temp.webm'
Deleting original file Hatsune Miku - World Is Mine Meets Metal-mIk4xvaf7CY.f248.webm (pass -k to keep)
Deleting original file Hatsune Miku - World Is Mine Meets Metal-mIk4xvaf7CY.f171.webm (pass -k to keep)
```

```
$ youtube-dl -v -x https://www.youtube.com/watch\?v\=mIk4xvaf7CY
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'-x', u'https://www.youtube.com/watch?v=mIk4xvaf7CY']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.13
[debug] Python version 2.7.5 - Darwin-13.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.8.6, ffprobe 2.8.6
[debug] Proxy map: {}
[youtube] mIk4xvaf7CY: Downloading webpage
[youtube] mIk4xvaf7CY: Downloading video info webpage
[youtube] mIk4xvaf7CY: Extracting video information
[youtube] {22} signature length 43.43, html5 player en_US-vflCdE8nM
[youtube] {43} signature length 43.43, html5 player en_US-vflCdE8nM
[youtube] {18} signature length 43.43, html5 player en_US-vflCdE8nM
[youtube] {5} signature length 43.43, html5 player en_US-vflCdE8nM
[youtube] {36} signature length 43.43, html5 player en_US-vflCdE8nM
[youtube] {17} signature length 43.43, html5 player en_US-vflCdE8nM
[youtube] {137} signature length 43.43, html5 player en_US-vflCdE8nM
[youtube] {248} signature length 43.43, html5 player en_US-vflCdE8nM
[youtube] {136} signature length 43.43, html5 player en_US-vflCdE8nM
[youtube] {247} signature length 43.43, html5 player en_US-vflCdE8nM
[youtube] {135} signature length 43.43, html5 player en_US-vflCdE8nM
[youtube] {244} signature length 43.43, html5 player en_US-vflCdE8nM
[youtube] {134} signature length 43.43, html5 player en_US-vflCdE8nM
[youtube] {243} signature length 43.43, html5 player en_US-vflCdE8nM
[youtube] {133} signature length 43.43, html5 player en_US-vflCdE8nM
[youtube] {242} signature length 43.43, html5 player en_US-vflCdE8nM
[youtube] {160} signature length 43.43, html5 player en_US-vflCdE8nM
[youtube] {278} signature length 43.43, html5 player en_US-vflCdE8nM
[youtube] {140} signature length 43.43, html5 player en_US-vflCdE8nM
[youtube] {171} signature length 43.43, html5 player en_US-vflCdE8nM
[youtube] {249} signature length 43.43, html5 player en_US-vflCdE8nM
[youtube] {250} signature length 43.43, html5 player en_US-vflCdE8nM
[youtube] {251} signature length 43.43, html5 player en_US-vflCdE8nM
[debug] Invoking downloader on u'https://r3---sn-oguesnze.googlevideo.com/videoplayback?requiressl=yes&initcwndbps=2141250&source=youtube&keepalive=yes&lmt=1436811349326783&sparams=clen%2Cdur%2Cgcr%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&ipbits=0&gcr=jp&id=o-AFmGwTr_2I7RKB9r7ctxODAnQwmxfNKJ9Cb68rTpYn3p&mv=m&upn=aLGdKzhRh2Y&mt=1455633873&ms=au&mn=sn-oguesnze&ip=220.111.56.73&mm=31&itag=171&pl=24&gir=yes&expire=1455655663&key=yt6&mime=audio%2Fwebm&fexp=9416126%2C9418200%2C9419451%2C9420452%2C9422342%2C9422596%2C9423455%2C9423661%2C9423662%2C9424135%2C9424814%2C9425423%2C9425731%2C9426949%2C9427108%2C9427173%2C9427667%2C9427796%2C9428702&nh=IgpwcjA0Lm5ydDEwKgkxMjcuMC4wLjE&clen=4819022&dur=270.174&sver=3&signature=2C91D182E291F8359F82DE2EEAC0BF9C62E28F01.424157BC326600844098919F78592F019A398045&ratebypass=yes'
[download] Hatsune Miku - World Is Mine Meets Metal-mIk4xvaf7CY.webm has already been downloaded
[download] 100% of 62.88MiB
[debug] ffmpeg command line: ffprobe -show_streams 'file:Hatsune Miku - World Is Mine Meets Metal-mIk4xvaf7CY.webm'
[ffmpeg] Destination: Hatsune Miku - World Is Mine Meets Metal-mIk4xvaf7CY.ogg
[debug] ffmpeg command line: ffmpeg -y -i 'file:Hatsune Miku - World Is Mine Meets Metal-mIk4xvaf7CY.webm' -vn -acodec copy 'file:Hatsune Miku - World Is Mine Meets Metal-mIk4xvaf7CY.ogg'
Deleting original file Hatsune Miku - World Is Mine Meets Metal-mIk4xvaf7CY.webm (pass -k to keep)
```

```
$ youtube-dl -v -x --audio-format m4a https://www.youtube.com/watch\?v\=mIk4xvaf7CY
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'-x', u'--audio-format', u'm4a', u'https://www.youtube.com/watch?v=mIk4xvaf7CY']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.13
[debug] Python version 2.7.5 - Darwin-13.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.8.6, ffprobe 2.8.6
[debug] Proxy map: {}
[youtube] mIk4xvaf7CY: Downloading webpage
[youtube] mIk4xvaf7CY: Downloading video info webpage
[youtube] mIk4xvaf7CY: Extracting video information
[youtube] {22} signature length 43.43, html5 player en_US-vflCdE8nM
[youtube] {43} signature length 43.43, html5 player en_US-vflCdE8nM
[youtube] {18} signature length 43.43, html5 player en_US-vflCdE8nM
[youtube] {5} signature length 43.43, html5 player en_US-vflCdE8nM
[youtube] {36} signature length 43.43, html5 player en_US-vflCdE8nM
[youtube] {17} signature length 43.43, html5 player en_US-vflCdE8nM
[youtube] {137} signature length 43.43, html5 player en_US-vflCdE8nM
[youtube] {248} signature length 43.43, html5 player en_US-vflCdE8nM
[youtube] {136} signature length 43.43, html5 player en_US-vflCdE8nM
[youtube] {247} signature length 43.43, html5 player en_US-vflCdE8nM
[youtube] {135} signature length 43.43, html5 player en_US-vflCdE8nM
[youtube] {244} signature length 43.43, html5 player en_US-vflCdE8nM
[youtube] {134} signature length 43.43, html5 player en_US-vflCdE8nM
[youtube] {243} signature length 43.43, html5 player en_US-vflCdE8nM
[youtube] {133} signature length 43.43, html5 player en_US-vflCdE8nM
[youtube] {242} signature length 43.43, html5 player en_US-vflCdE8nM
[youtube] {160} signature length 43.43, html5 player en_US-vflCdE8nM
[youtube] {278} signature length 43.43, html5 player en_US-vflCdE8nM
[youtube] {140} signature length 43.43, html5 player en_US-vflCdE8nM
[youtube] {171} signature length 43.43, html5 player en_US-vflCdE8nM
[youtube] {249} signature length 43.43, html5 player en_US-vflCdE8nM
[youtube] {250} signature length 43.43, html5 player en_US-vflCdE8nM
[youtube] {251} signature length 43.43, html5 player en_US-vflCdE8nM
[debug] Invoking downloader on u'https://r3---sn-oguesnze.googlevideo.com/videoplayback?expire=1455655716&mv=m&gcr=jp&ms=au&id=o-ALwoX6-t-wOcenNHxSXISfz1nCTkkEg5RJx5IKSGR9Ls&mn=sn-oguesnze&pl=24&source=youtube&mm=31&ip=220.111.56.73&mime=audio%2Fwebm&requiressl=yes&sver=3&fexp=9416126%2C9417203%2C9417368%2C9420452%2C9422596%2C9423039%2C9423661%2C9423662%2C9424861%2C9427261%2C9427391%2C9427667%2C9427916%2C9428424&itag=171&clen=4819022&ipbits=0&key=yt6&upn=488bD-ooU5w&keepalive=yes&nh=IgpwcjAyLm5ydDE5KgkxMjcuMC4wLjE&dur=270.174&initcwndbps=2160000&mt=1455634023&lmt=1436811349326783&sparams=clen%2Cdur%2Cgcr%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&gir=yes&signature=6932B6F723E4C4119B240FE972146E37AB761E68.297FDF38724CD0AFCAD0D7FD285E17E68C248918&ratebypass=yes'
[download] Destination: Hatsune Miku - World Is Mine Meets Metal-mIk4xvaf7CY.webm
[download] 100% of 4.60MiB in 00:06
[debug] ffmpeg command line: ffprobe -show_streams 'file:Hatsune Miku - World Is Mine Meets Metal-mIk4xvaf7CY.webm'
[ffmpeg] Destination: Hatsune Miku - World Is Mine Meets Metal-mIk4xvaf7CY.m4a
[debug] ffmpeg command line: ffmpeg -y -i 'file:Hatsune Miku - World Is Mine Meets Metal-mIk4xvaf7CY.webm' -vn -acodec aac -q:a 5 -bsf:a aac_adtstoasc 'file:Hatsune Miku - World Is Mine Meets Metal-mIk4xvaf7CY.m4a'
ERROR: audio conversion failed: [aac @ 0x7f9cba01c400] The encoder 'aac' is experimental but experimental codecs are not enabled, add '-strict -2' if you want to use it.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1738, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 280, in run
    'audio conversion failed: ' + e.msg)
PostProcessingError
```

**Comment by jacksonedmonds** [comment]
Bit of an old thread, but hey...
@watarumohawk This isn't a youtube-dl bug, rather ffmpeg doesn't support m4a (ie aac) conversion out of the box as it is a non-free format. You can compile ffmpeg yourself and enable libfdk_aac using --enable-libfdk-aac: https://trac.ffmpeg.org/wiki/Encode/AAC
While there isn't an official build of ffmpeg with lbfdk_aac, if you do some googling you may be able to find a build you can use (ffmpeg Hi for example: https://sourceforge.net/projects/ffmpeg-hi/).

**Comment by watarumohawk** [comment]
@jacksonedmonds 

Ah, I see. Thank you very much for your reply and urls.
