### ISSUE TITLE
WDR Maus stopped working

### ISSUE THREAD

**Issue by gedsic** [rg3/youtube-dl#8562]
Downloading the current "Sendung mit der Maus" does not work. Verbose output:

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://www.wdrmaus.de/aktuelle-sendung/index.php5', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.13
[debug] Python version 2.7.9 - Linux-4.0.0-kali1-amd64-x86_64-with-Kali-2.0-sana
[debug] exe versions: none
[debug] Proxy map: {}
[WDRMaus] aktuelle-sendung: Downloading webpage
ERROR: Unable to extract parameters; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 666, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 315, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/wdr.py", line 275, in _real_extract
    r'<a href="\?startVideo=1&amp;([^"]+)"', webpage, 'parameters')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 619, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 610, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract parameters; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by mrMoe** [comment]
Upgraded minutes ago 
still not working
`youtube-dl --verbose http://www.wdrmaus.de/aktuelle-sendung/index.php5   
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.wdrmaus.de/aktuelle-sendung/index.php5']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.04.13
[debug] Python version 3.5.1 - Linux-4.5.0-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 3.0.1, ffprobe 3.0.1, rtmpdump 2.4
[debug] Proxy map: {}
[WDRMaus] aktuelle-sendung: Downloading webpage
ERROR: Unable to extract parameters; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/moe/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 671, in extract_info
    ie_result = ie.extract(url)
  File "/home/moe/bin/youtube-dl/youtube_dl/extractor/common.py", line 341, in extract
    return self._real_extract(url)
  File "/home/moe/bin/youtube-dl/youtube_dl/extractor/wdr.py", line 275, in _real_extract
    r'<a href="\?startVideo=1&amp;([^"]+)"', webpage, 'parameters')
  File "/home/moe/bin/youtube-dl/youtube_dl/extractor/common.py", line 653, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/home/moe/bin/youtube-dl/youtube_dl/extractor/common.py", line 644, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract parameters; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
`
