### ISSUE TITLE
xtube: new video page

### ISSUE THREAD

**Issue by paulguy** [rg3/youtube-dl#8565]
XTube have completely redune their video page it looks like, so youtube-dl doesn't work.

here's the error I get:
```
$ youtube-dl --verbose http://www.xtube.com/watch.php?v=[redacted]
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.xtube.com/watch.php?v=[redacted]
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.10
[debug] Python version 2.7.11 - Linux-4.1.15-gentoo-r1-x86_64-Intel-R-_Core-TM-_i7-2600_CPU_@_3.40GHz-with-gentoo-2.2
[debug] exe versions: ffmpeg 2.8.5, ffprobe 2.8.5, rtmpdump 2.4
[debug] Proxy map: {}
[XTube] OhSVg-G770-: Downloading webpage
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 666, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/common.py", line 315, in extract
    return self._real_extract(url)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/xtube.py", line 40, in _real_extract
    r'<p class="title">([^<]+)', webpage, 'title')
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/common.py", line 619, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/common.py", line 610, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

Not very important since it's failing so early.  I imagine it's completely broken.

I left out the video ID for the sake of my own privacy but it should be similarly broken on every video.

**Comment by dstftw** [comment]
>I left out the video ID for the sake of my own privacy 

Actually, you've failed to left out all the occurrences.

**Comment by paulguy** [comment]
ahhhhh, I see.  hehe, whoops. :p
