### ISSUE TITLE
orf tvthek 404 Not Found

### ISSUE THREAD

**Issue by fx3O2** [rg3/youtube-dl#8580]
```
Downloads [master] youtube-dl http://tvthek.orf.at/program/Tirol-heute/70023/Tirol-heute/11959842 -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://tvthek.orf.at/program/Tirol-heute/70023/Tirol-heute/11959842', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.13
[debug] Python version 3.5.1 - Linux-4.4.1-2-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 2.8.6, ffprobe 2.8.6
[debug] Proxy map: {}
[orf:tvthek] 70023: Downloading webpage
[orf:tvthek] 11963326: Testing for geoblocking
[orf:tvthek] 11963328: Testing for geoblocking
[orf:tvthek] 11963329: Testing for geoblocking
[orf:tvthek] 11963330: Testing for geoblocking
[orf:tvthek] 11963331: Testing for geoblocking
[orf:tvthek] 11963332: Testing for geoblocking
[orf:tvthek] 11963333: Testing for geoblocking
[orf:tvthek] 11963334: Testing for geoblocking
[orf:tvthek] 11963335: Testing for geoblocking
[download] Downloading playlist: 70023
[orf:tvthek] playlist 70023: Collected 9 video ids (downloading 9 of them)
[download] Downloading video 1 of 9
[debug] Invoking downloader on 'http://apasfpd.apa.at/cms-worldwide/online/0a898f032781839119e889f6cb4263e2/1455638822/2016-02-12_1900_tl_28_TIROL-HEUTE--GS_Signation__11959842__o__0001818840__s11963326___on_THiRes_18595319P_19003216P_Q8C.mp4'
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 1624, in process_info
    success = dl(filename, info_dict)
  File "/usr/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 1566, in dl
    return fd.download(name, info)
  File "/usr/lib/python3.5/site-packages/youtube_dl/downloader/common.py", line 343, in download
    return self.real_download(filename, info_dict)
  File "/usr/lib/python3.5/site-packages/youtube_dl/downloader/http.py", line 58, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 1905, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 471, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 581, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 509, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 443, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 589, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

```

The following works (not best quality):
```
youtube-dl -f "progressive-Q6A-hoch" http://tvthek.orf.at/program/Tirol-heute/70023/Tirol-heute/11959842
```

```
Downloads [master] youtube-dl --version
2016.02.13
```

**Comment by fx3O2** [comment]
@dstftw It is only checking for formats, it won't choose a download by default. I've to manually choose the quality.
