### ISSUE TITLE
[FOX] [ThePlatform] No video formats found

### ISSUE THREAD

**Issue by mvbattista** [rg3/youtube-dl#8584]
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://www.fox.com/watch/621471811871/7684301568', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out None, pref UTF-8
[debug] youtube-dl version 2016.02.04
[debug] Python version 2.7.10 - Darwin-15.3.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.8.1, ffprobe 2.8.1
[debug] Proxy map: {}
[FOX] 621471811871: Downloading webpage
[ThePlatform] dPon_8bWu8VZ: Downloading SMIL data
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/theplatform.py", line 37, in _extract_theplatform_smil
    for n in meta.findall(_x('.//smil:ref'))
StopIteration
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 666, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 313, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/theplatform.py", line 237, in _real_extract
    formats, subtitles = self._extract_theplatform_smil(smil_url, video_id)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/theplatform.py", line 49, in _extract_theplatform_smil
    transform_rtmp_url=lambda streamer, src: (streamer, 'mp4:' + src))
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1263, in _parse_smil_formats
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 826, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

**Comment by remitamine** [comment]
this episode requires authontication.
free episode works fine:
```
python2 __main__.py -F http://www.fox.com/watch/601986627905/7684301568
[FOX] 601986627905: Downloading webpage
[ThePlatform] sCakxu_COaQ0: Downloading SMIL data
[ThePlatform] sCakxu_COaQ0: Checking video URL
[ThePlatform] sCakxu_COaQ0: Checking video URL
[ThePlatform] sCakxu_COaQ0: Checking video URL
[ThePlatform] sCakxu_COaQ0: Checking video URL
[ThePlatform] sCakxu_COaQ0: Checking video URL
[ThePlatform] sCakxu_COaQ0: Checking video URL
[ThePlatform] sCakxu_COaQ0: Checking video URL
[ThePlatform] sCakxu_COaQ0: Checking video URL
[ThePlatform] sCakxu_COaQ0: Downloading JSON metadata
WARNING: ar subtitles not available for 601986627905
WARNING: arME subtitles not available for 601986627905
WARNING: enUS subtitles not available for 601986627905
WARNING: en-US subtitles not available for 601986627905
[info] Available formats for 601986627905:
format code  extension  resolution note
http-249     mp4        402x226     249k 
http-321     mp4        402x226     321k 
http-395     mp4        480x270     395k 
http-595     mp4        480x270     595k 
http-896     mp4        640x360     896k 
http-1427    mp4        1024x576   1427k 
http-1928    mp4        1280x720   1928k 
http-2630    mp4        1280x720   2630k  (best)
```
