### ISSUE TITLE
[letv]ERROR: unable to download video

### ISSUE THREAD

**Issue by gam2046** [rg3/youtube-dl#8588]
```
[c:\~]$ youtube-dl -v http://www.letv.com/ptv/vplay/2068007.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.letv.com/ptv/vplay/2068007.html']
[debug] Encodings: locale cp936, fs mbcs, out None, pref cp936
[debug] youtube-dl version 2016.02.13
[debug] Python version 2.7.11 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-77197-gdf2ce13, ffprobe N-77197-gdf2ce13
[debug] Proxy map: {}
[Letv] 2068007: Downloading webpage
[Letv] 2068007: Downloading playJson data
[Letv] 2068007: Download JSON metadata for format 350
[Letv] 2068007: Downloading m3u8 information for format 350
[Letv] 2068007: Download JSON metadata for format 1000
[Letv] 2068007: Downloading m3u8 information for format 1000
[Letv] 2068007: Download JSON metadata for format 1300
[Letv] 2068007: Downloading m3u8 information for format 1300
[Letv] 2068007: Download JSON metadata for format 720p
[Letv] 2068007: Downloading m3u8 information for format 720p
[Letv] 2068007: Download JSON metadata for format 1080p
[Letv] 2068007: Downloading m3u8 information for format 1080p
There are many character like the following :
g1ODYwLnJwJnFvcz0zJmVuY2tpdD0mbTN2PTEmdG9rZW49JnZpZD0mbGl2ZWlkPSZzdGF0aW9uPSZhcHBfbmFtZT0mYXBwX3Zlcj0mZmNoZWNrPTAmcGFudG09JnBhbnVpZD0mcGFudG9rZW49DQojRVhULVgtRU5ETElTVA0K' -c copy -f mp4 -bsf:a aac_adtstoasc 'file:幸福选择题02-2068007.mp4.part'
ERROR: unable to download video
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 1692, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "c:\python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 677, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "c:\python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 722, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "c:\python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 1362, in process_video_result
    self.process_info(new_info)
  File "c:\python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 1629, in process_info
    raise UnavailableVideoError(err)
UnavailableVideoError: [Error 206] 
```

**Comment by yan12125** [comment]
It's a known bug and the current workaround is using ```--hls-prefer-native```. For example:
```
youtube-dl -v --hls-prefer-native http://www.letv.com/ptv/vplay/2068007.html
```

**Comment by gam2046** [comment]
Thanks, I tried. but there are some thing wrong with the video. Video is not smooth, lack of frame, the picture is missing, not continuous.
