### ISSUE TITLE
Vimeo Error: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by marteaurouge** [rg3/youtube-dl#8592]
The last 24 hours i encountered this error:
`ERROR: unable to download video data: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)>`

**Comment by dstftw** [comment]
**Post the full output of youtube-dl when run with `-v`**, i.e. add `-v` flag to your command line, copy the **whole** output and post it in the issue body wrapped in \`\`\` for better formatting. It should look similar to this:
```
$ youtube-dl -v http://www.youtube.com/watch?v=BaW_jenozKcj
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2015.12.06
[debug] Git HEAD: 135392e
[debug] Python version 2.6.6 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
```
**Do not post screenshots of verbose log only plain text is acceptable.**

The output (including the first lines) contains important debugging information. Issues without the full output are often not reproducible and therefore do not get solved in short order, if ever.

**Comment by marteaurouge** [comment]
$ youtube-dl -v https://vimeo.com/155086124

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://vimeo.com/155086124']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.13
[debug] Python version 2.7.9 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.3
[debug] exe versions: rtmpdump 2.4
[debug] Proxy map: {}
[vimeo] 155086124: Downloading webpage
[vimeo] 155086124: Extracting information
[vimeo] 155086124: Downloading webpage
[vimeo] 155086124: Downloading JSON metadata
[vimeo] 155086124: Downloading m3u8 information
[debug] Invoking downloader on u'https://skyfiregcs-a.akamaihd.net/exp=1455783189~acl=%2A%2F480598923.mp4%2A~hmac=56930b0defd943c8cf877cc6b4feff1f59656abb7a67bdfc94c3c8c534309806/2tierchgci/vimeo-prod-skyfire-std-us/01/1017/6/155086124/480598923.mp4'
ERROR: unable to download video data: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1624, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1566, in dl
    return fd.download(name, info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/common.py", line 343, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/http.py", line 58, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1905, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/utils.py", line 830, in https_open
    req, **kwargs)
  File "/usr/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)>

```

**Comment by marteaurouge** [comment]
using --no-check-certificate fix the problem
