### ISSUE TITLE
Failure downloading specific YouTube video

### ISSUE THREAD

**Issue by dundua** [rg3/youtube-dl#8595]
youtube-dl fails to download this specific video: https://www.youtube.com/watch?v=b2SaWtyVAaE
It is able to obtain the list of available formats, but is not able to actually download the video
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'--ignore-errors', u'--no-continue', u'--no-overwrites', u'--keep-video', u'--no-post-overwrites', u'--download-archive', u'archive.txt', u'--write-description', u'--write-info-json', u'--write-annotations', u'--write-thumbnail', u'--all-subs', u'--output', u'%(uploader)s (%(uploader_id)s)/%(id)s/%(title)s - %(upload_date)s.%(ext)s', u'-f', u'bestvideo[ext=mp4]+bestaudio[ext=m4a]', u'https://www.youtube.com/watch?v=b2SaWtyVAaE']
[debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8
[debug] youtube-dl version 2016.02.13
[debug] Python version 2.7.9 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.3
[debug] exe versions: avconv 11.4-6, avprobe 11.4-6
[debug] Proxy map: {}
[youtube] b2SaWtyVAaE: Downloading webpage
[youtube] b2SaWtyVAaE: Downloading video info webpage
[youtube] b2SaWtyVAaE: Extracting video information
WARNING: video doesn't have subtitles
[youtube] b2SaWtyVAaE: Searching for annotations.
[youtube] {22} signature length 46.44, html5 player en_US-vflGk0Qy7
[youtube] {43} signature length 46.42, html5 player en_US-vflGk0Qy7
[youtube] {18} signature length 46.44, html5 player en_US-vflGk0Qy7
[youtube] {5} signature length 46.44, html5 player en_US-vflGk0Qy7
[youtube] {36} signature length 46.44, html5 player en_US-vflGk0Qy7
[youtube] {17} signature length 46.44, html5 player en_US-vflGk0Qy7
[youtube] {136} signature length 46.44, html5 player en_US-vflGk0Qy7
[youtube] {247} signature length 46.44, html5 player en_US-vflGk0Qy7
[youtube] {298} signature length 46.44, html5 player en_US-vflGk0Qy7
[youtube] {302} signature length 46.44, html5 player en_US-vflGk0Qy7
[youtube] {135} signature length 46.44, html5 player en_US-vflGk0Qy7
[youtube] {244} signature length 46.44, html5 player en_US-vflGk0Qy7
[youtube] {134} signature length 46.44, html5 player en_US-vflGk0Qy7
[youtube] {243} signature length 46.44, html5 player en_US-vflGk0Qy7
[youtube] {133} signature length 46.44, html5 player en_US-vflGk0Qy7
[youtube] {242} signature length 46.44, html5 player en_US-vflGk0Qy7
[youtube] {160} signature length 46.44, html5 player en_US-vflGk0Qy7
[youtube] {278} signature length 46.44, html5 player en_US-vflGk0Qy7
[youtube] {140} signature length 46.44, html5 player en_US-vflGk0Qy7
[youtube] {171} signature length 46.44, html5 player en_US-vflGk0Qy7
[youtube] {249} signature length 46.44, html5 player en_US-vflGk0Qy7
[youtube] {250} signature length 46.44, html5 player en_US-vflGk0Qy7
[youtube] {251} signature length 46.44, html5 player en_US-vflGk0Qy7
ERROR: requested format not available
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 677, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 722, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1354, in process_video_result
    expected=True)
ExtractorError: requested format not available



[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'--ignore-errors', u'-s', u'-F', u'https://www.youtube.com/watch?v=b2SaWtyVAaE']
[debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8
[debug] youtube-dl version 2016.02.13
[debug] Python version 2.7.9 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.3
[debug] exe versions: avconv 11.4-6, avprobe 11.4-6
[debug] Proxy map: {}
[youtube] b2SaWtyVAaE: Downloading webpage
[youtube] b2SaWtyVAaE: Downloading video info webpage
[youtube] b2SaWtyVAaE: Extracting video information
[youtube] {22} signature length 46.44, html5 player en_US-vflGk0Qy7
[youtube] {43} signature length 46.44, html5 player en_US-vflGk0Qy7
[youtube] {18} signature length 46.44, html5 player en_US-vflGk0Qy7
[youtube] {5} signature length 46.44, html5 player en_US-vflGk0Qy7
[youtube] {36} signature length 46.44, html5 player en_US-vflGk0Qy7
[youtube] {17} signature length 46.44, html5 player en_US-vflGk0Qy7
[youtube] {136} signature length 46.44, html5 player en_US-vflGk0Qy7
[youtube] {247} signature length 46.44, html5 player en_US-vflGk0Qy7
[youtube] {298} signature length 46.44, html5 player en_US-vflGk0Qy7
[youtube] {302} signature length 46.44, html5 player en_US-vflGk0Qy7
[youtube] {135} signature length 46.44, html5 player en_US-vflGk0Qy7
[youtube] {244} signature length 46.44, html5 player en_US-vflGk0Qy7
[youtube] {134} signature length 46.44, html5 player en_US-vflGk0Qy7
[youtube] {243} signature length 46.44, html5 player en_US-vflGk0Qy7
[youtube] {133} signature length 46.44, html5 player en_US-vflGk0Qy7
[youtube] {242} signature length 46.44, html5 player en_US-vflGk0Qy7
[youtube] {160} signature length 46.44, html5 player en_US-vflGk0Qy7
[youtube] {278} signature length 46.44, html5 player en_US-vflGk0Qy7
[youtube] {140} signature length 46.44, html5 player en_US-vflGk0Qy7
[youtube] {171} signature length 46.44, html5 player en_US-vflGk0Qy7
[youtube] {249} signature length 46.44, html5 player en_US-vflGk0Qy7
[youtube] {250} signature length 46.44, html5 player en_US-vflGk0Qy7
[youtube] {251} signature length 46.44, html5 player en_US-vflGk0Qy7
[info] Available formats for b2SaWtyVAaE:
format code  extension  resolution note
249          webm       audio only DASH audio   60k , opus @ 50k, 21.42MiB
250          webm       audio only DASH audio   78k , opus @ 70k, 27.04MiB
171          webm       audio only DASH audio  106k , vorbis@128k, 35.44MiB
251          webm       audio only DASH audio  130k , opus @160k, 47.34MiB
140          mp4        audio only DASH audio  131k , m4a_dash container, mp4a.40.2@128k, 55.80MiB
278          webm       256x144    144p  118k , webm container, vp9, 15fps, video only, 45.38MiB
160          mp4        256x144    144p  125k , avc1.4d400c, 30fps, video only, 48.39MiB
242          webm       426x240    240p  238k , vp9, 30fps, video only, 79.87MiB
133          mp4        426x240    240p  259k , avc1.4d4015, 30fps, video only, 107.71MiB
243          webm       640x360    360p  433k , vp9, 30fps, video only, 152.19MiB
134          mp4        640x360    360p  458k , avc1.4d401e, 30fps, video only, 118.88MiB
244          webm       854x480    480p  790k , vp9, 30fps, video only, 274.65MiB
135          mp4        854x480    480p  947k , avc1.4d401f, 30fps, video only, 255.06MiB
247          webm       1280x720   720p 1571k , vp9, 30fps, video only, 579.59MiB
136          mp4        1280x720   720p 1812k , avc1.4d401f, 30fps, video only, 520.92MiB
302          webm       1280x720   720p60 2557k , vp9, 60fps, video only, 989.31MiB
298          mp4        1280x720   720p60 2978k , avc1.4d4020, 60fps, video only, 905.61MiB
36           3gp        320x?      small , mp4v.20.3,  mp4a.40.2
17           3gp        176x144    small , mp4v.20.3,  mp4a.40.2@ 24k
5            flv        400x240    small , h263, mp3  @ 64k
43           webm       640x360    medium , vp8.0,  vorbis@128k
18           mp4        640x360    medium , avc1.42001E,  mp4a.40.2@ 96k
22           mp4        1280x720   hd720 , avc1.64001F,  mp4a.40.2@192k (best)
```

**Comment by dstftw** [comment]
audio ext in this case is `mp4` not `m4a` due to #8511.
