### ISSUE TITLE
[Pornhub] [NSFW] Authentication doesn't work, can't download private videos

### ISSUE THREAD

**Issue by vxbinaca** [rg3/youtube-dl#8603]
```youtube-dl -n -v http://www.pornhub.com/view_video.php?viewkey=308291908```

```
[debug] System config: []
[debug] User config: [u'--download-archive', u'~/.ytdlarchive', u'--retries', u'100', u'--no-overwrites', u'--call-home', u'--continue', u'--write-info-json', u'--write-description', u'--write-thumbnail', u'--write-annotations', u'--all-subs', u'--sub-format', u'srt', u'--convert-subs', u'srt', u'--write-sub', u'--add-metadata', u'-f', u'bestvideo+bestaudio/best', u'--merge-output-format', u'mkv', u'--embed-subs']
[debug] Command-line args: [u'-n', u'-v', u'http://www.pornhub.com/view_video.php?viewkey=308291908']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.13
[debug] Python version 2.7.10 - Linux-4.2.0-27-generic-x86_64-with-Ubuntu-15.10-wily
[debug] exe versions: ffmpeg 2.7.6-0ubuntu0.15.10.1, ffprobe 2.7.6-0ubuntu0.15.10.1, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Public IP address: 76.101.221.232
[PornHub] 308291908: Downloading webpage
ERROR: 308291908: PornHub said: Sorry, but this video is private. You must be friends with poppiseed to view this video.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 666, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 315, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/pornhub.py", line 68, in _real_extract
    expected=True, video_id=video_id)
ExtractorError: 308291908: PornHub said: Sorry, but this video is private. You must be friends with poppiseed to view this video.
```

Okay so this is a private friends-only video, so it's difficult to reproduce the problem but I'll reproduce part of my ~/.netrc:

```
machine pornhub 
 login [REDACTED]@yahoo.com 
 password [REDACTED]
```

Is it something in my netrc that's a problem or does the module for pornhub not have authentication working? It does download public videos using auth but doesn't appear to log in.

**Comment by yan12125** [comment]
Login is not implemented yet. You may want to try ```--cookies```.

**Comment by vxbinaca** [comment]
```--cookies``` is appropriate solution. Closing.
