### ISSUE TITLE
Unable to download arte.tv magazine

### ISSUE THREAD

**Issue by MartinDelille** [rg3/youtube-dl#8613]
I'm unable to download arte+7 episode:

```
$ youtube-dl http://www.arte.tv/magazine/trepalium/fr/episode-0406-replay-trepalium -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://www.arte.tv/magazine/trepalium/fr/episode-0406-replay-trepalium', u'-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.13
[debug] Python version 2.7.9 - Darwin-13.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.8.5, ffprobe 2.8.5
[debug] Proxy map: {}
[generic] episode-0406-replay-trepalium: Requesting header
WARNING: Falling back on generic information extractor.
[generic] episode-0406-replay-trepalium: Downloading webpage
[generic] episode-0406-replay-trepalium: Extracting information
ERROR: Unsupported URL: http://www.arte.tv/magazine/trepalium/fr/episode-0406-replay-trepalium
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1308, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 248, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=etree.TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 237, in _XML
    parser.feed(text)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: mismatched tag: line 94, column 2
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 666, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 315, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1945, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.arte.tv/magazine/trepalium/fr/episode-0406-replay-trepalium
```

**Comment by yan12125** [comment]
This page gives 404 not found. Do you have other examples?
