### ISSUE TITLE
ERROR: audio conversion failed

### ISSUE THREAD

**Issue by deplexor** [rg3/youtube-dl#8615]
I've tried downloading a couple of songs and converting to MP3. It used to work, but now it doesn't, so maybe it's something to do with the new update? (This only started happening after I updated).

```
root@whisky:~# youtube-dl -x https://www.youtube.com/watch?v=ytQ5CYE1VZw        [youtube] ytQ5CYE1VZw: Downloading webpage
[youtube] ytQ5CYE1VZw: Downloading video info webpage
[youtube] ytQ5CYE1VZw: Extracting video information
[download] Eminem - Till I Collapse [HD]-ytQ5CYE1VZw.webm has already been downloaded
[download] 100% of 5.08MiB
[ffmpeg] Destination: Eminem - Till I Collapse [HD]-ytQ5CYE1VZw.mp3
WARNING: Your copy of avconv is outdated, update avconv to version 10-0 or newer if you encounter any errors.
ERROR: audio conversion failed: Decoder (codec id 0) not found for input stream #0:0
```

Different song:
```
root@whisky:~# youtube-dl -x https://www.youtube.com/watch?v=_Yhyp-_hX2s
[youtube] _Yhyp-_hX2s: Downloading webpage
[youtube] _Yhyp-_hX2s: Downloading video info webpage
[youtube] _Yhyp-_hX2s: Extracting video information
[youtube] _Yhyp-_hX2s: Downloading MPD manifest
[download] Destination: Eminem - Lose Yourself [HD]-_Yhyp-_hX2s.webm
[download] 100% of 5.20MiB in 00:00
[ffmpeg] Destination: Eminem - Lose Yourself [HD]-_Yhyp-_hX2s.mp3
WARNING: Your copy of avconv is outdated, update avconv to version 10-0 or newer if you encounter any errors.
ERROR: audio conversion failed: Decoder (codec id 0) not found for input stream #0:0

```

Debian 7 OS

**Comment by dstftw** [comment]
**Post the full output of youtube-dl when run with `-v`**, i.e. **add** `-v` flag to **your command line**, copy the **whole** output and post it in the issue body wrapped in \`\`\` for better formatting. It should look similar to this:
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2015.12.06
[debug] Git HEAD: 135392e
[debug] Python version 2.6.6 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
```
**Do not post screenshots of verbose log only plain text is acceptable.**

The output (including the first lines) contains important debugging information. Issues without the full output are often not reproducible and therefore do not get solved in short order, if ever.

**Comment by deplexor** [comment]
```
root@whisky:~# youtube-dl -v -x https://www.youtube.com/watch?v=ytQ5CYE1VZw
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'-x', u'https://www.youtube.com/watch?v=ytQ5                                                                             CYE1VZw']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.13
[debug] Python version 2.7.3 - Linux-3.2.0-4-amd64-x86_64-with-debian-7.9
[debug] exe versions: avconv 0.8.17-6, avprobe 0.8.17-6, ffmpeg 0.8.17-6, ffprob                                                                             e 0.8.17-6
[debug] Proxy map: {}
[youtube] ytQ5CYE1VZw: Downloading webpage
[youtube] ytQ5CYE1VZw: Downloading video info webpage
[youtube] ytQ5CYE1VZw: Extracting video information
[youtube] {22} signature length 40.41, html5 player en_US-vfldIygzk
[youtube] {43} signature length 40.41, html5 player en_US-vfldIygzk
[youtube] {18} signature length 40.41, html5 player en_US-vfldIygzk
[youtube] {5} signature length 40.41, html5 player en_US-vfldIygzk
[youtube] {36} signature length 40.41, html5 player en_US-vfldIygzk
[youtube] {17} signature length 40.41, html5 player en_US-vfldIygzk
[youtube] {137} signature length 40.39, html5 player en_US-vfldIygzk
[youtube] ytQ5CYE1VZw: Downloading player https://s.ytimg.com/yts/jsbin/player-e                                                                             n_US-vfldIygzk/base.js
[youtube] {248} signature length 40.41, html5 player en_US-vfldIygzk
[youtube] {136} signature length 40.41, html5 player en_US-vfldIygzk
[youtube] {247} signature length 40.41, html5 player en_US-vfldIygzk
[youtube] {135} signature length 40.41, html5 player en_US-vfldIygzk
[youtube] {244} signature length 40.41, html5 player en_US-vfldIygzk
[youtube] {134} signature length 40.41, html5 player en_US-vfldIygzk
[youtube] {243} signature length 40.41, html5 player en_US-vfldIygzk
[youtube] {133} signature length 40.41, html5 player en_US-vfldIygzk
[youtube] {242} signature length 40.41, html5 player en_US-vfldIygzk
[youtube] {160} signature length 40.41, html5 player en_US-vfldIygzk
[youtube] {278} signature length 40.41, html5 player en_US-vfldIygzk
[youtube] {140} signature length 40.41, html5 player en_US-vfldIygzk
[youtube] {171} signature length 40.41, html5 player en_US-vfldIygzk
[youtube] {249} signature length 40.41, html5 player en_US-vfldIygzk
[youtube] {250} signature length 40.41, html5 player en_US-vfldIygzk
[youtube] {251} signature length 40.41, html5 player en_US-vfldIygzk
[debug] Invoking downloader on u'https://r16---sn-aiglln7r.googlevideo.com/video                                                                             playback?id=o-AAclxJ_h6tLgdj6Zyvu6yULtehE23ER7HmS80M7abz5j&mv=u&upn=M9olFFwZWwA&                                                                             mt=1455972565&ms=au&mn=sn-aiglln7r&ip=178.62.66.55&mm=31&itag=251&pl=23&gir=yes&                                                                             key=yt6&mime=audio%2Fwebm&fexp=9405185%2C9410706%2C9416126%2C9418643%2C9420452%2                                                                             C9422596%2C9423661%2C9423662%2C9424489%2C9425396%2C9425549%2C9426651%2C9427126%2                                                                             C9428029%2C9428247%2C9428396%2C9429130%2C9429518&nh=IgpwcjAzLmxocjI2KgkxMjcuMC4w                                                                             LjE&clen=5328709&dur=298.541&sver=3&requiressl=yes&source=youtube&keepalive=yes&                                                                             lmt=1449635269960664&sparams=clen%2Cdur%2Cgcr%2Cgir%2Cid%2Cip%2Cipbits%2Citag%2C                                                                             keepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpl%2Crequiressl%2Csource%2Cupn                                                                             %2Cexpire&ipbits=0&expire=1455994219&gcr=gb&signature=32BF5084259E24781DAB34C3F0                                                                             590A616C5A4D04.A3A011E84C0F597494D023345C943C4B2370B124&ratebypass=yes'
[download] Destination: Eminem - Till I Collapse [HD]-ytQ5CYE1VZw.webm
[download] 100% of 5.08MiB in 00:00
[debug] avconv command line: avprobe -show_streams 'file:Eminem - Till I Collaps                                                                             e [HD]-ytQ5CYE1VZw.webm'
[ffmpeg] Destination: Eminem - Till I Collapse [HD]-ytQ5CYE1VZw.mp3
WARNING: Your copy of avconv is outdated, update avconv to version 10-0 or newer                                                                              if you encounter any errors.
[debug] ffmpeg command line: avconv -y -i 'file:Eminem - Till I Collapse [HD]-yt                                                                             Q5CYE1VZw.webm' -vn -acodec libmp3lame -q:a 5 'file:Eminem - Till I Collapse [HD                                                                             ]-ytQ5CYE1VZw.mp3'
ERROR: audio conversion failed: Decoder (codec id 0) not found for input stream                                                                              #0:0
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 17                                                                             38, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/postprocessor/ffmpeg.p                                                                             y", line 280, in run
    'audio conversion failed: ' + e.msg)
PostProcessingError
```
