### ISSUE TITLE
error using rai extractor downloading url from rai.tv

### ISSUE THREAD

**Issue by bedinsky** [rg3/youtube-dl#8617]
youtube-dl --verbose http://www.rai.tv/dl/RaiTV/programmi/media/ContentItem-52b804ad-d360-490a-a071-4d3ed30d3895.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.rai.tv/dl/RaiTV/programmi/media/ContentItem-52b804ad-d360-490a-a071-4d3ed30d3895.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.13
[debug] Python version 2.7.10 - Darwin-14.5.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.8.5, ffprobe 2.8.5, rtmpdump 2.4
[debug] Proxy map: {}
[RaiTV] 52b804ad-d360-490a-a071-4d3ed30d3895: Downloading video JSON
[RaiTV] 52b804ad-d360-490a-a071-4d3ed30d3895: Downloading XML
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 411, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 401, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1692, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 666, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 315, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/rai.py", line 111, in _real_extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 490, in _download_xml
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 248, in compat_etree_fromstring
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 238, in _XML
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1654, in close
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: syntax error: line 1, column 0

**Comment by yan12125** [comment]
Thanks for the report and sorry for the delay. Rai will be fixed in the next version.
