### ISSUE TITLE
Error: Audio conversion failed: Unknown encoder 'lib3lame'

### ISSUE THREAD

**Issue by deplexor** [rg3/youtube-dl#8618]
```
root@whisky:~# youtube-dl -v -x --audio-format mp3 --prefer-ffmpeg https://www.youtube.com/watch?v=ytQ5CYE1VZw
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'-x', u'--audio-format', u'mp3', u'--prefer-ffmpeg', u'https://www.youtube.com/watch?v=ytQ5CYE1VZw']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.13
[debug] Python version 2.7.3 - Linux-3.2.0-4-amd64-x86_64-with-debian-7.9
[debug] exe versions: avconv 10.7, avprobe 10.7, ffmpeg 3.0, ffprobe 3.0
[debug] Proxy map: {}
[youtube] ytQ5CYE1VZw: Downloading webpage
[youtube] ytQ5CYE1VZw: Downloading video info webpage
[youtube] ytQ5CYE1VZw: Extracting video information
[youtube] {22} signature length 40.41, html5 player en_US-vfldIygzk
[youtube] {43} signature length 40.41, html5 player en_US-vfldIygzk
[youtube] {18} signature length 40.41, html5 player en_US-vfldIygzk
[youtube] {5} signature length 40.41, html5 player en_US-vfldIygzk
[youtube] {36} signature length 40.41, html5 player en_US-vfldIygzk
[youtube] {17} signature length 40.41, html5 player en_US-vfldIygzk
[youtube] {137} signature length 40.41, html5 player en_US-vfldIygzk
[youtube] {248} signature length 40.41, html5 player en_US-vfldIygzk
[youtube] {136} signature length 40.41, html5 player en_US-vfldIygzk
[youtube] {247} signature length 40.41, html5 player en_US-vfldIygzk
[youtube] {135} signature length 40.41, html5 player en_US-vfldIygzk
[youtube] {244} signature length 40.41, html5 player en_US-vfldIygzk
[youtube] {134} signature length 40.41, html5 player en_US-vfldIygzk
[youtube] {243} signature length 40.41, html5 player en_US-vfldIygzk
[youtube] {133} signature length 40.41, html5 player en_US-vfldIygzk
[youtube] {242} signature length 40.41, html5 player en_US-vfldIygzk
[youtube] {160} signature length 40.41, html5 player en_US-vfldIygzk
[youtube] {278} signature length 40.41, html5 player en_US-vfldIygzk
[youtube] {140} signature length 40.41, html5 player en_US-vfldIygzk
[youtube] {171} signature length 40.41, html5 player en_US-vfldIygzk
[youtube] {249} signature length 40.41, html5 player en_US-vfldIygzk
[youtube] {250} signature length 40.41, html5 player en_US-vfldIygzk
[youtube] {251} signature length 40.41, html5 player en_US-vfldIygzk
[debug] Invoking downloader on u'https://r16---sn-aiglln7r.googlevideo.com/videoplayback?lmt=1449635269960664&source=youtube&upn=jKBEDpe8ViQ&fexp=9408206%2C9413141%2C9413516%2C9415948%2C9416126%2C9418199%2C9419444%2C9420452%2C9421512%2C9422596%2C9423661%2C9423662%2C9426656%2C9427126%2C9428470%2C9429201&keepalive=yes&nh=IgpwcjAzLmxocjI2KgkxMjcuMC4wLjE&key=yt6&gir=yes&mime=audio%2Fwebm&itag=251&clen=5328709&gcr=gb&dur=298.541&ipbits=0&sver=3&expire=1455997939&requiressl=yes&ip=178.62.66.55&mv=u&mt=1455975987&ms=au&mn=sn-aiglln7r&mm=31&pl=23&id=o-AIdXsY1Y0rLNMDbk63tEJV7pm2957g3f5VobujMbKWQ8&sparams=clen%2Cdur%2Cgcr%2Cgir%2Cid%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&signature=302C0D15080BAA4E748215A6FD72CABB52DC206D.8C1F6589037CBB5CF30E4D441E43EC2CF5CB4751&ratebypass=yes'
[download] Destination: Eminem - Till I Collapse [HD]-ytQ5CYE1VZw.webm
[download] 100% of 5.08MiB in 00:00
[debug] ffmpeg command line: ffprobe -show_streams 'file:Eminem - Till I Collapse [HD]-ytQ5CYE1VZw.webm'
[ffmpeg] Destination: Eminem - Till I Collapse [HD]-ytQ5CYE1VZw.mp3
[debug] ffmpeg command line: ffmpeg -y -i 'file:Eminem - Till I Collapse [HD]-ytQ5CYE1VZw.webm' -vn -acodec libmp3lame -q:a 5 'file:Eminem - Till I Collapse [HD]-ytQ5CYE1VZw.mp3'
ERROR: audio conversion failed: Unknown encoder 'libmp3lame'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1738, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/postprocessor/ffmpeg.py", line 280, in run
    'audio conversion failed: ' + e.msg)
PostProcessingError
```

After updating ffmpeg I get this. Same result without the --prefer-ffmpeg flag :/
Also, I did try an apt-get install libavcodec-extra-53

**Comment by yan12125** [comment]
Could you run the following three commands and post their results:
```
youtube-dl -v -f bestaudio --prefer-ffmpeg "https://www.youtube.com/watch?v=ytQ5CYE1VZw"
ffmpeg -y -i 'file:Eminem - Till I Collapse [HD]-ytQ5CYE1VZw.webm' -vn -acodec libmp3lame -q:a 5 'file:Eminem - Till I Collapse [HD]-ytQ5CYE1VZw.mp3'
ffmpeg -formats
```

> After updating ffmpeg I get this.

Most likely it's a bug of Debian. Report it to Debian guys.

**Comment by yan12125** [comment]
Closing as "Unknown encoder 'lib3lame'" is most likely a problem of ffmpeg but not youtube-dl, and no response from the original author for a long time.
