### ISSUE TITLE
[bbc] Failed to parse JSON error

### ISSUE THREAD

**Issue by surgeio** [rg3/youtube-dl#8626]
[debug] System config: []  
[debug] User config: []  
[debug] Command-line args: [u'--proxy', u'85.13.224.105:3128', u'--verbose', u'http://www.bbc.co.uk/iplayer/episode/b071fyfr']  
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8  
[debug] youtube-dl version 2016.02.13  
[debug] Python version 2.7.4 - Linux-2.6.32-5-openvz-686-i686-with-debian-6.0.10  
[debug] exe versions: avconv 0.8.6-6, avprobe 0.8.6-6, ffmpeg 0.8.6-6, ffprobe 0.8.6-6, rtmpdump 2.3  
[debug] Proxy map: {u'http': u'85.13.224.105:3128', u'https': u'85.13.224.105:3128'}  
[bbc.co.uk] b071fyfr: Downloading video page  
[bbc.co.uk] b071fyfr: Downloading playlist JSON  
ERROR: b071fyfr: Failed to parse JSON  (caused by ValueError('No JSON object could be decoded',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.  
Traceback (most recent call last):  
  File "/home/steve/personal/python/youtube-dl.py/youtube_dl/extractor/common.py", line 509, in _parse_json  
    return json.loads(json_string)  
  File "/usr/local/lib/python2.7/json/__init__.py", line 338, in loads  
    return _default_decoder.decode(s)  
  File "/usr/local/lib/python2.7/json/decoder.py", line 365, in decode  
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())  
  File "/usr/local/lib/python2.7/json/decoder.py", line 383, in raw_decode  
    raise ValueError("No JSON object could be decoded")  
ValueError: No JSON object could be decoded  
Traceback (most recent call last):  
  File "/home/steve/personal/python/youtube-dl.py/youtube_dl/YoutubeDL.py", line 666, in extract_info  
    ie_result = ie.extract(url)  
  File "/home/steve/personal/python/youtube-dl.py/youtube_dl/extractor/common.py", line 315, in extract  
    return self._real_extract(url)  
  File "/home/steve/personal/python/youtube-dl.py/youtube_dl/extractor/bbc.py", line 507, in _real_extract  
    programme_id, title, description, duration, formats, subtitles = self._download_playlist(group_id)  
  File "/home/steve/personal/python/youtube-dl.py/youtube_dl/extractor/bbc.py", line 396, in _download_playlist  
    playlist_id, 'Downloading playlist JSON')  
  File "/home/steve/personal/python/youtube-dl.py/youtube_dl/extractor/common.py", line 503, in _download_json  
    json_string, video_id, transform_source=transform_source, fatal=fatal)  
  File "/home/steve/personal/python/youtube-dl.py/youtube_dl/extractor/common.py", line 513, in _parse_json  
    raise ExtractorError(errmsg, cause=ve)  
ExtractorError: b071fyfr: Failed to parse JSON  (caused by ValueError('No JSON object could be decoded',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
Your proxy transfers all requests to TellyPass.com.

**Comment by surgeio** [comment]
On Sun, Feb 21, 2016 at 01:56:44AM -0800, Sergey M. wrote:
> Your proxy transfers all requests to TellyPass.com.

I'm not sure why that should stop the download from happening, but even 
if it should, then perhaps a better error message would be helpful? 
Something like "your proxy is doing bad things, change the proxy".

Steven

**Comment by dstftw** [comment]
There is no notion of a *bad thing*. You direct request to proxy, proxy returns you an HTML. It's impossible to guess whether it's bad or not.
