### ISSUE TITLE
[VK] No video formats found

### ISSUE THREAD

**Issue by kotofond** [rg3/youtube-dl#8646]
:~$ youtube-dl --verbose http://vk.com/video-110305615_171782105
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://vk.com/video-110305615_171782105']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.22
[debug] Python version 3.4.2 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.2
[debug] exe versions: avconv 11.4-6, avprobe 11.4-6, rtmpdump 2.4
[debug] Proxy map: {}
[vk] -110305615_171782105: Downloading webpage
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/webapps/getvideo/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 666, in extract_info
    ie_result = ie.extract(url)
  File "/webapps/getvideo/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 316, in extract
    return self._real_extract(url)
  File "/webapps/getvideo/lib/python3.4/site-packages/youtube_dl/extractor/vk.py", line 307, in _real_extract
    self._sort_formats(formats)
  File "/webapps/getvideo/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 829, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by skubi** [comment]
Still reproducible. Please, reopen.

```
% youtube-dl --verbose http://vk.com/video-22781583_456239892
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://vk.com/video-22781583_456239892']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.12.22
[debug] Python version 2.7.13 - Darwin-16.3.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.2.2, ffprobe 3.2.2
[debug] Proxy map: {}
[vk] -22781583_456239892: Downloading webpage
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 358, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/vk.py", line 419, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 925, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by yan12125** [comment]
Apparently they changed it again.

**Comment by skubi** [comment]
@dstftw could you please elaborate why this issue was closed again after being reopened?

**Comment by Hrxn** [comment]
Same for me..

Video in initial comment works, but this does not: http://vk.com/video-22781583_456239892
```
Microsoft Windows [Version 10.0.14393]

C:\Users\Hrxn>youtube-dl -v --ignore-config "http://vk.com/video-22781583_456239892"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', '--ignore-config', 'http://vk.com/video-22781583_456239892']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.12.22
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-82889-g54931fd, ffprobe N-82889-g54931fd
[debug] Proxy map: {}
[vk] -22781583_456239892: Downloading webpage
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptqqgo4yk\build\youtube_dl\YoutubeDL.py", line 694, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptqqgo4yk\build\youtube_dl\extractor\common.py", line 358, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptqqgo4yk\build\youtube_dl\extractor\vk.py", line 419, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmptqqgo4yk\build\youtube_dl\extractor\common.py", line 925, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


C:\Users\Hrxn>
```

Same result when using Python with youtube-dl binary.

Works in Chrome, is pretty slow, but this could  be my connection at the moment.

**Comment by yan12125** [comment]
There are some commits fixing VK-related problems on master: https://github.com/rg3/youtube-dl/commits/master. Seems dstftw forgot to add issue numbers to commit messages so this issue is not referenced. The fix will be included in the next release. If you're in urge, clone this repository and see https://github.com/rg3/youtube-dl#developer-instructions for how to run it.

Here's an example log of the current master:
```
$ youtube-dl --verbose http://vk.com/video-22781583_456239892
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://vk.com/video-22781583_456239892']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.12.22
[debug] Git HEAD: 424ed37ec
[debug] Python version 3.5.2 - Linux-4.9.0-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 3.2.2, ffprobe 3.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[vk] -22781583_456239892: Downloading webpage
[debug] Invoking downloader on 'https://cs635602.vk.me/7/u1506483/videos/91848a0409.1080.mp4?extra=kgLvZuqrhZNNM3-9YmwkkMt8a-oS74lv9_D_B3hwizBycN-wsD7UyZyz9DIVIULSdZbAMnkcKyxpQ1gxaIQgxxZ05nh3OVJRwhCLrUiLijf5IuOt7zXN3Jba26wQ9BEJ'
[download] Destination: [Стрим] Экшн года 2016. Марафон-456239892.mp4
[download]   0.0% of 6.87GiB at 154.89KiB/s ETA 12:54:55^CException ignored in: <_io.FileIO name='[Стрим] Экшн года 2016. Марафон-456239892.mp4.part' mode='wb' closefd=True>
ResourceWarning: unclosed file <_io.BufferedWriter name='[Стрим] Экшн года 2016. Марафон-456239892.mp4.part'>

ERROR: Interrupted by user
```

**Comment by Hrxn** [comment]
Can confirm..
```
C:\Users\Hrxn>Python "D:\Src\youtube-dl-master\youtube_dl\__main__.py" -v --ignore-config --restrict-filenames "http://vk.com/video-22781583_456239892"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', '--ignore-config', '--restrict-filenames', 'http://vk.com/video-22781583_456239892']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.12.22
[debug] Python version 3.5.2 - Windows-10-10.0.14393-SP0
[debug] exe versions: ffmpeg N-82889-g54931fd, ffprobe N-82889-g54931fd
[debug] Proxy map: {}
[vk] -22781583_456239892: Downloading webpage
[debug] Invoking downloader on 'https://cs635602.vk.me/7/u1506483/videos/204fb795d2.1080.mp4?extra=bN7Ao0d-ILuqnOXIgDNtbnO9rjctLk4bsGuEZ_Zns5f9WPKz4yGu7eTzd4rRMgBcQpugfwrW3cRj1lZFwc2nt11YuAAuX5VMTp8qNO9Lj_0XN7DPrylTjAI4CSA'
[download] Destination: 2016.-456239892.mp4
[download]   0.3% of 6.87GiB at 697.85KiB/s ETA 02:51:29
ERROR: Interrupted by user

C:\Users\Hrxn>
```

Issue has been closed because it is fixed 😄

**Comment by skubi** [comment]
@yan12125 thanks a lot for the clarification!
