### ISSUE TITLE
Issue with safaribooksonline books

### ISSUE THREAD

**Issue by gokudarkaqw** [rg3/youtube-dl#8648]
Hi guys, 

I saw that this tool is compatible with safaribooksonline. I wonder if it is just with videos or can we extract books as html webpage ?

Because i'm unable to do it :(

Example below:

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'--username', u'PRIVATE', u'http://search.safaribooksonline.com/book/operating-systems-and-server-administration/9781785289538/1dot-getting-started-with-nginx/ch01lvl1sec08_html']
Type account password and press [Return]:
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.22
[debug] Python version 2.6.6 - Linux-2.6.32-573.12.1.el6.x86_64-x86_64-with-centos-6.7-Final
[debug] exe versions: none
[debug] Proxy map: {}
[generic] ch01lvl1sec08_html: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ch01lvl1sec08_html: Downloading webpage
[generic] ch01lvl1sec08_html: Extracting information
ERROR: Unsupported URL: http://search.safaribooksonline.com/book/operating-systems-and-server-administration/9781785289538/1dot-getting-started-with-nginx/ch01lvl1sec08_html
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1308, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 248, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=etree.TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 237, in _XML
    parser.feed(text)
  File "/usr/lib64/python2.6/xml/etree/ElementTree.py", line 1245, in feed
    self._parser.Parse(data, 0)
ExpatError: not well-formed (invalid token): line 15, column 70
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 666, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 316, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1950, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://search.safaribooksonline.com/book/operating-systems-and-server-administration/9781785289538/1dot-getting-started-with-nginx/ch01lvl1sec08_html

Cheers.

**Comment by dstftw** [comment]
This is out of scope of youtube-dl.

**Comment by gokudarkaqw** [comment]
Waw ok. Hello to you too. Sorry to ask a question like that ....
