### ISSUE TITLE
Vimeo - Unable to extract info section (caused by RegexNotFoundError)

### ISSUE THREAD

**Issue by sboisson** [rg3/youtube-dl#8651]
With command: `youtube-dl --verbose https://vimeo.com/156448904` on OS X 

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'https://vimeo.com/156448904']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.12.10.3
[debug] Git HEAD: 80dbeba
[debug] Python version 2.7.10 - Darwin-15.3.0-x86_64-i386-64bit
[debug] exe versions: avconv 11.4, avprobe 11.4, ffmpeg 2.8, ffprobe 2.8, rtmpdump 2.4
[debug] Proxy map: {}
[vimeo] 156448904: Downloading webpage
[vimeo] 156448904: Extracting information
ERROR: Unable to extract info section (caused by RegexNotFoundError(u'Unable to extract \x1b[0;34minfo section\x1b[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/youtube_dl/extractor/vimeo.py", line 263, in _real_extract
    flags=re.DOTALL)
  File "/usr/local/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 484, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract info section; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 554, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 242, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python2.7/site-packages/youtube_dl/extractor/vimeo.py", line 274, in _real_extract
    cause=e)
ExtractorError: Unable to extract info section (caused by RegexNotFoundError(u'Unable to extract \x1b[0;34minfo section\x1b[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

**Comment by sboisson** [comment]
Seems to work on version from master (2016.02.22)

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.
