### ISSUE TITLE
ZDF mediathek download fails with certificate error

### ISSUE THREAD

**Issue by lorenzhs** [rg3/youtube-dl#8665]
```
%  youtube-dl --verbose http://www.zdf.de/ZDFmediathek#/beitrag/video/2649598/NEO-MAGAZIN-ROYALE-vom-25022016
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.zdf.de/ZDFmediathek#/beitrag/video/2649598/NEO-MAGAZIN-ROYALE-vom-25022016']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.22
[debug] Python version 2.7.11+ - Linux-4.3.0-1-amd64-x86_64-with-debian-stretch-sid
[debug] exe versions: avconv 2.8.6-1, avprobe 2.8.6-1, ffmpeg 2.8.6-1, ffprobe 2.8.6-1, rtmpdump 2.4
[debug] Proxy map: {}
[ZDF] 2649598: Downloading video info
[ZDF] 2649598: Downloading SMIL file
[ZDF] 2649598: Downloading f4m manifest
[ZDF] 2649598: Downloading m3u8 information
[ZDF] 2649598: Downloading m3u8 information
Traceback (most recent call last):
  File "/usr/bin/youtube-dl", line 9, in <module>
    load_entry_point('youtube-dl==2016.2.22', 'console_scripts', 'youtube-dl')()
  File "/usr/lib/python2.7/dist-packages/youtube_dl/__init__.py", line 411, in main
    _real_main(argv)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/__init__.py", line 401, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1692, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 666, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 316, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/zdf.py", line 194, in _real_extract
    return self.extract_from_xml_url(video_id, xml_url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/zdf.py", line 141, in extract_from_xml_url
    video_url, video_id, 'mp4', m3u8_id=format_id, fatal=False))
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 1031, in _extract_m3u8_formats
    fatal=fatal)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 375, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 355, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1905, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/utils.py", line 831, in https_open
    req, **kwargs)
  File "/usr/lib/python2.7/urllib2.py", line 1192, in do_open
    h.request(req.get_method(), req.get_selector(), req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1278, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python2.7/ssl.py", line 352, in wrap_socket
    _context=self)
  File "/usr/lib/python2.7/ssl.py", line 579, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 816, in do_handshake
    match_hostname(self.getpeercert(), self.server_hostname)
  File "/usr/lib/python2.7/ssl.py", line 271, in match_hostname
    % (hostname, ', '.join(map(repr, dnsnames))))
ssl.CertificateError: hostname u'zdf-hdios-none-i.zdf.de' doesn't match either of 'a248.e.akamai.net', '*.akamaihd.net', '*.akamaihd-staging.net', '*.akamaized.net', '*.akamaized-staging.net'
```

not sure if this is an issue with the ZDF mediathek or youtube-dl, but the video plays fine in the browser.

**Comment by Argon-** [comment]
Same for me and it looks like a problem of the extractor, going by the error.

**Comment by jaimeMF** [comment]
It will be fixed in the next version, thanks for the report.

**Comment by lorenzhs** [comment]
Thank you very much! That was quick :)
