### ISSUE TITLE
[Youtube] Fails to merge video

### ISSUE THREAD

**Issue by vxbinaca** [rg3/youtube-dl#8666]
```
youtube-dl -v olGC0rmGndg
```
```
[debug] System config: []
[debug] User config: [u'--download-archive', u'~/.ytdlarchive', u'--retries', u'100', u'--no-overwrites', u'--call-home', u'--continue', u'--write-info-json', u'--write-description', u'--write-thumbnail', u'--write-annotations', u'--all-subs', u'--sub-format', u'srt', u'--convert-subs', u'srt', u'--write-sub', u'--add-metadata', u'-f', u'bestvideo+bestaudio/best', u'--merge-output-format', u'mp4', u'--embed-subs', u'--prefer-ffmpeg', u'--embed-thumbnail']
[debug] Command-line args: [u'-v', u'olGC0rmGndg']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.22
[debug] Python version 2.7.10 - Linux-4.2.0-30-generic-x86_64-with-Ubuntu-15.10-wily
[debug] exe versions: ffmpeg 2.7.6-0ubuntu0.15.10.1, ffprobe 2.7.6-0ubuntu0.15.10.1, rtmpdump 2.4
[debug] Proxy map: {}
[debug] Public IP address: 76.101.221.232
[youtube] olGC0rmGndg: Downloading webpage
[youtube] olGC0rmGndg: Downloading video info webpage
[youtube] olGC0rmGndg: Extracting video information
WARNING: video doesn't have subtitles
[youtube] olGC0rmGndg: Searching for annotations.
[youtube] olGC0rmGndg: Downloading MPD manifest
[info] Video description is already present
[info] Video annotations are already present
[info] Video description metadata is already present
[youtube] olGC0rmGndg: Thumbnail is already present
[debug] Invoking downloader on u'https://r1---sn-o097znlk.googlevideo.com/videoplayback?id=a25182d2b9869dd8&itag=135&source=youtube&requiressl=yes&mn=sn-o097znlk&mm=31&mv=m&ms=au&nh=IgpwcjAyLnBhbzAzKgkxMjcuMC4wLjE&pl=16&ratebypass=yes&mime=video/mp4&gir=yes&clen=6894589&lmt=1403006066490455&dur=186.220&mt=1456449794&key=dg_yt0&upn=z9-PIriulzU&signature=36574E801873C623EAB1739C58B4BDA177997526.65778A2332C8848FF98C7A10AD80609F24EC085B&sver=3&fexp=9407473,9416126,9420452,9422596,9423660,9423662,9426665,9427119,9427319,9427903,9428660,9428703,9428946,9429885&ip=76.101.221.232&ipbits=0&expire=1456471508&sparams=ip,ipbits,expire,id,itag,source,requiressl,mn,mm,mv,ms,nh,pl,ratebypass,mime,gir,clen,lmt,dur'
[download] Let's Play Plumbers Don't Wear Ties - I Want The Hollywood Ending!!-olGC0rmGndg.f135.mp4 has already been downloaded
[download] 100% of 6.58MiB
[debug] Invoking downloader on u'https://r1---sn-o097znlk.googlevideo.com/videoplayback?initcwndbps=438750&expire=1456471508&mime=audio%2Fwebm&gir=yes&nh=IgpwcjAyLnBhbzAzKgkxMjcuMC4wLjE&itag=251&ipbits=0&source=youtube&clen=4403445&sver=3&upn=1Cky1WFgflo&lmt=1408717970136019&mt=1456449794&pl=16&mv=m&id=o-AIinQq5zEcnD9RweEeL_5wPc9UuIDdGQshciIr_vwaFh&ms=au&signature=73A7A26FDE1408C462CE98BFD5B7762051D031A6.3345411D1DF7BF0E93A2F232EC0D1F1788046570&key=yt6&ip=76.101.221.232&keepalive=yes&mm=31&mn=sn-o097znlk&fexp=9407473%2C9416126%2C9420452%2C9422596%2C9423660%2C9423662%2C9426665%2C9427119%2C9427319%2C9427903%2C9428660%2C9428703%2C9428946%2C9429885&dur=186.261&sparams=clen%2Cdur%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&requiressl=yes&ratebypass=yes'
[download] Let's Play Plumbers Don't Wear Ties - I Want The Hollywood Ending!!-olGC0rmGndg.f251.webm has already been downloaded
[download] 100% of 4.20MiB
[ffmpeg] Merging formats into "Let's Play Plumbers Don't Wear Ties - I Want The Hollywood Ending!!-olGC0rmGndg.mp4"
[debug] ffmpeg command line: ffmpeg -y -i 'file:Let'"'"'s Play Plumbers Don'"'"'t Wear Ties - I Want The Hollywood Ending!!-olGC0rmGndg.f135.mp4' -i 'file:Let'"'"'s Play Plumbers Don'"'"'t Wear Ties - I Want The Hollywood Ending!!-olGC0rmGndg.f251.webm' -c copy -map 0:v:0 -map 1:a:0 'file:Let'"'"'s Play Plumbers Don'"'"'t Wear Ties - I Want The Hollywood Ending!!-olGC0rmGndg.temp.mp4'
ERROR: Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1738, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/postprocessor/ffmpeg.py", line 411, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/postprocessor/ffmpeg.py", line 155, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
FFmpegPostProcessorError
```

**Comment by yan12125** [comment]
In your config file:
```
u'--merge-output-format', u'mp4'
```
In this case audio is webm and video is mp4. The two formats can't be merged into a single mp4. Remove ```--merge-output-format mp4``` from your configuraion file and try again.
