### ISSUE TITLE
[SiteSupport Request] cinemassacre.com

### ISSUE THREAD

**Issue by AhmedKamal20** [rg3/youtube-dl#8688]
**$ youtube-dl -v http://cinemassacre.com/2007/10/28/from-duck-till-dawn/ --prefer-avconv**
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://cinemassacre.com/2007/10/28/from-duck-till-dawn/', u'--prefer-avconv']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.27
[debug] Python version 2.7.6 - Linux-3.13.0-80-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 11.3-6, avprobe 11.3-6, ffmpeg N-76138-g7b4367d, ffprobe N-76138-g7b4367d, rtmpdump 2.4
[debug] Proxy map: {}
[Cinemassacre] from-duck-till-dawn: Downloading webpage
[ScreenwaveMedia] Cinemassacre-302: Downloading player webpage
[ScreenwaveMedia] Cinemassacre-302: Downloading playerconfig webpage
[ScreenwaveMedia] Cinemassacre-302: Downloading m3u8 information
[debug] Invoking downloader on u'http://174.127.103.127/vod/smil:Cinemassacre-302.smil/Cinemassacre-302__high.mp4_chunk.m3u8?nimblesessionid=1625425'
[download] Destination: From Dusk Till Dawn (1996) History of Horror-Cinemassacre-302.mp4
[debug] avconv command line: avconv -y -headers 'Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
Accept-Language: en-us,en;q=0.5
Accept-Encoding: gzip, deflate
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/44.0 (Chrome)
' -i 'http://174.127.103.127/vod/smil:Cinemassacre-302.smil/Cinemassacre-302__high.mp4_chunk.m3u8?nimblesessionid=1625425' -c copy -f mp4 -bsf:a aac_adtstoasc 'file:From Dusk Till Dawn (1996) History of Horror-Cinemassacre-302.mp4.part'
avconv version 11.3-6:11.3-1~trusty, Copyright (c) 2000-2014 the Libav developers
  built on Apr 13 2015 22:25:55 with gcc 4.8 (Ubuntu 4.8.2-19ubuntu1)
[mpegts @ 0xf732c0] Estimating duration from bitrate, this may be inaccurate
Input #0, hls,applehttp, from 'http://174.127.103.127/vod/smil:Cinemassacre-302.smil/Cinemassacre-302__high.mp4_chunk.m3u8?nimblesessionid=1625425':
  Duration: 00:02:46.89, start: 0.000000, bitrate: N/A
  Program 0 
    Metadata:
      variant_bitrate : 0
    Stream #0.0: Video: h264 (Constrained Baseline), yuv420p, 464x352, 29.97 fps, 90k tbn, 59.94 tbc
    Stream #0.1: Audio: aac, 44100 Hz, stereo, fltp, 74 kb/s
Output #0, mp4, to 'file:From Dusk Till Dawn (1996) History of Horror-Cinemassacre-302.mp4.part':
  Metadata:
    encoder         : Lavf56.1.0
    Stream #0.0: Video: libx264, yuv420p, 464x352, q=2-31, 90k tbn, 90k tbc
    Stream #0.1: Audio: libvo_aacenc, 44100 Hz, stereo, 74 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press ctrl-c to stop encoding
HTTP error 403 Forbidden.0 size=     250kB time=2.50 bitrate= 817.2kbits/s    
frame=   90 fps= 41 q=-1.0 Lsize=     276kB time=2.97 bitrate= 760.8kbits/s    
video:250kB audio:23kB other streams:0kB global headers:0kB muxing overhead: 1.071448%
[avconv] 282429 bytes
[download] 100% of 275.81KiB
```

**$ youtube-dl -v http://cinemassacre.com/2007/10/28/from-duck-till-dawn/ --prefer-ffmpeg**
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://cinemassacre.com/2007/10/28/from-duck-till-dawn/', u'--prefer-ffmpeg']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.27
[debug] Python version 2.7.6 - Linux-3.13.0-80-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 11.3-6, avprobe 11.3-6, ffmpeg N-76138-g7b4367d, ffprobe N-76138-g7b4367d, rtmpdump 2.4
[debug] Proxy map: {}
[Cinemassacre] from-duck-till-dawn: Downloading webpage
[ScreenwaveMedia] Cinemassacre-302: Downloading player webpage
[ScreenwaveMedia] Cinemassacre-302: Downloading playerconfig webpage
[ScreenwaveMedia] Cinemassacre-302: Downloading m3u8 information
[debug] Invoking downloader on u'http://206.217.201.111/vod/smil:Cinemassacre-302.smil/Cinemassacre-302__high.mp4_chunk.m3u8?nimblesessionid=1588892'
[download] Destination: From Dusk Till Dawn (1996) History of Horror-Cinemassacre-302.mp4
[debug] ffmpeg command line: ffmpeg -y -headers 'Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
Accept-Language: en-us,en;q=0.5
Accept-Encoding: gzip, deflate
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/44.0 (Chrome)
' -i 'http://206.217.201.111/vod/smil:Cinemassacre-302.smil/Cinemassacre-302__high.mp4_chunk.m3u8?nimblesessionid=1588892' -c copy -f mp4 -bsf:a aac_adtstoasc 'file:From Dusk Till Dawn (1996) History of Horror-Cinemassacre-302.mp4.part'
ffmpeg version N-76138-g7b4367d Copyright (c) 2000-2015 the FFmpeg developers
  built with gcc 4.8 (Ubuntu 4.8.4-2ubuntu1~14.04)
  configuration: --disable-yasm
  libavutil      55.  4.100 / 55.  4.100
  libavcodec     57.  7.100 / 57.  7.100
  libavformat    57.  8.102 / 57.  8.102
  libavdevice    57.  0.100 / 57.  0.100
  libavfilter     6. 12.100 /  6. 12.100
  libswscale      4.  0.100 /  4.  0.100
  libswresample   2.  0.100 /  2.  0.100
Input #0, hls,applehttp, from 'http://206.217.201.111/vod/smil:Cinemassacre-302.smil/Cinemassacre-302__high.mp4_chunk.m3u8?nimblesessionid=1588892':
  Duration: 00:02:46.89, start: 0.000000, bitrate: 0 kb/s
  Program 0 
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: h264 (Constrained Baseline) ([27][0][0][0] / 0x001B), yuv420p(tv, smpte170m/smpte170m/bt709), 464x352, 29.97 fps, 29.97 tbr, 90k tbn, 59.94 tbc
    Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp, 82 kb/s
[mp4 @ 0x2731ea0] Codec for stream 0 does not use global headers but container format requires global headers
[mp4 @ 0x2731ea0] Codec for stream 1 does not use global headers but container format requires global headers
Output #0, mp4, to 'file:From Dusk Till Dawn (1996) History of Horror-Cinemassacre-302.mp4.part':
  Metadata:
    encoder         : Lavf57.8.102
    Stream #0:0: Video: h264 ([33][0][0][0] / 0x0021), yuv420p, 464x352, q=2-31, 29.97 fps, 29.97 tbr, 90k tbn, 90k tbc
    Stream #0:1: Audio: aac ([64][0][0][0] / 0x0040), 44100 Hz, stereo, 82 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
[http @ 0x269d640] HTTP error 403 Forbiddentime=00:00:02.11 bitrate= 824.7kbits/s    
[hls,applehttp @ 0x2695580] Failed to open segment of playlist 0
[http @ 0x269f560] HTTP error 403 Forbidden
[hls,applehttp @ 0x2695580] Failed to open segment of playlist 0
[http @ 0x269f360] HTTP error 403 Forbidden
[hls,applehttp @ 0x2695580] Failed to open segment of playlist 0
[http @ 0x269f560] HTTP error 403 Forbidden
[hls,applehttp @ 0x2695580] Failed to open segment of playlist 0
[http @ 0x269f360] HTTP error 403 Forbidden
[hls,applehttp @ 0x2695580] Failed to open segment of playlist 0
[http @ 0x269f560] HTTP error 403 Forbidden
[hls,applehttp @ 0x2695580] Failed to open segment of playlist 0
[http @ 0x2726c60] HTTP error 403 Forbidden
[hls,applehttp @ 0x2695580] Failed to open segment of playlist 0
[http @ 0x27818a0] HTTP error 403 Forbidden
[hls,applehttp @ 0x2695580] Failed to open segment of playlist 0
[http @ 0x269f360] HTTP error 403 Forbidden
[hls,applehttp @ 0x2695580] Failed to open segment of playlist 0
[http @ 0x269f560] HTTP error 403 Forbidden
[hls,applehttp @ 0x2695580] Failed to open segment of playlist 0
[http @ 0x2726c60] HTTP error 403 Forbidden
[hls,applehttp @ 0x2695580] Failed to open segment of playlist 0
[http @ 0x2726c60] HTTP error 403 Forbidden
[hls,applehttp @ 0x2695580] Failed to open segment of playlist 0
[http @ 0x2726c60] HTTP error 403 Forbidden
[hls,applehttp @ 0x2695580] Failed to open segment of playlist 0
[http @ 0x2726c60] HTTP error 403 Forbidden
[hls,applehttp @ 0x2695580] Failed to open segment of playlist 0
[http @ 0x2726c60] HTTP error 403 Forbidden
[hls,applehttp @ 0x2695580] Failed to open segment of playlist 0
[http @ 0x27818a0] HTTP error 403 Forbidden
[hls,applehttp @ 0x2695580] Failed to open segment of playlist 0
[http @ 0x27818a0] HTTP error 403 Forbidden
[hls,applehttp @ 0x2695580] Failed to open segment of playlist 0
[http @ 0x269f560] HTTP error 403 Forbidden
[hls,applehttp @ 0x2695580] Failed to open segment of playlist 0
[http @ 0x27818a0] HTTP error 403 Forbidden
[hls,applehttp @ 0x2695580] Failed to open segment of playlist 0
[http @ 0x26ebaa0] HTTP error 403 Forbidden
[hls,applehttp @ 0x2695580] Failed to open segment of playlist 0
[http @ 0x269f560] HTTP error 403 Forbidden
[hls,applehttp @ 0x2695580] Failed to open segment of playlist 0
[http @ 0x2726c60] HTTP error 403 Forbidden
[hls,applehttp @ 0x2695580] Failed to open segment of playlist 0
[http @ 0x2782bc0] HTTP error 403 Forbiddentime=00:02:30.02 bitrate=  52.9kbits/s    
[hls,applehttp @ 0x2695580] Failed to open segment of playlist 0
[http @ 0x269f360] HTTP error 403 Forbidden
[hls,applehttp @ 0x2695580] Failed to open segment of playlist 0
[http @ 0x269f360] HTTP error 403 Forbidden
[hls,applehttp @ 0x2695580] Failed to open segment of playlist 0
frame=  496 fps= 35 q=-1.0 Lsize=    1189kB time=00:02:32.97 bitrate=  63.7kbits/s    
video:1058kB audio:116kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 1.279194%
[ffmpeg] 1217779 bytes
[download] 100% of 1.16MiB
```

**Comment by AhmedKamal20** [comment]
Both resulting files are have five seconds only, not the complete video .

**Comment by dstftw** [comment]
Can you watch it in browser in the first place?

**Comment by AhmedKamal20** [comment]
yes, of course 
[![Screen](http://i.imgur.com/QRKVDNP.png)](http://cinemassacre.com/2007/10/28/from-duck-till-dawn/)

**Comment by dstftw** [comment]
Try `youtube-dl -f hd1 http://cinemassacre.com/2007/10/28/from-duck-till-dawn/`.

**Comment by AhmedKamal20** [comment]
**$ youtube-dl -v -f hd1 http://cinemassacre.com/2007/10/28/from-duck-till-dawn/**
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'-f', u'hd1', u'http://cinemassacre.com/2007/10/28/from-duck-till-dawn/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.27
[debug] Python version 2.7.6 - Linux-3.13.0-80-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 11.3-6, avprobe 11.3-6, ffmpeg N-76138-g7b4367d, ffprobe N-76138-g7b4367d, rtmpdump 2.4
[debug] Proxy map: {}
[Cinemassacre] from-duck-till-dawn: Downloading webpage
[ScreenwaveMedia] Cinemassacre-302: Downloading player webpage
[ScreenwaveMedia] Cinemassacre-302: Downloading playerconfig webpage
[ScreenwaveMedia] Cinemassacre-302: Downloading m3u8 information
[debug] Invoking downloader on u'http://206.217.201.111/vod/Cinemassacre-302_hd1.mp4'
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1624, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1566, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 343, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 58, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1905, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 442, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 629, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found

```

**Comment by dstftw** [comment]
And `-f high`.

**Comment by AhmedKamal20** [comment]
downloaded  , thank you @dstftw

**Comment by AhmedKamal20** [comment]
i tried another video http://cinemassacre.com/2015/10/31/celebrating-halloween/
hd1 works 
videos with HD , hd1 , will work 
but in both scenarios  , other formats will not work ! 

```
format code  extension  resolution note
meta         mp4        multiple   Quality selection URL 
high         mp4        360p       
hd1          mp4        720p       
564          mp4        640x360     564k 
1128         mp4        854x480    1128k 
1628         mp4        1280x720   1628k 
3128         mp4        1920x1080  3128k  (best)

```

Is there away to download `3128` format ?

**Comment by dstftw** [comment]
Works fine for me as wel as all m3u8 formats. Can you watch 1920x1080 in browser?

**Comment by AhmedKamal20** [comment]
There is no option to change the quality of this video in the browser, but it's listed in --list-format .

**Comment by AhmedKamal20** [comment]
sorry , the page didn't load well 
yes there is option for 1080P in the browser

**Comment by dstftw** [comment]
So are you able to watch 1080p in browser?

**Comment by AhmedKamal20** [comment]
Sorry , no , HTTP 403
![NO](http://i.imgur.com/QdMS46A.png)

**Comment by dstftw** [comment]
Then you can't download it either.
