### ISSUE TITLE
[TFOU]  Unable to extract wat id

### ISSUE THREAD

**Issue by Crypt0Graf** [rg3/youtube-dl#8691]
Hi,
after the [recent problems with TF1](https://github.com/rg3/youtube-dl/issues/8599) (wat.tv), I thought the fix of this would also fix problems with tfou.fr, which is the child-version of TF1. Unfortunately, it doesn't work with the newest version. 
Here's the output:

youtube-dl http://www.tfou.fr/miraculous/videos/miraculous-les-aventures-de-ladybug-et-chat-noir-guitar-vilain-8719480-739.html --verbose flag
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://www.tfou.fr/miraculous/videos/miraculous-les-aventures-de-ladybug-et-chat-noir-guitar-vilain-8719480-739.html', u'--verbose', u'flag']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.27
[debug] Python version 2.7.6 - Linux-3.13.0-37-generic-x86_64-with-LinuxMint-17.3-rosa
[debug] exe versions: avconv 9.18-6, avprobe 9.18-6, rtmpdump 2.4
[debug] Proxy map: {'no': 'localhost,127.0.0.0/8,::1'}
[TF1] miraculous-les-aventures-de-ladybug-et-chat-noir-guitar-vilain-8719480-739: Downloading webpage
ERROR: Unable to extract wat id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 666, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 316, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/tf1.py", line 52, in _real_extract
    webpage, 'wat id', group='id')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 620, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 611, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract wat id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

This content is geo-restricted (France), but the download from wat.tv was possible from other countries as well, as it still is with tf1.fr .

However, you're doing a great job with youtube-dl. I love it and use it every day.

Thank you.

CTG

**Comment by dstftw** [comment]
This issue has been fixed and fix will be incorporated in the next version of youtube-dl.
