### ISSUE TITLE
[MDR] Mediathek not working

### ISSUE THREAD

**Issue by a-l-e-k** [rg3/youtube-dl#8702]
After recent changes on their site the download from MDR TV or Radio is no longer working. One example for video and one for audio are attached.

youtube-dl -v http://www.mdr.de/tv/programm/video323774.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.mdr.de/tv/programm/video323774.html']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.02.27
[debug] Python version 2.7.10 - Windows-XP-5.1.2600-SP3
[debug] exe versions: ffmpeg N-67100-g6dc99fd, ffprobe N-67100-g6dc99fd, rtmpdump 2.4
[debug] Proxy map: {}
[MDR] 323774: Downloading webpage
ERROR: Unable to extract data url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 666, in extract_info
  File "youtube_dl\extractor\common.pyo", line 316, in extract
  File "youtube_dl\extractor\mdr.pyo", line 72, in _real_extract
  File "youtube_dl\extractor\common.pyo", line 611, in _search_regex
RegexNotFoundError: Unable to extract data url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

youtube-dl -v http://www.mdr.de/mdr-figaro/literatur/audio-2648.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.mdr.de/mdr-figaro/literatur/audio-2648.html']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.02.27
[debug] Python version 2.7.10 - Windows-XP-5.1.2600-SP3
[debug] exe versions: ffmpeg N-67100-g6dc99fd, ffprobe N-67100-g6dc99fd, rtmpdump 2.4
[debug] Proxy map: {}
[generic] audio-2648: Requesting header
WARNING: Falling back on generic information extractor.
[generic] audio-2648: Downloading webpage
[generic] audio-2648: Extracting information
ERROR: Unsupported URL: http://www.mdr.de/mdr-figaro/literatur/audio-2648.html
Traceback (most recent call last):
  File "youtube_dl\extractor\generic.pyo", line 1309, in _real_extract
  File "youtube_dl\compat.pyo", line 248, in compat_etree_fromstring
  File "youtube_dl\compat.pyo", line 237, in _XML
  File "xml\etree\ElementTree.pyo", line 1642, in feed
  File "xml\etree\ElementTree.pyo", line 1506, in _raiseerror
ParseError: not well-formed (invalid token): line 61, column 97
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 666, in extract_info
  File "youtube_dl\extractor\common.pyo", line 316, in extract
  File "youtube_dl\extractor\generic.pyo", line 1956, in _real_extract
UnsupportedError: Unsupported URL: http://www.mdr.de/mdr-figaro/literatur/audio-2648.html

**Comment by dstftw** [comment]
This issue has been fixed and fix will be incorporated in the next version of youtube-dl.
