### ISSUE TITLE
[twitter] Wrong URLs reported for DASH formats

### ISSUE THREAD

**Issue by montanaflynn** [rg3/youtube-dl#8704]
When using youtube-dl to find twitter video URL's sometimes it fails, it seems random and fails roughly half the time. Here are the logs of two identical commands running right after each other where one fails and the next one works.

```
montanaflynn@youtube-dl-server:~$ youtube-dl --verbose -g https://twitter.com/jaydingeer/status/700207533655363584
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'-g', u'https://twitter.com/jaydingeer/status/700207533655363584']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.27
[debug] Python version 2.7.6 - Linux-3.19.0-49-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: ffmpeg N-78050-g209f50e-static, ffprobe N-78050-g209f50e-static
[debug] Proxy map: {}
ERROR: There's no video in this tweet.; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 666, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 316, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/twitter.py", line 237, in _real_extract
    raise ExtractorError('There\'s no video in this tweet.')
ExtractorError: There's no video in this tweet.; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

```
montanaflynn@youtube-dl-server:~$ youtube-dl --verbose -g https://twitter.com/jaydingeer/status/700207533655363584
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'-g', u'https://twitter.com/jaydingeer/status/700207533655363584']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.27
[debug] Python version 2.7.6 - Linux-3.19.0-49-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: ffmpeg N-78050-g209f50e-static, ffprobe N-78050-g209f50e-static
[debug] Proxy map: {}
https://video.twimg.com/ext_tw_video/700207414000242688/pu/vid/720x1280/-Z8BBc5fGcZ2ry8F.mp4
montanaflynn@public-api-production:~$

**Comment by yan12125** [comment]
Thanks for the report. This video will be supported in the next version.

**Comment by odeke-em** [comment]
I don't think that resolved the issue
```shell
$ git log | head -n 4
commit 1b5284b13f1b579b2cbac5ce6ab9faa5b95800fb
Author: Sergey M․ <dstftw@gmail.com>
Date:   Sun Mar 6 05:36:52 2016 +0600
$ youtube-dl -g https://twitter.com/jaydingeer/status/700207533655363584
https://video.twimg.com
https://video.twimg.com
```

That doesn't give the video URL.

**Comment by yan12125** [comment]
Twitter recently introduces DASH formats for some videos. URL field for DASH videos are still a problem (see https://github.com/rg3/youtube-dl/pull/8766#issuecomment-192625095). As a workaround of now, try the following command:
```
youtube-dl -g -f 'best[protocol=https]/best[protocol=http]' https://twitter.com/jaydingeer/status/700207533655363584
```

**Comment by odeke-em** [comment]
Cool. Thanks @yan12125, I can confirm that this works.
```shell
youtube-dl --get-url -f 'best[protocol=https]/best[protocol=http]' https://twitter.com/VicMensa/status/700138050492305408
https://video.twimg.com/ext_tw_video/700129618435526656/pu/vid/1280x720/XFcjoOk9lQ-qa9Tq.mp4
```

**Comment by yan12125** [comment]
Twitter no longer includes DASH formats in these videos, so reported URLs are correct. Note that the latest fix for Twitter is not included in any release yet. Please wait for the next version if you have the same problem as #8966.
