### ISSUE TITLE
Unable to download from Wistia (embed iframe)

### ISSUE THREAD

**Issue by absorber** [rg3/youtube-dl#8707]
I'm trying to download from an (embed) iframe of the video which is located [here](https://asana.com/guide/videos). The referred video is called "30-minute product tour".

Ideally it would download the maximum quality video (in this case, 1080p).
```
└─$  youtube-dl -v 'https://fast.wistia.net/embed/iframe/pa5la81ym3'
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://fast.wistia.net/embed/iframe/pa5la81ym3']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.27
[debug] Python version 2.7.6 - Linux-4.2.0-25-generic-x86_64-with-LinuxMint-17.2-rafaela
[debug] exe versions: avconv 9.18-6, avprobe 9.18-6, ffmpeg 2.4.3-1ubuntu1, ffprobe 2.4.3-1ubuntu1
[debug] Proxy map: {}
[Wistia] pa5la81ym3: Downloading JSON metadata
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 411, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 401, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1692, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 666, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 316, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/wistia.py", line 38, in _real_extract
AttributeError: 'list' object has no attribute 'items'
```

It's the same with the latest version:
```
└─$  youtube-dl -v 'https://fast.wistia.net/embed/iframe/pa5la81ym3'
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://fast.wistia.net/embed/iframe/pa5la81ym3']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.03.01
[debug] Python version 2.7.6 - Linux-4.2.0-25-generic-x86_64-with-LinuxMint-17.2-rafaela
[debug] exe versions: avconv 9.18-6, avprobe 9.18-6, ffmpeg 2.4.3-1ubuntu1, ffprobe 2.4.3-1ubuntu1
[debug] Proxy map: {}
[Wistia] pa5la81ym3: Downloading JSON metadata
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 411, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 401, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1692, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 666, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 316, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/wistia.py", line 38, in _real_extract
AttributeError: 'list' object has no attribute 'items'
```

**Comment by kaeff** [comment]
I also just ran into what seems to be this issue, on OS X with version  2016.02.27 installed via Homebrew.
```
$ youtube-dl -v https://www.thoughtworks.com/talks/keynote-thoughtworks-live-india-2015
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://www.thoughtworks.com/talks/keynote-thoughtworks-live-india-2015']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.27
[debug] Python version 2.7.10 - Darwin-15.2.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.8.1, ffprobe 2.8.1
[debug] Proxy map: {}
[generic] keynote-thoughtworks-live-india-2015: Requesting header
WARNING: Falling back on generic information extractor.
[generic] keynote-thoughtworks-live-india-2015: Downloading webpage
[generic] keynote-thoughtworks-live-india-2015: Extracting information
[Wistia] ikov9qqmln: Downloading JSON metadata
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 411, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 401, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1692, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 677, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 734, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 666, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 316, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/wistia.py", line 38, in _real_extract
AttributeError: 'list' object has no attribute 'items'
```

**Comment by kaeff** [comment]
Just tried the latest master (including the fix commit), and the download is successful using the command above.

@dstftw Wow, thank you so much for fixing this so quickly. Made my day =) Have a nice day

**Comment by ahmadawais** [comment]
If you are unable to find the embed link and all you see is blob links then watch this vid to extract the link https://www.youtube.com/watch?v=brPg8So8H-E

**Comment by b1ggjoe** [comment]
Hello All,

I am experiencing this issue in 01/2019. I can easily (manually) download the individual video files of a selected course. However, I'm having a difficult time finding the correct URL so that I can have youtube-dl grab and download all of the corresponding videos that are members of the course.

Any suggestions?

Thanks!

BJ
