### ISSUE TITLE
[lifenews] please fix extracting (unsupported URL error)

### ISSUE THREAD

**Issue by spvkgn** [rg3/youtube-dl#8714]
```
youtube-dl -v http://lifenews.ru/news/153461
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://lifenews.ru/news/153461']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.27
[debug] Python version 3.2.3 - Linux-3.13.0-77-generic-i686-with-LinuxMint-13-maya
[debug] exe versions: ffmpeg 2.8.6-dpkg, ffprobe 2.8.6-dpkg, rtmpdump 2.4
[debug] Proxy map: {}
[lifenews] 153461: Downloading page
[generic] ns: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ns: Downloading webpage
[generic] ns: Extracting information
ERROR: Unsupported URL: http://www.googletagmanager.com/ns.html?id=GTM-KWTW83
Traceback (most recent call last):
  File "/usr/local/lib/python3.2/dist-packages/youtube_dl/YoutubeDL.py", line 666, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.2/dist-packages/youtube_dl/extractor/common.py", line 316, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python3.2/dist-packages/youtube_dl/extractor/generic.py", line 1956, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.googletagmanager.com/ns.html?id=GTM-KWTW83
```

**Comment by dstftw** [comment]
This issue has been fixed and fix will be incorporated in the next version of youtube-dl.
