### ISSUE TITLE
Correcting container in "-" error at the end of every downloaded video

### ISSUE THREAD

**Issue by bwmarrin** [rg3/youtube-dl#8729]
I'm writing a Discord Music Bot using youtube-dl, ffmpeg, and another small tool.  I have each of these tools piping their content into the next tool and it works great.  However at the end of every single video I get the below error.  It looks like youtube-dl is calling ffmpeg itself but I'm not sure why.  This also adds a bit of delay before the next song starts.

You can see the code for this here : https://github.com/bwmarrin/musicplugin/blob/master/musicplugin.go#L412

The youtube-dl command is
`./youtube-dl -v -f bestaudio -o - URLHERE`

Am I using the tool wrong which is causing this error and if so, how can I use it right? :)  Or is there a bug somewhere?

```
[ffmpeg] Correcting container in "-"
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "./youtube-dl/__main__.py", line 19, in <module>
  File "./youtube-dl/youtube_dl/__init__.py", line 411, in main
  File "./youtube-dl/youtube_dl/__init__.py", line 401, in _real_main
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 1692, in download
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 677, in extract_info
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 722, in process_ie_result
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 1362, in process_video_result
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 1674, in process_info
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 1738, in post_process
  File "./youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 462, in run
  File "./youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 159, in run_ffmpeg
  File "./youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 133, in run_ffmpeg_multiple_files
  File "./youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 133, in <genexpr>
OSError: [Errno 2] No such file or directory: '-'
```

**Comment by bwmarrin** [comment]
Thanks a lot! That was one ninja fast fix.  I cloned the repo and tested again and it did fix the errors.  

Again, thanks a lot.
