### ISSUE TITLE
[Wistia] AttributeError: 'list' object has no attribute 'items'

### ISSUE THREAD

**Issue by kotofond** [rg3/youtube-dl#8751]
```
C:\WINDOWS\system32>youtube-dl --verbose https://mahayanadugast.wistia.com/medias/xkib9pdxyw
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'https://mahayanadugast.wistia.com/medias/xkib9pdxyw']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.03.01
[debug] Python version 3.5.1 - Windows-10-10.0.10586-SP0
[debug] exe versions: ffmpeg N-78358-g674cc26, ffprobe N-78358-g674cc26
[debug] Proxy map: {}
[generic] xkib9pdxyw: Requesting header
WARNING: Falling back on generic information extractor.
[generic] xkib9pdxyw: Downloading webpage
[generic] xkib9pdxyw: Extracting information
[Wistia] xkib9pdxyw: Downloading JSON metadata
Traceback (most recent call last):
  File "C:\Python35\Scripts\youtube-dl-script.py", line 9, in <module>
    load_entry_point('youtube-dl==2016.3.1', 'console_scripts', 'youtube-dl')()
  File "c:\python35\lib\site-packages\youtube_dl\__init__.py", line 411, in main
    _real_main(argv)
  File "c:\python35\lib\site-packages\youtube_dl\__init__.py", line 401, in _real_main
    retcode = ydl.download(all_urls)
  File "c:\python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 1692, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "c:\python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 677, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "c:\python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 734, in process_ie_result
    extra_info=extra_info, download=False, process=False)
  File "c:\python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 666, in extract_info
    ie_result = ie.extract(url)
  File "c:\python35\lib\site-packages\youtube_dl\extractor\common.py", line 316, in extract
    return self._real_extract(url)
  File "c:\python35\lib\site-packages\youtube_dl\extractor\wistia.py", line 38, in _real_extract
    for atype, a in data['assets'].items():
AttributeError: 'list' object has no attribute 'items'
```

**Comment by dstftw** [comment]
This issue is already fixed and fix will be incorporated in the next version of youtube-dl.
