### ISSUE TITLE
Not finding twitter video

### ISSUE THREAD

**Issue by montanaflynn** [rg3/youtube-dl#8763]
Hi, I reported another issue with twitter link failing intermittently but this one fails all the time so I thought I'd report it as well. Thanks!

`youtube-dl -f 18 --verbose https://twitter.com/stephaniedobyns/status/705860251132628993`

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-f', u'18', u'--verbose', u'https://twitter.com/stephaniedobyns/status/705860251132628993']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.03.01
[debug] Python version 2.7.10 - Linux-4.2.0-18-generic-x86_64-with-Ubuntu-15.10-wily
[debug] exe versions: none
[debug] Proxy map: {}
[twitter] 705860251132628993: Downloading webpage
ERROR: There's no video in this tweet.; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 666, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 316, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/twitter.py", line 237, in _real_extract
    raise ExtractorError('There\'s no video in this tweet.')
ExtractorError: There's no video in this tweet.; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

**Comment by dstftw** [comment]
This issue is already fixed and fix will be incorporated in the next version of youtube-dl.
