### ISSUE TITLE
SSLv2 Problem

### ISSUE THREAD

**Issue by Metalhead33** [rg3/youtube-dl#8767]
So, I go ahead and attempt to download a playlist:

> metalhead33@localhost ~/haguichi $ youtube-dl -citk --max-quality FORMAT --extract-audio --audio-format mp3 https://www.youtube.com/playlist?list=PLX5XLCxTj60mLQ9PqTiwq5PnzP7mZYwun

And the result is:
```
Traceback (most recent call last):
  File "/usr/bin/youtube-dl", line 3, in <module>
    import youtube_dl
  File "/usr/lib64/python2.7/site-packages/youtube_dl/__init__.py", line 15, in <module>
    from .options import (
  File "/usr/lib64/python2.7/site-packages/youtube_dl/options.py", line 7, in <module>
    from .downloader.external import list_external_downloaders
  File "/usr/lib64/python2.7/site-packages/youtube_dl/downloader/__init__.py", line 3, in <module>
    from .common import FileDownloader
  File "/usr/lib64/python2.7/site-packages/youtube_dl/downloader/common.py", line 8, in <module>
    from ..utils import (
  File "/usr/lib64/python2.7/site-packages/youtube_dl/utils.py", line 27, in <module>
    import ssl
  File "/usr/lib64/python2.7/ssl.py", line 97, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: /usr/lib64/python2.7/lib-dynload/_ssl.so: undefined symbol: SSLv2_method
```
My platform is:
Gentoo Linux X64, Kernel 4.4.3.  I have openssl 0.9.8z_p8, pyopenssl 0.15.1-r1, Python 2.7.9-r2, 3.3.5-r1 and 3.4.3

**Comment by yan12125** [comment]
Can you run the following command without errors?
```
python2.7 -c "import _ssl; print(_ssl)"
```
If not, there's something wrong in your Python build. Try to uninstall openssl and Python and rebuild them.
pyopenssl is not used in youtube-dl, so it should be irrelevant.

**Comment by Metalhead33** [comment]
No, I can't. 

> metalhead33@localhost ~/haguichi $ python2.7 -c "import _ssl; print(_ssl)"

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: /usr/lib64/python2.7/lib-dynload/_ssl.so: undefined symbol: SSLv2_method
```
I will try reinstalling Python and OpenSSL then.

**Comment by Metalhead33** [comment]
I re-emerged both Python and OpenSSL. Yay, it works completely perfectly now! Thanks!
