### ISSUE TITLE
vlive unable to extract creator

### ISSUE THREAD

**Issue by codygman** [rg3/youtube-dl#8814]
```shell
youtube-dl:master* λ python test/test_download.py TestDownload.test_VLive
[vlive] 1326: Downloading webpage
ERROR: Unable to download webpage: timed out (caused by timeout('timed out',))
  File "/home/cody/source/unsorted/youtube-dl/youtube_dl/extractor/common.py", line 358, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/home/cody/source/unsorted/youtube-dl/youtube_dl/YoutubeDL.py", line 1933, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/home/cody/source/unsorted/youtube-dl/youtube_dl/utils.py", line 719, in http_open
    req)
  File "/usr/lib/python2.7/urllib2.py", line 1200, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1131, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)

Retrying: 1 failed tries

##########


[vlive] 1326: Downloading webpage
[vlive] 1326: Downloading JSON metadata
ERROR: unable to extract creator; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "test/test_download.py", line 141, in test_template
    force_generic_extractor=params.get('force_generic_extractor', False))
  File "/home/cody/source/unsorted/youtube-dl/youtube_dl/YoutubeDL.py", line 683, in extract_info
    self.report_error(compat_str(e), e.format_traceback())
  File "/home/cody/source/unsorted/youtube-dl/youtube_dl/YoutubeDL.py", line 543, in report_error
    self.trouble(error_message, tb)
  File "/home/cody/source/unsorted/youtube-dl/youtube_dl/YoutubeDL.py", line 513, in trouble
    raise DownloadError(message, exc_info)
DownloadError: ERROR: Unable to download webpage: timed out (caused by timeout('timed out',))
Traceback (most recent call last):
  File "/home/cody/source/unsorted/youtube-dl/youtube_dl/YoutubeDL.py", line 668, in extract_info
    ie_result = ie.extract(url)
  File "/home/cody/source/unsorted/youtube-dl/youtube_dl/extractor/common.py", line 319, in extract
    return self._real_extract(url)
  File "/home/cody/source/unsorted/youtube-dl/youtube_dl/extractor/vlive.py", line 68, in _real_extract
    webpage, 'creator', fatal=False)
  File "/home/cody/source/unsorted/youtube-dl/youtube_dl/extractor/common.py", line 624, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/home/cody/source/unsorted/youtube-dl/youtube_dl/extractor/common.py", line 617, in _search_regex
    self._downloader.report_warning('unable to extract %s' % _name + bug_reports_message())
  File "/home/cody/source/unsorted/youtube-dl/test/helper.py", line 236, in _report_warning
    real_warning(w)
  File "test/test_download.py", line 52, in report_warning
    raise ExtractorError(message)
ExtractorError: unable to extract creator; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

E
======================================================================
ERROR: test_VLive (__main__.TestDownload)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_download.py", line 141, in test_template
    force_generic_extractor=params.get('force_generic_extractor', False))
  File "/home/cody/source/unsorted/youtube-dl/youtube_dl/YoutubeDL.py", line 683, in extract_info
    self.report_error(compat_str(e), e.format_traceback())
  File "/home/cody/source/unsorted/youtube-dl/youtube_dl/YoutubeDL.py", line 543, in report_error
    self.trouble(error_message, tb)
  File "/home/cody/source/unsorted/youtube-dl/youtube_dl/YoutubeDL.py", line 513, in trouble
    raise DownloadError(message, exc_info)
DownloadError: ERROR: unable to extract creator; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

----------------------------------------------------------------------
Ran 1 test in 21.681s

FAILED (errors=1)
```
version:

```
youtube-dl:master* λ git log -n 1 --oneline
e0dccdd [test_YoutubeDL] PEP 8
```

**Comment by yan12125** [comment]
Thanks this will be fixed in the next version.
