### ISSUE TITLE
[Tumblr] Unsupported URL for Instagram and Vine

### ISSUE THREAD

**Issue by Hrxn** [rg3/youtube-dl#8817]
Example 1 (Instagram):
http://vitasidorkina.tumblr.com/post/134652425014/joskriver-victoriassecret-invisibility-or

```
F:\>youtube-dl -v http://vitasidorkina.tumblr.com/post/134652425014/joskriver-victoriassecret-invisibility-or
[debug] System config: []
[debug] User config: [u'-o', u'D:\\Media\\YTIN\\%(id)s-%(title)s.%(ext)s']
[debug] Command-line args: [u'-v', u'http://vitasidorkina.tumblr.com/post/134652425014/joskriver-victoriassecret-invisibility-or']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.03.06
[debug] Python version 2.7.10 - Windows-8-6.2.9200
[debug] exe versions: ffmpeg N-78949-g6f5048f
[debug] Proxy map: {}
[Tumblr] 134652425014: Downloading webpage
[generic] joskriver-victoriassecret-invisibility-or#_=_: Requesting header
WARNING: Falling back on generic information extractor.
[generic] joskriver-victoriassecret-invisibility-or#_=_: Downloading webpage
[generic] joskriver-victoriassecret-invisibility-or#_=_: Extracting information
ERROR: Unsupported URL: http://vitasidorkina.tumblr.com/post/134652425014/joskriver-victoriassecret-invisibility-or#_=_
Traceback (most recent call last):
  File "youtube_dl\extractor\generic.pyo", line 1309, in _real_extract
  File "youtube_dl\compat.pyo", line 248, in compat_etree_fromstring
  File "youtube_dl\compat.pyo", line 237, in _XML
  File "xml\etree\ElementTree.pyo", line 1642, in feed
  File "xml\etree\ElementTree.pyo", line 1506, in _raiseerror
ParseError: junk after document element: line 2, column 35
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 668, in extract_info
  File "youtube_dl\extractor\common.pyo", line 319, in extract
  File "youtube_dl\extractor\generic.pyo", line 1956, in _real_extract
UnsupportedError: Unsupported URL: http://vitasidorkina.tumblr.com/post/134652425014/joskriver-victoriassecret-invisibility-or#_=_


F:\>
```

The direct Instagram link works as it should:
```
F:\>youtube-dl -g https://www.instagram.com/p/-7LnUPGlSo/
http://scontent-fra3-1.cdninstagram.com/t50.2886-16/12327516_1661602684127643_1808426200_n.mp4

F:\>
```

Example 2 (Vine):
http://sutiblr.tumblr.com/post/139638707273

```
F:\>youtube-dl -v http://sutiblr.tumblr.com/post/139638707273
[debug] System config: []
[debug] User config: [u'-o', u'D:\\Media\\YTIN\\%(id)s-%(title)s.%(ext)s']
[debug] Command-line args: [u'-v', u'http://sutiblr.tumblr.com/post/139638707273']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.03.06
[debug] Python version 2.7.10 - Windows-8-6.2.9200
[debug] exe versions: ffmpeg N-78949-g6f5048f
[debug] Proxy map: {}
[Tumblr] 139638707273: Downloading webpage
[generic] 139638707273#_=_: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 139638707273#_=_: Downloading webpage
[generic] 139638707273#_=_: Extracting information
ERROR: Unsupported URL: http://sutiblr.tumblr.com/post/139638707273#_=_
Traceback (most recent call last):
  File "youtube_dl\extractor\generic.pyo", line 1309, in _real_extract
  File "youtube_dl\compat.pyo", line 248, in compat_etree_fromstring
  File "youtube_dl\compat.pyo", line 237, in _XML
  File "xml\etree\ElementTree.pyo", line 1642, in feed
  File "xml\etree\ElementTree.pyo", line 1506, in _raiseerror
ParseError: junk after document element: line 2, column 35
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 668, in extract_info
  File "youtube_dl\extractor\common.pyo", line 319, in extract
  File "youtube_dl\extractor\generic.pyo", line 1956, in _real_extract
UnsupportedError: Unsupported URL: http://sutiblr.tumblr.com/post/139638707273#_=_


F:\>
```

The direct Vine link:
```
F:\>youtube-dl -g https://vine.co/v/ir7qBEIKqvq
http://v.cdn.vine.co/r/videos_h264high/923CB9FFD71312674294815469568_SW_WEBM_145594014779716b7e5cf18.mp4?versionId=WBDu1tZc.i_r9vv310fV4Anjaa4uI9II

F:\>
```

If I recall it correctly, this did work in the past, but I am not completely sure.
Other embedded videos on Tumblr (like Youtube, for example) still work.

**Comment by yan12125** [comment]
Thanks for the report. Instagram and Vine embeds will be supported in the next version.

**Comment by Hrxn** [comment]
Thank you Chi Hsuan!
