### ISSUE TITLE
ERROR: unable to download video data: <urlopen error [Errno 11004] getaddrinfo failed>

### ISSUE THREAD

**Issue by Jimmm** [rg3/youtube-dl#8836]
If I download this channel
https://www.youtube.com/user/askalexru/videos?view=0&flow=grid&sort=da
I can only get one half of them, the other half shows this message:

```
$youtube-dl.exe -v https://www.youtube.com/watch?v=bwAKNU3lEWQ
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=bwAKNU3lEWQ']
[debug] Encodings: locale cp1251, fs mbcs, out None, pref cp1251
[debug] youtube-dl version 2016.03.06
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
WARNING: [youtube] bwAKNU3lEWQ: Skipping DASH manifest: ExtractorError(u"Failed to download MPD manifest: <urlopen error [Errno 11004] getaddrinfo failed> (caused by URLError(gaierror(11004, 'getaddrinfo failed'),))",)
ERROR: unable to download video data: <urlopen error [Errno 11004] getaddrinfo failed>
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 1626, in process_info
  File "youtube_dl\YoutubeDL.pyo", line 1568, in dl
  File "youtube_dl\downloader\common.pyo", line 344, in download
  File "youtube_dl\downloader\http.pyo", line 58, in real_download
  File "youtube_dl\YoutubeDL.pyo", line 1931, in urlopen
  File "urllib2.pyo", line 431, in open
  File "urllib2.pyo", line 449, in _open
  File "urllib2.pyo", line 409, in _call_chain
  File "youtube_dl\utils.pyo", line 833, in https_open
  File "urllib2.pyo", line 1197, in do_open
URLError: <urlopen error [Errno 11004] getaddrinfo failed>
```

I use German Windows 7 x64 with, region and unicode set to Russian, version 2016.3.6.0

**Comment by dstftw** [comment]
Downloads fine for me. Most likely you have an name lookup/connectivity issues or it's a temporary error on YouTube side.
