### ISSUE TITLE
http://www.courrierinternational.com

### ISSUE THREAD

**Issue by Rudloff** [rg3/youtube-dl#8850]
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://www.courrierinternational.com/article/amours-interdites-chine-cici-et-max-un-amour-secret?utm_campaign=Echobox&utm_medium=Social&utm_source=Facebook#link_time=1457868179', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.03.06
[debug] Python version 2.7.9 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.3
[debug] exe versions: avconv 11.6-6, avprobe 11.6-6, rtmpdump 2.4
[debug] Proxy map: {}
[generic] amours-interdites-chine-cici-et-max-un-amour-secret?utm_campaign=Echobox&utm_medium=Social&utm_source=Facebook#link_time=1457868179: Requesting header
WARNING: Falling back on generic information extractor.
[generic] amours-interdites-chine-cici-et-max-un-amour-secret?utm_campaign=Echobox&utm_medium=Social&utm_source=Facebook#link_time=1457868179: Downloading webpage
[generic] amours-interdites-chine-cici-et-max-un-amour-secret?utm_campaign=Echobox&utm_medium=Social&utm_source=Facebook#link_time=1457868179: Extracting information
ERROR: Unsupported URL: http://www.courrierinternational.com/article/amours-interdites-chine-cici-et-max-un-amour-secret?utm_campaign=Echobox&utm_medium=Social&utm_source=Facebook#link_time=1457868179
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 1309, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/compat.py", line 248, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=etree.TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/compat.py", line 237, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 68, column 69
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 668, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 319, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 1956, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.courrierinternational.com/article/amours-interdites-chine-cici-et-max-un-amour-secret?utm_campaign=Echobox&utm_medium=Social&utm_source=Facebook#link_time=1457868179
```

**Comment by tiburce** [comment]
This site support html5 videos.
For example , with Firefox and html5 video (flash is not installed ) , right click and save as ....

**Comment by tiburce** [comment]
This site does not host its videos, it links embedded videos hosted by other sites.
For example, your test URL relink to arteTV.

**Comment by Rudloff** [comment]
Oh you're right, I didn't see it was an iframe.
