### ISSUE TITLE
Unable to download dailymotion protected video

### ISSUE THREAD

**Issue by sherpadown** [rg3/youtube-dl#8857]
Hello,

I try to download protected video on dailymotion with latest version of youtube-dl.
youtube-dl crashes with this output : 

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--video-password', u'PRIVATE', u'--verbose', u'http://www.dailymotion.com/video/protectedvideo']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.03.14
[debug] Python version 2.7.1 - Darwin-11.4.2-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.8.git, ffprobe 2.8.git
[debug] Proxy map: {}
[dailymotion] x3xg0nh: Downloading webpage
ERROR: An extractor error has occurred. (caused by KeyError(u'title',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/opt/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 320, in extract
    return self._real_extract(url)
  File "/opt/local/bin/youtube-dl/youtube_dl/extractor/dailymotion.py", line 145, in _real_extract
    self._check_error(metadata)
  File "/opt/local/bin/youtube-dl/youtube_dl/extractor/dailymotion.py", line 277, in _check_error
    '%s said: %s' % (self.IE_NAME, info['error']['title']), expected=True)
KeyError: u'title'
Traceback (most recent call last):
  File "/opt/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 668, in extract_info
    ie_result = ie.extract(url)
  File "/opt/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 326, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
ExtractorError: An extractor error has occurred. (caused by KeyError(u'title',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

I hope it will be useful.
Sincerely

**Comment by daxeel** [comment]
You can download protected and copyrighted videos.

**Comment by yan12125** [comment]
Superseded by #9789.
