### ISSUE TITLE
Invalid IPv6 URL

### ISSUE THREAD

**Issue by Wildefyr** [rg3/youtube-dl#8860]
Trying to use youtube-dl on any URL results in the following:

```
[debug] System config: []
[debug] User config: ['ytdl-format=bestvideo[height<=?1080]+bestaudio/best']
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?t=4&v=BaW_jenozKc']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.03.14
[debug] Python version 3.5.1 - Linux-4.1.12-x86_64-Intel-R-_Core-TM-_i5-2500K_CPU_@_3.30GHz-with-glibc2.2.5
[debug] exe versions: ffmpeg N-79043-gf1a3677, ffprobe N-79043-gf1a3677, rtmpdump 2.4
[debug] Proxy map: {}
WARNING: The url doesn't specify the protocol, trying with http
Traceback (most recent call last):
  File "/usr/bin/youtube-dl", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.5/site-packages/youtube_dl/__init__.py", line 412, in main
    _real_main(argv)
  File "/usr/lib/python3.5/site-packages/youtube_dl/__init__.py", line 402, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 1719, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 679, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 731, in process_ie_result
    extra_info=extra_info)
  File "/usr/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 668, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 320, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/generic.py", line 1180, in _real_extract
    parsed_url = compat_urlparse.urlparse(url)
  File "/usr/lib/python3.5/urllib/parse.py", line 295, in urlparse
    splitresult = urlsplit(url, scheme, allow_fragments)
  File "/usr/lib/python3.5/urllib/parse.py", line 345, in urlsplit
    raise ValueError("Invalid IPv6 URL")
ValueError: Invalid IPv6 URL
```

Version is: `2016.03.14`

**Comment by jaimeMF** [comment]
Your config file is wrong, you have to use:
```
--format=bestvideo[height<=?1080]+bestaudio/best
```
