### ISSUE TITLE
Cannot find player ID

### ISSUE THREAD

**Issue by wanchihh** [rg3/youtube-dl#8862]
Hi,

when I tried to download the video at "https://dl.dropboxusercontent.com/u/29092637/interview.html", youtube-dl returns an error "Cannot find player ID".

Thanks.

-----------------------

Output:

C:\youtube-dl> youtube-dl.exe "https://dl.dropboxusercontent.com/u/29092637/interview.html" --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'https://dl.dropboxusercontent.com/u/29092637/interview.html', u'--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.03.14
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-74113-gcdb0225, ffprobe N-74113-gcdb0225
[debug] Proxy map: {}
[generic] interview: Requesting header
WARNING: Falling back on generic information extractor.
[generic] interview: Downloading webpage
[generic] interview: Extracting information
ERROR: Cannot find player ID; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dl\extractor\generic.pyo", line 1314, in _real_extract
  File "youtube_dl\compat.pyo", line 248, in compat_etree_fromstring
  File "youtube_dl\compat.pyo", line 237, in _XML
  File "xml\etree\ElementTree.pyo", line 1642, in feed
  File "xml\etree\ElementTree.pyo", line 1506, in _raiseerror
ParseError: mismatched tag: line 46, column 4
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 668, in extract_info
  File "youtube_dl\extractor\common.pyo", line 320, in extract
  File "youtube_dl\extractor\generic.pyo", line 1374, in _real_extract
  File "youtube_dl\extractor\brightcove.pyo", line 220, in _extract_brightcove_urls
  File "youtube_dl\extractor\brightcove.pyo", line 151, in _build_brighcove_url
ExtractorError: Cannot find player ID; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by yan12125** [comment]
Thanks for the report. This will be fixed in the next version.
