### ISSUE TITLE
AETV Not working

### ISSUE THREAD

**Issue by eremini** [rg3/youtube-dl#8865]
Here's the log:

youtube-dl http://www.aetv.com/shows/bates-motel/season-4/episode-2 --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://www.aetv.com/shows/bates-motel/season-4/episode-2', u'--verbose']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.03.14
[debug] Python version 2.7.10 - Windows-8-6.2.9200
[debug] exe versions: ffmpeg N-78758-g5156578, ffprobe N-78758-g5156578
[debug] Proxy map: {}
[aenetworks] episode-2: Downloading webpage
[ThePlatform] Iz2_VdfKa90_: Downloading SMIL data
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "youtube_dl\__init__.pyo", line 412, in main
  File "youtube_dl\__init__.pyo", line 402, in _real_main
  File "youtube_dl\YoutubeDL.pyo", line 1719, in download
  File "youtube_dl\YoutubeDL.pyo", line 679, in extract_info
  File "youtube_dl\YoutubeDL.pyo", line 736, in process_ie_result
  File "youtube_dl\YoutubeDL.pyo", line 668, in extract_info
  File "youtube_dl\extractor\common.pyo", line 320, in extract
  File "youtube_dl\extractor\theplatform.pyo", line 234, in _real_extract
  File "youtube_dl\extractor\theplatform.pyo", line 34, in _extract_theplatform_smil
  File "youtube_dl\extractor\common.pyo", line 501, in _download_xml
  File "youtube_dl\compat.pyo", line 248, in compat_etree_fromstring
  File "youtube_dl\compat.pyo", line 237, in _XML
  File "xml\etree\ElementTree.pyo", line 1642, in feed
  File "xml\etree\ElementTree.pyo", line 1506, in _raiseerror
xml.etree.ElementTree.ParseError: syntax error: line 1, column 0

**Comment by dstftw** [comment]
Post the output of `youtube-dl -v --dump-pages http://www.aetv.com/shows/bates-motel/season-4/episode-2`.

**Comment by eremini** [comment]
Sorry it's actually a ffmpeg issue, reverting to 2.8.6 fixed it

**Comment by dstftw** [comment]
It has nothing to do with ffmpeg. It has crashed long before it.

**Comment by eremini** [comment]
Then it magically fixed itself.
