### ISSUE TITLE
ERROR: unable to download video data: <urlopen error [Errno 11002] getaddrinfo failed>

### ISSUE THREAD

**Issue by mkranthikmr** [rg3/youtube-dl#8882]
Hi I tried downloading videos from pluralsight and I am getting this error

ERROR: unable to download video data: <urlopen error [Errno 11002] getaddrinfo failed>
Traceback (most recent call last):
  File "C:\Python34\lib\urllib\request.py", line 1174, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "C:\Python34\lib\http\client.py", line 1090, in request
    self._send_request(method, url, body, headers)
  File "C:\Python34\lib\http\client.py", line 1128, in _send_request
    self.endheaders(body)
  File "C:\Python34\lib\http\client.py", line 1086, in endheaders
    self._send_output(message_body)
  File "C:\Python34\lib\http\client.py", line 924, in _send_output
    self.send(msg)
  File "C:\Python34\lib\http\client.py", line 859, in send
    self.connect()
  File "C:\Python34\lib\http\client.py", line 836, in connect
    self.timeout, self.source_address)
  File "C:\Python34\lib\socket.py", line 491, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "C:\Python34\lib\socket.py", line 530, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11002] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\youtube_dl\YoutubeDL.py", line 1627, in process_info
    success = dl(filename, info_dict)
  File "C:\Python34\lib\site-packages\youtube_dl\YoutubeDL.py", line 1569, in dl
    return fd.download(name, info)
  File "C:\Python34\lib\site-packages\youtube_dl\downloader\common.py", line 344, in download
    return self.real_download(filename, info_dict)
  File "C:\Python34\lib\site-packages\youtube_dl\downloader\http.py", line 58, in real_download
    data = self.ydl.urlopen(request)
  File "C:\Python34\lib\site-packages\youtube_dl\YoutubeDL.py", line 1929, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "C:\Python34\lib\urllib\request.py", line 455, in open
    response = self._open(req, data)
  File "C:\Python34\lib\urllib\request.py", line 473, in _open
    '_open', req)
  File "C:\Python34\lib\urllib\request.py", line 433, in _call_chain
    result = func(*args)
  File "C:\Python34\lib\site-packages\youtube_dl\utils.py", line 719, in http_open
    req)
  File "C:\Python34\lib\urllib\request.py", line 1176, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 11002] getaddrinfo failed>

**Comment by dstftw** [comment]
**Post the full output of youtube-dl when run with `-v`**, i.e. **add** `-v` flag to **your command line**, copy the **whole** output and post it in the issue body wrapped in \`\`\` for better formatting. It should look similar to this:
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2015.12.06
[debug] Git HEAD: 135392e
[debug] Python version 2.6.6 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
```
**Do not post screenshots of verbose log only plain text is acceptable.**

The output (including the first lines) contains important debugging information. Issues without the full output are often not reproducible and therefore do not get solved in short order, if ever.

**Comment by mkranthikmr** [comment]
PS I:\Courses\Android Beginner Series Understanding Android> youtube-dl --verbose -c  --username username@gmail.com
--password password**** --socket-timeout 600 --sleep-interval 300 -o "%(autonumber)s - %(title)s.%(ext)s" --autonumber-si
ze 2 "https://app.pluralsight.com/library/courses/android-beginner-platform-overview/table-of-contents"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '-c', '--username', 'PRIVATE', '--password', 'PRIVATE', '--socket-timeout', '60
0', '--sleep-interval', '300', '-o', '%(autonumber)s - %(title)s.%(ext)s', '--autonumber-size', '2', 'https://app.plural
sight.com/library/courses/android-beginner-platform-overview/table-of-contents']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.03.14
[debug] Python version 3.4.2 - Windows-8-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {}
[pluralsight:course] android-beginner-platform-overview: Downloading course JSON
[pluralsight:course] android-beginner-platform-overview: Downloading course data JSON
[download] Downloading playlist: Android Beginner Series: Understanding Android
[pluralsight:course] playlist Android Beginner Series: Understanding Android: Collected 88 video ids (downloading 88 of
them)
[download] Downloading video 1 of 88
[pluralsight] Downloading login page
[pluralsight] Logging in as username@gmail.com
[pluralsight] android-beginner-platform-overview-m1-welcome-0: Downloading webpage
[pluralsight] android-beginner-platform-overview-m1-welcome-0: Downloading mp4-high URL
[pluralsight] android-beginner-platform-overview-m1-welcome-0: Waiting for 5 seconds to avoid throttling
[debug] Invoking downloader on 'http://vid.pluralsight.com/expiretime=1458285187/128bb37b6a2dba1899528617398c457c/clip-v
ideos/john-sonmez/android-beginner-platform-overview-m1-welcome/android-beginner-platform-overview-m1-welcome-01/1024x76
8mp4/20151117141347.mp4'
[download] Sleeping 300.0 seconds...
ERROR: unable to download video data: <urlopen error [Errno 11002] getaddrinfo failed>
Traceback (most recent call last):
  File "C:\Python34\lib\urllib\request.py", line 1174, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "C:\Python34\lib\http\client.py", line 1090, in request
    self._send_request(method, url, body, headers)
  File "C:\Python34\lib\http\client.py", line 1128, in _send_request
    self.endheaders(body)
  File "C:\Python34\lib\http\client.py", line 1086, in endheaders
    self._send_output(message_body)
  File "C:\Python34\lib\http\client.py", line 924, in _send_output
    self.send(msg)
  File "C:\Python34\lib\http\client.py", line 859, in send
    self.connect()
  File "C:\Python34\lib\http\client.py", line 836, in connect
    self.timeout, self.source_address)
  File "C:\Python34\lib\socket.py", line 491, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "C:\Python34\lib\socket.py", line 530, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11002] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\youtube_dl\YoutubeDL.py", line 1627, in process_info
    success = dl(filename, info_dict)
  File "C:\Python34\lib\site-packages\youtube_dl\YoutubeDL.py", line 1569, in dl
    return fd.download(name, info)
  File "C:\Python34\lib\site-packages\youtube_dl\downloader\common.py", line 344, in download
    return self.real_download(filename, info_dict)
  File "C:\Python34\lib\site-packages\youtube_dl\downloader\http.py", line 58, in real_download
    data = self.ydl.urlopen(request)
  File "C:\Python34\lib\site-packages\youtube_dl\YoutubeDL.py", line 1929, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "C:\Python34\lib\urllib\request.py", line 455, in open
    response = self._open(req, data)
  File "C:\Python34\lib\urllib\request.py", line 473, in _open
    '_open', req)
  File "C:\Python34\lib\urllib\request.py", line 433, in _call_chain
    result = func(*args)
  File "C:\Python34\lib\site-packages\youtube_dl\utils.py", line 719, in http_open
    req)
  File "C:\Python34\lib\urllib\request.py", line 1176, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 11002] getaddrinfo failed>
