### ISSUE TITLE
site support request and help regarding developing extractor

### ISSUE THREAD

**Issue by siddht1** [rg3/youtube-dl#8886]
I would like site support for pornjam.com
test http://www.pornjam.com/video/brother-anal-fucks-his-little-sister/

 youtube-dl -v http://www.pornjam.com/video/brother-anal-fucks-his-little-sister/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.pornjam.com/video/brother-anal-fucks-his-little-sister/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.03.14
[debug] Python version 2.7.6 - Linux-3.19.0-32-generic-x86_64-with-LinuxMint-17.3-rosa
[debug] exe versions: avconv 9.18-6, avprobe 9.18-6
[debug] Proxy map: {}
[generic] brother-anal-fucks-his-little-sister: Requesting header
WARNING: Falling back on generic information extractor.
[generic] brother-anal-fucks-his-little-sister: Downloading webpage
[generic] brother-anal-fucks-his-little-sister: Extracting information
ERROR: Unsupported URL: http://www.pornjam.com/video/brother-anal-fucks-his-little-sister/
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1314, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 248, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=etree.TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 237, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 4, column 339
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 668, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 320, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1961, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.pornjam.com/video/brother-anal-fucks-his-little-sister/

But after checking the url and source page   at line number 333   , i found the link for  the  video

http://cdnlw.videosgratis.tv/videos/5/0/f/1/6/50f1678c6de3ablonde-teen-anal.flv?key=rZgNNSflF59XTesBQt4uzKudVvgvQWee_wcO8sgwraglrLnwZww-i9ECVT2shaSb6ozeSOB0TDtqxmFVH0uf5_eRCYU-TuEk-t-lRbg_QciXc9oOW7edyhpUOj5NO-0lAO99GKrn-TOIHnbFOi1tA35CXhiSMkU0DAi3QVPytnjpW6aGzkJ8u6Xm001MPip_G1PDduHmTpiA5WpLFYFLXA

which i downloaded using wget 

So how to code the extractor  for this site

**Comment by dstftw** [comment]
[Developer instructions](https://github.com/rg3/youtube-dl#developer-instructions).

**Comment by siddht1** [comment]
please give an example , a ]n example is better than a template

**Comment by dstftw** [comment]
Choose any existing extractor.

**Comment by siddht1** [comment]
can u write the code

**Comment by siddht1** [comment]
please help in writing the code

**Comment by dstftw** [comment]
Well, decide already whether you want to write it yourself or this is only a site support request and you want someone to write it.

**Comment by dstftw** [comment]
Note that you also must provide example URL that does not violate any [copyrights](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free).

**Comment by siddht1** [comment]
well i would be happy to write it myself , but i also need to understand all the parameters required to build the code. Well though there is no copyrights issue ,but it has age parameters as its an porn site not to be viewed by minors of any country i.e 18 years for my country , 21 years for other countries.

**Comment by siddht1** [comment]
But as this is my first time coding here , how the extractor returns the code ,  i would like to promote theis issue as site support.
