### ISSUE TITLE
CBS.com not working

### ISSUE THREAD

**Issue by syncretic** [rg3/youtube-dl#8892]
E:\apps\mh>youtube-dl --verbose http://www.cbs.com/shows/the-late-show-with-stephen-colbert/video/U6B47sA7bcL1OliOF9n_i6_llXVZLM6r/the-late-show-3-17-2016-william-h-macy-melissa-rauch-isaac-mizrahi-/
[debug] System config: []
[debug] User config: [u'--no-continue', u'-f', u'best', u'--all-subs', u'--call-home']
[debug] Command-line args: [u'--verbose', u'http://www.cbs.com/shows/the-late-show-with-stephen-colbert/video/U6B47sA7bcL1OliOF9n_i6_llXVZLM6r/the-late-show-3-17-2016-william-h-macy-melissa-rauch-isaac-mizrahi-/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.03.14
[debug] Python version 2.7.10 - Windows-8-6.2.9200
[debug] exe versions: ffmpeg N-76419-gdee7440, rtmpdump 2.5
[debug] Proxy map: {}
[debug] Public IP address: 184.58.124.159
[CBS] the-late-show-3-17-2016-william-h-macy-melissa-rauch-isaac-mizrahi-: Downloading webpage
[ThePlatform] of9zYH1kUpJS: Downloading SMIL data
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "youtube_dl\__init__.pyo", line 412, in main
  File "youtube_dl\__init__.pyo", line 402, in _real_main
  File "youtube_dl\YoutubeDL.pyo", line 1719, in download
  File "youtube_dl\YoutubeDL.pyo", line 679, in extract_info
  File "youtube_dl\YoutubeDL.pyo", line 736, in process_ie_result
  File "youtube_dl\YoutubeDL.pyo", line 668, in extract_info
  File "youtube_dl\extractor\common.pyo", line 320, in extract
  File "youtube_dl\extractor\theplatform.pyo", line 234, in _real_extract
  File "youtube_dl\extractor\theplatform.pyo", line 34, in _extract_theplatform_smil
  File "youtube_dl\extractor\common.pyo", line 501, in _download_xml
  File "youtube_dl\compat.pyo", line 248, in compat_etree_fromstring
  File "youtube_dl\compat.pyo", line 237, in _XML
  File "xml\etree\ElementTree.pyo", line 1642, in feed
  File "xml\etree\ElementTree.pyo", line 1506, in _raiseerror
xml.etree.ElementTree.ParseError: syntax error: line 1, column 0

E:\apps\mh>youtube-dl -U
youtube-dl is up-to-date (2016.03.14)

**Comment by remitamine** [comment]
will be fixed in the next version(4c92fd2e835cde89866d3dfb1fc05d23196b19db).
