### ISSUE TITLE
tunein does not work anymore

### ISSUE THREAD

**Issue by bubbleguuum** [rg3/youtube-dl#8899]
./youtube-dl --verbose http://tun.in/sew8w -J --flat-playlist --no-check-certificate --socket-timeout 30
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://tun.in/sew8w', u'-J', u'--flat-playlist', u'--no-check-certificate', u'--socket-timeout', u'30']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.03.18
[debug] Python version 2.7.3 - Linux-3.2.0-70-generic-x86_64-with-Ubuntu-12.04-precise
[debug] exe versions: avconv 0.10.12-7, avprobe 0.10.12-7, ffmpeg 0.10.12-7, ffprobe 0.10.12-7
[debug] Proxy map: {}
ERROR: Unable to extract stream info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 668, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 320, in extract
    return self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/tunein.py", line 33, in _real_extract
    r'\((.*)\);', stream_data, 'stream info'))['Streams']
  File "./youtube-dl/youtube_dl/extractor/common.py", line 621, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract stream info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by bubbleguuum** [comment]
I fixed this issue with the pull request below, but the pull request is blocked by the CI failing on some unrelated extractor. Can a dev commit this patch manually please ? 

https://github.com/rg3/youtube-dl/pull/8924
