### ISSUE TITLE
Youtube broke it again? ERROR: Signature extraction failed

### ISSUE THREAD

**Issue by IvarMatstoms** [rg3/youtube-dl#8904]
[youtube] 62uCuLQtBkk: Extracting video information
[youtube] 62uCuLQtBkk: Encrypted signatures detected.
WARNING: unable to extract html5 player; please report this issue on http://yt-dl.org/bug
[youtube] {43} signature length 44.43, html5 player None
ERROR: Signature extraction failed: Traceback (most recent call last):

**Comment by yan12125** [comment]
62uCuLQtBkk is working fine. Most likely your version is out-dated. Please post the full verbose output with ```-v```. For example:
```
youtube-dl -v 62uCuLQtBkk
```

**Comment by IvarMatstoms** [comment]
ok installed it yesterday but ill try

**Comment by IvarMatstoms** [comment]
im using apt-get and package is updated

**Comment by IvarMatstoms** [comment]
```
/tmp $ youtube-dl -v 62uCuLQtBkk
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', '62uCuLQtBkk']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.08.05
[debug] Python version 2.7.9 - Linux-4.1.18-v7+-armv7l-with-debian-8.0
[debug] Proxy map: {}
[youtube] Setting language
[youtube] 62uCuLQtBkk: Downloading webpage
[youtube] 62uCuLQtBkk: Downloading video info webpage
[youtube] 62uCuLQtBkk: Extracting video information
[youtube] 62uCuLQtBkk: Encrypted signatures detected.
WARNING: unable to extract html5 player; please report this issue on http://yt-dl.org/bug
[youtube] {43} signature length 44.43, html5 player None
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 479, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 356, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
ExtractorError: Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vflKkAVgb/base.js'; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 479, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 356, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
ExtractorError: Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vflKkAVgb/base.js'; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 516, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 170, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 860, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 489, in _decrypt_signature
    u'Signature extraction failed: ' + tb, cause=e)
ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 479, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 356, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
ExtractorError: Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vflKkAVgb/base.js'; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

```

**Comment by yan12125** [comment]
Package managers usually ship very old versions of youtube-dl.
```
[debug] youtube-dl version 2014.08.05
```
The latest version is 2016.03.18. Please remove the one from apt-get and [install manually](https://github.com/rg3/youtube-dl/blob/master/README.md#installation),
