### ISSUE TITLE
404 error while HLS download from youtube

### ISSUE THREAD

**Issue by sadono** [rg3/youtube-dl#8909]
Hy guys.

I've faced an error during recording HLS stream. Please, check it out:

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--ignore-errors', u'-v', u'-f', u'95', u'--hls-prefer-native', u'-o', u'AristocratsLive-2016-03-21_013247.%(ext)s', u'ezpBw1z8i1I']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.03.18
[debug] Python version 2.7.5 - Linux-3.10.0-123.8.1.el7.x86_64-x86_64-with-centos-7.1.1503-Core
[debug] exe versions: avconv 10.1, avprobe 10.1
[debug] Proxy map: {}
[youtube] ezpBw1z8i1I: Downloading webpage
[youtube] ezpBw1z8i1I: Downloading video info webpage
[youtube] ezpBw1z8i1I: Extracting video information
[youtube] ezpBw1z8i1I: Downloading formats manifest
[youtube] ezpBw1z8i1I: Downloading MPD manifest
[debug] Invoking downloader on u'https://manifest.googlevideo.com/api/manifest/hls_playlist/id/ezpBw1z8i1I.131/itag/95/source/yt_live_broadcast/requiressl/yes/ratebypass/yes/live/1/cmbypass/yes/goi/160/sgoap/itag%3D140/sgovp/itag%3D136/hls_chunk_host/r2---sn-5hne6nld.googlevideo.com/gcr/nl/playlist_type/DVR/mm/32/mn/sn-5hne6nld/ms/lv/mv/m/nh/IgpwcjAzLmFtczE2Kgw3Mi4xNC4yMTYuODU/pl/18/dover/3/upn/v1O6JW8H_1k/sver/3/fexp/9405984,9416126,9417380,9420016,9420452,9422596,9423661,9423662,9425064,9425969,9427902,9428289,9428983,9429013,9429255,9429650,9429887,9431012,9432388/mt/1458516731/ip/178.62.219.217/ipbits/0/expire/1458538370/sparams/ip,ipbits,expire,id,itag,source,requiressl,ratebypass,live,cmbypass,goi,sgoap,sgovp,hls_chunk_host,gcr,playlist_type,mm,mn,ms,mv,nh,pl/signature/1A080D63DAD35F1EB3A18982A58F96B89B0B17C4.0735BE8EB697F514A19F5FE961939ED1B7CCB34A/key/dg_yt0/playlist/index.m3u8'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 2909
[download] Destination: AristocratsLive-2016-03-21_013247.mp4
[download]   7.3% of ~1.70GiB at 66.20MiB/s ETA 02:38ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1627, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1569, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 344, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/hls.py", line 49, in real_download
    success = ctx['dl'].download(frag_filename, {'url': frag_url})
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 344, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 58, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1929, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found

I use the latest version of youtube-dl. VLC also doesn't want to play stream from youtube.

**Comment by Arrappathor** [comment]
Hi there, 
i get this http-error:

x@x-satellite:/media/x/0468-4FD3$ youtube-dl --verbose  http://www.ardmediathek.de/tv/Tatort/Zorn-Gottes-Video-tgl-ab-20-Uhr/Das-Erste/Video?bcastId=602916&documentId=34233908
[1] 1586
x@x-satellite:/media/x/0468-4FD3$ [debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.ardmediathek.de/tv/Tatort/Zorn-Gottes-Video-tgl-ab-20-Uhr/Das-Erste/Video?bcastId=602916']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.03.18
[debug] Python version 2.7.9 - Linux-3.16.0-4-686-pae-i686-with-debian-8.3
[debug] exe versions: avconv 11.6-6, avprobe 11.6-6
[debug] Proxy map: {}
[ARD:mediathek] Video: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 365, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1929, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

^C
[1]+  Exit 1                  youtube-dl --verbose http://www.ardmediathek.de/tv/Tatort/Zorn-Gottes-Video-tgl-ab-20-Uhr/Das-Erste/Video?bcastId=602916
x@x-satellite:/media/x/0468-4FD3$ youtube-dl -U
youtube-dl is up-to-date (2016.03.18)
x@x-satellite:/media/x/0468-4FD3$ 

Thanks!

**Comment by dstftw** [comment]
`--hls-prefer-native` does not support live streams.
