### ISSUE TITLE
[dailymotion] HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by elouann** [rg3/youtube-dl#8915]
Hi all,

I'm using youtube-dl without problem on many websites.
Unfortunattely, Dailymotion is responding "HTTP Error 403: Forbidden"
I tried diferrent URLs, checked the opened bug reports, and read the bug reporting guidelines.

Here the full verbose output:

```
$ torsocks youtube-dl --verbose "http://www.dailymotion.com/playlist/xvku1_JIENDALL_virtualisation-debian-et-derivee/1#video=x8mltx"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.dailymotion.com/playlist/xvku1_JIENDALL_virtualisation-debian-et-derivee/1#video=x8mltx']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.22
[debug] Python version 2.7.9 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.3
[debug] exe versions: none
[debug] Proxy map: {}
[dailymotion:playlist] xvku1_JIENDALL_virtualisation-debian-et-derivee: Downloading webpage
[download] Downloading playlist: virtualisation debian et dérivée
[dailymotion:playlist] xvku1_JIENDALL_virtualisation-debian-et-derivee: Downloading page 1
[dailymotion:playlist] playlist virtualisation debian et dérivée: Downloading 14 videos
[download] Downloading video 1 of 14
[dailymotion] x8mltx: Downloading webpage
[dailymotion] x8mltx: Downloading m3u8 information
[debug] Invoking downloader on u'https://www.dailymotion.com/cdn/H264-512x384/video/x8mltx.mp4?auth=1458730029-2562-mf4khchq-60fe66db5a29f044ebb00c66e10a3796'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1624, in process_info
    success = dl(filename, info_dict)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1566, in dl
    return fd.download(name, info)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/downloader/common.py", line 343, in download
    return self.real_download(filename, info_dict)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/downloader/http.py", line 58, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1905, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 469, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 656, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden
```

More context: I'm using [Tails](https://tails.boum.org) 2.2.1, and installed youtube-dl with `apt-get install youtube-dl/stretch`. Youtube-dl is here routed through Tor with `torsocks`, which works with regular youtube videos.
Please find the output with `--dump-pages` on this [zerobin](https://zerobin.net/?d3536a1cbb1beeb7#RXTQdFKbplqbXDZM/RhM2KLBTdZdevMm7dnDi6HUuy8=)

**Comment by Joshfindit** [comment]
Additional info:

Just got 403 while trying to download this: http://www.dailymotion.com/video/x5udlyp but I was able to work around it with a simple trick.

### Full command
```
youtube-dl http://www.dailymotion.com/video/x5udlyp -f best --hls-prefer-native
[dailymotion] x5udlyp: Downloading webpage
[dailymotion] x5udlyp: Downloading m3u8 information
[dailymotion] x5udlyp: Downloading m3u8 information
[dailymotion] x5udlyp: Downloading m3u8 information
[dailymotion] x5udlyp: Downloading m3u8 information
[dailymotion] x5udlyp: Downloading m3u8 information
[dailymotion] x5udlyp: Downloading m3u8 information
[hlsnative] Downloading m3u8 manifest
WARNING: hlsnative has detected features it does not support, extraction will be delegated to ffmpeg
[download] Destination: Steven Universe - Save The Light - Comic-Con 2017 Official Trailer-x5udlyp.mp4
ffmpeg version 3.4.1 Copyright (c) 2000-2017 the FFmpeg developers
  built with Apple LLVM version 9.0.0 (clang-900.0.39.2)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/3.4.1 --enable-shared --enable-pthreads --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-gpl --enable-libmp3lame --enable-libx264 --enable-libxvid --enable-opencl --enable-videotoolbox --disable-lzma
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
[https @ 0x7fc19c5003e0] HTTP error 403 Forbidden
https://proxy-02.nyc.dailymotion.com/sec(x89ccd4bdfc8fccc45be43825a51b760)/p/video/353/453/353354353_mp4_h264_aac_hd_2.m3u8#cell=nyc: Server returned 403 Forbidden (access denied)


ERROR: ffmpeg exited with code 1
```

### Extrapolated (failing) `ffmpeg` command
```
ffmpeg -i https://proxy-02.nyc.dailymotion.com/sec\(x89ccd4bdfc8fccc45be43825a51b760\)/p/video/353/453/353354353_mp4_h264_aac_hd_2.m3u8#cell=nyc "Steven Universe - Save The Light - Comic-Con 2017 Official Trailer-x5udlyp.mp4"
```

### Working `ffmpeg` command
```
ffmpeg -i https://proxy-02.nyc.dailymotion.com/sec\(x89ccd4bdfc8fccc45be43825a51b760\)/p/video/353/453/353354353_mp4_h264_aac_hd_2.m3u8 "Steven Universe - Save The Light - Comic-Con 2017 Official Trailer-x5udlyp.mp4"
```

*Note the missing **`#cell=nyc`**.*

**Comment by Poilaucul** [comment]
Same here.
```
C:\Users\_A.T.Omix_>youtube-dl https://www.dailymotion.com/video/x5seikg
[dailymotion] x5seikg: Downloading webpage
[dailymotion] x5seikg: Downloading m3u8 information
[dailymotion] x5seikg: Downloading m3u8 information
[dailymotion] x5seikg: Downloading m3u8 information
[dailymotion] x5seikg: Downloading m3u8 information
[dailymotion] x5seikg: Downloading m3u8 information
[dailymotion] x5seikg: Downloading m3u8 information
[dailymotion] x5seikg: Downloading m3u8 information
ERROR: requested format not available

C:\Users\_A.T.Omix_>
C:\Users\_A.T.Omix_>
C:\Users\_A.T.Omix_>youtube-dl -f hls-1080-3 https://www.dailymotion.com/video/x5seikg
[dailymotion] x5seikg: Downloading webpage
[dailymotion] x5seikg: Downloading m3u8 information
[dailymotion] x5seikg: Downloading m3u8 information
[dailymotion] x5seikg: Downloading m3u8 information
[dailymotion] x5seikg: Downloading m3u8 information
[dailymotion] x5seikg: Downloading m3u8 information
[dailymotion] x5seikg: Downloading m3u8 information
[dailymotion] x5seikg: Downloading m3u8 information
[download] Destination: U:\MPV\NA\20170703 - Damso - N. J Respect R - x5seikg - NA vues.mp4
ffmpeg version N-90346-g86c7d8df95 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 7.3.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
  libavutil      56. 10.100 / 56. 10.100
  libavcodec     58. 14.100 / 58. 14.100
  libavformat    58. 10.100 / 58. 10.100
  libavdevice    58.  2.100 / 58.  2.100
  libavfilter     7. 13.100 /  7. 13.100
  libswscale      5.  0.102 /  5.  0.102
  libswresample   3.  0.101 /  3.  0.101
  libpostproc    55.  0.100 / 55.  0.100
[https @ 000001adeab6bbc0] HTTP error 403 Forbidden
https://proxy-050.dc3.dailymotion.com/sec(x6d225777fbacab8d1aba6ee5abc80e0)/p/video/673/730/350037376_mp4_h264_aac_fhd.m3u8#cell=core: Server returned 403 Forbidden (access denied)


ERROR: ffmpeg exited with code 1

C:\Users\_A.T.Omix_>
```
