### ISSUE TITLE
Unable download CBS video saying Unauthorized

### ISSUE THREAD

**Issue by harlanb** [rg3/youtube-dl#8946]
This issue started with last update.

 $ youtube-dl --prefer-ffmpeg http://www.cbs.com/shows/scorpion/video/8C17FAA4-E1E8-B023-704E-9593559CAD8F/scorpion-djibouti-call/ --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--prefer-ffmpeg', u'http://www.cbs.com/shows/scorpion/video/8C17FAA4-E1E8-B023-704E-9593559CAD8F/scorpion-djibouti-call/', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.03.18
[debug] Python version 2.7.6 - Linux-3.13.0-37-generic-x86_64-with-LinuxMint-17.1-rebecca
[debug] exe versions: avconv 9.18-6, avprobe 9.18-6, ffmpeg N-76694-ga62178b, ffprobe N-76694-ga62178b, rtmpdump 2.4
[debug] Proxy map: {}
[CBS] scorpion-djibouti-call: Downloading webpage
[ThePlatform] QRuwCQJk7fNZ: Downloading SMIL data
[ThePlatform] QRuwCQJk7fNZ: Checking video URL
[ThePlatform] 303babdd-cf69-4e81-b13b-4265e7aa2a8b: Downloading m3u8 information
[ThePlatform] QRuwCQJk7fNZ: Downloading JSON metadata
[debug] Invoking downloader on u'http://once.unicornmedia.com/now/media/progressive/bb0b18ba-64f5-4b1b-a29f-0ac252f06b68/77a785f3-5188-4806-b788-0893a61634ed/468fb310-a585-11e4-bfdb-005056837bc7/303babdd-cf69-4e81-b13b-4265e7aa2a8b/content.mp4'
ERROR: unable to download video data: HTTP Error 401: Unauthorized
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1627, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1569, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 344, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 58, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1929, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 401: Unauthorized

**Comment by dstftw** [comment]
This issue is already fixed and fix will be incorporated in the next version of youtube-dl.
