### ISSUE TITLE
ERROR: giving up after 10 retries for some youtube videos

### ISSUE THREAD

**Issue by zhuyifei1999** [rg3/youtube-dl#8955]
May or may not be a regression from #8466:
```
$ LC_ALL=C sudo -H pip install -U https://github.com/rg3/youtube-dl/zipball/master#egg=youtube-dl
Collecting youtube-dl from https://github.com/rg3/youtube-dl/zipball/master#egg=youtube-dl
  Downloading https://github.com/rg3/youtube-dl/zipball/master
     | 1.3MB 52.5MB/s
Installing collected packages: youtube-dl
  Found existing installation: youtube-dl 2016.3.18
    Uninstalling youtube-dl-2016.3.18:
      Successfully uninstalled youtube-dl-2016.3.18
  Running setup.py install for youtube-dl ... done
Successfully installed youtube-dl-2016.3.18
$ youtube-dl https://www.youtube.com/watch?v=tb-U5694Bhg -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'https://www.youtube.com/watch?v=tb-U5694Bhg', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.03.18
[debug] Python version 2.7.9 - Linux-3.19.0-2-amd64-x86_64-with-debian-8.3
[debug] exe versions: ffmpeg 2.8.6-1, ffprobe 2.8.6-1
[debug] Proxy map: {}
[youtube] tb-U5694Bhg: Downloading webpage
[youtube] tb-U5694Bhg: Downloading video info webpage
[youtube] tb-U5694Bhg: Extracting video information
[youtube] tb-U5694Bhg: Downloading MPD manifest
[debug] Invoking downloader on u'https://r2---sn-p5qlsnez.googlevideo.com/videoplayback?id=b5bf94e7af780618&itag=264&source=youtube&requiressl=yes&nh=IgpwcjAxLmlhZDI2KgkxMjcuMC4wLjE&pl=24&mv=u&ms=au&mn=sn-p5qlsnez&mm=31&ratebypass=yes&mime=video/mp4&gir=yes&clen=21048354&lmt=1381155133260870&dur=35.880&sver=3&key=dg_yt0&upn=fQKB1JXVVis&signature=316D1987474C4E00EEF5BE2090980AFEDFC69B01.922D24D16BC8818DD4C3F1BB4F3AABC53AF0F43C&fexp=9416126,9420452,9422596,9423661,9423662,9424569,9425946,9427902,9428335,9431012,9431439,9432043,9432197,9432586&mt=1458810182&ip=208.80.155.255&ipbits=0&expire=1458832019&sparams=ip,ipbits,expire,id,itag,source,requiressl,nh,pl,mv,ms,mn,mm,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: xiu xiu, creepy teepee 2011-tb-U5694Bhg.f264.mp4
[download] 100% of 20.07MiB in 00:03
[debug] Invoking downloader on u'https://r2---sn-p5qlsnez.googlevideo.com/videoplayback?id=b5bf94e7af780618&itag=141&source=youtube&requiressl=yes&nh=IgpwcjAxLmlhZDI2KgkxMjcuMC4wLjE&pl=24&mv=u&ms=au&mn=sn-p5qlsnez&mm=31&ratebypass=yes&mime=audio/mp4&gir=yes&clen=1148340&lmt=1381155063707495&dur=35.990&sver=3&key=dg_yt0&upn=fQKB1JXVVis&signature=348B4BE57C1C04ABB024A05DA956B281EC6F7656.3B57A932FCE7909FC8EF4B2DA643BD5F6D84A2A6&fexp=9416126,9420452,9422596,9423661,9423662,9424569,9425946,9427902,9428335,9431012,9431439,9432043,9432197,9432586&mt=1458810182&ip=208.80.155.255&ipbits=0&expire=1458832019&sparams=ip,ipbits,expire,id,itag,source,requiressl,nh,pl,mv,ms,mn,mm,ratebypass,mime,gir,clen,lmt,dur'
[download] Got server HTTP error. Retrying (attempt 1 of 10)...
[download] Got server HTTP error. Retrying (attempt 2 of 10)...
[download] Got server HTTP error. Retrying (attempt 3 of 10)...
[download] Got server HTTP error. Retrying (attempt 4 of 10)...
[download] Got server HTTP error. Retrying (attempt 5 of 10)...
[download] Got server HTTP error. Retrying (attempt 6 of 10)...
[download] Got server HTTP error. Retrying (attempt 7 of 10)...
[download] Got server HTTP error. Retrying (attempt 8 of 10)...
[download] Got server HTTP error. Retrying (attempt 9 of 10)...
[download] Got server HTTP error. Retrying (attempt 10 of 10)...
ERROR: giving up after 10 retries
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/http.py", line 58, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1929, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 500: Internal Server Error
```

**Comment by dstftw** [comment]
Unrelated to #8466. Format 141 is not available on YouTube side.
