### ISSUE TITLE
Twitter video not found

### ISSUE THREAD

**Issue by mgaitan** [rg3/youtube-dl#8966]
I'm trying to download this video from a tweet https://twitter.com/LeandroQuiroga6/status/713095674393464834

```
tin@morochita:~$ youtube-dl https://twitter.com/LeandroQuiroga6/status/713095674393464834 --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'https://twitter.com/LeandroQuiroga6/status/713095674393464834', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.03.18
[debug] Python version 2.7.10 - Linux-4.2.0-18-generic-x86_64-with-Ubuntu-15.10-wily
[debug] exe versions: ffmpeg 2.7.2-1build1, ffprobe 2.7.2-1build1
[debug] Proxy map: {}
[twitter] 713095674393464834: Downloading webpage
[twitter:card] 713095674393464834: Downloading webpage
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 668, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 320, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/twitter.py", line 161, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 839, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by kotofond** [comment]
Facing the same issue with the latest version of youtube-dl:

```
C:\WINDOWS\system32>youtube-dl --verbose https://twitter.com/SaiRi_iTo/status/705783956570902530
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'https://twitter.com/SaiRi_iTo/status/705783956570902530']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.03.25
[debug] Python version 3.5.1 - Windows-10-10.0.10586-SP0
[debug] exe versions: ffmpeg N-78358-g674cc26, ffprobe N-78358-g674cc26
[debug] Proxy map: {}
[twitter] 705783956570902530: Downloading webpage
[twitter:card] 705783956570902530: Downloading webpage
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 668, in extract_info
    ie_result = ie.extract(url)
  File "c:\python35\lib\site-packages\youtube_dl\extractor\common.py", line 320, in extract
    return self._real_extract(url)
  File "c:\python35\lib\site-packages\youtube_dl\extractor\twitter.py", line 161, in _real_extract
    self._sort_formats(formats)
  File "c:\python35\lib\site-packages\youtube_dl\extractor\common.py", line 839, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by yan12125** [comment]
Thanks you all. Twitter will be fixed in the next version.
