### ISSUE TITLE
Naver tvcast : authentication issue

### ISSUE THREAD

**Issue by yupmin** [rg3/youtube-dl#8971]
youtube-dl -v http://tvcast.naver.com/v/656759
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://tvcast.naver.com/v/656759']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.03.18
[debug] Python version 2.7.10 - Darwin-15.4.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[Naver] 656759: Downloading webpage
ERROR: 19세 미만 청소년은 감상하실 수 없는 동영상으로
로그인 후 이용이 가능합니다.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 668, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 320, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/naver.py", line 52, in _real_extract
    raise ExtractorError(error, expected=True)
ExtractorError: 19\uc138 \ubbf8\ub9cc \uccad\uc18c\ub144\uc740 \uac10\uc0c1\ud558\uc2e4 \uc218 \uc5c6\ub294 \ub3d9\uc601\uc0c1\uc73c\ub85c
\ub85c\uadf8\uc778 \ud6c4 \uc774\uc6a9\uc774 \uac00\ub2a5\ud569\ub2c8\ub2e4.

19세 미만 청소년은 감상하실 수 없는 동영상으로
로그인 후 이용이 가능합니다. => Youth under the age of 19 will not be available after you log in to watch video.

**Comment by yan12125** [comment]
Logging is not implemented yet.
