### ISSUE TITLE
[Youtube] Playback on other websites has been disabled by the video owner

### ISSUE THREAD

**Issue by kotofond** [rg3/youtube-dl#8975]
```
C:\WINDOWS\system32>youtube-dl --verbose https://www.youtube.com/watch?v=gUYU3FqMLT8
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=gUYU3FqMLT8']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.03.25
[debug] Python version 3.5.1 - Windows-10-10.0.10586-SP0
[debug] exe versions: ffmpeg N-78358-g674cc26, ffprobe N-78358-g674cc26
[debug] Proxy map: {}
[youtube] gUYU3FqMLT8: Downloading webpage
[youtube] gUYU3FqMLT8: Downloading embed webpage
[youtube] gUYU3FqMLT8: Refetching age-gated info webpage
ERROR: gUYU3FqMLT8: YouTube said: <a href="http://www.youtube.com/watch?v=gUYU3FqMLT8&feature=player_embedded" target="_blank">Watch this video on YouTube.</a><br/>Playback on other websites has been disabled by the video owner.
Traceback (most recent call last):
  File "c:\python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 668, in extract_info
    ie_result = ie.extract(url)
  File "c:\python35\lib\site-packages\youtube_dl\extractor\common.py", line 320, in extract
    return self._real_extract(url)
  File "c:\python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1298, in _real_extract
    expected=True, video_id=video_id)
youtube_dl.utils.ExtractorError: gUYU3FqMLT8: YouTube said: <a href="http://www.youtube.com/watch?v=gUYU3FqMLT8&feature=player_embedded" target="_blank">Watch this video on YouTube.</a><br/>Playback on other websites has been disabled by the video owner.
```

**Comment by yan12125** [comment]
As indicated you need to provide credentials via ```--username``` and ```--password``` or use ```--netrc```.

**Comment by kotofond** [comment]
You are right, thanks. Sorry about false alarm
