### ISSUE TITLE
thescene.com not working

### ISSUE THREAD

**Issue by himadri0327** [rg3/youtube-dl#8978]
C:> youtube-dl -v https://thescene.com/watch/vogue/narciso-rodriguez-spring-2013-ready-to-wear
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://thescene.com/watch/vogue/narciso-rodriguez-spring-2013-ready-to-wear']
[debug] Encodings: locale cp1252, fs mbcs, out cp1251, pref cp1252
[debug] youtube-dl version 2016.03.25
[debug] Python version 2.7.10 - Windows-8-6.2.9200
[debug] exe versions: ffmpeg N-69156-gff5b9a1c, ffprobe N-69156-gff5b9a1c
[debug] Proxy map: {}
[TheScene] narciso-rodriguez-spring-2013-ready-to-wear: Downloading webpage
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "youtube_dl\__init__.pyo", line 419, in main
  File "youtube_dl\__init__.pyo", line 409, in _real_main
  File "youtube_dl\YoutubeDL.pyo", line 1719, in download
  File "youtube_dl\YoutubeDL.pyo", line 668, in extract_info
  File "youtube_dl\extractor\common.pyo", line 320, in extract
  File "youtube_dl\extractor\thescene.pyo", line 25, in _real_extract
AttributeError: 'module' object has no attribute 'urljoin'

**Comment by himadri0327** [comment]
Great work. Thank you.
