### ISSUE TITLE
CBS? Worked, but now doesn't

### ISSUE THREAD

**Issue by barryanders** [rg3/youtube-dl#8985]
Maybe this is just for me, but when I ran this command most recently, it didn't work, whereas it had been working no problem. Any ideas?

```
youtube-dl http://www.cbs.com/shows/survivor/video/B038A885-94D0-0D47-938B-7BADF048CAB9/survivor-brains-vs-brawn-vs-beauty-the-devils-we-know/
[CBS] survivor-brains-vs-brawn-vs-beauty-the-devils-we-know: Downloading webpage
[ThePlatform] XfH4DAy4QpYp: Downloading SMIL data
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 412, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 402, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1718, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 679, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 736, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 668, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 319, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/theplatform.py", line 234, in _real_extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/theplatform.py", line 34, in _extract_theplatform_smil
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 494, in _download_xml
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 248, in compat_etree_fromstring
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 237, in _XML
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: syntax error: line 1, column 0
```

**Comment by witmore1** [comment]
I am having the same problem with both the version from 3/18/2016 and 3/25/2016

` youtube-dl -v http://www.cbs.com/shows/big_bang_theory/video/0D36476D-16EC-F0CE-CDA9-5D5956B97CC1/the-big-bang-theory-the-application-deterioration/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.cbs.com/shows/big_bang_theory/video/0D36476D-16EC-F0CE-CDA9-5D5956B97CC1/the-big-bang-theory-the-application-deterioration/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.03.25
[debug] Python version 2.7.6 - Linux-3.19.0-51-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: ffmpeg git-2016-02-15-295de3e, ffprobe git-2016-02-15-295de3e
[debug] Proxy map: {}
[CBS] the-big-bang-theory-the-application-deterioration: Downloading webpage
[ThePlatform] CAtw1PioYHFg: Downloading SMIL data
[ThePlatform] CAtw1PioYHFg: Checking video URL
[ThePlatform] CAtw1PioYHFg: Downloading JSON metadata
[debug] Invoking downloader on u'http://once-aws-us-west-2c.unicornmedia.com/now/od/auto/bb0b18ba-64f5-4b1b-a29f-0ac252f06b68/77a785f3-5188-4806-b788-0893a61634ed/2cfe5a97-97da-4c73-b116-afe93e482a1e/content.once'
[download] The Big Bang Theory - The Application Deterioration-CAtw1PioYHFg.once has already been downloaded
[download] 100% of 3.21KiB
`

**Comment by dstftw** [comment]
This issue is already fixed and fix will be incorporated in the next version of youtube-dl.

**Comment by phihag** [comment]
See [our FAQ](https://yt-dl.org/update) on how to update to youtube-dl 2016.03.26 or newer, where this is fixed.
