### ISSUE TITLE
Error with CC, unpack requires a string argument of length 4

### ISSUE THREAD

**Issue by selvagem** [rg3/youtube-dl#8992]
Here is the error, 

youtube-dl http://www.cc.com/full-episodes/k9bdrw/the-daily-show-with-trevor-noah-march-24--2016---ethan-hawke-season-21-ep-21084
[ComedyCentral] the-daily-show-with-trevor-noah-march-24--2016---ethan-hawke-season-21-ep-21084: Downloading webpage
[ComedyCentral] 089f595a-b17b-44ff-831a-92e396084f89: Downloading info
Traceback (most recent call last):
  File "/Applications/Canopy.app/appdata/canopy-1.5.5.3123.macosx-x86_64/Canopy.app/Contents/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Applications/Canopy.app/appdata/canopy-1.5.5.3123.macosx-x86_64/Canopy.app/Contents/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 419, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 409, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1719, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 668, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 320, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/mtv.py", line 216, in _real_extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/mtv.py", line 180, in _get_videos_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/mtv.py", line 185, in _get_videos_info_from_url
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 496, in _download_xml
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 478, in _download_webpage
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 385, in _download_webpage_handle
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 365, in _request_webpage
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1929, in urlopen
  File "/Applications/Canopy.app/appdata/canopy-1.5.5.3123.macosx-x86_64/Canopy.app/Contents/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 813, in http_response
  File "/Applications/Canopy.app/appdata/canopy-1.5.5.3123.macosx-x86_64/Canopy.app/Contents/lib/python2.7/gzip.py", line 261, in read
    self._read(readsize)
  File "/Applications/Canopy.app/appdata/canopy-1.5.5.3123.macosx-x86_64/Canopy.app/Contents/lib/python2.7/gzip.py", line 303, in _read
    self._read_gzip_header()
  File "/Applications/Canopy.app/appdata/canopy-1.5.5.3123.macosx-x86_64/Canopy.app/Contents/lib/python2.7/gzip.py", line 202, in _read_gzip_header
    self.mtime = read32(self.fileobj)
  File "/Applications/Canopy.app/appdata/canopy-1.5.5.3123.macosx-x86_64/Canopy.app/Contents/lib/python2.7/gzip.py", line 25, in read32
    return struct.unpack("<I", input.read(4))[0]
struct.error: unpack requires a string argument of length 4

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.

**Comment by selvagem** [comment]
Just updated, same error

**Comment by dstftw** [comment]
[How to report bugs](https://github.com/rg3/youtube-dl#bugs).

**Comment by selvagem** [comment]
Woops, forgot the verbose. 

youtube-dl http://www.cc.com/full-episodes/0d8i55/the-daily-show-with-trevor-noah-march-22--2016----taavi-roivas-season-21-ep-21082 -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://www.cc.com/full-episodes/0d8i55/the-daily-show-with-trevor-noah-march-22--2016----taavi-roivas-season-21-ep-21082', u'-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.03.26
[debug] Python version 2.7.9 - Darwin-15.3.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.6.3, ffprobe 2.6.3, rtmpdump 2.4
[debug] Proxy map: {}
[ComedyCentral] the-daily-show-with-trevor-noah-march-22--2016----taavi-roivas-season-21-ep-21082: Downloading webpage
[ComedyCentral] f6e4b53d-2fcc-4e53-95f8-72c4472f8d8b: Downloading info
Traceback (most recent call last):
  File "/Applications/Canopy.app/appdata/canopy-1.5.5.3123.macosx-x86_64/Canopy.app/Contents/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Applications/Canopy.app/appdata/canopy-1.5.5.3123.macosx-x86_64/Canopy.app/Contents/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 419, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 409, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1719, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 668, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 320, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/mtv.py", line 216, in _real_extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/mtv.py", line 180, in _get_videos_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/mtv.py", line 185, in _get_videos_info_from_url
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 496, in _download_xml
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 478, in _download_webpage
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 385, in _download_webpage_handle
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 365, in _request_webpage
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1929, in urlopen
  File "/Applications/Canopy.app/appdata/canopy-1.5.5.3123.macosx-x86_64/Canopy.app/Contents/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 814, in http_response
  File "/Applications/Canopy.app/appdata/canopy-1.5.5.3123.macosx-x86_64/Canopy.app/Contents/lib/python2.7/gzip.py", line 261, in read
    self._read(readsize)
  File "/Applications/Canopy.app/appdata/canopy-1.5.5.3123.macosx-x86_64/Canopy.app/Contents/lib/python2.7/gzip.py", line 303, in _read
    self._read_gzip_header()
  File "/Applications/Canopy.app/appdata/canopy-1.5.5.3123.macosx-x86_64/Canopy.app/Contents/lib/python2.7/gzip.py", line 202, in _read_gzip_header
    self.mtime = read32(self.fileobj)
  File "/Applications/Canopy.app/appdata/canopy-1.5.5.3123.macosx-x86_64/Canopy.app/Contents/lib/python2.7/gzip.py", line 25, in read32
    return struct.unpack("<I", input.read(4))[0]
struct.error: unpack requires a string argument of length 4

**Comment by selvagem** [comment]
I discovered that this error does not occur if I change networks, can you tell me how exactly this error is dependent on the network/isp you are connected to? It seems strange to me.
