### ISSUE TITLE
Comedians in Cars Getting Coffee/Crackle - many episodes failing

### ISSUE THREAD

**Issue by anthorp** [rg3/youtube-dl#8995]
Download is failing for the following urls

S07E06 http://comediansincarsgettingcoffee.com/will-ferrell-mr-ferrell-for-the-last-time-were-going-to-ask-you-to-put-the-cigar-out
S07E05 http://comediansincarsgettingcoffee.com/sebastian-maniscalco-i-dont-think-thats-bestiality
S07E04 http://comediansincarsgettingcoffee.com/garry-shandling-its-great-that-garry-shandling-is-still-alive
S07E03 http://comediansincarsgettingcoffee.com/kathleen-madigan-chuck-martin-stroked-out-on-a-hot-machine
S07E02 http://comediansincarsgettingcoffee.com/steve-martin-if-you-see-this-on-a-toilet-seat-dont-sit-down
S07E01 http://comediansincarsgettingcoffee.com/president-barack-obama-just-tell-him-you-re-the-president
S06E06 http://comediansincarsgettingcoffee.com/stephen-colbert-cut-up-and-bloody-but-looking-good
S06E05 http://comediansincarsgettingcoffee.com/trevor-noah-thats-the-whole-point-of-apartheid-jerry
S06E04 http://comediansincarsgettingcoffee.com/bill-maher-the-comedy-team-of-smug-and-arrogant
S06E03 http://comediansincarsgettingcoffee.com/jim-carrey-we-love-breathing-what-youre-burning-baby
S06E02 http://comediansincarsgettingcoffee.com/steve-harvey-always-do-the-banana-joke-first
S06E01 http://comediansincarsgettingcoffee.com/julia-louis-dreyfus-ill-go-if-i-dont-have-to-talk
S05E08 http://comediansincarsgettingcoffee.com/jimmy-fallon-the-unsinkable-legend-part-1
S05E07 http://comediansincarsgettingcoffee.com/jimmy-fallon-the-unsinkable-legend-part-2
S04E03 http://comediansincarsgettingcoffee.com/robert-klein-opera-pimp

```
$ youtube-dl -v http://comediansincarsgettingcoffee.com/will-ferrell-mr-ferrell-for-the-last-time-were-going-to-ask-you-to-put-the-cigar-out
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://comediansincarsgettingcoffee.com/will-ferrell-mr-ferrell-for-the-last-time-were-going-to-ask-you-to-put-the-cigar-out']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.03.25
[debug] Python version 3.5.1 - Linux-4.1.16-1-lts-x86_64-with-arch
[debug] exe versions: ffmpeg 2.8.5, ffprobe 2.8.5, rtmpdump 2.4
[debug] Proxy map: {}
[ComCarCoff] will-ferrell-mr-ferrell-for-the-last-time-were-going-to-ask-you-to-put-the-cigar-out: Downloading webpage
[Crackle] 2497950: Downloading XML
Traceback (most recent call last):
  File "/usr/bin/youtube-dl", line 9, in <module>
    load_entry_point('youtube-dl==2016.3.25', 'console_scripts', 'youtube-dl')()
  File "/usr/lib/python3.5/site-packages/youtube_dl/__init__.py", line 419, in main
    _real_main(argv)
  File "/usr/lib/python3.5/site-packages/youtube_dl/__init__.py", line 409, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 1719, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 679, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 736, in process_ie_result
    extra_info=extra_info, download=False, process=False)
  File "/usr/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 668, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 320, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/crackle.py", line 54, in _real_extract
    title = item.attrib['t']
AttributeError: 'NoneType' object has no attribute 'attrib'
```

**Comment by saapa** [comment]
Tried this earlier: http://comediansincarsgettingcoffee.com/will-ferrell-mr-ferrell-for-the-last-time-were-going-to-ask-you-to-put-the-cigar-out
Worked for me, I had updated to version 2016.03.27 just before trying.

**Comment by scfc** [comment]
Still doesn't work for me with 2016.03.27:

```
[tim@passepartout ~]$ ./youtube-dl -v http://comediansincarsgettingcoffee.com/will-ferrell-mr-ferrell-for-the-last-time-were-going-to-ask-you-to-put-the-cigar-out
[debug] System config: [u'--prefer-free-formats']
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://comediansincarsgettingcoffee.com/will-ferrell-mr-ferrell-for-the-last-time-were-going-to-ask-you-to-put-the-cigar-out']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.03.27
[debug] Python version 2.7.10 - Linux-4.4.6-300.fc23.x86_64-x86_64-with-fedora-23-Twenty_Three
[debug] exe versions: ffmpeg 2.8.6, ffprobe 2.8.6, rtmpdump 2.4
[debug] Proxy map: {}
[ComCarCoff] will-ferrell-mr-ferrell-for-the-last-time-were-going-to-ask-you-to-put-the-cigar-out: Downloading webpage
[Crackle] 2497950: Downloading XML
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "./youtube-dl/__main__.py", line 19, in <module>
  File "./youtube-dl/youtube_dl/__init__.py", line 419, in main
  File "./youtube-dl/youtube_dl/__init__.py", line 409, in _real_main
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 1724, in download
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 680, in extract_info
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 737, in process_ie_result
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 669, in extract_info
  File "./youtube-dl/youtube_dl/extractor/common.py", line 321, in extract
  File "./youtube-dl/youtube_dl/extractor/crackle.py", line 54, in _real_extract
AttributeError: 'NoneType' object has no attribute 'attrib'
[tim@passepartout ~]$
```

Side note: I do not find the new episodes on crackle.com, only on comediansincarsgettingcoffee.com.
