### ISSUE TITLE
Support for txxx.com

### ISSUE THREAD

**Issue by EnginePod** [rg3/youtube-dl#9015]
This site is getting pretty big (http://alexa.com/siteinfo/txxx.com).
It'd be nice to have support added to it if that would be possible.

**Comment by dstftw** [comment]
Post [an example URL](https://github.com/rg3/youtube-dl/blob/master/README.md#is-the-description-of-the-issue-itself-sufficient).

**Comment by EnginePod** [comment]
http://www.txxx.com/videos/692919/another-example-of-a-desparate-woman-in-the-pawnshop/

**Comment by dstftw** [comment]
This looks like copyrighted content. youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free). Do they have rights to distribute this? If not provide [an example URL](https://github.com/rg3/youtube-dl/blob/master/README.md#is-the-description-of-the-issue-itself-sufficient) that does not violate any copyrights.

**Comment by EnginePod** [comment]
Ah god, I just picked a random video.
I'm in a SFW enviroment right now, but I updated the example video with something else (let me know if there's something wrong with it).

**Comment by dstftw** [comment]
This one similarly contains copyrights.

**Comment by tnmannen** [comment]
(http://www.txxx.com/videos/465363/amateur-teen-lesbians3/)[This example] is not copyrighted

**Comment by tnmannen** [comment]
Checking further there seems to be "partial" support for this site..

```
$ youtube-dl http://www.txxx.com/videos/465363/amateur-teen-lesbians3/
[generic] amateur-teen-lesbians3: Requesting header
WARNING: Falling back on generic information extractor.
[generic] amateur-teen-lesbians3: Downloading webpage
[generic] amateur-teen-lesbians3: Extracting information
[download] Downloading playlist: None
[generic] playlist None: Collected 2 video ids (downloading 2 of them)
[download] Downloading video 1 of 2
WARNING: Your copy of avconv is outdated and unable to properly mux separate video and audio files, youtube-dl will download single file media. Update avconv to version 10-0 or newer to fix this.
[download] Destination: amateur immature lesbians _ Tube Cup (1)-br=134.mp4
[download] 100% of 689.55KiB in 00:28
[download] Downloading video 2 of 2
WARNING: Your copy of avconv is outdated and unable to properly mux separate video and audio files, youtube-dl will download single file media. Update avconv to version 10-0 or newer to fix this.
[download] Destination: amateur immature lesbians _ Tube Cup (2)-timelines.phpcount=2&interval=30&video_id=465363&format=_hq.php
[download] 100% of 258.00B in 00:00
[download] Finished downloading playlist: None
```

But it would be nice to get rid of the "playlist" bug and just have it fetch the video itself =)

**Comment by sebma** [comment]
Yes, it seems it is still partially supported : 

```
$ youtube-dl --ignore-config -g http://www.txxx.com/videos/465363/amateur-teen-lesbians3/
WARNING: Falling back on generic information extractor.
http://www.txxx.com/get_file/9/c8820a08a21a9943ff8611dc37ca93f2/465000/465363/465363_hq.mp4/?br=134
http://www.txxx.com/get_file/9/c8820a08a21a9943ff8611dc37ca93f2/465000/465363/465363_hq.mp4/?br=134
http://www.txxx.com/player/timelines.php?count=2&interval=30&video_id=465363&format=_hq.mp4&rnd=1464715055
```

Can you fix this ?

**Comment by lovelyspringday** [comment]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.12.03*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.12.03**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
C:\youtube-dl>youtube-dl -v https://www.txxx.com/videos/175910/retro-porn-archive-video-reel-old-timers-14-01/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.txxx.com/videos/175910/retro-porn-archive-video-reel-old-timers-14-01/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.12.03
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg 4.1
[debug] Proxy map: {}
[generic] retro porn archive video reel old timers 14 01: Requesting header
WARNING: Falling back on generic information extractor.
[generic] retro porn archive video reel old timers 14 01: Downloading webpage
[generic] retro porn archive video reel old timers 14 01: Extracting information
ERROR: Unsupported URL: https://www.txxx.com/videos/175910/retro-porn-archive-video-reel-old-timers-14-01/
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpflqtkr62\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpflqtkr62\build\youtube_dl\extractor\common.py", line 508, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpflqtkr62\build\youtube_dl\extractor\generic.py", line 3318, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.txxx.com/videos/175910/retro-porn-archive-video-reel-old-timers-14-01/
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.txxx.com/videos/175910/retro-porn-archive-video-reel-old-timers-14-01/

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Site support request for https://www.txxx.com

**Comment by sebma** [comment]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.12.09**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

```
$ youtube-dl --ignore-config -v -g https://www.txxx.com/videos/810778/amateur-ebony-lesbians-threesome/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--ignore-config', '-v', '-g', 'https://www.txxx.com/videos/810778/amateur-ebony-lesbians-threesome/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.12.09
[debug] Python version 3.6.5 (CPython) - Linux-4.4.0-139-generic-x86_64-with-debian-jessie-sid
[debug] exe versions: avconv 3.4.4-1, avprobe 3.4.4-1, ffmpeg 3.4.4-1, ffprobe 3.4.4-1, rtmpdump 2.4
[debug] Proxy map: {}
WARNING: Falling back on generic information extractor.
NOT TEACHABLE
ERROR: Unsupported URL: https://www.txxx.com/videos/810778/amateur-ebony-lesbians-threesome/
Traceback (most recent call last):
  File "/usr/local/miniconda3/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 793, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/miniconda3/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/miniconda3/lib/python3.6/site-packages/youtube_dl/extractor/generic.py", line 3323, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.txxx.com/videos/810778/amateur-ebony-lesbians-threesome/
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.txxx.com/videos/810778/amateur-ebony-lesbians-threesome/

---
