### ISSUE TITLE
Crunchyroll: "AttributeError: 'NoneType' object has no attribute 'strip'"

### ISSUE THREAD

**Issue by JCDoesTech** [rg3/youtube-dl#9017]
While trying to download the series "Shin Sekai Yori" from crunchyroll I get an AttributeError:
`AttributeError: 'NoneType' object has no attribute 'strip'`
It only happened on Episode 24; Here is the verbose output for the problem episode

```
$ youtube-dl -u 'UserNameRedacted' --sub-format ass --sub-lang enUS --write-sub --verbose http://www.crunchyroll.com/shin-sekai-yori-from-the-new-world/episode-24-torchlight-in-the-darkness-611617
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-u', u'PRIVATE', u'--sub-format', u'ass', u'--sub-lang', u'enUS', u'--write-sub', u'--verbose', u'http://www.crunchyroll.com/shin-sekai-yori-from-the-new-world/episode-24-torchlight-in-the-darkness-611617']
Type account password and press [Return]: 
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.06.04.1
[debug] Python version 2.7.10 - Linux-4.2.0-34-generic-x86_64-with-Ubuntu-15.10-wily
[debug] exe versions: avconv 2.7.6-0ubuntu0.15.10.1, avprobe 2.7.6-0ubuntu0.15.10.1, ffmpeg 2.7.6-0ubuntu0.15.10.1, ffprobe 2.7.6-0ubuntu0.15.10.1, rtmpdump 2.4
[debug] Proxy map: {}
[Crunchyroll] Logging in
[Crunchyroll] 611617: Downloading webpage
[Crunchyroll] 611617: Downloading media info
[Crunchyroll] 611617: Downloading media info for 360p
[Crunchyroll] 611617: Downloading media info for 480p
[Crunchyroll] 611617: Downloading media info for 720p
[Crunchyroll] 611617: Downloading media info for 1080p
[Crunchyroll] 611617: Downloading subtitles for English (US)
[Crunchyroll] 611617: Downloading subtitles for Español
[Crunchyroll] 611617: Downloading subtitles for Português (Brasil)
Traceback (most recent call last):
  File "/usr/bin/youtube-dl", line 6, in <module>
    youtube_dl.main()
  File "/usr/lib/python2.7/dist-packages/youtube_dl/__init__.py", line 405, in main
    _real_main(argv)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/__init__.py", line 395, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1502, in download
    res = self.extract_info(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 661, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 707, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1086, in process_video_result
    format['http_headers'] = self._calc_headers(full_format_info)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 973, in _calc_headers
    cookies = self._calc_cookies(info_dict)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 980, in _calc_cookies
    pr = compat_urllib_request.Request(info_dict['url'])
  File "/usr/lib/python2.7/urllib2.py", line 229, in __init__
    self.__original = unwrap(url)
  File "/usr/lib/python2.7/urllib.py", line 1075, in unwrap
    url = url.strip()
AttributeError: 'NoneType' object has no attribute 'strip'
```

Though it does work on many other videos including every other episode in the "Shin Sekai Yori" series.
For example here is the verbose output for episode 25:
```
$ youtube-dl -u 'UserNameRedacted' --sub-format ass --sub-lang enUS --write-sub --verbose http://www.crunchyroll.com/shin-sekai-yori-from-the-new-world/episode-25-from-the-new-world-611619
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-u', u'PRIVATE', u'--sub-format', u'ass', u'--sub-lang', u'enUS', u'--write-sub', u'--verbose', u'http://www.crunchyroll.com/shin-sekai-yori-from-the-new-world/episode-25-from-the-new-world-611619']
Type account password and press [Return]: 
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.06.04.1
[debug] Python version 2.7.10 - Linux-4.2.0-34-generic-x86_64-with-Ubuntu-15.10-wily
[debug] exe versions: avconv 2.7.6-0ubuntu0.15.10.1, avprobe 2.7.6-0ubuntu0.15.10.1, ffmpeg 2.7.6-0ubuntu0.15.10.1, ffprobe 2.7.6-0ubuntu0.15.10.1, rtmpdump 2.4
[debug] Proxy map: {}
[Crunchyroll] Logging in
[Crunchyroll] 611619: Downloading webpage
[Crunchyroll] 611619: Downloading media info
[Crunchyroll] 611619: Downloading media info for 360p
[Crunchyroll] 611619: Downloading media info for 480p
[Crunchyroll] 611619: Downloading media info for 720p
[Crunchyroll] 611619: Downloading media info for 1080p
[Crunchyroll] 611619: Downloading subtitles for English (US)
[Crunchyroll] 611619: Downloading subtitles for Español
[Crunchyroll] 611619: Downloading subtitles for Português (Brasil)
[info] Writing video subtitles to: Crunchyroll-611619.enUS.ass
[debug] Invoking downloader on 'rtmpe://cp150757.edgefcs.net/ondemand/?auth=daEcocBb.crdhaBdKbVdcbWcld4buaCdfcd-bw.AsV-dHa-pCKxnsODEuB&aifp=0009&slist=c21/s/ve1025357/video.mp4'
[download] Destination: Crunchyroll-611619.flv
[debug] rtmpdump command line: rtmpdump --verbose -r 'rtmpe://cp150757.edgefcs.net/ondemand/?auth=daEcocBb.crdhaBdKbVdcbWcld4buaCdfcd-bw.AsV-dHa-pCKxnsODEuB&aifp=0009&slist=c21/s/ve1025357/video.mp4' -o Crunchyroll-611619.flv.part --playpath mp4:c21/s/ve1025357/video.mp4 --resume --skip 1
[rtmpdump] RTMPDump v2.4
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 2
[rtmpdump] DEBUG: Parsed host    : cp150757.edgefcs.net
[rtmpdump] DEBUG: Parsed app     : ondemand/?auth=daEcocBb.crdhaBdKbVdcbWcld4buaCdfcd-bw.AsV-dHa-pCKxnsODEuB&aifp=0009&slist=c21/s/ve1025357/video.mp4
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Protocol : RTMPE
[rtmpdump] DEBUG: Hostname : cp150757.edgefcs.net
[rtmpdump] DEBUG: Port     : 1935
[rtmpdump] DEBUG: Playpath : mp4:c21/s/ve1025357/video.mp4
[rtmpdump] DEBUG: tcUrl    : rtmpe://cp150757.edgefcs.net:1935/ondemand/?auth=daEcocBb.crdhaBdKbVdcbWcld4buaCdfcd-bw.AsV-dHa-pCKxnsODEuB&aifp=0009&slist=c21/s/ve1025357/video.mp4
[rtmpdump] DEBUG: app      : ondemand/?auth=daEcocBb.crdhaBdKbVdcbWcld4buaCdfcd-bw.AsV-dHa-pCKxnsODEuB&aifp=0009&slist=c21/s/ve1025357/video.mp4
[rtmpdump] DEBUG: live     : no
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: Setting buffer time to: 36000000ms
[rtmpdump] Connecting ...
[rtmpdump] DEBUG: RTMP_Connect1, ... connected, handshaking
[rtmpdump] DEBUG: HandShake: Client type: 06
[rtmpdump] DEBUG: HandShake: DH pubkey position: 472
[rtmpdump] DEBUG: HandShake: Client digest offset: 1383
[rtmpdump] DEBUG: HandShake: Initial client digest: 
[rtmpdump] DEBUG: REDACTED (2 Lines)
[rtmpdump] DEBUG: HandShake: Type Answer   : 08
[rtmpdump] WARNING: HandShake: Type mismatch: client sent 6, server answered 8
[rtmpdump] DEBUG: HandShake: Server Uptime : 57176309
[rtmpdump] DEBUG: HandShake: FMS Version   : 5.0.7.1
[rtmpdump] DEBUG: HandShake: Server DH public key offset: 447
[rtmpdump] DEBUG: HandShake: Secret key: 
[rtmpdump] DEBUG: REDACTED (8 Lines)
[rtmpdump] DEBUG: RC4 Out Key: 
[rtmpdump] DEBUG: REDACTED (1 Line)
[rtmpdump] DEBUG: RC4 In Key: 
[rtmpdump] DEBUG:REDACTED (1 Line)
[rtmpdump] DEBUG: HandShake: Calculated digest key from secure key and server digest: 
[rtmpdump] DEBUG: REDACTED (2 Lines)
[rtmpdump] DEBUG: HandShake: Client signature calculated:
[rtmpdump] DEBUG: REDACTED (2 Lines)
[rtmpdump] DEBUG: HandShake: Server sent signature:
[rtmpdump] DEBUG: REDACTED (2 Lines)
[rtmpdump] DEBUG: HandShake: Digest key: 
[rtmpdump] DEBUG: REDACTED (2 Lines)
[rtmpdump] DEBUG: HandShake: Signature calculated:
[rtmpdump] DEBUG: REDACTED (2 Lines)
[rtmpdump] DEBUG: HandShake: Genuine Adobe Flash Media Server
[rtmpdump] DEBUG: HandShake: Handshaking finished....
[rtmpdump] DEBUG: RTMP_Connect1, handshaked
[rtmpdump] DEBUG: Invoking connect
[rtmpdump] INFO: Connected...
[rtmpdump] DEBUG: HandleServerBW: server BW = 1250000
[rtmpdump] DEBUG: HandleClientBW: client BW = 1250000 2
[rtmpdump] DEBUG: HandleChangeChunkSize, received: chunk size change to 4096
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 242 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:             fmsVer, STRING:	FMS/5,0,7,7054>
[rtmpdump] DEBUG: Property: <Name:       capabilities, NUMBER:	127.00>
[rtmpdump] DEBUG: Property: <Name:               mode, NUMBER:	1.00>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:              level, STRING:	status>
[rtmpdump] DEBUG: Property: <Name:               code, STRING:	NetConnection.Connect.Success>
[rtmpdump] DEBUG: Property: <Name:        description, STRING:	Connection succeeded.>
[rtmpdump] DEBUG: Property: <Name:     objectEncoding, NUMBER:	0.00>
[rtmpdump] DEBUG: Property: <Name:               data, ECMA_ARRAY>
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:            version, STRING:	5,0,7,7054>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_result>
[rtmpdump] DEBUG: HandleInvoke, received result for method call <connect>
[rtmpdump] DEBUG: sending ctrl. type: 0x0003
[rtmpdump] DEBUG: Invoking createStream
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 21 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <onBWDone>
[rtmpdump] DEBUG: Invoking _checkbw
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 29 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_result>
[rtmpdump] DEBUG: HandleInvoke, received result for method call <createStream>
[rtmpdump] DEBUG: SendPlay, seekTime=0, stopTime=0, sending play: mp4:c21/s/ve1025357/video.mp4
[rtmpdump] DEBUG: Invoking play
[rtmpdump] DEBUG: sending ctrl. type: 0x0003
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 10275 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_onbwcheck>
[rtmpdump] DEBUG: Invoking _result
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 20515 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_onbwcheck>
[rtmpdump] DEBUG: Invoking _result
[rtmpdump] DEBUG: HandleCtrl, received ctrl. type: 4, len: 6
[rtmpdump] DEBUG: HandleCtrl, Stream IsRecorded 1
[rtmpdump] DEBUG: HandleChangeChunkSize, received: chunk size change to 4096
[rtmpdump] DEBUG: HandleCtrl, received ctrl. type: 0, len: 6
[rtmpdump] DEBUG: HandleCtrl, Stream Begin 1
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 186 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:              level, STRING:	status>
[rtmpdump] DEBUG: Property: <Name:               code, STRING:	NetStream.Play.Start>
[rtmpdump] DEBUG: Property: <Name:        description, STRING:	Started playing c21/s/ve1025357/video.mp4.>
[rtmpdump] DEBUG: Property: <Name:            details, STRING:	c21/s/ve1025357/video.mp4>
[rtmpdump] DEBUG: Property: <Name:           clientid, STRING:	oAAfgWBA>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <onStatus>
[rtmpdump] DEBUG: HandleInvoke, onStatus: NetStream.Play.Start
[rtmpdump] Starting download at: 0.000 kB
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 192 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:              level, STRING:	status>
[rtmpdump] DEBUG: Property: <Name:               code, STRING:	NetStream.Play.Reset>
[rtmpdump] DEBUG: Property: <Name:        description, STRING:	Playing and resetting c21/s/ve1025357/video.mp4.>
[rtmpdump] DEBUG: Property: <Name:            details, STRING:	c21/s/ve1025357/video.mp4>
[rtmpdump] DEBUG: Property: <Name:           clientid, STRING:	oAAfgWBA>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <onStatus>
[rtmpdump] DEBUG: HandleInvoke, onStatus: NetStream.Play.Reset
[rtmpdump] DEBUG: RTMP_ClientPacket, received: notify 24 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: ignoring too small audio packet: size: 0
[rtmpdump] DEBUG: RTMP_ClientPacket, received: notify 44 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:               code, STRING:	NetStream.Data.Start>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: RTMP_ClientPacket, received: notify 494 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:           duration, NUMBER:	1345.13>
[rtmpdump] DEBUG: Property: <Name:       moovPosition, NUMBER:	32.00>
[rtmpdump] DEBUG: Property: <Name:              width, NUMBER:	1920.00>
[rtmpdump] DEBUG: Property: <Name:             height, NUMBER:	1080.00>
[rtmpdump] DEBUG: Property: <Name:       videocodecid, STRING:	avc1>
[rtmpdump] DEBUG: Property: <Name:       audiocodecid, STRING:	mp4a>
[rtmpdump] DEBUG: Property: <Name:         avcprofile, NUMBER:	100.00>
[rtmpdump] DEBUG: Property: <Name:           avclevel, NUMBER:	40.00>
[rtmpdump] DEBUG: Property: <Name:             aacaot, NUMBER:	2.00>
[rtmpdump] DEBUG: Property: <Name:     videoframerate, NUMBER:	23.98>
[rtmpdump] DEBUG: Property: <Name:    audiosamplerate, NUMBER:	44100.00>
[rtmpdump] DEBUG: Property: <Name:      audiochannels, NUMBER:	2.00>
[rtmpdump] DEBUG: Property: <Name:          trackinfo, STRICT_ARRAY>
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:             length, NUMBER:	16124000.00>
[rtmpdump] DEBUG: Property: <Name:          timescale, NUMBER:	11988.00>
[rtmpdump] DEBUG: Property: <Name:           language, STRING:	und>
[rtmpdump] DEBUG: Property: <Name:  sampledescription, STRICT_ARRAY>
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:         sampletype, STRING:	avc1>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:             length, NUMBER:	59320320.00>
[rtmpdump] DEBUG: Property: <Name:          timescale, NUMBER:	44100.00>
[rtmpdump] DEBUG: Property: <Name:           language, STRING:	und>
[rtmpdump] DEBUG: Property: <Name:  sampledescription, STRICT_ARRAY>
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:         sampletype, STRING:	mp4a>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] INFO: Metadata:
[rtmpdump] INFO:   duration              1345.13
[rtmpdump] INFO:   moovPosition          32.00
[rtmpdump] INFO:   width                 1920.00
[rtmpdump] INFO:   height                1080.00
[rtmpdump] INFO:   videocodecid          avc1
[rtmpdump] INFO:   audiocodecid          mp4a
[rtmpdump] INFO:   avcprofile            100.00
[rtmpdump] INFO:   avclevel              40.00
[rtmpdump] INFO:   aacaot                2.00
[rtmpdump] INFO:   videoframerate        23.98
[rtmpdump] INFO:   audiosamplerate       44100.00
[rtmpdump] INFO:   audiochannels         2.00
[rtmpdump] INFO: trackinfo:
[rtmpdump] INFO:   length                16124000.00
[rtmpdump] INFO:   timescale             11988.00
[rtmpdump] INFO:   language              und
[rtmpdump] INFO: sampledescription:
[rtmpdump] INFO:   sampletype            avc1
[rtmpdump] INFO:   length                59320320.00
[rtmpdump] INFO:   timescale             44100.00
[rtmpdump] INFO:   language              und
[rtmpdump] INFO: sampledescription:
[rtmpdump] INFO:   sampletype            mp4a
[download] 1.75KiB at Unknown speed (00:00)
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 30755 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_onbwcheck>
[rtmpdump] DEBUG: Invoking _result
[download]   0.1% of ~188.25MiB at Unknown speed ETA Unknown ETA
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 40995 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_onbwcheck>
[rtmpdump] DEBUG: Invoking _result
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 51235 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_onbwcheck>
[rtmpdump] DEBUG: Invoking _result
[download]   0.2% of ~219.13MiB at 193.13KiB/s ETA 22:02
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 61475 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_onbwcheck>
[rtmpdump] DEBUG: Invoking _result
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 71717 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_onbwcheck>
[rtmpdump] DEBUG: Invoking _result
[download]   0.3% of ~208.58MiB at 283.97KiB/s ETA 13:06
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 81957 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_onbwcheck>
[rtmpdump] DEBUG: Invoking _result
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 92197 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_onbwcheck>
[rtmpdump] DEBUG: Invoking _result
[download]   0.3% of ~250.25MiB at 302.83KiB/s ETA 15:48
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 102437 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_onbwcheck>
[rtmpdump] DEBUG: Invoking _result
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 112677 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_onbwcheck>
[rtmpdump] DEBUG: Invoking _result
[download]   0.3% of ~312.75MiB at 335.67KiB/s ETA 19:00
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 122917 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_onbwcheck>
[rtmpdump] DEBUG: Invoking _result
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 133157 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_onbwcheck>
[rtmpdump] DEBUG: Invoking _result
[download]   0.4% of ~297.06MiB at 400.27KiB/s ETA 14:09
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 40 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_onbwdone>
[download]  61.8% of ~533.19MiB at  1.18MiB/s ETA 02:52
[rtmpdump] DEBUG: HandleCtrl, received ctrl. type: 6, len: 6
[rtmpdump] DEBUG: HandleCtrl, Ping 57411411
[rtmpdump] DEBUG: sending ctrl. type: 0x0007
[download]  99.9% of ~514.76MiB at  1.18MiB/s ETA 00:00
[rtmpdump] DEBUG: ignoring too small audio packet: size: 0
[rtmpdump] DEBUG: RTMP_ClientPacket, received: notify 102 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:               code, STRING:	NetStream.Play.Complete>
[rtmpdump] DEBUG: Property: <Name:              level, STRING:	status>
[rtmpdump] DEBUG: Property: <Name:           duration, NUMBER:	432.00>
[rtmpdump] DEBUG: Property: <Name:              bytes, NUMBER:	539220252.00>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleCtrl, received ctrl. type: 1, len: 6
[rtmpdump] DEBUG: HandleCtrl, Stream EOF 1
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 196 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:              level, STRING:	status>
[rtmpdump] DEBUG: Property: <Name:               code, STRING:	NetStream.Play.Stop>
[rtmpdump] DEBUG: Property: <Name:        description, STRING:	Stopped playing c21/s/ve1025357/video.mp4.>
[rtmpdump] DEBUG: Property: <Name:            details, STRING:	c21/s/ve1025357/video.mp4>
[rtmpdump] DEBUG: Property: <Name:           clientid, STRING:	oAAfgWBA>
[rtmpdump] DEBUG: Property: <Name:             reason, STRING:	>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <onStatus>
[rtmpdump] DEBUG: HandleInvoke, onStatus: NetStream.Play.Stop
[rtmpdump] DEBUG: Invoking deleteStream
[rtmpdump] DEBUG: Got Play.Complete or Play.Stop from server. Assuming stream is complete
[download]  99.9% of ~514.76MiB at  1.18MiB/s ETA 00:00
[rtmpdump] DEBUG: RTMP_Read returned: 0
[rtmpdump] Download complete
[rtmpdump] DEBUG: Closing connection.
[rtmpdump] 539220479 bytes
[download] 100% of 514.24MiB
```
I am unsure of how to fix this problem as I am unfamiliar with python and youtube-dl's code base so any help would be appreciated and any additional information other than secure data (for example: username and password along with secure keys) can be supplied upon request if needed.

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.
