### ISSUE TITLE
Download is always truncated at 89.8% for this one video

### ISSUE THREAD

**Issue by ekevoo** [rg3/youtube-dl#9022]
Applies to the following video: http://youtu.be/7F7JC9q7Lz8

If I visit on the site clicking the link above I can watch the full video.

If I use youtube-dl, the video is truncated at exactly 89.8% (every time); and trying to continue the download won't work.

Downloading anew:

```
ekevoo@Anas:~$ youtube-dl -v 7F7JC9q7Lz8
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'7F7JC9q7Lz8']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.03.27
[debug] Python version 2.7.10 - Darwin-15.3.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] 7F7JC9q7Lz8: Downloading webpage
[youtube] 7F7JC9q7Lz8: Downloading video info webpage
[youtube] 7F7JC9q7Lz8: Extracting video information
[youtube] 7F7JC9q7Lz8: Downloading MPD manifest
[debug] Invoking downloader on u'https://r7---sn-gvbxgn-tt1r.googlevideo.com/videoplayback?mt=1459221270&sparams=dur%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&mv=m&ms=au&sver=3&id=o-AFcJHuYZX0gX-RPoDflXqyXSPUhSm5FIm_cKQMv4Y_-f&mime=video%2Fmp4&pl=19&mm=31&ip=174.119.124.185&key=yt6&mn=sn-gvbxgn-tt1r&expire=1459242991&signature=1DD2C13399C77673C101C9183A0D9E21E5E1DDD5.89BAF2EA52BAB5A025E18942F5F8DDF1B2906860&requiressl=yes&pcm2cms=yes&itag=22&source=youtube&initcwndbps=2370000&dur=221.657&fexp=9408087%2C9416126%2C9420452%2C9422596%2C9423348%2C9423661%2C9423662%2C9427706%2C9427802%2C9427902%2C9429947%2C9430829%2C9431859%2C9432799&lmt=1445579451232601&ipbits=0&upn=dVbqwvvJkNw&ratebypass=yes'
[download] Destination: Come On Spitfire - SkyBolt - (Save Ferris, Ponified)-7F7JC9q7Lz8.mp4
[download]  89.8% of 20.04MiB at  3.49MiB/s ETA 00:00ERROR: content too short (expected 21018521 bytes and served 18874320)
Traceback (most recent call last):
  File "/Users/ekevoo/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1632, in process_info
    success = dl(filename, info_dict)
  File "/Users/ekevoo/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1574, in dl
    return fd.download(name, info)
  File "/Users/ekevoo/bin/youtube-dl/youtube_dl/downloader/common.py", line 350, in download
    return self.real_download(filename, info_dict)
  File "/Users/ekevoo/bin/youtube-dl/youtube_dl/downloader/http.py", line 236, in real_download
    raise ContentTooShortError(byte_counter, int(data_len))
ContentTooShortError
```

Continuing download:

```
ekevoo@Anas:~$ youtube-dl -v 7F7JC9q7Lz8
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'7F7JC9q7Lz8']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.03.27
[debug] Python version 2.7.10 - Darwin-15.3.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] 7F7JC9q7Lz8: Downloading webpage
[youtube] 7F7JC9q7Lz8: Downloading video info webpage
[youtube] 7F7JC9q7Lz8: Extracting video information
[youtube] 7F7JC9q7Lz8: Downloading MPD manifest
[debug] Invoking downloader on u'https://r7---sn-gvbxgn-tt1r.googlevideo.com/videoplayback?mn=sn-gvbxgn-tt1r&mm=31&dur=221.657&mv=m&mt=1459221270&ms=au&lmt=1445579451232601&ip=174.119.124.185&key=yt6&ipbits=0&upn=T5nKG01bhd8&id=o-AHxNy-ot3VfjPa_5RyPfQCgZviKgMmsLhW6okZzNjXuF&initcwndbps=2370000&ratebypass=yes&pl=19&signature=838E83A4EF6C7154326B1283A608521E900AFE77.3C2C4275F3C8377114F3CD7C9F8D11C13E46741C&requiressl=yes&sver=3&mime=video%2Fmp4&source=youtube&pcm2cms=yes&fexp=9406821%2C9407016%2C9408207%2C9416126%2C9420452%2C9422596%2C9423347%2C9423661%2C9423662%2C9427768%2C9427902%2C9428711%2C9429651%2C9431132%2C9431449%2C9431857%2C9432024%2C9432183&sparams=dur%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&itag=22&expire=1459243007'
[download] Resuming download at byte 18874320
[download] Got server HTTP error. Retrying (attempt 1 of 10)...
[download] Got server HTTP error. Retrying (attempt 2 of 10)...
[download] Got server HTTP error. Retrying (attempt 3 of 10)...
[download] Got server HTTP error. Retrying (attempt 4 of 10)...
[download] Got server HTTP error. Retrying (attempt 5 of 10)...
[download] Got server HTTP error. Retrying (attempt 6 of 10)...
[download] Got server HTTP error. Retrying (attempt 7 of 10)...
[download] Got server HTTP error. Retrying (attempt 8 of 10)...
[download] Got server HTTP error. Retrying (attempt 9 of 10)...
[download] Got server HTTP error. Retrying (attempt 10 of 10)...
ERROR: giving up after 10 retries
Traceback (most recent call last):
  File "/Users/ekevoo/bin/youtube-dl/youtube_dl/downloader/http.py", line 58, in real_download
    data = self.ydl.urlopen(request)
  File "/Users/ekevoo/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1934, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 500: Internal Server Error
```

When I was on Windows earlier today and opened #9013 the behaviour was exactly the same, but I didn't remember to make the `-v` output then.

**Comment by yan12125** [comment]
Confirmed with ```-f 22```. As a workaround, install ffmpeg or libav, delete the incomplete file and retry.

**Comment by yan12125** [comment]
For this video and itag 22, youtube served broken files. There's nothing youtube-dl can do. Try other formats.
