### ISSUE TITLE
Crash While downloading Crunchyroll Subtitles

### ISSUE THREAD

**Issue by JCDoesTech** [rg3/youtube-dl#9030]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.03.27*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.03.27**
```
$ youtube-dl -U
youtube-dl is up-to-date (2016.03.27)
```
### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### Description of your *issue*, suggested solution and other information

While attempting to download a video form crunchyroll and list the available subtitles with `--list-subs`; youtube-dl crashes. The crash also occours with the same output when attempting to skip the `--list-subs` command and use the know valid `--sub-lang` of `enUS`.

##### The following is the `2016.03.27` version unsuccessful '--list-subs' output:
```
$ youtube-dl --list-subs -v http://www.crunchyroll.com/gate/episode-23-paradrop-692655
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--list-subs', u'-v', u'http://www.crunchyroll.com/gate/episode-23-paradrop-692655']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.03.27
[debug] Python version 2.7.10 - Linux-4.2.0-34-generic-x86_64-with-Ubuntu-15.10-wily
[debug] exe versions: avconv 2.7.6-0ubuntu0.15.10.1, avprobe 2.7.6-0ubuntu0.15.10.1, ffmpeg 2.7.6-0ubuntu0.15.10.1, ffprobe 2.7.6-0ubuntu0.15.10.1, rtmpdump 2.4
[debug] Proxy map: {}
[Crunchyroll] 692655: Downloading webpage
[Crunchyroll] 692655: Downloading media info
[Crunchyroll] 692655: Downloading media info for 360p
[Crunchyroll] 692655: Downloading media info for 480p
[Crunchyroll] 692655: Downloading media info for 720p
[Crunchyroll] 692655: Downloading media info for 720p
[Crunchyroll] 692655: Downloading media info for 1080p
[Crunchyroll] 692655: Downloading media info for 1080p
[Crunchyroll] 692655: Downloading subtitles for English (US)
[Crunchyroll] 692655: Downloading subtitles for Español
[Crunchyroll] 692655: Downloading subtitles for Español (España)
[Crunchyroll] 692655: Downloading subtitles for Português (Brasil)
[Crunchyroll] 692655: Downloading subtitles for العربية
[Crunchyroll] 692655: Downloading subtitles for Deutsch
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 419, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 409, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1724, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 680, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 725, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1268, in process_video_result
KeyError: u'url'
```

The Download does work without attempting to download subtitles though.

##### The following is the `2016.03.27` version successful video only output:
```
$ youtube-dl -v http://www.crunchyroll.com/gate/episode-23-paradrop-692655
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.crunchyroll.com/gate/episode-23-paradrop-692655']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.03.27
[debug] Python version 2.7.10 - Linux-4.2.0-34-generic-x86_64-with-Ubuntu-15.10-wily
[debug] exe versions: avconv 2.7.6-0ubuntu0.15.10.1, avprobe 2.7.6-0ubuntu0.15.10.1, ffmpeg 2.7.6-0ubuntu0.15.10.1, ffprobe 2.7.6-0ubuntu0.15.10.1, rtmpdump 2.4
[debug] Proxy map: {}
[Crunchyroll] 692655: Downloading webpage
[Crunchyroll] 692655: Downloading media info
[Crunchyroll] 692655: Downloading media info for 360p
[Crunchyroll] 692655: Downloading media info for 480p
[Crunchyroll] 692655: Downloading media info for 720p
[Crunchyroll] 692655: Downloading media info for 720p
[Crunchyroll] 692655: Downloading media info for 1080p
[Crunchyroll] 692655: Downloading media info for 1080p
[debug] Invoking downloader on u'rtmpe://cp150757.edgefcs.net/ondemand/?auth=daEcabLavaEaUakdZcncHdbaQa9cecXbwc_-bw.2o5-dHa-lBKwmqHADuu&aifp=0009&slist=c19/s/ve2175163/video.mp4'
[download] Destination: GATE Episode 23 – Paradrop-692655.flv
[debug] rtmpdump command line: rtmpdump --verbose -r 'rtmpe://cp150757.edgefcs.net/ondemand/?auth=daEcabLavaEaUakdZcncHdbaQa9cecXbwc_-bw.2o5-dHa-lBKwmqHADuu&aifp=0009&slist=c19/s/ve2175163/video.mp4' -o 'GATE Episode 23 – Paradrop-692655.flv.part' --playpath mp4:c19/s/ve2175163/video.mp4 --resume --skip 1
[rtmpdump] RTMPDump v2.4
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 2
[rtmpdump] DEBUG: Parsed host    : cp150757.edgefcs.net
[rtmpdump] DEBUG: Parsed app     : ondemand/?auth=daEcabLavaEaUakdZcncHdbaQa9cecXbwc_-bw.2o5-dHa-lBKwmqHADuu&aifp=0009&slist=c19/s/ve2175163/video.mp4
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Protocol : RTMPE
[rtmpdump] DEBUG: Hostname : cp150757.edgefcs.net
[rtmpdump] DEBUG: Port     : 1935
[rtmpdump] DEBUG: Playpath : mp4:c19/s/ve2175163/video.mp4
[rtmpdump] DEBUG: tcUrl    : rtmpe://cp150757.edgefcs.net:1935/ondemand/?auth=daEcabLavaEaUakdZcncHdbaQa9cecXbwc_-bw.2o5-dHa-lBKwmqHADuu&aifp=0009&slist=c19/s/ve2175163/video.mp4
[rtmpdump] DEBUG: app      : ondemand/?auth=daEcabLavaEaUakdZcncHdbaQa9cecXbwc_-bw.2o5-dHa-lBKwmqHADuu&aifp=0009&slist=c19/s/ve2175163/video.mp4
[rtmpdump] DEBUG: live     : no
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: Setting buffer time to: 36000000ms
[rtmpdump] Connecting ...
[rtmpdump] DEBUG: RTMP_Connect1, ... connected, handshaking
[rtmpdump] DEBUG: HandShake: Client type: 06
[rtmpdump] DEBUG: HandShake: DH pubkey position: 472
[rtmpdump] DEBUG: HandShake: Client digest offset: 1383
[rtmpdump] DEBUG: HandShake: Initial client digest: 
[rtmpdump] DEBUG: d3 e6 c2 b4 96 16 54 fe 8a 7b 14 e7 e7 0c 3d a7
[rtmpdump] DEBUG: 12 3b bb df 1b 56 8c 36 92 6b 60 6b ca e3 69 9e
[rtmpdump] DEBUG: HandShake: Type Answer   : 08
[rtmpdump] WARNING: HandShake: Type mismatch: client sent 6, server answered 8
[rtmpdump] DEBUG: HandShake: Server Uptime : 1366643713
[rtmpdump] DEBUG: HandShake: FMS Version   : 5.0.7.1
[rtmpdump] DEBUG: HandShake: Server DH public key offset: 579
[rtmpdump] DEBUG: HandShake: Secret key: 
[rtmpdump] DEBUG: 60 06 79 76 7e 45 d4 6e 10 6c b7 fd e4 c5 bd e4
[rtmpdump] DEBUG: 1c 14 48 5f 94 a8 bc 59 83 3f 8c 40 9e 94 ca d9
[rtmpdump] DEBUG: a6 41 53 84 90 9b eb 93 b5 f1 42 17 33 1d a0 c0
[rtmpdump] DEBUG: b0 68 21 38 6b 24 6f 0e 66 40 38 80 6e ae c8 e5
[rtmpdump] DEBUG: 2f 92 6e 27 36 06 d5 de b8 19 be 0d ec 63 8d 48
[rtmpdump] DEBUG: a4 1a 66 50 ca e5 05 8a a2 4d 66 32 18 48 da 4b
[rtmpdump] DEBUG: c8 d4 8f 05 3d 34 60 10 7e 63 da ff 02 d2 1b 6c
[rtmpdump] DEBUG: 25 e0 c1 41 a8 9b bd 91 20 63 ed f6 b2 75 57 6e
[rtmpdump] DEBUG: RC4 Out Key: 
[rtmpdump] DEBUG: 91 49 dc 08 90 42 05 0a 91 9e 90 d6 ec a9 49 2c
[rtmpdump] DEBUG: RC4 In Key: 
[rtmpdump] DEBUG: 1e bc 4c 45 3d b8 b3 a4 c0 1a f0 a1 82 ff 3c 71
[rtmpdump] DEBUG: HandShake: Calculated digest key from secure key and server digest: 
[rtmpdump] DEBUG: 58 7a 38 37 7b 50 8c dc 96 ba 10 22 ff 50 08 fd
[rtmpdump] DEBUG: 0c 52 4a 14 3f 9c 38 0d 16 61 64 e7 49 34 1a 75
[rtmpdump] DEBUG: HandShake: Client signature calculated:
[rtmpdump] DEBUG: d9 20 dd 72 aa 75 c1 4a 34 74 9a a5 e5 1c 37 6e
[rtmpdump] DEBUG: 20 29 5a 0c f8 f8 38 b7 27 70 f9 fb aa 61 4b c1
[rtmpdump] DEBUG: HandShake: Server sent signature:
[rtmpdump] DEBUG: 83 cf d3 ca 41 11 a8 be a3 a6 98 6c 9e 66 fd 07
[rtmpdump] DEBUG: 6e ac f1 8e 24 61 75 a8 d0 15 28 86 71 af a4 df
[rtmpdump] DEBUG: HandShake: Digest key: 
[rtmpdump] DEBUG: 1c 30 e9 a4 94 69 17 63 58 d4 19 fd ea b5 02 33
[rtmpdump] DEBUG: 2d c8 74 67 ee 2d 8b df 8e c7 d8 f1 eb c5 4e a3
[rtmpdump] DEBUG: HandShake: Signature calculated:
[rtmpdump] DEBUG: 83 cf d3 ca 41 11 a8 be a3 a6 98 6c 9e 66 fd 07
[rtmpdump] DEBUG: 6e ac f1 8e 24 61 75 a8 d0 15 28 86 71 af a4 df
[rtmpdump] DEBUG: HandShake: Genuine Adobe Flash Media Server
[rtmpdump] DEBUG: HandShake: Handshaking finished....
[rtmpdump] DEBUG: RTMP_Connect1, handshaked
[rtmpdump] DEBUG: Invoking connect
[rtmpdump] INFO: Connected...
[rtmpdump] DEBUG: HandleServerBW: server BW = 1250000
[rtmpdump] DEBUG: HandleClientBW: client BW = 1250000 2
[rtmpdump] DEBUG: HandleChangeChunkSize, received: chunk size change to 4096
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 242 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:             fmsVer, STRING:	FMS/5,0,7,7054>
[rtmpdump] DEBUG: Property: <Name:       capabilities, NUMBER:	127.00>
[rtmpdump] DEBUG: Property: <Name:               mode, NUMBER:	1.00>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:              level, STRING:	status>
[rtmpdump] DEBUG: Property: <Name:               code, STRING:	NetConnection.Connect.Success>
[rtmpdump] DEBUG: Property: <Name:        description, STRING:	Connection succeeded.>
[rtmpdump] DEBUG: Property: <Name:     objectEncoding, NUMBER:	0.00>
[rtmpdump] DEBUG: Property: <Name:               data, ECMA_ARRAY>
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:            version, STRING:	5,0,7,7054>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_result>
[rtmpdump] DEBUG: HandleInvoke, received result for method call <connect>
[rtmpdump] DEBUG: sending ctrl. type: 0x0003
[rtmpdump] DEBUG: Invoking createStream
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 21 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <onBWDone>
[rtmpdump] DEBUG: Invoking _checkbw
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 29 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_result>
[rtmpdump] DEBUG: HandleInvoke, received result for method call <createStream>
[rtmpdump] DEBUG: SendPlay, seekTime=0, stopTime=0, sending play: mp4:c19/s/ve2175163/video.mp4
[rtmpdump] DEBUG: Invoking play
[rtmpdump] DEBUG: sending ctrl. type: 0x0003
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 10275 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_onbwcheck>
[rtmpdump] DEBUG: Invoking _result
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 20515 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_onbwcheck>
[rtmpdump] DEBUG: Invoking _result
[rtmpdump] DEBUG: HandleCtrl, received ctrl. type: 4, len: 6
[rtmpdump] DEBUG: HandleCtrl, Stream IsRecorded 1
[rtmpdump] DEBUG: HandleChangeChunkSize, received: chunk size change to 4096
[rtmpdump] DEBUG: HandleCtrl, received ctrl. type: 0, len: 6
[rtmpdump] DEBUG: HandleCtrl, Stream Begin 1
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 192 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:              level, STRING:	status>
[rtmpdump] DEBUG: Property: <Name:               code, STRING:	NetStream.Play.Reset>
[rtmpdump] DEBUG: Property: <Name:        description, STRING:	Playing and resetting c19/s/ve2175163/video.mp4.>
[rtmpdump] DEBUG: Property: <Name:            details, STRING:	c19/s/ve2175163/video.mp4>
[rtmpdump] DEBUG: Property: <Name:           clientid, STRING:	qAAPAJTA>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <onStatus>
[rtmpdump] DEBUG: HandleInvoke, onStatus: NetStream.Play.Reset
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 186 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:              level, STRING:	status>
[rtmpdump] DEBUG: Property: <Name:               code, STRING:	NetStream.Play.Start>
[rtmpdump] DEBUG: Property: <Name:        description, STRING:	Started playing c19/s/ve2175163/video.mp4.>
[rtmpdump] DEBUG: Property: <Name:            details, STRING:	c19/s/ve2175163/video.mp4>
[rtmpdump] DEBUG: Property: <Name:           clientid, STRING:	qAAPAJTA>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <onStatus>
[rtmpdump] DEBUG: HandleInvoke, onStatus: NetStream.Play.Start
[rtmpdump] Starting download at: 0.000 kB
[rtmpdump] DEBUG: RTMP_ClientPacket, received: notify 24 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: ignoring too small audio packet: size: 0
[rtmpdump] DEBUG: RTMP_ClientPacket, received: notify 44 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:               code, STRING:	NetStream.Data.Start>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: RTMP_ClientPacket, received: notify 494 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:           duration, NUMBER:	1421.50>
[rtmpdump] DEBUG: Property: <Name:       moovPosition, NUMBER:	32.00>
[rtmpdump] DEBUG: Property: <Name:              width, NUMBER:	848.00>
[rtmpdump] DEBUG: Property: <Name:             height, NUMBER:	480.00>
[rtmpdump] DEBUG: Property: <Name:       videocodecid, STRING:	avc1>
[rtmpdump] DEBUG: Property: <Name:       audiocodecid, STRING:	mp4a>
[rtmpdump] DEBUG: Property: <Name:         avcprofile, NUMBER:	77.00>
[rtmpdump] DEBUG: Property: <Name:           avclevel, NUMBER:	31.00>
[rtmpdump] DEBUG: Property: <Name:             aacaot, NUMBER:	2.00>
[rtmpdump] DEBUG: Property: <Name:     videoframerate, NUMBER:	23.98>
[rtmpdump] DEBUG: Property: <Name:    audiosamplerate, NUMBER:	44100.00>
[rtmpdump] DEBUG: Property: <Name:      audiochannels, NUMBER:	2.00>
[rtmpdump] DEBUG: Property: <Name:          trackinfo, STRICT_ARRAY>
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:             length, NUMBER:	17040000.00>
[rtmpdump] DEBUG: Property: <Name:          timescale, NUMBER:	11988.00>
[rtmpdump] DEBUG: Property: <Name:           language, STRING:	und>
[rtmpdump] DEBUG: Property: <Name:  sampledescription, STRICT_ARRAY>
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:         sampletype, STRING:	avc1>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:             length, NUMBER:	62688256.00>
[rtmpdump] DEBUG: Property: <Name:          timescale, NUMBER:	44100.00>
[rtmpdump] DEBUG: Property: <Name:           language, STRING:	und>
[rtmpdump] DEBUG: Property: <Name:  sampledescription, STRICT_ARRAY>
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:         sampletype, STRING:	mp4a>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] INFO: Metadata:
[rtmpdump] INFO:   duration              1421.50
[rtmpdump] INFO:   moovPosition          32.00
[rtmpdump] INFO:   width                 848.00
[rtmpdump] INFO:   height                480.00
[rtmpdump] INFO:   videocodecid          avc1
[rtmpdump] INFO:   audiocodecid          mp4a
[rtmpdump] INFO:   avcprofile            77.00
[rtmpdump] INFO:   avclevel              31.00
[rtmpdump] INFO:   aacaot                2.00
[rtmpdump] INFO:   videoframerate        23.98
[rtmpdump] INFO:   audiosamplerate       44100.00
[rtmpdump] INFO:   audiochannels         2.00
[rtmpdump] INFO: trackinfo:
[rtmpdump] INFO:   length                17040000.00
[rtmpdump] INFO:   timescale             11988.00
[rtmpdump] INFO:   language              und
[rtmpdump] INFO: sampledescription:
[rtmpdump] INFO:   sampletype            avc1
[rtmpdump] INFO:   length                62688256.00
[rtmpdump] INFO:   timescale             44100.00
[rtmpdump] INFO:   language              und
[rtmpdump] INFO: sampledescription:
[rtmpdump] INFO:   sampletype            mp4a
[download] 1.45KiB at Unknown speed (00:01)
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 30755 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_onbwcheck>
[rtmpdump] DEBUG: Invoking _result
[download]   0.2% of ~127.15MiB at Unknown speed ETA Unknown ETA
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 40995 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_onbwcheck>
[rtmpdump] DEBUG: Invoking _result
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 51235 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_onbwcheck>
[rtmpdump] DEBUG: Invoking _result
[download]   0.4% of ~141.70MiB at 209.22KiB/s ETA 12:41
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 61475 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_onbwcheck>
[rtmpdump] DEBUG: Invoking _result
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 71717 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_onbwcheck>
[rtmpdump] DEBUG: Invoking _result
[download]   0.4% of ~172.95MiB at 248.71KiB/s ETA 14:57
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 81957 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_onbwcheck>
[rtmpdump] DEBUG: Invoking _result
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 92197 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_onbwcheck>
[rtmpdump] DEBUG: Invoking _result
[download]   0.4% of ~219.83MiB at 308.38KiB/s ETA 17:13
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 102437 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_onbwcheck>
[rtmpdump] DEBUG: Invoking _result
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 112677 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_onbwcheck>
[rtmpdump] DEBUG: Invoking _result
[download]   0.5% of ~213.36MiB at 340.15KiB/s ETA 13:31
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 122917 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_onbwcheck>
[rtmpdump] DEBUG: Invoking _result
[download]   0.7% of ~170.26MiB at 364.35KiB/s ETA 08:43
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 133157 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_onbwcheck>
[rtmpdump] DEBUG: Invoking _result
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 40 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_onbwdone>
[download]  99.8% of ~147.70MiB at  1.19MiB/s ETA 00:00
[rtmpdump] DEBUG: ignoring too small audio packet: size: 0
[rtmpdump] DEBUG: RTMP_ClientPacket, received: notify 102 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:               code, STRING:	NetStream.Play.Complete>
[rtmpdump] DEBUG: Property: <Name:              level, STRING:	status>
[rtmpdump] DEBUG: Property: <Name:           duration, NUMBER:	123.00>
[rtmpdump] DEBUG: Property: <Name:              bytes, NUMBER:	154691484.00>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleCtrl, received ctrl. type: 1, len: 6
[rtmpdump] DEBUG: HandleCtrl, Stream EOF 1
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 196 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:              level, STRING:	status>
[rtmpdump] DEBUG: Property: <Name:               code, STRING:	NetStream.Play.Stop>
[rtmpdump] DEBUG: Property: <Name:        description, STRING:	Stopped playing c19/s/ve2175163/video.mp4.>
[rtmpdump] DEBUG: Property: <Name:            details, STRING:	c19/s/ve2175163/video.mp4>
[rtmpdump] DEBUG: Property: <Name:           clientid, STRING:	qAAPAJTA>
[rtmpdump] DEBUG: Property: <Name:             reason, STRING:	>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <onStatus>
[rtmpdump] DEBUG: HandleInvoke, onStatus: NetStream.Play.Stop
[rtmpdump] DEBUG: Invoking deleteStream
[rtmpdump] DEBUG: Got Play.Complete or Play.Stop from server. Assuming stream is complete
[download]  99.9% of ~147.67MiB at  1.19MiB/s ETA 00:00
[rtmpdump] DEBUG: RTMP_Read returned: 0
[rtmpdump] Download complete
[rtmpdump] DEBUG: Closing connection.
[rtmpdump] 154692461 bytes
[download] 100% of 147.53MiB

```
An interesting point to note though is that on version `2015.06.04.1` as available from the ubuntu 15.10 repository the subtitles list correctly and download. The `2016.03.27` version as mentioned previously does not. The `2016.03.27` version also clearly handles the naming of cruncyroll videos differently as the output video file is named `GATE Episode 23 – Paradrop-692655.flv` whereas the `2015.06.04.1` version names the same video `Crunchyroll-692655.flv`. 

##### The following is the `2015.06.04.1` version successful output:
```
$ youtube-dl --list-subs -v http://www.crunchyroll.com/gate/episode-23-paradrop-692655
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--list-subs', u'-v', u'http://www.crunchyroll.com/gate/episode-23-paradrop-692655']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.06.04.1
[debug] Python version 2.7.10 - Linux-4.2.0-34-generic-x86_64-with-Ubuntu-15.10-wily
[debug] exe versions: avconv 2.7.6-0ubuntu0.15.10.1, avprobe 2.7.6-0ubuntu0.15.10.1, ffmpeg 2.7.6-0ubuntu0.15.10.1, ffprobe 2.7.6-0ubuntu0.15.10.1, rtmpdump 2.4
[debug] Proxy map: {}
[Crunchyroll] 692655: Downloading webpage
[Crunchyroll] 692655: Downloading media info
[Crunchyroll] 692655: Downloading media info for 360p
[Crunchyroll] 692655: Downloading media info for 480p
[Crunchyroll] 692655: Downloading media info for 720p
[Crunchyroll] 692655: Downloading media info for 720p
[Crunchyroll] 692655: Downloading media info for 1080p
[Crunchyroll] 692655: Downloading media info for 1080p
[Crunchyroll] 692655: Downloading subtitles for English (US)
[Crunchyroll] 692655: Downloading subtitles for Español
[Crunchyroll] 692655: Downloading subtitles for Español (España)
[Crunchyroll] 692655: Downloading subtitles for Português (Brasil)
[Crunchyroll] 692655: Downloading subtitles for العربية
[Crunchyroll] 692655: Downloading subtitles for Deutsch
Available subtitles for 692655:
Language formats
esES     ass, srt
deDE     ass, srt
esLA     ass, srt
enUS     ass, srt
arME     ass, srt
ptBR     ass, srt
```
I chose this specific video for the issue as it does not require a login to view (please note that dues to the nature of the site it may be unavailable in certain locations but there's nothing I can do about that). 

My thoughts are that somewhere in the code the `2016.03.27` version of youtube-dl attempts to handle the subtitle urls differently than the `2015.06.04.1` version, at which point it encounters an error and crashes.

You should be able to recreate the circumstances with the information from the verbose output of the commands so I'm not sure what else I could offer. though I'd be more than happy to try and supply any additional information I can.

**Comment by JohnPeel** [comment]
Just going to note the current master has this fixed. (https://github.com/rg3/youtube-dl/commit/33f3040a3e611f45ad920bd06030691910ddf815)

**Comment by JCDoesTech** [comment]
Oh, OK, thank you. Do I have to wait for the next release or can I compile it now? (I'm new to github and am not sure whether just compiling what's here will work, it's probably not recommended even if it would technically work)

**Comment by dstftw** [comment]
This issue is already fixed and fix will be incorporated in the next version of youtube-dl.
