### ISSUE TITLE
Download on Streamcloud fail

### ISSUE THREAD

**Issue by cc-carlchen** [rg3/youtube-dl#9055]
Hello at all, 

since the two last updates I have the problem, that I can't download videos from streamcloud.eu and hope maybe it could fix it for the next update? 

Here are the verbose:

youtube-dl --verbose http://streamcloud.eu/p0637rgrq3rh/Detektiv.Conan.235.Der.junge.Meisterdieb.-.Teil.1.avi.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://streamcloud.eu/p0637rgrq3rh/Detektiv.Conan.235.Der.junge.Meisterdieb.-.Teil.1.avi.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.03.27
[debug] Python version 2.7.9 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.3
[debug] exe versions: avconv 11.6-6, avprobe 11.6-6, rtmpdump 2.4
[debug] Proxy map: {}
[streamcloud.eu] p0637rgrq3rh: Downloading webpage
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 419, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 409, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1724, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 669, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 321, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/streamcloud.py", line 40, in _real_extract
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1796, in urlencode_postdata
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 195, in compat_urllib_parse_urlencode
  File "/usr/lib/python2.7/urllib.py", line 1324, in urlencode
    raise TypeError
TypeError: not a valid non-string sequence or mapping object

Friendly regards
Carlchen

**Comment by yan12125** [comment]
Now streamcloud.eu always gives HTTP 404 Not Found. Is this site still working for you?

**Comment by cc-carlchen** [comment]
Hi, 

yes Streamcloud.eu works on my Iceweasel Browser. But still not working with youtube-dl latest version. 

Friendly regards
Carlchen

**Comment by yan12125** [comment]
Alright it's goerestricted. Confirmed the bug with Python 2.7 and an UK proxy.

**Comment by cc-carlchen** [comment]
Hi, 

allright, I use Debian stable, the newest version of Python is on Jessie 2.7.9-1. Maybe it could be fixed the problem with a new update version in the future. :-) 

Thanks a lot. 

Friendly regards
Carlchen

**Comment by yan12125** [comment]
Such bugs are fixed and will be available in the next version. Thanks for the report!

**Comment by cc-carlchen** [comment]
Hi yan12125,

I have to thanks, for the great and speedy help. Thank you very much. 

Friendly regards
Carlchen
