### ISSUE TITLE
Site Support Request Stan.com.au

### ISSUE THREAD

**Issue by 2wenty2wo** [rg3/youtube-dl#9068]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.04.01*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.04.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

youtube-dl -v https://play.stan.com.au/programs/387127/play
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://play.stan.com.au/programs/387127/play']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.04.01
[debug] Python version 2.7.11 - Darwin-15.2.0-x86_64-i386-64bit
[debug] exe versions: rtmpdump 2.4
[debug] Proxy map: {}
[generic] play: Requesting header
WARNING: Falling back on generic information extractor.
[generic] play: Downloading webpage
[generic] play: Extracting information
ERROR: Unsupported URL: https://play.stan.com.au/programs/387127/play
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1348, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 278, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=etree.TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 267, in _XML
    parser.feed(text)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: mismatched tag: line 5, column 1198
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 669, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 323, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2012, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://play.stan.com.au/programs/387127/play

This is a video page: https://play.stan.com.au/programs/387127/play
This is another video page: https://play.stan.com.au/programs/387128/play

**Comment by 2wenty2wo** [comment]
Since this website needs an account, is there something I can do or pull from the website that would be of any help?

**Comment by Artic0din** [comment]
@jaimeMF has there been any update on adding this site to the support list?

**Comment by joeynotjoe** [comment]
I would love to get this added as well.

**Comment by ObscenityIB** [comment]
just tried with cookies and everything, no formats found

**Comment by ObscenityIB** [comment]
update, successfully downloaded with ffmpeg, but its encrypted, glitchy video stream and silent audio stream

**Comment by Artic0din** [comment]
@ObscenityIB how did you go about that? How did you go about putting in your credentials?

**Comment by ObscenityIB** [comment]
> 
> 
> @ObscenityIB how did you go about that? How did you go about putting in your credentials?

netscape cookie file

**Comment by moffz0r** [comment]
So is there nothing more that can be done here? I have a login I am willing to share if anyone can help us with this.

**Comment by huxnlk** [comment]
Has anyone had any luck getting full streams from Stan?

**Comment by mario872** [comment]
I'm still pretty new to this but using chrome dev tools I found that Stan seems to use a .mpd file, although both yt-dlp and dash-mpd-cli fail to download it. VLC can accurately get the length of the video, but that's it.
Here's the link to one such .mpd file: 
https://api.stan.com.au/manifest/v1/dash/web.mpd?url=https%3A%2F%2F709-stan.akamaized.net%2F09%2Fdash%2Flive%2F406839A-4%2Fsd%2Fsdr%2Fmaster_h264-5efa8b5f.mpd%3Fcdns%3Dgoogle%252Cbandaid%26clearaudio%3Dtrue%26maxQuality%3Dsd&audioType=all&livecaptions=true&captionsUrl=https%3A%2F%2Fapi.stan.com.au%2Fmanifest%2Fv1%2Fvtt%2Fweb.vtt%3Ftype%3Dchrome%26url%3Dhttps%253A%252F%252Fstreamcott-a.akamaihd.net%252F406839A-1%252Feng.vtt&captionsLang=eng&version=126&trickmode=true

**Comment by 3052** [comment]
I have a Stan tool, but as mentioned it needs an account, and depending on which CDN you choose geo blocking is used as well

**Comment by dirkf** [comment]
The linked MPD specifies PlayReady DRM. Unless someone shows a page whose video plays in a browser with DRM disabled, the issue will be closed.

**Comment by 3052** [comment]
not sure about PlayReady, but yeah from my testing they for sure use Widevine across the board
