### ISSUE TITLE
 Site Support Request could not download from iqiyi An extractor error has occurred. (caused by KeyError(u'data',))

### ISSUE THREAD

**Issue by wanghaisheng** [rg3/youtube-dl#9071]
```
  ~ youtube-dl -v   http://www.iqiyi.com/v_19rrl0274k.html\?vfm\=2008_aldbd\&fv\=p_02_01\&bvfm\=videolocal
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.iqiyi.com/v_19rrl0274k.html?vfm=2008_aldbd&fv=p_02_01&bvfm=videolocal']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.04.01
[debug] Python version 2.7.10 - Darwin-15.3.0-x86_64-i386-64bit
[debug] exe versions: avconv 11.4, avprobe 11.4, ffmpeg 3.0, ffprobe 3.0
[debug] Proxy map: {}
[iqiyi] temp_id: download video page
[iqiyi] b292967951caee85a84be0cdae7ddffa: Downloading JSON metadata
[iqiyi] b292967951caee85a84be0cdae7ddffa: Downloading video authentication JSON
ERROR: An extractor error has occurred. (caused by KeyError(u'data',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 323, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/iqiyi.py", line 569, in _real_extract
    data, video_id, _uuid, tvid)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/iqiyi.py", line 452, in construct_video_urls
    't': auth_result['data']['t'],
KeyError: u'data'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 669, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 329, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
ExtractorError: An extractor error has occurred. (caused by KeyError(u'data',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

➜  ~ 

```

**Comment by yan12125** [comment]
Thanks for the report. This video requires a VIP account. You need to pass credentials to youtube-dl via ```--username``` and ```--pasword``` or ```--netrc```, or wait until this video is unlocked for non-VIP users. In the next version a better message will be shown insteada of confusing ```KeyError```.
