### ISSUE TITLE
Error: Unable to extract thumbnail   -  RTEplayer (files downloaded yesterday fail today)

### ISSUE THREAD

**Issue by gitane1** [rg3/youtube-dl#9085]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.04.01*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.04.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

[C:\Documents and Settings\adult\Local Settings\Temp\3\wget-1.16]youtube-dl --ve
rbose "http://www.rte.ie/player/ie/show/rte-news-special-1516/10554922/"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.rte.ie/player/ie/show/rte
-news-special-1516/10554922/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.04.01
[debug] Python version 2.7.10 - Windows-XP-5.1.2600-SP3
[debug] exe versions: none
[debug] Proxy map: {}
[rte] 10554922: Downloading webpage
ERROR: Unable to extract thumbnail; please report this issue on https://yt-dl.or
g/bug . Make sure you are using the latest version; type  youtube-dl -U  to upda
te. Be sure to call youtube-dl with the --verbose flag and include its complete
output.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 669, in extract_info
  File "youtube_dl\extractor\common.pyo", line 323, in extract
  File "youtube_dl\extractor\rte.pyo", line 43, in _real_extract
  File "youtube_dl\extractor\common.pyo", line 627, in _search_regex
RegexNotFoundError: Unable to extract thumbnail; please report this issue on htt
ps://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-d
l -U  to update. Be sure to call youtube-dl with the --verbose flag and include
its complete output.

<end of log>
```

### Description of your *issue*, suggested solution and other information

Several files downloaded successfully yesterday from RTEplayer but due to their size could not save all of the files onto removable storage from public access PC network. Today was unable to download any of the same files on the same public network with the same software and settings unchanged, getting the "thumbnail" error message every time.

Thanks for any advice :)

**Comment by gitane1** [comment]
Outstanding blazing turnaround many thanks :)
