### ISSUE TITLE
Support for clip.rs

### ISSUE THREAD

**Issue by vBm** [rg3/youtube-dl#9099]
### What is the purpose of your *issue*?
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.04.06**
- [x] Site support request (request for adding support for a new site)

---
```
λ youtube-dl --version
2016.04.06
λ youtube-dl -v http://www.clip.rs/premijera-frajle-predstavljaju-novi-spot-za-pesmu-moli-me-moli/3732
[debug] System config: []
[debug] User config: [u'--no-check-certificate']
[debug] Command-line args: [u'-v', u'http://www.clip.rs/premijera-frajle-predstavljaju-novi-spot-za-pesmu-moli-me-moli/3732']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.04.06
[debug] Python version 2.7.11 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-50911-g9efcfbe, ffprobe N-78313-g6632802
[debug] Proxy map: {}
[generic] 3732: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 3732: Downloading webpage
[generic] 3732: Extracting information
ERROR: Unsupported URL: http://www.clip.rs/premijera-frajle-predstavljaju-novi-spot-za-pesmu-moli-me-moli/3732
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\youtube_dl\extractor\generic.py", line 1348, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "c:\python27\lib\site-packages\youtube_dl\compat.py", line 279, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=etree.TreeBuilder(element_factory=_element_factory)))
  File "c:\python27\lib\site-packages\youtube_dl\compat.py", line 268, in _XML
    parser.feed(text)
  File "c:\python27\lib\xml\etree\ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "c:\python27\lib\xml\etree\ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 32, column 121
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 669, in extract_info
    ie_result = ie.extract(url)
  File "c:\python27\lib\site-packages\youtube_dl\extractor\common.py", line 323, in extract
    return self._real_extract(url)
  File "c:\python27\lib\site-packages\youtube_dl\extractor\generic.py", line 2012, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.clip.rs/premijera-frajle-predstavljaju-novi-spot-za-pesmu-moli-me-moli/3732
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://www.clip.rs/premijera-frajle-predstavljaju-novi-spot-za-pesmu-moli-me-moli/3732
- Single video: http://www.clip.rs/vojni-orkestar-u-knez-mihailovoj/2330
- Playlist: none

**Comment by vBm** [comment]
Thank you. Works like a charm.
