### ISSUE TITLE
Can not download VRDC video with latest version

### ISSUE THREAD

**Issue by Farl** [rg3/youtube-dl#9114]
GDCVault is out recently. I can download GDC video correctly.
However, I can't download the new VRDC content by latest version youtube-dl
Below is my verbose
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://www.gdcvault.com/play/1023671/Lessons-Learn
ed-from-I-Expect', u'--output', u'\\\\192.168.1.137\\GDCVault\\GDC 2016\\%(title
)s -%(id)s.%(ext)s', u'--username', u'PRIVATE', u'--password', u'PRIVATE', u'-v'
]
[debug] Encodings: locale cp950, fs mbcs, out cp950, pref cp950
[debug] youtube-dl version 2016.04.06
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[GDCVault] Lessons-Learned-from-I-Expect: Downloading webpage
[GDCVault] Lessons-Learned-from-I-Expect: Logging in
[GDCVault] Lessons-Learned-from-I-Expect: Getting authenticated video page
[GDCVault] Lessons-Learned-from-I-Expect: Logging out
ERROR: Unable to extract xml root; please report this issue on https://yt-dl.org
/bug . Make sure you are using the latest version; type  youtube-dl -U  to updat
e. Be sure to call youtube-dl with the --verbose flag and include its complete o
utput.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 669, in extract_info
  File "youtube_dl\extractor\common.pyo", line 323, in extract
  File "youtube_dl\extractor\gdcvault.pyo", line 175, in _real_extract
  File "youtube_dl\extractor\common.pyo", line 636, in _html_search_regex
  File "youtube_dl\extractor\common.pyo", line 627, in _search_regex
RegexNotFoundError: Unable to extract xml root; please report this issue on http
s://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl
 -U  to update. Be sure to call youtube-dl with the --verbose flag and include i
ts complete output.
```

**Comment by Farl** [comment]
Thanks dstftw!
When will this fix build in latest build?

**Comment by dstftw** [comment]
No ETA.
