### ISSUE TITLE
TV2 doesn't work for sumo.tv2.no

### ISSUE THREAD

**Issue by infSup33** [rg3/youtube-dl#9130]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.04.06*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.04.06**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [x] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
qp:TV2 Trox$ youtube-dl --verbose https://sumo.tv2.no/c-more/c-more-filmer/beck-den-siste-dagen-1032154.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://sumo.tv2.no/c-more/c-more-filmer/beck-den-siste-dagen-1032154.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.04.06
[debug] Python version 2.7.11 - Darwin-15.3.0-x86_64-i386-64bit
[debug] exe versions: avconv 11.4, avprobe 11.4, ffmpeg 3.0.1, ffprobe 3.0.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] beck-den-siste-dagen-1032154: Requesting header
WARNING: Falling back on generic information extractor.
[generic] beck-den-siste-dagen-1032154: Downloading webpage
[generic] beck-den-siste-dagen-1032154: Extracting information
ERROR: Unsupported URL: https://sumo.tv2.no/c-more/c-more-filmer/beck-den-siste-dagen-1032154.html
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1348, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 279, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=etree.TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 268, in _XML
    parser.feed(text)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: syntax error: line 1, column 0
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 669, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 323, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2012, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://sumo.tv2.no/c-more/c-more-filmer/beck-den-siste-dagen-1032154.html
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://sumo.tv2.no/c-more/c-more-filmer/beck-den-siste-dagen-1032154.html

---

### Description of your *issue*, suggested solution and other information

You support tv2.no, but when I try to download a video from sumo.tv2.no, I get an unsupported URL error.

**Comment by thomerl** [comment]
There are one series that doesn't require login, unsure about geo-restriction tho. But would be nice to get a working extractor for sumo.tv2.no. Here are the one that is available without an account: https://sumo.tv2.no/programmer/humor/kollektivet/

**Comment by yiveynod** [comment]
Hi! I'm very new to this program and have very little to no knowledge on how to write code but I'd like to solve this. I'm running Youtube-dl 2020.01.24 on macOS 10.13.6. 
sumo.tv2.no don't download, I only get:

> Kim-MBP:~ Kim$ youtube-dl https://sumo.tv2.no/programmer/serier/vill-i-hjertet/sesong-1/vill-i-hjertet-1-episode-1-1523209.html?showPlayer=true
> [generic] vill-i-hjertet-1-episode-1-1523209: Requesting header
> WARNING: Falling back on generic information extractor.
> [generic] vill-i-hjertet-1-episode-1-1523209: Downloading webpage
> [generic] vill-i-hjertet-1-episode-1-1523209: Extracting information
> ERROR: Unsupported URL: https://sumo.tv2.no/programmer/serier/vill-i-hjertet/sesong-1/vill-i-hjertet-1-episode-1-1523209.html?showPlayer=true

How can I help? The video is not geo restricted as far as I can see (I'm in Sweden and not running a VPN for this). I've got a free login also but the video can be played without being logged in.

**Comment by ijbh** [comment]
Hi. Is it possible to get support for this site?

**Comment by 89z** [comment]
Issue should be closed, URL is dead

**Comment by yiveynod** [comment]
> Issue should be closed, URL is dead

Site is DRM protected, and changed name from TV2 Sumo to TV2 Play.
