### ISSUE TITLE
XML error on www.rai.it download

### ISSUE THREAD

**Issue by pkirk** [rg3/youtube-dl#9157]
Both on my OSX and on Linux Debian 7, the same error.

youtube-dl http://www.report.rai.it/dl/Report/puntata/ContentItem-2af9e702-92c6-4612-8139-33aed9979ef8.html
[Rai] 2af9e702-92c6-4612-8139-33aed9979ef8: Downloading webpage
[RaiTV] 78a62133-1ae6-46ba-be73-b7e7a3c6dea3: Downloading video JSON
[RaiTV] 78a62133-1ae6-46ba-be73-b7e7a3c6dea3: Downloading XML
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 419, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 409, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1725, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 680, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 732, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 669, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 323, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/rai.py", line 111, in _real_extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 507, in _download_xml
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 279, in compat_etree_fromstring
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 269, in _XML
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1655, in close
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1507, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: syntax error: line 1, column 0`

**Comment by badpenguin** [comment]
Same here:

youtube-dl -F http://www.rai.tv/dl/RaiTV/programmi/media/ContentItem-5c781d67-83d8-49cf-a418-28440d12441c.html
[RaiTV] 5c781d67-83d8-49cf-a418-28440d12441c: Downloading video JSON
[RaiTV] 5c781d67-83d8-49cf-a418-28440d12441c: Downloading XML
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 419, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 409, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1730, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 671, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 341, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/rai.py", line 111, in _real_extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 524, in _download_xml
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 279, in compat_etree_fromstring
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 269, in _XML
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1654, in close
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: syntax error: line 1, column 0

**Comment by yan12125** [comment]
Thanks for the report and sorry for the delay. Rai will be fixed in the next version.
