### ISSUE TITLE
beeg 403 forbidden

### ISSUE THREAD

**Issue by campones** [rg3/youtube-dl#9168]
root@server:~/Downloads# youtube-dl -v http://beeg.com/8613291
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://beeg.com/8613291']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.04.06
[debug] Python version 2.7.6 - Linux-3.13.0-66-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: ffmpeg N-75403-g3a8e447, ffprobe N-75403-g3a8e447, rtmpdump 2.4
[debug] Proxy map: {}
[Beeg] 8613291: Downloading JSON metadata
[debug] Invoking downloader on u'https://video.beeg.com//key=.Ml@EiW+txyeldnnq@LBaM%2Cend=1460477717/720p/8613291.mp4'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1633, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1575, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 350, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 58, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1935, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden

**Comment by dstftw** [comment]
This issue is already fixed and fix will be incorporated in the next version of youtube-dl.

**Comment by campones** [comment]
ok sorry, thanks for your work
