### ISSUE TITLE
vevo.com videos fail from Germany

### ISSUE THREAD

**Issue by phihag** [rg3/youtube-dl#917]
From Germany, the vevo tests fail with

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://www.vevo.com/watch/hurts/somebody-to-die-for/GB1101300280', '-v']
[debug] youtube-dl version 2013.06.28
[debug] Git HEAD: 70d1924
[debug] Python version 2.7.5+ - Linux-3.4-trunk-amd64-x86_64-with-debian-jessie-sid
[debug] Proxy map: {}
[Vevo] GB1101300280: Downloading json info
[Vevo] GB1101300280: Downloading videos urls
[Vevo] GB1101300280: Extracting information
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/phihag/projects/youtube-dl/youtube_dl/__main__.py", line 18, in <module>
    youtube_dl.main()
  File "/home/phihag/projects/youtube-dl/youtube_dl/__init__.py", line 604, in main
    _real_main(argv)
  File "/home/phihag/projects/youtube-dl/youtube_dl/__init__.py", line 588, in _real_main
    retcode = ydl.download(all_urls)
  File "/home/phihag/projects/youtube-dl/youtube_dl/YoutubeDL.py", line 565, in download
    videos = self.extract_info(url)
  File "/home/phihag/projects/youtube-dl/youtube_dl/YoutubeDL.py", line 303, in extract_info
    ie_result = ie.extract(url)
  File "/home/phihag/projects/youtube-dl/youtube_dl/extractor/common.py", line 91, in extract
    return self._real_extract(url)
  File "/home/phihag/projects/youtube-dl/youtube_dl/extractor/vevo.py", line 24, in _real_extract
    video_info = json.loads(info_json)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

or (from another server)

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://www.vevo.com/watch/hurts/somebody-to-die-for/GB1101300280', '-v']
[debug] youtube-dl version 2013.06.28
[debug] Python version 2.7.5+ - Linux-3.0.68-x86_64-with-debian-jessie-sid
[debug] Proxy map: {}
[redirect] Following redirect to http://www.youtube.com/watch?v=Pt1kc_FniKM
[youtube] Setting language
[youtube] Pt1kc_FniKM: Downloading video webpage
[youtube] Pt1kc_FniKM: Downloading video info webpage
ERROR: YouTube said: Unfortunately, this video is not available in Germany because it may contain music for which GEMA has not granted the respective music rights.; please report this issue on GitHub.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/__init__.py", line 557, in _real_main
    cwd=os.path.dirname(os.path.abspath(__file__)))
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1308, in _execute_child
    raise child_exception
OSError: [Errno 20] Not a directory: '/usr/bin/youtube-dl/youtube_dl'
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 303, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 91, in extract
    return self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 394, in _real_extract
    raise ExtractorError(u'YouTube said: %s' % video_info['reason'][0])
ExtractorError: YouTube said: Unfortunately, this video is not available in Germany because it may contain music for which GEMA has not granted the respective music rights.; please report this issue on GitHub.
```
- [ ] Add a helper function to determine the country by IP(v4) address
- [ ] Allow to ignore tests based by locale (just emit a warning then)
- [ ] Ignore the vevo test
- [ ] Add a better error message for German users

**Comment by PotcFdk** [comment]
It should be noted that, at this time, I don't have any issues with that URL - the issue seems to be fixed.
