### ISSUE TITLE
[ytdl_hook] youtube-dl failed

### ISSUE THREAD

**Issue by uNouss** [rg3/youtube-dl#9173]
Hello i use mpv for watch lequipe21 channel and other. mpv use youtube-dl but since yesterday i have some issue like this 
![2016-04-12-225122_636x284_scrot](https://cloud.githubusercontent.com/assets/15982321/14475216/319fe956-0101-11e6-82fe-d398b729ffa7.png)

![2016-04-12-225200_636x542_scrot](https://cloud.githubusercontent.com/assets/15982321/14475223/3cb11be4-0101-11e6-847d-a4fba12e40ad.png)

**Comment by yan12125** [comment]
Please paste textual logs but not screenshots.

**Comment by uNouss** [comment]
@yan12125 ok 
```
unouss@YS:~$ youtube-dl -v -g https://www.dailymotion.com/embed/video/k4NQgz15Xuw3tKaCf1y?autoplay=autoplay
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', '-g', 'https://www.dailymotion.com/embed/video/k4NQgz15Xuw3tKaCf1y?autoplay=autoplay']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.04.06
[debug] Python version 3.4.3 - Linux-3.19.0-58-generic-i686-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.18-6, avprobe 9.18-6, ffmpeg N-79139-gde1a0d4, ffprobe N-79139-gde1a0d4, rtmpdump 2.4
[debug] Proxy map: {}
WARNING: Failed to download m3u8 information: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>
WARNING: Failed to download m3u8 information: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/youtube_dl/YoutubeDL.py", line 671, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.4/dist-packages/youtube_dl/extractor/common.py", line 341, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python3.4/dist-packages/youtube_dl/extractor/dailymotion.py", line 176, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/lib/python3.4/dist-packages/youtube_dl/extractor/common.py", line 862, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by yan12125** [comment]
This video is georestricted. Are you in France?

**Comment by uNouss** [comment]
@yan12125  yes i'm in France.

**Comment by dstftw** [comment]
They have misconfigured certificates. It does not work via SSL in browser due to the same reason. If you don't care you can use `--no-check-certificate` to disable certificate checking.
Closing since not a youtube-dl issue.
