### ISSUE TITLE
Tudou downloads not working

### ISSUE THREAD

**Issue by goonbag** [rg3/youtube-dl#9175]
Opening a new bug report as requested when I mentioned this on a seemingly related old issue.

**Verbose output for batch download:**
```
$ youtube-dl -v -a batch.txt
[debug] System config: []
[debug] User config: [u'-f', u'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best']
[debug] Command-line args: [u'-v', u'-a', u'batch.txt']
[debug] Batch file urls: [u'http://www.tudou.com/programs/view/B0zXrl9qXZY', u'http://www.tudou.com/programs/view/ZspnsxBJzbY', u'http://www.tudou.com/programs/view/mgwuvVDCsaU', u'http://www.tudou.com/programs/view/ot5D1pNDFIM', u'http://www.tudou.com/programs/view/fEnRKxFFkmk', u'http://www.tudou.com/programs/view/zBADqGfihGI', u'http://www.tudou.com/programs/view/nIrOE0nVcbY', u'http://www.tudou.com/programs/view/P8wekkJnQwk', u'http://www.tudou.com/programs/view/hmlh2L9lcxE', u'http://www.tudou.com/programs/view/-bDlVloIQYg', u'http://www.tudou.com/programs/view/zGx2OptJ4ws', u'http://www.tudou.com/programs/view/1-JCwAzlspQ', u'http://www.tudou.com/programs/view/jfecZsFRN7k', u'http://www.tudou.com/programs/view/YY5AuqtjAFQ', u'http://www.tudou.com/programs/view/vaqRUbunCRs', u'http://www.tudou.com/programs/view/FUXBJVCfcwc/', u'http://www.tudou.com/programs/view/yAxfWBu07mE/', u'http://www.tudou.com/programs/view/kYTBar21bFM/', u'http://www.tudou.com/programs/view/WmoxpYRaiXQ/', u'http://www.tudou.com/programs/view/r34_8nRiUAo/', u'http://www.tudou.com/programs/view/LiwU1f79ybw/', u'http://www.tudou.com/programs/view/cUTo3svdd00/', u'http://www.tudou.com/programs/view/cpZMREHIF-s/', u'http://www.tudou.com/programs/view/hperOU3gqtk/', u'http://www.tudou.com/programs/view/tJvtQo5rSi0/', u'http://www.tudou.com/programs/view/DyJCrWTFV6E/', u'http://www.tudou.com/programs/view/XQnes5_9Lkw/', u'http://www.tudou.com/programs/view/79wxMa6HpA4/', u'http://www.tudou.com/programs/view/aQ3SOGnxJeE/', u'http://www.tudou.com/programs/view/YUWPVg5CK10/', u'http://www.tudou.com/programs/view/nn6OpaPbdF8/', u'http://www.tudou.com/programs/view/QMYyJ3hX8GQ/', u'http://www.tudou.com/programs/view/yq30j-g6pGI/', u'http://www.tudou.com/programs/view/qMupVZn6qt4/', u'http://www.tudou.com/programs/view/TroP3Kz30jI/', u'http://www.tudou.com/programs/view/Ekz7QtcvQZ4/', u'http://www.tudou.com/programs/view/ZXUIucJLIOc/', u'http://www.tudou.com/programs/view/VuU525XYSHQ/', u'http://www.tudou.com/programs/view/SAULmZMqwn8/', u'http://www.tudou.com/programs/view/NvzHXv5OVjs/', u'http://www.tudou.com/programs/view/iG0KPsLYi4U/', u'http://www.tudou.com/programs/view/88SWB66Ions/', u'http://www.tudou.com/programs/view/1kHUQFG2oBQ/', u'http://www.tudou.com/programs/view/PM5qjlcJGnA/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.04.06
[debug] Python version 2.7.10 - Darwin-14.5.0-x86_64-i386-64bit
[debug] exe versions: avconv 11.4, avprobe 11.4, ffmpeg 2.8.3, ffprobe 2.8.3, rtmpdump 2.4
[debug] Proxy map: {}
[tudou] B0zXrl9qXZY: Downloading JSON metadata
[download] Downloading playlist: June 4 - Voice of Korea - Part 2
[tudou] 114473647: Opening the info XML page
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 419, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 409, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1725, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 680, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 799, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1706, in getslice
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/tudou.py", line 110, in part_func
AttributeError: 'NoneType' object has no attribute 'split'
```

Contents of batch.txt:
```
http://www.tudou.com/programs/view/B0zXrl9qXZY
http://www.tudou.com/programs/view/ZspnsxBJzbY
http://www.tudou.com/programs/view/mgwuvVDCsaU
http://www.tudou.com/programs/view/ot5D1pNDFIM
http://www.tudou.com/programs/view/fEnRKxFFkmk
http://www.tudou.com/programs/view/zBADqGfihGI
http://www.tudou.com/programs/view/nIrOE0nVcbY
http://www.tudou.com/programs/view/P8wekkJnQwk
http://www.tudou.com/programs/view/hmlh2L9lcxE
http://www.tudou.com/programs/view/-bDlVloIQYg
http://www.tudou.com/programs/view/zGx2OptJ4ws
http://www.tudou.com/programs/view/1-JCwAzlspQ
http://www.tudou.com/programs/view/jfecZsFRN7k
http://www.tudou.com/programs/view/YY5AuqtjAFQ
http://www.tudou.com/programs/view/vaqRUbunCRs
http://www.tudou.com/programs/view/FUXBJVCfcwc/
http://www.tudou.com/programs/view/yAxfWBu07mE/
http://www.tudou.com/programs/view/kYTBar21bFM/
http://www.tudou.com/programs/view/WmoxpYRaiXQ/
http://www.tudou.com/programs/view/r34_8nRiUAo/
http://www.tudou.com/programs/view/LiwU1f79ybw/
http://www.tudou.com/programs/view/cUTo3svdd00/
http://www.tudou.com/programs/view/cpZMREHIF-s/
http://www.tudou.com/programs/view/hperOU3gqtk/
http://www.tudou.com/programs/view/tJvtQo5rSi0/
http://www.tudou.com/programs/view/DyJCrWTFV6E/
http://www.tudou.com/programs/view/XQnes5_9Lkw/
http://www.tudou.com/programs/view/79wxMa6HpA4/
http://www.tudou.com/programs/view/aQ3SOGnxJeE/
http://www.tudou.com/programs/view/YUWPVg5CK10/
http://www.tudou.com/programs/view/nn6OpaPbdF8/
http://www.tudou.com/programs/view/QMYyJ3hX8GQ/
http://www.tudou.com/programs/view/yq30j-g6pGI/
http://www.tudou.com/programs/view/qMupVZn6qt4/
http://www.tudou.com/programs/view/TroP3Kz30jI/
http://www.tudou.com/programs/view/Ekz7QtcvQZ4/
http://www.tudou.com/programs/view/ZXUIucJLIOc/
http://www.tudou.com/programs/view/VuU525XYSHQ/
http://www.tudou.com/programs/view/SAULmZMqwn8/
http://www.tudou.com/programs/view/NvzHXv5OVjs/
http://www.tudou.com/programs/view/iG0KPsLYi4U/
http://www.tudou.com/programs/view/88SWB66Ions/
http://www.tudou.com/programs/view/1kHUQFG2oBQ/
http://www.tudou.com/programs/view/PM5qjlcJGnA/
```

**NB: Individual (non-batch) tudou downloads were working for me prior to updating youtube-dl to current version.** I am unsure what version I was running at the time but the error I received when attempting batch download (with same batch file) was as follows (sorry for non-verbose):

```
$ youtube-dl -a batch.txt
[tudou] B0zXrl9qXZY: Downloading JSON metadata
[tudou] 114473647: Opening the info XML page
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 411, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 401, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1692, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 666, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 316, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/tudou.py", line 85, in _real_extract
AttributeError: 'NoneType' object has no attribute 'split'
```

Since updating, individual downloads from tudou do not work anymore:
```
$ youtube-dl -v http://www.tudou.com/programs/view/ZspnsxBJzbY
[debug] System config: []
[debug] User config: [u'-f', u'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best']
[debug] Command-line args: [u'-v', u'http://www.tudou.com/programs/view/ZspnsxBJzbY']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.04.06
[debug] Python version 2.7.10 - Darwin-14.5.0-x86_64-i386-64bit
[debug] exe versions: avconv 11.4, avprobe 11.4, ffmpeg 2.8.3, ffprobe 2.8.3, rtmpdump 2.4
[debug] Proxy map: {}
[tudou] ZspnsxBJzbY: Downloading JSON metadata
[download] Downloading playlist: June 5 - Voice of Korea
[tudou] 125414770: Opening the info XML page
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 419, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 409, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1725, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 680, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 799, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1706, in getslice
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/tudou.py", line 110, in part_func
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by yan12125** [comment]
Could you run the command:
```
youtube-dl -v http://www.tudou.com/programs/view/ZspnsxBJzbY --dump-pages
```
And post the full output?

**Comment by goonbag** [comment]
That appears to be working:
```
$ youtube-dl -v http://www.tudou.com/programs/view/ZspnsxBJzbY --dump-pages
[debug] System config: []
[debug] User config: [u'-f', u'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best']
[debug] Command-line args: [u'-v', u'http://www.tudou.com/programs/view/ZspnsxBJzbY', u'--dump-pages']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.04.06
[debug] Python version 2.7.10 - Darwin-14.5.0-x86_64-i386-64bit
[debug] exe versions: avconv 11.4, avprobe 11.4, ffmpeg 2.8.3, ffprobe 2.8.3, rtmpdump 2.4
[debug] Proxy map: {}
[tudou] ZspnsxBJzbY: Downloading JSON metadata
[tudou] Dumping request to http://www.tudou.com/tvp/getItemInfo.action?ic=ZspnsxBJzbY
eyJvY29kZSI6IkZkT2ZiSDFnSTFFIiwia3ciOiJKdW5lIDUgLSBWb2ljZSBvZiBLb3JlYSIsImRlc2MiOiJWb2ljZSBvZiBLb3JlYSBFbmdsaXNoIGJyb2FkY2FzdCBmcm9tIFB5b25neWFuZyBtYWRlIG9uIEp1bmUgNSwgMjAwOC4iLCJvbmljIjoiZHBya3JhZGlvIiwib25hbWUiOiJkcHJrcmFkaW8iLCJpdGVtU2VncyI6IntcIjJcIjpbe1wiYmFzZVVybFwiOlwiaHR0cDpcXFwvXFxcL3YyLnR1ZG91LmNvbVxcXC94P2V2PTEmZXhwaXJlPTE0NjA1MzI3NDkmY2tzPWQ4MjViZWQ0YzljZGM3ZWVlNGExMDk4MTgwZGUxZGQ3XCIsXCJzZWNvbmRzXCI6MTY5NDEwMCxcIm5vXCI6MCxcInhpZFwiOlwiMDQwMDAyMDEwMDUxQkZFMDc5MTlGMDhENjcyRjFEN0ZFNzczREUtNDdDRi1GNTQ1LTgzNDktMDAwMTI1NDE0NzcwXCIsXCJwdFwiOjIsXCJrXCI6MTI1NDE0NzcwLFwic2l6ZVwiOjI4MzMzNDQwfV19IiwiaWlkIjoxODU4MjE3NSwidGFnIjoia29yZWEsZHByayxyYWRpbyxweW9uZ3lhbmcsanVjaGUiLCJjdXJsIjoiaHR0cDpcL1wvZW50LnR1ZG91LmNvbVwvIiwidGljdCI6MywiaGQiOjAsInBsYXlUaW1lcyI6NzYxLCJwaWMiOiJodHRwOlwvXC9pNC50ZGltZy5jb21cLzAzNFwvNzEyXC83OTlcL2F1ZGlvXzEyMHg5MC5qcGciLCJjaWQiOjEsIm1lZGlhVHlwZSI6ImF1IiwidGltZSI6IjI4OjE0IiwibXA0UGxheVR5cGVzIjoiIiwib2lkIjoyMTg2NzA3OCwiaGFzV2F0ZXJNYXJrIjowLCJwdCI6MTI4OTc1MDQwMDAwMCwiY25hbWUiOiLlqLHkuZAiLCJ0dmNDb2RlIjoiLTEiLCJ2Y29kZSI6IiIsImljb2RlIjoiWnNwbnN4Qkp6YlkifQ==
[download] Downloading playlist: June 5 - Voice of Korea
[tudou] 125414770: Opening the info XML page
[tudou] Dumping request to http://v2.tudou.com/f?id=125414770&hd2
PGYgczE9ImE4ZTRlYWI5ZWQyYWQ0M2EzZmRmZTcwZjgzNmIyNDM4MjU4NDBjYzQiIGJjPSIwIj5odHRwOi8vMTExLjkuMTIwLjE0OC9mNHYvNzUvMTg1ODIxNzUuY2dvLjIuZjR2P2tleT04OTExYzRkZDU3Zjk5OTJiNDExYzk5NTcwZGY2MGYwMDQwOTA4YzlmOWEmYW1wO3Fycz0yNDkwODk0NzAzJmFtcDtwPTE0Nzk1NDQ4ODMyODg3MTA2NTMzJmFtcDtwbGF5dHlwZT0yJmFtcDt0az03NTc0OTM5MTI1OTc2NzkwNTQzMDMxNTQyMiZhbXA7YnJ0PTImYW1wO2JjPTAmYW1wO3hpZD0wNDAwMDIwMTAwNTFCRkUwNzkxOUYwOEQ2NzJGMUQ3RkU3NzNERS00N0NGLUY1NDUtODM0OS0wMDAxMjU0MTQ3NzAmYW1wO250PTAmYW1wO253PTEmYW1wO2JzPTAmYW1wO2lzcGlkPTEwMDUmYW1wO3JjPTIxMCZhbXA7aW5mPTEyJmFtcDtzaT11biZhbXA7bnBjPTM5OTEmYW1wO3BwPTAmYW1wO3VsPTAmYW1wO210PTAmYW1wO3NpZD0wJmFtcDtwYz0wJmFtcDtjaXA9MjAzLjEyMi4yMjkuMTI4JmFtcDtpZD10dWRvdSZhbXA7aGY9MCZhbXA7aGQ9MCZhbXA7c3RhPTAmYW1wO3NzaWQ9MCZhbXA7Y3ZpZD0mYW1wO2l0ZW1pZD0xMjU0MTQ3NzAmYW1wO2ZpPTAmYW1wO3N6PTI4MzMzNDQwPC9mPjwhLS1wYWdldmlld19jYW5kaWRhdGUtLT4K
[tudou] playlist June 5 - Voice of Korea: Downloading 1 videos
[download] Downloading video 1 of 1
[debug] Invoking downloader on u'http://111.9.120.148/f4v/75/18582175.cgo.2.f4v?key=8911c4dd57f9992b411c99570df60f0040908c9f9a&qrs=2490894703&p=14795448832887106533&playtype=2&tk=75749391259767905430315422&brt=2&bc=0&xid=040002010051BFE07919F08D672F1D7FE773DE-47CF-F545-8349-000125414770&nt=0&nw=1&bs=0&ispid=1005&rc=210&inf=12&si=un&npc=3991&pp=0&ul=0&mt=0&sid=0&pc=0&cip=203.122.229.128&id=tudou&hf=0&hd=0&sta=0&ssid=0&cvid=&itemid=125414770&fi=0&sz=28333440'
[download] Destination: June 5 - Voice of Korea-125414770.f4v
[download]  17.8% of 27.02MiB at 87.77KiB/s ETA 04:19
```

**Comment by yan12125** [comment]
Looks like it's a temporary issue. Please paste the output of ```youtube-dl -v http://www.tudou.com/programs/view/ZspnsxBJzbY --dump-pages``` if the problem appears again.

**Comment by goonbag** [comment]
It's happening again:
```
$ youtube-dl -v http://www.tudou.com/programs/view/mgwuvVDCsaU --dump-pages
[debug] System config: []
[debug] User config: [u'-f', u'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best']
[debug] Command-line args: [u'-v', u'http://www.tudou.com/programs/view/mgwuvVDCsaU', u'--dump-pages']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.04.06
[debug] Python version 2.7.10 - Darwin-14.5.0-x86_64-i386-64bit
[debug] exe versions: avconv 11.4, avprobe 11.4, ffmpeg 2.8.3, ffprobe 2.8.3, rtmpdump 2.4
[debug] Proxy map: {}
[tudou] mgwuvVDCsaU: Downloading JSON metadata
[tudou] Dumping request to http://www.tudou.com/tvp/getItemInfo.action?ic=mgwuvVDCsaU
eyJvY29kZSI6IkZkT2ZiSDFnSTFFIiwia3ciOiJKdW5lIDQgLSBWb2ljZSBvZiBLb3JlYSAtIFBhcnQgMSIsImRlc2MiOiJGaXJzdCBwYXJ0IG9mIFZvaWNlIG9mIEtvcmVhIEVuZ2xpc2ggYnJvYWRjYXN0IGZyb20gUHlvbmd5YW5nIG1hZGUgb24gSnVuZSA0LCAyMDA4LiIsIm9uaWMiOiJkcHJrcmFkaW8iLCJvbmFtZSI6ImRwcmtyYWRpbyIsIml0ZW1TZWdzIjoie1wiMlwiOlt7XCJiYXNlVXJsXCI6XCJodHRwOlxcXC9cXFwvdjIudHVkb3UuY29tXFxcL3g/ZXY9MSZleHBpcmU9MTQ2MDUzNjczNCZja3M9YTdjMTdhYTA2OTc4MDEzOTgwNjRmZWQ3ZTI1OTI0Y2VcIixcInNlY29uZHNcIjoxNzE3NTAwLFwibm9cIjowLFwieGlkXCI6XCIwNDAwMDIwMTAwNTFCNDk3QkVGODFERTJDQUQ3RkI0OTNDQTQwOS1GRUVELUU0OUUtM0MxOS1FQUNDNzBBRkJBQTZcIixcInB0XCI6MixcImtcIjoxMDc5MDI5NjUsXCJzaXplXCI6Mjg3Mzk0MzV9XX0iLCJpaWQiOjE4NTQzNTM2LCJ0YWciOiJkcHJrLGtvcmVhLHJhZGlvLHB5b25neWFuZyxqdWNoZSIsImN1cmwiOiJodHRwOlwvXC9lbnQudHVkb3UuY29tXC8iLCJ0aWN0IjozLCJoZCI6MCwicGxheVRpbWVzIjo2MDcsInBpYyI6Imh0dHA6XC9cL2kxLnRkaW1nLmNvbVwvMDM0XC83MTJcLzc5OVwvYXVkaW9fMTIweDkwLmpwZyIsImNpZCI6MSwibWVkaWFUeXBlIjoiYXUiLCJ0aW1lIjoiMjg6MzciLCJtcDRQbGF5VHlwZXMiOiI1MiIsIm9pZCI6MjE4NjcwNzgsImhhc1dhdGVyTWFyayI6MCwicHQiOjEyODk3NTA0MDAwMDAsImNuYW1lIjoi5aix5LmQIiwidHZjQ29kZSI6Ii0xIiwidmNvZGUiOiIiLCJpY29kZSI6Im1nd3V2VkRDc2FVIn0=
[download] Downloading playlist: June 4 - Voice of Korea - Part 1
[tudou] 107902965: Opening the info XML page
[tudou] Dumping request to http://v2.tudou.com/f?id=107902965&hd2
PGUgZXJybm89JzUnIGVycm9yPSdpdGVtIGhhcyBubyBmaWxlIG5vdywgdHJ5IGxhdHRlcicgdGs9JzE0Mjc2Mjg5ODczOTQ1OTUzNjk1MDU2NTk4NCcgLz48IS0tcGFnZXZpZXdfY2FuZGlkYXRlLS0+Cg==
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 419, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 409, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1725, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 680, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 799, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1706, in getslice
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/tudou.py", line 110, in part_func
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by yan12125** [comment]
Looks like a temporary error on the server side:
```
$ echo "PGUgZXJybm89JzUnIGVycm9yPSdpdGVtIGhhcyBubyBmaWxlIG5vdywgdHJ5IGxhdHRlcicgdGs9JzE0Mjc2Mjg5ODczOTQ1OTUzNjk1MDU2NTk4NCcgLz48IS0tcGFnZXZpZXdfY2FuZGlkYXRlLS0+Cg==" | base64 -d
<e errno='5' error='item has no file now, try latter' tk='142762898739459536950565984' /><!--pageview_candidate-->
```
Anyway, I'm adding some error checking and proper messages will be printed:
```
$ youtube-dl -vF "http://www.tudou.com/programs/view/mgwuvVDCsaU"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-vF', 'http://www.tudou.com/programs/view/mgwuvVDCsaU']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.04.13
[debug] Git HEAD: 36b7d9d
[debug] Python version 3.5.1 - Linux-4.5.0-1-ARCH-x86_64-with-arch-Arch-Linux
[debug] exe versions: avconv v12_dev0-2591-gd12b5b2, avprobe v12_dev0-2591-gd12b5b2, ffmpeg 3.0.1, ffprobe 3.0.1, rtmpdump 2.4
[debug] Proxy map: {}
[tudou] mgwuvVDCsaU: Downloading JSON metadata
[download] Downloading playlist: June 4 - Voice of Korea - Part 1
ERROR: Tudou said: item has no file now, try latter
Traceback (most recent call last):
  File "/home/yen/Executables/Multimedia/youtube-dl/youtube_dl/YoutubeDL.py", line 682, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/yen/Executables/Multimedia/youtube-dl/youtube_dl/YoutubeDL.py", line 801, in process_ie_result
    playliststart, playlistend)
  File "/home/yen/Executables/Multimedia/youtube-dl/youtube_dl/utils.py", line 1706, in getslice
    page = list(self._pagefunc(pagenum))
  File "/home/yen/Executables/Multimedia/youtube-dl/youtube_dl/extractor/tudou.py", line 115, in part_func
    final_url = self._url_for_id(part_id, quality)
  File "/home/yen/Executables/Multimedia/youtube-dl/youtube_dl/extractor/tudou.py", line 73, in _url_for_id
    raise ExtractorError('Tudou said: %s' % error, expected=True)
youtube_dl.utils.ExtractorError: Tudou said: item has no file now, try latter
```
