### ISSUE TITLE
ImportError: No module named 'youtube_dl.extractor.alphaporno'

### ISSUE THREAD

**Issue by Beep6581** [rg3/youtube-dl#9206]
Hey

Trying to `youtube-dl -l -x "http://www.youtube.com/watch?v=A9ew7glBHy0"`, fails with:
```
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/youtube_dl/extractor/__init__.py", line 4, in <module>
    from .lazy_extractors import *
ImportError: No module named 'youtube_dl.extractor.lazy_extractors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/youtube-dl", line 3, in <module>
    import youtube_dl
  File "/usr/lib64/python3.4/site-packages/youtube_dl/__init__.py", line 43, in <module>
    from .extractor import gen_extractors, list_extractors
  File "/usr/lib64/python3.4/site-packages/youtube_dl/extractor/__init__.py", line 9, in <module>
    from .extractors import *
  File "/usr/lib64/python3.4/site-packages/youtube_dl/extractor/extractors.py", line 23, in <module>
    from .alphaporno import AlphaPornoIE
ImportError: No module named 'youtube_dl.extractor.alphaporno'
```

**Comment by Beep6581** [comment]
In fact just running `youtube-dl` without any arguments, or with `--help`, produces that fail.

Version 2016.04.13

**Comment by Beep6581** [comment]
Actually looks like a Gentoo Portage package issue.

**Comment by Beep6581** [comment]
Reported https://bugs.gentoo.org/show_bug.cgi?id=580070

**Comment by yan12125** [comment]
> Actually looks like a Gentoo Portage package issue.

I'm closing it here. Please leave comments if it's not a Gentoo issue but a youtube-dl one.
