### ISSUE TITLE
[StreetVoice] Test url 403

### ISSUE THREAD

**Issue by gineadai** [rg3/youtube-dl#9219]
In youtube-dl show to test url http://streetvoice.com/skippylu/songs/94440/
  `ERROR: unable to download video data: HTTP Error 403: Forbidden`, but work in browser. 
Other urls like: https://streetvoice.com/skippylu/songs/296258/ work fine.

**Comment by yan12125** [comment]
Another URL sometimes generates 403, too:
```
$ youtube-dl -v "https://streetvoice.com/skippylu/songs/296258/" 
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'https://streetvoice.com/skippylu/songs/296258/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.04.13
[debug] Git HEAD: 7bab22a
[debug] Python version 3.5.1 - Linux-4.5.0-1-ARCH-x86_64-with-arch-Arch-Linux
[debug] exe versions: avconv v12_dev0-2591-gd12b5b2, avprobe v12_dev0-2591-gd12b5b2, ffmpeg 3.0.1, ffprobe 3.0.1, rtmpdump 2.4
[debug] Proxy map: {}
[StreetVoice] 296258: Downloading JSON metadata
[debug] Invoking downloader on 'https://dbtocb5xx67gd.cloudfront.net/music/sk/ip/skippylu/296258_1e76c62a40004b9081a2ecb821687285_128000.mp3?Key-Pair-Id=APKAI4AGTUSBNNAXFQQA&Expires=1460996957&Signature=KhuXtMaAiSzVLNXE3BHAA9GAneDvXqmnhH2eOGBG0FX5-OISCvEJt%7E4lQjKLCryTCbdx-gm97lrIYA5bTSOiHaIa6a6DNczb0QiE71dHJsrzIaYZScUOgl86GU3KorjvCniQKVniDG2nr3fpjuAXalt09O2TLcnoaEM27iTHjI0_'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/home/yen/Executables/Multimedia/youtube-dl/youtube_dl/YoutubeDL.py", line 1638, in process_info
    success = dl(filename, info_dict)
  File "/home/yen/Executables/Multimedia/youtube-dl/youtube_dl/YoutubeDL.py", line 1580, in dl
    return fd.download(name, info)
  File "/home/yen/Executables/Multimedia/youtube-dl/youtube_dl/downloader/common.py", line 350, in download
    return self.real_download(filename, info_dict)
  File "/home/yen/Executables/Multimedia/youtube-dl/youtube_dl/downloader/http.py", line 58, in real_download
    data = self.ydl.urlopen(request)
  File "/home/yen/Executables/Multimedia/youtube-dl/youtube_dl/YoutubeDL.py", line 1940, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 471, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 581, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 509, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 443, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 589, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
```
From Firefox's console I see two StreetVoice API calls. I guess API does not always returns a valid URL and there are some client-side codes to determine whether an API response is valid or not. More investigation needed.

**Comment by yan12125** [comment]
streetvoice.py updated with the new API. Hopefully fixes 403 errors. Please leave comments if the problem is still.
