### ISSUE TITLE
[Netzkino] Multiple errors

### ISSUE THREAD

**Issue by gineadai** [rg3/youtube-dl#9226]
http://www.netzkino.de/#!/scifikino/rakete-zum-mond
`unable to download video data: HTTP Error 403: Forbidden`
http://www.netzkino.de/#!/drama/bathhouse-ov
`An extractor error has occurred. (caused by KeyError('posts',));`
http://www.netzkino.de/#!/neu/sin-nombre-life-without-hope-2
` An extractor error has occurred. (caused by StopIteration());`

**Comment by Hc10b** [comment]
I have also an error for `www.netzkino.de/#!/neu/die-kunst-des-negativen-denkens`
Output:
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['www.netzkino.de/#!/neu/die-kunst-des-negativen-denkens', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.12.02
[debug] Python version 3.6.3 - Linux-4.14.4-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 3.4, ffprobe 3.4, rtmpdump 2.4
[debug] Proxy map: {}
WARNING: The url doesn't specify the protocol, trying with http
[Netzkino] die-kunst-des-negativen-denkens: Downloading JSON metadata
ERROR: An extractor error has occurred. (caused by StopIteration()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 437, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/netzkino.py", line 45, in _real_extract
    p for p in api_info['posts'] if p['slug'] == video_id)
StopIteration
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 437, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/netzkino.py", line 45, in _real_extract
    p for p in api_info['posts'] if p['slug'] == video_id)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 450, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by StopIteration()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
