### ISSUE TITLE
AttributeError when trying to download from gdcvault.com 

### ISSUE THREAD

**Issue by indiecat** [rg3/youtube-dl#9248]
Trying to download http://gdcvault.com/play/1023460/Tenacious-Design-and-The-Interface

```
~/Downloads> youtube-dl -v "http://gdcvault.com/play/1023460/Tenacious-Design-and-The-Interface"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://gdcvault.com/play/1023460/Tenacious-Design-and-The-Interface']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.04.19
[debug] Python version 2.7.11 - Darwin-15.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.0.1, ffprobe 3.0.1, rtmpdump 2.4
[debug] Proxy map: {}
[GDCVault] Tenacious-Design-and-The-Interface: Downloading webpage
[GDCVault] Tenacious-Design-and-The-Interface: Downloading XML
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 419, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 409, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1730, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 671, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 341, in extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/gdcvault.py", line 192, in _real_extract
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/gdcvault.py", line 92, in _parse_flv
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1478, in remove_end
AttributeError: 'NoneType' object has no attribute 'ends with'
```

**Comment by yan12125** [comment]
This video will be fixed in the next version. Thanks for the report.
