### ISSUE TITLE
Ubuntu 16.04: MemoryError

### ISSUE THREAD

**Issue by ilf** [rg3/youtube-dl#9306]
Since the upgrade to Ubuntu 16.04, youtube-dl eats a lot of memory and then crashes.

```
% youtube-dl --version
2016.04.24

% python --version
Python 2.7.11+

% youtube-dl "XXXXXXXXXXX"
[youtube] XXXXXXXXXXX: Downloading webpage
[youtube] XXXXXXXXXXX: Downloading video info webpage
[youtube] XXXXXXXXXXX: Extracting video information
[youtube] XXXXXXXXXXX: Downloading MPD manifest
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 419, in main
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 409, in _real_main
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1732, in download
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 684, in extract_info
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 729, in process_ie_result
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1361, in process_video_result
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 48, in __init__
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 105, in _determine_executables
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 105, in <genexpr
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 1621, in get_exe_version
MemoryError
```

**Comment by yan12125** [comment]
From the log youtube-dl fails when trying to decode the output of one of the following commands: ```ffmpeg -version```, ```avconv -version```, ```ffprobe -version```, ```avprobe -version```. All of these commands print a few lines of messages (something like several KBytes), so this line shouldn't eats all of memory.

```
% python --version
Python 2.7.11+
```
Seems it's not authentic Python 2.7.11. (Usually a plus sign indicates "modified") Probably a Ubuntu issue. Please report it to them.

**Comment by ilf** [comment]
```
% ffmpeg -version
ffmpeg version 2.8.6-1ubuntu2 Copyright (c) 2000-2016 the FFmpeg developers
built with gcc 5.3.1 (Ubuntu 5.3.1-11ubuntu1) 20160311
configuration: --prefix=/usr --extra-version=1ubuntu2 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite
--enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv
libavutil      54. 31.100 / 54. 31.100
libavcodec     56. 60.100 / 56. 60.100
libavformat    56. 40.101 / 56. 40.101
libavdevice    56.  4.100 / 56.  4.100
libavfilter     5. 40.101 /  5. 40.101
libavresample   2.  1.  0 /  2.  1.  0
libswscale      3.  1.101 /  3.  1.101
libswresample   1.  2.101 /  1.  2.101
libpostproc    53.  3.100 / 53.  3.100
```
`/usr/bin/avconv` is a symlink to `/usr/bin/ffmpeg`

```
% ffprobe -version
ffprobe version 2.8.6-1ubuntu2 Copyright (c) 2007-2016 the FFmpeg developers
built with gcc 5.3.1 (Ubuntu 5.3.1-11ubuntu1) 20160311
configuration: --prefix=/usr --extra-version=1ubuntu2 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite
--enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv
libavutil      54. 31.100 / 54. 31.100
libavcodec     56. 60.100 / 56. 60.100
libavformat    56. 40.101 / 56. 40.101
libavdevice    56.  4.100 / 56.  4.100
libavfilter     5. 40.101 /  5. 40.101
libavresample   2.  1.  0 /  2.  1.  0
libswscale      3.  1.101 /  3.  1.101
libswresample   1.  2.101 /  1.  2.101
libpostproc    53.  3.100 / 53.  3.100
```
`/usr/bin/avprobe` is a Symlink to `/usr/bin/ffprobe`

Trying to monitor it with `top`, it does indeed seem like `avprobe` is eating a lot of CPU (98 %) and RAM (30 %) there. `youtube-dl` also uses another 68% CPU and 8.5 % RAM.

```
% apt-cache policy python
python:
  Installed: 2.7.11-1
```

Is it really an issue with the Ubuntu Python package? If so, what do I report to them?

**Comment by yan12125** [comment]
What's your total memory size?

**Comment by ilf** [comment]
4 GB

**Comment by yan12125** [comment]
avprobe eats 1.2GB. It's unusual. I'm not sure whether it's a ffprobe or Python issue. Maybe both.

Could you try with this Python script:
```
import subprocess

out, _ = subprocess.Popen(
    ['avprobe', '-version'],
    stdout=subprocess.PIPE, stderr=subprocess.STDOUT).communicate()
out = out.decode('ascii', 'ignore')
print(out)
```
It's a minimal version extracted from the failing point in youtube-dl.

**Comment by ilf** [comment]
Works:

```
% time python ./test.py
ffprobe version 2.8.6-1ubuntu2 Copyright (c) 2007-2016 the FFmpeg developers
built with gcc 5.3.1 (Ubuntu 5.3.1-11ubuntu1) 20160311
configuration: --prefix=/usr --extra-version=1ubuntu2 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite
--enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv
libavutil      54. 31.100 / 54. 31.100
libavcodec     56. 60.100 / 56. 60.100
libavformat    56. 40.101 / 56. 40.101
libavdevice    56.  4.100 / 56.  4.100
libavfilter     5. 40.101 /  5. 40.101
libavresample   2.  1.  0 /  2.  1.  0
libswscale      3.  1.101 /  3.  1.101
libswresample   1.  2.101 /  1.  2.101
libpostproc    53.  3.100 / 53.  3.100

python ./test.py  0.05s user 0.02s system 93% cpu 0.069 total
```

**Comment by yan12125** [comment]
I just tried on Ubuntu 16.04 live DVD and everything works. I'm afraid I can't help more. Ubuntu places may give you more help.

**Comment by OverlordQ** [comment]
Are you trying to pull down videos through Tor *and* trying to mux them at the same time? I get this error and this is due to torsocks being incompatible with ffmpeg

**Comment by yan12125** [comment]
It's a known bug (https://github.com/rg3/youtube-dl/issues/402#issuecomment-210873679). Note that SOCKS proxies support is available since version 2016.05.10. Use ```--proxy socks5://ip:port``` to enable it.

**Comment by OverlordQ** [comment]
Yeah, I was just making sure that wasn't the particular issue they were running into.

**Comment by ilf** [comment]
Oh yeah, I am using Tor, this was the issue. Sorry for the noise.
