### ISSUE TITLE
[Telegraaf] Unable to extract player

### ISSUE THREAD

**Issue by gineadai** [rg3/youtube-dl#9318]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.04.24**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

```
$ youtube-dl -v 'http://www.telegraaf.nl/tv/nieuws/binnenland/24353229/__Tikibad_ontruimd_wegens_brand__.html'
[debug] System config: []
[debug] User config: ['-4', '--prefer-free-formats', '--no-cache-dir', '--no-mtime', '--youtube-skip-dash-manifest']
[debug] Command-line args: ['-v', 'http://www.telegraaf.nl/tv/nieuws/binnenland/24353229/__Tikibad_ontruimd_wegens_brand__.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.04.24
[debug] Python version 3.5.1+ - Linux-4.6.0-rc3-686-i686-with-debian-stretch-sid
[debug] exe versions: ffmpeg 3.0.1, ffprobe 3.0.1, rtmpdump 2.4
[debug] Proxy map: {}
[Telegraaf] 24353229: Downloading webpage
ERROR: Unable to extract player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/YoutubeDL.py", line 673, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/common.py", line 341, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/telegraaf.py", line 29, in _real_extract
    r"iframe\.loadPlayer\('([^']+)'", webpage, 'player')
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/common.py", line 644, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


```

**Comment by Reino17** [comment]
I lack the experience to fix this in Python, but in the html-source follow:
```html
...
            <iframe src="//content.tmgvideo.nl/embed/account=Kx1PKc/item=mZlp2ctYIUEB/tikibad-ontruimd-wegens-brand.html" ...></iframe>
...
```
In there follow:
```java
StreamOnePlayer('video', {
...
	playlist: "http://content.tmgvideo.nl/playlist/account=Kx1PKc/item=mZlp2ctYIUEB/playlist.json",
...
}
```
The json's content:
```json
{
  "items": [
    {
      "id": "mZlp2ctYIUEB",
      "account": "Kx1PKc",
      "audioonly": false,
      "live": false,
      "title": "Tikibad ontruimd wegens brand",
      "description": "Het Tikibad in het Wassenaarse pretpark Duinrell is vrijdagavond ontruimd wegens brand. De brandweer is ter plekke, net zoals twee ambulances.",
      "poster": "http://content.tmgvideo.nl/img/account=Kx1PKc/item=mZlp2ctYIUEB/thumbid=20/image.jpg",
      "duration": 33,
      "locations": {
        "progressive": [
          {
            "label": "720p",
            "height": 720,
            "width": 1280,
            "sources": [
              {
                "type": "video/mp4",
                "src": "http://media.tmgvideo.nl/progressive/account=Kx1PKc/item=mZlp2ctYIUEB/file=G4kg2KPKIxAF/mZlp2ctYIUEB.mp4"
              }
            ]
          },
          {
            "label": "480p",
            "height": 480,
            "width": 854,
            "sources": [
              {
                "type": "video/mp4",
                "src": "http://media.tmgvideo.nl/progressive/account=Kx1PKc/item=mZlp2ctYIUEB/file=m59o-IbIKhEF/mZlp2ctYIUEB.mp4"
              }
            ]
          },
          {
            "label": "360p",
            "height": 360,
            "width": 640,
            "sources": [
              {
                "type": "video/mp4",
                "src": "http://media.tmgvideo.nl/progressive/account=Kx1PKc/item=mZlp2ctYIUEB/file=C49o2ILYKxkB/mZlp2ctYIUEB.mp4"
              }
            ]
          },
          {
            "label": "270p",
            "height": 270,
            "width": 480,
            "sources": [
              {
                "type": "video/mp4",
                "src": "http://media.tmgvideo.nl/progressive/account=Kx1PKc/item=mZlp2ctYIUEB/file=ix8g2KPaalEl/mZlp2ctYIUEB.mp4"
              }
            ]
          }
        ],
        "adaptive": [
          {
            "type": "application/dash+xml",
            "src": "http://media.tmgvideo.nl/dash/account=Kx1PKc/item=mZlp2ctYIUEB/mZlp2ctYIUEB.mpd"
          },
          {
            "type": "application/x-mpegURL",
            "src": "http://media.tmgvideo.nl/hls/account=Kx1PKc/item=mZlp2ctYIUEB/mZlp2ctYIUEB.m3u8"
          }
        ]
      }
    }
  ]
}
```
And I'm sure the developers here can extract all the video-formats from this json.

**Comment by yan12125** [comment]
Fixed. Thanks you all.
