### ISSUE TITLE
[20min] Unable to extract video id

### ISSUE THREAD

**Issue by loby66** [rg3/youtube-dl#9331]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.04.24**
- [X] Site support request (request for adding support for a new site)
```
C:\Program Files\youtubedl>youtube-dl -U
youtube-dl is up-to-date (2016.04.24)

C:\Program Files\youtubedl>youtube-dl --verbose -U http://www.20min.ch/ro/sports/football/story/Il-marque-une-bicyclette-de-plus-de-30-metres--21115184
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'-U', u'http://www.20min.ch/ro/sports/football/story/Il-marque-une-bicyclette-de-plus-de-30-metres--21115184']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.04.24
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 2.8.4
[debug] Proxy map: {}
youtube-dl is up-to-date (2016.04.24)
[20min] Il-marque-une-bicyclette-de-plus-de-30-metres--21115184: Downloading webpage
ERROR: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 673, in extract_info
  File "youtube_dl\extractor\common.pyo", line 341, in extract
  File "youtube_dl\extractor\twentymin.pyo", line 60, in _real_extract
  File "youtube_dl\extractor\common.pyo", line 644, in _search_regex
RegexNotFoundError: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by yan12125** [comment]
Thanks for the report. Embedded YouTube videos on 20min will be detected in the next version.
