### ISSUE TITLE
aac format download doesn't work

### ISSUE THREAD

**Issue by elichai** [rg3/youtube-dl#9360]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.05.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
```
$ youtube-dl -v -x --audio-format aac https://www.youtube.com/watch?v=X46t8ZFqUB4
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'-x', u'--audio-format', u'aac', u'https://www.youtube.com/watch?v=X46t8ZFqUB4']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.05.01
[debug] Python version 2.7.10 - Linux-4.2.0-36-generic-x86_64-with-Ubuntu-15.10-wily
[debug] exe versions: avconv 2.7.6-0ubuntu0.15.10.1, avprobe 2.7.6-0ubuntu0.15.10.1, ffmpeg 2.7.6-0ubuntu0.15.10.1, ffprobe 2.7.6-0ubuntu0.15.10.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] X46t8ZFqUB4: Downloading webpage
[youtube] X46t8ZFqUB4: Downloading video info webpage
[youtube] X46t8ZFqUB4: Extracting video information
[youtube] {22} signature length 41.40, html5 player en_US-vflA_6ZRP
[youtube] {43} signature length 41.40, html5 player en_US-vflA_6ZRP
[youtube] {18} signature length 41.40, html5 player en_US-vflA_6ZRP
[youtube] {5} signature length 41.40, html5 player en_US-vflA_6ZRP
[youtube] {36} signature length 41.40, html5 player en_US-vflA_6ZRP
[youtube] {17} signature length 41.40, html5 player en_US-vflA_6ZRP
[youtube] {137} signature length 41.40, html5 player en_US-vflA_6ZRP
[youtube] {248} signature length 41.40, html5 player en_US-vflA_6ZRP
[youtube] {136} signature length 41.40, html5 player en_US-vflA_6ZRP
[youtube] {247} signature length 41.40, html5 player en_US-vflA_6ZRP
[youtube] {135} signature length 41.40, html5 player en_US-vflA_6ZRP
[youtube] {244} signature length 41.40, html5 player en_US-vflA_6ZRP
[youtube] {134} signature length 41.40, html5 player en_US-vflA_6ZRP
[youtube] {243} signature length 41.40, html5 player en_US-vflA_6ZRP
[youtube] {133} signature length 41.40, html5 player en_US-vflA_6ZRP
[youtube] {242} signature length 41.40, html5 player en_US-vflA_6ZRP
[youtube] {160} signature length 41.40, html5 player en_US-vflA_6ZRP
[youtube] {278} signature length 41.40, html5 player en_US-vflA_6ZRP
[youtube] {140} signature length 41.40, html5 player en_US-vflA_6ZRP
[youtube] {171} signature length 41.40, html5 player en_US-vflA_6ZRP
[youtube] {249} signature length 41.40, html5 player en_US-vflA_6ZRP
[youtube] {250} signature length 41.40, html5 player en_US-vflA_6ZRP
[youtube] {251} signature length 41.40, html5 player en_US-vflA_6ZRP
[debug] Invoking downloader on u'https://r15---sn-5hnednek.googlevideo.com/videoplayback?fexp=9406124%2C9410705%2C9416126%2C9416891%2C9422596%2C9424134%2C9425007%2C9428399%2C9429856%2C9431012%2C9431582%2C9432000%2C9432684%2C9433096%2C9433693%2C9433946%2C9434290%2C9434344%2C9435278%2C9435283%2C9435398&sparams=clen%2Cdur%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&ip=146.185.130.203&clen=3908926&id=o-AIJSnOgURJL_ksQara4IenrTGLinhvhMnHtUWzbL9yVW&keepalive=yes&upn=RTtk7f97Zgs&mm=31&mn=sn-5hnednek&mt=1462104317&mv=m&ms=au&itag=251&ipbits=0&lmt=1449584570985797&sver=3&expire=1462126053&mime=audio%2Fwebm&key=yt6&nh=IgpwcjAyLmFtczE1KgkxMjcuMC4wLjE&gir=yes&requiressl=yes&source=youtube&dur=246.881&initcwndbps=8831250&pl=21&signature=D0BC6A457B81EF29BD924B21D7D492930C4670C3.2E958BE48BF28AD9F4A09C3777EFE675DA2FE841&ratebypass=yes'
[download] Zedd - I Want You To Know ft. Selena Gomez-X46t8ZFqUB4.webm has already been downloaded
[download] 100% of 3.73MiB
[debug] avconv command line: avprobe -show_streams 'file:Zedd - I Want You To Know ft. Selena Gomez-X46t8ZFqUB4.webm'
[ffmpeg] Destination: Zedd - I Want You To Know ft. Selena Gomez-X46t8ZFqUB4.aac
[debug] ffmpeg command line: avconv -y -i 'file:Zedd - I Want You To Know ft. Selena Gomez-X46t8ZFqUB4.webm' -vn -acodec aac -q:a 5 -f adts 'file:Zedd - I Want You To Know ft. Selena Gomez-X46t8ZFqUB4.aac'
ERROR: audio conversion failed: [aac @ 0x23eeb60] Alternatively use the non experimental encoder 'libvo_aacenc'.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1778, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 294, in run
    'audio conversion failed: ' + e.msg)
PostProcessingError

```
---

### Description of your *issue*

Can't download at aac audio format. always give me the same Error:
`ERROR: audio conversion failed: [aac @ 0x23eeb60] Alternatively use the non experimental encoder 'libvo_aacenc'.`

**Comment by dstftw** [comment]
Update ffmpeg.

**Comment by elichai** [comment]
still the same problem even when:
`[debug] exe versions: ffmpeg 2.8.6-1ubuntu2, ffprobe 2.8.6-1ubuntu2`

**Comment by dstftw** [comment]
Update to 3.x.

**Comment by elichai** [comment]
i'll try, although that's the latest in ubuntu repository

**Comment by elichai** [comment]
Updated to latest binary and it worked.
Thanks.
