### ISSUE TITLE
[SR] Mediathek Site support request

### ISSUE THREAD

**Issue by a-l-e-k** [rg3/youtube-dl#9373]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.05.01**

- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

- [x] Site support request (request for adding support for a new site)

- Single video: http://sr-mediathek.de/index.php?seite=7&id=1795
- Single audio: http://sr-mediathek.de/index.php?seite=7&id=7480

**description**
Can you please add support for SR Mediathek (Saarländischer Rundfunk)?
Log for audio example is attached.

**log**
```
youtube-dl.exe -v "http://sr-mediathek.de/index.php?seite=7&id=7480"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://sr-mediathek.de/index.php?seite=7&id=7480']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.05.01
[debug] Python version 2.7.10 - Windows-XP-5.1.2600-SP3
[debug] exe versions: ffmpeg N-67100-g6dc99fd, ffprobe N-67100-g6dc99fd, rtmpdump 2.4
[debug] Proxy map: {}
[generic] index: Requesting header
WARNING: Falling back on generic information extractor.
[generic] index: Downloading webpage
[generic] index: Extracting information
ERROR: Unsupported URL: http://sr-mediathek.de/index.php?seite=7&id=7480
Traceback (most recent call last):
  File "youtube_dl\extractor\generic.pyo", line 1393, in _real_extract
  File "youtube_dl\compat.pyo", line 279, in compat_etree_fromstring
  File "youtube_dl\compat.pyo", line 268, in _XML
  File "xml\etree\ElementTree.pyo", line 1642, in feed
  File "xml\etree\ElementTree.pyo", line 1506, in _raiseerror
ParseError: syntax error: line 1, column 1
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 673, in extract_info
  File "youtube_dl\extractor\common.pyo", line 341, in extract
  File "youtube_dl\extractor\generic.pyo", line 2063, in _real_extract
UnsupportedError: Unsupported URL: http://sr-mediathek.de/index.php?seite=7&id=7480
<end of log>
```

**Comment by dylziez** [comment]
`id=7480` -> `http://sr-mediathek.de/sr_player/mc.php?id=7480&tbl=&pnr=0`

```
{
	"_type": "audio",
	"_isLive": false,
	"_defaultQuality": 1,
	"_previewImage": "http://sr-mediathek.sr-multimedia.de/mediathek-images/thumb512/TN20110828200527sr2_bbc_springwatch_130.jpg",
	"_mediaArray": [{
		"_plugin": 1,
		"_mediaStreamArray": [{
			"_quality": 1,
			"_server": "",
			"_stream": "http://mediastorage01.sr-online.de/Audio/SR2/M/1314551162_crowdsourcing_erklaerung.mp3",
			"_cdn": "default"
		}]
	}, {
		"_plugin": 0,
		"_mediaStreamArray": [{
			"_quality": 1,
			"_server": "",
			"_stream": "http://mediastorage01.sr-online.de/Audio/SR2/M/1314551162_crowdsourcing_erklaerung.mp3",
			"_cdn": "default"
		}]
	}],
	"_audioImage": "http://sr-mediathek.sr-multimedia.de/mediathek-images/thumb512/TN20110828200527sr2_bbc_springwatch_130.jpg",
	"_sortierArray": [1, 0]
}
```

Is http://mediastorage01.sr-online.de/Audio/SR2/M/1314551162_crowdsourcing_erklaerung.mp3 the correct download for 7480?

**Comment by a-l-e-k** [comment]
Yes, the given url is the correct download for 7480.

**Comment by dstftw** [comment]
Does not look to be working:
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://sr-mediathek.de/index.php?seite=7&id=1795', u'-v']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.07.09
[debug] Git HEAD: 8cc9b40
[debug] Python version 2.7.11 - Windows-10-10.0.10240
[debug] exe versions: ffmpeg 3.0, ffprobe 3.0, rtmpdump 2.4
[debug] Proxy map: {}
[sr:mediathek] 1795: Downloading webpage
[sr:mediathek] 1795: Downloading media JSON
[sr:mediathek] 1795: Downloading f4m manifest
WARNING: Unable to download f4m manifest: HTTP Error 404: Not Found
[sr:mediathek] 1795: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 404: Not Found
[debug] Invoking downloader on u'http://mediastorage01.sr-online.de/Video/SR2/DOKU/abirede_L.mp4'
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "C:\Dev\youtube-dl\master\youtube_dl\YoutubeDL.py", line 1653, in process_info
    success = dl(filename, info_dict)
  File "C:\Dev\youtube-dl\master\youtube_dl\YoutubeDL.py", line 1595, in dl
    return fd.download(name, info)
  File "C:\Dev\youtube-dl\master\youtube_dl\downloader\common.py", line 350, in download
    return self.real_download(filename, info_dict)
  File "C:\Dev\youtube-dl\master\youtube_dl\downloader\http.py", line 58, in real_download
    data = self.ydl.urlopen(request)
  File "C:\Dev\youtube-dl\master\youtube_dl\YoutubeDL.py", line 1955, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "C:\Python\Python27\lib\urllib2.py", line 437, in open
    response = meth(req, response)
  File "C:\Python\Python27\lib\urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python\Python27\lib\urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "C:\Python\Python27\lib\urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "C:\Python\Python27\lib\urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found
```

**Comment by coltc50** [comment]
+1
