### ISSUE TITLE
[Periscope] Account ripping falls back on generic (account dumping implimented?)

### ISSUE THREAD

**Issue by vxbinaca** [rg3/youtube-dl#9388]
```youtube-dl -v  https://www.periscope.tv/FetishDollEmily/```

```
[debug] System config: []
[debug] User config: [u'--download-archive', u'~/.ytdlarchive', u'--retries', u'100', u'--no-overwrites', u'--call-home', u'--continue', u'--write-info-json', u'--write-description', u'--write-thumbnail', u'--write-annotations', u'--all-subs', u'--sub-format', u'srt', u'--convert-subs', u'srt', u'--write-sub', u'--add-metadata', u'-f', u'bestvideo+bestaudio/best', u'--merge-output-format', u'mkv', u'--prefer-ffmpeg', u'--embed-thumbnail']
[debug] Command-line args: [u'-v', u'https://www.periscope.tv/FetishDollEmily/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.05.01
[debug] Python version 2.7.11+ - Linux-4.4.0-21-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.6-1ubuntu2, ffprobe 2.8.6-1ubuntu2
[debug] Proxy map: {}
[debug] Public IP address: [REDACTED]
[generic] FetishDollEmily: Requesting header
WARNING: Falling back on generic information extractor.
[generic] FetishDollEmily: Downloading webpage
[generic] FetishDollEmily: Extracting information
ERROR: Unsupported URL: https://www.periscope.tv/FetishDollEmily/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 1393, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/compat.py", line 279, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=etree.TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/compat.py", line 268, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: mismatched tag: line 1, column 11173
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 673, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 341, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 2063, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.periscope.tv/FetishDollEmily/
```

**Comment by yan12125** [comment]
Did you see videos on https://www.periscope.tv/FetishDollEmily/?

**Comment by Vrihub** [comment]
I can confirm the issue / feature-request.
It would be nice if `youtube-dl https://periscope.tv/USERNAME` would download all videos available for replay on the page. The only problem I see is what to do if there's a live broadcast too: maybe it should download the live broadcast and then the older videos replays, with an option to skip the live broadcast and only download the replays (in case the user is only interested in those).

**Comment by yan12125** [comment]
@Vrihub Do you have an example?

**Comment by vxbinaca** [comment]
@yan12125 Apologies, I was afraid this would happen. The nature of Periscope is they stay up for about 6 hours. I'd need to find a *very* active account to test against. After that it's simply a matter of doing the regex and editing the module for Periscope.

**Comment by yan12125** [comment]
Does Periscope provide a list of users with videos in last 24 hrs?

**Comment by vxbinaca** [comment]
@yan12125 "@jimmyfallon" on Periscope appears to be popular. Perhaps wait for him to make a broadcast? I'm trying to find someone with videos.

**Comment by yan12125** [comment]
Take https://www.periscope.tv/LularoeHusbandMike for example, there are 5 videos. Is it your expectation?

**Comment by vxbinaca** [comment]
@yan12125 yes

**Comment by yan12125** [comment]
Thanks for all the information. Periscope user pages will be recognized in the next version.

**Comment by Vrihub** [comment]
Great feature, thanks!!!
Oh, and by the way, if there is a live broadcast going on and you are only interested in replays, remember you can skip downloading the live broadcast with: `youtube-dl --playlist-start 2`
