### ISSUE TITLE
[YouTube] "Could not write header for output file"

### ISSUE THREAD

**Issue by vxbinaca** [rg3/youtube-dl#9422]
```youtube-dl -v --ignore-config --retries 100 --no-overwrites --call-home --continue --write-info-json --write-description --write-thumbnail --write-annotations --all-subs --embed-sub -f bestvideo+bestaudio/best --merge-output-format 'mp4' --prefer-ffmpeg 4IAPPvDs8qg```

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'--ignore-config', u'--retries', u'100', u'--no-overwrites', u'--call-home', u'--continue', u'--write-info-json', u'--write-description', u'--write-thumbnail', u'--write-annotations', u'--all-subs', u'--embed-sub', u'-f', u'bestvideo+bestaudio/best', u'--merge-output-format', u'mp4', u'--prefer-ffmpeg', u'4IAPPvDs8qg']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.05.01
[debug] Python version 2.7.11+ - Linux-4.4.0-21-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.6-1ubuntu2, ffprobe 2.8.6-1ubuntu2
[debug] Proxy map: {}
[debug] Public IP address: [REDACTED]
[youtube] 4IAPPvDs8qg: Downloading webpage
[youtube] 4IAPPvDs8qg: Downloading video info webpage
[youtube] 4IAPPvDs8qg: Extracting video information
[youtube] 4IAPPvDs8qg: Searching for annotations.
[youtube] 4IAPPvDs8qg: Downloading MPD manifest
[info] Video description is already present
[info] Video annotations are already present
[info] Video subtitle en.vtt is already_present
[info] Video description metadata is already present
[youtube] 4IAPPvDs8qg: Thumbnail is already present
[debug] Invoking downloader on u'https://r17---sn-5uaezner.googlevideo.com/videoplayback?id=e0800f3ef0ecf2a8&itag=298&source=youtube&requiressl=yes&mv=m&pl=26&ms=au&nh=IgpwcjA0LmF0bDIyKgkxMjcuMC4wLjE&mm=31&mn=sn-5uaezner&initcwndbps=453750&ratebypass=yes&mime=video/mp4&gir=yes&clen=114234785&lmt=1462190746323986&dur=570.580&mt=1462584269&signature=1234B678A84FB5F9A8483EC53B985AE223CE0345.79337BD27C672A6167911DC6E792C3D72DF09226&fexp=9406128,9412858,9416126,9416891,9419452,9422596,9428398,9431012,9431118,9433096,9433387,9433694,9433946,9433999,9434213,9434280,9434607,9434768,9435036,9435504,9435580&sver=3&upn=yFUfxOyqH9Q&key=dg_yt0&ip=2601:6c5:200:e44f:c573:2255:ea97:c33d&ipbits=0&expire=1462606116&sparams=ip,ipbits,expire,id,itag,source,requiressl,mv,pl,ms,nh,mm,mn,initcwndbps,ratebypass,mime,gir,clen,lmt,dur'
[download] هل أوتاد الجبال إعجاز علمي ؟ - Are mountains like Pegs-4IAPPvDs8qg.f298.mp4 has already been downloaded
[download] 100% of 108.94MiB
[debug] Invoking downloader on u'https://r17---sn-5uaezner.googlevideo.com/videoplayback?id=e0800f3ef0ecf2a8&itag=251&source=youtube&requiressl=yes&mv=m&pl=26&ms=au&nh=IgpwcjA0LmF0bDIyKgkxMjcuMC4wLjE&mm=31&mn=sn-5uaezner&initcwndbps=453750&ratebypass=yes&mime=audio/webm&gir=yes&clen=9020917&lmt=1462191716791322&dur=570.581&mt=1462584269&signature=67E8BC0968A928FB75E5A059900CC9C60B817369.22BF19BAC8AA0EB1DFDD3847E78497A383B29997&fexp=9406128,9412858,9416126,9416891,9419452,9422596,9428398,9431012,9431118,9433096,9433387,9433694,9433946,9433999,9434213,9434280,9434607,9434768,9435036,9435504,9435580&sver=3&upn=yFUfxOyqH9Q&key=dg_yt0&ip=2601:6c5:200:e44f:c573:2255:ea97:c33d&ipbits=0&expire=1462606116&sparams=ip,ipbits,expire,id,itag,source,requiressl,mv,pl,ms,nh,mm,mn,initcwndbps,ratebypass,mime,gir,clen,lmt,dur'
[download] هل أوتاد الجبال إعجاز علمي ؟ - Are mountains like Pegs-4IAPPvDs8qg.f251.webm has already been downloaded
[download] 100% of 8.60MiB
[ffmpeg] Merging formats into "هل أوتاد الجبال إعجاز علمي ؟ - Are mountains like Pegs-4IAPPvDs8qg.mp4"
[debug] ffmpeg command line: ffmpeg -y -i 'file:هل أوتاد الجبال إعجاز علمي ؟ - Are mountains like Pegs-4IAPPvDs8qg.f298.mp4' -i 'file:هل أوتاد الجبال إعجاز علمي ؟ - Are mountains like Pegs-4IAPPvDs8qg.f251.webm' -c copy -map 0:v:0 -map 1:a:0 'file:هل أوتاد الجبال إعجاز علمي ؟ - Are mountains like Pegs-4IAPPvDs8qg.temp.mp4'
ERROR: Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1778, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/postprocessor/ffmpeg.py", line 445, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/postprocessor/ffmpeg.py", line 168, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
FFmpegPostProcessorError
youtube-dl -v --ignore-config --retries 100 --no-overwrites --call-home --continue --write-info-json --write-description --write-thumbnail --write-annotations --all-subs --embed-sub -f bestvideo+bestaudio/best --merge-output-format 'mp4' --prefer-ffmpeg 4IAPPvDs8qg
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'--ignore-config', u'--retries', u'100', u'--no-overwrites', u'--call-home', u'--continue', u'--write-info-json', u'--write-description', u'--write-thumbnail', u'--write-annotations', u'--all-subs', u'--embed-sub', u'-f', u'bestvideo+bestaudio/best', u'--merge-output-format', u'mp4', u'--prefer-ffmpeg', u'4IAPPvDs8qg']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.05.01
[debug] Python version 2.7.11+ - Linux-4.4.0-21-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.6-1ubuntu2, ffprobe 2.8.6-1ubuntu2
[debug] Proxy map: {}
[debug] Public IP address: 2601:6c5:200:e44f:c573:2255:ea97:c33d
[youtube] 4IAPPvDs8qg: Downloading webpage
[youtube] 4IAPPvDs8qg: Downloading video info webpage
[youtube] 4IAPPvDs8qg: Extracting video information
[youtube] 4IAPPvDs8qg: Searching for annotations.
[youtube] 4IAPPvDs8qg: Downloading MPD manifest
[info] Video description is already present
[info] Video annotations are already present
[info] Video subtitle en.vtt is already_present
[info] Video description metadata is already present
[youtube] 4IAPPvDs8qg: Thumbnail is already present
[debug] Invoking downloader on u'https://r17---sn-5uaezner.googlevideo.com/videoplayback?id=e0800f3ef0ecf2a8&itag=298&source=youtube&requiressl=yes&mv=m&pl=26&ms=au&nh=IgpwcjA0LmF0bDIyKgkxMjcuMC4wLjE&mm=31&mn=sn-5uaezner&initcwndbps=453750&ratebypass=yes&mime=video/mp4&gir=yes&clen=114234785&lmt=1462190746323986&dur=570.580&mt=1462584269&signature=1234B678A84FB5F9A8483EC53B985AE223CE0345.79337BD27C672A6167911DC6E792C3D72DF09226&fexp=9406128,9412858,9416126,9416891,9419452,9422596,9428398,9431012,9431118,9433096,9433387,9433694,9433946,9433999,9434213,9434280,9434607,9434768,9435036,9435504,9435580&sver=3&upn=yFUfxOyqH9Q&key=dg_yt0&ip=2601:6c5:200:e44f:c573:2255:ea97:c33d&ipbits=0&expire=1462606116&sparams=ip,ipbits,expire,id,itag,source,requiressl,mv,pl,ms,nh,mm,mn,initcwndbps,ratebypass,mime,gir,clen,lmt,dur'
[download] هل أوتاد الجبال إعجاز علمي ؟ - Are mountains like Pegs-4IAPPvDs8qg.f298.mp4 has already been downloaded
[download] 100% of 108.94MiB
[debug] Invoking downloader on u'https://r17---sn-5uaezner.googlevideo.com/videoplayback?id=e0800f3ef0ecf2a8&itag=251&source=youtube&requiressl=yes&mv=m&pl=26&ms=au&nh=IgpwcjA0LmF0bDIyKgkxMjcuMC4wLjE&mm=31&mn=sn-5uaezner&initcwndbps=453750&ratebypass=yes&mime=audio/webm&gir=yes&clen=9020917&lmt=1462191716791322&dur=570.581&mt=1462584269&signature=67E8BC0968A928FB75E5A059900CC9C60B817369.22BF19BAC8AA0EB1DFDD3847E78497A383B29997&fexp=9406128,9412858,9416126,9416891,9419452,9422596,9428398,9431012,9431118,9433096,9433387,9433694,9433946,9433999,9434213,9434280,9434607,9434768,9435036,9435504,9435580&sver=3&upn=yFUfxOyqH9Q&key=dg_yt0&ip=2601:6c5:200:e44f:c573:2255:ea97:c33d&ipbits=0&expire=1462606116&sparams=ip,ipbits,expire,id,itag,source,requiressl,mv,pl,ms,nh,mm,mn,initcwndbps,ratebypass,mime,gir,clen,lmt,dur'
[download] هل أوتاد الجبال إعجاز علمي ؟ - Are mountains like Pegs-4IAPPvDs8qg.f251.webm has already been downloaded
[download] 100% of 8.60MiB
[ffmpeg] Merging formats into "هل أوتاد الجبال إعجاز علمي ؟ - Are mountains like Pegs-4IAPPvDs8qg.mp4"
[debug] ffmpeg command line: ffmpeg -y -i 'file:هل أوتاد الجبال إعجاز علمي ؟ - Are mountains like Pegs-4IAPPvDs8qg.f298.mp4' -i 'file:هل أوتاد الجبال إعجاز علمي ؟ - Are mountains like Pegs-4IAPPvDs8qg.f251.webm' -c copy -map 0:v:0 -map 1:a:0 'file:هل أوتاد الجبال إعجاز علمي ؟ - Are mountains like Pegs-4IAPPvDs8qg.temp.mp4'
ERROR: Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1778, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/postprocessor/ffmpeg.py", line 445, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/postprocessor/ffmpeg.py", line 168, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
FFmpegPostProcessorError
youtube-dl -v --ignore-config --retries 100 --no-overwrites --call-home --continue --write-info-json --write-description --write-thumbnail --write-annotations --all-subs --embed-sub -f bestvideo+bestaudio/best --merge-output-format 'mp4' --prefer-ffmpeg 4IAPPvDs8qg
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'--ignore-config', u'--retries', u'100', u'--no-overwrites', u'--call-home', u'--continue', u'--write-info-json', u'--write-description', u'--write-thumbnail', u'--write-annotations', u'--all-subs', u'--embed-sub', u'-f', u'bestvideo+bestaudio/best', u'--merge-output-format', u'mp4', u'--prefer-ffmpeg', u'4IAPPvDs8qg']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.05.01
[debug] Python version 2.7.11+ - Linux-4.4.0-21-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.6-1ubuntu2, ffprobe 2.8.6-1ubuntu2
[debug] Proxy map: {}
[debug] Public IP address: 2601:6c5:200:e44f:c573:2255:ea97:c33d
[youtube] 4IAPPvDs8qg: Downloading webpage
[youtube] 4IAPPvDs8qg: Downloading video info webpage
[youtube] 4IAPPvDs8qg: Extracting video information
[youtube] 4IAPPvDs8qg: Searching for annotations.
[youtube] 4IAPPvDs8qg: Downloading MPD manifest
[info] Video description is already present
[info] Video annotations are already present
[info] Video subtitle en.vtt is already_present
[info] Video description metadata is already present
[youtube] 4IAPPvDs8qg: Thumbnail is already present
[debug] Invoking downloader on u'https://r17---sn-5uaezner.googlevideo.com/videoplayback?id=e0800f3ef0ecf2a8&itag=298&source=youtube&requiressl=yes&mv=m&pl=26&ms=au&nh=IgpwcjA0LmF0bDIyKgkxMjcuMC4wLjE&mm=31&mn=sn-5uaezner&initcwndbps=453750&ratebypass=yes&mime=video/mp4&gir=yes&clen=114234785&lmt=1462190746323986&dur=570.580&mt=1462584269&signature=1234B678A84FB5F9A8483EC53B985AE223CE0345.79337BD27C672A6167911DC6E792C3D72DF09226&fexp=9406128,9412858,9416126,9416891,9419452,9422596,9428398,9431012,9431118,9433096,9433387,9433694,9433946,9433999,9434213,9434280,9434607,9434768,9435036,9435504,9435580&sver=3&upn=yFUfxOyqH9Q&key=dg_yt0&ip=2601:6c5:200:e44f:c573:2255:ea97:c33d&ipbits=0&expire=1462606116&sparams=ip,ipbits,expire,id,itag,source,requiressl,mv,pl,ms,nh,mm,mn,initcwndbps,ratebypass,mime,gir,clen,lmt,dur'
[download] هل أوتاد الجبال إعجاز علمي ؟ - Are mountains like Pegs-4IAPPvDs8qg.f298.mp4 has already been downloaded
[download] 100% of 108.94MiB
[debug] Invoking downloader on u'https://r17---sn-5uaezner.googlevideo.com/videoplayback?id=e0800f3ef0ecf2a8&itag=251&source=youtube&requiressl=yes&mv=m&pl=26&ms=au&nh=IgpwcjA0LmF0bDIyKgkxMjcuMC4wLjE&mm=31&mn=sn-5uaezner&initcwndbps=453750&ratebypass=yes&mime=audio/webm&gir=yes&clen=9020917&lmt=1462191716791322&dur=570.581&mt=1462584269&signature=67E8BC0968A928FB75E5A059900CC9C60B817369.22BF19BAC8AA0EB1DFDD3847E78497A383B29997&fexp=9406128,9412858,9416126,9416891,9419452,9422596,9428398,9431012,9431118,9433096,9433387,9433694,9433946,9433999,9434213,9434280,9434607,9434768,9435036,9435504,9435580&sver=3&upn=yFUfxOyqH9Q&key=dg_yt0&ip=2601:6c5:200:e44f:c573:2255:ea97:c33d&ipbits=0&expire=1462606116&sparams=ip,ipbits,expire,id,itag,source,requiressl,mv,pl,ms,nh,mm,mn,initcwndbps,ratebypass,mime,gir,clen,lmt,dur'
[download] هل أوتاد الجبال إعجاز علمي ؟ - Are mountains like Pegs-4IAPPvDs8qg.f251.webm has already been downloaded
[download] 100% of 8.60MiB
[ffmpeg] Merging formats into "هل أوتاد الجبال إعجاز علمي ؟ - Are mountains like Pegs-4IAPPvDs8qg.mp4"
[debug] ffmpeg command line: ffmpeg -y -i 'file:هل أوتاد الجبال إعجاز علمي ؟ - Are mountains like Pegs-4IAPPvDs8qg.f298.mp4' -i 'file:هل أوتاد الجبال إعجاز علمي ؟ - Are mountains like Pegs-4IAPPvDs8qg.f251.webm' -c copy -map 0:v:0 -map 1:a:0 'file:هل أوتاد الجبال إعجاز علمي ؟ - Are mountains like Pegs-4IAPPvDs8qg.temp.mp4'
ERROR: Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1778, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/postprocessor/ffmpeg.py", line 445, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/postprocessor/ffmpeg.py", line 168, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
FFmpegPostProcessorError
```

**Comment by yan12125** [comment]
```bestaudio``` of this link contains an opus stream, which is currently not compatible with mp4 containers. Remove
```
--merge-output-format 'mp4'
```
Or use
```
-f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]"
```
