### ISSUE TITLE
ERROR: Signature extraction failed: Traceback (most recent call last)

### ISSUE THREAD

**Issue by RoboTehnik** [rg3/youtube-dl#9458]
C:\>youtube-dl.exe -v -f mp4 https://www.youtube.com/watch?v=ouqHQ589v7A
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'-f', u'mp4', u'https://www.youtube.com/watch?v=ouqHQ589v7A']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2015.11.21
[debug] Python version 2.7.10 - Windows-XP-5.1.2600-SP3
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] ouqHQ589v7A: Downloading webpage
[youtube] ouqHQ589v7A: Downloading video info webpage
[youtube] ouqHQ589v7A: Extracting video information
[youtube] {43} signature length 40.43, html5 player en_US-vflw9bxTw
[youtube] ouqHQ589v7A: Downloading player https://s.ytimg.com/yts/jsbin/player-en_US-vflw9bxTw/base.js
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 828, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 743, in _extract_signature_function
  File "youtube_dl\extractor\youtube.pyo", line 806, in _parse_sig_js
  File "youtube_dl\jsinterp.pyo", line 241, in extract_function
ExtractorError: Could not find JS function u'jr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. (caused by ExtractorError(u"Could not find JS function u'jr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose fla
g and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 828, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 743, in _extract_signature_function
  File "youtube_dl\extractor\youtube.pyo", line 806, in _parse_sig_js
  File "youtube_dl\jsinterp.pyo", line 241, in extract_function
ExtractorError: Could not find JS function u'jr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 661, in extract_info
  File "youtube_dl\extractor\common.pyo", line 290, in extract
  File "youtube_dl\extractor\youtube.pyo", line 1367, in _real_extract
  File "youtube_dl\extractor\youtube.pyo", line 838, in _decrypt_signature
ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "youtube_dl\extractor\youtube.pyo", line 828, in _decrypt_signature
  File "youtube_dl\extractor\youtube.pyo", line 743, in _extract_signature_function
  File "youtube_dl\extractor\youtube.pyo", line 806, in _parse_sig_js
  File "youtube_dl\jsinterp.pyo", line 241, in extract_function
ExtractorError: Could not find JS function u'jr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Could not find JS function u'jr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to
update. Be sure to call youtube-dl with the --verbose flag and include its compl
ete output.

**Comment by yan12125** [comment]
You are using an old version (2015.11.21). Upgrade to 2016.05.10 should solve the problem.
