### ISSUE TITLE
imdb : HTTP Error 405: Method Not Allowed

### ISSUE THREAD

**Issue by Arnaud69** [rg3/youtube-dl#9480]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.05.10*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2016.05.10**

### Before submitting an *issue* make sure you have:
- [ ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

i did it ;-)

### What is the purpose of your *issue*?
- [ x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

Hello !
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'-f', u'mp4/best', u'--no-cache-dir', u'http://www.imdb.com/video/screenplay/vi2694906137?ref_=nmvi_vi_imdb_1', u'-o', u'93f24789e7593dfe6aed7ff1e74ef3c8.tmp']
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out None, pref ANSI_X3.4-1968
[debug] youtube-dl version 2016.05.10
[debug] Python version 2.7.3 - Linux-2.6.38.2-grsec-xxxx-grs-ipv6-64-x86_64-with-debian-7.9
[debug] exe versions: ffmpeg N-53408-ga3659ca-static, ffprobe N-53408-ga3659ca-static, rtmpdump 2.4
[debug] Proxy map: {}
WARNING: Could not send HEAD request to http://www.imdb.com/video/screenplay/vi2694906137?ref_=nmvi_vi_imdb_1: HTTP Error 405: Method Not Allowed
WARNING: Falling back on generic information extractor.
ERROR: Unsupported URL: http://www.imdb.com/video/screenplay/vi2694906137?ref_=nmvi_vi_imdb_1
Traceback (most recent call last):
  File "youtube-dl/youtube_dl/extractor/generic.py", line 1393, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "youtube-dl/youtube_dl/compat.py", line 280, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=etree.TreeBuilder(element_factory=_element_factory)))
  File "youtube-dl/youtube_dl/compat.py", line 269, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1643, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1507, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 95, column 88
Traceback (most recent call last):
  File "youtube-dl/youtube_dl/YoutubeDL.py", line 676, in extract_info
    ie_result = ie.extract(url)
  File "youtube-dl/youtube_dl/extractor/common.py", line 341, in extract
    return self._real_extract(url)
  File "youtube-dl/youtube_dl/extractor/generic.py", line 2063, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.imdb.com/video/screenplay/vi2694906137?ref_=nmvi_vi_imdb_1
---
same with httpS://www.imdb.com/video/screenplay/vi2694906137?ref_=nmvi_vi_imdb_1

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.05.10
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* required an account credentials please provide them or explain how one can obtain them.

**Comment by Arnaud69** [comment]
line 15 in extractor :
_VALID_URL = r'https?://(?:www|m)\.imdb\.com/video/imdb/vi(?P<id>\d+)'
Should be :
_VALID_URL = r'https?://(?:www|m)\.imdb\.com/(?video|screenplay)/imdb/vi(?P<id>\d+)'

**Comment by Arnaud69** [comment]
http://www.imdb.com/video/screenplay/vi295043353?ref_=tt_ov_vi
and
http://www.imdb.com/video/imdb/vi295043353?ref_=tt_ov_vi
are the same page.

**Comment by Arnaud69** [comment]
pr open : https://github.com/rg3/youtube-dl/pull/9481
