### ISSUE TITLE
[Odnoklassniki] Unsupported URL

### ISSUE THREAD

**Issue by kotofond** [rg3/youtube-dl#9501]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.05.10*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.05.10**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
```
D:\>youtube-dl --verbose "http://m.ok.ru/dk?st.cmd=friendMediaStatusComments&st.edit=off&st.rpl=off&st.topicId=653485424"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://m.ok.ru/dk?st.cmd=friendMediaStatusComments&st.edit=off&st.rpl=off&st.topicId=653485424']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.05.10
[debug] Python version 3.5.1 - Windows-10-10.0.10586-SP0
[debug] exe versions: ffmpeg N-78358-g674cc26, ffprobe N-78358-g674cc26
[debug] Proxy map: {}
[generic] dk?st.cmd=friendMediaStatusComments&st.edit=off&st.rpl=off&st: Requesting header
[redirect] Following redirect to http://m.ok.ru/cdk/st.cmd/main/st.redirect/%252Fdk%253Fst.cmd%253DuserMain%2526tkn%253D2079%2526_prevCmd%253DfriendMediaStatusComments/_prevCmd/friendMediaStatusComments/tkn/2697
[generic] 2697: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 2697: Downloading webpage
[generic] 2697: Extracting information
ERROR: Unsupported URL: http://m.ok.ru/cdk/st.cmd/main/st.redirect/%252Fdk%253Fst.cmd%253DuserMain%2526tkn%253D2079%2526_prevCmd%253DfriendMediaStatusComments/_prevCmd/friendMediaStatusComments/tkn/2697
Traceback (most recent call last):
  File "c:\python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 676, in extract_info
    ie_result = ie.extract(url)
  File "c:\python35\lib\site-packages\youtube_dl\extractor\common.py", line 341, in extract
    return self._real_extract(url)
  File "c:\python35\lib\site-packages\youtube_dl\extractor\generic.py", line 2063, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: http://m.ok.ru/cdk/st.cmd/main/st.redirect/%252Fdk%253Fst.cmd%253DuserMain%2526tkn%253D2079%2526_prevCmd%253DfriendMediaStatusComments/_prevCmd/friendMediaStatusComments/tkn/2697
```

**Comment by kotofond** [comment]
That's weird, yesterday I was able to access that video via browser but can't do it now.
Closing this.
