### ISSUE TITLE
BBC downloads using a proxy fails with TypeError: int() argument must be a string or a number, not 'NoneType'

### ISSUE THREAD

**Issue by k3ck3c** [rg3/youtube-dl#9502]
Linux Ubuntu 15.10

When I want to download
http://www.bbc.co.uk/iplayer/episode/b079s75g/undercover-episode-5

I get an error message

$ youtube-dl -F --verbose http://www.bbc.co.uk/iplayer/episode/b079s75g/undercover-episode-5 --all-subs --proxy http://37.220.8.136:3128
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-F', u'--verbose', u'http://www.bbc.co.uk/iplayer/episode/b079s75g/undercover-episode-5--all-subs', u'--proxy', u'http://37.220.8.136:3128']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.06.04.1
[debug] Python version 2.7.10 - Linux-4.2.0-35-generic-x86_64-with-Ubuntu-15.10-wily
[debug] exe versions: avconv 2.7.6-0ubuntu0.15.10.1, avprobe 2.7.6-0ubuntu0.15.10.1, ffmpeg 2.7.6-0ubuntu0.15.10.1, ffprobe 2.7.6-0ubuntu0.15.10.1, rtmpdump 2.4-n97-gita107cef-ppa8
[debug] Proxy map: {u'http': u'http://37.220.8.136:3128', u'https': u'http://37.220.8.136:3128'}
[bbc.co.uk] b079s75g: Downloading video page
[bbc.co.uk] b079s73b: Downloading media selection XML
Traceback (most recent call last):
  File "/usr/bin/youtube-dl", line 6, in <module>
    youtube_dl.main()
  File "/usr/lib/python2.7/dist-packages/youtube_dl/__init__.py", line 405, in main
    _real_main(argv)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/__init__.py", line 395, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1502, in download
    res = self.extract_info(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 650, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 273, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/bbccouk.py", line 362, in _real_extract
    formats, subtitles = self._download_media_selector(programme_id)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/bbccouk.py", line 282, in _download_media_selector
    formats.extend(self._extract_video(media, programme_id))
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/bbccouk.py", line 204, in _extract_video
    file_size = int(media.get('media_file_size'))
TypeError: int() argument must be a string or a number, not 'NoneType'
$ 

$ youtube-dl --version
2015.06.04.1

$ uname -a
Linux asus 4.2.0-35-generic #40-Ubuntu SMP Tue Mar 15 22:15:45 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.
