### ISSUE TITLE
Traceback (most recent call last) error in windows 7

### ISSUE THREAD

**Issue by saravntbe** [rg3/youtube-dl#9559]
[x]Getting following error

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\py2exe\boot_common.py", line 92, in <modul
e>
ImportError: No module named linecache
Traceback (most recent call last):
  File "<install zipextimporter>", line 1, in <module>
ImportError: No module named zipextimporter
Traceback (most recent call last):
  File "__main__.py", line 2, in <module>
ImportError: No module named __future__

i am using window 7 x64.

**Comment by yan12125** [comment]
Did you put youtube-dl.exe in \Windows\System32?

**Comment by saravntbe** [comment]
yes. I Downloaded the youtube-dl.exe and place it in \Windows\System32.I also tried  running cmd  in Admin privilege but getting the same

**Comment by dstftw** [comment]
Do not place it in `%SYSTEMROOT%`.

**Comment by saravntbe** [comment]
Awesome :smile:  Thanks :+1:
