### ISSUE TITLE
Dowlnloading Lynda videos issue

### ISSUE THREAD

**Issue by kkoz84** [rg3/youtube-dl#9581]
Hi,

I am using this command in command prompt to download tutorial from lynda.com but i get error at the end. Here is code i use to run program: 

Youtube-dl.exe [http://www.lynda.com/PostgreSQL-tutorials/Prerequisites/73930/93117-4.html]--xxx
xxx@xx.com--password xxx

Here is outcome:

C:\Users\Lukasz\Desktop\Youtube Dl>Youtube-dl.exe [http://www.lynda.com/PostgreSQL-tutorials/Prerequisites/73930/93117-4.html]--xxx@xx.com--password xxxx
WARNING: The url doesn't specify the protocol, trying with http
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "youtube_dl\__init__.pyo", line 421, in main
  File "youtube_dl\__init__.pyo", line 411, in _real_main
  File "youtube_dl\YoutubeDL.pyo", line 1736, in download
  File "youtube_dl\YoutubeDL.pyo", line 687, in extract_info
  File "youtube_dl\YoutubeDL.pyo", line 740, in process_ie_result
  File "youtube_dl\YoutubeDL.pyo", line 676, in extract_info
  File "youtube_dl\extractor\common.pyo", line 341, in extract
  File "youtube_dl\extractor\generic.pyo", line 1278, in _real_extract
  File "urlparse.pyo", line 143, in urlparse
  File "urlparse.pyo", line 191, in urlsplit
ValueError: Invalid IPv6 URL

Any idead why it doesnt work?

Thanks,

**Comment by dstftw** [comment]
Remove brackets around the URL, put space before aech command line switch.

**Comment by dstftw** [comment]
Also change your lynda's password you've just posted on this public issue tracker.
