### ISSUE TITLE
Double Hyphen (to deal with Hyphen in front of Youtube String), causes output direction/titling to break.

### ISSUE THREAD

**Issue by artphotodude** [rg3/youtube-dl#9587]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.05.21.2*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.05.21.2**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
**_--------------------------------------------------------------------------------------------------------------
$  /usr/local/bin/python2.7 /usr/local/bin/youtube-dl -v -f 'best[ext!=webm][height<=?540]/best[ext!=webm][width<=1280]/[ext!=webm][height<=?1080]/best' -- '-Xo64Q2ucQ8' -o ~/Desktop/myTemp/ 
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'-f', u'best[ext!=webm][height<=?540]/best[ext!=webm][width<=1280]/[ext!=webm][height<=?1080]/best', u'--', u'-Xo64Q2ucQ8', u'-o', u'/Users/adamalbrec/Desktop/myTemp/']
[debug] Encodings: locale US-ASCII, fs utf-8, out US-ASCII, pref US-ASCII
[debug] youtube-dl version 2016.05.21.2
[debug] Python version 2.7.8 - Darwin-8.11.0-Power_Macintosh-powerpc-32bit
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] -Xo64Q2ucQ8: Downloading webpage
[youtube] -Xo64Q2ucQ8: Downloading video info webpage
[youtube] -Xo64Q2ucQ8: Extracting video information
[youtube] {22} signature length 40.41, html5 player en_US-vflGaNMBw
[youtube] {43} signature length 40.41, html5 player en_US-vflGaNMBw
[youtube] {18} signature length 40.41, html5 player en_US-vflGaNMBw
[youtube] {5} signature length 40.41, html5 player en_US-vflGaNMBw
[youtube] {36} signature length 40.41, html5 player en_US-vflGaNMBw
[youtube] {17} signature length 40.41, html5 player en_US-vflGaNMBw
[youtube] {137} signature length 40.41, html5 player en_US-vflGaNMBw
[youtube] {248} signature length 40.41, html5 player en_US-vflGaNMBw
[youtube] {136} signature length 40.41, html5 player en_US-vflGaNMBw
[youtube] {247} signature length 40.41, html5 player en_US-vflGaNMBw
[youtube] {135} signature length 40.41, html5 player en_US-vflGaNMBw
[youtube] {244} signature length 40.41, html5 player en_US-vflGaNMBw
[youtube] {134} signature length 40.41, html5 player en_US-vflGaNMBw
[youtube] {243} signature length 40.41, html5 player en_US-vflGaNMBw
[youtube] {133} signature length 40.41, html5 player en_US-vflGaNMBw
[youtube] {242} signature length 40.41, html5 player en_US-vflGaNMBw
[youtube] {160} signature length 40.41, html5 player en_US-vflGaNMBw
[youtube] {278} signature length 40.41, html5 player en_US-vflGaNMBw
[youtube] {140} signature length 40.41, html5 player en_US-vflGaNMBw
[youtube] {171} signature length 40.41, html5 player en_US-vflGaNMBw
[youtube] {249} signature length 40.41, html5 player en_US-vflGaNMBw
[youtube] {250} signature length 40.41, html5 player en_US-vflGaNMBw
[youtube] {251} signature length 40.41, html5 player en_US-vflGaNMBw
[debug] Invoking downloader on u'https://r6---sn-nx5e6n7d.googlevideo.com/videoplayback?ms=au&mv=m&pl=18&mt=1463968818&mn=sn-nx5e6n7d&mm=31&key=yt6&dur=194.374&source=youtube&id=o-AIXKBzisPWOvd4x7cHFOvbdBzb6KnRVGCIZ76C-rsmW4&requiressl=yes&itag=18&lmt=1458181989690647&sparams=dur%2Cgcr%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&ip=184.97.98.94&expire=1463990610&fexp=9405958%2C9416126%2C9416891%2C9422596%2C9423554%2C9424092%2C9428093%2C9428398%2C9428771%2C9431012%2C9432058%2C9433096%2C9433946%2C9433999%2C9434017%2C9435577%2C9435685%2C9435791%2C9435875%2C9436024%2C9436085%2C9436607%2C9436795%2C9437425&ipbits=0&ratebypass=yes&initcwndbps=368750&nh=IgpwcjAyLnNlYTAzKgkxMjcuMC4wLjE&upn=uuX0R9EEy40&mime=video%2Fmp4&sver=3&gcr=us&signature=3BC6BD6D7EFC1BF0EE3CCADA884954594F50B399.7CA44B6BE16BC1912AD6265597C0663A2D463C9E'
[download] Destination: [Official Video] Joy To The World  Pentatonix--Xo64Q2ucQ8.mp4
[download] 100% of 11.08MiB in 00:20
ERROR: u'-o' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:-o" ) to search YouTube
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 676, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 341, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1303, in _real_extract
    % (url, url), expected=True)
ExtractorError: u'-o' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:-o" ) to search YouTube

--------------------------------------------------------------------------------------------------------------_**

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* required an account credentials please provide them or explain how one can obtain them.

REALLY curious issue.  Have used the Double-Hyphen, as directed to allow for youtube-strings that begin with a hyphen, and it will download, but will not honor my output path (-o) / and Title-format request. Instead goes to ~/.

Does not happen with strings that do not have Hyphen in front.  
Is dynamically-generated code, and the only reliable way to handle MASSING possible variations with youtube-dl's narrow formatting tollerences is to strip-away everything but the explicit-string. Is there any other ways to escape/pass that front hyphen?

**Comment by artphotodude** [comment]
You can somewhat see the problem above with the defaulting above to the little **u'** before each additional notation. What does this happen after it correctly identifies/ and downloads the youtube string **-Xo64Q2ucQ8**?

_**u'--', u'-Xo64Q2ucQ8', u'-o', u'...**_

**Comment by dstftw** [comment]
`--` denotes the end of the optional arguments thus you can't have any optional argument after `--` by design. `-o` must go before `--`.

**Comment by artphotodude** [comment]
That fixed it! Thanks!
