### ISSUE TITLE
Site Request: Deadspin.com

### ISSUE THREAD

**Issue by RingoTheDog** [rg3/youtube-dl#9612]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.05.21.2*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X ] I've **verified** and **I assure** that I'm running youtube-dl **2016.05.21.2**

### Before submitting an *issue* make sure you have:
- [X ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [X ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- http://fittish.deadspin.com/pro-cyclist-crashes-spectacularly-into-snowbank-costs-1779152408
- http://theconcourse.deadspin.com/bear-catches-belly-rays-1779158981
- http://deadspin.com/russell-westbrook-tells-us-how-he-really-feels-about-st-1779124655
- Playlist: n/a

---

Thanks
Ringo

**Comment by yan12125** [comment]
@RingoTheDog Seems there's no video in the first example?

To developers: Custom YouTube embeds.

**Comment by RingoTheDog** [comment]
After "Instead, he quite literally rode right into it."

![image](https://cloud.githubusercontent.com/assets/4542921/15628452/a1c03a64-24b6-11e6-84d6-2edfacb71d7a.png)

**Comment by yan12125** [comment]
Alright, my ad blocker blocks it. It's a Twitter embedded.

**Comment by RingoTheDog** [comment]
no prob...and thanks!

**Comment by RingoTheDog** [comment]
***BUMP***

Hoping someone might be able to have another look at deadspin....

here is a more recent example URL:
http://screengrabber.deadspin.com/arena-football-play-so-bad-youll-forget-how-many-teams-1795612624

Thanks again
Ringo

**Comment by Hrxn** [comment]
Seems to use JW Player, which is also used by other supported sites already, as far as I know.

**Comment by RingoTheDog** [comment]
yes many of the vids use but JW Player...


http://screengrabber.deadspin.com/arena-football-play-so-bad-youll-forget-how-many-teams-1795612624  is JW Player

However: http://fittish.deadspin.com/pro-cyclist-crashes-spectacularly-into-snowbank-costs-1779152408 is a twitter embed (which points to: https://video.twimg.com/ext_tw_video/736192056104787972/pu/pl/1280x720/YUtVYgxkgcXmIcZc.m3u8)

**Comment by RingoTheDog** [comment]
Let's go to the archives an oldie but a goodie ;-)

Here is a new link:

https://deadspin.com/last-man-standing-in-bears-exhaustive-kicker-competitio-1837728402?jwsource=cl


youtube-dl.py` -v "https://deadspin.com/last-man-standing-in-be
ars-exhaustive-kicker-competitio-1837728402?jwsource=cl"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://deadspin.com/last-man-standing-in-bea
rs-exhaustive-kicker-competitio-1837728402?jwsource=cl']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2019.08.13
[debug] Python version 3.6.3 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-71727-g46778ab, rtmpdump 2.4
[debug] Proxy map: {}
[generic] last-man-standing-in-bears-exhaustive-kicker-competitio-1837728402?jws
ource=cl: Requesting header
WARNING: Falling back on generic information extractor.
[generic] last-man-standing-in-bears-exhaustive-kicker-competitio-1837728402?jws
ource=cl: Downloading webpage
[generic] last-man-standing-in-bears-exhaustive-kicker-competitio-1837728402?jws
ource=cl: Extracting information
ERROR: Unsupported URL: https://deadspin.com/last-man-standing-in-bears-exhausti
ve-kicker-competitio-1837728402?jwsource=cl
Traceback (most recent call last):
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\YoutubeDL.py", line 796, in e
xtract_info
    ie_result = ie.extract(url)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\common.py", line 53
0, in extract
    ie_result = self._real_extract(url)
  File "C:\Transmogrifier\youtube-dl.py\youtube_dl\extractor\generic.py", line 3
333, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://deadspin.com/last-ma
n-standing-in-bears-exhaustive-kicker-competitio-1837728402?jwsource=cl
