### ISSUE TITLE
Twitter: Wrong extension on video and leftover files

### ISSUE THREAD

**Issue by Skibicki** [rg3/youtube-dl#9623]
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2016.05.21.2**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other
---
```
youtube-dl -v https://twitter.com/OfficialWithHL/status/736627282601779201
[debug] System config: []
[debug] User config: ['--user-agent', 'Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.63 Safari/537.36', '--co
okies', 'C:\\Users\\Name\\AppData\\Roaming\\youtube-dl\\ytdl_cookies', '--no-check-certificate', '--rate-limit', '4.5M', '--retries', '1', '--format', '136+1
41/136+251/22+141/22+251/135+141/135+251/244+141/244+251/134+141/134+251/18+141/18+251/133+141/133+251/242+141/242+251/18+140/best', '--merge-output-format', 'm
kv', '--add-metadata', '--all-subs', '--sub-format', 'ass/srt', '--write-sub', '--embed-subs']
[debug] Command-line args: ['-v', 'https://twitter.com/OfficialWithHL/status/736627282601779201']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.05.21.2
[debug] Python version 3.5.1 - Windows-8.1-6.3.9600-SP0
[debug] exe versions: ffmpeg N-80109-g86d703f, ffprobe N-80109-g86d703f, rtmpdump 2.4
[debug] Proxy map: {}
[twitter] 736627282601779201: Downloading webpage
[twitter:card] 736627282601779201: Downloading webpage
[debug] Invoking downloader on 'https://video.twimg.com/ext_tw_video/736604044458926081/pu/pl/jMtbGVUWcO0BsaWN.m3u8'
[download] Destination: H&L Updates! - VIDEO _ Louis interview for Channel 4 at the Monaco F1 GP Qualifying! #3    (© LouisT91Updates)-736627282601779201.m3u8
[debug] ffmpeg command line: ffmpeg -y -headers 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Encoding: gzip, deflate
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
User-Agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.63 Safari/537.36
Accept-Language: en-us,en;q=0.5
' -i https://video.twimg.com/ext_tw_video/736604044458926081/pu/pl/jMtbGVUWcO0BsaWN.m3u8 -c copy -f mp4 -bsf:a aac_adtstoasc 'file:H&L Updates! - VIDEO _ Louis
interview for Channel 4 at the Monaco F1 GP Qualifying! #3    (© LouisT91Updates)-736627282601779201.m3u8.part'
ffmpeg version N-80109-g86d703f Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 5.3.0 (GCC)
  configuration: --enable-gpl --enable-version3 --disable-w32threads --enable-nvenc --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enabl
e-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libil
bc --enable-libmodplug --enable-libmfx --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-
librtmp --enable-libschroedinger --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo
-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-l
ibzimg --enable-lzma --enable-decklink --enable-zlib
  libavutil      55. 24.100 / 55. 24.100
  libavcodec     57. 43.100 / 57. 43.100
  libavformat    57. 37.100 / 57. 37.100
  libavdevice    57.  0.101 / 57.  0.101
  libavfilter     6. 46.100 /  6. 46.100
  libswscale      4.  1.100 /  4.  1.100
  libswresample   2.  0.101 /  2.  0.101
  libpostproc    54.  0.100 / 54.  0.100
Input #0, hls,applehttp, from 'https://video.twimg.com/ext_tw_video/736604044458926081/pu/pl/jMtbGVUWcO0BsaWN.m3u8':
  Duration: 00:00:30.03, start: 0.000000, bitrate: 0 kb/s
  Program 0
    Metadata:
      variant_bitrate : 320000
    Stream #0:0: Video: h264 (Constrained Baseline) ([27][0][0][0] / 0x001B), yuv420p, 320x180, 29.97 fps, 29.97 tbr, 90k tbn
    Metadata:
      variant_bitrate : 320000
    Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp, 65 kb/s
    Metadata:
      variant_bitrate : 320000
  Program 1
    Metadata:
      variant_bitrate : 832000
    Stream #0:2: Video: h264 (Constrained Baseline) ([27][0][0][0] / 0x001B), yuv420p, 640x360, 29.97 fps, 29.97 tbr, 90k tbn
    Metadata:
      variant_bitrate : 832000
    Stream #0:3: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp, 65 kb/s
    Metadata:
      variant_bitrate : 832000
  Program 2
    Metadata:
      variant_bitrate : 2176000
    Stream #0:4: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p, 1280x720, 29.97 fps, 29.97 tbr, 90k tbn
    Metadata:
      variant_bitrate : 2176000
    Stream #0:5: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp, 124 kb/s
    Metadata:
      variant_bitrate : 2176000
[mp4 @ 00000000035bae20] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
    Last message repeated 1 times
Output #0, mp4, to 'file:H&L Updates! - VIDEO _ Louis interview for Channel 4 at the Monaco F1 GP Qualifying! #3    (┬⌐ LouisT91Updates)-736627282601779201.m3u8
.part':
  Metadata:
    encoder         : Lavf57.37.100
    Stream #0:0: Video: h264 ([33][0][0][0] / 0x0021), yuv420p, 1280x720, q=2-31, 29.97 fps, 29.97 tbr, 90k tbn
    Metadata:
      variant_bitrate : 2176000
    Stream #0:1: Audio: aac (LC) ([64][0][0][0] / 0x0040), 44100 Hz, stereo, 65 kb/s
    Metadata:
      variant_bitrate : 320000
Stream mapping:
  Stream #0:4 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
[hls,applehttp @ 00000000024a5a00] No longer receiving playlist 1
frame=  900 fps=131 q=-1.0 Lsize=    5488kB time=00:00:30.04 bitrate=1496.2kbits/s speed=4.36x
video:5239kB audio:235kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.257819%
[ffmpeg] Downloaded 5619544 bytes
[download] 100% of 5.36MiB
[ffmpeg] Adding metadata to 'H&L Updates! - VIDEO _ Louis interview for Channel 4 at the Monaco F1 GP Qualifying! #3    (© LouisT91Updates)-736627282601779201.m
3u8'
[debug] ffmpeg command line: ffmpeg -y -i 'file:H&L Updates! - VIDEO _ Louis interview for Channel 4 at the Monaco F1 GP Qualifying! #3    (© LouisT91Updates)-7
36627282601779201.m3u8' -c copy -metadata 'comment=H&L Updates! on Twitter: "VIDEO || Louis interview for Channel 4 at the Monaco F1 GP Qualifying! #3    (© Lou
isT91Updates) https://t.co/E9z8eMtdcV"' -metadata purl=https://twitter.com/OfficialWithHL/status/736627282601779201 -metadata 'description=H&L Updates! on Twitt
er: "VIDEO || Louis interview for Channel 4 at the Monaco F1 GP Qualifying! #3    (© LouisT91Updates) https://t.co/E9z8eMtdcV"' -metadata 'artist=H&L Updates!'
-metadata 'title=H&L Updates! - VIDEO || Louis interview for Channel 4 at the Monaco F1 GP Qualifying! #3    (© LouisT91Updates)' 'file:H&L Updates! - VIDEO _ L
ouis interview for Channel 4 at the Monaco F1 GP Qualifying! #3    (© LouisT91Updates)-736627282601779201.temp.m3u8'
ERROR: Conversion failed!
Traceback (most recent call last):
  File "c:\other_programs\python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 1782, in post_process
    files_to_delete, info = pp.run(info)
  File "c:\other_programs\python35\lib\site-packages\youtube_dl\postprocessor\ffmpeg.py", line 433, in run
    self.run_ffmpeg(filename, temp_filename, options)
  File "c:\other_programs\python35\lib\site-packages\youtube_dl\postprocessor\ffmpeg.py", line 172, in run_ffmpeg
    self.run_ffmpeg_multiple_files([path], out_path, opts)
  File "c:\other_programs\python35\lib\site-packages\youtube_dl\postprocessor\ffmpeg.py", line 168, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError: Conversion failed!
...
<end of log>
```
---

### Description of your *issue*, suggested solution and other information
The downloaded videos is mislabeled with an m3u8 extension. Two other files are left behind, an m3u file with .temp.m3u8.tmp and an unknown file with temp0.ts. With ignore-config the other files do not appear.

**Comment by hurda** [comment]
With 2016.06.03 there are no leftover files, but the extension is still wrong.

```
>youtube-dl.exe -v https://twitter.com/OfficialWithHL/status/736627282601779201
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'https://twitter.com/OfficialWithHL/status/736
627282601779201']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.06.03
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-73361-g03b2b40, ffprobe N-73361-g03b2b40, rtmpdum
p 2.4
[debug] Proxy map: {}
[twitter] 736627282601779201: Downloading webpage
[twitter:card] 736627282601779201: Downloading webpage
[debug] Invoking downloader on 'https://video.twimg.com/ext_tw_video/73660404445
8926081/pu/pl/jMtbGVUWcO0BsaWN.m3u8'
[download] Destination: H&L Updates! - VIDEO _ Louis interview for Channel 4 at
the Monaco F1 GP Qualifying! #3    (© LouisT91Updates)-736627282601779201.m3u8
[debug] ffmpeg command line: ffmpeg -y -headers 'Accept: text/html,application/x
html+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-us,en;q=0.5
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/44.0
 (Chrome)
Accept-Encoding: gzip, deflate
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
' -i https://video.twimg.com/ext_tw_video/736604044458926081/pu/pl/jMtbGVUWcO0Bs
aWN.m3u8 -c copy -f mp4 -bsf:a aac_adtstoasc 'file:H&L Updates! - VIDEO _ Louis
interview for Channel 4 at the Monaco F1 GP Qualifying! #3    (© LouisT91Updates
)-736627282601779201.m3u8.part'
ffmpeg version N-73361-g03b2b40 Copyright (c) 2000-2015 the FFmpeg developers
  built with gcc 4.9.2 (GCC)
  configuration: --enable-gpl --enable-version3 --disable-w32threads --enable-av
isynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enab
le-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --
enable-libdcadec --enable-libfreetype --enable-libgme --enable-libgsm --enable-l
ibilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enab
le-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --en
able-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --ena
ble-libtwolame --enable-libvidstab --enable-libvo-aacenc --enable-libvo-amrwbenc
 --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enabl
e-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-lzma --ena
ble-decklink --enable-zlib
  libavutil      54. 27.100 / 54. 27.100
  libavcodec     56. 46.100 / 56. 46.100
  libavformat    56. 40.100 / 56. 40.100
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 19.100 /  5. 19.100
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.100 /  1.  2.100
  libpostproc    53.  3.100 / 53.  3.100
Input #0, hls,applehttp, from 'https://video.twimg.com/ext_tw_video/736604044458
926081/pu/pl/jMtbGVUWcO0BsaWN.m3u8':
  Duration: 00:00:30.03, start: 0.000000, bitrate: 0 kb/s
  Program 0
    Metadata:
      variant_bitrate : 320000
    Stream #0:0: Video: h264 (Constrained Baseline) ([27][0][0][0] / 0x001B), yu
v420p, 320x180, 29.97 fps, 29.97 tbr, 90k tbn, 59.94 tbc
    Metadata:
      variant_bitrate : 320000
    Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, flt
p, 67 kb/s
    Metadata:
      variant_bitrate : 320000
  Program 1
    Metadata:
      variant_bitrate : 832000
    Stream #0:2: Video: h264 (Constrained Baseline) ([27][0][0][0] / 0x001B), yu
v420p, 640x360, 29.97 fps, 29.97 tbr, 90k tbn, 59.94 tbc
    Metadata:
      variant_bitrate : 832000
    Stream #0:3: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, flt
p, 67 kb/s
    Metadata:
      variant_bitrate : 832000
  Program 2
    Metadata:
      variant_bitrate : 2176000
    Stream #0:4: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p, 1280x720,
 29.97 fps, 29.97 tbr, 90k tbn, 59.94 tbc
    Metadata:
      variant_bitrate : 2176000
    Stream #0:5: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, flt
p, 122 kb/s
    Metadata:
      variant_bitrate : 2176000
[mp4 @ 06a71ca0] Codec for stream 0 does not use global headers but container fo
rmat requires global headers
[mp4 @ 06a71ca0] Codec for stream 1 does not use global headers but container fo
rmat requires global headers
Output #0, mp4, to 'file:H&L Updates! - VIDEO _ Louis interview for Channel 4 at
 the Monaco F1 GP Qualifying! #3    (┬® LouisT91Updates)-736627282601779201.m3u8
.part':
  Metadata:
    encoder         : Lavf56.40.100
    Stream #0:0: Video: h264 ([33][0][0][0] / 0x0021), yuv420p, 1280x720, q=2-31
, 29.97 fps, 29.97 tbr, 90k tbn, 90k tbc
    Metadata:
      variant_bitrate : 2176000
    Stream #0:1: Audio: aac ([64][0][0][0] / 0x0040), 44100 Hz, stereo, 67 kb/s
    Metadata:
      variant_bitrate : 320000
Stream mapping:
  Stream #0:4 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
[hls,applehttp @ 02d12cc0] No longer receiving playlist 1
frame=   89 fps=0.0 q=-1.0 size=     520kB time=00:00:03.04 bitrate=1400.4kbits/
frame=  179 fps=176 q=-1.0 size=     978kB time=00:00:06.03 bitrate=1327.6kbits/
frame=  269 fps=173 q=-1.0 size=    1452kB time=00:00:09.03 bitrate=1316.7kbits/
frame=  359 fps=171 q=-1.0 size=    1997kB time=00:00:12.02 bitrate=1360.2kbits/
frame=  449 fps=169 q=-1.0 size=    2538kB time=00:00:15.02 bitrate=1383.8kbits/
frame=  539 fps=168 q=-1.0 size=    3087kB time=00:00:18.04 bitrate=1401.6kbits/
frame=  629 fps=168 q=-1.0 size=    3654kB time=00:00:21.03 bitrate=1422.8kbits/
frame=  719 fps=165 q=-1.0 size=    4217kB time=00:00:24.03 bitrate=1437.5kbits/
frame=  809 fps=164 q=-1.0 size=    4787kB time=00:00:27.02 bitrate=1451.0kbits/
frame=  900 fps=177 q=-1.0 Lsize=    5488kB time=00:00:30.04 bitrate=1496.2kbits
/s
video:5227kB audio:235kB subtitle:0kB other streams:0kB global headers:0kB muxin
g overhead: 0.483450%
[ffmpeg] Downloaded 5619544 bytes
[download] 100% of 5.36MiB
```

**Comment by yan12125** [comment]
Thanks for these reports and sorry for the late response. Twitter will be fixed in the next version.
