### ISSUE TITLE
Adding support for new ARTE playlists

### ISSUE THREAD

**Issue by mcymo** [rg3/youtube-dl#9632]
---

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

---

---

Since the site is already well supported (Arte)

```
$ youtube-dl --list-extractors |grep -i arte
arte.tv
arte.tv:+7
arte.tv:cinema
arte.tv:concert
arte.tv:creative
arte.tv:ddc
arte.tv:embed
arte.tv:future
arte.tv:info
arte.tv:magazine
```
this is not a completely new site, but it seems like ARTE has added a playlist format which as of yet fails to download:  
  
EXAMPLE URL: http://www.arte.tv/guide/de/plus7/?country=DE#collection/PL-013263/ARTETV

INPUT: youtube-dl -v  'http://www.arte.tv/guide/de/plus7/?country=DE#collection/PL-013263/ARTETV'

OUTPUT:
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.arte.tv/guide/de/plus7/?country=DE#collection/PL-013263/ARTETV']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.05.21.2
[debug] Python version 2.7.6 - Linux-3.13.0-86-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 11.3, avprobe 11.3, ffmpeg N-77547-g2893dbf, ffprobe N-77547-g2893dbf, rtmpdump 2.4
[debug] Proxy map: {}
[generic] ARTETV: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ARTETV: Downloading webpage
[generic] ARTETV: Extracting information
ERROR: Unsupported URL: http://www.arte.tv/guide/de/plus7/?country=DE#collection/PL-013263/ARTETV
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1413, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 280, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=etree.TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 269, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: syntax error: line 1, column 0
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 676, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 341, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2105, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.arte.tv/guide/de/plus7/?country=DE#collection/PL-013263/ARTETV
``` 

MORE EXAMPLE URLS:  
- http://www.arte.tv/guide/de/playlists?country=DE#collection/PL-012987/ARTETV  
- http://www.arte.tv/guide/de/playlists?country=DE#collection/PL-013257/ARTETV  
- http://www.arte.tv/guide/de/playlists?country=DE#collection/PL-013072/ARTETV  
- http://www.arte.tv/guide/de/playlists?country=DE#collection/PL-013190/ARTETV
  
So it would be nice to add these new playlists to the existing ARTE-extractors.

---

On a side-note: Thx to everybody involved in this great utility.

**Comment by dstftw** [comment]
Fixed in youtube-dl 2016.06.02.
