### ISSUE TITLE
Problem with original.livestream

### ISSUE THREAD

**Issue by Greg03** [rg3/youtube-dl#9635]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.05.21.2*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2016.05.21.2**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
C:\YT\ffmpeg\bin>C:\YT\ffmpeg\bin\youtube-dl.exe http://original.livestream.com/alcatrazindiretta/video?clipId=pla_7611df9c-a62e-40fa-b38d-ceb93348314a -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://original.livestream.com/alcatrazindiretta/video?clipId=pla_7611df9c-a62e-40fa-b38d-ceb93348314a', u'-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.05.21.2
[debug] Python version 2.7.10 - Windows-8-6.2.9200
[debug] exe versions: ffmpeg N-80117-gdac030d, ffprobe N-80117-gdac030d
[debug] Proxy map: {}
[livestream:original] pla_7611df9c-a62e-40fa-b38d-ceb93348314a: Downloading XML
[livestream:original] pla_7611df9c-a62e-40fa-b38d-ceb93348314a: Downloading JSON metadata
[livestream:original] pla_7611df9c-a62e-40fa-b38d-ceb93348314a: Downloading m3u8 information
[debug] Invoking downloader on u'http://mobilestr3.livestream.com/onDemand/ls/alcatrazindiretta/flv_1c33d320-ccfc-4ebe-90b7-6435ffa51875/chunklist.m3u8?wowzasessionid=1428253220'
[download] 010516-pla_7611df9c-a62e-40fa-b38d-ceb93348314a.mp4 has already been downloaded
[download] 100% of 0.00B
[ffmpeg] Fixing malformated aac bitstream in "010516-pla_7611df9c-a62e-40fa-b38d-ceb93348314a.mp4"
[debug] ffmpeg command line: ffmpeg -y -i file:010516-pla_7611df9c-a62e-40fa-b38d-ceb93348314a.mp4 -c copy -f mp4 -bsf:a aac_adtstoasc file:010516-pla_7611df9c-a62e-40fa-b38d-ceb93348314a.temp.mp4
ERROR: file:010516-pla_7611df9c-a62e-40fa-b38d-ceb93348314a.mp4: Invalid data found when processing input
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 1782, in post_process
  File "youtube_dl\postprocessor\ffmpeg.pyo", line 511, in run
  File "youtube_dl\postprocessor\ffmpeg.pyo", line 172, in run_ffmpeg
  File "youtube_dl\postprocessor\ffmpeg.pyo", line 168, in run_ffmpeg_multiple_files
FFmpegPostProcessorError


C:\YT\ffmpeg\bin>
```

---

### *Problem with original.livestream*

Hi!

I'm not a programmator and I do not speak english well, so maybe it's a problem with the installation. Anyway, I can download videos from Youtube but not from original.livestream.

Thank you

**Comment by Greg03** [comment]
Up!
