### ISSUE TITLE
Can't download playlists form music.yandex.ru

### ISSUE THREAD

**Issue by cikoriicabachkov** [rg3/youtube-dl#9637]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.05.30*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.05.30**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

```
➜  29.05 youtube-dl --verbose https://music.yandex.ru/users/cikoriicabachkov/playlists/1006
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://music.yandex.ru/users/cikoriicabachkov/playlists/1006']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.05.30
[debug] Python version 2.7.6 - Linux-3.13.0-86-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.18-6, avprobe 9.18-6
[debug] Proxy map: {}
[yandexmusic:playlist] 1006: Downloading missing tracks JSON
ERROR: An extractor error has occurred. (caused by KeyError(u'playlist',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 341, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/yandexmusic.py", line 223, in _real_extract
    })['playlist']
KeyError: u'playlist'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 676, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 347, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
ExtractorError: An extractor error has occurred. (caused by KeyError(u'playlist',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

### Description of your *issue*, suggested solution and other information

I can't download shared playlists from music.yandex.ru.

**Comment by dstftw** [comment]
Post the output of `youtube-dl --verbose --dump-pages https://music.yandex.ru/users/cikoriicabachkov/playlists/1006`.

**Comment by cikoriicabachkov** [comment]
```
➜  29.05 youtube-dl --verbose --dump-pages https://music.yandex.ru/users/cikoriicabachkov/playlists/1006
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'--dump-pages', u'https://music.yandex.ru/users/cikoriicabachkov/playlists/1006']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.05.30
[debug] Python version 2.7.6 - Linux-3.13.0-86-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: none
[debug] Proxy map: {}
[yandexmusic:playlist] 1006: Downloading missing tracks JSON
[yandexmusic:playlist] Dumping request to https://music.yandex.ru/handlers/playlist.jsx
ewogICAgInR5cGUiOiAiY2FwdGNoYSIsCiAgICAiY2FwdGNoYSI6IHsKICAgICAgICAiaW1nLXVybCI6ICJodHRwczovL211c2ljLnlhbmRleC5ydS9jYXB0Y2hhaW1nP2FIUjBjSE02THk5dVlpNWpZWEIwWTJoaExubGhibVJsZUM1dVpYUXZhVzFoWjJVX2EyVjVQVGd3V1ZkcFJ6RTVUbE54Wkc0eVFYZHdSM1JyUVZFelptaG1UblF6WjFZNV8wLzE0NjQ1NDk3MTQvOGI3ZmNhMDhlZGY4ZWJiODkzMDYzOTE4ODYwYWI2YzRfNmQ5ZjdiNWZmYTcwOTU0ZmMwZDhjOWZkODFkMjEwZTQiLAogICAgICAgICJrZXkiOiAiODBZV2lHMTlOU3FkbjJBd3BHdGtBUTNmaGZOdDNnVjlfMC8xNDY0NTQ5NzE0LzhiN2ZjYTA4ZWRmOGViYjg5MzA2MzkxODg2MGFiNmM0X2YyZGE5ZTBkZmIwODcxZmI3ZDdhZjNmY2EwZTkzMWU0IiwKICAgICAgICAic3RhdHVzIjogIiIsCiAgICAgICAgImNhcHRjaGEtcGFnZSI6ICJodHRwczovL211c2ljLnlhbmRleC5ydS9zaG93Y2FwdGNoYT9yZXRwYXRoPWh0dHBzJTNBLy9tdXNpYy55YW5kZXgucnUvdXNlcnMvY2lrb3JpaWNhYmFjaGtvdi9wbGF5bGlzdHMvMTAwNl9lNGU5MDcyMTY5NThmYTJlODlhNTljZDZmNmY1NDEwZCZ0PTAvMTQ2NDU0OTcxNC84YjdmY2EwOGVkZjhlYmI4OTMwNjM5MTg4NjBhYjZjNCZzPTc1MzczNjU4NzllMTE2YThkMjk1ZjQ5ZGY1NjA4Y2UzIgogICAgfQp9Cg==
ERROR: An extractor error has occurred. (caused by KeyError(u'playlist',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 341, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/yandexmusic.py", line 223, in _real_extract
    })['playlist']
KeyError: u'playlist'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 676, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 347, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
ExtractorError: An extractor error has occurred. (caused by KeyError(u'playlist',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by dstftw** [comment]
See https://github.com/rg3/youtube-dl/issues/8260#issuecomment-172295172.
