### ISSUE TITLE
Spankwire - ValueError: need more than 1 value to unpack

### ISSUE THREAD

**Issue by analogged** [rg3/youtube-dl#9657]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.05.30.2**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)

### Full verbose output:

```
[root@test~]# youtube --version
2016.05.30.2
[root@test~]# youtube -v -j http://www.spankwire.com/Cute-gamer-babe-with-glasses-in-hard-threesome-sex/video4829711/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'-j', u'http://www.spankwire.com/Cute-gamer-babe-with-glasses-in-hard-threesome-sex/video4829711/']
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
[debug] youtube-dl version 2016.05.30.2
[debug] Python version 2.6.6 - Linux-2.6.32-042stab108.5-x86_64-with-centos-6.7-Final
[debug] exe versions: none
[debug] Proxy map: {}
Traceback (most recent call last):
  File "/usr/lib64/python2.6/runpy.py", line 122, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.6/runpy.py", line 34, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube/youtube_dl/__init__.py", line 421, in main
  File "/usr/local/bin/youtube/youtube_dl/__init__.py", line 411, in _real_main
  File "/usr/local/bin/youtube/youtube_dl/YoutubeDL.py", line 1736, in download
  File "/usr/local/bin/youtube/youtube_dl/YoutubeDL.py", line 676, in extract_info
  File "/usr/local/bin/youtube/youtube_dl/extractor/common.py", line 341, in extract
  File "/usr/local/bin/youtube/youtube_dl/extractor/spankwire.py", line 99, in _real_extract
ValueError: need more than 1 value to unpack


```

---

### Description of issue

youtube-dl outputs a `ValueError: need more than 1 value to unpack
` error when trying to download certain Spankwire.com videos.

Video used in this example - http://www.spankwire.com/Cute-gamer-babe-with-glasses-in-hard-threesome-sex/video4829711/

Other videos with the same issue:
 - http://www.spankwire.com/Attractive-Donna-Bell-gets-anally-fucked-hard-in-few-poses/video4852751/
 - http://www.spankwire.com/Perfect-girl-Chloe-Amour-loves-hot-and-wild-sauna-sex-action/video4821961/
- http://www.spankwire.com/Cute-secretary-having-pasionate-sex-action-on-office-desk/video4829731/

**Comment by dstftw** [comment]
Fixed in youtube-dl 2016.06.02.
