### ISSUE TITLE
[vk] Unable to extract vars

### ISSUE THREAD

**Issue by kotofond** [rg3/youtube-dl#9691]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.06.03*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.06.03**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
D:\>youtube-dl --verbose https://vk.com/1tv?z=video-25380626_456239892%2Fvideos-25380626%2Fpl_-25380626_-2
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'https://vk.com/1tv?z=video-25380626_456239892%2Fvideos-25380626%2Fpl_-25380626_-2']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.06.03
[debug] Python version 3.5.1 - Windows-10-10.0.10586-SP0
[debug] exe versions: avconv 11.3, avprobe 11.3, ffmpeg N-78358-g674cc26, ffprobe N-78358-g674cc26, rtmpdump 2.4
[debug] Proxy map: {}
[vk] -25380626_456239892: Downloading webpage
ERROR: Unable to extract vars; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 676, in extract_info
    ie_result = ie.extract(url)
  File "c:\python35\lib\site-packages\youtube_dl\extractor\common.py", line 341, in extract
    return self._real_extract(url)
  File "c:\python35\lib\site-packages\youtube_dl\extractor\vk.py", line 296, in _real_extract
    data_json = self._search_regex(r'var\s+vars\s*=\s*({.+?});', info_page, 'vars')
  File "c:\python35\lib\site-packages\youtube_dl\extractor\common.py", line 644, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract vars; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by garilla22** [comment]
**You just need to put quotes**

**Comment by kotofond** [comment]
Thanks but didn't help:
```
D:\>youtube-dl --verbose "https://vk.com/1tv?z=video-25380626_456239892%2Fvideos-25380626%2Fpl_-25380626_-2"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'https://vk.com/1tv?z=video-25380626_456239892%2Fvideos-25380626%2Fpl_-25380626_-2']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.06.03
[debug] Python version 3.5.1 - Windows-10-10.0.10586-SP0
[debug] exe versions: avconv 11.3, avprobe 11.3, ffmpeg N-78358-g674cc26, ffprobe N-78358-g674cc26, rtmpdump 2.4
[debug] Proxy map: {}
[vk] -25380626_456239892: Downloading webpage
ERROR: Unable to extract vars; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 676, in extract_info
    ie_result = ie.extract(url)
  File "c:\python35\lib\site-packages\youtube_dl\extractor\common.py", line 341, in extract
    return self._real_extract(url)
  File "c:\python35\lib\site-packages\youtube_dl\extractor\vk.py", line 296, in _real_extract
    data_json = self._search_regex(r'var\s+vars\s*=\s*({.+?});', info_page, 'vars')
  File "c:\python35\lib\site-packages\youtube_dl\extractor\common.py", line 644, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract vars; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by garilla22** [comment]
try to Life image kali linux
