### ISSUE TITLE
Please support thesixtyone.com

### ISSUE THREAD

**Issue by starrychloe** [rg3/youtube-dl#9714]
Please support http://www.thesixtyone.com/maryatmidnight/song/StrawberriesandCream/yvWtLp0c4GQ/

ERROR: Unsupported URL: http://www.thesixtyone.com/maryatmidnight/song/StrawberriesandCream/yvWtLp0c4GQ/

Version: 2016.05.21.2

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

```
C:\Users\Chloe\Music>youtube-dl -v -x --audio-format mp3 --audio-quality 3   http://www.thesixtyone.com/maryatmidnight/song/StrawberriesandCream/yvWtLp0c4GQ/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'-x', u'--audio-format', u'mp3', u'--audio-quality', u'3', u'http://www.thesixtyone.com/maryatmidnight/song/StrawberriesandCream/yvWtLp0c4GQ/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.05.21.2
[debug] Python version 2.7.10 - Windows-8-6.2.9200
[debug] exe versions: ffmpeg 3.0.1, ffprobe 3.0.1
[debug] Proxy map: {}
[generic] yvWtLp0c4GQ: Requesting header
WARNING: Falling back on generic information extractor.
[generic] yvWtLp0c4GQ: Downloading webpage
[generic] yvWtLp0c4GQ: Extracting information
ERROR: Unsupported URL: http://www.thesixtyone.com/maryatmidnight/song/StrawberriesandCream/yvWtLp0c4GQ/
Traceback (most recent call last):
  File "youtube_dl\extractor\generic.pyo", line 1413, in _real_extract
  File "youtube_dl\compat.pyo", line 280, in compat_etree_fromstring
  File "youtube_dl\compat.pyo", line 269, in _XML
  File "xml\etree\ElementTree.pyo", line 1642, in feed
  File "xml\etree\ElementTree.pyo", line 1506, in _raiseerror
ParseError: mismatched tag: line 52, column 2
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 676, in extract_info
  File "youtube_dl\extractor\common.pyo", line 341, in extract
  File "youtube_dl\extractor\generic.pyo", line 2105, in _real_extract
UnsupportedError: Unsupported URL: http://www.thesixtyone.com/maryatmidnight/song/StrawberriesandCream/yvWtLp0c4GQ/
```

**Comment by starrychloe** [comment]
BTW viewing the network request in Chrome for the stream and using 'Copy curl request' works.
