### ISSUE TITLE
Can't download particular youtube video in Debian, works in OS X

### ISSUE THREAD

**Issue by duckpuppy** [rg3/youtube-dl#9724]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.06.03**

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)

When downloading a playlist on a MacMini running Debian Jessie, youtube-dl froze when trying a particular video.  Downloading that video directly also hangs, verbose output below.  It is important to note that all other videos in the playlist downloaded fine, and skipping this video using `--playlist-start` allowed me to continue the rest of the playlist - only this video has an issue.

However - I tried this on my Macbook Pro running OSX El Capitan, and it worked.

```
$ youtube-dl -v -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]' "https://www.youtube.com/watch?v=2bO8TDrkxC4"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'-f', u'bestvideo[ext=mp4]+bestaudio[ext=m4a]', u'https://www.youtube.com/watch?v=2bO8TDrkxC4']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.06.03
[debug] Python version 2.7.9 - Linux-3.16.0-4-686-pae-i686-with-debian-8.4
[debug] exe versions: avconv 11.6-6, avprobe 11.6-6
[debug] Proxy map: {}
[youtube] 2bO8TDrkxC4: Downloading webpage
[youtube] 2bO8TDrkxC4: Downloading video info webpage
[youtube] 2bO8TDrkxC4: Extracting video information
[youtube] 2bO8TDrkxC4: Downloading MPD manifest
[debug] Invoking downloader on u'https://r2---sn-5uaeznes.googlevideo.com/videoplayback?id=d9b3bc4c3ae4c42e&itag=137&source=youtube&requiressl=yes&mm=31&nh=IgpwcjAyLmF0bDIyKgkxMjcuMC4wLjE&pl=19&initcwndbps=337500&mv=m&ms=au&mn=sn-5uaeznes&ratebypass=yes&mime=video/mp4&gir=yes&clen=168657408&lmt=1442812898280477&dur=557.264&mt=1465328411&signature=1F4293C8253A1E6F992F43EE28C1551EEBCA5067.45AF1CF2E52FEB6F2B38FAFF18D2906EC8AE175F&sver=3&fexp=9416126,9416891,9418405,9419452,9422342,9422596,9423554,9424134,9426985,9428398,9431012,9433096,9433380,9433858,9433946,9434000,9434182,9435526,9435666,9435876,9436994,9437066,9437078,9437091,9437393,9437552,9437675,9437776&key=dg_yt0&upn=UUf_axCXmz8&ip=40.138.162.10&ipbits=0&expire=1465350496&sparams=ip,ipbits,expire,id,itag,source,requiressl,mm,nh,pl,initcwndbps,mv,ms,mn,ratebypass,mime,gir,clen,lmt,dur'
ERROR: unable to download video data: <urlopen error [Errno 101] Network is unreachable>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1638, in process_info
    partial_success = dl(fname, new_info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1586, in dl
    return fd.download(name, info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/common.py", line 350, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/downloader/http.py", line 58, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1946, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/utils.py", line 943, in https_open
    req, **kwargs)
  File "/usr/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 101] Network is unreachable>
```

Verbose output from OSX (working download)

```
$youtube-dl -v -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]' "https://www.youtube.com/watch?v=2bO8TDrkxC4"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'-f', u'bestvideo[ext=mp4]+bestaudio[ext=m4a]', u'https://www.youtube.com/watch?v=2bO8TDrkxC4']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.06.03
[debug] Python version 2.7.11 - Darwin-15.5.0-x86_64-i386-64bit
[debug] exe versions: avconv 11.4, avprobe 11.4, ffmpeg 3.0.2, ffprobe 3.0.2
[debug] Proxy map: {}
[youtube] 2bO8TDrkxC4: Downloading webpage
[youtube] 2bO8TDrkxC4: Downloading video info webpage
[youtube] 2bO8TDrkxC4: Extracting video information
[youtube] 2bO8TDrkxC4: Downloading MPD manifest
[debug] Invoking downloader on u'https://r2---sn-5uaeznes.googlevideo.com/videoplayback?id=d9b3bc4c3ae4c42e&itag=137&source=youtube&requiressl=yes&pl=21&mv=m&ms=au&initcwndbps=3722500&nh=IgpwcjA0LmF0bDIyKgkxMjcuMC4wLjE&mn=sn-5uaeznes&mm=31&ratebypass=yes&mime=video/mp4&gir=yes&clen=168657408&lmt=1442812898280477&dur=557.264&sver=3&mt=1465328731&signature=8776B1BAA41E939E186793340ADB78D109842982.5179C20A26655F3E091F27AE8FAAE8DFA0B3EC62&upn=UCxONCKMcjk&key=dg_yt0&fexp=9408209,9412859,9416126,9416313,9416891,9418778,9422596,9424417,9428398,9429983,9431012,9432684,9432825,9433096,9433380,9433425,9433456,9433773,9433946,9435527,9435667,9435727,9435876,9435917,9435957,9436394,9436809,9437066,9437553,9437756&ip=66.6.147.81&ipbits=0&expire=1465350617&sparams=ip,ipbits,expire,id,itag,source,requiressl,pl,mv,ms,initcwndbps,nh,mn,mm,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: Dish Best Served – Episode 11 – Red vs. Blue Season 13-2bO8TDrkxC4.f137.mp4
[download] 100% of 160.84MiB in 00:14
[debug] Invoking downloader on u'https://r2---sn-5uaeznes.googlevideo.com/videoplayback?id=d9b3bc4c3ae4c42e&itag=140&source=youtube&requiressl=yes&pl=21&mv=m&ms=au&initcwndbps=3722500&nh=IgpwcjA0LmF0bDIyKgkxMjcuMC4wLjE&mn=sn-5uaeznes&mm=31&ratebypass=yes&mime=audio/mp4&gir=yes&clen=8852095&lmt=1442812017441136&dur=557.325&sver=3&mt=1465328731&signature=12FD48B103837FBA8397338CB8D13D28AD7796CC.8EE8F4E3BFA747FE84A601BE9F751E535ECE789F&upn=UCxONCKMcjk&key=dg_yt0&fexp=9408209,9412859,9416126,9416313,9416891,9418778,9422596,9424417,9428398,9429983,9431012,9432684,9432825,9433096,9433380,9433425,9433456,9433773,9433946,9435527,9435667,9435727,9435876,9435917,9435957,9436394,9436809,9437066,9437553,9437756&ip=66.6.147.81&ipbits=0&expire=1465350617&sparams=ip,ipbits,expire,id,itag,source,requiressl,pl,mv,ms,initcwndbps,nh,mn,mm,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: Dish Best Served – Episode 11 – Red vs. Blue Season 13-2bO8TDrkxC4.f140.m4a
[download] 100% of 8.44MiB in 00:00
[ffmpeg] Merging formats into "Dish Best Served – Episode 11 – Red vs. Blue Season 13-2bO8TDrkxC4.mp4"
[debug] ffmpeg command line: avconv -y -i 'file:Dish Best Served – Episode 11 – Red vs. Blue Season 13-2bO8TDrkxC4.f137.mp4' -i 'file:Dish Best Served – Episode 11 – Red vs. Blue Season 13-2bO8TDrkxC4.f140.m4a' -c copy -map 0:v:0 -map 1:a:0 'file:Dish Best Served – Episode 11 – Red vs. Blue Season 13-2bO8TDrkxC4.temp.mp4'
Deleting original file Dish Best Served – Episode 11 – Red vs. Blue Season 13-2bO8TDrkxC4.f137.mp4 (pass -k to keep)
Deleting original file Dish Best Served – Episode 11 – Red vs. Blue Season 13-2bO8TDrkxC4.f140.m4a (pass -k to keep)
```

**Comment by dstftw** [comment]
As seen from the log you have a connectivity issue. You also have different IP addresses that explains why it does work under OS X. Can you download it under OS X via the same network interface? Try disabling IP v6 with `-4`.

**Comment by yan12125** [comment]
Closing as no feedback for a long time.

**Comment by duckpuppy** [comment]
There is no connectivity issue there - that single video was the only one from the entire playlist that didn't download on the Debian box.  Yes, the IP addresses are different between OSX and Debian, they're different machines, but the Debian box did not have any issues downloading any other youtube videos other than that single video.  It was not a connectivity issue.

**Comment by duckpuppy** [comment]
I just tried again.  It failed again... however, just to test connectivity, I actually WATCHED the video on the same machine while trying to download it.  Viewing is fine.  Download failed.

**Comment by yan12125** [comment]
Could you run the following command on both machines and post the outputs?

```
curl -v "https://r2---sn-5uaeznes.googlevideo.com/"
```

**Comment by yan12125** [comment]
If you don't provide necessary information, there's nothing we can do but closing the issue.
