### ISSUE TITLE
Crunchyroll subtitle error

### ISSUE THREAD

**Issue by kitokirisaki** [rg3/youtube-dl#9728]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.06.03**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [x] Other

---

## The .ass and .srt subtitle-files don't embed. If i use the command i get 2 files: .flv .ass. after ffmpeg render the file to the mp4 i get the error.

```
[ffmpeg] Converting video from flv to mp4, Destination: Re -ZERO -Starting Life in Another World- Folge 1A – Das Ende vom Anfang und der Anfang vom Ende (Teil 1)-702401.mp4
[debug] ffmpeg command line: ffmpeg -y -i 'file:Re -ZERO -Starting Life in Another World- Folge 1A – Das Ende vom Anfang und der Anfang vom Ende (Teil 1)-702401.flv' 'file:Re -ZERO -Starting Life in Another World- Folge 1A – Das Ende vom Anfang und der Anfang vom Ende (Teil 1)-702401.mp4'
Deleting original file Re -ZERO -Starting Life in Another World- Folge 1A – Das Ende vom Anfang und der Anfang vom Ende (Teil 1)-702401.flv (pass -k to keep)
[ffmpeg] Embedding subtitles in 'Re -ZERO -Starting Life in Another World- Folge 1A – Das Ende vom Anfang und der Anfang vom Ende (Teil 1)-702401.mp4'
[debug] ffmpeg command line: ffmpeg -y -i 'file:Re -ZERO -Starting Life in Another World- Folge 1A – Das Ende vom Anfang und der Anfang vom Ende (Teil 1)-702401.mp4' -i 'file:Re -ZERO -Starting Life in Another World- Folge 1A – Das Ende vom Anfang und der Anfang vom Ende (Teil 1)-702401.deDE.ass' -map 0 -c copy -map -0:s -c:s mov_text -map 1:0 -metadata:s:s:0 language=deu 'file:Re -ZERO -Starting Life in Another World- Folge 1A – Das Ende vom Anfang und der Anfang vom Ende (Teil 1)-702401.temp.mp4'

[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.06.03
[debug] Python version 2.7.9 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.5
[debug] exe versions: ffmpeg 3.0.2, ffprobe 3.0.2, rtmpdump 2.4                             
[debug] Proxy map: {}                                                                                 
ERROR: Press [q] to stop, [?] for help
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1782, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 382, in run
    self.run_ffmpeg_multiple_files(input_files, temp_filename, opts)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 168, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
FFmpegPostProcessorError
```

It is possible, to implement the following FFMPEG Command for ass subtitles

```
ffmpeg -i $INPUT.mp4 -c:a copy -vf ass=$ASSFILE $OUTPUTFILE.mp4
```

The comand work fine

[fulllog.txt](https://github.com/rg3/youtube-dl/files/304739/fulllog.txt)

---

PS: Sorry for my english

**Comment by dstftw** [comment]
I've already suggested to embed srt that works **just fine**. Proof:
```
> py -2.6 .\youtube_dl\__main__.py http://www.crunchyroll.com/rezero-starting-life-in-another-world-/rezero-starting-life-in-another-world-das-ende-vom-anfang-und-der-anfang-vom-ende-teil-1-702401 -f best --sub-lang deDE --write-sub --sub-format srt --embed-subs --recode-video mp4 -k -v
[debug] System config: []
[debug] User config: [u'-o', u'%(title)s-%(id)s-f%(format_id)s.%(ext)s']
[debug] Command-line args: [u'http://www.crunchyroll.com/rezero-starting-life-in-another-world-/rezero-starting-life-in-another-world-das-ende-vom-anfang-und-der-anfang-vom-ende-teil-1-702401', u'-f', u'best', u'--sub-lang', u'deDE', u'--write-sub', u'--sub-format', u'srt', u'--embed-subs', u'--recode-video', u'mp4', u'-k', u'-v']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.06.03
[debug] Git HEAD: 33d9f37
[debug] Python version 2.6.2 - Windows-post2008Server-6.2.9200
[debug] exe versions: ffmpeg 3.0, ffprobe 3.0, rtmpdump 2.4
[debug] Proxy map: {}
[Crunchyroll] 702401: Downloading webpage
[Crunchyroll] 702401: Downloading media info for 360p
[Crunchyroll] 702401: Downloading media info for 480p
[Crunchyroll] 702401: Downloading media info for 720p
[Crunchyroll] 702401: Downloading media info for 1080p
[Crunchyroll] 702401: Downloading media info
[Crunchyroll] 702401: Downloading subtitles for English (US)
[Crunchyroll] 702401: Downloading subtitles for العربية
[Crunchyroll] 702401: Downloading subtitles for Italiano
[Crunchyroll] 702401: Downloading subtitles for Deutsch
[info] Writing video subtitles to: Re -ZERO -Starting Life in Another World- Episode 1A – The End of the Beginning and the Beginning of the End (Part 1)-702401-f1080p.deDE.srt
[debug] Invoking downloader on u'rtmpe://cp150757.edgefcs.net/ondemand/?auth=daEa2cFd3amaUaZbpdXdaa5aWcIaAd5a4cW-bxwdq0-dHa-pCEzqqJADuv&aifp=0009&slist=c21/s/ve2189043/video.mp4'
[download] Destination: Re -ZERO -Starting Life in Another World- Episode 1A – The End of the Beginning and the Beginning of the End (Part 1)-702401-f1080p.flv
[debug] rtmpdump command line: rtmpdump --verbose -r 'rtmpe://cp150757.edgefcs.net/ondemand/?auth=daEa2cFd3amaUaZbpdXdaa5aWcIaAd5a4cW-bxwdq0-dHa-pCEzqqJADuv&aifp=0009&slist=c21/s/ve2189043/video.mp4' -o 'Re -ZERO -Starting Life in Another World- Episode 1A – The End of the Beginning and the Beginning of the End (Part 1)-702401-f1080p.flv.part' --playpath mp4:c21/s/ve2189043/video.mp4 --resume --skip 1
[rtmpdump] RTMPDump v2.4 GIT-2015-12-14 (Compiled by KSV)
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 2
[rtmpdump] DEBUG: Parsed host    : cp150757.edgefcs.net
[rtmpdump] DEBUG: Parsed app     : ondemand/?auth=daEa2cFd3amaUaZbpdXdaa5aWcIaAd5a4cW-bxwdq0-dHa-pCEzqqJADuv&aifp=0009&slist=c21/s/ve2189043/video.mp4
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Protocol : RTMPE
[rtmpdump] DEBUG: Hostname : cp150757.edgefcs.net
[rtmpdump] DEBUG: Port     : 1935
[rtmpdump] DEBUG: Playpath : mp4:c21/s/ve2189043/video.mp4
[rtmpdump] DEBUG: tcUrl    : rtmpe://cp150757.edgefcs.net:1935/ondemand/?auth=daEa2cFd3amaUaZbpdXdaa5aWcIaAd5a4cW-bxwdq0-dHa-pCEzqqJADuv&aifp=0009&slist=c21/s/ve2189043/video.mp4
[rtmpdump] DEBUG: app      : ondemand/?auth=daEa2cFd3amaUaZbpdXdaa5aWcIaAd5a4cW-bxwdq0-dHa-pCEzqqJADuv&aifp=0009&slist=c21/s/ve2189043/video.mp4
[rtmpdump] DEBUG: live     : no
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: Setting buffer time to: 36000000ms
[rtmpdump] Connecting ...
[rtmpdump] DEBUG: RTMP_Connect1, ... connected, handshaking
[rtmpdump] DEBUG: HandShake: Client type: 06
[rtmpdump] DEBUG: HandShake: DH pubkey position: 395
[rtmpdump] DEBUG: HandShake: Client digest offset: 1135
[rtmpdump] DEBUG: HandShake: Initial client digest:
[rtmpdump] DEBUG: 92 fc 0c 96 77 85 30 6b b5 e7 51 91 cb 96 0e 27
[rtmpdump] DEBUG: 7f c1 c2 7b e3 ca 9e c3 31 07 c1 4b b2 6c 34 2d
[rtmpdump] DEBUG: HandShake: Type Answer   : 08
[rtmpdump] WARNING: HandShake: Type mismatch: client sent 6, server answered 8
[rtmpdump] DEBUG: HandShake: Server Uptime : 166899029
[rtmpdump] DEBUG: HandShake: FMS Version   : 5.0.7.1
[rtmpdump] DEBUG: HandShake: Server DH public key offset: 451
[rtmpdump] DEBUG: HandShake: Secret key:
[rtmpdump] DEBUG: 5b d0 fd 9a 64 9c 07 f8 98 1c 2e d1 c0 5c 4a 63
[rtmpdump] DEBUG: a6 4b 8c b6 23 d8 23 7f f0 f7 f0 18 eb 21 08 e2
[rtmpdump] DEBUG: ac dc 27 67 d7 3e 46 ee 1c 99 db c7 87 a7 d2 8c
[rtmpdump] DEBUG: bb 82 40 41 4c d9 37 dc 56 2f 05 c3 6a 43 4a 2e
[rtmpdump] DEBUG: db 1e ec 6f 9b 10 51 f7 55 02 05 d8 11 b1 32 57
[rtmpdump] DEBUG: 98 aa 4e 09 41 49 7d 82 63 22 e0 58 71 b4 51 65
[rtmpdump] DEBUG: b6 b1 94 b4 0d 67 dd b6 21 81 40 a1 b6 2e 82 9a
[rtmpdump] DEBUG: 22 dc fe 27 26 75 91 e9 26 9b 6e a6 20 f2 30 15
[rtmpdump] DEBUG: RC4 Out Key:
[rtmpdump] DEBUG: 4a 49 09 58 4e 18 32 b8 4c b3 d0 b6 80 5e d3 ca
[rtmpdump] DEBUG: RC4 In Key:
[rtmpdump] DEBUG: 8b 91 cf 87 7a d7 5a 46 bf 5b e1 7e d2 0e 1e 08
[rtmpdump] DEBUG: HandShake: Calculated digest key from secure key and server digest:
[rtmpdump] DEBUG: 70 c1 53 ea fb 66 cc c3 5c ca 93 dc 93 25 9c f6
[rtmpdump] DEBUG: 12 5f c3 9d 6c 6d e2 29 e2 01 ad d1 75 bb 2c c7
[rtmpdump] DEBUG: HandShake: Client signature calculated:
[rtmpdump] DEBUG: 15 ac 10 26 c6 ff 2a 5e 1f 84 29 13 1d 0a 04 30
[rtmpdump] DEBUG: da 29 79 52 6a f7 43 35 fc 0f e7 42 26 60 98 cd
[rtmpdump] DEBUG: HandShake: Server sent signature:
[rtmpdump] DEBUG: a7 26 cd 15 66 f0 36 80 7a 09 aa 9e 8f 47 78 ac
[rtmpdump] DEBUG: 44 27 af ef cb 17 8f 76 ec 24 eb a0 05 43 51 5f
[rtmpdump] DEBUG: HandShake: Digest key:
[rtmpdump] DEBUG: eb 66 b7 d8 23 e6 be 0a 14 a6 af a5 c0 33 c1 df
[rtmpdump] DEBUG: d7 ec b3 c6 24 96 f7 0a 3f 1c 8d 1b 1e 8c 26 49
[rtmpdump] DEBUG: HandShake: Signature calculated:
[rtmpdump] DEBUG: a7 26 cd 15 66 f0 36 80 7a 09 aa 9e 8f 47 78 ac
[rtmpdump] DEBUG: 44 27 af ef cb 17 8f 76 ec 24 eb a0 05 43 51 5f
[rtmpdump] DEBUG: HandShake: Genuine Adobe Flash Media Server
[rtmpdump] DEBUG: HandShake: Handshaking finished....
[rtmpdump] DEBUG: RTMP_Connect1, handshaked
[rtmpdump] DEBUG: Invoking connect
[rtmpdump] INFO: Connected...
[rtmpdump] DEBUG: HandleServerBW: server BW = 1250000
[rtmpdump] DEBUG: HandleClientBW: client BW = 1250000 2
[rtmpdump] DEBUG: HandleChangeChunkSize, received: chunk size change to 4096
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 242 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:            no-name, STRING:  _result>
[rtmpdump] DEBUG: Property: <Name:            no-name, NUMBER:  1.00>
[rtmpdump] DEBUG: Property: <Name:            no-name, OBJECT>
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:             fmsVer, STRING:  FMS/5,0,7,7054>
[rtmpdump] DEBUG: Property: <Name:       capabilities, NUMBER:  127.00>
[rtmpdump] DEBUG: Property: <Name:               mode, NUMBER:  1.00>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: Property: <Name:            no-name, OBJECT>
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:              level, STRING:  status>
[rtmpdump] DEBUG: Property: <Name:               code, STRING:  NetConnection.Connect.Success>
[rtmpdump] DEBUG: Property: <Name:        description, STRING:  Connection succeeded.>
[rtmpdump] DEBUG: Property: <Name:     objectEncoding, NUMBER:  3.00>
[rtmpdump] DEBUG: Property: <Name:               data, ECMA_ARRAY>
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:            version, STRING:  5,0,7,7054>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_result>
[rtmpdump] DEBUG: HandleInvoke, received result for method call <connect>
[rtmpdump] DEBUG: sending ctrl, type: 0x0003
[rtmpdump] DEBUG: Invoking createStream
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 21 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:            no-name, STRING:  onBWDone>
[rtmpdump] DEBUG: Property: <Name:            no-name, NUMBER:  0.00>
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <onBWDone>
[rtmpdump] DEBUG: Invoking checkBandwidth
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 29 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:            no-name, STRING:  _result>
[rtmpdump] DEBUG: Property: <Name:            no-name, NUMBER:  2.00>
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: Property: <Name:            no-name, NUMBER:  1.00>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_result>
[rtmpdump] DEBUG: HandleInvoke, received result for method call <createStream>
[rtmpdump] DEBUG: SendPlay, seekTime=0, stopTime=0, sending play: mp4:c21/s/ve2189043/video.mp4
[rtmpdump] DEBUG: Invoking play
[rtmpdump] DEBUG: sending ctrl, type: 0x0003
[rtmpdump] DEBUG: RTMP_ClientPacket, flex message, size 10266 bytes, not fully supported
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:            no-name, STRING:  onBWCheck>
[rtmpdump] DEBUG: Property: <Name:            no-name, NUMBER:  2147483650.00>
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: Property: <Name:            no-name, STRING:  ! v 1 < m N % h 9 n G t % J M p 1 f # t % ^ u ( I ^ ) < 5 : ? @ a V O < S n [ * y N y T e * 3 P 1 F ! 6 #   + ( w > W \ - : = ` _ 6 q $ - 0 e x G . ' 4 [ * / 0 / & _ l ] @ k 8 ) > i | + & C " ! 6 / D 5 r ; X 9 . g 4 % 6 - 0 Q & a L c b U X i " 7 >>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <onBWCheck>
[rtmpdump] DEBUG: HandleCtrl, received ctrl, type: 4, len: 6
[rtmpdump] DEBUG: HandleCtrl, Stream IsRecorded 1
[rtmpdump] DEBUG: HandleChangeChunkSize, received: chunk size change to 4096
[rtmpdump] DEBUG: HandleCtrl, received ctrl, type: 0, len: 6
[rtmpdump] DEBUG: HandleCtrl, Stream Begin 1
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 192 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:            no-name, STRING:  onStatus>
[rtmpdump] DEBUG: Property: <Name:            no-name, NUMBER:  0.00>
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: Property: <Name:            no-name, OBJECT>
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:              level, STRING:  status>
[rtmpdump] DEBUG: Property: <Name:               code, STRING:  NetStream.Play.Reset>
[rtmpdump] DEBUG: Property: <Name:        description, STRING:  Playing and resetting c21/s/ve2189043/video.mp4.>
[rtmpdump] DEBUG: Property: <Name:            details, STRING:  c21/s/ve2189043/video.mp4>
[rtmpdump] DEBUG: Property: <Name:           clientid, STRING:  pAArgHAA>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <onStatus>
[rtmpdump] DEBUG: HandleInvoke, onStatus: NetStream.Play.Reset
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 186 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:            no-name, STRING:  onStatus>
[rtmpdump] DEBUG: Property: <Name:            no-name, NUMBER:  0.00>
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: Property: <Name:            no-name, OBJECT>
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:              level, STRING:  status>
[rtmpdump] DEBUG: Property: <Name:               code, STRING:  NetStream.Play.Start>
[rtmpdump] DEBUG: Property: <Name:        description, STRING:  Started playing c21/s/ve2189043/video.mp4.>
[rtmpdump] DEBUG: Property: <Name:            details, STRING:  c21/s/ve2189043/video.mp4>
[rtmpdump] DEBUG: Property: <Name:           clientid, STRING:  pAArgHAA>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <onStatus>
[rtmpdump] DEBUG: HandleInvoke, onStatus: NetStream.Play.Start
[rtmpdump] Starting download at: 0.000 kB
[rtmpdump] DEBUG: RTMP_ClientPacket, received: notify 24 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:            no-name, STRING:  |RtmpSampleAccess>
[rtmpdump] DEBUG: Property: <Name:            no-name, BOOLEAN: FALSE>
[rtmpdump] DEBUG: Property: <Name:            no-name, BOOLEAN: FALSE>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: ignoring too small audio packet: size: 0
[rtmpdump] DEBUG: RTMP_ClientPacket, received: notify 44 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:            no-name, STRING:  onStatus>
[rtmpdump] DEBUG: Property: <Name:            no-name, OBJECT>
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:               code, STRING:  NetStream.Data.Start>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: RTMP_ClientPacket, received: notify 494 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:            no-name, STRING:  onMetaData>
[rtmpdump] DEBUG: Property: <Name:            no-name, ECMA_ARRAY>
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:           duration, NUMBER:  1516.01>
[rtmpdump] DEBUG: Property: <Name:       moovPosition, NUMBER:  32.00>
[rtmpdump] DEBUG: Property: <Name:              width, NUMBER:  1920.00>
[rtmpdump] DEBUG: Property: <Name:             height, NUMBER:  1080.00>
[rtmpdump] DEBUG: Property: <Name:       videocodecid, STRING:  avc1>
[rtmpdump] DEBUG: Property: <Name:       audiocodecid, STRING:  mp4a>
[rtmpdump] DEBUG: Property: <Name:         avcprofile, NUMBER:  100.00>
[rtmpdump] DEBUG: Property: <Name:           avclevel, NUMBER:  40.00>
[rtmpdump] DEBUG: Property: <Name:             aacaot, NUMBER:  2.00>
[rtmpdump] DEBUG: Property: <Name:     videoframerate, NUMBER:  23.98>
[rtmpdump] DEBUG: Property: <Name:    audiosamplerate, NUMBER:  44100.00>
[rtmpdump] DEBUG: Property: <Name:      audiochannels, NUMBER:  2.00>
[rtmpdump] DEBUG: Property: <Name:          trackinfo, STRICT_ARRAY>
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:            no-name, OBJECT>
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:             length, NUMBER:  18172500.00>
[rtmpdump] DEBUG: Property: <Name:          timescale, NUMBER:  11988.00>
[rtmpdump] DEBUG: Property: <Name:           language, STRING:  und>
[rtmpdump] DEBUG: Property: <Name:  sampledescription, STRICT_ARRAY>
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:            no-name, OBJECT>
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:         sampletype, STRING:  avc1>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: Property: <Name:            no-name, OBJECT>
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:             length, NUMBER:  66855936.00>
[rtmpdump] DEBUG: Property: <Name:          timescale, NUMBER:  44100.00>
[rtmpdump] DEBUG: Property: <Name:           language, STRING:  und>
[rtmpdump] DEBUG: Property: <Name:  sampledescription, STRICT_ARRAY>
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:            no-name, OBJECT>
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:         sampletype, STRING:  mp4a>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] INFO: Metadata:
[rtmpdump] INFO:   duration                1516.01
[rtmpdump] INFO:   moovPosition            32.00
[rtmpdump] INFO:   width                   1920.00
[rtmpdump] INFO:   height                  1080.00
[rtmpdump] INFO:   videocodecid            avc1
[rtmpdump] INFO:   audiocodecid            mp4a
[rtmpdump] INFO:   avcprofile              100.00
[rtmpdump] INFO:   avclevel                40.00
[rtmpdump] INFO:   aacaot                  2.00
[rtmpdump] INFO:   videoframerate          23.98
[rtmpdump] INFO:   audiosamplerate         44100.00
[rtmpdump] INFO:   audiochannels           2.00
[rtmpdump] INFO: trackinfo:
[rtmpdump] INFO:   length                  18172500.00
[rtmpdump] INFO:   timescale               11988.00
[rtmpdump] INFO:   language                und
[rtmpdump] INFO: sampledescription:
[rtmpdump] INFO:   sampletype              avc1
[rtmpdump] INFO:   length                  66855936.00
[rtmpdump] INFO:   timescale               44100.00
[rtmpdump] INFO:   language                und
[rtmpdump] INFO: sampledescription:
[rtmpdump] INFO:   sampletype              mp4a
[download]  12.5% of ~744.28MiB at  1.18MiB/s ETA 09:10
[rtmpdump] DEBUG: HandleCtrl, received ctrl, type: 6, len: 6
[rtmpdump] DEBUG: HandleCtrl, Ping 166953036
[rtmpdump] DEBUG: sending ctrl, type: 0x0007
[download]  76.2% of ~588.69MiB at  1.18MiB/s ETA 01:58
[rtmpdump] DEBUG: HandleCtrl, received ctrl, type: 6, len: 6
[rtmpdump] DEBUG: HandleCtrl, Ping 167253278
[rtmpdump] DEBUG: sending ctrl, type: 0x0007
[download]  99.9% of ~578.87MiB at  1.19MiB/s ETA 00:00
[rtmpdump] DEBUG: ignoring too small audio packet: size: 0
[rtmpdump] DEBUG: RTMP_ClientPacket, received: notify 102 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:            no-name, STRING:  onPlayStatus>
[rtmpdump] DEBUG: Property: <Name:            no-name, OBJECT>
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:               code, STRING:  NetStream.Play.Complete>
[rtmpdump] DEBUG: Property: <Name:              level, STRING:  status>
[rtmpdump] DEBUG: Property: <Name:           duration, NUMBER:  485.00>
[rtmpdump] DEBUG: Property: <Name:              bytes, NUMBER:  606415447.00>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleCtrl, received ctrl, type: 1, len: 6
[rtmpdump] DEBUG: HandleCtrl, Stream EOF 1
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 196 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:            no-name, STRING:  onStatus>
[rtmpdump] DEBUG: Property: <Name:            no-name, NUMBER:  0.00>
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: Property: <Name:            no-name, OBJECT>
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:              level, STRING:  status>
[rtmpdump] DEBUG: Property: <Name:               code, STRING:  NetStream.Play.Stop>
[rtmpdump] DEBUG: Property: <Name:        description, STRING:  Stopped playing c21/s/ve2189043/video.mp4.>
[rtmpdump] DEBUG: Property: <Name:            details, STRING:  c21/s/ve2189043/video.mp4>
[rtmpdump] DEBUG: Property: <Name:           clientid, STRING:  pAArgHAA>
[rtmpdump] DEBUG: Property: <Name:             reason, STRING:  >
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <onStatus>
[rtmpdump] DEBUG: HandleInvoke, onStatus: NetStream.Play.Stop
[rtmpdump] DEBUG: Invoking deleteStream
[rtmpdump] DEBUG: Got Play.Complete or Play.Stop from server. Assuming stream is complete
[download]  99.9% of ~578.90MiB at  1.19MiB/s ETA 00:00
[rtmpdump] DEBUG: RTMP_Read returned: 0
[rtmpdump] Download complete
[rtmpdump] DEBUG: Closing connection.
[rtmpdump] 606415254 bytes
[download] 100% of 578.32MiB
[ffmpeg] Converting video from flv to mp4, Destination: Re -ZERO -Starting Life in Another World- Episode 1A – The End of the Beginning and the Beginning of the End (Part 1)-702401-f1080p.mp4
[debug] ffmpeg command line: ffmpeg -y -i 'file:Re -ZERO -Starting Life in Another World- Episode 1A – The End of the Beginning and the Beginning of the End (Part 1)-702401-f1080p.flv' 'file:Re -ZERO -Starting Life in Another World- Episode 1A – The End of the Beginning and the Beginning of the End (Part 1)-702401-f1080p.mp4'
[ffmpeg] Embedding subtitles in 'Re -ZERO -Starting Life in Another World- Episode 1A – The End of the Beginning and the Beginning of the End (Part 1)-702401-f1080p.mp4'
[debug] ffmpeg command line: ffmpeg -y -i 'file:Re -ZERO -Starting Life in Another World- Episode 1A – The End of the Beginning and the Beginning of the End (Part 1)-702401-f1080p.mp4' -i 'file:Re -ZERO -Starting Life in Another World- Episode 1A – The End of the Beginning and the Beginning of the End (Part 1)-702401-f1080p.deDE.srt' -map 0 -c copy -map -0:s -c:s mov_text -map 1:0 -metadata:s:s:0 language=deu 'file:Re -ZERO -Starting Life in Another World- Episode 1A – The End of the Beginning and the Beginning of the End (Part 1)-702401-f1080p.temp.mp4'
```
```
> ffmpeg.exe -i '.\Re -ZERO -Starting Life in Another World- Episode 1A – The End of the Begi
nning and the Beginning of the End (Part 1)-702401-f1080p.mp4'
ffmpeg version 3.0 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 5.3.0 (GCC)
  configuration: --enable-gpl --enable-version3 --disable-w32threads --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libdcadec --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-decklink --enable-zlib
  libavutil      55. 17.103 / 55. 17.103
  libavcodec     57. 24.102 / 57. 24.102
  libavformat    57. 25.100 / 57. 25.100
  libavdevice    57.  0.101 / 57.  0.101
  libavfilter     6. 31.100 /  6. 31.100
  libswscale      4.  0.100 /  4.  0.100
  libswresample   2.  0.101 /  2.  0.101
  libpostproc    54.  0.100 / 54.  0.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '.\Re -ZERO -Starting Life in Another World- Episode 1A тАУ The End of the Beginning and the Beginning of the End (Part 1)-702401-f1080p.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf57.25.100
  Duration: 00:25:16.06, start: 0.000000, bitrate: 2119 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], 1982 kb/s, 23.98 fps, 23.98 tbr, 24k tbn, 47.95 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 130 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
    Stream #0:2(deu): Subtitle: mov_text (tx3g / 0x67337874), 0 kb/s (default)
    Metadata:
      handler_name    : SubtitleHandler
```
Hardsubs are already requested in #9655 and not supported at the moment.
