### ISSUE TITLE
Support playlists on CC (was: Key and Peele on CC)

### ISSUE THREAD

**Issue by bouchard** [rg3/youtube-dl#9741]
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2016.06.03**
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [X] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

```

youtube-dl -v http://www.cc.com/shows/key-and-peele/video-guide
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.cc.com/shows/key-and-peele/video-guide']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.06.03
[debug] Python version 2.7.10 - Darwin-15.5.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.0.2, ffprobe 3.0.2, rtmpdump 2.4
[debug] Proxy map: {}
[ComedyCentral] video-guide: Downloading webpage
ERROR: Unable to extract mgid; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/mtv.py", line 193, in _extract_mgid
    og_url = self._og_search_video_url(webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 744, in _og_search_video_url
    return self._html_search_regex(regexes, html, name, **kargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 653, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 644, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 676, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 341, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/mtv.py", line 215, in _real_extract
    mgid = self._extract_mgid(webpage)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/mtv.py", line 209, in _extract_mgid
    r'embed/(mgid:.+?)["\'&?/]', sm4_embed, 'mgid')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 644, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract mgid; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://www.cc.com/video-clips/1dl1pp/key-and-peele-exclusive---vandaveon-and-mike-fix-key---peele---episode-2---uncensored
- Playlist: http://www.cc.com/shows/key-and-peele/video-guide

**Comment by TRox1972** [comment]
The single video provided works fine for me. So this would be a support for ComedyCentral playlists?

**Comment by bouchard** [comment]
My apologies, yes that would be correct.

**Comment by yan12125** [comment]
Superseded by a newer issue at #10003.
