### ISSUE TITLE
Drop Python 3.2 support

### ISSUE THREAD

**Issue by yan12125** [rg3/youtube-dl#9751]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.06.11.3**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [x] Other

---

The latest pip has dropped Python 3.2 support (pypa/pip#3156) . As a result, I can't install pip:

```
$ python3.2 ~/tmp/get-pip.py --user
/tmp/tmpyhlooe/pip.zip/pip/_vendor/pkg_resources/__init__.py:80: UserWarning: Support for Python 3.0-3.2 has been dropped. Future versions will fail here.
Traceback (most recent call last):
  File "/home/yen/tmp/get-pip.py", line 19177, in <module>
    main()
  File "/home/yen/tmp/get-pip.py", line 194, in main
    bootstrap(tmpdir=tmpdir)
  File "/home/yen/tmp/get-pip.py", line 82, in bootstrap
    import pip
  File "/tmp/tmpyhlooe/pip.zip/pip/__init__.py", line 16, in <module>
  File "/tmp/tmpyhlooe/pip.zip/pip/vcs/mercurial.py", line 9, in <module>
  File "/tmp/tmpyhlooe/pip.zip/pip/download.py", line 36, in <module>
  File "/tmp/tmpyhlooe/pip.zip/pip/utils/ui.py", line 15, in <module>
  File "/tmp/tmpyhlooe/pip.zip/pip/_vendor/progress/bar.py", line 48
    empty_fill = u'∙'
                      ^
SyntaxError: invalid syntax
```

Reasons for dropping:

* According to dstufft, requests by Python 3.2 clients account for less than 0.5% traffic on pypi.org
* pip does not support Python 3.2. I need pip to install nose and PyCrypto (for #8201)
* Although Ubuntu 12.04 LTS (EOL on April 2017) still ships Python 3.2, users can use Python 2.7

A last bit: re on Python 3.2 is broken.
```
$ python3.2 test/test_all_urls.py  
..F.............
======================================================================
FAIL: test_no_duplicates (__main__.TestAllURLsMatching)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_all_urls.py", line 93, in test_no_duplicates
    self.assertTrue(ie.suitable(url), '%s should match URL %r' % (type(ie).__name__, url))
AssertionError: False is not true : UnicodeBOMIE should match URL '\ufeffhttp://www.youtube.com/watch?v=BaW_jenozKc'

----------------------------------------------------------------------
Ran 16 tests in 1.708s

FAILED (failures=1)

$ python3.2
Python 3.2.6 (default, May 23 2016, 01:08:02) 
[GCC 6.1.1 20160501] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import re
>>> re.match(r'\ufeff', '\ufeff')
>>> 
```

**Comment by yan12125** [comment]
dstufft's statistics for pypi.org: https://caremad.io/2015/04/a-year-of-pypi-downloads/

**Comment by hugovk** [comment]
+1

More reasons for dropping 3.2:

* Unsupported since [2016-02-27](https://en.wikipedia.org/wiki/CPython#Version_history)
* pip 8 no longer supports Python 3.2 ([link](https://pip.pypa.io/en/stable/news/))
* Coverage 4 no longer supports Python 3.2 ([link](https://bitbucket.org/ned/coveragepy/issues/407/coverage-failing-on-python-325-using))
* Virtually no PyPI traffic (June 2016) https://github.com/pypa/pip/issues/3796

**Comment by yan12125** [comment]
@hugovk Thanks for those info. I've opened #14515.
