### ISSUE TITLE
d8.tv : ERROR unable to download video data

### ISSUE THREAD

**Issue by Animis09** [rg3/youtube-dl#9772]
youtube-dl "http://www.d8.tv/d8-divertissement/pid5206-d8-voyage-au-bout-de-la-nuit.html?vid=1396210" -f 'HLS-1314' -o "test" --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://www.d8.tv/d8-divertissement/pid5206-d8-voyage-au-bout-de-la-nuit.html?vid=1396210', u'-f', u'HLS-1314', u'-o', u'test', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.06.12
[debug] Proxy map: {}
[Canalplus] 1396210: Downloading video JSON
[Canalplus] 1396210: Downloading f4m manifest
[Canalplus] 1396210: Downloading m3u8 information
[debug] Invoking downloader on u'http://us-cplus-aka.canal-plus.com/i/1605/31/1173676_1156_,200k,400k,800k,1500k,.mp4.csmil/index_3_av.m3u8'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 151
[download] Destination: test
[download]  99.3% of ~249.31MiB at 909.21KiB/s ETA 00:00ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1648, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1590, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 350, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/hls.py", line 83, in real_download
    success = ctx['dl'].download(frag_filename, {'url': frag_url})
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 350, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 58, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1950, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 407, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 520, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 445, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 379, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 528, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found

Thank you for your help.

**Comment by dstftw** [comment]
The last fragment in m3u8 of the format you've selected is missing on hoster's side. Select another format.
