### ISSUE TITLE
cannot retreive infos from Gdrive folders (unsupported URL)

### ISSUE THREAD

**Issue by eadmaster** [rg3/youtube-dl#9797]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.06.14*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2016.06.14**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v --skip-download  --get-id --get-title  "https://drive.google.com/drive/folders/HIDDEN"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'--skip-download', u'--get-id', u'--get-title', u'https://drive.google.com/drive/folders/HIDDEN']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.06.14
[debug] Python version 2.7.6 - Linux-3.14.20-i686-with-glibc2.4
[debug] exe versions: avconv 9.16-6, avprobe 9.16-6, ffmpeg 9.16-6, rtmpdump 2.4
[debug] Proxy map: {}
WARNING: Falling back on generic information extractor.
ERROR: Unsupported URL: https://support.google.com/drive/answer/6286662?p=unsupported_browser&rd=1
Traceback (most recent call last):
  File "/tmp/youtube-dl/youtube-dl/youtube_dl/extractor/generic.py", line 1440, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/tmp/youtube-dl/youtube-dl/youtube_dl/compat.py", line 2524, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/tmp/youtube-dl/youtube-dl/youtube_dl/compat.py", line 2513, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: syntax error: line 1, column 0
Traceback (most recent call last):
  File "/tmp/youtube-dl/youtube-dl/youtube_dl/YoutubeDL.py", line 676, in extract_info
    ie_result = ie.extract(url)
  File "/tmp/youtube-dl/youtube-dl/youtube_dl/extractor/common.py", line 342, in extract
    return self._real_extract(url)
  File "/tmp/youtube-dl/youtube-dl/youtube_dl/extractor/generic.py", line 2140, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://support.google.com/drive/answer/6286662?p=unsupported_browser&rd=1
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* required an account credentials please provide them or explain how one can obtain them.

**Comment by yan12125** [comment]
Google Drive folders are not supported yet.

**Comment by upintheairsheep** [comment]
Try YT-DLP
