### ISSUE TITLE
Unable to download https://mobile.twitter.com's video.

### ISSUE THREAD

**Issue by antdude** [rg3/youtube-dl#9800]
Example:

$ youtube-dl -v https://twitter.com/i/moments/741297043239542784
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'https://twitter.com/i/moments/741297043239542784']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.06.14
[debug] Python version 3.4.2 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.5
[debug] exe versions: ffmpeg 3.0.2-2, ffprobe 3.0.2-2, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 741297043239542784: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 741297043239542784: Downloading webpage
[generic] 741297043239542784: Extracting information
[redirect] Following redirect to https://mobile.twitter.com/i/nojs_router?path=/i/moments/741297043239542784
[generic] 741297043239542784: Requesting header
[redirect] Following redirect to https://mobile.twitter.com/i/moments/741297043239542784?m=1
[generic] 741297043239542784?m=1: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 741297043239542784?m=1: Downloading webpage
[generic] 741297043239542784?m=1: Extracting information
ERROR: Unsupported URL: https://mobile.twitter.com/i/moments/741297043239542784?m=1
Traceback (most recent call last):
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 676, in extract_info
    ie_result = ie.extract(url)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/common.py", line 342, in extract
    return self._real_extract(url)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2140, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://mobile.twitter.com/i/moments/741297043239542784?m=1

**Comment by yan12125** [comment]
Twitter Moments are not supported yet.
