### ISSUE TITLE
mpsyt exited with the following errors

### ISSUE THREAD

**Issue by mjonyh** [rg3/youtube-dl#9805]
**After a searching the following error occurs below the playlist result:**
ERROR: Unable to download webpage: [Errno 104] Connection reset by peer (caused by ConnectionResetError(104, 'Connection reset by peer')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**After selecting the number the following error occur and exited from mpsyt:**
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/mps_youtube/main.py", line 1138, in playsong
    streams.get(song, force=failcount, callback=screen.writestatus)
  File "/usr/lib/python3.5/site-packages/mps_youtube/streams.py", line 50, in get
    p = get_pafy(vid, force=force, callback=callback)
  File "/usr/lib/python3.5/site-packages/mps_youtube/util.py", line 175, in get_pafy
    p = pafy.new(item.ytid, callback=callback_fn)
  File "/usr/lib/python3.5/site-packages/pafy/pafy.py", line 122, in new
    return Pafy(url, basic, gdata, size, callback, ydl_opts)
  File "/usr/lib/python3.5/site-packages/pafy/backend_youtube_dl.py", line 29, in __init__
    super(YtdlPafy, self).__init__(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/pafy/backend_shared.py", line 95, in __init__
    self._fetch_basic()
  File "/usr/lib/python3.5/site-packages/pafy/backend_youtube_dl.py", line 41, in _fetch_basic
    raise IOError(str(e).replace('YouTube said', 'Youtube says'))

Traceback (most recent call last):
  File "/usr/sbin/mpsyt", line 9, in <module>
    load_entry_point('mps-youtube==0.2.6', 'console_scripts', 'mpsyt')()
  File "/usr/lib/python3.5/site-packages/mps_youtube/main.py", line 3695, in main
    if matchfunction(i.function, i.regex, userinput):
  File "/usr/lib/python3.5/site-packages/mps_youtube/main.py", line 3644, in matchfunction
    func(*matches)
  File "/usr/lib/python3.5/site-packages/mps_youtube/main.py", line 2427, in play
    play_range(songlist, shuffle, repeat, override)
  File "/usr/lib/python3.5/site-packages/mps_youtube/main.py", line 2519, in play_range
    returncode = playsong(song, override=override)
  File "/usr/lib/python3.5/site-packages/mps_youtube/main.py", line 1150, in playsong
    return playsong(song, failcount=failcount, override=override)
  File "/usr/lib/python3.5/site-packages/mps_youtube/main.py", line 1150, in playsong
    return playsong(song, failcount=failcount, override=override)
  File "/usr/lib/python3.5/site-packages/mps_youtube/main.py", line 1150, in playsong
    return playsong(song, failcount=failcount, override=override)
  File "/usr/lib/python3.5/site-packages/mps_youtube/main.py", line 1162, in playsong
    cmd, songdata = generate_real_playerargs(song, override, failcount)
  File "/usr/lib/python3.5/site-packages/mps_youtube/main.py", line 1031, in generate_real_playerargs
    q, audio, cached = failcount, not video, g.streams[song.ytid]
KeyError: 'Q6NkiY9fylw'

**youtube-dl --version
2016.06.11.3**

**Comment by yan12125** [comment]
Ask mpsyt people. It's their problem.
