### ISSUE TITLE
[bbc.co.uk] Support playlists

### ISSUE THREAD

**Issue by smartbit** [rg3/youtube-dl#9812]
```
$ youtube-dl --write-sub http://www.bbc.co.uk/iplayer/episodes/b05rcz9v --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--write-sub', u'http://www.bbc.co.uk/iplayer/episodes/b05rcz9v', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.06.16
[debug] Python version 2.7.10 - Darwin-15.5.0-x86_64-i386-64bit
[debug] exe versions: avconv 11.4, avprobe 11.4
[debug] Proxy map: {}
[bbc] b05rcz9v: Downloading webpage
ERROR: Unable to extract playlist data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 676, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 342, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/bbc.py", line 892, in _real_extract
    webpage, 'playlist data'),
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 645, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract playlist data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
individual downloads work fine

**Comment by yan12125** [comment]
BBC playlists are not supported yet.

**Comment by smartbit** [comment]
Thank you for informing and for updating the title.

**Comment by dstftw** [comment]
bbc.co.uk playlists are supported since youtube-dl 2016.06.18.1.
