### ISSUE TITLE
Site support request [carambatv.ru]

### ISSUE THREAD

**Issue by YogSottot** [rg3/youtube-dl#9815]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.06.16**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Site support request (request for adding support for a new site)

```
$ youtube-dl -Fv http://carambatv.ru/movie/bad-comedian/razborka-v-manile/
[debug] System config: []
[debug] User config: [u'--sub-lang', u'ru,en']
[debug] Command-line args: [u'-Fv', u'http://carambatv.ru/movie/bad-comedian/razborka-v-manile/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.06.16
[debug] Python version 2.7.10 - Linux-4.4.12-gentoo-i686
[debug] exe versions: ffmpeg 3.0.2, ffprobe 3.0.2
[debug] Proxy map: {}
[generic] razborka-v-manile: Requesting header
WARNING: Falling back on generic information extractor.
[generic] razborka-v-manile: Downloading webpage
[generic] razborka-v-manile: Extracting information
ERROR: Unsupported URL: http://carambatv.ru/movie/bad-comedian/razborka-v-manile/
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/generic.py", line 1440, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/lib/python2.7/site-packages/youtube_dl/compat.py", line 2524, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/lib/python2.7/site-packages/youtube_dl/compat.py", line 2513, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 27, column 121
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 676, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 342, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/generic.py", line 2140, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://carambatv.ru/movie/bad-comedian/razborka-v-manile/
```

- Single video: http://carambatv.ru/movie/bad-comedian/razborka-v-manile/
- Single video: http://carambatv.ru/humor/golden-moustache/you_need_help/
- Single video: http://carambatv.ru/?p=81985

**Comment by dstftw** [comment]
carambatv is supported since youtube-dl 2016.06.18.1.

**Comment by alex3kov** [comment]
Doesn't work (stopped working?) on 2018.12.31. Example URL https://carambatv.ru/bad-comedian/divergent-hunger-games-in-twilight
```
youtube-dl "https://carambatv.ru/bad-comedian/divergent-hunger-games-in-twilight"
[CarambaTVPage] divergent-hunger-games-in-twilight: Downloading webpage
ERROR: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
~/removable_media/15G: youtube-dl --verbose "https://carambatv.ru/bad-comedian/divergent-hunger-games-in-twilight"
[debug] System config: []
[debug] User config: ['--no-playlist', '--output', '~/removable_media/15G/%(title)s.%(ext)s', '--ignore-errors']
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://carambatv.ru/bad-comedian/divergent-hunger-games-in-twilight']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.12.31
[debug] Python version 3.7.1 (CPython) - Linux-4.19.12-zen1-1-zen-x86_64-with-arch
[debug] exe versions: ffmpeg n4.1, ffprobe n4.1
[debug] Proxy map: {}
[CarambaTVPage] divergent-hunger-games-in-twilight: Downloading webpage
ERROR: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 793, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/carambatv.py", line 99, in _real_extract
    webpage, 'video id')
  File "/usr/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 983, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
