### ISSUE TITLE
[aenetworks] Add support for playlists

### ISSUE THREAD

**Issue by CollinChaffin** [rg3/youtube-dl#9816]
Searched open issues and see that history.com is shown to be supported as of early 2015, yet when I run against it using the latest 6/16 build, I get the following error which seems to indicate it may be a bug to report:

youtube-dl "http://www.history.com/shows/ancient-aliens/season-1" --verbose
[debug] System config: []
[debug] User config: ['--continue', '--ignore-errors', '--no-overwrites', '-f','best', '--output', '%(playlist_index)s_%(upload_date)s_%(height)sP_%(title)s.%(ext)s']
[debug] Command-line args: ['http://www.history.com/shows/ancient-aliens/season-1', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.06.16
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-80256-g0a9e781, ffprobe N-80256-g0a9e781
[debug] Proxy map: {}
[aenetworks] season-1: Downloading webpage
ERROR: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpxzf4ix2_\build\youtube_dl\YoutubeDL.py", line 676, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpxzf4ix2_\build\youtube_dl\extractor\common.py", line 342, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpxzf4ix2_\build\youtube_dl\extractor\aenetworks.py", line 68, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpxzf4ix2_\build\youtube_dl\extractor\common.py", line 645, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Let me know if there is any other way I can help test.  Thanks!

**Comment by dstftw** [comment]
Playlists are not supported.
