### ISSUE TITLE
MemoryError using y-dl with torify

### ISSUE THREAD

**Issue by kradan** [rg3/youtube-dl#9817]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.06.18.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)

```
$ torify youtube-dl -v -f 140 -c beWnF4bjpMw
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'-f', u'140', u'-c', u'beWnF4bjpMw']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.06.18.1
[debug] Python version 2.7.11+ - Linux-4.5.0-2-686-pae-i686-with-debian-stretch-sid
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/__init__.py", line 420, in main
    _real_main(argv)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/__init__.py", line 387, in _real_main
    with YoutubeDL(ydl_opts) as ydl:
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 352, in __init__
    self.print_debug_header()
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1991, in print_debug_header
    exe_versions = FFmpegPostProcessor.get_versions(self)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/postprocessor/ffmpeg.py", line 64, in get_versions
    return FFmpegPostProcessor(downloader)._versions
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/postprocessor/ffmpeg.py", line 48, in __init__
    self._determine_executables()
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/postprocessor/ffmpeg.py", line 105, in _determine_executables
    (p, get_exe_version(p, args=['-version'])) for p in programs)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/postprocessor/ffmpeg.py", line 105, in <genexpr>
    (p, get_exe_version(p, args=['-version'])) for p in programs)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/utils.py", line 1713, in get_exe_version
    out = out.decode('ascii', 'ignore')
MemoryError
```

### Description of your *issue*, suggested solution and other information

When I use youtube-dl in combination with torify, a Tor wrapper, youtube-dl runs out of memory when a video download has finished.
During this time you avprobe consumes 100% of the CPU, later half half together with y-dl.
Downloading the video normally without torify works well.

I am glad to test again with future versions.

Thanks for all your work!

**Comment by yan12125** [comment]
It's a known Tor-related bug, see https://github.com/rg3/youtube-dl/issues/402#issuecomment-210873679. Use ```--proxy socks5://ip:port``` instead of wrapper programs like torify or torsocks.
