### ISSUE TITLE
 ERROR: unable to download video data: ''

### ISSUE THREAD

**Issue by levinus** [rg3/youtube-dl#9824]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.06.18.1*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.06.18.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
I am using youtube-dl with some automated scripts and I recognized that they dont work anymore. I could reproduce the problem and I saw it is on youtube-dl. When I trie to download a video it runs fine, first, but then the google servers suddenly stop responing. Sample call:
```
root@levinus:/media/ytdown# youtube-dl -v --print-traffic -x https://www.youtube.com/watch?v=dushZybUYnM --audio-format mp3 -f bestaudio
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'--print-traffic', u'-x', u'https://www.youtube.com/watch?v=dushZybUYnM', u'--audio-format', u'mp3', u'-f', u'bestaudio']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.06.18.1
[debug] Python version 2.7.6 - Linux-2.6.32-042stab113.21-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.18-6, avprobe 9.18-6
[debug] Proxy map: {}
[youtube] dushZybUYnM: Downloading webpage
send: u'GET /watch?v=dushZybUYnM&gl=US&hl=en&has_verified=1&bpctr=9999999999 HTTP/1.1\r\nAccept-Language: en-us,en;q=0.5\r\nAccept-Encoding: gzip, deflate\r\nConnection: close\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nUser-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/47.0 (Chrome)\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nHost: www.youtube.com\r\nCookie: PREF=f1=50000000&hl=en\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: X-XSS-Protection: 1; mode=block; report=https://www.google.com/appserve/security-bugs/log/youtube
header: P3P: CP="This is not a P3P policy! See http://support.google.com/accounts/answer/151657?hl=en for more info."
header: Content-Encoding: gzip
header: Strict-Transport-Security: max-age=604800
header: X-Content-Type-Options: nosniff
header: X-Frame-Options: SAMEORIGIN
header: Content-Type: text/html; charset=utf-8
header: Cache-Control: no-cache
header: Expires: Tue, 27 Apr 1971 19:44:06 EST
header: Date: Sat, 18 Jun 2016 16:47:16 GMT
header: Server: YouTubeFrontEnd
header: Set-Cookie: VISITOR_INFO1_LIVE=G9maM_duqYQ; path=/; domain=.youtube.com; expires=Fri, 17-Feb-2017 04:40:16 GMT; httponly
header: Set-Cookie: YSC=nwQWDYN7CJU; path=/; domain=.youtube.com; httponly
header: Set-Cookie: s_gl=1d69aac621b2f9c0a25dade722d6e24bcwIAAABVUw==; path=/; domain=.youtube.com
header: Alternate-Protocol: 443:quic
header: Alt-Svc: quic=":443"; ma=2592000; v="34,33,32,31,30,29,28,27,26,25"
header: Connection: close
header: Transfer-Encoding: chunked
[youtube] dushZybUYnM: Downloading video info webpage
send: u'GET /get_video_info?&video_id=dushZybUYnM&el=info&ps=default&eurl=&gl=US&hl=en HTTP/1.1\r\nAccept-Language: en-us,en;q=0.5\r\nAccept-Encoding: gzip, deflate\r\nConnection: close\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nUser-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/47.0 (Chrome)\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nHost: www.youtube.com\r\nCookie: YSC=nwQWDYN7CJU; VISITOR_INFO1_LIVE=G9maM_duqYQ; PREF=f1=50000000&hl=en; s_gl=1d69aac621b2f9c0a25dade722d6e24bcwIAAABVUw==\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Content-Encoding: gzip
header: X-Content-Type-Options: nosniff
header: Cache-Control: no-store
header: Strict-Transport-Security: max-age=604800
header: X-XSS-Protection: 1; mode=block; report=https://www.google.com/appserve/security-bugs/log/youtube
header: Expires: Tue, 27 Apr 1971 19:44:06 EST
header: Content-Type: application/x-www-form-urlencoded
header: X-Frame-Options: SAMEORIGIN
header: P3P: CP="This is not a P3P policy! See http://support.google.com/accounts/answer/151657?hl=en for more info."
header: Date: Sat, 18 Jun 2016 16:47:17 GMT
header: Server: YouTubeFrontEnd
header: Set-Cookie: s_gl=1d69aac621b2f9c0a25dade722d6e24bcwIAAABVUw==; path=/; domain=.youtube.com
header: Alternate-Protocol: 443:quic
header: Alt-Svc: quic=":443"; ma=2592000; v="34,33,32,31,30,29,28,27,26,25"
header: Connection: close
header: Transfer-Encoding: chunked
[youtube] dushZybUYnM: Extracting video information
[youtube] dushZybUYnM: Downloading MPD manifest
send: u'GET /api/manifest/dash/ipbits/0/hfr/1/fexp/9414875%2C9416126%2C9416891%2C9419451%2C9420095%2C9422596%2C9428398%2C9431012%2C9432373%2C9433040%2C9433096%2C9433380%2C9433425%2C9433946%2C9434803%2C9434904%2C9434904%2C9435526%2C9435667%2C9435703%2C9435782%2C9435876%2C9435988%2C9436607%2C9436834%2C9437066%2C9437553%2C9437981%2C9439415%2C9439498%2C9439653/source/youtube/signature/825C1393A410729952B3A44ED31D7EFC20949013.3FFB1A14BA070783CA73BFD5C18C2D153A1AC6/upn/tjF4Tm5mUJI/nh/IgpwcjAyLmZyYTE2KgkxMjcuMC4wLjE/expire/1466290037/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/playback_host/r14---sn-4g57knz6.googlevideo.com/key/yt6/sver/3/mv/u/ip/2a05%3A8b81%3A1000%3A298%3A%3A2/mm/31/mn/sn-4g57knz6/sparams/as%2Chfr%2Cid%2Cip%2Cipbits%2Citag%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpl%2Cplayback_host%2Crequiressl%2Csource%2Cexpire/id/o-AETIcGgYhcT0vQAe6tGh2Ce-y3NjE3BTQ3G6B9XclAlS/mt/1466267785/itag/0/pl/48/requiressl/yes/ms/au HTTP/1.1\r\nAccept-Language: en-us,en;q=0.5\r\nAccept-Encoding: gzip, deflate\r\nConnection: close\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nUser-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/47.0 (Chrome)\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nHost: manifest.googlevideo.com\r\n\r\n'
reply: ''
WARNING: [youtube] dushZybUYnM: Skipping DASH manifest: ExtractorError(u'Failed to download MPD manifest: \'\' (caused by BadStatusLine("\'\'",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)
[debug] Invoking downloader on u'https://r14---sn-4g57knz6.googlevideo.com/videoplayback?ipbits=0&sparams=clen%2Cdur%2Cgir%2Cid%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&mime=audio%2Fwebm&keepalive=yes&mm=31&mn=sn-4g57knz6&id=o-AEmaJsAu1IhxPrWsj7Dse4PmniRr4juDTIxnt7VDaH_C&clen=5437264&mt=1466267785&mv=u&ms=au&ip=2a05%3A8b81%3A1000%3A298%3A%3A2&pl=48&itag=251&upn=VfnM_w7EPXk&expire=1466290037&sver=3&nh=IgpwcjAyLmZyYTE2KgkxMjcuMC4wLjE&fexp=9414875%2C9416126%2C9416891%2C9419451%2C9420095%2C9422596%2C9428398%2C9431012%2C9432373%2C9433040%2C9433096%2C9433380%2C9433425%2C9433946%2C9434803%2C9434904%2C9434904%2C9435526%2C9435667%2C9435703%2C9435782%2C9435876%2C9435988%2C9436607%2C9436834%2C9437066%2C9437553%2C9437981%2C9439415%2C9439498%2C9439653&gir=yes&signature=6964B3AAD8A70E788E60086C37F2C95AD9FD3450.7AB18A1B2E978CCFE7083D50431B61E703843087&key=yt6&source=youtube&dur=356.141&lmt=1449588967757027&requiressl=yes&ratebypass=yes'
send: u'GET /videoplayback?ipbits=0&sparams=clen%2Cdur%2Cgir%2Cid%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&mime=audio%2Fwebm&keepalive=yes&mm=31&mn=sn-4g57knz6&id=o-AEmaJsAu1IhxPrWsj7Dse4PmniRr4juDTIxnt7VDaH_C&clen=5437264&mt=1466267785&mv=u&ms=au&ip=2a05%3A8b81%3A1000%3A298%3A%3A2&pl=48&itag=251&upn=VfnM_w7EPXk&expire=1466290037&sver=3&nh=IgpwcjAyLmZyYTE2KgkxMjcuMC4wLjE&fexp=9414875%2C9416126%2C9416891%2C9419451%2C9420095%2C9422596%2C9428398%2C9431012%2C9432373%2C9433040%2C9433096%2C9433380%2C9433425%2C9433946%2C9434803%2C9434904%2C9434904%2C9435526%2C9435667%2C9435703%2C9435782%2C9435876%2C9435988%2C9436607%2C9436834%2C9437066%2C9437553%2C9437981%2C9439415%2C9439498%2C9439653&gir=yes&signature=6964B3AAD8A70E788E60086C37F2C95AD9FD3450.7AB18A1B2E978CCFE7083D50431B61E703843087&key=yt6&source=youtube&dur=356.141&lmt=1449588967757027&requiressl=yes&ratebypass=yes HTTP/1.1\r\nAccept-Encoding: identity\r\nAccept-Language: en-us,en;q=0.5\r\nHost: r14---sn-4g57knz6.googlevideo.com\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nUser-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/47.0 (Chrome)\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nConnection: close\r\n\r\n'
reply: ''
ERROR: unable to download video data: ''
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1648, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1590, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 350, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 58, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1950, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 951, in https_open
    req, **kwargs)
  File "/usr/lib/python2.7/urllib2.py", line 1187, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1051, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 415, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 379, in _read_status
    raise BadStatusLine(line)
BadStatusLine: ''
```
I get the same result when hitting an YouTube video without the audio flags and with -g.
Soundcloud, for example is running fine. Has YouTube blocked me? I had no such high download rate. (~100 Videos in more than 3 month)
Does anybody know what the problem is here?
I had a short time directly after searching for the problem in that I could download videos, after it failed one time.

Thanks for your effort, guys.

**Comment by dstftw** [comment]
Can you watch it in browser from the same network interface in the first place?

**Comment by levinus** [comment]
I could start a VNC server and install the firefox webbrowser (from ubuntu packages). I am able to visit the website, search for videos, open video pages and load, for example the preview pics in the video player (if you try to set a new video position). BUT the video doesnt load. (Black screen or preview pics + loading animation)

**Comment by dstftw** [comment]
Try disabling IPv6 with `-4`.

**Comment by levinus** [comment]
Works now! I turned IPv6 support on a time ago so I wonder that this problem shows now and I didnt connected with the protocol change/support. Thanks! (Do you know why the googlevideo servers do not support or accept IPv6? Usually, google is very far in development at those topics, I think)

**Comment by dstftw** [comment]
Basically, IPv6 should work just fine and it does according to others. Why don't you think it's just some misconfiguration on your side? Have you tried more recent python?

**Comment by levinus** [comment]
I thought about a issue on googles side because IPv6 works fine for me with some other services. But you're right, I'll check my configs. Thanks for your help and your work at youtube-dl!
