### ISSUE TITLE
ImgurAlbum extractor regression

### ISSUE THREAD

**Issue by libjared** [rg3/youtube-dl#9833]
```
$ youtube-dl -v "http://imgur.com/gallery/BIyA6"

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://imgur.com/gallery/BIyA6']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.06.19.1
[debug] Python version 2.7.10 - CYGWIN_NT-10.0-WOW-2.5.1-0.297-5-3-i686-32bit
[debug] exe versions: ffmpeg N-76776-g3c110b0, ffprobe N-76776-g3c110b0
[debug] Proxy map: {}
[ImgurAlbum] BIyA6: Downloading JSON metadata
[download] Downloading playlist: BIyA6
[ImgurAlbum] playlist BIyA6: Collected 9 video ids (downloading 9 of them)
[download] Downloading video 1 of 9
[Imgur] IEhcAND: Downloading webpage
WARNING: unable to extract width; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract height; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/updateon how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
ERROR: No sources found for video IEhcAND. Maybe an image?
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 676, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 342, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/imgur.py", line 66, in _real_extract
    expected=True)
ExtractorError: No sources found for video IEhcAND. Maybe an image?
```

I tried downloading the imgur album, and it looks like there is support for it given the "ImgurAlbum", but this extractor hits an error before completing. This is the latest youtube-dl version available from pip. I'm running on Windows. I searched "imgur" on the issues page and did not find anything so I made this post.

**Comment by yan12125** [comment]
There are no videos in this album. Static images are not supported yet. (See #9337)
