### ISSUE TITLE
Unable to login to Lynda.com site using linkedin username and password.

### ISSUE THREAD

**Issue by ersanjayverma** [rg3/youtube-dl#9843]
I am not able to login to Lynda website using my LinkedIn username and password.
How can i login to Lynda for downloading the videos.

The verbose command output is:

[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.lynda.com/Developer-Cloud-C
omputing-tutorials/Google-App-Engine-Essential-Training/194134-2.html', '--usern
ame', 'PRIVATE', '--password', 'PRIVATE']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.06.20
[debug] Python version 3.5.1 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[lynda:course] Downloading signin page
[lynda:course] Submitting email
ERROR: Unable to login: Please use the "Sign in with LinkedIn" option to sign in
.
Traceback (most recent call last):
  File "c:\myspace\installs\python\python35\lib\site-packages\youtube_dl\extract
or\common.py", line 390, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "c:\myspace\installs\python\python35\lib\site-packages\youtube_dl\Youtube
DL.py", line 1950, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "c:\myspace\installs\python\python35\lib\urllib\request.py", line 471, in
 open
    response = meth(req, response)
  File "c:\myspace\installs\python\python35\lib\urllib\request.py", line 581, in
 http_response
    'http', request, response, code, msg, hdrs)
  File "c:\myspace\installs\python\python35\lib\urllib\request.py", line 509, in
 error
    return self._call_chain(*args)
  File "c:\myspace\installs\python\python35\lib\urllib\request.py", line 443, in
 _call_chain
    result = func(*args)
  File "c:\myspace\installs\python\python35\lib\urllib\request.py", line 589, in
 http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\myspace\installs\python\python35\lib\site-packages\youtube_dl\extract
or\lynda.py", line 53, in _login_step
    'X-Requested-With': 'XMLHttpRequest',
  File "c:\myspace\installs\python\python35\lib\site-packages\youtube_dl\extract
or\common.py", line 535, in _download_json
    encoding=encoding, data=data, headers=headers, query=query)
  File "c:\myspace\installs\python\python35\lib\site-packages\youtube_dl\extract
or\common.py", line 503, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote,
 fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "c:\myspace\installs\python\python35\lib\site-packages\youtube_dl\extract
or\common.py", line 410, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal,
 data=data, headers=headers, query=query)
  File "c:\myspace\installs\python\python35\lib\site-packages\youtube_dl\extract
or\common.py", line 399, in _request_webpage
    raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
youtube_dl.utils.ExtractorError: Unable to download JSON metadata: HTTP Error 50
0: Internal Server Error (caused by <HTTPError 500: 'Internal Server Error'>); p
lease report this issue on https://yt-dl.org/bug . Make sure you are using the l
atest version; see  https://yt-dl.org/update  on how to update. Be sure to call
youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\myspace\installs\python\python35\lib\site-packages\youtube_dl\extract
or\common.py", line 390, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "c:\myspace\installs\python\python35\lib\site-packages\youtube_dl\Youtube
DL.py", line 1950, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "c:\myspace\installs\python\python35\lib\urllib\request.py", line 471, in
 open
    response = meth(req, response)
  File "c:\myspace\installs\python\python35\lib\urllib\request.py", line 581, in
 http_response
    'http', request, response, code, msg, hdrs)
  File "c:\myspace\installs\python\python35\lib\urllib\request.py", line 509, in
 error
    return self._call_chain(*args)
  File "c:\myspace\installs\python\python35\lib\urllib\request.py", line 443, in
 _call_chain
    result = func(*args)
  File "c:\myspace\installs\python\python35\lib\urllib\request.py", line 589, in
 http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\myspace\installs\python\python35\lib\site-packages\youtube_dl\extract
or\lynda.py", line 53, in _login_step
    'X-Requested-With': 'XMLHttpRequest',
  File "c:\myspace\installs\python\python35\lib\site-packages\youtube_dl\extract
or\common.py", line 535, in _download_json
    encoding=encoding, data=data, headers=headers, query=query)
  File "c:\myspace\installs\python\python35\lib\site-packages\youtube_dl\extract
or\common.py", line 503, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote,
 fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "c:\myspace\installs\python\python35\lib\site-packages\youtube_dl\extract
or\common.py", line 410, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal,
 data=data, headers=headers, query=query)
  File "c:\myspace\installs\python\python35\lib\site-packages\youtube_dl\extract
or\common.py", line 399, in _request_webpage
    raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
youtube_dl.utils.ExtractorError: Unable to download JSON metadata: HTTP Error 50
0: Internal Server Error (caused by <HTTPError 500: 'Internal Server Error'>); p
lease report this issue on https://yt-dl.org/bug . Make sure you are using the l
atest version; see  https://yt-dl.org/update  on how to update. Be sure to call
youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\myspace\installs\python\python35\lib\site-packages\youtube_dl\Youtube
DL.py", line 676, in extract_info
    ie_result = ie.extract(url)
  File "c:\myspace\installs\python\python35\lib\site-packages\youtube_dl\extract
or\common.py", line 342, in extract
    self.initialize()
  File "c:\myspace\installs\python\python35\lib\site-packages\youtube_dl\extract
or\common.py", line 336, in initialize
    self._real_initialize()
  File "c:\myspace\installs\python\python35\lib\site-packages\youtube_dl\extract
or\lynda.py", line 26, in _real_initialize
    self._login()
  File "c:\myspace\installs\python\python35\lib\site-packages\youtube_dl\extract
or\lynda.py", line 85, in _login
    'Submitting email', self._SIGNIN_URL)
  File "c:\myspace\installs\python\python35\lib\site-packages\youtube_dl\extract
or\lynda.py", line 58, in _login_step
    self._check_error(response, ('email', 'password'))
  File "c:\myspace\installs\python\python35\lib\site-packages\youtube_dl\extract
or\lynda.py", line 34, in _check_error
    raise ExtractorError('Unable to login: %s' % error, expected=True)
youtube_dl.utils.ExtractorError: Unable to login: Please use the "Sign in with L
inkedIn" option to sign in.

**Comment by ersanjayverma** [comment]
issue came when i login using linkedin credentials only.
