### ISSUE TITLE
youtube_dl.utils.ExtractorError: Could not find JS function 'ur'

### ISSUE THREAD

**Issue by kyroskoh** [rg3/youtube-dl#9870]
Whenever I search for the song title... it crashed.

```
[0;31mERROR:[0m Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 997, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 912, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 975, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/jsinterp.py", line 241, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'ur'
 (caused by ExtractorError("Could not find JS function 'ur'",))
```

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.
