### ISSUE TITLE
ExtractorError: Could not find JS function u'ur'; please report this issue on https://yt-dl.org/bug

### ISSUE THREAD

**Issue by nadtoka** [rg3/youtube-dl#9873]
Looks like issue is still there

[root@HH-Beast www]# youtube-dl --version
2016.05.16
[root@HH-Beast www]# /usr/bin/youtube-dl 'https://www.youtube.com/watch?v=4j3SDYuvas0'  —o '/var/www/domain.com/http/files/[HH]direct_PID41892[HD].mp4'  -f 22 --verbose
[debug] System config: [u'--prefer-free-formats']
[debug] User config: []
[debug] Command-line args: [u'https://www.youtube.com/watch?v=4j3SDYuvas0', u'\u2014o', u'/var/www/direct.animehaven.org/http/files/[HH]direct_PID41892[HD].mp4', u'-f', u'22', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.05.16
[debug] Python version 2.6.6 - Linux-2.6.32-573.12.1.el6.x86_64-x86_64-with-centos-6.7-Final
[debug] exe versions: ffmpeg N-79796-g1e109bb, ffprobe N-79796-g1e109bb
[debug] Proxy map: {}
[youtube] 4j3SDYuvas0: Downloading webpage
[youtube] 4j3SDYuvas0: Downloading video info webpage
[youtube] 4j3SDYuvas0: Extracting video information
[youtube] {22} signature length 40.43, html5 player en_US-vflkX1eCa
[youtube] 4j3SDYuvas0: Downloading player https://s.ytimg.com/yts/jsbin/player-en_US-vflkX1eCa/base.js
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/youtube_dl/extractor/youtube.py", line 995, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python2.6/site-packages/youtube_dl/extractor/youtube.py", line 910, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python2.6/site-packages/youtube_dl/extractor/youtube.py", line 973, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/lib/python2.6/site-packages/youtube_dl/jsinterp.py", line 241, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
ExtractorError: Could not find JS function u'ur'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Could not find JS function u'ur'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/youtube_dl/extractor/youtube.py", line 995, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python2.6/site-packages/youtube_dl/extractor/youtube.py", line 910, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python2.6/site-packages/youtube_dl/extractor/youtube.py", line 973, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/lib/python2.6/site-packages/youtube_dl/jsinterp.py", line 241, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
ExtractorError: Could not find JS function u'ur'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/youtube_dl/YoutubeDL.py", line 676, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.6/site-packages/youtube_dl/extractor/common.py", line 341, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.6/site-packages/youtube_dl/extractor/youtube.py", line 1568, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/usr/lib/python2.6/site-packages/youtube_dl/extractor/youtube.py", line 1005, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
ExtractorError: Signature extraction failed: Traceback (most recent call last):

**Comment by yan12125** [comment]
Already fixed in version 2016.06.23.1.
