### ISSUE TITLE
errored out with list of local files

### ISSUE THREAD

**Issue by thpublic** [rg3/youtube-dl#9889]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.06.25*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2016.06.25**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.06.25
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-F', 'http://www.nationallibertyalliance.org/common-law', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.06.25
[debug] Python version 3.4.4 - Windows-7-6.1.7600-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[generic] common-law: Requesting header
WARNING: Falling back on generic information extractor.
[generic] common-law: Downloading webpage
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpdy42tioh\build\youtube_dl\__init__.py", line 420, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpdy42tioh\build\youtube_dl\__init__.py", line 410, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpdy42tioh\build\youtube_dl\YoutubeDL.py", line 1740, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpdy42tioh\build\youtube_dl\YoutubeDL.py", line 676, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpdy42tioh\build\youtube_dl\extractor\common.py", line 343, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpdy42tioh\build\youtube_dl\extractor\generic.py", line 1412, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpdy42tioh\build\youtube_dl\extractor\common.py", line 390, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpdy42tioh\build\youtube_dl\YoutubeDL.py", line 1950, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpdy42tioh\build\youtube_dl\utils.py", line 842, in http_response
  File "C:\Python\Python34\lib\gzip.py", line 360, in read
  File "C:\Python\Python34\lib\gzip.py", line 449, in _read
  File "C:\Python\Python34\lib\gzip.py", line 482, in _read_eof
  File "C:\Python\Python34\lib\gzip.py", line 286, in _read_exact
EOFError: Compressed file ended before the end-of-stream marker was reached
---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* required an account credentials please provide them or explain how one can obtain them.

Wanted to see what files could be recognized from the provided URL knowing it would use the [generic] extractor, hoped I could pull the mp3s.  Did not expect it to error out with a list of local files.  After running the command, noted neither C:/User/dst nor C:\Python does not exist. FYI.  Have C++ 2010 redistributable installed.

**Comment by yan12125** [comment]
Looks like network problems. Could you try more times?

**Comment by thpublic** [comment]
Tried several more times.  Same response.  I can point youtube-dl at any youtube URL and it works.  I don't have a network problem anywhere else, just this particular site using this command.  Could the site block this request if it sees youtube-dl?

**Comment by yan12125** [comment]
> Could the site block this request if it sees youtube-dl?

I don't think so as the same command runs fine here.
