### ISSUE TITLE
ERROR: Signature extraction failed

### ISSUE THREAD

**Issue by gerard-jos** [rg3/youtube-dl#9891]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.06.25*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ ] I've **verified** and **I assure** that I'm running youtube-dl **2016.06.25**

### Before submitting an *issue* make sure you have:
- [ ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
[root@DESKTOP-Q81VBID Music]# youtube-dl --verbose https://www.youtube.com/watch?v=ovhm9TIQFws
[debug] System config: ['--prefer-free-formats']
[debug] User config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=ovhm9TIQFws']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.06.03
[debug] Python version 3.4.3 - Linux-4.5.7-200.fc23.x86_64-x86_64-with-fedora-23-Twenty_Three
[debug] exe versions: ffmpeg 2.8.7, ffprobe 2.8.7
[debug] Proxy map: {}
[youtube] ovhm9TIQFws: Downloading webpage
[youtube] ovhm9TIQFws: Downloading video info webpage
[youtube] ovhm9TIQFws: Extracting video information
[youtube] {22} signature length 40.40, html5 player en_US-vflLyLvKU
[youtube] ovhm9TIQFws: Downloading player https://s.ytimg.com/yts/jsbin/player-en_US-vflLyLvKU/base.js
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/youtube.py", line 995, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/youtube.py", line 910, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/youtube.py", line 973, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/lib/python3.4/site-packages/youtube_dl/jsinterp.py", line 241, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'ur'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Could not find JS function 'ur'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/youtube.py", line 995, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/youtube.py", line 910, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/youtube.py", line 973, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/lib/python3.4/site-packages/youtube_dl/jsinterp.py", line 241, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'ur'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/youtube.py", line 995, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/youtube.py", line 910, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/youtube.py", line 973, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/lib/python3.4/site-packages/youtube_dl/jsinterp.py", line 241, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'ur'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/youtube_dl/YoutubeDL.py", line 676, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/common.py", line 341, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/youtube.py", line 1568, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/youtube.py", line 1005, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/youtube.py", line 995, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/youtube.py", line 910, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python3.4/site-packages/youtube_dl/extractor/youtube.py", line 973, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/lib/python3.4/site-packages/youtube_dl/jsinterp.py", line 241, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'ur'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Could not find JS function 'ur'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* required an account credentials please provide them or explain how one can obtain them.

Not sure what went wrong worked always fine but not anymore getting this all the time now, sure hope for a fix for this problem

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.

**Comment by gerard-jos** [comment]
Yeah i saw that and immediately installed it like in you're FAQ works perfect again thanks for the fast reply.
