### ISSUE TITLE
[PBS] HTTP streams gives 403 Forbidden

### ISSUE THREAD

**Issue by jerblack** [rg3/youtube-dl#9921]
```
~$ youtube-dl --version
2016.06.26

~$ youtube-dl --verbose http://www.pbs.org/wgbh/frontline/film/suicide-plan/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.pbs.org/wgbh/frontline/film/suicide-plan/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.06.26
[debug] Python version 2.7.11+ - Linux-4.4.0-24-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.6-1ubuntu2, ffprobe 2.8.6-1ubuntu2
[debug] Proxy map: {}
[pbs] suicide-plan: Downloading webpage
[pbs] suicide-plan: Downloading video info JSON
[pbs] suicide-plan: Downloading widget/partnerplayer page
[pbs] suicide-plan: Downloading portalplayer page
[pbs] suicide-plan: Downloading ipad-16x9 video url info
[pbs] suicide-plan: Downloading m3u8 information
[pbs] suicide-plan: Downloading mp4-baseline-16x9 video url info
[pbs] suicide-plan: Downloading mirror-mpeg-4-500kbps video url info
[debug] Invoking downloader on u'http://ga.video.cdn.pbs.org/videos/frontline/002b095e-84ca-47cd-b888-62df6734ab9a/9523/hd-mezzanine-16x9/00003023-mp4-2500k-16x9.mp4'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1648, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1590, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 350, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 58, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1950, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden
```

**Comment by yan12125** [comment]
HTTP links are broken for PBS. Use HLS instead:
```
youtube-dl -v -f 'best[format_id^=hls]' "http://www.pbs.org/wgbh/frontline/film/suicide-plan/"
```
