### ISSUE TITLE
yt-dl not working after update

### ISSUE THREAD

**Issue by userdave** [rg3/youtube-dl#9924]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.06.26*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ ] I've **verified** and **I assure** that I'm running youtube-dl **2016.06.26**

### Before submitting an *issue* make sure you have:
- [ ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.06.26
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```heres what I get after the latest manjaro update

[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'https://youtu.be/x6zypc_LhnM\n']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.06.11.3
[debug] Python version 3.5.1 - Linux-4.4.13-1-MANJARO-x86_64-with-glibc2.3.4
[debug] exe versions: ffmpeg 3.0.2, ffprobe 3.0.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] x6zypc_LhnM: Downloading webpage
[youtube] x6zypc_LhnM: Downloading video info webpage
[youtube] x6zypc_LhnM: Extracting video information
[youtube] {22} signature length 40.40, html5 player en_US-vflLyLvKU
[youtube] x6zypc_LhnM: Downloading player https://s.ytimg.com/yts/jsbin/player-en_US-vflLyLvKU/base.js
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 997, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 912, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 975, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 241, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'ur'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Could not find JS function 'ur'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 997, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 912, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 975, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 241, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'ur'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 997, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 912, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 975, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 241, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'ur'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 676, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 342, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1570, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1007, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 997, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 912, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 975, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/lib/python3.5/site-packages/youtube_dl/jsinterp.py", line 241, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'ur'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Could not find JS function 'ur'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

---

**Comment by dstftw** [comment]
>[debug] youtube-dl version 2016.06.11.3

You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.
