### ISSUE TITLE
my issue..

### ISSUE THREAD

**Issue by helperornot** [rg3/youtube-dl#9941]
## During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\new\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 244, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\Users\new\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\bot.py", line 619, in on_message
    yield from self.process_commands(message)
  File "C:\Users\new\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\bot.py", line 611, in process_commands
    yield from command.invoke(ctx)
  File "C:\Users\new\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 384, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\new\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 47, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\new\AppData\Local\Programs\Python\Python35-32\cmnd.1.py", line 741, in p
    player = await voice.create_ytdl_player(string)
  File "C:\Users\new\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\voice_client.py", line 475, in create_ytdl_player
    info = yield from self.loop.run_in_executor(None, func)
  File "C:\Users\new\AppData\Local\Programs\Python\Python35-32\lib\asyncio\futures.py", line 358, in __iter__
    yield self  # This tells Task to wait for completion.
  File "C:\Users\new\AppData\Local\Programs\Python\Python35-32\lib\asyncio\tasks.py", line 290, in _wakeup
    future.result()
  File "C:\Users\new\AppData\Local\Programs\Python\Python35-32\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\Users\new\AppData\Local\Programs\Python\Python35-32\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\new\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 691, in extract_info
    self.report_error(compat_str(e), e.format_traceback())
  File "C:\Users\new\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 550, in report_error
    self.trouble(error_message, tb)
  File "C:\Users\new\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 520, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\new\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 995, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\new\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 910, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "C:\Users\new\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 973, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "C:\Users\new\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\jsinterp.py", line 241, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
youtube_dl.utils.ExtractorError: Could not find JS function 'wr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Could not find JS function 'wr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.
