### ISSUE TITLE
ESPN 30 for 30 shorts (HTTP Error 400)

### ISSUE THREAD

**Issue by troych** [rg3/youtube-dl#9942]
Looks like this should be working, at least I see from previous bug reports that it was fixed at some point. Any more infos I can provide? You don't need an ESPN account for those, freely available for everyone.

```
youtube-dl --verbose --ignore-errors http://espn.go.com/video/clip?id=15507776
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'--ignore-errors', u'http://espn.go.com/video/clip?id=15507776']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.06.27
[debug] Python version 2.7.3 - Linux-3.5.0-45-generic-i686-with-Ubuntu-12.10-quantal
*** stack smashing detected ***: rtmpdump terminated
[debug] exe versions: avconv 0.8.6-6, avprobe 0.8.6-6, ffmpeg git-2013-02-10-cf8d9b7, ffprobe git-2013-02-10-cf8d9b7, rtmpdump 2.4
[debug] Proxy map: {}
[ESPN] clip?id=15507776: Downloading webpage
[ESPN] 15507776: Downloading webpage
[OoyalaExternal] 15507776: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 390, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1950, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 407, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 520, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 445, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 379, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 528, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

ERROR: 'NoneType' object has no attribute 'copy'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 687, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 752, in process_ie_result
    new_result = info.copy()
AttributeError: 'NoneType' object has no attribute 'copy'
```

**Comment by dstftw** [comment]
Post the output of `youtube-dl --dump-pages http://espn.go.com/video/clip?id=15507776`.

**Comment by troych** [comment]
Thanks for that, the problem was indeed on my end ooyala was being redirected on a dns level. That didn't show up with the verbose option but I could now see it with dump-pages. Sorry for wasting your time.
