### ISSUE TITLE
Audiomack: ERROR Failed to parse JSON  (caused by ValueError('Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by sunk818** [rg3/youtube-dl#9949]
c:\>youtube-dl -v http://www.audiomack.com/song/raiderhader/vision-9-14-1992-side-a-b

[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.audiomack.com/song/raiderhader/vision-9-14-1992-side-a-b']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2016.06.27
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-80011-gaf3e944, ffprobe N-80011-gaf3e944, rtmpdump 2.4
[debug] Proxy map: {}
[audiomack] raiderhader/vision-9-14-1992-side-a-b: Downloading JSON metadata
ERROR: raiderhader/vision-9-14-1992-side-a-b: Failed to parse JSON  (caused by ValueError('Expecting value: line 1 column 1 (char 0)',)); please report this iss
ue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and
 include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmppxjfb828\build\youtube_dl\extractor\common.py", line 545, in _parse_json
  File "C:\Python\Python34\lib\json\__init__.py", line 318, in loads
  File "C:\Python\Python34\lib\json\decoder.py", line 343, in decode
  File "C:\Python\Python34\lib\json\decoder.py", line 361, in raw_decode
ValueError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmppxjfb828\build\youtube_dl\extractor\common.py", line 545, in _parse_json
  File "C:\Python\Python34\lib\json\__init__.py", line 318, in loads
  File "C:\Python\Python34\lib\json\decoder.py", line 343, in decode
  File "C:\Python\Python34\lib\json\decoder.py", line 361, in raw_decode
ValueError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmppxjfb828\build\youtube_dl\YoutubeDL.py", line 676, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmppxjfb828\build\youtube_dl\extractor\common.py", line 343, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmppxjfb828\build\youtube_dl\extractor\audiomack.py", line 56, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmppxjfb828\build\youtube_dl\extractor\common.py", line 539, in _download_json
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmppxjfb828\build\youtube_dl\extractor\common.py", line 549, in _parse_json
youtube_dl.utils.ExtractorError: raiderhader/vision-9-14-1992-side-a-b: Failed to parse JSON  (caused by ValueError('Expecting value: line 1 column 1 (char 0)',
)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl w
ith the --verbose flag and include its complete output.

**Comment by yan12125** [comment]
Works fine for me. Could you run the following command:
```
youtube-dl -vF http://www.audiomack.com/song/raiderhader/vision-9-14-1992-side-a-b --dump-pages
```
And post the output?

**Comment by yan12125** [comment]
Closing as no response for long time and most likely it's a network issue.

**Comment by sunk818** [comment]
I just tried the link again and worked fine. Thanks for following up.
