### ISSUE TITLE
ERROR: Signature extraction failed: Traceback (most recent call last):

### ISSUE THREAD

**Issue by val0x00ff** [rg3/youtube-dl#9959]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.06.27*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ ] I've **verified** and **I assure** that I'm running youtube-dl **2016.06.27**

### Before submitting an *issue* make sure you have:
- [ ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```

youtube-dl -v "https://www.youtube.com/watch?v=ccrP2SCThuo&list=PL6Kl613mmSRi-stBFOWf9Hc_GuQ4uHZoI"
[debug] System config: [u'--prefer-free-formats']
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=ccrP2SCThuo&list=PL6Kl613mmSRi-stBFOWf9Hc_GuQ4uHZoI']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.06.03
[debug] Python version 2.7.5 - Linux-3.10.0-327.18.2.el7.x86_64-x86_64-with-redhat-7.2-Nitrogen
[debug] exe versions: ffmpeg 2.6.8, ffprobe 2.6.8
[debug] Proxy map: {}
[youtube:playlist] Downloading playlist PL6Kl613mmSRi-stBFOWf9Hc_GuQ4uHZoI - add --no-playlist to just download video ccrP2SCThuo
[youtube:playlist] PL6Kl613mmSRi-stBFOWf9Hc_GuQ4uHZoI: Downloading webpage
[download] Downloading playlist: Tom Rosenthal - The Best Of (Which is pretty much everything he writes)
[youtube:playlist] playlist Tom Rosenthal - The Best Of (Which is pretty much everything he writes): Downloading 45 videos
[download] Downloading video 1 of 45
[youtube] ccrP2SCThuo: Downloading webpage
[youtube] ccrP2SCThuo: Downloading video info webpage
[youtube] ccrP2SCThuo: Extracting video information
[youtube] {22} signature length 40.45, html5 player en_US-vflOfyD_m
[youtube] ccrP2SCThuo: Downloading player https://s.ytimg.com/yts/jsbin/player-en_US-vflOfyD_m/base.js
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 995, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 910, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 973, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/lib/python2.7/site-packages/youtube_dl/jsinterp.py", line 241, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
ExtractorError: Could not find JS function u'wr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Could not find JS function u'wr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 995, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 910, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 973, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/lib/python2.7/site-packages/youtube_dl/jsinterp.py", line 241, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
ExtractorError: Could not find JS function u'wr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 676, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 341, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 1568, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 1005, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 995, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 910, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 973, in _parse_sig_js
    initial_function = jsi.extract_function(funcname)
  File "/usr/lib/python2.7/site-packages/youtube_dl/jsinterp.py", line 241, in extract_function
    raise ExtractorError('Could not find JS function %r' % funcname)
ExtractorError: Could not find JS function u'wr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Could not find JS function u'wr'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* required an account credentials please provide them or explain how one can obtain them.

**Comment by dstftw** [comment]
>[debug] youtube-dl version 2016.06.03

You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.
