### ISSUE TITLE
SIXplay not working with some links

### ISSUE THREAD

**Issue by wwark** [rg3/youtube-dl#9979]
Hello,

I will open this issue like you ask. Not all links working on this url https://www.6play.fr/

The issue is

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://www.6play.fr/kaamelott-p_888/livre-i-tome-i-episodes-1-a-15-p_1632', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.07.01
[debug] Python version 2.7.12rc1 - Linux-4.6.0-1-amd64-x86_64-with-debian-stretch-sid
[debug] exe versions: ffmpeg 3.0.2-4, ffprobe 3.0.2-4, rtmpdump 2.4
[debug] Proxy map: {}
[generic] livre-i-tome-i-episodes-1-a-15-p_1632: Requesting header
WARNING: Falling back on generic information extractor.
[generic] livre-i-tome-i-episodes-1-a-15-p_1632: Downloading webpage
[generic] livre-i-tome-i-episodes-1-a-15-p_1632: Extracting information
ERROR: Unsupported URL: http://www.6play.fr/kaamelott-p_888/livre-i-tome-i-episodes-1-a-15-p_1632
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/extractor/generic.py", line 1481, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "./youtube-dl/youtube_dl/compat.py", line 2524, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "./youtube-dl/youtube_dl/compat.py", line 2513, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 15, column 61
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 676, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 343, in extract
    return self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/generic.py", line 2182, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.6play.fr/kaamelott-p_888/livre-i-tome-i-episodes-1-a-15-p_1632

Thanks for you help,
Regards

**Comment by wwark** [comment]
Issue fixed with #12011
